### ISSUE TITLE
False Positive on Virustotal

### ISSUE THREAD

**Issue by danne2** [ShareX/ShareX#1002]
https://www.virustotal.com/en/file/50229feeef4a58547cba5dc5648757bf7e26eb8975ce7ea1c69f3be4fbaa6232/analysis/1442692303/

Might want to get that resolved.

**Comment by Jaex** [comment]
How am I supposed to solve it. They don't have english page. I don't know Chinese.

**Comment by trdwll** [comment]
If you want to try, you could contact VirusTotal using this form. https://www.virustotal.com/en/about/contact/

**Comment by Jaex** [comment]
What VirusTotal to do with it?

**Comment by trdwll** [comment]
VirusTotal is a virus scanning tool. Someone scanned ShareX and it picked up as a false positive.

**Comment by Jaex** [comment]
VirusTotal not picked up as false positive. Jiangmin picked it up as false positive.

**Comment by trdwll** [comment]
Oh yeah. Derp, just realized that.

**Comment by davidruhmann** [comment]
Here are some contact emails for Jiangmin
>Personal Products Services E-mail: support@jiangmin.com
>Enterprise Products Services E-mail: kvnet@jiangmin.com
