### ISSUE TITLE
Self-updating of portable version

### ISSUE THREAD

**Issue by aph3rson** [ShareX/ShareX#1003]
Right now, the portable version doesn't appear to auto-update. Instead, the full installer is downloaded, and/or (can't remember) you are sent to the releases page on GitHub.

Would it be possible for this to happen?

**Comment by Jaex** [comment]
It would be too much work. Because normal updating system relies on installer but portable not using installer.

**Comment by StoopidoMan** [comment]
@Jaex If I am wrong please correct me: 

This is the solution to keep your settings or configurations when updating the portable version:

ShareX , configuration, settings, and screenshots are stored in `ShareX` folder. Basically, all user data.

And this folder is not inside the downloaded zip file `ShareX-portable.zip` which can be found [here ](https://github.com/ShareX/ShareX/releases) if you want to update ShareX portable version.

Simply: 
1- first check if there is a `ShareX` folder inside the zip file  `ShareX-portable.zip`.
2- extract the content of  zip file `ShareX-portable.zip`  to where the old version reside and replace all files. 
3- that is it.
