### ISSUE TITLE
An option to move or remove cursor after capturing, like in Greenshot

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ShareX/ShareX#1009]
After capturing and opening the image editor, Greenshot allows to move or remove the mouse cursor. ShareX doesn't seem to have this option. It would be great if it would allow to do that too, that's the only feature I'm missing after moving from Greenshot.

http://i.imgur.com/wgc3X01.png

**Comment by Jaex** [comment]
That won't be possible because ShareX outputs image with cursor in it. I mean if I output without cursor then other after capture tasks can have issues because there is no cursor in it. So it will be complicated.

**Comment by justanotheranonymoususer** [comment]
Complicated is not impossible. Why close the issue? After all, Greenshot does this.

I don't care about other after capture tasks, so how about adding an option:
1. (current option) always capture cursor.
2. don't capture cursor, and if opening editor, add it as a movable object.

**Comment by Jaex** [comment]
I closed this issue because I was not planning to implement it. I can't implement every single request unfortunately. And you have no idea about difficulties it can create.

**Comment by justanotheranonymoususer** [comment]
OK, but the project is open source, and somebody else might implement it.

**Comment by Jaex** [comment]
If I let every single features I was not planning to implement open then issues section fills with them a lot and it makes difficult for me to find things which I was planning to implement or fix.

**Comment by justanotheranonymoususer** [comment]
OK, it's up to you. In any case, thanks for ShareX!

**Comment by qdi-jeffd** [comment]
Hey... sorry I had looked through the open issues before submitting #1782 but did not look through closed issues. After reading through this issue though, you can add to the list of user's that think this should be open for someone else to take on as it would be a very cool feature to add in.

It could be added as a sub option to the existing option (something like "Allow Cursor re-positioning in Editor") that would only apply to the image sent to the editor, all other after capture destinations could just adhere to the existing option whether or not to capture the cursor.

But that is just my random thoughts, whether you choose to act on this or not ShareX is an awesome tool and thank you for the work that you do on it!

**Comment by Venryx** [comment]
I would also find this really useful! A number of nice screenshots have been ruined because I had my mouse over it, and the data was no longer available to take a new one.

**Comment by BurningRaptor** [comment]
Hope to implement this feature. Mouse cursor is sometimes annoying

**Comment by vctls** [comment]
Since there is now an option to avoid capturing the cursor, it would just be a matter of adding a set of of cursor images to the region capture tool.
You can already do it with the standard "Drawing: Image" tool and a couple png files.

**Comment by vctls** [comment]
Here, you can try with those: http://telcontar.net/Misc/screeniecursors/

**Comment by vctls** [comment]
I even did a capture of the capture for you:
![2017-06-19_17-36-23](https://user-images.githubusercontent.com/18054077/27293210-05937778-5516-11e7-9f13-4863bd336931.gif)

**Comment by qdi-jeffd** [comment]
That is actually a good work around, I wish I had thought of it sooner. Thanks Victor!

**Comment by Jaex** [comment]
Added cursor move & delete support to ShareX region capture annotation: https://gfycat.com/PortlyReliableBison

**Comment by vctls** [comment]
Thanks, @Jaex !

**Comment by Scrxtchy** [comment]
👀 wat

**Comment by BurningRaptor** [comment]
THANKS!

**Comment by qdi-jeffd** [comment]
Sweet! Thanks!

**Comment by justanotheranonymoususer** [comment]
@Jaex with the new windowed annotation window, can this feature be enabled for the annotation window, too?
