### ISSUE TITLE
All settings lost

### ISSUE THREAD

**Issue by singh-jaspal** [ShareX/ShareX#1010]
Last thing I did was run it in administrator to change a folder, rebooted a couple hours later and all of my settings were reset to the defaults.

**Comment by Jaex** [comment]
If you changed folder where settings stored then settings won't be moved to this new folder. So your settings not lost you just didn't moved them?

**Comment by singh-jaspal** [comment]
Oh, I didn't know that those were stored in there as well. Fixed it, thank you.
