### ISSUE TITLE
[request] Increase image size in history dialogue

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#1011]
Please in history dialogue add splitter under image for increase image size

![2015-09-25_15-43-38_svqu4k5h](https://cloud.githubusercontent.com/assets/1897605/10100878/48c9d1c0-639d-11e5-90a6-88bcfa530a01.png)

**Comment by davidruhmann** [comment]
Does the image preview need to be bigger?  Why not just click on the preview to see it bigger?  Or use the Image History window for a visual browse?

**Comment by McoreD** [comment]
@QuAzI as @davidruhmann suggested please click on the image to view it full screen. That's the biggest you will ever see.

**Comment by QuAzI** [comment]
I use this program since the beginning 2014 and have many same screens gathered and it isn't convenient to look for among them the necessary screen opening each file in a new window. The behavior as at the main window there is a wish
