### ISSUE TITLE
Is there a way to upload a gifv to imgur?

### ISSUE THREAD

**Issue by ipoisonxl** [ShareX/ShareX#1012]
I know I can upload a webm to gfycat, but can I do the equivalent for imgur instead?

**Comment by Jaex** [comment]
Imgur not supports uploading videos. Converts gif to gifv if gif is big.

**Comment by ipoisonxl** [comment]
Can I upload a GIF to imgur with the same efficiency as if I uploaded a video to GFYcat?

**Comment by Jaex** [comment]
Yes. But Imgur have 10mb gif limit in API which is big problem.

**Comment by ipoisonxl** [comment]
So when I encode a GIF in 60fps it will take the same time as if I did a video in 60fps?

**Comment by Jaex** [comment]
GIF not even supports 60 fps in browsers...

**Comment by ipoisonxl** [comment]
Oh ok. So I can't make a 60fps gifv?

**Comment by Jaex** [comment]
You can't.

**Comment by ipoisonxl** [comment]
Okay. Thank you so much!
