### ISSUE TITLE
After capture actions are performed for upload tasks

### ISSUE THREAD

**Issue by DoumanAsh** [ShareX/ShareX#1013]
Subj.
Noticed that in version 10.2.5

This is a portable version which was upgraded over previous by saving all settings.

I make screenshot. Action run.
After that i issue upload. Action run and only after that upload starts.

**Comment by Jaex** [comment]
Check these settings to disable or enable them:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/ShareX.vshost_eyVebuB2EY.png)

So these was actually feature and not bug.

**Comment by DoumanAsh** [comment]
Oh... thank you. I'm sorry that i wasn't attentive.
Though i think such setting would be better moved into Upload section
