### ISSUE TITLE
FFmpeg related issues

### ISSUE THREAD

**Issue by singh-jaspal** [ShareX/ShareX#1014]
It keeps asking to download FFmpeg when I try to use the Shortcut to utilize screen recording. 

When clicking on any of the windows that follow afterwards, it will try to take a screenshot (which I can escape out of, and a minor annoyance only).

**Comment by Jaex** [comment]
So even if you downloaded FFmpeg it still asks? Also there is no code to take screen capture in screen recording selection, so how it is possible?

**Comment by singh-jaspal** [comment]
Yes. That's precisely it. 
![image](https://cloud.githubusercontent.com/assets/12993901/10128101/64ef3284-6562-11e5-8401-0143ba66dadc.png)
 

I honestly have no idea.

**Comment by Jaex** [comment]
So did you checked that folder is file exist?

**Comment by singh-jaspal** [comment]
Yes, it's in the tools folder and is around 35mb.

**Comment by Jaex** [comment]
In here what path is selected:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/ShareX_WC8bAIxeEe.png)

**Comment by singh-jaspal** [comment]
It has the same path as the one in the window I pasted earlier.

![image](https://cloud.githubusercontent.com/assets/12993901/10128200/2deaf474-6564-11e5-946b-95fd04a4a766.png)

**Comment by Jaex** [comment]
It tells that file not exist. So how it could be exist?

**Comment by singh-jaspal** [comment]
It was downloaded to the same desination before, so I'm not really sure how it worked right after the download, or how it was deleted the next time around for some reason.

**Comment by Jaex** [comment]
Main reason why people have this issue is FFmpeg path is empty by default and after download FFmpeg this path is set to where it is downloaded. But because Windows shutdown without wait for ShareX to save settings. This FFmpeg path not saves so in next ShareX start because FFmpeg path is empty it asks for re download. I will set default path to proper FFmpeg path by default so even if setting fail atleast it will have proper path set.

**Comment by weberankit** [comment]
hey everyone those who are facing issues related to ffmpeg just follow this video your problem will be solved (worked for me)
https://www.youtube.com/watch?v=BcaYRb7TElo
