### ISSUE TITLE
[Request] please add this function

### ISSUE THREAD

**Issue by umbertoB67** [ShareX/ShareX#1015]
I'm using Fastone Capture but I've discovered ShareX that has more options.
Why don't you add the effect used  in Fastone Capture called "Edge" (see screenshot)?
![2015-09-28_151511](https://cloud.githubusercontent.com/assets/10993001/10136259/d92c2b7a-65f3-11e5-8c8a-4e984ddde9ee.jpg)

**Comment by Jaex** [comment]
It is already exists:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/ShareX_q52FA2ut5C.png)
