### ISSUE TITLE
Can't upload to maxfile

### ISSUE THREAD

**Issue by riesza** [ShareX/ShareX#1016]
unfortunately I can't say if this is a problem on their end or on Sharex' but this is what I get when I try uploading something to maxfile:

![untitled-1](https://cloud.githubusercontent.com/assets/1399263/10142144/2dd5c5f6-6611-11e5-8af3-83d8c63f8dbe.png)

Uploading files through https://maxfile.ro/ works fine and other image hosts work fine through Sharex also.

**Comment by Jaex** [comment]
It tells internal server error so it can't be to do with ShareX.

**Comment by Scrxtchy** [comment]
For what it's worth
They're down completely
![](http://sharex.moe/i/2015/09/15-09-29_21-07-19.png)
