### ISSUE TITLE
Drag button

### ISSUE THREAD

**Issue by Nikolai-Nikostine** [ShareX/ShareX#1023]
I would looooove if ShareX had a (drag) function just like Skitch from Evernote
In the picture below, the function is shown
Really hope you will consider adding this feature :)

![image](https://cloud.githubusercontent.com/assets/14924813/10221001/a7387f24-684b-11e5-82b9-624723ee6699.png)

**Comment by Jaex** [comment]
I don't know what is drag function and that picture not explains too.

**Comment by Nikolai-Nikostine** [comment]
Sorry, I will try to explain the function

If you pull the button that says "Træk mig"(Drag Me in english) you can insert the image you just took in a program, just as if you drag an image from a folder in to a program.

It allows, for example. you can add screenshots (you just have taken) using drag and drop to Todoist.com. Rather than having to save them locally first.

**Comment by Jaex** [comment]
I was tried to make it dragable but because you can also drop to main window, people could drag and drop to same place and re upload image. I couldn't make it not dropable to same window where you started dragging therefore I was gave up.

**Comment by Nikolai-Nikostine** [comment]
Bummer :(

Can understand the problem, but hope there is someone or you, finds a solution at one time :)

**Comment by Jaex** [comment]
You can right click and copy -> Image as workaround. Probably it can work where dragging accepted.

**Comment by Nikolai-Nikostine** [comment]
Thank you, but it do not work with Todoist.com but I wonder if they will soon do so it can be done

**Comment by kolchan11** [comment]
+1

**Comment by Jaex** [comment]
It was easier than what I thought. When drag start I disable main window drop support. And when drag from list is stopped (this is where I couldn't figure out before but there was `QueryContinueDrag` event which easily supply this info to me) then I re enable drop support in main window.

**Comment by Jaex** [comment]
I was just added file drag support but maybe I should also add bitmap drag support with modifier like holding shift when dragging?

**Comment by YasseenDeHerdt** [comment]
Thank you for this. I love ShareX.
