### ISSUE TITLE
Pomf.Cat added as default destination

### ISSUE THREAD

**Issue by kp1993** [ShareX/ShareX#1029]
I own a pomf.cat clone cause sadly, pomf.se was shutdown, and I was wondering if I could get it added as a default ShareX config. The config is at https://pomf.cat/sharex.txt, we get roughly half a tb of bandwidth per day and ~500k requests a day (for if there is a requirement), and I was one of the many voters for the steam greenlight page <3

**Comment by Scrxtchy** [comment]
as the name implied

is it a fork of pomf.se?

**Comment by kp1993** [comment]
Yes it is

**Comment by Scrxtchy** [comment]
![](https://a.pomf.cat/jkevnu.png)

Done, just need to PR it

**Comment by kp1993** [comment]
PR?

**Comment by kp1993** [comment]
oh, pull request

**Comment by kp1993** [comment]
ok thanks.

**Comment by Jaex** [comment]
@kp1993 Pomf destination in ShareX now defaults to pomf.cat therefore no need to write custom uploader settings in https://pomf.cat/tools.html anymore.

**Comment by kp1993** [comment]
Thanks. Will remove when I'm home
