### ISSUE TITLE
[Question] How to reset to default Magnifier Pixel Count and Size?

### ISSUE THREAD

**Issue by wilflare** [ShareX/ShareX#1032]
Sorry to bother but is there any way to do the following?
- Reset to default Magnifier Pixel Count
- Reset to default Magnifier Pixel Size

Thank you

**Comment by Jaex** [comment]
There is no way to reset specific setting. These are default values:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/10/ShareX_UclfyWajGt.png)
