### ISSUE TITLE
S3 undersierable Cache-Control

### ISSUE THREAD

**Issue by Glitchvid** [ShareX/ShareX#1033]
When uploading to S3 objects are stored with the header "Cache-Control: no-store,no-cache".

This is undesirable as it will result in nonexistent caching from a CDN.  At least a check-box to disable storing with this header would be desired.

**Comment by Jaex** [comment]
@alanedwardes

**Comment by alanedwardes** [comment]
I would assume this is a default coming from S3 itself or the C# SDK.

Can you explain your use case? Bear in mind ShareX is not a general purpose S3 uploading tool, it is a screenshot sharing application.

Cheers

On 3 Oct 2015 7:51 pm, Jaex <notifications@github.com> wrote:

@alanedwardes<https://github.com/alanedwardes>

**Comment by Glitchvid** [comment]
My use case, and I suspect it's a pretty common one, is to use it for screencaps and then post on forums (E.G: Facepunch, Neogaf). 
Images rarely change and greatly benefit from proper caching on both the server and client end in these situations, which no-store,no-cache effectively disables.  
*Specifically* this makes all requests to my sharex uploads a miss, rendering cloudfront/CDNs pointless.
![90% Miss rate](https://s.gvid.me/s/2015/10/03/00Y616.png)
![Top objects miss](https://s.gvid.me/s/2015/10/03/JHo425.png)

To reiterate, this is important *because* ShareX is a screenshot sharing application, if I was using it to just store objects in S3, then the caching behavior wouldn't matter.

**Comment by alanedwardes** [comment]
This appears to be a limitation in the ShareX upload code: https://github.com/ShareX/ShareX/blob/454e64569a6049ca353020d45fdcb8c3523e7334/ShareX.UploadersLib/Uploader.cs#L392

I don't want to refactor that to fix this specific issue.

As a side note, you can instruct CloudFront to orderride the `Cache-Control` header, check the TTL settings on your CloudFront distribution:

![2015-10-04_15-57-40](https://cloud.githubusercontent.com/assets/110954/10268450/b50f9184-6ab0-11e5-8b4d-9b2ee70e4622.png)

I was able to force a minimum TTL with an object that had the `Cache-Control: no-cache` header set, and have CloudFront consider it cacheable:

![2015-10-04_15-59-00](https://cloud.githubusercontent.com/assets/110954/10268453/daa1bef4-6ab0-11e5-9873-1e8fb4a41475.png)

Cheers

**Comment by Glitchvid** [comment]
It's a sub optimal workaround, fortunately it can be done per-origin, making it feasible.  I hope this eventually gets changed, but for now this works.

Thanks for looking into it.

**Comment by Jaex** [comment]
I can't remember why I was added no-cache, it was long time ago someone was requested it I think. So can't remove it because it was solving something which I can't remember currently.
