### ISSUE TITLE
Capture area extends outside window area desktop: Input/output error

### ISSUE THREAD

**Issue by SoyG** [ShareX/ShareX#1035]
I keep getting this error popup as a DOS box when I try Screen Recording GIF. I select the top left corner so it highlights my desktop, but this pops up immediately: 

`[gdigrab @ 000000a816239920] Capture area (0,0),(1920,1080) extends outside window area (0,0),(1280,720)desktop: Input/output error`

This happens with any window that's over 1280x720. I checked the FFMpeg setting, and the command is:

`-y -rtbufsize 100M -f gdigrab -framerate 20 -offset_x 0 -offset_y 0 -video_size 1920x1080 -draw_mouse 1 -i desktop -c:v libx264 -r 20 -preset veryfast -tune zerolatency -crf 30 -pix_fmt yuv420p "output.mp4"`

When I click Test, I get the same error message.

**Comment by Jaex** [comment]
#923

**Comment by SoyG** [comment]
1920x1080 is considered hi DPI?
I'm running Windows 10, hooked up to an older HD TV (1080P). DPI is far lower than a monitor

**Comment by Jaex** [comment]
FFmpeg detects your resolution as 1280x720 so it is not fault of ShareX.
