### ISSUE TITLE
Computer freezes up after using full desktop screenshot.

### ISSUE THREAD

**Issue by meowxi** [ShareX/ShareX#1036]
What the title says.
As soon as I hit the Print button to capture the whole desktop my PC freezes up and I have to reboot it via power button. I don't know, why this is happening.

**Comment by Jaex** [comment]
Fullscreen capture codes not changed for years and I never heard ShareX can freeze anyones computer. So I have no clue why it happens to you. I mean even intentionally I can't manage to freeze computer. Something in your computer must be causing it.

**Comment by meowxi** [comment]
I'm just gonna try to reinstall ShareX. Maybe my installation is broken or something!
