### ISSUE TITLE
Is it possible to auto-save a file after edition?

### ISSUE THREAD

**Issue by wsw70** [ShareX/ShareX#1039]
Hello

I automatically save an image of a screenshot upon capturing, then automatically open the edition window.
Is it possible to automatically force the save of the edited image under the same name when closing (so that there is no `"Save as..."` message)?

Thank you
Wojtek

PS; I just discovered XShare and it truly rocks, compared to many similar solutions.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/10/ShareX_Upbsjb9gtj.png)

**Comment by wsw70** [comment]
Thank you - I missed that because I closed the window though the upper-right 'x'. A possible entry to the wish-list would be to be able to close with auto save by using the close button of the window (which now triggers a `Save as...'`.

**Comment by uperendi** [comment]
yes, this is a problem. It should save even image editor is opened. even tasks are cancelled, save should be automatically. i dont want to press "Ok, Enter, tickbox" each screenshot in the editor for it to be saved.

**Comment by baxenko** [comment]
Same problem. Someone decided?

**Comment by delta4957** [comment]
Same problem here.

**Comment by delta4957** [comment]
Same issue here.
Appreciate it if someone found a solution.
