### ISSUE TITLE
Mouse Click Effect During Recording

### ISSUE THREAD

**Issue by Mwr247** [ShareX/ShareX#1040]
A common feature among some screen recorders is to offer an option to add a click indicator effect during recording, so that the viewer can see if/when the mouse has been clicked somewhere on the screen. The effect can be anything from a change in cursor (size, shape, color, angle, etc) to an external effect (expanding rings, etc).

Would this be possible to implement as an option in ShareX? I use recordings to demo features in website development, and it would be useful if it could indicate when the mouse is pressed down (for things like dragging and etc).

**Comment by Jaex** [comment]
Because FFmpeg doing all recording I don't have any control on it to draw click effects to it.

**Comment by YerayAlonso** [comment]
I understand this cannot be done through the recording itself, but if there are programs that can add animations to the system mouse pointer/keyboard pressing, maybe something similar could be activated at the start of the recordering and stopped at the end.
If this was possible, it should also work for gif.

This program seems to do it, but it's not opensource:
http://www.markuswelz.de/software/

This is only for the keyboard, not for the mouse, but it's opensource:
https://github.com/Code52/carnac

**Comment by Arsenalist** [comment]
This would be a great feature.   https://screencast-o-matic.com/home does it as well.

**Comment by bradphelan** [comment]
I've found this solution works ok
http://superuser.com/questions/106815/how-do-you-add-a-visual-effect-to-a-mouse-click-from-within-windows

sharex records the animated cursor. 

Would it be possible to perform the same trick without installing AutoHotKey?

**Comment by Stefal** [comment]
This software is open source (Apache 2.0) and should do the job:
https://github.com/Phaiax/PxKeystrokesForScreencasts

**Comment by pfrng** [comment]
With the help of pointerfocus and hiddeX it can be done, Discussed here [highlight cursor in sharex](http://www.pfrng.com/enable-sharex-cursor-highlighting/)

**Comment by Chronial** [comment]
It is completely within the rights of the author of PointerFocus to decide not to give his code away for free. Writing a guide on how to circumvent that decision and then monetizing that with advertisements is definitely not good style.

@Jaex if you agree with that, I would ask you to remove that link.

**Comment by pfrng** [comment]
As you are not happy I removed the link, But one thing you are wrong no advertisement is shown in that post

**Comment by Chronial** [comment]
thx for your consideration

**Comment by Llorx** [comment]
Do you think that is possible to add a custom overlay while we are recording the screen to show button click animations? ffmpeg will capture them.

The same as running those external tools, but instead of running them along with the capture tool manually, which is tedious, integrate it somehow in ShareX.

**Comment by Heroesflorian** [comment]
Yeah, that would really come in handy!

**Comment by gingersnapbiscuit** [comment]
I found this solution and thought I would share: https://sites.google.com/site/boisvertlab/computer-stuff/online-teaching It's part of this YouTube video for a better explanation https://www.youtube.com/watch?v=kwSqtNvT7to

Works for me, and not just for use with ShareX. I auto-launch it on startup, with it set to not show on launch (see settings) so I can toggle it on/off with hotkey controls thereafter. Barely requires a second thought after initial setup. Suits me, might suit someone else too!

**Comment by abaumgaertner** [comment]
give this a try: https://github.com/bfritscher/carnac/

**Comment by ctecho** [comment]
if you're on a windows machine you can download Microsoft Powertoys (free utility)
https://docs.microsoft.com/en-us/windows/powertoys/install

this then has a "Mouse Utilities" that includes a mouse highlighter that ShareX captures both left and right click with different colours.

**Comment by nbourre** [comment]
For the keys and mouse, I've found Key'n Stroke which shows every input from the mouse and keyboard. You can find it here : https://github.com/Phaiax/Key-n-Stroke

**Comment by leoshortik** [comment]
Hi, is there any change in record clicks directly from ShareX?

**Comment by Jaex** [comment]
https://x.com/ShareX/status/2099996175860461577
