### ISSUE TITLE
Upload Errors (Ingur)

### ISSUE THREAD

**Issue by laicore** [ShareX/ShareX#1041]
Message:
Unable to write data to the transport connection: the Remote host forcibly broke the existing connection.

StackTrace:
   в System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   в System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   в System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   в System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   в System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   в System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   в ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   в ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by trdwll** [comment]
I would assume that their servers are having too many connections. Just keep trying.

**Comment by Jaex** [comment]
Every single Imgur errors happened was something in their end. It never ShareX's fault.
