### ISSUE TITLE
ShareX keeps attempting to download ffmpeg.exe

### ISSUE THREAD

**Issue by ThePsionic** [ShareX/ShareX#1042]
When trying to do a screen recording, I always get prompted to download ffmpeg.exe because it "doesn't exist", even if I have done so before. Canceling out of the download popup starts the screen capture process as expected, so ffmpeg.exe must already be downloaded and available to do this in the first place.

**Comment by Jaex** [comment]
What is configured in here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/10/ShareX_8Bb828N9UI.png)

**Comment by SephLeague** [comment]
Can confirm, everytime i restart my computer try to record a gif, it wants to download ffmpeg.exe

**Comment by Jaex** [comment]
Without more information I can't figure out what is wrong because can't find anything wrong in codes. Example if your settings not saving then it is not to do with only FFmpeg.

**Comment by SephLeague** [comment]
After i download it it works fine until restart, http://puush.faded.me/u/uSUE.png
I don't know it might be my antivirus deleting it :-1:

**Comment by ThePsionic** [comment]
![img](http://i.imgur.com/VPMpon9.png)
Sorry for the late reply. It is exactly as @SephLeague says, ffmpeg.exe is deleted from my computer when I restart. Using Windows Defender as AV, if it matters.

**Comment by Jaex** [comment]
I don't delete any files in codes. So no idea.

**Comment by Jaex** [comment]
#1014

**Comment by Soulflare3** [comment]
I just had this problem in Windows 10 after reinstalling. Documents are defaulted to Microsoft OneDrive, and ShareX' files are there. **Make sure your paths are correct**. Mine was looking in `C:\Users\<user>\Documents\ShareX\Tools\` and the correct path was `C:\Users\<user>\OneDrive\Documents\ShareX\Tools\`. This was why it was trying to redownload every time I restarted my PC, even though I knew I had ffmpeg.

Check your configs, and then check the actual folders to make sure it's in the folder that ShareX is looking at.
