### ISSUE TITLE
"Delete From Host" Button

### ISSUE THREAD

**Issue by Kaeltis** [ShareX/ShareX#1044]
Right now, to delete an image that was uploaded to e.g. Imgur, you have to right click the image in the list and then go to "Open" -> "Deletion URL".

Would be nice to have a direct Button "Delete file from host..." next to the "Delete file locally..." button in the right click menu.

**Comment by Jaex** [comment]
That would so easy if we have only one host supported in ShareX. But with multiple host it is beyond difficult. Because need to store host specific file ids or such things. So it is more complicated then what you think.

**Comment by thro86** [comment]
> That would so easy if we have only one host supported in ShareX. But with multiple host it is beyond difficult. Because need to store host specific file ids or such things. So it is more complicated then what you think.

I've seen two of these threads and the answer is always "there are multiple hosts its a PITA to implement it for all the hosts"

Ok so can we please just have support for whichever site is the most used? Imgur for Example? If we need to take a poll fine, but I'll bet money it's going to be imgur. Then someone can simply sort by URL in ShareX, then highlight ALL the imgur links and right click remove from host or w/e.

What do you need as far as time or money to outsource this functionality? I'm willing to throw money at this as it's insanely useful and time saving.
