### ISSUE TITLE
Automator's MouseMove breaks when given negative values

### ISSUE THREAD

**Issue by ClintonFlowers** [ShareX/ShareX#1048]
Automator's MouseMove breaks when given negative values-

My monitors are currently set up so that my "primary monitor" is on the right. When I click "Add cursor position", and have my mouse anywhere on my left monitor, the X position parameter is negative, and the function does not work. I believe this is breaking the function, as when I set my left monitor as my primary, all the resulting X coordinates are positive, and I do not have the issue. 

Example- http://i.imgur.com/b1emDIu.gifv

Thanks

**Comment by Jaex** [comment]
Wait 2000
MouseMove -500 -500
MouseMove 500 500

I tried this and it not breaks and move mouse to 500 500. I don't have multi monitor so I can't test is it moves to negative.

**Comment by Jaex** [comment]
But I noticed in codes now it not parsing negative number properly.
