### ISSUE TITLE
Active window screenshot doesn't always use transparency

### ISSUE THREAD

**Issue by tylercrumpton** [ShareX/ShareX#1054]
I'm having trouble taking screenshots of full windows with transparency enabled. Taking screenshots of the active window sometimes results in a beautiful, transparent, rounded-corner image like this:
![sharex_10 3_2015-10-08_17-44-06](https://cloud.githubusercontent.com/assets/1317406/10381970/c50910ec-6de4-11e5-859c-fa4546667397.png)

But other times, I get an ugly, non-transparent, black-corner image like this:
![sharex_10 3_2015-10-08_17-44-15](https://cloud.githubusercontent.com/assets/1317406/10381977/d9022de0-6de4-11e5-9be1-cbb71e70d1a0.png)

These results will happen right after each other with out changing anything, moving the mouse, or otherwise. If I keep taking screenshots, I'll usually eventually get a good transparent image.

On some windows still, I can't even get it to even do the transparent window.

Any thoughts?

**Comment by Jaex** [comment]
ShareX takes multiple images to calculate transparency. If something change between these captures then it fails. Because it compares first and last capture to make sure nothing changed on screen. So calculations can be correct. Also it can be timing problem too. So it is difficult to make it perfect. In some computers it works always in some it fails more.

**Comment by tylercrumpton** [comment]
Makes sense, thanks!

**Comment by hatifnatt** [comment]
Is it possible to make an option to force fill background with white color as it happens when transparency fails? I can make bunch of images with failed transparency, but suddenly it start working and as result I have differently looking screenshots.

**Comment by Jaex** [comment]
If it fails then it using first captured image which have white background.

**Comment by sergeevabc** [comment]
Year is 2021 and this issue is still relevant.
E.g. I switch on Windows 7 Basic theme and invoke Calculator against the orange background…

![](https://i1.imageban.ru/out/2021/04/19/8d36f62c80d61ddc467ccf76b5d014ed.png)

**Comment by Jaex** [comment]
> Year is 2021 and this issue is still relevant. For example, I switch on Windows 7 Basic theme and invoke Calculator against the orange background… colored corners are there. Then I switch to Windows 7 Aero theme and… corners are still visible.

Year is 2021 and people still using Windows 7.

**Comment by sergeevabc** [comment]
> Year is 2021 and people still using Windows 7.
Yes, people use Windows 7, simply because IT WORKS, contrary to what some greedy Silicon Valley companies say.
It is 64-bit stable, studied, and aesthetically pleasing OS for homes and offices around the globe for the near future. 
Instead of being sarcastic, mind your part in this story, because your piece of software DOES NOT work as expected.

**Comment by Jaex** [comment]
> > Year is 2021 and people still using Windows 7.
> 
> Yes, people use Windows 7, simply because IT WORKS, contrary to what some greedy Silicon Valley companies say.
> It is 64-bit stable, studied, and aesthetically pleasing OS for homes and offices around the globe for the near future.
> Instead of being sarcastic, mind your part in this story, because your piece of software DOES NOT work as expected.

Obviously I couldn't manage to fix it, so saying "Year is 2021" not makes any difference either. If anyone can fix it then feel free to pull request.

**Comment by sergeevabc** [comment]
@Jaex, I examined it further via [tips][1] on Stackoverflow and here are my observations.

A. Desktop composition and shadows are enabled, Capture-Window-Calculator. (Region capture failed to preserve transparency.)

![](https://i2.imageban.ru/out/2021/04/19/5bdf340c31616e9ca610f3d2b6457a67.png) ![](https://i1.imageban.ru/out/2021/04/19/4609e82407895ee0a1c1d4180cbc8972.png)

B. Shadows are disabled. As you can see, corners are transparent, yet some white pixels overlap the black frame.

![](https://i4.imageban.ru/out/2021/04/19/b84fd6389bd8e5ebd153f038af25a01b.png)

C. Shadows and desktop composition are disabled. There is no black frame at the bottom.

![](https://i6.imageban.ru/out/2021/04/19/8c5b09b48804cad69c49a7f0996193a9.png)

D. Bonus. The same setup as C, but captured via Alt+PrtScr (capture active window). Frame is OK, but corners and buttons are not.

![](https://i6.imageban.ru/out/2021/04/19/0b934d2ec807ae0682cd934b65f46aef.png)

[1]: https://stackoverflow.com/questions/2986508/taking-screenshots-in-windows-vista-windows-7-with-transparent-areas-outside-t?rq=1
