### ISSUE TITLE
Support for custom S3 Servers

### ISSUE THREAD

**Issue by Centzilius** [ShareX/ShareX#1058]
I'd like to add a custom S3 Server but although this pull request states "Added support for custom Amazon S3 endpoints[...]" I can't find the option to add a custom server.

**Comment by Jaex** [comment]
I can't find too. Probably it meant custom server support inside codes.

**Comment by Jaex** [comment]
@alanedwardes would you like to consider adding it or it is too much work?

**Comment by alanedwardes** [comment]
Hi,

Can you tell me a bit more about your use case?

Thanks



On Sun, Dec 27, 2015 at 10:16 AM -0800, "Jaex" <notifications@github.com<mailto:notifications@github.com>> wrote:


@alanedwardes<https://github.com/alanedwardes> would you like to consider adding it or it is too much work?

-

**Comment by Centzilius** [comment]
@alanedwardes (Not sure if you meant me) I'd like to use a OpenStack SWIFT Server which has if I'm not mistake a S3 compatible API.

**Comment by alanedwardes** [comment]
@Centzilius Thanks. If there are other people wanting to do this I think it should be considered, but I'm afraid your use case is very specific, so I don't think it's worth adding to ShareX.

Out of interest, why do you want to host your own S3? It feels a bit crazy considering the reliability, scale and cost-effectiveness Amazon gives you. You don't have to manage infrastructure!

**Comment by Centzilius** [comment]
@alanedwardes I was planing to use OVHs Public Cloud powered by OpenStack and it's pretty cheap in my opinion
https://www.ovh.de/cloud/storage/object-storage.xml (German)
https://www.ovh.co.uk/cloud/storage/object-storage.xml (English)

**Comment by grvr** [comment]
+1 from me. There are a few services out there that use an S3 compatible API. Being able to enter a custom host would allow ShareX to work with all of them.

https://en.wikipedia.org/wiki/Amazon_S3#S3_API_and_competing_services

**Comment by alanedwardes** [comment]
@grvr Which service are you using?

**Comment by grvr** [comment]
I am using ObjSpace from Delimiter.

http://wiki.delimiter.com/display/DEL/ObjSpace%3A+Configuring+S3+Browser

**Comment by umcookies** [comment]
I'm in the same boat as grvr, so yeah, throwing some support behind custom S3 end points.

**Comment by k0nsl** [comment]
I am using a self-hosted solution which is entirely S3 compatible. I'd love to be able to use it in ShareX.

**Comment by Jaex** [comment]
Because I didn't wrote this uploader, I can't add it. Especially because if I manage to add it, I can't even test it.

**Comment by k0nsl** [comment]
I can provide you with access to my S3 instance, if you would need to test. But it doesn't sound like you know how to go about it, unless I misunderstood you.

Oh well, it would have just been a nice thing to have :)

**Comment by deansheather** [comment]
Is this still happening? If so, could you please add the AWS Ohio region? It doesn't seem to be available. Region code is `us-east-2`.

Had a look through the code and couldn't seem to find the defs.

**Comment by alanedwardes** [comment]
This should just need an AWS SDK NuGet package update, the region list is coming from there.

@jaex would you be able to bump the package version? I can try to get around to this within the next few days if not, or there was a breaking change.

Cheers!

**Comment by neurogas** [comment]
+1

**Comment by Jaex** [comment]
If Amazon S3 was free I would write it from scratch to not have external library dependency and support all custom hosts but I can't even try free trial of it because it end years ago.

**Comment by neurogas** [comment]
But sharex doesn't support already dreamobjects?
https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/FileUploaders/AmazonS3.cs

BTW if you need an S3 compatible istance i could host it for you

**Comment by deansheather** [comment]
S3 is dirt cheap, anyways. It'd cost you a few cents to test on a region close to where you live.

If you're looking to implement your own implementation of the S3 uploader, please support both S3 v2 and v4 signature types on uploads to custom origins. v2 is easier to implement than v4 if I recall correctly (I think especially for multi-chunk uploads), and some S3-compatible APIs only support v2 signatures (like pithos).

S3 v2 signatures are documented [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html), and S3 v4 signatures are documented [here](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html). You'll definitely have to implement v4 signatures, as newer AWS S3 regions don't support v2 signed requests.

**Comment by Jaex** [comment]
I checked my Amazon S3 account now and its free trial was end years ago but still I can still use it for free not sure why. So I tried to implement it from scratch now without use Amazon library but this v4 signature looks so overwhelmingly difficult. Amazon SDK source codes for signature creation is literally thousands of codes :(

**Comment by Jaex** [comment]
Currently I tried to implement it in here: https://github.com/ShareX/ShareX/commit/af1c47a03d92a332ab794eb90d78e679b4b7feb1

But for signature not matches so upload fails. I'm not sure how can I debug this situation now.

**Comment by Jaex** [comment]
Now I added custom server support like this:

![](http://i.imgur.com/qmwI0AL.png)

It supports signature v4 currently.

But I don't have any custom server (with account) to test it. So I'm not even sure are there any servers which can work with Amazon S3 API without require any specific changes.

I also couldn't test [DreamObjects](https://www.dreamhost.com/cloud/storage/) which was exists in previous implementation. Because it requires credit card to even register for trial account. So I sent email to their support and requested test account. Not sure are they gonna give one too.

**Comment by neurogas** [comment]
If you want I could give you access to a test instance

Il 17 mar 2017 12:54 AM, "Jaex" <notifications@github.com> ha scritto:

**Comment by neurogas** [comment]
I've tested with lastest artifact:
![image](https://cloud.githubusercontent.com/assets/1896292/24048429/29d7aa6e-0b29-11e7-82f0-8e853db50f0f.png)

it appears to be adding unwanted prefix (the bucket name)

**Comment by deansheather** [comment]
@neurogas: That means that ShareX is using virtual hosts to upload, which should be supported by most S3 implementations anyways (and would probably work with the implementation you're using if you enabled wildcard DNS for `*.storage.ennetech.me`). Would it be difficult to add a checkbox to disable virtual host uploads, @Jaex?

**Comment by Jaex** [comment]
Amazon S3 specification require bucket name in sub domain.

**Comment by deansheather** [comment]
Paths... I know at least for v2 it's supported, I don't have any experience with v4 at all. But, `storage.ennetech.me/sharex` should work just as well as `sharex.storage.ennetech.me`, apart from some minor changes to the signature (at least for v2).

**Comment by neurogas** [comment]
but the ssl certificate wouldn't be valid, i've successfully used minio
with:
- s3 browser
- as backend for docker registry
- php Flysystem s3 adapter

will test it using the dns wildcard

2017-03-18 12:12 GMT+01:00 Dean Sheather <notifications@github.com>:

**Comment by Jaex** [comment]
I tested now, @deansheather your endpoint format works with v4 too. But I suspect it gonna solve @neurogas problem because he getting invalid signature which means his signature implementation must be different than what Amazon S3 API using.

**Comment by deansheather** [comment]
I was pretty sure minio follows the S3 signature specification...

This doesn't seem right, shouldn't `BucketName` and `Key` have values?:
`<Key></Key><BucketName></BucketName><Resource>/ShareX/2017/03/p49k0loaa7voyre1lh313baud927txp3.png</Resource>`

**Comment by neurogas** [comment]
This can help?
http://docs.minio.io/docs/how-to-use-aws-sdk-for-net-with-minio-server

**Comment by Jaex** [comment]
That link shows how to use library (I don't use library) and not tells anything about their specification.

**Comment by Jaex** [comment]
DreamObjects gave me account to test now. And it worked in first try, which shows that my Amazon S3 implementation don't have problem with working custom hosts.

**Comment by Jaex** [comment]
I noticed that we can test upload in public minio instance and it returns this message: `You are using Internet Explorer version 12.0 or lower. Due to security issues and lack of support for Web Standards it is highly recommended that you upgrade to a modern browser`.

**Comment by Jaex** [comment]
Currently I'm talking with developer of Minio to solve issue.

**Comment by neurogas** [comment]
I'm so glad to read this

**Comment by Jaex** [comment]
I fixed problem with help of Minio developer but still there is one big problem. Minio not supports this header: `headers["x-amz-acl"] = "public-read";` so returned URL becomes private. There is workaround to make bucket public but that require complicated policy creation.

**Comment by neurogas** [comment]
No problem at all, using minio UI setting a policy is a matter of seconds

**Comment by Jaex** [comment]
If you mean that Minio Browser bucket policy setting. I asked is that policy also makes your file listing public too and he told yes. So you need policy which will make file listing private but only reading file with url is public.

**Comment by neurogas** [comment]
Just tested with the last sharex artifact, working perfectly, thank you!

I will investigate to hopefully solve the privacy issue of leaving the whole bucket open
