### ISSUE TITLE
Links in ShareX does not work

### ISSUE THREAD

**Issue by HotPotSoup** [ShareX/ShareX#1059]
Clicking a link, for example Imgur's Authorization Button or anything in the About section of ShareX, does not do anything. I have Chrome set as my default browser.

**Comment by Jaex** [comment]
Open run window paste url there is it opens browser?

**Comment by HotPotSoup** [comment]
Doesn't seem to work either.

**Comment by Jaex** [comment]
That means your Windows have problem not ShareX.
