### ISSUE TITLE
Save and close in image editor

### ISSUE THREAD

**Issue by Lillecarl** [ShareX/ShareX#1062]
ShareX 10.3

When i use this settings:

After capture task:
- Open image in editor
- Save image to file
- Upload photo to image host

Is there a keybinding for save and close?
The tooltip that shows up when hovering should show this (imho).

That's all ive got, great work you guys! :)

**Comment by TheCloudlessSky** [comment]
:+1:

**Comment by jakebathman** [comment]
Similar to #676

**Comment by campbeb** [comment]
@Jaex This was implemented in ee88e25b2ff5556e8e2f12c26dd1ad8b089c4c50 and should be closed.
