### ISSUE TITLE
Add ability to backup all ShareX settings.

### ISSUE THREAD

**Issue by pilovali** [ShareX/ShareX#1065]
Exactly what the title says. Have the ability to export all custom settings to a file.

**Comment by davidruhmann** [comment]
Just copy the files
* ApplicationConfig.json
* HotkeysConfig.json
* UploadersConfig.json
* GreenshotImageEditor.ini

from `%UserProfile%\Documents\ShareX`

**Comment by zikeji** [comment]
While you can easily copy the settings out of your documents folder, I actually like this idea. ShareX is already the ultimate uploading tool, why not have a feature to automatically backup and import settings from your file uploader of choice?

**Comment by Jaex** [comment]
When you can copy setting files I don't see any point of exporting and importing them. It is even same amount of efforts. If it had any benefits I would have added it long time ago.

**Comment by Jaex** [comment]
Because many people requested it, I added `Export / Import` tab to application settings.
