### ISSUE TITLE
Having the ability to try again an option if failed could be great

### ISSUE THREAD

**Issue by LoosGuccreen** [ShareX/ShareX#1070]
Hi.
If I try to share something on twitter (for example) and that it fails (for whatever reason), my screenshot is lost and I can't directly try again (except by re-doing the screenshot). Having a try again option (at least for the latest action taken) would be great.
(Btw great app)

**Comment by Jaex** [comment]
Retry upload already exist:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/10/n3laRSpTvo.png)
