### ISSUE TITLE
Mouse pointer visual offset from actual position

### ISSUE THREAD

**Issue by chojrak11** [ShareX/ShareX#1073]
Don't know if this is an issue within ShareX or FFmpeg. When recording an area, window, or full screen, the mouse pointer on the recording is in different position than in reality. I mean when I recorded Calc (for test, obviously...) then on the video the mouse pointer was over different digits than were actually pressed. The offset increases when moving towards right bottom, and the pointer seems to be to the top left from actual position.

Here's the example recording (just 15 seconds) - http://1drv.ms/1MUSHTZ

EDIT: It's Windows 10 x64, 125% DPI.

**Comment by Jaex** [comment]
https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/56

**Comment by chojrak11** [comment]
Just to add that GDI capture produces the same result.
