### ISSUE TITLE
Stream screen recording

### ISSUE THREAD

**Issue by garygreen** [ShareX/ShareX#1075]
I'm trying to figure out a way to capture the screen to a .mp4 and then cast this video to my TV in realtime. I assume it's some ffmpeg settings that I need to play around with suitable for progressive / streaming access but can't seem to get it working. Any ideas?

**Comment by zikeji** [comment]
I can't tell if you're serious or not.

ShareX doesn't have a screen sharing feature and it never has had one.

**Comment by garygreen** [comment]
No, but it saves the recording to a file which in theory you can send by DLNA to your TV. It uses ffmpeg to encode and output the recording which supports streaming so I don't see why this wouldn't be possible?

**Comment by davidruhmann** [comment]
Look at using the tee option for ffmpeg https://ffmpeg.org/ffmpeg-formats.html#tee
My guess is that ffmpeg has the .mp4 being written locked (even read) until the recording is complete.

**Comment by Jaex** [comment]
I don't think using FFmpeg to stream is good idea even if it is capable of even streaming to Twitch. There must be softwares for this purpose.
