### ISSUE TITLE
Can't capture region while Visual Studio is in focus

### ISSUE THREAD

**Issue by addrum** [ShareX/ShareX#1077]
Only way to capture Visual Studio window is to click on the taskbar and then try the shortcut and it works. Might just be Visual Studio as I know it can be a PITA

**Comment by Jaex** [comment]
I always capture visual studio so I'm not sure why you can't.

**Comment by addrum** [comment]
Interesting, capturing entire screen and capture active window works, but region doesn't.

**Comment by junderhill** [comment]
I'm not able to reproduce this issue either. I've used ShareX in all different versions of VS and nearly always use region capture.

**Comment by addrum** [comment]
Anything to do with a specific VS or Windows version? I'm using Win 10 64 bit and VS 2013 (Community I think).

**Comment by junderhill** [comment]
I've used it under Win 8.1 and now 10, both 64bit. and VS 2013 Ultimate and now VS 2015 Enterprise. Are you using the keyboard shortcut to capture the screenshot? Perhaps its a keyboard binding conflict?

**Comment by Osolemio44** [comment]
Having the same problem in Windows 10 and now on Windows 11.

**Comment by Jaex** [comment]
If PrintScreen key not works while one application is focused, then most likely because that application is ran as admin. So only when ShareX also ran as admin then hotkey works. It is limitation in Microsoft's hotkey system.

**Comment by Osolemio44** [comment]
thanks. i didnt knew that. I followed [this tutorial](https://techcommunity.microsoft.com/t5/windows-11/how-to-run-app-as-administrator-by-default-in-windows-11/td-p/3033704) and all is wroking fine now. thanks a lot.

**Comment by softyoda** [comment]
Is there little shortcut inside sharex to elevate privilege ?
