### ISSUE TITLE
Task completion notifications reappearing in order long after completion.

### ISSUE THREAD

**Issue by StevieMJH** [ShareX/ShareX#1078]
I installed and have used ShareX for the past week after abandoning Greenshot (which apparently has terrible memory leak issues now) in favor of it. Only one minor bug so far that I've noticed just today. After taking a screenshot a couple days ago, two screen-cap gifs yesterday, and another screenshot earlier today, I ran my mouse over a different icon in my taskbar to close the program, and then all of the task completion notifications started appearing again in the order that they originally appeared.

I have everything set to auto upload to imgur with a couple backups. For general/completion settings I have disabled everything except "Save task info to history" and have changed the default notification to the slightly less intrusive balloon tray tip. I think I've seen this bug before with other programs using balloon tips, so it seems fairly common and may be out of your control, but I thought I'd report it anyway.

**Comment by Jaex** [comment]
It is definitely to do with Windows. Windows handling delaying and showing balloon tips when not idle or something like that. I mean ShareX don't have any event for tray icon which can trigger such thing. It don't even store balloon tip info somewhere.

**Comment by StevieMJH** [comment]
I figured as much, thanks for the quick reply.

**Comment by StevieMJH** [comment]
Also, for the great program!
