### ISSUE TITLE
Does not support 4K/high DPI or scaling in Windows

### ISSUE THREAD

**Issue by begna112** [ShareX/ShareX#1079]
ShareX appears incredibly tiny on a 4K display. Even with Windows scaling, it remains the same, despite reboots and reinstalls. See screenshot: 

![ShareX high DPI](http://i.imgur.com/eUDyKcl.png)

**Comment by Scrxtchy** [comment]
Works on my machine
![](http://sharex.moe/i/2015/11/15-11-11_19-44-26.jpg)

If anything, it's not something wrong with the program in itself

**Comment by Jaex** [comment]
It was working for me too when I tested high DPI stuffs.

**Comment by SlyNet** [comment]
Is image editor a part of sharex? Or it has separate bug tracking? It is tiny http://i.imgur.com/RKKDVR6.png

**Comment by Jaex** [comment]
Greenshot image editor ui size was fixed in their repo but merging it manually was too much work therefore I gave up merging anymore.

**Comment by campbeb** [comment]
@SlyNet 
Here is how to fix the editor icons once the next version of ShareX is released:
- Find your ShareX settings folder. Mine on Windows 10 is `C:\Users\campbeb\Documents\ShareX`
- Open `GreenshotImageEditor.ini`
- Find the line `IconSize=16, 16`
- Change it to something like `IconSize=128, 128`. You can change the numbers to other choices such as 64, 96, 128, 256

The icons will be stretched to the new larger size, so they may not look very good, but this is the solution Greenshot is using.
