### ISSUE TITLE
Fallback FTP

### ISSUE THREAD

**Issue by Quantumplation** [ShareX/ShareX#1096]
Hello,

I have ShareX configured to upload to one FTP server that I own.  I would like to configure it so that if uploading to that one fails, it uploads to a secondary FTP server that I own.  I have found the upload retry settings, but it seems I am unable to specify a different set of FTP servers to use.  Is this a currently unsupported feature?

Regards,
Pi Lanningham

**Comment by Jaex** [comment]
It is not supported. Making UI for such thing would be very complicated therefore I'm not planning to make it.

**Comment by Quantumplation** [comment]
Wouldn't it be as simple as choosing a separate workflow as fallback, instead of a separate destination?  i.e. let each workflow specify another workflow if it fails?
