### ISSUE TITLE
Disable Screen Pause During Capture

### ISSUE THREAD

**Issue by ragemuffin** [ShareX/ShareX#1098]
Is there anyway to prevent pausing the screen when using "Capture active window"?
This will help greatly in specific situations trying to screencap a moving YouTube video or a Twitch.tv stream.

**Comment by Jaex** [comment]
Active window capture never pause screen.

**Comment by ragemuffin** [comment]
Sorry, I meant "Capture region".
If you don't know what I'm talking about, I've uploaded a video as an example:
http://puu.sh/l7dmL/d1b81df76f.webm

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/11/T8W9OSXcY7.png)
