### ISSUE TITLE
Ffmpeg capture fails

### ISSUE THREAD

**Issue by cexikitin** [ShareX/ShareX#1100]
Goto capture an active window region and I always get the followingL

ffmpeg version N-69972-g6c91afe Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 19.100 / 54. 19.100
  libavcodec     56. 25.100 / 56. 25.100
  libavformat    56. 23.100 / 56. 23.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.100 /  5. 11.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[gdigrab @ 0000000004bdb340] Capturing whole desktop as 1534x972x32 at (195,69)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1446683656.591962, bitrate: 1431419 kb/s
    Stream #0:0: Video: bmp, bgra, 1534x972, 1431419 kb/s, 30 tbr, 1000k tbn, 30 tbc
[dshow @ 0000000004c05e20] Could not find audio only device with name [Wave (ASUS Xonar DX Audio Devic] among source devices of type audio.
[dshow @ 0000000004c05e20] Searching for audio device within video devices for Wave (ASUS Xonar DX Audio Devic
[dshow @ 0000000004c05e20] Could not enumerate audio only devices (or none found).
audio=Wave (ASUS Xonar DX Audio Devic: Input/output error

**Comment by Jaex** [comment]
You telling active window capture but you giving FFmpeg error? Active window capture never uses anything about FFmpeg.

If you getting this when trying to do screen recording, then it happens because invalid audio source is selected. You must select valid one or just select none for it.

**Comment by cexikitin** [comment]
Thanks, looks like after a clean install the audio box gets set to a blank value instead of none. After selecting none it worked properly.
