### ISSUE TITLE
Vocaroo (Sound Recording)

### ISSUE THREAD

**Issue by ChipWolf** [ShareX/ShareX#1104]
The ability to make sound recordings would be awesome.

**Comment by Scrxtchy** [comment]
```
{
  "Name": "vocaroo",
  "RequestType": "POST",
  "RequestURL": "http://s1.vocaroo.com/media/upload.php?respond_from_www_main",
  "FileFormName": "upload_data",
  "Arguments": {
    "filename": "%unix"
  },
  "Headers": {},
  "ResponseType": "Text",
  "RegexList": [
    "\"media_id\" : \"(\\w+)\"",
    "\"delete_token\" : \"(\\w+)\""
  ],
  "URL": "http://vocaroo.com/i/$1,1$",
  "ThumbnailURL": "",
  "DeletionURL": "http://vocaroo.com/delete/$1,1$/$2,1$"
}
```

Use a workflow that uses the Screenrecorder, and disable video capture device.
You will also need to set up a custom command for ffmpeg so that it will output a audio file

Then set the destination to the above
Keep in mind that vocaroo supports
>mp3, ogg, flac, wav, wma, amr, m4a, aiff, aif, aac, mp2, gsm, 3ga, au and ra)

**Comment by ChipWolf** [comment]
We're using the file upload mechanism right now, just upgraded our personal project https://github.com/starbs/yeh to allow audio and video uploads.
Now to see this in the program itself.

**Comment by Scrxtchy** [comment]
Got a frontend?

**Comment by ChipWolf** [comment]
@Scrxtchy no need for one right now, on the road-map for when the time comes though
