### ISSUE TITLE
Compiler Error in UpdateMessageBox.cs

### ISSUE THREAD

**Issue by tforsberg** [ShareX/ShareX#1108]
ShareX.HelpersLib\UpdateChecker\UpdateMessageBox.cs(80,55,80,57): error CS1002: ; expected
ShareX.HelpersLib\UpdateChecker\UpdateMessageBox.cs(80,73,80,74): error CS1519: Invalid token ';' in class, struct, or interface member declaration

Using VS2012 Professional, Win7 Pro 64-bit

Link to the line in the file:
https://github.com/ShareX/ShareX/blob/master/ShareX.HelpersLib/UpdateChecker/UpdateMessageBox.cs#L80

**Comment by davidruhmann** [comment]
ShareX uses C# 6.0
See https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#expression-bodies-on-property-like-function-members

Use Visual Studio 2015 or upgrade your compiler.
https://www.nuget.org/packages/Microsoft.Net.Compilers/

**Comment by tforsberg** [comment]
Sorry, I didn't catch that.  Thanks.

**Comment by davidruhmann** [comment]
You are using Visual Studio 2012 which supports C# version 4.0 and 5.0.  The code that you listed as an error is actual just a new C# 6.0 feature.  *Recommend* you install Visual Studio 2015 which has the latest Microsoft.Net.Compiler which supports C# 6.0.

Alternatively, *not recommended*, you can just install the latest version of the compiler on Visual Studio 2012 using the NuGet link, but note that there may be other packages needed and 2012 Intellisense will not know about the new features.

**Comment by tforsberg** [comment]
Thanks.  I'm installing VS2015.

On Wed, Nov 11, 2015 at 1:49 PM, David Ruhmann <notifications@github.com>
wrote:

> You are using Visual Studio 2012 which supports C# version 4.0 and 5.0.
> The code that you listed as an error is actual just a new C# 6.0 feature.
> *Recommend* you install Visual Studio 2015 which has the latest
> Microsoft.Net.Compiler which supports C# 6.0.
>
> Alternatively, *not recommended*, you can just install the latest version
> of the compiler on Visual Studio 2012 using the NuGet link, but note that
> there may be other packages needed and 2012 Intellisense will not know
> about the new features.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShareX/ShareX/issues/1108#issuecomment-155891662>.
>



-- 
-Todd
