### ISSUE TITLE
Unable to register hotkeys after Windows update

### ISSUE THREAD

**Issue by coggy9** [ShareX/ShareX#1112]
After upgrading Windows 10 to the Fall Update, build 10586, ShareX is unable to register the hotkeys I has set. I have tried reinstalling, but the issue still exists. The logs do not say anything helpful. Is there any way to enable more detailed logs, or figure out which app has that key combination in use, if any?

![Debug log](http://i.imgur.com/49cTtOw.png)

![Error and Winver](http://i.imgur.com/vZCeOji.png)

**Comment by Jaex** [comment]
Probably OneDrive using these hotkeys.

**Comment by coggy9** [comment]
Thanks. I didn't even notice that was re enabled on startup after the update.

**Comment by kodybaker** [comment]
What's the solution?

**Comment by Jaex** [comment]
Select different hotkey or close conflicting application.

**Comment by SebLemery** [comment]
its funny how this community says "well the problem is another program" boom closed. like... can you tell me how to fix my issue? ...

**Comment by Jaex** [comment]
I already told check previous message...

**Comment by SebLemery** [comment]
no, you didn't told me anything. you just closed it. There is no instructions whatsoever in here.

**Comment by Jaex** [comment]
This one? https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/11/36T2TBH2Gg.png

**Comment by dasjestyr** [comment]
@SebLemery right click on the OneDrive icon in your system try and go to settings. On the Auto Save tab, uncheck the "Automatically save screenshots I capture to OneDrive" checkbox. It seems that option bullies its way into controlling your screenshot keys.

**Comment by oldmud0** [comment]
It seems that OneDrive can show this option unchecked, but it may still hook the hotkeys anyway. Interesting...

**Comment by Daniel15** [comment]
I wish I could just tell OneDrive to stop hooking the keys. All I care about is ShareX. <_<

**Comment by McoreD** [comment]
@oldmud0 yes that's right; I noticed this too.

**Comment by oldmud0** [comment]
In theory, if ShareX started before OneDrive, it could hook the hotkeys before OneDrive possibly could.

**Comment by DARKFiB3R** [comment]
Using something like these to delay or edit the order in which applications start on your system seems like a possible fix. http://www.thewindowsclub.com/set-delay-time-startup-programs-windows

**Comment by Daniel15** [comment]
Great idea, thanks @DARKFiB3R! I used to delay application startup many many years ago back when I used Windows 98. At the time, it was a great way to ensure your system wasn't bogged down by heaps of apps all trying to start at the same time (especially given hard drives were much slower then). I didn't even think of using the same principle here. In my case I just completely disabled OneDrive, but I might re-enable it and do this instead! :smile:

**Comment by MagicMau** [comment]
You will need to sync your OneDrive's screenshot folder in order for it to understand NOT to hook the PrintScreen key. See also [this comment ](https://feedback.techsmith.com/techsmith/topics/the-print-screen-button-seem-to-be-invaded-by-onedrive?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16952118#reply_16952118) that explains it in more detail with screenshots. It basically comes down to enabling the feature, syncing your Screenshot folder and then disabling it again. This worked for me!

**Comment by m4tic** [comment]
A year later, I discovered this application and it's awesome, but has the keyboard conflicts with onedrive. I tried the startup delayer workaround as shown above and it works great. Thanks!

**Comment by nvivo** [comment]
Very old thread, but I solved this sometime ago and forgot it, spent the last minutes looking for a solution again. So, a simple solution that works for me on a clean install currently:

1. Press Print Screen, let one drive ask you if you want to use the feature to save screenshots there. 
2. Say "No, thanks"
3. Go back to ShareX hotkey settings and "Restore defaults" or restart the computer

Once you say "no, thanks", one drive stops binding to these keys.

**Comment by sharp-dev** [comment]
1 - sorry for the electronic translator
2 - my decision is 99% the same. and it's just
3 - Finish ShareX
4 - press PtrScr
5 - "OneDrive" asks a question - answer is NO
6 - restart ShareX
..enjoy

**Comment by nem8** [comment]
Can confirm @sharp-dev's solution works flawlessly. Note that this only applies to Onedrive Personal, Onedrive business doesnt have the screenshot capability.

**Comment by thejoikabolla** [comment]
another solution that may be worse is that you right click on the onedrive icon and then tell it to not start up when signed into windows. Then you right click on lightshot and click options. Then you just click okay then it should work.

**Comment by krygstem** [comment]
Dropbox has the same problem with Sharex, just disable autosaving of screenshots.

**Comment by GitAlexToTheGreek** [comment]
Hi all 🙂

What about a scenario where OneDrive is uninstalled but the same conflict alert message appears after each system start?

<a href="https://imgur.com/BzvHeEe"><img src="https://i.imgur.com/BzvHeEe.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/jRyt7ly"><img src="https://i.imgur.com/jRyt7ly.png" title="source: imgur.com" /></a>

🤔

ShareX v13.1

Windows 10 Home
Version 1909
OS build 18363.836

-> Can anyone suggest how to narrow down what the conflicting application could be?

Thanks in advance, 
Alex

**Comment by GitAlexToTheGreek** [comment]
Anyone?

**Comment by tikkatek** [comment]
@GitAlexToTheGreek, I'm new and just started using this app after a recommendation. Couple of things I noticed. First thing was that OneDrive Personal (not Business) has the option that hijacks the shortcut. After disabling this, it was then Snip & Sketch that was taking over. 

Go into Settings and search for "print", the option "Use the Print Screen key to launch screen snipping" should be available. 
![image](https://user-images.githubusercontent.com/26571381/84082735-4393a100-a9d8-11ea-9a17-d9183dafcaf3.png)

Click on that and search for the "Print Screen shortcut" option, then toggle it off.
![image](https://user-images.githubusercontent.com/26571381/84082801-5e661580-a9d8-11ea-8f83-2f247626ec70.png)

ShareX started working for me from there.

Good luck!

**Comment by GitAlexToTheGreek** [comment]
Hi tikkatek 😉

I appreciate the feedback... 

Checked and sure enough that setting (Print Screen shortcut) was enabled. I just deselected it.

Thankfully since my last post, the alert message stopped appearing following system restarts...and it's not even clear what fixed it 🙃

At any rate, I wasn't using the PrtScn shortcut to trigger ShareX to begin with so no harm in making all if this stuff a little less complicated.

Cheers.

**Comment by tayeep** [comment]
Why would this be OneDrive or Windows Snipping Tools problem? If I use Greenshot, it never fails to capture the shortcut key. 

Also, if I manually go to ShareX > Hot Key Settings > Click and set the shortcut key again, it works. Isn't this mean if ShareX tries to re-capture the shortcut key again after everything loaded, it can be successful?

**Comment by Bluscream** [comment]
> You will need to sync your OneDrive's screenshot folder in order for it to understand NOT to hook the PrintScreen key. See also [this comment ](https://feedback.techsmith.com/techsmith/topics/the-print-screen-button-seem-to-be-invaded-by-onedrive?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16952118#reply_16952118) that explains it in more detail with screenshots. It basically comes down to enabling the feature, syncing your Screenshot folder and then disabling it again. This worked for me!

Sadly the link is 404

**Comment by sharp-dev** [comment]
I've been using a very simple solution for a long time:
- DO NOT START ShareX
- run OneDrive
- click PrintScreen
- to a suggestion like "always use OneDrive for screenshots?" answers NO

it is enough to do it once

**Comment by bscreative** [comment]
Nothing in this thread helped me. On random occasions, OneDrive or DropBox would take control. Here's what I did to permanently stop the problem.

**The Solution**: Disable auto startup on OneDrive and DropBox. Then set up a Scheduled Tasks in Windows to launch OneDrive and DropBox 1 minute after startup (if you have a SSD). If you're running an older HDD, 3-4 minute delays might be better.

The instructions for delaying OneDrive are [well very documented here](https://windowsloop.com/delay-onedrive-startup/).

DropBox is the same process, except it uses the following Program location: 
`"C:\Program Files (x86)\Dropbox\Client\Dropbox.exe"`
**Argument**: /home
**Screenshot**: https://i.imgur.com/OkypKDx.png

**Comment by bruninjaman** [comment]
@sharp-dev simple and worked, thank you!

**Comment by JJGadgets** [comment]
I'm having the same problem now, except I don't have OneDrive or Dropbox installed (LTSC force removed, I don't have Office)
I've checked RTSS, Steam, MSI Afterburner, OBS, Discord and they all don't have any PrintScreen keybinds binded.
My error window also doesn't show the conflicting app. Any ideas?

**Comment by kgnfth** [comment]
i had the same issue with onedrive conflict

what i did was, i closed sharex, then i hit `prt sc` on my keyboard which i got a onedrive window telling me to save screenshots to onedrive, i hit cancel, then i open sharex, everything is fixed

sorry for my ugly motha focka english

**Comment by farmeunit** [comment]
@sharp-dev Definitely has the simplest answer and it works.  Realistically, ShareX should have the ability to counteract this or at least ask the question during install if that is an option for people instead of just throwing an error.  At least check and see if it's set and tell people.  Considering OneDrive is now in every single Windows install...

**Comment by Aholicknight** [comment]
Wish sharex **SAID** which process is causing the conflict...I get the pop-up and OneDrive is closed..

**Comment by Hermholtz** [comment]
@Jaex so if you could add the solution to the dialog message, that would be much easier for people to deal with it. Or a clickable link maybe? Thanks.

1. Exit ShareX. Usually you need to right click the ShareX tray icon and select "Exit".
2. Go to OneDrive Settings-Backup and **uncheck** "Automatically save screenshots I capture to OneDrive". Click OK.
3. Press the PrtSc key.
4. OneDrive will show a popup window asking if you want to use it for screenshots, click "No thanks".
5. From now on it will unhook the PrintScreen key and ShareX can be fully used without further warnings.

This problem is **not** specific to ShareX, every app that wants to use PrtSc has the same issue. You may also encounter it if you're running another screen capturing tool at the same time. Both cannot handle the PrintScreen key simultaneously.

**Comment by Aholicknight** [comment]
@Hermholtz bro, this issue has been closed since October 21st, and to fix the problem, I use [Startup Delayer](https://www.r2.com.au/page/products/show/startup-delayer/) to delay OneDrive from opening first and let ShareX open first.

**Comment by Hermholtz** [comment]
I'm glad you sorted that out. I think using Startup Delayer is a hack, not a proper solution, for example I don't want to introduce it in my system. 

Also, it's not just about you, it's about all users who can deal with this easier if the error message in ShareX is more informative as suggested above. Hoping to get some attention from @Jaex, so thanks for making noise.

**Comment by Aholicknight** [comment]
> Nothing in this thread helped me. On random occasions, OneDrive or DropBox would take control. Here's what I did to permanently stop the problem.
> 
> **The Solution**: Disable auto startup on OneDrive and DropBox. Then set up Scheduled Tasks in Windows to launch OneDrive and DropBox 1 minute after startup (if you have a SSD). If you're running an older HDD, 3-4 minute delays might be better.
> 
> The instructions for delaying OneDrive are [well very documented here](https://windowsloop.com/delay-onedrive-startup/).
> 
> DropBox is the same process, except it uses the following Program location: `"C:\Program Files (x86)\Dropbox\Client\Dropbox.exe"` **Argument**: /home **Screenshot**: [i.imgur.com/OkypKDx.png](https://i.imgur.com/OkypKDx.png)

you can also use this @Hermholtz and then you don't have to use a third party program

**Comment by Bluscream** [comment]
> I'm glad you sorted that out. I think using Startup Delayer is a hack, not a proper solution, for example I don't want to introduce it in my system.
> 
> Also, it's not just about you, it's about all users who can deal with this easier if the error message in ShareX is more informative as suggested above. Hoping to get some attention from @Jaex, so thanks for making noise.

jaex doesnt use github anymore

**Comment by Jaex** [comment]
> jaex doesnt use github anymore

I'm using GitHub and reading every single message.

**Comment by Bluscream** [comment]
You rarely respond to any bug report/feature request tho

**Comment by Jaex** [comment]
Because everyday so many people opening new report/feature requests and I'm one man team. I'm working in this project in my free time and I don't have time to respond to every single requests. So if issue is critical then more likely I respond to those.

**Comment by Madac1** [comment]
Alternatively if you have troubles, you can disable "Automatically save screenshots I capture to OneDrive", press "Ok", then enable it again, press "Ok", and disable it again and press "Ok". Works 100% of the times.

**Comment by Aholicknight** [comment]
> Alternatively if you have troubles, you can disable "Automatically save screenshots I capture to OneDrive", press "Ok", then enable it again, press "Ok", and disable it again and press "Ok". Works 100% of the times.

@Madac1 necroposting so hard lol

**Comment by tolga-balci** [comment]
@tikkatek 's solution is the only solution that worked for me.

**Comment by InteXX** [comment]
In my case it was the recently-installed latest version of Dropbox. Here's how I fixed it:

1. Exited ShareX
2. Pressed Alt+PrtScrn
3. When prompted by Dropbox, selected No (don't sync screenshots)
4. Restarted ShareX

There was no more hotkey conflict after that.

**Comment by ch-gz** [comment]
> Using something like these to delay or edit the order in which applications start on your system seems like a possible fix. http://www.thewindowsclub.com/set-delay-time-startup-programs-windows
> 
> EDIT: I used the free version of Startup Delayer, and that has fixed the issue for me.
> 
> I gave ShareX, Dropbox and OneDrive a manual delay of 0 but made sure that ShareX is first in the list.
> 
> ![2016-03-31_11-05-48](https://cloud.githubusercontent.com/assets/654659/14172583/a18011d6-f730-11e5-81cb-422f1a59d3ae.png)
> 
> EDIT 2: Thank you to @oldmud0 for giving me the idea ;)

Brilliant idea, and it works like a charm.
