### ISSUE TITLE
Proxy support for Tor?

### ISSUE THREAD

**Issue by intchloe** [ShareX/ShareX#1113]
ShareX already have support for proxy, but I can't get Tor to work with ShareX. I've tried to enter "socks5://127.0.0.1" and port 9050 but that didn't work. 

Does ShareX even have support for SOCKS5? If not, please include that.

**Comment by atillabyte** [comment]
There are applications such as Privoxy which can handle forwarding HTTP(S) requests over SOCKS5.
However, SOCKS support could be useful in other scenarios - not that I've found any.

**Comment by intchloe** [comment]
@atillabyte Yes, of course could I tunnel the SOCKS5-traffic to an HTTP-tunnel but that is a work-around which I don't want.

I would like to see native SOCKS4/5-support in ShareX, or just an option to use Tor.

**Comment by Jaex** [comment]
.NET Framework don't have SOCKS proxy support otherwise I would have added it.
