### ISSUE TITLE
ShareX says hotkeys are in use, even if i put new ones

### ISSUE THREAD

**Issue by fabiotp91** [ShareX/ShareX#1114]
I have even downloaded Windows Hotkey Explorer to see which program was using it, but none show using it, and if i put a new hotkey ShareX says it´s in use also. (have downloaded the Steam version and the "Web" version and have the same problem).

Using Windows 10
Version 1511 Build 10586.3

**Comment by Jaex** [comment]
Which hotkeys are in use it tells when you open ShareX?

**Comment by fabiotp91** [comment]
Print Screen
Ctrl + Print Screen
Shift + Print Screen
Shift + F12

**Comment by Jaex** [comment]
Are you have OneDrive or Dropbox?

**Comment by fabiotp91** [comment]
I have already unnistalled Dropbox.
Tried now Onedrive and cleared all hotkeys except Shift + F12 (Thanks for the onedrive tip)

**Comment by Jaex** [comment]
I noticed that too Shift + F12 unable to register, don't know why. It must be reserved for something in Windows.

**Comment by fabiotp91** [comment]
There´s no problem, at least i can use the main ones! 
Thank you very much!

**Comment by Jaex** [comment]
#1112
