### ISSUE TITLE
Temp-Share support

### ISSUE THREAD

**Issue by MisterX2000** [ShareX/ShareX#1124]
Upload support for [temp-share.com](https://temp-share.com/home), but I could not find an api.

**Comment by Scrxtchy** [comment]
I understand it's API, it's not public but can be understood from the source  
It's a two step process over HTTP verbs (need session cookie), something I can't make in a custom uploader  
shouldn't be too hard to create in C# if someone wants to give it a whirl

**Comment by qaisjp** [comment]
can you share the research for what you've reverse engineered

**Comment by Jaex** [comment]
Mainly if they don't have API that means they don't want softwares to use their service otherwise why would they not make API.

**Comment by qaisjp** [comment]
Makes sense.

**Comment by Scrxtchy** [comment]
I used the PHP form on the front page
Nothing special



Sent from my Mi phoneOn Qais Patankar <notifications@github.com>, 10/01/2016 6:07 am wrote:can you share the research for what you've reverse engineered
