### ISSUE TITLE
Default hotkeys conflict with OneDrive

### ISSUE THREAD

**Issue by wbenny** [ShareX/ShareX#1125]
This might not be actually your problem.

Windows 10 + OneDrive (17.3.6201.1019), it started few days ago.

I've built ShareX from the most recent master branch, where after the start the dialog also contains the name of the conflicting application (OneDrive.exe).

![untitled](https://cloud.githubusercontent.com/assets/4465216/11285253/d687e26c-8f0e-11e5-944e-5a261de2949b.png)

**Comment by Jaex** [comment]
#1112
