### ISSUE TITLE
ShareX Automatic Shutdown At New Version Update

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#1128]
How about implementing an automatic ShareX shutdown when it detects itself still running when installing an update? This would end the need to bring up task manager or other procedure to end task so that the update can take place.

**Comment by Jaex** [comment]
Auto updater already closing ShareX when installing?

**Comment by MrCD1968** [comment]
Mine doesn't shut down.  I just updated to 10.4 today.

**Comment by Jaex** [comment]
I opened previous version ShareX now and it asked for auto update. After download update it closed ShareX and installed it.

**Comment by kyodjinn** [comment]
My ShareX updated fine. Btw, thanks for the update, lots of great features!
