### ISSUE TITLE
We Transfer 

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#1129]
Is "We Transfer" supported?

https://www.wetransfer.com/#

**Comment by Kesmy** [comment]
The WeTransfer API "will only be available to select partners, beginning with Getty Images,"

**Comment by shaneknysh** [comment]
We transfer has a public API now. Someone might be able to jump on this and add it. However, there seems to be limits on the We Transfer API - specifically 2GB limit and transfers expire after 7 days. I can't see if the GB limit is per account or per time period.

https://wetransfer.zendesk.com/hc/en-us/articles/210512863-Introducing-the-WeTransfer-Public-API
https://developers.wetransfer.com/

Not sure if this is still desired functionality.

**Comment by Blendertom** [comment]
Yes, would love wetransfer integration.

**Comment by Jaex** [comment]
https://wetransfer.zendesk.com/hc/en-us/articles/360038551772-We-ve-retired-our-Public-API
