### ISSUE TITLE
Exception caused by the target of a call

### ISSUE THREAD

**Issue by diavolodeejay** [ShareX/ShareX#1130]
System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.BadImageFormatException: Impossibile caricare il file o l'assembly 'ShareX.IRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' o una delle relative dipendenze. Il modulo doveva contenere un manifesto di assembly.
   in ShareX.TaskSettingsTools..ctor()
   in ShareX.TaskSettings..ctor()
   in ShareX.ApplicationConfig..ctor()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   in System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   in System.Activator.CreateInstance[T]()
   in ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   in ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   in ShareX.Program.LoadProgramSettings()
   in ShareX.Program.Run()
   in ShareX.Program.Main(String[] args)

ShareX 10.4 Release

---

I don't really know what i copied. But i hope this will be helpfull

**Comment by Jaex** [comment]
#1049
