### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZSleyerLP** [ShareX/ShareX#1131]
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.BadImageFormatException: Die Datei oder Assembly "ShareX.IRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
   bei ShareX.TaskSettingsTools..ctor()
   bei ShareX.TaskSettings..ctor()
   bei ShareX.ApplicationConfig..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance[T]()
   bei ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   bei ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   bei ShareX.Program.LoadProgramSettings()
   bei ShareX.Program.Run()
   bei ShareX.Program.Main(String[] args)

ShareX 10.4 Release

**Comment by Jaex** [comment]
#1049
