### ISSUE TITLE
Alt + F1 not working anymore

### ISSUE THREAD

**Issue by Sickness-chan** [ShareX/ShareX#1134]
I had a region capture task assigned to ALT + F1, it worked just fine until today, now ShareX is not registering the hotkey anymore and I can't re-assign it either. Is there any particular reason for this?

**Comment by Jaex** [comment]
I can register ALT + F1, so something in your computer causing hotkey conflict.

**Comment by Sickness-chan** [comment]
Yeah, it was the new Nvidia GeForce Experience update that had some share feature turned on by default. Disabled that and could register it again.
