### ISSUE TITLE
Since 10.4 update I cannot upload screenshots at default server

### ISSUE THREAD

**Issue by vadymmykh** [ShareX/ShareX#1137]
I get this kind of error:

Message:
Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
Your firewall could be blocking it.

**Comment by vadymmykh** [comment]
I just downgraded it to 10.3 and everything is fine.

**Comment by Jaex** [comment]
Did you ever tried re opening 10.4?

**Comment by Jaex** [comment]
I'm pretty sure it is not to do with 10.4

**Comment by vadymmykh** [comment]
Yes. I tried to close and open the program, manually upload the picture by right clicking it, I restarted PC - nothing helped.

**Comment by Jaex** [comment]
"Unable to connect to the remote server" this can means two thing either your computer blocks ShareX or server is actually down. So it can't be to do with ShareX.

**Comment by vadymmykh** [comment]
The only thing I know for sure is it's working since v9 to 10.3 and NOT working in 10.4. So I assumed it has something to do with the program-to-server communication. It even may be the syntax - I got alike problem in MiniMoog synth. I started this topic just to know is it only me who has this kind of problem.

**Comment by Jaex** [comment]
Nothing changed in codes about uploading.

**Comment by Scrxtchy** [comment]
What destination are you using, and/or does it apply to multiple destinations?

**Comment by vadymmykh** [comment]
The default one - imgur. Didn't try to change destinations.

**Comment by Zumochi** [comment]
If you're logged in with imgur, try clearing authorization and re-authorizing. I had the same issue and this fixed it for me.

**Comment by vadymmykh** [comment]
Never had an account there. Never registered.
