### ISSUE TITLE
mega upload copies wrong url to clipboard

### ISSUE THREAD

**Issue by Dadude123** [ShareX/ShareX#1139]
upload a file to mega with credentials set.
it won't copy the correct url to your clipboard, when you try to download it, the progressbar will go to 100% and then it will say "decryption error".

but when i go to the file in mega after sharex has uploaded it and copy the full link manually it works.
and the link i get when copying the link also looks completely different than the one sharex got.

**Comment by Jaex** [comment]
Can you report it in https://github.com/gpailler/MegaApiClient/issues ?

**Comment by Dadude123** [comment]
ok will do!

**Comment by gpailler** [comment]
Created gpailler/MegaApiClient#18. Will be fixed within MegaApiClient 1.1.3

**Comment by gpailler** [comment]
MegaApiClient v1.1.3 is out. Please update Nuget dependencies
