### ISSUE TITLE
Google Drive upload folder path

### ISSUE THREAD

**Issue by servint** [ShareX/ShareX#1145]
Hi. Is it possible to make editable folder path input in "Destination settings" dialog?
So I can put some folder name + month (for ex.) and when I upload any file on Google Drive ShareX will check for that folder existence and if it's not there ShareX will create it via G Drive API. 

You can do this on "Copy" and "Dropbox". But not OneDrive or Google Drive.
Thank you.

**Comment by Jaex** [comment]
If it was possible I would add it. Dropbox and Copy allows it easily without separate request. But for others need to do folder checks etc. many requests will require before upload which will slow uploading a lot.
