### ISSUE TITLE
Error uploading to imgur

### ISSUE THREAD

**Issue by Shlink** [ShareX/ShareX#1149]
I can no longer upload screenshots to imgur, I'm not sure what has changed. Any suggestions?
I'm using ShareX 10.4

Message:
The remote server returned an error: (403) Forbidden.

Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by stvkno** [comment]
Do you use an imgur account to upload screenshots via ShareX? If so, maybe take a look at that.

**Comment by Shlink** [comment]
I do use an account. Clearing and re-applying the authorization within ShareX resolved my issue, thanks!

**Comment by SeraphineX** [comment]
I'm having the same problem, I'm using an account. I already re-applied the authorization code a couple of times and it works for a couple of hours and then it happens again,

The error message I'm getting is similar to yours: https://i.imgur.com/ZfoPydO.png

**Comment by Jaex** [comment]
#1138
