### ISSUE TITLE
Changelog missing?

### ISSUE THREAD

**Issue by Tarun80** [ShareX/ShareX#115]
With the last few releases I've been looking for a changelog to see what has changed but have been unable to find it. Is this available through the install or somewhere online?

So far, [this](https://github.com/ShareX/ShareX/releases) is all I can find. If this is an official changelog can it please be made a bit more publicly accessable through the program in some manner?

**Comment by Tarun80** [comment]
@McoreD, @Jaex, has this still not been added?

**Comment by Jaex** [comment]
Changelog exist in web site.

**Comment by Tarun80** [comment]
And once more I will echo what I have said in the past.

There is nothing accompanying the program itself. A user should not have to search the website for the changelog.

**Comment by Jaex** [comment]
Yesterday I added changelog link to update notification window so it will be sufficient.

**Comment by Tarun80** [comment]
Please add a link to the About section as well.

**Comment by Jaex** [comment]
About section already have link to changelog for long time.

**Comment by Tarun80** [comment]
Nothing in there states a link to the Changelog.

![bGVnz3r.png](http://i.imgur.com/bGVnz3r.png)

**Comment by Jaex** [comment]
It is there I can see it.

**Comment by Tarun80** [comment]
If it's there, it's using an incorrect term.

A changelog reflects the addition, removal, and bug fixes within a program. The screenshot clearly shows that nothing clearly designates where to find the Changelog.

**Comment by Jaex** [comment]
Many softwares make version text clickable which will open changelog.

**Comment by Tarun80** [comment]
I'm not sure what software you're using that does that kind of behavior, but it's not a clearly defined changelog nor is it correct behavior.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/ShareX.vshost_IycRbGRQ5W.png)

**Comment by Tarun80** [comment]
Thank you, that's much clearly than before.
