### ISSUE TITLE
Tools :: Convert PNG sequence to GIF

### ISSUE THREAD

**Issue by henpemaz** [ShareX/ShareX#1152]
I find myself many times exporting a sequence of images from Blender or Flash, or even After Effects, and then I usually use something like Fireworks or Photoshop to make a simple gif... It's a pain !

Since FFMPEG is already there, why not do it with ShareX ? I don't think I've seen anything like this in the current version or here in the issues section...

Load and sort multiple images (alphabetic order should be fine), save GIF to a file (or to default destination).

Basic settings would be
- FPS
- Repeat X times (0 for infinite loop, default)
- Color settings maybe ? (dither, palette mode)(I'm not aware of all the options in the FFMPEG cli)
- Downscale option ?
- Anything you think it may be important ?

Keep up the good work /)

**Comment by Jaex** [comment]
Finding Animated GIF editor tool will be better suited for what you want. But indeed FFmpeg can do what you want and you can write .bat file yourself to do it. After figure out what commands needed ofc. So I'm not planning to add GIF editor related features to ShareX.

**Comment by hced** [comment]
I'd like to ask if this is possible for video conversion rather than gif. Eg. convert a folder containing image_0001.png, image_0002.png, image_0003.png and so on to something like MP4 h.264 container?
