### ISSUE TITLE
Imgur authorisation on multiple instances

### ISSUE THREAD

**Issue by TomasLiutvinas** [ShareX/ShareX#1158]
Repro steps:
Authorize imgur on two different machines using shareX

Issue:  The 1st machine that is authorised is unable to upload images until refresh authorization is clicked. (When authorising on one machine it seems to deauthorize on the other.)

Idea: Can reauthorisation process be automated before uploading in case the auth. fails, since it does not require any user input, besides opening destinations menu and clicking the button.

**Comment by TomasLiutvinas** [comment]
http://i.imgur.com/UDKWyQj.png

**Comment by Jaex** [comment]
Maybe you should sync your config file so in two different computer it will use same token?

**Comment by TomasLiutvinas** [comment]
Turning off shareX, copying imgur auth details over to the first machines UploadersConfig.json helped.
