### ISSUE TITLE
Unable to upload to Imgur

### ISSUE THREAD

**Issue by Sovex66** [ShareX/ShareX#1160]
Got this error : 
Message:
Le serveur distant a retourné une erreur : (403) Interdit.
Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}
StackTrace:
   à System.Net.HttpWebRequest.GetResponse()
   à ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

I tried 2 older version, uninstall + installl
Clear the chrome extension
Clearing authorization on imgur
W10 + ShareX app

If anyone got a idea or can help me, thanks in advance

**Comment by Scrxtchy** [comment]
#1138
