### ISSUE TITLE
Need to authenticate every startup with imgur

### ISSUE THREAD

**Issue by ySomic** [ShareX/ShareX#1165]
I have no idea why, but on my secondary laptop, I always need to authenticate again with Imgur.
I am uploading to a specific album every time (the same album)

ShareX does say I am authenticated on startup, has the correct album but if i try to upload something, it throws an exception and when I refresh my albums it also throws an exception.

If i exit shareX and open it again without boot, it keeps on working.

I am not sure if the issue is with ShareX or Imgur.

**Comment by Jaex** [comment]
#1138
