### ISSUE TITLE
Big color depth loss depending on app to view them from

### ISSUE THREAD

**Issue by Slind14** [ShareX/ShareX#1166]
When taking screenshots either as png or jpeg they loose color depth depending on the app you open them with. 

| app                            | png color loss | jpg color loss |
|--------------------------------|----------------|----------------|
| Windows Photo Viewer        | 1              | 1              |
| Imgur API Upload (Browser View)               | 1              | 1              |
| Windows Paint                    | 1              | 1              |
| Chrome, Firefox                  | 1              | 0              |
| Imgur webinterface Upload (Browser View) | 0              | 0              |
| Greenshot Editor                 | 0              | 0              |
| ShareX Preview                  | 0              | 0              |

I could only explain this if the color space would not be saved and hence the apps doing a best guess or fallback.

**Comment by Jaex** [comment]
Can you show me comparison ss? I'm not sure how color loss happens in png.

**Comment by Slind14** [comment]
@Jaex I could confirm that it isn't a color loss, it depends on the app to view the image from. I assume it is an issue with the color space.

**Comment by Slind14** [comment]
png on the left, jpeg on the right. (I could only open the greenshot editor once, sorry)
Please be aware that as those are screenshots of screenshots, the color depth difference does look less between the images as another "loss" happened.
https://imageshack.com/a/img908/2883/4ovxrI.png

**Comment by Jaex** [comment]
I don't see any color loss in any software:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/YlsF4VnA33.png)

**Comment by Jaex** [comment]
I mean it is default .NET framework image saving how it can have issue? Extreme amount of people would report it if such thing happen.

**Comment by Slind14** [comment]
I took a screenshot of your Windows Photo View using only PNG in this case:
https://imageshack.com/a/img905/4569/UuDCgG.png
| png              | png                |
|------------------|--------------------|
| GreenShot Editor | Chrome             |
| Paint            | Windows Photo View |

**Comment by Jaex** [comment]
I remember long time ago someone else was reported it too and we suspected it was monitor color profile issue and there was no solution we could find for it. Did you tried using another screen capture software like Greenshot and checking is it have same issue too?

**Comment by Slind14** [comment]
using the shareX screen color picker:

| app                  | rgb         |
|----------------------|-------------|
| windows photo viewer | 188, 74, 40 |
| shareX preview       | 218, 57, 30 |
| chrome               | 188, 73, 40 |
| Paint                | 218, 57, 30 |

I'll try greenshot now.

**Comment by Slind14** [comment]
Same results with greenshot:

| app                  | rgb         |
|----------------------|-------------|
| windows photo viewer | 188, 74, 40 |
| chrome               | 188, 73, 40 |
| Paint                | 218, 57, 30 |

**Comment by Jaex** [comment]
So that means it is definitely not to do with ShareX. Probably other screen capture apps will have same results too.

**Comment by Slind14** [comment]
Made another test with windows screenshot -> paint -> save as png, same result. So seems to be on my end with color management and depending on whether the app used for displaying supports it or not. The only thing I don't understand is why it works with jpg's in browsers but not with png's, anyways, I guess that has nothing to do with ShareX anymore :)

Quick off topic question: when the capture dialog is opening up, is the image already converted to jpeg or png, or would it theoretically be possible to have another selection for the format? (PNG or JPEG).
The goal being to be able to quickly switch depending on what was taken, without the need of going into the options before taking the screenshot. (png for graphics, ui's, text and jpeg for photographic images..)

**Comment by Jaex** [comment]
It is bmp.

**Comment by Slind14** [comment]
thanks, so I'll open up a feature request :)
