### ISSUE TITLE
Image format selection on post capture task

### ISSUE THREAD

**Issue by Slind14** [ShareX/ShareX#1167]
It would be a great time safer and or file size safer it was possible to choose the image format on the `Post capture tasks` dialog.

- **PNG** lossless, perfect for images of color surfaces (UI's, websites, text..) -> smaller than jpeg in those cases
- **JPEG** lossy, small file size with photo graphical images, gradients..

![](https://i.imgur.com/8wBLMMB.png)

**Comment by Jaex** [comment]
Everybody will have their own needs how am i supposed to put everything there?

**Comment by Slind14** [comment]
Good point. I see how far I get with workflows.
