### ISSUE TITLE
Region (Annotate) capture mode's draw rectangle option is drawn wrongly

### ISSUE THREAD

**Issue by nicholastay** [ShareX/ShareX#1170]
My setup is a 1920x1080 monitor with my main monitor, 2560x1080 ultrawide on the right. When I draw a rectangle with the "Region (Annotate)" option, it renders the rectangle in the wrong position and appears on the very left.

Video showing this: http://puu.sh/lIDI6/e72a66a094.mp4

Quick edit: The standard pen tool works just fine, it is just the rectangle tool which is drawn wrongly.

**Comment by Jaex** [comment]
I think it is fixed now but can't verify because I don't have multi monitor.

**Comment by L1Q** [comment]
Can confirm. Fixed.
