### ISSUE TITLE
A feature query / request - random field in the screenshot URL / secure FTP

### ISSUE THREAD

**Issue by peterh337** [ShareX/ShareX#1171]
I have spent ages looking for a way to send a message to the ShareX team; hopefully this might reach them.

Currently I use Faststone Image Capture. It does what I need but has a big security problem if uploading the screenshots to an FTP site:

The screenshot URL obviously has an auto generated variable field, which is normally date/time-based and optionally can include a "DOS" environment variable. But if you send somebody the URL, they can fairly trivially step back the date/time field and extract all your previous screenshots!

What is needed is a randomised portion in the URL - say a hash of the date/time.

One way to achieve the random element might be to continually randomly modify the DOS environment variable, but under win32 you cannot have a program which modifies another program's environment variables. Especially as the screenshot program gets loaded when Windows starts up!

Faststone do not ever reply to any communications so I have been looking for other programs which might produce "random" URLs which cannot be reversed to yield *other* screenshots...

Also, does ShareX support SFTP (Secure FTP). No image / screenshot program I have ever found does that.

**Comment by Jaex** [comment]
ShareX web site have contact form also have live IRC chat link so I'm not sure how you were searching ages for a way to message us.

ShareX already supports many random naming options:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/ZyCqcGyRZB.png)

ShareX also supports SFTP.

**Comment by peterh337** [comment]
I could not find a contact form, and have not used IRC for about 20 years :)

However I will try ShareX as it does seem to do everything and more. I am running WinXP SP3.

Having a date/time *and* a random element means someone cannot work out other filenames, but I can still find stuff generated during a given date and hour.

Many thanks for your feedback.

**Comment by Jaex** [comment]
Few AdBlock addons block contact form I think. Mine don't block it.

**Comment by peterh337** [comment]
It looks good but very opaque re config:

1. I want to save screenshots to local drive c:\screenshots but the program creates a *directory* named after the variable field and puts a .png file (which also has a date-based variable field) inside that. Can it be configured to just create a .jpg file whose *name* contains the entire variable field and it goes into the root of that directory e.g.

c:\screenshots\image20151204ikrgtgnfls.jpg

2. I cannot get the FTP feature to work. In fact I can't find any FTP config. There is config for something called "proxy" - is that FTP? Also there is no obvious config for the path on the server, which in my case is /blahblah/screenshots and again the various images go into the root of that i.e. no new directories are created. The error message is Server committed a protocol violation, and a stacktrace of various items.

**Comment by Jaex** [comment]
Make here empty if you don't want sub folders:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/IHRo0Hht3k.png)

You can select jpg from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/0s4afPdYv6.jpg)

I don't know why your FTP upload not works. And ofc there is obvious config for the path on the server otherwise how people can use it.

**Comment by peterh337** [comment]
OK; great, many thanks. I have FTP upload working. 
There is one more issue: the FTP server path is not the same as the path which needs to be presented as the image URL. For example the FTP server path to a given file might be
/oddsandends/screenshots/image20151204hjhjhjhjh.jpg
while the URL which needs to be presented following the upload (and copied to the clipboard) would in that case be
http://www.peter123ftp.co.uk/screenshots/image20151204hjhjhjhjh.jpg
Currently I am getting e.g.
http://www.peter123ftp.co.uk/oddsandends/screenshots/image20151204hjhjhjhjh.jpg
where the "oddsandends" should not be there.
I recall spending many hours with Faststone capture, getting this to work right.

**Comment by Jaex** [comment]
HttpHomePath setting in ftp settings is key to set it correctly. Also disable AutoAddSubFolderPath setting next to it. So you can write exact url you want.

**Comment by peterh337** [comment]
OK, thanks.
I found the random-variable field config for the subfolders but as you suggest this needs to be blank because I don't want subfolders at all. Where would I find the config for *file* names?

**Comment by Jaex** [comment]
I already showed you with screenshot where that setting is.

**Comment by peterh337** [comment]
No I don't want you to take screenshot of screenshot.

I am keeping my existing solution.
