### ISSUE TITLE
Long sounds delay other sounds

### ISSUE THREAD

**Issue by Codicassert** [ShareX/ShareX#1175]
Setting a long sound as, say, custom capture sound makes the other sounds wait until the first sound has completed.

**Comment by Jaex** [comment]
Can you give me example sound to test?

**Comment by Codicassert** [comment]
I'm not at my computer right now, but i guess any long sound would suffice. Just set a long sound as your capture sound, and a different sound as your task complete sound.

I've added a notification tone from my phone to test it with here: http://www.mediafire.com/listen/egcwbsvvucflw55/TaDa.wav

**Comment by Jaex** [comment]
Look like it is not possible with default .NET methods: http://stackoverflow.com/a/4740810/264877
And I don't wanna rely on Windows Media player etc.

**Comment by Codicassert** [comment]
Mmmm, I see. I guess you can make it stop the playing sound, but i dont know how favorable that is. (It's not exactly a big deal, just dont set a 2hr symphony as your capture sound, I guess.)

**Comment by SeanLatimer** [comment]
A possible fix would be using DirectSound, that allows multiple sounds to be played at once.
But I doubt you want a dependency for DirectX on this

**Comment by Jaex** [comment]
Yes this problem not very critical to worth using other dependencies.
