### ISSUE TITLE
Option for download_url using box as a destination, particularly for images

### ISSUE THREAD

**Issue by raluaces** [ShareX/ShareX#1176]
Hi, 
Currently shareX's use of the box api gets the shared.url. Would it be possible to add an option to get the shared.download_url which provides a url directly to the file for box enterprise accounts?

in Box.cs this could probably be achieved by making
return fileEntry.shared_link.url;
into
return fileEntry.shared_link.download_url;

Also for reference see 
http://stackoverflow.com/questions/13446737/box-api-direct-link-for-music-file

Thanks!

**Comment by Jaex** [comment]
There is no download_url in my responses therefore I can't add it blindly.

**Comment by smashedr** [comment]
This can be done, a version was recompiled to support this. It would need to be added as an option as it is only available to enterprise users. Not sure why this was closed with out any further investigation. Guess all ShareX users with Box Enterprise will have to suffer until Jaex realizes this.

**Comment by Jaex** [comment]
Because I never add something without test and obviously I can't test paid service.

**Comment by smashedr** [comment]
We could probably get you a test account if you ask.

**Comment by smashedr** [comment]
I assume you unsubscribed to this thread as its closed. We will open a new issue, for this exact same problem =/

**Comment by Jaex** [comment]
I didn't unsubscribed.

**Comment by zikeji** [comment]
This isn't a problem, it's a feature request. Gotta get it right.

**Comment by raluaces** [comment]
I can provide a test enterprise account with access to this feature for the duration needed to test.

**Comment by zikeji** [comment]
The question is implementation. Do we check and see if the account is an
enterprise account and log it somewhere? That's alot of work. Or do we
simply add a "Use Raw Download URL (Enterprise Only)" that if checked, will
check the download_url value and if it's empty / doesn't exist default to
the normal URL? The last method seems like the quickest implementation.
