### ISSUE TITLE
[feature request] Add pause option when screen recording

### ISSUE THREAD

**Issue by mabbas64** [ShareX/ShareX#1183]
The video recording feature is awesome. One thing I miss daily is to have a pause option when screen-recording to video or GIF.

I hope i'm not posting in the wrong area :)

**Comment by Jaex** [comment]
#205

**Comment by zikeji** [comment]
Just cut out the unimportant bits in video editing software.

**Comment by mabbas64** [comment]
This is a great suggestion but I use on the fly recording for several
videos every hour for my job. I think I'll contribute a solution sometime
in the future to the project for this if possible.

Manually cutting out the parts from each video will be too time consuming.

Thanks!

Kind Regards,
- Abbas
