### ISSUE TITLE
Overlapping regions when using Ctrl + PrntScrn

### ISSUE THREAD

**Issue by lesydimitri** [ShareX/ShareX#1185]
If you press Ctrl+PrntScrn for a second time instead of drawing your region, a new regionselector is spawned on top of the first one.

Screenshot of the problem: 
![image](https://cloud.githubusercontent.com/assets/1854585/11687785/f6186528-9e88-11e5-9683-965bdf984c02.png)

**Comment by Jaex** [comment]
I don't see any problem. This is how you can take screenshot of region capture.
