### ISSUE TITLE
Can't view history - XML

### ISSUE THREAD

**Issue by XenRevo** [ShareX/ShareX#1186]
When trying to view the history/image history I get this error
![image](http://i.zips.me/a716f5v726.png)

**Comment by Jaex** [comment]
There is corruption happened when wrote to xml file. Open your History.xml file and check line 10364 and remove that corrupted lines. So rest of your xml file will be fine.

**Comment by XenRevo** [comment]
Couldn't see what was corrupt, so I just removed that block. 
Thanks.
