### ISSUE TITLE
ToastWindowRightClickAction [Enhancement]

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#1187]
It is possible to add configuration for ToastWindow right click?
Now on right click preview window closes. But I want file menu like on main window for use some features without opening/closing main window. For fastest upload, copy file, copy filepath and etc...

**Comment by Jaex** [comment]
#1207 like i told here adding little buttons under toast window will be better way. So it can have open, copy, upload etc. buttons. But having them customiseable etc. can be too much work.

**Comment by ValentinJesse** [comment]
If you are planning on replacing the header (which has no big relevance in showing the path)  with " Open - Copy - Upload " buttons, then i'm happy with it.  
![2015-12-27_21-02-02](https://cloud.githubusercontent.com/assets/7979136/12011584/33941318-acdd-11e5-84fa-20accf0a3e8e.png)

Customization of the header could come later, no problem.

**Comment by Jaex** [comment]
I won't like having hidden clickable region that people must guess there.

**Comment by ValentinJesse** [comment]
I see that the header appears on over. Can't you just make it permanently visible ? It's not obstructing anything

**Comment by Jaex** [comment]
It obstructing image.

**Comment by ValentinJesse** [comment]
I see, corrected my comment. Well, you can always add some margin/padding

**Comment by Jaex** [comment]
Then I told if i want to add margin then I can put buttons there anyway.

**Comment by Jaex** [comment]
Now I remembered why I didn't add that little buttons before, because that preview is dynamic size and if image width is too small then buttons won't show up fully.

**Comment by ValentinJesse** [comment]
The way i saw it was like this:

![demo](https://cloud.githubusercontent.com/assets/7979136/12011690/055aa9c2-ace1-11e5-9f0b-9c2a1a221380.png)

Remove the "path" text as it is not that relevant. Make the header visible permanently Add margin and place the buttons in there.

I see that there's an issue with the dynamic size. Set a minimum width for each capture (full screen or custom region),  make the buttons smaller and have them centered with:
margin: 0 auto;

**Comment by Jaex** [comment]
what is margin 0 auto

**Comment by ValentinJesse** [comment]
Or you can keep it simple for now and consider my previous suggestion, that in which i proposed to have the header open the "Screenshots" folder when hovering and clicking on it.

**Comment by Jaex** [comment]
I can't just add your propose. It is only works for you. Not for others. Other people need upload button etc. too.

**Comment by ValentinJesse** [comment]
Ok, i agree with you. Regarding the other question, sorry, i got caught up in HTML/CSS :). 
margin: 0 auto; is used for centering a div horizontally. In this particular case, the centering of the buttons in case that the notification changes its size.

**Comment by Jaex** [comment]
I was planning to add icon buttons without text. So more buttons can fit.

**Comment by ValentinJesse** [comment]
As long as they are easy to figure out, yes, why not. Sounds good.

**Comment by FichteFoll** [comment]
Fast uploading from the toast notification would be very nice, indeed!

**Comment by Jaex** [comment]
Added this option now:

![](https://jaex.getsharex.com/2018/11/ShareX_gEPLAYO0sq.png)

Which is not what you want too.
