### ISSUE TITLE
Tools -> Image editor -> Create new image [Enhancement]

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#1188]
ShareX image editor is very easy, fast and important and I hope use it to fast make simple diagrams or primitive images without run "paint" or other scary software. But now "Tools -> Image editor" always require existing file.

**Comment by Jaex** [comment]
It is Greenshot image editor.

**Comment by QuAzI** [comment]
It was meant

**Comment by Jaex** [comment]
I'm not planning to make improvements to Greenshot image editor. It is already so much work to merge them and for long time I didn't merge it because of insane amount of work needed to merge every single commit one by one. So I don't wanna also waste my time on adding features to it.
