### ISSUE TITLE
Autoadjust Greenshot image editor size by image size [Enhancement]

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#1189]
On the one hand there is no wish to spend working space without need, there is a wish to see the processes which are carried out in a background while you try to process a screenshot.
On the other hand the window should be developed every time to the picture sizes to see it all and to clean scrollbars.
The minimum size of a window by default - that all buttons got. ~640*480 now.
The maximum - the size of the picture or the maximized window if the picture too big.

**Comment by Jaex** [comment]
I'm not planning to make improvements to Greenshot image editor. It is already so much work to merge them and for long time I didn't merge it because of insane amount of work needed to merge every single commit one by one. So I don't wanna also waste my time on adding features to it.
