### ISSUE TITLE
Upgraded to v 10.5 Folder Preferences not preserved

### ISSUE THREAD

**Issue by SNaushadS** [ShareX/ShareX#1194]
I just installed the latest version of Sharex 10.5. After doing this i saw that the Folder Path preferences Application Settings > Paths> ShareX Personal Folderthat i had set earlier were not preserved.

How did i upgrade:
I downloaded latest copy of ShareX. 
Installed ShareX while previous version was installed.

Now, i had to change the Screen-shots folder to the custom one that i have created.

Can the upgrade experience be seamless ? Thanks.

**Comment by Jaex** [comment]
I always use custom personal folder and it always preserved so I have no idea why yours not.
