### ISSUE TITLE
[Request] Reverse Image Search

### ISSUE THREAD

**Issue by EgorkaSanyok** [ShareX/ShareX#1198]
Hey there!
It would be really nice if the option to reverse image search a specific image would be available. I tried implementing it myself via Custom uploaders, but I am totally at loss as to what I need to put in the fields in order to make it work with Google Images, for example. If anyone knows how to implement it via Custom uploaders that would also be a good solution. Thanks!

**Comment by Jaex** [comment]
I don't think it is possible to use google image with custom uploader.

**Comment by Scrxtchy** [comment]
Blood, Sweat, and Tears fused together to make the duct tape that holds this uploader together
```
{
  "Name": "googleri",
  "RequestType": "POST",
  "RequestURL": "https://www.google.com.au/searchbyimage/upload",
  "FileFormName": "encoded_image",
  "Arguments": {},
  "Headers": {},
  "ResponseType": "RedirectionURL",
  "RegexList": [
    "\\/webhp(.+)"
  ],
  "URL": "https://www.google.com.au/search$regex:1,1$",
  "ThumbnailURL": "",
  "DeletionURL": ""
}
```

**Comment by Jaex** [comment]
Nice, so needed to take part of url and append it to actual search url. I was gave up too early I guess :P

**Comment by EgorkaSanyok** [comment]
Thanks for your solution Scrxtchy!
Unfortunately, I am having trouble implementing it. Whenever I use the task, it always opens https://www.google.com.au/webhp . Maybe I did something wrong, but I can't figure it out. This is how the custom uploader looks:
http://i.imgur.com/ioSzW0l.png
And this is the task I made for it:
http://i.imgur.com/8ySODgp.png

**Comment by Jaex** [comment]
You copied fields manually look like. You needed to import them with button.

**Comment by EgorkaSanyok** [comment]
Ah, yes I saw it now. Sorry for the dumb question, I'm new at this. Thanks again!
