### ISSUE TITLE
Cannot access - FFmpegOptionsForm

### ISSUE THREAD

**Issue by westor7** [ShareX/ShareX#1199]
Hello,

An error appeared for report.

System.ObjectDisposedException: Δεν είναι δυνατή η πρόσβαση σε ένα αντικείμενο που έχει απορριφθεί.
Όνομα αντικειμένου: 'FFmpegOptionsForm'.
   σε System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   σε System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   σε ShareX.ScreenCaptureLib.FFmpegOptionsForm.DownloaderForm_InstallRequested(String filePath)
   σε ShareX.HelpersLib.DownloaderForm.OnInstallRequested()
   σε System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   σε System.Threading.ThreadHelper.ThreadStart()

ShareX 10.5 Release

Log File: http://pastebin.com/uveU4na3

- Thanks!

**Comment by Jaex** [comment]
I'm not sure how you can't access FFmpeg options window. Because that error you got is from downloading of FFmpeg and which not triggers when that window is opening.
