### ISSUE TITLE
Settings from old hdd

### ISSUE THREAD

**Issue by dex73r** [ShareX/ShareX#1200]
Hey, I was using ShareX on my old hdd but now when i reinstalled windows, I don't remember my old settings. Does ShareX have a folder where all setings are stored in? Or in short - Where are ShareX settings located?

**Comment by Jaex** [comment]
Documents/ShareX

**Comment by dex73r** [comment]
I was searching in appdata,programdata and .exe location, wouldn't think about documents haha. Thanks!
