### ISSUE TITLE
add Exit option to main window

### ISSUE THREAD

**Issue by smsrkr** [ShareX/ShareX#1201]
Can you add an Exit option to the main window? Preferably at the bottom of the left sidebar, after Donate and About options. Then ShareX can be closed from both the tray and the main window.

I know the tray icon can be disabled, and consequentially ShareX will exit when the window is closed, but then I'll miss the quick actions in tray.

**Comment by Jaex** [comment]
I don't wanna increase main window height for unnecessary thing because some people use very low resolution and main window couldn't fit their screen then.

**Comment by smsrkr** [comment]
well, how about an option like "Show Exit button in main window" in **Application Settings > General** ?

**Comment by Jaex** [comment]
@jonfre if you disable tray icon from application settings then it works exactly like that.

**Comment by StingyJack** [comment]
@Jaex - I added a [PR](https://github.com/ShareX/ShareX/pull/5331) to make the text align with most other programs that have similar functionality ("Minimize to Tray"). 

I can only do en-US as its the only language I know well enough. I hope thats not a problem.
