### ISSUE TITLE
Unable to register ANY hotkey after restart paired with clipboard not working

### ISSUE THREAD

**Issue by Goobles** [ShareX/ShareX#1204]
This is probably hard to reproduce but, any hotkey I try to configure comes up as being used
http://i.imgur.com/EuFm2o9.png

While I tried to upload THAT screenshot, something else occured as well
[log.txt](https://github.com/ShareX/ShareX/files/69859/log.txt)

It seems sometimes, ShareX is revoked access to the windows clipboard API, and when this occurs, it can't set/use any of the hotkeys as well.

This might as well be Windows 8.1 bugging out though.

**Comment by Jaex** [comment]
I have no idea how your Windows not allows to registering hotkey or interact with clipboard.

But isn't it look like it is some kind of permission issue in your OS or something like that and there is nothing I can do about it?

**Comment by Goobles** [comment]
Well, after restarting the problem didn't persist, let's just hope Microsoft becomes a better software developer.
