### ISSUE TITLE
Underlying Connection Was Closed Error

### ISSUE THREAD

**Issue by VisualStudio-zz** [ShareX/ShareX#1206]
Before I updated my server to a 4096 bit TLS certificate I was able to use my custom uploaders with it and now I can't for some reason. I've written a script in python to make sure my webserver is still working and it clearly is. Is there something wrong with ShareX in general or is it a .NET limitation with the WebClient? I've also tried writing a script in C# using a WebClient to upload a file over an HTTP POST request and that seemed to fail too.

![Error Prompt](https://i.imgur.com/gMqEI6H.jpg)

**Comment by Jaex** [comment]
We don't write any SSL stuff. It is Microsoft codes which handling that stuff. And it is same for nearly all .NET apps because people use built in web request class.
