### ISSUE TITLE
Enhancement - Notification after Capture - Make the header open the "screenshots" folder when clicking on it

### ISSUE THREAD

**Issue by ValentinJesse** [ShareX/ShareX#1207]
It would be a nice feature to have. Coming from Greenshot, i have to admit that i miss having the ability to open the folder right after the screenshot. With this feature we could have the best from the both worlds. 

![2015-12-27_11-48-50](https://cloud.githubusercontent.com/assets/7979136/12009817/10ad590e-ac92-11e5-8dcf-808be0da9905.png)

**Comment by Jaex** [comment]
That popup should have little buttons bottom of it to open, copy, upload etc.

**Comment by Jaex** [comment]
Merging this with #1187
