### ISSUE TITLE
Basic image cut/copy/paste features

### ISSUE THREAD

**Issue by Enissay** [ShareX/ShareX#1209]
Theses features are really very basic and very useful, yet they are [not implemented](https://greenshot.atlassian.net/browse/FEATURE-363) yet in Greenshot since it's an annotation tool NOT an image editor (according to some issues answers)

So i'm wondering if you can advise me of some other image editor that is compatible to use with sharex ?

**Comment by Jaex** [comment]
Paint .NET ?
