### ISSUE TITLE
Pack and upload

### ISSUE THREAD

**Issue by L1Q** [ShareX/ShareX#1210]
When uploading multiple files (especially from windows explorer context menu) I would like to have an option to automatically pack them as zip archive and then upload the archive.

**Comment by Jaex** [comment]
Then you can right click that multiple files and create zip file. Then upload that zip file. This request is beyond scope of ShareX because I can't fill right click menu of Windows with personal actions.

**Comment by L1Q** [comment]
Is it posible for sharex to detect if you are trying to upload multiple files?
If so, trigger this option.

**Comment by Jaex** [comment]
No ShareX receives files one by one and can't see is it multiple or single.
