### ISSUE TITLE
Record Screen Game - record only cursor

### ISSUE THREAD

**Issue by VadymVolos** [ShareX/ShareX#1212]
Record Screen Game - record only cursor
Game StarCraft2

![1](https://cloud.githubusercontent.com/assets/12669290/12025265/97c72b8a-adb5-11e5-81ba-e8a3d5f4e31d.png)

![2](https://cloud.githubusercontent.com/assets/12669290/12025275/c1a74822-adb5-11e5-8f57-a471c91ff8c3.png)

**Comment by corruptnova** [comment]
ShareX does not capture DirectX or OpenGL(?) applications.

**Comment by VadymVolos** [comment]
Why?

**Comment by Jaex** [comment]
Because I don't know how to do it :)

**Comment by Jaex** [comment]
#848
