### ISSUE TITLE
Tool Request: Hash generator

### ISSUE THREAD

**Issue by mrmcpowned** [ShareX/ShareX#1213]
We already have a hash verifier, so why not? Plus, it's a fairly useful tool in itself. We could even have it  integrated into the verifier as extended functionality.

**Comment by Jaex** [comment]
You mean string to hash converter? Like string to md5, sha1, base64 etc.

**Comment by Jaex** [comment]
Like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/Crypto.vshost_gMoDr7LDbY.png)

**Comment by mrmcpowned** [comment]
Yeah that is what I was asking for :)

**Comment by Jaex** [comment]
What do i call that tool then (was Hash check) after add these. Also what to name that second tab.

**Comment by mrmcpowned** [comment]
Well, you could call it "Hash Check and Verify" Both words have slightly different meanings, but both also apply here. We're checking the hashes of files but also verifying them with a given hash.

**Comment by Jaex** [comment]
What is it to do with verifying?

**Comment by mrmcpowned** [comment]
The original tool is also a verification tool, because you can set a target for what the hash should be.

**Comment by Jaex** [comment]
I thought you telling second tab is for verifying.

**Comment by mrmcpowned** [comment]
My bad, I meant to say check instead of verifying. I didn't notice that until now.

**Comment by Jaex** [comment]
Even when doing binary, base64 etc. conversation there is it good idea to still call it hash checker?

**Comment by mrmcpowned** [comment]
Well the other option is to spin off those conversions into another tool, but that would seem like an unnecessary addition to the tools list.

And even if the tool were to be renamed, it feels like whatever it would be called would be too long and make the tools menu looks awkward.

I'd say for now it's probably best to leave it as "hash check".

**Comment by Jaex** [comment]
What about these for tabs: "File hash check", "Text conversations"

**Comment by mrmcpowned** [comment]
That would work great. If you're still a bit unsure about having both in the same tool, you could include a string option in the first tab so you can check both stings and files in the same tab, and then you could make the conversions tool into a multi-conversion tool.
So like say I have a base64 encoded string and want to see what it shows in hex, binary, text, etc. The same goes for any of the other conversions, so if I paste into 1 textbox, it'll give me the result into the others.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/ShareX.vshost_Qu8CByZwKV.png)

Still not sure is tab or window name is correct too. Even my class name is horrible which is Translation because couldn't find better name for it back then when I made it :/

**Comment by mrmcpowned** [comment]
The tab titles and window name are correct :)
