### ISSUE TITLE
Uploading via tinypic is overridding imgur

### ISSUE THREAD

**Issue by cheeseluigi** [ShareX/ShareX#1214]
When I upload via clipboard or from the prompt on the right click menu ShareX uploads via tinypic even though I have my default destination set to imgur.

**Comment by Jaex** [comment]
Is this checked?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/ShareX_YGXa3loOqq.png)

**Comment by cheeseluigi** [comment]
Ah yeah that appears to be checked

**Comment by cheeseluigi** [comment]
It still isnt working, now I'm greeted with this error message: http://i.imgur.com/QOwZR00.png

**Comment by Jaex** [comment]
Wrong url.

**Comment by cheeseluigi** [comment]
Sorry: http://i.imgur.com/L4pwr8x.png

**Comment by Jaex** [comment]
Are you uploading to imgur account?

**Comment by cheeseluigi** [comment]
I was able to upload via right click and clipboard if the image is a jpg, am I just dumb or is ShareX is unable to upload PNGs to imgur?

**Comment by cheeseluigi** [comment]
I am

**Comment by Jaex** [comment]
Did you tried refreshing authentication?

**Comment by cheeseluigi** [comment]
alright well it uploaded a different png file via right click and clipboard, it appears to be just this specific photo. I have refreshed that, yes.

**Comment by Jaex** [comment]
Did you tried uploading that specific photo from their web site? If only that image not works.

**Comment by cheeseluigi** [comment]
welp I re-exported the image via gimp as a png and it worked, sorry to waste your time. Was an issue with the image.
