### ISSUE TITLE
please enable Javascript in your browser or use a browser with Javascript support< error with custom uploader?

### ISSUE THREAD

**Issue by Spikechrisgaming** [ShareX/ShareX#1216]
So i was trying to use a custom uploader and such and i'm getting this error 

```
please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>
```
How do i fix this?

My default browser has javascript enabled and my other browsers i have installed.

**Comment by Jaex** [comment]
What your browser to do with custom uploader?!

**Comment by Spikechrisgaming** [comment]
I don't know but thats just the error i'm getting..

**Comment by Jaex** [comment]
Probably that place you trying to upload checks User-Agent which is ShareX and thinks that not supports javascript.

**Comment by Spikechrisgaming** [comment]
Is there any sort of way to fix this?

**Comment by Jaex** [comment]
I don't even know where you trying to upload how am I supposed to check.

**Comment by Spikechrisgaming** [comment]
I'm using my own site which has all the stuff i need to do a custom uploader type thing on it.

**Comment by Jaex** [comment]
Then fix your web site.
