### ISSUE TITLE
Feature-Request: Pixelate region during selecting region

### ISSUE THREAD

**Issue by KennethWussmann** [ShareX/ShareX#1220]
Hey,

would be nice to pixelate a region on a screenshot during selecting the region.
For sure you can scribble with a color on parts you want to hide but to pixelate would be more beautiful.

Sorry if this is an existing feature request but I couldn't find anything about that.
Thanks,
Kenneth

**Comment by corruptnova** [comment]
You can do this in the greenshot image editor.
https://λ.pw/eFE.png

**Comment by Jaex** [comment]
Yes it is exist like corruptnova showed.
