### ISSUE TITLE
[Suggestion] High DPI Support

### ISSUE THREAD

**Issue by jiangzhenjerry** [ShareX/ShareX#1222]
I'm using a laptop with a 15.6'' 4K screen (3840x2160). The DPI scaling is set to be 250%, however many tools of ShareX are not DPI-aware and do not scale up. I am wondering whether there would be support for HiDPI sometime in the future, given that there are more and more HiDPI laptops nowadays.

1. The main windows of ShareX displays OK (although the icons are tiny, at least the functions are usable).
http://imgur.com/UzmMK4f

2. ...however the image editor is a disaster...
http://imgur.com/0238IkA

(1) The icons are way too small to use (please kindly note that the screenshot is from a 15.6'' screen);
(2) Some sub-windows, for example the color picker, are destroyed;
(3) The font size of the "step label" is fixed, and hence is generally too small compared to most of the screenshots made on my laptop. In order to add the step label properly, I have to resize my screenshots first (and sacrifice its quality).

Any thought will be appreciated!

**Comment by jiangzhenjerry** [comment]
Oops... Just realized that someone already asked about this (ticket #1079 ) and apparently dear @Jaex isn't very enthusiastic about fixing this (at least for the moment... ). Please disregard and close this ticket. I apologize for the duplicate!

**Comment by Jaex** [comment]
Where I got icons don't have more bigger size and obviously I can't draw my own icons for so many places because I'm not graphic artist.

**Comment by schlafesbruder** [comment]
But in the file IconHelper.cs there is the option to use large icons (32x32) and that option is set to 0 and the small icons 16x16 (which is the one we are complaining about I think), is set to 1. Cant you just increase the size of the icons? Or give us an option to do so?
