### ISSUE TITLE
How to back up and restore ShareX settings ?

### ISSUE THREAD

**Issue by monirulalom** [ShareX/ShareX#1227]
How to back up and restore shareX settings ?

**Comment by zingmars** [comment]
Win Vista or newer: %HOMEPATH%/Documents/ShareX
For WinXP it should be in My Documents.

Settings are in the *.json files. Just back them up and copy them to the target machine.

**Comment by Jaex** [comment]
History file is .xml so it is better for you to backup all files there except Screenshots and Tools folder. But ofc you could want to backup your screenshots too.

**Comment by MagTun** [comment]
This didn't work for me, but using the export/import option in `Application Settings` worked

**Comment by itzklyde** [comment]
> This didn't work for me, but using the export/import option in `Application Settings` worked

Of course it didn't work. You replied 4 years later lol.
