### ISSUE TITLE
SFTP - "URL is empty" error message is misleading

### ISSUE THREAD

**Issue by zingmars** [ShareX/ShareX#1228]
When changing destination settings, in particular SFTP settings, if the Keypath value is invalid (i.e. it points to a file that doesn't exist - http://i.imgur.com/qC6jpJB.png) ShareX will fail to upload images with the error "URL is empty" (http://i.imgur.com/HlgEcd1.png). There is no indication that it's a problem with the keyfile at all anywhere, as the error message is not descriptive at all. Here is an example log file - http://pastebin.com/CTYqDCR0.

**Comment by Jaex** [comment]
I can't test these things because I never have SFTP account. Therefore without try I can't fix it. Because it require me to see what SFTP library throws etc. when keyfile is missing.

**Comment by zingmars** [comment]
This is not a SFTP library problem. This is a ShareX problem.
There is no need to have an sftp account, as it never gets to making a connection. Just make a sftp profile, add an invalid path in the 'Keyfile' section and try to upload a file using that very profile.

**Comment by Jaex** [comment]
If you mean I could just check file path before create connection. That is not solution. What if keyfile is exist but invalid? That means I need to rely on SFTP library exceptions to throw proper error message.

**Comment by zingmars** [comment]
Yes, that's exactly what I mean and that already happens. The SFTP library already throws an exception if the connection fails or if the keyfile is invalid. It seems like this exception is thrown before the connection is even attempted.

**Comment by Jaex** [comment]
It should show error now I think.

**Comment by MasterCevin** [comment]
Jaex I can provide you an FTPS Server (explicit), if you want to use it.
