### ISSUE TITLE
Webm missing frame problem 

### ISSUE THREAD

**Issue by perayknox** [ShareX/ShareX#1233]
**There is a problem with webm record for me.**

I've changed all settings. 
I've tried different variations.
But nothing helps. [**Sometimes, the error doesn't appear in cmd but when I record a webm, still there is  a missing frames...**  *(onboard intel g41mxe vga)*]

(click for the full resolution)
![2016-01-09_21-35-47](https://cloud.githubusercontent.com/assets/13890542/12217980/bdd7f0ee-b719-11e5-8814-6531f68ce325.png)

**Comment by Jaex** [comment]
That happens because webm not very efficient for real time encoding. I recommend using x264 which gives far better real time encoding performance.

**Comment by perayknox** [comment]
@Jaex 
Ov thanks. I didn't know. Sorry.
