### ISSUE TITLE
ReTry Twitter upload if failed

### ISSUE THREAD

**Issue by EpicLPer** [ShareX/ShareX#1234]
It's a tiny but annoying thing. Sometimes ShareX fails to get "a secure connection" when uploading to Twitter and simply says an error message. It won't retry again and I've lost a few screenshots due to this already because I did not save them and Tweet them, I only tried to tweet them directly.

Please implement it so that the ShareX Twitter function tries again once it fails and if it fails 3 times (or more) you should be presented with an option to locally save it on your PC.

**Comment by Jaex** [comment]
Is retry option in application settings window not works for Twitter?

**Comment by EpicLPer** [comment]
Sorry, I just now found this option... I searched like an idiot before but didn't find one :P Can be closed.

Sorry again.
