### ISSUE TITLE
Preview / Notification After Screenshot

### ISSUE THREAD

**Issue by ImOnMars** [ShareX/ShareX#1235]
I like the preview when a screenshot has been taken, but I would ask that you maybe add options as to what click on the preview does. It currently opens it in your default image viewer, but I would like the option for clicking it to open the containing folder of the image.

Thanks.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/ShareX_iBRsJvgL9d.png)
