### ISSUE TITLE
Unhandled exception in uploading from clipboard (Microsoft Paint_

### ISSUE THREAD

**Issue by swablueme** [ShareX/ShareX#1237]
ShareX 10.6 Release
Steps to reproduce:
1. Open Microsoft Paint (Win 8 version)
2. Copy and paste the contents of the screen.
3. Right click sharex and upload clipboard contents 
http://pastebin.com/ZZppG5DS

**Comment by Jaex** [comment]
I fixed it now but for now you can make this setting true to make it work:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/ShareX.vshost_6xKdWB9LzB.png)
