### ISSUE TITLE
Settings: Sample Rate to 48khz?

### ISSUE THREAD

**Issue by fabiangeier** [ShareX/ShareX#1238]
When I record my screen with ShareX a standrad sample rate of 44khz is given to my audio.
Is there a way to change that to 48khz?
I am using screen-capture-recorder as video source and my auna-900-mic as audio source.

Do you need any further information?

Thank you for your help

Fabian

**Comment by Jaex** [comment]
Try these:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/ShareX_pfErl8WkqW.png)

**Comment by fabiangeier** [comment]
Thank you so much. Works fine.
