### ISSUE TITLE
Copy to Clipboard broken

### ISSUE THREAD

**Issue by HellGate94** [ShareX/ShareX#1239]
after the recent update to 10.6 the Copy to Clipboard after taking a screenshot is broken for me.
![img](http://i.imgur.com/zMVylf8.png)

trying to unset and re-set the option doesnt work.

Debug Log says: "Image copied to clipboard." but its empty

Win7 Sp1 x64

**Comment by Jaex** [comment]
You are copying file not image. Maybe you need copy image instead?

**Comment by HellGate94** [comment]
im using the german language but both "copy image to clipboard" and "copy file to clipboard" are checked in the "after capturing" settings (used to only have copy image checked but was trying to fix this issue)

and the debug log even says it was copied to clipboard

**Comment by Jaex** [comment]
I tried copy image to clipboard now and I can paste image to both Paint and Paint .NET without problem. Where you trying to paste that image? That could be the problem.

**Comment by HellGate94** [comment]
i tryed everywhere. the clipboard is empty (even checked with an old clipboard history tool of mine)

might be a permission issue from updating it?

**Comment by Jaex** [comment]
Are you sure you configured your settings properly? Like URL or image file can override image itself.

**Comment by HellGate94** [comment]
yea and i havent changed them sice i started using it (except when i was trying around after it broke).
right now its set up to save it to file (works) and copy to clipboard (doesnt work, even if the debug log says it was copied to clipboard). no upload or anything

it also overrides my clipboard with null or something that ends up being empty

**Comment by Jaex** [comment]
I keep trying it is not empty. But it is not seeing as image in few applications.

**Comment by Jaex** [comment]
You can revert to old image copy format which not supports transparency but works everywhere:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/ShareX.vshost_J2qOZyHQxC.png)

**Comment by HellGate94** [comment]
this worked! now im able to paste images in paint and other programs again. was this a change in 10.6 because i never chnaged this before and it worked fine

**Comment by Jaex** [comment]
New clipboard format was already be able to copy to Windows 10 paint. Maybe problem in previous Windows? Yes this change came with 10.6.

**Comment by HellGate94** [comment]
i suggest using the default one then on windows 7 platforms then as this might affect many users?

**Comment by Jaex** [comment]
It is not easy decision because I don't know how many software supports one format or not.

**Comment by Querijn** [comment]
Maybe add a test after copying into clipboard and use the alternative way when it's not in there?

**Comment by Jaex** [comment]
It is always there.

**Comment by BeeVee23** [comment]
I use this functionality a lot and paste to Skype, but the UseDefaultClipboardCopyImage doesn't help. Likewise, previously using ShareX with Photoshop would work (new image would offer Clipboard as a type giving the size, then pasting the clipped image in). I'll go back to 8.4 (which I have on my laptop with Win10)

B

**Comment by Jaex** [comment]
When I search ```clipboard skype``` in Google this is first result: http://getgreenshot.org/faq/how-can-i-paste-screenshots-into-skype/

So it not looks possible to do if transparency need to be supported. Unless Skype fix their clipboard support.

**Comment by stalks** [comment]
Win10 x64 -- ShareX will stop copying to clipboard and requires a restart several times a day. Can't paste into Paint / OneNote / Word / Outlook / Paint.NET. I have tried enabling/disabling UseDefaultClipboardCopyImage.

My work around is instead to save the picture, open it in Paint.NET and then copy/paste -- hardly ideal :/

**Comment by watercolorhearts** [comment]
This problem still happens on the latest version with Windows 7.

**Comment by ozarkii** [comment]
Also having problems on win7. Didn't happen with puush. Now even with the 2 options (copy image/file to clipboard) browser or link doesn't open.

**Comment by stalks** [comment]
ozarkii wrote:
> browser or link doesn't open
I think you're commenting on the wrong issue. This is about clipboard copy/paste, nothing to do with browsers or links.

**Comment by Weber-D** [comment]
I have the same problem on Windows 10 1709 when pasting images to IBM Sametime: Directly from ShareX it doesn't work. When I paste the image in MS Paint first, copy it again and paste it to Sametime, it works well. By setting `UseDefaultClipboardCopyImage` to `false` as described, everything seems to work well.
