### ISSUE TITLE
Imgur upload breaks

### ISSUE THREAD

**Issue by Karolis2011** [ShareX/ShareX#1240]
Steps to reproduce:
1. Install ShareX on two computers
2. Sign in on computer 1 with imgur account, everything works.
3. Sign in on computer 2 with same imgur account, everything works.
4. Go back to computer 1 and try to upload image, you will get 403, Forbidden.
Response:
```
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}
```

This can be issue with how imgur authorization works, but issue is solved by refreshing authorization at destination setting.

**Comment by Scrxtchy** [comment]
#1138

**Comment by Jaex** [comment]
When that error happen ShareX supposed to refresh it in latest version. Is it possible you were using previous version?

**Comment by Karolis2011** [comment]
It is plausible, I will try to update and see if it fixes it
