### ISSUE TITLE
ShareX Chrome Plugin - Choose uploader for photos

### ISSUE THREAD

**Issue by gui7vaz** [ShareX/ShareX#1244]
I have a dropbox and Imgur accounts logged in shareX. It would be nice to have the ability to choose the uploader service when uploading photos from the chrome extension.

**Comment by Jaex** [comment]
I'm not web developer therefore can't add any setting to extension itself. Even then it will be complicated to have all destinations etc. in extension.

**Comment by Densetsu** [comment]
I do have a similar dilemma:
My workflows should be able to use the default destinations but the Chrome extension always uses the default uploader config and also can't use upload filters, bypasses, do actions, etc.

If I want a specific uploader, I can only configure the default destinations for Chrome and then edit each existing (and future) workflows (and even then the extension can only partially use ShareX's basic features)


Maybe adding an option hidden until extension support is enabled in ShareX settings would do the trick ?

I'd think either a new destination menu
![image](https://user-images.githubusercontent.com/437011/42127637-b77fa67e-7c9c-11e8-8788-93db4c6054ce.png)
Or something similar to the custom uploaders config, where one could specify which uploader to use for each type of data ?
![image](https://user-images.githubusercontent.com/437011/42127805-6ced2dfe-7c9f-11e8-837e-3904d85d5ee9.png)
Or even some workflow-like menu
