### ISSUE TITLE
Cannot upload from clipboard from images made in MSPaint

### ISSUE THREAD

**Issue by dnlhrn** [ShareX/ShareX#1245]
Steps to reproduce:
Open image in MSPaint
Select segment of picture and copy to clipboard
Use upload from clipboard function to try and upload to image host

![image](https://cloud.githubusercontent.com/assets/16676038/12281120/6cf45c18-b961-11e5-9cdf-9e34ded08751.png)
![image](https://cloud.githubusercontent.com/assets/16676038/12281121/71c236de-b961-11e5-95e3-bb5961f42e93.png)

**Comment by Jaex** [comment]
#1237
