### ISSUE TITLE
Cannot "Save image to file as..." for recorded videos

### ISSUE THREAD

**Issue by slayer621** [ShareX/ShareX#1247]
Reproduction process: 
* Record region of screen with "Save image to file as..." set for "After capture" option. 

Expected result: 
* Windows dialog box appears asking where to save recorded file.

Actual result: 
* Recorded video is saved to default screenshot location.

#### In Depth Explanation
I have a hotkey task set up as follows:

![2016-01-14--03-42-28](https://cloud.githubusercontent.com/assets/9104303/12320928/036e004e-ba71-11e5-846c-34447c104f19.png)

Despite the "After capture" settings set to "After capture: Save image to file as...", the recorded video saves to my specified screenshot folder. **There is no dialog box for a custom save location**. File type (mp4, webm, etc.) does not change the outcome. 

This occurs regardless of what my default "After capture" settings. "Save image to file as..." DOES work for images captured with Screen Capture, but not for videos recorded with Screen Recording.

**Comment by Jaex** [comment]
Unfortunately that setting not applies to video recording.

**Comment by runcp10** [comment]
Hi @Jaex, Why can't the save as work for recording as it worked for screenshot? I mean, they are both just files right?
Let say I don't do any think in custom commands then is there a way for shareX to prompt save as location every time a record is created?
