### ISSUE TITLE
Feature to automatically delete file from destinations as well

### ISSUE THREAD

**Issue by matbech** [ShareX/ShareX#1248]
Currently when a file is being deleted, it is only deleted from the local file system. It would be nice if there is a function which would also delete the file from all destinations it has been uploaded to.
This could be implemented as either an option:
[x] Delete from destinations
or alternatively as an additional sub menu:
[Delete]
   Delete locally
   Delete from destinations
   Delete locally and from destinations

**Comment by Aokromes** [comment]
+1

**Comment by Jaex** [comment]
#92 #141 #1044
