### ISSUE TITLE
Copy Login is required

### ISSUE THREAD

**Issue by INFLIGERE** [ShareX/ShareX#1249]
http://a.pomf.cat/sekjvy.png

I have problems uploading webms/mp4s and such regardless of size to hosts, saying "copy login is required" wondering if anyone can help me with this problem!

**Comment by Jaex** [comment]
You have Copy file destination is selected.

**Comment by INFLIGERE** [comment]
Sorry I don't quite understand, I want it to have the uploaded webm/file copied when it's uploaded?

**Comment by Jaex** [comment]
You are uploading to wrong destination.

**Comment by INFLIGERE** [comment]
Thanks a lot sorted!
