### ISSUE TITLE
Tray icon is pixelated on hidpi displays after startup

### ISSUE THREAD

**Issue by vemacs** [ShareX/ShareX#1251]
Screenshot of issue: 

![](https://i.imgur.com/1iEfXKQ.png)

The strange part is that the icon fixes itself after a screenshot is uploaded. Could the 32x32 icon be also used at startup?

**Comment by Jaex** [comment]
In both startup and after progress change it using same codes to change tray icon so I don't understand how it works properly after screenshot is uploaded.

**Comment by Jaex** [comment]
Are you be able to compile and test this if I add manually getting correct icon size code?

**Comment by vemacs** [comment]
Seems to be fixed with 10.6.1. Thanks.
