### ISSUE TITLE
Video Upload

### ISSUE THREAD

**Issue by MrFarbodD** [ShareX/ShareX#1252]
I got this error the first time I tried to capture and upload a video:

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.FileUploaders.Dropbox.GetPublicURL(String path)
   at ShareX.UploadersLib.FileUploaders.Dropbox.CheckEarlyURLCopy(String path, String fileName)
   at ShareX.UploadersLib.FileUploaders.Dropbox.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.FileUploaders.Dropbox.GetPublicURL(String path)
   at ShareX.UploadersLib.FileUploaders.Dropbox.CheckEarlyURLCopy(String path, String fileName)
   at ShareX.UploadersLib.FileUploaders.Dropbox.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
Were you logged in to Dropbox?

**Comment by MrFarbodD** [comment]
Do I login from the Dropbox website or is there a setting where I have to enter my information in on the application?

**Comment by Jaex** [comment]
In destination settings window.

**Comment by MrFarbodD** [comment]
Oh I hadn't seen that before, I'll try again with the information entered there. Thanks.

**Comment by MrFarbodD** [comment]
Everything seems to be working now, thanks!

Suggestion: Instead of displaying the exception messages, it would help to display user friendly messages such as: "Failed to upload video. Please login to your dropbox account from the destination settings menu."

I also encountered another exception messages when trying to refresh my MEGA folder list, something about API session expiring, didn't take a picture or note it.

**Comment by Jaex** [comment]
It already supposed to display user friendly message. Not sure how it didn't for you.

**Comment by MrFarbodD** [comment]
That's odd, maybe it's worth looking into? Here's exactly what happened:

1. Clean install of ShareX (First time ever downloading and installing).
2. Tried to upload video.
3. Received exception.

**Comment by xnite** [comment]
Alright it was actually configured to do dropbox (which I didn't setup) after all. I switched my destination to the FTP server I configured and it worked just fine.

**Comment by Jaex** [comment]
Look like this problem happens when EarlyCopyURL is true and Dropbox is not configured.

**Comment by ohboy123** [comment]
`https://www.dropbox.com/s/w7k3j1h1nllvgvx/census_010416.db.bz2?dl=0

**Comment by Jaex** [comment]
?
