### ISSUE TITLE
ShareX not picking up my keyboard macro keys.

### ISSUE THREAD

**Issue by Choonce** [ShareX/ShareX#1256]
Hello! 

Recently I got a logitech G510, and using the software made a macro for "alt+0" on one of the keys, and then set it in ShareX to take a screenshot when I press it, but it doesn't seem to be working. 

Pressing the hotkey without the macro works fine, but for some reason it won't accept the macro key. Is there a workaround fix for this? Or a setting I'm missing?

Thanks.

**Comment by Jaex** [comment]
I tried with G502 to use "alt+0" and it works fine:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/explorer_IvUTsL8cIT.png)

**Comment by Choonce** [comment]
I just double checked and fixed it - apparently running logitech gaming software as admin fixed the issue for me.
