### ISSUE TITLE
[ Google Drive ] File Uploader Destination Issue [ v10.6 ]

### ISSUE THREAD

**Issue by psychednicole** [ShareX/ShareX#1257]
Hi..
I have noticed this bug occurring a lot.. actually it occurs always..
Uhh the destination ( Default destination ) for " File Uploader " option gets reset to Sendspace after every reboot..
Only after I realize that my file was uploaded on Sendspace, I have to change it back to Google Drive and re-upload my file..

I'd just post the settings I have in ShareX which I find to be somewhat relevant.

File Uploader ( Destination ) :- Google Drive & Signed in ( Obvious ) 
Status :- Logged in.
Upload type :- Private upload
Upload to :- A folder I have specified..

My IP :- Dynamic
ShareX Version :- 10.6 ( Latest out there as of now )
Platform :- Windows 8.1 Pro 

Please check it up ! Thanks !

**Comment by Jaex** [comment]
For some reason in some peoples computer when Windows shutdown, Windows never waits for ShareX to save settings. So there is nothing I can do about it. But I added in many places saving like when main window minimize to tray or close. Or when setting windows closing etc. So how you never minimize ShareX to tray all this time and it is unable to save?

**Comment by Jaex** [comment]
#702
