### ISSUE TITLE
Crash on use scrolling capture on twitter

### ISSUE THREAD

**Issue by XCanG** [ShareX/ShareX#1258]
Use tool "Share with scrolling" on some twitter page. Custom settings: "Simulate mouse wheel scrolling" and Max scrolling = 10, any other is default.

Error window say:
>System.ArgumentException: Недопустимый параметр.
   в System.Drawing.Image.get_Width()
   в System.Drawing.Image.get_Size()
   в System.Windows.Forms.PictureBox.GetPreferredSizeCore(Size proposedSize)
   в System.Windows.Forms.Control.GetPreferredSize(Size proposedSize)
   в System.Windows.Forms.Layout.DefaultLayout.LayoutAutoSizedControls(IArrangedElement container)
   в System.Windows.Forms.Layout.DefaultLayout.xLayout(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
   в System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   в System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   в System.Windows.Forms.ScrollableControl.OnLayout(LayoutEventArgs levent)
   в System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   в System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   в System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   в System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   в System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   в System.Windows.Forms.TabPage.set_Visible(Boolean value)
   в System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   в System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   в System.Windows.Forms.TabControl.WmSelChange()
   в System.Windows.Forms.TabControl.set_SelectedIndex(Int32 value)
   в System.Windows.Forms.TabControl.set_SelectedTab(TabPage value)
   в ShareX.ScreenCaptureLib.ScrollingCaptureForm.StopCapture()
   в ShareX.ScreenCaptureLib.ScrollingCaptureForm.captureTimer_Tick(Object sender, EventArgs e)
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

>ShareX 10.6 Release

P.S. Russian localisation

**Comment by Jaex** [comment]
Unfortunately I can't reproduce.

**Comment by XCanG** [comment]
What you need? may be recording a video? (can do by recording in OBS)

**Comment by Jaex** [comment]
If I can reproduce one problem it will be very easy to debug and fix. Now I have no idea how it never happens to me and happens to you.

**Comment by XCanG** [comment]
Recorded! Step-by-step: 1) Run program, 2) Open this tool, 3) Record page, 4) On Output page (where image) change some field, 5) Do same function again (no need to change settings) and program will be constantly crashed (every time try).

https://dl.dropboxusercontent.com/u/32566772/ShareX/Desktop%2001.18.2016%20-%2017.14.41.09.mp4

**Comment by Jaex** [comment]
Oh I see it happens in second scrolling capture therefore I couldn't reproduce it.

**Comment by Jaex** [comment]
By the way why you don't use ShareX screen recorder?!

**Comment by Jaex** [comment]
Released new version can you test?

**Comment by XCanG** [comment]
If I do same steps bug don't appear (fixed). Thanks.
