### ISSUE TITLE
High DPI Icon broken with latest update

### ISSUE THREAD

**Issue by HeyItsJono** [ShareX/ShareX#1259]
Hi there,

After the latest update (10.6.1), my system tray icon is all distorted and glitched when it used to display perfectly:

![distorted icon](http://i.imgur.com/e7dw8PE.png)

I'm on the [Medium (125%)](http://i.imgur.com/39kFdjn.png) scaling setting because my 1920x1080 laptop screen resolution is too high and everything is tiny otherwise, so I have to scale up a bit.  Any help in fixing this would be appreciated! Thanks!

**Comment by Jaex** [comment]
That is weird #1251 in he was told it is fixed in high dpi but this time yours broken.

**Comment by Jaex** [comment]
@vemacs I'm testing 150% DPI now and with both old and new codes it looks same:

150%
Old code: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/euphW7AMrD.png)
New code: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/yxyv4mONqH.png)

But for 125% old code better:

125%
Old code: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/JG9J6xjZ9Y.png)
New code: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/RBdU5VAkRE.png)

So I'm not sure how old code was causing problems in your computer.

**Comment by vemacs** [comment]
My scaling is at 200%.

**Comment by Jaex** [comment]
200%

New code: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/WD77jedchq.png)
Old code: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/K3NyvnJ4FY.png)

**Comment by vemacs** [comment]
Weird then. I'll see if I can reproduce when you revert it?

**Comment by HeyItsJono** [comment]
I think it's just the dodgy way Windows handles High DPI scaling. If there's any way to detect if the scaling amount is 125% and in that case use the old icon, that would be awesome.
