### ISSUE TITLE
Archive when loading multiple files.

### ISSUE THREAD

**Issue by Greeka67** [ShareX/ShareX#1260]
If you select multiple files to upload, archive first, and then download. Temporary archive is stored in the Temp folder, then remove load.
Offer in setting specifies the path to the program archive.
Select multiple files - Upload with ShareX - Automatic creation of the archive - the load on the file sharing.

**Comment by Jaex** [comment]
I don't understand what you mean.

**Comment by Greeka67** [comment]
Select multiple files - Upload with ShareX - Automatic creation of the archive - the load on the file sharing.

**Comment by Jaex** [comment]
I'm not planning to add auto archiving. Also it won't be possible to detect is multiple files selected when using Windows shell context menu upload or Windows send to menu anyway. Because those send files to ShareX one by one.
