### ISSUE TITLE
Clipboard images uploaded with a side border

### ISSUE THREAD

**Issue by djprmf** [ShareX/ShareX#1261]
I have been noticing a strange problem in uploaded images from the clipboard.

When a image is uploaded from the clipboard, a little border is added to the left. Appears that this border is from the other side of the imagem (as a "wrong crop").

For instance:
Original image: http://i.imgur.com/WJd84v7.jpg
Uploaded image: http://i.imgur.com/8zhpyU6.jpg

Is possible see the border in the second image, being a part of the other end of that image.
Also, this only appears to happend when the image is uploaded from the clipboard. From other method everything works fine.

Is this a bug in the recents versions?

Thanks

**Comment by Jaex** [comment]
Where you copy that image from?

**Comment by djprmf** [comment]
From the Google Image Search.

But i think this is related with the browser.
The problem happends in the Chrome (i am using the version 48.0.2564.79 beta-m 64-bit - latest beta). In the Edge he works just fine and the image is uploaded without the problem.

**Comment by Jaex** [comment]
I can reproduce it too.

**Comment by Jaex** [comment]
For now you can use this to revert to old way:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/ShareX.vshost_pN59Xki38V.png)

**Comment by djprmf** [comment]
Thanks a lot for the quick help.
That solve the problem. :+1:
