### ISSUE TITLE
ShareX automatic update

### ISSUE THREAD

**Issue by iamxerc** [ShareX/ShareX#1263]
Hi

For a normal day user, i think it is perfect the way this program is being updated often. However, I would really like there to be an advanced option or something, for it to handle this in the background.
We have the "AutoCheckUpdate", I would also like a "AutoInstallUpdate".

**Comment by Jaex** [comment]
I can't just update without ask user. It can close suddenly when user trying to use ShareX.

**Comment by iamxerc** [comment]
You can do it upon startup. you can check to see if sharex does anything exactly at that point and wait.
If the user ticks this to true, they probably know the risks..

**Comment by CFusion** [comment]
I came here to request a similar feature please consider this enhancement.

I would recommend the most common approach which is downloading updates in the background and applying them automatically next time the application is started. With maybe an exception to ask the user to restart if the version is more then X days out of date.

**Comment by Jaex** [comment]
I already implemented this in Steam build by the way.
