### ISSUE TITLE
Please add an After Capture Task: Show in Explorer

### ISSUE THREAD

**Issue by moniuch** [ShareX/ShareX#1265]
Rather than digging up the current screenshot folder with right click, I'd rather have the saved screenshot file revealed automatically. Thanks.

**Comment by junderhill** [comment]
This would definitly be a worth while enhancement. I may try and implement this if I get chance.

**Comment by moniuch** [comment]
Hi,

Thanks for recognizing the demand.

It would also be helpful to have a global system key combo for opening the
current screenshot folder. It is difficult to do so from within an external
shortcut utility because the folder name changes each month.

Regards and thanks for your work,
Artur

**Comment by Jaex** [comment]
There is already hotkey for it:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/ShareX_zSplkHurNT.png)

**Comment by moniuch** [comment]
Good call on the screenshot folder task. Haven't realized one could add
that.
I expected though that after defining such a task it would appear as an
option in the list of after capture tasks. This is however not the case. So
how can I now use the task as After Capture part?
