### ISSUE TITLE
Crash on startup for some reason

### ISSUE THREAD

**Issue by lcontant** [ShareX/ShareX#1266]
The program wont start anymore here is the print stack

**Comment by lcontant** [comment]
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
   à ShareX.TaskSettings..ctor()
   à ShareX.ApplicationConfig..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance[T]()
   à ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   à ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   à ShareX.Program.LoadProgramSettings()
   à ShareX.Program.Run()
   à ShareX.Program.Main(String[] args)

ShareX 10.6.1 Release

**Comment by Jaex** [comment]
That means dll is corrupt. Reinstalling ShareX solves it.
