### ISSUE TITLE
$"..." not supported in visual studio 2013

### ISSUE THREAD

**Issue by jevanpipitone** [ShareX/ShareX#1268]
The solution file (ShareX.sln) says minimum version visual studio 2010 current version 2014. However the code includes programming code such as:

sb.AppendLine($"CRC-32: {CRC32}");

in

public string HashToString()

of Translator.cs

where the $".." command is not supported in visual studio 2013 which I am using. Options to fix this issue could be:

- Everyone moves to visual studio 2015

OR

- Change the code to remove all instances of $".." and replace with alternative code

If you want me to change it just let me know and I'll do it and then create a pull request.

**Comment by Jaex** [comment]
I'm not planning to remove handy new features just because people want to use old version of VS.
