### ISSUE TITLE
[QUESTION] How do I rename text file extensions?

### ISSUE THREAD

**Issue by dumbninja22** [ShareX/ShareX#1269]
I am using ShareX to upload files to my host. My host does not allow viewing of .txt files, but if you changed the extension to anything else, or even removed the extension, it works fine.

So my question is, how do I make every single text file have no extension, while keeping the extensions of other file uploads?

**Comment by Jaex** [comment]
Is this not what you want?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/ShareX_m9AYznF5is.png)

**Comment by dumbninja22** [comment]
That only works for copy-paste text

**Comment by Jaex** [comment]
You need to solve this problem with your host other than you nobody would require such feature.
