### ISSUE TITLE
please just highlight the taskbar instead of flashing when app needs attention

### ISSUE THREAD

**Issue by mailinglists35** [ShareX/ShareX#1271]
for example when it wants to update, taskbar keeps on flashing.
a less intrusive way would be just to highlight the taskbar and keep it that way.
flashing indicates an emergency and should be used only for emergencies, which sharex does not belong to. it's quite annoying.

**Comment by Jaex** [comment]
What you mean by highlight the taskbar? Only flashing once?

**Comment by corruptnova** [comment]
He means just having the taskbar icon notification stay solid instead of flashing. Flashing the taskbar icon indicates attention and has nothing to do with the "urgency" of a particular notification. No real reason to change it, I'd say just get use to it.

**Comment by mailinglists35** [comment]
@corruptnova flashing taskbar infinitely means URGENCY
just highlighting the taskbar item means ATTENTION.

URGENCY is very annoying as you have to interact with it to make it stop flashing.

**Comment by mailinglists35** [comment]
@Jaex yes, just like putty does.
see this screencast example http://i.imgur.com/ON2t80H.gifv

**Comment by Jaex** [comment]
Highlighting will be enough too I guess for people to notice it.

**Comment by mailinglists35** [comment]
10 times? seriously? why 10 times? it's too aggressive! 10 times or forever, it's as annoying as flashing forever...
