### ISSUE TITLE
Scrolling Capture is severely limited

### ISSUE THREAD

**Issue by xnite** [ShareX/ShareX#1275]
The scrolling capture method will not do more than 100 scrolls which isn't nearly enough to capture most of the things I use it for. I have been using Fast Stone Capture (A paid program) for years to do scrolling captures and it pretty much scrolls until I tell it to stop or until it cannot scroll any more. I can't seem to get ShareX to do this, so it leaves me still using 2 programs, one of which will do this for me, and ofc ShareX which I love for the ability to setup destinations to automatically upload to.

**Comment by xnite** [comment]
Was going to take a screen recording to better describe what I am talking about... but see #1277

**Comment by Jaex** [comment]
Reason why I limited max scrolls because it is impossible to detect end of scroll in every single cases. Like if one web page video running in bottom of screen then all checks will fail because all images taken never same as each other. And obviously not all windows supports detecting scroll position. So for pre caution I was added limit so it won't try to scroll forever and never be able to stop it.

**Comment by xnite** [comment]
What about letting the user determine when they would like it to stop? For example with Faststone I can just hit the escape key and it's done and saves what it has. I'm not sure if there is a way (i haven't found one) but the best method I could find for scrolling so far was by emulating mouse weel, it doesn't scroll very far before stopping. Is there maybe at least a way to make it scroll further before capture so it gets more new data per capture?

**Comment by Betsy25** [comment]
I tried capturing my logins from Firefox, but even though i saw the scrolling, the end result of the capture was only 1/100th of what it should be.

**Comment by Jaex** [comment]
Also another reason to limit it to 100 was, checking each image and comparing them pixel by pixel is very time consuming and even having 100 scrolls can take more than minute to calculate. So it was not good idea to have very high amount of images to compare.

**Comment by Betsy25** [comment]
Then why not simple limit the scroll in the first place, the way it currently is, it scrolls perfectly fine over all the contents, giving the user the false idea that it's getting captured while he's just waiting for a worthless result.

**Comment by Jaex** [comment]
My message was to @xnite.

**Comment by mertmd** [comment]
Well this answer is not solving our problem, Jaex. 
I found a side path for unfinished scrolling. 

**For users who are having the same issue:**
When your scrolling is interrupted, just capture your screen second time with this little change:

![2016-08-18_22-12-11](https://cloud.githubusercontent.com/assets/9222621/17787231/ee1c60b6-6590-11e6-92f3-8f3af65cbf76.gif)
[Scroll top method before capture must be "Disable scrolling to top"]

So capturing can be continued that way as much as you want.
And you can merge images with Photoshop etc.

**Comment by mikeyww** [comment]
Issues cited by xnite are still significant and make the scrolling capture feature non-functional.

**Comment by blackwhattack** [comment]
Problem still present as mikeyww put it.

**Comment by MaxHayman** [comment]
Fix please

**Comment by OfficialFractal** [comment]
please consider at _least_ raising the maximum to 1,000-10,000 if you aren't going to give us the option to remove the cap and manually stop the capture :(

**Comment by MaxHayman** [comment]
+1

**Comment by danbromberg** [comment]
Can someone please point me to Sharex's (v12.4.1) **SCROLLING CAPTURE** method?
I see how to request it and sometimes the scroll bar scrolls for a few pages but then stops?!?
And then sometimes nothing happens at all.
Surely SHAREX must publish their documentation in a HELP file or manual somewhere!?
I just cannot find it.

Thanks in anticipation to all who reply.
Dan

**Comment by Cid-Lothbrock** [comment]
With the **Simulate mouse wheel scrolling** option, what I do to increase the distance travelled is change how many lines it covers each time it's rolled in **Settings>Devices>Mouse**. I don't know if this is a known workaround and I know it's impractical but in the first try I went from covering a web page in 33 pictures to 7, and probably I could have pushed it further.

**Comment by regs01** [comment]
Is it possible to simulate touch scroll (panning). I.e. hold mouse button and move to some number of pixels. Or completely manually?

**Comment by neilrush** [comment]
Scrolling capture should work like snagit. Just click start, manually scroll, and hit stop. No need for detecting the end of the page.

**Comment by mclovinf50** [comment]
> Also another reason to limit it to 100 was, checking each image and comparing them pixel by pixel is very time consuming and even having 100 scrolls can take more than minute to calculate. So it was not good idea to have very high amount of images to compare.

Interesting, but when I do scrolling capture with 100 screenshots, it takes about 4 seconds finish. This is with AMD 3700X CPU. When it was taking over a minute for you, what processor did you run it with? If you can, allowing the user to change the max would be very helpful.

**Comment by sweetins** [comment]
> Reason why I limited max scrolls because it is impossible to detect end of scroll in every single cases. Like if one web page have video running in bottom of screen then all checks will fail because all images taken never same as each other. And obviously not all windows supports detecting scroll position. So for pre caution I was added limit so it won't try to scroll forever and never be able to stop it. This is very rare case ofc. It mainly can detect end of scroll. But even for 1% chance I needed to take pre caution.

I use scroll capture mainly for a pdf document, there isn't any video to worry about but regardless, am limited to 100 scrolls. Certainly, an option to accommodate higher scroll number or scroll till stopped (a key press or other means), with a caution message of a sort will be very helpful.

**Comment by Jaex** [comment]
I'm remaking scrolling capture from scratch now and new scrolling capture don't have scroll limit anymore.
You can test it using [dev build](https://getsharex.com/docs/dev-builds).

**Comment by HyperSane** [comment]
still doesn't work.
