### ISSUE TITLE
Chrome extension no longer working with latest update 10.6.1

### ISSUE THREAD

**Issue by MrMugzy** [ShareX/ShareX#1278]
Worked fine in previous versions.  Getting an Windows 8.1 error notification box:  "ShareX Chrome has stopped working.  A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available."

Did a second install of 10.6.1 - unresolved
Removed and re enabled chrome extension - unresolved 
Used chrome clean up tool - unresolved
Rebooted - unresolved

**Comment by Jaex** [comment]
Problem was ShareX_Chrome.exe was expecting older version of json library so updated it to use latest version.

https://github.com/ShareX/ShareX_Chrome/commit/29467f488f484533dd4313cd7dd0d6a0baf10a56

**Comment by thedanioner** [comment]
What is the solution? I do not understand

**Comment by Jaex** [comment]
Either I can upload fixed exe for you or you can wait for new release.

**Comment by Jaex** [comment]
[ShareX.zip](https://github.com/ShareX/ShareX/files/97823/ShareX.zip)

Extract this to ShareX folder.

**Comment by MrMugzy** [comment]
Thanks, works like a charm again.

**Comment by thedanioner** [comment]
Work Fine, Thanks,

**Comment by gui7vaz** [comment]
Working fine again :)
Thank you so much!
