### ISSUE TITLE
Default upload host keeps changing after restart to TinyPic

### ISSUE THREAD

**Issue by ljparabolic** [ShareX/ShareX#1279]
Every time I'm restarting the ShareX or Windows the default upload host keeps changing to TinyPic and I have to manually switch it again.

**Comment by Jaex** [comment]
Need to check debug log or logs to see is saving fails or loading fails.

**Comment by ljparabolic** [comment]
I had this issue for about 3 weeks now but it seems to be working fine after a second restart after reinstalling the software.

**Comment by Jaex** [comment]
Also are you it is not fallback system if your primary uploader is fails.

**Comment by ljparabolic** [comment]
I haven't enabled a secondary upload. I usually just get an error if there is a problem.
