### ISSUE TITLE
"Run as administrator" prevent screenshot creation

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#128]
Hot keys not work when I run applications via "Run as administrator". If I click on taskbar then I can screen any

**Comment by Venryx** [comment]
I finally figured out why some hotkeys get blocked on certain windows (when ShareX isn't run as admin/elevated). See here for details: https://github.com/ShareX/ShareX/issues/334#issuecomment-610259444

**Short explanation**: For non-elevated ShareX, Windows blocks hotkeys when an elevated window is focused, **and** the hotkey in question does not include any modifier keys.

**Short solution**: Include at least one modifier key in all of your hotkeys.
