### ISSUE TITLE
Disable automatic upload

### ISSUE THREAD

**Issue by tekkeitserktok** [ShareX/ShareX#1281]
Hello,

Is there any way to stop automatic upload ?
I can't find it in settings...

This happens when I do an drag and drop in the main window

Thank you :)

**Comment by Scrxtchy** [comment]
![](https://jii.moe/VkJ-k3Ydl.png)

**Comment by Jaex** [comment]
There is no setting to disable drag and drop upload. Because if you don't want to upload then why would you drag file to it?!

**Comment by tekkeitserktok** [comment]
@Jaex 

Ok, maybe it wasn't clear.
Imagine you want to edit a picture with ShareX. Any picture, even a one taken with ShareX.

* Open ShareX
* A window appears ! -> This one: http://i.imgur.com/RkkFqWb.png
* Drag and drop a file in this window
* ShareX uploads the file

I just want to disable this upload feature. Is it possible ?

You said "why would you drag file to it ?!" 
* Answer: In order to edit it, and using drag and drop in order to open it with ShareX

**Comment by dannoe** [comment]
What about just making the Picture Editor able to accept files by drag&drop?

**Comment by McoreD** [comment]
It should be possible to customize Drag n Drop workflow.

**Comment by jevanpipitone** [comment]
If you open the editor using Tools, it asks for a file name, so it doesn't allow for drag and drop. Once in the editor, you can't open another file. Perhaps it might be possible to add a destination of "None" for the upload destinations? This would be in the first Destination menu, and means no upload for any type (file, text, image). Would that be a good idea, what do you think?

**Comment by Jaex** [comment]
If you enable this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/ufyp3yySZ9.png)

then after capture tasks will be applied to drag n drop and you can just open editor with no upload option.

**Comment by miklide** [comment]
@Jaex enable what? D:
![chrome_2017-09-03_23-48-28](https://user-images.githubusercontent.com/6789264/30004969-977f19ee-9102-11e7-8697-b64f0c5daeef.png)

**Comment by Jaex** [comment]
Updated image link.

**Comment by WiliTest** [comment]
thanks but the problem is that, with this option, it now copy the file to the shareX folder (when the option is set to false the files stayed in their directory while editing it which is more logical)

**Comment by Xant1k** [comment]
+1 for _Disable automatic upload when I do an drag and drop in the main window_

**Comment by WiliTest** [comment]
when we set `ProcessImagesDuringFileUpload` to True, it now copies the file to the shareX folder (when we edit with shareX, the files should be saved in its location). (When the option is set to False, after editing, the file is saved in the directory it belongs, which is more logical).

I wish I could use shareX editor to edit my images(*), but this is just too complicate since shareX either upload the picture I want to edit, or it saves it in another location.

(*)To edit the image using the context menu I simply changed HKEY_CLASSES_ROOT\SystemFileAssociations\image\shell\edit\commandchange "%systemroot%\system32\mspaint.exe" "%1" with "C:\Program Files\ShareX\ShareX.exe" "%1"

**Comment by Jaex** [comment]
@WiliTest ShareX already have option to add edit button to context menu:

![](https://jaex.getsharex.com/2019/06/ShareX_s6BaeMbItc.png)

**Comment by WiliTest** [comment]
Thanks Jaex! (Just found out it also works with the registry posted above). But unfortunately, that doesn't solve the issue mentioned above (it either upload the picture I want to edit, or it moves it)

**Comment by Jaex** [comment]
It neither move or upload image for me. It just saves to where I opened it.

**Comment by WiliTest** [comment]
Oh my bad, it's working as you say, it doesn't move the file and it doesn't upload when editing!
 I apologize, and thank you for your quick answer!

**Comment by Binapps** [comment]
> If you enable this:
> 
> ![](https://camo.githubusercontent.com/12ac2ec81b6db935ecabff213b05ab3de0bc974eb7324c03a54036fca3ac6dd9/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323031372f30392f75667970337979535a392e706e67)
> 
> then after capture tasks will be applied to drag n drop and you can just open editor with no upload option.

This really solves the problem. Thank you very much for that 😄 

I would like to recommend. It seems that the parameter has another purpose and as a side effect, it does what is required in this issue. It should have a better name or a specific parameter should be created for this purpose. but the parameter name is so confused.
