### ISSUE TITLE
Rewrite TinyPic Image URL to Direct Picture URL

### ISSUE THREAD

**Issue by iMehSharp** [ShareX/ShareX#1283]
https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/ImageUploaders/TinyPicUploader.cs

Image in the TinyPic Gallery (bad to link due to all the advertisment, spammy website)
http://i64.tinypic.com/v7cnip.png

Direct Picture (clean website, only the picture)
http://oi64.tinypic.com/v7cnip.jpg

**Comment by Jaex** [comment]
Your direct link opened gallery in first open too. In second open showed direct image.
