### ISSUE TITLE
ShareX Error after unexpected system-reboot

### ISSUE THREAD

**Issue by xyntron** [ShareX/ShareX#1285]
I recieve an error every time I have unexpected system-reboot, which doesn't allow me to run the program. After reinstalling shareX everything works fine. Here is the an error:

> System.Reflection.TargetInvocationException: Obiekt docelowy wywołania zgłosił wyjątek. ---> System.BadImageFormatException: Nie można załadować pliku lub zestawu 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' lub jednej z jego zależności. Oczekiwano, że moduł będzie zawierał manifest zestawu.
   w ShareX.TaskSettings..ctor()
   w ShareX.ApplicationConfig..ctor()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   w System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   w System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   w System.Activator.CreateInstance[T]()
   w ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   w ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   w ShareX.Program.LoadProgramSettings()
   w ShareX.Program.Run()
   w ShareX.Program.Main(String[] args)

> ShareX 10.6.1 Release

**Comment by Jaex** [comment]
That means dll file become corrupt and need to be reinstalled.

#1049

**Comment by xyntron** [comment]
Is it possible to fix it somehow? It's annoying to reinstall it every time. And I recieve this error kinda often.

**Comment by Jaex** [comment]
I have no idea how it becomes corrupt randomly in some people computer. Something installed in users computer could be causing this etc. so there is no way I can figure it out.
