### ISSUE TITLE
screen recording, audio/video delay/offset?

### ISSUE THREAD

**Issue by njorder** [ShareX/ShareX#1287]
Is there a way to control the audio/video delay for screen recording?

I'm using GDI grab and integrated microphone, with webcam on screen. And result due delay is not presentable..

**Comment by Jaex** [comment]
Did you tried using video-screen-recorder video device. It can be synced properly.

**Comment by vedranius** [comment]
I can reproduce this.
Whatever ffmpeg settings I use, async happens.
And yes, I'm using video-screen-recorder and audio-screen-recorder to record system audio.
And audio isn't in sync.

**Comment by HeCorr** [comment]
6 years later and I'm facing the same issue. when using the suggested `virtual-audio-capturer`, the audio gets completely desynced from the video. I had to use Windows' "Stereo Mix" thing and now all my recordings start with a little static pop, but at least they're usable now...

**Comment by HeCorr** [comment]
unfortunately none of the options are good. on my dual-monitor system with different screen resolutions (and scale) the cursor is large in one screen and offset in the other.

**Comment by minnieoo** [comment]
still nothin? shit
