### ISSUE TITLE
Screen recording default settings

### ISSUE THREAD

**Issue by SpoinkyNL** [ShareX/ShareX#1295]
Hey folks, 
ShareX is a great tool, very handy indeed.

I just wanted to drop this, until recently I thought screen recordings could only be done in mp4 and uploaded to Dropbox. 

Granted, I didn't look very far but wouldn't it make more sense to have it record a GIF and upload that to imgur by default?

**Comment by Jaex** [comment]
Imgur API not allows uploading more than 10mb gif which makes majority of gifs fail to upload.

**Comment by SpoinkyNL** [comment]
Right.. the uploader isn't important, it could be gfycat as well. What I'm trying to say is that it would just make more sense to record GIFs and upload those by default.

**Comment by Jaex** [comment]
GIFs mainly atleast 10x more size than video also only 256 colors which means horrible quality also takes more time to encode. So GIF is bad in every single way so why would I make GIF default instead of x264.
