### ISSUE TITLE
someimage API does not give direct url link

### ISSUE THREAD

**Issue by 2c2c** [ShareX/ShareX#1298]
this can be hacked together, but their api explicitly avoids giving a direct link

image id is consistent from their 'direct' link to the actual image file

a `http://someimage.com/asdf` direct link leads to a direct image of `https://i1.someimage.com/asdf.filetype` in every file ive uploaded. but it's kind of unsafe to assume they'll always use `i1` as subdomain

I like this host because I havent hit a filesize cap :p

**Comment by jevanpipitone** [comment]
Hi I have done another pull request with the resx fixed and the latest changes incorporated
