### ISSUE TITLE
Add on-screen editing when capturing a rectangle.

### ISSUE THREAD

**Issue by be5invis** [ShareX/ShareX#13]
I am a Chinese user and before using ShareX I use QQ to capture screen. The screenshoting feature is very convinent. It is a two-step capturing workflow:
1. Draw an rectangle on the screen, just like the current ShareX. However, QQ snapshot can also pick a window during this time. 
2. On-screen editing phase. In this step you can adjust the area you choose, or make some simple painting directly on the screen. To confirm a capture you have to click the "完成"(Finish) button.

The step 2 is very convinent if you are going to add some notes on your picture. I am wondrging that ShareX can add this feature.

Besides, the QQ capture cannot deal with high DPI correctly.

![Before Click](http://ww3.sinaimg.cn/large/798f7769gw1eb45y1ndemj21hc0u0dm2.jpg)

![After Click](http://ww2.sinaimg.cn/large/798f7769gw1eb460grv0dj21hc0u0wlf.jpg)

**Comment by Jaex** [comment]
Adding annotation support inside rectangle capture now:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/ShareX_3Js1MVF5xH.png)
