### ISSUE TITLE
Language-specific hotkey descriptions

### ISSUE THREAD

**Issue by dannoe** [ShareX/ShareX#1306]
E.g. on German keyboards the Control-Key (Ctrl) is named "Strg". And "Shift" is called "Umschalt".
But at the moment they are hard coded in the `HotkeyInfo.cs`

Can I add them to the resource files?

**Comment by Jaex** [comment]
All turkish keyboards using ctrl and shift on them so I dunno how it is different in other countries.

**Comment by Jaex** [comment]
Also you can't translate .NET Keys enums.

**Comment by dannoe** [comment]
There is also a .NET Class for converting keys in the correct translation:

[KeyConverter.ConvertToString Method (System.Windows.Input)](https://msdn.microsoft.com/en-us/library/system.windows.input.keyconverter.converttostring(v=vs.110).aspx)

**Comment by Jaex** [comment]
Using that won't allow me to do custom naming properly.
