### ISSUE TITLE
Upload screen video to maxfile.ro gives error

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1313]
Screen Video recording - upload is sent to maxfile.ro
and it returns this result which gives error page.
https://d.maxfile.ro/vgadoybuaj.mp4

IT MUST BE https://d**2**.maxfile.ro/vgadoybuaj.mp4 to be correct.
Can this be fixed to be **d2** instead of **d**
Thankyou
ShareX  10.0

**Comment by Jaex** [comment]
If owner of this website used latest pomf codes, response would include full link instead of only file name and we didn't have to change subdomain every single time.

**Comment by gotquestions** [comment]
You state above fixed #1313: maxfile url update
But not fixed in **ShareX 10.0** so what can I do to make a code change inside ShareX 10.0 to fix problem for me?
Thankyou

**Comment by Jaex** [comment]
You can fix it in your ShareX like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/ShareX_InUZCBzL1E.png)

**Comment by gotquestions** [comment]
Confused because I don't have Pomf.
I clicked through all the file uploaders and actually all of them from the leftside panel and did not find anything  with maxfile.ro "result Url" yet when I screen capture a video it automatically goes to maxfile.ro for upload.
Other suggestion or what am I doing wrong.
Thankyou

**Comment by Jaex** [comment]
Why are you using old ShareX version?

**Comment by gotquestions** [comment]
Because I want to keep all these menuitems. There is no option to keep them in later shareX versions.

![sharex 10 0 menu items](https://cloud.githubusercontent.com/assets/8550969/12905325/27545cc8-ce8b-11e5-9f49-dded240784ec.PNG)

I see now how I have maxfile setup here
![sharex 10 0 maxfile](https://cloud.githubusercontent.com/assets/8550969/12905284/b69f0b54-ce8a-11e5-8df5-27568d21d36d.PNG)

**Comment by gotquestions** [comment]
See here. No Pomf
![sharex 10 0 destinations maxfile](https://cloud.githubusercontent.com/assets/8550969/12905549/de317696-ce8c-11e5-81ee-07e4b3404f63.PNG)

**Comment by Jaex** [comment]
You are using very old version this is why it is not exist in your ShareX.
Can't you figure that out yourself after I ask why you are using old version?

**Comment by gotquestions** [comment]
I already told you in the very beginning that I am using ShareX10.0 
If it is uploaded to maxfile.ro then there should be a way to change the code inside it I would think. 
Did you see my post pic above?
https://cloud.githubusercontent.com/assets/8550969/12905549/de317696-ce8c-11e5-81ee-07e4b3404f63.PNG

**Comment by McoreD** [comment]
@gotquestions 10.0 is not the latest version. Download the latest (as of today) from here:
https://github.com/ShareX/ShareX/releases/download/v10.6.1/ShareX-10.6.1-setup.exe

**Comment by gotquestions** [comment]
I know it is not the latest version but I explained that I wanted Version 10.0 to keep themenuitems layout the way it was.
![sharex 10 0 menu items](https://cloud.githubusercontent.com/assets/8550969/12905768/de1786da-ce8e-11e5-9d05-1b23fcc12a0c.PNG)
