### ISSUE TITLE
vgy.me should use https when creating links

### ISSUE THREAD

**Issue by Dyras** [ShareX/ShareX#1315]
Hi. I've noticed that vgy.me has support for https, but ShareX isn't using it.
Compare this
http://vgy.me/JMggvU.jpg
To this
https://vgy.me/JMggvU.jpg

They both work just fine. I suggest you simply throw in an s for every vgy.me link, since there doesn't seem to be any harm.

**Comment by Jaex** [comment]
They don't use https for default web address. They don't also give https link in upload. Also API not gives https too. You need to use what API gives other if they decide to remove https support in future that will make all uploads broken in ShareX.

**Comment by Dyras** [comment]
@Jaex I emailed the creator of the site, and this is what he responded:

> It should return https links, if the request was sent over https.
> 
> Use https://vgy.me/upload instead of http://vgy.me/upload

**Comment by Jaex** [comment]
If https was suggested by site then it will be redirected automatically like how github and all web sites does.

**Comment by Dyras** [comment]
It's an option, not a requirement from the site. Like what The Pirate Bay did a couple of years ago. Want me to mail him and ask him why SSL isn't standard?

**Comment by Jaex** [comment]
Imgur supports https too but never returns https url in their API. It is not professional to use non default url formats because there is no guarantee it will always work.

**Comment by TechKat** [comment]
vgy.me creator here,

vgy.me runs on Laravel 5.1, and their routes helper uses either http or https, depending on how a client is connected. When Jaex implemented vgy.me into ShareX, it was before SSL was added to the site, so they have used the http protocol. Personally, I see no real problem with this as it's just image data. Unless an image contains someone's bank details, which quite frankly no one is that stupid to screenshot. And normally I would delete those kind of images myself as it's just not worth the risk, even though it's not my responsibility for the consequences of someone's bank details being shared online.

The purpose of an image host is to, as it implies, "host" an image, so you can link it to profiles or forums. I mean, there's just no point uploading an image to an image host and not sharing it anywhere, right?

**Comment by TechKat** [comment]
The real reason why vgy.me isn't on SSL always was because ShareX was using the http version. So sending a POST http request would generate a GET request to the https version.

I see now that Jaex has updated the code to use https and once that update rolls out, I will make vgy.me always use SSL.
