### ISSUE TITLE
Portable version's update check fails

### ISSUE THREAD

**Issue by seamoonz** [ShareX/ShareX#1317]
Portable version's update check fails. I have latest version and Xp Sp3.

**Comment by Jaex** [comment]
How it fails? Gives error?

**Comment by seamoonz** [comment]
I go about page and it checks automatically for update then gives "Update check failed"

**Comment by Jaex** [comment]
It tells ShareX is up to date for me:

![](http://i.imgur.com/o1Aewk1.png)

**Comment by seamoonz** [comment]
Have you tried on XP?

My ShareX:
http://i.imgur.com/kIflRiO.jpg

**Comment by Jaex** [comment]
How can I try XP nobody using XP in world anymore.

**Comment by seamoonz** [comment]
You can boot XP via usb stick.
Log says:
2016-02-14 16:44:05.656 - GitHub update check failed:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by Jaex** [comment]
I don't think this problem is to do with ShareX because normal update system and portable update system uses same codes and it works fine and nobody reported such thing before.
