### ISSUE TITLE
Unable to record 4k video

### ISSUE THREAD

**Issue by Aokromes** [ShareX/ShareX#1318]
I am using ShareX 10.6.1, when i try to record 4k video i get this error:

ffmpeg version N-72311-g17264cd Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 23.101 / 54. 23.101
  libavcodec     56. 40.100 / 56. 40.100
  libavformat    56. 33.101 / 56. 33.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[gdigrab @ 00000000050083c0] Capture area (104,45),(3736,2087) extends outside window area (0,0),(5888,1440)desktop: Input/output error

(i have a secondary 2k monitor, but i don't think that must be one issue)

**Comment by Jaex** [comment]
Use FFmpeg download button in ShareX to download latest FFmpeg version because this issue was fixed in latest versions.

**Comment by Aokromes** [comment]
Confirmed working, thx!
