### ISSUE TITLE
[Question] Selection Tool in Greenshot Editor

### ISSUE THREAD

**Issue by amiremami** [ShareX/ShareX#1319]
Hi guys
I'm new to sharex. Everything is great. I have only one question about greenshot editor. In Ms Paint there is a selection tool which let us delete part of image or duplicate it. I did not find any similar tool in greenshot editor. Do you know any solution?

![16yhutj](https://cloud.githubusercontent.com/assets/15929497/12999856/fc67452c-d153-11e5-8214-b8fd9effe673.png)

Thanks

**Comment by Jaex** [comment]
You can automatically launch paint after capture using Actions.

**Comment by amiremami** [comment]
Thanks a lot Jaex, so this feature is not in greenshot editor, am I right?

**Comment by Jaex** [comment]
You can only crop area not cut or duplicate.

**Comment by amiremami** [comment]
Yeah I found also this:
https://greenshot.atlassian.net/browse/FEATURE-428

It's really pitty it does not have it :(

But thanks a lot for your help Jaex :)

**Comment by amiremami** [comment]
Sorry @Jaex  to write here again, I want to open only paint.net for editing, but I didn't find any option for disabling greenshot image editor. It still opens at first. If I uncheck "open in editor" option, everything is okay but the problem is it uploads to host before opening paint.net.

Can I set order to tasks? Or is there any trick?

I appreciate your help :)
