### ISSUE TITLE
Suggestion - Drag & Drop support for the main list view

### ISSUE THREAD

**Issue by beppe9000** [ShareX/ShareX#1320]
Often I find myself wanting to quickly use a captured image without automatically distrupting my clipboard content.

It would be cool to add Drag & Drop support to list control in the main form: left drag and drop for file, rightclick-drag&drop for the actual bit map and something like middle-click drag&drop for the link text.

Hopefully this could save some clicks to drag&droppers like me.

*I may implement this if i have time, but don't count on it.*

**Comment by Jaex** [comment]
#1023
