### ISSUE TITLE
TinyPic credentials expire after 24-48 hours

### ISSUE THREAD

**Issue by tcfjr** [ShareX/ShareX#1322]
I use TinyPic as my Image Upload destination, using a specific account (not anonymous).  After I enter my credentials, uploads work fine for about 24-48 hours, after which they begin to fail with an 'unknown user' error.

I have to go back into the Destination settings and re-enter my TinyPic username and password before uploads will work again.

**Comment by Jaex** [comment]
Tinypic codes not changed for long years so how this can be fault of ShareX?

**Comment by tcfjr** [comment]
In ShareX, if you provide your login info for IMGUR once, ShareX will post to your IMGUR account without having to re-enter your IMGUR username and password.

With TinyPic, once you enter your login info, ShareX will upload to TinyPic for 24-48 hours, but will then require you to re-enter your TinyPic username and password.  The TinyPic credentials entered into ShareX expire after 24-48 hours (or so).

**Comment by Jaex** [comment]
Then you need to report this to TinyPic devs?
