### ISSUE TITLE
Uploading image right-click copied from Chrome will shift it 3 pixels to the right

### ISSUE THREAD

**Issue by TheAMM** [ShareX/ShareX#1324]
Any image that's copied as image data (right-clicking an image and selecting Copy image) in Chrome will get its pixels shifted to the right, wrapping around, when uploaded.

The shift seems to be always precisely 3 pixels.

This seems to only happen with images copied from Chrome - Firefox, Paint and GIMP clipboard-images work fine. Pasting the Chrome-clipboard image into Paint and GIMP works fine.

Cropped image uploaded from file:
![2016-02-15_02-02-26](https://cloud.githubusercontent.com/assets/6820963/13037388/544a3c32-d388-11e5-9e77-06ba162a4403.png)
The same image opened in Chrome, right-click copied and uploaded (and saved to upload to GitHub):
![2016-02-15_02-04-33](https://cloud.githubusercontent.com/assets/6820963/13037397/804d517a-d388-11e5-9ef5-b1652c32b618.png)

I'm using:
ShareX 10.6.1
Chrome 49.0.2623.47 beta-m (64-bit)
Windows 7 Ultimate

**Comment by Jaex** [comment]
I was fixed it 3 weeks ago, new version will release soon.

**Comment by TheAMM** [comment]
Good to hear.

**Comment by Jaex** [comment]
Argg when I'm pressing close button it become reopen in same time.

**Comment by TheAMM** [comment]
; )

**Comment by piterq** [comment]
Hi.
Sorry for writing in this very old issue, but I have exactly the same problem. I'm using ShareX version 16.1 on Windows 11 x64 23H2.
This sample image:
![image](https://github.com/user-attachments/assets/74886809-ef7b-4881-804c-b98472bd2daf)

pasted into Chrome/Edge becomes shifted:
![image](https://github.com/user-attachments/assets/5c72247c-59d6-42b9-b60d-521c24455ada)

but pasted into Firefox ESR looks normal:
![image](https://github.com/user-attachments/assets/99c596f5-b3e3-4796-a67c-33c187a44560)
