### ISSUE TITLE
Transliterate file naming [Enhancement]

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#1327]
Please make setting for transliterate file name because non ANSI chars in links is unreadable and URL too long. It is often shown when using window title (%t) or process name (%pn) in file naming.

Example:
> D:\Documents\ShareX\Screenshots\2016-02\Dr.Web_-_Антивирусная_правДА_-_Vimperator_firefox_2016-02-11_13-57-07_UMCHCpn0.png

URL:
> http://storage.internal/screenshots/yar/Dr.Web_-_%D0%90%D0%BD%D1%82%D0%B8%D0%B2%D0%B8%D1%80%D1%83%D1%81%D0%BD%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%B2%D0%94%D0%90_-_Vimperator_firefox_2016-02-11_13-57-07_UMCHCpn0.png

**Comment by Jaex** [comment]
What is transliterate means?

**Comment by BytewaveMLP** [comment]
@Jaex "Translate," but not into another language.
@QuAzI seems to speak Russian or some language with a non-Latin alphabet. Web servers, like the example provided, don't support URLs with non-ANSII codepage characters.
He's asking for an option to encode special characters that aren't part of an ASCII/ANSII codepage into URL-safe characters (see [this (for PHP)](https://ideone.com/Xt8Ud5)).

In the case of C#, like ShareX, you would want to use `Uri.EscapeUriString(str)` to encode URL/URIs the user wants encoded (see [this](https://ideone.com/xofkja)).

**Comment by Jaex** [comment]
Isn't ShareX already do that? Example I uploaded it to Dropbox:

https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/Dr.Web_-%D0%90%D0%BD%D1%82%D0%B8%D0%B2%D0%B8%D1%80%D1%83%D1%81%D0%BD%D0%B0%D1%8F%D0%BF%D1%80%D0%B0%D0%B2%D0%94%D0%90_-_Vimperator_firefox_2016-02-11_13-57-07_UMCHCpn0.png.png

and it works.

**Comment by QuAzI** [comment]
Transliterate means all chars from users locale translated to nearest char from ANSI that prevents problems with reading and fonts
https://en.wikipedia.org/wiki/List_of_ISO_transliterations
As example we use 
ISO 9-95 https://en.wikipedia.org/wiki/ISO_9
GOST 16876-71 https://en.wikipedia.org/wiki/GOST_16876-71
In code it defined as dictionary for replacing non ANSI chars

```
    gost.Add("А", "A");
    gost.Add("Б", "B");
    gost.Add("В", "V");
    gost.Add("Г", "G");
    gost.Add("Д", "D");
    gost.Add("Е", "E");
    gost.Add("Ё", "JO");
    gost.Add("Ж", "ZH");
    gost.Add("З", "Z");
    gost.Add("И", "I");
    gost.Add("Й", "JJ");
    gost.Add("К", "K");
    gost.Add("Л", "L");
    gost.Add("М", "M");
    gost.Add("Н", "N");
    gost.Add("О", "O");
    gost.Add("П", "P");
    gost.Add("Р", "R");
    gost.Add("С", "S");
    gost.Add("Т", "T");
    gost.Add("У", "U");
    gost.Add("Ф", "F");
```

When text looks like "%D0%90%D0%BD%D1%82" it is long, unreadable and scary.

**Comment by Jaex** [comment]
I'm not planning to find similar looking characters for each language.

**Comment by QuAzI** [comment]
It is used in many cases. SLUG as example. Human readable links need.
Some simple solutions exists
https://stackoverflow.com/questions/2173825/slugify-and-character-transliteration-in-c-sharp

**Comment by Jaex** [comment]
Also many people won't like their file name to be changed on host because those characters valid file name.

**Comment by QuAzI** [comment]
It is only option in settings which can be disabled by default.
Spaghetti of symbols instead of the readable text makes %t non comfortable for all non latin users. Also some FS (etc remote in case of FTP) have restrictions for file name length (one non ANSI symbol costs as two)
