### ISSUE TITLE
FFmpeg error of Unknown encoder 'libvo_aacenc'

### ISSUE THREAD

**Issue by ErikBleifield** [ShareX/ShareX#1328]
I am able to capture video fine - but any audio choice I select is giving me this error:

ffmpeg version N-78410-g588e2e3 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.100 / 55. 17.100
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[gdigrab @ 00000000001551e0] Capturing whole desktop as 844x406x32 at (178,299)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1455556217.759850, bitrate: 219313 kb/s
    Stream #0:0: Video: bmp, bgra, 844x406, 219313 kb/s, 20 tbr, 1000k tbn, 20 tbc
Guessed Channel Layout for  Input Stream #1.0 : stereo
Input #1, dshow, from 'audio=Microphone Array (IDT High Defi':
  Duration: N/A, start: 254271.019000, bitrate: 1411 kb/s
    Stream #1:0: Audio: pcm_s16le, 44100 Hz, 2 channels, s16, 1411 kb/s
Unknown encoder 'libvo_aacenc'

Any ideas on how to fix this?

Thanks,

---Erik

**Comment by Jaex** [comment]
libvo_aacenc encoder removed in latest ffmpeg therefore i was used aac but this version not released yet. You can enable custom commands and edit yourself it to aac ofc.

**Comment by ErikBleifield** [comment]
I am sorry I am not quite following: 
Can you show me what exactly I need edit here to make it work?
-y -rtbufsize 100M -f gdigrab -framerate $fps$ -offset_x $area_x$ -offset_y $area_y$ -video_size $area_width$x$area_height$ -draw_mouse $cursor$ -i desktop -f dshow -i audio="Microphone Array (IDT High Defi" -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 30 -pix_fmt yuv420p -c:a libvo_aacenc -ac 2 -b:a 128k "$output$"

Thanks! 

    On Monday, February 15, 2016 4:30 PM, Jaex <notifications@github.com> wrote:
 

 libvo_aacenc encoder removed in latest ffmpeg therefore i was used aac but this version not released yet. You can enable custom commands and edit yourself it to aac ofc.—

**Comment by rts58** [comment]
I had the same problem today.  I was able to get it to work by changing "libvo_aacenc" to just "aac".
