### ISSUE TITLE
Hotkey PrintScreen doesn't work in Applications with admin privileges

### ISSUE THREAD

**Issue by ngzero** [ShareX/ShareX#1330]
You can take any application. For me, I've tested with visual studio and pdf-xchange-editor.
If the application is started normally **without **admin rights, then with pressing PrintScr-Key ShareX comes up to capture.
If the application is started with administrative privileges, then pressing PrintScr-Key does nothing.

What doesn't work
PrintScreen (Task Capture region)
Alt+PrintScreen (Task Capture region)
Ctrl+PrintScreen (Task Capture region)
PrintScreen  (Task Capture region with delay)

What works
Alt+PrintScreen (Task Capture region with delay)
Ctrl+PrintScreen (Task Capture region with delay)

I am using the latest Windows 10 x64.

**Comment by Jaex** [comment]
Then it is limitation of Windows hotkey system, so there is nothing i can do about it.
Only solution would be using global keyboard hook and i'm not planning to use that system like majority of screen capture software or file syncing software.
