### ISSUE TITLE
[feature request] Clipboard history

### ISSUE THREAD

**Issue by ashtreylil** [ShareX/ShareX#1331]
i'd like to see sharex add a clipboard history feature to the program, a few things i'd like to see in this feature are as follows.

• history that stays when you logoff/shutdown/restart

• option to retain or erase text formatting

• customizable hotkey to show the clipboard history like the other features

**Comment by Jaex** [comment]
It will be out of scope for ShareX. Sure there is many such things in Tools section but clipboard manager can't be just one window tool, it should have tons of other features so I can't add it to ShareX. You should search standalone clipboard history softwares.

**Comment by HomelessAvatar** [comment]
There's already another free program that does what you require:

http://ditto-cp.sourceforge.net/
