### ISSUE TITLE
Feature Request: Add Lab values in Screen Color Picker

### ISSUE THREAD

**Issue by cassianokc** [ShareX/ShareX#1332]
Hi, 

First of all, thank you for such a great tool.
I would like to have as a feature also the Lab Color Space values when using the color picker.

Best regards,

**Comment by Jaex** [comment]
Lab color space used very rarely and to be honest I don't even know where it is used therefore I'm not planning to include it. Also there is no empty space in color picker window to put it unless I increase width of window to add it to right side which I don't want.
