### ISSUE TITLE
Last Region screen capture loses Window name

### ISSUE THREAD

**Issue by videoassist** [ShareX/ShareX#1333]
Hello!

I've configured a hotkey to capture last region but it loses the window name.

I use "%i{7}_%t" to naming files.

The files are named this way:

0000001_all_-_Google_Chrome.jpg
0000002_%t.jpg
0000003_%t.jpg
.
.
.

Thanks in advance.

**Comment by Jaex** [comment]
It can't keep window name with last region.

**Comment by videoassist** [comment]
Is this because ShareX cannot detect the window name when "last region"?
