### ISSUE TITLE
(Imgur) mass deletion of images

### ISSUE THREAD

**Issue by reddit-is-fun** [ShareX/ShareX#1335]
I accidentally uploaded over 500 images of my desktop to Imgur, some private content is visible. Don't ask me how I managed to do this - I was using a script that hammers a button and forgot that that key was also my hotkey in ShareX. Apparently uploading isn't limited in any way.
I haven't found a way to delete several uploaded images at once, going through the deletion links manually would be an arduous task. I hope you will add support to "delete all selected images" for at least the default image host Imgur, ShareX could go through the deletion links automatically.

**Comment by Jaex** [comment]
I'm not planning to add mass deletion feature because it would be an arduous task for me just for rarely 2 or 3 people gonna need it.

**Comment by reddit-is-fun** [comment]
Yes I could use a script, I may have overreacted a bit. Sorry for pressuring.
