### ISSUE TITLE
Screen Recording

### ISSUE THREAD

**Issue by cmtvr** [ShareX/ShareX#1337]
When saving a screen recording as a gif file, how do you add a pause betwen the end of the capture and the restart of the loop?  Can you add a black screen at the end before the restart?  Can you make the animation just play once?  With the looping of the recording it is hard to see when the recording begins and ends.

**Comment by Jaex** [comment]
You can use animated gif editor software for such things. I'm not planning to add editing capabilities.

**Comment by cmtvr** [comment]
I added "-loop 1" as an additional command line argument to ffmpeg.  I get this error.

Unable to find a suitable output format for 'pipe:' 
pipe:: Invalid argument
