### ISSUE TITLE
Malware detected after update - Kaspersky

### ISSUE THREAD

**Issue by h7896v7347** [ShareX/ShareX#1340]
`21.02.2016 14.49.52;Detected object (file) was deleted.;C:\Program Files\ShareX\ShareX_Chrome.exe;C:\Program Files\ShareX\ShareX_Chrome.exe;HEUR:Trojan.Win32.Generic;Trojan program;02/21/2016 14:49:52
`

**Comment by Jaex** [comment]
False positive.

**Comment by Jaex** [comment]
Got email response from Kaspersky:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/chrome_GVrxGomMac.png)
