### ISSUE TITLE
Image editor HiDPI support

### ISSUE THREAD

**Issue by karlobencic** [ShareX/ShareX#1341]
Please change the image editor to something with HiDPI support, because it's not usable on high resolutions.
![sharex_2016-02-21_14-52-07](https://cloud.githubusercontent.com/assets/10995543/13202938/b6bc8b50-d8aa-11e5-8e69-200353fa0f8e.png)

**Comment by Jaex** [comment]
This was fixed in latest Greenshot but merging changes too difficult I give up merging anymore. Because it require checking every single commits one by one for changes.

**Comment by campbeb** [comment]
Here is how to fix the editor icons once the next version of ShareX is released:
- Find your ShareX settings folder. Mine on Windows 10 is `C:\Users\campbeb\Documents\ShareX`
- Open `GreenshotImageEditor.ini`
- Find the line `IconSize=16, 16`
- Change it to something like `IconSize=128, 128`. You can change the numbers to other choices such as 64, 96, 128, 256

The icons will be stretched to the new larger size, so they may not look very good, but this is the solution Greenshot is using.
