### ISSUE TITLE
Malware detected after update - Kaspersky

### ISSUE THREAD

**Issue by h7896v7347** [ShareX/ShareX#1342]
`21.02.2016 14.49.52;Detected object (file) was deleted.;C:\Program Files\ShareX\ShareX_Chrome.exe;C:\Program Files\ShareX\ShareX_Chrome.exe;HEUR:Trojan.Win32.Generic;Trojan program;02/21/2016 14:49:52
`

#close 1342

**Comment by Jaex** [comment]
#1340
