### ISSUE TITLE
Add option to not place desktop shortcut on update

### ISSUE THREAD

**Issue by Cyberuben** [ShareX/ShareX#1344]
I have noticed that every time ShareX updates, a new desktop shortcut is created. I can not remember I have ever clicked a checkbox to actually place a shortcut, so I do not understand why it keeps coming back every update. 

It's not a huge bug but still rather annoying.

**Comment by Jaex** [comment]
InnoSetup using same options you checked while installing, when doing install with -silent. So it is not possible for me to make option for it. It would be better for InnoSetup to not execute any options you checked when first installing while doing -silent but can't find such setting.
