### ISSUE TITLE
ShareX_Chrome.exe detected as trojan

### ISSUE THREAD

**Issue by derN3rd** [ShareX/ShareX#1345]
Hey there,
just wanted to let you know that the ShareX_Chrome.exe is false flagged as a trojan.
Maybe you should change some behavior in order to keep the file (my Kaspersky tries to remove the file without any notice).
For more information see https://www.virustotal.com/de/file/28fac0eb24b0ab3a03b2f89767501a76c63a2433fa6609f282fc476860c9129e/analysis/

**Comment by Jaex** [comment]
#1340
