### ISSUE TITLE
Command Line Image Optimizers

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#1348]
I would be super happy if any of these image optimizer command line programs could be integrated with Share-X to be an option on the **After capture Tasks** menu.

Share-X is truly amazing and the ultimate image program and this is the last thing it is missing in my opinion and for my usage as well as many others.

When checked it would run the new image through the program to optimize/compress it before uploading or doing the other tasks.

## After capture tasks:  
  

- optimize PNG image with **PNGOut** - http://advsys.net/ken/utils.htm   
- optimize PNG image with **PNGCrush** - http://pmt.sourceforge.net/pngcrush/  
- optimize PNG image with **PNGQuant2** - http://pngquant.org/   
- optimize PNG image with **OptiPNG** - http://optipng.sourceforge.net/  
- optimize PNG image with **AdvPNG** - http://advancemame.sourceforge.net/doc-advpng.html  
- Optimize JPG Image with **JPEGTran** - http://jpegclub.org/jpegtran/   
- optimize JPG image with **JPEGOptim** - https://github.com/glennr/jpegoptim  
- optimize JPG image with **JPEGCrush** - http://akuvian.org/src/jpgcrush.tar.gz  
- optimize GIF image with **GIFSicle** - http://www.lcdf.org/gifsicle/    
  

Most of these are Linux command line programs but several have Binary Windows versions available online.  I can help find them if needed as some apps that use these will work on both Linux and Windows.

The WordPress plugin below uses the Linux and windows binary versions to allow support on both OS.

## Other apps using these:  

**EWWW Image Optimizer** - WordPress plugin that uses all these programs to optimize images. https://wordpress.org/plugins/ewww-image-optimizer/

**ImageOptim** - Mac program that wraps around all these image optimizers - https://imageoptim.com/

**Trimage** - same as above but a Linux version built in Python - https://trimage.org/

---

Please do share your thoughts on this, would you possibly add in this capability for any of these please?

Thanks so much for all your efforts and amazing work on Share-X, it is truly my favorite most useful used tool!

**Comment by Jaex** [comment]
It is already exist called "Actions" in ShareX.

**Comment by jasondavis** [comment]
Hi Jaex, that is great!  Could you possibly add some demo instructions for using with one of these applications sometimes?

**Comment by jasondavis** [comment]
I see what you mean now here...   

![chrome_2016-02-21_11-44-30](https://cloud.githubusercontent.com/assets/186818/13203926/bf2588ba-d890-11e5-8b63-903868946029.png)

**Comment by peckwood** [comment]
This is how I do it with pngcrush:

![ShareX_F62adgQw3W _compressed _compressed _compressed](https://user-images.githubusercontent.com/1825108/106841176-95fa9e00-66dc-11eb-902a-6cfd8302a90f.png)
