### ISSUE TITLE
Cannot open Task Settings window

### ISSUE THREAD

**Issue by maciozo** [ShareX/ShareX#1350]
Whenever I try to open the Task Settings windows from either the right click menu of the system tray icon or through the main window, I get this error. Clicking Continue closes the error window. Running on Windows 8.1.

```
System.ArgumentOutOfRangeException: Value of '5000' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at ShareX.TaskSettingsForm..ctor(TaskSettings hotkeySetting, Boolean isDefault)
   at ShareX.MainForm.tsbTaskSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.7 Release
```

**Comment by Jaex** [comment]
Open ShareX json config files search 5000 and find what was wrong and use proper value. Not sure how you managed to get wrong value too. Because this control not allows setting value 5000 because of max value limit.

**Comment by maciozo** [comment]
Problem seems to be resolved. I had ImageSizeLimit set to 5000, which was allowed before the update. Any idea why a limit of 2048 is now in place?

Either way, there should probably some sort of check to make sure that the user at least has a chance to reduce the value without having to dig through the config files.

**Comment by Jaex** [comment]
There is tons of controls in so many windows I can't add check for every single thing which was normally not possible to set in ShareX. But ofc still I do size range checks in many places but not everywhere.

I'm not sure how max limit become 2048 but it is not intended. Fixing it now.

**Comment by Budfraiz** [comment]
where can i find the ShareX json config files?

**Comment by Jaex** [comment]
Documents/ShareX

**Comment by Budfraiz** [comment]
The only thing with a value of 5000 is AutoReconnectDelay. Am I in the wrong place? ApplicationConfig.json

**Comment by Jaex** [comment]
There is no AutoReconnectDelay in my json file how you found it.

**Comment by Budfraiz** [comment]
http://i.imgur.com/eSlm7qu.png These are my files. A search in the whole folder for 5000 doesn't result in anything

**Comment by Jaex** [comment]
That files have 2015 in date modified so you must be not saving setting there?

**Comment by Budfraiz** [comment]
Oh you're right, two different drives. Found the updated one, but a search of 5000 doesn't show anything. any ideas?

**Comment by Jaex** [comment]
Search ImageSizeLimit check its value.

**Comment by Budfraiz** [comment]
in applicationconfig it's 2048, in the others its 1024

**Comment by Jaex** [comment]
In your error:

`System.ArgumentOutOfRangeException: Value of '5000' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.`

It tells setting have value of 5000. How your json files won't have it.

**Comment by Budfraiz** [comment]
Can i upload all the files somewhere?

**Comment by Budfraiz** [comment]
Hmmm, every time i change the 5000 to 2048 for ImageSizeLimit, whenever i restart the application it resets the number. Should it try deleting the json files?

**Comment by Jaex** [comment]
Are you changing json when ShareX is not open?

**Comment by Budfraiz** [comment]
You're a genius! Thanks heaps for the help. Where's the donate button? Gosh i'm silly sometimes

**Comment by Jaex** [comment]
In ShareX main window.

**Comment by EhsanKia** [comment]
A smoother handling of this should really be implemented. I again got it on the "MagnifierPixelCount" setting being set to 41. There needs to be some error catching mechanism that automatically snaps the setting to range if they're out of range.

**Comment by Jaex** [comment]
There is like 200+ numeric up down assigns in project, sometimes I forget to add checks for unexpected values :(

**Comment by roastchicken** [comment]
Why did the allowed values for "MagnifierPixelCount" change with the update?

**Comment by Jaex** [comment]
Was using PropertyGrid for those settings before, now using proper controls for it.

**Comment by nananananananana** [comment]
Until today I was recommending everyone to use ShareX instead one of the other crappy solutions.
TIL it's almost as crappy as it's competition.

> There is like 200+ numeric up down control assigns in project, sometimes I forget to add checks for unexpected values :(

[aww :(](http://images.parents.mdpcdn.com/sites/parents.com/files/styles/width_360/public/images/p_101528432.jpg)

**Comment by lithium720** [comment]
@nananananananana The best part about ShareX is it's open source. So if you think something is crappy about it, you can fix it yourself! Woot! I eagerly await your pull request / clone revisions to see all of the awesome changes you make to make ShareX far better for everyone.

On a less sarcastic note, @Jaex is doing an awesome job for doing this almost entirely by himself lately. So really, rather just bashing his work & being toxic, why don't you _try_ contribute to make ShareX even better?

**Comment by Jaex** [comment]
By the way for ` Value of '37' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.` issue just decreasing magnifier size is enough no need to edit json file.
