### ISSUE TITLE
Capture is blocked by measurements info

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1351]
Windows Vista
ShareX 10.7

Capture - Region
The static image I am trying to capture is covered over with the measurements.
I need to be able to see the complete capture to be sure I am capturing exactly what I intend to capture.
How to prevent this?
Thankyou

![sharex capture covered by info](https://cloud.githubusercontent.com/assets/8550969/13206051/38283770-d8ab-11e5-9396-4a2c8fcffa47.PNG)

**Comment by Jaex** [comment]
That info box normally shows outside but because top side have no space for it, it moved to bottom.

Press `I` button to hide it temporary then you can enable it later.

**Comment by gotquestions** [comment]
It moved to bottom but can it not be set to move to bottom of capture?
There is enough space for bottom of capture. Positioned right underneath the capture.

**Comment by Jaex** [comment]
What if bottom have no space too? I can't do countless checks for every cases.

**Comment by gotquestions** [comment]
Okay thankyou.

**Comment by gotquestions** [comment]
But couldn't it be just check top bottom left right and not any more than that countless ?
Then not have to remember to enable Press I button
