### ISSUE TITLE
How to remove from history item

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1353]
ShareX 10.7
I can remove the image from host (imgur) with Open/Deletion Url
But how to remove it from the shareX History 
window? History window is too filled with unwanted image list.
Thankyou

![sharex history removal](https://cloud.githubusercontent.com/assets/8550969/13206237/bd51d372-d8ae-11e5-8fa2-767a29accd7f.PNG)

**Comment by Jaex** [comment]
#314

**Comment by gotquestions** [comment]
I tried this.
I went to sharex/Uploaders History/rightclick on it to Edit with Notepad++ OR Open with notepad.
But there were only 4 images listed there from years ago.
Can you tell me the correct path "**History.xml in Notepad**" to all those images listed in the sharex history window so that I can delete them. 
Thankyou

**Comment by Jaex** [comment]
`Documents\ShareX\History.xml` unless you changed personal folder.

**Comment by gotquestions** [comment]
Yes I found that thankyou. Easy to remove all or just one from that folder, but if you need to remove a particular 20 it is difficult without being able to click and see the image to decide to remove.
But you explained why. If in the future an easier way to delete is possible then that would be great. Thankyou.
