### ISSUE TITLE
ShareX update automatically creates unwanted Desktop and other shortcuts

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#1354]
When I installed ShareX for first time, on installation prompt I unticked 'create desktop shortcut' and some other shortcut (that I don't remember).

After ShareX automatic update, it created unwanted desktop shortcut and probably other shortcut as well.

I suggest saving shortcut options on installation prompt so it will have same behavior on update.

Thanks.

**Comment by Jaex** [comment]
#1346
#1344

**Comment by dmxt** [comment]
Sorry ;~;
