### ISSUE TITLE
Switch host after capture

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1356]
ShareX 10.7
I use this menu list on the "Show Quick Task Menu".
I have Image Uploader set to imgur.
But usually I capture and want imgur because it expires in 6 months and the image is not that important to keep a long time.
But other times I want to use a different host that never expires the image or for another reason.
Is there a way that after capture I can make a decision to change from imgur to another host.

Or is the only way to remember before capture to make the change by:
RIghtclick on ShareX icon/ Destinations/Image Uploader/Cherverto
then go back and reset back to imgur.
Thankyou

![sharex quick tasks menu list](https://cloud.githubusercontent.com/assets/8550969/13207684/0f5418f8-d8c6-11e5-8e12-949bc308d030.PNG)

**Comment by Jaex** [comment]
After capture tasks -> Show "After capture" window
After capture tasks -> Show "Before upload" window

Allows to change destination before upload.

**Comment by gotquestions** [comment]
Thankyou but this did not work. It behaved as if only "Show Quick Task Menu" function.
![sharex menu](https://cloud.githubusercontent.com/assets/8550969/13207859/4a3e038c-d8c8-11e5-9fcd-01eec8c839d8.PNG)

This did nothing at all after capture. I captured, no window appeared, and no host url.
![sharex menu 2](https://cloud.githubusercontent.com/assets/8550969/13207951/1445efd2-d8c9-11e5-9f93-eded3b4c6721.PNG)

This opened window but the opening tab is all unchecked so I had to then read through it and select, then transfer to Destinations tab and choose. Many steps clicking.
![sharex menu 4](https://cloud.githubusercontent.com/assets/8550969/13208240/91b87d34-d8cb-11e5-8f81-3db3e844538b.PNG)

Would be nice if that choice was available with the "Show Quick Task Menu" but I guess too much code work.
Thankyou

**Comment by Jaex** [comment]
In your first image ofc it will act as only quick task menu because in your selection you override rest of tasks.

And in your second image there is no upload task so ofc it won't show upload destination window.

And after capture shows checked for me. But there is scroll bar issue.

**Comment by gotquestions** [comment]
So there is the over ride fact. Okay thankyou.
Yes I noticed the scrollbar issue but is so minor.

So this is EXACTLY what I'm looking for. Less clicks as I only have to set the Destination.
This is great it works best for me.
Thankyou
![sharex menu 5 line](https://cloud.githubusercontent.com/assets/8550969/13208837/d8643862-d8d1-11e5-801d-59ac9ad0bb5a.png)

**Comment by Jaex** [comment]
By the way I added icons to this menu now:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/sco7aknjnz.png)

Automatically uses proper icons.

**Comment by gotquestions** [comment]
Good but
the icons don't all seem to be a correct match.
http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png

Copy symbol is usually a double page, So a double image
http://www.iconarchive.com/search?q=copy

Edit symbol is usually a pencil ![sharex icon edit](https://cloud.githubusercontent.com/assets/8550969/13263002/89852764-da1c-11e5-99bf-6914e4a78632.PNG)
http://www.iconarchive.com/search?q=EDIT

Annotate maybe a paintbrush
http://www.iconarchive.com/search?q=paintbrush
http://www.iconarchive.com/search?q=paint

Upload is usually an Up Arrow (Upload, Copy URL)
http://www.iconarchive.com/search?q=upload

I also changed like this for more separation and more quick readable
Save, Upload, Copy URL
Save - Upload - Copy URL
