### ISSUE TITLE
Tiny Pic not give correct image png result

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1357]
ShareX 10.7
TinyPic url resulted as this instead of image png url.

Tested twice.
http://tinypic.com/view.php?pic=34q1jkx&s=9
http://tinypic.com/view.php?pic=155t1j7&s=9

**Comment by Jaex** [comment]
TinyPic gives this link: http://i67.tinypic.com/4zuni9.png
and it redirects to: http://tinypic.com/view.php?pic=4zuni9&s=9

So what ShareX can do about it?

**Comment by gotquestions** [comment]
Of course ShareX can do nothing about it, I did not realize it redirects like that, and why it does is strange.
It never redirected like that before.
 Maybe remove Tiny Pic from list in ShareX because it is not useable to anyone in this form. Will make the ShareX menu less height with a smaller list. Unless maybe you need have a Tiny Pic account or something. 
Thankyou.
