### ISSUE TITLE
Last version make bitdefender block as trojan.

### ISSUE THREAD

**Issue by ethaizone** [ShareX/ShareX#1358]
![seccenter_2016-02-22_15-09-22](https://cloud.githubusercontent.com/assets/1168777/13212773/5bd85f12-d976-11e5-871d-e7900688761c.png)

This image I capture from bitdefender tell ShareX is trojan.

**Comment by derN3rd** [comment]
Like Jaex said before ( https://github.com/ShareX/ShareX/issues/1340#issuecomment-186826753 ), it is a false positive.
Also you should check closed issues first before posting a new one.

Have a nice day
