### ISSUE TITLE
SFTP capped upload speed

### ISSUE THREAD

**Issue by zanshi** [ShareX/ShareX#136]
When uploading files using SFTP the transfer speed is capped at around 130KB/s. Using regular FTP I get around 2MB/s. Different buffer sizes produces the same result.

I have replicated the results on several machines running Windows 7 and Windows 8.1.

Would this be possible to fix somehow?

**Comment by Collisionc** [comment]
Running into this issue again, just at the 1 MB/s cap. I can upload to my SFTP with WinSCP at 3.5 MB/s normally.

I'll try and rebuild sharex with a newer version of ssh.net (if it exists) sometime this weekend and see if it allows a faster speed.

**Comment by Collisionc** [comment]
I can make an account on my server with a private/public SSH key so you can test uploading, if needed. Just let me know.

**Comment by Jaex** [comment]
What to test about. I didn't made SFTP library.

**Comment by Collisionc** [comment]
It looks like ssh.net library hasn't been updated since Nov. 2014, so if the issue is with ssh.net, it probably won't be fixed. :\  I'll deal with 1 MB/s, it's only a minor issue. :)

**Comment by Collisionc** [comment]
If you're interested at some point, winSCP has a .net library that can handle SFTP connections at full speed. Unfortunately, it does require bundling winSCP.exe with Sharex, which will bloat the download size by quite a bit. 

I forked a working version of winscp integration here - https://github.com/Collisionc/ShareX/commit/3357f25597d5b4cc6944e39d02110e89e8c1d8d0

It's ugly and broken outside uploading files, but it works.

**Comment by Jaex** [comment]
That exe bigger than ShareX itself so I won't like to use it.

**Comment by fantahund** [comment]
Will this bug be fixed at some point? this is unfortunately sher annoying I can upload with 40/mbits ShareX uses 2% of it. :(

**Comment by marketplex** [comment]
Same issue here, I get 19Mbps upload speed with ShareX when I have steady 60Mbps with FileZilla, makes the app useless with large files.

**Comment by PanCrucian** [comment]
Ok that lib issue, but maybe update new one? custom one? wel need more speed, ty
