### ISSUE TITLE
FFMPEG video capture - ACC flags

### ISSUE THREAD

**Issue by stdedos** [ShareX/ShareX#1360]
According to the Native [https://trac.ffmpeg.org/wiki/Encode/AAC](url), FFmpeg AAC encoder section

> Note: -strict experimental (or -strict -2) was previously required for this encoder, but it is ​no longer experimental and these options are unnecessary since 5 December 2015.

**Comment by Jaex** [comment]
99% of people using previous ffmpeg.exe
