### ISSUE TITLE
Open at Destinations Tab in After Capture Window

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1362]
Sharex 10.7
Could you please add an entry to choose:
Show "After capture" window at Destination Tab ? 

Then I can set to:
Show "After capture" window at Destination Tab - Upload image to host - Copy URL to clipboard - Open URL

Instead of:
Show "After capture" window - Upload image to host - Copy URL to clipboard - Open URL.
![sharex quick task edit menuitems](https://cloud.githubusercontent.com/assets/8550969/13271397/a732b9e8-da49-11e5-8dd6-05d0b95925ee.PNG)

This way, if I want to just change image upload from imgur to another, the window will open up in Destinations Tab instead of After Capture Tab and save me scanning through reading and an extra click.
![sharex after capture window](https://cloud.githubusercontent.com/assets/8550969/13271157/fddf9970-da47-11e5-8544-c0bdc435ea2a.PNG)

**Comment by Jaex** [comment]
Why you don't use "Show before upload window" then?

**Comment by gotquestions** [comment]
YESSSSSS ! Perfect !
Thankyou thankyou thankyou !!!!!!!!
