### ISSUE TITLE
Add Image Effects configure errors

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1366]
Most of the time I like to add a border and sometimes a shadow around the whole screenshot.
I checkmarked in After Capture/Add Image Effects watermark.
Tried to configure Image Effects with
Task Settings/Image/Effects/Image Effects Congiguration.
I get these errors and I am not sure if my steps to get the border/shadow are the right way.
Am I doing it wrong?
Thankyou

![sharex image effects border error](https://cloud.githubusercontent.com/assets/8550969/13344556/e834406a-dc0b-11e5-9856-ef4d69333e02.PNG)

![sharex configure image effects shadow](https://cloud.githubusercontent.com/assets/8550969/13344560/f0038184-dc0b-11e5-8824-bed5d09f7f43.PNG)

**Comment by Jaex** [comment]
When i open this window I can't reproduce your error:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/ShareX_RnGoqVllzy.png)

**Comment by gotquestions** [comment]
Windows Vista
Is this happening for anyone else?
If you or anyone else has any ideas of what I can do next to solve this error problem please report here.
Thankyou

**Comment by Jaex** [comment]
Why would you use Windows Vista?

**Comment by gotquestions** [comment]
Because that is what was loaded into my computer when I bought it and I do not have a new computer.
Do not need a new computer.
Are you saying that windows vista may be the reason for the error?
