### ISSUE TITLE
%t and %pn not working

### ISSUE THREAD

**Issue by Funergy** [ShareX/ShareX#1368]
I have setup my own upload website. I'm saving the extra info of the image like the active screen name on a txt file. The only argument I use right now is the active screen name. https://nielsdewulf.me/screenshot/1hvbES6ELZINnCv8A1xTca$Z
this is what I get from my upload script
https://nielsdewulf.me/screenshot/1HbkVpPEAgeOQPIkwsNIye$h

My code
https://nielsdewulf.me/screenshot/d91i1nsrx2y7HthsMRE$yHb4

So idk if this is some bug but I keep using regional selection and in the upload settings I kept the setting on so it detects my active window name.

**Comment by Jaex** [comment]
%t and %pn not reaches custom uploaders so you can't use them as parameter. So I need to remove them from textbox auto complete menu.

**Comment by Funergy** [comment]
Will it ever get added into the software?

**Comment by Jaex** [comment]
No.
