### ISSUE TITLE
Concerned about privacy

### ISSUE THREAD

**Issue by rbsriobr** [ShareX/ShareX#1371]
I accidentally pressed Paste (Ctrl + V) and Sharex sent the clipboard contents to an anonymous destination (Imgur) on the Internet. I think it would be interesting to add options as "none" in the <Destinations> <[Imagr, Text etc] upload:> menu and set them by default.

**Comment by Jaex** [comment]
Are you ever thinking thoroughly what you suggesting? If I make all destinations "none" as default. Thousands of people would be stuck unable to figure out how to upload to Imgur...

By the way If you uploaded something to Imgur by accident, open history window and right click that image and open deletion url so it will be removed from Imgur.

**Comment by McoreD** [comment]
@rbsriobr also the first ever message ShareX asks after ShareX is installed is if you would like to upload.
