### ISSUE TITLE
Quick Task Menu Menu Editor title characters

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1377]
In the Quick Task Menu Editor, can I use any characters to title/name the actions?
FOR MORE SEPARATION, can I change
Save, Upload, Copy Url 
to 
Save - Upload - Copy Url
or to
Save ~ Upload ~ Copy Url
or to
Save •• Upload •• Copy Url

And it will stick without going back to original text?
Or must I only use Comma to separate each task?
Thankyou

![sharex quick task menu editor](https://cloud.githubusercontent.com/assets/8550969/13475733/55fa5384-e079-11e5-8be6-f5bdec67bedb.PNG)

**Comment by Jaex** [comment]
Press edit button and change them to whatever you want.

**Comment by gotquestions** [comment]
Thankyou
