### ISSUE TITLE
Updater will not update to custom location.

### ISSUE THREAD

**Issue by Alaric-VISIGOTH** [ShareX/ShareX#1378]
I use custom install locations.

C:\Program Files\Utilities\Capture ShareX

Updater won't recognize and installs to.

C:\Program Files\ShareX

OS : Windows 10

Thanks

**Comment by Jaex** [comment]
Your issue is same with #1344 but still i thought it would remember last install location and install there. Not sure how to make it remember when doing -silent install.

**Comment by Alaric-VISIGOTH** [comment]
How about the ability to disable auto-updater? I don't mind to manually update.

Thanks

**Comment by Jaex** [comment]
You can disable from Application settings -> Advanced tab.

**Comment by Alaric-VISIGOTH** [comment]
Ticket #1344 is to do with desktop shortcuts. Not sure if issue is truly a duplicate?

**Comment by Alaric-VISIGOTH** [comment]
You can disable from Application settings -> Advanced tab.

K Thanks
