### ISSUE TITLE
Imgur Destination > URL is empty 

### ISSUE THREAD

**Issue by Vega88** [ShareX/ShareX#1380]
When destination is imgur, capture region, window, and monitor (I'm sure the rest) result in URL is empty. No changes were made, even if you upload after it still does it.

I apologize if this is an issue not controlled by ShareX and it's something up with Imgur. I am just double checking.. I have no idea how to report about this to Imgur, but it could be them for all I know. If it is, by all means close it.

**Comment by M4A1Silenced** [comment]
happening to me too

**Comment by Jokine** [comment]
Same

**Comment by Jaex** [comment]
Imgur works for me currently. Is it fixed maybe?

**Comment by M4A1Silenced** [comment]
seems like it

**Comment by Vega88** [comment]
Yes, it's fixed. Sorry for the inconvenience if any, just an issue with Imgur I guess.
