### ISSUE TITLE
Loss / corruption of data saved.

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ShareX/ShareX#1384]
I have taken over an estimated 500 screenshots in the month of Feb, 2016.  I had my computer reboot after locking up a couple times.  Simply rebooting does NOT cause 500 images to erase themselves off of my SSD.

I believe this program to be at fault because on every restart of the computer / sudden off - on cycle all of the configs for sharex are gone including the incremental numbering ect.  ShareX is the only program to experience this loss and hasn't till now caused me to lose actual data.  Now this has cost me a lot in terms of not being able to support my word in my line of work, including but not limited to providing tons of screenshots.

Sorry if I come across angry, I am extremely angry because I have been defrauded and now I don't have the proof of purchase (screenshot) to charge back the payment for goods never received.  Not to mention the loss of hundreds of memories and funny moments of last month.  With my memory loss I remember nothing small from last month pretty much.

**Comment by ZizzyDizzyMC** [comment]
I don't know how or why this happened but here is my issue, turns out ShareX probably doesn't know which folder to pick...  Honestly I don't understand how this even happened.  Two Documents folders? Come on Windows 10...
[http://zizzydizzymc.info/ss/00003.png](url)
My screenshots from last month are in one folder my ones from this month are in another folder.  Now I just need to find a proper method for merging both folders together.

Issue could be closed but I'm still wondering if anyone else has the issue with the settings being reset on a hard restart.  (Not shutdown -> turn on, just holding powerbutton till it shuts off.)

**Comment by campbeb** [comment]
I recommend you investigate setting up a backup solution for yourself so that you aren't at risk for losing weeks of work.

**Comment by Jaex** [comment]
ShareX can't remove your images, it is impossible.

About setting lose, ShareX saves settings when setting window closing, ShareX window minimize to tray or when computer is shutting down. And when saving happens if it become corrupt still ShareX have backup system that it will load previous setting. So I did everything I can for setting issue and there is nothing I can do more about it.
