### ISSUE TITLE
Disable screenlocking when using region capture

### ISSUE THREAD

**Issue by Christley** [ShareX/ShareX#1385]
i havent found an option to disable this, and ive asked around 2 forums and people told me it doesnt exist.

i want to suggest that you can disable the feature of "locking" the screen when you use region capture. right now it takes a snapshot and stops the screen from displaying anything until im finished. but i want to see what happens in the background and photograph what happens live.

puush have this feature, and its the only thing keeping me still using puush over shareX

**Comment by Jaex** [comment]
Capture -> Region (Transparent) is not lock screen.
