### ISSUE TITLE
When uploading GIF Files....

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#1386]
When uploading GIF files such as this http://i.imgur.com/qajTpZc.gifv it will not display in a forum until I remove the "v" and then place the link inside this code [img][/img].

The GIF I upload does not have this "v" extension so ShareX is adding that.

Why?

Is that a bug?

**Comment by BytewaveMLP** [comment]
GIFV is a format Imgur started employing around Oct. 9, 2014 to phase out GIFs by converting them to MP4/WebM files (in an embedded container, hence the controls at the bottom of the image).

This is not a bug, simply Imgur being helpful. Remove the v if you really need the massive, slow legacy format. :)

**Comment by MrCD1968** [comment]
How can I get the GIF to display then in a forum without having that extra step in having to remove the V? Otherwise the GIF shows as a broekn image in the forum.

**Comment by BytewaveMLP** [comment]
You can't. If the forum doesn't support the GIFV extension, it just won't work.

I suppose @Jaex could add an option for it, but is that really worth it?

**Comment by MrCD1968** [comment]
It is when I post 20 or 30 a day of animated creation in forums.  Certainly making an exception in ShareX cannot be that difficult. Otherwise I'll have to switch hosts.


  ----- Original Message -----

**Comment by MrCD1968** [comment]
Maybe add support for something like http://giphy.com/ or other GIF hoster that doesn't require modifying your data string so it will display.

**Comment by Jaex** [comment]
It is already exist:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/ShareX_xJucmnwccs.png)
