### ISSUE TITLE
Can't open task settings

### ISSUE THREAD

**Issue by Budfraiz** [ShareX/ShareX#1387]
> System.ArgumentOutOfRangeException: Value of '5000' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
> Parameter name: Value
>    at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
>    at ShareX.TaskSettingsForm..ctor(TaskSettings hotkeySetting, Boolean isDefault)
>    at ShareX.MainForm.tsbTaskSettings_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> ShareX 10.7 Steam

Tried uninstalling non-steam version and reinstalling the steam version to no avail

**Comment by Jaex** [comment]
#1350
