### ISSUE TITLE
Where to put Export Settings

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1389]
I want to export the ShareX settings.
So do I go to
Application Settings / Export
but then where do I place it?
Do I put it in 
Documents/ShareX
or Documents /ShareX/Backups folder?
Thankyou

**Comment by Jaex** [comment]
It is user choice where to export.

**Comment by gotquestions** [comment]
Okay I just didn't want to put it in a place where it would block or interfere with the operation of ShareX like putting it in Documents/ShareX.
Thankyou
