### ISSUE TITLE
paste.click support

### ISSUE THREAD

**Issue by theLMGN** [ShareX/ShareX#1390]
File sharing (accepts all file types.)  [API documentation](http://paste.click)

**Comment by Jaex** [comment]
Their API bad. It wants POST request but not even supports multipart form data.

**Comment by LMGN** [comment]
Alright, All I interprated that as "Their API is bad. It wants a post request but doesn't support blah blah blah technical phrase." xP

**Comment by yesBad** [comment]
Why's this still open. The website doesn't even exist anymore.
