### ISSUE TITLE
Transparancy lost when copying to clipboard

### ISSUE THREAD

**Issue by t3Nitro** [ShareX/ShareX#1393]
Steps:
* take screenshot and open with internal greenshot editor
* use Effects->TornEdge feature to make image borders transparent
* copy image to clipboard and paste to editor again

Actual
* transparency on edges of pasted image is lost

this was a greenshot issue: https://greenshot.atlassian.net/browse/BUG-1758
It's fixed now and last version of greenshot editor hasn't this issue, so updating libraries should help

**Comment by Jaex** [comment]
When this is false it can copy transparent image:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/ShareX_B0rg77RgII.png)

**Comment by t3Nitro** [comment]
Didn't help:
* False http://i.imgur.com/2RN2mek.png
* True http://i.imgur.com/Kc4mrcK.png

**Comment by Jaex** [comment]
Copied this image from greenshot image editor and did clipboard upload:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/5Bn5DXBHIn.png)

it is transparent.

**Comment by t3Nitro** [comment]
Please try copy/paste buttons inside editor: Capture->Torn->Copy-> Paste

**Comment by Jaex** [comment]
Editor paste button not uses ShareX clipboard methods.

**Comment by t3Nitro** [comment]
So this issue can't be fixed? Greenshot itself isn't have this issue

**Comment by Jaex** [comment]
I'm not planning to work weeks to be able to merge all changes manually one by one. It will be extreme amount of work.

**Comment by t3Nitro** [comment]
I see.. I hoped there was a simple way to fix this(

**Comment by Jaex** [comment]
Your issue fixed by #1406
