### ISSUE TITLE
Tray icon menu / Exit leaves mouse click event

### ISSUE THREAD

**Issue by campbeb** [ShareX/ShareX#1397]
Using latest version of ShareX on Windows 10 Pro 64-bit, if you right click the tray icon and then select Exit, ShareX closes, but then the mouse clicks whatever was under the Exit menu.

This appears to come from 7ca9f799b4cb4084e665a5b38228718ba7567048. The program closes on `MouseDown` which means it doesn't consume the `MouseClick`

You can see it happen below. After clicking Exit, you can see a window popup with is from it's tray icon being clicked.
![2016-03-10_16-58-37](https://cloud.githubusercontent.com/assets/1089399/13686073/ddc8e12c-e6e1-11e5-82b4-80499ee21246.gif)

**Comment by Jaex** [comment]
I did it on purpose because MouseClick event was happening after ContextMenu closed event and therefore I couldn't check for `forceClose` to not save settings if ShareX is actually closing.

**Comment by Jaex** [comment]
Okey found workaround for it.
