### ISSUE TITLE
Updater doesn't realize it needs administrator rights

### ISSUE THREAD

**Issue by QuadPiece** [ShareX/ShareX#1399]
I run ShareX on my work laptop where I don't have administrator rights and I'm just a regular user (Though I do have access to the admin account) - While updating ShareX however, the updater will just flat out fail instead of prompting for admin permissions like most installers/updaters do. The error message also doesn't even include a hint, such as "Try running the update again as an administrator"

---

Task: **Updating ShareX using a non-administrator account**

Expected behavior: **The updater should request a higher privilege level using a UAC window**

Actual behavior: **The updater will simply fail and throw permission errors.**

**Comment by Jaex** [comment]
I was removed it because of request from #1267
