### ISSUE TITLE
Self-Signed SSL Certificates

### ISSUE THREAD

**Issue by Farfie** [ShareX/ShareX#1400]
Hi,

I run a pomf clone (not currently in ShareX's default directories, and I would not like it there), however, I use a self-signed ssl certificate for https connectivity, and I'm assuming that ShareX is denying it automatically (like modern browsers), so I cannot use https through ShareX.

If I'm wrong about this, and something else is at play here, I apologize. If I'm right about how it's handling the cert (because I have not looked at ShareX's code), I believe there should be perhaps an option in the general advanced area to reverse this functionality to simply accept self-signed certs. Or, you could take the browser approach, and ask the user the first time they attempt to use any self-signed site. I suppose the perfect world would have both, but the advanced-option method seems easier to implement for you guys.

Thanks a ton for your consideration,
Farfie

**Comment by BytewaveMLP** [comment]
I'm not sure what kind of configuration you have here, but if you're running any sort of standard web server, [Let's Encrypt](https://letsencrypt.org/) has been in public beta for a while, and offers free, signed SSL certificates.

**Comment by Farfie** [comment]
Thank you for the suggestion, but there are many problems. Firstly, I am all Windows, and I wouldn't trust a Windows build found on the internet, nor do I feel like installing Linux for a cert. Secondly, depending on their method of proving that I own the domain, I may not be able to do that. For example, startcom makes you choose from a list of emails that point at the domain - but I don't own any of them because I use dynamic dns to map my ip to a human friendly name. Thirdly, I don't really need any trust or publicity - I use this site for myself and some friends and the only spec I really care about is SSL's end to end encryption. And finally, even if I did get a public cert just to get ShareX working, I love ShareX and would continue to assert that this should be handled somehow, even if it is extremely low priority.

**Comment by Jaex** [comment]
If I add this how can I test it?

**Comment by Farfie** [comment]
@Jaex I guess the easiest way would be to use my website. Would you like me to message it to you? I'd like to keep the URL away from public forum.

**Comment by Jaex** [comment]
Yes use website contact form.

**Comment by Farfie** [comment]
Pardon, but could you link it? Did you mean getsharex.com? I can only find an IRC link there, and GitHub doesn't seem to support messages in a regular fashion? Very strange. If you can't tell, I don't really do any work here, heh.

**Comment by Jaex** [comment]
yes getsharex.com bottom right corner.

**Comment by Farfie** [comment]
@Jaex
Weird - me and another friend cannot see the contact form, but the 3rd one could, so I had him send the info. I've tried disabling all of my addons, but I don't know why we can't see it and he can.
