### ISSUE TITLE
Unable to launch ShareX

### ISSUE THREAD

**Issue by CoughDropDev** [ShareX/ShareX#1401]
System.IO.FileNotFoundException: Could not load file or assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

ShareX 10.8 Release

Picture: https://gyazo.com/19ef9b8e5fb66a54c68c18e0a56a29f5

**Comment by Jaex** [comment]
#1398
