### ISSUE TITLE
Random Nouns and Adjectives in name patterns

### ISSUE THREAD

**Issue by SurelyExploding** [ShareX/ShareX#1403]
A site called [GFYCat](http://gfycat.com/) allows users to upload gifs and convert them into videos. It uses a unique file naming system where, instead of using numbers or letters, uses a pattern of two adjectives, and then the name of an animal, such as [OblongYoungChipmunk](https://giant.gfycat.com/OblongYoungChipmunk.webm). Since some people prefer to self host images and videos captured with ShareX, their file naming patterns are limited. Would it be possible to add similar functionality to ShareX?

**Comment by Jaex** [comment]
I don't like that naming format and see no point in such format. Random alphanumeric file naming is far better security with less characters.

**Comment by Jaex** [comment]
Added it now:

![](https://jaex.getsharex.com/2018/01/SphericalLemonchiffonVulture.png)
