### ISSUE TITLE
Upload from url does current image name.

### ISSUE THREAD

**Issue by theoddball** [ShareX/ShareX#1407]
I use amazon s3 (oddball.tf) for my image hosting, and I have to do %ra%ra%ra%ra%ra for my file names. When I upload from a url; take http://forums.backpack.tf/uploads/profile/photo-11007.jpg for example, it calls it the current image name: http://i.oddball.tf/8vl3B.png
http://i.oddball.tf/jGKwO.png Have file uploads file name selected too.

**Comment by Scrxtchy** [comment]
if we replaced
https://github.com/ShareX/ShareX/blob/master/ShareX/WorkerTask.cs#L240
```
task.Info.FileName = filename;
```
where filename is
https://github.com/ShareX/ShareX/blob/master/ShareX/WorkerTask.cs#L231
```
            string filename = URLHelpers.URLDecode(url, 10);
            filename = URLHelpers.GetFileName(filename);
            filename = Helpers.GetValidFileName(filename);
```

with 
```
            if (task.Info.TaskSettings.UploadSettings.FileUploadUseNamePattern)
            {
                string ext = Path.GetExtension(task.Info.FilePath);
                task.Info.FileName = TaskHelpers.GetFilename(task.Info.TaskSettings, ext);
            }
```

I think

**Comment by Jaex** [comment]
You can use %ra{5} by the way.
