### ISSUE TITLE
No longer running on Windows 10

### ISSUE THREAD

**Issue by ama4tf** [ShareX/ShareX#1412]
It won't show in the system tray and attempting to restart the application does nothing

**Comment by Jaex** [comment]
Did you checked Task manager is ShareX running?

**Comment by ama4tf** [comment]
It is not. Restarting the program adds it for a second before it disappears

**Comment by Jaex** [comment]
Is it possible .NET framework 4.0 missing? Did you tried removing Documents/ShareX folder.

**Comment by Aokromes** [comment]
Works for me on 10.0.14291
