### ISSUE TITLE
Feature Request: Pastebin and Gist Raw Link

### ISSUE THREAD

**Issue by Mikeeeyy** [ShareX/ShareX#1416]
Please could you add a simple checkbox to Pastebin and Gist in destination settings to get the raw link? Maybe add it for the other text uploaders too although I don't use them so I'm unsure if raw is available, but on Pastebin and Gist it is.

http://pastebin.com/7EfDBh1V
http://pastebin.com/raw/7EfDBh1V

https://gist.github.com/anonymous/6178fc1998b56203d3d6
https://gist.github.com/anonymous/6178fc1998b56203d3d6/raw

Thanks,
Mike

**Comment by Jaex** [comment]
I uploaded text to pastebin now and raw link not works:
https://pastebin.com/raw/Cy16fath
it redirects to non raw page.

**Comment by Mikeeeyy** [comment]
It appears raw for me:
http://i.imgur.com/iuJFrBh.png

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/chrome_OWe6TpaTGc.png)

**Comment by Mikeeeyy** [comment]
Maybe it has to be loaded once before raw can be used.

**Comment by Jaex** [comment]
I added raw link support but none of those raw links open for me and shows captcha instead.

**Comment by Mikeeeyy** [comment]
It's for that reason I use Gist instead, please add support for that too.

**Comment by Jaex** [comment]
Your example GitHub raw url was wrong. Response was including proper raw url.

**Comment by Mikeeeyy** [comment]
But the proper raw url is super long :P

**Comment by Jaex** [comment]
But proper raw url not redirects. Your short url can cause problems if need to be used directly.

**Comment by Mikeeeyy** [comment]
Okay, I'm happy with any kind of raw URL, great software you have made here and great support. Keep up the good work!
