### ISSUE TITLE
ShareX.ScreenCaptureLib.dll contained just zeros

### ISSUE THREAD

**Issue by XorFish** [ShareX/ShareX#1420]
At program start I had the en unhandeled exeption for the last few times.

ShareX-Log:
http://pastebin.com/7pHwtwGD

ApplicationConfig.json:
http://pastebin.com/jmmSjYh3

But the issue seems to be that the 
ShareX.ScreenCaptureLib.dll contains just zeros(hex) and thus failed to load.

Reinstalling ShareX resolved the issue for now.

Posting in case someone else experiences the same problem.

**Comment by Jaex** [comment]
ShareX codes can't modify dll files. Not sure what could too.

**Comment by AndrewDownsend** [comment]
Same issue for me, happened after an update, there goes my custom settings....

**Comment by XorFish** [comment]
@AndrewDownsend 

Have you opened the dll file in a hex editor?

Mine was also fine from the size but contained just zeros.
