### ISSUE TITLE
Website Capture To Local Disk

### ISSUE THREAD

**Issue by ISJ-439** [ShareX/ShareX#1421]
It wouldn't be that much code, yet it would save me/others a lot of time collectively. What do you guys think?

[Something like this maybe?](http://i.imgur.com/FDyy8EY.png)

**Comment by m4nd1cm4rk0** [comment]
How to you mean website capture?
All pages?

**Comment by Jaex** [comment]
It is not actually "Upload" button it just runs task using your "After capture tasks". So it is actually possible to only save.
