### ISSUE TITLE
When closing the app, form is hidden but process is still running

### ISSUE THREAD

**Issue by m4nd1cm4rk0** [ShareX/ShareX#1423]
If it's not suppose to be like that, than:

private void MainForm_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (e.CloseReason == CloseReason.UserClosing && Program.Settings.ShowTray && !forceClose)
            {
                e.Cancel = true;
                Hide();
                Program.SaveAllSettingsAsync();
            }

            Application.Exit(); this is addition
        }

**Comment by Jaex** [comment]
You mean ShareX icon not shows in tray bar too? Are you closing ShareX from tray menu?

**Comment by m4nd1cm4rk0** [comment]
Yes and when i click x on top right, MainForm is hidden(closed) but vshost.exe background process is running.
I'm not sure if you was planning to do in that way.

**Comment by m4nd1cm4rk0** [comment]
Ok, i got it. Everything is fine now :)
