### ISSUE TITLE
Custom Uploader Error Handling?

### ISSUE THREAD

**Issue by mrmcpowned** [ShareX/ShareX#1428]
Is there any kind of error handing syntax or something for custom uploaders so they know the response is an error? That way, ShareX can react appropriately (like letting me re-upload the file instead of saying it "worked" when it didn't).

**Comment by Jaex** [comment]
If parsing of url fails or url is empty then it will fail. Then people can right click and check response (I fixed issue recently about that show response was not showing up for custom uploader).
