### ISSUE TITLE
Get Error at startup

### ISSUE THREAD

**Issue by HHimbergen** [ShareX/ShareX#1437]
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.BadImageFormatException: Die Datei oder Assembly "ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
   bei ShareX.TaskSettings..ctor()
   bei ShareX.ApplicationConfig..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance[T]()
   bei ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   bei ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   bei ShareX.Program.LoadProgramSettings()
   bei ShareX.Program.Run()
   bei ShareX.Program.Main(String[] args)

ShareX 10.8 Steam

**Comment by Jaex** [comment]
That error means library file become corrupt. Reinstall ShareX to fix it.

#1049
