### ISSUE TITLE
Modified Greeshot version Icons very small and not adjustable (Surface Book)

### ISSUE THREAD

**Issue by schlafesbruder** [ShareX/ShareX#1442]
Hi, so I love this software, but I have one problem that keeps me from using it. The greenshot editor, which is so handy with the bubbles, arrows, etc., has super small icons. In the normal greenshot version I can adjust the icon sizes. But in ShareX I cannot. How can I change this please?

I am unable to upload my screenshot because I keep getting a really wrong error :( But I hope you can help me.

**Comment by Jaex** [comment]
#1341

**Comment by schlafesbruder** [comment]
Sorry, I saw. And thanks for the very fast response. Is it not possible to just increase the size, I dont care if the icons are ugly. Can I adjust the size locally? Like download the code and change the size properties and compile it for just me? 

Or asked differently: Do you have a suggestions for me that will help me get bigger icons? No need for fancy solution if too much effort

**Comment by Jaex** [comment]
Don't you read issue i linked which @campbeb tells it is fixed.

**Comment by schlafesbruder** [comment]
I read it. I have ShareX 10.8 and Greenshot 1.2.8.12 and in the GreenshotImageEditor file the mentioned property is not existing, the line is missing! What am I doing wrong?

**Comment by Jaex** [comment]
He tells "once the next version of ShareX is released".

**Comment by schlafesbruder** [comment]
You respond so quick and do good support and you even link all the tickets into the correct other tickets, etc. Jaex, great work! I work in IT and we need people that work so thoroughly!!! Looking for a job? :)
