### ISSUE TITLE
.jsx support (and other formats)

### ISSUE THREAD

**Issue by tag9724** [ShareX/ShareX#1449]
Add default destination for .jsx files to text hoster (like gist or pastebin),
and add the possibility to set the default hoster for specified extensions.

Thanks

**Comment by Jaex** [comment]
You can add it yourself from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/ShareX_jhAZ7Q84lc.png)

**Comment by tag9724** [comment]
wow thanks I have not see this option, sorry for that
