### ISSUE TITLE
Autoupdate fails because of "Access is denied"

### ISSUE THREAD

**Issue by CasualX** [ShareX/ShareX#1454]
I have installed ShareX 10.7.

Upon starting the program it asks me to update to a newer version 10.9.1. I press 'Yes'.

It downloads ShareX-10.9.1-setup.exe which is successful.

The installer window Errors with:

```
---------------------------
Error
---------------------------
C:\Program Files\ShareX\unins000.exe



An error occurred while trying to create a file in the destination directory:

Access is denied.



Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
---------------------------
Abort   Retry   Ignore   
---------------------------
```

I have 2 local windows user accounts, one Admin with admin privileges and a normal user account which I login to and use. I'm expecting the installer the ask for admin privileges before continuing.

Manually downloading the latest version and running the installer runs into the same error. Manually running this installer as admin works and the install proceeds as expected.

**Comment by Jaex** [comment]
I was added "run as admin" for updater to latest version so in future versions it will ask for admin. Maybe I should make that option as setting so people can disable it if they want and having it ask for admin by default.
