### ISSUE TITLE
Maximized bug since last update

### ISSUE THREAD

**Issue by thijsa** [ShareX/ShareX#1455]
Since the last update, the screenshot edit window doesn't popup maximized anymore, which is very annoying. It makes the window the size of the screenshot. When you have a big screenshot like 1920x1080, it displays it in the right corner over multiple monitors, so you cant see the picture anymore. An update ago, it always came in maximized.
Video:
https://www.youtube.com/watch?v=PrZKRWMOnbc

**Comment by Jaex** [comment]
You mean this request #1189 broken your behavior?

**Comment by thijsa** [comment]
Yes.

**Comment by thijsa** [comment]
Maybe make this optional in the settings?

**Comment by Jaex** [comment]
@campbeb what you think?

**Comment by thijsa** [comment]
@Jaex Thanks!

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/ShareX.vshost_PBpS058B9v.png)
