### ISSUE TITLE
Is there audio in screen recording?

### ISSUE THREAD

**Issue by misterpuggers** [ShareX/ShareX#1456]
If there is audio support in the screen capture tool, how come I cant hear anything when I'm done? also, the microphone its connected to doesnt pick up anything.... if there are these features in this application, can u guys help??

**Comment by Jaex** [comment]
Did you checked these:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/ShareX_aetRnNi2pY.png)

**Comment by misterpuggers** [comment]
thanks this helped, but im having trouble recording games on Steam, i can
record gameplay on games with an option of windowed/ fullscreen, but Steam
games dont really have this option, so whenever i try recording a gameplay
of a Steam game, it stays recording on the desktop, not the game, help?

**Comment by Jaex** [comment]
#848
