### ISSUE TITLE
After new update: IconSize property missing?

### ISSUE THREAD

**Issue by schlafesbruder** [ShareX/ShareX#1458]
Hi, am I doing something wrong? I was very excited about the new update. But still the icon size is very small when I want to annotate screenshots afterwards.

Other closed issue said there will be "IconSize"-property in config file, but its not there. Cant find anything in changelog about this either. Comment?

**Comment by Jaex** [comment]
I removed Documents/ShareX folder then opened ShareX and image editor. And config was containing IconSize.

**Comment by schlafesbruder** [comment]
Thank you. I did the same steps and I also found it. But still a problem. Here is what I did:
1. Did your steps successfully
2. Changed IconSizes to 32, 32
3. Saved, opened file again to check (32,32. correct)
4. Used my hotkey combination to take screenshot of screen region - selected random screenregion
5. Selected custom option I created "Annotate and copy to clipboard", the editor opened, Icons are STILL SMALL SIZE
6. I go back to config file and the IconSize is BACK AGAIN TO 16, 16.

Please try to reproduce using these steps. Apparently it removes the changes when the file is accessed?

**Comment by Jaex** [comment]
Did you closed ShareX when changing config files?

**Comment by schlafesbruder** [comment]
I am a noob. Sorry. It's working now. I AM SO HAPPY! LOVE YOU! Thanks thanks thanks!!!

**Comment by Jaex** [comment]
You don't need to edit config file yourself in next version by the way: #1455
