### ISSUE TITLE
Quick Task Menu Settings

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1460]
Last few times I updated ShareX I lost all my Settings in Edit Quick Task Menu which took a long time to sort out and redo.
This time I went to Application Settings and Exported Settings.
Will that hold the settings for Edit Quick Task Menu to import?

Why are all ShareX settings not automatically integrated into each ShareX update?
Thanks

**Comment by Jaex** [comment]
Yes it will hold all settings. None of settings will lose when upgrading ShareX.
