### ISSUE TITLE
Support for Microsoft Azure Blob storage

### ISSUE THREAD

**Issue by zerg-junior** [ShareX/ShareX#1461]
Hi,

It would be nice to be able to directly upload from ShareX to Azure Storage.

Docs: [Get started with Azure Blob storage using .NET](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-blobs/)

**Comment by bladefist** [comment]
This would be great, was just looking for this.

**Comment by fosterbuster** [comment]
Anyone currently working on this? I figure I could implement it rather quickly.

**Comment by Jaex** [comment]
Nobody working on it.

**Comment by bladefist** [comment]
@wi5nia they won't approve the pull request if you use the azure sdk.  They don't want more DLLs in the project.  Has to be a custom c# implementation.

**Comment by wi5nia** [comment]
I'm doing it in pure REST API calls so don't worry @bladefist :)

**Comment by wi5nia** [comment]
Pull request done so now just waiting for Jaex to accept :) #2229
