### ISSUE TITLE
Can not create IPC port. Access denied.

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1462]
System.Runtime.Remoting.RemotingException: Kan geen IPC-poort maken: Toegang geweigerd.

   bij System.Runtime.Remoting.Channels.Ipc.IpcServerChannel.StartListening(Object data)
   bij ShareX.HelpersLib.ApplicationInstanceManager.RegisterRemoteType(String uri)
   bij ShareX.HelpersLib.ApplicationInstanceManager.CreateFirstInstance(EventHandler`1 callback)
   bij ShareX.Program.Main(String[] args)

ShareX 10.9.1 Release

**Comment by xCryptic** [comment]
I just got this error too.

**Comment by Jaex** [comment]
This issue was not exist in 10.8.0 ?

**Comment by YasseenDeHerdt** [comment]
I don’t know.

**Comment by Jaex** [comment]
If you can still reproduce your error, can you try installing previous version https://github.com/ShareX/ShareX/releases/tag/v10.8.0 and test it?

**Comment by YasseenDeHerdt** [comment]
I have 2 accounts on my computer, with my main account I have no problem, on my guest account, I get this error. If that helps? I’ll try installing 10.8.0.

**Comment by Jaex** [comment]
I fixed it but not 100% sure is it fixed correctly because can't test it.

**Comment by NobleUplift** [comment]
So wait, how do we fix this to allow ShareX to be booted up on two different user accounts?
