### ISSUE TITLE
Installer publisher unknown

### ISSUE THREAD

**Issue by chasehaddleton** [ShareX/ShareX#1463]
When installing the program on Windows 10 (only platform tested on) the UAC prompt warns that the installer is from an unknown publisher. This was verified on my two personal devices and on my friends computer. 

Have you guys considered [signing your code](https://msdn.microsoft.com/en-us/library/ms537361(v=vs.85).aspx)?

![UAC Prompt](http://img.chasehaddleton.com/e96910014f_1459194245.png)

**Comment by Jaex** [comment]
I'm not planning to give hundreds of dollars every year just so Microsoft show publisher.
It is only viable for paid softwares or big companies.
