### ISSUE TITLE
[10.8] I stopped working after upgrade

### ISSUE THREAD

**Issue by Ya-Grisha** [ShareX/ShareX#1464]
HI
Veri good programm!

Problem:
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> System.BadImageFormatException: Не удалось загрузить файл или сборку "ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Ожидалось, что модуль содержит манифест сборки.
   в ShareX.TaskSettings..ctor()
   в ShareX.ApplicationConfig..ctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   в System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.Activator.CreateInstance[T]()
   в ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   в ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   в ShareX.Program.LoadProgramSettings()
   в ShareX.Program.Run()
   в ShareX.Program.Main(String[] args)

ShareX 10.8 Release

**Comment by Jaex** [comment]
That error means library file become corrupt. Reinstall ShareX to fix it.

#1049
