### ISSUE TITLE
Framedrops if recorded with audio

### ISSUE THREAD

**Issue by Sodazer0** [ShareX/ShareX#1468]
I am pretty sure this was discussed one billion times. 
But me no find no place on the web to follow up this topic.

I tryed 
x256/ 265
VP8
Xvid

and various audio codecs with various quality options.

Couldn`t manage a pairing of audio+video codes that would not result in framedroping in the final record.

I checked my CPU usage during the record by WindowsTaskManager. 
Doesn`t seem very havy on the CPU.

I really would love to have some backround music within my VideoScreenRecordUploads

btw.
Boy, do I love your Software. Amazing work.

**Comment by Jaex** [comment]
We didn't wrote FFmpeg or video/audio devices. We have no control over those stuffs other than changing encoding options.
