### ISSUE TITLE
Feature Request: Integrate support for BackBlaze B2 for file uploads

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#1471]
I just switched from Amazon S3 to Backblaze B2. Thanks!

**Comment by Jaex** [comment]
Isn't it using Amazon S3 API?

**Comment by Sushubh** [comment]
Ok. Just noticed that there is an endpoint field. It include DreamObjects which is the S3 implementation by Dreamhost. But there is no endpoint for Backblaze so that would need to be added if it is using the same API.

**Comment by Jaex** [comment]
#1058

**Comment by SystemUpdate** [comment]
Any updates on this?

**Comment by Sushubh** [comment]
I would like to know it too as B2 has come out of beta this week!

**Comment by Jaex** [comment]
I didn't made Amazon S3 uploader.

**Comment by Keavon** [comment]
This would be a really nice feature.

**Comment by Jaex** [comment]
Now I wanted to test BackBlaze but it want mobile phone number from me. Why would I give my phone number to random web site. So I can't test it.

**Comment by Keavon** [comment]
You could use Google Voice to get a phone number to give them. Or if it's not too complicated to set up, I could try testing it for you.

**Comment by ajthemacboy** [comment]
I would very much like B2 support as well. @Jaex, I can guarantee that Backblaze wouldn't do anything bad with your phone number, they are a very reputable company.

**Comment by ckippen** [comment]
I would like BackBlaze to be supported as well.

**Comment by Jaex** [comment]
ShareX supports custom Amazon S3 implementations which using v4 signing, are you sure it is not supported?

**Comment by Jaex** [comment]
I check here now: https://www.backblaze.com/b2/docs/ and it is not Amazon S3 API.

**Comment by Keavon** [comment]
Any status updates for this? It would be massively helpful for me to have this supported.

**Comment by matthewburnett** [comment]
As with Jaex, I lack an account to work with, though for anyone else interested, they even include C# examples. https://www.backblaze.com/b2/docs/b2_authorize_account.html

**Comment by tinybarks** [comment]
To those of you who are still interested, I have added support for B2 in the following PR, which has been merged: #3637 

You can wait until the next official release of ShareX (12.3.0, I think?), or grab any nightly newer than 12.3.0.3567 from [here](https://ci.appveyor.com/project/ShareX/sharex/history) if you want to try it out now. 

Note that [Backblaze B2 partnered up with CloudFlare](https://www.backblaze.com/blog/backblaze-and-cloudflare-partner-to-provide-free-data-transfer/), which means that data transfer between B2 and CloudFlare is now free. Might be appealing for some of you, especially combined with the free tier's free storage.
