### ISSUE TITLE
Small Bug

### ISSUE THREAD

**Issue by mikhoul** [ShareX/ShareX#1473]
I've just updated directly from ShareX and after the Update ShareX updated but loaded the "default settings" instead of my custom settings. I use SX in english but my Win is French so the interface was in French and everything was at default settings.

I exited SX and restarted and this time my settings were loaded,not a big thing but annoying since I was thinking I had lost my custom settings.

Regards :)

**Comment by Jaex** [comment]
Is your settings stored in default folder?

**Comment by McoreD** [comment]
When you say directly, do you mean pulling the latest source code and compiling it? We did a PersonalPath.cfg change in the source a few hours ago, but don't think that is now buggy.

**Comment by mikhoul** [comment]
* My settings are stored in  the _program folders_  AKA K:\ShareX for me ;-)

The bug is always there,  I just updated  to 10.9.1 same thing happened: 

I updated directly via ShareX interface:
http://i.imgur.com/F6f20BK.png

And now my language is back in french (Win OS is French) instead of english and all customization are not loaded. I closed completely SX and restarted SX ans language is back in english and my settings are back.  :blush:

**Comment by Jaex** [comment]
When that happen check debug log to see what is wrong.
For ShareX personal folder path did you used relative path?

**Comment by mikhoul** [comment]
Look here the log: http://i.imgur.com/8H1uOIt.png

You can see when it save the config/settings everything is fine **<ins>BUT</ins>** right after for a strange reason ShareX load the default for everything except the shortcuts.

You can clearly see that when I close ShareX and reopen it load my custom settings and revert to english language (from French).  :yum:

**Comment by Jaex** [comment]
ShareX 10.5.0 ?

**Comment by mikhoul** [comment]
Yep !

**Comment by Jaex** [comment]
We don't support old versions because problem could be solved in new version and it will waste our time trying to figure out why issue happens when it is already not exists.
