### ISSUE TITLE
Accidentally moved the folder with my ShareX screenshots into another folder, now all screenshots deleted?

### ISSUE THREAD

**Issue by pokerei** [ShareX/ShareX#1474]
My ShareX directory was originally in my Pictures folder, but I put that said pictures folder into another folder to categorize it, and when I opened my screenshots directory, only screenshots from that day were there, and all of my other ones from December 2015 - April 2016 were gone.

I was wondering where these are stored and if there is any way to recover them?

**Comment by Jaex** [comment]
ShareX can't delete or move any screenshots. I don't know where you moved your folders.

**Comment by pokerei** [comment]
I had a folder named "Old Pictures" which I created a copy of, and moved into the new folder, "Pictures."
I opened up my Screenshot directory and all were gone, I don't know what happened.

**Comment by Jaex** [comment]
Did you changed ShareX screenshots folder to point to your new destination?
It is not possible for ShareX to delete any file or folder.
So your screenshots must be somewhere where you moved them.
