### ISSUE TITLE
Upload PDF as image

### ISSUE THREAD

**Issue by Dreadaxe** [ShareX/ShareX#1475]
Possibility to add this function?

**Comment by Jaex** [comment]
Check here to configure any extension as image:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/ShareX_kPjH4NFn0T.png)

**Comment by Dreadaxe** [comment]
Excellent! 

What about the PDF with multiple pages?

**Comment by Jaex** [comment]
I thought you asking how to upload pdf to image destination. You didn't told you want to convert pdf to image.

**Comment by Dreadaxe** [comment]
Ok. So only the PDF with one page can be uploading. Ok.

**Comment by Jaex** [comment]
No.

**Comment by Dreadaxe** [comment]
Ok. It's imgur that convert the first page of PDF to image.

**Comment by wanghaisheng** [comment]
@Jaex  does  shareX support capture  screen into navtive pdf files（not embed image into image  when you open pdf with preview tools ,all  you can see is  a picture instead of i can choose text ）  instead of image
