### ISSUE TITLE
Greenshot Image Editor Enhancements

### ISSUE THREAD

**Issue by mmerlin10** [ShareX/ShareX#1476]
It would be really nice to improve the Greenshot Image Editor with the following features:

1. Add new button for 'Copy to clipboard & Close' - this is the action I take 99% of the time

2. Add zoom in / out buttons - I often need to crop the captured images to pixel precision and it is very difficult w/o ability to zoom in couple levels

3. Customizable toolbar buttons - allow hide / arrange the buttons in the top toolbar - I ultimately only use small subset (mainly copy to clipboard)

4. Allow for custom shortcuts for the toolbar buttons

5. Show shortcuts for buttons on cursor hower over the button

Thanks a lot for an awesome program!! :-)

**Comment by Jaex** [comment]
You know we are using customised version of [Greenshot](http://getgreenshot.org/) image editor, right?

**Comment by Jaex** [comment]
#219

**Comment by mmerlin10** [comment]
Hi Jaex,

yes, I know it but I am a bit unclear on what that means when it comes to enhancements - the main purpose of this ShareX is to come up with end-to-end solution for users to capture screen which definitely includes image editor. If it is not possible to enhance that image editor then maybe the choice of Grenshot was a wrong one and should be reconsidered so that it is not a roadblock... I still think the above enhancements are good for ShareX users.

**Comment by JNavas2** [comment]
My own take is that the editor badly needs Mouse Wheel Zoom!
