### ISSUE TITLE
Compilation error in ShareX.HelpersLib\Forms\QRCodeForm.resx

### ISSUE THREAD

**Issue by decay42** [ShareX/ShareX#1479]
I'm trying to build ShareX (cloned master as is) in Visual Studio 2013 and getting a weird error during the build process.
It says the ResX file is invalid, the error message points to line 129, Column 5 and I can't open the file in ressources view. Visual Studio just says "Unknown error".

Here's the original (german) error message:

    Fehler	1	Ungültige ResX-Datei. Der angeforderte Wert "Ctrl" konnte nicht gefunden werden. Zeile 129, Position 5.	C:\Users\jpfeiffer\Documents\dev\Projekte\ShareX_dev\ShareX.HelpersLib\Forms\QRCodeForm.resx	129	5	ShareX.HelpersLib

**Comment by Jaex** [comment]
You can't compile ShareX with VS2013 because it don't support new C# features.

**Comment by decay42** [comment]
Thanks.

You could add a note to the wiki page for "Code contribution", that you need Visual Studio 2015 for compiling.

**Comment by Jaex** [comment]
Good idea.

**Comment by McoreD** [comment]
VS2015 Community Editioni is free by the way.

**Comment by decay42** [comment]
Short update: tried with a fresh install of VS 2015 Community: same file, same error ..

**Comment by Jaex** [comment]
That error happens in German Visual Studio. Another german guy was reported it too back then. It is bug in Microsoft side. But there is workaround for it, replacing Ctrl with Control should work.
