### ISSUE TITLE
More random options for name patterns

### ISSUE THREAD

**Issue by Zelpa** [ShareX/ShareX#1481]
Would it be possible to add more random options to the name patterns? The hexadecimal one is nice, but something like base64 would be appreciated. With custom length like hexadecimal of course.

**Comment by Zelpa** [comment]
Actually now that I think about it this could cause issues with lower and upper case letters being regarded as the same. At the very least we could have base 36 encoding, A-Z 0-9.

**Comment by Jaex** [comment]
Why don't you just use random alphanumeric, it is better.

**Comment by Zelpa** [comment]
Huh, somehow I missed the random alphanumeric one. Guess that solves that then.
