### ISSUE TITLE
ShareX will not honor failed upload's previous upload location on re-upload

### ISSUE THREAD

**Issue by mrmcpowned** [ShareX/ShareX#1482]
If for example I have a hotkey set up to upload to my own server, and have my global upload settings set to mega, if the upload to my server fails and I click "Upload" in the right-click menu, ShareX will instead upload to mega and not my web server. I don't think this should be the intended behavior when re-uploading failed uploads. Re-uploading failed uploads should honor the previous uploaded location, and maybe after X amount of attempts ShareX could prompt whether the file should be uploaded to the global setting.

**Comment by Jaex** [comment]
Current behavior is better I think because if my upload fails that means that destination have problem so I will change destination then right click and do upload. If it uploaded to same destination then it would give error always and would have no point.
