### ISSUE TITLE
High-Contrast-Mode ignored! Accessibility ignored!

### ISSUE THREAD

**Issue by MartinL0815** [ShareX/ShareX#1487]
Having activated the high-contrast-mode with the yellow on black high-contrast-#1 theme ShareX looks sincerely like this and is unusable:

>![image](https://cloud.githubusercontent.com/assets/525700/14378499/8c8ddc54-fd75-11e5-8bbd-123db003e89d.png)

Please consider to fix this explicitly background coloring for high-contrast usage!

As example for a correct coloring the Windows 7 explorer:

>
![image](https://cloud.githubusercontent.com/assets/525700/14378576/fe7d8832-fd75-11e5-8d66-ab793a24acb8.png)

**Comment by Jaex** [comment]
May I ask why would you use such colors? It looks horrible to be honest.

**Comment by MartinL0815** [comment]
Some people those colors "hurts", for me it is an accessibility feature to allow me to work with computers since I have eye disabilities!
The high-contrast-mode in Windows is a special "overriding" and mandatory mode!
If enabled, the coloring is mandatory for all applications (take a look at MDSN) and that's all about supporting people like me with eye disabilities.

**Comment by Jaex** [comment]
In many places I set form background as white because default color gray was not looking good. Just for 0.01% of people gonna use high contrast theme, am I need to make 99.99% of people to get bad background colors in form? That not looks logical to me.

**Comment by MartinL0815** [comment]
No need to step back!

Dark/black based high contrast is detectable!

I will send you the details this weekend!

So detect the high contrast mode and use the system color COLOR_WINDOW as background color instead of white!

You made the decision to don't let people decide how the applications should look via Windows theming, that is your thing, to exclude 0.01% of those needing a change on the coloring … possible with a simple change … are you sure, you want this?

Kind regards,

Martin Lemburg
Berlin / Germany

martin.lemburg@gmx.net
http://about.me/Martin0815


------- Original message -------

**Comment by Jaex** [comment]
I'm trying high contrast mode now and it is like torture to my eyes. I wonder what kind of eye issues cause this mode to be helpful.

**Comment by Jaex** [comment]
Also custom colors becomes problem in this mode because I was set custom highlight and selected colors like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/gUaoJbmYm1.gif)

**Comment by MartinL0815** [comment]
So you have Inge location, where you configure the colors to be used for 
selection, background and what ever?

Take a look at the man page of GetSysColor, referee all constants are 
describes.
Next to "COLOR_WINDOW (TEXT| FRAME)?" there are highlight cookie 
definitions.

Please don't care for beauty in high contrast! It's all about usability and 
functionality!

Best regards,

Martin Lemburg
Berlin / Germany

martin.lemburg@gmx.net
http://about.me/Martin0815


------- Original message -------

**Comment by Jaex** [comment]
I noticed there is problem in .NET menu item controls that check tick icon not uses proper color therefore it is not possible to see tick icon:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/devenv_KEuCe0bzDb.png)

**Comment by Jaex** [comment]
One by one I checked every form to be sure all colors correct but I could of missed few of them.
Also that tick icons still not visible in menu because of .NET problem not to do with me.
Are you using Visual Studio, to be able to test changes?

**Comment by MartinL0815** [comment]
Sorry with .NET and the checked menu items, but I never developed really intensively with .NET.
I'm a C++, WIN32, MFC developer and never had such problems in all the years!

But ... I will take a look at this at Monday, when I'm back at the office, where I'm able to check with VS2013.

**Comment by MartinL0815** [comment]
BTW about my eye disability.

In my eyes the connection between retina and optical nerve is working, but the beginning of the optical nerve is not working correctly, so that the "information" is transported from the retina incompletely and slower than normal.
In consequence e.g. every white area in an UI dazzles me, because my brain is not able to react correctly at the bright light.
Same with massive sun at a sunny day! Direct sun light in my eyes is too much!

I need strong contrasts and balanced lightening to have a good sight.

**Comment by Jaex** [comment]
You can't compile with VS2013 because new C# features require VS2015.

**Comment by MartinL0815** [comment]
Hi,

I found a page about drawing attributes.
I had no time to read it completely, but there is a reference at 
https://msdn.microsoft.com/en-us/library/ms837933.aspx about setting the 
color of the menu item check mark!

Happy rest of weekend!

Martin Lemburg
Berlin / Germany

martin.lemburg@gmx.net
http://about.me/Martin0815


------- Original message -------

**Comment by Jaex** [comment]
Your link is not what we need I think.

I asked this in here: http://stackoverflow.com/questions/36520748/net-toolstripmenuitem-check-tick-not-visible-in-high-contrast-theme

**Comment by Jaex** [comment]
Made checked items font bold so it will be better than nothing:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/devenv_VQjdwnJ050.png)

**Comment by Jaex** [comment]
Now Microsoft fixed check mark issue in high contrast: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.6.2-4.7.2#accessibility-improvements-in-windows-forms-controls

> ToolStripMenuItem controls with their Checked property set to true now render the associated check mark in a contrasting system color. Previously the check mark color was not contrasting enough and not visible in High Contrast themes.

If you have .NET Framework 4.7.2 is installed then checked state should show up correctly with latest [ShareX dev build](https://getsharex.com/docs/dev-builds).
