### ISSUE TITLE
DropForm.cs [Design] can't open in VS2015

### ISSUE THREAD

**Issue by m4nd1cm4rk0** [ShareX/ShareX#1489]
It seems that problem is with the designer code in DropForm.cs

**Comment by Jaex** [comment]
DropForm.cs don't have designer.cs therefore can't open in designer.

**Comment by m4nd1cm4rk0** [comment]
So this is not an error?
![drp](https://cloud.githubusercontent.com/assets/13752427/14384864/a98d5f6e-fd9d-11e5-8f72-f4bf432eec0c.png)

**Comment by Jaex** [comment]
No.

**Comment by m4nd1cm4rk0** [comment]
Ok, thanks.
Btw nice app
