### ISSUE TITLE
Gif preview hangs main thread

### ISSUE THREAD

**Issue by TheBoJaN** [ShareX/ShareX#1490]
I just recorded a gif of the CRS-8 landing(Woo!) and when I select it the preview in the right pane causes the form to lock up as it loads each frame

**Comment by Jaex** [comment]
I suspect it is caused by ShareX because .NET picture box handling rendering it. Can you upload it for me to test it?

**Comment by TheBoJaN** [comment]
Sure thing, here it is:
https://lh3.googleusercontent.com/-UBafdQvWSVI/Vwgeod87mdI/AAAAAAAATGg/IowI-gc6QA4/s0/2016-04-08_15-10-13.gif

**Comment by Jaex** [comment]
I uploaded it and preview not caused ShareX to freeze.

**Comment by TheBoJaN** [comment]
Strange... I've tried re-uploading that same version thinking google modified the original gif in some way but it did the same thing. I also tried turning off my antivirus and that didn't make a difference. I'll reboot in an hour or so and see if my computer's just being a baby.

Here's a video of what I'm talking about anyway: https://dl.dropboxusercontent.com/u/5088470/ShareX/2016/04/2016-04-08_16-02-32.mp4

**Comment by Jaex** [comment]
I was even made it async: ` pbPreview.LoadImageFromFileAsync(uim.SelectedItem.Info.FilePath);`

So not sure why it happens to you.

**Comment by TheBoJaN** [comment]
I just encapsulated the MyPictureBox.LoadImageAsync code in a new thread and it works smoothly. As far as I know, async doesn't actually spawn a new thread so the main thread ends up waiting for GDI+ to  yield before rendering a frame itself and yielding to GDI+ again(async is relatively new and I don't know much about it, so I could be wrong)

Perhaps you could write a handler for loading images in a background thread. I'm not sure why I'm seeing this issue and you aren't though, perhaps Windows 10's leaky runtimebroker.exe has degraded my system performance to the point I'm able to notice this behavior.

**Comment by TheBoJaN** [comment]
I went ahead and forked the repo and wrote a handler myself. It should benefit folks with less than modern processors(or those encountering the dreaded Windows 10 runtimebroker.exe bug)
