### ISSUE TITLE
System.ArgumentException: Illegal characters in path. Recurring Issue

### ISSUE THREAD

**Issue by yerboi** [ShareX/ShareX#1492]
[ShareX-Log-2016-04.txt](https://github.com/ShareX/ShareX/files/211406/ShareX-Log-2016-04.txt)

This issue has been coming up recently. No matter how many times I completely wipe ShareX from my sytem, and then reinstall the program I still get this problem. This problem will come up after a day or two of use, progressively getting worst (ex. hotkeys not working, not being able to upload files, and then lastly not being able to open the program) over the days this error comes up. The only thing I have added to my ShareX client is adding a custom image uploader. 
[upload code.txt](https://github.com/ShareX/ShareX/files/211410/upload.code.txt)
This is used by [thousands of people](http://blog.catbox.moe/post/142164186715/march-2016-statistics), and I do not see the problem rising up with anybody else. Thank you in advance.

**Comment by Jaex** [comment]
Don't use old ShareX version then...
