### ISSUE TITLE
Window Title subfolder

### ISSUE THREAD

**Issue by kkaracho** [ShareX/ShareX#1493]
Is it possible to Name subfolders via active window capture so they are the same name?
Im doing a lot of game screenshots and having the Screenshots placed in the corresponding folders would be really nice
greenshot can do this, which i used until i found sharex

sharex looks great and has a lot of neat features which i really like (uploading etc)

and would it be possible for the "watch folder" option to add something like an image size exclusion?
i added a folder but it has thumbnails inside which i would like to not upload since it doesnt make sense

**Comment by Jaex** [comment]
#228
