### ISSUE TITLE
Cannot paste image in IBM Sametime

### ISSUE THREAD

**Issue by Mooz80** [ShareX/ShareX#1494]
I'm exploring ShareX product to see if I could use it at work and recommend it to friends, everything works perfectly except the combination of ShareX and IBM Sametime chat. 

Whatever the image format selected (gif, png, jpg, bmp) and output to Clipboard, it's impossible to paste the image into the IBM Sametime chat window. I have tried several other products and they all allow to paste into the chat window, but not ShareX. 

Any idea of how to fix this because I have to do this several times a day? 

Here is the version of IBM Notes we're using: 
IBM Notes 9 
Social Edition
Edition 9.0.1

**Comment by Jaex** [comment]
What is your after capture tasks? Because one person was reporting he couldn't copy image too but he was trying to paste image file and not image itself.

**Comment by Mooz80** [comment]
Only "Copy Image to Clipboard" is checked.

**Comment by Jaex** [comment]
So you can paste image to other places like Paint but only not works in this IBM thing?

**Comment by Mooz80** [comment]
Exactly. I'm not a fan of IBM Sametime, but we are forced to use this at work... 
I guess I'll just use another tool than ShareX. I love it and continue to use it at home, but will find something else for work. No worries.

**Comment by Jaex** [comment]
Try swapping this value:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/ShareX_8X1bVuXjZt.png)

**Comment by Mooz80** [comment]
Hey, it's working! Can this affect other behaviors of the applicatior?

**Comment by Jaex** [comment]
It depends on destination you copying image to. Some applications support one format and not other etc.

**Comment by Mooz80** [comment]
Perfect, thanks!

**Comment by RusseBlanc** [comment]
Hi,

I have the same problem as described above but the link to the solution image is broken. :/
Could you give the solution again please?

Thanks!
