### ISSUE TITLE
vgy.me integration for video files

### ISSUE THREAD

**Issue by AbelToy** [ShareX/ShareX#1497]
While I can select vgy.me to upload images, I'd also like to be able to select it for file-uploads, so I can directly upload my video recordings there.

It only supports webm, though, so I'm not entirely sure how it should work. Maybe ShareX could add a separate destination specifically for video uploads?

**Comment by Jaex** [comment]
There is reasons why I didn't add video destination. So many complications it can have and don't wanna re write all that reasons again. Currently I move such destinations to file that way both image and video can be uploaded.

**Comment by Jaex** [comment]
Like this video can be uploaded to vgy.me: https://i.vgy.me/uGlbGr.mp4
