### ISSUE TITLE
Showing pressed keys on screen while recording

### ISSUE THREAD

**Issue by devkhan** [ShareX/ShareX#1499]
Is it possible to show what keys are being pressed while recording screen?

Something like this:

![image](https://cloud.githubusercontent.com/assets/8049092/14518433/72cbf85e-0235-11e6-8b55-951c0cfd1ba0.png)

Forgive me if its stupid as I really don't know the scope of this project, but I thought that this project provides so many features, it may also be possible to do this.

**Comment by Jaex** [comment]
Because all recording happens in FFmpeg, ShareX don't have any control on it other than start/stopping it, so I can't add keyboard preview or mouse click animations.

**Comment by devkhan** [comment]
But is it possible to capture the key presses and showing them on screen using some kind of additional functionality added to ShareX via a plugin or library?

**Comment by Jaex** [comment]
Showing them on screen is bad idea. User already knows what key pressed or where is clicked.

**Comment by devkhan** [comment]
But what if the screen is recorded for demo purposes (showing shortcuts, key combinations for certain actions)? 

There's an example usage in the image I posted.

**Comment by thejase** [comment]
@devkhan I agree with the need, but maybe there is an app that can show keys pressed that could run alongside this--likely for accessibility. I'll keep an eye out, as I need this as well.

**Comment by devkhan** [comment]
@thejase I found a tool for this: https://github.com/Code52/carnac.

**Comment by pratham2003** [comment]
@devkhan Carnac Thanks! Carnac is awesome to use with Sublime Text / Visual Studio Code when building a tutorial that involves text manipulation using multiple cursors! It even supports multiple monitors :D

**Comment by Leroy-X** [comment]
I  like this so much. need it +1

**Comment by Philosoph228** [comment]
@Jaex I think we can record actions and

**Comment by Philosoph228** [comment]
@Jaex I think we can record input actions and lay them after on video record.

**Comment by Leroy-X** [comment]
Maybe can make a separate tool, designed to display button, just like the two-dimensional code tool, it's cooooool

**Comment by AndroidDeveloperLB** [comment]
Why is this request closed?
It says it's impossible, but I've seen video capturing tools that do capture the mouse and the keyboard.
How come ?
Please add this feature. I think it can be great. Also wrote about this here:
https://github.com/ShareX/ShareX/issues/4490

**Comment by AndroidDeveloperLB** [comment]
Maybe there is a way to integrate and run this tool automatically:
https://github.com/bfritscher/carnac/releases/tag/v3-beta
?

**Comment by kamalhm** [comment]
anoher +1 for this feature request, would be helpful for demoing

**Comment by JulienHeijmans** [comment]
Another +1, would love to have that option.

**Comment by apobekiaris** [comment]
of course this is a must have strange how such a useful and mature tool like ShareX is missing it

**Comment by greggman** [comment]
@Jaex Thank you for ShareX!
@devkhan Thank you for the pointer to Carnac

They work great together!

![SJRh8qHjN7](https://user-images.githubusercontent.com/234804/85267132-caa04900-b4af-11ea-821f-921cb7f02f34.gif)

I'm sure all this is detailed at the Carnac site but 

1. the installer is silent (no indication anything happened)
2. running carnac says nothing it just starts working
3. click the carnac icon in the system tray for options

**Comment by AndroidDeveloperLB** [comment]
Wait, this is all working on the official release?

**Comment by greggman** [comment]
There are 2 separate pieces of software 

1. ShareX which captures the screen
2. Carnac which shows keyboard presses on the screen.

Use Carnac to get keyboard presses on the screen, Use ShareX to capture the screen. Works great!

**Comment by AndroidDeveloperLB** [comment]
@greggman  Oh ok.
I thought it got to be finally inside the ShareX app.
Carnac (and seems like a lot of other similar apps) has various issues, especially with non-English letters (Hebrew in my case).

**Comment by greggman** [comment]
> Carnac (and seems like a lot of other similar apps) has various issues, especially with non-English letters (Hebrew in my case).

That's disappointing. Looks like [you brought it up over there](https://github.com/Code52/carnac/issues/239). 

I'm sad it's not working for you. Still I'm happy it's separate software. It let's each project move forward easier as they don't have to coordinate. Hopefully someone will come out with a keyboard display that solves your issue.

**Comment by AndroidDeveloperLB** [comment]
@greggman 
I don't know .

I think that since it's very common to take screenshots and videos of the screen to explain how to do something, it's important to show not just the mouse, but what the keyboard does too.
That's why I was hoping for it inside of this app.

**Comment by Leroy-X** [comment]
Can we learn from [Capture](https://github.com/MathewSachin/Captura)?

**Comment by Franck-Dernoncourt** [comment]
Demo with [Captura](https://github.com/MathewSachin/Captura):

![ezgif-6-e3e096d73376 1](https://user-images.githubusercontent.com/15331/110072443-a4b38f80-7d32-11eb-8351-c9751be7b610.gif)


Hopefully, ShareX will one day add this feature!

**Comment by locvnhub** [comment]
> Showing them on screen is bad idea. User already knows what key pressed or where is clicked.

if you make a video tutorial, this feature is needed

**Comment by AndroidDeveloperLB** [comment]
@locvnhub Not only tutorials. I use it sometimes to report bugs, but without seeing that I pressed somewhere with the mouse or without seeing which keys are pressed, it has less understanding what's going on.

**Comment by prathamesh-gharat** [comment]
Yes, consider you are recording a bug in a tool/utility which is specifically related to hotkeys (keyboard shortcuts).

**Comment by Jaex** [comment]
You guys don't even understand what I wrote... User don't have to see key presses on their own screen, it must be inside recording only.

**Comment by Vampire** [comment]
That would imho be pretty bad.
I'd like to see what is recorded.
Because e. g. 1. you see what is obstructed by the overlay and 2. you are reminded that this is on and you for example shouldn't type passwords.

**Comment by AndroidDeveloperLB** [comment]
@Jaex @Vampire Personally I think both of your comments make sense and that maybe it's best to just have an option for this on the settings.

But sadly we are talking about a feature that isn't being added (it's closed).
Do you think it will be added?
Will it be re-considered?

**Comment by Jaex** [comment]
> Will it be re-considered?

What you mean re-consider? Literally 30 minutes later this topic opened I wrote that I'm unable to implement it. If I could I would have done it before this issue is opened. Because obviously I prefer ShareX to be feature rich and I think about all these feature ideas before people even suggest them.

But people always ignore my messages and then keep requesting it for years even I told in initial message that I can't add it.

**Comment by AndroidDeveloperLB** [comment]
@Jaex Sorry but I don't understand. 
I see this request as "closed", and yet you talk about adding it ? And now you say that for years you say that you won't add it...

Is there hope in seeing it being added to the app?
Either by the original author or others?
If so, why not re-open the request here? 

The feature can be customized after it's done being added. Both of your ideas seem logical to me. Some people might prefer it being shown while recording and some won't. Default behavior should be based on what most people use (after the feature can be customized to be able to choose which behavior to have).
The feature is about the final video. 

I personally prefer to have it being shows as you record, but only if it's not so intrusive and overlaps what the video focuses on.
For example, if you put your mouse on the regular place that shows what is being pressed, show it on the other side.

**Comment by Vampire** [comment]
> But people always ignore my messages and then keep requesting it for years even I told in initial message that I can't add it.

You say that you can't add it, as ffmpeg does the recording and you cannot influence that. But actually I'd say there are at least two ways. One would be to simply display the overlay on screen within the recording area, so that ffmpeg can also record them. The other would be to just remember during recording at which time indexes to display the overlays and then remux the produced video in a post-processing step, adding the overlay to the recorded video. Those two ways also be the two options mentioned here lately.

**Comment by AndroidDeveloperLB** [comment]
@Vampire Indeed. I thought that was the plan, no?

**Comment by Vampire** [comment]
Obviously there is no plan, as the developer of the program says he cannot fix it, actually meaning he either does not want to fix it or he had no idea how to fix it. I now shared how I as developer would naively spontaneously think about fixing this without knowing the sources and hope that it is enough to reopen the issue and implement the feature eventually.

**Comment by AndroidDeveloperLB** [comment]
@Vampire By "plan" I mean "plan of implementation if the idea ever comes", not that it's the plan of the developer/s.

**Comment by RieBi** [comment]
Yeah @Jaex we need the feature. By 'we' I mean the hivemind of all developers that ever commented on this issue.

**Comment by RieBi** [comment]
Me, obviously, included

**Comment by Akronae** [comment]
I agree this feature would be really helpful and in line with all the existing features that help documenting a process (arrows, text, number bullets)

**Comment by NabiKAZ** [comment]
> Because all recording happens in FFmpeg, ShareX don't have any control on it other than start/stop it, so I can't add key preview or mouse click animations.

That was a strange answer! Nobody expects ffmpeg to show those buttons and it is clear that it is only responsible for screen recording.
Just as now when capturing a screen, a toolbar appears on top of the screen for drawing on the screen etc. which is a side program, this can also happen in video recording mode and another program like "[carnac](https://github.com/Code52/carnac)" that the friends introduced above runs in the background (or something like this is designed internally) then is always on top. Then finally ffmpeg starts the screen recording.
This is a simple and possible scenario.

**Comment by QuAzI** [comment]
Still waiting for pressed keys hints and mouse clicks highlighting. Maybe the most required missing feature at the moment

**Comment by sunbear87** [comment]
Plus one for this feature.

I honestly can't even think of a case of using ShareX to share screen recordings where one WOULDN'T want to also share key-presses/mouse-clicks. What do people use this program for, if not sharing one's actions on screen? I would think sharing tutorials and guides would be the primary use case for ShareX.

Generally bizzare responses from the developer on this topic.
