### ISSUE TITLE
Greenshot editor doesn't display selection resolution during image cropping

### ISSUE THREAD

**Issue by Twilightssuperb** [ShareX/ShareX#1507]
When I try to select image region to crop it, I can't see current resolution. So I have to wonder whether the current selection coincides with the region that I need. It's inconvenient. 
![sharex_2016-04-19_13-36-39](https://cloud.githubusercontent.com/assets/7080928/14647091/caddf762-0664-11e6-8c1a-d7b6b81bad7a.png)

**Comment by Jaex** [comment]
Is Greenshot software have this feature?
