### ISSUE TITLE
Request: choose destination from context menu upload

### ISSUE THREAD

**Issue by Efreak** [ShareX/ShareX#1508]
When I click a file on the desktop, I'd like to be able to choose the destination on certain filetypes. For example, if I right-click and upload an html file, sometimes I want it to be sent to the file destination (dropbox), but sometimes I want it sent to the text destination (github gist). Same thing with text files and even with images, occasionally. I can think of two fairly simple ways to do this - 1. add a second context menu entry to certain filetypes, or 2. put a selection box or multiple buttons on the upload confirmation dialog box.

The reasoning behind this is that sometimes I'm uploading text files for sharing with others and sometimes I'm uploading them for personal reasons, to have them automatically synced to another computer.

**Comment by Jaex** [comment]
I'm not planning to add destinations menu to shell context menu because I'm using registry to add context menu entries this will be complicated.

**Comment by Efreak** [comment]
An alternative way of doing this, as mentioned above, is to simply show the dialog box shown when uploading from the clipboard.

**Comment by Jaex** [comment]
There is already 3 different dialog option to show before upload which can allow selection of destination, what you mean?

**Comment by Efreak** [comment]
I'm not sure what you mean. When I right click a file to upload it, I don't get *any* options, it uploads automatically based on the predefined settings in the program. I'm asking for a way to choose *when I upload* whether I want it uploaded to the filehosting setting or the image/text/other hosting setting.

**Comment by Jaex** [comment]
Show quick task menu, Show after capture window, Show before upload window. All can allow you to change destination before upload.
