### ISSUE TITLE
Drag-and-drop from ShareX to Windows Explorer

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1510]
Hi,

Would it be possible to create a drag-and-drop feature from ShareX to Windows Explorer? To move the files? Now I always have to right click, then click to copy the file, and only then can I paste.

Like this:

![sharex_2016-04-21_16-16-37](https://cloud.githubusercontent.com/assets/18115558/14712235/993a0fb0-07dc-11e6-9b55-8f7446a53c37.png)

**Comment by Jaex** [comment]
#1023
