### ISSUE TITLE
Assign short-cut to task on file in ShareX

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1512]
Hi,

I want to select a file in ShareX and press a shortcut (CTRL+C) to do a task, for example:
- copy the file
- copy the file path

Like this:

![sharex_2016-04-21_16-33-18](https://cloud.githubusercontent.com/assets/18115558/14712841/1079d1a8-07df-11e6-81ab-c429a497e78a.png)

**Comment by Jaex** [comment]
ctrl + c copies URL.

**Comment by Jaex** [comment]
Adding tips to main window now so people can see all hidden stuffs:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/ShareX.vshost_spyM5Qhu0u.png)
