### ISSUE TITLE
How to resize selection area?

### ISSUE THREAD

**Issue by eugenesvk** [ShareX/ShareX#1514]
I've just installed ShareX 10.9.1 on Windows 10 x64 and am completely puzzled by lack of the core feature I see on the website's intro video (and, ironically, the reason I installed ShareX instead of Greenshot) — those little squares on the sides and in the corner of the screen capture area that allow you to adjust the size of the selection area after you've made the initial selection with a mouse. Instead, right after I release left mouse button the screenshots just gets taken with no option to adjust the screenshot area.

I've sifted through all the options, but can find nothing of the sorts and search does't help much.
How do I enable this feature? Thank you

**Comment by Jaex** [comment]
Press `Q` in region capture.

**Comment by eugenesvk** [comment]
Thank you!!!
Would you kindly rename this option to something that has **edit capture area size**?

**Comment by Jaex** [comment]
And then few days later someone asks would you rename it to something that has "edit multi region mode".

**Comment by eugenesvk** [comment]
Nope they won't because of **in addition to multi region**

**Comment by Jaex** [comment]
I can't make help tip very wide because of one tip.

**Comment by eugenesvk** [comment]
You don't need to. Here are two pretty obvious options

1. It will fit as is
a) The is enough extra width as is (compare with extra text for the Ctrl+Mousewheel)
magnifier pixel size___ (`_` are for padding to the right border)
/ edit capture area size
/ adjustable capture area (this might need 1-2 extra symbols, no big deal or see below)
b) Remove `Activate` and there — extra 8 symbols

2. Make it two lines

**Comment by mindaugasw** [comment]
You need to enable it in settings: Task settings > Capture > Region Capture > Use multi region mode...

Adding it here, as this is first Google result and first comment here isn't really useful, can't figure out when I should be pressing that Q, nothing happens with it.
> Press `Q` in region capture.
