### ISSUE TITLE
Google Drive Direct Link

### ISSUE THREAD

**Issue by edgarasf123** [ShareX/ShareX#1522]
It is possible to generate direct URL from response.
https://developers.google.com/drive/v2/reference/files#resource-representations
`downloadUrl`
`embedLink`

And also, as a last resort: http://www.labnol.org/internet/direct-links-for-google-drive/28356/
I'm pretty sure the response does include the file ID .

**Comment by Jaex** [comment]
`downloadUrl` is not even opens downloadable url.
`embedLink` not exists in response.

If there was direct link in response I would have added it obviously.

**Comment by Jaex** [comment]
#520

**Comment by edgarasf123** [comment]
It might not be in response, but you can make one just by grabbing the id(which I'm pretty sure it is included in response) and combining with URL. I also found a better way of making direct links, which doesn't make the clients automatically download files, or make an alert that the file is too large for virus scans.

https://googledrive.com/host/FILE_ID (You should also follow the redirect to get url with key)

To make it available without signing in, the permissions should be set to.
![Anyone on the internet can find and view](http://i.imgur.com/kjBxB83.png)

There, I made a video experimenting with google drive direct links.
https://77e4c0eb7eaa4d8e82fdcca1fb32aea779b7b635.googledrive.com/host/0B11uwRQw_I-kekRWZDktelNFTWM

Btw, the key appended to URL is static according to [google employee](https://productforums.google.com/forum/#!topic/drive/MNPk7x4nFcA).

I really want this feature added to ShareX, dropbox blocks all my public links because too many requests...

**Comment by Jaex** [comment]
ShareX creates this permission `Anyone with the link Can view` and with that permission host links not accessible without log in.

**Comment by edgarasf123** [comment]
I know, you must upload a file with permission "Anyone on the internet can [b]find[/b] and view". Regardless, I just noticed Google is [discontinuing ](http://googleappsdeveloper.blogspot.com/2015/08/deprecating-web-hosting-support-in.html) the feature on August 31 :(.

**Comment by Jaex** [comment]
I guess this is why I didn't add it. I remember talking about host links in IRC and didn't remember why I didn't add it.
