### ISSUE TITLE
Unable to use ShareX

### ISSUE THREAD

**Issue by geevizzz** [ShareX/ShareX#1523]
Get following error and unable to access settings or any ShareX functionality to view/update.  Also have tried uninstall and install multiple times:

System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Net.WebProxy.CreateProxyUri(String address)
   at ShareX.HelpersLib.ProxyInfo.GetWebProxy()
   at ShareX.TaskHelpers.CheckUpdate()
   at ShareX.MainForm.CheckUpdate()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading._TimerCallback.PerformTimerCallback(Object state)

ShareX 10.9.1 Release

**Comment by Jaex** [comment]
Your Windows gives default proxy to ShareX and this proxy hostname is invalid. Check IE proxy settings .NET framework using that by default.

**Comment by geevizzz** [comment]
Thank you for quick response.  Are you suggesting going to IE > Local Area Network (LAN) Settings?

Checked there and "Automatically detect settings" was enabled.   No .NET settings.  I guess I'm not following your instructions correctly.

**Comment by Jaex** [comment]
Windows using IE proxy settings for internet related stuffs including .NET framework. It is like default Windows proxy settings not specific to IE.

**Comment by geevizzz** [comment]
Don't see any Windows proxy settings in "Control Panel".
When I search for "Default windows proxy settings" on internet, all results point to IE > Settings > LAN.

**Comment by Jaex** [comment]
I told Windows don't have proxy settings...

**Comment by geevizzz** [comment]
Are you suggesting going back to ShareX and changing Application Settings > Proxy?  Then I can't get to that screen.  ShareX crashes when I click on "Continue" or "Quit" button

**Comment by Jaex** [comment]
I told "Check IE proxy settings".
But still I must fix that even if hostname is invalid still it should not give error.

**Comment by geevizzz** [comment]
Thanks for the updates in the last day.  Should I download a new version of ShareX for this issue?  

OR uninstall ShareX currently installed on my machine, but when reinstalled I still get the proxy error and can not make any changes to ShareX settings and wonder if I have to delete some windows registry residuals after uninstall.

**Comment by aniljadhavmca** [comment]
I was also getting the same error. And also found the solution for this issue!

Please refer following steps:
- Right click on sharX icon
- Click on Application settings menu - http://goo.gl/6ZOiE1
- Now click on proxy settings - http://goo.gl/ISmie7
- And select automatic proxy configuration
