### ISSUE TITLE
Toast Notification won't show preview

### ISSUE THREAD

**Issue by Nikoskio2** [ShareX/ShareX#1530]
Just did a clean install on a new OS, toast notifications [don't have previews.](http://i.imgur.com/1lqeOed.png)

[The option is enabled.](http://i.imgur.com/498FoDe.png)

**Comment by Jaex** [comment]
`After capture tasks -> Save image to file` required for image to show.

**Comment by makedir** [comment]
There is no reason for this, please change it. Use the source from copied to clipboard too. I dont want save to file, but want a preview still to show up.

**Comment by Jaex** [comment]
Next version won't require saving to file to show preview.

**Comment by n3rdc0r3** [comment]
I just ran into the exact same issue. Looks like this never got fixed?

- Task settings > General > After task is completed: Show toast notification with preview
- Task settings > Advanced > ToastWindowDuration 3
- Task settings > Advanced > ToastWindowFadeDuration 0
- Task settings > Advanced > ToastWindowPlacement TopCenter
- Task settings > Advanced > ToastWindowClickAction Open folder
- Task settings > Advanced > ToastWindowRightClickAction Annotate image
- Task settings > Advanced > ToastWindowMiddleClickAction Close notification
- After capture tasks > Copy image to clipboard (everything else like Save image to file etc. is disabled)

Is there any chance that you could reopen this issue and look into this? Thanks!
