### ISSUE TITLE
Pause shortcut for screen recording

### ISSUE THREAD

**Issue by BeeVee23** [ShareX/ShareX#1531]
Recording a window or screen is great, however you can always see the mouse go to the stop button at the bottom of the recording. It would be great if there was a keyboard shortcut to pause recording so you can hit Stop without it being obvious in the recording (or for that matter to stop the recording :)).

B

**Comment by Jaex** [comment]
Start hotkey is also stop hotkey.

**Comment by BeeVee23** [comment]
Nice!

B

On 2 May 2016 at 10:20, Jaex <notifications@github.com> wrote:

> Closed #1531 <https://github.com/ShareX/ShareX/issues/1531>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShareX/ShareX/issues/1531#event-647238698>
>



-- 
Ben Vost
Skype: BeeVee_at_work
FR Mobile/Cell/Portable: +33 678 145 745
UK Mobile/Cell/Portable: +44 775 818 3675
PGP Public key on request
