### ISSUE TITLE
Split file uploaders into video uploaders & file uploaders

### ISSUE THREAD

**Issue by oxysoft** [ShareX/ShareX#1538]
Gfycat is listed under file uploaders which is really stupid if you want to both record videos and have them upload to gfycat and also upload files to other hosts at the same time

**Comment by Jaex** [comment]
What about image uploaders which supports animated gif?

**Comment by oxysoft** [comment]
what do you mean?

**Comment by Jaex** [comment]
Also hosts which supports image and video.

**Comment by oxysoft** [comment]
I see, then shouldn't everything be separated by a layer where each hosts can describe their capabilities and the user can specify which hosts they want per extension/format rather than something abstract within the user interface?
