### ISSUE TITLE
problem for editing image on 10.9.1

### ISSUE THREAD

**Issue by titi51** [ShareX/ShareX#1544]
Hi, on the last version 10.9.1 when i take a screenshot and try to edit my screenshot, greenshot didn't open and i just have a white window in the taskbar, the problem isn't on 10.4.0

**Comment by Jaex** [comment]
I have no idea how window can be white in the taskbar.

**Comment by titi51** [comment]
it works well now.. i'll try to make a screenshot if i have this problem again

**Comment by pvarenik** [comment]
I have the same problem. Version: 10.9.1 and os: Windows 10.

**Comment by titi51** [comment]
i'm using windows 10 too

**Comment by titi51** [comment]
https://i1.someimage.com/7x6rafV.png
Here is a screen of the problem when i try to edit a screenshot with right clic + edit image. Sharex

**Comment by Jaex** [comment]
I didn't wrote Greenshot Image Editor therefore have no idea. But that problem never happened to me or anyone I know, so not sure why only happens to you.

**Comment by titi51** [comment]
It didn't happend only to me, pvarenik said he's got the same issue. Maybe it's not a big one, i'm ok with that.

**Comment by pvarenik** [comment]
I get some solution for this. Get Greenshot Image Editor dll there http://src.repairdll.org/greenshot.imageeditor.dll/en-download-29905.html (not an ad) and replace original dll in ShareX folder.
2 Jaex: may be you must update dll in your repo?

**Comment by pvarenik** [comment]
Version 11.0.1: bug doesn't reproduce.

**Comment by Jaex** [comment]
You mean it could be fixed.

**Comment by pvarenik** [comment]
May be. I doesn't find it in change log. In any case thank you.

**Comment by titi51** [comment]
Thank you @pvarenik i'll try it tomorrow and i'll say if i still have this problem. :)

**Comment by d-w-h** [comment]
Still had the issue on 11.0.1, Win 10. 

The solution from pvarenik solved it:

Get Greenshot Image Editor dll there http://src.repairdll.org/greenshot.imageeditor.dll/en-download-29905.html (not an ad) and replace original dll in ShareX folder.
