### ISSUE TITLE
Scrolling Capture + quick task menu or after capture window broken

### ISSUE THREAD

**Issue by Slind14** [ShareX/ShareX#1545]
Hey,

the completion (upload) button of the Scrolling Capture Task does not seem to work when "Quick task menu" or "after capture window" is selected as After capture task.

**Comment by Jaex** [comment]
I fixed it in here: 1ab59cee341a0f1f5540e985fccfcfd478ea28a2

**Comment by Slind14** [comment]
ahh, didn't find anything when searching the issues.
