### ISSUE TITLE
Windows 7 taskbar icon progress bar get's stuck.

### ISSUE THREAD

**Issue by madprops** [ShareX/ShareX#1549]
This might just be a problem with my system. But basically this is happening:

![discord_2016-05-11_17-51-25](https://cloud.githubusercontent.com/assets/206498/15200423/ebb3c35e-17a3-11e6-8a4c-ded3d428d42d.jpg)

After the upload of a file finishes the progress bar stays lit. It's happening in 10.9.1

**Comment by C99nl** [comment]
Try restarting explorer.exe and see if it's still green.
If the green disappeared, just try again and see if it stays green this time.

**Comment by madprops** [comment]
I did try that but didn't seem to work. But anyway after restarting my computer it works now. So I'm closing this.
