### ISSUE TITLE
[Suggestion]: GIF EDITOR features with ShareX

### ISSUE THREAD

**Issue by AnacondaPython** [ShareX/ShareX#1554]
so what I'd really love to see is ShareX have a built in GIF editor. Kind of like this- http://www.gifntext.com/, but built into it on the client side, before its send over to imgur/host. Nothing really fancy, just the ability to add text / text animations, to scrub out some things I don't want people to see, and highlight things. Falls really well in line with what ShareX is already doing

Example of an edited Gif I made (after using ShareX)
http://www.gifntext.com/78978-another-overlay-yay-overlay-on-top-of-it

Essentially, what happens is this.

1. HOTKEY (to start GIF capture)

2. Opens up dialog prompt with a GIF EDITOR, kind of like how you do it now with GREENSHOT editor for images

3. Allows you to add simple brush strokes, images, and text animations 

4. Submit, send to IMGUR , get URL link back

Literally, this would totally outplace techsmiths snagit with just this feature alone, and make OBS software obsolete for 10-15second GIF broadcasts

Perhaps you could find a offline GIF editor to work with this as you do with GREENSHOT IMAGE EDITOR?

I wouldn't mind contributing here, but I do not know where to really begin or what resources I'd need to contribute on github / build this out though. Perhaps some advice? On that same note, I don't know how to use C# either (ShareX is written in C# if i recall correctly)

**Comment by Jaex** [comment]
I'm not planning to make GIF editor, it will be massive effort to make.

**Comment by AnacondaPython** [comment]
Okay, was just wandering, thanks for the quick update

**Comment by Scrxtchy** [comment]
If you're looking to overlay a single image over every frame, instead if a fully fledged animator, it will be far easier to export a transparent image and overlay it using ffmpeg

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/wiki/FFmpeg%20options#adding-watermark-image

**Comment by ze-better** [comment]
This would've been a fantastic enhancement, too bad it's out of scope
