### ISSUE TITLE
Video: No audio

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1557]
When I record a video, there is no audio. How to enable audio?

**Comment by Spidersouris** [comment]
In the Screen recording options, select "virtual-audio-capturer" in the Audio source dropdown menu. Also, make sure to select an audio codec.

**Comment by YasseenDeHerdt** [comment]
Can you show this in a screen shot? I can't find recording options..

**Comment by Spidersouris** [comment]
[Here you go](https://gfycat.com/JitteryUnsightlyAngora)

**Comment by YasseenDeHerdt** [comment]
Thanks, however this solution doesn't work. I have only 2 options and none of them produce sound. How to fix it?

![sharex_2016-05-15_19-37-10](https://cloud.githubusercontent.com/assets/18115558/15275757/7637a6c0-1ad4-11e6-82c5-77bdd4115225.png)

**Comment by YasseenDeHerdt** [comment]
Allright, I click on Install recorder devices and installed from there, this created the option virtual-audio-capturer in audio source and now it works.

Thanks.
