### ISSUE TITLE
capture custom region take no effect

### ISSUE THREAD

**Issue by helloyan** [ShareX/ShareX#1561]
I set ctrl+alt+a for free capture,and the status cube is green, but it can't take effect, even if i invoke it from workflow.

another bug:
The history log always show  my first capture when i start it.

**Comment by Jaex** [comment]
What is free capture? Also you telling custom region capture. So which one.

**Comment by helloyan** [comment]
custom region capture ,sorry

**Comment by Jaex** [comment]
This is how you select region for custom capture:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/ShareX_xODD3lKMqt.jpg)

But I improved it in last version so you can drag region to easily assign area.

**Comment by helloyan** [comment]
i downlad ShareX 10.9.1, and i can't drag region

**Comment by Jaex** [comment]
I meant beta which you can find in IRC channel topic.
