### ISSUE TITLE
'After capture tasks' / 'Upload to image host' is checked by default after installation

### ISSUE THREAD

**Issue by int512** [ShareX/ShareX#1563]
I really don't believe it is good idea to have such feature ON by default without user notification. It can compromise privacy and security.

**Comment by Jaex** [comment]
It have notification, shows this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/ShareX_bU9k4e8gGc.jpg)

**Comment by 1Jesper1** [comment]
Why is this on by default?
