### ISSUE TITLE
When ShareX capture activated, characters in WebEx session are mapped incorrectly

### ISSUE THREAD

**Issue by lynchpatrickj** [ShareX/ShareX#1565]
This is a strange issue, that I've noticed over the last few versions. I see this on Windows 7. To reproduce:

- [ ] Create a capture or recording hotkey. 
- [ ] Start a WebEx session, and request control from a remote PC.
- [ ] When control is granted and accepted, type within the WebEx session, to validate text is as expected.
- [ ] Activate hotkey.
- [ ] Type some letters and numbers - num-lock and caps-lock may be reversed, and some keys may be mapped differently. Left mouse key is also permanently depressed.

**Comment by Jaex** [comment]
ShareX can't change key mapping of another software.

**Comment by lynchpatrickj** [comment]
I took a video of this. Will send
