### ISSUE TITLE
Add the ability to create a hotkey to upload to a specific album in imgur

### ISSUE THREAD

**Issue by Evar678** [ShareX/ShareX#1569]
This would be quite interesting and I see a lot of use cases for it.

For my particular case; It would be useful to be able to use a separate hotkey than normal use to automatically add a capture to an album for logging expensive item drops in a game without interrupting normal ShareX use outside of that.

I'm not sure if this already exists; if it does then pardon me ^-^

**Comment by Jaex** [comment]
I'm not planning to have uploaders config per hotkey too. It is already using task settings per hotkey and slowing down setting saving/loading.
