### ISSUE TITLE
Screen Recorder Format

### ISSUE THREAD

**Issue by padukakerol** [ShareX/ShareX#1570]
**I did a screen recording(mp4) but it was shown as a gif format in Telegram Desktop.**

![2016-05-23_16-33-33](https://cloud.githubusercontent.com/assets/15681858/15465283/69fa8a34-2106-11e6-94ac-08e269f482cf.png)

![2016-05-23_16-50-20](https://cloud.githubusercontent.com/assets/15681858/15465307/8248da82-2106-11e6-8152-25eaa0dcb5dc.png)

![2016-05-23_16-50-26](https://cloud.githubusercontent.com/assets/15681858/15465315/861ae8e4-2106-11e6-87f7-4dc83e6fa80e.png)

**Comment by Jaex** [comment]
Telegram must have automatically converting it to gif I guess.

**Comment by padukakerol** [comment]
Sorry sir. I somehow manage to solved it. i don't think that Telegram automatically converted the mp4 video to gif. What I did is changed the video and audio source to (I forgot) and then restart ShareX. Then I did the screen recorder and the video was posted in Telegram in mp4 format.
