### ISSUE TITLE
Info request: method used to determine user locale on first run?

### ISSUE THREAD

**Issue by TheRealMarnes** [ShareX/ShareX#1571]
Hi

This is more of a request for information than it is a bug report (or is it?)

I have a fresh windows 10 that came preinstalled in dutch, which I changed to english in all the right ways. All the programs I have - except the nvidia driver installer and sharex - recognize english as my language; the other 2 still default to dutch. I'd like to know why.

As you'd expect, nvidia's support is all but helpful, being phobic of actually contacting their developers and such to get a proper answer to the question "what is the (apparently faulty) method used by the installer to detect my locale?".

Could the sharex folks please summarize the process? Is the locale determined by reading a certain registry key or something?

Thanks for any info

**Comment by Jaex** [comment]
Check here: https://github.com/ShareX/ShareX/blob/master/ShareX/LanguageHelper.cs

            if (language == SupportedLanguage.Automatic)
            {
                currentCulture = CultureInfo.InstalledUICulture;
            }

**Comment by TheRealMarnes** [comment]
Thanks
