### ISSUE TITLE
Copy selection to clipboard and then upload it

### ISSUE THREAD

**Issue by CalibeR50** [ShareX/ShareX#1573]
Hi, it would be cool to be able to upload the current selection directly without having it to copy to the clipboard first (-> first invoke windows copy, then upload clipboard)

**Comment by Jaex** [comment]
What you mean invoke windows copy? Sending Ctrl + C to application?

**Comment by CalibeR50** [comment]
Yes, if I want to share code (or text), it would be cool to just select the text and directly upload it with only one hotkey, without having to copy it (manually) to the clipboard first and then invoke the hotkey to upload the clipboard.

**Comment by Jaex** [comment]
It is bad idea to expect every software to react to ctrl + c hotkey to copy selection therefore i'm not gonna implement it.

**Comment by CalibeR50** [comment]
Well, I don't know any (text / code) program which doesn't. This would even work for file uploads as windows will listen to the ctrl + c, too.
