### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by XeonG** [ShareX/ShareX#1575]
Default view... please add filesize column/datetime created... and allowing sorting.. would be good.
----
For gif/vid screen recording it would be much more useful if there was a way to move the capture area around.. much like other screenrecorders: bandicam etc

Or option for it follow mouse position upto screen border edges.
Show mouse/keyboard input directly in an overlay in one of the capture corners?

actually it would be useful to have something like that for all the capture modes, to able to resize and move the capture area.
----

Make preview work for .mp4

SFTP over SSH support?

Greenshot Image Editor...
Selection tool that did marquee selections.. allowed you to cut/copy those selections..
paste in other cut/copied selections from other images

**Comment by Jaex** [comment]
* Progress column already shows file size.
* Don't have space to add datetime, but you can check history window for it.
* I wrote reason many times before why I can't add drag able recording area or input overlay for it.
* Region capture already allows moving, resizing even multiple region selection if you disable "Quick crop" option
* I don't want to embed Windows media player to preview section and by default it don't even supports most of encoders
* ShareX already have SFTP support...
* I'm not developer of [Greenshot](http://getgreenshot.org/) image editor

**Comment by XeonG** [comment]
Progress column already shows file size.. not much good if you just recorded/captured something and didn't upload it... then is nothing

**Comment by XeonG** [comment]
ShareX already have SFTP support... oops didnt' see the protocol option

"I wrote reason many times before why I can't add drag able recording area or input overlay for it"

I have not seen that.. can you put it on the frontpage as FAQ?
