### ISSUE TITLE
ShareX not uploading screen recording to dropbox

### ISSUE THREAD

**Issue by navi198** [ShareX/ShareX#1576]
When I use the screen recording feature it doesn't do anything when it finishes, but when I do the dropbox upload test it works fine.

**Comment by Jaex** [comment]
It works for me: https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/NxECviOLAR.mp4
Something must be wrong in your end. Like ShareX configuration.

**Comment by navi198** [comment]
What would I do to fix it? The ShareX logo on my taskbar changes for a second then goes back to the logo without uploading it.
