### ISSUE TITLE
[Suggestion] audio clip uploading

### ISSUE THREAD

**Issue by SoundGoddess** [ShareX/ShareX#1582]
Just found out about ShareX and I'm loving it, especially now that I can submit to FTP. :)

It would be great to be able to share audio clips to Clyp.it or SoundCloud.

Dunno if anyone is working on this or not, but since I'm doing c# development now I can probably figure out how to add this feature and submit a PR.

**Comment by SoundGoddess** [comment]
I spent all day working on this, if anyone can help me get it working, I'd appreciate it.  

My changes are committed to this repo: https://github.com/SoundGoddess/ShareX

Here is where I'm at with the GUI:
http://metasmug.com/i/2016-05-26_17-51-16.mp4

Although it allows me to select Clyp from the menu, it seems that it still is uploading to the generic file transfer settings instead of to the audio settings.

I don't fully understand where everything is to complete this update but it would be great if audio clips were supported.  I don't mind doing the work, but there doesn't seem to be a lot of comments or documentation.  If someone who is really familiar with the code can help me finish this up, it would be greatly appreciated <3

**Comment by Jaex** [comment]
There is reasons why I didn't add video destinations menu. It is not that simple as making new category.

**Comment by SoundGoddess** [comment]
Alright, well I gave it a shot.  I'm stuck at this point, so I'm going to focus on something else for now.  If you do get around to looking at it let me know :)

**Comment by Jaex** [comment]
Added clyp.it custom uploader here:
https://github.com/ShareX/CustomUploaders/blob/master/clyp.it.json
