### ISSUE TITLE
Ftp asking for username and password when sharing link ?

### ISSUE THREAD

**Issue by NocturnalVioletRainbow** [ShareX/ShareX#1583]
I don't know if anyone is experiencing this, But I'm having a hard time getting the screen shots shared from my ftp my site to my friends, this is all being hosted ftp it will cap it and upload it but it will not of course allow them to see it unless they are using a username and password. any suggestions or help that could be offered ?

**Comment by Jaex** [comment]
It is nothing to do with ShareX. It is your server.
