### ISSUE TITLE
Add support for SLiMG

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#1584]
SLiMG is a competing service to Imgur which has pivoted from being a image hosting service to photo based social platform. SLiMG has just launched their public API in stable release and it would be nice to have an alternative to Imgur. 

[API Page](https://sli.mg/public/api)

**Comment by Jaex** [comment]
I implemented it now but Imgur was 5x faster than SLiMG one of the reason is need to do alot of requests after upload to wait for them to queue and process image and give url. So in this status it can't be alternative to Imgur.

**Comment by Sushubh** [comment]
I understand. And thank you! 

Imgur is of course massive and a much mature service with a proper development team. SLiMG is increasingly being used by even reddit (and voat) users because of censorship related issues on Imgur. Which is why I wanted to get it as an option on ShareX!

**Comment by Jaex** [comment]
`2016-05-28 11:58:59.136 - Task completed. Filename: ShareX.vshost_s4URZPQwix.png, URL: https://i.sli.mg/BKxzXO.png, Duration: 6117 ms`

As you can see this small image took 6 seconds to upload.

`2016-05-28 11:59:39.250 - Task completed. Filename: ShareX.vshost_pFCy2lej6U.png, URL: http://i.imgur.com/hzsB6H1.png, Duration: 1667 ms`

But same image 1.6 second in Imgur.

**Comment by Sushubh** [comment]
Yes I understand. Even the web ui is quite slow compared to Imgur. Which is why I was hoping to use it through ShareX where I can generate BBCODE for multiple images easily. SLiMG does not offer unified BBCODE for multiple images through the Web UI right now. Hopefully it gets better with time. Thanks for considering this.

**Comment by Sushubh** [comment]
Hello

Got the update today. Saw Slimg listed in changelog. But I could not locate it in the destinations. 
Lithiio is also new I assume. It's available so I assume I am on the latest update? 

Screenshot: http://i.imgur.com/mL5nX1T.png

Thanks!

**Comment by Jaex** [comment]
I didn't add account support yet. You can only do anonymous upload for now. Because upload was very slow I didn't thought it would worth making that effort to add oauth support. But later I talked with developer of sli.mg and he was did few improvements so it must be faster than before now but still was not fast enough.

**Comment by Sushubh** [comment]
Ah alright. Should be fine for my purpose! Lithiio also looks useful. Thanks!

**Comment by xzyxzy** [comment]
Endless upload - gets stuck at 99%

**Comment by Sushubh** [comment]
Looks like I should have never asked for support for slimg. The service seems to have killed all/most of their older images. I would be cleaning this mess for a long time on my board. I am now suggesting that you should consider removing it and blacklisting it for good. 😢
