### ISSUE TITLE
vgy.me getting forbidden while uploading files

### ISSUE THREAD

**Issue by yawalkar** [ShareX/ShareX#1585]
I'm getting the following message while trying to upload images to vgy.me

<img src="https://vgy.me/USN914.png">

**Comment by TechKat** [comment]
Hi yawalkar,

I think the problem here is, CloudFlare.

They, for some reason, decided to automatically add India to my firewall to force a "challenge" on your country. I have checked this and removed the entry but I can't guarantee they will put it back on.

Could you try again and let me know?

**Comment by yawalkar** [comment]
@TechKat 
Yes, its working now.

Thank you!
