### ISSUE TITLE
[Suggestion] Specific URLs for specific hotkeys

### ISSUE THREAD

**Issue by MySelfLuls** [ShareX/ShareX#1587]
Hello,

So what I currently use is 
CTRL + SHIFT + 1 to create a .webm and upload it to my server. 
That would of course upload with the settings I use in the File Naming.

I was wondering if we could create our own specific file namings for different hotkeys. 
Hope you'll understand what I mean :)

**Comment by Jaex** [comment]
Each hotkey can have different task settings, which means yes you can do that.

**Comment by MySelfLuls** [comment]
I can't seem to understand how then, when I enter hotkeys, go into settings and under file naming everything is greyed out.
How would I enable it so I can actually edit it?

As shown in this image:
http://ss.myselfluls.xyz/TJzs2Meg5m.png

**Comment by Spidersouris** [comment]
!(https://gfycat.com/FocusedSlimEuropeanpolecat)

**Comment by Spidersouris** [comment]
![test](https://gfycat.com/FocusedSlimEuropeanpolecat)
