### ISSUE TITLE
Screen Recording %n and %pn do not work

### ISSUE THREAD

**Issue by sethdmoore** [ShareX/ShareX#1588]
Screen Recording (region) does not detect windows
Image Capture manages to correctly detect the windows.

Every relevant option is enabled.

[Link showing settings](https://gfycat.com/DistortedAridHart)

Version Info
ShareX 10.9.1

OS Info
Windows 10 Pro

**Comment by sethdmoore** [comment]
Same issue in 11.0.1

**Comment by Jaex** [comment]
It is not exactly issue, it was designed that way. And will require alot of change to accomplish it in screen recording :( Because need to pass those data to so many functions.

**Comment by jnerin** [comment]
I guess obvious as it's still open, happens in current 13.5.0.

But could maybe, at least as a temporary workaround, variables that can't be substituted be given the empty string value? At least we won't end up %pn, %t, %n or the likes in the file names.

**Comment by Jaex** [comment]
It is implemented in last release.
