### ISSUE TITLE
Does not work in Fullscreen Games

### ISSUE THREAD

**Issue by kkthebeast** [ShareX/ShareX#1589]
I downloaded this for taking Screen shots in games I develop Mods for. It only captures a black screen every time. Also makes the game flash black 2x as if you where resetting the graphics drivers.

**Comment by Jaex** [comment]
#848

**Comment by kkthebeast** [comment]
Not a solution for those of us running Crossfire or SLI. the game HAS to be fullscreen in order for both graphics cards to work

**Comment by corruptnova** [comment]
From what I understand, ShareX isn't going to support capture from games
unless someone wants to make a pull request and add the support. ShareX
wasn't really intended to capture games.
