### ISSUE TITLE
ShareX keeps double uploading

### ISSUE THREAD

**Issue by AnacondaPython** [ShareX/ShareX#1592]
I haven't had any problems using ShareX for like 1000+ images, but I'm running into a recent problem when I started running firefox (I use mostly chrome) for some reason

Everytime I upload an image (capture region settings), shareX would immediately upload another image right afterwards of my right monitor

http://i.imgur.com/h9RixeA.png

Basically, I am uploading 2 images (1 intended, 1 unintended) everytime I use shareX.

**Comment by Jaex** [comment]
Did you checked debug log? Maybe it can have any clue.

**Comment by AnacondaPython** [comment]
Where do I go to see that? also wow you reply really fast

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/ShareX_WQ3TjVzrPk.png)

**Comment by AnacondaPython** [comment]
Here it is jaex. I just blurred out some private things

http://i.imgur.com/sbtCjbE.png

Only maybe 1 of those images is something I actually intended to upload. Everything else was automated , it clipped half my right monitor every time

**Comment by Jaex** [comment]
Nobody reported double upload related issue before and I don't know how it can happen.

**Comment by AnacondaPython** [comment]
ah okay I think I set "auto capture" on. I was playing around with some settings earlier. http://i.imgur.com/OD55YpC.gif

Is there a documentation log I can read more about this? or how do I turn it on /off

**Comment by Jaex** [comment]
If auto capture running it will be in tray bar.

**Comment by AnacondaPython** [comment]
Okay got it. But I can't find any documentation or settings on "Auto-Capture" anywhere on shareX through the wiki. I just wanted to know there was any settings to modify how often auto-capture works and what triggers it uses

**Comment by Jaex** [comment]
How am I supposed to write documentation with my bad english.
