### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by seriouspike** [ShareX/ShareX#1595]
I used ShareX for couple of weeks and all was fine. Since last weekend, i get the following error when trying to upload captured images:
![1](https://cloud.githubusercontent.com/assets/19774282/15816955/2bd6a548-2bde-11e6-95db-5b416421e426.png)

Does anyone else encountered this? I didn't see any issues in Windows event log.

**Comment by Jaex** [comment]
That mainly happens when firewall block ShareX connection.

**Comment by seriouspike** [comment]
I allowed the app private and public access - didn't helped.

![2](https://cloud.githubusercontent.com/assets/19774282/15833696/8d360246-2c30-11e6-9dd4-fc9a791c2eb6.jpg)


I disabled the firewall - same results.

![1](https://cloud.githubusercontent.com/assets/19774282/15833720/a4825698-2c30-11e6-860f-85fcf525ac27.jpg)

Please advise.

**Comment by lithium720** [comment]
What uploader / host are you trying to use?

**Comment by seriouspike** [comment]
Imgur
I'm using the Windows version of ShareX

**Comment by lithium720** [comment]
Does it work with other uploaders?

**Comment by seriouspike** [comment]
yes, with video capture to dropbox all is fine.

**Comment by lithium720** [comment]
Do you use any anti viruses or anything like that? Recently install some software? If it was working fine for awhile something on your machine had to of changed. Because the imgurs api works fine.

**Comment by seriouspike** [comment]
no anti-virus.
I uninstalled the app and re-installed it - same results.
I checked my recently installed app's and didn't found anything new.

Any logs I can find for more info?

**Comment by seriouspike** [comment]
found the log file: http://pastebin.com/apG39yFf
what do you say?

**Comment by lithium720** [comment]
Can you open CMD and
ping api.imgur.com
?

**Comment by seriouspike** [comment]
imgur is blocked here for some reason, that's the cause for the problem.
I will investigate this, thanks!
