### ISSUE TITLE
Colors are getting compressed automatically

### ISSUE THREAD

**Issue by RonMelkhior** [ShareX/ShareX#1597]
Here's a screenshot I took of my site: http://i.imgur.com/cVF6dsd.png
And here's the site itself: http://argos.co.il/login/

The colors are getting compressed and for some reason there's no way to disable that.

**Comment by Jaex** [comment]
Both your screenshot and website looks exactly same color (used color picker to check) so color problem in your end.

**Comment by RonMelkhior** [comment]
@Jaex 
I have used a color picker as well, and the page background shows as 2 different colors.
1F404B - Screenshot
2B3E50 - Website

**Comment by eNNercY1337** [comment]
@Jaex its totally not the same, i can see the difference without the need of an color picker.

**Comment by Jaex** [comment]
@RonMelkhior I told it is in your end of course you will have 2 different colors.

@eNNercY1337 I checked every single color in both web site and image and color values was identical in color picker.

**Comment by Jaex** [comment]
Proof: https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/CROQnXGslF.mp4

**Comment by RonMelkhior** [comment]
@Jaex Then can you please note me on what could possibly cause it to be different?

**Comment by Jaex** [comment]
I believe browser was causing color to look different in other users. Can you try checking image in image viewer or another browser?

**Comment by RonMelkhior** [comment]
@Jaex The local image saved has the diff. color as well.

**Comment by Jaex** [comment]
Did you tried opening that image in both chrome and firefox, and checking is colors look same?

**Comment by RonMelkhior** [comment]
@Jaex Seems like both Chrome and the image viewer show the wrong colors but Internet Explorer shows the correct colors. Is there any way to fix this?

**Comment by Jaex** [comment]
These maybe? https://www.google.com.tr/search?q=windows+image+viewer+wrong+colors

**Comment by RonMelkhior** [comment]
@Jaex Yep, this fixes it for Windows but not for Chrome, I'll try to look up on that now, thank you for your help.
