### ISSUE TITLE
Dropbox Quality

### ISSUE THREAD

**Issue by navi198** [ShareX/ShareX#1600]
Sorry for making another post, but the quality is pretty bad when I upload it to Dropbox.
These are all using the same settings
gfycat: http://i.imgur.com/CwdxtVO.png
recording in sharex folder: http://i.imgur.com/RQmE2bx.jpg
dropbox: http://i.imgur.com/OmXgSYZ.jpg
video is also very choppy on dropbox =(

**Comment by Jaex** [comment]
Try direct option:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/ShareX_c8Wm3M6mt8.png)

**Comment by navi198** [comment]
Thanks, it worked!
