### ISSUE TITLE
[10.9.1] ffmpeg.7z download - unable to connect to server

### ISSUE THREAD

**Issue by Pr3casatDragon** [ShareX/ShareX#1602]
Whenever I try to download ffmpeg to start recording gifs, the dialog says "unable to connect to server" and I can't download the flie

Screenshot  http://i.pr3cast.pw/06.09.mn.jpg

**Comment by Jaex** [comment]
It downloads fine for me. That means download source have no problem but something in your PC must be blocking it. Can you try downloading it from browser to check:

http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z
http://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-latest-win32-static.7z

ShareX using one of these URL to download it.

**Comment by Pr3casatDragon** [comment]
Yeah, I unzipped it and placed it and gif screenshots work fine now.

**Comment by teenangst** [comment]
I'm having this issue and the links provided by @Jaex return 404

**Comment by Jaex** [comment]
@teenangst ![](https://jaex.getsharex.com/2018/03/ShareX_YVTk7l66ON.png)

**Comment by teenangst** [comment]
Mine was unchecked, checked it and no change 🤷‍♀️

**Comment by Jaex** [comment]
If update not showed up then you probably don't have .NET Framework 4.5 or higher installed.

**Comment by teenangst** [comment]
I do have it installed

**Comment by teenangst** [comment]
I just had a friend give me their ffmpeg.exe, the issue from where I am is that the download location http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z returns a 404 so ShareX obviously can't download it

**Comment by saikatm** [comment]
@teenangst Yah I am Having the same Issue! @Jaex please help.

**Comment by stuntguy3000** [comment]
@Jaex Looks like the URL has changed to a ZIP file.

**Comment by Jaex** [comment]
ShareX already using ZIP link.

**Comment by stuntguy3000** [comment]
@saikatm Are you running the latest version of ShareX?

**Comment by saikatm** [comment]
@stuntguy3000 I have fixed it by manually downloading and placing ffmpeg.exe to the Documents/Sharex/Tools Folder!

**Comment by saikatm** [comment]
Download it from https://ffmpeg.zeranoe.com/builds/ and copy "ffmpeg.exe" to "Documents\ShareX\Tools" folder. @Jaex @stuntguy3000
