### ISSUE TITLE
[11.0.0] Error after saving anything

### ISSUE THREAD

**Issue by Inclushe** [ShareX/ShareX#1603]
Getting this error after saving screenshots or gifs.

"Object reference not set to an instance of an object."
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadInfoParser.Parse(TaskInfo info, String pattern)
   at ShareX.TaskManager.task_TaskCompleted(WorkerTask task)
   at ShareX.WorkerTask.OnTaskCompleted()

ShareX 11.0 Release
```
It goes back to normal if you click "Continue".  
Running on Windows 10.

Log file: http://pastebin.com/hzb5P04n

**Comment by Jaex** [comment]
Were you using $uploadtime ?

**Comment by Inclushe** [comment]
I don't think I am. I haven't changed any task settings besides ScreenColorPickerFormat to $hex.
![image](https://cloud.githubusercontent.com/assets/7546357/15952618/78a94aa6-2e90-11e6-8531-9d48c7e363fe.png)

**Comment by Kontr3X** [comment]
I do have the same problem.

**Comment by Purlek** [comment]
I am also having this exact issue. It occurs only when doing one hotkey: copy image, save image. That's all it does, and I get that error. However, as OP said, it does actually work, it just gives that annoying popup.

**Comment by Jaex** [comment]
Indeed this error always happens when there is no upload in task. Because I always upload images, I didn't encountered this error when developing :(

I will release new minor build asap.

**Comment by Purlek** [comment]
Thanks very much! :+1:

**Comment by Jaex** [comment]
Released fix build.

**Comment by Inclushe** [comment]
Fixed on my end. Thanks!

**Comment by Purlek** [comment]
Also fixed for me. Thanks much. :) :+1:

**Comment by Zivelz** [comment]
thx!

**Comment by Wexnaoz** [comment]
Fixed for me. Thanks very much :+1:
