### ISSUE TITLE
ShareX 11.0 error

### ISSUE THREAD

**Issue by Wexnaoz** [ShareX/ShareX#1606]
When I press PrtSc/SysRq I got an error message

> 
> System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
>    em ShareX.UploadInfoParser.Parse(TaskInfo info, String pattern)
>    em ShareX.TaskManager.task_TaskCompleted(WorkerTask task)
>    em ShareX.WorkerTask.OnTaskCompleted()
> 
> ShareX 11.0 Release

ShareX log

> ShareX 11.0 Release
> 2016-06-09 23:36:20.932 - ApplicationConfig save started: C:\Users\Myuser\Documents\ShareX\ApplicationConfig.json
> 2016-06-09 23:36:20.934 - HotkeysConfig save started: C:\Users\Myuser\Documents\ShareX\HotkeysConfig.json
> 2016-06-09 23:36:20.950 - HotkeysConfig save successful: C:\Users\Myuser\Documents\ShareX\HotkeysConfig.json
> 2016-06-09 23:36:21.008 - ApplicationConfig save successful: C:\Users\Myuser\Documents\ShareX\ApplicationConfig.json
> 2016-06-09 23:36:30.181 - URL opened: https://github.com/ShareX/ShareX/issues
> 
![sharex 11 error](https://cloud.githubusercontent.com/assets/11588504/15952990/3e174922-2e9c-11e6-9d40-34b753c0b252.png)

**Comment by Jaex** [comment]
#1603 please update ShareX.
