### ISSUE TITLE
Option to save the last used tool in image editor

### ISSUE THREAD

**Issue by alpasy** [ShareX/ShareX#1609]
Hi! I'm a new fan of ShareX. The way i use it mostly is this: region capture -> image editor -> highlight something in the image (via 'Draw line' or 'Draw arrow' tool mostly) -> image upload to imgur. 

Everything works cool and fine, except the default tool is always 'Draw rectangle' and there is _no way_ to change that or arrange tools on the panel (i checked ShareX settings, image editor settings, even the .ini file with a lot of settings for the image editor in the ShareX directory). Image editor saves other user stuff like line colors, line thickness, font settings etc., but not the tool itself sadly. 

The last 11.0.1 update mentions "SaveSettingsAfterTaskCompleted" setting, which "saves all settings after each task completed", but the tool selection in the image editor is still not saved, /sadpanda. 

Please consider adding the option (or saving the last used tool by default even?)

**Comment by campbeb** [comment]
If @Jaex is ok with this, I'll look into  it
