### ISSUE TITLE
Take a screenshot of a part of website 

### ISSUE THREAD

**Issue by Dreadaxe** [ShareX/ShareX#1610]
Option to program to take a screenshot of a part of the website with time intervals.

**Comment by Jaex** [comment]
Capture -> Auto capture can take screen capture with intervals.

**Comment by Dreadaxe** [comment]
Not possible to add deadline with date 
Not possible configure a zone to capture

**Comment by Jaex** [comment]
Auto capture allows to select zone.

**Comment by Dreadaxe** [comment]
It's not possible to add url to Auto capture, for have Auto "web" capture

**Comment by Jaex** [comment]
It is beyond scope of ShareX. You must write your own script if you want such automations.
