### ISSUE TITLE
 HEUR/QVM42.1.Malware.Gen 

### ISSUE THREAD

**Issue by ultravigo** [ShareX/ShareX#1614]
my  Qihoo-360  detected a malware is it a false warning?
https://www.virustotal.com/en/file/dbee1284bba2976a2e99b41ddc913340d3ad0c06fbd9d7c84729e49e25367681/analysis/

**Comment by Scrxtchy** [comment]
It should be false  
standard procedure is to usually report it to @QiHoo360

this can be done in a few ways, as written on their website

> Please compress the files and email them to support@360safe.com or visit the following web page and submit the samples: https://www.360totalsecurity.com/en/suspicion/

**Comment by Jaex** [comment]
#1264

@QiHoo360 detects it every single release, I'm tired reporting false positive they didn't tired falsely detecting it.
