### ISSUE TITLE
ShareX has started to upload any folder I double click

### ISSUE THREAD

**Issue by jadeonking** [ShareX/ShareX#1617]
I've used Sharex for about 3 to 4 months and this has just recently started to happen and I can't get it to stop I have changed no settings that I know of that would cause this reinstalling it has not resolved it either

**Comment by Jaex** [comment]
ShareX don't have any mouse hook or something like that to even know you are double clicking anything. It is literally impossible for ShareX to know you are double clicking folder.

**Comment by jadeonking** [comment]
Well im at a loss to what would cause this the only thing I can notice different is that upload to Sharex is now at the top of the right click menu instead of just "open"

**Comment by Jaex** [comment]
ShareX not even uses shell stuffs to add upload button to menu. It is just one line simple registry entry. Maybe try removing and readding it from here to see is it changes:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/ShareX_TRm71CZHc9.png)

**Comment by jadeonking** [comment]
that fixed it wow

**Comment by Jaex** [comment]
It is very strange how that entry can show up top in your menu. Something must be wrong in your computer caused that.
