### ISSUE TITLE
Crash after upgrade

### ISSUE THREAD

**Issue by sharexmailinatorcom** [ShareX/ShareX#1624]
System.Reflection.TargetInvocationException: Cíl vyvolání způsobil výjimku. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   v ShareX.TaskSettingsTools..ctor()
   v ShareX.TaskSettings..ctor()
   v ShareX.ApplicationConfig..ctor()
   --- Konec trasování zásobníku pro vnitřní výjimku ---
   v System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   v System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   v System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   v System.Activator.CreateInstance[T]()
   v ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   v ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   v ShareX.Program.LoadProgramSettings()
   v ShareX.Program.Run()
   v ShareX.Program.Main(String[] args)

ShareX 11.0.1 Release

**Comment by Jaex** [comment]
#1615
