### ISSUE TITLE
Add onTopReplica as a tool to ShareX

### ISSUE THREAD

**Issue by Permik** [ShareX/ShareX#1625]
[Enhancement]

[onTopReplica](http://ontopreplica.codeplex.com/) is an open source software that is built on .NET 4.0/4.5 framework and works kind of like [Helium](http://heliumfloats.com/) on OSX, so you can watch videos, or browse the Internet on floating windows!

Next, a copy-paste of features of onTopReplica:
A real-time, always on top, "replica" of a window of your choice, based on DWM Thumbnails.
Completely written in C# for .NET 4.0/4.5, makes use of the Windows Forms Aero library.

* Clone any of your windows and keep it _always on top_ while working with other windows,
* Select a subregion of the cloned window:
 * Store the selected subregions for future use,
 * Now with _relative_ subregions from the window's borders.
* Auto-resizing (fit the original window, half, quarter and fullscreen mode),
* Position lock on the screen's corners,
* Adjustable opacity,
* "Click forwarding" allows to interact with the cloned window,
* "Click-through" allows to click through the cloned thumbnail (especially useful with partial opacity),
* "Group switch" mode automatically switches through a group of windows while you use them,
* Non invasive installation doesn't require administrator elevation.

**Comment by Jaex** [comment]
Why you don't use that software as standalone and want it to be added to ShareX?
