### ISSUE TITLE
Gist authorization returns 404

### ISSUE THREAD

**Issue by mihe** [ShareX/ShareX#1628]
When clicking the `Open authorize page...` button in the GitHub Gist text uploader I'm presented with a 404 page.

When looking at [the GitHub API](https://developer.github.com/v3/oauth/), it seems they require the `client_id` query parameter, whereas the one opened by ShareX leaves it blank. Not sure if that's the issue or not.

**Comment by Jaex** [comment]
You didn't even mention you compiling it yourself. API key not exist there.

**Comment by mihe** [comment]
Oh right, I didn't even realize that could factor into it. Good thing you caught that early on. :sweat_smile:

**Comment by Oleksii-Kshenskyi** [comment]
@Jaex Could you please elaborate a bit on why they do not exist there?
I've cloned the project and am trying to make sense of it from the code standpoint, and I'm also having this client_id issue. I've debugged it and I see that API keys are empty in master, but it's not clear why and what can be done with it. Could you explain? Thanks!
