### ISSUE TITLE
[11.0.1] [Feature Request] Add Back in Capture Region  (Annotate) 

### ISSUE THREAD

**Issue by csprance** [ShareX/ShareX#1631]
Can't seem to find the Capture Region  (Annotate) option in 11.01. This was an extremely handy feature. It also broke any old Hotkey setups from version 10 in 11.0.1 that used this Screen Capture option.

Was it removed replaced?

**Comment by Jaex** [comment]
Because I was added annotation to current rectangle region capture, it could confuse people having 2x annotate method for no reason. But I should have waited until current one have pen drawing before removing it :( But other than pen drawing current annotation support surpasses all other features of it and will be more preferable, especially because current region capture also have other useful things in it.

**Comment by csprance** [comment]
Ahh, ok. I use a Wacom tablet almost exclusively and quite frequently need to provide feedback on art assets which often involves my terrible scribbles, handwritten words and curves.  Sounds like this feature is planned so I'll be looking forward to it. 

Keep up the great work guys!

**Comment by Jaex** [comment]
I'm having big trouble finding way to add pen drawing without decrease fps a lot. Even if you don't use pen still just having support for it also decreases normal region capture fps. Because then background image must be changeable (because of pen) which slows rendering time even when you don't draw anything :( So I can add it but it will decrease fps of non pen users too. So I have no idea what to do currently.

**Comment by NotSoSuper** [comment]
+1, the new one with a bunch of stuff is really annoying if you just wanna do a fast capture with some drawing for the whole screen/monitor.

**Comment by Jaex** [comment]
If I add it back only as hotkey would it be enough? I don't want to have 2x annotate method in capture menu.

**Comment by NotSoSuper** [comment]
Wow, wasn't expecting you to consider it, definitely would work for me! As for that is all I used it for, I actually downgraded to get it back.

**Comment by csprance** [comment]
Ya, +1 to the hotkey. I as well downgraded to use it. Critical part of my day as an art director type.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/ShareX.vshost_I36uYUb74H.png)

**Comment by SilverCory** [comment]
How about a way for us to modify what comes up in the capture menu? Or even a modifiable quick capture button thing? Super handy..

**Comment by dannoe** [comment]
@SilverCory what about this?
![sharex_2016-06-30_16-46-50](https://cloud.githubusercontent.com/assets/7450586/16492561/81b7cb6a-3ee2-11e6-8c50-45252b0b418a.png)

**Comment by Jaex** [comment]
Added freehand drawing support to region capture now:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/08/PlKa6KNUn7.png)

**Comment by Jaex** [comment]
@csprance now there is no need for simple annotate hotkey, right? So I can remove it.

**Comment by csprance** [comment]
Not sure whether to open a new issue or just continue on this one. It's fairly related.

Is there any way to change a hotkey for freehand drawing while using the region capture workflow?

 I just updated to that latest version and it dropped some of my hotkeys because they were on tasks that went away. (region capture (annotate))

It used to be before:
* enter region capture
* hit 3 
* draw what I needed 
* hit 1 
* drag my retangle region capture

Now it;s:
* enter region capture
* right click
* select freehand
* draw what I want
* hit 0 
* draw my region

Only one extra step really but it slows down the process considerably having to search for the freehand drawing option.

Is there a way to change the hotkeys used for the tool selection while region capture is activated? 

or maybe just bring back the workflow for region capture (annotate) 

It's extremely handy to quickly mark up and send a screenshot to an artist with feedback.

Thanks again. This is tool is amazing!

**Comment by Jaex** [comment]
There is no way to change hotkeys.

If you use `Tab` hotkey, maybe it can decrease steps more.
