### ISSUE TITLE
Disable right click menu in capture mode

### ISSUE THREAD

**Issue by cexikitin** [ShareX/ShareX#1635]
Old behavior was to cancel capture on right click, new menu is very annoying. Is there an option to disable this? Rolling back for now.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/ShareX_1KKdytUKiN.png)

Disable this.

Also new version will contain these new settings:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/ShareX_xRifWmBQXW.png)
