### ISSUE TITLE
Can't double click on windows to upload them anymore

### ISSUE THREAD

**Issue by FlaggedBrad** [ShareX/ShareX#1638]
It's bugged and ends up taking a screenshot of part of my upper left desktop ;-;

**Comment by Jaex** [comment]
I'm not even sure are you talking about region capture or are you using multi region mode.

**Comment by FlaggedBrad** [comment]
capture region. I press my hotkey and then i double click a window that i would like to upload..

**Comment by Jaex** [comment]
I can't reproduce your problem. Invisible window or something like this could be staying top of your windows, so not sure. Is hover region not shows before you click that there is something wrong?

**Comment by FlaggedBrad** [comment]
yea.... I have rainmeter so..

**Comment by FlaggedBrad** [comment]
the hover region shows the window at first, then it captures a random section of my screen when i double click the highlighted area

**Comment by Jaex** [comment]
Can you record video to show it?

**Comment by FlaggedBrad** [comment]
yeah, one second

**Comment by FlaggedBrad** [comment]
http://puu.sh/psHg9/6b8832f7ba.flv

**Comment by FlaggedBrad** [comment]
(in the video you can see me taking a screencap of my network load, but it captures the top of my left and middle monitor)

**Comment by Jaex** [comment]
Why you didn't use ShareX screen recorder so I could watch it from web site without download flv file. (Not for now, I already downloaded it)

**Comment by Jaex** [comment]
This is so weird, can you try disabling multi region mode from right click -> options and try again.

**Comment by FlaggedBrad** [comment]
too complicated..

**Comment by FlaggedBrad** [comment]
Where would i find that multi region mode setting?

**Comment by FlaggedBrad** [comment]
(there are so many configurable options haha)

**Comment by Jaex** [comment]
Right click in region capture then options in bottom.

**Comment by FlaggedBrad** [comment]
it is already disabled ;-;

**Comment by Jaex** [comment]
Then why you were double clicking?? When it is disabled just single click enough to capture hover areas.

**Comment by FlaggedBrad** [comment]
WHAT

**Comment by FlaggedBrad** [comment]
i'm stupid.

**Comment by FlaggedBrad** [comment]
> So used to double clicking that i forgot how to normal click and i now look like a complete idiot on the internet.

**Comment by Jaex** [comment]
So when you single click it works fine?

**Comment by FlaggedBrad** [comment]
Yes. But no double click..

**Comment by FlaggedBrad** [comment]
(I guess add more idiot-proofing?)

**Comment by Jaex** [comment]
This is again weird because after first click it triggers capturing so how you have time to do double click before it even closes lol. I can't even reproduce it because impossible to double click in time.

**Comment by FlaggedBrad** [comment]
(I have a button on my mouse that double clicks super uber duper quick)

**Comment by FlaggedBrad** [comment]
http://i.imgur.com/yTklOIA.png
