### ISSUE TITLE
Greenshot editor window hides underneath win10 taskbar

### ISSUE THREAD

**Issue by DukeOliver** [ShareX/ShareX#1640]
My windows 10 environment has the taskbar along the top. The Greenshot image editor, when opened automatically after a screenshot, hides underneath the taskbar half the time - this makes it difficult to close/move/etc. It has happened since updating a couple months back. The only fix for me so far is to move the taskbar after every screenshot, which gets cumbersome.

Normal:
![1](https://cloud.githubusercontent.com/assets/7144910/16082046/2e44e05e-32de-11e6-9281-a42de630555c.png)

Hidden:
![2](https://cloud.githubusercontent.com/assets/7144910/16082068/41d4ca1c-32de-11e6-9509-1334e44f0bc7.png)

**Comment by Jaex** [comment]
When you uncheck this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/ShareX_7T6174iU5D.png)

is problem solves?

**Comment by DukeOliver** [comment]
For now, it has solved my issue!

The Greenshot window now spawns in the same spot wherever I place it, instead of a random position underneath the taskbar. I'd have never guessed that was the function of this Setting.

Thanks!

**Comment by FichteFoll** [comment]
Related: when working with multiple monitors (primary on left), a full capture with the above mentioned setting checked will exceed the primary montior's bounds. The editor should never exceed the monitor it opens on, so I guess this requires a manual check for monitor bounds.

https://a.desu.sh/mrowrz.webm

**Comment by dannoe** [comment]
Then this should also be an option. I prefer the current behavior, so I don't accidentally upload files with confidential information on second screen. (You can easily overlook the scroll-bars in the editor)
