### ISSUE TITLE
Hotkeys got broken on latest update

### ISSUE THREAD

**Issue by AnacondaPython** [ShareX/ShareX#1643]
I had these settings

![image](https://cloud.githubusercontent.com/assets/10290348/16141965/dcd35b54-3415-11e6-9fad-6a4726c2ff51.png)

But on latest update, my ALT+S and ALT+A hotkeys no longer work

![image](https://cloud.githubusercontent.com/assets/10290348/16141974/f9e697a6-3415-11e6-88fc-e21e0eac6484.png)

Both images were pulled at the same time. 

Some reason I have lots of my hotkeys not working / missing under "workflows"

**Comment by Jaex** [comment]
You were probably using removed Region (Annotate) method. And hotkey of it reset to "None" because that method not available anymore.
