### ISSUE TITLE
Startup Conflict 

### ISSUE THREAD

**Issue by sunriseal** [ShareX/ShareX#1646]
When I start ShareX under Windows 10 a popup regarding a conflict with shortcuts is presented, The app ShareX is conflicting with are: Dropbox and OneDrive.

I checked DropBOx and OneDrive settings and there does not appear to be any settings relative to PrtSc. I know I can assign different shortcuts in ShareX, but was hoping I could keep ShareX settings

Any ideas/work arounds welcome
Al

**Comment by Jaex** [comment]
#1112
