### ISSUE TITLE
DPI Scaling in Windows 8.1 (and Possibly 8 and 7) causes "Capture ________(An Area)" to display as the wrong DPI

### ISSUE THREAD

**Issue by TheRealAlexV** [ShareX/ShareX#165]
Hi Guys,

DPI scaling causes the "Capture a Rectangle(or other shape)" to display with the wrong DPI/Zoom/Resolution.

Screenshots:

Normal Screen:
![2014-06-04 11 44 40](https://cloud.githubusercontent.com/assets/815793/3176069/51b86180-ec01-11e3-97e6-10d1bcf766d5.jpg)

Screen with Capture area selection active:
![2014-06-04 11 44 49](https://cloud.githubusercontent.com/assets/815793/3176070/51c5c33e-ec01-11e3-902d-9e01025bd5de.jpg)
As you can see, it zooms in quite a bit, and actually drags over part of the desktop from my other monitor. 

In windows 8.1 Under Control Panel\All Control Panel Items\Display:
"Let me choose one scaling level for all of my monitors"
^ If you un-check that, this issue goes away.
Note: This is a default option now for new computers with high resolution screens pre-installed with Windows 8.1.

**Comment by philraj** [comment]
I'm having this issue again in Windows 10.
