### ISSUE TITLE
Icon Size setting issue in Greenshot settings. v11.0.1

### ISSUE THREAD

**Issue by mabbas64** [ShareX/ShareX#1651]
v11.0.1,

The icon size option in greenshot editor settings doesn't save for me on Windows 10. It resets back to 10px after I close the greenshot editor or even restart teh sharex app

http://i.imgur.com/52GxMe2.jpg

**Comment by Jaex** [comment]
After change icon size to 32, re opened image editor it was still 32. Also restarted ShareX still it was 32px. Not sure how it not saves for you.

**Comment by mabbas64** [comment]
Ah thanks @jaex, I was trying with 24, it seems with 32 it saves fine.

<3

**Comment by campbeb** [comment]
The program adjusts it to a multiple of 16 (for 24, it rounded down to 16).
Maybe I can make that more obvious (either a note or change values in the box by 16)
