### ISSUE TITLE
ShareX 11.0.1 doesn't give an option to update and keep the program in the same (custom) directory

### ISSUE THREAD

**Issue by Ulexos** [ShareX/ShareX#1653]
There was no option to install the new version of ShareX in the current directory it's located in when I tried to update ShareX from version 10.9.1 to 11.0.1 .

Really liked it when one could set up and update ShareX in a custom path. Why was this option removed?

**Comment by Jaex** [comment]
I didn't remove anything?

**Comment by Ulexos** [comment]
It didn't update ShareX where I installed it at, the newer version installed itself to the default C:\Program Files directory instead of the one I set it up to use. There was no option in the updater whatsoever to install it to a custom directory.
