### ISSUE TITLE
ffmpeg download doen not work in Windows XP

### ISSUE THREAD

**Issue by jm-andonegi** [ShareX/ShareX#1654]
Apparently it doesn't find the file to download.

I found this post about ffmeg and XP: https://groups.google.com/forum/#!topic/alt.comp.os.windows-xp/EAFtX6jSfL0

The version mentioned has been moved. I have downloaded manually this version and works fine: https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-2.5.2-win32-static.7z

**Comment by Jaex** [comment]
I tried to download it worked for me. Can you try again because few days ago they were doing changes on URL. So it could be temporary down.
