### ISSUE TITLE
Show Cursor Clicks on Screen Recordings

### ISSUE THREAD

**Issue by teociejiijjs** [ShareX/ShareX#1657]
In screen recordings, is there a way to show mouse clicks by animating the cursor, or some other way to show a click was performed?

**Comment by Jaex** [comment]
#1040

**Comment by pfrng** [comment]
USe this hack to [highlight cursor and show click visual feedback](http://www.pfrng.com/enable-sharex-cursor-highlighting/)

**Comment by matijaerceg** [comment]
can we get the link above removed?
