### ISSUE TITLE
Audio screen capture in 11.0.1

### ISSUE THREAD

**Issue by TryCooo** [ShareX/ShareX#1658]
Another user had the same question as me here:
https://github.com/ShareX/ShareX/issues/215

As it was resolved, that was on an older version of ShareX. I am on 11.0.1 and my only options for audio recording are Headset Microphone (when my headphones are plugged in) and Microphone Array.

Is there any way now to record my screen and capture the audio from the source?

Thanks

**Comment by dannoe** [comment]
Did you try this?
![sharex_2016-06-22_17-54-22](https://cloud.githubusercontent.com/assets/7450586/16273601/84a76a88-38a2-11e6-8346-88f19e9a0796.png)

**Comment by TryCooo** [comment]
I didn't but I can try that now. Forgive my ignorance, but it looks like it installs a separate program rather than an addition to ShareX. Is that correct?

**Comment by MrTrvp** [comment]
@TryCooo It downloads another program to process what ShareX recorded. Not sure if ShareX records sounds, but FFMPEG can process it.

**Comment by TryCooo** [comment]
@MrTrvp Thank you. I guess I'll give it a shot. Fingers crossed!

**Comment by dannoe** [comment]
At bottom it just installs an virtual audio card, which repeats everything on your computer. And FFmpeg is going to use this card.

**Comment by TryCooo** [comment]
And we're good!! Thanks all :)
