### ISSUE TITLE
Can't upload raw bytes data to a custom uploader

### ISSUE THREAD

**Issue by FukujiMihoko** [ShareX/ShareX#1659]
Basically, some uploaders (like https://github.com/ccubed/Downloop) use raw bytes data in the body of their API requests for file uploading. In Python, it works by uploading like this:
```python
import requests
downloop_root_url = 'insert url to your server here'
with open('file.png', 'rb') as f:
    data = f.read()
r = requests.post(downloop_root_url+'/api/upload', data=data)```

The filename is handled by the server, as it just gets raw data and reads the MIME types. ShareX won't let me have an empty file form name (while the server expects just the data from the image itself, instead of the file).

**Comment by Jaex** [comment]
Reason why I didn't add raw bytes upload support because more than 99% of uploader hosts supports proper multi part upload support. UI don't have empty space to add new settings so not gonna worth adding it just for few weird uploaders which not supports proper way to upload.

**Comment by Jaex** [comment]
I redesigned custom uploader UI to create more space and added body type option now which also includes binary body type:

![](https://jaex.getsharex.com/2019/02/ShareX_NqWjv0N8R9.png)
