### ISSUE TITLE
[Suggestion] Remember last region when capture region

### ISSUE THREAD

**Issue by geofausto** [ShareX/ShareX#1663]
I bit different if I use Last region capture, sometimes I want to know last captured area by showing last polygon of region capture action.

I tried to find this action but I couldn't.

Thanks.

**Comment by Jaex** [comment]
ShareX already remembers last region. If you mean you know that it have last region capture hotkey but you don't want to capture it but just have it selected. Then I don't have plan to add it.

**Comment by bastienperez** [comment]
Hello, sorry to bother you about this feature, but the ability to remember the last region without capturing it automatically is often needed.
For example, when documenting a process, we sometimes need to blur, add text, or make other edits at each step.

Is there any way to implement this or not?

But for people who want to use this kind of feature, there is a "workaround": assign a specific mouse click to `Capture` > `Region capture` > `Capture last region`.

<img width="962" height="282" alt="Image" src="https://github.com/user-attachments/assets/927728b0-2a57-4d93-ba82-76bdd67e9873" />
