### ISSUE TITLE
Image History bug in 11.0.1

### ISSUE THREAD

**Issue by ScoopJohn** [ShareX/ShareX#1669]
Hi, my computer suddenly was facing problems and when i restarted my PC seems something resetted and that is my ShareX. The history in it was deleted in the program while the History.xml file is still there, except i can't access it anymore in ShareX, it gives me this error:
![image](https://cloud.githubusercontent.com/assets/20162073/16371215/56ad9d9a-3c45-11e6-82be-df75f07a966f.png)
Any way to solve it? ;(

**Comment by Jaex** [comment]
This is not bug. Corruption happened in part of your History.xml file. Open your History.xml file check line 26507 and remove invalid lines. That way your file won't be lose completely. This is why I only append data to that file so if something bad happen in your pc (or hard disk) still your previous data will be intact.
