### ISSUE TITLE
[Suggestion] "Show file in explorer" opens folder despite the fact it's already opened

### ISSUE THREAD

**Issue by side-by-side** [ShareX/ShareX#1673]
Hello. I'm using last version of ShareX (11.0.1) on Windows 8.
When we are using "Show file in explorer" as "After capture task" the folder with captures is opened every time i made a screeshot, even if it is already opened.

When I'm making 3 screenshots — 3 folder windows are opened. Etc.

Suggestion: check whether a folder with captures already opened and don't open it again.

**Comment by Jaex** [comment]
How am I supposed to know is folder is open already? Because there is countless windows explorer alternative and just checking process name and window title won't be enough. So it is not accomplish able.

**Comment by dannoe** [comment]
@Jaex http://stackoverflow.com/questions/14600987/code-to-open-windows-explorer-or-focus-if-exists-with-file-selected

**Comment by Jaex** [comment]
@dannoe it only works for Windows Explorer what about other explorers?

**Comment by dannoe** [comment]
@Jaex but aren't you using Process.Start("explorer.exe")? so it does not work for other filemanager right now anyways. or do i miss something?

**Comment by Jaex** [comment]
I'm sure that other file managers must have dummy executable or something to run their own file manager when explorer.exe is run, no? I didn't try but if that was not the case many people would have come and report here that folder not opens.

**Comment by dannoe** [comment]
I tried it with XYplorer and Explorer++ right now, and it didn't work.

**Comment by Jaex** [comment]
Okey then I will use your method.

**Comment by side-by-side** [comment]
You got the point, thank you.

**Comment by dannoe** [comment]
Great. I just tested it the other way. The SHOpenFolderAndSelectItems Method from my initial post will open other explorers if they are registered correctly. 
(I used Explorer++ and a small c# Sample Application with the code from Stackoverflow.)

**Comment by Jaex** [comment]
If you tested it already you can pull request it.

**Comment by dannoe** [comment]
Yeah I will do it later that day.

**Comment by side-by-side** [comment]
@dannoe, I want to thank you for this exremely extremely fix.
