### ISSUE TITLE
Capture doesn't upload.

### ISSUE THREAD

**Issue by fubie** [ShareX/ShareX#1680]
Hey, ShareX used to upload anything I captured automatically, any reason why it does not do that anymore?

**Comment by Jaex** [comment]
It is impossible for us to know why it doesn't upload for you.

**Comment by fubie** [comment]
It just saves to my sharex folder and doesn't upload to imgur, I have to manually upload it. Thanks for the help LOL.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/chrome_BGDx0eYGjx.png)

**Comment by fubie** [comment]
See, that wasn't that hard was it? You're a bit tough in the noggin there but you got it! Thanks for actually helping this time nigger. Next time you get a paying customer then you should actually help them like you finally did at the end of the day niggerfaggot, enjoy sharex because they probs pay u shit $$$ LOL

**Comment by Jaex** [comment]
In my first message I was already wrote:

`One guess is, maybe it is disabled in after capture tasks menu.`
