### ISSUE TITLE
ShareX Screen Capture - Mouse Pointer Offset with ZoomIt/Magnifier

### ISSUE THREAD

**Issue by Osaka78** [ShareX/ShareX#1681]
Dear ShareX Team,

Thank you for creating ShareX.

We're not sure if it's just us; We believe there's something odd happening when ShareX screen captures ZoomIt and Magnifier, as in: 
"Osaka78 shows Mouse Pointer Offset on ZoomIt/Magnifier with ShareX" (2:11 minutes)
https://youtu.be/anFtzN__Ccc

In the video you can see ShareX captures ZoomIt with two mouse pointers and Magnifier with an offset mouse pointer.

During normal use, as well as ShareX screen recording sessions, the mouse pointer is displayed as expected; mouse pointer offset shows up only in video playback.

Is there a way to eliminate the mouse pointer offset from ShareX videos and capture what we see on the screen with ZoomIt and Magnifier?

Thanks again and kind regards from Osaka78

**Comment by Jaex** [comment]
I suspect there is possibility to fix that. I don't think any screen recorder be able to capture it properly too, is it?

**Comment by Osaka78** [comment]
Dear Jaex, 

Thank you for your reply.

Yes, you are right. We haven't been able to screen capture ZoomIt or Magnifier with other screen recorders. We've seen YouTube videos with ZoomIt and Magnifier working though. 

Thanks again Jaex.

Kind regards from Osaka78
