### ISSUE TITLE
Thickness draw line

### ISSUE THREAD

**Issue by Sentaq** [ShareX/ShareX#1682]
First of all; my apologize if this question asked before. But, is it possible to change the thickness of the draw line while in capturing mode?

**Comment by Jaex** [comment]
Yes it is in right click menu: Border size.

**Comment by qubodup** [comment]
![image](https://github.com/ShareX/ShareX/assets/18312/3b575a0d-bd83-4574-bf78-6cb011d9a5b1)
For posterity/searchability, the line/outline/circle/rectangle border size/width/thickness/strength can be set in the tool options menu
