### ISSUE TITLE
Image editor window remains minimized after screenshot Windows 10

### ISSUE THREAD

**Issue by d-w-h** [ShareX/ShareX#1683]
After taking a snapshot, the image editor does not show and remains minimized in the task bar. If the window is closed, continues to work as normal uploading to the cloud (imgur in my case). Cannot see the window (even if the tool bar is moved to the top of the screen).

**Comment by d-w-h** [comment]
Looks like it was solved in a previous thread.

**Comment by d-w-h** [comment]
Issue open in another ticket.

**Comment by Jaex** [comment]
#1544
