### ISSUE TITLE
History is not ordered properly by date using non English base systems

### ISSUE THREAD

**Issue by domink** [ShareX/ShareX#1685]
The History panel does not show the images on the right order when I want to order by Date pushing the Date button.
![sharex_2016-07-01_11-04-40](https://cloud.githubusercontent.com/assets/1288430/16517086/ec521a5e-3f7b-11e6-8b9f-d37b576dcb8f.png)

My Windows is configured on Spanish and the date format is dd/mm/aaaa.
It looks like the History panel is using the lexicographic order instead date and it works property when the day format is aaaa/mm/dd but it is not on other cases.

**Comment by Jaex** [comment]
I was added generic sorting support to list view control and was enabled that option in history window. So it actually don't knows it is date time.

**Comment by campbeb** [comment]
@dannoe It seemed you were working on a pull request to fix this. Did you change your mind or run into problems?

**Comment by dannoe** [comment]
Yeah, I wrote a ListViewColumnSorter, afterwards realizing there is already one. I wanted to ask Jaex if I should change the existing one or add a new one.
I didn't had enough time anymore, so I paused it, but accidentally pushing it to my repo with the issue no. in the commit message.

I don't know when I'm able to get back to it. Feel free to take it.

**Comment by Jaex** [comment]
@dannoe I saw your implementation, it was not good because you were doing date time parsing instead of getting DateTime from object which stored in ListViewItem.Tag.

**Comment by dannoe** [comment]
@Jaex Yes this was intentional because I wanted the ListViewColumnSorter to be as abstract as possible and not depending on HistoryItem. So it's reusable in other places.

**Comment by Jaex** [comment]
Parsing 30k date time will slow down it alot I bet.

**Comment by dannoe** [comment]
Yeah totally right, that's possible. Did you see my Edit in the previous comment?

**Comment by Jaex** [comment]
No.
