### ISSUE TITLE
Downsampling / Superresolution Support (VSR/DSR)

### ISSUE THREAD

**Issue by mihawk90** [ShareX/ShareX#1688]
Currently Superresolution (or Downsampling, whatever you wanna call it) seems to be a little bugged or weird. I suppose this happens due to whatever method is used to get the image from the video card.

On my end this is happening with an AMD video card, I can't speak for nvidia since I don't currently have ShareX installed on any Nvidia machine. AMD introduced VSR a while ago, similar to what Nvidia calls DSR (which is basically what various Enthusiasts did way back before both of them introduced this "innovative" feature). Basically a game (or the desktop for that matter) is rendered at a higher resolution then the Display it is being used on. It adds detail to games and reduces Aliasing naturally. What both of them do is scaling the image down to the native resolution just before they are passed to the HDMI/DVI/DP output and rendered on the display.

For example I can render a game at 3200x1800, but actually use a 1920x1080 display, it's scaled down right before it passes the Videocard Output.

The Problem now with ShareX is that it seems to grab the scaled down version of the image (1920x1080), not the original render resolution (3200x1800). It also seems to add a weird padding around the image. The image is also weirdly blurred as you can see on the font.

It does recognize the original render resolution though, as shown here (this was just a quick test to see if it works). The image is actually 3200x1800, but the actual content/game is 1920x1080 in the corner. This image is unedited of course:
![image](https://cloud.githubusercontent.com/assets/556162/16541679/afbca28a-4089-11e6-95bc-29dfa10a63ab.png)

I'm using Fullscreen mode, not sure if it makes a difference though.

Also on a sidenote: when I first encountered this issue, I was using "Capture active monitor", but somehow that wouldn't work now and I have to use "Capture active window", the result is the same though. Active monitor works every now and then though, it's a little strange.

Also: I don't know if that helps, but using Windows' Built-In Screenshotting and pasting the image in Paint results in a full-size image as it was rendered, not shown (so 3200x1800).

**Comment by Jaex** [comment]
ShareX not supports game capture (directx/opengl).

**Comment by lithium720** [comment]
If you want to take screenshots of a game, run it in Windowed Borderless or Windowed. But it will not have the modified rendering scale like you want it to, because as @Jaex mentioned, ShareX doesn't support DirectX / OpenGL apps.

Overwatch itself does what you are mentioning though, just FYI. Video -> Advanced -> Screenshot Quality
