### ISSUE TITLE
Hastebin url based on file extension...?

### ISSUE THREAD

**Issue by leonardosnt** [ShareX/ShareX#1690]
Uploading a file named `something.c` gives a url like `hastebin.com/KEY.hs`
Uploading a file named `something.java` gives a url like` hastebin.com/KEY.hs`
Uploading a file named `something.cs` gives a url like `hastebin.com/KEY.hs`

Would be better

`something.c` > `hastebin.com/KEY.c`
`something.java` > `hastebin.com/KEY.java`
`something.cs` > `hastebin.com/KEY.cs`

and so on...

**Comment by Jaex** [comment]
I'm not sure is it good idea. Example .hs must have probably generic syntax highlighting and ShareX using .txt for clipboard text upload etc. so it can remove syntax highlighting. This can apply for invalid extensions too. And I don't have list of extensions hastebin supports. So it is not that easy.

**Comment by Jaex** [comment]
But still added it because better than having always `.hs`.

**Comment by leonardosnt** [comment]
@Jaex 

https://github.com/seejohnrun/haste-server/blob/master/static/application.js#L161-L172

**Comment by Jaex** [comment]
I wonder why their website automatically use .hs as default.

**Comment by leonardosnt** [comment]
Me too :laughing:

**Comment by ttwd80** [comment]
you can change what ever extension it gives you. if it gives you key.hs, you can use key.cpp or key.java and it would be the same content with different syntax highlight
