### ISSUE TITLE
Shift-pressing to maintain a selection's dimension's ratio doesn't work when editing the selection

### ISSUE THREAD

**Issue by ficion** [ShareX/ShareX#1691]
When capturing and selecting a region, you can select it while pressing Shift to make it a square. Once it's selected and you can only edit the region, that feature no longer works.
It's a really small issue but I thought it had to be noted.

**Comment by Jaex** [comment]
This is difficult to implement because I just can't do:

                    if (Manager.IsProportionalResizing)
                    {
                        endPos = CaptureHelpers.SnapPositionToDegree(StartPosition, endPos, 90, 45);
                    }

because in each node start and end position is dependent.

**Comment by ficion** [comment]
I see, I understand. Since it's really just a very small issue I don't think it deserves a more complicated solution, and it's barely a problem anyway.
Perhaps you could lock all the proportionally-made regions so they can't be nonproportional, but that's just an idea.

**Comment by Jaex** [comment]
Managed add this now: https://jaex.getsharex.com/2017/11/fCcqp36cBm.mp4
