### ISSUE TITLE
Exception when uploading a file

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [ShareX/ShareX#1693]
Uploading to mega, only this one file always has a problem.
It works with other files, mega works fine as well.
Out of 10 files this is the only one that fails (just another .zip file).
Its not at some special position, like the first of all files that get uploaded and its also not the last, seems random.
Doing a retry (rightclick, click upload manually again) doesnt work and immediately fails with the same error.
Restarting ShareX doesn't fix it either.

Its just this single file.

Awesome tool btw, thanks for creating it, can't live without it anymore :+1: 

> System.ArgumentNullException: Value cannot be null.
> Parameter name: value
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Object context)
>    at CG.Web.MegaApiClient.MegaApiClient.GetNodes()
>    at ShareX.UploadersLib.FileUploaders.Mega.GetParentNode()
>    at ShareX.UploadersLib.FileUploaders.Mega.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 
> Message:
> The remote server returned an error: (500) Internal Server Error.
> 
> StackTrace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
> 
> System.ArgumentNullException: Value cannot be null.
> Parameter name: value
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Object context)
>    at CG.Web.MegaApiClient.MegaApiClient.Login(AuthInfos authInfos)
>    at ShareX.UploadersLib.FileUploaders.Mega.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 
> Message:
> The remote server returned an error: (500) Internal Server Error.
> 
> StackTrace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

**Comment by asdfgasdfsafgsdfa** [comment]
Just tested: Uploading through the browser works, no problem.

**Comment by Scrxtchy** [comment]
The stack returns an issue saying that the message recieved wasn't in a json format.  
this is because the message was just "Server Error" etc.

Seeing as the issues was 8 days ago, is it still non-functional?

**Comment by Jaex** [comment]
`(500) Internal Server Error` means problem not to do with ShareX.
