### ISSUE TITLE
How do I use the custom region option?

### ISSUE THREAD

**Issue by LeDirt** [ShareX/ShareX#1696]
My current hotkey settings: [https://i.imgur.com/JW9O39s.png](link)
Whenever I try to press **PrintScreen** - my mouse just flashes for a moment and nothing happens.

I just want to screenshot a specific region (not a specific window, not the entire screen) of my screen and upload it. But all I am able to do is first take a fullscreen/window screenshot and then crop it.

I only seem to get the function working when I choose it from the program itself, by this I mean clicking on the **Capture** button and then on the **Region** button.

How do I make the hotkey for a custom region screenshot work, so each time I press the hotkey I can choose a region I want to screenshot?

**Comment by Jaex** [comment]
Something in your computer already registered `Print screen` hotkey and ShareX unable to register it. So something else in your PC flashing your cursor not ShareX.
