### ISSUE TITLE
Upload to host based on file type

### ISSUE THREAD

**Issue by Watchful1** [ShareX/ShareX#1697]
I have a hotkey set up to record a screen region which results in an mp4 file. I have a different hotkey that captures a screenshot, which results in a png.

I want to upload the mp4 to streamable and the png to imgur. But they are both "image" type files and you can only select one image destination.

Or possibly a way to select the destination directly in the workflow settings if that would make more sense.

**Comment by Jaex** [comment]
You can change screen recording hotkey destination to streamable.
