### ISSUE TITLE
[Suggestion] Cloud-based settings?

### ISSUE THREAD

**Issue by hex3r** [ShareX/ShareX#1698]
In the age of cloud storage it's a pain of setting up ShareX on a new machine since I, for one, have a lot of custom tweaks for seamless screen capturing. Can cloud-based settings be implemented in the application?

**Comment by Jaex** [comment]
That would require having hosting to store peoples settings and not to mention I'm not web developer so it won't be possible. And most of peoples won't like their account info to be stored in cloud which will be security threat.

**Comment by dannoe** [comment]
You could try to set your personal folder path to a cloud-based folder (like dropbox, seafile, qsync, gdrive, etc.)
![sharex_2016-07-10_15-36-01](https://cloud.githubusercontent.com/assets/7450586/16713858/2d3b4e5c-46b4-11e6-9886-683631a10769.png)
