### ISSUE TITLE
Cursor Highlight when recording screen.  Enhancement request

### ISSUE THREAD

**Issue by EntropyDivideByZero** [ShareX/ShareX#17]
Hi, 
Pardon me if I am posting this in the wrong or unsuitable place.

I would love it if a transparent coloured circle could be recorded where the mouse cursor is located during screen recording.  This would be useful in the case where a screencast or presentation is to be recorded of say a painting program where the cursor is very tiny.  Viewers could see what the person is pointing at.

Apologies again if I have posted this in an unsuitable place.

Thank you

**Comment by Jaex** [comment]
#1040
