### ISSUE TITLE
Subdomain support & change uploaded file name

### ISSUE THREAD

**Issue by Lucidator** [ShareX/ShareX#1705]
Hello! I would like to host my images, files, etc on my own server, and upload with ShareX.

I want to have a very short link to give to the viewers, like (i.test.com/12356.jpg), but I want to store them in a location like (test.com/sharex/images/123456.jpg). I've already set up the subdomain redirect, but ShareX will still output the longer version in my clipboard.

There should be a feature to allow you to replace it with a custom subdomain path.

Also, a way to change the uploaded file name to a custom pattern using some sort of variables system, like this:

%d - Day
%m - Month
%y - Year
%h - Hour
%i - Minute
%p - AM/PM
%a - Random alphanumeric character
%n - Random digit
%l - Random letter
%s - Random symbol

**Comment by Jaex** [comment]
ShareX support customization of output path fully so you can use subdomain.
Also supports file naming support with more pattern than your examples.
