### ISSUE TITLE
Multi-Region: Double-click doesn't work while in effect-mode

### ISSUE THREAD

**Issue by dannoe** [ShareX/ShareX#1707]
Multi-Region:
Double-click doesn't capture while in effect-mode, you have to change to region mode or use Enter.

**Comment by Jaex** [comment]
Capturing with double click in effect mode was actually bug and I was fixed it in this release :(
It also was canceling when double clicked when there is no region at all which was also bug.

**Comment by dannoe** [comment]
We may don't talk about the same thing. I am talking about finishing the capture with double-click in effect mode. 

Workflow:
- Capture region. (multi-region)
- Selection some regions.
- Change to effect (e.g. Pixelate)
- Selecting some areas for Pixelate effect.
- Trying to finish the complete capture with double-click.
- Doesn't work, I have to press enter or change to selection mode and then double-click.

**Comment by Jaex** [comment]
We talking about same thing. Most people won't have your issue because by default window hover capture is active therefore when people double click outside it will select something outside. And double clicking on top of effect was not triggering capture.

**Comment by dannoe** [comment]
Now I can understand, I have never tried to double-click outside of my selected regions, my though was it doesn't depend on where I double-click. 

But this behavior could be improved. We could just look for a general double-click and ignore the single click then, couldn't we?

**Comment by Jaex** [comment]
Ignoring single click would require waiting for double click time for each single click action which would delay action and will be annoying.

**Comment by dannoe** [comment]
What about just undoing the last single click action on double click?

**Comment by Jaex** [comment]
Try to use `Tab` shortcut which added in new build. It can help in your situation.

**Comment by dannoe** [comment]
Yeah, thanks for the hint. Seems to be fair, because left hand isn't leaving the keyboard anyway.
