### ISSUE TITLE
[Question] Adjusting region before capture?

### ISSUE THREAD

**Issue by wilandlane** [ShareX/ShareX#1709]
I just started using ShareX and love it so far. But can't find my favorite feature from other screen capture tools: the ability to adjust the capture region before capture.

Right now if I left click and drag a region as soon as I let go of the mouse, that region is captured. Is it possible to adjust the region before capturing? Like resizing an image?

**Comment by Jaex** [comment]
Right click -> Options -> Multi region mode will allow to move or resize regions without capture.

**Comment by wilandlane** [comment]
Yes, that's it! I read through those options but none of them jumped out as "adjustable."
This is now my new favorite screen cap tool. Thanks, Jaex!

**Comment by Jaex** [comment]
I didn't wanted to have very long description in that menu.
