### ISSUE TITLE
Lack of a hotkey to abort screen recording

### ISSUE THREAD

**Issue by geek085** [ShareX/ShareX#1711]
A user is able to start & stop screen recording using the keyboard shortcut combo "Shift + PrntScrn", but there is no such keyboard shortcut to abort the recording. This would be really helpful in cases where the entire screen is being recorded (in which case, the "Stop" & "Abort" buttons in the footer would not be visible to the user).

**Comment by Jaex** [comment]
By the way you know that there is tray icon which you can right click to abort, right?

**Comment by geek085** [comment]
Wow, never thought of looking there. 
Then again, a keyboard shortcut would be really nice just for the sheer ease of operation it would lend.

**Comment by Jaex** [comment]
I will add it.

**Comment by Jaex** [comment]
Added here: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/07/ShareX.vshost_43CGHWsPHx.png)

**Comment by geek085** [comment]
Thanks, this makes it that much easier.

**Comment by geek085** [comment]
When is the next release?

**Comment by Jaex** [comment]
I don't know?

**Comment by geek085** [comment]
Thank you for the new release. You are the best.
