### ISSUE TITLE
Issue with screen recording

### ISSUE THREAD

**Issue by letmein87** [ShareX/ShareX#1713]
Hello,
ShareX is most useful and easiest program ,which makes  pc usage more comfortable,.My request is to add two more features in screen recording which make recording more easier .

**1.**Is it possible to Add "pause" button in screen recording tab,i mean while recording,a feature to pause it and again continue recording and at the end result will be single video file.

**2.**Recording starts as soon as the required capture area is drawn,provide a start,stop switch,

**Comment by Jaex** [comment]
#205
