### ISSUE TITLE
Magnifier should be based on the corner of a region, when correcting regions

### ISSUE THREAD

**Issue by dannoe** [ShareX/ShareX#1714]
When you're trying to correct the size of a region, the magnifier should be based on the corner of the selection and not the mouse position Otherwise you have to hit the corner very precisely, to use the magnifier.

**Comment by Jaex** [comment]
I know that but it could be complicated to implement. But what could be more easier workaround is automatically moving node to be center of your cursor that way magnifier will point always corners.

**Comment by yashpalgoyal1304** [comment]
> But what could be more easier solution is automatically moving center of node to your cursor when clicked that way magnifier will point always corners.

i dont get that. can u illustrate or rephrase?

**Comment by yashpalgoyal1304** [comment]
ohh, okay, got it now. the "center of" was a bit of tautology for me. yeah, that can work too.
