### ISSUE TITLE
I acn get rid of the elipse on screenshot

### ISSUE THREAD

**Issue by snadge1** [ShareX/ShareX#1718]
Ive had a heck of a time trying to get rid of the elipses that just appeared when i take a screenshot, i normally have freehand+capture mode when i press F6, now its that, but only shows an elipse...how do i turn it off>?

tried uninstalling it with revo pro and still the same

thanks

**Comment by Jaex** [comment]
You can right click to select rectangle region when it is open.

**Comment by snadge1** [comment]
thanks man  :)
