### ISSUE TITLE
Main Menu will not respond to AHK script

### ISSUE THREAD

**Issue by TranquilMoose** [ShareX/ShareX#1719]
AutoHotkey scripts work on everything in ShareX except the main menu.  Neither sending a mouseclick or TAB

**Comment by Jaex** [comment]
What is it to do with ShareX?

**Comment by TranquilMoose** [comment]
I'm trying to get it to capture a window and upload a window every minute automatically.

**Comment by Jaex** [comment]
Auto capture of ShareX not helps?

**Comment by TranquilMoose** [comment]
I tried to use it but it doesn't have the functionality of the capture window option. If there was a way to tell Auto Capture to select a certain window I wouldn't need to use AHK.

**Comment by Jaex** [comment]
Is window region keep changing?

**Comment by TranquilMoose** [comment]
No, but it's not always in the foreground.  By selecting Capture, Window, (Window Name) it doesn't matter what I'm doing on the computer at the time it just takes a capture of the Window I want.

**Comment by Jaex** [comment]
You can take screenshot of window with AHK and then upload it with ShareX to have full control.

**Comment by TranquilMoose** [comment]
Not sure I follow you there.  I need to take the screenshot with sharex, but it doesn't do what I need nor will it allow me to use a script to make it do what I need.

**Comment by Jaex** [comment]
I have no idea why your script can't send input to ShareX main window. So I was offering alternative solution therefore.

**Comment by TranquilMoose** [comment]
Im interested in your alternate solution but don't understand what you mean to use AHK to take the screenshot.

**Comment by Jaex** [comment]
I didn't use AHK so can't give solution but in AutoIt it was one line code like this: https://www.autoitscript.com/autoit3/docs/libfunctions/_ScreenCapture_CaptureWnd.htm which then you could give file path to ShareX.exe and it would upload it in already open ShareX instance.

**Comment by TranquilMoose** [comment]
Interesting, I'm not sure if AHK does that or not but I will look into it. If not I will look into using autoit.  Thanks for the idea.

**Comment by dannoe** [comment]
You don't have you interact with the menu. You could just setup an hotkey in ShareX and press this specific hotkey in AHK.

**Comment by TranquilMoose** [comment]
I thought of that too, but for some reason ShareX does not have the option
of selecting a specific window to capture when set up as a hotkey/workflow
like it does when you select Capture, Window... from the main menu.  If it
did I was planning to use a command line switch to initiate that hotkey
because ShareX does not recognize when AHK sends hotkeys to it either.  I
looked into using AutoIt last night for a couple of hours but it was the
equivalent to me learning Mandarin overnight.

**Comment by dannoe** [comment]
I just tested it on my machine with the following AHK Script:
`F1::Send ^+h`

I just focused a random window (you may focus your specific window with AHK for the automation) and then pressed <kbd>F1</kbd>, which triggers: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>H</kbd> (^+h).
ShareX successfully took the screenshot.

Settings:
![sharex_2016-07-18_09-58-54](https://cloud.githubusercontent.com/assets/7450586/16908755/52503a3e-4cce-11e6-9eb8-20bc9e220421.png)

**Comment by TranquilMoose** [comment]
I notice in the screen capture you have it set to "Capture the Active
Window".  That's what I'm trying to avoid. I don't want it to have to make
it active in order to get a screen cap from it.  If there were a way of
selecting a window, like there is on the Main menu, Capture, Window... then
that would work.

**Comment by dannoe** [comment]
But the "Capture window" function does activate the window and then do the screenshot. So does it really matter if ShareX activates it or AHK?

**Comment by TranquilMoose** [comment]
What I'm trying to do is take a screen capture of something in the
background while I'm working on something else. Maybe if you look at my
work-around you will understand better what I'm trying to do.

loop
{IfWinExist, CBWTP_Development rob - 10.110.1.201 - Remote Desktop
Connection
    WinActivate
    WinMaximize
    run, C:\Program Files\ShareX\sharex.exe -startautocapture -s
    sleep, 1000
    send {altdown}{tab 2}{alt up}
    sleep, 58275
}

This works but it interrupts me once a min for 3 seconds.

**Comment by Scrxtchy** [comment]
found this on AHK forums
```
hwnd := WinExist("ahk_class MozillaWindowClass")
if !hwnd
	MsgBox, Mozilla window doesn't exist.
else
{
	pToken := Gdip_Startup()
	pBitmap := Gdip_BitmapFromHWND(hwnd)
	Gdip_SetBitmapToClipboard(pBitmap)	; or Gdip_SaveBitmapToFile()
	Gdip_DisposeImage(pBitmap)
	Gdip_Shutdown(pToken)
}

#Include Gdip.ahk				; by Tic http://www.autohotkey.com/forum/topic32238.html
```

Look at GDIP's library and if needed switch to saving file
have sharex process this saved file and delete it from the system via more scripting

**Comment by TranquilMoose** [comment]
I tried everything I knew to do to get that to work. I know it's seeing the
window exists because if I change the name I get the "window doesn't exist"
error and I know it's recognizing the external GDIP.AHK file because if I
change that filename it won't compile.  When I try to paste from the
clipboard into MSPaint or MSWord, after running the script, I get the error
"This image cannot currently be displayed" and when I try to save it as a
file, nothing ever shows up.  I've tried Jpg, Bmp, and Png.  Below is the
script I've been trying.


hwnd := WinExist("CBWTP_Development rob - 10.110.1.201 - Remote Desktop
Connection")
if !hwnd
    MsgBox, Mozilla window doesn't exist.
else
{
    pToken := Gdip_Startup()
    pBitmap := Gdip_BitmapFromHWND(hwnd)
    Gdip_SetBitmapToClipboard(pBitmap)  ;Gdip_SaveBitmapToFile(hwnd,
"c:\test.bmp", quality=100)
    Gdip_DisposeImage(pBitmap)
    Gdip_Shutdown(pToken)
}

#Include gdip.ahk               ; by Tic
http://www.autohotkey.com/forum/topic32238.html
