### ISSUE TITLE
Change default Pomf clone to a decent clone.

### ISSUE THREAD

**Issue by neko** [ShareX/ShareX#1720]
Pomf.cat's uptime the last few weeks has been really unreliable; I'd recommend using one of the more reliable clones from [this spreadsheet](https://docs.google.com/spreadsheets/d/1kh1TZdtyX7UlRd55OBxf7DB-JGj2rsfWckI0FPQRYhE/edit#gid=0) as the default.

I'd probably suggest mixtape.moe myself.

Compare pomf clone uptimes [here](http://pomfstatus.sapph.io/).

**Comment by banksymate** [comment]
Having the other owner change the NS back to CloudFlare since I'm out of town, our cache server is going down way too often and we've been aware and have been trying to address it but it hasn't been working out so I'm moving back to CloudFlare.
