### ISSUE TITLE
"Task Settings" Error

### ISSUE THREAD

**Issue by ImDale** [ShareX/ShareX#1726]
Get this error when I click Task Settings : http://i.imgur.com/3zxYWPD.png

Log : http://pastebin.com/brtphSqH

**Comment by Jaex** [comment]
#1350

**Comment by ImDale** [comment]
I tried everything in that post before I posted. I searched for "39" and there were no hits in any of the json's

**Comment by Jaex** [comment]
Open `D:\ShareX\UploadersConfig.json` and `D:\ShareX\HotkeysConfig.json` one of it must have 39.

**Comment by ImDale** [comment]
https://gfycat.com/CrispCheeryBumblebee

**Comment by Jaex** [comment]
You searching in Documents but your folder in D:\
What is that APIKey in video by the way?

**Comment by ImDale** [comment]
api key is ultraimg i think? http://i.imgur.com/4ENQtUS.png

Also so I looked in d: and in the app json the 39 is in "MagnifierPixelCount" What should it be? or just anything lower than 39?

**Comment by Jaex** [comment]
I figured it is ultraimg later, this is why I was edited my previous message.

You don't need to ping me, GitHub still sends me email for each issue message.

It should be max 35.
