### ISSUE TITLE
make abort button in recorder darkish-red

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#1731]
¯\\_(ツ)_/¯

**Comment by Jaex** [comment]
Red mainly means "Stop": https://www.google.com.tr/search?q=stop&tbm=isch

So making abort button red can be confusing for some people.

**Comment by Scrxtchy** [comment]
Although I've never really seen an abort button that isn't red either
Looking at images still returns Stop buttons though, since they are similar in terminology

![](http://jesusfuck.me/di/ZP8R/16-07-23-19-49-14-greenshot-image-editor-54x30-16-07-23-19-48-54.png)

Like our precious stop and cancel tasks button, mimicking an abort function

**Comment by Jaex** [comment]
There is difference in Greenshot buttons, both buttons there red. But you want abort button red, stop button black.
