### ISSUE TITLE
Unable to Shorten URLs

### ISSUE THREAD

**Issue by lyrixn** [ShareX/ShareX#1732]
I've set up the URL shortener for yourls.
Debug shortens the URL, so signature is valid.
Option "if clipboard contains a URL, then use URL shortener" is checked. Everything else on "Clipboard upload" is unchecked.

However when I copy a URL (any URL) it doesn't shorten it.

**Comment by Jaex** [comment]
I have configured like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/07/ShareX.vshost_xJja0Fq67U.png)

Then copied: https://github.com/ShareX/ShareX/issues/1732

and tried clipboard upload both from main window and hotkey and result was:

http://bit.ly/2afcQpJ

So not sure what is different in your settings.

**Comment by lyrixn** [comment]
Thank you for the fast response.

I have that exact setting enabled and nothing else under "Clipboard upload".

However when I CTRL + C and URL it doesn't CTRL + V it shortened. The "history" doesn't recognize any shortening going on as well.

"Debug - Test URL shortener" is successful.

Browser: Chome (sharex extension enabled).

**Comment by Jaex** [comment]
Which URL you trying? Maybe it is caused by url.

**Comment by lyrixn** [comment]
I've tried several, including https://github.com/ShareX/ShareX/issues/1732, unfortunately it doesn't shorten.

**Comment by lyrixn** [comment]
Update: I managed to set it up via hotkey. Automatic conversion doesn't work however.

**Comment by Jaex** [comment]
Nothing in debug log to give hint?

**Comment by lyrixn** [comment]
Well, the history shows the same short URL being created over and over again linking to this project no matter where I create it: https://i.zz.ee/Ps500VQ0sz.png

This is what debug logs show with hotkey shortening: https://i.zz.ee/A4tozXiBrW.png

Copying to clipboard doesn't register anything on debug.

**Comment by Jaex** [comment]
I don't understand what you trying to do. ShareX not monitors clipboard. Also not sure what you mean by "where i create".

**Comment by lyrixn** [comment]
Apologies.. I figured it out how to properly create short URLs. First I need to copy the url, then use the hotkey to produce a valid result.
