### ISSUE TITLE
Feature suggestion: ICC profiles in screenshots

### ISSUE THREAD

**Issue by Yuubari** [ShareX/ShareX#1734]
Would it be possible to embed the current ICC profile in the image files?

Below is an illustration of what happens in Chrome and Firefox (but not Edge/IE) on a Windows 10 machine with a wide gamut display. Left is untagged. Right is tagged with the currently selected system default ICC profile.

![dsc_2266](https://cloud.githubusercontent.com/assets/7750448/17051962/08bcb378-5004-11e6-8014-8f656676b984.JPG)

**Comment by Jaex** [comment]
There is no built in way in .NET framework to handle color profiles. It will require using library such as http://www.imagemagick.org which have high size and also will require to use .NET wrapper for it. So I won't like to increase ShareX size alot for this.

**Comment by Yuubari** [comment]
Apparently the [BitmapEncoder](https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.pngbitmapencoder.aspx) classes support setting a colour profile?

**Comment by Jaex** [comment]
It is for WPF apps.
