### ISSUE TITLE
File uploader Mega, upload status incorrect

### ISSUE THREAD

**Issue by YisroelAdler** [ShareX/ShareX#1737]
Hi, 

Thanks for your really really useful and great utility!

Lately, I have an issue, that when using the file uploader to upload a file to Mega, the Status and Progress indicators misbehave. For instance, when uploading a 30MB file, the progress would show something like 200KB/405KB, and the status would be 48% and that'll run until 100% and then it'll start again with a new small file size running till 100%, many times so until the whole file will be uploaded and I'll get a sharing link.

This picture is after uploading (successfully) a 26MB file to Mega.
![image](https://cloud.githubusercontent.com/assets/7387839/17066683/27b10178-5016-11e6-8f63-3e5b9ac30ea3.png)

**Comment by YisroelAdler** [comment]
Still not fixed.

**Comment by Jaex** [comment]
@gpailler

**Comment by gpailler** [comment]
You have this behavior because MegaApiClient uploads files by chunks now (gpailler/MegaApiClient#27). I'll take a look to find a way for a fix in ShareX

**Comment by gpailler** [comment]
I will implement gpailler/MegaApiClient#41 then I will propose a PR for ShareX to solve this issue

**Comment by YisroelAdler** [comment]
I see that in the new version (11.4.1) it has somewhat changed, but it is still messed up. I didn't follow it exactly, but **1)** The "/***.** KB" (the 2nd half of the progress column) does not show the file size right away but instead shows the size of the chunks from the file that were already uploaded. **2)** That is only until it reaches to 1 MB where it does not show anything higher but gets stuck till the download is finished. **2)** I think that the upload goes very slow and makes a break between uploading each chunk.

**Comment by Jaex** [comment]
This change not included in 11.4.1. I merged it after release.

**Comment by YisroelAdler** [comment]
I see. Interesting that something did got different. I'll wait for the fix to be released in coming versions.
