### ISSUE TITLE
录制屏幕没有声音？

### ISSUE THREAD

**Issue by kaeles** [ShareX/ShareX#1740]
录制屏幕没有声音(When recording a screen, Can't record sound)?
录制屏幕不能暂停(Recording screen can not be suspended)?

**Comment by Jaex** [comment]
You can record sound if you install this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/07/SystemSettings_y58aPeWAmK.png)

It is not possible to pause recording.
