### ISSUE TITLE
ShareX freezes upon attempting to upload more than 8000 images

### ISSUE THREAD

**Issue by classyjakey** [ShareX/ShareX#1741]
I'm trying to upload 8000 images in a album to Imgur using ShareX, but attempting this causes it to seize up.

**Comment by classyjakey** [comment]
Turns out pressing CTRL + A while doing this is the cause of the issue

**Comment by Jaex** [comment]
Is all images even managed to upload? Is Imgur don't have ip limit or something for such high usage in close time?

**Comment by classyjakey** [comment]
Yes it does
