### ISSUE TITLE
Choose actions after image capture [Enhancement]

### ISSUE THREAD

**Issue by iluvredwall** [ShareX/ShareX#1746]
As far as I can tell, there's currently no way to choose which actions to perform from the "after capture" window or "quick task" menu. It would make sense to add something like the quick task menu for actions: allow the user to define action sets of actions and give each action set an entry in the "after capture tasks" list

Also, there should probably be a "quick task menu settings" button with the rest of the settings buttons so users don't have to capture an image to edit the menu.

**Comment by Jaex** [comment]
For second question:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/07/ShareX_7L4EDQAi1u.png)

**Comment by iluvredwall** [comment]
Ah, thanks; I looked all over task settings but I guess I forgot to look in application settings.

**Comment by Unknow0059** [comment]
It would be nice if this were a feature.
For "Image Effects", too.
