### ISSUE TITLE
OCR defaults to English

### ISSUE THREAD

**Issue by Wilbo007** [ShareX/ShareX#1749]
Is there any way so I can set up a hotkey that will OCR in another language? 

Or perhaps have the OCR pop up with language selection before I capture, because at the moment it defaults to English, I then have to wait for it to finish, then choose another language

(sorry for my bad english)

**Comment by Jaex** [comment]
It uses last selected language.

**Comment by Jaex** [comment]
Adding check box for "auto start ocr" can solve this problem I think. So if you disable it, you can manually select language and start it yourself.
