### ISSUE TITLE
Hex Lowercase Color Picker Addition

### ISSUE THREAD

**Issue by ThomasMoonKang** [ShareX/ShareX#1751]
A lot of web designers prefer to use lowercase hex codes. Would it be possible to have $hex do lowercase letters while $HEX copies uppercase letters? Could also do $hexcaps, $hexlowercase, etc.

![image](https://cloud.githubusercontent.com/assets/8906561/17226879/ac1d5034-54d9-11e6-8a5c-6751250ab013.png)

Thank you!

**Comment by Jaex** [comment]
Indeed I was encountered this problem too when making ShareX website and later was forget to add it.

**Comment by ThomasMoonKang** [comment]
You're amazing, thank you.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/07/ShareX.vshost_yFDQ3Sacwf.png)
