### ISSUE TITLE
Streamable Upload Errors

### ISSUE THREAD

**Issue by Hakaan256** [ShareX/ShareX#1754]
Screen recordings uploaded to Streamable come up with this error:

[StreamableError.txt](https://github.com/ShareX/ShareX/files/392202/StreamableError.txt)

I'm logged in to Streamable (it didn't work anonymously either) and the video actually uploads to my account, but the URL fails to copy to my clipboard.

**Comment by Jaex** [comment]
@lawlmart should I use nullable int or string for status? Nullable int is not good idea in API because not all programming languages support it.

**Comment by lawlmart** [comment]
That's looks like a big in our api. Status should never be null, I'll check it out.

**Comment by lawlmart** [comment]
I'm going to hotfix our API so it returns 0s instead of nulls, but the StreamableStatusResponseVideo class definition should probably be limiting to our APIs official spec:

StreamableStatusResponseVideo
    {
        public string url { get; set; }
    }

**Comment by lawlmart** [comment]
Looks like that did the trick. Everything but url in the files array is undocumented and therefore subject to change so this should probably still be fixed in ShareX in the future. I'll submit a pull once I get this windows box set up.
