### ISSUE TITLE
Simple text label for Greenshot editor

### ISSUE THREAD

**Issue by Atmaks** [ShareX/ShareX#1756]
As far as I can tell, it's impossible to create a simple text label without border using Greenshot editor. The issue here is that text and border share color, so if you pick "transparent", text becomes invisible (if fill color is set to transparent). What is there to be done?

1. Make a separate property "Border color". That way a simple label can be made by setting this and "Fill color" to "Transparent";
2. Make a separate component "Label".

Which one should I use? Or maybe I'm just retarded and didn't see an obvious way to make a borderless filless label.

**Comment by Jaex** [comment]
When you asked it in IRC, I thought you were talking about region capture text label. Because you didn't mention about it was Greenshot editor.

**Comment by Jaex** [comment]
You can make line thickness: 0 to make border not visible.

**Comment by kaushal101** [comment]
> You can set line thickness: 0 to make border not visible.
Big help, works like a charm!
