### ISSUE TITLE
Having issue when trying to upload

### ISSUE THREAD

**Issue by wcalaes** [ShareX/ShareX#1758]
Hi, sorry if the problem is at my end and about my english, im having this error msg when trying to upload, i use proxy and already tried every confg possible. 
[ShareX-Log-2016-08.txt](https://github.com/ShareX/ShareX/files/397649/ShareX-Log-2016-08.txt)

**Comment by Jaex** [comment]
Can you try reinstalling ShareX.

**Comment by wcalaes** [comment]
Same thing, i also noticed that the error occur every time i open the program.
http://i.imgur.com/cvYphH6.png

**Comment by Jaex** [comment]
This is weird because nobody reported this issue before. And I don't see how it can give that error.

**Comment by wcalaes** [comment]
i think its the proxy, ill try a few things related to that and try to fix it, anyway thanks for your attention

**Comment by Jaex** [comment]
I don't think it is proxy.

**Comment by wcalaes** [comment]
ok, i found the same problem clicking on task settings...
