### ISSUE TITLE
No hotkeys are working

### ISSUE THREAD

**Issue by DeveloperRyan** [ShareX/ShareX#1760]
Some reason whenever I try using any of my hotkeys, none of them work. They're all default, and I've checked that no other program is using them. I do not have Dropbox nor OneDrive and am running Windows 7. The only way to take a screenshot with region capture is opening my system tray and clicking the tray icon using my middle mouse button; Otherwise, whenever I press it nothing happens.

I've tried both the desktop and steam version, and I've attempted to reinstall multiple times, but nothing's helped. I love ShareX so much and I don't want to use an alternate software. If someone could help me out I would appreciate it so much.

**Comment by Jaex** [comment]
Did you tried changing hotkeys. If some hotkeys work and some not (printscreen ones) that means another software in your pc registered printscreen hotkeys already and ShareX can't register them.

**Comment by Infinitylsx** [comment]
@Jaex I did, I tried things that I know werent used by other programs like ctrl alt shift T and such, but none seemed to work.
