### ISSUE TITLE
My screen capture select area suddenly turned into an annoying ellipse?

### ISSUE THREAD

**Issue by benanderson1** [ShareX/ShareX#1762]
![Example](http://i.imgur.com/YTro5fj.png)
![Better example with dark background](http://i.imgur.com/FXn2mKR.png)

Why did this happen and how can I change it back to the regular rectangle that I'm used to? I did not change any settings and tonight it suddenly changed to this ellipse.

Thanks for any help

**Comment by Jaex** [comment]
Right click in region capture.

**Comment by RK204800** [comment]
<img width="443" alt="NinjaTrader_gTwhYBFlfu" src="https://user-images.githubusercontent.com/98921786/152249044-ed40aaf4-4766-4fcc-89f3-7b15cc866182.png">

**Comment by RK204800** [comment]
From Task settings>Advanced - select True as in image
