### ISSUE TITLE
When there is no internet connecntion, and you reply "Yes" for downloading the missing ffempg.exe

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1764]
Not the expected behavior.

**Comment by lithium720** [comment]
To add to that, it just hangs at this window: https://i.lithi.io/C5Mw.png

**Comment by Jaex** [comment]
It is not possible to find internet connection status 100% correctly without send request to for example Google to check internet connection: http://stackoverflow.com/questions/2031824/what-is-the-best-way-to-check-for-internet-connectivity-using-net

And I don't want to do that so frequently just to be able to detect internet connection status.

Using `InternetGetConnectedState` etc. is not always gives correct results. This is why I didn't add internet connection checks to any stuff like this.
