### ISSUE TITLE
 Log file - put a -------- line after "ShareX closing" line

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1765]

**Comment by lithium720** [comment]
This is entirely a personal preference.

But maybe just an extra line break after ShareX closing would be preferable to easily see the breaks between ShareX sessions.

**Comment by Jaex** [comment]
Some people could prefer to not have inconsistent syntax in log file, like if they are parsing it etc.

You can search "ShareX closing" in any text editor from bottom to up to find all instances of ShareX closing.
