### ISSUE TITLE
CLI video encoder file does not exist

### ISSUE THREAD

**Issue by Primeey** [ShareX/ShareX#1767]
I'm trying to do a screen recording but I get this error http://i.imgur.com/UY5vluh.png. So I manually download x264 and put it in the folder in the error but it will only give me a gif when I finish capturing. Does ShareX not let you capture in video format like mp4?

**Comment by Jaex** [comment]
Why are you using CLI encoder?

**Comment by Primeey** [comment]
Your program says I need it if I want to screen record

**Comment by Jaex** [comment]
Because you enabled it. Without enable it program not says you need it.
