### ISSUE TITLE
Transparency lost when copying to clipboard in greenshot window

### ISSUE THREAD

**Issue by gpion** [ShareX/ShareX#177]
When editing images In built-in greenshot editor window, "effect->drop shadow" add a semi transparent shadow border.

In images uploaded using the "upload image" icon, transparency is kept (example: http://i.imgur.com/dSWisUr.png)

It's also OK inside files saved with the "save image as" button (providing we are using an image format supporting alpha channel, like png)

But, on image copied to clipboard using the "copy to clipboard" icon, transparency is lost.

(Note: this works when using the standalone "GreenShot" application)

**Comment by jampy** [comment]
> Reason is default .NET clipboard image copy method not supports transparency. But you can use alternative method which copying png to clipboard: https://dl.dropboxusercontent.com/u/14076298/ShareX/2014/06/ShareX_nImuwQKRoB.png so transparency will be preserved.

The link unfortunately does not work anymore.

Can anyone explain the "alternative method" here please?
