### ISSUE TITLE
CLI: Wait for upload and get exit code

### ISSUE THREAD

**Issue by Yanikore** [ShareX/ShareX#1770]
It would be good to have a command line switch that allows us to wait for the upload task to finish.

That way we can use it in scripts and do something with the original file after it's uploaded.

Including an exit code would allow us to make custom events based on the status of the upload as well.

**Comment by Jaex** [comment]
-autoclose isn't similar to what you want?

**Comment by Yanikore** [comment]
No. I mean this: http://i.imgur.com/kDst5f3.gif
As you can see it does not wait for the uploaded file to finish.

**Comment by Jaex** [comment]
I'm not planning to make console ShareX build.
