### ISSUE TITLE
ctrl (or alt-gr) + enter to tweet (or social media share in generally)

### ISSUE THREAD

**Issue by LoosGuccreen** [ShareX/ShareX#1773]
Very simple request: Be able to tweet using ctrl + enter from the tweet window.

Quite all the twitter apps allow to do that (even twitter itself), so suddenly not being able to do it is a bit odd.

It is really not a big deal but it would be more comfortable.

**Comment by Jaex** [comment]
I checked now it already tweets with ctrl + enter?
