### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by Hituh** [ShareX/ShareX#1775]
I have a few seconds delay while taking ss. Happening on Puush and on ShareX.

**Comment by lithium720** [comment]
Then It sounds like you have a problem on your end that isn't an issue with ShareX.

**Comment by Hituh** [comment]
So do you knot how to repair it?

**Comment by lithium720** [comment]
This is not a place to ask such questions was my point. This is to fix bugs / issues with ShareX.

**Comment by Hituh** [comment]
Where i'm supposed to ask?
