### ISSUE TITLE
Window going to the background

### ISSUE THREAD

**Issue by xaviex** [ShareX/ShareX#1777]
When you have a snapshot set to automatically open in the image editor then click print, the print prompt displays in the background.

**Comment by Jaex** [comment]
Now when testing I can't even make print dialog even stay in background. Which print prompt you talking about?

**Comment by xaviex** [comment]
![image](https://cloud.githubusercontent.com/assets/1398878/175
![image](https://cloud.githubusercontent.com/assets/1398878/17597145/916b9004-5fc2-11e6-95be-281f317f7ac4.png)
97092/58f099cc-5fc2-11e6-80e3-b1c37c54203e.png)
This, after enabling auto open edit

**Comment by Jaex** [comment]
Oh you talking about that print dialog, I thought Windows print dialog.
