### ISSUE TITLE
Rounded corners of screenshots?

### ISSUE THREAD

**Issue by anders1122** [ShareX/ShareX#1778]
I've been trying to figure out how I enabled this on my own, but haven't found a solution yet.
http://i.imgur.com/JrLyJlx.png

**Comment by Jaex** [comment]
Right click in region capture.

**Comment by anders1122** [comment]
Thank you so much.

**Comment by Doge117** [comment]
Thanks!

**Comment by Jaex** [comment]
Is this accidental region mode changes happening using <kbd>mouse wheel</kbd> right?
I'm planning to swap it with <kbd>ctrl + mouse wheel</kbd> so instead it will just resize magnifier.

**Comment by YasseenDeHerdt** [comment]
Thank you so much. I love ShareX :+1:

**Comment by anders1122** [comment]
I feel like it was most likely me accidentally using my mouse wheel, because I had not messed with it using right click in the past at all before this happened to me.

**Comment by m-ndstorm** [comment]
Maybe im a lame, or some issue with the traduction of myGUI,. bit i cant find:

> Right click in region capture and select "Region: Rectangle".
--> this 🙈

**Comment by m-ndstorm** [comment]
YAAAAY. After enabling the hotkey tooltips I found that the NUM 0 changes the shape, after I performing the hotkeys for "rectangle" capture!
Problem solved!
 BY THE WAY, I love this product, I think I will be your patron.

**Comment by Jaex** [comment]
Normally you select it from toolbar:

![](https://jaex.getsharex.com/2017/10/ShareX_m93tDxgY20.png)

and if it is rounded rectangle then:

![](https://jaex.getsharex.com/2017/10/ShareX_qYtQYlXP3Q.png)
