### ISSUE TITLE
Change extension for text uploaded from buffer [enhancement]

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#1780]
Please allow change extension before text uploaded when local FTP used. In buffer can be text, CSV, markdown, ini, XML, json, code examples and when it saved by default as txt it is not properly highlighted by advanced text editors in good case or not readable in bad case because opened in notepad instead specific software.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/08/ShareX_gyFCbCYO0h.png)

**Comment by QuAzI** [comment]
That is default extension but it not solve quick extension changing. It is used many times per day for very different targets when this feature used like pastebin and any time change settings too excessive in this case.

![change_extension_for_text_uploaded_from_buffer_ en_firefox_2016-08-12_16-44-25_dzfkknms](https://cloud.githubusercontent.com/assets/1897605/17624358/f59a084a-60ac-11e6-9f2e-ed6bde6c4ebb.png)
