### ISSUE TITLE
Chrome extension not working after clearing chrome's session data with ccleaner

### ISSUE THREAD

**Issue by xates** [ShareX/ShareX#1785]
Chrome extension downloaded and support enabled in the application but no context menu entry is showing in chrome :(
![sharex_2016-08-14_02-50-20](https://cloud.githubusercontent.com/assets/17145424/17646447/0d1cd2f4-61ca-11e6-9e9e-a7bb0fb6dfca.png)
![chrome_2016-08-14_02-51-18](https://cloud.githubusercontent.com/assets/17145424/17646448/130c44c4-61ca-11e6-82b7-598dca3678bf.png)

**Comment by Jaex** [comment]
Are you sure Chrome extension is enabled in Chrome?

**Comment by xates** [comment]
100%
![chrome_2016-08-14_02-54-23](https://cloud.githubusercontent.com/assets/17145424/17646464/a0b29314-61ca-11e6-9843-091c02ecbf62.png)

**Comment by Jaex** [comment]
When you right click image in this page, is it not shows too?

**Comment by xates** [comment]
Correct, in no page...

**Comment by Jaex** [comment]
I have no idea how it is possible. Nobody reported such thing before.

**Comment by xates** [comment]
That's strange to me too because it's a clean install of windows 10 with just chrome sharex and a few apps just installed and nothing more that could interfere... :/

**Comment by xates** [comment]
Ok, I found more information about what causes the problem:
I tried to uninstall and reinstall the extension and it worked.
Then after closing the browser and running ccleaner the extension stopped working like above.
So there is something with ccleaner that breaks the extension...
P.S. Clearing browsing data from chrome does nothing instead

**Comment by xates** [comment]
Ok, I have found the specific setting: it happens when clearing **session** data

**Comment by Jaex** [comment]
So problem not to do with ShareX.

**Comment by xates** [comment]
Well, actually clearing session data does not (and should not) affect
**any** other chrome extension I know so there's probably something inside
this extension that works with sessions while shouldn't

Il 14/ago/2016 03:48, "Jaex" <notifications@github.com> ha scritto:

**Comment by Jaex** [comment]
There is nothing about session data in its very simple codes: https://github.com/ShareX/ShareX_Chrome/blob/master/ShareX_Chrome/Chrome/eventPage.js

**Comment by xates** [comment]
I see... That's really, weird! I will try to contact piriform then
