### ISSUE TITLE
Different upload path per type

### ISSUE THREAD

**Issue by Phyxion** [ShareX/ShareX#1786]
Is it possible to have a different upload path per file type? 
I'm using Box but can switch to something else (preferably not FTP) if that works.
For example, I want the screenshots in /screenshots and files in /files.
Or is it perhaps possible to add another Box account with a different path?

**Comment by Jaex** [comment]
It is not possible in current ShareX.

**Comment by elvis1** [comment]
hi, still not possible?

**Comment by ilkekaratas** [comment]
Berk , I need that multiple upload feature as well. By the way I donated last year first time in my life. 

https://goo.gl/Vjum8P :D ( Ayrıca, tebrik ederim iyi iş çıkarıyorsun.)
