### ISSUE TITLE
Custom BBCode

### ISSUE THREAD

**Issue by Lemonadez** [ShareX/ShareX#1787]
Can you guy add a Custom Setting where anyone can add Manually a BBCode?

Example: [spoiler][img]URL LINK[/img][/spoiler]

After Upload Task -> use Copy Custom BBCode?

Because Im a forum poster and I use this program. It just that if there a way it can reduce typing 
[spoiler][img] ctrl+v [/img][/spoiler]. 

After Upload Task -> Only had Copy URL, So i use ctrl+v after typing [spoiler][img].
http://i.imgur.com/TbEwKqT.png

**Comment by Jaex** [comment]
It is already exists:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/08/ShareX_9gJBBLoMLN.png)

**Comment by regs01** [comment]
Is it possible to change bb codes themself? Not after upload copy, but ctrl+c. I usually upload multiple images, then copying them one-by-one with ctrl+c or via copy->bb code image+link.
