### ISSUE TITLE
Add Dropbox under Image Uploaders

### ISSUE THREAD

**Issue by e58** [ShareX/ShareX#1788]
https://dl.dropboxusercontent.com/u/10011842/Screenshots/ShareX/2016/August/ss.png

I'm aware that you can add Dropbox using _Destinations_ > _Image uploaders_ > _File Uploader_ > _Dropbox_, but this could be inefficient if users would want to upload screenshots and files to different Dropbox paths.

Something like this would be nice:
Image uploaders > Dropbox > Upload Path:
_Public/**Screenshots**/ShareX/%y/%mon2_

File uploaders > Dropbox > Upload Path:
_Public/**Files**/%y_

**Comment by Jaex** [comment]
Adding duplicate tabs in destination settings window is horrible idea.
