### ISSUE TITLE
ShareX  region doing ovals?

### ISSUE THREAD

**Issue by DiniOG** [ShareX/ShareX#1790]
Sharex was working perfectly fine before I left on my weekend trip and when I came back I noticed my hotkey for sharex is making ovals. I haven't changed anything nor does sharex have an update and it's making ovals every time I screenshot. http://i.imgur.com/GQhjO7n.png

I have changed it numerous times, tried just normal right clicking on task and it does the exact same. I have no clue why it is doing this and cannot find anywhere that says how to fix.

**Comment by Jaex** [comment]
#1778

**Comment by DiniOG** [comment]
Bless
