### ISSUE TITLE
Region capture - Mouse click actions

### ISSUE THREAD

**Issue by Chefkeks** [ShareX/ShareX#1793]
Hi there,

came across to share an idea how to improve ShareX and I hope you'll like and implement it.

Currently I've several hotkeys for capturing regions and I always need to use the correct hotkey for triggering a specific workflow - two of the hotkeys I use in 90% of all screenshots and I'd like to reduce this to a single hotkey since I run several other programs which have hotkeys already and so I'd be happy top reduce the hotkeys for ShareX. To achieve this I think it'd be great to add further options to the "mouse click options" for region capture. Currently when taking a screenshot I can double left click (or hit enter) to process in my workflow with the defined after capture/upload actions. 

Instead of choosing the workflow with the hotkey I think it'd be great to just have one hotkey and allow the selection of the workflows via the "mouse click action". I hope you understand already what I want, but in case not and to make this a bit better understandable, a little example comparing how it is currently and how it could be:

How it is currently:
Hotkey 1 for capturing a region (e.g. CTRL + 1) -> Double left click -> Hotkey 1 workflow (e.g. Copy image to clipboard, Save to file)
Hotkey 2 for capturing a region (e.g. CTRL + 2) -> Double left click -> Hotkey 2 workflow (e.g. Show quick task menu)
Hotkey 3 for capturing a region (e.g. CTRL + 3) -> Double left click -> Hotkey 3 workflow (e.g. Upload image to host, Delete file locally)
Hotkey 4 for capturing a region (e.g. CTRL + 4) -> Double left click -> Hotkey 4 workflow (e.g. Print image, Save image to file as...)

How it could be / my suggestion:
Hotkey 1 for capturing a region (e.g. CTRL + 1) -> Double left click -> Default workflow (e.g. Copy image to clipboard, Save to file)
Hotkey 1 for capturing a region (e.g. CTRL + 1) -> Middle click -> Alternative workflow (e.g. Show quick task menu)
Hotkey 1 for capturing a region (e.g. CTRL + 1) -> Mouse 4 click -> 2nd alternative workflow (e.g. Upload image to host, Delete file locally)
Hotkey 1 for capturing a region (e.g. CTRL + 1) -> Mouse 5 click -> 3rd alternative workflow (e.g. Print image, Save image to file as...)

Personally for me I think you'll disagree with that suggestion since it would kinda break up the whole workflow as it currently is, but having the option to "show the quick task menu" (e.g. when using middle click) would already help me a lot and could really be a great enhancement for the mouse click actions. So you could normally do a double left click when capturing to e.g. "Copy image to clipboard, Save to file" and when a different workflow should be done, a middle click when capturing could bring up the "quick tasks menu" and an alternative workflow could be started there ;)

Would like to hear you opinion about that suggestion :)

Cheers!
Michael

**Comment by Jaex** [comment]
I can't add two different setting enums to single dropdown menu. Coding wise it is very ugly and unusual way to accomplish it. So I'm not planning to do that.

**Comment by Chefkeks** [comment]
@Jaex 
Totally understand. But what about just adding the "Show quick task menu" - from there selecting the further workflows would be possible and it'd be just a single setting in the dropdown.

**Comment by vatterspun** [comment]
> I hope you understand already what I want, but in case not and to make this a bit better understandable, a little example comparing how it is currently and how it could be:

For reference, you might want to look into mock-up tools to describe what you're putting down here.  Complex feature requests generally need something visual or (ideally) some kind of basic animation.  I actually really like PowerPoint for this, but there are a ton of programs out there.

**Comment by Chefkeks** [comment]
@vatterspun
Get your point and I'm very familiar with a popular mockup tool (balsamiq), so I totally know what a (visual) difference it is between telling and showcasing an idea ;)
So when I find the time I'll consider making a mockup.
