### ISSUE TITLE
Scrolling Capture Problem

### ISSUE THREAD

**Issue by mertmd** [ShareX/ShareX#1794]
Hey, I'm having an issue about capture with scrolling. 
Maximum Scroll Count doesn't change. I'm trying to set it as 200 but it turns back to default value which is 100. 

![sharex_2016-08-18_15-00-27](https://cloud.githubusercontent.com/assets/9222621/17773023/bf3e836e-6554-11e6-9712-95f2fcf69784.png)
![sharex_2016-08-18_15-01-02](https://cloud.githubusercontent.com/assets/9222621/17773024/bf3f844e-6554-11e6-9989-66f76a605327.png)
![sharex_2016-08-18_15-01-19](https://cloud.githubusercontent.com/assets/9222621/17773025/bf41ef22-6554-11e6-8012-1defed3a3560.png)

**Comment by Jaex** [comment]
#1275
