### ISSUE TITLE
I need `-Exit_If_Running` Command Line Argument

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1795]
It's good for Start/Exit (=On/Off) ShareX, by the same Hotkey.

**Comment by Scrxtchy** [comment]
can't you use ```taskkill /f /im ShareX.exe```
or is there a special case which requires it to be run with the sharex executable as the zero parameter?

**Comment by Stamimail** [comment]
@Scrxtchy 
You are talking about -Exit option, but I'm talking about -Exit_if_running switch, that means to be able to launch and exit Sharex by the same .lnk

**Comment by Jaex** [comment]
Create batch file to do it?

**Comment by Scrxtchy** [comment]
```tasklist /nh /fi "imagename eq sharex.exe" | find /i "sharex.exe" > nul && (command if open) || (command if closed)```

**Comment by Stamimail** [comment]
1. Are you telling me that by a batch file `-Exit_If_Running` can be made for any app? (It will be great)
2. What about the INI and settings files that needs to be saved in Exit. What about app such as MS Word, You can't kill it just like that, you need to exit properly from all opened documents?

**Comment by Jaex** [comment]
1. Yes.
2. I don't know batch but I'm sure there must be way to send application exit command without kill process.

**Comment by Scrxtchy** [comment]
Can't do it with batch directly, need to use a wscript host

**Comment by Stamimail** [comment]
How can I get help with this? I'm not a programmer.

**Comment by Stamimail** [comment]
I asked someone with knowledge. He said your claim is impossible.
So, this feature has to be within the program.

**Comment by Jaex** [comment]
I never saw any software have exit if running cli command before. It is weird to run process with command just to be able to close it.

**Comment by Scrxtchy** [comment]
![](https://jii.moe/EyMzvBSZz.png)

![](https://img.shields.io/badge/works-on%20my%20machine-green.svg)

**Comment by Scrxtchy** [comment]
```
tasklist /nh /fi "imagename eq sharex.exe" | find /i "sharex.exe" > nul && taskkill /im "sharex.exe" || D:\Scratch\Documents\Github\ShareX\ShareX\bin\Debug\ShareX.exe
```

This is what you want in your opening post, based on my own sharex install location
for configs being saved, we aren't forcing a close with /f in taskkill, so a clean `WM_CLOSE` is sent to the program to close safely

**Comment by Stamimail** [comment]
Oh, It's realy nice feature.
It's for users that use the program medium frequency, and don't need the program run always in background.
e.g: Call the program with Ctrl+Alt+S, Capture and Upload and Get a link, Ctrl+Alt+S again for Exit.

Programs with such a feature:
Don't Sleep - (DontSleep_x64.exe exit)
Textify - (Textify.exe -exit_if_running -hidewnd)

**Comment by Stamimail** [comment]
Scrxtchy,
I place the following code in a bat file and placed the .bat in the Sharex folder. It is only run but not exit.
Can you please post here the full code. thanks.
`tasklist /nh /fi "imagename eq sharex.exe" | find /i "sharex.exe" > nul && taskkill /im "sharex.exe" || ShareX.exe`

**Comment by Scrxtchy** [comment]
```
C:\Users\Scratch>taskkill /im "sharex.exe"
SUCCESS: Sent termination signal to the process "ShareX.exe" with PID 6776.
```

Unsure how it wouldn't work, you can try running taskkill on it's own and see what's up

**Comment by Stamimail** [comment]
I found it does work only if I run the .bat twice without using Sharex.
Once I'm using Sharex, close it, and it sitting in my system tray, it won't work.

>[Another thing you need to remember, it should work even if the program is running in background, in the system tray.]

**Comment by Scrxtchy** [comment]
and it does
https://www.youtube.com/watch?v=gnW7fhCy4MU

**Comment by Jaex** [comment]
Why don't you use `-autoclose` ?

**Comment by Stamimail** [comment]
>and it does
>https://www.youtube.com/watch?v=gnW7fhCy4MU

Yes. You right.
Now, Please disable "On start minimize to tray" in appication settings.
Run again Sharex, close it (so it run in system tray), and then try your
code, and you will see.
BTW, I'm using now ShareX 11.2.1 Portable

>Why don't you use -autoclose ?
What's mean. I'm looking for closing by demand.

2016-11-16 16:34 GMT+02:00 Jaex <notifications@github.com>:

**Comment by Scrxtchy** [comment]
It is
I'm not dense

**Comment by Stamimail** [comment]
I downloaded the new version. I get the same thing also with taskkill /im "sharex.exe".
It just write SUCCESS but no exit.
If you ensured you close all things related to sharex except the system tray icon, and it works for you, do you have an idea why it doesn't work for me?

```
T:\ShareX-portable>tasklist /nh /fi "imagename eq sharex.exe" | find /i "sharex.
exe" > nul && taskkill /im "sharex.exe" || "T:\ShareX-portable\ShareX.exe"
SUCCESS: Sent termination signal to the process "ShareX.exe" with PID 5184.

T:\ShareX-portable>tasklist /nh /fi "imagename eq sharex.exe" | find /i "sharex.
exe" > nul && taskkill /im "sharex.exe" || "T:\ShareX-portable\ShareX.exe"
SUCCESS: Sent termination signal to the process "ShareX.exe" with PID 5184.

T:\ShareX-portable>tasklist /nh /fi "imagename eq sharex.exe" | find /i "sharex.
exe" > nul && taskkill /im "sharex.exe" || "T:\ShareX-portable\ShareX.exe"
SUCCESS: Sent termination signal to the process "ShareX.exe" with PID 5184.

T:\ShareX-portable>taskkill /im "sharex.exe"
SUCCESS: Sent termination signal to the process "ShareX.exe" with PID 5184.

T:\ShareX-portable>taskkill /im "sharex.exe"
SUCCESS: Sent termination signal to the process "ShareX.exe" with PID 5184.

T:\ShareX-portable>taskkill /im "sharex.exe"
SUCCESS: Sent termination signal to the process "ShareX.exe" with PID 5184.

T:\ShareX-portable>
```

**Comment by Stamimail** [comment]
Any news?
