### ISSUE TITLE
Auto update message box "Yes" button does not work

### ISSUE THREAD

**Issue by Jaex** [ShareX/ShareX#1796]
Due to a bug in the previous release (v11.1.0) clicking "Yes" in the auto update message box does not start the update process. Please click "About..." from the main window and click the update link at the top to start the update process. We are sorry for the inconvenience.

![](http://i.imgur.com/7qH6X1f.png)

**Comment by Puremin0rez** [comment]
Thanks. Unfortunately now I bet a lot of people will be stuck on the previous release :(

**Comment by dimon222** [comment]
Actually, if you press "Yes" in dialog it wont just don't download it, but will also break ShareX so you cant snap anything till you restart it.

**Comment by Jaex** [comment]
What you mean you can't snap anything?

**Comment by dimon222** [comment]
Hotkey or click on ShareX icon won't open rectangle tool to make a screenshot.

**Comment by Jaex** [comment]
When you press "Yes" it just acts like "No" so it is not supposed to create any issues. Also it not make sense how it can disable such things. I pressed "Yes" now and all works fine.

**Comment by Dragas** [comment]
I can confirm. Pressing yes and afterwards rightclicking the icon in notification area causes sharex to become not responding in v11.1

**Comment by sneak310** [comment]
This has been happening to me as well for a few days now. It frequently pops up a prompt asking if I want to update and whenever I press yes the popup just disappears and nothing ever happens.

Not having any issues with the program not responding or losing functionality.

**Comment by Soulflare3** [comment]
Thanks for posting this, I was getting confused why ShareX asked to update every time I booted Windows, and I know I hit that "yes" button multiple times. Updated fine from About dialog. :+1: @Jaex

**Comment by dmxt** [comment]
Took me a while to realize this. Can't imagine thousands of people who don't realize this, ouch.

**Comment by inspector71** [comment]
Wow, this is a killer bug. Oh well. Workaround sorted I guess.

**Comment by litruv** [comment]
And I've been annoyed at the update every day... I'm sure glad I googled about what was happening.
