### ISSUE TITLE
Images appear corrupted on upload

### ISSUE THREAD

**Issue by TNTUP** [ShareX/ShareX#1797]
Hi, I've updated ShareX today and when I take a screenshot the image is corrupted, Is it due to my ISP or computer? I've tried rebooting another PC and it still happens. Would uninstalling/reinstalling will fix it?

Here's a proof like this one: http://i.qcfb.ca/20160819023320.png In FireFox the image wont load due it contains errors but chrome loads it but incomplete. I've downloaded the file from my webserver and it appears corrupted. It cannot be my webserver, nothing has changed since :/ 

Tried downgrading, didn't work... I guess my installation of ShareX is now corrupted?

Tried uninstalling, no luck

EDIT: Changed buffer setting and it appears solved huh.. I've left it to 512KB and I had no issues since today.... Still happens with larger png images, I guess setting at 1KB Buffer size would solve my issue... Why uploading uses 256kb/s upload? Thats why I've increased the buffer size :/

EDIT2: Still buggy, idk why it does that... never happened

**Comment by Jaex** [comment]
Is local saved image corrupt too?

**Comment by TNTUP** [comment]
Nevermind, setting back to 32kb buffer appears to be fixed.... That's strange, it never happened in the past.... Was always at 512Kb....

The local file isn't, while uploading is. Probably either the buffer size idk not supported by the SFTP protocol?

**Comment by TNTUP** [comment]
Setting to 32kb buffer size does not happen (I hope!, it does upload at 800kb+/s so thats fine), but if higher/lower it happens (I tested 1, 4, 8, 512, 1MB, 2MB etc..)

**Comment by Jaex** [comment]
What buffer size to do with corrupt upload.

**Comment by Techbot121** [comment]
this also happened to me at higher buffer sizes, setting it down to 32kb fixed it.

**Comment by Jaex** [comment]
Was this issue always exist and nobody reported it or new SFTP library update caused it?

**Comment by Techbot121** [comment]
nope it just happened after the recent update.

**Comment by TNTUP** [comment]
@Jaex Same as Techbot, Probably the SFTP lib you say (that's I use since 2012) and its the first time I see that issue xD

**Comment by Jaex** [comment]
Try downloading previous version portable (https://github.com/ShareX/ShareX/releases/download/v11.1.0/ShareX-portable.zip) and copy `Renci.SshNet.dll` file from it to your ShareX folder to replace new one. That way you can test is new library causing it.

**Comment by TNTUP** [comment]
Permission Issue? I've replaced the file with the portable one

System.IO.FileLoadException: Impossible de charger le fichier ou l'assembly 'Renci.SshNet, Version=2016.0.0.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106' ou une de ses dépendances. La définition trouvée du manifeste de l'assembly ne correspond pas à la référence de l'assembly. (Exception de HRESULT : 0x80131040)
Nom de fichier : 'Renci.SshNet, Version=2016.0.0.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106'
   à ShareX.UploadersLib.FileUploaders.SFTP.Dispose()
   à ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   à ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   à ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
Replacing with old dll not always work :(

**Comment by TNTUP** [comment]
I've replaced the file (I was lazy to reinstall and didn't do a backup dll) within the recent portable zip file and buffer size was at 64 and still buggy, Reverting to 32kb fixes it. Is it Renci.SshNet's side then?

**Comment by Jaex** [comment]
If it were to do with ShareX then normal uploads would corrupt too because using same transfer method.

**Comment by TNTUP** [comment]
Atleast the workaround is setting the buffer size to 32 :)

**Comment by Nathanael-Mtd** [comment]
Same problem with FTP, and I confirm about the workaround, it works fine with 32kb.

**Comment by Jaex** [comment]
Nothing changed in SFTP codes and only SFTP library updated which means problem can't be to do with ShareX.

**Comment by TNTUP** [comment]
If you have a linux serveur with SFTP/SSH server you can, setting your webserver to point a directory. Though this is not my application (ShareX) Idk if they would fix on their side.

**Comment by Jaex** [comment]
I don't have any server. I always implement FTP, SFTP stuffs blindly without be able to test them.

**Comment by Nathanael-Mtd** [comment]
I confirm problem is linked to SSH.NET. The only one solution for now if going back to the old version or make a report in SSH.NET GitHub.

**Comment by TNTUP** [comment]
@Nathanael-Mtd I did a report, but if tecky dev stuff I cannot answer xD

**Comment by Nathanael-Mtd** [comment]
@TNTUP Nice, btw if you want the new version without the problem of buffer > http://l.i4g.me/ShareX-11.2.1-setup.exe

**Comment by TNTUP** [comment]
@Nathanael-Mtd Thanks! Although I've set the buffer to 32kb and i dont remember why its use XD (too lazy to read the docs)

@Jaex I've opened up an issue on their bug tracker what they can do XD if they say tricky stuff I couldn't answer since thats not my software :)

**Comment by Jaex** [comment]
@TNTUP GitHub automatically linked that issue with this issue so I will receive emails when there is new messages in that issue too.

**Comment by TNTUP** [comment]
Ahh nice, didn't knew that. Like if I mention your name it automatically notify you? Sweet XD Sorry for those "double mention" xD

**Comment by Jaex** [comment]
Yes.

**Comment by TNTUP** [comment]
The dev responded he will probably fix it this weekend, bugfix next weekend :D

**Comment by jasondavis** [comment]
Where can I set the buffer size?

**Comment by Nathanael-Mtd** [comment]
@jasondavis In application parameters I think. But you can use my build instead if you want (7 posts before)

**Comment by jasondavis** [comment]
@Nathanael-Mtd Thanks.  BTW does your version simple change that 1 buffer setting value or it does other things too?  Thanks

**Comment by Nathanael-Mtd** [comment]
No, just I just made a version without the problem on old SSH.NET build. There are also a build with the new SSH.NET build, but I didn't uploaded yet.

On Wed, Sep 07, 2016 at 9:39 PM, Jason Davis < notifications@github.com [notifications@github.com] > wrote:
@Nathanael-Mtd [https://github.com/Nathanael-Mtd] Thanks. BTW does your version simple change that 1 buffer setting value or it does other things too? Thanks

**Comment by RenanGBarreto** [comment]
I just confirm that this bug exists on a preinstalled Windows 10 64bits machine.
Changing the buffer to 32kb solves the issue.

**Comment by Jaex** [comment]
Returning to SSH.NET.2014.4.6-beta2 until new build release.

**Comment by Jaex** [comment]
After 3 years finally non beta build which don't have this bug.

![](https://jaex.getsharex.com/2017/10/chrome_uU7FVbcLCd.png)
