### ISSUE TITLE
Clipboard Bug

### ISSUE THREAD

**Issue by fumetsuu** [ShareX/ShareX#1798]
After taking a screenshot with any kind of tool, sometimes the image doesn't copy to clipboard or the co ordinates are copied instead X:342 Y:216 for example (or smth like that). This has been happening for quite a while and to fix it, I have to reinstall ShareX each time.
It's kinda annoying, but I appreciate ShareX a lot. If there's a fix I'll be happy, if not, I can live with it.
Thank you!

**Comment by Jaex** [comment]
Coordinates will copy to clipboard if you press ctrl + c while region capture is open. I don't see how it can copy otherwise.

**Comment by fumetsuu** [comment]
Thanks for the quick reply! Never knew that ctrl + c copies the co-ords, although I don't remember purposely pressing ctrl + c. I'll continue to use ShareX and next time if it happens again I'll remember what I did to make not copy to clipboard.
