### ISSUE TITLE
Encountering Error When Inserting Captured PNG Image in Paint.NET as an Action

### ISSUE THREAD

**Issue by GregoryProvost** [ShareX/ShareX#1799]
Suddenly, as of ShareX version 11.2.1, I am encountering the error message "The image type is not recognized, and cannot be opened." when capturing a PNG image and inserting it directly into Paint.NET using the defined Actions in ShareX. This has been working without issue in all past versions of ShareX that I have ever used. This issue does not occur when I revert to the previous version of ShareX that I was last using, which is version 11.1.0.

**Comment by Jaex** [comment]
Long time ago I was using %filepath% but years ago I was changed it to %input (with %output) and was still allowed old %filepath%. In this release I removed old format support. So you need to replace %filepath% args with %input for it to work.

**Comment by GregoryProvost** [comment]
Jaex:

Thank you very much. Replacing %filepath% with %input has resolved the
issue.

Sincerely,

Gregory Provost
Business Analyst - Quality Systems
Americas IT, Industrial Systems

Lafarge Canada Inc.
334 Avro Avenue, Pointe-Claire, Quebec  H9R 5W5
Office: 438-265-1039 / 514-428-7300 x2651039
Mobile: 514-893-1293  Fax: 514-221-4685
email: greg.provost@lafargeholcim.com <greg.provost@lafarge-na.com>,
NA-M-A-IS-QIMS

For immediate IT support contact
360 Support:1-844-360-6360

*A Member of LafargeHolcim*

*CONFIDENTIALITY NOTICE* This message is intended exclusively for the
person to whom it is addressed.  This communication may contain information
that is proprietary, privileged, confidential and/or legally exempt from
disclosure.  If you are not the named addressee, you are not authorized to
read, print, retain copy or disseminate this message or any part of it.  If
you have received this message in error, please notify the sender
immediately by e-mail and delete/destroy all copies of the message.
*AVIS DE CONFIDENTIALITÉ*  Ce message est destiné exclusivement à la
personne à qui il est adressé.  Cette communication peut contenir de
l'information privilégiée, confidentielle et/ou exempte de divulgation aux
termes des lois applicables.  Si vous n'êtes pas le destinataire, vous
n'êtes pas autorisé à lire, imprimer, conserver, copier ou disséminer ce
message, en tout ou en partie.  Si ce message vous est parvenu par erreur,
veuillez en aviser l'expéditeur immédiatement par courriel et effacer ce
message.
