### ISSUE TITLE
Problem region capture/selection

### ISSUE THREAD

**Issue by DabForJesus** [ShareX/ShareX#1800]
I have a problem with region capture where bottom chunk of the screen is not affected so it just runs like normal while the rest is still and works fine.
![2016-08-19_20-42-11](https://cloud.githubusercontent.com/assets/21128027/17815634/a36bda4c-664e-11e6-9242-1a8564ec43a5.png)

[https://my.mixtape.moe/mwakii.png](url)

**Comment by Jaex** [comment]
Unfortunately I'm not be able to reproduce it. Not sure why it happens in your pc.

**Comment by piyo-gh** [comment]
I have the same problem. 
My monitor is 1920x1080, but height of region capture window is always 997 pixel.
So, I must resize window manually to cover whole monitor's region.

This is very annoying now, because image editor also use this window.

**Comment by howar31** [comment]
I have exactly the same problem here.
1920x1080 on Windows 7 Pro 64-bit, ShareX 11.2.1

I cannot select the bottom of the screen since ShareX was cut off and I will click through if I try to select any region at the bottom of the screen.

![image](https://cloud.githubusercontent.com/assets/880459/18620901/b6453f5c-7e4d-11e6-9b35-c461b57e95d3.png)

**Comment by Jaex** [comment]
Both of you looks using same Windows version, something must be similar in your both of your pc which causing this issue but I can't figure out what causing it.

**Comment by howar31** [comment]
My Win 7 build number is 

> 7601.win7sp1_ldr.160902-0600

It was newly installed with my new computer last week.  I dunno what else to provide, just tell me if you need any related info and I'll try my best to help. :D

**Comment by Jaex** [comment]
Sorry I have no clue why region capture window size wrong. I believe ShareX gives proper size to window but your Windows not changes window size to that size correctly for some reason.

**Comment by piyo-gh** [comment]
My OS is Windows 10 Pro x64. I also tested on Hyper-V (Windows 10 Insider fast ring build), and result was the same.

I am not a programmer but tryed to debug a little.

In InitializeComponent()  on RegionCaptureForms.cs

`AutoScaleMode = AutoScaleMode.Font;`

Before this line AutoScaleMode {Width=1 Height=1}
After this line AutoScaleMode {Width=1 Height=0.9230769}
1080*0.923=997

Maybe this is the reason that form height is 997 pixel for my monitor.
But I didn't change DPI setting nor monitor scaling setting at all.
So, this should be default.

Strange enough.

**Comment by Jaex** [comment]
@piyo-gh try to debug this line:

https://github.com/ShareX/ShareX/blob/master/ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs#L135

It sets window size in that line.

**Comment by piyo-gh** [comment]
Bounds is {X = 0 Y = 0 Width = 1920 Height = 1080} before `ResumeLayout(false);`.
But after `ResumeLayout(false);`, Bounds changed to {X = 0 Y = 0 Width = 1920 Height = 997}.

**Comment by SumsMee** [comment]
![sharex_2016-12-05_11-15-12](https://cloud.githubusercontent.com/assets/19486398/20872783/5c08b822-badc-11e6-955e-7b81c41ee11b.jpg)

same issue on my Windows 10 Pro (Insider, Build14971), while can't reproduce on my Win 10 tablet.

**Comment by Kisesy** [comment]
@Jaex  I have the same problem.
> Win7 x32 sp1 1024x768  ShareX 11.6.0

![2017-02-27_11-14-35](https://cloud.githubusercontent.com/assets/5843694/23347569/0fb01490-fcde-11e6-9f5b-a74e6ca8f569.gif)

**Comment by howar31** [comment]
I found that no matter what resolution my screens are, the "uncovered" region for ShareX will always be the same. :/

**Comment by Renari** [comment]
One thing I noticed on W10 is that this only happens on one of my monitors, my second monitor will size to the window I'm selecting but the first will always size to the whole desktop.

**Comment by Genteure** [comment]
Same problem here.
Even my taskbar is on the right of my screen (same as 
@howar31 https://github.com/ShareX/ShareX/issues/1800#issuecomment-247898390).
System: Windows 10, 1703, 15063.632

**Comment by ZeroGravity83** [comment]
I have the exact same problem.
Windows 10 Pro, 1709, 16299.125
ShareX 12.0
Softwares in my task tray: Display Fusion, Unchecky, Evernote, Malwarebytes, Corsair LINK, Everything, CCleaner, AI Suite 3, Plex, Steam, Creative Cloud, MEGA, Airdroid 3, MSI Afterburner, MacType, Discord, ShareX

https://i.imgur.com/hlsoDMR.png
https://i.imgur.com/NkidpTM.jpg

**Comment by howar31** [comment]
Yes, I can confirm that this issue is still exist in ShareX 12.0

![img](https://i.imgur.com/8QqE7B4.png)
![img](https://i.imgur.com/9bxLgUw.png)
![img](https://i.imgur.com/3L7AvwS.png)

Windows 10 Professional, 1703, 15063.726, English 64-bit

**Comment by Kisesy** [comment]
https://ci.appveyor.com/project/ShareX/sharex
latest build, should be fixed

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds

**Comment by howar31** [comment]
Awesome!!  
Issue solved in ShareX 12.1 Beta is confirmed!!
