### ISSUE TITLE
FFmpeg error

### ISSUE THREAD

**Issue by vectorwarrior** [ShareX/ShareX#1801]
I've been getting these FFmpeg errors for a little while, possibly since version 11.1. I just updated to 11.2.1 and was hoping it would fix it but no joy.
Here's the error I get:
![ffmpeg error](https://cloud.githubusercontent.com/assets/11049403/17818900/5f64ad96-65fa-11e6-9866-81b04b31237c.jpg)

And here are my settings:
![settings](https://cloud.githubusercontent.com/assets/11049403/17818949/9854d108-65fa-11e6-8ddb-a75c7a397c9f.jpg)

I'm recording a region, maybe 720p size. The audio output is 5.1, but the video captures in stereo (although this is probably totally unrelated).

Hopefully someone can repro and resolve this as I've sunk a fair amount of time trying to get this working with different settings. It usually error's after a few seconds and it's maybe 50% repro. 

Thanks!

**Comment by Jaex** [comment]
Did you updated to Windows 10 anniversary update?

**Comment by vectorwarrior** [comment]
I dont believe so, but perhaps. System is just telling me I'm on 'Windows 10 Pro' and the update process is locked by my organization so I can't do a manual update.

**Comment by Jaex** [comment]
<kbd>Win + R</kbd> write `winver` to get version.

**Comment by vectorwarrior** [comment]
![win](https://cloud.githubusercontent.com/assets/11049403/17827687/03354648-6636-11e6-8e91-724eecc4ae2f.jpg)

Leaned something new today!

**Comment by Collisionc** [comment]
I also get these errors, running windows 10 anniversary update.

**Comment by Jaex** [comment]
ShareX downloads latest FFmpeg.

**Comment by Collisionc** [comment]
Weird. There must be some difference in the compiler or options that I am using to compile ffmpeg and the options that https://ffmpeg.zeranoe.com/builds/ is using to compile ffmpeg, because the one I build works and the one downloaded from there doesn't work, even though they are basically the same version.

**Comment by Jaex** [comment]
Same issue I think #1743

**Comment by Daisukioficial** [comment]
me too
