### ISSUE TITLE
ShareX 11.2.1 is corrupting uploads to SFTP 

### ISSUE THREAD

**Issue by Kiwi-1995** [ShareX/ShareX#1802]
https://chie.club/files/images/st/1819b4c5-4de7-4c93-90d9-e278a57bc8cc.png - Uploaded
https://chie.club/files/images/st/1819b4c5-4de7-4c93-90d9-e278a57bc8c2c.png - The original
The only special setting I've done capture wise is that the image is jpeg'd at 1.2MB or bigger(they're all clearly under)

It's also not the issue with the host(my own using SFTP) I'm uploading to as I'm hosting the original too(used filezila to upload the original and it checked out okay)

Have re-installed ShareX with no change.
Went back to ShareX 11.1 and the issue is resolved.

**Comment by Jaex** [comment]
#1797
