### ISSUE TITLE
can't capture this way

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1805]
I left click the sharex icon in taskbar and then press 2  for rounded rectangle and it borders in red but then nothing happens. How to get it to capture and upload or capture and open the 
Quick Task Menu for selection.

I right click the sharex icon in taskbar and press region, press 5 arrow and draw arrow, press 2 for rounded region and draw region which borders red, then nothing happens.
How to get it to capture and upload or capture and open the 
Quick Task Menu for selection.
thanx

**Comment by Jaex** [comment]
It is not rounded region, it is rounded drawing, you need to select rounded region not drawing.
