### ISSUE TITLE
"After upload" window shown even when no upload

### ISSUE THREAD

**Issue by fluid-decanter** [ShareX/ShareX#1806]
If I have _Show "after upload" window_ selected as one of my _After upload tasks_, the window is shown  even if I do not have _Upload image to host_ as one of my _After capture tasks_. It seems intuitive that if there is no upload, there should be no "after upload tasks" processed.

Observed in ShareX 11.2.1

**Comment by McoreD** [comment]
Strange. I tried the same settings and could not reproduce this issue.

**Comment by SandwichChef** [comment]
I just updated to 11.2.1 to test this _bug_ and found that I could reproduce it. I'm not sure if this is intentional behaviour or not, to be honest.

**Comment by fluid-decanter** [comment]
I don't think it should be intentional behavior. There's an "after capture" window as well.

I did a little more testing and found that it's reproducible with _Save image to file_ as the only after capture task and _Show "after upload window_ as the only after upload task. If that still isn't sufficient for others to reproduce the issue I'm willing to try from a fresh install.

**Comment by fluid-decanter** [comment]
I see this is still marked "cannot reproduce". What specific information should I provide that would help reproduce the problem?

**Comment by dannoe** [comment]
Maybe I am wrong, but this is the same issue, isn't it? #1837

**Comment by fluid-decanter** [comment]
Ah, seems #1837 is indeed the same issue. I wouldn't have thought to start a new thread just to add more info, but whatever works, I suppose...
