### ISSUE TITLE
problem with twitter

### ISSUE THREAD

**Issue by xguil1** [ShareX/ShareX#1810]
Hi. when I try to open the account validation page to set up my twitter account from sharex , this does not open, it does not link to anything. could you help me?  Thank you

**Comment by xguil1** [comment]
please, help me...
i have just find this in de log file
2016-08-24 00:10:21.421 - TwitterAuthOpen - Authorization URL is empty.

i think that the url athorization is https://api.twitter.com/oauth/authorize

but i don't know where and how i have to put it. 
please help me

thanks....

**Comment by Jaex** [comment]
In my tries it opens authorization URL correctly, so I don't know why it not for you.

**Comment by xguil1** [comment]
this url are in the uploadersconfig.jar file or in sharex program?

i used the program with twitter well since 6months, but 1,5 month ago it crash (only the part of twitter)... i dont know why

i have tried to uninstall all the program and erasing de .jar files in "my documents" but it is the same

can you help me? some idea?
