### ISSUE TITLE
Error on saving when image was loaded from url

### ISSUE THREAD

**Issue by medoni** [ShareX/ShareX#1811]
System.Runtime.InteropServices.ExternalException (0x80004005): Allgemeiner Fehler in GDI+.
   bei System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   bei ShareX.TaskHelpers.<>c__DisplayClass7_2.<AnnotateImage>b__5()
   bei ShareX.HelpersLib.Extensions.InvokeSafe(Control control, Action action)
   bei Greenshot.ImageEditorForm.OnImageSaveRequested()
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei Greenshot.Controls.ToolStripEx.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.1 (Release)

This happens when you try to save an image which was opened from an url. (Windows Open FileDLG then paste an url [eg. google images], then click on open)

**Comment by Jaex** [comment]
Can you give me your URL so I can test it.

**Comment by Jaex** [comment]
You not even mentioned that you were talking about image editor. There is countless place in ShareX where open dialog is used to open image.

**Comment by medoni** [comment]
Yes the error came from (Greenshot) Image Editor. Steps to reproduce:

1) Right click Taskbar Icon -> Tools -> Image Editor
2) Paste http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2013/11/Image-Effects.png (from google image search)
3) Click on Open
4) Click on Save (not Save As!)

This still occurs in 11.2.1 (Release)

This issue is depending on which url or type of image you are choosing.
For Example the Gravatar icon of ShareX(Github) works. https://avatars2.githubusercontent.com/u/822090?v=3&s=88

Sorry for my late answering

**Comment by Jaex** [comment]
I already figured out that reproduce steps. You are supposed to write it in your first message.
