### ISSUE TITLE
Option: Import pictures

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1812]
is it possible to import pictures to ShareX?

I have a link (or a list of links) of local pictures, like the following: 

•	C:\Users\my_username\Documents\ShareX\Screenshots\2016-06\picture.png

it's just this text link so drag-and-drop to paste the picture in ShareX won't work as it's pasted as pure text

**Comment by dannoe** [comment]
Yes that's possible. Just call ShareX with your paths as parameter:
e.g.: "C:\Program Files\ShareX\ShareX.exe" "C:\IMAGE1.png" "C:\IMAGE2.png"

**Comment by Jaex** [comment]
How ShareX supposed to know is it file path or text. What if user actually wants to upload file paths to text destination?
