### ISSUE TITLE
Can't make a screenshot(Doens't save on pc, doesn't upload) Tried reinstalling.

### ISSUE THREAD

**Issue by Laisergs** [ShareX/ShareX#1814]
System.OverflowException: Переполнение в результате выполнения арифметической операции.
   в System.Windows.Forms.ListView.GetDisplayIndex(ListViewItem item, Int32 lastIndex)
   в System.Windows.Forms.ListViewItem.EnsureVisible()
   в ShareX.TaskManager.CreateListViewItem(WorkerTask task)
   в ShareX.TaskManager.Start(WorkerTask task)
   в ShareX.UploadManager.RunImageTask(Image img, TaskSettings taskSettings, Boolean skipQuickTaskMenu, Boolean skipAfterCaptureWindow)
   в ShareX.MainForm.AfterCapture(Image img, CaptureType captureType, TaskSettings taskSettings)
   в ShareX.MainForm.DoCaptureWork(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   в ShareX.MainForm.DoCapture(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   в ShareX.MainForm.CaptureScreenshot(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   в System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.2.1 (Release)

**Comment by campbeb** [comment]
@Laisergs Can you show your History settings?
![History Settings](https://cloud.githubusercontent.com/assets/1089399/17913538/e1d7ecae-6968-11e6-8ae9-f14345e7d006.png)

Also, if you disable "Save tasks to history" and "Save recent tasks", does it work?

Do you have a lot of items in your history or task list?

**Comment by Laisergs** [comment]
It just randomly started working now, oh wait nvm, when i was typing this i tried screenshot and it started giving me errors again even after i've changed the settings. Also it gave me this error when i tried clicking anywhere. 
System.OverflowException: Переполнение в результате выполнения арифметической операции.
   в System.Windows.Forms.ListView.GetDisplayIndex(ListViewItem item, Int32 lastIndex)
   в System.Windows.Forms.ListViewItem.EnsureVisible()
   в ShareX.TaskManager.CreateListViewItem(WorkerTask task)
   в ShareX.TaskManager.Start(WorkerTask task)
   в ShareX.UploadManager.RunImageTask(Image img, TaskSettings taskSettings, Boolean skipQuickTaskMenu, Boolean skipAfterCaptureWindow)
   в ShareX.MainForm.AfterCapture(Image img, CaptureType captureType, TaskSettings taskSettings)
   в ShareX.MainForm.DoCaptureWork(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   в ShareX.MainForm.DoCapture(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   в ShareX.MainForm.CaptureRegion(TaskSettings taskSettings, Boolean autoHideForm)
   в ShareX.MainForm.ExecuteJob(TaskSettings taskSettings, HotkeyType job)
   в ShareX.HotkeyForm.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.2.1 (Release)


My settings were exactly the same as on the screenshot you gave.

**Comment by Laisergs** [comment]
And it just now randomly works sometimes but no pop-up on the right corner of the screen, only the link to the image gets copied into the buffer.

**Comment by dmxt** [comment]
Translation for first line: `System.OverflowException: overflow as a result of an arithmetic operation.`
Last line seem to be always `in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)` Perhaps a hint to a cause of an error?

Are you sure that there is no other program running that is conflicting with Prt Scr button?

**Comment by Laisergs** [comment]
And it just started working normally randomly again. I'm sure there're no other programms on my PC that use Prt Scr.
