### ISSUE TITLE
Portable version & ffmpeg.exe

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1815]
Portable version supposed to run in both x32 and x64 systems. So the version(s) of ffmpeg.exe downloaded should be fit to both systems.
You can decide there will be 2 files/folders for 32/64.

The default location of ffmpeg.exe must be under %sharex%\ShareX\Tools.
In case it was linked to other location in one computer, it must return to default location, to be able to run in other computer where it can't find the previous link.

**Comment by vatterspun** [comment]
Confirmed.  The FFMPEG location is a hard link (e.g. j:\portable\sharex-portable\ShareX\Tools\ffmpeg.exe")

Workaround: you can modify the FFmpeg path to the following: 

".\ShareX\Tools\ffmpeg.exe"

![2016-11-15 18_33_39-sharex - screen recording options](https://cloud.githubusercontent.com/assets/1289134/20330104/165f08a0-ab62-11e6-95a7-d0d940543473.png)

I tested this on the portable version in Win7x86 and it worked fine.

**Comment by Jaex** [comment]
I never understand why people use `.\` in their paths. It works without require '.\' anyway?

**Comment by vatterspun** [comment]
@Jaex I really don't know, I'm just basing it off other, similar workarounds.  

`ShareX\Tools\ffmpeg.exe `

... works just fine.

**Comment by vatterspun** [comment]
( Related issue: https://github.com/ShareX/ShareX/issues/1223 )
