### ISSUE TITLE
Low framerate when recording screen, even though low cpu usage

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#1816]
Hi!

I use this command line:

`-y -rtbufsize 300M -f gdigrab -framerate 60 -offset_x $area_x$ -offset_y $area_y$ -video_size $area_width$x$area_height$ -draw_mouse $cursor$ -i desktop -an -pix_fmt yuvj444p -vf scale=out_color_matrix=bt709 -c:v libx264 -r 60 -crf 22 -preset fast -tune zerolatency -x264opts colorprim=bt709:transfer=bt709:colormatrix=bt709 "$output$"`

But when I watch the result the framerate is poor, even though the cpu suage is really high. Anything wrong with it?

I made screencast of it:
[2016-08-24_12-26-52.zip](https://github.com/ShareX/ShareX/files/434504/2016-08-24_12-26-52.zip)

**Comment by XCanG** [comment]
@mzso do you try to run it in console? (in settings)
I try your command and get 60 fps: http://hnng.moe/f/GRW

**Comment by mzso** [comment]
What do you mean console? I use it in sharex. With the custom command.

**Comment by campbeb** [comment]
@mzso 
I believe he means using the Test with CMD button to see what results you get.

![sharex_2016-08-24_21-15-06](https://cloud.githubusercontent.com/assets/1089399/17953256/fc905662-6a3f-11e6-8b7f-8b7e575b4e87.png)

**Comment by mzso** [comment]
I get 8.8fps at best, and cpu usage around 25%... Is ffmpeg forced to run in single thread mode for some reason? for what reason could be the CPU usage be capped ad such low value?

**Comment by mzso** [comment]
Okay this is incomprehesinble I only get 10 fps if I change the preset to ultrafast...

**Comment by XCanG** [comment]
@mzso yeah, I mean this testing, but how you have so low FPS? What is you PC specs?
Also try screen-capture-recorder instread of GDI. If it take a change in your FPS, may be problem here. Also I think problem may be in Aero if you on Windows 7, it very slow down capturing screen.

And again I make a test, see video https://my.mixtape.moe/cacoex.webm it working good for me.

**Comment by mzso** [comment]
I tried screen capture recorder. It didn't make a difference, when it worked. 
I have an E5450, but it's not even half utilized when I record...

**Comment by XenHat** [comment]
Using the same command as the OP, I get a "Test CMD" result of 62 fps, but a "real" video capture of 2-10 fps, recording an OpenGL application.

My specs:
```
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (3997.67 MHz)
RAM: 32713 MB
O/S: Microsoft Windows 10 64-bit (Build 16257)
GPU: NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

OpenGL Version: 4.5.0 

NVIDIA 382.05
```
Sample Video:
[3xK6sXG9.zip](https://github.com/ShareX/ShareX/files/1224491/3xK6sXG9.zip)

**Comment by XCanG** [comment]
@XenHat as you have GTX 970 try to record with parameters:
Video Codec: H.264 NVENC (.mp4)
Then on tab NVENC use your bitrate, 3000 is ok, you may use slow (high quality 2 passes) method also but if default record normally.
For audio I suggest AAC.

So ShareX will show something like that in output:
```
-y -rtbufsize 100M -f dshow -framerate 30 -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:v h264_nvenc -r 30 -preset slow -b:v 3000k -pix_fmt yuv420p -c:a aac -strict -2 -ac 2 -b:a 128k "output.mp4"
```
Source depend on you, I use virtual devices.

**Comment by loicbisiere** [comment]
Same problem for me. If I set mic recording to none, there is no problem. I suspect it's a sound recording synchronisation with the video that limit the video recording framerate.

**Comment by mzso** [comment]
[**@loicbisiere**](https://github.com/loicbisiere) commented on [2017. nov. 8. 17:55 CET](https://github.com/ShareX/ShareX/issues/1816#issuecomment-342881453 "2017-11-08T16:55:11Z - Replied by Github Reply Comments"):
> Same problem for me. If I set mic recording to none, there is no problem. I suspect it's a sound recording synchronisation with the video that limit the video recording framerate.

Good to know. Quite sure it's an ffmpeg issue though since I experienced before with plain ffmpeg. Maybe you could report it to them.

**Comment by dcalag** [comment]
I was having the same issue and after doing some experimentation with the ffmpegs params I found that for me removing the '-tune zerolatency' param solves the problem.  Also, I had to use the 'super fast', 'very fast' or slower preset. The video still had low fps with the 'ultra-fast' preset.

**Comment by nicolasparada** [comment]
@dcalag Thanks, removing the zerolatency tune improved the fps 😊

**Comment by mzso** [comment]
[**@dcalag**](https://github.com/dcalag) commented on [2017. dec. 11. 20:18 CET](https://github.com/ShareX/ShareX/issues/1816#issuecomment-350828229 "2017-12-11T19:18:23Z - Replied by Github Reply Comments"):
> I was having the same issue and after doing some experimentation with the ffmpegs params I found that for me removing the '-tune zerolatency' param solves the problem.  Also, I had to use the 'super fast', 'very fast' or slower preset. The video still had low fps with the 'ultra-fast' preset.

Or maybe just improves it? It's not just libx264 that's affected. I got framedrops even with -vcodec rawvideo which doesn't compress the video at all. (I recorded to an SSD so drive speed isn't an issue.)

**Comment by gridphp** [comment]
In my case "-rtbufsize 300M" seems to be the culprit.
I removed it and it work smooth with defaults.

**Comment by XenHat** [comment]
Seems like I completely forgot to reply to this. I just tested various things, and while the `Test with CMD` function seems to "produce" 60 fps video, the actual recording in many, many circumstances seems to suffer from severe stutter and low FPS issues.

I also tried @XCanG 's advice to use NVENC, so I used the following parameters
`-y -rtbufsize 100M -f dshow -framerate 60 -i video="screen-capture-recorder" -vcodec rawvideo -c:v h264_nvenc -r 60 -preset losslesshp -b:v 5000k -pix_fmt yuv420p "output.mp4"`

I can't say it helped achieve 60 fps as well as I hoped. =(
I can't send the video due to size (180MB zipped)..

**Comment by mzso** [comment]
Since ffmpeg is so bugged, I wonder if something else could be used for screen recording? Mencoder? MPV?

**Comment by XenHat** [comment]
ffmpeg works fine in other well known projects, such as OBS Studio.

**Comment by mzso** [comment]
[**@XenHat**](https://github.com/XenHat) commented on [2018. febr. 25. 19:10 CET](https://github.com/ShareX/ShareX/issues/1816#issuecomment-368330805 "2018-02-25T18:10:35Z - Replied by Github Reply Comments"):
> ffmpeg works fine in other well known projects, such as OBS Studio.

Well, for screen recording it has horrible issues, as evidenced by this conversation here.

**Comment by RealDavidoff** [comment]
I have the same problem with sharex: it records choppy like hell, despite that I tried all parameters you posted above, except for this which I can't find where to set it: "with the ffmpegs params I found that for me removing the '-tune zerolatency' param solves the problem"

The odd thing is, I never noticed it until today, so it cannot have been choppy recording before, I would have noticed.
But my system had no change, and I even rebooted it to see if sharex performs better after fresh reboot, but it does not unfortunately.

Any help much appreciated! Thx

**Comment by dcalag** [comment]
RealDavidoff: to remove -tune zerolatency go to 'Task settings - Capture/Screen recorder - Screen recording options button' and then click on 'Uso custom commands' at the bottom and edit the commands to remove the '-tune zerolatency' part.

**Comment by RealDavidoff** [comment]
Oh that was easy, thank you so much.
Odd is, now today I recorded a bit from youtube, and with my change from yesterday (sound off) it was fine, like the other poster said.
However, I sometimes really need sound with footage, so I am glad I can now test without that latency thing and WITH sound.
That aside, I find sharex GREAT, it is so powerful, almost scary. I use screen recording a lot and before depended on Camstudio, which in comparison is weaker than weak.

**Comment by mzso** [comment]
What's the point is this stupid stale bot. It certainly didn't solve the issue. Only hid it.

**Comment by AntumDeluge** [comment]
I am having a similar issue with FFmpeg on both a Windows system (using *gdigrab*) & a Linux system (using *x11grab*). The problem occurs with I try to capture the entire desktop (*1920x1080* on Windows system, *1600x900* on Linux).

When trying to capture at 60fps, I only get around 24 or 25. I haven't solved the problem, but came across something that could be hint... maybe? By adding the *-vsync 1* option to the end of the command line, FFmpeg reports the correct framerate. Checkout the output video with MediaInfo confirms a constant framerate of 60. However, playing the video, it appears choppy. This is because it is duplicating frames to produce the resulting 60fps. It uses around 40% of my CPU. It may be worth noting that when the *-vsync 1* option is omitted, MediaInfo reports that the video uses a variable framerate.

Not sure if this will help anything, just though I would mention it.

My FFmpeg command (Linux):
```
ffmpeg -y -hide_banner -rtbufsize 1500M -probesize 100M -f x11grab -framerate 60 -s 1600x900 -i :0.0 -c:v mpeg4 -vtag xvid -qscale:v 0 -vsync 1 testcapture/out.mkv
```

**Comment by mzso** [comment]
I think the biggest issue here is with gdigrab. I changed to Screen Capture Recorder and the videos turned out fine. I wouldn't hold my breath about the ffmpeg people fixing this, since it's bugged for ages.
I could even record fullscreen without framedrops using the ffv1 codec.

**Comment by AntumDeluge** [comment]
I think I had the same result with Screen Capture Recorder. But I will try it again.

I also used [Captura](https://github.com/MathewSachin/Captura), which uses FFmpeg as well, which worked fine.

**Comment by mzso** [comment]
[**@AntumDeluge**](https://github.com/AntumDeluge) commented on [2019. márc. 11. 00:12 CET](https://github.com/ShareX/ShareX/issues/1816#issuecomment-471364008 "2019-03-10T23:12:08Z - Replied by Github Reply Comments"):
> I think I had the same result with Screen Capture Recorder. But I will try it again.
> 
Perhaps you have other issues as well? It works rather fine with latest Sharex the the SCR that it downloads/installs when you click the button in the config window.

> I also used [Captura](https://github.com/MathewSachin/Captura), which uses FFmpeg as well, which worked fine.

That would be weird because I had the same issues with using ffmpeg by itself, from command line.

**Comment by mzso** [comment]
[**@AntumDeluge**](https://github.com/AntumDeluge) commented on [2019. márc. 11. 00:12 CET](https://github.com/ShareX/ShareX/issues/1816#issuecomment-471364008 "2019-03-10T23:12:08Z - Replied by Github Reply Comments"):
> I think I had the same result with Screen Capture Recorder. But I will try it again.
> 
> I also used [Captura](https://github.com/MathewSachin/Captura), which uses FFmpeg as well, which worked fine.

Okay. I maintain that the biggest issue was gdigrab, but with SCR it still sucks. There are stutters, audio crackle and such (as such in the video as well of course) in the app (epsxe) I'm recording. Nothing fixes this completely but not using sharex/ffmpeg.
In contrast MSI afterburner has no effect whatsoever. I think the ShareX dev should consider some other backend for screen recording. FFMPEG is hopeless. (It also consistently butchers lossless full-range video. BT primaries are wrong or it becomes limited range. You need dig up various eclectic settings for different codecs to encode the recorded videos properly.)

**Comment by XCanG** [comment]
If you have issues with performance, then try to use Hardware Acceleration.
More info here: https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by Knufje** [comment]
I had the same problem to by using screen recording with an hotkey which started a custom screen recording, which I then applied to the entire screen. But when I started recording using the screen recording button in the application it self and using just the region of a game window which gave me a much better fps. (Not really a solution I know)

**Comment by ArunEdathadan** [comment]
My PC Spec is  I5, 8GB Ram, SSD.
The recording is too slow. 

Sample video 
[https://www.youtube.com/watch?v=yqoHjZqVyX0&feature=youtu.be](url)

**Comment by ColdSpirit0** [comment]
Same issue for me - when starting recording, entire desktop shows about 2 fps. On my previous config - intel hd 610 it didnt happen, but on new config amd fx + amd rx 570 it happens. I tried dxva2 acceleration, but got same 2 fps + input desync.
That is ffmpeg problem, because when I tried to run capture from cmd line - got the same bug.

**Comment by ColdSpirit0** [comment]
> I also used [Captura](https://github.com/MathewSachin/Captura), which uses FFmpeg as well, which worked fine.
Captura works much worse than ShareX for me.

In the same time, OBS studio works fine with hw and sw encoding.

**Comment by danass** [comment]
i have the same issue. Ive been tweeking all aroundi get the same results.
i have gtx 1650 ss1to i7 10th gen ..

**Comment by rdp** [comment]
What does afterburner use?

**Comment by ze0ss** [comment]
This is still an issue for many, including me, shame it's been over 5 years, and no solution.
I used the Screen Recorder Capture to get the audio as well, for which ShareX had to download and install something, otherwise the default one could not record the in-game audio.
My game is flawless at around 75 fps, but the moment I start screen recording using Shift+PrntScrn, the Fps drops to less than 25 wtf.
Help asap.

**Comment by mzso** [comment]
[**@ze0ss**](https://github.com/ze0ss) commented on [2021. ápr. 21. 15:55 CEST](https://github.com/ShareX/ShareX/issues/1816#issuecomment-824080929 "2021-04-21T13:55:09Z - Replied by Github Reply Comments"):
> This is still an issue for many, including me, shame it's been over 5 years, and no solution.  
> I used the Screen Recorder Capture to get the audio as well, for which ShareX had to download and install something, otherwise the default one could not record the in-game audio.  
> My game is flawless at around 75 fps, but the moment I start screen recording using Shift+PrntScrn, the Fps drops to less than 25 wtf.  
> Help asap.

Your problem is not the same, at least mostly not. It's about dropping frames when there's nothing graphic resource hungry is running, without real justifiable cause. But it's an ffmpeg bug. And if I remember correctly it only happens when audio is recorded as well. So someone hypothesized some synchronization issue.

But your main problem is sharex is a screen recorder and not a game recorder. If I understand correctly it records whatever's shown on screen or part of the screen, which is not very efficient.

Meanwhile game recorders hook into Directx/Vulkan and get an image from there with less disruption to the program.
So you really should be trying MSI afterburner. For which I recommend the UT-Video codec (full range RGB, without subsampling) for minimal impact on game performance (You'll need to record on a different HDD/SSD than where the game is, preferably a good one). And then re-encode it into whatever format is best for your purposes.

**Comment by XCanG** [comment]
> This is still an issue for many, including me, shame it's been over 5 years, and no solution.
> I used the Screen Recorder Capture to get the audio as well, for which ShareX had to download and install something, otherwise the default one could not record the in-game audio.
> My game is flawless at around 75 fps, but the moment I start screen recording using Shift+PrntScrn, the Fps drops to less than 25 wtf.
> Help asap.

I can give you better advice, but it depend on your overall performance.
So if you record in 60 fps and your game is ~75, then limit framerate for your game (or turn on vsync), then start recording. By doing that you will have some free resources to use.

Also what is recording settings you using? You may have unoptimal solution.

 Alternatively just record on CPU.

**Comment by Neoony** [comment]
maybe try downloading newer/different version of ffmpeg?

ShareX does not exactly downloads the newest ffmpeg

e.g. https://www.gyan.dev/ffmpeg/builds/

but anyways I would never recommend ShareX for recording games
Just use OBS

Even gifs I record, I first record with OBS and then play the video in player and record gif (but mainly because of scaling the player window to reduce gif size easily)

**Comment by ze0ss** [comment]
Here's my settings @XCanG 

![image](https://user-images.githubusercontent.com/56572179/115659877-d3281100-a358-11eb-974d-cea6df93626b.png)

**Comment by ze0ss** [comment]
> but anyways I would never recommend ShareX for recording games
why not?

> Just use OBS
ok, but in sharex, I only have to press Shift+prntscrn for starting or stopping the recording, in obs we need the whole obs window for controlling the recording.

**Comment by mzso** [comment]
[**@Neoony**](https://github.com/Neoony) commented on [2021. ápr. 22. 01:11 CEST](https://github.com/ShareX/ShareX/issues/1816#issuecomment-824422636 "2021-04-21T23:11:26Z - Replied by Github Reply Comments"):
> 
> Even gifs I record, I first record with OBS and then play the video in player and record gif (but mainly because of scaling the player window to reduce gif size easily)

That's rather silly. You can just transcode video to animated GIF (also APNG). Via ffmpeg for example.

**Comment by Neoony** [comment]
> why not?
> 
> > Just use OBS
> 
> ok, but in sharex, I only have to press Shift+prntscrn for starting or stopping the recording, in obs we need the whole obs window for controlling the recording.
> 
> @Neoony

Like I said, OBS is most likely much more optimized for recording games. Not using ffmpeg
ShareX is rather an office tool.

Of course there are hotkeys in OBS
You dont need the OBS window at all

> That's rather silly. You can just transcode video to animated GIF (also APNG). Via ffmpeg for example.

I usually record long videos of a match/round. Then I only want to clip gif of some small part of the video.
Works perfect and is super easy and fast to do for what I need.
Last time I tried converting video to gif over sharex, it was all bugged.
And like I said, this makes it easy to scale resolution up or down to make shorter gif better quality, or longer gif worse or so on

https://www.youtube.com/watch?v=oBedUnZiTHo

never actually heard about APNG, will check thx

**Comment by mzso** [comment]
[**@Neoony**](https://github.com/Neoony) commented on [2021. ápr. 22. 16:24 CEST](https://github.com/ShareX/ShareX/issues/1816#issuecomment-824887815 "2021-04-22T14:24:34Z - Replied by Github Reply Comments"):
> oh well and the ShareX video converter converts my 88MB 39sec mp4 into couple GB GIF or APNG (4.27GB APNG !!!)  
> not sure if thats something in my settings but I did not use any custom arguments (lowest quality/size)
> 
> Is video converter supposed to be using settiings from "Task settings - Screen recorder - Screen recording options"?  
> Otherwise I cant explain the absolutely huge size
> 
> The gif also does not really work

Apng/gif are lossless formats, they're not meant for long, high resolution videos.

**Comment by XCanG** [comment]
@Neoony APNG is like a patch for PNG, not really good solution, but have advantages: 24bit color and transparency
so you may need to optimize APNG later (it use raw frames as default and you need to replace them to difference only)

A new and better alternative would be WEBP (via libwebp binaries or ffmpeg).

@ze0ss settings look good, it more like you don't have enough performance to play + record then.

If you have NVIDIA video card, there is internal solution via Nvidia Geforce Experience, called Nvidia Share (previously known as Shadowplay) https://www.nvidia.com/en-us/geforce/geforce-experience/shadowplay/

OBS is also suitable as mentioned above.

Also about ffmpeg, if you tweak it settings, you can use GPU to record, check this page https://trac.ffmpeg.org/wiki/Capture/Desktop
As you can see Windows settings pretty much reflect ShareX settings, BUT there is Hardware Acceleration section which show example how to record on your GPU, so you may edit ShareX command manually and use that settings instead.

And there is a bit of settings in ShareX as well, just try this recorders according to your graphic card brand NVIDIA / AMD
from link above there was table for supported codecs on different video cards
![image](https://user-images.githubusercontent.com/4011523/115832572-78f88000-a42c-11eb-89a3-b104d0aee373.png)

**Comment by ze0ss** [comment]
@XCanG I've started using obs thanks for that.
I don't have any frame drops anymore whatsoever.

**Comment by lynrayy** [comment]
Any solution?

**Comment by lynrayy** [comment]
i set 2000m buffer but it keep saying 
[dshow @ 000001b7935feb80] real-time buffer [screen-capture-recorder] [video input] too full or near too full (87% of size: 2000000000 [rtbufsize parameter])! frame dropped!

**Comment by mzso** [comment]
[**@lynrayy**](https://github.com/lynrayy) commented on [2021. szept. 2. 23:10 CEST](https://github.com/ShareX/ShareX/issues/1816#issuecomment-912059651 "2021-09-02T21:10:20Z - Replied by Github Reply Comments"):
> Any solution?

Never found one. It seems like you need to use something else to capture full screen video+audio.

**Comment by ColdSpirit0** [comment]
It happened for me when I opened Unity's Asset Store (inner browser) window, or when some subwindow was detached. Cant reproduce it now but did it before, when Asset Store worked. Maybe in old Unity versions it still works

**Comment by DAOWAce** [comment]
Over 6 years later and this is still a problem.

I can't get fullscreen recording (3440x1440) working with a stable framerate no matter what options I seem to pick (CPU or GPU encoding), buffer size, removing zerolatency tuning, removing audio source, changing quality, etc.  Setting to 'record in lossless then encode' results in broken recording, it only seems to want to record when I hit the hotkey to stop the recording, then records infinitely until I click the "encoding..." tray icon.  And no, not using GDI grab; that is a source of terrible performance.

If I record a small section of the screen, it's 60FPS no issue.   If I record a larger section (tested down to 2560x1440), framerate is chugging and looks to be in the 20's.  System is overkill: 5950x, RTX 4090, 64GB RAM.

This tool has been invaluable to me over the years for quickly recording clips, but as technology improves, increasing minimums to quality also follows.  I don't want to record 30/45FPS footage anymore.

I really don't want to have to load up OBS and have to deal with it injecting into things just to record a stable 60FPS clip of the screen, but it seems there's no other option now.

**Comment by lynrayy** [comment]
It's just a fucking random
Sometimes it installing and have lags, sometimes you reinstall or pray to the pasta gods and it starts work properly
¯\_(ツ)_/¯

**Comment by rdp** [comment]
Is the CPU maxed out?

On Friday, January 13, 2023, lynrayy ***@***.***> wrote:
> It's just a fucking random
> Sometimes it installing and have lags, sometimes you reinstall or pray to
the pasta gods and it starts work properly
> ¯_(ツ)_/¯
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci4.googleusercontent.com/proxy/afko9S7wPtXAEbeXuinBkTl3nv7OD4C2367Q3yUkD-_CW-khjbf9_bKzhmxlOdLnYxWUXCCLwzana3keirO8jDEqcEi9YMkX3iNNxUV4JejdiGaEv9vzweS3X2_b4d8z2Olmq-M5hpiWwuHRQXJyu4VcAaFlv1HNWQ5GxNqD7iHm4ogu1hqmqlAKX0LrUw9glVJ71V_cHhcs8dS6CG5bU6JPwFkYZkWaEtAoFQ6F-w=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUFJDEQA6XSME6XI4QTWSE423A5CNFSM4CNPQGE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOKJNYUIQ.gif>Message
ID: ***@***.***>

**Comment by DAOWAce** [comment]
It's not random at all; it's strictly based on the resolution of the capture region.

ShareX is incapable of recording video at higher resolution and framerate than 1080p60. Anything higher and it falls over.

It's comparable to a high speed camera: Some cameras can do, let's say, 240FPS at 4k.  But to get to 20,000 FPS, you have drop to like 320x140.

There is no current solution even after **8 years**.

There is a solution within ffmpeg by using a different capture method (ie; [ddagrab](https://ffmpeg.org/ffmpeg-filters.html#ddagrab)), but as of now, no contributor has added it to the program.

ShareX is no longer fit for screen recording in the modern age, unfortunately.  Other solutions (like [wcap](https://github.com/mmozeiko/wcap)) are annoying to use or limited in functionality.

Had I the knowledge I would work on adding this, but I am not a programmer, nor see learning programming in my near future.

**Comment by lynrayy** [comment]
`ShareX is incapable of recording video at higher resolution and framerate than 1080p60. Anything higher and it falls over.`

It is absolute random. Since time when i'm wrote here, it started working don't know when and why, but now it working. 1920x1080. Nothing changed except 2-3 windows re-installs

**Comment by L1Q** [comment]
> There is a solution within ffmpeg by using a different capture method (ie; [ddagrab](https://ffmpeg.org/ffmpeg-filters.html#ddagrab)), but as of now, no contributor has added it to the program.

ShareX supports ffmpeg ddagrab since [16.0.0](https://getsharex.com/changelog#v16.0.0)

**Comment by lynrayy** [comment]
`ShareX is no longer fit for screen recording in the modern age`

Yes, but it still have no alternative with auto-upload on youtube in private access AND storing this in folder AND copying link in the CTRL+C buffer. Also i don't know any soft that can capture selected ZONE on the screen. It's very useful if you want to record something and not to show other things that you have on screen

**Comment by DAOWAce** [comment]
> > There is a solution within ffmpeg by using a different capture method (ie; [ddagrab](https://ffmpeg.org/ffmpeg-filters.html#ddagrab)), but as of now, no contributor has added it to the program.
> 
> ShareX supports ffmpeg ddagrab since [16.0.0](https://getsharex.com/changelog#v16.0.0)

For some reason I didn't see any reply despite it happening on the same day, within even half an hour.

It took **until now** to realize there was an update in **March** that added DDAgrab which completely solved this longstanding issue entirely.  And the NVENC encoder makes it so the rendering performance on the user's side is practically identical to not capturing the screen, which software encoding even with DDAgrab still didn't resolve (though the recording was much better).

Guess this is what I get for disabling update checks.  Needlessly spent 9 months longer with poor recordings.. sigh.

**Comment by BrycensRanch** [comment]
There’s no good reason to be holding your software at static versions. There’s a reason why the update check was added. 

> > ShareX supports ffmpeg ddagrab since [16.0.0](https://getsharex.com/changelog#v16.0.0)
> 
> For some reason I didn't see any reply despite it happening on the same day, within even half an hour.
> 
> It took **until now** to realize there was an update in **March** _(before I posted!)_ that added DDAgrab which completely solved this longstanding issue entirely. And the NVENC encoder makes it so the rendering performance on the user's side is practically identical to not capturing the screen, which software encoding even with DDAgrab still didn't resolve (though the recording was much better).
> 
> Guess this is what I get for disabling update checks. Needlessly spent 9 months longer with poor recordings.. sigh.

Disabling update checks for ShareX makes no sense in the first place. ShareX has been stable for years with hardly any changes that’d make daily drivers upset. You can look at screenshots from 2020 and the software looks like it hasn’t changed much

**Comment by lynrayy** [comment]
> Guess this is what I get for disabling update checks.

It's not your fault. It's the fault of the person who doesn't sort the changes by importance in the changelog, and people don't even read these changelogs. And also the fault of those who make updates too frequent or such that they change the interface, although the user didn't even ask for it.

I also disabled updates everywhere, for the reasons described above. Most often, updates cause more problems than they help.

**Comment by BrycensRanch** [comment]
> > Guess this is what I get for disabling update checks.
> 
> It's not your fault. It's the fault of the person who doesn't sort the changes by importance in the changelog, and that's why people don't even read these changelogs. And also the fault of those who make updates too frequent or such that they change the interface, although the user didn't even ask for it.
> 
> I also disabled updates everywhere, for the reasons described above. Most often, updates cause more problems than they help.

This is amazing blame shifting. The changelogs are comprehensive and informative. They’re also interesting to read imho. Stop trying to blame the devs for your misguided decisions. Jaex hardly changes the core interfaces or even the UI workflows so you don’t have a leg to stand on. You only say “updates cause more problems than they help” because you don’t see the good they do, only when they temporarily disrupt you. Keeping software at static versions is a known bad practice in the software world, especially with careless users.

**Comment by lynrayy** [comment]
> The changelogs are comprehensive and informative.

Important changes, such as fixing bugs that make the app unusable (like lags when recording video), should be higher on the list than everything else. Preferably put in a separate category. I haven't seen anyone do that.

**Comment by lynrayy** [comment]
> Jaex hardly changes the core interfaces or even the UI workflows

I'm not talking about him specifically, I'm talking about the developers' tendency in general. I'm not going to study the version history of each individual application to say "Aha, here I can update without fear of breakage" and "Aha, but this application often changes the interface, it's better not to update it." People just have a specific stereotype about updates, and therefore more and more people avoid them.

**Comment by BrycensRanch** [comment]
> > The changelogs are comprehensive and informative.
> 
> Important changes, such as fixing bugs that make the app unusable (like lags when recording video), should be higher on the list than everything else. Preferably put in a separate category. I haven't seen anyone do that.

https://jaex.getsharex.com/2024/12/chrome_OcG4B3fybi.png
https://jaex.getsharex.com/2024/12/chrome_ISPH9Oty3D.png

Stereotypes are not reality. Full stop.

**Comment by lynrayy** [comment]
> https://jaex.getsharex.com/2024/12/chrome_OcG4B3fybi.png
> https://jaex.getsharex.com/2024/12/chrome_ISPH9Oty3D.png

And how is a regular user like me supposed to understand what this means? Lucky me, I know what NVENC is, but what is ddagrab? What do these changes even mean?
You need to write in plain language - RECORDING STOPS ON NVIDIA VIDEO CARDS HAVE BEEN FIXED, and only after that technical information. Users and developers are different people. What is obvious to you is a dark forest for users

**Comment by BrycensRanch** [comment]
> > https://jaex.getsharex.com/2024/12/chrome_OcG4B3fybi.png
> > https://jaex.getsharex.com/2024/12/chrome_ISPH9Oty3D.png
> 
> And how is a regular user like me supposed to understand what this means? Lucky me, I know what NVENC is, but what is ddagrab? What do these changes even mean? You need to write in plain language - RECORDING LAGS ON NVIDIA VIDEO CARDS HAVE BEEN FIXED, and only after that technical information. Users and developers are different people. What is obvious to you is a dark forest for users

Because it’s not a bug fix it’s an enhancement to ShareX’s screen recording. The previous method worked ok for people but this is a new capture method. Stop acting like you would have even bothered to read the change logs. Do you have any other excuses? This is open source software, see how far acting like a entitled brat will get you.

**Comment by lynrayy** [comment]
> Stop acting like you would have even bothered to read the change logs.

Because I really don't read changelogs. 99.99% of the time there's nothing interesting for me there.
