### ISSUE TITLE
Action paths broken

### ISSUE THREAD

**Issue by bradsmithee** [ShareX/ShareX#1827]
**Issue** : When using actions, paths are not handled correctly.
**Version** : 11.2.1
**OS** : Windows 10 ProN Build 14393
**Explanation** : I'm attempting to have ShareX call a bat/cmd file that uses "gsutil" to upload to Google Cloud and set correct permissions.  The batch file does not recognize gsutil despite it being in my environment paths.  Upon doing echo %path% from the batch, I can see the path (and others) missing.  If attempting to call the full path ("C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gsutil.cmd"), it is not found.  If navigating to the directory via "cd" in the batch and then calling "gsutil.cmd", the path is also not found.  Common command-line operations such as "start" do not work.
**Expectation** : %path%, relative, and absolute paths to programs work from a standard command prompt and when running the batch standalone or from other applications, but not through a ShareX action running a batch/cmd.

**Comment by Jaex** [comment]
I tried this: `"C:\Program Files (x86)\IrfanView\i_view32.exe" %1`
it worked which means absolute paths have no problem.

   cd "C:\Program Files (x86)\IrfanView"
   i_view32.exe %1

But this not worked. But I'm not good with batch so something could be wrong in that code.

**Comment by dannoe** [comment]
Check your environment variables with `set` in both cmds.
Maybe you installed ShareX with the admin account and now the environment variables from admin are used.
