### ISSUE TITLE
Consider adding a simple ReadMe.TXT file with basic info

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1832]
such commands line arguments.

**Comment by Scrxtchy** [comment]
https://github.com/ShareX/ShareX/wiki/Command-line-arguments

**Comment by Stamimail** [comment]
for offline use...

**Comment by dmxt** [comment]
Yeah, why not slap entire ShareX wiki for offline use. Why it gotta be just command line page that you specifically picked out? Also ShareX is mainly usable for online use.

Another stupid shit.

**Comment by Scrxtchy** [comment]
```git clone https://github.com/ShareX/ShareX.wiki.git``` will download the entire wiki for offline storage

**Comment by Stamimail** [comment]
:)
Look, you don't have to agree with me.
I only know, I was needed it, and it wasn't be there.

2016-08-29 12:56 GMT+03:00 Scratch <notifications@github.com>:

**Comment by dmxt** [comment]
@Scrxtchy Excellent solution. 

Doesn't need to apply to everyone like OP thinks
