### ISSUE TITLE
More advance folder watching

### ISSUE THREAD

**Issue by scj643** [ShareX/ShareX#1840]
For folder watching one should have the option to select the destination it goes to and to watch for modifications.

**Comment by dannoe** [comment]
> the option to select the destination it goes to
That's already possible. Just create a new Task with your destination and setup the folder watch inside the new the task.

**Comment by Jaex** [comment]
There is reason why I didn't add "modifications" trigger because when file is written it can trigger multiple times depending on how software writing file. So it won't be what you want.

**Comment by Arsenalist** [comment]
I'm trying to do something similar.  Basically, trying to only upload files that are of a certain extension in the watch folder, e.g., .mp4. 

Also, how do you create a new task? I see a lot of stuff pre-configured as task, but didn't know I could create one as well.

**Comment by dannoe** [comment]
> Also, how do you create a new task? I see a lot of stuff pre-configured as task, but didn't know I could create one as well.

![](https://cloud.githubusercontent.com/assets/7450586/18313223/df45d680-750d-11e6-87a0-cbb37c23c6e9.png)

And with the "Edit" button you can change the settings for a specific task.
