### ISSUE TITLE
Problems with copying to clipboard for region capture

### ISSUE THREAD

**Issue by fumetsuu** [ShareX/ShareX#1845]
Hello,
I've been using ShareX for a long time and have come across this persistent problem a few weeks/month ago. I've made another issue on it but didn't explain much. 
I have a capture task which allows me to capture a region, and after that, it saves the file and copies the image to the clipboard. This works fine, but sometimes it decides to stop working and doesn't copy to clipboard. Instead of pasting the image that I had just taken, the thing that was previously on my clipboard is pasted, whether it be text or another image. It copies to clipboard fine if I use window capture or monitor capture.
If I restart ShareX, I'm able to capture (and copy to clipboard) one screenshot before it stops copying to clipboard again. In order to further temporarily resolve the problem, I have to reinstall ShareX. Each time the problem occurs, I reinstall (it happens once, twice maybe three times a day, depending on how much I use it.)
I've tried installing ShareX's older versions (10.6.0, 10.6.1) as well as the recent ones, but the problem still remains. 
All of the advanced settings are set at default.

I think that the problem isn't with ShareX, but with my computer.
If anyone has any idea as to what the problem is, I'd be very grateful.

Thank you.

**Comment by Jaex** [comment]
It not make sense how reinstalling ShareX can solve copying to clipboard. Reinstalling not even touches ShareX settings.

**Comment by fumetsuu** [comment]
Yea true, that was what I was thinking. I also tried deleting everything I could find to do with ShareX from the registries. Pretty sure the problem is with my computer, although my brother experiences the same thing.
