### ISSUE TITLE
Screen color picker copy HEX type gone from Advanced?

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#1851]
I have auto screen color picker and auto HEX copy setup and binded, but after updates, it only copy RGB. I went to advanced tab to change this, but couldn't find any line to modify from RGB to HEX. What happened? Sorry if I was missing something

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/wiki/Changelog

**Comment by dmxt** [comment]
@Jaex Thank you! I didn't see that before. Have a feeling that it still belong to Advanced with all other settings, considering Tools is really empty..
