### ISSUE TITLE
ShareX Updating keeps reseting the settings

### ISSUE THREAD

**Issue by Goldy58** [ShareX/ShareX#1857]
Ok, I'm not sure what it is, but I like this application because it can upload directly to my FTP account, and get it's address by finishing uploaded. I dont know if its a bug or what, but everytime i decided to update ShareX, all the settings and HotKeys are reset to default, and I had to end up changing the configs everytime. Is there a way to prevent this from happening, like a config file where the application check to see if there's an existing default config file to load up without having to reset everything to default? This is very frustrating, and when I start to do a capture, it prompts to save and upload to its default selected server (imgur in this case), and I know i had selected FTP from the last update before this new one. Please fix this or change something to prevent it from creating a new config file.

**Comment by dannoe** [comment]
You can try to set your own configuration path.
![sharex_2016-08-31_20-04-21](https://cloud.githubusercontent.com/assets/7450586/18140510/2844c164-6fb6-11e6-8a8e-19ac71411ec1.png)

**Comment by karasique86** [comment]
I can confirm that this still occurs upon every update on both of my PCs. Setting up a personal folder for settings doesn't do anything because config files get overwritten by default ones.

**Comment by Goldy58** [comment]
Well, is there a way to get this fixed to where it won't have to overwrite the configuration files again? Cause doing that doesn't help at all. Of course that we can save each configuration files and all, but having to update it and then find out that all are overwritten is a disaster and we have to configure each file again. Thus doing that making a backup copy of the files and when we do update it, have to find the files to load up the configuration takes time too.

**Comment by tommynaranjo** [comment]
This is still an issue! I can't believe this hasn't been fixed. A program that doesn't save its own settings?

**Comment by TendToAscend** [comment]
> 
> 
> This is still an issue! I can't believe this hasn't been fixed. A program that doesn't save its own settings?

I agree. I'm currently having this issue as well.

**Comment by joshuathomas2** [comment]
This is definitely still an issue. I made it so the program wouldn't automatically upload to imgur because of screen capturing sensitive materials. The program just reset my settings so now it does do that. I just uploaded private information and my IP to Imgur...

**Comment by MastaCoder** [comment]
Having the same problem, ShareX just reverted my custom upload settings twice in the past week.

**Comment by 0Hyp3r10n0** [comment]
I have this issue too. It happened every single time on my old laptop, I got a new pc just recently and it started happening from time to time.

**Comment by Exaint** [comment]
i still have this issue

**Comment by maxkunes** [comment]
Still having this issue. Not even sure its caused by new versions.

**Comment by maxkunes** [comment]
I would suspect it has something to do with force closing sharex, as I often hard restart/shut off my pc.

**Comment by Fleckky** [comment]
Still having this issue

**Comment by maxkunes** [comment]
Just had it happened again today as well in case it was questioned whether or not this still happens.

**Comment by Tahnx** [comment]
bump - still an issue I have been experiencing

**Comment by davidb91** [comment]
I had the same issue when updating to the version 13.0.1 (install and updates via chocoletey package).

**Comment by greenlittleapple** [comment]
Same issue with 13.0.1. This is really infuriating since it just gets overwritten and all my custom settings are lost.

**Comment by Braunson** [comment]
I've figured a solution, not ideal but it works here https://github.com/ShareX/ShareX/issues/4709#issuecomment-613713287

**Comment by a-hulman** [comment]
Ping 2022 still not working.

**Comment by baphomutt** [comment]
still having this issue.
every update my custom folder location, upload settings, and keyboard configurations were getting reset :(

have tried multiple fixes, so now I have disabled the app from updating or prompting me to update.

**Comment by guicbrito** [comment]
I can confirm this bug still exists. 
1. Go to Application Settings -> Paths, change the personal folder and apply. ShareX prompts for restart and assigns the custom folder as the personal folder correctly. 
2. Quit and reopen ShareX (or restart computer). 
3. ShareX personal folder resets to the default path (C:/Users/user/Documets/ShareX), recreating the folder as needed. This means you can't actually change the personal folder. 
I'm using Windows 11. This happens both on the last development version and on version 8.0.0, even after reinstalling.

**Comment by wolfsprite** [comment]
I've personally just stopped updating the app ever. Which is unfortunate as a solution, but I've had this issue for over a year and it still has not been resolved. :(

This issue was marked as stale and closed, sadly. Should probably open a new issue.

**Comment by HorselessName** [comment]
The issue persists. 
But here is my personal solution:

- Use a custom path, on `Program Settings`, Path.
- Do everything you need, configure everything, then, mark the following files as `Read Only`.

Files that needs to be marked as Read Only:

![image](https://github.com/ShareX/ShareX/assets/20173635/13ea935e-6e5f-4bef-8477-83dbf34ed505)

For some reason it created those .temp files, but I updated it and it worked. Settings remained the same.

I believe that we can even block the app from creating those `.temp` files as well, using Folder Group Policies to block extension types.

**Comment by Goldy58** [comment]
Hi. I'm the one who started this thread years ago, and it surprises me to see that even after years of this discussion, it still a problem to most people. I have decided years ago that I switch over to Greenshot which do the same thing as ShareX. With the updates too, it dosent reset the configure files and the hot keys too.

**Comment by fari-99** [comment]
@Goldy58 ,  can confirm still a problem to this day. 😆

**Comment by Goldy58** [comment]
8 years, and still no fix. Well, everyone. Using Greenshot has the same features as ShareX, and it's completely free to download and can be  used as a Portable program too, so you can save the installation in a USB and can be used on many computer, and it dosent reset the config file lol.

**Comment by SMSum** [comment]
Revisiting this one after 10 years now, after further investigation, PersonalPath.cfg is stored inside Documents\ShareX\ path which users delete when moving to a custom folder (or at least I did when running into this). A simple fix could be as easy as mirroring the desired personal path into registry and checking that instead of defaulting.

Shortest solution since you're not open to PR's would be making WritePersonalPathConfig writeout the desired path into registry, and equally read that on initial startup to avoid needing to retain this file across potentially unwanted drives.
