### ISSUE TITLE
Keymapping to upload file in Windows Explorer

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#1858]
In the Windows explorer file list there is a right click context menu item to upload the selected file using ShareX.

I have a custom programmable keypad for making shortcut keys to perform actions.  I would like to be able to select a file in windows explorer and simply hit a mapped key to have that file uploaded with ShareX.  

Right now the context menu item uploads the selected file so would you possibly also add a keyboard shortcut to do this same action?

![explorer_2016-08-31_00-29-12](https://cloud.githubusercontent.com/assets/186818/18115995/01cecdb2-6f12-11e6-85d5-4dbfda3311b5.png)

**Comment by Jaex** [comment]
How to tell to windows explorer to upload selected file? Sending ctrl + c is not an option, that is pretty ugly way.

**Comment by jasondavis** [comment]
ahh good idea!  Thank you
