### ISSUE TITLE
Capture Region: not rectangular anymore

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1859]
Hi,

Since last update my region capture is not rectangular, it is in a manual shape. How to fix it, please? It's very ennoying :(

![explorer_2016-08-31_13-23-22](https://cloud.githubusercontent.com/assets/18115558/18127004/1c016f84-6f7e-11e6-90d7-6774649a2ffb.png)

**Comment by Jaex** [comment]
#1778
