### ISSUE TITLE
Size limitation on uploads?

### ISSUE THREAD

**Issue by Griever92** [ShareX/ShareX#1862]
I recently setup a sharex uploader on my personal server and seem to be encountering a size limitation to my upload ability, though no limitation of any sort has been configured.

I'm able to successfully upload files up to roughly 2MB in size, but anything great than this and the uploader errors out with a "CHMOD/Folder not found" message.

All files under 2MB in size upload correctly to the proper destination and are accessible.

Below is the upload script I am using. 
(Apologies for formatting with quote, the codeblock was not displaying properly.)

> <?php
> $secret_key = "xxxxxxxx";
> $sharexdir = "../";
> $domain_url = 'http://img.host.tld';
> $lengthofstring = 6;
> 
> $safe_types = ["jpg", "jpeg", "png", "gif", "webm"];
> 
> function RandomString($length) {
>     $keys = array_merge(range(0,9), range('a', 'z'));
>     for($i=0; $i < $length; $i++) {
>         $key .= $keys[mt_rand(0, count($keys) - 1)];
>     }
>     return $key;
> }
> 
> if(isset($_POST['secret']))
> {
>     if($_POST['secret'] == $secret_key)
>     {
>         $filename = RandomString($lengthofstring);
>         $target_file = $_FILES["sharex"]["name"];
>         $fileType = strtolower(end(explode(".", $target_file)));
>         if (in_array($fileType, $safe_types))
>         {
>             if (move_uploaded_file($_FILES["sharex"]["tmp_name"], $sharexdir.$filename.'.'.$fileType))
>             {
>                 echo $domain_url.'/'.$filename.'.'.$fileType;
>             }
>             else
>             {
>                echo 'File upload failed - CHMOD/Folder doesn\'t exist?';
>             }
>         }
>     }
>     else
>     {
>         echo 'Invalid Secret Key';
>     }
> }
> else
> {
>     echo 'No post data recieved';
> }

**Comment by Jaex** [comment]
I don't know anything about php.
