### ISSUE TITLE
Watch folders, screenshot folder and Screen recording(GIF) functions conflict

### ISSUE THREAD

**Issue by KulaGGin** [ShareX/ShareX#1867]
First of all, I want to say that ShareX is an awesome unique program. Never seen anything even close to ShareX with that functionality. Thanks for your hard work, keep it up.

But I've got this problem with ShareX. Let me tell you my long story, otherwise it will not make any sense to you.

I am using ShareX to record screenshots, GIFs and upload them to appropriate hosts. I also use MSi Afterburner, Dxtory and Steam to record screenshots and videos in different games and programs. The thing is that in different games different recording programs can or can not take screenshots or record videos, so the only solution for me is to use different recording programs to take screenshots or record videos in different games and programs.

Here's my settings for different programs:
Dxtory screenshot folder: F:\Multimedia\All Screenshots
Afterburner screenshot folder: F:\Multimedia\All Screenshots
ShareX screenshot folder: F:\Multimedia\All Screenshots
http://i.imgur.com/Xeulrdx.png

I turned off **Upload image to host** in **After capture tasks** in **ShareX**:
http://i.imgur.com/I3E9RDJ.png

I also added folder _F:\Multimedia\All Screenshots_ to watch list in **Watch Folders** menu in **Tasks settings**:
http://i.imgur.com/NBj1wjf.png

So when I take screenshot using Dxtory, Afterburner or ShareX my screenshots are saved in _F:\Multimedia\All Screenshots_ and then ShareX uploads these screenshots because ShareX watches this folder.

The problem is that with settings listed above 1 second after I start recording GIF using ShareX I get this error:
http://i.imgur.com/vZwkWGc.png

It obviously happens because ShareX watches _F:\Multimedia\All Screenshots_ folder and creates **.mp4** file while recording screen in the same folder for screenshots and not in personal ShareX folder(where it is supposed to, right?) which is set to _D:\Programs\ShareX_ for me(folder where ShareX is installed on my PC).

It actually records file fine. Here's a live recorded gif from the field with error for you:
http://i.imgur.com/YzHhRtc.gifv

But it doesn't upload file to a host(imgur in my case) after this error message.

Once I uncheck Watch folders and if new file created then upload it, problem is gone, too:
http://i.imgur.com/YzHhRtc.gifv

Obvious solution would be to record screen and save *.mp4 files to a different folder and then copy compressed gifs to a screenshot folder. I couldn't find this kind of option in ShareX, so it would be nice if you added option to record *.mp4 files to a different folder and then make ShareX to copy these files to a proper screenshot folder.

**Comment by KulaGGin** [comment]
Bump. It would be so nice to know if devs at least read the message.

**Comment by Jaex** [comment]
Of course I read all messages...
