### ISSUE TITLE
GIF recorder does not work with 4K display

### ISSUE THREAD

**Issue by ghost** [ShareX/ShareX#1869]
http://i.imgur.com/CVJb2CK.png

I tried to reinstall ShareX and reset all settings.

**Comment by Jaex** [comment]
Try this video source:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/ShareX.vshost_SPr9WtEC7e.png)

**Comment by afkMeister** [comment]
![](https://i.imgur.com/YEIvDNR.png)
