### ISSUE TITLE
Combine Pictures: Crash after adding 80 pictures

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1871]
System.Runtime.InteropServices.ExternalException (0x80004005): Er is een algemene fout opgetreden in GDI+.
   bij System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   bij ShareX.TaskHelpers.SaveImage(Image img, EImageFormat imageFormat, Int32 jpegQuality, GIFQuality gifQuality)
   bij ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   bij ShareX.WorkerTask.DoAfterCaptureJobs()
   bij ShareX.WorkerTask.DoThreadJob()
   bij ShareX.WorkerTask.ThreadDoWork()
   bij ShareX.HelpersLib.ThreadWorker.WorkThread()
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bij System.Threading.ThreadHelper.ThreadStart()

ShareX 11.1 (Release)

**Comment by KamranMackey** [comment]
Have you tried ShareX 11.2?

**Comment by YasseenDeHerdt** [comment]
How to update?

**Comment by YasseenDeHerdt** [comment]
This happens: 
![sharex_2016-09-04_00-38-14](https://cloud.githubusercontent.com/assets/18115558/18227967/e84cf85e-7237-11e6-8245-278efdb566ac.png)

**Comment by KamranMackey** [comment]
About -> Check for update

**Comment by Jaex** [comment]
That error unfortunately not gives any info to know exact reason. I wonder is one specific image causing it.

**Comment by GreenShade** [comment]
I managed to reproduce this error. I thought that it might be caused by out of memory but I actually can save the same image transposed. Does Windows allow to create such huge images?

**Comment by Jaex** [comment]
I don't think they will limit image size.

**Comment by YasseenDeHerdt** [comment]
FYI, those pictures were screenshots taken on iPad Air 2.

**Comment by GreenShade** [comment]
What is their actual size?

**Comment by YasseenDeHerdt** [comment]
1536x2048

**Comment by campbeb** [comment]
This is a limit in the size of a Bitmap that can be created in .NET based on memory usage.
The crash is coming from `Bitmap bmp = new Bitmap(width, height);`

If you are combining vertically, then `width` is maximum width of any of the images and `height` is combined total of all the image heights plus any spacing that is set.

Explained here: http://stackoverflow.com/questions/6333681/c-sharp-parameter-is-not-valid-creating-new-bitmap
