### ISSUE TITLE
System.UnauthorizedAccessException for /DOCUMENTS/ directory

### ISSUE THREAD

**Issue by Snaxeko** [ShareX/ShareX#1873]
This problem was habitual for programFiles shareX folder so I added permissions there in vain ofc because the problem for me is that ShareX can't do anything in my C:\Users\******\Documents\ShareX\ directory.
One of these similars errors : 

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\******\Documents\ShareX' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String path)

**Comment by Jaex** [comment]
If your Windows not allows ShareX to access folder, there is nothing ShareX can do about it. Check is `Documents\ShareX` folder is read only or is that folder have proper permissions.

**Comment by Snaxeko** [comment]
No all permissions are good. I used appdata folder it works thx anyway.

**Comment by danielsawan** [comment]
@Jaex i also have this prob on win 10. My folder is not marked as read only. You should trust the user that report bugs ! I test that on 2 version of windows 10. One was update from win 8 and the other was fresh install.

@Snaxeko Thanks for the %appdata% tricks. It also worked for me
