### ISSUE TITLE
No "Quick Tasks" menu after region capture using hotkey

### ISSUE THREAD

**Issue by korzynski** [ShareX/ShareX#1874]
When I capture a region using the hotkey (Ctrl+ Print Screen), the region is captured but the "Quick Tasks"  menu doesn't open. Instead, the image is saved immediately, the thumbnail appears in the task tray and the "completed" sound plays. 

If I capture a region by left-clicking on the ShareX task tray icon instead of using the hotkey, then the Quick Tasks window opens as expected. 

When I capture using the other hotkeys, such as Entire Screen (Print Screen) or Active Window (Alt + Print Screen), the Quick Tasks menu opens after the capture as expected.  The problem only seems to occur when I use the region capture hotkey. I tried changing the hotkey for region capture to just Print Screen but the problem still occurs.

I am running Windows 10 Enterprise 64-bit with ShareX version 11.2.1

**Comment by Jaex** [comment]
You must have overridden after capture tasks in that hotkey.

**Comment by korzynski** [comment]
I'm pretty sure I didn't do that, but if I did, where would it be done? I only know of one configuration set for Capture Region and it seems to apply to both the hotkey and the task tray icon.

http://i.imgur.com/uAv2IrV.png

**Comment by Jaex** [comment]
I have no idea how such thing can happen, I can't manage to reproduce that problem.

**Comment by thoughtsunificator** [comment]
ShareX version 12.3.1

I tried overriding the capture settings to "After Capture: Show quick task menu" it is still saving the file instead of showing the quick task menu.

**Comment by DaedalusGame** [comment]
Still a problem in version 12.4.1

In the main ShareX window, I've set "After Capture: Show quick task menu"
In the hotkey window, even though it's pointless, I've also set "After Capture: Show quick task menu"
Both of these result in the default behavior happening: the result is just saved to file.
Is there some other spot where I have to change after-recording actions?

**Comment by praetor22** [comment]
I've been having this issue for the past few weeks.

**Comment by VapidLinus** [comment]
@ghost @DaedalusGame @NoStereo, did you ever find a solution to this problem?

I'm having the same problem with "Quick Tasks" not showing after region capture. It works for screenshots but not recordings.

![image](https://github.com/ShareX/ShareX/assets/4418470/5f6c35ef-056d-469a-a85f-016441bbb57b)

![image](https://github.com/ShareX/ShareX/assets/4418470/ac41f354-6763-43fe-8857-967fdfb4b22c)
