### ISSUE TITLE
Screenshot uploaded to FTP distorts lower portion of image on upload

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#1875]
For the past week it seems anytime I make a screenshot and have it selected to uload to my FTP server like I always do.  It uploads the full size image however only the top `225px` of my screenshot images looks correct and anything below that on the image uploaded is distorted and generally includeds a distorted copy of the top good part on the lower section.

**Example of the image being uploaded:**

![chrome_2016-09-05_21-09-43](https://cloud.githubusercontent.com/assets/186818/18259137/c2c61b7e-73ae-11e6-847f-856b1ff11e44.png)

---

**Example of the file on my FTP server after the upload:**

![explorer_2016-09-05_21-15-52](https://cloud.githubusercontent.com/assets/186818/18259146/e0b4458e-73ae-11e6-8d77-db2719b6b72d.png)

---

As the image above shows, only the top 226px looks correctly on the uploaded image however the image that shareX saves to my local PC looks correct as the to image.

This issue seems to happen to all my FTP screenshot uploads now for the past week.  If I upload to a service like Imgur, it works fine on those sites.

Could this be an issue with the FTP uploading library?  Or could this be an issue on my server somehow?

Here is a direct link to the file above that is a result of the FTP upload http://goo.gl/a8BkpJ

**Comment by campbeb** [comment]
@jasondavis Can you try the workaround mentioned here for setting the buffer size: https://github.com/ShareX/ShareX/issues/1797

**Comment by Jaex** [comment]
Yes it is SFTP library issue.
