### ISSUE TITLE
Sound-clipping in video-recording

### ISSUE THREAD

**Issue by KeronCyst** [ShareX/ShareX#1876]
Hi, I really love ShareX but I've discovered that its video-recording feature incorrectly records sound (internal only: no microphone input here), and causes clipping as shown by the red lines below, portrayed in Audacity:

![image](https://cloud.githubusercontent.com/assets/13827055/18262373/c3b23a20-73b5-11e6-912e-590c25ac8c39.png)

I'm wondering if this could be fixed by adding an optional feature to automatically reduce all captured sound by a user-specified amount, or by capping input to a certain max level. Thanks for your incredible utility, either way.

**Comment by KeronCyst** [comment]
Hello, has this been fixed?

**Comment by stuntguy3000** [comment]
Not as you suggested.

Can you try again with the newest version of ShareX and identify if this issue is still present?
