### ISSUE TITLE
Lack of an option to capture mouse click indicator while recording screen

### ISSUE THREAD

**Issue by geek085** [ShareX/ShareX#1877]
Mouse clicks or key presses are not being captured currently while recording the screen. This feature would be really useful. 

For a reference, please see the black circle around the mouse pointer in the below animated gif. 

[https://blog.udemy.com/wp-content/uploads/2015/08/image47.gif](https://blog.udemy.com/wp-content/uploads/2015/08/image47.gif)

**Comment by dannoe** [comment]
see #1040

**Comment by geek085** [comment]
Wow.. that was quick
