### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by Tritaya** [ShareX/ShareX#1878]
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> System.BadImageFormatException: Не удалось загрузить файл или сборку "ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Ожидалось, что модуль содержит манифест сборки.
   в ShareX.TaskSettingsTools..ctor()
   в ShareX.TaskSettings..ctor()
   в ShareX.ApplicationConfig..ctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   в System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.Activator.CreateInstance[T]()
   в ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   в ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   в ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   в ShareX.Program.LoadProgramSettings()
   в ShareX.Program.Run()
   в ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)

**Comment by Jaex** [comment]
#1615
