### ISSUE TITLE
Google Drive auto upload not working

### ISSUE THREAD

**Issue by CodersRock** [ShareX/ShareX#1880]
Just found your app and really like what it can do from video demo!
Thanks for creating and sharing this app

usercase:
for every screen capture, want to auto-upload to google drive folder

in destination settings, under google drive - i authenticate with verifaction code all OK
and can see and choose folders

public upload - unticked
direct link - ticked

 = =

I set:
After capture tasks > Upload image to host

![2016-09-07 14_29_02-clipboard](https://cloud.githubusercontent.com/assets/22045670/18301952/88f1c9d4-7507-11e6-99c5-9c09d810d6d7.png)

It doesn't do upload to Google drive for some reason
I have to refresh authentication which - login is still active

Appreciate your help

Cheers

**Comment by Jaex** [comment]
Did you select it from destinations menu?

**Comment by CodersRock** [comment]
Got it - thanks Jaex!
(user error :) )

Below screen capture is for those looking to do the same thing

![2016-09-08_13-53-30](https://cloud.githubusercontent.com/assets/22045670/18338496/ed7cb5b6-75cb-11e6-9754-c49dd624e68d.gif)
