### ISSUE TITLE
Capture window with transparency doesn't work

### ISSUE THREAD

**Issue by ZenoNiQ** [ShareX/ShareX#1883]
If I understand right this options must add shadow to screenshots, but no any shadows on screen img.

How to reproduce: just screen something with this 
Options:
![2016-09-07_11-13-16](https://cloud.githubusercontent.com/assets/1075196/18305199/19186d56-74ef-11e6-8b78-6a7c2e8721b7.png)
![sharex_2016-09-07_11-18-08](https://cloud.githubusercontent.com/assets/1075196/18305208/211ec2e8-74ef-11e6-923a-fa5cf6bcedc7.png)

Another bug in my opinion if I add shadow from **Image effects** all fine after uploading on Imgur, but if only copy to clipboard it's copied **with no transparency**  

Option:
![sharex_2016-09-07_11-20-46](https://cloud.githubusercontent.com/assets/1075196/18305231/4039364a-74ef-11e6-964a-7c591ad4ece0.png)

Example: 
First insert from url, second from clipboard or from: context menu>copy>image
Drug and drop from file folder work fine.
![discord_2016-09-07_11-40-56](https://cloud.githubusercontent.com/assets/1075196/18305445/46994010-74f0-11e6-8951-8cb4f4180807.png)

Pls some help... what I do wrong? Cuz I spend so much time and can't understand why it is copied from the main window with border

**Comment by Jaex** [comment]
Reason why it don't have transparency when copied to clipboard because 99% of software not supports reading image with transparency from clipboard. You can enable it from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/ShareX_e73oGno6By.png)

But then software not support transparency won't even be able to receive image. So this is why I disabled it by default.

**Comment by ZenoNiQ** [comment]
And what about first question why id don't add shadowdrop? Or that function not about that?

**Comment by Jaex** [comment]
Your screenshots already have shadow.

**Comment by ZenoNiQ** [comment]
Yeah, only if i enable it from **Image effects** 
if i turn on only this, no any changes 
![image](https://cloud.githubusercontent.com/assets/1075196/18307527/ad0fddaa-74f9-11e6-9837-a8c6896f8543.png)

**Comment by Jaex** [comment]
It is to capture window which already have shadow.

**Comment by ZenoNiQ** [comment]
Oh thx, now understand... <3
