### ISSUE TITLE
Integrate External/3rd Party Animated GIF Screen Recording App

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#1884]
I know I was one of the original people pushing for Animated GIF image capabilities and you really delivered an amazing solution.  However mny needs for animated GIF images has slightly changed and I need better quality GIFs now.

I have tried and tested every animated GIF app for Windows that I can find and I have abouyt 4-5 that work fairly good.  There is 1 that stands ahead of the pack however as the very best!  

It is called [Screen2GIF](https://screentogif.codeplex.com/) and some core features:

[https://screentogif.codeplex.com/](https://screentogif.codeplex.com/)

- Record your screen and save directly to a gif looped animation or a video.
- Pause and continue to record or start over by discard the recording.
- Move the window around to record what you want, it stays on top.
- Record webcam image
- Import other images or video or other media objects to project
- Resize4 GIF
- CROP GIF
- Add/Delete Frames
- Set time duration between each frame
- Re-arrange frame order
- Add caption text frame
- Add Text layers
- Freehand drawing
- Cinemagraph to erase areas of the main image and allow the background layer images to play through
- Add borders
- Add watermark images
- Select a folder to save the file automatically or select one before encoding.
- Add the system cursor to your recording.
- Very small sized and portable (uses a settings file under the AppData folder) executable.
- Requires .Net Framework 4.6.1.

---

My question, would it be difficult to integrate this app so that the GIF recording controls in ShareX would launch this app and upload its final image somehow?

**Comment by Jaex** [comment]
I'm not planning to add whole software inside ShareX.
