### ISSUE TITLE
Network shares have become inaccessible since 11.2.1

### ISSUE THREAD

**Issue by PizzaCompiler** [ShareX/ShareX#1887]
I used to have ShareX save to a network folder mapped as a drive but this stopped working since 11.2.1. It doesn't see the shares anymore in the file browser, nor can it access them. 

Same goes if I browse to it using "Network locations. Although the file browser does show the location, ShareX can't write to the path (E.g \\webserver\sharedFolder).

**Comment by Jaex** [comment]
Did you tried installing previous version to test it? Because I don't remember any changes which can cause such issue.

**Comment by PizzaCompiler** [comment]
Yeah I switched back to 11.2, and it works fine with that version.

**Comment by dannoe** [comment]
Maybe an user context problem? Did you install ShareX with an admininistrator account and map the network only in your user account?

**Comment by Jaex** [comment]
11.2 and 11.2.1 is identical... Which proves that your problem was not to do with latest version.

**Comment by PizzaCompiler** [comment]
So basically I discovered that if I upgrade through ShareX it won't be able to access network shares anymore. But if I upgrade from the setup it works fine.

**Comment by Jaex** [comment]
Setup runs as admin so it runs ShareX as admin too.
