### ISSUE TITLE
Hotkeys don't work when programs with admin privileges are focussed.

### ISSUE THREAD

**Issue by Ghorich** [ShareX/ShareX#1888]
Screenshot hotkeys don't work when programs ran with admin privileges are focussed. 

To reproduce, run any program (notepad e.g) without admin privileges and try if the screenshot hotkey works, it should. After, run that same program with admin privileges, the hotkey doesn't make a screenshot then.

**Comment by Jaex** [comment]
There is nothing I can do about it other than changing hotkey system to use keyboard hook which I'm not planning to. Or you can run ShareX as admin then hotkeys will work in those apps too.
