### ISSUE TITLE
Can't Scale GIFs

### ISSUE THREAD

**Issue by vectorwarrior** [ShareX/ShareX#1889]
You can scale video captures with the command:
-vf "scale=trunc(iw_0.5/2)_2:trunc(ow/a/2)*2"
Unfortunately this doesn't affect GIFs and as a result GIF files end up being really large, which is a problem as so many websites/apps have max sizes for GIFs. 

Can you either make GIF capture support custom commands such as the above, or add a property to set a scaling size for gifs.

Thanks!

**Comment by vatterspun** [comment]
A few workaround programs:

* PhotoScape (Photoscape.org)
* GIF Resizer (http://www.ashongsoft.com/product/gif-resizer.html)
