### ISSUE TITLE
ShareX and Disabling the Tray Icon

### ISSUE THREAD

**Issue by ChowMains** [ShareX/ShareX#1890]
If it is possible, I'd like it so that there was a way to make it so that when the Show Tray Icon option is disabled, hitting the Close button on the window doesn't end the process like it currently does. If it could instead be made so that it functions like the default program which runs as a background process when the Show Tray Icon option is enabled, and the Close button is hit, just with the tray icon hidden from view.

**Comment by dannoe** [comment]
You can just hide the tray icon with windows builtin functionality.

**Comment by ChowMains** [comment]
Can you please explain how I can hide tray icons on Windows 10 natively? As I do not see any options for it, and [https://puu.sh/r4Fb8.png](url) I've already gotten this disabled, so unless there's something I'm missing, I don't think this is something I can do.

**Comment by dannoe** [comment]
Sorry, I didn't know the behavior of Win10 is different from Win7 with these options. But on Windows 7 it will be hidden inside the extended taskicon section.

![](http://i.imgur.com/YGc4RfF.png)

**Comment by Jaex** [comment]
It is not different you can hide tray icons in Windows 10 too.

**Comment by ristein** [comment]
I can't seem to find a way to hide the tray icon. When I select the setting that says so, I can't close the main window without exiting the application
