### ISSUE TITLE
SLi.mg not finishing upload

### ISSUE THREAD

**Issue by ExperimentalDJ** [ShareX/ShareX#1893]
When uploading with SLiMG it will not finish processing the upload. Everything works smoothly up to the point where it reaches 100% on the upload. After it reaches 100% it just stays there waiting. It creates the screenshot file just fine obviously. https://i.sli.mg/MU9pql.png

The rest of the upload destinations work so I'm not sure if it's on their end.

**Comment by Jaex** [comment]
It stucks in this state:
`20 = Queued for media processing.`
So it is not to do with ShareX.
