### ISSUE TITLE
REQUEST ssh/scp upload

### ISSUE THREAD

**Issue by CanadianJeff** [ShareX/ShareX#1895]
because FTP is so old and not secure possible for ssh?

also ssh with public key auth using putty gen key

**Comment by dannoe** [comment]
![sharex_2016-09-10_09-11-18](https://cloud.githubusercontent.com/assets/7450586/18408693/94fc3b20-7736-11e6-90b1-efb688bfa511.png)

**Comment by CanadianJeff** [comment]
oh thanks
