### ISSUE TITLE
Filter on a watch folder - inclusive or exclusive?

### ISSUE THREAD

**Issue by Arsenalist** [ShareX/ShareX#1896]
Here's a screenshot: http://i.imgur.com/jLBGCIj.png

Is this filter supposed to be inclusive (i.e., only upload files that match the pattern) or exclusive (i.e., do not upload files that match the pattern)?  So far, I find that it basically ignores whatever's in there, or maybe I'm doing something wrong.

Also, is there any way to specify multiple filters.  Basically, I would only like .mp4 and .jpg files to be uploaded, and nothing else.

Thank you for the great tool!

**Comment by Jaex** [comment]
It uploads that match the pattern.

https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher.filter(v=vs.110).aspx

` Use of multiple filters such as "*.txt|*.doc" is not supported.`

But you can make multiple workflows.
