### ISSUE TITLE
Can't upload to FTP server

### ISSUE THREAD

**Issue by ghost** [ShareX/ShareX#1897]
**ShareX 11.2.1**
I get this when i try to upload pictures to my FTP server.
`System.IO.IOException: The connection was terminated before a greeting could be read.
   at: System.Net.FtpClient.FtpClient.Connect()
   at: System.Net.FtpClient.FtpClient.Execute(String command)
   at: System.Net.FtpClient.FtpClient.GetWorkingDirectory()
   at: System.Net.FtpClient.FtpClient.GetListing(String path, FtpListOption options)
   at: ShareX.UploadersLib.FTPClientForm.LoadDirectory(String path)
   at: System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at: System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at: System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at: System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at: System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at: System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at: System.Windows.Forms.Control.WndProc(Message& m)
   at: System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at: System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by NotSoSuper** [comment]
There's most likely an issue with your FTP server, ShareX attempted to establish a connection and was cut off.

Make sure your FTP server allows remote connections and is configured correctly.

**Comment by NotSoSuper** [comment]
[12:34 PM] invalid-69: wait no ya i cant connect the ftp lmao

/close

**Comment by cathalmf** [comment]
Possibly room for a cleaner error when a connection fails.
