### ISSUE TITLE
Bug at launch

### ISSUE THREAD

**Issue by Thedarklife74** [ShareX/ShareX#1900]
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
   à ShareX.TaskSettingsTools..ctor()
   à ShareX.TaskSettings..ctor()
   à ShareX.ApplicationConfig..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance[T]()
   à ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   à ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   à ShareX.Program.LoadProgramSettings()
   à ShareX.Program.Run()
   à ShareX.Program.Main(String[] args)

ShareX 11.2.1 (Release)

**Comment by Jaex** [comment]
#1615
