### ISSUE TITLE
[Suggestion] Allow "Show quick task menu" task from the quick task menu

### ISSUE THREAD

**Issue by pangeacake** [ShareX/ShareX#1901]
Suggestion is to allow tasks in the quick task menu to reopen the menu afterwards; this way you could "chain" tasks.

For example, you could have tasks for saving, uploading, and copying to clipboard; this way you can choose any combination of the three.

**Comment by Jaex** [comment]
Reason why I excluded it because then continue button can nonstop open that menu.

**Comment by pangeacake** [comment]
Hm.. that's true. Maybe you could have it ignore the menu task only if you are continuing from the menu.

**Comment by Jaex** [comment]
Now I remember why it is not supported. Because after capture tasks executed in same order that it is listed. When you select task with "show quick task menu" it will open that without execute other tasks so it will non stop open menu without execute rest of stuffs. So it is not possible to make what you requested happen.

**Comment by pangeacake** [comment]
Is it possible to instead make some menu where you can select multiple tasks then? This way it is easier to choose a combination of them.

**Comment by Jaex** [comment]
You can add tasks which have those multiple tasks.

**Comment by pangeacake** [comment]
Yes, but then I'd need 6 tasks for all the combinations and even more with multiple tasks. ex:

Save
Save, Copy
Save, Copy, Upload
Copy, Upload
Upload
Copy

**Comment by Jaex** [comment]
Look from bright side you won't need to click 4 times to check 3 different task and then continue. Also after capture tasks window is close to what you want anyway.
