### ISSUE TITLE
ShareX dislocate mouse upon recording GIF

### ISSUE THREAD

**Issue by pwign** [ShareX/ShareX#1908]
My mouse is fine when I record something, however, the result appears to dislocate the mouse and moved it off the original position.

![Bug GIF](https://i.lithi.io/SlKjv.gif)

**Comment by Jaex** [comment]
Try this video source:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/ShareX_EvEcoljgQ8.png)

**Comment by pwign** [comment]
The problem still persist 

![Image](https://i.lithi.io/JK9Po.gif)

**Comment by Jaex** [comment]
Because it is not ShareX code, there is no way for me to fix it.
