### ISSUE TITLE
[new feature] File Deletion API

### ISSUE THREAD

**Issue by VisualStudio-zz** [ShareX/ShareX#1910]
I think it would be nice for there to be an option in custom uploaders for something like "silent delete" or something of the sort so that it doesn't have to open a web browser to delete the image, is this easily possible?

**Comment by Jaex** [comment]
It is not easily possible. Deletion URL is also stored in history etc. so it have many benefits.

**Comment by VisualStudio-zz** [comment]
It's not possible to pass the url to a WebClient and let it make the request instead of a browser?
