### ISSUE TITLE
Cannot upload via SFTP w/ keys

### ISSUE THREAD

**Issue by ghost** [ShareX/ShareX#1912]
Hi,

I'm currently running the latest version of ShareX. Up until I put SSH keys on my vps it has been working flawlessly. Although, when using SSH keys it does not work.

I am able to use WinSCP to login to my server with the key over SFTP although ShareX simply will not budge, saying that my key is invalid.

Thanks.

**Comment by Jaex** [comment]
Maybe key type you using not supported in SFTP library? https://github.com/sshnet/SSH.NET
