### ISSUE TITLE
Hotkeys don't work within certain applications.

### ISSUE THREAD

**Issue by Vahryx** [ShareX/ShareX#1915]
For example, while I am playing League of Legends, none of the hotkeys work. They are not bound to any keys used within the application either; I tried multiple hotkeys. They do usually work fine with other applications.

**Comment by Jaex** [comment]
If game works as admin then it is limitation of hotkey system that non admin app can't receive hotkey input from admin app. So nothing I can do about it. It also can be that game not letting hotkey to reach ShareX too. So in any case there is no way to fix it with this hotkey system.

**Comment by MINIMAN10000** [comment]
Also of note the game Kenshi does not run as admin, runs in full screen borderless, and is unable to capture hotkeys when in focus. I believe using global hotkeys might be a viable option https://stackoverflow.com/questions/2450373

**Comment by ReikaKalseki** [comment]
I ran into this myself recently with a program I am making (which has to run as admin because it calls FFMPEG, which itself needs to run as admin to work on Windows 7).

Is there a way to issue a command to ShareX to take a screen capture via some sort of inter-program communication line?

**Comment by TheFurryDevil** [comment]
It's insane how there are still no solutions to this. Just give users a setting to make ShareX use a keyboard hook.
I found some ancient reply where it said they tried a keyboard hook but there were problems like it randomly not working anymore, so they used RegisterHotKey instead. Instead of figuring out why the other option didn't work...

**Comment by davidonabus** [comment]
Yes, I'm also in need of this. I may try to add it myself.

**Comment by Nammehub** [comment]
> If game works as admin then it is limitation of hotkey system that non admin app can't receive hotkey input from admin app. It also can be that game not letting hotkey to reach ShareX. So in any case there is no way to fix it with this hotkey system.

but the same thing works in OBS

**Comment by Nammehub** [comment]
> If game works as admin

And if not, not from the admin, but the program still doesn’t respond to the hotkey?

<img width="485" height="151" alt="Image" src="https://github.com/user-attachments/assets/aeab8109-eb47-42b3-a60e-55864b3777aa" />
