### ISSUE TITLE
Cannot URL Upload from Long URLs

### ISSUE THREAD

**Issue by MWisBest** [ShareX/ShareX#1916]
ShareX is unable to upload images by URL when the number of characters in the URL exceeds 260.

![](http://i.imgur.com/HdyDjxt.png)

**Comment by Jaex** [comment]
That error looks to do with file path not url and it is limitation: http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows

**Comment by MWisBest** [comment]
That is NOT a file path. Try uploading this image using ShareX:

https://lh3.googleusercontent.com/KGvSVpu-2b7SVtcU_XrVxQ1zpta3mLdTIEUd_mgbLYWzJhU2xh2ZqMCk3jDkcgtq3q822lmoFkf8q8xuqz6ZgSvc_2kW7EMCxYIGZBbh0OOeXJMOCgz1be7ny509PQzLZ1DMNGzme0l0SjEsh7Ua7Gxq2aGFee3Rnpd4Rbi0pc2pM6wofxG9vjnh4TNrM932MQ_VkNqAoXQoRjlGBriykJGcJMN6lO0Sponqi-AaPXc78XU4v7aQIcc3TphbOQII3K7cYk9JjxZdiJwf2rspimvlHjW4mwp91owt_u5LBgCUcsLOw1JA0oagPNXo_NY4cpsXEvR99scapx-tJ3VcwPZwxPQp9KreLAhv1OdNjv4Cvd9pLcHjv3mRF-wnlqoMijg_ANlh4dZcSMHjIV6rKV0tV5axfXrf7g2qTzddxk95Jt2zxy0DwFwPhgCyd-kEG68R6nUHfbFxApaRaFg00UiOZClbw-LF9_sT2iZ6SpCrEErSwIYxStGCeJnBHrTTw3FPNRXEB_4N-emLnYCw-8hDtj4n_20gACea6l4vvVxP4KgbkrKtnS3JNxKUMILIWzcJflzv1MRoTue_cnSPLOB6pbgmaqHat2uSha4p99I=s0

**Comment by Jaex** [comment]
ShareX uses last section in URL as file name so it is file path.

**Comment by MWisBest** [comment]
So in other words you can work around this issue by checking if the last section of the URL exceeds the character limit and chop off the extra characters when downloading the file.

**Comment by EliteTK** [comment]
Certainly at least a better error message is in order.

**Comment by MWisBest** [comment]
@EliteTK, @Jaex is just too incompetent to fix the issue.
