### ISSUE TITLE
Please rework scroll capture

### ISSUE THREAD

**Issue by MildPanda** [ShareX/ShareX#1917]
I was trying to get it to successfully capture a forums page (that has a changing background so perhaps that may have been troublesome for the program to handle) and I couldn't get it to work. It scrolls and all but it would either not end itself and when I go to end it that causes the program to capture sharex's menu and only 1 portion of the thread. I found another tool :( that worked first try. Don't wanna say it unless asked by a ShareX programmer/contributer.

**Comment by campbeb** [comment]
It would be helpful if you mentioned the site that is not working for you.

**Comment by Opzon** [comment]
Well.... the site is a hacking forums. I believe I tested out the feature on a different site and it didn't work well either. I will make some tests and upload the failed samples too.

**Comment by Jaex** [comment]
If something changing in background how am I supposed to know where to stitch screenshots?

**Comment by Opzon** [comment]
while that is a good question and I am in no way a programmer of any sort I do know another program is able to accomplish this. I have only tinkered with coding so I know close to nothing. My only suggestion would be to look at the scroll bar and stitch it with that and if the user has selected only a portion of the screen still look at that bar and crop accordingly. Thanks for replying, I truly appreciate your guy's work and hope I can contribute (money wise) in the future as I don't make much money now.

**Comment by Jaex** [comment]
Keeping track of scroll position very rarely works because there is so many situations scroll bar can be custom one and I'm unable to get its position. Not to mention rendered stuffs not always need to match scroll bar position correctly. So it is impossible to rely on scroll bar position when stitching stuffs.

**Comment by Opzon** [comment]
Welp. then I have no other ideas :( thanks for your time though 👍

**Comment by vatterspun** [comment]
> it is impossible to rely on scroll bar position when stitching stuffs

Can confirm.  Several programs (especially Java tools) frequently have unexpected scroll bar behavior.
