### ISSUE TITLE
[new feature] take snapshots -> produce GIF animate

### ISSUE THREAD

**Issue by pipiscrew** [ShareX/ShareX#1921]
the famous to us [Wink ](http://www.debugmode.com/wink/) from 2000! user can take snapshots and in the end export to swf. SWF will disabled in 3months ([officially from Google](http://www.ghacks.net/2016/09/14/old-flash-activex-will-be-blocked-on-windows-7/)).

-the user should be in **GIF ANIMATE** phase, this means from the moment click the option, the app stay at tray, press PrnScrn to take the first snapshot is the **base** of width&height. The next PrnScrn should be a region equals to first snapshot where user is able to move around the screen, when left click, take the snapshot.

-user should be able to create **GIF ANIMATE** from already existing images (drag&drop to listview).

the options should be like :
![snap041](https://cloud.githubusercontent.com/assets/3852762/18642116/b7564146-7e9f-11e6-9c68-58b48e35fa47.png)

thanks!

**Comment by Jaex** [comment]
Did you tried this app: http://screentogif.codeplex.com/

Maybe it can do exactly what you want.

**Comment by pipiscrew** [comment]
yes I know this fantastic app, didnt know, the **new version** has editor! WPF pff... sitting on win7x64, just testing 

![snap052](https://cloud.githubusercontent.com/assets/3852762/18683805/0dea0984-7f72-11e6-883b-fe57ff170c00.png)

---

more simplier. more simplier.. as described.. above, thanks for quick response.

**Comment by Jaex** [comment]
I'm not planning to add gif editing related features because even for user it can be simpler but coding it can be too much work. But also another reason is ShareX using FFmpeg to record animated gif and not creating itself.

**Comment by pipiscrew** [comment]
ok no problem. thanks for your time again.

FYI 
[Stackoverflow - Create animated gif from a set of jpeg images](http://stackoverflow.com/a/29542944)

**Comment by NickeManarin** [comment]
@pipiscrew In order to use ScreenToGif version 2.2 or above, you need to install [.Net Framework 4.6.1](https://www.microsoft.com/en-us/download/details.aspx?id=49982).
