### ISSUE TITLE
Why was Up1 removed as an uploader?

### ISSUE THREAD

**Issue by zeffy** [ShareX/ShareX#1922]
I'm referring to https://github.com/ShareX/ShareX/commit/c7b38b59f6ce5b59ffcfb50ac842c2d40a5fcc0e

I understand that the original service at https://up1.ca has been down for long time, but there are still other sites that host private instances of its code and can be used with ShareX by changing the host and api key. 

Any chance Up1 support could be added back before the next release?

**Comment by zeffy** [comment]
Well, looks like this commit made it in to 11.3. That's a real shame.

**Comment by zeffy** [comment]
Referenced wrong commit in my first commit, whoops.

**Comment by Efreak** [comment]
There is an up1 server at share.riseup.net and probable others as well.
