### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ZenoNiQ** [ShareX/ShareX#1925]
Question, 
1. How can I turn on default upload from clipboard? (as like from browser download) Cuz when I dl it by sharex it's dl file with watermark.(
![image](https://cloud.githubusercontent.com/assets/1075196/18695139/49aa08d4-7fb8-11e6-8328-487036e1a6aa.png)
)
U can reproduce it here http://joyreactor.cc/ by dl any GIF.
1. Where I can find an option to upload files more then 10MB to another host? 
   I mean when I am trying to upload gif more then 10MB to Imgur, API blocked it and I want to upload it to GFYCAT instead so I am trying to switch it here to secondary image uploader "File hoster" it's back error  
   ![image](https://cloud.githubusercontent.com/assets/1075196/18695052/c9870418-7fb7-11e6-84e7-506b4232a02d.png)

**Comment by Jaex** [comment]
What you mean default clipboard upload? What browser download to do with clipboard upload? How file can be downloaded with watermark?!

ShareX don't have file size check to change to different uploader.

**Comment by ZenoNiQ** [comment]
> What you mean default clipboard upload? What browser download to do with clipboard upload? How file can be downloaded with watermark?!
When you share GIF/JPG URL from that site on another one it will add to your pic watermark, but when you dl it directly to the PC, no any watermark will be added, so I just ask how can I emulate direct dl to PC?

**Comment by ZenoNiQ** [comment]
Reproduce: 
1. Just DL this pic to PC directly 
http://img0.joyreactor.cc/pics/post/Terry-Crews-%D0%B3%D0%B8%D1%84%D0%BA%D0%B8-3377144.gif
2. And dl it by clipboardURL upload in this step it will add watermark.

**Comment by ZenoNiQ** [comment]
Just what i mean i want to do
1. Click shift+%keyname%
![image](https://cloud.githubusercontent.com/assets/1075196/18722711/6ae26e0c-803e-11e6-918a-a83bf1392324.png)

(In this step it dl it with watermark )

2. sharex choose if file more then 10MB> upload it to second hosting, i think i can do it by retry here https://cloud.githubusercontent.com/assets/1075196/18695052/c9870418-7fb7-11e6-84e7-506b4232a02d.png

**Comment by Jaex** [comment]
http://img0.joyreactor.cc/pics/post/Terry-Crews-%D0%B3%D0%B8%D1%84%D0%BA%D0%B8-3377144.gif I downloaded this from browser, it have watermark same as ShareX one.

**Comment by ZenoNiQ** [comment]
oh yes, i tested it, when u logged it to site only then no watermark.  https://gfycat.com/BreakablePossibleEasternnewt

But what about another question if first time img don't upload to imgur must it be upload to another host ? As like  in pic to "file uploader" (my file uploader option is GFYCAT)
