### ISSUE TITLE
It does not change the aspect ratio

### ISSUE THREAD

**Issue by Detsle** [ShareX/ShareX#1926]
Good afternoon,
Change the settings in the image format, and saving (http://i.imgur.com/8lpyz8Y.jpg), it becomes equal to the default of PNG (http://i.imgur.com/Q2znxow.jpg).

**Comment by Jaex** [comment]
Save dialog choices current file name extension automatically. It is intended behavior.

**Comment by Detsle** [comment]
Perhaps to make the default Jpeg?

**Comment by Jaex** [comment]
Years ago I would agree because people had slow internet connection but these days people prefer png more than jpg because internet connections significantly faster than before.
