### ISSUE TITLE
Error when uploading to VPS using SFTP.

### ISSUE THREAD

**Issue by AlphaYus** [ShareX/ShareX#1927]
> Renci.SshNet.Common.SftpPathNotFoundException: No such file
>    at Renci.SshNet.Sftp.SftpSession.RequestOpen(String path, Flags flags, Boolean nullOnError)
>    at Renci.SshNet.Sftp.SftpFileStream..ctor(ISftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize, Boolean useAsync)
>    at Renci.SshNet.Sftp.SftpFileStream..ctor(ISftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize)
>    at Renci.SshNet.SftpClient.Create(String path)
>    at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
>    at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadFile(Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)

When testing the connection, it connected, and even created the directory specified as the upload path, but upon trying to upload anything at all, it hangs and gives me this error.

**Comment by jimmydorry** [comment]
Sounds like a user issue. I just setup SFTP for my site, and saw all kinds of issues like the above, while my VM was incorrectly setup.

I used the following guides to get it working:

https://www.digitalocean.com/community/tutorials/how-to-add-and-delete-users-on-an-ubuntu-14-04-vps

https://bensmann.no/restrict-sftp-users-to-home-folder/

http://www.thegeekstuff.com/2012/03/chroot-sftp-setup
