### ISSUE TITLE
Right-clicking Traytool icon for ShareX while doing a region Capture causes user to lose ability to switch apps

### ISSUE THREAD

**Issue by chrisofevil123** [ShareX/ShareX#1928]
If the user right clicks on the ShareX traytool shortcut during a screen region capture, they help menu and region capture take complete focus from the PC.  You can open task manager, but cannot force close the app - and switching between apps fails because ShareX appears to continually steal focus.

**Comment by Jaex** [comment]
You already reported this with email 4 minutes ago...

**Comment by chrisofevil123** [comment]
I did!  Wow, that was fast. I realized I could just write my own bug report.  I didn't realize it would duplicate.

**Comment by chrisofevil123** [comment]
Jaex, I would be happy to close this bug report if you'd prefer to work from the email.

**Comment by Jaex** [comment]
I already replied your email 5 minutes ago.

**Comment by chrisofevil123** [comment]
Apologies, you're much much faster than I anticipated.  Ill continue with the email chain.

**Comment by chrisofevil123** [comment]
After speaking with Jaex, I have been unable to repro this problem despite it being easy to do a few minutes ago.  I will close this until I can find a solid repro case for the developers.
