### ISSUE TITLE
Taking a screenshot from a game and clicking "Upload, Copy URL" crashes the game

### ISSUE THREAD

**Issue by darthdeus** [ShareX/ShareX#1930]
I've tried this in two different games so far (Hearthstone and Rocket League), and it seems to work every single time.

I hit ctrl+printscreen for region selection, select a region, the menu pops up (the game still works at that point), but the moment I click "Upload, Copy URL" the game completely freezes.

This seems to be happening only since the second to last update. I've been taking screenshots for a few months without any issues, but only recently it started crashing the games.

It doesn't happen for regular programs, so my guess would be that it's tied to the program using a DirectX context. I've also tried it in my own game which uses OpenGL and it works just fine. I can't however completely confirm that this is the cause, so take it with a grain of salt.

**Comment by Jaex** [comment]
In Hearthstone I tried ctrl+printscreen and clicked "Upload, Copy URL" and game not crashed:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/Hearthstone_zufquU72F9.jpg)

I don't see how uploading can crash game.

**Comment by darthdeus** [comment]
Any idea what I can try to diagnose this? It seems to crash 100% of the time, no matter if I'm in the menu or in game.

**Comment by Jaex** [comment]
If you select just uploading from menu is it still crash? Or just canceling that menu.

**Comment by darthdeus** [comment]
Canceling the menu crashes as well, sorry I didn't notice that earlier. Actually I can interact with the game just fine while the menu is up, but clicking anything in there (cancel, upload, or just copy) crashes.

**Comment by Jaex** [comment]
Closing menu just runs `cms.Close();` so it is weird. What about without menu, did you tried normal uploading?

**Comment by darthdeus** [comment]
If I go into "After capture" and disable "Show quick task menu", it will take the screenshot as normal and upload it, and the game continues to run just fine.

But I just found something really interesting.

If the menu pops up and I click on a menu item that doesn't have Hearthstone under it (HS being in windowed mode), it doesn't crash. For example, if I take a screenshot of the bottom right corner so that the menu pops up outside of the application, I can click the menu as normal and it won't crash. This is even if the menu is partically covered by HS and I click on the side that doesn't have HS under it.

Here's what I mean

![screenshot](http://i.imgur.com/eN0SBXw.png)

**Comment by Jaex** [comment]
I still can't reproduce it.
