### ISSUE TITLE
How to make auto uploaded google drive image file URLs publicly viewable?

### ISSUE THREAD

**Issue by CodersRock** [ShareX/ShareX#1931]
Hi Jaex and team

LOVE ShareX google drive upload feature

after capture, it comes up in browser with following link URL structure:
https://doc-0s-0c-docs.googleusercontent.com/docs/securesc/icbrq6 etc etc

I tried looking at settings to change it so that when uploaded to Google drive, the link can be immediately viewed by anyone publicly (not just by the owner)

how can this be done?

Thank you!

**Comment by Jaex** [comment]
Did you not selected this?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/ShareX_7NhbG7rPwM.jpg)

**Comment by CodersRock** [comment]
yes i selected it
i also selected below "use direct link"

Does that matter?
what is "direct link" - the URL of the file uploaded into google drive?
