### ISSUE TITLE
[Enhancement] Apply regex to URL on after upload, then copy to clipboard. (Regex.Replace)

### ISSUE THREAD

**Issue by JoKneeMo** [ShareX/ShareX#1932]
I've been digging around and reading many forums. I can't see to find a way to change the URL that is copied to the clipboard when using an API uploader.

In my specific case I am using the Seafile uploader and it only returns a $result and $url value.

The $result appears as `https://fileshare.mycompany.com/f/a0b1c2d3e4`

I want the actual URL copied to the clipboard to change to `https://fs.tt/f/a0b1c2d3e4`

ShareX already has the feature to change HTTP to HTTPS, so it seems like it would be fairly simple to have it change $result domain to a new domain. But for this to resolve issues for existing and future users, it seems a general regex replace would be the best feature.

**Comment by moonman407** [comment]
@Jaex Any idea if this is currently possible?

**Comment by Jaex** [comment]
No.

**Comment by moonman407** [comment]
For anyone that comes up with this same request, I was able to work around it by using the [Polr ](https://github.com/Cydrobolt/polr)URL shortener.

**Comment by Jaex** [comment]
I'm planning to implement this in next release.

**Comment by Jaex** [comment]
Added it now:

![](https://jaex.getsharex.com/2020/09/ShareX_6YkmNxH64l.png)
