### ISSUE TITLE
Problem with capture

### ISSUE THREAD

**Issue by zzz232** [ShareX/ShareX#1938]
Hello, pls help how to fix this? http://imgur.com/7aNRsjN

before everything was normal. I do not know why it's broken

**Comment by dannoe** [comment]
Right-Click while taking Screenshot -> Region: Rectangle

**Comment by zzz232** [comment]
when i click right-click programm make full screenshot

sorry for my bad english

**Comment by zzz232** [comment]
fixed, thanks!

**Comment by Jaex** [comment]
#1778
