### ISSUE TITLE
Recording lag

### ISSUE THREAD

**Issue by dapal-003** [ShareX/ShareX#1939]
Hello, 

I was just wondering if it would be possible to record mp4's with audio with out them being laggy.
https://a.pomf.cat/hkkyli.mp4 This is what a mp4 looks like with audio
https://a.pomf.cat/rwltxv.mp4 This is what a mp4 looks like wihtout audio

As audio source i have to use the virtual audio capture because for some reason it won't record audio from Voicemeetere.

This is the command line with audio
-y -rtbufsize 100M -f gdigrab -framerate 60 -offset_x 0 -offset_y 0 -video_size 1920x1080 -draw_mouse 1 -i desktop -f dshow -i audio="virtual-audio-capturer" -c:v libx264 -r 60 -preset ultrafast -tune zerolatency -crf 30 -pix_fmt yuv420p -c:a aac -strict -2 -ac 2 -b:a 320k "output.mp4"

This is the command line without audio
-y -rtbufsize 100M -f gdigrab -framerate 60 -offset_x 0 -offset_y 0 -video_size 1920x1080 -draw_mouse 1 -i desktop -c:v libx264 -r 60 -preset ultrafast -tune zerolatency -crf 30 -pix_fmt yuv420p "output.mp4"

Thank you reading/responding

**Comment by KSib** [comment]
I've also experienced this, but I had my capture set  to 60 FPS instead of 30 FPS:

Settings with audio enabled:

```PowerShell
-y -rtbufsize 100M -f gdigrab -framerate 60 -offset_x 0 -offset_y 0 -video_size 2560x1440 -draw_mouse 1 -i desktop -f dshow -i audio="Microphone (High Definition Audio Device)" -c:v libx264 -r 60 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -c:a aac -strict -2 -ac 2 -b:a 128k "output.mp4"

**Comment by nicefox1** [comment]
same here.

with audio disabled its ok
with audio enabled it lags the same like op and almost no cpu usage

**Comment by AshkoreDracson** [comment]
Still a problem to this day.

It lags only when audio is enabled, trying to fiddle with quality settings of the audio or changing the audio input does the same.

**Comment by Jaex** [comment]
Both recording and encoding happens inside FFmpeg (unless you are using external devices for recording) and not to do with ShareX.

**Comment by doneykoo** [comment]
Here's my workaround for the lag issue when recording with audio, which at least works well in my case (win10). 

ShareX -> Task Settings... -> select tab: Screen recorder -> click Screen recording options... -> click Install recorder -> follow the setup steps and finish installation -> make sure the Screen recording options now selects screen-capture-recorder for Video source, and virtual-audio-capturer for Audio source.

![snipaste_2018-01-27_20-54-08](https://user-images.githubusercontent.com/1118771/35472131-3ee29cf6-03a4-11e8-9b4f-e0da15db5003.png)

**Comment by dapal-003** [comment]
I have them both already enabled, doing just that didn't seem to fix it for me. However since I have a nvidia gpu I can use the build in Nvenc encoder allowing me to record things without lag just fine. These are the current settings I'm using that work great for me. https://i.imgur.com/T0RPIJ0.png

**Comment by Mighty72** [comment]
> 
> 
> I have them both already enabled, doing just that didn't seem to fix it for me. However since I have a nvidia gpu I can use the build in Nvenc encoder allowing me to record things without lag just fine. These are the current settings I'm using that work great for me. https://i.imgur.com/T0RPIJ0.png

This solved it for me. Now it works flawless. Many thanks!  :)

**Comment by lynrayy** [comment]
Maybe i should smehow change -rtbufsize?

**Comment by d0verenny** [comment]
I'm using Nvenc and it is supposed to make things faster. Yet it's 2025 and here we are! Nothing helps, the recording is jittery AF
