### ISSUE TITLE
Freehand

### ISSUE THREAD

**Issue by v2k** [ShareX/ShareX#1941]
I can't seem to capture a region as normal; it's always in freehand mode?  How does one capture a rectangle region now?

e.g.
![image](https://cloud.githubusercontent.com/assets/608250/18846842/9c387626-83dc-11e6-97ae-eeca79981423.png)

**Comment by Jaex** [comment]
#1778

**Comment by v2k** [comment]
Thanks; maybe it's worth disabling the mouse wheel behaviour by default.

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/commit/9f6b3cf63aeae3bfa93b70de02398f68bfe7f220
