### ISSUE TITLE
Convert ShareX to UWP

### ISSUE THREAD

**Issue by bdbch** [ShareX/ShareX#1942]
I think you guys would be featured on the Windows 10 Store if you convert ShareX.

I'll try to convert and give you feedback asap!

**Comment by Jaex** [comment]
I bet there will be alot of limitations when converting and it will fail somewhere.

**Comment by db2k** [comment]
I'll try that right now and give you feedback on my try! @Jaex

**Comment by db2k** [comment]
So I converted and signed the application. It's running now and I'll test some features around it.

Here are the first screenshots:

### main view
![image](https://cloud.githubusercontent.com/assets/6538827/18850848/9d77b2f6-8439-11e6-9acb-2f9104112aa4.png)

### windows menu app icon
![image](https://cloud.githubusercontent.com/assets/6538827/18850867/ada8221e-8439-11e6-86f2-4ec2ba7be28c.png)

### colorpicker tool
![image](https://cloud.githubusercontent.com/assets/6538827/18850944/0b26256c-843a-11e6-8d75-55b2dca5916e.png)

### Gifs (generated by my shareX UWP App)
* **Colorpicker**: http://i.imgur.com/YSTCrq0.gifv
* **Several Tools**: http://i.imgur.com/h3MmPrF.gifv

### Works:
* Uploading Files from context menu
* Screenshots ( the screenshots were done via my converted app )
* Changing Configurations
* Tray Icon
* Changing Hotkeys
* Defining Upload Targets
* Colorpicker Tool
* Image Editor
* File Compare Tool
* QR Code Generator
* Measurement Tools
* Automator
* Index folder
* Monitor check
* ffmpeg Tools
* ffmpeg Downloader

---

So for now I didn't find any problem.

I converted via this command (with the current installation .exe)
`DesktopAppConverter.exe -Installer H:\Downloads\sharex\ShareX.exe -InstallerArguments "/S /silent /quiet /norestart" -Destination H:\Downloads\ShareXUWP -PackageName "ShareX" -Publisher "CN=ShareX" -Version 0.0.0.1 -MakeAppx -Verbose -Sign`

**Comment by db2k** [comment]
I guess the guys from www.reddit.com/r/Windows10 will love you

**Comment by Jaex** [comment]
Is it require code sign certificate?

**Comment by db2k** [comment]
It requires a certificate for the Appstore and Installation, yes.
For testing purposes you can sign the app yourself via `-Sign`

**Comment by Jaex** [comment]
I don't have certificate.

**Comment by db2k** [comment]
I just found this.
https://developer.microsoft.com/en-us/store/register
I would get an certificate but I don't think I'm allowed to add ShareX to the Appstore?

**Comment by db2k** [comment]
Looks like the certification is done by Microsoft as soon as the Application is deployed to the Store. The Certification checks if the tool is clean (no viruses, etc.) and checks other requirements.

I don't think ShareX will fall through though.

**Comment by Jaex** [comment]
I can't risk paying 20$ without be sure about is code sign certificate required.

**Comment by db2k** [comment]
Since I wanted to get a Microsoft Development Account anyway I could try?

**Comment by Jaex** [comment]
Try what?

**Comment by db2k** [comment]
Adding it to the Appstore. I'm currently playing around with the application manifest and optimizing the meta data. after that I could try "package" a final appx container for the store?

Just need confirmation that I could add it to the store for you.

**Comment by Jaex** [comment]
Unfortunately I can't allow that. Because I don't know you. It won't be right to allow random person to add our software to Windows Store officially.

**Comment by db2k** [comment]
To bad. Well :/ Any plans for the future since the tool seems to work fine?

**Comment by Jaex** [comment]
If it not require code signing certificate then I can pay 20$ and add it. But how to be sure about it.

**Comment by db2k** [comment]
It won't change. I just checked and you need to register with your 14€ payment as soon as you want to register as a dev so no chance to check the certificate before then.

**Comment by Jaex** [comment]
What you mean it won't change. If certificate is required then it would be waste of time and money to register.

**Comment by db2k** [comment]
thanks for considering anyways.

I think we should look out for the future. Since UWP apps getting more attention now, people will look out more for them.

(see Evernote, Adobe with Adobe XD, etc).

**Comment by Jaex** [comment]
Did you encountered any problem in converted app?

**Comment by db2k** [comment]
Not really, I'm using it right now instead of the desktop app. See my report from above:
https://github.com/ShareX/ShareX/issues/1942#issuecomment-249692304

for now there are no bugs what so ever.

**Comment by Jaex** [comment]
Are you using Steam?

**Comment by db2k** [comment]
yes. is there something I should test?

**Comment by Jaex** [comment]
I thought we can talk in Steam if I need help when trying it.

**Comment by db2k** [comment]
Sure.
http://steamcommunity.com/profiles/76561197998341154/

**Comment by vitorgrs** [comment]
Jaex, I can give you a voucher to get a free developer account for you ;)

**Comment by db2k** [comment]
@vitorgrs you're the man! 👍 feel free to grab some free beer with me if you're in germany at some point. 😄

**Comment by Jaex** [comment]
I was just about one click away to pay it, what you mean voucher?

**Comment by vitorgrs** [comment]
I have a unused student voucher (as I'm student but already have a dev account from few years ago). All students get a free dev voucher to get a free dev account. But if you want to pay for it... 😛

**Comment by Jaex** [comment]
Well I went to bank in 01:00 am just to pay for this, so I better pay it :P
If you told it before I go to bank then I would accept it :(

**Comment by vitorgrs** [comment]
And some notes on how it works... you can create your own certificate (the same store give details to create). But for now, Win32 is closed on submissions afaik, but I know a few people on MSFT that can help you.

**Comment by db2k** [comment]
Oh you just went to the bank @Jaex? Thanks man, you guys rock.

Also looking forward to give support via steam or here on Github.

**Comment by Jaex** [comment]
In billing email it tells I bought "Windows and Windows Phone yearly developer registration" (in my language)

What it means "yearly"?!

**Comment by db2k** [comment]
Maybe @vitorgrs knows more about it. As far as I know there is no yearly plan (it's one lifetime payment).

**Comment by Jaex** [comment]
There was no info about it being yearly in registration pages, so I have no idea why it tells yearly in billing result email.

**Comment by vitorgrs** [comment]
Are you sure? Here it says is lifetime...
https://developer.microsoft.com/en-us/store/register
> This is a one-time registration fee and no renewal is required.

**Comment by Jaex** [comment]
This is what I got in email (translated it to english):

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/chrome_rXlnINs7L9.jpg)

**Comment by db2k** [comment]
This shouldn't be annual, you paid the turkish price right?

**Comment by Jaex** [comment]
Yes.

**Comment by vitorgrs** [comment]
Probably just outdated name, maybe? As right now is just Windows account, not Windows Phone even. And also work for Xbox... a few years ago it was annual, but they changed and it's lifetime. I have my account for like, 3 years.

**Comment by db2k** [comment]
From the Microsoft Help Center:
https://msdn.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees

> * Restricted from using certain app capabilities
> * Costs approximately $19 USD (one-time registration fee; the exact amount varies depending on your country or region)

**Comment by db2k** [comment]
so all good. you're a licensed microsoft developer now! 👍

**Comment by Jaex** [comment]
I sent message to Microsoft support to verify is it really outdated name.

**Comment by notnsane** [comment]
@Jaex if you have any doubts about the Windows Store, ask me, I have one app there already. 

Some quick tips: 
1. Don't worry about "code certification" and "signing", you don't need to do that (I didn't)
2. The certification process will take between 5-10 business days even though it says 48 hours

Thanks for doing this! We need more popular awesome apps on the Windows Store! 💃 

If you don't have it yet, go request a BizSpark account right now, since you have a business: https://bizspark.microsoft.com
With BizSpark you get a free MS Developer account to publish, and also thousands of other software (like several Windows licenses). So, even if you already paid, you can get a bunch of stuff for free. Again, if any doubts, ask me.

I can help you with the process, and if you want, you can join us on the Windows Discord for quicker help: https://discord.gg/microsoft

Wish I would read this sooner. Cheers!

**Comment by Jaex** [comment]
All these years I didn't bought Microsoft Dev account and right after buy it you guys keep telling me ways to get it free :(

**Comment by db2k** [comment]
Sorry man, I didn't knew. Also purchased my license already so I feel with you :D

**Comment by adamnoffie** [comment]
Mayhaps some of these folks so interested in @Jaex getting this setup could donate to help reimburse him for the dev account.  https://getsharex.com/donate/

Wouldn't take much, couple bucks per person in this thread.  😄

**Comment by db2k** [comment]
Already talked with him about donations. I'm full in for donations.

**Comment by Jaex** [comment]
I don't want donation. I just want to solve these problems:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/DACTileLauncher_5SjPKzBZbn.png)

**Comment by db2k** [comment]
This problem is super strange. It seemed to work for him, but his Powershell doesn't accept `Set-ExecutionPolicy bypass`. The Powershell always tries to open some file.

@Jaex did you tried bypassing the ExecutionPolicy via Registry? I think this is why it says `...this OS platform`

**Comment by Jaex** [comment]
I didn't.

**Comment by db2k** [comment]
Could you try it? I don't know why your Powershell is bugging out on the Set-ExecutionPolicy tool, maybe it's an installed application we don't use but anyway, I think the only problem is the restricted Execution policy.

**Comment by Jaex** [comment]
`Cleanup All	Deletes all expanded base images, removes any temporary converter files, removes the container network, and disables the optional Windows feature, Containers.`

Maybe this can fix it because this problem happened right after expand base image. But I can't even manage to run exe to be able to give parameter to it. Just because it is Windows Store app so many access problems etc.

**Comment by db2k** [comment]
@Jaex any news yet?

**Comment by Jaex** [comment]
What news? After try to fix it for many hours, I gave up.

**Comment by Jaex** [comment]
Now I was reinstalled Windows 10 and this time it worked properly.

But I noticed there is problem in desktop bridge, it checking this `C:\Program Files (x86)\Windows Kits\10\bin\x64` folder for `MakeAppx.exe` but Visual Studio 2017 was already installed Windows SDK stuffs and standalone Windows SDK setup was telling "Features installed on this computer are up-to-date", then I noticed those stuffs actually stored inside: `C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64` folder so I just copied x64 folder to previous folder path and it worked. So desktop bridge was not aware of new Windows SDK paths.

Currently in my testing appx ShareX could even be able to detect custom personal path from user appdata folder and be able to use configured setting files from another drive.

But implementing this tab gonna be very difficult:

![](http://i.imgur.com/aNK2Qop.png)

We can set startup auto run in manifest file but it is crucial for this setting to be configurable by user from UI therefore not sure how to accomplish that.

**Comment by charlesmilette** [comment]
The TaskId setting for the autorun in manifest can be resolved to a [StartupTask](https://docs.microsoft.com/fr-ca/uwp/api/Windows.ApplicationModel.StartupTask) object which in turn can get disabled or enable quite easily.

**Comment by notnsane** [comment]
is there any way you can automatically disable all the other options expect "run sharex when windows starts"?

That's one of the predicaments of UWP apps, you can't run anything at admin level or write registry. I see no problem with that, since that's a limitation I prefer to avoid future issues.

**Comment by db2k** [comment]
@Jaex is there a test version of your converted app I could try out to see if I can find other things which are not working as intended?

**Comment by Jaex** [comment]
I keep having a lot of trouble for example right now when I read `"C:\Users\username\AppData\Local\ShareX\PersonalPath.cfg"` it returning zeros. Therefore ShareX gives error on startup.

**Comment by db2k** [comment]
Thats strange, since users should have permissions and access on their own user directories. Is there maybe a issue with some permission/scope of the application when generated?

**Comment by Jaex** [comment]
I'm moving `%localappdata%\ShareX\PersonalPath.cfg` to `Documents\ShareX\PersonalPath.cfg` in desktop builds as solution. So WindowsStore build can access or change them.

**Comment by Jaex** [comment]
By the way sharing test builds can be problem because of certificate.

**Comment by Jaex** [comment]
By the way sharing test builds can be problem because of self signed certificate.
But I need testers for Windows Store build, so not sure what to do.

**Comment by db2k** [comment]
Okay but great one. still looking forward for the Store Release (Would be good for Windows S users too in the future)

**Comment by Jaex** [comment]
I'm gonna use this option in Windows Store:

![](https://jaex.getsharex.com/2017/05/chrome_ZHpXolz19E.png)

**Comment by bdbch** [comment]
Cool, could you send me a link so I could test it again?

**Comment by Jaex** [comment]
Currently I'm stuck at store listing section because it require a lot of english text and image making. So didn't put to store yet.

**Comment by bdbch** [comment]
Any news? :) Would love to test it out asap and give it a good rating.

**Comment by Jaex** [comment]
I sent it to Windows store today and waiting for it to show up. And I can give beta keys after that.

**Comment by bdbch** [comment]
Awesome man, thank you very much!

**Comment by Jaex** [comment]
By the way you can get latest info about its status from ShareX Discord server. I will also send beta keys there because with direct message it will be easy.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/05/ApplicationFrameHost_mH1SCsoK3J.png)

I'm giving beta keys to anyone request in ShareX Discord server now.

**Comment by Jaex** [comment]
Released on Windows Store now: https://www.microsoft.com/store/apps/9nblggh4z1sp

**Comment by bdbch** [comment]
Awesome. Thanks!
