### ISSUE TITLE
Placement of Preview Window in Main Dialog

### ISSUE THREAD

**Issue by adamnoffie** [ShareX/ShareX#1943]
I'm guessing 95% of screenshots taken on today's widescreen monitors are, themselves, wider than they are tall.   This seems to hold true for me for sure.  But in order to see all of the columns (useful) in the screen capture list in the main dialog of ShareX, I usually have to shrink down the preview area until it is more vertical than horizontal, do to them being placed side-by-side.

May I politely suggest that by default, or perhaps as an option at least, the preview window be placed below (or even above) the file list, so that they both have more horizontal real-estate to work with?

Visual of what I'm referring to:
![image](https://cloud.githubusercontent.com/assets/98626/18852117/ac525806-8404-11e6-9b11-4913e047b97f.png)

Thanks much for your consideration!

**Comment by Jaex** [comment]
In this default window size:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/ShareX_RnYAkA2kZL.jpg)

How you can suggest me to add preview vertically as default, I'm failing to understand. If I add that then there will be empty space for like 2 or 3 rows to be visible. Your suggestion only makes sense when people make ShareX window height very big like in your ss and it is very rare case.

**Comment by adamnoffie** [comment]
I think maybe the point is not about the size of ShareX, but rather the average size (or aspect ratio, to be more precise) of your average screenshot.  I guess I'd love some input from other users - maybe I'm odd - but for me my **screenshots themselves** tend to be very wide aspect ratio, and the issue is that they get scaled way down in the vertically tall/narrow preview window you get when trying to view all your columns in the list as well.  Maybe an example with my window sized more like your default there will make my point:

![image](https://cloud.githubusercontent.com/assets/98626/18878983/55806dda-8498-11e6-992c-f2e03d492082.png)

You can see in that capture that when you have widescreen screenshot in a narrow preview window, it has to scale it way down to the point that it is difficult to see what the screenshot even is.

Here is another example, showing how narrow (and thus less useful) I have to make the file list to see the preview window at or near 100% zoom:

![image](https://cloud.githubusercontent.com/assets/98626/18879142/d9b45c56-8498-11e6-8297-075222189064.png)

I guess it might be better still to have the option of either, rather than just changing the default, but I figured that might be more difficult programming.  I do admit though that if someone tends to take more square or vertically tall screen captures (which seems odd to me, but I'll admit it is possible) they might like the default layout more.
