### ISSUE TITLE
FTP upload results in corrupted file

### ISSUE THREAD

**Issue by Hakairo** [ShareX/ShareX#1947]
I recently updated and always used ftp upload. Now the files are always corrupted after FTP upload:
http://bit.ly/2dAaAdo
The file on my pc is okay and uploading it manually (via filezilla) results in a good image. Only FTP upload via sharex fails. Uploading to imgur works, changing image format and similiar settings would not help so far.

**Comment by Jaex** [comment]
Are you using ShareX 11.3.0?

**Comment by Hakairo** [comment]
No, it is 11.2.1

**Comment by Jaex** [comment]
Try 11.3.0

**Comment by Hakairo** [comment]
Works with this version. thanks.

**Comment by Jaex** [comment]
#1797
