### ISSUE TITLE
How to make ShareX ask if I want to upload?

### ISSUE THREAD

**Issue by TWiStErRob** [ShareX/ShareX#1951]
Currently if I make a region capture or a GIF region capture it automatically uploads to Imgur, what I want is to review the captured file first and then upload if I'm satisfied with the capture. This would best be as a dialog showing the image and asking if I want to upload. Is there a config for this or it's not implemented yet?

**Comment by Jaex** [comment]
Check this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/ShareX_KTnBD2uYhT.png)

**Comment by TWiStErRob** [comment]
Ah, man, I was looking all over in the settings... :)
Thanks.

Note: the preview doesn't work for GIF capture. It shows a checkered grid only.

**Comment by TWiStErRob** [comment]
Should I open another issue for GIF or is it known?

**Comment by Jaex** [comment]
I can't draw animated gif, it is complicated.

**Comment by TWiStErRob** [comment]
Huh? You can create gifs but not draw them? You should at least put this info into the users face when "previewing a gif".

So is there any way to preview the GIF I just captured before uploading?

**Comment by TWiStErRob** [comment]
GIF works in other parts of the app:

![o7stjv5](https://cloud.githubusercontent.com/assets/2906988/18989321/ac6c0d8c-870b-11e6-9f88-9f5f065de8d9.gif)

**Comment by Jaex** [comment]
I understood your issue wrong. Ignore my previous message.

**Comment by TWiStErRob** [comment]
When I make a GIF recording the "After capture" is empty:
![image](https://cloud.githubusercontent.com/assets/2906988/18989684/911ef592-870d-11e6-9032-dca08ab04520.png)

**Comment by TWiStErRob** [comment]
Thanks for the quick fix, looking forward to 11.3.1/11.4 if I saw the tags correctly.

**Comment by Jaex** [comment]
You can download latest setup from https://ci.appveyor.com/project/ShareX/sharex

**Comment by TWiStErRob** [comment]
Awesome, found it. It works, but I found two cosmetic issues on first try:

1. "Loading image: 93%" stuck even after the recording played many times  
![image](https://cloud.githubusercontent.com/assets/2906988/19015946/6e67f7c2-880e-11e6-847e-fffddb74ad17.png)
2. Clicking to preview to go full screen results in artifacts:  
![image](https://cloud.githubusercontent.com/assets/2906988/19015967/de34523a-880e-11e6-83a8-ce004014f6ab.png)

original capture:
![2016-10-01_19-35-39](https://cloud.githubusercontent.com/assets/2906988/19015972/e9d3e448-880e-11e6-878c-c6e0f5f9e16a.gif)

**Comment by Jaex** [comment]
Both bug of .NET picture box control.

1. Sometimes LoadCompleted event not triggers so can't know it is completed loading to hide status label.

2. If one animated gif used in two different picture box then this corruption happens in animation. And interestingly this even happens if I clone image and use that cloned image in fullscreen preview picture box.

**Comment by TWiStErRob** [comment]
That's nasty. For 1) did you try adding the following to `MyPictureBox.pbMain_LoadProgressChanged`:
```cs
} else {
    pbMain_LoadCompleted(sender, new AsyncCompletedEventArgs(null, false, null));
}
```

**Comment by Jaex** [comment]
That status issue happens rarely so I can't reproduce it to test is progress changed event reports 100 when completed event not triggered. Normally it reports 100 but need to test it when completed event is not triggered too.
