### ISSUE TITLE
TargetInvocationException

### ISSUE THREAD

**Issue by Ruffus2000** [ShareX/ShareX#1953]
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.BadImageFormatException: Die Datei oder Assembly "ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
   bei ShareX.TaskSettingsTools..ctor()
   bei ShareX.TaskSettings..ctor()
   bei ShareX.ApplicationConfig..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance[T]()
   bei ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   bei ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   bei ShareX.Program.LoadProgramSettings()
   bei ShareX.Program.Run()
   bei ShareX.Program.Main(String[] args)

ShareX 11.3 (Release)

Logfile:
2016-09-30 18:12:41.333 - ShareX continue.
2016-09-30 18:12:44.596 - Build: Release
2016-09-30 18:12:44.596 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2016-09-30 18:12:44.598 - ShareX 11.3
2016-09-30 18:12:44.599 - Personal path: D:\Eigene Dateien\ShareX
2016-09-30 18:12:44.600 - Operating system: Windows 10 Home
2016-09-30 18:12:44.604 - ApplicationConfig load started: D:\Eigene Dateien\ShareX\ApplicationConfig.json
2016-09-30 18:12:44.737 - ApplicationConfig load failed: D:\Eigene Dateien\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   bei ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-30 18:12:44.738 - ApplicationConfig load started: D:\Eigene Dateien\ShareX\ApplicationConfig.json.bak
2016-09-30 18:12:44.739 - ApplicationConfig load failed: D:\Eigene Dateien\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   bei ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-30 18:12:44.741 - ApplicationConfig not found. Loading new instance.
2016-09-30 18:12:44.762 - Unhandled exception:
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.BadImageFormatException: Die Datei oder Assembly "ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
   bei ShareX.TaskSettingsTools..ctor()
   bei ShareX.TaskSettings..ctor()
   bei ShareX.ApplicationConfig..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance[T]()
   bei ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   bei ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   bei ShareX.Program.LoadProgramSettings()
   bei ShareX.Program.Run()
   bei ShareX.Program.Main(String[] args)

ShareX 11.3 (Release)

**Comment by Jaex** [comment]
#1615
