### ISSUE TITLE
Lambda.sx / λ.pw Upload not working

### ISSUE THREAD

**Issue by carrageen** [ShareX/ShareX#1954]
Before you ask: I checked my API key twice and even tried it with a new account. Still not working.

![i_view32_2016-09-30_19-02-54](https://cloud.githubusercontent.com/assets/19150352/18999995/847214ae-8740-11e6-8c0f-548c88832734.png)

![sharex_2016-09-30_18-56-57](https://cloud.githubusercontent.com/assets/19150352/18999919/2840d918-8740-11e6-82c8-189853fab444.png)

Message:
The remote server returned an error: (502) Bad Gateway.

Response:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Upload failed for unknown reason. Check your API key.

As I said, I already checked my API key, cleared cookies and it's still not resolved.

**Comment by Jaex** [comment]
502 Bad Gateway
cloudflare-nginx

These two sentences shows there is problem in their server.
