### ISSUE TITLE
'Perform Actions' doesn't work when %input is used and 'Save image to file' isn't also enabled

### ISSUE THREAD

**Issue by arcastro** [ShareX/ShareX#1955]
If 'Save image to file' isn't enabled, the Action won't even trigger - and no error shows up on the Debug Log. 

In this case, the image should be saved to the OS's temp folder so that the Action will still trigger and work correctly.

Open to suggestions.

**Comment by Jaex** [comment]
Just for this reason I was added "Delete file locally" option in "After capture tasks" so it can clean up temporary saved image.
