### ISSUE TITLE
Unexpect 'perform actions' executed before upload a picture

### ISSUE THREAD

**Issue by acethical** [ShareX/ShareX#1957]
This issue is resemble my last issue: https://github.com/ShareX/ShareX/issues/1837
Now I setting ShareX like this:

<img src="http://img2.lght.pics/b33841467935aa3e984330f76d80b49d.png"/>

When capture a picture, I hope ShareX does 2 things
1, Save the picture to desktop
2, Preview the picture with my photo viewer (JPEGView) ---- **this causes issue**
as below

<img src="http://img.lght.pics/d5c2fd521e6c2ec28e34a6f5bf349740.png"/>

Until here, all things are normally. ShareX runs with my willing.

----Below is the issue----

My 'after upload' setting is this

<img src="http://img1.lght.pics/87d91476c0dd4692f905837a263bf7f8.png"/>

When I upload a picture, all I need is: 
1, Show "After upload" window
2, So I can copy the links easily. 

Issue:
When I try to upload a picture, ShareX doesn't upload it, but open the picture with photo viewer (actually, ShareX does 'perform actions' before upload)
And it **won't upload** the picture as well.
**Until** I stop the 'perform actions' (close photo viewer), ShareX starts upload.

If I uncheck 'perform actions' in 'After capture tasks', ShareX will upload pictures immediately.
I think there is a bug somewhere. Because there's no need to preview the picture before upload everytime.

**Comment by Jaex** [comment]
It is expected behavior. It waits so if image is modified with external editor. Then modified image can be uploaded.
