### ISSUE TITLE
Auto selected region capture

### ISSUE THREAD

**Issue by Lapin-Blanc** [ShareX/ShareX#1958]
When using ctrl+printscreen to select a region, hovering windows, menus, etc. autoselects those items (inner zone of a window in my case).
I can't find a way to capture those suggested areas ?
For exemple, I would like to capture the suggested **x:173, 7:205, w:800, h:640** in the image below
![sharex_-_capturer_une_region__2016-10-01_11-48-58](https://cloud.githubusercontent.com/assets/2578326/19013295/20481950-87cd-11e6-95c2-ba89697c35b6.png)

**Comment by Jaex** [comment]
Normally it captures when you click it once. I guess you enabled multi region mode so it requires double click. You can press `Q` to disable multi region mode.

**Comment by Lapin-Blanc** [comment]
Damn, it was so simple, I've been looking too far ! Thank you for your quick response !
