### ISSUE TITLE
[Feature request] Disable cursor on screenshot use hotkey

### ISSUE THREAD

**Issue by Kristinita** [ShareX/ShareX#1959]
### Request

It would be very nice if to be added the ability remove the cursor at the time of selection of the area in the screen, when I make screenshot.

### Justification

When I select the area of ​​the screen to take a screenshot, I often notice that the mouse cursor enters the selected area. 

![Enable cursor](http://i.imgur.com/4mL4CSh.png)

I have to click on the <kbd>Esc</kbd> → to move the mouse cursor from the selection area → I select the area again.

### Expected behavior

I select area → if cursor is situated in my area, I press any hotkey, for example, <kbd>Numpad1</kbd> → cursor was removed at selection area. 

Thanks.

**Comment by Jaex** [comment]
You can disable cursor just for region capture workflow:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/ShareX.vshost_Ybm1JYMXEV.png)

**Comment by Kristinita** [comment]
@Jaex , I know. But I do not want to disable the cursor always. I need it often on my screenshots. Thanks.

**Comment by Jaex** [comment]
#1009

**Comment by Kristinita** [comment]
@Jaex , several people would like to see this feature. I hope that you will ever implement it. Thanks for the ShareX!

**Comment by Jaex** [comment]
I want it too. But it is complicated to implement.
