### ISSUE TITLE
UWP Apps Running in Background, Seems Like They Have Window

### ISSUE THREAD

**Issue by mkykadir** [ShareX/ShareX#1960]
In Windows 10, UWP apps are running in background even if they cannot seen in the task bar. But ShareX sees them like they have active windows.

![2016-10-01_22-55-35](https://cloud.githubusercontent.com/assets/3192210/19016720/2f87e69e-882b-11e6-92d4-6d8e649eda24.png)

If you select one of them, ShareX hides itself and captures an area where UWP window was. The following image is not a cropped image, ShareX snaps with last size of UWP window.

![2016-10-01_22-55-41](https://cloud.githubusercontent.com/assets/3192210/19016735/78be20ee-882b-11e6-8d44-9cf5b152893a.png)

**Comment by Jaex** [comment]
I already know that but how am I supposed to ignore them? Not to mention what if uwp app is visible. I already check windows for visibility and uwp apps show up as visible so I can't filter them.
