### ISSUE TITLE
Capture active window also capture Windows 10 volume adjustments and notifications

### ISSUE THREAD

**Issue by Dyr-Fenrir** [ShareX/ShareX#1962]
Greetings,

When I adjust the volume in Windows 10, I get an "overlay" in the left corner displaying the volume level but this appears on the screenshot when I use the setting "capture window", the same issue occurs when a notification (Windows 10 notifications) happens at the same time than the screenshot.

Is there a way to add a feature to hide all overlays and simply use the currently running application as the screenshot's output? Please note that I would still need to be able to record the cursor.

Thank you for your time and help.

**Comment by Jaex** [comment]
There is a way to get image from window handle but that way is not consistent because you telling window to render itself as bitmap and this not works in all windows or have other issues like incorrect window theme rendering etc. So there is no perfect way.
