### ISSUE TITLE
Up1 support?

### ISSUE THREAD

**Issue by incorpusyehtee** [ShareX/ShareX#1963]
Hello, is there any way to retain Up1 support in versions of ShareX above 11.3?

There are still plenty of Up1 services online.

https://share.riseup.net/ and I have a personal one.

Thanks much

**Comment by zeffy** [comment]
You can compile my [up1-support](https://github.com/zeffy/ShareX/tree/up1-support) branch to get Up1 support back for now, until its changes get merged into master (assuming they do).

**Comment by Jaex** [comment]
#1922
