### ISSUE TITLE
UseShareXForAnnotation

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#1965]
Added experimental setting to use ShareX region capture to annotate images instead of using Greenshot image editor.

Changed to True (In "Task settings -> Advanced tab -> UseShareXForAnnotation
But the Greenshot Editor still appears.
How to test the ShareX for Annotation thanx?

**Comment by Jaex** [comment]
It replacing "Tools -> Image editor" and in task list right click "Edit image".

**Comment by yllekz** [comment]
Where did this option go? It's gone as of ShareX 12.1.1.
I immensely prefer the built-in capture annotation to Greenshot's invasive full screen editor (which has less options)
