### ISSUE TITLE
Paste from clipboard: still uploads, even upload is disabled

### ISSUE THREAD

**Issue by Boorj** [ShareX/ShareX#1966]
I'm trying to make ShareX save clipboard image to local file, without upload. Without capturing area.
Have deselected **upload image to host**, leaved only **save image to file**. But it still uploads file to selected destination. 
![2016-10-02_11-58-29](https://cloud.githubusercontent.com/assets/2145313/19018708/70b8c9aa-8897-11e6-9db1-69e24a2210e0.png)

Only way that i found is use destination `shared folder`, so it save file. But i like sharex's save to folder settings, so the question is: **Is it possible to perform saving from clipboard without upload**?

**Comment by Jaex** [comment]
Yes it is possible:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/ShareX_UbW5o7z6Bs.png)

**Comment by tizosa** [comment]
Can you reupload the screenshot @Jaex ?

**Comment by Jaex** [comment]
Updated image link now.
