### ISSUE TITLE
OwnCloud download url has changed

### ISSUE THREAD

**Issue by pilovali** [ShareX/ShareX#1970]
The OwnCloud download URL has changed from ?download to /download.

**Comment by Jaex** [comment]
Isn't this setting already uses it?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/ShareX_bN0PsL5dwn.png)

**Comment by pilovali** [comment]
Ah, I'm being subborn again. I thought that it enabled some sort of legacy feature. My fault!
