### ISSUE TITLE
[11.3.0] Region capture change current tool

### ISSUE THREAD

**Issue by ZeroMaki** [ShareX/ShareX#1971]
Before 11.3.0 version I was able to change current tool by scrolling, but now I have to click control since magnifier and current tool were switched because before it was the magnifier that required control to be held down, how can I change it back because this is rather frustrating.

**Comment by Jaex** [comment]
I changed it because many people found it frustrating: #1778

Now I'm adding toolbar menu for tools maybe it can helpful for you to navigate between tools:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/ShareX_vtm90XM4RU.png)

**Comment by ZeroMaki** [comment]
Honestly, I'd much rather you add an option somewhere in the settings to toggle it back and forth, since I'm pretty close to reverting back to old version and if this isn't an option it won't be possible for me to update to later versions.
