### ISSUE TITLE
Stuck on "Preparing"

### ISSUE THREAD

**Issue by Raikia** [ShareX/ShareX#1973]
After the latest update, whenever I take a screenshot meant for file saving, it gets stuck on "Preparing"

**Comment by Jaex** [comment]
I never manage to stuck in Preparing status before so not sure how to reproduce your issue.

**Comment by Raikia** [comment]
It was me being stupid.  I take screenshots of VMs a lot (host system with sharex) and the "Save as..." dialog started popping up under the VM window.  I doubt that's fixable, but thats what the problem was if anyone else finds this issue from google
