### ISSUE TITLE
Image not saved after adding annotions

### ISSUE THREAD

**Issue by Viper007Bond** [ShareX/ShareX#1981]
I'm using the default quick task menu (I even made sure to reset it to default) and the image is not saved after adding annotations.

Steps to reproduce:
1. Press Print Screen to trigger ShareX.
2. Select the "Annotate" option.
3. Optionally add some annotations to the image in the Greenshot image editor.
4. Click green check mark in the upper-left to save and close.
5. See that nothing happens, including the lack of screenshot preview in the bottom right of the screen. No screenshot is located in the image folder.

A work-around for this is to modify the default quick task menu and add "Save image to file" to the list of "After capture tasks". This results in expected behavior. One thing to think about though if you opt to just add that action to the default quick task menu is that it won't fix it for people with custom quick task menus I assume.

**ShareX 11.3 on the latest version of Windows 10 Pro**

**Comment by campbeb** [comment]
If you just select 'Annotate' from quick task menu, then that is all that ShareX is going to do. (I understand that just annotating might not be when you intended).

From inside the Greenshot image editor, you have the options to save, upload, copy to clipboard.

**Comment by Viper007Bond** [comment]
Yep, see step 4. The green checkmark in Greenshot is "Save and close". :)

However the saved image is nowhere to be found. It's not in my default save folder (Desktop) or anywhere else on my computer as far as I can tell. Search doesn't find it.

**Comment by campbeb** [comment]
Then the green check mark should be renamed.  It just returns to ShareX for
it to do whatever was set to do. If you are choosing just Annotate, then
use save button in Greenshot toolbar if you decide to save.

**Comment by Viper007Bond** [comment]
The image being passed to Greenshot is also a Bitmap, not the PNG that my screenshots normally are. I suspect it's ShareX → temp folder → Greenshot → temp folder (although I can't find it). If you add "Save image to file" onto the quick task menu item, then ShareX saves the image as a PNG to my desktop.

**Comment by campbeb** [comment]
I'm not sure what you are trying to explain.

If you select Annotate from quick task menu, then that is all ShareX will do.
The green check mark in Greenshot being labelled "Save and close" is misleading. It should be "Confirm and close" or some such.
