### ISSUE TITLE
SSL/TLS Error (Can't upload)

### ISSUE THREAD

**Issue by kkthebeast** [ShareX/ShareX#1982]
Getting an error uploading Screenshots to any service as of this morning, Nothing has changed on my end. No new programs or applications for a month

ShareX - Error
Message:
The underlying connection was closed: Could not establish trust relationship for SSL/TLS secure channel.

StaceTrace:
at
System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
  at System.Net.HttpWebRequest.GetRequestS

**Comment by nooneto1** [comment]
This actually is easily reproduced - use a self-signed SSL cert. It also has a solution: Go to the Application Settings > Advanced, scroll down and find AcceptInvalidSSLCertificates. Set it to True.

I confirmed this using OwnCloud and the most recent version of the ShareX app as of the date of this post.

Note that URL shorteners save for Polr will not shorten HTTPS links with self-signed certificates.
