### ISSUE TITLE
Google Photos album limit

### ISSUE THREAD

**Issue by kyelbek** [ShareX/ShareX#1983]
There's 2k photos limit on picasa albums. ShareX is showing error when You try to upload any photo to filled album. I didn't know that, so I started using puush as alternative because I thought google changed something in thier API. You should add exception to inform user about it.
![2016-10-08_20-33-36](https://cloud.githubusercontent.com/assets/9123992/19215185/55c47d24-8d97-11e6-8325-02cb539bdc9d.png)

**Comment by Jaex** [comment]
Without have 2k photo in my album I can't know what response it returns to fix and test it.

**Comment by kyelbek** [comment]
I've got this in debug log (I didn't check it before posting)

```
StackTrace:
   w System.Net.HttpWebRequest.GetResponse()
   w ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: s
   w System.IO.StringReader..ctor(String s)
   w System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   w ShareX.UploadersLib.ImageUploaders.Picasa.Upload(Stream stream, String fileName)
   w ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   w ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
Serwer zdalny zwrócił błąd: (403) Zabronione.

Response:
Photo limit reached.

```
There's clear info about it, but it should be shown in popup. You know what to do so this issue can be closed.
