### ISSUE TITLE
Removal of uploaded file

### ISSUE THREAD

**Issue by Spiderboi** [ShareX/ShareX#1984]
I, by accident uploaded a file which I want to delete from ShareX but I can't?

How can I remove a file uploaded?
It's a cpp file (c++) and when I right click Open -> Deletion URL is not available.

Thanks

**Comment by Spiderboi** [comment]
At puush.me I removed the file, but it's still accessible over the url..
Any idea how I can remove it?

**Comment by Jaex** [comment]
It could be removed from server but CloudFlare could be still showing it from cache.

**Comment by Spiderboi** [comment]
That solved it, thanks!

**Comment by bpage-gamedev** [comment]
How does one clear the CloudFlare cache..? What is the CloudFlare cache?

**Comment by MAGICCC** [comment]
And what is googling and what is resurecting old issues?
https://support.cloudflare.com/hc/en-us/articles/200168256-What-are-Cloudflare-s-caching-levels-
Only the website owner can clear the cache from his cloudflare 'protected' site

**Comment by stuntguy3000** [comment]
Yes
