### ISSUE TITLE
No automatic update?

### ISSUE THREAD

**Issue by n8r8r** [ShareX/ShareX#1986]
Every time I turn on my computer, sharex window pops up asking to update. I have to re-check the box to stop prompting for updates, and then click yes to update. What I want is an option in application settings to automatically update when I turn on my computer, and then not update again until the next time I turn on the computer. Because having to click the same buttons over and over is starting to feel very redundant.

**Comment by campbeb** [comment]
What version of ShareX do you have? If it is 11.1, then you might have the bug mentioned at #1796 

Otherwise, it sounds like you're asking for #1028
