### ISSUE TITLE
No toolbar in Edit Image application

### ISSUE THREAD

**Issue by tx-trainwreck** [ShareX/ShareX#1989]
Previously, when I edited an image, a separate window would appear with toolbars.  At some point, it has changed into a fullscreen mode and there are no toolbar buttons.  I've tried a variety of keys like ESC, F11... but none will get it to revert back to the window-ed version.  How can I do this?

**Comment by Jaex** [comment]
You must have enabled this setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/ShareX_RXgIgCTN5G.png)

**Comment by campbeb** [comment]
Under Task Settings / Advanced:
![sharex vshost_2016-10-11_18-41-19](https://cloud.githubusercontent.com/assets/1089399/19291301/6031c6e8-8fe2-11e6-97e2-476fe4ccbf4d.png)

Change the setting to False to use Greenshot image editor.
Note: In newest builds, the full screen image editor has gained a toolbar as well.

**Comment by tx-trainwreck** [comment]
Thanks.  Now I remember changing that.
