### ISSUE TITLE
Hotkey - Reset auto increment number

### ISSUE THREAD

**Issue by ArkIntersiec** [ShareX/ShareX#1992]
Is it possible to assingn "Reset auto increment number" to hotkey ?
I have to often reset auto incremenet number and I do not want every time go to settings.

Alternatively program could detect that in screenshots folder were removed screenshots and automatically reset auto increment number.

Do any of these functions is possible to introduce ?

**Comment by bruno812** [comment]
I have just started using sharex and found this problem and it's really annoying. Other things are just about time to get used to them, but I find this particular problem kinda serious..

**Comment by klueman** [comment]
Same as above, just found the app, and it's great, except for this one obnoxious oversight. There needs to be an option to reset the increment count back to 0 without having to open settings every time.

**Comment by b3hdad** [comment]
Same here. Just found this awesome app but I wish either we could assign a reset to the hotkeys, or, it would reset, when a new folder is created based on the date.

**Comment by RidwanRz** [comment]
Still no update regarding this?
