### ISSUE TITLE
Delayed/broken screenshots

### ISSUE THREAD

**Issue by pajwoj** [ShareX/ShareX#1995]
Every time i try to make a screenshot in a game called "osu!", the program screenshots things that happened a few seconds ago, or if it shows the image at the right time, it's like resized and doesn't show all details. 

At least one of the two issues happen every time i try to screenshot the game.
Here's a link to a broken screenshot: 

https://puu.sh/rILqj/4bd0b4bf28.jpg 

It should have my username, name of the song that's currently being placed, and a few other things. My cursor should be on the left side of the screen too, not on the bottom.

**Comment by Jaex** [comment]
Are you trying to capture directx fullscreen game?

**Comment by pajwoj** [comment]
Yes, it worked before and just broke recently.

**Comment by Jaex** [comment]
#848
