### ISSUE TITLE
Single-Key Hotkeys (i.e. PRT SCR Key) only work when certain Programs are in focus or when you click on the Desktop/Taskbar

### ISSUE THREAD

**Issue by bmferreira** [ShareX/ShareX#1996]
This seems to be specific to single-key hotkeys, if you set it as the regular CTRL+SHIFT+1 it triggers everywhere, doesn't matter what application you have in focus. If you select PRTSCR as your single hotkey it doesnt register when you have certain applications in focus. Only works everytime if you click the taskbar or your desktop.

[Sharex Focused Screenshot](http://i.imgur.com/qVzWww7.jpg) In this situation, I can trigger the hotkey if Sharex is in focus. If I switch to defraggler(per example) it stops registering the hotkey

[Hotkeys](http://i.imgur.com/tVSSXMt.jpg)

100% Reproducible, I can make a video of it if you're having trouble reproducing it.
This is on a fresh install of Windows 10 Pro. Sharex was installed through ninite.

**Comment by Jaex** [comment]
Must be this issue: #1915
