### ISSUE TITLE
Share operation on Windows 10

### ISSUE THREAD

**Issue by Eudaldca** [ShareX/ShareX#2001]
Windows 10, in the photos app, file explorer, etc. have buttons for sharing the file(s) with certain apps. It would be cool that sharex implemented this functionality, so I could view a photo in the photos app, click on share -> sharex and as my default upload it to Imgur, as an example.

**Comment by Jaex** [comment]
Few months ago I wanted to add it and couldn't find much info about how to implement it.

**Comment by Eudaldca** [comment]
I believe this has a bunch of info on the apis, bottom and/or right of the page https://msdn.microsoft.com/en-us/library/windows/apps/hh465251.aspx

**Comment by Jaex** [comment]
It talks about XAML which means probably require UWP app.

**Comment by campbeb** [comment]
Yes, this feature only works with UWP apps. 
https://msdn.microsoft.com/windows/uwp/app-to-app/receive-data
