### ISSUE TITLE
Allow more than 5 image editor instances to be open at a time

### ISSUE THREAD

**Issue by KamranMackey** [ShareX/ShareX#2003]
Sometimes I leave multiple image editor windows at a time (max limit to be specific) and when I take a new screenshot, I have to close one of those instances, which is kinda annoying. It would be nice if we could have more than 5 image editor instances to be open at a time.

**Comment by campbeb** [comment]
Change this value in Application Settings:
![devenv_2016-10-16_00-41-52](https://cloud.githubusercontent.com/assets/1089399/19415259/69dfae6c-9339-11e6-960e-fc6f0dbe8dff.png)

**Comment by eclutsk** [comment]
Glad to find this (very much appreciate that it was asked and answered), but the label needs to be updated.  I would never have guessed the setting affected the number of simultaneously open image editor windows too.  As a suggestion to devs, please add a note to "Upload" window describing this additional feature.

Thank you for all that you do!  Love this app!  Really helps with creating documentation and sharing information (picture is worth 1000+ words).

**Comment by teauxfu** [comment]
image link in previous comment is broken, reproducing here for the next person to land here from google 

![image](https://user-images.githubusercontent.com/1144380/234408901-844fab42-d37f-4980-ac51-0145e47ce191.png)
