### ISSUE TITLE
Can not capture taskbar

### ISSUE THREAD

**Issue by fumetsuu** [ShareX/ShareX#2008]
When I try to capture a screenshot using the region tool, I am unable to capture the taskbar and a bit above it. My screen's resolution is 1366x768. Instead of showing me the crosshairs, it shows me my normal cursor. It is as though that bit is unaffected by ShareX at all, but I am able to capture the taskbar if I start the crosshairs above it in an area that is affected.

If there is a solution so that I'll be able to capture the taskbar, please let me know. 

Thank you.

Windows 10
ShareX 11.3

**Comment by Jaex** [comment]
#1800
