### ISSUE TITLE
Pause in screen recording?

### ISSUE THREAD

**Issue by ifmihai** [ShareX/ShareX#2010]
I don't know about others
but putting screen recording on pause, would be very beneficial for me
(i'm not aware if this is possible or how to do it, in current version as of today)

What do you say?
Would this be a worthy enhancement?

**Comment by Jaex** [comment]
Are you seriously thinking am I didn't think about adding pause button. It is first thing will come to mind if you adding screen recording...

**Comment by Jaex** [comment]
#205

**Comment by ifmihai** [comment]
This didn't really cross my mind, because I really appreciate ShareX, and its developer(s)

But developers have personal preferences
and as a user, you really don't know if the developer thought about it, if he hates it, ignores it, likes it, doesn't have time for it, or if he delays it (because more important priorities), etc

Sorry if i sounded weird, english is not my first language
