### ISSUE TITLE
Problem and Question on Scaling an Image as Image Effect

### ISSUE THREAD

**Issue by tx-trainwreck** [ShareX/ShareX#2011]
I've tried adding an image effect to scale the image down because so many of my images appear too large when I paste them into an email.  I've used the Scale function and set it to WidthPercentage = 0, HeightPercentage = 80.

The process is working ok, but:
1. the images are much blurrier than an image of the same window captured without any scaling.
2. I currently have it set to save the file and copy it to the clipboard at the same time.  Is it possible to save the file without scaling but scale down the one in the clipboard?  i.e., I want to retain the original file but when I paste into an email, have it already re-sized down a bit.

Not sure if this affects it but I'm using a 4k monitor at 3440x1440 200 DPI.

**Comment by Jaex** [comment]
Why you don't show example image so I see how blurry it is.

**Comment by tx-trainwreck** [comment]
Here is the original screenshot:  http://i.imgur.com/WODz5lB.png
And here is one that uses an 80% scale down:  http://i.imgur.com/GYYLpRg.png

**Comment by Jaex** [comment]
Original one looks proper size why you scaling it 80% down?

**Comment by tx-trainwreck** [comment]
Because the images are too large when I paste them into an email or a Word document.  After pasting the image, I immediately have to resize them.  I was hoping to take the screenshot and have it resized down ~60% so that it's dimensions are smaller and more suitable for an email.

**Comment by Jaex** [comment]
That image looks same size as no dpi and 80% one looks smaller than how it is supposed to look.

**Comment by alecperkey** [comment]
@tx-trainwreck not sure about your resolution, but I am on UHD (3840px) so I downscale an even 50% to reach 1920px. Looks good at these settings
