### ISSUE TITLE
11.2.1: Failure of "Update is available" dialog to respond to keyboard

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#2013]
The "Update is available" dialog fails to respond to keyboard input http://i.imgur.com/rjRenAK.png , inc. TAB, ENTER, arrows, ESC. Hence it seems not possible to operate it except by mouse, touchscreen etc.

This on Win 7.

**Comment by Jaex** [comment]
I couldn't manage to make focus support in custom controls because it is more difficult than expected: http://stackoverflow.com/a/2362975/264877

**Comment by chrisjj** [comment]
You've lost me there. Keyboard operability is within the capability of hundreds Windows dialog boxes I have seen elsewhere, including in ShareX e..g http://i.imgur.com/x0kAR1T.png

**Comment by Jaex** [comment]
Those are not custom controls.

**Comment by chrisjj** [comment]
Evidently that was a good choice! :-)
