### ISSUE TITLE
Capture region after delay

### ISSUE THREAD

**Issue by CanadianJeff** [ShareX/ShareX#2014]
I have a delay of 5.0 seconds but when I choose to capture a region it ignores the delay setting and captures instantly this is a big issue when trying to capture a tooltip that hides itself

**Comment by Jaex** [comment]
Delay runs before open region capture because it applies to all screen capture stuffs. Problem is I can't make it work after select region because region capture freezes screen and crops image from it, so it wouldn't work later.

**Comment by CanadianJeff** [comment]
why was this closed as invalid the issue still exists thats stupid

**Comment by munrobasher** [comment]
I've got 12.3.1 and can't see this option?
