### ISSUE TITLE
Can't use any tool on other programs other then desktop

### ISSUE THREAD

**Issue by Mistaf** [ShareX/ShareX#2015]
Like the title says I can't use any tool of sharex on any program if I try to make for example a screenshot of my internet I use the hotkey ctrl + shift + 4 en normaly I just select what I want but starting today it randomly hides all open programs and just shows my desktop.. how to fix...

**Comment by Jaex** [comment]
ShareX won't hide all open programs.

**Comment by Mistaf** [comment]
it does now for me...

**Comment by Mistaf** [comment]
could it be because I got 4 screens connected to my pc?

**Comment by Jaex** [comment]
Did you tried changing hotkey? Maybe something in your pc intercepting that hotkey.

**Comment by Mistaf** [comment]
I did

**Comment by Mistaf** [comment]
I unplugged all my screens (except main screen) and still got that weird bug...

**Comment by Jaex** [comment]
Nobody reported such bug before. Not sure how it is possible.

**Comment by Mistaf** [comment]
do you have skype then I can show u and maby u get a better understanding of the bug

**Comment by Jaex** [comment]
I don't use skype.

**Comment by Mistaf** [comment]
any other screen share program?

**Comment by Mistaf** [comment]
because I cant really use sharex

**Comment by Jaex** [comment]
ShareX?

**Comment by Mistaf** [comment]
yh

**Comment by Mistaf** [comment]
can't use that

**Comment by Mistaf** [comment]
:l

**Comment by Mistaf** [comment]
fixed it somehow
