### ISSUE TITLE
Ping timeout after screenshot

### ISSUE THREAD

**Issue by qwitriy** [ShareX/ShareX#2018]
In most cases after uploading screenshot or video using ShareX (no matter to Dropbox or puu.sh) I get ping timeout. It's even disconnect any network activity.
I'm not sure if I can post here link to recorded video, but here is cmd screenshot.

WiFi connection.
ShareX 11.3 on Windows 10 x64.
![cmd_2016-10-20_21-47-18](https://cloud.githubusercontent.com/assets/6897424/19564786/e209b742-970e-11e6-910e-8cc0232b69dd.png)

**Comment by Jaex** [comment]
I took 10 active window screenshots while pinging:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/cmd_iUXl5CGo0n.png)

And nobody reported ShareX disconnects any network activity before. Not sure how it can with simple web request using .NET Framework functions.

**Comment by Jaex** [comment]
So I suspect something wrong in your end.

**Comment by qwitriy** [comment]
Okay. Thx for response.
