### ISSUE TITLE
Rectangle capture: use arrow keys for fine positioning

### ISSUE THREAD

**Issue by AGSPhoenix** [ShareX/ShareX#202]
Rectangle capture is pretty nice, but trying to select an exact region can be quite difficult, depending on mouse sensitivity settings. Would it be possible to allow the current positioning to be adjusted 1px by pressing the arrow keys?

Not sure how the mouse should be handled in this case, since it might be a bit awkward to keep holding the mouse button while adjusting with the arrow keys.

I think this would be best implemented by having the arrow keys actually move the mouse cursor instead of just adjusting the selected region, so that large adjustments aren't reset by small mouse movements.

**Comment by leumasme** [comment]
Wiki got removed and i cant seem to find it in the new Docs, send help if you are still alive.

**Comment by Jaex** [comment]
https://getsharex.com/docs/region-capture
