### ISSUE TITLE
Can't capture over Windows 10 stuff

### ISSUE THREAD

**Issue by fumetsuu** [ShareX/ShareX#2020]
When I try to take a region capture of the start menu or taskbar for example, instead of capturing, the actual thing is clicked and the crosshairs disappear and turn into the normal cursor (almost as though ShareX disappears over that area). Is there a way to fix this? I can give as much information as needed so please ask if something is unclear! 

Thank you.

**Comment by campbeb** [comment]
Are you going to ShareX menu, selecting Capture / Region, then opening the Start menu?
I can take a picture of Start menu by opening it and then using my hotkey for Capture Region (It doesn't automatically detect the Start menu as a window, but I can draw the region around it)

**Comment by Jaex** [comment]
#1338 this issue I think.

**Comment by fumetsuu** [comment]
Yes that's exactly it Jaex, is it unfixable then?

**Comment by Jaex** [comment]
I don't know what is problem.

**Comment by piyo-gh** [comment]
#1800 is also the same issue.

I think most of the people which reported this issue are using Chinese or Japanese version of Windows, aren't they ?
In these locale, system default font is different from English version and default full-width characters are square.
Maybe SizeF(6F, 12F) is the default, isn't it ?

But as I said I am not a programmer, I don't know how to solve this issue.

**Comment by fumetsuu** [comment]
Yes I am using a Japanese version of Windows, so that must be the problem it seems.

**Comment by Jaex** [comment]
Yes same issue with #1800
