### ISSUE TITLE
Please support Anhso.info

### ISSUE THREAD

**Issue by vncadp** [ShareX/ShareX#2026]
I'm not the owner of this site but I think _Anhso.info_ was built by Chevereto. And I want create JSON for _Anhso.info_ manually but I've forgotten how to make :(. Sorry if it makes you confused..

**Comment by Jaex** [comment]
ShareX already supports Chevereto why would you make JSON for it.

**Comment by vncadp** [comment]
I don't have API :(

**Comment by Jaex** [comment]
Can't add without API key.

**Comment by vncadp** [comment]
Contacting...
