### ISSUE TITLE
Custom Uploader Not Working (hizliresim.com)

### ISSUE THREAD

**Issue by bkrcrc** [ShareX/ShareX#2028]
Please try to update this uploader for images, I am using it.
https://github.com/ShareX/CustomUploaders/blob/master/hizliresim.com.json
They also uses SSL security for the direct image URLs..please consider this too.

Thanks

**Comment by Jaex** [comment]
I think it requires token from home page otherwise request fails. So custom uploader can't be used.

**Comment by bkrcrc** [comment]
@Jaex Teşekkürler Jaex, buralarda Türk olduğunu bilmiyordum.
Türk upload sitelerini ekleme şansımız var mı kütüphaneye?
Thanks anyway.

**Comment by Jaex** [comment]
Hayır.

**Comment by bkrcrc** [comment]
Sağol
