### ISSUE TITLE
Sharex update is horrible

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#2029]
It kept pestering on every startup. When I finally clicked to update it:
- Installed a normal version in parallel instead of updating the portable version
- didn't ask or tell where it installs. Or show any options.
- set itself to start automatically with windows
- started with default settings.
- spoofed me to believe that it updated my portable installation and erased all settings

**Comment by Jaex** [comment]
Portable auto updater not updates ShareX it just opens link to zip download file.

**Comment by mzso** [comment]
Well, I guess it was a bug in the old version. Or not a portable installation after all.

**Comment by Jaex** [comment]
I downloaded previous version portable, it asked for update, press yes, it opened:
`https://github.com/ShareX/ShareX/releases/download/v11.3.0/ShareX-portable.zip`
in browser.

So it works as intended.

**Comment by mzso** [comment]
It was 11.0.1. But I guess I mistook the it for an old portable version.
