### ISSUE TITLE
Can't prevent sharex from adding an unsupported extension when using custom command

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#2031]
Hi!

When I use a custom command I have "$output$". Which adds an extension automatically. I'm guessing based on the "video codec" setting above which isn't even used. So when I have a format that's incompatible with the container the encoding fails. Alternatively I can add an extension after it, but then I'll have something like filename.mp4.avi.

**Comment by Jaex** [comment]
I must add something like $filepath$ I guess.

**Comment by mzso** [comment]
That'd be nice. I don't see sharex automatically determining a valid container

**Comment by Jaex** [comment]
Before I was letting user select container (it was already automatically filling proper container) but then people was keep selecting invalid containers and keep reporting it not works so I was fully automated it.
