### ISSUE TITLE
ShareX + Overwatch creates a memory leak

### ISSUE THREAD

**Issue by Phibonacci** [ShareX/ShareX#2033]
When taking a screenshot with ShareX while playing Overwatch, the memory consumed by Overwatch *may* increase considerably, it can go from 700MB to 3000MB, causing the game to swap.  
The memory then goes back to normal in the seconds that follow (or minutes in case of swap).  

This does not always happen. However, once it happened once, the next screenshots are all going to create the same issue. It happened multiple times already, I will investigate further and report any new clue on the topic.

**Comment by Jaex** [comment]
How Overwatch memory increase to do with ShareX?

**Comment by Phibonacci** [comment]
I was hopping you could tell me. It makes absolutely not doubt that the huge increase in memory is a direct consequence to a screenshot take with ShareX.

**Comment by Jaex** [comment]
ShareX can't increase memory of another process. Because ShareX have nothing to do with another process. Because there is no game capture support.

**Comment by Scrxtchy** [comment]
Overwatch has it's own printscreen function
You can set this to render like 7x your resolution, with images at like 300mb or higher

please check your settings and see if this is enabled

**Comment by Phibonacci** [comment]
@Scrxtchy I changed the shortcut already. Only ShareX is taking a screenshot when I press the key.
