### ISSUE TITLE
In "Region Capture" mode, pressing another ShareX keyboard shortcut could not make capture of the capture but change output parameters

### ISSUE THREAD

**Issue by klint** [ShareX/ShareX#2048]
Hello there.
Assume you have 2 shortcuts S1 and S2.
S1 is region capture, then copy to clipboard
S2 is region capture, then upload to web and copy URL in clipboard.

I press key S1. 
The screen enters in Region Capture mode, and I can draw on the frozen screen.
Yet, instead of copying the output to the clipboard, I now would prefer upload and get URL in clipboard.
So I naturally press key... S2.
But then S2 enters in Region Capture mode of the current screen which is... in S1 Region Capture mode actually.

Instead of having that behavior for "nested shortcut usages", it would be helpful that, if I pressed S2 during Region Capture mode, nothing changed except that when doing the capture itself, the output action became the one associated to S2 and not the one associated to S1.

Therefore, I still can change my mind about the post-capture action even while I'm in Region Capture mode.

Hope I explained clearly enough :)
Thanks.

**Comment by Jaex** [comment]
Region capture in ShareX is not singleton. Because that way I can take region capture of region capture. What you want require region capture to be singleton that way second press can transfer functionality to already open one which I can't do because it must not be singleton form.
