### ISSUE TITLE
ffmpeg download on Windows x64 fails (403 error)

### ISSUE THREAD

**Issue by dave0j** [ShareX/ShareX#2049]
Attempting to download FFmpeg on a Windows 10 x64 system fails with a 403 (Forbidden) error. The request being made by ShareX is:

GET http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z HTTP/1.1
User-Agent: ShareX
Proxy-Connection: Keep-Alive
Host: ffmpeg.zeranoe.com

Response is:
HTTP/1.1 403 Forbidden
Server: nginx/1.10.2
Date: Mon, 07 Nov 2016 23:57:06 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 370
Connection: keep-alive

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /builds/win64/static/ffmpeg-latest-win64-static.7z
on this server.</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

**Comment by Jaex** [comment]
https://ffmpeg.zeranoe.com/ is down.

**Comment by Jaex** [comment]
Web site back now.

**Comment by ferrouswheel** [comment]
It's down again.

**Comment by dave0j** [comment]
Is it worth mirroring this to avoid the dependency? Or maybe a redirector capable of detecting if the primary source is down?

**Comment by Jaex** [comment]
I don't know should I email and report owner of web site because probably he will be doing something which caused it to be down, so he must be aware of it.

**Comment by ferrouswheel** [comment]
@Jaex Since this has happened before, and it's a 403, I'm guessing it might be that they have exceeded their allowed bandwidth at the hosting provider.

**Comment by Jaex** [comment]
https://twitter.com/Zeranoe/status/806642847394988032

**Comment by Jaex** [comment]
If anyone need to download latest stable 64 bit FFmpeg build then I uploaded it here: http://ge.tt/9eTltlh2

**Comment by FichteFoll** [comment]
Can always just download it from here? http://ffmpeg.zeranoe.com/builds/

**Comment by ooker777** [comment]
(Update Aug 2018) https://ffmpeg.zeranoe.com/ works now, but ShareX still can't download it (404 error). I've download the build, but don't know how to run it. There is no exe file in there.
