### ISSUE TITLE
Feature Request: Rotate between FTP destinations

### ISSUE THREAD

**Issue by jimmydorry** [ShareX/ShareX#2050]
Rotate between FTP destinations. I have a few vanity domains that I would like to upload to in random order (preferably), or even in round-robin.

This is probably a niche use-case, so I understand this being closed.

**Example workflow:**

* Upload `image1` via FTP to `FTP_destination_1`
* Upload `image2` via FTP to `FTP_destination_2`
* Upload `image3` via FTP to `FTP_destination_1`
* Upload `image4` via FTP to `FTP_destination_2`
* etc.

**Comment by Jaex** [comment]
Sorry but this is very personal case feature request that other than you nobody gonna need and have no actual use, therefore I'm not planning to add it.

**Comment by Jaex** [comment]
Custom uploader had `$random:domain1.com|domain2.com|domain3.com$` syntax support, so now I added that syntax support to FTP "URL path" field.

Like this:
![](https://jaex.getsharex.com/2019/03/ShareX_ejckfIKScB.png)

**Comment by jimmydorry** [comment]
Pog! Thanks
