### ISSUE TITLE
new region capture toolbar too small in 4K resolution

### ISSUE THREAD

**Issue by Zivelz** [ShareX/ShareX#2053]
I love this new feature, like right click cancel,

 but toolbar not work with win10 DPI scaling,(i used 200% DPI scailing)

http://i.imgur.com/DQCy1WN.jpg

**Comment by Jaex** [comment]
I was made sure that toolbar icons resizes with different DPI scaling. Not sure why it not works for you.

**Comment by tomlaf** [comment]
I have the same issue on Win 10 Build 14971.
My scalling is at 125 % but the icon size are minimal.
In the option the menu are scale correctly but the detail are not...
![image](https://cloud.githubusercontent.com/assets/8548490/20550472/f765a97a-b103-11e6-8470-51ca1975c419.png)
![image](https://cloud.githubusercontent.com/assets/8548490/20550476/ff17344a-b103-11e6-92ae-b3d9e35d8066.png)

**Comment by melior88** [comment]
Having the same issue here:
![Desktop](http://i.imgur.com/AWATmPf.png)
