### ISSUE TITLE
Bad sound through mobile mic

### ISSUE THREAD

**Issue by areebbeigh** [ShareX/ShareX#2054]
I use my Android phone as a mic for the PC and it works good while recording or streaming the sound from the mic on the PC but when I try recording with ShareX I get this weird disturbed noise as if a terminator is speaking (which is cool but it still is an issue). I tried settings the sound quality to max but it doesn't make much difference. 

The app I use - WO Mic.

**Comment by vatterspun** [comment]
This might be a sound option selection issue.  Can you post a screencap of what you have the FFMPEG page set to?  

![test](https://cloud.githubusercontent.com/assets/1289134/20329245/b56366ae-ab5c-11e6-9eb3-a2fd2ba87ce5.png)

This is under **Task Settings - Screen Recorder - Screen recording options**

**Comment by areebbeigh** [comment]
I've selected the correct Audio Source. I used TinyTake by MangoApps for screen recording before.

![capture](https://cloud.githubusercontent.com/assets/15276828/20456879/7247c008-aea5-11e6-8365-01d153db0a91.PNG)

**Comment by vatterspun** [comment]
What programs are running successfully with Mic recordings?  Have you used Window's own recorder or Audacity?

As a (not very good) workaround, you might record the audio and video with separate tools and then reassemble them later with a video editor.

**Comment by Jaex** [comment]
All recording happens inside FFmpeg.exe so it is not to do with us.
