### ISSUE TITLE
Request: Year/Month/Date variable support in CapturePath advanced setting

### ISSUE THREAD

**Issue by RadGH** [ShareX/ShareX#2058]
There is a "CapturePath" option in the advanced settings, where files get saved to: https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-868470985522/ShareX/2016/11/ShareX_2016-11-09_11-09-33.jpg

I would like the ability to create a folder for the day/month/year. I've tried using the same format that is used for the fields such as OpenURLFormat which support %y %mo and %d. But it just makes a folder with those wildcards in the name, instead of resolving them to Y/M/D.

There are many other tags that can be seen when editing Upload > File Naming > Name pattern: https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-868470985522/ShareX/2016/11/KSP_x64_2016-11-09_11-05-55.jpg

I think most of these variables could work in the CapturePath field. Also note, I tried setting this up in the file naming pattern mentioned in the previous paragraph. But this does not create folders, it simply removes the slashes.

**EXAMPLE**

CapturePath: G:\ShareX\\%y\\%mo\\%d
Result: G:\ShareX\2016\11\09\screenshot.jpg

Thanks!!

**Comment by Jaex** [comment]
Is there any reason you don't use this?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/ShareX_qhb0Ue5ELM.png)

**Comment by RadGH** [comment]
Oooh. I must have missed that option. That is exactly what I needed. Thanks for pointing that out :)

**Comment by ErnestUTN** [comment]
> Is there any reason you don't use this?

I'm Sorry, but I can't view what you are refering to "this". I'm having the same issue.
