### ISSUE TITLE
Streamable parameters such as HD, Autoplay, etc.

### ISSUE THREAD

**Issue by Psyda** [ShareX/ShareX#2061]
As of right now you get the Streamable link copied to your clipboard, but it only plays the video in a very low quality.
Users watching the video can make it playback in HD by hitting the HD button, but it can very hard to see in some cases and most of the time goes unnoticed..

You can have these possible parameters added to the url.
muted=1 autoplay=1 logo=0 hd=1
~Since ShareX doesn't record audio Muted won't be a needed option.~

For reference here is a Streamable video with all parameters enabled.
https://streamable.com/z0uw?muted=1&amp;autoplay=1&amp;logo=0&amp;hd=1

If anything HD should have an option or be enabled by default while autoplay is just kinda handy.

**Comment by Jaex** [comment]
ShareX can record audio.

**Comment by Psyda** [comment]
I wasn't aware, ignore that part then.

**Comment by lawlmart** [comment]
The query string params are deprecated and will be removed soon. I wouldn't suggest adding them to ShareX until we hammer out a better solution on our end.
