### ISSUE TITLE
Add a "post-capture action" option in "Region Capture" mode

### ISSUE THREAD

**Issue by klint** [ShareX/ShareX#2063]
Context:
Obvious things first: when I do a capture, it can be for various purposes, with different post-capture actions: upload if I want to share, copy to file, copy filename or image to clipboard, or the editor itself. I have a specific keyboard shortcut for each and every usage of screen shot. Thanks to ShareX.
Trouble is, I have to select and remember the right shortcut before using it. And I often press the wrong one by accident, because habits are strong and I almost always start by pressing the most used shortcut (a 3-keys on the left of the keyboard, easily reachable without moving the left hand and allowing selection to be done with the right hand on the mouse... I'm lazy ;) ).

Request:
With the Region Capture feature being more powerful and more handy then ever, replacing the need for the editor itself for instance, it would be very helpful to have a new selector for the action to be done after capture, in the Region Capture toolbar
By default it would be the one associated to the shortcut used to enter in Region Capture mode.
And instead of having all options available for post-capture, maybe it could be reduced to the various post-capture options defined in my shortcuts.
This way, by using a single shortcut (and defining more but without having to use them necessarily), I could easily perform all my usual and various type of captures. And if I really to do it quicker, I still can use the right shortcut.
Thanks

**Comment by Jaex** [comment]
Region capture have editor mode which have similar buttons to what you want:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/ShareX_4MxhRW4voT.png)

But that buttons can't work as expected because you can't just for example copy image to clipboard because region selection must be made and confirmed to be able to have image.

**Comment by klint** [comment]
Thanks for your answer.
But how can I see these buttons? My toolbar looks like this:
![image](https://cloud.githubusercontent.com/assets/218971/20172537/c9f7885a-a735-11e6-89f4-ed386e9ed0f6.png)

**Comment by Jaex** [comment]
Editor mode used for editing when you right click task or opening it from tools menu.

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/ShareX_cS4FpdMZuU.png)

**Comment by klint** [comment]
Thanks. Now I have toggled this setting, but I'm sorry, I still can't get your version of the toolbar.

**Comment by Jaex** [comment]
That setting is not for region capture but for:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/ShareX_hvv0KFeWdq.png)

I was just gave it as example but it is not to do with region capture.

**Comment by klint** [comment]
Ok, I get it now. But, yes, this won't help me as it is different from region capture. Thanks anyway.

**Comment by Jaex** [comment]
By the way why you took photo of your monitor?!

**Comment by klint** [comment]
Because I could not capture the toolbar. It was capturing the image behing... I have not discovered all subtleties of XShare, so powerful ;) 
For instance, I just have resolved all my problems by using the "Quick menu" as the post-capture actions. Wasn't ever aware of its existence before a few minutes ago!
