### ISSUE TITLE
Broken GIF custom region recording

### ISSUE THREAD

**Issue by newton378** [ShareX/ShareX#2066]
trying to hotkey for a custom region GIF screen recording, not working

**Comment by vatterspun** [comment]
Confirmed on Win7x86

**Steps**:

1. Click **Hotkey settings**
2. Click **Add**
3. Select **Screen record - Start screen recording (GIF) using custom region** from the "Task" dropdown list

![2016-11-15 17_59_52-greenshot](https://cloud.githubusercontent.com/assets/1289134/20329437/ce418812-ab5d-11e6-9a1c-8bdb56170bd9.png)

4. Set description to "test"
5. Uncheck all default actions
6. Set After Capture to **Save image to file**
7. Press **X** to return to the hotkey screen and set a hotkey (I tried a few different combos to make sure it wasn't a conflict)
8. Press **X** to return to main screen
9. Execute hotkey

**Defect**: GIF recording cursor 
**Expected result**: GIF recording cursor should appear as when you choose the option from the **Capture** menu

**Comment by newton378** [comment]
I'm on win8.1 x64, I believe, it doesn't work

**Comment by newton378** [comment]
https://puu.sh/sjBmU/7fc634d6dd.png

**Comment by vatterspun** [comment]
@newton378 
Forgot to add the Debug view, thanks.

**Comment by vatterspun** [comment]
@newton378 
Forgot to add the Debug view, thanks.

**Comment by Jaex** [comment]
I tried now it works. You probably didn't configure custom region:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/ShareX.vshost_GhMyuXJ2Iv.png)

**Comment by vatterspun** [comment]
> probably didn't configure custom region

Confirmed.  Works fine now.

Maybe this could be a feature request to add a note around that function needing additional configuration in the Task Settings menu.  Otherwise I guess close the issue.

**Comment by newton378** [comment]
my idea is to suggest adding a "light" region capture feature for screen recordings, specifically gif recording, so that one doesn't need to set the "custom region" manually but rather select the region upon hotkey trigger

**Comment by vatterspun** [comment]
@newton378 
> so that one doesn't need to set the "custom region" manually but rather select the region

I'm not sure that's radically different in terms of functionality versus the current capability to "Start/Stop screen recording (GIF)".  If you were looking for something reproducible (i.e. you keep recording the same area) just use "Start/Stop screen recording (GIF) using last region" for successive captures.

**Comment by savovs** [comment]
How do you set the custom region? I'm trying to record a video but nothing happens when I press the hotkey?

**Comment by Jaex** [comment]
Custom region means previously configured region. You actually want normal screen recording and by default there is already hotkey for it.
