### ISSUE TITLE
Support for droplr

### ISSUE THREAD

**Issue by twiddern** [ShareX/ShareX#2068]
Hi

I'm not sure about this because it's like a competitor and I didn't found any mention about this here. It would be nice to see support for the droplr api. 

Docs: http://droplr.github.io/docs/

**Comment by Jaex** [comment]
You can use http://droplr.com/ app to upload to droplr.

**Comment by TheZoker** [comment]
Since you integrate other image hoster (like Imgur) it would be nice to have a default support within your app for droplr

**Comment by Noshtzy** [comment]
Would be nice. https://github.com/ShareX/ShareX/issues/4620
