### ISSUE TITLE
puush was simple useful and fast. puush is now "pain and agony" (for 90% of puush-ers)

### ISSUE THREAD

**Issue by DBJDBJ** [ShareX/ShareX#2072]
### If you can do something, it does not mean you have to show it in users face.
UX? Have only one simple short context menu. Move **everything** else to the "Settings..." window. 
Do not overload "screen capture experience" with "oh yes we can do this too" features ... 
When capture is done and uploaded, do nothing: just a ping sound is enough ( icon can show some animation but only when ticked in setup)

UX is the problem. The engine is fine of course.

**Comment by Jaex** [comment]
As soon as I make that context menu shorter, there will be issue spams in GitHub asking me to add those stuffs back (I know that because everytime I try to remove something to simplify UI people keep becoming unhappy about it). Not everyone have same opinions as you. Just because you prefer simple context menu does not means everyone would prefer it too. Actually people keep asking me to add more stuffs to that context menu and I keep declining their requests and then users becoming angry to me just because I didn't add what they requested.

If you mean by "do nothing" is not showing preview in right bottom corner then you can hide it or even change how it gonna show up like balloon tip or customizing how preview gonna show etc. By default users prefer to see preview.

So point is impossible to make everyone happy because everyone have different tastes about what is good UX.

**Comment by peppy** [comment]
i completely agree, but once you have things setup there should be no reason to deal with the bad UX. take a few minutes to learn things and set them up and go on with your business.

or find another products which offers the simplicity you're after.

**Comment by DBJDBJ** [comment]
@peppy @Jaex we are in agreement, and I think you can sense we might be in the same "business" too .
and yes we are now hitting the big issue of open source projects: funding.

We all know this is solved with staged delivery , properly staffed UAT team, an little army of UX testers and a such.

But. One can always see what is available. A good example that will help here to clarify what it excellent UX comes from a well funded team behind  Avast. I think this is what I am talking about.

**Comment by peppy** [comment]
i wouldn't have switched to providing sharex as the official puush client if you had to deal with configuration on a daily basis.

it's setup-and-forget. just spend half an hour getting things how you want it then forget. the UX is definitely improving as time goes on, so there's that.

**Comment by oxysoft** [comment]
ShareX is 5000% times more powerful than the Puush client ever was, (or any screen capture software on the market for that matter) so don't complain because you can't make sense of it. It is a screen capture software on steroids but I agree that some things could be better organized or named.

**Comment by Aaeon** [comment]
Instead of trying to defend ShareX why not think of a way to make everyone happy.

Tools > Preferences > Functions > ... 
Function A  Enable █ Disable █
"                                                "
and so on... 

Why people in general can't realize a better way is beyond me.

**Comment by peppy** [comment]
what are you trying to do? if you have more information we may be able to help.

**Comment by Aaeon** [comment]
I'm a puush user and I simply don't like the bloated menus of ShareX like most puush'ers.

There is a way to make everyone happy without altering ShareX's core functionality.

**Comment by peppy** [comment]
I mean the UX isn't perfect, but once you set it up you don't need to use the menus again.

**Comment by Aaeon** [comment]
That's the problem, you don't need to setup Puush.  So where's a setup guide?

**Comment by xSamagon** [comment]
@Aaeon Where's your problem? if you dont like sharex, just dont use it?
Use the "old" puush uploader and have ur' old puush. If you dont need any "extra" function of sharex (like gifs), you wont miss anything..
http://puush.me/dl/puush.exe

@All Why aren't you just happy with what you get, using puush? Ok - With the downloadlink from the homepage you get sharex, but you get unlimited space for your images, not an single ad, you can even manage and delete your stuff like you want and you get these thing all for FREE. - Just be happy with that and invest that f*ckn' 5 minutes in setting up ShareX, like you want it, or search and install the old puush uploader...
btw: Not even one of the ShareX contributors is the "evil guy" which made puush using sharex. It was puush's decision not their.

**Comment by DBJDBJ** [comment]
@Aaeon  + 9 others (20NOV16) are the sign of discontent.  I repeat: ShareX is fine. UX is the problem.

**Comment by Gatreh** [comment]
I just want to point out that the solution is that the user gets to decide what is and isn't in the context menu, and preferably you'd get something like a guided tour on first setup.

**Comment by Aaeon** [comment]
> Instead of trying to defend ShareX why not think of a way to make everyone happy.
> 
> Tools > Preferences > Functions > ...
> Function A Enable █ Disable █
> " "
> and so on...
> 
> Why people in general can't realize a better way is beyond me.

I have re-installed ShareX to give it another go but, you shared the puush installer above and it will only work if you already have an account created. You also cannot export anything ever again. So you must have an account already. 

What I was trying to point out here is, YES there is a way to make everyone happy. You as the developer has to make that decision, if you decide the user interface is better when you move something then do it. Options that are moved to make the user interface more organized is a good move. Better than having features removed entirely.

To make Puush users happy you could create a menu in preferences called functions with an enable or disable function. I have already setup the hotkeys to work like Puush but there is a major issue here. Everytime I goto grab a region this huge crosshair graphic appears that is simply a graphic and doesn't have any useful information except for the coordinate read out above the selected region, upon committing to the desired region there is this loud sword clang followed by a loud keyboard note with a preview of the selected region.

What the hell is this lol, I mean c'mon seriously?!

I would really love to disable that huge floating graphic next to the cursor while selecting a region.
I would really love to be able to change the sounds or disable them entirely.

**Comment by peppy** [comment]
All of the things you mention are settings you can already adjust.

**Comment by Aaeon** [comment]
Can you please share how! thanks

**Comment by DBJDBJ** [comment]
Sorry, @Aaeon, I am leaving .... this is a waste of time ...

**Comment by peppy** [comment]
turn off sound (two options):

![image](https://user-images.githubusercontent.com/191335/78516094-554ba300-77f3-11ea-9fed-4e7a24b414f8.png)

turn off crosshair (and "huge floating graphic"):

![image](https://user-images.githubusercontent.com/191335/78516157-8deb7c80-77f3-11ea-9607-f8b1ac6465dd.png)

**Comment by Aaeon** [comment]
Thanks Peppy those settings are quite buried and hard to find.

Is there anyway to replace the sound when capture is finished uploading/copied to clipboard with the sound from Puush? I personally find that sound way more unobtrusive.

**Comment by peppy** [comment]
I'm sure you could replace the file, or open a separate issue asking for customisation over that.

**Comment by Aaeon** [comment]
https://i.imgur.com/Ueov5cD.png

It's already been requested and removed it seems.

**Comment by peppy** [comment]
Oh, it's already a thing. Doesn't look removed? Is it not working for you?

**Comment by Aaeon** [comment]
https://puu.sh/FtPHk/0faba953e9.png

**Comment by Aaeon** [comment]
Peppy that screenshot is of the same area on my screen and the option is not there.

**Comment by peppy** [comment]
Because you turned off the sounds?
