### ISSUE TITLE
Text encoding issue when uploading to pasteBin

### ISSUE THREAD

**Issue by dev101** [ShareX/ShareX#2073]
Text with non-ascii characters is uploaded like this: http://pastebin.com/GpXcQCnT

**Comment by Jaex** [comment]
I uploaded these characters using Chrome extension without problem: https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/tmp5BE3.txt

Which characters you can't upload?

**Comment by dev101** [comment]
I tried selected text from this page: https://www.reformagkh.ru/api

https://www.dropbox.com/s/ef3iey6lq2c9y4x/chrome_2016-11-11_14-58-39.png?dl=0

**Comment by Jaex** [comment]
Still worked: https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/tmpDAEC.txt

**Comment by dev101** [comment]
So what could it be? latest chrome, latest ShareX, US/English locale in windows... What else can I check?
https://www.dropbox.com/s/2jkm1b2961xy2oo/ShareX_2016-11-11_17-03-00.png?dl=0

**Comment by dev101** [comment]
I got it: try to upload to pasteBin instead of dropbox.

**Comment by Jaex** [comment]
http://pastebin.com/uNQA5nEg this means it was not to do with extension but also happens when doing clipboard upload.

**Comment by dev101** [comment]
You mean pastebin doesn't support UTF-8?

**Comment by Jaex** [comment]
I checked other text uploaders and all shows utf-8 texts properly but not Pastebin and all text uploaders using same request method so I'm not sure what is wrong currently.

**Comment by Jaex** [comment]
See only Pastebin fails:

http://pastebin.com/FynJ8MS4
http://paste2.org/ZXGG4k0G
http://slexy.org/view/s20P4nXJNY
http://paste.ee/p/OjKvB
https://gist.github.com/c0178e00587e70a699f9127a9a9bc27c
http://upaste.me/892235608e4eaca5d
http://hastebin.com/utefovapay.hs

**Comment by Jaex** [comment]
I sent email to Pastebin to report this issue now.

**Comment by Jaex** [comment]
They fixed issue now: https://pastebin.com/suSqfApN
