### ISSUE TITLE
Send by email to Greenshot image editor

### ISSUE THREAD

**Issue by Dreadaxe** [ShareX/ShareX#2075]
Where can I find this function to Greenshot image editor?

**Comment by vatterspun** [comment]
Possible workaround: 

1. Download and install Greenshot separate from ShareX (www.getgreenshot.org)
2. Right-click the _Greenshot.exe_ file and choose "create shortcut"
3. In Explorer, type "shell:sendto" (without the quotes)
4. Paste the shortcut into this folder

Result:
![2016-11-15 18_17_08-](https://cloud.githubusercontent.com/assets/1289134/20329744/c320847c-ab5f-11e6-9a96-5c789d5ff07d.png)

**Comment by Dreadaxe** [comment]
Thanks. But I want to have a option to Greenshot to send the image by
email.

**Comment by vatterspun** [comment]
Oh I think I understand.  ShareX draws from a separate project for it's image editor (one of the great things about open licenses).  You might want to make that request here: https://greenshot.atlassian.net/projects/FEATURE/issues

**Comment by Jaex** [comment]
They have that feature.

**Comment by vatterspun** [comment]
> I want to have a option to Greenshot to send the image by email

I figured it out: you can configure Greenshot to send email by doing the following:

1. Open **Destinations** - **Destination Settings** 
2. Scroll down to **Email** and configure

![2016-11-17 16_53_35-sharex - destination settings - j__portableapps_sharex-portable_sharex_uploaders](https://cloud.githubusercontent.com/assets/1289134/20411290/7bbb8090-ace6-11e6-9a32-51e1a0675dd2.png)

3. Click the upload button from the Greenshot image editor.

![2016-11-17 16_55_56-clipboard](https://cloud.githubusercontent.com/assets/1289134/20411415/fc29482a-ace6-11e6-8ae6-a1a9041f087b.png)

**Comment by Dreadaxe** [comment]
Ok thanks.

* Pity to don't have more than one Destinations option for send when you put the "upload" button
* Pity that Email destionation don't have access to my contact or simply open my email client program.

**Comment by vatterspun** [comment]
> more than one Destination option; simply open my email client program

I recommend writing those up as separate feature requests with clear specifics on what kind of functionality you need and why.

**Comment by Dreadaxe** [comment]
Ok. I'm a french user, It's not easy for me to write to english ;)

**Comment by vatterspun** [comment]
> Ok. I'm a french user, It's not easy for me to write to english ;)

Understandable.  I work with many developers who don't speak great English.  I try to breaking up requests into simple steps with lots of pictures really helps.

**Comment by Dreadaxe** [comment]
http://i.imgur.com/XfvN3M1.png

**Comment by AnacondaPython** [comment]
I wanted to look into this as well, does this mean you can't have both an image URL uploader and a email uploader at the same time? Something like this would be nice to have setup: http://i.imgur.com/3vWeQZQ.png . Like I want to default everything to imgur links, but may or may not use email attachments as well. Maybe greenshot print settings? Print2email? http://www.blackice.com/Print2Email.htm
