### ISSUE TITLE
Files Upload with no extentions

### ISSUE THREAD

**Issue by Sparqey** [ShareX/ShareX#2076]
i use a custom ftp to upload screenshots and other files
but when using the chrome extention it always uploads with no file extentions making it unable to open?

i have checked thru settings and in my eyes it is a bug?

**Comment by Jaex** [comment]
Which image you tried to upload with chrome extension?

**Comment by Sparqey** [comment]
I figured out the issue i think, if the site shows the image without the extention it will also upload without the extention

here is a example
http://putin.host/11/122S3d

**Comment by Jaex** [comment]
Yes ShareX gets file extension from url. If there is no extension in url then ShareX can't know what extension to use.

**Comment by Sparqey** [comment]
Is there maybe like a fix to it?
Maybe like a option, if no extention then use png?

**Comment by Jaex** [comment]
How can I randomly enforce png.

**Comment by Sparqey** [comment]
idk?
or what could be a little fix is that we can like chose what a different uploading method etc for chrome extention, so we can change that in the settings
