### ISSUE TITLE
FFMPEG error when recording GIF

### ISSUE THREAD

**Issue by MarcusTarkus** [ShareX/ShareX#2081]
I always get an error message when I finish my screen recording. It does not occur when running ShareX with administrator privileges(Win 7) or I just do a video recording as mp4. 
It's the latest ffmpeg.exe that I downloaded through the ShareX options, but updating didn't change anything in that matter.

> ffmpeg version N-82324-g872b358 Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 5.4.0 (GCC)
>   configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
>   libavutil      55. 36.100 / 55. 36.100
>   libavcodec     57. 66.101 / 57. 66.101
>   libavformat    57. 57.100 / 57. 57.100
>   libavdevice    57.  2.100 / 57.  2.100
>   libavfilter     6. 66.100 /  6. 66.100
>   libswscale      4.  3.100 /  4.  3.100
>   libswresample   2.  4.100 /  2.  4.100
>   libpostproc    54.  2.100 / 54.  2.100
> [gdigrab @ 000000000033a600] Capturing whole desktop as 404x272x32 at (1288,450)
> Input #0, gdigrab, from 'desktop':
>   Duration: N/A, start: 1478944371.848455, bitrate: 35168 kb/s
>     Stream #0:0: Video: bmp, bgra, 404x272, 35168 kb/s, 10 fps, 10 tbr, 1000k tbn, 1000k tbc
> No pixel format specified, yuv444p for H.264 encoding chosen.
> Use -pix_fmt yuv420p for compatibility with outdated media players.
> [libx264 @ 000000000066f200] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
> [libx264 @ 000000000066f200] profile High 4:4:4 Predictive, level 2.1, 4:4:4 8-bit
> [libx264 @ 000000000066f200] 264 - core 148 r2721 72d53ab - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=10 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
> Output #0, mp4, to 'G:\Marcus\Photos\ShareX\2016-11\2016-11-12_10-52-51.mp4':
>   Metadata:
>     encoder         : Lavf57.57.100
>     Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 404x272, q=-1--1, 10 fps, 10240 tbn, 10 tbc
>     Metadata:
>       encoder         : Lavc57.66.101 libx264
>     Side data:
>       cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
> Stream mapping:
>   Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
> Press [q] to stop, [?] for help
> frame=   17 fps=0.0 q=0.0 size=      12kB time=00:00:01.60 bitrate=  63.4kbits/s speed=3.16x    
> frame=   22 fps= 22 q=0.0 size=      17kB time=00:00:02.10 bitrate=  64.5kbits/s speed=2.09x    
> frame=   28 fps= 18 q=0.0 size=      20kB time=00:00:02.70 bitrate=  62.0kbits/s dup=3 drop=0 speed=1.74x    
> frame=   34 fps= 17 q=0.0 size=      26kB time=00:00:03.30 bitrate=  63.4kbits/s dup=3 drop=0 speed= 1.6x    
> frame=   39 fps= 15 q=0.0 size=      30kB time=00:00:03.80 bitrate=  64.4kbits/s dup=3 drop=0 speed=1.49x    
> frame=   44 fps= 14 q=0.0 size=      34kB time=00:00:04.30 bitrate=  65.3kbits/s dup=3 drop=0 speed= 1.4x    
> frame=   49 fps= 14 q=0.0 size=      38kB time=00:00:04.80 bitrate=  65.2kbits/s dup=3 drop=0 speed=1.34x    
> frame=   53 fps= 13 q=0.0 Lsize=      41kB time=00:00:05.20 bitrate=  64.5kbits/s dup=3 drop=0 speed=1.31x    
> video:40kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.921177%
> [libx264 @ 000000000066f200] frame I:1     Avg QP: 0.00  size:  2415
> [libx264 @ 000000000066f200] frame P:52    Avg QP: 0.00  size:   727
> [libx264 @ 000000000066f200] mb I  I16..4: 100.0%  0.0%  0.0%
> [libx264 @ 000000000066f200] mb P  I16..4: 74.0%  0.0%  0.0%  P16..4:  0.5%  0.0%  0.0%  0.0%  0.0%    skip:25.5%
> [libx264 @ 000000000066f200] coded y,u,v intra: 0.2% 0.2% 0.2% inter: 0.4% 0.4% 0.4%
> [libx264 @ 000000000066f200] i16 v,h,dc,p: 99%  0%  1%  0%
> [libx264 @ 000000000066f200] kb/s:60.69
> ffmpeg version N-82324-g872b358 Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 5.4.0 (GCC)
>   configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
>   libavutil      55. 36.100 / 55. 36.100
>   libavcodec     57. 66.101 / 57. 66.101
>   libavformat    57. 57.100 / 57. 57.100
>   libavdevice    57.  2.100 / 57.  2.100
>   libavfilter     6. 66.100 /  6. 66.100
>   libswscale      4.  3.100 /  4.  3.100
>   libswresample   2.  4.100 /  2.  4.100
>   libpostproc    54.  2.100 / 54.  2.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'G:\Marcus\Photos\ShareX\2016-11\2016-11-12_10-52-51.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf57.57.100
>   Duration: 00:00:05.30, start: 0.000000, bitrate: 63 kb/s
>     Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 404x272, 61 kb/s, 10 fps, 10 tbr, 10240 tbn, 20 tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
> Output #0, image2, to 'C:\Program Files\ShareX\Tools\palette.png':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf57.57.100
>     Stream #0:0(und): Video: png, rgba, 16x16 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 10 fps, 10 tbn, 10 tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
>       encoder         : Lavc57.66.101 png
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> png (native))
> Press [q] to stop, [?] for help
> [Parsed_palettegen_0 @ 0000000000597b20] 45(+1) colors generated out of 45 colors; ratio=1.000000
> [image2 @ 00000000004dbba0] Could not open file : C:\Program Files\ShareX\Tools\palette.png
> av_interleaved_write_frame(): I/O error
> frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.10 bitrate=N/A speed=1.77x    
> video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> Conversion failed!

**Comment by Jaex** [comment]
You changed ShareX personal path to program files and FFmpeg don't have access to create file there.

**Comment by MarcusTarkus** [comment]
Oh, I didn't even think about that. Thank you!

Fixed it by moving the ffmpeg.exe
