### ISSUE TITLE
Allow actions to run for file uploads and/or add local file path to custom uploaders

### ISSUE THREAD

**Issue by ds6** [ShareX/ShareX#2086]
I decided to make my own service for file hosting, and the server is hosted on my own machine. I thought it would be good to allow for local file "uploads" so that it just copies the file to the directory that files are served from.

Originally I tried using "Perform actions" to run a shell script to automatically move images and files to the right directory and with the right filename pattern, which worked well, but then I realized this only worked for image and clipboard capture and not file upload or URLs.

Next I tried writing a small webapp to handle it instead, to use as a custom uploader. I got all the backend code done and then after messing around with ShareX I realized there was no ability to give the URL of the file that was saved or the path of the file to be uploaded (that I could find at least), which my API would prepare to be served.

Would there be a way to either add support for performing actions on all file types, or to add the local path of the file for use with custom uploaders? One way to solve it would just be to add $input$ to custom upload GET requests (which normally are not allowed, so it wouldn't break backwards compatibility at all) and have it point to the local file. If the file wasn't saved, then an error can be thrown like before.

Yes, I could just pipe the data through a POST request, but I feel that's rather pointless when I could just move or copy it locally, saving lots of processing power and time. If this is not something that is in the scope of the project then I will either try my hand at adding it myself or find some other way to approach it that doesn't involve piping gigs of data through the app.

**Comment by Jaex** [comment]
Why don't you use "Shared folder" destination to copy files to any folder you want and generate url for it.

**Comment by ds6** [comment]
I've never used that, it looks nice. However it's not what I'm looking for. I already have a server to serve the files that uses its own method of functionality, and I would prefer to use it, especially if I want to build on it in the future. It would be a nice solution for simpler usage though.
