### ISSUE TITLE
Feature Request: Random (FTP) Uploader

### ISSUE THREAD

**Issue by d0x7** [ShareX/ShareX#2087]
Could you please add the ability to have multiple "active" (FTP-)Uploaders and once you're uploading a screenshot, it picks a random one from the "active" ones?

For example, I currently have 4 different ([Screenshot](https://cdn.d0x7.com/3)) FTP upload configs  (which are all the same, just the "PreviewHttpPath" is different) and I wanna use a different upload config with each upload. Like cyle through those config's.

Also, is there any feature like uploading to multiple hosts?

Thanks.

**Comment by Jaex** [comment]
#2050
