### ISSUE TITLE
ShareX - combine pictures

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#2088]
Files are removed from file system.

![sharex_2016-11-15_17-49-22](https://cloud.githubusercontent.com/assets/18115558/20314836/e4fa0e00-ab5b-11e6-9def-23104f563973.png)

**Comment by vatterspun** [comment]
Not seeing this on my system.  Tested in Win7x86.

1. Tools - Image Combiner
2. Added some screencaps from my desktop
3. Clicked combine images button

Result: Opened in Greenshot image editor as expected

**Comment by YasseenDeHerdt** [comment]
Did you try this too:
1. Tools - Image Combiner
2. Added some screencaps from my desktop
3.  Delete those screencaps from file system
4. Clicked combine images button

**Comment by vatterspun** [comment]
@YasseenDeHerdt 
I don't think what you're describing is a bug.  That the program waits until you click combine to actually go out and grab those images is fairly normal.  Otherwise it's going to require @Jaex to write an additional caching step which seems unnecessary.
