### ISSUE TITLE
Region Capture: Add color picker (pipette)

### ISSUE THREAD

**Issue by FichteFoll** [ShareX/ShareX#2090]
You can't pick a color for fore- or background annotations in region capture. By picker I mean the pipette that allows to take the color of an on-screen pixel.

In the same vein, it would be nice if the color of the currently hovered pixel was shown below the magnifier.

**Comment by vatterspun** [comment]
> You can't pick a color for fore- or background annotations in region capture

Are you talking about in the Image Editor or in the Image Effects tool?

**Comment by FichteFoll** [comment]
Uhm, I'm talking about Region Captue. Not sure if it has another name.

**Comment by vatterspun** [comment]
Oh okay ... I'm not sure I understand what you're requesting in terms of functionality.

**Comment by Jaex** [comment]
Because pipette using region capture window too, opening two different region capture window top of each other can cause performance issues or problems, therefore I'm not planning to add it.

**Comment by FichteFoll** [comment]
That's a bummer. Overlaying content (for example text) with a rectangle of the same color as the background is a common patter for censoring and will be impossible in region capture.

Couldn't you make the pipette re-use the already open region capture?

**Comment by Jaex** [comment]
Wouldn't using Pixelate with 1000 size can work which will mainly use background color only to fill rectangle area. But I was set maximum limit 100 for it so I must change it now.

**Comment by Scrxtchy** [comment]
![](https://jii.moe/NyUKxVBzz.png)
? I've used this for many revolutions around the sun

Ctrl+C Will copy whatever is in the info text box, you sacrifice regular position information for this

**Comment by AndroidDeveloperLB** [comment]
Why was this closed?
It's actually a good thing, to be able to do both cropping and copying of the color...

**Comment by Scrxtchy** [comment]
@AndroidDeveloperLB I have updated my comment to upload the image to github
![image](https://user-images.githubusercontent.com/12771982/53693602-d8cbe100-3df6-11e9-8dc4-f23f29f7814e.png)

**Comment by AndroidDeveloperLB** [comment]
@Scrxtchy I've made 2 requests about this:

https://github.com/ShareX/ShareX/issues/3998
https://github.com/ShareX/ShareX/issues/3999
