### ISSUE TITLE
Bug: Task sequence is ignoring task settings

### ISSUE THREAD

**Issue by vatterspun** [ShareX/ShareX#2091]
**Setup**: Win7x86 and x64, ShareX 11.4.1

**Steps**:

1. Download the portable ZIP version 
2. Click **Hotkey settings**
3. Click **Add** 
4. Select **Screen Capture - Auto Capture** from the "Task" dropdown list
5. Set description to "autocap"
6. Uncheck all default actions
7. Set the after capture menu to exclusively **Save Image to file** (_The crucial bit here is that "Copy image to clipboard"_ isn't checked.)

![out](https://cloud.githubusercontent.com/assets/1289134/20328807/6023e292-ab5a-11e6-9268-fdfa84e9a10a.png)

8. Press **X** to return to the Hotkey menu
9. Set the hotkey (I used CTRL+SHIFT+A) and again press **X** to return to the Main screen
10. Execute the hotkey and set the location to full screen and click **Start**
11. Execute the hotkey again to stop
12. Open a program like Word and paste

**Defect**: The last screen capture of the sequence is saved to the clipboard (shown here pasted into a Word doc immediately after capture sequence):

![out2](https://cloud.githubusercontent.com/assets/1289134/20329002/6cfdd92c-ab5b-11e6-98a4-1da6b6a05616.png)

**Other notes:**

* Affects versions 11.3 and 11.4.  I think this surfaced around version 11.3 but I'm not sure.  Can try to verify if that helps.
* I consider this a minor issue in an excellent program.  Hope this is useful. 
* I realize there's probably a shorter process I could have run to demonstrate this but I've tested 

**Related**
#2066

**Comment by YasseenDeHerdt** [comment]
I did not read all but you make nice bug reports.

**Comment by vatterspun** [comment]
@YasseenDeHerdt 
That's a fine compliment, thank you :)

**Comment by Jaex** [comment]
Because auto capture form is singleton it was using default task settings.

**Comment by vatterspun** [comment]
> auto capture form is singleton it was using default task settings.

Sorry, I don't understand.  The form is singleton?  Do you mean there has to be more than one option selected than **Save image to file**?

**Comment by Jaex** [comment]
There is only one form you can't open two different auto capture form with two different workflows. So because it is only form it was using default task settings not hotkey one.

**Comment by vatterspun** [comment]
> There is only one form, you can't open two different auto capture form with two different workflows.  So because it is only single form it was using default task settings not hotkey one.

Sorry, I'm just not understanding here: I've only set up one auto-capture capability.  I don't know what you mean by two forms.  

Maybe it might help to suggest a workaround for this?  My goal is to run auto-capture without copying each and every one of them to the clipboard.  The concern is that it's both slowing down the recording process with additional function, as well as banking a lot of screens in my clipboard logging program (the excellent open source Ditto).

**Comment by vatterspun** [comment]
I have resolved this.

1. Setup the default actions as not saving to clipboard:

![sharex_2017-01-25_18-45-17](https://cloud.githubusercontent.com/assets/1289134/22315858/e4b0e3b4-e32e-11e6-9fa2-b80a2d0fab1e.png)

2. In **Task settings**, setup Capture region to save captures to clipboard:

![sharex_2017-01-25_18-44-43](https://cloud.githubusercontent.com/assets/1289134/22315839/c35f8d96-e32e-11e6-83c3-590eb7776f37.png)

3. Also in **Task settings**, setup Task: Auto capture to Save Image to File

![sharex_2017-01-25_18-56-09](https://cloud.githubusercontent.com/assets/1289134/22316033/fbd18a16-e32f-11e6-8af9-45889c6941c6.png)
