### ISSUE TITLE
Impossible to paste to GitHub or Visual Studio Team Services

### ISSUE THREAD

**Issue by JulienFerraro** [ShareX/ShareX#2092]
Steps to reproduce : 
1. Capture a screen and copy it to the clipboard (via the menu or the image editor)
2. Create a new GitHub issue (or VSTS backlog)
3. Paste the image
4. Nothing happens

The workaround I found is the following : 
1. Capture a screen and copy it to the clipboard (via the menu or the image editor)
2. Paste it into Paint.net
3. Copy the image from Paint.net
4. Create a new GitHub issue (or VSTS backlog)
5. Paste the image
6. It's there

**Comment by campbeb** [comment]
Try the setting mentioned here: #1961

**Comment by JulienFerraro** [comment]
@campbeb thank you that did it perfectly.

Problem solved !
