### ISSUE TITLE
TargetInvocationException

### ISSUE THREAD

**Issue by jlixerkun** [ShareX/ShareX#2094]
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.BadImageFormatException: No se puede cargar el archivo o ensamblado 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ni una de sus dependencias. Se esperaba que el módulo tuviera un manifiesto de ensamblado.
   en ShareX.TaskSettingsTools..ctor()
   en ShareX.TaskSettings..ctor()
   en ShareX.ApplicationConfig..ctor()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   en System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   en System.Activator.CreateInstance[T]()
   en ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   en ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   en ShareX.Program.LoadProgramSettings()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 11.4.1 (Release)

**Comment by Scrxtchy** [comment]
#2083

**Comment by Jaex** [comment]
#1615
