### ISSUE TITLE
(Solved \ feature request) optimize PNG screenshots with PngOptimizer

### ISSUE THREAD

**Issue by UserNaem** [ShareX/ShareX#2096]
This took me quite a while to figure out. Could this be an inbuilt feature so others don't have to look up on how to run a CLI application via "Actions"?

File path: C:\Windows\System32\cmd.exe
Arguments: /c PngOptimizer -KeepFileDate -file:%input
Extension filter: png
Hidden window flag checked
This assumes PngOptimizer is in $PATH. The filesize reduction is usually 20-40% so I think it's worth doing.

**Comment by Jaex** [comment]
I was tried png compression softwares and those were taking so long time when lowest possible size aimed. And even then file size difference was so small it was not worth doing. But ofc for people who want to use those images on web site every bit of bandwidth usage decrease can help but it is minority of people. Also if it can reduce size 40% then it must be doing lossy reduction. In this case you can use jpg anyway. So I don't think it is worth adding by default.

**Comment by UserNaem** [comment]
No, PngOptimizer usually takes less than one second to process the image, and raw pixel data stays the same without quality loss.
Please make an instruction on how to run a CLI application via Actions, it took me like 2 hours to figure that out and it's not mentioned anywhere in the wiki.

**Comment by Jaex** [comment]
Writing instructions very difficult with english.
