### ISSUE TITLE
Cant take pictures

### ISSUE THREAD

**Issue by Ardow** [ShareX/ShareX#2098]
I press my keybinds the sound comes up but no picture, i check history no picture there either. But when i check the ShareX "thing" it says that i've "done something" no url it just says DONE i cant open or copy it. While im here id like to know how to get my pictures to turn into puush links... i only get them as pictures i have set file, text and image uploader too puush but i still only get pictures...?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/BmOnAENZuL.png) did you have these checked?

**Comment by Ardow** [comment]
Thank you! Fixed!
