### ISSUE TITLE
Transparent background ?

### ISSUE THREAD

**Issue by warpdesign** [ShareX/ShareX#2099]
When capturing a window with transparency & shadow enabled, the window is correctly captured, but with some applications the captured image has a white background below the shadow.

For other apps, it works and the background is transparent.

For example with the cmd.exe app it works as expected:

![works](https://cloud.githubusercontent.com/assets/199648/20400374/bcf46f6e-acf4-11e6-9802-b054bbb26167.png)

And here is an app where the transparent background is replaced with white solid color on the captured picture: this makes inserting the capture into other projects impossible:

![doesntwork](https://cloud.githubusercontent.com/assets/199648/20400408/e0473a3c-acf4-11e6-8d09-a3fa669f0229.png)

**Comment by warpdesign** [comment]
Here are some random apps which doesn't seem to show a transparent background:

 - VSCode
 - Directory Opus
 - Microsoft Edge
 - Microsoft IE 11

**Comment by vatterspun** [comment]
Wait, what steps are you using to get this?  Capture - Region (Transparent)?  I can't figure out how you did that.

Anyway, two a possible workarounds:

1. You can make any screencap have a transparent surrounding via the **Image Effects** menu and selecting **Add Image Effects / watermark** from the **After Capture tasks** menu. 

2. Choose **Drop Shadow** under the Greenshot image editor:

![Uploading 2016-11-17 16_47_31-Greenshot image editor - 258x142 - 2016-11-17_16-45-25.png.png…]()

**Comment by warpdesign** [comment]
I am using alt+printscreen to take a screenshot of the current active window.

Sometimes the created image file has a white background, sometimes background is transparent (that's what I always expect).

**Comment by campbeb** [comment]
Does the fix at #1393  help you at all?

**Comment by warpdesign** [comment]
@campbeb I'm not sure I understand what the fix is supposed to be.

Btw, it's not a clipboard problem: ShareX generates a file and that file doesn't have a transparent background when opened in an editor.

**Comment by warpdesign** [comment]
Here is what I am doing:

 1. press alt+x to take a screenshot of the current active window
 2. open the created file into an editor that properly handles transparency (photoshop,...)

What happens ?

 - The picture sometimes doesn't have a transparent background, it's solid white instead

What should happen

 - The picture should always have a transparent background

Note: it seems to depend on the application. For example, I see no problem with CMD.exe, but Microsoft Edge always have a white background.

**Comment by Jaex** [comment]
#167
