### ISSUE TITLE
Upload file and copy URL to clipboard

### ISSUE THREAD

**Issue by tx-trainwreck** [ShareX/ShareX#2100]
I looked through the CLI arguments in the Wiki and I'm trying to work with a CL that uploads the selected file to imgur.com and then copies the URL to the clipboard.

The following will upload the selected file:
"C:\Program Files\ShareX\ShareX.exe" "%1"

But if I add -CopyURLToClipboard before or after the file variable, it doesn't do anything.
"C:\Program Files\ShareX\ShareX.exe" "%1" -CopyURLToClipboard 

Any ideas?

**Comment by Jaex** [comment]
You can create workflow with copy url to clipboard and run that workflow using CLI.

**Comment by tx-trainwreck** [comment]
Thanks, that worked great.
