### ISSUE TITLE
Change Preview Action to Image Editor

### ISSUE THREAD

**Issue by tx-trainwreck** [ShareX/ShareX#2101]
When a screenshot is taken, a preview of the file is shown in the bottom right hand corner.  If I click on it, it appears in my default image viewer.  Is it possible to have a parameter so that when I click on it, it appears in the Image Editor instead?  That would serve both purposes of viewing and quickly initiating an edit to the file.  Thanks.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/ShareX_k9O8XdE2an.png)
