### ISSUE TITLE
Have more choices for Destinations

### ISSUE THREAD

**Issue by Dreadaxe** [ShareX/ShareX#2104]
When you choose the destination for send, it's a pity to don't have the possibility to choose more than one service.  I imagine to have to choose when I put to the "upload" button.

**Comment by campbeb** [comment]
Based on the comments in #2075, I think you are wanting more options when you choose Upload inside the Greenshot editor.
Clicking Upload in the Greenshot image editor just tells the main program to continue executing after capture and after upload tasks.
There are many options in those menus that will probably satisfy what you are looking for.

**Comment by vatterspun** [comment]
@Dreadaxe Could you give some detail here on what's missing?  ShareX has more upload options than most uploader tools available, freeware or otherwise.
