### ISSUE TITLE
Send image with email destination, options and contacts

### ISSUE THREAD

**Issue by Dreadaxe** [ShareX/ShareX#2105]
Pity that don't have access to my contact or simply open my email client program.

**Comment by Dreadaxe** [comment]
Look to Fireshot
http://i.imgur.com/XfvN3M1.png

**Comment by vatterspun** [comment]
@Dreadaxe You might want to look up how to write a feature request.  I know your native language is French so I tried to find something in French that might help with that process.

**Comment by Dreadaxe** [comment]
@vatterspun  news?
Send by email icon to image editor please
