### ISSUE TITLE
Screen recording stalls at 00:00:00 before starting to record

### ISSUE THREAD

**Issue by oxysoft** [ShareX/ShareX#2106]
I have the "Start recording after:" option disabled and the recording doesn't begin immediately, it stalls at 0 for a few. Even enabling that option, it will count down, then stall at zero before starting. I use ffmpeg to record with VP8 and Vorbis codecs, and the recorder devices for inputs. (screen-capture-recorder and virtual-audio-capturer)

I wouldn't half mind it if there was a countdown to this delay so that I know exactly when it'll begin to record. I can only assume that this happens because fffmpeg is preparing to record or something of the sort but it would be GREAT if it could be worked around.

**Comment by Jaex** [comment]
ShareX runs ffmpeg.exe to record. Executable must be opening slow for you. How am I supposed to workaround that? I already made sure that counter not starts without actual recording start, so atleast it shows proper counter.

**Comment by oxysoft** [comment]
Would it be possible to keep an idle ffmpeg process running which only starts recording when you want to use screen recording? Also is there any way I can actually test to see if that is indeed the issue and not something else

**Comment by Jaex** [comment]
Even if it is possible it would be so horrible workaround to hold it on memory for no reason.
It is combination of executable opening and recording initiating in ffmpeg which is both not fixable in ShareX.

**Comment by vpathuis** [comment]
We had the same issue and were able to fix this by finding the ffmpeg command in the debug console of ShareX and running this command in a command prompt. This showed an error that had caused ffmpeg to quit and we were quickly able to fix this (audio device was not found in our case, but could be something else of course).
