### ISSUE TITLE
Add quick action on capture panel to copy capture to clipboard

### ISSUE THREAD

**Issue by Zvirja** [ShareX/ShareX#2110]
Very often I need to just make a screenshot with annotations (e.g. arrows, rectangles) and use it as an image. In this scenario I don't need to upload picture. Moreover, often it might be dangerous to upload screenshot because it contains confident data (e.g. pieces of source code).

It would be really useful if we could add somehow a "Copy to clipboard" button to the capture panel:
![image](https://cloud.githubusercontent.com/assets/1074182/20533175/513a6734-b0e5-11e6-956a-a47df1a75930.png)

Now there is a very inconvenient workaround - I enable post-editing, later use Greenshot Editor to copy to clipboard and discard operation. But there are issues with that:
- If you close Greenshot Editor, it will just upload image >_> You need to don't forget to click the "Abort" button (or `Alt` + `C`). I'm using ShareX for more than 3 months and still forget to press the "Abort" sometimes :(
- It's not very convenient to have an extra-window to just copy content to clipboard.

I understand that it might be "dirty" from architecture perspective, where you have a pipeline. But it worth it for me. For instance, this button could define some "Copy to clipboard" pipeline instead of the default one.
I don't mind to even implement that via custom plugin, but do we have an API for that?

If you don't mind, I could fire a PR and try to add this feature.

**Comment by Jaex** [comment]
#2063
