### ISSUE TITLE
How does one use the "draw rectangle" tool?

### ISSUE THREAD

**Issue by grub-basket** [ShareX/ShareX#2111]
When I want to take a screenshot and click the option to draw a rectangle on the screen, and hit enter, it doesn't seem to do anything. Nothing ends up in Sharex's main window, either. What purpose does it serve and what is it for? 

When I click inside the rectangle, the screenshot frame disappears, when I click outside of it, the same happens. 

It seems like it serves the purpose of both making a rectangle around something, as well as being able to set the dimensions for a screenshot. 

Thank you in advance.

**Comment by Jaex** [comment]
You talking about "Drawing: Rectangle" or "Region: Rectangle" ?
