### ISSUE TITLE
Imgur is down check

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#2119]
I wonder if this will be feasable.
If imgur returns a bad response, check it's status page,
https://imgur.statuspage.io/

Which has a functioning API, docs are readable at 
https://imgur.statuspage.io/api

There's a possibility that the site is complete shit and won't actually assist, I don't use imgur, so I won't be able to see if results from an upload will actually give a reasonable response from the statuspage.

The main reason I'm considering this, so we can alert unaware users that imgur is indeed the issue with uploads, instead of resorting to the issues page here before being directing blame back to the upload service

**Comment by Jaex** [comment]
Check here and see: https://imgur.statuspage.io/history

Their API issues never show up there.

**Comment by Scrxtchy** [comment]
The incidence history will only display incidents that are written up manually to inform users by the system managers, not any outages that are detected by the system
for example; http://status.melbourneit.com.au/incidents/vx7rp1sqy083

I have a python script running in the background of my machine that will report any downtime
