### ISSUE TITLE
Cancel all after capture tasks from Annotate Image task

### ISSUE THREAD

**Issue by DmitriyYukhanov** [ShareX/ShareX#212]
Sometimes in Image Editor (Annotate Image task) I see what I captured wrong stuff and would like to not upload it at all. Would be great to be able to cancel any further tasks right from Image Editor.

**Comment by kkonarkk** [comment]
Hi,
Commenting on a closed  issue, hope that's alright.
Is there anyway to change the file-type from bmp to png in the Annotate Image task? 
Like in Jaex 's screen-capture above,  the new capture (in Annotate mode) opens as bmp in Greenshot Image editor. Is that by design?

**Comment by Jaex** [comment]
@kkonarkk Saving happens after annotation obviously therefore it can't be PNG. What is point of saving image before annotation if image gonna be changed anyway.

**Comment by kkonarkk** [comment]
@Jaex  Good point. I guess my issue is, I click on the green check-mark on the top-left corner after annotation which doesn't seem to be saving the file. I understand I can simply use "save image as" option.
