### ISSUE TITLE
How to copy settings to new portable version

### ISSUE THREAD

**Issue by neomodern** [ShareX/ShareX#2120]
I've downloaded the new portable version but it's not obvious what to do as there's no Wiki page for it nor is there a distinct 'Settings' folder in the portable app.

So I don't know which files I need to copy across into the new portable folder in order to retain my hotkeys and other settings.

**Comment by Jaex** [comment]
You don't need to copy anything. It creates setting files inside same folder as portable executable.

**Comment by vatterspun** [comment]
> I've downloaded the new portable version but it's not obvious what to do as there's no Wiki page for it nor is there a distinct 'Settings' folder in the portable app.

This is an ongoing problem with portable software.  It's something the portablefreeware.com people are trying to solve by listing where settings are saved in the program listings https://www.portablefreeware.com/index.php?id=2409 but it's still non-simple.

The advantage to this manual procedure is that you have total control over your settings.  You can move them, swap them, backup to a previous version, or even try different settings files, etc.  It's great for software testing.
