### ISSUE TITLE
Add option: update automatically without confirmation dialog

### ISSUE THREAD

**Issue by kpa6uk** [ShareX/ShareX#2123]
Each time ShareX update is detected I see dialog asking me to confirm the update.
It asks me on every device I use: at home on 2 laptops and at work on my PC.
Every time I click `Yes`. It's annoying  because of high update rate of this wonderful app.
Please make an option (default: `false`) that I can set to `true`, and ShareX will not ask me next time it wants to update.
You can add checkbox to update dialog too: `[ ] Update automatically next time`

**Comment by Scrxtchy** [comment]
Reposting @campbeb's reponse to a similar issue;

What version of ShareX do you have? If it is 11.1, then you might have the bug mentioned at #1796

Otherwise, it sounds like you're asking for #1028

**Comment by kpa6uk** [comment]
It is related to #1796.
Version was 11.1, and I successfully updated to 11.4 from the About dialog.
Thanks.
