### ISSUE TITLE
ffscreencast usage question

### ISSUE THREAD

**Issue by modulexcite** [ShareX/ShareX#2125]
Thank you for an excellent tool, life wouldn't be the same without it.
Would it be possible to use https://github.com/cytopia/ffscreencast as the recording device for capturing mouse click animations? I know you have answered this a few times as ShareX uses ffmpeg and ffmpeg itself doesn't support this natively, sorry for posting yet another question about it.

**Comment by Jaex** [comment]
I don't think so:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/chrome_ugM5x08lid.png)

**Comment by modulexcite** [comment]
Thank you for your response, I understand they don't have a windows release yet but would it possible to add it if they did.

**Comment by Jaex** [comment]
It not look like video device so it wouldn't be possible.

**Comment by modulexcite** [comment]
ok thanks, just thought I'd check if that's a possibility.
