### ISSUE TITLE
Option to hide new toolbar

### ISSUE THREAD

**Issue by skiddiks** [ShareX/ShareX#2126]
Personally, I very rarely use any of the tools. It'd be nice if there was a to hide/unhide it, or a way to revert it back to the right-click menu.

**Comment by Jaex** [comment]
For now you can right click drag dots to collapse toolbar and make sure "remember menu state" option is enabled. That way it will waste very small area in your screen compared to now.

**Comment by IndubitablyBengt** [comment]
It would be great to just have a setting in the application to disable and enable it.

**Comment by Jaex** [comment]
I just don't understand why someone would like to hide it too. Annotation is very handy feature.

**Comment by IndubitablyBengt** [comment]
I love the implementation, don't get me wrong; the features and customizability of the program is really unparalleled, but that's the idea: in keeping with the spirit of customizability it should be able to turned off for those who don't ever use any of the tools. For myself personally, 99% of the time I am using ShareX I am using it to rectangularly capture a region after a hotkey, with auto upload to imgur. I normally just ignore the toolbar, but in the rare cases it gets in the way it does become annoying, just from a cleanliness point of view, to either stash it somewhere minimized or drag it out of the way when needed.

I don't want to be a complainer, it's just a small option that would be in keeping with the rest of the excellent customization available: every other aspect of the capture ui is customizable and able to be disabled or enabled except for this.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/ShareX.vshost_QsnE94f6Ti.png)

Added there.
