### ISSUE TITLE
Clipboard container doesn't understand url 

### ISSUE THREAD

**Issue by ZenoNiQ** [ShareX/ShareX#2127]
Link's like this one http://joyreactor.cc/post/2899075 doesn't try to be shortener 
log:

> 2016-12-04 12:43:58.604 - Executing: Upload from clipboard
> 2016-12-04 12:43:58.612 - Task in queue. Job: DownloadUpload, Type: File, Host: Gfycat
> 2016-12-04 12:43:58.619 - Task status: Preparing
> 2016-12-04 12:43:58.625 - Task status: Preparing
> 2016-12-04 12:43:59.470 - Upload started. Filename: 2899075, Filepath: C:\Users\ZenoN\Documents\ShareX\Screenshots\2016-12\2899075
> 2016-12-04 12:44:04.086 - Exception:
> System.DivideByZeroException: Attempted to divide by zero.
>    at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
>    at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 2016-12-04 12:44:04.100 - Upload failed. Retrying upload.
> 2016-12-04 12:44:07.447 - Exception:
> 

![image](https://cloud.githubusercontent.com/assets/1075196/20865600/7e541a6a-ba1f-11e6-9d6a-8b1c7578dd4b.png)

**Comment by Jaex** [comment]
You must uncheck first option. Because some file urls don't have extension it can't know is it file url or not.
