### ISSUE TITLE
FTP UPLOAD FAILURE

### ISSUE THREAD

**Issue by FaNNboii** [ShareX/ShareX#2128]
System.TimeoutException: Timed out trying to read data from the socket stream!
   bei System.Net.FtpClient.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   bei System.Net.FtpClient.FtpSocketStream.ReadLine(Encoding encoding)
   bei System.Net.FtpClient.FtpClient.GetReply()
   bei System.Net.FtpClient.FtpClient.Execute(String command)
   bei System.Net.FtpClient.FtpClient.Authenticate()
   bei System.Net.FtpClient.FtpClient.Connect()
   bei ShareX.UploadersLib.FileUploaders.FTP.Connect()
   bei ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   bei ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   bei ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   bei ShareX.WorkerTask.DoUpload(Int32 retry)

IsActive already false!

pls help!

**Comment by sergeevabc** [comment]
Specify your workflow step by step.

**Comment by vatterspun** [comment]
@FaNNboii if you want to give us a shot at helping, you might want to look up http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/
