### ISSUE TITLE
Region Capture is a Circle instead of Rectangle

### ISSUE THREAD

**Issue by breakinirl** [ShareX/ShareX#2129]
I don't know how I did this but can someone help me change this back to a rectangle instead of a circle please. It looks something like this. 
![circle](https://cloud.githubusercontent.com/assets/24388237/20886186/bb23564a-baec-11e6-816a-c5ea5134afdd.png)

**Comment by Jaex** [comment]
If you are using latest ShareX version then you can change region type from toolbar at top of screen.

**Comment by breakinirl** [comment]
HOW

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX_5M22VxiyZ7.png)

**Comment by breakinirl** [comment]
Ok thank you I had my toolbar disabled for these past few months so forgot that it was there

**Comment by Jaex** [comment]
How did you disabled toolbar?!

**Comment by breakinirl** [comment]
I don't know how but it isn't there haha its fine now tho thanks

**Comment by maximillionfrday** [comment]
I was glad to find this message... Thanks!!!

**Comment by UpworksTeam** [comment]
Hi all. This is the second time I've come across this "useless" feature. Enabling and disabling it is not logical and not explicit.
