### ISSUE TITLE
Auto increment failure

### ISSUE THREAD

**Issue by sergeevabc** [ShareX/ShareX#2130]
ShareX 11.4.1

Name pattern is ```%y%mo%d-%i{4}```.
Counter has been reset to zero.
Subsequent filename is expected to be ```20161207-0001```, but…
First after capture dialogue suggests ```20161207-0002```, second is ```20161207-0004```, etc

**Comment by Jaex** [comment]
You mean you canceled your previous after capture window and still %i was increased. Fixing that will be very difficult because increase of %i happens inside file name generation method.

**Comment by sergeevabc** [comment]
I do not cancel anything.
It’s just [increasing in a wrong manner][1], hence the increment feature is misleading.
Perhaps it’s time to suspend the development and focus on cutting down the complexity of pilot’s cockpit?

[1]: https://f.lewd.se/LwSJTx.mp4
