### ISSUE TITLE
ffmpeg 404 notfound

### ISSUE THREAD

**Issue by yangkebiao** [ShareX/ShareX#2133]
ffmpeg的官网暂时无法下载windows版本，请问是否可以给我发一个历史版本，谢谢了！

**Comment by Jaex** [comment]
What?

**Comment by yangkebiao** [comment]
Ffmpeg the official website temporarily unable to download windows version, may I ask if you can send me a historical version, thank you!

**Comment by yangkebiao** [comment]
Screen recording (gif) is not available

**Comment by Jaex** [comment]
Uploading FFmpeg latest version wait please.

**Comment by Jaex** [comment]
Your Windows is 64 bit, right?

**Comment by yangkebiao** [comment]
yes

**Comment by Jaex** [comment]
Uploaded here: http://ge.tt/9eTltlh2

**Comment by yangkebiao** [comment]
thank you

**Comment by Jaex** [comment]
#2049
