### ISSUE TITLE
Ability to use OCR on existing screenshots.

### ISSUE THREAD

**Issue by solmri** [ShareX/ShareX#2134]
(From what I have found) Currently the OCR functionality can be used only during a new capture. It is possible to extend this OCR functionality to the existing, already captured screenshots. 

Is this a viable feature to work upon? If yes, I'd definitely like to contribute.

**Comment by vatterspun** [comment]
**Workaround**: open a given screenshot in a viewer at 100% zoom and then run an OCR operation on that image.
