### ISSUE TITLE
Cant download ffmpeg.7z

### ISSUE THREAD

**Issue by andre-paulo98** [ShareX/ShareX#2135]
So i tried record a GIF with ShareX, first this shows up:
http://i.imgur.com/ROiNY6v.png
Clicked on yes and this show up:
http://i.imgur.com/o5ZTrX7.png
(Status: The remote server returned a error: 40.. )

**Comment by ohbugger** [comment]
Same here with v11.4.1 on W7.

**Comment by Jaex** [comment]
#2049
