### ISSUE TITLE
Wanted: Ability to capture window contents only...no frame.

### ISSUE THREAD

**Issue by Mortarm** [ShareX/ShareX#2139]
I know this can be done via Region, but it'd be more convenient as a one-click solution.

**Comment by Jaex** [comment]
You want this I think:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX_Bee0dNqXJK.png)

**Comment by vatterspun** [comment]
I didn't know this was an option.  Very cool.
