### ISSUE TITLE
Imgland.net

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2140]
I begin using images I uploaded to Imgland.net via ShareX to some music forums (album covers) and they starting being block from being display in my forums. 

Any idea why? Is uploading via ShareX considered uploading by proxy?  If so that may be why.

**Comment by Jaex** [comment]
You must ask to owner of imgland.net

**Comment by bytesoftly** [comment]
Did you manage to resolve your upload issue in the end (an imgland.net developer here)?

**Comment by MrCD1968** [comment]
They never replied. I just chose another upload access point.

  ----- Original Message -----
