### ISSUE TITLE
Bud: Ptr Scr does not work, NIS

### ISSUE THREAD

**Issue by glotmp** [ShareX/ShareX#2141]
screenshot does not work, when stands out Norton AntiVirus Internet security
![2016-12-11_12-06-52](https://cloud.githubusercontent.com/assets/3048263/21078265/18c6df44-bf9b-11e6-8547-0a59a8a99c9f.gif)
[https://9.lithi.io/Y4JpS.gif](url)

**Comment by Jaex** [comment]
That happens because norton ran as admin and sharex not ran as admin. So it is limitation of hotkey system and nothing can be done about it other than running sharex as admin.

**Comment by glotmp** [comment]
Oh, thank you!
