### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by PecnikMiha** [ShareX/ShareX#2142]
Our team takes a lot of screenshots while RDP-ing to other machines, this isn't currently possible with ShareX unless one copies the files to each server that is being administered. Please add the ability of Always on top.

**Comment by campbeb** [comment]
This works fine for me.
Is your RDP session in full screen or windowed? Can you explain how "Always on top" would solve your problem?

**Comment by Jaex** [comment]
I can't get what "Always on top" to do with it too. But if your app is not fullscreen you can try clicking tray icon to start region capture.

**Comment by PecnikMiha** [comment]
Let me add some background. I'm trying to switch from http://www.faststone.org/FSCaptureDetail.htm which has the always on top function and it lets me make screenshots even when using RDP in Full Screen (that is how I normally work). The Always On Top means that even when we RDP into a server, the program is visible even in that session.

We're testing the newest version of ShareX, but the portable version (in case that is the problem).

![capture](https://cloud.githubusercontent.com/assets/19249788/21090061/6b3255e0-c03d-11e6-8404-01e1a76160b8.png)

**Comment by Jaex** [comment]
Putting main window of ShareX top of RDP will be inefficient because that window is too big.

**Comment by Jaex** [comment]
If it were only menu I would easily make it but people gonna request customize able menu for sure which makes sense and making that gonna be so boring because for example I must assign icon for each possible button (task) etc. which is so repetitive work because there is alot of tasks which you can see from hotkey tasks. But you can still open issue for it because it is different than this issue.

**Comment by PecnikMiha** [comment]
OK, although such a shame. I'm thinking most would be just fine if the main windows could somehow be minimized to only a menu and that would contain only the features under "Capture" (I could do with just Full screen, Region and Screen recording). Exposing just the menus, without the right part of the GUI would also work just fine:

![capture](https://cloud.githubusercontent.com/assets/19249788/21093585/e9efe5a4-c052-11e6-8087-316a47b1b1d5.JPG)

**Comment by Jaex** [comment]
I told you it is fine for us to have that few buttons but then people gonna open issues and request customize able menu as always.

**Comment by PecnikMiha** [comment]
I totally agree, there will be requests, but it will still add functionality to the software. Being able to take screenshots on remote systems is definitely a big plus.

**Comment by Jaex** [comment]
Problem is when writing it from beginning, it must be designed with customize support to not write it from scratch in the future.

**Comment by PecnikMiha** [comment]
I understand. Please at least consider it, I've tried dozens of programs and this one has pretty much everything apart from this.

**Comment by Jaex** [comment]
I told you if you open new issue, one day I could be less bored and decide to do it. But not now :D Can't get bored even more.

**Comment by Jaex** [comment]
But I will be definitely adding it in future because it is also can be handy for people who want "Simple UI" so it can be called simple mode. Reason why I wanted you to open issue so I don't forget it.

**Comment by PecnikMiha** [comment]
Thank you, done.

**Comment by sergeevabc** [comment]
Region capture of 13.4 can’t detect the error window of [some other app][2], which is displayed on top of other windows, so I have to use Capture->Windows->[that window] as a workaround. However, for example, [FSCapture][1] has no such issue.

[1]: https://www.faststone.org/FSCaptureDetail.htm
[2]: https://github.com/farrokhi/dnsdiag/releases/tag/v2.0.0

**Comment by abdo2048** [comment]
@MP-blue You can use "Alyas on Top" tool which makes any winodw (one only) you choose on top. Download it: https://www.labnol.org/software/tutorials/keep-window-always-on-top/5213/
1. Run the tool 2. Make sure the window you want is selected 3. Press the shortcut Ctrl+Space 4. To disable it, press select the windows and press the shortcut again.
