### ISSUE TITLE
Simple UI request

### ISSUE THREAD

**Issue by PecnikMiha** [ShareX/ShareX#2144]
It would be great if there was an option of minimum UI, meaning it would only show the left part of the UI as it is now:
![capture](https://cloud.githubusercontent.com/assets/19249788/21097827/bfabe554-c066-11e6-964e-52083f0fbcd4.JPG)

This simple UI would also make it possible (if Always on top was implemented https://github.com/ShareX/ShareX/issues/2142#issuecomment-266400936 ) to take screnshots in RDP sessions.

I don't know how far you can take it, but having the ability to show, hide certain buttons, groups of buttons would be prefered. For example having the ability to completely hide Upload (company policy prohibits it, it wouldn't work as it is) would be an added bonus.

**Comment by Jaex** [comment]
I was planning to add just buttons from hotkey list which contains nearly all possible actions that exist in main window toolbar. But I can't add after capture tasks etc. sub menus with that system if that was what you wanted. Because it will be too complicated.

**Comment by Jaex** [comment]
This is currently how it looks:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/devenv_PdbmNufEDO.png)

Which made of this code:

`new List<HotkeyType>() { HotkeyType.RectangleRegion, HotkeyType.PrintScreen, HotkeyType.LastRegion, HotkeyType.FileUpload, HotkeyType.ClipboardUploadWithContentViewer };`

**Comment by PecnikMiha** [comment]
This looks awesome, as far as I'm concerned after capture tasks are not needed. I'd gladly test it when a there's a version available and provide additional feedback.

**Comment by Jaex** [comment]
This is work in progress edit window:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX.vshost_tVVjYiiw1C.png)

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX.vshost_a2EHMYINNW.png)

So you must have understood how it works now.

**Comment by PecnikMiha** [comment]
Thank you very much for implementing this, it really looks great.

**Comment by PecnikMiha** [comment]
Thank you yet again, it's my go to tool now.
