### ISSUE TITLE
Filename is not respected when saving record

### ISSUE THREAD

**Issue by sergeevabc** [ShareX/ShareX#2145]
ShareX 11.4.1

1. Set name pattern ```%y%mo%d-%i{4}```.
2. Record screen.
3. Change filename to ```x``` in after-capture dialogue.

Result: ```20161212-0016.mp4```
Expected: ```x.mp4```

**Comment by Jaex** [comment]
I can't reproduce this too: https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/custom%20file%20name.mp4

Default name was random but it used after capture form file name.

**Comment by sergeevabc** [comment]
[Watch screencast].

[1]: https://a.rokket.space/zoikyi.mp4

**Comment by Jaex** [comment]
It was intended because after capture form not designed to rename already exists files but instead allows you to set what name to be supplied to task but I can modify code to also rename file.

**Comment by sergeevabc** [comment]
Name for the task?! What?

After capture dialogue implies capture has been made and it resides in some kinda limbo while user decides what to do with it (add annotations, save to specified filename, upload, etc). That’s why there is filename field on the bottom with suggested name. And when user marks “Save to file” and changes that filename, that capture is expected to be saved with exact that name.

**Comment by Jaex** [comment]
After capture window file name field is designed to be used for "Save file" task. And it was designed for screen capture only. So I cheated and added it for screen recording too and because it not using "Save file" and file already exists, it not renames already exist file but using that name in all part of task jobs which is uploading etc.

**Comment by sergeevabc** [comment]
> So I cheated and added it for screen recording too
This issue should be label as Enhancement then since current (screencasted) behaviour is so misleading.
