### ISSUE TITLE
Option to upload Gif to different site than images?

### ISSUE THREAD

**Issue by alster551** [ShareX/ShareX#2147]
Sometimes i record GIFs which are too long for Imgur to upload, which is my preferred image hosting site, but Gfycat allows, however I have to manually change this whenever i want to record a gif or upload an image, unless im missing something there isn't away to set this. Could something like this be added?

**Comment by Jaex** [comment]
L,ike this?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX_3J6erLNfwU.png)

**Comment by alster551** [comment]
Yup!

**Comment by fireclaw20** [comment]
Is the "like this?" supposed to show something? I want to know as well.

**Comment by Jaex** [comment]
Fixed image link.

**Comment by MicaelJarniac** [comment]
Is it possible to add a file size filter, so like <10MB gifs go to Imgur and >=10MB ones go to Gfycat, for example?
