### ISSUE TITLE
Hotkey Triggers, No Action Executed

### ISSUE THREAD

**Issue by Marty9231** [ShareX/ShareX#2148]
I tried assigning a hotkey to record a GIF in a custom region. The assigning went fine, the debug log shows that it recognizes my command, but it does not actually execute anything.

![image](https://cloud.githubusercontent.com/assets/24533516/21119655/db4d67e4-c0c3-11e6-93c8-e7a92066e782.png)

The log produces the above whenever I hit my shortcut, but it does not allow me to select a region nor do anything else. If I hadn't opened the log it is as if nothing actually happened. I've tried rebooting, re-launching and re-assigning the hotkey to other things, same result.

**Comment by Jaex** [comment]
Custom region is not allows you to select region it is to use already assigned regions which means quick capturing.
