### ISSUE TITLE
Add support for GitHub Enterprise Gist

### ISSUE THREAD

**Issue by fragmer** [ShareX/ShareX#2149]
[GitHub Enterprise](https://enterprise.github.com/) is a version of GitHub (which includes Gist) that is hosted on a local server by a business or organization. These instances of GitHub support all the same APIs as regular GitHub -- the only difference is the base URL.

Could you please add a way to upload text (at least anonymously) to GitHub Enterprise Gist, by adding a way to override `ShareX.UploadersLib.TextUploaders.GitHubGist.URLAPI` in the destination settings?

**Comment by Jaex** [comment]
I didn't know it is all about just adding custom URL. I thought it had special API or something.

**Comment by Jaex** [comment]
@mxschmitt should I remove custom URL support now? Because [anonymous uploads not possible anymore](https://blog.github.com/2018-03-20-removing-anonymous-gist-creation/) and your PR was only working with anonymous uploads.

**Comment by mxschmitt** [comment]
@Jaex sure, because now it isn't working anymore. Maybe add support there for custom URL authorized Gists.

**Comment by alexgman** [comment]
so how do we upload to non-enterprise gist at the moment? is this possible?
