### ISSUE TITLE
Audio from source when screen recording

### ISSUE THREAD

**Issue by godratio** [ShareX/ShareX#215]
Screen capture with audio source select would be a nice feature to have.

**Comment by jontio** [comment]
For others they are found by going to
**Main window -> Task settings -> Capture -> Screen recorder**

**Comment by Alexico1969** [comment]
I changed the settings  (audio source) ... but still..   no sound is recorded... :-(

**Comment by Alexico1969** [comment]
> I changed the settings (audio source) ... but still.. no sound is recorded... :-(

Wait... wait.... its working now !  :-)
