### ISSUE TITLE
FEATURE REQUEST: Local historical log of [locally saved image Name ::::URL link]

### ISSUE THREAD

**Issue by AnacondaPython** [ShareX/ShareX#2151]
Hey Jaex

I've used shareX for well over 5000 images/gifs and have really loved everything about it over the past 2 years

I have one concern though when it comes to scability in managing images.

Should the company I host my images at (imgur.com) were to shutdown, a lot of various tools and services that I have used with imgur.com links would also go away. These include blog links, email links, reddit links, note links, etc, which would reverse a lot of the work I've done in those areas

I'd like a way to back it up locally. ShareX already has the option to copy the filepath of the image to the clipboard,  and copy the shareable imgur.com link as well. 

**Could you perhaps make a setting in ShareX that allows a .log,.txt,.csv, or .xml to be made during creation of links? This file would relate all imgur.com links created to their localfilepath image equivalents**.

E.G.

2016-12-07_10-41-29.gif, imgur.com/XXXXXXX
2016-12-06_9-30-29.png, imgur.com/ABCABC
chrome_2016-12-04_12-28-29.png, imgur.com/DEDEDEDEDE

This way, if I had to rebuild any text based files, I can run some scripts (if imgur.com decides to cease working.)

**Comment by Jaex** [comment]
You know ShareX have history support, right?

**Comment by AnacondaPython** [comment]
Okay with ShareX history support, the only problem is that its in a .sxb format which I am not familiar with.  If I could geta .txt or .csv format that would be nice. 

Basically, all these files

![](http://i.imgur.com/5SPG0WY.png)

how would I go about doing this?

**Comment by Jaex** [comment]
I don't know what is .sxb but history is in .xml format. Which is one of the easiest parseable format.

**Comment by AnacondaPython** [comment]
![](http://i.imgur.com/xb5VYY8.gif)

.sxb is shareX backup format you had set on there. I cannot find where the export XML is anywhere though

**Comment by Jaex** [comment]
It is inside `Documents\ShareX`.
