### ISSUE TITLE
Error when upload a GIF on my FTP..

### ISSUE THREAD

**Issue by SwokZ** [ShareX/ShareX#2152]
Hi i got a problem when i try to upload a gif / big (~5Mo) .RAR
For the gif i got this error :

> L'analyse de la réponse a échoué.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   à Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   à ShareX.HelpersLib.Helpers.ParseJSON(String text, String jsonPath)
   à ShareX.UploadersLib.CustomUploaderItem.ParseURL(String url)
   à ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, Boolean isShortenedURL)
   à ShareX.UploadersLib.FileUploaders.CustomFileUploader.Upload(Stream stream, String fileName)

And when the download is finished it restarts a second time..
Thanks for your help !

**Comment by Jaex** [comment]
You don't even tell where you uploading it to.

**Comment by SwokZ** [comment]
But it's strange because when i upload a smaller gif it work :/

**Comment by Jaex** [comment]
You can't right click to see response right? Probably response includes error message from your server.

**Comment by SwokZ** [comment]
No i have nothing :/

https://screen.swokiswoka.com/b2hYtupZ.png

**Comment by Jaex** [comment]
You have error message there which returned from your server. So problem is completely to do in your side.

**Comment by SwokZ** [comment]
Ok thanks, you don't know how can i see the error / fix it ? :/
Thanks for your help

**Comment by Jaex** [comment]
I don't know.

**Comment by vatterspun** [comment]
> Ok thanks, you don't know how can i see the error / fix it ? :/

You might want to look up suggestions on how to submit a bug report.  You've not provided much data here so it's hard for Jaex or other folks on here to potentially diagnose the issue.

- Have you tried other FTP tools?  Is it just ShareX that isn't working?
- What steps did you follow?
- What operating system are you using?  What version of ShareX?

**Comment by SwokZ** [comment]
I just have try with my FTP
Hum a custom ftp
and windows 10

**Comment by vatterspun** [comment]
> I just have try with my FTP ... Hum a custom ftp ... and windows 10

@SwokZ That's not a lot of additional data.  Again, you might want to look into how to submit a bug report.
