### ISSUE TITLE
AutoCapture repeat time intervals too coarse in 11.4

### ISSUE THREAD

**Issue by lr16** [ShareX/ShareX#2154]
If you restore the half-second repeat time intervals on the AutoCapture dialog, please say so in the Changelog so I know whether to update.

**Comment by Jaex** [comment]
What is interval is coarse even means?

**Comment by lr16** [comment]
Sorry.  It means coarse vs. fine.  In 11.3 you could repeat captures 1.5 seconds apart, 2 seconds apart, 2.5 seconds apart, etc.  In 11.4 it's only 2 seconds, 3 seconds, etc.  No more half seconds.
