### ISSUE TITLE
[suggestion] ShareX mono solution

### ISSUE THREAD

**Issue by johnfg10** [ShareX/ShareX#2155]
Hey i was reading https://github.com/ShareX/ShareX/issues/498 earlier and was wondering if support for mono has been considered shouldnt in theory require much if any work but would allow alot off users to access the program which i think is great BTW.

Thanks for your time.

**Comment by Jaex** [comment]
#498

**Comment by johnfg10** [comment]
mono you wouldnt need to rebuild as most of the project should work and to my knowledge winform is supported by mono
