### ISSUE TITLE
Uploader request: Giphy

### ISSUE THREAD

**Issue by savovs** [ShareX/ShareX#2157]
Hi guys, it would be awesome if ShareX could upload to http://giphy.com/

**Comment by Scrxtchy** [comment]
```
{
  "Name": "giphy",
  "RequestType": "POST",
  "RequestURL": "https://upload.giphy.com/v1/gifs",
  "FileFormName": "file",
  "Arguments": {
    "api_key": "dc6zaTOxFJmzC"
  },
  "ResponseType": "Text",
  "URL": "https://media.giphy.com/media/$json:data.id$/giphy.gif"
}
```
The api_key is public, if you want to use  your own; check the github repo
Same goes for username
https://github.com/Giphy/GiphyAPI#upload-api

**Comment by Jaex** [comment]
I sent API key request and this is their response:

Per our API terms of service, we request that our API partners include additional functionality outside of the features available on GIPHY products such as GIPHY Capture, which has the same functionality as your app. Therefore, we cannot issue you a production key at the moment.

**Comment by campbeb** [comment]
That's interesting that is the response that gave you.
From the API submission form, it says open-source apps should use the beta key vice a private production key.

> If your app is a form of a bot (ie. hubot), for internal purposes, open source, or for a class project, we highly recommend you institute the beta key for your app. Unless you're making thousands of requests per IP, you shouldn't have any issues.

However, the API license terms have other odd requirements even if you did choose to implement it:

> You shall (i) conspicuously label any Application with the words "Powered by Giphy," and the Giphy logo, and (ii) comply with the branding requirements that we may provide to you from time to time.

**Comment by Scrxtchy** [comment]
Interesting enough, this is done for the OCR form.
![](https://jii.moe/N1__xiWVG.png)
I suspect this is in place as people make applications dedicated for the giphy service, usually found on mobile IM clients

**Comment by vankasteelj** [comment]
That's a stupid response from them. They have no windows app, and all they do is make gifs where sharex does it all.

**Comment by vassilyzaitsev** [comment]
Still not able to upload to Giphy?
