### ISSUE TITLE
Disable magnifier crosshair

### ISSUE THREAD

**Issue by ertay** [ShareX/ShareX#2158]
Since I am visually impaired, I am using the Windows Magnifier 'Color Inversion' option heavily. However, since ShareX also uses the Magnifier API, when I want to capture a region, it 'disables' magnifier.exe and therefore removes the color inversion until the region is captured. After the image is captured, magnifier.exe takes control and reactivates color inversion.

Is there a way I can use 'Capture Region' with magnifier.exe running at the same time so I can take screenshots with color inversion turned ON?

Steps to reproduce:
1. Run Windows Magnifier (magnifier.exe)
2. In magnifier options, enable Color Inversion 
3. Try to capture a region - color inversion is turned off until capture is complete.

**Comment by Jaex** [comment]
ShareX not using magnifier API. Reason why this happens is, ShareX takes screen capture and showing it in background which is inverse colored. But then magnifier also inversing it which making it normal colors.

You can use "Region (Transparent)" which not takes screen capture to show in background. That way inverse can work properly.

**Comment by ertay** [comment]
That makes sense. Thank you.
