### ISSUE TITLE
CustomUploader: The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by Dunky13** [ShareX/ShareX#2159]
I haven't had a lot of problems until today, where all my machines I get this error:
> Message:
> The underlying connection was closed: An unexpected error occurred on a send.
> 
> StackTrace:
>    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
>    at System.Net.HttpWebRequest.GetRequestStream()
>    at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
> 
> System.ArgumentException: Stream was not readable.
>    at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
>    at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
>    at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)

I have BitDefender, tried disabling everything - firewall, ransomware protection, av etc.. - but no solution

**Comment by xathz** [comment]
I have this issue too. I set my web server to only accept TLS 1.2 and TLS 1.1 and all uploads from ShareX fail with this error. Enabling TLS 1.0 it works just fine.

**Comment by Dunky13** [comment]
Why is the code not compiled to .net 4.5/4.6? Seems like a bug

**Comment by Jaex** [comment]
Latest version have workaround to support TLS 1.2.
