### ISSUE TITLE
With new Nextcloud 11 I get an error

### ISSUE THREAD

**Issue by Lord-Protector** [ShareX/ShareX#2160]
Message:
Удаленный сервер возвратил ошибку: (412) Precondition failed.

Response:
{"message":"CSRF check failed"}

StackTrace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

**Comment by multimill** [comment]
Yep, same problem here. Would love to see an update for it.

**Comment by Jaex** [comment]
What is Nextcloud 11?

**Comment by Lord-Protector** [comment]
@Jaex, It's ideological successor of ownCloud. Core team of Nextcloud are from ownCloud.
In brief: The lawyers have fought with programmers. After some time we got fork -- Nextcloud.

**Comment by Jaex** [comment]
Is it not owncloud api compliant?

**Comment by Lord-Protector** [comment]
Yes. For example they just change some logos in desktop client and it's works good.
I think also important detail that screens and videos are successfully upload and I can use on my server, but with error 412 doesnt opens window for copy pic, link, etc.

**Comment by Jaex** [comment]
I mean if owncloud works properly and nextcloud not then isn't this means nextcloud API have problem.

**Comment by Lord-Protector** [comment]
@Jaex, I understand you. But I think it's some minor changes.
There many Nextcloud users, so I think in future you can divide it.

**Comment by Jaex** [comment]
Adding owncloud was already very difficult because I couldn't test it. So it is not easy for me.

**Comment by Lord-Protector** [comment]
@Jaex I think it's not I problem to give you account for testing :)

**Comment by multimill** [comment]
Yes, if needed I can provide an account for testing.

**Comment by aStonedPenguin** [comment]
I'd really love for proper nextCloud support

**Comment by Jaex** [comment]
If you want to test it: https://github.com/ShareX/ShareX/wiki/Dev%20builds

**Comment by multimill** [comment]
Nice one. Working without problems.

**Comment by Lord-Protector** [comment]
Thanks for fix!

**Comment by MarvinMenzerath** [comment]
I just tried a recent dev-build on a Nextcloud 11 installation and while the upload is working fine now, I am still unable to get a shareable url:
```
2016-12-30 00:47:38.108 - Upload started. Filename: 2016-12-30_00-47-38.png
2016-12-30 00:47:39.066 - AddWebError(): Message:
Der Remoteserver hat einen Fehler zurückgegeben: (412) Precondition failed.

Response:
{"message":"CSRF check failed"}

StackTrace:
   bei System.Net.HttpWebRequest.GetResponse()
   bei ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
2016-12-30 00:47:39.067 - Upload failed. Retrying upload.
```

Looking at the code from commit 23f9f1bdcfc2d77fddf7f27b036dca31bb3758c5 I assume, that the line
```
headers["OCS-APIREQUEST"] = "true";
```
also has to be added in the `ShareFile(string path)`-method.

Would you mind looking at this again?

**Comment by aStonedPenguin** [comment]
I made a PR @MarvinMenzerath According to their docs all APIs require that header, I assume in the non dev version it wasn't fully supported yet and that's why my first PR worked.

https://github.com/ShareX/ShareX/pull/2172

**Comment by MarvinMenzerath** [comment]
Thank you!
Now it works perfectly again!
