### ISSUE TITLE
System.Exception: 'File form name' must be not empty.

### ISSUE THREAD

**Issue by nick-2017** [ShareX/ShareX#2161]
When ever I try to upload a file using custom uploader, I get "System.Exception: 'File form name' must be not empty." error but 'File form name' is not empty.

Picture of custom uploaders and the error: https://files.simpleshare.pw/d6e4/sys/Lk9.png

Latest version (updated like 5 min ago)

**Comment by Jaex** [comment]
You are uploading to your other custom uploader which have file form name missing.
