### ISSUE TITLE
Option to remove ShareX from Windows context menu

### ISSUE THREAD

**Issue by 07416** [ShareX/ShareX#2162]
Is there a setting to remove ShareX entries from Windows context menu? Can this be done without  registry editing or third-party software?

![da0o7mu](https://cloud.githubusercontent.com/assets/14923168/21309682/e8a13708-c5e7-11e6-855b-e20d54c4633d.png)

**Comment by Jaex** [comment]
Uncheck this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX_z4OIye1xcU.png)

**Comment by 07416** [comment]
I have disabled the setting, it was enabled again. I use Chocolatey repository: https://chocolatey.org/packages/sharex

**Comment by Jaex** [comment]
You must have enabled it from setup, which remembers your setting and re enable it when re installing for update. I can't find way to not enable it while reinstalling. So you must uninstall and reinstall with those setup options not checked.

**Comment by sparcut** [comment]
@Jaex Why can the option not be added in the program itself? You would just need to manage the registry entry, remove/adding relative to option.

**Comment by Jaex** [comment]
Option already in the program.

**Comment by 07416** [comment]
@Jaex Your image [in the second post](https://github.com/ShareX/ShareX/issues/2162#issuecomment-268006348) appears to have been removed.

**Comment by Jaex** [comment]
Because Dropbox removed all public folder urls.

**Comment by sparcut** [comment]
For anyone finding this in the future, its right in front of you. ![Kappa](https://d3aqoihi2n8ty8.cloudfront.net/actions/kappa/light/animated/5000/1.gif)

![sharex_2017-12-20_13-36-32](https://user-images.githubusercontent.com/16233822/34188505-e0fdb3a0-e58a-11e7-8fcd-3d74e1682377.png)

**Comment by sparcut** [comment]
For anyone finding this in the future, its right in front of you. ![kappa](https://user-images.githubusercontent.com/16233822/34188584-5300b20e-e58b-11e7-82a7-3fd51b8ad4b7.png)

![sharex_2017-12-20_13-36-32](https://user-images.githubusercontent.com/16233822/34188505-e0fdb3a0-e58a-11e7-8fcd-3d74e1682377.png)
