### ISSUE TITLE
Support for Sync.com

### ISSUE THREAD

**Issue by Jonatino** [ShareX/ShareX#2163]
Switched from Dropbox to Sync.com and was wondering if we could get file/image/text uploading with this provider :D

**Comment by Jaex** [comment]
I don't think they have API.

**Comment by Jonatino** [comment]
@Jaex spoke with someone at Sync.com and they have not finiliazed their infastructure yet so there is no API for the time being. Up to you whether or not you want to keep this open for the time being. Cheers!
