### ISSUE TITLE
Dropbox Upload Fails

### ISSUE THREAD

**Issue by YisroelAdler** [ShareX/ShareX#2167]
Hi,

I tried uploading to Dropbox, and after going until 100% if gives me an error "bad request". Below is the complete error message:

`Message:`
`The remote server returned an error: (400) Bad Request.`

`Response:`
`Error in call to API function "files/upload": HTTP header "Dropbox-API-Arg": could not decode input as JSON`

`StackTrace:`
`   at System.Net.HttpWebRequest.GetResponse()`
`   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)`

----------------------
And if we're at it. Since Dropbox [announced](http://gadgets.ndtv.com/apps/news/dropbox-public-folders-will-soon-become-private-folders-for-basic-users-1638697) that they are almost immediately disabling support for the Public folder altogether, you can change the default save location away from _Public/ShareX/%y/%mo_, and also remove the: _If you are using the "Public" folder. a shareable url is already generated You don't need to check "Create shareable URL"_

**Comment by Jaex** [comment]
I'm using Dropbox too and can't reproduce your issue. Are you using shareable url?

I'm not gonna remove public folder option yet because there is 3 more months (which is not almost immediate) for it to be disabled.

**Comment by YisroelAdler** [comment]
Got the problem! The file I was trying to upload was named with [Hebrew letters](https://en.wikipedia.org/wiki/Hebrew_alphabet). Files named in English only are uploaded all okay.

Still strange, given that uploading to Dropbox in the web-interface doesn't have any problem taking files named in Hebrew.

--------------
You are right that it is still 3 months, but it is obvious that when that time will come people will regret having uploaded now things via the Public folder which links won't work.

**Comment by Jaex** [comment]
If I remove public folder support now people gonna uninstall new version just to install old version so they can continue using it.

**Comment by YisroelAdler** [comment]
I understand.

Anyhow thanks again for this useful tool!

**Comment by Jaex** [comment]
Can you paste name of your file so I can test it.

**Comment by YisroelAdler** [comment]
Anything Hebrew, tried several files. One example **Test נסיון.pdf**

**Comment by Jaex** [comment]
I can't be sure is this problem in Dropbox API v2 or in ShareX.

**Comment by YisroelAdler** [comment]
Thanks for your work! Hope they'll manage to find the problem.
