### ISSUE TITLE
Download/Upload File URL downloads and uploads all urls, no matter what.

### ISSUE THREAD

**Issue by eye-sigil** [ShareX/ShareX#2168]
I'd like for ShareX to upload file urls when it's in my clipboard but for it to shorten links if they are not; however, nothing ever gets to the shortener option because it ends up being downloaded and uploaded instead.

https://i.am-a.ninja/f0560b.png My settings, for reference.

For example, https://www.reddit.com/r/Undertale, which should be outputted to the shortener base https://awau.moe, is instead downloaded in its entirety and uploaded as https://i.am-a.ninja/9b5811.

Some sites seem to not do anything at all, and these seem to be the ones that end in `/`s.

On Windows 10, ShareX version `11.4.1`. Using `Pomf` for upload and `Polr` for shortening.

**Comment by eye-sigil** [comment]
https://i.am-a.ninja/a88ebd.png full clipboard upload settings, actually.

**Comment by Jaex** [comment]
#2127
