### ISSUE TITLE
[URLShortener] Polr API destination is out of date

### ISSUE THREAD

**Issue by moonman407** [ShareX/ShareX#2171]
The Polr v2 API operates differently than the current ShareX implementation.

Polr v1 implemented in #865 used a syntax of 
`https://example.com/api.php?`**apikey**`=1234567&`**action=shorten**`&`**url**`=https://getsharex.com`

Polr v2 that has been out for about a year uses the syntax
`https://example.com/`**api/v2/action/shorten**`?`**key**`=1234567&`**url**`=https://getsharex.com`

It took me a while to figure out why the service wasn't working.
The API is documented [here](http://docs.polr.me/en/latest/developer-guide/api/)
In the end I figured out how to use the custom uploader to get it working.
Here are my settings.

```
{
  "Name": "Polr",
  "RequestType": "POST",
  "RequestURL": "https://example.com/api/v2/action/shorten",
  "Arguments": {
    "key": "12ab34cd45ef67fe89dc01ba",
    "url": "$input$",
    "is_secret": "false"
  },
  "ResponseType": "Text"
}
```

It seems that in PolrURLShortener.cs you could just be updated line 82 to `args.Add("key", API_KEY);`
And remove line 85.
The helper text should also be updated since api.php is no longer used.

**Comment by Jaex** [comment]
https://github.com/ShareX/CustomUploaders/pull/62

**Comment by Jaex** [comment]
API shows it returns json as result how you were using Text response type in your custom uploader?

**Comment by cydrobolt** [comment]
Thanks for fixing this :+1:
