### ISSUE TITLE
when the windows taskbar is on the left side of a screen with another monitor to the left of it, the tray menu shows up on the wrong screen.

### ISSUE THREAD

**Issue by Kiyiko** [ShareX/ShareX#2173]
That's a terrible title. wow.

Expected behaviour: The tray menu should show up directly right of the cursor, like all the other applications :)

This specific multi-monitor condition seems to be the only one that produces the tray menu in an unexpected/undesirable location.

Not sure if that's something you can fix.

![jwpowk](https://cloud.githubusercontent.com/assets/4523694/21559300/3c4bb0de-ce0f-11e6-99fc-2179730ac117.jpg)

**Comment by Kiyiko** [comment]
Found another problem. The submenus get split between multi-screens too, which is undesirable
![untitled](https://cloud.githubusercontent.com/assets/4523694/21559385/0d36a32e-ce11-11e6-9455-ec733fe38d71.jpg)

**Comment by Jaex** [comment]
Both menu and sub menu opens automatically by .NET Framework and I don't actually position them myself.
