### ISSUE TITLE
Want to add a new function

### ISSUE THREAD

**Issue by google8** [ShareX/ShareX#2174]
can capture the fixed area, for example:800*800, this value needs to be customized.
Thank you.

**Comment by Jaex** [comment]
Why you can't customize it?

**Comment by google8** [comment]
![1612312038192](https://cloud.githubusercontent.com/assets/22744723/21577550/7499c1ac-cf99-11e6-9758-5890fc544539.jpg)
a function like "FastStone Capture" as the picture.

**Comment by Jaex** [comment]
You mean this?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX_6ICxkqz9sB.png)

**Comment by google8** [comment]
Oh! Yes!
This function is hidden a bit deep.Thank you!
