### ISSUE TITLE
ShareX 11.4.1 -- sorting date column on history is not correct

### ISSUE THREAD

**Issue by thezoggy** [ShareX/ShareX#2175]
win7 - sharex 11.4.1
when sorting on the date column its not sorting correctly at all.. 
for example on my screen its doing 3/12/2016 then 12/18/2016 then 11/6/2016..  which isnt correct no matter how you want to sort it..

**Comment by thezoggy** [comment]
also to note, the history shows one date format while the filename it generates uses another.. any way to change one/both to make them the same?

history: 12/28/2016
filename: 2016-12-28

**Comment by Jaex** [comment]
#1685
