### ISSUE TITLE
Can't upload to Owncloud

### ISSUE THREAD

**Issue by tsudo** [ShareX/ShareX#2176]
Uploading to my Owncloud server worked until a few weeks ago. Now I get an error of "**The underlying connection was closed: An unexpected error occurred on a send.**"

I've tried all the different options within the destination settings and tried switching between http/https (valid https cert is being used.)

Any suggestions of what else I can try?

**Comment by thejustsoul** [comment]
I have "ShareX 11.4.1" and "ownCloud 9.1.3", upload is working normal. Check ownCloud free space\limits\username\password. Try upload from web interface.

**Comment by tsudo** [comment]
I checked everything and couldn't find a fix. Then somehow with this latest version it is working again.

**Comment by Jaex** [comment]
TLS 1.2 support in latest version fixed your problem I think.
