### ISSUE TITLE
Rounded Edges...?

### ISSUE THREAD

**Issue by Appa2015** [ShareX/ShareX#2178]
Whenever I screenshot something it always has rounded corners...

![](https://cdn.discordapp.com/attachments/249637117129392129/264739391581192193/unknown.png)

I looked online and people say to go to region capture settings... except its not there anymore.

**Comment by Jaex** [comment]
In region capture: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_n1B3fdMNia.png)
