### ISSUE TITLE
Can you please port over the ability to take the cursor out of images present in Greenshot?

### ISSUE THREAD

**Issue by mauricecaaaaaben** [ShareX/ShareX#2180]

**Comment by Scrxtchy** [comment]
Is this what you are referring to?
![](https://upload.teknik.io/tLVzQ.png)

**Comment by mauricecaaaaaben** [comment]
Sorta. In greenshot the mouse is present however you can drag it out of the image and what was below it wil show

**Comment by vatterspun** [comment]
> In greenshot the mouse is present however you can drag it out of the image and what was below it wil show

That functionality should be present in ShareX.  You should be able to take a screenshot of a window that you are not currently hovering the mouse over.

**Comment by Jaex** [comment]
#1009
