### ISSUE TITLE
transfer.sh links broken

### ISSUE THREAD

**Issue by YisroelAdler** [ShareX/ShareX#2181]
I use a lot transfer.sh upload through ShareX. It worked nicely until in the middle of the day today, but then the links it gives started to come in only partially.

The sharing links used to come in a format like this https://transfer.sh/klu2x/taking-loan-from-so-called-islamic-banks.mp3 but now it comes only the first part, like this https://transfer.sh/bNYAF/ and this opens to a page which says "Not Found"

It is funny it happened today from one moment to the other. I uploaded 5 files, the first went through normally and the following 4 got these broken links:
![2017-01-03_22-45-11](https://cloud.githubusercontent.com/assets/7387839/21631189/7144cb5e-d206-11e6-9d5f-20c26aa29141.png)
 
And since then this is how the links are for any file I try.

**Comment by Jaex** [comment]
If link format changed suddenly that means they changed something in API. So it is not to do with ShareX.
