### ISSUE TITLE
Image Hosting and Hotlinking

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2183]
I am finding that many of the image hosting sites in the ShareX program either disallow hotlinking ( I post album and CD covers on forums) or they assume it's copyright and remove it.  I am sure the images are posted hundreds of places on the internet (after all that's where I get many of them) 

The question, is there a host that anyone know will allow hotlinking and doesn't mind CD cover and artwork to be displayed on forums?

**Comment by m-alice** [comment]
funkyimg can in hotlinks
vgy.me too, but upload constantly failed
