### ISSUE TITLE
Add Image Host SwiftPic

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2186]
http://www.swiftpic.org

**Comment by Jaex** [comment]
Wow they added css files end of html so web page shows up without css styling first then later styling shows up...

**Comment by Scrxtchy** [comment]
```json
{
  "Name": "swiftpic",
  "RequestType": "POST",
  "RequestURL": "http://www.swiftpic.org/ajax-upload",
  "FileFormName": "filename[]",
  "Arguments": {
    "terms": "yes"
  },
  "ResponseType": "Text",
  "URL": "$json:redirect_to$"
}
```
Response URL; http://www.swiftpic.org/view-image/1167bfd296aa490555b6256ebfaeb260.png

**Comment by MrCD1968** [comment]
what does that mean?

  ----- Original Message -----

**Comment by Jaex** [comment]
This is how web site opens:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/chrome_AOltzuKlnR.png)

Because files required to style this web site is put end of html file instead of top of it. So after all javascript stuffs etc. completed css files loaded and web site styled.
