### ISSUE TITLE
Zoom part of a screenshot

### ISSUE THREAD

**Issue by andrewpros** [ShareX/ShareX#219]
Hi.

I would like to suggest to add zooming option to part of image in image editor, it could have 2 versions, a rectangle or circle zoom.

It should work just like rectangle, ability to change size and radius for circle version.

Especially helpful when i want to upload some screen with text, but the text i kinda small.

**Comment by Jaex** [comment]
related: #2891

**Comment by JNavas2** [comment]
My own take is that the editor badly needs **Mouse Wheel Zoom**!
