### ISSUE TITLE
Tiny enhancement in menu selection

### ISSUE THREAD

**Issue by sylvain-bougnoux** [ShareX/ShareX#2190]
Due to the vertical composition of the menu, it is difficult to select the submenu item. Eg when clicking on "capture" in the middle of the button, the sub-menu appears on the far right,therefore when moving the pointer to it, one may loose the submenu panel if getting out of the primary button. It would be better if the submenu panel appear on the current pointer location.

My 2c. Thanks anyway.

**Comment by Jaex** [comment]
Showing sub menu under cursor in tray menu is not expected behavior. I never saw any software have such tray menu before.

**Comment by sylvain-bougnoux** [comment]
Maybe it requires a little more consideration, I think it is the major bottle neck  in “user experience” at least in mine. Try clicking on the left of the “capture” button, and then go straight to “region” or worst to "automatic capture". The direct way will make the menu disappear before reaching “region”. One has to follow the “capture” button and then move down to “region”. Maybe my proposal is not “expected behavior”, but the issue subsist. I think it is natural, as popup menu acts like this. IMHO vertical menus are more unexpected. **Sub menus must appear below** the current cursor position for efficiency, whether they are attached to their primary button or not. 

My countermeasure is currently to use key (arrows) or shortcut...

**Comment by Jaex** [comment]
Maybe your mouse is bad? Because it is very easy to move cursor horizontally to go to sub menu.
