### ISSUE TITLE
How to capture the current canvas

### ISSUE THREAD

**Issue by sylvain-bougnoux** [ShareX/ShareX#2191]
AFAIR in the previous version (?) it was possible to copy the current pointed canvas (a sub window). It is quite convenient to discard windows decoration. Currently when selecting "capture/region" the canvas is selected if pointed (appears dotted) but how to capture it ? ie without dragging the ROI.

Thanks again.

**Comment by Jaex** [comment]
Is this selected in your region capture?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_ueS41jyQmK.png)

**Comment by sylvain-bougnoux** [comment]
Yes it is, and was the reason. Without this option a single click capture the selected canvas.

Maybe if multi is selected, a press on return could capture the current canvas if no other regions have been created? It would avoid switching mode (easy with Q though).

Thanks for effective and prompt answer

**Comment by Jaex** [comment]
You don't need to switch mode, you can double click to select and capture that hovered area.
