### ISSUE TITLE
Dropped shadow not functionning for windows aligned with screen top border

### ISSUE THREAD

**Issue by sylvain-bougnoux** [ShareX/ShareX#2192]
It seems that the shadow is wrongly computed. It creates a black region above the capture.
It seems to work with the other borders (left,right,bottom) though.

Just to let you know as one can simply moves away the window before capture.

ShareX 11.4.1
Windows 7.

**Comment by Jaex** [comment]
Can you show ss for it. Also I'm not sure are you using image effects feature of ShareX or window capture with shadow.

**Comment by sylvain-bougnoux** [comment]
When using alt+print (default windows screen capture) the result is normal, whereas going through shareX the results is as here.
![image](https://cloud.githubusercontent.com/assets/6706662/21840573/826cb076-d7de-11e6-97bf-02885a36c6df.png).

My aero (default) config does indeed include a shadow. How do I know if win7 captures with shadows?

**Comment by Jaex** [comment]
So you enabled these?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_n3ZoDJcIPA.png)

**Comment by sylvain-bougnoux** [comment]
Yes both were checked. But without "with transparency", ie as yours, it is the same.

**Comment by Jaex** [comment]
I think you have multi monitor and one monitor is smaller than other which causing this issue. Because I don't have multi monitor I couldn't reproduce this issue before.

**Comment by sylvain-bougnoux** [comment]
Hum very relevant :-) 

I have 2 monitors, one is horizontal, one is vertical, and they are aligned on the bottom. I have the bug on the horizontal monitor where there is a "void or unmapped" area, because the vertical monitor is higher. On the vertical monitor, the shadow looks cropped but it is quite acceptable (see below). You should be able to reproduce the bug by turning one monitor 90degre (if they support it).

Thanks for having considered the issue anyway.

![image](https://cloud.githubusercontent.com/assets/6706662/21853248/9e646eee-d816-11e6-81a4-809bc42726c3.png)

**Comment by Jaex** [comment]
I can't reproduce that bug by turning monitor. It require multi monitor.

**Comment by sylvain-bougnoux** [comment]
Indeed I mean 2 monitors, one turned.
 
De : Jaex [mailto:notifications@github.com] 
Envoyé : mercredi 11 janvier 2017 16:05
À : ShareX/ShareX
Cc : sylvain-bougnoux; Author
Objet : Re: [ShareX/ShareX] Dropped shadow not functionning for windows aligned with screen top border (#2192)
 
I can't reproduce that bug by turning monitor. It require multi monitor.

**Comment by Jaex** [comment]
I have don't have multi monitor to test it. So not sure is problem fixed.
