### ISSUE TITLE
Image corruption when uploading captures of some programs with ShareX

### ISSUE THREAD

**Issue by archon810** [ShareX/ShareX#2194]
This one's really weird, but it's been happening for many months now, and I've only recently traced it down to ShareX - previously, I was blaming the programs I was taking screenshots of.

What happens is when screenshotting some programs (using good old Windows clipboard), and then using ShareX to upload the clipboard to Imgur (I have a shortcut for this - Ctrl-Shift-Alt-PgUp), the uploaded image will be corrupted in a very weird way. It'll be missing whole layers of text and other elements. However, if pasted directly into some photo editing program or on imgur.com, the image is fine.

Here's an example of what ShareX-uploaded clipboard looks like: http://i.imgur.com/oDxI58o.png.

And here's directly pasted at imgur.com: http://i.imgur.com/K0IiHrw.png.

The capture here is of the Windows Google Drive desktop app. I've also observed the same issue while capturing Total Commander and some other programs I don't recall right now. The weird part is most programs screenshot just fine, it's just only some that ShareX corrupts.

Any ideas?

**Comment by Jaex** [comment]
Can you reproduce this issue in that specific programs all the time?

If yes then can you first try disabling this setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_HnR4X78SOY.png)

then clipboard upload.

Also enable this setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_yLa5ycV9qp.png)

and try clipboard upload again.

But still I have no idea how such thing can happen to images. I'm not even sure is it happens when loading image from clipboard.

**Comment by archon810** [comment]
Yes, the situation is consistent. If it happens to a given app, it happens to it all the time.

After disabling the first setting: http://i.imgur.com/3UOvdjD.png.

After enabling the 2nd setting: http://i.imgur.com/FOyJrNg.png.

Enabling the 2nd one did it.

What does this tell us?

**Comment by Jaex** [comment]
.NET Framework have clipboard methods to get image from clipboard. But that method only supports 24 bit images which means no alpha support. So I was searched way to support 32 bit images and there was close to not exist resource about it so I was tried to write it myself (https://github.com/ShareX/ShareX/blob/master/ShareX.HelpersLib/Helpers/ClipboardHelpers.cs#L323) which was working in my tests but look like it still have problems and I have no idea how to correct it. I mean there was not a single code example in Google searches about how to get 32 bit images. The thing is 32 bit bitmap on clipboard very rarely supported and most of software just copy 24 bit bitmap + png to clipboard. So it is not common thing to find.

**Comment by archon810** [comment]
So you're saying there's a reliable method but it doesn't support transparency, or an unreliable one that does?

And by tweaking these settings, I'm now in the former mode, whereas before, I was in the default mode that does support transparency but has issues like this one?

**Comment by Jaex** [comment]
Yes you are using non transparent supported mode currently which is reliable.

**Comment by archon810** [comment]
Yeah, you're right. 

Image with alpha with these tweaks: http://i.imgur.com/5qrWHJv.png.

Image with alpha with tweaks reverted to default: http://i.imgur.com/DhvcqG8.png.

:(

So what now?

**Comment by Jaex** [comment]
I can make reliable way default option but then people gonna open issues about lack of transparent support so not sure.

**Comment by archon810** [comment]
There has to be a solution if browsers and other apps are able to paste without this bug... or file a bug somewhere against .NET if it's its fault?

**Comment by Jaex** [comment]
Very few apps support 32 bit bitmap. And some support PNG.
