### ISSUE TITLE
Shared links are not allowed for this path

### ISSUE THREAD

**Issue by Viskrul** [ShareX/ShareX#2195]
Message:
The remote server returned an error: (403) Forbidden.

Response:
{"error": "Shared links are not allowed for this path"}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

My dropbox is linked in "destinations" (correctly) and the files do appear in the folders. Maybe there is something wrong with connecting to the sever

**Comment by tekord** [comment]
+1.

**Comment by tekord** [comment]
I found the solution. My upload path was /Public/ShareX/..., I moved all files to other folder (out of Public) and it works now.

**Comment by Viskrul** [comment]
I've always used the Public/ShareX/ folder and never had the issue before. Can you confirm this as well? That might indicate it's on Dropbox's end.

**Comment by tekord** [comment]
@Viskrul This issue started for me today. I guess it is on dropbox's end. They do something with Public folder, maybe disable sharing for it, don't know (i got email about it).

**Comment by Jaex** [comment]
I must change default path to "ShareX" then.
