### ISSUE TITLE
The special characters does not appear after using an Arabic letter.

### ISSUE THREAD

**Issue by Abu3safeer** [ShareX/ShareX#2197]
Hello, i am facing a problem with Arabic language while using in in typing.
the main issue that it does not support RightToLeft direction, and the special characters does not show after writing an Arabic letter.
![example](http://i.imgur.com/r4kwvrI.png)

as you can see i can write all special characters while using English only,
but writing an Arabic letter *"Which is ه in the example"* all the special characters **disappeared completely**.

***EDIT:*** what i mean by RightToLeft direction is this feature in text editiors : 
![text direction](https://cdn4.iconfinder.com/data/icons/materia-design-vol-2/24/034_098_format_text_direction_left-128.png)

**Comment by Jaex** [comment]
I can write special characters after `ه` character?

**Comment by Abu3safeer** [comment]
This is a video how I see it : 
[Click Here to see the Video on Oploaded.co](https://openload.co/f/8gXnGDaRn54/)

**Comment by Jaex** [comment]
Maybe your arabic font causing it?

**Comment by Abu3safeer** [comment]
LOL, you are right, i have changed the font to Arial and it worked just find, looks like not all fonts are supported, Droid Sans fonts don't support special characters with Arabic letters.
too bad, I really like that font in Arabic, beside it is free, most of Arabic fonts are paid.

anyway thanks, you can mark this as solved, and mark your question as the answer, you may.

**Comment by Abu3safeer** [comment]
I will leave it Open if you wanted to leave a comment.
