### ISSUE TITLE
How to capture the result after using annotation tools

### ISSUE THREAD

**Issue by laurentkempe** [ShareX/ShareX#2198]
First thanks for such a great tool!

I take a region screenshot then I add annotations to it, but then I want to get the result with annotations and I don't know how to do it! I searched for hotkey, click on the mouse...

Thanks for your support

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_8jCaO5OOPk.png)

Click region tool and drag rectangle to capture where you want.

**Comment by laurentkempe** [comment]
@Jaex I knew it was easy but I couldn't get it! Thanks a lot!
