### ISSUE TITLE
[Feature request] Watermark images automatically with transparent image

### ISSUE THREAD

**Issue by Abu3safeer** [ShareX/ShareX#2199]
Hello everyone, I want to Watermark all the images with Transparent image.
This feature is already built-in, but it only add a small text to the right-bottom cornet, which is easy to remove by others.

if not, is it possible to make it as a feature in the image editor? 
like adding new transparency button:
![transparency ration](http://i.imgur.com/EtsABf3.png)

Thanks for your work 👍.

**Comment by Jaex** [comment]
I don't understand why you watermark with image editor instead of image effects:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_Nwg4jLiPPL.png)

**Comment by Abu3safeer** [comment]
WOW, I am sorry for that, 
I have used this feature before, but looks like I was not using it in the right way, 
because I thought that it is only for text watermarks.
sorry for this stupid question, my fault.
