### ISSUE TITLE
gif compression request

### ISSUE THREAD

**Issue by hikapoo** [ShareX/ShareX#2200]
would it be possible to compress gifs directly in shareX? I like to share files directly from shareX but the files are always so big so it takes forever to load them in e.g discord. I also use a 1440p monitor which makes the gifs huge, being able to change the resolution would be nice too.

**Comment by Jaex** [comment]
This is why everybody using video recording instead of gif recording. Which makes extremely small files compared to gif and be able to playback in browsers.

**Comment by vatterspun** [comment]
> would it be possible to compress gifs directly in shareX?

You can use **After Capture Tasks - Perform Actions** and setup the **Task Settings - Actions** menu to include the open source compression tool FileOptimizer (http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer)

![wckw1v6](https://cloud.githubusercontent.com/assets/1289134/22316276/c24b3a4c-e331-11e6-8394-b14b0960b17c.png)

Jaex is right, however.  Despite some serious improvements with this format, the h.265 video recording tools are way (literally 20 years) ahead of .GIF compression.

If you need to compress something losslessly, I recommend PNGOptimizer (https://github.com/hadrien-psydk/pngoptimizer), which will convert your GIF into animated PNG format, which has better compression but isn't broadly supported.

**Comment by Demoniaque** [comment]
Apparently, ffmpeg has gif compression features
https://superuser.com/a/556031
https://superuser.com/questions/1049606/reduce-generated-gif-size-using-ffmpeg
http://cassidy.codes/blog/2017/04/25/ffmpeg-frames-to-gif-optimization/

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/55050269-627f6f00-5082-11e9-94e9-faff6337f999.png)

my setting, size reduce about 10-30%
