### ISSUE TITLE
System.IO.IOException - Not enough disk space (not true)

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#2202]
I'm casting my iPad Air 2 with reflector and filming it with ShareX. I have enough disk space (15 + GB)
![sharex_2017-01-13_15-52-58](https://cloud.githubusercontent.com/assets/18115558/21934123/878bf87a-d9a8-11e6-9c58-7b34d932a10a.png)

![sharex_2017-01-13_15-52-55](https://cloud.githubusercontent.com/assets/18115558/21934133/8d69e37e-d9a8-11e6-9981-e64f13863c9f.png)

**Comment by YasseenDeHerdt** [comment]
not sure if 2 pictures are directly related, but happened after each other

**Comment by Jaex** [comment]
Both image tells not enough space on hard drive when two of them different apps. So it is your pc.
