### ISSUE TITLE
JPEG Colour Quality

### ISSUE THREAD

**Issue by GenesisAria** [ShareX/ShareX#2205]
Quite frankly, it's terrible.  While even if you set the jpeg compression quality to 100, you do get a nice clean image without noise artifacts, but there is some serious chroma issues.

Here are screenshot comparisons:
[http://imgur.com/a/t0X6d](http://imgur.com/a/t0X6d)
[http://screenshotcomparison.com/comparison/197352](http://screenshotcomparison.com/comparison/197352)

**Comment by Jaex** [comment]
ShareX using .NET Framework to encode image as JPEG.
