### ISSUE TITLE
#LO-PRIO: Multiple places to add ffmpeg arguments

### ISSUE THREAD

**Issue by stdedos** [ShareX/ShareX#2207]
Some arguments of ffmpeg should be at the beggining, like `-thread_queue_size` for example.

I know I can tick "Use custom commands" and be on my way, but then no control is updating the command line.

Something like

**Additional ffmpeg commands:**

ffmpeg-specific|capture-specific
------------ | -------------
-thread_queue_size 512|-force_key_frames expr:gte(t,n_forced*1)

**Comment by Jaex** [comment]
And what you suggest?

**Comment by stdedos** [comment]
![image](https://cloud.githubusercontent.com/assets/133706/21999325/36242c36-dc42-11e6-8349-39e2da33326e.png)

Something like this (i.e. split the box)

Or create a new one, underneath

EDIT: (of course, the "Use custom commands" would be unchecked)

**Comment by Jaex** [comment]
The thing is there is more edge cases where code should be inserted in another position, then I will require to have 3. box then 4. box so it goes on. So if you want full control, custom commands is way to go.

**Comment by stdedos** [comment]
Well, I just guess that a lot of people had trouble with -thread_queue_size (Google at least things to seem so).

Your call, of course :)
I just like to drop hints if alright

**Comment by Jaex** [comment]
What thread_queue_size do?

**Comment by stdedos** [comment]
Saves you from these kind of errors:
![image](https://cloud.githubusercontent.com/assets/133706/22000393/864e570e-dc47-11e6-8852-ed88361245eb.png)
