### ISSUE TITLE
how to remove filename.mp4 stamp on captured video

### ISSUE THREAD

**Issue by stuartWagenius** [ShareX/ShareX#2208]
Is there a way to remove the .mp4 that appears at the beginning of a screen capture video? I figured out how to remove the filename using "Name pattern for capture of clipboad upload," but I can't remove the extension.

**Comment by Jaex** [comment]
Are you uploading video with FTP?

**Comment by stuartWagenius** [comment]
I uploaded files to Dropbox. I now see that the appearance of the filename depends on my media player or browser. Thanks for the great software!
