### ISSUE TITLE
Mouse cursor in wrong position when recording high DPI screen

### ISSUE THREAD

**Issue by Daniel15** [ShareX/ShareX#2212]
When making a screen recording on a high DPI screen, the cursor appears in the wrong location. It appears to be offset by 2x from its real location - For example, if my cursor is at 1000x1000, it appears at 500x500 in the recording.

**Comment by Jaex** [comment]
#1329

**Comment by Daniel15** [comment]
Thanks @Jaex! Sorry I missed that issue, as I was only searching through open issues.
