### ISSUE TITLE
ffmpeg fails to download

### ISSUE THREAD

**Issue by xshotD** [ShareX/ShareX#2213]
Hello - 

I am a ShareX user who thought "Hmm... let's try this screen recorder feature." It asks me to download ffmpeg, so I click "Yes" obviously.
It says "Underlying connection was closed" when I try. It pops up the selector anyway, and I encounter 2 windows of "FFmpeg error" when I close out the selector.

**Comment by Jaex** [comment]
I can download FFmpeg without problem currently. Maybe their server was down temporary.

**Comment by xshotD** [comment]
![](https://file.house/1O9C.png)

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_8hhASjv7Xq.png)

**Comment by xshotD** [comment]
Huh, weird. Got any suggestions?

**Comment by Jaex** [comment]
Download it from https://ffmpeg.zeranoe.com/builds/ and copy it to "Documents\ShareX\Tools" folder.

**Comment by xshotD** [comment]
Alright, will try.

**Comment by xshotD** [comment]
Manually downloading and putting the .exe into the folder worked, thank you!

**Comment by IwishIcanFLighT** [comment]
I had the same issue as well. I work in a coworking office. Could it be related to firewall security?
What's the download url of the ffmpeg file?

**Comment by Jaex** [comment]
No #3189

**Comment by IwishIcanFLighT** [comment]
Thanks !

**Comment by jimbo1qaz** [comment]
The crash only occurs when I begin recording without music from foobar2000 (no audio output streams are open?).

I'm guessing ffmpeg blocks waiting for audio input, and queues up encoded video frames while waiting for audio to be encoded (and both to be written to .mp4). Eventually this queue fills (around 4 seconds in, for me).

Beginning music during the recording prevents the crash from occurring. Terminating music midway through doesn't seem to crash.

**Comment by Jaex** [comment]
@jimbo1qaz try re installing video/audio recording device, latest version of it supposed to fix that issue.

**Comment by jimbo1qaz** [comment]
oops wrong issue

**Comment by hermann-san** [comment]
In my case the download proceed to about 99% and then that same error message came. I do believe that this is because I use the portable edition of ShareX and I've put it into a subfolder of the program files folder. When I copy the ffmpg.exe into the tools folder, then windows explorer asks for admin permissions.  When I copy and past ffmpg.exe manually then I simply confirm the permission pop-up, but I assume that ShareX doesn't expect a admin permission prompt after the automatic download. Hence it throughs the error message.

**Comment by Osmiogrzesznik** [comment]
![image](https://user-images.githubusercontent.com/28631235/66352957-c7ccea80-e958-11e9-8485-296ebbe1dcb0.png)
 same here , fresh install

**Comment by putsan** [comment]
That happens again! I can't download FFmpeg for a few weeks..(
![image](https://user-images.githubusercontent.com/11944886/95580648-5b3f6c80-0a40-11eb-809e-af6ff490eda7.png)

> Download it from https://ffmpeg.zeranoe.com/builds/ and copy "ffmpeg.exe" to "Documents\ShareX\Tools" folder.

zeranoe.com site did not work in now in Ukraine or for everyone don't work too...

I was visiting different sites, but I do not find there .exe file. Can you help me or send me that file?? Or how I can build .exe from the source if you know what I need to do??

**Comment by L1Q** [comment]
zeranoe website is down for good, see their [tweet](https://twitter.com/Zeranoe/status/1300596971934224385)
> http://ffmpeg.zeranoe.com will close on Sep 18, 2020, and all builds will be removed.

We have the files hosted in another repo [ShareX/FFmpeg](https://github.com/ShareX/FFmpeg/releases)
New versions of ShareX should now download from new place.

**Comment by Tamren** [comment]
I tried downloading ffmpeg though sharex portable 13.2.1 and nothing happens. It just says "waiting". I'll try to get it from the repo.

**Comment by putsan** [comment]
> I tried downloading FFmpeg though ShareX portable 13.2.1 and nothing happens. It just says "waiting". I'll try to get it from the repo.

Yes I have the same problem..

**Comment by L1Q** [comment]
the app looks for ffmpeg on disk F and you are putting it on disk C

**Comment by a-raccoon** [comment]
Still a problem in 2020.  At the very minimum, the program should provide the instructions given by @Jaex above and provide a button for "Open Folder" to take you there.

> Download it from https://github.com/ShareX/FFmpeg/releases and copy "ffmpeg.exe" to "Documents\ShareX\Tools" folder.

> `[Visit Website]` `[Open Folder]`

**Comment by Andrewss32** [comment]
**A solution for PORTABLE version.**
Problem:  no "ffmpeg.exe" file in ShareX folder (it's false).

**If you have MOVED ShareX from one disk (HDD/SSD) to another one**
(Letter in path to ShareX folder has been changed),
just open "ShareX" subfolder, "ApplicationConfig.json" file
and replace the old disk letter
to the new one.

**Comment by a-raccoon** [comment]
> **A solution for PORTABLE version.** Problem: no "ffmpeg.exe" file in ShareX folder (it's false).
> 
> **If you have MOVED ShareX from one disk (HDD/SSD) to another one** (Letter in path to ShareX folder has been changed), just open "ShareX" subfolder, "ApplicationConfig.json" file and replace the old disk letter to the new one.

Not sure what you mean. PORTABLE "installs" of programs have NO conf paths or drive letters. They can be run from anywhere, all over the place, in any unpredictable location from any unpredictable mount, day by day, hour by hour. There is no editing. Only relative paths ever.

**Comment by Andrewss32** [comment]
> PORTABLE "installs" of programs have NO conf paths or drive letters.

But ShareX portable HAVE it (open its' root directory, then "ShareX" subdirectory & you'll fild ApplicationConfig.json file).

I have used MANY portable apps which HAVE configs (Photoshop, for example). If you did not, please do not mislead.
