### ISSUE TITLE
[Request] Custom hotkeys

### ISSUE THREAD

**Issue by diksm8** [ShareX/ShareX#2214]
I already love this program and I would really appreciate if you added the ability to add custom hotkeys.
I.e launch programs with custom args

**Comment by Jaex** [comment]
What launching programs to do with ShareX??

**Comment by diksm8** [comment]
If we are going with that attitude then what does a DNS changer have to do with a screenshot uploader?
A hotkey to send a get request to the last deletion URL doesn't seem like that bad of an idea to me.

**Comment by Jaex** [comment]
For example both Imgur (default image destination) and Pastebin (default text destination) is banned in my country and only accessible when you change DNS. So it helps my country users to quickly configure DNS to allow uploading. So without that tool "uploader" part not even works...
