### ISSUE TITLE
.NET Core future

### ISSUE THREAD

**Issue by RheaAyase** [ShareX/ShareX#2217]
Hello,

as we all should know by now .NET Framework is dropped and the future is with netcore. I've done a quick search through the issues and haven't found one so here goes...

.NET Core is an open source replacement of .NET Framework and with upcoming `2.0` version _(early summer?)_ should be rather good and it should contain big portion of the necessary stuff. I know that you mentioned "windows native libraries" in other issues related to linux or mac, so I went ahead and generated [this portability analysis report[1]](http://rhea-ayase.eu/files/ShareX-PortabilityAnalysis.html). I would like to ask, did you guys check with the problematic libraries what are their plans, whether they consider to replace some of the missing system libraries with something else, etc..?

I'll also link to [this article[2]](https://developers.redhat.com/blog/2016/12/08/observations-porting-from-net-framework-to-net-core) which may be of some help, but then there are so many good resources already out there :)

Cheers!
Radka

&nbsp;

[1]: ShareX .NET Core Portability Analysis Report: [http://rhea-ayase.eu/files/ShareX-PortabilityAnalysis.html](http://rhea-ayase.eu/files/ShareX-PortabilityAnalysis.html)
[2]: Todd Mancini (RedHat) - Observations on Porting from .NET Framework to .NET Core: [https://developers.redhat.com/blog/2016/12/08/observations-porting-from-net-framework-to-net-core](https://developers.redhat.com/blog/2016/12/08/observations-porting-from-net-framework-to-net-core)

**Comment by Jaex** [comment]
https://developers.redhat.com/blog/2016/12/08/observations-porting-from-net-framework-to-net-core/

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/chrome_dS02ZGo8qy.png)

**Comment by Jaex** [comment]
#498

**Comment by RheaAyase** [comment]
#498 is **TWO YEARS OLD**

This is about netcore, not about "linux/mac port" and is well on topic, please don't just dismiss it like that.

_And don't you think that I've seen the article when I worked on it with the author?_

**Comment by Jaex** [comment]
.NET core talked about in #498 in Oct 17, 2016 which is not **TWO YEARS OLD**.

This is about porting ShareX to Linux, hence it is duplicate.

**Comment by RheaAyase** [comment]
Porting to Linux is not porting to netcore. Framework is gonna die, this has to happen sooner or later for windows as well, be it 5 years from now, it still will happen one day, and i thought that it would be a good idea to have a tracking issue open, the same approach we take at work with long-term problems. I'm sorry I took your time.

**Comment by RheaAyase** [comment]
_gg `Jaex changed the title from Mac Port to Mac/Linux Port 21 minutes ago`_

**Comment by Jaex** [comment]
What is gg about it? That post had 22 mention of "Linux" and people who just check title when searching issues in GitHub could think it is not about Linux too. So I changed title to reflect that...

**Comment by RheaAyase** [comment]
And I was not searching for linux port, because that's not what this is about. I searched for "core" and it came up with nothing related, that issue was not in the list. That's all.

`netcore != linux != mac`

**Comment by Jaex** [comment]
I didn't told you were searching for linux port.

Currently only reason someone will port their desktop app to netcore is for multi platform support. So yeah it is all about linux port in your case.

Also you keep saying ` .NET Framework is dropped` & `Framework is gonna die` but you never giving any proofs about it to prove your statement. In current state even porting console apps to netcore is too difficult. When I'm porting my console app to netcore I needed to remove countless basic stuffs which not exists in netcore to make it work. So even if netcore gonna catch .NET framework one day, it gonna take so long time. And like I told before it is not certain it will catch up.

**Comment by RheaAyase** [comment]
netcore 1.1 added over 1300 apis, you probably used 1.0 - and 2.0 is going to improve a lot more again, hence why i'm talking about 2.0 there. Of course it's hard, and as i said, maybe in 5 years we would be able to get there - not now. Doesn't hurt to start looking around. Either way your choice, good bye.

**Comment by QuAzI** [comment]
Possible workaround: change most of parts to .NET Standard 2.0, change other parts to .NET Core, use Avalonia UI ( https://github.com/AvaloniaUI/Avalonia ) for cross-platform UI development

**Comment by jamesqo** [comment]
In addition to Avalonia there's also the Eto.Forms framework: https://github.com/picoe/Eto

**Comment by crsncc** [comment]
Casually looking at this in 2020

**Comment by RheaAyase** [comment]
Casually reading the dumb discussion about how netcore == linux. So now in 2020 and with .NET 5 on the horizon, do you still think it's equal? It's not, .NET5 will incorporate all of .NET Framework (like I promised Framework is going to die.) While many of these APIs will not be available on Linux.

> Also you keep saying `.NET Framework is dropped` & `Framework is gonna die` but you never giving any proofs about it to prove your statement. In current state even porting console apps to netcore is too difficult. When I'm porting my console app to netcore I needed to remove countless basic stuffs which not exists in netcore to make it compileable. So even if netcore gonna catch .NET framework one day, it gonna take so long time. And like I told before it is not certain it will catch up.

_Told you so @Jaex._

**Comment by Beyley** [comment]
I believe that this should definitely be re-opened and used as a long term tracking ticket for a possible port, recently I was able to port a 156k line project over to .NET 5 from .NET framework 4.0, it uses Windows Forms exclusively and many native Windows DLL calls, it only took me and my team 2 weeks of work, and we had never even used .NET 5 before

The line counts are very comparable to ShareX, which has 112k lines of code. If I still used windows, I'd begin a port myself, but currently I use Linux and don't have a powerful enough CPU for a Windows VM so I'm unable to work on a port as i don't want to dual boot. Might help out once I upgrade my PC though

As a side note, .NET 5 this would also close #5635, and possibly more issues that i haven't been able to dig through yet

**Comment by RheaAyase** [comment]
(I feel like another year later I need to add a plus to the five, with .NET 6 coming up shortly :D)

**Comment by Droppers** [comment]
Paint.net is now also using .NET 5.0, which is also a winforms application. I think this is a good example of a successful port to .NET Core.

.NET Core also brings a lot of performance optimizations.
