### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by EnderDave** [ShareX/ShareX#2218]
Trying to upload anything when:

Message:
The remote server returned an error: (500) Internal Server Error.

Response:
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by GarrusValkyrin** [comment]
I can confirm I am getting this error as well

**Comment by Kodaigan** [comment]
Confirmation. Here too.

**Comment by Ecxdirerr** [comment]
Confirm here 2

**Comment by Fevci1501** [comment]
Confirm !

**Comment by kocko94** [comment]
yup

**Comment by Fevci1501** [comment]
Sharex Error.

I add png image


23.01.2017 00:39 tarihinde Konstantin Vankov yazdı:

**Comment by Fevci1501** [comment]
Sharex Error

I add png image


23.01.2017 00:39 tarihinde Konstantin Vankov yazdı:

**Comment by Scrxtchy** [comment]
But ShareX hosts no servers
Where are you lot uploading to?

**Comment by EnderDave** [comment]
wherever it goes. i've personally been going to puush

**Comment by Scrxtchy** [comment]
Puush confirmed a downtime earlier today
https://twitter.com/puushme/status/823335731774881792

**Comment by Jaex** [comment]
Everyone here had issue uploading to Puush I think and it is resolved [in server side now](https://twitter.com/puushme/status/823335731774881792).
