### ISSUE TITLE
Make more options for uploading specific file types.

### ISSUE THREAD

**Issue by yomamaisonfier** [ShareX/ShareX#2219]
The ability to set separate uploaders for text vs images and whatnot is fine, but then it gets too broad when it gets to "file". This means anything that isn't a "text" or "image" file right? Well, I don't want my gifs to upload to the same place as my images, I'd rather use gfycat to save bandwidth for others. I don't want .mp3s (or any audio file) to upload to the same location as my .mp4s (or any video file). I think allowing us to choose for each file type will broaden the usability of the app quite a bit.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX.vshost_qMxhiJFOqU.png)
