### ISSUE TITLE
Question: Sort history descending

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#2220]
How can I sort the history descending (last picture at the top)? I have searched in the options, and I know this used to be possible, but I can't find it back anymore.

![sharex_2017-01-23_12-24-55](https://cloud.githubusercontent.com/assets/18115558/22202163/333918b8-e167-11e6-8ccb-62a5ebd49723.png)

**Comment by Jaex** [comment]
This? ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX.vshost_yPS51uf6Fm.png)

**Comment by YasseenDeHerdt** [comment]
Yes, that's it. Thank you! @Jaex
