### ISSUE TITLE
Customized Naming After Capture {Question]

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2223]
Is there a way to give a customized file name to a capture?

**Comment by Jaex** [comment]
After capture window have file name field.

**Comment by vatterspun** [comment]
> Is there a way to give a customized file name to a capture?

Modify this:
![2017-01-25 18_32_20-sharex - task settings](https://cloud.githubusercontent.com/assets/1289134/22315496/a9e9fb00-e32c-11e6-8162-a4c69a287820.png)

**Comment by MrCD1968** [comment]
I don't see where I choose to name an image. For example if my capture was a picture of an apple how would I name it apple.
  ----- Original Message -----

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_N8ByR5ejOz.png)

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_6XalD64HfS.png)
