### ISSUE TITLE
Do not treat GIFs as images

### ISSUE THREAD

**Issue by Llorx** [ShareX/ShareX#2224]
Simply, I want images to be copied to the clipboard and not uploaded, and gifs to be uploaded and get the URL.

Right now is impossible to achieve such task, as "Upload image to host" will upload all images and gifs.

Yeah, I know that gifs are images, but, you know, with images I mean static images.

I know that I can filter the uploads, but what I want is a filter to block the upload instead of uploading it to a different host.

**Comment by Scrxtchy** [comment]
#2219

**Comment by vatterspun** [comment]
> Simply, I want images to be copied to the clipboard and not uploaded, and gifs to be uploaded and get the URL.

Wait, so the steps here are:

1. Drag and drop an image onto ShareX
2. If GIF then upload, if other copy to clipboard?

Possible workaround: Under **Task Settings**, setup watch folders with a **.gif** filter.

**Comment by Llorx** [comment]
Thanx for your interest :P

I'm creating a screen gif via a serie of hotkeys I registered, then I have this configuration:
![http://i.imgur.com/K99oaA4.png](http://i.imgur.com/K99oaA4.png)

And this:
![http://i.imgur.com/h6mJX9M.png](http://i.imgur.com/h6mJX9M.png)

So the problem here is that is uploaded all images: "static" and "gif" ones. I would like to have a "Upload GIF to host" (or "Upload screen capture to host") and a different "Upload image to host" (Talking about images).

Maybe one workaround can be add to the uploader filters an option to not upload instead of just change host, so we can filter gif extention and block it.

Don't thought about your workaround. Going to:
- After capture, save image to file
- Watch the folder and filter by extension

By the way, a direct way of doing this would be awesome, so I don't have to save all my captures.

**Comment by Scrxtchy** [comment]
Another option is to use a custom workflow for recording, as workflows can have their own unique configurations
this does mean you have to use the workflow menu to use your tools, however shortcut keys can still be rebound if you choose to use them

**Comment by Llorx** [comment]
Oh, forgot about that. That's perfect as I always use hotkeys for my captures.

**Comment by vatterspun** [comment]
> ... the watcher thing. There's a problem. I also make mp4 videos so I'm watching for mp4 videos too:

You should probably submit that as a separate case.  That seems like a bug.

**Comment by Llorx** [comment]
Going to do so.

**Comment by vatterspun** [comment]
> EDIT: Works like a charm. Thank you!

Close the case?
