### ISSUE TITLE
Request: Firefox Addon

### ISSUE THREAD

**Issue by Stele77** [ShareX/ShareX#2225]
Hi,
All i am missing from an otherwise nearly perfect piece of software would be a browser extension for Firefox. 
Even with Chrome's dominance in the market, Firefox is still the 2. largest, and even on par in parts of Europe. 
Thanks for your work and an exceptional piece of software!

**Comment by Jaex** [comment]
I don't know how to make Firefox addon. It mainly require to be web developer to make it.

**Comment by Jaex** [comment]
Look like now Firefox moving to Chrome web extensions system and planning to deprecate their own addon system. In that old addon system doing native messaging was so complicated I couldn't figure out it. But now I can just copy paste our Chrome extension which is few lines of codes. And with few text changes it can work in Firefox! So I'm currently working on it.

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX_Firefox
