### ISSUE TITLE
System.Configuration.ConfigurationErrorsException

### ISSUE THREAD

**Issue by ShinobuDonut** [ShareX/ShareX#2226]
Hi ! When I'm launching ShareX, everything seems to be okay but when I do a capture, this message pop : 

System.Configuration.ConfigurationErrorsException: Échec de l'initialisation du système de configuration ---> System.Configuration.ConfigurationErrorsException: Section de configuration non reconnue startup. (C:\Program Files\ShareX\ShareX.exe.Config line 3)
   à System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   à System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   à System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Configuration.ConfigurationManager.PrepareConfigSystem()
   à System.Configuration.ConfigurationManager.GetSection(String sectionName)
   à System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   à System.Net.Configuration.WebRequestModulesSectionInternal.GetSection()
   à System.Net.WebRequest.get_PrefixList()
   à System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   à System.Windows.Forms.PictureBox.LoadAsync()
   à ShareX.HelpersLib.MyPictureBox.LoadImageAsync(String path)
   à ShareX.HelpersLib.MyPictureBox.LoadImageFromFileAsync(String filePath)
   à ShareX.MainForm.UpdateContextMenu()
   à System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   à System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   à System.Windows.Forms.ListView.WndProc(Message& m)
   à ShareX.HelpersLib.MyListView.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.4.1 (Release)

What can I do ?

**Comment by Jaex** [comment]
I'm not sure why you receive such weird error. Nobody reported similar problem before. And error happens inside .NET framework function so it is not looks to do with ShareX.

"C:\Program Files\ShareX\ShareX.exe.Config line 3"

Can you check this file is something wrong in line 3?

**Comment by ShinobuDonut** [comment]
It was caused by a .netframework stuff apparently
