### ISSUE TITLE
Paste does not work in all application

### ISSUE THREAD

**Issue by DeployWindowsInfo** [ShareX/ShareX#2227]
After taking a screenshot I edit the picture in the built-in editor and automatically put this in clipboard memory. But when I try to paste this into some applications it does not work, nothing gets paste. My last application with this issues are Windows Live Writer on Windows 10 1607.

**Comment by Jaex** [comment]
It is problem in application which can't paste image. But you can try alternative copy way from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_kA8QCIXFkY.png)

**Comment by DeployWindowsInfo** [comment]
Thanks, great works perfect!
