### ISSUE TITLE
Menus should not close automatically when moving mouse pointer off

### ISSUE THREAD

**Issue by Keith94** [ShareX/ShareX#2230]
## Steps to reproduce
1. In ShareX window, click on "Capture" to open the menu
2. Move the mouse pointer downwards onto "Upload"

## Expected results
The active menu should automatically switch from "Capture" to "Upload" or whichever one is hovered on

## Actual results
The "Capture" menu automatically closes when moving mouse pointer down

---
I recorded a screencast of the issue here: https://a.pomf.cat/bmvtqa.mp4

**Comment by Keith94** [comment]
@Jaex It's a duplicate of which issue? A bug or intended behavior?

**Comment by Jaex** [comment]
#2190
