### ISSUE TITLE
Question: Open image in editor when clicking the thumb on the right after screenshot

### ISSUE THREAD

**Issue by Luc45** [ShareX/ShareX#2232]
When I click the thumb that shows up on the bottom right of the screen after taking a SS with Sharex, it opens with Windows Image Preview, and I would like to configure it to open with Fireworks:

![2017-01-27_14-08-51](https://cloud.githubusercontent.com/assets/9341686/22377826/6fe90896-e49a-11e6-9f53-217754cc458c.jpg)

I know I can change the default software to view .jpg files on Windows, but I like Windows Image Preview to open .jpg on my computer, I just would like to open the editor when clicking the thumb after Sharex's SS.

How can I do that?

![sharex_2017-01-27_14-11-36](https://cloud.githubusercontent.com/assets/9341686/22377870/9bbca1b2-e49a-11e6-9b99-adf081431b6c.jpg)

I already added Fireworks to open .jpg on Task Config -> Actions but it didn't work.

**Comment by vatterspun** [comment]
> I already added Fireworks to open .jpg on Task Config -> Actions but it didn't work.

I know this isn't the focus of your question, but on the **Action** menu part, I'm confused why Fireworks isn't launching.  I've tested a number of editors without issue, and even tested a new one today for Photoscape:

![sharex_2017-01-27_14-45-44](https://cloud.githubusercontent.com/assets/1289134/22387069/8c6e8518-e49f-11e6-9fe3-fb04b81c8f72.png)

**Comment by AlainCh2** [comment]
I have the same Issue with PicPick Editor.

Actions doesnt seems to works.

( enabled in aftercapture as well )

![image](https://user-images.githubusercontent.com/41082160/148661611-1a529f78-a041-4308-8b2f-62b2706e8e6a.png)
