### ISSUE TITLE
SUGGESTION: option to Capture web URL (if) active window is a browser like chrome

### ISSUE THREAD

**Issue by AnacondaPython** [ShareX/ShareX#2233]
I use shareX when doing research based documents, because you can't specify on some web pages a specific place to bookmark or annotate. 

Normally I'll take an image screenshot, annotate that webpage, and then copypaste the URL web page link for reference (where I screenshotted)

Example: 

"
http://i.imgur.com/rwDXpie.png 
from http://stackoverflow.com/questions/214741/what-is-a-stackoverflowerror
"

Is it possible to have a feature built into shareX for this?

1. If ShareX recognizes active window as chrome, capture URL

2. Copy the URL to clipboard and then the image uploaded URL* 
OR 2. Copy the URL to clipboard & append the image URL link output same time

I am not sure how something like this would be implemented (e.g. how to capture the URL), but this would be a really amazing feature for people who do a lot of technical documentation / write out extensive reports

*(I run ditto so I can grab the previous clipboard contents)

**Comment by Jaex** [comment]
How to get URL from active browser tab?

**Comment by AnacondaPython** [comment]
The only way I can see it is a shareX chrome plugin that integrates with the sharex application. 

The javascript plugin would basically look at the active windows using http://stackoverflow.com/questions/29720294/active-window-detection 

and then output that information to a json file (or even as a local cookie?), to which shareX pulls the latest information off there when it detects the PN (program name) and then outputs the URL if its chrome.

There must be some chrome API's you could work with though

Same goes for firefox, internet explorer, etc

That's all I can think of

Sorry I am not an expert here >_>

**Comment by Jaex** [comment]
That will be very ugly method and unreliable one. Not to mention it will be very complicated to implement.
