### ISSUE TITLE
Pleas help!

### ISSUE THREAD

**Issue by MUSICOELECTRO** [ShareX/ShareX#2235]
I was changing the folder and delete som files and noy many errors is recurrent

Please see photos and let me now how to fix
uninstalling an reinstalling is not an option

![3](https://cloud.githubusercontent.com/assets/22566357/22388541/ff57b28e-e4ae-11e6-833f-bda6d0ce8daf.jpg)
![2](https://cloud.githubusercontent.com/assets/22566357/22388542/ff5c3ade-e4ae-11e6-968e-8ef7d86f057b.jpg)
![1](https://cloud.githubusercontent.com/assets/22566357/22388543/ff5fbcc2-e4ae-11e6-87ad-2c8370a149e0.jpg)

on,.,.

**Comment by Jaex** [comment]
You changed ShareX personal folder to "Program Files\ShareX". But ShareX can't create any file inside program files without admin permission. So personal folder must be outside program files. Default path is "Documents\ShareX". So change your personal path from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_hS5saczMlK.png)

**Comment by MUSICOELECTRO** [comment]
Amazing!
this aspect solved,

and this?
![4](https://cloud.githubusercontent.com/assets/22566357/22389762/4d11c450-e4b5-11e6-8d41-684ef48b025b.jpg)

**Comment by Jaex** [comment]
Did you removed that audio device? Reinstall it from:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_976DLPIX6P.png)

**Comment by MUSICOELECTRO** [comment]
No
The same audio system and software
