### ISSUE TITLE
Where to get and place the ShareX.UploadersLib file?

### ISSUE THREAD

**Issue by grub-basket** [ShareX/ShareX#2238]
When I was updating SX (ShareX), the ShareX.UploadersLib file couldn't be overwritten for some reason, and since retrying wouldn't work, I hit ignore, which obviously broke it, and now it won't run.

It appears to be a folder in your code, so I'm not sure what to do. 

![image](https://cloud.githubusercontent.com/assets/12993901/22394370/3d2d7920-e4d4-11e6-9a52-387449bbd8a4.png)

Is there a way I could reinstall ShareX without losing all of my current data/preferences and then add it into the new one (assuming it's not as easy as moving and replacing some files and folders)?

**Comment by Jaex** [comment]
Just re run ShareX installer.
