### ISSUE TITLE
Add new text editor for image effects.

### ISSUE THREAD

**Issue by WebFreak001** [ShareX/ShareX#224]
The Text object in Image effects is really basic. I would like to see a GUI editor for it where you can change the text alignment, color for each character by selecting it and changing the color, adding multiple text shadows, gradient editor for the background and foreground, connected padding like in visual studio where you can change the whole value or every other value, enable anti aliasing (font smoothing), multiple corner radius, etc. That as a combined value in a class using a custom control/form would be really nice. You could see better whats going on and it would remove every propertie of the image effect object from Text until Gradient Type

**Comment by padukakerol** [comment]
Hi. Sorry.
I hope the ShareX allow us to change font color.
