### ISSUE TITLE
Question: Is it possible to configure to drag & drop image from webpage in .jpg format?

### ISSUE THREAD

**Issue by lyflyflxf** [ShareX/ShareX#2240]
I'm new to Drag and Drop upload in Upload.  Every time I drag & drop a .jpg image from firefox, it was automatically converted to .bmp.  I quickly went through all options inside ShareX and found nothing related.

As my most suitable destinations don't convert to .jpg, it would be more convenient to have jpg files uploaded at first place.

Thank you.

**Comment by dannoe** [comment]
Are you using Firefox? 
If so, see here: https://bugzilla.mozilla.org/show_bug.cgi?id=1191462

**Comment by Jaex** [comment]
Both drag n drop and clipboard operations using bitmap in Windows. But very rarely software can add png/jpg to clipboard but it is not likely and not supported by majority of software.

**Comment by lyflyflxf** [comment]
@dannoe This is possibly the cause.  I tried to drag jpg from FirefoxThank you.

@Jaex 
Windows clipboard seems to leave the image as it be.

I've been using the copy image option in right click menu of Firefox and "upload from clipboard" of ShareX for some time.  This combination works perfect for me, uploading the exact image from the webpage.  I just tested with IE 11 and Chrome 55, both latest, and they work well too.

I'm using Windows 8.1 x64 with update and latest hotfixes.  Firefox x86 51.0.1

But Drag & Drop images from IE fail completely, see This:[http://i66.tinypic.com/34s179t.jpg](url)
every image dragged from Chrome turns into the link of the image and is uploaded to text uploader consequently.

So can I conclude that the Drag and Drop feature in windows are primarily for local files?

**Comment by vatterspun** [comment]
@lyflyflxf
> Every time I drag & drop a .jpg image from firefox, it was automatically converted to .bmp. I quickly went through all options inside ShareX and found nothing related.

**Workaround**: Drag an image from Firefox to a temporary Windows explorer location (e.g. the desktop).  Drag from this location to ShareX.
