### ISSUE TITLE
Crash Error 

### ISSUE THREAD

**Issue by Joschiii** [ShareX/ShareX#2241]
After the update, ShareX can not start anymore:

System.BadImageFormatException: Die Datei oder Assembly "ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
Dateiname: "ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
   bei ShareX.Program.LoadProgramSettings()
   bei ShareX.Program.Run()
   bei ShareX.Program.Main(String[] args)

WRN: Protokollierung der Assemblybindung ist AUS.
Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.

ShareX 11.5 (Release)

**Comment by Jaex** [comment]
Every single time this error happen people tells this happened after update but later they admitting ShareX started after update properly but after next ShareX open (mainly on Windows startup) this error happened.

**Comment by Jaex** [comment]
#1615
