### ISSUE TITLE
Action on clicking preview toast

### ISSUE THREAD

**Issue by moniuch** [ShareX/ShareX#2242]
Is it possible to attach or configure the action to be triggered when clicking on the preview toast?
Sometimes I want to ccopy the image, sometimes I want to reveal the file in explorer, sometimes someone could want something different... Could we perhaps have the toaster extended with an action dropdown (with the last used action pre-selected)?

**Comment by Scrxtchy** [comment]
It is possible to configure, check the advanced window for the task settings
![](https://upload.teknik.io/zjyCl.png)
