### ISSUE TITLE
On monitor number 2 blackscreen when try catch

### ISSUE THREAD

**Issue by godlatro** [ShareX/ShareX#2247]
I have 2 monitors 1920x1080, windows 10 pro 64, version 11.5 and 11.4.x
On primary monitor - all ok.
On secondary monitor - black screen only.
in GreenShot same problem
in faststonecapture - white screen

When ANY monitor in PRIMARY mode - its work, and SECONDARY monitor have black Screen, but windows frame and crosshair working

Windows Included PrntScr to buffer work perfectly. In the past I never take this problem

**Comment by lithium720** [comment]
I don't seem to have this problem as demonstrated by the screenshot below:

**Comment by godlatro** [comment]
maybe this problem in my windows

**Comment by Jaex** [comment]
Because I don't have multi monitor it is not possible for me to reproduce this issue. But there is a lot of multi monitor users and look like very few of them got this issue so not sure what is different.

**Comment by lithium720** [comment]
Do you have a GPU?

**Comment by DeathStryke** [comment]
I have a Gtx 770 with the same issue
I don't know if these settings will help at all
![settings_2017-02-08_15-15-24](https://cloud.githubusercontent.com/assets/4499235/22736871/7e4c1560-ee11-11e6-9da8-0646a9ff311e.png)
![settings_2017-02-08_15-15-26](https://cloud.githubusercontent.com/assets/4499235/22736872/7e4d0b28-ee11-11e6-812d-d636b1efc4e7.png)
![nvidia_control_panel_2017-02-08_15-14-56](https://cloud.githubusercontent.com/assets/4499235/22736875/80b9183e-ee11-11e6-9c91-58c8d158f85b.png)
![nvidia_control_panel_2017-02-08_15-15-09](https://cloud.githubusercontent.com/assets/4499235/22736876/80bd4eea-ee11-11e6-8f53-72093408f350.png)

**Comment by lithium720** [comment]
My settings look exactly the same. All I can suggest is make sure your GPU driver is up to date as well as Windows.

**Comment by godlatro** [comment]
In the past i always use FastStone Capture - everytime it will work perfectly. But now i have trouble in any caoture programs except default windows. I think problem in some programs.

**Comment by godlatro** [comment]
Today I will try to fix this issue, and after I report result

**Comment by godlatro** [comment]
All my attempts were unsuccessful. I disabled services, turnoff some programs and drivers, but result the same.
I DONT try delete some programs for image view, or video coders.
Now I just Reinstall my old Windows 10 for new Core version. I install all needed programs, include ShareX
Now shareX works fine as expected.
Thanks for add PANEL WITH BUTTONS for ShareX - in compare with FastStone Capture it necessity and very helpful unlike last version.

**Comment by Jaex** [comment]
You mean actions toolbar?
