### ISSUE TITLE
Clipboard URL upload

### ISSUE THREAD

**Issue by horusra** [ShareX/ShareX#2248]
Is there any way to have the "Clipboard URL upload" function just work without popping up an input box? just upload the clipboard without confirmation box?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_EFG7XzRQ9k.png)

Then configure clipboard upload hotkey like <kbd>Ctrl + Page up</kbd> which i'm using.

**Comment by horusra** [comment]
Id swear that's what I did. but I guess checking that mark in the specific task setting for the hotkey didn't do it, so I changed it in the general task settings.
