### ISSUE TITLE
Help To Fix This.

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2249]
How do I stop this window from coming up after capture? [img]https://lh3.googleusercontent.com/-QNsJFmWrgQs/WI6YDQJ5bnI/AAAAAAAAANM/0VI_2HRSMtg/s0/111.JPG[/img]

I want it to default back to the links for forums etc after capture.  I still cannot see how to capture, give a customized file name, and then upload. Doesn't seem to work for me as I am sure I am doing something wrong. I use ShareX in a limited capacity but enjoy it nonetheless.

**Comment by Jaex** [comment]
Uncheck this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_Ki19lRgxau.png)

**Comment by vatterspun** [comment]
> I want it to default back to the links for forums etc after capture. I still cannot see how to capture, give a customized file name, and then upload.

Custom file naming is under **Task Settings - File naming**.  Then just modify the after capture tasks to upload.

You can also also edit the popup menu (which I quite like) to give some finer controls if for example you want occasionally capture and NOT upload.  Open Application settings -> General -> Edit quick task menu.
