### ISSUE TITLE
Capture Active Window doesn't work properly

### ISSUE THREAD

**Issue by silviulaurentiu** [ShareX/ShareX#2251]
I used hotkey Alt+W to capture Active Window and Alt+X to Capture Region
I captured first attached window with Alt+W and Alt+X. When I used Alt+W, the image shows like second attached image (not all buttons of window are present in the image). When I use Alt+X, everything work well. After I captured the window with Alt+X, then Alt+W work well. If the window is minimized and then maximized and I used again Alt+W, is the same problem like in the second attachement. 
![alt x](https://cloud.githubusercontent.com/assets/14875058/22431565/a2e9b90c-e71a-11e6-946d-7051b1562cad.png)
![alt w](https://cloud.githubusercontent.com/assets/14875058/22431578/b0092b54-e71a-11e6-840e-9f94a6888e6c.png)
The windows comes from Orcad Capture 16.5
Thanks a lot!

**Comment by vatterspun** [comment]
That is a really interesting bug.

**Comment by Jaex** [comment]
I suspect it is bug in ShareX. ShareX captures what Windows supplies.

**Comment by silviulaurentiu** [comment]
Thank you for your info :-)
