### ISSUE TITLE
Possible to add up1 back as uploader?

### ISSUE THREAD

**Issue by ElecM8** [ShareX/ShareX#2255]
Hey. First of all, great work making ShareX such an amazing tool!

I was wondering if it was possible to add up1 as a file uploader again. As far as I know, this is the only encrypted file host ShareX offers and I've been stuck using the 11.2.1 because of that

I know [someone](https://github.com/ShareX/ShareX/issues/1922) asked the same question and I thought it'd be added back in this version but apparently, it's not. Would it be possible to add it again?
A current valid host for up1 would be https://share.riseup.net, using the following API key: 59Mnk5nY6eCn4bi9GvfOXhMH54E7Bh6EMJXtyJfs

Thanks in advance for your answers

**Comment by Jaex** [comment]
Main reason why I didn't add it back because I don't want external library dependency (Lib/Security.Cryptography.dll) as possible for uploaders. Because I know you guys wouldn't like this answer therefore I was not responded before.
