### ISSUE TITLE
Unable to drag pictures onto ShareX

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#2257]
If I drag a PNG or JPEG from Windows Explorer onto ShareX:
- It works on 1 PC
- It doesn't work on 1 other PC

Why ? Both are version 11.5

![sharex_2017-02-01_13-59-04](https://cloud.githubusercontent.com/assets/18115558/22507733/33912ad6-e887-11e6-87df-f0c1a48efe37.png)

**Comment by Jaex** [comment]
Your ShareX could be run as admin which happens after installer open ShareX.

**Comment by YasseenDeHerdt** [comment]
Running as admin or non-admin didn't change.

**Comment by Jaex** [comment]
Did you tried restarting pc?

**Comment by vatterspun** [comment]
> It works on 1 PC
> It doesn't work on 1 other PC

What are the differences between the PCs?  Is one of them 64 bit?  Is one of them a different version of Windows?  Do they both have all their updates applied?  Have you had drag-and-drop issues with other programs?

**Comment by YasseenDeHerdt** [comment]
@Jaex  it happened right after the update to 11.5
@vatterspun the PC where it works is Windows 7 64-bit, the PC where it doesn't work is Windows 10 64-bit, I don't think has anything to do with it though. Both have all their updates applied. What I can do it drag-and-drop from ShareX to Windows Explorer but not from Windows Explorer to ShareX. I have no issues with drag-and-drop in other programs. I was thinking if it can have anything to do with particular settings, such as upload, etc?

**Comment by vatterspun** [comment]
Thanks for the additional info.  My Win7x64 with all the updates where drag-and-drop is working fine so I'm not sure what's causing your issue.

**Comment by YasseenDeHerdt** [comment]
I can also drag-and-drop from the main screen to the 'Combine Pictures' screen, but not from Explorer to ShareX.

**Comment by YasseenDeHerdt** [comment]
I have downgraded to ShareX 11.4.1 and it works again, I'll keep on this version. 

Thanks
