### ISSUE TITLE
Newest 10 screenshots being exported when "export history" is not selected

### ISSUE THREAD

**Issue by eqagunn** [ShareX/ShareX#2259]
I have introduced ShareX to a friend and exported my settings for him.
Only "export settings" was selected but he received 10 of my latest screenshots in his history.
Those that were saved locally on my PC were not available for him, but he could open those that were uploaded.
This could have been an inconvenience for me if screenshots contained some info which I didn't want to share with him, but in this case it wasn't.
However, other people could experience different outcome.

**Comment by Jaex** [comment]
This is how export works:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/chrome_J4oXJQ3m9J.png)

But you have these exported:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/ShareX_ysEc1hv6fT.png)

which is recent tasks and not history items.

So last 10 task remembers from your main window and saves them in application settings file.

**Comment by eqagunn** [comment]
Thanks you for the nice explanation, I understand.
However, I think no one will assume this works like that while making an export.
I recommend excluding recent tasks from export for the sake of people's privacy.

**Comment by Jaex** [comment]
It is actually just zipping files so excluding them can be too much work.

**Comment by eqagunn** [comment]
Storing recent tasks in a separate file would do the trick.
Though only you know how much work that would require.
Let's leave it at this. Cheers!
