### ISSUE TITLE
Is there a way to change the file type to JPG after i capture a screenshot?

### ISSUE THREAD

**Issue by JunkyardCat** [ShareX/ShareX#2260]
I know it saves itself in cache as PNG then converts it to JPEG after downloaded since when i press paste it pastes the PNG version of the screenshot.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/ShareX_TlPwNwWtrH.jpg)

**Comment by JunkyardCat** [comment]
i already know that. it saves as JPEG but what i want is the minute i capture it pressing alt+printscreen and i immediately click paste it pastes as PNG

heres the steps 

press alt+printscreen
immediately go to a place where you can paste things like a folder or word then click ctrl+V

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/ShareX_Wfi6fZlTlc.png)
