### ISSUE TITLE
Is there a way to capture the screenshot as JPG isntead of JPG?

### ISSUE THREAD

**Issue by JunkyardCat** [ShareX/ShareX#2262]
This is kind of like a special kind of question so please see below on how to replicate it. FYI I already know how to save as JPG adn its working

heres the steps

press alt+printscreen to capture a screenshot
immediately go to a place where you can paste things like open a empty microsoft word then click ctrl+V. youll notice its a png file

**Comment by Jaex** [comment]
#2260
