### ISSUE TITLE
Disparity in webm recorded sound volume and actual application volume

### ISSUE THREAD

**Issue by d3athrow** [ShareX/ShareX#2263]
i recorded something and the volume that it recorded at was much lower for some reason and i can't find any setting that would have affected this, here's the webm for example:  http://ss13.moe/uploads/2017-02-02_15-48-25.webm
Now here's the actual audio recorded through audacity using my speakers loopback, note the drastic volume difference.
http://ss13.moe/uploads/medicine.ogg

**Comment by vatterspun** [comment]
Just to be clear: are you using Vorbis audio?  At what quality level?

**Comment by d3athrow** [comment]
Vorbis quality 5.

**Comment by vatterspun** [comment]
I ran a test on mic recordings using both h.264 (MP4) and WEBM and they both seemed to record at the same levels.  I don't know how to test program application recording.  Maybe post your Audacity settings?
