### ISSUE TITLE
[Question] Video - low compression, high-compression video sequence

### ISSUE THREAD

**Issue by vatterspun** [ShareX/ShareX#2265]
NOTE: this is more focused on low-end or older machines, and probably low priority

---

Right now in ShareX there is functionality for recording high quality MP4 files, but with the caveat "for realtime encoding the preset must be as fast as possible" (as noted in the tooltip that shows up if you hover over the preset).

![2017-02-03 23_00_57-sharex - screen recording options](https://cloud.githubusercontent.com/assets/1289134/22615863/b1d5e6fa-ea64-11e6-84d5-46e394fea3cf.png)

I'm interested in doing an initial recording that keeps a lot of detail and doesn't overwhelm the processor, then following up with a slower, processor-intensive compression.  Something that takes advantage of the best compression FFMPEG has to offer.  While there is functionality for doing post-video recording compression ("Run CLI afterwards"), I'm not sure what to use.  The CLI references "x264.exe" but that's not actually present in the program.

Any recommendations?

**Comment by McoreD** [comment]
Just wanted to say that x264.exe was meant to be an example. You are free to use any CLI there.

**Comment by vatterspun** [comment]
> x264.exe was meant to be an example. You are free to use any CLI there.

I suspected as much.  Any CLI programs and settings details suggestions are welcome.

**Comment by vatterspun** [comment]
This has been open for long enough.  I'll go ahead and close this just to get it out of the queue but I welcome any additional feedback.
