### ISSUE TITLE
Tray menu item to drag last capture file

### ISSUE THREAD

**Issue by oxysoft** [ShareX/ShareX#2267]
This is a feature idea. I would like a menu item in the ShareX tray menu that allows you to click and drag it, and it would act as if you were dragging the last captured file so that you can drop it into Discord or Skype for example.

What do you think?

**Comment by vatterspun** [comment]
Sorry I'm not sure what you're suggesting here.  You can currently drag something from the list of captured items on the main window into any other application.  You want something for the last captured item to turn into a drag-and-drop element?

**Comment by joye-ramone** [comment]
Is it possible/difficult to add drag&drop feature to History.../Image History... screens?
I can create a separate issue if needed.

**Comment by vatterspun** [comment]
> Is it possible and how difficult to add drag&drop feature to History.../Image History... screens?

I'm assuming you mean the file that was created in the history and not the listed URL.  Why do you need drag and drop for that?

> I can create a separate issue if needed.

I'd probably do that given that I still have no idea what oxysoft is asking for.

**Comment by oxysoft** [comment]
Sorry, I forgot to reply. The right click menu on the ShareX tray icon, I'd find it useful if there was a menu item that linked to the file of the last capture and I could drag the menu item itself, and it'd act as if I was dragging the file itself which I could drop into Discord/Skype/Etc.

I know you can press "Copy" in the After Capture window and paste it into Skype or Discord for the same effect, but some times I only realize after that I wanted to share the file itself instead of a link. It'd save me from having to open my screenshot folder to then drag it.

There are cases where "Copy" would not work either, for example: if you wanted to upload the file to some particular website, you could just right click the tray icon and drag the menu item instead of again, opening the screenshot directory.

**Comment by joye-ramone** [comment]
> Why do you need drag and drop for that?

I often use this Image History window to review existing images and send it via Skype, emails etc. I know that I can copy URL (if it exists), but more often I would like to send file itself. As of for now I should open folder first and then drag&drop file from explorer. It would be really nice to allow drag directly from this History screen. Do it make sense?

**Comment by Jaex** [comment]
@oxysoft you know you can drag file from main window right?

**Comment by oxysoft** [comment]
true, but I rarely open the ShareX window itself. I think it feels awkward having to open the window to drag it then remembering to close it every time.

**Comment by Jaex** [comment]
ShareX already have recent items in tray menu and you want me to add additional recent item to parent menu, how it makes sense?

**Comment by oxysoft** [comment]
actually that makes me think, what if the functionality I want was added to the "recent link" items?

Currently we have
* Left click to copy link
* Right click to open link

I suggest dragging the items to act as dragging the file on the disk itself

**Comment by vatterspun** [comment]
> It would be really nice to allow drag directly from this History screen. Do it make sense?

Yes, now delete that and create a separate issue as this is hijacking the original conversation with oxysoft.  After which I'll delete this post as well.

**Comment by Jaex** [comment]
Even if I add drag n drop support for it, you can't drag files to Discord because Discord not supports copy dragging and only allows move dragging. And ShareX must do copy dragging.

**Comment by oxysoft** [comment]
is it not possible to do move dragging in c#?

**Comment by vatterspun** [comment]
>  The right click menu on the ShareX tray icon, I'd find it useful if there was a menu item that linked to the file of the last capture and I could drag the menu item itself, and it'd act as if I was dragging the file itself which I could drop into Discord/Skype/Etc.

Can you point to a program that works similarly or mock something up?  I've never seen a drag-and-drop component coming out of a context menu.  This sounds very odd.

As a possible workaround, you might use Ditto (or other clipboard tools) as it has a recent copy history that has thumbnails and can paste images.  Should work fine with Skype.

**Comment by Jaex** [comment]
When people drag file they mainly want it to be copied not cut and moved. So this is why ShareX do copy drag and not move drag. Accepting both copy and move drag is one word code but Discord still not do it, dunno why.
