### ISSUE TITLE
Sli.mg service offline (probably permanently)

### ISSUE THREAD

**Issue by zeffy** [ShareX/ShareX#2268]
Sli.mg has been down for about three weeks, and there has been zero communication with the maintainer(s) for months. It is very likely that it won't be coming back.

See: https://voat.co/v/Slimg/1570256 / https://voat.co/v/Conspiracy/1570823

Regardless of the actual reasons for it going down, it would probably be a good idea to remove it from ShareX.

**Comment by Jaex** [comment]
Currently http://sli.mg opens.

**Comment by zeffy** [comment]
Right. I should have mentioned that, sorry. Anyway, thanks for taking care of this so quickly!
