### ISSUE TITLE
Bug with Image editor stuck minimized in the taskbar.

### ISSUE THREAD

**Issue by mikhoul** [ShareX/ShareX#2269]
This bug is there since few version, so it's not a "new" bug ...

OS = Windows 7/64
ScreenX = Latest version

When I  take a screenshot, the editor open with the screenshoot inside ---> http://i.imgur.com/5STXPXA.png

If I minimize the windows in the taskbar ----> http://i.imgur.com/69xeoAj.png

Lot of times it for a strange reason when I click on the minimized window in the taskbar the window wont restore, the window stay minimized.  

The only way to restore the Window when it happen is to  hover on the Taskbar and choose restore ----> http://i.imgur.com/OpFFpoV.png

It don't happen every time but it happen lot of times to be very annoying sadly 😠 

To help you to identify what is causing this random bug to happen I used "PROCMON" to see what happen when the Window is stuck in the Taskbar and when I try to restore it.

Here's a Screenshot of PROCMON: http://i.imgur.com/6u8vQ0n.png  The Query to open the editor windows fail with "NAME NOT FOUND"

Let me know if I can do something else to help you to fix this annoying bug.

Regards :octocat:

**Comment by Jaex** [comment]
I can't reproduce your minimize restore issue. Are you sure you are using ShareX and not ScreenX?

**Comment by mikhoul** [comment]
@Jaex   Look at the process name... 

> Here's a Screenshot of PROCMON: http://i.imgur.com/6u8vQ0n.png The Query to open the editor windows fail with "NAME NOT FOUND"

**Comment by Jaex** [comment]
It was joke.

**Comment by vatterspun** [comment]
> Lot of times it for a strange reason when I click on the minimized window in the taskbar the window wont restore, the window stay minimized.

Sometimes when I have multiple Greenshot windows open or there's some kind of prompt, I have to either (A) close the latest Greenshot image edit window or (B) find the prompt window and click "OK" or whatever.  Could this be your issue?

**Comment by mikhoul** [comment]
@Jaex @vatterspun   Yes you're right it's part of the issue too, maybe with this information it will help to track the issue.

Regards :octocat:
