### ISSUE TITLE
Capture active window cannot perform file-changing actions

### ISSUE THREAD

**Issue by guijan** [ShareX/ShareX#2270]
If I create an action which takes the %input file and transforms it into %output
![sharex_2017-02-06_15-07-49](https://cloud.githubusercontent.com/assets/25590950/22657892/31fe130e-ec7f-11e6-91df-e11140a73ad3.png)
 and then use it in conjunction with the "capture active window" option, sharex will either not perform the action or fail at performing the action then output the original %input file.
When I use my mozjpeg action with "capture active window" I get a .bmp file instead of a .jpg, and the same action with the same everything else works just fine with a "capture entire screen" sdcreenshot and results in the .jpg I wanted. I also tested it with a ffmpeg that does the same or similar (convert a bitmap into a jpeg, and other formats) and obtained the same result, %output goes nowhere and i get %input.

**Comment by vatterspun** [comment]
Have you tested this argument line independent of ShareX Actions menu?  I just don't want Jaex to get into the position of troubleshooting a program that's not part of ShareX.

Also: 
* Could you paste the full contents of your "Arguments" line?  Where did you get that specific set from? Is that recommended?
* Have you messed at all with FileOptimizer?  It includes MozJpeg.

**Comment by vatterspun** [comment]
Have you tested this argument line independent of ShareX Actions menu?  I just don't want Jaex to get into the position of troubleshooting a program that's not part of ShareX.

Also: 
* Could you paste the full contents of your "Arguments" line?  Where did you get that specific set from? Is that recommended?
* Have you messed at all with FileOptimizer?  It includes MozJpeg.

**Comment by guijan** [comment]
- Have you tested this argument line independent of ShareX Actions menu?
Yes, i also use the exact same argument line to take regular screenshots (instead of region or window ones) and it works just fine, it only won't work with region and window screenshots and that program is not the only one. 
- Could you paste the full contents of your "Arguments" line?
It's in the picture of my first post. 
- Where did you get that specific set from?
From the help page of mozjpeg itself, shown in this picture:
![image](https://cloud.githubusercontent.com/assets/25590950/22678671/f3f2f2a0-ece2-11e6-9113-da5967fd781c.png)
- Is that recommended?
Yes, it's proper usage of what the help page itself says.
- Have you messed at all with FileOptimizer? It includes MozJpeg.
If I tell sharex to use mozjpeg from a premade command instead of making FileOptimizer do it, more of the work is automated. And no, I haven't used fileoptimizer.

**Comment by guijan** [comment]
I have also noticed another thing, if I look at the debug log it doesn't even mention if ShareX tried to execute my action when taking a window/region screenshot. Here's a piece of the log from one attempt at a window screenshot. Keep in mind I edited the log and changed my real username for "<CENSOREDUSERNAME>" 
[ShareX-Log-2017-02.txt](https://github.com/ShareX/ShareX/files/756655/ShareX-Log-2017-02.txt)
I don't know what other kind of information to provide, but if you need it i'm here.

**Comment by Jaex** [comment]
Is it possible that your specific hotkey don't have "Perform actions" checked?

**Comment by guijan** [comment]
It does have "perform actions checked
![sem titulo](https://cloud.githubusercontent.com/assets/25590950/22679260/e9adcb3a-ece7-11e6-8e6e-00de1e712e23.png)

**Comment by Jaex** [comment]
I can't even find CLI download link for mozjpeg in here https://github.com/mozilla/mozjpeg so can't test it.

**Comment by guijan** [comment]
Mozilla only provides the source of mozjpeg, and if you want to use it you have to compile from source.
I'm sure there's some licensing issue with distributing this, but here are the binaries I compiled. 
https://files.catbox.moe/eue8fx.7z

**Comment by Jaex** [comment]
I can't trust random executables.

**Comment by guijan** [comment]
I seem to have narrowed down the issue better, the extension filter was filtering my .jpg files. I thought it would actually filter anything _but_ them. I found another issue however, without the filter I get both the .bmp and .jpeg files (as it should be), but I can't use the filter to filter out the .bmp files.

**Comment by Jaex** [comment]
I tried this now:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/ShareX.vshost_xqZSBGagTw.png)

and it only opens Paint when it is bmp file.

**Comment by vatterspun** [comment]
> I can't trust random executables.

If in the future you want to mess with it, the program is distributed in (as mentioned above) FileOptimizer  http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer as _mozjpegtran.exe_
