### ISSUE TITLE
Yandex-Disk Support

### ISSUE THREAD

**Issue by SkyLostTR** [ShareX/ShareX#2272]
Hello,
If there'll be Yandex-Disk support on ShareX. It'll be great. Thanks for developing this aplication for us, good works.

**Comment by Jaex** [comment]
#320

**Comment by SkyLostTR** [comment]
Please do not close it immediately without waiting for an answer, Yes I already saw these Issue Submissions, but there's no Yandex-Disk support on any part of ShareX. (As much as I seen)

Sorry if I disturbed you and sorry for re-opening this issue, hope the ShareX community gets bigger. It's a great solution for automation purposes.

Btw are you from Turkey?
