### ISSUE TITLE
Second monitor shows up as blank

### ISSUE THREAD

**Issue by DeathStryke** [ShareX/ShareX#2275]
I just reinstalled Windows 10 and for some reason I can't use Sharex to capture the whole screen. I always can  only capture the "Main" display but not the other one it just appears as blank.

I tried using different ports/cables it's the same. I don't know what's wrong normal print screen works just fine.

I tried different versions/reset the settings too still the same.

Thanks,
![2017-02-08_14-36-43](https://cloud.githubusercontent.com/assets/4499235/22735767/3af989b4-ee0c-11e6-82d9-7adb1f9436c6.png)

**Comment by Jaex** [comment]
#2247
