### ISSUE TITLE
Newer Google Photos albums are difficult to identify

### ISSUE THREAD

**Issue by NTWarrior** [ShareX/ShareX#2276]
I wanted to put my screenshots in a Google Photos album simply named "Screenshots" just for them, but for albums created more recently the Name in the Destination Settings album list is the same as the ID (with the exception of InstantUpload) and the descriptions are blank, regardless of what name and description I actually entered through the site or app. Those IDs don't match the URL of the album so it is trial and error to create the right one.

This is from my primary Google account where there is a mix of albums with and without unique names (I didn't add that description myself):

![sharex_2017-02-08_20-37-09](https://cloud.githubusercontent.com/assets/854211/22756508/3e74436c-ee3f-11e6-8ece-d50d375d6f8a.png)

And this is from a Google account I've just started uploading photos to (the albums here are actually all the same albums in the primary account because I shared them from the primary account to this one):

![sharex_2017-02-08_20-22-04](https://cloud.githubusercontent.com/assets/854211/22756814/50adee06-ee40-11e6-83a0-59da73762935.png)

**Comment by andrei1015** [comment]
Ah yes, thank you. Came here looking for a problem of not finding the album, but it was there. Hmn..

**Comment by Jaex** [comment]
fixed #2411
