### ISSUE TITLE
Opening saved image with ShareX automatically uploads to imgur

### ISSUE THREAD

**Issue by somenode** [ShareX/ShareX#2279]
"After Capture Tasks" are limited to "Copy image to clipboard" and "Save image to file" but, when I open a saved image with ShareX, the image is automatically uploaded to imgur. 

Is there another setting to prevent this from happening?

**Comment by Jaex** [comment]
Opening ShareX with file will upload that file. You can disable uploading in whole app but if you don't want it to upload why you open ShareX with file?

**Comment by somenode** [comment]
I was opening saved images on the Desktop. The steps were right-click "someimage.png" on Desktop > "Open With" > ShareX. 

By doing that, the image was uploaded to imgur which was totally unexpected. I wasn't intending on uploading the image.

**Comment by Jaex** [comment]
You can disable upload app wide like this:

![](http://i.imgur.com/jKplq4V.png)

**Comment by gavluk** [comment]
Now Upload->Disable upload not allowed. 
What is the way to configure what to do on "Open with..." ?
Upload is really unexpected behavior as for me. Image annotate or view is much more appropriate, isn't?

**Comment by kilo8ytes** [comment]
To open an image in the Image Editor you need to open ShareX.exe with the [-ImageEditor argument](https://getsharex.com/docs/command-line-arguments), followed by the path to the image. 

For example: 
[path/to/]ShareX.exe -ImageEditor [path/to/]image.png

On Windows 10, to have a "Send To Image Editor" option in the context menu when you right-click a file, create a registry entry with the code below. 

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\Send To Image Editor]

[HKEY_CLASSES_ROOT\*\shell\Send To Image Editor\command]
@="\"C:\\Program Files\\ShareX\\ShareX.exe\" -ImageEditor \"%1\""
```
Adjust the path to ShareX.exe if needed. 

Save the code as a .reg file, and double click it to add the registry entry.

**Comment by Dover8** [comment]
I know this is marked as closed, but I agree that the "Open with -> ShareX" menu setting it to auto upload is a very strange behaviour.

I would expect it to open the Annotation Editor.
