### ISSUE TITLE
%t and %pn in sub folder pattern for screenshot folder not working

### ISSUE THREAD

**Issue by Jutosa** [ShareX/ShareX#228]
ShareX 9.2.1
Windows 8.1 64bit

The placeholder %t (Title of active windows) and %pn (Process name of active window) don't appear to be working for me.

Maybe I'm using it wrong.

When I use the following pattern %y-%mo\%t\

I get folder structure that looks like this ..\2014-08\%t\filename.ext

The placeholder is not being replaced by the actual value.

**Comment by Jaex** [comment]
Added it now:

![](https://jaex.getsharex.com/2021/12/ShareX_gE7bsfLJCV.png)
