### ISSUE TITLE
Capture active monitor doesn't work anymore with DX11 game on windowed mode

### ISSUE THREAD

**Issue by Xebtria** [ShareX/ShareX#2280]
I have two monitors. I use capture active window to make screenshots of the game I'm playing.
It used to work, but for some reason it stopped working recently (can't pinpoint it exactly when). It just doesn't do anything anymore.

it still works on the second monitor where I have my browser, It even works when I move my browser over my game to the first monitor. and It also works when I use capture region on the game itself, however this then "freezes" the game a few milliseconds until I click the mouse to actually do the capture, which is not good/nice, thus I usually want to use the capture active monitor.

It also doesn't work when I use capture active window (same behaviour with the browser, it works with browser, but not with the game, and this on both monitors also).

it works with capture entire screen, it then makes one picture with both monitors (which includes the game).

I also tried to change the shortcut and resetting the shortcut settings, but this doesn't change anything.
again it used to work, this apparently was introduced with one of the later updates....

**Comment by Jaex** [comment]
Did you tried install old ShareX to test is it latest version causing it.

**Comment by Xebtria** [comment]
I did now. and now I am even more confused, because even with version 10.0.0 it doesn't work but it definitely worked in the past :o 

:(

**Comment by Jaex** [comment]
This happens really so much that people always blame that latest update broken something but it is not the case most of the time :/

**Comment by Xebtria** [comment]
Ok it gets even weirder. I now thought ok what the heck, the game has an option to switch between DX11 and DX9 mode. let's try DX9 instead.
.,.. and it worked with DX9.
then I changed it back to DX11 and ...

... it now works there (again) also. 

I sometimes don't understand it.

anyways, I guess the issue is now no longer an issue. I think.... 

Thanks for the quick replies though :)

**Comment by Xebtria** [comment]
Hi,

basically immediately after I closed this issue 2 weeks ago, it was again not working. but that time switching the dx modes of the game did not change anything.

however, right now, merely by accident, I can perfectly say when it is working and when it is not working. 

I tried as well back with version 10.0.0, and it behaves the same there. I still don't know what is different to earlier, because as I originally wrote, I am sure it worked at some point, but well. at least it is reproducible now.
I also checked with the different DX modes and it behaves the same in all versions, so this doesn't make any difference either.

so I have two monitors. when I make the browser (or desktop or whatever is on the first monitor) the main by clicking on it and then press the hotkey for active monitor, it makes the screen from that monitor. when I then hover over to my game on the second monitor (which is in windowed-fullscreen mode, which is why I can just do that) **without clicking on it** (so technically the browser is still the focus), it makes the screen from the game. but as soon as I click in the game again and therefore make it the focus, it doesn't make the screenshot anymore.

and as usual, when I make capture region, it still works even with the game as focus (but it freezes it until I made or cancelled the capture, but that is expected with capture region)

I hope you can figure something out with this information...
-xeb

**Comment by Jaex** [comment]
Both hotkey system and screen capture system using Windows API so I don't think I can do anything about it in both case.

**Comment by Xebtria** [comment]
I might have found the problem. I'm not 100% sure as the behaviour was sometimes a bit ... fishy and not as expected at all, but I'm giving my hopes to that...

I'm specifically running the game as administrator. ShareX however, I was not. so I changed it to start ShareX as admin as well and _it looks like_ this solved the problem. 

could it be a possibility to change ShareX so it runs as administrator by default?

I hope it is okay if I keep this one open as I want to observe it for another while to see if it really works now? :)
