### ISSUE TITLE
Low FPS when recording screen via Webm

### ISSUE THREAD

**Issue by RyanSacha** [ShareX/ShareX#2284]
I have set the FPS limit to 60 and also the maximum bitrate to 100Mb but still I get very low fps videos (10-15fps).

Here's a screenshot of my settings?

https://s3.amazonaws.com/snaps-bucket/2017/02/XJa0NEI/2017-02-13_15-44-51.png

Is it possible to tweak this to make it spit out high fps (60fps) screen recordings?

I really don't wanna use mp4 because it's not as sharp/clean looking as webm videos.

**Comment by Jaex** [comment]
Real time webm encoding is very costly and not suggested.
