### ISSUE TITLE
Potential user data leak when using Dropbox as an image uploader with default settings?

### ISSUE THREAD

**Issue by gyunter** [ShareX/ShareX#2285]
### Steps to reproduce
1.  Link your Dropbox to ShareX as a File Uploader
2.  Leave upload path default (Destination Settings > Dropbox : Upload path). Should be something like the path below:
`Public/Screenshots/%y-%mo`
3. Leave the name pattern for capture or clipboard upload as default (Task Settings > Upload >  File naming)

### Behaviour
All files that are placed in Public folder of Dropbox automatically become shareable by URL. ShareX returns a URL of the following pattern: 
`https://dl.dropboxusercontent.com/u/1455235/ShareX/2016-02/chrome_2016-01-21_12-41-02.png`
Even though we are unable to go to the folder itself, it is still _possible_ to iterate over all timestamps, common applications and paths (which are by default YYYY-DD, YYYY-MM-DD_HH_MM_SS.format etc). 

If a malicious user is familiar with programming, it won't be a problem to write a basic script to iterate over the victim's Dropbox Public folder and get alive links with content which can be private sometimes: screenshots and all the stuff people use the uploader for. Even thought the folder is called Public, most of us use it to share files with specific people, not to make it accessable for everyone in world wide web.

Simple analogy is Youtube: videos can have the following access level:
- public - available to anyone
- unlisted - available by link only
- private - available only for the uploader

I found myself reasonable to change the filename to %guid% to actually make it less possible to get my files via plain iterating. Do you find it as an actual possibility for data leak or I'm excessively paranoid?

**Version of ShareX:** 11.5

**Comment by Jaex** [comment]
This applies to most of uploaders in the world. For example Imgur creates like this URL:

http://i.imgur.com/2a3lwES.png

Which is 7 characters long and someone can brute force every single variation to find all Imgur images stored in their servers.

So it is users responsibility to choice which hosting or file naming they want to use.
