### ISSUE TITLE
Custom uploader wrong post arguments

### ISSUE THREAD

**Issue by CalibeR50** [ShareX/ShareX#2289]
My URL shortener does not work anymore. It is using POST as request type with an empty file form name and an argument with url = $input$. When clicking test, the arguments are encoded into the url (From Apache logs: POST /sharex.php?apiKey=xyz&type=url&url=https%3a%2f%2fgetsharex.com HTTP/1.0). 

Shouldn't the arguments be in the request body, or am I missing something?

**Comment by Jaex** [comment]
#2250
