### ISSUE TITLE
[Request] Copy multiple tagged urls/forum code urls from history panel

### ISSUE THREAD

**Issue by tioaxel** [ShareX/ShareX#2292]
When dragging and dropping for a batch upload, the files are usually out or order and cannot be sorted by filename:
[http://i.imgur.com/8Cruzzw.png](url)
This shouldn't be an issue because history lets me sort and filter, but here's the kicker: on Sharex's activity window, I can select multiple images, right click -> Copy -> Forum (BB Code) Linked Image (for example), and it'll copy the Forum (BB Code) Linked Image for all selected images. In the History window, this doesn't work (it only copies the code for the first selected file); the only 'multiple copy' options that work are URL and HTML Link.

So, my request: make copying multiple link/image/linked images available for history, or make sorting available for the activity window.

Thank you.

**Comment by Jaex** [comment]
Added by #4548
