### ISSUE TITLE
Custom URL Shortener "Error: Result is empty."

### ISSUE THREAD

**Issue by Xorgon** [ShareX/ShareX#2295]
I am currently receiving "Error: Result is empty." when testing my custom URL shortener. It has worked in the past, and the server side is fine (tested with a separate POST request which returned a shortened URL). It is a simple POST request with an argument specifying the URL to be shortened. The same script works fine for image and file uploads with ShareX.

I don't recall shortening any links recently, so it is plausible that it has broken as of 11.5.

**Comment by Jaex** [comment]
#2250
