### ISSUE TITLE
Settings Question

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2296]
I have ShareX on my PC and a portable version on my USB drive.  Is it possible to clone the settings from the PC installation to the USB portable?

**Comment by Jaex** [comment]
Portable creates ShareX folder in it to store settings. So you can copy your settings from Documents/ShareX to that portable folder.

**Comment by MrCD1968** [comment]
Do you copy everything in the documents sharex folder or just the files that say sharexsettings.xml and sharexsettings.json?
 
  ----- Original Message -----

**Comment by Jaex** [comment]
Only json and xml files.
