### ISSUE TITLE
4K screen problems

### ISSUE THREAD

**Issue by ssl** [ShareX/ShareX#2298]
Hello!

There is a problem with icons on 4K screens, it just doesn't look good:
![image](https://cloud.githubusercontent.com/assets/25695071/23039348/8d3fc6fc-f48d-11e6-80b8-3a905767259c.png)

Also all the images will be 4 times bigger when you upload it.
For example, look at the logo on the left top. When I screenshot it is ends up like this:
![image](https://cloud.githubusercontent.com/assets/25695071/23039434/c37aa4a8-f48d-11e6-93b8-11355e465cb5.png)

Would love some 4K support.

Thanks.

**Comment by Jaex** [comment]
Without have 4k monitor it is not easy to support it. Because it will require many testings for many things.

**Comment by legit** [comment]
too bad. same problem over here

**Comment by ssl** [comment]
Hi Jaex,

When I put my windows scaling in 100% the screenshots are fine.
![image](https://cloud.githubusercontent.com/assets/25695071/23042765/38dd1724-f49a-11e6-87de-0ab24d018d63.png)

Maybe it is possible to make 100% a default, or a setting in ShareX. That way testing is not really needed. 
I really really love ShareX, but it is just not working as I need it to be.

**Comment by melior88** [comment]
As a temporary fix, you can create a manual manifest to handle DPI.
`Press  Windows Button + R, type “regedit”, and then click OK.
Navigate to the following registry subkey:
HKEY_LOCAL_MACHINE > SOFTWARE > Microsoft > Windows > CurrentVersion > SideBySide
Right-click, select NEW > DWORD (32 bit) Value
Type PreferExternalManifest, and then press ENTER.
Right-click PreferExternalManifest, and then click Modify.
Enter Value Data 1 and select Decimal.
Click OK. Exit Registry Editor.`

and then create a file on the ShareX installation folder named `ShareX.exe.manifest` and add this code:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">

<dependency>
  <dependentAssembly>
    <assemblyIdentity
      type="win32"
      name="Microsoft.Windows.Common-Controls"
      version="6.0.0.0" processorArchitecture="*"
      publicKeyToken="6595b64144ccf1df"
      language="*">
    </assemblyIdentity>
  </dependentAssembly>
</dependency>

<dependency>
  <dependentAssembly>
    <assemblyIdentity
      type="win32"
      name="Microsoft.VC90.CRT"
      version="9.0.21022.8"
      processorArchitecture="amd64"
      publicKeyToken="1fc8b3b9a1e18e3b">
    </assemblyIdentity>
  </dependentAssembly>
</dependency>

<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
  <security>
    <requestedPrivileges>
      <requestedExecutionLevel
        level="asInvoker"
        uiAccess="false"/>
    </requestedPrivileges>
  </security>
</trustInfo>

<asmv3:application>
  <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
    <ms_windowsSettings:dpiAware xmlns:ms_windowsSettings="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</ms_windowsSettings:dpiAware>
  </asmv3:windowsSettings>
</asmv3:application>

</assembly>`

**Comment by emreeren** [comment]
@melior88 thank you for the suggestion, that fixes the dpi issue. Unfortunately it breaks capture preview. My screen scales to %250 so it previews about 1/5 of the screen.

**Comment by melior88** [comment]
@emreeren I encountered the same issue so I had to go back on that as well. Last version has improved a lot on this matter so now is at least tolerable.

**Comment by BHare1985** [comment]
I also experience this issue in 12.2 so I want to bring this out of stale. I am more concerned about my screenshots being 2x or 4x bigger than normal.
