### ISSUE TITLE
Support PUT in Custom Uploaders

### ISSUE THREAD

**Issue by sinni800** [ShareX/ShareX#2299]
You have PUT listed as a method, but apparently it isn't even allowed to be used for anything.

At least with files, allow PUT with the file name being either something random or the actual file name the screen was saved with on the hard drive. 

Since the server only gives you back success without any json or xml, allow inserting the FileName or the whole url into the "resulting" url. 

Because for example I have a webdav target that is protected using basic auth (myserver.de/webdav/) while the root is public. The file would be PUT to the resource myserver.de/webdav/file.name while the file would be retreivable at myserver.de/file.name. This is just the way I have it now. Others might have myserver.de already be a webdav target but that differs.

**Comment by Jaex** [comment]
Are you sure where you uploading is allows PUT multi-part data instead of just plain data on request.

**Comment by sinni800** [comment]
I don't need a multipart PUT since I only have the file name and the file content anyway.

**Comment by Jaex** [comment]
The thing is there is so many methods like PUT with binary data, PUT with multipart, PUT with url encoded data, PUT with query parameter, PUT with multipart/related protocol etc. So I added most used method per http method to custom uploader to keep it simple as possible. Using binary data uploading is very bad way when there is multipart protocol which allows supplying file name in same section, not to mention it is very rarely used by file uploader APIs. Therefore I'm not planning to add it.

**Comment by sinni800** [comment]
PUT is the standard method used for WebDav. Also, it us usually used without a multipart encoding - multipart encodings are reserved to POST queries most of the time.

I haven't ever honestly seen PUT used with a multipart payload. 

You usually say

    PUT /somewhere/destinationFilename.jpg
    Content-Type: image/jpeg (or, generally, application/octet-stream, can be used for all files)

and dump the whole file content into the request payload.

This one method would satisfy DropBox (through DropDav), Seafile, Owncloud and incidentally, any webservers with WebDav capabilities. This includes Apache (mod_dav) and Nginx (ngx_http_dav_module), Microsoft IIS, lighttpd, Caddy and others. 

The reponse will only be a 200 OK response without any file names attached. This is because usually, the file name you provide is the file name that it will be on the server.

**Comment by Jaex** [comment]
Added binary body support to custom uploader now but because webdav not returns url. I don't think it gonna be possible to be used with custom uploader.

**Comment by sinni800** [comment]
I will test it will Seafile's seaf-dav module

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds

**Comment by sinni800** [comment]
Oh thanks, I was about to build it manually... That's much quicker.

**Comment by sinni800** [comment]
Alright, after testing, I found out it works, but there is one problem with it: It doesn't do authentication, it seems!

This is a non-password protected webdav server:
use https://davtest.metalgearsonic.de/dav/$filename$ as the upload URL
use https://davtest.metalgearsonic.de/$filename$ as the uploaded result URL

This works fine

But try it with this password protected one: 
https://test:abc@davtest.metalgearsonic.de/davauth/$filename$
https://davtest.metalgearsonic.de/$filename$ as result url

the user name is "test", the password is "abc" - encoded into the path. It would be helpful to be able to use http authentication so your webdav server can be protected from other people writing to it!

**Comment by Jaex** [comment]
It worked: https://davtest.metalgearsonic.de/Test.png

```json
{
  "DestinationType": "ImageUploader, TextUploader, FileUploader",
  "RequestType": "PUT",
  "RequestURL": "https://davtest.metalgearsonic.de/davauth/$filename$",
  "RequestFormat": "Binary",
  "Headers": {
    "Authorization": "Basic $base64:test:abc$"
  },
  "URL": "https://davtest.metalgearsonic.de/$filename$"
}
```

**Comment by sinni800** [comment]
Ahh, thanks for the configuration. Good to know it should be configured this way!

**Comment by artfabrique** [comment]
@Jaex I've checked dev build and it does not append file name to request URL but it should. Do you have any wildcards in the request URL like $filename etc?

**Comment by artfabrique** [comment]
AH! it's worked with $filename$

**Comment by Jaex** [comment]
Note, I changed name of `RequestFormat` variable to `Body` so you must re select `Binary` option in latest dev build or next stable version. I would prefer you to download latest dev build too for testing purposes.

**Comment by sinni800** [comment]
@Jaex Would it be possible to have HTTP DELETE too, for the removal link? It would somewhat complete the WebDav support in general and RESTful access to online resources.

**Comment by Jaex** [comment]
Do you think it is like that easy. It requires a lot of settings to be stored in history. Literally I would need to store custom uploader itself in history for each entry to specify required data required for that deletion request. Right now only deletion URL stored in history. Also duplicate of #3943.

**Comment by sinni800** [comment]
Oops, I forgot that I already put this in as an issue. I didn't want to assume how hard it would be!
I see what you mean though and it's definitely true that the custom uploader would have to be present in the history, hum.
