### ISSUE TITLE
Copy to clipboard before opening in editor

### ISSUE THREAD

**Issue by pvutov** [ShareX/ShareX#2301]
Currently the "After capture tasks" list looks like so: http://i.imgur.com/E3i7DOA.png
Could a copy of the "Copy image to clipboard" task be added before the "open in editor" task? [So it becomes : http://i.imgur.com/lT7I69x.png ]

As a user my most common use cases with screenshots are:
-copy area -> paste it into anki
-copy area -> highlight some part of it -> paste into anki
-copy area -> upload -> send to friend

Previously I used the windows snipping tool, and it's very convenient for use case 1 because it puts the image in clipboard before opening the editor. It's a bit slower with ShareX because there isn't a copy to clipboard task above the open editor one, so I have to press "copy" in the editor even if I'm not making any changes to the image.

I could read up and write a custom perform action script for myself, but maybe you'll judge this a common enough use case to make available without scripts?

**Comment by Jaex** [comment]
There is reason why it is under image editor, because it should copy result from image editor. So it can have up to date image.

**Comment by DavidMichaelangelo** [comment]
@Jaex what about an option to change that order? Most of the time I don't need to edit the image, so I'd like the original capture to be copied. Then, if I want to copy the image after editing it, I can do it manually. As it is right now I have to manually copy most of the captures I take.

(Also, after I make an edit, the image isn't automatically copied either. So is there no way to have it automatically copy it at all? I don't need to ever upload my images, I just need it to automatically copy the capture with the option to edit the image and then manually copy the edited one.)

**Comment by lonelymaw** [comment]
Seconded on this, this is a common workflow for me that I was used to from Greenshot -- like @DavidMichaelangelo, I don't usually need to do post-capture editing, but I like having the option without slowing down my workflow.

**Comment by yashpalgoyal1304** [comment]
hello all, if i am getting what u are saying right, then this can easily be accomplished by using the quick task menu in the after capture tasks - and that menu items can be customised too.

![image](https://user-images.githubusercontent.com/19423063/104860154-03be7000-5950-11eb-8d69-98070e7a577e.png)
![tTVzlrTA94](https://user-images.githubusercontent.com/19423063/104860321-e047f500-5950-11eb-994a-8245763e90d2.gif)

**Comment by DavidMichaelangelo** [comment]
yashpalgoyal1304, that's almost what I'm looking for but is there a way to get it to copy the image automatically?
I'm trying to save myself having to manually copy the image every time, since I **always** want to copy the screen capture. 

I want to be able to hit "PrtSc" to have the screenshot taken and copied at the same time so I can immediately paste it into Photoshop.

**Comment by DavidMichaelangelo** [comment]
Also, it appears that by using the quick action menu, it disrupts the flow. So I can't select to copy the image and then have it open in the editor. If I edit the menu option, it won't allow me to have the image copied **first** and then open the editor. It always opens the editor first, and then the image is never copied . . .

**Comment by boast1570** [comment]
I'd like to see this functionality as well. Coming from Snagit... With both "Open Image Editor" and "Copy to Clipboard" are selected, the copy does not occur. Seems like a bug to me. It's not performing the second requested "after capture task. This would save quite a few clicks. Any chance to reopen this?

**Comment by pvutov** [comment]
Thanks @yershom, as far as I can tell this does the job perfectly.

**Comment by Rudi54rv** [comment]
Hy all,

i also wanna have to "copy to clipboard" and "savefile" before the "Editor". I solved it with the "PerformAction" task.

<img width="253" height="466" alt="Image" src="https://github.com/user-attachments/assets/b5382856-f4bf-4a8e-b869-c59b4a5b55d3" />

The perform action can be organised with:
Task settings -> Actions -> add a action with path to sharex.exe

<img width="1263" height="543" alt="Image" src="https://github.com/user-attachments/assets/e239874a-5d3b-46fb-a356-c2cb0b920f95" />

Hope that helps. But would be nice to organise the "after capture tasks" manually.
