### ISSUE TITLE
Screen Record(FFmpeg) mouse posistion not exact

### ISSUE THREAD

**Issue by JeffreySu** [ShareX/ShareX#2303]
![image](https://cloud.githubusercontent.com/assets/2281927/23090814/f8ab9cc2-f5e1-11e6-8e6b-24164080fe66.png)

My real mouse position is on Label 2 at that time, but in MP4 it's on Label 1.

My screen is 3000 * 2000, windows 10 pro, surface book.

**Comment by Jaex** [comment]
#1329
