### ISSUE TITLE
missing "apply" button on greenshot editor when I drop external picture on it to edit it

### ISSUE THREAD

**Issue by WiliTest** [ShareX/ShareX#2305]
To reproduce:
take one of your picture. Drop it into sharex. Click Edit. It will be opened in greenshot editor. Modifie it, then you get stuck. You can't save it (well you can, by clicking on the save button and then closing the windows, but it's not intuitive since there is no message. Showing the ✔ green button would solved it.

Thanks!

**Comment by campbeb** [comment]
The green check mark means "Accept and perform tasks" (the after capture and upload tasks).
Because you are just editing, there are no tasks, so the arrow, stop and cancel buttons are not shown.

**Comment by WiliTest** [comment]
Thanks for your reply. I understand, but it's just that the way to save isn't intuitive: when you click on the save icon, it doesn't do anything. Ex: I made many changes and I did not know if they were saved or not, to know I needed to close the editor and check the picture after (I knew I could no going back, since the editing layers are merged with the picture). It's just a feedback.

**Comment by Jaex** [comment]
All save buttons works like that in all image editors or text editors.
