### ISSUE TITLE
Suggestion/Enhancement/Question: Add previously expired images to History.

### ISSUE THREAD

**Issue by availableusername888** [ShareX/ShareX#2306]
So I accidentally uploaded my screens anonymously to Imgur. I have easily activated the deletion URL for the most recent ones, and the ten set to show up in the Main Window Toolbar. But I have doubtless uploaded several dozen other screenshots that outlive the ten "History" items. Is there a way I can bring these old images within reach to appear as "History" like these other ten? I toggled "Save Recent Items" up to the maximum but that has not done the trick.

Apologies in advance if bringing that functionality would be too much work; I am not a programmer and would not know.

![sharex_2017-02-19_21-03-48](https://cloud.githubusercontent.com/assets/25891113/23110427/f6a3476c-f6e6-11e6-9129-07d5e4325585.png)

**Comment by Jaex** [comment]
Check history:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/ShareX_512D9676De.png)

**Comment by availableusername888** [comment]
Right. I followed the History link specifically, it led me to 33 photos from a seemingly random period of time, two of which had links and I snuffed them out. So thanks for that.

![sharex_2017-02-19_21-22-16](https://cloud.githubusercontent.com/assets/25891113/23110789/888f50ec-f6e9-11e6-9220-8fb3161b31b7.png)

I opened "UploadersConfig.json" in my ShareX folder and in the Imgur section I see a line making notice to an expiration date; does this have anything to do with my situation?

![applicationframehost_2017-02-19_21-24-49](https://cloud.githubusercontent.com/assets/25891113/23110884/377fdb12-f6ea-11e6-96a4-f24dd0fabc63.png)

**Comment by Jaex** [comment]
Why you showing your secret tokens in public...

ExpireDate is when tokens expire. Nothing to do with image expiration.

**Comment by Jaex** [comment]
Go here http://imgur.com/account/settings/apps and revoke access to ShareX. Then those tokens gonna be invalid.

**Comment by availableusername888** [comment]
I tied an account to Imgur just today in an attempt to retrieve photos somehow but it's useless without URLs in hand. Looking through the logs it does not seem like all the screenshots were uploaded upon capture, and those that were have the URL present here in the logs.

If I am right in assuming I have every URL of every public photo then I will just collect them from my logs and submit them to Imgur in a deletion request.

Thank you for your attention.
