### ISSUE TITLE
Nextcloud uploading succeeds but no URL provided, errors

### ISSUE THREAD

**Issue by zaggynl** [ShareX/ShareX#2308]
Using ShareX 11.5 and Nextcloud 11.0.1.
Using the Owncloud profile.
It uploads successfully but errors afterwards with:

> The server commited a protocol violation. Section=ResponseHeaderDetail=CR must be followed by LF

I'm running my own Nextcloud server at https://zaggy.nl/nextcloud, can provide a login for testing.

**Comment by Jaex** [comment]
I don't use Nextcloud or ownCloud but people who using nextcloud was told that ShareX supports Nextcloud properly in latest version.

**Comment by zaggynl** [comment]
Tried with ShareX 11.6, no change.

**Comment by maxibanki** [comment]
I've tested it with the latest version. It works without any problems, 
Nextcloud: 11
ShareX: 5e5a5e4 01.03.2017 Build from source

**Comment by zaggynl** [comment]
Thanks for confirming, I'll wait for the next release binary :)

**Comment by zaggynl** [comment]
Tested with ShareX 11.7, same error.

**Comment by aStonedPenguin** [comment]
It works fine on NextCloud11.0.0, they probably changed something again. It may be worth making ownCloud and NextCloud separate uploaders in the future.

**Comment by BetaLeaf** [comment]
@aStonedPenguin I agree with this assessment. If you need, I have a NextCloud 12 Server available to test stuff on. Let me know if I can help.

**Comment by BetaLeaf** [comment]
Nevermind, after looking at the source code, I got it working on NextCloud 12. I was using the webdav path instead of just the hostname.

**Comment by zaggynl** [comment]
@BetaLeaf How did you get it working?
I'm currently using the following settings: http://i.imgur.com/ODXAF10.png
Am still getting the same error on ShareX 11.8.

**Comment by aStonedPenguin** [comment]
Does the folder /ShareX exist already in NextCloud?

**Comment by BetaLeaf** [comment]
Using ShareX 11.8, my settings looks like this: https://drive.google.com/uc?id=0ByILJfRaEBfkd3pSaHdGdEh0UGs

**Comment by BetaLeaf** [comment]
Using ShareX 11.8, my settings looks like this: https://drive.google.com/uc?id=0ByILJfRaEBfkR2hKeTZlZUVUZDQ
Edit: Fixed Link.

**Comment by BetaLeaf** [comment]
Your settings look correct. Make sure the following is true:

Make sure the path already exists.
Make sure your username and password is correct.
Make sure you ip address isn't restricted by the anti-flood module. 

You can verify if it is or not by mapping your root webdav folder to Window's File Explorer. Logging in will either only take a few seconds, or will take about 30 seconds. If it takes about 30 seconds, your ip is being restricted by the anti-flood module. Note if restricted via webdav, you can still log in on the website pretty fast. It only restricts the type of login you attempt. If you are restricted, do the following unrestrict your ip address:

If you have phpmyadmin installed, log into phpmyadmin. You can find your login details by 
```sudo nano /var/www/nextcloud/config/config.php```, then select the nextcloud_db from the list of databases on the left. Then at the top, click the SQL button. Insert 
```DELETE FROM `oc_bruteforce_attempts` WHERE `oc_bruteforce_attempts`.`ip` = 'xxx.xxx.xxx.xxx';```, replacing xxx.xxx.xxx.xxx with your IP Address and click simulate query and see if it finds anything. If it does, then click go to run the command against your server. 

If you don't have phpmyadmin, then on your box, 
```sudo mysql```, then 
```use nextcloud_db```, then 
```DELETE FROM `oc_bruteforce_attempts` WHERE `oc_bruteforce_attempts`.`ip` = 'xxx.xxx.xxx.xxx';```, replacing xxx.xxx.xxx.xxx with your IP Address.

**Comment by zaggynl** [comment]
Thanks for the replies!

Make sure the path already exists. ☑ (it uploads fine, with or without ShareX folder, file just ends up in root)
Make sure your username and password is correct. ☑ (it uploads fine)
Make sure you ip address isn't restricted by the anti-flood module. ☑ (I truncated the oc_bruteforce_attempts table) and whitelisted my LAN range in nextcloud.

Not sure how to use the Windows 10 webdav networking mapping, it won't accept https://zaggy.nl/nextcloud/remote.php/webdav/ as a path, I actually bought Mountain Duck for webdav as it's the most stable so far.
---------------------------
Add Network Location
---------------------------
The folder you entered does not appear to be valid.  Please choose another.
---------------------------
OK   
---------------------------

**Comment by lankanmon** [comment]
I would like to BUMP this as I am experiencing the same issue.
Using OwnCloud setting with Nextcloud address.
I also ensured that all above steps are correct.

ShareX does upload the files correctly, but returns a failed message and no URL.

This is the error:
```
Message:
The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF

Request URL:
https://<my.nextcloud.domain>/remote.php/webdav/PC/screenshots/2017-09-15_23-31-11.png

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
```

Any help would be much appreciated!

Thank You!

**Comment by BetaLeaf** [comment]
https://help.nextcloud.com/t/solved-webdav-problems-with-windows-explorer-on-windows-10/6178/6

**Comment by zaggynl** [comment]
Decided to give it another go, appears to be working with below configuration:
https://i.imgur.com/WpM7h07.jpg
