### ISSUE TITLE
starting auto capture automatically with Windows?

### ISSUE THREAD

**Issue by piconut** [ShareX/ShareX#2309]
Greetings,  I just installed your ShareX and I can get ShareX to automatically start with Windows (even though the dialog checkbox doesn't stay checked) but I have to manually start the automatic capture each time Windows starts up.  I need to enable the auto capture mode so that it starts automatically when Windows boots up.  How can I do this?  Thank you for your help.

**Comment by Jaex** [comment]
`silent -startautocapture` adding these to ShareX startup shortcut should work.

**Comment by piconut** [comment]
That worked fine, thank you Jaex.

**Comment by yyyavuz** [comment]
I could not jaex

**Comment by yyyavuz** [comment]
Can you help me?

**Comment by yyyavuz** [comment]
it doesn't work I cant start auto capture after restart
Can you share more detail
Thank you
