### ISSUE TITLE
how to save a screen capture file and upload a copy with a different name

### ISSUE THREAD

**Issue by piconut** [ShareX/ShareX#2310]
Greetings,

I would like to save a dated copy of the file locally but upload a file with a static name.  Specifically, I am would like to save the screen capture with the year-month-day file name (%y-%mo-%d) but when I upload the file, I want the file to be named screen.png.  Currently, my settings have the file being named with %y-%mo-%d but it also uploads the file with the same naming convention which makes it difficult to link within an HTML document because the name changes.  Can you please tell me what settings I need to change to save the remote file with a static filename (screen.png)?    Thank you once again for your help.

**Comment by Jaex** [comment]
You can't have different file naming for upload.

**Comment by piconut** [comment]
OK, so here is what I'm trying to do and maybe there is another way to do it.  I have an HTML document that has an image embedded in it called "screen.png".  If I set up ShareX to save the file with the same name every time and upload it, it works fine; however, I also need to save a backup of the screen capture locally and have a historical listing of all those files, one for each day.  How can I do this?

**Comment by Jaex** [comment]
Write your own script?

**Comment by piconut** [comment]
Unfortunately I am not a programmer and know nothing about writing a script. 

How about this for a work around:  Can I use ShareX to take 2 different sets of screen captures.  The first one would capture every hour, and the second one would capture every 24 hours.  Is that possible?  I really do appreciate your help.

**Comment by Jaex** [comment]
Auto capture of ShareX is singleton window which means it can't be opened multiple times (opening it second time activates already open one). So you can't have 2x auto capture running.
