### ISSUE TITLE
cuntflaps.me changes its name to safe.moe

### ISSUE THREAD

**Issue by carrageen** [ShareX/ShareX#2312]
Hey there,
cuntflaps.me has changes its name to safe.moe (more about that here: https://loli.forsale/blog/push-f-for-respects/)
Could you please push an update and hotfix the uploader?

Kind regards

**Comment by Jaex** [comment]
You can easily change it from here: https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/FileUploaders/Pomf.cs

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/chrome_84xkG6eYVA.png)

**Comment by Scrxtchy** [comment]
This has already been fixed in #2282
