### ISSUE TITLE
getsharex.com Error 1014

### ISSUE THREAD

**Issue by sparkyman215** [ShareX/ShareX#2313]
![pkdlhwo 1](https://cloud.githubusercontent.com/assets/4030760/23280068/cf3a2bee-f9e5-11e6-8f26-aed6d0cbd45a.jpg)

Went to check the changelog after an alert for a new update.

**Comment by Jaex** [comment]
Cloudflare have problem and many peoples web site is banned currently:
https://twitter.com/search?q=CNAME%20Cross-User%20Banned&src=typd

**Comment by sparkyman215** [comment]
Ah ok. Just wanted to make sure shareX was okay. Shoulda done some research beforehand 😜

**Comment by Jaex** [comment]
https://twitter.com/GetShareX/status/834890611467698176

**Comment by Jaex** [comment]
They fixed problem look like, web site opens now.
