### ISSUE TITLE
f. request: delete file on server 

### ISSUE THREAD

**Issue by WiliTest** [ShareX/ShareX#2317]
It's super to upload file on server, but it would be even better if we could also delete them too.
For instance we can right now upload file on imgur, it would be nice to be able to delete file (ex using a right click/delete file on server).

(I understand it's quite complicate to deal with these APIs requests)

thanks for your work!

**Comment by Jaex** [comment]
You know about "Open -> Deletion URL" right?

**Comment by WiliTest** [comment]
no! I'm testing it right now!

**Comment by WiliTest** [comment]
I uploaded a screenshoot on imgur (I checked the destination), then I right click on the item open/deletion URL but nothing happens

**Comment by Jaex** [comment]
How nothing happens? It opens deletion url in my browser.

**Comment by WiliTest** [comment]
No really, nothing happens (at all). I'm trying on another computer

**Comment by Jaex** [comment]
Can you check debug log, it must show url which tried to open.

**Comment by WiliTest** [comment]
```
2017-02-25 11:51:09.870 - OpenURL(http://imgur.com/delete/UZu4c1yxeQ8lZcH) failed:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.URLHelpers.<>c__DisplayClass0_0.<OpenURL>b__0()
```
It's maybe because the file is not saved locally. I'm checking that

**Comment by Jaex** [comment]
Open Windows run (Windows button + R) and then type url there and press enter. It will fail too probably.

**Comment by WiliTest** [comment]
[Window Title]
(http://imgur.com/delete/UZu4c1yxeQ8lZcH

[Content]
Windows cannot find '(http://imgur.com/delete/UZu4c1yxeQ8lZcH'. Make sure you typed the name correctly, and then try again.

[OK]

**Comment by WiliTest** [comment]
I'm trying to find that option (save locally)

**Comment by Jaex** [comment]
It is nothing to do with ShareX or its save locally option.

**Comment by WiliTest** [comment]
ah ok, what should I do?

**Comment by Jaex** [comment]
Try re installing your browser maybe.

**Comment by WiliTest** [comment]
I'm using chrome by the way. I could test with another browser, right?

**Comment by WiliTest** [comment]
[SOLVED!] Somehow the browser path link to an empty folder. Now it's working. Oh man sharex is just awesome. 

I would though recommand:
● using "delete file on server" (or delete distant file). I did not understand what "Delete URL" meant. 
● moving this option either under a "delete" category or with the main stuff (it's not inuitive to go to "open" to delete a file. 
I understand open means probably "open the delete URL", but both, the categorization and name aren't intuitive for basic users (like me). It I'm not the only one looking for the delete option: https://github.com/ShareX/ShareX/issues/389

**Comment by Jaex** [comment]
It __opens__ URL in your browser, same as other open URL options there. So it must be inside open and fits very well with other options in that category. Also "Delete file on server" is very misleading because it not deletes file, it just opens deletion URL.

**Comment by WiliTest** [comment]
I understand your point, but I disagree (basic users logic isn't the same as your). But I won't forget this awesome option, so it doesnt matter anymore for me and I'm (very) happy with it! 

Making it work with google drive would be also super (If sharex use python, I could help with the API request)

**Comment by ZimM-LostPolygon** [comment]
What about deleting a file from FTP? Dropbox? Google Drive etc.? It would be super useful.
