### ISSUE TITLE
Request: Azure Storage with custom domain

### ISSUE THREAD

**Issue by NullEntity** [ShareX/ShareX#2318]
I have an Azure CDN with a vanity domain that points my Azure Storage account. I would like to be able to have my uploads use https://StoreYourSh.it/agent766/example.png over https://storeyourstuff.blob.core.windows.net/agent766/example.png. Maybe custom URLs could be written in the same format as custom uploaders.

**Comment by wi5nia** [comment]
It will be done :)

**Comment by altano** [comment]
I would love this as well!

**Comment by Lego6245** [comment]
Hopefully this lights up for folks soon! Enjoy.
