### ISSUE TITLE
SFTP destination keypath no longer accepts keys on network drives

### ISSUE THREAD

**Issue by snownel** [ShareX/ShareX#2319]
When using the SFTP destination with a keyfile, the keypath no longer accepts keys on network drives as of 11.6 - the only drives that appear in the file selector are local ones, and the network drives are not even shown at all. This is a problem because I store my private keyfile on a NAS instead of on each local machine. This was not the case in 11.5 and earlier but nothing in the changelog indicates a change to the SFTP uploader.

When trying to upload, this is the debug log:

> 2017-02-25 11:54:18.624 - Task in queue. Job: Job, Type: File, Host: FTP
> 2017-02-25 11:54:18.630 - Exception:
> System.IO.FileNotFoundException: Key path is invalid.
> File name: 'N:\ShareX\Keys\ssh-private-key-openssh.key'
>    at ShareX.UploadersLib.FileUploaders.SFTP.Connect()
>    at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
>    at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 2017-02-25 11:54:18.638 - Task status: Preparing
> 2017-02-25 11:54:18.643 - Upload started. Filename: ddgMT.png
> 2017-02-25 11:54:18.649 - Task failed. Filename: ddgMT.png, Errors:
> System.IO.FileNotFoundException: Key path is invalid.
> File name: 'N:\ShareX\Keys\ssh-private-key-openssh.key'
>    at ShareX.UploadersLib.FileUploaders.SFTP.Connect()
>    at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
>    at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)

Moving the key to a local drive fixes this problem but is a poor workaround. Why can ShareX suddenly not handle network drives?

**Comment by Jaex** [comment]
There is no change in SFTP codes as you can see from here: https://github.com/ShareX/ShareX/commits/master/ShareX.UploadersLib/FileUploaders/SFTP.cs

**Comment by snownel** [comment]
A clean reinstall appears to have fixed the problem... somehow.
