### ISSUE TITLE
"You are attempting to upload a large file." dialog issues

### ISSUE THREAD

**Issue by YisroelAdler** [ShareX/ShareX#2324]
When trying to upload a large file (100MB by default) with ShareX it will ask if you are sure that you want to continue. 

But it is very annoying that the popup dialog pops up behind all open windows (see screen share below), and sometimes one doesn't realize until later when he opens the ShareX window and see it doesn't upload or until he closes all other windows.

I think it is very important that this dialog should appear on top of everything.

![Alt Text](http://i.imgur.com/FKKds6S.gif)

**Comment by Jaex** [comment]
I even bring that window front in form shown event, how it managed to stay back.

**Comment by Svetomech** [comment]
I had the same issue w/ winforms back when I still used them. Found no real solution, only a workaround of creating a timer which periodically sets `TopMost` property to `true`.

**Comment by YisroelAdler** [comment]
For me, it does not show in front of any window I tried it with (Chrome, Windows Explorer, Virtualbox and more.)

**Comment by Jaex** [comment]
That window stays top of everything (Chrome, Windows Explorer) in my pc. And I can't make it stay behind any window.

**Comment by Jaex** [comment]
Your ShareX runs as admin I think. Not sure why but that causing this issue.

**Comment by YisroelAdler** [comment]
Why do you think my ShareX runs as admin? From what I see (see Task Manager below) it does not. I also tried it now with run as admin and it was the same.

![taskmgr_2017-02-26_15-09-47](https://cloud.githubusercontent.com/assets/7387839/23343210/cbe64048-fc35-11e6-9454-824811293fca.png)

**Comment by Jaex** [comment]
Because I ran ShareX as admin and finally I could reproduce your issue.

**Comment by YisroelAdler** [comment]
But as you can see in my Task Manager screenshot I'm clearly not running it as admin.

The only way for me that it does pop up in front of all windows is if the ShareX window is open (as a window in the Task Bar and not merely in the Notification Area) and it is minimized to the Task Bar. And in that situation it comes in front even if run as admin.
