### ISSUE TITLE
Request: Warning before uploading image

### ISSUE THREAD

**Issue by Freekers** [ShareX/ShareX#2326]
Upon taking my first screenshot, I got a warning that it would be uploaded. However, this warning only appears once, while I would like to have it for every screenshot I took.

A workaround would be to enable the 'Before Upload' dialog and clicking cancel, however such a large window is unnecessary in my opinion just to cancel a upload. (Or create two seperate hotkeys; one for taking just screenshots and the other one for taking & uploading screenshots).

**Comment by Jaex** [comment]
You can also use "Show quick task menu" or "Show after capture menu". So there is 3 different method to show window before uploading image already.
