### ISSUE TITLE
Request: Cheaper Patreon Levels

### ISSUE THREAD

**Issue by Freekers** [ShareX/ShareX#2328]
I'm willing to support you guys, but to be honest 5$ a month is a tad too high for me. How about implementing some cheaper Patreon levels, e.g. 1$ or 2.5$? Every bit helps right?

**Comment by Jaex** [comment]
Patreon allows donating any amount when you click this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/chrome_mYl9iSCrRi.png)
