### ISSUE TITLE
Will not create a screenshot file

### ISSUE THREAD

**Issue by marekpetak** [ShareX/ShareX#2333]
ShareX 11.6

Capture screenshot will not create a file of screnshot. But will create record int status list. Record screen to gi works. Capture -> Window, Capture -> Monitor

![2017-02-28_10-25-29](https://cloud.githubusercontent.com/assets/7045818/23401705/9a92a024-fda0-11e6-8781-1657f1524e47.gif)

**Comment by Jaex** [comment]
Is "after capture tasks -> save image to file" checked?

**Comment by marekpetak** [comment]
No it wasn't ... Wierd I have never touched that settings. Was this reset by default on upgrade/install Thanks!

**Comment by Jaex** [comment]
By default that setting is checked.
