### ISSUE TITLE
The server committed a protocol violation. Section=ResponseStatusLine

### ISSUE THREAD

**Issue by Dantesa** [ShareX/ShareX#2335]
I just updated ShareX to 11.6 and started to get "The server committed a protocol violation. Section=ResponseStatusLine" error everytime I attempt to capture something. I was wondering what causes this and if there is anyway I can fix it or if I have to go back to an older version of ShareX if possible.

**Comment by Artiiz** [comment]
This is happening to me aswell, just recently started.

**Comment by snowingleader** [comment]
happened to me like an hour after, updating the thing, is there a way to turn off update?

**Comment by budthechud** [comment]
Getting this as well. 

```
Message:
The server committed a protocol violation. Section=ResponseStatusLine

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

Same for everyone?

**Comment by mrarticuno** [comment]
Same here

**Comment by ClearlyInvsible** [comment]
@budthechud Yep, same thing I got. Is it a broken upload connection to Imgur?

**Comment by snowingleader** [comment]
same, pls fix

**Comment by Dantesa** [comment]
Well im glad its not just me, now I feel less dumb

**Comment by Artiiz** [comment]
Yeah the error is at Imgur, I can't seem to even upload an imgur on the official site, so probably not issues with ShareX, just the API.

**Comment by budthechud** [comment]
It is at Imgur.  Looks like they changed their API out of the blue.

**Comment by ClearlyInvsible** [comment]
Of course they did.

Well now we wait.

**Comment by timelf123** [comment]
Doesn't seem that they changed it: https://api.imgur.com/changelog

`{"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":500}`

**Comment by budthechud** [comment]
Just change the Uploader for the time being. 

Destinations> Image Uploader > [Take your pick]

**Comment by Dantesa** [comment]
Changing uploader works http://tinypic.com/view.php?pic=2ecf4mp&s=9

**Comment by budthechud** [comment]
@timelf123 The Sharex Error shows 

 ```
 at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

Which could attribute to a temporary outtage but an API socket change would look the same with a failed .GetResponse() from WebRequest

**Comment by Flevity** [comment]
same here

**Comment by Jaykul** [comment]
It's not imgur, it's the _actual images_ -- I can't upload them to GitHub or Slack either. 🔥

**Comment by woctezuma** [comment]
> Amazon Web Services (S3), leading cloud computing company, went offline, dozens of big companies across the United States affected.

**Comment by Jaex** [comment]
https://twitter.com/imgur/status/836645670954008576

**Comment by cyberium** [comment]
I have also thought it was a regression due to recent upgrade. Thanks for the explanation.
[imgur status](http://status.imgur.com/)

**Comment by XxLMM13xXgaming** [comment]
Just started to me as well! So how can we fix?

**Comment by charlesmilette** [comment]
@XxLMM13xXgaming There's a major outage with Imgur. Wait until it gets fixed, you can see the status here: http://status.imgur.com/

**Comment by XxLMM13xXgaming** [comment]
@charlesmilette alright will do thanks!

**Comment by Jaykul** [comment]
Just use TinyPic 😁

At least until [AWS Health](https://status.aws.amazon.com/) is green again
