### ISSUE TITLE
Please add an application filter to the sub folder pattern

### ISSUE THREAD

**Issue by Cephel** [ShareX/ShareX#2336]
It is tedious when looking through screenshots from multiple applications to find them all in the same folder, it would be more convenient if it was able to create subfolders based on the application that the screenshot was taken from

ie.

Instead of 
- Screenshots/2017-02/chrome_2017-02-28_22-12-50.png
- Screenshots/2017-02/Discord_2017-02-02_21-50-32.png

It should be possible to set them as such:
- Screenshots/2017-02/chrome/2017-02-28_22-12-50.png
- Screenshots/2017-02/Discord/2017-02-02_21-50-32.png

**Comment by Jaex** [comment]
#2293
