### ISSUE TITLE
I can't open the app

### ISSUE THREAD

**Issue by brunomscoelho** [ShareX/ShareX#2338]
System.Reflection.TargetInvocationException: Uma exceção foi acionada pelo destino de uma chamada. ---> System.BadImageFormatException: Não foi possível carregar arquivo ou assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou uma de suas dependências. O módulo deveria conter um manifesto de assembly.
   em ShareX.TaskSettingsTools..ctor()
   em ShareX.TaskSettings..ctor()
   em ShareX.ApplicationConfig..ctor()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   em System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   em System.Activator.CreateInstance[T]()
   em ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   em ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   em ShareX.Program.LoadProgramSettings()
   em ShareX.Program.Run()
   em ShareX.Program.Main(String[] args)

ShareX 11.6 (Release)

**Comment by Jaex** [comment]
#1615
