### ISSUE TITLE
Google Photos Direct Link

### ISSUE THREAD

**Issue by ibigfire** [ShareX/ShareX#2344]
Okay, super sorry as this isn't really a problem with ShareX, moreso a problem with Google Photos.

When I take a picture with ShareX and it auto uploads and spits out a url, it's relatively short and very functional.  Something along the lines of: https://lh3.googleusercontent.com/-fK1Z-yS4Hak/WLk3nq2l6BI/AAAAAAAAN4I/0maT6mFpQTs/s0/firefox_2017-03-03_01-30-04.png and that's great.

I'm just really curious how you get that URL.  When I go into Google Photos and right click and view the image I get: https://lh3.googleusercontent.com/KGsk3fARgGEz0Gbt3ZpLKb-PIujXKCJd9rorsOFKv8aZSbvn9j3Bm_50l-Q3pt0mh0ndshilzqG505pPty-VGcZRcAk5rNhva42cx88VL5lgBWObHoAIrqRQVbC5s-eXDv5Hxi4kC6eVz2bHWZ3rG5-xTdceEFC25DCk89fiHpUFpKmtLpxnSQ2KgOCniuKC-BUFj_cK-xWPNRWOnRpej2MjTGSTiAqeCUpTGl6v2b4toU7pQ-Qq_YZYAhUg-a_jkTSEN13IZza0Q7Mn9kMSdUGqGRtpOigRIC6CpLgH3wRjjrMscQUXYfARC_A4-a3Xopcdjq5awag-3BkGHoGIJlG1eEU0I0xFNWJwrEfRBj5BnJd6Roav1UfdptAP-sd8MYlQNpLyL8T7BxSpe40zYusU6kxAiwDpoOBbXg5WbyTk2T11_4j_XLGL5JHdffJrFmvPb95CNMrB7hvZ7zuv5wrgaw8M4t_HZLPo7BnBVfMZ1pARF3m6YsuzRlSFAFvT9UevmQe_htlwFlYZvmRdcrS6clmQ346rRcnsQCDPZRcMmfL2nWAN6ihIyYUzxupAeCK5nhX8Dr_1oX_nJ_CkPW49OFO4iMuwGMb5Mi7aYkKgE59Sxhqz=w701-h294-no
which is large, unwieldy, not just the raw image, and overall just utter garbage.

So I'm just curious as to how you get the nice short and well formed URLs that you do.

**Comment by Jaex** [comment]
Picasa API gives that link.
