### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dreadaxe** [ShareX/ShareX#2347]
System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le fichier spécifié est introuvable.
Nom de fichier : 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   à ShareX.Program.Run()
   à ShareX.Program.Main(String[] args)

AVT : la journalisation de liaison d'assembly est désactivée.
Pour activer la journalisation des échecs de liaison d'assembly, attribuez la valeur 1 à la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD).
Remarque : une certaine perte de performance est associée à l'enregistrement dans le journal des échecs de liaison d'assembly.
Pour désactiver cette fonctionnalité, supprimez la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog].

ShareX 11.6 (Release)

**Comment by Jaex** [comment]
#1615
