### ISSUE TITLE
Add Gfycat login [Gfycat API added]

### ISSUE THREAD

**Issue by PossiblyKris** [ShareX/ShareX#2348]
Since #559 was closed Gfycat has added API authentification. 
https://developers.gfycat.com/api/#authentication

Is it now possible to implement Gfycat login so we can upload to our accounts instead of anonymously?
It would be greatly appreciated. Thanks for your time.

**Comment by Jaex** [comment]
Gfycat was contacted me 1 month ago they told they planning to implement new API to ShareX.

**Comment by kvazio** [comment]
I asked them about it on reddit but it doesn't seem like they have anything like an API for ShareX in plans at all https://www.reddit.com/r/gfycat/comments/5yhctl/gfycat_working_on_api_for_sharex/

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/s/gjqpufnb7d8ld5e/chrome_TTTwYuMo4h.png)

This is our email conversation.

**Comment by Jaex** [comment]
#2389
