### ISSUE TITLE
Greenshot Image Editor Configuration Options

### ISSUE THREAD

**Issue by zamarax** [ShareX/ShareX#2349]
Any chance we can get more finite control over Greenshot image editor? One thing they have in their own app is the ability to automatically insert into Microsoft app's such as Outlook, which is a beautiful feature.

**Comment by campbeb** [comment]
There are no plans to merge any additional functionality from Greenshot into the image editor in ShareX.

**Comment by zamarax** [comment]
Is Share-X building their own?

**Comment by campbeb** [comment]
Well, the older version of Greenshot image editor is already included and there is work to duplicate all of that functionality in ShareX proper.
You can try it out by going to Task Settings / Advanced and under General, set UseShareXForAnnotation to True.

**Comment by zamarax** [comment]
​I've now tried that but it's not quite the same, It would be ideal to have
after capture 'open in image editor' annotation, vs the live on screen one.

Good to know that ShareX is incorporating those settings though.​

__
Regards, Corey Zamara
Network Administrator
