### ISSUE TITLE
Retake button [Suggestion]

### ISSUE THREAD

**Issue by shimakazekai** [ShareX/ShareX#2351]
It would be nice if in the menu that pops up after a screenshot there would be a button to retake the screenshot. 
I often mess up the screenshot region for the first time and have to retake and going all the way to the taskbar is a waste of time if a menu pops up right near the mouse.

**Comment by Jaex** [comment]
If you have problem about accidental region selections then check this setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/03/ShareX.vshost_wVLOdPypBZ.png)

**Comment by shimakazekai** [comment]
How do you get to this menu?

**Comment by Jaex** [comment]
It is inside region capture.

**Comment by shimakazekai** [comment]
Ah, it makes taking screenshots a little slower because of extra clicks though.

**Comment by Jaex** [comment]
Retaking screenshot also makes it slower.

**Comment by shimakazekai** [comment]
Haha yes, but it doesn't slow the normal use case, only when really necessary.

**Comment by vatterspun** [comment]
> It would be nice if in the menu that pops up after a screenshot there would be a button to retake the screenshot

I'm confused: if you mess up the screenshot, why not just take another one and discard the first capture?

**Comment by grrinch** [comment]
I know I'm responding to a very old issue/suggestion, but I just came across a need for this exact functionality - retake screenshot.

I would think this isn't included in ShareX yet, so just wanted to leave this comment here for anyone who's looking for it - **ShareX Retake Screenshot is available**!

If you want to retake a screenshot, especially if you took it with rectangle/region option, just go to the main window -> Capture -> Last Region.

![image](https://user-images.githubusercontent.com/5729796/63702978-f450fb00-c81f-11e9-9d8a-3f1d98d34fca.png)

Works like a charm!

Hope it helps :)
