### ISSUE TITLE
[Azure] Set blob content-type headers

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#2352]
These should be handled so that files/blobs are delivered with the correct headers, instead of application/octet-stream
Current Azure Maintainer is @wi5nia 

According to the docs, this should be fixed by adding the `Content-Type` to the header of the `Put Blob` request to the storage container
https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/put-blob
`requestHeaders["Content-Type"] = Helpers.GetMimeType(fileName);`
could be an adequate fix, this also requires adding the HelpersLib to the file

**Comment by wi5nia** [comment]
It's an optional parameter so it can but doesn't have to be this way :) I will add this together with support for custom domain.

**Comment by Scrxtchy** [comment]
Jaex and I have been looking into it with my storage account keys
Adding the headers alone doesn't fix the issue, as it has some complications with the signature

**Comment by Scrxtchy** [comment]
Figured it out
![](https://tenryuu.blob.core.windows.net/astrid/17-03-10_00-31-46-scratch@MAI_mntcUsersScratch.png)
