### ISSUE TITLE
copy screenshot to clipboard without saving?

### ISSUE THREAD

**Issue by PlotTwisted** [ShareX/ShareX#2366]
So I don't know if I can already do this but, I want to copy a screenshot to clipboard without the image saving in screenshot folder like what you can do in lightshot were you can choose whether to save or just copy the image to clipboard and paste it somewhere. Also if I can do google image search the same way as lightshot without having to open search by image and uploading a image? Thank You

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/03/wHFvwROCpk.png)

**Comment by PlotTwisted** [comment]
oh wow I'm dumb sorry I just got ShareX, since I found better than lightshot. Thank You for the really fast responce :)

**Comment by Jaex** [comment]
Also this can allow selection each capture:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/03/ShareX_vpZxHQabvC.png)

**Comment by PlotTwisted** [comment]
oh wow I see, thanks that will come in handy

**Comment by Jaex** [comment]
Google Image search custom uploader: https://github.com/ShareX/CustomUploaders/blob/master/google.com%20(Image%20search).sxcu

**Comment by Jaex** [comment]
Maybe I should add right click entry to open this url:
https://www.google.com/searchbyimage?image_url=<url_here>
Is it how lightshot doing it?

**Comment by PlotTwisted** [comment]
![image](https://cloud.githubusercontent.com/assets/26395450/23881171/21c1b3f8-082f-11e7-9d41-0493fedd9b49.png)
like this

**Comment by Jaex** [comment]
I was asking more technical answer :D 
It must be opening link in your browser.

**Comment by PlotTwisted** [comment]
ye

**Comment by PlotTwisted** [comment]
https://streamable.com/d0t6v

**Comment by Jaex** [comment]
Because there is two way, one is uploading image directly which is not legal without use their api and that api is paid. Another way is uploading image and then opening google image search url with that uploaded url which is legal.

**Comment by PlotTwisted** [comment]
ok

**Comment by PlotTwisted** [comment]
so Im trying to add the custom uploader but its greyed out 
![image](https://cloud.githubusercontent.com/assets/26395450/23881279/030e1b26-0830-11e7-8196-a66a00155d4b.png)

**Comment by PlotTwisted** [comment]
nvm I got it

**Comment by PlotTwisted** [comment]
yep I got it

**Comment by PlotTwisted** [comment]
thank you

**Comment by berkdemir** [comment]
Since @Jaex's answers' pictures are not visible, I still have the same question. I use Sharex a lot and this causes a great mess in my screenshot folder. Is there an option to just copy to clipboard and not save to screenshot folder?

**Comment by PlotTwisted** [comment]
@berkdemir like so
https://user-images.githubusercontent.com/26395450/104691493-5d1a6b00-56d4-11eb-8978-b98c20b5cfa4.mp4
