### ISSUE TITLE
"Upload with ShareX" context menu option broken

### ISSUE THREAD

**Issue by Fowz** [ShareX/ShareX#2370]
Well I have an imgur account and I upload some things there, it was working past 3 days but not anymore.
What happens: when I right click one image and select _Upload with ShareX_ instead of uploading the image the Main Window opens.
Already checked the account validation and configuration.
![20170316 050428](https://cloud.githubusercontent.com/assets/10855150/23987024/0c3a7636-0a06-11e7-97fb-5f75e2e45c9e.png)

**Comment by Jaex** [comment]
Is "After capture tasks -> Upload image to host" selected?

**Comment by WiliTest** [comment]
The upload in context menu was not working.  I disabled and reenabled application settings/integration/ uncheck show "upload with shareX" and it worked.

(I works without selecting the "After capture tasks/Upload image to host")
