### ISSUE TITLE
Azure Authentication Fails when Filename has Non-English Characters

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#2371]
![](https://tenryuu.blob.core.windows.net/astrid/17-03-16_19-09-56-ShareX_-_Error.png)

Seems to include emoji
![](https://tenryuu.blob.core.windows.net/astrid/17-03-17_01-43-47-ShareX_-_Error.png)

**Comment by Scrxtchy** [comment]
URL Encoding these filenames works, but then affects other symbols that are not
![](https://tenryuu.blob.core.windows.net/astrid/17-03-17_05-04-55.png)

**Comment by Scrxtchy** [comment]
@wi5nia Is this able to be investigated?
I could write up a patch myself If I knew which ranges of characters this behaviour affects

**Comment by wi5nia** [comment]
Maybe this will help: https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/Naming-and-Referencing-Containers--Blobs--and-Metadata?redirectedfrom=MSDN

**Comment by Scrxtchy** [comment]
Nah, no good.
What needs to be done is a url encoding of characters, which isn't covered in the article.
Only can tell this had to be done from the XML return error

For example, a file that's uploaded with a name of
`abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 _+-.,!@$%^&();'.png.png` returns
`abcdefghijklmnopqrstuvwxyz%20ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789%20_+-.,!@$%25%5E&amp;();'.png.png`

Which is very inconsistant, most symbols aren't needed to be encoded
`%^&` and whitespace have to be encoded, while many common symbols are not, 
Then any characters that are outside the latin alphabet
Hashes will break the filename completely

**Comment by Scrxtchy** [comment]
🤖🔫👀
