### ISSUE TITLE
Crash during ffmpeg recording

### ISSUE THREAD

**Issue by Mascotte123** [ShareX/ShareX#2376]
1. Pressed shortcut to start recording
2. Pressed stop
3. Error appeared & ShareX crashed

![sharex_2017-03-21_22-18-26](https://cloud.githubusercontent.com/assets/18115558/24171374/7c6276d4-0e84-11e7-8784-9741a9a1026e.png)

**Comment by Jaex** [comment]
Did you tried redownloading FFmpeg from ShareX to get latest version?

**Comment by YasseenDeHerdt** [comment]
Hi, I can't download the FFmpeg from ShareX right now , because company network is blocking it. Is there a direct URL to download from?

**Comment by Jaex** [comment]
https://ffmpeg.zeranoe.com/builds/

**Comment by YasseenDeHerdt** [comment]
Ok, I updated the FFmpeg file and that works. Anyway, this crash occurred but only 1 time in maybe 200 recordings, so maybe not that important then.

**Comment by Jaex** [comment]
You told ShareX crashed but normally it should give .NET exception and not crash instantly.

**Comment by YasseenDeHerdt** [comment]
Yes, it was frozen and I had to shut it with Task Manager.

**Comment by Jaex** [comment]
Did you close that FFmpeg error window?

**Comment by YasseenDeHerdt** [comment]
Yes, that was possible.

**Comment by Jaex** [comment]
If you didn't close that window then you couldn't access other parts of ShareX because it waits for that window to close.
