### ISSUE TITLE
60 FPS gifv for imgur

### ISSUE THREAD

**Issue by MrGoatsy** [ShareX/ShareX#2379]
I would like to select a window to record and have it record at 60 FPS, or at least the ability to set the FPS amount you want instead of the 3 FPS it currently is.

**Comment by Kyokou** [comment]
.gifv **is** .webm

.gif recording caps at 30fps, .webm caps at 60fps. There aren't any "60fps gifs" those are "60fps webm". Which you can totally do with Sharex. Set up FFmpeg as your GIF encoder and record as .webm

http://i.imgur.com/CidC4Ia.png
