### ISSUE TITLE
Rectangle selection incomplete if not performed from bottom left to top right

### ISSUE THREAD

**Issue by woctezuma** [ShareX/ShareX#2380]
I like to capture a rectangular region which I select with my mouse. So I like to press `Ctrl+PrintScreen` and then proceed to draw the rectangle. This works fine most of the time, however I have noticed the selection is often wrong due to what looks like a mouse bug. It seems the problem happens if I do the selection in any manner **but** from bottom left-corner to top right-corner.

[Website used for the example](https://www.humblebundle.com/books/history-book-bundle)

[Example of wrong rectangular selection](http://i.imgur.com/wfMJ7wL.png)

[What I want](http://i.imgur.com/kCDgs8q.png)

Does anyone else notice this issue? Or is it my mouse?

**Comment by duianto** [comment]
@woctezuma When reporting issues, don't forget to include your operating system and application (ShareX) version, that makes it easier to narrow down where the issue could be occurring.

Everything in the rectangle gets captured, for me in windows 10. It doesn't matter from which corner the rectangle is drawn.

#### System Info
Windows 10 Version 1607 (OS Build 14393.953)
ShareX v11.6.0

**Comment by woctezuma** [comment]
I have thrown my mouse away and it works now. Sorry.
