### ISSUE TITLE
Uploading videos via Google Photos

### ISSUE THREAD

**Issue by McoreD** [ShareX/ShareX#2381]
According to https://developers.google.com/picasa-web/docs/3.0/developers_guide_protocol#PostVideo one could use supported MIME type and upload videos the same way as photos.

Calling all developers around the world to have Google Photos in ShareX support uploading videos.

**Comment by DrW3b** [comment]
This feature will be implemented?

**Comment by jareboomafoo** [comment]
It would be great to use the unlimited storage in google photos for screen sharing clips.

**Comment by panthersdude2001** [comment]
With 13.0.2, you can now upload videos with Google Photos.
First, you must go to Task Settings and go to Uploader Filters and select Google Photos.
Type in the video format, such as .wmv or .mp4, and then press add.
When you upload the video, it will go right to photos.
