### ISSUE TITLE
ImageEditor: crash in Greenshot (reproducible)

### ISSUE THREAD

**Issue by Mascotte123** [ShareX/ShareX#2383]
1. Go to ImageEditor
2. Enter "http://i.imgur.com/iMXn4fD.png"
3. Open in Greenshot
4. Click 'Save'

![sharex_2017-03-25_13-22-04](https://cloud.githubusercontent.com/assets/18115558/24322148/0a8ccdde-115e-11e7-9527-6142200f4804.png)

**Comment by campbeb** [comment]
I believe this is caused due to a permissions issue.
When you open the URL, Windows downloads the image to a temp folder (for me, it is C:\Users\debugit\AppData\Local\Microsoft\Windows\INetCache\IE\1ZPIXTMU\iMXn4fD.png).
When I try to Save, ShareX doesn't have permission to write to that folder, so that crash occurs. If you use Save As and choose a different folder, there is no crash.

I get a slightly different call stack:
```
 	[External Code]	
	ShareX.HelpersLib.dll!ShareX.HelpersLib.ImageHelpers.SaveImage(System.Drawing.Image img, string filePath) Line 1454	C#
 	ShareX.exe!ShareX.TaskHelpers.AnnotateImageUsingGreenshot.AnonymousMethod__5() Line 853	C#
 	ShareX.HelpersLib.dll!ShareX.HelpersLib.Extensions.InvokeSafe(System.Windows.Forms.Control control, System.Action action) Line 340	C#
 	ShareX.exe!ShareX.TaskHelpers.AnnotateImageUsingGreenshot.AnonymousMethod__40_4(System.Drawing.Image x, string filePath) Line 853	C#
 	Greenshot.ImageEditor.dll!Greenshot.ImageEditorForm.OnImageSaveRequested() Line 1388	C#
 	Greenshot.ImageEditor.dll!Greenshot.ImageEditorForm.btnSave_Click(object sender, System.EventArgs e) Line 1466	C#
 	[External Code]	
 	Greenshot.ImageEditor.dll!Greenshot.Controls.ToolStripEx.WndProc(ref System.Windows.Forms.Message m) Line 64	C#
 	[External Code]	
 	ShareX.exe!ShareX.TaskHelpers.AnnotateImageUsingGreenshot(System.Drawing.Image img, string imgPath, bool allowSave, string configPath, System.Action<System.Drawing.Image> clipboardCopyRequested, System.Action<System.Drawing.Image> imageUploadRequested, System.Action<System.Drawing.Image, string> imageSaveRequested, System.Func<System.Drawing.Image, string, string> imageSaveAsRequested, System.Action<System.Drawing.Image> printImageRequested) Line 885	C#
 	ShareX.exe!ShareX.TaskHelpers.AnnotateImageUsingGreenshot(System.Drawing.Image img, string imgPath) Line 850	C#
 	ShareX.exe!ShareX.TaskHelpers.AnnotateImage(string filePath, ShareX.TaskSettings taskSettings) Line 788	C#
 	ShareX.exe!ShareX.TaskHelpers.AnnotateImage(ShareX.TaskSettings taskSettings) Line 772	C#
 	ShareX.exe!ShareX.MainForm.tsmiImageEditor_Click(object sender, System.EventArgs e) Line 1397	C#
 	[External Code]	
 	ShareX.exe!ShareX.Program.Run() Line 357	C#
 	ShareX.exe!ShareX.Program.Main(string[] args) Line 311	C#
 	[External Code]	

```

**Comment by YasseenDeHerdt** [comment]
Yes, you can be right. If I choose "Save as" and choose the same folder, Windows says "This file has the property Read-Only. Try again with a different file name." and a different file name works.

**Comment by YasseenDeHerdt** [comment]
In case the image loaded into the ImageEditor is from the web, it can be saved in the default screenshot folder (instead of a temp folder) to prevent the problem ?

**Comment by campbeb** [comment]
It might be difficult to determine as ShareX doesn't know the image is from the web. Windows downloads the image and gives the local hard drive path to ShareX.
ShareX might be better able to recognize that it can't save to the file where it is located on the hard drive.
