### ISSUE TITLE
Disable Update Requests

### ISSUE THREAD

**Issue by GWSB** [ShareX/ShareX#2384]
They seem to pop up almost daily. I'm not a super user. I'm perfectly content with the features I currently have and the state of the program. How do I turn these pop ups off? Or change them to cycle monthly?

I found #1518 but the solution was given with what is now a broken link.

Thanks!

**Comment by YisroelAdler** [comment]
In Application Settings>Advanced change the value for **AutoCheckUpdate** from True to **False**

![sharex_2017-03-26_02-41-09](https://cloud.githubusercontent.com/assets/7387839/24329225/e3c77c74-11cd-11e7-91dd-0bfdef11b0a2.png)

**Comment by Jaex** [comment]
He probably have this issue: #1796
