### ISSUE TITLE
Link to raw file for Seafile uploads

### ISSUE THREAD

**Issue by Battleroid** [ShareX/ShareX#2385]
I use the Seafile integration quite heavily, but was wondering if a toggle could be added to link directly to the file.

**Comment by Feld0** [comment]
+1 - I'd find this really useful. A similar option is already available on the Dropbox and Google Drive destination types. All it needs to do is append `?dl=1` to the shareable URL that the Seafile API returns.

**Comment by Battleroid** [comment]
bump

**Comment by Jaex** [comment]
Added by #4786
