### ISSUE TITLE
Picture Preview on Dual Monitor PC

### ISSUE THREAD

**Issue by YisroelTech** [ShareX/ShareX#2387]
When clicking on the preview of a picture in the right side pane in ShareX you get a full-screen preview. When doing so on a dual monitor PC the fullscreen preview will always go on the main monitor.

I would suggest, if possible, to have the preview on the monitor the ShareX windows is open on.

**Comment by individuell** [comment]
similar issue here, but it's not even opening on my main monitor- but on my 4th monitor which is usually turned off (TV).

It would be awesome if it would open the image on the same monitor where I double-clicked a screenshot inside the "Image History" window.

**Comment by alexroston** [comment]
same issue here. has there been any update to fix this yet?
