### ISSUE TITLE
Got an issue with login to oneDrive

### ISSUE THREAD

**Issue by ferylukacs** [ShareX/ShareX#2392]
I have a company one drive account, but has no "login.live" account associated with it, and when i try to set it up for a OneDrive Open Auth page, it redirects me to the live.login page instead of the one drive login page.

Is there a workaround? thanks

**Comment by vatterspun** [comment]
This is probably hard for the dev to reproduce because he can't get a OneDrive for business account without actually purchasing it.

**Comment by Jaex** [comment]
Duplicate of #1853
