### ISSUE TITLE
500 error when uploading images

### ISSUE THREAD

**Issue by ItsJord** [ShareX/ShareX#2393]
Since ~3 days ago I'm getting 500 errors when I try to screenshot any area and let ShareX upload it to Imgur. Sometimes it works, sometimes it doesn't, same when I use the built-in testing feature in the application. When it fails, I get the following log:

> Message:
> De externe server heeft een fout geretourneerd: (500) Interne serverfout.
> The external server has returned an error: (500) Internal server error.
> 
> Request URL:
> https://api.imgur.com/3/image
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Anything I can do about this? My internet connection is perfectly fine and ShareX is up to date as far as I'm aware.

**Comment by Jaex** [comment]
Most of the time internal server error means problem to do with server and not ShareX.
