### ISSUE TITLE
Greenshot highlighter is zooming in Sharex 11.6

### ISSUE THREAD

**Issue by Zyphon30** [ShareX/ShareX#2394]
After I recently updated to Sharex 11.;6; when I am trying to edit a captured image in Greenshot. The highlight option no longer works correctly and instead tries to zoom the image when you draw a box around a region.

I really love Sharex, please fix the highlighter option as it is such a useful features.

Thanks.

**Comment by campbeb** [comment]
What version of Windows are you using? What is your monitor resolution and do you have any scaling set?
Can you attach a picture or video of what happens? I can't reproduce it.

**Comment by campbeb** [comment]
@Zyphon30 One of the settings in Greenshot has been changed.
After clicking highlight on left side, check the menu in the top as shown in this picture:
![2017-04-10_16-24-20](https://cloud.githubusercontent.com/assets/1089399/24880955/50ef54fa-1e0a-11e7-93d8-86fed625ce83.png)

You probably have it set to Magnify.
