### ISSUE TITLE
ShareX Crash in IOException: Not enough disc space available

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#2395]
Take a screenshot or start screen recording while no disk space available on C: drive.

![sharex_2017-03-30_17-11-52](https://cloud.githubusercontent.com/assets/18115558/24511400/330b2b0e-156c-11e7-8f45-3c68e6de034e.png)

**Comment by Jaex** [comment]
So what is problem?

**Comment by YasseenDeHerdt** [comment]
Can it propose to save in different location in this case? I lost valuable recording.

**Comment by Jaex** [comment]
Clean your hard drive or buy bigger hard drive if you don't wanna lose valuable recording.
