### ISSUE TITLE
Screen recording to Gyfcat gave me a used gyfcat link?

### ISSUE THREAD

**Issue by LBUlises** [ShareX/ShareX#2399]
I know it's April 1st today so I assume this might be a joke from ShareX or Gyfcat but this happened just a couple minutes ago:

I recorded [this](https://gfycat.com/HairyPerfectDragon) video (turned into a gif through the gyfcat website directly now, not ShareX) and it spit out [this](https://gfycat.com/PeriodicGrotesqueBlackbear) link. (NSFW-ish)

I have the logs to prove it:
https://pastebin.com/pt4deCdx

It even appears under my [recent links](https://i.imgur.com/MwsKMMa.png)

Also [here ](https://i.imgur.com/BVMjoL6.png)are the original screen recording details (the time/date match with logs)

Was this a bug or just a April Fools joke?

**Comment by Jaex** [comment]
We don't know why Gfycat returns used links but next ShareX version gonna use latest Gfycat API, maybe there won't be issue with it.
