### ISSUE TITLE
PrintScreen button stops working randomly

### ISSUE THREAD

**Issue by pointcache** [ShareX/ShareX#2403]
It works in some programs, in others refuses
doesnt work in:
* visual studio
* unity3d
* task manager
works in all the rest (browsers, photoshop, discord..)

**Comment by TheAdventist** [comment]
Are there in those 3 apps an hotkey already assigned to the PrtScrn button?

**Comment by pointcache** [comment]
Nope. None of them has any functionality like that.

**Comment by Scrxtchy** [comment]
I have this problem sometimes too
Try running ShareX with elevated permissions and see if it helps (this means you cannot drag-drop into sharex though)

My workaround is to have a different window focused (or click the desktop) and capture the window using the rectangle region (window) tool

**Comment by pointcache** [comment]
fixed with latest update, thanks guys
