### ISSUE TITLE
Request - Latex To Png

### ISSUE THREAD

**Issue by Vastrix** [ShareX/ShareX#2404]
Bit of a nerdy request.. :p 

Would you be so kind to add a latex editor (the mere basics) able to convert to a png? :)
It'd fit well under "tools" ;)

something like:
![Example](https://puu.sh/v7LDa/fd874a769e.png)
Maybe add some sexy options as well like bold, font color etc?

Thanks anways.

**Comment by Jaex** [comment]
This is very personal request and probably only you gonna be using it and not to mention it is nothing to do with ShareX anyway therefore I'm not planning to add it. But also it would require external library for rendering (if there is one) and I prefer to keep library dependency to minimum.

**Comment by Vastrix** [comment]
@Jaex 
_This is very personal request and probably only you gonna be using it_
A lot of College students use Latex..

_it is nothing to do with ShareX anyway_
I believe this has more to do with shareX (capture/img share software) than The Hash Check tool which currently resides under "Tools"'

But yea, I ofc accept your decision.. :/

**Comment by Jaex** [comment]
Everytime I tell "it is nothing to do with ShareX" I know that reply gonna include response listing tools from ShareX and again same thing happened. If I accepted every single like this request then that tool menu would have atleast 30 more tools there...

**Comment by Vastrix** [comment]
I know, maybe then just say something like:

"Sorry but the currently my mind is not set on adding even more 3th party dependencies.
Also, we've gotten a LOT of tools request lately so it's a bit crowded atm (concerning tools request)
I hope you understand, cheers :)"

Instead of saying that no one will use it (again, a lot of students use latex) or that it has nothing to do with img capture/share software (Creating **images** from text to make that text more readable for the people who you'll **share** it with..)


But again, like I said, I totally accept your decision :)

**Comment by Jaex** [comment]
English is very difficult. I literally edited my previous message +10 times to fix stuffs.

**Comment by Vastrix** [comment]
That's ok, I understand ;)
