### ISSUE TITLE
Scale issue on Greenshot TornEdge and DropShadow 

### ISSUE THREAD

**Issue by dtgeorge** [ShareX/ShareX#2406]
http://i.imgur.com/WUrK1gA.png
http://i.imgur.com/OVMruA1.png

Windows 10, 125% global scale, 1920*1080, 14" monitor

**Comment by campbeb** [comment]
To clarify, the issue is in the dialog box that pops up, not in the image effect.

**Comment by dtgeorge** [comment]
Yes, sure!
