### ISSUE TITLE
New feature suggested

### ISSUE THREAD

**Issue by BurningRaptor** [ShareX/ShareX#2410]
Hope to add a feature that allows users to rename the image in ShareX without opening explorer

**Comment by mancevd** [comment]
You can change the "After capture tasks" to "Save image file to as..."

**Comment by BurningRaptor** [comment]
@mancevd Well this is a good idea. But I don't need to rename eveey screenshot I take.

**Comment by Jaex** [comment]
I can suggest "Open -> Folder" which opens Windows Explorer with file selected that way you can easily rename.
