### ISSUE TITLE
Add a 'Cancel' button to OCR window

### ISSUE THREAD

**Issue by Leloiandudu** [ShareX/ShareX#2415]
I often OCR text in different languages, and ShareX remembers the last used language and starts the OCR right away which is inconvenient in my case: I have to wait for the results to show up in order to switch the language and to click 'OCR' again. It would be nice to have a 'Cancel' button that stops the OCR process to allow the user to change the language.
![image](https://cloud.githubusercontent.com/assets/2293329/24780100/ceeaa28a-1b88-11e7-915d-71224c4f24e6.png)

**Comment by Jaex** [comment]
#1749
