### ISSUE TITLE
Jittery screen recordings due to higher refresh rate

### ISSUE THREAD

**Issue by SavvyKat** [ShareX/ShareX#2417]
I have been experiencing very jittery screen recordings for a little while now and I realized that the issue had started when I had gotten a new monitor that supports 144hz. I then tried to take recordings with 144hz and 60hz and found that recording in 60hz worked perfectly. 

[here is the clip I took at 60hz](https://streamable.com/4fw1b)

[then 144hz](https://streamable.com/6hxbp).

I'm hoping this can be resolved hopefully, or if there is something I can do besides having to switch refresh rates every time.

**Comment by tambry** [comment]
Both links are the same.

**Comment by SavvyKat** [comment]
Never realized, just fixed the links. Thank you.
