### ISSUE TITLE
Many Issues founded in GIF capture

### ISSUE THREAD

**Issue by tamashii** [ShareX/ShareX#2419]
If you first time run GIF capture, it will literally download a file called  ffmpeg.7z,
and then if you click the cancel button when it's download in the half way (I canceled it because it's connection timeout in the PRC, see it below), the capture will not canceled, and prompt ffmpeg errror.
Then run GIF capture again, attempted do download the ffmpeg.7z again, and caught an exception:

> System.IO.IOException: File "C:\Users\Tamashii\AppData\Local\Temp\ShareX\ffmpeg.7z" is using by another task, therefore current task can not access this file.

And restart the software, this problem may solved. However if you run the GIF capture again, it will appear again.

This problem maybe because the file stream of ffmpeg.7z not closed when cancel the download.
___
Then the connection timeout problem of ffmpeg.7z. Can anybody actually tell me what kind of url is actually used for download ? I will try if or not it works in PRC.

**Comment by Scrxtchy** [comment]
>Can anybody actually tell me what kind of url is actually used for download

http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z

**Comment by techxpert** [comment]
Let me check

**Comment by tamashii** [comment]
I dunno why but this issue has been solved.
