### ISSUE TITLE
I have to hit enter to upload? 

### ISSUE THREAD

**Issue by dudeedud4** [ShareX/ShareX#2421]
Sorry for the crappy title but it's as described. Previously all I had to do to upload a screenshot with selection/region capture is just hit my hotkeys, draw the selection while hilding my mouse1 and then let go and it uploads it automatically. Now I have to hit enter after letting go of the mouse1 key. Any way to make not hitting enter the option to upload? I've searched through the settings and issues but I don't see it. I may just be missing it so sorry if it's been reported or asked before.

**Comment by Jaex** [comment]
Uncheck this:

![](https://jaex.getsharex.com/2017/04/ShareX_MSiSTaJkW1.png)
