### ISSUE TITLE
Search with Image

### ISSUE THREAD

**Issue by clementine123** [ShareX/ShareX#2422]
I have checked out this software and found a must have feature missing. After a screenshot is taken, can you provide a functionality to search with the image on some popular image search sites like Google and TinyEye?

This is available in other screenshot extension for Chrome called "Lightshot".

**Comment by Scrxtchy** [comment]
Google Reverse Image Search is already implemented
4a2afc4d427ca6de86fc16b13fc3c6d7e2f32b53
