### ISSUE TITLE
Move "Open in image editor" to top

### ISSUE THREAD

**Issue by Scrumplex** [ShareX/ShareX#2424]
I think, that the task "Open in image editor" should be moved to top, or at least over "Add image effects / watermark" because if you crop the image in the editor it will also remove the watermark.

**Comment by Jaex** [comment]
There is reason in that order. In your purpose it can be better but there is other purposes which this order makes more sense. For example most people would prefer their annotation to be top of effects. And no I can't make after capture tasks orders changeable it won't be possible. There is many tasks there actually depend on order to work.
