### ISSUE TITLE
Add support for Rebrandly (full API available)

### ISSUE THREAD

**Issue by xrimayyh** [ShareX/ShareX#2426]
I've been trying to add a Custom Uploader to ShareX via:

`Destinations > Destination Settings > Custom Uploaders > Import > From File`

I've tried importing the various code into a text file with a .SXCU extension to no avail.

I'm trying to add support for Rebrandly (a URL shortener); a full API is [available here](https://developers.rebrandly.com/docs/get-started).

Is anybody able to do this? Thanks

**Comment by aph3rson** [comment]
The documentation for CUs seems to go under the impression that the contents of our POST is whatever we're uploading, and only that.

I put something together, but I have no idea if it works (uses JsonPath syntax, which is used in parsing the output). You can try it, replacing the API_KEY with your own:

```json
{
  "Name": "Rebrandly",
  "DestinationType": "URLShortener",
  "RequestType": "POST",
  "RequestURL": "https://api.rebrandly.com/v1/links",
  "Arguments": {
    "$json:destination$": "$input$",
    "$json:domain.fullName$": "rebrand.ly"
  },
  "Headers": {
    "Content-Type": "application/json",
    "apikey": "YOUR_API_KEY"
  },
  "ResponseType": "Text",
  "URL": "$json:shortUrl$"
}
```

If it does work, let me know and I can spin up a PR for it to go into the repo.

**Comment by Jaex** [comment]
ShareX custom uploaders not supports json request body. It is either multi-part arguments or query arguments.

**Comment by aph3rson** [comment]
It seems like there's a few issues out there that are looking to use APIs that use a POST request with a JSON  body. Perhaps an issue for implementing that?

**Comment by Canettieri** [comment]
I use Rebrandly and ShareX for marketing works. It will be nice have it in ShareX. Hope it will be added in a future update!

**Comment by Jaex** [comment]
I'm adding JSON request support to custom uploader system now, with it Rebrandly url shortening possible now:

![](https://jaex.getsharex.com/2018/11/ShareX_daCP61DipD.png)

**Comment by aph3rson** [comment]
@Jaex, when will the custom uploaded support be in the release build? Would be _really_ nice for some internal projects I have.

**Comment by Jaex** [comment]
You can use dev build: https://getsharex.com/docs/dev-builds

**Comment by Jaex** [comment]
Uploaded custom uploader of it to here: https://github.com/ShareX/CustomUploaders/blob/master/rebrandly.com.sxcu

**Comment by godgutten** [comment]
How can i use a costom rebrandly domain?

**Comment by srnyx** [comment]
> How can i use a costom rebrandly domain?

@Jaex I have the same question

**Comment by Johnnycyan** [comment]
To use a custom domain replace the body with 
```
{
  "destination": "$input$",
  "domain": {
    "id": "DOMAIN-ID",
    "ref": "/domains/DOMAIN-ID"
  }
}
```
![image](https://user-images.githubusercontent.com/24556317/139715610-330efb4e-8f6e-49d0-a5fa-3a09c1b0bf57.png)
