### ISSUE TITLE
Region capture failure

### ISSUE THREAD

**Issue by sergeevabc** [ShareX/ShareX#2431]
1. Launch some app that throws error ([example][1]).
2. Use ShareX 11.7 to make region capture.
3. Window’s dimensions are detected upon hover, yet window in not captured upon click.

Edit: same failure whether multi-region mode is on or off.

![](https://vgy.me/xwG5Z0.png)

[1]: https://transfer.sh/yh1qs/MillerBroken.7z

**Comment by Jaex** [comment]
Message box window there is top most and stays in front of region capture window.

**Comment by Jaex** [comment]
You can use <kbd>alt + printscreen</kbd> hotkey to capture that window.
