### ISSUE TITLE
Pressing Enter in history resets the view, should maybe open entry instead.

### ISSUE THREAD

**Issue by EhsanKia** [ShareX/ShareX#2433]
I'm guessing it may be a result of #532, but generally, my first instinct when using the history page is to press Enter after I select an entry, and I expected it to open the entry I have selected. Instead, it just resets the view, making me lose the entry I had selected and spent a long time finding...

I never touched the filters or any of the textboxes, all I do is scroll way down, select an entry and press Enter, and it just unselects my entry and scrolls back to the start of the list. Very unintuitive.

**Comment by Jaex** [comment]
You are right that pull request broken it by making filter button accept button, so enter triggers it.

**Comment by Jaex** [comment]
You are right that pull request (#534) broken it by making filter button accept button, so enter triggers it.
