### ISSUE TITLE
Suggestion: Allow uploading videos to video hosting and unknown format to other file sharing site.

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#2434]
### Issue:
Currently we have video hosting 'Gfycat' under 'File uploader' destination:

![image](https://cloud.githubusercontent.com/assets/3248782/25077687/3b9a7e3c-22fa-11e7-8469-6876be457e09.png)

I have it set to Gfycat, because I record .webm with ShareX and upload it to Gfycat. 

But file uploader take any formats that are not images, let it be an archive, an .exe or a video. According to the above image, if I try to upload miscellaneous file format such as .zip, .exe, etc, it will attempt to upload on Gfycat, a video hosting site, which will inevitable fail.

### Suggestion:
* Separate video option for .webm, .mp4, .wmv, etc and allow them options to choose what site to use to upload their video.
* And new option for miscellaneous (unknown/unrecognized) file format and allow users to choose what site to upload these files, typically a file sharing hosting like http://put.re/

Thank you for your consideration.

**Comment by Jaex** [comment]
Check this setting:

![](https://jaex.getsharex.com/2017/04/ShareX_iI1J00C1Ar.png)

**Comment by dmxt** [comment]
@Jaex Thank you, problem solved!

**Comment by rainbowjose** [comment]
Damn, sorry for my stupidity. Thank you!
