### ISSUE TITLE
Make Region Capture Rectangle Animations Configurable

### ISSUE THREAD

**Issue by RagingCactus** [ShareX/ShareX#2435]
The new update introduced animations for the selection rectangles in region capture mode. I find the "transitioning" between rectangles to be very distracting and liked the previous, snappy behaviour a lot more.
Would you mind implementing a toggle for the animations, maybe in the advanced settings?

Thank you for creating this awesome tool :)

**Comment by Jaex** [comment]
I will add it to region capture toolbar options menu.
