### ISSUE TITLE
GreenShot Image Editor Broken in 11.7

### ISSUE THREAD

**Issue by zamarax** [ShareX/ShareX#2436]
Just upgraded to the latest version and I noticed that GreenShot Image Editor is no longer working for annotation after a capture.

**Comment by Jaex** [comment]
It working in my test:

![](https://jaex.getsharex.com/2017/04/ShareX_aFHyGjUgdW.png)

**Comment by fernandoslemos** [comment]
In last version you have to disable annotation to work with greenshot editor 

![2017-04-17_15-13-14](https://cloud.githubusercontent.com/assets/27688663/25091359/9f65d494-2380-11e7-9746-a174e73cb320.png)

But i have noted that with sharex annotation if i active After Capture tasks\Annotate image, it dont work after capture dont open editor

**Comment by zamarax** [comment]
Thanks, Disabling 'UseShareXForAnnotation' was exactly it.

**Comment by Jaex** [comment]
You told you were upgraded, that setting is enabled only for new installations not for upgrades. Also you told it was not working like there was error in it. You didn't told anything else was opening.

**Comment by zamarax** [comment]
Sure, but I had made that change a long while ago and only on this update did it actually affect the usability.

Perhaps a warning or a note in the changelog?

**Comment by Jaex** [comment]
I was already wrote note about it in changelog?

**Comment by Jaex** [comment]
Next version gonna have windowed annotator:

![](https://jaex.getsharex.com/2017/10/DaFwG7lavh.png)

**Comment by ze-better** [comment]
A windowed ShareX annotator would be a very welcome functionality!

**Comment by Minidoracat** [comment]
Can't find UseShareXForAnnotation
