### ISSUE TITLE
11.7 default screen recording is mp4 and not GIF

### ISSUE THREAD

**Issue by Zireael07** [ShareX/ShareX#2437]
How do I go back to the old behavior? I tried setting up a new hotkey and task, and it still captures mp4.

To capture gif, I need to manually select 'screen capture (GIF)' option.

**Comment by Jaex** [comment]
Add hotkey like this:

![](https://jaex.getsharex.com/2017/04/ShareX_oXsc6kX1Hl.png)

**Comment by Zireael07** [comment]
Thanks.

Curiously enough no change regarding 'screen recording' vs 'screen recording (GIF)' was mentioned in the changelog (and I updated straight from 11.6 without changing any options or the like). Side effect of something else you did?

**Comment by Jaex** [comment]
That hotkey was added years ago. You were selected GIF from here instead?

![](https://jaex.getsharex.com/2017/04/ShareX_1bM5h0H66C.png)

**Comment by Zireael07** [comment]
Yes, that's what was set there. As I said, I made no changes apart from updating and suddenly went from making gifs to mp4.

**Comment by Jaex** [comment]
Look like that option is broken. Because I was using hotkey method of GIF recording, I couldn't notice it when testing GIF recording.

**Comment by Bodomi** [comment]
Are you gonna push this update to Steam or do I have to download it here?
