### ISSUE TITLE
Uploading to S3 no longer works after 11.7 update

### ISSUE THREAD

**Issue by cc-sam** [ShareX/ShareX#2440]
After upgrading to 11.7 my team is unable to upload to our S3 bucket. Downgrading to 11.6 allows uploads to work normally again.

[sharex-s3-errors.txt](https://github.com/ShareX/ShareX/files/926173/sharex-s3-errors.txt)

![image](https://cloud.githubusercontent.com/assets/12958565/25096926/32dd9f42-2357-11e7-8b59-b9d87254ff5c.png)

**Comment by Kaosheaven** [comment]
try ticking the use style path bucket
thats what i did to get mine working

**Comment by cc-sam** [comment]
I can confirm with the "Use path style request" uploading works correctly, however I'm using a custom domain without SSL or Amazon CloudFront. Based on the URL preview ShareX displays HTTPS is now prefixed for all generated URLs and I don't see a way to disable HTTPS.

I'm looking into creating a cert via Amazon Certificate Manager. Ideally there should be an option for no SSL unless perhaps the new S3 integration requires it.

**Comment by Kaosheaven** [comment]
I am using a custom domain as well and the url has ssl through cloudflaire but i think it was detecting ssl from amazon itself not my cloudflaire domain

**Comment by Jaex** [comment]
It allows using `http://` only when it is missing, it using `https://`.

**Comment by Jaex** [comment]
Now I opened bucket in "US West (N. California)" region and image uploaded without problem. I was also tested 3 different regions before and there is no error in my tests. So not sure what causing problem in your side.

**Comment by cc-sam** [comment]
Got it, thanks Jaex

In conclusion: When using a custom domain name with no protocol specified in ShareX 11.6 the generated URL would default to HTTP. With version 11.7 it defaults to HTTPS which means unless you have an SSL cert installed via Amazon CloudFront it will give an error.

The solution is simply defining the URL protocol to HTTP, so it doesn't default to HTTPS.

![image](https://cloud.githubusercontent.com/assets/12958565/25144696/a263d328-2423-11e7-8c5c-23d4208952a9.png)

Thanks

**Comment by Jaex** [comment]
You had SSL error on upload. But custom domain never used on request. It is only used when generating output URL string. So your problem was not to do with it.

**Comment by Jaex** [comment]
#2451 according to here dot in bucket name causing this problem. Was your bucket had dot?
