### ISSUE TITLE
Unable to edit image in the latest ShareX

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ShareX/ShareX#2441]
After updating to the latest version of ShareX, Im unable to right click capture image and choose edit. The edit image option is gone.

If you have removed it, please bring it back. It is super useful.

Thanks.

**Comment by syaifulnizamyahya** [comment]
Installing previous version brings back the edit image option. https://github.com/ShareX/ShareX/releases/tag/v11.6.0

**Comment by Jaex** [comment]
You can use "Annotate image" option instead.
