### ISSUE TITLE
Hotkeys not working in certain apps.

### ISSUE THREAD

**Issue by pointcache** [ShareX/ShareX#2442]
Once again, after last update it worked for couple of seconds, not anymore.
In Visual Studio, Unity engine, Task Manager 
YOUR PROGRAM HOTKEY PRINT SCREEN DOESNT WORK
and it was properly setup and works in other apps.

**Comment by Jaex** [comment]
Hotkey system handled by Windows, so after ShareX register specific hotkey, if Windows not lets ShareX know of hotkey press then what ShareX supposed to do about it?

**Comment by pointcache** [comment]
Why then it works in Lightshot and other apps?
