### ISSUE TITLE
Blue loading line under toolbox for Capture Region

### ISSUE THREAD

**Issue by milosivanovic** [ShareX/ShareX#2443]
In 11.7 a new feature seems to have been added: when running Capture Region, a toolbox/toolbar appears at the top of the screen. There is an annoying blue loading line that dissipates outwards underneath it, and it animates like this every single time as if I didn't realise it was there the first time.

Is there an option to disable this, and if not, could one please be added?

**Comment by Jaex** [comment]
I added option for it yesterday but it gonna also disable region animation. Because I was named it "Enable animations".
