### ISSUE TITLE
Marching ants animation around capture regions

### ISSUE THREAD

**Issue by milosivanovic** [ShareX/ShareX#2444]
In version 11.7, the marching ants around capture regions are being animated slowly instead of instantly selecting the region. In short, it reduces the perceived responsiveness of the application and is also distracting to the eye when moving around lots of possible capture regions within a window.

Could an option to revert the behaviour to instant detection/selection of capture regions like in the previous version please be added?

**Comment by Jaex** [comment]
#2435
