### ISSUE TITLE
Add new aftercapture task: Annotate with ShareX annotation mode

### ISSUE THREAD

**Issue by servint** [ShareX/ShareX#2446]
Hi. Will be nice to see the 'Annotate with ShareX annotation mode' option available in Aftercapture menu. So after the initial capture the sharex annotation mode is opened automatically. I know that all annotation tools are available during initial capture, but sometimes you want to recheck the image for missing annotation before uploading. 

If you don't need annotations is better to just hit enter rather than doing recapture with reannotation. 
Thanks!

**Comment by BytewaveMLP** [comment]
Does opening the image in the editor not suffice? That's how I usually add my annotations.

**Comment by Jaex** [comment]
You can right click already captured image in list and select annotate image:

![](https://jaex.getsharex.com/2017/04/ShareX_8OEfuzFYVa.png)

**Comment by servint** [comment]
BytewaveMLP, checking 'annotate image' in aftercapture tasks does nothing for me. Sharex annotate mode does not open. 

Jaex, thanks for pointing this out.

**Comment by BytewaveMLP** [comment]
@servint That's odd. It works for me; the Greenshot editor opens before every upload. Sounds like an issue on your end.

**Comment by servint** [comment]
You were not reading carefully. I am talking about ShareX annotation mode, not about Greenshot editor which is working just fine for me. :)

**Comment by BytewaveMLP** [comment]
Are they not similar, though? Annotation mode has the same tools, just in a different view. Unless there's some kind of hidden feature I haven't seen yet.

Right-clicking an image in your history just opens the Greenshot editor, so...

**Comment by servint** [comment]
Yes, they are pretty similar. But it's always better to have your own implementation of functionality rather than using something 3rd party. It's my opinion. 

P.S - and I like ShareX annotation mode way more than Greenshot's editor ))

**Comment by Jaex** [comment]
So your issue is actually this: #2438

**Comment by BytewaveMLP** [comment]
Looking back on this, I wasn't aware @Jaex had implemented a ShareX homebrew annotation mode (which feels so nice, especially being sued to region capture!). Perhaps it helps to be up to date on the latest features before I say anything. :P

**Comment by xueyayang** [comment]
I read the #2438.  It's exactly what the function i want:
1 capture the region  I am interesting
2 mark up on the result.
3 paste the modified picture to somewhere,  word, excel, etc.

I think this is more natural way of capturing and annotating.  If the first two steps was reversed, I found i cannot focus the contents.  

In fact,  in Firefox,  the 'easy screenshot' button on the right-up corners does exactly like this.
Will u be so kind to enable open annotate windows in capture-region mode?

> So your issue (which is not actually issue) is actually this: #2438

**Comment by Jaex** [comment]
I can add option to enable annotation in region capture but it looks weird than after close region capture another region capture opens in editor mode.

**Comment by Fredrik-G** [comment]
I agree with @xueyayang that this is a good feature and something I really want. 
@Jaex can you not make that possible via an option or something?

**Comment by Jaex** [comment]
Gonna write my solution to base issue: #2438
