### ISSUE TITLE
Automatic "use path style request"

### ISSUE THREAD

**Issue by hclewk** [ShareX/ShareX#2451]
Uploading to Amazon S3 broke for me with the 11.7 update. The issue is that my domain name had a dot in it, which breaks the default ssl used when making a request to [bucket].s3.amazonaws.com. If my bucket was named "example.com", then the request to amazon would be https://example.com.s3.amazonaws.com. Amazon has a wildcard for *.s3.amazonaws.com, which works for buckets without dots in them, but by adding the dot, the request falls outside of that scope.

Took me half an hour to figure out why my s3 uploads were suddenly failing. Checking the "Use path style request" box fixes this issue, but that option should be automatically checked if the bucket name has a dot in it. Are there other reasons this check box exists? If there aren't, the check box should go away, and it should just determine whether or not to use "path style" with a simple if statement.

![image](https://cloud.githubusercontent.com/assets/1243396/25230629/4c0e1c2c-259a-11e7-9b33-eac96380ba02.png)

**Comment by Jaex** [comment]
I wonder all other people reported this issue such as in here #2440 had dot in their bucket name too. Because I couldn't reproduce their problem and was not sure how path style could resolve their SSL error. Now it makes sense.

I will make that checkbox selected by default then.

**Comment by cc-sam** [comment]
(I do have a dot in my bucket name.)

It's also worth mentioning any S3 bucket intended to be used for a custom domain (not Amazon subdomain) is going to have a dot since it's a requirement the bucket name matches the domain name.

http://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html#root-domain-walkthrough-s3-tasks

> The bucket names must match the names of the website that you are hosting. For example, to host your example.com website on Amazon S3, you would create a bucket named example.com
