### ISSUE TITLE
Upload files by extension type to different FTP locations in the Upload Filters Setting

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#2453]
I use the SFTP Destination for my uploads.

I have created separate FTP entries on the same server which go to different directories.

For example I have these directories which each have an FTP entry shown in thye image below...

- screenshots
- files
- files/zip
- files/markdown
- files/txt

![image](https://cloud.githubusercontent.com/assets/186818/25285329/d4236ad4-2687-11e7-98d9-a156ff4c6fe8.png)

---

With the FTP destinations above I am able to send all my images to my `screenshots` folder and all non-image files to my `files` folder.

My issue is it is hard to send a non-image files to a specific `files/markdown`, `files/txt` style folder.

In the `Task Settings` screen there is a tab for `Upload Filters` which allows me to filter a files Uploader by file extension.  Shown in the image below.

This is awesome however it will only allow me to select `FTP` as an uploader and not select an actual `FTP Entry` 

If it allowed me to select a specific FTP entry then I would be able to upload files with certain extensions to one FTP directory and files of another extension to a different FTP directory.

![image](https://cloud.githubusercontent.com/assets/186818/25285615/e6ad5e02-2688-11e7-9915-b436d18b19b1.png)

---
![image](https://cloud.githubusercontent.com/assets/186818/25285534/8b66409a-2688-11e7-8e62-c21f20c4df51.png)

---

So would it be possible to make the Uploaders list on the` Task Setttings > Upload Filters > Uploaders` setting list all the available FTP entries so that files can be uploaded to specific FTP destinations based on there file extension?

**Comment by Jaex** [comment]
It wouldn't be possible. Coding wise it would be pretty complicated.

**Comment by jasondavis** [comment]
I think this would be a great feature.  I don't use any of the cloud services and prefer to upload to my own server so I always use the FTP uploader.  It's great that the FTP uploader has option for different FTP entry for text, image, and file but would just be even more useful if there was a way to filter by file extension as well.

Does this sound like something that you might be interested in implementing some time down the line into ShareX?

Also I know you have the ways for people to donate $ to the project but have you considered making a "Pro" version and perhaps only allow non paid users to only use a few of the destination options and a paid license would unlock all of them.  Maybe even lock and unlock other features this could bring a good source of $ for the project which could help to implement even more features!

Just thinking out loud I have used ShareX for like 6+ years and I tell everyone about it as there really is nothing even close to as good and useful as it is!  Thanks for all your work over the years and sharing it

**Comment by Scrxtchy** [comment]
get a load of this guy

**Comment by Joshua2504** [comment]
gonna push this up.

another suggestion: let me choose the destination ftp before uploading

**Comment by Scrxtchy** [comment]
> another suggestion: let me choose the destination ftp before uploading
The before upload window would help, if the FTP was not restricted to one setting

@Jaex How hard would it be to put a combo box labelled **Target** on the before upload window.  

Populate the list with saved destinations from FTP, Shared Folder, or Custom when those bullet points are selected. This would change the current FTP/SMB/Custom destination without having to jump through the Destination settings to change it

**Comment by jcommander** [comment]
> > another suggestion: let me choose the destination ftp before uploading
> 
> The before upload window would help, if the FTP was not restricted to one setting
> 
> @Jaex How hard would it be to put a combo box labelled **Target** on the before upload window.
> 
> Populate the list with saved destinations from FTP, Shared Folder, or Custom when those bullet points are selected. This would change the current FTP/SMB/Custom destination without having to jump through the Destination settings to change it
@Scrxtchy 
Been a while, huh?
I just got into actually giving ShareX a shot and it seems like this still isn't part of ShareX as of today. I was so glad the 'before upload' window also shows before file upload but then disappointed again to see I couldn't select ftp per profile. I would allow me to pick between private and public upload.
Anyways if there's no way now and it doesn't turn out to complicated I might look into the source and try to do it myself.
