### ISSUE TITLE
b o i

### ISSUE THREAD

**Issue by P4risAndStuff** [ShareX/ShareX#2454]
**me:** hey jaex from ShareX

**jaex:** yes 🅱arisandstuff from github

**me:** spell FTP

**jaex:** HOLY CRAP like to win a free iphone 5

**_seriosuly tho, whom'st'd've knows how to solve my issue? 💯💯💯💯_**

---------------------

hola my name is p4ris and i've contacted sharex today to ask about FTP
image removed)

essentially, i'm trying to get files to upload to my website so i configured FTP in destinations, and then i set "file uploads" to FTP in the home window for sharex. so i did everything normally, yet the files **aren't uploading!**

i know what my info for the FTP is, i entered it correctly. what am i supposed to do?

**Comment by P4risAndStuff** [comment]
hey look guys the image is back
![](https://vgy.me/Of2w0j.png)

**Comment by Jaex** [comment]
Go troll anywhere else.
