### ISSUE TITLE
Dropbox Image Uploader Failing

### ISSUE THREAD

**Issue by Jonatino** [ShareX/ShareX#2457]
After latest 11.7 update Dropbox destination for image uploads is no longer working.

The following error comes up after taking a screenshot:

https://vgy.me/aLudJS.png

I tried to relink ShareX with my Dropbox account with a new API auth key, but that didn't help either.

**Comment by Jaex** [comment]
Are you creating shareable url?

**Comment by Jonatino** [comment]
@Jaex oh god I feel so stupid :( Both checkboxes were unchecked for some reason.

FYI for anyone in the future, make sure these two checkboxes are checked 👍 

![chrome_2017-04-22_13-16-47 1](https://cloud.githubusercontent.com/assets/1808569/25306580/118eb29e-275e-11e7-8943-71257c9d9022.png)
