### ISSUE TITLE
After Capture Image Editor Option Missing

### ISSUE THREAD

**Issue by Ryahn** [ShareX/ShareX#2459]
I am not able to see the image editor as an option anymore. I have installed 11.7

Here is my menu that I have
https://i.gomn.net/eQJA.png

**Comment by campbeb** [comment]
It is now shown as "Annotate Image"

Then you may need to go under Task Settings / Advanced / General / UseShareXForAnnotation and change it to False.

**Comment by Ryahn** [comment]
Perfect. THank you!

**Comment by WiliTest** [comment]
(I don't see any "General", but it's in the 4th block)

**Comment by JovialMockingbird** [comment]
I wouldn't even mind the built in option so much if it wasn't completely full screen, taking me 'out' of whatever I'm doing is not something I usually enjoy.

**Comment by NicoVerkest** [comment]
The UseShareXForAnnotation was under Advanced, not General. Works like a charm tho, ty!
