### ISSUE TITLE
Annotation Selection Tool [Feature Request]

### ISSUE THREAD

**Issue by jnever1** [ShareX/ShareX#2463]
I read from the release notes that greenshot has been replaced by built-in **annotation** and **effects** post processing. I am all for the change, but annotation and effects are missing a **selection tool**. This makes overlay manipulation a chore as the current process lacks appropriate add vs edit feedback.

I would like to request the inclusion of a selection tool, where appropriate and/or improved add vs edit feedback.

**Comment by Jaex** [comment]
Current way allows faster editing because no need to select cursor tool. And you want slower version of it?!

**Comment by jnever1** [comment]
> and/or improved add vs edit feedback
Is is only faster in some use cases such at "one tool at a time." Making multiple manipulations of several types of objects is cumbersome. The selection tool (of greenshot) has previously brought convenience in this case.

Use Case [cumbersome]:
Make an arrow
Make a blur
Make a text box
Manipulate text box
Manipulate arrow
Manipulate blur

Use Case [ideal]:
Make an arrow
Manipulate arrow
Make a blur
Manipulate blur
Make a text box
Manipulate text box

**Comment by mikejanick** [comment]
Yeah, me too.  I liked it the old way.  We use the region capture all the time and now there is no way to edit without going through a menu first.

**Comment by Jaex** [comment]
I'm not planning to add selection tool because it is not exactly image editor and workaround to use region capture as image annotator.
