### ISSUE TITLE
Deactivate animation for region selection

### ISSUE THREAD

**Issue by CreeperLava** [ShareX/ShareX#2464]
While the animation looks nice, I found it to be too distracting after a while. I prefer ShareX to feel snappy and responsive. I looked through the options and didn't see anything that could disable it. It's very subjective, but would it be possible to have an option to deactivate that animation and revert to the old behaviour ?

**Comment by Jaex** [comment]
#2435

**Comment by CreeperLava** [comment]
My bad, I should have searched a bit more thoroughly before posting. Thank you !
