### ISSUE TITLE
list of screenshots, video recorded

### ISSUE THREAD

**Issue by ronitosan** [ShareX/ShareX#2465]
Hi good day, just want to ask about the main screen of ShareX. I backed up the "Screenshots" folder as all the files i screenshot and recorded videos are there. I reinstalled a new version of ShareX of 11.7.

Now the issue i want to discuss is on how to show again the list of files on the main screen. I put the old "Screenshots" folder to the new one and all my old files are there.

How can i see again all previous files on the list. Thanks to enlighten me on this.

![image](https://cloud.githubusercontent.com/assets/22126973/25448303/03922916-2a86-11e7-8758-feb3fec94d29.png)

**Comment by Jaex** [comment]
If you mean that History button in main window then Documents/ShareX/History.xml must be backed up. Main window recent list is stored in other config files.
