### ISSUE TITLE
ShareX isn't sending arguments with custom uploader

### ISSUE THREAD

**Issue by d0x7** [ShareX/ShareX#2469]
Hi.

So, I have the following issue; When I create a custom uploader and provide some arguments, ShareX isn't always sending them in the request.

For example, I have the following configuration:

> {
>   "Name": "MyCustomUploader",
>   "DestinationType": "None",
>   "RequestType": "POST",
>   "RequestURL": "http://localhost:4567/upload",
>   "FileFormName": "file",
>   "Arguments": {
>     "secret": "1123",
>     "asdas": "asasas",
>     "asasasasasasas": "das",
>     "dadas": "d",
>     "dasa": "a"
>   },
>   "Headers": {
>     "d": "dsadasads"
>   },
>   "ResponseType": "Text",
>   "URL": "$json:url$",
>   "ThumbnailURL": "$json:thumb$"
> }

On the webserver, I'm not receiving any arguements (queryParams in this case, because I'm using SparkJava). 

Evidence: 
![2040b](https://cloud.githubusercontent.com/assets/17951467/25513479/b9871786-2bd5-11e7-997d-a8b2c98385eb.gif)

But when I open http://localhost:8080/upload?secret=1234 in my browser, it works.

Evidence: 
![2042b](https://cloud.githubusercontent.com/assets/17951467/25513494/c79563dc-2bd5-11e7-9ff3-fac3dd4b1726.gif)

But sometimes, as mentioned before, it actually does work. I just went crazy because I thought there's a bug in my application but ShareX is just randomly not sending arguments. I haven't changed anything on this configuration (except for some random arguments for testing) for hours. 

Thanks in advance.

EDIT // Before someone asks, that has nothing to do with POST or GET. It doesn't work with queryParams nor params in SparkJava. I'm not receiving any arguments within the request.

**Comment by Jaex** [comment]
I used this to test:

```json
{
  "Name": "httpbin.org",
  "DestinationType": "None",
  "RequestType": "POST",
  "RequestURL": "http://httpbin.org/post",
  "FileFormName": "file",
  "Arguments": {
    "secret": "1123",
    "asdas": "asasas",
    "asasasasasasas": "das",
    "dadas": "d",
    "dasa": "a"
  },
  "Headers": {
    "d": "dsadasads"
  },
  "ResponseType": "Text"
}
```

It sends all arguments all the time. Also nobody reported such issue before. And I don't see how randomly arguments can't be send.

**Comment by d0x7** [comment]
Okay, well. 
I just tried to print out the received body, and there are those arguments again.
I guess it's a bug in SparkJava, not in ShareX. Sorry in this case.
