### ISSUE TITLE
Animated GIF is selected, but the output is mp4

### ISSUE THREAD

**Issue by nirewen** [ShareX/ShareX#2470]
Windows 10
Sharex 11.7

Few weeks ago I was recording my screen and I noticed that the output was mp4. Thought the problem was with ffmpeg itself, reinstalled it. Didn't work. Today, I noticed that the output is actually mp4, and I can't change.
![output is mp4](http://nirewen.s-ul.eu/rQr722TX.png)

**Comment by DoctorVWA** [comment]
Noreão

**Comment by Jaex** [comment]
#2437
