### ISSUE TITLE
Spacebar to reposition starting corner

### ISSUE THREAD

**Issue by ehuss** [ShareX/ShareX#2471]
It would be nice if you could reposition the starting corner after you click to set a region if you place it slightly off.  This is a feature available on OS X's built-in screenshot capability, and is common in graphics programs like Photoshop when you create marquee selections.  Holding spacebar after setting the first corner should allow you to reposition the capture region until you let go of the spacebar.

**Comment by Jaex** [comment]
Holding <kbd>Alt</kbd> already changes corner.

**Comment by ehuss** [comment]
Oh great!  (Actually, it seems to be <kbd>Ctrl</kbd> for me on 11.7.  <kbd>Alt</kbd> shows some red rectangles.)   Can these be added to the "Show Hotkeys"/F1 list?

**Comment by Jaex** [comment]
I found that hotkey already from F1 list. Alt key changes corner when you selected region, not when creating it.
