### ISSUE TITLE
Essential feature missing from ShareX Annotation Tool

### ISSUE THREAD

**Issue by dinosw** [ShareX/ShareX#2479]
I really like your new annotation tool, except for the lack of one very essential feature, there is no crop tool.
I do not believe this tool can in anyway replace the Greenshot annotation tool, which you used to use, unless the crop feature is added.

**Comment by Jaex** [comment]
I'm planning to add it but because it would be difficult to add, was not added yet. Also planning to add insert image from capture which will work very similar to crop but instead of cropping it, will duplicate image from selection so you can drag it.

**Comment by dinosw** [comment]
That sounds amazing, I just wanted to point it out, as I am often forced to use Greenshot instead, due to the missing crop feature.
I am looking forward to future updates as usual :+1:

**Comment by dinosw** [comment]
btw. thank you for the blazingly fast response time :+1:

**Comment by Jaex** [comment]
https://gfycat.com/GiddyReadyAmericancrocodile

**Comment by dinosw** [comment]
That looks amazing :+1: 
I just noticed another missing tool, if I am annotating a screenshot, I have to select the same tool again, to change a placed object, as there is no selection tool available.

**Comment by Jaex** [comment]
I'm not planning to add selection tool, it is by design.

**Comment by dinosw** [comment]
Alright, well, that feature wasn't essential for me anyways, but I am really looking forward to the crop feature =D
