### ISSUE TITLE
SFTP doesn't create subdirectory anymore

### ISSUE THREAD

**Issue by XeR** [ShareX/ShareX#2482]
Hello,

I use ShareX to upload screenshots to my personnal server.
I set it up to use SFTP, and to upload them to `www/upload/img/%y/%mo/%d`.
It worked like a charm since August 2015, but it suddenly stopped working today (May 1st).
My guess is that ShareX tries to create the day directory (`01/`) in an non-existant directory (`05/`)
If I manually create this directory (`mkdir www/upload/img/2017/05`), it starts working wonders again.
I did not try to use a regular FTP server.

**Error log**:
> 2017-05-01 13:41:26.106 - Task in queue. Job: Job, Type: File, Host: FTP
> 2017-05-01 13:41:26.106 - Task status: Preparing
> 2017-05-01 13:41:26.108 - Image copied to clipboard.
> 2017-05-01 13:41:26.109 - Image saved to file: D:\XeR\Documents\ShareX\Screenshots\2017\05\01\Seven-13-41-26.png
> 2017-05-01 13:41:26.109 - Upload started. Filename: Seven-13-41-26.png, Filepath: D:\XeR\Documents\ShareX\Screenshots\2017\05\01\Seven-13-41-26.png
> 2017-05-01 13:41:26.724 - Exception:
> Renci.SshNet.Common.SftpPathNotFoundException: No such file
>    à Renci.SshNet.Sftp.SftpSession.RequestMkDir(String path)
>    à ShareX.UploadersLib.FileUploaders.SFTP.CreateDirectory(String path, Boolean createMultiDirectory)
>    à ShareX.UploadersLib.FileUploaders.SFTP.CreateMultiDirectory(String path)
>    à ShareX.UploadersLib.FileUploaders.SFTP.CreateDirectory(String path, Boolean createMultiDirectory)
>    à ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath, Boolean autoCreateDirectory)
>    à ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    à ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    à ShareX.WorkerTask.DoUpload(Int32 retry)
> 2017-05-01 13:41:26.725 - Task failed. Filename: Seven-13-41-26.png, Errors:
> Renci.SshNet.Common.SftpPathNotFoundException: No such file
>    à Renci.SshNet.Sftp.SftpSession.RequestMkDir(String path)
>    à ShareX.UploadersLib.FileUploaders.SFTP.CreateDirectory(String path, Boolean createMultiDirectory)
>    à ShareX.UploadersLib.FileUploaders.SFTP.CreateMultiDirectory(String path)
>    à ShareX.UploadersLib.FileUploaders.SFTP.CreateDirectory(String path, Boolean createMultiDirectory)
>    à ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath, Boolean autoCreateDirectory)
>    à ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    à ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    à ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Sharparam** [comment]
Possibly related to commit a991572ad31ca242e6a81ca862a66245885e6065?

**Comment by Jaex** [comment]
Until next version you can use absolute folder path instead of relative folder path. This problem only happens when relative folder path used.
