### ISSUE TITLE
Annotation SubMenu Idea (Illustrated)

### ISSUE THREAD

**Issue by dinosw** [ShareX/ShareX#2483]
Hi

I would really love to be able to select my annotation tool.
The available tools could perhaps be ShareX at the top, with a line separating the other choices, those choices could be the programs we add here.: `Task Settings... > Actions`
Then, if no additional programs have been added, the annotation tool would simply works as it does now.
Another way, would be to perhaps replace this option.: `Task Settings... > Advanced > UseShareXForAnnotation`, with an option to enable/disable a submenu for Annotation.
I have spent a some time with Paint (and yes, just plain ol' paint :wink:), and have constructed an image below.
![Image of Annotation Submenu](http://i.imgur.com/uXz8V5F.png)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2019/09/ShareX_ahRQnMLcZQ.png)
