### ISSUE TITLE
Cursor is way off when capturing screen recording

### ISSUE THREAD

**Issue by TheJjokerR** [ShareX/ShareX#2487]
![sharex_cursor_issue](https://cloud.githubusercontent.com/assets/2738114/25655644/df74b8b2-2ff5-11e7-8a05-ed28b191ad39.png)

I have a 4K display on this Dell XPS 15 (9530) and the cursor is way off when capturing screen recordings. Screenshots seem to work fine.

**Comment by Jaex** [comment]
#1329
