### ISSUE TITLE
It is recommended to check whether the chevereto website supports https

### ISSUE THREAD

**Issue by jiajiechan** [ShareX/ShareX#2489]
It is recommended to check whether the chevereto website supports https。

Hello, i am jiajiechan （m#jjc.im）, imgchr.com person in charge. I looked at some of the chevereto's website and found that some sites were submitted to you long ago, and now these sites are using https secure connections, and the list is still http. Hope to be able to detect whether http and https through the test, and then automatically select https as the first upload URL.

**Comment by Jaex** [comment]
That is very bad idea.
