### ISSUE TITLE
Workflow will not open image in editor after capture

### ISSUE THREAD

**Issue by wes1099** [ShareX/ShareX#2490]
I selected the "Override "After Capture" settings" checkbox and added "Annotate Image" to the workflow, but it doesn't open the image in the editor. I also tried changing the global "After Capture" settings to include "Annotate Image" but that did not work either. The image editor does however work when manually accessing it by clicking Tools>Annotate Image.

[http://i.imgur.com/Xb7oUsu.png](http://i.imgur.com/Xb7oUsu.png)
[http://i.imgur.com/Woy88Yq.png](http://i.imgur.com/Woy88Yq.png)

**Comment by Jaex** [comment]
#2438
