### ISSUE TITLE
Add a hotkey or button to restart ShareX.

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#2493]
### Background
_It exists on different on relative app.

I know it's not a big deal, but it's just for the convenience. Firefox has done it, Google Chrome has done it, and they both restart without losing tabs or data. Perhaps some other apps have done it and why not ShareX?

* **Firefox:** Enter `Shift+F2`, enter `restart` and the browser will restart with all tabs intact.
* **Chrome:** Enter `chrome://restart` in URL bar and press enter. The browser will restart with all tabs intact.

### Suggestion:
Open ShareX and press `Shift+Ctrl+R` (_or use another shortcut, however you like, you're an admin :scream:_) to restart with all history intact, if possible, but keeping history isn't needed, though it would be still _convenienvce_ with luxury of not needing to manually exit and starting the app while squatting and chilling in the backyard of 1-star hotel with my Slavic friends, Stolichnaya and little bags of Semechki with heavy salty flavor.

**Comment by vatterspun** [comment]
I know the use case for browser restarts: it's an effective debug operation and can help clear out your RAM by just opening the necessary web pages.  What's the use case for adding this to ShareX?  Why do you need it and what would it solve?  Are you restarting the program frequently?

**Workaround**: Splat (freeware from SKwire) does a great job of closing and re-opening programs sequentially and I believe you can add hotkeys.

**Comment by dmxt** [comment]
@vatterspun @Jaex ShareX constantly stopped allowing me to drag and drop from explorer to the ShareX window, forcing me to restart the program to fix the issue. 

It was happening for over few years, it did not happen very frequently to be annoying, and I have no idea what caused this problem or if someone else had this problem as well. 

Shall I check logs next time it happened? Thanks!

**Comment by Jaex** [comment]
After update ShareX, Inno Setup runs ShareX as admin. This mainly causing drag n drop to not work.
