### ISSUE TITLE
Geeting error while screen recording using FFMPEG .. 

### ISSUE THREAD

**Issue by ankur4747github** [ShareX/ShareX#2500]
ffmpeg version N-84348-gdb7a05d Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 50.100 / 55. 50.100
  libavcodec     57. 83.101 / 57. 83.101
  libavformat    57. 66.105 / 57. 66.105
  libavdevice    57.  3.100 / 57.  3.100
  libavfilter     6. 78.100 /  6. 78.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, dshow, from 'video=screen-capture-recorder':
  Duration: N/A, start: 866001.687000, bitrate: N/A
    Stream #0:0: Video: rawvideo, bgr0, 788x404, 30 fps, 30 tbr, 10000k tbn, 10000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0000000002505740] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0000000002505740] profile Constrained Baseline, level 3.0
[libx264 @ 0000000002505740] 264 - core 148 r2762 90a61ec - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'C:\Users\Ankur\AppData\Roaming\Ankur\Recent\Temp\2.mp4':
  Metadata:
    encoder         : Lavf57.66.105
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 788x404, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.83.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   16 fps=0.0 q=21.0 size=     131kB time=00:00:00.50 bitrate=2146.4kbits/s speed=0.997x    
frame=   31 fps= 31 q=18.0 size=     142kB time=00:00:01.00 bitrate=1166.0kbits/s speed=0.998x    
frame=   46 fps= 31 q=18.0 size=     143kB time=00:00:01.50 bitrate= 783.1kbits/s speed=0.998x    
frame=   61 fps= 30 q=18.0 size=     144kB time=00:00:02.00 bitrate= 591.2kbits/s speed=0.998x    
frame=   76 fps= 30 q=18.0 size=     145kB time=00:00:02.50 bitrate= 475.4kbits/s speed=0.994x    
frame=   91 fps= 30 q=18.0 size=     146kB time=00:00:03.00 bitrate= 399.1kbits/s speed=0.994x    
frame=  106 fps= 30 q=18.0 size=     147kB time=00:00:03.50 bitrate= 344.3kbits/s speed=0.993x    
frame=  121 fps= 30 q=18.0 size=     148kB time=00:00:04.00 bitrate= 303.4kbits/s speed=0.993x    
frame=  136 fps= 30 q=18.0 size=     149kB time=00:00:04.50 bitrate= 271.4kbits/s speed=0.994x    
frame=  152 fps= 30 q=18.0 size=     150kB time=00:00:05.03 bitrate= 244.4kbits/s speed=   1x    
frame=  167 fps= 30 q=18.0 size=     151kB time=00:00:05.53 bitrate= 223.7kbits/s speed=   1x    
frame=  182 fps= 30 q=18.0 size=     152kB time=00:00:06.03 bitrate= 206.7kbits/s speed=0.999x    
frame=  197 fps= 30 q=18.0 size=     153kB time=00:00:06.53 bitrate= 192.2kbits/s speed=0.999x    
frame=  212 fps= 30 q=18.0 size=     154kB time=00:00:07.03 bitrate= 179.6kbits/s speed=0.998x    
frame=  227 fps= 30 q=18.0 size=     155kB time=00:00:07.53 bitrate= 168.8kbits/s speed=0.998x    
frame=  242 fps= 30 q=18.0 size=     156kB time=00:00:08.03 bitrate= 159.3kbits/s speed=0.997x    
frame=  258 fps= 30 q=20.0 size=     292kB time=00:00:08.56 bitrate= 279.4kbits/s speed=   1x    
frame=  273 fps= 30 q=18.0 size=     293kB time=00:00:09.06 bitrate= 264.9kbits/s speed=   1x    
frame=  288 fps= 30 q=18.0 size=     294kB time=00:00:09.56 bitrate= 252.0kbits/s speed=0.999x    
frame=  303 fps= 30 q=18.0 size=     295kB time=00:00:10.06 bitrate= 240.2kbits/s speed=0.999x    
frame=  318 fps= 30 q=18.0 size=     296kB time=00:00:10.56 bitrate= 229.7kbits/s speed=0.998x    
frame=  333 fps= 30 q=18.0 size=     297kB time=00:00:11.06 bitrate= 220.0kbits/s speed=0.998x    
frame=  349 fps= 30 q=18.0 size=     298kB time=00:00:11.60 bitrate= 210.7kbits/s speed=   1x    
frame=  364 fps= 30 q=18.0 size=     299kB time=00:00:12.10 bitrate= 202.4kbits/s speed=   1x    
frame=  379 fps= 30 q=19.0 size=     300kB time=00:00:12.60 bitrate= 195.2kbits/s speed=   1x    
frame=  394 fps= 30 q=18.0 size=     301kB time=00:00:13.10 bitrate= 188.2kbits/s speed=   1x    
frame=  409 fps= 30 q=18.0 size=     302kB time=00:00:13.60 bitrate= 181.9kbits/s speed=   1x    
frame=  424 fps= 30 q=18.0 size=     303kB time=00:00:14.10 bitrate= 176.1kbits/s speed=   1x    
frame=  439 fps= 30 q=18.0 size=     304kB time=00:00:14.60 bitrate= 170.6kbits/s speed=0.999x    
frame=  454 fps= 30 q=18.0 size=     305kB time=00:00:15.10 bitrate= 165.5kbits/s speed=0.999x    
frame=  469 fps= 30 q=18.0 size=     306kB time=00:00:15.60 bitrate= 160.7kbits/s speed=0.998x    
frame=  485 fps= 30 q=18.0 size=     307kB time=00:00:16.13 bitrate= 155.9kbits/s speed=   1x    
frame=  500 fps= 30 q=18.0 size=     308kB time=00:00:16.63 bitrate= 151.8kbits/s speed=   1x    
frame=  515 fps= 30 q=18.0 size=     444kB time=00:00:17.13 bitrate= 212.3kbits/s speed=   1x    
frame=  530 fps= 30 q=18.0 size=     445kB time=00:00:17.63 bitrate= 206.7kbits/s speed=   1x    
frame=  545 fps= 30 q=18.0 size=     446kB time=00:00:18.13 bitrate= 201.5kbits/s speed=   1x    
frame=  560 fps= 30 q=18.0 size=     447kB time=00:00:18.63 bitrate= 196.6kbits/s speed=0.999x    
frame=  575 fps= 30 q=18.0 size=     448kB time=00:00:19.13 bitrate= 191.8kbits/s speed=0.999x    
frame=  590 fps= 30 q=18.0 size=     449kB time=00:00:19.63 bitrate= 187.4kbits/s speed=0.999x    
frame=  606 fps= 30 q=18.0 size=     450kB time=00:00:20.16 bitrate= 182.8kbits/s speed=   1x    
frame=  621 fps= 30 q=18.0 size=     451kB time=00:00:20.66 bitrate= 178.8kbits/s speed=   1x    
frame=  636 fps= 30 q=18.0 size=     452kB time=00:00:21.16 bitrate= 174.9kbits/s speed=0.999x    
frame=  651 fps= 30 q=18.0 size=     453kB time=00:00:21.66 bitrate= 171.2kbits/s speed=0.999x    
frame=  667 fps= 30 q=18.0 size=     454kB time=00:00:22.20 bitrate= 167.5kbits/s speed=   1x    
frame=  682 fps= 30 q=18.0 size=     455kB time=00:00:22.70 bitrate= 164.1kbits/s speed=   1x    
frame=  697 fps= 30 q=18.0 size=     456kB time=00:00:23.20 bitrate= 161.0kbits/s speed=0.999x    
frame=  712 fps= 30 q=18.0 size=     457kB time=00:00:23.70 bitrate= 158.0kbits/s speed=0.999x    
frame=  727 fps= 30 q=18.0 size=     458kB time=00:00:24.20 bitrate= 155.0kbits/s speed=0.999x    
frame=  742 fps= 30 q=18.0 size=     459kB time=00:00:24.70 bitrate= 152.2kbits/s speed=0.999x    
frame=  758 fps= 30 q=20.0 size=     595kB time=00:00:25.23 bitrate= 193.1kbits/s speed=   1x    
frame=  773 fps= 30 q=18.0 size=     596kB time=00:00:25.73 bitrate= 189.7kbits/s speed=   1x    
frame=  788 fps= 30 q=18.0 size=     597kB time=00:00:26.23 bitrate= 186.4kbits/s speed=   1x    
frame=  803 fps= 30 q=18.0 size=     598kB time=00:00:26.73 bitrate= 183.2kbits/s speed=   1x    
frame=  818 fps= 30 q=18.0 size=     599kB time=00:00:27.23 bitrate= 180.1kbits/s speed=0.999x    
frame=  833 fps= 30 q=18.0 size=     600kB time=00:00:27.73 bitrate= 177.2kbits/s speed=0.999x    
frame=  849 fps= 30 q=18.0 size=     601kB time=00:00:28.26 bitrate= 174.1kbits/s speed=   1x    
frame=  864 fps= 30 q=18.0 size=     602kB time=00:00:28.76 bitrate= 171.5kbits/s speed=   1x    
frame=  879 fps= 30 q=18.0 size=     603kB time=00:00:29.26 bitrate= 168.8kbits/s speed=   1x    
frame=  894 fps= 30 q=18.0 size=     604kB time=00:00:29.76 bitrate= 166.3kbits/s speed=   1x    
frame=  909 fps= 30 q=18.0 size=     605kB time=00:00:30.26 bitrate= 163.8kbits/s speed=   1x    
frame=  924 fps= 30 q=18.0 size=     606kB time=00:00:30.76 bitrate= 161.4kbits/s speed=0.999x    
frame=  939 fps= 30 q=18.0 size=     607kB time=00:00:31.26 bitrate= 159.0kbits/s speed=0.999x    
frame=  954 fps= 30 q=18.0 size=     608kB time=00:00:31.76 bitrate= 156.8kbits/s speed=0.999x    
frame=  969 fps= 30 q=18.0 size=     609kB time=00:00:32.26 bitrate= 154.6kbits/s speed=0.999x    
frame=  985 fps= 30 q=18.0 size=     610kB time=00:00:32.80 bitrate= 152.3kbits/s speed=   1x    
frame= 1000 fps= 30 q=18.0 size=     611kB time=00:00:33.30 bitrate= 150.3kbits/s speed=   1x    
frame= 1015 fps= 30 q=18.0 size=     747kB time=00:00:33.80 bitrate= 181.0kbits/s speed=   1x    
frame= 1030 fps= 30 q=18.0 size=     748kB time=00:00:34.30 bitrate= 178.6kbits/s speed=0.999x    
frame= 1045 fps= 30 q=18.0 size=     749kB time=00:00:34.80 bitrate= 176.3kbits/s speed=0.999x    
frame= 1061 fps= 30 q=18.0 size=     750kB time=00:00:35.33 bitrate= 173.8kbits/s speed=   1x    
frame= 1076 fps= 30 q=18.0 size=     751kB time=00:00:35.83 bitrate= 171.6kbits/s speed=   1x    
frame= 1091 fps= 30 q=18.0 size=     752kB time=00:00:36.33 bitrate= 169.5kbits/s speed=   1x    
frame= 1106 fps= 30 q=18.0 size=     753kB time=00:00:36.83 bitrate= 167.4kbits/s speed=   1x    
frame= 1121 fps= 30 q=18.0 size=     754kB time=00:00:37.33 bitrate= 165.4kbits/s speed=0.999x    
frame= 1136 fps= 30 q=18.0 size=     755kB time=00:00:37.83 bitrate= 163.4kbits/s speed=0.999x    
frame= 1151 fps= 30 q=18.0 size=     756kB time=00:00:38.33 bitrate= 161.5kbits/s speed=0.999x

**Comment by Scrxtchy** [comment]
I don't see an error

**Comment by ankur4747github** [comment]
After stop recording, this error comes and I need to again click stop button for stop recording? why suddenly CMD windows comes with this message.. is i am doing any thing wrong?
