### ISSUE TITLE
Taking a screenshot crushes the colours

### ISSUE THREAD

**Issue by ibigfire** [ShareX/ShareX#2501]
Everytime I take a screenshot it crushes the colours of whatever I take a picture of.  It is most noticeable on dark colours.  As an example, I took a screenshot of a greyscale colour wheel, then took a screenshot of that screenshot, etc., and with each progressive screenshot it gets darker and darker, to the point where two of the sections blend together entirely.

1st: http://i.imgur.com/uQ23UIT.png
2nd: http://i.imgur.com/RAAnL7A.png
3rd: http://i.imgur.com/EpH7f6b.png
4th: http://i.imgur.com/3HuuGsE.png
5th: http://i.imgur.com/Slq3dvu.png

**Comment by Jaex** [comment]
#1236

**Comment by ibigfire** [comment]
I don't think #1236 is related?  I'm not using colour picker or colour profiles in an image editor.  I'm just taking a picture of a picture that's in my web browser.

**Comment by Jaex** [comment]
Only reason colors look different is when monitor have different color profiles.

**Comment by ibigfire** [comment]
But it's the exact same image, on the exact same computer.  All I did was open http://i.imgur.com/uQ23UIT.png in a tab, take a screenshot of it and upload it.  Then I took a screenshot of that and uploaded it, and the result was the 2nd picture.  Then I took a screenshot of that and uploaded it, and the result was the 3rd picture.  Then I did the same for the 4th and the 5th.  And each one is darker than the last for some reason.

I agree it's weird, but it's the exact same computer, using the exact same monitor, and the exact same browser, for each snapshot of the pictures.

**Comment by Jaex** [comment]
GDI applying your color profile to bitmap image when processing it so it becomes more darker each capture.

**Comment by ibigfire** [comment]
Ah.  Okay!  Thanks so much for putting up with me and getting back to me on this.  Now I'll just have to do some research into that and see how I can stop it from happening.  Much appreciated!

**Comment by ibigfire** [comment]
Okay, so.  Super sorry for bothering you again.  But how do I make it so it doesn't become darker with each capture then?  When I capture my screen I want it to look exactly like what I'm seeing on my monitor.
