### ISSUE TITLE
request: add MKV for screencast

### ISSUE THREAD

**Issue by baudav** [ShareX/ShareX#2503]
Hi, can you add MKV extension for screencast?
and with vp8+vorbis it's same as webm; or vp9+opus (chrome browser can read MKV, webm)

**Comment by Scrxtchy** [comment]
easily doable with a custom argument,
![](https://tenryuu.blob.core.windows.net/astrid/17-05-09_03-59-06-CWindowsSystem32cmd.exe_-_ffmpeg.exe__-y_-rtbu.png)

Should ask someone better at ffmpeg to fix the value for -rtbufsize,
ortherwise I just change the extension, and the codec libraries used, along with variable bitrate

**Comment by baudav** [comment]
already tested, but final file is filename.mkv.mp4 and not move to destination folder.

**Comment by sergeevabc** [comment]
Similar request [here][1].

[1]: https://github.com/ShareX/ShareX/issues/4015#issuecomment-639133147
