### ISSUE TITLE
use default windows folders Docs,AppData,roaming,local

### ISSUE THREAD

**Issue by baudav** [ShareX/ShareX#2504]
Hi,
option is limited, but can ShareX use by default windows predefined folder?
logs to %LOCALAPPDATA%\ShareX  (local)
settings to %APPDATA%\ShareX (roaming)

temp in %temp% (I see when make screencast temp is with ffdshow.exe)
ffdshow shared for all users (CommonProgramW6432) or ProgramFiles\shareX
...
Just for it to be clean

**Comment by Jaex** [comment]
Saving everything all over the place is not clean. How it is currently is clean. So you can delete everything easily when needed.

**Comment by baudav** [comment]
As it is currently, it's rough, not better.

**Comment by Jaex** [comment]
Soon I'm gonna release Microsoft Store build and that build not even have access to localappdata, appdata, temp, program files to write. But have access to Documents folder.

**Comment by Scrxtchy** [comment]
> My document, is to store 'my document' and not executable, not log and not settings for apps and backup.
and not for store temporary file.

![](https://tenryuu.blob.core.windows.net/astrid/17-05-09_19-27-50-ShareX_-_Application_settings.png)
No one is forcing it to be like that
move it if you want

My thought it having different folders for different items is really bad for managing, having to navigate to and from to test and debug errors.
It's fine where it is, but having options for each can be considered a hassle, and I believe it is not worth investing time to make this an option unless it has more support.

Either way, there are a number of windows based games that use /My Documents/My Games for storing both savedata and configurations. It's up to the developer on where to decide storing their data. The fact is that a regular user is more able to find this data in My Documents. The ability in ShareX to move the personal settings folder (and a custom folder for screenshots) is already great enough

**Comment by baudav** [comment]
change folder not move files= reset config; and custom screenshots folder return to empty.
Hard to configure ShareX to work in domain AD with redirected my documents and profile; and more difficult with ffmpeg. But understand for previous comment. I not use Microsoft Store.

**Comment by Scrxtchy** [comment]
Active Directory is an interesting topic to mention :thinking:
