### ISSUE TITLE
Hochladefehler: URL ist leer

### ISSUE THREAD

**Issue by tysk93** [ShareX/ShareX#2505]
Hallo, hab als Ziel Dropbox eingestellt, und vor einigen Wochen hatte ich das Problem nicht, doch wenn ich jetzt einen Screenshot uploaden will, schlägt dies Fehl. Als Fehlermeldung dann "URL ist leer".

Kann mir jemand helfen?

Danke!

**Comment by Jaex** [comment]
I don't know german.
