### ISSUE TITLE
Cannot Screen record video on screen bottom - controlbuttons are out of screen

### ISSUE THREAD

**Issue by chris400** [ShareX/ShareX#2506]
When Screen Recording the Buttons _STOP_ and _CANCEL_ are always below the recording area. If the area is on the bottom of your screen, you cannot click them. Please move them to top of recording area, if windows is on the lower half of the screen.

When recording the complete screen there needs to be another solution.

**Comment by Jaex** [comment]
Tray bar already have stop button also there is hotkey. If I move those buttons to up then buttons will show up inside recording.

**Comment by chris400** [comment]
Sorry, but I don't see a stop button on tray bar and I cannot define a hotkey for "stop recording" - what am I missing? :-(

![2017-05-10_16-34-25](https://cloud.githubusercontent.com/assets/10909668/25904344/4673cc66-359f-11e7-8da0-887384ec03af.jpg)

**Comment by Jaex** [comment]
Are you hiding tray icons. Start and stop hotkey is same.

**Comment by chris400** [comment]
no, I am not hiding icons. I just found out, that the stop button's icon is just a tiny red dot!
Thanks for you help 👍
