### ISSUE TITLE
Empty URL

### ISSUE THREAD

**Issue by tysk93** [ShareX/ShareX#2507]
Hello, 

this is a a problem that just started occuring recently. I have set Dropbox as a target for uploading screenshots etc., but now it won't work. There is an X in the list next to the filename, and when I right click it to see the error message, it just says "empty URL".

What to do? Thanks in advance.

**Comment by Jaex** [comment]
Did you enabled Dropbox shareable url?

**Comment by Jaex** [comment]
But showing error when URL is not expected is bug. So fixed that.

**Comment by cjestal** [comment]
Hi,
Has this been fixed? I'm still encountering this even though I added 'url' in the parameters.
