### ISSUE TITLE
Sound popping in screenshot mode

### ISSUE THREAD

**Issue by DiniOG** [ShareX/ShareX#2508]
I thought I made a post about this before which really wasn't fixed. While the screenshot overlay is up, background sounds as well as my microphone pops until I get out of screenshot mode. No clue why this happens, but it's only when ShareX screenshot grid etc is up.

**Comment by Jaex** [comment]
Problem must be to do in your computer. Like high cpu usage causing sounds in your computer to lag for some reason etc.

**Comment by DiniOG** [comment]
Eh, maybe. I fixed it for now once again. Thanks though.

**Comment by DiniOG** [comment]
For anyone having this issue, it was motherboard related. I upgraded end of July without the popping issue anywhere, even though it happened mostly whilst using shareX. So, if you come across this, you need a motherboard upgrade.
