### ISSUE TITLE
Add screenshot border automatically

### ISSUE THREAD

**Issue by chucklu** [ShareX/ShareX#2509]
After I captured a picture，is it possible to add the border for the screenshot automatically?
The reason why I need this is when I insert a picture，people can not recognize the border of the picture.

I have searched by Google and also searched the issues in this repository,I did not find information about this.
I wonder if you have already implemented this function. If the software supported this already,could you please tell me how to config this function.

the screenshot  border is showed below，the red rectangle
![2017-05-11_10-31-46](https://cloud.githubusercontent.com/assets/3004057/25930075/b136465e-3636-11e7-8bfe-466b2095dd0f.png)

**Comment by Jaex** [comment]
You can use image effects:

![](https://jaex.getsharex.com/2017/05/ShareX_vvDsFkNXEO.png)

Which automatically applied to image when selected in after capture tasks.

**Comment by chucklu** [comment]
@Jaex  Could you tell me how to add a border image effect?
I click the tools menu,then image effects. Then I get a dialog to select a picture,why?
I hope  to create a border image effect for all screenshot I get,not manually set for the particular.

I did not choose a picture,just click cancel button on the dialog.
Then I get the image effects editor,I add a border image effect.
But I have no idea how to save it,and I do not understand the usage of combobox under the bottom.

So,did you have a tutorial about how to create an image effect?

**Comment by chucklu** [comment]
I have found the location of image effects editor.
TaskSettings-->Image-->Effects-->image effects configuration
I will try it again

**Comment by chucklu** [comment]
I have solved this,thanks a lot.

**Comment by ooker777** [comment]
1. ![](https://i.imgur.com/rbMMuCp.png)
2. ![](https://i.imgur.com/Ty4FyvS.png)
3. Click cancel
4. ![](https://i.imgur.com/Z7EOFlY.png)
5. Make sure the border box is checked

**Comment by JayTheCoder123** [comment]
thank you
