### ISSUE TITLE
Annotate image setting in After capture tasks did not work 

### ISSUE THREAD

**Issue by chucklu** [ShareX/ShareX#2510]
I have enabled the annotate image selection in after capture tasks.
When I capture the picture,the annotate dialog did not appear automatically.
![2017-05-11_13-34-37](https://cloud.githubusercontent.com/assets/3004057/25934157/d2361a9c-364e-11e7-94e0-f5598f971d75.png)

btw,I have enabled the image effects，and add a border image effect .The image effect works fine.

**Comment by chucklu** [comment]
Another detail,the annotate image setting in after capture tasks only trigger when I press the PrtScn key on keyboard.

**Comment by Jaex** [comment]
#2438
