### ISSUE TITLE
Annotate image setting  did not work

### ISSUE THREAD

**Issue by chucklu** [ShareX/ShareX#2511]
I have created an issue yesterday https://github.com/ShareX/ShareX/issues/2510
And you tell me it's duplicate.

Actually，the point is not only about the automatically annotate image after capture.
The point is the **combine usage of image effects and annotate**.

When I capture the picture，sharex apply the image effect.
If I use the annotate image function from Tools. After I annotate the image，sharex apply the image again.

Expected behavior:
The correct logic should be,** first annotate image，second apply the image effects**.

Here is a picture I uploaded yesterday,the  image effect of border and watermark applied twice,it's weird.
![2017-05-11_13-34-37](https://cloud.githubusercontent.com/assets/3004057/25934157/d2361a9c-364e-11e7-94e0-f5598f971d75.png)

**Comment by Jaex** [comment]
I tested now it not applies image effects twice:

![](https://jaex.getsharex.com/2017/05/ShareX_niEYwTaFor.png)

**Comment by chucklu** [comment]
@Jaex  Could you tell me the steps?

**Comment by chucklu** [comment]
@Jaex  It seems you do not enable watermark image effect.
You can enable the watermark as well as the canva,then you will find the watermark was applied twice.

**Comment by chucklu** [comment]
Just find my sharex version was 11.7

**Comment by chucklu** [comment]
Have checked the version on website https://getsharex.com/
The download package version is 11.7

**Comment by chucklu** [comment]
I know the problem ,after annotate image,I click √，which represents "run after capture tasks".
I tried the second button save, it works fine now.
