### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2514]
I have Sharex on my pc and I want to clone it on my USB stick as a portable version. It was once explained and I quote "Portable creates ShareX folder in it to store settings. So you can copy your settings from Documents/ShareX to that portable folder."

So does that mean copy all in the sharex folder or just the two files sharexsettings.xml and sharexsettings.json?

Detailed instructions for a novice please.

**Comment by Jaex** [comment]
#2296
