### ISSUE TITLE
the settings are recovered when I shutdown the computer then start the computer again

### ISSUE THREAD

**Issue by chucklu** [ShareX/ShareX#2515]
I lost the settings for hotkey  and the sub folder pattern.
However,the setting for personal folder is still working.

Btw,my computer account is under widows domain.

**Comment by chucklu** [comment]
I am not sure the location where you saved the setting files.
Maybe reset by the domain policy?

**Comment by chucklu** [comment]
the setting for custom screenshots folder
the setting  for image effect 
both are recovered

**Comment by chucklu** [comment]
After capture tasks，apply image effect and annotate image both lost

**Comment by chucklu** [comment]
Could you tell the where is the location for the config/setting file?
Is it possible for user to set the location for the config file?
Thanks a lot. @Jaex

**Comment by Scrxtchy** [comment]
Settings are in `My Documents/ShareX/`

These can be changed from `Application Settings > Paths`

**Comment by chucklu** [comment]
@Scrxtchy  Not sure,I have checked my setting folder.
I set that folder when I add the image effect.
Maybe caused by my mistake，never mind.
@Scrxtchy  Thanks  a lot.
