### ISSUE TITLE
QR code reader

### ISSUE THREAD

**Issue by ajloveslily14** [ShareX/ShareX#2516]
Something like a QR code reader that just shows what the text of a QR code is in a box, or opens the QR in your browser.

**Comment by vatterspun** [comment]
It might be possible to implement via ZXing (a.k.a Zebra Crossing) C# libraries according to the QR Code Reader project: https://qrcodereader.codeplex.com/

Invariably however someone's going to ask for the reader program to function with a webcam, which might be a lot more complex.

@Jaex Make sure if you ever do add this to make a warning about clicking on links, which can point to malicious websites or run bad code in insecure associated programs (e.g. PDF/Word macros).

**Comment by Jaex** [comment]
I'm not planning to add more dependency (library) unless it is gonna be widely used.

**Comment by Jaex** [comment]
https://gfycat.com/SereneLividBrownbear

**Comment by ajloveslily14** [comment]
Sweet

**Comment by vatterspun** [comment]
> https://gfycat.com/SereneLividBrownbear
> Sweet

Yeah that's a step above other QR code readers.  Wow.
