### ISSUE TITLE
Reset Settings - Capture Region hotkey is in draw mode.

### ISSUE THREAD

**Issue by kawohi** [ShareX/ShareX#2517]
When pressing CTRL+PrntScrn, the capture is in draw mode when I want it to be the default capture rectangle mode, how do I fix this?

**Comment by Jaex** [comment]
Do you want to hide toolbar or something?

**Comment by kawohi** [comment]
I want to stop CTRL+PrntScrn from going to draw mode and to rectangle mode.

**Comment by Jaex** [comment]
Check this setting:

![](https://jaex.getsharex.com/2017/05/ShareX_qaos6XImkS.png)

**Comment by kawohi** [comment]
I do not have that setting. I went ahead and uninstalled and reinstalled, still do not have that setting and the problem consists.

**Comment by Jaex** [comment]
That setting exists in latest version, I checked now.

**Comment by kawohi** [comment]
I don't see it though...  http://i.imgur.com/MtCLz2B.png

**Comment by Scrxtchy** [comment]
You are in the wrong settings window
