### ISSUE TITLE
Unable to upload to AWS S3

### ISSUE THREAD

**Issue by rngrx** [ShareX/ShareX#2518]
Uploads to Imgur work, machine is bypassing firewall. I've tried recreating the credentials but to no luck.

> 2017-05-15 23:19:57.823 - Hotkey triggered. Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
> 2017-05-15 23:19:57.824 - Executing: Capture active window
> 2017-05-15 23:19:58.858 - Image copied to clipboard.
> 2017-05-15 23:19:58.870 - Image saved to file: G:\Pictures\Screenshots\Screenshots\2017-05\May.15-23.19.58.png
> 2017-05-15 23:19:59.387 - Task in queue. Job: Job, Type: File, Host: Amazon S3
> 2017-05-15 23:19:59.387 - Task status: Working
> 2017-05-15 23:19:59.396 - Upload started. Filename: May.15-23.19.58.png, Filepath: G:\Pictures\Screenshots\Screenshots\2017-05\May.15-23.19.58.png
> 2017-05-15 23:20:00.089 - Error:
> Message:
> **The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.**
> 
> Request URL:
> https://REDACTED.s3.amazonaws.com/img/May.15-23.19.58.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REDACTED%2F20170516%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170516T061959Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=content-type%3Bhost%3Bx-amz-acl%3Bx-amz-storage-class&X-Amz-Signature=REDATED
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
>    at System.Net.HttpWebRequest.GetRequestStream()
>    at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
> 2017-05-15 23:20:00.089 - Task failed. Filename: May.15-23.19.58.png, Errors:
> Message:
> **The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.**
> 
> Request URL:
> https://REDACTED.s3.amazonaws.com/img/May.15-23.19.58.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REDACTED%2F20170516%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170516T061959Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=content-type%3Bhost%3Bx-amz-acl%3Bx-amz-storage-class&X-Amz-Signature=REDATED
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
>    at System.Net.HttpWebRequest.GetRequestStream()
>    at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
> 
> Upload to Amazon S3 failed. Check your access credentials.
> 2017-05-15 23:20:00.112 - ApplicationConfig save started: G:\Pictures\Screenshots\ApplicationConfig.json
> 2017-05-15 23:20:00.112 - UploadersConfig save started: G:\Pictures\Screenshots\UploadersConfig.json
> 2017-05-15 23:20:00.113 - HotkeysConfig save started: G:\Pictures\Screenshots\HotkeysConfig.json
> 2017-05-15 23:20:00.195 - UploadersConfig save successful: G:\Pictures\Screenshots\UploadersConfig.json
> 2017-05-15 23:20:00.221 - HotkeysConfig save successful: G:\Pictures\Screenshots\HotkeysConfig.json
> 2017-05-15 23:20:00.243 - ApplicationConfig save successful: G:\Pictures\Screenshots\ApplicationConfig.json

Accessing the request URL gives me:
```
<Error>
<Code>InvalidAccessKeyId</Code>
<Message>
The AWS Access Key Id you provided does not exist in our records.
</Message>
<AWSAccessKeyId>REDACTED</AWSAccessKeyId>
<RequestId>A983C77DF047B83B</RequestId>
<HostId>
7Rzr59S3VI95Mc3li1RKn7futnh2DY6rtI+kj5XRTsfKJQCcfobyjYmHkzdDWi/fO5yFqBJxRmE=
</HostId>
</Error>
```

Bucket Policy:
```
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"AddPerm",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":["arn:aws:s3:::example.com/*"]
    }
  ]
} 
```

**Comment by Jaex** [comment]
I think your issue is this: #2440
