### ISSUE TITLE
Error with FFMPEG 

### ISSUE THREAD

**Issue by viktae** [ShareX/ShareX#2520]
Hello! I have this error while i'm trying to record with FFMpeg
http://i.imgur.com/1Rr84RZ.png

Do you have an idea how to solve this issue? Thanks!

**Comment by ErikHumphrey** [comment]
Have you installed the `screen-capture-recorder` and `virtual-audio-capturer` recorder devices?  
Do you have permission to save to the output directory?

**Comment by viktae** [comment]
1. I have the screeen-capture-recorder and virtual-audio-capturer installed.
2. I thought about this but... didn't find where to change the directory.

**Comment by alec20114** [comment]
same error .. can do anything

**Comment by scriptzteam** [comment]
Smae error :(

**Comment by Ristarchik** [comment]
Поможет только переключение на такие параметры.https://puu.sh/xGip3.png в иных случаях летят ошибки.
