### ISSUE TITLE
Imgur upload showing subtle but noticeable color change

### ISSUE THREAD

**Issue by nasog** [ShareX/ShareX#2521]
I noticed that when you upload an image using the cropping tool to imgur, the colors change a bit. I'm using the ctrl + print screen hotkey to use the cropping tool and letting the auto upload do it's thing. The first upload is the original crop from a game. The color change is there and looks different than in-game. As you can see from the progressing uploads, the image color is slowly changing color and getting darker. It's very slight between the original source and the uploaded image, but it's there. I re-uploaded the same image over and over to more easily see it's effects between the first upload and the last.

1st Upload : http://i.imgur.com/Dhoet59.png
2nd Upload: http://i.imgur.com/YSR9TEZ.png
3rd Upload: http://i.imgur.com/J85GFyg.png
4th Upload: http://i.imgur.com/VI0wISl.png
5th Upload: http://i.imgur.com/r3b9vSY.png
6th Upload: http://i.imgur.com/TiR9qv7.png

In-game screenshot file, uploaded manually to imgur: http://i.imgur.com/QGQNLI7.png

**Comment by Jaex** [comment]
#1236 #2501
