### ISSUE TITLE
"you are attempting to upload a large file" dialog box gets rendered beneath all other windows

### ISSUE THREAD

**Issue by khazhyk** [ShareX/ShareX#2522]
When you attempt to upload a large file, a dialog box shows up asking if you're sure about that. It was rendered as the absolute bottom window, which results in the confusing behavior that seemingly, the upload is stuck and not progressing anywhere. This window should probably render at the top.

**Comment by Jaex** [comment]
Is this you?

![](https://jaex.getsharex.com/2017/05/Discord_DsTV2dkxju.png)
