### ISSUE TITLE
Restarted ShareX and all configs defaulted.

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#2523]
I don't really understand what happened there... 

I restarted ShareX at 01:36 according to the log, and took a screenshot at 5:00 to make an issue post. I didn't make a backup of config, unfortunately, but fortunately, there isn't much to reconfigure.

![everything_2017-05-17_05-02-13](https://cloud.githubusercontent.com/assets/3248782/26146541/860d66f6-3abe-11e7-97a6-d1f5f295617c.png)

Is something off or?

By the way, does `ApplicationConfig.json.bak` file get created before closing the program? I also have these [(image)](http://i.imgur.com/KOdF9oy.png)... is it ShareX constantly making the backup? Kudo to ya. 

But the main reason I created this issue is to report that it happened. I restarted ShareX and it lost all latest config for an unknown reason.

**Comment by Jaex** [comment]
Did you changed personal path to J:\Pictures\Screenshots and then later restarted ShareX?

.bak file creates every successful save. So if corrupt happen while saving it can load non corrupt one in next load.

**Comment by dmxt** [comment]
@Jaex No, I didn't change the path. :( I guess it just got corrupted for an unknown reason, any way to find out by logs or it's not worth investigating?
