### ISSUE TITLE
'Photobucket configuration is invalid or missing' when trying to upload whole files

### ISSUE THREAD

**Issue by mateuszj1995** [ShareX/ShareX#2525]
Hi,

Whenever I try to upload whole files, be it via folder auto-upload or by dragging them in, I get some silly 'Photobucket configuration is invalid or missing...' error. The thing is, I don't use photobucket for anything. All my uploads go to imgur, I have not once used Photobucket with sharex.

I tried going through destination/task settings but did not see anything that would specify Photobucket as the platform to upload to. It's really inconveniencing me that auto-upload from folders is not working. I'm not sure if this is an issue with Sharex or with some setting, but I don't remember making any changes to configurations that could have resulted in this.

**Comment by Jaex** [comment]
If your destinations not pointing to Photobucket but it still trying to upload there, there is two possibility, either you have fallback set to photobucket and your primary upload is failing. Or your hotkey overriding default destination to upload to photobucket.
