### ISSUE TITLE
[Missing] Screen recording (GIF) using custom region hotkey do not work.

### ISSUE THREAD

**Issue by michal037** [ShareX/ShareX#2526]
Hello, 

I created a new keyboard shortcut, `Start screen recording (GIF) using custom region` on `Shift + Print screen`  and this configuration do not work. 

But for example `Start/Stop screen recording  (GIF)` option works for me.
I'm running a program with default settings. Except that.

**Comment by Jaex** [comment]
This is custom region:

![](https://jaex.getsharex.com/2017/05/ShareX_NCDG0AMmvJ.png)

So it using that region automatically.

**Comment by michal037** [comment]
Ajajajaj my bad. At the first moment I thought that when you press the hotkey will be able to choose the size. When nothing worked, I thought it was broken.
