### ISSUE TITLE
feature request: pause and resume gif/video recording

### ISSUE THREAD

**Issue by vbNETonIce** [ShareX/ShareX#2527]
currently it's not possible to pause screen recording and resume it again later. Is this on the roadmap?

Also when I'm recording something towards the bottom of the screen the buttons are not clickable anymore. They disappear behind the taskbar. 
In that case they should appear above the recorded aread. 
If the whole screen is being recorded then of course the user must stop recording with the system tray icon.

**Comment by Jaex** [comment]
#205

You can use hotkeys or tray icon to stop recording.
