### ISSUE TITLE
bug: images editor not opening after capturing an area

### ISSUE THREAD

**Issue by SHDanielZ** [ShareX/ShareX#2529]
Hello guys. I'm currently using such settings: 
![image](https://cloud.githubusercontent.com/assets/28786447/26210861/a218aa54-3bf9-11e7-8b8a-e17d08a51447.png)
ShareX doesn't start an image editor after i capture something, only copies the image in the buffer. Is there a way to fix it? I'm using Windows 7 and latest version of ShareX. Is there any more of the information i should provide?

**Comment by Jaex** [comment]
#2438
