### ISSUE TITLE
Feature Request for the new Annotation Tool

### ISSUE THREAD

**Issue by dinosw** [ShareX/ShareX#2532]
I would love to see a point to point region selection, when using multi-region mode for screen capture.
As in, being able to click to set capture markers, and then have the region be captured when the first and last marker connects, or if the user presses enter (in which case the first and last point would auto-connect, much like they do in freehand mode).

Kind Regards
Steven Windfeld

**Comment by Jaex** [comment]
I don't see any benefit in point to point region selection.
