### ISSUE TITLE
Is it possible to add watermarks in all inages in a folder?

### ISSUE THREAD

**Issue by kamenoccc** [ShareX/ShareX#2533]
I have a folder full f images I would like to add an image as watermark. ShareX does this for captures, can it do this to images already stored in a PC?

**Comment by Kontorted** [comment]
I cannot understand what you say. Do you mean to say that you want to add watermarks to pre-existing images?

**Comment by Scrxtchy** [comment]
I can get a custom workflow for this to.. not really work
Since the image watermark only works on a capture, using a drag+drop uploader or filepicker will bypass the capture settings, rendering the task of applying a watermark to images existing useless

**Comment by kamenoccc** [comment]
This is simply done by accessing settings to treat uploads as captures! I'll rephrase the OP and close this. 

Thanks ShareX devs, what I was asking for was already there.
