### ISSUE TITLE
The annotate image don't open before uploading

### ISSUE THREAD

**Issue by mr-aleks** [ShareX/ShareX#2534]
Hello, I have problem,the annotate image don't open before uploading. In the settings this item is selected
Look https://youtu.be/3X1K12hWswc

**Comment by Jaex** [comment]
#2438

**Comment by mr-aleks** [comment]
I tried this solution, but it does not work for me. With the change of the item in the settings, the annotation still does not open

**Comment by Jaex** [comment]
It is not released yet.
