### ISSUE TITLE
creating  Deletion URL in Cistom uploaders

### ISSUE THREAD

**Issue by Lennyss** [ShareX/ShareX#2535]
http://scr.hu/1det/vp7lk
 what should i write in delete/{Here} to make link f.e
i.test.eu/delete/fileName
when uploaded
i.test.eu/i/fileName
?

**Comment by Scrxtchy** [comment]
It depends on where you are uploading to
we can't tell if we have no information about the platform, since there is nothing we can base it on

**Comment by Lennyss** [comment]
i send this to my vps where i make php script like this:
    public function upload(Request $request)
    {
       $key = $request->input('key');
       if($key != $this->key){
           return response("Key not match!",401);
       }
       $file = $request->file('sharex');
       $file->move(public_path().'/i',$file->getClientOriginalName());
        return asset('/i/'.$file->getClientOriginalName());
    }
and sending/uploding works, but i need to add to delete url fileName because i must find file in my vps and remove it

**Comment by Scrxtchy** [comment]
Looks like this does not support deleting of files, you'll need a more advanced PHP script
