### ISSUE TITLE
Screen recording using custom region does not start

### ISSUE THREAD

**Issue by MySelfLuls** [ShareX/ShareX#2536]
Hello,
I've setup the screen recording using custom a custom region, however nothing happens when I press the keybind, I've tried changing the keybind, deleting it and also tried tyo override all the default settings.
However nothing seems to be happening when I press my keybind, the debug console shows otherwise but nothing comes up UI-wise nor does it save anything.
![bauv3uefiw](https://cloud.githubusercontent.com/assets/9057749/26286866/1b420494-3e6f-11e7-9912-a05858e05e50.png)
![fldrasqxnk](https://cloud.githubusercontent.com/assets/9057749/26286881/69005e4c-3e6f-11e7-9d1c-45adf2b780c6.png)

**Comment by Jaex** [comment]
#2526
