### ISSUE TITLE
Hotkey doesn't work

### ISSUE THREAD

**Issue by shulymn** [ShareX/ShareX#2537]
Hello,

Can you please add the possibility to use the hotkey "Ctrl + Shift" only?
It doesn't work if it's just these 2 keys, the app is waiting for another key when you hit those two buttons.
Please add this.

Thank you.

![image](https://cloud.githubusercontent.com/assets/13053858/26287218/1610c87c-3e77-11e7-946c-ba424209ceba.png)

**Comment by vatterspun** [comment]
That's an interesting request.  I think it's a standard to assume that CTRL and SHIFT are modifier keys, meaning they depend on a 3rd key by definition.  Still, I've seen several Windows protocol guides say that the Windows key is exclusively for operating system actions, which is something almost nobody actually follows.

**Comment by shulymn** [comment]
If I asked that, it's because the app (puush) i was using a few years ago allowed this shortcut. It still allows it. I talked to a friend avec ShareX, she wanted to set the same shortcut as this app, but she couldn't. 
So if it's possible, it's cool. If it's not then, i guess she can get used to a new shortcut heh, but i think it should be possible and not too difficult to do, but hey i'm not a dev i'm not gonna say that in their place :P

**Comment by Jaex** [comment]
Using only modifiers as hotkey is big mistake. You would be using those modifiers in all other apps when doing other things. Therefore I'm not gonna allow such hotkey.
