### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by krakenicek** [ShareX/ShareX#2541]
Hi, this is not probably a issue, but a question. Can i convert image size after capture automatically? Thanks.

**Comment by campbeb** [comment]
Go to Task Settings
Under Image / Effects, click Image Effects Configuration
Click Add / Manipulations / Resize 
![resize](https://cloud.githubusercontent.com/assets/1089399/26378691/a4c8e550-3fe3-11e7-9189-75733fd70dac.png)
