### ISSUE TITLE
error 502

### ISSUE THREAD

**Issue by shroud30** [ShareX/ShareX#2542]
i try to upload a image with puush and it wont finish uploading itll get to 100% but then say error

**Comment by Jaex** [comment]
It was problem in host side.

**Comment by Psychokiller1888** [comment]
Same here, very very very often

**Comment by DeadlySandwich** [comment]
Yep, I have this issue too. Version 11.8, all puush uploads return 502 bad gateway despite reaching 100%

**Comment by Psychokiller1888** [comment]
Same for me, I dropped puush, and use imgur as it doesn't fail
