### ISSUE TITLE
After annote image,the image is not replaced

### ISSUE THREAD

**Issue by chucklu** [ShareX/ShareX#2544]
When a capture a picture,then annote it.
The software works fine previously.

I am not sure when it happened,now the software won't replace the image and copy the image to clipboard automatically.
Everytime I annote the image,I need to switch to another picture,then switch back.
After that ,the original image was replaced by the result of annotation.
However,the annotation still not copy to clipboard,I need to do it manually.

I am not sure,what's wrong with the sharex.
Maybe some setting problem?

**Comment by oxrc** [comment]
I can't even annotate if I capture a part of the screen. Seems that something's wrong with the setting to exclude/include annotation for only a part of the screen.

**Comment by vatterspun** [comment]
> The software works fine previously.

What version were you using when it worked?  What version are you using now?  What operating system are you on?

> the software won't replace the image and copy the image to clipboard automatically. Everytime I annote the image,I need to switch to another picture,then switch back. After that ,the original image was replaced by the result of annotation. However,the annotation still not copy to clipboard,I need to do it manually.

Could you walk through a specific list of steps on what you're seeing?  Like if you were explaining this to a friend, what specific steps would they take to reproduce it?

> I can't even annotate if I capture a part of the screen. Seems that something's wrong with the setting to exclude/include annotation for only a part of the screen.

Can you open a separate case with system information, steps you took, etc.?

**Comment by chucklu** [comment]
@vatterspun 

> What version were you using when it worked? What version are you using now? What operating system are you on?
Just the same version, I am using the latest version 11.7.
I am using win10

> Could you walk through a specific list of steps on what you're seeing? Like if you were explaining this to a friend, what specific steps would they take to reproduce it?
I don't understand. There is no specific steps:
1.capture a picture
2.annotate it
3.then I encounter the problem
I  feel weird cause sharex works fine previously,I am not sure if it’s setting problem.

**Comment by vatterspun** [comment]
> I don't understand.  There is no specific steps

I've been following Jaex and a lot of other developers for a while now and the issues that get addressed quickly have clear instructions on how to make the error happen on someone elses' computer.  When you say "capture a picture" did you use a key combination or did you launch via the main window?  When you "annotated" it, what did you click on?  When you say you had a problem what exactly did you see (screenshot)?  What were you expecting?

I'm no expert on the topic, this is all based on a variety of good guides on the net around writing good bug reports: https://leantesting.com/write-good-bug-report/

**Comment by chucklu** [comment]
Today,I find I can not open the picture on my computer.
![inetmgr_2017-05-20_18-07-40](https://cloud.githubusercontent.com/assets/3004057/26538613/7398feb6-447a-11e7-8781-00f033bd549b.png)

Check the log of sharex:

> 2017-05-29 14:14:15.798 - OpenURL(D:\ChuckLu\Pictures\ShareX\2017-05-28\chrome_2017-05-28_18-17-01.png) failed:
> System.ComponentModel.Win32Exception (0x80004005): Class not registered
>    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at ShareX.HelpersLib.URLHelpers.<>c__DisplayClass0_0.<OpenURL>b__0() in D:\ChuckLu\Git\GitHub\ShareX\ShareX.HelpersLib\Helpers\URLHelpers.cs:line 53

https://answers.microsoft.com/en-us/windows/forum/windows_10-files/class-not-registered-error-for-pictures-with/e737c708-2e10-4c87-8777-e990a89502f1

> The exact same thing happened to me.  It turned out somehow my default viewer changed to something called "TWINUI".  The tech seemed to think it happened when I was possibly viewing a picture on the internet (changing without my knowledge) .  So we changed the default viewer back to Windows Photo Viewer and all is working fine again.  Right click on a picture, choose properties, where it says "open with" click on the change button and then choose windows photo viewer. This corrected the problem for me, and hopefully it will for you as well. It was a really simple fix.

**Comment by chucklu** [comment]
It's  weird,I have change the default photo viewer to the windows photo viewer.
The exception disappeared,but after annotate image,the picture still keep the one before annotate.

**Comment by chucklu** [comment]
@vatterspun  ok,I capture the picture by hot key.
then annotate the picture by right click the list of picture.

Expected:
After I annotate the image ，the new picture should replace the old one.

Exactly happened:
The new picture was just saved in file. not reload on sharex，and not copied to clipboard.

**Comment by vatterspun** [comment]
Are you running version 11.7.  I think I may have figured out your issue and it got resolved in the latest version as Jaex switched from the Greenshot image editor to something else.

**Comment by chucklu** [comment]
I will upgrade the tools to latest version and check this issue later.
