### ISSUE TITLE
When opening multiple image editor windows, only the most recent one can be interacted with

### ISSUE THREAD

**Issue by briman0094** [ShareX/ShareX#2546]
I have a shortcut defined for the `Annotate image` tool. If I open more than one of the Greenshot windows at once, for example by taking a screenshot, using my defined shortcut, then repeating with a new screenshot, I can only interact with the most recently opened Greenshot window. Attempting to interact with any previously opened instances of this window results in a system beep. I don't recall this always being the case...I recall previously being able to open multiple image editor windows and being able to interact with each of them without having to close others.

**Comment by Inforcer25** [comment]
How did you get the image editor to open? I reinstalled sharex but i cant remember how i enabled the image editor.

**Comment by briman0094** [comment]
Right click tray icon -> Tools -> Annotate image

**Comment by Inforcer25** [comment]
Yeah I have tried that but it doesnt work. Also i have tried restarting the application but still no luck.

**Comment by vatterspun** [comment]
> ... for example by taking a screenshot, using my defined shortcut, then repeating with a new screenshot, I can only interact with the most recently opened Greenshot window. Attempting to interact with any previously opened instances of this window results in a system beep.

Confirmed on Win7x64, except I don't get a system beep.  Can put together a vid of this process if needed.

**Comment by Jaex** [comment]
This issue should be not exists anymore.

**Comment by eclutsk** [comment]
> Right click tray icon -> Tools -> Annotate image

Thank you!!!!! You helped me to find how to open an image from clipboard manually (or from File or New)!  **Tools -> Image Editor**.  This has been eluding me for some time now (switched from GreenShot awhile back).

Have a great day!
