### ISSUE TITLE
%i+342

### ISSUE THREAD

**Issue by cyberiacavs** [ShareX/ShareX#2548]
Hi, for a long time I was naming the photos manually from ShareX screenshots, and now I'm on photo number 952 , now I want to start using the autoname tool, but I need to continue from 952 , how can I add 952 to the automatic tool? (%i+952)
thank you very much!

**Comment by Jaex** [comment]
It is `NameParserAutoIncrementNumber` in "Documents\ShareX\ApplicationConfig.json" file.

**Comment by cyberiacavs** [comment]
what should I do on that line?
  "NameParserAutoIncrementNumber": 0,

if I edit the 0 for 952 nothing happens, should I do anything else? thanks!

**Comment by Jaex** [comment]
ShareX must be close while editing setting file.
