### ISSUE TITLE
Paths setting for personal folder didn't work

### ISSUE THREAD

**Issue by chucklu** [ShareX/ShareX#2550]
![sharex_2017-05-29_14-45-23](https://cloud.githubusercontent.com/assets/3004057/26539140/79d90d04-447d-11e7-8c10-c5e1ebc05d55.png)
I set the path for personal folder is D:\ChuckLu\Pictures\ShareX
However,sharex still create log files under %UserProfile%\Documents\ShareX automatically.
![explorer_2017-05-29_14-47-42](https://cloud.githubusercontent.com/assets/3004057/26539221/d67709b2-447d-11e7-9f4d-6c07da337b08.png)

**Comment by vatterspun** [comment]
Did you try this with the Portable version?  https://getsharex.com/downloads/

**Comment by Jaex** [comment]
After change personal path did you restarted ShareX?

**Comment by chucklu** [comment]
@Jaex  yes,I knew it
It's weird,now the log is generate at the right place.
But sharex still update the file under %userProfile%\documents\sharex.It's confused,since I set the personal folder under D:\ChuckLu\Pictures\ShareX,and there are config files already.
![explorer_2017-05-30_14-07-01](https://cloud.githubusercontent.com/assets/3004057/26570133/69e257c4-4541-11e7-9df8-fa4468dc9a8e.png)

**Comment by chucklu** [comment]
@vatterspun  what did you mean by protable version?I get the installation package from official website
and the version I am using is 11.7
![chrome_2017-05-30_14-11-58](https://cloud.githubusercontent.com/assets/3004057/26570267/1d0daf74-4542-11e7-96d9-1474decd0256.png)

**Comment by vatterspun** [comment]
I don't think this is meaningful to the bug report but just FYI:

> what did you mean by protable version?

If you click on the link I provided, you'll get to a list of releases.  If you click on the latest one, you'll see _ShareX-portable.zip_  That is a setting that Jaex added early in development allowing any and all settings to be saved to the local folder, useful for cloud and USB drives.

**Comment by chucklu** [comment]
I closed the sharex and deleted the folder under documents.
It works fine now
