### ISSUE TITLE
Feature request: Silent Updates

### ISSUE THREAD

**Issue by xoorath** [ShareX/ShareX#2551]
It feels like every time I sit down to use any of my computers I'm prompted to update ShareX. I'd like to request the ability to automatically update ShareX any time an update is available, instead of requiring a prompt.

I think it would be less disruptful to have ShareX update while using it once in a blue moon, than to have to say "yes" every time I sit down at a computer.

**Comment by Jaex** [comment]
You have probably faulty release which yes button not works. Otherwise ShareX releases monthly.
