### ISSUE TITLE
Double-clicking the ShareX Icon Opens the Screenshot Folder

### ISSUE THREAD

**Issue by YisroelAdler** [ShareX/ShareX#2552]
Usually with ShareX (and it is that way on several of my other computers) when double-clicking on the ShareX icon in the Notification Tray the ShareX Main Windows opens.

But on one of my devices, it recently started opening the folder where the screenshots are saved in Windows Explorer. And to open the Main Window I need to right-click the icon and select Open Main Window.

Is this a setting or what may cause this?

See below how it happens:
![2017-05-29_23-34-25](https://cloud.githubusercontent.com/assets/7387839/26567303/202e8694-44c8-11e7-8797-f612d089e380.gif)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/05/ShareX_udssyT6daq.png)

**Comment by YisroelAdler** [comment]
I already experienced more than once (possibly after updates) that it reverts back to opening the folder where the screenshots are saved without me changing any settings.

I changed it now again to open Main Window.

Any suggestion?

**Comment by YisroelAdler** [comment]
I was able to reproduce the issue. It happens any time ShareX is exited (and I guess the same thing when the PC is restarted.)

See screen recording how it happens in action:
https://streamable.com/q3yur

**Comment by Jaex** [comment]
It looks like your settings not saving, check debug log for any error.

**Comment by YisroelAdler** [comment]
This sounds right! I found lines like:
`System.UnauthorizedAccessException: Access to the path 'C:\Program Files\ShareX\ApplicationConfig.json.temp' is denied.`

I have moved the "ShareX personal folder" to "C:\Program Files\ShareX\"

Now I gave Full Control permissions for my user to that folder and issue seems to be solved. Thanks!

**Comment by shodanx2** [comment]
Hello,

Could we get actions for double right click and double middle click ?

I would like to make the following pattern

left click, open main window
double left click open last screenshot in sharex image editor
double left click if last screenshot is a video, open in losslesscut
middle click open folder of last screenshot
double middle click upload clipboard content to web media upload
right click open context menu
double right click open last screenshot in (gimp/paint.net/irfanview/krita)
double right click open if last screenshot is a video open in (openshot/shotcut)
