### ISSUE TITLE
Options for auto capture

### ISSUE THREAD

**Issue by madprops** [ShareX/ShareX#2553]
Automatic capture is great. But sometimes I want to not upload the images to the image host on every capture. And I see absolutely no options at all on how to manage those captures. Am I missing something?

**Comment by Jaex** [comment]
Uncheck this option:

![](https://jaex.getsharex.com/2017/05/devenv_EPytYi4jft.png)

**Comment by madprops** [comment]
Oh ok. Yeah that was obvious, I thought that would mess up my hotkeys, but I see they override those tasks.

**Comment by vatterspun** [comment]
Related: #2091
