### ISSUE TITLE
Support filename, or at least file extension, in custom uploader arguments

### ISSUE THREAD

**Issue by tritium21** [ShareX/ShareX#2558]
A painfully verbose destination (that will remain nameless) for some reason requires the filename be sent as a separate argument.  ShareX does not provide a way to get at this from the custom uploader API.  Baring supplying the filename a second time, could there be a file extension identifier?  (eg. %ext could evaluate to .png)

**Comment by Jaex** [comment]
File upload requests already contains file name with extension. Giving it second time makes no sense. When request already contains filename if the file host still can't use it then it is their problem and should be reported to them?

**Comment by tritium21** [comment]
This is valid, it is invalid to close it as invalid.  This is not the fist time it has been asked for, so it is needed to support upload hosts in the wild.

**Comment by Jaex** [comment]
"Invalid" means I'm not planning to implement it and I already wrote my reason for it.

**Comment by tritium21** [comment]
If its just not wanting to do the work, I'll write it.  Do you want a pull request for it?  I'll write the pull request to add the entirety properties of the system.io.fileinfo class (sans directory (useless in this case, with directoryname already on the class), and exists properties) to the custom field.
