### ISSUE TITLE
Stuck in Greenshot full screen mode

### ISSUE THREAD

**Issue by WiliTest** [ShareX/ShareX#2560]
I tried to roll back to previous shareX version but I have the same problem: when I annotate, it send me to a full screen windows (showing the picture to edit). (Same as some app when I press F11) I tried to press escape to minimize the windows (to get the normal greenshot windows) but escape close greenshot. I'm stuck in that enlarge anotating view mode.

 Exept the moving tool, (and an anoying circle showing enlarged pixels) all other the greenshot menu are missing. I don't find the way to edit it in the normal greenshot windows.  Any idea what could go wrong?

**Comment by campbeb** [comment]
See #2459
