### ISSUE TITLE
Pastebin uploads as a guest instead of logged in account after a period of time.

### ISSUE THREAD

**Issue by Hallucine** [ShareX/ShareX#2561]
Pastebin uploads as a guest instead of the logged in account after a period of time. The exact time is unknown time at the moment, as it's only done this twice.
It still reports as being logged in when I check the destination settings.
https://i.imgur.com/sWFNN1H.png
https://i.imgur.com/QfYYh9S.png

Clicking login again will fix the issue temporarily.

**Comment by Jaex** [comment]
I was logged in to Pastebin long time ago. Now tried to upload text and it uploaded to my account.
