### ISSUE TITLE
[Suggestion] ShareX 'Library' button in explorer. 

### ISSUE THREAD

**Issue by wBakunis** [ShareX/ShareX#2562]
The one and only feature I would like to see added to ShareX is a 'Library' button in explorer like what Google Drive, DropBox, and OneDrive have
![image](https://user-images.githubusercontent.com/3248262/26852208-7ed26350-4adb-11e7-8fe2-667377c1c9f7.png)

**Comment by Eubur** [comment]
Why won't you just add a Library button to explorer? It's Windows 10 feature...

**Comment by Jaex** [comment]
I don't know how to make it but I also don't see any benefit in that because you can pin ShareX folder anyway.
