### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by 20cstrothman** [ShareX/ShareX#2566]
ShareX will not start. this is what popps up and that's it.
![screenshot 12](https://user-images.githubusercontent.com/29297335/26960943-0d230654-4ca9-11e7-98f3-ea85bde9b5f1.png)
[ShareX-Log-2017-06.txt](https://github.com/ShareX/ShareX/files/1063001/ShareX-Log-2017-06.txt)

**Comment by Jaex** [comment]
#1615
