### ISSUE TITLE
"-silent" detected as malware

### ISSUE THREAD

**Issue by yigita** [ShareX/ShareX#2567]
Merhaba,

I am using ShareX for a long time i really like the capabilities of the program. But just after a new malware detection software has been installed on my PC, now it's detected as malware by TRAPS

CyveraCode: LocalAnalysis 
CyveraInternalCode: LOCAL_ANALYSIS 
CyveraVersion: 3.4.2.18344 
ProcessVersion: 11.7.0.0 
Arguments: "C:\Program Files\ShareX\ShareX.exe" -silent 
Sent: True 
SentToServerTime: 9.6.2017 9:14:16 
PreventionMode: Terminate 
TargetSource: Unknown 
SourceFilePath: C:\Program Files\ShareX\ShareX.exe 
Quarantine: No 
ContentVersion: 14-1067 
Id: 0 
Time: 9.6.2017 9:14:15 
TimeZoneOffsetMinutes: 0 
Message: Attempted execution of locally-detected malware 
ProcessName: sharex.exe 
TargetProcessName:  

Best Regards,
Yigit

**Comment by vatterspun** [comment]
Like other false-positive detection problems, I suspect this isn't really something Jaex can fix.  It's probably in TRAPS' court to enable a specific type of installation of what is clearly a popular, widely-trusted file.

Why do you need to install it silently?  Have you found a workaround?

**Comment by Jaex** [comment]
Yes, nothing I can do about it. I don't even know what is TRAPS.

**Comment by hognevevle** [comment]
Had the same issue. However, for me it started working again after a while. 
According to our policy, Traps will upload unknown executables to Wildfire for analysis. If the analysis rules the process to be non-malicious, it will then be allowed to run.

(In case you have a stricter protection policy than us, exceptions can be created in Traps' ESM Console. Contact your sysadmin/Traps provider if you do not have access to this.)

@Jaex: [Traps](https://www.paloaltonetworks.com/products/secure-the-endpoint/traps) is an endpoint protection software by Palo Alto Networks. FYI :)

**Comment by vatterspun** [comment]
> Had the same issue. However, for me it started working again after a while.

Since yigita didn't reply, I'll try asking again: why did you run it with -silent?

**Comment by hognevevle** [comment]
I never specified any -silent flag. Traps blocked the program when it started automatically after a Windows reboot, so I'm guessing the -silent flag is a consequence of the ShareX launching silently in the background? I'd assume this is by default, as I can't recall choosing this explicitly in any settings.

**Comment by vatterspun** [comment]
> never specified any -silent flag. Traps blocked the program when it started automatically after a Windows reboot

Ah ok.  So Traps is just real paranoid.

**Comment by yigita** [comment]
I have never run it silent mode, but I guess it's an option, which is specified for Traps as a dangerous action.. I just wanted to inform developers,
