### ISSUE TITLE
Flickr uploader not working

### ISSUE THREAD

**Issue by rudolphos** [ShareX/ShareX#2571]
1. So I was trying to authorize flickr uploader, it opened a webpage https://www.flickr.com/services/auth/ , then api key URL (https://www.flickr.com/services/auth/?api_key=XXXXXXX&perms=write&frob=XXXXX-XXXXX-XXXXX&api_sig=XXXXX), and then redirected me to flickr.com main page.

2. I clicked on 'complete auth' button, and this is the error I got
![image](https://user-images.githubusercontent.com/4366810/27013234-a19f5242-4ee8-11e7-8c1a-7be4691bccf9.png)

```
---------------------------
Error
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at ShareX.UploadersLib.ImageUploaders.FlickrAuthInfo..ctor(XElement element)

   at ShareX.UploadersLib.ImageUploaders.FlickrUploader.GetToken(String frob)

   at ShareX.UploadersLib.UploadersConfigForm.FlickrAuthComplete()
---------------------------
OK   
---------------------------

```

I guess this means it's outdated, because I tried other plugins (web apps) for flickr and they worked and prompted me to approve or disapprove app access.

EDIT: I copied the .json uploader config file to the computer where auth didn't work and it's working now.

**Comment by Jaex** [comment]
It redirecting me to home page too, also I can't even login to their web site, it keep looping login screen.

**Comment by rudolphos** [comment]
@Jaex Maybe they have changed their auth API, because my existing .json file worked (from my other computer), but when I tried to authorize from a new computer it didn't (redirected to main page).

**Comment by laurentkempe** [comment]
The Flickr destination doesn't work anymore, I cannot get to work and have the same problem as described by @rudolphos!

**Comment by Jaex** [comment]
Implemented new Flickr API now in codes, also added direct link option.

**Comment by laurentkempe** [comment]
When do you think we will get it?

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds
