### ISSUE TITLE
What can happen to the program that will not let me start it?

### ISSUE THREAD

**Issue by wikipedio** [ShareX/ShareX#2573]
System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'System.Net.ServicePointManager'. ---> System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'System.Net.ComNetOS'. ---> System.Configuration.ConfigurationErrorsException: Error en la inicialización del sistema de configuración ---> System.Configuration.ConfigurationErrorsException: Sección de configuración no reconocida startup. (C:\Program Files\ShareX\ShareX.exe.Config line 3)
   en System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   en System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   en System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Configuration.ConfigurationManager.PrepareConfigSystem()
   en System.Configuration.ConfigurationManager.GetSection(String sectionName)
   en System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   en System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   en System.Diagnostics.DiagnosticsConfiguration.Initialize()
   en System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   en System.Diagnostics.TraceSource.Initialize()
   en System.Net.Logging.InitializeLogging()
   en System.Net.Logging.get_On()
   en System.Net.ComNetOS..cctor()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.ServicePointManager..cctor()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.ServicePointManager.set_InternalConnectionLimit(Int32 value)
   en System.Net.ServicePointManager.set_DefaultConnectionLimit(Int32 value)
   en ShareX.UploadersLib.Uploader.UpdateServicePointManager()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 11.7 (Release)

**Comment by Jaex** [comment]
Check this file: `C:\Program Files\ShareX\ShareX.exe.Config line 3` is something wrong there.

**Comment by writtinfool** [comment]
This may be related to my problem. I just installed on a networked system with $ admin user. ShareX will not run as regular user. It requires clicking to run as administrator and validating with admin user name and password. Works but inconvenient.
