### ISSUE TITLE
Automatically recording stopped when screen locked [ShareX]

### ISSUE THREAD

**Issue by KarthikSM02** [ShareX/ShareX#2574]
Hi Team,

I am having an issue with Sharex software. After the  recording is started, when i lock my screen it automatically stops the recording . Is there anyway to keep the application alive even when the System is in locked state?

Thanks in advance.

**Comment by Kontorted** [comment]
Lock your screen?
Like Windows + L?

**Comment by KarthikSM02** [comment]
Ya but i figured it out now. Thanks

**Comment by Kontorted** [comment]
Alright then.

**Comment by ashwin** [comment]
@KarthikSM02 When you say you figured it out - what solution did you find for this? I find that ShareX stops the screen recording and writes out the video file when I lock the screen. How do I make ShareX continue recording ignoring Windows lock?

**Comment by craziedde** [comment]
> @KarthikSM02 When you say you figured it out - what solution did you find for this? I find that ShareX stops the screen recording and writes out the video file when I lock the screen. How do I make ShareX continue recording ignoring Windows lock?

Solution to this issue.

1. Keep your computer unlocked
2. But can turn off monitor manually or in control panel
