### ISSUE TITLE
Tinypic not working

### ISSUE THREAD

**Issue by teddyursa** [ShareX/ShareX#2576]
`Message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
http://api.tinypic.com/api.php?action=getuploadkey&tpid=e2aabb8d555322fa&sig=d251709a418616847d999bbd0dba0042&responsetype=XML

Response:

<html>
<head>
<title>Fastly error: unknown domain api.tinypic.com</title>
</head>
<body>
Fastly error: unknown domain: api.tinypic.com. Please check that this domain has been added to a service.</body></html>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

Unable to get upload key.`

**Had this for the past 2 days, any idea how to fix this. Or is this Tinypics problem?**

**Comment by Jaex** [comment]
"Internal Server Error" means problem in their send.
