### ISSUE TITLE
Twitter as Video destination

### ISSUE THREAD

**Issue by EntranceJew** [ShareX/ShareX#2577]
I frequently record videos, I would like if I could send them to twitter or youtube w/o taking the time to upload and link them, for files that are too large for imgur.

**Comment by vatterspun** [comment]
This is discussed in #976 ... in the mean time, Google Drive upload is more than adequate for most video uploads and sharing.  For the Twitter part, ShareX already has twitter URL posting built-in.

**Comment by EntranceJew** [comment]
I don't think sharing a link to a Google drive MP4 has the same
gravity/visibility of posting an embedded MP4. Unless the feature is
seriously mislabeled.

**Comment by Kontorted** [comment]
Doesn't twitter have an API for this??

Can't you just add it to the custom uploaders?

**Comment by Scrxtchy** [comment]
You can't oauth login with custom uploaders

**Comment by theel0ja** [comment]
@Scrxtchy Why not?

![image](https://user-images.githubusercontent.com/5832930/27483778-68829406-582f-11e7-9483-8497418c0248.png)

That _Open authorize page..._ button that opens some oauth page on Twitter.

**Comment by Scrxtchy** [comment]
Next tab down is custom uploaders

**Comment by chhopsky** [comment]
Any update on this? I'm trying to upload video to twitter as well but same error.

Youtube embedding would be good .. if I could upload to YT then tweet it out, but YT not done yet either.

![chrome_2017-11-26_14-32-13](https://user-images.githubusercontent.com/7484998/33245041-fa794ff6-d2b6-11e7-9451-f5334b2b20ac.jpg)

**Comment by Cleroth** [comment]
@theel0ja That twitter page seems to only be for URL sharing. I can't really seem to get it to work with video sharing.

**Comment by theel0ja** [comment]
@Cleroth yeah, i just said that twitter auth was already there

**Comment by theel0ja** [comment]
I don't think this issue should be closed.


Off-topic, but related to closing stale issues: https://twitter.com/sindresorhus/status/1082145283285250048
