### ISSUE TITLE
PDF Merger in Tools

### ISSUE THREAD

**Issue by SirWaddles** [ShareX/ShareX#2578]
I was wondering if it would be possible to write a simple PDF Merger utilty in the tools menu, seems like something that could be pretty useful.

I'll probably write it myself and send in a PR, but I figured I'd make an issue first to see if anyone agrees or not. It seems like it would be simple enough to include [itext7](https://github.com/itext/itext7-dotnet) and then [merge a pdf](http://developers.itextpdf.com/examples/merging-pdf-documents/clone-merging-documents-bookmarks)

I don't think there'd be any licensing issues as itext is AGPL and ShareX is GPL3, but not really sure.

**Comment by Jaex** [comment]
I don't want to add additional external libraries as possible.

**Comment by SirWaddles** [comment]
That's fair enough, there's not really a way to easily do it natively in just the C# runtime though.

**Comment by vatterspun** [comment]
@SirWaddles There are a variety of excellent freeware PDF merger tools available including PDF SAM, PDFTK4ALL, PDF Multitool, and PDF Shaper.
