### ISSUE TITLE
[Feature Request] Hotkey task to open the image folder

### ISSUE THREAD

**Issue by KurzedMetal** [ShareX/ShareX#258]
It would be very useful if I could set a hotkey to open the image folder.

I know I could do this with the default Windows features but I was expecting to use "Ctrl + Shift + PrintScreen" which can't be set up in Windows shortcuts.

**Comment by dharmaturtle** [comment]
For future googlers, this is currently possible:

![image](https://user-images.githubusercontent.com/1278803/50358183-13bfb780-051e-11e9-987d-c92a6915bc21.png)
