### ISSUE TITLE
Upload stuck at starting with large files

### ISSUE THREAD

**Issue by d3athrow** [ShareX/ShareX#2581]
with files larger than around 50MB upload gets stuck in the starting phase and looking at the destination server logs no connection is ever made.
Attempting to stop the upload results in it getting stuck at stopping as well and will be there until the program is restarted.

**Comment by Jaex** [comment]
Is it possible that high file warning message box must be shown under ShareX main window?

**Comment by d3athrow** [comment]
Huh yeah that was the issue, never knew there was a warning for that.
Seems odd it wouldn't focus on popup though.
