### ISSUE TITLE
Upload from Cliboard should detect an URL and short if it

### ISSUE THREAD

**Issue by maxibanki** [ShareX/ShareX#2582]
Hello,

whats about an feature which will detect if you have enabled the `upload from clipboard` function and bound it on a hotkey. After you have an URL in your clipboard and trigger this hotkey the mechanism will detect that it is an URL and short it instead.

What do you  think about it? It is already integrated or can I make a PR?

**Comment by vatterspun** [comment]
That seems out of scope for ShareX so I suspect Jaex will decline to add that.  You might wish to reach out to a URL shortening program and ask them to add that functionality.

**Comment by Jaex** [comment]
It is already exists:

![](https://jaex.getsharex.com/2017/06/ShareX_Gs3GEN26BT.png)

**Comment by cx622** [comment]
its not working for me for some reason
