### ISSUE TITLE
Limit upload speed?

### ISSUE THREAD

**Issue by Farfie** [ShareX/ShareX#2588]
Sorry if I just can't find it, but having ShareX eat up all my upload and everything chugging until the upload is finished is quite bad.

Edit for minor grammar.

**Comment by vatterspun** [comment]
Probably a good feature request.  I can see some cases where download speed limits would also be useful.  In fairness to Jaex, no other uploader program I've tested including MyImgur and Image Uploader have that feature.  I haven't tested File & Image Uploader, but that does seem to have some speed limits.

Possible workarounds in the mean time:

* A program like Netlimiter (non-free) 
* Figure out what port you are sharing data on and have your router set that to low priority.
* Use something like FileZilla to handle uploads

**Comment by irn-bru** [comment]
I'd like to throw my support behind this too. It really would be handy to have this feature at certain times.

**Comment by iTouchU** [comment]
It's only four years later, I guess no one wants upload speed control.

**Comment by PolicyPuma4** [comment]
A fat plus one to this feature request, I'd love to be able to limit my ShareX upload speed without third party programs.
