### ISSUE TITLE
Weak TLS?

### ISSUE THREAD

**Issue by Yuubari** [ShareX/ShareX#2590]
FTPS does not work for me with PureFTPd:

`Jun 24 06:26:43 tricoro pure-ftpd: [WARNING] Sorry, cleartext sessions and weak ciphers are not accepted on this server. Please reconnect using TLS security mechanisms.`

**Comment by vatterspun** [comment]
As a workaround, can you configure PureFTPd to run as an SFTP server?  That's generally more secure anyhow.

**Comment by Yuubari** [comment]
Not quite possible as it's an FTP server daemon, it does not implement SSH.

In general FTP/FTPS is a lot easier to work with when you need virtual users and whatnot… Is it impossible to get ShareX to use the modern crypto APIs provided by Windows?

**Comment by vatterspun** [comment]
This is a dotNET application and, according to some quick research, TLS didn't appear in the dotNET application toolset until version 4.6 and I think ShareX is still using 4.0.  

> Starting with the .NET Framework 4.6, the System.Net.ServicePointManager and System.Net.Security.SslStream classes are allowed to use one of the following three protocols: Tls1.0, Tls1.1, or Tls 1.2. The SSL3.0 protocol and RC4 cipher are not supported. 

That's no mark against Jaex as there are reasons why you'd want your program running older versions of dotNET, including broader operating system support and portability.

From there, it's likely just a case of favoring the newer, more secure libraries over the older, more compatible ones.

**Comment by Yuubari** [comment]
It looks like [it is possible](http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/) to use TLS 1.2 with 4.0 as long as 4.5+ is installed:
```c++
ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
```

**Comment by Jaex** [comment]
ShareX already supports TLS 1.2.
FTP library is not.

**Comment by Yuubari** [comment]
It seems 12.1 now uses a different FTP library, but the problem persists even though FluentFTP seems to support TLS 1.2. I am using FTPS with Explicit encryption selected.

**Comment by tinybarks** [comment]
#3635 is related to this.
