### ISSUE TITLE
Region capture issues

### ISSUE THREAD

**Issue by wavauiwi** [ShareX/ShareX#2591]
I had to reinstall Sharex, and after reinstalling I can't get the image editor to open. when I enable the quick task menu from the after capture tasks, the editor opens across all 3 of my monitors in full-screen mode. is there any way to disable this?I think that might be why the editor isn't opening.

**Comment by DmitriyYukhanov** [comment]
Having same issue after updating to the latest version.
Annotation editor doesn't start anymore when I have it enabled:
http://i.imgur.com/krc3b6o.png

It just uploads photo immediately.
