### ISSUE TITLE
Custom Hotkey Settings Do Not Work For Gifs

### ISSUE THREAD

**Issue by Naught0** [ShareX/ShareX#2592]
Hi. I'm currently able to create custom hotkeys for regular screen capture, however, when I create a custom key for a custom region gif capture, nothing happens. I have attempted to bind this to many different keys, and have wound up putting it on the Print Screen key to no avail. However, when normal image captures are bound to the same key, there is no issue. 

Below are my settings:
![image](https://user-images.githubusercontent.com/4589250/27612545-0b3dcd40-5b65-11e7-955b-5202c6a7d21a.png)

If I'm doing something wrong, please let me know. The gif functionality is really cool, and I would prefer to have it bound to a key rather than having to select it from the system tray icon.

Cheers.

**Comment by Jaex** [comment]
Custom region is actually pre configured custom region so you must select "Start/Stop screen recording" one.

**Comment by Jaex** [comment]
For next release I tried to name them more understandable:

![](https://jaex.getsharex.com/2017/06/ShareX_nMbJqZhlQe.png)

**Comment by Naught0** [comment]
A-ha! You glorious ~~bastard~~ developer! Thanks for that. Works like a charm. I didn't see any similar issues around so I hope this wasn't redundant. Thanks a ton.
