### ISSUE TITLE
[Feature request] Animated PNG functionality

### ISSUE THREAD

**Issue by vatterspun** [ShareX/ShareX#2595]
**Why Animated PNG?**

No one can deny the ongoing popularity of GIF, but the format is roughly 30 years old this year and there has been an updated version for some time now.  Like standard PNG images, the APNG format enjoys better color support and (in my testing) anywhere from 10-50% space savings.  The topic hasn't come up much because it was missing support from some of the major players, notably Google Chrome.  However, as of June 5th, the list of viewers is looking fairly complete: https://en.wikipedia.org/wiki/APNG . 

**Why ShareX?**

The list of GIF creators is long, but there are very few APNG creators unless you're talking about simple converters (like the excellent PNG Optimizer).  ShareX would be a great addition to that list.

**Reasons not to support APNG**

It's not yet ubiquitous and GIF is still more than adequate.  Older graphics viewers and Internet Explorer for example still don't support it.  Existing FFMPEG video recording tools inside ShareX are more efficient when recording very colorful images.

**Comment by Jaex** [comment]
Wikipedia is banned in my country so I can't see list of viewers.

**Comment by maxstepin** [comment]
Most browsers support APNG now, except for IE/Edge.

Imgur supports it, and many other image hosting sites too.

XnView and IrfanView supports it.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/06/explorer_YwQ4JTJiin.png)

I tried converting 147 kb video to apng and result become 3.6mb.
So FFmpeg not doing optimizations to ignore duplicate frames etc. which causing very high size and not suitable for ShareX. I can't add it like this.
Also when I tried to open that .apng like in my Chrome browser, it was downloading it instead of showing preview.

**Comment by maxstepin** [comment]
Lossy source is not ideal for such testing. It's like converting JPEG to PNG. 
If you try clean PNG sequence with apngasm converter - the results are much better.
Converting GIF to APNG with gif2apng is also likely to produce APNG that's smaller than original GIF.
It landed in Stable Chrome 59 recently, so not everyone's updated yet.
Demo page with apng samples: https://people-mozilla.org/~dolske/apng/demo.html

**Comment by vatterspun** [comment]
> Lossy source is not ideal for such testing. It's like converting JPEG to PNG.

Exactly right.  Here are some example screens from a GIF file created using some PNG screenshots + APNG Anime Maker and run through PNG Optimizer (size = 36k):

![a](https://user-images.githubusercontent.com/1289134/27713715-8fec533e-5cf2-11e7-9f43-fe1e47590c43.png)


Same sequence compiled using PhotoScape (size = 56k, lower quality):

![b](https://user-images.githubusercontent.com/1289134/27713717-931d62a0-5cf2-11e7-8e6b-c5d445d21586.gif)

**Comment by Jaex** [comment]
Those apps you telling handling duplicate frames and doing probably diff checks to only draw changed parts which decreasing file size greatly. Until FFmpeg also do these, it will be pointless to add.

**Comment by vatterspun** [comment]
> Those apps you telling handling duplicate frames and doing probably diff checks to only draw changed parts which decreasing file size greatly. 

True: there are some great GIF file compression tools that allow for similar areas to be utilized from frame to frame, similar to modern video codecs.  However, one of the reasons GIF is still so common (and maybe bigger than ever) is that you can add, add, disassemble, and otherwise build upon existing GIFs.  Meanwhile, edits to even old MPEG-2 videos start to look terrible as you can tell by all the poor quality Youtube re-posts out there.  

APNG has all the advantages of GIF and only one negatives: doesn't work on old devices (or Internet Explorer).

> Until FFmpeg also do these, it will be pointless to add.

I get that you want to add real and accepted formats so I certainly understand.  There is an APNG converter [inside FFmpeg](https://www.ffmpeg.org/ffmpeg-formats.html#apng), but I'm not clear how advanced it is.  I might make sense to wait until the tool has matured a bit more.

**Comment by vatterspun** [comment]
**Workaround for creating APNG files with ShareX**: PNGOptimizer: http://psydk.org/pngoptimizer (dead-simple, drag and drop converter, also open source and works on any number of files)

Related: #3084
