### ISSUE TITLE
Screenshotting in some full screen games works not well.

### ISSUE THREAD

**Issue by coffee-sgr** [ShareX/ShareX#2596]
When I press PrtSc key in Left 4 Dead 2, only the desktop is captured instead of the game scene.
Other games such as Overwatch and Watch_Dogs works perfect.

**Comment by vatterspun** [comment]
That might be out of scope for a program that seems focused on general productivity.  You might want to look into the excellent Open Broadcast Software, which is open like ShareX but specially designed for webcams and full screen games.

**Comment by Jaex** [comment]
#848
