### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#2602]
1. Consider put OCR also in Tools.
2. I couldn't SelectAll text by ctrl+A
3. You get the result but for some reason the taskbar button is still flashing. IMO, it shoudln't flash.

**Comment by Jaex** [comment]
It is inside "Capture" sub menu already why also duplicate it to tools?

**Comment by Stamimail** [comment]
I just wanted to use it once (rarely use), and there I was looked for it.

**Comment by Stamimail** [comment]
1. Now I saw it's already availble here:
Capture > Text capture (OCR)...
Good to know...
2.3. unsolved yet

**Comment by Jaex** [comment]
I can't reproduce taskbar flash.

**Comment by Stamimail** [comment]
Set
After capture tasks > Recognize text (OCR)
then
Capture > Region (Light)

Try several times (sometimes it works ok) with big selection.
Do you see it?

**Comment by Jaex** [comment]
Oh I see what you mean. It shows looping progress bar before actual upload start. So as soon as you close that window, it will change to upload progress bar and then disappear. So it is intended.

**Comment by Stamimail** [comment]
Upload is disabled in my side, so IMO it shouldn't looks like it is preparing for upload.

**Comment by Stamimail** [comment]
Coincidence
Just a week ago I've mentioned the OCR of ShareX . here
http://rammichael.com/textify/comment-page-3#comment-8984
