### ISSUE TITLE
How to capture a (non-active) window by clicking visually on its titlebar?

### ISSUE THREAD

**Issue by bsto** [ShareX/ShareX#2606]
What I miss in Sharex is to select one of the opened windows by select it visually with the mouse (e.g. by clicking on the corresponding on its title bar).

When I press ALT+Print then always the ACTIVE window is captured.

Meanwhile I found a solution by 
- opening the Sharex window
- click "Capture
- click "Window"
- click the windows

This is to tedious and not intuitive, I need a more comfortable way:

I want ShareX to let me (after pressing ALT+Print) VISUALLY select by mouse the windows which I want to capture (e.g.by marking it with a red border frame).

Could you add this in the next release?

Thank you

**Comment by Jaex** [comment]
It is already exists in region capture?

**Comment by P4risAndStuff** [comment]
lol

**Comment by vatterspun** [comment]
@bsto As a workaround, you might look into Snipaste, which will also grab submenus and icons but is not open source and lacks all the mature customizations and intelligent features of Sharex.
