### ISSUE TITLE
Supported OS? Windows, Mac, Linux??

### ISSUE THREAD

**Issue by styfle** [ShareX/ShareX#2610]
I can't find which Operating Systems are supported on the website or the readme.

It looks like its probably windows only, but which version of windows?
Is Mac OS or Linux supported?

**Comment by Jaex** [comment]
Windows XP or later is supported.

**Comment by styfle** [comment]
Is that documented anywhere? Should it be added to the readme or website?

**Comment by Jaex** [comment]
https://getsharex.com/docs/faq

**Comment by vatterspun** [comment]
Should note that someone did get the program running in Mint #2712 via what I'm guessing is Wine or Crossover, but that's still not official support.  With a few exceptions, I haven't seen a lot of effective porting of dotNET programs to Linux or Mac.

**Comment by NovusTheory** [comment]
That's mac support for the IDE, ShareX depends too much on Windows only libaries. It's not possible to port it

**Comment by MAGICCC** [comment]
There's also https://github.com/Francesco149/sharenix
Not that good but better than nothing

**Comment by NovusTheory** [comment]
Don't use that, use KShare if you want a linux alternative (still in devlopment) https://github.com/ArsenArsen/KShare
