### ISSUE TITLE
v11.8  When annotation step enabled the greenshot editor window is not opened  

### ISSUE THREAD

**Issue by MikeZnaet** [ShareX/ShareX#2611]
Recent change made to v11.8  makes all screens (I have them 3) black after capturing instead of opening greenshot editor window.  This makes user experience a little bit complicated as I need to look at other opened windows when annotating the screenshot. 

P.S.  I keep rollin back to v11.6  as this is the last one where greenshot editor still pops up.

**Comment by campbeb** [comment]
See https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879
