### ISSUE TITLE
Selection from Custom Uploaders

### ISSUE THREAD

**Issue by DeInfernal** [ShareX/ShareX#2614]
Let us have a dropdown menu where Custom Uploaders is!

So we could create better hotkeys...
(For example, one of hotkeys will send to a Custom Uploader#1, and other hotkey to Custom Uploader#2)

**Comment by Jaex** [comment]
You can override custom uploader destination per hotkey:

![](https://jaex.getsharex.com/2017/07/ShareX_X3kvPmI3FD.png)
