### ISSUE TITLE
Verify signatures of DLLs before loading them.

### ISSUE THREAD

**Issue by sirocyl** [ShareX/ShareX#2615]
Signing the actual program, including DLLs and the ffmpeg download, ensures a path of trust rooted in your own hands.
Verifying these signatures on DLLs, before loading them, prevents from simple DLL hijacking and bait-and-switch attacks, where a valid .exe is running malicious code.

Notepad++ was the target of [a bait-and-switch attack by a state actor](https://yro.slashdot.org/story/17/03/12/1932250/notepad-update-fixes-cia-hacking-issue), in which a modified DLL replaced one included with the program.

Widely-used open-source applications such as this, are a large vulnerability surface for such social-engineering and DLL hijack attacks, since its large install base ensures that a malicious actor's "toolbox" targeting popular applications, can have ShareX in its library.

See also: #578. concerning signatures on the updater.

**Comment by TheOddball** [comment]
Wouldn't this destroy being able to edit the source for yourself?

**Comment by sirocyl** [comment]
Certainly not. The signature checks would be entirely disabled on your own builds, or replaced with your own signature if you chose to do so; such checks only concern the original binary builds.

You wouldn't _really_ need code-signing for your own builds, considering Git has rather strong code-integrity from the source.

**Comment by sirocyl** [comment]
Adding to this: 
https://notepad-plus-plus.org/news/hijacked-incident-info-update/
