### ISSUE TITLE
Is it possible to skip an after capture task?

### ISSUE THREAD

**Issue by jakon2048** [ShareX/ShareX#2617]
Right now my flow is: capture -> opens the screenshot edit window/tool -> after complete, perform upload.

Sometimes I just use the "copy" function in the screenshot edit window/tool and would like to call it the end of a day. However, when I click the "close" button, the upload still happens. 

Is it possible to somehow skip the upload step in my flow?

Thanks!

**Comment by NovusTheory** [comment]
I believe you can setup your hotkeys to override the capture settings 👍

**Comment by jakon2048** [comment]
I guess that would mean I'd have to set a different hotkey depending if I'd like to upload or not. Any other ways?

**Comment by NovusTheory** [comment]
Not that I know of no, maybe someone else might know

**Comment by vatterspun** [comment]
> that would mean I'd have to set a different hotkey depending if I'd like to upload or not. Any other ways?

First, is using a different hotkey really that tedious?  If so, can you suggest something?  What would you like to see?  Like hold down shift to stop a process?

**Comment by jakon2048** [comment]
Muscle memory is annoying to override. 

I guess the expectation mismatch happens where hitting "x" or "close" on the image editor should stop the process, not execute the next step.
