### ISSUE TITLE
[Feature Request] Quick Task Destinations

### ISSUE THREAD

**Issue by DeJayDevelopment** [ShareX/ShareX#2620]
Hi there! I'd like the option to be able to use multiple destinations. 

Currently my flow takes a screenshot and then opens the Quick Task menu. In this Quick Task menu I have a simple Upload to Host, and Copy to Clipboard Combo. However, flexibility create a task to upload to ANOTHER host would allow me to use image hosting services that support multiple domains.

**Comment by vatterspun** [comment]
Evidently not possible.  See #2594
