### ISSUE TITLE
Image editor in Sharex 11.8 VERY BAD and not logical. How return back old one?

### ISSUE THREAD

**Issue by anacondaqq** [ShareX/ShareX#2621]
### Problem

In Sharex 11.8 has been changed image editor to some another version. 
This version of the image editor the reason of the large list of problems.

**Because of the next reasons below:**
* No more windows borders where you can exactly see that image right now opened inside specific app and you can edit it
* No more WSYWG effect when applying different filters like pixelization. You don't see exact effect what is going on
* Clicking enter in 95% cases a result of saving image and closing editor. But in previous versions enter was a good button to save changes related to specific filter, or text block, or modified block.
* Changed pane from Vertical to Horizontal one. This provoked a lot of problems, because you can not edit the image quickly, you have to look and find the right button on this stupid panel. This is a matter of habit that you destroyed with this latest one update (several years of use - and here on you - changed the most important part of the application).
* Very ugly and problematic right now capturing floating region of screen with holding ctrl + left mouse.

Please return back old image editor, or add an option to select which image processor to select for fast image editing before uploading it to the internet.

**Comment by campbeb** [comment]
See https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879

**Comment by anacondaqq** [comment]
This is fixing the problem.
