### ISSUE TITLE
Integrate AeroShot

### ISSUE THREAD

**Issue by krook1024** [ShareX/ShareX#2622]
> AeroShot is an open source screenshot utility designed for capturing individual windows. It captures screenshots with full transparency, such as seen in the Windows Aero visual style. This allows for a clean and professional screenshot, useful for showcasing an application.

https://code.google.com/archive/p/aeroshot/

I personally love this program and would love to see it integrated in ShareX. Is it possible to make?

**Comment by Jaex** [comment]
ShareX already supports transparent capture.

**Comment by krook1024** [comment]
ShareX's transparent capture feature is not exactly what aeroshot does.

**Comment by Jaex** [comment]
I don't see any feature AeroShot have that ShareX don't.

**Comment by krook1024** [comment]
Fair enough. Sorry.
