### ISSUE TITLE
How do we use Custom Domain support for Azure?

### ISSUE THREAD

**Issue by altano** [ShareX/ShareX#2623]
I see that custom domain support was supposed to come with ShareX 11.8 (https://github.com/ShareX/ShareX/pull/2613). How does it work? I upgraded to 11.8 but the "Azure Storage" pane in the Destination Settings doesn't have a custom domain field.

Thanks so much for adding this btw!

**Comment by Jaex** [comment]
Azure custom domain support added after 11.8 release, so it will come with next release.
