### ISSUE TITLE
One-time donation?

### ISSUE THREAD

**Issue by altano** [ShareX/ShareX#2624]
Can you add a donation option on the website that allows for a one-time donation and doesn't require knowing how to use Bitcoin? E.g. paypal or credit card or something?

Patreon would be fine but I don't want to make a recurring donation.

**Comment by Jaex** [comment]
PayPal and most of credit card payment services blocked in my country, so Patreon is only way I could get donation. You don't have to do recurring donation, you can disable subscription after initial payment.

**Comment by altano** [comment]
Ah, that sucks. It took me a bit and was non-intuitive but I figured out how to use Patreon and then cancel the pledge. Thanks!

**Comment by Jaex** [comment]
Thank you!

**Comment by vatterspun** [comment]
Yeah thanks for doing that @altano

**Comment by altano** [comment]
No, thank you for making this awesome app.
