### ISSUE TITLE
Repeated hanging on 100% upload

### ISSUE THREAD

**Issue by TheDreamcaster** [ShareX/ShareX#2628]
Repeatedly hangs on 100% upload and occasionally returns bad gateway and fails to upload, very frustrating.

**Comment by Elodyz** [comment]
Same here :(

**Comment by wolfhound871** [comment]
The remote server returned an error: (502) Bad Gateway.

Request URL:
https://puush.me/api/up

**Comment by Jaex** [comment]
#2627
