### ISSUE TITLE
Add feature: Sheduled capture

### ISSUE THREAD

**Issue by APletenev** [ShareX/ShareX#2630]
Task settings->Screen recorder: Start recording after and Fixed duration.
Both of parameters limited to 60 sec currently. Just removing of this limitation will give to ShareX new brilliant feature: Sheduled capture.
Use case: Capturing of Youtube or other channels live translations, webinars etc. in time when you unable to be in front of computer. It is also great competitive advantage because most of screen capturing utilities unable to shedule of capturing.

**Comment by Pcenginefx** [comment]
I was JUST going to post something like this request as well - I just installed ShareX and it is AMAZING (I will be donating for sure!) - only thing that could make it even better is yes, scheduled automatic capture (in my case, screen capture). I'd love to be able to set times (say 8AM, 12PM, 8PM) daily for ShareX to do screen captures every day for me.

**Comment by vatterspun** [comment]
Thank you for listing a use case.

**Comment by Scrxtchy** [comment]
you can do something like this already within windows. With some configuration of workflows, these can be executed from the command line.
run `taskschd.msc` and click `create basic task` on the sidebar, follow the basic configuration, you can input multiple triggers in later, as well as re-occurrence
Point the program to your sharex.exe, and the optional argument with the needed arguments https://getsharex.com/docs/command-line-arguments

A lot of the input boxes for time aren't restricted to the values from basic task, you can later type in `4 hours` and it will be a valid input
![image](https://user-images.githubusercontent.com/12771982/28199552-e31b494e-68a9-11e7-836f-27e4c6f25cea.png)
