### ISSUE TITLE
Annotation window doesn't allow panning or zooming and doesn't show entire image

### ISSUE THREAD

**Issue by hheimbuerger** [ShareX/ShareX#2631]
#### Use case
I'd like to use the "Scrolling capture" function and then crop the resulting image.

#### Environment
Windows 10, two monitors, each with a resolution of 1920x1080, resulting in a total desktop of 3840x1080.

#### Reproduction steps
1. Run a scrolling capture. Have a screenshot of about 1920x3240 resolution.
2. Right-click the file in ShareX and select "Annotate image".

#### Expected behavior
The annotation screen opens on one monitor, zooming out to roughly 33% to show the entire image and allow me to crop it.
Or it does show the image at 100%, but e.g. the cursor keys, or the right mouse button allow panning around.

#### Actual behavior
The annotation screen opens across both monitors. Vertically, It shows only the center portion of the image, roughly from coordinates (0, 1080) to (1920, 2160). The top area from (0, 0) to (1920, 1080) and the bottom area from (0, 2160) to (1920, 3240) is invisible and therefore cannot be included in the crop.

Additionally, — and this does not affect functionality, it's just jarring UX — the annotation screen centers the image horizontall across both monitors. So the left side of the image appears on the right half of the left monitor, and the right side of the image appears on the left half of the right monitor.

**Comment by vatterspun** [comment]
Can you provide some screenshots?

**Comment by Jaex** [comment]
Implementing this gonna be very difficult because it is not designed to be image editor but instead written top of region capture to support annotation on screen.

**Comment by Jaex** [comment]
@L1Q added panning support with mouse middle drag now: https://gfycat.com/CrazyImperfectBrahmanbull

That way you can annotate images bigger than screen.

**Comment by provalinf** [comment]
Hello,
I'm looking forward to this feature, because I often open images larger than my screen to blur parts or make annotations, and de-zoom or moving are really missing features.

PS: Thank you for your great software :)

**Comment by Huntario** [comment]
My workaround is to take a screenshot of the image and then annotate that. Works!

**Comment by WiliTest** [comment]
(To play with the panning press the mouse middle button). 

Hi Jaex!  Please add an editor panel in hotkey settings to customize the editor shortcuts too!
