### ISSUE TITLE
Error at Windows Startup

### ISSUE THREAD

**Issue by denismattos** [ShareX/ShareX#2632]
I've been getting this error at Windows startup since the penultimate update.
ShareX displays the message:

> System.BadImageFormatException: Could not load file or assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
> File name: 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
>    at ShareX.Program.Run()
>    at ShareX.Program.Main(String[] args)
> 
> WRN: Assembly binding logging is turned OFF.
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> Note: There is some performance penalty associated with assembly bind failure logging.
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
> 
> ShareX 11.8 (Steam)

I then click "Continue" at the error message window and the program starts normally.

What should I do to prevent this error?
Or is it safe to simply ignore?

Thanks in advance.

**Comment by Scrxtchy** [comment]
#1615

**Comment by denismattos** [comment]
Thanks for the answer, Scrxtchy.

Just to add to it: I actually came here to comment I solved the issue without reinstalling.
I opened the Steam Client and verified the integrity of the application's cache. It said the cache was perfect, but fixed the issue anyway (I opened it afterwards and it worked perfectly. No error message, nothing.).
