### ISSUE TITLE
WebM + Audio

### ISSUE THREAD

**Issue by DArkes1312** [ShareX/ShareX#2634]
Hello ; I have a problem with webm format files.

It record well without sound but as soon as I add sound it just goes laggy like 3 fps.

http://wunkiakorps.net/i/23678.webm  With sounds
http://wunkiakorps.net/i/6052.webm Without sounds.

What I am missing ? 

http://wunkiakorps.net/i/45120.png

EDIT: It does that with everything when i add sounds recording.

**Comment by vatterspun** [comment]
I have no idea.  Have you tried something other than webm?  Do other codecs have similar sound issues?

(Almost) related: #2263
