### ISSUE TITLE
Column Width Resets

### ISSUE THREAD

**Issue by JAK0723** [ShareX/ShareX#2635]
The column width resets whenever shareX is exited, as such I have to resize them every time I turn on the computer. At the default width, it is impossible to see the full contents of the column, except for the last one.
I should note that I use a 4k display resolution, I'm not sure if this issue is caused by a high resolution, or merely exacerbated by it.

**Comment by JAK0723** [comment]
So is this issue going to be addressed at some point? Is this a reproducible bug or is something just wrong with my setup?

**Comment by Jaex** [comment]
This is how columns look currently:

![](http://i.imgur.com/85mdbED.png)

What you mean by bug?

**Comment by JAK0723** [comment]
This is how it looks like when the program starts:
![sharex_2017-08-23_17-10-41](https://user-images.githubusercontent.com/29014804/29603122-47b0c74e-8826-11e7-9182-93054dd6f5e6.png)
I can adjust it to look better like this:
![sharex_2017-08-23_17-11-22](https://user-images.githubusercontent.com/29014804/29603160-6734e7d0-8826-11e7-8a1f-3cf3e34eec6e.png)
But then it just resets the next time I exit and reopen the program. I would much prefer if the program saved the column widths, so I wouldn't have to manually adjust it every time I want to use it.

**Comment by JAK0723** [comment]
Like I said before, it might be worsened by using a HiDPI monitor. You might not notice it if you use a normal resolution, but it's very annoying with a 4K screen.
