### ISSUE TITLE
Azure Custom Domain support with https

### ISSUE THREAD

**Issue by Doridian** [ShareX/ShareX#2636]
I have recently seen that Azure custom domain support has landed, which is great.
However it forces the protocol to http://, which is incorrect.

While it is true that Azure does not support custom domains with https directly (as CNAME), it does support HTTPS if you add a CDN endpoint (*.azureedge.net) pointing to the blob storage container.

So it would be very neat to add support that it defaults to http://, but still allows https:// to be specified.

**Comment by Lego6245** [comment]
I was going off of the following page in general:

https://docs.microsoft.com/en-us/azure/storage/storage-custom-domain-name

My understanding was that's technically a different endpoint than the regular blob storage system, is that wrong?

**Comment by Doridian** [comment]
Well, you can enable this from within the blob storage (in the sidebar there's "CDN").
You can not upload using that URL of course, but everyone can view all your blob's contents using it.

**Comment by Lego6245** [comment]
Ah, so you're still using the same blob storage PUTs, but it's just routed differently. This is probably better as a toggle, which if it's true we use whatever you put in, appending https://, and with it off, force to http://

**Comment by Jaex** [comment]
`URLHelpers.FixPrefix(url);` should be used. It is users responsibility to know is https:// supported or not.
