### ISSUE TITLE
Feature request: full screen application detection

### ISSUE THREAD

**Issue by solidsneak** [ShareX/ShareX#2638]
It would be great for ShareX (to at least have the option) to be able to detect full screen applications and disabled hotkeys while they're open (preferably, if possible.. only when they are the active window). That way when we are playing games we won't accidentally hit the hotkey, causing a bunch of issues.

**Comment by SilverMight** [comment]
This would be amazing, I've done this so many times

**Comment by sneak310** [comment]
Still want this

**Comment by M45T3Ryu** [comment]
THIS IS NEEDED, IT IS REALLY ANNOYING TO UPLOAD BLACK SCREENSHOTS AND EXIT FULLSCREEN FOR THE "FILE UPLOADED" NOTIFICATION EVERYTIME I PRESS THE BUTTON, I LIKE SHAREX BUT I HATE IT BECAUSE OF THIS

**Comment by stuntguy3000** [comment]
I believe it's too hard if not borderline impossible. Some programs or apps run "full screen" without rendering anything, leading to plenty of false positives.

**Comment by Darkblader24** [comment]
I need this, please implement it.

**Comment by Jaex** [comment]
Added two different options:

![](https://jaex.getsharex.com/2019/04/ShareX_R8kGmk3yhD.png)

![](https://jaex.getsharex.com/2019/04/ShareX_h074Zvw4TH.png)

**Comment by solidsneak** [comment]
Thank you so much

**Comment by solidsneak** [comment]
You said you added the option but there's no update. Where's the update with the option?

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds
