### ISSUE TITLE
Re: Closed #2640.

### ISSUE THREAD

**Issue by ctahok** [ShareX/ShareX#2641]
This ticket #2640. Just to add comment that the SpaceX was installed automatically via ninite.com which puts it to default location C:\Program Files\ShareX\ folder which is normal behavior. So changing and making it work like your rival C:\Program Files\Greenshot does would make your soft only better.

**Comment by Jaex** [comment]
#2640

**Comment by bolsomito** [comment]
SpaceX :lul:

hello dbl community
