### ISSUE TITLE
GFYCat Duplicates

### ISSUE THREAD

**Issue by xoxfaby** [ShareX/ShareX#2642]
When you upload a file to gfycat that already exists, the website shows you that post and gives you the option to make a duplicate of it, which will create your own post with the same file. This is all handled in the API. ShareX by default only takes the link from the original post and doesn't give you the chance to make a duplicate instead. 

Could this be implemented? From what I understand, it should be very easy. It could be a setting in the destination setting for GFYcat to automatically duplicate if possible.

**Comment by xoxfaby** [comment]
ShareX/ShareX.UploadersLib/FileUploaders/GfycatUploader.cs

Line 89:
            IgnoreExisting = false;

if this wasn't hardcoded, but a setting, it would be perfect.

**Comment by Jaex** [comment]
I will add it to UI.

**Comment by Jaex** [comment]
To be honest I don't see why would someone want to get url to already exist video. It is not like allows avoiding upload, you still need to upload it. So that option should be true always.
