### ISSUE TITLE
ShareX.HelperLib.dll not found 

### ISSUE THREAD

**Issue by MohsinAli512** [ShareX/ShareX#2645]
when i compile this project than this error is arise ShareX.HelperLib.dll is not found when i go to specified folder than there will be no dll present.Can you please help me?

**Comment by kirhgoph** [comment]
I encountered this problem when tried to compile with Visual Studio 2015.
What version of Visual Studio do you use?
I've installed 2017 and checked components "Development for Universal Windows Platform" and "Classic .NET apps" (component names may be incorrect as I translate them into English).
And after that compilation was successfull
