### ISSUE TITLE
Bad innovations

### ISSUE THREAD

**Issue by Detsle** [ShareX/ShareX#2646]
Good afternoon, the version of your excellent program was updated and I was horrified (((
1) Why is the image editor on the whole screen? How to remove it? The window was very comfortable.
2) Why blur and pixelization effects do not show their effect in real time?

Help remove these shortcomings (((very much like your program, but with such innovations it is difficult to work.

**Comment by Detsle** [comment]
While I had to roll back to version 11.6 =((

**Comment by campbeb** [comment]
See https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879

**Comment by vatterspun** [comment]
A little background: ShareX was using an integrated editor "Greenshot," which is open source with a compatible license.  Jaex has been working on another editor, which is in progress.  I have little doubt that time will tell as far as innovation and you might find you prefer the new editor once it meets feature parity with the Greenshot editor.

**Comment by Jaex** [comment]
Both of your requests added now in dev build: https://jaex.getsharex.com/2017/11/mp6w8i2iWV.mp4

**Comment by vatterspun** [comment]
> Both of your requests added now in dev build: https://jaex.getsharex.com/2017/11/mp6w8i2iWV.mp4

Nice!
