### ISSUE TITLE
[BUG] Quick task menu not opening after recording video

### ISSUE THREAD

**Issue by Zeblote** [ShareX/ShareX#2648]
Set up like this:

![chrome_2017-07-22_04-54-57](https://user-images.githubusercontent.com/6764788/28487819-03282dce-6e9a-11e7-8b01-fbb169bc231f.png)

The quick task menu opens after taking screenshots, letting me choose upload/copy file, but if I record a video it just saves it and nothing else happens.

**Comment by Klocko** [comment]
I'm also getting this issue.

**Comment by Zeblote** [comment]
Wat? You can't just close a bug just because you haven't fixed it in a year.
