### ISSUE TITLE
How to send translation?

### ISSUE THREAD

**Issue by pjammo** [ShareX/ShareX#2649]
I worked on a translation lately, how should I send files?

**Comment by Jaex** [comment]
Normally you fork this repo, then do translation in your own fork, push your changes to your own fork, use https://github.com/ShareX/ShareX/compare to pull request it to this repo. Not sure how you did translation.

**Comment by pjammo** [comment]
"ResX Resource Manager", I followed https://getsharex.com/docs/translation.
