### ISSUE TITLE
Simple gif editor with ShareX

### ISSUE THREAD

**Issue by quazi-irfan** [ShareX/ShareX#2651]
I remember seeing a small menu after completion of GIF capture using ShareX - and one of the options of that menu allowed me to open the gif in a gif editor. But the menu isn't showing up anymore.

Do ShareX comes with any editor that allows simple gif modification(i.e. removing frames)? If yes, how do I get it?

**Comment by Jaex** [comment]
ShareX never had gif editor.

**Comment by vatterspun** [comment]
> Do ShareX comes with any editor that allows simple gif modification(i.e. removing frames)? If yes, how do I get it?

Like a video editor, a GIF editor is probably out of scope for ShareX.  Two also programs that are open source like ShareX that can help include OpenShot (http://www.openshotvideo.com/2015/02/february-update-gifs-video-playback.html) and ScreentoGIF (http://www.screentogif.com/)
