### ISSUE TITLE
Pausing when screenshotting region

### ISSUE THREAD

**Issue by virtualflying** [ShareX/ShareX#2654]
I just downloaded this program and it is phenomenal. It has so many options to do whatever I need.

One thing I wondered is if while I am screen-shotting a region, the desktop/monitors don't freeze. I saw a previous post about this issue, but you attached an image that is no longer available.

Cheers

**Comment by Jaex** [comment]
Region (Transparent) in capture menu not freezes background, but it don't have annotation capabilities.

**Comment by virtualflying** [comment]
Can you show which/where the setting is? I can't find it. Sorry to bother

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/07/ShareX_MtZKQBDNC2.png)

You can configure it as hotkey too. But I still don't recommend it because there is no annotation support in it.

**Comment by virtualflying** [comment]
Thanks so much, keep up the amazing work!
