### ISSUE TITLE
Fixed size region mode

### ISSUE THREAD

**Issue by svnpenn** [ShareX/ShareX#2655]
Sometimes I want to use this, and sometimes I want to manually choose the region.

It seems if I want to switch back and forth I have to go into the Task settings each time? Is a better solution available?

**Comment by Jaex** [comment]
Region capture toolbar have option for it.

**Comment by svnpenn** [comment]
I came up with better option:

1. Hotkey settings
1. Add another hotkey
1. Edit
1. Task > Task > Screen capture > Capture region
1. Capture > Override capture settings
1. Capture > Region capture > Fixed size region mode

This way you can use the default hotkey for "region mode", and another Hotkey
for "Fixed size region mode"
