### ISSUE TITLE
Print screen Issue

### ISSUE THREAD

**Issue by mohmmedali7** [ShareX/ShareX#2656]
Dear Concerned Person,

![Uploading print screen issue.png…]()
![Uploading print screen issue.png…]()

For me, Print screen should work according to my system default not as per ShareX.
I tried with some settings in my ShareX application like I removed the hotkey settings for the Print screen and when I press Print screen on my keyboard, it is not getting captured by my computer.
Can you please help me for some settings that ShareX should work for other things but not for PrintScr for my system? I almost spent my 4 hours searching and google the resolution for this issue but not able to catch.
Please help!

**Comment by Jaex** [comment]
I couldn't understand what you mean.

**Comment by ArsenArsen** [comment]
I will assume you mean that you want to do the built in screenshot. In this case you want to unbind ShareX in task settings.

If you mean that the print screen button does nothing look for a FN button in bottom left and hold it while pressing print screen.
