### ISSUE TITLE
Option to disable magnifier in annotation screen

### ISSUE THREAD

**Issue by josegeraldo1** [ShareX/ShareX#2658]
Hello,

It would be nice an option to disable magnifier in annotation screen as it is irritating while you are editing a captured image.
So magnifier would appear only during capturing screen.

Thanks!

**Comment by Jaex** [comment]
You can disable magnifier from here:

![](https://jaex.getsharex.com/2017/08/ShareX_uQqVd1Cn8U.png)

A lot of people can find magnifier helpful even in annotation.

**Comment by josegeraldo1** [comment]
What I mean was to disable magnifier only in annotation screen that is opened after capture.
Magnifier is great during capture, but after that, during image edition, it might be irritating when you don't need it. So I meant to say to have specific option to disable magnifier only in annotation screen after capture. Please see GIF below showing what I mean.
Maybe you could reconsider this issue.
![2017-08-01_16-26-26](https://user-images.githubusercontent.com/20847642/28843711-97b4b05c-76d8-11e7-960b-c060439d860d.gif)

Thanks!

**Comment by jabobian** [comment]
Eight years later, this feature is still not provided, what a pity.
The said disbled magnifier will be activated again when scrolling the scroll wheel. Obviously this checkbox is not a persistant option.
