### ISSUE TITLE
Arrows with different head options

### ISSUE THREAD

**Issue by josegeraldo1** [ShareX/ShareX#2661]
Hi,

It would be great to have more Arrow options like ones below:
- Arrows with 2 heads (1 head in each side).
- Arrow with head in start point (when mouse button is pressed).
- Arrow with head in end point (when mouse button is released).

Thanks,

**Comment by Jaex** [comment]
Arrow with two heads can make sense but what would be point of arrow with head in start point? I mean you can start drawing from end to have same effect.

**Comment by josegeraldo1** [comment]
Yes, arrow with two heads is great and needed in my opinion.
Regarding option to chose if head is in start point or in end would be only to provide still more options for the users. Some like more in start point, others in end point. (but I agree that it is not big deal)
Thanks!

**Comment by Jaex** [comment]
I'm planning to add check box to here for two heads option instead of another drop down menu.

![](https://jaex.getsharex.com/2017/08/ShareX_kqs0Gw31MP.png)

Something like "Arrow heads in both side" maybe?

**Comment by josegeraldo1** [comment]
Yes.. that is it. Looks great!

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/08/ShareX_Dq5JBAX0qg.png)

**Comment by odyskat** [comment]
Hi, I use ShareX 15.0, and I can't find the option for arrowhead n both sides. Was it implemented?
