### ISSUE TITLE
Cleanup for old files in "Screenshot folder"

### ISSUE THREAD

**Issue by josegeraldo1** [ShareX/ShareX#2663]
Hi,

It would be nice to have an option in ShareX to schedule a cleanup for old files in "Screenshot folder".
This cleanup routine could run once per day or every time that ShareX is started.
The number of days to keep the screenshots would be defined by user in the options.

Thanks!

**Comment by Jaex** [comment]
Sorry I'm not planning to add scheduled cleanup. But you can write script to do it yourself.
