### ISSUE TITLE
[Feature Request] Crop final picture after Scrolling Capture

### ISSUE THREAD

**Issue by meiskam** [ShareX/ShareX#2667]
Similar to #2631 but I think this request easier to implement

I'd love to be able to do a "scrolling capture", but then crop the top/bottom of the final capture .. left/right works with "trim edges", but top/bottom messes up combining the images.  Example shown in video: 
[2017-08-03_12-13-38.zip](https://github.com/ShareX/ShareX/files/1197892/2017-08-03_12-13-38.zip)

**Comment by dmxt** [comment]
I 100% support this feature since it reminded me of FireShot perfect execution of scrolling capture, however, you can make a task to open a program with cropping tool after scrolling capture.

**Comment by meiskam** [comment]
bump

**Comment by meiskam** [comment]
bump

**Comment by meiskam** [comment]
bump

**Comment by dmxt** [comment]
https://github.com/ShareX/ShareX/issues/2667#issuecomment-325567117

**Comment by meiskam** [comment]
bump

**Comment by meiskam** [comment]
aight this is the last time i'm bumping this, it's been 3 years, if after that time y'all don't think it's worth doing i'm giving up

**Comment by Norlandz** [comment]
Always wanted such feature. 
Allowing **crop the top/bottom of the image** after a scrolling capture is very common functionality. 
Idk why this is not present in Sharex. 
I have to reload the image into the editor to manually drag & crop a long way & save everytime.
