### ISSUE TITLE
How to use ShareX Solution for Visual Studio 2015?

### ISSUE THREAD

**Issue by Pinguish** [ShareX/ShareX#2668]
I want to test for screen casting but i got a lot of errors

I use windows 10 and visual studio 2015

Do i need to add these ( in the picture's error such as ScreenCaptureLib.dll ) dlls one by one?

and if there any default set before start?

then please tell me in details Thanks

![k-039](https://user-images.githubusercontent.com/24609245/28955073-7a384050-791e-11e7-85e4-9bc767b7211d.png)
![k-040](https://user-images.githubusercontent.com/24609245/28955098-abcc9cce-791e-11e7-929e-cf547874df52.png)

**Comment by campbeb** [comment]
ShareX is using language features of C# 7.0 which are not supported in Visual Studio 2015 - only Visual Studio 2017.
Your easiest solution is to install Visual Studio 2017. If you don't want to do that or can't, then you'll have to edit your local code to not use the new features.

For example, the first screen shot you posted is using inline out parameter declaration (See Out variables on https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/)
To compile in VS2015, you'll have to change it from this:
```
            if (ColorPickerForm.PickColor(Color, out Color newColor))
            {
                Color = newColor;
            }
```
to this:
```
            Color newColor;
            if (ColorPickerForm.PickColor(Color, newColor))
            {
                Color = newColor;
            }
```
You'd have to make that type of change in every location. I believe ShareX is also using expression bodied members and maybe tuples. So you'd have to edit all of those as well.

**Comment by Pinguish** [comment]
Thanks a lot! It really helpful and now I'm using vs 2017 community ver

But I still have troubles with solution build

First the references ( such as Sharex.historylib ...) was not connected automatically

So i delete them and additionally add proper reference then i solve it

But I got another problem like this

![k-043](https://user-images.githubusercontent.com/24609245/29016614-1236d06c-7b8e-11e7-9845-76f464831cce.png)

So I add each cs files but another problem occurred

like this

![k-045](https://user-images.githubusercontent.com/24609245/29018254-65e6e2ae-7b95-11e7-8a30-57511b4e8fb5.png)



I wonder that Is there nothing to add additionally environment setting or reference ? 

Because whenever i add the reference for solving errors and warnings I face endless errors..

If you respond me I'll be grateful for your help

**Comment by campbeb** [comment]
You are doing something wrong. ShareX is the easiest program to build I've ever helped with.
I just redownloaded a clean copy of the source code, opened it in VS2017 and compiled everything without any issues. You shouldn't have to remove or relink any references.

**Comment by Pinguish** [comment]
Well I think that i'm wrong or my computer environment is unclear

so I think that i can't use sharex

Because although i use nuget manager but i got this errors again anyway until now really thank you!

![k-049](https://user-images.githubusercontent.com/24609245/29053736-ad05620e-7c2c-11e7-8e17-df2b9ca556c9.png)

**Comment by campbeb** [comment]
All of those errors are for components that are built from ShareX, not downloaded.
- You did Build / Rebuild Solution?
- Have you tried using a directory path that only contains ASCII characters? (I don't know why Unicode characters wouldn't work)

**Comment by Jaex** [comment]
Why you trying to compile ShareX?

**Comment by Pinguish** [comment]
Yes i tried build and reduild and used only ASCII directory path too..


Because I want to use sharex's video capture function

**Comment by Jaex** [comment]
So you can't use it in ShareX?

**Comment by Pinguish** [comment]
No it really works good. But I mean i wanna make video capture program

And your video capture function looks awesome so I want to use that in my project

**Comment by Scrxtchy** [comment]
video capture is handled by @FFmpeg
It takes the coordinates selected as the values to use when calling ffmpeg over the shell directly. The output file recording is processed back by sharex. ( A little vague description really ).
ShareX itself does not record anything

**Comment by Pinguish** [comment]
Can I use sharex's source partially?
I think that if i can use that partially then my project will go easy

**Comment by campbeb** [comment]
@Pinguish You have to follow the license. https://github.com/ShareX/ShareX/blob/master/LICENSE.txt

**Comment by Pinguish** [comment]
Sorry and Thank you Everyone I reinstall windows 10 and visual studio 2017 then i solved it

I think the older versions have collided with each other.
