### ISSUE TITLE
Colour Profile issue?

### ISSUE THREAD

**Issue by Denyerec** [ShareX/ShareX#2670]
When I screenshot from Photoshop and the file is large enough to trigger a JPG upload, the colours display correctly when opened in Vivaldi web browser (Chromium based). If the screenshotted region is below the size threshold and a PNG is generated, the colours are no longer as they were seen in Photoshop (Example side by side here:  http://www.denyerec.co.uk/stuff/.screencaps/2017-08-04_22-52-49.jpg

I'm assuming it's somehow related to colour profiling, but can't find an option in ShareX to disable it - I was rather naively assuming that ShareX would just blindly copy the screenbuffer region and dump it into a file without concerning itself with active colour profiles, though maybe the profile comes after the stage ShareX  grabs the capture from?

Either way I'd love to know if there's anything I can do in the settings to have them render the same, or if it's just the fact that the PNGs aren't profile tagged and thus will never display correctly on my machine unless opened in Photoshop, perhaps ?

**Comment by campbeb** [comment]
Take a look at #2501 and #1236

**Comment by Denyerec** [comment]
@campbeb I did search and read those items before posting, but I didn't understand well enough from the responses whether there's a "problem" or exactly what's going on and, as they're closed, thought the correct process was to ask again rather than reply? Apologies if I got that bit wrong.

Am I correct in thinking then that JPGs captured will contain an embedded ICC and thus render correctly in supporting applications, whereas the PNG files do not contain the ICC information, and thus will render incorrectly?  I have my monitor calibrated to aRGB emulation space (Eizo CX271) so this makes sense in my head, but then so do a great many other things that may not be correct!

**Comment by campbeb** [comment]
@Denyerec Sorry, I'm not knowledgeable enough on color profiles or what exactly is going on to provide you an answer. I was hoping the linked issues might help you.

Are you saying the the JPG from ShareX contains ICC profile, but the PNG does not (as verified by looking at image properties in an editor or viewer, not visually)? Can you upload 2 sample images?
