### ISSUE TITLE
Custom resolution causes issues on Windows 10

### ISSUE THREAD

**Issue by kraxarn** [ShareX/ShareX#2671]
I have one of my monitors setup so that it displays in 2560x1440, even though it's only 1920x1080. I've done this through the Nvidia control panel. Previously on Windows 7, when trying to capture a region or window with ShareX on that monitor, it all worked fine. Although, on Windows 10 with the same setup, the scaling does all sort of weird things. When first trying to capture a region, the preview bugs out like crazy and scales weirdly. The preview scales down very weirdly like this
![](https://vgy.me/cN670I.png)
Trying to capture something like this also has some very weird behavior where it gets very blurry.
For example, this is how it's supposed to be displayed
![](https://vgy.me/C8is5Z.png)
But it instead gets captured like this
![](https://vgy.me/6MTulU.png)
(They should be the same size)

**Comment by campbeb** [comment]
When you go into Windows Display settings, what resolution does it show?
In ShareX, if you go to Tools / Ruler and then hover over the empty desktop, what dimensions does it show? 
This block: 
![sharex_2017-08-04_19-12-31](https://user-images.githubusercontent.com/1089399/28990226-4b75350e-7949-11e7-8f78-798aca7f1a39.png)

**Comment by KraXarN** [comment]
Windows says 2560x1440
SahreX also says 2560x1440 (For height and width)

**Comment by campbeb** [comment]
This appears to be inherent in Windows, not just ShareX. If I scale up my monitor to 2560x1440 as you did, then the builtin Windows print screen and Snipping Tool give the same type of results.
For example, this is from Windows Alt-Print Screen of just the calculator. You can see that it is scaled in the same way.
![clipboard04](https://user-images.githubusercontent.com/1089399/28996273-f2040a04-79ca-11e7-8cd5-9e7c00b2f2d7.jpg)

It may be difficult or not possible to resolve this as ShareX basically gets the image from Windows, which can't process it correctly either.
