### ISSUE TITLE
Scalling Problem on high Resolution screen

### ISSUE THREAD

**Issue by lvl0-i74134** [ShareX/ShareX#2672]
**Scaling** Problem on **high Resolution** screen (e.g. on Surface pro 4) and cannot be fixed through **new** compatibility option available in updated Windows 10 as it improve UI but effects the functionality.  
**FIX IT PLEASE.**

- **Original**

everithing Small:

![screenshot 88 _li_2](https://user-images.githubusercontent.com/22149938/29007089-5091a5c6-7b11-11e7-88b6-b6c9beefffb6.jpg)

but works:

![screenshot 89 _1](https://user-images.githubusercontent.com/22149938/29007095-7b6443da-7b11-11e7-88d2-b562170933f3.jpg)

- **enhanced**

items have ideal size:

![screenshot 85 _li_2](https://user-images.githubusercontent.com/22149938/29007109-b8853580-7b11-11e7-9786-369871b97ddd.jpg)

nonfunctional:

![screenshot 86 _1](https://user-images.githubusercontent.com/22149938/29007117-dc019224-7b11-11e7-9c78-9993757cd44f.jpg)

**Comment by Stauros-Nicod** [comment]
when you set your 4K monitor to work in 1080p resolution nothing work. Can't use ShareX in my system with any settings. Please, fix it.

**Comment by tehffs** [comment]
Hello,

Same problem here. When I press "Prt Scr", my left screen changes its resolution and "overlay" the other screen" : 

![image](https://user-images.githubusercontent.com/40688444/42083107-33410280-7b8a-11e8-9130-65cd5e08aca4.png)
