### ISSUE TITLE
Searching on Tiny Eye.

### ISSUE THREAD

**Issue by skanskan** [ShareX/ShareX#2676]
Could you add the Customuploader  file for the Reverse Image Search site Tiny Eye, please?

www.tinyeye.com

I've tried but I don't know what to write in the regex field, nor the arguments and headers.

**Comment by Scrxtchy** [comment]
It's tineye, not Tiny Eye, a theropy service 😉 

```
{
  "Name": "tineye",
  "DestinationType": "None",
  "RequestType": "POST",
  "RequestURL": "https://www.tineye.com/search",
  "FileFormName": "image",
  "ResponseType": "RedirectionURL"
}
```

**Comment by Jaex** [comment]
Do you know about this?

![](https://jaex.getsharex.com/2017/08/ShareX_DuwpxW6IhR.png)

**Comment by skanskan** [comment]
Yes I know the Google Image option, but sometimes I also want to try other.

@Scrxtchy  thanks

**Comment by vatterspun** [comment]
> Do you know about this?

I actually hadn't noticed that.  Thanks.

**Comment by Jaex** [comment]
Added it to here: https://github.com/ShareX/CustomUploaders/blob/master/tineye.com.sxcu

**Comment by vatterspun** [comment]
Nice, thanks for adding.

**Comment by cr1901** [comment]
>Do you know about this?

My copy of ShareX doesn't seem to have "Google image search" (or quite a few others!) on right-click:

![image](https://user-images.githubusercontent.com/6418027/42408950-ee1c18da-81a0-11e8-9894-cc130ee6d988.png)

Do I need to enable this in a ShareX setting for right-click context menu?

**Comment by Scrxtchy** [comment]
ShareX currently only supports google image search via URLs from the context menu
Means you need to have your images uploaded for the feature to work
