### ISSUE TITLE
[Feature Request] List of random uploaders

### ISSUE THREAD

**Issue by Bluscream** [ShareX/ShareX#2681]
In addition to the new `$random:` syntax i would like to request a new list where you can select which uploaders to use for random uploading and then you can select 'Random' in the destination menus c:

![](https://justin.took-my-blobs-away-from.me/f3e0c3.png)

**Comment by vatterspun** [comment]
Use case?

**Comment by Bluscream** [comment]
More randomness of course. Counter-Question; whats the usecase of random domains?

**Comment by Scrxtchy** [comment]
write an nginx server config that takes the subdomain and find the image with that name within storage
genius :rofl:

**Comment by Scrxtchy** [comment]
was warned
