### ISSUE TITLE
Question - Command-line way to silent-launch a screenshot without client actions.

### ISSUE THREAD

**Issue by Sashraan** [ShareX/ShareX#2685]
Hi there Jaex!

I tried to search but could not find a way to do the following;

I want to launch ShareX (from command line, or another way if necessary) and have it take a screenshot of a client's full screen and save it to a folder without uploading or giving any pop-ups.

The goal is to have a way to send ShareX to a client's computer, have it take a screenshot and save it in a folder and have another application pull that screenshot for me and my colleagues to view (it's a helpdesk environment).

Right now I'm using the following : 

`[path]\ShareX.exe -m -p -s -sandbox -autoclose -nohotkeys -PrintScreen`

However, this brings up a pop-up asking if the user really wants to upload the file, as the default settings for PrintScreen also upload the file... Is there any way to have it just take the screenshot, copy it to clipboard and save the file to a specified folder and nothing else afterwards?

Thanks for any help! :) 👍

**Comment by Bluscream** [comment]
Try checking out the advanced options, maybe there is a way to suppress that popup

**Comment by Sashraan** [comment]
There is, but in the scenario I would like to use ShareX in, I do not have access to the user's side of things.

The whole point is to have a remote screenshot tool that works when Remote Desktop fails.. so going into advanced options isn't an option, heheh.

Unless there is a way to activate said option from within the command line arguments? I didn't find much about those besides the short https://github.com/ShareX/ShareX/wiki/Command-line-arguments page.

**Comment by Bluscream** [comment]
How would you execute `[path]\ShareX.exe -m -p -s -sandbox -autoclose -nohotkeys -PrintScreen` if you don't have access to the client system?

**Comment by Sashraan** [comment]
Through a command line opened on the client system. Underlying problem being that our Helpdesk tools aren't the most reliable, so remote viewing of a client's screen is sometimes impossible. 

The idea is that if we can get a quick screenshot of the client computer without the pc-illiterate clients needing to do anything, we can see the error message and figure out where to go from there, rather than spend time troubleshooting the remote-connection tools and **then** seeing the error and troubleshooting the true issue at hand.

**Comment by Bluscream** [comment]
When you have command line access you can easily modify sharex's config to not show the popup

**Comment by Sashraan** [comment]
Are there ressources somewhere for me to dive into and understand how to do that?

I feel like asking for the way to do it is cheap, I'd much rather learn how to do it through exploring a thread/collection/book of how to change config files through cmd.

**Comment by Bluscream** [comment]
Documents\ShareX should contain the config files, you just need to search for the right config value

**Comment by campbeb** [comment]
I think maybe a change is needed around that first time upload screen.
 - A command line option to not show it
 - Or an existing command line option prevents it from being shown
 - Or even an optionfor DisableUpload

Have to see what Jaex thinks

**Comment by Bluscream** [comment]
@jaex

**Comment by menzow** [comment]
Why so much effort to take a screenshot without notifying the user? In what scenario do you take these screenshots? It seems a screenshot would only be applicable when in direct communication with the client - may as well tell them to confirm uploading the screenshot to you..

**Comment by stuntguy3000** [comment]
I would love to hear the use case for this also.

**Comment by Sashraan** [comment]
The reason for this is to be able to take a screenshot of a client's screen without the possibility to use remote-connection tools to see the client's screen.

RDP, AnyDesk, TeamViewer, NetOP, pcAnywhere are all tools we have to use where I work and unfortunately there are some times where even with five different ways to connect to a machine, none will work or display the client's screen appropriately. In these cases, taking a screenshot of an SQL error box makes it much faster to troubleshoot and could speed up the process rather than taking extra steps to troubleshoot the remote connection and _then_ take a screenshot.

In other cases, clients aren't available to us, so asking a client to accept a remote control session (AnyDesk) in order to take a screenshot of the error is impossible even if it's just within reach through other remote methods.

**Comment by stuntguy3000** [comment]
How would you trigger the remote execution on a clients machine?
