### ISSUE TITLE
[Feature Request] Provide easy Hotkey ex/import

### ISSUE THREAD

**Issue by Bluscream** [ShareX/ShareX#2687]
![image](https://user-images.githubusercontent.com/3318223/29227783-802c6f86-7ed7-11e7-9a2c-3243860c78b3.png)

Right now sharing hotkeys involves JSON editing which has a big chances of failing for normal users.

**Comment by vatterspun** [comment]
Really?  How often are you exporting hotkeys?  Is this a thing?

If you use the portable version you can just copy over the entire ShareX folder.  Or -- strange as it sounds -- the ShareX\ShareX folder (the profile folder has the same name).

**Comment by Bluscream** [comment]
I mean more to give it to other users, there are hotkeys that automatically add effects and watermarks that other users want to have too.

**Comment by Bluscream** [comment]
@jaex is this too low-prio?

**Comment by Bluscream** [comment]
:(

**Comment by vatterspun** [comment]
Note for someone who might come across this thread in the future: you can easily export settings:

![image](https://user-images.githubusercontent.com/1289134/56045573-15003480-5d07-11e9-81f4-8de2cfcb896f.png)

... and then use the import button below it to integrate those same settings.  This would certainly include hotkeys.

**Comment by Bluscream** [comment]
What if one just wants to export one hotkey?

**Comment by vatterspun** [comment]
> What if one just wants to export one hotkey?

I'm not sure I can think of a way to import/export that wouldn't be more time consuming than just re-entering the hotkey.  If you have a dozen or so specific hotkeys, an import/export tool is certainly warranted, but just one?

**Comment by Bluscream** [comment]
Maybe ill just write a external C# app that can extract single/multiple hotkeys from the main json and import it into another
