### ISSUE TITLE
[Request] Button to test random domains

### ISSUE THREAD

**Issue by Bluscream** [ShareX/ShareX#2688]
I would love to have a button to test if all domain combinations would work. For that it could

1. Upload a file to that CustomUploader
2. Request the file from each of the possible request URL's
3. Show a list with those combinations that failed

**Comment by vatterspun** [comment]
I know I'm turning into a broken record in reply to some of your Feature Requests but what's the use case?  Why random?

**Comment by Bluscream** [comment]
To see if any cominations broke and if yes, which.

Similar to this (but without the need of a extra php server):
![image](https://user-images.githubusercontent.com/3318223/29482968-dfb1c8c4-849b-11e7-979e-2c89a7852c76.png)
