### ISSUE TITLE
Not sure if Issue

### ISSUE THREAD

**Issue by Therealboy** [ShareX/ShareX#2689]
I was just wondering, I had recently downloaded ShareX on a new computer and I was wondering when annotating after a screenshot is there a way to change it so it isn't actually full screen? If so that'd be wonderful if you could tell me how, if not would the devs please try and make this an option, it kills my gaming experience!

**Comment by Bluscream** [comment]
Wut?

**Comment by campbeb** [comment]
See https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879
