### ISSUE TITLE
ShareX does not capture when the mouse is captured by a game.

### ISSUE THREAD

**Issue by RileyGuy** [ShareX/ShareX#2692]
This used to work until the most recent update as of the time of posting this. When the mouse is being used by a game it will not trigger the region capture like it used to. Why is this? Full-screen capture works fine, as well as entire desktop capture but not region capture and it's very annoying.

**Comment by PremiumSaltine** [comment]
This just started in 11.9 for me. I play Garry's Mod and have to open chat, which releases the cursor, before I can do a region capture. Had to go back to 11.8.

**Comment by Jaex** [comment]
@RileyGuy which game?

**Comment by Jaex** [comment]
Can you enable pre release updates and try is this issue resolved:

![](https://jaex.getsharex.com/2017/08/ShareX_kvnsWQQP3p.png)

**Comment by PremiumSaltine** [comment]
works fine now. thank you!
