### ISSUE TITLE
Windows Store Installation doesn't add ShareX Context menu.

### ISSUE THREAD

**Issue by SherifAbdlNaby** [ShareX/ShareX#2694]
Installing ShareX through windows store doesn't add ShareX context menu. there isn't any option inside the app settings to add them too.

**Comment by NovusTheory** [comment]
That's a limitation Windows Store has, it can't be fixed.

**Comment by Scrxtchy** [comment]
Could this be procurated by a batch separate batch file?
Adding values to registry outside of the program. Where executable access is restricted on platforms such a Windows 10 S
