### ISSUE TITLE
[Improvement] Add warning message when turning 'Upload image to host' feature on

### ISSUE THREAD

**Issue by tmvan** [ShareX/ShareX#2699]
The **Upload image to host** feature is good but it could be dangerous when it used in working environment because it could upload the private information if we forget to turn it off.  So please disable feature as default and show an warning message before turn it on or we could display some signal on UI while it is on.  These notification could be turn off in setting to don't bother people don't need it.

**Comment by Jaex** [comment]
There is already warning in first upload which allows user to enable or disable upload function:

![](http://i.imgur.com/exNZDsq.png)

If user presses "No" in that message box then upload disables.
