### ISSUE TITLE
"Annotate image" window show incorrectly.

### ISSUE THREAD

**Issue by Humhah** [ShareX/ShareX#2701]
English isn't my first language,maybe my description isn't so exact.
**My office computer has no independent graphic card.**
And when I finishen capture,the "Annotate image" window show up incorrectly.
It has a strange blank background and a top toolbar(it should show in the left).
And then I can't fullscreen other window until I finishen "Annotate image"

![2017-08-14_16-31-57](https://user-images.githubusercontent.com/26346635/29264116-5f83d45c-810e-11e7-9d9d-60a0e0d7e6fb.png)

## **it's the normal "Annotate image" window in my personal computer.**
![005030fdkg6wp25nw2en6h](https://user-images.githubusercontent.com/26346635/29264428-99683bb2-810f-11e7-8a4b-00bb1cdef8cd.png)

**Comment by campbeb** [comment]
This is due to a new setting that is probably different between your two computers.
See https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879

**Comment by Humhah** [comment]
Thanks,it works.
