### ISSUE TITLE
ImageMagick CLI doesn't work on Action

### ISSUE THREAD

**Issue by hugmanrique** [ShareX/ShareX#2702]
I'm trying to create an action that optimizes my PNG images before uploading. Here's my config:

Access route: `D:\Program Files\ImageMagick-7.0.6-Q16\magick.exe`
Arguments: `%input -strip -alpha Remove %output`
Output ext: (Empty)
Extension filter: `png`
Hidden Window: `false`

I've also enabled the Run actions checkbox on "tasks after capture".

When I upload a pic nothing gets compressed, and if I go to the ShareX logs, I can see the following line:
`Running D:\Program Files\ImageMagick-7.0.6-Q16\magick.exe with arguments: "D:\Users\Hugo\Desktop\PXgkwfj - copia - copia.png" -strip -alpha Remove "D:\Users\Hugo\Desktop\PXgkwfj - copia - copia.png"`

If I try to open cmd and paste the same command, it suddenly works.

**Comment by user6323** [comment]
Do you want to shrink the image, so png file will be smaller?
I don't know how to resolve your issue, but I can describe how I do such a thing.
I use pngquant for this and it's working perfectly.

In actions i added this parameters:
![1503148627s](https://user-images.githubusercontent.com/10479545/29486920-4823722a-8502-11e7-8f57-7ed344137e99.png)

It creates new, shrank file in screenshot folder, but with "s" at the end, near original image.

**Comment by vatterspun** [comment]
Thanks for posting about this.  I'm very interested in this topic.  Possible workaround with PNGOptimizer described here: https://www.portablefreeware.com/forums/viewtopic.php?f=2&t=22181
