### ISSUE TITLE
won't save settings

### ISSUE THREAD

**Issue by zosoro** [ShareX/ShareX#2703]
I have set windows to use My documents path to D:\
I have set ShareX to have a personal folder to D:\user\sharex
And every time ShareX starts, it loses all settings and goes back to using D:\ as a personal folder.

**Comment by Jaex** [comment]
I'm using `D:\ShareX` as my personal folder and don't have any problem. Not sure what is wrong in your setup.

**Comment by zosoro** [comment]
http://i.imgur.com/tuwv7zc.png

**Comment by Jaex** [comment]
I don't see problem in that screenshot.

**Comment by zosoro** [comment]
Again. I dont want D:\sharex, i want D:\vali\sharex. I set it up, it says i need to restart to use it, I restart Sharex and it goes back to D:\sharex
