### ISSUE TITLE
[Feature request] video recording show keys

### ISSUE THREAD

**Issue by idefy** [ShareX/ShareX#2705]
When recording a tutorial or showing how to reproduce an issue, it would be useful the video includes indication as to what is pressed. From mouse clicking and scrolling to short cuts used, this would be very helpful that ShareX automatically capture those and displays them somewhere in the video.

**Comment by Jaex** [comment]
#1040

**Comment by vatterspun** [comment]
Actually the duplicate mentioned in issue #1040 was just about mouse-clicks.  For the request about keypress recording from @idefy, there are a few options that should work with ShareX:

* qipress - http://aalapshah.in/qipress (freeware for non-commercial use)
* Nohboard https://sourceforge.net/projects/nohboard/ - open source but takes up a fair amount of screen real estate

Separate from Sharex, Screen2Gif has some capabilities here http://www.screentogif.com/ but doesn't support audio and FlashBack Express Recorder will do all these things but I really don't recommend it.  It's a borderline demo program meant to just get people to move to the pay version.
