### ISSUE TITLE
Trying to capture an image simply creates a black screen?

### ISSUE THREAD

**Issue by Omen267901** [ShareX/ShareX#2707]
Title. If I try to capture anything my entire screen goes black except for the number in the top left and when I capture the image it's just a black screen.

**Comment by Omen267901** [comment]
No, was attempting to capture Notepad++, then discord, then google chrome. All three caused it,

**Comment by Jaex** [comment]
Are you have anti virus app which could be blocking screen capture?

**Comment by Omen267901** [comment]
No, I have no antivirus unless windows defender is causing the issue.

**Comment by NovusTheory** [comment]
I find this issue odd, the only time I'd ever see black screen is if DRM protected content caught onto a screenshot happening

**Comment by Omen267901** [comment]
http://i.imgur.com/ZyeXDw3.gifv

Here you can see that attempting to record a .gif is met with a black screen.

**Comment by Jaex** [comment]
That gif is recorded using separate application called FFmpeg, which shows problem is not to do with ShareX then. Because both app unable to capture.

**Comment by Omen267901** [comment]
[The issue happens with Image capturing too.](http://i.imgur.com/ROMUPj1.png)

**Comment by Scrxtchy** [comment]
I agree with @NovusTheory. This is an extra-ordinary case. I can fail to see where sharex could be fixed for this issue that many of us would be unable to either replicate, or even in the slightest look at where to start.

but I better ask anyway.
Does snipping tool work

**Comment by Omen267901** [comment]
Snipping tool does not work. It causes the same issue.

**Comment by NovusTheory** [comment]
At least snipping tool does the same thing, that helps sum it up. ShareX isn't the direct issue then. I am unsure what would actually cause such a thing then.

**Comment by Jaex** [comment]
If even snipping tool not works then problem is not to do with ShareX.

**Comment by Omen267901** [comment]
As an extra note, I've managed to fix the issue. Restarting my computer a few times made it fix itself.
