### ISSUE TITLE
Sync off on episode change

### ISSUE THREAD

**Issue by Squeeshy** [ShareX/ShareX#2708]
Recording episodes of a show for easy playback later from a website. (personal use only).
Every time it changes from one episode to the next, the sync of sound & video gets worse.

It starts out perfectly in sync, but gets off ~10-20 seconds when it changes episodes.
Recording works, but we like to be able to have kid's shows play without a huge lag in video and sound as it progresses in episodes.

Running ShareX 11.8 - Screen Recording - Video codec: x264 (mp4) Audio codec: AAC - CRF:30 Preset: Ultra fast - Bitrate: 128k 
Command line preview:
-y -rtbufsize 100M -f dshow -framerate 30 -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 30 -pix_fmt yuv420p -c:a aac -strict -2 -ac 2 -b:a 128k "output.mp4"

**Comment by vatterspun** [comment]
I think this is more likely to get fixed if you list the steps for someone to recreate this.  For example what site was used, what browser / program / player was used, etc.
