### ISSUE TITLE
Azure custom domain support and containers

### ISSUE THREAD

**Issue by altano** [ShareX/ShareX#2710]
These are my settings:
![image](https://user-images.githubusercontent.com/1009/29397134-192c79d6-82d1-11e7-9eb6-95ad6d7a5805.png)

My custom domain for Azure does NOT include the container, though, so the resulting URL which does include the container (/public) is wrong. E.g. I need ShareX to convert the URL:

`http://terriblefiles.blob.core.windows.net/public/XXX`

to

`https://files.terriblefish.com/XXX`

but instead I get

`http://files.terriblefish.com/public/XXX`

I see that the https issue was fixed but is it possible to specify that the container shouldn't be provided as well with the current settings?

**Comment by Scrxtchy** [comment]
should a checkbox be implemented so that the container will not be appended to the returned url?

**Comment by altano** [comment]
I would say that either the checkbox would be definitely be fine, or the most flexible option I can think of is to just let people type in whatever they want to create a custom URL, something like:

```
+----------------------------------------------------------------------------------+
|                                                                                  |
|   Account Name                                                                   |
|   +-------------------------------------------------------------------------+    |
|   | ...                                                                     |    |
|   +-------------------------------------------------------------------------+    |
|                                                                                  |
|   Access Key                                                                     |
|   +-------------------------------------------------------------------------+    |
|   | ...                                                                     |    |
|   +-------------------------------------------------------------------------+    |
|                                                                                  |
|   Container                                                                      |
|   +-------------------------------------------------------------------------+    |
|   | ...                                                                     |    |
|   +-------------------------------------------------------------------------+    |
|                                                                                  |
|   Environment                                                                    |
|   +-------------------------------------------------------------------------+    |
|   | ...                                                                     |    |
|   +-------------------------------------------------------------------------+    |
|                                                                                  |
|   Custom Domain                                                                  |
|   +-------------------------------------------------------------------------+    |
|   | https://files.terriblefish.com/{container}/{path-to-file}               |    |
|   +-------------------------------------------------------------------------+    |
|                                                                                  |
|       Supported Variables in Custom Domain:                                      |
|         * container                                                              |
|         * path-to-file                                                           |
|                                                                                  |
+----------------------------------------------------------------------------------+

```

**Comment by Lego6245** [comment]
If I understand correctly, you have a CDN endpoint that's `https://files.terriblefish.com/` that points to Azure Blob Storage at `http://terriblefiles.blob.core.windows.net/public/`? If that's the case, I feel we should probably just provide the option to mask out the container, instead of a custom domain builder, since you're never going to see, for instance `foo.bar/{path-to-file}/{container}` or whatever.

**Comment by altano** [comment]
That would certainly work for me!

**Comment by Jaex** [comment]
Fixed by #3436

**Comment by Jaex** [comment]
@altano is check box really necessary? In both Amazon S3 and Google Cloud Storage that using custom domain not adds container/bucket name to url. Just adds upload path. And if user really want container name to be added then they can add it manually to custom domain section. Not to mention that way they have full control on position of container.

**Comment by altano** [comment]
The fix looks great and works perfectly, thanks again.
