### ISSUE TITLE
Successfully launch ShareX on Linux Mint 18.2 (help needed) 

### ISSUE THREAD

**Issue by bullik01** [ShareX/ShareX#2712]
![2017-08-18 14-58-18](https://user-images.githubusercontent.com/4389593/29458048-d8631ef4-8425-11e7-908e-f8fc3edd935b.png)

Hello! I successfully launch ShareX on Linux Mint 18.2!
How do configure upload services like "puush"?

**Comment by L1Q** [comment]
Check Destinations (Сервисы загрузок) and either select whatever destination you need or go configure them in Destination settings (Настройки сервисов)

**Comment by oxodao** [comment]
Ah, that's quite nice. Did you launch it through Wine or Mono ?
That is a huge step forward if you got at least screen capture working

**Comment by bullik01** [comment]
Yup, taking screenshots are working.

**Comment by bullik01** [comment]
> Ah, that's quite nice. Did you launch it through Wine or Mono ?
That is a huge step forward if you got at least screen capture working

Mono.
Soon i try to launch it on debian or arch.
