### ISSUE TITLE
Is there a qr reader in this program?

### ISSUE THREAD

**Issue by alidan** [ShareX/ShareX#2716]
More and more games are putting qr's in games, I have no smartphone, and the program already has a qr generator
If there isn't, at least I would like one, if that's not an option at all, can anyone direct me to a lightweight qr reader for windows?

**Comment by Scrxtchy** [comment]
no qr reader in sharex, feels out of scope.

Are you looking for software with Web Camera support? 
I've always used https://www.the-qrcode-generator.com/scan since it saves itself locally into the browser cache for offline usage

**Comment by Jaex** [comment]
#2516

**Comment by alidan** [comment]
Nah, webcam support for qr is kind of useless for me, Just wondering if there is something that can read it from screenshots.

**Comment by Scrxtchy** [comment]
@Jaex We already have an external qr library, if you want to replace gma qr with Zxing's library (which is more widely used throughout a lot of software of many different languages), which is actually updated. This could be beneficial
https://zxingnet.codeplex.com/ vs https://qrcodenet.codeplex.com/

I use their web library for image decoding, as well as their android versions
https://zxing.org/w/decode.jspx

**Comment by Jaex** [comment]
@Scrxtchy Indeed ZXing .Net library looks good and up to date. Added decode support using it now.
