### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by OliBomby** [ShareX/ShareX#2718]
When I try starting up ShareX I get this error:

System.NotSupportedException: De opgegeven padindeling wordt niet ondersteund.
   bij System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   bij System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   bij ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   bij ShareX.Program.CheckPersonalPathConfig()
   bij ShareX.Program.UpdatePersonalPath()
   bij ShareX.Program.Main(String[] args)

ShareX 11.9.1 (Release)

I already tried reïnstalling but that didn't work

**Comment by Scrxtchy** [comment]
`The given path's format is not supported.`
Does the sharex configuration files still exist? these by default are in `My Documents` > `ShareX`

**Comment by OliBomby** [comment]
Yes, they're still there.
