### ISSUE TITLE
Monochromatic Tray Icon to fit Windows 10 style

### ISSUE THREAD

**Issue by roughnecks** [ShareX/ShareX#2719]
It would be cool, thanks.

**Comment by charlesmilette** [comment]
[There you go](https://getsharex.com/img/ShareX_Logo_White_Transparent.png)

You can easily use GIMP, PhotoShop, or an online converter to convert it as .ico for use in Windows

To use, just change the icon of the start menu shortcut (right-click -> open file location -> right-click -> properties -> change icon). You might need to restart ShareX or unpin and repin to taskbar for the changes to take effect

**Comment by roughnecks** [comment]
Thanks, but I'm using the Store App, is this the same?
I've searched for "ShareX.exe" and found it in "C:\Program Files\WindowsApps\19568ShareX.ShareX_11.9.1.0_x64__egrzcvs15399j" but it's not a shortcut and I cannot change icon.

**Comment by charlesmilette** [comment]
You cannot change icons on the Store build.

**Comment by roughnecks** [comment]
>You cannot change icons on the Store build.

Yeah, pretty much why I'm asking for a feature to be added.

**Comment by Scrxtchy** [comment]
We change the icon all the time

how do you think the upload indicator works?

**Comment by charlesmilette** [comment]
Because he wants to change the icon in the taskbar, not the tray.

**Comment by Scrxtchy** [comment]
if you want to edit the taskbar tray, you need to edit the icons in 
`C:\Program Files\WindowsApps\19568ShareX.ShareX_11.9.1.0_x64__egrzcvs15399j\Assets\`

The easy part is getting them
the harder part is putting new ones over the top
![image](https://user-images.githubusercontent.com/12771982/29492559-cbb95238-85c2-11e7-838e-35b71cb504d2.png)

I can tell you if you delete these files, sharex UWP will run without icons, but won't crash 
eg. soundcloud
![image](https://user-images.githubusercontent.com/12771982/29492565-e69e44a0-85c2-11e7-80fe-d390a2f43526.png)

**Comment by roughnecks** [comment]
>He wants to change the icon in the taskbar and the tray, not only the tray.

Where did I write that?
I only want the TRAY icon to be monochromatic.
Icons in the taskbar are all colored, no need to change those.

**Comment by Scrxtchy** [comment]
> Icons in the taskbar are all colored, no need to change those.  

Pretty much what I thought

**Comment by Jaex** [comment]
White icon not looks good as 16x16 because then difficult to differentiate its parts.

**Comment by Scrxtchy** [comment]
Like this a little bit
![image](https://user-images.githubusercontent.com/12771982/29495448-d1deacc2-8602-11e7-8932-0d0919504cac.png)

**Comment by roughnecks** [comment]
I could always install the Desktop App, but automatic updates managed by Windows Store are much better.
In the meanwhile, if @Jaex doesn't feel like doing this change, I'll just keep ShareX hidden in the tray.

Thank you all.

**Comment by Jaex** [comment]
This is the example where 16x16 icon not looks good:

![](https://jaex.getsharex.com/2019/02/bcJu1l4kvD.png)

Separation lines barely visible.

**Comment by Jaex** [comment]
I tried to make separation of parts more visible:

![](https://jaex.getsharex.com/2019/02/dZuU9WxvcU.png)

**Comment by Jaex** [comment]
Added it to here:

![](https://jaex.getsharex.com/2019/02/ShareX_HSPsGFBs8n.png)

**Comment by ErikHumphrey** [comment]
@Jaex Could you make it so the white version still occupies the same amount of space in the 256x256 icon? The white one is 20px taller/wider, so it looks a little bit unsightly in the taskbar due to its size.

**Comment by pocce90** [comment]
@Jaex Is this feature disappeared? I can't find "UseWhiteShareXIcon" in advanced setting anymore...

**Comment by Jaex** [comment]
> @Jaex Is this feature disappeared? I can't find "UseWhiteShareXIcon" in advanced setting anymore...

![](https://jaex.getsharex.com/2022/09/ShareX_Oxp0f1l37L.png)

**Comment by vathanac** [comment]
@Jaex Can I use custom icon instead. Tray icon is big and still look out of place.

![image](https://user-images.githubusercontent.com/87689818/210321774-a893c7bf-8d8c-4e29-a50c-88954e901c78.png)

**Comment by futuremotiondev** [comment]
Is there any way to save or extract the icon that's used when `UseWhiteShareXIcon` is selected? I've tried using Resource Hacker but it's not embedded in `sharex.exe` and I can't find where it's coming from.

I'm trying to make a custom taskbar icon in the same style and [the official icons here](https://getsharex.com/brand-assets) don't include the white version - except for [this](ShareX_Logo_White_Transparent.png), but the "blades" of the icon don't match the `UseWhiteShareXIcon` Icon used in the system tray. The system tray icon has a lot more space between each "blade" of the ShareX fan.

**Comment by Jaex** [comment]
here: https://github.com/ShareX/ShareX/blob/develop/ShareX.HelpersLib/Resources/ShareX_Icon_White.ico
