### ISSUE TITLE
Remove dead pomf clones

### ISSUE THREAD

**Issue by 3k2** [ShareX/ShareX#2724]
https://u.aww.moe/
https://cocaine.ninja
https://desu.sh
https://filebunker.pw/
http://g.zxq.co/
https://p.fuwafuwa.moe
https://pomf.is/
https://u.xpw.us possibly dead??

[here's list of pomf clones](https://docs.google.com/spreadsheets/d/1kh1TZdtyX7UlRd55OBxf7DB-JGj2rsfWckI0FPQRYhE/htmlview)

**Comment by Jaex** [comment]
Tested them now:

Failed uploads (13):

u.aww.moe
biyori.moe
cocaine.ninja
desu.sh
filebunker.pw
g.zxq.co
nya.is
lolisafe.moe
p.fuwafuwa.moe
pomf.is
u.xpw.us
up.che.moe
yiff.moe

**Comment by 3k2** [comment]
I believe dusu.sh changed name to https://doko.moe/ 

I think following should be added. 

https://share.riseup.net/
https://rokket.space/
https://lewd.se/
https://u.teknik.io/

**Comment by sergeevabc** [comment]
@Jaex, indeed, [rokket.space][1]’s config should be added to Destination/File Uploader/Pomf. 

[1]: https://rokket.space/sharex

**Comment by sergeevabc** [comment]
@gphg, they are up, yet “uploads are temporarily disabled”.
