### ISSUE TITLE
Capture window with shadow with more options

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#2728]
For the currently unknown reason I have disabled, but here is the reference point of this issue:

![sharex_2017-08-23_03-38-46](https://user-images.githubusercontent.com/3248782/29604405-66779c5a-87b5-11e7-812d-83384b4a07ca.png)

In Photoshop or simply CSS, we have many options for shadows, check it out [here](https://www.cssmatic.com/box-shadow). 

Is it possible to implement them, or some of them? Right now we only have options for shadow offset.

**Comment by Jaex** [comment]
You can use image effects to add fake shadow like this:

![](https://jaex.getsharex.com/2017/08/ShareX_4vL2Z2GZMU.png)

![](https://jaex.getsharex.com/2017/08/ShareX_scMleUKqgr.png)

**Comment by dmxt** [comment]
@Jaex Thank you. How about rounded corner effect?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/08/ShareX_K2Z8zZcuBE.png)
