### ISSUE TITLE
"Delete file locally" is in "After capture tasks", but it should be in "After upload tasks" instead.

### ISSUE THREAD

**Issue by CoolOppo** [ShareX/ShareX#273]
![](http://i.imgur.com/dgC8ALq.png)

**Comment by blaenk** [comment]
So is there any way to delete the local file once/if it successfully uploads? While allowing Sharex to still display a thumbnail of the capture?

**Comment by deepesharora** [comment]
woud love to know if there ia way to delete the local fie after th upload is successful?

**Comment by deepesharora** [comment]
@Jaex  it woudl be great to have this so we can actually delete the local file after its successfully upload. i'm open to a suggestion from you for a workaround.....
