### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by soRailicious** [ShareX/ShareX#2730]
While starting ShareX the folloiwing msg is coming.

System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.BadImageFormatException: Die Datei oder Assembly "ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
   bei ShareX.TaskSettingsTools..ctor()
   bei ShareX.TaskSettings..ctor()
   bei ShareX.ApplicationConfig..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance[T]()
   bei ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   bei ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   bei ShareX.SettingManager.LoadApplicationConfig()
   bei ShareX.SettingManager.LoadInitialSettings()
   bei ShareX.Program.Run()
   bei ShareX.Program.Main(String[] args)

ShareX 11.9.1 (Release)

**Comment by NovusTheory** [comment]
#1615
