### ISSUE TITLE
Dropbox upload path

### ISSUE THREAD

**Issue by Dubz** [ShareX/ShareX#2731]
Whenever I add spaces to the upload path, the files get moved to a different folder with %20 as the space. Done with the folder name containing a space. Haven't tested file names.

**Comment by NovusTheory** [comment]
Well I can tell you one thing is that %20 is url escape and it's mandatory that it's done like that

**Comment by Dubz** [comment]
I know %20 is url escaped, my only question then is is it Dropbox's doing or ShareX's doing?
