### ISSUE TITLE
Windows DPI scaling results in wrong mouse cursor position in videos and GIFs

### ISSUE THREAD

**Issue by mabbas64** [ShareX/ShareX#2732]
On Windows 10 x64, I'm experiencing this issue where the mouse cursor position is off in Videos/GIFVs when DPI scaling is set to 125%. I'm on a 2560x1440p monitor but I believe this is irrelevant as you can test DPI scaling on any monitor even 1080p.

You can compare the two GIFs (created by shareX screen recording) below, one with DPI scaling set to 100% and one with 125%.

Mouse cursor was on top of the tick-boxes in reality but in video its off in DPI=125% video . 

 
DPI  scaling at 100%:

![170824031k4](https://user-images.githubusercontent.com/2238313/29653874-374701d6-8879-11e7-9bd4-75d2197ff78e.gif)

DPI scaling at 125%:
![170824031k1](https://user-images.githubusercontent.com/2238313/29653873-37462b44-8879-11e7-9372-35690b5d4f0f.gif)

![170824031k2](https://user-images.githubusercontent.com/2238313/29653861-285f6e4c-8879-11e7-9f4e-255f6572b907.jpg)

direct GIFV links:

http://i.imgur.com/JvMR6vW.gifv
http://i.imgur.com/PpNXi0d.gifv

Testing was done on latest ShareX version by this morning.

**Comment by Jaex** [comment]
#1329
