### ISSUE TITLE
Imgur links should use https

### ISSUE THREAD

**Issue by Dyras** [ShareX/ShareX#2733]
Greetings! First of all, thanks for making one of my favorite programs. You are truly a blessing.

Now onto my request: Imgur links don't use https, they always use http even though Imgur supports https. I think you should change this.

https://imgur.com/ <-- Imgur supports https, but ShareX only gives you http links

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/08/ShareX_pldWJMwUfr.png)

**Comment by Dyras** [comment]
*Hides in shame*

**Comment by Dyras** [comment]
@Jaex Shouldn't enabled be default though?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/08/chrome_iTipiC0M41.png)
