### ISSUE TITLE
Record user events functionality (like PSR)

### ISSUE THREAD

**Issue by vatterspun** [ShareX/ShareX#2735]
I'm well aware this might be out of scope but I can't think of another project that would even consider it.  This is not related to #1809 .

**Current behavior**

You have to click a hotkey or interact with the program to take screenshots.  Each screenshot or video is dependent upon the user.

**Requested behavior**

Enable a mode so that everything clicked on takes a screenshot.  Once the mode is stopped, all actions would be saved to a series of screenshots or PDF as a report.  This would be great for bug reports, software testing, HOWTOs and more.
  
The program would take no screenshots unless the user was doing something, meaning the mode could be enabled for hours with nothing saved to the hard drive until the user takes action.

**Potential problems**

This is a slippery slope into a lot of other functionality questions.  For example, if you're writing a howto, it's hard to show when you use the mouse to click-and-drag.  Showing that someone right-clicked on something rather than left-click is also difficult.  Do you change the mouse to a big red dot so it's clear what was selected?
  
**Workaround**

Just take screenshots with autocapture and then go back in with a program that deletes delete duplicates.  Open these images in Word, Powerpoint, (or Libreoffice) and make changes/edits there.

**Why not just use PSR.EXE, which comes with Win7 and above?**

Poor quality, JPEG screenshots.  The program insists on doing the entire screen, and has a one-size-fits-all output that's difficult to edit and won't really open in anything but IE.  There's the non-cheap commercial StepShot, Dr. Explain, and a few others, and more but there are very few freeware tools that even approach this functionality.

**Comment by wanghaisheng** [comment]
any update

**Comment by vatterspun** [comment]
Some alternative free tools (none are open source like ShareX):

* Imago - out of date, but works well on Win7)
* StepsToReproduce - out of date, editor is crashy
* ActivePresenter - works well, freemium software
