### ISSUE TITLE
UAC prompt cancels screen recording

### ISSUE THREAD

**Issue by nyuszika7h** [ShareX/ShareX#2738]
When a User Account Control prompt appears on the secure desktop, it causes ShareX to abort screen recording. I understand the UAC prompt can't be recorded without changing settings not to dim the desktop, but the recording should be simply paused while the prompt is being displayed rather than aborted.

**Comment by Scrxtchy** [comment]
Which recording device are you using? (gdibrab, screen-recorder)

**Comment by nyuszika7h** [comment]
I'm not sure, how do I check? I use whatever the default is.

**Comment by Scrxtchy** [comment]
As I though, it's a GDIGrab issue, Try installing the alternative screenrecorder devices and use them

https://stackoverflow.com/questions/43886350/ffmpeg-fails-to-capture-desktop-when-uac-prompt-appears

**Comment by fredrik-nti-johanneberg** [comment]
Sorry to confirm this issue today with the following configuration:

- ShareX 18.0.1
- ffmpeg version 8.0-essentials_build-www.gyan.dev
- Windows 11 Education 24H2 26000.6584

Could this be related to Windows GPO:s or Intune policy management in our Windows domain?
