### ISSUE TITLE
Scrolling capture improvements

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#2739]
When I was using XP, I used an old program called FireShot. It's still up for download. It had perfectly executed scrolling capture and it even opens a cropper tool¹ after the capture. 

Sadly, on the current version of ShareX cropper tool usually glitches out, miss some pieces or doesn't come up with satisfied capture. You're probably aware of this issue, and I hope this is in somewhere on your todo list.

I'll be pleased to hear from your input on this issue.

_¹ We'll be happy if you add a cropping feature in Output Scrolling Capture window. It's extremely useful, perhaps the most used feature and I _always_ used this feature after scrolling capture. I fully understand that you can create a task to open an image editor to crop, but that's a little clunky experience. In my opinion, the ost valuable is proper scrolling capture and second valuable feature is a simple cropping tool._

**Comment by vatterspun** [comment]
I was sure he Jaex wasn't interested in supporting WinXP but I couldn't find system requirements for the program anywhere.  Finally I found on Steam that the minimum OS is in fact Windows XP:

http://store.steampowered.com/app/400040/ShareX/

**Comment by dmxt** [comment]
@vatterspun I'm not sure what Windows XP has to do with this. Fireshot works just fine on my current operating system, Windows 8.

**Comment by vatterspun** [comment]
@dmxt Yeah I screwed up.  I thought you were saying in that first line that this was an issue with ShareX in XP, but you were just referencing a previously correct feature.

**Comment by dmxt** [comment]
@vatterspun It's okay, no problem. Just hoping for some input from Jaex. Maybe he's trying to correct it? Or it's low on his todo list? Who knows... I'm hoping to know more about his situation and opinion of scrolling capture feature.

**Comment by Jaex** [comment]
FireShot looks like browser addon so it is very easy for it to have perfect scrolling capture support with cropping.

Obviously if I could make scrolling capture better, I would. But also most of  the time it is impossible to make perfect scrolling capture because if something move or stay static in web page then algorithm unable to find match to merge them from correct position. So it is very complicated.

**Comment by dmxt** [comment]
@Jaex When I use them it's not just for websites, it's for various apps
with needs to make a vertical screen shots with scrolling. Detection could
be better as well, since it didnt detect native app scrollbar one time I
used it.

**Comment by vatterspun** [comment]
> When I use them it's not just for websites

What Jaex means is that different applications handle scrolling capture.  When you're just doing scrolling capture for a single application, it's a far, far easier implementation.

You might also test Screenshot Captor (freeware, not open source), though I've had better luck with ShareX.
