### ISSUE TITLE
Hot key doesn't hide shared-x program window

### ISSUE THREAD

**Issue by fullon9** [ShareX/ShareX#2740]
Hi, All
Share-X 11.9.1
OS : windows10 pro

Hot key(prtScreen is assigned to region capture) doesn't hide main window of shared-X.
But Menu command (capture -> region light) HIDE  main window of Shared-X.

Thanks in advance

**Comment by Jaex** [comment]
It is intentional so you can capture main window of ShareX.

**Comment by fullon9** [comment]
Thank you for quick update ...

But I don't understand why pressing hot key for capture region(light)
doesn't hide share-X main window ....
Who want to capture something including share-X main window ?

How about option for this ?

Thanks in advance ...
