### ISSUE TITLE
Configuration doesn't saved correctly

### ISSUE THREAD

**Issue by trhdon123** [ShareX/ShareX#2741]
As mentioned, after made some changes in Application Settings, ShareX just won't save them correctly. 
For example, supposing I change Path -> Shared personal folder from "%documents%\ShareX" to another place then relaunch ShareX. ShareX rarely remembers this as well as it usually turns back to default (%documents&\ShareX) after some time (if succeeded). So I guess other settings I made wouldn't be applied since config files are in Shared personal folder.
I've tried on several PCs but still the same issue. Most of them are on Win10x64Creator, some are Win7x64SP1.
Tried versions were 11.8.0 to 11.9.1.

**Comment by Jaex** [comment]
After configure custom path, you not removing Documents/ShareX folder right? Because inside that folder custom path is stored.

**Comment by truonghoangdon123** [comment]
I both tried remove and leave it there. I checked the ApplicationConfig.json in Documents/ShareX, there's only 2 lines containing path:
[https://ibb.co/c103Wv](url) (didn't touch this)
[https://ibb.co/mAgMJa](url) (was manually edited in text editor so I guess ShareX can't forget anymore 🗡 )
There's no line to change from Documents/ShareX to another path right? I also looked for config files in C:\ProgramFiles.
You may ask me to send any config file if needed.
