### ISSUE TITLE
No "Uplaod with ShareX" option to right click menu on image

### ISSUE THREAD

**Issue by AmazMicio** [ShareX/ShareX#2742]
As I saw here https://github.com/ShareX/ShareX/issues/2370 there's an option to upload images directly on the host (Imgur for example). I remember it on puush. Now I when I right click an image I have't the "Upload with ShareX" option, what can I do?

**Comment by NovusTheory** [comment]
What version of ShareX did you grab? Windows 10 Store edition or other?

**Comment by AmazMicio** [comment]
11.9.1

I'm using Windows 10.

**Comment by Scrxtchy** [comment]
Where did you download sharex from?

**Comment by AmazMicio** [comment]
From ShareX official website.

**Comment by ErikHumphrey** [comment]
Do you have `Show "Upload with ShareX" button in Windows Explorer context menu` checked in the Integration section of application settings?

**Comment by AmazMicio** [comment]
Ok fine I got it, sorry, it wasn't checked. Thank you.

**Comment by Keavon** [comment]
I don't see `Show "Upload with ShareX" button in Windows Explorer context menu` in *Application Settings* > *Integration*. All I see is `Run ShareX when Windows starts`. How can I get the "Upload with ShareX" explorer shell extension? Thanks.

**Comment by Scrxtchy** [comment]
These controls are missing if you are using the application from the Windows Store
https://github.com/ShareX/ShareX/blob/9ff1d0690245e4f8ecb94b89e8d5c09d588e3e31/ShareX/Forms/ApplicationSettingsForm.cs#L129-L143

**Comment by Keavon** [comment]
I'm pretty darn sure I had the regular installer version of ShareX installed, not through the Microsoft Store or elsewhere. But I just uninstalled ShareX (thanks for the settings export/import feature to make that easier) and then reinstalled it successfully. Now the *Application Settings* > *Integration* area has lots of choices and the context menu entry shows up as expected. Glad it's working now at least!
