### ISSUE TITLE
[Feature Request] Set Window Size

### ISSUE THREAD

**Issue by YipYipX4** [ShareX/ShareX#2743]
Hi,

First of all, thank you for such a great tool!

I'd like to request a simple but useful feature:  Set Window Size

Prior to recording a window (or snapping window-based screenshots), I'd like to set the window to a standard size so that all of my recordings have the same resolution.  It would be great to be able to be able to use UI similar to the Ruler function to set the size of a window (or UI that shows a list of windows like the Capture->Window->... function).  Sizes could be selected from a list of pre-defined options or the user could enter any valid values for width and height.  If you use a list of windows, then the list of sizes, plus "Custom..." could be an additional pop-out menu.

I did look for this function, but couldn't find it.  If it is already there, please let me know.

Thanks,
Walt

**Comment by Jaex** [comment]
This is what you need I think:

![](https://jaex.getsharex.com/2017/08/ShareX_agGFIojIfD.png)

**Comment by YipYipX4** [comment]
I tried that out, but it does not affect the target window size -- it only causes the capture region to snap to those various pre-defined sizes.

Let's say I'm running my desktop at 1200p, but I want to record a session of Visual Studio (or any other app) running at 720p (the screen recorder function already makes it easy to record just one window).  I'd like to adjust the non-maximized (restored) size of my Visual Studio window to exactly 720p (1280x720) including title bar and status bar.  I could try to do this by hand, but I'll most likely be off by a few pixels.  I could then check with the Ruler tool, and then make adjustments again, but it would be difficult to exactly hit 720p.

One possible UI for this would be:
Tools ->Set Window Size ->(menu listing open windows) -> (menu listing pre-defined sizes, plus "Custom...") 
Then, if "Custom..." is selected, show a dialog to input precise width and height, then set the selected window to the specified resolution.  Or, just use the same list of resolutions provided in your screenshot (which can already be customized).

FYI, web developers may also find this function useful for testing web sites at various specific resolutions (although Chrome helps by showing the [page] window size when resizing with the dev tools open).

**Comment by Jaex** [comment]
Web developers never need this function because there is built in feature for it in Chrome: https://jaex.getsharex.com/2017/08/chrome_a1md8ZlBXk.png

**Comment by YipYipX4** [comment]
That feature in Chrome does not actually resize the outer window (including the window "chrome").  It resizes the client area and puts a dark background around the client area (it also changes the media type, affecting the page rendering).  Thus, even for Chrome, if I want to record a training video at exactly 720p and I want to include the tabs and address bar as part of the training video (so the full window size is 720p), then this feature would be useful.

Plus, some web developers still have to support Internet Explorer or other browsers that don't have this feature built-in.  And, of course, there are millions of other apps that don't have built-in capability to set the window size to specific sizes, so I think it makes a lot of sense to have this feature in ShareX.

Also when creating documentation for an application, it would look better if all of the screenshots of an application have the same image dimensions, so prior to pressing Alt+PrintScreen, I'd like to set the window size to some pre-determined size suitable for the documentation format.

Here's a mock-up of the UI I proposed:

![image](https://user-images.githubusercontent.com/2667349/29933713-829dae0a-8e2d-11e7-94e2-e3e26e8dd4fb.png)

The menu of window dimensions can come from the same customizable list of dimensions for the capture region snap sizes.

**Comment by campbeb** [comment]
This can be done fairly easily, but I'm not sure it will be useful for most users.
![2017-09-02_13-40-27](https://user-images.githubusercontent.com/1089399/29997561-827e99e4-8fe4-11e7-87bf-e97d8ea81862.gif)

**Comment by YipYipX4** [comment]
Well, I most often use this tool for snapping screenshots of applications for documentation, recording training videos, or capturing a UI bug for an issue report.  I understand that a big focus of the tool is uploading & sharing images, and not everyone would care about the precise resolution of window screenshots.  I can't think of another tool more suitable for this feature, though.

If you are concerned about keeping the UI simple, then maybe the feature could be hidden by default and enabled with a checkbox under settings?

Thank you for considering this request!

**Comment by 3Rton** [comment]
So where did this feature disappear to? It is gone in 12.0

**Comment by Solarbotics** [comment]
That is /almost/ a perfect solution for an issue I'm having. I need to add the aspect-ratio into this mix. Gonna talk to my C# dev tomorrow... (yay!)

**Comment by Solarbotics** [comment]
Nope. Did some digging around, and where we _thought_ was the 1:1 ratio doesn't compile it to the default 4:3 we want. If any dev can point out where in the source that 1:1 ratio is set, we'd appreciate it!
