### ISSUE TITLE
[Enhancement]A "delete file locally" option in the after upload tasks 

### ISSUE THREAD

**Issue by ajloveslily14** [ShareX/ShareX#2745]
Think this would be a good addition for those who like to see the image preview of what they captured, but don't like saving every image they capture to their documents folder. So add a delete file locally option to the "after upload tasks" drop down so it still shows the image preview, but doesn't keep the saved image. I have tried to set delete file locally and save image to file but that makes it not show the preview.

**Comment by AlbinoGeek** [comment]
Can confirm, even if using upload; the thumbnail preview doesn't happen.

[After Capture Tasks](https://drive.google.com/file/d/0B3qkg1GEKCmXN05xQjYzVHo3dVU/view?usp=drivesdk)

**Comment by ajloveslily14** [comment]
Still hasn't been fixed

**Comment by AlbinoGeek** [comment]
+1

**Comment by ajloveslily14** [comment]
its a feature request it can't be unstable

**Comment by Jaex** [comment]
Fixed by #3638

**Comment by ajloveslily14** [comment]
I assume this will come into effect in the next update? I don't see anything in 12.2
