### ISSUE TITLE
Error: Could not write image to path

### ISSUE THREAD

**Issue by Azure-the-Malk** [ShareX/ShareX#2747]
This is an error that has been persisting for months now after many months of working perfectly.. 
![image](https://user-images.githubusercontent.com/9307663/29997888-4a983804-9062-11e7-9b1e-7dad0b7bbc14.png)

Every time I capture an image I get this error, and I have to upload it again from clipboard, however video capture seems to work fine - I'd hoped it would be fixed with an update, or that there'd be some info on what's going on and how to fix it, but no luck so far..

**Comment by dannygraaff** [comment]
Same issue here unfortunately..

**Comment by Jaex** [comment]
#2760

**Comment by Jaex** [comment]
Looks like Bitdefender have new feature called "safe files" and it causing this permission issues recently to users. Disabling that feature fixed problem in those users.

But in any case if there is permission error, it is never to do with ShareX.

**Comment by dcomtois** [comment]
To get rid of the blocking rule, go to Bitdefender > Protection - View Features > Safe files - Application Access ; then toggle the switch to allow ShareX (or add to programs list if ShareX is not showing)

**Comment by dn1M** [comment]
Go to Windows Defender, then go to Virus & threat protection > then Virus & threat protection settings > then disable Controlled folder access.

**Comment by Quavelen** [comment]
> Go to Windows Defender, then go to Virus & threat protection > then Virus & threat protection settings > then disable Controlled folder access.

@dn1M, thank you for this. I started getting this issue yesterday, and I couldn't for the life of me figure out why it was refusing to create the file. Especially since it had been functioning perfectly fine for me since 2015 lol. Weird how Windows randomly decided to enable that setting yesterday. 

Also, sorry for gravedigging an old issue. Just wanted to express my thanks.

**Comment by bradley-newman** [comment]
- Exit ShareX
- Go to 
    - Windows Defender
    - Open Windows Defender Security Settings
    - Virus and Threat Protection
    - Virus and Threat Protection Settings
    - Controlled folder access > Allow an app through Controlled folder access.
    - Add and allowed app and navigate to ShareX.exe.
- Restart ShareX

**Comment by jdroo** [comment]
> 
> 
> Go to Windows Defender, then go to Virus & threat protection > then Virus & threat protection settings > then disable Controlled folder access.

That fixed it for me, tho it's strange that I had to do this all a sudden, I changed nothing, and it was working fine... Why is this a problem all a sudden?

**Comment by jdroo** [comment]
> 
> 
>     * Exit ShareX
> 
>     * Go to
>       
>       * Windows Defender
>       * Open Windows Defender Security Settings
>       * Virus and Threat Protection
>       * Virus and Threat Protection Settings
>       * Controlled folder access > Allow an app through Controlled folder access.
>       * Add and allowed app and navigate to ShareX.exe.
> 
>     * Restart ShareX

That fixed it for me, tho it's strange that I had to do this all a sudden, I changed nothing, and it was working fine... Why is this a problem all a sudden?

**Comment by PLASMAchicken** [comment]
Just faced this after Avast Antivirus updated to latest Version, disabling Avast Anti Virus fixed it.

**Comment by deepakfialok** [comment]
> * Exit ShareX
> * Go to
>   
>   * Windows Defender
>   * Open Windows Defender Security Settings
>   * Virus and Threat Protection
>   * Virus and Threat Protection Settings
>   * Controlled folder access > Allow an app through Controlled folder access.
>   * Add and allowed app and navigate to ShareX.exe.
> * Restart ShareX

This has solved for me.... Thank you very much for the step by step guide for saving thousands of combined hours of people scratching their head.

**Comment by dylanh724** [comment]
Controlled folder access is OFF - was working fine until I updated ShareX (today).

**Comment by ghanisch** [comment]
same here, Win10. There has to be some other Acess Problem...
> Controlled folder access is OFF - was working fine until I updated ShareX (today).
