### ISSUE TITLE
Slow mouse response

### ISSUE THREAD

**Issue by svnpenn** [ShareX/ShareX#2748]
I am coming from SnagIt, and I quite like ShareX, but I have noticed 1 issue (Windows):

If I used Fixed size region mode, the program seems to lag a little when I am moving the rectangle around

I even deselected:

1. Show position and size info
2. Show magnifier

Can I change some setting to get faster response?

**Comment by Jaex** [comment]
You probably have multi monitors which could be decreasing FPS. When I enabled fixed region mode, fps not even changed at all. So in general your fps must be low.

**Comment by svnpenn** [comment]
my point is that SnagIt rectangle movement is smooth - ShareX is slower response - not huge difference, but noticeable

**Comment by Jaex** [comment]
Is this smooth?

![](https://jaex.getsharex.com/2017/09/chrome_mgjIdujhQT.png)

**Comment by svnpenn** [comment]
That seems better, but I dont see how to do "Region (Light)" with "Fixed size region mode"

**Comment by Jaex** [comment]
Because it is light, it don't have those extra features, otherwise it wouldn't be light.

**Comment by svnpenn** [comment]
Hm - seems we are at an impasse - if you think of anything else let me know - thanks

**Comment by svnpenn** [comment]
I updated my graphic driver - it seems to have helped - probably part of the problem is I am running two monitors off a splitter rather than dual output graphic card - thanks
