### ISSUE TITLE
Unable to record GIFs

### ISSUE THREAD

**Issue by CJampion** [ShareX/ShareX#2749]
When I attempt to record a GIF, the screen recording box pops up, and stays at 00:00:00, with the STOP and ABORT buttons not functioning. After a few seconds, I will receive **this error.** I have fully updated my software, along with uninstalling/reinstalling multiple times.

ffmpeg version N-87130-g2b9fd15 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 74.100 / 55. 74.100
  libavcodec     57.104.100 / 57.104.100
  libavformat    57. 79.100 / 57. 79.100
  libavdevice    57.  8.100 / 57.  8.100
  libavfilter     6.101.100 /  6.101.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, dshow, from 'video=screen-capture-recorder':
  Duration: N/A, start: 32200.775000, bitrate: N/A
    Stream #0:0: Video: rawvideo, bgr0, 38x44, 15 fps, 15 tbr, 10000k tbn, 10000k tbc
C:\Users\Unive\Documents\ShareX\Screenshots\2017-09\2017-09-02_22-03-32.mp4: Permission denied
leaving aero on

**Comment by Scrxtchy** [comment]
Does regular screen recording work?
I'd be surprised if it does

**Comment by CJampion** [comment]
Nope, here's the error.



ffmpeg version N-87130-g2b9fd15 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 74.100 / 55. 74.100
  libavcodec     57.104.100 / 57.104.100
  libavformat    57. 79.100 / 57. 79.100
  libavdevice    57.  8.100 / 57.  8.100
  libavfilter     6.101.100 /  6.101.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, dshow, from 'video=screen-capture-recorder:audio=virtual-audio-capturer':
  Duration: N/A, start: 38693.377000, bitrate: 1536 kb/s
    Stream #0:0: Video: rawvideo, bgr0, 680x428, 30 fps, 30 tbr, 10000k tbn, 10000k tbc
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[dshow @ 0000000001ec3340] real-time buffer [screen-capture-recorder] [video input] too full or near too full (67% of size: 100000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 1 times
[dshow @ 0000000001ec3340] real-time buffer [screen-capture-recorder] [video input] too full or near too full (88% of size: 100000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 8 times
[dshow @ 0000000001ec3340] real-time buffer [screen-capture-recorder] [video input] too full or near too full (97% of size: 100000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 7 times
[dshow @ 0000000001ec3340] real-time buffer [screen-capture-recorder] [video input] too full or near too full (100% of size: 100000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 29 times
C:\Users\Unive\Documents\ShareX\Screenshots\2017-09\2017-09-02_23-51-42.mp4: Permission denied
[dshow @ 0000000001ec3340] real-time buffer [screen-capture-recorder] [video input] too full or near too full (100% of size: 100000000 [rtbufsize parameter])! frame dropped!
leaving aero on






      - CJ



-----Original Message-----

**Comment by Scrxtchy** [comment]
Yeah, as expected, for some reason ffmpeg is getting Permission issues when writing files to your ShareX Documents folder. I can't really explain why either.

**Comment by Jaex** [comment]
Are you using Bitdefender?

**Comment by MantieReid** [comment]
Hello, 
I had the same problem too. Turns out it was Bit defender denying it access from the folder. 

![seccenter_2018-05-31_20-13-31](https://user-images.githubusercontent.com/21320755/40814635-532cfef0-650f-11e8-84f1-572b8c1a3bc8.png)


The solution was to allow it access via bit defender. 
![2018-05-31_20-13-43](https://user-images.githubusercontent.com/21320755/40814639-5cd94ed6-650f-11e8-95ff-2876c6b52ba9.png)

**Comment by drewgato** [comment]
The Bitdefender call was spot on - thank you.

**Comment by woothie** [comment]
I also got this error, but on Windows 10. I do not have Bit defender, but I do have AVG. Recording worked just fine yesterday before a reboot, but today I got this exact error. After running ShareX as administrator and trying to record again, AVG reared it's ugly head and told me now (but not before I started ShareX as admin??) that it had blocked ffmpeg.exe from writing to Documents. This might be useful for anyone else who might hit this issue in the future. 

In order to solve it, you could either move the destination folder for your recordings to somewhere that isn't Documents, or add ShareX/Tools/ffmpeg.exe to the whitelist of your antivirus which will allow it to record into the Documents folder. I did the latter.

**Comment by blanchae** [comment]
I know this is an old thread but I ran into the same problem in 2020. It was Avast AntiVirus stopping ffmpeg from writing to the destination folder. If you have Avast Notification's disabled, you won't see the message saying that the anti-virus is protecting you.

**Comment by Popedigoz** [comment]
how do I allow antivirus or malwarebytes to write on the destination folder? how do I even check if they were the problem

**Comment by blanchae** [comment]
Your antivirus should have a user interface that has a quarantine section or something indicating that it is blocking a program. You may have to add the program to a list of exceptions. This is something you will have to figure out depending on your antivirus program.

**Comment by Aholicknight** [comment]
![image](https://user-images.githubusercontent.com/7843719/104515087-e8eaa500-55b7-11eb-8165-7c8894a34381.png)
Adding ffmpeg to the Ransomware shield allowed apps fixes this for Avast.
