### ISSUE TITLE
[Enhancement] Allow auto-removal of whitespace borders from region captures

### ISSUE THREAD

**Issue by pnacht** [ShareX/ShareX#2757]
Frequently when capturing an image region, it is relatively troublesome to capture precisely the image we want and instead we capture the image and some "padding" around it. An After Capture task to automatically remove this padding would we useful. This could be done by checking if the padding along each side of the region (first row/column of pixels along each side) is of the same color and, if so, deleting that entire row/column, and repeating until a difference is found.

For instance, imagine I captured the following image (a structural force diagram, if you're interested):

![image](https://user-images.githubusercontent.com/15221358/30214083-11e3c646-94a3-11e7-9898-62dc8a293fb6.png)

I was sloppy, and collected a lot of padding, especially on the right-hand border. Really, all I wanted was:

![image](https://user-images.githubusercontent.com/15221358/30214088-163cd78c-94a3-11e7-927a-63d5373308b8.png)

Currently, I need to capture the image, throw it into Paint.NET and then trim it there (Shift+S and click to select the entire margin, Ctrl+I to invert the selection (to become everything **but** the margin), and Ctrl+Shift+X to crop the image).

An After Capture task could speed this process up significantly, which would be nice.

I know that Snagit Editor already has this functionality ("Auto Trim"): https://support.techsmith.com/hc/en-us/articles/215851598-Remove-Unwanted-Areas-from-an-Image

**Comment by Jaex** [comment]
This can be done for single color for example I was using transparent color to remove empty pixels around image. But doing it for all colors will be problematic like you told checking similar colors. That can yield incorrect results.

**Comment by Jaex** [comment]
There is few auto crop methods which can yield different results. Can you test this image https://jaex.getsharex.com/2017/11/qmMbstq9HH.png in Snagit auto trim and show me the result. That way I can know what kind of trim method you prefer.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/11/IJv7xaxZXM.gif)

**Comment by pnacht** [comment]
Yeah, Snagit uses the most common method: it checks each side independently and crops it. With the image you gave me, repeating the process chips away at the image, as can be seen in the attached images.

![1](https://user-images.githubusercontent.com/15221358/33346686-834b883a-d488-11e7-8481-5a142b9ce976.png)

![2](https://user-images.githubusercontent.com/15221358/33346709-8f3f937a-d488-11e7-9c46-cce93ce35651.png)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/12/pm4xMpykor.gif)
