### ISSUE TITLE
Option to "pause" while screen recording

### ISSUE THREAD

**Issue by jaitjacob** [ShareX/ShareX#2758]
Currently, the application allows only to "Stop" or "Abort" while you are recording the screen. Please add the option to "Pause" also. This adds to the usability of the software.

**Comment by campbeb** [comment]
Same as #205

**Comment by jaitjacob** [comment]
yeah, sorry my bad.

**Comment by campbeb** [comment]
It can be worthwhile to bring it up / look at it again as that was 3 years ago.
