### ISSUE TITLE
屏幕gif录制不受设置页面的nvenc模式与比特率控制

### ISSUE THREAD

**Issue by 1265578519** [ShareX/ShareX#2759]
屏幕gif录制不受设置页面的nvenc模式与比特率控制
![1](https://user-images.githubusercontent.com/6442439/30249330-11621ecc-966d-11e7-922f-1dc81408d542.jpg)

**Comment by Scrxtchy** [comment]
GIF recording using it's own basic configuration on the previous screen, the screen recording option on the menu follows this option

![image](https://user-images.githubusercontent.com/12771982/30249799-b81a30b0-9686-11e7-8c64-af3979a35812.png)

**Comment by 1265578519** [comment]
General
Complete name                  : E:\新建文件夹\ShareX-portable\ShareX\Screenshots\2017-09\2017-09-10_22-33-19.mp4
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/iso2/avc1/mp41)
File size                      : 65.0 MiB
Duration                       : 22 s 200 ms
Overall bit rate               : 24.6 Mb/s
Writing application            : Lavf57.78.100

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High 4:4:4 Predictive@L4
Format settings, CABAC         : No
Format settings, ReFrames      : 1 frame
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 22 s 200 ms
Bit rate                       : 24.6 Mb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 5.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:4:4
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 2.369
Stream size                    : 65.0 MiB (100%)
Writing library                : x264 core 152 r2851 ba24899
Encoding settings              : cabac=0 / ref=1 / deblock=0:0:0 / analyse=0:0 / me=dia / subme=0 / psy=0 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=0 / threads=4 / lookahead_threads=4 / sliced_threads=1 / slices=4 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=250 / keyint_min=5 / scenecut=0 / intra_refresh=0 / rc=cqp / mbtree=0 / qp=0


通过gif录制功能生成的临时mp4文件，看到录制出来的使用是x264而不是nvenc，并且使用了cqp不可控制码率模式，因此Bit rate很高，文件非常巨大。导致出现的gif文件也异常巨大。
![2](https://user-images.githubusercontent.com/6442439/30249923-816522c2-9678-11e7-88e9-8bce57f4a23e.jpg)

**Comment by 1265578519** [comment]
@Scrxtchy ...
