### ISSUE TITLE
Cant save images as file / installation problems

### ISSUE THREAD

**Issue by MayorRev** [ShareX/ShareX#2760]
This is a two part issue but they both seem to be in the same category:

1: Attempting to capture an image via usual methods results in this error: 

![sharex-error](https://user-images.githubusercontent.com/31830867/30253162-834b247c-964d-11e7-81b1-45b3f456883d.png)

2. Reinstalling ShareX results in this error midway through: 

![sharex-error-install](https://user-images.githubusercontent.com/31830867/30253166-98b5293e-964d-11e7-9301-df227636473b.png)

I've attempted to make the screenshots folder non-read-only but the checkbox for it always resets to a black square. This is apparent with all folders in my PC. I have also attempted multiple methods of running ShareX as an administrator, but to no success.

**Comment by Arze1** [comment]
sharex dosnt have access to the path sharex is trying to save in

**Comment by MayorRev** [comment]
How would I go about granting access to it?

**Comment by Jaex** [comment]
Looks like Bitdefender have new feature called "safe files" and it causing this permission issues recently to users. Disabling that feature fixed problem in those users.

But in any case if there is permission error, it is never to do with ShareX.

**Comment by Jaex** [comment]
#2747
