### ISSUE TITLE
ShareX FFMPEG Error

### ISSUE THREAD

**Issue by MoistLemon** [ShareX/ShareX#2761]
Not too sure why this is happening as it was working fine yesterday : 

![image](https://user-images.githubusercontent.com/31858581/30284573-2b7e0c98-9713-11e7-9be9-881b90e78050.png)

Using latest Windows 10 version (1703 i think) and trying to record a window

Thank you for the help :)

**Comment by Scrxtchy** [comment]
There is no error within this screenshot's state

**Comment by MoistLemon** [comment]
This is all that pops up when I try to record anything, I see the timer in the bottom left of the window but it stays stuck at 0, then this appears and nothing else happens. I've tried reinstalling etc. but nothing is helping?

**Comment by Scrxtchy** [comment]
Post a screenshot of your Screen Recording Settings perhaps?

**Comment by Jaex** [comment]
Try installing this previous stable build maybe it will work: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.2-win64-static.zip

**Comment by MoistLemon** [comment]
I've run the .bat file in that download but still getting the same error, is there something else I need to do to get it onto the previous build?

Sorry for all the questions, not too familiar with this stuff

**Comment by Scrxtchy** [comment]
Did you replace the ffmpeg executable that sharex uses from the one inside the zip?

**Comment by MoistLemon** [comment]
Yep, now I get this error, it's slightly different : 

![image](https://user-images.githubusercontent.com/31858581/30373208-6f4ef26e-9878-11e7-91e8-ccfbdbe89869.png)

**Comment by Scrxtchy** [comment]
ahh, please (re)install the screen-capture-recorder utilities

**Comment by MoistLemon** [comment]
I reinstalled ShareX but still getting the error, is the screen-capture-recorder utilities something different?

**Comment by Scrxtchy** [comment]
yes
![image](https://user-images.githubusercontent.com/12771982/30373493-d0b99a26-98c4-11e7-9de9-c1338de28752.png)

**Comment by MoistLemon** [comment]
Just did that and it's gone back to the first error again

**Comment by Scrxtchy** [comment]
Try switching the video source to GDi Grab, test a recording using that
Then try again with screen-capture-recorder

**Comment by MoistLemon** [comment]
When I press the "Test with CMD" button with GDI Grab selected it comes up with this error : 
![image](https://user-images.githubusercontent.com/31858581/30374002-397ca5b6-987b-11e7-8e5e-f51dc15bc560.png)

If I switch it back to screen-capture-recorder and do the same it says this : 
![image](https://user-images.githubusercontent.com/31858581/30374040-6121eb30-987b-11e7-8a48-84ec8dfc588f.png)

Thank you for all your help by the way it is really appreciated :)

**Comment by Scrxtchy** [comment]
Did you set your audio capture to anything? Looks like that's failing
Turn it to None for now
![image](https://user-images.githubusercontent.com/12771982/30374092-0c4937a2-98c7-11e7-9146-242dac8b1857.png)

**Comment by MoistLemon** [comment]
Thank you :) The video recording is working now :)

I can add audio after which is what I was planning on doing anyway

Thank you so much again :)

**Comment by Scrxtchy** [comment]
Re-enabling the audio device may fix it, if windows confused it in the background, as it's reference maybe be properly updated now. But can't say that it would be the truth

**Comment by MoistLemon** [comment]
Tried re-enabling it and it just came up with the same error as before, no big deal though just glad I can record :)

**Comment by Ristarchik** [comment]
Only such parameters help. In other cases, as on the bugs above.
[https://puu.sh/xGip3.png](url)

**Comment by laggingreflex** [comment]
Was getting the same error, I switched from "screen-capture-recorder" to "GDI grab" and it worked for me.

![image](https://user-images.githubusercontent.com/2523987/62333963-50f01d00-b4e3-11e9-990d-a07b4e61fae3.png)

**Comment by G3Kappa** [comment]
I am also getting the same error but switching to GDI grab doesn't help.

However, I can shed some light on the problem. This error occurs when I switch audio drivers (e.g. when selecting ASIO4ALL and then going back to the system drivers). Nothing short of a system reboot seems to fix this. I've tried disabling my output peripherals to no avail. I also use virtual audio cable, which I thought could be part of the problem, but even after disabling all virtual peripherals I still can't get to fix this without rebooting ffmpeg.

**Comment by arhun** [comment]
https://d.radikal.ru/d38/2010/34/62cdff5edac4.jpg
Hello, when the "gif" picture gives an error. I reinstalled the program, an error still comes out. How to fix?

**Comment by NNTin** [comment]
Experiencing same issue. I've installed ffmpeg.exe in C:\Users\nguye\Documents\ShareX\Tools. Either manually or automatically through ShareX. I did try multiple versions of ffmpeg.exe including latest one.

I did go into the settings 
![image](https://user-images.githubusercontent.com/18033169/103412705-bb910680-4b76-11eb-9b03-9c7743bc978f.png)

and manually set the video and audio source etc. Nothing helped.
Here are my error logs:

```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[gdigrab @ 0000021f34f4ebc0] Capturing whole desktop as 393x217x32 at (504,410)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1609422345.676617, bitrate: 40941 kb/s
    Stream #0:0: Video: bmp, bgra, 393x217, 40941 kb/s, 15 fps, 15 tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0000021f34fff340] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000212a9cdcb40] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000212a9cdcb40] moov atom not found
C:\Users\nguye\Documents\ShareX\Screenshots\2020-12\2020-12-31_14-45-45.mp4: Invalid data found when processing input
```

doing a normal screenshot, scrolling screenshot works fine. Video capture ffmpeg and gif are not working for me.

**Comment by Scrxtchy** [comment]
> [mov,mp4,m4a,3gp,3g2,mj2 @ 00000212a9cdcb40] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
> [mov,mp4,m4a,3gp,3g2,mj2 @ 00000212a9cdcb40] moov atom not found

According to a post on Reddit, the moov atom is placed at the end of the file (by default) and this error usually pops up if the recording was terminated abruptly for any number of reasons.
there is a suggestion to add the `-movflags faststart` flag to your command, as this will put the moov atom at the start of the file, not the end, but this is done on a second pass, I am unsure how much this will help as the operation that is interrupting the recording is not defined anywhere

**Comment by NNTin** [comment]
![image](https://user-images.githubusercontent.com/18033169/103413661-d5344d00-4b7a-11eb-8a43-ad380551eea9.png)

I don't know how relevant it is. It fails writing the file already. That error might be related from reading an invalid file format.

**Comment by arhun** [comment]
I resolved this issue a long time ago. Thank you!



чт, 31 дек. 2020 г. в 20:15, NNTin <notifications@github.com>:

**Comment by RomyTheBoy** [comment]
I have a similar problem and I can't solve it in any way(((
After I press "Stop" when recording a video, it continues to be recorded for a while, and then this error appears:

ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[gdigrab @ 000001d69278ef80] Capturing whole desktop as 174x172x32 at (574,133)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1615487481.342944, bitrate: 28743 kb/s
    Stream #0:0: Video: bmp, bgra, 174x172, 28743 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, dshow, from 'audio=virtual-audio-capturer':
  Duration: N/A, start: 717528.201000, bitrate: 1536 kb/s
    Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[gdigrab @ 000001d69278ef80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 000001d6933ad3c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 000001d6933ad3c0] profile High 4:4:4 Predictive, level 1.2, 4:4:4, 8-bit
[libx264 @ 000001d6933ad3c0] 64 - core 161 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=2 lookahead_threads=2 sliced_threads=1 slices=2 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
[dshow @ 000001d6927eb700] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Finishing stream 0:1 without any data written to it.
Output #0, mp4, to 'C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv444p(progressive), 174x172, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac
frame=    1 fps=0.1 q=0.0 Lsize=      20kB time=00:00:00.00 bitrate=2517661.5kbits/s speed=7.01e-06x    
video:19kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 4.085890%
[libx264 @ 000001d6933ad3c0] frame I:1     Avg QP: 0.00  size: 19137
[libx264 @ 000001d6933ad3c0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 000001d6933ad3c0] coded y,u,v intra: 100.0% 98.6% 98.3%
[libx264 @ 000001d6933ad3c0] i16 v,h,dc,p: 37% 61%  2%  0%
[libx264 @ 000001d6933ad3c0] kb/s:4592.88
[aac @ 000001d692829680] Qavg: nan
Received stop event after 931 passes
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:00:00.03, start: 0.000000, bitrate: 4813 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 174x172, 4717 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Codec AVOption b (set bitrate (in bits/s)) specified for output file #0 (C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Output C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.

![Video 22 12, 11 03 2021](https://user-images.githubusercontent.com/75387140/110841420-e7d3ac80-82b6-11eb-818b-fcc03a1aa394.png)
![Video 22 12, 11 03 2021](https://user-images.githubusercontent.com/75387140/110841474-f7eb8c00-82b6-11eb-9a0d-52033ec0f957.png)

And in the folder for the video, a video appears, but its duration is 00:00:00
What should I do?

**Comment by weberankit** [comment]
hey everyone those who are facing issues related to ffmpeg just follow this video your problem will be solved (worked for me)
https://www.youtube.com/watch?v=BcaYRb7TElo

**Comment by grindmasterbear** [comment]
https://vb-audio.com/Cable/
install this
