### ISSUE TITLE
Installing ShareX using Run as administrator sets the screenshot folder as the Administered user

### ISSUE THREAD

**Issue by Mystiflow** [ShareX/ShareX#2766]
Using version 11.9.1 from source https://getsharex.com/ on Windows 10 64 Bit.

Let's say I have two users; 'admin' and 'mystiflow'. 
'mystiflow' is a Standard user account and 'admin' is; well, an, Admin account. 

I wasn't able to install the software from my Standard user account due to a permission error. So as a workaround; using the content menu for the download exe; I selected 'Run as an Administrator' and entered my password for 'admin' to authorise using UAC.

After installing, the software is using the Screenshots folder for the admin user and I am unable to open the folder or view any of them from my mystiflow user.

**Comment by NovusTheory** [comment]
Is this like supposed to be bug? Because that's intended behavior from Windows.

You'll have to set the owner of the folder to your standard user now

**Comment by Mystiflow** [comment]
I see now after fiddling about in the settings that the owner can be changed.

Is it not best behaviour to set the owner from the installing user regardless if an Admin or not?

**Comment by NovusTheory** [comment]
It can't really do that, it depends what user the program is run under. When you run a program as Admin, it runs the program under that user
