### ISSUE TITLE
[Feature Request] Pause/Unpause Screen Recording (Single Output File)

### ISSUE THREAD

**Issue by YipYipX4** [ShareX/ShareX#2767]
When I start screen recording, buttons appear below the capture area to Stop or Abort the screen recording.  Pressing Stop will end the recording and save the file.  It would be great to also have a "Pause" button that suspends the recording and switches to an "Unpause" button which would resume the recording to the _same_ output file.

One reason for this feature is to pause recording while waiting for a progress bar (or other long-running operation) to complete.

Workaround 1: Stop recording and then start a new recording and later stitch the videos together with a video editing tool.  A hotkey can be set to start recording with the previous capture region.
Workaround 2: Keep recording and later edit out the undesired section with a video editing tool.

Having this feature would be more convenient than either of the above workarounds.

Thank you for considering this request.

**Comment by NovusTheory** [comment]
I recommend reading #205

**Comment by YipYipX4** [comment]
Ok, thanks.
