### ISSUE TITLE
i compile the share x get error like this

### ISSUE THREAD

**Issue by Edison6351** [ShareX/ShareX#2769]
hi gus,
       i'm using vs 2017 community complie this solution get error like this:
      
![wx20170915-174731](https://user-images.githubusercontent.com/8285762/30477016-69b3995a-9a3e-11e7-9246-b28bd2115376.png)

      
      need help please

**Comment by campbeb** [comment]
Can you please paste a text version so I can translate the messages?

**Comment by Edison6351** [comment]
ok, i compile agian and the error like this:
![image](https://user-images.githubusercontent.com/8285762/30527204-d3467df8-9c58-11e7-9151-3e0ce810ab08.png)

 command “cd \\Mac\Home\Desktop\项目\github\ShareX\ShareX.UploadersLib\APIKeys\if not exist APIKeysLocal.cs (    type nul > APIKeysLocal.cs)”已退出，代码为 1。 | ShareX.UploadersLib |   |   |  

APIKeysLocal.cs not in local:

![image](https://user-images.githubusercontent.com/8285762/30527219-ff98ac32-9c58-11e7-9171-2db2cc26e1ea.png)

thanks for help

**Comment by Edison6351** [comment]
as plus i used a macbook pro parallels Desktop for dev, is't becase of this?

**Comment by campbeb** [comment]
Yes, it may be because you are on a Mac. Both of those lines are trying to run Windows command prompt statements.

The first creates that file if it doesn't exist.
The second creates a hash for a release build.

You can do the first one manually and then remove both of those lines from the project file.

**Comment by NovusTheory** [comment]
Good luck getting ShareX to run on Mac, it depends too much on Windows to run properly

**Comment by Edison6351** [comment]
yes,i got a pc and complie it passed thanks @campbeb
