### ISSUE TITLE
StackStorage support

### ISSUE THREAD

**Issue by melerpe** [ShareX/ShareX#2770]
Hi,
In the netherlands stackip gives you a free cloud space of 1tb.
It has webdav, maybe make a webdav uploader?

https://[NameHere].stackstorage.com/remote.php/webdav/

Will send name in private if you request

-Melerpe

**Comment by Scrxtchy** [comment]
@Jaex do we have anything for webdav?

**Comment by Jaex** [comment]
OwnCloud is using webdav but not sure about differences of it from other webdav implementations.

**Comment by Xalaxis** [comment]
I get a 400 - Bad request when uploading files to Stack through the default ownCloud implementation.

**Comment by Xalaxis** [comment]
@melerpe Can you reopen this?

**Comment by Jaex** [comment]
Can't you use custom uploader for webdav? Like this: https://github.com/ShareX/ShareX/issues/2299#issuecomment-441398676
