### ISSUE TITLE
Mention supported OSs

### ISSUE THREAD

**Issue by daylightbrightledlight** [ShareX/ShareX#2771]
I think the website should mention which OSs the software will support (e.g. Windows 7, Windows 10).

**Comment by vatterspun** [comment]
#2610

**Comment by daylightbrightledlight** [comment]
@vatterspun I see. Do you think it would be nice to show OS requirements (e.g. Windows 7 or later)? I think it would make it easier for users to find this information if it was available somewhere on the [main website](https://getsharex.com/).
