### ISSUE TITLE
FFmpeg options described in the wiki?

### ISSUE THREAD

**Issue by Huygenz** [ShareX/ShareX#2772]
Where is this? I can't find it anywhere.
https://github.com/ShareX/ShareX/wiki/FFmpeg-options

**Comment by Jaex** [comment]
If you mean options window:

![](https://jaex.getsharex.com/2017/09/ShareX_ScxCpixmtD.png)

**Comment by Huygenz** [comment]
No, I mean the options described in the link I provided.

**Comment by Jaex** [comment]
Devices come with install button there, container format automatically selects depending on video type.

**Comment by Huygenz** [comment]
Alright, thanks. Fixed my problem. :)
