### ISSUE TITLE
Add a "Restart" Option in the "Gif" and "Screen Recording" capture mode menu.

### ISSUE THREAD

**Issue by probiner** [ShareX/ShareX#2773]
I use both those modes a lot and sometimes I need to restart the recording several time.

At the moment this means to search for the recording mode in ShareX menu again, and to redrawn the capture region.

To speed "takes" up I would suggest an option along "Stop" and "Abort" called "Restart", which basically allows you to stay in the same recording mode, same capture region and try again.

Thank you!

**Comment by Jaex** [comment]
You can make last region hotkey like this:

![](https://jaex.getsharex.com/2017/09/ShareX_kBuJ3cuJCr.png)

**Comment by probiner** [comment]
Hi Jaex. Thank you for the input, this can sort it out.
I would still thing it would be deserving of being a button, the same way the Abort action is a button and a shortcut.
Cheers

**Comment by Stamimail** [comment]
+1
When your moves in the recording are not good, you want simply to click a "Restart" button to Restart the recording.
In case the user Aborted, he looks for another thing - a way to use the last region for the current recording.

**Comment by Stamimail** [comment]
???

**Comment by gmkado** [comment]
I agree this would be useful
