### ISSUE TITLE
Import Tool For New PC Migration

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#2775]
Can a tool be created that preserves all my settings, folders and files, in such a way that allows me to seamlessly migrate all to a new PC?

If one already exists could you please give a detailed explanation on how to perform this?

**Comment by Jaex** [comment]
You mean this?

![](https://jaex.getsharex.com/2017/09/ShareX_6FkFAoiL2m.png)

**Comment by MrCD1968** [comment]
Why yes. Sorry for the trouble. I don't see as well as I used to :-)


  ----- Original Message -----
