### ISSUE TITLE
为什么捕捉矩形区域的情况下最下面有一块不在可选范围内？

### ISSUE THREAD

**Issue by seeeeeena** [ShareX/ShareX#2777]
![2017-09-18_21-15-40](https://user-images.githubusercontent.com/24690075/30543785-e78a8b52-9cb6-11e7-9fe5-2f38326fc696.png)

**Comment by campbeb** [comment]
Do you always have that problem in Chrome?
Do you have that problem if you run Chrome in Incognito mode?

**Comment by seeeeeena** [comment]
This problem in anywhere.
It does not matter with Chrome.
My screenshot with Chrome background simply because here the contrast is high.

**Comment by Jaex** [comment]
#1338
