### ISSUE TITLE
Feature request: Option to show mouse / keyboard actions during video capture.

### ISSUE THREAD

**Issue by corylulu** [ShareX/ShareX#2779]
There are some instances where in their screen capture, people will want to show: left/right-clicking, scrolling, typing, holding modifier keys, etc. 

I'm thinking an option to show a small, transparent box in the corner of the capture with text showing the current keyboard/mouse actions (stacking) or an icon representation in the same fashion. 

Think this would be super useful for "how to" situations.

**Comment by NovusTheory** [comment]
Falls in line with #1040

**Comment by corylulu** [comment]
@Jaex You could just create a click-through, always-on-top, transparent window to render the text rather than trying to add it via ffmpeg.
