### ISSUE TITLE
SFTP not support public/private key pair

### ISSUE THREAD

**Issue by tldzyx** [ShareX/ShareX#2780]
![image](https://user-images.githubusercontent.com/5987706/30620831-4cccd42e-9dda-11e7-8dc2-e7f61811a29a.png)

so, which key should I use ? I try to use Putty Private Key, it's not work, too.

![image](https://user-images.githubusercontent.com/5987706/30620969-1b88e442-9ddb-11e7-876d-843578962aa5.png)

**Comment by sylveon** [comment]
You need to export the private key in PuTTYgen to the OpenSSH format. Then use the resulting file in ShareX

**Comment by AlbinoGeek** [comment]
Can confirm, works only with OpenSSH v2 format -- no other format works.
