### ISSUE TITLE
Error uploading to GE.TT

### ISSUE THREAD

**Issue by apometron** [ShareX/ShareX#2781]
I tried upload to GE.TT and I could not.

![screeny 2017 09 20 00 15 06](https://user-images.githubusercontent.com/4054252/30665823-bbb05368-9e28-11e7-8ac6-457d7b2e3d22.png)

Above the capture I did with Screeny software.

Thanks ! =)

**Comment by Jaex** [comment]
Login request gives `The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.` error and I'm not sure why.
