### ISSUE TITLE
Bug: cmd line "autoclose": ShareX does not end process if task not completed

### ISSUE THREAD

**Issue by muffmolch** [ShareX/ShareX#2782]
I want to make a screenhot with sharex triggered by a button click inside a c# application.

Therefore I run Start ShareX via command line:

    Clipboard.Clear();

    var pi = new ProcessStartInfo();
    pi.FileName  = ShareXPatcher.ShareXBinary;
    pi.Arguments = "-m -s -autoclose -nohotkeys -RectangleRegion";

    var p = Process.Start(pi);
    p.WaitForExit();

    if(Clipboard.ContainsImage()) {
    ...
    }
     
Problem is: If the user cancels the operation (by pressing ESC) shareX never exit!

Is there another way to trigger a screenshot snapshot from anaother c# application?

**Comment by argothiel** [comment]
The issue still occurs. Please, reopen.
