### ISSUE TITLE
The lower side does not become a capture screen when trying to capture

### ISSUE THREAD

**Issue by OnePeNNy114** [ShareX/ShareX#2784]
When I press Ctrl+PrintScreen, I enter the capture screen but the bottom side is not adapted.
I took a movie so please watch it.
https://www.youtube.com/watch?v=LzKXVYCrgyM
There are other problems but if you try to capture the main monitor it will do exactly but if you try to capture the sub monitor it will behave strangely.
I tried changing the version but it still occurred.
Is this a bug?
I am sorry that my English is so bad.

**Comment by Jaex** [comment]
#1338
