### ISSUE TITLE
Google Chrome extension icon greyed out

### ISSUE THREAD

**Issue by mythofechelon** [ShareX/ShareX#2787]
On two different PCs (but the same Google Chrome account / profile), I have done the following:
1. Opened ShareX.
2. Selected "Application settings..."
3. Selected "Integration".
4. Selected "Enable Chrome extension support".
5. Selected "Install ShareX Chrome extension".
6. Installed the ShareX's Google Chrome extension from https://chrome.google.com/webstore/detail/sharex/nlkoigbdolhchiicbonbihbphgamnaoc.
7. Found that ShareX's Google Chrome extension icon is simply greyed out.
8. Verified that ShareX's Google Chrome extension is enabled.

No one else seems to have had this problem. 

Have I done something wrong?

**Comment by Jaex** [comment]
ShareX don't have any function for that button but Chrome still adds it for all extensions. You can drag chrome toolbar to hide those icons:

![](https://jaex.getsharex.com/2017/09/LNb3k4glpw.png)
