### ISSUE TITLE
F12 doesn't work with hotkeys. 

### ISSUE THREAD

**Issue by SC2Mitch** [ShareX/ShareX#2788]
I seen in the ShareX discord that the F12 hotkey doesn't work, after checking it out it's constantly in red, unable to enable it. 
![image](https://user-images.githubusercontent.com/29955942/30758225-61aa60b4-9fc9-11e7-9b2b-6bc9c2314f31.png)

**Comment by Jaex** [comment]
https://stackoverflow.com/q/27953175/264877
