### ISSUE TITLE
FFMpeg randomly starts to error

### ISSUE THREAD

**Issue by Khodyn** [ShareX/ShareX#2789]
Sometimes ShareX'll work, but then the next captures will always end up like this:

https://i.imgur.com/p2QX50F.png

(GitHub was erroring when uploading the screenshot)

**Comment by Klocko** [comment]
Update.

I re-plugged my wireless headset's USB dongle and it's suddenly started to work again. Weird.

**Comment by mythofechelon** [comment]
I'm having the same problem - screen recording takes a few second to start then after ~4.5 seconds I get the same error as you.

I've tried updating FFmpeg and reinstalling the recording devices but that hasn't resolved the problem.
