### ISSUE TITLE
How to get image previews?

### ISSUE THREAD

**Issue by HamJabroni** [ShareX/ShareX#2792]
When I reinstalled, previews now look like this

https://i.imgur.com/YE1vkYx.png

Would much rather have an actual image.

**Comment by campbeb** [comment]
In Task Settings, verify this option is set:
![sharex_2017-09-24_14-23-04](https://user-images.githubusercontent.com/1089399/30785366-fb3fabf6-a133-11e7-8f2a-610553dc4dd7.png)

**Comment by HamJabroni** [comment]
It is.

**Comment by Jaex** [comment]
Image must be saved to file for preview to show it.
