### ISSUE TITLE
ShareX copies to clipboard but has issues with XMIND

### ISSUE THREAD

**Issue by mfaisalk1** [ShareX/ShareX#2793]
My workflow is annotate and copy to clipboard. I can do so from sharex to microsoft applications. However I am not able to do it to my mindmap application xmind. What could be the reason ? I know that the screenshot is copied but it does not bring it in xmind. Note, it was working fine with windows 7 and xmind ( version 7), only when i upgraded to windows 10 and latest vesion of xmind (version 8) that this issue starting happening. Please suggest a workaround.

**Comment by campbeb** [comment]
ShareX has several clipboard settings. Can you see if adjusting them has any impact?
![clipboard](https://user-images.githubusercontent.com/1089399/30835905-f6d1d404-a228-11e7-9478-ef1f98f4347c.png)

**Comment by mfaisalk1** [comment]
Thanks, i tried to play with these settings, but it did not help

**Comment by mfaisalk1** [comment]
Thanks!

Interesting, now it is working.  Please see the settings which I changed.

![image](https://user-images.githubusercontent.com/32096388/30842482-395a96c8-a28b-11e7-8c41-434192267c12.png)
