### ISSUE TITLE
Cannot stop recording when audio source is removed

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ShareX/ShareX#2797]
If you have an audio source for one sessions, then you remove the audio source and start recording again, the recording will not stop. You have to close ShareX completely and restart, then go to Task Settings > Capture > Screen Recorder > Screen Recording Options > Audio Source and set this to None (it should be blank before this).

**Comment by stuntguy3000** [comment]
Is this issue still valid, there have been recentish updates to audio drivers.

**Comment by Anti-Distinctlyminty** [comment]
Just tested. Appears to be fixed. Thanks.
