### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by stdedos** [ShareX/ShareX#2798]
I was prompted with a bug. I pressed bug report - however, it seem to do something that I couldn't see, because the whole screen was covered with ShareX.

I pressed `Esc` to remove the screen and see what happened, without having the chance to save anything. I didn't think to copy-paste the info window.

Neither do I "understood" what did I do to create the issue, as it had something to do with mouse input. I got a new mouse that, instead of having the accurancy button on the middle-click, is somewhere different. Hence, I was pressing it and a combination of the main buttons + wheel that created the issue.

Attached maybe some useful files?

**Comment by Jaex** [comment]
Where that debug.log file come from?

**Comment by stdedos** [comment]
I assume from the same origin. I searched for text files related to ShareX.

**Comment by Jaex** [comment]
Are you enabled custom info text for region capture to show color? For some reason it used coordinates outside of screen or something. Not sure how that possible.

**Comment by stdedos** [comment]
I ... am not sure I understand the meaning of the sentence.
> Are you enabled custom info text for region capture to show color?


I recently moved to Windows 10 and setup my dual screen configuration.
It could be that the right screen has the (0,0) coordinates - hence left screen appears "outside of screen"

**Comment by Jaex** [comment]
Was it happened in screen color picker?

**Comment by stdedos** [comment]
I have no idea _how_ it happened, as I mentioned above.

I was doing my normal routine (i.e. Square-Region-Capture). I used to have `Accurancy` in the middle click, and a much "harder" wheel, so usually I pressed-and-held middle-click for accurancy in the capture. No scrolling involved.

However, I assume that press-and-hold middle-click allows to swap between the tools. Wheel was "uncontrollable" (since I am used to _quantized_ scroll instead of free-scroll), so I assume I rolled back-and-forth between tools. I might have held down left-click. I possibly moved the pointer outside of screen bounds - definitely not outside of viewport area though.

**Comment by Jaex** [comment]
How you can move pointer outside of screen when it is fullscreen window?

**Comment by stdedos** [comment]
> I recently moved to Windows 10 and setup my dual screen configuration.
It could be that the right screen has the (0,0) coordinates - hence left screen appears "outside of screen"

**Comment by Jaex** [comment]
Well I have no clue how that cursor coordinate can be outside screen and I don't have multi monitor. But I added code to limit it inside screen so error won't happen again.
