### ISSUE TITLE
suggestion: set 'UseShareXForAnnotation' disabled by default, and organize the settings

### ISSUE THREAD

**Issue by getreadyforme** [ShareX/ShareX#2801]
Thank you for this useful program!  

The biggest issue I had with this is that the default Annotate window takes over the screen!  It is always fullscreen (with an ugly grey background) and stays on top of all other windows.  This doesn't allow taking multiple screenshots, or Alt-tabbing to other programs.  This is really bad.  Basically once I enter the annotate screen, no other actions are available to me on the computer, unless I exit or save the current image.  

This is very restrictive, since I'm used to programs like FS Capture, where I can take multiple screenshots, combine them if needed, and save them later.  I was ready to give up on ShareX, when I accidentally found the UseShareXForAnnotation setting, which removes the restriction.  I think that should be disabled by default, or at least it should be made more obvious.  Currently it is buried under Task settings >> Advanced >> General, in an ocean of other settings that are difficult to understand.   

In fact the entire settings menu should be organized better.  The Task settings and Application settings should be combined and streamlined, and the Advanced screens should be made easier to understand - the single-word names in the advanced tab are very tedious to read and understand.  Most of the True/False options should be changed to check boxes. 

Also, there shouldn't be  multiple settings screens with the same name -  e.g. "Task settings >> General", and "Task settings >> Advanced >> General".  Same with 'Upload' settings.  This is just too scattered and confusing.

**Comment by Jaex** [comment]
Reason why it is enabled by default because that editor is deprecated and gonna be removed in future.

Reason why application settings and task settings is separate and can't be combined is, task settings is specific per hotkey but application settings not. So you can edit each hotkey to have different task settings etc.
