### ISSUE TITLE
Enable Esc key to work as 'Exit' in Quick Tasks Menu?

### ISSUE THREAD

**Issue by Vismund-Cygnus** [ShareX/ShareX#2802]
I have my normal PstSc button mapped to a ShareX task. The only issue is that I'm on a laptop and I often hit the PrtSc button by mistake, which takes a screenshot and sends me to the Quick Tasks Menu so I can decide what to do with the screenshot. 90% of the time I just want to hit 'Exit' since it was a mistake, and it gets annoying having to switch from the keyboard to mouse just to go press the 'Exit' option on the menu before I can do anything else.

So I was wondering if you guys could enable a setting so when you press the Esc button while the QTM is open, it Exits the menu without continuing.

**Comment by ViRGiL175** [comment]
Highest priority for this! The same problem.
