### ISSUE TITLE
Digital Ocean Spaces Signature Mismatch

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#2803]
Digital Ocean has it's S3 Compatible API. However I am getting Signature mismatch (403 Forbidden)
```
Message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://tenryuu.nyc3.digitaloceanspaces.com/astrid/2017-09/629dcba19e8135e8c23671254adea894414ca4be1c9a71a913dbbe1c8575aa28.png

Response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx000000000000001b7638c-0059cdfbfa-24e9b-nyc3a</RequestId><HostId>24e9b-nyc3a-nyc</HostId></Error>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

Upload to Amazon S3 failed. Check your access credentials.
```

Access key and Secret Key should be correct, I have double checked them from The API and Applications page on Digital Ocean. Using keys specific for the storage service.

![image](https://user-images.githubusercontent.com/12771982/31006510-41ae9e66-a540-11e7-981e-0a978f30851e.png)

**Comment by Jaex** [comment]
https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/31523221-spaces-api-support-presigned-upload-urls-like-tho

**Comment by Scrxtchy** [comment]
Now We Wait

**Comment by Jaex** [comment]
Now you vote

**Comment by Jaex** [comment]
Implemented authorization header authentication method now which is supported by DigitalOcean Spaces and it works now. Also added Spaces endpoints to list.

**Comment by fonderco** [comment]
@Jaex - can you post any of your code that worked?
