### ISSUE TITLE
Dropbox 409 Conflict When Uploading Same File

### ISSUE THREAD

**Issue by Jonatino** [ShareX/ShareX#2805]
This started happening recently (6 months or so) when I upload a file twice the second time it says.

https://dl.dropboxusercontent.com/s/dypbuisggz8laei/idea64_2017-09-30_16-34-09.png

I remember before Sharex would upload the same file and replace the one that's on the server.

**Comment by Jaex** [comment]
Actually it uploads and overwrites but while creating shareable link this happens. And because I don't want to check is shareable link already created each upload which would make it 3 different requests. This happens. Old API probably didn't have this problem therefore it was not happening before.

**Comment by Jonatino** [comment]
@Jaex ah that makes sense.

Saw a post on Dropbox which says you could get back the shared url.

https://www.dropboxforum.com/t5/API-support/shared-link-already-exists/td-p/190946

Greg K.  Dropboxer
‎10-17-2016 11:35 AM  
When calling /2/sharing/create_shared_link_with_settings a shared_link_already_exists error is expected if a shared link already exists for that path.
 
This can occur, for example, if your app already made that API call for that path. Is it possible your app ran that code more than once for a particular path?
 
If can also occur if the user elsewhere made a link for that file or folder though, even outside of your app, e.g., via the Dropbox web site.
 
That being the case, you should make sure your app is ready to handle that error. You can use /2/sharing/list_shared_links with direct=true to get the existing link.

**Comment by jorjic** [comment]
I ran into this problem, and fixed it by verifying the email on my Dropbox account.
