### ISSUE TITLE
Feature Request: Modify Screen Before Recording GIF 

### ISSUE THREAD

**Issue by sr10952** [ShareX/ShareX#2815]
Hi,
Using ShareX for a while, and the GIF recording almost daily, I would love to be able to edit the GIF's, but I know and I understand it's not going to happen so quickly. :( 
My suggestion is not so complicated to invent, so let's put it down.

When capturing an image of a region, some annotations pops up, like this; https://transfer.sh/tlQLY/dllhost_2017-10-03_15-01-04.png this annotiations are excelent for lots of things.  Though not all the annotations are good for GIF captures, some of them are very useful, for instance, adding a watermark on the entire GIF or blurring a spot on the screen. In other words, these editing tools to annotate the screen before doing the final capture of an image, should be available before capturing a GIF and should remain like it throughout the GIF recording.

**Comment by vatterspun** [comment]
> should be available before capturing a GIF and should remain like it throughout the GIF recording

Jaex might want to hand this request off to a proper GIF editor like ScreenToGif, PhotoScape, or RealWorld Paint.  Still, the graphics editor keeps getting better and better, so maybe that's worth digging into.
