### ISSUE TITLE
Prevent new instance after completion of silent installation

### ISSUE THREAD

**Issue by CatPurrfect** [ShareX/ShareX#2823]
A silent installation using the `/silent` or `/verysilent` parameter works, however after completion of a silent installation the program automatically starts up. I believe you're missing the `skipifsilent` flag in the `[RUN]` section of the `install_script.iss`.

**Comment by CatPurrfect** [comment]
I’m confused why it must run automatically after install? What does it have to do with updates?

**Comment by Scrxtchy** [comment]
Updating ShareX is just running an installation for the new version

**Comment by CatPurrfect** [comment]
Okay, so it updates by using the installation silently. However, I’m still confused why it must run after updating? Can’t you just run it when you want afterwards?

**Comment by marionus** [comment]
I'm also looking for a way to keep ShareX installer from running the app at the end of a silent install. So far, my best solution is to kill the sharex process after install.

**Comment by Jaex** [comment]
As a solution I'm planning to disable auto running by default but instead having support for `/AUTORUN` parameter that way ShareX can add this parameter when running setup for updating.

**Comment by Jaex** [comment]
I can't decide what to name parameter:
`/NORUN`
`/NOAUTORUN`
`/NOSTART`
`/NOAUTOSTART`

Also when that parameter is used and there is no `\SILENT` used then last page of setup not gonna show check box to run ShareX.
