### ISSUE TITLE
Feature Request: Add "Send Anywhere" as file uploader

### ISSUE THREAD

**Issue by bijitplus** [ShareX/ShareX#2826]
Hello,
First of all, thank you very much for this awesome app. I'd like to request a feature to upload files on https://send-anywhere.com/

It is a very very popular and useful website for uploading/sharing files. 

Thanks

**Comment by JakeMakesStuff** [comment]
I will look into it. I am not affiliated with ShareX but I might be able to make a pull request for their uploader if it is supported.
