### ISSUE TITLE
With & Height args are empty

### ISSUE THREAD

**Issue by DracoZ12** [ShareX/ShareX#2830]
I tried to make a script giving back the image width and height, but the %width and %height arguments always return nothing, am i doing something wrong?

**Comment by campbeb** [comment]
Can you elaborate more on exactly what you are setting up and where in the program?

**Comment by DracoZ12** [comment]
i am using this 
![image](https://user-images.githubusercontent.com/25370216/33804463-d9fd3e50-dda5-11e7-9c51-519c0ee64cae.png) but it always returns void

**Comment by Jaex** [comment]
Uploader don't knows is it image or not. It just receives bytes to transfer therefore it is not possible to use width there.
