### ISSUE TITLE
How to shorten the dropbox link

### ISSUE THREAD

**Issue by rdbox** [ShareX/ShareX#2831]
Hi, I know that the dropbox itself can shorten the links in the config file there is a parameter `"DropboxURLType": "Default",`
How it needs to be changed so that links would be short of this kind https://db.tt

**Comment by Jaex** [comment]
They removed shortened URL type from their latest API. I sent them email asked about it before:

![](https://jaex.getsharex.com/2017/10/chrome_w7teniCJxP.png)

**Comment by rdbox** [comment]
I have a telegram bot and it can automatically check for the presence of files in the dropbox so here it sends me and a short link to the dropbox
How can this be?
If developers dropbox closed in their API?


![image](https://user-images.githubusercontent.com/18515862/31312067-ee5bd7fe-abc2-11e7-91ed-594e25fc1ad1.png)
