### ISSUE TITLE
Combined image has wrong thumbnail

### ISSUE THREAD

**Issue by user6323** [ShareX/ShareX#2839]
https://dl.dropboxusercontent.com/s/r47kiejsx86rweg/1507744190.mp4
How to reproduce:
1. Combine 2 image
2. Click on resulting combined image
Thumbnail of the resulting image is a thumbnail of the second image.

**Comment by campbeb** [comment]
A simpler way to reproduce this:
1. Have 3 items in the list
2. Select the first 2 items
3. Then select the 3rd item. The preview window will not show the 3rd item, but one of the first 2.

Problem traces back to `if (!isImageLoading)` in `MyPictureBox::LoadImageAsync`. It is trying to avoid excessive image loads, but ends up not loading the last selected image.
