### ISSUE TITLE
Try to launch ShareX, only works after installation, after computer restart, Share won't restart

### ISSUE THREAD

**Issue by Kileahh** [ShareX/ShareX#2842]
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
   à ShareX.TaskSettingsTools..ctor()
   à ShareX.TaskSettings..ctor()
   à ShareX.ApplicationConfig..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance[T]()
   à ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   à ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   à ShareX.SettingManager.LoadApplicationConfig()
   à ShareX.SettingManager.LoadInitialSettings()
   à ShareX.Program.Run()
   à ShareX.Program.Main(String[] args)

ShareX 11.9.1 (Release)

**Comment by NovusTheory** [comment]
Reinstall ShareX (also is this duplicate?)

**Comment by Kileahh** [comment]
I reinstall it, It didn’t ask to specify folder and options (create shortcut, button on explorer…) was like I ask the first time. It didn’t duplicate, it just replace/put good files.

And it works with my history of screenshots
