### ISSUE TITLE
Persistent gif recording issues. 

### ISSUE THREAD

**Issue by SC2Mitch** [ShareX/ShareX#2844]
Morning, I'm having some issues with gif recording and the uploading, the uploading process slows to a crawl at 99% then it just stops and reuploads again then repeats the same persistent issue thus rendering it unable to upload to Gyfcat which is bothersome. Running on the latest stable version. If you need more info @ Mitch on discord.

**Comment by Scrxtchy** [comment]
Does the upload return an error message?

**Comment by SC2Mitch** [comment]
No, just goes to 99.9% then restarts the upload process.

**Comment by SC2Mitch** [comment]
This can be closed; fairly sure it was a gfycat issue.
