### ISSUE TITLE
Azure Virtual Folders

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#2845]
Really easy issue,
Azure blob storage allows storing within a virtual folder, and can be seen from the Portal within folders, as well as it's used within the blob url.

This can easily be added by adding the path to use to the url and canonicalizedResource variables

`string url = $"https://{AzureStorageAccountName}.{AzureStorageEnvironment}/{AzureStorageContainer}/{virtualFolder}/{fileName}";` as an example

No extra code is necessary for the uploader. This will just change the HTTP request for azure to add the path.

Ideally, this would be using a similar system to the Upload Path from AmazonS3

**Comment by Scrxtchy** [comment]
🤖🔫👀

**Comment by Lego6245** [comment]
In theory this is achievable by just adding additional stuff to the end of your container (it's not that smart). So if you wanted a virtual directory `bar` in container `foo`, you could set your container to `foo/bar`. However, explicitly allowing you to do custom directories like the upload path in S3 is a good enhancement.

**Comment by Jaex** [comment]
Fixed by #3436
