### ISSUE TITLE
Suggested feature: Copy the OCR output (text) to clipboard automatically and close window

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#2848]
Currently, Sharex can OCR the snapshot. 
The OCR window stays open and shows the OCR'd text.
The next steps are manual:
- The user has to highlight the text and press CTRL+C.
- He has to close the window by pressing the X button at top-right corner.

This multi-step process can be shortened to increase productivity: Provide a **turbo** mode, in which the OCR'd text gets copied to clipboard automatically, and the OCR window is closed.

The settings remain same as the non-turbo mode. (e.g. if the user has selected "Spanish" as OCR language, it remains unchanged in turbo mode.)

**Comment by vatterspun** [comment]
I think the main window showing up is intended as a way to allow review the analysis so you can see if the OCR conversion was accurate.  That said, there's been a program called Capture2Text that has the functionality you describe.  I don't know how it compares to ShareX overall or in terms of the OCR processing.

**Comment by stuntguy3000** [comment]
Perhaps the OCR window can be not brought up at all?

Similar to the way GIF/Video processing works, use the use of notifications and tray icons to process the action.

**Comment by Detys** [comment]
You need the OCR window for language selection, although an option to set the default OCR language could be set.

**Comment by Duos-Apros** [comment]
I have used Capture2Text  and found the OCR process much slower than ShareX.

I have used ShareX for some time now and strongly support this suggestion; it will improve productivity.

**Comment by jayryemure** [comment]
The ShareX region selection box is much easier to use over Capture2Text as well I find, in addition to being consistent with all the other capture tasks we use ShareX for.

We can always have separate tasks configured for opening the OCR window (default) vs. copying the text directly to the clipboard.

I heartily support this enhancement!

**Comment by stuntguy3000** [comment]
Working on this.
