### ISSUE TITLE
Feature suggestion: Please add a tool to resize image

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#2849]
Often websites have file-size limitation for uploaded images. (e.g. KYC document uploaded to Amazon).
We have to reduce the file size of the image, before uploading it to the website. 

There are apps like IrfanView that can reduce the resolution of an image to a preset value (FHD, HD, QHD etc), or reduce it by a given percentage (it has some fixed popular ratios, and also allows a user-defined % value).

But it would be good to have this tool integrated in Sharex itself.

**Comment by Jaex** [comment]
Image effects tool can resize by size or percentage.

**Comment by raindropsfromsky** [comment]
I tried all controls, but did not find the controls to resize the image.
Could you please point out how to do this?

Thanks in advance!

Regards
Narayan

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/10/ShareX_HLZbnZWEuH.png)
![](https://jaex.getsharex.com/2017/10/ShareX_BCxJurU1sB.png)

**Comment by raindropsfromsky** [comment]
Wow! The GUI is deceptively simple, but it hides a lot of functions!
Thanks for the tip!

**Comment by Jaex** [comment]
Image editor also can resize image now.
