### ISSUE TITLE
Suggested feature: Add a quick search field to locate the command

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#2850]
Sharex has long list of settings at two places:
1. Task settings > Advanced
2. Application settings > Advanced

The user has to go through all options carefully to tweak the settings.

It would be far easier if he can enter his desired effect in a **Quick search** field.
As he types the words, Sharex should search for that string in the main command and help text.
It should shortlist the matching commands.

**Comment by stuntguy3000** [comment]
@Jaex Mark as enhancement?

**Comment by Korb** [comment]
Perhaps developers don't use apps with the proposed feature, or they think it's so rare that it will scare off new users. Let me spark your imagination with some references of this feature in famous apps:

**Mozilla Firefox**
![Image](https://github.com/user-attachments/assets/60273ee4-42b6-456e-aabb-a37afad4d6ff)

**Google Chrome**
![Image](https://github.com/user-attachments/assets/bdeb596b-134f-4ba9-b878-9ac3d747b301)

**PDF-XChange Editor**
![Image](https://github.com/user-attachments/assets/deb7f0f5-cd25-4ef0-b23e-985ec393cfc7)
![Image](https://github.com/user-attachments/assets/1ed8e33c-c007-41be-a70d-be5df9b3270e)

**PDF-Tools**
![Image](https://github.com/user-attachments/assets/b2f900ab-2aa9-4b72-84bc-e38cacffaeb9)

**Microsoft Word**
![Image](https://github.com/user-attachments/assets/45fb2964-6388-4af1-9cc9-03e98e560eb2)

**Kdenlive**
![Image](https://github.com/user-attachments/assets/ab236992-96ad-41d4-8b8a-a1fc468e42e8)

**Double Commander**
![Image](https://github.com/user-attachments/assets/7ff433b5-5f40-43dd-b721-34bf383038b5)

**VLC**
![Image](https://github.com/user-attachments/assets/554e4f3b-cd4d-4db1-8c9a-af77aa687fb1)

**foobar2000**
![Image](https://github.com/user-attachments/assets/1a08191e-7051-4d83-8b64-ee692c2b255b)

So, I am sure that new users will not be scared away from this wonderful application by yet another feature, and old ShareX users will be so liberal that they will be able to ignore its appearance without excessive criticism.
