### ISSUE TITLE
Desired feature: In "Destinations..." screen, provide "None" option

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#2851]
The **Application settings > Advanced** menu option has a provision to disable all uploads.
This can be simplified if the **Destinations** screen provides a "None" choice for each type of destination.

For example, the **Image Uploader** list begins with Imgur, and has other websites such as Imagestack, TinyPic, Flickr etc. Instead, let it begin with "None" option. If the user selects this option, it means the uploading is disabled. 

Likewise, the "None" option should be added to all other menus: 
- Image uploader 
- text uploader
- file uploader
- URL shortener
- URL sharing service

Thus the user has the fine-granular control over what he wants to upload.

**Comment by Jaex** [comment]
Adding this will be misleading for users. They will think selecting None in all uploaders is a proper way to disable uploads and not bother finding proper method which is disabling upload from after capture tasks.
