### ISSUE TITLE
Feature request: Please allow the change the numerical value with UpArrow and DownArrow

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#2853]
Sharex has many controls with numerical value, which needs to be adjusted.
The normal way is to enter a new value and click outside the box to see its effect.
Can we change the value by pressing **UpArrow** and **DownArrow**?
(In case the user keeps it pressed down, hold off the response still he stops for xxx miliseconds.)

**Comment by Atrolantra** [comment]
Which controls did you have in mind? Numeric ones already work for me, for example:
In _Task Settings_ > _Thumbnail_ > _Width_
I can change that value by holding arrow keys.

**Comment by raindropsfromsky** [comment]
Well, those controls already have spinner controls, so UpArrow And
DownArrows will work.

But spinner controls are not provided at many other places where we have
numerical values.
At those places, we have to click and enter a specific value, and see the
effect.
But in most places there is no theory that recommends a specific value-- It
is mostly trial and error.
*So it would be good to have a spinner control at all those places.*

For example, in *Tools > Image effects...* menu, load an image and
then use *Add>
Filters>blur*.
The amount of blur is a matter of individual choice, and we have to
increase/decrease it till we are happy.
This can best be done by rapidly using spinner controls.

Of course, we can enter some values to roughly determine the range within
which we want to adjust the final value.
At that time, we can click and enter values.

Regards
Narayan
