### ISSUE TITLE
Streamable encoding takes exactly 1 minute then returns status 2

### ISSUE THREAD

**Issue by Jaex** [ShareX/ShareX#2854]
After upload to Streamable it returns this response for exactly 1 minute:

```
{"status": 1, "files": {"mp4": {"status": 2, "width": 428, "url": "", "bitrate": 0, "duration": 0, "size": 0, "framerate": 0, "height": 428}} ...
```

And when elapsed time reach to exactly 1:00 then it returns this:

```
{"status": 2, "files": {"mp4": {"status": 2, "width": 680, "url": ""//cf-e2.streamablevideo.com/video/mp4/...
```

Because this process exactly takes 1 minute in every single try, there must be something wrong.

Also https://streamable.com/documentation lacks info about status numbers.

@lawlmart

**Comment by lawlmart** [comment]
How often are these requests being made? You may be running up against a rate limit and we're caching the result.

**Comment by Jaex** [comment]
User was reported it. I also tried once yesterday and once today and could reproduce it with single request.

**Comment by lawlmart** [comment]
I'll look into it.

**Comment by Nogarthemage** [comment]
i noticed over several days uploading normal vids ranging from 2 seconds up to 40 seconds it took 1 minute to give me the link after already having to wait for the uploading

**Comment by Jaex** [comment]
#2855
