### ISSUE TITLE
Ao terminar uma gravação da tela...

### ISSUE THREAD

**Issue by cradino** [ShareX/ShareX#2856]
The remote server returned an error: (409) Conflict.
Message:
The remote server returned an error: (409) Conflict.

Request URL:
https://content.dropboxapi.com/2/files/upload

Response:
{"error_summary": "path/insufficient_space/", "error": {".tag": "path", "reason": {".tag": "insufficient_space"}, "upload_session_id": "AAAAAAAAS1iRiGqx8nSsVQ"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

**Comment by Scrxtchy** [comment]
You have run out of storage in your dropbox allocation

**Comment by cradino** [comment]
Mas eu quero em definitivo desligar o destino dropbox das minhas capturas e videos... Como posso fazer esse desligar?

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/32390842-172a5b94-c124-11e7-8b81-7de4f860ccb2.png)

Pick One

**Comment by cradino** [comment]
Não entendi nada! Como desativo o Dropbox?
