### ISSUE TITLE
File saving suggestion

### ISSUE THREAD

**Issue by YummyOreos** [ShareX/ShareX#2857]
Hello,
I would like to suggest that when you take a screenshot (with automatic uploading), that it pops up with a message when you take the screenshot asking you if you want to save the file to a folder or not (instead of needing to Open ShareX, find the screenshot, save it etc.).

Maybe also have an option in the settings to set where all of the files you click "Yes" to saving, saves to. (Like if I have Desktop set in settings, If I click yes, it would save to desktop.)

I'd also suggest having an option to turn the save pop-up on or off, because some people might not like to use the pop-up.

Kind regards,
Connor.

**Comment by campbeb** [comment]
You should look at using the "Show quick task menu" option under "After capture tasks".

You can create entries for what you want to do and customize the list. So you could have one that just uploads, one that saves to the folder you already selected and then uploads, one that prompts you where to save it, etc.

I believe the functionality you are looking for is there already.
