### ISSUE TITLE
Imgur Uploading to folder error

### ISSUE THREAD

**Issue by Maxwelljones** [ShareX/ShareX#2860]
Every time I try to upload to a folder on Imgur, it gets this error:
https://pastebin.com/Yn68uGzZ

Changing to uploading to Imgur without choosing a folder works fine.

Let me know if you need more info.

Thanks for a great software! Amazing options =)

**Comment by Jaex** [comment]
This error not looks like to do with ShareX? `"message":"Cannot change album contents while in gallery"`
