### ISSUE TITLE
Disable upload via registry/Group Policy

### ISSUE THREAD

**Issue by mcmcghee** [ShareX/ShareX#2861]
Is there a registry key that can be set to disable uploads? 

This would be needed for deployment in certain environments to prevent accidental upload of sensitive data.

**Comment by Jaex** [comment]
Only this: ![](https://jaex.getsharex.com/2017/10/ShareX_zBlBf6B5V6.png)

**Comment by tekmaven** [comment]
Hey @Jaex is there a way to get this set without changing it in the UI?  I think the goal here for most requests around DisableUpload is that we would like to use ShareX in a corporate environment, and this seems to be a real barrier for administrators.

**Comment by Jaex** [comment]
Even if you change it outside UI still user can re enable it from settings.

**Comment by tekmaven** [comment]
I have a custom fork where I've modified the `DisableUpload` property to always `return true;`.  I think we would want the registry setting (or some other means of configuration) to never allow that boolean to be false.

**Comment by tekmaven** [comment]
@Jaex I believe ShareX could have a lot more adoption in businesses if there was a administrator-controlled way to enforce screenshots do not get uploaded anywhere.  The default behavior of public uploads with a confirmation screen on the first upload does not work in a corporate environment and probably scares away a lot of administrators.

Would you be willing to accept a PR that changes this behavior?

**Comment by Abhishek-k2020** [comment]
did we have any settings through group policy / firewall , which can enable us to restrict uploads on public code repositories

**Comment by Jaex** [comment]
This feature added in #5822, let us know if implementation fits to your needs or requires any changes before release.
