### ISSUE TITLE
Annotate Images Fullscreen Disable?

### ISSUE THREAD

**Issue by Fiala06** [ShareX/ShareX#2862]
I just wiped and reinstalled windows on my machine. Appears my old program I guess never updated and noticed the "Annotate Images" is now different. 

Is it possible to use the old one? Or disable full screen for the new annotation? I find it annoying when I need to add info to images that's on a word doc/website that I can no longer see. Thanks!

**Comment by campbeb** [comment]
See https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879
