### ISSUE TITLE
Creating a capture zone no longer instantly captures an image

### ISSUE THREAD

**Issue by Megaddd** [ShareX/ShareX#2863]
The fact that you now have to move your hands over to the enter key to capture an image tilts me to no end. This has literally more than tripled the amount of time it takes to capture a screen area, and doesn't even allow you to do it with spacebar, which instead captures all monitors regardless of current capture regions set (which has lead to me doxxing myself, thanks by the way).

This popped up overnight with no warning and it is worse than the Las Vegas shooting. Really cripples the entire functionality of the application.

Nobody asked for this: https://streamable.com/f2bsx

**Comment by Jaex** [comment]
Uncheck this or press Q:

![](https://jaex.getsharex.com/2017/10/ShareX_5jSEI31YL0.png)

It is not enabled by default.

**Comment by Megaddd** [comment]
Oh thank god

**Comment by Megaddd** [comment]
I was about to lose it
