### ISSUE TITLE
ShareX reported as adware by Malware Bytes.

### ISSUE THREAD

**Issue by arjankuijpers** [ShareX/ShareX#2864]
![image](https://user-images.githubusercontent.com/1952012/31800777-9ced1452-b543-11e7-8e3c-925ceaffc817.png)

as action the file gets deleted from disk by restart.

**Comment by sylveon** [comment]
yes, this is a false positive. someone contacted mbam about it, we'll hope it gets fixed soon

**Comment by arjankuijpers** [comment]
Good to know, that it isn't actually a virus or malware.

**Comment by Jaex** [comment]
https://forums.malwarebytes.com/topic/213041-sharex-recorder-devices-setupexe/?do=findComment&comment=1174385

**Comment by Jaex** [comment]
They didn't reply to my ticket yet but I did malwarebytes update now and it not detects ShareX as adware anymore.
