### ISSUE TITLE
Imgur authorize not working for me via google+

### ISSUE THREAD

**Issue by MaZyGer** [ShareX/ShareX#2873]
Step 1: Open authorize website:

![Step 1](https://i.imgur.com/eL2tTSw.png)

Step 2: Select google + click on allow
Step 3: Choosing my account.

Result:
![Result](https://i.imgur.com/Qy9XgAb.png)

Do I miss something here? 
ShareX version: 11.9.1

I've setup password now. If I log in via username and password the process worked. But with google+ loggin it does not work. 
But I did it once via google+ loggin. because I was already authorized ( I just made a mistake.. using mousescroll while hovering over settings. This removed the authorization for a reason.)

**Comment by Jaex** [comment]
It not looks like problem in ShareX side?

**Comment by MaZyGer** [comment]
I am not sure. Just wanted to report it. I know with twitch api you can give a callback url. So I thought its maybe same and url was wrong.
