### ISSUE TITLE
Support for Windows 10 Share

### ISSUE THREAD

**Issue by notnsane** [ShareX/ShareX#2880]
Hi Jaex it's me again with the unreasonable requests!

Fall Creators Update introduced this one:

![0hyarhb](https://user-images.githubusercontent.com/7162375/32043419-129ed9d4-ba11-11e7-9f78-552b66878cfe.png)

Which opens the updated Share menu (previously Charms or whatever)

![tv7oyos](https://user-images.githubusercontent.com/7162375/32043465-2d0540ce-ba11-11e7-8254-f4f0ab781984.png)

API stuff that I found that might or might not be related, specially since it's a centennial app and some of these docs are for Windows 8:

* https://msdn.microsoft.com/library/windows/apps/hh758314
* https://peterfoot.net/2015/08/20/add-sharing-to-your-uwp-app/
* https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-sharetarget
* https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/ShareTarget

**Comment by Jaex** [comment]
All your links look like to do with UWP stuffs.

**Comment by stuntguy3000** [comment]
ShareX isn't a UWP app. I don't think this is doable...
