### ISSUE TITLE
Record Window Alt + F4/Force Close

### ISSUE THREAD

**Issue by NovusTheory** [ShareX/ShareX#2884]
If you start a new gif/screen record capture and then Alt + F4 it or force close it without clicking abort/stop ShareX will be unable to start a new screen/gif recording without restarting the application

**Comment by TheAdventist** [comment]
I understand the question, but not the logic. Why do you want to forcefully quit the recording without ShareX making any attempt to save your work....
Don't mean to be mean though :)

**Comment by NovusTheory** [comment]
It's just a bug, that's all it is. It's in case it actually force quits (not by the user)
