### ISSUE TITLE
Drag and drop didn't do anything I expect it to

### ISSUE THREAD

**Issue by Anonanon** [ShareX/ShareX#2885]
I dragged and dropped an image on a web page to the drag and drop box (which had to be manually invoked). Instead of outputting a clipboard link to the hosted image, it gave me a hosted txt file containing the original image URL, which sounds absolutely nothing like the feature implies.

I would like to see an enhancement where if I drag and drop a web image on to the area, it should upload the image and then copy the output image URL to my clipboard. And to make this feature extremely good, allow the user to drag and drop to the tray icon instead. Make this feature as part of the list of single/double click tray icon options.

**Comment by Jaex** [comment]
I tried dragging image from Chrome to Paint, Paint .NET and Photoshop and none of them could read it. Because Chrome not drags image. So it is not ShareX fault.

**Comment by Anonanon** [comment]
Is it possible to make it so when you drag and drop a web image on to the tray icon, it saves a temporary local copy to C:\Program Files (x86)\ShareX\ShareX\Screenshots (or whereever your directory is), upload that local file, save hosted URL to clipboard, then auto delete the temporary local copy?

**Comment by LuteroK** [comment]
There's a chrome extension that allows you to upload and manage Sharex from within Chrome.

**Comment by Anonanon** [comment]
Thanks LuteroK, I never knew about that extension, that's exactly what I want. When I install the extension and enable it in Integration, attempting to use it gives me an error "Download failed: System.Net.WebException: The remote server returned an error: (404) Not found."

**Comment by campbeb** [comment]
This is similar to #1630
