### ISSUE TITLE
Adding magnifying glass

### ISSUE THREAD

**Issue by szegi** [ShareX/ShareX#2891]
It would be great if in screenshot region mode i could add effect like this
https://www.screenpresso.com/how-to-create-gorgeous-magnifying-glass-effects/
or something like this
http://www.snapfiles.com/screenshots/n4magnify.htm

**Comment by Jaex** [comment]
Main reason I didn't add this tool is because 2x enlarged image looks bad.

**Comment by vatterspun** [comment]
> Main reason I didn't add this tool is because 2x enlarged image looks bad.

I think the main idea is to get an image that you'll resize smaller later, especially email.  So it's ugly in the editor but it looks better once you shrink it.  Maybe there's a way to make the magnifying effect go along with shrinking the main image, I dunno.

Workaround: I occasionally build these inside PowerPoint or LibreOffice Impress.  

1. Paste in two of the same image:

![image](https://user-images.githubusercontent.com/1289134/33181316-6856e36e-d035-11e7-9953-26f95af0eee9.png)

2. Shrink the first image and crop the second:

![image](https://user-images.githubusercontent.com/1289134/33181608-75f44880-d036-11e7-96e4-e4d9adc5369a.png)

3. Draw a frame around the area you want to zoom in and it's result, then add an arrow

![image](https://user-images.githubusercontent.com/1289134/33181601-696f1414-d036-11e7-82bd-41c16b13f146.png)

**Comment by szegi** [comment]
yes maybe this approach is possible

**Comment by Jaex** [comment]
@vatterspun you can already do exactly that easily using "Image (Screen)" and resize:

![](https://jaex.getsharex.com/2017/12/ShareX_yz9l87sqa7.png)

**Comment by szegi** [comment]
@Jaex i dont see this options with size and canvas in my menu

**Comment by Jaex** [comment]
That menu not exists in region capture annotation, it is in after capture tasks -> image editor etc.

**Comment by szegi** [comment]
@Jaex i dont see option to change from greenshot editor to different
sorry for offtopic but i see it can solve my other issue;p

**Comment by Jaex** [comment]
In task settings window -> advanced tab -> UseShareXForAnnotation option.

**Comment by vatterspun** [comment]
> you can already do exactly that using "Image (Screen)" and resize:

Oh nice!  Thanks for that.  That's much faster than my trick.

**Other workarounds**

This lit a fire under me so I did a bit of digging and came across a few other possible workarounds.  None are any better than what Jaex already listed:

1. A virtual magnifying glass: http://magnifier.sourceforge.net/
2. SnapDraw Free - a rather old and not very good freeware image capture/editor from several years ago  (http://www.crossgl.com/asc_overview.htm).  
3. Screenpresso has a tool for this but that program has several issues including loads of feature limitations for the pro version and requires a net connection for some reason (https://www.screenpresso.com/features/).

**Comment by Jaex** [comment]
Now I'm adding magnify tool but like I told before it looks bad when zoom is pixelated like this:

![](https://jaex.getsharex.com/2019/05/chrome_qyqZIaxB4K.png)

It looks even worse if I use anti aliasing because of blurry result.

**Comment by vatterspun** [comment]
> Now I'm adding magnify tool but like I told before it looks bad when zoom is pixelated like this:

You're right that the pixelated image doesn't look good, but the ideal usage for zoom is to call attention to something on a big interface.  I used this frequently at a previous job where our developers keep jamming more and more items onto an ever-growing interface.  One example (though far from the worst) is Thunderbird with the Lightning calendar add-on enabled: on smaller screens it can be overwhelming.  So a zoom view would highlight the area you're trying to point users to:

![image](https://user-images.githubusercontent.com/1289134/57117680-a6216480-6d23-11e9-8e2a-f2d5b735bb3d.png)

As such, I think what would make the most sense is to both boost the section you want to focus viewers on and then reduce the size of the image by 50%.  So for the image you posted above:

![image](https://user-images.githubusercontent.com/1289134/57117663-6f4b4e80-6d23-11e9-8702-c504c0f97f92.png)
