### ISSUE TITLE
Problem with capturing a web page with multimedia content.

### ISSUE THREAD

**Issue by Elkillax7** [ShareX/ShareX#2895]
Hi everybody, I found a little problem when I was using this software.

If you want to capture a web page with multimedia content, especifically with videos, in fact ShareX captures the whole page, but ShareX reproduces the multimedia content of the web page too. This is a problem, because if you are listening music in a web page (e.g Youtube), you have to close the capturator of ShareX if you want to hear only one sound at the time. Sometimes the people need to work with a web page and ShareX simultaneosly, but due to this problem this is not so possible.

Thanks for your atention friends.

**Comment by vatterspun** [comment]
Could you give a little more detail?  If @Jaex can't reproduce your issue, he can't fix it.

Here's a pretty good look at submitting a good bug report
https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
