### ISSUE TITLE
Double easter egg doesnt follow resolution changes

### ISSUE THREAD

**Issue by TheOddball** [ShareX/ShareX#2896]
I know this is basically a non-issue but I like bugging Jaex :)
http://i.oddball.tf/zoOl2.png
In this display configuration, the bouncing window acts like the bottom of the primary monitor continues to the 2nd, bouncing underneath the screen. http://i.oddball.tf/kRHfh.jpg

**Comment by Jaex** [comment]
I don't have multi monitor so it would be difficult for me to fix and test it.

**Comment by stuntguy3000** [comment]
As someone who has multiple monitors, I'm happy to have a crack at this.

On one condition,

**Share the Easter egg.**
