### ISSUE TITLE
[Feature Request] Support Mac and Linux platforms

### ISSUE THREAD

**Issue by aaronfranke** [ShareX/ShareX#2897]
It would be nice to have. I can't recommend this tool to my friends if it doesn't work for everyone.

**Comment by sylveon** [comment]
Duplicate of #498

**Comment by aaronfranke** [comment]
That bug report is closed and contains outdated information.

> C# (.NET Framework) not supported officially in mac or linux.

https://www.microsoft.com/net/core#linuxubuntu https://github.com/Microsoft/dotnet 

Alternatively, if .NET < 4.0 is required, http://www.mono-project.com may work.

**Comment by sylveon** [comment]
#162 #2217
