### ISSUE TITLE
Add optional checkbox for public uploads to S3

### ISSUE THREAD

**Issue by cynotek** [ShareX/ShareX#2899]
I employ CloudFront in front of my S3 bucket serving my files uploaded from ShareX, utilizing this CDN enables me to restrict access to files strictly through the CDN endpoint, rather than direct bucket access. ShareX applies a public ACL to every object uploaded, meaning that if a user wanted, they could simply bypass the CDN and access the file directly if they wanted, potentially creating more cost due to bandwidth not being accessed through the CDN. This is called Origin Access Policy, which allows CloudFront to access the bucket and serve files and disables direct bucket access "makes it private". Forcing all files to be accessible through the CDN only. This checkbox should be enabled by default obviously, but the option to not have that public read header always on would be nice, considering you can configure buckets to have all files publicly readable anyway without applying the header to each object.

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

**Comment by Jaex** [comment]
Added by #3021
