### ISSUE TITLE
Having the browser tab title as an image property

### ISSUE THREAD

**Issue by LGFN** [ShareX/ShareX#2901]
Perhaps this can be seen as two questions/requests: I capture screenshots from browser windows very often and I'd love to be able to search for it later.

Is it possible to:

1. Get the title of the _tab_
2. Put it in a property of the image (I.e. "Title")

Thank you.

**Comment by vatterspun** [comment]
I can see this being very useful as well but I wonder if some tabs wouldn't have extremely long names that would result in very long file names with odd characters.  For example one of my tabs right now is "Inbox (12) - username@email.com - Gmail - Other"  So the program would both need to convert non-filename characters and truncate titles to maybe 15 characters.

**Comment by LGFN** [comment]
I can understand the issue with page titles having illegal characters and being too long for the file name, but putting it in a property (like Title) as suggested shouldn't cause any issues. Regardless, even using it as filenames should work using your method of converting and truncating.

**Comment by harolato** [comment]
Has there been any progress on this one? Maybe some parsing/filtering could be done after fetching page title for it to be usable as a file name?
