### ISSUE TITLE
'Laggy' selector while using transparent region mode

### ISSUE THREAD

**Issue by MAGICCC** [ShareX/ShareX#2906]
Somehow the selector is laggy when using the transport region mode.
The ShareX process uses ~12% of my cpu and therefore I can't capture region quickly.
Note: The normal region is doing fine, but I am using the transparent mode for e.g. RDP sessions

![](https://m.mufff.in/084.png)

**Comment by icedream** [comment]
This issue still exists. To be exact, during selection a full CPU core is used by ShareX and RAM usage increases. The RAM usage decreases by the same amount again after selection but the CPU usage remains at a full CPU core.
