### ISSUE TITLE
ShareX sudden setting issues.

### ISSUE THREAD

**Issue by DrOutside** [ShareX/ShareX#2918]
Hello! I'm not sure how it happen but whenever I attempt to take a screenshot this bar appears: https://i.imgur.com/KJA9QZL.png and I have no idea how to disable it.

On top of that, prior to this if I simple did the hotkey for taking a screenshot, dragged it over an area then let go of my left click it took a screenshot of the selected area. But now if I drag over it, it doesn't take a screenshot immediately and have to now double click instead.

I tried looking through the settings but can't find anything.

Can I please get some help on how I can go back to my old settings without these two new things? Thanks so much!

**Comment by Jaex** [comment]
This causing you to not instantly capture area:

![](https://jaex.getsharex.com/2017/11/ShareX_6kq7BdqsCV.png)

**Comment by DrOutside** [comment]
Thank you so much for that!

However I'm still confused as to how I can hide the UI bar in the first place while taking a screenshot

This bar is what I'm talking about: https://i.imgur.com/KJA9QZL.png

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/11/ShareX_9EmwRj1sgb.png)
