### ISSUE TITLE
New Workflows Not Saved

### ISSUE THREAD

**Issue by mikegeig** [ShareX/ShareX#2919]
Howdy, I love this tool but lately I've had some frustrations getting my custom workflows to save. This is the first time I am trying custom workflows so I don't know if it has always been like this or if this is a new bug. After I create a new workflow it has a pencil icon next to it. Whenever I reboot my system, I lose any workflows I have created. Am I doing something wrong? Is there some way to save these that I am not seeing?

Image for reference:
![image](https://user-images.githubusercontent.com/3311369/32625512-61228020-c55a-11e7-8745-da78234dbb5d.png)

Thanks!

**Comment by stuntguy3000** [comment]
@mikegeig Is this still an issue?

I cannot replicate this problem.
