### ISSUE TITLE
Update the Tweet Message box to allow 280 characters

### ISSUE THREAD

**Issue by TheRandomMelon** [ShareX/ShareX#2921]
![image](https://user-images.githubusercontent.com/22629722/32683665-9db64042-c642-11e7-82e7-e7602f41c925.png)
_ShareX's current Tweet Message window._

Right now, ShareX's Tweet Message box only allows for 140 characters. This should be updated to 280 characters.

**Comment by Jaex** [comment]
I already updated it in codes, it will be available next release.

**Comment by TheRandomMelon** [comment]
Ah, sorry.
