### ISSUE TITLE
What exactly is "reopen ShareX for personal folder changes"?

### ISSUE THREAD

**Issue by ooker777** [ShareX/ShareX#2923]
I want to move all config data of ShareX to another location, but I don't know how to follow this dialog:

![](https://i.imgur.com/rdFeRbV.png)

What exactly is "reopen ShareX for personal folder changes"? What should I have done?

**Comment by sylveon** [comment]
Just restart the program.

**Comment by ooker777** [comment]
I did exit and relaunch it, but when I restart the computer, it returns to the previous folder and start anew.
