### ISSUE TITLE
Disable saving of screenshots?

### ISSUE THREAD

**Issue by psbj** [ShareX/ShareX#2924]
Is it possible to completely disable the saving of screenshots in a local folder? Because I use a custom uploader that saves the uploaded files to a remote server, I don't need copies saved in a local folder. 

If this isn't possible, could this feature be added?

Thank you for this amazing program!

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/11/ShareX_WOlQrakgB8.png)

Uncheck that option.

**Comment by rustov** [comment]
This option is unchecked but the program still saves all screens to my local disk...

**Comment by psbj** [comment]
Yeah I noticed this as well, there's months of captured screenshots saved even though that option is checked.

**Comment by psbj** [comment]
@Jaex Can we get an option to delete saved screenshots after they're uploaded?
