### ISSUE TITLE
Audio Voice  Only Recording

### ISSUE THREAD

**Issue by xianx** [ShareX/ShareX#2925]
Sometimes It is very important to share only voice record to team member. Is there a any option to do that with sharex. Will please consider voice only recording option to next version?

**Comment by Jaex** [comment]
You can just record audio if you select "None" as video device in screen recording settings.

**Comment by xianx** [comment]
But that is not the stander way to record voice. and for it one have to change setting every time for record voice and again changing settings for record video. I think it  need little development to introduce a voice record feature. Will you please add a feature to capture voice in next release?

**Comment by Jaex** [comment]
You can have different hotkey for voice recording which can have different setting. So it won't require you to change setting at all.

**Comment by xianx** [comment]
Cant it be a separate option for voice share?
