### ISSUE TITLE
Software Requirements Specification Document (SRS)

### ISSUE THREAD

**Issue by koufounak** [ShareX/ShareX#2928]
Hello,
I really liked your project and i think it's very usefull.
I want to create a Software Requirements Specification Document(SRS) for this project. I think that it can improve the precodural aspect of the project by describing analytically the functionality and structure of the program as well as it's features and of course it's requirements. This will clarify the purpose of the software making it easier to develop new parts for it as well as testing them and the allready existing ones. The structure of the document i want to use will be in agreement with the Karl E. Wiegers' template.
Download Link of the tamplate : www.exinfm.com/training/M2C3/srs_template.doc

I really hope i'll get a possitive feedback of this,
Dimitrios Koufounakis.

**Comment by vatterspun** [comment]
> ... it can improve the precodural aspect of the project by describing analytically the functionality and structure of the program as well as it's features and of course it's requirements

Some questions here: 

* Have you done this for other projects?
* How do you expect this to help the ShareX project?
* What's with the "shareware" notice on the top of that template?  Does someone need to pay for that?

@koufounak I've written a few documents like the one you describe but that's usually to get organizations on the same page about project resources.  I think @Jaex has put together a pretty good website for that purpose.  Still, if you can start filling in something and show that it's something valuable, I welcome it.  At minimum, I would recommend using something other than Microsoft Word template to create this unless you're not really looking for collaborators.  LibreOffice, GoogleDocs, any number of Wikis, and other tools all have better collaborative capabilities than Word and are free.

**Comment by vatterspun** [comment]
I recommend closing this issue.  I think it's probably a useful tool, but not for the ShareX project.
