### ISSUE TITLE
Small request: Cmd-A to select all in OCR text box

### ISSUE THREAD

**Issue by ianaf100** [ShareX/ShareX#2938]
I have a keyboard shortcut for OCR which is massively convenient. However, Cmd/Ctrl-A doesn't work in the text box that comes up, meaning I have to manually select everything with my mouse. It's a small thing but it gets me every time. It would be great to be able to quickly do Cmd-A, Cmd-C to copy everything instead of having to use the mouse.

And I am on Windows 7 64 bit, version 11.9.1

**Comment by NovusTheory** [comment]
#2868

**Comment by Jaex** [comment]
#2852
