### ISSUE TITLE
drawing shapes no longer transparent

### ISSUE THREAD

**Issue by Kangarude** [ShareX/ShareX#2940]
all of a sudden my shapes are filled with colour, and i cant for the life of me work out how to make them transparent again

eg below - its filled with green,  i just want the red box

![image](https://user-images.githubusercontent.com/33894065/33119136-0582d414-cfa9-11e7-9971-d5b1ef01caa1.png)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/11/ShareX_NL2V55TpVQ.png)

You can make fill color transparent like this.

**Comment by Kangarude** [comment]
thank you so much, super speedy response!
