### ISSUE TITLE
Blur + Pixelate Region Capture

### ISSUE THREAD

**Issue by pydlv** [ShareX/ShareX#2942]
You are currently able to draw areas to be blurred or pixelated in the screenshot region area. I constantly find myself drawing both of these effects onto the same region to create a combined effect, but it would be nice to have a single option to apply both of them at once, so I don't have to draw each of them separately.

For example, take the following image:
![image](https://user-images.githubusercontent.com/24441042/33186827-a5b3db7a-d041-11e7-917c-fd7060fefd23.png)

Blurred:
![image](https://user-images.githubusercontent.com/24441042/33186839-bd6ea29a-d041-11e7-87e3-354fb93de740.png)

Pixelated:
![image](https://user-images.githubusercontent.com/24441042/33186852-dcb35e2a-d041-11e7-8422-d525daeacdf9.png)

Blurred + pixelated:
![image](https://user-images.githubusercontent.com/24441042/33186855-efd844ca-d041-11e7-9157-e5ebe4bcf4a2.png)

**Comment by Jaex** [comment]
You know you can change strength of blur and pixelate right?

**Comment by pydlv** [comment]
> You know you can change strength of blur and pixelate right?
Yes, I am aware of that option. I concede that it is a matter of personal preference to use both blur and pixelation as opposed to a stronger effect of either one independently. Being able to apply both with one click seems like something that a tool as elaborate as ShareX would benefit from.

**Comment by Jaex** [comment]
Toolbar size already keep becoming bigger therefore I'm not planning to add another tool to make blur + pixelate together.
