### ISSUE TITLE
Adware report once again

### ISSUE THREAD

**Issue by maujogador** [ShareX/ShareX#2944]
I recently updated my record-devices in the settings and ever since every now and then (5-10 mins) my browser opens tabs by itself see [this](https://i.imgur.com/JANE1I4.png) and [this](https://i.imgur.com/wGOfuaE.png)
I saw [#2864](https://github.com/ShareX/ShareX/issues/2864) and started experimenting myself. Here's what I've found:
[process memory](https://i.imgur.com/U36FsEQ.png)
[virus total scan](https://www.virustotal.com/#/file/ade6116389e002962a87651bae370ed9186108cd29160f0226f57d7297f50c1b/detection)

**Comment by Jaex** [comment]
ShareX-11.9.1-setup.exe:
https://www.virustotal.com/#/file/91a4c497c314f95313b80acddc0ac01511507f7ce71eb980e2d2e31f60b259d6/detection

Recorder-devices-setup.exe:
https://www.virustotal.com/#/file/bcd17e2a9474677ae28858bedf9c9af03fef6ea23aec32119fea453d141d52de/detection

What is "Publisher.exe" VirtualTotal link you gave?

**Comment by maujogador** [comment]
This is the file: http://www.mediafire.com/file/b7sj82ufpuy7287/Recorder-devices-setup.rar
This is my hash: https://i.imgur.com/ovQMfbG.png

Whenever i upload it to virustotal it shows up as publisher.exe, I don't know why
I would appreciate if you could link me a good recorder-devices-setup.exe

**Comment by Jaex** [comment]
Your file have different file size and icon as you can see from here:

![](https://jaex.getsharex.com/2017/11/explorer_LGXsXGQ09Q.png)

Hash is also different. Which means something in your PC replaced it.

**Comment by maujogador** [comment]
I'm not sure of what is going on   https://streamable.com/n97c0
I will just reinstall everything

**Comment by sylveon** [comment]
Yes, it might be a good idea.

Following the link in the memory analysis of the process brings to this page:

![](https://cdn.discordapp.com/attachments/280092803587899392/384056213484208138/image.png)

Which is an obvious attempt at faking the Microsoft login page for users to install an """"""antivirus""""".

This leads me to the conclusion a virus has infected your machine.
