### ISSUE TITLE
Is it possible to filter by url in history?

### ISSUE THREAD

**Issue by gety9** [ShareX/ShareX#2946]
Guys,

Sometimes my push is expired and shows "That puush could not be found."
But i still need it and would like to reupload the file/image.

Is there a way to find file that i've used by provided url?

In history i see only "Filename filter"
https://puu.sh/ytzKH/444cae9138.png

How can i filter by url?
It takes some time to find this url / file combo manually :)

**Comment by Jaex** [comment]
Currently you can search URL inside `Documents\ShareX\History.xml` file.

**Comment by gety9** [comment]
@Jaex @Fyers I don't see it, using Newest version 12.2 on Windows 10 and see only this
https://puu.sh/BWdhg/0f43891c1c.png

it filters by host name, but not url, am i missing something?

**Comment by Jaex** [comment]
New version not released yet.

**Comment by gety9** [comment]
@Jaex what is the release date? can install this patch myself?

**Comment by Jaex** [comment]
Yes you can install it like this: https://getsharex.com/docs/dev-builds
