### ISSUE TITLE
i face show this error windows8 32bit

### ISSUE THREAD

**Issue by asmilon0** [ShareX/ShareX#2947]
https://i.imgur.com/5OKBTU1.png

**Comment by vatterspun** [comment]
There's a hundred reasons why that might be failing but you can download FFMPEG manually from here:

https://ffmpeg.zeranoe.com/builds/

1. Extract the downloaded zip file somewhere
2. Change the folder in **Task settings - Screen Recorder - Screen Recording options** to point to that folder (press the "..." to navigate there)

![image](https://user-images.githubusercontent.com/1289134/33792348-59effaca-dc62-11e7-9ab3-e71e1d2f94b2.png)

3. You're done.

Note that you just need the file _bin\ffmpeg.exe_ and can delete the others if you need to save space.
