### ISSUE TITLE
Wrong mouse cursor position on mp4 video created by "screen capture" on highDPI monitor

### ISSUE THREAD

**Issue by dtgeorge** [ShareX/ShareX#2953]
Win10 x64, 1920*1080 sreen, system scale is 125%.
On mp4 file created by Screen Capture mouse cursor has wrong position.

Please, check the video: https://www.fastprint.ua/issuie_sample_shareX.mp4
In real world I was clicking mouse cursor on text postions and text cursor moves to place I clicked.
In video we can see that mouse cursor is not over text, but at som other place... If I would clicking as video shows - text cursor would not be affected.

**Comment by dtgeorge** [comment]
Duplicate to what issue #?

I've searched for opend issues before, doesn't find any... Sorry!

**Comment by Jaex** [comment]
#1329
