### ISSUE TITLE
Cannot update ShareX using dialog window that pops up on program startup (Windows 10)

### ISSUE THREAD

**Issue by DiskPro** [ShareX/ShareX#2954]
Even when launching the application with administrator privileges, accepting the update does not yield any result. This same window keeps popping up on program startup every time, and yet, I can update the program using the link provided on the "About" section.

I am running ShareX on Windows 10 Enterprise x64, cannot provide build version as the dialog only appears when there is a new avaliable version, but as of now, I am running the most up-to-date version.

**Comment by Jaex** [comment]
You were probably stuck in 2 years old version which had update dialog broken.
