### ISSUE TITLE
[PENDING] Option to change node visuals

### ISSUE THREAD

**Issue by sergeevabc** [ShareX/ShareX#2955]
Being an active user who regularly reports bugs and explains how to use various pieces of software, I need to grab and comment small parts of the screen. New nodes visuals, bulky and opaque, introduced in 12.0 are obstacles to this mission, therefore I’m looking for a way to revert back to transparent squares.

![](https://images.vfl.ru/ii/1511905264/37261c4e/19609552.png)

**Comment by sergeevabc** [comment]
Alas, this option is not ready in the latest 12.1.0

**Comment by Jaex** [comment]
What do you think I should call that setting when I add it to this menu as checkbox:

![](https://jaex.getsharex.com/2018/08/ShareX_g91Ynue8G7.png)

**Comment by Jaex** [comment]
Currently I added code side of it but having hard time finding suitable label for that setting.

**Comment by sergeevabc** [comment]
@Jaex, thank you.
