### ISSUE TITLE
Custom Uploader error: Please enable Javascript in your browser.

### ISSUE THREAD

**Issue by Prophesied** [ShareX/ShareX#2960]
I am trying to setup a custom uploader with ShareX but it gives me the following error:
`please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>`

How can I fix this?
My browsers have JavaScript enabled.

**Comment by TTtie** [comment]
ShareX doesn't depend on your browser to get the data. It fetches the data as it is, not as it displays in your browser.

**Comment by Jaex** [comment]
It is problem in your custom uploader script.

**Comment by AnalPudding** [comment]
fucking nigger yes
