### ISSUE TITLE
Upload image to Imgur.com failed

### ISSUE THREAD

**Issue by AEBus** [ShareX/ShareX#2962]
There a debug log:

>2017-12-01 02:26:08.660 - Task in queue. Job: Job, Type: Image, Host: Imgur

>2017-12-01 02:26:08.676 - Task status: Preparing

>2017-12-01 02:26:08.692 - Upload started. Filename: 2017-12-01_02-26-08.png

>2017-12-01 02:26:08.692 - UploadersConfig save successful: C:\Users\AEBus\Documents\ShareX\UploadersConfig.json

>2017-12-01 02:26:08.761 - HotkeysConfig save successful: C:\Users\AEBus\Documents\ShareX\HotkeysConfig.json

>2017-12-01 02:26:08.807 - ApplicationConfig save successful: C:\Users\AEBus\Documents\ShareX\ApplicationConfig.json

>2017-12-01 02:26:09.664 - Error:
>Message:
>The remote server returned an error: (400) Bad Request.

>Request URL:
>https://api.imgur.com/3/image

>Response:
>{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

>Stack trace:
>   at System.Net.HttpWebRequest.GetResponse()
>   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

>2017-12-01 02:26:09.711 - Upload failed. Retrying upload.

>2017-12-01 02:26:11.559 - Error:
>Message:
>The remote server returned an error: (400) Bad Request.

>Request URL:
>https://api.imgur.com/3/image

>Response:
>{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

>Stack trace:
>   at System.Net.HttpWebRequest.GetResponse()
>   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

>2017-12-01 02:26:11.591 - Task failed. Filename: 2017-12-01_02-26-08.png, Errors:
>Imgur upload failed: (400) Forbidden

>Message:
>The remote server returned an error: (400) Bad Request.

>Request URL:
>https://api.imgur.com/3/image

>Response:
>{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

>Stack trace:
>   at System.Net.HttpWebRequest.GetResponse()
>   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
Did you tried re authenticating to Imgur if you are using your account.
Can you try uploading from Imgur web site?

**Comment by AEBus** [comment]
>Did you tried re authenticating to Imgur if you are using your account.

Yes

>Can you try uploading from Imgur web site?

No... This is strange... An error occurs on the page https://imgur.com/upload:
>{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":{}},"request":"\/upload","method":"GET"},"success":false,"status":403}

**Comment by Jaex** [comment]
Then that means problem is not to do with ShareX.

**Comment by AEBus** [comment]
Just for information, how i fixed this problem:
Simply changed my email address in imgur.com account settings from .ru zone to gmail

**Comment by West456** [comment]
Changing the email helps with this Problem.

**Comment by gitalexhubuser** [comment]
Ok. Problem is **gone**. I`m shooting a short video how to fix it.
https://www.youtube.com/watch?v=yH8b9DzTySg
![default](https://user-images.githubusercontent.com/17017177/42728389-c63855f0-87c1-11e8-9d86-bbee963f2b9e.jpg)
