### ISSUE TITLE
Fail when resizing

### ISSUE THREAD

**Issue by Tsvetkovv** [ShareX/ShareX#2963]
Steps to reproduce
1. Capture an area, screenshot editor is opened.
2. Create new screenshot and copy it.
3. Paste the image into the first editor.
4. Hold Shift and try to resize pasted image
5. Crashing

Error report is here: https://pastebin.com/MyZDDaHM
App version: **12.0**
OS: **Win 10, 64x**
After, the app is not responsible, but I can take a screenshot :)
![image](https://user-images.githubusercontent.com/11594423/33469891-d5e2944c-d67e-11e7-9b5b-5c3aaa92b763.png)

**Comment by Revvilo** [comment]
Has the fixed version not been released yet?

![image](https://user-images.githubusercontent.com/13816212/33914854-0c3e9bc8-e005-11e7-91aa-4fd964a7496f.png)

**Comment by Jaex** [comment]
No, but you can use dev build.
