### ISSUE TITLE
Import Image Effects don't work on 12.0

### ISSUE THREAD

**Issue by viper25** [ShareX/ShareX#2964]
Upgraded ShareX Portable from 11X to the latest 12.0. Before doing so, I exported my Image Effects: `Task Settings > Image Effects > Image Effects Configuration > Export` (to JSON).

Opened up 12.0, Imported the General settings (that doesn't seem to import Image effects btw) and then went into `Task Settings > Image Effects > Image Effects Configuration > Import`

Nothing is imported.

Side Note: I assumed Exporting adn Importing **Application Settings** should've brought everything over.

**Comment by Jaex** [comment]
Image effect setting format is now changed so it is not importable from previous versions.
