### ISSUE TITLE
[Feature Request] Floating toolbar

### ISSUE THREAD

**Issue by tam481** [ShareX/ShareX#2965]
Hello, would it be possible to add a floating toolbar for various capture options as well as quick setting changes such as cursor visibility and countdown as these are currently very hard to change.

Thank you in advance

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/12/TMnf0PnGtd.png)

This?

**Comment by tam481** [comment]
That's wonderful. It just needs the ability to toggle the cursor visibility and a countdown timer.

**Comment by nothinglastsforever** [comment]
> a countdown timer

I cannot emphasize this request enough. Please add it!
