### ISSUE TITLE
FFmpeg Error. Cant record any gifs.

### ISSUE THREAD

**Issue by yuvali1337** [ShareX/ShareX#2967]
Hello, so i have this issue with ShareX, I cant record any GIF's it open an FFmpeg Error.
Heres the log: 
```ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[gdigrab @ 0000018c38d024c0] Capturing whole desktop as 222x256x32 at (1630,493)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1512134018.436796, bitrate: 54571 kb/s
    Stream #0:0: Video: bmp, bgra, 222x256, 54571 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0000018c376db540] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000018c376db540] profile High 4:4:4 Predictive, level 1.3, 4:4:4 8-bit
[libx264 @ 0000018c376db540] 264 - core 152 r2851 ba24899 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'C:\Users\yuval\Documents\ShareX\Screenshots\2017-12\47451SHb.mp4':
  Metadata:
    encoder         : Lavf57.56.100
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 222x256, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.64.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame=   36 fps=0.0 q=0.0 size=      48kB time=00:00:01.16 bitrate= 339.4kbits/s speed=2.33x    
frame=   51 fps= 51 q=0.0 size=      54kB time=00:00:01.66 bitrate= 267.5kbits/s speed=1.66x    
frame=   66 fps= 44 q=0.0 size=      55kB time=00:00:02.16 bitrate= 208.5kbits/s speed=1.44x    
frame=   75 fps= 41 q=0.0 Lsize=      57kB time=00:00:02.46 bitrate= 187.8kbits/s speed=1.36x    
video:55kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.372156%
[libx264 @ 0000018c376db540] frame I:1     Avg QP: 0.00  size: 31464
[libx264 @ 0000018c376db540] frame P:74    Avg QP: 0.00  size:   332
[libx264 @ 0000018c376db540] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0000018c376db540] mb P  I16..4:  0.6%  0.0%  0.0%  P16..4:  0.3%  0.0%  0.0%  0.0%  0.0%    skip:99.1%
[libx264 @ 0000018c376db540] coded y,u,v intra: 100.0% 9.6% 11.6% inter: 0.1% 0.1% 0.1%
[libx264 @ 0000018c376db540] i16 v,h,dc,p: 26% 49% 24%  0%
[libx264 @ 0000018c376db540] kb/s:179.33
ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\yuval\Documents\ShareX\Screenshots\2017-12\47451SHb.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.56.100
  Duration: 00:00:02.50, start: 0.000000, bitrate: 185 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 222x256, 181 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Output #0, image2, to 'D:\Steam Games\steamapps\common\ShareX\ShareX\palette.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.56.100
    Stream #0:0(und): Video: png, rgba, 16x16 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.64.100 png
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
[Parsed_palettegen_0 @ 0000027f0ea55ca0] 232(+1) colors generated out of 232 colors; ratio=1.000000
```

Please help.

**Comment by yuvali1337** [comment]
More organized code can be found here > https://yuv41artworkz.xyz/img/hosting/19o8bNcc.txt

**Comment by gordonwalkedby** [comment]
the same problem with you, need fix!
`ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[gdigrab @ 0000024aa15b7fe0] Capturing whole desktop as 346x200x32 at (440,330)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1512136028.321142, bitrate: 19933 kb/s
    Stream #0:0: Video: bmp, bgra, 346x200, 19933 kb/s, 9 fps, 9 tbr, 1000k tbn, 1000k tbc
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0000024aa15bd5c0] using cpu capabilities: MMX2 SSE2Fast LZCNT
[libx264 @ 0000024aa15bd5c0] profile High 4:4:4 Predictive, level 1.1, 4:4:4 8-bit
[libx264 @ 0000024aa15bd5c0] 264 - core 152 r2851 ba24899 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=3 lookahead_threads=3 sliced_threads=1 slices=3 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=9 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'C:\Users\Walkedby\Documents\ShareX\Screenshots\2017-12\2017-12-01_21-47-06.mp4':
  Metadata:
    encoder         : Lavf57.56.100
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 346x200, q=-1--1, 9 fps, 18432 tbn, 9 tbc
    Metadata:
      encoder         : Lavc57.64.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame=   23 fps=0.0 q=0.0 size=     224kB time=00:00:02.44 bitrate= 750.3kbits/s speed=4.82x    
frame=   28 fps= 28 q=0.0 size=     225kB time=00:00:03.00 bitrate= 613.9kbits/s speed=2.95x    
frame=   29 fps= 24 q=0.0 Lsize=     226kB time=00:00:03.11 bitrate= 594.8kbits/s speed=2.62x    
video:225kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.430703%
[libx264 @ 0000024aa15bd5c0] frame I:1     Avg QP: 0.00  size: 14075
[libx264 @ 0000024aa15bd5c0] frame P:28    Avg QP: 0.00  size:  7704
[libx264 @ 0000024aa15bd5c0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0000024aa15bd5c0] mb P  I16..4: 49.2%  0.0%  0.0%  P16..4:  6.9%  0.0%  0.0%  0.0%  0.0%    skip:43.9%
[libx264 @ 0000024aa15bd5c0] coded y,u,v intra: 15.9% 4.6% 4.6% inter: 8.4% 0.4% 0.4%
[libx264 @ 0000024aa15bd5c0] i16 v,h,dc,p: 84% 11%  5%  0%
[libx264 @ 0000024aa15bd5c0] kb/s:570.52
ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Walkedby\Documents\ShareX\Screenshots\2017-12\2017-12-01_21-47-06.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.56.100
  Duration: 00:00:03.22, start: 0.000000, bitrate: 574 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 346x200, 571 kb/s, 9 fps, 9 tbr, 18432 tbn, 18 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Output #0, image2, to 'F:\Steam\steamapps\common\ShareX\ShareX\palette.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.56.100
    Stream #0:0(und): Video: png, rgba, 16x16 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 9 fps, 9 tbn, 9 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.64.100 png
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
[Parsed_palettegen_0 @ 000002590ac392a0] 3(+1) colors generated out of 3 colors; ratio=1.000000
`

**Comment by Jaex** [comment]
Are you using Steam build?

**Comment by Jaex** [comment]
https://trac.ffmpeg.org/ticket/6786

**Comment by Jaex** [comment]
Released new Steam build update which using latest FFmpeg nightly build which don't have this issue.
