### ISSUE TITLE
Window borders are recorded only partly

### ISSUE THREAD

**Issue by sergeevabc** [ShareX/ShareX#2973]
Win7 x64, [7Squared Aero][1] theme with transparency turned off
ShareX v12.0, FFMPEG [20171201][3]

The following issue reveals itself in GIF and video recordings, whereas image capture works fine.

GIF made by ShareX, one window border (the bottom one) is missing.

![](https://images.vfl.ru/ii/1512243863/0d20c471/19662157.gif)

GIF made by [ScreenToGif][2] v2.10, the same version of FFMPEG, all window borders are visible.

![](https://images.vfl.ru/ii/1512243863/a8160de0/19662156.gif)

Changing Source from ScreenCaptureRecorder [v0.12.10][4] to GDIPanel does not help.
Tried to use ShareX with earlier version of FFMPEG (e.g. stable [v3.4][5]), but it throws errors then. 

[1]: https://sumitmandal.deviantart.com/art/7-Squared-362610348
[2]: https://github.com/NickeManarin/ScreenToGif
[3]: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20171130-83ecdc9-win64-static.zip
[4]: https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases
[5]: https://ffmpeg.zeranoe.com/builds/

**Comment by Jaex** [comment]
Because ShareX initially records it as x264 and it requires even width/height for encoding, therefore your region height decreased by 1 px to make height even number.

**Comment by sergeevabc** [comment]
Sorry, but I do not see why this issue is invalid, since promised feature is not fully provided.

**Comment by Jaex** [comment]
How you won't see it as invalid? FFmpeg not allows x264 recording with odd height size.

**Comment by sergeevabc** [comment]
There is an operation system, manufactured to be customizable.
There is a theme for this OS to be applied, which meets manufacturer’s standards.
It skins windows as rectangles without tricky rounded corners and they co-exist without a hassle.
There is an application, which claims to be able to capture screen parts in still and in motion.
This application for whatever reasons is designed so it depends on other applications.
Now such subapp fails to do its job, fails to capture an element, which user can see and touch.
Being a user, I believe either subapp should be tweaked or parent app should get a workaround.
Because for mere users there are no odd heights, there are screen parts and capture tools.

**Comment by sergeevabc** [comment]
Dear @NickeManarin, the very developer of ScreenToGif, could you be so kind to tell if you app uses FFMPEG for GIF recording as well (I saw such field in settings) or you preferred to go the other way?

**Comment by NickeManarin** [comment]
@sergeevabc No, FFmpeg is only used after the capture, for the encoding of the video. 

The workaround used by ScreenToGif to save the video with an odd width/height is to simply use padding, with the command:

`-c:v libx264 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black"`

Before the encoding, I just need to replace the `{W}` and `{H}` with a valid size.

**Comment by sergeevabc** [comment]
From what I am able to grasp, there are at least three actions to consider regarding ShareX:
* show warning message if element’s height is odd and advise user to change window size
* add pixel by padding instead of removing pixel from element user explicitly asked to record
* rework GIF recording in order to reduce dependence on FFMPEG

Sounds reasonable, @Jaex? What do you think, @McoreD?

**Comment by sergeevabc** [comment]
@Jaex, I see you have silently committed a change, which presumably improves GIF recording, so the ice is broken and this issue no longer seems to be invalid. Should we mark as fixed then?
