### ISSUE TITLE
QR Code window not preloading clipboard contents

### ISSUE THREAD

**Issue by Spown** [ShareX/ShareX#2974]
Prior the QR code decode tab was introduced the encode window would assume the clipboard string as the input. Now it opens with no input and the user has to paste it manually. Not a big hassle, but still would be nice to have this functionality back.

Thank you.

**Comment by Jaex** [comment]
Currently it only pastes clipboard contents if text is url.

**Comment by Spown** [comment]
hm, yeah, come to think of this I probably never tried to encode a simple string and only encoded urls thias way.

Than consider it a feature request: extending autoloading for the arbitrary string as well. Probably a max length is in order to keep it sane.

Thank you.

**Comment by Scrxtchy** [comment]
Fun fact, this was an oversight because I forgot to commit extra code
