### ISSUE TITLE
error

### ISSUE THREAD

**Issue by the-mec** [ShareX/ShareX#2975]
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (429) nginx.

Request URL:
https://api.imgur.com/3/image

Response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <title>    Imgur: the most awesome 429 page on the internet</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=1138">
        <meta name="robots" content="noindex,nofollow" />
    <meta name="keywords" content="images, photos, gif, gifs, memes, pictures, new pictures, reaction gifs, share photos, share images, latest images, funny, cute, visual storytelling, imgur" />
    <meta name="description" content="Imgur is the best place to share and enjoy the most awesome images on the Internet. Every day, millions of people use Imgur to be entertained and inspired by funny, heartwarming and helpful images and stories from all around the world." />
    <meta name="copyright" content="Copyright 2017 Imgur, Inc." />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge;" />
    
    <link rel="icon" type="image/png" href="//s.imgur.com/images/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="//s.imgur.com/images/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="//s.imgur.com/images/favicon-16x16.png" sizes="16x16">
    <link rel="apple-touch-icon-precomposed" href="//s.imgur.com/images/favicon-152.png">
    <meta name="msapplication-TileColor" content="#2cd63c">
    <meta name="msapplication-TileImage" content="//s.imgur.com/images/favicon-144.png">
    
        <link rel="stylesheet" type="text/css" href="//s.imgur.com/min/404.css?1512158938" />

            
    
            <link rel="canonical" href="https://imgur.com/3/image" />
        <meta property="og:url" content="https://imgur.com/3/image" />
    

            <link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.imgur.com/3/image">
    

    <meta name="p:domain_verify" content="a1e7abe8af908cc6dfaf935dd9a20384"/>
    <meta property="og:site_name" content="Imgur" />
    <meta property="fb:admins" content="12331492" />
    <meta property="fb:admins" content="12301369" />
    <meta property="fb:app_id" content="127621437303857" />
    <meta property="al:android:url" content="imgur://imgur.com/3/image?from=fbreferral" />
    <meta property="al:android:app_name" content="Imgur" />
    <meta property="al:android:package" content="com.imgur.mobile" />
    <meta property="al:ios:url" content="imgur://imgur.com/3/image?from=fbreferral" />
    <meta property="al:ios:app_store_id" content="639881495" />
    <meta property="al:ios:app_name" content="Imgur" />
    <meta property="al:web:url" content="https://imgur.com/3/image" />
    <meta name="twitter:site" content="@imgur" />
    <meta name="twitter:domain" content="imgur.com" />
    <meta name="twitter:app:id:googleplay" content="com.imgur.mobile" />
            <meta property="og:title" content="Imgur" />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="Imgur: The most awesome images on the Internet." />
        <meta property="og:image" content="https://s.imgur.com/images/logo-1200-630.jpg?2" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:width" content="1200" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Imgur" />
        <meta name="twitter:description" content="Imgur: The most awesome images on the Internet." />
        <meta name="twitter:image:src" content="//s.imgur.com/images/logo-1200-630.jpg?2" />
        <meta name="twitter:image:height" content="630" />
        <meta name="twitter:image:width" content="1200" />
        <meta name="twitter:creator" content="@imgur" />
    

    
    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "WebSite",
            "url": "https://imgur.com",
            "name": "Imgur",
            "potentialAction": {
                "@type": "SearchAction",
                "target": "https://imgur.com/search?q={search_term_string}",
                "query-input": "required name=search_term_string"
            }
        }
    </script>
    
    
    
</head>
<body class="">
    <div id="drop-layer"></div>
            
    

    

    

    

        <div class="footer textbox">
        <h1>Whoa! You're moving too fast.</h1>
        <p>Please wait a few minutes and make your request again.</p>
        <p>If you are looking for groovy images, <a href="//imgur.com">visit our gallery!</a></p>
        <a href="//imgur.com" class="footer-logo"><img src="//s.imgur.com/images/imgurlogo-header.png"></a>
    </div>
    

    

            
    

    

    

            <script type="text/javascript" src="//s.imgur.com/min/advertising.js?1512158938"></script>

        <script>
            !function(a9,a,p,s,t,A,g){if(a[a9])return;function q(c,r){a[a9]._Q.push([c,r])}a[a9]={init:function(){q("i",arguments)},fetchBids:function()
            {q("f",arguments)},setDisplayBids:function(){},_Q:[]};A=p.createElement(s);A.async=!0;A.src=t;g=p.getElementsByTagName(s)[0];g.parentNode.insertBefore(
            A,g)}("apstag",window,document,"script","//c.amazon-adsystem.com/aax2/apstag.js");
            apstag.init({pubID: '3079', adServer: 'googletag', bidTimeout: 2e3});
        </script>

        <script type="text/javascript" class="abp" src="//s.imgur.com/min/px.js?ch=1"></script>
        <script type="text/javascript" class="abp" src="//s.imgur.com/min/px.js?ch=2"></script>

        <script type="text/javascript">
            window.runSlots = {
                config: {"ads_website":"http:\/\/www.imgurads.com\/","allow_nsfw":false,"allow_unmoderated":false,"allow_subreddits_nsfw":false,"_enabled_":true,"active_slots":[{"name":"under_sidebar","element":"div-gpt-ad-under_sidebar","insertSelector":".panel-ad","insertMethod":"append","sizes":[[300,250],[300,600]],"slot_id":"\/4761660\/H_I_300x250","prebid":{"sovrn":{"prod":true,"config":{"bidder":"sovrn","params":{"tagid":"151260"}}},"aol":{"prod":true,"config":{"bidder":"aol","params":{"placement":"3937264","network":"9432.1","sizeId":"170"}}},"indexExchange":{"prod":true,"config":{"bidder":"indexExchange","params":{"id":"1","siteID":172790}}},"criteo":{"prod":false,"config":{"bidder":"criteo","params":{"zoneId":"706134"}}},"districtmDMX":{"prod":true,"config":{"bidder":"districtmDMX","params":{"id":"144150"}}},"sonobi":{"prod":false,"config":{"bidder":"sonobi","params":{"placement_id":"4ab906a688a14fe00b28"}}}}},{"name":"top_banner","element":"div-gpt-ad-top_banner","insertSelector":"#inside .post-container","insertMethod":"before","sizes":[[728,90]],"slot_id":"\/4761660\/Leaderboard_970x90_ATF","prebid":{"sovrn":{"prod":true,"config":{"bidder":"sovrn","params":{"tagid":"151259"}}},"aol":{"prod":true,"config":{"bidder":"aol","params":{"placement":"3937263","network":"9432.1","sizeId":"225"}}},"indexExchange":{"prod":true,"config":{"bidder":"indexExchange","params":{"id":"2","siteID":164899}}},"criteo":{"prod":false,"config":{"bidder":"criteo","params":{"zoneId":"706133"}}},"districtmDMX":{"prod":true,"config":{"bidder":"districtmDMX","params":{"id":"144152"}}},"sonobi":{"prod":false,"config":{"bidder":"sonobi","params":{"placement_id":"cee8b35ed54a1b43c870"}}}}},{"name":"spotlight","element":"div-gpt-ad-spotlight","domElement":"iframe","sizes":[[728,90]],"slot_id":"\/4761660\/Leaderboard_728x90_ATF_LI","prebid":null},{"name":"pop_sky","element":"div-gpt-ad-sky_pop","insertSelector":"#fixed-side-footer-links","insertMethod":"after","sizes":[[300,600],[160,600],[300,250]],"slot_id":"\/4761660\/H_I_160x600","prebid":{"sovrn":{"prod":true,"config":{"bidder":"sovrn","params":{"tagid":"151261"}}},"aol":{"prod":true,"config":{"bidder":"aol","params":{"placement":"3937265","network":"9432.1","sizeId":"154"}}},"indexExchange":{"prod":true,"config":{"bidder":"indexExchange","params":{"id":"3","siteID":172792}}},"criteo":{"prod":false,"config":{"bidder":"criteo","params":{"zoneId":"706132"}}},"districtmDMX":{"prod":true,"config":{"bidder":"districtmDMX","params":{"id":"144151"}}},"sonobi":{"prod":false,"config":{"bidder":"sonobi","params":{"placement_id":"691b4c88b69d09969705"}}}}}],"bidder_adjustments":{"aol":0.9,"districtmDMX":0.9,"indexExchange":1,"sovrn":1,"sonobi":1,"criteo":1},"partners":{"gpt":{"src":"\/\/www.googletagservices.com\/tag\/js\/gpt.js"}},"global_flags":{"page_load":true,"other":false,"user_page":false,"album_page":true},"gallery_flags":{"gallery":true,"subreddit":true,"subreddit_nsfw":false},"item_flags":{"album":true,"in_gallery":true,"mature":false,"sixth_unmod":false,"sixth_mod_safe":true,"sixth_mod_unsafe":false,"onsfw_unmod":false,"onsfw_mod_safe":true,"onsfw_mod_unsafe":false,"nsfw":false,"promoted":false,"referer":true,"share":true,"spam":false,"under_10":false},"defaultFlags":{"album":true,"in_gallery":true,"mature":false,"sixth_unmod":false,"sixth_mod_safe":true,"sixth_mod_unsafe":false,"onsfw_unmod":false,"onsfw_mod_safe":true,"onsfw_mod_unsafe":false,"nsfw":false,"promoted":false,"referer":true,"share":true,"spam":false,"under_10":false,"gallery":true,"subreddit":true,"subreddit_nsfw":false,"page_load":true,"other":false,"user_page":false,"album_page":true}},
                item: undefined
            };

            var PREBID_TIMEOUT = 1000;
            var pbjs = pbjs || { };
            pbjs.que = pbjs.que || [];
        </script>
        <script type="text/javascript" src="//s.imgur.com/min/runSlots.js?1512158938"></script>

    

    

            <script>
            var ReactDOM = window.ReactDOM || window.React;
            ReactDOM.render(React.createElement(Imgur.Upload,
                    {
                        privacy: Imgur.Environment.auth.album_privacy,
                        host: Imgur.Environment.host,
                        instance: 'global',
                        emitter: imgur._.emitter,
                        has_access: false,
            }),
            document.getElementById('upload-global'));
        </script>
    

            <script type="text/javascript">
            if (typeof _widgetFactory !== 'undefined') {
                _widgetFactory.initNotifications(null, [{"name":"Neutral","reputation":399},{"name":"Accepted","reputation":999},{"name":"Liked","reputation":1999},{"name":"Trusted","reputation":3999},{"name":"Idolized","reputation":7999},{"name":"Renowned","reputation":19999},{"name":"Glorious","reputation":9223372036854775807}]);
            }
        </script>
    

    

    

            <script type="text/javascript">
        if (typeof _widgetFactory !== 'undefined') {
            _widgetFactory.produceSearch();
            _widgetFactory.initIdleMonitor();
        }
        </script>
    

        
    

            <script type="text/javascript">
            Imgur.Util.getGoogleTracker();
            __ga('send', 'pageview');
        </script>

        
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        

        

        <script type="text/javascript">
    var _comscore = _comscore || [];
    _comscore.push({ c1: "2", c2: "7770950" });
    (function() {
        var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
        s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
        el.parentNode.insertBefore(s, el);
    })();
</script>
<noscript>
    <img src="http://b.scorecardresearch.com/p?c1=2&c2=7770950&cv=2.0&cj=1" />
</noscript>
        
<script type="text/javascript">
var _qevents = _qevents || [];
(function() {
    var elem = document.createElement('script');
    elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";
    elem.async = true;
    elem.type = "text/javascript";
    var scpt = document.getElementsByTagName('script')[0];
    scpt.parentNode.insertBefore(elem, scpt);
})();
_qevents.push({
    qacct:"p-f8oruOqDFlMeI"
});
</script>

<noscript>
    <div style="display:none;"><img src="//pixel.quantserve.com/pixel/p-f8oruOqDFlMeI.gif" border="0" height="1" width="1" alt="Quantcast"/></div>
</noscript>

        
<script src="//tags.crwdcntrl.net/c/11429/cc_af.js" async></script>

        <script type="text/javascript">
            !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
            n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
            document,'script','//connect.facebook.net/en_US/fbevents.js');

            fbq('init', '742377892535530');
            fbq('track', 'PageView');

            if (document.location.search === '?reg') {
                fbq('track', 'CompleteRegistration');
            }
        </script>
        <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=742377892535530&ev=PageView&noscript=1"/></noscript>
    

            <script type="text/javascript">
        
        (function(){
            try{
                var msg = '\n      _\n     (_)\n      _ _ __ ___   __ _ _   _ _ __\n     | | \'_ ` _ \\ / _` | | | | \'__|\n     | | | | | | | (_| | |_| | |\n     |_|_| |_| |_|\\__, |\\__,_|_|\n                   __/ |\n                  |___/\n';
                msg += '========================================\nYou opened the console! Know some code,\ndo you? Want to work for one of the best\nstartups around? https://imgur.com/jobs\n========================================\n';
                console.log(msg);
            }catch(e){}
        })()
        
    </script>
    
    

    
</body>
</html>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (429) nginx.

Request URL:
https://api.imgur.com/3/image

Response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <title>    Imgur: the most awesome 429 page on the internet</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=1138">
        <meta name="robots" content="noindex,nofollow" />
    <meta name="keywords" content="images, photos, gif, gifs, memes, pictures, new pictures, reaction gifs, share photos, share images, latest images, funny, cute, visual storytelling, imgur" />
    <meta name="description" content="Imgur is the best place to share and enjoy the most awesome images on the Internet. Every day, millions of people use Imgur to be entertained and inspired by funny, heartwarming and helpful images and stories from all around the world." />
    <meta name="copyright" content="Copyright 2017 Imgur, Inc." />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge;" />
    
    <link rel="icon" type="image/png" href="//s.imgur.com/images/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="//s.imgur.com/images/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="//s.imgur.com/images/favicon-16x16.png" sizes="16x16">
    <link rel="apple-touch-icon-precomposed" href="//s.imgur.com/images/favicon-152.png">
    <meta name="msapplication-TileColor" content="#2cd63c">
    <meta name="msapplication-TileImage" content="//s.imgur.com/images/favicon-144.png">
    
        <link rel="stylesheet" type="text/css" href="//s.imgur.com/min/404.css?1512158938" />

            
    
            <link rel="canonical" href="https://imgur.com/3/image" />
        <meta property="og:url" content="https://imgur.com/3/image" />
    

            <link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.imgur.com/3/image">
    

    <meta name="p:domain_verify" content="a1e7abe8af908cc6dfaf935dd9a20384"/>
    <meta property="og:site_name" content="Imgur" />
    <meta property="fb:admins" content="12331492" />
    <meta property="fb:admins" content="12301369" />
    <meta property="fb:app_id" content="127621437303857" />
    <meta property="al:android:url" content="imgur://imgur.com/3/image?from=fbreferral" />
    <meta property="al:android:app_name" content="Imgur" />
    <meta property="al:android:package" content="com.imgur.mobile" />
    <meta property="al:ios:url" content="imgur://imgur.com/3/image?from=fbreferral" />
    <meta property="al:ios:app_store_id" content="639881495" />
    <meta property="al:ios:app_name" content="Imgur" />
    <meta property="al:web:url" content="https://imgur.com/3/image" />
    <meta name="twitter:site" content="@imgur" />
    <meta name="twitter:domain" content="imgur.com" />
    <meta name="twitter:app:id:googleplay" content="com.imgur.mobile" />
            <meta property="og:title" content="Imgur" />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="Imgur: The most awesome images on the Internet." />
        <meta property="og:image" content="https://s.imgur.com/images/logo-1200-630.jpg?2" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:width" content="1200" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Imgur" />
        <meta name="twitter:description" content="Imgur: The most awesome images on the Internet." />
        <meta name="twitter:image:src" content="//s.imgur.com/images/logo-1200-630.jpg?2" />
        <meta name="twitter:image:height" content="630" />
        <meta name="twitter:image:width" content="1200" />
        <meta name="twitter:creator" content="@imgur" />
    

    
    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "WebSite",
            "url": "https://imgur.com",
            "name": "Imgur",
            "potentialAction": {
                "@type": "SearchAction",
                "target": "https://imgur.com/search?q={search_term_string}",
                "query-input": "required name=search_term_string"
            }
        }
    </script>
    
    
    
</head>
<body class="">
    <div id="drop-layer"></div>
            
    

    

    

    

        <div class="footer textbox">
        <h1>Whoa! You're moving too fast.</h1>
        <p>Please wait a few minutes and make your request again.</p>
        <p>If you are looking for groovy images, <a href="//imgur.com">visit our gallery!</a></p>
        <a href="//imgur.com" class="footer-logo"><img src="//s.imgur.com/images/imgurlogo-header.png"></a>
    </div>
    

    

            
    

    

    

            <script type="text/javascript" src="//s.imgur.com/min/advertising.js?1512158938"></script>

        <script>
            !function(a9,a,p,s,t,A,g){if(a[a9])return;function q(c,r){a[a9]._Q.push([c,r])}a[a9]={init:function(){q("i",arguments)},fetchBids:function()
            {q("f",arguments)},setDisplayBids:function(){},_Q:[]};A=p.createElement(s);A.async=!0;A.src=t;g=p.getElementsByTagName(s)[0];g.parentNode.insertBefore(
            A,g)}("apstag",window,document,"script","//c.amazon-adsystem.com/aax2/apstag.js");
            apstag.init({pubID: '3079', adServer: 'googletag', bidTimeout: 2e3});
        </script>

        <script type="text/javascript" class="abp" src="//s.imgur.com/min/px.js?ch=1"></script>
        <script type="text/javascript" class="abp" src="//s.imgur.com/min/px.js?ch=2"></script>

        <script type="text/javascript">
            window.runSlots = {
                config: {"ads_website":"http:\/\/www.imgurads.com\/","allow_nsfw":false,"allow_unmoderated":false,"allow_subreddits_nsfw":false,"_enabled_":true,"active_slots":[{"name":"under_sidebar","element":"div-gpt-ad-under_sidebar","insertSelector":".panel-ad","insertMethod":"append","sizes":[[300,250],[300,600]],"slot_id":"\/4761660\/H_I_300x250","prebid":{"sovrn":{"prod":true,"config":{"bidder":"sovrn","params":{"tagid":"151260"}}},"aol":{"prod":true,"config":{"bidder":"aol","params":{"placement":"3937264","network":"9432.1","sizeId":"170"}}},"indexExchange":{"prod":true,"config":{"bidder":"indexExchange","params":{"id":"1","siteID":172790}}},"criteo":{"prod":false,"config":{"bidder":"criteo","params":{"zoneId":"706134"}}},"districtmDMX":{"prod":true,"config":{"bidder":"districtmDMX","params":{"id":"144150"}}},"sonobi":{"prod":false,"config":{"bidder":"sonobi","params":{"placement_id":"4ab906a688a14fe00b28"}}}}},{"name":"top_banner","element":"div-gpt-ad-top_banner","insertSelector":"#inside .post-container","insertMethod":"before","sizes":[[728,90]],"slot_id":"\/4761660\/Leaderboard_970x90_ATF","prebid":{"sovrn":{"prod":true,"config":{"bidder":"sovrn","params":{"tagid":"151259"}}},"aol":{"prod":true,"config":{"bidder":"aol","params":{"placement":"3937263","network":"9432.1","sizeId":"225"}}},"indexExchange":{"prod":true,"config":{"bidder":"indexExchange","params":{"id":"2","siteID":164899}}},"criteo":{"prod":false,"config":{"bidder":"criteo","params":{"zoneId":"706133"}}},"districtmDMX":{"prod":true,"config":{"bidder":"districtmDMX","params":{"id":"144152"}}},"sonobi":{"prod":false,"config":{"bidder":"sonobi","params":{"placement_id":"cee8b35ed54a1b43c870"}}}}},{"name":"spotlight","element":"div-gpt-ad-spotlight","domElement":"iframe","sizes":[[728,90]],"slot_id":"\/4761660\/Leaderboard_728x90_ATF_LI","prebid":null},{"name":"pop_sky","element":"div-gpt-ad-sky_pop","insertSelector":"#fixed-side-footer-links","insertMethod":"after","sizes":[[300,600],[160,600],[300,250]],"slot_id":"\/4761660\/H_I_160x600","prebid":{"sovrn":{"prod":true,"config":{"bidder":"sovrn","params":{"tagid":"151261"}}},"aol":{"prod":true,"config":{"bidder":"aol","params":{"placement":"3937265","network":"9432.1","sizeId":"154"}}},"indexExchange":{"prod":true,"config":{"bidder":"indexExchange","params":{"id":"3","siteID":172792}}},"criteo":{"prod":false,"config":{"bidder":"criteo","params":{"zoneId":"706132"}}},"districtmDMX":{"prod":true,"config":{"bidder":"districtmDMX","params":{"id":"144151"}}},"sonobi":{"prod":false,"config":{"bidder":"sonobi","params":{"placement_id":"691b4c88b69d09969705"}}}}}],"bidder_adjustments":{"aol":0.9,"districtmDMX":0.9,"indexExchange":1,"sovrn":1,"sonobi":1,"criteo":1},"partners":{"gpt":{"src":"\/\/www.googletagservices.com\/tag\/js\/gpt.js"}},"global_flags":{"page_load":true,"other":false,"user_page":false,"album_page":true},"gallery_flags":{"gallery":true,"subreddit":true,"subreddit_nsfw":false},"item_flags":{"album":true,"in_gallery":true,"mature":false,"sixth_unmod":false,"sixth_mod_safe":true,"sixth_mod_unsafe":false,"onsfw_unmod":false,"onsfw_mod_safe":true,"onsfw_mod_unsafe":false,"nsfw":false,"promoted":false,"referer":true,"share":true,"spam":false,"under_10":false},"defaultFlags":{"album":true,"in_gallery":true,"mature":false,"sixth_unmod":false,"sixth_mod_safe":true,"sixth_mod_unsafe":false,"onsfw_unmod":false,"onsfw_mod_safe":true,"onsfw_mod_unsafe":false,"nsfw":false,"promoted":false,"referer":true,"share":true,"spam":false,"under_10":false,"gallery":true,"subreddit":true,"subreddit_nsfw":false,"page_load":true,"other":false,"user_page":false,"album_page":true}},
                item: undefined
            };

            var PREBID_TIMEOUT = 1000;
            var pbjs = pbjs || { };
            pbjs.que = pbjs.que || [];
        </script>
        <script type="text/javascript" src="//s.imgur.com/min/runSlots.js?1512158938"></script>

    

    

            <script>
            var ReactDOM = window.ReactDOM || window.React;
            ReactDOM.render(React.createElement(Imgur.Upload,
                    {
                        privacy: Imgur.Environment.auth.album_privacy,
                        host: Imgur.Environment.host,
                        instance: 'global',
                        emitter: imgur._.emitter,
                        has_access: false,
            }),
            document.getElementById('upload-global'));
        </script>
    

            <script type="text/javascript">
            if (typeof _widgetFactory !== 'undefined') {
                _widgetFactory.initNotifications(null, [{"name":"Neutral","reputation":399},{"name":"Accepted","reputation":999},{"name":"Liked","reputation":1999},{"name":"Trusted","reputation":3999},{"name":"Idolized","reputation":7999},{"name":"Renowned","reputation":19999},{"name":"Glorious","reputation":9223372036854775807}]);
            }
        </script>
    

    

    

            <script type="text/javascript">
        if (typeof _widgetFactory !== 'undefined') {
            _widgetFactory.produceSearch();
            _widgetFactory.initIdleMonitor();
        }
        </script>
    

        
    

            <script type="text/javascript">
            Imgur.Util.getGoogleTracker();
            __ga('send', 'pageview');
        </script>

        
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        

        

        <script type="text/javascript">
    var _comscore = _comscore || [];
    _comscore.push({ c1: "2", c2: "7770950" });
    (function() {
        var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
        s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
        el.parentNode.insertBefore(s, el);
    })();
</script>
<noscript>
    <img src="http://b.scorecardresearch.com/p?c1=2&c2=7770950&cv=2.0&cj=1" />
</noscript>
        
<script type="text/javascript">
var _qevents = _qevents || [];
(function() {
    var elem = document.createElement('script');
    elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";
    elem.async = true;
    elem.type = "text/javascript";
    var scpt = document.getElementsByTagName('script')[0];
    scpt.parentNode.insertBefore(elem, scpt);
})();
_qevents.push({
    qacct:"p-f8oruOqDFlMeI"
});
</script>

<noscript>
    <div style="display:none;"><img src="//pixel.quantserve.com/pixel/p-f8oruOqDFlMeI.gif" border="0" height="1" width="1" alt="Quantcast"/></div>
</noscript>

        
<script src="//tags.crwdcntrl.net/c/11429/cc_af.js" async></script>

        <script type="text/javascript">
            !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
            n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
            document,'script','//connect.facebook.net/en_US/fbevents.js');

            fbq('init', '742377892535530');
            fbq('track', 'PageView');

            if (document.location.search === '?reg') {
                fbq('track', 'CompleteRegistration');
            }
        </script>
        <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=742377892535530&ev=PageView&noscript=1"/></noscript>
    

            <script type="text/javascript">
        
        (function(){
            try{
                var msg = '\n      _\n     (_)\n      _ _ __ ___   __ _ _   _ _ __\n     | | \'_ ` _ \\ / _` | | | | \'__|\n     | | | | | | | (_| | |_| | |\n     |_|_| |_| |_|\\__, |\\__,_|_|\n                   __/ |\n                  |___/\n';
                msg += '========================================\nYou opened the console! Know some code,\ndo you? Want to work for one of the best\nstartups around? https://imgur.com/jobs\n========================================\n';
                console.log(msg);
            }catch(e){}
        })()
        
    </script>
    
    

    
</body>
</html>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
It is Imgur problem:

```The remote server returned an error: (429) nginx.```
