### ISSUE TITLE
Need help with Custom Uploaders (pCloud)

### ISSUE THREAD

**Issue by welpdx** [ShareX/ShareX#2976]
Hey Jaex,

I love your project and have been trying to add my own Cloud Service to the uploader for ease of access.
Using the Custom Uploader Editor under Destination Settings, I was unable to reproduce an url but was able to upload the file. 

The issue is because the pCloud Api does not have a method to "Upload" and "Generate a Download Link" at the same time. (Ie [uploadfile](https://docs.pcloud.com/methods/file/uploadfile.html) and [getfilepublink](https://docs.pcloud.com/methods/public_links/getfilepublink.html))

**Since, I'm not that good of a coder, I was wondering if you can have a look at it.** This "uploader" for pCloud seems to be very similar to mediafire where you only need the login info and path. 
I've tried to take a look at the UploadersConfig.json but I got a bit confused so I didn't mess with that lol.

Here's what I did: [Picture of Result](https://vgy.me/3BR02D.jpg)

*I did not add "$json:url$" or edit the Response Text condition to see the outputs.

[Output code: ](https://pastebin.com/k0XNif72)

`{
    "result": 0,
    "metadata": [
        {
            "name": "Test.png",
            "created": "Sun, 03 Dec 2017 16:16:50 +0000",
            "thumb": true,
            "modified": "Sun, 03 Dec 2017 16:16:50 +0000",
            "isfolder": false,
            "height": 256,
            "fileid": 4572377023,
            "width": 256,
            "hash": 7109101225546285670,
            "path": "\/New\/Test.png",
            "category": 1,
            "id": "f4572377023",
            "isshared": false,
            "ismine": true,
            "size": 27391,
            "parentfolderid": 1247261759,
            "contenttype": "image\/png",
            "icon": "image"
        }
    ],
    "checksums": [
        {
            "sha1": "1b8b9f68f561c21c6cec15191738c1a3692910df",
            "md5": "0c0e15c159f2080678a61c4dd1f355a6"
        }
    ],
    "fileids": [
        4572377023
    ]
}`

[Json Code:](https://pastebin.com/Dde9rKpa)

`{
      "Name": "pCloud3",
      "DestinationType": "FileUploader",
      "RequestType": "POST",
      "RequestURL": "https://api.pcloud.com/uploadfile",
      "FileFormName": "filename",
      "Arguments": {
        "username": "testingcode@yandex.com",
        "password": "test123",
        "path": "/New"
      },
      "ResponseType": "Text",
      "URL": "",
      "ThumbnailURL": "",
      "DeletionURL": ""
    },`

Thanks,

You may also use the username and password in the Json. (The acc was created for this purpose)

**Comment by NovusTheory** [comment]
One suggestion could be that if you're able to modify source code for pCloud that you could implement a system that allows you to poll the public file link with the upload url and implement that into the response.
