### ISSUE TITLE
Setting tasktray icon double-click to "start/stop recording with custom region" results in a screen-shot and recording to be taken when used

### ISSUE THREAD

**Issue by alanosman** [ShareX/ShareX#2978]
Windows 10, Creators 2 release
ShareX version 12.0

**Issue**
When I set the default action for left double click on task track icon to "start/stop recording using custom region", double clicking the task tray icon is not resulting in the same action as right-clicking the task-tray icon, selecting capture and then selecting screen recording (which is what I assumed it would do).  Instead it seems to take a screen shot and start recording at the same time. .

![image](https://user-images.githubusercontent.com/2914981/33574800-675dabba-d908-11e7-8c69-f0bba4f6d95c.png)

**Comment by Jaex** [comment]
I tested now it just did screen recording without take screen capture.

**Comment by alanosman** [comment]
Still the same for me.  here's a vid.

https://www.screencast.com/t/keS9GmN5G4

It could be that it is picking up the configuration of my after capture tasks which is not the same set of steps if I select Capture -> Screen Recording.

![image](https://user-images.githubusercontent.com/2914981/33608797-a6903ef2-d993-11e7-852c-f59a7088aa12.png)

Another scenario is that I have 3 monitors, though I don't think that has anything to do with it.

**Comment by Jaex** [comment]
This is very weird. I'm not sure how it can happen. Is your Windows double click time modified? Because it is used to detect single click instead of double click.

**Comment by alanosman** [comment]
@Jaex When you ask "is my Windows double click modified time modified".. the answer is no, not in any other unusual way.  The only thing I have set here is in ShareX settings, where I have single click for screen shot and double click for video.  Ahh... wait - so this gives me an idea.

So I just tested by turning off single click screen shot and now it behaves correctly.  So for some reason, ShareX is picking up both events set.  It is picking up single click and double click and executing both at the same time. 

So this works
![image](https://user-images.githubusercontent.com/2914981/33609273-7e58c6be-d995-11e7-9782-482f38a46bba.png)

And this does not
![image](https://user-images.githubusercontent.com/2914981/33609302-958ce8ba-d995-11e7-81c3-2658ee3679b5.png)

**Comment by DogeAmazed** [comment]
I got the same issue and debugged it a bit. The following calls came out (`HH:mm:ss.ffff`):
```
12:53:37.7446 - niTray_MouseDoubleClick
12:53:37.8678 - niTray_MouseClick
12:53:40.4035 - timerTraySingleClick_Tick
```

So somehow the double click get called first, so the timer never get stopped by it.
