### ISSUE TITLE
FTP upload but permission error for view

### ISSUE THREAD

**Issue by huntervcx** [ShareX/ShareX#2982]
HI,
I use ShareX to upload my screens to a vps, in order to show my screens online. but when an img is uploaded, the default permission don't give a public read wich cause a 403 error on my website. I couldn't find a way to configure this

**Comment by andreblue** [comment]
That would be something with your setup. Try making it so your ftp related user has permission. IF if it is linux add the user to the web group

**Comment by huntervcx** [comment]
The folrder is in 777 permission, user already have access, but when a file is uploaded the default permission is 600 (and webserver need at least 644)
