### ISSUE TITLE
Image Effects: Rounded corners only on top?

### ISSUE THREAD

**Issue by AE1360** [ShareX/ShareX#2985]
Hey, was curious if we could get the option to have it apply to all 4 corners of an image?

Perhaps make it just like some of the others and allow all 4 corners to be set separately if you wanted. As it is right now, it only rounds the top corners.

**Comment by Jaex** [comment]
It rounds all corners. You probably have canvas at bottom.

**Comment by AE1360** [comment]
I did, I haven't checked adding rounded since I fixed the canvas part. My bad!
