### ISSUE TITLE
Capture regions got clipped

### ISSUE THREAD

**Issue by finejustice** [ShareX/ShareX#2988]
as the image below, capture regins got clipped.
![2017-12-09_14-18-43](https://user-images.githubusercontent.com/5276596/33792786-607cab88-dcec-11e7-9d13-dba4b9e93807.png)

I cannot capture outside of the dimmed region, like taskbar, start menu, etc.

Capture Fullscreen still works.

I tried to find any 3rd party apps which causes this issue but I found no one.

**Comment by Jaex** [comment]
Duplicate of #1800
