### ISSUE TITLE
[Suggestion] Choose imgur image link type

### ISSUE THREAD

**Issue by Maveee** [ShareX/ShareX#2993]
When you upload an image to imgur you have a few options link-wise:

- image link
- direct link
- markdown link
- html
- bbcode
- linked bbcode

The myimgur program already enables you to select your preferred link, but I'd rather switch to ShareX.

For me personally I use the bbcode a lot: [img]image link[/img] so this would come in quite handy!

Cheers.
![ibrrmye](https://user-images.githubusercontent.com/8791604/33835560-2c019084-de87-11e7-9743-681ad036d890.png)

**Comment by Jaex** [comment]
Main window right click menu already have all these options. There is even after upload window which you can enable which shows these options too.

**Comment by Maveee** [comment]
I cannot find an options to automatically copy the bbcode..

**Comment by sunbeam906** [comment]
^ Subscribing to same request. It is in the window, however no option to auto-copy the BBCode instead of the default link. Makes no sense to increase productivity when you're the one who should type all the time [img]ctrl+v[/img] :|

**Comment by Jaex** [comment]
This option can be used to configure auto copy format:

![](https://jaex.getsharex.com/2019/02/ShareX_IPPjgce0EF.png)

**Comment by ZeroCool22** [comment]
> This option can be used to configure auto copy format:
> 
> ![](https://camo.githubusercontent.com/0713b338d1bd636fad9afe0245bbba45b44807af0a4911a5a61ca4c6ce157d0f/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323031392f30322f5368617265585f4950506a6763653045462e706e67)

Can you tell me what value i should put there to get the BBCODE copied after upload?
