### ISSUE TITLE
[Suggestion] Multi-clipboard

### ISSUE THREAD

**Issue by Qwerty-Space** [ShareX/ShareX#2994]
I have a suggestion for ShareX called multi-clipboard.
I'll describe it using example hotkeys, just to make things easier.

You go to copy something, and you do `Ctrl+C` then you choose a clipboard by pressing another key like `X`, `C,` or `V`.

Then when you go to paste, you'll do `Ctrl+V` then `X`, `C`, or `V`.  
Obviously users will be able to change the clipboard keys and have as many as they like.  

This can be implemented into ShareX by bringing up a clipboard dialog showing what is in each clipboard.  And maybe if the user right clicks and selects pase, a circle appears around the cursor with each clipboard and their contents.  Like the inventory wheel in games like Dishonored 2.

You could also tell ShareX to copy images, or links to specific clipboards by default, or to ask the user to specify each time.

**Comment by vatterspun** [comment]
Why not something like Ditto or ArsClip?

**Comment by Qwerty-Space** [comment]
@vatterspun that won't integrate with ShareX very well, I don't think.

**Comment by vatterspun** [comment]
> that won't integrate with ShareX

Well, I use Ditto all the time and it works okay with several elements of ShareX such as file locations and passwords.  When I upload images to imgur and add those addresses to my clipboard, it stores them for later use.  

Maybe you could give an idea of what kind of behavior you were expecting that's more integrated than existing clipboard managers?

**Comment by Qwerty-Space** [comment]
@vatterspun "You could also tell ShareX to copy images, or links to specific clipboards by default, or to ask the user to specify each time."  For example, when taking a screenshot it copies to clipboard 1.  Video to clipboard 2, whatever.

And on the aftercapture window, it could have a dropdown on "copy" for different clipboards

**Comment by vatterspun** [comment]
I'm not sure I understand the use case behind this, meaning who really needs separate clipboards for different actions, but maybe @Jaex will have some insight.

**Comment by Qwerty-Space** [comment]
Say you're working on quite a few things, sometimes you need to copy multiple things a few times.  It can work for that too
