### ISSUE TITLE
Unable to make certain aspect ratios easily

### ISSUE THREAD

**Issue by jtm297** [ShareX/ShareX#2996]
Hello,

It is possible to show aspect ratios when selecting regions? I've noticed when I hold shift during my region selection it is only doing a square (nxn) region. I want to be able to make 16:9 ratio regions while holding shift then save my images as 200x123 size afterwards. Is this possible? Am I missing something? This feature is supported in Jing and I would really like to switch to ShareX.

**Comment by Solarbotics** [comment]
Ditto! I'm on board with this feature!

**Comment by Gertsch** [comment]
any news on this?

**Comment by madzadev** [comment]
second this, would be a very handy feature 😉

**Comment by Madekuji** [comment]
Same here, this feature definitely needs attention.

**Comment by ikjadoon** [comment]
Would also love this feature.

Being able to set ratios would be fantastic, as well, so we can one-click use them afterwards. 16:9, 9:16, 4:3, etc.

Currently, only 1:1 can be used by pressing & holding `Shift` while dragging.

**Comment by flleeppyy** [comment]
Any updates on this? Would be really useful for me when recording videos to Twitter because if I don't give a 16:9 video, twitter will compress the hell out of it.

**Comment by ikjadoon** [comment]
Is there a way to re-open this request? I'm curious if it being closed makes it appear as if final action has been taken. FWIW, [the other Stale issues all remain open](https://github.com/ShareX/ShareX/labels/Stale).

This also removes it from the primary stream of issues.

**Comment by szepeviktor** [comment]
Twitter needs 16:9 images.
It would be nice not use a calculator but to have fixed ratio.

**Comment by mplattner** [comment]
Would love to see this being implemented, @Jaex. Many thanks, ShareX is a fantastic tool. ❤️

**Comment by Chouffy** [comment]
There's kind of a workaround: in Task Settings → Capture → Region Capture, define Fixed size region mode to the ratio that you would like.
Then, during screenshot, resize the selected region while maintaining the `SHIFT` key - so the aspect ratio stays the same :)

![image](https://github.com/ShareX/ShareX/assets/9288966/5d01dbdd-5327-4fc7-9bf3-bad8f6193ebc)

**Comment by 2-fly-4-ai** [comment]
This feature is missing in every screenshot tool. Unistalled immediately. Your proposed solution is hacky and doesn't work.

**Comment by thewaliii** [comment]
Please add Aspect-ratio capture!
