### ISSUE TITLE
Clipboard auto clear

### ISSUE THREAD

**Issue by matthewburnett** [ShareX/ShareX#2997]
Clear the clipboard as a task after a specific timeout.

**Comment by vatterspun** [comment]
I went looking elsewhere for another program that could handle this, either in terms of a clipboard manager or a security tool.  I tried Sisma, which is a password manager with a clear password function, but from what I can tell it's manual.  There's also ClipAngel but it looks like that has the same problem.

**Comment by sylveon** [comment]
This AHK script can work. You can probably edit it to only clear if it contains the URL from your task or something

```ahk
#Persistent

; Triggered when the clipboard changes
OnClipboardChange:
    ; If it's not empty
    if (Clipboard != "") {
        Sleep, 30000 ; Wait for 30 seconds
        Clipboard := "" ; Clear the clipboard
    }```
