### ISSUE TITLE
Unable to select FTP server for image uploading

### ISSUE THREAD

**Issue by SacDin** [ShareX/ShareX#3]
Hello.

I have added FTP server, tested, working fine. Then from the left menu, when I select 'file uploader' for image files, the image straightly go to the dropbox. There is no option to select from which file uploader to use for image. Can you please help me on this ?

Thank you.

**Comment by laxerbrohan** [comment]
http://is.gd/Q25B81 Sorry for opening this again but I cannot seem to select FTP at all :/

**Comment by P4risAndStuff** [comment]
@laxerbrohan Did you set up your FTP in destinations?
