### ISSUE TITLE
[Feature Request] Draw over screenshot

### ISSUE THREAD

**Issue by Dubz** [ShareX/ShareX#3000]
It would be great to have some tools to do quick markups on a screenshot, rather than try to hack together manipulations through the watermark tool.

For instance, a pen to draw lines, circles, arrows, etc.
Shapes to add, as in neat circles and arrows, rather than drawing them as well.
Blocks to blur out certain sections or cut them out.

THis could obviously be expanded to other things if other people have input on what they'd like to see, but this is one thing ShareX does not have that other tools have, which I wish it did.

**Comment by Jaex** [comment]
All stuffs you told already exists in ShareX image editor.

**Comment by sylveon** [comment]
Hint: hit ctrl-printscreen

**Comment by Dubz** [comment]
I did not realize the image editor did all of this. I think I first imagined it just loaded it into Microsoft Paint to edit and all, but this is definitely a lot better than I had in mind.

Definitely going to be using this a lot more, and it will make screenshots a whole lot easier knowing this is available.
