### ISSUE TITLE
Feature Request - drag-and-drop video thumbnailer

### ISSUE THREAD

**Issue by nickodemos** [ShareX/ShareX#3001]
Asking that if a video file is dropped it can just start the Video Thumbnailer.

Add the name Video Thumbnailer under upload filters and we can set the files we want video thumbnailer to just auto create thumbnails for.

**Comment by vatterspun** [comment]
Housecleaning bit: @nickodemos could you set a more descriptive title?  So instead of "Feature Request" do something like "Feature Request - drag-and-drop video thumbnailer"

**Comment by vatterspun** [comment]
> nickodemos changed the title from Feature Request to Feature Request - drag-and-drop video thumbnailer

Cool, thanks.

**Comment by nickodemos** [comment]
This went stale so responding. If this is a no go idea let me know and I wont refresh this the next time it goes stale.

**Comment by nickodemos** [comment]
Back since I got an email about being stale.

**Comment by vatterspun** [comment]
> Back since I got an email about being stale.

I think it's the intention of the developers to let old issues auto-close.  This has happened for a LOT of issues in the ShareX Github site.  I think it's the equivalent of a WONTFIX.  You're welcome to ping him on the Discord server about the policy.
