### ISSUE TITLE
check if an image has been auto-uploaded or not

### ISSUE THREAD

**Issue by apllike** [ShareX/ShareX#3003]
Hi, I have used ShareX without knowing that it has a feature to auto upload captured images to Imgur. In order to check if my screenshots have been uploaded or not, I tried to use 'URL' or 'Deletion URL' options, but when I mouse right clicked each file, all URL related options seem to be disabled under 'Open' menu. The same thing happens in 'History' tab as well. Does this mean that the images have not been auto-uploaded?

**Comment by Jaex** [comment]
If URL buttons disabled that means it is not uploaded.
