### ISSUE TITLE
Owncloud/Nextcloud direct link error (&download)

### ISSUE THREAD

**Issue by alberizo** [ShareX/ShareX#3004]
Hi. The Owncloud option to add &download to URL is wrong, I guess was correct in past, but nowadays the correct way is adding /download. The generated URL is wrong and when you visit that link says "The shared file doesn't exists", so now is useless that option.

**Comment by Jaex** [comment]
Toggle this option: ![](https://jaex.getsharex.com/2017/12/ShareX_etddPDOVdt.png)

**Comment by alberizo** [comment]
I tried the ownCloud 8.1+ compatibility and works OK. 
I don't know why are in two separated options but maybe compatibility should be checked by default if you check previous checkbox.
Thanks!

**Comment by Jaex** [comment]
Because majority of people was using previous versions when that option added and that would break their links.
