### ISSUE TITLE
[Suggestion] Ability to add image effect presets to browser addon

### ISSUE THREAD

**Issue by Maveee** [ShareX/ShareX#3006]
Why? Sometimes you want to resize images, but not always. For instance I post a lot of images on my forum that I want with a width of 1000px max (comics for example) and 1920px width (wallpapers for example)
Talking about something like this:

![sharex](https://user-images.githubusercontent.com/8791604/34029767-745586de-e16a-11e7-86e3-340be8988173.jpg)

**Comment by vatterspun** [comment]
I certainly wouldn't want that as a default to avoid cluttering my right-click menu but I could definitely see some custom upload items streamlining my workflow.  

Also kudos on building even a basic mockup graphic like that.  It's so rare to see that on Github and really helpful to explain your idea.
