### ISSUE TITLE
image diff tool

### ISSUE THREAD

**Issue by beppe9000** [ShareX/ShareX#3007]
Something [like this app](https://github.com/atdrago/negative) should be in the Tools menu of the taskbar icon. See https://github.com/atdrago/negative/issues/163 too.

**Comment by vatterspun** [comment]
That seems a little out of scope for an image capture / image uploader program, but I'll admit @Jaex has added in some features that I didn't think he would.

**Comment by beppe9000** [comment]
Honestly many things in the Tools menu look out of scope, so why not this ? :D

**Comment by vatterspun** [comment]
Well it's a desktop productivity tool with tools for uploading, image and color management, and some file operations.  If picture comparison falls under one of those categories, I guess it's in scope but ... I guess it's a question of whether or not people are going to use it.  I mean, I thought QR codes were pointless a few years ago but they're still going strong.

As to why skip a given feature, this runs into territory I'm not 100% about.  My understanding is that there's such a thing as feature interference, where adding one feature can add unintended complexity to the code, slowing development and making testing more difficult.  Also as ShareX includes some amazing automation functions, meaning there's quite a bit of functionality under the hood.  Maintaining a simplified program operations can make issues with automation sequences easier to diagnose when they break.

**Comment by jasondavis** [comment]
I have been using this app since it was released many years ago and it is 1 of my top used apps.  

My dream update would be to convert the tools to a plugin system so that tools can be added/removed as well as the ability to easily add new tools

**Comment by vatterspun** [comment]
> I have been using this app since it was released many years ago and it is 1 of my top used apps.

Please feel free to support the program (if you're not already) via Patreon.

> My dream update would be to convert the tools to a plugin system so that tools can be added/removed as well as the ability to easily add new tools

As in the Firefox add-on system?  That might be something you want to create a separate issue for.
