### ISSUE TITLE
ShareX Image editor closing after clicking copy to clipboard.

### ISSUE THREAD

**Issue by Northmana** [ShareX/ShareX#3008]
Hye guys,

Every time I capture an image and open it in the editor if I click on copy to clipboard button, it just closes the editor. This wasn't the case in previous versions.

Please help :(

**Comment by DogeAmazed** [comment]
This was introduced with the commit a7b93af654ec3c9fc474bf7db5ae0ad34b7c5f0d on the 18. September last year.

I would call this also a bug because it's the same with saving. I dont want the program to close after saving.

**Comment by Jaex** [comment]
It is not bug. I thought most people want it to close automatically.

**Comment by Jaex** [comment]
I will add optional setting for it.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/12/ShareX_uN6gtlt23b.png)

**Comment by melvinev** [comment]
Hi - where can I find the setting for this in the menus?

**Comment by Jaex** [comment]
Not released yet.

**Comment by melvinev** [comment]
Okay, thanks. What version # introduced this auto-close change?  I want to revert back cause it's driving me nuts :)

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds

**Comment by vatterspun** [comment]
> I'm adding optional setting for it.

To be clear I greatly disliked that feature originally and now I wouldn't want it any other way.  As such I'd suggest keeping the current default.  Still I can see some reasons not to have that function so thanks for making it optional.

**Comment by abdqeb** [comment]
Btw, love this feature.

**Comment by Promikes** [comment]
i need this feature after cleanshot... i cant use software without auto-closing, and i cant find setting youve shown anywhere... where is it?
