### ISSUE TITLE
Resize images before uploading to imgur?

### ISSUE THREAD

**Issue by Maveee** [ShareX/ShareX#3012]
All images I upload and save with ShareX are done through the browser extension: I right lick and select "Upload with ShareX".
So I want every image I upload through this method to imgur, to be resized to 1920px width. (not only locally, but also **before uploading to imgur**)
I created this effect, but I have no idea how to automatically do this for browser uploads...
Can anyone help?

**Comment by vatterspun** [comment]
Is this a dupe of your #3006 issue?
