### ISSUE TITLE
12.0.0 has issues with [mapped network drive letters.] Plus,11.9.11 nags to update

### ISSUE THREAD

**Issue by TaranVH** [ShareX/ShareX#3017]
Windows 10.
I wish I could remember exactly what, but it made ShareX so unusable, I had to revert back to 11.9.1

This would be all well and good, but now EVERY time I have to reboot my computer, I get a nagging pop-up:
_A newer version of ShareX is available.
Would you like to download and install it?_

My only option here is "_Do not prompt again until ShareX starts next time._"

What I need, is  "_Do not prompt again for this version (12.0.0)_"

Does such an option exist? Is there ANY way to murder that pop-up forever?

**Comment by Jaex** [comment]
Instead of trying to fix issue in latest version you asking how to stay in old version. I didn't understood your issue in latest version too.

**Comment by TaranVH** [comment]
Okay, I'll install 12.0.0 again just to check.
Ah, now I remember. It can't handle letter-assigned networked drives.
I get an error anytime I try to save a file onto our server:
<img width="925" alt="sharex broken" src="https://user-images.githubusercontent.com/16040799/34134410-481433de-e40f-11e7-8fcc-64af98895105.PNG">

As you can see, the drive letters are mapped, but ShareX 12.0.0 cannot see them.
<img width="1080" alt="sahrex 2" src="https://user-images.githubusercontent.com/16040799/34134414-4b6d6bae-e40f-11e7-911c-2c4660ad11c5.PNG">

----

So yes, I have to stay on 11.9.11 until this is fixed, since it makes my work impossible to do. Having that nag pop up every time I restart my computer is pretty annoying.

**Comment by Jaex** [comment]
That file dialog belongs to Microsoft and nothing to do with ShareX. And there was no changes related to file dialog codes. Only difference I can think of you can have is that right after you install new version ShareX is run as admin.

**Comment by TaranVH** [comment]
The "Choose a folder to save ..." dialog box was spawned from ShareX. It's a part of the program. I have ShareX set up to prompt me for a save location after I take a screenshot.

I closed the program, and re-opened it as administrator. Still, ShareX 12.0.0 can not access any network locations, when I attempt to save.

ShareX 11.9.11 was able to do this with no issues. Something has changed. Can you, or someone, please look into it?

**Comment by Jaex** [comment]
Open ShareX 12.0 normally without admin.

**Comment by TaranVH** [comment]
That's weird. Manually opening the program, deliberately NOT as admin, resolves my issue. ShareX can now access those networked drive letter locations.

So, ShareX only opens itself as admin, immediately after you install it? That's not too bad. I'll check that the next time I reboot.

It would still be nice to get the
_"Do not prompt again for this version"_
check box option, just in case other weird problems arise in the future, and people want to stay on an older version.

**Comment by Jaex** [comment]
Because setup requires admin access to copy files to program files, it also runs ShareX as admin unintentionally.

There is already a way to disable updates, but intentionally I didn't told it so you can solve your problem in latest release and not require it.
