### ISSUE TITLE
Arrow key issue in Task Settings

### ISSUE THREAD

**Issue by SC2Mitch** [ShareX/ShareX#3018]
I'm having a issue with the arrow keys in the task settings, when I try and use the up arrow in the uploading tabs, it doesn't continue up, it just continues to refresh the upload tab. Gif provides better clarity. 
https://gfycat.com/ColorfulUnsungDeinonychus

**Comment by Jaex** [comment]
That happens because when Upload is selected it automatically moves selection to bottom because Upload don't have any content in it. So it can be difficult to fix.
