### ISSUE TITLE
[Share 12.0] How to save images that I copied on the clipboard and pasted on ShareX locally instead of auto uploading them?

### ISSUE THREAD

**Issue by alexllg** [ShareX/ShareX#3019]

**Comment by vatterspun** [comment]
That should happen with the following settings:

![image](https://user-images.githubusercontent.com/1289134/34286142-6795a214-e6a4-11e7-8821-e7c854b29781.png)

**Comment by regs01** [comment]
I have same issue. It used to be saving pasted images on the disk. But now there is only Upload and Cancel buttons. Upload is uploading image.
