### ISSUE TITLE
[Feature request] Add an option to forbid uploading

### ISSUE THREAD

**Issue by drehren** [ShareX/ShareX#3020]
Hi! Today I happen to accidentally press an upload button in the editor, and thought that it wouldn’t upload because I was certain I had set that I didn’t want any upload...

Of course the image was uploaded and it was very frustrating because that image should have never been uploaded in the first place. Had to find how to delete it and the spanish translation didn’t help. Also it didn’t help that a new entry was created in the history.

So is it possible to add an option to at least ask for user confirmation before uploading an image?

I would like an option to disable all kind of uploading feature.. but that would mean to change the application name from ShareX to X.

Thanks

**Comment by Jaex** [comment]
You can disable all uploading like this:

![](https://jaex.getsharex.com/2017/12/ShareX_eV9NSUH1HH.png)

**Comment by drehren** [comment]
Hey thanks! Was looking at the advanced settings but didn’t found that option. 
Anyway I have to say it worked, in the sense that it didn’t upload the image anymore, but it creates duplicate entries in the history. 
Also the button in the image editor creates different entries.

Thanks!

**Comment by Jaex** [comment]
Don't press upload button if you don't want it to create duplicate entries.
