### ISSUE TITLE
Watch Folder - Upload file when it changes

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#3024]
I love the Watch Folder feature for uploading settings and data files from my other programs like Notebooks app BoostNote and config files for other dev software.

It says it will upload new file in the irectory.

Is it possibble to also upload existing files once they are updated/changed?  Perhaps when the timestamp or file size changes it could re-upload a file that was already uploaded previously so that the files I use will be backed up to the server when I update them?

Thanks

**Comment by Jaex** [comment]
Currently I'm using file created event, if I use file changed event then it can probably trigger a lot while file is being written and can be difficult to handle it.

**Comment by jasondavis** [comment]
Ok another idea to solve my issue:

If I run a process/app on my PC to zip/archive my backup files on a regular basis and automatically save the files to a folder that ShareX is watching.  Before saving the file to the ShareX watched folder it will delete the existing file with the same name and then same the new copy which triggers ShareX to upload the new version over the old one on the remote server
