### ISSUE TITLE
slice split long images from windows with scroll

### ISSUE THREAD

**Issue by godlatro** [ShareX/ShareX#3026]
ShareX best free screenshot utility. Thank you
But FastStone Capture still best ever screnshot utility

In FSCapture we have tool that can easy crop image after capture in editor, and then it can PRINT long scrolled images and slice it to pages. Thats amaizing!
If you can please add analog function, who can print and split big and long images into pages.
Or capture and split to A4 if image long, if choose this function

**Comment by vatterspun** [comment]
So the steps here are: 

1. Do a scrolling capture
2. Split the scrolling capture into separate images that are auto-sized to a given printer width (in your case A4)
3. Print

Correct?

I don't know what you mean by "analog function"

**Possible workaround:** 

1. Paste the scrolling capture image into LibreOffice Draw on multiple pages. 
2. Rotate the page setup to the arrangement you want
3. Move the image to different locations on the screen

I had to do a bit of cropping to make this work, but I've had good luck with LibreOffice Draw.

![image](https://user-images.githubusercontent.com/1289134/34463970-5e47e136-ee33-11e7-99d9-96d80295a336.png)

**Comment by godlatro** [comment]
"analog" - I mean "similar"
By default I just create html file with code <img src="my-img.png"> and add some style for body, and then I print this file in Chrome PDF.
This method work in most case
