### ISSUE TITLE
Can't upload to imgur.

### ISSUE THREAD

**Issue by Its-Patchi** [ShareX/ShareX#3027]
I already tried changing my email, and uploading to imgur straight works.

```Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

**Comment by Jaex** [comment]
I can't upload from web site too:

![](https://jaex.getsharex.com/2017/12/chrome_UaW79Uhc54.png)

It is Imgur problem.

**Comment by c933103** [comment]
Reply from imgur:


I apologize for this hassle and inconvenience. This morning we were made aware of uploads failing for many Imgurians across all platforms: iOS, Android, Desktop. Unfortunately, while we work on this issue, your dank memes will have to wait to be shared with the community.
Our team is working hard on finding the cause and solution as soon as possible; we apologize for the inconvenience.
Updates can be found here: http://status.imgur.com/
We hope this adorable cat tax will help in for the time being: https://imgur.com/gallery/FvBkSjr
I will update you as soon as possible with any information I get. Feel free to reply back if you have any questions, comments or concerns.

**Comment by TWSSYesterday** [comment]
Thanks @Jaex
