### ISSUE TITLE
Imgur login 400 bad request.

### ISSUE THREAD

**Issue by c933103** [ShareX/ShareX#3030]
I tried to authorize my imgur account but it say failed, so I try to manually reauthorize it, and then I get directed to [https://api.imgur.com/oauth2/authorize?client_id=(a alphanumeric string)&response_type=pin] and then I get 400 bad request as a result

**Comment by Jaex** [comment]
Duplicate of #3027

**Comment by c933103** [comment]
3027 is upload, this is login, although it is the same error 400 and likely imgur's problem
