### ISSUE TITLE
System.Net.Sockets.SocketException(0x80004005)

### ISSUE THREAD

**Issue by IzumiEguchi** [ShareX/ShareX#3033]
I am trying to set up my VPS as the upload destination for images, but I am getting this error when I capture a screenshot.
http://i66.tinypic.com/2nuta52.png

This is what I'm getting in the Destination settings.
http://i64.tinypic.com/2v3rii0.png

**Comment by v0l** [comment]
What are your destination settings?

**Comment by Kyousei** [comment]
Here. https://i.imgur.com/2qpNaIl.png
