### ISSUE TITLE
Le serveur distant a retourné une erreur : (400) Demande incorrecte.

### ISSUE THREAD

**Issue by D0cH0use** [ShareX/ShareX#3035]
Message:

Request URL:
https://api.imgur.com/3/image

Stack trace:
   à System.Net.HttpWebRequest.GetResponse()
   à ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by sh1ny** [comment]
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Just so i can confirm it's happening also, English version :P

**Comment by SC2Mitch** [comment]
#3027 retoast, Imgur replied with a statement on the problem:
ENG:
I apologize for this hassle and inconvenience. This morning we were made aware of uploads failing for many Imgurians across all platforms: iOS, Android, Desktop. Unfortunately, while we work on this issue, your dank memes will have to wait to be shared with the community.
Our team is working hard on finding the cause and solution as soon as possible; we apologize for the inconvenience.

FR:
Je m'excuse pour cette dispute et inconvénient. Ce matin nous avons été mis au courant de l'échec des uploads pour beaucoup d'Imgurians sur toutes les plateformes: iOS, Android, Desktop. Malheureusement, pendant que nous travaillons sur ce problème, vos memes devront attendre d'être partagés avec la communauté.
Notre équipe travaille dur pour trouver la cause et la solution dès que possible; Nous nous excusons pour le dérangement.

**Comment by Jaex** [comment]
Duplicate of #3027
