### ISSUE TITLE
Feature Request: sandbox,canvas for screenshot creating

### ISSUE THREAD

**Issue by szegi** [ShareX/ShareX#3039]
I dont know if something like this exists in sharex

i would like to have an option to build my screenshot from pieces

when i click Capture->Region
i have many options above
like Drawing image(screen) (file)
that i can use to put some images to the screenshot
but this freezes whole screen
and sometimes i would like to use it like an editor
that i could start with empty canvas
and then using this tools create bigger screenshot
but instead of frezeed screen i can click something and
add another screen after a while

option like this have this app: monosnap
but it is not developped as fast as ShareX and is missing
many of ShareX tools and options

screen record of how it looks in monosnap
![test](https://user-images.githubusercontent.com/12111506/34458034-0d3e0f00-edc4-11e7-8e25-377cc8c0c955.gif)

of course it is just an suggestion:)

**Comment by szegi** [comment]
@Jaex thanks for response in my previous ticket
i see that using ShareX image editor i could achieve similar feature

but it has some issues:/

- first i have to start doing screenshot to open the editor
or run editor first but then i cant easily control my flow like after capture,upload tasks

- in ShareX image editor i cant add screenshot using Drawing image(screen) (file) because it uses only part of image from editor window
so i have to copy part of the screen and then paste it to editor using another tools

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/12/chrome_o6lGIeGg1f.png)

I'm gonna add "Insert image from screen" button under this.

**Comment by Jaex** [comment]
You can test it if you want using dev build: https://getsharex.com/docs/dev-builds

**Comment by Jaex** [comment]
Also added this dialog for auto canvas resizing when inserting image:

![](https://jaex.getsharex.com/2018/04/ShareX_y37Ge3vIF6.png)
