### ISSUE TITLE
Feature Request: ShareX image editor allow to select elements of different types

### ISSUE THREAD

**Issue by szegi** [ShareX/ShareX#3044]
I started using ShareX image editor
and one annoying thing is
that if i want to move things around
i have to select proper tool from menu
it would great if i could select just normal cursor
and changing properties of existing objects
without switching between tools

of course as always only suggestion:)
thanks for great software

**Comment by vatterspun** [comment]
Yeah I've been frustrated by ShareX not functioning like other graphics editors, but a few of the tools have solved issues in a fairly interesting/creative way so I'm curious where the team goes with it next.

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/issues/3769#issuecomment-482924421
