### ISSUE TITLE
Bug: Screen recording on multi monitors

### ISSUE THREAD

**Issue by mcka-dev** [ShareX/ShareX#3055]
I found a bug when capturing the desktop.

My configuration:
Version ShareX: 12.0
OS: Windows 10 64 bits
Monitor1: 1600x1200 (scaling: 100%)
Monitor2: 1920x1080 (scaling: 150%)
![project-menu](https://user-images.githubusercontent.com/16173503/34553741-3f5c1fb2-f13a-11e7-8b17-f5acf122d004.png)

My steps in ShareX:
Capture ->  Screen recording (Capture the entire desktop)

Result:
![sharex_2018-01-04_11-13-32](https://user-images.githubusercontent.com/16173503/34554957-68522b04-f140-11e7-8b66-403ec667fb70.png)

P.S. At the same time capturing any window works fine! The only problem with the capture of the desktop.

**Comment by paulvi** [comment]
That is issue of ffmpeg, and would be enhancement here.
Issue should be raised for ffmpeg and linked here.

**Comment by paulvi** [comment]
Why to close? This was not closed.

**Comment by mcka-dev** [comment]
Works in version 13.1
thanks!

**Comment by mcka-dev** [comment]
In the latest version 13.1, no recording is performed(((
