### ISSUE TITLE
I can't record on fullscreen while audio recording is enabled

### ISSUE THREAD

**Issue by LOuroboros** [ShareX/ShareX#3056]
So, I've been having this issue for a long, long time now and I really wanna know how to fix it, so I finally decided to come over here and try to ask a solution for it.

Straight to the point, I can't record my full desktop while audio recording is enabled, otherwise, ffmpeg crashes after 1 minute or so. I noticed that, in some cases, it works just fine though.
For example:
*If I disable audio recording, it works just fine.
*At certain resolutions like 730x532, it works just fine even if I have audio recording enabled.

This is the configuration that I use with ShareX:
Screen Recorder: https://i.imgur.com/C0FYhcW.png
Screen Recorder Options: https://i.imgur.com/UPO4ax6.png

I tried all the video codecs available except for the NVENC ones (_those are for the NVIDIA GPUs, right?_) and the Animated GIF codec.
Here's a picture of the crash with each of them:
-x264: https://i.imgur.com/Q6Ozl4A.png
-VP8: https://i.imgur.com/KvqJaBd.png
-Xvid: https://i.imgur.com/U5ZgKrB.png
-x265: https://i.imgur.com/omDQk8z.png
Maybe the full log would be more helpful..?
If so, please let me know and I'll put them in a Pastebin right away.

Worth adding, I'm using Windows 8.1 x64 and I have the latest version of ShareX (_Portable_).
I re-installed the ffmpeg version that it allows you to download too and I also re-installed the recording devices using the built-in option.

**Comment by LOuroboros** [comment]
So, is this getting fixed anytime soon or.,..?

**Comment by Jaex** [comment]
If you installed latest FFmpeg and reinstalled recorder devices from latest ShareX version and if problem still continues, there is nothing we can do about it. Because it is not to do with ShareX.

**Comment by LOuroboros** [comment]
Alright, so I downloaded the latest build of ffmpeg, dropped ffmpeg.exe inside \ShareX\ShareX\Tools and it looks like recording the full desktop while audio is enabled does work correctly now.
Thanks for suggesting it, @Jaex :)
