### ISSUE TITLE
Open with Microsoft Store ShareX

### ISSUE THREAD

**Issue by seongliyn** [ShareX/ShareX#3058]
How can I open an image file in ShareX image editor?

**Comment by vatterspun** [comment]
![image](https://user-images.githubusercontent.com/1289134/34647067-6e996316-f33d-11e7-8ffd-38940492f477.png)

**Comment by seongliyn** [comment]
What I mean is can I right click an image file, then select Open With?

**Comment by vatterspun** [comment]
Oh okay so Feature Request: Image edit via the context menu.

Are you asking to edit images from anywhere or edit images from within the ShareX app?

**Comment by seongliyn** [comment]
Ya, image edit via context menu. Some times I have an image that are not screenshot using ShareX, but I would like to annotate it using ShareX image editor because it is so user friendly.

**Comment by vatterspun** [comment]
> I would like to annotate it using ShareX image editor because it is so user friendly.

I remember seeing a few posts complaining that the editor sucked, but the editor's definitely come a long way.  I guess if nothing else a feature request for a context menu item is a pretty big endorsement for it's quality.

**Comment by seongliyn** [comment]
I personally think that the image editor is simple enough for image annotation. Image edit via the context menu will definitely save my time.
