### ISSUE TITLE
Feature Request: Add one-time.nl as Image Hosting Service

### ISSUE THREAD

**Issue by e58** [ShareX/ShareX#3059]
Might be useful for some users who want to share images for one-time viewing only..

https://one-time.nl

**What is this site?**
_This is a disposable encrypted image hosting. When you upload an image, your browser generates a random password, encrypts image with this passwords and sends ciphertext to the server. Password stored in the link to the image after '#' symbol, and it never leaves your computer, if you aren't sharing a link with somebody, of course._
_When you open the link the process is inverted: you download the ciphertext from server, decrypt it with password extracted from the link and see a picture. Take a good look (or save it), because it's already deleted from the server!_

**Comment by trollmad3** [comment]
I would actually love this because as of `6/2/2018` there is **NO** one-time view image destinations.

**Comment by stuntguy3000** [comment]
> _This is a disposable encrypted image hosting. When you upload an image, your browser generates a random password, encrypts image with this passwords and sends ciphertext to the server. Password stored in the link to the image after '#' symbol, and it never leaves your computer, if you aren't sharing a link with somebody, of course.
> When you open the link the process is inverted: you download the ciphertext from server, decrypt it with password extracted from the link and see a picture. Take a good look (or save it), because it's already deleted from the server!

This looks like something outside the scope of ShareX to implement.

**Comment by trollmad3** [comment]
@stuntguy3000 If we can have Onetimesecret then we can add this. I don't see anything wrong with this.
