### ISSUE TITLE
Main Menu Arrow

### ISSUE THREAD

**Issue by Fyers** [ShareX/ShareX#3061]
Is the MainMenu Arrow on purpose pointing down?
My menu, and as far as I know, it always pop ups right.

Now:
![grafik](https://i.imgur.com/XSL45b7.png)

Should be?
![grafik](https://i.imgur.com/wElWZYD.png)

If it should point to the right I could make a PR.

**Comment by Jaex** [comment]
Is it really gonna worth the effort to customize default UI behavior of Windows control? Because how it draws can change depending on Windows OS version. So it can be bad idea to override and draw your own arrows.

**Comment by Fyers** [comment]
you could just set the direction of the arrow to right, and let windows draw it as it would, but with the other direction.

**Comment by Jaex** [comment]
I can't find arrow direction option, are you sure such option exists?

**Comment by Fyers** [comment]
I ment Overriding the OnRenderArrow() in the ToolStripRenderer and setting ToolStripArrowRenderEventArgs Direction to right.
