### ISSUE TITLE
where do I suggest translations?

### ISSUE THREAD

**Issue by ichbineinNerd** [ShareX/ShareX#3067]
I'm too lazy to look through all the projects.

//edit: I dont want "Pull requests" as an answer, but "in folderXY/translations/the.langfiles", for example. thanks for your time

**Comment by Fyers** [comment]
Well as far as I understand you would like to add some translations...?

There is a documentation on how you can [add/upadte translations]( https://getsharex.com/docs/translation)

The translations are in the *.resx files (For example: "ShareX.HelpersLib/Properties/Resources.de.resx") but editing them is described in the documentation linked above.

**Comment by ichbineinNerd** [comment]
ok, thanks
