### ISSUE TITLE
Black screen when takeing capture

### ISSUE THREAD

**Issue by trollmad3** [ShareX/ShareX#3071]
When I take a screen shot this happens: 
![image](https://user-images.githubusercontent.com/7843719/34751007-c34dbcb6-f56f-11e7-8682-3ff517c42412.png)

I have no idea how to fix this.

**Comment by Jaex** [comment]
You must be taking screenshot from game which is not possible to capture with ShareX unless it is borderless windowed.

**Comment by trollmad3** [comment]
Fixed it.

**Comment by BrinkOfGlory** [comment]
How'd you fix it my man? (Sorry for necro)
