### ISSUE TITLE
I always get the mouse pointer in the captured image (the part that is within the captured rectangle)

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#3072]
In the **Task Settings > Capture** menu, the **Show cursor in screenshots** checkbox is unselected.
Even then I always get the mouse pointer in the captured image. This spoils the screenshot

I have found the pattern: Depending on how I draw the lasso (marqee) rectangle (i.e., the direction), it captures the mouse pointer partly or fully.

To be precise, at the instant I release the left mouse button, whatever part of the mouse pointer lies within the marqee rectangle gets captured.

See the following examples:

If I draw the lasso (marqee) from right-bottom corner to left-top corner, I get a full mouse pointer:
![image](https://user-images.githubusercontent.com/9047168/34810098-596c0342-f6bf-11e7-807e-c5ed6fd0a815.png)

If I draw the lasso (marqee) from left-top corner to right-bottom corner, I get only a black dot (look at the bottom-right corner of the image), which is actually the tip of the the mouse pointer (left-pointed arrow):
![image](https://user-images.githubusercontent.com/9047168/34810251-1c82eeea-f6c0-11e7-8d96-0a73ee058e10.png)
(Note that if the mouse pointer is different shape, a larger part of it gets captured, which is much more noticeable.)

If I draw the lasso (marqee) from right-top corner to left-bottom corner, I again get a part of the mouse pointer, which looks like "T" (look at the bottom-left corner of the image):

![image](https://user-images.githubusercontent.com/9047168/34810567-3ec2e2b0-f6c2-11e7-9954-223e41e926aa.png)

Reporting for Win 10 32 bit. I have same behavior on another PC with Win 10 64 bit also.

**Comment by Jaex** [comment]
I'm unable to reproduce your issue:

![](https://jaex.getsharex.com/2018/01/chrome_tybiifjHV4.png)

**Comment by raindropsfromsky** [comment]
Attaching two samples:

In the following, the mouse pointer looks like a double-lined cross-hair.
![image](https://user-images.githubusercontent.com/9047168/34813253-3efc7478-f6cf-11e7-803d-291cae9b1c70.png)

In this screenshot, the mouse pointer looks like a palm with pointing finger.
![image](https://user-images.githubusercontent.com/9047168/34813277-5b2c9f6a-f6cf-11e7-9638-b70eae8e65f5.png)

In both cases, I pressed **PrntScrn** button (which is set to capture a region.)
Then I drew the rectangle from right-bottom corner to left-top corner. (This is important).

**Comment by Jaex** [comment]
Yes I draw it from right bottom corner to left top corner yet it didn't add cursor.

**Comment by raindropsfromsky** [comment]
Is this possible because of some corruption in registry etc?
How can I re-install a plain vanilla version of Sharex once again?

**Comment by raindropsfromsky** [comment]
I tried to uninstall and re-install but that did not work.
Possibly some settings remain in user-settings, which I may have to delete.

**Comment by raindropsfromsky** [comment]
I restarted the PC several times also, but that has no effect.

**Comment by raindropsfromsky** [comment]
I tried twice, and got mixed results:

Pointer is not captured at all:
![image](https://user-images.githubusercontent.com/9047168/34813614-a685f366-f6d0-11e7-8afa-a588947d299f.png)

Pointer captured
![image](https://user-images.githubusercontent.com/9047168/34813628-b1aaa0e8-f6d0-11e7-84ba-b8a25877486b.png)

**Comment by raindropsfromsky** [comment]
Nope! I tried that once again, and it captures the pointer!
![image](https://user-images.githubusercontent.com/9047168/34813711-03d8ef00-f6d1-11e7-8dce-c047f06ed862.png)

**Comment by raindropsfromsky** [comment]
I found another pattern:

While releasing the LMB, if I move the mouse away from the selection marqee, then the pointer does not get captured. If I do not move the mouse, then the pointer gets captured.

![image](https://user-images.githubusercontent.com/9047168/34813784-47483eee-f6d1-11e7-9a56-2cd48e77119c.png)
![image](https://user-images.githubusercontent.com/9047168/34813797-538f0930-f6d1-11e7-9249-a5bbd478c3d1.png)
![image](https://user-images.githubusercontent.com/9047168/34813808-5ef2181c-f6d1-11e7-9ea7-57cac1f8d894.png)
