### ISSUE TITLE
Question: how to change UI language to English, e.g. on Chinese Windows?

### ISSUE THREAD

**Issue by paulvi** [ShareX/ShareX#3076]
how to change UI language to English, e.g. on Chinese Windows?

![image](https://user-images.githubusercontent.com/1614482/34934777-ba252a42-fa16-11e7-8461-88f1ce5e05d0.png)

**Comment by Fyers** [comment]
![2018-01-15_11-55-02](https://user-images.githubusercontent.com/26491227/34939137-05b775fe-f9eb-11e7-90ea-f65b28986bb3.png)

**Comment by paulvi** [comment]
Thanks. see #3077
