### ISSUE TITLE
Requested feature: Repeat fixed size screen capture and store as images

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#3079]
I am making a user manual for a software, for which I need to capture the screenshots of all toolbar buttons of that software.

Can we have the following feature (the full scenario is developed below):

1. The user selects the button size in pixels from a pull-down menu 
  (16x16, 32x32, 48x48, ... and a free size (user-defined).

2. The user defines the hotkey for this capture.

3. When the user presses the hotkey, Sharex creates a dotted square of the desired size. </br>This dotted square is attached to the mouse pointer; and moves with the mouse. </br>It can also be nudged with the arrow keys. </br>A magnifier window moves with the capture square, so that the can align the region perfectly. </br>There is no need for a screen-wide cross-hair in this mode.
  
4. When the user presses the left mouse button, Sharex captures the region, and stores it as image. </br> The user should be able to select the file format, and compression (0-90%). </br> The user should be able to specify the saving location.</br> The user should be able to specify the file-naming format </br> (typically, a prefix and then a running number, date+time stamp, etc.).

**Comment by Jaex** [comment]
Fixed mode already exists:

![](https://jaex.getsharex.com/2018/01/ShareX_0pC9GKOu7W.png)

**Comment by raindropsfromsky** [comment]
Hi

I am unable to see this menu bar. I tried all the options, but not getting
it.
Could you please let me know where this toolbar is available?

Thanks in advance

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Jaex** [comment]
In region capture.

**Comment by raindropsfromsky** [comment]
Thanks!

But in all fairness, I did not expect to change the settings after I launch the capture command!
(All apps have settings before launch the capture command. Even Sharex follows the same trend for all other settings.)

**Comment by Jaex** [comment]
It is already possible to change it before open capture.
