### ISSUE TITLE
Exclusively for Windows?

### ISSUE THREAD

**Issue by hartwork** [ShareX/ShareX#3081]
Hi!

Does ShareX  support platforms other than Windows? My vote for mentioning supported platforms in the  GitHub repository description at the very top. Thank you!

**Comment by Jaex** [comment]
https://getsharex.com/docs/faq

**Comment by hartwork** [comment]
So how about
```
--- ShareX is a free and open source program
+++ ShareX is a free and open source program for Windows
```
?

**Comment by vatterspun** [comment]
> My vote for mentioning supported platforms in the GitHub repository description at the very top. 

This comes up a lot so you're certainly not alone, but my understanding is doing so would be especially difficult.  But hey that's the beauty of open source: maybe you could hire someone or do some kind of feature bounty to encourage development outside Windows.  *shrug*
