### ISSUE TITLE
Simple video edit feature to trim the video after editing

### ISSUE THREAD

**Issue by PESER** [ShareX/ShareX#3082]
That would make it a lot easier to record your screen and then cut the bits you don't want. Even just cutting either from the start and an end. Doesn't have to edit few points at once.

**Comment by Jaex** [comment]
Duplicate of #2278

**Comment by mark325hr** [comment]
srhre[h](fiverr)

**Comment by mark325hr** [comment]
<a href="https://www.w3schools.com">Visit W3Schools.com!</a>
