### ISSUE TITLE
Feature Request: Universal Block of Uploading

### ISSUE THREAD

**Issue by jlpoolen** [ShareX/ShareX#3083]
I realize this project is all about easily getting photos to some server so they may be shared.  You have an impressive product in the area of screen capture and editing thereafter.

For businesses, having software installed for the employees that makes it so easy to upload to public server could be a nightmare.  Having a setting which disables all upload ability could be an incentive for companies to consider using your product and not have confidential material inadvertently posted on some public web site.

I spent some time trying to find if there was a configuration setting that completely disabled uploading capability and could not find such a setting.  If there is one, could some please advise?

Otherwise, have a setting such as "Disable all uploading ability" with a 1/0 or true/false setting could be an attractive feature.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2018/01/ShareX_JNoqeovPZR.png)

**Comment by jlpoolen** [comment]
Thank you, I must not have scrolled down to the very end to see the setting.
