### ISSUE TITLE
Capture specific window command line

### ISSUE THREAD

**Issue by ben-swain** [ShareX/ShareX#3086]
Is there a command I can use to capture an image from a specific window? Essentially I need to use the feature shown below in command line.

![image](https://user-images.githubusercontent.com/19712540/35199284-daddb218-fec1-11e7-89c5-27c6767acb1e.png)

**Comment by Jaex** [comment]
No.

**Comment by ben-swain** [comment]
Alternatively, is there a way I can set up a repeating capture of a specific window from the menus (not from command line)?

**Comment by Jaex** [comment]
Capture last region hotkey?

**Comment by ben-swain** [comment]
I need to capture a window even if it is behind another window. Does last region hotkey do this?

**Comment by Jaex** [comment]
Even window hotkey not do it, its moving window to front.

**Comment by vatterspun** [comment]
> Is there a command I can use to capture an image from a specific window?

MiniCap (not open source) has this functionality via the _$windowtitle$_ argument.
