### ISSUE TITLE
Upload Errors

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#3087]
Message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://picasaweb.google.com/data/feed/api/user/default/albumid/default

Response:
Internal error, try again later

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

**Comment by MrCD1968** [comment]
I show that I am logged in.

**Comment by NovusTheory** [comment]
This is a 500+ error. This has nothing to do with ShareX. Blame the server

**Comment by CMS12345** [comment]
How weird happened exactly the same time last year 📦 

https://github.com/ShareX/ShareX/issues/2218

**Comment by Jaex** [comment]
Your linked issue is not even Google Photos.

**Comment by CMS12345** [comment]
I'm aware, wasn't clear with what I said.

But the same type of issue :)

**Comment by thedanioner** [comment]
I also have the same error, any solution?

**Comment by Jaex** [comment]
Looks like Google fixed the issue.

**Comment by MrTakedi** [comment]
Google is deprecating the Picasa Web API.

[Picasa Web Albums Data API](https://developers.google.com/picasa-web/)
