### ISSUE TITLE
Add Contextual Windows Shortcuts

### ISSUE THREAD

**Issue by Dreadaxe** [ShareX/ShareX#3089]
Example
![2018-01-23_14-39-35](https://user-images.githubusercontent.com/13752505/35279348-2c4b8c92-004d-11e8-9253-650fd6380ea5.png)

**Comment by JeremyShih** [comment]
If you select a picture and click "upload with ShareX", ShareX will upload the pic to imgur or other site and give you the link. Similar works will be done when you select files.
So...I am wondering what functions do you need exactly.

**Comment by Dreadaxe** [comment]
The function can be view to the image scratch

--
Benoît

On January 29, 2018 at 9:28 GMT, Jeremy Shih <notifications@github.com> wrote:

If you select a picture and click "upload with ShareX", ShareX will upload the pic to imgur or other site and give you the link. Similar works will be done when you select files.
So...I am wondering what functions do you need exactly.

**Comment by JeremyShih** [comment]
If QR code means providing a QR code to the upload link, I could try to deal with it.
As for other functions, if you could give an english version, I may be able to help.

**Comment by Dreadaxe** [comment]
Tools functions are the same that you can have with right click one ShareX icon.

**Comment by JeremyShih** [comment]
The functions you have with right click on ShareX icon could be done with "upload with ShareX" in contextual windows shortcuts with the type of files you selected.

**Comment by JeremyShih** [comment]
I got what you mean just now. I think I could help.
