### ISSUE TITLE
Google Photos and ShareX

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#3091]
A number of folks seem to no longer be able to upload to Google Photos from ShareX and while it may not be a ShareX issue it no longer works. Might be a good idea to just remove it from ShareX. It's not likely to be fixed any time soon.

**Comment by Jaex** [comment]
"It's not likely to be fixed any time soon." how you know that?

**Comment by IanMooreIsMe** [comment]
I've been having the same issue. First noticed it yesterday on 2018-01-22.
[Here's what my debug log says](https://gist.github.com/IanMooreIsMe/a93e9840c96baa364671a70fd6432361), in case that helps with... debugging.
I use the Empty no album upload, however I tested setting an album and this issue still occurs with a notification warning about a 500 error.

**Comment by SC2Mitch** [comment]
> It's likely not to be fixed any time soon
Thank you armchair developer, Leave it up to Google to resolve the problem. ShareX isn't at fault for Google's server problems.

**Comment by MrCD1968** [comment]
How do you know that Google Photos API did not change something and ShareX needs to be updated to accommodate that change (whatever that is)?

**Comment by Jaex** [comment]
https://developers.google.com/picasa-web/docs/3.0/releasenotes

**Comment by MrCD1968** [comment]
So do you gather from this that Google Photos will in fact no longer work thus ShareX will no longer have functionality as we have known it for uploading to Google Photos? If not, what is required than? A rework of ShareX or A workaround?

**Comment by Jaex** [comment]
#3087

**Comment by MrCD1968** [comment]
So surprised to report that this seems to be working again.

**Comment by RogerioDosSantos** [comment]
The issue is back. This time due to a deprecation of the Picasa API:
https://developers.google.com/picasa-web/

**Comment by sniff122** [comment]
> 
> 
> The issue is back. This time due to a deprecation of the Picasa API:
> https://developers.google.com/picasa-web/

:-( so annoying, was useful to have my screenshots access able on my mobile devices

**Comment by Mylezz** [comment]
I'm having the same issue

**Comment by tdchien** [comment]
I'm having the same issue too

**Comment by itsmeevg** [comment]
+1

**Comment by stjema** [comment]
+1

**Comment by pavan-p** [comment]
Any update? :o
