### ISSUE TITLE
Share can't put a copy in a dropbox folder anymore

### ISSUE THREAD

**Issue by consultantseo** [ShareX/ShareX#3097]
Hi, 

I'm getting this message when I take  screenshot: https://i.imgur.com/VbWWtmS.jpg

Until then, it was uploading the screenshot to imgur (which it still does properly) and it was also saving the file in a dropbox folder named IMAGES (which it can't do anymore, apparently). 

Does anyone have an idea about what's blocking ShareX from accessing this folder? I'm using BitDefender for several years and it's never caused any issue before.

Thanks in advance for your help.

Best regards, 
Florence.

**Comment by Jaex** [comment]
Bitdefender have protected folder feature which was blocking ShareX by default for other users.

**Comment by consultantseo** [comment]
Thank you very much, Jaex, I looked at this feature in BitDefender and added ShareX application in the exclusions, it fixed the issue.
