### ISSUE TITLE
Minimum size option

### ISSUE THREAD

**Issue by RadGH** [ShareX/ShareX#3098]
So I've had this issue several times and I'm sure even the developers have, where you go to take a full page screenshot but when you press the mouse button down you move the mouse ever so slightly. The full page screenshot becomes a tiny rectangle, like this screenshot you might not even see:

![chrome_2018-01-26_10-53-20](https://user-images.githubusercontent.com/2008464/35455549-23822986-0287-11e8-8fb7-6eab7cca33a4.png)

An easy fix is to make the minimum size for screenshots 10x10 and if you don't make it at least that big, it takes a full screenshot instead (or makes you try clicking again).

Just a thought, not sure of all the implications. There could be some people who want to take a 5x5 screenshot for some reason.

(I just sent an email with a screenshot of a spreadsheet I had open and didn't notice until it was too late, and wondered how that could have been avoided. Did not see the option in the settings, if it does already exist somewhere)

**Comment by Jaex** [comment]
There is actually minimum size exists which is 3x3: https://github.com/ShareX/ShareX/blob/master/ShareX.ScreenCaptureLib/Shapes/BaseShape.cs#L36

So you can't accidentally make small screenshots easily.

**Comment by RadGH** [comment]
As usual you thought of everything! That has probably caught a majority of mistaken screenshots, but as I get lazier with my mouse that deadzone would need to get bigger. Doesn't make sense to keep getting bigger. I think 3x3 is perfectly fine. Thanks!
