### ISSUE TITLE
Lambda file hosting changed url

### ISSUE THREAD

**Issue by Kaos1337** [ShareX/ShareX#3101]
Hi,
the default file uploader settings "Lambda" isn't working anymore, they have changed the url to: https://lbda.net

**Comment by Jaex** [comment]
Duplicate of #3100

**Comment by mstojcevich** [comment]
I have removed the domain redirect, so the existing URLs should at least work until I can write a better fix to update the config files that use the old domain (xn--wxa, which is no longer up)
