### ISSUE TITLE
Uploading .tar.gz file to S3 creates a .gz file

### ISSUE THREAD

**Issue by cascer1** [ShareX/ShareX#3104]
When I upload a `.tar.gz` archive to S3, the resulting upload url will be a simple `.gz` archive, which cannot be extracted without manually renaming it to .tar.gz first.

I would expect the original extensions to remain, so that I can upload and download the files without any issues.

**Comment by Jaex** [comment]
Are you using naming pattern which overrides your file name?

**Comment by cascer1** [comment]
@Jaex I am indeed using the name pattern

**Comment by Jaex** [comment]
Name pattern to be able to replace name removing extension part but because it can't know how many dots extension contains it also removes .tar section. And multiple dots not always means extension so it could be part of file name too.

**Comment by matthewburnett** [comment]
@cascer1 Alternatively you could opt for `.tgz`

**Comment by Jaex** [comment]
I couldn't find perfect way to handle two extension file names but at least handled .tar.gz case.
