### ISSUE TITLE
plz support gifski

### ISSUE THREAD

**Issue by onanana** [ShareX/ShareX#3105]
thx for developing sharex.

its very useful tool.

bcuz i cant speak english well.

so i'll simply ask a favor.

plz support gifski.

making gif, its quality is good.

thank you again.

**Comment by campbeb** [comment]
It seems that gifski is just a program and not an image hosting site. Is that correct?

If so, you can already do this with ShareX.
For your After capture task, select "Perform actions"
![actions](https://user-images.githubusercontent.com/1089399/35597982-fcea6cbe-05ee-11e8-9970-572cd13fd928.png)

Then go to Task Settings and select Actions. You can add new action that runs a .bat file which does your conversion and then uploads the file back to ShareX.

**Comment by sylveon** [comment]
The problem with that is that you have a .gif, convert it to frames for gifski to parse, and then have gifski convert it back to .gif. It's not really efficient, and you lose some of the good points of gifski. Considering gifski can take video files (when built with `--features=video`), it should be better to add it as gif encoder.
