### ISSUE TITLE
Can Screen Recording FPS be more than 60?

### ISSUE THREAD

**Issue by pharan** [ShareX/ShareX#3107]
I just realized that OBS (https://github.com/jp9000/obs-studio) supports screen or window recording at 120fps. And I tried it and it worked!

Is there something preventing ShareX from doing the same?

The "Screen Recording FPS" number field seems to be maxed at 60.

**Comment by pharan** [comment]
I guess this is the behavior on the form side. https://github.com/ShareX/ShareX/blob/master/ShareX/Forms/TaskSettingsForm.Designer.cs#L1466-L1486

**Comment by NovusTheory** [comment]
imo you shouldn't be trying to record something at 120 FPS with ShareX anyways. ShareX was mainly made for quick capturing + uploading and sharing

**Comment by Jaex** [comment]
ShareX (FFmpeg) doing real time encoding which slowing it a lot. So even there is 60 fps setting most of people gonna have frame drops.

**Comment by pharan** [comment]
@NovusTheory 
Well, yeah. I wanted to quickly capture 120fps recordings.

Frame drops or not, I was wondering if the UI wasn't unnecessarily and arbitrarily capping the number.
People should be able to use it if they have the machine to handle it, right?

I'm also not sure if ffmpeg can take enough advantage of hardware Nvidia NVENC (since it is an option under codecs) that this becomes much less of a problem, even for people with low-end Nvidia cards.

**Comment by NovusTheory** [comment]
You do have a point there. But unless you're recording gameplay, 120 FPS just doesn't seem necessary. Even then if that's the case, 60 FPS should still do fine
