### ISSUE TITLE
Esc button in edit mode closes the edit window

### ISSUE THREAD

**Issue by klyushin** [ShareX/ShareX#3116]
I know that the button executes the function it should but it is freaking me out when I was drawing some arrows and stuff for quite a long time and then I enter some text in a text window and press accidentally Esc twice and it closes all the process without asking yes/no ... It is so frustrating to start all over again... I would be very grateful to you if the esc button wouldn't close the edit window or at least it would ask for a confirmation. Thanks! 

windows 10 / sharex12.0

There's a gif attached showing the process recorded.
![sharex](https://user-images.githubusercontent.com/5040256/35754157-189b7a42-086b-11e8-9116-60202fa3c2cc.gif)

**Comment by Jaex** [comment]
I also find it frustrating when I press esc to close window and it asking me am I sure. Why would I press it if I were not sure and it slowing me down unnecessarily.

**Comment by klyushin** [comment]
Well maybe you're right and it's a matter of habit but it causes me so much trouble. Well anyway I've found a workaround - I've made a small script for AutoHotkey program and now it prevents ESC button in ShareX from closing any windows. It works on my windows 10.
maybe someone will find it helpful I've attached the script below:


`#IfWinActive, ahk_exe ShareX.exe
$ESC::return`


https://autohotkey.com/docs/Tutorial.htm
Thanks for your respond anyway! Have a good day!

**Comment by Jaex** [comment]
I added confirmation message box for editor close:

![](https://jaex.getsharex.com/2018/05/ShareX_yiFlqkJCuB.png)
