### ISSUE TITLE
ShareX saving recording saves locally even though I have it turned off

### ISSUE THREAD

**Issue by NoahBK** [ShareX/ShareX#3117]
Hello,

The issue that I am facing is where I take a screen recording of something and I have it set to auto upload the screen recording to gyfcat which is what I want. It also copies the url afterwards so I can post it to discord and things of that nature. But, it also saves the file locally to my screenshots folder which I don't want. Is there a way to get it to stop saving the recording locally?

Thanks.

**Comment by Jaex** [comment]
FFmpeg saves it to file.
This option can delete video after upload: https://jaex.getsharex.com/2018/02/chrome_UdQq6ymHZ2.png

**Comment by NoahBK** [comment]
Thank you very much for the information. Exactly what I was looking for.
