### ISSUE TITLE
Horizontal scrolling capture & inverted capture

### ISSUE THREAD

**Issue by beppe9000** [ShareX/ShareX#3124]
it would make the "scrolling capture" tool more powerful

**Comment by beppe9000** [comment]
...

**Comment by beppe9000** [comment]
l

**Comment by ryan-schubert** [comment]
Also looking for this feature...

**Comment by Av1dLearner** [comment]
me too

**Comment by frankzheng43** [comment]
me too

**Comment by gruponewage** [comment]
Please would help a lot!

**Comment by Jay-Tarzan** [comment]
Do do

**Comment by sweetins** [comment]
Its 2024... is this future ever getting implemented?

**Comment by wajika** [comment]
Agree

**Comment by megamorphg** [comment]
[Fresh request created](https://github.com/ShareX/ShareX/issues/8136) as it could be used in quite a few instances.
