### ISSUE TITLE
ShareX screen interfering GIF

### ISSUE THREAD

**Issue by meetdilip** [ShareX/ShareX#3127]
Looks like it is almost impossible not to capture ShareX window while trying to record a GIF. A small countdown timer to minimise the ShareX interface before recording GIF would be great. I mean, not to start recording instantly. There is a tool in Ubuntu called Peek. They give like 3-5 seconds window before the GIF recording starts. Thanks.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2018/02/ShareX_t0VgYfNj2E.png)
