### ISSUE TITLE
Small Icons in a large screen resolution

### ISSUE THREAD

**Issue by nidhalkratos** [ShareX/ShareX#3128]
I have an HP Envy 13 with a 2K resolution screen and the icons are very very small that it is hard to see them, I hope icons and text sizes would no longer be dependent on the actual number of pixels , but on the actual screen size.

**Comment by zlamma** [comment]
The icon size is annoying, but even more serious is the size of the 'step' circle, when I add it to the screenshot in the editor. Just compare it to the size of icons in github:

![image](https://user-images.githubusercontent.com/557753/36339993-a11731ae-13c9-11e8-88f1-d3fb4f93e019.png)


Please make its size dependent on the screen DPI, just like the 'speech baloon'.

**Comment by jiangzhenjerry** [comment]
I raised this issue two years ago
https://github.com/ShareX/ShareX/issues/1222

and someone even earlier:
https://github.com/ShareX/ShareX/issues/1079
