### ISSUE TITLE
Shift+PrtScr dialog can't be dismissed with the Esc key

### ISSUE THREAD

**Issue by wodim** [ShareX/ShareX#3137]
This dialog:

![image](https://user-images.githubusercontent.com/1001553/36063685-5d1ab140-0e80-11e8-9787-a97a895d7e04.png)

Can't be dismissed with the Esc key (i.e. "No")

**Comment by Fyers** [comment]
The Esc-Key only works if "Cancel" is shown as an option.
It could be changed to "Yes, No, Cancel" or "okay, cancel" but I think then the actions are confusing. Because Cancel and No would do the same.

As far as I know, there is no other way to let escapse trigger "no".

**Comment by stuntguy3000** [comment]
The only solution is to create a custom message box class. Not worth it.

**Comment by wodim** [comment]
Rephrase it so it works with “OK, Cancel”.

**Comment by stuntguy3000** [comment]
@Jaex Do you think this is worth the effort?

**Comment by wodim** [comment]
Every time I press Shift+PrtScr I have to move my mouse or remember to
press the N key to cancel that dialog. It’s super stressing and I find
myself on the brink of suicide

**Comment by stuntguy3000** [comment]
Memes aside,

I suggest you click **yes** and let FFMPEG download, or simply fix your hotkey settings.

**Comment by Jaex** [comment]
It is default Windows message box and we can't change its hotkeys.

@stuntguy3000 no.
