### ISSUE TITLE
Blur/pixelate won't display over pasted image

### ISSUE THREAD

**Issue by viktorix** [ShareX/ShareX#3146]
Here's an issue. If I paste another image inside my original image, blur/pixelate won't go over that image. It stays below pasted image. I tried using arrange options, bring to front, bring forward. They don't work.

![image](https://user-images.githubusercontent.com/1692600/36275205-2baddd2c-1258-11e8-9ff5-cd1c6a05d30b.png)

Running v 12.0

**Comment by Jaex** [comment]
It is intentional, for performance related reason I made it like that so blur can preview fast as possible. But most of the time people prefer to blur stuffs on screenshot, so it can be even advantage for some people so they don't have to move it back.

**Comment by viktorix** [comment]
Shouldn't at least arrange options work? I understand the default behavior, but arranging elements should still work to give user freedom to use it as needed. If they continue to not work, you should at least disable them for blur/pixelate so it doesn't look like it's broken.

For example, I take screenshots and combine them by copy/pasting one into another for comparison, and sometimes need to hide sensitive information.

**Comment by Jaex** [comment]
You thinking it as only images. Think it like you put 3 different blur which all collide and for top blur to be able to render behind 2 blur must render. So this will increase render time of top blur by 3x. This is not acceptable. Like I told before for performance reasons I made it like this so it can be fast.

**Comment by viktorix** [comment]
What about adding an option to "flatten image"? 

Basically, whatever is on the canvas would be merged into one image. For anyone who wants to use multiple blur/pixelate on top of each other, they would simply use blur one time and flatten image. Then they could use it again. This would allow user to use multiple layers but without performance hit you've described. This is a feature in Photoshop, when you have multiple layers you can flatten image.

**Comment by NogrTL** [comment]
Same issues with my editor. It feels super unintuitive. And no warning or etc

If it just performance issue - I guess re-rendering few times os okay once you edit it. 
If not - make it as 1 image and apply it to that image and everyone's happy. Because it's technically would be 1 image after you finish the edites
