### ISSUE TITLE
execute tasks without hotkey

### ISSUE THREAD

**Issue by User3794739** [ShareX/ShareX#3147]
I would like to have a feature to execute tasks from the hotkey settings without needing to bind a hotkey.
If this isn't too much effort, it would also be great to see this tasks somewhere on the default page.

**Comment by Jaex** [comment]
These?

![](https://jaex.getsharex.com/2018/02/ShareX_YYfpnkaUBD.png)

**Comment by User3794739** [comment]
Oops, thx. ^^
