### ISSUE TITLE
Add new image site

### ISSUE THREAD

**Issue by linuxgurugamer** [ShareX/ShareX#3153]
https://imgbb.com/

**Comment by Jaex** [comment]
ShareX already supports Chevereto: https://jaex.getsharex.com/2018/02/ShareX_j1JFxUJSpS.png
But only if they made their API key public.

**Comment by sergeevabc** [comment]
Does not work.

```
Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgbb.com/1/upload

Status code:
400 BadRequest

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Cache-Control, X-Requested-With, Content-Type
Access-Control-Allow-Methods: POST, GET, OPTIONS
Pragma: no-cache
Cache-Control: no-cache, must-revalidate
Content-Type: application/json; charset=UTF-8
Date: Sun, 05 May 2019 10:15:24 GMT
Last-Modified: Sun, 05 May 2019 10:15:24GMT
Server: nginx

Response text:
{"status_code":400,"error":{"message":"Empty upload source.","code":130,"context":"Exception"},"status_txt":"Bad Request"}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by TurkDesk** [comment]
Will imgbb added or it just doesn't work ?

**Comment by sergeevabc** [comment]
Custom uploader is ready. Be sure to insert your API key.

```
{
  "Version": "12.4.1",
  "Name": "imgbb.com (User)",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://api.imgbb.com/1/upload",
  "Body": "MultipartFormData",
  "Arguments": {
    "key": "YOUR_API_KEY"
  },
  "FileFormName": "image",
  "URL": "$json:data.display_url$",
  "ThumbnailURL": "$json:data.thumb.url$",
  "DeletionURL": "$json:data.delete_url$"
}
```

**Comment by mahadevan** [comment]
Working :) Request URL

> Custom uploader is ready. Be sure to insert your API key.
> 
> ```
> {
>   "Version": "12.4.1",
>   "Name": "imgbb.com (User)",
>   "DestinationType": "ImageUploader",
>   "RequestMethod": "POST",
>   "RequestURL": "https://api.imgbb.com/1/upload",
>   "Body": "MultipartFormData",
>   "Arguments": {
>     "key": "YOUR_API_KEY"
>   },
>   "FileFormName": "image",
>   "URL": "$json:data.display_url$",
>   "ThumbnailURL": "$json:data.thumb.url$",
>   "DeletionURL": "$json:data.delete_url$"
> }
> ```

Working :) . Request URL give : https://imgbb.com/

Is there any workthrough for uploading to specific Album ( Private ) ?
