### ISSUE TITLE
Clipboard upload auto URL shortening doesn't work.

### ISSUE THREAD

**Issue by DafsCode** [ShareX/ShareX#3155]
I've set clipboard upload to auto shorten urls, yet when i copy URLs nothing happens

https://i.imgur.com/NspdRa3.png bitly config

https://i.imgur.com/SPovKhl.png clipboard upload settings

**Comment by Jaex** [comment]
It works when you press clipboard upload hotkey. Not automatically.

**Comment by DafsCode** [comment]
Any way I can call that as a suggestion??

**Comment by Jaex** [comment]
I'm avoiding using any kind of hooks like keyboard hook, clipboard hook etc.
