### ISSUE TITLE
More settings for image watermarks

### ISSUE THREAD

**Issue by Bluscream** [ShareX/ShareX#3157]
![](https://i.imgur.com/4mbnYi4.png)

In addition to `Placement`, `Offset`, `AutoHide` and `ImageLocation` i'd like to request:

- `SizePolicy` with the possible values: `Initial`, `Fixed` and `Relative`
- `Size` which is
    - greyed out when `SizePolicy` is `Initial`
    - accepts numbers when `SizePolicy` is set to `Fixed`
    - accepts percentage when `SizePolicy` is set to `Relative`

**Comment by Eranikid** [comment]
I would like to take this

**Comment by Bluscream** [comment]
@Jaex when can i expect this to be in a compiled version? :)

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds
