### ISSUE TITLE
malfunction | ghost & strips

### ISSUE THREAD

**Issue by DarthMoulByte** [ShareX/ShareX#3163]
How to prevent this from happening?
in many gif has happened to me that creates a ghost in the image and remains recorded in the gif, as in this example
I ask you here because your fandub discord community is blind, they see a normal gif I see a big flaw in the creation of gif of your software

![2018-02-22_23-49-26](https://user-images.githubusercontent.com/24207840/36581718-faea3be0-1833-11e8-9207-e539b5687771.gif)

**Comment by L1Q** [comment]
Your example is not informative enough.   
Is there supposed to be one of those items in this frame?  
![](https://l1q.getsharex.com/2018/02/chrome_kF9tVgYTq9.png)
Could you provide examples of correct image vs broken image?
