### ISSUE TITLE
Image editor should warn on unsaved changes

### ISSUE THREAD

**Issue by taob** [ShareX/ShareX#3166]
Almost each time I use the image editor to annotate a screencap, I hit instinctively Escape with the intention of cancelling a tool or backing out of an operation, but instead if instantly closes the window without offering to save the changes I've made. There should be a confirmation dialog if changes were made without saving the file.

**Comment by vatterspun** [comment]
I agree based on conventions set for other Windows programs, but I think Jaex is going for a different kind of image editor.

**Comment by campbeb** [comment]
Implemented in 6b4a7002f3559024d391451940f5d97576cc9437
Should be available in next update.
