### ISSUE TITLE
custom region detection

### ISSUE THREAD

**Issue by peteruhnak** [ShareX/ShareX#3167]
Is it possible to customize the region detection?

For example consider the following screenshot:

![image](https://user-images.githubusercontent.com/1276328/36659745-c25f2aca-1ad5-11e8-92ae-c9d0cd6e1100.png)

I would like to detect regions based on e.g. border color, so the possible regions would be the following ones.

![image](https://user-images.githubusercontent.com/1276328/36659724-b609884c-1ad5-11e8-8b43-596cb15077ca.png)

I will need to implement the detection (that is not problem), but I need a way to hook into ShareX region detection mechanism.

**Comment by peteruhnak** [comment]
The actual implementation of the detection is my problem, what I am looking for is a way to hook it up to sharex.

**Comment by Jaex** [comment]
You are aware how current detection works right? Which using window & control handles to get rectangle info. So no image processing involved.

**Comment by peteruhnak** [comment]
Ah, I didn't know that, thanks!
I'll resolve this in post processing or something...
