### ISSUE TITLE
[Feature request] Auto crop

### ISSUE THREAD

**Issue by erenseymen** [ShareX/ShareX#3172]
Greenshot has this feature. It removes the same color frame from the picture. Example pictures attached.
![before auto crop](https://user-images.githubusercontent.com/27849007/36936722-0010537e-1f1a-11e8-9910-d480b450bd49.png)
![after auto crop](https://user-images.githubusercontent.com/27849007/36936727-062ee7de-1f1a-11e8-8e09-71bec1561b9a.png)

**Comment by Jaex** [comment]
It is already added in dev build: https://getsharex.com/docs/dev-builds

**Comment by erenseymen** [comment]
Oh that was quick :) Thx.

**Comment by vatterspun** [comment]
Generally speaking someone who puts in a feature request for auto-crop asks for it because they've done it a lot.  As such you might want to be aware that the excellent ImageMagick (also free and open source) has some remarkably good batch auto-cropping tools: www.imagemagick.org
