### ISSUE TITLE
Add support for boring.host

### ISSUE THREAD

**Issue by Rutmeister** [ShareX/ShareX#3173]
I'm currently running a minimalistic uncompressed image hosting service called [boring.host](https://boring.host) and recently people have requested me to add ShareX support. 
After finding out what ShareX is I think it's an awesome tool and I created the [configs](https://boring.host/p/sharex) for it.
Although these work fine I think it would be awesome if it could be added under the image uploaders list.
Please let me know if this would be possible or if you need anything.

**Comment by 1070rik** [comment]
👍

**Comment by 1070rik** [comment]
:+1:
