### ISSUE TITLE
Migrate ShareX Libs to .NET Standard 2.0

### ISSUE THREAD

**Issue by AluminiumTech** [ShareX/ShareX#3174]
Hi,
I've seen plenty of issues relating to ShareX on Mac or Linux.

And yes, some parts of the code such as the Windows Forms GUI rely on .NET Framework a lot.

There are some rumors that Microsoft is going to be working on a .NET Core Cross-platform GUI system in the future.

To prepare for this and also to ensure better cross-platform compatibility in the future, I propose migrating some of the ShareX Libs from .NET Framework 4.6.2 to .NET Standard 2.0 .

The libs which would be migrated under this proposal are:

- ShareX.UploadersLib

- ShareX.ScreenCaptureLib

- ShareX.MediaLib

- ShareX.IndexerLib

- ShareX.ImageEffectsLib

- ShareX.HistoryLib

- ShareX.HelpersLib

And I'd like to also suggest porting ShareX.Setup to a .NET Core 2.0 Console App (from .NET Framework Console App)

The migration of the libs would also allow a native UWP ShareX app to be created in the future.

In some cases the amount of time and effort for the migration may be fairly minimal. In other cases it may require a bit more time and effort.

I genuinely think it is well worth the effort and I hope this is completed.
Thanks.

**Comment by sylveon** [comment]
ShareX.UploadersLib cannot be migrated to .NET Standard because it contains Windows Forms code

**Comment by AluminiumTech** [comment]
> ShareX.UploadersLib cannot be migrated to .NET Standard because it contains Windows Forms code

In any cases where there is Windows Forms code in a library, it could be moved to the main ShareX application.

**Comment by Jaex** [comment]
All libraries contains Windows Forms.
