### ISSUE TITLE
Transparent PNG image in clipboard not transparent?

### ISSUE THREAD

**Issue by TheManInTheWall** [ShareX/ShareX#3175]
When I upload an image that is somewhat transparent it doesn't upload as transparent like here: https://i.imgur.com/zyv9YcL.png
But when I upload the image saved it is transparent: https://i.imgur.com/dl7ymeJ.png
Anything I can do?

**Comment by Jaex** [comment]
Short answer is bitmap is copied to clipboard and it not supports alpha channel. And even if I copy PNG to clipboard apps can't paste it.
