### ISSUE TITLE
Enhancement: Please support fractional frame rates for ffmpeg

### ISSUE THREAD

**Issue by wolfen351** [ShareX/ShareX#3183]
ffmpeg does support capturing at very low framerates, like 0.1 or 0.01 - please can you enhance this dialog box to allow this? It will allow me to make a "time lapse" of my screen for a day for example.. 

The 0.01 in this box reverts to 1 when it loses focus.. 

![image](https://user-images.githubusercontent.com/5477547/37184571-d7eb4e4a-23a0-11e8-8784-3257b765b731.png)

**Comment by sylveon** [comment]
You can use a custom command line for this effect, under screen recording options ![](https://charles.getsharex.com/LimegreenImpureDoe)

**Comment by wolfen351** [comment]
Great, thanks that's a awesome work-around!
