### ISSUE TITLE
[Bug] No method to change "TinyPicRememberUserPass" setting in the application

### ISSUE THREAD

**Issue by beneficadoramocaba** [ShareX/ShareX#3186]
System details:
ShareX v12.0 (current version)
Windows 7 x64 

ShareX accepts Tinypic login info, logs in successfully, and images can be posted without issues - but only until the program exits (at user's request or due to Windows rebooting). When ShareX is started the next time, the credentials are no longer available and the next attempt to upload an image fails. Opening the _Destination Settings..._ window reveals that the credential textboxes are now blank. This has 100% reproducibility on my system.

My debug log confirms that UploadersConfig.json is written to, and later read from, successfully, and my credentials for a second destination (Mega) are retained when the program restarts, so this is not an issue with file corruption or security rights.

A quick search reveals several other users having similar symptoms in relation to Tinypic, but none of them appear to have been resolved - perhaps they gave up and used a different hosting provider:
#46
#157
#460
#1322

**Comment by beneficadoramocaba** [comment]
There is a variable in the UploadersConfig.json file, "TinyPicRememberUserPass", which was set to false. 

Replacing false with true resolves the symptom, however IMHO this is still a bug, as there is nowhere in the application to toggle this setting.

**Comment by campbeb** [comment]
Excellent job finding the value in the .json file.

Long ago, there was a check box that allowed configuring whether to save the login or not (https://github.com/ShareX/ShareX/blob/dba0ec79f8d70f684c48c3ed250dacb9570200f8/UploadersLib/GUI/UploadersConfigForm.cs#L164)

However, @Jaex removed it (accidentally?) long ago as well (https://github.com/ShareX/ShareX/commit/520dee156350e9300bae4925e7002e819eb39e71#diff-04eb5bd01d54191d782a4954ae73a6c1L154). That was shortly before the first issue you posted (#46).

I'll submit a PR to remove the setting of whether to save or not and always save.
