### ISSUE TITLE
IMGUR upload fails

### ISSUE THREAD

**Issue by GronbergInfo** [ShareX/ShareX#3187]
> Imgur upload failed: (403) The access token provided is invalid.
> 
> Message:
> The remote server returned an error: (403) Forbidden.
> 
> Request URL:
> https://api.imgur.com/3/image
> 
> Response:
> {"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
> 
> Message:
> The remote server returned an error: (400) Bad Request.
> 
> Request URL:
> https://api.imgur.com/oauth2/token
> 
> Response:
> {"data":{"error":"Invalid refresh token","request":"\/oauth2\/token","method":"POST"},"success":false,"status":400}
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

**Comment by Jaex** [comment]
Try re authenticating from destination settings window.

**Comment by GronbergInfo** [comment]
It worked. Maybe sharex should check for such info in the error and present a dialog stating maybe one needs to re-auth and then option to take me to that settings page.

**Comment by Jaex** [comment]
Normally it automatically re authenticates but even that fails for you, not sure why.
