### ISSUE TITLE
Missing comma Chevereto.cs ShareX.UploadersLib

### ISSUE THREAD

**Issue by JMccormick264** [ShareX/ShareX#3188]
There is a missing comma after
```
new CheveretoUploader("https://picr.ws/api/1/upload", "2fbe6bbdac3ceab2e33d47a9a562cef9"),
new CheveretoUploader("https://site.pictures/api/1/upload", "3d1c64db9c84e0f4a14a734d43a28e4f") <---
```

which is causing Visual Studio to error out when build the latest commits.

Image here https://puu.sh/zEUEc/0133e97e41.png

On commit [43df50d](https://github.com/ShareX/ShareX/commit/43df50df589578a6497cfa67ce0080f0c54ca282)

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/pull/3185 :(
