### ISSUE TITLE
Very low performance over remote Desktop

### ISSUE THREAD

**Issue by theelectricsoul** [ShareX/ShareX#3191]
Hello Please see the following video. You are seeing a capture of a remote session, using RDP for Windows. The remote client is running Windows 7.

https://streamable.com/5y4x6

Selecting a region doesn't perform. Same applies to the image editor.

**Comment by L1Q** [comment]
Are you sure the host machine's hardware is not underperforming?

**Comment by theelectricsoul** [comment]
Yes very. Please see a comparison between greenshot and shareX
https://streamable.com/ha83t

**Comment by theelectricsoul** [comment]
additionally I use sharex on the same remote client computer, when I am not doing a remote session. This is my desktop computer at work.

**Comment by theelectricsoul** [comment]
Is any more input needed ?

**Comment by stuntguy3000** [comment]
@theelectricsoul 

I have deployed ShareX on a corporate network which uses RDS/Terminal Services as you suggested.
We have the exact same scenario as you. RDP Sucks at rendering motion graphics. There is no way around this. This isn't something ShareX can fix up, RDP just sucks at this stuff.

Basically you're out of luck!

We are moving to a Citrix environment soon, so I expect some improvement.

@L1Q Unfortunately this has nothing to do with machine hardware, only protocol limitations.

**Comment by stuntguy3000** [comment]
ShareX's methods of drawing the region selector is more visually engaging.

**Comment by theelectricsoul** [comment]
You can guess what I am about to suggest ;) 
An option to use a a less visually engaging selector would come in handy ;)

**Comment by theelectricsoul** [comment]
keep thread alive :) 

**Request**
An option to use a a less visually engaging selector , that will perform under RDP.
