### ISSUE TITLE
Sharex settings getting restarted.

### ISSUE THREAD

**Issue by Thehail** [ShareX/ShareX#3193]
Everytime I restart my PC, every setting gets restarted. Not the settings just the paths settings. This is what I have setup:

![image](https://user-images.githubusercontent.com/11244301/37427568-b78f5572-27c1-11e8-934d-09af744b2b18.png)

**Comment by stuntguy3000** [comment]
@Thehail Do the settings save if you close and reopen ShareX?

**Comment by Thehail** [comment]
@stuntguy3000 Somehow, it is finally saving the settings. I don't know if there was any release or something, but it works for now.

**Comment by stuntguy3000** [comment]
@Jaex requesting close
