### ISSUE TITLE
[Enhancement] Colorpicker: Copy HEX value of color

### ISSUE THREAD

**Issue by AgentBallermann** [ShareX/ShareX#3200]
I am missing the ability to copy the HTML Color  Hex-code instead of the RGB values when using the color picker.

**Comment by L1Q** [comment]
Go to Task settings - Tools and edit the "Screen color picker format" field.
There you can add $hex or $HEX to have upper or lowercase hex value.
You can also configure this per hotkey in hotkey settings.

For example I have ``#$hex`` in that field to have something like ``#f8e45f`` copied.
