### ISSUE TITLE
.NET Framework upgrade and impact on Windows XP/Vista users

### ISSUE THREAD

**Issue by Jaex** [ShareX/ShareX#3201]
We were using .NET Framework 4.0 for a long time because it was the last [.NET Framework version which supports Windows XP](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements). Because .NET Framework 4.0 does not support [TLS 1.2](https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.2) we are now forced to upgrade the .NET Framework version. Recently [GitHub removed support for weak cryptographic standards](https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/) and because of this **ShareX auto updater which relies on the GitHub API to check for updates now only works if you have .NET Framework 4.5 or higher installed**. In future, more and more services will drop support for weak cryptographic standards and make TLS 1.2 necessary. Because of this we have no choice but to upgrade the .NET Framework. Unfortunately because of this, ShareX 12.0.0 will be the last update for Windows XP and Windows Vista users. Upgrade of .NET Framework is also going to give us more technologies to work with and it is better for the security of users. We wanted to upgrade our .NET Framework version for a long time and it has now become necessary to do so. Windows XP and Vista users can still use ShareX 12.0.0 but they won't receive auto updates anymore. Unfortunately in the Steam build we are unable to stop Windows XP and Vista users from receiving updates so you must use desktop version if you are a Windows XP or Vista user. If you are using Windows 7 or higher but don't have .NET Framework 4.5 or higher installed, you can download the latest ShareX setup manually and setup will automatically download necessary .NET Framework and install it.

**Comment by ShereeBrown** [comment]
it can't opened and launch after update,i need help

**Comment by mokeev1995** [comment]
@Jaex Win Vista has .Net Framework 4.5 as i know. Am I wrong?

**Comment by TheLucky007** [comment]
@mokeev1995 in the [changelog](https://getsharex.com/changelog/) they're moving over to .NET Framework 4.6.2 which Windows Vista does not support (Vista goes up to 4.6); likewise Windows 8 (not 8.1 which can go up to 4.7.1) goes up to 4.6.1 so in other words Windows XP, Vista and 8 will no longer be supported. And as what Jaex said ShareX 12.0.0 will be the last version for the aforementioned OS's/users who are on those OS's.

Hope that answers your question.

**Comment by mokeev1995** [comment]
@TheLucky007 oh, yeah, thanks. I didn't pay attention to the fact that they switched to 4.6.1.

**Comment by thejustsoul** [comment]
This is bad news, now I will not be able to carry on the ShareX flash drive and run on different computers current portable version. Will have to remain on version of 12.0.0. Because does not work everywhere (on other computers) have a set of monstrous .NET Framework 4.6.2+ It's sad..

Maybe there's a way to make the .NET Framework portable and glue it to the portable version of ShareX? To work all "out of the box" and without installation in the system..

**Comment by BHare1985** [comment]
Dropping windows 8 support is too aggressive.  Please just move to framework 4.6 and not 4.6.2

**Comment by campbeb** [comment]
@BHare1985 Support for Windows 7 isn't dropped. Support for Windows 8 line isn't dropped, just for 8.0. The upgrade from 8.0 to 8.1 is free (https://support.microsoft.com/en-us/help/15288/windows-8-update-to-windows-8-1)

**Comment by csdsinc** [comment]
My record video function always crashes. I used Windows 10 Pro and ShareX 12.1.1. Can anyone help?

**Comment by panthersdude2001** [comment]
If anybody wants Google Photos support, they can use my panthersdude2001/GShareX program. Be aware it still has bugs. Based on the 12.0 Version.
Don't like that? Just like @Tragen said, I will modify the 1.2 code and give you panthersdude2001/ShareXP !
