### ISSUE TITLE
Questions about new version.

### ISSUE THREAD

**Issue by mikhoul** [ShareX/ShareX#3204]
I upgraded form an older version of ShareX and I have some questions.

- How I can retrieve the scroll bars in the image editor ? 

- Is it possible to put the toolbar in vertical position on the left side (like before) ?

- How I can remove the "getsharex.com" label in my screenshot ? 

- Do you have a complete documentation for all the options of ShareX somewhere ?

Regards :octocat:

**Comment by Jaex** [comment]
You have this enabled:

![](https://jaex.getsharex.com/2018/03/ShareX_DoKCY9Wr7G.png)

Which creating that "getsharex.com" watermark.

There is no complete documentation.

**Comment by mikhoul** [comment]
Thanks @Jaex  for your reply but what about my 2 other questions:



How I can retrieve the scroll bars in the image editor ?

Is it possible to put the toolbar in vertical position on the left side (like before) ?

Regards :octocat:

**Comment by Jaex** [comment]
No.

**Comment by mikhoul** [comment]
Could you tell me @Jaex  which is the more recent version of ScreenX which have "scroll bars" in the image editor ?

Regards :octocat:

**Comment by Jaex** [comment]
Currently you can pan with middle mouse drag. Scroll bars planned for next release.
