### ISSUE TITLE
Location of the sound after the task is completed.

### ISSUE THREAD

**Issue by mikhoul** [ShareX/ShareX#3206]
Where is the location of the **sound after the task is completed** ?

There is no more sound when the task end (upload).
https://i.imgur.com/a5hQnuJ.png

I know it use the Windows internal sound but I don,t know which file ShareX is looking for .

Maybe the file was deleted by another user and with the name I would be able to replace it to have it to play again when the task end. 

Regards :octocat:

**Comment by Jaex** [comment]
It is not separate file.

**Comment by mikhoul** [comment]
But why the sound does not play no more at the end of the task ?  

Do you have any idea where I could look to fix it ? 

The capture sound (shutter sound) play fine, it's only the sound after the task that stopped playing.

**Comment by Jaex** [comment]
I don't know. Try restarting pc maybe.
