### ISSUE TITLE
FFmpeg I/O error

### ISSUE THREAD

**Issue by Kn0p3XX** [ShareX/ShareX#3207]
I don't know what's wrong.. i just wanted to record a region via FFmpeg and that happened (every time).
I'm using ShareX 12.1 (got that via Pre-releases)
It worked fine before.
![sharex_2018-03-20_12-32-24](https://user-images.githubusercontent.com/16920375/37652310-5e002dc8-2c3b-11e8-8ce9-e5238eab6fc7.jpg)

**Comment by Jaex** [comment]
Are you sure those devices installed?

**Comment by Kn0p3XX** [comment]
Whoops. Forgot to install recorder devices.
I document this here again:
Click on "Task settings", go to "Screen recorder" on the left side, click on "Screen recording options..." button and then under Sources, click on the "Install recorder devices" button besides the "?" button there.
Now the "screen-capture-recorder" under Video source and the "virtual-audio-capturer" under Audio source appears.

**Comment by wibort** [comment]
Hi,

I install the recorde devices but it does not work, I get the following error

![Captura7](https://user-images.githubusercontent.com/51130608/58496381-62adf080-813f-11e9-8d6c-25aadda04b1a.JPG)

I clarify that you leave the audio and video sources configured like this:
![Captura8](https://user-images.githubusercontent.com/51130608/58496497-a43e9b80-813f-11e9-9197-16b21e112893.JPG)

If I change the audio source and use the PC's microphone, the error changes to this:

![Captura9](https://user-images.githubusercontent.com/51130608/58496674-fa134380-813f-11e9-8466-2646ab77cdc3.JPG)

Can you help me please.

**Comment by darkgreen** [comment]
I was able to resolve this by changing audio codec from AAC to MP3 ... now recording screen capture plus audio.

**Comment by darkgreen** [comment]
I was able to resolve this by changing audio codec from AAC to MP3 ... now recording screen capture plus audio.
