### ISSUE TITLE
Don't Close window if file not saved

### ISSUE THREAD

**Issue by Muramas** [ShareX/ShareX#3208]
I made it so when I capture a region it opens directly in the editor, it would be nice if I click "save as" button but click cancel (say I forgot to do something) it would not close the editor. 

In general I suggest making the editor more resilient and not close automatically.

**Comment by ned-martin** [comment]
I agree.

Currently after editing an image in the ShareX editor, it is closed and all changes are lost without prompting to save.

**Comment by opav** [comment]
It also closes without any warning on mouse right-clicks.  Very strange,infuriating and non-intuitive.

**Comment by opav** [comment]
It also closes without any warning on mouse right-clicks on most areas of the image.  Very strange,infuriating and non-intuitive.

**Comment by GregariousJB** [comment]
Adding my +1 to this. I can spend 10 minutes making text boxes, arrows, and other edits on a screenshot, but if I accidentally right-click my mouse, all of that is GONE.

**Comment by NoMoreAngel** [comment]
Same goes for copying to clipboard, previously the editor stayed open, now it closes as soon as you click the button to copy to the clipboard.

**Comment by campbeb** [comment]
I believe there is a setting already that will solve most of these issues.
![setting](https://user-images.githubusercontent.com/1089399/38065220-f6cfc852-32cf-11e8-9c88-d98e5e355916.png)
Unchecking it will leave window open on copy to clipboard and on Save as.
The next release will also include a prompt about unsaved changes which should alleviate the right clicking issue as well.

**Comment by smartfonreddit** [comment]
@Jaex could you give this another look, please? It's too easy to lose the photo editing work. All it takes is a single right click to force-close the editor without saving the changes. Right click is a commonly used gesture. Users don't expect all the work to be lost upon right-clicking. Thanks.

**Comment by Jaex** [comment]
@smartfonreddit I fixed it already in dev build.

**Comment by ngrcld** [comment]
@Jaex I have "Auto close editor on task" not checked, but the editor closes automatically on right click (also on Esc, Space, Enter)

**Comment by JakubKoralewski** [comment]
Right clicked by accident lost a beautiful meme...
