### ISSUE TITLE
Save and copy

### ISSUE THREAD

**Issue by Muramas** [ShareX/ShareX#3209]
If I am editing a capture and I want to save and copy I have to save the file and then copy. If I just click copy it closes the editor loosing all edits made to it.

I could see this being fixed by not closing the editor once the copy button is pressed or adding a separate function.

**Comment by Jaex** [comment]
In ShareX 12.1:

![](https://jaex.getsharex.com/2018/03/chrome_ZyaIcL34NR.png)
