### ISSUE TITLE
Save on Capture

### ISSUE THREAD

**Issue by Muramas** [ShareX/ShareX#3210]
I might be missing where to do this and it might already be in the program. When I am making a capture, I would like it to save a copy of it locally right away so I have a master file of it.

My wanted Workflow
Capture Region -> Save in folder -> open in editor

**Comment by trollmad3** [comment]
![image](https://user-images.githubusercontent.com/7843719/37859869-894c5bb2-2ee0-11e8-93e0-790aab96b208.png)
Do you have this enabled?

**Comment by trollmad3** [comment]
Bump @Muramas
