### ISSUE TITLE
ResultsForceHTTP ? 

### ISSUE THREAD

**Issue by hAirypAulsAck** [ShareX/ShareX#3212]
I see the ResultsForceHTTPS, and believe that it is for the API access, but I'm wondering if there is a way to output the shared link in http rather than https.. don't feel like making an ahk script for this lol ;)

**Comment by 0xRiolu** [comment]
Not that I am aware of. That won't be added either, if the service supports https there will be no reason to use http anyway.

**Comment by stuntguy3000** [comment]
@hAirypAulsAck What use case do you have for something like this?

As HTTP is on it's way out, following what @matthewburnett said, I see no reason to do this.

**Comment by hAirypAulsAck** [comment]
It was more just asking if it were possible, not asking for a feature or anything. @stuntguy3000 there is the option to copy the url of the 'newly uploaded share' to the clipboard which is a convenient feature, only downside is in order to use that share url, I need to strip the s from the https (hence the ahk mention).. No biggy, if anything, the other end should accommodate the https rather than force us to go sub standard

**Comment by stuntguy3000** [comment]
Why do you need to strip the HTTP**s** from the URL?

**Comment by hAirypAulsAck** [comment]
well the most recent case came when doing mission testing for a game.
Unfortunately to do the testing, you must upload, then insert the link
in-game so that the game can download the uploaded mission and you can
access and test it. To be honest, I can't think of any reason why they
wouldn't host it themselves, it's not like they are trying to save money
with file sizes 50~500kb. Anyway, I greatly reduced the time by using the
context shell menu upload document to drive and copy link to clipboard
(here I must thank sharex for it features because they really are great,
big difference having the ability to get the direct link rather than the
share link) feature, which is really nice cause can drop it right in the
load address bar in game, just have to strip the 's'. Odd because I thought
it would default back to http if they couldn't support it so could just be
a line of code rather than some security feature. deadly json text files ;)
. ahk ftw. take care all
