### ISSUE TITLE
Greenshot editor removed

### ISSUE THREAD

**Issue by ned-martin** [ShareX/ShareX#3220]
Please return the Greenshot image editor.

With all respect, the inbuilt editor is not yet a good replacement and is missing much of the ease of use of the Greenshot editor. Hopefully the inbuilt editor will one day be better than the Greenshot editor but at this stage the Greenshot image editor is better.

**Comment by blanzh** [comment]
I have two monitors and I can not crop an image (after printscreen) without scrollbars
And I can't undo crop

**Comment by edmunek** [comment]
Since recent updates, plenty of people were changing the "after screenshot" editor by disabling the "UseShareXForAnnotation". Yesterday an update 12.1 arrived and removed this functionality and the only editor left is the ShareX.
Why if the editor is for some people completely unusable, unlogical and just terrible?

#2621
#2436 (comment)

At this particular moment I am thinking about no longer using ShareX as I am finding this product going in wrong direction

**Comment by SC2Mitch** [comment]
>At this particular moment I am thinking about no longer using ShareX as I am finding this product going in wrong direction

OK? Go on then? ShareX wasn't made for photo editing, if you want something like that then I highly recommend Gimp or Photoshop. Making silly statements like "I'm thinking about not using ShareX" then don't? If you don't like it, feel free to uninstall. No-one here is stopping you at all.

**Comment by Torubloo** [comment]
I agree ShareX was made for screenshoting and basic image changes/edits if you want to do more powerful things use GIMP/Photoshop or something similar

**Comment by Inomares** [comment]
GIMP/Photoshop are magnitudes more heavyweight in terms of complexity and loading times than greenshot was, and third party apps do not, to my knowledge, let us "send the image back", if you will, to ShareX for uploading and other tasks.

**Comment by SoufianAkh** [comment]
Agree that Greenshot should be back. The current editor is still in its beta phase and not ready for advanced use. It should be set as an optional setting to use the new editor.

The old one had the "Copy paste" with CTRL + C and CTRL + V for example, the new version doesn't.
And many more small details.

Bring back the old editor and make your users happy. :)

**Comment by sylveon** [comment]
Instead of just wanting the old editor back, why don't you tell us what you don't like about the new one so that we can fix that?

**Comment by SoufianAkh** [comment]
@sylveon A few points:

* There's no way to switch back to the "mouse" feature to select any elements no matter the type.
* You can't modify previous placed elements without selecting that specific type first again.
* You can't copy paste using CTRL + C and CTRL + V

* The "Drawing cursor" is confusing, because in Greenshot it was used to select any element and modify it. In this new editor it actually draws a cursor (which is unnecessary).

**Comment by edmunek** [comment]
> OK? Go on then? ShareX wasn't made for photo editing, if you want something like that then I highly recommend Gimp or Photoshop. Making silly statements like "I'm thinking about not using ShareX" then don't? If you don't like it, feel free to uninstall. No-one here is stopping you at all.

??
Really? You really don't understand, that there are people which selected ShareX over other products (even purchased) because they can "like something" which just works great?
I did purchase SnagIt some time ago and I have moved myself to ShareX because it is just quicker on slower machines (and we do have such machines in our office). And I really don't understand, why when everything was "great", dev decided to change default editor from GreenShot to ShareX editor. There was still an option to use GreenShot, but now this option has been removed. So basically - some functionality which is one of the biggest advantages of the program, has been removed and replaced by ShareX editor which just does not work very well on multiple monitors enviroment. And you are saying that I should teach the whole account department to use Gimp or purchase Photoshop for hundreds of dollars where we are talking about users which say "Computer" when they see monitor on their desk?
Great point of view man, great point of view. I have asked, why this functionality has been removed as myself (and I do already have e-mails from other departments that "something bad happened to ShareX, please revert it back like it was before") and some other people don't like the ShareX editor, and you are telling me that they should move to Photoshop. 
I am speechless. Don't know what else I can say to you.
One point of view - yours.
And to answer in advance, I am not saying that GreenShot should be a default editor because we don't like ShareX editor, I am asking why the option of choosing the editor has been removed.

**Comment by SoufianAkh** [comment]
I think the simple solution for all of this is to simply have an option in which you can choose to whether use the Greenshot editor or use the inbuilt editor. And I get the point of ShareX developers for wanting people to use their inbuilt editor.

So simply use the inbuilt editor by default but optional so the user can change it back to Greenshot.

**Comment by edmunek** [comment]
And this is for what I am asking for.
Why in 12.0 there was a chance to select an editor, where in 12.1 we are forced to use ShareX editor ?

**Comment by ned-martin** [comment]
The editor is not for editing photos. It is for annotating screenshots. Unfortunately the inbuilt one doesn't do this well and has some serious flaws (such as not saving when hitting escape, not having quick ways to select tools, etc.), but the Greenshot editor does. I see that the inbuilt editor is rapidly getting better, but until such time as it is as good as the Greenshot one, removing the Greenshot one makes ShareX worse than Greenshot.

However, version 12 seems to work well? I will simply never update. Alternatively, try the Greenshot screenshot program (which is where the editor comes from.) I prefer ShareX but without the editor, it's not much good and you may as well use the one built into Windows.

**Comment by jayryemure** [comment]
I find this discussion interesting as the built-in editor is the feature that actually drew me to ShareX.  The curved lines/arrows to be more specific, which Greenshot doesn't support.

I have no use for layers and would much prefer not having them for simple image annotation.

Features I _would_ like in the ShareX image editor:

1. Mouse wheel zoom
2. No right-click exit
3. All object on the image freely selected, not just ones that menu selection
4. Color picker layout appears bugged on very high resolutions (4k)
5. Pre-set stamps.  E.g. Common stuff like legends

**Comment by GregariousJB** [comment]
The screenshot immediately closing after work has been done on it simply because I right-clicked my mouse is tantamount to cruel and unusual punishment.

**Comment by Muramas** [comment]
I agree with people here that the greenshot shouldn't of been removed yet as people still had issues with the ShareX's but I understand it from a point of view that "we want to use our own editor and need testing" though I also think that Sx's editor is strong but isn't 100% ready yet.
I know you can't make everyone happy I just think that there could of been a better way of doing that.

**Comment by sylveon** [comment]
BTW you can always set up the Greenshot editor separately downloaded from their website as action.
An example here with Paint (don't forget to check the entry however):
![](https://files.charlesmilette.net/SorrowfulJampackedDodobird)

**Comment by mtaki14** [comment]
@SoufianAkh 

>The "Drawing cursor" is confusing, because in Greenshot it was used to select any element and modify it. In this new editor it actually draws a cursor (which is unnecessary).

I actually think this is pretty useful for when you prefer to have the cursor capture disabled by default but in certain scenarios need to make screenshots with the cursor included. Being able to throw it in at will seems neat.

>When you want to copy a screenshot it immediately closes the editor window. While with Greenshot after clicking the Copy button, it stays open for further actions that you want to take such as saving or editing.

There's an option to disable this behaviour, if you click the settings cogwheel, "Auto close editor on task".

As for the rest, I agree. Some improvements are certainly still needed, but this new editor looks promising.

**Comment by SnIPeRSnIPeR** [comment]
Stupid developers. I am using Greenshot and I LOVE it SO MUCH. Why you removed it completely from ShareX????

**Comment by jamezrin** [comment]
I started to use ShareX yesterday, I switched from Greenshot. I don't know how was Greenshot integrated into ShareX but I prefer ShareX's editor over it. I don't really see a problem with it, and if you want the old behavior back just install the old version?

**Comment by TeaConcepts** [comment]
if ShareX's editor would have shortcut keys for arrow, rectangle, etc like greenshot i think it'd be fine for most people. right now having to point and click thru the tools is just painful. i hate it. reverting back to greenshot enabled version for now.

**Comment by sylveon** [comment]
@TeaConcepts #3237

**Comment by Jaex** [comment]
These are current keybinds in dev build: https://getsharex.com/docs/region-capture

Any suggestions for current and missing tool keybinds?

![](https://jaex.getsharex.com/2018/03/chrome_cDdM2Cu5t3.png)

**Comment by Jaex** [comment]
Also added keybinds for image editor tasks:

![](https://jaex.getsharex.com/2018/03/chrome_IuVsQdnU6K.png)

**Comment by JustOff** [comment]
Please bring back Greenshot editor, at least as an option! I'm forced to revert to 12.0 until then.

**Comment by B4rt0** [comment]
> @sylveon A few points:
> 
> There's no way to switch back to the "mouse" feature to select any element no matter the type.
> 
> You can't modify previously placed elements without selecting that specific element type again.
> 
> You can't copy paste using CTRL + C and CTRL + V
> 
> The "Drawing cursor" is confusing, because in Greenshot it was used to select any element and modify it. In this new editor it actually draws a cursor (which is unnecessary).
> 
> This new version uses a lot of CPU, Greenshot was lightweight.
> 
> When you want to copy a screenshot it immediately closes the editor window. While with Greenshot after clicking the Copy button, it stays open for further actions that you want to take such as saving or editing.

I couldn't agree more, the only thing I would disagree is the cursor draw tool. For the most screenshots I take I don't want the cursor to appear, hence I have it disabled in settings, but sometimes (not too often) you may want to show someone where to click in an elegant way which is to show cursor and I don't feel like changing settings every time (with greenshot I've used arrow drawing tool and drew it without the tail).

**Comment by kovacsattila-hun** [comment]
+1: Very bad a new image editor!
The best is the Greenshot!

**Comment by GregariousJB** [comment]
@Jaex, if you couldn't already tell by the replies you're getting, not many care about keybinds right now. Though it could be said that a user's issue is always seen as top-priority to the user, I'd argue that doing hours of work annotating a screenshot only to have it disappear with no alert message simply by right-clicking or hitting the ESC key is software gore. You'll lose far more users from frustration than from inconvenience.

**Comment by anacondaqq** [comment]
Sorry, but I will not be tolerant in my message. You may be offended, but the situation right now very bad.
* Default Sharex Image Editor is a big piece of not usable crap with tons of limitations and conceptual issues with interaction which requires a lot of time just to understand how is it works.
* It's not usable for doing small screenshot + small edit (just add text, or blur some area, or add an arrow) for the image. 
* All elements placed totally differently at the top, not at the left
* We, after using Greenshot for years, can't just in one day to switch it to any other editor.
* For using greenshot for around 5 years or more, I did not saw ANY crash, or bug, or any other problem.
* Ctrl+Z / moving elements on the image, confirmation button before doing some stuff is very important.

### How you can make default sharex image editor better:

#### Easy way
> return back greenshot and allow users to have a choice

#### Hardway: 

1. Open greenshot
2. Copy-paste all elements positions and logical features from greenshot to your tool at the same position with same icons / or very similar in the same order which does exactly the same what doing greenshot
3. Done

Again, the most problematic thing is the position of elements on UI.
We can not go against our habits or sharp change them. This causes only resentment and aggression.

**Comment by MartinStettner** [comment]
For me the (Greenshot) annotation tool was the main point of using and reccommending ShareX over the last three years. I updated yesterday and noticed the change when trying to crop/annotate a webpage that is "longer" than my monitor. Not having scrollbars made this task impossible!
I totally understand that developers want users to use the ShareX editor. But removing the other one during a minor version change without any notice wasn't a good idea imo.

I switched back to 12.0.0 and disabled the automatic update. Not that it matters, but I'm seriously considering switching entirely to Greenshot (need to check out their screenshot functionality though, but  this issue showed me, that that is perhaps not my most important requirement...)

**Comment by mtaki14** [comment]
@MartinStettner You can use middle-click to move around the image. But I agree that having scrollbars visible as well is better from an accessibility perspective.

**Comment by edmunek** [comment]
"I switched back to 12.0.0 and disabled the automatic update"

Exactly what I have done as well. Sadly it looks like I have brought up the topic that ShareX with Greenshot was perfect (and as you, I did recommend it to colleagues, friends, coworkers) and now even if I am trying to explain to Dev that forcing users to use ShareX editor is not a good idea, I am being the one to criticise.

**Comment by Jaex** [comment]
@GregariousJB added unsaved changes confirmation message box now, it shows when user try to close editor by pressing X button, alt + f4, esc or right click:

![](https://jaex.getsharex.com/2018/03/O3XqIlSAbc.gif)

But also if you don't like how right click works you can change it behavior from here:

![](https://jaex.getsharex.com/2018/03/ShareX_GrSX0Ax0tD.png)

**Comment by SnIPeRSnIPeR** [comment]
Stubborn person...

**Comment by GregariousJB** [comment]
@Jaex, it's a start, thank you.

I thought I'd found a decent compromise between fixing the ShareX editor and keeping the Greenshot one away, but there's quite a few angry people in here. You might want to consider bringing back the Greenshot editor and making it optional and turned off by default, like before. 

Was it hurting anything being part of the project? Any copyright issues or performance problems? Looks like it's under GNU General Public License, and I don't recall it ever crashing, so I'm not sure.

**Comment by Mascotte123** [comment]
I donated a lot to this project!!!
Reverted back to 11.4.1, problem solved!!

**Comment by theelectricsoul** [comment]
I agree. No being able to scroll or zoom....  argh.....   painful :)

**Comment by GregariousJB** [comment]
@theelectricsoul  You click and hold Middle Mouse Button to scroll. Don't know about zoom, though.

**Comment by cbenard** [comment]
I made the mistake of using the Windows Store version that auto-updates and now I'm forced back onto the crappy ShareX editor (I had already changed the General option back to Greenshot). Why are you doing this, devs? Your editor is worse. Why are you removing the option.

I have to try to find the 12.0.0 installer now and use that forever, I guess, and uninstall the Windows Store version.

**Comment by MichaelUray** [comment]
[Downloading](https://getsharex.com/downloads/) + installing the version 12.0.0 and changing UseShareXForAnnotation in the settings to false worked for me (runs the GreenShot editor again):
![2018-04-03_17-40-47_sharex_-_application_settings](https://user-images.githubusercontent.com/25169478/38259843-5e56d58e-3766-11e8-8c7c-063441e78586.png)


Disabling the auto-update check helps to get rid of the update popup messages on start-up.
![2018-04-03_17-38-05_sharex_-_task_settings](https://user-images.githubusercontent.com/25169478/38259844-5e965d12-3766-11e8-8dda-4710288592e7.png)

**Comment by cbenard** [comment]
Downloading 12.0.0, disabling AutoCheckUpdate and UseShareXForAnnotation also worked for me. I guess I'm stuck with that version forever. I put the setup executable on my Dropbox, since I presume they're going to delete it, trying to force everyone to the new editor for some reason.

**Comment by Jaex** [comment]
@MartinStettner We added scroll bars now:

![](https://jaex.getsharex.com/2018/04/1X7HooeAH4.gif)

But also you can scroll by holding middle mouse button to pan image.

**Comment by jatmn** [comment]
Thanks for the tips everyone about rolling back and disabling the auto update.. 
Been using ShareX for a few years now since I think 8.x or 9.x .. honestly, 99% of my usage of it is screenshot -> greenshot annotate...  The latest build is completely useless to me..  👎 

Image editor gripes to hopefully make it better..
- Full-screen editor is horrible.. windowed mode is no better.. the environment feels like a clone of windows image viewer with random toolbar slapped on it and very bulky and difficult to use when you have multi-monitor setups (I have 2-3 on my workstations)
- Drawing: (any type)  is too much effort to figure out how to change color/thickness of each element it was very quick and easy before. (literally the only tools in greenshot I even used)
- The magnifier tool thing that follows the cursor should be quick and easy to disable..  (personally I would never use it enabled and it's just in the way of what I'm trying to do honestly)

What I liked and used ShareX for was quick screen shot's of portions of the screen quick line/box/arrow around the section to refer to for reference change color and line thickness and send to someone/chat the image editor makes this process much longer and annoying.. Though the Quickstep numbering is neat. sadly not enough for me to like Image editor

Hopefully you bring back greenshot or make image editor better or ill have to search again for a alternative to sharex :(

**Comment by sylveon** [comment]
You can disable the magnifier already:

![](https://charles.getsharex.com/PiercingWavyWhitetaileddeer)

It's also easy the color/thickness of an element:

![](https://charles.getsharex.com/NaughtyCruelGlassfrog)
(The first button is the border color and second is the inside color)

**Comment by jatmn** [comment]
Thanks, I saw the magnifier already after posting..
Knowing those setting are under that button for border size nice information.. 

But like I said.. I just dont like anything about the interface or user experience of the Image editor. It always causes issues and annoyances when working with multi-monitor and as others mentioned it takes too much vs greenshot..

Im sorry my opinion is unchanged.

**Comment by L1Q** [comment]
What issues do you have with multi-monitor?

**Comment by jatmn** [comment]
- Toolbar bounces around independent of the "editor" window when moving it around, resizing.
- When dragging the window around in windowed mode it "snaps" to invisible grids on the desktop so the movement of the window is more of a left/right up/down slide vs floating like other applications 

- Rectangle drawing tool selection is too intrusive/sensitive? try drawing one inside of each other, just wants to move around the first one
- Resize "Dots" on the rectangle and other draw elements are way too big in my opinion (maybe 75% of that current size)

**Comment by edmunek** [comment]
Based on this topic I do have a feeling that devs don't care about users and their initial reported issue which is "why have you disabled a choice option between Greenshot and ShareX image editor" where users prefer Greenshot. Nope. Devs here just constantly ask a question on "what is the issue" so they could still force everyone to use their editor as their editor is still filled with things which users don't like.
As mentioned, for people which are new to ShareX maybe your editor is "ok" but as me, my colleagues, friends and plenty of people in this topic has said, if Greenshot was perfect as editor with using ShareX as just capturing soft then your idea to force them to use ShareX editor is just bad.
Looking at your approach (in my humble opinion) I see some similarity to Winamp, ePuls or Gadu Gadu where users loved the product until someone "smart" decided that "let's change this this and this" without listening to the customers feedback. And again I will point out, that the only massive change you are doing is not leaving users the choice where they could easily try ShareX editor, but still disable it in settings to use the Greenshot.

**Comment by phrench** [comment]
Been using ShareX for years. Updated recently and wanted to annotate a screenshot and was like "Am I just stupid or did the UI of the software just become useless?".

Turns out ShareX just came totally useless for me. And from the answers here it seems the dev team doesn't care about it. I'm going to revert back and also already started looking for alternatives.

This makes a great case study on how to scare away users by ignoring their needs and feedback.

**Comment by phrench** [comment]
Maybe somebody can help with the new editor:

1) I can't even select an element I created anymore to move it.

2) The cursor just produces kind of stamps of the cursor when I click on the image, but it cannot be used to select or move elements.

Is this normal behavior?

**Comment by theelectricsoul** [comment]
I had the same experience. It is quiet a different user experience with the new annotation tool. But there is nothing that I cannot get used to. I trust with enough user input, it will become an awesome annotator :)

**Comment by SoufianAkh** [comment]
@sylveon Why break something that already works. It's much easier to select all types with just the cursor instead of selecting a tool for each element.
For now I'll stick with 12.0.0 until the latest version will support Greenshot as well.

How harsh it might sound, I don't think you guys should try to replace Greenshot, because it has a countless amount of features.

**Comment by theelectricsoul** [comment]
**@Developers**
Maybe it is easier to explain the user, why greenshot was abandoned.

**Comment by phrench** [comment]
@sylveon Thanks for the explanation. Now I understand, but to be honest it's very illogical and not intuitive (which should be the main goal of a UI).

Any plans to include a normal cursor function which allows to select and move elements? That would hugely improve the tool and make it usable again.

**Comment by ned-martin** [comment]
@dam012345 thanks for the detailed instructions, but unfortunately this is not really a solution, though it does sort of work. Using your instructions will result in the entire Greenshot application (including its screenshot abilities, keyboard shortcuts, etc.) being loaded (which is a bit slow, and means that two almost identical screenshot programs are running at the same time), and while the image does open in the Greenshot editor, there is no "Close and cancel tasks" option. By default, both Greenshot and ShareX try to use the same keyboard shortcuts.

It might be better to just use Greenshot to take the original screenshot (it is very similar to ShareX) rather than running both at once, though I have got used to the ShareX interface (apart from the new editor which is unusable) and prefer it.

Or just keep using version 12 of ShareX, before the editor was removed. I am not aware of any issues with version 12 and it works correctly for me? I don't know what new features were added with the newer versions.

**Comment by SnIPeRSnIPeR** [comment]
Dev is very stubborn person. People need in Greenshot, not in bad built-in editor. I will use 12.0.0 FOREVER, because of Greenshot only.

**Comment by theelectricsoul** [comment]
@SnIPeRSnIPeR 
I encourage you to actually compare the two editors. There are features in the new one, that are pretty useful and have no parallel in greenshot.

But I still think the admin could elaborate a bit on the roadmap.

**Comment by ned-martin** [comment]
Doesn't really matter if there are new features that are useful when:

- People don't need or want them and
- The editor lacks features people require as essential, and
- There are bugs or design choices/features which prevent the editor from being used

I understand that the developer wants this to be his own work without depending on someone else's editor, and that's great, but unfortunately one of the main reason I - and based on what people are saying here, many other people - used ShareX was because it worked well for us with the way it took screenshots and then let us edit them in the Greenshot editor. The Greenshot program itself can also take screenshots and edit them, but the way ShareX did it was nicer. But without the Greenshot editor it becomes far less useful than the Greenshot screenshot program.

If the developer wishes to build his own editor, then I think he needs to wait until it is at least as good as the Greenshot one and doesn't have any big flaws before removing the Greenshot editor, and even then he may find that a lot of people prefer the way the Greenshot editor worked and will not be happy.

At this stage I can't see any reason to not stay using version 12 with the Greenshot editor included, but I assume at some stage something will happen making version 12 too old and I will have to switch back to the Greenshot screenshot program. I will test the inbuilt editor again at that stage to see if it's become something I would like to use, but based on this thread it does not seem that there is much interest in making it into something that I - and the other people here - want to use.

**Comment by aidsevo** [comment]
I have used the new editor a few weeks to try to get used to it.  I can agree with most other sentiments here that the new editor is not very user friendly at present.  I will list some things I dont like so this is not just another empty complaint...

One feature I sorely miss from Greenshot was how the "color picker" for annotations would keep a record of recently used colors.  With the new editor, everytime I change my annotation color it is very difficult to go back and get the same color again for the next annotation.  

I also find many settings like "border size" are more buried in drop-down menus etc which make it more frustrating to use.  Commonly used settings like this to me feel like they should be easy to access on the main toolbar, not buried down in sub menus.

The arrow tool is also less useful as you cant pick which end of the line to place the arrowhead.

It would be less disappointing if you can bring back some of this functionality.
I still think ShareX is an awesome application and recommend it to all my colleagues but I think I'm gonna roll back to 12.0 for now as this new editor is just too frustrating to use at present.

**Comment by Jaex** [comment]
@aidsevo 

> One feature I sorely miss from Greenshot was how the "color picker" for annotations would keep a record of recently used colors. With the new editor, everytime I change my annotation color it is very difficult to go back and get the same color again for the next annotation.

Added recent colors support to color picker now:

![](https://jaex.getsharex.com/2018/04/ShareX_H0T4vovlGr.png)

**Comment by phrench** [comment]
Thanks @Jaex, that will help a lot!

Any chance you're going to add a pointer which can select all elements? That is the single biggest downside of the current editor IMHO.

**Comment by drNovikov** [comment]
Long ago I've been using SnagIT and switched to Greenshot because of how faster it was. Then I discovered ShareX and switched again, because it seemed to be more stable and convenient.

I make dozens of screenshots every day. I annotate them, upload them, paste them into documents, etc. Every unnecessary click counts.

Greenshot Editor is much better for annotating than the new ShareX editor. I can click where I want my speech bubble to point, drag the mouse, type, and then move the bubble, but have the pointer point where I initially placed it. It is very important. It is so important I had to revert back to 12.0.0 and disable autoupdates.

**Comment by Torubloo** [comment]
I am pretty sure it's possible to still use Greenshot using Actions I think, not completely use

**Comment by Ethrin** [comment]
I came here with the same problems, but I see that ShareX is trying their hardest to improve their image editing program so we don't need a separate program. This sounds like a good idea, but ShareX editor definitely needs some improvements. I currently have v12.1.1, so my apologies if any of these have been fixed already.

My biggest complaint is sometimes, I'll press ESC expecting to cancel a selection, but it immediately aborts the whole image process, even when I have unsaved changes.

**Comment by cbenard** [comment]
I haven't looked back through the source for when they removed the option. Would it be pretty simple to just fork ShareX and keep taking updates from sharex/master and keep the option to open Greenshot?

If 12.0.0 ever stops working, I'll look into that myself.

**Comment by drNovikov** [comment]
Damn... testing Screenpresso's Editor further... If ShareX's editor had these features and was a bit more usable, I'd donate 50 or even 100 dollars.

**Comment by drNovikov** [comment]
Oh well...looks like I am about to buy Snagit. It has an amazing SmartMove feature, and it's scrolling capture is much better than ShareX's or other competitors. They just need to adopt Screenpresso's step markers and magnifyer.

**Comment by InkToCode** [comment]
Few requests:For image editor, can you please add select element option, similar to Greenshot. It took me 2 weeks to find out how to select specific element that I draw in sharex , for example : https://app.box.com/s/tbylcmypygguscc1y1oqhuvw7xwzfr2g 
![image](https://user-images.githubusercontent.com/12539328/42132317-431e4786-7d1e-11e8-8ba1-d7d7c6089bd9.png)

For example, if we draw an arrow and next we draw an rectangular , to edit, move the arrow we need to select the arrow drawing element first and hover over. In greenshot img editor we just had a select element feature.

**Comment by CatGirlsAreLife** [comment]
I would love if I could take in any image into the editor and then have an option for the following:

1. Recolor entire image based on a specific color a user picks from a color picker dialog.
2. Remove a specific color based on a selected color and any darker versions of be becoming partially transparent.

**Comment by SnIPeRSnIPeR** [comment]
I say it again..

"Just return an option to use GREENSHOT instead of built-in editor. That's all what WE WANT FROM YOU. After that you can fix your built-in editor from now until forever."

**Comment by jamezrin** [comment]
If you don't like ShareX's editor, stop using it and go to Greenshot, it's that simple. I like ShareX's editor anyway so I'll keep using it. 
The developers of ShareX don't owe anything to you all, this software is free and they do whatever they feel is the best for everyone, if you don't like it, as I said earlier, stop using it.

**Comment by MichaelUray** [comment]
What is actually the reason that the Greenshot editor got removed?
Is there a disadvantage to have both editors in ShareX included?

**Comment by Torubloo** [comment]
@MichaelUray Only having 1 editor means ShareX is smaller in size and more lightweight which is exactly what ShareX is designed to be, lightweight.

It also means not relying on other software and other developers for your program to work.

**Comment by Torubloo** [comment]
Here this guy goes again, spamming dislike on helpful comments, only crying and complaining instead of contributing anything.

**Comment by JustOff** [comment]
@Torubloo Haven't you already unsubscribed as promised? It seems the best thing you can do, instead of useless advocating.

**Comment by cbenard** [comment]
I'd be fine if they didn't bundle Greenshot but instead let you use it the same way it used to work if you had it installed. The actions menu @Torubloo proposes is obviously inferior to anyone who's attempted to use it, so saying it "multiple times" doesn't make it any more useful of a tip.

As it is, I'll be staying on 12.0.0 forever, I suppose.

**Comment by sylveon** [comment]
That's not possible the way Greenshot was bundled. It was compiled directly as a library dependency, instead of a separate program being distributed.

**Comment by franco27** [comment]
I do not like the new editor

**Comment by stuntguy3000** [comment]
"new editor"

**Comment by TeaConcepts** [comment]
came back to check if the dev has reconsidered and reverted back to the way almost all veteran ShareX users want it... sucks be disappointed... i guess im stuck @ v12 forever as well.. :(

**Comment by Jaex** [comment]
@phrench

> Any chance you're going to add a pointer which can select all elements? That is the single biggest downside of the current editor IMHO.

Select tool now added (#4058) to [dev build](https://getsharex.com/docs/dev-builds).

![](https://jaex.getsharex.com/2019/04/ShareX_Ul5SEuSgsG.png)

**Comment by rafitamolin** [comment]
The new editor uses way a lot CPU, uninstalling the latest version and using whatever version that uses Greenshot.

**Comment by SoufianAkh** [comment]
I'm still proudly using Greenshot editor and haven't updated ShareX since this update.

**Comment by sylveon** [comment]
Ok, good for you

**Comment by theelectricsoul** [comment]
@SoufianAkh 
lol...  tell the developer what to improve. But do not tell him to use MS Office when he is developing Libreoffice. Thats crap.

**Comment by cbenard** [comment]
> I'm still proudly using Greenshot editor and haven't updated ShareX since this update.

@SoufianAkh Sadly, I'm also marooned on 12.0.0.0, never to update again. It's still working on 1903, thankfully. I'm really sad the developer removed the **choice** from us.

**Comment by jatmn** [comment]
Really wish the dev would have reconsidered removing Greenshot
#Version12.0.0.0Forever

**Comment by ned-martin** [comment]
Thanks for the detailed instructions. Unfortunately, doing it the way you've shown, means you don't get these three buttons, which are the main ones I use - hence why I have also stuck with the old version. If it eventually breaks for some reason and I need to upgrade, I'll go spend some time researching the market and switch to using whatever screenshotting tool out there is currently best (sadly not ShareX anymore), but until then, version 12 works fine.

![image](https://user-images.githubusercontent.com/8716445/63731765-7a1e8600-c8b4-11e9-9cee-261012d0937a.png)

**Comment by ryantheleach** [comment]
@ned-martin What do those buttons even do? I'm running the latest version of greenshot, and they don't appear. It would seem that you need to downgrade greenshot, not sharex.

**Comment by ned-martin** [comment]
> 
> 
> @ned-martin What do those buttons even do? I'm running the latest version of greenshot, and they don't appear. It would seem that you need to downgrade greenshot, not sharex.

@ryantheleach this is about ShareX (which used to use the Greenshot editor, which is what this discussion is about), not Greenshot. They are two different programs. 

For what it's worth, those buttons save (or whatever your configured action is, it could be upload, etc.), cancel, or delete the screenshot taking process.

**Comment by ryantheleach** [comment]
I understood, but someone posted a workaround above, but the complaint was those icons were missing, so either sharex was using a forked greenshot, OR greenshot itself removed those icons from the editor.

**Comment by ned-martin** [comment]
> 
> 
> I understood, but someone posted a workaround above, but the complaint was those icons were missing, so either sharex was using a forked greenshot, OR greenshot itself removed those icons from the editor. It was my assumption that the fault of those icons being missing, was greenshots, not sharex. It's definitely sharex's decision that removed greenshot editor from being bundled with sharex however.

You have misunderstood the issue here.

Yes, ShareX used a modified version of Greenshot's editor for its own editor.

Unfortunately the developer of ShareX removed this and replaced it with his own editor. A lot of us feel that his own editor is substandard when compaerd to the modified version of Greenshot's editor, and started this issue thread to request that the modified version of Greenshot's editor be added back.

The "workaround" posted above uses a standalone third-party Greenshot editor, which is not the same as the modified version that was included with ShareX and which doesn't integrate properly with ShareX's workflow, and hence does not fix this issue or return the functionality (such as those three buttons) that is missing.

However despite quite a large amount of people requesting this, it's been made quite clear that the developer has no interest in returning, and is continuing to develop his own editor instead, so this is probably a dead issue. I assume most people are doing the same as me, and using an old version of ShareX before the Greenshot editor was removed.

**Comment by ryantheleach** [comment]
Ok, found the answer, 
1. Yes the Greenshot editor was indeed forked.
2. Yes there are changes not present in older versions of Greenshot.

**Comment by ryantheleach** [comment]
For what it's worth, I attempted to fork the old sharex, but the version of .net that it uses is old enough that I'm unable to find the developer pack / sdk online, to compile out a stand-alone version of the greenshot editor. So I can't get it to build with Rider.

**Comment by daslicht** [comment]
which is the fastest way to draw in arrows and cut/blur parts after capture , please?

**Comment by anacondaq** [comment]
To be honest, the issue not really actual anymore. The functions added to the current sharex pretty okay, and good for capturing, and working with captured images, the same experience like with the greenshot. But maybe a little bit different hotkeys what need to learn.

**Comment by ned-martin** [comment]
> 
> 
> To be honest, the issue not really actual anymore. The functions added to the current sharex pretty okay, and good for capturing, and working with captured images, the same experience like with the greenshot. But maybe a little bit different hotkeys what need to learn.

Many of us will never know as we can't update past version 12.0 - the last version with the Greenshot editor in it :)

**Comment by cbenard** [comment]
> Many of us will never know as we can't update past version 12.0 - the last version with the Greenshot editor in it :)

My thoughts exactly. I'm on 12.0.0 until it doesn't work anymore.

**Comment by anacondaq** [comment]
@cbenard @ned-martin try latest sharex, I confirm that first versions when greensharex dropped was awful, but current versions much better if compare to initial ones. Try it, it's great.

**Comment by MichaelUray** [comment]
I tried the latest version a couple month ago and then I went back to the old version 12.0 which includes the Greenshot editor.
