### ISSUE TITLE
BUG: Cannot drag to the main window of ShareX to upload after the 12.1 update.

### ISSUE THREAD

**Issue by thelastfantasy** [ShareX/ShareX#3222]
This is very inconvenient.

**Comment by Jaex** [comment]
It could be because ShareX ran as admin from setup. Close ShareX, reopen it.

**Comment by thelastfantasy** [comment]
fixed, thank you!

**Comment by MrCD1968** [comment]
Closing it and reopening did not work for me. Still cannot drag and drop.

**Comment by MrCD1968** [comment]
Why do you keep closing this? Drag and Drop no longer works. The above explanation is not my solution. If you don't want to investigate it further state so and then close it.  If it doesn't  work someone will simply reopen the ticket or create a new one.  Thanks for the program
