### ISSUE TITLE
Uploading via FTP only 1/4 image

### ISSUE THREAD

**Issue by ginoname** [ShareX/ShareX#3224]
Afer update i have huge problem. Uploading on my FTP, i see only 1/4 image. https://i.imgur.com/mg7dhel.png New update is bugged so much, on older vesion is working fine. 
Where i can disable damn update notifications? When i check "Do not prompt again untill ShareX starts next time" and press NO its not working. I see this every time i run my PC. Whare can i block this? Mabe hosts edit?

**Comment by Nico207** [comment]
Hi !
To disable update, set the value in "Application settings / Advanced / Autocheck Update" to false.

**Comment by C0kkie** [comment]
I have the problem that i cant upload to a ftp server anymore since the last update

**Comment by Jaex** [comment]
fixed by #3225

**Comment by Jaex** [comment]
Can you try dev build (https://getsharex.com/docs/dev-builds) to verify is issue fixed?

**Comment by C0kkie** [comment]
For me its fixed

**Comment by Sickness-chan** [comment]
The dev build seems to fix it for me as well

**Comment by idarktech** [comment]
I am also experiencing this problem with the latest version 12.1.0. I simply downgraded back to 12.0.0 where it is working fine. I will try the dev build.
