### ISSUE TITLE
"Removed Greenshot image editor"

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [ShareX/ShareX#3226]
Why you removed very usable Greenshot image editor from new version? I am using this very long time and LOVE it so much. Your image redactor is uncomfortable compare to GREENSHOT. WHY? How can I return it??

**Comment by jacksonisiah** [comment]
Duplicate of #3220

**Comment by trollmad3** [comment]
Greenshot image editor is litterally garbage. If you love it that much you can download it [here.](http://getgreenshot.org/)

**Comment by SnIPeRSnIPeR** [comment]
You ruined your app.

**Comment by trollmad3** [comment]
@SnIPeRSnIPeR How? The app is litterally **perfect** without greenshhot. Infact Greenshot made sharex worse of how buggy it is.
