### ISSUE TITLE
OwnCloud using /preview instead of /download

### ISSUE THREAD

**Issue by Z0mbine** [ShareX/ShareX#3228]
I am not sure why this was changed, because my direct links all end with /download, as per default ownCloud 10 installation settings.
Using /preview, no image shows up anywhere and when clicking the link, I am taken to my ownCloud home page.

Is there a way I may revert this?

**Comment by mltnhm** [comment]
Guess I'll need to add an option for that. Didn't know ownCloud was missing previews. Should have done more testing.

**Comment by Z0mbine** [comment]
ownCloud has stated they are firmly against having images preview in browsers for "security reasons."
This can be bypassed with some editing of their files, though.

**Comment by Jaex** [comment]
@mltnhm I will release new build soon because of FTP bug. Do you think you can add it before that release?

**Comment by mltnhm** [comment]
Working on it

**Comment by mltnhm** [comment]
Sorry for taking so long but I've added a setting for it in #3205
