### ISSUE TITLE
Updating creates desktop shortcut when not needed.

### ISSUE THREAD

**Issue by SylveonBottle** [ShareX/ShareX#3238]
Updating from a previous to a new version creates a new desktop icon for Sharex when there wasn't one previously.

If I'm updating the program, then it shouldn't have to create a new desktop icon if I already have one. And if I don't have one, that just means I didn't want one in the first place.

Should be a simple check on the installer to see if there's already files for ShareX before installation, maybe some cache or the programs folder. If there is, don't touch the desktop for sake of users' preference.

**Comment by sylveon** [comment]
It doesn't on my machine. Probably because you checked the option to create a shortcut during the initial installation which means future updates end up respecting that choice too. In my case during the initial install I didn't check it, meaning the updater respects that choice and doesn't creates one.

Maybe it's possible to add additional logic for detection of the desktop shortcut's presence in the updating process.

**Comment by SylveonBottle** [comment]
Ah, I see. I use [Chocolatey](https://chocolatey.org/packages/sharex) for bulk installation on new computers, so I'm assuming that's a default option for the installation process.

**Comment by sylveon** [comment]
Checking the source of the Chocolatey package, it does not specify any options for it:
```ps1
$packageArgs = @{
    packageName    = $packageName
    fileType       = 'exe'       
    url            = 'https://github.com/ShareX/ShareX/releases/download/v12.0.0/ShareX-12.0.0-setup.exe'
    url64bit       = $url   
    checksum       = 'DAC621553C23297569CF9B863C27D5B93B52DAA378257E8DC7B12E4C7E26EAFF'
    checksumType   = 'sha256'
    checksum64     = $checksum
    checksumType64 = $checksumType
    silentArgs     = '/sp /silent /norestart'
	validExitCodes = @(0)
}
```

This means the installer's default kicks in, which effectively is to create a desktop shortcut.

I've filled a pull request that should make the update process not recreate it, #3243
