### ISSUE TITLE
cannot disable history list

### ISSUE THREAD

**Issue by greatwroth** [ShareX/ShareX#3240]
I have unchecked everything in the history tab but the main window still lists recent captures.
![image](https://user-images.githubusercontent.com/3023924/37877987-335c832a-3017-11e8-854e-bae0c5fd5f70.png)
Windows 10 Pro 64bit with ShareX 12.1.1

**Comment by Jaex** [comment]
Those options to disable saving them so when you re open ShareX those entries won't show up again. So you can't disable entries showing up for active instance.
