### ISSUE TITLE
v12.1.1

### ISSUE THREAD

**Issue by MQAdmin007** [ShareX/ShareX#3241]
Some issues in new v12.1.1 (possibly from 12.1, jumped from 12.0 ->12.1.1):
- Image editor - allows annotations to spill outside the canvas;
- Is there a way to return Image Editor Vertical Tool Bar?
- Application setting - Path -> Sub folder Pattern (%y-%mo-%d) -  gets **ignored**, 
  images get stored in the Custom folder (root), no dated sub dir created.
---
P.S. Thank you for the great tool, using it every day.

**Comment by Jaex** [comment]
* It is intentional.
* No.
* It works for me: ![](https://jaex.getsharex.com/2018/03/ShareX_9SAQcka4mn.png)
