### ISSUE TITLE
.Net Framework version 

### ISSUE THREAD

**Issue by seeyouethan** [ShareX/ShareX#3244]
Must I have to run this program on .net framework 4.6.2 ?
Can it run on .net framework 4.5.2 or .net framework 4.5 up

**Comment by Kirides** [comment]
It Depends.

If the only reason for 4.6.2 is TLS 1.2 then no. But 4.5 is the minimum version required to support it in any way that i know of.

- https://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/

**Comment by zacr0** [comment]
My ShareX refuses to open even after updating .NET framework to version 4.6.2. What should I do?

**Comment by Torvinski** [comment]
Same issue here. I installed the .NET 4.6.2 but still get that popup window indicating I need to install .Net 4.6.2

**Comment by tablatronix** [comment]
What is the deal with this, suddenly unusable.

![image](https://user-images.githubusercontent.com/807787/39871344-16f7aaf2-542a-11e8-950b-2e352a858efe.png)

![image](https://user-images.githubusercontent.com/807787/39871351-1b6e82c2-542a-11e8-87ad-ae072aa4c291.png)

**Comment by tablatronix** [comment]
I reverted to 12, seems to work so far
https://github.com/ShareX/ShareX/releases/tag/v12.0.0

**Comment by tablatronix** [comment]
anyone know if this is fixed, I am mostly using mac now

**Comment by Jaex** [comment]
Fix what? There is no issue.

**Comment by tablatronix** [comment]
Just upgraded to 12.2 no errors, issue seems resolved
