### ISSUE TITLE
Get rid of the annoying update popup

### ISSUE THREAD

**Issue by Scellow** [ShareX/ShareX#3246]
Hello

The popup that randomly spawn is just annoying

Suggestion:

- Make it popup only when i open ShareX
or
- System Tray notification
or
- Windows Notification

**Comment by Dyras** [comment]
What popup? I don't have any kind of popup for ShareX

**Comment by campbeb** [comment]
Can you post a picture of the popup you are referring to?

**Comment by Scellow** [comment]
This one: 
![sharex_2018-03-30_21-58-20](https://user-images.githubusercontent.com/27389256/38160602-d6895e58-34c0-11e8-880c-0df805d0c4e9.png)

**Comment by campbeb** [comment]
If you click the checkbox in the dialog, then it will only display when ShareX starts.

Or you can disable it completely:
![image](https://user-images.githubusercontent.com/1089399/38165726-1d882e22-34e6-11e8-925e-c2047a01119e.png)

**Comment by stuntguy3000** [comment]
Either do above or _update ShareX_

**Comment by Scellow** [comment]
From UX point on view this is just bad design, can you imagine if all of your running program would spam their popup because they want an update ?

Do like everything else, and implement a system tray notification

**Comment by stuntguy3000** [comment]
ShareX doesn't spam the updates though. In no way is this bad UI design.

You only see the update notification on program launch. It provides a dialogue to hide it.

Updates are important. Tray icon notifications get ignored.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Actualization** [comment]
ShareX is the only program I know that is built to start with the computer and has update notices that display.

Possible solutions
- Auto update option (If its important that we update to the point we need a pop ups continually on start till we update on every version release we should update each version, why not just update it if its that stable, important and safe?)
- Ignore until next major version (a common option found in programs such as OBS) with perhaps an override for security fix branch releases aka releases with major security fixes pre major version with some flag.
- Ignore until next version release (an option found in software such as DBeaver)

**Comment by meifiant** [comment]
> This one: ![sharex_2018-03-30_21-58-20](https://user-images.githubusercontent.com/27389256/38160602-d6895e58-34c0-11e8-880c-0df805d0c4e9.png)

Thanks, will try and test.

**Comment by Glendios** [comment]
Sharex also uses a lot of cpu when the popup is open, so you're forced to click the notification and click no or experience a slowdonw until you do it. That is my main problem with the update notifications.

**Comment by CorentinJ** [comment]
Why is this closed? This is still an annoying issue

**Comment by cnra** [comment]
Can't see this option:
![image](https://github.com/ShareX/ShareX/assets/538421/8b7ef7a6-a3fc-489d-8fbe-ceaff9258da1)

**Comment by AldeRoberge** [comment]
@cnra 

<img width="846" height="518" alt="Image" src="https://github.com/user-attachments/assets/427c07c5-84c0-406d-977c-78f6a26f05be" />
