### ISSUE TITLE
AVG Antivirus Thinks That The Latest Version of ShareX is Ransomware

### ISSUE THREAD

**Issue by XOverdose** [ShareX/ShareX#3250]
Today I updated to the latest version of ShareX, as I wanted to take a screenshot of my team in FIFA 18.  However, once I updated the software and tried to take the screenshot, I got this error, "Cannot write to documents/ShareX/Screenshots/3-18, something like that.  I restarted the machine and reinstalled the latest version and when I went to take a screenshot with the clean installed latest version, I got a message on my computer from my antivirus, AVG saying "Threat Blocked, Allow App, Don't Allow App." and then it said under it "Potentially Ransomware," which shareX shouldn't be as its a safe program to install.

I don't have any screenshots because I reinstalled the last version, which is working fine for me.  Anyone else experiencing the issue?

**Comment by mltnhm** [comment]
Do they have an option to report a false positive? If so I'd say to link them to the repo.

**Comment by Jaex** [comment]
https://www.virustotal.com/#/file/ee590a66234c0f1dc57725173eb4c4d3c1babf40c516b64e7d1604eb37f85909/detection
