### ISSUE TITLE
[12.1.1] Region Capture No Longer Auto-Fit to App Windows

### ISSUE THREAD

**Issue by VaslD** [ShareX/ShareX#3251]
[Video (Dropbox link, GitHub doesn't support MP4.)](https://www.dropbox.com/s/wre3bgh5aene7dc/ShareX%20Bug%20Report.mp4?dl=0)

Prior to 12.1.1, (maybe from 12.1.0? Skipped that update.) Region Capture used to "lock on" to visible windows. Single-clicking on a visible window will automatically select the entire window as a new region. In the latest version, Region Capture defaults to fullscreen region only and I have to drag a rectangle around a visible windows to capture it.

A workaround is using the Window Capture, but Window Capture uses drop-down menu so it doesn't allow selecting multiple windows at once.

Not sure if this is a bug or intended feature change to distinguish Window Capture and Region Capture. Nothing like this was mentioned in the changelog.

Debug log shows only loading configs. The following assemblies are also loaded:

- ShareX.exe
- ShareX.HelpersLib.dll
- ShareX.UploadersLib.dll
- Newtonsoft.Json.dll
- ShareX.ScreenCaptureLib.dll
- ShareX.ImageEffectsLib.dll
- ShareX.IndexerLib.dll
- ShareX.MediaLib.dll
- MegaApiClient.dll

Tested on Windows 10 Version 1709 (Build 16299.334, latest from Windows Update); NVIDIA GeForce GTX 10-series with overlay shortcut turned on but Instant Replay turned off. No other application (besides Services and system/background stuff) was interfering I assume, everything running were visible in the video.

**Comment by Jaex** [comment]
Most likely there is invisible fullscreen window in front of everything therefore ShareX sees that and hovers it.

**Comment by VaslD** [comment]
Possible, but I have switched between 4 recent versions and only 12.1.0 and
12.1.1 exhibit this behavior.

**Comment by Jaex** [comment]
Hover related codes last updates more than 1 year ago.

**Comment by Mikrz** [comment]
Seems like this hasn't been solved yet, @Jaex is there any way to tell what app ShareX is detecting as "on top" in relation to it's region selection? I feel like it could be an always on overlay like Nvidia's GeForce Experience Alt+Z overlay perhaps? Though it seems that specific overlay is not the cause in my case as disabling it does nothing.

**Comment by VaslD** [comment]
@Mikrz Your input corresponds to what I strongly suspect: Microsoft happened. Windows 10 Version 1803 was released in April, and whatever changes they made might have affected ShareX. Since @Jaex said all code related to hover was last modified long time ago, it is possible that improvements are needed to be compatible with the new Windows 10.

I do not have sufficient knowledge to identify the exact problem/code. But I will try and report back if I'm lucky.
