### ISSUE TITLE
Feature: markup/annotation capability similar to SnagIt

### ISSUE THREAD

**Issue by phipurcell** [ShareX/ShareX#3253]
One of the most useful features of SnagIt is being able to draw lines, circles, squares, arrows and add text to a screen capture. 

New here so, if this is a duplicate suggestion or not the right place; delete, move or whatever.

**Comment by campbeb** [comment]
ShareX can absolutely do this. 
Just set an after capture task to "Open in image editor"
![edit](https://user-images.githubusercontent.com/1089399/37999339-5f7357b0-31f0-11e8-8584-e64238233026.png)
