### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by allele** [ShareX/ShareX#3257]
[report.txt](https://github.com/ShareX/ShareX/files/1853910/report.txt)

Caused by a failed sleep mode on Windows 7.

Computer froze up when trying to go to sleep, had to force reboot.

I have reinstalled Sharex, but the error still appears.

**Comment by campbeb** [comment]
Your computer seems to have lost the Arial font.
See #374 for a link to Microsoft site where you can download it.

**Comment by allele** [comment]
Fixed, thanks!
