### ISSUE TITLE
Create gif with progress bar

### ISSUE THREAD

**Issue by nicosmeenk** [ShareX/ShareX#3258]
It would be cool to be able to add a progress bar to a gif - see https://www.excelcampus.com/library/add-progress-bar-to-gif/

Maybe it could be enabled in the settings/properties.

**Comment by nicosmeenk** [comment]
I don't think it would increase the render time a lot. It's just another ~5px bigger than before. And if it's possible to enable/disable the feature in the settings, I don't see a problem with it.

**Comment by nicosmeenk** [comment]
I still think that would be super useful!

**Comment by robdotdotdot** [comment]
Agreed. Can we promote this up?

**Comment by nicosmeenk** [comment]
nope... would still be a super useful feature

**Comment by nicosmeenk** [comment]
guess I am too late :(

**Comment by cernyjan** [comment]
I miss this feature in an otherwise perfect ShareX, so I have made python script for adding progress bar into already recorded gif by ShareX -> https://github.com/cernyjan/gifTimelined
