### ISSUE TITLE
After upload callback url?

### ISSUE THREAD

**Issue by Kcko** [ShareX/ShareX#3259]
Hi, at first thx for best app for saving image screenshots and video capturing :-)

Is there exists any chance for this idea -> I need call some url (lets call eg: after ftp upload callback url) for image processing after upload to my ftp. 

im uploading screenshot and after upload sharex will call after upload url /myserver/?screenshot=foo i and and I will process it in php (save to database etc).

Does it make sense? Now I can only upload image / file without mine interaction :/

**Comment by Jaex** [comment]
You can use custom url sharing destination:

![](https://jaex.getsharex.com/2018/03/chrome_EN1LFnssLL.png)
