### ISSUE TITLE
Editor: top toolbox covers the image

### ISSUE THREAD

**Issue by barsv** [ShareX/ShareX#3267]
My problem with built-in editor is that the top tool box covers part of the image, when i take full screen screenshots. 
here: 
![2018-03-29_13-10-35](https://user-images.githubusercontent.com/2222578/38080933-d68adea4-3353-11e8-8eb2-b39fc4b108df.png)
i want to annotate url in the address bar but i don't see it because of the toolbox.

**Comment by barsv** [comment]
if there is no workaround then i can try to fix it with a pull request.
options:
1) add zoom in/out toolbox button
2) make the image to be always below the toolbox
3) make to toolbox draggable and resizable
@Jaex , please advise

**Comment by L1Q** [comment]
You can pan the image with middle mouse button

**Comment by barsv** [comment]
thank you!
closing. 
though it's probably good to add 'pan' button to the toolbox.
