### ISSUE TITLE
Gif recording issue

### ISSUE THREAD

**Issue by Lerkis** [ShareX/ShareX#3268]
Gif still saves as a file when instructed not to.
![image](https://user-images.githubusercontent.com/37546151/38093258-fb1be3c8-339c-11e8-9835-8e350ac7256a.png)

**Comment by Jaex** [comment]
It can't record without saving to file. But you can use this option to remove file after upload:

![](https://jaex.getsharex.com/2018/03/explorer_VYD4ZL3Ysb.png)
