### ISSUE TITLE
Feature request: better file opening in image editor

### ISSUE THREAD

**Issue by cloo** [ShareX/ShareX#3270]
ShareX image editor is very useful- and I often use it for non-screenshot images. But opening other files on Windows now looks like this: 

Right click ShareX tray icon > Navigate  to Tools > Navigate to Image editor > New dialog opens > Use Browse file and find the file to annotate (drag'n'drop on the dialog doesn't work).

So clumsy. 

Woudln't it be nice to have a desktop shortcut for Image editor?
Or maybe it is easier to update shell integration, so that I could right click image file in explorer and choose "edit with ShareX"? An option for people who appreciate it, maybe.

Or am I missing something?

**Comment by Jaex** [comment]
I will add "Edit with ShareX" button to Windows Explorer context menu in next release.

**Comment by MiLeX84** [comment]
What happened to the edit with ShareX context menu button, I it super clumsy to have to sent the image to shareX first, instead of just right-click any file and directly open it with the shareX editor, that all I want.
