### ISSUE TITLE
Error on "Import settings..." importing 12.0 and 11.8 settings from "non-Portable" into Portable

### ISSUE THREAD

**Issue by jerryasher** [ShareX/ShareX#3271]
I exported my settings from the regular, non-portable 12.0 version of ShareX, downloaded the portable version, tried to import my settings and received this:

![ShareX - Error message box](https://i.imgur.com/3dX2OjK.png)

My 11.8 settings failed in the same manner.

**Comment by Jaex** [comment]
From changelog:

![](https://jaex.getsharex.com/2018/03/chrome_UQ7waM0pH7.png)

**Comment by xmedeko** [comment]
Well, it works, thanks. But some nice error message would be better. Something like:
```c#
} catch (InvalidDataException ex)
{
    throw new Exception("Cannot read settings. If are importing pre 12.0 then uppack the settings manually to the Documents/ShareX folder. See changelog URL. ...", ex);
}
