### ISSUE TITLE
i has same issues with ShareX

### ISSUE THREAD

**Issue by ShereeBrown** [ShareX/ShareX#3281]
i got problem with Share X  same on windows 10,please help
![capture](https://user-images.githubusercontent.com/8306345/38274397-0705dfac-37d2-11e8-98bb-cd4075253d3b.PNG)

**Comment by campbeb** [comment]
The message displays what the problem is and lets you know what programs are likely causing the conflict.
What additional help are you looking for?

**Comment by stuntguy3000** [comment]
Going to assume your issue here..

@ShereeBrown I recommend [this fabulous application](https://www.r2.com.au/page/products/show/startup-delayer/) to combat your issue.

This allows you to launch Dropbox and OneDrive **after** ShareX on system startup, preventing hotkey reg from being an issue.
