### ISSUE TITLE
DNS 1.1.1.1 added to list.

### ISSUE THREAD

**Issue by Mitsuma** [ShareX/ShareX#3283]
Wonder if ShareX could add https://1.1.1.1/ to the List of DNS services.
I know you can just manually add 1.1.1.1 and 1.0.0.1 but since this one not bad in speed and security it might not be a bad idea to have it in the list.

**Comment by Jaex** [comment]
I already added it.

**Comment by Mitsuma** [comment]
Should have looked into the history I guess.
On a sidenote 1.1.1.1 apparently is blocked on some ISPs although I don't think you can or need to write any warning about it.
