### ISSUE TITLE
Chocolatey Updates required

### ISSUE THREAD

**Issue by Jarli01** [ShareX/ShareX#3286]
Hi team,

Please update the packaging for Chocolatey so we don't have to manually update this software. The currently supported version is 12.0.0, 12.1.1 is out. 

Thank you,

https://chocolatey.org/packages/sharex

**Comment by Jaex** [comment]
We can't update it. Users own that package.

**Comment by sylveon** [comment]
The user which maintains that package seems to have deleted his GitHub account. @Jaex do you think it would be a good idea to email Chocolatey support to get ownership of it?

**Comment by Jarli01** [comment]
That would be ideal, as I know of at least a few organizations that use Chocolatey and ShareX, while updating is easy enough, it does require admin permissions to do. 

If you wouldn't mind here is the link to [contact the Chocolatey admins to address this. ](https://chocolatey.org/packages/sharex/12.0.0/ContactAdmins)

**Comment by Jarli01** [comment]
`$ErrorActionPreference = 'Stop';
 
$packageName = 'sharex'
  
$packageArgs = @{
    packageName    = $packageName
    fileType       = 'exe'      
    url            = 'https://github.com/ShareX/ShareX/releases/download/v12.1.1/ShareX-12.1.1-setup.exe'
    url64bit       = $url  
    checksum       = 'EE590A66234C0F1DC57725173EB4C4D3C1BABF40C516B64E7D1604EB37F85909'
    checksumType   = 'sha256'
    checksum64     = $checksum
    checksumType64 = $checksumType
    silentArgs     = '/sp /silent /norestart'
  validExitCodes = @(0)
}
 
echo "If an older version of ShareX is running on this machine, it will be closed prior to the installation of the newer version."
ps sharex -ea 0| kill
 
Install-ChocolateyPackage @packageArgs`


That would be all that is required to maintain the package as far as I can tell. I've reached out to the Chocolatey Admins to see if they can assist in any way.

**Comment by Jarli01** [comment]
Hey @Jaex it looks like someone on the chocolatey team is able to pick up the project. The team there was curious if you wanted to pick it up to maintain it?

https://github.com/chocolatey/chocolatey-package-requests/issues/296

**Comment by gep13** [comment]
@Jaex I am one of the Chocolatey Admin Team, if you as the creator of the application wants to take ownership of the ShareX Chocolatey Package, then that is certainly something that we can make happen.  Do you have an account on chocolatey.org?  If so, let me know your username, and I can get you added to the package.

**Comment by ferventcoder** [comment]
@Jaex having you maintain the package gives you the option to put the software directly into the package as well if you choose to go that route. One of the things we've added more recently is a nice decision matrix that helps folks decide how to create those packages that comes when they run `choco new <pkgid>` - we'd definitely help you along that route if you need assistance. Awesome tool by the way!
