### ISSUE TITLE
Alert question after selecting Abort button.

### ISSUE THREAD

**Issue by marcin-jedynski** [ShareX/ShareX#3287]
Please that would be really nice if application would ask you for confirmation after clicking Abort button.
I just lost an hour of recording because I missed Stop button.

**Comment by Torubloo** [comment]
Firstly why the hell are you recording for 1 hour? if you are recording a game use OBS, Sharex was made for examples and showing off a few seconds of something

i don't see this needing to be added, again you shouldn't be recording for 1 hour

**Comment by marcin-jedynski** [comment]
Well you know some webinars take an hour...

**Comment by Mosrod** [comment]
You can use OBS to capture everything on your screen.

**Comment by lostallmymoney** [comment]
Maybe add a button that adds a button that asks for confirmation ?

**Comment by marcin-jedynski** [comment]
Keeping in mind that OBS takes some time to set it up there always will be people that don’t have this luxury. I think ShareX perfectly fills the gap and there’s no point of assuming that it should be only used for “short recordings”.  Besides even at 5 min length it may be annoying to lose your work just by accident.

**Comment by Torubloo** [comment]
it takes about 10 seconds to download, install, and setup OBS for screen recordings

**Comment by Torubloo** [comment]
ShareX is SIMPLY not made to make hour long screen recordings, it is for small demos for example the demo on main page of https://getsharex.com/, tho this one is a gif xD but this is what you would do with screen recordings

**Comment by Torubloo** [comment]
Adding a confirm box to stop or abort would simply slow things down for simple demo video tasks

**Comment by stuntguy3000** [comment]
Regardless of the length, I agree a confirmation dialog is probably a smart idea.

PR Inbound
