### ISSUE TITLE
Multiple file uploaders same service?

### ISSUE THREAD

**Issue by jarlave** [ShareX/ShareX#3288]
Hi,
is it possible (some conifg) to be able to have multiple nextcloud servers like it is possible with the file uploader for FTP/SFTP/FTPS? Because I recently switched from plain FTP to nextcloud and searching for a way to put text, images and other files in different folders like it is possible with FTP.
Uploaders already showing in a "tab view" maybe it is possible to add a + to duplicate one uploader

**Comment by Jaex** [comment]
No.

**Comment by jarlave** [comment]
Next time I just write nothing in the comment, just a waste of my time for only a "No." without an explanation why.

**Comment by Jaex** [comment]
How am I supposed to write "no" longer...
