### ISSUE TITLE
OCR doesn't work

### ISSUE THREAD

**Issue by Gettyk** [ShareX/ShareX#3289]
Hi, 

I am quite frequently using shareX OCR but today it's not working. I have updated ShareX and still OCR isn't working. 

I tried on another computer and there again it's not working. 

Any idea why?

I have created a quick task menu and I start the OCR from there

**Comment by Jaex** [comment]
OCR service we using was down before, now it is up.

**Comment by Gettyk** [comment]
Wahoo, that's super effective. Thanks a lot, it's working now! 
So when it doesn't work, it doesn't come from shareX and I simply have to wait for the OCR service to be up again?

**Comment by Jaex** [comment]
Yes we using that service for OCR.

**Comment by dlricher** [comment]
OCR not working for me, for some time now.
