### ISSUE TITLE
all edits on an image are lost when we right click

### ISSUE THREAD

**Issue by WiliTest** [ShareX/ShareX#3290]
I just updated to the last version (many awesome features added, thanks a lot!). The right click closes the editor without warning without saving (all edit are lost). It would be nice to escape with `escape`, the right click is too dangerous (I expected to see a context menu, but instead I lost my edits)

Off topic: I searched for a while if you implemented a way to move the image (I missed the noticed that appear when opening the editor). Then I discovered I could move the picture by clicking on the middle button (which is cool !). But it would nice to  add the standard shortcut: pressing `space`  (photoshop, adobe acrobat pro and many apps use it)

**Comment by Jaex** [comment]
I added both exit confirmation and scroll bars: #3220

**Comment by WiliTest** [comment]
Thanks but the right click still close the editor when no change has been done (which is annoying, especially to find the one that has been closed when many were opened).

 It's intuitive to right click to find hidden option when we look for something, or by mistake.
