### ISSUE TITLE
problem while saving

### ISSUE THREAD

**Issue by CookieGamerPT** [ShareX/ShareX#3293]
Hello, when taking a screenshot of Sharex and trying to save it to the desktop or any other folder (except the Downloads folder) I have a problem. A problem that does not happen when using PrintScr> paste the image into paint and then save.

In practice: I took a screenshot of imgur.com and tried to save it on my desktop and had the following error -> https://i.imgur.com/HTOXQyw.png

**Comment by trollmad3** [comment]
Is it possible if you can recreate the error but this time with english?

**Comment by CookieGamerPT** [comment]
when I changed the language, I had the following error:

![image](https://user-images.githubusercontent.com/26194848/38625800-a4ea6788-3d81-11e8-85ff-895a6eeb1698.png)

**Comment by trollmad3** [comment]
Your windows 10 does not allow ShareX to access "C:\Users\User\Documents\ShareX\Screenshots\2015-08" this folder, therefore Share X can do nothing about it.

**Comment by CookieGamerPT** [comment]
I understand. but you know how I can solve it? I have no idea what to do.

**Comment by trollmad3** [comment]
Its nothing with Share X. It something with your windows, therefore you can only fix it.

**Comment by CookieGamerPT** [comment]
problem solved.
solution: https://support.microsoft.com/en-us/help/4046851/windows-10-controlled-folder-access-windows-defender-security-center
I disabled this control that was blocking several applications from saving images and others.
