### ISSUE TITLE
FTPS "URL is Empty" Error

### ISSUE THREAD

**Issue by Danieu001** [ShareX/ShareX#3300]
Think I've discovered a bug regarding FTPS
I have a fairly standard setup with VSFTPD on my server and ShareX setup to connect to it over FTPS
It manages to connect and upload anything to the server into the right location but then returns the error "Url is Empty"

I've tried all the configurations i can think of in the URL path but it always seems to return with the error "Url is Empty" after uploading the file 100%. I also noticed some strange irregularities with the URL path when accessing the FTP Client window and right clicking on a file and copying the URL or Opening as i figured i'd experiment with that. 

For Example having it setup like this in this picture.
https://turtlebase.net/u/ShareX_2018-04-10_11-55-14.png
and then opening the client window and then right clicking on the same file above and copying the URL path returns "https://turtlebase.net/u/u/ShareX_2018-04-10_12-04-55.png" even tho append remote directory path is left unticked? 

Either way i just want to be able to use the SFTP option as was intended. 
It definitely connects to the server and uploads the file 100% but then for whatever unknown reasons returns with the error "Url is empty" no matter what URL path i specify.

**Comment by Jaex** [comment]
Did you check debug log is there any error?

**Comment by Danieu001** [comment]
This is all i get in the debug log
2018-04-10 12:05:05.670 - Upload started. Filename: ShareX_2018-04-10_12-04-55.png, Filepath: C:\Users\Daniel\Documents\ShareX\Screenshots\2018-04\ShareX_2018-04-10_12-04-55.png

2018-04-10 12:05:10.100 - Task failed. Filename: ShareX_2018-04-10_12-04-55.png, Errors:
URL is empty

**Comment by Danieu001** [comment]
[ShareX-Log-2018-04.txt](https://github.com/ShareX/ShareX/files/1892646/ShareX-Log-2018-04.txt)
Attached it for you to have a look at but i personally can't see anything in there out of the ordinary...

**Comment by Jaex** [comment]
I have one guess, maybe you don't have that uploader is selected in images, text and file drop down. Which means it could be using another uploader you have configured which URL path section is empty.

**Comment by Danieu001** [comment]
Hmmm?
https://turtlebase.net/u/2018-04-10_12-47-56.png

**Comment by Danieu001** [comment]
I'm able to atleast get the url copied automatically to my clipboard using the Advanced Task settings upload option "EarlyCopyUrl" and i also set "DisableNotifications" to True so i didn't get the annoying error popup. But that means i don't get the notification when its done and it doesn't save the URL to the history. 

Somethings definitely borked somewhere 🤔 
Let me know if you have any ideas or want me to try anything

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2018/04/ShareX_fdHNreYWir.png)

**Comment by Jaex** [comment]
I don't have FTP server therefore I'm unable to test it. But you are first person reporting this, so I wonder why other people don't have this issue.

Did you tried ShareX 12.0 is this issue still persists?

**Comment by Danieu001** [comment]
Well this time it uploaded as normal but theirs an actual error in the debug log
2018-04-10 15:24:22.984 - Upload started. Filename: a1dc95cdcc222f0c9bd1c00a8efd0816.png, Filepath: C:\Users\Daniel\Pictures\a1dc95cdcc222f0c9bd1c00a8efd0816.png
2018-04-10 15:24:47.137 - Exception:
System.Net.FtpClient.FtpCommandException: Failure reading network stream.
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2018-04-10 15:24:47.142 - Task failed. Filename: a1dc95cdcc222f0c9bd1c00a8efd0816.png, Errors:
System.Net.FtpClient.FtpCommandException: Failure reading network stream.
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
It can be to do with FTP server or maybe FTP library I'm not sure.

**Comment by Danieu001** [comment]
Hmmmm well when i get some time a little later I'll try narrowing it down for you by trying with ProFTPD server and with with both FTPS and FTP. 

Hopefully we can work out what it is.

**Comment by MasterCevin** [comment]
Is there any solution, because i still have this problem and i have to use FTP over SSL/TLS.

Kind regards
MasterCevin

**Comment by MasterCevin** [comment]
> I don't have FTP server therefore I'm unable to test it. But you are first person reporting this, so I wonder why other people don't have this issue.

Jaex I can provide you an FTPS Server (explicit), if you want to use it.
I am getting the same error ("URL is empty").

**Comment by SEKCobra** [comment]
I would like to contribute to this issue, as it has been stopping me from using ShareX for about a year. The issue occurs on FTPS connections, while FTP works fine. The files are uploaded, but ShareX still logs "URL is empty" and fails. If any additional logs or information is needed, I am happy to help.
