### ISSUE TITLE
Cursor hard to see on darker background

### ISSUE THREAD

**Issue by nmat** [ShareX/ShareX#3301]
The black cursor on area select is hard to see in darker areas. Especially when using hidpi.

Is it possible to have it read from monitor and adjust or change the cursor in anyway to have a better output then completely black when using dark theme?

**Comment by Torubloo** [comment]
What black cursor? you mean Windows cursor or the selection cursor?

**Comment by nmat** [comment]
I mean the windows selection cursor. the + cursor on pressing Ctrl+PrintScreen

I can't see it all and looks all black with no white in it at all. its just a dark black +

**Comment by nmat** [comment]
it could be the hidpi causing the rendering wrong but then shouldn't it rerender?

**Comment by nmat** [comment]
indeed this does seem to have to do with the hidpi. Using it in a non hidpi works just fine and shows the cursor correctly

**Comment by Jaex** [comment]
I have no idea how cursor can become black on high dpi.

**Comment by nmat** [comment]
it seems to be scaling the cursor. Causing it to be very very very small. So not sure why it would scale it down like that

**Comment by nmat** [comment]
https://github.com/ShareX/ShareX/commit/d599c16076d0857d4e76c71ccba181fc2a326bf6

Could be the solution for this. Since the cursor is being scaled. Once the release is out I can test it there.
