### ISSUE TITLE
Interested in using the app in our schools, but permissions. Argh.

### ISSUE THREAD

**Issue by rasqual** [ShareX/ShareX#3303]
Why full access to Drive? We can't do that for FERPA reasons.

Why not:
https://www.googleapis.com/auth/drive.file | Per-file access to files created or opened by the app. File authorization is granted on a per-user basis and is revoked when the user deauthorizes the app.

Heck, I evaluate apps for my own use with the same question: are they requiring the least intrusive permissions, or the most?

I realize the app is capable of retrieving files it hasn't created and that this is a _feature_. But permitting the app to run with an inability to access remote files it did not create would satisfy our security needs.  It's possible to offer both for approval but make this one optional:

https://www.googleapis.com/auth/drive | Full, permissive scope to access all of a user's files, excluding the Application Data folder. Request this scope only when it is strictly necessary.

Any chance of this changing?

**Comment by SupSuper** [comment]
ShareX needs at least readonly access to the whole drive to get the folders list. Is that acceptable by FERPA?

**Comment by guygg** [comment]
Yeah, this full permission request stops me from using the feature as well, as I don't give away full permissions to everything to an app that doesn't need it.  All I'm wanting to do is upload screen recordings & captures to my Drive account. The drive.file authorization scope should be just fine for that. That way, the app is only authorized to access files that it uploaded. I'm not 100% sure if drive.file will allow a folder to be created or not to put the uploads in, but I believe it will (iirc, I use a couple apps that do that with the proper drive.file authorization scope).

https://developers.google.com/drive/api/v3/about-auth

Granting read access to the entire Drive is major lack-of-data-security overkill for an app to just be able to upload files. One of the great things about some of the cloud providers and their different levels of permission scopes is that it's actually possible to do sandboxed security of data between applications and storage.

At the very least if the "drive.file" scope doesn't allow custom folder creation, just authorize for "drive.file" scope when enabling the Google Drive upload option and have the uploads just go into the root of Drive for the user. If they check the box to upload to a specific folder, then request authorization to the full "drive" scope.
