### ISSUE TITLE
[Request] Image annotation - Auto resize image canvas

### ISSUE THREAD

**Issue by theelectricsoul** [ShareX/ShareX#3304]
[Video](https://streamable.com/92i62)

### Problem
I love the "insert from screen" feature. But if I move a portion of the picture outside of the canvas, then the canvas has to be adjusted manually to see the hole picture. That takes time.

### Request
Option to let shareX image editor automatically adjust canvas size as needed.

Thanks :)

**Comment by Jaex** [comment]
I thought about auto resizing canvas too, but then there is gonna be people who want to insert image top of current image without canvas resize. So I need to find better solution. Also need to ask user is canvas should be extended vertically or horizontally too.

**Comment by Jaex** [comment]
I was thinking more like, this solution: https://jaex.getsharex.com/2018/04/NQJFIlkSJu.mp4

But that solution have flaw that when you move image back to original position still extra canvas stays there. Especially because I can't know is canvas created manually by user or image. So this gonna be problematic.

**Comment by theelectricsoul** [comment]
How about this.

**Auto canvas = True**
If the user is about to save the image or copy it into the clipboard, the auto crop tool kicks in and shrinks the canvas to fit the image.

**Comment by theelectricsoul** [comment]
This is how tools like bpmn.io or draw.io work. They constantly adjust canvas size/workspace

**Comment by Jaex** [comment]
I'm unable to find solution after so much thinking.

**Comment by theelectricsoul** [comment]
Relax my friend :)   lol ... and now waaaaatch
![image](https://user-images.githubusercontent.com/10260832/38731374-369a6eb4-3f1a-11e8-924a-55b8ce3f8bdc.png)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2018/04/1ae5rOKPo8.gif)

**Comment by Jaex** [comment]
I didn't like my previous solution.
This solution looks better: https://jaex.getsharex.com/2018/04/H9fIGS78gY.mp4
That dialog shows up when pasting image, inserting image file or inserting image from screen.

**Comment by theelectricsoul** [comment]
**A**
With your idea its more clicking and repositioning and maybe expanding the canvas manually. You never know what the final position of an inserted object will be. So as soon as the user has pasted the image the user might want to expand the canvas anyways.

**B**
Hmmm.. I'd argue that my the "Auto-cavas" option would interfere less with the workflow. You move an object(no matter which one) outside of the canvas... the canvas expands. Vica versa it shrinks as needed. And the user choses the exact position.

**Comment by theelectricsoul** [comment]
Or to put in in other words. This solution doesn't solve the problem :) I'd still have to expand the canvas, maybe less often.

**Comment by theelectricsoul** [comment]
And you've closed the ticket ?  :/    ... uhm....      well. Should I open a new ticket if I still have a problem...? Probably.

**Comment by chad-exc** [comment]
I second looking into this again. I'm trying to make notes on a small/narrow image, but I need the image to get bigger to keep the notes, as I'm leaving the notes outside the canvas area, so they don't cover up the part of the image I'm discussing in the note.

**Comment by dat-Koriel** [comment]
> I am not sure ... there has not been anything done on this, right?
> 
> Coming from the windows cut and sketch tool, which has a very intuitive automatic canvas when you add stuff outside of the image boundaries I was stunned not finding this basic feature in a such overwhelmingly feature-rich app like ShareX
> 
> So what I want (and also strongly need) is an automatic expansion as soon as you actively draw something or put sicker outside of the current image canvas in the editor. whatever you draw should be part of the image without thinking about it. (Basically just like the inbuild windows tool does it) this includes also a little extra boundary on top of the outer edge of the drawing i think. just looks better if the text does not stop exactly at the image border.
> 
> Other elements which are just obfuscating (pixelate, blur) are not required to expand the canvas
> 
> do not just cut away the smileys i put on the corner of my images ... it hurts their feelings

Id LOVE for this too, please! 

Usually I'll just screenshot the very part of the screen where an element is, and then I'd like to annotate outside the boundary, and for the Image Editor to automatically expand the canvas to fit it all.

Pretty please? :')
Manually resizing the canvas afterwards is kind of painful.
