### ISSUE TITLE
Allow an uploader to support all five "upload types" at once

### ISSUE THREAD

**Issue by popey456963** [ShareX/ShareX#3306]
At the moment, you seem to have to pick between:

 - Image / Text / File uploader
 - URL shortener / URL sharing service

The former all require `File form name` to be implemented, the latter require it not to be implemented.  If we altered the latter so that it only ignored the field, instead of requiring it not to be filled a single uploader would be able to support all five upload types at once.

**Comment by popey456963** [comment]
Echoing my previous comment

> Inclined to say that just because an issue is fairly complex to implement for less gain doesn't mean it should be closed.

**Comment by Jaex** [comment]
"File form name" already ignored by url shortener and url sharing services.

**Comment by popey456963** [comment]
Oh neat!  In which case this problem seems to have been solved?

Do you happen to have an example .sxcu file which can handle all five methods at once?

**Comment by Jaex** [comment]
I never seen someone using single sxcu for all uploaders. Also it would be inefficient because `$input$` would be supplied twice for text uploader.

**Comment by popey456963** [comment]
Could we clarify this issue then to be resolved when you can efficiently add all 5 upload types to a single SXCU.  I imagine no-one has done it yet due to that inefficiency.

**Comment by Jaex** [comment]
What you mean clarify? It is literally not possible.
