### ISSUE TITLE
How to record videos in ShareX(not .gif)?

### ISSUE THREAD

**Issue by KulaGGin** [ShareX/ShareX#3308]
I don't have extension container option in screen recording options. Here's a screen from some article:
![media_1421647008092 1](https://user-images.githubusercontent.com/16989713/38769060-92926a00-4005-11e8-8684-dab09f7487f9.png)

And here's screen from my ShareX:
![sharex_2018-04-14_17-04-54](https://user-images.githubusercontent.com/16989713/38769069-a9f117a0-4005-11e8-9a3c-1cbbf247c5d7.png)

I can record .gif just fine.

How do I record .avi, .mkv or .mp4 videos with sound?

**Comment by stuntguy3000** [comment]
So close.

You see where it says _Audio Source_

Click on that dropdown, select your source, done.

**Comment by KulaGGin** [comment]
Em, I already had it set in the past, and I set it just to test, it still records .gif even with audio source set:
![2018-04-14_18-10-09](https://user-images.githubusercontent.com/16989713/38769641-eafdefee-400e-11e8-9fe4-81f8bb0b361a.gif)

**Comment by stuntguy3000** [comment]
![image](https://user-images.githubusercontent.com/1522389/38769653-8a4abbfa-4045-11e8-92ca-ae2cc3d6cf41.png)

Are you selecting the right screen recording option?

**Comment by KulaGGin** [comment]
Ah, yes, thanks! I just have it on shortcut, like this:
![sharex_2018-04-14_18-15-00](https://user-images.githubusercontent.com/16989713/38769683-74ae4a9a-400f-11e8-8271-d8f7df337892.png)

And I forgot that there were different options to record. It now records .mp4 even with no audio source when I choose Screen recording, just as it is supposed to.

Another quick question: is there a way to record .mkv instead of .mp4? This article says it is possible but I don't think it explains how to record .mkv:
https://sublimelms.com/docs/Video-App-Guide/Video%20App/How_to_record_screen_with_voice_using_Sharex_.html

**Comment by WiliTest** [comment]
To change the video format (Gif vs mp4) it's here (in hotkey settings>click the one you want>:)
![2021-06-06_21-31-48](https://user-images.githubusercontent.com/24194840/120937603-b4b28500-c70e-11eb-8e42-97b0b6d4851d.png)
