### ISSUE TITLE
Settings online save and sinhronize

### ISSUE THREAD

**Issue by BofEmptiness** [ShareX/ShareX#3310]
Hello,

Can you please add online setting save and sinhronize? Maybe with file in google drive folder.

**Comment by matthewburnett** [comment]
Install google drive to your computer and drag the sharex folder to it, then set sharex to read it from there.

**Comment by BofEmptiness** [comment]
@matthewburnett i'm not sure that undarstand this method. How can i use sharex from different PC (work and home) with same settings and if i change something at work, it's will change home to. What do you mean "set sharex to read it?".

**Comment by BofEmptiness** [comment]
I need to sinhronize only setting, not files.
