### ISSUE TITLE
Using bat file as on-off timer for Sharex Screen Recorder

### ISSUE THREAD

**Issue by Michaelk001** [ShareX/ShareX#3311]
I want to set a on-off timer for Sharex.  I am not a programmer. Will this bat file work? If not what can I do to enable an on-off timer?

@echo off
set /p time_h="Enter Recording timeout(H): "
set /p time_m="Enter Recording timeout(M): "
set /a result_h = %time_h% * 60 * 60
set /a result_m = %time_m% * 60
echo %result_h%
echo %result_m%
set /a time = %result_m% + %result_h% 
echo %time%
timeout /t 5 /nobreak
start "" "C:\Program Files\Sharex\sharex.exe -StartScreenRecorder"
timeout /t %time% /nobreak
start "" "C:\Program Files\Sharex\sharex.exe -autoclose" 

Thanks
Michael

**Comment by stuntguy3000** [comment]
Have you tried running it?

**Comment by Jaex** [comment]
You should not close ShareX, it won't stop recording. `-ScreenRecorder` stops recording.

**Comment by Michaelk001** [comment]
Got it. That is what I did in the bat file.

 

@echo off

set /p time_h="Enter Recording timeout(H): "

set /p time_m="Enter Recording timeout(M): "

set /p time_s="Enter Recording timeout(S): "

set /a result_h = %time_h% * 60 * 60 

set /a result_m = %time_m% * 60 

set /a result_s = %time_s%

echo %result_h%

echo %result_m%

echo %result_s%

set /a time = %result_s% + %result_m% + %result_h% 

echo %time%

timeout /t %time% /nobreak

start "" "C:\Program Files"\Sharex\sharex.exe -StartScreenRecorder

**Comment by Michaelk001** [comment]
OOPS,

 

Now corrected.

 

@echo off

set /p time_h="Enter Recording timeout(H): "

set /p time_m="Enter Recording timeout(M): "

set /p time_s="Enter Recording timeout(S): "

set /a result_h = %time_h% * 60 * 60 

set /a result_m = %time_m% * 60 

set /a result_s = %time_s%

echo %result_h%

echo %result_m%

echo %result_s%

set /a time = %result_s% + %result_m% + %result_h% 

echo %time%

timeout /t %time% /nobreak

start "" "C:\Program Files"\Sharex\sharex.exe -ScreenRecorder
