### ISSUE TITLE
Screen recording region snapping disables after recording

### ISSUE THREAD

**Issue by Spown** [ShareX/ShareX#3312]
When trying to start a new screen recording session (after completing another one), region snapping to a window gets broken - it snaps to the entire screen. I still can define a custom region via mouse selection, but to make it start snapping to the window/window subregions I have to initiate a simple screenshot - then the snapping starts to work again (in most cases)

**Comment by Jaex** [comment]
I noticed few times snapping not worked too but couldn't manage to reproduce it. It happens very rarely and I'm not sure what causing it.

**Comment by Jaex** [comment]
I already tried it and unable to reproduce it.

**Comment by Spown** [comment]
``¯\_(ツ)_/¯``
Well, at least you know this bug exists... It's a start.

**Comment by stuntguy3000** [comment]
@Spown More info please:

What OS do you use?
Any special software?
What hardware do you run?

**Comment by Jaex** [comment]
@Spown we can't know is it bug or not. There is situations where invisible fullscreen window can stay top of everything and even when I'm checking for not visible windows those are not counted because they using transparency to make them invisible etc. Especially because snapping codes not changed for long years I think.

**Comment by Spown** [comment]
@stuntguy3000 Win10x64, AMD CPU, AMD Radeon 6870HD... Dunno what one can call special soft, but the window I was capturing - Bluestacks 3.

@Jaex the thing is if I encounter this behavior - I would cancel screen capture and I would try to take a normal region screenshot - and it would always snap to the window. However if I cancel the screenshot and try to initiate a capture - it still would snap to the entire screen. So the scenario with a transparent frame/invisible fullscreen seems to be highly unlikely. If I go with screenshot task till the end - it would likely "cure" the screen capture snapping. In about 5 times witnessing this bug/not a bug 4 times a screenshot would help and 1 time it would not.

**Comment by stuntguy3000** [comment]
Does it happen when you're not trying to play android games?

**Comment by Spown** [comment]
@stuntguy3000 yes. I've just captured a couple of seconds of a Thunderbird window. Then tried it again and it snapped to the entire screen. BlueStacks is not even running (not even a service in the background).

**Comment by stuntguy3000** [comment]
Do you have any way to show this behavior?

Even with another program like OBS

**Comment by Spown** [comment]
>Sounds like this is an issue ShareX cannot solve. Good luck.
>request close, invalid.

Me being unable to record a repro video with another util is not the issue much less an issue ShareX should be fixing. That doesn't mean the OP issue shouldn't be fixed. Please do not invent reasons to ignore the issue. If you want to pretend it doesn't exist - just do it.

**Comment by stuntguy3000** [comment]
We're not ignoring it nor pretending it doesn't exist. We can't replicate it, and you haven't given us steps to reproduce it/demonstrate a bug with ShareX.

**Comment by Spown** [comment]
Doesn't really make it invalid...

**Comment by stuntguy3000** [comment]
It's more Can't Fix than Invalid, but again, without steps to reproduce it...

**Comment by Spown** [comment]
What would a video change? That I am not a lair? It would've shown exactly the same thing I have described 2 times already in a text form (with steps to repro). Having seen this theoretical video wouldn't make it repro on your machine...

But oh well, it's actually not a fatal bug. Close it if you want.

**Comment by Spown** [comment]
Ok, I've recorded it with my phone. Need some time till its uploaded and playback ready.

**Comment by Spown** [comment]
https://www.youtube.com/watch?v=j-FixXXGB7Q

**Comment by MorrisonGamer** [comment]
Well, like I mentioned in #3314 region snapping doesn't work, but for my case, it's for screenshot, never tested screen recording. And the guy here says region snapping works with screenshots, so I doubt we have the same problem, but for a bit more of a reference, it's broken since 12.1.0. When I downgraded to 12.0.0, it works just fine.

**Comment by FireyCirno** [comment]
I believe I had this issue (screen recording region being different when the recording was output), and I resolved it by uninstalling screen-capture-recorder and reinstalling it via ShareX. I apologize for the massive necropost.
