### ISSUE TITLE
How to let google drive overwrite the file with the same name?

### ISSUE THREAD

**Issue by hien89** [ShareX/ShareX#3317]
Hi ShareX developers!
I am using ShareX to capture the screen with interval 60s/1 screenshot. After the screen is captured, it will be uploaded to Google Drive. The feature I want is that there will be an option that  let google drive overwrite the old file (or all files in that folder) instead of keep save as a new file (although all file have the same name). Is it possible? (sorry my English isn't good)

**Comment by Jaex** [comment]
In here if you use static text:

![](https://jaex.getsharex.com/2018/04/ShareX_JPslrVB3IJ.png)

It should use same name for each file.

**Comment by hien89** [comment]
Hi Jaex,
I had already tried that (put "screenshot" to all fields). But when the file uploaded to Google Drive, it just create a new file on Google Drive and won't delete the old file that has the same name.
[https://i.imgur.com/gUW6lzy.png](url)

**Comment by hien89** [comment]
Hi Jaex,
I had already tried that (put "screenshot" to all fields). But when the file uploaded to Google Drive, it just create a new file on Google Drive and won't delete the old file that has the same name.

**Comment by hien89** [comment]
Yes, I have resolved the issue by let ShareX to call the google api script to delete old pictures after the image is uploaded.

**Comment by stuntguy3000** [comment]
@tumGER It's actually a feature of Google Drive.

Yep..

**Comment by IMJ355** [comment]
@hien89 it's actually 1 of the feature of google drive... when you upload the file with same name, it will replace the file automatically.

**Comment by BoJio976** [comment]
> Yes, I have resolved the issue by let ShareX to call the google api script to delete old pictures after the image is uploaded.

Hi, may i know whats is the API Script ? i also need that to overwrite my image
