### ISSUE TITLE
Recording meetings

### ISSUE THREAD

**Issue by ACE350** [ShareX/ShareX#3319]
I must document a lot of meetings with engineers of all types of disciplines. Quite often something will be discussed that I cannot document properly without further information, so I ask questions. I use ShareX to record my meetings and the presentations. My computer died after many years and I had to install ShareX on a new computer. I cannot remember the custom command I used to capture my meetings (video, speaker audio, microphone audio). I know this is simple but I cannot figure it out again. I remember I have to specify the "virtual-audio-capturer" and my headset but I cannot remember the flags that make this work. I currently have the following:
`-y -rtbufsize 100M -f dshow -framerate $fps$ -i video="screen-capture-recorder":audio="Headset Microphone (Plantronics Blackwire 325.1)" -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a aac -strict -2 -ac 2 -b:a 128k "$output$"`

**Comment by stuntguy3000** [comment]
You shouldn't need to set any flags to record audio. You mention the audio capture device. What is the issue?

**Comment by notcammy** [comment]
You shouldn't be using ShareX for this kind of purpose.

**Comment by ACE350** [comment]
@stuntguy3000, I am recording meetings and need to capture the audio from the meeting and microphone.
@notcammy, I know there are probably more suitable apps out there to do this, but this is the only one I had available to me at the time, and I am not sure if I can install anything else on my computer. I am open to suggestions though. If there is something else I should be using that can capture my meeting and allow me to select the screen real estate to record, I am game to try.

**Comment by Jaex** [comment]
I don't recommend ShareX for long recordings. You can use: https://obsproject.com/

**Comment by xumix** [comment]
I've found a way to add secondary stream: add this line to advanced ffmpeg arguments replacing with your mic name
`-f dshow -i audio="Microphone (HD Webcam C310)" -filter_complex amix=inputs=2:duration=longest`

**Comment by deepesharora** [comment]
@ACE350  did you ever get this working...i'm looking to do the exact same thing and would appreciate your help if you have solved this already
