### ISSUE TITLE
Please explain auto increment pad with {n}

### ISSUE THREAD

**Issue by davewilton** [ShareX/ShareX#3321]
Would you please be able to explain/document the pad with {n}? I'd like to pad with leading zeros to end up with a file name such as IMG_001 which it appears to say it will do but I can't work it out.

![image](https://user-images.githubusercontent.com/2278405/38966905-e5b3ba02-43c7-11e8-9372-b85f3ebe0ccd.png)

Thanks, I really like the tool. Very powerful

**Comment by Jaex** [comment]
Use `%i{3}`

**Comment by davewilton** [comment]
Perfect! Stupid I tried that but the wrong way round {3}%i

**Comment by AndyDaSilva52** [comment]
It would be great if has an example of use in the application
