### ISSUE TITLE
[Enhancement] Add command pallete

### ISSUE THREAD

**Issue by PhmNgocNghia** [ShareX/ShareX#3322]
Visual Studio code, google chrome developer tool... have a feature call command palette. It's feature that help user quicky navigate to their function without look the UI or remember hotkey. For example i want to take screen shot of a region or maybe checkout some edit image i can search for the function i need without look up for it in the UI. 

Type crop in the command palete for quickly natvigate for crop image function. In window desktop instead of remember the hotkey to take screenshoot of window i can quickly use some hotkey to open command palete type in something like window screen shoot. Very quick, no hotkey, no hassle

---------------------
This is about edit image feature

When was edit image. If i click right click then the editor will close and i lose all of my change.
This is so  anoying. Also about UX : The editor shouldn't close if user save image.

That is my idea, please consider add it.

**Comment by Jaex** [comment]
I'm not planning to add command palette. You can configure hotkeys for any actions you need.

> If i click right click then the editor will close and i lose all of my change.
This is so anoying.

I added confirmation message box for next release.

>  Also about UX : The editor shouldn't close if user save image.

This option:

![](https://jaex.getsharex.com/2018/04/chrome_osbtdingy0.png)
