### ISSUE TITLE
Start button for custom region recordings

### ISSUE THREAD

**Issue by ehmprah** [ShareX/ShareX#3323]
I love ShareX a lot, but what prevents me from really adopting it: I'm missing a start button for custom region recordings. I'd like to set the region, do some other stuff and then start the recording in time. Could you add that?

**Comment by Jaex** [comment]
Uncheck this option:

![](https://jaex.getsharex.com/2018/04/ShareX_TpmquOOg5i.png)

**Comment by ehmprah** [comment]
Aw, I didn't get that. Thank you so much! :-)
