### ISSUE TITLE
New editor

### ISSUE THREAD

**Issue by MadCompie** [ShareX/ShareX#3326]
A new editor ... it's not Greenshot but the functionality remains somewhat the same...
Here some issues about this new interface:
- missing the arrow button to select the objects ; it works without it but is somewhat confusing
- while open, CPU goes +15% (on Windows 10)

Nevertheless a great tool!

**Comment by gpion** [comment]
> while open, CPU goes +15% (on Windows 10)

On my system (quad core CPU) it monopolizes a full core for itself (25% total).
And even when in background  (iconified).
![ShareX CPU graph](https://i.imgur.com/2Oydcpl.png)

**Comment by baudav** [comment]
same on windows 7. high cpu usage! very bad for laptop on battery. 60MB memory and hisrtory not work for image.
![screenshot](https://i.imgur.com/0AN7DqG.png)

**Comment by baudav** [comment]
pas pret d'etre corrigé alors cette utilisation abusive de CPU! je reste sur shareX11.4.1
not ready to be corrected, this strong misuse of CPU. stay on 11.4.1

**Comment by Jaex** [comment]
Arrow button to select objects added now: https://github.com/ShareX/ShareX/issues/3769#issuecomment-482924421
