### ISSUE TITLE
What happened to the ability to highlight things like this?

### ISSUE THREAD

**Issue by pharan** [ShareX/ShareX#3336]
There used to be a feature that allowed me to highlight parts of an image by darkening or lightening the parts except a rectangle area. But it seems to be gone. Was that part of the Greenshot editor that was removed?

If it's removed, can I request it be added?

![fasfasg](https://user-images.githubusercontent.com/1911082/39223127-cb6de596-4872-11e8-8b24-a58ae2e63123.png)
(Done in Photoshop here. Kind of annoying if you have to do a lot of these.)

**Comment by Jaex** [comment]
Duplicate of https://github.com/ShareX/ShareX/issues/3041
