### ISSUE TITLE
ShareX crashes after screenshot

### ISSUE THREAD

**Issue by lipkau** [ShareX/ShareX#3338]
Hi.

I have been experiencing this for a while now:

My ShareX crashes right after taking a screenshot. This normally happens after my 2nd screenshot after opening ShareX.

Here is the log:

> ```
> 2018-04-26 09:33:02.072 - ShareX 12.1.1
> 2018-04-26 09:33:02.074 - Build: Release
> 2018-04-26 09:33:02.074 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
> 2018-04-26 09:33:02.074 - Personal path: C:\Users\olive\Documents\ShareX
> 2018-04-26 09:33:02.074 - Operating system: Windows 10 Pro
> 2018-04-26 09:33:02.075 - Flags: SilentRun
> 2018-04-26 09:33:02.121 - ApplicationConfig load started: 
> C:\Users\olive\Documents\ShareX\ApplicationConfig.json
> 2018-04-26 09:33:02.577 - ApplicationConfig load finished: C:\Users\olive\Documents\ShareX\ApplicationConfig.json
> 2018-04-26 09:33:02.579 - UploadersConfig load started: C:\Users\olive\Documents\ShareX\UploadersConfig.json
> 2018-04-26 09:33:02.579 - MainForm init started.
> 2018-04-26 09:33:02.682 - UploadersConfig load finished: C:\Users\olive\Documents\ShareX\UploadersConfig.json
> 2018-04-26 09:33:02.684 - HotkeysConfig load started: C:\Users\olive\Documents\ShareX\HotkeysConfig.json
> 2018-04-26 09:33:02.712 - HotkeysConfig load finished: C:\Users\olive\Documents\ShareX\HotkeysConfig.json
> 2018-04-26 09:33:02.831 - MainForm init finished.
> 2018-04-26 09:33:02.956 - Startup time: 1022 ms
> 2018-04-26 09:33:02.958 - CommandLine: silent
> 2018-04-26 09:33:02.966 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
> 2018-04-26 09:33:02.966 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
> 2018-04-26 09:33:02.966 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
> 2018-04-26 09:33:02.966 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
> 2018-04-26 09:33:02.966 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF) using custom region, Job: ScreenRecorderGIF
> 2018-04-26 09:33:02.967 - HotkeyManager started.
> 2018-04-26 09:33:02.968 - WatchFolderManager started.
> 2018-04-26 09:58:07.563 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
> 2018-04-26 09:58:07.600 - Executing: Capture region
> 2018-04-26 09:58:12.529 - Task in queue. Job: Job, Type: Image, Host: 
> 2018-04-26 09:58:12.535 - Task status: Preparing
> 2018-04-26 09:58:12.562 - Image copied to clipboard.
> 2018-04-26 09:58:12.575 - Image saved to file: C:\Users\olive\Documents\ShareX\Screenshots\2018-04\vivaldi_2018-04-26_09-58-12.png
> 2018-04-26 09:58:12.586 - Task completed. Filename: vivaldi_2018-04-26_09-58-12.png, Duration: 46 ms
> 2018-04-26 09:58:12.625 - ApplicationConfig save started: C:\Users\olive\Documents\ShareX\ApplicationConfig.json
> 2018-04-26 09:58:12.631 - HotkeysConfig save started: C:\Users\olive\Documents\ShareX\HotkeysConfig.json
> 2018-04-26 09:58:12.631 - UploadersConfig save started: C:\Users\olive\Documents\ShareX\UploadersConfig.json
> 2018-04-26 09:58:12.829 - UploadersConfig save successful: C:\Users\olive\Documents\ShareX\UploadersConfig.json
> 2018-04-26 09:58:12.867 - HotkeysConfig save successful: C:\Users\olive\Documents\ShareX\HotkeysConfig.json
> 2018-04-26 09:58:12.888 - ApplicationConfig save successful: C:\Users\olive\Documents\ShareX\ApplicationConfig.json
> 2018-04-26 09:58:48.246 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
> 2018-04-26 09:58:48.246 - Executing: Capture region
> 2018-04-26 09:58:58.027 - Task in queue. Job: Job, Type: Image, Host: 
> 2018-04-26 09:58:58.027 - Task status: Preparing
> 2018-04-26 09:58:58.030 - Image copied to clipboard.
> 2018-04-26 09:58:58.042 - Image saved to file: C:\Users\olive\Documents\ShareX\Screenshots\2018-04\vivaldi_2018-04-26_09-58-58.png
> 2018-04-26 09:58:58.042 - Task completed. Filename: vivaldi_2018-04-26_09-58-58.png, Duration: 15 ms
> 2018-04-26 09:58:58.071 - ApplicationConfig save started: C:\Users\olive\Documents\ShareX\ApplicationConfig.json
> 2018-04-26 09:58:58.077 - UploadersConfig save started: C:\Users\olive\Documents\ShareX\UploadersConfig.json
> 2018-04-26 09:58:58.081 - HotkeysConfig save started: C:\Users\olive\Documents\ShareX\HotkeysConfig.json
> 2018-04-26 09:59:01.838 - UploadersConfig save successful: C:\Users\olive\Documents\ShareX\UploadersConfig.json
> 2018-04-26 09:59:01.891 - HotkeysConfig save successful: C:\Users\olive\Documents\ShareX\HotkeysConfig.json
> 2018-04-26 09:59:01.895 - ApplicationConfig save successful: C:\Users\olive\Documents\ShareX\ApplicationConfig.json
> ---- here is where it crashed ----
> 2018-04-26 10:04:13.381 - ShareX 12.1.1
> ```

### Environment

**OS** : Windows 10 Pro
**ShareX** : 12.1.1

**Comment by Jaex** [comment]
That log not shows any error.

**Comment by lipkau** [comment]
I know. but that's what is in the log.

Here is a capture of my screen (this took 3 screenshot to creash):
https://www.dropbox.com/s/x6v1zzq2hu7rc3s/ScreenCaptureProject1.mp4?dl=0

**Comment by Jaex** [comment]
Mainly when there is no .NET exception that means problem is not to do with ShareX.

**Comment by lipkau** [comment]
Any tips on how I can debug this?

**Comment by lipkau** [comment]
I found this in the event viewer:

```xml
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-04-26T09:00:06.318087400Z" /> 
  <EventRecordID>28196</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-MF87NG8</Computer> 
  <Security /> 
  </System> <EventData>
  <Data>Application: ShareX.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: exception code c0000005, exception address 00007FFB3F4C34F0</Data> 
  </EventData>
  </Event>
```

**Comment by stuntguy3000** [comment]
If I can read, you're running an old .NET version.

Try giving this a shot:
https://www.microsoft.com/en-us/download/details.aspx?id=56116

**Comment by lipkau** [comment]
After installing yesterday' s `Windows 10 April 2018 Update`, It seems to be fixed
(as it updated the .NET version)

I will reopen if I am mistaken.
Thank you for the support

**Comment by JamieH** [comment]
👍 I'm also getting a crash with `MMDevApi`

**Comment by JamieH** [comment]
So far I've managed to recreate it by unplugging/plugging my USB headset a couple of times

**Comment by Anton04** [comment]
I can confirm that ShareX stops crashing once I go into task settings and disable the sound effects when taking screenshots.

**Comment by macchky** [comment]
Recently I encountered same issue. And recently I installed ASUS Sonic Studio and ASUS Sonic Radar.

I think Sonic stuff interfere MMDevApi and ShareX.

**Comment by jekeam** [comment]
A similar problem, it constantly crashes after the screenshot...
