### ISSUE TITLE
[UI] Hyperlink cursor has a legacy style

### ISSUE THREAD

**Issue by Philosoph228** [ShareX/ShareX#3341]
I think this kind of trifles isn't necessary, but it would be better if cursor have modern look as rest part of application and OS.
![image](https://user-images.githubusercontent.com/13369540/39352957-bc108c12-4a1f-11e8-809f-06a0cc397368.png)
![image](https://user-images.githubusercontent.com/13369540/39353359-d53cd410-4a20-11e8-8897-5204a3f516e7.png)

**Comment by stuntguy3000** [comment]
Minus anti aliasing and gradient, what's the difference?

**Comment by RedMser** [comment]
> Minus anti aliasing and gradient, what's the difference?

On themes with custom cursors, the link cursor from the theme does not get used. In case of something like black or inverted cursors, this is pretty noticeable.

This behavior only happens on the `LinkLabel` control. The [LinkLabel2](https://wyday.com/linklabel2/) control attempts to fix this inconsistency (as well as others).

**Comment by sylveon** [comment]
The problem with LinkLabel2 is that it only fixes link labels. Picture boxes with links and rich text boxes will still use the old style. I created a pull request which changes the inner Cursors.Hand field of WinForms, so it fixes this without having to overload each control using it.
