### ISSUE TITLE
QuickTaskMenu AutoClose Bug

### ISSUE THREAD

**Issue by jswon7942** [ShareX/ShareX#3343]
#QuickTaskMenu.cs
-----------------------------------------------------------------------
ContextMenuStrip cms = new ContextMenuStrip()
        {
            Font = new Font("Arial", 10f),
            AutoClose = false
        };
-----------------------------------------------------------------------
I will ShareX cms close that auto close to start capture action when hotkey(region capture setting key) press.

But, "AutoClose = true" is not working or disorder working.

I have the this problem.

Give me the best guide or bug fix, please.

**Comment by stuntguy3000** [comment]
Sorry?

Can you please explain your issue with steps on how to reproduce it.
