### ISSUE TITLE
Recording wont work

### ISSUE THREAD

**Issue by KatiePortmann** [ShareX/ShareX#3353]
I am unable to use screen recorder. this error comes up: 
![image](https://user-images.githubusercontent.com/38830979/39404616-81304796-4bea-11e8-9793-5a911a0c0b9f.png)

**Comment by Jaex** [comment]
I can't see your image.

**Comment by KatiePortmann** [comment]
11.9.1

Warmest regards,




[cid:image001.png@01D1996F.A0167160]<http://www.ezyvet.com/>

Katie Portmann  [ IMPLEMENTATIONS MANAGER ]
ezyVet – Beautiful Veterinary Software

MOBILE +64 27 517 5613  NZ 0800 EZYVET  AUSTRALIA 1300 EZYVET
USA 18444 EZYVET  UK +44 2035149301  INTERNATIONAL +64 9 280 6210
www.ezyvet.com<http://www.ezyvet.com/>


Find us online

[cid:image002.png@01D1996F.A0167160]<https://www.facebook.com/ezyvetveterinarysoftware>[cid:image003.png@01D1996F.A0167160]<https://twitter.com/ezyvet>[cid:image004.png@01D1996F.A0167160]<http://www.instagram.com/ezyvet/>

**Comment by Jaex** [comment]
You are using old version. That issue fixed in latest version.
