### ISSUE TITLE
short freeze on start

### ISSUE THREAD

**Issue by philiparvidsson** [ShareX/ShareX#3354]
# how to reproduce

1. start sharex

# expected results

sharex starts immediately

# actual results

sharex starts, show busy cursors and freezes for ~2 seconds, then returns to normal

likely cause seems to be news download (because the + next to news appears after the delay). auto check for updates is disabled.

**Comment by Jaex** [comment]
Download actually happens in new thread. But some reason this method slows it down between 10-50ms per added item: https://github.com/ShareX/ShareX/blob/master/ShareX/Controls/NewsListControl.cs#L146
I'm not sure what causing that increasing slow.

**Comment by philiparvidsson** [comment]
considering the increased time for each added item, I'd say it's some kind of layout update issue.

**Comment by Jaex** [comment]
Indeed if I suspend layout before add items and then resume it then test results is:

```2.7893 milliseconds.
0.327 milliseconds.
0.2848 milliseconds.
0.3158 milliseconds.
0.3435 milliseconds.
0.3031 milliseconds.
0.2823 milliseconds.
0.2724 milliseconds.
0.3009 milliseconds.
0.4514 milliseconds.
```

**Comment by philiparvidsson** [comment]
to be honest, I'd prefer to see news removed entirely and just replaced with a link to some website. few people care to read the news every single time the program is started. or at least provide an option to disable it.

**Comment by Jaex** [comment]
I added news for emergency needs too. For example this news was pretty important and all users must read it:

![](https://jaex.getsharex.com/2018/04/ShareX_ypIQBkq9ob.png)

**Comment by philiparvidsson** [comment]
I see. perhaps `-silent` could disable news loading?

**Comment by Jaex** [comment]
I don't see any reason why loading news once at startup should create any issues to users when layout issue is fixed.
