### ISSUE TITLE
'Shared Folder' destination not working as of 11.8

### ISSUE THREAD

**Issue by Steamlined** [ShareX/ShareX#3362]
When updating ShareX to the latest version, the Shared Folder destination stopped working. I have checked the settings and they are all the same as they were in 11.8, where they work without issue. On the latest version, however, any uploads show an error box, and the upload itself fails.

[Screenshot here](https://steamlined.co.uk/files/ShareX_30-04-18_14-47-55.png)
(System.IO.DirectoryNotFoundException)

**Comment by Jaex** [comment]
Shared folder codes not changed past 2 years: https://github.com/ShareX/ShareX/commits/master/ShareX.UploadersLib/FileUploaders/SharedFolderUploader.cs

**Comment by Steamlined** [comment]
Well, I went back through the updates from 11.8 and manually installed them, stepping up one version each time until the latest and now it's working without issue, so, consider me stumped and consider the issue closed.
