### ISSUE TITLE
Keep editor opened after copying

### ISSUE THREAD

**Issue by Dubz** [ShareX/ShareX#3365]
I'd like it if the image editor dialog would stay open after making changes. Sometimes I want to copy an image as well as continue its task, but I am unable to since the image closes after clicking on copy.

I haven't tried it with saving or printing, but I'd imagine the same results as well.

**Comment by Jaex** [comment]
Uncheck this:

![](https://jaex.getsharex.com/2018/05/ShareX_mkhT8ea4QU.png)
