### ISSUE TITLE
Will not copy to clipboard

### ISSUE THREAD

**Issue by kimchaee** [ShareX/ShareX#3366]
Won't copy url to clipboard after capturing. I even chcked the open url option as well and it won't open url either.

**Comment by stuntguy3000** [comment]
What item are you trying to open?

Sounds like it _doesn't_ have a URL.

**Comment by kimchaee** [comment]
I'm just trying to take regular screenshots. I just got a new pc today was working fine on my old one. Instead of giving me a URL on imgur like it did previously I just get files now.

**Comment by stuntguy3000** [comment]
![image](https://user-images.githubusercontent.com/1522389/39509512-ad05845c-4e25-11e8-95a6-ebccf572dff6.png)

Is this set?

**Comment by kimchaee** [comment]
It wasn't. Just checked it though and still does not work.

**Comment by kimchaee** [comment]
I even copied my settings over "the sharex folder in documents" from my old pc over and it still won't work so I have no idea what's wrong.
