### ISSUE TITLE
[Feature Request] Add Eyedropper to Color Picker

### ISSUE THREAD

**Issue by gnosticJade** [ShareX/ShareX#3374]
Pretty straightforward -- back in the older versions of ShareX before the Greenshot annotator was removed, the [color picker had the eyedropper tool](https://i.imgur.com/hff9Fu9.png). In the new image editor, [there is no eyedropper in the color picker](https://i.imgur.com/ggE3ufO.png). If you go to the Tools > Color Picker, however, [there _is_ an eyedropper tool](https://i.imgur.com/tNia0bV.png). Could we get the eyedropper added to the image editor's color picker?

**Comment by Jaex** [comment]
One of the reason why I was not added eyedropper to all color pickers because it using region capture to color pick from screen. And opening full screen region capture inside fullscreen region capture can be problematic.

**Comment by Jaex** [comment]
I only added screen color picker to image editor now so it won't run when color picker opened from region capture.

**Comment by 10se1ucgo** [comment]
Is it possible to use the color picker on the capture itself? The window hides itself whenever I press the color picker.

**Comment by 567legodude** [comment]
Sorry to bring up an old issue. I understand not wanting to open two region captures at once. But to pick a color for the drawing tool or shape tools during a capture, is it not possible for the color picker to use the same region capture instance that's already there?
