### ISSUE TITLE
Upload image  files (by FTP) of same name, overwriting old file?

### ISSUE THREAD

**Issue by Chris-Wilson123** [ShareX/ShareX#3375]
I am new to ShareX, I want to upload an image file, a full screenshot of the desktop, say called image.jpg to my ftp server, once every 30 minutes. I want the file name on the server to stay the same and be overwritten when the next upload occurs. Is this possible, and if so how do I set this up please? Thanks!

**Comment by Chris-Wilson123** [comment]
Thanks for the reply, but how do I force it to overwrite with a single, same, file name please?

**Comment by Jaex** [comment]
You can write static name here so it will be always same:

![](https://jaex.getsharex.com/2018/05/ShareX_PwbC2YLGaU.png)

**Comment by Chris-Wilson123** [comment]
Working fine now, many thanks Jaex
