### ISSUE TITLE
Possible to create an 'add border' after capture task?

### ISSUE THREAD

**Issue by ze-better** [ShareX/ShareX#3376]
See the two screenshots below:

![image](https://user-images.githubusercontent.com/33571987/39683358-5b1ac28e-51f8-11e8-8d0e-ecff5d421a3c.png)

The first one is from a guide that I created, the second one is from Salesforce documentation. As you can see, the second one looks much cleaner and more visually appealing simply because of the **thin black border** around the screenshot.

So I thought I'd ask, would it be possible to implement a simple way to automatically add a border like the one above around screenshots (assuming it is not possible already)? In my opinion, an after capture task would be most suitable for this functionality.

Many thanks

**Comment by gnosticJade** [comment]
You can do this using the Image effects/watermark post-capture function. 

Task Settings > Effects > Image effects configuration > Remove default settings > Add > Drawings > Border 

Then, change the size to however thick you'd like the line to be. I'd guess you'd want it a size of 2 based on your screenshot. Window should look something [like this](https://i.imgur.com/WBuPlGv.png) but with a black border (hard to see the black on black, so it's Red in my picture.)

**Comment by ze-better** [comment]
Fantastic! Exactly what I wanted. Thank you.
