### ISSUE TITLE
Image History needs an open in editor button

### ISSUE THREAD

**Issue by stuntguy3000** [ShareX/ShareX#3382]
I'll do this PR, making the issue so I don't forget...

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/commit/0047bc087a8dd7c8a267f51a03e104d879cbbfdb

**Comment by sheldonhull** [comment]
@Jaex  this is great and resolved my issue I was trying to fix for the last week. Is there a way to set the default double click behavior to edit image rather than copying to clipboard or is that an issue I'd have to open and request?
