### ISSUE TITLE
Copy image to clipboard is not working with gif.

### ISSUE THREAD

**Issue by SetoKaiba** [ShareX/ShareX#3384]
Copy image to clipboard is not working with gif.

**Comment by ThrashAbaddon** [comment]
@Torubloo Ok but that still doesn't solve the problem. Clipboard implementation should be fixed then so this could be implemented.

**Comment by alreadypro** [comment]
Any update on this?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2021/04/ShareX_Abv9Uc8hv5.png)

**Comment by alreadypro** [comment]
This isn't working for me, just wipes the clipboard

**Comment by alreadypro** [comment]
@Jaex this isn't working for me, it just wipes the clipboard

**Comment by newmedicine** [comment]
Same issue for me

**Comment by ThrashAbaddon** [comment]
@Jaex Yes I know about [this](https://github.com/ShareX/ShareX/issues/3384#issuecomment-812804989), and it is turned on, but it doesn't work.

**Comment by francisrohner** [comment]
> ![](https://camo.githubusercontent.com/f1e17666fd183ceecc1859cbef0402e8233b94f2d32b0d95de0e515ead201c54/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f30342f5368617265585f416276395563386876352e706e67)

This works for me with pasting into slack. 
Thank you!!!! 🐐 🐐 🐐

**Comment by GalacticInspired** [comment]
This is still an issue.

**Comment by alreadypro** [comment]
> ![](https://camo.githubusercontent.com/f1e17666fd183ceecc1859cbef0402e8233b94f2d32b0d95de0e515ead201c54/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f30342f5368617265585f416276395563386876352e706e67)

This is now working for me as of version 15.0 on Windows 11

**Comment by slrgt** [comment]
if this is enabled it stops copy image to clipboard from working
