### ISSUE TITLE
High CPU usage when taking region screenshot

### ISSUE THREAD

**Issue by rafitamolin** [ShareX/ShareX#3386]
Similar to issue #3221. I'd like to take a screenshot of a region on my screen, but when selecting the normal option to capture a region or the option to capture a transparent region, CPU usage starts increasing a lot. This doesn't happen with the "light region" feature.

This behavior shouldn't be normal.

**Comment by MAGICCC** [comment]
I have the same problem, but only when using the transparent one https://github.com/ShareX/ShareX/issues/2906

**Comment by rafitamolin** [comment]
Still occuring in latest version... pathetic.

**Comment by Liquidream** [comment]
Any update on this? As it kills my Intel NUC when taking screenshots of regions
(and lowers the FPS of my games when trying to capture videos - in lossless, for later encoding)
Thanks.
