### ISSUE TITLE
Language support Issue(Find untranslated parts)

### ISSUE THREAD

**Issue by JooHyungByun** [ShareX/ShareX#3389]
Hello,
While using Sharex, I found a part that was not translated.
In Task settings... -> Advanced.
![image](https://user-images.githubusercontent.com/37129256/39954919-88f8bbe4-5602-11e8-9e33-914c62cb21ff.png)

I have confirmed that this occurs in other languages ​​as well.
![image](https://user-images.githubusercontent.com/37129256/39954852-2af5ca38-5601-11e8-9ba4-13d15d9ca9c9.png)

Did not you translate this part intentionally?
If not, can I translate to korean?

**Comment by Jaex** [comment]
Those are not translatable easily. Because it just shows variable names automatically.

**Comment by JooHyungByun** [comment]
![image](https://user-images.githubusercontent.com/37129256/39954953-380489ce-5603-11e8-9f8a-eb5eed2e8b11.png)

These parts need translation and seem to be translated easily. Isn't it?

**Comment by JooHyungByun** [comment]
Hello, on issue #3389
These parts need translation and seem to be translated easily. Isn't it?
 
-----Original Message-----
