### ISSUE TITLE
Stop Recording comand line missing.

### ISSUE THREAD

**Issue by sdraganov** [ShareX/ShareX#3392]
Not sure if this is the right place to report issues.
I'm trying to incorporate ShareX into our QA tests. More specifically I would like to run ShareX from a command line capture a video and save it into specific location.
I can't find a command to stop the video recording however, there is a command for aborting it but not for stopping it.

The other thing I am missing is the ActiveMonitor option - is there a way to specify the entire screen of the current monitor, or if not what parameters I should use for CustomRegion?

If this is not the right place to ask for help please let me know where I could do that.

Regards,
Svetlozar Draganov

**Comment by Jaex** [comment]
Start recording hotkey also stops it.
