### ISSUE TITLE
Mouse Cursor

### ISSUE THREAD

**Issue by joshhroberts** [ShareX/ShareX#3394]
When recording video or a GIF, the mouse always seems to centre for no reason.

Example: [https://plsno.co.uk/917a79f.mp4](https://plsno.co.uk/917a79f.mp4)

That's just from me circling my mouse. Any help?

**Comment by vatterspun** [comment]
Now *that's* a bug report.

**Comment by Alcha** [comment]
Just tried this on my Windows 10 machine with no issues. Could there be something with your particular OS/configuration?

Example: https://imgur.com/a/3sk2ICn

I tried copying your exact clip of just moving the cursor in circles off to the side. I did this a number of times, using MP4 saves and Gif saves, gifs are just easier to post on Imgur.

**Comment by x-Josh** [comment]
Strange, must just be me.

Maybe there is some sort of underlying problem. Although, I tried the awful Gyazo Gif application and it was fine.
Example: [https://gyazo.com/35060520647fcc8103727b45fe8fa912](https://gyazo.com/35060520647fcc8103727b45fe8fa912)
