### ISSUE TITLE
Imgur upload failed: (400) These actions are forbidden.

### ISSUE THREAD

**Issue by Kumiri** [ShareX/ShareX#3395]
Imgur upload failed: (400) These actions are forbidden.

Message:
远程服务器返回错误: (400) 错误的请求。
Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":"These actions are forbidden."},"success":false,"status":400}

Stack trace:
   在 System.Net.HttpWebRequest.GetResponse()
   在 ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**# Ping：https://vgy.me/igz2Lf.png**

**Comment by Kumiri** [comment]
Message:
无法将数据写入传输连接: 远程主机强迫关闭了一个现有的连接。。

Request URL:
https://api.imgur.com/3/image

Stack trace:
   在 System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   在 System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   在 System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   在 ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   在 ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by johnzhang2013** [comment]
I also encountered this ..... no way to fix it.... sadlly!

**Comment by popey456963** [comment]
Are you able to navigate to https://api.imgur.com/3/image in your web browser?  Do you get a 400 error there?
