### ISSUE TITLE
ShareX isnt able to access my ftp server

### ISSUE THREAD

**Issue by LeshDev** [ShareX/ShareX#3401]
Hello Guys,

I own a FTP Server and I thought I've setup everything correctly. But as soon as I upload an image there is no file on the FTP Server.  
It looks like ShareX isn't able to connect to my server over the port 22
With FileZilla I'm able to connect to my server with the same entries.

![My FTP Settings](https://user-images.githubusercontent.com/11671272/40053983-88ece1d2-5843-11e8-8ccb-f7d91fcc8e7a.PNG)

Hope you guys can help me

**Comment by Torubloo** [comment]
Not sure where you are entering those but normally you would go into Destination settings then down to File uploaders and click FTP / FTPS / SFTP and that works fine for me.

Let me know where you are entering them

**Comment by Torubloo** [comment]
Might be easier if you have Discord as well, can talk in real time.

**Comment by LeshDev** [comment]
This is how it looks like in the normal GUI

![image](https://user-images.githubusercontent.com/11671272/40061808-0bfc8c9c-585a-11e8-988e-f795e84c06ee.png)

**Comment by LeshDev** [comment]
This is how it looks like in the normal GUI

![ftp2](https://user-images.githubusercontent.com/11671272/40061857-2bbf30c0-585a-11e8-8436-a8149f54998c.PNG)

**Comment by LeshDev** [comment]
Fixed the issue.
There was no FTP Server. Only sftp
