### ISSUE TITLE
[Feature Request]Add option fully disable and hide all "upload to host" options

### ISSUE THREAD

**Issue by norweeg** [ShareX/ShareX#3403]
Could you add an option to fully disable and hide the "upload to host" options or produce a version devoid of "upload to host" support?  I would like to use ShareX in contexts where I would be capturing sensitive information for internal use within my organization, but am discouraged from doing so because ShareX default config seems to default to upload to host enabled as an after capture and I have had the option seemingly spontaneously re-enable itself after being turned off.  I regrettably end up using Snipping Tool instead because I am paranoid that ShareX will inadvertently share what I capture to imgur or another image sharing host and sadly cannot recommend others in my organization use it, even if it would otherwise be extremely useful because of this very reason.  I just want a version of ShareX that is only for capturing and marking-up screen captures locally, confident that I am not inadvertently jeopardizing the security of my organization.

**Comment by Jaex** [comment]
That option already exists:

![](https://jaex.getsharex.com/2018/05/ShareX_AzeVguu86G.png)

**Comment by norweeg** [comment]
Yes, I've see that, but I have also had it go from False to True for seemingly no reason at all (possibly after an application update).  My request is because I am somewhat perturbed by the fact that uploading is default 'on' after install instead of off, when, in my opinion, image upload should be opt-in not opt-out.  I am also bothered by the fact that, even after making this option 'True', the upload options are still visible in the menu.  I do consider ShareX to be among the best screen capture applications available, however, I struggle to understand what the use case is that necessitates default uploading of every screen capture to an image sharing service.

**Comment by norweeg** [comment]
All I'm asking is please consider the use case of someone who just wants a quality screen capture application, nothing more, nothing less.  Judging by the name of the application I'm guessing you consider image sharing to be the core purpose of the application instead of screen capture and markup

**Comment by stuntguy3000** [comment]
I managed an enterprise IT network myself, and I have chosen to deploy ShareX.

If you care about document sensitivity, I would
 * Not use ShareX
 * Beef up your firewall

Get a solid Firewall, block and detect image uploading services in the first place.

Users can change the settings anyway, and ShareX does not support registry/GPO based settings.

**Comment by norweeg** [comment]
@stuntguy3000 its not just in a secure organization.  Say, for example, I'm just an average user who wanted to capture and OCR something on screen on a personal computer, which does not have enterprise-managed security or firewall, that contains my personal information for the purpose of sharing with someone I want to disclose this info to.  I should not have to worry about ShareX inadvertently exposing this data publicly via image/text upload either by default in its default configuration or its tendency to revert to its default configuration for reasons unknown.  Honestly I don't understand why the sharing is part of the core functionality of what is ostensibly a screen capture application and not an optional add-on or plug-in.  I can see from looking at reviews of sharex online that other people consider the on-by-default image upload functionality to be similarly problematic and undesirable.

**Comment by Jaex** [comment]
> Honestly I don't understand why the sharing is part of the core functionality of what is ostensibly a screen capture application and not an optional add-on or plug-in.

It is literally part of application name **Share**X. Initial versions of ShareX didn't even had any screen capture functionality. High percentage of users downloads ShareX for uploading functionality. People who wants to only screen capture can already use built in snipping tool.

**Comment by posti85** [comment]
> It is literally part of application name **Share**X. Initial versions of ShareX didn't even had any screen capture functionality. High percentage of users downloads ShareX to be able to upload screenshots. People who wants to only screen capture can already use built in snipping tool.

I'm sorry, but that argument it's really poor. @Jaex, you should realize that your application has evolve over time to the best screen capturing app ever. Nowadays there are people that only wants to use XShare just for private captures. And that's why there are many issue related to the same: 'Disable upload entirety', 'Block uploads'...

For example, Youtube in its beginnings was a kind of social network like Facebook is. But its nice feature of managing video uploads made the platform evolve over time so people just use to upload and share videos easily.

You should change your mind and consider these suggestions.

**Comment by Zorklis** [comment]
> It is literally part of application name **Share**X.
> High percentage of users downloads ShareX to be able to upload screenshots.
I highly doubt a high percentage do that. Has there ever been a public poll to know that? Probably not.
As for Share in ShareX, it should be sorta like a synonym with Shearing which is a tool to cut (wool).

**Comment by Jaex** [comment]
> I just want a version of ShareX that is only for capturing and marking-up screen captures locally, confident that I am not inadvertently jeopardizing the security of my organization.

https://getsharex.com/docs/command-line-arguments#registry

`DisableUpload` registry setting can be used.

**Comment by nodejsg** [comment]
PLZ Disable Upload Entirely by default, both install version and portable version. Portable version does not disable it by default.
There is a NO UPLOAD version. https://github.com/Cosebdd/ShareNot
