### ISSUE TITLE
Suggestion: Add Beta Channel to test release candidates thoroughly before Stable releases

### ISSUE THREAD

**Issue by AluminiumTech** [ShareX/ShareX#3404]
Hi,
I'd like to make a few suggestions. 

I think that a Beta channel should be added so that there is some sort of middle ground between Stable versions and getting the very latest commit. This would allow more users to be able to test releases candidates before an official release on the stable channel.

E.g. When you're working on Stable version you make commits to the master branch and merge into Stable when you release a new Stable version.

And when you want to release a beta version, merge commits into Beta branch. And release a new Beta version similar to how you release Stable versions in GitHub releases but using the pre-release tag on GitHub and warning users that it is not stable. 

And a mechanism for auto-updating in the Beta branch would be cool as well. Beta build change logs would also be appreciated :) .

And having a rough schedule of how often a beta build should come out would be nice E.g. Once every week or once every 2 weeks or once every 2 days.

The suggestions I've listed above should hopefully help provide a faster release cadence and more stable Official Stable versions. 

Thanks.

**Comment by AluminiumTech** [comment]
> I wouldn't like filling https://github.com/ShareX/ShareX/releases with countless beta releases. Because then normal users wouldn't be able to find stable builds.

GitHub, Brave Software, and others manage to do this just fine with their projects. A good example of the kind of thing I was suggesting is Atom's way of doing Betas.

**Comment by Jaex** [comment]
https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/0.22.669/winx64/BraveSetup-x64.exe
https://atom-installer.github.com/v1.26.1/AtomSetup-x64.exe

Both not using releases for actual download. And probably not for updates too.

**Comment by Jaex** [comment]
I also mark releases as pre-release initially so I wouldn't be able to use it as beta marker.

**Comment by AluminiumTech** [comment]
@Jaex  Oh? And why are they initially marked as Betas? 

If they need to be initially marked as betas then you could just label Betas releases as X.Y.Z Beta for example. And just a short warning in the release notes that it's not a stable release.

**Comment by Jaex** [comment]
When releasing I'm marking them as pre-release first and people can get it 3 days early than normal users. If there is no bugs then I remove pre-release tag so everyone can get it. If there is bugs then I fix and release another version as non pre-release.

**Comment by AluminiumTech** [comment]
@Jaex  Maybe you could tweak the update mechanism so that if a URL contains the word "Beta" it recognizes it and then you could try it with the first ShareX Beta.
