### ISSUE TITLE
Deprecate support for dead URL shorteners

### ISSUE THREAD

**Issue by AluminiumTech** [ShareX/ShareX#3408]
I'm bundling multiple suggestions for deprecating different URL Shorteners here since they all seem to be dead.

![2gp](https://user-images.githubusercontent.com/14107316/40077689-576cc97e-587a-11e8-9c06-74b8052089f5.PNG)
![coinurl](https://user-images.githubusercontent.com/14107316/40077708-5b3503be-587a-11e8-8086-d56f3a6a490d.PNG)
![googl](https://user-images.githubusercontent.com/14107316/40077770-8d3e53c4-587a-11e8-82b1-d2deb607b1a7.PNG)

Google isn't shortening URLs from new users.

**Comment by sylveon** [comment]
Goo.gl has already been removed and replaced by Firebase Dynamic Links for the next version.

**Comment by Jaex** [comment]
I will remove those deprecated uploaders in 3 days. So I can make sure none of them was temporary down.

**Comment by Jaex** [comment]
http://2.gp opens but url shortening not works for some reason even in their web site.
