### ISSUE TITLE
Possible to add a border to gif recordings?

### ISSUE THREAD

**Issue by ze-better** [ShareX/ShareX#3412]
Similar to how you can add a border to images from **Task Settings** > **Image** > **Effects** > **Image effects configuration**.

![border](https://user-images.githubusercontent.com/33571987/40148478-875522e8-59b1-11e8-9363-793f3c311755.png)

This would be very useful.

**Comment by Alcha** [comment]
Would this not be similar to being able to edit gifs, such as in #3393?

**Comment by ze-better** [comment]
Thans for pointing that out. The original idea regarding editing GIFs seems to be #1554 - unfortunately though, Jaex has already indicated that it is out of scope.

I'm enquiring about a much simpler functionality - simply adding a black border around GIFs after they've been captured. So I don't think this should be classified as a duplicate.

**Comment by Jaex** [comment]
Because FFmpeg doing recording and GIF encoding, it won't be easy for ShareX to add borders. And I don't have plans to implement GIF editing functionality.
