### ISSUE TITLE
Issue/Suggestion: Image editor closing

### ISSUE THREAD

**Issue by Dubz** [ShareX/ShareX#3425]
Whenever you have the image editor open, right clicking cancels the operation, whereas hitting enter continues the task (I'd assume).

Is there a way to disable this from happening? I'd rather have to click the check manually instead of being able to hit enter. I'd also like to not have the operation cancel when I right click the image. Sometimes I'm in the middle of an edit and doing either of these stops the editing process and I have to start over.

**Comment by Jaex** [comment]
Next version gonna have msg box to ask before closing but for now you can disable it from here:

![](https://jaex.getsharex.com/2018/05/ShareX_tSk3M0s1KS.png)
