### ISSUE TITLE
Google Photos Short Link

### ISSUE THREAD

**Issue by BetaLeaf** [ShareX/ShareX#3427]
As it is now, screenshots taken with ShareX use the expanded url: 
https://lh3.googleusercontent.com/-eSSxbVRcHlY/WwwcLCLEVYI/AAAAAAAAS9E/6EQnTFJBMjAczVGc9Y6dHtQwP-SGo7TagCHMYCw/s0/chrome_2018-05-28_11-11-38.png

Google Photos supports short links which look like this:
https://photos.app.goo.gl/lbLD57WjG4Thd5X73

Can we get support for short links please?

**Comment by matthewburnett** [comment]
We're using an old Picasa API currently which doesn't support this response. I believe the new API does here https://developers.google.com/photos/

So to support this, we would need to rewrite the entire uploader anyway using this new API.
