### ISSUE TITLE
When using screen recording,  the region selection sometimes goes wrong.

### ISSUE THREAD

**Issue by gunooknam** [ShareX/ShareX#3430]
I set the screen recording with the shortcut key, and then record it 

sometimes, the region selection is wrong.

https://www.youtube.com/watch?v=sq_w-iOc2L4&feature=youtu.be

**Comment by Jaex** [comment]
Your video not opens.

**Comment by gunooknam** [comment]
sorry, I uploaded it again.
https://www.youtube.com/watch?v=sq_w-iOc2L4&feature=youtu.be
