### ISSUE TITLE
Hotkey registration failed

### ISSUE THREAD

**Issue by NatoBoram** [ShareX/ShareX#3431]
A core component of Windows 10, OneDrive, uses the following shortcuts by default : 

* CTRL + Print Screen
* Print Screen
* Alt + Print Screen

Because of this, every Windows 10 installations I have pops up the same error message from ShareX.

![capture](https://user-images.githubusercontent.com/10495562/40881851-a5f11cf2-669f-11e8-956a-56f2abe45abb.PNG)

It would be nice if the ShareX build that comes from the Windows Store played it nice with Windows 10.

Possible solutions : 

* Don't show the error message. I don't think that anyone actually cares if ShareX wants to override Windows 10's default behaviour.
* Change default shortcuts. Ideally, an application downloaded from the Windows Store shouldn't enter in conflict with Windows 10
* Show how to disable these shortcuts. It's nice and all, but honestly, ShareX's interface is *very* unusual and confusing.

That said, ShareX is the single best tool I've ever used.

**Comment by sylveon** [comment]
You can turn off OneDrive screenshot uploading in its settings. Restart OneDrive, restart ShareX, and they should work.

**Comment by Jaex** [comment]
* If I don't show error message then people won't know why their hotkeys not working.
* I can't change default hotkeys, people got used to those hotkeys for using ShareX past 10 years.
* User can change or delete hotkeys if they want to.

So your solutions not really solution.

**Comment by NatoBoram** [comment]
Maybe there can be a more meaningful error message, with a few auto-correct options inside it?

For example, new users won't mind if those shortcuts suddenly are disabled if they're not used to them. Adding a "disable affected shortcuts" button would be helpful.

Another example would be to detect if the conflicting application is OneDrive and add a few lines on how to disable the conflicting behavior in OneDrive.

I hope those solutions are more appropriate!

**Comment by NatoBoram** [comment]
Maybe there can be a more meaningful error message, with a few auto-correct options inside it?

For example, new users won't mind if those shortcuts suddenly are disabled if they're not used to them. Adding a "disable affected shortcuts" button would be helpful.

Another example would be to detect if the conflicting application is OneDrive and add a few lines on how to disable the conflicting behavior in OneDrive.

One improvement possible to the message would be to add the icon of the shortcut menu in the message so the button would be easier to see in ShareX' interface. Like I said, its interface is fairly unusual, so adding an icon when referring to a button can help to visually spot the menu entry.

I hope those solutions are more appropriate!

**Comment by fuhrmanator** [comment]
> You can turn off OneDrive screenshot uploading in its settings. Restart OneDrive, restart ShareX, and they should work.

I checked my OneDrive settings and this was already turned off. There are no settings in OneDrive that I can find to change the keys. 

Finally, to stop the pop-up at each re-start, I had to go into **ShareX  - Hotekey settings...** and set the hotkeys to "None" (click the definition, then click elsewhere).

**Comment by anique9999** [comment]
Is there a way to suppress this prompt through via Setup CLI (ex. /Silent)? 
I tried using -nohotkeys with Setup CLI commands but I'm still getting the pop-up.

**Comment by konradsikorski** [comment]
@Jaex 
> * If I don't show warning message then people won't know why their hotkeys not working.
> * I can't change default hotkeys, people got used to those hotkeys for using ShareX past 10 years.
> * User can change or delete hotkeys if they want to.
> 
> So your solutions not really solution.

Other solutions:
1. Add an option to the dialog, "ok, do not show anymore". 
2. add an option in the app: "override hotkeys"

**Comment by frigvid** [comment]
This certainly needs a toggle to disable showing the error message as it doesn't even detect properly sometimes.

E.g. if you have a work and personal account for OneDrive, you can have more than one session, and each have their own settings. A business/work account does not include the settings for screenshot upload like the personal one does. Even with the personal account setting for screenshot upload being disabled does nothing to stop ShareX from showing the error message. However, the keybind still works as expected and takes a screenshot through ShareX without interruption.

It also has the same issue with Dropbox sometimes, as it is also listed in the error message even if the setting is disabled.

**Comment by bradthurber** [comment]
I know this is closed, but in case this helps someone else.

It was OneDrive for me that was causing problems for me even though it was turned off in the OneDrive settings dialog. 

The solution was to press the PrintScreen key on my keyboard, wait for the OneDrive dialog box to popup about saving screenshots, then click the `No Thanks` link in the OneDrive dialog. Now when launching ShareX, I do not get a prompt about not being able to register hotkeys.

Who knows if this apparently hidden setting will "hold", but it seems to be working for now.

**Comment by therollonation** [comment]
Following Brad's comment about pressing the PrintScreen button on my keyboard, on Win 11 build 22631.3296 this will bring up the Snipping Tool which has a toggle for the screenshot upload.    You can make the pop up go away by disabling it inside this other app as well.

Maybe an update to the pop up about looking for this setting in the snipping tool as well?  (if it's already there please disregard)

**Comment by kalyanid1** [comment]
> I know this is closed, but in case this helps someone else.
> 
> It was OneDrive for me that was causing problems for me even though it was turned off in the OneDrive settings dialog.
> 
> The solution was to press the PrintScreen key on my keyboard, wait for the OneDrive dialog box to popup about saving screenshots, then click the `No Thanks` link in the OneDrive dialog. Now when launching ShareX, I do not get a prompt about not being able to register hotkeys.
> 
> Who knows if this apparently hidden setting will "hold", but it seems to be working for now.

This worked for me! Thanks @bradthurber
