### ISSUE TITLE
GifV format

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#344]
Are you aware of and prepared for the new **GifV** ?
Do you have any plans for GifV to be implemented into ShareX as an option?
Please do.
http://www.cnet.com/news/imgur-gifv-format-speeds-up-viral-image-sharing/#!

Thankyou

**Comment by WiliTest** [comment]
Slightly related question: is there a way to retrieve the .gif url instead of the .gifv after uploading to Imgur?

**Comment by Jaex** [comment]
Uncheck this:

![](https://jaex.getsharex.com/2020/01/ShareX_T9hAfEIlDb.png)
