### ISSUE TITLE
error ftp

### ISSUE THREAD

**Issue by zykoytz** [ShareX/ShareX#3443]
Hello I add my ftp from my image hosting site then I have an error can you help me?
![screenshot_223](https://user-images.githubusercontent.com/31708587/41207006-05ceb30e-6d0e-11e8-9f37-f767cf3deb82.png)

![screenshot_224](https://user-images.githubusercontent.com/31708587/41207009-1ab23b42-6d0e-11e8-99ae-16525665d266.png)

**Comment by trollmad3** [comment]
When you translate the error 
> System.UriFormatException: URI non 
valide : Impossible d'analyser le nom 
d'hôte. 
it translates to 
> System.UriFormatException: URI No
valid: Can not parse namehost.

Maybe there is an error in your FTP server that you configured wrong.
