### ISSUE TITLE
Screen region recording creates empty files

### ISSUE THREAD

**Issue by TutMat** [ShareX/ShareX#3444]
Hi,
suddenly (worked fine few weeks ago) sharex stopped creating proper mp4 files for me.
I activate screen region recording from hotkey, show region it starts recording. After clicking stop proper file should be created but it creates empty (0kb) file for me.
i tried to reinstall/reboot PC, did not help.

File attached is created video: [2018-06-12_14-06-09.zip](https://github.com/ShareX/ShareX/files/2093930/2018-06-12_14-06-09.zip)
Video should have few seconds
this is how debug log looks for me: 

> 2018-06-12 14:06:08.171 - Executing: Start/Stop screen recording using custom region
> 2018-06-12 14:06:08.173 - Starting screen recording. Video encoder: "x265 (mp4)", Audio encoder: "AAC", FPS: 60
> 2018-06-12 14:06:09.390 - CLI: "C:\Users\my User\Documents\ShareX\Tools\ffmpeg.exe" -y -rtbufsize 100M -f dshow -framerate 60 -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:v libx265 -r 60 -preset superfast -tune zerolatency -crf 30 -pix_fmt yuv420p -movflags +faststart -c:a aac -strict -2 -ac 2 -b:a 128k "C:\Users\my User\Documents\ShareX\Screenshots\2018-06\2018-06-12_14-06-09.mp4"
> 2018-06-12 14:06:13.425 - Task in queue. Job: Job, Type: File, Host: 
> 2018-06-12 14:06:13.431 - Task status: Preparing
> 2018-06-12 14:06:13.432 - Task completed. Filename: 2018-06-12_14-06-09.mp4, Duration: 6 ms

**Comment by Jaex** [comment]
In screen recording options window there is Test window can you try that.

**Comment by TutMat** [comment]
Sure, just tested - log is attached below.
[Sharex_CMDRegionScreenLog.txt](https://github.com/ShareX/ShareX/files/2097121/Sharex_CMDRegionScreenLog.txt)

**Comment by Jaex** [comment]
Did you tried installing latest recorder devices from last ShareX version and redownloading FFmpeg to get latest FFmpeg.

**Comment by TutMat** [comment]
That helped! Now it works again, thank you!
I did not know that those files need to be re-installed and re-downloaded after some updated.
Thanks again :)
