### ISSUE TITLE
Could there be an option for the ShareX tray icon to glow when a screenshot is made

### ISSUE THREAD

**Issue by Crashego** [ShareX/ShareX#3451]
Could there be an option for the ShareX tray icon to glow when a screenshot (task) is made (so that you know it worked)?

**Comment by Jaex** [comment]
When screenshot taken capture sound plays and if you can't hear it then there is also task complete notification shows up at right bottom.

**Comment by Crashego** [comment]
My computer is muted. The task complete notification is shown in screenshots when I take screenshots in quick succession (so I have disabled it). If it were possible, an option of a quick flicker of the ShareX tray icon when a task is completed would be nice.
