### ISSUE TITLE
[Feature request] Allow renaming of saved files through History window

### ISSUE THREAD

**Issue by RenewedRS** [ShareX/ShareX#3452]
On this right-click menu somewhere, or maybe just double clicking the filename? Many times I will come back to find an image that I hadn't named previously and there is no way to rename it quickly through sharex

![image](https://user-images.githubusercontent.com/14082337/41509341-38fe2cbe-724a-11e8-8eef-5f572ac7be15.png)

**Comment by vperep** [comment]
Yes, renaming files thru file list interface would be a very useful feature. Now I need to use explorer for that - and after such manual renaming, that file becomes not opened /accessible in main XShare windows. 
Please implement it. 
PS: SnagIt has it. PictureStone has it....

**Comment by friuns2** [comment]
yeah

**Comment by poebrand** [comment]
Agree, this would be a great feature to make it quicker/simpler to manage captures.

**Comment by t0l0** [comment]
On my wishlist, too. Renaming from History/Image history with a simple F2 Button action

**Comment by allwynmascar** [comment]
This would be a great feature..im not sure if its already on .. as this request is quite old..anyone know anything?

**Comment by Destroy666x** [comment]
+1 for this
