### ISSUE TITLE
Image history appearing off screen

### ISSUE THREAD

**Issue by Cacuu** [ShareX/ShareX#3456]
On windows if you have the taskbar on top, every time you launch the image history, it'll be covered by the taskbar, even if you move the window using a move command. The next time you launch it, it'll move even 'deeper' offscreen. It seems to go up the size of the taskbar per launch, so every time you open the image history it seems to push it further up into the screen. Regardless of whether you move it or not, it seems to always appear under the taskbar.

I think this has to do with the program considering that the taskbar will always be on bottom and compensating for that (by moving the window up by the width of the taskbar). So when the taskbar is on top, it moves into it.

![Screencap](https://user-images.githubusercontent.com/20868562/41630882-bf11e58e-7407-11e8-9544-cd2ff3f7502a.png)
I blurred the contents of the image history and the taskbar. but hopefully you can see the issue.

How to reproduce:
Move windows taskbar to the top. I have two monitors and I moved the taskbar to my secondary monitor on the top. That might be relevant.
Open image history through the notification area icon (right click > Image history)
It should appear a bit offscreen.

Temporary fix:
Move the taskbar to the bottom then back up. the window gets unstuck.
or
shift right click the icon on the taskbar and select move, use arrow keys to move it out of the bar.

This isnt a major issue or anything, but it's something that has bothered me for some time now. I know how to move it out of it, but it can be troublesome for an user without that knowledge.

**Comment by Jaex** [comment]
Windows GetWindowPlacement function returns wrong Y position when taskbar at top which causing this issue.
