### ISSUE TITLE
Two screenshots in quick succession, second screenshot is not captured

### ISSUE THREAD

**Issue by Xebtria** [ShareX/ShareX#3458]
I use sharex to do documented testing of software, the only thing sharex does is save the image as a file with an incremental numbering.

sometimes I do two screenshots very quickly after another. 

I found out that when the first screenshot has not yet been saved to disk yet and I press the button (only happens well within <1 second after the first) again, then the second screenshot is never saved to disk.

can this be fixed?

**Comment by Jaex** [comment]
I added configurable hotkey time limit for next version, by default it was 1 second.
