### ISSUE TITLE
Hovering over a thumbnail preview after uploading generates an error

### ISSUE THREAD

**Issue by MetalRuller** [ShareX/ShareX#3464]
Using custom uploaders and unicode characters generates this upon hovering over the thumbnail
Before hovering over the thumbnail, it correctly displays the captured data, simply when hovering converts to a white box with a red X on it and gives those 2 errors.

![sharex_2018-06-24_18-10-28](https://user-images.githubusercontent.com/9076708/41821526-eb8b6b96-77d9-11e8-8be3-2bb9ea19fc95.png)
![sharex_2018-06-24_18-10-36](https://user-images.githubusercontent.com/9076708/41821527-eba51d20-77d9-11e8-9009-1563e322e2cc.png)
![sharex_2018-06-24_18-10-32](https://user-images.githubusercontent.com/9076708/41821528-ebbeda3a-77d9-11e8-8df8-e8cf276854f4.png)

**Comment by MetalRuller** [comment]
I'm willing to provide a sample of the URL itself with all the unicode (on discord) or the upload host's import file for ShareX if necessary for reproduction purposes

**Comment by Jaex** [comment]
Only solution I could find is adding try catch to those sections in code but that is pretty ugly solution.

**Comment by MetalRuller** [comment]
Issue somewhat resolved generally, and resolved properly on my end, after I actually looked at ShareX's settings, closing it for now I guess
