### ISSUE TITLE
ShareX crash/suspend on startup after computer restart

### ISSUE THREAD

**Issue by GLugia** [ShareX/ShareX#3465]
https://pastebin.com/raw/B0Y74bnS

I'm not sure how to read this but it seems like it's just failing to read the config file. Reinstalling solved the issue but I wanted to point this out for future references. I've had various issues with ShareX since the recent update such as it not capturing games that are set to fullscreen or uploading to imgur (I've resorted to using catbox.moe and other various third-party sites). This was the weirdest occurrence so far.

**Comment by Jaex** [comment]
Pastebin is blocked in my country.

**Comment by GLugia** [comment]
How about hastebin? https://hastebin.com/raw/ukufuconoy

**Comment by Jaex** [comment]
That error means library file become corrupt and you need to reinstall ShareX.

**Comment by Jaex** [comment]
I don't know how.

**Comment by eXpl0it3r** [comment]
My system locked up and needed to be force rebooted. Then ShareX wanted to install the update, which I let it do and when it tried to start again, it crashed.

Maybe my Symantec had interfered? I also have Dropbox installed which it usually runs into hotkey fights.

Reinstall fixed the issue.

**Comment by eXpl0it3r** [comment]
Haven't had that in a while, so idk 😄
