### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by mohamedb11117** [ShareX/ShareX#3466]
Imgur upload failed: (400) Banned country attempt (EG)

Message:
أرجع الملقم البعيد الخطأ: (400) طلب غير صالح.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":1016,"message":"Banned country attempt (EG)","type":"Exception_Logged","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   عند System.Net.HttpWebRequest.GetResponse()
   عند ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
Imgur gives this error: "(400) Banned country attempt (EG)" which is not to do with ShareX.

**Comment by mohamedb11117** [comment]
What's the solution

**Comment by NitroxydeX** [comment]
Using an other uploader. Like the response states: imgur has banned access from the country you are living in to their service.
