### ISSUE TITLE
screen shot capture speed limited?

### ISSUE THREAD

**Issue by rareX55** [ShareX/ShareX#3467]
I've used another capture program.
The program was able to take 5~6 pictures per second
However, this program only takes one shot per second
Other features are overwhelmingly good for ShareX
Can I turn off Capture Speed Limit?

**Comment by Jaex** [comment]
Yes:

![](https://jaex.getsharex.com/2018/06/ShareX_oAVqtYskRI.png)

I don't recommend making it 0 too :)

**Comment by rareX55** [comment]
THANKS! 
But there are more questions.
When capturing quickly, a new file name window is activated
Is this window inactive and you can not continue using the options you originally selected?
Also, can you lower the minimum limit to 200?
