### ISSUE TITLE
capture speed (not same question)

### ISSUE THREAD

**Issue by rareX55** [ShareX/ShareX#3469]
When capturing quickly, a new file name window is activated (2018-06-26_15-36-40 (2) )
Is this window inactive and you can not continue using the options you originally selected?
Also, can you lower the minimum limit to 200?

**Comment by Jaex** [comment]
Are you asking this?

![](https://jaex.getsharex.com/2018/06/ShareX_LL3wk4Zptq.png)

Minimum limit is already 200.

**Comment by rareX55** [comment]
wow thanks!!

**Comment by rareX55** [comment]
can i limit 100?

**Comment by rareX55** [comment]
need more speed

**Comment by Jaex** [comment]
If you want faster capture speed then you can use screen recording.
