### ISSUE TITLE
ShareX update failing and deleting itself

### ISSUE THREAD

**Issue by baabaablackgoat** [ShareX/ShareX#3473]
After being prompted to update ShareX, the installer is unable to replace ShareX.exe for some reason.
When attempting to reopen ShareX after aborting the installation, the executable is missing.
I had to get the installer from the website to reinstall.
![related error message](https://i.imgur.com/I9CSjCr.png)

Error occured on both Windows 8 and 10 (latest stable build each) while upgrading to 12.2.0.

**Comment by Jaex** [comment]
Do you use anti virus software?

**Comment by baabaablackgoat** [comment]
MBAM and Windows Defender.

**Comment by Jaex** [comment]
Malwarebytes causing it.

**Comment by baabaablackgoat** [comment]
Ah, i was unaware of that. Apologies.

**Comment by Jaex** [comment]
I sent support ticket to Malwarebytes now and gonna write here when issue is resolved.

**Comment by Nathan-Lane** [comment]
Ah, that explains it. Thanks.

**Comment by Jaex** [comment]
Got response:

![](https://jaex.getsharex.com/2018/06/chrome_Q50lIObPUn.png)
