### ISSUE TITLE
CTRL+Scroll during capture doesn't seem to change tool anymore

### ISSUE THREAD

**Issue by BristolITDave** [ShareX/ShareX#3475]
Since updating this morning, I seem unable to scroll through my tools at the top while "Capturing and Annotating"

Instead, while holding CTRL, it just zooms, as if I weren't holding it.

Has anyone else run into this?

**Comment by JamesHarrisonBaggs** [comment]
I can confirm this occurs in 12.2 and not in 12.1

https://github.com/ShareX/ShareX/releases/tag/v12.1.1

**Comment by Jaex** [comment]
People keep accidentally switching rectangle region tool to circle region tool with mouse wheel without be aware of it, therefore I needed to disable that shortcut. But I added new hotkeys for tools which should help at least switching tools fast.

**Comment by BristolITDave** [comment]
@Jaex Thanks - that makes sense, although it changes mine (and probably quite a few other's workflow). Is it possible to get an option to toggle this functionality back on? I have no problem with the default being off.

As an alternative, please could you put shortcuts that match the order of the buttons at the top? 
i.e. 1,2,3 = Region Rectangle, Region Ellipse, Region Freehand etc.. I have to remember so many different keyboard shortcuts already for other programs it would be nice to have some universally guessable ones - which is why the mousewheel was so nice. Or as another alternative, put little icons that show the keybind on each tool?

Before raising this issue, I also checked the keybinds page at: https://getsharex.com/docs/region-capture which still states that this is an option - might be worth updating this.

PS: Many thanks for this awesome software - it truly makes a difference to my daily life!
