### ISSUE TITLE
WASD keys no longer work.

### ISSUE THREAD

**Issue by trollmad3** [ShareX/ShareX#3476]
I have no idea what I did but whenever I try to move this over 
![image](https://user-images.githubusercontent.com/7843719/41921295-c8d7b996-791f-11e8-891e-3b15d2ef86db.png) 
it will stay. The arrow keys work fine but not `WASD` if anyone knows how to fix this please tell me.

**Comment by Jaex** [comment]
Now we added shortcuts for tools which using those characters therefore you can't use WASD to move cursor anymore.

**Comment by trollmad3** [comment]
@Jaex Is there a way to revert it?

**Comment by Cpawel** [comment]
Echoing trollmad3's comment, is there way to revert, or perhaps change the keybindings, swapping the commands on wasd to the arrow keys?

**Comment by trollmad3** [comment]
@Cpawel I hope there is. But this _probably_ isn't a problem for me anymore because I got used to using arrow keys.

**Comment by MiakoMoto** [comment]
+1, my workflow is thrown off. is there a way to change this besides compiling myself
