### ISSUE TITLE
drag and drop screenshot preview into another application?

### ISSUE THREAD

**Issue by akeissami** [ShareX/ShareX#3486]
Is this possible?
https://www.youtube.com/watch?v=uzgEVef0udI&feature=youtu.be&t=2m44s

btw, love ShareX, thank you!

**Comment by sosnik** [comment]
The latest screenshot is copied to clipboard, so you can just `CTRL+V` instead of drag-n-dropping to whatever application you want.

**Comment by akeissami** [comment]
Pasting using Ctrl+V is nice but, depending on the destination, doesn't always work.  For example, I can't paste into many applications but I can drag-and-drop.

Also, since we're pasting from the clipboard, the filename is not included which requires a manual entry of a filename upon safe from an editing application.

Thanks again.

**Comment by Jaex** [comment]
Implemented in #5548
