### ISSUE TITLE
Request: for video capture, allow to capture mouse clicks and keyboard types

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#3488]
Show on the recorded video which is clicked: mouse right/left click, keyboard keys, etc...

**Comment by Jaex** [comment]
Duplicate of #1040

**Comment by AndroidDeveloperLB** [comment]
Why duplicate?
I'm talking about all kinds of interaction.
Not just mouse. Also keyboard...

**Comment by abaumgaertner** [comment]
give try this: https://github.com/bfritscher/carnac/
