### ISSUE TITLE
Request: when deleting from list of items, actually delete the file

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#3490]
I'm talking about this:

![image](https://user-images.githubusercontent.com/5357526/42082025-a004cbae-7b8f-11e8-920a-4714003d1adb.png)

**Comment by Jaex** [comment]
This?

![](https://jaex.getsharex.com/2018/06/ShareX_hxUqRaYfhV.png)

**Comment by AndroidDeveloperLB** [comment]
Yes.
Please let us use just Del key for real deletion.

**Comment by Jaex** [comment]
It is Shift+Del.

**Comment by AndroidDeveloperLB** [comment]
Can I please customize it?
Or maybe add a button in each item for actual deletion?

**Comment by AndroidDeveloperLB** [comment]
What is this?
Spam can come even to Github?
