### ISSUE TITLE
Can't login to puush

### ISSUE THREAD

**Issue by zackory875** [ShareX/ShareX#3499]
Hi. For two days now I can't upload with my puush account. Trying to login gives me Login failed message. I can however login to the website.
![screenshot 1](https://user-images.githubusercontent.com/40823520/42268190-2ee36cd8-7f7b-11e8-9e98-c61026dc1f0f.png)

**Comment by Torubloo** [comment]
This is probably NOT ShareX related, It is a problem with their api? correct me if I'm wrong someone

**Comment by Jaex** [comment]
I can successfully login right now.

**Comment by Torubloo** [comment]
@zackory875 Try again now, is it working?
