### ISSUE TITLE
Error when installing version 12.2.0: "This program does not support the version of Windows your computer is running

### ISSUE THREAD

**Issue by liamrosen** [ShareX/ShareX#3505]
This is my version of Windows:
![image](https://user-images.githubusercontent.com/718461/42380998-b1f28608-80fd-11e8-9821-f60ce489e818.png)

12.0 worked fine.

**Comment by sylveon** [comment]
You need to install the Service Pack 1. Newer ShareX versions depend on .NET 4.6, which itself requires SP1. You currently are running the original Windows 7, without any service pack.

**Comment by xurizaemon** [comment]
I ran into this issue with a Windows 7 SP1 that lacked .NET 4.6.

I downloaded the "portable" zip from https://github.com/ShareX/ShareX/releases and tried to run it.

This has triggered Windows to try downloading .NET 4.6, so ... here's hoping :grin:

**Comment by xurizaemon** [comment]
Ugh, my comment update removed the Stale label, feel free to close this. Was just recording what happened as proto-docs.
