### ISSUE TITLE
FALSE POSITIVE ? SUSPICIOUS PROGRAM

### ISSUE THREAD

**Issue by antuketot76** [ShareX/ShareX#3507]
Check out this result : 

File Location : [HERE](https://github.com/ShareX/ShareX/releases/download/v12.2.0/ShareX-12.2.0-setup.exe)
VirusTotal Result : [HERE](https://www.virustotal.com/#/url/86215b0b6493243f209f4e1e510126f22633cd3bcf944da457ef1c7cd367a8e4/detection) OKAY
Hybrid Analysis : [HERE](https://www.hybrid-analysis.com/sample/dd32f013d2de00d1b150decbed2e2ead5807124ec87aff20f366e57933f55cd2/5b41de2f7ca3e179c13b7b45) SUSPICIOUS

![image](https://user-images.githubusercontent.com/33280865/42418846-0dc052ca-82e4-11e8-919e-8d3a635aa59d.png)

**Comment by LeonZewe** [comment]
Its simply a false positive. Or do you think he would release the code to Github with a virus in it and nobody would notice?
