### ISSUE TITLE
Capture profiles

### ISSUE THREAD

**Issue by mrandreastoth** [ShareX/ShareX#3508]
Instead of having one set of settings that affect everything there needs to be configurable capture profiles that can then be assigned to hotkeys and menu items to allow them to be quickly invoked/toggled.

**Comment by sylveon** [comment]
Hotkeys can override task settings.

**Comment by mrandreastoth** [comment]
Hotkeys are a non-visual solution. I'm looking for a visual solution. Good design makes everything visible to the user.

**Comment by Jaex** [comment]
Hotkeys are also added to workflows menu.

**Comment by mrandreastoth** [comment]
Oh, and I see that it isn't necessary to create a hotkey. That's good. OK, that solves that "issue". :)

**Comment by ShowGoShane** [comment]
> Oh, and I see that it isn't necessary to create a hotkey. That's good. OK, that solves that "issue". :)
 
Hello. If I understand the post from mrandreastoth, then I'm looking for the same solution, however, I didn't understand what the solution was. Will you help, with a more basic description?

I'm looking to have what I call a Profile, a set of settings. i.e. - the Setting; _Text (Background) has this font, at this font size, color, etc.
![IMG_ShareX_Post_01](https://user-images.githubusercontent.com/39810670/61513109-ea321600-a9b0-11e9-867c-432eaf17d220.png)

This might go with the Arrows red, double-headed, etc. Then, I might like a different setup for a User Manual and want to make sure that both of my computers have the same setting so I want to be able to save this in a 'Profile'.

Can anyone think of a way to do this with ShareX? 

To be honest, I could see wanting about 3 variations for each major feature; Task (with and without background), Speech bubble, Steps (varying sizes), etc.

Whoever can help me out with this will be my savior as this will save me so much time! 
(I'll do your laundry for a week!  ;) )

Thanks in advance for stopping to read this!
Shane
_
