### ISSUE TITLE
I am served this message everytime I attempt to take a screenshot. This has been occuring for the last few months.

### ISSUE THREAD

**Issue by Chrissawalker** [ShareX/ShareX#3516]
![capture](https://user-images.githubusercontent.com/41080046/42527493-d13942bc-8446-11e8-99f9-faa4279acfb4.PNG)

**Comment by blaize9** [comment]
It's most likely the space at the end of your day folder "07(July)-10-2018 ", windows will remove the space automatically when you create the folder ending in a space.
