### ISSUE TITLE
Multiple accounts for one service

### ISSUE THREAD

**Issue by web2033** [ShareX/ShareX#3518]
Hey!
Is it possible to make ShareX work with several accounts for one service?
Example - two Google Drive accounts, one personal and other for work.
So there will be a possibility between two of one kind.

**Comment by Jaex** [comment]
I wanted that feature too but it would require so much efforts therefore couldn't add it. Because would need to remake whole destination settings ui then.

**Comment by web2033** [comment]
No problem, I will find some workaround. Thanks anyway!
