### ISSUE TITLE
Option to remove line break in OCR

### ISSUE THREAD

**Issue by ppardi** [ShareX/ShareX#3520]
Love the OCR feature of ShareX. But if I capture text from a narrow column, line breaks are inserted after each line of the captured text. When I paste that text to a target app, I have to manually remove all the line breaks (so it "flows" properly). It would be great to have an option to automatically remove all line breaks/carriage returns.

**Comment by Jaex** [comment]
Added it now:

![](https://jaex.getsharex.com/2022/07/ShareX_OPhAvCyv91.gif)
