### ISSUE TITLE
Failing to upload SS to Imgur

### ISSUE THREAD

**Issue by sykotikkytten** [ShareX/ShareX#3526]
> 2018-07-12 18:48:40.312 - Task in queue. Job: Job, Type: Image, Host: Imgur
> 2018-07-12 18:48:40.317 - Task status: Preparing
> 2018-07-12 18:48:40.341 - Upload started. Filename: 2018-07-12_18-48-40.png
> 2018-07-12 18:48:40.773 - Error:
> Message:
> The remote server returned an error: (400) Bad Request.
> 
> Request URL:
> https://api.imgur.com/3/image
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
> 2018-07-12 18:48:40.775 - Upload failed. Retrying upload.
> 2018-07-12 18:48:41.994 - Error:
> Message:
> The remote server returned an error: (400) Bad Request.
> 
> Request URL:
> https://api.imgur.com/3/image
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
> 2018-07-12 18:48:42.009 - Task failed. Filename: 2018-07-12_18-48-40.png, Errors:
> Message:
> The remote server returned an error: (400) Bad Request.
> 
> Request URL:
> https://api.imgur.com/3/image
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Thought it was my version, checked version, saw it had an update, updated. Same thing. Restarted computer, same thing. Tried a different computer, same thing. The API for Imgur seems to be up and fully functional.
First computer - Windows 7
Second computer - WIndows 10

**Comment by MaxAkito** [comment]
I have the same error, latest version as well.

**Comment by tilerthps** [comment]
I had the same error, seems to be working now.

**Comment by MaxAkito** [comment]
This issue as been fixed for me, I did nothing to fix it. I assume it was imgur's fault.

**Comment by sykotikkytten** [comment]
Seems to be fixed now.

**Comment by itskamel** [comment]
still getting this error on my end.
