### ISSUE TITLE
Destination Settings Opens Every Time I Upload a Screenshot

### ISSUE THREAD

**Issue by Freezinater** [ShareX/ShareX#3529]
As of late, whenever I upload a screenshot, it opens the Destination Settings. It also uploads to TinyPic instead of Imgur, but I assume it may be related to the other recent issues about Imgur uploads not working, specifically issue #3526.

I am not sure why the Destination Settings are suddenly opening now.

**Comment by mabbas64** [comment]
+1 about this. Its is pretty annoying to have the Destination Settings window open up so frequently. Is there any way to close it permanently?  @Jaex

**Comment by mabbas64** [comment]
Were you able to find a solution for this @Freezinater ?

This is annoying.

**Comment by jared-dti** [comment]
Its a setting: https://drive.google.com/uc?id=1jgqyxLKP7p4wrSN457qmx19TtNYZqvQD
