### ISSUE TITLE
Scrolling Capture

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#3531]
I tried the Scrolling Capture.
The default settings made this result:
it was like it managed to scroll and take the shots, but at the result I got only the first shot and the the last shot.
Example:
instead of getting:
1
2
3
4

I got:
1
4

I used ShareX 12.0 Portable

**Comment by ZuLeweiner** [comment]
I have a similar problem. I got only the first shot, as if made a simple print screen. When I go to the "output" tab and click reset option, I can see all the shots that were made correctly. However, when click "Guess and combine" images, that's where it all gets messed up. I don't know what to do.

**Comment by anandabrata** [comment]
I have tried using the scroll capture for a webpage. I am using the Portable  12.2 version.  The functionality has given sketchy results. But even if I manage to mouse scroll capture, the image is saved as a png as whole image. Even if I save it as a gif, it still is saved as a single image and whole scroll capture is lost. Hence looking suggestions incase there is a better way to do it.

Thanks

**Comment by trollmad3** [comment]
This tool is also broken for me. Whenever I take a picture of a menu such as my Spotify playlist it stays still or does nothing for 2 seconds and says it has it when in reality it doesn't.

**Comment by iwanwibisono** [comment]
Hi, I think I have similar / same issue here.
Sometimes after I did scrolling capture there are 2 or more images in the output and I cannot remove the previous ones (can only remove the last one). Any idea?
![image](https://user-images.githubusercontent.com/46212118/52028370-c174ac00-2549-11e9-84b1-336b4ff9b42e.png)
