### ISSUE TITLE
Image wont copy itself to clipboard after you take a screenshot of a certain region then open it up in image editor

### ISSUE THREAD

**Issue by th3reallegend** [ShareX/ShareX#3534]
I have to press CTRL+Shift+C to get it copied, otherwise it doesn't copy automatically. I've tried restarting ShareX, checking the option then unchecking etc. but every time i screenshot a region, then have it open in image editor the original image wont copy itself, despite being instructed to do so.

**Comment by FurkanKambay** [comment]
I don't think the setting is for copying the original image. If you look at the `After capture tasks` menu, `Open in image editor` comes before `Copy image to clipboard` and they *are* supposed to execute in that order. Even when you press `Ctrl+Shift+C`, it copies the edited image, not the original one.

Would you find it useful if it did have an option to copy the original image before editing? If so, I suggest you open a new feature request issue and close this one.

**Comment by Thepenguin9** [comment]
As furkan described above, once you've edited the image, that image is then copied to the clipboard. I'm not at my pc currently to check, but that's the workflow at the moment

**Comment by Aokromes** [comment]
https://github.com/ShareX/ShareX/issues/3530 duplicate?

**Comment by imennodenis** [comment]
Same issue here.
