### ISSUE TITLE
Suggestion:  add ability to save image before and after editing

### ISSUE THREAD

**Issue by JesseRacine** [ShareX/ShareX#3537]
There does not seem to be a method to save a copy of the image capture before and after editing it using the built-in image editor. I tried to use both "save" and "save as" as after-capture tasks but this just leaves one copy of the image after editing it. Is there a way to do this? If not, this might make a good addition to the software.

**Comment by FurkanKambay** [comment]
I would suggest adding the option to reorder the `After-X tasks` lists wholly. Maybe even the ability to duplicate some of the items. So basically, the order and the amount of every item could be changed.

**Comment by ZennfI** [comment]
For those who want this feature, I just found a workaround that I posted here: https://github.com/ShareX/ShareX/issues/4807#issuecomment-1455895153

**Comment by jpdribbler** [comment]
> For those who want this feature, I just found a workaround that I posted here: [#4807 (comment)](https://github.com/ShareX/ShareX/issues/4807#issuecomment-1455895153)

The workaround is not working for me. If i close the editor it will just close wihtout saving. If i press enter it will just open the editor again.-
