### ISSUE TITLE
DX9 DX12的游戏截图会黑屏。

### ISSUE THREAD

**Issue by yun2673436976** [ShareX/ShareX#3539]
我运行 DEAD OR ALIVE 5游戏，这是DX9的游戏，我选择全屏游戏，ShareX在后台运行，按快捷键截图，截出来的图片要么一片空白要么黑屏请你及时解决。与其把时间没有意义的功能上，先把游戏截图黑屏的问题解决。

**Comment by Jaex** [comment]
I don't know Chinese.

**Comment by Scrxtchy** [comment]
游戏捕获不是支持或计划的功能。 如果您知道如何，欢迎自己制作此功能

**Comment by yun2673436976** [comment]
@Jaex I run DEAD OR ALIVE 5 game, this is DX9 game, I choose full-screen game, ShareX runs in the background, press shortcut screenshot, the picture is either blank or black screen, please solve it in time. Instead of taking the timeless meaning of the function, first solve the black screen problem of the game screenshot.Do not understand Chinese, please copy Chinese to https://translate.google.cn
我运行DEAD OR ALIVE 5游戏，这是DX9的游戏，我选择全屏游戏，ShareX在后台运行，按快捷键截图，截出来的图片要么一片空白要么黑屏请你及时解决。与其把时间没有意义的功能上，先把游戏截图黑屏的问题解决。

**Comment by IMJ355** [comment]
From @Scrxtchy reply :  

Game capture is not a supported or planned feature. If you know how, feel free to make this feature yourself.
游戏捕获不是支持或计划的功能。 如果您知道如何，欢迎自己制作此功能

**Comment by xlichen** [comment]
@yun2673436976    Jaex have no obligation to help you

**Comment by yun2673436976** [comment]
@xlichen 我不是叫他帮助，只是建议。一款截图软件本身的功能就是截图。

**Comment by Scrxtchy** [comment]
#848

**Comment by yun2673436976** [comment]
@Jaex A screenshot software, the core function is the screenshot. ShareX takes screenshots in the DX9 DX11 DX12 game, and the screenshots are all black. Please give priority to solving this problem. ShareX can take screenshots under any conditions. This is the most important. ShareX is a professional screenshot software that is not OCR software or even photo editing software.

**Comment by Jaex** [comment]
Giving priority not changes anything when I don't know how to do it.
