### ISSUE TITLE
SnagIt-like capture options/workflows

### ISSUE THREAD

**Issue by mrandreastoth** [ShareX/ShareX#3547]
After years of using SnagIt, there are a few things I miss from ShareX such as...

1) Being able to capture *any* window, including menus (ShareX only lists windows that are currently visible, and not ones that may be visible once the capture starts, such as a pop-up menu).

2) Panoramic capture (user scrolls/pans the region and SnagIt captures and builds the image - this eliminates issues where scrolling captures don't work).

3) Countdown capture of any type (ShareX has hard-coded capture types supporting countdown while SnagIt is more modular and allows any capture to have a countdown).

4) OCR capture.

5) Profiles (create profiles that are not necessarily bound to hotkeys).

The thing I *really* love about ShareX is how it can be configured to display the current capture as a notification and the multi-region feature. However, even SnagIt has a multi-region feature nowadays.

**Comment by neilrush** [comment]
The panoramic capture is a must. I always have problems with the automatic scrolling, and I would like to scroll manually just like snagit.
