### ISSUE TITLE
Can't move set the paths of ShareX personal folder.

### ISSUE THREAD

**Issue by OldFanta** [ShareX/ShareX#3549]
At first, I set a folder in One Drive as my local Document folder.
And it does set there, as you can see in following picture:
![image](https://user-images.githubusercontent.com/30617361/43046193-4ecacc68-8df8-11e8-8a2a-f49581b46b93.png)
And then, I wanna change it to another folder, such as "C:\Program Files (x86)\ShareX", however,after I restart ShareX as it asked,it change back to the folder before, the change doesn't work.:(
I used to reinstall it many times, but it never changed.
can you give me some advice? Thank you.

**Comment by Jaex** [comment]
You can't use program files folder without ShareX running as admin. So you must not put personal folder inside program files.

**Comment by OldFanta** [comment]
Well,the same as "C:\Users\Muyao\Documents"? I changed it to here,but it doesn't work,neither.
I just have two disk——One is SSD as system,another is HDD as backup. so should i put it in HDD?

**Comment by OldFanta** [comment]
Emmm... I download it from [Offical Website](https://getsharex.com/) again, it seems work well now(before now, i downloaded it from Microsoft Store & Steam).
I am sorry to trouble you, thank you again.

**Comment by OldFanta** [comment]
@Jaex ok，I think i know what's wrong with my ShareX.
when I set the path `C:\Users\Username\Documents\ShareX`, it obviously shown as `%Documents%\ShareX`, however,the default Documents path is `C:\Users\Username\OneDrive\Documents\ShareX`.
This may be the reason?

**Comment by trollmad3** [comment]
![2018-07-27_11-55-15](https://user-images.githubusercontent.com/7843719/43338531-f197c60a-9193-11e8-8e82-0cad7d4b84df.png)

**Comment by AuroraKy** [comment]
Why does setting the personal folder to another folder like 
"P:/ShareX/Data"
leave a file called PersonalPath.cfg in Documents/ShareX/
that if removed or renamed resets the configuration to Documents/ShareX/ (Thus it thinks it's my first opening of the programm)?
![personalPath.cfg with contents in documents](https://i.imgur.com/O6honNe.png)
I think this personalpath should not be saved in Documents/ShareX since the entire point of setting it for me was to not have a shareX folder in Documents.

![Paths](https://i.imgur.com/PbVBOAd.png)

**Comment by Jaex** [comment]
Because it need to store path somewhere otherwise how it can know. I initially stored it in userdata folder but Windows Store unable to read it therefore as last resort I needed to store it in Documents. You can also store it near ShareX.exe.

**Comment by AuroraKy** [comment]
How do I store it in the installation folder?

**Comment by Jaex** [comment]
Cut PersonalPath.cfg and paste to that folder.

**Comment by AuroraKy** [comment]
Well that was an extremely simple solution, thank you very much for telling me that

**Comment by Viper007Bond** [comment]
I'm still getting the dang folder in my Documents.

Seems like all of this should go into my user folder where most apps store their settings.

**Comment by nepphhh** [comment]
Cutting `PersonalPath.cfg` and pasting in the destination personal folder does not prevent ShareX from forgetting the path on the next boot and remaking its application folder in the middle of _my personal documents_.

Having it default to making a folder in my documents without offering me the option to put it elsewhere is already ridiculous, but not being able to fix this after-the-fact is too much. Why is this data not stored in `%appdata%`? This is incredibly lazy design and needs to be fixed.

**Comment by TheComputerNerd88** [comment]
@nepphhh What Jaex means is that you need to copy PersonalPath.cfg to wherever you installed ShareX (normally C:\Program Files\ShareX)

However, I agree with you on the other points. Why is there no option to store things in other places in the UI like this? If you can't get the Microsoft Store version to access the user data folder, where else can you put it? Why is there little to no documentation on these things?

It may sound like I'm hating on ShareX, but I'm not. Even though there are some downsides like these, when you know how to use it, ShareX is an **amazing** program (despite the fact that I only discovered this today!)

@Jaex as far as I'm aware there's no documentation for ShareX. Maybe consider creating some?

**Comment by Aholicknight** [comment]
This issue has been closed since Jul 24, 2019.
