### ISSUE TITLE
ShareX not opening, no error code.

### ISSUE THREAD

**Issue by Mistdancer** [ShareX/ShareX#3551]
I've tried re-installing multiple times, closing down other background programs, and also tried the Steam version, to no avail. Opening it does nothing, not even a background process opens (to my knowledge.) I'm unsure of how to fix it, any help?

**Comment by Mistdancer** [comment]
It did run at one point, and for quite a while. I also tried installing an older version of ShareX, but that didn't change anything.

**Comment by stuntguy3000** [comment]
Open ShareX, then right after go to the Event Log -> Application

![image](https://user-images.githubusercontent.com/1522389/43129036-99f6b3b6-8f72-11e8-8721-d3d6bb51979d.png)

Do you see any errors?

**Comment by detourious** [comment]
I'm also having this issue. I am unsure whether or not I should create a new issue.
