### ISSUE TITLE
Problems with screenshot color

### ISSUE THREAD

**Issue by UmptyMaDoo** [ShareX/ShareX#3557]
I'm not sure if this is sharex, or something i did on my computer, but I haven't a clue what's going on.

For some reason, every screenshot I take has this slightly burned color. Changing color settings on my computer doesn't seem to change this fact, and if i screenshot the screenshot, the colors continue to get more burned.
[https://i.imgur.com/cm4nJM6.png](url)

**Comment by anaknickerbocker** [comment]
What type of capture are you using? Do you get different results with different types of captures?

**Comment by UmptyMaDoo** [comment]
I did end up discovering that this bug was unrelated to sharex. The default screenshot utility yields the same color. 
That being said, if you have any suggestions i'm open to them because i still haven't fixed it.
