### ISSUE TITLE
Ability to change font color

### ISSUE THREAD

**Issue by stephanieroll20** [ShareX/ShareX#3558]
The default font color (on the inside of the text) is white, and cannot be changed. I can change the background of the text box or the outline of the text, but not the inside of the text. 

As a result, I can't use a white background when annotating a screen shot. This is a problem for many users.

As a user of ShareX, I would like to be able to change the inside color of the letters of text so that my users can see the annotations.

![fontcolors](https://user-images.githubusercontent.com/38018371/43272594-3819e62a-90af-11e8-9b2f-f9d2c996a1ef.png)

**Comment by Jaex** [comment]
It is already changeable, you can even make it gradient color:

![](https://jaex.getsharex.com/2018/07/ShareX_kGKkHxX1Z7.png)

**Comment by BopItFreak** [comment]
Except I have this issue as well.... @Jaex 

Can you explain exactly how to change the outer color? I can't figure it out.

**Comment by fodaley** [comment]
Came here for same issue. Changed font color to Green...but the red outline remains.

Example:
![image](https://user-images.githubusercontent.com/1638468/102723126-0a67b200-42d4-11eb-8dd7-d16e50cf84db.png)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/12/ShareX_OnvUsipOkq.png)

**Comment by ars4l4n** [comment]
> Came here for same issue. Changed font color to Green...but the red outline remains.
> 
> Example:
> ![image](https://user-images.githubusercontent.com/1638468/102723126-0a67b200-42d4-11eb-8dd7-d16e50cf84db.png)

I'm on the latest ShareX version and couldn't change the font color either. Whenever I picked a color from the gradient and pressed "Ok", ShareX just ignored it and stayed on the previous color. 

The fix was to click "Show Standard Colors" and pick one out of them instead of the gradient.

**Comment by GaryEarthling** [comment]
Came here looking for the same thing. Background color is on the main toolbar but you have to double click to get to the text color.

![Screenshot 2022-07-14 065037](https://user-images.githubusercontent.com/54581080/178966558-85ee0551-6f47-4f98-ae6c-473bfc250763.png)
.

**Comment by Telvin7** [comment]
I uninstalled the application after I realized that the outer color of the font (frame color) is also the color for arrows, shapes, etc. Those. I don't need the outer font color, I can't remove it. If I make the outer font color white, the arrows turn white too! Who thought of such savagery?
