### ISSUE TITLE
hubiC Support

### ISSUE THREAD

**Issue by ThePierrezou** [ShareX/ShareX#356]
Hello,
Can you add a support for hubiC please.
It's a file hoster with 25 GO free :)
( i don't know but i think it can be help you : https://api.hubic.com/ )
Thanks 
ThePierrezou

**Comment by Fatih54102** [comment]
+1

**Comment by Jaex** [comment]
Added by @Kouga-

**Comment by R0GGER** [comment]
Can not find Hubic in Destinations...
screenshot: http://imgurl.nl/2l

**Comment by McoreD** [comment]
@R0GGER reasoning is explained here https://github.com/ShareX/ShareX/pull/452
