### ISSUE TITLE
Could not upload .txt file to ghostbin.

### ISSUE THREAD

**Issue by trollmad3** [ShareX/ShareX#3560]
Ghostbin is one of the text uploaders contained in the [Custom Uploaders repository](https://github.com/ShareX/CustomUploaders) and is currently _**broken.**_

![image](https://user-images.githubusercontent.com/7843719/43352346-6c220dfe-91df-11e8-9539-0f3cfce9081b.png)

**Comment by trollmad3** [comment]
@popey456963 So I guess this has to get deleted now?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2018/07/chrome_xFxMruWGUc.png)

This page opens.

**Comment by trollmad3** [comment]
@Jaex That's not what I'm trying to say _**AT ALL.**_ When you upload a .txt file to ghostbin it says that and then prevents it from uploading using sharex. Try it yourself and you will get the same error. 

![image](https://user-images.githubusercontent.com/7843719/43370977-f0c3493a-9345-11e8-9e4d-3abf6483badc.png)

**Comment by popey456963** [comment]
@trollmad3, I'm afraid we have no way of circumventing this system, unless ghost bin has an API which does not have cloud flare in front of it.

**Comment by Techial** [comment]
Submitted fix to this issue.
