### ISSUE TITLE
Sugestion: Watch folders for new files and upload them

### ISSUE THREAD

**Issue by Far-Se** [ShareX/ShareX#3561]
Sugestion: Watch folders for new files and upload them

It's good for example if a record a video with Windows GameTab, and it saves the file in a folder, and then ShareX would upload it based on settings.

**Comment by popey456963** [comment]
Watch out for the implementation of this, some applications (especially video recorders) will update the file iteratively (every X seconds).  It would be a bad idea to reupload the file every single time.

**Comment by Jaex** [comment]
It is already exists.
