### ISSUE TITLE
Feature req: open editor after capture when clicking on preview image 

### ISSUE THREAD

**Issue by olsonnn** [ShareX/ShareX#3562]
Feature req:

Most of the time i don't want to open the editor after capture image.
So the idea: after capture allow to click on the preview image in the right corner to open the editor.

Any other recommendations how to do this EASY?
What i have now: after capture press ctrl 1 to open the editor but then it does not allow me DIRECT select the image from clipboard.

**Comment by Jaex** [comment]
This option:

![](https://jaex.getsharex.com/2018/07/ShareX_tMxL2HWvat.png)

**Comment by olsonnn** [comment]
exactly what i needed! thanks!

**Comment by zuckerthoben** [comment]
I can't find this option in version 13.0.1. As I am just writing this, I found out that you can configure this in the ShareX Main-Window and then "After capture tasks". Don't know why I had so much trouble finding this.

**Comment by trevorjobling** [comment]
As zuckerthoben said, ToastWindowClickAction is no longer an option. But "After capture tasks" is not a solution, as that affects all captures. I specifically want to open the editor "if and when" I click on the toast image, as olsonnn originally did. Is there any way to achieve this now?

**Comment by olsonnn** [comment]
? i'm not sure what you want but the option is still there. 
![image](https://user-images.githubusercontent.com/36011279/107426472-8f2abb80-6b20-11eb-9935-d9b7a2a91865.png)

"effects" all captures... but you don't need to click on it ? :-)?

**Comment by trevorjobling** [comment]
Oops. I suffered a bout of temporary blindness, or maybe stupidity! Either way I have now found the setting and it is perfect for my needs. Thank you.

**Comment by uselessscat** [comment]
I think this has been moved to their own tab in 13.5:

![image](https://user-images.githubusercontent.com/15332878/119558725-c50e4b80-bd6f-11eb-8aae-753bdc0c45be.png)

**Comment by abdusco** [comment]
@uselessscat The action is now titled "Edit image"

![image](https://user-images.githubusercontent.com/3243482/135268108-8d13e783-e3f2-4c64-a6c7-c51c1c0382dd.png)

**Comment by the-Arioch** [comment]
> @uselessscat The action is now titled "Edit image"
> 
> ![image](https://user-images.githubusercontent.com/3243482/135268108-8d13e783-e3f2-4c64-a6c7-c51c1c0382dd.png)

Well, no. It is still "annotate" at places :-)

![firefox_fdx4Ylb35I](https://github.com/ShareX/ShareX/assets/937774/a0c5a082-bfb3-421b-8323-c9d8f2060ad1)
