### ISSUE TITLE
Screenshot delay causes region capture to not recognize regions

### ISSUE THREAD

**Issue by begberts** [ShareX/ShareX#3567]
If you have screenshot delay enabled, the region capture does not recognize various regions on screen. 

Build 12.2.0

Steps to reproduce:
1. Make sure screenshot delay is disabled.
2. Open Sharex and do a region capture.
3. Mouse over various regions on the screen and note how the different regions are highlighted.
4. Now enable screenshot delay.
5. Do a region capture and note how none of the different regions are highlighted and you can only capture either a fullscreen or a manually selected area like in region light.

**Comment by Jaex** [comment]
I don't think it is to do with delay option. I can't reproduce it like that. But it happens randomly sometimes.

**Comment by Asmageddon** [comment]
This was driving me mad, I thought that at some point the functionality just broke, but then I found this issue.

And I can confirm it, disabling screenshot delay fixed the issue. Enabling it breaks the functionality again, even with the delay set to `0.0`. Using Windows 10 here.

**Comment by Asmageddon** [comment]
The issue appears to indeed be resolved in the current versions. I can take region screenshots just fine with a 0.2s delay.
