### ISSUE TITLE
Bug: "capture region and open in image editor" doesn't work after you put some graphics over the area before capturing

### ISSUE THREAD

**Issue by snakecase** [ShareX/ShareX#3569]
I have a preset called "Capture region and open in image editor". All it does is captures a region I select and then opens it in image editor (no clipboard copying, no uploading etc). The problem occurred when I tried to capture a picture that way with some arrows put before capturing. It just blinks and does nothing like being cancelled with Esc. How to recreate:

Start capturing
Put some arrows, borders etc
Select "Region: rectangle" again
Try to capture a region

Latest version, 12.2.

**Comment by Jaex** [comment]
It is not a bug but feature. So if user already annotated image then it won't show image editor again to annotate.
