### ISSUE TITLE
way of disabling uploads out of app

### ISSUE THREAD

**Issue by Muramas** [ShareX/ShareX#3570]
It would be nice to have a way of disabling upload by default either by registry or command switch while installing.

**Comment by campbeb** [comment]
On a new install of ShareX, the first upload will trigger a warning to ensure the user knows it will happen. You can then choose to disable uploads.

The settings can been seen here and can be edited in configuration file, ApplicationConfig.json.

![image](https://user-images.githubusercontent.com/1089399/43616307-e2d5bc58-9689-11e8-8868-f0bab4596b3c.png)

**Comment by Jaex** [comment]
Duplicate of #2861
