### ISSUE TITLE
Default action on clicking file in history

### ISSUE THREAD

**Issue by Muramas** [ShareX/ShareX#3571]
After making a snip it goes into your history, is there a way to have it so the default action when doubleclicking on the filename it goes to the editor instead of the viewer / browser?

**Comment by campbeb** [comment]
The default action can not be changed. To edit, you must right click.

**Comment by Muramas** [comment]
That is what I was thinking. Is there a way of changing this?

**Comment by campbeb** [comment]
If you wanted to build your own version of ShareX, you could change it. Otherwise, it would have to be a new feature added.
