### ISSUE TITLE
TinyPic upload fails until Login button in Destination Settings is clicked

### ISSUE THREAD

**Issue by beneficadoramocaba** [ShareX/ShareX#3573]
Affected system: Windows 7 + ShareX v12.4.1

I previously reported bug #3186, which was fixed. There is a new problem that may be related (possibly occurring since the fix). 

I have entered and saved my account credentials for TinyPic in the Destination Settings. If the Login button there is clicked, uploading works as expected, but only for a certain amount of time. After that time has elapsed, when I tell ShareX to upload, the task's progress bar climbs to 100%, then a few seconds later an error is reported:

> 2018-08-04  00:02:31.097 - Task in queue. Job: FileUpload, Type: Image, Host: TinyPic
> 2018-08-04 00:02:31.098 - Task status: Preparing
> 2018-08-04 00:02:31.100 - Upload started. Filename: test.jpg, Filepath: C:\test.jpg
> 2018-08-04 00:02:31.740 - Upload failed. Retrying upload.
> 2018-08-04 00:02:33.345 - Task failed. Filename: test.jpg, Errors: **Bad User Credentials: Invalid or no user credentials (username or pass) in a request that required username/pass to be valid.**

To bypass the problem, I must open the Destination Settings, go to the TinyPic section and click Login again. The login is successful with the previously saved credentials, and the subsequent upload attempts function as expected, until it stops working again.

Restarting Windows, putting the computer through a sleep/wake cycle. and restarting ShareX do not seem to cause the problem to return. Therefore my guess is that it may be time-related, such as a cookie or authentication token expiring and not being renewed. Perhaps the code being run by the [Login] button is not identical to the code used in the upload task?

**Comment by beneficadoramocaba** [comment]
Behaviour is identical in ShareX v12.3. I've included the log, but there's not really any useful information in it.
[ShareX-Log-2018-11.txt](https://github.com/ShareX/ShareX/files/2592303/ShareX-Log-2018-11.txt)

**Comment by stuntguy3000** [comment]
Here is what happened to me which _I believe_ is sufficient intended behavior.

Upon my first upload with no credentials specified, ShareX failed the upload and prompted me to login. Once I successfully logged in, any further attempts to take a screenshot successfully went ahead and were uploaded to TinyPic.

Is this what you are referring to?

**Comment by beneficadoramocaba** [comment]
Hi @stuntguy3000, I've attempted to clarify the first post somewhat, but in essence: My credentials are correctly saved in ShareX (if I click the Login button, the login succeeds). However, after a certain period has elapsed (see OP last paragraph) ShareX seems to stop using the credentials and I must to go back into the settings and click Login again, which I don't believe is the intended functionality.

**Comment by sdugoten** [comment]
yes, same issue.  After you manually login to Tinypic in ShareX for a period of time, it timeout and you will have to click on the login button again.

**Comment by beneficadoramocaba** [comment]
Thank you for confirming it's not just me, @sdugoten 

Updated the first post to reflect that this continues to be an issue with v12.3.1,

**Comment by beneficadoramocaba** [comment]
And v12.4.1, :)

**Comment by beneficadoramocaba** [comment]
Well, might as well close this since the host is shutting down.
