### ISSUE TITLE
ShareX does not screenshot entire screen when Device Manager is focused

### ISSUE THREAD

**Issue by Accelyte** [ShareX/ShareX#3574]
I'm on Windows 10 Home using ShareX v. 12.2. I have my ShareX set so that when I click PrtScr, the entire screen is captured, and File Explorer opens to show me the file. However, this does not happen when the Device Manager is open and focused. Clicking Ctrl+PrtScr still opens the region selector; clicking Alt+PrtScr still captures the open and focused Device Manager window, with File Explorer opening to show me the file. If I click PrtScr with the Device Manager window opened and focused, ShareX ignores it completely. I can still paste the screenshot into mspaint though.

**Comment by Jaex** [comment]
When window which is ran as admin active then printscreen hotkey not works. You can click taskbar then press printscreen to workaround that.

**Comment by stephen147** [comment]
Thanks, I was just about to post a bug report but this entirely makes sense.

**Comment by Nicofisi** [comment]
I had the same issue with scrolling capture of the device manager, running ShareX as admin fixed it, nice.
