### ISSUE TITLE
Add support for multi-monitor setup with different DPI settings

### ISSUE THREAD

**Issue by mwidmann** [ShareX/ShareX#3578]
My setup consists of two monitors: main display 3000x2000 set to 200% scaling, secondary display 2560x1440 set to 100% scaling. 

When the ShareX window is on the main display the size is maybe a little too small
![chrome_2018-08-08_16-28-10](https://user-images.githubusercontent.com/251322/43843533-18e9e4f2-9b28-11e8-931e-051be2f9b16a.png)

When the ShareX window is on the secondary display the size is huge
![conemu64_2018-08-08_16-27-13](https://user-images.githubusercontent.com/251322/43843572-2c4f7048-9b28-11e8-932c-57b6e1428b12.png)

The Chrome window in the background is for size comparison. It is actually wider on the secondary display, it wouldn't fit the main one.

**Comment by NicoHaase** [comment]
Isn't this the same as #1477?
