### ISSUE TITLE
[Question] Where is the right place to put APIKeys.OCRSpaceAPIKey value?

### ISSUE THREAD

**Issue by YueLinHo** [ShareX/ShareX#3580]
AFAIK, [ocr.space](https://ocr.space/) is used as OCR tool, and that OCR needs a API key.

Is there a config file for putting this OCR API key?

or put it [here](https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/APIKeys/APIKeys.cs#L71)?
```
namespace ShareX.UploadersLib
{
    internal static partial class APIKeys
    {
        // Image uploaders
        ...
        public static readonly string OCRSpaceAPIKey = "";
    }
}
```

**Comment by YueLinHo** [comment]
cf. #1692

**Comment by sylveon** [comment]
Yeah, that should work. Make sure to not commit it however.

**Comment by YueLinHo** [comment]
@sylveon Thanks.
