### ISSUE TITLE
(403) Forbidden.

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#3585]
What Does this mean exactly?  Things I tried. Refreshed authorization, Logged out and back in. To no avail.

Message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://picasaweb.google.com/data/feed/api/user/default/albumid/default

Response:
Access forbidden.

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

**Comment by thedanioner** [comment]
I have exactly the same error. Any solution?

![nvidia share_2018-08-13_18-41-33](https://user-images.githubusercontent.com/16803726/44063988-85a52490-9f28-11e8-9f6a-3ec6b7750e18.jpg)

**Comment by matthewburnett** [comment]
Couldn't repro, did this just start happening? Personal account or business?

**Comment by jdcollier1968** [comment]
Mine cleared itself after a few hours. No longer an issue here.

**Comment by trollmad3** [comment]
Site works perfectly fine if you use a web browser.
