### ISSUE TITLE
Screen Recording Devices Not Working!!

### ISSUE THREAD

**Issue by MiyreaZED** [ShareX/ShareX#3586]
About an hour and a half ago I was able to record a video with audio from the game and the discord call I was in. I tried to mess with the microphone settings and audio input in the screenrecording options and now it no longer shows any of my many audio devices, and when I click install recording devices it does NOTHING! I click download to download ffmpeg and it comes up with this error so basically I can't record video at all now! HELP!

![2018-08-16_00-23-23](https://user-images.githubusercontent.com/42428002/44188345-0cf5e380-a0eb-11e8-9daa-36532a0bc396.png)

**Comment by Dalexz4** [comment]
<a href="https://davidolatestsong.com.ng/broda-shaggi-oya-hit/">Broda Shaggi Oya Hit Me</a>
