### ISSUE TITLE
Http uploader: The request was aborted: The connection was closed unexpectedly

### ISSUE THREAD

**Issue by duncte123** [ShareX/ShareX#3587]
After a windows update, I keep getting this message while trying to upload an image. 
I tried using an old uploader that worked fine a while back but it's also giving me the same message now.

```prolog
Error: Message:
The request was aborted: The connection was closed unexpectedly.

Request URL:
[redacted]

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

**Comment by matthewburnett** [comment]
Full log

**Comment by duncte123** [comment]
@matthewburnett where can I find the full log?

**Comment by matthewburnett** [comment]
Debug > Debug log > copy all

**Comment by duncte123** [comment]
Here is the debug log https://ghostbin.com/paste/2uphw

**Comment by matthewburnett** [comment]
If you're on Windows 10 you can try our Store build, otherwise could you use debug again with the default Imgur uploader? This looks to be a problem on your host though.

**Comment by duncte123** [comment]
The default imgur uploader works, I'm starting to think that it is a cloudflare issue as some other uploader that I made myself a while back randomly stopped working
