### ISSUE TITLE
 Can not resolve the remote name: 

### ISSUE THREAD

**Issue by Azius** [ShareX/ShareX#3588]
can anyone help pls?

Message:
Can not resolve the remote name: 'mydomain.com'

Request URL:
https://mydomain.com/up.php

Stack trace:
   w System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   w System.Net.HttpWebRequest.GetRequestStream()
   w ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by trollmad3** [comment]
Create the folder `Folder` in that directory.

**Comment by cat-toy5** [comment]
> can anyone help pls?
> 
> Message:
> Can not resolve the remote name: 'mydomain.com'
> 
> Request URL:
> https://mydomain.com/up.php
> 
> Stack trace:
> w System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
> w System.Net.HttpWebRequest.GetRequestStream()
> w ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

can you tell me how did you fix it please because i got the same problem thanks for replying @Azius
