### ISSUE TITLE
(Question/Request) Edit screenshot

### ISSUE THREAD

**Issue by GrPK** [ShareX/ShareX#3589]
Hello! Sorry if it was asked before, but I searched for a while and there was no clear answer for my question. Is there any way to edit a screenshot before we take it? I mean, not opening an editor after we screenshot it, but the screenshot has already the edit. To understand better what I mean (and I hope that nobody gets angry, because I just want to clarify what Im asking), look at the snipaste/lightshoot option to edit the screenshot before it is taken, so that there are fewer tasks to do. 
Thanks for your time and have a great day!

**Comment by Jaex** [comment]
Region capture have toolbar with annotation tools.

**Comment by GrPK** [comment]
Thanks!
