### ISSUE TITLE
Disable auto upload as part of default installation

### ISSUE THREAD

**Issue by mrkanaly** [ShareX/ShareX#3590]
Having auto upload enabled has led to numerous times when installed on new computers that information that should not be uploaded to imgur was accidentally because Sharex out of the box is configured to upload every screenshot to imgur. Without some kind of option or modified installer that will allow this to NOT be enabled on installation, deployment of this app at large scale in a group will not take place, despite how great it is.

**Comment by sylveon** [comment]
First screenshot will ask the user to upload or not and the selection will persist. Besides, you can deploy it with an accompanying config file which has uploads disabled.

**Comment by AndrewZamora** [comment]
Please disable this by default.
