### ISSUE TITLE
Is there a way to automatically delete images?

### ISSUE THREAD

**Issue by trollmad3** [ShareX/ShareX#3591]
I have a very small system space and do not know how to make it automatically delete images. Is there a way?

**Comment by Jaex** [comment]
Don't save them.

**Comment by trollmad3** [comment]
@Jaex I would like to save them, but is there a way to automatically delete them after a certain time?
??

**Comment by Jaex** [comment]
No.

**Comment by trollmad3** [comment]
Darn.
