### ISSUE TITLE
Magnifier tool

### ISSUE THREAD

**Issue by repository** [ShareX/ShareX#3593]
A magnifier tool, like the one shown while capturing, would be great as a standalone feature. It'd also be better if it worked dynamically, with changing content, i.e. gifs or videos.

**Comment by Memnarch1113** [comment]
![new-prime-tower](https://user-images.githubusercontent.com/1627557/46418627-2df5b080-c6fa-11e8-810a-ec5722b6e146.jpg)

Here's an example
