### ISSUE TITLE
Ошибка 400

### ISSUE THREAD

**Issue by DucKKTheFun** [ShareX/ShareX#3596]
Хотел сделать Gif с размером изображения
![2018-08-20_10-17-23](https://user-images.githubusercontent.com/42533267/44325971-f0e3a080-a462-11e8-9d7b-bccf753a5acc.png), но выдало ошибку 400 
![2018-08-20_10-07-11](https://user-images.githubusercontent.com/42533267/44326022-11135f80-a463-11e8-9213-bfaca55bc5f4.png), вот как её исправить? если знаете то напишите мне пожалуйста...

**Comment by Jaex** [comment]
Imgur API have 10 mb upload size limit. This is why it gave you this error.

**Comment by DucKKTheFun** [comment]
спасибо
