### ISSUE TITLE
Support Newer SSH Ciphers and MACs etc

### ISSUE THREAD

**Issue by Cronus89** [ShareX/ShareX#3599]
Upon securing my sshd ShareX's usage of ssh does not allow secure modern(ish) ciphers kex's etc

for instance

curve25519-sha256@libssh.org          -- [info] available since OpenSSH 6.5, Dropbear SSH 2013.62

is not supported.

And other Older MACs,  is this from your 3rd party ssh lib?
Can a newer one be used thats more modern?

**Comment by Jaex** [comment]
Shows whats supported here: https://github.com/sshnet/SSH.NET
