### ISSUE TITLE
Request: Add support for Anonfile and Bayfiles

### ISSUE THREAD

**Issue by Dyras** [ShareX/ShareX#3600]
Greetings! Bayfiles is back with a new website, based on Anonfile. So if you add support for one you could easily get support for both.

These sites are seemingly all based on Anonfile:
https://anonfile.com/
https://bayfiles.com/
https://megaupload.nz/
https://myfile.is/us

**Comment by Jaex** [comment]
You can use custom uploader like this:

```json
{
  "DestinationType": "ImageUploader, TextUploader, FileUploader",
  "RequestURL": "https://anonfile.com/api/upload",
  "FileFormName": "file",
  "URL": "$json:data.file.url.full$"
}
```

**Comment by Dyras** [comment]
They just updated their API. Here's a new version

```
{
  "Version": "13.0.1",
  "DestinationType": "ImageUploader, TextUploader, FileUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://api.anonfiles.com/upload",
  "Body": "MultipartFormData",
  "FileFormName": "file",
  "URL": "$json:data.file.url.full$"
}
```
