### ISSUE TITLE
problem with sharex and encrypted drives

### ISSUE THREAD

**Issue by MightyElemental** [ShareX/ShareX#3602]
I currently have two hard drives in my laptop. I have ShareX installed on the C drive however, the sharex config files are on the other drive (B) which is encrypted with bitlocker.
When I turn my laptop on, shareX displays a flood of warnings saying it cannot find the config files and the screenshot folder and all sorts. I go to unencrypt my drive, restart sharex and then I have to redo all the options because they were reset to default.

Is there a way to change where sharex looks for the config file?

**Comment by matthewburnett** [comment]
Turn on auto-unlock. 
![image](https://user-images.githubusercontent.com/10692069/44632820-72e63480-a94f-11e8-9ab0-c71f649dc5ef.png)

and you can change config location from App settings
![image](https://user-images.githubusercontent.com/10692069/44632821-8c877c00-a94f-11e8-9e94-094302adbca2.png)
