### ISSUE TITLE
Unable to authorize Imgur in version 12.2

### ISSUE THREAD

**Issue by bsquidwrd** [ShareX/ShareX#3607]
Imgur authorization page opens, I sign in and click "Allow" and receive the below error:

```json
{
    "data": {
        "error": "Unauthorized",
        "request": "/oauth2/authorize",
        "method": "POST"
    },
    "success": false,
    "status": 403
}
```

**Comment by AxelPina** [comment]
This happens to me as well when I try to link my imgur account to the application.

**Comment by ShizCalev** [comment]
Likewise here.

**Comment by bsquidwrd** [comment]
I was thinking it was an error with the Client ID when attempting to authorize.

If they're having degraded performance across all platforms, I'll wait and test again after it is resolved and see how that goes.

**Comment by AxelPina** [comment]
@bsquidwrd @ShizCalev The issue has been fixed, you can now link ShareX with imgur. Tried it just now.
