### ISSUE TITLE
Add m2ts extension when i upload on youtube

### ISSUE THREAD

**Issue by EngineExt** [ShareX/ShareX#3608]
I set this extension to upload on youtube, but I receive an error.
YouTube suport this format video File
https://youtu.be/Z_n__sz9qz8

![jmve1ex](https://user-images.githubusercontent.com/28253387/44910353-8caac180-ad2b-11e8-97d2-1ff1bd46e262.png)

**Comment by Jaex** [comment]
https://support.google.com/youtube/troubleshooter/2888402?hl=en

I guess I should just remove file extension check.

**Comment by EngineExt** [comment]
>I guess I should just remove file extension check.
Yes, if its posible.
