### ISSUE TITLE
Drawing: Step - Make step number/letter configurable

### ISSUE THREAD

**Issue by Chefkeks** [ShareX/ShareX#3611]
Hey there,

occasionally doing screenshots with **Drawing: Step** and on every new screenshot the steps are set back to 1 (or A) and a continuous numbering from e.g.
Screenshot 1 - Step 1 + 2
Screenshot 2 - Step 3
Screenshot 3 - Step 4
Screenshot 4 - Step 5 -7 
is not really possible. Or am I mistaken here and there is an option already?

Therefore it would be great to have an enhancement to define the starting number/letter for _Drawing: Step_ via the menu, so you can start at e.g. 8 for screenshot 5.

Btw. currently doing this workaround: Adding step 1, step 2 and step 3 for example and move them all in the same position so step 3 is above step 1 and 2 and you only see step 3 on the screenshot, but a real solution via an option would be great!

Thanks in advance!
Michael

**Comment by Jaex** [comment]
Currently as workaround I'm just moving initial steps outside of screenshot area.

**Comment by Chefkeks** [comment]
That's an even better workaround 😁 👍

**Comment by Jaex** [comment]
Added by @Fyers

**Comment by Chefkeks** [comment]
So nice 😁 👍 
Thank you @Fyers

**Comment by Taroslord** [comment]
Additional question:
Is there a way to add a second count starting from 1 inside the same shot?
I would like to count from 1,2,3 and restart a second counting starting at 1 at a different position.

So I could do this: 1,2,3,1,2,3,4,5 etc.

Currently I create another screenshot to start counting from 1 in the same image.

**Comment by Devar** [comment]
> Additional question: Is there a way to add a second count starting from 1 inside the same shot?

Also wondering this, sometimes the ability to start a separate count set would be handy without having to save/commit an image and re-open to apply a new count set on top.
