### ISSUE TITLE
Switch Between Screen and Webcam During Capture

### ISSUE THREAD

**Issue by sr10952** [ShareX/ShareX#3613]
Hi,
Again, I love ShareX.
I would love to see the option of being able to record both, the screen and the webcam (Say, a small window on the screen for the webcam and the rest should be the monitor)
I do understand that it may be difficult to get this as a feature, but what I would love to see added, is the ability to "change" the video source during a recording session. 
Say, you want to explain something for the audience and then show it on the screen. I would add the button right next to the Stop and Abort buttons, and/or a hot key to swap
How about?

Thank you so much for this free utility!

**Comment by Scrxtchy** [comment]
Regarding a swap button, this doesn't really seem all that possible in something that makes a lot of sense using ShareX.

We'd have to be outputting to a streaming output on the computer. As the recorder will save this stream, as another screen recorder process will stop and start for each transition of video input streams. 
There's a good article about it here; https://stackoverflow.com/questions/42737129/change-ffmpeg-input-on-the-fly

However,
Overlaying your desktop with your webcam doesn't seem all that hard though. A solution like [CamDesk ](https://sourceforge.net/projects/camdesk/)is really useful for something like this, even though the project is abandoned 
![image](https://user-images.githubusercontent.com/12771982/46577376-230c8a00-ca32-11e8-9d78-962a0c04726c.png)
