### ISSUE TITLE
All shareX operations are extremely slow!

### ISSUE THREAD

**Issue by seitzbg** [ShareX/ShareX#3614]
It takes 5-10 seconds after hitting the capture region button for the capture tool to show up. (Never been the case for me, been using for many years).

It takes almost 30 seconds for the Sharex -> task settings window to pop up.

Any help/advice would be appreciated!

I am on the latest released ShareX and Win10 1803 (17134.254)

**Comment by AndreiGK** [comment]
seitzbg : i had installed  shareX yesterday and it very fast doing screen captur faster then 1 sec

**Comment by seitzbg** [comment]
I found the issue to be Acronis backup software and 'active protection'.  Sorry for the ticket!
