### ISSUE TITLE
[Resolved] Save to clipboard not working on FB message box

### ISSUE THREAD

**Issue by GrPK** [ShareX/ShareX#3615]
Hello! As the title describes the problem. Try on any FB conversation, it wont et you CTRL-V it in the box. On other programs, like Telegram, it works. Thanks in advance!

**Comment by Donkie** [comment]
Tested just now on ShareX 12.2 and it works without problem

**Comment by GrPK** [comment]
I have the "copy file to clipboard" on after capture tasks and it doesnt work in fb conversation. I need to open sharex and copy image from there. On telegram it works as it should, without opening the app

**Comment by GrPK** [comment]
Nevermind. I chose the "save file", not "save image", There are 2 different options. Sorry and thanks for help!
