### ISSUE TITLE
Delay when using hotkey and predefined coord screenshot

### ISSUE THREAD

**Issue by tayl** [ShareX/ShareX#3617]
Hello,

I have a use case where I'm quickly moving through different frames and hitting a hotkey defined in ShareX to take a screenshot of a predefined area. The process works (quite well!), but there is a delay after triggering the screenshot. It seems to be right around 1000ms.

1 second is not an issue for typical use cases I'm sure, but I have a hotkey set up in ShareX (say, "1"), and a hotkey set up in my environment (say "2") such that I can quickly type "12121212" etc. to get the screenshots I need. It is in this use case that this issue arises.

Is there something I can change in the settings to decrease this time limitation? I thought it might have been the notification or sound byte causing the delay, but disabling either of them doesn't help. I also thought it might have been file name related since I had a timestamp in it, but adding a random GUID doesn't help either.

Let me know if I can provide any more info.

Thank you

**Comment by tayl** [comment]
The fact that it seems to be almost exactly 1 second makes me think there might be some logic internally that is limiting the functionality.

**Comment by Jaex** [comment]
You can decrease that delay from here:

![](https://jaex.getsharex.com/2018/09/ShareX_yQrho2Hfzd.png)

**Comment by tayl** [comment]
Hey, that did it! I knew it had to be a setting. I even looked through that setting list. I'm surprised I missed it. Thank you.
