### ISSUE TITLE
Mouse cursor display quality issue 

### ISSUE THREAD

**Issue by gridphp** [ShareX/ShareX#3623]
Mouse pointer graphics quality in screen recording gif/mp4 is not smooth.
Can anyone help on this? 

gif:
https://ibb.co/hW3OGe

mp4:
https://streamable.com/7geva

**Comment by L1Q** [comment]
Looks like DPI scaling issue. Do you have scaling enabled in display settings?

**Comment by gridphp** [comment]
Yes, i do have it. Win10 with custom scaling 125%.
Without it the text on some app dialogs is blurry so i must have it.
If i go 100% it is too small to see. I hate win10 for this.

Any solution?

**Comment by gridphp** [comment]
By my knowledge, OBS studio uses ffmpeg as well and it record my cursor well even with win10 scaling.
Do you still think its ffmpeg issue?

**Comment by L1Q** [comment]
I do, when recording screen ShareX really does not do anything besides constructing a set of launch options and running FFmpeg with them. You can see those options in screen recording settings.

**Comment by dotriz** [comment]
This thread should not be closed. This issue is still valid when using Windows 10 with scaling display.

**Comment by zeroarst** [comment]
I am having the same issue... has anyone found the solution?
