### ISSUE TITLE
My print screen button automatically saves to imgur.com ; how can I disable it

### ISSUE THREAD

**Issue by ttaylor29** [ShareX/ShareX#3627]
My print screen button automatically saves to imgur.com ; how can I disable it that functionality?!

**Comment by CtrlShiftEscape** [comment]
![image](https://user-images.githubusercontent.com/36315896/45891511-704ff100-bdce-11e8-97a9-c130fb5c05af.png)

**Comment by ttaylor29** [comment]
Perfect. Thanks!

This fixed it!
