### ISSUE TITLE
ffmpeg permissions error

### ISSUE THREAD

**Issue by krazyjakee** [ShareX/ShareX#3629]
- I have disabled antivirus/antimalware.
- I am running sharex as administrator.

I get permission denied.

![image](https://user-images.githubusercontent.com/623463/45915586-9d94b180-be57-11e8-91c2-b50fb748408a.png)

**Comment by tinybarks** [comment]
Does that directory exist? Can you manually create a file in that directory?

**Comment by attilafustos** [comment]
Happened to me today.
