### ISSUE TITLE
Webpage capture error - outdated browser

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [ShareX/ShareX#3634]
Hi,
I recently discovered `ShareX `and it is a great tool. The only problem I encountered is when using webpage capture utility. It throws the error - `You are using outdated browser.`

**For my personal website -** 

![sharex_2018-09-25_20-00-13](https://user-images.githubusercontent.com/17742733/46021293-feddae80-c0fd-11e8-90f8-917370de0174.jpg)

**For some other website -** 

![sharex_2018-09-25_19-58-53](https://user-images.githubusercontent.com/17742733/46021437-4d8b4880-c0fe-11e8-8b69-cc23036d19a3.jpg)

**Comment by Jaex** [comment]
It using internet explorer. I suggest this way: https://getsharex.com/docs/website-capture

**Comment by Kulbhushan-Chand** [comment]
@Jaex Thanks, I didn't knew about this feature in chrome. 
- However the screenshot is of lesser resolution than full screen resolution because of opened developer console panel. **Is there any shortcut for this feature?**
- What is the difference between scrolling page capture of ShareX and the chrome in-built screenshot capture? (because scrolling page can capture at full resolution, but the [above feature](https://getsharex.com/docs/website-capture) can't)

**Comment by Jaex** [comment]
What you mean lower resolution. It captures full page with same resolution as your browser.

**Comment by Kulbhushan-Chand** [comment]
It captures (browser width - width occupied by chrome developer console)

**Comment by Jaex** [comment]
Well either you can put developer panel to bottom or use alternative way to screenshot which is this: https://jaex.getsharex.com/2018/08/chrome_iKJvrgdasC.png

**Comment by Kulbhushan-Chand** [comment]
Have you added **1080p** display option by yourself ?

**Comment by Kulbhushan-Chand** [comment]
I added 1080p, 720p screen profiles.
As shown by you, I have checked both the options - 1) developer console at the bottom, 2) using device toolbar mode.
**Both works wonderfully.** I end up liking the second option i.e. using device toolbar since I can add 1080p, 720p etc. profiles and produce consistent resolution screenshots.
Thanks again for the support..  😄

**Comment by Jaex** [comment]
Added that alternative Chrome method to here now: https://getsharex.com/docs/website-capture

**Comment by Kulbhushan-Chand** [comment]
**Thanks for the documentation**, this will help others.. 👍 👏
