### ISSUE TITLE
Administrator privileges for changing the value of the "DisableUpload" parameter

### ISSUE THREAD

**Issue by Myr4ik** [ShareX/ShareX#3652]
Hello!
Is it possible to prevent a user who does not have administrator privileges in the system from changing the value of the "DisableUpload" parameter?

**Comment by Jaex** [comment]
No. It is stored in json settings file so people can easily edit it.

**Comment by Myr4ik** [comment]
Clear. Thanks for the answer.
Perhaps there is some other way to prohibit uploading images?

**Comment by Jaex** [comment]
Blocking internet access of ShareX.exe with firewall.

**Comment by Myr4ik** [comment]
Last question.
Do you have the opportunity to build a separate version without network functions?

**Comment by LewisTehMinerz** [comment]
That would literally defeat the point of ShareX's capture tools, because most if not all people who use them upload to a web service.

**Comment by Myr4ik** [comment]
> That would literally defeat the point of ShareX's capture tools, because most if not all people who use them upload to a web service. If you really don't want network support, build it yourself.

Ok, thx for the answer!
