### ISSUE TITLE
ShareX error.....

### ISSUE THREAD

**Issue by wowweemip-fan** [ShareX/ShareX#3653]
Message:
Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, Stream dataStream)

Unable to get upload key.

**Comment by tinybarks** [comment]
`Unable to connect to the remote server` indicates that the issue is related to your network. 

Please answer the following: 

1. Can you access TinyPic in your browser? Click here: http://tinypic.com/
2. If accessing TinyPic in your browser works, try uploading again. Does it work now?

**Comment by wowweemip-fan** [comment]
Late reply I know xD

Tinypic is available but proceeds to cause issues.

**Comment by tinybarks** [comment]
That didn't answer my questions, which means I can't help you.

**Comment by wowweemip-fan** [comment]
Tinypic is available on my browser, but proceeds to cause issues with sharex.

**Comment by tinybarks** [comment]
I asked two questions, which you can see again below: 

![image](https://user-images.githubusercontent.com/31551149/46891667-ecd46d80-ce6a-11e8-8219-374808744b17.png)

**Comment by wowweemip-fan** [comment]
1. Tinypic is available on my browser
2. it still does not work.

**Comment by wowweemip-fan** [comment]
I'm still confused.
