### ISSUE TITLE
Request: Please Add an After Capture Option to "Open in Snip & Sketch"?

### ISSUE THREAD

**Issue by raaomoka** [ShareX/ShareX#3661]
Really love this extremely versatile tool. It has loads of uses you wouldn't find anywhere else, especially it's fast and handy OCR feature for those grayed out/unselectable text you come across around the internet.

However, it's After Capture image editing tools live a whole lot to be desired. It's not touch friendly, it doesn't properly support pen annotation, etc. On the other hand, the new built-in Snip & Sketch tool that came with the Windows 10 October update has this part all covered AND it allows opening of files in it.

So, I was thinking that your app could give an option to open the image captured inside the Windows Snip & Sketch app for markup. That would be the best of both apps working together. Please 🙏🏽 kindly implement this.

**Comment by Jaex** [comment]
You can open other image editors like this if those image editors support command line input:

![](https://jaex.getsharex.com/2018/10/ShareX_FLDuV2tPVU.png)
![](https://jaex.getsharex.com/2018/10/ShareX_wNrfyD6qjx.png)

**Comment by raaomoka** [comment]
How do I do that with the built-in Snip & Sketch app? It's a UWP app.
