### ISSUE TITLE
How do I add a UWP App as an After Capture Action?

### ISSUE THREAD

**Issue by raaomoka** [ShareX/ShareX#3662]
So, I earlier requested that you should support opening screen clips in the Windows Snip & Sketch app here ( https://github.com/ShareX/ShareX/issues/3661 ). As you stated, it's already possible if the app supports command line input.

I'm aware that the Snip & Sketch app supports opening of files in it from File Explorer like any other photo editing program, so, it most likely supports input commands. The problem is, I'm not aware of the proper format to select a UWP app as the editor in ShareX at the moment. How do I go about doing this?

I know the Snip & Sketch app can be launched with this command, but how do I format it to work with ShareX:
>`C:\Windows\explorer.exe shell:appsFolder\Microsoft.ScreenSketch_8wekyb3d8bbwe!App`

Please and thank you.

**Comment by raaomoka** [comment]
Bump.

**Comment by yinyue200** [comment]
I have made a toolkit for it. see https://github.com/yinyue200/MetroLaunchTookit. 
Here is the powershell code to open the Snip & Sketch app with a file.
```
powershell .\Test2.ps1 -name "Microsoft.ScreenSketch" -path "your file path"

```

test2.ps1 is in my repo

**Comment by yinyue200** [comment]
In ShareX, you can set the form like that

name: as you want
filepath: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
par: <Test2.ps1 location> -name "Microsoft.ScreenSketch" -path %input
