### ISSUE TITLE
ShareX Error

### ISSUE THREAD

**Issue by akiraaisha** [ShareX/ShareX#3665]
I'm getting errors.
> Error: Message:
> The request was aborted: Could not create SSL/TLS secure channel.
> 
> Request URL:
> https://lewd.se/api.php
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
>    at System.Net.HttpWebRequest.GetRequestStream()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
>

**Comment by tinybarks** [comment]
Can you access that site in your browser?

**Comment by tinybarks** [comment]
Also, what version of Windows are you using?

**Comment by akiraaisha** [comment]
Yep. Tried also other file hosting sites. Same errors
Windows 7 64bit.

**Comment by tinybarks** [comment]
This might stem from that host only accepting TLS 1.2 connections, but .NET on Windows 7 seemingly only supporting protocols up to TLS 1.0 by default. Try following the steps here:

https://support.cybersource.com/s/article/How-do-I-enable-TLS-1-2-on-Windows-7

Import the .reg file after verifying its contents, then reboot and see if it works.

**Comment by akiraaisha** [comment]
Still getting errors.
```
Error: Message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://puush.me/api/up

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

```
