### ISSUE TITLE
Option to lock custom region selection to one monitor

### ISSUE THREAD

**Issue by Kampfkarren** [ShareX/ShareX#3670]
I recently got a new monitor, and trying to capture in the corners of my screen has become a bit annoying.

Say you have a monitor on your left, and a monitor on your right. If you want to capture anything that borders the middle of the left and right monitors (i.e. the right side of the left monitor, the left side of the right monitor), ShareX will work as if they were one big screen. I want the option to lock selecting a custom region to only one screen, so if I were trying to capture something on the left side of my right monitor, it would pretend like the left monitor wasn't even there.

**Comment by ichbineinNerd** [comment]
as far as I know, that isn't really possible (without using all kinds of internal dlls) :/
still, :+1: because if anyone **is** able to implement that, it'd be pretty useful
