### ISSUE TITLE
How to change the default upload target?

### ISSUE THREAD

**Issue by fatnick** [ShareX/ShareX#3672]
Keeps on trying dropbox, i want youtube for video...

**Comment by Jaex** [comment]
![](https://getsharex.com/img/ScreenshotChangelogUploaderFilters.png)

**Comment by PwrSrg** [comment]
I have the **same issue**!  It keeps uploading my videos to Dropbox, but I **_WANT_** them to go to **[Imgur](https://imgur.com)**.

**Comment by Unknow0059** [comment]
> I have the **same issue**! It keeps uploading my videos to Dropbox, but I **_WANT_** them to go to **[Imgur](https://imgur.com)**.

![image](https://user-images.githubusercontent.com/25656892/224456772-4d1df4a8-6fb5-46f7-ba2d-e3ab2c1100e1.png)
