### ISSUE TITLE
Imgur + gifs

### ISSUE THREAD

**Issue by gracacs** [ShareX/ShareX#3676]
When I capture gifs and it is uploaded to imgur the image is enormous, see the example --> https://i.imgur.com/ZsRkcF4.gifv

Locally the gifs are fine, pre-visualization is also fine, is there a way to change resolution uploads?

**Comment by trollmad3** [comment]
This is not a issue because other upload sites have bigger file sizes that they allow. Imgur maximum file size for `.gif` is `5MB`. Anything bigger then `5MB` will not work and give you that error. Other gif uploading sites have bigger maximum file sizes.

**Comment by gracacs** [comment]
so are you saying:
1 - My gifs are bigger than 200MB - they are not https://i.imgur.com/RT1nRKb.png
2 - there is the possibility to upload with other uploading sites? how?

**Comment by trollmad3** [comment]
@pkzeshi what?

**Comment by trollmad3** [comment]
@gracacs 
![image](https://user-images.githubusercontent.com/7843719/48306919-b2143280-e507-11e8-8ff4-b26db9327dc1.png) This is how you can pick another image uploader.

**Comment by Michael6988** [comment]
Ty

**Comment by Michael6988** [comment]
Hi

**Comment by trollmad3** [comment]
@Michael6988 I told you on the pull request you made #3726 that this part of the repo is specifically made for issues related to the program, not shitposts. Please quit doing it.
