### ISSUE TITLE
some invisible settings when scaling

### ISSUE THREAD

**Issue by bombaglad** [ShareX/ShareX#3678]
hi, so i have a 15" 4k display so i have to use 200% scaling, and one area in settings doesn't show up properly (see screenshot)
![sharex_2018-10-18_20-27-22](https://user-images.githubusercontent.com/44273538/47176029-e20b5400-d314-11e8-8900-714e53fa21fe.png)

**Comment by Jaex** [comment]
Is it Windows Store build?

**Comment by bombaglad** [comment]
yes, downloaded and installed today
