### ISSUE TITLE
my screen turns black when trying to capture area in sharex

### ISSUE THREAD

**Issue by Marsinator** [ShareX/ShareX#3684]
This has only been happening recently, I can not find a solution to fix this.

Please let me know what further information you require to pinpoint the issue

e: if I create an area to screen shot regardless of everything being black, the screen shot itself also comes out all black. the screen then goes back to normal afterwards.

Frank

**Comment by Jaex** [comment]
Most likely anti virus etc. software you are using causing it.

**Comment by Marsinator** [comment]
I only use avast antivirus, free version
