### ISSUE TITLE
Memory not freed after uploading to remote dest files with sharex

### ISSUE THREAD

**Issue by anacondaq** [ShareX/ShareX#3685]
# Problem explained
![](https://i.imgur.com/APPGSbi.png)

As you see sharex memory usage is 850MB
For some reason memory not always freed or not freed at all after uploading files though it.
How is it happen? I have just uploaded ~800MB file to mega via right click - send to sharex file and pressing "ok". FIle successfully uploaded, but the memory even after some time did not freed.

# How to reproduce:
1. Prepare any big archive file (for example 1 GB file)
2. Configure remote destination where you will upload files (in my case Mega)
3. Right click on file -> send -> ShareX
4. Wait for finishing the process
5. Check memory usage, it's not freed (or not always freed).

# Expected result: 
I understand, that the file must be stored somewhere while uploading, but the garbage must be cleaned fro memory after successful uploading file from the memory.

**Comment by Jaex** [comment]
We are using https://github.com/gpailler/MegaApiClient library. So I don't think it is caused by ShareX itself.
