### ISSUE TITLE
Suggestion: Improvements to the ruler tool

### ISSUE THREAD

**Issue by HugoBDesigner** [ShareX/ShareX#3686]
As it stands, the ruler is very useful and practical, but I find it rather limited and inflexible at times. For instance, on web designer, sometimes I just want an actual ruler to make sure two page elements are properly lined up. That quickly becomes a problem given that we can't move or hide the UI:

![image](https://user-images.githubusercontent.com/6296061/47401710-d787fa80-d718-11e8-8dc8-508c2433a5b8.png)
<sub>Suppose I was checking that those buttons were aligned.</sub>

Additionally, while the angle checking is fairly handy, being able to rotate the ruler would make it significantly more useful and practical (mainly in tasks such as drawing, level design or photography):

![image](https://user-images.githubusercontent.com/6296061/47402562-aa3d4b80-d71c-11e8-8d8f-1d4b951faca0.png)
<sub>Angle measured with rotation would differ from angle between two opposite corners, so I imagine the ruler's rotational angle would need to take place.</sub>

**Comment by sergeevabc** [comment]
@Jaex, could you be so kind to make some data (such as distance and angle) optional to display?

**Comment by paakjis** [comment]
I would use this too.
