### ISSUE TITLE
Suggestion: Color Picker in Toolbar

### ISSUE THREAD

**Issue by F-Lambda** [ShareX/ShareX#3687]
It would be great if one of the tools in the editor toolbar was a color picker. There have been many times that I just wanted to know the color of something instead of taking an actual screenshot, and having a color picker in the interface would have been great. Currently, I must instead take a screenshot, open it in another editor, and then use the color picker.

Edit: Just realized that there already is a color picker, but it's hidden. It should get a second, more prominent position. ![New position of color picker](https://i.imgur.com/fCMjl63.png)

**Comment by trollmad3** [comment]
I feel like this would be important to have, but can't you just goto `tools > color picker`?

**Comment by AndroidDeveloperLB** [comment]
But it's useful here too. Please consider adding it here.
