### ISSUE TITLE
Suggestion : saved region

### ISSUE THREAD

**Issue by StreamHi5** [ShareX/ShareX#3698]
Hello!

![saved](https://user-images.githubusercontent.com/44619843/47743625-c5114200-dc7f-11e8-947e-36edc73774c0.jpg)

Last region work correctly but if i reboot my computer, i lose this "last" region :/  and i need to create another.
It's possible to add saved region? I choose a region like this picture (the option already exists for the auto mode) :
![region](https://user-images.githubusercontent.com/44619843/47744080-b7a88780-dc80-11e8-88d0-0c242e675929.JPG)

Thanks :)

**Comment by Jaex** [comment]
It is there:

![](https://jaex.getsharex.com/2018/10/ShareX_BJosE8sD4G.png)

Which can be added to workflows menu.

**Comment by StreamHi5** [comment]
Ty Jaex :)
