### ISSUE TITLE
ShareX won't save settings

### ISSUE THREAD

**Issue by Kjaerside** [ShareX/ShareX#3701]
Hello

I've tried installing and reinstalling ShareX, but everytime i shutdown my computer or the program it resets all my settings, i only tried to change Hotkey for Capture Region and making it take a copy to clipboard so i can share pictures, but i dont understand why it keeps resetting hotkey and after capture settings.

**Comment by stuntguy3000** [comment]
@Kjaerside Do you run an anti-virus application?
