### ISSUE TITLE
Won't let me upload to twitter why?

### ISSUE THREAD

**Issue by lcortes888** [ShareX/ShareX#3702]
Message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://api.twitter.com/1.1/statuses/update_with_media.json

Response:
{"errors":[{"code":185,"message":"User is over daily status update limit."}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2018/11/chrome_JAnEmfN19V.png)

**Comment by lcortes888** [comment]
No way.

**Comment by AtomskOuO** [comment]
Hello! I'm getting the same exact problem even though I barely tweeted much at all today. I usually use ShareX a lot during the week and it has never had this problem this early before. I've been locked out of my account for tweeting too many times within an hour, but I didn't even submit 10 tweets and I was immediately locked out from ShareX. I can still submit pictures and tweet normally on my phone and on my desktop client, so I think the problem is with ShareX.

**Comment by AtomskOuO** [comment]
> 
> I haven't even tweeted at all and it said this. Sent from Yahoo Mail on Android On Thu, Nov 1, 2018 at 4:36 PM, AtomskOuO<notifications@github.com> wrote: Hello! I'm getting the same exact problem even though I barely tweeted much at all today. I usually use ShareX a lot during the week and it has never had this problem this early before. I've been locked out of my account for tweeting too many times within an hour, but I didn't even submit 10 tweets and I was immediately locked out from ShareX. I can still submit pictures and tweet normally on my phone and on my desktop client, so I think the problem is with ShareX. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Yeah same here. I should be more clear: I tweeted normally on my phone/desktop client, but didn't even get 1 tweet off in ShareX like I usually can before it said that I was over my daily limit. I'm almost sure that it's on ShareX's end or Twitter's connection with them or something. Hopefully it gets fixed soon!
