### ISSUE TITLE
custom uploader with firebase dynamic links 

### ISSUE THREAD

**Issue by DNCD** [ShareX/ShareX#3703]
I have set up my sharex with my custom domain and firebase links, but every time I take a screenshot, it does not use my firebase link. what it does everytime I take a screenshot a window for bit.ly pop-up, but I don't want to set up bit.ly I just want to use firebase links. is there anyway to fix it?

**Comment by matthewburnett** [comment]
![image](https://user-images.githubusercontent.com/10692069/47959343-ea6fba00-dfb7-11e8-89ff-39c25381734e.png)
 Make sure Firebase Dynamic Links are set as your URL Shortener destination.

**Comment by DNCD** [comment]
take a look at the video I have everything set up like that
[https://dl.beastemail.com/i/rsbl7.mp4](url)

**Comment by DNCD** [comment]
I have uninstalled sharex, and I deleted it all the files associates it and reinstall a fresh copy and that fixed.
Thanks appreciate it

**Comment by DNCD** [comment]
I have uninstalled sharex, and I deleted it all the files associates it and reinstall a fresh copy and that fixed thanks very much appreciate it
