### ISSUE TITLE
[Windows Store] Context menu integration missing (along with the setting)

### ISSUE THREAD

**Issue by martinsstuff** [ShareX/ShareX#3705]
Am I misremembering that it was available before? Edit: (I used the store version before as well), version is 12.2.

![image](https://user-images.githubusercontent.com/29005772/47932454-21ef4100-dea8-11e8-8bba-1c73a60a4a2e.png)

**Comment by martinsstuff** [comment]
Actually, is this incorrect then?

From the store page https://www.microsoft.com/en-us/p/sharex/9nblggh4z1sp?activetab=pivot:overviewtab

![image](https://user-images.githubusercontent.com/29005772/47933111-fec59100-dea9-11e8-821b-88e686157052.png)

**Comment by Jaex** [comment]
Yes that description is incorrect.
