### ISSUE TITLE
ShareX doesn't delete old configs

### ISSUE THREAD

**Issue by Zireael07** [ShareX/ShareX#3706]
I have been using ShareX since the end of 2016. I just discovered the program doesn't delete old configuration files and log files. A file is created every week, so that's 52-53 files a year.
This affects /Logs and /Backup, namely ApplicationConfig, History, HotkeysConfig, UploadersConfig

**Comment by Jaex** [comment]
It is not supposed to delete logs or backups.

**Comment by Zireael07** [comment]
It should delete old files, just like 99% programs do. They keep the latest X files and/or use a cutoff date to determine which files should be kept. The cutoff may or may not be user configurable. But keeping 2+ years old files is not what programs do.

**Comment by Jaex** [comment]
There could be option to remove n days old files but I wouldn't make it enabled by default.

**Comment by Zireael07** [comment]
An option to remove n days old files would still be useful.
