### ISSUE TITLE
not an issue, just a suggestion

### ISSUE THREAD

**Issue by FernanDK** [ShareX/ShareX#3707]
sorry for posting a feature request in the issue zone, I tried to find the proper feedback channel for suggestions but unfortunately I was unable to locate it.

so I noticed there is a portable version, and it works flawlessly, I come to request you to work in parallel with the guys at portableapps.com and put a copy of the portable version of ShareX inside portableapps' launcher. I would be awesome because it updates the apps automatically.

thank you

**Comment by sylveon** [comment]
PortableApps does not accept .NET apps

**Comment by FernanDK** [comment]
oh I see,

well then I guess not all dreams come true. Shame on them for discriminating so bluntly like that. thanks for the heads-up!

**Comment by Jaex** [comment]
https://github.com/ShareX/PortableApps

I was making this but because they didn't allow .NET apps to be listed in their list, I gave up and didn't update it.
