### ISSUE TITLE
Watch folder upload issue

### ISSUE THREAD

**Issue by commensal** [ShareX/ShareX#3710]
I set watch folder for images to upload to imgur and that does not work when Chrome Extension (Kantu) downloads images to this folder. But if I copy and paste the same image to the same folder (it gets the name with "copy") the image gets uploaded.
Is there a way to fix this issue? Thanks.

**Comment by Mahaldo** [comment]
I'm having the same problem, I synchronize captures from my android with the Syncthing software and it doesn't go up alone, if I copy it and take it from my windows system, if it works, the upload.
