### ISSUE TITLE
Save as png, jpg

### ISSUE THREAD

**Issue by Devocub** [ShareX/ShareX#3714]
I would like to choose png or jpg. Currently there's only one format

**Comment by AlcaDesign** [comment]
Click "Task settings..." on the left side of ShareX and then click "Image" in the nav. There's a drop down for PNG, JPEG, GIF, BMP, and TIFF formats.

![image](https://user-images.githubusercontent.com/7132646/48299319-76d71c80-e491-11e8-8e04-7ad2baee5a54.png)

**Comment by Devocub** [comment]
@AlcaDesign i know about it. I mean this
![image](https://user-images.githubusercontent.com/2735824/48300576-48892980-e4f1-11e8-8a0e-d4e9f8d506ba.png)

![image](https://user-images.githubusercontent.com/2735824/48300574-3dce9480-e4f1-11e8-93ad-688ab966363a.png)
