### ISSUE TITLE
After recording a video/gif, allow to open folder from popup (and other actions)

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ShareX/ShareX#3715]
After I record a video/gif, there's a popup which I can click and it will open the file. I'd like to have an option to open the folder, too. And it would be even better if I had the option to upload it to imgur right away.

![image](https://user-images.githubusercontent.com/5781692/48052373-6c2a3800-e1b0-11e8-830d-96262588c99f.png)

**Comment by Jaex** [comment]
It is already exists:

![](https://jaex.getsharex.com/2018/11/ShareX_PbSWRZdtMb.png)

**Comment by justanotheranonymoususer** [comment]
That's nice, but I can't have more than one action. Say I want sometimes to open folder, and sometimes to upload. Perhaps make right click show a menu with all options? That should be easy to implement.

Also, I tried "Annotate image", and it doesn't really work with videos. For gifs, it opens only the first frame.

**Comment by Jaex** [comment]
Right click closes popup so I can't add menu there. How annotate can work on videos?!

**Comment by justanotheranonymoususer** [comment]
Well, one of the menu entries can be "close popup". Or you can add a button labeled as "more actions".

As for "annotate videos", if it doesn't work, why is it an option? Anyway, the annotate window has an upload button, so I was just hoping to get a window where I can do several actions.
