### ISSUE TITLE
Add more edit features (effects/drawing).

### ISSUE THREAD

**Issue by HulkyBigBoi** [ShareX/ShareX#3718]
My suggestions are:
- Check mark (C when in editor - https://i.imgur.com/B0po36O.png)
- X (Draws an X - https://i.imgur.com/qgVGjcz.png)
- Black out (blacks out the selected area - https://i.imgur.com/d7Vp5Yl.png)
- Blur/pixelation strength.
- Blur/pixelation color (could also be a subsitute for the "Black out" suggestion.)

**Comment by trollmad3** [comment]
Pixelation already exists. 
![2018-11-10_17-04-45](https://user-images.githubusercontent.com/7843719/48307064-bee65580-e50a-11e8-8d5a-f9dd4b9f62b5.gif)
