### ISSUE TITLE
Transfer.sh shutting down

### ISSUE THREAD

**Issue by Lambik** [ShareX/ShareX#3720]
Hi,

Unfortunately, this service is shutting down at the end of this november. Stated on their website:

> transfer.sh will shutdown 30th of November 2018
> After running transfer.sh for 4 years, it has to come to an end. I started this project, because I needed something quick and simple to share files between from the command line. Now it has grown out of control, with millions of files being shared each month, and no longer sustainable and affordable to keep it running for free. From day one the code has been opensource, of which you can run your own instance. Special thanks to Andrea Spacca for maintaining the opensource version, the amazing community for all efforts, the patrons for all support and to Gopher  for being you. 
> So Long, and Thanks for All the Fish. 
> Remco Verhoef.

It is self-hostable through their github repo, but currently the transfer.sh plugin has no config options to change the URL.

I would propose that either you remove the integration after november, or let people change the url to their self-hosted instance?

**Comment by matthewburnett** [comment]
transfer.sh.sxcu is a simple text file, you can change the url in the file before imported to sharex, or change the url in the custom uploader page.

**Comment by Lambik** [comment]
Thanks for the info. Apparently transfer.sh got funding and isn't shutting down right now, so this isn't really needed yet, but still good to know!
