### ISSUE TITLE
Can't see the cross hairs after changing the cursor look/size

### ISSUE THREAD

**Issue by grub-basket** [ShareX/ShareX#3727]
On Windows, in the mouse window, I can't see the cursor when doing a region select capture. This makes is difficult to know where to start from and how to touch the resize buttons on the edge of the region frame.

![image](https://user-images.githubusercontent.com/12993901/48308023-f8b95b00-e50e-11e8-98f6-627472b711aa.png)

All I've done was change the mouse cursor style in this window, but was unable to change the effects when reverting it ot use the default. 

![image](https://user-images.githubusercontent.com/12993901/48308036-50f05d00-e50f-11e8-9116-94df06277c45.png)

Any help would be appreciated. Thank you so much.

**Comment by jwdinkel** [comment]
I think I have this same problem. When taking a screenshot of a dark background like in visual studio code, the crosshair is not colored white, so it's hard...  Wonder if there might be a way to change the crosshair to invert the background colors?

**Comment by Jaex** [comment]
@jwdinkel cursor normally contains both white and black. You are probably using high DPI which causing this cursor issue.

**Comment by jwdinkel** [comment]
Thank you. There seems to be another possible solution. I can activate the screen wide crosshair that is available in the gear menu after starting the screenshot.  This seems to be perfect because it draws large lines vertical and horizontal. Perhaps that will help @grub-basket also?

I am using a 4k monitor... but my cursor has a single color when I start the capture...

**Comment by Jaex** [comment]
I couldn't figure out how to fix cursor for high dpi users. Because when I increase dpi option of my Windows, still cursor shows up properly.

**Comment by jwdinkel** [comment]
Here is what I am seeing. I'm happy with the screen wide crosshair... So no need to go further for me here. Perhaps somebody else will notice why later...

![sharex_2018-11-15_11-14-58](https://user-images.githubusercontent.com/7911734/48546053-9aea9180-e8c7-11e8-9583-0e6bcab7c0bb.png)

**Comment by grub-basket** [comment]
I'm in the same boat. Sorry @Jaex. Thank you both. I will just have to live with the crosshair, lol.

**Comment by Jaex** [comment]
I mean I also have friends who using Windows with high DPI yet they didn't have cursor problem. And when I Google about this stuffs can't find any solution too.

**Comment by grub-basket** [comment]
Yeah, on some days it appears and some days it doesn't. I guess it's just an issue with Windows.

**Comment by UnderVoid** [comment]
Hey, just thought I'd update this by saying I'm experiencing the issue. Had a 2160p and 1440p monitor for years with no problem, recently added a second 1440p screen and it must have been around the same time that this bug started, didn't notice it until a bit afterwards though. I get the exact same thing as that screenshot above with the tiny black dot of a cursor which is impossible to see most of the time. 

Did anybody find a solution?

**Comment by 111Iceman111** [comment]
was googling to see the soulution for this.. on 4k monitor with 150 magnification, the cross is black and i cant see it at all if i am screenshoting some black area
