### ISSUE TITLE
Automatic download of FFMPEG fails if ..\Documents\ShareX\Tools folder does not exist

### ISSUE THREAD

**Issue by peheje** [ShareX/ShareX#3729]
Automatic download of FFMPEG fails if the Tools folder does not exist. Manually creating the folder and Sharex is successful.

Windows 10

**Comment by Jaex** [comment]
Right before press Download FFmpeg button I renamed my Documents/ShareX folder and it created required folders automatically. So it not fails if directory not exists. Your PC not letting creating directory most likely.

**Comment by peheje** [comment]
Yes probably. Can I send you some logs? I'd be happy to. Awesome software.

søn. 11. nov. 2018 21.12 skrev Jaex <notifications@github.com>:

**Comment by Jaex** [comment]
Most of the time anti viruses not letting ShareX to create folder. Even Windows Defender have this feature. So it is nothing to do with ShareX.
