### ISSUE TITLE
FTPS upload failes

### ISSUE THREAD

**Issue by Uripura** [ShareX/ShareX#3732]
Upload with FTP works fine, but as soon as I switch to FTPS it says the Connection timed out.
When testing the connection in the settings menu is says, that is connected successfully.

I use Passive mode and it uploads the file correctly but says "URL is empty"

2018-11-12 19:51:29.338 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Region aufnehmen, Job: RectangleRegion
2018-11-12 19:51:29.338 - Executing: Region aufnehmen
2018-11-12 19:51:33.015 - Task in queue. Job: Job, Type: File, Host: FTP
2018-11-12 19:51:33.015 - Task status: Preparing
2018-11-12 19:51:33.022 - Image copied to clipboard.
2018-11-12 19:51:33.029 - Image saved to file: C:\Users\Uripura\Documents\ShareX\Screenshots\2018-11\ShareX_2018-11-12_19-51-33.png
2018-11-12 19:51:33.041 - Upload started. Filename: ShareX_2018-11-12_19-51-33.png, Filepath: C:\Users\Uripura\Documents\ShareX\Screenshots\2018-11\ShareX_2018-11-12_19-51-33.png
2018-11-12 19:51:33.440 - Task failed. Filename: ShareX_2018-11-12_19-51-33.png, Errors:
URL ist leer.

**Comment by Uripura** [comment]
I got around to get a debug log. I use vsftpd.

Tue Nov 13 16:55:47 2018 [pid 9273] CONNECT: Client "1234:1234:1234:1234:1234:1234:1234:1234"
Tue Nov 13 16:55:47 2018 [pid 9273] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "220 Welcome to my FTP service."
Tue Nov 13 16:55:47 2018 [pid 9273] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "AUTH TLS"
Tue Nov 13 16:55:47 2018 [pid 9273] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "234 Proceed with negotiation."
Tue Nov 13 16:55:47 2018 [pid 9273] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SSL version: TLSv1.2, SSL cipher: ECDHE-RSA-AES256-GCM-SHA384, not reused, no cert"
Tue Nov 13 16:55:47 2018 [pid 9273] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "USER ftpuser"
Tue Nov 13 16:55:47 2018 [pid 9273] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "331 Please specify the password."
Tue Nov 13 16:55:47 2018 [pid 9273] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "PASS <password>"
Tue Nov 13 16:55:47 2018 [pid 9272] [ftpuser] OK LOGIN: Client "1234:1234:1234:1234:1234:1234:1234:1234"
Tue Nov 13 16:55:47 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "230 Login successful."
Tue Nov 13 16:55:47 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "PBSZ 0"
Tue Nov 13 16:55:47 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "200 PBSZ set to 0."
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "PROT P"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "200 PROT now Private."
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "FEAT"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "211-Features:"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " AUTH TLS??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " EPRT??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " EPSV??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " MDTM??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " PASV??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " PBSZ??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " PROT??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " REST STREAM??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " SIZE??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", " TVFS??"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "211 End"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SYST"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "215 UNIX Type: L8"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "TYPE I"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "200 Switching to Binary mode."
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SIZE /var/www/img/share/ShareX_2018-11-13_16-55-44.png"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "550 Could not get file size."
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "EPSV"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "229 Entering Extended Passive Mode (|||20803|)"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "STOR /var/www/img/share/ShareX_2018-11-13_16-55-44.png"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "150 Ok to send data."
Tue Nov 13 16:55:48 2018 [pid 9273] [ftpuser] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SSL version: TLSv1.2, SSL cipher: ECDHE-RSA-AES256-GCM-SHA384, reused, no cert"
Tue Nov 13 16:55:48 2018 [pid 9273] [ftpuser] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "DATA connection terminated without SSL shutdown. Buggy client! Integrity of upload cannot be asserted."
Tue Nov 13 16:55:48 2018 [pid 9273] [ftpuser] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SSL shutdown state is: NONE"
Tue Nov 13 16:55:48 2018 [pid 9273] [ftpuser] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SSL shutdown state is: SSL_SENT_SHUTDOWN"
Tue Nov 13 16:55:48 2018 [pid 9273] [ftpuser] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SSL shutdown state is: SSL_SENT_SHUTDOWN"
Tue Nov 13 16:55:48 2018 [pid 9273] [ftpuser] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SSL shutdown state is: SSL_SENT_SHUTDOWN"
Tue Nov 13 16:55:48 2018 [pid 9273] [ftpuser] DEBUG: Client "1234:1234:1234:1234:1234:1234:1234:1234", "SSL ret: 18446744073709551615, SSL error: error:00000000:lib(0):func(0):reason(0), errno: 0"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "426 Failure reading network stream."
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FAIL UPLOAD: Client "1234:1234:1234:1234:1234:1234:1234:1234", "/var/www/img/share/ShareX_2018-11-13_16-55-44.png", 5873 bytes, 100.75Kbyte/sec
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP command: Client "1234:1234:1234:1234:1234:1234:1234:1234", "QUIT"
Tue Nov 13 16:55:48 2018 [pid 9274] [ftpuser] FTP response: Client "1234:1234:1234:1234:1234:1234:1234:1234", "221 Goodbye."

**Comment by tdharris** [comment]
I am experiencing the same issue and have for some time.
```
ShareX 12.3.1
vsftpd: version 3.0.3
```
ShareX log (client):
```
Task in queue. Job: FileUpload, Type: File, Host: FTP
Task status: Preparing
Upload started. Filename: test.png, Filepath: C:\<filepath>\test.png
Task failed. Filename: test.png, Errors:
URL is empty.
```

vsftpd log (server):
```
CONNECT: Client "<ipAddress>"
FTP response: Client "<ipAddress>", "220 Welcome to our FTP service."
FTP command: Client "<ipAddress>", "AUTH TLS"
FTP response: Client "<ipAddress>", "234 Proceed with negotiation."
FTP command: Client "<ipAddress>", "USER admin"
[user] FTP response: Client "<ipAddress>", "331 Please specify the password."
[user] FTP command: Client "<ipAddress>", "PASS <password>"
[user] OK LOGIN: Client "<ipAddress>"
[user] FTP response: Client "<ipAddress>", "230 Login successful."
[user] FTP command: Client "<ipAddress>", "PBSZ 0"
[user] FTP response: Client "<ipAddress>", "200 PBSZ set to 0."
[user] FTP command: Client "<ipAddress>", "PROT P"
[user] FTP response: Client "<ipAddress>", "200 PROT now Private."
[user] FTP command: Client "<ipAddress>", "FEAT"
[user] FTP response: Client "<ipAddress>", "211-Features:"
[user] FTP response: Client "<ipAddress>", " AUTH TLS??"
[user] FTP response: Client "<ipAddress>", " EPRT??"
[user] FTP response: Client "<ipAddress>", " EPSV??"
[user] FTP response: Client "<ipAddress>", " MDTM??"
[user] FTP response: Client "<ipAddress>", " PASV??"
[user] FTP response: Client "<ipAddress>", " PBSZ??"
[user] FTP response: Client "<ipAddress>", " PROT??"
[user] FTP response: Client "<ipAddress>", " REST STREAM??"
[user] FTP response: Client "<ipAddress>", " SIZE??"
[user] FTP response: Client "<ipAddress>", " TVFS??"
[user] FTP response: Client "<ipAddress>", "211 End"
[user] FTP command: Client "<ipAddress>", "SYST"
[user] FTP response: Client "<ipAddress>", "215 UNIX Type: L8"
[user] FTP command: Client "<ipAddress>", "TYPE I"
[user] FTP response: Client "<ipAddress>", "200 Switching to Binary mode."
[user] FTP command: Client "<ipAddress>", "SIZE /tmp/test.png"
[user] FTP response: Client "<ipAddress>", "550 Could not get file size."
[user] FTP command: Client "<ipAddress>", "EPSV"
[user] FTP response: Client "<ipAddress>", "229 Entering Extended Passive Mode (|||41671|)"
[user] FTP command: Client "<ipAddress>", "STOR /tmp/test.png"
[user] FTP response: Client "<ipAddress>", "150 Ok to send data."
[user] DEBUG: Client "<ipAddress>", "DATA connection terminated without SSL shutdown. Buggy client! Integrity of upload cannot be asserted."
[user] FTP response: Client "<ipAddress>", "426 Failure reading network stream."
[user] FAIL UPLOAD: Client "<ipAddress>", "/tmp/test.png", 61959 bytes, 12132.91Kbyte/sec
[user] FTP command: Client "<ipAddress>", "QUIT"
[user] FTP response: Client "<ipAddress>", "221 Goodbye."
```

So it seems ShareX Client does a `SIZE` ftp command initially, assuming this is to check if the file exists already before attempting to upload (so `550 Could not get file size.` is fine, since the file does not exist). Then it sends the file over (`STOR`), but the problem I see appears to be a ssl client issue:
```
DATA connection terminated without SSL shutdown. Buggy client! Integrity of upload cannot be asserted.
426 Failure reading network stream.
```

But the file does indeed upload and is on the ftp server fine.

**Comment by sneak-it** [comment]
Updating this issue, I'm attemping to use SFTP as well. Prior to now, I used plain FTP where everything worked fine, now this problem has popped up for me. "URL Is Empty". The file uploads without issue, except the URL cannot be copied.

Debug log:

```
2019-04-11 02:16:13.977 - Hotkey triggered. Hotkey: Ctrl + Shift + 4, Description: Capture region, Job: RectangleRegion
2019-04-11 02:16:13.977 - Executing: Capture region
2019-04-11 02:16:15.568 - Task in queue. Job: Job, Type: File, Host: FTP
2019-04-11 02:16:15.587 - Task status: Preparing
2019-04-11 02:16:15.589 - Upload started. Filename: 8VxQGv.png
2019-04-11 02:16:16.533 - Task failed. Filename: 8VxQGv.png, Errors:
URL is empty.
```

VSFTPD server log:

```
Thu Apr 11 01:16:19 2019 [pid 937] CONNECT: Client "::ffff:xx.xxx.xxx.xxx"
Thu Apr 11 01:16:19 2019 [pid 934] [user] OK LOGIN: Client "::ffff:xx.xxx.xxx.xxx"
Thu Apr 11 01:16:20 2019 [pid 937] [user] DEBUG: Client "::ffff:xx.xxx.xxx.xxx", "DATA connection terminated without SSL shutdown. Buggy client! Integrity of upload cannot be asserted."
Thu Apr 11 01:16:20 2019 [pid 940] [user] FAIL UPLOAD: Client "::ffff:xx.xxx.xxx.xxx", "/public_html/i/8VxQGv.png", 9463 bytes, 70.05Kbyte/sec
```

**Comment by tdharris** [comment]
I found that adding this specific setting to `vsftpd.conf` resolved the issue: `strict_ssl_read_eof=NO`

[vsftpd.conf](http://vsftpd.beasts.org/vsftpd_conf.html):
"strict_ssl_read_eof
If enabled, SSL data uploads are required to terminate via SSL, not an EOF on the socket. This option is required to be sure that an attacker did not terminate an upload prematurely with a faked TCP FIN. Unfortunately, it is not enabled by default because so few clients get it right. (New in v2.0.7).
Default: NO"

So eventhough my `vsftpd.conf` wasn't explicitly set `YES` for this option, if I explicitly set it to `NO` (eventhough that is the apparent default), it did fix the client issue I was having with ShareX via FTPS in this case.

**Comment by Uripura** [comment]
OMG you are my hero! Finally after all this time it works again!

**Comment by sneak-it** [comment]
Awesome find @tdharris thank you! Fixed the issue for me.
