### ISSUE TITLE
ShareX doesnt open pictures in the new firefox

### ISSUE THREAD

**Issue by asdf337** [ShareX/ShareX#3733]
ShareX doesnt seem to be able to open screenshots that have just been taken in the new firefox quantum. Any fix on this? It seems to be able to open in all other browsers when I switch the default internet app.

**Comment by Jaex** [comment]
It is not to do with ShareX. ShareX just gives url to Windows and it is up to Windows to decide how to open URLs using default browser.

**Comment by asdf337** [comment]
Yes it is, right after the last shareX update it works, so it was shareX
not working with the new firefox version, it works now tho, AFTER the most
recently update to shareX.
