### ISSUE TITLE
disk written lossless images don't preserve colors

### ISSUE THREAD

**Issue by graphitemaster** [ShareX/ShareX#3734]
## Environment
Affects all versions of ShareX for all platforms

## Steps to reproduce
* Open a raster image editor and fill the canvas with a solid color to which you know the RGB value
* Capture that window and save a PNG to disk
* Open the saved PNG and compare the RGB value

## Expected result
The RGB values should be the same

## Rationale
PNG and other lossless image formats shouldn't have this problem. The compression algorithm isn't supposed to alter the bit level image data.

## Investigation
This seems to be a problem with `System.Drawing.Imaging` in the .NET run time. Some investigative work shows that `.Save` with `ImageFormat.PNG` doesn't faithfully reproduce colors as evidenced by some others as outlined here <https://stackoverflow.com/questions/41521955/system-drawing-image-colors-are-not-matching-web-colors>.

## Discussion
This isn't hard to fix but will require a move to a different image library for the purposes of saving images. I'm going to also open a bug report upstream on the .NET run time but that could take a long time to be fixed, if at all.

As it stands ShareX is unsuitable for faithfully reproducing captures which makes it very difficult to use as a design tool.

## Further concerns
While searching the code base to isolate the problem it became apparent that `System.Drawing.Imaging` doesn't specify which color space it applies it's transformations in. I assume linear as that is the most useful way to but I have some concerns that image saving itself may reinterpret the bitmap data by applying sRGB transformations or color profiles to it which may explain why `100L` quality JPEG compressed images have slightly incorrect results. Still investigating this and will open as a different bug report if my intuition is correct.

**Comment by Jaex** [comment]
It is most likely monitor color profile issue: #1236

**Comment by graphitemaster** [comment]
Why would .NET be applying the color profile on a `.Save` though, that seems like a huge mistake. If it is then maybe we need to explore alternatives?

**Comment by graphitemaster** [comment]
after reading the source code of .NET here <https://github.com/dotnet/corefx/tree/master/src/System.Drawing.Common/src/System/Drawing/Imaging> and looking at how saving of PNGs and other formats are done, it appears to just shell out to GDI on Windows here <https://github.com/dotnet/corefx/tree/master/src/System.Drawing.Common/src/misc/GDI>. Looking into GDI it doesn't apply color transformations at all, not even ICC ones so it can't possibly be that.

**Comment by graphitemaster** [comment]
Would you be against the inclusion of a hack that strips the gAMA chunk from the PNG? It's quite trivial to assemble the PNG in memory as a stream, read the header to find the gAMA chunk and just drop it from the stream (as an option of course in the program)

**Comment by graphitemaster** [comment]
I mean it seems to be a common theme for people using PNGs in ASP.NET even to do this since it does cause color reproduction issues <https://www.codeproject.com/Articles/37157/Strip-gAMA-Chunk-from-PNG-for-ASP-NET-Applications>

**Comment by Jaex** [comment]
Because this issue happens to very small amount of people I don't prefer that workaround. If everyone was going to get incorrect colors then of course this would be necessary, but there must be something different in your computer causing this issue. Not to mention I'm not sure is there a reason that header could be necessary for some users, otherwise why would Microsoft decide to include it by default with no option at all?

**Comment by graphitemaster** [comment]
They include the `gAMA` chunk in every PNG but depending on ICC profile adjust the value. Some people get away with a gamma of `1` so it cancels out during multiplication while others have a slightly adjusted gamma because they have professional configured displays (like myself), especially when you have something that doesn't have standard gamut (e.g my display covers full sRGB and most of REC 2020.) Seeing as ~99% of monitors are cheap TN panels (or Windows doesn't have an ICC profile so it uses the default.) this doesn't affect most users.

I just verified this by adjusting my own ICC profile to have 6x larger gamut (no display does this but I wanted to be sure) and ShareX incorrectly exported `#112233` as `#ABC7E3` which is literally 6x the gamma. That's a major difference and a completely
different color.

What MS is doing here is incorrect behavior and a bug in their GDI+ encoder. Other PNG libraries like libpng do not have these problems because the default is to never export a `gAMA` chunk unless you ask for it. Since people are working in linear space they expect their images to also stay linear. The work around on that page is actually a necessary evil in my opinion.

This will continue to become a problem as more people transition to displays that have wider color gamuts or just to displays that are seen as higher end and so MS includes ICC profiles in Windows updates for them.

That `gAMA` chunk is also responsible for causing some transparency issues too in PNGs. When you author a transparent image you may have an alpha of `0x00` which is fine, but the RGB channels often contain some garbage uninitialized data or if you're lucky, solid white and black. The `gAMA` correction still gets applied to those pixels and may cause them to stick out more when alpha blending (this issue is often solved by using premultiplied alpha.)

I can get more into the science of these image formats and color theory if you want but this requires some fix.

**Comment by graphitemaster** [comment]
Obviously it's not a nice thing to ask people to use the standard ICC profile for their display and have colors broken everywhere else, especially if they work in design.

**Comment by Jaex** [comment]
Of course it must be fixed but just I was not fond of that workaround you showed. Only if there were built in GDI+ way to solve it while saving.

**Comment by graphitemaster** [comment]
The alternative would be to drop GDI+ and pickup some other library which may not be a bad idea if you want to support even more formats for export. But if we want to stick to the C# wrapped GDI+ interfaces than the only real solution I see is to hack around the exported data.

**Comment by Jaex** [comment]
I don't prefer to add external libraries as long as it is not necessary. Especially when you consider just ImageMagick is bigger than ShareX itself. But you can use ImageMagick CLI to convert BMP to PNG (http://www.imagemagick.org/script/convert.php). Which means ShareX can save as BMP and actions feature can be used to launch ImageMagick CLI to convert BMP to PNG. But then I noticed that I must add new setting to actions to be able to delete source file if output file name is different than source file name.

**Comment by Jaex** [comment]
Actually you can use ImageMagick CLI to fix gamma header like this I think: https://stackoverflow.com/questions/49449220/how-can-i-fix-pngs-gamma-using-imagemagick
So there won't be problem about removing source file too.

**Comment by graphitemaster** [comment]
That's not a very clean or elegant solution. Needing an external tool when ShareX should be capable of exporting the image correctly. ImageMagick is a massive library indeed but it also does way more than what you need. You should check into FreeImage as an alternative.

**Comment by Jaex** [comment]
Your workaround was also not elegant.

**Comment by graphitemaster** [comment]
No it wasn't, but it was also the least amount of work for the most amount of gain

**Comment by Jaex** [comment]
I can add your workaround as optional advanced setting. I wouldn't prefer that workaround to be applied by default.

**Comment by graphitemaster** [comment]
I think that's an acceptable compromise. I wouldn't mind documenting it on the wiki either.

**Comment by Jaex** [comment]
I added advanced setting to remove these chunks: "gAMA", "cHRM", "sRGB", "iCCP" (http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html)

If you would like to test it because I can't: https://getsharex.com/docs/dev-builds

**Comment by graphitemaster** [comment]
I can test a dev build later but looking at the commit this may strip data from an image that happens to encode 4 bytes as one of those chunks on a 4-byte boundary, shouldn't there be a condition to make sure it's a chunk?

**Comment by Jaex** [comment]
4-byte boundary?

**Comment by graphitemaster** [comment]
Well the code just processes the whole file 4 bytes at a time, it's possible that there's some byte pattern that has the same value as one of the chunk's bytes and this will strip them

**Comment by graphitemaster** [comment]
Oh never mind I misread the code, this will work.

**Comment by haasn** [comment]
> Because this issue happens to very small amount of people I don't prefer that workaround. If everyone was getting incorrect colors then of course this would be necessary, but there must be something different in your computer causing this issue. Not to mention I'm not sure is there a reason that header could be necessary for some users, otherwise why would Microsoft decide to include it by default with no option at all?

Microsoft is pretty much doing the correct thing here. When you take a screenshot of your display (in your display's native color space), tagging the resulting file with that same color space ensures consistent reproduction across platforms / devices.

For example, if I view an HD video file on a wide gamut display and take a screenshot of the windows, then send this screenshot somebody with a more standard sRGB display, they would see a very desaturated version of what I see - unless the screenshot was tagged with either an ICC profile of the target display, or gAMA/cHRM chunks approximating it (as a fallback - although note that gAMA is severely limited in that it can only handle pure power curves).
