### ISSUE TITLE
Wrong Download Link

### ISSUE THREAD

**Issue by ab-cc** [ShareX/ShareX#3737]
The download link for the portable versions is not as per the latest version... If I download ShareX-portable.zip from https://github.com/ShareX/ShareX/releases, the downloaded zip contains v12.2.0 instead of v12.3.0.

The executable .exe download is fine. Only portable download still contains an older version.

**Comment by Jaex** [comment]
I tested now it is 12.3.0.

**Comment by ab-cc** [comment]
Looks like there is a lag then... Are the links auto generated?
