### ISSUE TITLE
error on startup lasted version

### ISSUE THREAD

**Issue by KuroSenseii** [ShareX/ShareX#3739]
System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'ShareX.UploadersLib, Version=12.3.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
Nom de fichier : 'ShareX.UploadersLib, Version=12.3.0.0, Culture=neutral, PublicKeyToken=null'
   à ShareX.Program.Run()
   à ShareX.Program.Main(String[] args)

AVT : la journalisation de liaison d'assembly est désactivée.
Pour activer la journalisation des échecs de liaison d'assembly, attribuez la valeur 1 à la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD).
Remarque : une certaine perte de performance est associée à l'enregistrement dans le journal des échecs de liaison d'assembly.
Pour désactiver cette fonctionnalité, supprimez la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog].

ShareX 12.3 (Release)

**Comment by RensVerhagen** [comment]
Same error for me, after adding the item in the registry as described, i get the following error:

--------------------------------------------------------------------------------------------------
System.BadImageFormatException: Could not load file or assembly 'ShareX.UploadersLib, Version=12.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.UploadersLib, Version=12.3.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

=== Pre-bind state information ===
LOG: DisplayName = ShareX.UploadersLib, Version=12.3.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/ShareX/
LOG: Initial PrivatePath = NULL
Calling assembly : ShareX, Version=12.3.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\ShareX\ShareX.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Program Files/ShareX/ShareX.UploadersLib.DLL.
ERR: Failed to complete setup of assembly (hr = 0x80131018). Probing terminated.


ShareX 12.3 (Release)
--------------------------------------------------------------------------------------------------

**Comment by Jaex** [comment]
BadImageFormatException means dll file become corrupt. So you must re install ShareX.
