### ISSUE TITLE
System.OverflowException when try to shutdown

### ISSUE THREAD

**Issue by SiroQ** [ShareX/ShareX#3740]
System.OverflowException: 算術演算の結果オーバーフローが発生しました。
   場所 ShareX.MainForm.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.3 (Release)

**Comment by Jaex** [comment]
Duplicate of #3738
