### ISSUE TITLE
Error uploading after newest update.

### ISSUE THREAD

**Issue by Newcool1230** [ShareX/ShareX#3742]
I'm currently facing a problem once I updated to the new version 12.3.
When I try to upload on my website through >Custom uploaders. It will just spit out my website URL without the linking the picture. If I press "test" through Custom uploader it also redirects me to my website instead of the picture.

I have changed nothing in my upload.php or config.php.

Is there a quick hotfix for this issue?

**Comment by Newcool1230** [comment]
Hm... I did check the changelog... I'm not 100% if I understand everything in the change log... is it regex change that is breaking my custom uploader?

https://i.imgur.com/o9TTmWy.png

**Comment by Jaex** [comment]
In URL field it must be `$regex:1$` instead of `$1$`.

**Comment by Newcool1230** [comment]
Thank you very much!
