### ISSUE TITLE
Allow option to save video as GIF

### ISSUE THREAD

**Issue by burdoto** [ShareX/ShareX#3744]
When screenrecording, I would wish to be able to choose whether to store as a full blown Video or as a GIF, as sometimes I change my mind while recording and just wanna have a GIF, as those are easier to upload.
Maybe we could have a button saying "Save as Video" and one "Save as GIF" in this context:
![grafik](https://user-images.githubusercontent.com/42473485/48501135-c2e0e300-e83c-11e8-9e52-db784a221ddc.png)

**Comment by stuntguy3000** [comment]
![image](https://user-images.githubusercontent.com/1522389/48525177-07b75900-e8d3-11e8-9889-9dbd8065469f.png)

Just select the right one before you record?
