### ISSUE TITLE
Image showing preview of screenshot even with setting turned off

### ISSUE THREAD

**Issue by NoahBK** [ShareX/ShareX#3747]
I recently updated sharex and when I did the image preview showed back up. I still have the setting in sharex turned off I think, but it still shows it. Is this a bug or is this now built into sharex? Thanks.

**Comment by Jaex** [comment]
I can't reproduce it with preview disabled:

![](https://jaex.getsharex.com/2018/11/ShareX_MM6vg4QMCA.png)
