### ISSUE TITLE
Google Photos uploads are overwriting the original date stamp of picture 

### ISSUE THREAD

**Issue by FernanDK** [ShareX/ShareX#3749]
the following picture was taken in 2015 but I uploaded it today using drag-n-drop feature just for testing purposes. Upon checking the date of the picture was overwritten by the date of upload. 

here's the link of the picture uploaded by ShareX = https://photos.app.goo.gl/cpUZVQMaC4kcJjcX8
here's the link of the picture uploaded directly to Google Photos via browser = https://photos.app.goo.gl/TBJNxFm9gzLfgTx77

this is an issue because original time, date & any other EXIF embedded-data-stamps should be respected, in fact that has always been the police in Picasa, and in the discontinued official Google Photos uploader too. And they are if you drag-n-drop the picture directly inside the webclient running in a browser. So I believe they should also be respected by ShareX. Maybe it's a bug maybe it's deliberate, either way I'd say needs fixing.

**Comment by matthewburnett** [comment]
I'm currently in the process of rewriting the uploader to be using the new Google Photos API rather than the soon to be deprecated Picasa api we currently use. Not to my knowledge do we strip EXIF intentionally.

**Comment by FernanDK** [comment]
I suspected it wasn't intentional, but you never really know, you know? you guys are the best in anyways.
