### ISSUE TITLE
Cannot Use Screen Record or GIF Feature

### ISSUE THREAD

**Issue by Rynozilla** [ShareX/ShareX#3752]
I consistently get this error window when I try either 
![a049msv](https://user-images.githubusercontent.com/45077280/48572602-e0af5600-e8d7-11e8-8131-78ff1fbeee4b.png)

**Comment by sylveon** [comment]
You most likely have an antivirus denying ffmpeg.exe permission to write here, as part of an anti ransomware feature.

**Comment by Rynozilla** [comment]
I have no idea how to get around that
The antivirus I use doesn’t have a proactive firewall, as far as I know, could be wrong
I use the free version of Avast

**Comment by trollmad3** [comment]
@Rynozilla noticed the `Permission Denied`, Does that directory exist?

**Comment by Rynozilla** [comment]
@trollmad3 it does, I even went to it before posting here, which adds to my confusion

**Comment by trollmad3** [comment]
@Rynozilla Run ShareX as admin.

**Comment by theoryshaw** [comment]
same problem
