### ISSUE TITLE
Hotkey to end recordings.

### ISSUE THREAD

**Issue by Reasel** [ShareX/ShareX#3753]
I have different hotkeys setup for different recordings. Things like local only recordings, gif, video w/sound, video without.

I would love to be able to set a hotkey to end a recording similar to the abort recording. Something like Ctrl + Alt + Enter will end all recordings. That way I don't have to remember what hotkey I used to start.

I like to keep my hotkeys complex so I don't accidentally trigger them, but that means its hard to end them on the fly.

**Comment by NabiKAZ** [comment]
@Reasel The key for start and stop recording video same is: <kbd>Shift</kbd> + <kbd>Print Screen</kbd>
