### ISSUE TITLE
[URGENT BUG] Custom uploader isn't working with version 12.3.0!

### ISSUE THREAD

**Issue by MoweME** [ShareX/ShareX#3754]
Hello guys,
the custom uploader isn't working anymore from version 12.3.0!
Not just at mine. Other users (they i know) have the same problems.
The upload only outputs the raw domain of the hoster.
I tested it with my server, no files are getting uploaded.
That means, that it isn't not just a display bug.

Fix (for users, not developer):
My current workaround is it to do downgrade to a version they is before the affected version.
In my case i just installed 12.2.0 via the installer. The user doesn't have to change anything at the settings, only click through the wizard. The settings of ShareX stays untouched!
12.2.0 (setup): https://github.com/ShareX/ShareX/releases/download/v12.2.0/ShareX-12.2.0-setup.exe
12.2.0 (portable): https://github.com/ShareX/ShareX/releases/download/v12.2.0/ShareX-portable.zip
As long as this bug has not been fixed, you should not update!

Regards,
Möwe (Seagull)

**Comment by Jaex** [comment]
Most likely your custom uploader configuration using deprecated regex syntax. So you must update it to use new syntax. This is mentioned in changelog.

**Comment by MoweME** [comment]
Doesn't work with updated regex syntax too.

**Comment by Jaex** [comment]
Well without know your custom uploader configuration it is impossible for me to know what is wrong with it.

**Comment by Jaex** [comment]
If your password contains `$` or `\` characters then you must add `\` behind them to escape them.

**Comment by MoweME** [comment]
Doen't works. Just changed the password. Thanks!

**Comment by Jaex** [comment]
You mean it still not works?

**Comment by MoweME** [comment]
It's working now. Thanks for your help!
