### ISSUE TITLE
v12.3.0 Network mapped drives show up as non-existant.

### ISSUE THREAD

**Issue by Confuseh** [ShareX/ShareX#3755]
I have a NAS mounted as network-mapped drive, and as of v12.3.0, trying to save screenshots to directory inside network-mapped drive e.g. `P:\ShareX` will give two errors, [first saying that directory cannot be created/doesn't exist](https://puu.sh/C2plF/ffa78ee0b9.png), [second saying that image couldn't be written](https://puu.sh/C2pn6/a3816cd5ed.png)

Downgrading to v12.2.0 currently serves as a workaround.

**Comment by stuntguy3000** [comment]
@Confuseh I've attempted to replicate the issue and have been unable to do so. Are you able to hop on the ShareX Discord so we can investigate further?

**Comment by Confuseh** [comment]
Ensuring that ShareX is launched as user seems to resolve this, odd how admin wouldn't even have the shares, but oh well. Closing.
