### ISSUE TITLE
Backblaze backend throws SocketException

### ISSUE THREAD

**Issue by cbz** [ShareX/ShareX#3761]
Using the backblaze backend throws the following exception [I can access the bucket from the same machine outside backblaze], additionally the suggested host in the url is incorrect, this bucket is on f002.backblazeb2.com rather than f001.backblazeb2.com

![2018-11-16_18-44-51](https://user-images.githubusercontent.com/142137/48641796-d920a780-e9d2-11e8-8d74-dd02aceef60f.png)

**Comment by trollmad3** [comment]
Could you goto the logs and send the **FULL** error, and not the pop up?

**Comment by cbz** [comment]
Where would I find the logs in this case?

**Comment by cbz** [comment]
Okay - got it, thanks:

> 2018-11-22 21:32:17.098 - Exception:
> System.Net.Sockets.SocketException (0x80004005): No such host is known
>    at System.Net.Dns.GetAddrInfo(String name)
>    at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
>    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
>    at FluentFTP.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)
>    at FluentFTP.FtpClient.Connect()
>    at ShareX.UploadersLib.FileUploaders.FTP.Connect()
>    at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
>    at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 2018-11-22 21:32:17.107 - Task failed. Filename: 2018-11-22_21-32-10.png, Errors:
> System.Net.Sockets.SocketException (0x80004005): No such host is known
>    at System.Net.Dns.GetAddrInfo(String name)
>    at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
>    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
>    at FluentFTP.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)
>    at FluentFTP.FtpClient.Connect()
>    at ShareX.UploadersLib.FileUploaders.FTP.Connect()
>    at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
>    at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by trollmad3** [comment]
@cbz The error `System.Net.Sockets.SocketException (0x80004005): No such host is known` is easy to fix. Did you use an IP address or a hostname when you set up the FTP uploader?

**Comment by cbz** [comment]
Oh okay. That's set to an invalid host - but I assumed that by selecting the backblaze b2 uploader I wasn't using that configuration at all - and ShareX hardcoded the backblaze API endpoint somewhere?

**Comment by trollmad3** [comment]
@cbz I have no idea what you're telling me. Did you use a hostname or IP?

**Comment by cbz** [comment]
I have configured the 'Backblaze B2' backend (with API details), and have that selected as 'Image Uploader'.  I am unclear as to why FTP uploader configuration is being used given that particular configuration.
