### ISSUE TITLE
Feature: do request on deletion URL without opening browser.

### ISSUE THREAD

**Issue by takase1121** [ShareX/ShareX#3763]
I made a small server that will host my image files. Everytime when I want to delete a screenshot from the server a browser window will be opened. In my case, this is pretty useless since the deletion URL is just something like `https://blablabla/delete/fileID` and only returns a JSON response. It'll be nice if ShareX will support sending requests for deletion URLs with browser as alternative option.

**Comment by Xenthys** [comment]
Maintaining ShareXen that also returns JSON for every request, I fully support this idea for multiple reasons:
- Convenience. It would just be easier, maybe have some "Delete from remote uploader" button appear if there is a deletion URL.
- Efficiency. Some people hurt themselves by having a bloated browser taking ages to start, with a lot of extensions. Making a simple request would be faster.
- Security. Some uploaders put the user token itself in the deletion URL. Avoiding it to be in the browser history and seen by extensions would be nice.

I assume people would like POST requests support, aka. deletion would be way more configurable than just being a stored URL in ShareX, but that would probably be too bloated in the end. Having ShareX do the request would already be a nice QOL improvement.
