### ISSUE TITLE
transfer.sh will be back

### ISSUE THREAD

**Issue by trollmad3** [ShareX/ShareX#3768]
![2018-11-18_16-11-44](https://user-images.githubusercontent.com/7843719/48678725-b4e8d600-eb4c-11e8-8555-5e36b21459b3.png)
It says that transfer.sh will be back, are you going to put it back in or no?

**Comment by sylveon** [comment]
It's still in https://github.com/ShareX/CustomUploaders

**Comment by trollmad3** [comment]
Okay, thats good.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2018/11/chrome_IcLvrieab8.png) ???
