### ISSUE TITLE
Default "Select tool" for Image Editor

### ISSUE THREAD

**Issue by Danielku15** [ShareX/ShareX#3769]
**Request**
Please note that this feature request might be a duplicate of #3044 which got stale and was closed by the bot. I hope by this more comprehensive feature request we might get the feature described here. 

Please add a new "select tool" to the image editor which allows users to select/edit/delete any shape that was added via the other drawing tools. It would be great if via an additional option users can decide whether the select tool is automatically activated after any other shape was drawn. Clicking again on the existing tool button in the toolbar should activate again the "select tool". 

The "select tool" should work similar as any other tool for the individual types. e.g. when the rectangle tool is active, you can hover the shapes and they get highlighted as selectable. When selecting you see the additional controls and potentially a double-click opens a editor (text). Once selected users can use the shown controls to edit the shape or delete them via keyboard (DEL). The select tool should allow this for all shape types on the screen without the need of switching to the individual tool. Clicking anywhere, where no shape is results in no action. When a user presses ESC while a drawing tool is active, it should activate the "select tool" to cancel the drawing operation. If ESC is pressed while the "select tool" is active, the existing close confirmation should be shown. 

**Background** 
I just moved from Greenshot to ShareX and so far it looks really nice. I have setup as default task that any screenshot is opened in the image editor for further annotation and decision whether to save or only copy it. 

One main thing I dislike on the image editor is that there is always a "drawing tool" active. For me this results often in some accidentally created shapes. In Greenshot I liked the behavior that the default tool was some sort of "select tool" where you could select and modify any existing shape in the image. Also after drawing any shape, it jumps back to the select tool. 

The behavior in ShareX is a bit tricky to use. If you want to edit or delete any shape, you need to select the correct option in the toolbar and then you can start modifying shapes of this type. Also it seems that freehand drawings cannot be selected and deleted after creation. 

**Dev Info**
It seems that the [ShapeManager class](https://github.com/ShareX/ShareX/blob/9d923aeb13d72d5bba9eec195c542f631baad96e/ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs) is the area that will need mainly the adjustments. It hooks up all events and holds the tool information. The `StartRegionSelection` method has the logic in place that you can only select shapes of the current tool. There we could add the check that it needs to be the current tool or the select tool for selection. Then only the enum for the ShapeType, the UI behavior and the handling of the `ShapeType.Select` needs to be added. Maybe I'll give it a shot to add the feature and file a pull request.

**Comment by Meatplowz** [comment]
@Danielku15 
Have you had any luck updating the drawing being able to be selected?

**Comment by Danielku15** [comment]
Unfortunately not. I digged into the code and see it as feasable. But I didn't get the chance to setup a fork and dev-env for doing any implementation. But I'm still eager to do it 😉

**Comment by baldzilla** [comment]
The "Select Tool" feature is a "must have".  ShareX is great, however, not having the "Select Tool" feature to move around created objects on demand is too cumbersome for me to use.  I will have to use another screen capture because of this feature not being in ShareX

**Comment by bossconian** [comment]
You can't believe how much frustration it inflicts by not having the "Select Tool" and when the editing window disappears when you hit ESCAPE (as you would normally hit to get back to the default "Select Tool"). God.......

**Comment by jacquen** [comment]
It some kind pain without this tool if you want move or delete existed object in image editor. Thanks to add it.

**Comment by mochigithub** [comment]
Could the author comment on this? If this is not planned, I would like to move onto another app.  I love everything about ShareX ( speed, portability), but this is a serious dealbreaker IMO.

**Comment by Danielku15** [comment]
I started with the change today. The behavior works already quite good, I just want to add some more settings to give the user the freedom to choose how the select tool should work. 
Unfortunately it is a bit a chicken-egg issue to show the behavior. I cannot use ShareX to record the "demo" of the changes in ShareX 😆

**Comment by mochigithub** [comment]
Oh my god. thank you so much !!! 
Can you let us know when the feature is added? I am happy to test 

Thanks
Sev

**Comment by baldzilla** [comment]
this is a HUGE feature, I was going to not use ShareX because of that.  I will test also.

**Comment by mochigithub** [comment]
I see updates to the ticket. If there’s a dev build out (without having to compile the files ourselves as I don’t know how to do that) let us know and I am sure there are many people who would be eager to test. I use this feature daily so I’ll figure out a way to break it. Lol!

Thanks
Sev

**Comment by Jaex** [comment]
@Danielku15 implemented this feature now. You can install dev build to test it and give feedback to him: https://getsharex.com/docs/dev-builds

**Comment by ken-colvin** [comment]
I installed the DEV build.  I assume you have to click the select icon to select an object.  
NOTE: The object gets deleted when I Right-Click on object in select mode.

![image](https://user-images.githubusercontent.com/8449843/67113040-964cee00-f1a6-11e9-8092-3d20dcfaaae0.png)
