### ISSUE TITLE
Ability to customize hotkeys

### ISSUE THREAD

**Issue by Rostislaved** [ShareX/ShareX#3773]
Is it possible somehow to change hotkeys for image editor? I used to copy image by ctrl+c with my previous screenshoter, but now I see your one is much better, except that I cann't modify hotkeys. It will allow resolve two of my issues:
1. Copy with ctrl+c (not with shift)
2. Delete 'spacebar' and 'mouse_right_click' hotkeys, which I can press by accident.

**Comment by trollmad3** [comment]
Possible duplicate issue #1621
