### ISSUE TITLE
Shlink support

### ISSUE THREAD

**Issue by silas229** [ShareX/ShareX#3774]
Please add support for [Shlink](https://shlink.io/).

**Comment by Jaex** [comment]
Now I added JSON body support to custom uploader system, so using Shlink should be possible with custom uploader in next version.

**Comment by Jaex** [comment]
I couldn't find example Shlink web site to create and test custom uploader to be able to upload it to https://github.com/ShareX/CustomUploaders

**Comment by dnorelid** [comment]
I'm sorry, but I'm not entirely familiar with how to submit stuff like this, but I made a sxcu for my shlink server and thought it might help some folks

```
{
  "Version": "12.4.1",
  "DestinationType": "URLShortener",
  "RequestMethod": "POST",
  "RequestURL": "https://your-shlink.server/rest/v1/short-urls",
  "Headers": {
    "X-Api-Key": "your-shlink-api-key"
  },
  "Body": "JSON",
  "Data": "{\"longUrl\":\"$input$\"}",
  "URL": "$json:shortUrl$"
}
```
