### ISSUE TITLE
How to set multiple destinations (former Greenshot user)

### ISSUE THREAD

**Issue by FluidNets-DamianS** [ShareX/ShareX#3775]
My default workflow is to capture an area and open in the editor.  However in GS my default was that the capture went to the editor AND the clipboard at the same time.

Second note, while the features in ShareX are way better than GS I really struggle working with the ease I had in GS.

![image](https://user-images.githubusercontent.com/10325877/48750798-f9f53100-ec4e-11e8-9129-716ee5daa254.png)

**Comment by trollmad3** [comment]
I know this sounds difficult but can you explain more when you say 'How to set multiple destinations?'

**Comment by FluidNets-DamianS** [comment]
So what I want to happen is the following by default:
                                  
                                --> Open ShareX Editor
(screen capture) <
                                --> Copy Screen Capture to Clipboard

------------------------------------------------------------------
Then figure out how to easily do the following as seperate workflow/commands:

(screen capture)  >  Editor > Upload  >  Copy URL to Clipboard

**Comment by FluidNets-DamianS** [comment]
That first part comes out ugly no matter what.  When I do a screen capture I want the captured image to open in the editor AND also copy to the clipboard at the same time.

**Comment by FluidNets-DamianS** [comment]
Any  thoughts on this?

**Comment by trollmad3** [comment]
This sounds hard to complete. Did you checkmark everything on this, on what you want to do?
![image](https://user-images.githubusercontent.com/7843719/49120979-794cbb00-f274-11e8-9b36-9b755307fa8a.png)
