### ISSUE TITLE
[Feature Request] Restrict users from changing settings

### ISSUE THREAD

**Issue by totgezockt** [ShareX/ShareX#3781]
Hi there,

I'm deploying this application in a company environment and we don't allow internet traffic. So we disabled the upload feature of your application. Would it be possible to restrict users from editing the config file? Because right now, they would be able to turn uploading back on.

With regards,
Moritz

**Comment by Jaex** [comment]
No.

**Comment by jcyogesh** [comment]
Please reconsider this request. I have configured to displaydate time stamp and want to keep it from changing or modification by any user.

**Comment by totgezockt** [comment]
I wouldn't count this as stale. It is still a request with potential.

**Comment by xan2622** [comment]
Hi @totgezockt.

If you are on Windows, why don't you use the **Firewall with advanced security** ?

It allows you to block outgoing traffic for each software.

**Comment by totgezockt** [comment]
Hi @xan2622,
that, to me, seems more like a workaround than a solution. It would still mean that users can change their settings, which we/I don't want. We want some settings to not be changeable. So good tip, but it isn't what I would like... :/
