### ISSUE TITLE
[Feature Request] Timestamp on video recordings

### ISSUE THREAD

**Issue by jakubswiejkowski-wrk** [ShareX/ShareX#3782]
I wish there was a possibility to add a small hard-rendered timestamp into the video recordings. This should be possible to enable via settings. 

**Such a feature would help the following situation (while using ShareX as screen recorder for software development):**
1. A user/tester is recording himself using the tested app/website. A crash happens.
2. A developer has the recording and application logs. He needs to find the applicable log entries from a huge log file, but the user has forgotten when it happened - and now the dev needs to spend an hour searching through the log and debugging

A timestamp (with system time) visible constantly on the video would help with linking a visible action with the proper log entry.

**Comment by L1Q** [comment]
Is this not the same as having file creation time and frame number/position in recording? Just adding those 2 up would give you enough info to find out the time.

Anyhow, the feature you are requesting if possible is a part of ffmpeg as it's the component that actually does the recording. So as soon as you can make ffmpeg do this, you just need to edit screen recording options in ShareX.

It is also possible to run custom CLI commands against recorded material right after capture. With the power if this feature you could setup additional transcoding pass  to add those timestamps.
