### ISSUE TITLE
Video recording crash

### ISSUE THREAD

**Issue by Arthur-Freedom** [ShareX/ShareX#3787]
hi, when I start a recording it crashes
how to fix it?

![sharex_2018-11-26_16-04-46](https://user-images.githubusercontent.com/18115558/49022780-ff460480-f195-11e8-80bb-f4132cf4074b.png)

**Comment by Mascotte123** [comment]
i restart my comp it work.. no idea why xd

**Comment by derodthegod** [comment]
> i restart my comp it work.. no idea why xd

How did you get it to start back working?

**Comment by Mascotte123** [comment]
No idea, I just restarted my PC and then it worked again. 👍
