### ISSUE TITLE
[Feature Request] capturing sound while video recording

### ISSUE THREAD

**Issue by githubinfidel** [ShareX/ShareX#3790]
Please enable capturing the sound while video recording, sound source could be selected from the different outputs, inputs or both

**Comment by stuntguy3000** [comment]
![image](https://user-images.githubusercontent.com/1522389/49280151-540cb680-f4d9-11e8-9b72-11b4d4fced18.png)

Already a feature.

**Comment by Deilan** [comment]
> ![image](https://user-images.githubusercontent.com/1522389/49280151-540cb680-f4d9-11e8-9b72-11b4d4fced18.png)
> 
> Already a feature.

And how to enable it?

**Comment by stephen147** [comment]
You mean this?

<kbd>Install recorder devices</kbd>

![image](https://user-images.githubusercontent.com/14054664/60199888-cf023980-983c-11e9-8def-81155a5c48ea.png)
