### ISSUE TITLE
Ctrl+A not working in ShareX Hash check

### ISSUE THREAD

**Issue by Mitsuma** [ShareX/ShareX#3792]
Fairly minor thing, but I noticed that Ctrl+A to select all doesn't work in two text boxes of the Hash Check tool.

That being the "Result" and "Target" textboxes. 
It does work just fine in the "File path" as well as the others in the "Text conversions" fields.

It is just a minor inconvenience as you can still double click to select all, I'm personally just used to using ctrl+a to select all and was wondering why it didn't work there. 
Right click - Select all works as well.

ShareX Version 12.3.1
Windows 10 v1803 64bit

**Comment by stuntguy3000** [comment]
I can't replicate this for the _target_ textbox but can for _result_. Referenced fix above.
