### ISSUE TITLE
Instant capture and upload without pressing enter?

### ISSUE THREAD

**Issue by Ovicron** [ShareX/ShareX#3793]
I want to capture without needing to pressing enter. PLEASE BRING IT BACK. I regret updating so much. I just want it to instantly capture whatever I highlighted without pressing enter.

**Comment by sylveon** [comment]
Disable multi-region mode
![](https://cdn.discordapp.com/attachments/279655394496872449/516003853859160064/unknown.png)

**Comment by Ovicron** [comment]
Thanks a LOT!!!
