### ISSUE TITLE
12.3.1 Portable downloads 12.2

### ISSUE THREAD

**Issue by analogueworld** [ShareX/ShareX#3797]
The 12.3.1 portable download opens up a 12.2 version?

**Comment by Jaex** [comment]
It is not?

![](https://jaex.getsharex.com/2018/12/Q4Y15YhWRA.png)

**Comment by analogueworld** [comment]
My bad. I already had ShareX portable 12.2 open. Then downloaded the 12.3.1 version and tried to open that. However, I didn't realize that if the 12.2 version is already open, even if you thereafter open the 12.3.1 exe, then the 12.2 share-x appears and not the 12.3.1
