### ISSUE TITLE
Screenshot became a circle

### ISSUE THREAD

**Issue by Mascotte123** [ShareX/ShareX#3798]
I take a lot of screenshots and suddenly it changed to a circle, why?
how can I change it back?
![sharex_2018-12-02_11-36-12](https://user-images.githubusercontent.com/18115558/49338754-9abbf700-f626-11e8-950b-93d061797b79.png)

**Comment by Jaex** [comment]
Select this in region capture:

![](https://jaex.getsharex.com/2018/12/ShareX_cIWEg22w7Q.png)

**Comment by Mascotte123** [comment]
Errr.. that area with those buttons don't appear for me 
:-(
