### ISSUE TITLE
"Shadow" image effect shift items

### ISSUE THREAD

**Issue by gpion** [ShareX/ShareX#3799]
Applying "shadow" image effect shifts previously drawed shapes.
I've added a rectangle around the "content" word
Here's the result
- Before applying effect: 
![before effect](https://i.imgur.com/MUCUR7l.png)
- After: 
![After effect](https://i.imgur.com/m2BvIop.png)

Note: this can be specific to "shadow" effect, I didn't test others effects.

**Comment by Jaex** [comment]
Image editor can't know how much to shift shapes because depending on applied effects margins can be random from each side.

**Comment by gpion** [comment]
I miss Greenshot editor even more
