### ISSUE TITLE
Modifier Key(s) to reverse arrow direction

### ISSUE THREAD

**Issue by jonnyb023** [ShareX/ShareX#3803]
When pointing to a line of text with the Shift key, it can be difficult to keep it vertically aligned with the center of that line of text, seen here:
![image](https://user-images.githubusercontent.com/19791293/49464247-6122f180-f7c8-11e8-9288-55c369832df8.png)
It would be much easier if you could start at the text, drag/draw the arrow outward, and reverse the arrow direction so it was pointing back in.

**Comment by Jaex** [comment]
You can also hold ctrl to move whole arrow that way you can align it vertically more easier?

**Comment by jonnyb023** [comment]
Almost, except when I first hold Shift, then hold Ctrl, it's like the Ctrl overrides the Shift instead of combining the functionality.  Then my arrow is horizontal anymore.  If that were fixed then it would work! :)
