### ISSUE TITLE
CLI after screen recorder

### ISSUE THREAD

**Issue by IcedCoffeee** [ShareX/ShareX#3805]
Can you add back the CLI after record option? I used to use it to encode to VP9 after recording with NVENC, for minimal CPU usage while recording games and etc, then converting it to VP9 to keep the file size down because I have slow upload speed.
The new feature doesn't let me achieve this.

**Comment by Jaex** [comment]
ShareX actions gives nearly identical functionality but lacks deleting input file after output file is created. I'm adding that option now.

**Comment by Jaex** [comment]
Like this:

![](https://jaex.getsharex.com/2018/12/ShareX_8mmGYKZdvA.png)
