### ISSUE TITLE
[Feature Request] Allow the user to convert any video to GIF using ShareX's encoder

### ISSUE THREAD

**Issue by SimoFiuz** [ShareX/ShareX#3807]
Converting small portions of video files to GIF is a common task, and since ShareX does variable size capture so well, it would be super nice to have a builtin feature to convert any user supplied video file in .gif format using ShareX's Task Settings for screen recording.

**Comment by Scrxtchy** [comment]
ShareX is just using ffmpeg for handling media, I suggest you to look into scripting for it, a batch file works just as well.

Even though gifs suck

**Comment by eyoxin** [comment]
This became "stale" but would be a really convenient feature to have a simple way for sharex to do the conversion since it already uses ffmpeg.

**Comment by Jaex** [comment]
> This became "stale" but would be a really convenient feature to have a simple way for sharex to do the conversion since it already uses ffmpeg.

ShareX already can do that?

![](https://jaex.getsharex.com/2022/08/ShareX_djK0OlDnIJ.png)

**Comment by eyoxin** [comment]
Oh wow im sorry, i didnt know this was a feature and googling for it led me
to this issue.

**Comment by ardamaks** [comment]
after pressing "Start encoding", nothing happens. Also no file produced.

**Comment by julianmojico** [comment]
This worked great!

![image](https://github.com/ShareX/ShareX/assets/12740590/d992155b-0b4b-4989-93aa-1a8729f19af5)
