### ISSUE TITLE
Whether the file uploaded by default violates the privacy of users

### ISSUE THREAD

**Issue by sunqianGitHub** [ShareX/ShareX#3810]
By default, the automatic upload file has been selected. I found it after many days of use. Is it reasonable to do so?And there are no obvious clues.Are account and password saved in user screenshot or privacy leakage codes taken into account?

**Comment by stuntguy3000** [comment]
> And there are no obvious clues

![image](https://user-images.githubusercontent.com/1522389/49632804-f29f9700-fa46-11e8-89d3-37d275a2a2af.png)

https://youtu.be/Ag1o3koTLWM
