### ISSUE TITLE
after capture not working well?

### ISSUE THREAD

**Issue by kevindevm** [ShareX/ShareX#3811]
![image](https://user-images.githubusercontent.com/7692819/49679343-5c309d00-fa69-11e8-8f13-5d6d6b8b8dd3.png)
just do the first thing never copy nor save, can i change the the order? copy → save → open?

**Comment by dgasaway** [comment]
I encountered this as well, with the same after capture tasks.  I think the problem is with the 'Open in image editor' action.  If I turn that off, it will copy and save.  If it's on, it neither copies or saves.

**Comment by kevindevm** [comment]
so? its a bug or is intended?

**Comment by edmunek** [comment]
was that ever fixed?
