### ISSUE TITLE
[feature request] scrollable screenshot

### ISSUE THREAD

**Issue by FernanDK** [ShareX/ShareX#3813]
hey folks, scrollable screenshots are common practice on Android OS. I know Windows makes things tough, but still, it's doable so I came here to ask in the name of the community. For sure it would be super useful and awesome to have the ability to take screenshots of entire vertical pages or long horizontal excel sheets. pretty please?

**Comment by stuntguy3000** [comment]
![image](https://user-images.githubusercontent.com/1522389/49686050-ac2d6380-fb3e-11e8-880f-ad176b8f12c2.png)

**Comment by FernanDK** [comment]
marvelous. worked perfectly! Thank you for the heads-up @stuntguy3000
