### ISSUE TITLE
Incorrect capture region with vertically stacked monitors

### ISSUE THREAD

**Issue by cptnoblivious** [ShareX/ShareX#3816]
For whatever reason, the region selector only has access to the "top" monitor in this configuration and tries to stretch it to fill the total desktop area. The problem does not occur if the one monitor is below the other three, however. While I can consistently reproduce this problem, I don't really know the exact reasons why certain monitor layouts cause the error and others do not.
[https://i.imgur.com/EEfJaT9.jpg](https://i.imgur.com/EEfJaT9.jpg)

**Comment by Jaex** [comment]
I don't have multi monitor and you guys making it even more difficult for me to guess how those monitor configurations work with such setups :(

**Comment by cptnoblivious** [comment]
There's an amount of this I know is "that's a very specific setup I've got here" and edge cases are never fun. It's certainly not any kind of high priority. If you have any ideas on how I can best test various combinations of things for you, I'll be more than happy to research whatever I can. I just don't know where to start.
