### ISSUE TITLE
[Feature Request] Auto split videos by duration or size

### ISSUE THREAD

**Issue by vunsb** [ShareX/ShareX#3818]
First of all thanks for this amazing soft!  
It would be great to be able to set limit for file duration and/or file size so that captured video is automaticly split in files  that are all for example 1h long or 500MB large.

**Comment by stuntguy3000** [comment]
ShareX is not a good tool for capturing _long_ videos, due to the risk of corruption and other non user friendly issues

**Comment by vatterspun** [comment]
> ShareX is not a good tool for capturing _long_ videos, due to the risk of corruption and other non user friendly issues

I haven't tested this recently, but Jaex has stated this in the past #3319 and recomends the excellent OBS tool.  I have and will continue to use it to record meetings with better overall quality than Skype and other recorders.  It's excellent.
