### ISSUE TITLE
ShareX won't upload large files

### ISSUE THREAD

**Issue by bratan98** [ShareX/ShareX#3819]
Hello,

Whenever I try to upload a large file (100mb+) with the drag&drop option (which I really love for smaller files) it won't work. It will upload (very slowly) to about 10-20% and then just cancel. If you would somehow manage to fix that it'd improve my life a lot. Another common issue is that the file hits 99% but then just stops and starts at 0% again. Thanks for reading. 

(only sendspace seems to work, even though it takes unusually long to upload as well)

**Comment by ploughedfieldman123** [comment]
why are some files slow to upload.  I mean i have a picture a .jpg its only 4.41MB   its taken ages its now been a good 3 mins and its just a 4.61MB  I am windows 10 with 8GB ram
