### ISSUE TITLE
How do I run sharex from commandline to immediately record the whole screen?

### ISSUE THREAD

**Issue by nitrocode** [ShareX/ShareX#382]
Hi. I'm running the following command now

> cmd /k Z:\Utilities\ShareX\ShareX.exe -portable -ScreenRecorder

And then I have to select the coordinates of the screen to record. I'm trying to integrate ShareX with my company's automation software. I'm having issues automating the mouse movements due to limitations with the automation software. 

Is it possible to run this from the commandline without having to drag the mouse?

> cmd /k Z:\Utilities\ShareX\ShareX.exe -portable -FullScreenRecorder

**Comment by nitrocode** [comment]
Hi Jaex. A couple more questions.

I've explored the ffmpeg option and I was just curious, if I'm using ShareX's ffmpeg, what video device does ShareX use so I don't have to install a new one?

    ffmpeg -list_options true -f dshow -i video="Decklink Video Capture"

Also regarding change #382, does this add recording full screen cli support to ShareX? If not, may I add that as a reasonable enhancement? :)

**Comment by Jaex** [comment]
That command line (-StartScreenRecorder) starts screen recorder using last region.

You can see what video devices ShareX using from video device list.

**Comment by xpxrzerr** [comment]
You can also stop recording from the command-line by running ShareX.exe -StartScreenRecorder a second time
