### ISSUE TITLE
Customize file naming for images copied from clipboard

### ISSUE THREAD

**Issue by diegoteliz** [ShareX/ShareX#3820]
I currently have a pattern configured on file naming options (`screenshot_%y%mo%d-%h%mi%s`), however, when I use the "Copy image to clipboard" option in the image editor and then I paste it anywhere else by hitting `CTRL + V`, the file name is `image.png`.

See example in Asana:
![image](https://user-images.githubusercontent.com/7451265/49839383-afad3d00-fe13-11e8-8bbd-f56b1b7b36f8.png)

I'd like to set a custom pattern for that if possible :)

**Comment by Jaex** [comment]
Image in clipboard not contains file name. It is bitmap.
