### ISSUE TITLE
when f.lux is enabled, sharex captures a red tinted image

### ISSUE THREAD

**Issue by mailinglists35** [ShareX/ShareX#3824]
not sure if I correctly described this in title, so here are some images taken with my phone
https://imgur.com/a/q5xhpJs

**Comment by stuntguy3000** [comment]
This is exactly how it should happen. Flux will cause ShareX to red tint images, and then by showing the tinted image Flux tints it some more, rinse and repeat.

**Comment by mailinglists35** [comment]
>This is exactly how it should happen

ooops you are right. f.lux appears to also affect all other apps including game bar or snipping tool. I will try to pursue this issue on f.lux then (albeit on their forums there is nothing indicating intention for supporting command line interface, scripting or api interaction with other apps.)

How do you see a solution to this?

I see it has an Alt-End keyboard shortcut that toggles it on/off - do you think it would be feasible to make ShareX simulate this keypress before and after taking the screenshot?

(otoh interesting is that windows 10 night light appears to do the color effect on the data sent to monitor while the screenshot remains unaffected)

**Comment by stuntguy3000** [comment]
I've moved from Flux to Windows 10 Night Light for that very reason.

**Comment by mailinglists35** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/winforms/how-to-simulate-mouse-and-keyboard-events-in-code

**Comment by AGSPhoenix** [comment]
I'm not seeing this behavior. Just took this screenshot with f.lux turned all the way down to firelight: ![image of f.lux set to the strongest setting. No color distortion is visible in the image.](https://user-images.githubusercontent.com/450785/50733170-a8e5c180-1156-11e9-8f7a-08811f77ff80.png)  Running f.lux 4.84 and ShareX 12.3.1.

**Comment by stuntguy3000** [comment]
@AGSPhoenix I guess this is because you're on Windows 7.

@mailinglists35 @Jaex Can be closed as `invalid` I think.

**Comment by mailinglists35** [comment]
@Jaex I hope maybe when you have time to revisit this. It's just a matter of simulating pressing Alt-End from within .net code.

**Comment by woctezuma** [comment]
> 
> 
> I've moved from Flux to Windows 10 Night Light for that very reason.

Thank you. I could keep ShareX and drop f.lux.

**Comment by mailinglists35** [comment]
@woctezuma try with latest f.lux beta, it is fixed for me

**Comment by mailinglists35** [comment]
@woctezuma update, it is broken again. I did change nothing. it would still be nice if @Jaex workaround with those simulated keypresses

**Comment by bencooper222** [comment]
This error is happening for me with Windows night light now. Anyone else?

**Comment by bencooper222** [comment]
It's traceable to this. Not ShareX's fault: https://www.laptopmag.com/articles/windows-10-update-orange-bug

**Comment by mailinglists35** [comment]
yes it’s windows’ fault, but neither @jaex wants to do a very simple workaround by simulating a keypress in the sharex app (f.lux has registered global hotkey alt-end to toggle enable/disable)
  

  
  

  
  
>

**Comment by FrankSalmick** [comment]
I encountered this problem from google and tried your solution @mailinglists35, but it doesn't work as Flux has a transition time. Even if Flux is set to "Very Fast: Gaming", there's still a (200ms I think) delay between your screen being white and orange. 

Anyway, switching to night light fixed it for me as well so thanks!

**Comment by ctsstc** [comment]
Been having this problem ever since the ol windows update from a year or two ago.

- **Windows**: `19043.1586`
- **Flux**: `4.120`
- **Sharex**: `13.7`

I kind of figured there was no fix given how long it's been. Then I regained hope today when I saw Window's screen snipping tool seems to get around it somehow 🤔

**Comment by mailinglists35** [comment]
@ctsstc for me the issue persists but also the workaround keeps working: press Alt-End, f.lux disables, press PrtScr or use ShareX menus to capture (it only matters at the time of capture), press Alt-End again to enable f.lux

**Comment by Cellora09** [comment]
Go to f.lux > option > Disable > for full screen application

**Comment by AceCooper** [comment]
Even better, f.lux now has a separate option: 
right click f.lux > Disable > when using ShareX

**Comment by psy0ch** [comment]
Even with this option my screen goes very orange for a second or two before actually readjusting to the normal colors. im using both option to disable the tint, disable for fullscreen applications + disable when using sharex

**Comment by LapinskasL** [comment]
> Even better, f.lux now has a separate option: right click f.lux in tray > Disable > when using ShareX

Sounds like the perfect setting, but I don't see it. Is it still there for you?

**Comment by Tmnath** [comment]
> > Even better, f.lux now has a separate option: right click f.lux in tray > Disable > when using ShareX
> 
> Sounds like the perfect setting, but I don't see it. Is it still there for you?

For future reference: you need to open ShareX's main window for the option to appear in f.lux

**Comment by zirib** [comment]
This issue is still present, and the "Alt+End" or "Disable when using Share X" workarounds don't work (i.e. you can't just PrntScr and have the tint not be there, it's always after a transition time (either post Alt+End or post opening the main ShareX window). It's weird because I've had periods (maybe versions?) when this issue would go away on its own.

**Comment by a-wil** [comment]
Does anyone have a fix for this? The disable when using ShareX method doesnt really work for me as others have said about the delay

**Comment by pyxelr** [comment]
> Does anyone have a fix for this? The disable when using ShareX method doesnt really work for me as others have said about the delay

Not really. I observed that this issue comes and goes, but is rather rare.
