### ISSUE TITLE
Encrypted paswords

### ISSUE THREAD

**Issue by Vampie** [ShareX/ShareX#383]
Hi,

I wanted to transfer settings (C:\Users<username>\Documents\ShareX\UploadersConfig.json) to a new PC an had a look inside the file.

To my suprise, I saw that the login to the services I configured, did NOT have an encrypted password in the file.

Isn't that a big threath to the secutiry of the program?

Kind Regards,
Vampie.

**Comment by Jaex** [comment]
I was reading this now and they also write similar stuffs to what I wrote: https://developer.pidgin.im/wiki/PlainTextPasswords
