### ISSUE TITLE
Configuration Files being saved in the Screenshot folder

### ISSUE THREAD

**Issue by Suyeta** [ShareX/ShareX#3830]
I am having an issue with my work computer. I have convinced everyone to try sharex because I want to use it at work. But some of my coworkers prefer snagit. I was messing with the settings trying to make ShareX work almost exactly like snagit and the next thing I knew it was saving my settings and the backup folder inside the Screenshots folder. I have tried just deleting the extra files but then sharex just closes randomly and when I reopen it, it acts like it's the first time I've ever run it. Is there a way to fix this without reinstalling? I don't want to bug my server admin for his login for another program install lol I've already had to bug him a lot recently.

**Comment by Jaex** [comment]
This is where ShareX stores its configuration files:

![](https://jaex.getsharex.com/2018/12/ShareX_jpHPFZl2qj.png)

So you must have changed it.

**Comment by Jaex** [comment]
![]https://jaex.getsharex.com/2018/12/ShareX_Is9sVWKr1j.png)

**Comment by Suyeta** [comment]
Thank you!
