### ISSUE TITLE
Cant install sharex on windows 7 32bit

### ISSUE THREAD

**Issue by RazorApple** [ShareX/ShareX#3833]
): 
img below
![capture](https://user-images.githubusercontent.com/35845382/50052712-2490b780-0131-11e9-841c-263370c455b0.PNG)

**Comment by Jaex** [comment]
.NET Framework 4.6.2 requires Windows 7 Service Pack 1.

**Comment by RazorApple** [comment]
1. I use .net framework 4.5.2 and I dont have SP1
2. How can I get sp1

**Comment by vatterspun** [comment]
>How can I get sp1

It's free: https://support.microsoft.com/en-us/help/15090/windows-7-install-service-pack-1-sp1
