### ISSUE TITLE
Imgur file limit 10mb

### ISSUE THREAD

**Issue by MrGoatsy** [ShareX/ShareX#3835]
The limit of Imgur is bigger than 10mb as I uploaded the picture fine via their website.

**Comment by Jaex** [comment]
Imgur API have 10mb limit.

**Comment by Reasel** [comment]
@Jaex according to their documentation it is 200MB for gifs. Is there a reason my 112MB file got a "File is over the size limit" error from the API? Is it simply that the API is lying?

**Comment by Jaex** [comment]
Imgur is unblocked in my country now so finally I could take screenshot from API doc:

![](https://jaex.getsharex.com/2020/02/chrome_mcs6lrwl3W.png)

**Comment by Reasel** [comment]
Yeah awhile after seeing this I found out that the actual specs are 10MB. Their Documentation for a video file states 
![image](https://user-images.githubusercontent.com/1210740/74178794-0a495100-4bf1-11ea-9d15-c17f4f3c29e4.png)

The reason I ask is that I would love to be able to upload a video and have imgur turn it into a gif. They have this available https://imgur.com/vidgif. Just wanted to be able to push videos to gif format in imgur up to 200MB.

**Comment by Patrity** [comment]
That's their file size limit for homepage uploads via their own system. Any third party must use their API. API limit is 10mb.

**Comment by jackTabsCode** [comment]
The API limit for videos is clearly 200MB. It says it right on the page.
