### ISSUE TITLE
Add a 'Cancel' button for touch screen.

### ISSUE THREAD

**Issue by Explorare** [ShareX/ShareX#3838]
It seems that the only way to exit the screen capture mode is to press the `ESC` button in the current version, which is inconvenient for a Windows 10 tablet. Is it possible to add a cancel icon in the toolbar or somewhere else?
Thanks

**Comment by Explorare** [comment]
Thanks. And if it's possible to add a cancel button here?
![image](https://user-images.githubusercontent.com/5090766/50083790-d7dfd600-022f-11e9-92f9-d875d26b1d70.png)

**Comment by Jaex** [comment]
Close button is cancel button.

**Comment by Explorare** [comment]
If it is possible to also include a trigger to show the close button when the tablet mode is off? Because the system tray icons won't show up with the tablet mode is on, so I always switch back to desktop mode to click the tray icon and active the screen capture mode. Thanks.

**Comment by Scrxtchy** [comment]
If in doubt, you should be able to long-press on the screen to do a right click.
I have this bound to cancel capture
![image](https://user-images.githubusercontent.com/12771982/50536178-c25e9a80-0ba5-11e9-8887-f2f1c189d128.png)

**Comment by Jaex** [comment]
> Works like a charm. Thanks!

What works?

**Comment by Explorare** [comment]
> 
> 
> > Works like a charm. Thanks!
> 
> What works?

As @Scrxtchy said, long-press will trigger a right-click, which can cancel capture.

**Comment by Jaex** [comment]
So am I added close button for no reason.

**Comment by Explorare** [comment]
There is, actually. It would be the same question as "How to exit Vim?" for the new users with a detachable tablet. And again, thanks for this project and your great effort. Happy new year.

**Comment by Scrxtchy** [comment]
Closing with a pen/finger has always been jank as fuck
