### ISSUE TITLE
Wanting to make a one-off donation?

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#3840]
Just a note to anyone who wants to make a one-off donation but does not have Bitcoin. You can use Patreon for this. I just found it only takes a a few seconds to sign-up, pledge to ShareX and then cancel the recurring pledge. You don't even have to confirm your email address. Start here: [https://www.patreon.com/ShareX](https://www.patreon.com/ShareX).

And to the ShareX team, my heartfelt thanks for all the time your program has saved me.

**Comment by vatterspun** [comment]
It's possible to sign up on Patreon to support ShareX and then disable it.  The service should (based on a recent test) automatically send a payment for that month.  After which, you can turn off support.

**Comment by Ivoz** [comment]
It would be nice if you had a PayPal address to donate to, or any other such service which could for example handle a credit card donation. I also am not interested in dealing with bitcoins for the moment.

**Comment by Jaex** [comment]
@Ivoz PayPal is banned in my country, I can't use it. But Patreon supports PayPal.

**Comment by vatterspun** [comment]
> PayPal is banned in my country

Have you looked into https://liberapay.com/ ?
