### ISSUE TITLE
V12.3.1 Problems with webpage capture

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#3841]
Webpage Capture fails variously on most pages I've tried. Examples include an empty black image, an error like this on https://getsharex.com/ [https://i.imgur.com/IpV732S.png](https://i.imgur.com/IpV732S.png) or an image with rough quality and white marks, and a different layout like this [https://i.imgur.com/VsHXHW0.png](https://i.imgur.com/VsHXHW0.png) from original [https://i.imgur.com/8vnwkGn.png](https://i.imgur.com/8vnwkGn.png).

Thanks last one refers to Internet Explorer, so I guess the issues are due to ShareX replaying on that browser component.

**Comment by Jaex** [comment]
Webpage capture loading page in IE and taking capture of it. This gives poor results therefore I suggest you to use built in capture methods of web browsers like this: https://getsharex.com/docs/website-capture

**Comment by chrisjj** [comment]
Thanks.

By the way, re your "Chrome will then take a full-page screenshot of the
website, and put it in your Downloads folder.", here (Windows 7) is offers
a Save As.. dialog showing the last folder in which I saved, which may or
may not be Downloads.

**Comment by Jaex** [comment]
It not shows save as dialog for me.

**Comment by chrisjj** [comment]
Ah. Then one of us has changed Chrome setting "Ask where to save each file
before downloading". I didn't think it was me but I could be wrong! :)

**Comment by Jaex** [comment]
I don't remember changing it, I thought it was disabled by default.
