### ISSUE TITLE
Ability to upload html text (fonts, bolding, sizes, hyperlinks, etc.) 

### ISSUE THREAD

**Issue by janjanis** [ShareX/ShareX#3847]
Hello,
Thanks for great app! I use it everyday!
Only thing that I miss is ability to upload html text ([example](https://anotepad.com/notes/ygb5gw)). Instead theyŗe always .txt files (like [this](https://anotepad.com/notes/tpg329))

It this something that could be considered adding in future?
I always assumed that this isn't due to tehnical limitations, but if it is, then by all means, my apologies, and thanks for great app :)

Cheers :)
Janis

**Comment by Jaex** [comment]
You can do it like this:

![](https://jaex.getsharex.com/2018/12/ShareX_fRgX8CpmaU.png)

**Comment by janjanis** [comment]
Hmm, i noticed that and suspected that, but wasn't able to find any documentation for it online.

I tried to mess with this like [this](https://i.imgur.com/3uaTrHo.jpg) but it didn't work.

Do you know exactly what you put there?

Thank you so much :) I really do appreciate it. 

janis

**Comment by janjanis** [comment]
Hei :)
Sorry to bother you again. Don't mean to be hassle here.
It seems that you've closed down this thread, and thus my messages don't come to you.

Um, if you don't have for this, can you collequielly tell me where I can find it. There wasn't no info in sharex.com or https://github.com/ShareX/ShareX , but if I've missed something please do let me know.

Thanks a bunch :)
Janis
