### ISSUE TITLE
Feature request: capture with delay from menu

### ISSUE THREAD

**Issue by munrobasher** [ShareX/ShareX#3849]
I'm aware that there is a setting to turn on captured delay, but that's a faff to turn on and more importantly, I always forget to turn it off and then wonder why Ctrl-PrintScreen doesn't appear to be working so I press it again, and again and end up with multiple captures.

It would be useful therefore to be able to trigger a one-off delayed capture from the menu. Maybe another checkbox where "Show cursor" is currently that says "One-off delayed capture" - unchecks itself after the next capture?

It's the one feature from WinSnap that I miss after switching to ShareX which otherwise is way better.

**Comment by Jaex** [comment]
I added this few days ago:

![](https://jaex.getsharex.com/2018/12/RuEOVlHluQ.png)

should be good enough for your needs.

**Comment by munrobasher** [comment]
Not very familiar with GitHub. How do I label this as an enhancement?

**Comment by munrobasher** [comment]
I've got 12.3.1 and can't see this? Coming in the next version?

**Comment by munrobasher** [comment]
Later... I've checked I've got the latest version v12.3.1 and I'm still unable to see this new option. What am I missing?

**Comment by Jaex** [comment]
It is not released yet, I meant "added in codes".
