### ISSUE TITLE
Feature Request- Option to disable News

### ISSUE THREAD

**Issue by xMateMCPE** [ShareX/ShareX#3850]
I always disliked news in applications due to it using traffic and showing things most people doesn't care about. I think there should be an option to disable showing and downloading news for people that doesn't need it.

**Comment by stuntguy3000** [comment]
I dislike this request for a few reason.

a) The news source file is **1.9 KB**. Opening a browser will use more data than that.
b) The news is **important** at providing important information, from new releases to important deprecation notices.

If you don't like it, don't click on the news tab. It stays hidden until you need it.
