### ISSUE TITLE
Doesn't upload after screenshot?

### ISSUE THREAD

**Issue by duftwatterson** [ShareX/ShareX#3851]
At some point, ShareX quit uploading images for me automatically. I used to take a screenshot and it would immediately copy a ` puush.me/img.png` link to my clipboard. Now, it just takes a screenshot and saves it locally. I have gone through the settings pretty exhaustively trying to fix this. If I manually right-click an image, it will upload as usual, but it doesn't ever auto-upload. Is this a bug, or am I doing something wrong?

**Comment by Jaex** [comment]
Is this checked:

![](https://jaex.getsharex.com/2018/12/Z8hRqNj58k.png)
