### ISSUE TITLE
Support saving in .avif (AV1 Image File Format)

### ISSUE THREAD

**Issue by EwoutH** [ShareX/ShareX#3853]
AVIF (AV1 Image File Format) is a new image format based on the AV1 video codec. It supports both lossless and lossy compression and [saves](https://calendar.perfplanet.com/2018/is-avif-the-future-of-images-on-the-web/) up to 50% space at the same quality compared to JPG.

A checkbox for lossless compression (enabled by default) and a slider for the quality/compression ratio when lossy compression is used would be nice.

Here is the [AVIF specification](https://aomediacodec.github.io/av1-avif/) and some .avif samples from [Netflix](http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/) and [Microsoft](https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Microsoft). AVIF files can currently be viewed with [VLC](https://nightlies.videolan.org/) and are going to be supported soon in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1443863) and [Windows 10](https://github.com/AOMediaCodec/av1-avif/wiki).

**Comment by Scrxtchy** [comment]
Would be up to Jaex if he wants to add another library for this (which is very rare), as I don't think a .NET framework update will happen any time soon, as it is currently used for saving captures to images.

Another option that should work today is to add an action that is performed on capture. This can allow the use of ffmpeg to a similar application to convert an already captured file into your desired format for uploading

**Comment by vatterspun** [comment]
> Another option that should work today is to add an action that is performed on capture. This can allow the use of ffmpeg to a similar application to convert an already captured file into your desired format for uploading

You'd want to use a high-quality, low compression method.  I'd probably start with x264 set to "ultra fast" and the highest quality AAC audio.  It takes a lot more disk space to record, but would turn out much better in the end.  Compressing a video that's already been compressed at roughly the same bitrate is just going to look ugly.

Related #2265

**Comment by EwoutH** [comment]
[libavif](https://github.com/joedrago/avif) tagged a new release, [0.1.3](https://github.com/joedrago/avif/releases/tag/v0.1.3). See [Colorist](https://github.com/joedrago/colorist) for an example [implementation](https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c).

**Comment by ibex-are-goats** [comment]
Any progress?

**Comment by vatterspun** [comment]
I think it's worth noting how one of the more popular image encoding programs (Handbrake) has reacted to AV1: https://github.com/HandBrake/HandBrake/issues/457#issuecomment-380591452 ... I think that's a good indication of what should happen with other encoder software.  Ultra slow compression is not something most ShareX users are going to want, regardless of the file size and quality improvements.

**Comment by rudolphos** [comment]
@ibex-are-goats same question. FFmpeg now supports AV1. https://trac.ffmpeg.org/wiki/Encode/AV1

**Comment by Dreadaxe** [comment]
Any progress?

**Comment by nixatsnow** [comment]
to be able to save screenshots as WebP and AVIF would absolutely be so amazing!
Any light at the end of the tunnel? :)

**Comment by 3xploiton3** [comment]
This is future for data saving

**Comment by derekhearst** [comment]
I would also love this

**Comment by Dreadaxe** [comment]
+1

**Comment by koloved** [comment]
i made the script that will auto install/config ShareX to use AVIF format for video and images

https://gist.github.com/koloved/dad73f942f92b592763dc7be7308a7b8

**Comment by Dreadaxe** [comment]
> i made the script that will auto install/config ShareX to use AVIF format for video and images
> 
> https://gist.github.com/koloved/dad73f942f92b592763dc7be7308a7b8

Can you explain in more detail, for example with a video or screenshots?

**Comment by koloved** [comment]
> > i made the script that will auto install/config ShareX to use AVIF format for video and images
> > https://gist.github.com/koloved/dad73f942f92b592763dc7be7308a7b8
> 
> Can you explain in more detail, for example with a video or screenshots?

its just auto create two actions and download ffmpeg that support av1
1) mp4 convert to avif (without audio, if you need it , you should modify the action command)
2) png convert to avif too (but as single image)

![Image](https://github.com/user-attachments/assets/4bb3fd50-2a72-4e44-9333-64f333d58492)
