### ISSUE TITLE
Google Drive login fail

### ISSUE THREAD

**Issue by choreno** [ShareX/ShareX#3855]
I got a log in fail when I did paste a verification code and click the step2 button. 
Please do check the Google drive upload verification processes. 
Thank. 

![image](https://user-images.githubusercontent.com/2278053/50519344-6c480500-0a88-11e9-90da-aa9c54cfa36b.png)

**Comment by choreno** [comment]
Can it handle such code, especially, special characters ("/", etc )?  
(Note: some characters are intentionally changed for security of my file)

4/wQC2Hc8sJXpgS4MyDTbaQ3wj7z6x06MX1GU68VviORK_yVR9N5rm7GggY

P.S When I use picPick app there is no problem to save at my google drive. 
Thanks

**Comment by choreno** [comment]
By the way, what's the meaning of red color font  vs black color font at screenshot.

**Comment by YisroelTech** [comment]
Yes it can handle verification codes like this (this is how google's verification codes always look.)

The black color font means that it is available to use (either no sign in needed or already signed in) whole the red font means that it cannit be used yet since it is not authenticated.
