### ISSUE TITLE
当我使用sharex 标注文字时，输入法指示器浮窗不展示了 | When I use sharex to annotate text, the input method indicator does not show up.

### ISSUE THREAD

**Issue by geekyouth** [ShareX/ShareX#3858]
***
当我使用sharex 标注文字时，输入法指示器浮窗不展示了 

When I use sharex to annotate text, the input method indicator does not show up.

正面的例子| Positive example ：
![image](https://user-images.githubusercontent.com/12899262/50544156-9edc3400-0c27-11e9-9961-aedfe7e60bdc.png)

反面的例子 | Negative example ：
![image](https://user-images.githubusercontent.com/12899262/50544159-c206e380-0c27-11e9-842c-1918302e9c51.png)

当我使用sharex 标注文字时，输入法指示器不展示了，导致我不知道我正在使用哪种输入法，切换输入法没有任何浮窗提示。

When I use sharex to annotate text, the input method indicator is not displayed, causing me to not know which input method I am using. There is no floating window prompt for switching input methods.

**Comment by geekyouth** [comment]
who can help me ？

**Comment by Scrxtchy** [comment]
Which input method are you using?

**Comment by yinyue200** [comment]
你用的啥输入法？

**Comment by geekyouth** [comment]
baidu pinyin input method | 百度拼音输入法
