### ISSUE TITLE
Unable to capture in ellipse?

### ISSUE THREAD

**Issue by xyn-n** [ShareX/ShareX#3860]
I'm not sure if this is meant to happen or not, but I'm unable to capture in a ellipse fashion. (To elaborate, I _**CAN**_ actually capture in Ellipse, but the edges around the area are white and not transparent.)

Is this meant to happen?

**Comment by xyn-n** [comment]
> Is your image png?

Sorry for the late reply. Yes, it is PNG. 
![vv0fcibv9t](https://user-images.githubusercontent.com/29865135/50567601-c07c0f00-0d3e-11e9-8d72-0eae1ca564ce.png)

This is what it looks like in the ShareX editor, but if I actually post it anywhere (Discord, for example) the edges are white.

**Comment by Jaex** [comment]
When you copy image to clipboard it not retains transparency because it is not PNG in your clipboard.
