### ISSUE TITLE
The personal path would be reset to MyDocuments after opening Settings

### ISSUE THREAD

**Issue by OCDEngineerBoy** [ShareX/ShareX#3865]
I prefer to put the working path of ShareX outside My Documents. But after the program is restarted twice, if I open the Settings window, the personal path will be reset to MyDocuments. After restart the default path will be used again.
![sharex_dlw6vges3x](https://user-images.githubusercontent.com/39701608/50722358-2dd8c880-10ce-11e9-9f69-d900c3079963.png)

**Comment by juansvisbal** [comment]
This seems to have been posted many times and the issue keeps being closed. I am uninstalling in the meantime.
