### ISSUE TITLE
Nextcloud "use preview link" checkbox creates direct download link

### ISSUE THREAD

**Issue by kwint** [ShareX/ShareX#3868]
When I check "use preview link (nextcloud only)" shareX generates links with /download on the end, making it a direct download link. When I uncheck that option the /download part is removed, which does result in a nice preview. Checking the ownCloud 8.1+ compatibility doesn't change anything. My server runs nextcloud 14.0.4 and sharex is version 12.3.1. 

Both cases generate links with /download:
![image](https://user-images.githubusercontent.com/7907280/50860991-b76eeb80-1397-11e9-851e-f266fcd0d7c7.png)
![image](https://user-images.githubusercontent.com/7907280/50861004-c0f85380-1397-11e9-8cb7-02e33e2adfac.png)
![image](https://user-images.githubusercontent.com/7907280/50861112-07e64900-1398-11e9-9fcb-cce328f9cec9.png)

If someone can confirm that this is not something on my site I might look into fixing this myself, altough I don't have any experince in C#

**Comment by Jaex** [comment]
You need to check direct link I think.

**Comment by kwint** [comment]
Nope checking "Direct link" still returns a /download link.

I was just reading the code and think I found the "bug".
When the preview checkbox is checked it either add /preview or /download to the end of the URL. The /preview only works for images, not for other files. So when a file is not an image it automatically adds /download. So unchecking preview generates normal URLs, without /download or /preview.

So the solution for me was to uncheck the preview link options to generate preview links for files other than images. Which isn't how it's supposed to be, I think.

https://github.com/ShareX/ShareX/blob/407c644f1f5665fa81e859824d15b9bab29f0af0/ShareX.UploadersLib/FileUploaders/OwnCloud.cs#L186

**Comment by Jaex** [comment]
I have no clue about how those stuffs works, I never used NextCloud or OwnCloud before. Was blindly implemented it.
