### ISSUE TITLE
Unable to upload to Imgur

### ISSUE THREAD

**Issue by valeriluk** [ShareX/ShareX#3870]
There is mistake when I try to upload an image:

 `Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   в Newtonsoft.Json.JsonTextReader.ParseValue()
   в Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   в ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   в ShareX.WorkerTask.DoUpload(Int32 retry)`

**Comment by Zaczero** [comment]
Couldn't repeat the issue. I'm using the imgur as a default destination and it works completely fine. I guess it was a temporary server-side error as @r3538987 mentioned.

**Comment by trollmad3** [comment]
I had this issue also and just used one of the other uploaders for the time being. I don't know why people are getting problems when uploading to imgur.

**Comment by r3538987** [comment]
Okay, TLDR, email change to *@gmail.com fixed the issue. 
Don't know why this service does not like my previous mail provider.
