### ISSUE TITLE
Cannot exit capture mode

### ISSUE THREAD

**Issue by diracsbracket** [ShareX/ShareX#3873]
This just happened for a second time: I start ShareX and want to capture a region, but cannot exit the mode, and consequently cannot do anything with the computer other than restart it. ESC won't work, and pressing space, doubleclick or whatever to execute the capture and exit the mode does not work either. The only thing I can do is access the floating toolbar, but there is no option in there to force the capture to end or kill ShareX alltogether. This is highly annoying, as a hard reboot means I could lose unsaved work! (I can still start new processes, such as process explorer - to kill ShareX - but I cannot get it or any other window to the foreground because of the capture mode.
 
Has anyone else encountered this problem? Is there any other method to kill ShareX should that happen again?

**Comment by diracsbracket** [comment]
@Jaex Thank you for reacting. I wish I could reproduce it. It does not always happen. I am on Windows 10 Pro, on a Lenovo laptop (P51, with Intel Xeon and 32GB RAM) and in both instances of the problem I had a VMware VM running Debian 9.5. I also must say that I have the really bad habit of not rebooting my laptop often, but instead just fold it to put it to sleep. Also, in both cases, the capture area bounding rectangle seemed to be stuck in the resize mode (with the circle handles in the corners and halfway the sides). In a normal CTRL+PrintScreen capture, I don't get those resize handles.

Maybe the problem is a system-level side effect of this and has nothing to do with ShareX, but in any case, it would be nice to have a way to exit the capture provided in the Options menu of the capture toolbar, as that one remains functional.

**Comment by Tralexium** [comment]
I'm also having this issue but slightly differently, when I press prtsc to capture a region it works for a bit and then freezes up. After a few seconds the program just terminates on it's own without any errors or traces in the logs. This started happening to me 2 days ago after I installed a newer version of window. If I do recall correctly the "October Update", which was delayed many times. had a screen capture feature of it's own so I wonder if the OS kernel code is interfering with Sharex despite not having that feature turned on on my machine.

**Comment by timwillhack** [comment]
ctrl alt delete to bring up options like task manager.  I switch users, open task manager and kill share x from another profile.  A similar thing has happened to me where share x keeps opening multiple capture events over and over again until it uses too much ram and then crashes (itself but sometimes freaking windows)
