### ISSUE TITLE
Settings export in plain text 

### ISSUE THREAD

**Issue by TimoSta** [ShareX/ShareX#3874]
ShareX allows the export of settings to .sxb files. Those files appear to be encoded in a proprietary binary format.

I would like to back up and version my configuration using git, together with several other 'dotfiles'.

---

To do so, it would be of advantage if the **exported configuration would be in a plain text format**, for two main reasons:

- plain text files allow the user to **see changes between versions**
- plain text files allow the user to see the content, and thus to **make sure no sensitive information** (like passwords) is shared

---

Would it be feasible to offer a plain text import/export option for settings?

**Comment by Jaex** [comment]
You can open that file with any zip software. There is multiple files in it.
