### ISSUE TITLE
[Suggestion] IBM Cloud Object Storage

### ISSUE THREAD

**Issue by kot83** [ShareX/ShareX#3880]
[See here](https://www.ibm.com/cloud/object-storage)

**Comment by matthewburnett** [comment]
It appears to use a S3 subset HMAC authencation for its API, which means you should be able to configure the Amazon S3 uploader and use the IBM cloud storage endpoint.

**Comment by matthewburnett** [comment]
@kot83 I don't have an IBM account to test with, could you verify that an endpoint works and I could pr it to be included in the drop down list of endpoints.

**Comment by kot83** [comment]
Never mind, I got it to work by creating new service credentials and checking the HMAC option. This added the following lines to the configuration:
```
"cos_hmac_keys": {
    "access_key_id": "",
    "secret_access_key": ""
  },
```

**Comment by matthewburnett** [comment]
Great, if you would like, you can screenshot your S3 configuration page with that info (personal info blacked out) so I can embed it as an option in the drop down menu.

**Comment by kot83** [comment]
![screenshot](https://s3.us-east.cloud-object-storage.appdomain.cloud/larako/2019_01/ShareX_2019-01-29_20-49-20.png)

**Comment by Jaex** [comment]
Users who want to use IBM Cloud Object Storage using Amazon S3 API can find endpoints from here: https://console.bluemix.net/docs/services/cloud-object-storage/basics/endpoints.html
