### ISSUE TITLE
[Request] Focus an area (inverse blur)

### ISSUE THREAD

**Issue by RadGH** [ShareX/ShareX#3885]
I've used ShareX for awhile and the image editor is very similar to Greenshot. But there is one feature I really miss. I forget what it was actually named, but it was basically the opposite of the current blur tool. Instead of blurring the rectangle you selected, everything else gets blurred / darkened.

If this tool were added it could go next to "Highlight" because it serves the same purpose, it just looks different.

![05-editor-highlighting-area](https://user-images.githubusercontent.com/2008464/51282579-4bdddd00-199a-11e9-8611-f28299174726.png)

**Comment by loliprotector** [comment]
I definitely would find this useful

**Comment by L1Q** [comment]
You do it by blurring the entire image and then using Image from screen on the area you need to have sharp

**Comment by RadGH** [comment]
How do you do "Image from screen" within the screenshot interface? I'm not looking to add too many steps to accomplish this. It would be  perfect as a single button, might not be worth the trouble if I have to blur, then un-blur another area. And the darkening effect is also necessary in some cases otherwise you have to hunt for the part that is not blurred.

**Comment by Jaex** [comment]
Duplicate of https://github.com/ShareX/ShareX/issues/3041

**Comment by RadGH** [comment]
I just saw @Jaex posted a new "Spotlight" feature on twitter that is basically exactly what I described: https://x.com/ShareX/status/1972233757844525370 (source [here](https://github.com/ShareX/ShareX/issues/3041#issuecomment-3343086054))

Awesome! Thanks! Just wanted to leave that link in case anyone else lands here wondering about it.
