### ISSUE TITLE
"Last vertical" adjustment only works with the last image.

### ISSUE THREAD

**Issue by hizamakura** [ShareX/ShareX#3888]
In Scrolling Capture, the "Last Vertical" adjustment option will not work unless it is the very last image, even if you changed the amount of images by using the "Remove Last" option. It should adjust the current last image when you try to remove some images, as how it implies.
![Image](https://thighs.are-pretty.sexy/add2e3.gif)

**Comment by mateherber** [comment]
This still happens in latest version

**Comment by supra107** [comment]
Still happens in 13.7, meaning that when you inevitably take too many screenshots at the end you cannot properly adjust the final vertical alignment as it's being applied to an unwanted image that's been excluded by the "Remove Last" option. It should be reopened as it essentially forces users to do the final alignment manually in other software.

**Comment by rakosi2** [comment]
@mateherber Could you reopen this as I also am having this issue with 14.1
