### ISSUE TITLE
Asks twice to confirm overwrite of 'save as' file

### ISSUE THREAD

**Issue by hbruun** [ShareX/ShareX#3889]
It asks twice if you want to save captured image as a file that already exists.

steps to reproduce.. capture region, 'save as', enter filename that already exists. It then asks twice if you want to overwrite the file.

**Comment by Jaex** [comment]
https://devblogs.microsoft.com/dotnet/net-framework-march-1-2019-cumulative-update-for-windows-10-version-1809-and-windows-server-2019/

> Additionally, it addresses a double prompt for file save dialogue and folder browser dialogue.
