### ISSUE TITLE
Imgur delete support

### ISSUE THREAD

**Issue by LukeHandle** [ShareX/ShareX#389]
When uploading to imgur, you get a "deletehash" in the response. As per https://api.imgur.com/endpoints/image you can delete a remote image using that hash (anonymous upload) or with authentication.

Right-clicking and "Delete from Web" or something like that would be nice when clicking on the uploaded version in the ShareX list.

**Comment by Efreak** [comment]
@Jaex: Any chance of just adding a shortcut in the menu to open that url in the browser? This would be far more convenient for those of us that have to actually look up the url for it every time we want to delete something.

It doesn't help that [double-clicking the hash to select the word selects a whole bunch of other text as well](http://i.imgur.com/QMHtI5e.png).

**Comment by Jaex** [comment]
@Efreak there is already Open -> Deletion URL button.

**Comment by Efreak** [comment]
@Jaex Feel free to pretend I didn't ask that...I have no idea how I missed it.
:frowning: :anguished:

**Comment by techpulse** [comment]
Where does it store deletion URL's?

**Comment by Jaex** [comment]
In history window.

**Comment by MrGoatsy** [comment]
How can I disconnect the imgur API from ShareX? I can't find the API settings anymore.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/ShareX.vshost_hV90OZvui2.png)

**Comment by MrGoatsy** [comment]
Where can I find that menu?

**Comment by Jaex** [comment]
In main window destinations menu.

**Comment by MrGoatsy** [comment]
Thanks.

**Comment by WiliTest** [comment]
if nothing happens : check the path of your browser in application settings/ advance (in  my case the path was pointing to an empty folder, the remains of an old Firefox installation)

**Comment by satyashr** [comment]
I love the ShareX application and have been recommending it to my colleagues. Keep up the good work team.

I think straight out "Delete from IMGUR direclty" rather than having to open a link and click on Yes Remove from Imgur in Imgur site, as a Menu Item seems to be a reasonable request. 

Also having Delete URL under Open menu item is bit confusing, Can we not have it on the first level of the Menu like "Delete URL"

**Comment by takase1121** [comment]
I think this option is still relevant. Some API requires a lot more to delete files, such as tokens and other types of requests. These are impossible to do with browsers.

**Comment by BoltPow3r** [comment]
@Jaex Could we at least get an option to select more than one image at a time and then open a whole bunch of deletion URLs at once? Would make the proccess much faster. Thank you for the consideration
