### ISSUE TITLE
black screen in windowed borderless (overwatch)

### ISSUE THREAD

**Issue by faluren** [ShareX/ShareX#3896]
hello!

recently (as of ~2 weeks ago) sharex has started blackscreening when i try to screenshot overwatch (windowed borderless). i can't figure out why it suddenly stopped working. i've looked through the other threads and i haven't changed new antiviruses, and apparently only fullscreen has an issue (ironically, i can screenshot in fullscreen but not windowed borderless). it works outside of this specific program.

anyone have any suggestions as to what settings to check where to try and fix the problem?

thank you

**Comment by KiraSokolov** [comment]
same problem

**Comment by paz** [comment]
im having this issue too, but its probably battleeye
