### ISSUE TITLE
Can you guys make it so it says Screenshot 1 and then 2 and so on it will make my life easier

### ISSUE THREAD

**Issue by Shortyxd** [ShareX/ShareX#3898]
i have almost 10k screenshots on my pc so it would help out

**Comment by xangelix** [comment]
*This menu can be found under "Task settings..." or can be overridden on a per-hotkey basis.*

To achieve what you are asking, for normal "Capture region"s simply change the name pattern for capture or clipboard upload to: ```Screenshot %i```

**Also:**
You can pad it by adding {<# digits>} after the %i incrementer along with some other options you can see here:

Example: ```Screenshot %i{3}```
Would give: ```Screenshot 001```, ```Screenshot 002```, etc.

Hopefully this answers your question! 😄 

![Changing filenames](https://user-images.githubusercontent.com/16216097/51446021-08f17180-1cda-11e9-8bbe-c4af253e3d49.png)
