### ISSUE TITLE
Run sharex when windows start with run as admin not working

### ISSUE THREAD

**Issue by Jfamig** [ShareX/ShareX#3908]
I have been pulling my hair out trying to get sharex to work on applications that have to be run as admin by setting it as admin, but sharex won't start with windows when I force it to run as admin all the time. my UAC is disabled and has been because that just how I prefer it. 

- Start sharex with windows is checked in the options
- Sharex is in shell:startup
- Sharex is in shell:common startup
- I tried the "making a task instead (run in cmd/powershell)" method from https://github.com/ShareX/ShareX/issues/94#issuecomment-39364108 this comment
- Sharex is enabled to start automatically in task manager

Please for the love of god, someone help me out here. 
I NEED sharex to run as admin
I NEED sharex to automatically start with windows
Thank you

**Comment by Abu3safeer** [comment]
Excuse me, but why do need it to run as admin? 
It works properly with me without any admin privileges.

**Comment by Zaczero** [comment]
Run *Task Scheduler* (search in start for it - it's windows system app).

![](https://i.imgur.com/ntvaIa9.png)

Then create a task with the highest privileges. It should do the job. You can leave UAC enabled and it won't show you a pop-up on the startup which is nice about it!

**Comment by Jfamig** [comment]
@Abu3safeer 
> Excuse me, but why do need it to run as admin?
> It works properly with me without any admin privileges.

I require Sharex to run as admin so the screenshot hotkey will work on programs that must be run in admin themselves. When you run sharex _below_ admin and desire to take a screenshot of a program that _requires_ admin privileges to run, the hotkey will not work. Sharex _must also_ be run as admin.

@Zaczero 
Thank you very much! The cmd/powershell command I ran scheduled the program to run at the wrong file destination. I didn't realize I could just use Task Scheduler. It works now!

**Comment by Abu3safeer** [comment]
> I require Sharex to run as admin so the screenshot hotkey will work on programs that must be run in admin themselves. When you run sharex _below_ admin and desire to take a screenshot of a program that _requires_ admin privileges to run, the hotkey will not work. Sharex _must also_ be run as admin.

I was wondering why ShareX does not work with some apps, now I understand why.
Thank you.

**Comment by Venryx** [comment]
I finally figured out the full explanation for why some hotkeys get blocked on certain windows (when ShareX is run non-elevated). See here for details: https://github.com/ShareX/ShareX/issues/334#issuecomment-610259444

Short version: Windows blocks hotkeys when an elevated/admin window is focused, **and** the hotkey in question does not include any modifier keys.

I've long known the first part of that condition, but the second part I just found out a few minutes ago.

It's a bit annoying, but I understand it for security reasons, and it means there is now a workaround: just make sure to include a modifier key in all of your hotkeys. (admittedly, this isn't quite as nice as being able to just hit the one-key "print screen" button, but it's better than the annoyance of the hotkey sometimes not-working/requiring-focusing-a-different-window)

**Comment by Rings4** [comment]
> I finally figured out the full explanation why some hotkeys get blocked on certain windows (when ShareX isn't run as admin/elevated). See here for details: [#334 (comment)](https://github.com/ShareX/ShareX/issues/334#issuecomment-610259444)
> 
> **Short explanation**: For non-elevated ShareX, Windows blocks hotkeys when an elevated window is focused, **and** the hotkey in question does not include any modifier keys.
> 
> **Short solution**: Include at least one modifier key in all of your hotkeys.

Sorry for the necro, but this isn't the case. My region capture hotkey shift+printscreen does not work. However, my program capture hotkey alt+printscreen works. I think it depends on what function the hotkey is calling.

Either that, or for some incredible reason, Sharex accepts the alt hotkey but not the shift hotkey for admin programs.

I'll be running Sharex as admin via the task scheduler from now on.
