### ISSUE TITLE
Ошибка при загрузке картинки на imageshack

### ISSUE THREAD

**Issue by BodyDub** [ShareX/ShareX#3909]
При загрузке картинок на сервер получаю следующую ошибку: http://imageshack.com/f/pnhyMKjdj
Но при этом, сами картинки на сервер загружаются. Получается, что ShareX не получает ссылку от сервиса. http://imageshack.com/f/pnZorz8Yj

**Comment by MustangChris04** [comment]
I have been experiencing the same 404 error from imageshack since Monday of this week. The image gets uploaded to imageshack and shows on my profile, but the URL does not get generated. This is hindering my workflow. Imageshack is useless because I emailed them on Monday and they did not answer.

**Comment by BodyDub** [comment]
> При загрузке картинок на сервер получаю следующую ошибку: http://imageshack.com/f/pnhyMKjdj
> Но при этом, сами картинки на сервер загружаются. Получается, что ShareX не получает ссылку от сервиса. http://imageshack.com/f/pnZorz8Yj
