### ISSUE TITLE
FTPS does not work with TLSv1.2

### ISSUE THREAD

**Issue by MLWALK3R** [ShareX/ShareX#391]
FTPs needs TLSv1.2 support, SSLv3 is no longer a secure.

System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The supplied message is incomplete. The signature was not verified
   --- End of inner exception stack trace ---
   at System.Net.FtpClient.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts)
   at System.Net.FtpClient.FtpClient.Connect()
   at UploadersLib.FileUploaders.FTP.Connect()
   at UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

**Comment by MLWALK3R** [comment]
BTW Jaex there was an update on this: https://netftp.codeplex.com/workitem/388

**Comment by Jaex** [comment]
Changed code for targeting .net framework 4.5 (VS2012 framework 4.5)

ShareX not using 4.5

**Comment by k0nsl** [comment]
When is this expected to be resolved? I have the same issue.

**Comment by Jaex** [comment]
ShareX using this FTP library https://netftp.codeplex.com/ and problem is not to do with ShareX codes. So I can't help about it.

**Comment by k0nsl** [comment]
@Jaex 
That project was last updated in 2014 :(

**Comment by vavavr00m** [comment]
Can't use another library?

https://github.com/bagder/curl
https://github.com/masroore/CurlSharp

**Comment by Jaex** [comment]
Previous FTP library we were using was more outdated than it :(
This was most up to date and good one I can find.

**Comment by k0nsl** [comment]
The first suggestion looks like it would work; the other one doesn't
seem actively developed. At any rate, the current library is worthless
for explicit FTP (TLS).

vavavr00m skrev den 7/9/2015 12:01 PM:
>
> Can't use another library?
>
> https://github.com/bagder/curl
> https://github.com/masroore/CurlSharp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShareX/ShareX/issues/391#issuecomment-119895776>.
>

-- 
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination, distribution,
copying or the taking of any action in reliance on the information
herein is prohibited.
