### ISSUE TITLE
12.3.1 custom uploader stopped working

### ISSUE THREAD

**Issue by xaviergmail** [ShareX/ShareX#3912]
After upgrading to 12.3.1 from 12.2.0, my custom uploader with the following settings has stopped working.
I get a login error from my server which means my api key / username combo don't match. Both of these are passed as query string.

 It seems request arguments aren't passed properly (? can't confirm yet)

![](https://xavie.ru/i/rsOx7e.png)

**Comment by Jaex** [comment]
If any fields contains $ or \ then you must add \ behind them to escape them.

**Comment by xaviergmail** [comment]
👍 That does it! I had two `$` with some stuff inbetween them in one of the arguments. Thank you.

Although I think some form of input linting should be done to notify the user of a malformed argument (or whatever's happening here)

**Comment by Jaex** [comment]
I already added syntax highlighting for text boxes but listview not supports multi colored text so can't do it.

**Comment by xaviergmail** [comment]
That's pretty nice. Perhaps you could instead make the listview item's background color change to red along with some hover tooltip? In my case I just pasted a 60+ char access token a few years ago and I would've never thought about this!
