### ISSUE TITLE
Feature request: Able to auto delete uploads after a while

### ISSUE THREAD

**Issue by mailinglists35** [ShareX/ShareX#3919]
I have uploaded tons of useless stuff.
Most of the time the link is useful to me for one day - one week but rarely more than that, but due to laziness and zero cost to upload, I never delete them.

I would highly appreciate an option inside the upload window like this:

![image](https://user-images.githubusercontent.com/2054302/51920574-5b274680-23ee-11e9-92d0-838ee94654ef.png)

**Comment by mailinglists35** [comment]
Or if it's too complicated, have the time interval setup in application settings, then just a checkbox in the upload window.

**Comment by mailinglists35** [comment]
When I say "interval", I mean time since upload, not interval of periodic task runs of deletions. That could be something internal not user accessible like 1 minute or 1 hour

**Comment by vatterspun** [comment]
I know lots of image hosting services would appreciate more people deleting images they know aren't useful after given time frame.

Maybe "[X] Add expiration date" checkbox with a note "(ShareX must be running)".

**Comment by mailinglists35** [comment]
this is still a missing feature

**Comment by vatterspun** [comment]
> this is still a missing feature

Most of the issues that go stale here on github are essentially "wontfix".  Maybe Jaex and team will come back to it.

**Comment by mailinglists35** [comment]
please reopen. it would still be a very useful feature. still manually deleting.

**Comment by mailinglists35** [comment]
@Jaex
