### ISSUE TITLE
One thing more I would like from ShareX

### ISSUE THREAD

**Issue by Seawolfgb** [ShareX/ShareX#3926]
Hi. The one thing I would like to see in ShareX is the ability to "Save As" an .ico file to create easy icons! Thanks

**Comment by sylveon** [comment]
To look good at all resolutions, an .ico file should have the following sizes stored (all in 32-bits color):
- 256x256 (with PNG compression)
- 128x128
- 64x64
- 48x48
- 32x32
- 24x24
- 16x16

**Comment by sylveon** [comment]
From [this list](https://docs.microsoft.com/fr-fr/windows/desktop/uxguide/vis-icons#size-requirements), the following sizes would also be desired:
- 20x20
- 40x40
