### ISSUE TITLE
Make ShareX Stop uploading after 50 Files to Imgur, and then continue when available. 

### ISSUE THREAD

**Issue by Kristijan1001** [ShareX/ShareX#3928]
After 50 Files imgur doesn't allow to upload anymore. So you have to reset your ip and upload 50 more and so on. The problem is i can't que 500 Pictures, but i have to manually add 50 by 50 each time because ShareX doesn't stop when it says error occurred it just keeps going and errors on each file and there is no way to pause it or reset it without clearing the whole list then adding it again to upload. It would be nice if ShareX had an option when it does encounter this error, it puts in a Cooldown For Example: Retrying in 3 minutes, by that time you would be able to reset and keep going, instead of the whole thing going and failing on single file and forcing you to clear the list.

If this kind of feature is already available and i am blind please point it out, thank you.

**Comment by vatterspun** [comment]
As Jaex might consider this functionality out of scope, you might consider another image hosting site for large numbers of images other than Imgur.  Google for example boasts unlimited image storage and probably wouldn't hesitate to take over 50 images.
