### ISSUE TITLE
How to open Drag and drop upload with a hotkey.

### ISSUE THREAD

**Issue by cagross** [ShareX/ShareX#3931]
If I open ShareX, click Upload, then click "Drag and drop upload..." a small blue box appears in the bottom right corner of my screen ([screenshots](https://imgur.com/a/L6W5A0g)).  Is there a way to get this box to display by using a hotkey, instead of opening Sharex and clicking Upload-->"Drag and drop upload..."?

Alternatively, is there a way to select one (or more) files in Windows Explorer, and send them to ShareX's "Drag and drop upload" feature?

Thanks.

**Comment by Jaex** [comment]
You can create hotkey:

![](https://jaex.getsharex.com/2019/02/ShareX_kHMxgG21d1.png)

For explorer why don't you use this option:

![](https://jaex.getsharex.com/2019/02/ShareX_yLJo7VBH7t.png)

**Comment by cagross** [comment]
OK thanks. Adding 'Upload with ShareX' to the Win Explorer context menu is actually closer to what I'd like.  I did so, and uploaded one file as a test.  It uploaded.  But in doing so, it opened the ShareX application, and after the upload, the ShareX application remained open on my computer.  Is there a way to ensure that after the upload, the application minimizes to the systray?
