### ISSUE TITLE
Add option to color picker to get the color as float

### ISSUE THREAD

**Issue by DrummerB** [ShareX/ShareX#3933]
Lots of APIs or tools use float values for RGB colors. It would be nice to be able to copy the color as float from the color picker.

E.g. instead of `92, 133, 233` I would prefer `0.36, 0.52, 0.91`

**Comment by dnnp2011** [comment]
I would also like to be able to copy colors as floats that are compatible with Unity color object.
Alternatively, a way to create custom color copy outputs would be helpful.
