### ISSUE TITLE
Customizable color picker format

### ISSUE THREAD

**Issue by DrummerB** [ShareX/ShareX#3934]
It would be useful to be able to define custom export formats for the Color Picker tool, similar to the Screen Color Picker tool.

E.g. you could define export format that could be pasted directly into source code:

Format: `new Color($.3rf, $.3gf, $.3bf)` 
Example output: `new Color(0.123f, 0.456f, 0.789f)`

Format: `UIColor(red: $.2r, green: $.2g, blue: $.2b, alpha: $.2a)` 
Example output: `UIColor(red: 0.10, green: 0.25, blue: 0.50, alpha: 1.00)`

![image](https://user-images.githubusercontent.com/2104474/52209997-ec326d80-2885-11e9-8294-a8135881b78f.png)

**Comment by FirstDagger** [comment]
This would be very useful _even if_ only an additional option for copy the hex value into the clipboard was available. Currently this is a deficiency of ShareXs IMHO.

**Comment by Jaex** [comment]
Implemented in #5072
