### ISSUE TITLE
Refresh album list doesn't work for Google Photos new dev build 12.4

### ISSUE THREAD

**Issue by Ramadas108** [ShareX/ShareX#3937]
Refresh album list doesn't work for Google Photos new dev build 12.4

![2019-02-05_18-33-36](https://user-images.githubusercontent.com/46054140/52292244-94befb00-2974-11e9-93d4-62a73f921f5f.png)

**Comment by lucario** [comment]
It only shows albums sharex owns. You must create an album in sharex first.

**Comment by Ramadas108** [comment]
Ok, thanks! Solved then.
