### ISSUE TITLE
Feature Request: add "show cursor in screenshots" & "image format" hotkey/shortcut.

### ISSUE THREAD

**Issue by ImSpecial** [ShareX/ShareX#3939]
Requesting a QoL feature I'd love to see added to ShareX.

The two options [show cursor in screenshots](https://i.imgur.com/S1QYHwu.png) & [Image Format](https://i.imgur.com/4I5ji6r.png), could these be added to these two windows as a checkbox/dropdown for easier toggling?

[ Auto Cature](https://i.imgur.com/6zGgDkg.png) & [Action Toolbar](https://i.imgur.com/V4lfOFf.png)

**Comment by Jaex** [comment]
Show cursor already have shortcut in tray menu:

![](https://jaex.getsharex.com/2019/02/chrome_rRCS9wpWaN.png)

**Comment by ImSpecial** [comment]
Damn I missed that, well this kinda solves my issue...
