### ISSUE TITLE
Request : Custom Toast location 

### ISSUE THREAD

**Issue by Aceship** [ShareX/ShareX#3941]
Is there any feature of custom toast location ?
currently i have multiple screen, and i wanna move the toast to the least used area, especially the main screen is used for gaming

**Comment by Jaex** [comment]
Only this:

![](https://jaex.getsharex.com/2019/02/ShareX_1AJgQFgmUO.png)

**Comment by Aceship** [comment]
is it all still in main monitor ?
i kinda want it on other monitor, or at least i still want to see the preview while screenshot the main screen repeatly, without having toast window in the screenshot

**Comment by Jaex** [comment]
You can disable toast window as workaround.
