### ISSUE TITLE
Custom Uploader: Allow using HTTP DELETE (RESTful, WebDav) for DeletionURL

### ISSUE THREAD

**Issue by sinni800** [ShareX/ShareX#3943]
This would necessiate also being able to set the headers for the deletion request (namely Authorization). 

It would further simplify using your own file server as your ShareX target, as these standard HTTP commands are supported by every WebDav server as-is

**Comment by Jaex** [comment]
Replied in https://github.com/ShareX/ShareX/issues/2299#issuecomment-464227489
