### ISSUE TITLE
Google Photos - Remote Server returned error 400 bad request

### ISSUE THREAD

**Issue by Chocobubba** [ShareX/ShareX#3945]
Until Recently Google Photos has been working as a destination, but now no matter what I do, i get the error in the title.

I've already made sure to be on the latest version (12.3.1), I double-checked my authorization, and even tried signing out and back in to no avail. While I'm logged in, it refuses to upload.

Also, even though i'm signed in seemingly successfully I can't view my album list at all.

**Comment by Jaex** [comment]
Duplicate of #3884
