### ISSUE TITLE
[Feature Suggestion] Hotkey task: open menu

### ISSUE THREAD

**Issue by Sasha-Sorokin** [ShareX/ShareX#3949]
**Suggestion**: Task to open menu the same as when you right click icon in the tray.

**Why this should be a feature?**

I frequently don't want to open taskbar, go into tray, right click ShareX and then open taskbar again, and repeat right clicking until the menu finally opens (that is incompatibility with [Buttery Taskbar](https://github.com/CrypticButter/ButteryTaskbar)) 😴

I do not ask to fix the incompatibility because I think Buttery Taskbar uses some dirty Windows API hack, but instead I would really appreciate the task for the hotkey that opens the same quick menu with all the utilities nearby your current cursor position (so you don't have to move your mouse through all your desktop as with the case of <kbd>Win</kbd>+<kbd>X</kbd> (that is the same as right clicking Start menu)).

Thanks! ❤️

**Comment by vatterspun** [comment]
Little confused here.  So currently when you right-click on the ShareX tray icon, it doesn't open properly and you want a hotkey to open said tray?

**Comment by Sasha-Sorokin** [comment]
Exactly. When I click on it, the task bar menu getting hidden and the menu from ShareX does not come up. So hotkey that opens this menu near the current cursor position would be a great workaround
