### ISSUE TITLE
ShareX Auto Increment is incrementing by 2 instead of 1.

### ISSUE THREAD

**Issue by aj123gamer** [ShareX/ShareX#3951]
Hello, I am new to ShareX. I have been trying to make the increment work correctly.

Whenever I save a screenshot. It increments the file number by 2 instead of 1.

For example:

First Screenshot: screenshotx_2.png
Second Screenshot: screenshotx_4.png
Third Screenshot: screenshotx_6.png

How can I make it this way:

First Screenshot: screenshotx_1.png
Second Screenshot: screenshotx_2.png
Third Screenshot: screenshotx_3.png

Thanks.

Screenshot of the File Name Increment Settings: https://i.imgur.com/irakErP.png

**Comment by Jaex** [comment]
What is your after capture tasks settings?

**Comment by Jaex** [comment]
Because with this options I can't reproduce it:

![](https://jaex.getsharex.com/2019/02/rvLHMKQYhi.png)
