### ISSUE TITLE
Arrow key region resizing is slow on 4k screen

### ISSUE THREAD

**Issue by Fealthas** [ShareX/ShareX#3953]
It seems that the shift+arrow keys moves the region by a hard coded number of pixels (10), which is fine on a 1080p display, but it would be equivalent to shifting 1/4th the percent of screen on a 4k display, and so is quite slow.

Proposal:
Allow user to set the number of pixels moved by the shift+arrow binding, or hard-code it to be larger when 4k is detected.

**Comment by lanes100** [comment]
bump
