### ISSUE TITLE
Issue with dev build installer

### ISSUE THREAD

**Issue by s-malik** [ShareX/ShareX#3954]
I have the latest dev build on my system. When I check for a dev build update, it offers to download the same build installer.

![sharex_1](https://user-images.githubusercontent.com/46628021/52820385-78f0de80-3071-11e9-8b6a-a65ae93f0b8b.png)

![sharex_2](https://user-images.githubusercontent.com/46628021/52820394-7db59280-3071-11e9-91cb-5644cb380071.png)

**Comment by Jaex** [comment]
Dev builds have same versions as yours because I don't increase version each commit. That version I showed there is AppVeyor build number. So there is no real auto update system for dev builds, I just used same dialogs to make it easier to dl dev builds.
