### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by SuperSandro2000** [ShareX/ShareX#3955]
Add support for short.cm api ref https://short.cm/api#/reference/0/link-api/create-a-new-url .
This api currently can't be used with custom uploaders cause the service requires a body.

**Comment by Jaex** [comment]
Custom uploader supports body types in dev build if you would like to try it: https://getsharex.com/docs/dev-builds

So in next version it gonna be possible to use that service with custom uploader system.

**Comment by SuperSandro2000** [comment]
Nice! Thx.

**Comment by Jaex** [comment]
Custom uploader of it: https://github.com/ShareX/CustomUploaders/blob/master/short.cm.sxcu
