### ISSUE TITLE
Backblaze not finding bucket ID

### ISSUE THREAD

**Issue by boboben1** [ShareX/ShareX#3958]
> 2019-02-18 13:37:19.063 - B2 uploader: Attempting to authorize as '[CENSORED]'.
> 2019-02-18 13:37:19.433 - B2 uploader: Authorized, using API server https://api002.backblazeb2.com, download URL https://f002.backblazeb2.com
> 2019-02-18 13:37:19.433 - B2 uploader: Key doesn't have a bucket ID set, so I'm looking for a bucket ID.
> 2019-02-18 13:37:19.805 - B2 uploader: Checking clientside whether we have permission to upload.
> 2019-02-18 13:37:19.805 - B2 uploader: Upload attempt 1 of 5. New URL.
> 2019-02-18 13:37:19.805 - B2 uploader: Getting new upload URL.
> 2019-02-18 13:37:19.889 - B2 uploader: ParseB2Error() got: {
>   "code": "bad_request",
>   "message": "required field bucketId cannot be null",
>   "status": 400
> }
> 2019-02-18 13:37:19.889 - B2 uploader: Got error trying to get upload URL.
> 2019-02-18 13:37:19.889 - Task failed. Filename: files.zip, Errors:
> Could not get B2 upload URL: Got status 400 (bad_request): required field bucketId cannot be null

Steps to reproduce:

1. Create new application key for all buckets with proper permissions.
2. Add to ShareX. Fill in `Bucket Name` field appropriately.
3. Attempt to upload a file.

**Comment by xspoco** [comment]
The same issue

**Comment by xspoco** [comment]
@tinybarks

**Comment by writingpoli** [comment]
Same issue.

**Comment by itfanr** [comment]
Same issue.

**Comment by Enlight432** [comment]
The same issue
