### ISSUE TITLE
Filenames saved to disk

### ISSUE THREAD

**Issue by Gedili** [ShareX/ShareX#3960]
Hello, nice tool, very handy, thanks for the work!
I recently updated to the latest version, and noticed the pattern of filenames have changed (those saved on the disk, I don't use the upload features). It used to be like chrome_2018-10-16_13-38-41.png, now instead of date and incremental number, it gets a random string, for instance chrome_UwFTuf1tve.png

It was more pratical with the older naming convention, is there any way to set this? (I've looked at all the options in the settings menu, couldn't find one to change this)

**Comment by Jaex** [comment]
In this window:

![](https://jaex.getsharex.com/2019/02/ShareX_pbL17TYfMw.png)

Use this pattern: `%pn_%y-%mo-%d_%h-%mi-%s`

**Comment by Gedili** [comment]
I had seen that option on an other issue thread, however it doesn't appear for me
![image](https://user-images.githubusercontent.com/45516124/53093086-3148d780-34f5-11e9-9e62-133529021c37.png)
I'm using the lasted official build on Win 10
![image](https://user-images.githubusercontent.com/45516124/53093177-7836cd00-34f5-11e9-9599-88a965b5e6b6.png)

**Comment by Gedili** [comment]
Oh, ignore the last message, I just realized there was a Task Setting menu too (I was in the application setting...). Thanks for the help !
