### ISSUE TITLE
Why does my custom hotkey config fail to capture to clipboard?

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#3965]
Here it is:

![image](https://user-images.githubusercontent.com/6157073/53258568-d9f96180-36c4-11e9-9c43-0b0416bf6ee4.png)

![image](https://user-images.githubusercontent.com/6157073/53258530-bfbf8380-36c4-11e9-9d22-c75b3851bf57.png)

The capture appears to happen, except nothing appears on the clipboard. The standard hotkey captures to clipboard fine.

**Comment by Jaex** [comment]
You selected "Copy file to clipboard" but didn't "Save image to file" so there is nothing to copy. Maybe you wanted to select "Copy image to clipboard" instead.

**Comment by chrisjj** [comment]
Duh! Stupid me. I settled for 

![image](https://user-images.githubusercontent.com/6157073/53261563-42980c80-36cc-11e9-86dd-fbf17e8e42bd.png)

which works great. Thanks. Expect another donation.

PS Is there a better place for such questions?

**Comment by Jaex** [comment]
You can ask questions in our Discord server.
