### ISSUE TITLE
Changelog has incorrect version

### ISSUE THREAD

**Issue by bgopalakrishnan1986** [ShareX/ShareX#3971]
Hi Team,

The latest changelog does not reflect the correct version number 12.4.1 instead it shows pre-release version number 12.4.0

https://getsharex.com/changelog/#sharex-1240---2019-02-20

Thanks,
Gopal

**Comment by Jaex** [comment]
It is on purpose because 12.4.1 only have slight bug fix, not any new features. Otherwise people gonna think that new update don't have any new features. So only 12.4.0 changelog is matters to users.

**Comment by bgopalakrishnan1986** [comment]
Thanks.
