### ISSUE TITLE
File naming is disabled

### ISSUE THREAD

**Issue by khashashin** [ShareX/ShareX#3972]
![image](https://user-images.githubusercontent.com/17837758/53303309-31d0cd80-3869-11e9-9629-1a2115b38f24.png)

Inside custom Task settings I wasn't able to change the name pattern. I'll to create different tasks and each Task will save the screenshot in different name format. I have removed the whole name from "General" task settings but this didn't help. Is the a bug?

**Comment by Jaex** [comment]
Click Upload tab and check override option.

**Comment by khashashin** [comment]
![image](https://user-images.githubusercontent.com/17837758/53303356-b6bbe700-3869-11e9-8290-48a2448f7bc6.png)
Ooops didn't notice that. Thanks!
