### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by juzand** [ShareX/ShareX#3976]
After not using shareX for many months I get this error. Program wont start. pls help. already verified integrity of files and deinstalled and reinstalled. same error happening.

Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.SettingManager.ApplicationConfigBackwardCompatibilityTasks()
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 12.4.1 (Steam)

error happens after loading ApplicationConfig.json

**Comment by Jaex** [comment]
`Documents\ShareX\ApplicationConfig.json`
`Documents\ShareX\Backup\ApplicationConfig.json`
Remove these two files.

**Comment by NotebookPaper** [comment]
Getting this error now also.
Have uninstalled and re-installed.
-------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.SettingManager.ApplicationConfigBackwardCompatibilityTasks()
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 12.4.1 (Release)

**Comment by Jaex** [comment]
Which version was installed before?

**Comment by NotebookPaper** [comment]
"ApplicationVersion": "12.3.1"

Also, windows user account was migrated right before this started to occur.  

"The computer will enter the migration phase silently and become sluggish while it moves your user profile from John.Doe to Doe12345. This will cause another reboot."

**Comment by Jaex** [comment]
If you upgraded from 12.3.1 then it don't even have any backward compatibility codes there.

**Comment by click4dylan** [comment]
I have the same issue, upgraded from version 11.1

**Comment by MiniOranges** [comment]
Getting the same problem after 2 days ago. Tried uninstalling, reinstalling, deleting config files etc. It just won't open and no log files ever get made.
