### ISSUE TITLE
Font setting not correct on quick menu

### ISSUE THREAD

**Issue by bluelovers** [ShareX/ShareX#3979]
Actual

![image](https://user-images.githubusercontent.com/167966/53468548-a4be8c00-3a95-11e9-84c8-03a856c54a99.png)

Expected

![image](https://user-images.githubusercontent.com/167966/53468584-c28bf100-3a95-11e9-86b3-51a72a7b0e8b.png)

**Comment by Jaex** [comment]
I don't see anything wrong, it using Arial font correctly.

**Comment by bluelovers** [comment]
pic1 font should look same as pic 2 ( size and style )

**Comment by Jaex** [comment]
Why should it look same?

**Comment by bluelovers** [comment]
![C0I8E5tH2m](https://user-images.githubusercontent.com/167966/54282488-12f76880-45d7-11e9-9c9e-58875053bc06.png)
