### ISSUE TITLE
Delay when selecting with pen

### ISSUE THREAD

**Issue by Somethingweirdhere** [ShareX/ShareX#3981]
Similar to #3925 

When I make a screenshot of an area, and try to select the area, then whenever I do it with a pen, there is a short time-delay between the touchdown and the actual selection. Same goes for drawing later on, but the seleciton-part was never mentioned. Is there any way I can help to find the cause?

**Comment by einarmagnus** [comment]
I'm having this same issue with a pen on a surface pro
