### ISSUE TITLE
URL is empty

### ISSUE THREAD

**Issue by artfabrique** [ShareX/ShareX#3982]
Custom uploader worked until the update.
### Params
**Request**
Method: PUT
URL: https://monosnap.crazypanda.ru/monosnap/$filename$
Body: Binary
**Response**
URL: https://service.crazypanda.ru/v/monosnap/$filename$ (notice that it's different then PUT url)

The requirement is to format filename, otherwise, the server will return 403 error.
%y-%mo-%d-%h-%mi-%s-%ra{5}

You can test it.
Basically, it has to mock the way Monosnap uploads images. It worked before the update.
Now it gives me **"URL is empty"** and no other errors in the debug log.

**Comment by Jaex** [comment]
That nginx server returns 403 forbidden error which is mainly to do with authorization problem. So not looks like to do with ShareX.

**Comment by artfabrique** [comment]
> That nginx server returns 403 forbidden error which is mainly to do with authorization problem. So not looks like to do with ShareX.
Hi!
It's for security reasons. Please read above - you have to provide a valid filename matching with a pattern:
%y-%mo-%d-%h-%mi-%s-%ra{5}

it's working with Monosnap and prev version on ShareX right now.

**Comment by Jaex** [comment]
I see now, problem happens because when parsing response to generate URL, it check is response text is empty. Because your host returns empty response, it not tries to generate result URL.

I asked in here for you guys to test final version: https://github.com/ShareX/ShareX/issues/2299#issuecomment-464225861

If you did this could be avoided.

**Comment by artfabrique** [comment]
> I see now, problem happens because when parsing response to generate URL, it check is response text is empty. Because your host returns empty response, it not tries to generate result URL.
> 
> I asked in here for you guys to test final version: [#2299 (comment)](https://github.com/ShareX/ShareX/issues/2299#issuecomment-464225861)
> 
> If you did before this could be avoided.

Oh! Sorry. It completely slipped out of my mind. I was planning to ask our office admin to create a silent installer with embedded config for a couple of the volunteered colleagues. But it all stopped at some point.
So... does this empty response is a regular thing? I guess we will have to leave the "empty response" because at the office somebody uses Clip2Net, somebody Monosnap etc (all mapped to our media server)

**Comment by Jaex** [comment]
Yes empty response is valid thing. So I will fix it.

**Comment by artfabrique** [comment]
> Yes empty response is valid thing. So I will fix it.

Thank you!

**Comment by Jaex** [comment]
You can test the fix with dev build.

**Comment by artfabrique** [comment]
> You can test the fix with dev build.

It seems to work now!
