### ISSUE TITLE
Picasa API Still not functioning properly 

### ISSUE THREAD

**Issue by bajungadustin** [ShareX/ShareX#3984]
[Example Error](https://photos.google.com/lr/photo/AGQQmEtjDCeeIKzkj03OeW7DbtioS1neZjAfk_fcz4voqzhuKR_N7Z_ypTZXUD_U482aGCumlG9Oyp0srN4Co-i5FksZH5vdfg)

After the Picasa API changed and you guys updated it on the DEV build 12.4.0 the screenshots started uploading again however its still messed up. Before when posting an Image link in a facebook messenger chat window it would populate the image. Then i could delete the link text and send the image. Its was very convenient. Now instead of sending an image it sends a ["please sign into google"](https://photos.google.com/lr/photo/AGQQmEumSdeF_88spLYs1c-4kVgxwM9VVLfFvvZ7lQre-7_iUwXBxmDgKkdhizno_-g2B1RPF4IKHo5tID1XOZzv8tZqTlnmLg)  it also sends this if i remove the link text. 

I have double checked that i am signed into google in every aspect. Signed in to the browser, Sharex, I can even have Google photos up and running in a separate tab and still wants me to sign in but if i click the sign in it just takes me to the image. 

EDIT: This also remains an issue on 12.4.1

**Comment by lucario** [comment]
You have to check “Public upload” for others to see it.

**Comment by bajungadustin** [comment]
oh well this was never a thing before. or atleast it was never required. Im guessing this happened when the API was switched because i never selected this before and it always worked.
