### ISSUE TITLE
Reverse image search

### ISSUE THREAD

**Issue by Lerkis** [ShareX/ShareX#3987]
It generates the url just fine but i just get a 404

**Comment by HaydnDias** [comment]
Can you paste an example URL? I've tested this a few times with no issues myself.

**Comment by Lerkis** [comment]
https://www.google.com/search%3Ftbs%3Dsbi:AMhZZisJnFmYd_1mqxuKXIxBw_10roEpzFu1gPK0cANdEQO94xoTPHGAdozKW0rahM9CikAMD_1XoWj0GpRT1KkNIbRXmL83bewNSxOlQm9Qls1IOFvrHw0F4q2hqoWsS23iUZZIm6isaMYxQ2RmzDhL9fyMhFyyix3-6vUWjhm_1Z-AQyMNxQHA65Tv-uH3ENY3IpqQWpJuOnLKSxJOJ0Cv4kd_1T2d3u28R-LgXSY1F3WxmmHQJv9ZzhovEjyIC956adnGKwX1NI-VGnMsvhcnmneiZf7gjs8b09K3pS2AQn1S_1u7osjqb2wik5P5SdtBoqh0asd85aCeYr (this is from a test run)

**Comment by NettieJM** [comment]
Same issue, probably seems to be due to the encoding format of the URL.

**Comment by Jaex** [comment]
This not works?

![](https://jaex.getsharex.com/2019/04/ShareX_XYk0eynqmn.png)

**Comment by NettieJM** [comment]
It is working, but I use this custom uploader. (https://github.com/ShareX/ShareX/issues/1198)
It is inconvenient because I want to search directly for capturing image.

**Comment by Jaex** [comment]
I couldn't make that custom uploader work with new system too.

**Comment by Lerkis** [comment]
Can't you make it a hotkey under tools? 

![ShareX_UeNDI7ajAv](https://user-images.githubusercontent.com/37546151/56092850-15a9ee00-5ef4-11e9-8d03-7a89a4ef3196.png)

**Comment by Jaex** [comment]
Last time I check Google Search API was not free and free version had usage limit.

**Comment by NettieJM** [comment]
Now it works correctly if I decode the test result URL I tried.
Is it just a URL formatting issue?
https://www.google.com/search%3Ftbs%3Dsbi:AMhZZiu8mgoi7BakgAriVQtpIcNlq24Ly-O5yChzGlhrwsI1c-YCQs62OlY18s4yRDvmMAwlZxiey5YBUR0FPC5QHDZJimKxB-Q7hDKf6eBBIDeNyy6wK5gRBrRv6ydbgdRVm5sgmgisIts_1vmMrupTbaVUzljIjTws4naKfR6fMzrMtgdNP6NDS6VIDNNi_1tpUMtisfXyvvYDrV_1_1TJo7Pq-KLCMd3Dyphu9VY-R59PZDps2N9D1DQV_1iH3tspkO4suQ8LWtNOiSp4K589CqyFq5a_1CvPGS-evmJrONGmP1LuKOAh8UouPan-2WbgPzY2QEeKgZjHGK
↓https://www.google.com/search%3Ftbs%3Dsbi:AMhZZiu8mgoi7BakgAriVQtpIcNlq24Ly-O5yChzGlhrwsI1c-YCQs62OlY18s4yRDvmMAwlZxiey5YBUR0FPC5QHDZJimKxB-Q7hDKf6eBBIDeNyy6wK5gRBrRv6ydbgdRVm5sgmgisIts_1vmMrupTbaVUzljIjTws4naKfR6fMzrMtgdNP6NDS6VIDNNi_1tpUMtisfXyvvYDrV_1_1TJo7Pq-KLCMd3Dyphu9VY-R59PZDps2N9D1DQV_1iH3tspkO4suQ8LWtNOiSp4K589CqyFq5a_1CvPGS-evmJrONGmP1LuKOAh8UouPan-2WbgPzY2QEeKgZjHGK
https://www.google.com/search%3Ftbs%3Dsbi:AMhZZiu8mgoi7BakgAriVQtpIcNlq24Ly-O5yChzGlhrwsI1c-YCQs62OlY18s4yRDvmMAwlZxiey5YBUR0FPC5QHDZJimKxB-Q7hDKf6eBBIDeNyy6wK5gRBrRv6ydbgdRVm5sgmgisIts_1vmMrupTbaVUzljIjTws4naKfR6fMzrMtgdNP6NDS6VIDNNi_1tpUMtisfXyvvYDrV_1_1TJo7Pq-KLCMd3Dyphu9VY-R59PZDps2N9D1DQV_1iH3tspkO4suQ8LWtNOiSp4K589CqyFq5a_1CvPGS-evmJrONGmP1LuKOAh8UouPan-2WbgPzY2QEeKgZjHGKhttps://www.google.com/search%3Ftbs%3Dsbi:AMhZZiu8mgoi7BakgAriVQtpIcNlq24Ly-O5yChzGlhrwsI1c-YCQs62OlY18s4yRDvmMAwlZxiey5YBUR0FPC5QHDZJimKxB-Q7hDKf6eBBIDeNyy6wK5gRBrRv6ydbgdRVm5sgmgisIts_1vmMrupTbaVUzljIjTws4naKfR6fMzrMtgdNP6NDS6VIDNNi_1tpUMtisfXyvvYDrV_1_1TJo7Pq-KLCMd3Dyphu9VY-R59PZDps2N9D1DQV_1iH3tspkO4suQ8LWtNOiSp4K589CqyFq5a_1CvPGS-evmJrONGmP1LuKOAh8UouPan-2WbgPzY2QEeKgZjHGK
↓
https://www.google.com/search?tbs=sbi:AMhZZiu8mgoi7BakgAriVQtpIcNlq24Ly-O5yChzGlhrwsI1c-YCQs62OlY18s4yRDvmMAwlZxiey5YBUR0FPC5QHDZJimKxB-Q7hDKf6eBBIDeNyy6wK5gRBrRv6ydbgdRVm5sgmgisIts_1vmMrupTbaVUzljIjTws4naKfR6fMzrMtgdNP6NDS6VIDNNi_1tpUMtisfXyvvYDrV_1_1TJo7Pq-KLCMd3Dyphu9VY-R59PZDps2N9D1DQV_1iH3tspkO4suQ8LWtNOiSp4K589CqyFq5a_1CvPGS-evmJrONGmP1LuKOAh8UouPan-2WbgPzY2QEeKgZjHGK

**Comment by NettieJM** [comment]
oh, correct before URL:
https://www.google.com/search%3Ftbs%3Dsbi:AMhZZiu8mgoi7BakgAriVQtpIcNlq24Ly-O5yChzGlhrwsI1c-YCQs62OlY18s4yRDvmMAwlZxiey5YBUR0FPC5QHDZJimKxB-Q7hDKf6eBBIDeNyy6wK5gRBrRv6ydbgdRVm5sgmgisIts_1vmMrupTbaVUzljIjTws4naKfR6fMzrMtgdNP6NDS6VIDNNi_1tpUMtisfXyvvYDrV_1_1TJo7Pq-KLCMd3Dyphu9VY-R59PZDps2N9D1DQV_1iH3tspkO4suQ8LWtNOiSp4K589CqyFq5a_1CvPGS-evmJrONGmP1LuKOAh8UouPan-2WbgPzY2QEeKgZjHGK

**Comment by Lerkis** [comment]
What about adding it to the after upload tasks?
![ShareX_uAgGFGHwhU](https://user-images.githubusercontent.com/37546151/56093072-bc8f8980-5ef6-11e9-8726-6dc898427662.png)

**Comment by NettieJM** [comment]
My setting, destination is the above custom uploader.
![ShareX_ANcWf1WrWC](https://user-images.githubusercontent.com/28821962/56093148-beaa1600-5eff-11e9-9d14-9a9a86a84081.png)

**Comment by Delivator** [comment]
Yeah would be nice to use that as an action for quick tasks!
