### ISSUE TITLE
Hide public_html from sharex

### ISSUE THREAD

**Issue by CodingEnzyme** [ShareX/ShareX#3990]
Hello.

I use sharex to upload images to my webserver. This is how the configuration for the FTP looks.

https://i.stack.imgur.com/bGuTr.png

Thing is, if I want to access the url after uploading it, i can't use "public_html" first in the directory. Since the program automaticly copies that link, I need to edit that out before I can post it. Does anyone know a way to allow public_html in the adress, or to copy the link without public_html?

**Comment by Jaex** [comment]
Uncheck "Append remote directory" option.

**Comment by CodingEnzyme** [comment]
Thank you.
