### ISSUE TITLE
ShareX in regards to WinForms being Open Sourced

### ISSUE THREAD

**Issue by nsuchy** [ShareX/ShareX#3994]
As many of you may or may not know know, the project winforms (Windows Forms) has historically been a closed source ui framework. Microsoft open sourced the framework, see: https://github.com/dotnet/winforms and is including it in dotnet core 3.0 (releasing later this year). With that stated, will ShareX consider releasing builds for other operating systems and building the project for dotnet core?

**Comment by Jaex** [comment]
> will ShareX consider releasing builds for other operating systems

You are aware Win Forms in .NET Core is Windows only, right?

**Comment by sylveon** [comment]
I did get ShareX building on .NET Core, but it crashed at runtime.
![](https://cdn.discordapp.com/attachments/286227439343108096/520411868364537857/unknown.png)

**Comment by nsuchy** [comment]
> > will ShareX consider releasing builds for other operating systems
> 
> You are aware Win Forms in .NET Core is Windows only, right?

Oh, I was under the impression it being included in core meant it would be supported on other platforms.



> I did get ShareX building on .NET Core, but it crashed at runtime.
> ![](https://camo.githubusercontent.com/a3b9b8d29949d5093280aa6c946cf26b7fcb2eb2/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3238363232373433393334333130383039362f3532303431313836383336343533373835372f756e6b6e6f776e2e706e67)

Even if this is still limited to Windows for now, getting ShareX's codebase working on dotnet core would be really cool :)
