### ISSUE TITLE
Will ShareXin Be Merged with ShareX?

### ISSUE THREAD

**Issue by AntumDeluge** [ShareX/ShareX#3995]
I came to ask if ShareX can be compiled for Linux/BSD/X11 & found out about [ShareXin](https://github.com/ShareXin/ShareXin). I'm curious if it will ever be merged with ShareX for multi-platform support.

**Comment by sylveon** [comment]
ShareXin is a complete rewrite, not a port. It cannot be merged with ShareX.

**Comment by AntumDeluge** [comment]
Ah thanks. After looking through ShareXin's source, I came back to ask if it was branched from ShareX, but you were too fast. :)
