### ISSUE TITLE
12.4.1 Download Has Wrong Version

### ISSUE THREAD

**Issue by AntumDeluge** [ShareX/ShareX#3996]
I downloaded [*ShareX-portable.zip* version 12.4.1](https://github.com/ShareX/ShareX/releases/tag/v12.4.1). However, when launching it, the version number is 12.3.1 & it reports that a newer version is available. Not sure if the wrong version is included in the .zip download, or if it is actually the newest with the wrong number encoded into it. I then downloaded *ShareX-12.4.1-setup.exe* & found that it was the same. The version number displayed in the title bar & the about dialog is 12.3.1.

**Comment by Jaex** [comment]
You didn't close your old ShareX. So it opens when you run new versions.

**Comment by AntumDeluge** [comment]
Ah, sorry. I didn't realize it was running in the tray. I am only now beginning to experiment with ShareX.
