### ISSUE TITLE
Request: when choosing to capture region, show zoomed area, and make it work like color picker if picked a dot

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#3998]
Something like that:

[2019-03-03_11-17-10.zip](https://github.com/ShareX/ShareX/files/2922927/2019-03-03_11-17-10.zip)

This can help to precisely choose the rectangle of cropping.

But if instead of dragging to choose a rectangle, you just click, it will show a dialog of the color that the cursor was pointing at, so that you could copy its fields.

In addition, in the settings, you could choose if you want to show the dialog, or instantly copy the value of the color (Hex value of RGB should be useful).

**Comment by AndroidDeveloperLB** [comment]
It could also be nice to have the color-picker option available on the toolbar, after the image was chosen.

**Comment by Scrxtchy** [comment]
Why not just use the colour picker?
I have mine bound to when I middle click the task bar icon, you can otherwise give it your own shortcut key in the hotkey settings

![19-03-03_22-32-50-sharex_-_region_capture](https://user-images.githubusercontent.com/12771982/53694555-ae812000-3e04-11e9-80af-45716edcbcf2.png)

**Comment by AndroidDeveloperLB** [comment]
Color picker has 2 tools that don't work well
1. Shows a dialog that you show here, which requires an additional step to get the color from the screen. 
2. Directly select a color, but doesn't show a zoomed area for it.

But now that I think about it, the current behavior of area selection when clicking is to capture the window, which makes sense too. 
So I think this feature should be optional (need a toggle in the settings for what to do when clicking while having a region capture), yet it should show a zoomed area of what we choose, and should allow us to have a color picker on the toolbar that is shown after the selection was done.

**Comment by 567legodude** [comment]
We keep getting the response that the color picker requires another region capture, and we don't want to have 2 region captures open at once. This doesn't make any sense.
If I want to draw a rectangle using a color from the screen, why can't the color picker use the existing region capture instance that's already there?

**Comment by AndroidDeveloperLB** [comment]
It's a request. Not an issue.
And why auto-close?

**Comment by AndroidDeveloperLB** [comment]
It's a request. Not an issue.
And why auto-close?

**Comment by 567legodude** [comment]
As far as I can tell this feature seems to be present on the latest version. Not sure when it was added, but I'm glad it finally was.

**Comment by AndroidDeveloperLB** [comment]
Still I don't see it. I'm talking about the screen that's shown after you take a screenshot.
