### ISSUE TITLE
Request: allow to re-adjust selected region after was selected

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#3999]
Since there is no precise selection of regions, it might go off by a pixel or two from where we intend to choose it. That's why I suggested to have a zoomed-in popup while choosing: https://github.com/ShareX/ShareX/issues/3998 . 

However, even if it will get added, there is still a chance that the user hasn't selected the correct area, and need to make it larger.

Please allow to change the rectangle (resize, move, etc... ) after it was chosen.

Something like that:

[2019-03-03_11-48-10.zip](https://github.com/ShareX/ShareX/files/2922961/2019-03-03_11-48-10.zip)

**Comment by Scrxtchy** [comment]
https://tenryuu.blob.core.windows.net/astrid/2019/03/19-03-03_22-30-11.webm

**Comment by AndroidDeveloperLB** [comment]
@Scrxtchy Yes, like this. Why close the issue?
I don't see it work like that.

**Comment by Scrxtchy** [comment]
Then you haven't configured your region select. You probably have quick select turned on

**Comment by AndroidDeveloperLB** [comment]
Quick select?
You mean the editor that comes after that?
Why not allow to merge them, so that instead of 2 steps, it would be one?
Meaning that you show the toolbar for the selected rectangle, and yet also allow to still change the selected rectangle?
It would be much better... 
See, like this:

[2019-03-03_14-54-28.zip](https://github.com/ShareX/ShareX/files/2923129/2019-03-03_14-54-28.zip)

**Comment by Scrxtchy** [comment]
Why are you even sending zip files?

**Comment by AndroidDeveloperLB** [comment]
If you open it, it will have a video inside, showing what I mean.
Github doesn't let to put the video file right away. Zipped files are allowed instead.

**Comment by AndroidDeveloperLB** [comment]
Why close?
