### ISSUE TITLE
When using region capture, the image in the clipboard is moved a few pixels to the right, with weird pixels appearing on the bottom-left. Program issue or something else?

### ISSUE THREAD

**Issue by naibalucian** [ShareX/ShareX#4000]
![Quick example of what's going on.](https://user-images.githubusercontent.com/24809091/53694238-8f5aa200-3db4-11e9-9f2f-835f4a54c25b.png) It's been happening for the last 3-4 days. Reinstalling and updating the graphics card drivers did not fix the issue, and the issue only occurs when using region capture. Weirdly, when copying the image into a program like Paint or Photoshop, the issue does not appear and neither does it when uploading it via ShareX, but when uploading elsewhere (imgur, Twitter etc) via Chrome or Firefox the problem instantly appears.

**Comment by Jaex** [comment]
This option is "True" right?

![](https://jaex.getsharex.com/2019/03/ShareX_G8ynA48Xj3.png)

**Comment by naibalucian** [comment]
It is indeed true. Changing it to false does not solve the issue.

**Comment by anon88391** [comment]
I'm experiencing the same bug. When pasting the picture from clipboard on most websites, 1 column of pixels from the very right is shifted to the very left.
I also have UseDefaultClipboardCopyImage set to true.

**Comment by Frynee** [comment]
Same
