### ISSUE TITLE
Feature Request: Zoom/Pan in image preview

### ISSUE THREAD

**Issue by Lewis14** [ShareX/ShareX#4005]
![image](https://user-images.githubusercontent.com/41471929/53961564-cb597400-40e0-11e9-85ca-ace7eb11873e.png)

Would it be possible to see some kind of zoom and pan option for the image preview window? I take screengrabs of tech windows all the time and rather than opening them with Windows previewer to zoom it would be very useful to have the option to scroll and zoom on this bit.

**Comment by Jaex** [comment]
Clicking on it opens fullscreen preview, is that not enough?

**Comment by Lewis14** [comment]
> Clicking on it opens fullscreen preview, is that not enough?

When the captured region is very small, it will stay at 100% size rather than enlarging with the preview window. So for small captures it would be nice to zoom in a bit.

**Comment by hotellinawebmaster** [comment]
Hello, congrats for tis software first of all, it's a piece of cake.
It would be nice if you add zoom  and pan as Lewis suggested, otherwise we need to open it on an external image reader to have 
 kind of zoom pan features. Thaaaaaanks.

**Comment by L1Q** [comment]
This feature has been implemented for some time already. Use Ctrl+ mouse wheel to zoom, press and hold the mouse wheel to pan.
