### ISSUE TITLE
Request: Define Default Settings / Import settings on install (command line)

### ISSUE THREAD

**Issue by adutra22** [ShareX/ShareX#4006]
I would like to request being able to use a slash command to auto-import a preset configuration file (hotkey and application config files) so each install is setup exactly the same. Also so that any new users that log into the machine get the proper config files as well. With the files stored in a user folder, any new users won't get the proper settings (in its current design).

**Comment by Alaponuke** [comment]
Yes please this feature will be fantastic to deploy the app in all computers with same configuration
