### ISSUE TITLE
Any way to fully remove or disable destinations and upload settings?

### ISSUE THREAD

**Issue by markusd1984** [ShareX/ShareX#4008]
I'm sure there are a lot of share x users in a corporate setting that don't like the **risk exposure** of the upload functionality to be configurable by the user in the **Advanced Application settings**, some may not even be able to use share x entirely due to this.

Since settings are stored only in the configuration file (and thus no settings can be set via group policy), is there any way we could disable access to the setting that way?

Is there any way we can remove all of the destinations entirely part of a portable version?

**Comment by markusd1984** [comment]
related issues:

Prevent inadvertant uploads https://github.com/ShareX/ShareX/issues/1504

Disable automatic upload https://github.com/ShareX/ShareX/issues/1281

**Comment by lucario** [comment]
You should be able to configure sharex how you want, then lock the application config as read only to prevent modification, and duplicate it other machines.

**Comment by Peter-Optiway** [comment]
My settings window has no DisableUpload value to change!
![image](https://user-images.githubusercontent.com/29247423/55235564-212bc280-522e-11e9-9cfc-d80e608ae272.png)

**Comment by Jaex** [comment]
@Peter-Optiway it is in application settings window.

**Comment by markusd1984** [comment]
> You should be able to configure sharex how you want, then lock the application config as read only to prevent modification, and duplicate it other machines.

Even if one were to deploy the portable version with the config file as read only, How/Where does one **disable all upload capabilities and destinations** in the app settings?
