### ISSUE TITLE
Both "$output$".mkv and "$output$".mkv results in filenames such as: 2019-03-10_19-34-48.mp4.mkv with screen recorder

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#4015]
Hi!

This is an ancient issue. I never figured out why it happens or how to solve it.
No clue where or why the .mp4 comes from, the container is in fact matroska. 

It doesn't happen with "$output$.avi", it looks like.

My actual command line right now,  if it's of interest:
`-y -rtbufsize 1300M -f dshow -framerate 50 -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:a copy  -vf scale=out_color_matrix=bt709 -vcodec ffv1 -pix_fmt bgr0 -slices 4 -threads 2 -level 3 -coder 0 "$output$.mkv"`

**Comment by sergeevabc** [comment]
I believe this issue deserves more attention. If users want to record desktop in two steps (fast lossless then slow compression), then it is likely s/he will want to use MKV for immediate phase. So how could we change the extension here in a proper way (i.e. *.mp4.mkv -> *.mkv)? @Jaex
