### ISSUE TITLE
[Feature Request]Firefox Send

### ISSUE THREAD

**Issue by x9cf9w73cv7y** [ShareX/ShareX#4020]
It would be nice to add support for Firefox Send since it's not a beta anymore.
https://send.firefox.com/
https://github.com/mozilla/send

**Comment by Kezxo** [comment]
This command line tool can upload files to Firefox Send if that helps in some way: https://github.com/timvisee/ffsend

**Comment by Jaex** [comment]
Duplicate of #2736
