### ISSUE TITLE
auto-saving

### ISSUE THREAD

**Issue by raafaello1982** [ShareX/ShareX#4022]
Hey, During manual selection of the selected area, "clipping" the slice. Clicking the left mouse button several times causes the recording to be blanked.

Order model:
After selecting the selected area and "releasing" the left mouse button, the image would be automatically saved. I had such a configuration on the previous workstation, to which I no longer have access.

**Comment by Jaex** [comment]
You are asking this option in region capture?

![](https://jaex.getsharex.com/2019/03/ShareX_BxysStvumq.png)

**Comment by raafaello1982** [comment]
By clicking on the ShareX icon next to the clock, I select the area with the left mouse button. When I do this, the picture should be saved automatically, it is currently "freezing" - a few clicks are required (then the editor starts and only the file is saved).

**Comment by Jaex** [comment]
Did you uncheck option I showed to you?

**Comment by raafaello1982** [comment]
Unfortunately, no, I do not start such a panel. I'm developing options from the right mouse click, moving on the ShareX icon, visible near the Windows clock.

**Comment by Jaex** [comment]
Region capture have that panel.

**Comment by raafaello1982** [comment]
I managed to set this, I disabled the "Use multi region mode which will also allow" option

Currently after the screenshot I do not get a preview of the picture near the clock, which symbolized the correctness of the screen. If you clicked on it, he opened a picture of the file stored on the disk.

**Comment by Jaex** [comment]
In after capture tasks menu you must have disabled upload option.

**Comment by raafaello1982** [comment]
<a href=https://zapodaj.net/c785e65dbed41.jpg.html>19marzec13085842.jpg</a>
I have such options, I am asking for information that I should have marked.
