### ISSUE TITLE
FFMPEG windows 10 Error

### ISSUE THREAD

**Issue by lythopya** [ShareX/ShareX#4024]
hello, i just download sharex 12.4.1 with my laptop windows 10, i try sharex at my other laptop with windows 8 and it work perfectly.

but with my windows 10 laptop it show this
![hel 3](https://user-images.githubusercontent.com/48537483/54324691-4d8def00-4631-11e9-8f6a-6b2985a1bcc1.png)

i tried reinstall it like in this issue https://github.com/ShareX/ShareX/issues/2761
download the stable verison and put the ffmpeg.exe to the sharex/tool/ replacing the ffmpeg

tried reinstall the ffmpeg

and then with the issue i tried to set video source to GDI with no sound
![hel 2](https://user-images.githubusercontent.com/48537483/54324676-38b15b80-4631-11e9-9d44-8acbf502e161.png)
it seems run fine test CMD 

and i tried change the recording voice with microphone phone array result this
![hel  1](https://user-images.githubusercontent.com/48537483/54324632-0e5f9e00-4631-11e9-9fd1-b60ef34f2326.png)

but as soon as i change it to virtual audio capture [https://ibb.co/rZXM67f](url)

i really confuse with this please help i just want to record voice in my laptop. not pic/ vids

Ps: i uninstall my antivirus for this

**Comment by Scrxtchy** [comment]
If you want to just record audio from your PC, I may suggest using alternative software such as 
https://www.audacityteam.org/
It is better suited to recording only voice, and you don't need a software engineering experience to solve problems with ffmpeg

ShareX is mainly designed as a tool for screen capture

**Comment by lythopya** [comment]
> If you want to just record audio from your PC, I may suggest using alternative software such as
> https://www.audacityteam.org/
> It is better suited to recording only voice, and you don't need a software engineering experience to solve problems with ffmpeg
> 
> ShareX is mainly designed as a tool for screen capture

thanks for the suggestion, i will look into it.

it's just make me confuse with the windows 8 everything works great, but in the windows 10 and my new laptop it just doesn't work.
but i was wondering are the problem are from the windows 10 or the laptop or perhaps the driver not installed properly.

**Comment by Scrxtchy** [comment]
Probably not installed properly, a number of people have reported the issue, but they say it resolves itself after a few attempts 
https://github.com/rdp/virtual-audio-capture-grabber-device/issues/25

**Comment by lythopya** [comment]
> Probably not installed properly, a number of people have reported the issue, but they say it resolves itself after a few attempts
> [rdp/virtual-audio-capture-grabber-device#25](https://github.com/rdp/virtual-audio-capture-grabber-device/issues/25)

i will try looking into it, for now using audacity seems great, but looking foward to use sharex if i can.

thanks alot !
