### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by hamstar0** [ShareX/ShareX#4026]
ffmpeg version N-91158-g63c4a4b0d6 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 19.104 / 58. 19.104
  libavformat    58. 17.100 / 58. 17.100
  libavdevice    58.  4.100 / 58.  4.100
  libavfilter     7. 24.100 /  7. 24.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[gdigrab @ 000001f2217db400] Capturing whole desktop as 800x600x32 at (283,96)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1552607316.035239, bitrate: 460812 kb/s
    Stream #0:0: Video: bmp, bgra, 800x600, 460812 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
C:\Users\Spinach\Documents\ShareX\Screenshots\2019-03\2019-03-14_16-48-35.mp4: No such file or directory

I have no idea what this means. This occurs when I try to screen record a window. It began after I updated to the newest version (12.4.1), and continues even after reinstall.

**Comment by Jaex** [comment]
Most likely Windows Defender controlled folder access feature or another anti virus blocking ffmpeg.exe.

**Comment by Hendog** [comment]
> Most likely Windows Defender controlled folder access feature or another anti virus blocking ffmpeg.exe.

Can it be addressed in the installation routine of ShareX to whitelist ShareX and FFMPEG during the installation process? 
This should be standard practice for developers to have their apps whitelisted for write access in the folder they expect to be writing in.
