### ISSUE TITLE
Function request: Is possible add adjust board size function to image editor

### ISSUE THREAD

**Issue by jacquen** [ShareX/ShareX#4027]
Hi, Team

Is possible add resize board function in image editor, the board of circle or square and arrow is too  thick some time. Better have a way can adjust it. Thanks
![qG0aV5ln3d](https://user-images.githubusercontent.com/2107576/54404690-5b19a680-470f-11e9-9857-c81587ecafe0.png)

**Comment by Jaex** [comment]
You can change border size.
