### ISSUE TITLE
ability to save "last regions"

### ISSUE THREAD

**Issue by mishaxz** [ShareX/ShareX#4029]
Would be great to have the ability to save "last region"s and to label them and to select them.

So that you can easily take screenshots of predefined areas of the screen.

**Comment by OhiraKyou** [comment]
Just came here to leave this same suggestion. I could really use custom region presets, as I always record the same, specific regions.

**Comment by OhiraKyou** [comment]
Still want this feature.

**Comment by diskree** [comment]
+1
