### ISSUE TITLE
Google Drive file-upload not working

### ISSUE THREAD

**Issue by greensn0w** [ShareX/ShareX#404]
Whenever I try to upload a file to Google Drive using the `send to` menu, ShareX gives me this error:

> Response:
Metadata part is too large.

>StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)

Screenshots are working normally...

**Comment by TheKeyLimePie** [comment]
Did you check your anti-virus program? Yesterday my Norton program decided to block any ShareX traffic.

**Comment by fernmndez** [comment]
It's to do with the actual upload itself, it'd give a different error code / be unreachable if they're being blocked by the anti-virus

**Comment by mathemans** [comment]
![2015-02-12_08-55-00](https://cloud.githubusercontent.com/assets/1627956/6159750/0782615a-b295-11e4-95e1-ab93250379fa.png)

When I upload .ai files, google drive return errors and cannot upload at all.

**Comment by PaulBGD** [comment]
The original 400 error is occurring with me.

**Comment by Jaex** [comment]
Kesmy pull request fixed these issues I think.
