### ISSUE TITLE
Disable default selected option "upload image to host" at "after capture tasks" 

### ISSUE THREAD

**Issue by 1Jesper1** [ShareX/ShareX#4042]
Disable default selected option "upload image to host" at "after capture tasks" after installation, because a new capture would get uploaded to Imgur by default, without changing the settings.

**Comment by Jaex** [comment]
ShareX asks user in first upload, if user press no in that message box then upload gets disabled in after capture tasks.

**Comment by flanagansshenanigans** [comment]
Perhaps you should give more information. E.g. ALERT YOUR IMAGE WILL BE HOSTED ON A PUBLICLY VISIBLE ACCOUNT. I just took a screenshot of work related stuff, expecting it to be saved to my documents, but not to an online storage medium, expecially an online medium with no security. Wouldn't be so bad, if the link you get had a security token in it.

**Comment by Jaex** [comment]
Application already gives clear warning about screenshot gonna be uploaded and letting you disable it:

![](https://jaex.getsharex.com/2020/05/ShareX_o3V93OskYx.png)

So user error.

**Comment by Mattk50** [comment]
The warning doesn't specify what kind of upload it's warning about, private or public, which is a problem.
