### ISSUE TITLE
Microsoft Store version of Sharex missing features

### ISSUE THREAD

**Issue by ssolidus** [ShareX/ShareX#4047]
It appears that the "Install screen recorder" option has been removed, or at least hidden, in the **Microsoft Store** version of this program. Please note this somewhere so that people know that the Store version is missing features. Evidence is below.

![ShareX_2019-03-28_18-20-50](https://user-images.githubusercontent.com/14216632/55137897-482eb980-5186-11e9-811a-fb5d6f2694b8.png)

![image](https://user-images.githubusercontent.com/14216632/55137958-6f858680-5186-11e9-9d35-f2ef34e5552a.png)

**Comment by Jaex** [comment]
Because of restrictions it can't have all features.

**Comment by ssolidus** [comment]
@Jaex I understand this... my request is that you note it somewhere. Did you even read my entire post?

**Comment by Jaex** [comment]
Of course I read entire post. Why would I reply without reading it. But my english is not very good.

**Comment by ssolidus** [comment]
That's fine - I would appreciate if you put a note on the Store page indicating the features that that version is missing, so that users like myself don't have to figure it out themselves.

**Comment by Jaex** [comment]
Build differences:

### Steam

- Show first time config window on initial startup
- Show "Show In-App in Steam" option
- Show "Use custom path" option in FFmpeg path section

### Windows Store

- Windows 10 64 bit only
- Hide shell context menu option
- Hide send to menu option
- Hide Chrome extension panel
- Hide Firefox addon panel
- Hide DNS changer tool
- Hide "Install recorder devices" button in FFmpeg sources section

### Steam & Windows Store

- Disable auto update checking
- Hide update checker in about window
- Show build label in about window
- Hide pre release updates option
- Hide "AutoCheckUpdate" advanced option

**Comment by ssolidus** [comment]
@Jaex thanks, could you put this in the `README.md` somewhere?
