### ISSUE TITLE
Feature Request: Optional IMG code with ALT attribute!

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#4050]
Was just wondering if it would be possible to add support for BBCODE ALT Text as an option. I mostly embed images on XenForo boards which now support alt text in BBCODE. Would be nice to have an empty field included in copied code. It already happens with markdown image code where alt field is empty but available in copied code. Cheers.

**Comment by Jaex** [comment]
You can add custom format like this:

![](https://jaex.getsharex.com/2019/03/ShareX_RhHROFC9CP.png)

**Comment by Sushubh** [comment]
this worked! now if only i could attach a keyboard shortcut as well! but thanks for highlighting this feature. 🙏
