### ISSUE TITLE
New Feature - Add Effects Edges in screenshot

### ISSUE THREAD

**Issue by andersonpo** [ShareX/ShareX#4051]
Hello, 

I would like to add a new feature equal to the techsmith snagit tool, called edges, which leave the image with cropped, ripped, fade, among others.

![image](https://user-images.githubusercontent.com/7301858/55235739-009f4080-520d-11e9-881e-c298684fcb65.png)

![image](https://user-images.githubusercontent.com/7301858/55235756-0bf26c00-520d-11e9-83c9-a1c05433157b.png)

![image](https://user-images.githubusercontent.com/7301858/55235713-f2512480-520c-11e9-960b-33089d0c73db.png)

**Comment by Jaex** [comment]
It is already exists:

![](https://jaex.getsharex.com/2019/03/ShareX_nnKTIuqQLJ.png)

**Comment by Korb** [comment]
> It is already exists

@Jaex, I see this effect mentioned in the ShareX Changelog:

> ShareX 11.8.0 – 2017-07-04
> Addition of curved edge support to the torn edges image effect.
> 
> ShareX 8.4.1 – 2013-12-05
> The torn edge image effect in ShareX has been improved to support edge selection, giving users more control over the appearance and style of torn edges in their images.

However, when I installed ShareX 17.0.0 today (Jan 8, 2025), I didn't find this effect in the original set of two effects, nor on [the ShareX Image effects page](https://getsharex.com/image-effects). Have they been removed, or is there another way to get them?
