### ISSUE TITLE
ShareX license

### ISSUE THREAD

**Issue by ektrontek** [ShareX/ShareX#4053]
Would it be to use sharex software in commercial place? And is there restriction when it can use in commercial place? Thanks a lot.

**Comment by Serinus1** [comment]
It's unclear what you're asking, but the answers aren't hard to find.  It's the GPL standard license.  You can use the work the work in a commercial setting, yes, depending on your use.  You should also check the FAQ here https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem

**Comment by vatterspun** [comment]
The license allows free use in private, public, government, and commercial environments.

The only restrictions on the program are if you decide to modify the program for use and then distribute your changes.  In that case, you'd need to make available the source code edits.

You might run into issues with running the program on a system that restricts installation or only allows software that's been vetted by the Microsoft Store.  In that case either download the portable version or visit the Microsoft Store site: https://www.microsoft.com/en-us/p/sharex/

**Comment by vatterspun** [comment]
Recommend closing this case.
