### ISSUE TITLE
Customization of the window boundary selection during image capture

### ISSUE THREAD

**Issue by aashreys** [ShareX/ShareX#4055]
We're using ShareX for a usability study with some users with slight vision impairment but they're having trouble seeing the window boundary selector which capturing images. This causes them to not identify what area of the screen they are capturing.

How can I **change the stroke width and color of the window boundary selector?**

**Comment by vatterspun** [comment]
I don't know how to do this with the current config.  Under Task Settings, you can use a screen-wide crosshair to help out with visualizing.

You *might* try using Screenpresso which has a little more intense (red) borders, but that program has it's own problems (not free or open, limited features with pro warnings everywhere, insists on being able to auto-update itself, etc.).

**Comment by eidylon** [comment]
> I don't know how to do this with the current config. Under Task Settings, 
> you can use a screen-wide crosshair to help out with visualizing.

I actually just came to the github to post this as a feature request, and found out I don't have to. Awesome!

**Comment by aashreys** [comment]
I’ll see if I can find the config file which controls these visual properties. Will update the thread if I find something.

Regards,
Aashrey
