### ISSUE TITLE
[Feature Request] Image zoom in editor

### ISSUE THREAD

**Issue by Voriaz** [ShareX/ShareX#4056]
Hi,

I often use the editor to edit some pictures on my PC. Somtimes they are really big and it would be usefull to zoom out on these pictures in order to see the whole picture in the editor.

Is it possible ?

Thanks,

A.

**Comment by stephen147** [comment]
Yes, I would nearly say this was a bug. Opening an image that's larger than you monitor res is not a good time. 😒

**Comment by stephen147** [comment]
Duplicate of:

**Request: Add zoom function to image editor #2325**
