### ISSUE TITLE
Name is too difficult

### ISSUE THREAD

**Issue by akbardwi** [ShareX/ShareX#4062]
The saved file name is too hard to memorize, so it makes users confused when the screnshoot will be uploaded. If you can, give an easy name like filename.exe_dd-mm-yy.png (with extension picture jpg, png, gif, or anymore)
Note: dd-mm-yy is the date when the screnshoot was taken

**Comment by angelhdz** [comment]
You can modify the directory name and the file name of the captures, and also the uploaded's.

![image](https://user-images.githubusercontent.com/10191085/55680464-d2de8980-58e7-11e9-9d29-448db04cd404.png)
