### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by raziEiL** [ShareX/ShareX#4063]
Color picker tools show incorrect value of saturation and brightness.
For example I get F1C40F RGB color and convert it to HSL.

[**w3schools.com converter**](https://www.w3schools.com/colors/colors_converter.asp)
![chrome_NYMjXBnfBt](https://user-images.githubusercontent.com/2551987/55666509-4ab99f00-5869-11e9-9f67-e82a8ef36682.png)

**Against**

Color picker
![ShareX_ir9lEV9YN0](https://user-images.githubusercontent.com/2551987/55666510-4db48f80-5869-11e9-8367-b57fd20eb7ef.png)

So, Color picker numbers is confusing a lot.

**Comment by Jaex** [comment]
This screenshot from Photoshop color picker:

![](https://jaex.getsharex.com/2019/04/Photoshop_DVcsSb80Jb.png)

which proves ShareX showing correct values.
