### ISSUE TITLE
Second monitor is black

### ISSUE THREAD

**Issue by fancolj** [ShareX/ShareX#4065]
Hello. I have the same issue as #2275 #2247

https://i.imgur.com/FOwkier.png 

My second monitor is black while using capture region. I have this issue from about 2 weeks. The only changes in my system was automatic update of Windows 10. 

I can't find solution of this problem.

**Comment by Jaex** [comment]
I don't have second monitor. But high amount of people using ShareX with multi monitors and when I ask them they don't have this problem.

**Comment by fancolj** [comment]
I used ShareX with 2 monitors from a few years. This happened around 2 weeks ago.

**Comment by ZjemCiKolege** [comment]
Same issue ;)

**Comment by Jaex** [comment]
If you close ShareX and use Windows printscreen key to take screenshot, is all monitors capture correctly?

**Comment by fancolj** [comment]
Yes. Using PrintScreen with ShareX turned off correctly captures both monitors

**Comment by fancolj** [comment]
We have a... solution. The problem was caused by COMODO Internet Security software. After uninstalling I see both monitors. Probably some module of sandbox/HIPS caused this problem. I still do no know what exactly was it and how do add an exception in Comodo to work with it.
