### ISSUE TITLE
Scaling issue with any capture(screen, region, etc...)

### ISSUE THREAD

**Issue by Zoob011** [ShareX/ShareX#4073]
Anyway, for quite a while on 1 of the PCs that i have i got this issue, with what looks like to be scaling(could be totally wrong here). On the other PC works just fine(PC#1 is laptop and it worked fine on it in the past, just stopped working few months ago). It has Windows10 on it. Here's screen shot example of the problem

https://i.imgur.com/s0WOia7.png

**Comment by Jaex** [comment]
If you use Windows own printscreen to capture, is it captures correctly?

**Comment by Zoob011** [comment]
Huh, no, same issue, So i guess it's Windows related then? And if so, by any chance, you know how to fix that ? ^_^

**Comment by Jaex** [comment]
It is not ShareX issue then. I have no clue why it happens to you.

**Comment by Zoob011** [comment]
Eh, anyway, found out why it was happening. Have some intel graphics panel. When i went into graphic options(under display), found out that it had scaling set to "Adjust to Full screen", changed it to "Don't change ratio" option and it works now. Hope it helps someone

**Comment by Jaex** [comment]
Few people also reported this issue before, so thanks for writing your solution.
