### ISSUE TITLE
ShareX Disable Upload Entirely

### ISSUE THREAD

**Issue by CameronHodgson** [ShareX/ShareX#4074]
Hello,

I mainly use ShareX to take screenshots in place of a tool like the windows snipping tool.

I'd like to use this for work but I don't want the screenshots to be uploaded. Is there a way to entirely disable uploads and have them only save locally to a folder? I tried messing around with the settings and advanced settings but can't find a clear option.

**Comment by L1Q** [comment]
try Application - Advanced - Disable Upload

**Comment by CameronHodgson** [comment]
Perfect! This worked. Thankyou!

**Comment by DoS007** [comment]
@L1Q This does not work anymore? How to do it now?

**Comment by mrra66** [comment]
thanks

**Comment by posti85** [comment]
Thank you very much. It's great to see that such option exists.

Anyway, I think that option shouldn't be that hidden or advanced, because there are many people (like me) who only will use this tool for private (in local drive) screenshots/video captures.

**Comment by igroglaz** [comment]
This option should be in main settings - visible and clear, not like right now as config option.. And uploading should be forbidden by default.

**Comment by Stan-Stani** [comment]
What if I want files (videos) to upload but not images?

**Comment by Kyhze** [comment]
> What if I want files (videos) to upload but not images?

I'm also looking for that. But the other way around: I wanna keep uploading image captures, but not video captures. 
Seems it's either all or nothing.

**Comment by theonlybrand** [comment]
Why not make this an opt-in instead of an opt-out?

**Comment by BrycensRanch** [comment]
> Why not make this an opt-in instead of an opt-out?

The community voted for it on X.

**Comment by JNavith** [comment]
I just accidentally uploaded my drivers license to imgur over this and can't delete it myself cause it's using an anonymous account.

I know the world doesn't revolve around me, but please for the love of god make uploading opt-in or prompt for credentials before falling back to anonymous...

**Comment by Mystqr4** [comment]
> I just accidentally uploaded my drivers license to imgur over this and can't delete it myself cause it's using an anonymous account.
> 
> I know the world doesn't revolve around me, but please for the love of god make uploading opt-in or prompt for credentials before falling back to anonymous...

Absolutely agree!  
An optional confirmation or decline prompt should be added.

**Comment by nodejsg** [comment]
PLZ Disable Upload Entirely by default, both install version and portable version.
There is a NO UPLOAD version. https://github.com/Cosebdd/ShareNot

**Comment by Mystqr4** [comment]
Making it opt in is a start, adding an option for a confirmation dialog to appear before it uploads would be great too. You could also add a tick box to remember decision so if one decides to not want a confirmation and have it as it is now they can. Another addition on top of that could be to remember per session which could be pre-configured to a set amount of time deep in the settings for example allow to define a session by minutes/hours that way if you are uploading lots of images separately then you can manage that within a session so the confirmation dialog does not appear within that session time that way one can continue to recklessly upload files without confirmation with that session time. Once again the remember decision tick box could still be deployed also.

There are a lot of ways to go about this but as it is its just very bad. 

I am aware of the ShareX fork (ShareNot) that does not contain any upload feature but it just boggles my mind why this cannot be improved upon in ShareX.

ShareNot is something my brother would use as he has no interest in uploading any pics but I do from time to time when posting reviews or for general fun and such in discussion forums/boards and stuff.
