### ISSUE TITLE
Not an issue. Just wanted the option to donate via paypal

### ISSUE THREAD

**Issue by denisedelbando** [ShareX/ShareX#4076]
I would like to donate to this project cause its done really well but would like an option to transfer via paypal. I dont have any bitcoins nor do i have patreon

**Comment by Jaex** [comment]
PayPal is blocked in my country so I can't use it. But Patreon support PayPal.

**Comment by sylveon** [comment]
Patreon accepts PayPal payments but is a recurring donation system. You can use it for single-time donations however simply by becoming a patron then immediately cancelling it.
