### ISSUE TITLE
upload to google drive 401 unauthorized?

### ISSUE THREAD

**Issue by hien4990** [ShareX/ShareX#4077]
when i sign in i can upload to google drive normally, but after a few hours i can upload anymore it say "401 unauthorized"
i just refresh the authorization on sharex and it work again, are there a solution that sharex always work until i signed off instead of must refresh the authorization every hour?

**Comment by hien4990** [comment]
here the error log
Status code:
401 Unauthorized

Headers:
X-GUploader-UploadID: AEnB2UppPMHIqLobDlJnQ-5Gs_kfRS4H-YjnZyvb-YdgKcvfzfD9YUaSQDPdjxqRSg68Y-8iqzTgEWCYVBat3rL2VchfkkeIQftXHxe32OipkDgG8J_2s8I
Vary: Origin,X-Origin
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Content-Length: 249
Content-Type: application/json; charset=UTF-8
Date: Sun, 14 Apr 2019 13:05:30 GMT
Server: UploadServer
WWW-Authenticate: Bearer realm="https://accounts.google.com/", error=invalid_token

Response text:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by perler** [comment]
the exact same thing with the same log entry happens here..

**Comment by explorer9000** [comment]
the same problem on version 13.7
