### ISSUE TITLE
Uploading mp4s to gfycat with audio

### ISSUE THREAD

**Issue by maroru** [ShareX/ShareX#4078]
If I screen record a mp4 and upload to gfycat it doesn't have any audio on the websites upload, however the gfycat website does allow you to upload videos with audio, but you need an account to toggle it.

How this looks like on the gfycat website:
![How this looks like on gfycat website](https://i.imgur.com/clMypT8.png)
I've created a gfycat account and authorized it with sharex and tried to upload again with sharex but there's still no audio. If I use my browser and go upload my mp4 to gfycat through their website and toggle sound it will upload correctly with audio, and if I set my sharex file upload destination to streamable it has audio on that website.

Is there some setting I am missing or is this not a supported feature for gfycat?

Is there a way to toggle audio on/off for uploads (if I wanted to upload to streamable without audio) ?

**Comment by lucario** [comment]
Gfycat with audio is in the latest dev build https://getsharex.com/docs/dev-builds

**Comment by maroru** [comment]
Dev build unavailable for steam version?
![sharex](https://i.imgur.com/doIC2fD.png)

**Comment by Jaex** [comment]
Yes only normal build have dev build install.
