### ISSUE TITLE
Transparency only works via url share, not clipboard?

### ISSUE THREAD

**Issue by Zwodo** [ShareX/ShareX#4080]
Hello,

I had puu.sh set up for years and I never really knew about ShareX (I heard of it once) until recently I renewed my PC. So far, I love it! The transparency, copying to clipboard, circular cropping, free-hand cropping.. Amazing tools! However, there lies the problem already. I cannot seem to get it to work where I copy something to clipboard and it is transparent. If I **upload to host**, then **open the URL** and **copy it from there**, it is transparent. If I **don't upload** and  **only copy to clipboard**, it is never transparent.
I read some threads about it, but none of them helped me out. I also saw that you posted a way to copy transparent images to clipboard, but the link you posted was broken. 

Is there a way to copy transparent images to clipboard, or should I just always upload and copy them? It's a bit of a hassle. Other than that, I love ShareX so far! Thank you very much.

**Comment by Jaex** [comment]
If it were possible I would have added it. Even if you add support for it majority of apps wouldn't support pasting it with alpha channels.
