### ISSUE TITLE
increase fixed duration time

### ISSUE THREAD

**Issue by 4evermaat** [ShareX/ShareX#4085]
Can you allow users to customize the fixed duration time?  Currently it is limited to 60 seconds.  

But what if I want to have a longer fixed recording?  Why is it hard coded to 60 seconds?
![ShareX fixed duration limited to 60 seconds](https://user-images.githubusercontent.com/830306/56179559-53ac2c80-6030-11e9-8cc9-ac6821fce9d4.png)

Also, the option to either continue recording OR to only record once per session is needed.  To allow continuous recording, but broken up into smaller files vs 1 large file.

**Comment by Jaex** [comment]
Because ShareX is not good for long recordings.

**Comment by 4evermaat** [comment]
> Because ShareX is not good for long recordings.

Can you please elaborate on why this is the case? (If it is good for short recordings, why can't it be good for long recordings?)

Why have a checkmark option at all then?  Why not make it hard coded to have maximum 60 second clips?

**Comment by 4evermaat** [comment]
> Because ShareX is not good for long recordings.

Can you please elaborate on why this is the case? (If it is good for short recordings, why can't it be good for long recordings?)

Why have a checkmark option at all then? Why not make it hard coded to have maximum 60 second clips?

There was no technical reasons  provided.

**Comment by nr1995** [comment]
Yeah I'm also wondering why an answer for this was so pointedly avoided.

**Comment by sharchun** [comment]
Late, but I found the answer on [Reddit](https://www.reddit.com/r/sharex/comments/nfxwmm/how_to_set_time_limit_for_screen_recording/):

> In "additional command line arguments" of "screen recording option" located just above fixed duration, you can set time duration.
> 
> To give duration in hour, minutes and seconds the syntax is
> 
> -t HH:MM:SS
> 
> So for 1 hour 10 minutes
> 
> -t 01:10:00

Personally tested this recording 1 hour+ videos and can confirm it works just fine.
