### ISSUE TITLE
Pixelate blur strength

### ISSUE THREAD

**Issue by Meercat9** [ShareX/ShareX#4087]
I've been unable to find any way to change the amount of blur/pixelate. The number in the bracket appears to be the strength which implies it's possible to change this?

![image](https://user-images.githubusercontent.com/13530200/56251015-3c834280-60f5-11e9-92f1-7281690e38f1.png)

I've read some comments about it being possible, but I think that might be referring to the old editor - #3220.

Is this possible, and if not would it be practical to add this to the new editor? Even the ability to change the default at a global level?

**Comment by L1Q** [comment]
You do it in the panel that appears on top center of your screen.
Under "Shape options" there should be "Blur strength" or "Pixel size" option for respective effects.

**Comment by Meercat9** [comment]
Ah okay. I didn't realise that the pop-out changed depending on the tool selection. Thank you for the help - no application issues here.

**Comment by maxlindb** [comment]
Sorry for the necro, but I want to point out that as a long time user, finding this issue on google was the only way I was able to figure out how to do this. A settings menu under another button (a button that is in the same "section" as the blur tool itself) changing its when-open content based on the active tool is _entirely unintuitive_. Not bad if you learn it, but not learnable through intuition.

Showing something like "shift+scroll" next to the blur strength that is already visible on the blurred area itself, or a small tool settings popup window while the tool is active would surely increase the use of the useful "blur strength" setting!
