### ISSUE TITLE
Issue with 1680x1050 monitor (region capture) (distortion)

### ISSUE THREAD

**Issue by douglaslins** [ShareX/ShareX#4094]
Hi, I've been using ShareX with a 1440x900 + 1920x1080 and never had this issue

This issue only popped up after upgrading to a 1680x1050

See what happens when I try to capture region:

ShareX resizes monitor 2's image, making it even cover part of monitor 1 https://i.imgur.com/qceulkK.jpg

It even resizes in a bad way. You can see the text is distorted.

Capture Monitor 1 (1920x1080): https://i.imgur.com/zsXiM54.jpg

Capture Monitor 2 (1680x1050): https://i.imgur.com/ACKJITv.jpg

**Comment by Jaex** [comment]
What happens if you take screenshot with Windows itself without ShareX?

**Comment by douglaslins** [comment]
Oh! Same issue. 

So it isn't a ShareX problem. Any idea how to fix it?

**Comment by Jaex** [comment]
Check: https://github.com/ShareX/ShareX/issues/4073#issuecomment-482054557

**Comment by douglaslins** [comment]
Solved! Thank you.

In my case it was Nvidia aspect ratio :)
