### ISSUE TITLE
Use custom screenshot folder setting not saved

### ISSUE THREAD

**Issue by firebone-be** [ShareX/ShareX#4096]
When setting a custom screenshot folder the setting is lost after each reboot.
![ShareX_3uDUYFbh6l](https://user-images.githubusercontent.com/47481963/56664676-cf4d4f80-66a8-11e9-86f1-74f770c9e565.png)

**Comment by Jaex** [comment]
Writing files to program files requires admin access. ShareX not runs as admin. Which causing your settings to lost.
