### ISSUE TITLE
Suggestion: Capture clicks when recording GIFs

### ISSUE THREAD

**Issue by alejandro5042** [ShareX/ShareX#4097]
Add an option that captures clicks in GIFs with a halo, similar to:

![image](https://user-images.githubusercontent.com/3143819/56770600-063f6600-677a-11e9-84e9-fcbdfd985444.png)

**Comment by MikelLuri** [comment]
I'd love to have this, too

**Comment by alejandro5042** [comment]
I still want this, thanks!

**Comment by alejandro5042** [comment]
I still care about this. Would make a big positive impact to recording issues to post in bug trackers.

**Comment by alejandro5042** [comment]
Darn it, I still care about this. Missed the last message! Can we reopen?
