### ISSUE TITLE
[Feature request] Crop to selection

### ISSUE THREAD

**Issue by timlt** [ShareX/ShareX#4103]
Hi, when editing an image, it would be helpful to be able to crop to selection.  For example, if the user has drawn an ellipse in the captured image, it would be useful to have a feature such as "Crop to selection."

If this capability already exists in ShareX, please let me know, haven't been able to locate it.

**Comment by Jaex** [comment]
This tool?

![](https://jaex.getsharex.com/2019/04/ShareX_rhUN2j98iU.png)

**Comment by timlt** [comment]
Yes I use that tool that crops to a rectangular shape.  I meant an option that lets you select a shape, like an ellipse or freehand selection, and crop to that.
