### ISSUE TITLE
Windows 10 UHD mode completely washes out visuals when taking a screenshot

### ISSUE THREAD

**Issue by StormedJF** [ShareX/ShareX#4105]
I recently got a UHD 4K TV and noticed after enabling Windows 10's HDR mode (also known as Windows HD Color), all visuals are be washed out when entering screenshot mode. As an example, here is a comparison:

Original Image: https://i.imgur.com/Jh7RhPj.jpg
Screenshotted Image: https://i.imgur.com/f0LFTc9.jpg

While I don't know if this would even be able to be fixed since this is probably Windows fault with how it handles HDR, but I feel like it's worth sharing here.

**Comment by dylanh724** [comment]
I have this exact issue, and only happened when I enabled HDR10 on Win10.
