### ISSUE TITLE
[Feature Request] Thanos snap effect

### ISSUE THREAD

**Issue by ghost** [ShareX/ShareX#4106]
That'd be cool to see a "Thanos Snap" as effect in ShareX! Here's an example:

![Pixelate](https://user-images.githubusercontent.com/46478307/57025813-48b8e500-6c49-11e9-95af-54c74663dea1.png)

**Comment by JakubKoralewski** [comment]
This is a must-have actually.

**Comment by JohnyTheCarrot** [comment]
+1

**Comment by vatterspun** [comment]
This is probably out of scope for ShareX, but there is a free app called PicsArt that uses a "Dispursion" : https://picsart.com/hashtag/dispersion

If you want something that looks really good, it's probably going to require Photoshop: https://photoshopcafe.com/particle-disintegration-effect-photoshop-tutorial/
