### ISSUE TITLE
Hovering over region requires double click instead of a single click to confirm screenshot

### ISSUE THREAD

**Issue by JakubKoralewski** [ShareX/ShareX#4109]
For a long time I had this feature that I could hover over a region and in a single click I would have always taken the screenshot. But since a few days/weeks I need to double click the highlighted region for some reason. I don't know if it's an update or I turned off the feature by accident while I was snooping around the settings or something. 

I'd like to have it as previously where I could just hover over a region and in a single, swift click take the screenshot.

Here's a video: https://streamable.com/x35ij
Same happens when I select the region manually, I have to double click it.

**Comment by Jaex** [comment]
Uncheck this option:

![](https://jaex.getsharex.com/2019/05/ShareX_3NG16xWrva.png)
