### ISSUE TITLE
URL returned when uploading to B2 is not percent encoded

### ISSUE THREAD

**Issue by AviKav** [ShareX/ShareX#4110]
File uploaded: `foo bar`
Expected url ending: `foo%20bar`
Actual url ending: `foo bar`

![ShareX_2019-05-04_16-44-43](https://user-images.githubusercontent.com/18518861/57184651-8ce7f780-6e8c-11e9-993e-98e9ab5e5d0b.png)

Disparity as shown in Discord:

![Discord_2019-05-04_16-46-57](https://user-images.githubusercontent.com/18518861/57184696-2d3e1c00-6e8d-11e9-902e-8125206644dc.png)

**Comment by FelixMayer123** [comment]
actually you cannot use space text

**Comment by Jaex** [comment]
Because I don't have B2 account, I can't test it. You can test it using dev build, if you would like to.

**Comment by AviKav** [comment]
Tested on 3cf0dec (Upload path was customized to `ShareX/%y/%mo/%d/%h_%mi_%s/`)

![image](https://user-images.githubusercontent.com/18518861/57200756-7198ed00-6f5d-11e9-84be-e8d841049121.png)
