### ISSUE TITLE
The remote server returned an error: (503) Server Unavailable.

### ISSUE THREAD

**Issue by jdroo** [ShareX/ShareX#4112]
Error message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
http://api.tinypic.com/api.php

Status code:
503 ServiceUnavailable

Headers:
Retry-After: 5
X-Varnish: 3638986951
Age: 10
Connection: close
X-Varnish-Server: den2tpv65
X-Cache: MISS
Accept-Ranges: bytes
Content-Length: 419
Content-Type: text/html; charset=utf-8
Date: Tue, 07 May 2019 08:06:32 GMT
Server: Varnish
Via: 1.1 varnish

Response text:

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Service Unavailable</title>
  </head>
  <body>
    <h1>Error 503 Service Unavailable</h1>
    <p>Service Unavailable</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 3638986951</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by Jaex** [comment]
TinyPic server is down.

**Comment by jdroo** [comment]
ah
