### ISSUE TITLE
[feature request] Pre-configured region coordinates, relative to current window.

### ISSUE THREAD

**Issue by towelcat** [ShareX/ShareX#4115]
As far as I can tell, the pre-configured region option only allows selecting a static region on the whole screen. It'd be nice to specify relative coordinates for the current window (so if I move the window around it'll still capture the portion I'm after).

Apologies if this is already possible, the settings windows can be a pain to navigate at times.

**Comment by Fohsap** [comment]
Hopefully clarifying the initial inquiry: 
Would like to capture a region relative to the cursor position.

**Comment by LAPIII** [comment]
I'd like this too!
