### ISSUE TITLE
[Bug] Can't both copy to clipboard and editor at the same time

### ISSUE THREAD

**Issue by zer0xs** [ShareX/ShareX#4116]
I currently have after capture tasks set to both open editor and copy to clipboard set. However, the editor opens but the image doesn't copy. Trying again with only copy to editor selected resolves the issue.

**Comment by Jaex** [comment]
It copies after editor is closed so clipboard can contain final version of image.

**Comment by zer0xs** [comment]
Is there any way to copy before instead of having to close the editor?
