### ISSUE TITLE
How to completelly reinstall Share X

### ISSUE THREAD

**Issue by NoticeMeHentai** [ShareX/ShareX#4119]
Alright I know there's another thread about "Share X not saving/resets at every startup", but this is kind of different and I can't come up with a precise title.
I had Share X installed in my SSD C:/, and I needed some space in it, and like the fool that I am, I simply drag dropped the folder into the same "ProgramFiles" folder in my HDD D:/, included the folder that was in the "My Documents" folder in C:/. Obviously, that caused the program to lose it's own references and it resetted. Even though I set it up again, at every startup it'd reset itself.

Also whenever I try screenshoting with the default settings (saving in "My Documents"), I get this error (File attached). If I use a custom folder it saves correctly. 
Of course I uninstalled and reinstalled, and deleted both folders (except screenshots folder, which is just image data). I can't remember if it asked for a folder installation, but if it did I specified the HDD disk instead of the previous SDD, but nothing changed (Personal Share X still redirects to My Documents on SSD). 

How can I completely uninstall/eliminate all of the software data so I can properly reinstall it? Thanks
![unknown (2)](https://user-images.githubusercontent.com/43136048/57574170-33576e00-7434-11e9-90ae-4fb9df136f2d.png)

**Comment by vatterspun** [comment]
You might try using the portable version as it should ignore the installed version in favor of it's own files and folders: https://github.com/ShareX/ShareX/releases

Related: #3160
