### ISSUE TITLE
Unable to register the DLL/OCX: RegSvr32 failed with exit code 0x3

### ISSUE THREAD

**Issue by InfoLibre** [ShareX/ShareX#412]
I tried ShareX 9.4.2 with a new Windows XP Pro SP3 + updates + .NET 4.0 + Microsoft Visual C++ 2010 (http://www.microsoft.com/en-us/download/details.aspx?id=5555) and have the error "Unable to register the DLL/OCX: RegSvr32 failed with exit code 0x3" like here :
https://github.com/ShareX/ShareX/issues/132

I tried with Microsoft Visual C++ 2010 **SP1** (https://www.microsoft.com/fr-fr/download/details.aspx?id=8328), same error.

**Comment by Burinis** [comment]
I have the same problem with ShareX 12.
[](https://youtu.be/EmWl4CQmG7M)
