### ISSUE TITLE
Sharex Always asks for update

### ISSUE THREAD

**Issue by Fennecai** [ShareX/ShareX#4120]
I have an issue happening with sharex where it asks me if i'd like to install the newest update every time it starts; which is a problem because it still asks even after I _do_ update it.

I think this might be a bug? it's like the program doesn't check it's own version properly.

side note, semi-related: your website should have a contact/support button, even if it just links to here. I had to look around a lot before I found out I could submit an issue here.

**Comment by Jaex** [comment]
What version is your ShareX? 2.5 years old version had that bug.

**Comment by Fennecai** [comment]
12.4.1, and keeps telling me to update even when i get newest version manually. as seen in this quote from the post you just read:

"which is a problem because it still asks even after I _do_ update it."

**Comment by Jaex** [comment]
That means you installed new ShareX to another location and that old startup ShareX starts from another location too.

**Comment by nikolay-borzov** [comment]
Have the same problem. I keep ShareX at `C:/my program files/ShareX`. After program start it asks for update and installs ShareX to `C:/Program FIles/ShareX`
