### ISSUE TITLE
Optimizing Gif Quality

### ISSUE THREAD

**Issue by Glombus1** [ShareX/ShareX#4123]
I'm not exactly at expert when it comes to making great quality gifs that are also still somewhat small size. Does anyone have any tips? I generally want to keep gifs to under 4MB - on occasion though I tend to make gifs that are maybe 6-7 seconds long, making it hard to keep their size minimal. lol, furfag telling people what to do.

**Comment by lucario** [comment]
Stop using gifs. MP4 or webm is superior in every way to gif in terms of quality and file size. Gif is an archaic format and shouldn't be used.
