### ISSUE TITLE
Keep History/Recent task without limit

### ISSUE THREAD

**Issue by MeeJay** [ShareX/ShareX#4125]
I would like to know if it's possible to keep everything in history, actually Recent Task are limited to 100 and history is vanishing little by little each time I take a pic or a vid but i'm using my own uploader on my own web server and it's not good to login by FTP each time I want to get an old file because my uploader is randomizing file name, could be easier if ShareX could simply keep all history and remove nothing.

Thank you,
Mat.

**Comment by Jaex** [comment]
For that purpose there is "History" and "Image history" buttons in main window. Those keep everything permanently.

**Comment by MeeJay** [comment]
So fast answer, thank you so much!
Ohh really great, I was not knowing about this feature, ShareX is just an amazing software and you guys are doing a great job ! Keep making this software amazing! I will continue to recommend it to all my friends!
