### ISSUE TITLE
ShareX can not be used properly in the internal network, is there any way to solve it?

### ISSUE THREAD

**Issue by btcpa** [ShareX/ShareX#4127]
I want to use shareX, on the internal network, but because I can't connect to the Internet according to the regulations, I can't download the FFmpeg file, so I can't use the screen recording (gif) feature. Excuse me, is there any way to solve this problem? 

![image](https://user-images.githubusercontent.com/48898846/57821656-df49e200-77c3-11e9-8b9c-7ae33aff7086.png)

**Comment by btcpa** [comment]
![image](https://user-images.githubusercontent.com/48898846/57821716-1fa96000-77c4-11e9-9cf4-660c8d28413d.png)

**Comment by sylveon** [comment]
Download FFMPEG by yourself, extract it somewhere and then set the ffmpeg path in video recording settings to the copy you extracted.

**Comment by btcpa** [comment]
谢谢你，已经按照你说的方法解决问题了。非常感谢

**Comment by btcpa** [comment]
Thank you. The problem has been solved in the way you said. Thank you very much
