### ISSUE TITLE
[Feature Request] Make Blob Emoji (and possibly other things?) optional

### ISSUE THREAD

**Issue by davidjcralph** [ShareX/ShareX#4130]
As someone who often has to use limited data, making blob emoji a downloadable extra (such as ffmpeg) would benefit users who need to save data when downloading ShareX onto their computer, or who do not want said images.

This could also apply to other things, such as certain dll files.

Please consider this idea!

**Comment by MorphineBear** [comment]
What are blob emojis even used for? There's a Discord Wumpus icon at the bottom.

**Comment by ohlookitsderpy** [comment]
They're used for stickers

**Comment by ohlookitsderpy** [comment]
no thanks

**Comment by ohlookitsderpy** [comment]
again, no thanks

**Comment by ohlookitsderpy** [comment]
no stale

**Comment by ryantheleach** [comment]
I don't think it's worth the added complexity. FFMPEG was likely necessary due to licensing.
