### ISSUE TITLE
Links generated from Google Photos are not shareable

### ISSUE THREAD

**Issue by bobloadmire** [ShareX/ShareX#4135]
If i send someone thats automatically added to the clipboard, they can't view it. I tried making the ShareX album in google photos public, but that didn't work either. Suggestions?

**Comment by lucario** [comment]
You have to check "public" in sharex g photos settings pane

**Comment by stjema** [comment]
> You have to check "public" in sharex g photos settings pane

no. that leads to creating a album for every pic you upload.

**Comment by lucario** [comment]
That’s just how google photos works.
