### ISSUE TITLE
Suggestion: Add functionality "restart recording" from screen recording tray icon

### ISSUE THREAD

**Issue by carlos-cadu** [ShareX/ShareX#4142]
Hi,

ShareX has already the handy option "Task: Start/Stop screen recording using last region".

The suggestion to add the functionality "restart recording" from screen recording tray icon would be an extension of the mentioned option, to make it more explicit, intuitive and easier accessible for the user.

Thanks for considering the suggestion,
Carlos

![ShareX_Tray icon_2019-05-24_21 15 49](https://user-images.githubusercontent.com/17261157/58362353-766e0400-7e6c-11e9-8742-935be9396213.png)

**Comment by carlos-cadu** [comment]
Hi. Just following up, hoping that "Add functionality 'restart recording' from screen recording tray icon" could be implemented at some point.
Thank you!

**Comment by carlos-cadu** [comment]
Hi. Just following up. Any chance of having this feature improvement?
Thank you!

**Comment by skeddles** [comment]
This is a desperately needed feature. When I'm recording gifs, it almost always takes a few tries to get it right. Which means what I have to do is 

- right click icon, 
- capture > screen recording gif
- select area
- record gif
Then when I realize I need to start over, I have to hit abort, then do the whole thing over again, including selecting the specific area. And I usually end up doing it 5 times, which makes it very tedious.

It would be so much easier if there was just a reset button which kept the same selection without me having to draw it again and again.

I would just like to add to OPs post that it shouldn't just be on the tray icon, the on screen buttons when recording in a smaller area need it too.

**Comment by skeddles** [comment]
!badbot

**Comment by skeddles** [comment]
CAN YOU NOT
