### ISSUE TITLE
Many open windows when computer wakes up

### ISSUE THREAD

**Issue by einarmagnus** [ShareX/ShareX#4143]
When I start my computer after it's been off for some time there are often (maybe always, but I'm not sure) several dialogs open from ShareX:

![image](https://i.imgur.com/rfkrMVr.png)

There seems to be nothing related in the debug log.

I'm using an MS Surface Pro 6 with win 10.0.17763.503

**Comment by Jaex** [comment]
I thought somehow your hotkeys getting triggered when after capture tasks -> show quick task menu is enabled but you telling those hotkey tasks not even show up in debug log, so I have no clue then how this can happen.
