### ISSUE TITLE
Capture windows client area only

### ISSUE THREAD

**Issue by Tragen** [ShareX/ShareX#4144]
I would love to see the feature added to capture only the client area of a whole window.
IrfanView has this feature and we use it always for our documentation so that we have consistent screenshots regardless of the used theme.
But we would prefer to use ShareX which we use 99% of the time.

![image](https://user-images.githubusercontent.com/1700241/58383399-87d31f80-7fd6-11e9-834a-6a4f38aef417.png)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2019/05/ShareX_EmpAFjGXHr.png)

**Comment by Tragen** [comment]
Thank you very much.
