### ISSUE TITLE
[potential feature] Support for trusted timestamping of screenshots?

### ISSUE THREAD

**Issue by beppe9000** [ShareX/ShareX#4147]
I don't have an actual use case for myself yet I think it could be a cool feature.
 
https://en.wikipedia.org/wiki/Trusted_timestamping

The downside is that it does not prevent tampering (I could press F12 and have you reply me anything, then screenshot)... it only guarantees that a specific version of a file existed at a specific time, regardless of its authenticity.

**Comment by vatterspun** [comment]
I can definitely see reasons to put this together for legal documents and digital signatures, but not sure I can think of a reason for a screen capture tool.

**Comment by beppe9000** [comment]
Despite that (*) I think it's a pretty simple thing to implement... if there is support for plugins that can define additional tasks after upload or capture I can develop it externally when I revisit this in the future.

* one could say that a dns changer is out of scope in a screen capture tool ;)

**Comment by vatterspun** [comment]
> one could say that a dns changer is out of scope in a screen capture tool ;)

Yeah makes sense

**Comment by beppe9000** [comment]
.

**Comment by beppe9000** [comment]
bot

**Comment by vatterspun** [comment]
Found a possible workaround on a similar project: https://github.com/NickeManarin/ScreenToGif/issues/444

**Comment by beppe9000** [comment]
..

**Comment by beppe9000** [comment]
:|
