### ISSUE TITLE
ftp/sftp/ftps slow upload

### ISSUE THREAD

**Issue by foooon** [ShareX/ShareX#4148]
I am getting fluctuations in my upload speed when using ftp/sftp/ftps. Myself and a friend in a different location have tested with 3 different hosts and its all the same. Starts at around 1MB/s, ramps up to my max upload speed (at around 8MB/s), and then drops sharp down to 400KB/s, and starts ramping up again.

If I use any ftp client, I cap my upload speed instantly and it stays steady. If I use file hosts in sharex (like mediafire), I also cap my upload  and it also stays steady.

**Comment by cyperdark** [comment]
same here, any solution

**Comment by WinterPhoenix** [comment]
INSANELY slow. I can pull 8-9 MEGAbytes/second with FileZilla and top out at 300 KILObytes with ShareX. Please fix this.
