### ISSUE TITLE
Firebase Shortened URLs don't appear in Firebase dashboard

### ISSUE THREAD

**Issue by thethomasjfellows** [ShareX/ShareX#4150]
I am able to automatically create short Firebase URLs after taking a screenshot but the URLs don't show up in my Firebase dashboard. I would like to keep a list there and track results. 

Here is a video of the issue: https://qfido.dubb.com/v/Bc1kOy

 Thanks for any tips.

**Comment by lucario** [comment]
Firebase Dev here. Unfortunately it seems that it’s a limitation of the API, generated URLs as used in sharex, don’t appear in the dashboard. If this changes in the future I will ensure it gets added to sharex.

**Comment by thethomasjfellows** [comment]
Thank you for the reply. Is there a way to get a notification immediately
when someone clicks my link if I make it in the dashboard?
Thomas
