### ISSUE TITLE
Possible set position of annotation toolbar on the bottom of the screen (default appears on top)?

### ISSUE THREAD

**Issue by carlos-cadu** [ShareX/ShareX#4151]
Hi,

I'd appreciate help.
The default position of the annotation toolbar is on the top of the screen.

Considering my ShareX isn't set to dim the screen when annotating, overall the annotation toolbar overlaps the software UI being captured.

Actually, I've been using Sharex during webinars to annotate content on the screen, saving the snapshot to send later to the participants. Because of that, I can't dim the screen indeed, and the top annotation toolbar overlapping the software UI is an issue to my audience too. 

Is it possible to set the position of annotation toolbar to appear ALWAYS on the bottom of the screen, as shown in the snapshot attached?

Ps.: In the snapshot, the annotation toolbar is over the Windows taskbar. If this overlay is not possible, anywhere on the bottom of the screen would fit perfectly.

Thank you very much,
Carlos

![ShareX_2019-05-29_20 09 13](https://user-images.githubusercontent.com/17261157/58642647-25c73280-82d4-11e9-8792-95dfdf04ec7d.png)

**Comment by Jaex** [comment]
You can use this option to save toolbar position:

![](https://jaex.getsharex.com/2019/05/ShareX_aTWHc1xGUT.png)

**Comment by carlos-cadu** [comment]
Perfect. Everything I needed!
Congrats for the development of so handy and flexible tool!
