### ISSUE TITLE
Upload Error 6.1.19

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#4154]
Can someone interpret this for me?  I am not able to upload an image.

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings

Status code:
500 InternalServerError

Headers:
Connection: keep-alive
Content-Security-Policy: sandbox; frame-ancestors 'none'
X-Dropbox-Request-Id: bdd64668f61d468ec7772ba9fc6b40da
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Content-Disposition: attachment; filename='error'
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Sat, 01 Jun 2019 22:10:36 GMT
Server: nginx

Response text:

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

**Comment by SC2Mitch** [comment]
> Internal server error
It's Dropbox's issue, not ShareX.

**Comment by jdcollier1968** [comment]
Thanks
