### ISSUE TITLE
Split recorded video files

### ISSUE THREAD

**Issue by kidmar** [ShareX/ShareX#4157]
Hi.
I need to record a long session (a few hours) so I would like to split video every X minutes.
I foud that it is possible to do it using custom ffmpeg commands:
-f segment -segment_time 00:00:05

To make it work I also have to edit the output file name from "$output$" to something like "$output$_%03d.mp4".
This way I'm telling ffmpeg how to name splitted files.

Is there any way to change output variable without flagging "Use custom commands"?
It would be very useful to have a parameter to manage this option (both output file name and split time).

My resulting ffmpeg command is this:
`-y -rtbufsize 150M -f gdigrab -framerate $fps$ -offset_x $area_x$ -offset_y $area_y$ -video_size $area_width$x$area_height$ -draw_mouse $cursor$ -i desktop -f segment -segment_time 00:30:00 -c:v libx265 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart "$output$_%03d.mp4"`

**Comment by vatterspun** [comment]
I don't think that's something that will get added based on issues #3818 #2865
