### ISSUE TITLE
[Feature Request] An option to disable space character replacement

### ISSUE THREAD

**Issue by zfs2019** [ShareX/ShareX#4159]
I use a window title (%t) to automatically tag the contents of a screenshot.
If a filename contains space, it will be replaced with an underscore, this can be hard to read and looks like a bit longer (See the attached image.)
This may be a personal preference, so it would be nice to have an option to disable that replacement.

![Screenshots](https://user-images.githubusercontent.com/48113574/59002154-739be780-884c-11e9-9794-67c1679a1c33.png)

**Comment by matthew-e-brown** [comment]
This doesn't look too complicated to add. It seems to be a small tweak to these two blocks:

https://github.com/ShareX/ShareX/blob/19369ac2457d448f63e8706df0bdde8499ea7fec/ShareX.HelpersLib/NameParser/NameParser.cs#L84-L98

I'm not sure what the repercussions are to swapping underscores back with spaces, though. I doubt it was done without reason. Possibly some issues with uploads?

**Comment by zfs2019** [comment]
> 
> 
> This doesn't look too complicated to add. It seems to be a small tweak to these two blocks:
> 
> https://github.com/ShareX/ShareX/blob/19369ac2457d448f63e8706df0bdde8499ea7fec/ShareX.HelpersLib/NameParser/NameParser.cs#L84-L98

Yeah, it seems to be. I would do it myself and make a PR if I had time.

**Comment by matthew-e-brown** [comment]
I'll start to take a look at it tomorrow after my midterm. Just need to figure out this source-code enough to properly add a settings option for it.
