### ISSUE TITLE
Uploading existing file causes local overwrite

### ISSUE THREAD

**Issue by WeaverThree** [ShareX/ShareX#4163]
If I save a screenshot without uploading, and then want to upload later, I get the 'file overwrite' prompt as if I dragged a new copy of the image into the window.

What I expect to happen is for the file as is to be uploaded and its url information added to the history record for it.

I can't just enable 'overwrite' or 'do not save' on all because there will be problems when I drag and drop files into the sharex window-- like all those 'unknown.jpg' that come from discord >.>. I want that dialog to pop when there's an /actual/ duplication issue, but not when i'm just uploading a file that hasn't been uploaded before.

**Comment by Jaex** [comment]
If I save screenshot then right click Upload, I don't see overwrite prompt.
