### ISSUE TITLE
is there a way to make a guaranteed unique file name?

### ISSUE THREAD

**Issue by hiitsdan** [ShareX/ShareX#4165]

**Comment by Mosrod** [comment]
Task Settings > Upload(File Naming) > Name Pattern for capture or clipboard upload > Put %unix
this will get the current date and is always going to be unique

**Comment by hiitsdan** [comment]
thank you, is there a way to see all the options for the % things if you get what I mean, like all the replacements

**Comment by Mosrod** [comment]
Click in the text area and it will show you all of the possible placeholders you can use
![image](https://user-images.githubusercontent.com/18247709/59392828-18d02780-8d47-11e9-9f0e-ff14d9c99150.png)

**Comment by hiitsdan** [comment]
perfect, thanks a lot
