### ISSUE TITLE
No audio sources available in dropdown Task Options -> Screen Recorder -> Screen Recorder Options...

### ISSUE THREAD

**Issue by petrj10** [ShareX/ShareX#4166]
I have audio on my dell laptop. I use Windows 10 Pro 1809.
But the options drop down stays blank, even after reboot., Please advise.
![image](https://user-images.githubusercontent.com/51699731/59259205-9b6ac100-8c39-11e9-94f2-a27af84a1ff9.png)

**Comment by Mosrod** [comment]
Click install recorder devices
![image](https://user-images.githubusercontent.com/18247709/59388272-604fb700-8d39-11e9-8722-9a11253f0c5d.png)

**Comment by Markxxx7** [comment]
the same thing is happening to me even if I install recorder devices. Any fixes yet?

**Comment by turrithugger** [comment]
I have the same problems, I tried installing the recorder devices three times and nothing happened

**Comment by Mosrod** [comment]
@turrithugger Could you please send me a screenshot of your Screen recording options page?

**Comment by turrithugger** [comment]
[click me](https://gyazo.com/da6b96d0f8176a1df76600f36b6e83c2)

**Comment by Mosrod** [comment]
@turrithugger In video-source and audio-source, could you select the recorder devices, or are they not available?

**Comment by lu-as** [comment]
Sorry for reopening this issue. But I had the same problem and after hours of searching found the solution.
In the above screenshot "FFmpeg path" is red, indicating FFmpeg was not yet installed. Click download. FFmpeg will be installed, "FFmpeg path" will turn green. After this, the recording devices you are looking for will be available.
Hope this helps...
