### ISSUE TITLE
Sharex doesn't open

### ISSUE THREAD

**Issue by theidolfriend** [ShareX/ShareX#4168]
for some reason i get this message every time i try to open it and then when i press ok it says that stop working
System.ArgumentException: El parámetro no es válido.
   en System.Drawing.Font.GetHeight(Graphics graphics)
   en System.Drawing.Font.get_SizeInPoints()
   en System.Drawing.SystemFonts.FontInPoints(Font font)
   en System.Drawing.SystemFonts.get_MenuFont()
   en System.Windows.Forms.ToolStripManager.get_DefaultFont()
   en System.Windows.Forms.ToolStripItem.get_Font()
   en System.Windows.Forms.ToolStripItem.SetOwner(ToolStrip newOwner)
   en System.Windows.Forms.ToolStripItemCollection.SetOwner(ToolStripItem item)
   en System.Windows.Forms.ToolStripItemCollection.Add(ToolStripItem value)
   en System.Windows.Forms.ToolStripItemCollection.AddRange(ToolStripItem[] toolStripItems)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 12.4.1 (Release)

**Comment by Mosrod** [comment]
Have you tried reinstalling ShareX?

**Comment by theidolfriend** [comment]
Yes, i got the same error
