### ISSUE TITLE
[Suggestion] ShareX settings stored in Dropbox, different config files per computer (simultaneous access and redundant log files)

### ISSUE THREAD

**Issue by Zcehtro** [ShareX/ShareX#4169]
I use multiple computers (work, personal, etc.) and I have ShareX installed on all of them.

On all computers I also have Dropbox installed and My Documents folder is located within it. This causes a slight problem with the log files ShareX creates. Every time I start my user session in Windows, ShareX starts and finishes loading before Dropbox and creates the pertinent logs, then Dropbox starts and finishes syncing the log files from the other computers and starts creating duplicate files with sync conflicts. These sync conflicts are the files from the other computers.

Also, ShareX settings aren't stored properly when I have more than one user session open because all computers are accessing the same config file in my synced Documents folder.

I tried creating separate config files for ShareX within Dropbox but I never could get each computer to recognize its own config file, they always ended up sharing the same config.

Is there a way to have ShareX running separately on multiple computers?

**Comment by Mosrod** [comment]
Go to Sharex > Application settings > Paths > ShareX personal folder: > Click browse and choose a folder outside of your documents.
![image](https://user-images.githubusercontent.com/18247709/59465884-edf2db80-8df9-11e9-90b7-9534b73fbcf9.png)

**Comment by Mosrod** [comment]
If you wanted to keep all of the screenshots synced, check use custom screenshots folder and find a folder inside your documents.

**Comment by Zcehtro** [comment]
Hi! Thank you for replying and I apologize for coming back so late to this, it's been almost a month, my bad.

I was already doing this before, but it doesn't work.
The reason, I suspect, is because when I change the setting for the ShareX Personal Folder, it created a file in My Documents\ShareX called PersonalPath.cfg.
The contents of this file is the new destination folder for the Personal Folder.

So, this doesn't really fix the problem in the OP if I have My Documents folder within my DropBox/One Drive/GoogleDrive/etc. because every computer will get the same destination for the ShareX Personal Folder becuase of the cloud syncing.

**Comment by Jaex** [comment]
You can move PersonalPath.cfg file near ShareX.exe that way it will read it from there instead of documents folder.

**Comment by hikaritenchi** [comment]
I'm not sure this is an option for the Windows Store version of ShareX, since `ShareX.exe` is in the WindowsApps folder, which isn't modifiable by users.
