### ISSUE TITLE
Can't save recording small area as gif

### ISSUE THREAD

**Issue by MilanRS** [ShareX/ShareX#417]
Steps to reproduce:
1. execute shortcut to record as gif
2. mark small part of screen (ex. smiley)
3. try to press Save. It is not visible.
http://i.imgur.com/NHKzJVP.jpg

Sharex is great app, I use it every day. Thank you.

**Comment by Jaex** [comment]
Fixed it: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/qJX0PHcP6g.png)
