### ISSUE TITLE
Pressing "4" key closes the editor window and throws away edits

### ISSUE THREAD

**Issue by munrobasher** [ShareX/ShareX#4170]
In this example, I have edited a screenshot and added some text. If I press the "4" key (which I did by mistake), it simply closes the window throwing away edits.

![image](https://user-images.githubusercontent.com/13134946/59507704-bccee580-8ea3-11e9-8d7a-0e796ff02277.png)

**Comment by CubityFirst** [comment]
Not a bug as far as I can tell, it seems like from my limited testing that each of the number keys are aliased to the first X keys in the top bar.

https://i.cubityfir.st/kwCkcbCa9k

7th option is upload, if i click 7, it'll upload the image, if I cancel (3), it'll cancel, etc. 
4 is Save, so it seems like it'll just save the image, and run no other tasks.

https://i.cubityfir.st/MVsSYGX6uj Task log after testing
https://i.cubityfir.st/p9AdFkrPvy Debug log, it just seems like it's saving and then not doing anything else.

**Comment by munrobasher** [comment]
For me, 1-4 simply throws away all edits and closes the editor window. No saving going on. Got bored after getting to "4" :-)

**Comment by Jaex** [comment]
It happens because those number keys execute specific monitor capture in region capture mode. It should have been disabled in image editor mode.

**Comment by munrobasher** [comment]
Bit confused by this been closed? Has it been flagged elsewhere as a bug? Because they are not disabled in image editor mode?

**Comment by Jaex** [comment]
I fixed it so issue is closed automatically.

**Comment by munrobasher** [comment]
Ahh gotcha - wow, that was fast 👍
