### ISSUE TITLE
Loading settings programmatically from the outside?

### ISSUE THREAD

**Issue by ffMathy** [ShareX/ShareX#4172]
If I make my own Visual Studio solution with a Windows Forms project, reference all ShareX projects by adding the ShareX `csproj` files as existing projects and run the following code:

```
RegionCaptureTasks.GetRectangleRegion(out var rectangle, GetRegionCaptureOptions());
ScreenRecordManager.StartStopRecording(ScreenRecordOutput.FFmpeg, ScreenRecordStartMethod.CustomRegion, new TaskSettings()
{
    CaptureSettings = new TaskSettingsCapture()
    {
        FFmpegOptions = new FFmpegOptions()
        {
            VideoCodec = FFmpegVideoCodec.libvpx,
            VPx_bitrate = 2000
        },
        CaptureCustomRegion = rectangle
    }
});
```

Then it fails because `Program.Settings` is `null` (null reference exception). However, `SettingManager` and `Program.Settings` are `internal`, so I can't access them from my project.

Saving images works just fine, but I need video capture functionality as well in my application.

Can we make the `SettingManager` exposed to the outside (making it public), or perhaps make `Program.Settings` public instead?

I made a PR for my proposal of fixing the issue.

**Comment by ffMathy** [comment]
It should be noted that this isn't a bug per-se in the software itself, it is just a thing that makes it impossible for anyone to reference ShareX in their code for the sole purpose of capturing video more easily.

And I think open-source software should permit that kind of stuff.

**Comment by juventus18** [comment]
you said you made a PR, why not just compile your PR and reference that instead of sharex?

**Comment by ffMathy** [comment]
Because I would like to continually get new ShareX updates easily, so I referenced it as a submodule.

I honestly think that it would be very powerful for other libraries to reference ShareX the way I'm doing it :)

**Comment by ffMathy** [comment]
Not stale.
