### ISSUE TITLE
error issue

### ISSUE THREAD

**Issue by idblock** [ShareX/ShareX#4176]
System.NotSupportedException: Le format du chemin d'accès donné n'est pas pris en charge.
   à System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   à System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   à ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   à ShareX.ApplicationSettingsForm.txtSaveImageSubFolderPattern_TextChanged(Object sender, EventArgs e)
   à System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   à System.Windows.Forms.Control.set_Text(String value)
   à System.Windows.Forms.TextBoxBase.set_Text(String value)
   à System.Windows.Forms.TextBox.set_Text(String value)
   à ShareX.ApplicationSettingsForm.UpdateControls()
   à ShareX.ApplicationSettingsForm..ctor()
   à ShareX.MainForm.tsbApplicationSettings_Click(Object sender, EventArgs e)
   à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   à System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ToolStrip.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.4.1 (Steam)

**Comment by L1Q** [comment]
What were you trying to do right before this happened?

**Comment by Jaex** [comment]
I think while fixing this issue #2359, this issue also should be fixed.
