### ISSUE TITLE
Scroll capture cuts off too much 

### ISSUE THREAD

**Issue by Metazolid** [ShareX/ShareX#4186]
The scroll capture function is inconsistent, sometimes capturing all website elements and binding the images together corrently but other times, it refuses to do so, basically keeping only one image  and stuffing all 99 beneath it.

**Comment by CollinChaffin** [comment]
I didn't even see this I just commented on an older open issue #4162 see my comments/screenshots there that also demonstrate just how much ShareX is discarding compared to another app (Snagit) on scrolling captures. Scrolling captures seem to be ShareX's Kryptonite.
