### ISSUE TITLE
Feature Request: Synchronize all Settings with other devices

### ISSUE THREAD

**Issue by johmarjac** [ShareX/ShareX#4196]
Hi,

I am using two Desktops. I have one at home, and I have one at work and both I am using this AWESOME tool (Thanks for that). However, it would be cool, if some kind of Settings Synchronization would be possible. Like I add a new Hotkey Setting on my Work PC, so I get it on my Home PC too. U know what I mean?

What do you think?

**Comment by Azhe403** [comment]
Up

**Comment by burdoto** [comment]
Bump
