### ISSUE TITLE
After Upload: create custom HTML clipboard with the upload link

### ISSUE THREAD

**Issue by MagTun** [ShareX/ShareX#4199]
Currently, after I use ShareX to upload an image, I run a python script that retrieves the clipboard content, embeds it into an HTML `img` tag and send this code to my clipboard as HMTL format so I just have to press <kbd>CTRL+V</kbd> to paste it in my HTML editor (TinyMCE).

That would be great if ShareX would integrate a similar feature so that we could do all this from within ShareX. For example, an option in the `After Upload` could provide a "custom" field where the paths would be easily available (maybe with wildcard) to create a custom HMTL code. 

If needed, I use this [python script ](https://github.com/MagTun/Zotero_Pdf_Highlights_with_HtmlClipboard/blob/master/HtmlClipboard.py)to send HTML format Clipboard

**Comment by Jaex** [comment]
You can customize clipboard content from here:

![](https://jaex.getsharex.com/2019/06/ShareX_gA7xMkIVh1.png)

Or add context menu entry from here:

![](https://jaex.getsharex.com/2019/06/ShareX_JsyiH1sRGW.png)

**Comment by CaterpyOwO** [comment]
xd

**Comment by MagTun** [comment]
Sorry I haven't seen this option. I was able to create the custom clipboard content but not to get the clipboard as HTML format. 
The HTML format allows me to paste the link not in the source code like `<img src="https://i.imgur.com/xxx.png" alt=""  width="200px">` but directly in the "rendered" part of a HTML editor. 

HTML format clipboard has special  header like:  

        "Version:1.0\r\n" \
        "StartHTML:%09d\r\n" \
        "EndHTML:%09d\r\n" \
        "StartFragment:%09d\r\n" \
        "EndFragment:%09d\r\n" \
        "StartSelection:%09d\r\n" \
        "EndSelection:%09d\r\n" \
        "SourceURL:%s\r\n"
