### ISSUE TITLE
Feature Request: Email to...

### ISSUE THREAD

**Issue by Dubz** [ShareX/ShareX#4202]
My coworkers would like to have an email to button available in the after capture tasks. I personally just click copy and paste it in an email (so my signature and such is included), but they would rather have an email button to save the step.

They currently use Windows' snippet tool over this because of that one feature (and they don't care to look into all the configurations for ShareX). I think they'd like this better though because of the better editing tools. They make the screenshots look so much cleaner than a doodled version done with Snippet Tool.

**Comment by Somethingweirdhere** [comment]
#3894 would fix that
