### ISSUE TITLE
Can multi-region screenshots be saved as multiple files?

### ISSUE THREAD

**Issue by qq492269704** [ShareX/ShareX#4206]
Can multi-region screenshots be saved as multiple files? Very Thankful!!!

**Comment by michaeltamilio** [comment]
I am wondering the same thing?

**Comment by dasebasto** [comment]
It would be a nice feature.

**Comment by stdedos** [comment]
Not necessarily that; however, I'd like to be able to have a mode that I work with one screenshot still, and I can use it multiple times until I dismiss it.

Maybe there is too much happening at the screen, and all the stars aligned, for 3 different things.

I could just save it all and then use the Image Editor; however, for full screen features (or even worse, multi-screen setups), the Image Editor is lacking "the power" to be able to use your full monitor setup as its canvas.
The way the scroll bars work is also a bit disappointing 😕

**Comment by shodanx2** [comment]
This issue is related to #1052
