### ISSUE TITLE
need better integration of the newer google API due to album issues. 

### ISSUE THREAD

**Issue by bajungadustin** [ShareX/ShareX#4212]
Due to the fairly recent changes in Googles API... Sharex no longer uploads to a specific album. I can sometimes get my album list to show but no matter what i do it creates a new album with every single screenshot. (public upload is on)

I have tried selectin the album from the list when it pops up...
I have tried creating an album with the option in the settings
I have tried leaving it blank because it says this wont put it in an ablum
I have even tried copying the album ID out of the web address

But every picture i take still creates its own album instead of going into my predesignated "Screenshot" album like it used to. 

I now have over 700 albums that have no pictures in them (i deleted / moved the images)
And i not have to delete 700 albums at 3 clicks each requiring 2100 clicks and a massive amount of time due to this issue. [Example](https://photos.app.goo.gl/VHRHuoWLsuYpnu326)

This isnt how google photos is supposed to work... It used to upload to the specific album selected. As an example.. then i take a screenshot on my phone it uploads to the screenshot album.. So something with Sharex is causing an issue to make it create an album every time I take a screenshot.

**Comment by lucario** [comment]
The new API no longer allows direct shareable links to images, so public upload simply create a single shared album for the image. There’s unfortunately no way to restore the same functionality the Picasa API provided. If the new API is updated to support this, I will update it. Other API limitations means ShareX can no longer upload to user created albums. ShareX can only upload to ShareX created albums. 

All these changes by Google has made GPhotos difficult to use with sharex, we recommend moving to Google Cloud Storage which is supported in ShareX.
