### ISSUE TITLE
Google Photos uploads no longer display pics when linked

### ISSUE THREAD

**Issue by bajungadustin** [ShareX/ShareX#4213]
Previously before the google API update a while back the link that was copied to the clipboard when using a google photo upload would pop up with the picture when used in things like facebook messenger or in image links on forums. 

Now instead it gives you this. [Example](https://lh3.googleusercontent.com/dNrFj3QsKtQmBcVXoK5h1u2pcYPYgvEJAEwa0Dj2JdH0SgLTlC0xajEdDCkXQZuA3KBokBZIjrHTLEciQhC0thPCTE_EDeLRodIYI7K0IIlsKHhhz-8qlfA4Ll6JHeVLvAxylYmaSCdvnmUuuqqcwUYX03N4SGErL2dkCQbVnt17BR8Bk7WUl76mHKNhDxurHSSboIWxEwphRVzlbZvBPK6z7AiOmvJNj0dyMbq4WzM4T63Su7UAEINmpGqUSJoMmeuoVFp9Ze1WXK_QrqApQ0xzuyN4-knekoUoWG8AHggH1xCvasMgtY0Bl5I0dzkMdnJUZTG5yyyUalb4ZqcQYcjRwuUTSvCU_NlCRZd-TLugNfw76t4roxuE-aKFO7LB2DgjlYb7QHZ5ldPTuvBdZ8voZiJM_wAiFz_Z61rISUl0Kb2CnnEgc0RSyxfHpMVvpzp18POIp1lLJmw2FPiXm9dLvDvK_JSUbMgfe3fkju9Q79xF7Vyf7TYgtakaonbgHQeu5cFMQvqjFsk1Hp9XmFlB9Pmg0OF7gnWRUpt7LG22MH6-dM-TCfAABInaWR5CRkAlF1KQ_974QhqczHrec2NgOV-xG-bG5x6P2EEa3OWPbAZsUzSJctBspxTS3VsnZ7VueGpJnZWUNdjpZzOujh0GxPDOyEHIUlVsNtidiTDdxAnggXtfAk4EdAEa9H59ZvASyHw0rxAQEa27ZtB8TSrbiA=w635-h167-no)

Before you could let the link populate the pic and delete the link and just uplaod the image. It was honestly the best thing about the entire program.. Now it requires me to paste the link in a browser.. then open the link to the image in new tab.. then open image in new tab.. then copy the massively long link and paste it... a process that before didnt require any of this. 

Public Upload is checked

**Comment by lucario** [comment]
#4212
