### ISSUE TITLE
Disable update check globally

### ISSUE THREAD

**Issue by snok87** [ShareX/ShareX#4219]
I deploy Sharex to computers where users havent administrative rights, it would be nice something like a regkey in HKLM to disable update checks.

**Comment by Jaex** [comment]
You can only disable updates like this:
![](https://jaex.getsharex.com/2019/07/ShareX_sFnnyBdgMQ.png)

**Comment by snok87** [comment]
I know i can disable it that way, but in a enterprise that you have 600 computers and computers are multiusers you cannot deploy the app with updates disabled. Imagine users calling to support center telling that they are viewing every day a popup telling something about update.

**Comment by gituser** [comment]
@snok87 all settings of ShareX by default are stored at: 

```
@echo off
for /f "tokens=3*" %%p in ('REG QUERY "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v Personal') do (
    set DocumentsFolder=%%p
)
echo %DocumentsFolder%\ShareX\ApplicationConfig.json

```
You can edit this file with powershell or any other way and change there setting:

```
...
  "AutoCheckUpdate": false,
...
```

**Comment by snok87** [comment]
Computers are multiusers, how can i execute a powershell on all profiles?

**Comment by snok87** [comment]
For example, in Notepad++ it works that way:

open %APPDATA%\Notepad++ in explorer
copy the file config.xml to %ProgramFiles%\Notepad++
(note: the path is %ProgramFiles(x86)%\Notepad++ for the 32 bit version)
and rename it to config.model.xml

and then config.xml is generated using as template the file config.model.xml

**Comment by gituser** [comment]
@snok87 ask @Jaex for a feature request. I don't think currently there is any way to control settings globally for all users. Not sure though as I did not study ShareX source code.

Or you could send a pull request with this functionality.

**Comment by snok87** [comment]
I dont know how to ask to Jaex or send a pull request, how can i send a message to him?

**Comment by gituser** [comment]
Explain in this issue what is exactly you want to implement and how.

Pull request is the source code changes request which implements the change.

**Comment by snok87** [comment]
I want a KEY on HKLM\Software\ShareX with a value DisableUpdates
If you set that value on 1, by default all users have disabled updates.

**Comment by snok87** [comment]
We havent a key to disable updates globaly yet.

**Comment by jpsv** [comment]
A command-line switch to disable update checks during install would satisfy a lot of people. Along with an option to disable upload by default:

`/VERYSILENT /DISABLEUPDATECHECK /UPLOADOFF`

**Comment by snok87** [comment]
We still need an option like that.

**Comment by LeeViewB** [comment]
Hi everyone,

I am able to disable the check for updates, plus other Application settings. Please note that these settings are saved in C:\users\%username%\Documents\ShareX\ApplicationConfig.json
I installed the app, took that json file, opened it with notepad++, set   "AutoCheckUpdate": false, saved it (you can make other setting changes).
Then I used the PSADT to install the application, then copy the json file for each user profile on the computer (this is necessary because the installation via ConfigMgr takes place under the SYSTEM account, but you want to copy the file in the local user profile). 

Here is a link to the [Paste Bin](https://pastebin.pl/view/ca947bf6) script of how I am doing this using the PowerShell App Deployment Toolkit.

**Comment by snok87** [comment]
Yes it work is some environments, you can just use powershell without any kind of tools to do the same. The problem appears when you start using VDI that autodestroy at night with folder redirection and you delete a user profile that is corrupted. 
I have tried several options and at the end you still have issues. Thats why i asked for a global disable option.

**Comment by KazuyDarklight** [comment]
Just here to fend of the stale bot, I think this has a lot of value, in particular @jpsv 's suggestion of install parameters.  I think that would honestly be perfect and I'd love to be able to install with the upload option off by default since our users have no need for it normally.

**Comment by Jaex** [comment]
I added disable update check in here: #5857
Also disable upload added by @Erik3003 in here: #5822

Let me know if this registry solution fits to your needs.

**Comment by Jaex** [comment]
Example registry:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\ShareX]
"DisableUpdateCheck"="true"
"DisableUpload"="true"
```

**Comment by Jaex** [comment]
There is two more places related to updates. About window have update check label and application settings have "Install dev build" button. These two places should disable with this flag too right?
