### ISSUE TITLE
Animated gif - timer and stop button not display

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#422]
If the captured selection is small then the timer and stop button do not appear when creating animated gif.
I like to keep the capture as small a possible to keep the file size low for storage and uploading.
Also do not want to include anything else on the capture that is not needed, so making it a bigger capture is not a solution.

-- Is there a way to make timer and stop button always appear even when the capture is small?
Like move vertically underneath the abort button? Or some other position or solution?
-- And also maybe color red one of the buttons stop or Abort for quick distinction.
Thankyou.

![sharex animated gif time not display](https://cloud.githubusercontent.com/assets/8550969/5563060/0e051c9a-8e08-11e4-824d-903d463e5a41.PNG)

![sharex animated gif measurements appear](https://cloud.githubusercontent.com/assets/8550969/5563032/401b3036-8e06-11e4-9c73-8aa353e2d012.gif)

**Comment by gotquestions** [comment]
I don't know javascript and don't know how to fix it.
Jing and other programs do like this:

![jing controls appear with small capture 2](https://cloud.githubusercontent.com/assets/8550969/5595570/8275ab90-922b-11e4-8a69-0e7a4b00d0a5.PNG)

**Comment by Jaex** [comment]
You can use Jing.

**Comment by gotquestions** [comment]
What kind of an answer is that?

ShareX is an open source program and should not have any problems.
When problems/bugs are presented, then they should be answered with a solution or a fix.
This is a forum where problems are to be reported, discussed, resolved, and not told to use another program.

The timer does not appear with small selected capture and you said you didn't know how to fix it. 
The problem is still there even though you don't know how to fix it.

Without a fix to the problem then this thread should be kept Open and not Closed.

**Comment by Jaex** [comment]
If you don't like what exists in ShareX then you can use other software which you prefer.
If stopping recording was not possible then it should be resolved but it is possible to stop so it is not big deal and I don't wanna waste my whole day to fix it. Just so you don't wanna use hotkey. You reporting it like I didn't know while programming it... I was aware of it and it was too much job and not big deal so I decided to not handle it. Why would I not close issue, who gonna fix it anyway?

`ShareX is an open source program and should not have any problems.`

What is that even means? It is opposite. Paid apps have more reason to fix their issues because it worths it. Because they earn good money from it. But I don't earn anything so I got bored working for 7 years. People still prefer to use other bad paid screenshot softwares and I can't even manage to find more users to ShareX. So I don't care about this little issues anymore.

**Comment by gotquestions** [comment]
My previous post was regarding the **TIMER** count.
And I explained in my first post the reasons why displaying timer count is important.

![sharex timer](https://cloud.githubusercontent.com/assets/8550969/5602230/dc2f6ffc-92f5-11e4-9ae8-9a825bd9fbff.PNG)

**Comment by Jaex** [comment]
Fixed it: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/qJX0PHcP6g.png)

**Comment by gotquestions** [comment]
Good thinking. Good job. **Thankyou very much** Jaex !
You could also add an **OPTION** to **use icons** instead of text, with less width padding 
for the Start/Stop/Abort sections like this:

![sharex default animated gif control panel](https://cloud.githubusercontent.com/assets/8550969/6201639/b27b620c-b469-11e4-91ab-2a3ab589989d.PNG)

![sharex control panel icons reversed](https://cloud.githubusercontent.com/assets/8550969/6201614/28982de0-b469-11e4-97cf-4d8127851e4c.PNG)

**Comment by Jaex** [comment]
That icons will make confusion between stop and abort. People won't know which one stops.

**Comment by gotquestions** [comment]
Stop could be this but proper size. And keep the Abort X icon.
You could also have a tooltip when hover to state text of button.
But less width padding for the Start/Stop/Abort will make a big difference with total width.

![stop sign red transprt bg cropped darkgrey extra remove white border grey to red to post replaced text 4 right blur](https://cloud.githubusercontent.com/assets/8550969/6201652/d25ef718-b46a-11e4-9cfd-029c1a14e8f9.png)

**Comment by gotquestions** [comment]
![stop smilie animated](https://cloud.githubusercontent.com/assets/8550969/6201686/37bef1ec-b46d-11e4-9435-432c749c380d.gif)

![sharex big stop sign 20pxw](https://cloud.githubusercontent.com/assets/8550969/6201687/515011fe-b46d-11e4-9d08-ef2eabad2808.PNG)

Abort could also be a cancel delete icon. But I like the X best.
![cancel delete disable remove tiny darkred](https://cloud.githubusercontent.com/assets/8550969/6201695/a1338aa2-b46d-11e4-8d87-73292c1186dc.png)

**Comment by gotquestions** [comment]
This is what it could look like with less padding within the Start/Stop/Abort.

![sharex default animated gif control panel](https://cloud.githubusercontent.com/assets/8550969/6201639/b27b620c-b469-11e4-91ab-2a3ab589989d.PNG)

![sharex default control panel less padding](https://cloud.githubusercontent.com/assets/8550969/6201760/28278948-b471-11e4-947a-9c69f481f765.PNG)

**Comment by Jaex** [comment]
What about other languages?

**Comment by gotquestions** [comment]
Every language must have their own stop sign, so their own language stop sign icon.
If that's too difficult
Okay then, the Start can be text and the Abort an X icon.
**See my post above**  that shows the control panel with less padding.

**Comment by Jaex** [comment]
I made that buttons big so in other language which text bigger it can be fit...

**Comment by gotquestions** [comment]
I see.
But there is not a code for width to fit text?
min-width: px !important; and max-width: px !important; ?
width: -moz-max-content !important;
IF not then I see the situation.
