### ISSUE TITLE
Can we have a hotkey for "capture region with multi region mode ON" and "capture region with multi region mode OFF"?

### ISSUE THREAD

**Issue by sevelee** [ShareX/ShareX#4220]
When using ShareX I will change between "multi region mode" on/off very often.
But I often forgot with mode I am in and the "multi region mode" checkbox is hidden in Options. So manytime I thought I was in "multi region mode" but acturly I am not. So I need to active capture mode again and check "multi region mode" then do my capture, which is very boring and ineffective.

So maybe we can have a hotkey to "capture region with multi region mode **ON**", and a hotkey to "capture region with multi region mode **OFF**"。

**Comment by Jaex** [comment]
Each hotkey can have different task settings, so you can just overwrite that option from task settings of hotkey.

**Comment by sevelee** [comment]
> Each hotkey can have different task settings, so you can just overwrite that option from task settings of hotkey.

Yes But in Task Setting now,  there is no setting for multi region mode status.
![image](https://user-images.githubusercontent.com/8036235/61204512-efc4fd00-a71f-11e9-8950-e92db0b93b4a.png)

**Comment by Jaex** [comment]
Here:

![](https://jaex.getsharex.com/2019/07/ShareX_JURyb0NoRb.png)
