### ISSUE TITLE
Location of my file on the web

### ISSUE THREAD

**Issue by Octopod2** [ShareX/ShareX#4222]
Made a  partial screenshot, saved it to Desktop, and  I chose Imgur as a host. "Upload to host" does nothing. If it did upload, it's not showing me the URL, which is the same thing.

There's no Help file with this program, but a lot fewer people would be posting here if you had created one.  A program with hundreds of options and no directions...

**Comment by Aholicknight** [comment]
Could you take a pic of the ShareX program when you took the screenshot? It should look like this:
![image](https://user-images.githubusercontent.com/7843719/61179849-3d2e5680-a5c8-11e9-8a48-3fc016b87ca9.png)
