### ISSUE TITLE
ShareX crashes & cannot be started after KB4507453 installed

### ISSUE THREAD

**Issue by takwing** [ShareX/ShareX#4226]
ShareX crashes & cannot be started after KB4507453 (2019-07 commulative update for windows 10 Version 1903) installed

**Comment by Aholicknight** [comment]
What are you specs?

**Comment by takwing** [comment]
I found that this was a false alarm.  With unknown reason, installing KB4507453 reuslt in .Net framework 3.5, 4.6.2 etc being disabled.  I had enabled that and shareX can start smoothly.
