### ISSUE TITLE
Install-level ApplicationConfig.json

### ISSUE THREAD

**Issue by mintsoft** [ShareX/ShareX#4228]
Hiya,

I'm rolling this out through auto-deployment at the moment and I want to standardise the settings for all the users. I can't find a way of achieving what I want at the moment which would be:

I want to roll out a base `ApplicationConfig.json` installed into C:\Program Files\ShareX which is basically preconfigured to point to `ffmpeg` in `C:\Program Files\ShareX\Tools\ffmpeg.exe` and disable uploading. 

I *can* roll out user-level settings and create a "My Documents\ShareX\ApplicationConfig.json" but ideally I'd like it machine-wide. 

Is this possible in a way I've not noticed? 
If not are you happy for me to implement and PR? 
If so do you have any preference as to any implementation detail?

**Comment by mintsoft** [comment]
Not my fault nobody has replied mr stale bot!

**Comment by nkronberg** [comment]
I'll second this request; this is hugely important in corporate environments who don't want confidential company information accidentally uploaded to Imgur by a stray mouse click.  Ideally the ApplicationConfig.json could be stored in a location where only Administrators of the machine could access it, and automatically override the user-level copy under Documents.  Or to take it a step further, be able to pre-define a subset of the ApplicationConfig.json file in a smaller JSON file under Program Files\ShareX, and merge the two configs so as to allow the end user to modify some settings but not others.

**Comment by mintsoft** [comment]
@nkronberg I'm happy to implement this but I was hoping for some guidance/feedback from the developers about what they thought/would want before I go gung-ho and whack out some code. 

I was thinking about implementing it as copy in: `C:\Program Files\ShareX` which would be the default settings and then have all saves of configuration go into the User's copy (`My Documents\ShareX\ApplicationConfig.json`). It would be relying on filesystem permissions so that users can't modify the global settings file in `Program Files`; however I think that would only be a problem if you have Administrator access on the machine itself which seems reasonable to me?

Out of curiousity for your use-case do you want defaults (i.e. can be overridden by the user) or enforcement? (i.e cannot be overridden, like group policy)?

**Comment by nkronberg** [comment]
> @nkronberg I'm happy to implement this but I was hoping for some guidance/feedback from the developers about what they thought/would want before I go gung-ho and whack out some code.
> 
> I was thinking about implementing it as copy in: `C:\Program Files\ShareX` which would be the default settings and then have all saves of configuration go into the User's copy (`My Documents\ShareX\ApplicationConfig.json`). It would be relying on filesystem permissions so that users can't modify the global settings file in `Program Files`; however I think that would only be a problem if you have Administrator access on the machine itself which seems reasonable to me?
> 
> Out of curiousity for your use-case do you want defaults (i.e. can be overridden by the user) or enforcement? (i.e cannot be overridden, like group policy)?

I like the idea of implementing the authoritative settings under the application's install directory under Program Files, relying on filesystem permissions as you said.  Ideally it would override any user's settings, but only the settings that conflicted.  Similar to how KeePass does it: [https://keepass.info/help/base/configuration.html](Link)

**Comment by mintsoft** [comment]
Unstale ¬_¬

**Comment by IvyUK** [comment]
This needs to happen, i can't roll this out, without it

**Comment by AdrianFletcher** [comment]
Just to bump this one, we would also love to roll this out to users but would love this feature.

What about having two different files in the root installation directory for each config file. The base file would overwrite any user specific settings, and the default file would simply be a starting point for users when they open the application for the first time?

I suppose ProgramData would be the correct location for the folder/files.

C:\ProgramData\ShareX

ApplicationConfig.json
ApplicationConfig_Default.json
HotkeysConfig.json
HotkeysConfig_Default.json
UploadersConfig.json
UploadersConfig_Default.json

**Comment by mintsoft** [comment]
@AdrianFletcher So basically it's like GPP vs GPO? The defaults are preferences, what the user gets if unset; the other file is enforced and they can't change it?

**Comment by AdrianFletcher** [comment]
> @AdrianFletcher So basically it's like GPP vs GPO? The defaults are preferences, what the user gets if unset; the other file is enforced and they can't change it?

Exactly that.

Another option might be to skip straight to supporting ADMX/InTune/Endpoint Manager configuration by reading out these settings from the software policy key/store in the registry, Something like HKLM\SOFTWARE\Policies\ShareX\Preferences. But this is a little more esoteric for users to adopt.

**Comment by mintsoft** [comment]
It's basically up to @Jaex I'm happy to implement either technique

**Comment by mintsoft** [comment]
Unstale ¬_¬

**Comment by Yokiie** [comment]
Found this issue through google and I'm having the exact same issue as OP with my company. 
I hope the dev can answer.

**Comment by IvyUK** [comment]
> Found this issue through google and I'm having the exact same issue as OP with my company. I hope the dev can answer.

i've had to rollout greenshot instead

**Comment by Yokiie** [comment]
> > Found this issue through google and I'm having the exact same issue as OP with my company. I hope the dev can answer.
> 
> i've had to rollout greenshot instead

I see, does greenshort have video screen recording like ShareX? Or did you roll it for screenshots only ?

**Comment by mintsoft** [comment]
unstale :)

**Comment by lublak** [comment]
@mintsoft I am also interested :) I have currently asked in Discord whether an implementation is desired.

**Comment by IvyUK** [comment]
Can this be uncompleted and unstaled @mintsoft

**Comment by mintsoft** [comment]
It could be, it doesn't even look that hard but judging by the lack of reply from anyone associated with the project I don't think it's likely. It's not something I'm likely to implement as I don't have need for it anymore.
