### ISSUE TITLE
[Bug] custom uploader response parsing broken since update

### ISSUE THREAD

**Issue by TheRealMarnes** [ShareX/ShareX#4234]
I just updated sharex on one of my PCs from 12.2 to 12.4.1. Since then, each attempt to upload a screenshot to my personal server results in an error: "URL is empty".

My server returns a header `X-Location` with a url (not `Location` because php doesn't allow returning that header with a 20x status code). I've tested my server using postman and firefox (I built webpages around my upload functionality), and everything definitely still works on it: the file is accepted and written away, the header is returned with the same old URL, and my identical (old) sharex installation on a different PC still works perfectly.

When I do test uploads from sharex on the PC where I updated it, I see the file arriving on the server, so it's not some sort of firewall or DNS issue.

I've tried with both
```
$header:X-Location$
```
and (as it has always been, and still is on my other PC but with `|` replaced by `,` because of syntax changes, I guess)
```
X-Location: \"(?<url>.+)\"
$regex:1|url$
```
but neither works. When I noticed sharex wasn't working anymore, I saw a notice in the config that the `$regex` feature was deprecated, prompting me to try the `$header:` config instead. Long ago, when I configured my custom uploader on both PCs, sharex already never worked with `$header:foo$`, only with the `regex` option. Since somewhere between 12.2 and 12.4.1, neither works anymore.

Hope I've explained myself clearly. TLDR: my server still works perfectly, returning the `X-Location` header on a file upload, and is being reached by the updated sharex instance with its test file.

Honestly, my gut feeling as a programmer is that sharex uses some HTTP library that was updated in recent builds and has become finnicky about the `X-Location` header, and that the `$header:` feature has never really worked as documented. Either that, or sharex now somewhow sends odd requests that cause PHP to drop headers or something.

![image](https://user-images.githubusercontent.com/3950300/61583787-3dd16a80-ab3d-11e9-97aa-52c829b59b4c.png)
![image](https://user-images.githubusercontent.com/3950300/61583788-3f029780-ab3d-11e9-96e7-f1695571f20b.png)
![image](https://user-images.githubusercontent.com/3950300/61583789-445fe200-ab3d-11e9-8dde-ebf35e7e1e6f.png)
![image](https://user-images.githubusercontent.com/3950300/61583790-45910f00-ab3d-11e9-8d7f-2f9647bb8a4b.png)
![image](https://user-images.githubusercontent.com/3950300/61583791-4629a580-ab3d-11e9-9722-d3fefba6cc76.png)

**Comment by Jaex** [comment]
I tested your custom uploader and it worked correctly like this: https://leaumar.net/dump/ShareX_yciWKoI1ZO.png

**Comment by TheRealMarnes** [comment]
Hmm, very strange. Can you think of anything sharex-related that could make it work fine for you but not for me when those settings are the same?

**Comment by TheRealMarnes** [comment]
Tried a fresh install (portable) with exported and imported config, still the same. There has to be some reason sharex isn't parsing the response header, or my server isn't sending it. Is there a way to inspect the "raw" http response sharex gets to its test upload?

**Comment by Jaex** [comment]
Try latest dev build: https://getsharex.com/docs/dev-builds

**Comment by TheRealMarnes** [comment]
It redirects me to an installer. Do the dev builds come in portable flavor by any chance?

**Comment by TheRealMarnes** [comment]
Yeah, the latest dev build works. I've copied over the installed files to my portable dir and reimported my settings. Guess one of the next official releases will solve this.

Thanks!
