### ISSUE TITLE
 Please add video codec (h264_qsv)

### ISSUE THREAD

**Issue by alex2345** [ShareX/ShareX#4238]
Hello, 
I found that FFmpeg provides -vcodec **h264_qsv**,
but ShareX not yet provides this option as one of the Video codec.

A good link for h264_qsv = [Intel QuickSync](https://trac.ffmpeg.org/wiki/Hardware/QuickSync)
Could you please add this option to help people who use **Intel GPU**?
Thank you very much!

**Comment by Jaex** [comment]
It is already added in codes, gonna be available in next release.
