### ISSUE TITLE
Does this exist - if not Feature Request - Enable Saved Style or Annotation Profiles

### ISSUE THREAD

**Issue by ShowGoShane** [ShareX/ShareX#4240]
When I was drawing this up in Excel, I quickly realized that this can get very complicated, but here it is.

I have a software product and I use ShareX daily, I love it!! Thank you Gods for whoever is selfless enough to spend their time bringing this amazing, useful, and necessary tool to the masses. Amazing, amazing product, that is thoughtful, has real-life applications and is super flexible without being too complex. Thank you!

Anyway, I use ShareX for a couple of different applications and needs. When I'm working in those different 'areas' or projects, I have a different set of 'settings' in ShareX and it's tough to switch them all by hand each time I switch my focus for that hour, or what have you.

Let's say that when I work on **User Manuals, I like to have 
  * Green arrows, with drop shadow, 3pt border, single arrow head, 
  * I like the 'Text: Background' to use Tahoma at 10pt, Italics, with Green background in the rectangle.
  * I set the blur effect to level '7'

Then, when I'm responding to Errors in the software, 
  * RED arrows, WITHOUT drop shadow, 1PT border, single arrow head, 
  * I like the 'Text: Background' to use VERDANA at 12pt, no-Italics * BOLD with BLUE background in the rectangle.
  * I set the blur effect to level '10'

Further, in the Manual I like the Watermark, in the Error Reporting, I don't use that.

If I could save a 'Profile' that I could name 'User Manual' and it would save all of the current settings, font, font size, etc., and then I could change all of them, get set for working on Error Reporting, then Save that Profile as such, this would be amazing and save so much time.

Is this currently possible, and if not, is this worth even suggesting as a Feature Suggestion?

**I was just thinking... I guess I could 'Import and Export' all of these settings via **Application settings...  >  Export/Import** couldn't I?  I guess ultimately, this is what I was hoping could be brought into the software with a drop-down list of Profile Names.

Thank you for your reply.

**Comment by ShowGoShane** [comment]
![IMG_ShareX Feature Request](https://user-images.githubusercontent.com/39810670/62017144-66271d80-b16a-11e9-9c09-e4f24e36145d.png)

**Comment by Jaex** [comment]
Annotation templates were requested in this issue #4227
