### ISSUE TITLE
Utilise already installed FFmpeg?

### ISSUE THREAD

**Issue by alivefromupstairs** [ShareX/ShareX#4241]
Screen recording needs ffmpeg installed, but I already have ffmpeg and its accessible from the command line. Can't you make use of it instead of having duplicate dependencies?

**Comment by sylveon** [comment]
ShareX allows you to give it a custom path for the FFmpeg tool
![image](https://user-images.githubusercontent.com/6440374/62336002-4cecdc80-b49c-11e9-8141-24e8069b8cf4.png)

**Comment by gitgt** [comment]
Screenshot proves was possible in 2019 but now in 2021 with version 13.5 it's not possible, no FFmpeg path anywhere.
Why? Please set this option back.
