### ISSUE TITLE
How do I add an application to perform custom actions in the menu?

### ISSUE THREAD

**Issue by Xevion** [ShareX/ShareX#4245]
I've created a script in Python that uses the `argparser` module to intercept arugments to the file whenever it's ran. I've created a task in ShareX like so:

![image](https://user-images.githubusercontent.com/44609630/62434408-c59ea380-b6fd-11e9-9876-13030f25e1a2.png)

For whatever reason, it doesn't work like I expect it to. I see a window pop up in the background, but nothing occurs on the scripts end that verifies in working nature of the script.
The script is supposed to write a little excerpt as well as confirmation that the file has been indeed ran, but nothing occurs, the file is not written to or even created.
In the debug log, I can see it ran this command:

```markdown
"X:\Users\Xevion\Anaconda3\python.exe" E:\Programming\Python\General\sharex-quickzoom\main.py "C:\Users\Xevion\Documents\ShareX\Screenshots\2019-08\Code_2019-08-04_21-14-49.png"
```

This runs correctly when I run it myself in the command line, and makes the correct output.
What's going on, and what should I do to fix it? Thanks.

**Comment by neilfranci** [comment]
Hi, it is been 5 years.
But I just want to ask did you make it work? Cause I have the same problem.
