### ISSUE TITLE
Feature: File name template

### ISSUE THREAD

**Issue by ndc168** [ShareX/ShareX#4251]
Under "Application Settings", "Subfolder Pattern", user can set naming template for subfolder to put files.

However, the same is not offered for file naming template. It will preset to i.e. chrome_1I0LccoEGf. This convention makes little sense to human eyes.

Can the same template be extended to file naming? so users can choose to append to a dated name and put under the subfolder of a day for instance?

Thanks.

**Comment by grrinch** [comment]
It does, actually.

It's under Task Settings:

![image](https://user-images.githubusercontent.com/5729796/63703377-c3bd9100-c820-11e9-83ea-e67c118a06f4.png)

Hope it helps!
