### ISSUE TITLE
Can't upload to Dropbox

### ISSUE THREAD

**Issue by iShyboy** [ShareX/ShareX#4253]
![image](https://user-images.githubusercontent.com/10236047/62582632-84d09700-b883-11e9-9d79-fadce88f7250.png)
![image](https://user-images.githubusercontent.com/10236047/62582654-93b74980-b883-11e9-8207-be915fceb6ec.png)
![image](https://user-images.githubusercontent.com/10236047/62582666-9b76ee00-b883-11e9-9912-b3fdc99480ce.png)

Into steps, I can verify my code but it didnt get my account info and does not see the path to upload? I've tried on another boot windows but Still get the same error, I've tried even start another dropbox account, still same thing.

**Comment by Jaex** [comment]
Are you using ShareX 12.4.1?

**Comment by iShyboy** [comment]
Clearly not, for some unknown reason I always got 404 when trying to check for updates. Only now I did update it from 12.3.1 to 12.4.1, strange that the Steam Sharex didn't even open here. It work now. Dumb me.
Thx.
