### ISSUE TITLE
Can't start after install

### ISSUE THREAD

**Issue by crazygo** [ShareX/ShareX#4257]
System.NullReferenceException: 
  ShareX.SettingManager.ApplicationConfigBackwardCompatibilityTasks()
   ShareX.SettingManager.LoadApplicationConfig()
   ShareX.SettingManager.LoadInitialSettings()
   ShareX.Program.Run()
   ShareX.Program.Main(String[] args)

ShareX 12.4.1 (Release)

**Comment by Jaex** [comment]
Duplicate of #3976
