### ISSUE TITLE
Crash when upload from clipboard

### ISSUE THREAD

**Issue by XCanG** [ShareX/ShareX#4260]
I make a screenshot via ShareX, but click copy on window, later I was need to upload image, but when I select Upload from clipboard, window appeared normally, but when I click OK it instantly crashed with error:
```
System.Runtime.InteropServices.ExternalException (0x80004005): В GDI+ возникла ошибка общего вида.
   в System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData)
   в System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format)
   в ShareX.HelpersLib.UnsafeBitmap.Lock(ImageLockMode imageLockMode)
   в ShareX.HelpersLib.ImageHelpers.IsImageTransparent(Bitmap bmp)
   в ShareX.TaskHelpers.SaveImageAsPNGStream(Image img, Stream stream, PNGBitDepth bitDepth)
   в ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   в ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   в ShareX.WorkerTask.DoAfterCaptureJobs()
   в ShareX.WorkerTask.DoThreadJob()
   в ShareX.WorkerTask.ThreadDoWork()
   в ShareX.HelpersLib.ThreadWorker.WorkThread()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()

ShareX 12.4.1 (Release)
```
Image, what make it crash uploaded manually (via browser) here: https://files.catbox.moe/fktgo0.png

**Comment by Jaex** [comment]
I cannot reproduce the crash using Chrome.

**Comment by XCanG** [comment]
Chrome? Ok I make another try and it work: 
1) Try to save file on local drive
2) Do not upload it from file, but open in image editor (in my case I open in `Paint.Net`)
3) Ctrl+A, Ctrl+C
4) Use ShareX `Upload from Clipboard` feature.
5) It will crash when you click ok.

**Comment by Jaex** [comment]
Still not crashing for me.

**Comment by XCanG** [comment]
Do you need any additional info to understand issue?

**Comment by XCanG** [comment]
### How this image was created?
I was actually bug reporting another thing and I was need to attach an image, so I use ShareX to select region, however I was think at first I can upload attachment from clipboard, so I not upload it in "after capture" window.
![image](https://user-images.githubusercontent.com/4011523/62826760-c8583780-bbda-11e9-84d6-a43ac97faf37.png)
Then when uploading from clipboard fails, I just try to upload again in ShareX using `Upload from clipboard` feature
![image](https://user-images.githubusercontent.com/4011523/62826771-06555b80-bbdb-11e9-9704-90f96299daa2.png)
There I seen normally my image in preview and just click ok, but it crash instead. I restarted it and try again and it crashed.

I also have **Clipdiary**, so I use it to save image into file then I upload it to this service and use later.

Since image didn't converted it still will crash my ShareX when you copy it again and try to upload.

**Comment by XCanG** [comment]
It will not crash ShareX if I use `Upload file` feature (I was tested that only when you say you can't reproduce that, that's why I mentioned it in https://github.com/ShareX/ShareX/issues/4260#issuecomment-520177538)

**Comment by XCanG** [comment]
If you need my ShareX settings what produce that image:
![image](https://user-images.githubusercontent.com/4011523/62826842-76181600-bbdc-11e9-9df6-68c6852b2828.png)
![image](https://user-images.githubusercontent.com/4011523/62826844-787a7000-bbdc-11e9-8bdb-1b4600ded849.png)

**Comment by XCanG** [comment]
Also I make another test, in case you copy image in `Paint` (included in windows), it will not crash ShareX. I was mentioned `Paint.Net` because it rich image editor, I bet same will be for Gimp, Photoshop and other tools if you have them, but I can't test them.

**Comment by Jaex** [comment]
I downloaded ShareX 12.4.1 portable and tested there, still browser and paint .net copy and clipboard upload works fine.

**Comment by XCanG** [comment]
@Jaex can you confirm image you copied are 32 bit depth?
