### ISSUE TITLE
[Feature request] History -> Clear History

### ISSUE THREAD

**Issue by alex2345** [ShareX/ShareX#4263]
Please provide function to **[History] -> [Clear History]**, Thank you very much!

**Comment by Jaex** [comment]
You can clear history by deleting "Documents\ShareX\History.xml" file. I on purpose did not add button to delete that file, because user can accidentally click it and even confirm it and then blame ShareX for losing years of history. So if users really want to clear it, they can delete the history file manually.

**Comment by pootzko** [comment]
I don't believe anyone would blame you. It's even part of the license - you can use it as is. And if it's behind a confirm box and the message is clear that they will lose the history, people should take responsibility for that. It's impossible to babysit everyone. 

> 15. Disclaimer of Warranty.
> 
>   THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
> APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
> HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
> OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
> THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
> PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
> IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
> ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

**Comment by OSHI7** [comment]
I believe it is History.JSON now, eh?

**Comment by stevesobol** [comment]
It should absolutely NOT delete the files.

**Comment by JohnS0N2** [comment]
I agree, there should be an easy clear history button inside the UI. NOT to delete the files, but just clear the history. Or you could also add a double confirmation. Do you want to delete? Are you really sure? ...

Thanks for making this app. Super time saver.
