### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [ShareX/ShareX#4267]
every time when i try to capture region of a video this windowed screen appear it only happens when the vid i am playing is on full screen

![image](https://user-images.githubusercontent.com/35454710/63048353-30b75980-bef8-11e9-8420-f683a31011be.png)
 how to disable this option

**Comment by grrinch** [comment]
I don't seem to be able to reproduce the error - below screenshot from Netflix running in full-screen mode:
![image](https://user-images.githubusercontent.com/5729796/63704731-8ad2eb80-c823-11e9-9891-2787c58ddb5e.png)

I also tested it with VLC and Windows Video Player (Windows 10) and everything seems fine.

Maybe try a different player.

It also looks that you're using Windows 7 - may be worth upgrading at some point.

As a workaround, you can make the movie play in a maximised window (but not full-screen) and just do a rectangle selection screenshot?

**Comment by 0ANIMEFREAK0** [comment]
the surprising part is i am actually using windows 10
that windowed screen showed up on win 10
