### ISSUE TITLE
Have all "after capture tasks" trigger after capture, instead of sequentially?

### ISSUE THREAD

**Issue by frankrende** [ShareX/ShareX#4268]
I currently have the following "after capture tasks" set:
- Open in image editor
- Copy image to clipboard
- Save image to file

In the image editor, if I don't click the Continue Task button (or spacebar/right-click), then the image is never copied to my clipboard or saved to my screenshots folder.

I work in QA, so I sometimes use the image editor to mark up my screenshots with arrows or boxes to highlight issues. But there are plenty of times when I don't need to mark up a screenshot, I just want to paste it "as is". If I don't continue my task then it never gets to my clipboard. I have to remember to interact with the image editor each time.

There would be two possible solutions for my situation:
1. Have all "after capture tasks" trigger at the same time, instead of sequentially, so by the time the image editor opens the file is already in my clipboard and saved
2. Allow me to reorder the sequence of the "after capture tasks", so the clipboard copy happens first, then the "save", then the "image editor"

Is any of this currently possible?

**Comment by Kobus-Smit** [comment]
I have the same requirement and would prefer this order:
* Copy image to clipboard
* Save image to file
* Open in image editor

Any workarounds perhaps?

**Comment by Kobus-Smit** [comment]
Found a workaround:

Add the `Perform actions` to the `After capture tasks`

![image](https://user-images.githubusercontent.com/11263864/70579482-e2476c80-1c04-11ea-9b0e-bd6b63360132.png)

Add an Action with Name: `Edit with ShareX` File path: `C:\Program Files\ShareX\ShareX.exe` Arguments: `-ImageEditor %input`

![image](https://user-images.githubusercontent.com/11263864/70579606-479b5d80-1c05-11ea-949f-6ee6619aa8ed.png)

**Comment by ryantheleach** [comment]
This sounds like an issue of a conflict of user expectations.

One camp will expect cancelling the editor will abandon an operation, the other, that it continues with no changes made.

Personally I'd be a fan of 'explicit' cancel/halt.

**Comment by andyhoffman12** [comment]
I would also like some features around this.
I would like the ability to have it in this order
Save the file
Apply Effects
Copy to Clipboard
Open Editor

It would be nice to reorder the list of after capture tasks and also choose if we can skip the task list or not. This could just be a simple settings page.

**Comment by frankrende** [comment]
> Found a workaround:
> 
> Add the `Perform actions` to the `After capture tasks`
> 
> ![image](https://user-images.githubusercontent.com/11263864/70579482-e2476c80-1c04-11ea-9b0e-bd6b63360132.png)
> 
> Add an Action with Name: `Edit with ShareX` File path: `C:\Program Files\ShareX\ShareX.exe` Arguments: `-ImageEditor %input`
> 
> ![image](https://user-images.githubusercontent.com/11263864/70579606-479b5d80-1c05-11ea-949f-6ee6619aa8ed.png)

Hey @Kobus-Smit - your solution was working for me until I updated to the latest version. Now every time I right-click the Image Editor to close it, it reopens again. I think it's related to the Action. Is this happening for you as well? Any ideas?

**Comment by leviustinov** [comment]
I would still like this implemented. I realized that I lost a bunch of screenshots thinking the tasks are performed concurrently!
Maybe there should be a way to re-order the tasks.

I looked into the workaround - since I have the UWP version the exe path will change with every update.
I guess I will settle for the snip and sketch tool for now...

**Comment by ckeschnat** [comment]
> 
> 
> > Found a workaround:
> > Add the `Perform actions` to the `After capture tasks`
> > ![image](https://user-images.githubusercontent.com/11263864/70579482-e2476c80-1c04-11ea-9b0e-bd6b63360132.png)
> > Add an Action with Name: `Edit with ShareX` File path: `C:\Program Files\ShareX\ShareX.exe` Arguments: `-ImageEditor %input`
> > ![image](https://user-images.githubusercontent.com/11263864/70579606-479b5d80-1c05-11ea-949f-6ee6619aa8ed.png)
> 
> Hey @Kobus-Smit - your solution was working for me until I updated to the latest version. Now every time I right-click the Image Editor to close it, it reopens again. I think it's related to the Action. Is this happening for you as well? Any ideas?

I only now used the workaround so I can't say how ShareX behaved in previous versions. Seeing this implemented would be awesome, but for me the workaround is still working.

If I don't modify the picture I can just press Esc. The editor closes and the image is saved and in the clipboard.
If I modify it, I press Enter or the green checkmark. The editor then opens again, but here Esc also works.

**Comment by IceToast** [comment]
> ng for me until I updated to the latest version. Now every time I right-click the Image Editor to close it, it reopens again. I think it's related to the Action. Is this happening for you as well? Any ideas?

That's because 'Enter' will perform the Actions (in the Actions-list) again after closing the Image Editor.

**Workaround:**
Don't use a Action but a Action for the workflow itself.

**Edit the Workflow:**
![015veAMOjC](https://user-images.githubusercontent.com/54889359/130792030-fb166517-f9f4-46ea-9110-15f3bb6d1357.png)

**Add the Action:**
![O14w9xHfkm](https://user-images.githubusercontent.com/54889359/130792113-537af9fd-4202-4c8c-ba31-3bc2cc99963b.png)

This way ShareX will only run the Image Editor Action after the specific Workflow, Capture Region for instance.
When you press 'Enter' to close the Image Editor it will run the "After Capture"-Actions which are the more or less global Actions from the first Workaround. However it won't run the Workflow Actions

Hope that works well for you
