### ISSUE TITLE
Add a simple offline OCR 

### ISSUE THREAD

**Issue by no-boot-device** [ShareX/ShareX#4269]
I think it'd be nice to have an option to have something like ffmpeg.exe where you simply download tesseract.dll and it loads in, replacing the admittedly nice ocr.space API for those of us with slower internet or who just have issues where it'll get stuck sometimes.

Edit: For the record, there is a tesseract net module. Any other OCR options are acceptable, though -- it's not like most users would care what is used as long as it works well enoughish.

**Comment by vatterspun** [comment]
**Background**: The Tesseract OCR library that @no-boot-device is referring to is here: https://github.com/tesseract-ocr/tesseract  The program is far from the best available picture-to-text program, but it's come a long way.

**Use case**: As someone who uses ShareX at work, sending data to be decoded by an external server could violate company policies, especially if I OCR something with customer data.  Where I work they're pretty serious about this sort of thing, and it could result in dismissal.

**Workaround**: You can send images to PDF XChange, which uses the Tesseract OCR libraries in their default distribution.

**Comment by no-boot-device** [comment]
I think "what if you don't know the language you're looking at" could be solved just by including some text in the language beside the language's name.

**Comment by mikamidd** [comment]
Offline OCR is something I'd really love to see in ShareX. 
Obviously including all or even a few essential languages isn't a good option, speaking in regards to tesseract at least, but having something like the current ffmpeg implementation where by default ShareX won't include any languages and it's up to a user to download appropriate language files separately.

**Comment by Jaex** [comment]
Check #5656 for progress.
