### ISSUE TITLE
SUGGESTION: Please, add shortcut "ctrl+w" to close "Image Editor"

### ISSUE THREAD

**Issue by carlos-cadu** [ShareX/ShareX#4272]
Please, add shortcut "ctrl+w" to close "Image Editor"
Thank you very much!

**Comment by Jaex** [comment]
Why don't you use "Escape" key instead?

**Comment by carlos-cadu** [comment]
Hey Jaex,

Thanks for the ESC suggestion. I'm so used with ctrl+W that I missed that.
Anyway, since ctrl+W is an almost universal command, I would still suggest
its inclusion.

Taking the opportunity of this conversation, I just miss in ShareX a
universal selection/move tool that could work with all shapes/text tools.
An example: I've annotated an image using rectangle, arrow, and text. To
achieve the final layout I need to move and adjust the position of each
shape selecting each tool, move the shape, select another tool, move text,
and so on. With the universal selection/move tool, this workflow would be
much more effective and pleasant.

Despite the lack of selection/move tool, I love your app, very
well-designed and full-featured. The best screen-capture/annotation/sharing
app ever!!!

Thank you,
Carlos

**Comment by Jaex** [comment]
Check: https://github.com/ShareX/ShareX/issues/4273#issuecomment-523435761

**Comment by carlos-cadu** [comment]
"Next version of image editor gonna have "Select and move" tool which lets
you unselect. Pressing escape once also unselects in that version. "

Thank you very much for the forthcoming improvement! You made my day :)

Is there a beta-testing going on? Since I use ShareX dozens, even hundreds
of times per day, I could provide feedback.

Cheers,
Carlos

**Comment by Jaex** [comment]
Yes you can test it: https://getsharex.com/docs/dev-builds

**Comment by carlos-cadu** [comment]
Hi Jaex,

Just a feedback: v13 is simply marvelous.
Amazing job!!!

Carlos
