### ISSUE TITLE
[Error] Could not load file or assembly 'ShareX.UploadersLib' on startup, preventing normal operation.

### ISSUE THREAD

**Issue by TeslaSupreme** [ShareX/ShareX#4275]
`System.BadImageFormatException: Could not load file or assembly 'ShareX.UploadersLib, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.UploadersLib, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

ShareX 12.4.1 (Release)`

This prevents the client from starting up. It might be my antivirus which has contained the file in question, but i have no idea.

**Comment by Jaex** [comment]
It means ShareX library file become corrupt, reinstall ShareX to solve it.
