### ISSUE TITLE
Where do I download the last commit of source code?

### ISSUE THREAD

**Issue by alex2345** [ShareX/ShareX#4276]
I've pulled a ShareX with git clone from https://github.com/ShareX/ShareX 
** 
Q1) How does ShareX perform a installation GUI?
currently I just see a project named ShareX.Setup (a console program).
or I can search which keyword on which project to find it?
**
Q2) Why on my first time to build it, 
Visual Studio told me it cannot using **Newtonsoft.json**?
and cannot find name space for **JsonConverter**?
but one minute later, my Visual studio fixed it automatically.
**
Thank you very much!

**Comment by T3RY4** [comment]
Maaaaaaaaaaaan, its .Net Framework app. To build you need .Net Framework SDK and Runtime(if you want to startup). And I recommend you to read or watch some guide about .Net and git.
