### ISSUE TITLE
Magnifier tool uses a fill if enabled.

### ISSUE THREAD

**Issue by stephen147** [ShareX/ShareX#4279]
**Quick Q before I go on:**
Where's the slice image effect. I can't see that.

---
**Bug**
With the new tool add magnifier in the edit window.

If there's a solid background then the magnifier still uses that as fill instead of transparency.

![image](https://user-images.githubusercontent.com/14054664/63638893-ab653f00-c685-11e9-9344-7cd3bff96c10.png)

**Btw, great update.**

**Comment by Jaex** [comment]
Slice image effect is this:

![](https://jaex.getsharex.com/2019/08/ShareX_Z6Yw1pyFLV.png)

Even opaque fill color is not intended still it can have uses if people want slight transparent color tint.

**Comment by stephen147** [comment]
Yes. I suppose you're right. It can also draw circle shapes if needed.

I should RTFM. I missed the effects section completely! Thanks.
