### ISSUE TITLE
Auto-Increment Filename Number does not save on crash or unexpected shutdown

### ISSUE THREAD

**Issue by leumasme** [ShareX/ShareX#4281]
I have my Naming Scheme set to %i{7} to keep my screenshots nicely ordered.
Now, when ShareX silently crashes about once a week (where do i find the logs from this?) or i have to unexpectedly shut my PC down because Windows Froze or a Power failure, the auto increment number is not saved, and on the next ShareX start and Screenshot, i have to manually open the folder to see what the latest number was, and then manually increment it.
The Screenshot history also does not save when this happens.
I suggest saving these things after each screenshot, as this is very annoying.

I know that i could add a few random character to the Naming Scheme as a workarround to the Overwrite dialogue, but i do not want this as the numbers will still be duplicate wich breaks the sorting.

**Comment by Jaex** [comment]
That option already exists:

![](https://jaex.getsharex.com/2019/08/ShareX_KJrctfQUl6.png)

**Comment by leumasme** [comment]
Why are you so fucking good?
