### ISSUE TITLE
Easy way of adding frames to a photo?

### ISSUE THREAD

**Issue by robertheadley** [ShareX/ShareX#4294]
Before shareX I used screenshotgrabber, which had a way of adding a few different frame styles to an image. before uploading a screenshot, a nice contrasting border and even drop shadow can have a huge effect on how it is received. Does anyone know if an existing way to do this in shareX even with a 3rd party tool?

**Comment by Jaex** [comment]
Like this:

![](https://jaex.getsharex.com/2019/08/chrome_U1fDEi7WJK.png)
