### ISSUE TITLE
Not themed scrollbar

### ISSUE THREAD

**Issue by runic-tears** [ShareX/ShareX#4295]
**ShareX v13.0.1**

The scroll bar looks not themed, which is kinda annoying tbh 🤔

![](https://i.imgur.com/WRYonr7.png)

**Comment by Jaex** [comment]
Because I can't theme it.

**Comment by runic-tears** [comment]
> Because I can't theme it.

Oh, that's a RIP. Btw, is there an option to switch themes?

**Comment by HyerrDoktyer** [comment]
Would it be possible to add an option to hide the scrollbar? I see no reason for it to be there and it would look much nicer if it was gone entirely.

**Comment by Jaex** [comment]
> is there an option to switch themes?

You can switch to light theme from application settings.
