### ISSUE TITLE
Window title for file name

### ISSUE THREAD

**Issue by benhooperastrix** [ShareX/ShareX#4299]
I used to use Greenshot which had a very useful option of using the window title in the file name. Could this be added to ShareX?

**Comment by Jaex** [comment]
It is already exists.

**Comment by longtth** [comment]
hi @Jaex  can you guide how to the window title in sharex? I've spent serveral hours in setting and Google but can't find it out.

**Comment by longtth** [comment]
the setting is here. 

![image](https://github.com/ShareX/ShareX/assets/1010849/c5d1d84e-80cd-4e59-b325-57cb600cf54e)
