### ISSUE TITLE
BUG? ShareX doesn't show shape color (shapes are transparent) since v13.0.1 update

### ISSUE THREAD

**Issue by carlos-cadu** [ShareX/ShareX#4300]
Hi,

As shown in this screencast (http://bit.ly/2ZAKSQo), since I updated to v13.0.1, ShareX can't set/show shape color anymore. Shapes are transparent, independent of selecting color. Any workaround to show colors again?

Thank you!

**Comment by chrisadipascual** [comment]
Can confirm , updating to v13.0.1 from v12.X will set your border size to 0. Thanks you so much carlos-cadu I for the solution.

**Comment by chrisadipascual** [comment]
I wonder why this is marked as invalid ?

**Comment by Jaex** [comment]
Because I tested it multiple times. Even now just because you insist, I installed ShareX 12.4.1 with fresh settings then draw arrow. Then updated ShareX to latest version and still arrow keeps its size. So you just wasting my time non stop testing it when there is no code related to resetting border size. How can I be sure that user is not changing border size to 0 itself?

**Comment by chrisadipascual** [comment]
Wow someone woke up on the wrong side of the bed today. 

I apologize for the time wasted on this , and any grief or annoyance this has caused you.

I'm certain that I never tinker with the settings and just updated to 13.0.1 . I couldn't remember what version it was , but it was 12.X to 13.0.1

**Comment by Jaex** [comment]
Where am I mad? I was just explaining the situation with details. Because you were asking why this issue marked as invalid.

**Comment by chrisadipascual** [comment]
Ah I see , you must've seen that on email , that was already removed and edited 2 days ago with "any chance to re-open this issue please?"

**Comment by shadow-42** [comment]
Same issue.

**Comment by Centaurium** [comment]
I had the same exact issue as OP. I didn't change the border size (ever), then suddenly my arrows stop working. Not sure why you're so salty about looking into a bug.
