### ISSUE TITLE
Dark theme - poor visibility

### ISSUE THREAD

**Issue by moniuch** [ShareX/ShareX#4304]
The dark theme that I have just discovered is IMO very badly designed
- The black color is way too dark
- The popup menus (such as when you click `Workflows >`) has no visible elements that would help the menus stand out from the background. In the default theme the menus are neatly bordered as well as accented with drop shadows.

**Comment by Smir** [comment]
Looks perfect here. Unsure how your struggling.

**Comment by moniuch** [comment]
This is how it renders on Win 8.1
![2019-08-28_20-59-16](https://user-images.githubusercontent.com/681956/63887684-9b2ec600-c9dd-11e9-9262-1948231187f4.png)

**Comment by Smir** [comment]
here's windows 10, but yours look fine to me? might be your monitor?
![image](https://user-images.githubusercontent.com/8978982/63888987-f8c01400-c9d7-11e9-9fe7-d80e6b99ed02.png)
how do you get your previous images to display? mine never show, only the latest one taken.

**Comment by moniuch** [comment]
I don't think it is good UI - the purpose of adark theme is not to make everything black beyond recognition. Lack of borders actually causes eye strain, so it is counter-effective.

I haven't one anything special to make the thumbs load. As far as I can recall I haven't had any trouble with that.

**Comment by mkosmo** [comment]
> the purpose of adark theme is not to make everything black beyond recognition. Lack of borders actually causes eye strain, so it is counter-effective.

Are you sure you don't have a monitor or other display issue?  On your screenshot, I can clearly see the borders.  There's less contrast than before, but there's still easily discernible bordering.

**Comment by Jaex** [comment]
Because how dark the theme is completely depends on monitors brightness and other monitor settings. Even that dark theme looking okey for us, it could be looking far more darker for you. Therefore it is problematic to choice proper colors.

**Comment by Jaex** [comment]
I'm making theme colors customizable now. Example color change:

![](https://jaex.getsharex.com/2019/09/ShareX_2ZETEWMUFN.png)

**Comment by Jaex** [comment]
https://twitter.com/GetShareX/status/1170333288914968577
