### ISSUE TITLE
[Dark Theme] Some things are still on light theme

### ISSUE THREAD

**Issue by thegamerx1** [ShareX/ShareX#4305]
![ShareX_Jd2env5VV0](https://user-images.githubusercontent.com/34986564/63901790-64b97100-ca06-11e9-938b-8208324e12ac.png)
The configuration menus are also not dark

**Comment by Jaex** [comment]
Enable this option:

![](https://jaex.getsharex.com/2019/08/ShareX_82taRQdSeO.png)
