### ISSUE TITLE
can't scroll thumbnail view with mousewheel

### ISSUE THREAD

**Issue by wareya** [ShareX/ShareX#4306]
title

**Comment by Jaex** [comment]
I'm unable to reproduce it.

**Comment by Jaex** [comment]
I could reproduce it after disable this option in Windows 10:

https://jaex.getsharex.com/2019/09/ApplicationFrameHost_AtCY1pb504.png

which is enabled by default so Windows 10 users should not be able to reproduce it.

Added workaround for this issue in https://github.com/ShareX/ShareX/commit/6c07490ea33ee6e2b9d1109923c2aa39fb41340e
