### ISSUE TITLE
Choosing HTTP defaults to HTTPS for FTP

### ISSUE THREAD

**Issue by Neltulz** [ShareX/ShareX#4308]
Title pretty much sums it up.  I don't yet have an SSL cert for my web hosting, and I'm basically just using regular plain jane HTTP for my URLs so that I can paste them into Discord easily... ShareX defaults the url to https:// which is annoying because I have to rename the URL to http://

For the time being, I'm using Clipboard fusion to convert the https:// to http:// but I really shouldn't have to do that.

Hopefully it's an easy fix! :)

**Comment by Jaex** [comment]
I can't reproduce it, shows http in this preview:

![](https://jaex.getsharex.com/2019/08/ShareX_0S5ddYI4R1.png)

**Comment by Neltulz** [comment]
Did you try setting up an SFTP with "http://", then doing a test upload, and checking to see what url goes into your clipboard?

**Comment by Jaex** [comment]
I can't do test upload, I don't have SFTP server.

**Comment by Neltulz** [comment]
Why not just use www.getsharex.com for testing purposes?  Why wouldn't that have SFTP support?

Besides, are we even sure this is an issue with SFTP?  It could just simply be an issue elsewhere in the shareX code.  How do you not have any way to test FTP?  If that is not possible, can we discuss this further in discord, where I'd be able to DM you my FTP login info so that you can try testing an upload?

Let me know. Thanks,
-Neil

**Comment by Jaex** [comment]
> WWhy not just use www.getsharex.com for testing purposes? Why wouldn't that have SFTP support?

Because web site is hosted by GitHub Pages.

**Comment by Neltulz** [comment]
> 
> 
> > WWhy not just use [www.getsharex.com](http://www.getsharex.com) for testing purposes? Why wouldn't that have SFTP support?
> 
> Because web site is hosted by GitHub Pages.

Ah, okay.  Well, in that case, would you like me to send you my FTP login info via discord?  You really need a way to test this to confirm if there's a bug, rather than just relying on the URL preview, which is a shoddy method of testing at best.

**Comment by Jaex** [comment]
To make sure, you did not enable this setting, right?

![](https://jaex.getsharex.com/2019/08/ShareX_JSj0IOLIVv.png)

**Comment by Neltulz** [comment]
Looks like that was the problem.  I must have enabled that option some time in the past and forgot all about it.

Thank you for helping me find the problem, and sorry for assuming it was a bug with ShareX.  You may close this issue.
