### ISSUE TITLE
[feature request] nondestructive editing (save annotated image to .psd like format)

### ISSUE THREAD

**Issue by 429IhD0** [ShareX/ShareX#4312]
Greenshot editor is able to save the edited image to its own .greenshot format, which is like Photoshop's .psd in not flattening the image so that it can be edited again when opened in Greenshot. I'd like to request this feature in ShareX as well (though not necessarily using Greenshot's approach, it seems possible to embed editing information in .png files, see [1][2]). I can imagine many use cases

- be able to save work (esp. important if it takes a lot of time to annotate)
- collaboration (I might want to send partially annotated file to someone else to be further annotated/modified)
- note taker (one can use each file as a little note taker)

[1] https://www.w3.org/TR/PNG/#11Ancillary-chunks
[2] https://faq.pdfviewer.io/en/articles/2118250-non-destructive-image-editing

**Comment by jesaisplus** [comment]
It could be great functionality
And to ask if you really want to exit when you make a right click... before close the editor's window and lose all your annotations

**Comment by vatterspun** [comment]
Two notes here: 

* From what I've read, PSD as a format is completely bonkers, so I definitely would recommend against that format.  PDF would work because it functions with layers, as would GIMP's XCF.
* It may also be possible to just save image generations, meaning the original and first edit, second edit, etc.  There shouldn't be a separate file for each and every edit (could get out of hand quickly) but maybe auto-save once per minute.  Not ideal but might be easy to implement.

> Greenshot editor is able to save the edited image to its own .greenshot format

Interesting stuff - I didn't know that about Greenshot.

**Comment by desknotes** [comment]
Yes, I came here to write this kind of post but forunately some one else has already done it.
ShareX is a great tool, but I miss a lot this kind of workflow, which is a key foundation for example of Evernote Skitch. 
The opportunity to change previous edits is a big milestone for productivity.

Hope to have this feature soon on next releases.

**Comment by vatterspun** [comment]
> hope to have this feature soon

It's been 8 months without reply, I don't think that's an option.  You might lobby for it's inclusion in their Discord channel or ask them to add it in exchange for becoming a supporter.

**Comment by NAL100** [comment]
+1 Would like this feature!  Something like a history of generations of edits would be great.

**Comment by stephen147** [comment]
Showing my support for this idea.

A layers system would be cool. Even one layer over the image would be a good start to allow erasing the edited layer. Then the code could be expanded to create a layer for each action or tool type.

**Comment by SpinnerWebs** [comment]
This would be very useful functionality. Picasa used to have something similar. Having this in ShareX would help in attempting to wean users off (the now ancient) Picasa.

**Comment by WiliTest** [comment]
+1 (I again lost +30 minutes of work  by mistake, probably by pressing one of those annoying shortcuts that close the editor).

**Comment by MagTun** [comment]
I had to modify a image made via ShareX with many arrow, and because there is not file like .greenshot,  I had to start again from the beginning. Please add this feature.

**Comment by domsleee** [comment]
I agree this would be a good feature!

Another example is from `draw.io`, it embeds information in the png

![image](https://github.com/ShareX/ShareX/assets/14891742/e7a827f0-9093-4bef-a534-ae0fd7fe4b1b)

![untitled drawio](https://github.com/ShareX/ShareX/assets/14891742/cdd7a1e7-09a2-4b67-ae17-7b2fd48e6f80)

If you look at it in a [png inspector](https://www.nayuki.io/page/png-file-chunk-inspector), it is embedding it in the file itself:

![image](https://github.com/ShareX/ShareX/assets/14891742/95d96709-d992-4710-8af0-3eac645c2c7b)

```
Text string: %3Cmxfile%20host%3D%22app.diagrams.net%22%20modified%3D%222023-12-14T01%3A43%3A24.710Z%22%20agent%3D%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F120.0.0.0%20Safari%2F537.36%22%20etag%3D%22GnpB6K4TQ3fLmt80Lzz7%22%20version%3D%2222.1.8%22%3E%0A%20%20%3Cdiagram%20name%3D%22Page-1%22%20id%3D%22HxyqlUWOYgPnnMdDcUO2%22%3E%0A%20%20%20%20%3CmxGraphModel%20dx%3D%222074%22%20dy%3D%221098%22%20grid%3D%221%22%20gridSize%3D%2210%22%20guides%3D%221%22%20tooltips%3D%221%22%20connect%3D%221%22%20arrows%3D%221%22%20fold%3D%221%22%20page%3D%221%22%20pageScale%3D%221%22%20pageWidth%3D%22827%22%20pageHeight%3D%221169%22%20math%3D%220%22%20shadow%3D%220%22%3E%0A%20%20%20%20%20%20%3Croot%3E%0A%20%20%20%20%20%20%20%20%3CmxCell%20id%3D%220%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3CmxCell%20id%3D%221%22%20parent%3D%220%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3CmxCell%20id%3D%22U1lcAxe9_cJxtm4eZkDm-3%22%20value%3D%22%22%20style%3D%22edgeStyle%3DorthogonalEdgeStyle%3Brounded%3D0%3BorthogonalLoop%3D1%3BjettySize%3Dauto%3Bhtml%3D1%3B%22%20edge%3D%221%22%20parent%3D%221%22%20source%3D%22U1lcAxe9_cJxtm4eZkDm-1%22%20target%3D%22U1lcAxe9_cJxtm4eZkDm-2%22%3E%0A%20%20%20%20%20%20%20%20%20%20%3CmxGeometry%20relative%3D%221%22%20as%3D%22geometry%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FmxCell%3E%0A%20%20%20%20%20%20%20%20%3CmxCell%20id%3D%22U1lcAxe9_cJxtm4eZkDm-1%22%20value%3D%22example%22%20style%3D%22rounded%3D0%3BwhiteSpace%3Dwrap%3Bhtml%3D1%3B%22%20vertex%3D%221%22%20parent%3D%221%22%3E%0A%20%20%20%20%20%20%20%20%20%20%3CmxGeometry%20x%3D%22350%22%20y%3D%22530%22%20width%3D%22120%22%20height%3D%2260%22%20as%3D%22geometry%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FmxCell%3E%0A%20%20%20%20%20%20%20%20%3CmxCell%20id%3D%22U1lcAxe9_cJxtm4eZkDm-2%22%20value%3D%22example2%22%20style%3D%22rounded%3D0%3BwhiteSpace%3Dwrap%3Bhtml%3D1%3B%22%20vertex%3D%221%22%20parent%3D%221%22%3E%0A%20%20%20%20%20%20%20%20%20%20%3CmxGeometry%20x%3D%22350%22%20y%3D%22390%22%20width%3D%22120%22%20height%3D%2260%22%20as%3D%22geometry%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FmxCell%3E%0A%20%20%20%20%20%20%3C%2Froot%3E%0A%20%20%20%20%3C%2FmxGraphModel%3E%0A%20%20%3C%2Fdiagram%3E%0A%3C%2Fmxfile%3E%0A
```

Maybe ShareX could take a similar approach?

**Comment by Mentaleak** [comment]
I would also Like to vote for this to be implemented
