### ISSUE TITLE
Revert to light theme by default

### ISSUE THREAD

**Issue by Dragas** [ShareX/ShareX#4315]
In latest update you've set the dark theme as the default. Can you revert that setting back to light mode instead?

**Comment by Jaex** [comment]
You can revert back to light mode from application settings.

**Comment by Dragas** [comment]
But why is dark theme the default? Is it so necessary to follow some internet fads?

**Comment by Jaex** [comment]
Because it is better.

**Comment by OscarVanL** [comment]
I thought the same @Dragas , I thought it would be better to infer the user's preference from the dark theme setting in Windows 10 (https://github.com/ShareX/ShareX/issues/4310). Saying "Because it is better" is so subjective. I prefer light theme in the day and dark theme in the night for example.

**Comment by Dragas** [comment]
The same issue suggests that "Dark mode is better" which is plain wrong. Both light and dark modes have their own usecases and considering ShareX features a lot of text, light mode IS the way to go when using it, as seen by https://www.laurenscharff.com/research/survreslts.html and http://www.linknet1.com/sighci/bit04/BIT_Hall.pdf (page 19)

**Comment by cnra** [comment]
How can I revert to light theme I couldn't find it on docs?

**Comment by jukzi** [comment]
Dark theme looks very odd when the rest of UI is running in light theme. i never had to adjust a theme bevore.
+1 to use system default theme

**Comment by przyjacieldawida** [comment]
@jukzi It will be brilliant to add that feature.
