### ISSUE TITLE
Revert to list view by default

### ISSUE THREAD

**Issue by Dragas** [ShareX/ShareX#4316]
In latest update (13.0.1) you've set thumbnail view as the default. Can you revert that option back to list view?

**Comment by Jaex** [comment]
Yes, from main window right click menu.

**Comment by Dragas** [comment]
But why thumbnail view is the default?

**Comment by Jaex** [comment]
Because it is better.

**Comment by yowshi** [comment]
ah no it isn't. it;s terrible and has terrible terrible information load. also what menu am i supposed to right clock on? because i can't find the option to go back to list view.
