### ISSUE TITLE
Support for LICECap for GIF Recording.

### ISSUE THREAD

**Issue by Fatih54102** [ShareX/ShareX#432]
I think it would be better if the classic gif recording is ditched and Licecap used instead.

Benefits of doing this:
*LICECap is open source as well.
*LICECap is written in C++. More Performance!
*It uses a special algorithm that the size of files generated are smaller than Sharex's gif recorder.
*...

Take a look: http://www.cockos.com/licecap

**Comment by Jaex** [comment]
I don't know how to use C++ things in C#.

**Comment by Fatih54102** [comment]
Maybe you can use that as 3rd party executable rather than including into the project.
http://i.imgur.com/LhXV5zb.png
