### ISSUE TITLE
Update removed every time I restart my PC

### ISSUE THREAD

**Issue by Laiteux** [ShareX/ShareX#4323]
So basically, when I start my PC, ShareX starts with it.
It tells me that there's an update available, so I install it.
However, after restarting my PC, it acts like the update has never been installed.
The version is still 12.3.1 and it asks me every PC restart if I wanna update it.
I tried reinstalling ShareX, didn't change anything.
I've been having this issue for months now.

**Comment by Jaex** [comment]
Most likely updater is installing to previous install location but you moved your old ShareX installation to another place and that ShareX is starting at startup not the newly installed one.

**Comment by Laiteux** [comment]
I can't remember having moved anything. Also, as explained, I did reinstall it.
How could I check and try fixing it, please? Kind regards.

**Comment by Laiteux** [comment]
@Jaex

**Comment by vatterspun** [comment]
> I can't remember having moved anything. Also, as explained, I did reinstall it.

You might try doing a search for anything to do with ShareX on your computer and delete/uninstall all instances.  I run "Everything" but there are a number of different tools that will help you track down that info.

My personal preference is to use the Portable version, though that tool will not automatically update, which I prefer.
