### ISSUE TITLE
Error message in sponsor dialog

### ISSUE THREAD

**Issue by simonporte** [ShareX/ShareX#4325]
It seems you (@Jaex user) are not/no longer enroled in the github sponsor program.
So there is a red banner on top of dialog if you click on 
![image](https://user-images.githubusercontent.com/32496803/64068901-75a0f700-cc3f-11e9-93ef-21e162c2d254.png) button on github.

![image](https://user-images.githubusercontent.com/32496803/64068873-b64c4080-cc3e-11e9-9d68-8f2d6a6592aa.png)

I guess you should remove the corresponding line in config if you do not correct the access to sponsor program itself.

`.github/FUNDING.yml`
`github: [Jaex] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]`

**Comment by redmicc9e** [comment]
[CODe](https://gitee.com/zhengqingya/code-generator)

**Comment by simonporte** [comment]
Problem still occurs.

**Comment by Jaex** [comment]
I already applied to the beta. It is not supported here yet.
