### ISSUE TITLE
Option to auto upload recorded GFYs but not auto upload images

### ISSUE THREAD

**Issue by Long-Horse** [ShareX/ShareX#433]
I request this because when I record a clip for a gfycat, I obviously want to upload it right away. When I take a screenshot, I have it open in the image editor where I highlight the focus point or whatever and then upload from the image editor.

AFAIK, [this option](http://i.imgur.com/wHy7C7h.png) is the only option and controls both gfycats and images. Is there a way to have it upload gfycats but not images?

**Comment by Jaex** [comment]
You can set different destinations per hotkey so your screen record hotkey can have gfycat destination.

**Comment by Long-Horse** [comment]
Thanks, didn't know I could each hotkey. Kinda new to this.
