### ISSUE TITLE
历史记录怎么删除

### ISSUE THREAD

**Issue by Kumiri** [ShareX/ShareX#4331]
中：ShareX 历史记录不知道怎么删除？？
Eng：How to delete ShareX history??

中：历史记录里大多数都是已删除的，而记录一直都存在。
Eng：Most of the history records have been deleted, and records have always existed.

Screenshot：https://i.vgy.me/A8c7VZ.png

**Comment by tonychen3** [comment]
You can open **"C:\Users\(YOUR USER NAME)\Documents\ShareX\History.xml"** with notepad and choose whatever history you prefer to delete.

**Comment by Kumiri** [comment]
Thank you
Still, deleting files is more convenient.

> 
> 
> You can open **"C:\Users\(YOUR USER NAME)\Documents\ShareX\History.xml"** with notepad and choose whatever history you prefer to delete.

Thank you
Still, deleting files is more convenient.
