### ISSUE TITLE
Update broke drag-n-drop

### ISSUE THREAD

**Issue by PhilipWith1L** [ShareX/ShareX#4333]
With the latest update to 13.0.1, on a Windows 10 machine, I am unable to drag captures from the file list in the ShareX interface and drop it into any other application. I tried this with Chrome, Slack, Word. Searched around here to see if anyone else has reported this, but I'm not seeing any so far.
Let me know what other info I can provide that would be helpful.

**Comment by Jaex** [comment]
When you install the updater, because setup is ran as admin, it also rans ShareX as admin too. When is ran as admin then you can't drag n drop stuffs. So if you reopen ShareX then this issue will be resolved. So this issue only happens once right after installation of new update because of setup.
