### ISSUE TITLE
Automatically copy original image to clipboard when opening in the editor

### ISSUE THREAD

**Issue by Dmitrinjo** [ShareX/ShareX#4337]
Can you please add the option that when an after capture task "Open in the image editor" is selected the original image is automatically copied to clipboard. Then I can use that image and if I edit the image then I can manually click copy button or CTRL + Shift + C. This would be much more useful. You can even add this option as a checkbox in the settings so people can turn it on and off. Thank you!

**Comment by uninvitedguest** [comment]
I wish this functionality existed too (or wasn't broken). I have the "Copy image to clipboard" after capture set, as well as open the image edit. Unfortunately the image is never copied to the clipboard. I have to manually do it from the editor.
![image](https://user-images.githubusercontent.com/24210277/72379978-76b05d80-36e2-11ea-9938-f0eabce9cf65.png)

**Comment by Dmitrinjo** [comment]
Bump

**Comment by frankrende** [comment]
I was previously getting around this by having an action which would manually open the image editor (configured as **-ImageEditor %input**). This worked because the "Perform Actions" comes after the Copy to Clipboard.

Since the latest update there's an issue though. Every time I right-click the image editor to close, it reopens itself. I think this is related to my Action, but can't figure out why it's happening.

**Comment by dpertierra** [comment]
I have the same issue I use the "Copy image to clipboard" after capture set, as well as open the image editor. but it does not copy the image to the clipboard, I always have to press the copy button from the editor.

**Comment by JimBreton** [comment]
Bump

**Comment by Jaex** [comment]
Check this option:

![](https://jaex.getsharex.com/2022/06/chrome_02LCqV9TlY.png)

**Comment by JimBreton** [comment]
@Jaex , that works, thank you!!

**Comment by ScottBeeson** [comment]
These are my settings for PRTSCRN. It does open the editor, but it does NOT copy to the clipboard or save the file until I hit the little checkmark. How do I make it automatically do this?

![image](https://github.com/ShareX/ShareX/assets/108358/85108c60-30bd-4613-ba23-6a6e78d16e18)

**Comment by uninvitedguest** [comment]
Looks like the setting has been moved, and is now only visible when you have the editor window open: 
![image](https://github.com/ShareX/ShareX/assets/24210277/c5e75eea-a0e9-4326-857a-7cf760aecd2d)

**Comment by longtth** [comment]
> Check this option:
> 
> ![](https://camo.githubusercontent.com/df907a1b56aaf9d9364db7e3a9bd6d9add17218802965c09a3ba8ebbea234529/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032322f30362f6368726f6d655f30324c43715639546c592e706e67)

thank you very much, this fixed my problem.
