### ISSUE TITLE
Black screen appears when trying to capture

### ISSUE THREAD

**Issue by Degree23** [ShareX/ShareX#434]
When I try to do any capture, a black screen appears and I can't see what I am trying to capture. Even if I press the Print Screen button I am given a black screen. This started happening after I had Geek Squad wipe my hard drive clean, and also had them install WebRoot. Maybe it is WebRoot affecting ShareX one way or another? Not entirely sure. What could I do to resolve this issue?

**Comment by Jaex** [comment]
It is your responsibility to uninstall WebRoot and check is problem solved. If another application causing this issue then I can't do anything about it.

**Comment by jeroenvvv** [comment]
I have the same issue...

**Comment by Thom-Ernst** [comment]
what a way to fix bugsm did you manage to resolve this after 3 years?
