### ISSUE TITLE
Update 12.4.1 to 13.0.1 fails with illegal Windows folder name

### ISSUE THREAD

**Issue by TonyGravagno** [ShareX/ShareX#4340]
Update is available for 12.4.1 to 13.0.1. On all attempts to update there is a critical error and the update fails. 

> Folder names cannot include any of the following characters: / : * ? " < > |

![image](https://user-images.githubusercontent.com/499473/64198814-d26a0080-ce3d-11e9-81a3-b51ac1c138d5.png)

This is completely new. I use ShareX all the time and have not had any errors. (Wow!)

**Comment by TonyGravagno** [comment]
I'm hoping someone can check the most recent Inno Setup configuration for 13.0.1. These are my note about the [attached installation log](https://github.com/ShareX/ShareX/files/3632517/share11.log):

1. It shows several issues for "RestartManager found an application using one of our files".
1. Those errors show garbage for the filenames.
1. My system language is US-EN.
1. I've rebooted many times since originally reporting this issue.
1. I've killed a bunch of apps/processes/services manually right before installation of ShareX.

My guess is that Inno Setup (written in Pascal) has something invalid in its [array of ProcessInfos](https://github.com/jrsoftware/issrc/blob/master/Projects/Wizard.pas#L1990). It looks like the array elements could contain null or invalid pointers, and maybe just dumping whatever is found in memory at the current address of the array.

I spent time to try to ask Martijn (maintains Inno Setup) about this but they still use NNTP for that FOSS, and I'm not going to install a NNTP reader to try to diagnose an issue when I don't have access to the Inno Setup config.

I'm a C# developer, happy to help with diagnostics. But right now there doesn't seem to be much more that I can do.

Thanks.

Running ShareX over Windows 8.1/64

**Comment by Jaex** [comment]
You can't uninstall and reinstall either?

**Comment by TonyGravagno** [comment]
I'm sure I can but then the issue is simply masked. If this is due to a change you made related to Inno Setup then I thought you'd want an opportunity to diagnose it. If you think this is a one-off (sure seems like it) then sure, I'll just re-install, fix My problem and be done with it. Thanks!

**Comment by Jaex** [comment]
Problem happens inside InnoSetup I can't do anything. But most likely they can't do anything too. Probably last installation folder path while saving corrupted.
