### ISSUE TITLE
No fill color option for lines and arrows

### ISSUE THREAD

**Issue by maartenbrakkee** [ShareX/ShareX#4344]
In the image editor, I can't change the fill color of any arrows or lines.

Version: 13.0.1

![image](https://user-images.githubusercontent.com/1454803/64238115-115f8b00-cefe-11e9-8aac-5f9abed5df34.png)

**Comment by Jaex** [comment]
Border size must be set to 0 somehow.

**Comment by maartenbrakkee** [comment]
That was the case, thank you. I'll close this issue.

**Comment by ReidJiangwu** [comment]
how to reset border size？

**Comment by mulfunction** [comment]
how to reset border size?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2019/11/ShareX_0JOVjHsasX.png)
