### ISSUE TITLE
Bad Request when uploading to imgur

### ISSUE THREAD

**Issue by Machiination** [ShareX/ShareX#4345]
I believe this started happening after the last update

https://pastebin.com/HQEEqQ0N

> 2019-09-04 15:26:31.011 - ShareX starting.
> 2019-09-04 15:26:31.013 - Version: 13.0.1
> 2019-09-04 15:26:31.013 - Build: Release
> 2019-09-04 15:26:31.013 - Command line: "D:\ShareX\ShareX.exe" 
> 2019-09-04 15:26:31.014 - Personal path: D:\Machination-5570\Documents\ShareX
> 2019-09-04 15:26:31.014 - Operating system: Windows 10 Pro (64-bit)
> 2019-09-04 15:26:31.015 - Running as elevated process: False
> 2019-09-04 15:26:31.024 - ApplicationConfig load started: D:\Machination-5570\Documents\ShareX\ApplicationConfig.json
> 2019-09-04 15:26:31.497 - ApplicationConfig load finished: D:\Machination-5570\Documents\ShareX\ApplicationConfig.json
> 2019-09-04 15:26:31.499 - UploadersConfig load started: D:\Machination-5570\Documents\ShareX\UploadersConfig.json
> 2019-09-04 15:26:31.501 - MainForm init started.
> 2019-09-04 15:26:31.961 - UploadersConfig load finished: D:\Machination-5570\Documents\ShareX\UploadersConfig.json
> 2019-09-04 15:26:31.964 - HotkeysConfig load started: D:\Machination-5570\Documents\ShareX\HotkeysConfig.json
> 2019-09-04 15:26:31.991 - HotkeysConfig load finished: D:\Machination-5570\Documents\ShareX\HotkeysConfig.json
> 2019-09-04 15:26:32.189 - MainForm init finished.
> 2019-09-04 15:26:32.710 - Startup time: 1723 ms
> 2019-09-04 15:26:32.750 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
> 2019-09-04 15:26:32.750 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
> 2019-09-04 15:26:32.750 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
> 2019-09-04 15:26:32.750 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
> 2019-09-04 15:26:32.750 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF) using custom region, Job: ScreenRecorderGIF
> 2019-09-04 15:26:32.752 - HotkeyManager started.
> 2019-09-04 15:26:32.753 - WatchFolderManager started.
> 2019-09-04 15:26:34.641 - Hotkey triggered. Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
> 2019-09-04 15:26:34.643 - Executing: Capture entire screen
> 2019-09-04 15:26:34.730 - Task in queue. Job: Job, Type: Image, Host: Imgur
> 2019-09-04 15:26:34.905 - Task status: Preparing
> 2019-09-04 15:26:34.970 - Image copied to clipboard.
> 2019-09-04 15:26:35.054 - Image saved to file: D:\Machination-5570\Documents\ShareX\Screenshots\2019-09\nXN157gY6d.png
> 2019-09-04 15:26:35.082 - Upload started. Filename: nXN157gY6d.png, Filepath: D:\Machination-5570\Documents\ShareX\Screenshots\2019-09\nXN157gY6d.png
> 2019-09-04 15:26:37.981 - Error:
> Error message:
> The remote server returned an error: (400) Bad Request.
> 
> Request URL:
> https://api.imgur.com/3/upload
> 
> Status code:
> (400) Bad Request
> 
> Headers:
> Connection: close
> X-Ratelimit-Clientlimit: 12500
> X-Ratelimit-Clientremaining: 12500
> X-Ratelimit-Clientreset: 86400
> X-Ratelimit-Userlimit: 500
> X-Ratelimit-Userremaining: 499
> X-Ratelimit-Userreset: 3141
> Strict-Transport-Security: max-age=15724800; includeSubDomains;
> Content-Length: 100
> Content-Type: application/json; charset=utf-8
> Date: Wed, 04 Sep 2019 13:26:37 GMT
> Server: nginx/1.13.5
> 
> Response text:
> {"status":400,"success":false,"data":{"error":"Bad Request","request":"/3/upload","method":"POST"}}
> 
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
> 2019-09-04 15:26:38.010 - Upload failed. Retrying upload.
> 2019-09-04 15:26:41.543 - Error:
> Error message:
> The remote server returned an error: (400) Bad Request.
> 
> Request URL:
> https://api.imgur.com/3/upload
> 
> Status code:
> (400) Bad Request
> 
> Headers:
> Connection: close
> X-Ratelimit-Clientlimit: 12500
> X-Ratelimit-Clientremaining: 12500
> X-Ratelimit-Clientreset: 86400
> X-Ratelimit-Userlimit: 500
> X-Ratelimit-Userremaining: 499
> X-Ratelimit-Userreset: 3137
> Strict-Transport-Security: max-age=15724800; includeSubDomains;
> Content-Length: 100
> Content-Type: application/json; charset=utf-8
> Date: Wed, 04 Sep 2019 13:26:41 GMT
> Server: nginx/1.13.5
> 
> Response text:
> {"status":400,"success":false,"data":{"error":"Bad Request","request":"/3/upload","method":"POST"}}
> 
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
> 2019-09-04 15:26:41.549 - Task failed. Filename: nXN157gY6d.png, Errors:
> Imgur upload failed: (400) Bad Request
> 
> Error message:
> The remote server returned an error: (400) Bad Request.
> 
> Request URL:
> https://api.imgur.com/3/upload
> 
> Status code:
> (400) Bad Request
> 
> Headers:
> Connection: close
> X-Ratelimit-Clientlimit: 12500
> X-Ratelimit-Clientremaining: 12500
> X-Ratelimit-Clientreset: 86400
> X-Ratelimit-Userlimit: 500
> X-Ratelimit-Userremaining: 499
> X-Ratelimit-Userreset: 3137
> Strict-Transport-Security: max-age=15724800; includeSubDomains;
> Content-Length: 100
> Content-Type: application/json; charset=utf-8
> Date: Wed, 04 Sep 2019 13:26:41 GMT
> Server: nginx/1.13.5
> 
> Response text:
> {"status":400,"success":false,"data":{"error":"Bad Request","request":"/3/upload","method":"POST"}}
> 
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by Jaex** [comment]
Pastebin is blocked in my country but always those "Bad requests" to do with Imgur and not ShareX. We are using their new upload endpoint so that could explain the reason why last update have this issue but not previous.

**Comment by Machiination** [comment]
Well, using old upload endpoint as a fallback may be a good strategy

**Comment by Jaex** [comment]
Few days ago we also noticed that latest endpoint was giving "Bad request" error in response but old end point was giving more descriptive error and that error was saying that specific country is blocked by Imgur.

**Comment by Machiination** [comment]
Imgur ban is bypassed by simply logging in, I get this exact error regardless of login status.

**Comment by Jaex** [comment]
That country ban was not bypassable.

**Comment by Machiination** [comment]
My country is banned on imgur, uploading without being logged in doesn't work.

Uploading while logged in does work.

**Comment by Jaex** [comment]
What is your country?

**Comment by Machiination** [comment]
I prefer not to answer that publicly

**Comment by CubityFirst** [comment]
Regardless of what you're saying, if you're in Egypt, or Turkey (The two that I'm aware that has this issue), then you won't be able to use the Imgur API (Or Service at all in case of Turkey).

If that is the case, You'll have to find a different screenshot host for all of your images.

**Comment by Machiination** [comment]
Well, this issue doesn't need to remain open since it apparently is on Imgur's side.
