### ISSUE TITLE
Imgur mp4 upload fails

### ISSUE THREAD

**Issue by Waleedov** [ShareX/ShareX#4346]
It shows it succeded
![image](https://user-images.githubusercontent.com/48418015/64337608-04b36380-cfe0-11e9-8158-3d11b78b2936.png)

But when I visit the link it shows this
![image](https://user-images.githubusercontent.com/48418015/64337640-1563d980-cfe0-11e9-9d65-17c588e8c50a.png)

Here is the config
![image](https://user-images.githubusercontent.com/48418015/64337711-33c9d500-cfe0-11e9-89bd-66ce063d2636.png)

What is missing?

**Comment by Waleedov** [comment]
Any news on this?

**Comment by Jaex** [comment]
I can't replicate: https://i.imgur.com/dUR2z3R.mp4
