### ISSUE TITLE
Keybinds for region

### ISSUE THREAD

**Issue by radekhanus1** [ShareX/ShareX#4347]
Hi,
is possible add new feature - map a key shotcurt for region? 

![image](https://user-images.githubusercontent.com/47090713/64381243-05c1b080-d033-11e9-905b-2a07e8bd0837.png)

All tools have keybinds but Rectangle region, eclipse region, freedand region are without it.
I think that this feature are very usefull.

thanks 
Radek

**Comment by Jaex** [comment]
Tab key switches to region.

**Comment by radekhanus1** [comment]
Hi, 

great - thanks for your answer.

Radek
