### ISSUE TITLE
After capture dialog, allow drag & drop?

### ISSUE THREAD

**Issue by Waleedov** [ShareX/ShareX#4348]
Is it possible to allow images to be dragged and dropped from this dialogue?

![image](https://user-images.githubusercontent.com/48418015/64444664-f09d5e00-d0d4-11e9-86b5-97ccbd5dcda8.png)

At the moment this dialogue allows you to open the image. But many times I prefer to use that image straight in an application or dropped it on desktop.

**Comment by Nicofisi** [comment]
I would also love that
