### ISSUE TITLE
Avoid duplicates when auto capture

### ISSUE THREAD

**Issue by Magikh42** [ShareX/ShareX#4349]
I want a setting in auto capture that cancel the save / upload task if the screen hasn't change since last screenshot

**Comment by vatterspun** [comment]
Good suggestion. 

In the mean time you can use the "Automatic Screenshotter" freeware program for this or run an anti-duplication program like AllDup after the recording to delete all files within a similarity threshold (e.g. delete anything with small mouse movements but don't delete major screen changes).
