### ISSUE TITLE
Using custom settings of any kind results in ffmpeg breaking

### ISSUE THREAD

**Issue by glyphical** [ShareX/ShareX#4350]
See title.

I was trying to record in 60fps but noticed that when I record I get severely low framerates. This seems to be a common problem and one of the suggestions was removing -tune zerolatency. However, when I tried to do so it caused ShareX to encode infinitely; when testing with CMD it returns no visible errors, but even 3+ hours later after trying to record 4 seconds of video, it's still encoding.

I tested further and found that even with completely identical commands in the command line, checking "Use custom commands" causes ffmpeg to encode infinitely no matter what. Here is what shows without custom commands:

``-y -rtbufsize 150M -f dshow -framerate 60 -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:v libx265 -r 60 -preset ultrafast -tune zerolatency -crf 18 -pix_fmt yuv420p -movflags +faststart -c:a aac -strict -2 -ac 2 -b:a 128k "output.mp4"``

Here is what shows when I copy the same text into custom commands:

``-y -rtbufsize 150M -f dshow -framerate 60 -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:v libx265 -r 60 -preset ultrafast -tune zerolatency -crf 18 -pix_fmt yuv420p -movflags +faststart -c:a aac -strict -2 -ac 2 -b:a 128k "output.mp4"``

And yet, for some reason, asking it to use custom settings is causing ffmpeg to stall out and permanently encode. It seems to be using resources in the background, but never actually does anything no matter how long I wait.

**Comment by MaxOfS2D** [comment]
I can confirm this happens for me if I tick "Record using lossless encoding and then apply user encoding option".

When the bug happens, what's going on is that it starts recording and encoding (in realtime) **from the moment you hit "stop".**

It's supposed to take what I just recorded losslessly, and apply the encoding settings to that, but instead the lossless recording gets ignored. It IS written to disk, and it's there, accessible and readable, but ShareX (or FFMpeg) is instead continuing to record with your customized commands.

**Comment by glyphical** [comment]
Interestingly, I've never had the option to actually do anything with the ShareX encoding icon. All of its options were always greyed out. But, your tip has lead to something odd—I no longer have infinite encoding or anything of the sort going on in the background when I record... but with that option off, instead, it just literally never produces anything. Doesn't start encoding, doesn't produce any video, the recorder just turns off and nothing happens. 

https://i.imgur.com/zIyiLsJ.png

Here is an image of my settings exactly as they are. Note: It didn't work with tune zerolatency either, so don't mind that conspicuous absence.

**Comment by eLeCtrOssSnake** [comment]
Still broken...
