### ISSUE TITLE
Copy settings from a backup?

### ISSUE THREAD

**Issue by Chris-Wilson123** [ShareX/ShareX#4355]
What files do I need to copy from a backup of a hard drive to a fresh installation of ShareX in order to make it work as the old one please? I have the current version loaded on a new PC but the backup is an earlier version.... Thanks!

**Comment by AraHaan** [comment]
Maybe ShareX needs an import/export settings option like what Visual Studio has now too? @Jaex what you think?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2019/09/ShareX_b6u2NIId3b.png)

**Comment by Chris-Wilson123** [comment]
Thanks, I appreciate there's an export / import settings tab, but the original version is on a back up tape, at the file level, so I am looking for a file level change, IYSWIM? But I appreciate the replies, thank you :)

**Comment by Jaex** [comment]
It is just about replacing Document/ShareX folder with your backup when ShareX is not on.

**Comment by Chris-Wilson123** [comment]
OK, I'll transfer all that's in the My Documents/ShareX folder into the same directory of the new version ensuring it is NOT running! Thank you. Is there any issue with migrating this folder to the current version from my back up which is 12.3.1?
