### ISSUE TITLE
@ character appears to be improperly percent encoded when URL is given to clipboard

### ISSUE THREAD

**Issue by irandms401** [ShareX/ShareX#436]
Uploading a file through (maybe just through FTP?) appears to cause an issue if the filename has an @ in it somehow.

example: uploading a file named "@.png" gives the following URL:

http://blah blah blah/%2540.png

@ percent encoded is %40, and % percent encoded is %25. 
It seems like the percent sign in %40 is getting encoded.
This looks like it happens every single time @ appears, as so:

Link given to my clipboard after upload: http://irandms.noip.me/~irandms/sharex/2015/01/03_19-01-32_CUsersirandmsDocuments%2540_test__test_%2540_test_.png

Actual link: http://irandms.noip.me/~irandms/sharex/2015/01/03_19-01-32_CUsersirandmsDocuments@_test__test_@_test_.png

EDIT: this appears for way more than just @, it pretty much looks like it affects anything that gets percent encoded.

example: file named "! @ # $ % ^ & ( ) [ ] ; ' . , .txt" is put in clipboard as:

http://irandms.noip.me/~irandms/sharex/2015/01/!%20%2540%20%2523%20%2524%20%20%20%2526%20(%20)%20%5B%20%5D%20%253B%20'%20%20.%20%252C%20.txt

instead of the actual URL:

http://irandms.noip.me/~irandms/sharex/2015/01/!%20@%20%23%20$%20%20%20&%20%28%20%29%20%5B%20%5D%20%3b%20%27%20%20.%20,%20.txt

Apologies if this has been reported before, didn't see it in search. Can give more details if needed as well.

**Comment by Jaex** [comment]
@SolidX is your changes caused this issue too :( ?

**Comment by SolidX** [comment]
@Jaex I'll check it out as soon as I get a chance. :+1:

**Comment by Jaex** [comment]
Thanks :)

**Comment by SolidX** [comment]
@Jaex looks like this is still an issue after #431 was merged in.
