### ISSUE TITLE
Yellow tint on Screenshots

### ISSUE THREAD

**Issue by johnthatfield** [ShareX/ShareX#4361]
When taking a screenshot, the screen is tinted yellow to ensure the selection can be chosen. However, this yellow tint is now included in the screenshot with the new update. Even when turning the dim screen setting off whilst screenshotting this feature does not get turned off.

![image](https://user-images.githubusercontent.com/7272069/64761126-aefe2e80-d57e-11e9-9932-5810e56e362b.png)

**Comment by PulzHF** [comment]
I am having the same issue. Everything looks yellow, worth mentioning that I got a new monitor today- and updated my graphics drivers.
I went from 60 to 144hz, if that's of any importance.

Did not have this issue prior.

**Comment by PulzHF** [comment]
@Myth2014 I just fixed this issue for me- assuming it is the same for you.

I simply restarted my f.lux application.
