### ISSUE TITLE
Image saved as JPG instead of PNG when complexity increases

### ISSUE THREAD

**Issue by andyjsmith** [ShareX/ShareX#4362]
In task settings, I have the image format set to PNG. When I capture an image and click save as, it usually saves as PNG. However, when the complexity of an image increases, it changes the save format to JPG. I'm guessing ShareX thinks it will save space by saving as a JPG? Is there a way to turn this off?

I'm guessing this is the same issue @Devocub was having in #3714, but he never received a response.

**Here's an example, using a blank page in Chrome:**
Blank white page, image is saved as a PNG
![image](https://user-images.githubusercontent.com/10589271/64808087-8ff2a300-d564-11e9-8db9-114ab3c02f82.png)

Page with a complex background, probably hard to compress, saved as JPG:
![image](https://user-images.githubusercontent.com/10589271/64808188-c6302280-d564-11e9-859e-a8637e9b6f9c.png)

_Version: ShareX 13.0.1
Platform: Windows 10 1903_

**Comment by DAOWAce** [comment]
I've found this happening to me even with that option disabled.

It seems to be completely random (though maybe not random to the capture software).  I can attempt take a picture of the same exact window with the same exact thing in it (ex. a specific game), and one screenshot will be .png, the other will be .jpeg.

Attempting to google search to see if there's anything mentioning this but this is the only sort of relevant result found so far.

**Comment by Kiefy** [comment]
That setting does nothing for me either. at least when performing a full-screen capture of 3 monitors.

It gives me an extremely grainy jpeg, despite the following settings:

- Image format: PNG
- JPEG Quality: 100
- If Image size bigger than specified: UNTICKED
