### ISSUE TITLE
Possible Linux Port?

### ISSUE THREAD

**Issue by lorenzoi** [ShareX/ShareX#4365]
Could it be possible to create a Linux port using `mono` and seeing how that would go?

**Comment by L1Q** [comment]
Attempts were made, it did not go well.

**Comment by Kasp42** [comment]
I really wanted to use ShareX.
Maybe there is some way to use it on Linux?

**Comment by vatterspun** [comment]
This has been requested many times before.  Please search before posting
#3110 #3016 #1515 #1572

**Comment by dxf** [comment]
FYI https://magiccap.me/ serves screenshot&upload for Linux and Mac much like ShareX.
