### ISSUE TITLE
[Feature request] Cut out

### ISSUE THREAD

**Issue by qualityprovider** [ShareX/ShareX#4366]
In some cases a new feature Cut out requires: 
(user doesn't need space between and to make picture smaller needs only start and end parts or lsome left and some right parts)

right now you've got workaround: Capture part and then 
Image -> Insert image from screen -> Insert image below or Insert image on right side

As a user I want to select horizontal (or vertical) limiters, so after confirmation space between those lines erased and remained areas sticked together.

![before](https://user-images.githubusercontent.com/33333156/64871742-8d6c7800-d64e-11e9-84bd-2a44ea5b2855.png)
![after](https://user-images.githubusercontent.com/33333156/64871747-8f363b80-d64e-11e9-87a1-c8b2b10cf975.png)

**Comment by thefrenchmatt** [comment]
Am also looking for the same function as in SnagIt 
Use-case: after using the magic eraser, removes the space between 2 sections (full width or height + range)

**Comment by jonadem** [comment]
I am also looking for this feature. Can it be reopened ?

**Comment by SullyPanda76cl** [comment]
+1 to reopen it.... 
this is a very important feature

**Comment by chilirock** [comment]
+1 to re-open issue. I really got used to this feature in other screen capture applications. I would really appreciate it if you would consider adding it to ShareX.

**Comment by Jaex** [comment]
It is already open here: #4513

**Comment by SullyPanda76cl** [comment]
Can we merge these?
[#4366](https://github.com/ShareX/ShareX/issues/4366) 
[#4513](https://github.com/ShareX/ShareX/issues/4513)
[#6026](https://github.com/ShareX/ShareX/issues/6026)

**Comment by emeyedeejay** [comment]
Another +1 - this is one of my most used items in snagit.

**Comment by emeyedeejay** [comment]
> 

I see this is nearing release in another of the threads above - awesome!!!!!
