### ISSUE TITLE
Request: Adding some on-screen info to recordings

### ISSUE THREAD

**Issue by szegi** [ShareX/ShareX#4371]
Hi

I use Sharex often to gif recording
and i need adding some on-screen info to the recording

like
- elapsed time
- title

because when I record and share gif its not so easy to know when it starts
also when you display it online filename doesn't mean anything
so the option to add some on-screen title and timer would be helpful 

Or maybe its somehow possibly and i don't know about it

**Comment by vatterspun** [comment]
This is probably out of scope for the ShareX project.
 
**Possible workaround**: you can do some of this with another project called Screentogif: 

![image](https://user-images.githubusercontent.com/1289134/71601518-bc392c00-2b21-11ea-94b6-9de64f184aad.png)
