### ISSUE TITLE
Request: Gfycat direct URL

### ISSUE THREAD

**Issue by JAK0723** [ShareX/ShareX#4374]
I've seen a "use direct link" option in the destination settings for some hosts, but the destination settings for Gfycat lack such an option.

Would it be possible to add this option for Gfycat? It'd be much more convenient if I was able to get the direct URL immediately after uploading.

**Comment by stuntguy3000** [comment]
The API doesn't explicitly return the direct URL, but it does return the GIF ID. 

The only way to achieve this is to manually form the GIF Link using that GIF ID (if possible), which is probably out of scope of this.
