### ISSUE TITLE
[Bug] Updating ShareX from innate updater installs update in wrong folder

### ISSUE THREAD

**Issue by MusicManiac** [ShareX/ShareX#4375]
So what happened, is that I have ShareX installed on my D drive, and every time I start my Windows it prompts me to update to newest version 13.0.1. And I've been updating it very time. But the fact is that it was creating new directory in C/Program Files/ShareX instead of updating it in the costum install location, which is my D/Apps/Sharex.

Issue: Sharex installs update not in the folder where it's installed, but just to default directory

**Comment by Frenzaih** [comment]
Just letting you know I have the same problem.

**Comment by MusicManiac** [comment]
This issue is still not resolved
