### ISSUE TITLE
Installer erroneously requires accepting the GPL

### ISSUE THREAD

**Issue by chris-morgan** [ShareX/ShareX#4376]
[From the text of the GPL v3:](https://www.gnu.org/licenses/gpl-3.0.en.html)

> 9\. Acceptance Not Required for Having Copies.
>
> You are not required to accept this License in order to receive or run a copy of the Program. Ancillary propagation of a covered work occurring solely as a consequence of using peer-to-peer transmission to receive a copy likewise does not require acceptance. However, nothing other than this License grants you permission to propagate or modify any covered work. These actions infringe copyright if you do not accept this License. Therefore, by modifying or propagating a covered work, you indicate your acceptance of this License to do so.

Yet the installer requires GPL acceptance:

<img alt="Screenshot of the license agreement page of the ShareX installer" src=https://user-images.githubusercontent.com/392868/65207283-8329fe00-dad4-11e9-81ee-0360d7bf5d32.png width=499 height=371>

Here’s what Inkscape does, for reference of an alternative (it’s using NSIS, not sure what ShareX’s installer uses):

![Screenshot of the license agreement of the Inkscape installer](https://user-images.githubusercontent.com/392868/65207439-f59ade00-dad4-11e9-9365-364b2536bd5f.png)

**Comment by vatterspun** [comment]
I see what you're saying here, but the license doesn't expressly forbid an "accept/do not accept."  I can see some advantages of encouraging users to read the license (as you obviously have) and some disadvantages (scary licenses may push away some users).

Not sure what I'd do here.

**Comment by chris-morgan** [comment]
I deem that the license *does* forbid it. Clause 10:

> You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License.

When the license text expressly declares that acceptance is not required, it is a “further restriction” for the installer to require that you accept the license.

**Comment by vatterspun** [comment]
> the license does forbid it

Well anyway, it's not my call.  On a related note, that kind of thinking would pay off in legal circles.  Hopefully you've considered law school.
