### ISSUE TITLE
ShareX doesn’t take per-monitor scaling into account

### ISSUE THREAD

**Issue by chris-morgan** [ShareX/ShareX#4377]
I have a Surface Book and two external monitors. The primary, internal display has a scaling factor of 200%, and the external monitors have a scaling factor of 100%.

ShareX is operating at a scaling factor of 200% regardless of display. I expect it to shrink to half the physical pixel size when I move the window to the displays with a scaling factor of 100%.

ShareX 13.0.1, Windows 10 version 1903, build 10.0.18362.356, and I’m using a fairly large orange cursor with its new pointer size and colour picker.

**Comment by chris-morgan** [comment]
This issue still exists. (Opinion: bots like **stale** are a bad thing in general, and more specifically have no business trying to close out issues which have simply never been responded to in the first place.)

**Comment by jeroen-corteville** [comment]
I'm having the same issue.

**Comment by forcenzw** [comment]
Following

**Comment by chris-morgan** [comment]
They might have renamed @stale to @github-actions, but this business of automatically marking things as stale is still a stupid thing that should be killed with prejudice. Seriously, maintainers, *turn it off*. It’s harmful.

(In other news, I don’t actually care about this any more because I’ve switched to Linux on a new laptop. If the madness and folly of automatically marking issues as stale continues, I won’t intervene any more.)

**Comment by tracybreen** [comment]
I am having the same issue. Would love to know if there's a way to fix it.

**Comment by forcenzw** [comment]
This is still an issue.

**Comment by Rediwed** [comment]
Hi, is there any update on this issue?
