### ISSUE TITLE
Cursor not included in entire screen and active window captures

### ISSUE THREAD

**Issue by chris-morgan** [ShareX/ShareX#4379]
When I use “capture region”, the cursor is included in the screenshot.

When I use “capture entire screen” or “capture active window”, it is not.

The hotkeys are at the default settings, which means that the capture settings are not being overridden in any of these cases.

ShareX 13.0.1, Windows 10 version 1903, build 10.0.18362.356, and I’m using a fairly large orange cursor with its new pointer size and colour picker. Mixed-DPI environment.

----

While this bug exists, the workaround is to use “capture region” and select the active window or the entire screen after that. Slower, but functional.

**Comment by denchat** [comment]
I confirm this issue. Windows 10 v1909. The issue remains even with default cursor.

**Comment by chris-morgan** [comment]
Let it be known that I *hate* the @stale bot and think it should be utterly destroyed from existence. All it has ever done to me is closed genuine issues that simply haven’t been fixed. Really waters down the meaning of “closed” on a ticket, which *should* have meant “it was fixed, or a duplicate, or we decided to definitely not do this”, but now half the time it’s just… there probably wasn’t any will to fix this in the short term. And so then you’ll get duplicates created, because people will be searching *open* issues.

**Comment by chris-morgan** [comment]
They might have renamed @stale to @github-actions, but this business of automatically marking things as stale is still a stupid thing that should be killed with prejudice. Seriously, maintainers, *turn it off*. It’s harmful.

(In other news, I don’t actually care about this any more because I’ve switched to Linux on a new laptop. If the madness and folly of automatically marking issues as stale continues, I won’t intervene any more.)

**Comment by KyodaiKen** [comment]
I am having the same issue again with Windows 11 Moment 4. Double checked that there are no overrides for the hotkeys.
