### ISSUE TITLE
URL shortener goo.gl  not working

### ISSUE THREAD

**Issue by tagplus5** [ShareX/ShareX#438]
Account type: Anonymous

Debug log:

Response:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Value",
    "locationType": "parameter",
    "location": "resource.longUrl"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
 }
}

**Comment by Jaex** [comment]
I tried it now and it is working. Maybe it was to do with URL. What URL you tried to shorten?

**Comment by tagplus5** [comment]
2015-01-05 16:48:09.391 - AddWebError(): Message:
The remote server returned an error: (400) Invalid request.

Response:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Value",
    "locationType": "parameter",
    "location": "resource.longUrl"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
 }
}


StackTrace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
2015-01-05 16:48:09.429 - Task completed. Filename: 2015-01-05_16-48-01_QVnN8zvd.png, URL: https://dl.dropboxusercontent.com/u/1146239/Screenshots/2015-01-05_16-48-01_QVnN8zvd.png, Duration: 7880 ms

**Comment by Jaex** [comment]
That URL not even work in their web site: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/01/5rAU2bXKOn.png) so their API have problem and not to do with ShareX.

**Comment by Jaex** [comment]
Other people reported it here: https://groups.google.com/forum/#!searchin/google-url-shortener/invalid$20value/google-url-shortener/4WsJRAK8hsY/pZezW5B6CCoJ
