### ISSUE TITLE
Red "X" Appears Instead of Picture When Uploading 

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#4382]
Any ideas why this occurs?

![error](https://user-images.githubusercontent.com/42359733/65376424-332e7100-dc65-11e9-8049-330cf4202a8b.JPG)

**Comment by josborne26** [comment]
Does this happen with every image file?  Does it happen only when uploading to Dropbox?  Does it happen every time you attempt to upload this specific file?
