### ISSUE TITLE
Colour identifier for picker

### ISSUE THREAD

**Issue by mythofechelon** [ShareX/ShareX#4385]
As a partially colour blind person, it would be very useful if ShareX's colour picker could identify the colour too. I'm guessing that a colour code chart like https://www.rapidtables.com/web/color/RGB_Color.html would just need to be integrated.

Color Blind Pal is an iOS example of this functionality: https://apps.apple.com/gb/app/color-blind-pal/id1037744228

**Comment by Jaex** [comment]
Finding array of color names is difficult.

**Comment by mythofechelon** [comment]
Did I not give you one (https://www.rapidtables.com/web/color/RGB_Color.html)?

**Comment by Jaex** [comment]
It is not array. Manually copying them would be insane amount of boring repetitive work.

**Comment by mythofechelon** [comment]
I've gotten pretty good at doing things like that efficiently. What format do you need it in?

**Comment by Jaex** [comment]
I noticed I could just enumerate https://docs.microsoft.com/en-us/dotnet/api/system.drawing.knowncolor?view=netframework-4.8 from AliceBlue to YellowGreen. So I'm adding it now.

**Comment by Jaex** [comment]
https://jaex.getsharex.com/2019/10/1JAllqQxjR.mp4

**Comment by mythofechelon** [comment]
That's awesome! I look forward to it! Thank you!

**Comment by mythofechelon** [comment]
Is there any chance that you could add this to the actual picker itself? Something like this:
![2020-09-11 18-32-41 - Windows_10_Pro_64-bit_2_(DL)_ Running _-_Oracle_VM](https://user-images.githubusercontent.com/28054556/92955821-c86ddb00-f45d-11ea-9974-1a6e24ae0ac3.png)

Thanks.
