### ISSUE TITLE
Unable to download ffmpeg.zip - (403) Forbidden 

### ISSUE THREAD

**Issue by sarangb1** [ShareX/ShareX#4386]
There is an error downloading "ffmpeg.zip" inside ShareX.

I am using Tor VPN, if your CDN site is using Cloudlfare, please make an exception for Tor users, you can follow this guide to make it quickly - https://github.com/allow-tor/on-cloudflare

![Capture](https://user-images.githubusercontent.com/55713440/65453928-6a0ead80-de44-11e9-8495-2622a58470e9.PNG)

**Comment by Jaex** [comment]
It is hosted on https://ffmpeg.zeranoe.com/builds/
