### ISSUE TITLE
Documentation and Tutorials for ShareX

### ISSUE THREAD

**Issue by polato94** [ShareX/ShareX#4393]
ShareX has a lot of functions and is getting more and more complex. I would suggest you to create a documentation or tutorial to make it easier for new ShareX-User.

I would recommend the following pages for documentation:
- [docusaurus.io](docusaurus.io)
- [readthedocs](https://readthedocs.org/)

**Comment by Jaex** [comment]
My english is not good enough to make whole documentation of ShareX.

**Comment by polato94** [comment]
i thought the open source community would have helped you, but it's your decision. :)
