### ISSUE TITLE
Specific file name for automatic screenshot

### ISSUE THREAD

**Issue by Bruneux** [ShareX/ShareX#4394]
Hi

I am able to make automatic screenshot every 5 seconds. But I would like to have specific file name scheme like image1.png, image2.png, image3.png, etc.

Is there a way to do this ?

Thanks

**Comment by telusss** [comment]
I need something exactly like this.

Before the app generated the screenshort with the date created and sorted them in sequential order, now with the new update the random pattern of naming images simply made the use of the app unfeasible in my case.

**Comment by Jaex** [comment]
You can customize file naming:

![](https://jaex.getsharex.com/2019/09/chrome_Ytid9PJciC.png)

**Comment by Bruneux** [comment]
Ok thanks.

What if I wanted to keep the same file name that would automatically overwrite, without asking me for confirmation?
