### ISSUE TITLE
Azure text uploads do not have a character encoding

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#4395]
Uploading text from my clipboard sends text without a encoding header (I assume). This means azure has nothing to return back to users who request the file

This can result in Unicode text being decoded as US-ASCII incorrectly by a web browser

**Comment by Scrxtchy** [comment]
Harder then I thought looking into this, because I have lost track with a lot of how ShareX works. As Azure is a generic file uploader, it can easily get the mime type from the file, but I would still have to look into how it is treated when used with text uploading and providing specific instructions when done so.

After that, being able to determine the encoding from file/clipboard is the second task

**Comment by Scrxtchy** [comment]
Discussion now has recent activity but I have nothing new to report

**Comment by Scrxtchy** [comment]
I should fix this one day

**Comment by Scrxtchy** [comment]
😒

**Comment by pointydev** [comment]
I'd also like to see this issue be fixed, as I have a similar experience on the custom file host I use, as it serves the Content-Type that is uploaded by the client.
