### ISSUE TITLE
ShareX 8.5 - Delay before capture missing !

### ISSUE THREAD

**Issue by sparxz** [ShareX/ShareX#44]
ShareX 8.5 - Delay before capture missing !

I really appreciated this feature and used the delay most of the time.
Cannot now find the setting to turn it on now, or find reference to delay
in the online manual.
Can it be re-enabled some other way ?
All Linux screen shot grabbers have delay built in, I was delighted when I found an open source on Windows platform too.

**Comment by deltreey** [comment]
your link is a 404, and you're the top 10 google results for this search.  Could you please update @Jaex ?

**Comment by Jaex** [comment]
This?

![](https://dl.dropboxusercontent.com/s/yejxgmvgh5ysie0/ShareX_h4h83J8qsf.png)
