### ISSUE TITLE
Automatic scrollbar removal

### ISSUE THREAD

**Issue by mythofechelon** [ShareX/ShareX#4411]
It'd be great if ShareX had an option to automatically detect and not capture / remove the scrollbar in windows.

I'm guessing that ShareX could detect the OS and application and adjust the capture area accordingly. For example, Google Chrome's Windows scrollbar is 17px wide and located on the immediate right-hand side of the capture area.

Example of the area to not capture / remove in a region capture:
![2019-10-05_12-43-16 - ShareX_-_Region_capture](https://user-images.githubusercontent.com/28054556/66254432-25511380-e76e-11e9-84c1-6c9f85974f32.png)

Example of the "right" value to not capture / remove the area in a scrolling capture, before and after:
![2019-10-05_12-47-32 - ShareX_-_Scrolling_capture](https://user-images.githubusercontent.com/28054556/66254489-b2946800-e76e-11e9-9eae-f46749d3f9ca.png)
![2019-10-05_12-47-43 - ShareX_-_Scrolling_capture](https://user-images.githubusercontent.com/28054556/66254490-b58f5880-e76e-11e9-93a3-81bb1bf9e887.png)

**Comment by Scrxtchy** [comment]
Browsers are weird because the width can be adjusted by the site administrator, it would not be wise to give them a static option based on a single page.
Mapping these out for different programs would be a cumbersome and cluttering task

**Comment by mythofechelon** [comment]
@Scrxtchy I appreciate that but, in my experience, 99 % of the time the scrollbar is the same size so maybe just an option to set a personal default?
