### ISSUE TITLE
Overwriting a file during automatic screen capture

### ISSUE THREAD

**Issue by Bruneux** [ShareX/ShareX#4413]
Hi

Is it possible to save a file with the same name during an automatic screenshot every 5 seconds and without warning? In other words, overwrite without prompt.

Thanks

**Comment by Jaex** [comment]
If you edit file naming pattern to have static name then it would save with that name always and you can disable file name warning too. Then you can run auto capture with 5 sec interval. You can even have these settings specific to auto capture hotkey only, that way your default settings won't be affected. And then you can run this from workflow menu, not need to use hotkey.
