### ISSUE TITLE
Lost ability to draw lines / arrows / shapes etc in Sharex 13.1

### ISSUE THREAD

**Issue by mhoneywill** [ShareX/ShareX#4418]
I can add these objects but they seem to be drawn in transparent ink. So I can only see the drag circles but not the added object. I eventually found out that my border size had been set to 0. Maybe it would be good to limit this to a minimum of 1

![image](https://user-images.githubusercontent.com/3499580/66476670-1af48980-ea8e-11e9-9f75-e83de93b31f8.png)

**Comment by Jaex** [comment]
There is a reason it is not limited to minimum 1 because rectangle etc. also using same setting and it can be set 0 to hide border.

**Comment by mhoneywill** [comment]
Thanks for quick reply :-) 
It just took me ages to find out why I couldn't see the arrows that I was adding. If I set this to 0 and I draw rectangle, I can't see them. What use is that? maybe there is a valid use I'm just not aware of it.

**Comment by Jaex** [comment]
Initially I told that I can't set minimum 1 to that border size option (numeric up down control) but while drawing those shapes I can do that limiting inside codes, that way border size configuration won't be affected and minimum restriction will be only applied to shapes which is necessary.

**Comment by Jaex** [comment]
But still limiting that in line and arrow not gonna solve your rectangle drawing issue because it is expected that user can have no border but fill color.

**Comment by Jaex** [comment]
Finally I could reproduce this issue. It is related to cursor tool added in pull request #4015.

If you draw text which have border size 0 and then use cursor tool to select the text and afterwards try to draw line then border size of line sets to 0.

@Danielku15 can you check the issue?

**Comment by mulfunction** [comment]
But where can I set the border size?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2019/11/ShareX_0JOVjHsasX.png)

**Comment by mulfunction** [comment]
Thanks so much
