### ISSUE TITLE
Change Border Color, Font Color, Border Thickness via Workflows?

### ISSUE THREAD

**Issue by ShowGoShane** [ShareX/ShareX#4419]
Sorry for the rookie question, but, is there a way to do the following (via Workflows or otherwise)?

**Let's say, Press CTRL + SHIFT + W, then...**
For the Speech Balloon, 
Fill Color Change to RED
Font Color Change to BLACK
Change Border thickness to 3

**THEN, when I Press CTRL + SHIFT + O, then...**
For the Speech Balloon, 
Fill Color Change to GREEN
Font Color Change to WHITE
Change Border thickness to 1

Thank you, in advance, for your consideration and reply.

**Comment by Jaex** [comment]
No.
