### ISSUE TITLE
Please add a way to bypass ssl check with YOURLS

### ISSUE THREAD

**Issue by gyratory** [ShareX/ShareX#442]
Hi, I'm running yourls on my own server but when I attempt shortening URLS, sharex aborts the attempt because I'm using a self-signed certificate.  It would be awesome if there was a checkbox or option in the advanced menu to call the SSLBypassHelper.

Here's the debug:
> StackTrace:
>    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
>    at System.Net.HttpWebRequest.GetRequestStream()
>    at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
> 2015-01-05 23:10:38.693 - Task completed. Filename: 2015-01-05_23-10-32.png, URL: removed, Duration: 6336 ms
> 2015-01-05 23:11:18.228 - UploadersConfig save started: D:\ShareXmod\UploadersConfig.json
> 2015-01-05 23:11:18.280 - UploadersConfig save successful: D:\ShareXmod\UploadersConfig.json
> 2015-01-05 23:11:48.169 - Hotkey triggered: Hotkey: Ctrl + Shift + 4, Description: Capture rectangle region, Job: RectangleRegion
> 2015-01-05 23:11:53.239 - Task in queue. Job: Job, Type: File, Host: Google Drive
> 2015-01-05 23:11:53.240 - Task status: Preparing
> 2015-01-05 23:11:53.248 - Upload started. Filename: 2015-01-05_23-11-53.png
> 2015-01-05 23:11:56.823 - AddWebError(): Message:
> The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

**Comment by riesza** [comment]
I don't know if this is a similar problem but I've been getting these when trying to upload through puush
![Uploading e3258a414c[1].png . . .]()

**Comment by gyratory** [comment]
After looking for a workaround, I tried Cloudflare's Universal SSL and ended getting another error.  However this only occurs when I trigger hotkeys or upload a file.  When I manually shorten the Google Drive link with YOURLS it works correctly and provides a shortened url.
On the other hand, I gave my friend an account to test and he has had no problems shortening urls with Cloudflare enabled.
```
2015-01-13 21:42:32.684 - Task in queue. Job: Job, Type: File, Host: Google Drive
2015-01-13 21:42:32.684 - Task status: Preparing
2015-01-13 21:42:32.721 - Upload started. Filename: 2015-01-13_21-42-32.png
2015-01-13 21:42:39.704 - AddWebError(): Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
2015-01-13 21:42:39.705 - Task completed. Filename: 2015-01-13_21-42-32.png, URL: removed, Duration: 7020 ms
```

**Comment by gyratory** [comment]
Solved the SSL/TLS secure channel issue by uninstalling ShareX, deleting all configuration files, and reinstalling.  The original issue with selfsigned certs can be worked around by using cloudflare's ssl or getting a signed ssl cert.
