### ISSUE TITLE
Exporting of settings should not export history by default

### ISSUE THREAD

**Issue by usego** [ShareX/ShareX#4422]
It is very unobvious that exporting of settings includes history too. We have just discovered a security leak because of few screens were shared with sensitive info with paths stored in history and ShareX configuration was exported to public storage to make setup easier within the company.

Please add a checkbox "include history" in export dialog unchecked by default. At least this will make things obvious.

**Comment by Jaex** [comment]
I agree it was not obvious thats why I added note to that tab 14 days ago (https://github.com/ShareX/ShareX/commit/9d9742dfb5348462b9cade063eda7ee157e4b7a1) like this:

![](https://jaex.getsharex.com/2019/10/ShareX_lXmS0yjQls.png)

**Comment by kmakarevich2** [comment]
This is a serios security issue, I recommed fix it asap

**Comment by Jaex** [comment]
Added check boxes to allow selecting what to export:

![](https://jaex.getsharex.com/2019/10/ShareX_UjmRMZNJ9s.png)
