### ISSUE TITLE
Vgy.me now gives out 422 (Unprocessable Entity) error code

### ISSUE THREAD

**Issue by Aholicknight** [ShareX/ShareX#4432]
![ShareX_y4StXanxJ3](https://user-images.githubusercontent.com/7843719/66963788-2faac180-f03a-11e9-9d06-586387ffe422.png)
Vgy.me now gives out an error code with the message:
`Response text:
{"error":true,"messages":{"Unauthorized":"You are not logged in, or your account has been banned. You cannot upload anonymously."}}`
Should this uploaded be removed now?

**Comment by ouTPhaze** [comment]
I'm having this issue currently.
