### ISSUE TITLE
URL is empty.

### ISSUE THREAD

**Issue by trifo13** [ShareX/ShareX#4437]
Hi.

From a few weeks I started getting: "URL is empty." when using FTPS for image uploads.

It used to work flawlessly for years and just stopped without nothing changed on my end and if I recall correctly - weeks after the 13.0.1 update.

Switching to FTP resolves the problem though.

When testing the settings with the SFTP protocol, I get the successful Connected! message, but trying to upload the image results in the error - URL is empty.

Thanks for the great product!

Best Regards,
Trifo.

**Comment by GH-Rake** [comment]
Still an issue, I have the same history.  Worked fine until around October of last year.  The file gets uploaded but it's just a 0 byte file and the only error you get from ShareX is "URL is empty".

**Comment by MasterCevin** [comment]
Jaex I can provide you an FTPS Server (explicit), if you want to use it.
I am getting the same error ("URL is empty")

**Comment by GH-Rake** [comment]
This should not be closed, this is an active problem that has still not been resolved that makes it impossible to use for uploading screenshots via FTP.

**Comment by MasterCevin** [comment]
> This should not be closed, this is an active problem that has still not been resolved that makes it impossible to use for uploading screenshots via FTP. There are complains all over the place about this issue.

This is true because I still have this Problem today and it is still a huge risk to just upload via ftp (because ftps isn’t working and sftp is a security Risk if you have one Server with multiple „isolated“ users

**Comment by GH-Rake** [comment]
It works on regular FTP for you?  It does not work on any FTP at all for me

**Comment by MasterCevin** [comment]
> It works on regular FTP for you? It does not work on any FTP at all for me

Can I contact you via teamspeak or discord? Maybe I’m able to resolve your issue with ftp

**Comment by Ichigo69** [comment]
Yes, this needs to be solved. I am also having this issue sftp on the latest version of Win10

**Comment by MasterCevin** [comment]
@GH-Rake Can I contact you via teamspeak or discord? Maybe I’m able to resolve your issue with ftp

**Comment by GH-Rake** [comment]
> @GH-Rake Can I contact you via teamspeak or discord? Maybe I’m able to resolve your issue with ftp.

Just say it here

**Comment by EzzPrograms** [comment]
Also got the same error that URL is empty but with an exception:
```
2020-12-30 14:41:13.416 - Task in queue. Job: FileUpload, Type: File, Host: FTP
2020-12-30 14:41:13.439 - Task status: Working
2020-12-30 14:41:13.448 - Upload started. Filename: 14-41-13.png, Filepath: C:\Users\[User]\Documents\ShareX\Screenshots\2020-12\14-35-10.png
2020-12-30 14:41:13.516 - Task failed. Filename: 14-41-13.png, Errors:
URL is empty.
2020-12-30 14:41:16.923 - Exception:
System.ArgumentException: Win32 handle that was passed to Icon is not valid or is the wrong type.
   at System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   at System.Drawing.Icon.FromHandle(IntPtr handle)
   at ShareX.HelpersLib.NativeMethods.GetFileIcon(String filePath, Boolean isSmallIcon)
   at ShareX.HelpersLib.ImageFilesCache.GetFileIconAsImage(String filePath, Boolean isSmallIcon)
   at ShareX.MainForm.UpdateActionsMenu(String filePath)
```
Not sure if it's related to the cause of the URL is empty error, but every time the upload fails this exception is bundled with it.

**Comment by MasterCevin** [comment]
> > @GH-Rake Can I contact you via teamspeak or discord? Maybe I’m able to resolve your issue with ftp.
> 
> Just say it here

Is the destination host your own Server with some ftp Server installed on it or is the destination host some server where the Hoster gives you the ftp login details and manages the ftp server software?

**Comment by GH-Rake** [comment]
> > > @GH-Rake Can I contact you via teamspeak or discord? Maybe I’m able to resolve your issue with ftp.
> > 
> > 
> > Just say it here
> 
> Is the destination host your own Server with some ftp Server installed on it or is the destination host some server where the Hoster gives you the ftp login details and manages the ftp server software?

I self host Pure-FTPD on a VPS, so I have full control
https://www.pureftpd.org/project/pure-ftpd/

**Comment by MasterCevin** [comment]
You could turn ftps off and use regular ftp but it's a security risk when transferring sensitive data.
Another option is to use sftp instead because it is encrypted and you could use a key for authentication but there also is a security risk because if the login credentials get compromised the attacker could in the worst case full access to the server or in the best case only delete the files which the attacker has permissions to and/or can get some more information about the system.
Ether way I hope that the issue with FTPS will get fixed soon because it's an important protocol to get more security when uploading files directly to your server.
