### ISSUE TITLE
QuickCrop + Image editor

### ISSUE THREAD

**Issue by RDeluxe** [ShareX/ShareX#444]
I don't manage to make QuickCrop and "open in image editor" work together. QuickCrop is set to "true", but as soon as I add the action to open in image editor, the quickcrop stops functionning, and I have to press enter.

Is this me or is there a bug there ?

**Comment by Jaex** [comment]
I always use quick drop and open in image editor together.

**Comment by RDeluxe** [comment]
Well, without changing anything it's working now, after some closing/opening of the app. Damn, I feel dumb now. Wondering if it could be because of Dropbox (I store my ShareX portable install in there).
