### ISSUE TITLE
how to rename an image you just took?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [ShareX/ShareX#4443]

**Comment by jmvermeulen** [comment]
I would like a naming template for region snapshots. Now the filename is very random and that's not pratical.

**Comment by SolveAllProblemsRightNow** [comment]
hello anybody how to do the renaming? 

im just gonna uninstall this software for now, all the basic things that everything else does this doesnt do

**Comment by Fuzzqt** [comment]
Task Settings > File Naming > click on either name pattern for which capture method. A drop down box should pop up with options, for me personally I just like the date it was captured so you can also use this string %mo_%d_%yy (you an add exact hour and time if you want by looking at the date and time section) but there are many other options there as well. 

You can always right click the file name and change it if you put Open in File explorer in your hotkey settings.

**Comment by jmvermeulen** [comment]
This only works when selection the region, not when using a hot-key to capture the last region again. Using the hot-key makes a random name again.

**Comment by KesKim** [comment]
I take a lot of screenshots of software and code in some specific state I need to use to elaborate workflows and issues, etc. That means automatic pattern naming doesn't do anything for me when I want to name something as [ProjectName]-[SetupSituation]-[Issue]-[SlideNumberI'mGonnaUseItOn].jpg or something.

Yes, I can open this file in Explorer and rename it there, but then the ShareX main window / task list loses it's link to the file, gets scattered with dead links to now-renamed random/pattern-named files and becomes a chore or almost pointless to use beyond clicking that "open containing Folder"-button before renaming the files.

An internal rename-function/context menu item to ShareX would be vastly preferable and could still retain the Task List useability and linking.

**Comment by neiljthomson** [comment]
+1 for better renaming.

This would include tagging multiple images in the list and allowing a prefix (e.g. project name) and time sequential numbering (ideally configurable)

**Comment by snu7** [comment]
+1 for renaming

In ShareX you can use has elaborated pattern to name recordings. 
But a option to simply rename recordings I am missing. 
Often I do not know how to name before I have recorded.

**Comment by marcinsmialek** [comment]
+1 for reopening this issue

It's a common case for me to capture an image, and then if it's special, rename it.
Doing so externally breaks history and adds unnecessary steps. I've spent some time looking for such an option, and I was surprised it's not there. If you paired it with Exif tags, it would be even better.

**Comment by randoomdude** [comment]
> I take a lot of screenshots of software and code in some specific state I need to use to elaborate workflows and issues, etc. That means automatic pattern naming doesn't do anything for me when I want to name something as [ProjectName]-[SetupSituation]-[Issue]-[SlideNumberI'mGonnaUseItOn].jpg or something.
> 
> Yes, I can open this file in Explorer and rename it there, but then the ShareX main window / task list loses it's link to the file, gets scattered with dead links to now-renamed random/pattern-named files and becomes a chore or almost pointless to use beyond clicking that "open containing Folder"-button before renaming the files.
> 
> An internal rename-function/context menu item to ShareX would be vastly preferable and could still retain the Task List useability and linking.

This, you should both be able to rename the file and still have it accesible within sharex instead of totally loosing the ability to interact with it once you change it in explorer

**Comment by gradyking** [comment]
I found a way to do this, if you enable After Capture Tasks -> Show "After Capture" Window, you immediately get a pop-up where you can rename the file. No broken links

![Image](https://github.com/user-attachments/assets/f45dfc6a-a713-4204-8c05-ba9fbcfdd043)

**Comment by dullahan8** [comment]
> I found a way to do this, if you enable After Capture Tasks -> Show "After Capture" Window, you immediately get a pop-up where you can rename the file. No broken links
> 
> ![Image](https://github.com/user-attachments/assets/f45dfc6a-a713-4204-8c05-ba9fbcfdd043)

This helps, but in the case where I only need to rename a file once in a blue moon I don't want to have the after capture window open up every time.

The best solution would be to have the ability to right click an item and rename it there. Or perhaps the ability to rename an item by double clicking the name of the file in the main window. This should trigger ShareX to rename the file on the file system as well as update all its internal links.

**Comment by Unknow0059** [comment]
Reopen the issue.
I often use ShareX's "Cut out" feature from the image editor but I need the file renamed to something else while having access to that, for which ShareX needs to be able to locate the file. It cannot do that unless it's name is known to the program.
@Jaex
