### ISSUE TITLE
how to set the default save location of the images you take?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [ShareX/ShareX#4444]

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/67208709-b956f680-f461-11e9-8e70-67e24d28a979.png)

**Comment by SolveAllProblemsRightNow** [comment]
that's solid, how to do this https://github.com/ShareX/ShareX/issues/4443

**Comment by SolveAllProblemsRightNow** [comment]
hello anybody how to do the renaming? https://github.com/ShareX/ShareX/issues/4443

im just gonna uninstall this software for now, all the basic things that everything else does this doesnt do
