### ISSUE TITLE
Add libopus as Audio codec in "Screen recording options"

### ISSUE THREAD

**Issue by MaxLebled** [ShareX/ShareX#4446]
libopus offers much better audio quality than the default aac encoder. More importantly, it doesn't waste anywhere near as many bits if there is no audio playing: the effective bitrate drops to roughly a quarter of the selected bitrate (e.g. 128k drops 32k, 64k drops to 18k), whereas the aac encoder takes up its full bitrate no matter what.

Opus streams are supported by the mp4 container.

You can try it yourself by ticking "use custom commands" and changing `-c:a aac` to `-c:a libopus`

**Comment by Scrxtchy** [comment]
I got this working in https://github.com/Scrxtchy/ShareX/commit/7149408658684a17a68d7ba181522194041e799c

want to test it properly before doing a PR. Seems to work though
![image](https://user-images.githubusercontent.com/12771982/67206849-2b2d4100-f45e-11e9-8f0c-dcfd30ba9c74.png)
