### ISSUE TITLE
Gif doesn't copy as gif, only as first frame

### ISSUE THREAD

**Issue by goldserg** [ShareX/ShareX#4448]
I want record gif and after copy this gif in clipboard for paste in Skype or I want copy resulted gif from context menu "Copy"-"Image (Alt+C)".
When I copy, only the first frame gets to the clipboard. Copying a file doesn't help either.

**Comment by Scrxtchy** [comment]
Windows clipboard does not store animated content, if you want to upload the gif you will need to upload the file. You can do this by dragging the file from ShareX to Skype, or using Copy-File (Shift+C) and then pasting (Some software does not support this)

**Comment by goldserg** [comment]
Drag work, but copy file not work...

ср, 23 окт. 2019 г., 6:12 Scratch <notifications@github.com>:
