### ISSUE TITLE
how to make close actually close it (without  minimising to tray)?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [ShareX/ShareX#4449]

**Comment by Jaex** [comment]
Disable tray icon:

![](https://jaex.getsharex.com/2019/10/ShareX_pqRtdC9kU6.png)

**Comment by SolveAllProblemsRightNow** [comment]
that doesnt say it doesnt minimise to tray, and that it actually closes

it just says that it doesnt 'show the tray icon'

**Comment by Jaex** [comment]
When there is no tray icon, app can't be minimized to tray icon...

**Comment by SolveAllProblemsRightNow** [comment]
i want to close it like any other apps when you press 'x'

this is not closing it

it's still open and using memory so it's still no closed?

**Comment by SolveAllProblemsRightNow** [comment]
reopen this, you dont understand the problem

let someone else answer it

**Comment by CubityFirst** [comment]
Hiya @SolveAllProblemsRightNow 

I think there's a little bit of a misunderstanding here, Jaex is the main and only core developer of the ShareX Project.

If you follow his advice, and untick that single box, when you click close on the program (via X in the top right hand corner), it will actually close and the process with cease to exist from then on until you decide to open it again, then it's not using any resources, or any CPU time at all. 

He does understand the issue, and gave you the correct & appropriate response to your issue.

**Comment by SolveAllProblemsRightNow** [comment]
tried it again, it actually closed this time

think it's bugged the first time you put that setting

the wording is still completely wrong, un-descriptive, and not accurate unlike many other apps (discord, etc.) that actually has correct wording 

so that still needs to be fixed

**Comment by SolveAllProblemsRightNow** [comment]
hello anybody how to do the renaming? https://github.com/ShareX/ShareX/issues/4443

im just gonna uninstall this software for now, all the basic things that everything else does this doesnt do

**Comment by alanbork** [comment]
what a bad UI choice (still this way in 2023)
