### ISSUE TITLE
URLs not opening

### ISSUE THREAD

**Issue by SeraphineX** [ShareX/ShareX#445]
Hey there, just installed ShareX last night and I set a task to open the URL after uploading an image and I noticed it doesn't work, I want to upload the screens I take to an imgur album so I figured I should add my account. 

After that I tried to open the authorization page of imgur but nothing happens when I click the authorize button. This happens with every URL (images) and the other sites like Drive, Dropbox, etc.

**Comment by Jaex** [comment]
If your browser not opens then ShareX can't do anything about it. Try to run ShareX as admin and try to close your browser if you have it open already and try again. Also authorization url must be in debug log too.

**Comment by SeraphineX** [comment]
Thanks, seems to work now after I ran ShareX as admin. Silly mistake from my part I guess.

**Comment by Jaex** [comment]
Normally ShareX not require to be run as admin for browser to open too. Something must be different in your computer.
