### ISSUE TITLE
editor icon size?

### ISSUE THREAD

**Issue by peixotorms** [ShareX/ShareX#4450]
Is there any way to resize the icon size on sharex, as well as menu?

My laptop is 15.6, 1980X1920 and it resizes to 125%.
https://i.imgur.com/Eu6Zx3u.png

But then sharex menu and more importantly, the editor icons on top are too small.
I would like to increase my icon sizes or if possible, all the menus.
Any tricks or ways to do it on 13.0.1?

**Comment by brain8891** [comment]
I agree with @peixotorms,
I use ShareX along with other image editor because of the small icons:
![image](https://user-images.githubusercontent.com/7104190/89185787-da7d7380-d5ab-11ea-907f-4c881bc1abb8.png)
