### ISSUE TITLE
How can I remove all Imgur links anonymously?

### ISSUE THREAD

**Issue by FLawLesSTaStE** [ShareX/ShareX#4451]
I know that I can right-click and pick Deletion URL... but when I pick all of them I can not do it. 
I have no skills in coding or scripts... please can you do an update with it, I beg you. I did not know until 1 year later that it is uploading to  Imgur... which is my bad also. Any advice or help would be so appreciated. People see my images even tho I did not share the link it is weird. 

With respect,

-FtS

**Comment by Jaex** [comment]
Duplicate of #1335
