### ISSUE TITLE
Suggestion - Enter key creates a new line and ctrl+enter accepts changes in editor

### ISSUE THREAD

**Issue by stephen147** [ShareX/ShareX#4452]
See attached the suggestion. This would feel more natural to me.

It would be nice perhaps to have this as an option for those that prefer this behaviour.

Thanks.

![5Tjb5IQOyp](https://user-images.githubusercontent.com/14054664/67486363-d2c79080-f663-11e9-881a-5c7bf7100ea3.png)

**Comment by JeremyCrookshank** [comment]
Makes sense to me from a UX POV
