### ISSUE TITLE
Don't see line, arrow in editor screenshot

### ISSUE THREAD

**Issue by StAlKeRxXl** [ShareX/ShareX#4456]
Hello! I use win10
but one problem:
![wur3CJcCf9](https://user-images.githubusercontent.com/19319937/67619934-a4d47e80-f812-11e9-8512-9cf3ec368d3c.gif)

**Comment by Jaex** [comment]
Border size is 0, increase it to see line.

**Comment by Jaex** [comment]
Duplicate of #4418
