### ISSUE TITLE
Unable to use NextCloud

### ISSUE THREAD

**Issue by Avijojo** [ShareX/ShareX#4458]
Hello,
I'm running a nextcloudpi server off of a raspberry pi off of my local network (nextcloudpi is just nextcloud but for raspberry pi), and I can't seem to upload anything to it, whenever I try I get this error:
```
Error message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Request URL:
https://192.168.0.190/remote.php/webdav/waterfox_1hA3JSgvlU.png

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
```

**Comment by OH6BPL** [comment]
The certificate is not valid. So it's should not even work. They could add "trust all certificates" option.

**Comment by Avijojo** [comment]
Makes sense, is there anyway to fix this problem, or to force it to trust the certificate?

**Comment by OH6BPL** [comment]
You really don't need to use https in the internal network. So it would be easy to just upload with http and allow it from the nextcloud.

**Comment by Avijojo** [comment]
Okay, I'm also using nextcloud with other people as well, but I guess I'll just use and allow http. Thanks for your help!
