### ISSUE TITLE
Hotkey: Screen color picker

### ISSUE THREAD

**Issue by tabweg** [ShareX/ShareX#446]
Hi.

Is is possible to launch not the window of Color Picker but the option when you click on the pipette icon and you have the cursor with zoom by side.
And after clicking with LMB (like selecting desired point on screen) is is possible to not open the Color Picker window but have an option to put into clipboard the HEX color of clicked point ?
It would be fantastic.

**Comment by Jaex** [comment]
What if I need RGB color of clicked point.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/01/ShareX.vshost_9ORZUOWJyY.png)

**Comment by Somnius** [comment]
i'd also like that, to pick the cursor color and copy html value (#xxXXxx) on the clipboard

**Comment by Jaex** [comment]
It is already added 2 months ago:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/04/ShareX_B4ebqf3oRs.png)

**Comment by Somnius** [comment]
Thank you very much! Going to see if i can assign it to a hot key!

**Comment by Jaex** [comment]
You can.

**Comment by Somnius** [comment]
Ok saw the "Add" on the hotkeys, configured on Advanced for the $hex but as the following video shows https://www.sendspace.com/file/bnfy9o i don't know what to select to make this hotkey only get the color and copy it to clipboard! Help?! :D

**Comment by Jaex** [comment]
You should upload videos to somewhere which supports playback like Dropbox.

**Comment by Somnius** [comment]
Sure.. check it here!
https://db.tt/VY3qflwu
i'm used to sendspace cause it's free for stuff i don't need to keep!

**Comment by Jaex** [comment]
Screen color picker task.

**Comment by Somnius** [comment]
I've seen only the *Task: Color Picker*
as shown in the snap http://i.imgur.com/o6Xv1Sk.png

**Comment by Jaex** [comment]
Use Screen color picker task!

**Comment by Somnius** [comment]
Just saw it.. but you know something.. to open up the dialog just to click on the picker and then pic, and then after that get the result an all forms, it's quite nice.. i'll keep my way that displays the dialog first!

![image](https://cloud.githubusercontent.com/assets/144157/7022683/02b00af2-dd37-11e4-8c20-d5e4e7d9712c.png)
