### ISSUE TITLE
Deploy ShareX via SCCM / AutoConfiguration.json

### ISSUE THREAD

**Issue by SentryRaven** [ShareX/ShareX#4460]
I want to deploy ShareX with SCCM, but I also want to disable the Upload fuctionality.
I understand I can edit this in AutoConfiguration.json, however this is only post-installation, as far as I can tell. Since SCCM does not use the same user that triggers the installation, but a system account, I cannot really script this, except for ALL user profiles, which is not an elegant method.

Referenced in [https://github.com/ShareX/ShareX/issues/3590](https://github.com/ShareX/ShareX/issues/3590) I saw that:

> Besides, you can deploy it with an accompanying config file which has uploads disabled.

On the website for ShareX, I can only find setup parameters for /SILENT /VERYSILENT installation, but how would I also have the installer use a preprepared autoconfiguration file that disables the Upload functionality? Is this even implemented or is the above comment referring to scripted solutions?

**Comment by jpsv** [comment]
Where do I find AutoConfiguration.json and how do I use it? I wouldn't mind applying it to all user profiles upon first launch, but I'd like them to be able to edit their own configs after installation.
