### ISSUE TITLE
How to ensure image editor always pre-selects JPG format with 'Save as?'

### ISSUE THREAD

**Issue by cagross** [ShareX/ShareX#4461]
When I take a screenshot, I have ShareX configured to open the screenshot for editing, using its built-in editor.  When that occurs, the file is temporarily saved as a JPG ([screenshot](https://i.imgur.com/H2dhXKR.jpg)).  But in the image editor, when I click 'Save as' the file type in the 'Save as' dialogue is set to PNG ([screenshot](https://i.imgur.com/DFJ0aVV.jpg)). How can I ensure this is preset to JPG whenever I click 'Save as?'

I have tried modifying Task settings, Hotkey settings, and Application settings in ShareX, but none seem to change this behavior.

Thanks.

**Comment by Jaex** [comment]
Image editor opens before file is saved, but you told it is saved as jpg before that? Image editor can't know what it gonna be saved as because saving image doing some work to check png size and automatically change it to jpg. And because until reach file saving there is multiple image processing also can happen, it is impossible for image editor to know end result hence it can't predict extension.

**Comment by cagross** [comment]
Thanks for the reply. 

I may have misspoke in my earlier message. So to clarify, here is what I am describing:

* I press the ShareX keybind I have created (ctrl + alt + prtsc).
* ShareX takes a screenshot, automatically opens the image editor, and displays the screenshot (as desired).
* If I press ctrl + shift + s to 'Save as,' the 'Save as' dialog box opens ([screenshot](https://imgur.com/DFJ0aVV)).  In it, PNG format is always preset.  I am wondering if JPG can be always be preset, instead of PNG.

Are you saying it is not possible to change the preset image format in the 'Save as' dialog box?

Thanks.

**Comment by Jaex** [comment]
I will add support for it. It is not currently supported.

**Comment by cagross** [comment]
OK no worries, thanks for confirming.  I'll subscribe to releases here and be on the lookout for it.  I appreciate the time and information.  We can call this ticket closed if you want.  Or you can keep it open while you work on the feature--up to you :-)
