### ISSUE TITLE
How to perform ShareX.exe -hashcheck <hashtype> <filepath>

### ISSUE THREAD

**Issue by ariefcfa** [ShareX/ShareX#4464]
Please help, i tried ShareX.exe -hashcheck sha-1 file
but the result is only open "ShareX - Hash check" window
thanks

**Comment by IdpugantiSanjay** [comment]
Can you refer any doc where it is mentions it will work ? 
I don't think this is supported

**Comment by ariefcfa** [comment]
Thanks, I tried to replicate ShareX ImageEditor context menu command but to perform HashCheck. My plan is to create a shortcut in Windows shell:SendTo. In the shortcut target, i experiment with value `..\ShareX.exe" -ImageEditor`, this successfully load a file to ImageEditor program window, but with `..ShareX.exe" -HashCheck` the file is not loaded in HashCheck program window file path.

I can't find if there any documentation about this. I am aware now the issue title is not correct, at the time i think by putting description into the title will get me helped as fast as possible 🤦‍♂️. Sorry
