### ISSUE TITLE
What does sharex use to take the screenshots?

### ISSUE THREAD

**Issue by A-Random-Birb** [ShareX/ShareX#4467]
I would like to know since I'm having issues with the colours, as in every red colour gets oversaturated, then blue and then green. Shares isn't the only program that does this, I e experienced the same thing with green shot and OBS
Is it something to do with my graphics card or something that sharesx uses?

**Comment by Scrxtchy** [comment]
it's using GDI
https://github.com/ShareX/ShareX/blob/1b094a47254519efdb244df26e8108f5ed617e2e/ShareX.HelpersLib/Native/NativeMethods.cs#L329-L330
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createcompatiblebitmap
