### ISSUE TITLE
Opt-in flow to automatically upload screenshots

### ISSUE THREAD

**Issue by shravan2x** [ShareX/ShareX#4468]
I recently learnt that ShareX automatically uploads private screen captures to Imgur by default. I unchecked the option in "After capture actions" immediately.

1. Does it make sense to make this opt-in instead of opt-out?
1. Where do I find the URLs of all previously uploaded images so I can delete them?

**Comment by Jaex** [comment]
1. It is already like opt-in, in your first screen capture ShareX shows this:

![](https://jaex.getsharex.com/2019/11/aDpZYwDFPM.jpg)

and disables upload if you press "No".

2. Open "History" window from main window and then right click "Open -> Deletion URL" to delete them.
