### ISSUE TITLE
Pomf.se account support

### ISSUE THREAD

**Issue by HitomiTenshi** [ShareX/ShareX#447]
Hi, you support uploading to Pomf.se but I can't log into my account for file deletion, uploaded files also aren't in my file list.

Please add the possibility to log into Pomf.se.

Login Page: http://cayootie.pomf.se/user/login/

Creates a cookie after login:
Domain: cayootie.pomf.se
Name: PHPSESSID
Value: \<your session id\>

This cookie is used when uploading images to index them at your file page.
The cookie needs to be refreshed every ~1 hour, otherwise it expires and uploaded images after that aren't listed in your file page.

**Comment by Jaex** [comment]
I won't add account support until they have proper api (like oauth) for it. Because don't like cookie stuff.
