### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#4473]
I am a novice on this program and it's growing beyond my basic needs. Here is what I would request if someone can and knows how. Could you upload a portable version of Share X  configured to capture and display what it captures in the following screen shot. The screen shot is not mine but I want the links to display this way. If you can help I would be much obliged.

**Comment by Jaex** [comment]
Enable this option:

![](https://jaex.getsharex.com/2019/11/ShareX_xSqDhBsbHw.png)

**Comment by jdcollier1968** [comment]
I did that and part of what I am seeking has been corrected. Is there some prerequisite to the above setting to get the links to display like the image below? Nothing pops ups like before after the image uploads.  We're getting there but we're not there yet.

![123](https://user-images.githubusercontent.com/42359733/66728683-fa209100-ee0b-11e9-861d-b86d9ba99b0a.png)

**Comment by Jaex** [comment]
If that window not shows up, that could mean upload not happens?

**Comment by jdcollier1968** [comment]
I can see the image has uploaded because it shows in the windows afterwards but the above window in the image does not appear.

**Comment by jdcollier1968** [comment]
This is all that will show after capture. The image has uploaded because I see it on the host.

![sharexscr](https://user-images.githubusercontent.com/42359733/68100506-eeb20a00-fe8d-11e9-9208-995c2ab9cca5.JPG)

**Comment by Jaex** [comment]
Change image destination to Imgur. Dropbox don't have rest of url formats.

**Comment by jdcollier1968** [comment]
Changed to Google Photos. Something is not right. 

![sharexcr](https://user-images.githubusercontent.com/42359733/68100666-c7a80800-fe8e-11e9-8604-e1789c730485.JPG)
