### ISSUE TITLE
Always-On recording Feature Request

### ISSUE THREAD

**Issue by popbee** [ShareX/ShareX#4479]
I would like to have a sort of "Always-On Recording" (limited to a time window - maybe up to 1 hour?) and be able to easily grab a section of that "time window" afterwards to generate a video out of it to share to others.

My use case is "QA" work:  Essentially one spends a lot of time testing software and suddenly you run into an issue. You want to know what happened going shortly "in the past" and share a snippet of video to others without the need to reproduce what happened within a new "recording" session.

I believe this would be a distinctive and powerful feature. I can't seem to find any screen capturing product doing what I am after.  (correct me if I am wrong here).  You always have to press a "record" button to start recording immediately. You can't just "go in the past and grab a time portion to share it".

I know this is asking for a lot. Tell me if really I am day dreaming. Or if anybody heard of alternatives for my use case.

regards,
Bernard Poulin

**Comment by canpolat** [comment]
What is already possible is that, in the beginning of the test session you start a screen recording and keep it recording until the very end. This will generate a (potentially very large) mp4 file. When you encounter a problem, you can write down the time and once the session is over, you can use another app to cut the resulting mp4 file in pieces, so that you get the exact section you want. Alternatively, you can stop the recording immediately when you encounter a bug and then restart it again. This way, you would know that at the end of every mp4 file is a bug report. You will still need to cut the mp4 files, but it will be much easier to find the exact places in a video (just the last few minutes of every mp4 file).

So, in a way, "always ON recording" is already possible. But that last bit, cutting the mp4 files is something you will need to do manually.

**Comment by popbee** [comment]
Thanks for answering. Yeah of course, I could just start recording and go and edit it afterwards but that's too much a hassle.  You never know in advance if you are going to get a case that is hard to reproduce. Since these are more rare it's not worth it.

Ease of use is really what I am after. If it was very easy, then I would use it always. 

I think this type of workflow where it always record would raise the bar and allow more ad hoc recordings use cases.  Let's say someone plays games and always leaves it on the during the whole session (many hours - knowing that there's a recording window that will never fill the disk). He could share something that suddenly occurred. I think some games actually have a similar feature built in.

I think my question is if this could work out within the scope of this project. I'll check if I could implement something either stand alone or maybe within this project.

Do we know if it would be possible technically to record small 1 minute videos that could be stitched back quickly with zero loss of frames? For a 1 hour window, we would keep only the last 60 mp4 files. Or would this be something be part of ffmpeg? I know that some streaming systems breaks the video in small chunks, maybe it already exists ways to record in "chunks"?

If the recording part could work, then we would need a GUI for the user to "rebuild a video" out of a time range. This could be a separate tool if too complex to bake in ShareX.

Anyways. Any insights could help. Thanks!

**Comment by popbee** [comment]
Just saw that ffmpeg has what they call "segments". Lots of options(!)

https://www.ffmpeg.org/ffmpeg-formats.html#toc-segment_002c-stream_005fsegment_002c-ssegment

**Comment by canpolat** [comment]
I'm not a developer in this project, so, I cannot comment on the roadmap, but what you describe sounds like a separate application, to me.

**Comment by vatterspun** [comment]
> My use case is "QA" work: Essentially one spends a lot of time testing software and suddenly you run into an issue. You want to know what happened going shortly "in the past" and share a snippet of video to others without the need to reproduce what happened within a new "recording" session.

Yes, I've run into this exact issue.  How I handle it with ShareX is to use Autocapture with a repeat time of between 1 and 3 seconds.  This uses a fair amount of disk space and memory but it's definitely worth it to be able to rewind your process.

![image](https://user-images.githubusercontent.com/1289134/71601077-e7228080-2b1f-11ea-851f-066b72ba35c1.png)

If you run a program like SFK that searches for and deletes duplicate frames (when you were idle), you end up getting a great look at all the activity on your computer.  I created a simple batch file that I have set to run hourly to avoid zapping my whole hard drive: 

`sfk dupfind C:\Temp\Screenshots .png +del!`

You can also use commercial "step recording" software like ActivePresenter, which only records something when there's a change.  ShareX does not have this functionality ( #2735 ).
