### ISSUE TITLE
Feature request: Copy custom URL to clipboard when uploading through SMB

### ISSUE THREAD

**Issue by BASIL4201337** [ShareX/ShareX#4480]
Hi, I have a situation where I have a server without FTP/SFTP, and it's a Windows one running a webserver and fetching the served files through SMB from another machine

What I'd like to accomplish is upload screenshots etc. from my desktop to a SMB share, and then copypaste a URL to clipboard which would be domain.tld/uploadedfile.png for example. I am not sure is this functionality already present, it's easy to accomplish with SFTP etc. but when using the "Shared folder" uploader I can't find a way to copy a custom URL, the only format I am able to get to clipboard with this uploader is `file://ad2/wwwdata/domain.tld/html/file.png`

Would it be possible to add a custom URL functionality for "Shared folder" option?

**Comment by Jaex** [comment]
Shared folder options nearly identical to FTP (but with different namings) therefore you can also copy custom structured URL there too.

**Comment by BASIL4201337** [comment]
> Shared folder options nearly identical to FTP (but with different namings) therefore you can also copy custom structured URL there too.

You're right, it already contains exactly what I need. 😄  So sorry for making a useless issue, don't know how I missed httpHomePath and RemoteProtocol options, maybe I was too tired last night haha
