### ISSUE TITLE
GIF screen recording ignores Show Cursor option

### ISSUE THREAD

**Issue by brettinternet** [ShareX/ShareX#4481]
GIF screen recording ignores the Show Cursor option available in the "Capture" dropdown menu, and the cursor always appears in the screen recordings and is unable to be hidden. It looks like this might be an option `-draw_mouse 0` in FFmpeg.

ShareX v13.01

**Comment by Jaex** [comment]
Screen capture and screen recording have separate show cursor options.
You must disable it from here: ![](https://jaex.getsharex.com/2019/11/ShareX_PDdKAUR33A.png)

**Comment by brettinternet** [comment]
Oops, thank you for the reply and screenshot @Jaex!
