### ISSUE TITLE
Freehand (or any shape except rectangle) capture gets pasted with background filled white in ShareX editor.

### ISSUE THREAD

**Issue by domi-domi** [ShareX/ShareX#4486]
Can shape captures have the surrounding area not get filled with white into a rectangle when pasting? I understand that not every editor will pull from clipboard with transparency, but can it at least be made to work within ShareX's own editor?

**Comment by ErikHumphrey** [comment]
I'm also interested in having transparent backgrounds with ellipse region or freehand region captures, if there already isn't an option to change this.

**Comment by Jaex** [comment]
@ErikHumphrey check:

![](https://jaex.getsharex.com/2021/06/ShareX_7T4DDlsN44.png)

**Comment by ErikHumphrey** [comment]
Those did the trick, thanks!

**Comment by berkdemir** [comment]
This does the trick, but for Office applications at least, CTRL-V doesn't work, after CTRL-V, you need to select paste as image. Idk why.
