### ISSUE TITLE
How to select multi files in the task list window, which list all the recent screenshots.

### ISSUE THREAD

**Issue by rsyqvthv** [ShareX/ShareX#4487]
I can right click one file, there are menus with the shortcuts, like delete file locally (shift+del) , which is nice to use keyboard to implement, but I can't select even one screenshot there, drag and select also won't work for me. that's strange. 

anybody can help? thanks.

**Comment by Jaex** [comment]
It is currently available in dev build if you would like to try it.

**Comment by rsyqvthv** [comment]
thanks for the hint, but it still same when I upgrade to "ShareX 13.0.2 Dev", anything I need to config to make this valid in dev version?

thanks.

**Comment by Jaex** [comment]
You can hold ctrl or shift to select multiple items.

**Comment by rsyqvthv** [comment]
thank you, it works. 

but hope it can operate like selecting files in the explore of windows, 

by mouse:

one click to select one file, ctrl / shift to select multiples, double click to open it.

by keyboard:

using keyboard, up /down/ left /right to move the focus on files and combine ctrl/shift to select multiples. use enter to open it.

Thanks.
