### ISSUE TITLE
Request: work with "carnac" app, to be able to show captured mouse and keyboard events

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#4492]
See this:
https://github.com/bfritscher/carnac/releases/tag/mouse_test

It could be great if when we capture a video, it will automatically enable this app, and disable it when it's done capturing the video.
Currently we have to do it all manually, because sadly ShareX doesn't support showing information about what's clicked and typed.

**Comment by vatterspun** [comment]
#2705

**Comment by AndroidDeveloperLB** [comment]
Doesn't seem Screentogif shows any indication of mouse/keyboard.
However, Captura seems to be able to do it quite well. 
Weird thing is that it doesn't show it on Google Android emulator, probably because the emulator catches everything.

**Comment by AndroidDeveloperLB** [comment]
But I really want to have this... :(

**Comment by vatterspun** [comment]
> But I really want to have this... :(

I haven't seen anything about feature bounties here or in the Discord channel, but you might try reaching out and seeing if Jaex or someone connected to development would be willing to add it for a donation.

He might think it's out of scope as captured mouse and keyboard events are more for training and howto videos, which hasn't been their focus.

**Comment by AndroidDeveloperLB** [comment]
One of the most common usages for screenshot and screen recording is to show how to do something ("tutorial").
That's also why the app has a way to edit the screenshot and put arrows and texts...
I use it mainly to show about bug reports.

**Comment by vatterspun** [comment]
> One of the most common usages for screenshot and screen recording is to show how to do something ("tutorial").

My post was not to suggest that screen recordings are divorced from tutorials, but to set expectations with a possible rationale.  This project has gone WAY beyond where it started but, based on my time following it, I don't think this feature will get included.  I will be very happy if I am wrong about this.

**Comment by AndroidDeveloperLB** [comment]
To me it seems very useful for tutorials and showing how to reproduce issues.
It's very tied to "how to" .
