### ISSUE TITLE
ShareX v13.0.1 doesn't “copy image to clipboard” of some clipboard manager apps

### ISSUE THREAD

**Issue by carlos-cadu** [ShareX/ShareX#4495]
Hi,

I'd appreciate your help.

As shown in this screencast ([http://bit.ly/2qxKsuA]), I tested ShareX (v13.0.1) “copy image to clipboard” with 3 different clipboard manager applications. The apps and results:

Ditto: worked 
ClipCache: didn't work
MSOffice Clipboard: didn't work

Then I tried another screenshot tool (Lightshot) to see how its “copy image to clipboard” would work with those 3 clipboard manager applications. In every case, the image was copied to the clipboard properly. 

Does ShareX have any setting that can be tweaked to make/force it to work with MSOffice Clipboard and ClipCache?

Thanks for the assistance,
Carlos

--------------------------------
SYSTEM INFO
OS Windows 10 Pro 64bit
Notebook Dell XPS 9570
Core i7-8750H
Memory 16GB DDR4
Graphics Intel UHD 630 + NVIDIA GTX 1050Ti 4GB
Monitor Dell 27" U2719D (2560x1440 scaled 120%)

**Comment by snsnsjsn** [comment]
yes , my problem is sharex could not copy image into clipcache. 
and early version is ok when set in advanced settings.
![image](https://user-images.githubusercontent.com/11435527/71362520-48eb6380-25d1-11ea-8b47-69a480aec3f7.png)
use the two setting can copy image into clipcache with sharex 12.2

but in 13.1 , the two settings disappear.
so please get the two setting back.
