### ISSUE TITLE
Add support for donating using the lightning network (Bitcoin)

### ISSUE THREAD

**Issue by MrManPew** [ShareX/ShareX#4497]
Hi,
Can you please add an option to donate to the software using the lightning network?
You can easily do it with https://about.bottle.li/ 
Thanks.

**Comment by Jaex** [comment]
Hi, I created Bottle account: https://pay.bottle.li/send/social/github/Jaex

**Comment by MrManPew** [comment]
Great, can you add it to here:
https://getsharex.com/donate/
and I'll make sure to post it in website that advertise lightning supported
websites
