### ISSUE TITLE
Making toast more useful

### ISSUE THREAD

**Issue by jjnilton** [ShareX/ShareX#45]
Just a idea I had, you could put something to happen on clicking the toast notification...

Right click would do a action and left click would do another, like annotate image or upload.

Something like that.

**Comment by barnwell** [comment]
@McoreD I would love to have a CopyUrl option there. How can I go about adding this?

**Comment by Jaex** [comment]
It is already added in beta: https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX-10.1.0-setup.exe

**Comment by eRadicant** [comment]
Would love to see another advanced option for middle click.
