### ISSUE TITLE
Browser selection

### ISSUE THREAD

**Issue by At-Libitum** [ShareX/ShareX#450]
Hi there,

New user here. Installed the program, looks great so far :)

Got one request/question. I am very much a portable guy so downloaded and am trying out the portable version. However, when I tried linking it to my various img hosts, it always starts up the system's default browser... sadly there's no recent enough version of IE installed on most of the locations I access. Which means that if I try using any of the actions involving the opening of a browser window, I always have to copy the target link from the non-accepted old ie version to my own preferred portable browser.

Since it already is possible to run it as a portable application, would it be possible to add a setting somewhere to also use a user-selected browser instead of the system's default? Much obliged.

**Comment by Jaex** [comment]
We will add optional browser path setting to Application Settings window advanced tab.

**Comment by At-Libitum** [comment]
Thank you very much.
