### ISSUE TITLE
[Request] Re-position capture area option

### ISSUE THREAD

**Issue by Tritaya** [ShareX/ShareX#4503]
There is a great option of snapping a capture area borders to the predefined sizes with holdin Alt key.
However, you often need to reposition a little bit an upper left corner (if you choose the area dragging the cursor from left to right and from up to down) after you snapped to the desired size.

For example, I use a square predefined size. And after capturing the area, I have to re-position a little bit the area to be capture to fit the image inside just in the center of that square.

Actually, even without a snapping feature, the re-position ability of the beginning point would be useful.

**Comment by Jaex** [comment]
If you press "Q" then you can re position regions.

**Comment by Tritaya** [comment]
Thank you, I've just figured that out that holding Ctrl is the solution. I am sorry to not having studied that beforehand.
