### ISSUE TITLE
The cursor position is not recorded in the proper position

### ISSUE THREAD

**Issue by martrod** [ShareX/ShareX#4508]
Hope the image talk for me.

https://imgur.com/7WSbsT0

I'm recording in a second monitor, full HD resolution on windows 10. The cursor position is recorded with a offset distance en x and y.

In main monitor, cursor recording is accurate:

https://imgur.com/11XVlHh

**Comment by Jaex** [comment]
No it can't because Imgur is blocked in my country.

But must be duplicate of #1329
