### ISSUE TITLE
Feature to snip/crop out/shorten middle of long pictures

### ISSUE THREAD

**Issue by nielsmh** [ShareX/ShareX#4513]
When capturing e.g. long drop-down menus, and most of the menu is irrelevant for the context, it would be convenient with a feature to snip/crop out the _middle_ of the image, with an effect-shape inserted to denote that part of a long/wide image has been removed.

**Comment by vatterspun** [comment]
I'm not sure if @Jaex will do anything about this, but I'm curious and having difficulty picturing what you imagine.  Can you put together a before-and-after of what you have in mind?

**Comment by nielsmh** [comment]
Here's an attempt at doing a quick and dirty job, took perhaps 3-5 minutes in Paint.net, and looks pretty bad.

![image](https://user-images.githubusercontent.com/1062071/71616708-f05f2c00-2bb7-11ea-9b25-4677aa3425b8.png)

**Comment by vatterspun** [comment]
> quick and dirty job, took perhaps 3-5 minutes in Paint.net, and looks pretty bad

I disagree totally -- that's pretty great.  I have up-voted the suggestion.

**Comment by bartosz-jarmuz** [comment]
Yes, that is a greatly missed thing!

**Comment by chilirock** [comment]
+ 1 to add this feature. As far as implementation, it's good to have options. I would prefer a more seemless final result without the jagged/ripped portion visible in the final result, e.g. similar to the post from @yahooshua. Thanks.

**Comment by chilirock** [comment]
It appears that with the number of duplicate issues: #4366, #4513, and #6026 that there is some pent up demand for this functionality. There are probably others out there that would benefit that haven't formally expressed their support.

**Comment by jwoodard80** [comment]
I hate to just be a +1 but, yes.... +1

I used Greenshot for years and changed to ShareX. I've been very happy with it, however, with the amount of captures I take the lack of this feature is extremely glaring. I can try to move windows to a optimum spot for a capture but it's still then an extra 10-15min sometimes trying to edit it and cut out the areas I don't want. 

It is a open source program so I understand that I have no place to gripe. I'm extremely appreciative of the hard work that has gone into this software. It makes me happy to have turned several people on to using it with great results. Personally, however, I'm now having to re-evaluating options (free and paid) to see what is there and if a better workflow is possible. Lack of the ability to "cut out" a section of a capture is the main driver of that. I would MUCH rather donate to this software/group than use something else. 

My point is not to be negative and rage quit, but to humbly ask that attention be given to those who have expressed support in this feature. We may not all be developers, however, we WANT ShareX to succeed! Features like this are what provide parity with closed source software and help us make the case for change. :-)

**Comment by NoqturnalOne** [comment]
+1

**Comment by SullyPanda76cl** [comment]
Can we merge these?

[#4366](https://github.com/ShareX/ShareX/issues/4366) 
[#4513](https://github.com/ShareX/ShareX/issues/4513)
[#6026](https://github.com/ShareX/ShareX/issues/6026)

**Comment by Jay-Tarzan** [comment]
About :)

**Comment by nielsmh** [comment]
Well, it's been a while and I guess I had to see if I can do this myself.
This is almost 90% of the work done, just need the other 90% now!

![demo](https://user-images.githubusercontent.com/1062071/184732239-0efca37d-e760-4ce0-8b2f-940eb9dba202.gif)

**Comment by SullyPanda76cl** [comment]
This is awesome news!

**Comment by Jaex** [comment]
Good work!

I think `TrimInteriorTool` name is not good. Need to check what other image editors calling this tool.

**Comment by yahooshua** [comment]
Awesome!

**Comment by nielsmh** [comment]
> I think `TrimInteriorTool` name is not good. Need to check what other image editors calling this tool.

Completely agree. I had to pick something to at least get the code going, but finding a good name and good toolbar icon for this is going to be difficult too.
Other ideas: Shorten, Crop middle, Cut middle, Cut out, Fold

As for UI, my idea is to make the Accept/Cancel buttons vertical when doing a horizontal trim, and perhaps instead of the Accept button have several buttons that perform different cutting effects. Cutting effects could be "none" (straight cut), "torn paper", "gradient crossfade", and perhaps more.
But maybe the effect selection belongs in the Tool Options menu.

**Comment by Jaex** [comment]
> Other ideas: Shorten, Crop middle, Cut middle, Cut out, Fold

Cut out tool? Only if we knew what other apps calling it. People keep telling in here that other apps could do it but not tells what apps.

> good toolbar icon

I already know what icon to use, so leave it empty.

> But maybe the effect selection belongs in the Tool Options menu.

Yea, it should be in options menu.

**Comment by bossanova808** [comment]
Snagit does it, they indeed call it the Cut Out tool...

https://www.techsmith.com/learn/tutorials/snagit/remove-image-parts/

**Comment by chilirock** [comment]
Screenshot Captor has it and it's called "Splice out strip defined by selection". The "selection" is user defined in width/height and can be either a vertical or horizontal strip. 

In Screenshot Captor, the function is called in the Image Editor from an effects menu, or by a function key combination, Ctrl+Alt+P. For ShareX, I would think you would place it in the Image Editor, under the "Image" drop down button, maybe in the Crop subsection, since it seems to be a variation of cropping the image. At least that's where I was looking for it when tried to find it in ShareX.

**Comment by SullyPanda76cl** [comment]
> Snagit does it, they indeed call it the Cut Out tool...
> 
> https://www.techsmith.com/learn/tutorials/snagit/remove-image-parts/

+1

**Comment by Jaex** [comment]
Implemented by @nielsmh at #6454.

**Comment by Jaex** [comment]
Using <kbd>X</kbd> for cut out tool hotkey?

**Comment by jwoodard80** [comment]
Not sure this is the appropriate channel but I just wanted to take a second and offer very humble and heartfelt thanks to @nielsmh for the work on this. I'm sure it wasn't easy but we all benefit from your time and effort. @Jaex thanks to you as well for the overall work you have put into this entire project. It is a labor of love that you, I would suspect, do not hear encouragement enough about. We do appreciate the work. 

Thank you for taking this upon yourself and adding a much needed feature! :-)

**Comment by Jaex** [comment]
Indeed @nielsmh did a great work! Thanks for the kind words.

**Comment by bossanova808** [comment]
Indeed awesome work that increases the utility of an already fabulous programme further.   Much appreciated!

**Comment by joworfspm** [comment]
when will we see this new function to be available? I'd like to express my thanks as well. The Cut-Out tool is a great function that was missed and will be a great new addition for all users of ShareX

**Comment by jwoodard80** [comment]
You can use the Pre-Release and test it now actually.... Application Settings > General > Check for pre-release updates. 

I have highlighted the icon to use the tool. :-)

![image](https://user-images.githubusercontent.com/10240627/187274251-43176faf-2eaf-4d2f-86ae-0c35a15e7d50.png)

**Comment by bossanova808** [comment]
I have done that and in general it's just great to have it -  but there _is_ a little 'jankiness' with it currently - might be worth some tweaking before release.

The main issue is that if I try and cut an area, its seems quite random about whether it will do a vertical or horizontal cut and will swap between those options as the mouse is moved, even if moved consistently in one direction.

The other is very minor, but the tick/cross buttons sort of dance when you hover over them - I presume that's to indicate a pushed status but it doesn't look great.

There is a crappy video here - I am trying to cut a horizontal section, but you can see it flips to vertical several times...

https://photos.app.goo.gl/aNQMohWBE9F97Fvv9

**Comment by nielsmh** [comment]
The selection between horizontal and vertical is based entirely on whether you dragged the furthest in horizontal or in vertical direction. Unless that was changed/fixed too, there is an invisible selection rectangle where you dragged, you can see it when you hover the mouse over it. It'll show you how much you actually dragged in only one direction, it will be very thin/narrow if you were consistent.

**Comment by bossanova808** [comment]
Hmm, I feel there must be a better way then, as it's definitely janky in practise - I noticed it immediately and on every use - and as a heavy user of image editing apps I don't encounter such issues with those.    I think, at least, once it has determined a direction (after an initial test period of 'are they going up/down or left/right' - it should then stick to what it has chosen....

**Comment by chilirock** [comment]
I would prefer if the cutout area selection action was separate from the cut action itself. It might make it more clear from a development standpoint and provide more flexibility from a user standpoint if the user could first draw out a selection rectangle on the image. And then provide the normal handles to resize and move the selection area before clicking a button to cut out the area. 

From a development perspective, you could decide whether to cut a vertical or horizontal strip based on the dimensions and positioning of the rectangle. If the rectangle is wider than it is tall, then you cut a horizontal strip. If the rectangle is taller than it is wide, then you cut a vertical strip. The thickness of the strip is based on the shorter of the two dimensions.

**Comment by nielsmh** [comment]
> From a development perspective, you could decide whether to cut a vertical or horizontal strip based on the dimensions and positioning of the rectangle. If the rectangle is wider than it is tall, then you cut a horizontal strip. If the rectangle is taller than it is wide, then you cut a vertical strip. The thickness of the strip is based on the shorter of the two dimensions.

That is exactly how the implementation works: The user draws a rectangle, the larger of the two dimensions becomes the size of the cut. Originally the implementation did show the rectangle and resizing handles, and it was kind of awkward. A different control would probably make more sense, if anything.

**Comment by emeyedeejay** [comment]
> Hmm, I feel there must be a better way then, as it's definitely janky in practise - I noticed it immediately and on every use - and as a heavy user of image editing apps I don't encounter such issues with those. I think, at least, once it has determined a direction (after an initial test period of 'are they going up/down or left/right' - it should then stick to what it has chosen....

I'm seeing exactly the same - the selection area does not match the longest side rule ... I don't think?

![221003191237-Sharex screenshot](https://user-images.githubusercontent.com/8543879/193643930-10d9886b-e2ec-4895-961d-f6adc017c95b.gif)

**Comment by emeyedeejay** [comment]
Ah ... OK I see what you mean now - you don't need to enclose the area you want to remove with the rectangle (like you would for a crop) - you either move horizontally or vertically and the selection "auto select" the whole strip either up/down or left/right.

Got it...

![221003195050-Sharex screenshot](https://user-images.githubusercontent.com/8543879/193644879-2ee25c49-50c7-41ba-b6fc-91264b41bbd1.gif)

**Comment by KennyJolt** [comment]
This Cut Out tool is great! Thank you so much!

**Comment by bossanova808** [comment]
My nitpicking above about the slight quirkiness of the cut out selection aside - which is soon gotten used to in practise - this feature is absolutely great, and has allowed me to finally get rid of Snagit once and for all.  ShareX is wonderful - obviously a bit more tough to set up/configure than some tools, as it's so powerful, but once the setup is mastered (and you can import and export setups to make new machine setup trivial - so good!!) - it's just a generally marvellous tool and huge thanks to @Jaex and @nielsmh for it.

**Comment by emeyedeejay** [comment]
Ok ... so this is user error I'm sure but for the life of me I cannot find where to "Install dev build" for the cutout functionality... 

![image](https://user-images.githubusercontent.com/8543879/203123030-e8b7a505-5781-4bf8-ba05-b1272fbabc5e.png)

What am I missing? Thanks!

**Comment by chilirock** [comment]
@emeyedeejay, you can download the dev build from the https://getsharex.com/ site. 

Here's the direct link: https://github.com/ShareX/DevBuilds/releases/download/v14.1.3.6155/ShareX-14.1.3-setup.exe

Anyone have an idea when the next production version will be released with this included?

**Comment by chilirock** [comment]
@nielsmh, thank you again for creating the cut out tool! This has been a game changer for me in ShareX. I've been using the new tool regularly since it was released in the 15.0 version. I don't seem to be able to "undo" the cut out action. If I make a mistake or cut out a section that is too big or too small, I would like to be able to "undo" the action and try again. Am I missing something, is it possible to "undo" a cut out, or could it be added to a future release?

**Comment by snowman** [comment]
**undo** feature is missing either `crop` or `cut`

![image](https://github.com/ShareX/ShareX/assets/16096559/be90c92c-6b6d-4d3c-95b4-99a6ec09dfc3)
