### ISSUE TITLE
Border color when editing images always transparent

### ISSUE THREAD

**Issue by lbrtdy** [ShareX/ShareX#4514]
I went to edit image today and the arrow and rectangular tools always draw transparently. I can select the color red but no arrow or rectangle results. I tried uninstalling and reinstalling but no avail.

Version 13.0.1

![Zc90BOq5Nm](https://user-images.githubusercontent.com/9099814/70359366-97a6a880-1830-11ea-868f-71b41797dc64.jpg)
![ShareX_q8cVOg8vXJ](https://user-images.githubusercontent.com/9099814/70359367-97a6a880-1830-11ea-9d72-d799242cb467.png)

**Comment by Jaex** [comment]
Increase border size, it is 0 currently.
