### ISSUE TITLE
Screen Recording MP4 is only 1 fps

### ISSUE THREAD

**Issue by arusergithub** [ShareX/ShareX#4515]
Screen Recording's MP4 is OK for the first second, but then falls to about 1 fps, despite that the settings ask for 20fps.

Screen Recording (GIF) is fine.

I'm using the default encoder settings.

Any ideas?

ShareX V13.0.1 on Windows 7, Viewing using VLC Media Player and Windows Media Player.

**Comment by Jaex** [comment]
It could be related to audio recording if gif is fine and mp4 is not. Try disabling audio recording and test like that.

**Comment by arusergithub** [comment]
You're right! With Audios source: none, the video is good. Thanks.

Any idea of a solution?

**Comment by arusergithub** [comment]
This problem persists on version "13.0.2 Dev", though today the dropped FPS is approx 2.

**Comment by arusergithub** [comment]
Issue persists. It would be great to have a fix.

**Comment by arusergithub** [comment]
Issue persists. It would be great to have a fix.

**Comment by arusergithub** [comment]
Issue persists. It would be great to have a fix.

**Comment by arusergithub** [comment]
Issue not reproduced on V13.7. If you fixed it, thanks!

I have found once on this version that the recording about .5s in seizes for .5s, but this has not recurred (yet).
