### ISSUE TITLE
Hide all "Upload File" Commands in UI

### ISSUE THREAD

**Issue by megabugman** [ShareX/ShareX#4521]
I don't plan to ever upload anything, therefore I set DisableUpload "True" in Settings.
In Image history window the command "upload file" is still visible. Also the main Window 
still shows the Upload Button containing the subcommands Upload File/Folder,etc.

I miss an option to hide everything (buttons, menu entries, action toolbar, etc) regarding uploading in the UI including OCR, basically a offline version. ATM I see a big chance of unmeant data leakage. Thanks

**Comment by Jaex** [comment]
> In Image history window the command "upload file" is still visible. Also the main Window
still shows the Upload Button containing the subcommands Upload File/Folder,etc.

Both history and main window upload buttons does not upload if you enabled "DisableUpload" option.

> including OCR

Now I made sure "DisableUpload" option also gonna disable OCR functionality in next release.

> ATM I see a big chance of unmeant data leakage.

If you enabled "DisableUpload" option then only OCR bypass that option. So there is no big chance of data leakage. If there is any other place which not respects that option then please let me know.

> basically a offline version

Technically you can accomplish this for most applications by blocking them using firewall software.
