### ISSUE TITLE
Request: Hotkey to open last screenshot in editor

### ISSUE THREAD

**Issue by XDelta** [ShareX/ShareX#4522]
I would like to be able to set a hotkey to open the image editor with the most recent screenshot taken and I did not see and way to do this. More specifically not as a single step, I could open the editor with a hotkey and then manually find the image or paste a clipboard copy. Would be an appreciated addition.

**Comment by vatterspun** [comment]
This is very easy to enable and I do it on every machine I use:

1. Click on Hotkey Settings
2. Click Add
3. Choose

![image](https://user-images.githubusercontent.com/1289134/73129174-a8aba480-3fab-11ea-86e6-4feeb3e7d687.png)

4. Close the window by pressing X in the top-right corner

**Comment by XDelta** [comment]
Thanks for a reply but the process you showed is what I had mentioned about setting a hotkey to open the editor. The feature I wanted to see was that hotkey being able to automatically open the last image I took instead of needing to find it manually or use a clipboard copy.

**Comment by vatterspun** [comment]
Oh I see now.  Would something like this work?

![POWERPNT_Z2YJRA9c4A](https://user-images.githubusercontent.com/1289134/73130243-a99c0080-3fc2-11ea-934f-bdeed7d21720.png)

**Comment by XDelta** [comment]
Something like that mock up would be a good alternative

**Comment by shodanx2** [comment]
Hi,

This issue is not resolved

Please add "Open last shot in editor" as an option in Tools


![image](https://github.com/ShareX/ShareX/assets/10621885/3eab99f2-2f9c-4f0d-b764-d731a261518e)
