### ISSUE TITLE
[Hotkey request] Toggle cursor visibility 

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#4526]
## Feature request
**Hotkey option for toggling the cursor visibility** as indicated in the screenshot below:

![image](https://user-images.githubusercontent.com/3248782/71041979-81360200-20f8-11ea-8905-2f771f66ee62.png)

* Implementation for us choose global hotkey for this feature (unconfigured/disabled on default)
* If implemented, add this hotkey feature under a **`disable hotkeys`** branch, meaning if it's disabled, then this hotkey also be non-functional. 

### Reason
It has gotten super tedious to open the menu every time to toggle cursor visibility ON and OFF, it would be beneficial to configure a global hotkey for toggling cursor visibility with a global hotkey to speed-up the workflow.

## Plans for implementation up for discussion 🤔

I've written the main idea I came up with, but I still didn't come up with a concentrated plan for implementing this method in the interface area. 

❤ To show love for developers, we should work together to help developers to be confident to implement this feature; all are welcomed to participate in this brainstorming.

### For discussion

**1. Where do we place an option for users to choose their global hotkey preference to toggle the cursor visibility?**
* Keep in mind, this specific feature is not identical to hotkey settings.
* This feature would be disabled or null since it's not configured on default.

**2. Do we need a safety tickbox to disable/enable the global hotkey for toggling cursor visibility?**
* If needed, then where would we place it?
* This feature can be replaced with the current `Task > Disable hotkey` we have.

**Comment by dmxt** [comment]
## Current methods in manual, mouse way
At the time of writing, I found three methods, I believe, all have the same behavior, as demonstrated in animated screenshots below: 

### Method 1 (Quickest) `Tray > Capture > Show cursor`
![0wuLlRBOG4](https://user-images.githubusercontent.com/3248782/71038218-52675e00-20ef-11ea-8c66-404ec58843f6.gif)
_P.S. It's much better with a toggle in the tray menu! I would give you a **big** credit for this part; it used to be horrendous!_

### Method 2 `ShareX > Capture > Show cursor`
![image](https://user-images.githubusercontent.com/3248782/71039969-7d53b100-20f3-11ea-8a77-6829b79bd8d6.png)

### Method 3 `ShareX > Tasks Settings > Capture > ☐ Show cursor in screenshots`
![klTmq4GXpr](https://user-images.githubusercontent.com/3248782/71039638-9f98ff00-20f2-11ea-86fc-6500730abdd6.gif)

**Comment by dmxt** [comment]
My first suggestion ¯\_(ツ)_/¯
Add a new checkbox **☑ Toggle cursor** in `Hotkey settings`... but where?

![image](https://user-images.githubusercontent.com/3248782/71044265-38ce1280-20ff-11ea-95b3-e824c95c136c.png)

**Comment by dmxt** [comment]
Yo guys? I put a lot of time in the thread.

**Comment by Jaex** [comment]
You could just write you need "Cursor visibility toggle hotkey". You didn't have to write wall of text for such simple request.

**Comment by mirismaili** [comment]
I need this too. 

As a workaround, I defined a new task for it and assign a hotkey to it.

![image](https://user-images.githubusercontent.com/15800189/150231625-782d4b7e-4597-4114-a0ae-2d60f3ffbf0c.png)

![image](https://user-images.githubusercontent.com/15800189/150231545-c8fed0d2-73d2-4835-94af-da305c3ebe8f.png)

**Comment by dmxt** [comment]
@mirismaili That's a good workaround but it won't apply to video recording or other screencap functions.

What I was suggesting is an ability to turn on and off the cursor **globally** via a hotkey for all screencap functions. This is an important take from my issue thread.

**Comment by shodanx2** [comment]
Hello, 

This similar issue might have a solution that works for you if we manage it 
https://github.com/ShareX/ShareX/issues/7818

Basically, calling command at start / end to show/disable mouse trails should work for hiding/showing cursor
