### ISSUE TITLE
Silent OCR doesn't work

### ISSUE THREAD

**Issue by vanjavk** [ShareX/ShareX#4529]
If it's supposed to silently scan image and copy contents to clipboard it doesn't work. Nothing gets copied to clipboard. SHAREX 13.0.1

**Comment by SerpentDrago** [comment]
I just reproduced this myself 

![image](https://user-images.githubusercontent.com/21133858/82719064-3b680180-9c75-11ea-92b2-97719af12f19.png)


see above , how i have it set , it works , but pops up the dialog with what it ocr'd and copys to clipboard  ( i have a after capture action to OCR )  > 
![image](https://user-images.githubusercontent.com/21133858/82719073-59356680-9c75-11ea-990f-a7582c8d6853.png)

![image](https://user-images.githubusercontent.com/21133858/82719081-618da180-9c75-11ea-9b31-e13a95168e6b.png)


but if you check silent mode , 

It pops up notification saying it ocr'd and copied to clipboard but it doesn't actually work

**Comment by Hexcede** [comment]
I can reproduce this in ShareX 13.1 for "After capture tasks".
Repro:
1. Hotkey settings
2. Add
3. Selecet a task, e.g. Capture region
4. Override after capture settings
5. Select "Recognize text (OCR)"
6. Override capture settings and use Silent OCR or use Silent OCR globally
7. Use the hotkey and it will respond with a "Copied" notification however the clipboard will be unchanged. Selecting the Copy image after capture task copies the image, and the automatically clear clipboard setting does not actually clear the clipboard if the task is removed (maybe specific to some normal task types?).

For me using the "Text capture (OCR)" **normal task** (not after capture task) worked 100% as intended and copied the results using Silent OCR.

**Comment by desophos** [comment]
I've run into this same issue (ShareX 13.1), but I have a bit more info. I have a custom workflow set up as follows:

Task: Capture region
After capture: Recognize text (OCR)
Override capture settings; only change "Automatically copy results to clipboard" under OCR.

After-capture OCR works fine and copies to clipboard without "Process OCR silently", but with that option enabled (and nothing else changed) I get the following error in the debug log:

> Clipboard copy text failed.:
> System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.
>    at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
>    at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
>    at ShareX.HelpersLib.ClipboardHelpers.CopyText(String text)

I don't think I can use the "Text capture (OCR)" normal task because I need to preprocess (filter/adjust) the captured image to get decent OCR results.

**Comment by pinusm** [comment]
I came here facing the same issue, but found that the problem I was having was related to setting the task as Capture region, instead of Text capture (OCR).

![image](https://user-images.githubusercontent.com/10765331/100343774-7cf0b500-2fe8-11eb-9f7a-81fb1edd435d.png)

**Comment by vanjavk** [comment]
> I came here facing the same issue, but found that the problem I was having was related to setting the task as Capture region, instead of Text capture (OCR).
> 
> ![image](https://user-images.githubusercontent.com/10765331/100343774-7cf0b500-2fe8-11eb-9f7a-81fb1edd435d.png)
> 
> 
> 

Your solution worked, thank you!
