### ISSUE TITLE
[Request] Update promotional material

### ISSUE THREAD

**Issue by SonOfDiablo** [ShareX/ShareX#4530]
Hello,

I'm fairly new ShareX user and I just spend a bunch of time trying to track down a feature that seems to have been removed about 3 releases ago...

Namely the "Webpage Capture" option. 
I know that it wasn't listed under Features on the webpage and that the Docs had a page about using the browsers build-in capture feature.

But at first I saw this feature on the promotional imagery you are using, which seems to be from version 12 and earlier.

I don't know if any other features has come and gone between then and now, but maybe it's time to update the screenshots on the website and the gif you use here on Github and the homepage of the website.

Again, I know this isn't a big deal, but it would be nice for new users to be met with some updated visuals.

**Comment by vatterspun** [comment]
> I just spend a bunch of time trying to track down a feature that seems to have been removed about 3 releases ago ... Namely the "Webpage Capture" option.

I think it's been replaced with Scrolling Capture or the Chrome plugin.  I'm not sure.

**Comment by SonOfDiablo** [comment]
> > I just spend a bunch of time trying to track down a feature that seems to have been removed about 3 releases ago ... Namely the "Webpage Capture" option.
> 
> I think it's been replaced with Scrolling Capture or the Chrome plugin. I'm not sure.

According to the website under [docs/website-capture](https://getsharex.com/docs/website-capture) this feature was removed and it is suggested to use the browsers build-in web capture functionality.  
  
The Chrome plugin is for interacting with images, text, etc. on webpages not to capture the page itself.

**Comment by Jaex** [comment]
I will update them on next release.
