### ISSUE TITLE
Youtube movies blacked out when taking screenshots

### ISSUE THREAD

**Issue by panthersdude2001** [ShareX/ShareX#4538]
all,
when taking screenshots of movies on youtube that I've bought, the movie is completely blacked out.
is this an expected issue, or is it a bug?
![elf whilst LHI](https://user-images.githubusercontent.com/44646536/71447554-a7adfb80-26fd-11ea-86c6-c818634d7d05.png)
the above screenshot taken with your program is blacking out the movie completely.

**Comment by panthersdude2001** [comment]
also, merry christmas everyone. 🎄🎄🎄🎄➡🥰🥰🥰🥰

**Comment by Jaex** [comment]
We can't do anything about it if YouTube using DRM to block screenshoting their contents.

**Comment by panthersdude2001** [comment]
Oh ok Jaex, I knew this was an expected bug. Thanks. Happy holidays

**Comment by skaddistic** [comment]
sorry for bringing back this thread but if you want to screenshot then use
**SHIFT+CTRL+S**
