### ISSUE TITLE
feature request - custom search engine on OCR

### ISSUE THREAD

**Issue by mortyobnoxious** [ShareX/ShareX#4539]
Hi, is it possible to give users an option to add custom search engines on OCR screen below?

Like:
`https://www.google.com/search?q=`
`https://eksisozluk.com/?q=`

![ShareX_ALX2TyMmf2](https://user-images.githubusercontent.com/42044258/71482884-f2229b80-2815-11ea-885b-cfc1ae12a422.png)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2022/05/ShareX_147iYMw3u5.png)
