### ISSUE TITLE
Question: Popup preview above system tray?

### ISSUE THREAD

**Issue by At-Libitum** [ShareX/ShareX#454]
Hi there, 

I didn't know where else to put this but I've got a question I can't seem to find the answer for. When you capture a screen there is a small preview popping up above the system tray. Is there any way to prevent that preview from popping?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/01/iq0lLYaS9v.png)

**Comment by At-Libitum** [comment]
Wow :D you broke the lightspeed barrier. Can't believe I missed that... thanks a bunch
