### ISSUE TITLE
UI does not scale properly. At least font size option is needed.

### ISSUE THREAD

**Issue by HubKing** [ShareX/ShareX#4540]
I am using 200% DPI scaling, and ShareX's text is still to small to read comfortably. This is annoying because there are so many texts on the UI, especially on the settings windows. 

Setting the High DPI scaling override to "System" on the compatibility options makes the UI readable, but then when I tried to record the screen, the screen was zoomed two times and shows only a quarter of the screen, which makes the application unusable.

If, for some reason, you cannot support high DPI scaling, please at least allow users to change the application font size (and scale the window according to the font size).

**Comment by lispeedyg** [comment]
I could not agree more. I'm on a 4K laptop and have it scaled to 150% (Comfortable for me) but launching this app is extremely painful (see below).  Is there any way to resolve this for High DPI screens?
![image](https://user-images.githubusercontent.com/8366831/75899742-ecdf5f80-5e09-11ea-9c09-7837bea34ec2.png)

**Comment by joyhguan** [comment]
Same here! it is so hard to see!

The app is awesome though. 

Please add option for the sizes of font and buttons. T_T

**Comment by curiouspers** [comment]
Got similar issue, main window is ok, but application settings and capture settings is screwed up. 1440p monitor
![ShareX_wP7BDCRlGR](https://user-images.githubusercontent.com/2457159/95340996-7da97c80-08be-11eb-80ad-990a49b8817c.png)

**Comment by NickAdriaenssens** [comment]
On my screen (1440p) nothing overlaps but font size, inputs, buttons,.. are really big.

![image](https://user-images.githubusercontent.com/5507224/97632440-c7efca80-1a32-11eb-90ab-f5bb6c92e3b0.png)

**Comment by NickAdriaenssens** [comment]
My issue seems to be fixed in Windows 10 build 1809 (upgraded from 1803).

**Comment by ai1980** [comment]
Hi any updates on this? It's 2022 and i am having the same issue: 
![image](https://user-images.githubusercontent.com/94709188/168532031-5b90edb8-9abc-490c-9f70-aef0e1326251.png)

**Comment by jerrywcy** [comment]
Same Problem! Haven't found any ways to solve it...

**Comment by Seawolf159** [comment]
Kind of game breaking. I am on 2560x1440 at 100 % scale on windows 11.

![image](https://user-images.githubusercontent.com/38156717/210270449-eb144cd7-720c-4430-9bdb-7b2d2df4ad7b.png)
![image](https://user-images.githubusercontent.com/38156717/210270474-f2c88e96-20a9-42ad-9fb7-e5d196ef1785.png)

**Comment by mrzcn** [comment]
I have same issue. I cannot read the settings menu fonts.

**Comment by PatrickGriffiths** [comment]
I am also having this issue, I can not read a single thing on my screen, I am having to use windows magnifier and that is killing me lol -- has anyone found a fix for this?

**Comment by PatrickGriffiths** [comment]
> Same issue, I can't almost read anything. It makes the whole app useless unfortunately, is there any fix?

The only thing I can find to half ass fix this is to change the font size in: 
"Application Settings > Theme > MenuFont > Size" 

Though this only effects the main menu, it has made things a little more readable for me on my screen although making it too large will make things look strange and on the menus outside of the main window it will still be super tiny....

I hope that someone can find a better fix or an option could be added. This has been an issue for far too long!


Kind regards, 
Patrick.

**Comment by icaptnbob** [comment]
Same problem, but this issue is marked as closed.
Creating a new issue https://github.com/ShareX/ShareX/issues/6951  seeing that we cannot re-open this one.

**Comment by icaptnbob** [comment]
A work-around on Windows 10 is to open Windows "Display Settings", under "Advanced scaling settings" set custom scaling to 100 and reboot.
In Windows 11, this is under Display > Scale & Layout > Custom scaling.
Note, this doesn't happen on the very latest Windows 11. I'm on this version and it seems ok.
2023-06 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5027231)
