### ISSUE TITLE
The UI is too comlicated to use specific features.

### ISSUE THREAD

**Issue by HubKing** [ShareX/ShareX#4541]
I don't know about others, but I found this application while trying to find a free software for recording the computer screen. ShareX's screen recording feature seems very convenient (the recording UI part is very good), but the application's UI as a whole is too complicated, and there seems to be no way to customise it.

For example, I only want to use screen recording, but since there are so many features (most which, in my case, are not necessary), I have to click the "capture" button on the left pane, and then choose "screen recording" in the context menu which has lots of other items. And the fact that ShareX's UI does not scale properly amplifies the inconvenience from the complicated UI.

How about providing separate simplified UI modes for commonly used features? For those who just want to record the screen, ShareX could provide a simplified UI for that, something like,

![Capture](https://user-images.githubusercontent.com/10900489/71489360-89b0da00-2868-11ea-8d49-0c0604ade9e1.PNG)

**Comment by vatterspun** [comment]
Ultimately there are a LOT of screen capture tools out there with a much simpler UI than Screen

How about providing separate simplified UI modes for commonly used features? For those who just want to record the screen, ShareX could provide a simplified UI for that, something like,

**Comment by Fuzzqt** [comment]
ShareX for recording desktop environments is great, it is not great for high processing/graphical things. If you simply just want to record your desktop for a tutorial or show something then it is highly useful. If you are not interested in the latter I recommend installing a program called OBS.

I'll show you the easiest way to record your desktop with Hotkeys. (Just a heads up default ShareX loads you with this Hotkey already set up, but if you were curious about how you can make your own from scratch this is how you would do it) I'll also include how you can add your microphone to the video if you wanted to present information.

![ShareX_uvqA4CCYZE](https://user-images.githubusercontent.com/47482485/74093039-9006b880-4a9a-11ea-8083-85fe6a4e855a.png)

![ShareX_SJ7GHFX1bA](https://user-images.githubusercontent.com/47482485/74093041-985ef380-4a9a-11ea-9b41-cdd7078d77d0.png)

![ShareX_EmBCqkJEZt](https://user-images.githubusercontent.com/47482485/74093062-de1bbc00-4a9a-11ea-8d70-4ed58354788a.png)

![ShareX_qTELBfgWaF](https://user-images.githubusercontent.com/47482485/74093056-bdebfd00-4a9a-11ea-8a03-e2e664211c3a.png)

This is for an offline recording (If you wanted to automatically upload it to a upload site then you would click upload to host)

![ShareX_gaIA6ucAyR](https://user-images.githubusercontent.com/47482485/74093071-01466b80-4a9b-11ea-982b-62dc3fa271c1.png)

![ShareX_V0daiY9GQ1](https://user-images.githubusercontent.com/47482485/74093082-1de2a380-4a9b-11ea-9629-611d0c3d69da.png)

This last step is only needed if you want audio from your end

I understand at first it can feel overwhelming but once you learn Hotkeys and using them it makes ShareX a great utility for more than just screenshotting.

Now in my case I bound my tutorial screen record to Ctrl X, so every time I press Ctrl X a rectangle will pop up and allow me to screen grab whatever I have boxed within. This will immediately start recording. You simply click stop once you're done, or abort if you want to take another cut and delete that recording.
