### ISSUE TITLE
BackBlaze B2: BucketID Required but no option for BucketID in ShareX Destination Settings

### ISSUE THREAD

**Issue by dxf** [ShareX/ShareX#4542]
![image](https://user-images.githubusercontent.com/38754061/71514645-8e40b700-2897-11ea-9076-4cef5dad2eda.png)

Could not get B2 upload URL: Error 402 bad request, BucketID required

![image](https://user-images.githubusercontent.com/38754061/71514665-aadcef00-2897-11ea-9563-896cf06e3cfa.png)

**Comment by Nighthax** [comment]
I too have this issue

**Comment by vincentchu37** [comment]
I solved this issue by issuing a new key in backblaze and explicitly limiting the key to one bucket.

![image](https://user-images.githubusercontent.com/19421154/104134387-69a26a80-5346-11eb-9230-47443017bf56.png)
