### ISSUE TITLE
V13.0.1 Double-click History MP4 causes PotPlayer to play all in folder

### ISSUE THREAD

**Issue by arusergithub** [ShareX/ShareX#4544]
Using PotPlayer, in History, a double-click on an MP4 causes the player to try to player all MP4's in History's (possibly outdated record of the) folder, confirmed by PP playlist window e.g. https://i.imgur.com/MhmK3N7.png . Unsurprisingly this causes errors on any MP4 that's been deleted.

Not reproduced on VLC media player.

Windows 7.

**Comment by Scrxtchy** [comment]
Please check if this fixes your issue
https://forum.videohelp.com/threads/362398-Play-next-file-automatically-in-PotPlayer

it is not a problem with the ShareX softwrae

**Comment by arusergithub** [comment]
Yup, that's my issue. This PotPlayer setting
https://i.imgur.com/IZbxDnl.pngtv . Bonkers. Fixed by changing to
https://i.imgur.com/74YtGUz.png .

Brilliant. Thanks.
