### ISSUE TITLE
FTPS issue, "URL is empty"

### ISSUE THREAD

**Issue by CryPt00n** [ShareX/ShareX#4545]
Hello,
when using FTPS for uploading my Screenshots, i´m getting the error "URL is Empty". File ist uploaded to the server, but no URL copied to my clipboard. 
When usig FTP, all is working fine.
Using ScreenX on Win10, my FTP is vsftpd on Ubuntu Server 18.04

**Comment by nzzzn** [comment]
The same my error and other issue.
Duplicate of #4437

**Comment by Ichigo69** [comment]
I'm getting this exact same error on 13.1

**Comment by MasterCevin** [comment]
Is there any solution, because i still have this problem and i have to use FTP over SSL/TLS.

btw. #3300 there is also this problem

regards
MasterCevin
