### ISSUE TITLE
Add toggle for File Naming that will prompt for filename

### ISSUE THREAD

**Issue by Reasel** [ShareX/ShareX#4546]
Simply a checkbox that will prompt the user for a filename, but will be pre-filled with the pattern.

This would allow the user to specifically name the file after capturing an image or video without having to navigate, rename, copy, and/or upload.

**Comment by Jaex** [comment]
There is already two different option in after capture tasks to ask for file name before saving.

**Comment by Reasel** [comment]
I was trying to do this with recorded GIF screen recording and it does not seem to prompt for file name. This is not the case for image capture. Is this intended? Am I missing something?

**Comment by traycerb** [comment]
I do seem to have the same issue, prompts for screenshot but not screen recording
