### ISSUE TITLE
ShareX Window

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#4550]
Hello,

How do you get this window to pop up in ShareX 

![ShareX](https://user-images.githubusercontent.com/42359733/71645798-452ba100-2ca3-11ea-80ad-a7e8c85930f3.png)

**Comment by Jaex** [comment]
From here:

![](https://jaex.getsharex.com/2020/01/ShareX_VjsC8OAbyX.png)

**Comment by jdcollier1968** [comment]
I have that checked but it's not popping up. Below I have taken a snapshot of my settings for after capture and before uploads. Can you tell if I have something not configured correctly?

![After Capture](https://user-images.githubusercontent.com/42359733/71645997-0fd48280-2ca6-11ea-9456-b1881fe77daf.png)
![AfterUpload](https://user-images.githubusercontent.com/42359733/71645998-1236dc80-2ca6-11ea-8501-a3614b331128.JPG)

**Comment by jdcollier1968** [comment]
Well?

**Comment by jdcollier1968** [comment]
You know... the support on this site is really terrible.

**Comment by vatterspun** [comment]
I've tested the "after upload" function on ShareX 13.0.1 with a configuration similar to yours and it works fine.  Maybe disable image effects and see if it works?

Also I think #4512 is a dupe of this.  May want to close that issue.
