### ISSUE TITLE
is there a way to use open with on preview toast screen notification 

### ISSUE THREAD

**Issue by sinfulslave** [ShareX/ShareX#4557]
i didn't know if this feature avilable or not and i didn;t notice a section for feedback or suggest
i do use the normal photo viewer apps but some times i need to edit on the fly with any editor mgiht be normal paint app i have to go into folder to edit it 
could u tell me how to use open with on the preview and if not could u please embed this feature
and if there a way to open captured image directly or open folder also tell me how please

**Comment by vatterspun** [comment]
> could u tell me how to use open with on the preview

Could you detail the steps you're wanting the program to follow?  Are you expecting to be able to click on the thumbnail that appears in the bottom-right corner of the screen and selecting your editor?

You might try going to Task Settings - Actions where you can select an editor function:

![image](https://user-images.githubusercontent.com/1289134/73129124-9846fa00-3faa-11ea-8462-217bd5d19e28.png)

I think you might solve this by enabling the "After capture" menu, which can give you some controls after you capture a screen.

![image](https://user-images.githubusercontent.com/1289134/73129132-b44a9b80-3faa-11ea-897f-5fcc0d1b1ada.png)

**Comment by sinfulslave** [comment]
?

**Comment by sinfulslave** [comment]
ur reply was late
