### ISSUE TITLE
Please add separate Erasing Rectangle tool

### ISSUE THREAD

**Issue by rualark** [ShareX/ShareX#4559]
Hi! Thanks for a beautiful project!

When annotating images by removing unneeded details with white filled rectangles and drawing colored non-filled rectangles, one needs to switch rectangle fill and border colors all the time. Can there be added separate Erasing Rectangle or Rectangle2 so that color settings are remembered?

**Comment by Jaex** [comment]
I added it now: https://jaex.getsharex.com/2020/03/Uv8jMODG4u.mp4

**Comment by rualark** [comment]
Thanks! But 13.1 version does not have it yet. When do you plan to release it?
![image](https://user-images.githubusercontent.com/15198808/78607992-c4171380-7868-11ea-9441-d8fb2c74df45.png)

**Comment by Jaex** [comment]
You can use dev build if you would like to try it: https://getsharex.com/docs/dev-builds

**Comment by rualark** [comment]
Thanks, it works
