### ISSUE TITLE
ShareX "Object reference not set to an instance of an object" 

### ISSUE THREAD

**Issue by casualspook** [ShareX/ShareX#4561]
I've seen this issue here before, but mine is not for video files. I was making selected region captures and then twenty seconds later it just stopped working. I don't want to switch programs. I updated from 12.something to 13.0 and the issue still is happening. 

"System.NullReferenceException".  For some reason I can't actually view the error itself, it just goes away if I interact with it. I'm not sure what information would be helpful, I just saw that people were posting sharex problems here. I really like shareX and don't want to change to snippingtool or photofiltre :'( 
i did all the little debug test options and they worked fine.

**Comment by casualspook** [comment]
Its also now uploading to my computer, but the error message still pops up and I can't share an imgur link, even though i tested image uploads. Crisis is averted but I would still like to fix this, since now its slightly more inconvenient.

**Comment by Monoverde888** [comment]
come on sharex why would you think closing stale issues is a good idea
