### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Kamkokos** [ShareX/ShareX#4568]
Full paste:

> Message:
> The request was aborted: Could not create SSL/TLS secure channel.
> 
> StackTrace:
>    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
>    at System.Net.HttpWebRequest.GetRequestStream()
>    at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

I'm uploading to s-ul.eu. It looks like it started happening after the 30th of Dec.

**Comment by laurens84** [comment]
I've got the same problem on my own webserver after upgrading to the new TLS1.3 protocol. I went ahead an checked s-ul.eu and they are also using TLS1.3. I guess they upgraded around 30th of December.

For now i enabled TLS1.2 on my webserver again for the time being. Hope TLS1.3 will be added to shareX soon.
