### ISSUE TITLE
Unable to authorize Google Drive in Opera GX

### ISSUE THREAD

**Issue by odie2** [ShareX/ShareX#4569]
Hello,

Generally I used to need reauthorize Google Drive in Destination settings every 2-3 weeks as it say that failed to upload on Google Drive, even when settings show "Status: Logged in." from I started to use ShareX like 2 years ago.

Same happent a few days ago, but this time it just logged me out completelly and clicking "Open authorize page..." does nothing. None page is opened. Right now while writting ticket, changed default browser from Opera GX to normal stable Opera and noticed it worked. Now not sure should I report it here or to Opera team? Other links opened by default browser (for example news links from game launchers) are fine in Opera GX.

Greetings

**Comment by lucario** [comment]
We can't provide support for browsers, especially unstable ones. You should not need to reauthorize however, we support auth refresh tokens. Ensure ShareX is not being killed or shutdown improperly.
