### ISSUE TITLE
Low image quality

### ISSUE THREAD

**Issue by ljparabolic** [ShareX/ShareX#457]
Hi, there is too much compression for jpegs which is particularly visible when using red color (which is normal for low quality jpeg) http://i.imgur.com/IuGocOB.jpg

I tried changing settings but they doesn't seem to affect the picture quality in any way. I tried both optimizing quality settings (no improvement) or changing to PNG which seems to just not show any effect, images are still being uploaded as JPEG sometimes and sometimes as PNGs. 

http://i.imgur.com/Sqh0i09.png (.NET)
http://i.imgur.com/ahc04Lr.png (Octree)

For example I can take a screenshot of the photoshop UI and it's being uploaded as a PNG http://i.imgur.com/AajSpuv.png

But just when I open a PSD file the screenshots are being saved as JPEG. http://i.imgur.com/bNzwPay.jpg

Love the app nevertheless, best regards.

**Comment by Jaex** [comment]
If image size limit is 0 then it should always use PNG.
Probably you overrided that setting in hotkey setting or something like that.

**Comment by ljparabolic** [comment]
I'm using the same shortcut for all screens
Here's the photoshop screenshot with PSD open with raster layer http://i.imgur.com/FQKUfYj.jpg
And here's the same PSD file with that layer disabled http://i.imgur.com/Ovc3vqK.png

It seems like the content of the picture affects the file format. Maybe there is a limit for the size of PNG and it couldn't handle such amount of raster objects and turns to JPEG instead?. I can't find any settings that might still affect it.

**Comment by Jaex** [comment]
There is file size limit setting which allows you to use JPG for big images automatically. But when you set it 0 then it disables that. So you must have it enabled in default or hotkey task settings otherwise it won't use second file format which is JPG.

**Comment by ljparabolic** [comment]
I already provided the screenshots with settings of image size to 0  http://i.imgur.com/mvx7LiX.png

I'm using default settings for shortcuts http://i.imgur.com/aYHDDOm.png but this isn't the problem, I'm using the same shortcuts for the same screenshot and it's being uploaded as PNG when there is no raster content and as JPEG if there is. So no varation here.

**Comment by Jaex** [comment]
Can you send me your config file because it not make sense how it can use JPG even when you selected PNG as second image format.

**Comment by ljparabolic** [comment]
I will, can you tell me how can I do that? I only found ShareX.exe.config in ShareX folder which doesn't seem to contain any of the important informations.

**Comment by ljparabolic** [comment]
Nevermind, I got it https://dl.dropboxusercontent.com/u/13127874/ShareX/ShareX.zip

**Comment by Jaex** [comment]
Was just needed ApplicationConfig.json and HotkeysConfig.json files.
UploadersConfig.json can contain your account info therefore I removed your message.
Gonna test now.

**Comment by Jaex** [comment]
When I press Ctrl + Shift + 2 with your config it uploads 2mb+ png. Not makes jpg.

**Comment by ljparabolic** [comment]
Ha! Works perfectly http://i.imgur.com/HerqXMQ.png

Thank you for the help!

**Comment by Jaex** [comment]
Response from Imgur:
"Currently we compress images over 5MB for anon uploads. We might lift this restriction down the road, but for now we don't have any parameters to disable this."
