### ISSUE TITLE
Enhancement - Rename images on the fly inside application main window / image list

### ISSUE THREAD

**Issue by user82912** [ShareX/ShareX#4574]
Enhancement Idea - in the main landing page of the windows application, it shows all the screenshot I've taken. Those have their random gen names above them, could it be possible to rename this with the application on the fly but double clicking on the text? Or even a re click menu option on the screenshot to rename the image.

screenshot for help of the text/name location:
<img width="643" alt="ZH3BqoDGAb" src="https://user-images.githubusercontent.com/59927796/72450384-2f919d80-37b2-11ea-9d10-72f2515a9154.png">

thanks!

**Comment by user82912** [comment]
still think this is a nice one to have guys!

**Comment by yfdyh000** [comment]
> still think this is a nice one to have guys!

+1, and work in progress on the source code.
