### ISSUE TITLE
adding external storage

### ISSUE THREAD

**Issue by zintermaertes** [ShareX/ShareX#4575]
Hello everyone,
having problems adding external local storage (USB drive) since I updated to nextcloudpi v.1.20.1.
Doing all the same I did with older versions - so the external drive is added and I can see the folder, but when I click on it, it´s not opening but going back to my files.
Reinstalled nextcloudpi on another sd-card but same behaviour.
I hope the description makes the problem kinda clear.
I´m already using nextcloud for a while but I´m definitely not an experienced user - so any help is highly appreciated!
Regards
Martin

**Comment by vatterspun** [comment]
I think you might be posting this to the wrong forum.  Are you trying to access nextcloud through ShareX?  Can you provide screenshots?
