### ISSUE TITLE
ShareX doesnt properly copy the link 

### ISSUE THREAD

**Issue by juwulie** [ShareX/ShareX#4579]
Basically copies this: {"success":true,"hash":"fpf6B5kj_Ns56zm0gHKfNg==","shorthash":"fpf6","url":"http://julie.u.catgirlsare.sexy/fpf6.png"} instead of the normal url (http://julie.u.catgirlsare.sexy/fpf6.png)

**Comment by IdpugantiSanjay** [comment]
Can you elaborate ?
