### ISSUE TITLE
Toggle Windows night light when taking a screenshot

### ISSUE THREAD

**Issue by xXBuilderBXx** [ShareX/ShareX#4583]
So some people that i know who use ShareX are also using Windows night light which makes screenshots appear a bit orangy and just overall not good for screenshots.

It would be cool if you could disable this when taking a screenshot and then enable it again which is very possible with registry values https://superuser.com/questions/1200222/configure-windows-creators-update-night-light-via-registry.

**Comment by bagnaraex** [comment]
I would like it also.

**Comment by xXBuilderBXx** [comment]
I guess noone responds to these issues sigh
