### ISSUE TITLE
Watch Folder filter to support wildcard in filename

### ISSUE THREAD

**Issue by Reasel** [ShareX/ShareX#4584]
You can do things like `test.*` but not something like `Capture*.mp4` or am I missing something?

**Comment by FrankTurnerSoftware** [comment]
Are you using 2 different folder watchers, 1 for test.*, and 1 for Capture*.mp4?
I tried this, and it works.

**Comment by Reasel** [comment]
No, I have a folder that has a bunch of auto generated videos. I only want to grab the ones with a specific naming pattern. But when I do something like Capture*.mp4 it triggers on nothing.

**Comment by FrankTurnerSoftware** [comment]
I debugged the code from Visual Studio, and the file watcher is triggering. 
Maybe the trigger is working, but something else is broken. 
How do you know it's not triggering? Is a file not uploading or something? Is a configuration set up correctly? Is there anything in Debug/Debug log that is helpful?

**Comment by Reasel** [comment]
It might have been my exact setup. I was having ShareX monitor the folder that houses Xbox Console Companion recordings. By default the naming of the recordings is a certain format. In the app you can trim and save as a new file. I was trying to do that, but its possible that I needed to rename before saving. 

I just tried dragging a "new" file in that should have fit the Capture*.mp4 format and it did not upload. I can try again when I am back at my comp to further test.
