### ISSUE TITLE
Digitally Sign Installer

### ISSUE THREAD

**Issue by dlwillequer** [ShareX/ShareX#4589]
I am reaching out to request that the ShareX installers and/or the files be digitally signed. I am requesting this as my department is exploring the possibility of using this software in an enterprise setting (as an alternative replacement to similar software such as SnagIt and Greenshot) and our security team requires applications to be digitally signed (from a verifiable trust chain) so that it can be validated and recognized as pre-approved software.

I did review prior issues (#578, #1463) opened concerning this and it looks like both issues have been closed and current versions do not contain a digital signature. A list of Certificate Authorities is available here: https://en.wikipedia.org/wiki/Certificate_authority

The cheapest I have been able to find that would be sufficient for this purpose is Certum (which is $25 Euros or Approximately $27.11 USD per year). 

I was also able to find this relevant blog post that details how to digitally sign software using Certum as an example: https://blog.aluxian.com/free-code-signing-certificate-for-open-source-software-d836270823a7

NOTE: I am not affiliated with any of the companies mentioned above.

**Comment by dlwillequer** [comment]
One additional alternative that appears to be free / open-source (Not sure if it would serve the purpose): https://www.vchain.us/ & https://www.codenotary.io/
Looking for a certificate similar to the one pictured below **(SHA-256 preferred)**:
![image](https://user-images.githubusercontent.com/25806407/73225839-779db200-411a-11ea-83ef-ce4063452fcd.png)

**Comment by sylveon** [comment]
Getting a Certum certificate shows your legal name as the certificate common name, which @Jaex understandably does not want to do. Other options like purchasing a full certificate where you could customize the common name are very expensive for an open source project (~200/year)

**Comment by sylveon** [comment]
The alternatives you listed don't go back to any of the Windows-default root CAs

**Comment by xXBuilderBXx** [comment]
There really is no cheap open source cert, as a dev myself i just think it's way too expensive just to sign an app and have it somewhat trusted by windows.
I tried ascertia.com with a trial code cert (originally $17) but even those are not in the windows default trusted certs so it will still popup with the windows defender warning.

**Comment by liberdis** [comment]
A signing cert costs around $8-10 per year. Someone buy the dev a cup of coffee lol.

**Comment by liberdis** [comment]
> > A signing cert costs around $8-10 per year. Someone buy the dev a cup of coffee lol.
> 
> Read the actual comments -_- it dosen't cost $8 more like $100+

Oh my bad i was thinking TLS. Thank you.

**Comment by xXBuilderBXx** [comment]
SSL certs are free, look up letencrypt or use cloudflare.

**Comment by xXBuilderBXx** [comment]
A signing cert dosen't really increase security btw it's just a say for people and windows to show it's visually trusted, there is no issue running ShareX or other programs without one.
