### ISSUE TITLE
How to change ShareX background color?

### ISSUE THREAD

**Issue by it19862** [ShareX/ShareX#4595]
ShareX 13.0.1.
I updated the program to ShareX version 13.0.1.
The background color of the program is black.
I want the background color of the program white.

![2020-01-29_13-14-59](https://user-images.githubusercontent.com/18245828/73348050-bdcd4f80-4299-11ea-8267-fd4e0da62a02.png)

**Comment by Fuzzqt** [comment]
Click Application Settings within the Sharex GUI > Click Install Dev Build > Re-click Application Settings once updating > Click Theme > Check mark Experimental custom theme

You can now have a white or whatever color you desire

Or just click theme and click light instead of Dark

**Comment by it19862** [comment]
I use the Russian version of the program.
I use the Russian version of the program.
And I don’t have the "Theme" item in mei.
Or I do not see.

![2020-02-07_21-07-01_2](https://user-images.githubusercontent.com/18245828/74054160-8162c780-49ee-11ea-8a1b-47b5c5ecb318.png)

![2020-02-07_21-07-01_3](https://user-images.githubusercontent.com/18245828/74054443-22518280-49ef-11ea-9cda-1f664d9bdf8b.png)

**Comment by Fuzzqt** [comment]
My apologies, under General it will say "Use Dark Theme" automatically clicked, if you uncheck this box in the General tab then you should have a default white background

![ShareX_VPVKNVHZbt](https://user-images.githubusercontent.com/47482485/74067051-595f6e00-49c6-11ea-8a7e-d8a2f46b6ecf.png)

I'm not sure if the Russian version differs from any other but for my default client it is under General.
