### ISSUE TITLE
I can't seem to find any way to turn off and delete ShareX or turn off its hotkeys

### ISSUE THREAD

**Issue by logalogwasnotthere** [ShareX/ShareX#4598]
When I try to delete ShareX, it gives me a notification that says its running, and to close it. The problem is is that I can't find where its open and how to close it.

The second problem is when I try to turn off its hotkeys, it won't let me. The official tutorial said to press ctrl, alt, and f8 to open a dialogue that allows you to turn the hotkeys off, but it wouldn't let me open that dialogue. When I press all three keys at the same time, nothing happens. When I go to the settings on the program itself, there is no way to turn off hotkeys.

Can someone help me figure out what to do? The program's hotkey settings are messing up a bunch of my other programs, and I want to either delete ShareX, or turn off the hotkeys.

**Comment by Fuzzqt** [comment]
Right click your Sharex icon on the tray bar > Click Disable Hotkeys in the menu.
