### ISSUE TITLE
Is upload screenshot to Slack possible?

### ISSUE THREAD

**Issue by cagross** [ShareX/ShareX#4599]
Hello.  Currently I have configured ShareX to upload my screenshot to imgur, with a hotkey.  But I frequently need to post my ShareX screenshots to Slack instead (via the Slack app for Windows).  Is it possible to do the same with Slack, i.e. post my ShareX screenshot to Slack with a hotkey?  

I had a look at the application settings, and in the upload-->secondary uploaders section, did not see Slack ([screenshot](https://i.imgur.com/BrMjdFx.jpg)).  But I just thought I'd ask here.  I realize posting to Slack is a little more complex than simply posting to imgur (e.g. which Slack channel to use, etc).

Thanks.

**Comment by simieski** [comment]
I'd love to see this reopened.
