### ISSUE TITLE
Doesn't remember destinations

### ISSUE THREAD

**Issue by jms1989** [ShareX/ShareX#460]
I'm not sure why but ShareX will not remember destinations which results in failed uploads every time the computer starts. I can set a destination, close the program, reopen it and the setting is lost.

**Comment by Jaex** [comment]
ShareX saves settings even when you minimize ShareX to tray. So I'm not sure how it failing. It is expected when PC closing sometimes it won't allow saving settings but still when minimizing it should be saving your selected destinations.

**Comment by jms1989** [comment]
How can I get a debug print out on what's happening?

I can set the destination and it'll remember it as long as it's running but once the program is terminated manually or by shutting down the computer, it forgets the destination credentials.I'm using windows 7 and the latest version of sharex.

**Comment by Jaex** [comment]
In debug log window you can see every single setting saving and loading. And when it fails, it will show there too. Debug log saved in ShareX personal folder. But mainly if settings not saving it is possible debug can't save too.

**Comment by jms1989** [comment]
Hmm, I don't know what I did but it seems to be saving my config now. debug output didn't show any errors. It hides the tinypic username and password after the window is closed which made me think it wasn't saving.
