### ISSUE TITLE
When saving to an existing filename, typing a new name and pressing Enter should save file

### ISSUE THREAD

**Issue by jimbo1qaz** [ShareX/ShareX#4601]
I set up ShareX to ask for a name before it saves any screenshots. This allows me to find the screenshot I want in the massive haystack of my screenshot folder.

When I pick a name that I have already used, ShareX pops up a dialog saying "There is already a file with the same name in this location...". Typing a name and pressing Enter does nothing, I have to press Tab to focus the "Use new name: ..." button, before pressing Enter.

I think pressing Enter when the text field is focused should automatically trigger the "Use new name" button, if the new name is unique. Otherwise it should do nothing.

**Comment by Jaex** [comment]
Good idea.
