### ISSUE TITLE
Installer Changes Feature Request 

### ISSUE THREAD

**Issue by mcrichman** [ShareX/ShareX#4603]
You have created a Great program with many very useful options.  I am looking to deploy it at my company, however all of the options can be a bit overwhelming to new users or in an environment that does not want to allow some of them.  

I have seen other suggestions about separating into two programs, I thought it would be great if the installer provided more options like being able to configure what parts get installed or enabled?  If it goes to an MSI that allows for managed customizing using an mst.  This could be a great option for those looking to manage shareX in a business environment.

I think there is a nice template for installer options on your main website https://getsharex.com that identifies the categories and the features in them.

Thank you for your consideration.

**Comment by vatterspun** [comment]
Could you add a more descriptive title than "feature request"?

> I have seen other suggestions about separating into two programs

Where?

**Comment by mcrichman** [comment]
I saw the discussion about two programs on an earlier ticket from 2018.  
https://github.com/ShareX/ShareX/issues/3403 

Thanks For All of the great work you do with ShareX.  It is a great program that has clearly had MANY hours put into it!

Thanks!

**Comment by vatterspun** [comment]
> Thanks For All of the great work you do with ShareX

I can't take credit for this excellent program, just trying to help out with the issues.

> two programs on an earlier ticket

I had not seen that -- I'm not sure if Jaex will reconsider the program separation idea mentioned in #3403

**Comment by mcrichman** [comment]
I was trying to offer an alternative to splitting the code base by offering improved installer options to allow people to only install the features they want.

thank you!
