### ISSUE TITLE
[Feature Request] Extended Active Capture

### ISSUE THREAD

**Issue by caburum** [ShareX/ShareX#4604]
It would be very useful if this feature was added. It resizes the window to be very long, and then captures it so you can have an entire webpage without any glitches like with scrolling capture.

**Comment by CCreativeCND** [comment]
This is still needed

**Comment by Silver-Fullbuster** [comment]
Still needed

**Comment by Silver-Fullbuster** [comment]
Still needed

**Comment by Silver-Fullbuster** [comment]
Still needed
