### ISSUE TITLE
[Feature Request] HTML Screenshot Selection Snapping 

### ISSUE THREAD

**Issue by Jet132** [ShareX/ShareX#4605]
A very useful feature would be to have the selection snapping feature that ShareX currently uses on windows and window elements (only in some cases) also working for HTML. 
This could probably be implemented using an extension or some other way. The benefit of an extension would be to also have other requested features like #4604 implemented.
I can't think of another way to implement this but if there is another way, it would maybe be possible to also support apps with embedded HTML in it like Electron apps.

**Comment by CCreativeCND** [comment]
This is still needed
