### ISSUE TITLE
[Feature Request] Send SQL data

### ISSUE THREAD

**Issue by 78wesley** [ShareX/ShareX#4611]
It would be great to send some SQL data to a database after I made a screenshot.

**Comment by JeremyCrookshank** [comment]
What do you mean? To your own database?

**Comment by 78wesley** [comment]
Yes to a own database. like phpmyadmin.

**Comment by 78wesley** [comment]
maybe something like this.
| basename      | name          | filetype      | program       | uploaddate            | uploaddateyear | uploaddatemonth| uploaddateday | uploaddatetime | size          | createdatetime      | createdateyear | createdatemonth| createdateday | createtime     | videolength |
| ------------- | ------------- | ------------- | ------------- | -------------         | -------------  |  ------------- | ------------- | -------------  | ------------- | -------------       | -------------  |  ------------- | ------------- | -------------  | ----------- |
| photo.png     | photo         | png           | chrome        | 10-03-2020 01:01:42   | 2020           | 03             | 10            | 01:01:42       | 42            | 10-03-2020 01:01:40 | 2020           | 03             | 10            | 01:01:40       |             |
| abcde.mp4     | abcde         | mp4           | windows       | 10-03-2020 01:02:42   | 2020           | 03             | 10            | 01:02:42       | 1337          | 10-03-2020 01:02:40 | 2020           | 03             | 10            | 01:02:40       | 00:04:20    |
