### ISSUE TITLE
Screenshots from color managed applications use the post-calibration colors instead of the original pixel color values

### ISSUE THREAD

**Issue by Chillstice** [ShareX/ShareX#4613]
This issue involves color-calibrated screens, monitor color profiles, and embedded image color profiles. Here's an excellent - albeit long - video explaining facets of color profiles as well as showcasing this issue: https://youtu.be/QPubgoqtfbk

**Versions**
```
ShareX 13.0.1
Windows 10 64-bit Build 18363
Adobe Photoshop CC 21.0.3
DisplayCal 3.8.9.3
ArgyllCMS 2.1.2
ImageGlass 7.5.1.1 (Color-managed image viewer that honors monitor profile)
Firefox Nightly 64-bit 75.0a1
```
**I imagine someone's going to link to these other issues, so I'll just do it first**
[#2501](https://github.com/ShareX/ShareX/issues/2501) [#1236](https://github.com/ShareX/ShareX/issues/1236) [#2670](https://github.com/ShareX/ShareX/issues/2670)

**What should happen**
When taking a screenshot of a color-managed application that adjusts for the current monitor's profile, the screenshot should use the raw logical pixel values for color instead of capturing the colors post-correction. The monitor's color profile is specific to that one monitor and shouldn't be immortalized in the screenshot for sharing on other monitors. 

When viewing the screenshot of a color-managed application with another color-managed application, the monitor correction will only be applied once rendering correct and accurate colors.

**What actually happens**
The screenshot captures the colors after the application has already changed them using the monitor's color profile. This means that the unique monitor profile is essentially baked-in to the image. If the image is then viewed with another color-managed image viewer that adjusts for the same monitor profile, the correction is doubled, meaning it is over-corrected. 

Color-management has to be disabled before taking a screenshot or else the source-material is vulnerable to being permanently altered in the resulting screenshot. This takes time, can be easily forgotten, and is a clunky work-around.

**Example**
A 1000x1000px image with a full-spectrum rainbow gradient in the srgb IEC61966-2.1 color space is generated and exported:
**Original PS export srgb embedded** https://s.chillstice.com/wtXWk

A screenshot of the image is taken directly from the Photoshop preview window:
**Screenshot of the original from Photoshop** https://s.chillstice.com/H8B3i

A screenshot of the original image is taken from a non-color managed application that shows the raw pixel values:
**Screenshot from Paint** https://s.chillstice.com/klTj1

Here's a comparison image: https://s.chillstice.com/OK4lQ

In theory if I were to take a screenshot of this image from my color-managed image-viewer (ImageGlass) over and over, the image will eventually lose all saturation because my monitor profile is de-saturating the srgb color gamut because the monitor is capable of displaying a larger gamut. The corrective profile that's being baked-in and applied over and over is lowering the saturation.

**Comment by sylveon** [comment]
It's basically going to be the same answer than the issues you link: GDI, which ShareX uses, does not handle color profiles.

**Comment by Jaex** [comment]
Duplicate of #2501 #1236 #2670
