### ISSUE TITLE
Allow for editing filename before saving/uploading

### ISSUE THREAD

**Issue by can0k** [ShareX/ShareX#462]
Is it possible to add an option for editing the filename in the "After Capture" tasks list?  I appreciate that you can add the process name and/or window title to a window capture, but there doesn't seem to be any way to add similar details to a rectangle capture's filename.  Rather than adding the %pn or %t options to the rectangular capture, I was thinking offering the option to edit the filename in the After Capture tasks would offer the most flexibility.  An alternative suggestion would be to offer this functionality in the Image Editor.

Thanks

**Comment by McoreD** [comment]
Great idea. This was possible in ZScreen and it is something we overlooked
to port.

**Comment by alisa-rend** [comment]
:+1:

**Comment by damikem** [comment]
How about using the 'Save image to file as' workflow, where you can change the name of all the captures?

**Comment by can0k** [comment]
I just checked out 9.6, thanks for a great solution!

**Comment by Jaex** [comment]
Added it to "Post capture tasks" window now:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/10/ShareX.vshost_X4aDdmqVS3.png)
