### ISSUE TITLE
How to work with destination settings?

### ISSUE THREAD

**Issue by Perezari** [ShareX/ShareX#4623]
When im using the source code and trying to connect for example to google drive im getiing this error from google drive: **Missing required parameter: client_id**
and im getting errors from webs in all destinations.
how to fix it or how use it?
![chrome_2020-02-20_08-28-19](https://user-images.githubusercontent.com/24621247/74906928-040a6000-53bb-11ea-8db4-84b83be28ff2.png)

**Comment by Jaex** [comment]
Source code not contains API keys.

**Comment by Perezari** [comment]
ok how can i add my api keys?
