### ISSUE TITLE
[Request] Encrypted credentials for FTP destination settings export

### ISSUE THREAD

**Issue by theelectricsoul** [ShareX/ShareX#4625]
We use ShareX in a sensitive environment.

It would be great if the FTP destination settings could be exported without revealing the actual credentials. Encrypted crendetials would be great.

thank you for the awesome software :)

**Comment by lucario** [comment]
If you really use it in a sensitive environment, there are better alternatives than using FTP credentials. SFTP with keys is arguably more secure, and your disk should be fully encrypted with something like Bitlocker.

**Comment by theelectricsoul** [comment]
I elaborate :)

We use shareX in our company. Hundrets of users. It is problematic, if they see the FTP credentials.
