### ISSUE TITLE
Cannot screen record properly with headset earphone

### ISSUE THREAD

**Issue by MisesEnForce** [ShareX/ShareX#4629]
I have a headseat earphone that works properly with my laptop (under lastest win10 pro update).

1. If I plug it to my laptop, and if in ShareX I do "Task settings ... --> Screen Recorder --> Screen Recording options" and if I select there, in "Audio Source", my headset earphone (detected by ShareX as "Headset Microphone") and if I do a "Capture --> Screen Recording" then in the resulting video, I hear the sound of me speaking in the microphone, but not the sound that I hear in the headset during the recording
2. If I use the microphone and sound of my laptop instead of my "headset earphone", everything works as expected, meaning that I ear in the recorded video both sound.

How could I achieve the same behaviour as in 2 but in the case 1 ?

My use case is simple and is the following : I want to screen record a skype video call, by recording the skype window of the call and while using my headset earphone, and I want to have sound when I speak and when my correspondant speaks in the resulting recorded video.

[For privacy reasons (I am working in a company) I can't use the skype integrated functionnality allowing for recording the whole video conversation as the resulting recording is apparently made on skype servers, from which I have to download it after, and my legal department forbids me to do it because of the fact that the conversations are stricly confidential and cannot be on skype servers.]

**Comment by Fuzzqt** [comment]
I'd recommend using OBS for supporting multiple audio sources and recording a screen.

https://obsproject.com/

**Comment by MisesEnForce** [comment]
It indeed worked perfectly in cases 1 & 2 with OBS, thanks for the suggestion.

**Comment by g-franck** [comment]
> I have a headseat earphone that works properly with my laptop (under lastest win10 pro update).
...
> [For privacy reasons (I am working in a company) I can't use the skype integrated functionnality allowing for recording the whole video conversation as the resulting recording is apparently made on skype servers, from which I have to download it after, and my legal department forbids me to do it because of the fact that the conversations are stricly confidential and cannot be on skype servers.]

it works fine if you install the recorder devices in Screen recording options and setup Audio source as virtual audio capturer
