### ISSUE TITLE
[BUG] Sharex 13.0.1 -  Outlines - No longer outlining the selected colour

### ISSUE THREAD

**Issue by Insert2Coins** [ShareX/ShareX#4631]
As per title, the outlines will not show the coloured outline as per the settings. Have tried to uninstall and reinstall. Close and reopen fully without any luck. Attached is a gif with the issue. 

![ShareXissue](https://user-images.githubusercontent.com/61440380/75205198-3eaf3680-57c7-11ea-80bf-1ee9280585a1.gif)

**Comment by Insert2Coins** [comment]
Have also tried other colours for outline - not working 
Changed filled colour to NOT transparent - working

**Comment by Fuzzqt** [comment]
Shape Options > Make sure your border size is not 0, if zero there will be no outline.

**Comment by Insert2Coins** [comment]
Oh man, thanks so much. Sorry about that !
