### ISSUE TITLE
Fit in window

### ISSUE THREAD

**Issue by neesti** [ShareX/ShareX#4632]
Hello.
When I open an image for editing with ShareX, I need it be open as fit of windows, NO in actual size!

Sorry for My bad English.

**Comment by Fuzzqt** [comment]
I'm assuming you mean when you run Edit Image... You want the window to be fully maximized? If so right far on the GUI panel click Options > Editor Start Mode > Maximized

**Comment by neesti** [comment]
NO! 
I need to add an  this option (Fit to window) to Editors start mode.

**Comment by neesti** [comment]
Fit To Window sets an image display mode based on the window size. In this mode, when the window is resized, the image is resized. The image size matches the window size apart from window space needed to maintain the image's height-to-width ratio.

**Comment by neesti** [comment]
Would you please to label this issue as enhancement?

**Comment by neesti** [comment]
Would you please add this useful feature to ShareX 13.1.0?
