### ISSUE TITLE
ShareX does not start with windows

### ISSUE THREAD

**Issue by derekantrican** [ShareX/ShareX#4637]
I have ShareX set to start with Windows (see screenshot) but it does not

![](https://i.imgur.com/XiW5AOF.png)

Any suggestions?

**Comment by Fuzzqt** [comment]
That is indeed odd, if you've already tried to shell:startup it via windows documentation with no luck I'd suggest trying to set up a custom startup with Task Scheduler which is baked into Windows. 

Here's a guide


https://www.howtogeek.com/138159/how-to-enable-programs-and-custom-scripts-to-run-at-boot/

If that doesn't work i'd try re-installing, but not sure. Make sure to update your windows as well and sfc /scannow within CMD admin to check for corrupt files.

![0BTypKbiqSSaturday](https://user-images.githubusercontent.com/47482485/75612025-d4133900-5aed-11ea-88f8-e50697b30c23.png)

Also make sure that's checked in the Application settings

**Comment by derekantrican** [comment]
Yep, I have that checked in application settings. I'll try the Task Scheduler thing
