### ISSUE TITLE
Error while using the multi region mode toggle.

### ISSUE THREAD

**Issue by JLiszt** [ShareX/ShareX#4641]
Greetings,

I'm getting an error message if I enable the advanced option RegionCaptureDisableAnnotation and then try to toggle multi-region mode (pressing Q). The message is the following:

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ShareX.ScreenCaptureLib.ShapeManager.form_KeyDown(Object sender, KeyEventArgs e)
>    at System.Windows.Forms.KeyEventHandler.Invoke(Object sender, KeyEventArgs e)
>    at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
>    at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
>    at System.Windows.Forms.Control.WmKeyChar(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Form.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> ShareX 13.0.1 Portable (Release)

The error window allows the user to continue, so it's no biggie, but I wanted to report it anyway. And thanks for providing this awesome tool for free to all of us. It's incredibly useful.

**Comment by Jaex** [comment]
It is already fixed in pre release build.
