### ISSUE TITLE
Persian (Farsi) Numbers

### ISSUE THREAD

**Issue by neesti** [ShareX/ShareX#4642]
Hello.
When I edit an image into ShareX and click on "Step (I)", Numbers shows as English format. We (Persian users) need Persian numbers instead of English numbers. 

![image](https://user-images.githubusercontent.com/14938202/75647514-6d635c00-5c62-11ea-8d15-1d8f0ff9f944.png)

**Comment by xmha97** [comment]
English Numbers:
`0` `1` `2` `3` `4` `5` `6` `7` `8` `9`
Persian (Farsi) & Arabic Numbers:
`۰` `۱` `۲` `۳` `۴` `۵` `۶` `۷` `۸` `۹`
If ShareX allows me to change the font of the "Step" tool, this issue will be resolved.

**Comment by Jaex** [comment]
I don't think changing number format automatically depending on locale will be good idea because still persian users may prefer global format. Because when it is global format everyone can understand the order including persians, right?

**Comment by xmha97** [comment]
> 
> 
> I don't think changing number format automatically depending on locale will be good idea because still persian users may prefer global format. Because when it is global format everyone can understand the order including persians, right?

You do not need to add number settings.
If ShareX allows me to change the font of the "Step" tool, this issue will be resolved.
![Notepad](https://user-images.githubusercontent.com/23485114/76137700-1fc96380-6055-11ea-84f1-9eebeb804482.gif)
