### ISSUE TITLE
Improve 100% JPG image quality 

### ISSUE THREAD

**Issue by AlexBurkhardt** [ShareX/ShareX#4644]
Hi there, ShareX has become my favorite screen capturing tool in record time! There is only one small detail which I hope you can improve.

Even when you set the JPG image quality to 100% it still feels like 50% compared to other tools which use JPG compression. I've attached a screenshot (200% zoomed in) where I compared a PNG converted to JPG in IrfanView and in ShareX:

![jpg-compression](https://user-images.githubusercontent.com/12297941/75796566-26658b80-5d74-11ea-8c3d-4e4540c713fe.png)

You can clearly see the compression artifacts in ShareX around the text on the right. In IrfanView however, there are hardly any artifacts visible at 100% JPG quality. Is it supposed to be like that in ShareX or am I missing something?

Many thanks,
Alex

**Comment by Jaex** [comment]
We are using JPG encoding exists in .NET Framework, so without use external image encoding libraries it is not possible to get such results.

**Comment by nixxquality** [comment]
Would you be willing to accept a pull request to use something like [mozjpeg](https://github.com/mozilla/mozjpeg) instead of the .NET Framework API?

I've considered doing an experiment to that end, but I would like to know that I'm not wasting my time before I start.

**Comment by Jaex** [comment]
I prefer to keep external dependencies to minimum as possible, therefore I don't want to include external image encoding library.

But you can use actions support of ShareX to encode using any CLI encoder you want, which will be seamless enough.
You can check here for examples: https://getsharex.com/actions/

**Comment by nixxquality** [comment]
Thank you, that was a lot easier than rooting through the source code.

If you want to use mozjpeg, grab an exe from [their releases page](https://github.com/mozilla/mozjpeg/releases), put it somewhere safe.

In Task Effects -> Image set format to BMP and uncheck "Use JPEG as image format if image size is bigger than ..."
In Task Effects -> Actions add a Mozjpeg action like
File: cjpeg.exe (or cjpeg-static.exe)
Arguments: `-optimize -quality 95 -outfile "$output" "$input"`
Output extension: jpg
[x] Hidden window
[x] Delete input file

**Comment by Jaex** [comment]
I should add example for it to actions page too. But I'm not sure how good mozjpeg encoder is compared to ImageMagick jpeg encoder.

**Comment by nixxquality** [comment]
Perhaps, I'm just leaving it as an example for someone that happens to find this thread :) 

If you're curious, here's a writeup about what makes mozjpeg special (as far as I know): https://calendar.perfplanet.com/2014/mozjpeg-3-0/

**Comment by Jaex** [comment]
What about https://github.com/google/guetzli ?

**Comment by Jaex** [comment]
Added MozJPEG example to actions page now: https://getsharex.com/actions
