### ISSUE TITLE
Black screen When trying to capture on the second monitor

### ISSUE THREAD

**Issue by yaronelh** [ShareX/ShareX#4647]
Hi, I am experiencing a blacks screen when trying to capture the second monitor.
ShareX seems to be detecting all the windows on the screen, the dashed capture indication Is still seeing the windows when I move the mouse on the other screen, but it's blacked if I try to capture.

Here's a captured screenshot of both screens at the same time (The right monitor is black)
https://i.imgur.com/NXNGMnJ.png

**Comment by Fuzzqt** [comment]
Were you running a game on that 2nd monitor by any chance? ShareX won't capture full screen games(will just give you a black screen), try using windows mode or fullscreen borderless if this is the case.

**Comment by yaronelh** [comment]
No, just normal usage no game or anything.

**Comment by Fuzzqt** [comment]
Only thing I can think of is DRM protected content or your anti-virus, I've seen people have issues with Avast, Webroot, and a few others. 

Have you tried taking screenshots of just your browser in both monitors? Or is it black 100% of the time no matter what you're screencapping? 

Do me a favor and try snipping tool (windows built in) that same process that blacked out for ShareX and see if it blacks out again.

**Comment by yaronelh** [comment]
interesting... It is black for the snipping  tool  as well (did know this
tool existed)
it's 100% black no matter what I'm trying to capture on the other screen

**Comment by Fuzzqt** [comment]
Hmm, try updating your graphics drivers and restarting. Cube seemed to have that issue at one point and that fixed it for him. Also make sure your windows is up to date but the culprit may be fixable with a graphics driver update.

**Comment by yaronelh** [comment]
Graphic Drivers and Windows are up-to-date, I tried to that first
Mmm...
