### ISSUE TITLE
Can't select items on thumbnail view

### ISSUE THREAD

**Issue by xmha97** [ShareX/ShareX#4648]
Hello, I want to report an issue with ShareX.
Can't select items on the thumbnail view
![ShareX](https://user-images.githubusercontent.com/23485114/76137236-9ebb9d80-604f-11ea-816f-5b83c451f201.gif)
Thanks.

**Comment by Jaex** [comment]
It is difficult to implement therefore I couldn't implement it. But in pre-release version atleast I added support for selection by holding ctrl or shift keys and then clicking thumbnails.
