### ISSUE TITLE
How to directly open qrcode window without opening ShareX

### ISSUE THREAD

**Issue by snowman** [ShareX/ShareX#4649]
![image](https://user-images.githubusercontent.com/16096559/76145307-5c33a880-60c3-11ea-9d01-1b371d9b5886.png)

**Comment by Fuzzqt** [comment]
You can set a keybind to automate the window like you would with screen capture.

![bSfA7MWrIqSaturday](https://user-images.githubusercontent.com/47482485/76145558-653b6000-6058-11ea-94e6-32bfda853165.png)
