### ISSUE TITLE
Some borders aren't themed correctly in dark mode (see screenshot)

### ISSUE THREAD

**Issue by Gladuin** [ShareX/ShareX#4651]
Some elements aren't themed correctly when using the dark theme. See the screenshot below for an example (the white borders around the after capture settings for example).

![Naamloos](https://user-images.githubusercontent.com/34450360/76324578-274f6d80-62de-11ea-92ca-35023b894812.png)

**Comment by Jaex** [comment]
Because I can't theme them. Win form controls very limited, unless you make your own control.
