### ISSUE TITLE
Warning after capture since upgrade to 13.1

### ISSUE THREAD

**Issue by okulair** [ShareX/ShareX#4652]
Since last upgrade, I am getting a warning message after every capture:
"This feature will not work when "DisableUpload" option is enabled!"

My DisableUpload is enabled but I do not know what other feature is causing this message.

Thanks

**Comment by TameTheCloud** [comment]
I also have this warning come up, I've tried playing with a few several upload settings but none make any difference.

**Comment by Jaex** [comment]
You have this option enabled:

![](https://jaex.getsharex.com/2020/03/FUVoVJ1cqu.png)

So ShareX warning you telling that your upload option is enabled yet it can't be done because you disabled uploading application wide. So you must uncheck that option from after capture tasks menu.

**Comment by simonl65** [comment]
Thank you :-)

**Comment by Speiger** [comment]
Sadly this isn't a fix for my issue. It was disabled for me by default. Even by redisabling it (toggling it twice) it still does it.
Also maybe pin one of these so it will be found easier

**Comment by Speiger** [comment]
For Everyone who has this issue still even after doing what the developer is suggesting.
Here is a simple fix:
https://github.com/ShareX/ShareX/releases/tag/v13.0.1
Install that version disable updates for a bit and you have no longer this bug that was introduced 1 version later

**Comment by davcomNZ** [comment]
> 
> 
> For Everyone who has this issue still even after doing what the developer is suggesting.
> Here is a simple fix:
> https://github.com/ShareX/ShareX/releases/tag/v13.0.1
> Install that version disable updates for a bit and you have no longer this bug that was introduced 1 version later

23/3/2020

• The "fix" for the "This feature will not work when "DisableUpload" is enabled." is surprisingly simple to apply.
• The conflict arises from having DisableUpload option enabled but you also have an After Capture task enabled of "Upload image to host".
• Not immediately apparent but if you see this option here "Upload image to host" in bold simply click it to de-bold it and that After Capture task will not be enabled and you will not get the warning.
• Jaex, can I suggest that you reword the notification to show that after de-selecting this "After Capture task > Upload image to host" by clicking it will correctly disable the DisableUpload warning ? or, better yet, if the DisableUpload=True (which had to be manually selected originally) then de-select this After Capture task by default during an upgrade/install and perhaps say so?
![DGE-P15F_20200323_1004-07_firefox](https://user-images.githubusercontent.com/18519634/77261046-835bbe00-6cf0-11ea-88d1-13b626c53678.png)

**Comment by Speiger** [comment]
@davcomNZ i had this option disabled. And it still did it. Unless there was a "fix" for it done recently after i made my "fix" description

**Comment by KleinDevDE** [comment]
This issue comes back with the latest Release 13.4.0 :/
I have disabled the option that the image is uploaded directly.
Still I get this message..,

I use ShareX for work and need to make screenshots regularly, so the DisableUploads is at "TRUE" for security reasons.
This message popup is quite annoying.
Also, the editor does not open now after the screenshot is taken.

![image](https://user-images.githubusercontent.com/13904220/103880337-4757e500-50d9-11eb-890c-aca518300656.png)
![image](https://user-images.githubusercontent.com/13904220/103880369-4fb02000-50d9-11eb-9d96-d868df6dd2ff.png)
![image](https://user-images.githubusercontent.com/13904220/103880414-58a0f180-50d9-11eb-8f0e-2420eb1ab2d3.png)

**Comment by KleinDevDE** [comment]
Embarrassing

Seems to be gone after I restarted ShareX

**Comment by HairyMilkshakes** [comment]
2 years later and this bug is still here. 

- After capture task: upload to host disabled
- DisableUpload: true

**Comment by Speiger** [comment]
@Jaex honestly at this point just delete this issue.
The problem has been solved a year ago or so for me.

**Comment by HairyMilkshakes** [comment]
This problem is STILL present in v19.0.2 lol
