### ISSUE TITLE
[Request] Left/Right/Center align for image combiner (+drag&drop).

### ISSUE THREAD

**Issue by Mitsuma** [ShareX/ShareX#4655]
I'm quite the fan of the image combiner but I always notice that it just combines them left aligned.
Like this: 
![KpOhZpU4hH](https://user-images.githubusercontent.com/8568089/76365960-ecbef280-6328-11ea-9e9a-87697ba165e7.png)

It would be nice to have the options to just center them or right align like this:
![022](https://user-images.githubusercontent.com/8568089/76365994-ffd1c280-6328-11ea-80b8-cf82c4a5980d.png)

Also I could swear that drag&drop worked in the past, there was even an issue here. #1484 
I was wondering if that somehow got removed again on accident. (v13.1 windows 64bit)

**Comment by Jaex** [comment]
Running ShareX as admin causing drag n drop issues because installer needed to run as admin. So restarting ShareX should fix your issue.

**Comment by Mitsuma** [comment]
It did fix the issue with drag and drop, thanks.

**Comment by Jaex** [comment]
Like this:
https://jaex.getsharex.com/2020/03/w3xbVq0jAd.png
https://jaex.getsharex.com/2020/03/78rMQ4Yftp.png
https://jaex.getsharex.com/2020/03/SlRriQhsTV.png
https://jaex.getsharex.com/2020/03/iap7Ux7OEq.png
https://jaex.getsharex.com/2020/03/IPMu5CdmAr.png
https://jaex.getsharex.com/2020/03/dbaq82qDBQ.png

**Comment by Mitsuma** [comment]
Exactly what I imagined.
