### ISSUE TITLE
[Request] Merge social icons with the donate button

### ISSUE THREAD

**Issue by jinkaitoo** [ShareX/ShareX#4656]
Having the icons under a tab and merged with the Donate button would be better than 5 30x30 icons.

**Comment by AstralFS** [comment]
I was just about to make a request like this and you beat me to it. I think the icons are a bit too distracting in the UI, personally.

**Comment by worldsdream** [comment]
I find it distracting as well. Hopefully the dev(s) will take this in consideration.
