### ISSUE TITLE
[Suggestion] More convenient control

### ISSUE THREAD

**Issue by fantasyz** [ShareX/ShareX#4663]
First of all, thank you for making ShareX, it is a very nice tool Here is a little suggestion after using it for a year:

1. Hold [Print Screen] key and drag the mouse on the screen to do a region capture.
Not need to move mouse cursor to the tray icon~ yay~

2. Allow customize combination shortcut to quick determine capture to clipboard or file.
For example, I would like to setup the key to work lilke:
[Print Screen] = capture to clipboard.
[Ctrl] + [Print Screen] = capture to file.

Thanks

**Comment by Nicofisi** [comment]
> Hold [Print Screen] key and drag the mouse on the screen to do a region capture.
Not need to move mouse cursor to the tray icon~ yay~

You can use ctrl + print screen for that by default
> Allow customize combination shortcut to quick determine capture to clipboard or file.
For example, I would like to setup the key to work lilke:
[Print Screen] = capture to clipboard.
[Ctrl] + [Print Screen] = capture to file.

You can already do that using Hotkey settings -> Add... -> Task: screen capture: capture entire screen -> Override after capture settings -> select whatver you need. And then close the window and choose a shortcut for this action.

I hope I helped :)

**Comment by fantasyz** [comment]
Oh thank you. It definitely helped!
