### ISSUE TITLE
Bug cursor position when capturing video

### ISSUE THREAD

**Issue by mcka-dev** [ShareX/ShareX#4665]
I found a bug when capturing video in HiDpi. 
My configuration:
Version ShareX: 13.1
OS: Microsoft Windows [Version 10.0.18363.719] 64 bits
Display resolution: 3840x 2160 pixels **scaling: 150%**

When recording the screen scale is not taken into account as a result we get an error 
![изображение](https://user-images.githubusercontent.com/16173503/76501203-e5940380-6452-11ea-9157-d986114487b6.png)

**Comment by YalandHong** [comment]
Duplicate of #1329
You should discuss about the problem and find the possible solutions there

**Comment by mcka-dev** [comment]
In ShareX: 13.4 it worked, the cursor is positioned correctly, but the cursor size is very small((
