### ISSUE TITLE
Access to the Path is Denied

### ISSUE THREAD

**Issue by patocl** [ShareX/ShareX#4666]
After updating Sharex to the last version 13.1, I got this error!
I try run normal and as administrator and I still getting the problem

System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite)
   at ShareX.SettingManager.MigrateHistoryFile()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)

Thanks and I hope to recover soon my version, maybe I will to try downgrade my version
Cheers and nice job!

**Comment by haydenslee** [comment]
We have the exact same issue after upgrding to V 13.1 tonight on our Terminal Servers.

Running Server 2008R2
Folder has the correct permissions.
Never had this issue with previous versions

System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite)
   at ShareX.SettingManager.MigrateHistoryFile()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)

**Comment by tamusjroyce** [comment]
users\...\Documents\ShareX is the incorrect place to save settings files. Should be users\...\local\AppData

Reason: Antivirus and valid folder permissions prevents ShareX from working. Anyone have time to correct by building a PR?

**Comment by alfredneu** [comment]
Any news on this? I still have this issue on my laptop with ShareX 13.3 portable. Same with 13.2.

**Comment by agungsp2000** [comment]
im experiencing this, after update from 13.3 to 13.4, i've even set sharex to run as adminsitrator mode, still denied, error dialog : https://i.imgur.com/vdsKaJ7.png

**Comment by agungsp2000** [comment]
> im experiencing this, after update from 13.3 to 13.4,

rolling back to 13.3 fix the problem, so the problem is the new 13.4

**Comment by DasDunkel** [comment]
Your issue isn't ShareX, it is the Anti Virus software you have installed blocking ShareX from writing to Documents, usually Avast :)

**Comment by alfredneu** [comment]
Don't think it is the anti-virus, and I don't use Avast. I use Symantec, which is really bad, but it usually complains noticeably when it blocks something. Instead, I think it has to do with the files located on a shared location. For agungsp2000, it is Dropbox, for me it is Onedrive. 

Another observation from my case: The new "*.json-temp" config files are written OK, but the file move to the "*.json" location fails. 

==> I think that the function used for the file move does not work well if the directory is being monitored by a sharing software.

**Comment by wiredzax** [comment]
After installing one of the dev builds, 13.4.1.5072, it has seemed to fix it on my computer. if you're feeling risky i'd say go for it, but i don't know how stable it will be in your computer.

**Comment by kamekku14** [comment]
Actually got this error, too:
![image](https://user-images.githubusercontent.com/66167734/103476294-5b58c980-4def-11eb-95be-1b66de8f2f1b.png)

**Comment by jimuthere** [comment]
In my case, it appears that Avast anti-virus may have been the cause of this error.  
 
I resolved by:

In ShareX, select **Application settings...:  Paths.**

Under "**ShareX personal folder**", Browse to select the normal directory that ShareX uses  i.e. **C:\Users\you\Documents\ShareX**  (or any other path you wish to use) and press Apply. 

Now, or when you attempt your next screenshot, an Avast dialog will be displayed.  Click on "allow", not "block".

**Comment by 1smrt-cgardom** [comment]
I just created a GitHub account, but this can be related, Have you ever heard of virus total, well, look at this, It may be your antivirus or the privileges of the folder
![Captura de pantalla 2024-10-04 120524](https://github.com/user-attachments/assets/0c833841-09d0-4077-9131-b85162aea520)
Hope this helps bro

**Comment by 1smrt-cgardom** [comment]
I'm having a similar if not the same problem
