### ISSUE TITLE
[Request] Option to set the amount of time "toast notification with preview" appears

### ISSUE THREAD

**Issue by Andrefpvs** [ShareX/ShareX#4667]
I love being able to see the preview for a screenshot I just took, it's one of my favourite features. However, in my opinion the preview lingers for too long, and this can affect screenshots taken in quick succession.

Would it be possible to add an option that allows us to customize the amount of time that the preview stays on the screen?

As a bonus request, maybe an option to set the size of the preview as well?

Thank you!

**Comment by Jaex** [comment]
Both option already exists:

![](https://jaex.getsharex.com/2020/03/ShareX_HZkicpRp1B.png)

**Comment by Andrefpvs** [comment]
My bad!

Thank you!
