### ISSUE TITLE
Add delete button in screenshot preview

### ISSUE THREAD

**Issue by xmha97** [ShareX/ShareX#4668]
Hello, Please add below feature:
- Add delete button in screenshot preview
![image](https://user-images.githubusercontent.com/23485114/76553879-13f0fd80-64aa-11ea-88bc-8204cfd4e851.png)

**Comment by worldsdream** [comment]
I like this feature 👍

**Comment by worldsdream** [comment]
You can right click on the picture and it will hide. It’s better than a delete text.

**Comment by worldsdream** [comment]
@Jaex you can close this if you like. As I said, right clicking the notificaiton will hide. It’s much better than a delete button.

**Comment by xmha97** [comment]
OK, thanks.
