### ISSUE TITLE
In editor, arrow keys should reposition elements, not resize them

### ISSUE THREAD

**Issue by RadGH** [ShareX/ShareX#4669]
Sometimes when trying to place lines or boxes in the editor I would like to use arrow keys to get pixel-perfect alignment. Strangely, that resizing elements instead. I run into this often and am always just a little bit annoyed, it just doesn't make any sense that it would resize the element.

Here is a video I ran into easily, where **my mouse could not achieve pixel-perfect accuracy** and so I attempted to move an element. Instead, it stretched it downwards.

https://radleysustaire.com/s3/bf5d7d/chrome

In that situation I eventually realized I could resizing it the opposite direction to finally fix the 1px gap that I was trying to cover up.

Arrow keys move the pointer when taking a screenshot, so I am not sure why those controls should change after you take the screenshot and enter the editor.

**EDIT:** It looks like you can actually hold CTRL to move elements! I'll use that. Still I think it's worth considering swapping that around. It seems backwards, CTRL should resize the element don't you think?

**Comment by worldsdream** [comment]
@RadGH I didn't know that we can hold CTRL and use the arrows. Thanks for the tip!

**Comment by Jaex** [comment]
I hope people won't request previous keybind back.
