### ISSUE TITLE
"Application settings" not redrawn when deselecting "Apply custom theme to all windows"

### ISSUE THREAD

**Issue by sorashadow** [ShareX/ShareX#4670]
Just a cosmetic issue: I don't know if it's a limitation of the platform, but deselecting checkbox "Apply custom theme to all windows" doesn't automatically redraw the "Application settings..." window. You have to close and open it again so it can be redrawn.

Before applying custom theme:
![image](https://user-images.githubusercontent.com/5746442/76623950-23f0f780-6513-11ea-9d51-44f8e5008b37.png)

After applying custom theme:
![image](https://user-images.githubusercontent.com/5746442/76624215-a4175d00-6513-11ea-83f2-cc853bbcafb2.png)

After deselecting "Apply custom theme to all windows":
![image](https://user-images.githubusercontent.com/5746442/76624237-b42f3c80-6513-11ea-80a6-7ce7d46a10d7.png)

After reopening "Application settings...":
![image](https://user-images.githubusercontent.com/5746442/76624302-cad59380-6513-11ea-94e4-601a1f6688ce.png)

**Comment by Jaex** [comment]
It is intentional because there is no code to apply default system colors. It just not applies custom colors so system colors remains as it is.
