### ISSUE TITLE
How to disable the recent tasks?

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#4671]
See screenshot: https://i.imgur.com/d9fyUTw.png

How are we able to disable the recent tasks? 
We are able to disable the image history, but so far I see not the recent tasks. Why?
Can there be a setting option to disable recent tasks. This is for privacy reasons.

**Comment by Jaex** [comment]
This?

![](https://jaex.getsharex.com/2020/03/ShareX_7L4fcpYE74.png)

**Comment by worldsdream** [comment]
That's what I thought, I did uncheck it but it still is showing. I have shareX installed on 2 machines. Both are having this issue.

https://i.imgur.com/zoOAGDc.png

**Comment by Ares9323** [comment]
I can confirm it doesn't work on my 2 devices too!
I disabled all checkboxes but tasks continue to appear:
![image](https://user-images.githubusercontent.com/46932745/77014654-199b8700-6973-11ea-8ee3-bb38027c2876.png)

**Comment by worldsdream** [comment]
Thanks @Ares9323. I hope that @Jaex can reproduce and fix this.

**Comment by Jaex** [comment]
That option makes sure to not save recent tasks when you re open ShareX. You can't disable tasks showing for active instance.

**Comment by Ares9323** [comment]
If I kill the process and reopen it history is cleared, I didn't know I couldn't disable the current instance's tasks.
I think it's useful if you save every screenshot you take, but in my case (as you can see from my screenshot) history is just full of dead links with random names, i'd rather see the default page "Currently configured hotkeys"

I tried to fork and solve it by myself but I totally could not understand where to look for 😅

**Comment by Ares9323** [comment]
The simplest solution I found is to add "Clear task list" to the "After capture tasks", it's not very professional but it does the job and you don't need to rewrite existing code!

**Comment by Piepop101** [comment]
@Ares9323 How were you able to add the "Clear task list" to the "After capture tasks" if you don't mind me asking?

**Comment by Ares9323** [comment]
> @Ares9323 How were you able to add the "Clear task list" to the "After capture tasks" if you don't mind me asking?

It's very simple, I didn't 🤣
It was a suggestion to the developer in how to implement this function without changing the core of the software!

**Comment by koobs** [comment]
Request re-open please.

**Comment by Rubber-Duckie** [comment]
I would not trust this application what so ever. A history of screen shots remain resident in the system for any adversary to inspect, what in gods name is that about?  The checkbox not to store history means the user does NOT want to store history, not sure what part of that is so difficult to understand. Of course its not difficult, dev's have an agenda and its to keep your data around regardless of what you say as a user, to hell with that they say. Hmmm whats going on here, very very suspicious. 

Playing mind games with users in some twisted roundabout "well ye we store them for a secret reason when the app is running regardless of your indicated wishes, but make them disappear only when the application is restarted" is hugely concerning, casts a dark shadow on the intentions of these devs. What game to they think they are playing.

**Comment by bugproof** [comment]
> roundabout "well ye we store them for a secret reason when the app is running regardless of your indicated wishes, but make them disappear only when the application is restarted" is hugely concerning, casts a dark shadow on the intentions of these devs. What game do they think they are playing.

Exactly... The situation with not clearing the tasks is very annoying. It clearly still stores the screenshots in some undisclosed location on your disk or in memory. Any other screenshot tool you've decided to use?

**Comment by STIG-STIG** [comment]
Hi,
Can a HERO please make an emergency release of the app with @Ares9323 suggestion about adding the "Clear task list" to the "After capture tasks"???
I can compile the app with Visual Studio but I couldn't figure out how to add the "Clear task list" to the "After capture tasks."
I hope someone could help because I use this app to capture many images and this issue is very annoying for me!!!
Looking forward to your help.
Thank you so much for your attention...
Kind Regards,
Stig

**Comment by csavalas** [comment]
I love this program and have also wanted to see this feature for a while now. As a stopgap, I created a [fork of the repo](https://github.com/csavalas/ShareX) here with recent tasks and logging completely disabled. Feel free to build it yourself, or you can just copy the contents of the zip file in the root of the fork [ShareX-Mod](https://github.com/csavalas/ShareX/blob/develop/ShareX-Mod.zip) into your existing ShareX directory (`C:\Program Files\ShareX`). Only two slight changes were made to the following files:

`ShareX/ShareX/Program.cs`
`ShareX/ShareX/Forms/MainForm.cs`

**Comment by Rehaan13** [comment]
I guess another janky way to achieve this is to have the `After capture task > Perform action` run a batch file that kills ShareX and then re-starts it.

Batch file could be something like this:
`@echo
cls
taskkill /IM ShareX.exe /T /F
timeout /t 2 /nobreak
Start "" "C:\Program Files\ShareX\ShareX.exe"
exit`

**Comment by SpencerPatterson** [comment]
Will this ever be fixed?  This is definitely a bug if the box that says "saves tasks to history" is unchecked yet it still saves the tasks to history.

**Comment by Yoongbo** [comment]
What's the point of the task list there? All items in the right-click menu is grayed out.

**Comment by samerop** [comment]
+1

**Comment by Pamlau** [comment]
+1 I spent like 30 mins  trying to find the option to stop showing image history and only show the hotkey actions screen just to find out it doesn't even exist

**Comment by DonMatron** [comment]
The problem  is still present and it's a counter-intuitive behavior. Why was this issue closed?

**Comment by SpencerPatterson** [comment]
Still a security issue. I have to run a task to auto clear it every day because of this.

**Comment by csavalas** [comment]
> I love this program and have also wanted to see this feature for a while now. As a stopgap, I created a [fork of the repo](https://github.com/csavalas/ShareX) here with recent tasks and logging completely disabled. Feel free to build it yourself, or you can just copy the contents of the zip file in the root of the fork [ShareX-Mod](https://github.com/csavalas/ShareX/blob/develop/ShareX-Mod.zip) into your existing ShareX directory (`C:\Program Files\ShareX`). Minor changes were made to the following files:
> 
> `ShareX/ShareX/Forms/MainForm.cs` `ShareX/ShareX/Forms/MainForm.Designer.cs`

My solution here should still work

**Comment by rthfhgyhy567** [comment]
So do the tasks automatically clear themself (if the captures were deleted) after a reboot?  If not this would add a lot of random clutter to my computer over time with all these tasks for captures that no longer exist.  

I don't like the idea of "tasks", as I have all my captures set to save to my desktop for quick access

**Comment by BrycensRanch** [comment]
> So do the tasks automatically clear themself (if the captures were deleted) after a reboot? If not this would add a lot of random clutter to my computer over time with all these tasks for captures that no longer exist.
> 
> I don't like the idea of "tasks", as I have all my captures set to save to my desktop for quick access

It's not random clutter. It's all in your `ApplicationConfig.json`.  All recent tasks are objects that track the most recent tasks, which may include failed uploads.

**Comment by Indy2l** [comment]
Still waiting for this btw

**Comment by argothiel** [comment]
The issue still occurs, please reopen.

**Comment by ghost** [comment]
Same here, please reopen. This is a massive privacy issue if more than one person uses your computer. Switching to another software is the only solution for now.

**Comment by Neppkun** [comment]
> Same here, please reopen. This is a massive privacy issue if more than one person uses your computer. Switching to another software is the only solution for now.

this is exactly why your computer has the capability to create different users. And if you're worried about the aforementioned people breaking out of their own account just to see YOUR screenshots, maybe re-consider who you let around your computer.

**Comment by ghost** [comment]
> this is exactly why your computer has the capability to create different users. And if you're worried about the aforementioned people breaking out of their own account just to see YOUR screenshots, maybe re-consider who you let around your computer.

Flameshot it is then. So long and thanks for all the fish! I've dealt with enough rude developer ego in my lifetime.

**Comment by Neppkun** [comment]
> > this is exactly why your computer has the capability to create different users. And if you're worried about the aforementioned people breaking out of their own account just to see YOUR screenshots, maybe re-consider who you let around your computer.
> 
> Flameshot it is then. So long and thanks for all the fish! I've dealt with enough rude developer ego in my lifetime.

I haven't contributed a single line of code to ShareX. I'm just not stupid enough to take screenshots that would warrant privacy concerns on a shared machine. If you REALLY want this feature, ask Claude to implement it for you and make a PR, lol.

**Comment by argothiel** [comment]
Just want to mention that multiple people using one computer is not the only scenario where this would be useful. There are also people just being around a computer and potentially looking at it. Which you can fully trust using privacy-respecting apps, but it becomes a problem when the apps don't fully allow to configure their privacy settings.

And then there's me, who is just embarrassed by the number and quality of stuff I screenshot for the entire time my computer is running and would happily not have to look at this history every time I open the app.

My current workaround is to use an AutoHotkey script which runs the ShareX screenshot command and exits the program immediately when it's done, but it's more messy than it should be.

I'll happily implement a fix, but would like some direction from the developer: should we go with the "clear task list" post-capture action, or should it just be a separate setting?
