### ISSUE TITLE
[BUG]Tray icon double left click image editor

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#4672]
I have the following settings configured: https://i.imgur.com/nUSAwqq.png
When I double left click on the tray icon, the image editor shows up, BUT also the capture region.

Can you fix that bug?

When double clicking the tray icon, it should only show the image editor. Thank you.

**Comment by Jaex** [comment]
Can you test the fix using dev build? https://getsharex.com/docs/dev-builds

**Comment by worldsdream** [comment]
It’s fixed with the dev build. Great job.
