### ISSUE TITLE
ShareX caused Blue Screen, Windows 7 Pro, SP1

### ISSUE THREAD

**Issue by SeminVsevolod** [ShareX/ShareX#4678]
Hello. Today ShareX caused windows blue screen. ShareX wasn't open, it had been running in the system tray. I think that last build ShareX 13.1 (Release) has some errors.

Info from log file (I have russian localization of Windows, but I think that you will understand, what's the problem):
2020-03-15 15:21:07.438 - ShareX starting.
2020-03-15 15:21:07.478 - Version: 13.1
2020-03-15 15:21:07.478 - Build: Release
2020-03-15 15:21:07.478 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2020-03-15 15:21:07.478 - Personal path: C:\Users\Vsevolod\Documents\ShareX
2020-03-15 15:21:07.478 - Operating system: Windows 7 Professional (64-bit)
2020-03-15 15:21:07.488 - Running as elevated process: True
2020-03-15 15:21:07.488 - Flags: SilentRun
2020-03-15 15:21:07.548 - ApplicationConfig load started: C:\Users\Vsevolod\Documents\ShareX\ApplicationConfig.json
2020-03-15 15:21:09.467 - ApplicationConfig load failed: C:\Users\Vsevolod\Documents\ShareX\ApplicationConfig.json:
System.BadImageFormatException: Не удалось загрузить файл или сборку "ShareX.ScreenCaptureLib, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Ожидалось, что модуль содержит манифест сборки.
Имя файла: 'ShareX.ScreenCaptureLib, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null'
   в ShareX.TaskSettingsCapture..ctor()
   в ShareX.TaskSettings..ctor()
   в ShareX.ApplicationConfig..ctor()
   в CreateShareX.ApplicationConfig()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   в ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

2020-03-15 15:21:09.476 - ApplicationConfig load started: C:\Users\Vsevolod\Documents\ShareX\Backup\ApplicationConfig.json
2020-03-15 15:21:09.483 - ApplicationConfig load failed: C:\Users\Vsevolod\Documents\ShareX\Backup\ApplicationConfig.json:
System.BadImageFormatException: Не удалось загрузить файл или сборку "ShareX.ScreenCaptureLib, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Ожидалось, что модуль содержит манифест сборки.
Имя файла: 'ShareX.ScreenCaptureLib, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null'
   в ShareX.TaskSettingsCapture..ctor()
   в ShareX.TaskSettings..ctor()
   в ShareX.ApplicationConfig..ctor()
   в CreateShareX.ApplicationConfig()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   в ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

2020-03-15 15:21:09.483 - Loading new ApplicationConfig instance.
2020-03-15 15:21:11.489 - Unhandled exception:
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> System.BadImageFormatException: Не удалось загрузить файл или сборку "ShareX.ScreenCaptureLib, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Ожидалось, что модуль содержит манифест сборки.
   в ShareX.TaskSettingsCapture..ctor()
   в ShareX.TaskSettings..ctor()
   в ShareX.ApplicationConfig..ctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   в System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.Activator.CreateInstance[T]()
   в ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
   в ShareX.HelpersLib.SettingsBase`1.Load(String filePath, String backupFolder, Boolean createBackup, Boolean createWeeklyBackup)
   в ShareX.SettingManager.LoadApplicationConfig()
   в ShareX.SettingManager.LoadInitialSettings()
   в ShareX.Program.Run()
   в ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
2020-03-15 15:21:24.714 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-03-15 15:25:42.593 - File opened: C:\Users\Vsevolod\Documents\ShareX\Logs\ShareX-Log-2020-03.txt

**Comment by SeminVsevolod** [comment]
Maybe this problem is related with this issue -> [https://github.com/ShareX/ShareX/issues/1615](https://github.com/ShareX/ShareX/issues/1615)

**Comment by Jaex** [comment]
How you can be sure that ShareX caused the blue screen?

**Comment by SeminVsevolod** [comment]
Really I am not sure :) ShareX itself prompted me think so.
Because when system restarted after blue screen the first thing that I saw was a window from ShareX with this error:
![ShareX - Error](https://user-images.githubusercontent.com/35951053/76705930-eb107880-66f4-11ea-97b2-226018ece95f.jpg)

**Comment by Jaex** [comment]
Because your blue screen corrupted library of ShareX. You must reinstall ShareX.
