### ISSUE TITLE
[Feature Request] Allow GIF / PNG destination settings

### ISSUE THREAD

**Issue by Patrity** [ShareX/ShareX#4680]
Imgur is a great place to upload PNG's but due to file size limits, it's nearly unusable for GIF's

In the destination settings, could you allow users to specify GIFs going to one location and PNGs to another?

Thanks

**Comment by Jaex** [comment]
Yes:

![](https://jaex.getsharex.com/2020/03/ShareX_w8Wb5eOqk9.png)
