### ISSUE TITLE
Conflict with "Open image editor" and "Copy to clipboard" after capture

### ISSUE THREAD

**Issue by Ares9323** [ShareX/ShareX#4684]
Hi, I've installed ShareX few hours ago and I find it insanely useful!
I have selected after capture **"Open image editor"** and **"Copy image to clipboard**" but if I close the editor windows nothing is copied in my clipboard. I have to click on the copy button or the shortcut **Ctrl + Shift + C**.

![image](https://user-images.githubusercontent.com/46932745/77009576-6ded3980-6968-11ea-9cac-ba16f482dfa8.png)

For me it would be enough to switch the keybindings from **Ctrl + Shift + C** to **Ctrl + C**, and I've seen several issues asking for this, because I guess that "Copy position and size info" is far less used than copying the image (please consider this solution 😊)

The **"Copy to clipboard"** function works fine if launched alone, maybe another solution could be to launch it before opening the editor?
This could allow simply to close the editor and keep the original screenshot, or click the copy tool again and overwrite the image in the picture.

Thanks for your work, it's really great!

**Comment by andreasozzi** [comment]
Hey man! You know you're right! I was trying this beautiful and very complete software for the first time, but there was something wrong. Now that you make me wonder about it, if they accepted this motif it would become the perfect final software!

**Comment by zer0xs** [comment]
Can confirm, am having this issue. Please have the software **first** copy to clipboard, then open in the editor

**Comment by popstas** [comment]
@Ares9323, thank you for Ctrl+Shift+C! How did you find this shortcut? It absents on copy button title.
