### ISSUE TITLE
Do not show mainwinodow on start ?

### ISSUE THREAD

**Issue by daslicht** [ShareX/ShareX#4686]
Hi,
is there a way to NOT show the main window on each start please?
Is that the wrong place to ask , i apologize where wouldbe the correct place to ask ?
Cheers

**Comment by Jaex** [comment]
This option?

![](https://jaex.getsharex.com/2020/03/ShareX_PjoahoKCtK.png)

**Comment by daslicht** [comment]
I have enabled that but the main window still keeps open?
