### ISSUE TITLE
Feature request: Support for video watermarks and Screen recorder annotation tools

### ISSUE THREAD

**Issue by SalihPalamut** [ShareX/ShareX#4691]
## Hi I Added 2 features for Sharex.
So I want you to adding next release version.
best regards.
## Watermark logo support is added
![](https://raw.githubusercontent.com/SalihPalamut/ShareX/master/Imgs/watermark.png)

## Screen recorder annotation tools menu is added
![](https://github.com/SalihPalamut/ShareX/blob/master/Imgs/watermark.gif?raw=true)

https://github.com/SalihPalamut/ShareX

**Comment by vatterspun** [comment]
> Can you add this features

Maybe rename the issue subject something like "Feature request: Support for video watermarks"?

**Comment by BasketballBuzz** [comment]
Can we please have this feature integrated into ShareX. The ability to watermark captured videos is a must-have.
Look forward to having the ability to use this feature inside this fantastic software.
Thanks again and keep-up the good work.

**Comment by eqan** [comment]
This feature has still not been added!
