### ISSUE TITLE
Difference between "gdi grab" and "screen-capture-recorder"

### ISSUE THREAD

**Issue by ZaneCEO** [ShareX/ShareX#4692]
Hi guys, this is not really an issue, just a question. What's the difference between the two recording mode? Is one better than the other?

Thanks!

**Comment by ZaneCEO** [comment]
stale-bot go away, I'm still interesting in this.

**Comment by rudolphos** [comment]
Same question. Which is better for capturing graphics?

**Comment by ZaneCEO** [comment]
thanks @rudolphos for your reply. But that seems outdated: as you can see, you can record audio with GDI:

![zShot_1602321533](https://user-images.githubusercontent.com/5873880/95651451-c6457d80-0aea-11eb-8a14-4ba80487af38.png)

From your post I understand that GDI uses ffmpeg and screen-capture-recorder uses a DirectShow filter. Still: what are the pros and cons of each?

**Comment by billbalm** [comment]
@ZaneCEO,

GDI and DirectShow are two different APIs from Microsoft, both capable of, among many other things, screen capture.

See:
https://docs.microsoft.com/en-us/windows/win32/gdi/windows-gdi
https://docs.microsoft.com/en-us/windows/win32/directshow/directshow

https://en.wikipedia.org/wiki/DirectShow

From what I read, GDI doesn't do it at hardware level, while DirectShow (not 100% sure here) seems to.

My guess is that with screen-capture-recorder you'd get a little bit more performance on screen recording. But that's just an educated guess.

By the way, DirectShow is being replaced by Microsoft, in my opinion probably over media content copyright concerns from Hollywood.

**Comment by ZaneCEO** [comment]
@billbalm Looking good, thanks!

**Comment by gamelaster** [comment]
I don't think this is accurate.
GDI have API for capturing the screen, that's correct. But, with DirectShow, there is one catch.
For getting DirectShow video capturing working, is by installing this app https://github.com/rdp/screen-capture-recorder-to-video-windows-free/ . This app creates DirectShow filters for recording video and audio. At video side, this plugin uses GDI to capture image ([proof](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/blob/master/source_code/PushSourceDesktop.cpp#L454), [StretchBlt ](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-stretchblt) is WinGDI function). So thus, difference between GDI and DirectShow is none, both use GDI under the hood.

**Comment by sulisu** [comment]
If you start recording the screen and leave the computer alone, GDI is fine, it is faster than screen-capture-recorder.

But, if you keep using the computer and trigger the user priviliege screen, the captured video will be frozen, only audio continue and ShareX will not throw an alert.

Using screen-capture-recorder can solve this problem.

**Comment by gamelaster** [comment]
@sulisu very good point! Although, when you run the GDI capturing process as administrator, isn't able to capture user privilege screen too ? Also, isn't this all about the implementation of screen capture software? Thus you can handle the scenarios with user privilege screen.
