### ISSUE TITLE
How to get shareX to copy original GIF link in Imgur

### ISSUE THREAD

**Issue by JerryGoyal** [ShareX/ShareX#4693]
ShareX gives me the direct link but how can I configure shareX to copy original GIF link instead?

![image](https://user-images.githubusercontent.com/7106086/77227017-c14acc00-6ba2-11ea-93ce-028f0038dae4.png)

There was one old similar issue https://github.com/ShareX/ShareX/issues/2993 but that didn't solve the issue of copying **original GIF link**

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/03/ShareX_mSYAFSh32r.png)
