### ISSUE TITLE
Lighter icons against darker theme

### ISSUE THREAD

**Issue by jwoodard80** [ShareX/ShareX#4694]
Forgive if this is answered somewhere else but I didn't notice it. 

I love the dark theme....until recently. I would like to just know if these icons can be adjusted when dark to stand out a bit more. If this is a setting I'm missing i'd love to know as well. 

Thank you!

![Screenshot_03_23_2020__01 03 42 42 PM](https://user-images.githubusercontent.com/10240627/77348984-561b0a00-6d08-11ea-8a50-2c074ba54bed.jpg)
it comes to editing a screen capture

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/03/ShareX_sCReIgFY6w.png)

**Comment by Jaex** [comment]
Now icons become little inconsistent because previously all icons were blue now it is half blue, half white.
