### ISSUE TITLE
Gif recording missing frames

### ISSUE THREAD

**Issue by KevinClaytonGustafson** [ShareX/ShareX#4695]
Recording gif seems to miss frames and seems to freeze and/or it stops recording before the end.

{test] I am recording this and typing the whole time to show the missing frames.

Example:
![2020-03-23_15-51-41](https://user-images.githubusercontent.com/41588917/77357244-355daf00-6d1e-11ea-9ba3-111e085589a4.gif)

**Comment by Jaex** [comment]
Try updating FFmpeg like this:

![](https://jaex.getsharex.com/2020/03/explorer_igDfy6fnSr.png)

**Comment by KevinClaytonGustafson** [comment]
I just checked and that worked. Thanks for the heads up!
