### ISSUE TITLE
Chunk uploading large images

### ISSUE THREAD

**Issue by DusterTheFirst** [ShareX/ShareX#4696]
Is there any way currently to upload large files in chunks to a custom uploader as to bypass upload limits on Cloudflare?

**Comment by Jaex** [comment]
No.

**Comment by DusterTheFirst** [comment]
Any plans to add such?

**Comment by Jaex** [comment]
No.

**Comment by camjac251** [comment]
Are the reasons available to read? This would allow for resumable uploads in addition to saturating a connection upload speed

https://en.wikipedia.org/wiki/Chunked_transfer_encoding
