### ISSUE TITLE
No ToastWindow after copying image to clipboard

### ISSUE THREAD

**Issue by n3rdc0r3** [ShareX/ShareX#4698]
Issue probably related to: [https://github.com/ShareX/ShareX/issues/1530](url) (require saving to file to show ToastWindow)

My configuration:
- Task settings > General > After task is completed: Show toast notification with preview
- Task settings > Advanced > ToastWindowDuration 3
- Task settings > Advanced > ToastWindowFadeDuration 0
- Task settings > Advanced > ToastWindowPlacement TopCenter
- Task settings > Advanced > ToastWindowClickAction Annotate image
- Task settings > Advanced > ToastWindowRightClickAction Close notification
- Task settings > Advanced > ToastWindowMiddleClickAction Close notification
- Task settings > Advanced > ToastWindowSize 500, 375
- After capture tasks > Copy image to clipboard (everything else like Save image to file etc. is disabled)

Is there any chance that you could look into this? Thanks!

**Comment by xaminmo** [comment]
Toast windows require converting the screenshot, which means sending it to disk.  To keep it from cluttering up your drive with images you don't want, go into the right-click menu, then "After Capture Tasks" context menu, choose the very last option, "Delete file locally".  You will never see the file end up in the image snapshot folder, and it is pretty easy to reverse if you change your mind later.  I just confirmed that this still shows a toast thumbnail version, and the file does not get saved to the screenshot directory.
