### ISSUE TITLE
Disable update notifications until next version

### ISSUE THREAD

**Issue by paarthenon** [ShareX/ShareX#4700]
I enjoy the program but I find it irritating that ShareX will ask me to update multiple times and the only option I have is "Do not prompt again until ShareX starts next time". I'd like to be able to say "Do not prompt again for this version". Is this something you're open to implementing or would accept PRs for?

![image](https://user-images.githubusercontent.com/10353928/77443183-48758b00-6dc1-11ea-983f-d34aaae5aa94.png)

p.s. I do see that I can disable updates in the advanced app settings. I'd still like to have the info, just less often (or perhaps in a less obtrusive way). A remind me later or having it as an alert in the menus rather than a window would also improve the situation.

**Comment by paarthenon** [comment]
Bumping to cancel "Stale"

**Comment by paarthenon** [comment]
Once again bumping to cancel stale. Are these issues watched by anyone? Is there somewhere else I should be posting?

**Comment by dotjairo** [comment]
Yes, In my opinion, disabling this notification would greatly improve the user experience.

**Comment by paarthenon** [comment]
Me too. Unfortunately it looks like the developers do not care about this issue, or at least haven't bothered to acknowledge it for a year and a half. I wouldn't hold your breath.
