### ISSUE TITLE
Feature Request: Add a hotkey to slow the cursor down for precise region selection

### ISSUE THREAD

**Issue by Keagel** [ShareX/ShareX#4704]
And maybe a setting to increase the size of the zoomed-in preview?

![preview](https://user-images.githubusercontent.com/18720666/77756652-ea9aaa80-702f-11ea-8d22-21d0cc39b5bf.png)

**Comment by Benjaminhu** [comment]
"Add a hotkey to slow the cursor down for precise region selection" +1

@Keagel use mouse wheel!

**Comment by Keagel** [comment]
@Benjaminhu thanks for the tip, didn't know you could zoom with the mouse wheel.
