### ISSUE TITLE
Black images

### ISSUE THREAD

**Issue by nickodemos** [ShareX/ShareX#4705]
When using Video Thumbnailer on this updated version all I get is one single black image when saving files. No settings changed after update. ffmpeg is installed.

Took steps and uninstalled, deleted all reference to program, the file and then downloaded from webpage and installed. Same issue.

Here is an image when I had upload images set. 
![ShareX_vJsX78MdOq](https://user-images.githubusercontent.com/17693113/77783755-c939be80-702f-11ea-987a-52a459218fe4.png)

**Comment by fasetto** [comment]
I am having this issue.
ShareX version: 13.1 & it says up to date.

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds

**Comment by fasetto** [comment]
@Jaex I don't know if my issue is different from this but in my _ShareX_ it looks like this.
Yesterday I installed dev build like you said. Thats weird. 🤔 

![image](https://user-images.githubusercontent.com/20834021/81067158-e727f800-8ee6-11ea-8b02-20086118d9e1.png)
