### ISSUE TITLE
Feature Request: Add option to have Screen Recording (No Audio)

### ISSUE THREAD

**Issue by ZLoth** [ShareX/ShareX#4706]
One of the key features of ShareX that I love is that screen recording to a MP4 file. By default, the settings allow for the recording of audio while making the MP4 audio. This can be fixed by going into Task Settings → Capture → Screen Recorder → Screen Recorder Options → Audio Source: None, but involves a number of steps. It would be good if there was two options:

- Screen Recording (with Audio)
- Screen Recording (no Audio)

**Comment by Scrxtchy** [comment]
This can be accomplished with the current version by utilising workflows
Workflows offer capture/tool functions to be executed with an alternate set of options.
By overriding the capture settings, you can disable/enable the audio of the screen recording

![image](https://user-images.githubusercontent.com/12771982/77851172-3f524700-7223-11ea-9678-483bb7a384a7.png)

A hotkey is optional, you can still find all of your configured workflows from both the sharex main window and the taskbar
