### ISSUE TITLE
Sharex settings

### ISSUE THREAD

**Issue by ken-colvin** [ShareX/ShareX#4709]
- I seem to loose all my sharex settings on every upgrade of sharex
- I have to config my hot keys, do not show mouse cursor,  and after capture settings every time there is a sharex update
- current version of sharex is 13.1

**Comment by marknorrapscm** [comment]
Also on 13.1 and just noticed my settings are gone. The following have been lost:

- Hotkey settings and preferences
- Default image host and image host authorisation

**Comment by Braunson** [comment]
Also having this issue.. hotkeys, customer upload endpoints (FTP) all missing. I can see the file still has my info and hotkeys in `Documents\ShareX` but the app isn't reading them..

**Comment by JakeSteam** [comment]
@Braunson Thanks for the guide, I used a slightly easier method you might prefer:

1. Close ShareX.
2. Look in `...Documents\ShareX\Backup\`
3. Find the `ApplicationConfig.json`, `History.json`, `HotkeysConfig.json`, and `UploadersConfig.json` from just before you updated.
4. Put them into the main `ShareX` directory, and rename them to remove the date.
5. Start ShareX, all your settings should be back :)

**Comment by Braunson** [comment]
@JakeSteam Great to hear, I did try excluding the date and it reverted back to the newer settings. Thanks for posting this easier method!
