### ISSUE TITLE
FTP upload issue

### ISSUE THREAD

**Issue by beny9512** [ShareX/ShareX#471]
Hello,

I'm trying to upload my pictures to FTP server, and it always say error. The username and password are correct, I can connect manually from my FTP client, FileZilla.

System.TimeoutException: Timed out trying to read data from the socket stream!
   a következő helyen: System.Net.FtpClient.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   a következő helyen: System.Net.FtpClient.FtpSocketStream.ReadLine(Encoding encoding)
   a következő helyen: System.Net.FtpClient.FtpClient.GetReply()
   a következő helyen: System.Net.FtpClient.FtpClient.Execute(String command)
   a következő helyen: System.Net.FtpClient.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   a következő helyen: System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   a következő helyen: System.Net.FtpClient.FtpClient.GetListing(String path, FtpListOption options)
   a következő helyen: ShareX.UploadersLib.FTPClientForm.LoadDirectory(String path)
   a következő helyen: System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   a következő helyen: System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   a következő helyen: System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   a következő helyen: System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   a következő helyen: System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   a következő helyen: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   a következő helyen: System.Windows.Forms.Control.WndProc(Message& m)
   a következő helyen: System.Windows.Forms.ToolStrip.WndProc(Message& m)
   a következő helyen: System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   a következő helyen: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jaex** [comment]
Did you tried changing "IsActive" ?

**Comment by beny9512** [comment]
Oh, yes. That was the problem. Thank you very much, Jaex! You saved the day! :)
