### ISSUE TITLE
Unable to record with Share X v 13.1.0

### ISSUE THREAD

**Issue by kalinoir** [ShareX/ShareX#4714]
I have some problem with recording.
The Windows record do not start and send me this prompt message:

> ffmpeg version N-92086-gd702769213 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180813
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 31.102 / 58. 31.102
  libavformat    58. 18.103 / 58. 18.103
  libavdevice    58.  4.105 / 58.  4.105
  libavfilter     7. 33.100 /  7. 33.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[gdigrab @ 0000016041bec380] Capturing whole desktop as 1920x1016x32 at (0,23)
[gdigrab @ 0000016041bec380] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1585584595.935320, bitrate: 1872704 kb/s
    Stream #0:0: Video: bmp, bgra, 1920x1016, 1872704 kb/s, 30 fps, 1000k tbr, 1000k tbn, 1000k tbc
[dshow @ 0000016041bf0240] Could not find audio only device with name [Missaggio stereo (Realtek High Definition Audio)] among source devices of type audio.
[dshow @ 0000016041bf0240] Searching for audio device within video devices for Missaggio stereo (Realtek High Definition Audio)
[dshow @ 0000016041bf0240] Could not find audio only device with name [Missaggio stereo (Realtek High Definition Audio)] among source devices of type video.
audio=Missaggio stereo (Realtek High Definition Audio): I/O error

> 

Anyone have this problem?

Thank you . 
Hope anyone help me ! _^_

**Comment by zcraber** [comment]
I'm having the same issue on Sharex 13.4.
Here is the message:
```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[gdigrab @ 000002682cdbeac0] Capturing whole desktop as 1366x768x32 at (0,0)
[gdigrab @ 000002682cdbeac0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1619295650.148216, bitrate: 1007137 kb/s
    Stream #0:0: Video: bmp, bgra, 1366x768, 1007137 kb/s, 30 fps, 1000k tbr, 1000k tbn, 1000k tbc
C:\Users\Zcraber's PC\Videos\57Af4rzqqh.mp4: No such file or directory
```
