### ISSUE TITLE
Google Reverse Image Search as an image upload service

### ISSUE THREAD

**Issue by pedrofracassi** [ShareX/ShareX#4715]
One of my main uses of ShareX is quickly looking up images with Google's Reverse Image Search. In the past, I've used a custom uploader I found in #1198, but it seems to have stopped working. Currenly, I've configured ShareX to upload the image to imgur, and then share the URL to google. That works, but includes unnecessary steps that slow the process down.

Google does let you to upload images directly through POST instead of passing the images as links by using `https://images.google.com/searchbyimage/upload`, the same endpoint used in http://images.google.com/.

Could you please make Google Reverse Image Search an image uploader, please?

**Comment by Nzzyme** [comment]
+1 for this. After so many years of development of this wonderful program, can't believe this feature is still not available out of the box.

@Jaex Can you please consider this? On the left navigation panel of the 'Destination Settings' window, we see many different headers like Image Uploaders, Text Uploaders, File Uploaders, URL Shortners, Other uploaders.

Can you also include one more section named 'Reverse Image Search' and under that provide the individual search services namely: 

Google Images
Bing Images
TinyEye
Yandex

Reverse Image Search is already available in atleast one of the other screenshot tools that I have used earlier (LightShot) so it should be possible to include it here too.

**Comment by BobanaterBob** [comment]
You can already do this.

Make a new hotkey, go to the settings and change them to this.

![lyBoNHNbHn](https://user-images.githubusercontent.com/42789693/81468783-b9c19f80-91af-11ea-8d08-9831a4cd1737.png)

**Comment by pedrofracassi** [comment]
Yup, as I stated in the first post, you can already do this, but it requires an extra step. That's why I'm proposing Google Image Search as an **image upload service**.

**Comment by Jaex** [comment]
> Reverse Image Search is already available in atleast one of the other screenshot tools that I have used earlier (LightShot) so it should be possible to include it here too.

It is already included long time ago and works same:

![](https://jaex.getsharex.com/2020/09/ShareX_7ufjfJnLYH.png)

**Comment by pedrofracassi** [comment]
> as I stated in the first post, you can already do this, but it requires an extra step. That's why I'm proposing Google Image Search as an **image upload service**.

I want to be able to just screenshot something and have the upload service be Google Image Search, so I don't have to open ShareX, right click the image and do that every time

**Comment by mreduar** [comment]
@pedrofracassi Did you succeed in doing it without having to enter the app each time?

**Comment by nightkall** [comment]
> @pedrofracassi Did you succeed in doing it without having to enter the app each time?

You can add a hotkey shortcut in 'Hotkey Settings'

[https://i.imgur.com/nKDBk5d.jpeg](https://i.imgur.com/nKDBk5d.jpeg)
![nKDBk5d 1](https://user-images.githubusercontent.com/20248397/174317134-855e3e26-2c66-4546-8d73-86987e2cf44c.jpeg)

**Comment by vanbang9710** [comment]
I encounter this bug when using Google image search. It only opens the google search page without uploading the image. The Bing search works fine though.
![|50pct](https://i.imgur.com/VficHOE.gif)

**Comment by Jaex** [comment]
> I encounter this bug when using Google image search. It only opens the google search page without uploading the image. The Bing search works fine though.

Looks like Google Image Search is deprecated and they are using Google Lens now. I updated the service to use Google Lens instead.

**Comment by ButaBrot** [comment]
> Looks like Google Image Search is deprecated and they are using Google Lens now. I updated the service to use Google Lens instead.
https://github.com/ShareX/ShareX/issues/4715#issuecomment-1594275677

I still have the same problem. Version is 15.0

**Comment by schmutly** [comment]
I have exactly the same issue. It was convenient in Lightshot to click the Google icon and it went to reverse image check but that stopped working a long time ago and the program seems abandoned.
Has anyone else got this to work when set up to use our own shortcut? The images and import JSON that's been presented doesn't seem to add the '/raw' on the end (understandably as it is looking for an image file and not an XBB page.)
Be wonderful to get this working. :)
