### ISSUE TITLE
Text capture (OCR) -- Can you improve the Line-breaking

### ISSUE THREAD

**Issue by amwihgu** [ShareX/ShareX#4717]
#4717 https://github.com/ShareX/ShareX/issues/3520#issue-340113908

Sorry for re-opening this existing issue -- it went ignored.
I am encountering this issue also:
Give the screen showing a very narrow article with 2 paragraghs.

> P1:Sentence1, setenc
> e2. Sentence3.
> 
> P2:Sentence1, setenc
> e2. Sentence3.

the OCR always gives me result of "Sentence2" breaked. However there are already very muture OCR engines providing the option to **ignore the line-break within paragraphs**.
Does OCR.space provide that? Could you kindly check please?

**Comment by Jaex** [comment]
> Does OCR.space provide that? Could you kindly check please?

No.

**Comment by vatterspun** [comment]
As a workaround, you can try using a program like CuteMarkEd that will auto-wrap anything that's not a double paragraph (basically pressing Enter twice)
