### ISSUE TITLE
Version with public Uploaders disabled by default

### ISSUE THREAD

**Issue by danielhamelberg** [ShareX/ShareX#4719]
For Enterprise compliance reasons, I want to suggest to build a version of Sharex with public and anonymous Uploaders disabled or removed by default. Please also share thoughts on other ways to accomplish this within the software itself or related configuration files.

**Comment by JohnS-BCS** [comment]
I agree

**Comment by danielhamelberg** [comment]
Patiently awaiting the dev's response here.

**Comment by Jaex** [comment]
There is no plan.

**Comment by Jaex** [comment]
> Please also share thoughts on other ways to accomplish this within the software itself or related configuration files.

https://getsharex.com/docs/command-line-arguments#registry

`DisableUpload` registry setting can be used.

**Comment by LordShelmchen** [comment]
When will the anonymous image upload (to Imgur) finally be disabled by default? This is an enormous security risk!

Imgur support will never delete such Screenshots, it's impossible. Tried this several times....

**Comment by nodejsg** [comment]
PLZ Disable Upload Entirely by default, both install version and portable version. Portable version does not disable it by default.
There is a NO UPLOAD version. https://github.com/Cosebdd/ShareNot
