### ISSUE TITLE
Image Host Request (Postimage.org) [Enhancement Request] 

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#472]
http://postimage.org

**Comment by Jaex** [comment]
They don't have API.

**Comment by Scrxtchy** [comment]
These are one of those *fuck you* hosts
It's impossible to get a high quality version of the image even from parsing the output from sharex

Best I was able to do was simply return the webpage that handles various outputs of the uploaded image, which is given from the redirection url
```
{
  "Name": "postimage.org",
  "RequestType": "POST",
  "RequestURL": "http://postimage.org/index.php",
  "FileFormName": "upload[]",
  "Arguments": {},
  "ResponseType": "RedirectionURL",
  "RegexList": [],
  "URL": "",
  "ThumbnailURL": "",
  "DeletionURL": ""
}
```

**Comment by zeus-dx** [comment]
They do now!!

**Comment by Scrxtchy** [comment]
Couldn't find anything, process remains relatively the same

**Comment by zeus-dx** [comment]
You can get it from here:
postimage.org/settings.php?api=1
https://postimages.org/login/api

I got these links from their official Postimage Windows App.

**Comment by Scrxtchy** [comment]
An api key is almost useless without documentation unless you're volunteering to reverse engineer their desktop application

**Comment by zeus-dx** [comment]
oh i did not know.

**Comment by neu-ma-tic** [comment]
I dug into some source code for their plugins, and they lead to scripts that user JSON post requests. I've found the following to work :)
```json
{
  "Version": "13.6.1",
  "Name": "postimages.org",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://postimg.cc/json?q=a",
  "Body": "MultipartFormData",
  "Arguments": {
    "token": "61aa06d6116f7331ad7b2ba9c7fb707ec9b182e8",
    "upload_session": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "numfiles": "1",
    "gallery": null,
    "adult": null,
    "ui": null,
    "optsize": null,
    "upload_referer": "https://www.phpbb.com",
    "mode": null,
    "lang": null,
    "content": null,
    "forumurl": null
  },
  "FileFormName": "file",
  "URL": "$json:url$"
}
```
the token is from the script, and the session is a random generated string in the script

**Comment by erbanku** [comment]
@neu-ma-tic Thanks for sharing, it works for me too. But It will upload images anonymously, is there any way to upload under my own account? 

I know this may be impossible as they not providing APIs to do that, but I would be appreciated it if we can find a way to do that.

**Comment by neu-ma-tic** [comment]
> @neu-ma-tic Thanks for sharing, it works for me too. But It will upload images anonymously, is there any way to upload under my own account? 
> 
> I know this may be impossible as they not providing APIs to do that, but I would be appreciated it if we can find a way to do that.

I think you may be able to use a custom token, but I'll have to test

**Comment by RakoGames** [comment]
> I dug into some source code for their plugins, and they lead to scripts that user JSON post requests. I've found the following to work :)
> 
> ```json
> {
>   "Version": "13.6.1",
>   "Name": "postimages.org",
>   "DestinationType": "ImageUploader",
>   "RequestMethod": "POST",
>   "RequestURL": "https://postimg.cc/json?q=a",
>   "Body": "MultipartFormData",
>   "Arguments": {
>     "token": "61aa06d6116f7331ad7b2ba9c7fb707ec9b182e8",
>     "upload_session": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
>     "numfiles": "1",
>     "gallery": null,
>     "adult": null,
>     "ui": null,
>     "optsize": null,
>     "upload_referer": "https://www.phpbb.com",
>     "mode": null,
>     "lang": null,
>     "content": null,
>     "forumurl": null
>   },
>   "FileFormName": "file",
>   "URL": "$json:url$"
> }
> ```
> 
> the token is from the script, and the session is a random generated string in the script
> 
> * looking into it, it seems like the token doesn't change

Any example code of using it?

**Comment by botatooo** [comment]
> I dug into some source code for their plugins, and they lead to scripts that user JSON post requests. I've found the following to work :)
> 
> ```json
> {
>   "Version": "13.6.1",
>   "Name": "postimages.org",
>   "DestinationType": "ImageUploader",
>   "RequestMethod": "POST",
>   "RequestURL": "https://postimg.cc/json?q=a",
>   "Body": "MultipartFormData",
>   "Arguments": {
>     "token": "61aa06d6116f7331ad7b2ba9c7fb707ec9b182e8",
>     "upload_session": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
>     "numfiles": "1",
>     "gallery": null,
>     "adult": null,
>     "ui": null,
>     "optsize": null,
>     "upload_referer": "https://www.phpbb.com",
>     "mode": null,
>     "lang": null,
>     "content": null,
>     "forumurl": null
>   },
>   "FileFormName": "file",
>   "URL": "$json:url$"
> }
> ```
> 
> the token is from the script, and the session is a random generated string in the script
> 
>     * looking into it, it seems like the token doesn't change

I've played with this a little bit, and I've been able to reduce the content to a minimum
```json
{
  "Version": "13.6.1",
  "Name": "postimages.org",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://postimg.cc/json",
  "Body": "MultipartFormData",
  "Arguments": {
    "token": "61aa06d6116f7331ad7b2ba9c7fb707ec9b182e8",
    "upload_session": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "numfiles": "1",
    "upload_referer": "https://getsharex.com/",
  },
  "FileFormName": "file",
  "URL": "$json:url$"
}
```

**Comment by onanana** [comment]
can i get the direct link instead of basic url?

**Comment by Pharaoh2k** [comment]
I second that. Would really love to have a good free alternative to imgur which seem to block my ISP for several months already.

**Comment by MilanV01** [comment]
any updates on how to get a direct link one with https://i.postimg.cc instead of postimg.cc

**Comment by imageu98** [comment]
you can try imagesupload.xyz

**Comment by Antho-321** [comment]
Here is an example implementation in Python code: import requests
import sys
import json
from bs4 import BeautifulSoup

def upload_image(api_url, token, image_path, upload_session):
    try:
        with open(image_path, "rb") as image_file:
            files = {"file": image_file}
            data = {
                "token": token,
                "upload_session": upload_session,
                "numfiles": "1",
                "upload_referer": "https://www.phpbb.com"
            }
            
            response = requests.post(api_url, files=files, data=data, timeout=30)
            return response
    except requests.exceptions.RequestException as e:
        print(f"An error occurred during the request: {e}")
        return None
    except IOError as e:
        print(f"Error: Unable to read the image file. Please check if the file exists and you have permission to read it. Details: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        print(f"Exception type: {type(e).__name__}")
        return None

def get_direct_image_url(initial_url):
    try:
        response = requests.get(initial_url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        direct_url_input = soup.find('input', {'id': 'code_direct'})
        if direct_url_input:
            return direct_url_input['value']
        else:
            print("Couldn't find the direct image URL in the HTML.")
            return None
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the image page: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred while parsing the HTML: {e}")
        return None

def main():
    api_url = "https://postimg.cc/json?q=a"
    token = "61aa06d6116f7331ad7b2ba9c7fb707ec9b182e8"
    upload_session = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    image_path = r"C:\Users\Administrador\Downloads\IMG_20211102_142914.jpg"
    
    print("Attempting to upload image...")
    response = upload_image(api_url, token, image_path, upload_session)
    
    if response:
        print("Received response from server.")
        print(f"Status code: {response.status_code}")
        print("Headers:")
        for header, value in response.headers.items():
            print(f"  {header}: {value}")
        print("\nResponse content:")
        print(response.text)
        
        try:
            json_response = response.json()
            print("\nJSON response:")
            print(json.dumps(json_response, indent=2))
        except json.JSONDecodeError:
            print("The response content is not valid JSON.")
        
        if response.status_code == 200:
            print("\nImage uploaded successfully!")
            try:
                initial_url = json_response["url"]
                print("Initial Image URL:", initial_url)
                
                print("\nFetching direct image URL...")
                direct_url = get_direct_image_url(initial_url)
                if direct_url:
                    print("Direct Image URL:", direct_url)
                else:
                    print("Failed to retrieve the direct image URL.")
            except KeyError:
                print("Image URL not found in the response.")
        else:
            print(f"\nFailed to upload image. Status code: {response.status_code}")
    else:
        print("Failed to get a response from the server.")

if __name__ == "__main__":
    main()

**Comment by Aholicknight** [comment]
> I've played with this a little bit, and I've been able to reduce the content to a minimum

<img width="458" height="79" alt="Image" src="https://github.com/user-attachments/assets/aa616916-7f84-4afd-9112-52932288b902" />

@adntaha this works. Is there a way to get the Direct URL as the response instead?

**Comment by Moemen12** [comment]
I hope you find this useful ,


```

  const params = new URLSearchParams()
    params.append('key', apiKey || '')
    params.append('name', uniqueName)
    params.append('type', imageType)
    params.append('image', base64Data)
    params.append('o', '2b819584285c102318568238c7d4a4c7')
    params.append('m', '59c2ad4b46b0c1e12d5703302bff0120')
    params.append('version', '1.0.1')
    params.append('portable', '1')

  
    const response = await fetch('https://api.postimage.org/1/upload', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: params.toString(),
    })

```


u will get an xml response as follow

```
<?xml version="1.0" encoding="utf-8"?>
<data success="1" status="200">
        <image>
                <name>product_1757265818850_t7b74sdjr4d</name>
                <time>Sun, 07 Sep 2025 14:23:44 -0300</time>
                <type>jpg</type>
                <width>1059</width>
                <height>1280</height>
                <size>96557</size>
        </image>
        <links>
                <page>https://postimg.cc/KkbHYJhr</page>
                <edit>https://postimg.cc/KkbHYJhr/f7645c60</edit>
                <delete>https://postimg.cc/delete/2PhRMD6S/f7645c60</delete>
                <thumbnail>https://i.postimg.cc/KkbHYJhr/product-1757265818850-t7b74sdjr4d.jpg</thumbnail>
                <hotlink>https://i.postimg.cc/yd34vbf5/product-1757265818850-t7b74sdjr4d.jpg</hotlink>
        </links>
        <codes>
                <thumbnail_forum>[url=https://postimg.cc/KkbHYJhr][img]https://i.postimg.cc/KkbHYJhr/product-1757265818850-t7b74sdjr4d.jpg[/img][/url]</thumbnail_forum>
                <thumbnail_html>&lt;a href=&#039;https://postimg.cc/KkbHYJhr&#039; target=&#039;_blank&#039;&gt;&lt;img src=&#039;https://i.postimg.cc/KkbHYJhr/product-1757265818850-t7b74sdjr4d.jpg&#039; border=&#039;0&#039; alt=&#039;product-1757265818850-t7b74sdjr4d&#039;/&gt;&lt;/a&gt;</thumbnail_html>
                <hotlink_forum>[url=https://postimg.cc/KkbHYJhr][img]https://i.postimg.cc/yd34vbf5/product-1757265818850-t7b74sdjr4d.jpg[/img][/url]</hotlink_forum>
                <hotlink_html>&lt;a href=&#039;https://postimg.cc/KkbHYJhr&#039; target=&#039;_blank&#039;&gt;&lt;img src=&#039;https://i.postimg.cc/yd34vbf5/product-1757265818850-t7b74sdjr4d.jpg&#039; border=&#039;0&#039; alt=&#039;product-1757265818850-t7b74sdjr4d&#039;/&gt;</hotlink_html>
        </codes>
</data>
```

**Comment by Aholicknight** [comment]
> can i get the direct link instead of basic url?

@onanana were you ever able to fix this?

**Comment by samirxpikachuio** [comment]
# Unofficial Postimages API Guide (Node.js)

## Setup

1. Make an account and log in: https://postimages.org/login
2. Grab your API key from https://postimages.org/login/api
3. Create a gallery at https://postimg.cc/files, then grab the gallery ID from the URL (e.g. `postimg.cc/gallery/XXXXXXX` → the `XXXXXXX` part)

Keep both your API key and gallery ID out of your code — use env vars:

```bash
export POSTIMAGE_API_KEY=your_key_here
export POSTIMAGE_GALLERY=your_gallery_id
```

## Install

```bash
npm install axios fast-xml-parser
```

## Upload function

```js
import axios from "axios";
import { XMLParser } from "fast-xml-parser";
import fs from "fs/promises";

const defaultConfig = {
  apiKey: process.env.POSTIMAGE_API_KEY,
  gallery: process.env.POSTIMAGE_GALLERY,
};

const genName = (ext = "png") =>
  `img_${Math.random().toString(36).slice(2, 8)}.${ext}`;

const encodeForm = (obj) =>
  Object.entries(obj)
    .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`)
    .join("&");

async function urlToB64(url) {
  const res = await axios.get(url, { responseType: "arraybuffer" });
  return Buffer.from(res.data).toString("base64");
}

async function fileToB64(path) {
  const buf = await fs.readFile(path);
  return buf.toString("base64");
}

function buildReq(cfg, fileName, b64img) {
  const ext = fileName.split(".").pop() || "png";
  const name = fileName.split(".")[0] || genName(ext).split(".")[0];

  const form = {
    key: cfg.apiKey,
    gallery: cfg.gallery,
    o: "2b819584285c102318568238c7d4a4c7",
    m: "59c2ad4b46b0c1e12d5703302bff0120",
    version: "1.0.1",
    portable: "1",
    name,
    type: ext,
    image: b64img,
  };

  return {
    method: "POST",
    url: "https://api.postimage.org/1/upload",
    headers: { "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8" },
    data: encodeForm(form),
    responseType: "text",
  };
}

function parseRes(xml) {
  const parser = new XMLParser({ ignoreAttributes: false });
  const j = parser.parse(xml);
  const img = j.data?.image || {};
  const links = j.data?.links || {};

  return {
    name: img.name,
    size: img.size,
    type: img.type,
    dim: `${img.width}x${img.height}`,
    time: img.time,
    page: links.page,
    thumb: links.thumbnail,
    hotlink: links.hotlink,
    del: links.delete,
  };
}

async function uploadUrl(cfg = defaultConfig, url, fileName) {
  const b64 = await urlToB64(url);
  const name = fileName || genName(url.split(".").pop());
  const req = buildReq(cfg, name, b64);
  const res = await axios(req);
  return parseRes(res.data);
}

async function uploadBuffer(cfg = defaultConfig, input, fileName) {
  let b64;

  if (Buffer.isBuffer(input)) {
    b64 = input.toString("base64");
  } else if (typeof input === "string") {
    if (input.startsWith("data:")) {
      b64 = input.split(",")[1];
    } else if (/^[A-Za-z0-9+/=]+$/.test(input) && input.length > 100) {
      b64 = input;
    } else {
      b64 = await fileToB64(input);
    }
  } else {
    throw new Error("Input must be a file path, base64 string, or Buffer");
  }

  let ext = "png";
  if (fileName) ext = fileName.split(".").pop();
  const name = fileName || genName(ext);

  const req = buildReq(cfg, name, b64);
  const res = await axios(req);
  return parseRes(res.data);
}

export const postimage = {
  url: uploadUrl,
  buffer: uploadBuffer,
  config: defaultConfig,
};
```



The response is XML, parsed into something like this:

```json
{
  "data": {
    "image": { "name": "cat", "width": 512, "height": 512 },
    "links": {
      "page": "https://postimg.cc/...",
      "thumbnail": "https://i.postimg.cc/...",
      "hotlink": "https://i.postimg.cc/full-image.png",
      "delete": "https://postimg.cc/delete/..."
    }
  }
}
```
