### ISSUE TITLE
Store config files in online storage

### ISSUE THREAD

**Issue by user6323** [ShareX/ShareX#473]
Hi. I have enhancement request.
I use sharex on 3 pc. When i change settings, i have to copy settings manually to each client.
It would be convenient to save and get settings from online storage automatically, using same destination setting, as for uploaded images.

**Comment by Jaex** [comment]
It is not possible because without have destination settings you can't download your destination settings from destination.

**Comment by McoreD** [comment]
@user6323 you may use custom paths to mimick this desired behavior: 
http://i.imgur.com/Gf2NuPE.png
