### ISSUE TITLE
Setting CheckerSize theme option to 0 causes issues

### ISSUE THREAD

**Issue by dgasaway** [ShareX/ShareX#4732]
I was messing around with the theme options and set the CheckerSize to 0.  This caused a number of exceptions regarding an invalid property value.  I tried to set it back, but it didn't seem to take.  Eventually, ShareX crashed.  Then it wouldn't launch - it would get an exception on start and crash.  I managed to track the setting down in the JSON file and set it back to 15.  Then the program would launch again.

**Comment by Jaex** [comment]
I think if checker size is 0 then using solid color for background would be good idea, that way you can disable checker background too.
