### ISSUE TITLE
Option to disable walking ants animation

### ISSUE THREAD

**Issue by dgasaway** [ShareX/ShareX#4733]
Now that I'm working remotely a lot (and initiating captures remotely), the "walking ants" animation really drags down the session and makes it difficult to get the correct region captured.  I've already disabled the "Enable animations" option in the capture toolbar, but it didn't seem to have any effect on the ants.  Thanks!

**Comment by Jaex** [comment]
I on purpose did not stop ants effect with disable animations option because I thought people wouldn't like disabling ants effect. So now I made it also disable ant animation and probably some people not gonna be happy about it.

**Comment by dgasaway** [comment]
Sure, I understand.  I wasn't surprised that it did not, because I saw that people were requesting the option specifically for a different kind of animation.  That's why I phrased it as a request for a different option.  I'll live with it, whatever you decide.  Thanks.
