### ISSUE TITLE
Feature Request: Preselect last captured region in region capture

### ISSUE THREAD

**Issue by georg-jung** [ShareX/ShareX#4741]
I've used some [rather ancient screenshot tool](https://www.heise.de/download/product/activaid-24593) in the past. While it's far inferior in most disciplines, it provides a feature that I used a lot but didn't find an equivalent in ShareX.

There was an option to have the last captured region preselected in region capture mode. It wasn't about capturing the exact same region automatically again (which I know exists as "Capture > Last Region") and it wasn't just about the same size (which I know [exists](https://github.com/ShareX/ShareX/issues/3079) too) but rather a "Capture > Region (Last Region preselected)" or a "\<Capture Region Screen\>: Options > Preselect last captured region", so that I could edit/move/... the on screen selection.

Hope you think this would be useful too :)

**Comment by georg-jung** [comment]
I still think this would be useful - so it's not stale in that sense.

**Comment by realNZZN** [comment]
Still needed

**Comment by X-Raym** [comment]
+1 for this!
We have no way to remake a region exactly the same twice in a row if it isn't snapped to a window.

**Comment by cachius** [comment]
MacOS hast this in the built-in screenshot tool. Would be great to have in ShareX.
This is needed when you need to take multiple screenshots of the same size, but from different positions.
E.g. for a presentation, gallery, reddit post from different websites.
- We could combine it with 'fixed area, by making width and height easily settable from the last screenshot dimensions
- We could enable this through pressing a modifier key on 'Capture last area'

@Jaex Please re-open this

**Comment by cachius** [comment]
See also https://www.reddit.com/r/sharex/comments/pcq1m9/use_size_of_last_captured_region/
