### ISSUE TITLE
Essential folders and files location

### ISSUE THREAD

**Issue by s-malik** [ShareX/ShareX#4742]
I think "%Documents%\ShareX" default location including all folders and files except "Screenshots" folder, should be in %LocalAppData% or %AppData%. The "Screenshots" folder location should be in %Pictures%

![ShareX folder](https://user-images.githubusercontent.com/46628021/79058211-9ea35480-7c30-11ea-8754-6ee635f3d209.png)

**Comment by lucario** [comment]
What gain is there to having those changes?

**Comment by s-malik** [comment]
> What gain is there to having those changes?

I think essentials files are more safe and secure into %LocalAppData% or %AppData%. The “%Documents%” folder is easily accessible.  I share my computer and someone mistakenly deleted the whole folder from "%Documents%” including all of the backup files. I don’t know a program that stores essential files into  "%Documents%”.

**Comment by lucario** [comment]
Maybe you should give the shared user their own account who can't access your Documents folder. We cannot change our file structure due to user error.

**Comment by God-Asimov** [comment]
I can't modify my personal folder. It will continue to be built under Documents.

**Comment by ast3citos** [comment]
I support this request...

> What gain is there to having those changes?

The gain is not to clutter Documents in the user profile as these files and folders are not user documents, they are config files and logs that belong in (Roaming) AppData as per MS best practices.

Screenshots, actually are the documents (pictures) that the user needs so these should go in Pictures/Screenshots

More info here...
+https://blogs.windows.com/windowsdeveloper/2016/05/10/getting-started-storing-app-data-locally/
+https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-5.0#System_Environment_SpecialFolder_MyDocuments
+https://social.msdn.microsoft.com/Forums/vstudio/en-US/77aaf6e1-8de5-4529-9b26-fa89b55fcc49/best-practices-storing-application-data-and-resources?forum=csharpgeneral

Thanks!

**Comment by Wayfarer-es** [comment]
Completely agree with @ast3citos, very good summary of the reasons to change the folder structure.

**Comment by ast3citos** [comment]
I would like to encourage the owners of the project not to ignore this. User error is one of the issues that programmers are taught to take into account, but this is not user error. This is not following best practices for the language in question.
