### ISSUE TITLE
Color picker right click for RGB

### ISSUE THREAD

**Issue by JapanYoshi** [ShareX/ShareX#4743]
I'd like the option to copy the RGB integer values from the color picker *alongside* the hex code.

**Comment by Aholicknight** [comment]
@JapanYoshi Already does that. 
![image](https://user-images.githubusercontent.com/7843719/79183305-bae0f600-7dd6-11ea-96a2-6d7cefc57f36.png)

**Comment by JapanYoshi** [comment]
I meant the “Screen color picker”. As it stands, there is only one custom defined format available in the settings.

**Comment by Jaex** [comment]
RGB is here: ![](https://jaex.getsharex.com/2020/04/ShareX_bcjtIU0pOp.png)

**Comment by JapanYoshi** [comment]
No, I mean I want multiple formats to copy on a case by case basis. Right click does exactly the same thing as left click right now; why not default left click to hex and right click to decimal RGB?

**Comment by Jaex** [comment]
Because right click let you not copy anything to clipboard.

**Comment by JapanYoshi** [comment]
What about shift click then?

**Comment by AfricansCantSwim** [comment]
i agree this si a good idea

**Comment by tomastalian3** [comment]
![image](https://user-images.githubusercontent.com/55493945/95573819-5244a000-0a2c-11eb-8d5b-30bdfc2666d3.png)
Would something like this be okay?

**Comment by JapanYoshi** [comment]
Sounds great!

**Comment by Jaex** [comment]
Added in #5126
