### ISSUE TITLE
Turn off right click to exit Sharex Image Editor

### ISSUE THREAD

**Issue by Ramadas108** [ShareX/ShareX#4746]
Now right click in Sharex Image Editor makes it shut down without prompt for saving. It is very annoying because it can be done by mistake.... and work is lost

**Comment by livan3li** [comment]
yes i was looking for a solution for this issue. How can we overcome it. İ am drawing, typing cropping etc and accidently a right click, all of them is gone! 

The exit choice can be Escape(ESC key) in my opinion no necessery ESC and Right click. One is sufficiant

**Comment by Obi-Sean** [comment]
Just had this betray me yesterday, and even updating to v17 this morning has not solved it. Can we *please* at least get a work around on this?
