### ISSUE TITLE
disable capture sound?

### ISSUE THREAD

**Issue by pstoric83** [ShareX/ShareX#4747]
I can't see a way to disable the capture noise after taking a region capture. Is this possible?

**Comment by Jaex** [comment]
Yes: ![](https://jaex.getsharex.com/2020/04/ShareX_wqqZt3pcSX.png)

**Comment by pstoric83** [comment]
Thanks! I was looking in app settings instead of task settings.

**Comment by Aholicknight** [comment]
@pstoric83 why is this issue still open if it's solved?

**Comment by dinbtechit** [comment]
Hmm.. I no longer see that option to disable the sound.

I am using the latest version.

![image](https://user-images.githubusercontent.com/17984781/199523039-301913fe-9419-4729-ba07-c9327637f255.png)

**Comment by asolopovas** [comment]
It is no longer there where is it this time?

**Comment by asolopovas** [comment]
Maybe it should be disabled by default to allow people to choose if they want a buzz each time especially at night

**Comment by Aholicknight** [comment]
> It is no longer there where is it this time?

![ShareX_20231218_8xiJ8rhUQc](https://github.com/ShareX/ShareX/assets/7843719/9b550857-3993-465e-84d0-bc52521cd533)

Look harder.

**Comment by rbtmarshall** [comment]
It's not there anymore, and this thread is the top search result for the issue

Currently looking harder...
