### ISSUE TITLE
Weird editor problem

### ISSUE THREAD

**Issue by rasqual** [ShareX/ShareX#4753]
Can't figure this out.

In the editor, only the bottom right-hand portion of an image allows the mouse button to act. It displays as a pointer everywhere else in the image, but as a cross-hair only in the lower right. 

Thus, I cannot click to begin a highlight range anywhere to the left in the image, or toward the top. Only in the lower right. I can drag the range TO the left, or upward, but I cannot begin IN the left, or top parts of an image. 

Very strange, and it's making the whole tool useless to me.

Am I missing something obvious?

**Comment by eeskildsen** [comment]
I'm having the same issue. It only happens on my second monitor. I wonder if this has something to do with scaling?

In the image editor, the cursor is a resize handle everywhere except the bottom-right corner. And it's actually functional: If I click and drag, it resizes the window.

Here's a demo. Unfortunately it didn't capture my cursor ... just the ShareX magnifier. Hopefully it's clear what's happening from the magnifier's position.

https://i.imgur.com/BFAEWRQ.gif

**Comment by herronism** [comment]
I also have the same issue as @eeskildsen. If the editor is on my second monitor, I'm only able to see the crosshairs when I move to the very edge of the image. Works 100% fine on my primary screen - just drag the editor window across and it works!

**Comment by herronism** [comment]
This issue is still occurring for me as described above. Can this thread be reopened?

**Comment by herronism** [comment]
@Jaex Please can you retest the issue :)
