### ISSUE TITLE
cricle screenshot

### ISSUE THREAD

**Issue by Cantay** [ShareX/ShareX#4755]
Is there a way I can take screenshots in a round shape other than rectangular and square?

**Comment by Jaex** [comment]
Yes: ![](https://jaex.getsharex.com/2020/04/ShareX_X9q6GNG9Ii.png)

**Comment by Cantay** [comment]
Hi Jaex, is there any way to choose the region selection round while taking screenshot? Is there an add-on?

**Comment by JeffaloBob** [comment]
![image](https://user-images.githubusercontent.com/40470736/79765009-5ec22880-8326-11ea-9f28-033f0a3cd9bf.png)
