### ISSUE TITLE
Google photos, folder bug

### ISSUE THREAD

**Issue by mgjuhler** [ShareX/ShareX#4756]
Hi,

I'm not sure if this is a bug in sharex or in google photos. When I click "refresh folder list" under "google photos" it lists only the folders I created via sharex and not any of the folders that are on the google photos website. The folders that I create via sharex are created on the google photos page..
![img_2](https://user-images.githubusercontent.com/6578036/79783945-c76ace80-8341-11ea-85bc-3cbc2e6e39dd.png)
![img_1](https://user-images.githubusercontent.com/6578036/79783947-c89bfb80-8341-11ea-9401-0192cf7a9318.png)

**Comment by lucario** [comment]
Hello, I wrote Google Photos for ShareX. This is not a bug, the API is limited to where you cannot upload to folders you did not create using ShareX, so I simply don't display them as it would result in an error anyway.

**Comment by LANudlejning** [comment]
> Hello, I wrote Google Photos for ShareX. This is not a bug, the API is limited to where you cannot upload to folders you did not create using ShareX, so I simply don't display them as it would result in an error anyway.

Although I select one of the two folders I created via ShareX, it does not upload the files to the selected folder. Instead, it creates a new folder with the same name as the file and uploads the file to that folder.

![img 1](https://user-images.githubusercontent.com/55537386/79830961-d172e880-83a6-11ea-9418-2c3578d92123.png)
![img 2](https://user-images.githubusercontent.com/55537386/79830962-d20b7f00-83a6-11ea-95b9-d894b0c68618.jpg)
![img 3](https://user-images.githubusercontent.com/55537386/79830957-d0da5200-83a6-11ea-8ba2-ac3e57bbe814.png)

**Comment by mgjuhler** [comment]
> Hello, I wrote Google Photos for ShareX. This is not a bug, the API is limited to where you cannot upload to folders you did not create using ShareX, so I simply don't display them as it would result in an error anyway.

Although I select one of the two folders I created via ShareX, it does not upload the files to the selected folder. Instead, it creates a new folder with the same name as the file and uploads the file to that folder.

![img 1](https://user-images.githubusercontent.com/55537386/79830961-d172e880-83a6-11ea-9418-2c3578d92123.png)
![img 2](https://user-images.githubusercontent.com/55537386/79830962-d20b7f00-83a6-11ea-95b9-d894b0c68618.jpg)
![img 3](https://user-images.githubusercontent.com/55537386/79830957-d0da5200-83a6-11ea-8ba2-ac3e57bbe814.png)

**Comment by lucario** [comment]
I wish I could tell you that was a bug, but it isn't. The Google Photos API is very limited and doesn't cater well to ShareX's use case. There is no concept of public images, only public folders. So by needing to upload a single image, we must create a folder specifically for that image, then share the url to the folder. I know all of this is less than ideal, but there is currently no better option regarding their API. I also created the Google Cloud Storage support for ShareX, and I recommend it if you want a great way to use ShareX.
