### ISSUE TITLE
Regular emoji stickers?

### ISSUE THREAD

**Issue by Germain-Italic** [ShareX/ShareX#4761]
Hi,
blob emoji stickers are great, but regular emojis would be greater.
Is this planned?
[Twemoji](https://twemoji.twitter.com/) stickers are open-source.

**Comment by KeronCyst** [comment]
I want to use emoji in screenshot text annotation, too!

**Comment by Jaex** [comment]
You can add your own sticker packs by selecting folders which contains images. We are not planning to add more emoji packs because it increasing setup size of ShareX significantly.

**Comment by KeronCyst** [comment]
Wait, I'm not talking about emoji packs. I'm talking about the default Windows emoji that are invoked by Win+period. Those seem to only show up as boxes when typing.

**Comment by Germain-Italic** [comment]
> Those seem to only show up as boxes when typing

Yep, bug confirmed

**Comment by Jaex** [comment]
GDI which is used to draw text not supports drawing emojis. And GDI+ draws non colored emoji which still looks bad.

**Comment by gooddadmike** [comment]
Any windows text box control can get these emojis. There has to be a simple way to enable them as an annotation. This rich text editor (and most dumb text editors) we are using right now can do it using `Win` + `+`

💪🤓👍👋🔋🤝❤🚗🥂🎓💯🧵🤜🤛⭐🤷‍♂️🎂🎉😜🆒🎓📚📚📋💰

**Comment by Aholicknight** [comment]
Is there a site where we can download emoji sticker packs? If I try to search on google "microsoft emoji pack download" "download emoji pack" nothing shows up

**Comment by evil-pechenka** [comment]
You can add from here, very good emoji: https://openmoji.org/library/

https://github.com/hfg-gmuend/openmoji/releases/
![2023-05-25_14-50-33-%t](https://github.com/ShareX/ShareX/assets/109512933/453b5864-8244-4914-af28-abc4514a53df)

**Comment by softyoda** [comment]
How do i add the release link you shared to actual share-x ?
