### ISSUE TITLE
Why it's become a circle?

### ISSUE THREAD

**Issue by RtYkk** [ShareX/ShareX#4762]
![ShareX_w91iPQ9qEt](https://user-images.githubusercontent.com/45971730/80219741-79bdd100-8675-11ea-8f48-eaa3ff304582.jpg)
How to change it to rectangle? I don't set anything but it suddenly become circle! I have uninstall and reinstall it. There's no use. It really puzzled me and I've tried to Google but I have no answer.
I'm going mad. Who can help me? Thank you very much. Sorry to open a useless issue

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/04/chrome_K3Hf7seApr.png)

**Comment by RtYkk** [comment]
> ![](https://jaex.getsharex.com/2020/04/chrome_K3Hf7seApr.png)

Thank you very much ❤️.
