### ISSUE TITLE
Feature Request or Access Question - Launch Editor Directly

### ISSUE THREAD

**Issue by DustDiesel** [ShareX/ShareX#4766]
I love the ShareX Editor for annotations, hilights, magnifications, etc..

I have found that I am able to open other pictures once I am already in the ShareX Picture Editor..

I would like there to be a shortcut to open the Editor directly or have a Windows Context option available to edit images I have in various folders, screenshots or not.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/04/ShareX_BBE3BmpMD4.png)
