### ISSUE TITLE
[feature request] rotate capture before upload

### ISSUE THREAD

**Issue by Aokromes** [ShareX/ShareX#4771]
imho this feature can have use on case someone gives you one image incorrectly rotated and you need to send to someone else without having to download, rotate, upload.

example:

https://i.imgur.com/eCcw5AR.jpg

**Comment by Aokromes** [comment]
still wanted.

**Comment by Aokromes** [comment]
still wanted

**Comment by MateusAuri** [comment]
I got here while looking for something else, but it seems a basic rotate and flip option was added in May
https://getsharex.com/changelog/#sharex-1350---2021-05-13

I'm not entirely sure, but I think you need to go into the "edit image" mode to use it, after taking the screenshot.
![image](https://user-images.githubusercontent.com/19670632/142759756-80877419-6780-4660-a130-f420b532902c.png)

**Comment by Aokromes** [comment]
strange i don't have such options on that setting, maybe because my instalation is ancient.

**Comment by Aokromes** [comment]
ah ok, it's on the image editor, i want to have it while capturing.

**Comment by MateusAuri** [comment]
Yeah, for now, the workaround would be to take the screenshot first and rotate it later through the editor

**Comment by Xiarno** [comment]
I'd like to rotate it while capturing too.

**Comment by Mqisty** [comment]
still wanted

**Comment by joannesalfa** [comment]
still wanted

**Comment by Xiarno** [comment]
It's still wanted.

**Comment by Aokromes** [comment]
stil lwanted

**Comment by Xiarno** [comment]
@Aokromes Maybe we'll need to open a new issue :/

**Comment by safhossain** [comment]
Still wanted
