### ISSUE TITLE
Different path for screenshot and screen record

### ISSUE THREAD

**Issue by xmha97** [ShareX/ShareX#4773]
Hello,
Please add below feature:
- Different path for screenshot and screen record.

![ShareX](https://user-images.githubusercontent.com/23485114/80644913-aca20380-8a7f-11ea-83b0-2fa35ec63197.png)

**Comment by OMGasm** [comment]
Does changing the capture path for your record task do anything?
![image](https://user-images.githubusercontent.com/1008183/81478848-2cd81e00-9263-11ea-9801-7c40622a4b33.png)

**Comment by xmha97** [comment]
I changed this path:
![image](https://user-images.githubusercontent.com/23485114/81483310-7c621e00-9252-11ea-81ca-a7bfd95940cd.png)

From now on, all screenshot and screen record will be saved in this path.
I want to save screenshot and screen record in separate folders.
