### ISSUE TITLE
BUG: Custom image uploader appears twice in upload window

### ISSUE THREAD

**Issue by stephen147** [ShareX/ShareX#4775]
Here is the problem.

If I enter one item in the uploader settings, two appear in the upload window.
## The main settings window for uploaders
![image](https://user-images.githubusercontent.com/14054664/79259629-ec17ff80-7e84-11ea-9b8d-b627ee6bfb65.png)

## The upload window now has 2 entries instead of 1
![image](https://user-images.githubusercontent.com/14054664/79259510-be32bb00-7e84-11ea-8e5d-a17ecc51aa56.png)

**Comment by Jaex** [comment]
It is not a bug, one is custom image uploader other is custom file uploader.

**Comment by stephen147** [comment]
I don't understand, why can't the one custom item not do the two seeing as it's the same hosting site?

I have the destination type set to image but still, I have two items appearing at the before upload option dialog.

It doesn't make sense to have image hosting sites show up when you want to upload a text file or vice versa.
