### ISSUE TITLE
Imgur upload privacy ?

### ISSUE THREAD

**Issue by Kellphy** [ShareX/ShareX#4777]
New user here, I'm sorry for the simple question.

Is a photo uploaded as "Anonymous" set to Public, Private or Hidden:?
Can it only be accessed through the link provided by ShareX ?

Thank you! :)

**Comment by Kellphy** [comment]
![image](https://user-images.githubusercontent.com/46824693/80723101-dc491e00-8b08-11ea-9ef9-166fe81419b6.png)

Sorry, I did find my answer on: https://help.imgur.com/hc/en-us/articles/201746817-Post-Privacy-Settings
TL;DR Hidden

**Comment by Jaex** [comment]
That answer is misleading. Because URLs are short, people can find them by brute force. So you must assume your links are public.
