### ISSUE TITLE
Recorder-devices-setup.exe being detected as malicious, again?

### ISSUE THREAD

**Issue by elee001** [ShareX/ShareX#4778]
After some googling, I did see in the past sharex was being detect as malicious and it was a known false positive. It looks like its back. 

https://www.virustotal.com/gui/file/cea1142189b290affe70b16708b9d1b43bc63c375fbeb76336397554d207b484/details

**Comment by LinuxOnTheDesktop** [comment]
Same here: one scanner on VirusTotal - though admittedly a scanner I've never heard of - [deems the latest setup executable (version 13.2.1) malicious](https://www.virustotal.com/gui/file/ee62651c559c7d15edc945ff887e7c52e59c8eda8dc01a6b60a27aaa1475d8f4/detection).

**Comment by omniscient3** [comment]
This appears to be happening on the latest 13.3 release as well. Virustotal is reporting two engines are detecting, one of which being CrowdStrike

https://www.virustotal.com/gui/file/8190f916d2c1fa5e0a9404de2b193ae92571952d271403ef81eb510d81094a69/detection

I think this is also causing the installer exe to be detected as malware

**Comment by Luttudo** [comment]
Just happened to me
