### ISSUE TITLE
Suggestion - Add additional formats for Step tool

### ISSUE THREAD

**Issue by frankroj** [ShareX/ShareX#4779]
The Step tool in the Image Editor currently only allows you to stamp with numbers. It would be nice if we could also stamp with letters instead of numbers (a, b, c, d, etc). Ideally it would support both uppercase and lowercase.

**Comment by Jaex** [comment]
Step tool already have "Use letters" option.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/04/ShareX_6SKQ76M3Le.png)

**Comment by frankroj** [comment]
I am so sorry. I looked and looked and couldn't find the option. I even looked at this screen. I also had someone else look for it and they couldn't find it either. It was staring us in the face.

**Comment by Jaex** [comment]
Added lowercase support too now:

![](https://jaex.getsharex.com/2021/04/ShareX_H6dL39Rc3Q.png)
