### ISSUE TITLE
feature_request(presets): make action, use another configuration

### ISSUE THREAD

**Issue by Kristinita** [ShareX/ShareX#4792]
### 1. Summary

It would be nice, if would be possible run [**any ShareX action**](https://github.com/ShareX/ShareX/blob/master/ShareX/Enums.cs#L167-L228) use different settings presets.

#### 2.1. Common cause

Automation. Saving users time.

#### 2.2. Details

I need to change my ShareX settings, where I want to make screenshot not in normal mode → after screenshot making I need to revert settings in normal mode. It takes my time. So I use another screenshot app (Greenshot) for making screenshots not in normal mode.

To save users time it would be nice to have presets of settings and quick switching between presets.

#### 2.3. Modes

I need 3 ShareX modes.

1. **Normal**

    ```json
    "AfterCaptureJob": "AddImageEffects, AnnotateImage, SaveImageToFile, UploadImageToHost"
    ```

2. **Site**

    I make screenshots for my personal site. In my site I use [**CSS shadows effects for images**](https://css-tricks.com/almanac/properties/b/box-shadow/) → so I disable `AddImageEffects` in this mode.

3. **Simple**

    I use it, where I want quickly save screenshot in live game. No image effects, annotations and uploading to remote hosting. I capture the window and save image to folder. I change `CustomScreenshotsPath` setting for this mode.

### 3. Example of expected behavior

[**Command-line (CLI) argument**](https://getsharex.com/docs/command-line-arguments) `--config`.

User run in terminal:

```text
sharex -ActiveWindow --config 'path/to/another/ApplicationConfig.json'
```

ShareX capture active window, use settings from custom `ApplicationConfig.json` file.

Thanks.

**Comment by Jaex** [comment]
ShareX workflows already supports this. Each of your hotkey can have different task settings.

**Comment by Kristinita** [comment]
**Status: Solved for me** ✔️

Problem solved via `Hotkey settings` → `Add…`.

Sorry, I didn't look to this menu item, when I was looking for a solution to my problem.

Thanks.
