### ISSUE TITLE
4k support

### ISSUE THREAD

**Issue by lmiol** [ShareX/ShareX#4793]
Right now toolbar and settings cant be sized correctrly for Windows Desktop resolution 3840x

if i trying to do windows app copablity - then after prntscreen my screen is not ful

**Comment by lucario** [comment]
ShareX displays fine on my 4k monitor with 200% scaling. Please update to the latest version of ShareX, and provide screenshots and logs.

**Comment by KevinClaytonGustafson** [comment]
I was attempting to record in 4k and got fairly poor results. Should I post that here or in another ticket?

**Comment by lucario** [comment]
@KevinClaytonGustafson This issue is related to UI scaling @4k, recording in 4k would indeed be a separate issue, However, we may be able to answer your question faster in ShareX support on discord discord.gg/sharex
