### ISSUE TITLE
Screen Recorder Leaving blank files

### ISSUE THREAD

**Issue by Darkenflame** [ShareX/ShareX#4797]
Sharex has been working just fine for me, until I switched the audio to microphone, because I wanted to speak into my mic while recording something on screen. Since then, the recorder has been refusing to working as attended since then. I tried switching the Codec. I was working fine with one of them for a few minutes then it went back to creating blank videos. I even tried installing the new ffmpeg and everything, but that won't work either. How can I fix this?

**Comment by Duckrinium** [comment]
Have you tried reinstalling recorder devices?
![image](https://user-images.githubusercontent.com/37019004/82103473-ce57e780-971b-11ea-981c-8dab1968dd7f.png)
