### ISSUE TITLE
Regex in history search (filename, url)

### ISSUE THREAD

**Issue by EhsanKia** [ShareX/ShareX#4799]
Being able to search history is great, but it would be much more powerful if I could use regex in filename/url fields.

**Comment by EhsanKia** [comment]
I still think this is a useful feature and not too hard to implement.

**Comment by Jaex** [comment]
> I still think this is a useful feature and not too hard to implement.

Actually it would be easier than current search implementation, because to be able to support wildcards we are converting wildcards to regex in the background. Is regex really needed when there is wildcard support though?

**Comment by EhsanKia** [comment]
Honestly, it was long ago and I don't remember exactly why I needed regex, but I don't think I realized wildcards work, so in hindsight that might be good enough in most cases indeed. Up to you, if you think it's easy enough to throw a checkbox somewhere, I could see cases where it would be useful to be more specific as regex can be very powerful.
