### ISSUE TITLE
Wrong number of bytes in statistics

### ISSUE THREAD

**Issue by user6323** [ShareX/ShareX#480]
Hello.
I use url shortener after upload to destination. When it uploaded - i see correct size. But after url shortening i see 139 byte. http://j.mp/1CAEenM
Maybe it does not matter with screenshots, but the video size is important for me.

**Comment by Jaex** [comment]
You didn't told which url shortener. Because now I tried bit.ly and it not changed file size.

**Comment by Jaex** [comment]
I tried bit.ly and file size not changed. How to reproduce it?

**Comment by user6323** [comment]
Right now i disabled shortener and problem still there. The problem is not in shortener.

I was able to repeat this is only unloading on dropbox, without shortener.

https://dl.dropboxusercontent.com/s/tdrbhaumsl54apn/1421866047.webm?dl=0 - video with error.

**Comment by Jaex** [comment]
Creating Dropbox shareable link was causing it.
