### ISSUE TITLE
"Open in image editor" and "Save image to file" together

### ISSUE THREAD

**Issue by endrx** [ShareX/ShareX#4807]
If "After capture tasks": "Open in image editor" and "Save image to file" both switched on, then "Save image to file" doesnt' happen. Capture opens in editor, but saving not occur.

I think that it should occur in this case. Because if somebody wants to save from editor, he can turn auto save off.

**Comment by JustYT** [comment]
The same issue if you have "copy to clipboard" and "open in editor". It just opens it in editor but doesn't copy in clipboard.

**Comment by tomastalian3** [comment]
This happens because when you click "cancel task" in the editor, all following tasks are also cancelled. I don't know if this is the intended behavior, but if it is okay with @Jaex, I can fix it and open a PR.

**Comment by djtrao** [comment]
> This happens because when you close the editor or click "cancel task", all following tasks are also cancelled. You have to click "continue task" to proceed with other tasks which can be a bit confusing. Maybe closing the editor should continue with other tasks and there should be a button called "cancel all tasks" instead. I can change this behavior and open a PR. More up-to-date issue: #5107

This is it, thanks alot. 
Kinda strange to haveing to do it that way... I would expect that copy to clipboard and opening the editor would happen at the same time, it's the most convenient. I'll have to swtich to another software in that case. 

Thanks alot for the link!

**Comment by tomastalian3** [comment]
What's your opinion on this @Jaex ? I can change the behavior but I need to know how would you like it done.

**Comment by Jaex** [comment]
> I need to know how would you like it done.

I already done it how I would like it done?

**Comment by tomastalian3** [comment]
Oh, so this is fixed?

**Comment by Jaex** [comment]
There is no bug to fix, it works as intended.

**Comment by tomastalian3** [comment]
Well yes, but the behavior is maybe a bit confusing for users as there are multiple open issues about this. Maybe it needs just a small change and that would be: closing the editor window does not cancel the other tasks.

**Comment by Jaex** [comment]
And then more people gonna open issues because they can't cancel the tasks by closing the window, like before...

**Comment by djtrao** [comment]
To quickly Grab a Screenshot, look if I need to crop it and then Inserat it
into a Mail etc, this "first Click on next" step in the editor is really
awkward. I dont know of any other Programms that do it.

You take the Screenshot, editor opens. You just paste it and you re done.

Only if I need to crop/draw on it etc, I will hit copy once I'm done.

Closing the editor should not be what trigger the copy to Clip board.
Taking the Screenshot is. That's how every ss prog I used works. Take
Screenshot, it's already in Clip board, no matter what I do next.

(IMHO)

**Comment by popstas** [comment]
Solution for me: press Enter in image editor (previous pressed Esc-Esc). Then image editor closes and other tasks executes!

**Comment by Ion3** [comment]
If I understand you right, there is no way it automatically saves the image before opening the saved file in the image editor?

**Comment by Ion3** [comment]
Is it right just to close the issue because there is no action?

I would prefer the action to enable „save file“ & „open editor“ in combination..

**Comment by lx30011** [comment]
A save "unedited image" option, maybe? I'd use it.

**Comment by bbseal** [comment]
Yeah this doesn't make any sense.  If I have "Save image to file" as an after-capture task, my intention is obviously to save the file.  The primary reason I also "open in image editor" is to look at what I've just captured, and possibly edit it.  Here I have to "continue" the task just so I can ensure the file is saved, but since this closes the editor, I have to go back and open the editor again!

Is there a way to adjust the order of operations so that the save occurs first?

**Comment by uperendi** [comment]
yes, this is a problem. It should save even image editor is opened. even tasks are cancelled, save should be automatically. i dont want to press "Ok, Enter, tickbox" each screenshot in the editor for it to be saved.

Basically it should save it first, and if I make changes in the editor, it should override the file saved with the changes. but it should first save without pressing enter.

**Comment by ZennfI** [comment]
Just found a workaround. 

In task settings, open "Actions" and add a new entry with the file path of ShareX.exe (by default on Windows, %ProgramFiles%\ShareX\ShareX.exe) and with the argument `-imageeditor "$input"`. 

![image](https://user-images.githubusercontent.com/1340067/223087525-9a3aba8e-76f9-4533-84e8-95507bc1a193.png)

Don't forget to activate the action (ticked) and to choose `After capture tasks > Perform actions`

![image](https://user-images.githubusercontent.com/1340067/223088150-38d2620c-b40d-4571-9a58-3c76e39bfbcc.png)

**Comment by KonRay** [comment]
It is really frustrating to see this issue being closed without any actual fix applied.

Logically, if I select several tasks after capture, I expect all of them to run simultaneously, not one after another.

Also, if I cancel the editor because I decide I don't want to edit that particular image, it should not mean the image is not saved at all. Cancelling the edit should simply skip editing — not cancel the entire save process.

Honestly, the current behavior does not make sense and should not be treated as expected.
