### ISSUE TITLE
Could not load file or assembly 'ShareX.UploadersLib. Version-1.0.0.0. Culture-neytral.PublicKey Token=null or one of its dependencies'

### ISSUE THREAD

**Issue by Nikschavan** [ShareX/ShareX#481]
System.BadImageFormatException: Could not load file or assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Nikschavan** [comment]
This error is since todays update.

**Comment by Jaex** [comment]
It means corrupt UploadersLib.dll I think try reinstalling manually. Not sure how it can be corrupt too.

**Comment by Nikschavan** [comment]
Reinstalling fixed it.
Thank you :)
