### ISSUE TITLE
Theme isn't applied correctly to disabled GroupBoxes and ListViews

### ISSUE THREAD

**Issue by maximmax42** [ShareX/ShareX#4813]
In the Application Settings -> Upload -> Retry there are 3 GroupBoxes that, when disabled with a checkbox above, are getting colored incorrectly.

![image](https://user-images.githubusercontent.com/2225711/82121712-8cc14e00-97a8-11ea-8fbc-39b82e956377.png)
![image](https://user-images.githubusercontent.com/2225711/82121714-90ed6b80-97a8-11ea-9dff-48ce2ec360be.png)

**Comment by Jaex** [comment]
Win forms not let me change color of disabled controls color.
