### ISSUE TITLE
Unable to Snap to Windows with Medal 

### ISSUE THREAD

**Issue by ititaniscrippled** [ShareX/ShareX#4824]
I recently started to use Medal to record all my game clips, etc. I have been using ShareX for the past couple of years for picture/gif taking. However, when I have Medal open (either in the foreground or background), ShareX cannot seem to snap to windows as it usually does; however, once I close Medal, ShareX starts to snap to windows once more.

Video Reference: [https://streamable.com/9o8ul3](https://streamable.com/9o8ul3)

**Comment by aliakbo** [comment]
Hey, I'm a Medal dev.
Will address this in our next release.

**Comment by xLuckyOne** [comment]
@aliakbo News on this?
