### ISSUE TITLE
The remote server returned an error: (422) Unprocessable Entity.

### ISSUE THREAD

**Issue by splattadat** [ShareX/ShareX#4826]
```
Request URL:
https://vgy.me/upload

Status code:
(422) Unprocessable Entity

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, private
Content-Type: application/json
Date: Sat, 23 May 2020 23:15:35 GMT
Set-Cookie: __cfduid=[redacted]; expires=Mon, 22-Jun-20 23:15:35 GMT; path=/; domain=.vgy.me; HttpOnly; SameSite=Lax; Secure,XSRF-TOKEN=[redacted]; expires=Sun, 24-May-2020 01:15:25 GMT; Max-Age=7200; path=/; secure,vgyme_session=[redacted]; expires=Sun, 24-May-2020 01:15:25 GMT; Max-Age=7200; path=/; secure; httponly
X-Powered-By: PHP/7.3.18
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Strict-Transport-Security: max-age=2592000; includeSubDomains; preload
Server: cloudflare
CF-RAY: [redacted]
cf-request-id: [redacted]

Response text:
{"error":true,"messages":{"Internal Error":"An unknown error occurred.<br \/>Please try again, or contact us if it continues."}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```
When using the Upload function (CTRL-U), if **ANY** major server error occurs (not just the one listed above), a nasty outcome is that the image (_that just had 20 mins editing effort added to it_) is then listed as NOT viewable, editable or anything - the image data is simple discarded with an `error` entry added to the filename view. This is extremely unnerving and frustrating - please fix.

A server upload connection failure should **not** affect the image being successfully created/edited and saved as a local file. I have fallen over this nasty outcome a few times over several upgrades, thinking that someone would have reported this obvious flow flaw.

**Comment by Jaex** [comment]
Is file saving not enabled in your ShareX? Because then your 20 mins editing effort would still stay as file and you can reupload it.

**Comment by splattadat** [comment]
Today, there was no editing, as this feature has left me in a state where i have kind of stopped editing due to fear of image data loss (red: time wasted), a previous time, there was editing, and no, the image data was not saved - which made me shout out aloud a rude word or two.

**Comment by splattadat** [comment]
> Is file saving not enabled in your ShareX

Today, there was no editing, as this `feature` has left me in a state where i have kind of stopped editing due to fear of image data loss (red: time wasted), a previous time, there was editing, and no, the image data was not saved - which made me shout out aloud a rude word or two. 

My flow, is i click the taskbar icon, begin to capture, (perhaps edit), then click the upload button, at this point the image data is not saved **unless the upload is successful** - this is the problem.

**Comment by Jaex** [comment]
If saving to file is enabled in after capture tasks then it saves file before uploading. Therefore even if upload is fail then file stays there and you can easily reupload it from ShareX.

**Comment by splattadat** [comment]
Yes, menu item "Save image to file" (under "print") is enabled and **bolded** in sub menu "After capture tasks".

**Comment by splattadat** [comment]
Yes, menu item "Save image to file" (under "Print image") in the sub menu "After capture tasks", is enabled, its text is **bolded**, and the menu item icon has a square around it to indicate that it is enabled.

**Comment by splattadat** [comment]
vgy is now back online, so attached is an image of the ShareX UI and the erroneous entry... observe how the image data is not presented in the right hand pane - it is forfeit due to the upload failure...
<img src="https://i.vgy.me/mvz5zb.png">

**Comment by Jaex** [comment]
In image editor you not letting task continue and overriding after capture tasks with only upload, therefore ShareX does exactly what you instructed it to do.

**Comment by splattadat** [comment]
1) If the upload task is a success, then the image data is saved, there is no "override" in the case of success. It is **ONLY** if upload task fails that image data is lost.
2) The upload button is not marked, "override upload then abort save" - because that would be nonsense.
3) If task == capture, then regardless of the upload outcome, a capture task has taken place, therefore, after the capture task, the image data is supposed to be saved in **every** case.

**Comment by splattadat** [comment]
1) If the upload task is a success, then the image data is saved, there is no "override" in the case of success. It is **ONLY** if upload task fails that image data is lost.
2) If task == capture, then regardless of the upload outcome, a capture task has taken place, therefore, after the capture task, the image data is supposed to be saved to file in **every** case.

If you won't change this behaviour, then please consider to add an advanced option to remove the "Upload task" button from the edit page so that only the green tick can be pressed, and therefore, we can be prevented from falling down the black hole trap of the "override on failure" feature.

**Comment by splattadat** [comment]
`vgy.me` is currently down and Cloudflare is posting 502, therefore, capturing a screenshot, adding some text for the other person to read and then uploading will again end in an error and the image is then lost, not saved. Resulting in a big sigh exhaled ;) Please, please, please, think about addressing this.

**Comment by BHare1985** [comment]
vgy.me now only accepts registered accounts. It will have to be updated to accept an API or something

**Comment by splattadat** [comment]
> vgy.me now only accepts registered accounts. It will have to be updated to accept an API or something

I've always used a registered account, that functions fine and is not the issue raised here.

**Comment by BHare1985** [comment]
> > vgy.me now only accepts registered accounts. It will have to be updated to accept an API or something
> 
> I've always used a registered account, that functions fine and is not the issue raised here.

It is for me, if you look at the debug when you get 422 Unprocessable Entity

```
Request URL:
https://vgy.me/upload

Status code:
(422) Unprocessable Entity

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, private
Content-Type: application/json
Date: Wed, 05 Aug 2020 22:42:45 GMT
Set-Cookie: __cfduid=db1d4d8bc61e3906e646d80b1400249501596667364; expires=Fri, 04-Sep-20 22:42:44 GMT; path=/; domain=.vgy.me; HttpOnly; SameSite=Lax; Secure,XSRF-TOKEN=eyJpdiI6Im1DQU9LcFQ0WUdQOTU3QXFmd2E0eUE9PSIsInZhbHVlIjoieGhLaWQ3ZDdaWTdCRGtuK3NTTTNVV2RkOXVmd2dYQkJtOXUyTGVVMnorS2NwNFFtam5QTzZZcHFCRDRMK3FUdyIsIm1hYyI6ImNlNjgwNGFlYzczMDRmNTk3ZjExM2NkM2Q1NTU4ZThhMDMxNDcyOTIyMDg0YTU3MDczZDBiNjFkMjcxMzAxNjMifQ%3D%3D; expires=Thu, 06-Aug-2020 00:42:22 GMT; Max-Age=7200; path=/,vgyme_session=BxMhvnQJdUhLutpkrTPM9YGQGZt5aWKXxLTfsVnZ; expires=Thu, 06-Aug-2020 00:42:22 GMT; Max-Age=7200; path=/; httponly
X-Powered-By: PHP/7.3.21
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'self'; img-src https: data:; media-src https: data:; script-src 'unsafe-inline' 'unsafe-eval' https:; style-src 'unsafe-inline' https:; font-src https: data:; frame-src https:
Strict-Transport-Security: max-age=2592000; includeSubDomains; preload
CF-Cache-Status: DYNAMIC
cf-request-id: 0462639e4800007e25cd3df200000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5be40876dd677e25-DTW

Response text:
{"error":true,"messages":{"Unauthorized":"You are not logged in, or your account has been banned. You cannot upload anonymously."}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2020-08-05 18:42:45.226 - UploadersConfig save started: C:\Users\bhare\Documents\ShareX\UploadersConfig.json
2020-08-05 18:42:45.226 - ApplicationConfig save started: C:\Users\bhare\Documents\ShareX\ApplicationConfig.json
2020-08-05 18:42:45.226 - HotkeysConfig save started: C:\Users\bhare\Documents\ShareX\HotkeysConfig.json
2020-08-05 18:42:45.322 - UploadersConfig save successful: C:\Users\bhare\Documents\ShareX\UploadersConfig.json
2020-08-05 18:42:45.360 - HotkeysConfig save successful: C:\Users\bhare\Documents\ShareX\HotkeysConfig.json
2020-08-05 18:42:45.397 - ApplicationConfig save successful: C:\Users\bhare\Documents\ShareX\ApplicationConfig.json
2020-08-05 18:42:51.652 - ApplicationConfig save started: C:\Users\bhare\Documents\ShareX\ApplicationConfig.json
2020-08-05 18:42:51.652 - HotkeysConfig save started: C:\Users\bhare\Documents\ShareX\HotkeysConfig.json
2020-08-05 18:42:51.652 - UploadersConfig save started: C:\Users\bhare\Documents\ShareX\UploadersConfig.json
2020-08-05 18:42:51.741 - UploadersConfig save successful: C:\Users\bhare\Documents\ShareX\UploadersConfig.json
2020-08-05 18:42:51.769 - HotkeysConfig save successful: C:\Users\bhare\Documents\ShareX\HotkeysConfig.json
2020-08-05 18:42:51.788 - ApplicationConfig save successful: C:\Users\bhare\Documents\ShareX\ApplicationConfig.json

```

**Comment by splattadat** [comment]
> > > vgy.me now only accepts registered accounts. It will have to be updated to accept an API or something
> > 
> > 
> > I've always used a registered account, that functions fine and is not the issue raised here.
> 
> It is for me, if you look at the debug when you get 422 Unprocessable Entity recently it says unauthorized. Perhaps back in May it was an error on vgy.me but it seems now it requires an account and my shareX (latest) doesn't have vgy.me as an account I can put credentials into
> 

Again, I have always used a registered account, that is NOT the issue here.... you are not confirming the issue reported and are actually diverting away with your misuse of the app by not actually setting up the credentials correctly, maybe this will help you set it up correctly...

<img src="https://i.vgy.me/h3CzV7.png">

**Comment by splattadat** [comment]
The original reported issue still exists. 

I circumvent the issue by trying to never click the "Upload image" button in the "Image editor" as the editor is configured to open immediately "After capture task"...

<img src="https://i.vgy.me/fldVlv.png">

...instead I use the green tick button to *save without failure*, and then the "Upload" action from the main display context menu, otherwise the image can disappear into a hole. Happened again the other day when I accidentally pressed the upload button. Horrible "feature", but it is what it is. Otherwise, great app.

**Comment by splattadat** [comment]
Issue still exists.

**Comment by Cyph3r** [comment]
+1
