### ISSUE TITLE
FTP configuration menu fields are grayed out and can't have any FTP details added to them

### ISSUE THREAD

**Issue by imeuropa** [ShareX/ShareX#4827]
Whenever I try to enter the FTP details for my server the fields are just grayed out and you can't even select them. Trying to enter anything is impossible.
I've tried reinstalling the program and deleting all my config files in "Documents -> ShareX" and nothing changes. Anyone have the slightest clue how to fix this?
https://imgur.com/73Dvbz6

**Comment by splattadat** [comment]
In the "Destination settings", under "FTP...", click the "Add" button, that works for me...

<img src="https://i.vgy.me/LNHjna.png">
