### ISSUE TITLE
Not specifying an FTP password gives an unhelpful error message rather than a password prompt.

### ISSUE THREAD

**Issue by flarn2006** [ShareX/ShareX#484]
To expand on what I mentioned in #482: I tried removing the password from the server configuration, expecting it to prompt me for one. Instead, when I clicked the "Test" button: I got the following "error message", which is clearly the result of a bug:

![2015-01-22_17-25-33](https://cloud.githubusercontent.com/assets/687313/5866038/d22dabac-a25b-11e4-959b-31a4e4c5814b.png)

If I try to upload a file anyway, it gives me an error that says "URL is empty" or something similar, which does not describe the problem. If no password is specified, a better way to handle it would be to prompt the user for a password, perhaps attempting to authenticate with a blank password first and prompting for a password if it fails.

**Comment by Jaex** [comment]
Error messages too difficult because require english which is far more difficult than programming :/
I don't prefer password to be not saved because then it losing all point of be able to share quickly. Everybody would hate writing password every single time.
