### ISSUE TITLE
Bug report. Get rid of mouse cursor blinking while capturing video

### ISSUE THREAD

**Issue by helperman** [ShareX/ShareX#4845]
A mouse cursor is constantly blinking during video capturing.
It makes eyes tired.
Is it possible to get rid of it?
This effect appears only during capturing process and is not presented in result video.

**Comment by adzm** [comment]
I am pretty sure this is a byproduct of BitBlt with CAPTUREBLT -- on some video set ups, the mouse blinks when the screen is captured. There are newer capture APIs in Windows 8+ like desktop duplication but might be a bit heavy for something like ShareX.

**Comment by isnandar1471** [comment]
Is there a solution for this?
I am still experiencing it in `Screen recording` and `Screen recording (GIF)` in ShareX version 17.1.0.0,
in Windows 11 Pro Version 23H2
