### ISSUE TITLE
Is it possible to record system audio without installing?

### ISSUE THREAD

**Issue by drkui** [ShareX/ShareX#4846]
I noticed the: Installs "screen-capture-recorder" and "virtual-audio-capturer" video/audio source option for system audio. Is there another way of capturing system audio that doesn't require installation? (I'm using ShareX portable)

**Comment by Jaex** [comment]
FFmpeg not supports audio recording built-in in Windows. So only if they add support for it. But they do support audio recording in Linux.

**Comment by GyanD** [comment]
This is not true. ffmpeg definitely records sound on Windows - I've done it hundreds of times!

You need to make sure the loopback device for audio is enabled in Control Panel -> Sound -> Recording tab

**Comment by cclaerhout** [comment]
Hello, just a short message to say it would be nice to be able to record the sound system without having to install a software that requires admin permissions, which is the situation with this module:
https://github.com/rdp/screen-capture-recorder-to-video-windows-free
