### ISSUE TITLE
Feature request: Pause/Suspend video capturing

### ISSUE THREAD

**Issue by helperman** [ShareX/ShareX#4850]
It would be useful to have ability to pause video capturing for some time and continue it later.
For example, in addition to existing "Stop" and "Abort" buttons, I suggest to add additional button "Pause".
When user clicks the brand new button a current record pauses until user clicks Resume button to proceed the record again.

**Comment by AaqibAhamed** [comment]
> It would be useful to have ability to pause video capturing for some time and continue it later.
> For example, in addition to existing "Stop" and "Abort" buttons, I suggest to add additional button "Pause".
> When user clicks the brand new button a current record pauses until user clicks Resume button to proceed the record again.

I have the same issue.It's better if we have `Pause` button and `Resume` button for all kind of recordings.I'm a .NET developer and I'll try to fix this issue.

**Comment by bagnaraex** [comment]
it would be very cool =DDD please, fix it!!

**Comment by AaqibAhamed** [comment]
> it would be very cool =DDD please, fix it!!

Ok.I have just started.

**Comment by 116581658** [comment]
Me too I am missing very much this functionality. If you can do it will satisfy almost 90% of the missing things about ShareX :) (for me)
