### ISSUE TITLE
[Bug] Freezing after few seconds of recording.

### ISSUE THREAD

**Issue by Fogsight** [ShareX/ShareX#4856]
While area capturing, around 2-3 seconds in every recording has a 1 second freeze.
Just month ago my captures did not have this. Suspect one of the Windows 10 updates introduced it.
The same with GIF and video with/without sound, switching to another codec didn't help. Downloading latest setup with clean reinstall didn't help.
Other capture programs I tried did not have similar problem.
AMD Ryzen 5 2600, 32GB RAM, AMD Radeon R9 200. All drivers/updates up-to-date.

P.S. Just tried Dev build, it has the same problem.

**Comment by Dreamykass** [comment]
I experience a similar issue - recording freezes for a few seconds, very shortly after starting it. The "freeze" is not visible during recording - everything's as normal - but it's visible only on the output gif/video. Here's an example of such:

https://thumbs.gfycat.com/DefiantEveryAchillestang-mobile.mp4
The video starts, freezes after a moment, and unfreezes a few seconds later. What it _should_ look like, is an animation of a bubble sort.

i7-6700, GTX 980 Ti, 32GB RAM. Turning off NVIDIA GeForce Experience doesn't help. Other programs (like ScreenToGif) don't have this issue. All drivers should be up to date.

**Comment by Fogsight** [comment]
Seems to be fixed in 13.2.1

**Comment by StrikerTheHedgefox** [comment]
Hasn't been fixed. I still get it all of the damn time: https://shadowmavericks.com/files/ShareX/ATLYSS_2025-03-14_13-35-29.mp4
