### ISSUE TITLE
Dual monitor vs. region selection

### ISSUE THREAD

**Issue by Shiikii** [ShareX/ShareX#4862]
Whenever, whatever I would like to capture, I can do it only on main screen. During process of region selection secondary screen is covered in black - as well as taken screenshots/vids/gifs/everything.

**Comment by AmauryOrtega** [comment]
This is definitely isolated to your setup. Try giving the version of ShareX you are using and/or logs so the developers can get more insight into your setup

**Comment by Lucasamiel0406** [comment]
It's happening for me too, I upgrade my Windows 7 to 10 and now I can't take screenshots with dual monitor

**Comment by Shiikii** [comment]
ShareX 13.1, up to date, W10 fully updated.
Latest log: https://pastebin.com/qfeqZ8sS

**Comment by JoshuaMaitland** [comment]
Same issue for me as well

**Comment by hessianerd** [comment]
I am also having this issue.  I have three monitors with one in portrite mode and it shows what I am capturing from the first monitor on the second (portrait) monitor.

**Comment by brimwats** [comment]
I've provided a recording of this in #5395

**Comment by decrypt-ai** [comment]
Solution: Uncheck "Restrict region capture and cursor within the active monitor"

Steps:

Open ShareX
Go to Task Settings → Capture → Region Capture
Scroll to the very bottom of the settings panel
Uncheck "Restrict region capture and cursor within the active monitor"
What this does:
When this setting is checked (which appears to be the default for many users), ShareX locks both the capture overlay and your cursor to whichever monitor you initiated the capture on. You cannot drag a selection across monitor boundaries.

Unchecking it makes the capture overlay span the entire virtual screen (SystemInformation.VirtualScreen), allowing you to freely draw a region selection across multiple monitors.

Verified on: ShareX 19.0.2, Windows 11, dual monitors with same scaling (no mixed DPI).

Why this went unnoticed: The setting is at the very bottom of a long settings page, and its name doesn't obviously connect to the "region capture doesn't work on my second monitor" problem that most users search for. Multiple GitHub issues have been open for 5+ years describing this exact problem (#5408, #5127, #8002, #7955).

Note: This fix applies to setups where all monitors use the same DPI/scaling. If you have mixed scaling (e.g., 150% on one monitor, 100% on another), you may still experience rendering/offset issues — those are separate bugs.

![ShareX Region Capture Settings](your screenshot)

<img width="720" height="457" alt="Image" src="https://github.com/user-attachments/assets/ae0cfed5-869d-45f5-82aa-de13e2ccfb77" />

**Comment by limacohen** [comment]
> Solution: Uncheck "Restrict region capture and cursor within the active monitor"

This almost works for me, but it moves the whole screen to make room for the Taskbar. It does this regardless of the capture trigger (hotkey or tray icon).

Unchecking this two options in FancyZones solves that:
<img width="512" height="94" alt="Image" src="https://github.com/user-attachments/assets/42e061ef-1a78-48d0-9e9a-4eced64326ea" />
