### ISSUE TITLE
Start auto-capture at program start

### ISSUE THREAD

**Issue by kimisinnl** [ShareX/ShareX#487]
Hi, I have a suggestion for ShareX:

- Ability to start auto-capture after program starts, via a checkbox in the advanced options

So the idea would be:
1.) Set the options for after capture+upload tasks, destinations, etc. as you would normally do
2.) Go to the advanced options in application settings to enable auto capture after program startup (using the currently set auto capture settings)
( 3.) It must be possible to have this functionality without a user ever noticing it, so no popups/sounds )

Is this something that can be added?

**Comment by Jaex** [comment]
It already exist: ![](http://i.imgur.com/FrLZ0Jc.png)
and then use workflow cli command to run it: https://github.com/ShareX/ShareX/wiki/Command-line-arguments

**Comment by kimisinnl** [comment]
Hi Jaex, thanks for the quick reply, only I start to feel a little foolish... I Really can't find this option, had spent an hour looking for it (and discovering that ShareX really is a nice product by the way!) before asking for the functionality.

I'm using the latest Windows build, and only have these options:
![image](https://cloud.githubusercontent.com/assets/10755776/5956164/b941dfa6-a7aa-11e4-8c25-2a2a2df92c9a.png)
The Task menu is missing, do I need to select some option somewhere else first?

**Comment by Jaex** [comment]
It is in Hotkey settings.

**Comment by Jaex** [comment]
`-StartAutoCapture` CLI command starts it.

**Comment by inkhsutesou** [comment]
Wow @Jaex very fast reply and quick response.  I'll use this !!

**Comment by inkhsutesou** [comment]
Ummm, if ShareX starts on Window's Start .. How would I use the CLI command ?  Could there be an additional configuration property ?

**Comment by Jaex** [comment]
Open Windows run then input `shell:startup` open it. There edit ShareX shortcut.
