### ISSUE TITLE
Please add screenshot preview customization

### ISSUE THREAD

**Issue by zxsleebu** [ShareX/ShareX#4875]
Hello. I'm glad, if you reading this. I think that screenshot preview customization will be very good feature.
For example, i want to copy the file of image in my clipboard by pressing middle mouse button on preview. Or copying the image to clipboard. Custom disappear time, its size, and more other.
I will be very happy, if you will ad this to ShareX. Thanks!

**Comment by Jaex** [comment]
All of those stuffs you asked is already exists.

**Comment by zxsleebu** [comment]
Please say, where it is? I searched everywhere, but didn't find. I'm so sorry that i'm blind :(

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/06/ShareX_rVIBkCmPW4.png)
