### ISSUE TITLE
make available in systray (for later copying) the list of last few recently uploaded

### ISSUE THREAD

**Issue by mailinglists35** [ShareX/ShareX#488]
sometimes (in fact, most of the time) I do not intend to copy _right_now_ the url into the clipboard.
it would be useful if the last few uploaded/saved files to be available as a list available from systray right click, and the when clicked the path would get copied into clipboard.

i used to use clip2net and i liked it's simplicity (0.9.4 version) but recent/later versions got bloated and buggy.
they had this pretty nice feature implemented like this: after hitting "publish", they showed a window and from there you could manually copy the url at the press of a button.
however looking at how far more advanced sharex is, a systray method seems to me more adequate.

thanks!

**Comment by Jaex** [comment]
There is one important problem, you want when clicked it will copy url but some people would like to open url when clicked. And I can't make it setting because need to be both open and copy functionality in menu and I can't add buttons to that menu items.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/rM4Yc2ps64.png)

**Comment by Jaex** [comment]
Now I'm thinking should I open Recent links menu automatically instead Capture menu. Which menu gonna be more useful to automatically open with tray menu.

**Comment by porkchop13587** [comment]
Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                                         From: JaexSent: Monday, February 2, 2015 9:52 AMTo: ShareX/ShareXReply To: ShareX/ShareXSubject: Re: [ShareX] make available in systray (for later copying) the list of last few recently uploaded (#488)Now I'm thinking should I open Recent links menu automatically instead Capture menu. Which menu gonna be more useful to automatically open with tray menu.

—Reply to this email directly or view it on GitHub.

**Comment by mailinglists35** [comment]
wow, you're pretty fast!!! :)
 my unfinished mockup drawing idea was to expand a second level submenu under each path, containing two submenus: "copy" and "open" :)
but right click is good, too. click to copy, right to open is okay if that involves less coding time ;)
