### ISSUE TITLE
changer JPEG encoder to mozjepg

### ISSUE THREAD

**Issue by raysar** [ShareX/ShareX#4883]
Mozjpeg is consider to the best jpeg encoder.
Is can avoid ugly jpeg artifacts in black and white caracter, that's very important to a print screen software.
I'm not capable to see what jpeg encoder is used in your code (because i'm a noob), but it produce very bad jpeg, and i suspect that is not mozjpeg encoder inside :/
Who can takes time to add this encoder? It's hard to do this upgrade?
Thank you <3
https://github.com/mozilla/mozjpeg

**Comment by Dreadaxe** [comment]
Exemple of use 
https://jpeg.rocks/

A function to ShareX for re-encodes image using a lossy algorithm could be very interesting.
