### ISSUE TITLE
Feature request: Direct image search online

### ISSUE THREAD

**Issue by Shpigorx** [ShareX/ShareX#4889]
Compare to lightshot: it has a feature to select region and click on button G opens google image search direct from screen selection. Just 1click search, no any addons or 100-steps moves. But Lightshot involve selected area modification, so you select first, then buttons appear and you can modify selection or click button.

![изображение](https://user-images.githubusercontent.com/12695405/85209360-e71d7380-b33f-11ea-93cd-a3ac77c90a5a.png)

**Comment by Jaex** [comment]
ShareX already supports it:

![](https://jaex.getsharex.com/2020/09/ShareX_7ufjfJnLYH.png)
