### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by mailinglists35** [ShareX/ShareX#489]
I was trying to draw a mockup for issue #488 when i encountered this error (pasted below):
several drawed lines and text were lost, but program continued functioning.

the error occured after I selected an area for cutting, then pressing the "ok" button - well not literally ok but that checked button.

using windows 10 build 9926 64 bit

http://i.imgur.com/y1RoteR.png

can't figure out how to paste correctly this text below

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DivideByZeroException: Attempted to divide by zero.
   at Greenshot.Drawing.TextContainer.Transform(Matrix matrix)
   at Greenshot.Drawing.DrawableContainerList.Transform(Matrix matrix)
   at Greenshot.Drawing.Surface.ApplyCrop(Rectangle cropRectangle)
   at Greenshot.Drawing.Surface.ConfirmSelectedConfirmableElements(Boolean confirm)
   at Greenshot.ImageEditorForm.BtnConfirmClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at Greenshot.Controls.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ShareX
    Assembly Version: 9.6.1.0
    Win32 Version: 9.6.1
    CodeBase: file:///D:/Programs/ShareX/ShareX.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ShareX.HelpersLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/ShareX/ShareX.HelpersLib.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ShareX.UploadersLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/ShareX/ShareX.UploadersLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///D:/Programs/ShareX/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ShareX.ScreenCaptureLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/ShareX/ShareX.ScreenCaptureLib.DLL
----------------------------------------
ShareX.IndexerLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/ShareX/ShareX.IndexerLib.DLL
----------------------------------------
ShareX.ImageEffectsLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/ShareX/ShareX.ImageEffectsLib.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
MegaApiClient
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///D:/Programs/ShareX/MegaApiClient.DLL
----------------------------------------
System.Drawing.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.Design.dll
----------------------------------------
Greenshot.ImageEditor
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///D:/Programs/ShareX/Greenshot.ImageEditor.DLL
----------------------------------------
ShareX.HistoryLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/ShareX/ShareX.HistoryLib.DLL
----------------------------------------
ImageListView
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.0.0
    CodeBase: file:///D:/Programs/ShareX/ImageListView.DLL
----------------------------------------
Gma.QrCodeNet.Encoding
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.1.2
    CodeBase: file:///D:/Programs/ShareX/Gma.QrCodeNet.Encoding.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Jaex** [comment]
I can't fix Greenshot image editor problems.

**Comment by mailinglists35** [comment]
oh, it is not part of sharex? if it is developed by someone else, could you help raising attention to it's developer?

**Comment by Jaex** [comment]
Yes it is developed by someone else.

**Comment by mailinglists35** [comment]
do you think you could bring this to their attention? thanks so much!

**Comment by Jaex** [comment]
Their issue tracker was difficult to sign up. I couldn't sign up there. So I don't think so.

**Comment by mailinglists35** [comment]
i have got an unknown error at first, but then i setup my password in such a complex way until the line below the password field fills to the "very strong". after that, they finish the signup successfully.

**Comment by mailinglists35** [comment]
what version are you using? i'm submiting an issue now

**Comment by Jaex** [comment]
It was latest stable.

**Comment by mailinglists35** [comment]
filed bug 1743 https://greenshot.atlassian.net/browse/BUG-1743

**Comment by Lakritzator** [comment]
Jeax, the problem with the signing up has long long long been solved.
I'll have a look at it.

**Comment by McoreD** [comment]
Thanks @Lakritzator - long time no see! :)

**Comment by Lakritzator** [comment]
@McoreD Well, I have been busy... trying to start a new project which I am doing alone. (more on that another time)

Anyway, I can't reproduce it inside Greenshot 1.2.4.9 with cropping, but probably it depends on a few factors.
We do have a similar issue which we fixed for 1.2.5 (coming soon) documented here: https://bitbucket.org/greenshot/greenshot/commits/2c26d287ff4f5bd1cefc47ba11d67e950c86934a 
The missing cast caused the DivideByZeroException, maybe you can integrate this fix?

P.S.
Offtopic: I still plan to extract the Editor... :)
Soon... and I want to make it available as a NuGet package.

**Comment by Jaex** [comment]
I was merged until 1.2.4.10 version.
By the way how I'm doing merge is checking every single commit one by one then copying part of codes if required manually to required places. So it takes long time doing this manually because I must make sure not overwriting my changes and not missing any code and not copying not required places to keep library size small.

Now I don't think it gonna be possible to use Editor separately because of changes in UI:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/shm9qvIATm.png)
First one is "Save and close", second is "Close", and third is "Close and cancel tasks". Also save, copy, upload, print buttons using ShareX tasks and their settings too. Also tried to make UI more compact.
