### ISSUE TITLE
upload image fail

### ISSUE THREAD

**Issue by InvisibleLeVen** [ShareX/ShareX#4894]
Error message:
无法连接到远程服务器

Request URL:
https://api.imgur.com/3/upload

Stack trace:
   在 System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   在 System.Net.HttpWebRequest.GetRequestStream()
   在 ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by BreadBreadington** [comment]
The same thing has started happening to me recently.
Completely out of the blue, no updates/changes to config etc.
If I reauthenticate it will work for a few images then go back to this

**Comment by memefinderr** [comment]
same thing happend with me
