### ISSUE TITLE
Drag'n'drop for ShareX window [Enhancement]

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#490]
![2015-02-03_10-57-22](https://cloud.githubusercontent.com/assets/1897605/6016507/0f763c7c-ab94-11e4-9505-d7b65d5569f6.png)

**Comment by Jaex** [comment]
I was already tried it and there was some complications which I don't remember now.

So you must do right click Copy -> File.

**Comment by QuAzI** [comment]
Interestingly which complications were here.
What about directly drag'n'drop to browser, skype or other software? Inserting of images by dragging into MSWord looks like a charm.
Too many actions are necessary in order that every time to cause to open dialogue, to choose there copying, then to open dialogue of a choice of the file and to insert there the text. 
It is really good and necessary feature I think.

**Comment by Jaex** [comment]
I think reason was that you could drag and drop it to same area where you dragging which will cause it to re upload. But maybe I can ignore own dragging.

**Comment by Jaex** [comment]
I can't ignore drag and drop files to main window so I can't do it.
