### ISSUE TITLE
[Bug] Teknik link changed(orbroke), ain't working in Sharex.

### ISSUE THREAD

**Issue by hdpcshow** [ShareX/ShareX#4906]
Its now https://dev.teknik.io/?sub=upload but yea it ain't working (Error 404) in Sharex.

**Comment by Jaex** [comment]
https://help.teknik.io/API/v1/Upload says it is: `https://api.teknik.io/v1/Upload`

**Comment by JohnFlowerful** [comment]
Are you sure it's 404? You'll get 401 after an hour when your access token expires. Teknik is pretty much useless until sharex fixes #4533.
