### ISSUE TITLE
Mapping to Ctrl + Scroll Lock maps to Ctrl + Pause/Break

### ISSUE THREAD

**Issue by aybe** [ShareX/ShareX#4910]
I was trying to map screen color picker to `Ctrl + Scroll Lock` but in the software it is seen as `Ctrl + Cancel`.

Now when I try the shortcut, it is both assigned to `Ctrl + Scroll Lock` and `Ctrl + Pause/Break`!

However, if you press only Scroll Lock or Pause/Break, the software makes the distinction between both.

Thank you

**Comment by Jaex** [comment]
https://en.wikipedia.org/wiki/Scroll_Lock
