### ISSUE TITLE
No longer records video

### ISSUE THREAD

**Issue by roman02** [ShareX/ShareX#4912]
I used to be able to record but not anymore. Using Windows 10 Home, build 18362

Here's what the dev version produced:

ffmpeg version git-2020-04-26-1128aa8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 43.100 / 56. 43.100
  libavcodec     58. 82.100 / 58. 82.100
  libavformat    58. 42.101 / 58. 42.101
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 79.100 /  7. 79.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[gdigrab @ 000002cb8efde180] Capturing whole desktop as 1920x1040x32 at (0,0)
[gdigrab @ 000002cb8efde180] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1593697644.708318, bitrate: 1916940 kb/s
    Stream #0:0: Video: bmp, bgra, 1920x1040, 1916940 kb/s, 30 fps, 1000k tbr, 1000k tbn, 1000k tbc
[dshow @ 000002cb8efe2080] Could not find audio only device with name [Microphone (3- USB PnP Audio Device)] among source devices of type audio.
[dshow @ 000002cb8efe2080] Searching for audio device within video devices for Microphone (3- USB PnP Audio Device)
[dshow @ 000002cb8efe2080] Could not find audio only device with name [Microphone (3- USB PnP Audio Device)] among source devices of type video.
audio=Microphone (3- USB PnP Audio Device): I/O error

**Comment by Scrxtchy** [comment]
Adjust your audio device settings. The names of these might have been reset in a windows update (clears out the existing Device IDs typically). FFMPEG can't find the old names on the new list.
While an update might not have caused it, having a Microphone 3 means that you've gone through different device names often enough. Even as much as plugging a microphone into a new USB port can increase the number 

![image](https://user-images.githubusercontent.com/12771982/86453803-b25ae480-bd61-11ea-9fac-72d331bb6f6b.png)
