### ISSUE TITLE
Add support for AV1 in the Video converter

### ISSUE THREAD

**Issue by FozzieHi** [ShareX/ShareX#4914]
AV1 is a new video codec which delivers higher quality videos with smaller file sizes through better compression codecs.

More information: https://engineering.fb.com/video-engineering/av1-beats-x264-and-libvpx-vp9-in-practical-use-case/

**Comment by Jaex** [comment]
AV1 support in FFmpeg is in beta and not works properly, thats why I did not add it.

**Comment by FozzieHi** [comment]
This is a feature request, is this not the place for them? I see others in this Issues page.

**Comment by rudolphos** [comment]
Bump
