### ISSUE TITLE
Can you please make QR code decoding directly accessible?

### ISSUE THREAD

**Issue by skygate2012** [ShareX/ShareX#4918]
Currently when I press a hotkey to launch the QR code tool it will open the GUI for generating and decoding QR code. Is it possible to make this direct, like when I press a hotkey it goes straight to decoding from screen or image file?

**Comment by vassilyzaitsev** [comment]
skygate2012, you can use an AutoHotkey script if you don't wanna wait for ShareX to support this option.

I can write it for you, if you want.

It would be something like:

Shortcut:
Wait for window (Share X - QR Code)
Send Control Click (decoding from screen or image file)

**Comment by skygate2012** [comment]
@vassilyzaitsev Thanks! I had actually wrote an AHK script automating the GUI process, but it's not native experience so I thought it would be nice to have the feature supported natively.

**Comment by vassilyzaitsev** [comment]
Oh yes, definitely!
