### ISSUE TITLE
Save picture to own ShareX format

### ISSUE THREAD

**Issue by sobujbd** [ShareX/ShareX#4921]
What I think, After capturing an screenshot, save it as own ShareX format with compressing. Then user wish to edit or keep it. And export it as image.

**Comment by chrislockwood** [comment]
This would be useful in the event that you need to reannotate/edit an image, particularly should you need to tweak of remove previous ShareX mark-ups (arrows, highlighting, etc.).

**Comment by McoreD** [comment]
This is a great idea. In the package, we can store the png, and the json config for the png which can include any modifications.

**Comment by TheBestPessimist** [comment]
not stale

**Comment by rainsia** [comment]
Also request this feature to be implemented.

**Comment by TheBestPessimist** [comment]
👎

**Comment by anaCIRdes** [comment]
This feature would be very nice to have. Every day i use this great tool and i wish i could save annotations in own format to change it later.

**Comment by amabent** [comment]
Another request for this feature

**Comment by SuthasU-gHub** [comment]
Yes, please add the feature to save image editor project. Like "myProject.shx"
Then I can come back to re-edit the annotations, edit text, move text, etc.
Thank you.

**Comment by nabazgharib** [comment]
Another request for this feature

**Comment by PhillyMay** [comment]
I'd also like to see this feature getting implemented.

**Comment by lourdas** [comment]
Yes, this is a feature that is much needed.
