### ISSUE TITLE
Publish MSIX/APPX on the GitHub Releases or anywhere else Microsoft Store

### ISSUE THREAD

**Issue by felipecrs** [ShareX/ShareX#4923]
With the availability of this package, we could install it without using the Microsoft Store. Similar to how the Windows Terminal does at https://github.com/microsoft/terminal/releases.

Then, I would be pleased to convert the current ShareX listing in WinGet to use the MSIX/APPX instead. :P

**Comment by sylveon** [comment]
The msix version has multiple limitations that the normal installer version doesn't have

**Comment by felipecassiors** [comment]
> The msix version has multiple limitations that the normal installer version doesn't have 

That's true. But isn't a reason to do not publish the package once it's already being built.

**Comment by felipecassiors** [comment]
By the way, it would be interesting to have documentation on how the Store version of ShareX is limited. I personally don't know and therefore I don't know why the normal installer is better.

**Comment by sylveon** [comment]
Here's a non-exhaustive list:
- 64-bits only (therefore can't run on ARM64)
- No built-in support for the recorder devices, you have to manually download them from the internet
- No DNS changer
- No "Upload with ShareX" context menu entry

**Comment by felipecassiors** [comment]
Thanks! 

By the way, I believe "MSIX" apps can add entries to the context menu yes. Windows Terminal did it via  https://github.com/microsoft/terminal/pull/6100.

**Comment by sylveon** [comment]
We can't add global context menu entries. The upload with sharex context menu is global (shows up on every file you right click). We could use a shell extension for this but it's not worth the effort.
