### ISSUE TITLE
Minio Amazon S3 not working

### ISSUE THREAD

**Issue by Runabox** [ShareX/ShareX#4924]
I have everything setup right and it just doesn't work.

"Unable to connect to the remote server"

I am able to browse it if im using S3 Browser, but ShareX doesn't work.
![Annotation 2020-07-10 234157](https://user-images.githubusercontent.com/61383318/87215692-f708f180-c306-11ea-800c-a0c9ad9aed39.png)

Please tell me if im doing anything wrong. Thanks

**Comment by Jaex** [comment]
Did you tried toggling "Use path style request" option?

**Comment by Runabox** [comment]
Yes but that makes the link sharex.storage.runaa.tk which doesn't work @Jaex

**Comment by norfair00** [comment]
Bucket name added on domain
![image](https://user-images.githubusercontent.com/1060346/87730338-be19c280-c7c7-11ea-92ce-cc9cdd3c2fe7.png)
