### ISSUE TITLE
Restart incrementing labels

### ISSUE THREAD

**Issue by RheingoldRiver** [ShareX/ShareX#4926]
Hi, is it possible to restart incrementing labels over again at 1? Or if not could this be added? Thanks!

**Comment by Jaex** [comment]
Yes: ![](https://jaex.getsharex.com/2020/07/ShareX_eRUoR5ykyY.png)

**Comment by RheingoldRiver** [comment]
Sorry I mean, I click 1,2,3,4,5 then I want to label on the opposite side of my screen again 1,2,3,4,5 if I press `i` again could it restart at 1 or something?
