### ISSUE TITLE
[Feature request] Prevent accidental uploads on first run

### ISSUE THREAD

**Issue by matoi974** [ShareX/ShareX#4927]
When you take a screenshot for the first time, ShareX prompts whether or not you'd like to upload it online. The problem is, if you hit "Yes" or "Enter" by accident, the contents of your screen are now public, which may expose private information. There is no failsafe to prevent accidental confirmations. I would strongly suggest to either prompt at a more appropriate time (maybe at first run, before any screenshots can be taken?), or add a timeout before any of the buttons can be pressed, to prevent accidental uploads.
![image](https://user-images.githubusercontent.com/63289008/87255044-ce1c6400-c4a0-11ea-8817-2fe9e7db6d74.png)

**Comment by Jaex** [comment]
This added in latest release:

> Improved the “First time upload” dialog to save people from unintentional uploads: added big “Attention” text with red background and locked the “Yes” button for 5 seconds
