### ISSUE TITLE
Request: allow to exclude specific windows from capturing hotkeys

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#4929]
I use ShareX on both my PC and one that I sometimes remote-control using AnyDesk.
I have about the same settings of it on both.
But, when I use the hotkeys, the one that contains AnyDesk takes over, instead of the one that I control.

Please offer to exclude specific windows (AnyDesk in this case) from handling hotkeys.
Because of this, I have to disable hotkeys on the one that controls, and re-enable it when I'm done...

**Comment by AndroidDeveloperLB** [comment]
Why?

**Comment by AndroidDeveloperLB** [comment]
Please don't close it

**Comment by AndroidDeveloperLB** [comment]
Please don't

**Comment by livejamie** [comment]
I have the same issue this would be helpful for me.

**Comment by livejamie** [comment]
Similar requests: #6028 #4929

Could be a potential solution for: #3312 #3314 #3574

**Comment by AndroidDeveloperLB** [comment]
@livejamie These are actually good too. I use Carnac sometimes, and it offers to capture its window even though it's mostly transparent.
It could be useful to ignore windows of specific apps from being offered to be captured, as if they are not on top.

Here, though, I request to ignore the hotkeys when a window of some app is focused.

**Comment by livejamie** [comment]
Ah, my apologies.

**Comment by AndroidDeveloperLB** [comment]
@livejamie I think it's a good request too, though
