### ISSUE TITLE
绘图的箭头能否添加“任意多边形”？

### ISSUE THREAD

**Issue by wjingyuan** [ShareX/ShareX#4930]
截完图后想对图片进行标注，想实现如图所示黄色箭头的样子。能否增加一个**任意多边形箭头**的功能呢？

![image](https://user-images.githubusercontent.com/28554380/87299343-687eb500-c53e-11ea-8399-670b93a25e54.png)

**Comment by Fusseldieb** [comment]
@wjingyuan English, please!

**Comment by wjingyuan** [comment]
Sorry,my english is very terrible.SO,I hope you can understand what's my mean.

**Firstly**,Thank you for your work and Share X.It is really very good.

**Secondly**,I hope you can increase some functions.The effect is as shown.When I sign the image,I hope I can use arbitrary polygon arrow.

![image](https://user-images.githubusercontent.com/28554380/87329540-af35d480-c569-11ea-9850-e9eb9aad303b.png)

*shape like yellow arrow*

**Thirdly**,I can't use all kinds of skydrive that Share X built-in functions to upload image in China.But I can use some domestic skydrive such as Baidu SkyDrive,Tencent SkyDrive and Jianguo SkyDrive,and so on.So Whether it can support other picture bed In China?

**Comment by ImSeaWorld** [comment]
@wjingyuan You can use a `custom destination` and input API endpoints. Documentation here: https://getsharex.com/docs/custom-uploader

**Comment by Fusseldieb** [comment]
> Sorry,my english is very terrible.

It isn't that bad, honestly. I could understand you no problem.

**Comment by AaqibAhamed** [comment]
Can you explain everything in English.? .If you say everything in English it's easy for me.Bad English also OK....

**Comment by yfdyh000** [comment]
> Can you explain everything in English.? .If you say everything in English it's easy for me.Bad English also OK....

An arrow marking tool that allows turning points.

**Comment by AaqibAhamed** [comment]
can i update .NET entity framework version?
