### ISSUE TITLE
Print Screen hotkey works when some windows have focus, but not others

### ISSUE THREAD

**Issue by flatline-studios** [ShareX/ShareX#4932]
This is a super weird bug...

I'm using Windows x64 Pro 2004.

If I hit print screen (my `capture region` hotkey), while Vivaldi/Desktop/Thunderbird/Process Explorer... or a ton of other applications have focus, then everything works as it should do (I get the auto-predict sections screenshot selection tool).

However, if Adobe Acrobat Reader/XYplorer/FreeFileSync and some others have focus, then I get the regular Windows action of copying the screen to my clipboard.

Furthermore, if I use a different hotkey (or an additional one), say, CTRL+ALT+PRINT_SCREEN, then it works with any window in focus, as you'd expect.

I'm at a loss as to how to provide more information than the vague bits I have done here, so please let me know what more I can offer... There's no info in the debug log for when windows handles the print screen keypress, as is to be expected.

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/issues/3574#issuecomment-410439052
