### ISSUE TITLE
Command Line Upload to Twitter

### ISSUE THREAD

**Issue by tildebox** [ShareX/ShareX#4933]
How I can tweet a text with a gif or an image on Twitter with command line on Windows?

I type following line in the command line - **How I can also add text to my image or gif?**:
ShareX.exe "image.png" -task "Upload to Twitter"
..but get following error:
ShareX.exe : The term 'ShareX.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ShareX.exe "image.png" -task "Upload to Twitter"

**Comment by ilikepotatoes121** [comment]
you either need to go to ShareX's install location and do that command or put the full path in e.g. ``"C:\Program Files\ShareX\ShareX.exe" "image.png" -task "Upload to Twitter"`` would work

**Comment by tildebox** [comment]
Thanks for your reply.

But how I can add also a Twitter description text?

"C:\Program Files\ShareX\ShareX.exe" "image.png" -task "Upload to Twitter"
-> Just uploads without text.

**Comment by Victor1266** [comment]
> Thanks for your reply.
> 
> But how I can add also a Twitter description text?
> 
> If I upload with ShareX window a panel appears, where I can add a description text.
> 
> "C:\Program Files\ShareX\ShareX.exe" "image.png" -task "Upload to Twitter" -> Just uploads without text.

did you find out how to do this?
