### ISSUE TITLE
Sharex customization such as after capture tasks and hotkeys are reset to default after power surge

### ISSUE THREAD

**Issue by gtech6** [ShareX/ShareX#4934]
Hi, since installing Sharex I have made the following changes for convenience:

- (Hotkeys) Removed the full screen hotkey bound to Print Screen key
- (Hotkeys) Replaced the region screenshot hotkey to Print Screen key
- (Task settings > Capture) Hidden cursor in screenshots
- (Task settings > Region capture) Enabled multi region mode
- (After upload tasks) Enabled sending uploaded image URL to clipboard

I have found that the above settings will return after turning a PC off and on as normal, but when it comes to the PC turning off suddenly due to a power surge, those settings will not return on next PC boot up. I've had to deal with the loss of those settings several times these past few months and there is nothing I can do about the power surges. 

Is it possible for you guys to help the software retain its settings even if the machine faces a sudden power surge?
If not, is it possible to save my settings into a file locally so I can upload them onto Sharex whenever my settings get reset? Something like how Chrome offers to export and import saved login credentials.

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/issues/702#issuecomment-630541152
