### ISSUE TITLE
The Arguments field: What does "%input" mean? What other arguments are possible? 

### ISSUE THREAD

**Issue by ThinkALot** [ShareX/ShareX#4936]
I'm referring to this:  Task Settings / Actions / Add / Arguments

What does %input mean? 

What else can be written in the Arguments field? 

Does the order of the arguments matter?

For the many ShareX users who don't know much about programming, an explanation that is clear and simple would be most helpful. 

See the screenshot below.

Thanks.

![image](https://user-images.githubusercontent.com/2463204/87879795-40baa180-c9c3-11ea-815f-df10fa8f2630.png)

**Comment by Jaex** [comment]
> What does %input mean?

%input is replaced with file path of current screenshot file.
%output is replaced with current file path but using output file name extension, which can be handy if you are converting image file to another image file format and extension needs to be different.

All your other questions depends on which application you are trying to supply screenshot file path to. For example image editor apps can accept file path as argument to open it, so using %input only for arguments enough.
