### ISSUE TITLE
Image not copies to clipboard when "Open in Image Editor" is enabled

### ISSUE THREAD

**Issue by rogeriodec** [ShareX/ShareX#4938]
My workflow is simple:
I capture an image and I want to revise it in the editor. If I change something in the editor, I know I have to Ctrl+Shit+C to copy the modifications to the clipboard.
But even if nothing is changed, I still have to use Ctrl+Shift+C, even if the option "copy image to clipboard" is checked.
![image](https://user-images.githubusercontent.com/11199752/87883784-293de180-c9e0-11ea-853f-c7e634276f62.png).

So it seems that the editor kills the original copied image from the clipboard when it's activated, and this is not the correct behavior.

**Comment by Jaex** [comment]
You can press "Enter" and let tasks continue executing:

![](https://jaex.getsharex.com/2020/07/ShareX_wuVwpLri56.png)

**Comment by rogeriodec** [comment]
Ok, tks
