### ISSUE TITLE
FYI:  ICON MISSING IN FIREFOX ICON ROW (top of browser)

### ISSUE THREAD

**Issue by ab1kenobee** [ShareX/ShareX#4945]
Hello:

I am not able to get to SETTINGS.
For some reason ShareX has not installed an ADD-ONS ICON at top of FF browser.

Appreciate this extension.

Please advise for fix.

Thank you,

~ Alan

intercept007@gmail.com

**Comment by Jaex** [comment]
There is no settings, it just adds "Upload with ShareX" to right click context menu of images.
