### ISSUE TITLE
Allow Ctrl + Shift to be used in conjunction

### ISSUE THREAD

**Issue by iamdansker** [ShareX/ShareX#495]
I have tried manually creating this hotkey in the config, however it didn't work, i have however noticed that Alt + Ctrl works in conjunction however much hard to hold down at the same time.

I am moving over to ShareX from puush but i really liked the hotkeys used in puush, so i was wondering if it was possible to add the ability to use more than one modifier key with the exception of the one that already exists created by using right alt (shows up as ctrl + alt)

**Comment by Jaex** [comment]
You can already use ctrl + shift

**Comment by iamdansker** [comment]
Everytime i try, it just gets stuck at "ctrl + shift +" and never allow me to actually type the 3rd key, anything i am doing wrong here?

**Comment by Baegus** [comment]
It does work for me.

**Comment by iamdansker** [comment]
Never mind, figured out what was wrong, totally forgot i had only disabled pushing from puush, so i guess even if disabled, puush still holds on to the key combination.

Completely closing puush solved the problem and now to uninstall ^^, had left it on in case i would switch back, though after toying with ShareX, i am not definitely not switching back

My bad :P
