### ISSUE TITLE
Screen record no sound

### ISSUE THREAD

**Issue by ChayimEliazer** [ShareX/ShareX#4959]
Lately when recording screen it does not record sound of screen video recorded.

**Comment by Neurotoxin001** [comment]
Same issue on 13.2.1 and also video is lagging when sound recording is enabled

**Comment by Neurotoxin001** [comment]
13.4 still have this issue

**Comment by yashpalgoyal1304** [comment]
migrating over from #5369 

### Summary:
Sharex is not recording the audio

### Reproduction:
**Steps:**
1. open sharex
2. start screen recording
3. play some music
4. stop recording, and play the resultant file

**What happened:** Recording starts, but the resultant file doesnt contain any sound

**Frequency:** Mostly, very likely

### Settings: 
- Screen Recording FPS: 15
- Audio src: virtual audio capturer, and tried with microphone array too
- Audio codec: AAC 96k
- Video src: GDI grab
- Video codec: tried with mutliple

### Versions:
- Sharex version: 13.4.0\
.exe from https://github.com/ShareX/ShareX/releases/tag/v13.4.0
- Recorder Devices: default (0.12.10)\
but [latest version🡭](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases) is 0.12.11
- ffmpeg: default (version unknown)
- OS: Windows 10 1903

### Hardware:
- intel i5 and intel UHD 630
- Nvidia 1050Ti

**Comment by yashpalgoyal1304** [comment]
**Update:** \
The issue for me was due to "hotkey settings" which is not just hotkey, but whole workflow settings 🤕🤦‍♀️\
So, the settings i was setting in "general task settings" were not getting applied to the hotkey i set earlier for capturing full screen.

**Comment by yashpalgoyal1304** [comment]
**Update:** \
The issue for me was due to "hotkey settings" which is not just a simple hotkey, but whole workflow settings 🤕🤦‍♀️\
So, the settings i was choosing/making in "general task settings" were not getting applied to the "task settings for the hotkey workflow" i set earlier for capturing full screen.

**Comment by yashpalgoyal1304** [comment]
To verify if ur issue is due to the same underlying issue: 
1. choose the relevant audio source \
in task settings > screen recorder > screen recording options > audio source = **virtual audio capturer** for example
2. **MAIN STEP:** now try capturing NOT via hotkeys, but **via the UI** buttons i.e. **Capture** > **Screen Recording** and choosing a random region
![image](https://user-images.githubusercontent.com/19423063/107118009-2fc07780-68a4-11eb-93c5-c580540de17a.png)
3. play some audio (song etc) and stop the recording 5-10 seconds thereafter
4. watch the resulting file

the microphone on/off doesnt affect virtual audio capturer - which is as expected/intended (:
![dvWRrjXvFK](https://user-images.githubusercontent.com/19423063/107118346-8464f200-68a6-11eb-8fa9-88bd6e26f796.gif)

**Comment by yashpalgoyal1304** [comment]
@ChayimEliazer and @Neurotoxin001 can u test if above fixed the issue for u too or not??

If it doesnt fix the issue for you, then it will mean that u are facing some other issue too and hence these two arent duplicate.

**Comment by Neurotoxin001** [comment]
https://user-images.githubusercontent.com/39812401/107118556-cbe18300-6892-11eb-9a91-31d19204c09e.mp4

No sound + video is lagging (video is not lagging with sound off in settings). Btw I don't use hotkeys, I use mouse wheel click on ShareX icon (but with manual start like you showed result the same).

**Comment by yashpalgoyal1304** [comment]
okay @Neurotoxin001 - thanks for quick reply. so it means that my issue can be considered different. I will be copying over this diagnose over to my issue and closing that one - but without stating duplicate (:

**Comment by yashpalgoyal1304** [comment]
Oh botttt, u are pain in butt

Sent from Mail for Windows 10

**Comment by ChayimEliazer** [comment]
> To verify if ur issue is due to the same underlying issue:
> 
> 1. choose the relevant audio source 
>    in task settings > screen recorder > screen recording options > audio source = **virtual audio capturer** for example
> 2. **MAIN STEP:** now try capturing NOT via hotkeys, but **via the UI** buttons i.e. **Capture** > **Screen Recording** and choosing a random region
>    ![image](https://user-images.githubusercontent.com/19423063/107118009-2fc07780-68a4-11eb-93c5-c580540de17a.png)
> 3. play some audio (song etc) and stop the recording 5-10 seconds thereafter
> 4. watch the resulting file
> 
> the microphone on/off doesnt affect virtual audio capturer - which is as expected/intended (: ![dvWRrjXvFK](https://user-images.githubusercontent.com/19423063/107118346-8464f200-68a6-11eb-8fa9-88bd6e26f796.gif)

Solved

**Comment by ChayimEliazer** [comment]
@yashpalgoyal1304 
This is only to record external audio from mic but does not record original audio from file streaming

**Comment by ChayimEliazer** [comment]
> 

This is only to record external audio from mic but does not record original audio from file streaming

**Comment by ChayimEliazer** [comment]
> To verify if ur issue is due to the same underlying issue:
> 
> 1. choose the relevant audio source 
>    in task settings > screen recorder > screen recording options > audio source = **virtual audio capturer** for example
> 2. **MAIN STEP:** now try capturing NOT via hotkeys, but **via the UI** buttons i.e. **Capture** > **Screen Recording** and choosing a random region
>    ![image](https://user-images.githubusercontent.com/19423063/107118009-2fc07780-68a4-11eb-93c5-c580540de17a.png)
> 3. play some audio (song etc) and stop the recording 5-10 seconds thereafter
> 4. watch the resulting file
> 
> the microphone on/off doesnt affect virtual audio capturer - which is as expected/intended (: ![dvWRrjXvFK](https://user-images.githubusercontent.com/19423063/107118346-8464f200-68a6-11eb-8fa9-88bd6e26f796.gif)

This is only to record external audio from mic but does not record original audio from file streaming

**Comment by ChayimEliazer** [comment]
@yashpalgoyal1304 
Now confirmed that this issue is because it was installed from Microsoft Windows App store that is restricted installation of "Install screen recorder"
https://github.com/ShareX/ShareX/issues/4047

**Comment by Sicoval31** [comment]
Hi, I download  Sharex directly from github and ffmepg was directly DL by sharex.

**Comment by dimmduh** [comment]
Wow. I always thought no sound when recording screen = it's by design.
I clicked "Install devices" in Task setting and it works now
