### ISSUE TITLE
Automatic deletion (imgur)

### ISSUE THREAD

**Issue by Kocayine** [ShareX/ShareX#496]
Since when uploading to imgur there's a function to delete the image with a URL (which is already possible in ShareX as we know) I was thinking if a function to delete uploaded images after X amount of days automatically and 'silent' (in the background)?

I personally use ShareX as a fast way to show friends over IM chat something that's going on, on my screen, and those images I really wouldn't mind if got deleted. As I understand it, imgur should delete images that havent been accessed after 6 months but I go years back and find things I uploaded (not public) still being online..

**Comment by Jaex** [comment]
I'm not planning to add automatic deletion because something can go wrong and not auto delete and it will be security risk then.

**Comment by lupuleasa-core** [comment]
I am passing the first viewer the right to delete this image.
You must NOT delete this image.

The social experiment has begun.

https://i.imgur.com/kZ5wmPN.png (delete image: https://imgur.com/delete/B6cFxcRhXSUrh6N)

**Comment by Jaex** [comment]
When Imgur is blocked in my country even if I want, I can't delete it.

**Comment by lupuleasa-core** [comment]
German or Chinese?
