### ISSUE TITLE
Toolbar and very small icons.

### ISSUE THREAD

**Issue by luapfr** [ShareX/ShareX#4960]
I use a 1920x1080 monitor resolution and found the ShareX toolbar very small compared to my Windows icons and toolbar, I see that a size option for the Toolbar that could be controlled by size would be very interesting of the fonts,

   see this attached image for a better understanding.

![Small_ToolBar](https://user-images.githubusercontent.com/50739062/89178037-1b04cf00-d563-11ea-9ffa-96b08b50b51c.png)

**Comment by Jaex** [comment]
It already auto sized to be bigger, see mine is smaller:

![](https://jaex.getsharex.com/2020/08/ShareX_c87ZaG0qTl.png)

**Comment by luapfr** [comment]
what i realize is that yours only has a few icons, but the height of the bar is small like mine.

the interesting thing would be to increase the height of the bar to be the same as the windows taskbar.

**Comment by Jaex** [comment]
Can you try:

https://ci.appveyor.com/api/buildjobs/dt4cq51p5vdlghby/artifacts/ShareX-13.2.2-setup.exe

![](https://jaex.getsharex.com/2020/09/ShareX_xj5fKCD0B6.png)

**Comment by luapfr** [comment]
Now this toolbar is very good.

I'm sorry for asking you one more thing but as I have a problem with my eyes and I wear glasses the general settings are also small if it was possible to increase see

https://ibb.co/9vhvMw7

**Comment by StoopidoMan** [comment]
@Jaex, Is there a way to get a portable version of the Dev build?

**Comment by AndroidDeveloperLB** [comment]
I use v15. 
Are there any news about this?
Even the workaround of manually setting icons size works only on the toolbar buttons, but not in texts in various places of the app, such as on the "Application settings" screen, history, and others...

Can you please make it automatically scale everywhere, including icons and texts?
