### ISSUE TITLE
 Screenshot does not open

### ISSUE THREAD

**Issue by theendik** [ShareX/ShareX#4962]
After taking a screenshot, I can't open it.
Also, this screenshot does not appear in the save folder.
It started two days ago, the program has already been reinstalled.
How can this error be corrected?

Windows 7 x64
![sharex](https://user-images.githubusercontent.com/69191452/89272964-95a71a80-d647-11ea-99a2-68e8d77d9c51.jpg)

**Comment by Jaex** [comment]
You must enable saving to file:

![](https://jaex.getsharex.com/2020/08/chrome_Q100K1LJt7.png)

**Comment by theendik** [comment]
Really :)
thank
