### ISSUE TITLE
"After capture tasks" not working

### ISSUE THREAD

**Issue by zvit** [ShareX/ShareX#4967]
Everything worked fine until I installed ShareX on a new system. I chose my old "After capture tasks," Copy, Save, Show (see screenshot below) but all it's really doing is uploading to Imgur and saving the URL to the file (both of which I don't need.)

What is wrong?

![QGl17CwSIA](https://user-images.githubusercontent.com/9898388/89570554-078d8880-d82f-11ea-8639-f03a776323c1.png)

**Comment by Jaex** [comment]
You can override after capture tasks per hotkey. So you probably overridden it in your hotkey.

**Comment by zvit** [comment]
Solved it. You can't select "Copy image to clipboard" before it saved the image to a file.
So, by selecting this sequence, it now works fine:

![rZJiIJdRRK](https://user-images.githubusercontent.com/9898388/89576422-f137fa80-d837-11ea-9c42-8f3d654b23e4.png)
