### ISSUE TITLE
Cant register hotkey

### ISSUE THREAD

**Issue by RealAqua** [ShareX/ShareX#4982]
I'm confused right now, I've reinstalled any wiped EVERYTHING that was from leftovers of sharex and yet I can't register the hotkey to "Capture Region" with "Ctrl + Shift + C" please help me. 
![unknown](https://user-images.githubusercontent.com/69742708/90326214-9e56f500-df53-11ea-8bb9-fe6fb2936757.png)

**Comment by BopItFreak** [comment]
Did you try restarting your computer

**Comment by RealAqua** [comment]
Your fucking joking right? I’ve had this for months of course I restarted my pc.

**Comment by spacecabbie** [comment]
> Your fucking joking right? I’ve had this for months of course I restarted my pc.

https://medium.com/@teejeetech/etiquette-in-open-source-projects-f302b6e19c38
https://medium.com/@d4nyll/the-open-source-community-have-no-place-for-disrespect-70c85d473332

Seriously, go pay the devs 25-50 euro for the use of the product en then tell them they are fucking joking. And still demand support. @Scrxtchy Respect for not just closing and deleting the issue.
