### ISSUE TITLE
[Image Editor] Crop and Cut/Paste enhancement

### ISSUE THREAD

**Issue by beijingjazzpanda** [ShareX/ShareX#4986]
It is suggested to enhance the crop, cut/paste function in Image Editor :

- select the crop range by mouse, enter "Enter" key to crop the selection.
- select the crop range by mouse, enter "Delete" key to remove the selection from image (crop other parts except the selection).
- select the crop range by mouse, can Cut/Paste the selection in/out clipboard
- crop by move the resize node around the image

Those functions are very handy when crop and combine with other images. 
Many Thanks !

Example (by FastStone Capture) below :
![qUAYRsFVx9](https://user-images.githubusercontent.com/10892928/90369938-21389680-e09f-11ea-9ff6-34da45979957.gif)

**Comment by JoeTheSane** [comment]
Yes, something like Snag-It's Cut Out feature would be amazing!
