### ISSUE TITLE
[bug] Video Recording Mouse offset with windows scaling 

### ISSUE THREAD

**Issue by daslicht** [ShareX/ShareX#4987]
Hi,
when windows scaling is enabled (eg 150%) the mouse pointer is not recorded at the actual position.

Try setting windows scaling to 150%. 
Start video recording
cycle with the mousepointer around  and object on the desktop

Expected result:
the recording should show the mouse pointer cycling around an object on the desktop

Actual Result:
the mouse pointer is offset cycling not where intended

**Comment by Jaex** [comment]
Duplicate of #1329

**Comment by daslicht** [comment]
AWESOME ! Thank you very much!
Maybe add a note to the docs to prevent further duplicates
