### ISSUE TITLE
Can't record screen

### ISSUE THREAD

**Issue by MellowMaus** [ShareX/ShareX#4989]
Screen capture straight up doesn't work for whatever reason. I start the capture, but it doesn't actually start recording, then it just stops like it never happened. I've tried reinstalling both sharex and ffmpeg to no avail. I just updated to a dev build last night thinking that might help, and i guess it did something; this window popped up when trying to record, but it still doesn't work. Windows 10 Pro version 1909
![image](https://user-images.githubusercontent.com/67393961/90812641-49143e00-e2db-11ea-8a44-bffce5f11146.png)

**Comment by Frotty** [comment]
I suddenly can't record anymore, too.
