### ISSUE TITLE
Fast screenshots/burst shot

### ISSUE THREAD

**Issue by kamijoan** [ShareX/ShareX#4990]
A long time ago I used fraps to take screenshots of a lot of things but fraps just died at some point. One of the things I liked from it was that screenshots basically came out as many times as you pressed the hotkey but I can't do that on shareX because there's like a whole second of lag between screenshots.

Is there any configuration on shareX to be able to do this? or should this post be a feature request?

Thanks

**Comment by Jaex** [comment]
Decrease this:

![](https://jaex.getsharex.com/2020/08/ShareX_IccEeVcsej.png)
