### ISSUE TITLE
Override destination in workflow ignored

### ISSUE THREAD

**Issue by gpion** [ShareX/ShareX#4991]
NB: Maybe I've misunderstood something

I've created a workflow named _"Capture to google Photo"_
* Task: _"Capture region"_
* Checked _"override after capture settings"_ and set to _"Open in image editor"_
* Checked _"Override destinations"_ et set Image Uploader to _"Google Photos"_

I activate the workflow, select region , image editor opens. 
I make small editions, click on _"upload image"_

Problem is that capture is uploaded to the default uploader, not Google Photos

**Comment by gpion** [comment]
Hello @Jaex 
Does "closed" mean "will be fixed in upcoming release" ?

**Comment by gpion** [comment]
@Jaex  thanks for the quick fix!

**Comment by chrisweis** [comment]
It seems to me like this issue still exists in the current Microsoft Store version (13.5).
