### ISSUE TITLE
Sorry to ask but, Linux

### ISSUE THREAD

**Issue by spacecabbie** [ShareX/ShareX#4998]
Will it ever be supported are there any plans? Or is sharex strictly windows only ?

If this has been asked(can't image it hasn't)  i do apologize  i was unable to find any info searching online and the issues here.

**Comment by L1Q** [comment]
#336 #1515 #1572 #3110 #4365 #4639 also [FAQ](https://getsharex.com/docs/faq#will-sharex-be-released-on-linux-or-mac-operating-systems)
TL;DR: yes, strictly windows only

**Comment by spacecabbie** [comment]
> #336 #1515 #1572 #3110 #4365 #4639 also [FAQ](https://getsharex.com/docs/faq#will-sharex-be-released-on-linux-or-mac-operating-systems)
> TL;DR: yes, strictly windows only
Ok i am going to remove my internet connection now i should not be allowed on the internet.... I guess i am getting old.
Barrely visited the site just looked on github, and i realized now i searched in open issues ffs.... So sorry.

Ps. Dot.net 5 was supposed to drop mono. But i believe it got pushed back, unsure about that i am not uptodate there.

**Comment by tifDev** [comment]
Any plans to support Linux?
