### ISSUE TITLE
When the record video are too large, it will be damaged

### ISSUE THREAD

**Issue by CaptainHarryChen** [ShareX/ShareX#4999]
The record video are too large, it will be damaged. (Maybe the file > 5G, or 4G, I'm not sure...)
![QQ截图20200826145200](https://user-images.githubusercontent.com/29812003/91270892-f095e280-e7ab-11ea-9bb7-9ddf89e7f914.png)
![QQ截图20200826145215](https://user-images.githubusercontent.com/29812003/91270906-f55a9680-e7ab-11ea-8309-12cdb13d06fc.png)
It seems the damaged mp4 file lost some data at the beginning of the file, so that the video can't be identified.

**Comment by sylveon** [comment]
ShareX isn't for long recordings, you should use OBS for that

**Comment by CaptainHarryChen** [comment]
> ShareX isn't for long recordings, you should use OBS for that

- 

Oh, that's disappointing....................
![QQ截图20200827225451](https://user-images.githubusercontent.com/29812003/91458730-70a96e80-e8b8-11ea-976f-33c5f7df1114.png)


And, thanks for your advice.
