### ISSUE TITLE
New Feature to add OCR Support

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#500]
Would be cool to see a way to integrate the command line tool Tesseract OCR to be able to upload an image with text on it and have ShareX run the image through Tesseract OCR and then upload the image and then upload the text file that Tesseract OCR creates containing the text it read and detected from the image.

**Comment by Jaex** [comment]
While processing image having text output is complex workflow and I can't think easy solution for it. Probably there is many OCR software so it will be overkill to use ShareX for it anyway.

**Comment by jasondavis** [comment]
understand, just wanted to share the Tesseract OCR that I see is being integrated into some other projects on GitHub right now so thought it might be a cool addon...in my opinion ShareX is absolutely perfect as it is right now!  I have been using it for almost 5-6 years now and it is a piece of software that I use almost every single day!  So again thank you @Jaex for keeping the project alive these past years and sharing it with the world!

Everytime I see an update, I am just amazed at the software has evolved to be more awesome over and over again!   With that said, I can't wait to see what else you come up with in the future.  At the same time, I don't want the project to shed away to far from it;s main purpose and become some bloated piece of crap!  I am confidant that you will not allow that to happen though as you have only added awesome and useful features so far, so thanks again and look forward to the future of ShareX!

BTW I am constantly promoting the app to other people as I feel like it really is a hidden Gem!  So many people would love this app if they just knew it existed and more importantly knew just how powerful and how many feature it has!  It;s hard to teach people of all the good features though as people are lazy and wont take the time to discover and learn things...either way it;s there loss!  I will keep spreading the word though!

- Jason
- Twitter - @JasonDavisFL

**Comment by MzHub** [comment]
I was about to suggest this myself, so I'll at least give my 2 cents.

@Jaex, while I agree that OCR can get complex, I think you may be thinking of a different use case than what was intended here. OCR of photos and scans is a whole different world, but a much simpler use case - and in my opinion more useful for a tool like ShareX - is copying text from screenshots or other images to the clipboard.

I used to have an application for exactly that use case years ago, and I still miss it often. It could not read anything complex, but it handled normal fonts well. I would love to have that in ShareX behind another screenshot hotkey, as I'm already used to how ShareX works. I would rather not get another application for that.

I disagree that this functionality would be overkill, or out of the scope of ShareX, since there is already text and clipboard handling and uploading. To me it would make sense for ShareX to combine screenshot + text via OCR. As jasondavis said, Tesseract may be one option to look into.

However, I understand if this is not a high priority :)

**Comment by MzHub** [comment]
Here is another option, as used by Greenshot:
http://getgreenshot.org/faq/how-can-i-use-greenshot-for-ocr/

>For the Greenshot OCR (Optical Character Recognition) plug-in to work we are depending on a component from Microsoft called MODI (Microsoft Office Document Imaging). If this is installed Greenshot will activate the plugin (if installed) and you will have an OCR destination. If you select this destination the OCR logic from Microsoft will try to detect the text on the screenshot and Greenshot will place this on the clipboard. MODI can be installed as an option from the Microsoft Office 2003 / 2007 installer or as an option from the free Microsoft SharePoint Designer 2007 ( you can find a description and a link to download it under “method 2″ here: http://support.microsoft.com/kb/982760)

**Comment by MzHub** [comment]
@Jaex on the OCR endpoint idea, here are some free solutions that some users might be able to use:

Microsoft's Computer Vision API - https://www.projectoxford.ai/pricing - free quota 5,000/month
Google's Cloud Vision API - https://cloud.google.com/vision/pricing - free quota 1,000/month
HP's OCR API - https://dev.havenondemand.com/apis/ocrdocument - free quota ?

**Comment by anjdreas** [comment]
This would be great as a plugin to ShareX, or simply included out of the box.
My usecase is using ShareX to select a part of the screen, then copy the parsed text to the clipboard.

**Comment by anjdreas** [comment]
Update, I just tried Capture2Text from http://www.makeuseof.com/tag/5-best-ocr-tools-extracting-text-images/ .

I works pretty much like I want to, hotkey to start a rectangle selection, move mouse then mouse click to end rectangle selection. Parsed text is then copied to clipboard. It would be awesome to have something similar in ShareX, but obviously there are working alternatives out there.

**Comment by Jaex** [comment]
I added OCR as "Text capture" in capture menu:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/ShareX_Wt0oUgjp98.png)

It uses online API to do OCR and shows result like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/05/ShareX_2BrrQ7ixHb.png)

**Comment by rskvirskiy-lohika** [comment]
Really cool feature, thanks! 

But several suggestions:
1. "Optical character recognition" window opene after each capture, and user forced to select a text and paste to clipboard. Is it possible to add additonal option to just copy recignized text to clipboard (with predefined language in the settings?
2. Ctrl + A doesn't work to select all text in "Optical character recognition" window

Thanks in advance!

**Comment by trickbz** [comment]
Really cool feature, thanks!

But several suggestions:
1. "Optical character recognition" window opene after each capture, and user forced to select a text and paste to clipboard. Is it possible to add additonal option to just copy recignized text to clipboard (with predefined language in the settings?
2. Ctrl + A doesn't work to select all text in "Optical character recognition" window

Thanks in advance!

**Comment by GnstheGrain** [comment]
@Jaex 
> https://github.com/ShareX/ShareX/issues/500#issuecomment-219176246
May I ask what service provider the api is being used from ? thx

**warning on using 3rd-party OCR scanning service provider**
_while I do use the feature and appreciate it's integration to ShareX, I just wanted to remind users to consider that everything you scan using this API is sent directly to the provider (so avoid scanning password,passphrase,sensitive image, wallet address, qrcode, private key, etc...)_

@Jaex 
Are you aware if some on-premise or self-hosted solution exist to replace the use of the third-party's API for this ? Would be a great privacy enhancement.

**Comment by Jaex** [comment]
https://ocr.space
