### ISSUE TITLE
Out of nowhere, ShareX cannot bind my hotkeys anymore

### ISSUE THREAD

**Issue by mortenmoulder** [ShareX/ShareX#5000]
![image](https://user-images.githubusercontent.com/1304665/91292592-077e0a00-e797-11ea-8bff-db137ae402b0.png)

As you can see, all of my 4 hotkeys do not work anymore. Happened out of no where. I don't have OneDrive installed or anything like that.

Not really sure what to do here..?

**Comment by mortenmoulder** [comment]
After restarting (where Dropbox also starts), it seems like Dropbox is the culprit here:
![image](https://user-images.githubusercontent.com/1304665/91305059-c2fc6980-e7aa-11ea-9452-ada820650452.png)

I tried closing Dropbox including all processes (basically `taskkill /F /PID dropbox.exe`) but that didn't work either.

**Comment by DBVE** [comment]
Look like same issue in https://github.com/ShareX/ShareX/issues/5000
