### ISSUE TITLE
Not being able to use the PrtSc Button

### ISSUE THREAD

**Issue by syedhaiderijaz** [ShareX/ShareX#5001]
Hey been trying to get the PRTSC button working for my windows laptop no luck. Ive unistalled screensketch and disabled onedrive but the PRTSC button still wont work with sharex and other config works but not this. Sharex itself gives no errors?

https://pastebin.com/yqqctYFD

**Comment by DBVE** [comment]
I have this issue also. I've logged out to Windows OneDrive and then de PrtScr button is working normally.
If i am logged in I see a red square at the hotkey settings ( probably that the button is occupied). 

Snagit has an option to override it, see: https://support.techsmith.com/hc/en-us/articles/203731428

Is this also possible for ShareX?

FYI company policy is forced to my laptop to also backup the pictures folder.
