### ISSUE TITLE
Image not saved after adding annotions

### ISSUE THREAD

**Issue by romulopimentel** [ShareX/ShareX#5003]
So, the only similar issue I found was this 4 year old thread, already closed, but unsolved:
https://github.com/ShareX/ShareX/issues/1981

The very same thing is happening to me now.

What I do:
I hit PrintScreen, select the area, then select "Annotate" from the Quick task menu, add some lines, arrows, text, etc and then hit "Continue".

What happens:
Image (without annotations) goes to History, but as .bmp (note: I configured it to save as .png) and then no action is possible using right click (everything is grayed out)

If I skip the annotations part, and hit PrintScreen, select the area and select "Annotate", it'll save just fine as a .png file

I've attached the debug log below in case anybody is kind enough to check this issue. Thanks.
[20.08.28-192932 %pn.txt](https://github.com/ShareX/ShareX/files/5144394/20.08.28-192932.pn.txt)

https://pastebin.com/Vd246D0a

**Comment by mnaranjoc** [comment]
Checking your debug log I detected that before making the capture and editing it, something is triggering the "Open main window" event.

I opened ShareX and was able to reproduce the error by performing the following steps:
- Configure hotkey to show the main window with "q" key.
- Press PrintScreen
- Select Annotate
- Add some arrows
- Press q (the hotkey to show the main screen)
- Press the continue button
- Confirm that image in history is a bmp and without the arrows

Please check if you have configured a hotkey or a workflow that shows the main screen

**Comment by Jaex** [comment]
You must edit and add "Save image to file" to annotate option, if you want it to save when continue is pressed.
