### ISSUE TITLE
Suggestion: Add direct link option to OneDrive shared images

### ISSUE THREAD

**Issue by intelektor** [ShareX/ShareX#5005]
Other hosting services have it like Dropbox and GDrive.

It is also available on OneDrive but not available on Sharex.

It is found on "See Original" on OneDrive, screenshot (using Dropbox, the irony): https://dl.dropboxusercontent.com/s/t97tibph2iw12bs/2020Ox7cf.png

It would be great to have it!

**Comment by davidsarkany** [comment]
It's can help implement this feature. 
https://github.com/aploium/OneDrive-Direct-Link

**Comment by welpdx** [comment]
bump
this would be really useful

**Comment by campbell-reid-displayr** [comment]
I got tired of messy SharePoint URLs, so I built a clipboard tool that automatically cleans them up when you copy them. It runs silently in the background and replaces long redirect links with the cleaner direct versions.

https://github.com/campbell-reid-displayr/ClipboardCleaner
