### ISSUE TITLE
plz support giphy upload

### ISSUE THREAD

**Issue by klover5** [ShareX/ShareX#5009]
I saw this thread

https://github.com/ShareX/ShareX/issues/2157

but now giphy support api

so plz recontact giphy

and support giphy upload

thx

**Comment by CoopJax** [comment]
giphy support would be nice but can't you upload gifs to imgur?

**Comment by klover5** [comment]
> giphy support would be nice but can't you upload gifs to imgur?

someone cant see imgur image in someplace

**Comment by BIoob** [comment]
I would like this as well. Any update?
