### ISSUE TITLE
ge.tt login error

### ISSUE THREAD

**Issue by klover5** [ShareX/ShareX#5011]
![20200902_093627](https://user-images.githubusercontent.com/20735356/91919258-4284be00-ed00-11ea-85cc-3a12a282e9e6.png)

I cant login ge.tt uploader

**Comment by ghiki** [comment]
Yep, same here

![imagen](https://user-images.githubusercontent.com/854302/93687013-b540b800-faba-11ea-8041-e8d67bf40b25.png)
