### ISSUE TITLE
how can I add gif dither 

### ISSUE THREAD

**Issue by klover5** [ShareX/ShareX#5013]
![20200902_095752](https://user-images.githubusercontent.com/20735356/91920201-51b93b00-ed03-11ea-9352-889d9a1b27da.png)

I wanna use 
"bayer:bayer_scale=3"
dither mode

This is the best quality dither mode in gif

how can I use it?

**Comment by Scrxtchy** [comment]
As per the referenced issue listed above (and it's several edits). This feature currently does not exist in ShareX, however I have created a pull request that may potentially be merged in a future version to allow changing the bayer scale.

Until then, altering the bayer scale will not be possible

**Comment by klover5** [comment]
> As per the referenced issue listed above (and it's several edits). This feature currently does not exist in ShareX, however I have created a pull request that may potentially be merged in a future version to allow changing the bayer scale.
> 
> Until then, altering the bayer scale will not be possible

thx a lot
appreciate it

u r awesome handsome beautiful

**Comment by ihyppolitec69** [comment]
How can I help
ihyppolitec@outlook.com 
 
  On Thu, Sep 10, 2020 at 12:01 AM, klover5<notifications@github.com> wrote:   



As per the referenced issue listed above (and it's several edits). This feature currently does not exist in ShareX, however I have created a pull request that may potentially be merged in a future version to allow changing the bayer scale.

Until then, altering the bayer scale will not be possible


thx a lot
appreciate it

u r awesome handsome beautiful
