### ISSUE TITLE
Teknik file uploader giving "URL is empty." error upon upload with the new pre-release 13.2

### ISSUE THREAD

**Issue by ItsCubeTime** [ShareX/ShareX#5015]
Im using ShareX portable, fresh install.

To reproduce, download ShareX portable from here:

https://github.com/ShareX/ShareX/releases/tag/v13.2.0

Set the file uploader to Teknik and get an authorization key in the destinations settings window.

Attempt doing some video recordings, and click "Yes" on the prompt where it asks if you want to upload to your file host or not.

You wont get any link in your clipboard like you usually do either, so its not a false error

Other uploaders like imgur seems to still work fine, I suspect this is related to the changes  done here by uncled1023 : https://github.com/ShareX/ShareX/pull/4995

Then it will look like this: https://imgur.com/a/g9LgRc6

Log: https://pastebin.com/gp5Eg3y8

**Comment by Jaex** [comment]
@uncled1023 oauth response not contains refresh token so ShareX unable to refresh it.

**Comment by Jaex** [comment]
fixed in #5021

**Comment by ItsCubeTime** [comment]
@Jaex  Sorry for asking this in the wrong place but, do you think you can update the pre-release version on getsharex.com with a build that includes the #5021 fix?

Or are there any other places where I can get  prebuilt versions?
