### ISSUE TITLE
[Bug] Sometimes ShareX captures an invalid region.

### ISSUE THREAD

**Issue by Jonatino** [ShareX/ShareX#5018]
I've noticed this has started within the past couple months where I'll take a normal screenshot and ShareX only captures like 1/100th of the original region.

1:
Expected screenshot:
https://dl.dropboxusercontent.com/s/889i2qsalrz5t5b/java_LC6DkDgWC1.png

Actual screenshot:
https://dl.dropboxusercontent.com/s/1sovtow1w7xhq36/java_BOOcn7ioq7.png

2:
Expected screenshot:
https://dl.dropboxusercontent.com/s/s3j19r3pl33jfjt/chrome_p2YKu2RPr0.png

Actual screenshot:
https://dl.dropboxusercontent.com/s/if8yden5gpnp9ao/chrome_MnlnC3w9U3.png

3:
Expected screenshot:
https://dl.dropboxusercontent.com/s/izu1obd66442x84/GTA5_755j76CRX2.jpg

Actual screenshot:
https://dl.dropboxusercontent.com/s/izkrjw7eh9pbk33/GTA5_FIGErFIBtp.png

This is a intermittent issue, happens about 20% of the time I screen shot. I haven't found out a reliable way to reproduce it.

**Comment by Jaex** [comment]
You are capturing by clicking I think. But after press mouse button down you moving cursor before releasing the button, therefore capturing the region.

**Comment by Jonatino** [comment]
> You are capturing by clicking I think. But after press mouse button down you moving cursor before releasing the button, therefore capturing the region.

Yeah I am. I usually press ctrl + printscreen then click the area/window I want captured. Would it make sense to change that event to wait for button down instead of button released to capture?

**Comment by Scrxtchy** [comment]
> Would it make sense to change that event to wait for button down instead of button released to capture?
There's a setting for Multi Capture Mode (formerly Quick Capture) which you currently use. It's bound to Q on the keyboard when capturing, or you can find it in the capture overflow menu
![image](https://user-images.githubusercontent.com/12771982/92325042-ba4d4280-f08a-11ea-902d-63e95204b8cb.png)

With this enabled, captures are not taken when the mouse is lifted, but instead when you double click on a capture zone or press enter
