### ISSUE TITLE
Show ShareX Processing

### ISSUE THREAD

**Issue by keeganatorr** [ShareX/ShareX#5020]
Please add in functionality that shows the percentage of the progress of background processes.
If I make a screen recording and stop the recording process, there is no visual feedback showing how long the processing time is going to take.

**Comment by Jaex** [comment]
Currently tray icon tooltip shows progress:

![](https://jaex.getsharex.com/2020/09/XH6rhmrfKX.png)

I'm planning of showing it as number tray icon in future.

**Comment by Zero2003** [comment]
@Jaex Maybe make the current encoding icon small and put it on the top left of the number so you can visually tell the difference.
Or you can make the background of the number icons a little different. You know how it's current a blue background on upload? I would suggest making it something like this:
Blue background = encoding
Green background = uploading
Just my thoughts, hope you find it useful or it leads you to think of something better
