### ISSUE TITLE
ShareX --> Tools --> Image Editor --> [Problem!] - No Zoom In OR Zoom Out

### ISSUE THREAD

**Issue by arindam0708** [ShareX/ShareX#5025]
The **'Image Editor'** can be used to either _edit the screenshots or edit the photo which is been copied to your clipboard._
In scenarios where the image which is present in the clipboard is bigger than the resolution of the display. The application (ShareX --> Image Editor) just chooses to display the centre of the picture.
**There's no way to scale down the image as per our needs. Its is always on 100%**

At some point the users might like to see the whole picture on the screen so they might be able to do the necessary actions they want to. **Like Cropping a picture which is bigger than the resolution of your laptop is just something kind of impossible to be done just using trackpad**. Using a mouse, by holding the middle button it is scrollable, yet it's not just proper!

The developers can add an option to preview the images in the Image Editor at 100%, 75%, 50% and so one. Or use a shortcut like Cltr + (Up or Down) using mouse/trackpad to zoom in or zoom out the image. 

I'm a student and this single application is just a lifesaver. And truly define what productivity application should mean.
The problem I find very frustrating is... at times I used a pdf file, copy the image from that pdf (which is basically the whole page), then use ShareX for cropping and making notes using the bits and pieces from them. _**But cropping the images is not the smoothest experience. My laptop resolution is less than the actual picture. If there was an option to preview the image (copied in the clipboard) at a smaller scale than cropping would have been a much easier job.**__

**Comment by yashpalgoyal1304** [comment]
this issue should be closed as a duplicate of #2325 
please search for duplicates before filing the issues

**Comment by ivolake** [comment]
+1 to have a zoom feature.

**Comment by vpr2k1** [comment]
it's still no zoom in Sharex??? WTF

**Comment by anyfactor** [comment]
+1
