### ISSUE TITLE
Can you add a function to name subfolders based on the current quarter of the year instead of just year or month?

### ISSUE THREAD

**Issue by ars4l4n** [ShareX/ShareX#5026]
Googled it but didn't see anything doing it yet

I found some powershell lines in this thread that I tried to copy pasta but got an error that they weren't supported

**Comment by Thundercraft5** [comment]
Hello, I've just run across this issue while trying to figure out a workaround for this. So far I've tried using an after-task script which renames the file using a placeholder, but it does not work as ShareX will throw an error as it cannot find the file.

**Comment by Thundercraft5** [comment]
Actually, there is a workaround which works! 
You need to create an environment variable (in my case `CURRENT_QUARTER`. After setting it to something (for example `Q1`), you need to put `%CURRENT_QUARTER%` where you wish to use it (example: Subfolder pattern). 

Make sure to restart ShareX, and it works perfectly! The only thing you need to do is have a script update `CURRENT_QUARTER` every 3 months.

**Comment by ars4l4n** [comment]
@Thundercraft5 Can you give me step by step instructions on how to implement this solution? Thanks for the effort.

**Comment by ars4l4n** [comment]
@Thundercraft5
Or honestly, I'm not even sure if I want this solution at this point. See, originally I wanted this solution to reduce the amount of clicks I need to do to navigate my image folders compared to creating monthly folders and because I felt like splitting up screenshots into this many months felt wrong, because when thinking of when I made a screenshot I wouldn't think "at month x in that year" but rather "towards the beginning/middle/end of the year". On top of that, there'd be months when I'd barely take any screenshots.
On the other hand, I've noticed that even when using an NVME SSD my PC takes multiple seconds to load up folders with that have dozens of image files. So I'm thinking to myself if it's even worth going for larger folders.

**Comment by Thundercraft5** [comment]
@ars4l4n Here's my configuration for the subfolder pattern: `%y\%CURRENT_QUARTER%\%mo - %mon\%y.%mo.%d`

Steps I used:
1. Go to Windows search > Edit System Environment variables > Environment variables 
2. New... > Create new variable named "CURRENT_QUARTER" with the value of your choice (`Q1` in my case) > Save
3. Save the subfolder pattern, then restart ShareX
4. (optional) Go to the task scheduler and create a new task at logon using this command (default `powershell` command could also be used, but I haven't tested): `/c start /min pwsh -WindowStyle hidden -noLogo -ExecutionPolicy unrestricted -noProfile -file "C:\<Your script path>\Update-QuarterlyVariable.ps1"`

**Comment by DasDunkel** [comment]
Had to jump in;
@ars4l4n 
> On the other hand, I've noticed that even when using an NVME SSD my PC takes multiple seconds to load up folders with dozens of image files.

An NVMe should be able to load a folder with *thousands* of files basically instantly, the fact that it is taking *multiple seconds* is beyond concerning, and you should both check the health of your drive, and backup anything important, because I get the feeling it's nearing the end of it's life.

I tested in a VM with only 2 cores and 4GB RAM, and it loaded a folder with 10,000 files instantly.

**Comment by ars4l4n** [comment]
@DasDunkel 
I updated my Samsung Magician (hard drive software) and accepted the software's prompt to download a driver for one of my SSDs and that seemed to have fixed the issue. Folders with any amount of images load up in about 0,5-1s now. Thanks for the tip.
