### ISSUE TITLE
Add "beta" or "pre-release" to the changelog

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#5029]
I love the changelog, thank you --> https://getsharex.com/changelog/

Can you please add behind it if it's a pre-release or latest version? This is easier for the users.

An example:
![PdcyxoFoOF](https://user-images.githubusercontent.com/12443285/92737830-be73ab80-f37b-11ea-82da-bcf7d0ad9eb6.png)

**Comment by McoreD** [comment]
Hi, we will instead ensure Change Log always points to releases rather than pre-release/beta versions. Our intention is not to point to final releases in Change Log.
