### ISSUE TITLE
De-elevate after install/update

### ISSUE THREAD

**Issue by Efreak** [ShareX/ShareX#503]
ShareX requests elevation for the installer/updater, then runs it. It then runs the new version of ShareX with full elevation. I have verified this in Task Manager (just add the elevation column). The installer (or better, ShareX itself) should de-elevate on running the new version.

**Comment by Jaex** [comment]
I can't find anything about running non elevated in here: http://www.jrsoftware.org/ishelp/index.php?topic=runsection

**Comment by Efreak** [comment]
More research shows that it is very difficult to directly de-elevate; NSIS has a plugin for doing so, however INNO doesn't, and the only direct way I've seen [is apparently a bug](http://mdb-blog.blogspot.com/2013/01/nsis-lunch-program-as-user-from-uac.html?showComment=1388694317801#c939517856791332836) is apparently a bug. However, you can add a scheduled task with no triggers, call it manually, then remove it (I think this can be done automatically).

Alternatively, the application can set 'everyone' write permissions on the application folder, or install it to programdata (chrome does this; it's annoying but it works), so that updates don't need to be run as administrator.
