### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by iBeny** [ShareX/ShareX#5030]
Hi !

Where do we configure the captured or recorded shots name in ShareX ?

Best regards
Beny

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/09/ShareX_4ibCP6INpR.png)

**Comment by iBeny** [comment]
Thanks a lot ! I haven't bothered to check there because I interpreted "Upload" as an "Internet" upload procedure which I don't do. I only wanted to save the capture in my pc so... some GUI menu naming to change/modify from your part too isn't it ? 

Best regards
Beny
