### ISSUE TITLE
History in exports

### ISSUE THREAD

**Issue by mythofechelon** [ShareX/ShareX#5031]
In version v13.2.1 (latest as of writing), using `Application settings...` → `Settings` → `Export...` and `Import...` contains the task history even when the checkbox `History` is unticked.

Is this expected?

I know there's a warning note saying that the file might contain your upload history but why else is the checkbox there?

Thanks.

**Comment by Jaex** [comment]
It is for History.json file which is what History window uses. Task history is not stored there.
