### ISSUE TITLE
Error while saving screenshot

### ISSUE THREAD

**Issue by potatto99** [ShareX/ShareX#5034]
![image](https://user-images.githubusercontent.com/43730820/92963009-18569d00-f472-11ea-8a60-c2c1da9c259f.png)
![image](https://user-images.githubusercontent.com/43730820/92963101-37edc580-f472-11ea-99dd-dd794c27f723.png)

**Comment by Jaex** [comment]
We can't do anything about it if something in your PC blocking ShareX access to that folder. Most of the time anti virus software.

**Comment by ziemniok99** [comment]
It is only happening on 13.2.1 version, I changed it to 13.1.0 back and it stopped appearing

**Comment by Dariusz1989** [comment]
@ziemniok99 Its probably this > https://github.com/ShareX/ShareX/issues/5035

**Comment by DW01** [comment]
Reporting in to confirm I'm having the same issue--13.1.0 works fine but 13.2.1 throws the exception. If it were purely an issue with antivirus, downgrading to 13.1 wouldn't have fixed the problem. Something's likely up with how 13.2.1 writes image data to files in its directory--has anything changed on this front between versions?

**Comment by philosowaffle** [comment]
Same issue for me.  After upgrade to 13.2.1 ShareX can't write to the network drive.

**Comment by Dariusz1989** [comment]
You guys can use network paths to save in mean time. something like `//192.168.1.10/share/etc/etc/etc`

**Comment by ziemniok99** [comment]
@Jaex pinging for his answer

**Comment by Violetnred2** [comment]
same problem here. saving worked fine with many different settings until the latest update.

**Comment by Jaex** [comment]
99.9% of times people who got this error is using Avast anti virus. Rarely another anti virus software.
And every single time they telling it was working before now don't, so it is certainly to do with ShareX and not Avast. After they add ShareX to proper whitelist section (a lot of times they add it to wrong whitelist section) then problem resolves and they understand they were wrong. But I'm just tired of arguing about it every single day because hundreds of Avast users keep coming with same issue.

**Comment by Violetnred2** [comment]
ok, i don't use Avast, but i did add ShareX to my antivirus' exception list and now saving works.

**Comment by Dariusz1989** [comment]
@Jaex Yep, I've whitelisted it and now I can browse network drivers. So maybe its worth adding a [?] Button next to browse with some information for users to fix the issue on the spot?

Like - Please white list ShareX in ur antivirus software as it can block access to network paths?

**Comment by philosowaffle** [comment]
Sounds like this is a common question you get, but its not something I've ever run into till now (have used sharex for a couple years). Perhaps this info would be a good addition to the Documentation or the FAQ section?  Maybe its already there, and I'm just blind, but if not, we should get it added.

**Comment by Dariusz1989** [comment]
Its also a bit odd, I had avast for years and it never was a problem before so... bit weird!

**Comment by osworx** [comment]
1.having same errors when saving file
2. Win10 (32bit) tells me that it may the Antivirus (using only Win internal solution - no external!) or the user write permissions
3. had this error also before the latest 13.2.1 release (from teh 1st install a few months ago)

So telling people that the "Antivirus" solution may the "eval" is not true.
And what about the permission issue - never had such before!

If oyu ar enot able to fix that, I will unstall it and use another (commercial) sw.

**Comment by Jarod997** [comment]
I never used to have this, but recently it popped up. As I was having other windows problems, I formatted my drive and did a fresh install of my basic programs. This is still coming up. I don't have any anti-virus other than built-in (for the moment).

**Comment by osworx** [comment]
Ah, we need a machine (bot) for answering nonsens!
What about a solution from the developer??

**Comment by tieubinhco** [comment]
Hello everyone, try installing the newest ShareX 16.1 on Microsoft Store, it works. I installed ver 16.1 by .exe and faced the same issue, the version on MS store does not have the issue.
