### ISSUE TITLE
Warning from Norton 360: "Filename: sharex-13.2.1-setup.exe - Threat name: SONAR.Heuristic.170"

### ISSUE THREAD

**Issue by hendratno64** [ShareX/ShareX#5037]
When I installed ShareX 13.2.1 on Windows 10 (which comes with Norton 360), Norton issued a warning: "Filename: sharex-13.2.1-setup.exe - Threat name: SONAR.Heuristic.170".

The screenshot is as follows:

![image](https://user-images.githubusercontent.com/6907983/92994263-1dbff000-f523-11ea-930e-064069f2fc0b.png)

**Comment by Elle199** [comment]
This is most likely due to the .exe file not being signed with a publisher and Norton not liking that.

**Comment by McoreD** [comment]
Got this on my own work laptop. Please allow the exe through Norton a couple of times and it will go away.
