### ISSUE TITLE
The large size of PNG files

### ISSUE THREAD

**Issue by user6323** [ShareX/ShareX#504]
Hello.
I notice .png sometimes get very large.
Example: https://i.imgur.com/GiW0kEV.png - 752kb

In settings i see jpeg quality only. I cant use jpeg because it changes color (example - https://i.imgur.com/pDVbDbU.png )

I try to shrink png - and i saved 70% ( https://i.imgur.com/kZiGxBM.png ) .
Can you do something to make .png smaller?

**Comment by Jaex** [comment]
You can use actions to run CLI like this: http://optipng.sourceforge.net/

![](http://i.imgur.com/yFfGMQB.png)
