### ISSUE TITLE
Help: How to make the Image Editor buttons icon bigger? (because bigger is better)

### ISSUE THREAD

**Issue by StoopidoMan** [ShareX/ShareX#5040]
![image](https://user-images.githubusercontent.com/71223069/93021858-4ebd2500-f5f6-11ea-9cda-79642e64b2af.png)

For someone who uses glasses and is on a FULLHD monitory the buttons are too tiny, is there a way to change the icons manually, I use the portable version

**Comment by Jaex** [comment]
duplicate of #4960
