### ISSUE TITLE
Copy an arrow or anything else we insert

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#5044]
I use the arrow or rectangle, but sometimes I like to copy it. So I have the exact same size. This does not work. 

Is this something you can add or can tell how to copy it?

**Comment by worldsdream** [comment]
Thank you @Jaex !!

**Comment by worldsdream** [comment]
@Jaex I did update to the latest version. When I create an arrow, and I copy it and paste it. I don't see the arrow, but I do see X Y W H. 

![info](https://user-images.githubusercontent.com/12443285/98441249-6c41d300-20fd-11eb-91e6-c99f4608ba55.png)

**Comment by Jaex** [comment]
Don't copy and paste instead use duplicate (ctrl + d).
