### ISSUE TITLE
Error when attempting to record screen with audio merged from two sources

### ISSUE THREAD

**Issue by ErnestUTN** [ShareX/ShareX#5045]
I am using a custom command, that used to work before, that records the screen and merges the stereo-mix and the microphone input into one. Here it is:

### Additional command line arguments:
`-f dshow -i audio="Jack Mic (Realtek Audio)" -f dshow -i audio="Stereo Mix (Realtek Audio)" -filter_complex "[1:a][2:a]amerge=inputs=2[a]" -map 0 -map "[a]"`

### Command line preview:
`-rtbufsize 150M -f dshow -framerate $fps$ -i video="screen-capture-recorder" -f dshow -i audio="Jack Mic (Realtek Audio)" -f dshow -i audio="Stereo Mix (Realtek Audio)" -filter_complex "[1:a][2:a]amerge=inputs=2[a]" -map 0 -map "[a]" -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -y "$output$"`

### Screen recording options capture:
![ShareX_2020-09-15_14-52-22](https://user-images.githubusercontent.com/8976434/93247563-de80e180-f764-11ea-9d0c-570f10af5454.png)

### Recording devices:
![rundll32_2020-09-15_14-55-13](https://user-images.githubusercontent.com/8976434/93247547-d759d380-f764-11ea-99fc-74e4490e5b67.png)

**Note**: Mind you that the (Realtek Audio) next to Stereo Mix and Jack Mic still used to work fine

### Console error Full log:
```
ffmpeg version git-2020-05-15-b18fd2b Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200513
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enabl
e-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enab
le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enabl
e-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --
enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-l
ibvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom
--disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nven
c --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 45.100 / 56. 45.100
  libavcodec     58. 84.100 / 58. 84.100
  libavformat    58. 43.100 / 58. 43.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 81.100 /  7. 81.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
leaving aero onInput #0, dshow, from 'video=screen-capture-recorder':
  Duration: N/A, start: 331472.039000, bitrate: N/A
    Stream #0:0: Video: rawvideo, bgr0, 1600x900, 30 fps, 30 tbr, 10000k tbn, 10000k tbc
[dshow @ 000002204d317440] Could not run graph (sometimes caused by a device already in use by other application)
audio=Jack Mic (Realtek Audio): I/O error
```

### Short Error log
**[dshow @ 000002204d317440] Could not run graph (sometimes caused by a device already in use by other application)
audio=Jack Mic (Realtek Audio): I/O error**

### Things I checked
- Restarted the sharex app
- Checked that there weren't multiple instances of the app
- Updated to 13.2.1

Regards!!

**Comment by ErnestUTN** [comment]
bump. Nobody?

**Comment by mcrrobinson** [comment]
I have the same issue, there is a stackoverflow page with the same error but nothing there neither. I believe it's an ffmpeg issue as I am running ffmpeg commandline.
