### ISSUE TITLE
Add 2nd Imgur uploader

### ISSUE THREAD

**Issue by Dream-Cypher** [ShareX/ShareX#505]
Hello,
Is there a way to add a 2nd uploader for imgur, such that one could be configured for "user account" and the second could be "anonymous"?

I see I can set up one via "custom" to upload anonymously, but it doesn't provide the delete hash.

Thanks.

**Comment by Jaex** [comment]
You can't set 2nd Imgur uploader.

**Comment by Dream-Cypher** [comment]
Bummer. I was hoping there would be some way to retrieve the delete hash using the "custom" uploader option for anonymous uploads.

Thanks anyway.
