### ISSUE TITLE
Zoom can't see placed lines, arrows, rectangle and all others objects

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#5051]
Example:

1. Make a rectangle
2. Select an arrow and place it against the rectangle
3. We can't see the rectangle.

Please adjust this, that if we add a new object or move an object, for example arrow, we can see the rectangle.

![P8ztdPsPbf](https://user-images.githubusercontent.com/12443285/93461642-56761580-f8e5-11ea-976b-6f24bdfbe0dc.png)

**Comment by Vampire** [comment]
.

**Comment by Vampire** [comment]
Could someone please reopen this issue?
It is still relevant and annoying.

**Comment by Vampire** [comment]
Still the same with 13.7, please reopen

**Comment by worldsdream** [comment]
@Vampire I don't think the dev will fix this...

**Comment by Vampire** [comment]
Maybe he changes it, maybe a contributor changes it, maybe noone changes it.
But either way it is an extreme usage problem and should stay open as issue.
