### ISSUE TITLE
[BUG] Wrong presentation of mouse pointer with adjustet pointer size

### ISSUE THREAD

**Issue by boop5** [ShareX/ShareX#5055]
I've changed the color and size of my mouse pointer. When I take a screenshot the mouse pointer is scaled down to default size. This applies to the _preview_ and the actual picture.

----

So I didn't know how to properly screenshot the issue so I took them with my phone

Here a shot of my actual mouse pointer
![20200918_173404](https://user-images.githubusercontent.com/4655466/93617439-4427d480-f9d6-11ea-91a7-ecfa0ec52d48.jpg)

Here a shot when taking a screenshot with ShareX
![20200918_173413](https://user-images.githubusercontent.com/4655466/93617442-44c06b00-f9d6-11ea-83f5-3926a7646b2a.jpg)

I'm on Windows 10 Enterprise 2004 but I had the same issue on a lots of different patches and versions of Windows 10 and ShareX.

Here are the Windows 10 Settings for my cursor

![image](https://user-images.githubusercontent.com/4655466/93617596-7802fa00-f9d6-11ea-860e-87e9ad3d7ce5.png)

edit: typo

**Comment by datkat21** [comment]
I had the same problem and i fixed it by changing mouse size to 1

**Comment by HubKing** [comment]
> 
> 
> I had the same problem and i fixed it by changing mouse size to 1

That is not a "fix", because I need to use size 2.

**Comment by datkat21** [comment]
I myself use size 2 now and this is a problem. Here is a comparison between the screenshot ShareX takes and a picture I took with a camera:

ShareX's result
![ShareX_Small_pointer](https://user-images.githubusercontent.com/49850194/100344579-a983dd00-2fa6-11eb-876c-168bdce34366.png)

My camera's result
<img src="https://user-images.githubusercontent.com/49850194/100344625-bc96ad00-2fa6-11eb-87d7-37f27a0d62c4.png" width="48">

As you can see, the camera shows the 2 size cursor with its big white outline. When it comes to ShareX, it sticks with the 1x size and looks very weird and pixelated, unless I set the size to 1:

> Screenshot with 1 cursor size
>  ![image](https://user-images.githubusercontent.com/49850194/100344992-48103e00-2fa7-11eb-9c69-e4026cb212f3.png)
> 
> Screenshot with 2 cursor size (notice the weird pixelation in the cursor)
> ![image](https://user-images.githubusercontent.com/49850194/100344998-4ba3c500-2fa7-11eb-95b3-0bd0fec6ea49.png)

While I'm not sure how to fix it, I hope there should be a fix soon. 👍

**Comment by Jaex** [comment]
If I could I would fix it. But I also couldn't find any other screen capture app which managed to fix this issue.

**Comment by HubKing** [comment]
> 
> 
> If I could I would fix it. But I also couldn't find any other screen capture app which managed to fix this issue.

Would it be possible, at least, to add some sort of marker to make the mouse pointer/click more conspicuous? I think I saw screen captures in which the mouse pointer was highlighted by a yellow circle. The main reason why I wanted this to be fixed was that the mouse pointer was difficult to recognise in a 4K recording; if the pointer is somehow marked to be more conspicuous, I won't need the pointer to be exactly the same size as I see.

**Comment by Terrance** [comment]
I'm not sure if this eventually got fixed, as I've been using a size 2 mouse for a while and it had been rendering correctly in my screenshots, but as of today I'm seeing the scaling/pixellation as described above.

![image](https://user-images.githubusercontent.com/4025899/158075954-2a97ecee-7953-46c7-96c2-60c3811a1183.png)

**Comment by boop5** [comment]
@Terrance it never worked for me 
![image](https://user-images.githubusercontent.com/4655466/158076044-f208027a-0c13-450c-94bc-2ff66755a511.png)

**Comment by hybridherbst** [comment]
I believe the approach described here actually works – the registry value updates as expected when changing the cursor size.
- https://stackoverflow.com/a/63295870

Video:

https://user-images.githubusercontent.com/2693840/173633747-b0749ff0-06d8-4f3d-9a92-d6fdad863070.mp4

- the value "Computer\HKEY_CURRENT_USER\Control Panel\Cursors\CursorBaseSize" changes
- all the .cur/.ani files change accordingly - seems their files get regenerated and are placed in `AppData/Local/Microsoft/Windows/Cursors` in the correct size
  
![image](https://user-images.githubusercontent.com/2693840/173634347-ec55604b-8578-48f1-970a-ef1e17d6865b.png)

@Jaex hope that helps!

**Comment by hybridherbst** [comment]
Did a quick check of 13.7.2 Dev (it's awesome that one can update to latest dev from inside ShareX!) - seems that while the right icon is used, the size is still small.

**Comment by Jaex** [comment]
I was still working on it. Now I finished it. Can you try dev build again? I feel like bigger cursor is one pixel off because of manual hotspot guessing :(

**Comment by hybridherbst** [comment]
Nice, that works! Can confirm – looks like the cursor is offset to the left by 2px and to the bottom by 1px. Not a giant issue if you ask me but I understand it's not ideal.

Will this also be possible for mp4 capture via ffmpeg? Currently the cursor is still small there but I'm not sure if that is handled by ShareX or ffmpeg directly.

**Comment by Jaex** [comment]
> Not a giant issue if you ask me but I understand it's not ideal.

I'm not sure how to fix hotspot issue :(

> Will this also be possible for mp4 capture via ffmpeg?

FFmpeg does recording itself, so I can't fix it.

**Comment by hybridherbst** [comment]
Just did a quick test using OBS that might be interesting:

Seems that "DXGI Desktop Duplication" captures the cursor incorrectly but "Windows 10 (1903 and up)" captures the cursor at the correct size.

![image](https://user-images.githubusercontent.com/2693840/173706529-7673ee9f-00f9-40dc-9e1d-50f26c026b5b.png)

**Comment by Jaex** [comment]
@hybridherbst now I realized using cursor size from registry is not good solution either because some games have custom cursors with bigger sizes. So custom cursors broken now :(

Registry size:

![](https://jaex.getsharex.com/2022/06/chrome_cukhiJjscL.png)

Actual size:

![](https://jaex.getsharex.com/2022/06/PSXgwzzErW.png)

**Comment by Jaex** [comment]
I fixed custom cursor size issue but past 2 hours struggling to fix transparency issue.

Current custom cursor:

![](https://jaex.getsharex.com/2022/06/ffxiv_dx11_7s9n3iyzTk.png)

Actual custom cursor:

![](https://jaex.getsharex.com/2022/06/chrome_ZxXfxQQKev.png)

**Comment by Jaex** [comment]
I saw this in .NET source codes now:

![](https://jaex.getsharex.com/2022/06/chrome_yPgMBxWHrq.png)

So it was not exactly my fault. As last resort I used .NET way of converting cursor to bitmap for default size. That way transparency at least will be correct at default size for custom cursors.

@hybridherbst can you test dev build one more time before release, so we can be sure that somethings not broken with latest cursor changes.

**Comment by Jaex** [comment]
And now I have another problem: https://jaex.getsharex.com/2022/06/PathOfExileSteam_5tmSCeunXH.jpg

Cursor is drawn bigger in ShareX because Windows pointer size option is high, but in game cursor size never changes. But it was changing in another game. I really started to regret adding support for Windows cursor size because it is endless issues and workarounds that there is no hope of perfectly supporting it.

**Comment by hybridherbst** [comment]
Just tested, looking good! Cursor scale still works correctly after updating to latest dev build from within ShareX. Thank you! And sorry for the trouble with games, that is so weird...

**Comment by MiyagawaMizu** [comment]
this bug not fixed yet?
