### ISSUE TITLE
Feature Request: Add a "Presets" option for Screen Recording Options

### ISSUE THREAD

**Issue by zellchristensen** [ShareX/ShareX#5056]
It would be great if there was an option to store a given set of Screen Recording Options as a Preset. 
Sometimes I need to change the settings on the fly.
For example, using GDI Grab instead of screen-capture-recorder, or switching audio to None, or changing the framerate.
Sometimes certain options require additional or customized command line options for FFMPEG.
It can be a pain to remember which arguments need to be added/modified or more cumbersome to save them somewhere else by hand.
It would be great if there was an option to just save them all as a custom named preset and a way to easily switch between presets, maybe by right clicking the task icon or even having custom hotkeys for different presets.

**Comment by Jaex** [comment]
You can already do that by hotkey workflows.

**Comment by zellchristensen** [comment]
So I can!  For some reason it just didn't seem intuitive at the time as I kept trying to use the master settings and couldn't find the override option for individual workflows.  Looks like everything is set now!  Thank you!
