### ISSUE TITLE
Unable to record audio in screen record

### ISSUE THREAD

**Issue by onlytanmoy** [ShareX/ShareX#5057]
Hiya, I am using latest version of ShareX on my Win 10 laptop. Please let me know how to record screen with audio.

I tried with all the 3 audio sources as seen in the screenshot, no luck. Any solution?

https://imgur.com/a/B0kVJCi

**Comment by onlytanmoy** [comment]
@Jaex can you look into this please?

**Comment by Scrxtchy** [comment]
are you trying to record the audio from your computer or from your microphone.
There's an installer that adds the capability to use the the virtual audio capture, but the button does not appear when using the Windows Store version. I am not sure how to set this up do that that limitation

**Comment by onlytanmoy** [comment]
@Scrxtchy Many thanks for the pointer mate, the Windows Store version was not showing me the virtual audio capture option, so I uninstalled that and installed after downloading from ShareX site, all good now :) closing this ticket.
