### ISSUE TITLE
Custom Uploader with htaccess authorization

### ISSUE THREAD

**Issue by observeroftime02** [ShareX/ShareX#5058]
I run a uguu.se clone on my own server. I protected the site with basic htaccess authentication so that not everyone who comes across it can start uploading whatever. I successfully set up a custom uploader that works great when htaccess protection is disabled, it does what it's supposed to. However, when turning on htaccess authentication, I run into problems.

I thought it would be as simple as simply providing the URL as
`https://username:password@myhosting.ca/uguu/api.php`
but that throws a lot of errors, and doesn't work. 

Here is the error message

> Error message:
> The remote server returned an error: (401) Unauthorized.
> 
> Request URL:
> https://username:password@myhosting.ca/uguu/api.php?d=upload-tool
> 
> Status code:
> (401) Unauthorized
> 
> Headers:
> Content-Length: 458
> Content-Type: text/html; charset=iso-8859-1
> Date: Sun, 20 Sep 2020 06:54:01 GMT
> Server: Apache/2.4.18 (Ubuntu)
> WWW-Authenticate: Basic realm="Members Only"
> 
> Response text:
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>401 Unauthorized</title>
> </head><body>
> Unauthorized
> <p>This server could not verify that you
> are authorized to access the document
> requested.  Either you supplied the wrong
> credentials (e.g., bad password), or your
> browser doesn't understand how to supply
> the credentials required.</p>
> <hr>
> <address>Apache/2.4.18 (Ubuntu) Server at myhosting.ca Port 443</address>
> </body></html>
> 
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
> 
> 

when I use curl to upload a file, it works just fine

`curl -i -F name=test.jpg -F file=@test.png https://user:password@myhost.ca/uguu/api.php?d=upload-tool`

Am I doing something wrong, do I need to enable some special settings, or how do I get this to work?

**Comment by Jaex** [comment]
https://en.wikipedia.org/wiki/Basic_access_authentication

> This has been deprecated by RFC 3986: Use of the format "user:password" in the userinfo field is deprecated.

You can use headers for authentication.
