### ISSUE TITLE
Colour identifier on picker itself

### ISSUE THREAD

**Issue by mythofechelon** [ShareX/ShareX#5059]
Following https://github.com/ShareX/ShareX/issues/4385, is there any chance that the colour identifier could be added to the actual picker itself? Something like this:
![92955821-c86ddb00-f45d-11ea-9974-1a6e24ae0ac3](https://user-images.githubusercontent.com/28054556/93716285-dd85f080-fb66-11ea-9f1c-75b21ed00c2e.png)

**Comment by Jaex** [comment]
I will make it fully customizable I guess, that way users can add whatever they want to tooltip.

**Comment by mythofechelon** [comment]
Thank you very much!
