### ISSUE TITLE
System.NullReferenceException on capture region using the highlight tool

### ISSUE THREAD

**Issue by codingdave** [ShareX/ShareX#5061]
Version: 13.2.1

The following steps are not creating a screenshot but a System.NullReferenceException on my side:

* capture region by keyboard shortcut (Cntrl+Print)
* selecting the highlight tool
* drawing a region with the highlight tool
* pressing enter

This is my log:

2020-09-21 09:32:46.175 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2020-09-21 09:32:46.175 - Executing: Capture region
2020-09-21 09:32:54.805 - Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.ScreenCaptureLib.ShapeManager.RenderOutputImage(Bitmap bmp, Point offset)
   at ShareX.ScreenCaptureLib.RegionCaptureForm.GetResultImage()
   at ShareX.CaptureRegion.ExecuteRegionCapture(TaskSettings taskSettings)
   at ShareX.CaptureBase.CaptureInternal(TaskSettings taskSettings, Boolean autoHideForm)

[ShareX-Log-2020-09.txt](https://github.com/ShareX/ShareX/files/5253960/ShareX-Log-2020-09.txt)

**Comment by Jaex** [comment]
I can't manage to reproduce it.

**Comment by codingdave** [comment]
Looks like `UpdateRegionPath();` is not called in `RegionCaptureForms.Draw()` because there are no `ShapeManager.ValidRegions`.

**Comment by codingdave** [comment]
I can also reproduce that using v13.2.1-48-g9a92490f9

**Comment by codingdave** [comment]
Did you try the exact steps @Jaex ?

**Comment by Jaex** [comment]
Yes.

**Comment by codingdave** [comment]
@Jaex 
please try
* capture region by keyboard shortcut (<Cntrl>+<Print>) - that should give you a rectangular selection
* Press <Enter>
* If you did not yet get the exception, press <Enter> again

**Comment by codingdave** [comment]
Maybe add
`Debug.Assert(gp != null);`
to RegionCaptureForm.cs in line 1357 (before `using (Bitmap bmp = RegionCaptureTasks.ApplyRegionPathToImage(Canvas, gp, out Rectangle rect))`)

**Comment by codingdave** [comment]
> 
> 
> @Jaex
> please try
> 
>     * capture region by keyboard shortcut (Cntrl+Print) - that should give you a rectangular selection
> 
>     * Press Enter
> 
>     * If you did not yet get the exception, press Enter again

Hi @Jaex 
did you try that?

**Comment by Jaex** [comment]
Of course I did. I told I can't reproduce it. If it were that easily reproduceable, everyone would report it.

**Comment by codingdave** [comment]
@Jaex Thats why I ask. 
I can reproduce that issue deterministically on several computers with the steps given above. So I expect that other users are not doing the same or are not aware of the exception (which shows up only in the logs - on failure a user does not get any screenshot done when the exception is caught).

**Comment by Jaex** [comment]
> which shows up only in the logs

I thought you are receiving error window. I can see it in debug log too.

**Comment by codingdave** [comment]
dc21005 fixes the exception but the highlight tool still does not work as it was like I recall. Also no screenshot is created. So this commit only treats the symptom, not the cause. 

Previously, if I remember correctly, you could have a region and use the highlight tool, draw the hightlighted area on the screen, somehow accept the area wich is being highlighted. You could continue with further editing until you finish the screenshot operation and you would end up having a screenshot with the highlight and other editing taken.

What happens now is that you can draw the highlight and in the moment you click the enter key the highlight and screenshot area disappear and you end up without a screenshot.

**Comment by Jaex** [comment]
It did not work like that before. You probably confusing it with multi region support.

**Comment by codingdave** [comment]
I agree that I remember it not correctly. I went back 4000 commits to verify that.

What still puzzles me is the workflow it seems: How would you do:
* Capture region
* Highlight some fraction
* Accept / Complete (to get the screenshot)

I see 2 difficulties here:
1. You need to select one of the "region" tools first or pressing Enter will just make your capture go away
2. Because the capture region is changing wherever my mouse cursor moves (so not on the initial region). Having 2 windows open beneath each other you could capture region on the right window, do some operations on the right (like highlight) go back to one region tool and click on the left window. This will create a screenshot of the left window without the edits.

Is there any documentation recommending a workflow here?
