### ISSUE TITLE
ShareX will not start

### ISSUE THREAD

**Issue by TallTimbers95** [ShareX/ShareX#5063]
I have tried:
Running as administrator.
Reinstalling.
Deleting the ShareX folder from documents
Reinstalling on a different drive.

**Comment by entvex** [comment]
Hello @TallTimbers95 
Do you get any kind of error messages, when you try to tun ShareX?

**Comment by TallTimbers95** [comment]
TL;DR issue exists outside of app. 

Hi, This ticket was created early as ShareX was the first app I noticed behaving incorrectly because of multiple errors from sources like .netframework and the windows TrustedInstaller. As I discovered more and more issues I decided to do a full reinstall of windows 10 and have now got sharex(among other apps) working again.
