### ISSUE TITLE
Open ShareX Image Editor from Command Line

### ISSUE THREAD

**Issue by heyvoon** [ShareX/ShareX#5065]
Hello Everyone,

I've google around already and couldn't find anything on how I could open ShareX Image Editor from Command Line. Is there a way of doing this? If YES, how?

Thank you all in advance ;-)

**Comment by botatooo** [comment]
Yes its possible, and its also [documented on the sharex docs](https://getsharex.com/docs/command-line-arguments)

**Comment by Jaex** [comment]
```
-ImageEditor "filepath"
```

**Comment by heyvoon** [comment]
Hi @Jaex  and thank you for your response. But it does't work for what I am trying to do!

I want to be able to double click on an image file and open it with ShareX Image Editor directly. I created a Shortcut and told Windows Explorer to "Always Open With..." with the following shortcut settings and it doesn't work. Instead it uploads the image to Ingur.
![image](https://user-images.githubusercontent.com/3281265/94000206-258b5a00-fd97-11ea-84d0-544ca97edba3.png)

**Comment by PotoTan** [comment]
> Hi @Jaex and thank you for your response. But it does't work for what I am trying to do!
> 
> I want to be able to double click on an image file and open it with ShareX Image Editor directly. I created a Shortcut and told Windows Explorer to "Always Open With..." with the following shortcut settings and it doesn't work. Instead it uploads the image to Ingur.
> ![image](https://user-images.githubusercontent.com/3281265/94000206-258b5a00-fd97-11ea-84d0-544ca97edba3.png)

Remove the double quotes from sharex.exe in your picture, you wrote the wrong command

**Comment by gsteve3** [comment]
FWIW, I could not get the above working with Explorer, it always kept opening the default for ShareX, which is to share that file type, for me, on Twitter. But... I have been using the AWESOME [FastStone Image Viewer/Browser](https://www.faststone.org/), and it lets you **define external apps to edit the image in**. 

I setup ShareX.exe, then the **Parameters** I added `-ImageEditor` to the beginning, so it became `-ImageEdtior {filename}`.

That worked! FastStone seems great, sorry to sound like an ad, just really helps my workflow and hopefully can help yours too.

All the best! Thanks to everyone involved in this project that truly runs my day.


https://pbs.twimg.com/media/FQo9tiUVIAAsgWy?format=png&name=900x900

**Comment by stephen147** [comment]
`-imageedtior (filename)`worked for me. `-imageeditor` was case sensitive for me at least.

**Comment by flower-spring** [comment]
> -imageedtior (filename)

-image<ins><ins>editor</ins></ins> (filename)
