### ISSUE TITLE
Feature request: Image editor: Change font color.

### ISSUE THREAD

**Issue by syrsly** [ShareX/ShareX#5073]
I can change the border color for the text in the image editor, but even that is a bit finicky.

I would like the text to be black, for example, when on a white bubble. I can't for the life of me find a font color option, though. Perhaps it exists but isn't intuitively located? Even if it exists, I'd like this option to be located on the settings gear menu rather than be part of the specific tool's options. A global font color setting, please.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/09/ShareX_PkETdc7Kqa.png)
