### ISSUE TITLE
Suggestion: Include pastebin's new API features.

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [ShareX/ShareX#5074]
Pastebin has evolved lately for the first time in 100 years. So we might want to make use of features like passwords, and burn after read directly in ShareX.
Also, as the side note, I would rather have an option that pops out a new window to ask me what settings and syntax, password and all of that stuff after selecting what to upload, or at least to have it in after clicking uploads section.

**Comment by Jaex** [comment]
pastebin.com not opens in my country so I can't know any new features.
