### ISSUE TITLE
Backup folder has over 500 files and takes 100 MB of space

### ISSUE THREAD

**Issue by mataski** [ShareX/ShareX#5078]
Any setting to control/limit the C:\Users\Documents\ShareX\Backup usage?

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/95008960-dcc28380-0669-11eb-8339-609a98f2ed8e.png)
Yeah I think it is needed

**Comment by Jaex** [comment]
Implemented in 3c6212a53610ec475916b43f778a0409c7283237

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/12/ShareX_qNhNDwBoxX.png)

**Comment by BrycensRanch** [comment]
Some users have secrets in there that are difficult to replace and some users have a “just right configuration” they don’t know how to reproduce.  Not to mention it’s helpful when you have a rare unfortunate moment of your filesystem messing up the configuration file for one reason or another

**Comment by gqqnbig** [comment]
Your reasons perfectly apply to config files for git, visual studio, video players, ms word, Chrome browser, to name but a few. Yet I don't see them making copies of themselves. 

I am an advocate of the single-responsibility principle. Let professoral backup software/practices do their job. ShareX doesn't have to back up itself.

**Comment by BrycensRanch** [comment]
If ShareX followed your single-responsibility principles, it'd only do screen capture. No OCR, no uploading, and a bunch of other features.  Bottom line is, the backups are in fact a feature.
