### ISSUE TITLE
[Workaround] Program corrupted after computer freeze upon loading ShareX after update

### ISSUE THREAD

**Issue by Drakonas** [ShareX/ShareX#508]
My computer was running beautifully, and then once the program loaded the first time after the latest update, my computer froze. I'm a tech support agent, and regularly clean malware/junk off my self-built gaming machine, so freezes -never- happen.

All I remember is the program loaded (window and all), and I was about to close the window, only to find the mouse wasn't moving.

After waiting a couple minutes (hardly necessary... once your keyboard CAPS lock doesn't even respond, you know your PC is frozen...), I force rebooted, only to find that this window shown up on login.

[Window Title]
C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ShareX.lnk

[Content]
C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ShareX.lnk

"The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail."

[OK]

Event viewer shows these for each attempt to start the program:
Event 59: SideBySide: "Activation context generation failed for "C:\Program Files\ShareX\ShareX.exe".Error in manifest or policy file "C:\Program Files\ShareX\ShareX.exe.Config" on line 0. Invalid Xml syntax."

There are no Event Viewer logs regarding any trouble before the crash.

This is the only entry within an hour of the crash:
Event 7036: Service Control Manager: "The WinHTTP Web Proxy Auto-Discovery Service service entered the running state."
(Not that helpful)

How to workaround: Install the program over the already-installed software.

I thought I'd post this so if anyone has the issue, they can find the problem. I am not sure if the problem even originated from ShareX, but mayhaps the developer knows of something I don't.

A simple over-install (without uninstalling) fixed the problem with no configuration loss, so I'm happy.

**Comment by Drakonas** [comment]
Sorry. I often hit buttons without thinking.. my bad. Please close if nothing is necessary to change.

**Comment by Jaex** [comment]
I don't think it is possible for ShareX to freeze your computer. I not even used keyboard hook which can cause similar effects when input not handled.

**Comment by dany-on-demand** [comment]
I "solved" this issue by installing sharex over the folder where steam installed it
