### ISSUE TITLE
Files in the clipboard are way bigger than the original screenshot.

### ISSUE THREAD

**Issue by Wise-Wolf** [ShareX/ShareX#5082]
Hey, since a couple months I've noticed that whenever I capture a part of my screen or a window, and then try to use CTRL+V in discord, the file that it uploads is a lot larger than the screenshot in my screenshots folder. Here is an [example](https://imgur.com/a/oSoEj6e) You can easily see that the file that is being uploaded to discord is many times the size of the actual file. I'm wondering what happens there, what is causing this, and why has it started happening only recently.

**Comment by L1Q** [comment]
What you end up having in clipboard is not the file, but the original image captured.
In "After capture tasks" there are separate options for "Copy image to clipboard" and "Copy file to clipboard".
Make sure the latter is enabled.

**Comment by Wise-Wolf** [comment]
Oh, gotcha. Thank you, had no idea since it seemingly popped out of nowhere for me.
