### ISSUE TITLE
Can't hit any button but Abort when recording small gifs

### ISSUE THREAD

**Issue by CronosDage** [ShareX/ShareX#509]
I need an 80x160 gif done easy. It and similar sizes only show the abort button and not the timer or the start button, so I just get a useless ff0000 dashed box.

**Comment by Jaex** [comment]
You can click on tray icon to stop or press gif recording hotkey to stop.

**Comment by CronosDage** [comment]
the issue is more or less starting it. the abort button is the only one there. I set Num2 to "start screen recording (gif) using last region but it recorded an mpeg anyway and it stopped recording as soon as i let go of the key

**Comment by Jaex** [comment]
I tried ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/I3M2gcipP7.png) and it worked fine. Starting and stopping is same tray icon click or hotkey press. And there is no such thing in hotkey system as executing something as soon as the hotkey is relesed.

**Comment by Jaex** [comment]
Okey fixed it: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/RqvGlPoIWt.png)
