### ISSUE TITLE
FFMPEG Error related to audio device

### ISSUE THREAD

**Issue by G3Kappa** [ShareX/ShareX#5096]
Re-re-opening #4687 (#2761) because StaleBot is a useless piece of junk.

**THIS IS A RARE ISSUE, SO IT SHOULDN'T GET CLOSED EVEN IF IT GOES STALE**

**Comment by NNTin** [comment]
I updated https://github.com/ShareX/ShareX/issues/2761, experiencing same issue.

**Comment by G3Kappa** [comment]
I give up, apparently this issue is not important enough for you guys to even mark it as permanently open
