### ISSUE TITLE
Refresh image preview after editing with greenshot editor

### ISSUE THREAD

**Issue by piejanssens** [ShareX/ShareX#510]
It would be better that ShareX refreshes the preview image after it comes back in focus(after editing and saving the image.

**Comment by Jaex** [comment]
There is many steps which can modify file and reloading image everytime would be inefficient and it is not very high likely you can select it from list before edit anyway mainly people would select it when uploading so it will always show latest version. Actually in normal capturing it opens image editor before saving so how you got preview at all?! Not to mention file can be not modified after these tasks and it will be waste of hard disk io reading it again. So I'm not planning to keep refreshing it. You can reselect it to force refresh incase needed.
