### ISSUE TITLE
Modifier to draw arrows in reverse

### ISSUE THREAD

**Issue by moniuch** [ShareX/ShareX#5103]
Provide a modifier click and drag to draw an annotation arror in the opposite direction.

I find it more efficient (ie. requiring fewer subsequent touchups/corrections) to start drawing an arrow from the object to a coarsely placed area (which is where the legend will go) rather than end at the object (current fashion). Would be great if - for example - alt could be used to temporarily reverse the direction.

**Comment by obgarmo** [comment]
thx!
