### ISSUE TITLE
Abnormally high CPU usage on current version

### ISSUE THREAD

**Issue by ValiantBlade** [ShareX/ShareX#5105]
As of a few days ago, I noticed that ShareX was pegging a quarter of my CPU.

Previously, ShareX consumed 0%-3% of my CPU. I have since disabled ShareX from running at startup, and that's about all I can do without knowing anything about what is happening.

**Comment by Jaex** [comment]
When ShareX on tray it should not use more than 0% cpu.

**Comment by ValiantBlade** [comment]
![image](https://user-images.githubusercontent.com/22118940/95204005-7ea0b800-07b1-11eb-94cb-c61c3e9be5d6.png)

It's most certainly using more, even after I just briefly opened it. I have the Steam version in particular, if that matters.

**Comment by ValiantBlade** [comment]
I reinstalled the main version off the website and it works now
