### ISSUE TITLE
copy to clipboard after capture not working (Windows10)

### ISSUE THREAD

**Issue by djtrao** [ShareX/ShareX#5107]
When I take a screenshot (for example region) and I go to paint, word, etc...
CTRL+V will not insert said capture. It does not get copied to the clipboard. If I have another pic in the clipboard, it will simply paste that, even after taking another screenshot, that's why I know it is not being copied to the clipboard. 

I need to manually use the "copy to clipboard" button, then it works. 
the after capture option, won't work. 

I have the following options activated under after capture: 
- Open in Image Editor
- Copy image to Clipboard

Ok, I just noticed: If I take "open in image editor" away, then it works. 

So I guess the question is, how can I have both? Have it appear in the editor, but when I'm happy with it, and don't need to edit it, I should be able to simply CTRL+V it anywhere. I have that option in other capture sofwares. 
IF I want to edit it, crop etc... then of course, I'm going to manually use the copy to clipboard button afterwards. 

Is this a missing feature in ShareX?

Thanks for the help

**Comment by Catxue** [comment]
I had the same problem as you and I uninstalled and reinstalled the software again and it didn't fix the problem.

**Comment by Heart1010** [comment]
After you edited the screenshot in the editor - **do you press ENTER** (or click the green play icon) in order to go on with the tasks so the image goes to the clipboard?

It's working here!

**Comment by djtrao** [comment]
Hi, I'm not sure who you are addressing. 

For ShareX to be as convenient and fast (specially if you take alot of Screenshots in succession, e.g. to make tutorials) as other screen capture softwares it should be possible to take a screenshot and insert it - for example - into a Word document like this: 

1) I press whatever Screenshot Shortcut I need, PrintScreen or Alt+printScreen etc.
2) I alt-tab to Word and press CTRL+V

That's it. I have just inserted a screenshot of something into word. That's how almost all other programs work. 

I do NOT want to press additional icons. Yes, if I use the editor and alter the screenshot, it's perfectly cool to press the "copy to clipboard" icon.

**Comment by Heart1010** [comment]
Sure - but why you have actived "Open in Image Editor" then? Deactivate that option and you have it like you wish? (and this is working here - tested few seconds ago)

If you want to annotate the screenshot - so you have activated "Open in Image Editor" you simple do your annotations in the editor and press ENTER.

**Comment by djtrao** [comment]
Because sometimes I need to make some changes. Blurr something out or put sme arrows in (eg when making tutorials).
So you want to document how to use a software, or how to make a payment in ebanking etc. 

you're going to end up taking 10 screenshots, and in 4-5 of them you will change something. 

So why should it not be possible in one step? Editor opens, but at the same time, it's in the clipboard. IF needed, I use the editor, and then re-copy it so that my changes are now in the clipboard (usually I need to do another CTRL+C in other programs). 

If I don't, I'm all set and just alt tab to the word doc etc.


This is all no problem, when you take ONE screen shot and then are done. When you need to take screenshots often, and more than one, this really becomes cumbersome the way it is now.

**Comment by Heart1010** [comment]
I understand your point... but on the other hand you have to close the editor anyway all the time regardless if you changed something or not, don't you? 
So you click the X top right for that now?
Instead of clicking X simply press ENTER and you're good to go 😃 

But as said I got your point...

**Comment by djtrao** [comment]
Yes, in other programs, you don't get a new editor every time you make a screenshot. 
They just work with tabs, or just put the last screenshot behind the newest one. You can then "close all" or at any time go back to see the previous ones, if needed.

**Comment by mfatty** [comment]
I think there is an easy fix here, unless I'm missing something. 
Let's say I have two "after capture tasks" activated. 
(1)  copy image to clipboard
(2) save image file as ...

Why can't this application make both (1) and (2) happen at the same time? If I only need the clipboard so I can paste in Ms.Word, then I'll just close the "save as" explorer window as I don't need to save this screenshot.
Is this hard to implement?

**Comment by nanangp** [comment]
An alternative solution would be to _allow re-arranging of tasks._ 

Or at least add an option to have the Editor task happen later in the sequence. Looking at people's suggestions, being able to trigger the Editor _after_ Clipboard and/or File Save would make a lot of people happy (myself included).

**Comment by originallgb** [comment]
I struggled with this problem for ages. I was able to get this working the way I want that making sure the "add image effects -> name" after capture task is enabled .
![image](https://user-images.githubusercontent.com/2849533/112000878-49e1ac80-8b16-11eb-91f3-674a56629565.png)

**Comment by alex24409331** [comment]
aftercapture tasks don't work.
**ctrl+shift+c** and your screenshot will be in the clipboard

**Comment by divinaet** [comment]
I had the same issue, when you target editor and clipboard.
Actually you have to hit enter when the editor is open (even if you haven't made any modification), and then the editor close and your screenshot is in your clipboard !

**Comment by james-dripdrop** [comment]
Note that issues can exist if both copy image to clipboard and copy file to clipboard are selected - I'm assuming this is an order of operations issue.

**Comment by BenjaminEOT** [comment]
This bug continues to haunt v18.0.1 on Windows 11 Pro 24H2
50% of the time I have to recapture the screen a second time before it is able to get onto the clipboard. 

Just a moment ago it failed spectacularly that no matter what I did, it absolutely refuses to get onto the clipboard. 

After capture tasks > 
+ Copy image to clipboard
+ Show quick task menu > Copy image
+ Show "After capture" window > Copy

Kill & Restart ShareX 

Absolutely nothing could get onto the clipboard until I saved it to a file, opened the file in a seperate image viewer and copied it off from there.

**Comment by cole-1** [comment]
I have just found this out so maybe it would be of some help to someone...
Make sure you have checked the "Auto copy image to clipboard" option enabled in image editor:

<img width="650" height="302" alt="Image" src="https://github.com/user-attachments/assets/95cd0a7d-5050-455f-9fa1-b8184ee68503" />
