### ISSUE TITLE
[Suggestion] Preview of taken photo bottom right corner

### ISSUE THREAD

**Issue by Scrat94** [ShareX/ShareX#5108]
Dear developers,

currently, if you take a screenshot, a small preview is shown on the bottom right corner. If you click on it, you will open the image in the default photo viewer. 
Is it possible to change this behavior, to open the image instead in ShareX. I like the Chronik / Structure in ShareX directly and do not want the taken screenshot to open somewhere else. Is this possible?

Thanks in advance!
Regards
Scrat

**Comment by stdedos** [comment]
I'd prefer to open the containing folder, so yeah - some action customization pls? :-D

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/10/ShareX_2IRmDMN9WO.png)

**Comment by stdedos** [comment]
I think the OP asked for a "very" custom action support (Open with ShareX Image Editor).

I know that he could've just used the "After Screenshot" flow - but I guess someone should let him know of his options / whether a custom action (`custom-path/ShareX-Image-Editor.exe %s`) would be considered etc ...

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/10/chrome_6Qep4jen8C.png)
