### ISSUE TITLE
"Before Upload" window issues

### ISSUE THREAD

**Issue by Dream-Cypher** [ShareX/ShareX#511]
1. When I upload an image with the "before upload" window enabled, if I choose a file destination (such as dropbox or copy.com), the file still uploads to the default image location (i.e. imgur).  If I choose a different image location (such as tinypic), it behaves correctly.

2. When I upload a file (from the "Upload File..." option) using the "before upload" window, it always defaults to dropbox, even if I have a different provider chosen as the default destination. (unless it is an image file, in which case is defaults to the correct image destination... choosing a file destination results in the same result as above)

**Comment by McoreD** [comment]
Thank you for the bug report. I managed to reproduce issue 1 however I could not reproduce issue 2. I will keep a closer eye on issue 2.
