### ISSUE TITLE
GIF Recording: Text Cursor have black squared area in fullscreen Windows 10 Remote Desctop

### ISSUE THREAD

**Issue by Sonare** [ShareX/ShareX#5111]
When it RDP Win 10 (fullscreen) and catching GIF with text area my cursor have black squared artifact nearby. 
Sometime cursor try to  drag to the point it was 1 sec ago (it's annoying).
In gif I can't see this, so GIF captured properly.
![xDXba7Uf4g](https://user-images.githubusercontent.com/16069939/95350043-6c656d80-08c8-11eb-8928-dfa25fd187c3.gif)

**Comment by Scrxtchy** [comment]
I was able to replicate this with `ffplay -f gdigrab -framerate 30 -i desktop -video_size 640x480`
This is an issue with GDIGrab in ffmpeg, there is really not much we can do fix this inherently.

If you use the non-windows store version of ShareX, there is an option to install alternative recorder devices within the Screen Recording settings. This can be used as an alternative to GDIGrab and does not have this issue.

**Comment by Sonare** [comment]
I'm using the Win version but can handle with this bug through not-full-screen RDP window
