### ISSUE TITLE
Override Destination does not change the Destination

### ISSUE THREAD

**Issue by Forbidden-Duck** [ShareX/ShareX#5115]
I have 2 hotkeys one is set to override destination to custom uploader and the other one is to override destination to Imgur.
The issue is, neither of them change. I've made sure that the checkbox is ticked and I switched them to "1" and "2" to see if they would prevent the key from being pressed in text areas and it does.

I'm just unsure if I'm using it wrong. Sending screenshots of the setup.

**Hotkey Window**
![Hotkey Window](https://i.imgur.com/eeKScpm.png)

**Custom Uploader Window**
![Custom Uploader Window](https://i.imgur.com/bfPo4ie.png)

**Imgur Window**
![Imgur Window](https://i.imgur.com/cGCCtXM.png)

And yes, in the Destinations it is set to the corresponding destination for the hotkey

**Comment by Scrxtchy** [comment]
The workflows are not used for change the settings of the application. In this case, it would be doing a new operation where every time you use that hotkey, it would use a destination based on those overrides.
In the top of the window, your Task is set to **None**, where this can be set to many of sharex's actions, such as Capture and Upload image. There is no task within ShareX that allows you to apply custom workflow settings as the application default
