### ISSUE TITLE
Possible to show screen wide crosshair while capturing but not while editing?

### ISSUE THREAD

**Issue by DannyDeLoach** [ShareX/ShareX#5117]
Is it possible to have the screen wide crosshair visible when capturing a region but not have it visible when editing a picture? In my use of the software it seems the screen wide crosshair is either visible in both cases or not visible in either case. It would be nice if I could have it visible while capturing a region, but I would prefer to not have it visible while editing a photo. Thanks for any help on this issue.

**Comment by chaslp** [comment]
Kindly consider reopening this ‘Stale’ complaint. I agree with the original poster. This change would be welcome by many users. 

The screen wide crosshair is very useful when capturing a region. But when editing an image, the crosshair is extremely annoying and distracting.

A checkbox box to turn off the crosshair while editing would be a welcome option.

ShareX is one of the best programs I’ve ever encountered. Great work!
Thank you.
