### ISSUE TITLE
Remove spaces from file uploads prior to uploading

### ISSUE THREAD

**Issue by jms1989** [ShareX/ShareX#512]
I just setup ftp uploading for sharex and noticed when I upload a file with spaces in it, it ends up not loading in the web browser. I get a 404 error from my server and am wondering how if I can configure sharex to rename them but not like the default pattern for screenshots. or is there something I can do in htaccess on my upload directory that'll force it to load the file like normal

Example: http://thelonegeek.net/s/e

thanks

**Comment by Jaex** [comment]
Spaces using %20 in url which is valid encoding so there is no problem in file naming. There is no setting to remove spaces in ShareX. Problem must be to do server side.
