### ISSUE TITLE
Use System.Text.Json instead of Json.Net

### ISSUE THREAD

**Issue by kotx** [ShareX/ShareX#5122]
System.Text.Json weighs about 30KB, while Json.Net weighs ~640KB.

**Comment by sylveon** [comment]
Sounds like a great candidate for a PR 😉

**Comment by Jaex** [comment]
We don't use Core .NET

**Comment by kotx** [comment]
> We don't use Core .NET

Yes, System.Text.Json is part of standard library only for .NET Core, but it can be added as a Nuget package.

**Comment by sylveon** [comment]
In which case it brings a bunch of other dependencies, defeating the size gains:

![image](https://user-images.githubusercontent.com/6440374/95889729-c941a780-0d50-11eb-98fc-b226dac7c736.png)

**Comment by kotx** [comment]
> In which case it brings a bunch of other dependencies, defeating the size gains

Fair enough. I've heard that it is significantly faster than Newtonsoft.Json, but it might not be relevant for the use cases of ShareX.
