### ISSUE TITLE
capturing an off-desktop application window 

### ISSUE THREAD

**Issue by elig0n** [ShareX/ShareX#5123]
I did not succeed capturing a window whos height is higher than or part of it is hidden than the viewable monitor desktop with neither _Region capture_ nor _Window capture_. For example a Windows Explorer window with some part of it out of the monitor that part is not captured. Is it possible to do this somehow or would you consider implementing it ?

**Comment by Pedrilkov** [comment]
This cannot be done because it is out of the buffer. Like outside the universe!
