### ISSUE TITLE
Activating screen capture on secondary monitor overlays the window from the primary monitor

### ISSUE THREAD

**Issue by PrimozR** [ShareX/ShareX#5127]
With two monitors at work, I have recently started getting an issue with ShareX. When I press my hotkey to capture a region, if my mouse cursor is positioned on the primary (left) window, everything works normal (also on the secondary (right) monitor). If my mouse cursor is positioned on the secondary (right) monitor, the active window from the primary monitor is overlaid over the content of the secondary monitor with a ~10x10px offset from the upper left corner, covering the content of the secondary monitor.

That means I cannot capture content on my secondary monitor, unless I actively position my mouse cursor on the primary monitor.

This has been going on for the past ~2 weeks. I have recently updated PowerToys from Microsoft and have recently set up FancyZones, but I have done it later than this issue has started happening. Plus I'm running the same setup regarding PowerToys at home, albeit with only one monitor, but there are no issues.

I'm running a laptop (FullHD) connected to dual FullHD monitors via a Thunderbolt dock and I'm running Windows 10.
I'm opening this issue from home, but I can provide pictures or screenshots if needed.

**Comment by hessianerd** [comment]
sounds like this
https://github.com/ShareX/ShareX/issues/4862
for me it doesnt happen when I use the tray to select region capture

**Comment by PrimozR** [comment]
Indeed it does sound like it. I'll try it out once I'm at work, where I have two monitors (the part where not using hotkeys does not produce this issue). The thing is, like I mentioned, that this is a relatively new phenomenon.

**Comment by brimwats** [comment]
I've provided a recording of this in #5395

**Comment by Heinrix** [comment]
I am experiencing this issue as well and it seems to be related to PowerToys - FancyZones function "Move newly created windows to the current active monitor (EXPERIMENTAL)".
Turn that feature off and everything works fine again.

**Comment by PrimozR** [comment]
I have it turned off and I still have the issue on my SINGLE 49" monitor. If I restart ShareX it works, but after a while, it offsets the left part of my monitor to the right (either to the middle or the right FancyZone).

It does appear to be an issue with FancyZones though.

**Comment by limacohen** [comment]
> I am experiencing this issue as well and it seems to be related to PowerToys - FancyZones function "Move newly created windows to the current active monitor (EXPERIMENTAL)".
> Turn that feature off and everything works fine again.

Another less disruptive option would be to add `ShareX.exe` to the "Excluded apps" in PowerToys - FancyZones:
![PowerToys Settings_pBIUWtwW99](https://user-images.githubusercontent.com/541169/128399895-d27e4da7-7641-44b4-9a15-e719973e8260.png)

**Comment by PrimozR** [comment]
Correct, can confirm this exclusion works.

Does anybody know, is this a fairly recent feature of PowerToys?

**Comment by limacohen** [comment]
> Correct, can confirm this exclusion works.
> 
> Does anybody know, is this a fairly recent feature of PowerToys?

Might not be related but it's been happening to me since I switched to Windows 11 (21H2). I've also been experimenting with a couple zones (3) that go on top of other zones. Maybe the overlapping throws ShareX off? Since the exclusion works, I haven't given it more thought. Tip: Resize/reposition ShareX's main window before excluding it.

**Comment by PrimozR** [comment]
No, overlapping zones aren't a factor, as I don't have overlapping zones and still had problems.

**Comment by silversword411** [comment]
See my comment here: https://github.com/ShareX/ShareX/issues/5408#issuecomment-908552568

I'm sure there's lots of utils that can look for windows off screen that try to bring them back on screen to be visible to the user. 

<img width="467" alt="2021-08-30_135313 - offscreen portions of windows" src="https://user-images.githubusercontent.com/13395348/131382946-47abad2e-61d7-4614-b865-2d61d04fd203.png">

**Comment by Ironship** [comment]
> I am experiencing this issue as well and it seems to be related to PowerToys - FancyZones function "Move newly created windows to the current active monitor (EXPERIMENTAL)". Turn that feature off and everything works fine again.

Dude i love you
