### ISSUE TITLE
How do I disable logging?

### ISSUE THREAD

**Issue by Pedrilkov** [ShareX/ShareX#5129]
I don't need any data left on the computer to calculate my actions. How can I disable this log? I put a ban on writing to a folder and because of this I see errors. This is the Logs folder

**Comment by Jaex** [comment]
You can't disable.

**Comment by Pedrilkov** [comment]
Do you spy users? I will figure you out

**Comment by Jaex** [comment]
lol

**Comment by voidray** [comment]
I checked the code and it should be pretty easy to add a setting (under advanced maybe) to disable logging. I compiled my own version with logging disabled. I don't like the idea of there being a complete history of all the actions I took with the application.

Currently the FileWrite variable is always set to 'true' in the Logger class initialization.

**Comment by csavalas** [comment]
I love this program and have also wanted to see this feature for a while now. As a stopgap, I created a [fork of the repo](https://github.com/csavalas/ShareX) here with recent tasks and logging completely disabled. Feel free to build it yourself, or you can just copy the contents of the zip file in the root of the fork [ShareX-Mod](https://github.com/csavalas/ShareX/blob/develop/ShareX-Mod.zip) into your existing ShareX directory (`C:\Program Files\ShareX`). Only two slight changes were made to the following files:

`ShareX/ShareX/Program.cs`
`ShareX/ShareX/Forms/MainForm.cs`

**Comment by Jaex** [comment]
@csavalas https://getsharex.com/docs/command-line-arguments#registry

> DisableLogging REG_DWORD
> Disables debug log file saving.

**Comment by crash5** [comment]
> @csavalas https://getsharex.com/docs/command-line-arguments#registry
> 
> > DisableLogging REG_DWORD
> > Disables debug log file saving.

How can I use use this for a portable installation?

**Comment by X88R88** [comment]
> I love this program and have also wanted to see this feature for a while now. As a stopgap, I created a [fork of the repo](https://github.com/csavalas/ShareX) here with recent tasks and logging completely disabled. Feel free to build it yourself, or you can just copy the contents of the zip file in the root of the fork [ShareX-Mod](https://github.com/csavalas/ShareX/blob/develop/ShareX-Mod.zip) into your existing ShareX directory (`C:\Program Files\ShareX`). Minor changes were made to the following files:
> 
> `ShareX/ShareX/Forms/MainForm.cs` `ShareX/ShareX/Forms/MainForm.Designer.cs`

Does this still work?

**Comment by csavalas** [comment]
> > I love this program and have also wanted to see this feature for a while now. As a stopgap, I created a [fork of the repo](https://github.com/csavalas/ShareX) here with recent tasks and logging completely disabled. Feel free to build it yourself, or you can just copy the contents of the zip file in the root of the fork [ShareX-Mod](https://github.com/csavalas/ShareX/blob/develop/ShareX-Mod.zip) into your existing ShareX directory (`C:\Program Files\ShareX`). Minor changes were made to the following files:
> > `ShareX/ShareX/Forms/MainForm.cs` `ShareX/ShareX/Forms/MainForm.Designer.cs`
> 
> Does this still work? I replaced the original files with the mod folders files and nothing happened.

Did you then compile from source, or what do you mean by 'nothing happened'?
