### ISSUE TITLE
zippyshare support

### ISSUE THREAD

**Issue by Aokromes** [ShareX/ShareX#513]
Hi, i found this amazing tool, and i wonder if we can have support for http://www.zippyshare.com
Thx!

**Comment by MrLesh** [comment]
As far as i can see from their website they don't have a public api that we can work with...
they did release a desktop application but I'm not sure we can work with that legally, and even so not sure we would want too...
This is for Jaex to decide I guess

**Comment by Scrxtchy** [comment]
```
{
  "Name": "zippyshare",
  "RequestType": "POST",
  "RequestURL": "http://www40.zippyshare.com/upload",
  "FileFormName": "file_0",
  "Arguments": {
    "private": "true"
  },
  "ResponseType": "Text",
  "RegexList": [
    "\\/v\\/(?<code>\\w+)\\/file\\.html"
  ],
  "URL": "http://www40.zippyshare.com/v/$1,code$/file.html",
  "ThumbnailURL": "http://www40.zippyshare.com/thumb/$1,code$/file.html",
  "DeletionURL": ""
}
```

**Comment by Jaex** [comment]
Added it here: https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#zippysharecom

**Comment by eqagunn** [comment]
This is great! Should be part of default file uploaders, along with 1fichier.com.

**Comment by Aokromes** [comment]
no longer needed, since it will close.
