### ISSUE TITLE
Feature Request: screenshots subfolder pattern for application

### ISSUE THREAD

**Issue by eidylon** [ShareX/ShareX#5133]
Right now there are various options for creating subfolders for your screenshots. 
It would be **eminently** useful to have an option in there for creating subfolders based upon the program being screenshotted. 

![image](https://user-images.githubusercontent.com/5951045/96359137-2042d600-10dd-11eb-8818-dffc6156f9fa.png)

So like how it prepends the program name on the filename, it would instead create a folder for the program. 
For example, these screenshots would've been saved in folders by "datagrip", "mstsc", "firefox", "code", and "opera".

![image](https://user-images.githubusercontent.com/5951045/96359194-cd1d5300-10dd-11eb-8545-4422967d682e.png)

**Comment by Tenome** [comment]
I found this while looking for this exact feature. Maybe it's possible with some rigging of the current naming variables, or does this need to be implemented?

**Comment by curious-questions** [comment]
Need this...
