### ISSUE TITLE
Thumbnail update after image edit

### ISSUE THREAD

**Issue by hynrey** [ShareX/ShareX#5135]
After editing image in ShareX editor, thumbnail of image does not refresh to actual but image is fine.
Version 13.0.1

**Comment by jennybrown8** [comment]
I'm seeing this as well.  Reproduction steps:
1. Take a screenshot
2. Edit in ShareX image editor
3. Do a drastic crop in the image editor, and press Save.
4. Close the image editor.  ShareX still incorrectly shows the uncropped version, even though the file on disk is properly cropped.

This makes it tedious to sort through a list of several similar screenshots to find which one I did the crop to.

**Comment by randbrown** [comment]
Yes this would be great!  So tedious trying to find images after having edited them.

**Comment by jennybrown8** [comment]
This is still a bug and I believe the ticket should remain open.

**Comment by d0verenny** [comment]
The bug still exists
