### ISSUE TITLE
Custom Uploader Specification

### ISSUE THREAD

**Issue by borgmanJeremy** [ShareX/ShareX#5138]
Hello,

I am the maintainer for the screenshot program Flameshot. We are reworking our image upload system and we got a suggestion that we support the same format as shareX for custom uploaders. I think this is a great idea to minimize the overhead required for plugins.

Do you have an actual specification for the plugin syntax / key value pairs? I see this [link](https://getsharex.com/docs/custom-uploader) but was not sure if there was a more formal definition / documentation.

For the upload destinations you officially support (like dropbox or next cloud), do you have .xscu file's for those?

**Comment by Jaex** [comment]
Hi borgmanJeremy,

Unfortunately we don't have specification for it, other than that custom uploader guide page aimed for users.

You can see object of custom uploader in here: https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/CustomUploader/CustomUploaderItem.cs

This object is serialized to JSON. So `.sxcu` (ShareX Custom Uploader) file is actually JSON file.

Best way for you to see how it works would be using it and exporting JSON like this:

![](https://jaex.getsharex.com/2020/10/ShareX_xEKPxU9IDc.png)

But if you don't have Windows VM then you won't be able to test it.

Our custom uploader system not supports OAuth and refreshing tokens, so we don't use custom uploader for Dropbox. Custom uploader system is useable if only single request is needed to upload data.

**Comment by Jaex** [comment]
It is not exactly specification but added more info about sxcu file here: https://getsharex.com/docs/custom-uploader#sxcu-file
