### ISSUE TITLE
Add New Setting to add a default color code field to clipboard when using the Color Picker app

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#514]
I find myself often using the color picker in addition to the screenshots. editor, and new video recording apps.

My ultimate goal from this feature request is to add the ability to streamline the process of quickly getting a color value...

- hitting a keyboard combination which launches the color picker  
- I then select a color  
- the `Hex` color value is then added to my clipboard  
- color picker app closes

I always have to open the color picker app, do the process to get the color, and then copy and past the HEX value `#6FC850` 

I would find it really useful if there was a setting to make it automatically add the color value to your clipboard when you select a color.  There would then be another setting to determine which color value is copied to the clipboard by default.  In my example and my main usage would be simply the `Hex` value of the new selected color!

For example I mainly only use the `HEX` color code which I have highlighted in the screenshot below.  I would really like that value to be copied to my clipboard automatically to streamline the process of getting a color quickly just like the screenshot process is streamline!

What are your thoughts on this?  Thanks

- Jason

![2015-02-14_14-22-30](https://cloud.githubusercontent.com/assets/186818/6200783/1d1f2aa4-b455-11e4-8977-7eb365456ec0.png)

**Comment by Jaex** [comment]
I already added that in latest version, you need set hotkey for "Screen color picker" and then set:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/ShareX_iZPAmJ3JfE.png)

**Comment by jasondavis** [comment]
Amazing, thanks you really have thought of it all!
