### ISSUE TITLE
Share X not recording audio - Please Help!

### ISSUE THREAD

**Issue by Jamington** [ShareX/ShareX#5147]
Hello there!

I have been using ShareX to record audio snippets from Japanese shows on my Windows 10 PC(for language learning). I am using the setup outlined here https://youtu.be/CfvDKgNUSi8?t=1196

Unfortunately, my recordings are blank. When I click on the VLC recording, I get [this](https://gyazo.com/23e600320b666fec9eef8c99d73b0504) window. The bar at the bottom has --:-- next to it and there's no audio. Not even a recording that rolls but doesn't have sound, there's just nothing, no recording at all.

Every time I try to record using my hotkey for recording, it takes the program a few seconds to start recording. It also takes it a few seconds to stop after I press the hotkey again. The recordings are always blank.

Here's what I've tried so far! I've followed exactly the setup in the video, which I know works for others. I have installed ffmpeg and I've installed recorder devices. I've restarted my PC. I've uninstalled and reinstalled ShareX. Nothing seems to work. I have only been trying to record windowed applications, not full-screen ones.

Does anyone have any advice on this, please? If not, perhaps an alternative program for recording audio snippets? 
Thank you for your time!
![1szZO638BM](https://user-images.githubusercontent.com/73316067/96934290-e3e6ef80-14b9-11eb-86be-dc3ee9271603.jpg)

**Comment by nalam002** [comment]
Does it work if you also record the video along with the audio and extract the audio afterwards with something like [Pazera's free software](https://www.pazera-software.com/products/audio-extractor/)?

**Comment by Jamington** [comment]
Hi there! Thank you for your comment and suggestion. I changed the video source to 'screen-capture-recorder' and two things happened
- the delay between when I click 'stop' and when the recording actually stops has increased from 5 to 10 seconds
- the recordings are still blank and in fact give me an error.

I tested with CMD and got this error message... Do you perhaps have any other ideas, please?

Thanks!
![Capture](https://user-images.githubusercontent.com/73316067/97026091-dc265a00-1550-11eb-8b91-9b81e90d6c3d.PNG)

**Comment by nalam002** [comment]
Interesting. 
I can't seem to reproduce your problem, everything works ok for me. How about you set audio source to None/Microphone and add "-f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest" to the **additional command line arguments**? That's what I'm doing. (Also I use AAC as my audio codec)

Here's my complete command line if you wish to compare:
```
-rtbufsize 150M -f dshow -framerate 30 -i video="screen-capture-recorder":audio="Microphone (Realtek(R) Audio)" -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a aac -ac 2 -b:a 192k -y "output.mp4"
```

**Comment by Jamington** [comment]
Thanks for the reply! I'm also on ShareX 13.2.1. I tried a few things after reading your response. The first thing I did was add that to the additional command line arguments. I then tried the following:

- no screen recorder + no audio source 

result: ShareX says I can't have both of them set to 'none'

command line in this case: empty

- no screen recorder + mic as audio source 

result: same error outlined in my original post

command line in this case: -rtbufsize 150M -f dshow -i audio="Microphone Array (Realtek Audio)" -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest -c:a libmp3lame -qscale:a 4 -y "output.mp3"

- screen recorder and either no audio source or mic as audio source 

result: same error as in my comment from yesterday

command line with no audio source: -rtbufsize 150M -f dshow -framerate 30 -i video="screen-capture-recorder" -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -y "output.mp4"

command line with mic as audio source: -rtbufsize 150M -f dshow -framerate 30 -i video="screen-capture-recorder":audio="Microphone Array (Realtek Audio)" -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a libmp3lame -qscale:a 4 -y "output.mp4"

This is tricky... Do you have any other ideas perhaps? 

I'm grateful for your help so far!

**Comment by nalam002** [comment]
Hmm, maybe try removing the additional arguments and try with video + only mic and video + no sound, so we are not using the ""virtual-audio-capturer"" at all. This might help us pinpoint if the problem is with the audio codec or the video one.

I also found another person's [post](https://stackoverflow.com/questions/48320119/real-time-buffer-too-full-ffmpeg) who mentioned that adding **-thread_queue_size 5096** in front of each -f dshow solved his problem.

**Comment by Jamington** [comment]
Thanks for the reply. I removed the additional arguments and tried a few things

- screen-capture-recorder + no sound
- screen-capture-recorder + mic

Result in both cases
- the delay between when I press 'stop' and when the recording stops fell from 5 seconds to 1 second
- the recordings are[ still blank](https://gyazo.com/e64338345b7dda2dba761e4747b607cf) - same as before. However, now, if i click the play button in VLC player, the window expands for a splitsecond as if it's about to play the video, before returning to the blank state. That didn't happen before, though I'm guessing it may just be because now I'm trying to capture video, not just audio. The result is basically the same anyway - no recording.

I also added the -thread_queue_size 5096 in front of each -f dshow, so my command line looks something like
`-rtbufsize 150M -thread_queue_size 5096 -f dshow -framerate $fps$ -i video="screen-capture-recorder" -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -y "$output$"`

It makes no difference though - same blank recordings and the same error when I test with CMD, as in my comment from yesterday.

Since I had virtual-audio-capturer off in all these cases, maybe the issue is with the video codec? But then, why would that prevent me from taking just audio snippets without video, as I originally intended? I'm pretty lost ngl

Thanks

**Comment by nalam002** [comment]
@Jamington This is super late and you have probably solved the issue by now, but suddenly one day this issue started popping up for me too, and after a lot of wrestling I managed to fix it by adding -rtbufsize 1024M -thread_queue_size 512 in front of my video input and -rtbufsize 100M -thread_queue_size 1024 in front of the audio.
Complete command line:
```
ffmpeg -thread_queue_size 512 -rtbufsize 1024M -f dshow -framerate 15 -i video="screen-capture-recorder":audio="Microphone (Realtek(R) Audio)" -rtbufsize 100M -thread_queue_size 1024 -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest -c:v libx264 -r 15 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a aac -ac 2 -b:a 192k -y "output.mp4"
```

**Comment by kunamvahees** [comment]
> -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest

Tdding this line enables me to record both Audio in and out with my capture. Thank you.
