### ISSUE TITLE
Add SiteShoter a command line tool to generate fullpage webpage screenshots as a new tool in ShareX?

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#515]
SiteShoter - Webpage screenshot generator program that can be ran from the command line or from a GUI app.  You can supply a ULR of a webpage or supply a text file with a list of urls and the program will generate full length webpage screenshots.

There are a lot of Browser extensions for doing this but I find they often mess up and do not always work on many sites.

Perhaps this small utility program could be added as a new tool to ShareX for creating screenshots of webpages.

I realize it would be a lot of work most likely but would be a nice addition to ShareX's tools.  The app runs from command line too which would simplify things I believe!

The website is here http://www.nirsoft.net/utils/web_site_screenshot.html

Your Thoughts?

**Comment by Jaex** [comment]
It using Internet Explorer to render screenshot. I could have easily added that to ShareX but rendering it in IE is horrible. And most importantly people would like to get ss of what they see which means including their logged in status etc. So cookies won't work in these. So using these is best bet: https://github.com/ShareX/ShareX/wiki/Capture%20webpages%20using%20browser
