### ISSUE TITLE
(optionally) Automatically remove blank space in multi region captures

### ISSUE THREAD

**Issue by spoergsmaal** [ShareX/ShareX#5150]
When using multi region mode for captures, the captured frames retain their original distance to each other in the produced image.
For example, compare these two screenshots:

https://i.imgur.com/P6IAA6j.png
https://i.imgur.com/shRVC7h.png

Is it possible to automatically have ShareX composite these separate regions, so they appear immediately next to each other in the output image?

**Comment by L1Q** [comment]
Not as of now.
Maybe if there is a good algorithm to always get acceptable results somebody could implement it.
Meanwhile you can do it manually with "Image (Screen)" tool during capture to assemble single region by moving multiple small pieces and capture it.

**Comment by spoergsmaal** [comment]
> Not as of now.
> Maybe if there is a good algorithm to always get acceptable results somebody could implement it.
> Meanwhile you can do it manually with "Image (Screen)" tool during capture to assemble single region by moving multiple small pieces and capture it.

I was not aware of the "Image (Screen)" tool, that definitely helps! Thank you.
