### ISSUE TITLE
Capture the screenshot hotkey

### ISSUE THREAD

**Issue by oliversalzburg** [ShareX/ShareX#5153]
On the latest revision of the Microsoft Ergnomic Keyboard 4000, there's a dedicated screenshot button, that invokes the Snipping Tool when pressed.

Obviously, this button is useless unless it invokes ShareX. It'd great if this key could be captured and used for ShareX. When I press it while trying to assign a keyboard, it's not captured and, instead, the Snipping Tool opens.

Maybe it just triggers Win+Shift+S under the hood?

**Comment by Jaex** [comment]
> Maybe it just triggers Win+Shift+S under the hood?

How can we know, we don't have the keyboard.

**Comment by oliversalzburg** [comment]
I totally understand that. The way I phrased that was misleading, sorry.

I tried to look into what it does and didn't have much success. I was hoping someone else might have seen the same functionality elsewhere and could chime in.

But, assuming it would just invoke the mentioned key combination, can that be hooked in general to replace the snipping tool? Which would then indirectly also make the hotkey usable to ShareX.

**Comment by Scrxtchy** [comment]
The keyboard pre-dates the shortcut's existence. I wonder if it's programmed into the driver, but I cannot install Mouse and Keyboard Centre in the sandbox for investigation
![image](https://user-images.githubusercontent.com/12771982/97243838-4c7ff480-184b-11eb-9803-b88b94b4cd4d.png)

**Comment by oliversalzburg** [comment]
My mistake. I mentioned the Ergonomic Keyboard 4000 in my original post. The new version, which was released in 2020, does not have the "4000" suffix.

The Ergonomic Keyboard 4000 did not have that key, the new version does.

If you have any ideas on how I could investigate myself, I'd be happy to get into it :)

**Comment by Scrxtchy** [comment]
I managed to unpack the installer (wasn't hard, just didn't think about it at the time), but I notice that the xml data for the Ergonomic keyboard lists the printscreen command as an excluded command

![image](https://user-images.githubusercontent.com/12771982/97384689-5164a700-1924-11eb-84a4-7b55dfca965b.png)

It doesn't really make that much sense because there's a bunch of buttons that aren't on the supported events (or are, but their descriptions are weird, ie `IDS_EMOJI`).
Also worth noting that there's an entry for One-note clipping

**Comment by oliversalzburg** [comment]
Maybe those are the commands that can _not_ be reassigned on that keyboard.

Maybe the "OneNote screen clipping" command is the one I'm referring to. It seems like the clipping tool invokation is a later iteration of that feature: https://support.microsoft.com/en-us/office/why-doesn-t-the-screen-clipping-tool-work-anymore-311c21ff-68d9-4e2a-8769-ede9faafdb17

There is some related work to disable/capture the Office key here: https://github.com/anthonyheddings/OfficeKeyFix But that seems to operate by trying to register the hotkeys when Explorer isn't running. Probably not a valid approach for ShareX.
