### ISSUE TITLE
Editor issue - pointer locked in pan mode

### ISSUE THREAD

**Issue by yobryon** [ShareX/ShareX#5160]
I have a weird issue that seems to have recently started where the mouse cursor is perpetually in the pan mode (diagonal cursor, clicking and moving moves the image around the window canvas). As such, I can't use a mouse click to actually perform any of the editor's actions (like drawing an arrow, selecting, etc.). 

Oddly, I _can_ press _insert_ which acts like a mouse click would have. 

Have tried various things to rule out intermittent system issue as well -- reboot, uninstall/reinstall, review app settings, etc.

This is on Win 10 v2004, ShareX versions 13.2.1 and 13.3. (I have not tried downgrading to see if the issue goes away).

**Comment by yobryon** [comment]
Update: I've narrowed down the conditions of this. This is occurring in a multi-monitor setup, and whenever the image editor is on a display that is not the primary display (so, when the image editor is on the second monitor).

**Comment by barsv** [comment]
Reproduces for me too. 
I see several other bug reports where people have issues when coordinates are negative. My second monitor is bigger that the laptop display and it's positioned higher than the laptop's display:
![image](https://user-images.githubusercontent.com/2222578/119656232-847c0400-be3b-11eb-97ce-24c7be7ee71c.png)
The issue reproduces only on the second monitor and when cursor position is above the top left position of the primary monitor. That is it reproduces here:
![image](https://user-images.githubusercontent.com/2222578/119656388-ad03fe00-be3b-11eb-94f8-4629ba5022aa.png)
It reproduces already at lest several months. I was lazily waiting that maybe somebody will fix it. But looks like the only way to get it fixed is to do it yourself.

**Comment by Jaex** [comment]
> It reproduces already at lest several months. I was lazily waiting that maybe somebody will fix it. But looks like the only way to get it fixed is to do it yourself.

I don't have multi monitor. So I can't reproduce it.
