### ISSUE TITLE
After selecting an area, make an additional request from the program to confirm the boundaries of the area?

### ISSUE THREAD

**Issue by it19862** [ShareX/ShareX#5162]
When you select an area, the area boundaries are shifted.
This does not always happen, but it does sometimes.
In other words, the picture is cropped, and not within the boundaries that I chose.
ShareX sets the start point of the area selection not at the time of the code the user performs the left keel, but after the left click, with a delay.
I suspect that this is due to the fact that I have a weak computer.

In other words, I am doing:
  **1.** left click (keep it pressed) - point-start of area selection;
  **2.** I start to move the mouse cursor down to the right;
  **3.** ShareX includes a selection area;
  **4.** I finish moving the mouse cursor - the finish point of the area selection;
 
**Problem.**
   - ShareX at step "1" does not set the start point of the area selection, but sets the start point of the area selection at step 3;
 
**Question.**
  How to make ShareX provide an option to resize the area after selecting the area?

**Example:**
        - chose an area;
        - pressed the "Ok" button.
   Similar functionality is implemented in **Lightshot.**
In other words, after selecting an area, make an additional request from the program for an additional action.

**Comment by Jaex** [comment]
You can use this option:

![](https://jaex.getsharex.com/2020/10/ShareX_lBUYF0Gs3C.png)
