### ISSUE TITLE
[Feature] Keyboard shortcuts for Region Capture Options

### ISSUE THREAD

**Issue by TimRoenicke** [ShareX/ShareX#5164]
The regions seem to be the only elements that don't have a shortcut. https://getsharex.com/docs/region-capture

It would be nice to be able to select our own bindings here or at least have bindings available for the regions. Able to press `A` draw the arrow then something like `Shift+R` to move back to the rectangle region would be a quicker workflow. The ability to easily do most shortcuts from the left hand would be ideal.

**Comment by Jaex** [comment]
Press <kbd>Tab</kbd>.
