### ISSUE TITLE
Region Capture - Missing the magnified guide section?

### ISSUE THREAD

**Issue by Robmonster** [ShareX/ShareX#5166]
Hi there,

I've noticed that when capturing a Region I no longer have the small magnified section near the cursor that helps line up the area nto capture.  I don't believe I've updated the app, any idea how I can get this back? Is it on a Hotkey I have accidentally pressed?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/11/ShareX_dIlMbH2jmw.png)
