### ISSUE TITLE
Steps are smaller when border is added and picture saved

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#5167]
Please follow the steps to reproduce the bug.

1. Edit an image with ShareX
2. Add steps, for example, 1, 2, 3
3. Save the image and inspect the image (see screenshot without border)

All is great.

4. Add a border to the image (see screenshot border)
5. Save image as
6. Inspect the image (see screenshot with border)

The steps are smaller. 

This happens when you add a border to the image and save the image. See attached screenshots.

I hope you can reproduce the issue and if not, let me know and I prove more screenshots or details. It happens not only on my system but on other systems too.

![without border](https://user-images.githubusercontent.com/12443285/97967380-6d9d9380-1dbd-11eb-90cd-6ef0d1e6e143.png)
![with border](https://user-images.githubusercontent.com/12443285/97967384-6e362a00-1dbd-11eb-9991-68bfd25ca8c8.png)
![border](https://user-images.githubusercontent.com/12443285/97967385-6e362a00-1dbd-11eb-9843-592cd60cf230.png)

**Comment by worldsdream** [comment]
If this is not a bug and this is happening because of the border, please let me know how to edit the border to make sure that it's not shrinking the steps. Thank you.

**Comment by Jaex** [comment]
I can't reproduce the issue.

**Comment by worldsdream** [comment]
I will sent more steps or a video on how to reproduce. I hope to do that by tomorrow.

**Comment by worldsdream** [comment]
@Jaex I hope that this gives you more information. 

https://mega.nz/file/PixwjLBZ#KvhT5s5yHLvf1ZveaXBm_A82SjmfzzotXRpiRmNMaqk

**Comment by worldsdream** [comment]
@Jaex I know you are busy, can you please have a look at the video and tell me if you can confirm this issue?

**Comment by worldsdream** [comment]
Problem is still here.

**Comment by worldsdream** [comment]
Problem still here

**Comment by worldsdream** [comment]
Problem is still here

**Comment by cknori** [comment]
@worldsdream I am interested in resolving this issue. I seem to be unable to reproduce the problem as well. is the issue still here and if so, would you be willing to re-upload the video? It appears the Mega link you provided no longer works.
