### ISSUE TITLE
[Screen Recording] Windows not being detected as they used to.

### ISSUE THREAD

**Issue by Gamartto** [ShareX/ShareX#517]
Hi, I´ve been using Sharex for a while now without any issues. My problem is that due a hardware reconfiguration I had to format my PC and now when I try to record, the program doesn´t detect the windows as it used to do.

Let me explain my issue...I use a program called mRemoteNG as a remote desktop connections aggregator, previously if I wanted to record the session with Sharex I just simply started the capture and Sharex detected the RDP window within the mRemoteNG main window, and that was just perfect since I configured the RDP resolution to 1280x720 so as you can imagine those videos were HD ready.

Now, after formatting and reinstalling the latest version of each program (mRemoteNG v1.72, Sharex 9.7.0, and whatever version of ffmpeg that Sharex downloads), Sharex is not able to detect the window within the main mRemoteNG window, so as you can imagine getting a precise capture of the remote desktop connection is not possible. I know I can create a fixed size recording window but still there´s room for not being precise when selecting the area.

So, is there anything I can do to fix this issue?

Thank you.

**Comment by Jaex** [comment]
Try running ShareX as admin.

**Comment by Gamartto** [comment]
Didn't work.

Here's a screenshot of the issue

http://i.imgur.com/gPziv8N.jpg

The green solid line was added to show the area that previously was able to detect the program... but as you can see even as admin and changing between gdi-grab or scree-capture-recorder the dotted line is what the program is detecting ATM.

Thanks.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/ShareX_SIVXZl0epJ.png) try enabling these.

**Comment by Gamartto** [comment]
Include controls alone did the trick! (no need to run it as an admin).

Thank You!

PS: Are there any sharex forums so I can ask questions like this without raising an "issue"?

**Comment by Jaex** [comment]
There is IRC.
