### ISSUE TITLE
[Enhacement] - Disable and clear "History..."

### ISSUE THREAD

**Issue by RiQuY** [ShareX/ShareX#5174]
I want to disable the history so my recent/new screenshoot URLs don't appear there anymore.

Screenshoot of the menu I want to clear and disable:

![3667ee800a 1](https://user-images.githubusercontent.com/26349954/98403267-9b563700-2060-11eb-9f90-605befdf3879.png)

EDIT: I already know that I can delete the History.json file, but that's just clearing, not disabling the history.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/11/ShareX_4i0Xwz5dSn.png)
