### ISSUE TITLE
[Suggestion] Add a separate option to disable toast notifications.

### ISSUE THREAD

**Issue by turkeyhandwoven** [ShareX/ShareX#5178]
Hi,

I just updated to v13.3.0, and there doesn't seem to be a distinct option to disable the newly added custom toast notifications/balloon tips, for example the ones when using the Color Picker: 
![Notification](https://user-images.githubusercontent.com/56019360/98524976-23625980-2278-11eb-967e-cb129c2ece07.png)

Setting **DisableNotifications** to **True** under **Task Settings -> Advanced -> Notifications** does not disable that notification window for me. I don't want to set this option to True anyway, because I still want to be able to hear sound notifications when doing a screen capture.

The only way I could find to disable these particular notifications is by setting **ToastWindowDuration** and **ToastWindowFadeDuration** to **0**.
Maybe there should be a separate option for this instead.

Sorry if there already is such a setting and I just missed it.

Good day.

**Comment by quriousxr** [comment]
Just want to say thank you @turkeyhandwoven. These notifications are driving me crazy. Really appreciated the solution to disable them.

**Comment by tomasstefanisko** [comment]
I can add a simple setting to disable them without having to change the durations.
