### ISSUE TITLE
Does that mean I did record too much? My precious memory got fucked up. 

### ISSUE THREAD

**Issue by DeepondG** [ShareX/ShareX#5181]
![XIEC7VrlXQ](https://user-images.githubusercontent.com/73928444/98623462-14020f80-234f-11eb-94ca-29999a9f533d.jpg)
I recorded today's live event of D2 for 2 hours, but all I can see is just dark screen. PLZ somebody help me

**Comment by botatooo** [comment]
We don’t recommend recording anything longer than 2 minutes with ShareX, and no your memory isn’t fucked, it’s just that ShareX (or ffmpeg, aka it’s what we use to record) ran out of memory, and the recordings tend to end up being black. If you want to record bigger clips, we recommend [OBS](https://obsproject.com). Lucky for you, there’s most likely other people that recorded D2.

**Comment by DeepondG** [comment]
Thanks. Even though I did lose the record, I could get a good program for recording my screen. Appreciate your hard work.
