### ISSUE TITLE
catbox.moe not working

### ISSUE THREAD

**Issue by xavierxross** [ShareX/ShareX#5189]
I wanna use catbox as custom uploader but its showing error> https://i.imgur.com/lhaWnNx.png

**Comment by xavierxross** [comment]
Fixed now!

**Comment by GattoDev-debug** [comment]
redacted previous comment, sorry for the offensiveness, didnt mean that.

**Comment by Kekerykek** [comment]
@GattoDev-debug, just do it manually like this. Something must've changed along the way, the file method doesn't work for some reason. You can add your userhash if you wanna upload the file to your Catbox account.

![Image](https://github.com/user-attachments/assets/23d42bd7-54c2-45a7-b6e8-f5fe0c1b8338)

**Comment by GattoDev-debug** [comment]
Thanks.

**Comment by sketchioh-hub** [comment]
> motherfucker
> 
> # TELL US HOW
> how do people just say that without giving explanation are you a fucking idiot

Lol. What a fucking prick.
