### ISSUE TITLE
Print Screen Key

### ISSUE THREAD

**Issue by donnje** [ShareX/ShareX#5191]
Hi,
If I open some programs on the desktop (eg CrystalDiskMark 7) the "Print Screen" key of the keyboard does not save the image while it works with the software command, can anyone solve?
Thanks

**Comment by Jaex** [comment]
If active app is ran as admin then ShareX also must ran as admin for hotkey to work.

**Comment by donnje** [comment]
Thanks a lot so it works, but there is a new problem that is not loaded when windows start even if set in automatic executions while this works if I disable "run with administrator" do you have any ideas for solve it, please?
