### ISSUE TITLE
Feature request: editor right click not exiting

### ISSUE THREAD

**Issue by cloo** [ShareX/ShareX#5195]
I do not use ShareX daily, and I often hit right-click by accident, which is an instinct to see what options of any tool are available (it is default behaviour in many apps). This way I have by accident lost quite a few annotations and had to restart the work. 
So I suggest to change the binding, or even make it customizable.

**Comment by Jaex** [comment]
This?

![](https://jaex.getsharex.com/2020/11/ShareX_HwHLDGw5rP.png)

**Comment by cloo** [comment]
It works, thank you!
But by description I shouldn't, as it describes capture process, which is different context, where right-click cancel is actually convenient. Thus I didnt even try it at first.
