### ISSUE TITLE
History - Video - Convert to GIF

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#5199]
Is it possible to have quick way to convert previously saved video to GIF? Some sites doesn't support video uploads and manual conversion makes me crazy

**Comment by Jaex** [comment]
This is one way:

![](https://jaex.getsharex.com/2020/11/ShareX_W32yTAbMna.png)

Arguments:

```-i %input -lavfi "palettegen=stats_mode=full[palette],[0:v][palette]paletteuse=dither=sierra2_4a" -y %output```

![](https://jaex.getsharex.com/2020/11/ShareX_2PF9Jvrwmp.png)
