### ISSUE TITLE
Raw file URL for Google Drive

### ISSUE THREAD

**Issue by quasar** [ShareX/ShareX#520]
Is it possible to make an option for Google Drive, when you upload an image or a file, in return you'll get not just a shareable link, but direct link to file. I think it is called "webContentLink" 

I mean not https://docs.google.com/file/d/<id>/edit, but https://lh4.googleusercontent.com/<blahblahblah-id>

**Comment by Jaex** [comment]
Response was not including direct link.

**Comment by Jaex** [comment]
Raw file url not exist in response therefore I can't make an option for it.
