### ISSUE TITLE
Request: Follow mouse cursor region video capture

### ISSUE THREAD

**Issue by Cookiebot1** [ShareX/ShareX#5201]
I would love to have a option to specify a region size for video capture that would follow the mouse around. Would make tutorial recording a lot easier. Mouse would be in the center.

**Comment by dj-nitehawk** [comment]
count me in for this too. i've been doing it with bandicam but sharex seems very good.

**Comment by Permanently** [comment]
Shame this suggestion fell through. I think this feature would be great for ShareX.

**Comment by Aetherinox** [comment]
Was just looking for this feature. Sad to see it not a thing.
