### ISSUE TITLE
Capture videos in free size

### ISSUE THREAD

**Issue by Hwang372** [ShareX/ShareX#5203]
Hello, first of all, thank you for making a good program.
Using ShareX, it is easy to use to capture videos in local size. However, I want to capture videos in free size, what should I do?

 If there is no such function, can I try making it?

**Comment by Ma-ve** [comment]
Hi! What do you mean by 'local' size and 'free' size?

**Comment by Hwang372** [comment]
free size means It's capturing the area I want, like image capture.
but, When I record a screen, the specified area is based on the full screen or the window that is open.
that means 'local size'

**Comment by Hwang372** [comment]
Sorry, i Find that function, thank you
