### ISSUE TITLE
After capture window forces game window to "Stay on top" forever

### ISSUE THREAD

**Issue by Neoony** [ShareX/ShareX#5207]
It seems that when capturing a windowed borderless game and having Show "After capture" window enabled, this forces the game window to stay on top, but it is never removed after closing "After capture" window

Reproduce:
Make sure that Show "After capture" window is enabled.
Start Rocket League in Borderless windowed (probably any windowed works too)
Capture a picture to make After capture window open.
Now try to alt-tab to something else and notice that the game window is always staying on top of everything, even after closing "After capture" window

Right now using Displayfusion to toggle "Stay on top" off

**Comment by TheCatMan2000** [comment]
I have this same problem while playing PAYDAY 2.

Not only does the game window stay on top of everything, it makes everything on my other monitor inaccessible while ShareX is running.

**Comment by quetzalcoatl** [comment]
If you can find HWND "handle" of the problematic window, you can strip WS_EX_TOPMOST flag from it with this powershell script:

    $handle = 0x50812       # replace with the HWND handle you've found

    $signature = @'
    [DllImport("user32.dll")]
    public static extern bool SetWindowPos(IntPtr hWnd,IntPtr hWndInsertAfter,int X,int Y,int cx,int cy,uint uFlags);
    '@
    $type = Add-Type -MemberDefinition $signature -Name SetWindowPosition -Namespace SetWindowPos -Using System.Text -PassThru
    $flags = New-Object -TypeName System.IntPtr -ArgumentList (-2)
    $type::SetWindowPos($handle, $flags, 0, 0, 0, 0, 0x0013)

"-2" in the $flags is HWND_NOTOPMOST
"0x13" in the last line is SWP_NOSIZE | SWP_NOMOVE|SWP_NOACTIVATE
