### ISSUE TITLE
Fail to upload gif to imgur.

### ISSUE THREAD

**Issue by akbuddy** [ShareX/ShareX#521]
Hi! when I try to upload a gif to imgur I get this message: http://i.imgur.com/vyUkooa.png. And the limit on imgur is much more than 10mb. I talked to imgur support as i was told by someone in your IRC. Imgur said that it was a problem with shareX and not them. (http://i.imgur.com/ZJPx0PV.png) It works when i upload manually though their site. I have tried to upload with and without imgur account.
Anyone else who has this problem or knows how to solve it?

**Comment by Jaex** [comment]
It is nothing to do with ShareX obviously.

**Comment by akbuddy** [comment]
Okey, so the limit is then 10 mb wehn i use share x, or?

**Comment by Jaex** [comment]
Their API have 10mb limit.

**Comment by akbuddy** [comment]
Thanks for quik answer, i dont know what API is. Is share x using their api, so u are limited to 10 mb? Or i there any way i can upload larger files with sharex?

**Comment by Jaex** [comment]
They don't allow ShareX to upload bigger than 10mb size.

**Comment by akbuddy** [comment]
Okey thank you. Do u know any other image host that do?

**Comment by Jaex** [comment]
I'm using Dropbox.

**Comment by akbuddy** [comment]
Okey thanks

**Comment by Silithas** [comment]
Jaex, that sucks, cause then i have to manually upload the gifs to imgur by dragging them from the result list to the upload page on imgur
