### ISSUE TITLE
TAKE A LOOT AT THIS ERROR REPORTED FROM SHAREX 9.7

### ISSUE THREAD

**Issue by apometron** [ShareX/ShareX#522]
Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html >
<head >< title > 405 Not Allowed </ title></ head>
< body bgcolor="white" >
< center >< h1 > 405 Not Allowed </ h1></ center>
< hr >< center > nginx </ center>
</ body>
</ html>

StackTrace:
![2015-02-20_13-25-26](https://cloud.githubusercontent.com/assets/4054252/6289080/b79cffda-b904-11e4-857c-612a2a369107.png)

   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)

**Comment by Jaex** [comment]
Which host gave this error?

**Comment by apometron** [comment]
I DONT KNOW WHAT HOST IT IS. I JUST DID TRY IT AND IT FAILED.

LETS TRY AGAIN, WHAT DO YOU THINK?

**Comment by Jaex** [comment]
Were you uploading to Imgur?

**Comment by apometron** [comment]
YES, I THINK IT IS BECAUSE I DONT CHANGED NOTHING IN THE CONFIG. SO, I THINK IT IS.

**Comment by Jaex** [comment]
I think their server was down when you uploading. Is it works now?

**Comment by apometron** [comment]
LETS TRY AGAIN. =D

**Comment by apometron** [comment]
WOOOOOOW, PERFECTLY.

http://i.imgur.com/9k7oHkm.png

=)

**Comment by Stanzilla** [comment]
your capslock key is stuck

**Comment by apometron** [comment]
Sorry. =(
