### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by xHyroM** [ShareX/ShareX#5222]
Please create for linux (ubuntu, debian)

**Comment by sujay1844** [comment]
yes please create for linux.

**Comment by sujay1844** [comment]
@Jaex  duplicate to what??

**Comment by botatooo** [comment]
> @Jaex duplicate to what??

I don't need to say it again; https://github.com/ShareX/ShareX/issues/5028#issuecomment-689893321

**Comment by McoreD** [comment]
There could be some hope in 2 years. No promises!
