### ISSUE TITLE
Capture is cancelled if you press Enter while in capture mode without selecting anything

### ISSUE THREAD

**Issue by wodim** [ShareX/ShareX#5223]
1. Press Ctrl+Print Screen, entering capture mode

2. Without selecting anything, press Enter

Capture mode is cancelled and nothing is captured. I think that either 1) whatever is selected by the marching ants should be captured, 2) the entire screen should be captured, or 3) the application should remain in capture mode.

I think the current behaviour of closing capture mode without capturing anything as if you had pressed the Escape key is wrong. The Enter key is supposed to do something; the way it is now it behaves as if you had cancelled.

**Comment by Jaex** [comment]
Are you not using ShareX 13.3?

**Comment by wodim** [comment]
Yes, but my configuration file is very, very old. Maybe the default changed sometime in between? In that case which option should I change?

**Comment by wodim** [comment]
...

**Comment by wodim** [comment]
@Jaex

**Comment by Jaex** [comment]
I can't reproduce it, Enter captures currently hovered region for me.
