### ISSUE TITLE
Screen color picker picking up incorrect colors

### ISSUE THREAD

**Issue by PriyadarshiBros** [ShareX/ShareX#5231]
This is happening only on my second and third monitors. When I pick up a color on my laptop, it shows #4164af which is correct. However, when I choose the same color on my extended monitors it shows #3766ac which is similar but incorrect.

Can you help me out with this?

**Comment by yashpalgoyal1304** [comment]
hi, can u see if that issue fits ur scenario? if so, then add ur input there and close this issue (: generally, newer duplicates are closed, but that issue already has more input. So.

**Comment by yashpalgoyal1304** [comment]
https://github.com/ShareX/ShareX/issues/5259
