### ISSUE TITLE
Error when upload to transfer.sh

### ISSUE THREAD

**Issue by GreenAndBlueG** [ShareX/ShareX#5232]
Transfer.sh has changed the domain and now use [transfersh.com](https://transfersh.com/).

So ShareX fails to upload a file on that service

![sharex error](https://i.imgur.com/YPHKn48.png)

> *English? Not my primary language*
> *If there are some errors of any kind feel free to tell me and i will corrent 😉*

**Comment by Jaex** [comment]
https://transfersh.com not looks like official.

https://github.com/dutchcoders/transfer.sh/issues/326

**Comment by Jaex** [comment]
https://transfer.sh is up now.
