### ISSUE TITLE
Feature Request: selecting/copying/pasting objects in the image editor

### ISSUE THREAD

**Issue by patefoniq** [ShareX/ShareX#5236]
Hi,
in short words.

Please add/improve copying and multi-selecting objects in the image editor. I see this like that:
I am selecting a few objects and then I just copy them and paste them next door like in all programs (paint, word, excel, photoshop, corel, dreamweaver etc.). Is it possible to implement this improvement?
Now it is not working properly and what worse when I copy the object then it pastes as text (with some co-ordinates) and a fragment of copied object. The same is with selecting, there is no possibility to select more than one object in the image editor.

It's the most long-awaited change for me and most of the users, I think.

I wait for hearing from you. Thanks.

**Comment by Jaex** [comment]
Currently you can use <kbd>Ctrl + D</kbd> hotkey to dupicate objects. So it will be similar to copy/pasting.

**Comment by patefoniq** [comment]
I know that function but still, it works only for one-by-one objects. What if I have the arrow with text and counter and I would like to copy all the three treating it like one object? And so on several times.

**Comment by Jaex** [comment]
Implementing that would be too much work.

**Comment by patefoniq** [comment]
What about the selecting itself via selecting tool (like everywhere else)? If selecting will work properly "duplicate" function could be enough.

**Comment by patefoniq** [comment]
Is any chance to make this improvement in the closest time?

**Comment by aisbergde** [comment]
Would be fine to reopen the issue:
I am looking for a way to select an area and then to copy this area and to past as a copy.
I want to duplicate a specific selected area.
An intuitive way would be to use the "Select and move" (Arrow tool) to be able to select a region (press mouse button and drag).
Currently, it is possible to copy the whole image, but not only a part.
