### ISSUE TITLE
Error message at startup, when users are in home working

### ISSUE THREAD

**Issue by lediabolo** [ShareX/ShareX#5238]
Hello

I 've a remark which is of importance to me because I'm in the case where my users start their computer from home (home working). And the company's Documents folder is therefore not yet present and we have error messages.
![2020-12-03_082134](https://user-images.githubusercontent.com/22579607/101018573-fe59c180-356b-11eb-803d-21bdd1fd76b8.png)

Users must first start the VPN but ShareX obviously starts before the VPN is manually started.

Actually, I think that ShareX should not write JSON configuration files to **C:\Users\\%USERNAME%\Documents\\**
but rather in **%APPDATA%** as most applications do (GIMP, XnView, VLC, FileZilla...).
The **%APPDATA%** folder is making to store application information for each users.
Documents folder is used to put documents (Word documents for example) and not to put configuration files or Logs.

In my case, moving these JSON files in **%APPDATA%** will avoid to have error popups to startup of ShareX. 
In my company, the user profil is synchronized, but not the Documents (because it's to big)

Please, let me know what you think of it

**Comment by botatooo** [comment]
You can change where ShareX stores configuration files.

**Comment by lediabolo** [comment]
This one, the ShareX personal folder ?
![B6tA74Kr6k](https://user-images.githubusercontent.com/22579607/101019928-fb5fd080-356d-11eb-8e19-a9b82a0f7ba7.png)

**Comment by botatooo** [comment]
> This one, the ShareX personal folder ?

Yeah, and then click apply. 
*PS: You’ll need to copy your old configuration files to this new folder.*

**Comment by lediabolo** [comment]
Ok, I'll test it.
thanks very much :)

**Comment by lediabolo** [comment]
It work, thank you very much
