### ISSUE TITLE
Bug: wrong file extension using annotate after screenshot, unable to edit/view/copy results

### ISSUE THREAD

**Issue by hippalectryon-0** [ShareX/ShareX#5239]
Version: 13.3 on Windows 10 10.0.18363 Build 18363 x64

Here's the bug (my default output is PNG):
* Capture part of the screen
* Click "annotate"
* Click either "apply changes and continue" or  "continue task"
* Result: the file appears as "[filename].bmp" instead of ".png", and it is not saved to local folders. Therefore, all the menus are greyed out and the file is not copied to clipboard.

![image](https://user-images.githubusercontent.com/6502864/101042922-facf3600-357d-11eb-9f8f-1b64d154c60a.png)

Remark: this does not happen if I use the annotate tool on already-saved images.

Settings below:

![ShareX_3q58xdDMOA](https://user-images.githubusercontent.com/6502864/101042842-e2f7b200-357d-11eb-80a3-3f3d64d2a777.png)

![image](https://user-images.githubusercontent.com/6502864/101042867-eb4fed00-357d-11eb-856a-7e4c0a2e68c9.png)

**Comment by RobFreundlich** [comment]
I'm having the same problem with version 13.4

**Comment by PrincessAkira** [comment]
Hey,

i have the same Problem. I cant even overwrite the Hotkey Image settings. Everything is saved as BMP, when i have JPG and PNG etc. selected. It started suddenly, and i have no idea what the hell is happening. I can copy the images to clipboard tho after Upload, but there arent any files created, so when i select ,,Open Folder,, it wont open it while it exists in Clipboard.
