### ISSUE TITLE
Font in 13.2.1 used to look more crisp and more legible

### ISSUE THREAD

**Issue by stdedos** [ShareX/ShareX#5241]
![image](https://user-images.githubusercontent.com/133706/101075773-23b9f000-35ab-11eb-98e0-e42b29f5948d.png)

vs

![image](https://user-images.githubusercontent.com/133706/101075121-4566a780-35aa-11eb-9c2a-455491d58775.png)

**Comment by Jaex** [comment]
Font is same.

**Comment by stdedos** [comment]
I did re-do the ClearType settings (just in case it was different), but I don't see a difference:

![image](https://user-images.githubusercontent.com/133706/101076058-83180000-35ab-11eb-85e5-edd50ab5b4f7.png)

Sublime Merge has a nice "Onion Skin" image diff feature, but that requires to commit the images to repo to see the difference.

**Comment by stdedos** [comment]
(They are exactly the same, https://online-image-comparison.com/):
![image](https://user-images.githubusercontent.com/133706/101076397-00dc0b80-35ac-11eb-9fca-90a0f87bf8a1.png)

**Comment by Jaex** [comment]
You can set it 9pt:

![](https://jaex.getsharex.com/2020/12/ShareX_dROm5sNMW8.png)

**Comment by stdedos** [comment]
"Restored to original defaults". Thanks!

`Segoe UI; 10pt; Semi-bold` can be an option too (although after confirming:
* it returns: `Segoe UI Semibold; 9,75pt; style=Bold`
* affects the "Show Cursor" boldness, and
* the Font window "is uninitialized" if/when it is opened again
)
