### ISSUE TITLE
Cannot save settings in screen recorder options. GDI grab always selected

### ISSUE THREAD

**Issue by N00ree** [ShareX/ShareX#5244]
Hi,

The GDI grab is selected as default and I cannot change it.
The default behavior is that it saves all settings automatically.
But if I close this settings window it will switch to GDI grab again.

![WlHhShusBr](https://user-images.githubusercontent.com/61552289/101185540-494e0480-3652-11eb-9afc-df20def2ae7c.gif)

And this also happens when clicking on the refresh button left to the video source option.

Temporary fix:
Leave the settings window open after changing to "screen-capture-recorder" and it will record with this setting applied.

regards
Nuri

**Comment by Neoony** [comment]
Yes, I have noticed the exact same thing

**Comment by Neoony** [comment]
![gif](https://i.imgur.com/q3eX1yB.gif)

**Comment by Neoony** [comment]
Right
I guess its fixed here
https://github.com/ShareX/ShareX/commit/0b23ff9b050e97e54f823290e23231c33b21f2c1

Issue: https://github.com/ShareX/ShareX/issues/5179

**Comment by sylveon** [comment]
Install the dev builds for the fix https://getsharex.com/docs/dev-builds

**Comment by N00ree** [comment]
Will do. Thanks
