### ISSUE TITLE
Can't change the folder destination of saving screen recordings

### ISSUE THREAD

**Issue by Hakeem-HEK** [ShareX/ShareX#5246]
The screen recordings are been saved in a deep path of folder destination. I want to save the screen recording in a path which is easy for me. I want the option to be added at the place of "Screen recording options..."

![2020-12-05 Saturday 05 41 PM](https://user-images.githubusercontent.com/75527715/101242744-5980e500-3721-11eb-9935-0678946a3ba4.png)

![2020-12-05 Saturday 05 41 PM (2)](https://user-images.githubusercontent.com/75527715/101242740-5685f480-3721-11eb-83ac-e3d5383695e2.png)

**Comment by NikolayEKolev** [comment]
![3lIDuLjga8](https://user-images.githubusercontent.com/70388317/102024148-dbfc4b00-3d98-11eb-86f2-ee45aa240b50.jpg)

**Comment by yashpalgoyal1304** [comment]
@Hakeem-HEK hi, i hope ur issue is solved with @NikolayEKolev's input. If so, then u can close the issue (:

**Comment by Hakeem-HEK** [comment]
> @Hakeem-HEK hi, i hope ur issue is solved with @NikolayEKolev's input. If so, then u can close the issue (:

Thanks a lot
