### ISSUE TITLE
FYI: Win7 & TLS 1.2

### ISSUE THREAD

**Issue by Astara** [ShareX/ShareX#5249]
I'm on Win7x64SP1 and as soon as I started ShareX, it notified me about the new update.  

Read the release notes and noticed the caveat about TLS1.2 for Win7 -- tried to update and **it worked normally**.

Sometime back, after MS stopped with sending out updates for Win7, the 1.2TLS support was released.  MS didn't mark it as a security update, so it had to be loaded/installed separately.  It is still available, as it is part of the procedure to upgrade for Win7 Long-Term support for Businesses (through 2023).  So if you search for MS's extended or long term support, its in one of the updates needed.

**Comment by Jaex** [comment]
I think 99% of users don't have that update installed. I tried on Windows 7 VM and had all auto updates done still didn't support it.

**Comment by Astara** [comment]
It is not an auto update.  It has to be installed manually as part of preparing to install "Extended Security Updates".    From this link ([(https://techcommunity.microsoft.com/t5/windows-it-pro-blog/obtaining-extended-security-updates-for-eligible-windows-devices/ba-p/1167091)]), I see links on that page (not sure which are needed; I installed all, at one point) for KB4490628 (https://support.microsoft.com/help/4490628), KB4474419 (https://support.microsoft.com/help/4474419), KB4562030 (https://support.microsoft.com/help/4562030) and KB4538483 (https://support.microsoft.com/help/4538483).  I think you should be able to check in Windows 7 installed programs+updates (updates toggled on, I usually sort by installed data after displaying that column) to see which you might need.  

Also, FWIW, I have both IE(11?) and MS Edge installed.  Security updates for either of those should also have pulled in latest TLS, as the older ones weren't considered that secure anymore....oops, IE11 just crash, so that might not be working ( :-) ), but MS-edge still works and is being updated, so that's probably the one to go with (don't really use them, except for testing things that don't work in other browsers).

Hope this helps...

**Comment by Astara** [comment]
@Jaex -- what feature was missing caused win7 probs?  Am curious as I found one of the updates MS released as a hot fix for adding:
./MS/win6.1/windows6.1-add_SHA2_to_Win7.msu
Also for tsl updates I found:

Microsoft WinHTTP support for TLS 1.1 and TLS 1.2 Missing ...
https://social.technet.microsoft.com › Forums › en-US
Apr 25, 2019 · 3 posts
Microsoft now released KB 3140245 which allows Administrators to specify which SSL protocols should be used when the ...

Was it one of those? If so I could upload it here for those who need it...
