### ISSUE TITLE
Replace Mediacru.sh with Imgrush

### ISSUE THREAD

**Issue by sergeevabc** [ShareX/ShareX#525]
Dear ShareX,
Mediacru.sh was [recently closed][1].
Community offered a clone replacement called [Imgrush][2].

Please, update.

[1]: http://www.reddit.com/r/MediaCrush
[2]: https://imgrush.com/

**Comment by Jaex** [comment]
Are you telling this right after I delete it? Am I supposed to re add all UI stuff now with all their translations...

**Comment by sergeevabc** [comment]
Could you be so kind to add IMGRush option to copy Direct URL to clipboard after upload?
Now it leads to a [page with image and other stuff][1].
[1]: https://imgrush.com/rHAjZf_DTDSH

**Comment by Jaex** [comment]
This is why i told you right after I deleted UI options for mediacrush you requested it and I'm lazy about ui stuff :P

**Comment by sergeevabc** [comment]
Dear @Jaex, there’s a reason why ShareX is the hallmark of screenshot Windows apps out there (except for grabbing windows with scroll, alas). Reason, i believe, is the flexibility achieved by means of wide variety of options, right? Let's maintain its reputation.
