### ISSUE TITLE
Suggestion : quick resize

### ISSUE THREAD

**Issue by nonobio** [ShareX/ShareX#5253]
Hello :)

I often want to resize my screenshot before to copy it elsewhere (mail, note, etc.).

ShareX can resize from its menu "Picture\Picture size" but i have to enter the pixel numbers.

So, actually i use another app : ["rEASYze"](https://www.reasyze.com/) where i paste my clipboard and use the "quick size" button to resize image, and i copy the result in my clipboard:

![image](https://user-images.githubusercontent.com/7425799/101477494-96322380-394f-11eb-80fd-5040d84bf5fb.png)

The process is quick but it could be useful to have a button like this right in ShareX (editor and/or toolbar) or an action like "resize and copy to clipboard".

What do you think ?

Thanks :)

**Comment by nonobio** [comment]
I still think it could be a useful feature.

**Comment by rcdailey** [comment]
Yes I'd love to see this as well. It's a pain to dig through these toolbar menus.

**Comment by mdissel** [comment]
Very handy feature!

**Comment by nonobio** [comment]
I still think it could be a useful feature.

**Comment by nekocarpet** [comment]
Was in need of something similar. Then discovered the "rescale" and "resize" effect. Add it to your effect preset and enable it in "After capture tasks". Your screenshot will then be automatically resized and copied.

![image](https://github.com/ShareX/ShareX/assets/103965383/080009bf-2e51-4b35-8275-7969abf587b5)

The "resize" feature also came with an if function which is very handy if you need to target a specific size.

**Comment by nonobio** [comment]
Hi,
This isn't exactly what I'm looking for because I want to have the choice of resizing for each capture, but thanks for the tip :)
