### ISSUE TITLE
Mouse Cursor Jumps during GIF recording over RDC

### ISSUE THREAD

**Issue by evlas1013** [ShareX/ShareX#5254]
This is a bit complicated but here's my issue. 
I'm using remote desktop connection since I'm working remotely now....

When I try to capture a GIF of my remote session, the mouse jumps all over the place.

ShareX is installed on my remote system so that may have something to do with it. 
I am unable to trigger my (local) ShareX hotkeys when my RDC is active.

![3bvfTFnzLK](https://user-images.githubusercontent.com/14222342/101503180-d38eb500-393f-11eb-927e-909448bc3507.gif)

**Comment by rminderhoud** [comment]
I can confirm this is still an issue on ShareX 13.5. Same visual effect as the recording above but with windows local using windows RDP to windows remote.
