### ISSUE TITLE
Oval picture every single time...

### ISSUE THREAD

**Issue by Pwnership** [ShareX/ShareX#5255]
https://puu.sh/GVAky/01dff22e6a.png

Why??

**Comment by Jaex** [comment]
Select this in region capture:

![](https://jaex.getsharex.com/2020/12/ShareX_GeDLWzTz2X.png)

**Comment by Pwnership** [comment]
I don't see where that is to select it, why after over 2 years of using this does this happen without me changing anything?  I have been looking for such setting for about 8 months now.
