### ISSUE TITLE
(Screen) Color Picker picks incorrectly

### ISSUE THREAD

**Issue by VipSaran** [ShareX/ShareX#5259]
![image](https://user-images.githubusercontent.com/995948/101773473-1b067400-3aed-11eb-8215-00b8d1b4eb33.png)

**Comment by Marium045** [comment]
Sometimes it happens to me too. When I select the color it didn't select as the same. But didn't happen all time. Are you facing the issue all the time?

**Comment by VipSaran** [comment]
@Marium045 only those few times i used it. Since I lost trust in results it's giving, I had to use different tool to get the job done.

**Comment by Infinitay** [comment]
I recently faced a similar _issue_, but I don't think it's fair to label it as an issue. I also noticed the hex code differs depending on my monitor. I believe things such as color profiles (perhaps software versus hardware) affects the results.
