### ISSUE TITLE
ShareX Action Toolbar replacement/hovering

### ISSUE THREAD

**Issue by janborup** [ShareX/ShareX#5260]
**Hi a small request..** 

I'm using the ShareX Action Toolbar on-top anytime, but there it a small problem.

The Toolbar fills to much on the screen, even if I only had the smalles amount of items in the bar
![image](https://user-images.githubusercontent.com/6866443/101795179-ec49c700-3b07-11eb-900d-6e87402a9564.png)

**Question/Task:**
Could the ShareX Action Toolbar be replace by another smaller item, like a sticker or a smaller bar, that can expand when hovering over the bar.

![image](https://user-images.githubusercontent.com/6866443/101796657-70507e80-3b09-11eb-9d5d-586d069dd32e.png)

When hovering the Icon.
![image](https://user-images.githubusercontent.com/6866443/101796871-aee63900-3b09-11eb-9cd9-b46482a9659c.png)

Best christimas regards
From Denmark

**Comment by A-Sparowe** [comment]
I was just looking into something like this for the Action Bar. Is it possible to edit the background color of the action bar or the transparency? I wouldn't mind it staying on top as much if I could make the background semi-transparent or completely transparent while leaving the icons of my actions visible. I use it primarily for screenshots while gaming and the way I have my in game hud setup I have a small area designated for the action bar. I know every user has their own preferences when using anything and while browsing the web or when using other desktop applications on my 4K screen I tend to center most of my windows while leaving margins on the window borders and the border of my display creating a "picture frame" is the best way to describe it. This is where I put things like ShareX action bar among others.
