### ISSUE TITLE
Suggestion: Circular buffer for recording

### ISSUE THREAD

**Issue by mtranchi** [ShareX/ShareX#5266]
I'd like to continuously record a part of the screen but only keep, say, the last 5 minutes. Ideally how much history to keep would be adjustable, i.e. 1 minute up to whatever. I reckon this would have to be done in RAM, which I'd prefer anyway. Why would I like this? I often have a news streaming service running and sometimes I'd like to be able include something that they just said in a blog post. Or sometime be able to capture commercials and do parodies of them, [like this one](https://www.youtube.com/watch?v=jlSF0dtDRD8)

**Comment by SMerlock7** [comment]
+1
