### ISSUE TITLE
Cannot stick on screen-capture-recorder in screen recording options

### ISSUE THREAD

**Issue by AliZ14-ECE** [ShareX/ShareX#5267]
Hey all - when I record with my GDI Grab, there is a delay between audio and video. For some reason, since recently, when I select screen-capture-recorder in my options, it immediately changes back to GDI grab once I close the window, essentially removing the option to use screen-capture-recorder at all. I've tried reinstalling the recorder devices to no avail. How can I solve this?
Here is how it looks like: [https://streamable.com/lj212t](url)

**Comment by Neoony** [comment]
Just download the dev build
It has been fixed already 

[img](https://i.imgur.com/teg2gMk.png)

fixed here: https://github.com/ShareX/ShareX/commit/0b23ff9b050e97e54f823290e23231c33b21f2c1
issue: https://github.com/ShareX/ShareX/issues/5179
