### ISSUE TITLE
Screen recorder video source keeps resetting itself to "GDI grab"

### ISSUE THREAD

**Issue by MaxLebled** [ShareX/ShareX#5269]
[Video of the issue here.](https://dl.dropboxusercontent.com/s/37ueay3jca5u306/2020-12-15_18-41-07.mp4)

Only workaround I could find was to go in ApplicationConfig.json and replace

`        "VideoSource": "GDI grab",`

by

`        "VideoSource": "screen-capture-recorder"`

Nothing short of this will prevent GDI grab from being used once the settings window is closed.

**Comment by Jaex** [comment]
Duplicate of #5179
