### ISSUE TITLE
Accidently pressed Abort on a recording - any way to recover?

### ISSUE THREAD

**Issue by itheropro** [ShareX/ShareX#5273]
I accidently pressed on Abort instead of Stop. The recording is gone now. I noticed, however, that the mp4 file is created and keeps being populated with data as the recording is being performed. If you click Stop the file remains, if you click Abort the file disappears.
Is there any chance to recover the file by using file recovery tools? Is the file marked as deleted in the file system, or it is more than just that? Is it worth trying to search by the signature: MP4 or the data written on the disk is not complete to qualify as a consistent file?

Any help would be very helpful. I am desperate at this point, willing to try anything if there is a slight chance.

Thanks!

**Comment by yashpalgoyal1304** [comment]
hi, this issue is duplicate of #5262
