### ISSUE TITLE
new feature request : specify various folders that can be saved

### ISSUE THREAD

**Issue by FingerDrill** [ShareX/ShareX#5274]
I am mainly using sharex by capturing in rectangular mode.
When I start the rectangle mode, I can designate the area I want, and it would be nice if I could save it in one of the various folders that I have set in advance. Of course, in this rectangle mode, I wish I could designate a folder using shortcuts 1,2,3,4, ... etc. 
The reason I want this function is that I want to divide it into folders by the information I capture.

**Comment by kc8** [comment]
@FingerDrill I believe you can currently do this within the Hotkey settings by Hot Key Settings > Add... > Override After capture Settings then at the bottom Override screenshots folder. 
Give the new task a description, close the window then to the right of the description box click the white box and enter your desired shortcuts
