### ISSUE TITLE
A new update is available. Update? Yes <-> No

### ISSUE THREAD

**Issue by mimischi** [ShareX/ShareX#528]
I'm using the german language set and I didn't update for a while to the newer version, so I got the update notification for quite some time. I was wondering why it would download and try to install the update after clicking "Nein" (No). Just now I wanted to update and clicked "Ja" (Yes), but no update occured. After some time the update notification popped up and I clicked "Nein" again -> the update began.

It looks like that either the translation is messed up or the function of those buttons is wrong. I couldn't find the corresponding language file and therefore I'm not sure what's wrong.

**Comment by Jaex** [comment]
Translation have problem and it is already fixed in latest version.

**Comment by mimischi** [comment]
Ok thanks. Just got the idea, that the update just fixed it :+1:
