### ISSUE TITLE
“Capture region” magnifying glass is tiny as of the latest stable version.

### ISSUE THREAD

**Issue by obskyr** [ShareX/ShareX#5281]
For some reason, the magnifying glass in the “capture region” feature is positively tiny! It went from showing a good area of the screen, to showing but a pittance of pixels.

![Tiny magnifying glass in action.](https://user-images.githubusercontent.com/4363779/102702292-9e218a00-42a4-11eb-9054-52cbea11377f.png)

I'm on ShareX 13.3 on Windows 10 (64-bit; 19041.685).

**Comment by Jaex** [comment]
Use mouse wheel to change zoom of it.

**Comment by obskyr** [comment]
That was indeed it – I had no idea that was a feature! Thank you kindly.

**Comment by Shok12** [comment]
its a cool feature too.
