### ISSUE TITLE
error using ShareX recording

### ISSUE THREAD

**Issue by RalkeyOfficial** [ShareX/ShareX#5282]
![ShareX_Q2Cy4HdQx8](https://user-images.githubusercontent.com/30209145/102725635-84218f00-4318-11eb-833b-da6424d9acd8.png)

i get this error when trying to start a recording or recording(GIF)

**Comment by botatooo** [comment]
Do you use an antivirus? if so, is it avast?

**Comment by RalkeyOfficial** [comment]
> Do you use an antivirus? if so, is it avast?

that was a quick guess. yeah i use avast but that has never been a problem in the past
