### ISSUE TITLE
Ability to submit your own image effects.

### ISSUE THREAD

**Issue by Shok12** [ShareX/ShareX#5284]
What?

With this you could submit your own image effect where anyone (or just you) can use it. 

How?

Well, there could be a page for you to upload it and then moderators could review it (in the application) or you could make it in the website or the discord server.

Why?

Well, its because the current options are limited (but very good) and I think that if everyone had the chance to go this the app could get better.

If you find this cool please help me get @Jaex to notice this and make it happen!

**:)**

**Comment by Jaex** [comment]
How am I supposed to make it happen, I'm not web developer.

**Comment by Shok12** [comment]
@Jaex Make a discord channel for this or a tab in to application.

**Comment by Aholicknight** [comment]
Lmao
