### ISSUE TITLE
Custom Uploader Destination Suggestion

### ISSUE THREAD

**Issue by slowstab** [ShareX/ShareX#5286]
this isn't that important, but can you make it so custom uploaders are treated separately and aren't just combined into "Custom ... uploader"? so if i have 2 separate custom image uploader configs for 2 different sites and i wanna set it so that if the first custom image uploader fails i can use the second custom image uploader as a secondary image uploader through the upload retry section in application settings.
thanks! and i really love your app!

**Comment by Goku-04** [comment]
I really like this idea please add this feature Jaex 🥺
