### ISSUE TITLE
ShareX can only capture black images

### ISSUE THREAD

**Issue by c933103** [ShareX/ShareX#5290]
Not sure why but all of a sudden all the images captured by my ShareX was black, no matter I was in my browser (Chrome and Vivaldi and edge and such) or my desktop (Explorer). Thing was normal some days before and I didn't know what was changed and I didn't upgrade/downgrade my system/sharex app.
ShareX version 12.4.1
Windows 10 64 bit 1607

**Comment by aztazt** [comment]
Same issue here since I've updated my nVidia driver. I'll investigate more.

**Comment by aztazt** [comment]
Ok,
1. I uninstalled ShareX, then reinstalled ShareX -> problem persists
2. I removed nVidia Driver components one by one -> problem persists
3. I removed nVidia Driver and rebooted my computer -> ShareX can now capture images, problem solved.
4. I reinstalled last nVidia Driver (461.40) then rebooted -> ShareX still works ! Yay :)

**Comment by c933103** [comment]
I dod not have any nvidia hardware nor software but problem disappeared for now
