### ISSUE TITLE
Error When trying to do Video Capture & Screen Capture

### ISSUE THREAD

**Issue by Morpheus1101** [ShareX/ShareX#5295]
Each time i try and do a video capture of a screen it keeps throwing up this error screen every time despite having un-installed and re-installed ShareX and when doing a screen shot, it also throws an error but does the screenshot anyway.

https://puu.sh/H25m4/802fa2523f.png

**Comment by MrT3chGuy** [comment]
I have the same issue when taking a screenshot 😢

**Comment by Morpheus1101** [comment]
Mine has only occured after a re-install for screenshots and video used ot have an issue with ffmpeg .. but now its there well, yeah .. its annoying an google hasnt helped fixing the issue

**Comment by Morpheus1101** [comment]
Ok, so after more searching an looking through, ive at least stopped the screen capture bug by telling AVG to stop protecting the documents folder in the list of stuff protected by its RandsomWare Protection
