### ISSUE TITLE
Allow fast copy paste stickers

### ISSUE THREAD

**Issue by qwerthor** [ShareX/ShareX#5297]
![vZx1cgGLoq](https://user-images.githubusercontent.com/4999454/103373610-f90a7b00-4b07-11eb-9d59-789becd9bd58.png)

Hello, i love stickers, especially the gun stickers, it reminds me of counter strike.

i can't use copy paste, ctrl+c and ctrl+v on stickers. every time i press ctrl v, it creates image coordinate instead. 

Image coordinate is no fun, stickers is. 
please add this whenever you have time, thanks. 😄

**Comment by Jaex** [comment]
You can already do it, hold <kbd>Ctrl</kbd> then click spam.
