### ISSUE TITLE
Free hand drawing, line or Arrow thickness in editor ?

### ISSUE THREAD

**Issue by freMea** [ShareX/ShareX#5298]
Hi, 

I didn’t find the feature in v13..4. If it’s not implemented, it’s a feature request for all tools in the editor as well as change color.

**Comment by Jaex** [comment]
It is already exists.

**Comment by freMea** [comment]
> It is already exists.

Maybe you may tell me how to do. I didn’t find it.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2020/12/ShareX_DEdQC5ryEn.png)
