### ISSUE TITLE
Qr Decoder Enhancement

### ISSUE THREAD

**Issue by StoopidoMan** [ShareX/ShareX#5307]
I suggest to add Decoding from Camera/Webcam with a drop list to choose the camera with some basic setting to adjust brightness or manual/auto focus.
![image](https://user-images.githubusercontent.com/71223069/103528507-84379800-4e9d-11eb-9a7e-801f16107c81.png)

This will help users like me who have to Open vlc then decode from the screen when trying to read  a QR code on business card, or a cellphone, and I think doing that directly is easy to implement and is worth it, specially that there is no user friendly, open source, and portable QR code decoder for Windows. 

Additional unrelated feedback: the Encoder is awesome, and maybe this is an overkill and I think 99.9% of users wont use  this suggestion unless if ShareX became the de facto open source QR encoder and decoders for windows if so then having advance option like Error Correction leve, mask pattern etc.  would be great. 

Thank you for making my life easy <3

**Comment by easrng** [comment]
Open Windows Camera, slightly easier than vlc.

**Comment by Jaex** [comment]
> doing that directly is easy to implement

How it is easy to implement??

**Comment by StoopidoMan** [comment]
> 
> 
> > doing that directly is easy to implement
> 
> How it is easy to implement??

 well, I said I THINK! I am Sorry if it is not. I just assumed  that Windows API handle managing webcam/cameras, so an application would not need much coding to view the camera and for the code the user could press a button to take a screenshot of the video, that is a hacky simple approach in my mind, Notice my username.

Alternatively there is an opensource software called Zbar 
 http://zbar.sourceforge.net/
https://alternativeto.net/software/zbar-bar-code-reader/

Again @Jaex  there is no opensource application on windows that is a user-friendly, portable, and most importantly opensource barcode/QRcode reader and the closest I got was ShareX and it became my go to Qr Reader solution, and I thank you for that.

If it is hard to implement and maintenance this then of course focus on core function of ShareX

**Comment by StoopidoMan** [comment]
> 
> 
> Open Windows Camera, slightly easier than vlc.

Thanks, I didn't notice your reply, you are absolutely right!
