### ISSUE TITLE
Please add HEX at the Screen Color Picker

### ISSUE THREAD

**Issue by Anlini** [ShareX/ShareX#531]
I found possibility change SCP format to HEX but it only copies HEX to clipboard
![tia28ns](https://cloud.githubusercontent.com/assets/4973581/6441331/e0ec601a-c0f7-11e4-995f-1869cfe83494.png)
Also need to show HEX code beside a cursor where RGB right now
![2015_03_02 - 16_00_57](https://cloud.githubusercontent.com/assets/4973581/6441393/77f2a69a-c0f8-11e4-85f9-1e33be6bf54f.png)

**Comment by Jaex** [comment]
I don't see point of seeing hex there.

**Comment by Anlini** [comment]
It is very useful when there is a need to compare known hex color with existing, for example, after image compression some colors can be distorted. And I just hover SCP on it to check, without copying to clipboard.
Now I need to use PicPick for this purpose

**Comment by mnpenner** [comment]
Thank you! Was wondering where I could change this.

**Comment by Jaex** [comment]
You mean this?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/03/ShareX_O10XMUu0Ea.png)

**Comment by mnpenner** [comment]
Yes. It does support `$hex`. Which is perfect. I use that feature fairly regularly. Much easier than screenshotting and pasting into PhotoShop like I used to do.
