### ISSUE TITLE
Error everytime I try to take a screenshot

### ISSUE THREAD

**Issue by tajetaje** [ShareX/ShareX#5313]
Video/GIF recording works fine, but I cannot take screenshots anymore. Below is the error message:
![ShareX 1_7_2021 11_10_28 AM](https://user-images.githubusercontent.com/29828269/103915605-6bb3c180-50d9-11eb-8e44-0fd5e81a1d39.png)

I can send my settings export to a dev on request, but I won't post it here because it contains personal data.

EDIT: to clarify, I tried running shareX in administrator mode as well and that didn't change anything

Debug log:
> 2021-01-07 11:01:47.288 - ShareX starting.
> 2021-01-07 11:01:47.292 - Version: 13.4
> 2021-01-07 11:01:47.292 - Build: Release
> 2021-01-07 11:01:47.292 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
> 2021-01-07 11:01:47.292 - Personal path: C:\Users\Tag Howard\Documents\ShareX
> 2021-01-07 11:01:47.293 - Operating system: Windows 10 Home (64-bit)
> 2021-01-07 11:01:47.293 - Running as elevated process: True
> 2021-01-07 11:01:47.310 - ApplicationConfig load started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:01:47.765 - ApplicationConfig load finished: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:01:47.768 - UploadersConfig load started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:01:47.769 - MainForm init started.
> 2021-01-07 11:01:47.914 - UploadersConfig load finished: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:01:47.920 - HotkeysConfig load started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:01:48.048 - HotkeysConfig load finished: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:01:48.284 - MainForm init finished.
> 2021-01-07 11:01:48.659 - Startup time: 1401 ms
> 2021-01-07 11:01:48.778 - Hotkey registered: Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
> 2021-01-07 11:01:48.779 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture entire screen, Job: PrintScreen
> 2021-01-07 11:01:48.779 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
> 2021-01-07 11:01:48.779 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
> 2021-01-07 11:01:48.779 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
> 2021-01-07 11:01:48.780 - HotkeyManager started.
> 2021-01-07 11:01:48.781 - WatchFolderManager started.
> 2021-01-07 11:01:51.574 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:01:51.575 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:01:51.575 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:01:51.669 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:01:51.706 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:01:51.736 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:01:55.797 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
> 2021-01-07 11:01:55.798 - Executing: Capture region
> 2021-01-07 11:01:57.023 - Task in queue. Job: Job, Type: Image, Host: 
> 2021-01-07 11:01:57.032 - Task status: Preparing
> 2021-01-07 11:01:57.054 - Image copied to clipboard.
> 2021-01-07 11:01:57.080 - Exception:
> System.UnauthorizedAccessException: Access to the path 'C:\Users\Tag Howard\Pictures\Screenshots\2021-01\Zoom_ahsNDZ5mbC.png' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at ShareX.HelpersLib.StreamExtensions.WriteToFile(Stream stream, String filePath)
>    at ShareX.ImageData.Write(String filePath)
> 2021-01-07 11:01:58.786 - Image saved to file: C:\Users\Tag Howard\Pictures\Screenshots\2021-01\Zoom_ahsNDZ5mbC.png
> 2021-01-07 11:01:58.800 - Task completed. Filename: Zoom_ahsNDZ5mbC.png, Duration: 1766 ms
> 2021-01-07 11:09:18.542 - Executing: Capture region
> 2021-01-07 11:09:22.821 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:09:22.821 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:09:22.821 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:09:22.882 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:09:22.917 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:09:22.937 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:09:28.795 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:09:28.795 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:09:28.795 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:09:28.860 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:09:28.892 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:09:28.914 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:10:17.579 - Executing: Capture region
> 2021-01-07 11:10:19.539 - Task in queue. Job: Job, Type: Image, Host: 
> 2021-01-07 11:10:19.571 - Task status: Preparing
> 2021-01-07 11:10:19.685 - Image copied to clipboard.
> 2021-01-07 11:10:19.747 - Exception:
> System.UnauthorizedAccessException: Access to the path 'C:\Users\Tag Howard\Pictures\Screenshots\2021-01\msedge_BPB3mu2RKr.png' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at ShareX.HelpersLib.StreamExtensions.WriteToFile(Stream stream, String filePath)
>    at ShareX.ImageData.Write(String filePath)
> 2021-01-07 11:10:48.279 - Image saved to file: C:\Users\Tag Howard\Pictures\Screenshots\2021-01\msedge_BPB3mu2RKr.png
> 2021-01-07 11:10:48.330 - Task completed. Filename: msedge_BPB3mu2RKr.png, Duration: 28760 ms
> 2021-01-07 11:11:07.431 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:11:07.431 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:11:07.431 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:11:07.438 - Starting screen recording. Video encoder: "H.264 / x264", Audio encoder: "AAC", FPS: 30
> 2021-01-07 11:11:07.489 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:11:07.525 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:11:07.554 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:11:09.002 - CLI: "C:\Users\Tag Howard\Documents\ShareX\Tools\ffmpeg.exe" -rtbufsize 150M -f gdigrab -framerate 30 -offset_x 0 -offset_y 154 -video_size 3840x1946 -draw_mouse 1 -i desktop -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -y "C:\Users\Tag Howard\Pictures\Screenshots\2021-01\AMR6r6w40P.mp4"
> 2021-01-07 11:11:11.416 - Task in queue. Job: Job, Type: File, Host: 
> 2021-01-07 11:11:11.455 - Task status: Preparing
> 2021-01-07 11:11:11.462 - Task completed. Filename: AMR6r6w40P.mp4, Duration: 7 ms
> 2021-01-07 11:11:18.139 - Executing: Capture region
> 2021-01-07 11:11:22.739 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:11:22.739 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:11:22.739 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:11:22.747 - Starting screen recording. Video encoder: "GIF", Audio encoder: "AAC", FPS: 15
> 2021-01-07 11:11:22.800 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:11:22.836 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:11:22.857 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:11:24.347 - CLI: "C:\Users\Tag Howard\Documents\ShareX\Tools\ffmpeg.exe" -rtbufsize 150M -f gdigrab -framerate 15 -offset_x 0 -offset_y 154 -video_size 3840x1947 -draw_mouse 1 -i desktop -c:v libx264 -r 15 -preset ultrafast -tune zerolatency -qp 0 -y "C:\Users\Tag Howard\Pictures\Screenshots\2021-01\aNlFQYYWc4.mp4"
> 2021-01-07 11:11:26.671 - CLI: "C:\Users\Tag Howard\Documents\ShareX\Tools\ffmpeg.exe" -i "C:\Users\Tag Howard\Pictures\Screenshots\2021-01\aNlFQYYWc4.mp4" -lavfi "palettegen=stats_mode=full[palette],[0:v][palette]paletteuse=dither=sierra2_4a" -y "C:\Users\Tag Howard\Pictures\Screenshots\2021-01\7LKEZSmU2a.gif"
> 2021-01-07 11:11:28.167 - Task in queue. Job: Job, Type: File, Host: 
> 2021-01-07 11:11:28.174 - Task status: Preparing
> 2021-01-07 11:11:28.176 - Task completed. Filename: aNlFQYYWc4.mp4, Duration: 1 ms
> 2021-01-07 11:11:29.020 - URL opened: C:\Users\Tag Howard\Pictures\Screenshots\2021-01\aNlFQYYWc4.mp4
> 2021-01-07 11:12:19.506 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:12:19.506 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:12:19.506 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:12:19.564 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:12:19.601 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:12:19.604 - Task in queue. Job: Job, Type: Image, Host: 
> 2021-01-07 11:12:19.622 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:12:19.634 - Task status: Preparing
> 2021-01-07 11:12:19.755 - Image copied to clipboard.
> 2021-01-07 11:12:19.829 - Exception:
> System.UnauthorizedAccessException: Access to the path 'C:\Users\Tag Howard\Pictures\Screenshots\2021-01\Nw4WXGO6QS.png' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at ShareX.HelpersLib.StreamExtensions.WriteToFile(Stream stream, String filePath)
>    at ShareX.ImageData.Write(String filePath)
> 2021-01-07 11:12:21.331 - Image saved to file: C:\Users\Tag Howard\Pictures\Screenshots\2021-01\Nw4WXGO6QS.png
> 2021-01-07 11:12:21.390 - Task completed. Filename: Nw4WXGO6QS.png, Duration: 1756 ms
> 2021-01-07 11:12:55.659 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:12:55.659 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:12:55.659 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:12:55.719 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:12:55.754 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:12:55.775 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:13:19.686 - Export started: C:\Users\Tag Howard\Documents\ShareX-13.4.0-backup.sxb
> 2021-01-07 11:13:19.687 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:13:19.797 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:13:19.797 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:13:19.847 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:13:19.847 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:13:19.924 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:13:20.167 - Export completed: C:\Users\Tag Howard\Documents\ShareX-13.4.0-backup.sxb
> 2021-01-07 11:13:22.167 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:13:22.267 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:17:17.345 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:17:17.345 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:17:17.346 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:17:17.409 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:17:17.442 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:17:17.464 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:17:27.524 - ApplicationConfig save started: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json
> 2021-01-07 11:17:27.524 - UploadersConfig save started: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:17:27.524 - HotkeysConfig save started: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:17:27.584 - UploadersConfig save successful: C:\Users\Tag Howard\Documents\ShareX\UploadersConfig.json
> 2021-01-07 11:17:27.619 - HotkeysConfig save successful: C:\Users\Tag Howard\Documents\ShareX\HotkeysConfig.json
> 2021-01-07 11:17:27.640 - ApplicationConfig save successful: C:\Users\Tag Howard\Documents\ShareX\ApplicationConfig.json

**Comment by AevusErus** [comment]
I had a similar problem, and actually discovered that it was my antivirus that had blocked ShareX. I have Avast and was able to follow this video I found on the ShareX discord to resolve the issue: https://jaex.getsharex.com/2019/02/0tgX0icy2I.mp4

**Comment by tajetaje** [comment]
> I had a similar problem, and actually discovered that it was my antivirus that had blocked ShareX. I have Avast and was able to follow this video I found on the ShareX discord to resolve the issue: https://jaex.getsharex.com/2019/02/0tgX0icy2I.mp4

I also use avast, that seems to be the issue, odd that it didn't notify me. Maybe that's something @Jaex would have to contact them about. Regardless, I'll close this unless I run into more issues

**Comment by asheroto** [comment]
FYI, if you run ShareX as administrator, Windows permissions may not allow it to access user folders. It used to work, but now it doesn't. Windows beefed-up its security apparently.

The way I found around this is to disable ShareX from running on startup, create a schedule task and `Run whether user is logged in or not`. That way it'll run as your user, but you can run as Administrator for your user. I know, it's weird.
