### ISSUE TITLE
Possible to not save image to file if coming from a certain program?

### ISSUE THREAD

**Issue by WhenInWome** [ShareX/ShareX#5316]
I use ShareX for both work and personal, and it's kind of annoying that my work screenshots sync to my personal phone. I only ever take work screenshots in Firefox, so I'm wondering if there's a way I can not save the images coming from Firefox (so they're clipboard only), but do save the images coming from everything else. Thanks!

**Comment by yashpalgoyal1304** [comment]
I dont think there's an automated way yet. But just as a tip, you can use the quick task menu (in the after capture tasks) and do copy from there.
