### ISSUE TITLE
Search field - key listener

### ISSUE THREAD

**Issue by MilanRS** [ShareX/ShareX#532]
On history page can you add event listener on EnterKey for apply filters?
And on first letter inserted in Filename filter set checkbox checked?
http://i.imgur.com/bkTwydL.jpg

Often I write search term, press Enter and find out that I need to take mouse and klick on checkbox and Apply filters.

**Comment by Jaex** [comment]
I'm not planning to add auto applying when typing because when your history is too big it can delay typing.
