### ISSUE TITLE
Add option to stop screen recording automatically after certain time

### ISSUE THREAD

**Issue by adwaitpande11** [ShareX/ShareX#5322]
The screen recording feature should have an option to stop the recording automatically after few minutes. Say, I enrolled for a webinar but cannot attend; so I would just start the recording when the webinar starts and I mention beforehand to stop recording after 1 hr (coz I would know webinar won't extend further).

**Comment by mattvasc** [comment]
Meanwhile the ShareX does not have the option, you can use a python script to do the same:

`
import time
import sys
from datetime import timedelta, datetime

try:
	import keyboard
except ImportError:
	print("\n\nkeyboard library needed to run, please install with the command: pip install keyboard\n\n")
	sys.exit(1)

if len(sys.argv) != 2:
	print("\n\nWrong usage, correct syntax: python sharex_stop_screen_recorder.py <MINUTES>\n\n")
	sys.exit(1)
	
minutes = 0
try:
	minutes = int(sys.argv[1])
except:
	print("\n\nPlease input a valid number for <MINUTES> parameter\n\n")
	sys.exit(1)
print("\n\nEstimate time to stop: {}\n\n".format(datetime.now() + timedelta(minutes=minutes)))

while minutes > 0:
	print("Going to wait {} minutes before press shift + print_screen".format(minutes), end="\r")
	time.sleep(60)
	minutes = minutes - 1
	
print("\n\nSending keystroke!!")
keyboard.press_and_release("shift+print_screen")
print("\n\nDone. Credits: @mattvasc")

sys.exit(0)
`

**Comment by mattvasc** [comment]
While ShareX does not have an embed feature, you can use a simple python script to accomplish the same.

https://github.com/mattvasc/sharex_stop_recording/blob/main/ssr.py

**Comment by adwaitpande11** [comment]
> While ShareX does not have an embed feature, you can use a simple python script to accomplish the same.
> 
> https://github.com/mattvasc/sharex_stop_recording

@mattvasc This is awesome, working like a charm. Thank you very much.

**Comment by Jay-Tarzan** [comment]
warte - cancel

**Comment by adwaitpande11** [comment]
Override stale

**Comment by maciejkowalski** [comment]
Actually somebody came with good solution on reddit:

https://www.reddit.com/r/sharex/comments/nfxwmm/how_to_set_time_limit_for_screen_recording/
