### ISSUE TITLE
Save to PDF gives standard name file instead of randomized name

### ISSUE THREAD

**Issue by KipThorne** [ShareX/ShareX#5326]
Hi, I don't know if it's a normal behaviour but when ShareX saves a captured image to PDF (with "Print image"), file name is automatically sets to a standard name ("document.pdf") instead of the randomized name. So is it normal ? Is there any way to put the randomized name as the default PDF file name ? Thanks.

**Comment by sarjanwebdev** [comment]
It would be great if we can save screenshots as PDF without printing.
