### ISSUE TITLE
Custom Uploader fetch and parse url from upload response

### ISSUE THREAD

**Issue by 0-MegaMind-0** [ShareX/ShareX#5330]
I've a custom uploader which uploads the files and sends in a file_id response 
```json
{"status": "ok", "file_id": 1234}
```

but to get the actual url i need to fetch `example.com/getfile?file_id=1234`
which sends another response
```json
{"status": "ok", "file_path": "randompath/test.img"}
```
and the final url I need to is `example.com/getfile/file/randompath/test.img`

Right now the custom uploader i made can only get me this url `example.com/getfile?file_id=1234` is the a way to make it fetch the 2nd url and get the final file_path response ?

**Comment by Jaex** [comment]
Custom uploader system not supports multiple requests.
