### ISSUE TITLE
Pasting image data to sharex window should create file

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5332]
#### Steps to reproduce:

1. 1. copy some image > open sharex window > <kbd>Ctrl</kbd> + <kbd>V</kbd>
    2. right click on some image / ⋯ in snip and sketch > open with > sharex
    3. drag and drop some image onto sharex window
3. Sharex - Clipboard upload window is shown
4. clicking upload 

#### What happened:

1. dialog for disabled upload is shown: `This feature will not work when "DisableUpload" option is enabled!`
2. thereafter, the task completion notification (the bottom rt corner) is shown
3. thereafter the image file's task shows up in the recent files list 
4. the correct thumbnail is shown, but the image is not saved in sharex folder - 
    on clicking it, it either opens from the source location where it was brought from, 
    or in case 1.1 when the source doesnt exist as file already, it wont open and task entry is shown empty (as mentioned in https://github.com/ShareX/ShareX/issues/5064 and shown below) :

![image](https://user-images.githubusercontent.com/19423063/104853862-9c8dc500-5929-11eb-9503-15dbdc6e0730.png)

#### Already existing better case:

When in step 1, some text is copy-pasted into sharex, then, for what happened, at step-4. a new text file containing the pasted text content is saved in the folder where the sharex screenshots etc go.

#### Version: 
All i guess? If not, then Sharex 13.4 on windows 10 1903

**Comment by yashpalgoyal1304** [comment]
This is the same behaviour when some image is "Open with" Sharex for example from Snip and sketch, or also, drag and dropping on sharex main window - the only difference being that after step 4.3, on opening the file - it opens the source file.

**Comment by yashpalgoyal1304** [comment]
(i have decided to split the suggestion as a separate comment)

#### Summary:

1. Feature request: Create image file on pasting into sharex window, just like text file is created
2. The UX/workflow can be improved here

#### Details:

1. **Create image file on pasting into sharex window,** just like text file is created. 
Why? This would help me immensely - as sometimes i copy images from browser (copy image), sometimes from gimp (copy visible), sometimes i use windows snip and sketch via <kbd>Win</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>. 
So, pasting to sharex as permanent image file (as against temporary file in clipboard) and able to work from there, will help me a lot. 
I know there is already way of doing that in Sharex : Tools > Image Editor > Load image from clipboard - but that is cumbersome and will still require 2 yet more steps if i just want to save the image without any manipulation.

2. Also, the UX/workflow can be improved here.
**Some way to expose the local upload functionality can be used,** for example, in step 3 (upload window). It can be a separate button, a checkbox (illustrated below), or maybe given in preferences. 
It will give this feature more reach, and can eliminate dependence on the "disable upload" thing for this purpose. 
![image](https://user-images.githubusercontent.com/19423063/104855069-8b948200-5930-11eb-9520-f1f15bdcf128.png)
<br/>Wording can be: 
   - "upload to local folder" (best one in my opinion) , 
   - "paste to (local) sharex folder" , 
   - "paste locally" , 
   - "paste as file" 
   - (or some variation - u get the idea) 
   - {upload locally would still be ambiguous to me, so, not in favor of that}

**Comment by regs01** [comment]
Back in the days it was possible. But at some point Ctrl+V started working only for upload. But it would be very useful to have ability to capture from clipboard and past window needs an option to explicitly select image format. If it's not UI, then PNG would be very hefty.
