### ISSUE TITLE
Play sound when recording starts

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5333]
#### Summary

There should be an option to enable the capture/shutter sound. 
If the timer sound (say for integer times) can be added too, that would be a super cool bonus - but to me, it is not that important as shutter sound.

#### Scenarios:

ShareX provides 2 indications of start of recording - the timer widget at the bottom of recording area, and in taskbar. A lot of time - for example when in full screen, both of these things are hidden.

So, a shutter sound would come in really handy in those times.

**Comment by Jaex** [comment]
Problem is that shutter sound would play in recording too.

**Comment by yashpalgoyal1304** [comment]
maybe some milliseconds earlier?!
