### ISSUE TITLE
Tool rearrangement

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5337]
Currently, the tool order after the initial ones **seems** random to me. These should be arranged according to some particular thing - so that they can be together made more sense of.

in following proposal, I have arranged the tools roughly on the basis of their input and output data type. So:
Color label below | Domain | I/O | Tools like
-- | -- | -- | --
Orangish | Basics | info fetching | color, ruler
White | Screenshot manipulations (main) | Images | annotations, effects, combine, split, thumbnail
Green Yellow | Somewhat mechanical tasks | video, image, text, clipboard | converter, viewer, qr de/ncoder
Slate Blue | Additional tools | manly files, directories, and addresses | hash, indexer, dns
Rest | 'cz why not? | misc | monitor test, tweet

![image](https://user-images.githubusercontent.com/19423063/104885399-050e8d80-598e-11eb-8dc8-cf3f66a7eaa6.png)

**Comment by DylanMurphey** [comment]
Didn't know I wanted this! Good suggestion

**Comment by Jaex** [comment]
@yashpalgoyal1304

![](https://jaex.getsharex.com/2021/06/DiscordCanary_KPvR0ic0Ut.png)

What do you think?

**Comment by yashpalgoyal1304** [comment]
seems good @Jaex :+1: 

the moving of tweet message is nice catch too 👍

**Comment by yashpalgoyal1304** [comment]
seems good @Jaex :+1: 

the moving of tweet message is nice catch too 👍

**Comment by Jaex** [comment]
You can always test latest changes using dev builds like this: https://getsharex.com/docs/dev-builds

**Comment by yashpalgoyal1304** [comment]
also, any example/recording/description of what does directory indexer & dns changer does? i would have tried these myself, but since i dont know what to expect, am afraid of messing smth.

**Comment by yashpalgoyal1304** [comment]
what is this for?? https://github.com/Mattes0h/ShareX/commit/05c6d03f72ca56a03afa88ffb54f86c0e1337750 
:thinking :

**Comment by yashpalgoyal1304** [comment]
_sorry, i forgot to copy over the comment https://github.com/ShareX/ShareX/pull/5365#issuecomment-772453009 over here._

- video thumbnailer can be moved up so that it is just next to image thumbnailer. Views??
- also, now that i am on it, how 'bout moving "image combiner..." down?? the reason is not much strong. but
   - image splitting fits with the tools above it.
   - it looks nice too (in the name's length)   
     editor...
     effects...
     splitter...
     combiner...
     thumbnailer...
