### ISSUE TITLE
[Feature Request] 2FA Support for MEGA (Maybe Others?)

### ISSUE THREAD

**Issue by PXAbstraction** [ShareX/ShareX#5340]
Hey all. I just started using ShareX and absolutely love it. Thank you for your awesome work!

I just had one request. I am a MEGA user and tried to tie my account to ShareX but authentication always fails. I suspect this is because I have 2FA setup with MEGA and when trying to authenticate with ShareX, it never prompts me for the code so it just fails.

I'm not sure if MEGA makes available the ability to add their 2FA to third-party applications but I wanted to request this as MEGA seems to be unavailable in ShareX for users with 2FA enabled.

Thanks again!

**Comment by dreamlabnetwork** [comment]
I agree with this. Is it possible to add this feature? I would really prefer to have my 2fa enabled and not have to disable it just to use your software with it. I am pretty sure you would want your users to be safe and not have to turn this off. I am a little surprised this has not even gotten a reply from the team.

**Comment by Destroy666x** [comment]
Bump, this is still relevant and a serious issue for the service, not sure why it was closed so quickly @Jaex

**Comment by GalaxySH** [comment]
Still relevant, mega is a useful tool and better when secured with 2fa.

**Comment by Blushock** [comment]
still relevant

**Comment by ARHAEEM** [comment]
ShareX founder hate mega 📣
![FB_IMG_1712965259416.jpg](https://github.com/ShareX/ShareX/assets/63544079/40e34e60-7178-40a1-9918-f7277ac201da)
