### ISSUE TITLE
Capture cursor not rendering on screen but is in screenshots

### ISSUE THREAD

**Issue by nagelxz** [ShareX/ShareX#5344]
I'm not sure when it started, but the region capture cursor is rendering weird on the screen.
![IMG_20210121_173659](https://user-images.githubusercontent.com/4513621/105421215-c0922480-5c0f-11eb-9d08-a435d2b279ac.jpg)

But it's rendering fine in a screenshot after starting a region capture

![ShareX_2021-01-21_17-36-12](https://user-images.githubusercontent.com/4513621/105421464-241c5200-5c10-11eb-8fc5-f592a69c3a7d.png)

I'm on a relatively fresh install of windows.

There's no errors in the Event Viewer, and nothing in the Sharex debug log

2021-01-21 17:46:32.697 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2021-01-21 17:46:32.697 - Executing: Capture region

**Comment by Vamennnn** [comment]
The same issue is happening with me too, and I noticed it breaks when ever the size of the windows mouse pointer is greater than 1
