### ISSUE TITLE
[Feature request] Record specific virtual desktop on windows 10

### ISSUE THREAD

**Issue by zfxstd** [ShareX/ShareX#5346]
Is there any way to implement thing like recording specific virtual desktop? 
Like just create another desktop, open some programs, select, start record and switch then back on main desktop and let it work in "background" until i switch back and stop it.

**Comment by TDLab2015** [comment]
why not record in that virtual environment... installing a share x on that VM...

**Comment by zfxstd** [comment]
its practical idea but its very overweight and uncomfortable solution. like if you need go away 100m and u using your car for that. And if someone has like laptop or old pc - its sometimes not even possible.
