### ISSUE TITLE
[Feature Request] Custom Upload Sound

### ISSUE THREAD

**Issue by MaxTCodes** [ShareX/ShareX#5348]
Hi all,

I am working on an image hosting service, and I thought it would be really cool if either the user or the service can provide a custom mp3 file (limited to like 1-2 seconds) that plays when there is a successful upload! It would add the ability for services to be unique and add more customization to their services!

Thanks,
Max T

**Comment by Vladimir-0001** [comment]
yes

**Comment by CallumlousTV** [comment]
100% would want.

**Comment by DogeSkiii** [comment]
give or bad

**Comment by MaxThakurCodes** [comment]
Hi, @ShareX. I'm just checking up on this. Is this feature going to be implemented? Is this even possible?

**Comment by Jay-Tarzan** [comment]
I'am on leave

**Comment by DogeSkii** [comment]
bump
