### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by BirchTreeCoconut** [ShareX/ShareX#5350]
Since there is only one "TextColor" option, it only works on active panels, but the text in inactive panels may become unreadable and barely visible, especially with low screen brightness. I think there should be 2 scripts for active and inactive texts.
![ShareX_t2Vhv95b09](https://user-images.githubusercontent.com/77694896/105606293-1828bf80-5dcb-11eb-9c33-7b96dd80a453.png)
![ShareX_js1peUsgLj](https://user-images.githubusercontent.com/77694896/105606295-1959ec80-5dcb-11eb-90e0-33722e61b62b.png)

**Comment by Scrxtchy** [comment]
#4813
