### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by TheChilliPL** [ShareX/ShareX#5357]
Hello, at the moment I have ShareX in version 13.3 and every time I start my PC, it prompts me to update to 13.4. If I click I do want to, it doesn't install it anyway. Like, it does something for sure, but it keeps asking to update every time. I have no idea if it's a bug in code (maybe cause my installation directory is `P:\ShareX`?) or something doesn't work only for me, so I wanted to ask how can I force it to update? I thought to uninstall it and install it again but I have no idea if it will preserve my configuration

**Comment by samwez** [comment]
I have exactly the same issue its been going on for a while

**Comment by TheChilliPL** [comment]
![image](https://user-images.githubusercontent.com/18823939/107117223-1f46d780-6879-11eb-956a-0d9f44206999.png)
I noticed the newest version gets installed for all users for some reason. The older version keeps getting launched though.

Also, I originally installed ShareX in path `P:\ShareX` but now I can also see it installed in `C:\Program Files\ShareX`

**Comment by TheChilliPL** [comment]
I made a backup of my screenshots and config folder (`Documents\ShareX`) but it seems like uninstallation doesn't remove any of it and after installing ShareX 13.4.0 manually, it already has the old config in it. I'll let you all know if I have this issue again, but I'm not closing it as it should update itself properly
