### ISSUE TITLE
ShareX isn't working with multi monitors 

### ISSUE THREAD

**Issue by loststone2** [ShareX/ShareX#5358]
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[gdigrab @ 0000013d7f47ebc0] Capture area (1920,0),(3840,1080) extends outside window area (-1920,0),(3456,1080)desktop: I/O error

**Comment by co6aka333** [comment]
I've got similar issue. I have two fullHD monitors. In my case error appears only if I try capture video/gif in 640x1920 area in left part of the left monitor. Screenshots working well.
[gdigrab @ 000001b225bfed40] Capture area (-1920,0),(1920,1080) extends outside window area (-1280,0),(1920,1080)desktop: I/O error

**Comment by PerryCodes** [comment]
Same issue. Doesn't account for different settings on multiple monitors.  Also doesn't handle fonts correctly when the scaling is fairly high - I've got a 4K 15" laptop that requires between 200% and 250% display scaling.

**Comment by apsis0215** [comment]
Same issue- Dell Dock 4K go to capture region and it insists on the top-left monitor. Let me know if there are logs I can send for support : )
