### ISSUE TITLE
Making a Distorted Screenshot in VLC Player Under Win7 

### ISSUE THREAD

**Issue by Maik3l22** [ShareX/ShareX#5363]
Making a Distorted Screenshot in VLC Player Under Win7 

Windows 7
Share X 13.4

With the new version (13.4) of ShareX I can't make a screenshot of a video, which is proper, if VLC player is at fullscreen. It's distorted everytime under Win 7. I tried it in Win 10 on my laptop and there it functions perfectly. (I use Win7 on my Home-PC because it is better to work with.)

![vlc_pGsGZwuAwh](https://user-images.githubusercontent.com/78445044/106656288-c9cdaa80-659a-11eb-8d64-b12579e1581a.jpg)
![vlc_5uJIeaIEZ9](https://user-images.githubusercontent.com/78445044/106656428-f84b8580-659a-11eb-9a90-751f8b58cd4e.jpg)
![vlc_Cy2fIhBPmL](https://user-images.githubusercontent.com/78445044/106656474-06010b00-659b-11eb-82b8-47e7c5706af0.jpg)
![vlc_BkZvmTJLW0](https://user-images.githubusercontent.com/78445044/106656483-09949200-659b-11eb-8894-d4dc7e5538d2.jpg)
![gtOO3dsA73](https://user-images.githubusercontent.com/78445044/106656526-174a1780-659b-11eb-94a6-0fc14f244933.jpg)

**Comment by Jaex** [comment]
Try taking screenshot using Windows built in printscreen.

**Comment by Maik3l22** [comment]
I tried it and it's the same failure. So it must be a Windows failure.
I wonder therefore, why it doesn't function anymore.
Two months ago I mirrored my SSD. Maybe from there comes the failure. Do you know what can cause it?

![aaaaUntitled](https://user-images.githubusercontent.com/78445044/106694651-42535c00-65d9-11eb-8293-191bd84c1124.jpg)

**Comment by Maik3l22** [comment]
Ok. 
I found out that the failure was in the configuration of VLC player. I made a reset and it's okay now.

Thx for the help.
