### ISSUE TITLE
Week numbers shifted in 2021

### ISSUE THREAD

**Issue by knlknl** [ShareX/ShareX#5367]
Hi and thanks all developpers for that great application !

I use to store my capture by weeks numbers.
Two things:
- 1 issue : weeks numbers are shifted in 2021 (at leat for France) (was OK in 2020) please see my screen capture with outlook calendar for reference
- 1 improvement request : possibility to write that week number also with two digits (e.g: 05 instead of 5) for weeks before week 10

Thanks again for the development
Regards
![ShareX - week nb issue](https://user-images.githubusercontent.com/78535271/106874931-6c3e7880-66d6-11eb-8638-2d597ac2a99e.png)

**Comment by yashpalgoyal1304** [comment]
niiice suggestion. i'd suggest that keep this issue to only the bug, and separate the suggestion to a new issue. If u will be do so, i will have something to add to that suggestion too (:

**Comment by yashpalgoyal1304** [comment]
@knlknl
