### ISSUE TITLE
 Unable to record audio

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5369]
### Update:
Resolved , go to https://github.com/ShareX/ShareX/issues/5369#issuecomment-774474844 for diagnosis, and https://github.com/ShareX/ShareX/issues/5369#issuecomment-774475518 for verification

### Summary:
Sharex is not recording the audio

### Reproduction:
**Steps:**
1. open sharex
2. start screen recording
3. play some music
4. stop recording, and play the resultant file

**What happened:** Recording starts, but the resultant file doesnt contain any sound

**Frequency:** Mostly, very likely

### Settings: 
- Screen Recording FPS: 15
- Audio src: virtual audio capturer, and tried with microphone array too
- Audio codec: AAC 96k
- Video src: GDI grab
- Video codec: tried with mutliple

### Versions:
- Sharex version: 13.4.0\
.exe from https://github.com/ShareX/ShareX/releases/tag/v13.4.0
- Recorder Devices: default (0.12.10)\
but [latest version🡭](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases) is 0.12.11
- ffmpeg: default (version unknown)
- OS: Windows 10 1903

### Hardware:
- intel i5 and intel UHD 630
- Nvidia 1050Ti

**Comment by ilko-k** [comment]
@yashpalgoyal1304 note that JRE is required in order to make the virtual audio source to work (and seems not to be needed in Windows 10). If you still have troubles recording sound, try enabling the "Stereo Mix" input device and select it as the audio source. The whole sound is redirected to this virtual device and is equivalent to the "what you hear" thing but is natively built in Windows.
![image](https://user-images.githubusercontent.com/5411848/107106390-44d3d280-67e0-11eb-93b7-b72997ed95f7.png)
![image](https://user-images.githubusercontent.com/5411848/107106412-69c84580-67e0-11eb-9c12-513454686135.png)

**Comment by yashpalgoyal1304** [comment]
hello @ilko-k i just tried with that too. and it didnt work too :(

**Comment by Neurotoxin001** [comment]
Same.

**Comment by yashpalgoyal1304** [comment]
oops, duplicate of #4959 \
will be migrating my input there

**Comment by yashpalgoyal1304** [comment]
**Update:** \
The issue for me was due to "hotkey settings" which is not just a simple hotkey, but whole workflow settings 🤕🤦‍♀️

So, 
- the settings i was choosing in "general task settings > screen recorder" were not getting applied to the "task settings for the hotkey workflow" which i had set earlier for capturing full screen
- ... since it had "override capture settings" enabled
- ... which was required to be able to set the predefined region (full screen) 
- ... and the problem here was that it also made it to override the screen recorder settings \
which contained the earlier audio source settings etc (i.e. audio source = none).
- ... which was the reason for sound not getting recorded in my case

![ShareX_gJXEPHfh2K](https://user-images.githubusercontent.com/19423063/107118650-33ee9400-68a8-11eb-8a3c-c2aca7004d25.png)

**Comment by yashpalgoyal1304** [comment]
To verify if ur issue is due to the same cause: 
1. choose the relevant audio source \
in task settings > screen recorder > screen recording options > audio source = **virtual audio capturer** for example
2. **MAIN STEP:** now try capturing NOT via hotkeys, but **via the UI** buttons i.e. **Capture** > **Screen Recording** and choosing a random region
![image](https://user-images.githubusercontent.com/19423063/107118009-2fc07780-68a4-11eb-93c5-c580540de17a.png)
3. play some audio (song etc) and stop the recording 5-10 seconds thereafter
4. watch the resulting file

the microphone on/off doesnt affect when audio_src = virtual audio capturer - which is as expected/intended (:
![dvWRrjXvFK](https://user-images.githubusercontent.com/19423063/107118346-8464f200-68a6-11eb-8fa9-88bd6e26f796.gif)
