### ISSUE TITLE
Do not force user to accept GPL but just show it

### ISSUE THREAD

**Issue by Vampire** [ShareX/ShareX#5377]
I as end-user am not affected by the GPL.
It only applies to modifying and distributing.
I should not be forced to formally accept it.
Instead it should just be shown with a "Next" button
in the installer instead of being forced to accept it.

**Comment by Vampire** [comment]
still the same with 13.5

**Comment by Vampire** [comment]
Still the same with 13.7, please reopen

**Comment by BrycensRanch** [comment]
As an end user, you are involved with GPL v3. It defines what you can do with ShareX. Accepting a software license/ToS is standard with installers on Windows.

**Comment by Vampire** [comment]
@BrycensRanch nothing in the GPLv3 is involved with **using** licensed software.
It only comes into play when **modifying** the code and distributing it.

The typical way is to show an installer page that shows the GPLv3 with a "Next" button instead of requiring the user to accept something that does not apply to him at all when just using the software.

Let me quote the [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.html#ClickThrough):
> Can software installers ask people to click to agree to the GPL? If I get some software under the GPL, do I have to agree to anything?
>> Some software packaging systems have a place which requires you to click through or otherwise indicate assent to the terms of the GPL. This is neither required nor forbidden. With or without a click through, the GPL's rules remain the same.
>>

>> Merely agreeing to the GPL doesn't place any obligations on you. You are not required to agree to anything to merely use software which is licensed under the GPL. You only have obligations if you modify or distribute the software. If it really bothers you to click through the GPL, nothing stops you from hacking the GPLed software to bypass this.

**Comment by BrycensRanch** [comment]
My apologies I was wrong. I’ll send in a PR shortly to attempt to rectify the issue. Just keep in mind it’s up to JaeX whether or not they accept it. Cheers 🎉
