### ISSUE TITLE
Why are all my Sharex screen recordings jerky?

### ISSUE THREAD

**Issue by OOP-EFSC** [ShareX/ShareX#5384]
Why are all my Sharex screen recordings jerky? I have it set to 60 FPS and the max bitrate. What else do I need to do?

**Comment by Jon-chalk** [comment]
Possible reason could be the framerate you selected. Try 30 fps in the :task settings, "screen recorder". Make sure the "screen recording FPS is set for 30 in the box. I tried 29 FPS and it was jerky/choppy.

**Comment by OOP-EFSC** [comment]
It was even more jerky when I had it at 30 fps. That was why I raised it to 60 fps. I will try 30 again next time I restart. It seems to work better after a restart.

**Comment by vertigo220** [comment]
Your hardware might not be able to keep up. For example, I'm able to do a smooth recording of desktop use, but when I tried recording a game it was pretty bad. Try using a faster codec (e.g. 264 vs 265, QuickSync or NEVC if available) and preset. Also, if you're recording to the same drive that you're playing whatever you're recording from, especially if it's a hard drive and not an SSD, that might be affecting it.
