### ISSUE TITLE
Images are PNG in clipboard but save in JPEG

### ISSUE THREAD

**Issue by softyoda** [ShareX/ShareX#5398]
Since last update, i lose all my settings, i had to rebuild them from scratch.

I'm trying to have full jpg workflow as i often upload screenshoot to other service and don't want to wait 2mb when i can have 200ko.

I have set the capture to jpeg but my clipboard remain png with heavy images.

Windows 10 pro Sharex 13.4

**Comment by Jaex** [comment]
Your clipboard not contains PNG. Where you are pasting image converts image data to PNG.

**Comment by softyoda** [comment]
Why discord convert data to png when i do CTRL+V with the new version, but not the old version of shareX, and why discord don't convert jpg to png when i drag and drop the jpg from the screenshoot folder ?

**Comment by softyoda** [comment]
![image](https://user-images.githubusercontent.com/13988751/108074396-6f881b80-7069-11eb-9654-d01718c69ae9.png)
this is an image pasted from the clipboard

![444_%pn_%t_16_02_2021_15h12(1327x1084)_PK4m](https://user-images.githubusercontent.com/13988751/108074461-829aeb80-7069-11eb-9e26-28ce2afd8252.jpg)
this is an image drag and dropped to the text area of github


Firefof last stable version, on windows 10.

**Comment by B-iggy** [comment]
Any update on this?

**Comment by B-iggy** [comment]
As you can see the original image is jpg:
But as soon as I click the "store to clipboard" icon, it gets converted to .png.

Is this a ShareX or Windows 11 setting?
![image](https://user-images.githubusercontent.com/7815434/205489983-f1c0c872-e707-44e1-9566-ebd1d7bc0af9.png)
