### ISSUE TITLE
Optimize Image after capture!

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#540]
ShareX is by far my favorite and most used program over the past 5 years.  It is truly amazing and the features make it seem as if I had hired you to build it exactly to my specs....it's just that perfect for my usage!

It has really evolved as well and the features have gotten better and better and even more useful than ever.  THANK YOU!

Now with that said, there is literally only 1 more feature that I can currently think of that I wish it had and would even pay to have it added!

Right now, I have my screenshots uploaded to my FTP server which is the best feature of all for my usage.  The one thing missing though is the ability to set the image to be ran through an image optimizer program after capture.

The programs I often use and countless other programs and app use these command line programs to optimize images:

AdvPNG - http://advancemame.sourceforge.net/comp-readme.html
optiPNG - http://optipng.sourceforge.net/
PNGCrush - http://pmt.sourceforge.net/pngcrush/
PNGquant - http://pngquant.org/
GIFsicle - http://www.lcdf.org/gifsicle/
JPEGTran - http://jpegclub.org/jpegtran/
JPEGOptim - https://github.com/glennr/jpegoptim
jpegrescan

Trimage is an example of one of many programs and apps that combine and use all these amazing command line image optimizer tools. 
Trimage image compressor – A cross-platform tool for losslessly optimizing PNG and JPG files.
http://trimage.org/ https://github.com/Kilian/Trimage

So my huge request would be to in some manner, add a new option to the `After Capture Tasks` menu which would allow to `Optimize Image Files`  and it would run the file through the image optimizer programs before uploading the optimized image!

This would be such an amazing new feature and I believe that with what is available that it is totally possible to integrate such a feature!

Please consider it!

If such a feature was added into ShareX, then I think it should also have some settings such as:

- Pick which file types are optimized and which ones are not.  Perhaps you only want JPG images optimize and not GIF images.  
- Set the quality of compression for JPG images... example 80%  
- Option to keep un-optimized image locally as well as optimized.  Perhaps there could be another folder to save the optimized images.

**Comment by Jaex** [comment]
This is why I added "Perform actions" to After capture tasks. With it you can use any image compression app.

**Comment by peckwood** [comment]
This is how I do it with pngcrush:

![ShareX_F62adgQw3W _compressed _compressed _compressed](https://user-images.githubusercontent.com/1825108/106841176-95fa9e00-66dc-11eb-902a-6cfd8302a90f.png)
