### ISSUE TITLE
Bug: The cloud file provider is not running

### ISSUE THREAD

**Issue by Wolf1910** [ShareX/ShareX#5401]
I got this message whenever I try to run ShareX, this issue persists even when I reinstall it, any idea how to fix it? 
[Log.txt](https://github.com/ShareX/ShareX/files/5992705/Log.txt)

**Comment by dennisvtang** [comment]
I had a similar issue. Mine had to do with my ffmpeg.exe file being located in my OneDrive. I think it was because I didn't have OneDrive running, but I solved it by redirecting what ffmpeg.exe ShareX was using.
