### ISSUE TITLE
Copy to Clipboard closes the ShareX window

### ISSUE THREAD

**Issue by justinjalandoniiwest** [ShareX/ShareX#5405]
When I try to copy to clipboard the ShareX window closes as seen in the GIF:

![bFuOUN30oi](https://user-images.githubusercontent.com/75491773/108345952-cfbdbf80-7219-11eb-96b1-d50e1b5ab8a6.gif)

**Comment by Jaex** [comment]
Uncheck this option:

![](https://jaex.getsharex.com/2021/02/explorer_aaZuKNzNgs.png)

**Comment by justinjalandoniiwest** [comment]
This resolved the issue

**Comment by justinjalandoniiwest** [comment]
> 
> 
> Uncheck this option:
> 
> ![](https://camo.githubusercontent.com/7c0712e17a0232f770f12f255b55ec3ce12775ef0c8c441809358f6a6d6c6338/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f30322f6578706c6f7265725f61615a754b4e7a4e67732e706e67)

Thanks. Issue has been resolved.
