### ISSUE TITLE
Video recording to clipboard

### ISSUE THREAD

**Issue by decio-db1** [ShareX/ShareX#5407]
Hello,

I use ShareX to record a lot of videos and I'm wondering if the copy to clipboard doesn't work with videos.
With images is fine, but after recording a video I can not paste it anywhere, I need to open sharex and drag-drop the video where I want.

I tried with a few different settings but no success so far:
![image](https://user-images.githubusercontent.com/62886374/108379132-65d6f300-71e4-11eb-8e70-fb0a30431692.png)

Copy file to clipboard doesn't seem to change anything for me.

Maybe is something to do with the video format?
![image](https://user-images.githubusercontent.com/62886374/108380028-3c6a9700-71e5-11eb-871d-3e8f61b9d2d9.png)

I tried a bunch of settings but nothing worked so far :(

**Comment by Jaex** [comment]
I only selected "Copy file to clipboard" and I could paste video to desktop.

**Comment by decio-db1** [comment]
Tried with only "Copy file to clipboard" but still didn't work.
Is there a way for me to debug or see the logs if is indeed copying to clipboard after the task is done?

**Comment by decio-db1** [comment]
Actually I noticed that even images are not working.
I made a quick video, testing the windows snipping tool and sharex and showing the logs, the windows copied the image to the clipboard correctly, but the sharex even though it shows on the logs that it was copied, still has nothing on the clipboard.

https://user-images.githubusercontent.com/62886374/108386139-22cc4e00-71eb-11eb-8da8-20a0ba3fe70c.mp4

I also check the AutoClearClipboard setting, but is the to false:
![image](https://user-images.githubusercontent.com/62886374/108386276-41cae000-71eb-11eb-94c8-cec8e9475c63.png)

Any idea what could be the problem?

**Comment by ItsCubeTime** [comment]
Same issue here, Windows 10  [Version 10.0.19042.867]

Although unlike op this only occurs with video recordings for me, regular images and gifs are fine.

**Comment by ItsCubeTime** [comment]
Actually it seems the issue is that services like Github, Discord and various forums dont support pasting the file into the text box like you can with screenshots (pasting the file into my desktop works just fine).

Perhaps we could see some after capture feature "Copy video to clipboard", just like copy image to clipboard but for videos?

**Comment by decio-db1** [comment]
After more than a year dealing with this issue I think I have found a solution.

By disabling the option "Save image to file", the screenshots and videos I recorded started appearing in the clipboard.

![image](https://user-images.githubusercontent.com/62886374/133858728-259365ad-ff92-4c53-b9c2-4e7f6d2dfff6.png)

I'm not sure if this is a bug or if it's intended, but it's clear for me that with the option enabled, screenshots and videos do not appear on the clipboard.

**Comment by khag7** [comment]
Why was this closed? Is this not a bug? When I create a screen recording it does not get saved to my clipboard, only to a file. How can I make it save to my clipboard as well?

**Comment by Jaex** [comment]
It is not a bug. It copies fine. Just not all apps supports pasting it.

**Comment by khag7** [comment]
> It is not a bug. It copies fine. Just not all apps supports pasting it.

Oh, I apologize then. That's excellent news. It's not working for me in *any* app. Also its not showing on my Windows Clipboard viewer (press windows key plus V to see whats on your clipboard)

So it sounds like my settings are not configured correctly then. Screenshots go right to my clipboard no problem Screen recordings do not. And I can't seem to find any setting to make screen recordings do the same as screenshots.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2022/01/3jwx7tvpEU.png)

**Comment by khag7** [comment]
Oh, Yeah I saw that. I thought there was a distinct difference between "Copy image to clipboard" and "Copy file to clipboard". I guess I was suggesting that I thought it was a bug that "copy image to clipboard" doesn't work for gif images (screen recordings). Regardless, it sounds like that's not an intended feature and things are working as they're supposed to. In that case, consider this a feature request. It would be great if the gif image itself was copied to the clipboard rather than the file.

It's interesting... when I go into image history I can right click on a gif and choose "copy image" instead of "copy file" and that works just fine.

**Comment by ItsCubeTime** [comment]
> By disabling the option "Save image to file", the screenshots and videos I recorded started appearing in the clipboard.
>  ![image](https://user-images.githubusercontent.com/20190653/151690601-431c64c2-aeb9-42ee-99c6-75f53fba44e0.png)

The settings youre showing here just copies the file to the clipboard. Not a video.

Like @khag7 is saying. Social media platforms usually doesnt support pasting in files (which does not typically work for images either, ironically dragging and dropping files works fine. I wish I knew what the  technical difference was here however :l ).

**Comment by RedSnt** [comment]
I guess using the "Show file in explorer" option will have to suffice for drag and dropping. Disappointed that "Copy file to clipboard" doesn't seem to work with anything but captured images.

**Comment by Jaex** [comment]
> I guess using the "Show file in explorer" option will have to suffice for drag and dropping. Disappointed that "Copy file to clipboard" doesn't seem to work with anything but captured images.

It works when this option is enabled:

![](https://jaex.getsharex.com/2022/07/ShareX_JdjSxThmxK.png)

I literally tested it just now. Most likely what you are trying to paste it not supports it, such as Discord. So it is not ShareX fault.

**Comment by RedSnt** [comment]
> I literally tested it just now. Most likely what you are trying to paste it not supports it, such as Discord. So it is not ShareX fault.

You're right, I was wanting for this to work in Discord, but even with the debug console open I can't see it mentioning copying the result, and using windows clipboard (Win+V) I can't see anything there either.   
Also, I already had that UseAfterCaptureTasksDuringFileUpload option set to true.  
BUT, I do recognize that the last copied entry to the clipboard doesn't show up, so something must be in there. Either way, a simple drag and drop for my use is more than enough.
