### ISSUE TITLE
Video Screen Capture Size Limitation

### ISSUE THREAD

**Issue by WillCoffin** [ShareX/ShareX#541]
Attempting to start a video screen capture of my monitor throws this error in FFmpeg:

[gdigrab @ 000000000447aea0] Capture area (0,0),(3840,2160) extends outside window area (0,0),(4000,1440)desktop: Input/output error

Any way to increase the vertical resolution max?

**Comment by Jaex** [comment]
Are you using different DPI?

**Comment by Jaex** [comment]
#923

**Comment by rishabhsati94** [comment]
video size is 5 hours and Video is not playing after being recorded
