### ISSUE TITLE
Creating a Hotkey to capture the monitor defined by size

### ISSUE THREAD

**Issue by Photosbykev** [ShareX/ShareX#5411]
Good morning, loving the software now I've found a decent a screen capture programme :)

My system runs on 3 monitors, the main is a 4k one and two smaller 1080p monitors. I see I can use the software to capture the monitor of size X even if it isn't in 'focus' (in my case it would always be the 4k monitor).

I'm trying to create a hotkey to always capture this larger monitor screen but the option doesn't appear to be available under the task dropdown list?

Is there a way to force the software to always capture the larger monitor via a hotkey rather than having to open up the ShareX program and do it through the menus?

best regards
Kev

**Comment by Jaex** [comment]
Yes:

![](https://jaex.getsharex.com/2021/02/ShareX_dYA9YcbbQA.png)

![](https://jaex.getsharex.com/2021/02/ShareX_COP3FIoZNa.png)

**Comment by Photosbykev** [comment]
thank you, I didn't think of using the region settings.
