### ISSUE TITLE
Feature Request: pin screenshot on top

### ISSUE THREAD

**Issue by StevenLi-DS** [ShareX/ShareX#5416]
I just converted to ShareX and really love it.

I need to make a screenshot and then pin it on the top to move around sometimes. It looks like this:
![JaZZIQDRj1](https://user-images.githubusercontent.com/33796896/108601903-1ff96680-736d-11eb-9b52-647cf7ab7dea.gif)

This is really useful if you need to compare something when the content cannot fit on your screen.
I hope ShareX team could please consider adding this feature in future development.

Thanks

**Comment by StevenLi-DS** [comment]
Hi @Jaex. I didn't find an existing issue about this FR before opening it. Could you please refer the issue or maybe this feature is not under considering at all?

**Comment by zhupengfeivip** [comment]
This is a great feature. When will it be available?

**Comment by Jaex** [comment]
Duplicate of #2363
