### ISSUE TITLE
How to have the running ants cover the whole window easily in some applications ?

### ISSUE THREAD

**Issue by rekotomo** [ShareX/ShareX#5428]
My ShareX version is 12.2

For window screen capture, I do by right click ShareX icon in the taskbar :
Capture ---> Window ---> then choose what window I want to capture.

For window screen recording, I understand that I can just draw a rectangle to cover the opened window. 

But to have the running ants cover the whole window, for some reason, it seems some applications can be easily to make the running ants cover the whole window, for example: Notepad and MPC-HC.....

![2021-02-25_12-17-57](https://user-images.githubusercontent.com/79619035/109102465-ead18780-7763-11eb-8f1a-aa744d98e6d0.png)

Above example, I can just hover the cursor around the "X" area in the window title of MPC-HC,
then the running ants cover the whole MPC-HC window.

but with some application, it's soooo hard to have the running ants to cover the whole window. For example Microsoft Excel 

![2021-02-25_12-13-18](https://user-images.githubusercontent.com/79619035/109102300-83b3d300-7763-11eb-9823-960df3760c50.png)

To have the running ants cover the whole Excel window, it takes a lot of time for me because I need to hover the cursor precisely at the edge of the window.

I wonder if there is a way to have the running ants cover the whole window easily for that some apps (Excel in this example) besides draw a rectangle covering the whole window.

Any kind of help would be greatly appreciated.
Thank you in advanced.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2021/02/ShareX_9i3S0DVbsF.png)

Uncheck this option.

**Comment by rekotomo** [comment]
> 
> Uncheck this option.

Hi Jaex,
Thank you very much for your help.
I did as you suggest ---> uncheck the "also detect control regions".
It worked for screen capture but unfortunately it didn't work for screen recording.

Below, screen capture (region). Mouse hover around "X" area in the title bar. 
The running ants automatically cover the whole window.
![2021-02-25_13-55-47](https://user-images.githubusercontent.com/79619035/109110012-48b89c00-7771-11eb-86db-3ff18d113abf.png)

Below, screen recording. Mouse hover around "X" area in the title bar. 
The running ants automatically cover only the Excel menu area bar.
![2021-02-25_13-56-05](https://user-images.githubusercontent.com/79619035/109110175-90d7be80-7771-11eb-827c-d6b7f7602813.png)

**Comment by rekotomo** [comment]
Hi Jaex,

I finally figure out on how to screen recording the whole window easily.
I set a hot key, then select the option : "Start/Stop screen recording using active window region".

Thank you once again, and thank you so much for all the developers of this great application.

This post can be closed by Admin.
Thank you.
