### ISSUE TITLE
Update message minimizes fullscreen applications - including games

### ISSUE THREAD

**Issue by rahlzel** [ShareX/ShareX#543]
This is pretty dangerous. I was playing Assassin's Creed Rogue and my game suddenly minimized in order to show the update message from ShareX. Not a big deal for me since I wasn't doing anything competitive, but if someone is playing CS:GO, Dota 2, LoL, or some other important game and it suddenly minimizes to show an update window from ShareX, you can bet they're going to uninstall ShareX as soon as they possibly can out of sheer rage.

Just my 2 cents.

**Comment by Jaex** [comment]
I already made update message to not activate itself and tried in fullscreen games. It was not minimizing my fullscreen games. Only in first update check it activates, which means when ShareX is opening.

**Comment by rahlzel** [comment]
Well, it's happening in at least one configuration - mine. That might be enough for me to want to suppress update messages and instead have a small bottom-right notification like with default Windows when there's a new Windows Update, or like a Skype notification. Something that the operating system thinks is less important. Food for thought.

**Comment by Jaex** [comment]
I opened CS:GO and ShareX update window not minimized game. It was staying in taskbar not active.

**Comment by rahlzel** [comment]
Do you have a way of trying Assassin's Creed Rogue? How about other games?

Since it's just for testing purposes, a quick torrent download to check it might be reasonable. I'm using [this one](http://kickass.to/assassin-s-creed-rogue-v-1-1-0-2015-pc-repack-by-r-g-freedom-t10329445.html).

**Comment by Jaex** [comment]
Sorry I don't pirate games.

**Comment by rahlzel** [comment]
Is that because you don't like to, or you're not sure how? If it's the latter I can show you. It'd be for a good cause, at least - testing.

In either case, thank you for ShareX. I was using Greenshot for about a year and recently discovered it. I LOVE it.

**Comment by WebFreak001** [comment]
Are you playing actual fullscreen or borderless window?

**Comment by rahlzel** [comment]
Fullscreen.
