### ISSUE TITLE
Feature suggestion: keyboard shortcut for rectangle region

### ISSUE THREAD

**Issue by abcasada** [ShareX/ShareX#5433]
I often use the keyboard shortcuts, right before taking a screenshot, to switch to the tools for drawing on the screen (such as R for rectangle). However there is no shortcut to return to the rectangle region tool (for selecting a rectangular region to screenshot). Would it make sense to add a shortcut for that?

**Comment by Jaex** [comment]
Tab key or mouse middle click.

**Comment by abcasada** [comment]
Great. Thanks.

Adam Casada

**Comment by berkdemir** [comment]
Suggestion: Adding the tab key to the end of Rectangle Region text similar to others.

**Comment by smauglys** [comment]
> > Suggestion: Adding the tab key to the end of Rectangle Region text similar to others.
> 
> Bump.
> 
> A very small change would save people from coming to this closed issue.

Definitely, was looking for wanting this feature for a few years, and finally searched enough to find this answer...
Adding TAB on the hover would help.
