### ISSUE TITLE
Is there any option to hide this red button so that it will only be shown in system tray?

### ISSUE THREAD

**Issue by zcraber** [ShareX/ShareX#5434]
It appears while screen-recording:

![image](https://user-images.githubusercontent.com/61133303/109599992-52138100-7b42-11eb-861b-68d31c0e602b.png)

My application settings:

![image](https://user-images.githubusercontent.com/61133303/109600014-5a6bbc00-7b42-11eb-81aa-75b1b0b21a86.png)

**Comment by vertigo220** [comment]
It's there as your only means of readily stopping the recording. Why not just move it into the overflow so it only shows if you click the arrow?

**Comment by zcraber** [comment]
> It's there as your only means of readily stopping the recording. 
I actually meant hiding it among the system tray icons. 

> Why not just move it into the overflow so it only shows if you click the arrow?
Sorry, I didn't get this. Do you mind explaining?

**Comment by vertigo220** [comment]
![Screenshot_21-08-10_04 08](https://user-images.githubusercontent.com/12024557/128831790-7b421dff-4449-4791-a374-92dcc6e40b51.gif)

**Comment by vertigo220** [comment]
And your title still doesn't make sense, since it's already in the system tray. So I don't know if my animation is what you're trying to do, or if I'm completely missing the point.

**Comment by zcraber** [comment]
When you start recording using ShareX, for me, that red icon appears on the taskbar first. And only when I click on the ^ icon, it will move to the system tray.

https://user-images.githubusercontent.com/61133303/128836949-f6e3c808-f371-4e0d-a8c6-8467df61c90a.mp4

**Comment by vertigo220** [comment]
For me, if it shows when I start a recording, if I drag it into the overflow, then stop the recording, the next time it doesn't show but is automatically in the overflow right away.
