### ISSUE TITLE
Not listing any installed image effects with image editor

### ISSUE THREAD

**Issue by kanaxx** [ShareX/ShareX#5437]
I woud like to report the problem of Image Effect function.

I have installed Image Effect (polaroid.sxie) into my ShareX.

# Good case
I can use polaroid image effect from following two ways.
 - Main Window > tools > Image Effect
 - Thumbnail image (Right Click) > add Image effect

![image](https://user-images.githubusercontent.com/36564954/109807408-30f98000-7c69-11eb-9be4-b8557c0bc737.png)

# Bad case
I can't find any preset of Image Effects when I start "add image effect" with Image Editor.

select "add image effect" from image editor tool menu.
![image](https://user-images.githubusercontent.com/36564954/109807555-669e6900-7c69-11eb-9e57-d0517c03c922.png)

no preset shows in this window.
![image](https://user-images.githubusercontent.com/36564954/109807683-8d5c9f80-7c69-11eb-8596-15666b8924f3.png)

Could anyone fix this problem?

**Comment by t0l0** [comment]
+1
I experience this problem too.
ShareX 13.4

**Comment by wdcook4** [comment]
I recently found this out after making and packaging my own image effect. Maybe this window could use the same presets as the regular Image Effects window? (I also found out that you can't import an image from the clipboard into Image Effects like you can the Editor without saving it to disk first, which is somewhat annoying)

**Comment by azhe403** [comment]
Same here.

ShareX 13.5

![image](https://user-images.githubusercontent.com/17938038/128591386-64ccf974-fee4-478a-99b9-f2d6e7649427.png)
![image](https://user-images.githubusercontent.com/17938038/128591395-78e84cd2-44ff-48bc-a9e7-46748dd4c793.png)

**Comment by azhe403** [comment]
Up

**Comment by diegobajetti** [comment]
experiencing the same issue myself
