### ISSUE TITLE
Share X won't record Audio 

### ISSUE THREAD

**Issue by Barrystea** [ShareX/ShareX#5439]
I'd like to preface from the start I don't have bitdefender or any other similar software that would deny permission. Also one thing I noted on the video codec it doesn't allow me to select X264( Mp4) it allows me to select H264/X264 I'm not sure if they are the same thing.
Below I will attach a screenshot of my current settings on share x, the video codec options, the command line preview and the error message. Hopefully one of you guys can crack my problem.
Command line preview: -rtbufsize 150M -f gdigrab -framerate 30 -offset_x 0 -offset_y 0 -video_size 1920x1080 -draw_mouse 1 -i desktop -f dshow -i audio="virtual-audio-capturer" -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a libmp3lame -qscale:a 6 -y "output.mp4"

![ShareX_g15XGINiEX](https://user-images.githubusercontent.com/80043422/109972520-4f09c380-7cef-11eb-9071-b601dd1e2c2f.jpg)

![94EPPSXGLw](https://user-images.githubusercontent.com/80043422/109972539-5630d180-7cef-11eb-929f-7aafe5a4df76.jpg)

Error Message:   libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[gdigrab @ 000002162d6afd40] Capturing whole desktop as 1920x1030x32 at (0,0)
[gdigrab @ 000002162d6afd40] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1614865544.703063, bitrate: 1898508 kb/s
    Stream #0:0: Video: bmp, bgra, 1920x1030, 1898508 kb/s, 30 fps, 1000k tbr, 1000k tbn, 1000k

 Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, dshow, from 'audio=virtual-audio-capturer':
  Duration: N/A, start: 773099.243000, bitrate: 1536 kb/s
    Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
C:\Users\Barry\OneDrive\Documents\ShareX\Screenshots\2021-03\UZEI3ZzQAV.mp4: Permission denied
Received stop event after 255 passes

**Comment by TicTac9k1** [comment]
I had this exact issue with recording. It seems that ShareX looks at the "Recorder Devices for ShareX" install path or ..\Documents\ShareX\Tools because when doing a dry test run I get the error audio="virtual-audio-capturer" not found.

After https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/tag/v0.12.11 grabbing this release and copy over the virtual audio capturer dll files to the install dir and ..\Documents\ShareX\Tools it worked.

I haven't narrowed down which folder is the determining location ShareX uses to check the presence of the files, but it's either one of those.

**Comment by gauravr397** [comment]
@Barrystea 
![ShareX_cTo8PtoXpd](https://user-images.githubusercontent.com/57338455/111733606-4e039500-889e-11eb-9e3e-f2b7455f4636.png) 
try these no issues on these for me

**Comment by Ryann778** [comment]
I faced similar issue but setting the app to always run as administrator fixed the problem.
