### ISSUE TITLE
File naming won't work for image width and height

### ISSUE THREAD

**Issue by madzadev** [ShareX/ShareX#5442]
Currently, all the filenames including `%width` and `%height` are being generated using the user's screen resolution (constant), not the specific image resolution, that has been cropped.

![1920x1080](https://user-images.githubusercontent.com/42511917/110206458-6dee8e00-7e86-11eb-90fe-219293ab7fca.png)

**Comment by Jaex** [comment]
I tested now it using image width and height for me.

**Comment by madzadev** [comment]
@Jaex Appreciated the fast response!
Strange. Just did a screenshot and here is the produced filename:

![1920x1080 (3)](https://user-images.githubusercontent.com/42511917/110207030-dd19b180-7e89-11eb-9d0c-718ea928b7f3.png)

Although the screenshot itself is 648x376.
I'm using Sharex v13.4.

**Comment by Jaex** [comment]
This was my test image: https://jaex.getsharex.com/2021/03/ShareX_PIXvNgpVQJ_846-503.png

**Comment by madzadev** [comment]
I guess I'm gonna try to re-install the app to see if that helps, will report back

**Comment by madzadev** [comment]
@Jaex Yup, can confirm, re-installed, and now works as expected!
Thanks for the feedback! An awesome and powerful tool 👍
