### ISSUE TITLE
ShareX FFMPEG error: video is not recorded

### ISSUE THREAD

**Issue by RomyTheBoy** [ShareX/ShareX#5457]
I have a problem and I can't solve it in any way(((
After I press "Stop" when recording a video, it continues to be recorded for a while, and then this error appears:

ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.2.1 (GCC) 20200726
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil 56. 51.100 / 56. 51.100
libavcodec 58. 91.100 / 58. 91.100
libavformat 58. 45.100 / 58. 45.100
libavdevice 58. 10.100 / 58. 10.100
libavfilter 7. 85.100 / 7. 85.100
libswscale 5. 7.100 / 5. 7.100
libswresample 3. 7.100 / 3. 7.100
libpostproc 55. 7.100 / 55. 7.100
[gdigrab @ 000001d69278ef80] Capturing whole desktop as 174x172x32 at (574,133)
Input #0, gdigrab, from 'desktop':
Duration: N/A, start: 1615487481.342944, bitrate: 28743 kb/s
Stream #0:0: Video: bmp, bgra, 174x172, 28743 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, dshow, from 'audio=virtual-audio-capturer':
Duration: N/A, start: 717528.201000, bitrate: 1536 kb/s
Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
Stream mapping:
Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[gdigrab @ 000001d69278ef80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 000001d6933ad3c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 000001d6933ad3c0] profile High 4:4:4 Predictive, level 1.2, 4:4:4, 8-bit
[libx264 @ 000001d6933ad3c0] 64 - core 161 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=2 lookahead_threads=2 sliced_threads=1 slices=2 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
[dshow @ 000001d6927eb700] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Finishing stream 0:1 without any data written to it.
Output #0, mp4, to 'C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4':
Metadata:
encoder : Lavf58.45.100
Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv444p(progressive), 174x172, q=-1--1, 30 fps, 15360 tbn, 30 tbc
Metadata:
encoder : Lavc58.91.100 libx264
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
Metadata:
encoder : Lavc58.91.100 aac
frame= 1 fps=0.1 q=0.0 Lsize= 20kB time=00:00:00.00 bitrate=2517661.5kbits/s speed=7.01e-06x
video:19kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 4.085890%
[libx264 @ 000001d6933ad3c0] frame I:1 Avg QP: 0.00 size: 19137
[libx264 @ 000001d6933ad3c0] mb I I16..4: 100.0% 0.0% 0.0%
[libx264 @ 000001d6933ad3c0] coded y,u,v intra: 100.0% 98.6% 98.3%
[libx264 @ 000001d6933ad3c0] i16 v,h,dc,p: 37% 61% 2% 0%
[libx264 @ 000001d6933ad3c0] kb/s:4592.88
[aac @ 000001d692829680] Qavg: nan
Received stop event after 931 passes
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.2.1 (GCC) 20200726
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil 56. 51.100 / 56. 51.100
libavcodec 58. 91.100 / 58. 91.100
libavformat 58. 45.100 / 58. 45.100
libavdevice 58. 10.100 / 58. 10.100
libavfilter 7. 85.100 / 7. 85.100
libswscale 5. 7.100 / 5. 7.100
libswresample 3. 7.100 / 3. 7.100
libpostproc 55. 7.100 / 55. 7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4':
Metadata:
major_brand : isom
minor_version : 512
compatible_brands: isomiso2avc1mp41
encoder : Lavf58.45.100
Duration: 00:00:00.03, start: 0.000000, bitrate: 4813 kb/s
Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 174x172, 4717 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
Metadata:
handler_name : VideoHandler
Codec AVOption b (set bitrate (in bits/s)) specified for output file #0 (C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Output C:\Users\Дракончик\Documents\ShareX\Screenshots\2021-03\Screen 21.31, 11.03.2021.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.

And in the folder for the video, a video appears, but its duration is 00:00:00
What should I do?

![Video 22 12, 11 03 2021](https://user-images.githubusercontent.com/75387140/110950254-ad205180-8354-11eb-8f34-06768e0473d7.png)
![Video 17 00, 12 03 2021](https://user-images.githubusercontent.com/75387140/110950271-b3aec900-8354-11eb-8e00-0a408800f524.png)

**Comment by Casiyus** [comment]
Hello. I am facing the same error, did you happen to find the solution ?
Screen recorder works fine on its own but when it is in advanced options it gives me this error too.

**Comment by Polyterative** [comment]
Here too

**Comment by Kuroonehalf** [comment]
Same here.

**Comment by AndroidDeveloperLB** [comment]
Could this be related:
https://github.com/ShareX/ShareX/issues/6390
?
