### ISSUE TITLE
Ability to configure the hotkey's for Image Editor!!

### ISSUE THREAD

**Issue by kartikfire** [ShareX/ShareX#5463]
Feature Request: It would help us a lot if we can configure our own custom hotkey's for image editor, as well as the toolbar that apper's on the top of the capture.

**Comment by Skylertodd** [comment]
Just to add to this, things like spacebar discards changes and closes is almost frustrating enough to no longer use this tool... Who thought right click to delete was a good call?

**Comment by Jaex** [comment]
> Just to add to this, things like spacebar discards changes and closes is almost frustrating enough to no longer use this tool... Who thought right click to delete was a good call?

I thought. It allows me to add or remove stuffs quickly.

**Comment by notNSANE** [comment]
Have to comment to prevent bug close, this would be a very useful feature.

**Comment by gmkado** [comment]
Is there really no way to change this?

**Comment by lihuelworks** [comment]
Also want this, stop marking as stale please.
