### ISSUE TITLE
Button/Option to upload image in non-default destination.

### ISSUE THREAD

**Issue by billionaire** [ShareX/ShareX#547]
Hi.
Thank you for excellent program.
I usually upload all screenshots to my ftp server, but sometimes I need a one-time upload the image to the public service (eg imgur.com).
For this I change destination before creating screenshot.
It would be convenient to add a button (or something else) to select a different destination at a one time, if such functionality needed by many people.
Thank you for your attention.
Kind regards.
![sharex](https://cloud.githubusercontent.com/assets/6255854/6605295/6faccad8-c837-11e4-8271-2dc6b4e25dc9.png)

**Comment by Jaex** [comment]
You can set two different hotkey for your capture & upload operations.
One can upload to FTP other can upload to Imgur.
Or you can use one of these settings to show destination window:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/03/pJbaHt7a2G.png)
But hotkey would be more convenient solution.

**Comment by billionaire** [comment]
By the way, ShareX can force open "Before upload" window, if user press the "Save and close" button with pressed Alt (Ctrl, Shift or other combination).
![screen3](https://cloud.githubusercontent.com/assets/6255854/6649430/5c8474da-c9f2-11e4-8003-27b15057a827.png)
