### ISSUE TITLE
ShareX preventing Windows from shutting down

### ISSUE THREAD

**Issue by Zenoo** [ShareX/ShareX#5470]
Every time I shut down my computer, ShareX is preventing the shutdown for a good minute ...

```
GDI+ Window (ShareX.exe)
This app is preventing shutdown
```

![IMG_20210319_004809](https://user-images.githubusercontent.com/7151485/111865489-95a22380-8967-11eb-9120-a4eaa7fcb194.jpg)

**Comment by Killshot-1337** [comment]
Click shut down anyway,it doesn't affect anything and instantly shuts down your pc.

**Comment by Zenoo** [comment]
That's kind of an "under the rug" solution, though
