### ISSUE TITLE
ShareX doesn't start at bootup

### ISSUE THREAD

**Issue by sbot50** [ShareX/ShareX#5475]
So, ik this has been adressed in another post but nobe of the solutions there worked (UAC/creating a new process on startup).
The shortcut in the startup folder works fine and the app itself and shortcut are both set to run as administrator.
Idk what else i can try and its getting annoying needing to startup sharex manually every time.
Please help.

**Comment by MaciejGorczyca** [comment]
I have the issue as well for at least few months and it kinda got to the point of being annoying.

Enabled in task manager startup apps.

![2021-03-31-03-30-32-038-560x332-Task_Manager](https://user-images.githubusercontent.com/26925976/113077493-8e81dd80-91d1-11eb-88e4-c2f85e4982ab.png)

Enabled in settings.

![2021-03-31-03-30-44-261-739x434-ShareX_-_Application_settings](https://user-images.githubusercontent.com/26925976/113077520-980b4580-91d1-11eb-89d0-e5f2cd680bed.png)

The app simply does not start. Checking logs shows that it didn't even attempt to start. There are no logs from the time of starting up the system.

**Comment by Sbot50** [comment]
> I have the issue as well for at least few months and it kinda got to the point of being annoying.
> 
> Enabled in task manager startup apps.
> 
> ![2021-03-31-03-30-32-038-560x332-Task_Manager](https://user-images.githubusercontent.com/26925976/113077493-8e81dd80-91d1-11eb-88e4-c2f85e4982ab.png)
> 
> Enabled in settings.
> 
> ![2021-03-31-03-30-44-261-739x434-ShareX_-_Application_settings](https://user-images.githubusercontent.com/26925976/113077520-980b4580-91d1-11eb-89d0-e5f2cd680bed.png)
> 
> The app simply does not start. Checking logs shows that it didn't even attempt to start. There are no logs from the time of starting up the system.

So I'm not the only one? Good... Now we need a fix lol

**Comment by Jorgi-1** [comment]
You could always use the task scheduler on windows or similar to start the sharex exe upon boot until you get a real fix for the issue.

**Comment by sbot50** [comment]
I finally found a fix, use the second method in this video: https://www.youtube.com/watch?v=_bTTdKi7Lvg
