### ISSUE TITLE
Time zone from filename template.

### ISSUE THREAD

**Issue by billionaire** [ShareX/ShareX#548]
Hi.
In the settings ShareX user can specify a file name template. In particular, the creation of images. It is very convenient.
But there is a caveat: when user publish anywhere link to an image, other users can find out what time zone is set to the user's PC, which publishes the image.
It would be convenient to add ability to set custom time zone (UTC, GMT-+X, etc).
Thank you.
Regards.
![sharex2](https://cloud.githubusercontent.com/assets/6255854/6605722/c4f1fa06-c83a-11e4-9dea-057ab88c034a.png)

**Comment by Jaex** [comment]
So you want to be able to select gmt which will apply to both name patterns?

**Comment by billionaire** [comment]
Yes. GMT or UTC (for myself i have not decided what its better, in this case, but you have more experience to make such decisions).
If it is necessary for someone other than me, and it is worth spending time developers.

**Comment by Jaex** [comment]
I will add dropdown box top of name pattern section which will have list of gmt from -12 to +12 and this selection will apply to two name patterns.

**Comment by Jaex** [comment]
I added this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/03/kwcHy87SGX.png)

But not sure is it possible to detect daylight saving from these regions or I must add separate setting for it.

**Comment by Korb** [comment]
> ShareX - Task settings / Upload
> Name pattern for capture or clipboard upload:
> %y%mo%d%h%m%s%ra%cr%ra%cr%ra%cr%ra%cr%ra
> Preview: 20150311215659MDjhLUJ59Y
> Name pattern for active window capture:
> %y%mo%d%h%m%s%ra%cr%ra%cr%ra%cr%ra%cr%ra
> Preview: 20150311215659FU9g48Na72
> Reset auto increment number**
> Use name pattern for file uploads too instead actual file name

Where were the automatic file name by mask settings moved? In the current version, the `Upload` tab contains only the following settings:

> Simultaneous upload limit
> Buffer size
> Number of times to retry if upload fails
> Use secondary uploaders in order of preference when retrying
> Secondary image uploaders
> Secondary text uploaders
> Secondary file uploaders
