### ISSUE TITLE
Volume is too low while recording

### ISSUE THREAD

**Issue by Killshot-1337** [ShareX/ShareX#5480]
Hello,I tried to record some videos with sharex but the volume is too low.The only way I can make it somewhat audible is by turning my pc volume to max.It'd be great if you guys could add configurable volume or something to get rid of this issue.
Thanks for the great software!
PS:Forgive me if this has been asked before.

**Comment by mihail4o** [comment]
Are you using Bluetooth audio connection? If so, try to connect directly via 3.5mm jack, if it is possible. I had a similar problem and the only way to get audio to works was to eliminate wireless connection! The ShareX don't know how to handle it - correct me if I am wrong!

**Comment by benafrank** [comment]
I'm experiencing the same issue with ShareX using the default microphone. All other applications record the microphone volume clearly and at a good level. However, with ShareX, I have to turn the input volume up to the maximum, resulting in unbearable background noise and static.
