### ISSUE TITLE
FFmpeg Error After Recording more then 4 min

### ISSUE THREAD

**Issue by HA4g3n** [ShareX/ShareX#5481]
Same error over two computers, latest version.
FFmpeg error after recording more then 3-4 minutes, before i could record several hours.
I think it's the FFmpeg that fails?

I have reinstalled, changed codec, clicked install recorder devices, tried alternative FFmpegs without any results. 

After exiting the recording the application is stuck in this recording mode after some seconds it shows this error:
**Always ends with something like:**
[dshow @ 000002a8e25bf1c0] real-time buffer [screen-capture-recorder] [video input] too full or near too full (88% of size: 150000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 8 times
[dshow @ 000002a8e25bf1c0] real-time buffer [screen-capture-recorder] [video input] too full or near too full (99% of size: 150000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 5 times
[dshow @ 000002a8e25bf1c0] real-time buffer [screen-capture-recorder] [video input] too full or near too full (110% of size: 150000000 [rtbufsize parameter])! frame dropped!

Log is addatched as a file.
[Error_Log.txt](https://github.com/ShareX/ShareX/files/6207334/Error_Log.txt)

Settings:
![image](https://user-images.githubusercontent.com/13786699/112531737-377ea180-8da8-11eb-9c13-45e890207047.png)

**Comment by HA4g3n** [comment]
No reaction?

**Comment by zvodd** [comment]
The first item in the "Command line preview" looks like it sets the video buffer memory size  to 150M with  `-rtbufsize 150M`
You could manually increase that number, it should mean that you can record for longer at the cost of utilizing more system memory whilst recording.

**Comment by HA4g3n** [comment]
> The first item in the "Command line preview" looks like it sets the video buffer memory size to 150M with `-rtbufsize 150M`
> You could manually increase that number, it should mean that you can record for longer at the cost of utilizing more system memory whilst recording.

Hi,
I changed that value it to 1500MB and application still crashes when saving longer sessions.
I did some reading of recommended changes for optimizing the recordings and i changed the codec from x264 to x265 but i still cannot record a 40 min session.

Here is the error:

frame=98851 fps= 30 q=19.5 size=  229632kB time=00:54:54.83 bitrate= 570.9kbits/s dup=7 drop=6 speed=   1x    
frame=98866 fps= 30 q=19.5 size=  229632kB time=00:54:55.33 bitrate= 570.9kbits/s dup=7 drop=6 speed=   1x    
frame=98881 fps= 30 q=19.5 size=  229632kB time=00:54:55.83 bitrate= 570.8kbits/s dup=7 drop=6 speed=   1x    
frame=98896 fps= 30 q=19.5 size=  229632kB time=00:54:56.33 bitrate= 570.7kbits/s dup=7 drop=6 speed=   1x    
[mp4 @ 0000022654837080] Starting second pass: moving the moov atom to the beginning of the file
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (75% of size: 150000000 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (92% of size: 150000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 2 times
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 20 times
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (62% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (63% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (65% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 1 times
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (66% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (68% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (69% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (71% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
[dshow @ 0000022654831a40] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (72% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 00000226547cf200] real-time buffer [screen-capture-recorder] [video input] too full or near too full (101% of size: 150000000 [rtbufsize parameter])! frame dropped!
    Last message repeated 1 times

**Comment by HA4g3n** [comment]
> The first item in the "Command line preview" looks like it sets the video buffer memory size to 150M with `-rtbufsize 150M`
> You could manually increase that number, it should mean that you can record for longer at the cost of utilizing more system memory whilst recording.

https://github.com/ShareX/ShareX/issues/5481
-f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2:duration=longest

Hi,
I changed that value it to 1500MB and application still freezes and then crashes when saving longer sessions and you stop the recording.
I did some reading of recommended changes for optimizing the recordings and i changed the codec from x264 to x265 but i still cannot record a 40 min session.
Have reinstalled application and same error on several computers. Have reinstalled the recording devices as well.

Here is the error in the end of outoutfile:
frame=122993 fps= 30 q=19.5 size=  282880kB time=01:08:19.56 bitrate= 565.3kbits/s speed=   1x    
frame=123008 fps= 30 q=28.2 size=  282880kB time=01:08:20.06 bitrate= 565.2kbits/s speed=   1x    
[mp4 @ 000001f904fec400] Starting second pass: moving the moov atom to the beginning of the file
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (63% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (65% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (66% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (68% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (69% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (71% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (72% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (74% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (75% of size: 3041280 [rtbufsize parameter])! frame dropped!
    Last message repeated 1 times
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (76% of size: 3041280 [rtbufsize parameter])! frame dropped!
    Last message repeated 1 times
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (77% of size: 3041280 [rtbufsize parameter])! frame dropped!
    Last message repeated 1 times
[dshow @ 000001f904f7f380] real-time buffer [screen-capture-recorder] [video input] too full or near too full (64% of size: 1500000000 [rtbufsize parameter])! frame dropped!
[dshow @ 000001f904fe1c00] real-time buffer [virtual-audio-capturer] [audio input] too full or near too full (78% of size: 3041280 [rtbufsize parameter])! frame dropped!

**Comment by Suryadreams** [comment]
I am facing the same issue. Any solution to this?
