### ISSUE TITLE
Support Ed25519 SSH keys for SFTP uploader

### ISSUE THREAD

**Issue by GTAXL** [ShareX/ShareX#5482]
Please add support for the modern and fast Ed25519 ssh key for the SFTP uploader. This offers strong security but is much faster than RSA. More info here, https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54

**Comment by sylveon** [comment]
The library we use for SSH doesn't support it yet. There is a PR for it here: https://github.com/sshnet/SSH.NET/pull/614. Once merged it should eventually show up in a release of SSH.NET and then in ShareX.

**Comment by MAGICCC** [comment]
Since upstream got merged, I hope we'll see some progress on it then here

**Comment by alucard87pl** [comment]
Any progress on this?

**Comment by Jaex** [comment]
What progress?

**Comment by sylveon** [comment]
The upstream PR got merged but no new release of SSH.NET has been made since, so we cannot provide it yet.

**Comment by MAGICCC** [comment]
:)
https://github.com/sshnet/SSH.NET/releases/tag/2020.0.2

**Comment by Jaex** [comment]
> :) https://github.com/sshnet/SSH.NET/releases/tag/2020.0.2

https://github.com/ShareX/ShareX/commit/11d4dc8b5a8c133ff174459db3d09dfe8323c8ac

👍

**Comment by MAGICCC** [comment]
Seems it's still not working correctly but thats a SSH.net issue (yay)
If you want to use ed25519 keys you may use ssh-keygen to generate a key using a different encryption
`ssh-keygen -t ed25519 -b 384 -C "<comment>" -f <output_keyfile> -Z aes256-cbc`

>-Z cipher
>Specifies the cipher to use for encryption when writing an OpenSSH-format private key file.  The list of available ciphers may be >obtained using "ssh -Q cipher".  The default is “aes256-ctr”.


Also see https://github.com/sshnet/SSH.NET/issues/742
