### ISSUE TITLE
Korean Character on File Name Changing to '_'

### ISSUE THREAD

**Issue by sanvit** [ShareX/ShareX#5483]
Right clicking a file and choosing 'Upload with ShareX' does upload the file, but changes all Korean character to '_'.

e.g.

테스트_PDF_파일.pdf => \_\_PDF\_.pdf

This happens on both Amazon S3 and Dropbox.

**Comment by sylveon** [comment]
Uncheck "Replace characters problematic in URLs by underscores when uploading" in Task settings > Upload > File naming

**Comment by sanvit** [comment]
That indeed fixed the problem! Thanks!
