### ISSUE TITLE
How to make all screenshots in one folder rather than multi-folders by monthly?

### ISSUE THREAD

**Issue by GF-Huang** [ShareX/ShareX#5490]
![image](https://user-images.githubusercontent.com/4510984/112760842-fa761180-902a-11eb-9bfa-d8935d4c59d9.png)

**Comment by radekvebr** [comment]
Remove the subfolder pattern in Application settings.

![image](https://user-images.githubusercontent.com/3408993/113573008-94d0e900-9619-11eb-8e94-f50b18a82926.png)
