### ISSUE TITLE
FFMPEG error

### ISSUE THREAD

**Issue by el-bekasto** [ShareX/ShareX#5492]
Hi, I got the error when I finished a 40 minute recording. The record is preserved, weighs 2 GB(I must say, too much for such a video, perhaps the compression did not work), but does not open. More precisely, it opens, but does not play. Unfortunately I didn't take screenshot of error because didn't pay attention to it then. I searched and found an [issue](https://github.com/ShareX/ShareX/issues/2761) that has a similar problem. But first: that user has different errors. Secondly: he can't even start recording at all, while I can successfully record minute videos without any errors. But the error appeared when I recorded longer video, in this case 40 minute videos. And I would like to restore that 2 GB video, is it possible?

Also, what is remarkable, when I finished my work and wanted to stop recording by clicking on the button in the taskbar, I had to press it several times, the program froze a little. Maybe this is the problem? Maybe I should have clicked once and waited instead of clicking many times?

**Comment by el-bekasto** [comment]
And if necessary, this is how my settings look like, though in Russian:
![image](https://user-images.githubusercontent.com/57838936/112841155-98182200-90b9-11eb-86a9-269f4801cda7.png)

**Comment by grindmasterbear** [comment]
https://vb-audio.com/Cable/ install this
