### ISSUE TITLE
[Bug] After capture settings stick

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5493]
### Summary:
After first run, the first run's "After capture tasks" automatically executed

### Illustrative Steps:
1. ShareX
2. Tools > image editor/Image Combiner > do some relevant things 
3. Run 'after capture tasks'
![image](https://user-images.githubusercontent.com/19423063/112943613-55a12480-914f-11eb-9ff7-6722e0f32c11.png) 
![image](https://user-images.githubusercontent.com/19423063/112943899-b92b5200-914f-11eb-89b9-c0538d88eac0.png)
4. After capture tasks window shall open
5. Click continue
6. Return back to the tool in step 2
7. Redo step 3

### Reality
This time the after capture tasks window won't open, but the tasks that were selected last time will automatically execute.

### Expectations
The capture tasks window should open like they do the first time "Run after capture tasks" is run.

**Comment by ndroftheline** [comment]
i may be experiencing a similar/same thing. all i think i changed after install was to enable "show quick task menu" on "after capture tasks" so i could optionally annotate a screen capture. when i click run after capture tasks from the annotate screen, it just exits and the image isn't on my clipboard. not running annotate behaves as expected. perhaps this is the same basic problem, and i've got a task nesting situation i'm not aware of?

**Comment by yashpalgoyal1304** [comment]
tale tale tale, this issue is not stale

**Comment by yashpalgoyal1304** [comment]
.

**Comment by yashpalgoyal1304** [comment]
wow - shame that the bot is not updated to "close as not planned" - nice!
