### ISSUE TITLE
Consider changing the default upload behaviour to avoid accidentally sharing sensitive data

### ISSUE THREAD

**Issue by blake-mealey** [ShareX/ShareX#5497]
When I first used ShareX many years ago I loved the default behaviour of uploading to Imgur and copying the URL to my clipboard. Since then I've realized that over the years on various computers I've probably uploaded many images with sensitive data in them. When it comes to using it on my work machine, the first thing I do is change the settings to avoid this possibility. This makes it harder for me to recommend this amazing app to colleagues because I have to preface it with the warning *make sure to change the default settings before use*! Today I forgot to add that caveat and a coworker accidentally started uploading images to Imgur. He realized the mistake and quickly deleted them but it got me thinking more about this.

For the last couple of years I have been using the "After capture tasks":
* Copy image to clipboard
* Save image to file

And I now believe these should be the default settings. In a world where users are starting to wake up about privacy, these settings give full control to users on where to upload their images with almost the same user-experience as the Imgur links. You can paste the image into any of the communication tools I regularly use (e.g. Facebook Messenger, WhatsApp Web, Microsoft Teams, Discord, Slack, GMail, etc.) and it will automatically upload them to the service. Additionally, this would make it a no-brainer for recommending to co-workers for company use.

Of course, some users may still prefer the Imgur upload, and they may choose to enable it themselves, but I believe they should no longer be the default settings.

Thanks for your consideration.

**Comment by blake-mealey** [comment]
Interesting, I didn't know that! Maybe this is a case of users not reading carefully. I know that in the case of my coworker today he uploaded about a dozen screenshots before noticing.

**Comment by boorac** [comment]
If you take a screenshot, you will be prompted if you wish to upload an image or not.

However, if you just want to use the embedded editor to edit any image, and __Upload__  (thinking for example it is a localhost server used for any reason) Sharex to be able to annotate, these files **will** be uploaded, **even if** you answered no to the above screenshot and __After capture tasks __ -> __Upload image to host__  is **not selected**. 

It was very unclear to me how to add files to Sharex without uploading, and it never even crossed my mind that any application would just upload screenshots to Imgur using an anonymous account - granted I should have read the documentation more thoroughly, however for a simple screenshotting application (and for my needs which are screenshots and possibly any simple image editing), this application is way out of scope.
