### ISSUE TITLE
Where is the 'Quick Tasks Menu Editor'?  

### ISSUE THREAD

**Issue by Snacko** [ShareX/ShareX#5498]
Thanks for this awesome program!!

I want to have my screenshots organized by the application's name that they were taken from.  But I see no option in the file naming convention to allow this.  So then, I thought I could have it organized by the subfolder name, but this also does not allow using the application name in the subfolder's naming convention.

So, I thought I could edit the Quick Tasks Menu to add some folder destinations?  But I cannot find this editor.  I've googled the internet, and also https://getsharex.com, with no result.  But I see some questions about this editor, so I'm hoping that it exists?

Thanks again.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2021/04/ShareX_reDX4Buqmc.png)

**Comment by Snacko** [comment]
Damn!  How'd I miss that?  Thanks!
