### ISSUE TITLE
1 second key lock after image capture makes workflow slow

### ISSUE THREAD

**Issue by TheCoinAxe** [ShareX/ShareX#5505]
I understand that a 1 second key lock is added to the image editor (after capture) because of requests from other users who find it interfering with hotkeys.

But I'm facing the opposite scenario where this key lock is making my workflow very slow in a way that I have to remember to wait a second until I can press enter (I tend to work fast with keyboard and shortcuts). Is it possible to add an option in the advanced menu to disable it on/off please.

**To reproduce this:**
Take a screenshot with the option of seeing the image editor after, then as soon as you do quickly tap enter or space after it, usually you'll wait till the 3rd or 4th click until it registers and closes. This is really annoying when I'm trying to work fast, as I have to wait for a second to pass until I can save my image to the clipboard.

I hope an option can be added to disable this key lock.

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/commit/65062b5332d16858ba5a8dbed46f70c2d0881fb0
