### ISSUE TITLE
SFTP: Uploading a file seems to be abnormally slow, possible to implement SCP?

### ISSUE THREAD

**Issue by LShirohana** [ShareX/ShareX#5508]
Whenever I upload to my own website over SFTP, I will max at 800 - 850 KB/s. This is unusual because if I upload to my own website using WinSCP, which, as far as my small googling shows, uses the same method, it will upload easily @ 5 MB/s, and I can upload anywhere else with the same speed. 

Is SCP and SFTP not the same? If not, would it be possible to add SCP as an upload option? Thanks for any help if someone knows a better method.

Edit: Well, embarrassing, but just a quick look @ a comparison table shows that SFTP and SCP are not the same, and SCP has a vastly more efficient algorithm for encryption, hence the better upload. 

Therefore, I'm changing this to ask about SCP implementation.

**Comment by QuAzI** [comment]
According to https://www.openssh.com/txt/release-8.9
```
A near-future release of OpenSSH will switch scp(1) from using the
legacy scp/rcp protocol to using SFTP by default.
```
So SCP was obsoleted
