### ISSUE TITLE
[Feature] Nestable Tasks System

### ISSUE THREAD

**Issue by aStonedPenguin** [ShareX/ShareX#5512]
###  The suggestion:
Replace destinations, custom uploaders, after capture tasks and after upload tasks with a nestable tasks system.

### Why:
While making a custom uploader I needed to do more than just POST one url. While I could accomplish this with actions or some other suboptimal unintended use of features this doesn't allow me to share my custom uploader without a lengthy setup process. What if you could just make custom tasks? The possibilities are endless at that point.

 ### Benefits:
- Modularizes practically everything
- Cuts down on niche requests significantly
- Simplifies everything for the lay user
- Expands functionality for the power user
- Implements #1024 without the security concerns or need to maintain any sort of API compatibility 
- Implements #1712, add a delay task
- Implements #2056 & #3992, just make a new task for each uploader
- Implements #2047, add a copy image task
- Could implement #4033 if conditional support was added

### Example:
![task1](https://i.imgur.com/Awas2jG.png)
![task2](https://i.imgur.com/9hbOHtA.png)

**Comment by yashpalgoyal1304** [comment]
interesting suggestion
