### ISSUE TITLE
Need Help with getting my app to stay as active window when recording.

### ISSUE THREAD

**Issue by L0VEFIRE** [ShareX/ShareX#5516]
So when I intiate a screenshot or a screen recording, most recordings, the recording box statys as the active window until i click the screen again to select the app im using i want to capture. 

How do i have Share X automaticly go back to the app i was using so its active and I dont have to click the screen and app again, its getting really annoying having to do this every time.

**Comment by yashpalgoyal1304** [comment]
i have had similar experience too
