### ISSUE TITLE
Suggestion: name files sequentially

### ISSUE THREAD

**Issue by Skylark13** [ShareX/ShareX#5518]
Hello,

If I take two screenshots of the same app one after the other, I think it would make sense if their names followed each other sequentially. That way, in an image viewer which has "next" and "previous" buttons, I could use them to swap between the images.

I just tested, and took two screenshots of MS Visual Studio (devenv.exe). The first one was named devenv_xC1LH70FMU.png, and the second was named devenv_c4DctxB6nW.png . It's fine if the exe name is the prefix, but I think the suffix should increment sequentially instead of being seemingly random (I'm sure that string of characters is based on something, but it looks random).

**Comment by saltoo666** [comment]
Its not based on anything it lets you change file naming scheme to whatever you want it would be best to set it to time of day since that means it would be sequential if you see it clearly says random characters.

**Comment by Skylark13** [comment]
Ah so there are actually options for that. Sorry, I hadn't noticed. Thank you!
