### ISSUE TITLE
Update nagging

### ISSUE THREAD

**Issue by raoulvdberge** [ShareX/ShareX#552]
When an update is available the ShareX updater asks me every x minutes to update; this is very annoying.

Is there an option to turn this off?

Thanks

**Comment by Jaex** [comment]
It checks for update every 60 minutes. Reason for this was some people not closing ShareX for weeks.
You can disable auto checking from Application settings, advanced tab.

**Comment by nathanchere** [comment]
This should be a LOT more prominent. Over a year later, still a really annoying 'feature'.
An update check frequency or even a simple box to uncheck under "General" would be a huge usability and overall experience improvement.

**Comment by hockeymikey** [comment]
A simple field for update interval would be great.  I want to keep it updated but I don't want to be updating the thing every day.

**Comment by dsverdlo** [comment]
Glad I found this issue. It is very annoying getting this popup all the time on 3+ devices.

**Comment by dsverdlo** [comment]
@Scrxtchy I have updated many times, but then always like a week later there is another update with features or changes that I won't ever use. All the time; update update. It just felt like a never ending, suffocating burden. Which is a pity since it is a great program with many features that does exactly what I want it to do (ever since the first version).

**Comment by Scrxtchy** [comment]
Every week, sharex only gets a major update once a month

**Comment by dsverdlo** [comment]
Most of the time yes. Coincidentally last update was only a week apart:
http://i.imgur.com/FJQUEKm.png

I've just never had this nagging feeling about any other program.
Anyway, I'm not one to complain much about freeware. I just wanted to SHARE my eXperience.

**Comment by BoltUpright** [comment]
I came looking for a way to turn off the Update nag every time I boot up...
Will setting **"AutoCheckUpdate" to False**, under Advanced in Application Settings do the trick?

I see this has been going on for a couple of years now. If the developer no longer wants to work on it, which I totally understand, perhaps hand it over to someone else? Or start charging $5-8 maybe? 
It's a great program.

It has been working fine for me on Win10 & have no wish to Update it regularly.
Thanks & cheers

**Comment by Scrxtchy** [comment]
Every time you boot up sounds like #1796

**Comment by BoltUpright** [comment]
**setting "AutoCheckUpdate" to False, under Advanced in Application Settings** 
worked for me! :)
