### ISSUE TITLE
Help for translate all string to Portuguese Brazil

### ISSUE THREAD

**Issue by wanderleihuttel** [ShareX/ShareX#5520]
Hello Guys
First of all, congratulations for this amazing software and many thanks for it

I would like to help to translate all missing strings of Portuguese Brazilian language, but I can't found the original ones. 
For example I'm trying to translate when I click with right button of mouse in the ShareX icon on task bar and appear some english strings yet, for example "Toggle actions toolbar". I've tried to found the this string in English for translate to Portuguese Brazilian, but I can't found.

**Comment by jakeob28** [comment]
> I would like to help to translate all missing strings of Portuguese Brazilian language, but I can't found the original ones.
> For example I'm trying to translate when I click with right button of mouse in the ShareX icon on task bar and appear some english strings yet, for example "Toggle actions toolbar". I've tried to found the this string in English for translate to Portuguese Brazilian, but I can't found.

See https://getsharex.com/docs/translation
