### ISSUE TITLE
offline use sharex portable opt out privacy

### ISSUE THREAD

**Issue by 5TDg9** [ShareX/ShareX#5521]
In this "closed" issue [here](https://github.com/ShareX/ShareX/issues/795) you said sharex could be used in offline mode:

I did set:
"AutoCheckUpdate" to false
"Disable Upload" to True

in last ShareX **portable** release [v13.4.0](https://github.com/ShareX/ShareX/releases/tag/v13.4.0)
but still:
my firewall reports a connection to internet:
for example to remote ip [140.82.121.5](https://who.is/whois-ip/ip-address/140.82.121.5) which is a github server.

What is this all about?
This is not privacy friendly behaviour.
No possibilty to opt-out from "online" tracking?
Nowhere to find a declaration on data protection or data processing?

**Comment by Jaex** [comment]
What "online" tracking you talking about...

**Comment by 5TDg9** [comment]
tell me. I don't know the ShareX code very well, but i trust my firewall.

**Comment by Jaex** [comment]
And your firewall tells GitHub server.

**Comment by botatooo** [comment]
ShareX's source code is available to anyone, and has been for a long while. Trust me, if there was something somewhere that was tracking, someone would have discovered it already.

P.S.: GitHub is a service used to host source code online, not track users.

**Comment by 5TDg9** [comment]
I just tell you what ShareX does. I don't audit code.
The connection to github could be because of checking for new releases.

Ok, the portable version doesn't store the settings. Why?

I will try it with the setup installer which is unfortunately not signed.
Another thing that can be critical.
Could you please provide a SHA-signature for the setup-packages?
This is important and will be more and more important to keep ShareX trustfully.

**Comment by 5TDg9** [comment]
I tried with the setup installer. Here the settings are kept stored.

1. First start: 
Firewall blocks [140.82.121.6](https://who.is/whois-ip/ip-address/140.82.121.6)

2. settings:
"AutoCheckUpdate" to false

3. after restart:
Firewall blocks connection to [185.199.111.153](https://who.is/whois-ip/ip-address/185.199.111.153)  (port 443).

4. go to settings again and
switch: "Disable Upload" to True

5. restart -> and still: 
ShareX tries to connect to [185.199.111.153](https://who.is/whois-ip/ip-address/185.199.111.153)

**Comment by 5TDg9** [comment]
> 
> 
> ShareX's source code is available to anyone, and has been for a long while. Trust me, if there was something somewhere that was tracking, someone would have discovered it already.
> 
> P.S.: GitHub is a service used to host source code online, not track users.

open source + long time = secure code ??
*ouch*
