### ISSUE TITLE
ShareX can't work with Bepasty due to lack of Content-Range header

### ISSUE THREAD

**Issue by Duckle29** [ShareX/ShareX#5522]
I'd really like to make a custom uploader that works with my bepasty instance, however bepasty is a bit odd in that it expects a binary file, but base64 encoded.

Additionally it requires the Content-Range header to be set.

I was wondering where I'd want to poke if I wanted to add the option of calculating Content-Range header, and adding an option to the binary upload for "base64 encode" 

[BePasty docs](https://bepasty-server.readthedocs.io/en/stable/rest.html#uploading-a-file)  
[BePasty CLI implementation](https://github.com/bepasty/bepasty-client-cli/blob/master/bepasty_cli/cli.py#L241)

**Comment by Jaex** [comment]
I on purpose did not add base64 support because you should upload data using minimum bandwidth as possible, not the opposite. So you should find proper hosting solution which not involves unnecessary bandwidth increases for no reason at all.

**Comment by ihyppolitec69** [comment]
How can I help

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
