### ISSUE TITLE
Image editor toolbar - With a small image the toolbar is not shown fully

### ISSUE THREAD

**Issue by stephen147** [ShareX/ShareX#5525]
Here's a screenshot of the issue.

It would be nice if the toolbar wasn't hidden when there's a small image or perhaps wrapped around to fit.

![image](https://user-images.githubusercontent.com/14054664/115160436-04ba8700-a090-11eb-9488-7ec8c2fe464f.png)

**Comment by ihyppolitec69** [comment]
How can I help

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: stephen147 ***@***.***>
Sent: Sunday, April 18, 2021 4:50:49 PM
To: ShareX/ShareX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShareX/ShareX] Image editor toolbar - With a small image the toolbar is not shown fully (#5525)


Here's a screenshot of the issue.

It would be nice if the toolbar wasn't hidden when there's a small image or perhaps wrapped around to fit.

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F14054664%2F115160436-04ba8700-a090-11eb-9488-7ec8c2fe464f.png&data=04%7C01%7C%7Cf4fa3cd6ee2a4ff0fbd108d902aba61b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543758507595742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3wgFNIAKZV1GpkdE7pZQEltViH%2BNUKBb3mkX9Ncw8wI%3D&reserved=0>

**Comment by stephen147** [comment]
Bumping this to unmark as stale.

**Comment by stephen147** [comment]
Bumping once again.
