### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by zahin45** [ShareX/ShareX#5527]
```
2021-04-19 19:32:42.766 - Task failed. Filename: ShareX_IsywIelAFx.png, Errors:
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://zar1f.cf/up.php?embed=yes&embedColor=%23fc0303&embedMDY=yes
Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

```
Help

**Comment by ausername-1** [comment]
The website you are probably trying to upload an image to probably doesn't have https enabled so to fix this you need to go to your custom uploaders and change the request url from https://<websitename>.<tld> to http://<websitename>.<tld>, However this is really a temporarily fix so you may need to contact the website owner to allow https.

**Comment by zahin45** [comment]
It is already http://

**Comment by zahin45** [comment]
> The website you are probably trying to upload an image to probably doesn't have https enabled so to fix this you need to go to your custom uploaders and change the request url from https://. to http://., However this is really a temporarily fix so you may need to contact the website owner to allow https.

its already http://

**Comment by ausername-1** [comment]
It says https:// in the error.

**Comment by zahin45** [comment]
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("e8e26ae8339000066f2b967cf1191143");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="https://lyrix.cf/up.php?embed=yes&embedColor=%23fc0303&embedMDY=yes&i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>

I remade it but new error
