### ISSUE TITLE
Upload  is okey, cilboard is not

### ISSUE THREAD

**Issue by zahin45** [ShareX/ShareX#5528]
Bacially, when i upload, it goes all good, execpet , the it copys this on my clip board
`<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("e8e26ae8339000066f2b967cf1191143");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="https://lyrix.cf/up.php?embed=yes&embedColor=%23fc0303&embedMDY=yes&i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>`

**Comment by Jaex** [comment]
This is to do with your host not ShareX.
