### ISSUE TITLE
Taks and Hotkey settings were reset after update

### ISSUE THREAD

**Issue by gxoptg** [ShareX/ShareX#553]
Hi,

I’m using ShareX portable. Today I’ve updated to version 9.8, and my task and hotkey settings were reset. Application settings haven’t changed. Is this the intended behavior or a bug?

**Comment by Jaex** [comment]
Default task settings and application settings in same file so it is not possible for one to reset but other not.

**Comment by gxoptg** [comment]
I see.

Well, it seems strange. If the issue repeats, I’ll tell you.






From: Jaex
Sent: ‎Thursday‎, ‎March‎ ‎12‎, ‎2015 ‎21‎:‎27
To: ShareX/ShareX
Cc: Ivan Akulov





Default task settings and application settings in same file so it is not possible for one to reset but other not.

**Comment by gxoptg** [comment]
I’ve found the reason. Instead of upgrading ShareX Portable, the upgrader has installed the copy of ShareX to Program Files. Therefore the updated version has launched with fresh settings from non-portable copy of the application, and I thought that the settings got reset.






From: Jaex
Sent: ‎Thursday‎, ‎March‎ ‎12‎, ‎2015 ‎21‎:‎35
To: ShareX/ShareX
Cc: Ivan Akulov





Closed #553.
