### ISSUE TITLE
bluetooth connection broken when region capture opens

### ISSUE THREAD

**Issue by dapal-003** [ShareX/ShareX#5530]
I've noticed that the Bluetooth connection with my phone gets interrupted whenever I activate the region capture from ShareX.

My phone is running android 11, when opening the region capture tool the Bluetooth signal drops instantly. As soon as the region capture is closed the connection recovers.

**Comment by Jaex** [comment]
How you guys keep coming with weirdest issues??

**Comment by dapal-003** [comment]
I don't know honestly, I noticed it since I started using Microsoft's "Your Phone" application to receive and make calls from my computer. And whenever ShareX was used my phone buzzed, it's nothing breaking but I did want to document it.

**Comment by dapal-003** [comment]
To add for others that might come across this: I've now also noticed that it's not only ShareX that does this, PowerToy's FancyZones also happens to cause this exact same issue. Speculation: So might be something related to drawing a full screen overlay?

**Comment by dapal-003** [comment]
Hey, I know this issue is marked as close but I found why ShareX was causing this issue to happen. 
The Bluetooth connections is interrupted because focus assist is turned on. By default focus assist is turned on when there is a full screen app. (Hence why PowerToy's FancyZone also triggered the exact same issue to occur)

So whenever the region capture of ShareX starts focus assist is quickly toggled to "Alarms only": https://cdn.astolfo.nl/Ryhc93.mp4 causing the Bluetooth signal to drop.

I assume that you where not able to replicate it because the setting of automatically toggling focus assist was turned off for you. So the solution was to turn off automatic focus assist for full screen applications.

**Comment by Jaex** [comment]
Nice to know.
