### ISSUE TITLE
Capture Issue or design?

### ISSUE THREAD

**Issue by bigbro6** [ShareX/ShareX#5532]
Hello,
I have what may be a "by design" issue but I have been unable to locate anything in the help / web about it being a feature / by design.
The short and sweet is, I have my "after action" for region capture set to open in the image editor, and then stop until I hit the continue task or close or whatever I want to do. 
My issue is, after taking about 5 region captures, they stop appearing ("spawning") in new windows. They are still being captured, but in order to display the next one, I have to close one of them. I would like to change this if possible, as sometimes I have a use to have more than 5 temporary images up on my screen and the image editor makes for a highly convenient, visible to the windows system and win10 thumbnail preview system, etc. Is there a value somewhere I can change to increase the number of allowed windows? My machine can definitely handle the resources required.
Thank you.

**Comment by Jaex** [comment]
Set this to 0:

![](https://jaex.getsharex.com/2021/04/ShareX_lr23L8VFKY.png)
