### ISSUE TITLE
Kutt URL Shortener not returning https:// links

### ISSUE THREAD

**Issue by EmilyLove26** [ShareX/ShareX#5535]
Whenever I take a screenshot and use the Kutt URL Shortener, it always returns http:// links, even when I tell it not to. I want it to return https:// links

![image](https://user-images.githubusercontent.com/7028351/115944415-99075e00-a483-11eb-9176-f6a4cfa37327.png)
(Mirror: http://photo.emilylove.app/Ck)

[UploadersConfig.json.txt](https://github.com/ShareX/ShareX/files/6368871/UploadersConfig.json.txt)

**Comment by Jaex** [comment]
https://github.com/thedevs-network/kutt/issues/67#issuecomment-665728094
