### ISSUE TITLE
does not make screenshot

### ISSUE THREAD

**Issue by modx-arseniy** [ShareX/ShareX#554]
installed program does not make screenshot. last update. saves files only if you select from the menu on the taskbar by clicking the mouse. when you press PrtSсr / Alt+PrtSсr nothing happens. 

sorry my English
windows 8.1, UAC enabled, installed in programs files

**Comment by MrLesh** [comment]
Hi,
Can you please be more specific:
 - what exactly are you trying to do?
- what are the steps you are doing in order to reproduce this issue?(i.e. what buttons are pressing in what order?)
- can you please provide more logs?

Thanks

**Comment by modx-arseniy** [comment]
Hi.  now it work well. i just installed clear W8.1.
i just tried to do screenshot by pressing PrtScr. worked in chrome + my
online mmo. as i do it usually. may be bugs of dirty windows. oem msi
windows is too dirty.

Thanks

2015-03-13 18:31 GMT+04:00 MrLesh <notifications@github.com>:

**Comment by modx-arseniy** [comment]
//program ignored the pressing PrtScr and other quick combinations

2015-03-14 0:58 GMT+04:00 Arseniy P <modxarseniy@gmail.com>:
