### ISSUE TITLE
No keybind for region selection 

### ISSUE THREAD

**Issue by smark91** [ShareX/ShareX#5541]
It will be very useful to have a keybind (customizable if possible) for the tools Rectangol region, Ellipse region, Freehand region

**Comment by khewweifeng** [comment]
You can do keybind in hotkey settings

![image](https://user-images.githubusercontent.com/54496743/116637929-c2e6e600-a997-11eb-9ef7-f47c3739bedc.png)

**Comment by smark91** [comment]
@khewweifeng please read better the request. I'm not asking how to set keybinds but to add the possibility to map Rectangol region, Ellipse region and Freehand region tools in the keybinds. Currently, I don't find any way to do it.

**Comment by wallybh** [comment]
I think the problem here is there is no keybind to the region select when I'm editing the capture. We can see it on the docs page https://getsharex.com/docs/region-capture#region-tools, there is no keybind to the 'Region tools' buttons. It's an issue for me too.

**Comment by Jaex** [comment]
It is tab key:

![](https://jaex.getsharex.com/2022/01/chrome_fe9EdAYOpl.png)
