### ISSUE TITLE
Capture region can't auto choose what window to capture anymore. 

### ISSUE THREAD

**Issue by ki13n0** [ShareX/ShareX#5545]
![Screenshot 2021-05-01 143206](https://user-images.githubusercontent.com/83491828/116774926-13d70700-aa8a-11eb-9774-e1f667270c59.png)

**Comment by DroidThug** [comment]
I have the same issue

**Comment by joshualyon** [comment]
Check if you have any apps that have an invisible overlay -- for example, it sounds like recent Nvidia Driver updates include an always-on transparent window that sites on top of everything else as [noted in this issue](https://github.com/ShareX/ShareX/issues/6147).
