### ISSUE TITLE
[Feature Request] Fake Pixelate/Blur Option for Better Security

### ISSUE THREAD

**Issue by timothymhuang** [ShareX/ShareX#5546]
ShareX provides a Pixelate/Blur option for screenshots, presumably for hiding sensitive data. However, software exists that can reveal the text that was obfuscated. So I suggest an option that will toggle a fake blur/pixelate option. It will make it look like something is being blurred/pixelated, but it is not the actual text that is being blurred, so there is no way that you can de-obfuscate the text since it didn't exist in the first place. However it should still look blurred/pixelated, otherwise, it would just look like the eraser.

**Comment by saltoo666** [comment]
or you know you could just use smart eraser and not add unnecessary features

**Comment by Jaex** [comment]
That's exactly why we added smart eraser feature. Otherwise you can just increase pixelate size option.

**Comment by yashpalgoyal1304** [comment]
ahh, so, this suggestion is about creating a pattern like thing. ohkayy.

**Comment by Korkman** [comment]
Just had the same thought. At least for pixelate it would be nice to have the option to randomize the pixel ordering after creation, thus destroying any useful information contained but keeping color tones. For blur, I have no idea how to implement it easily.

**Comment by saltoo666** [comment]
if you want a pixelated effect and don't want to use smart eraser that bad you could just increase the blur strength and pixel size to the point where it is impossible to see, you'll get nothing from like a pixel size of 30.
or you could just use the smart eraser and hide everything there is 
![14;31;52 chrome🍴](https://user-images.githubusercontent.com/81023284/155516357-e4e26fb6-fddf-470b-995a-b3a76997f8ab.png)
