### ISSUE TITLE
Image Editor > Crop does not update the working area

### ISSUE THREAD

**Issue by stdedos** [ShareX/ShareX#5558]
Start with:
![ExSTARTadulttriagesyst](https://user-images.githubusercontent.com/133706/117549304-50829f80-b042-11eb-81dc-ec33ff60d687.gif)

and then add the following portion (bottom/expand),
![image](https://user-images.githubusercontent.com/133706/117549298-3e086600-b042-11eb-8ce5-65f1f3e6beea.png)

to end up with this image:
![image](https://user-images.githubusercontent.com/133706/117549411-f0402d80-b042-11eb-8def-40f70e271b46.png)

Then, use crop, and try to remove the extraneous:
![image](https://user-images.githubusercontent.com/133706/117549443-12d24680-b043-11eb-97e5-5113fbeaaef7.png)

Expected:
![image](https://user-images.githubusercontent.com/133706/117549454-25e51680-b043-11eb-8a53-2c0fb8729d85.png)

Actual:
![image](https://user-images.githubusercontent.com/133706/117549327-7b6cf380-b042-11eb-9609-44542c155b42.png)

The saved result, however, is correct:
![ExSTARTadulttriagesyst](https://user-images.githubusercontent.com/133706/117549487-56c54b80-b043-11eb-8ee9-ff29425cda19.gif)

_PS: It's weirdly ... weird to take screenshots with the tool you are working with 😛_

**Comment by Elaws** [comment]
Problem still occurring.
