### ISSUE TITLE
"After Capture > Open in image editor" not working for gifs

### ISSUE THREAD

**Issue by rahlzel** [ShareX/ShareX#556]
It works fine for normal images - it opens up in Greenshot's image editor. However, when I capture a gif using the same settings, everything BUT opening it in Greenshot happens (save to clipboard, etc).

Since I don't want to immediately upload all images (I want to edit them first), I have to switch back and forth between enabling and disabling the "After Capture > Open in image editor" option.

My settings:
![my settings](http://i.imgur.com/vH4YNY5.png)

**Comment by Jaex** [comment]
I tried it and gif opened in image editor:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/03/ShareX_zEQ0uTjbbM.gif)

**Comment by rahlzel** [comment]
Since you seem adamant to close this, I recorded myself capturing a gif of a gif:

https://www.youtube.com/watch?v=IYsObGtq-lg

Note that the image editor does not appear, but the gif is still saved to the clipboard.

**Comment by Jaex** [comment]
Animated gif can't be edited obviously.

**Comment by rahlzel** [comment]
> I tried it and gif opened in image editor

> Animated gif can't be edited obviously.

![image](http://i.imgur.com/TPHAplo.jpg)

**Comment by xPaw** [comment]
@Jaex There either should be a separate "after capture" option for captured videos/gifs, or a separate confirmation window.

I currently have after capture set to "open in image editor" which works for images, and I can upload it from within that editor, but for videos, it does nothing, and I have to digging for the captured video to upload it.

**Comment by Jaex** [comment]
@xPaw is this can solve your problem?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/chrome_dBmeGCGGb7.png)

So your video or animated gif recordings will always upload.

**Comment by xPaw** [comment]
That only solves the problem if I use hotkeys, so no, not really.

**Comment by Jaex** [comment]
You can execute hotkey actions from "Workflows" menu so no need to use hotkey.

**Comment by xPaw** [comment]
Well that helps, but certainly is a hack.

**Comment by Jaex** [comment]
Having separate duplicate "after capture" option for captured videos/gifs in main window is not good idea either. Especially when people can request separate "after capture" menu for other things too. Current workflow system is designed to solve this situation.

**Comment by xPaw** [comment]
Does "Show before upload window" not work on videos too?

**Comment by Jaex** [comment]
It works in videos too? Even "Show after capture window" works in video.

**Comment by xPaw** [comment]
What is that option is supposed to do exactly? I tried it on pictures, and it does nothing there too.

**Comment by Jaex** [comment]
That means you don't have upload option is checked so ShareX automatically detects there is no need to select upload destination when there is no upload needed.

**Comment by xPaw** [comment]
Great user experience.
