### ISSUE TITLE
Cursor is drawn at the wrong position on capture.

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#5562]
I just noticed this.
Never got this before. Not sure if it happened after I upgraded to a never version.
I have this recording settings:
`-y -rtbufsize 1300M -f dshow -framerate 60  -i video="screen-capture-recorder":audio="virtual-audio-capturer" -an -vcodec libx264rgb -tune zerolatency -preset superfast -crf 0 "$output$.mkv"`

https://drive.google.com/file/d/1plX5DuuJkXtTKG7hv2pzV2DlLP44Si94/view?usp=sharing

PS: I still get the borked "<filename>.mp4.mkv" as output.

**Comment by mzso** [comment]
Some data I accidentally added to a duplicate post.
Like this attachment:
https://github.com/ShareX/ShareX/files/6447243/2021-05-09_11-36-11.mp4.zip

This issue was also labelled "duplicate", which is it the duplicate of? I want to follow it.

**Comment by Duckrinium** [comment]
Do you have DPI scaling set not to 100%? Settings > System > Display > Scaling

**Comment by mzso** [comment]
[**@Duckrinium**](https://github.com/Duckrinium) commented on [2021. máj. 9. 11:48 CEST](https://github.com/ShareX/ShareX/issues/5562#issuecomment-835768894 "2021-05-09T09:48:55Z - Replied by Github Reply Comments"):
> Do you have DPI scaling set not to 100%? Settings > System > Display > Scaling

Yes. 150%

**Comment by elamhut** [comment]
I have this problem as well on a 4k monitor with 150% scale

**Comment by elamhut** [comment]
I wanted to check on this because I think this issue is very serious and it's directly impacting my work :/
Any news if this issue is going to be fixed? Please

**Comment by Jaex** [comment]
There is no issue in ShareX, otherwise I would have fixed it. FFmpeg doing the recording not ShareX, so we don't have control on it.
