### ISSUE TITLE
ShareX creates white border around black border

### ISSUE THREAD

**Issue by CroxxFire** [ShareX/ShareX#5567]
Hello

I just went from Greenshot to ShareX as it can create a black border around my screenshots per default, which is awesome!

BUT, I noticed when I take a screenshot with ShareX and it creates my custom black border, it inserts a white border around that.
If I take a screenshot with Windows Snip & Sketch, it creates no white border.
I just took a screenshot of a grey image and pasted in on a red background to be able to see the difference.

Is this possible to remove in ShareX?
![Test](https://user-images.githubusercontent.com/84068343/117941377-51e5ed80-b30a-11eb-8c44-c720dce7f483.png)

**Comment by CroxxFire** [comment]
Found out I could add a crop effect in the Image Effects which crops the white (the cropping width is adjustable).
![Crop](https://user-images.githubusercontent.com/84068343/117944594-b6567c00-b30d-11eb-8604-603d90a1eaa4.png)

**Comment by Jaex** [comment]
Remove canvas effect.

**Comment by yashpalgoyal1304** [comment]
hi, more like question label??
