### ISSUE TITLE
Uploading high resolution images fails

### ISSUE THREAD

**Issue by lvh1** [ShareX/ShareX#557]
Uploading images which are bigger than 3840x1080 (10+ MB) fail to upload. Works perfectly fine for everything smaller or equal to that.

This is the error I get:

```
Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)
```
Happens with both imgur and chevereto as uploaders. Works with tinypic, haven't tried others.. 
ShareX version 9.8.

**Comment by Jaex** [comment]
Imgur have 10mb image limit. I don't think problem to do with ShareX.

**Comment by Nayncore** [comment]
Actually, the limit is 20MB https://help.imgur.com/hc/en-us/articles/201476437-What-is-the-maximum-file-size-for-uploads-

**Comment by Jaex** [comment]
Actually, the limit is 10MB http://api.imgur.com/endpoints/image
    image	required	A binary file, base64 data, or a URL for an image. (up to 10MB)

**Comment by lvh1** [comment]
Hmm, looks like they forgot to update their API I guess... That's why I got confused by the error message as it doesn't imply that the image is simply too big. 
Oh well thanks for your time.
