### ISSUE TITLE
Suggestion: make function that stretches screenshot to 1920x1080 if pc resolution is thinner

### ISSUE THREAD

**Issue by ratabomb** [ShareX/ShareX#5572]
strange suggestion :)
in some games its popular to use stretched resolution, and sometimes it is needed to capture picture stretched out (as example to show look of some games and locations with stretched resolution), but if you have stretched resolution, lets say 4:3, sharex captures screenshot with chosen resolution and final screenshot isnt stretched.

**Comment by DogancanYr** [comment]
Also, there should be an automatic stretch option on the desktop.
