### ISSUE TITLE
Unreadable settings window with dark theme

### ISSUE THREAD

**Issue by datlas122** [ShareX/ShareX#5574]
Windows 10 OS
ShareX version 13.4
Only in light themes settings have correct colors of text labels. In dark and dracula settings window looks like it is on screenshot. Is this known issue?
![изображение](https://user-images.githubusercontent.com/83924510/118529422-2ae54c80-b74c-11eb-8f3c-86ee51354779.png)

**Comment by Jaex** [comment]
Win forms don't have color option to change disable control colors.

**Comment by datlas122** [comment]
> 
> 
> Win forms don't have color option to change disabled control colors.

It is possible to use the checkbox autocheck property (false) instead of disabling the control and define colors manually. Maybe?

**Comment by lostzombie** [comment]
Maybe possible to use the checkbox autocheck property (false) instead of disabling the control and define colors manually
