### ISSUE TITLE
[bug]Some web text editors have no copy - paste uploaded images

### ISSUE THREAD

**Issue by zhupengfeivip** [ShareX/ShareX#5576]
# Problem description
In some text editors, such as GitHub, you cannot paste uploaded images when submitting issues.You must select copy to paste board in the edit screen.

# steps
![image](https://i.imgur.com/xvhUSnO.gif)
# configuration
![image](https://user-images.githubusercontent.com/30720809/118929212-cfe36d80-b976-11eb-828d-ec789943628b.png)

# expect
After setting the screenshot, the action is to copy to the clipboard. You can upload the screenshot directly to GitHub

**Comment by LongueBarcheNoir** [comment]
Hi,

I'm experiencing the same kind of issue on my side. After a search, it seems we are a few having the bug.
#5819
#5909 
#5923 

From my findings, the "copy image to clipboard (ctrl+shift+c)" in the editor works flawlessly, always (and with full transparency).

From the task list, 2 scenarios depending on the application Advanced settings named "**UseAlternativeClipboardCopyImage**" : 
When set to **_True_** : 
Doing a right-click on an image in the ShareX task list then selecting "copy image (alt+C)" will not work.
When set to **_False_** : 
Doing a right-click on an image in the ShareX task list then selecting "copy image (alt+C)" will work but no transparency will be retain, the background is filled with white.

I hope this can help. And thanks for the very neat software !

**Comment by LongueBarcheNoir** [comment]
While checking the difference of the clipboard copied item in "ditto", I found out the non working copy contains a "HTML format" in the "copy formats" properties. If I remove it, the item works correctly.
![image](https://user-images.githubusercontent.com/81383799/140304697-2c802cc7-0206-403f-9c83-a0c07f825f81.png)

When checking the properties of an item copied from the editor, this "HTML format" doesn't appears.

**Comment by zhupengfeivip** [comment]
I don't know where you opened the copy Properties window above, I looked for a long time, but could not find this setting.
And it doesn't seem to be a perfect solution

After I tested it again, I'm not sure if it has anything to do with it
When I selected the action after the screenshot to copy the image and file to the clipboard at the same time, I could not paste the image on Github, wordjack did not work, and the software like Dingding worked normally.
Github automatically pasted images when I only selected the screenshot action to copy the image to the clipboard. Nailing can,
Github doesn't work when I only select the action after screenshot to copy files to clipboard. Nailing will do.

All in all, Snipaste doesn't work for all of my scenarios, but it's not as rich as ShareX.

We look forward to a perfect solution to this problem.

yueque website:  https://www.yuque.com/

我不明白你上面的copy properties 窗口是在哪里打开的，我找了好久，都没有找到这个设置。
而且，似乎并不是一个很完美的解决方案哦

经过我再次的测试，不确定是不是和这个有关
当我同时选中 截图后动作下的将图像和文件复制到剪切板时，在github无法粘贴图像，语雀不行，在钉钉等软件可以正常。
当我只选中截图后动作下的将图像复制到剪切板时，github是可以自动粘贴图像的，语雀不行。钉钉可以，
当我只选中截图后动作下的将文件复制到剪切板时，github不行，语雀不行。钉钉可以。

总之，并不满足我所有的使用场景，而 Snipaste 就可以满足所有的场景，但Snipaste 功能没有sharex功能丰富。

很期待这一问题能够得到完美解决。

**Comment by zhupengfeivip** [comment]
I found the perfect solution
1. Do not open the image editor after setting the screenshot.
2, only set the screenshot paste image to the clipboard, cancel the paste file to the clipboard
3. If you want to edit the image, you can set the preview image left button to Edit the image

So far, it has satisfied my use requirements. Come on! sharex

我找到一个完美的解决办法
1、设置截图后不要打开图像编辑器，
2、只设置截图后粘贴图像到剪切板，取消粘贴文件到剪切板
3.如果想编辑图像，可以设置预览图像左键为编辑图像

至此，满足了我的使用需求。加油！sharex
