### ISSUE TITLE
Switch to MAUI

### ISSUE THREAD

**Issue by iMonZ** [ShareX/ShareX#5579]
Is it possible to think about switching to .NET Maui in the next years?
This would allow having Linux and MacOS support.
Also .NET 6 should have the missing features that have missed for supporting all PC platforms

**Comment by nanangp** [comment]
Unlikely, considering the tight integration with all the [Windows-specific APIs](https://github.com/ShareX/ShareX/blob/master/ShareX.HelpersLib/Native/NativeMethods.cs).

**Comment by iMonZ** [comment]
> Unlikely, considering the tight integration with all the [Windows-specific APIs](https://github.com/ShareX/ShareX/blob/master/ShareX.HelpersLib/Native/NativeMethods.cs).

The system library’s that you are using are available on other platforms too!
GTKsharp would be an alternative too!

**Comment by iMonZ** [comment]
unstale

**Comment by iMonZ** [comment]
Reopen Please
