### ISSUE TITLE
Uploading via FTP

### ISSUE THREAD

**Issue by utilitydog** [ShareX/ShareX#558]
Is there a way to have ShareX point to my folder that's in /var/www/.../temp/ as just typing in temp in the subfolder path in the FTP menu just leads it to my /user/temp. Or is there a way to have my website fetch from the /user/temp folder in /home

**Comment by Jaex** [comment]
Is problem that uploaded url not matches correct temp folder?

**Comment by utilitydog** [comment]
Yes, that is correct. Is there a way to fix this?

**Comment by Jaex** [comment]
I can't know what settings you configuring but nearly everytime this problem to do with wrong config.

**Comment by jbouwensgilson** [comment]
You could create a symbolic link, so that uploading to /user/temp links to a folder in /var/www/.../temp

**Comment by utilitydog** [comment]
Great! That fixed it, thanks
