### ISSUE TITLE
ShareX can't handle config files as symlink

### ISSUE THREAD

**Issue by edshamis** [ShareX/ShareX#5582]
I try to sync config files (ApplicationConfig.json, HotkeysConfig.json, UploadersConfig.json) across my computes by replacing them with symlinks. Instead of using symlinks, ShareX creates new files with .temp ending (ApplicationConfig.json.temp ...)

**Comment by fliespl** [comment]
I would also like to see it happening - allows keeping configs in sync between multiple machines.
