### ISSUE TITLE
Precise drag control with keyboard arrows

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ShareX/ShareX#5587]
I like it that initially, when selecting a region, I can use my keyboard arrow keys to move the mouse one pixel at a time. But once I made a selection, this feature is no longer active. I'd like, in addition, to have the arrow keys control when dragging an existing selection, i.e. holding the mouse button down when resizing or moving. Thanks.

**Comment by nanangp** [comment]
Some other apps allows pressing a key (e.g. space) to start a "hold mouse down" event. The user is then free to move the cursor around with either the mouse or keyboard as if performing a drag. The same keypress then "releases" the drag to perform a capture.
