### ISSUE TITLE
Add Gfycat login

### ISSUE THREAD

**Issue by Long-Horse** [ShareX/ShareX#559]
Please add the option to upload our gfycats to our own gfycat account as opposed to anonymously.

**Comment by Jaex** [comment]
Because they don't have API it would be difficult to do.

**Comment by joey5755** [comment]
Gfycat dev here.  
  
We will eventually add API functions for accounts, but probably not for several months.  The eventual functions will work via auth tokens (likely oauth2).  However, the functions are currently setup to work over ajax but require cookie based password authentication.

**Comment by danne2** [comment]
Thanks for the update Joey. It'll be nice once it's implemented into the site

**Comment by blaenk** [comment]
It looks like they have added a way of authenticating through their API:

* https://developers.gfycat.com/api/#authentication

**Comment by coty-crg** [comment]
+1
