### ISSUE TITLE
Strange tray menu location in multi monitor configuration.

### ISSUE THREAD

**Issue by joye-ramone** [ShareX/ShareX#5591]
When use two monitors and click on tray icon to get main app menu I got this:
![image](https://user-images.githubusercontent.com/5493488/119720640-e60b9500-be72-11eb-909a-8264c5f6ae68.png)
Right side (including taskbar) - Main monitor
Left side after read line - second monitor.
With such setup of monitors and task bar location - main menu appear at second monitor at the left of task bar.
But sub menus still appears at correct location

**Comment by DuckyCrayfish** [comment]
![image](https://user-images.githubusercontent.com/6509035/127943322-42308d97-f3d7-4197-bbb0-9c0bf2bf0f82.png)

This affects me as well. It's pretty confusing when I have my left monitor off.

**Comment by DuckyCrayfish** [comment]
Issue still stands

**Comment by owovin** [comment]
Same problem here, configuration gets even weirder dependent on your monitor's positioning in windows/GPU settings, for example i was able to get a normal looking one from positioning my monitor to not lap over more than a small corner ( https://i.murr.pro/7fxec9iq.png ), but if its more aligned to the monitor on the side, it'll cause the issue ( https://i.murr.pro/7cli60gc.png )

**Comment by Thespikedballofdoom** [comment]
Still happening
