### ISSUE TITLE
Do you support Linux

### ISSUE THREAD

**Issue by lexluthors** [ShareX/ShareX#5593]
Do you support Linux

**Comment by saltoo666** [comment]
no sharex doesn't support linux as it would need everyone to rewrite many years worth of code and learn something new so unless they feel comfortable with it or someone volunteers to write it no it won't work on linux

**Comment by nonetrix** [comment]
It seems to use Windows Forms heavily, so first it would have to be ported to something like QT, and that's probably just the beginning of what would be needed.

**Comment by inson1** [comment]
just use avalonia
