### ISSUE TITLE
Setting change for image preview, edit.

### ISSUE THREAD

**Issue by tx-trainwreck** [ShareX/ShareX#5596]
When I take a screenshot on Windows, an image appears in the lower right hand portion of my screen.  Prior to release 13.5,  if I left-clicked on that image it would open up in Edit mode.  now, it opens up using the standard Windows picture viewer where I can't edit the image.  Where is the setting to control the left-click action on the screenshot preview?  Thanks.

**Comment by Jaex** [comment]
Moved to here:

![](https://jaex.getsharex.com/2021/05/ShareX_bFq7xZg62d.png)
