### ISSUE TITLE
upload error (screenshot,vault.ooo)

### ISSUE THREAD

**Issue by BrickDown87** [ShareX/ShareX#5599]
I get this every second screenshot I upload, pls help/fix

System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei ShareX.UploadersLib.FileUploaders.Vault_ooo.Upload(Stream stream, String fileName)
   bei ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   bei ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.

Request URL:
https://vault.ooo/60d8e92d-b-eac0-9db5eb1cefedec3435baaf56b68f07696b0675e9d44b99a26424ea05a6c8084d025a944c81e3e05c?X-Get-Raw-File=1

Status code:
(500) Internal Server Error

Headers:
Connection: keep-alive
cf-request-id: 0a56692d4d00001f9004914000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=tRsCFWvHIG7Ps8VUbLfRj%2Bl%2Bbi3GIUykWtpT8b%2BRBgkCTX7RMlioMT%2F3a%2BOycDdoN1vyhSCUFH8tZGDP8lMEhJ%2BJPqgEtyRhem8i2YR44bQRiHKh81M%2F"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
CF-RAY: 656a77c21cce1f90-AMS
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
Content-Length: 217
Content-Type: application/json
Date: Fri, 28 May 2021 21:10:06 GMT
Server: cloudflare

Response text:
"HTTPError: Forbidden\n    at responseErrorThrower (worker.js:180:26)\n    at async GoogleDrive.createFolder (worker.js:2729:7)\n    at async onPost (worker.js:3118:5)\n    at async handleRequest (worker.js:3199:106)"

Stack trace:
   bei System.Net.HttpWebRequest.GetResponse()
   bei ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei ShareX.UploadersLib.FileUploaders.Vault_ooo.Upload(Stream stream, String fileName)
   bei ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   bei ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.

Request URL:
https://vault.ooo/60d8e92f-b-eac0-ed2117ed3bf41e0e2c1518c638aa66bc59d059bd4ccfedadde341c90d7f8688461ee75a7a69b8a91?X-Get-Raw-File=1

Status code:
(500) Internal Server Error

Headers:
Connection: keep-alive
cf-request-id: 0a5669324000001f900736f000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=zTLtMrYA5jSuOnisNjhRamGjgAKJr2M9rHYINTyHqE1iUKWeD3UIw77KSsUbg6ko3DQqtQqMCTw3kZsShfvwOP2NTYNjsnKpA8CpgFDUb2LjTZsZlEN%2F"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
CF-RAY: 656a77c9f8ad1f90-AMS
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
Content-Length: 217
Content-Type: application/json
Date: Fri, 28 May 2021 21:10:07 GMT
Server: cloudflare

Response text:
"HTTPError: Forbidden\n    at responseErrorThrower (worker.js:180:26)\n    at async GoogleDrive.createFolder (worker.js:2729:7)\n    at async onPost (worker.js:3118:5)\n    at async handleRequest (worker.js:3199:106)"

Stack trace:
   bei System.Net.HttpWebRequest.GetResponse()
   bei ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

**Comment by shjonas** [comment]
Hello, thanks for reporting the bug. Since the error no longer occurs without a change to the code, I assume that a quota limit was used up and this caused the error to occur. We had received more traffic through ShareX than planned. Now everything should work as usual again. I apologize for the inconvenience.
