### ISSUE TITLE
Too many requests [429] uploading to imgur.

### ISSUE THREAD

**Issue by RainyInKyoto** [ShareX/ShareX#5602]
For around a week now I haven't been able to upload any of my pictures to Imgur after taking them.
I didn't change any settings or do anything out of the ordinary.
I've looked around for solutions or if other people had the same issue, but only found instances of it happening when Imgur was down, and that's not the case this time.
I'm not entirely sure what's causing it.
Attached error message below.
Also checked previous threads/messages about this issue but also to no avail.
![ImgurSharexError](https://user-images.githubusercontent.com/84879112/120086574-34719b80-c0e0-11eb-9373-af731232c0e5.png)

**Comment by RainyInKyoto** [comment]
Quick note: Tried contacting Imgur and according to them it's not something caused from their side.
So now I'm even more confused than before.

**Comment by KyroOW** [comment]
I'm also having this, same error since WEEKS, i haven't been able to upload anything, never ever had this in years.
