### ISSUE TITLE
Can't find option "Show toast notification with preview" anymore with the latest update

### ISSUE THREAD

**Issue by Kyhze** [ShareX/ShareX#5603]
Prior to the 13.5 version there used to be the option under Task settings > General > After task is completed: Show toast notification with preview, but now I can't find it anymore.
I actually wish to disable the preview but keep the toast notification (text only), like it was before updating to this version. 
Where can I find the option to control this behavior now?

**Comment by nimnimnim** [comment]
Maybe this was *just* solved and ShareX updated today?
But I still had this same issue until this evening when I changed the shortcut for Capture Last Region from Shift+PrtScn to just PrtScn and now there is no Toast notification of each capture (as I've made sure to set in the settings)...
Now there was a pen icon in the right end of the name field of the action of Capture Last Region.
I didn't see how I had edited the action to change any of its default behavior so I just deleted it and created it again with my new hotkey just PrtScn...
And now there are no Toasts like there should (shouldn't) be!

Kyhze sorry to add a "replies: 1" or "replied to" status to your issue if this won't help you but in case you have the exact same reason for the problem maybe this was it for you too?

Love ShareX thanks!
