### ISSUE TITLE
viewing an image isn't displaying on top of the Application.

### ISSUE THREAD

**Issue by taiiat0** [ShareX/ShareX#5604]
i just noticed a few minutes ago that for some reason viewing an Image in ShareX isn't putting the view on top of the rest of the Application like normal.
i don't know when this happened, i'm pretty sure i was browsing my uploaded stuff fine even just a few days ago, and i don't know of anything happening since then.

i tried looking through all of the Settings but i didn't see an 'always on top' sort of setting related to viewing images.
_is something just wrong with me, or is it ShareX_?
one thing i have noticed is that opening the main window is automatically sorting it behind any other open Windows, instead of in front like would be normal.
ex. (_can see that viewing this image has shown behind the Application instead of in front_)
![ShareX_2021-05-30_23-16-52](https://user-images.githubusercontent.com/63434844/120135218-c5f31300-c19d-11eb-8236-eb92f7b0d0ee.png)

**Comment by taiiat0** [comment]
well.... today now it's working normally again. i guess it's just another freak occurrence in Windows, something only to be seen once or hardly ever. sorry for probably wasting your time.

**Comment by Yakov5776** [comment]
I can't seem to reproduce this, I think this is only happening to you (and if that's the case, you may Close the issue)
