### ISSUE TITLE
Idea: add date macros to google drive folder

### ISSUE THREAD

**Issue by f1h0** [ShareX/ShareX#5606]
Developers ask you to add the ability to automatically create a folder when uploading inside Google drive

![image](https://user-images.githubusercontent.com/1436880/120288540-01d6c700-c2c9-11eb-9f2b-a345f44df416.png)

This way when the file is loaded
It will fit in working folder and date folder
**"id_folder\\{date}01.06.2021\\"**
Desperately needed feature

**Comment by slingring** [comment]
Привет 

I dont think the issues section is for ideas?
correct me if im wrong.
