### ISSUE TITLE
customize tray menu

### ISSUE THREAD

**Issue by Klages** [ShareX/ShareX#5607]
the tray menu has a lot of entries, it would be nice to have an option to select which entries are displayed in this menu. with this option the user could only display the entries he really needs. in my case i would like to show only capture, tools and settings.
i think this would be a good quality of life improvement and also speed up workflows as one does not have to go trough a big menu of which most stuff is not needed.

![02 06 21_09-49-13_lyVnj](https://user-images.githubusercontent.com/3393617/120444807-483f2b00-c388-11eb-9828-0cec2f4b05d6.png)

this could be done with a simple setting in the application settings to select/deselect certain entries.

**Comment by Alaponuke** [comment]
yes please is ther any way to remove the destination options in the menu?
