### ISSUE TITLE
New authentication schemes in S3 (V4)

### ISSUE THREAD

**Issue by SimWhite** [ShareX/ShareX#561]
I'm trying to use new Frankfurt region with AWS uploads and getting following error:

<pre>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</pre>

As I know AWS4-HMAC-SHA256, also known as "V4," is one of new authentication schemes in S3. US-Standard and practically all other regions (but not all of them) also support the other, older scheme, V2.

According to http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html new S3 regions deployed after January 2014 will only support V4. Since Frankfurt region was introduced in late 2014 it apparently does not support V2.

**Comment by Jaex** [comment]
@alanedwardes can you check it?

**Comment by alanedwardes** [comment]
@Jaex Yeah this looks like something we need to do. I'll take a look at implementing at some point, hopefully the weekend (unless anyone else wants a go at it).

**Comment by alanedwardes** [comment]
Looking into this. It's actually a little trickier than it seems, we need to have access to the AWS region name to sign requests, right now we just have an arbitrary endpoint: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html

So this will require a UI change.

**Comment by alanedwardes** [comment]
Also worth noting, this will kill DreamObjects support, they do not support this form of authentication in their API: http://docs.dreamobjects.net/s3-api/authentication.html

**Comment by Jaex** [comment]
Is this region works #605 now or not?

**Comment by alanedwardes** [comment]
no

**Comment by Jaex** [comment]
Then why he added it, if it were not working.

**Comment by alanedwardes** [comment]
That might be a question for him :wink:

**Comment by Jaex** [comment]
@junderhill ?

**Comment by junderhill** [comment]
I didn't realise it only supported v4. Poor assumption on my part, apologies.
