### ISSUE TITLE
Week of Year - ISO 8601

### ISSUE THREAD

**Issue by MuffinName** [ShareX/ShareX#5610]
Currently when selecting the week of year for the naming scheme using `%wy`, the week is numbered using the convention used in America, where the week containing Jan 1st is week 1. Is it possible to also add the ISO 8601 convention of numbering weeks, where the week containing Jan 4th is counted as week 1?

**Comment by nanangp** [comment]
Should be pretty straightforward in .NET. [reference](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.isoweek)
