### ISSUE TITLE
Imgur upload failed: (417) Internal expectation failed

### ISSUE THREAD

**Issue by derekantrican** [ShareX/ShareX#5611]
Trying to upload a gif (gif created with "screen recording (GIF)"). Uploading a png works just fine.

```
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1247
X-Post-Rate-Limit-Reset: 3569
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Thu, 03 Jun 2021 22:22:36 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by Jaex** [comment]
Imgur API have 10 mb size limit for GIFs, otherwise giving that error.

**Comment by Jaex** [comment]
Proof:
![](https://jaex.getsharex.com/2021/06/chrome_uis24D2a0q.png)

**Comment by derekantrican** [comment]
Please provide a more helpful error message in this case rather than "internal expectation failed"

**Comment by Jaex** [comment]
Imgur provides it, not us. So you must tell Imgur to report proper error messages.

**Comment by derekantrican** [comment]
Sure, it's the Imgur API but Imgur doesn't control ShareX. You can catch that error and instead show a more helpful message. This isn't hard

**Comment by Jaex** [comment]
We don't know what is the real error. There is countless reasons that Imgur could return "Internal expectation failed" error. So it is not hard, it is impossible to show correct reason because we are not Imgur...

**Comment by Jaex** [comment]
For example in the past they returned "Internal expectation failed" if one persons country is banned or their account have issues, or many other reasons.
