### ISSUE TITLE
[Feature Request] Capture by coordinates

### ISSUE THREAD

**Issue by LAPIII** [ShareX/ShareX#5614]
I just want to screenshot certain areas of my screen based on precise coordinates.  The idea is similar `Capture > Region` and `Capture > Last region` except that the original area could be lost if a new one is drawn.

**Comment by Jaex** [comment]
It is already exists:

![](https://jaex.getsharex.com/2021/06/ShareX_FuzTjsh1W3.png)

**Comment by LAPIII** [comment]
I've selected the region. Now how do I to a screenshot using this?

**Comment by Jaex** [comment]
Create hotkey.
