### ISSUE TITLE
min size for editor window size

### ISSUE THREAD

**Issue by yxd0018** [ShareX/ShareX#5615]
Is there a min window size for the editor? It seems I can't minimize the editor window to a much smaller size.

**Comment by phazzzy** [comment]
Hey! I have the opposite problem, need to increase the minimum window size.

If I take a small screenshot when the automatic resizing of the window is turned on, then some of the useful buttons in the toolbar are hidden. This is inconvenient, I think it would be possible to increase the minimum width to prevent this behavior.

In addition to the fact that some buttons are hidden in the drop-down menu, the Border color and Tool options buttons have disappeared.

![image](https://user-images.githubusercontent.com/26648228/132978134-3055665a-7ffb-428b-bc93-6f2b49b55571.png)
