### ISSUE TITLE
Installation via SCCM shows error message "internal error: failed to expand shell folder constant 'userstartup'

### ISSUE THREAD

**Issue by Saxomania** [ShareX/ShareX#5625]
SCCM is installing via SYSTEM context on a device and SYSTEM has no user profile and some other default folders
you can verify it with running psexec.exe from MS (former sysinternals), run elevated cmd.exe, psexec.exe -s -i cmd.exe and run installer from this new cmd, during install process you will get this message. Installation works fine after clicking OK but not good to deploy it with this error message

adding /NORUN as parameter during install doesnt change this behaviour

<img width="154" alt="sharex" src="https://user-images.githubusercontent.com/11755505/121729514-de90f080-caee-11eb-899e-d9e4736e6e13.PNG">

**Comment by haavarstein** [comment]
/VERYSILENT /NOCLOSEAPPLICATIONS /NORESTARTAPPLICATIONS /NORESTART /SP- /SUPPRESSMSGBOXES

**Comment by Saxomania** [comment]
ok i will give it a try and report but may someone can solve the cause of the message as well

**Comment by Saxomania** [comment]
late reply :)

/VERYSILENT /NOCLOSEAPPLICATIONS /NORESTARTAPPLICATIONS /NORESTART /SP- /SUPPRESSMSGBOXES

worked

**Comment by liujingmao** [comment]
when I install Ollama,alse encounter this issue,so ....

**Comment by douchebanner** [comment]
> when I install Ollama,alse encounter this issue,so ....

same here
