### ISSUE TITLE
End action when file change.

### ISSUE THREAD

**Issue by user6323** [ShareX/ShareX#563]
Hello.
I suggest to add next feature:

![1426701381s](https://cloud.githubusercontent.com/assets/10479545/6715752/1093ff84-cdba-11e4-8eb3-64e1beb5c6e1.png)

Currently, sharex started upload or next action when application (what executed in action) was closed.
I suggest add option to end current action on first save of screenshot.

I suggest it because i have a problem: my favourite editor (screenpresso) stay in tray after it has been closed. ShareX waiting when it was closed. 
Also, if screenpreso running when sharex start execute actions, sharex not wait until editor and saves unedited screenshot (like skips editor action)

**Comment by Jaex** [comment]
Detecting file changes is not very reliable because many small changes can happen so I can't add it.
