### ISSUE TITLE
[Feature Request] Allow to use arrow keys in image previews when browsing through history

### ISSUE THREAD

**Issue by Yakov5776** [ShareX/ShareX#5630]
When you open the History Window in ShareX, you can use the Up & Down Arrow keys to browse through the images.

If you click on the image you can preview it in a full-size view, However you cannot use the Up & Down arrow keys to shift through the images while in this full-size view due to the listbox not being Active.

Allowing you to shift through the images with your arrow keys when in the full-size view would make going through images easier.

**Comment by sylvain-bougnoux** [comment]
+1.
But not only in history. I mean when opening the image to full size as well (single click on an image), then use left/right arrow key to navigate inside the current folder (and other?).
I guess up/down is less meaning full as it is related to the width of the history window, changing the number of images per row, hence the alignment. But it could be use to navigate faster and eg skip 5 images or so... Thanks
