### ISSUE TITLE
Prevent screenshot on mouse-btn release.

### ISSUE THREAD

**Issue by GoldenMaximo** [ShareX/ShareX#5633]
I want to select an area with a tool (e.g.: "Rectangle Region"), adjust the corners and then add/edit stuff inside said area with other tools (e.g.: "Freehand", "Line", "Text" etc).

**Behavior I'm experiencing:**
 When using the selection tools as soon as I release the left mouse button the screenshot is taken.

**Behavior I wish I could experience:**
 When using the selection tools as soon as I release the left mouse button NO screenshot is taken, allowing me to add/edit stuff inside the selected area.

**Comment by Jaex** [comment]
You can already do that if you enable multi region mode.

**Comment by GoldenMaximo** [comment]
Thanks @Jaex 

If anyone stumbles upon this issue the option is located @
![ShareX_O9uBGGFOr3](https://user-images.githubusercontent.com/51284438/121911626-4e2cf880-cd06-11eb-8f16-8ad30c3155b3.png)
