### ISSUE TITLE
Onedrive for business uploads from Sharex are failing

### ISSUE THREAD

**Issue by Mantas-Wren** [ShareX/ShareX#5634]
Sharex is failing to upload to Onedrive business account since beginning of May 2021.
**Error that comes up:**

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.OneDrive.CreateShareableLink(String id, OneDriveLinkType linkType)
   at ShareX.UploadersLib.FileUploaders.OneDrive.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://graph.microsoft.com/v1.0/me/drive/items/01LTXFAFPJN5MIRVUVUNAL6BBLH6DQB4LV/createLink

Status code:
(403) Forbidden

Headers:
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000
request-id: c02b82cd-504d-4557-8871-369b43fedf85
client-request-id: c02b82cd-504d-4557-8871-369b43fedf85
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"E","Ring":"4","ScaleUnit":"001","RoleInstance":"DU2PEPF00008886"}}
Cache-Control: no-cache
Content-Type: application/json
Date: Tue, 15 Jun 2021 09:13:00 GMT

Response text:
{"error":{"code":"notAllowed","message":"The feature has been disabled. Please contact your admin to get it enabled.","innerError":{"date":"2021-06-15T09:13:00","request-id":"c02b82cd-504d-4557-8871-369b43fedf85","client-request-id":"c02b82cd-504d-4557-8871-369b43fedf85"}}}

**Comment by Mantas-Wren** [comment]
@Jaex
Could this be looked into please?

**Comment by Jaex** [comment]
I don't have OneDrive business account, how am I supposed to look?

**Comment by Mantas-Wren** [comment]
I mean the error message. Is that something you came across before of has been reported by anyone else?

**Comment by Jaex** [comment]
I don't know why it says: `The feature has been disabled. Please contact your admin to get it enabled.`

**Comment by Mantas-Wren** [comment]
Ran it through admin and network teams. They aren't blocking anything.

**Comment by Mantas-Wren** [comment]
Waste of time ticket.
