### ISSUE TITLE
Google Photos Image Uploader error: The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by erbanku** [ShareX/ShareX#5637]
I use Google Photos under my personal Google account as my image uploader, but whenever I use ShareX to upload photos after restarting the system, it will prompt the **following error message**, which can only be successfully uploaded after refreshing authorization in Destination settings. Why does this happen? Is there any solution? Thanks.

error message:

**_The remote server returned an error: (401) Unauthorized._**

I am using Windows10 21H1, ShareX 13.5.0, and all security software are disabled, already gave access to ShareX start on boot permission.

**Comment by erbanku** [comment]
It’s strange that I’ve restarted the system a few times and found the problem by itself. I can’t reproduce this error. This problem has bothered me for a month before. now it is solved by itself.

**Comment by openFaster** [comment]
It's insane that the default behavior for taking screen shots is to upload images to a server. If these were going to our computers we wouldn't be having this issue!

**Comment by erbanku** [comment]
> I use Google Photos under my personal Google account as my image uploader, but whenever I use ShareX to upload photos after restarting the system, it will prompt the **following error message**, which can only be successfully uploaded after refreshing authorization in Destination settings. Why does this happen? Is there any solution? Thanks.
> 
> 
> 
> error message:
> 
> 
> 
> **_The remote server returned an error: (401) Unauthorized._**
> 
> 
> 
> I am using Windows10 21H1, ShareX 13.5.0, and all security software are disabled, already gave access to ShareX start on boot permission.



The problem reproduced to me again.This is the screen recording about it: https://photos.app.goo.gl/VCFRkXC3U67iFKBa8

**Comment by erbanku** [comment]
> It's insane that the default behavior for taking screen shots is to upload images to a server. If these were going to our computers we wouldn't be having this issue! 
> 
> 
> 
> My error message:
> 
> The remote server returned an error: (429) Too Many Requests.

 Yes,totally agree for me. But for some people maybe the method uploading to the server directly is more convenient as it doesn't need the synchronization applications.

**Comment by openFaster** [comment]
I have no problem with uploading as an **option** but as the default it is just insane.

**Comment by DasDunkel** [comment]
> 
> 
> I have no problem with uploading as an **option** but as the default it is just insane.

It isn't "default", you have to click OK on a popup that appears asking you if you want your screenshot uploaded after your first one:  https://dunk.dev/2qY6jq4q.png

Do not try to blame ShareX for a decision you made yourself, whether you read the popup or not.

**Comment by openFaster** [comment]
_whether you read the popup or not_
1) Slipping something like that in there on the first load is sketchy.
2) Not making it an obvious setting is worse.
3) I still don't know where it got a server address to upload to! I certainly didn't give it one. I wouldn't ever do that. I assume it's something else done on the first upload. This feels very much like all those spam emails that I've been "opted in" over the years, never having chosen to opt into anything myself.

**Comment by DasDunkel** [comment]
1. it specifically pops up as soon as you take the screenshot, you probably just hit "Yes" without reading, the popup is now being changed to stop people like you from complaining about your own actions: https://jaex.getsharex.com/2021/06/ShareX_4OMqF7ftL6.png
2. "After capture tasks" is obvious enough for most
3. it defaults to Imgur, the largest image sharing service out there, your screenshots are automatically uploaded as anonymous and can only be accessed if you have the URL, they won't show up anywhere else

**Comment by openFaster** [comment]
1. Yes, I probably did hit "Yes", or more likely enter. Once again: wrong default. "Yes" should require two steps. One to deliberately get to the point where you make that choice, and the second to finalize it. There is no valid reason for doing it on the first screenshot.
2. No, it is not. After capture implies image processing **after the capture**. In other words, the image had been placed on my computer and now we're going to do something like apply a filter to it.
3. This is not obvious. Also, security by obscurity is not security. What if someone takes a screenshot of their bank account information so they have a record for themselves. Should that be on the internet?

**Comment by DasDunkel** [comment]
1. That has been eliviated by the new popup, you are now required to wait 5 seconds so you can **read the popup before spamming enter**
2. "After capture tasks" means anything that needs done directly after the image is captured, like saving and uploading, not after it has been saved and is waiting next steps
3. Well if that someone themself selected "Yes" to have all screenshots uploaded and then took a screenshot of personal information, it is on them, but when they finally realise their mistake they can very easily go back into ShareX and `right click the image > Open > Deletion URL ` to then delete it from Imgur

**Comment by openFaster** [comment]
You are advocating for terrible user interface design.

**Comment by DasDunkel** [comment]
I would also like to add on to this by saying the amount of people that are actually having issues with this is minimal as most people will actually acknowledge a popup that appeared and read it properly before taking action upon it, instead of just hitting enter to get rid of it instantly.

**Comment by openFaster** [comment]
Most people rarely use screenshots of any kind. When they do use it, they're convinced immediately that anything that goes wrong is their problem because they don't know how to use it.

I'm using this to document my code changes, and if I did things in my code that you're advocating I'd be out of a job.

**Comment by CubityFirst** [comment]
>     1. Yes, I probably did hit "Yes", or more likely enter. Once again: wrong default. "Yes" should require two steps. One to deliberately get to the point where you make that choice, and the second to finalize it. There is no valid reason for doing it on the first screenshot.
> 
>     2. No, it is not. After capture implies image processing **after the capture**. In other words, the image had been placed on my computer and now we're going to do something like apply a filter to it.
> 
>     3. This is not obvious. Also, security by obscurity is not security. What if someone takes a screenshot of their bank account information so they have a record for themselves. Should that be on the internet?


1. You still confirmed it, and ShareX is much more proactive about it than most applications. This is also being changed in the future for users to be more aware for what they're confirming.

2. After Capture and After Upload, you'd assume that After Capture might have uploader settings.

3. Security through obscurity is not security, I'll agree with you on that one, but you have to recemember, that you've also confirmed that you want to upload it.

**Comment by openFaster** [comment]
I would assume that After Capture Settings would have settings, but After Capture tasks would NOT because settings are NOT TASKS!

**Comment by CubityFirst** [comment]
> 
> 
> Most people rarely use screenshots of any kind. When they do use it, they're convinced immediately that anything that goes wrong is their problem because they don't know how to use it.
> 
> I'm using this to document my code changes, and if I did things in my code that you're advocating I'd be out of a job.

Great that you don't work here then. Most of the users that use ShareX want to upload, so it's not insane that most people will want to upload. You have to remember, services like Gyazo etc DO NOT ASK YOU in the first place. ShareX actually goes out of it's way to make sure that you're doing what you want, and yet again, this is getting changed in the future to be even more obvious for people who click through prompts blindly.

**Comment by CubityFirst** [comment]
> 
> 
> I would assume that After Capture Settings would have settings, but After Capture tasks would NOT because settings are NOT TASKS!

After Capture tasks, are tasks, that are done, after the capture.

**Comment by erbanku** [comment]
> You are advocating for terrible user interface design.

Please don't say that,  ShareX extremely useful if you take your time for setting the preferences (and backup the settings file). This is an open-source software if you find something not good enough you can contribute it and make it better continuously, but please do not blame it for small issues.

**Comment by openFaster** [comment]
> > I would assume that After Capture Settings would have settings, but After Capture tasks would NOT because settings are NOT TASKS!
> 
> After Capture tasks, are tasks, that are done, after the capture.

Exactly, and after the capture the file should be where it is set to be stored. Moving from there is wrong. You're conflating settings and actions.

**Comment by CubityFirst** [comment]
It's there, and there's an option for more things to happen after the capture, which is accessible any time, and / or you're asked about it the very first time you take a screenshot.

In the future, there's going to be a big red important bar, clearer text to help make people understand what they're actually enabling, and a button lockout for 5 seconds so that you can't just click through it.

**Comment by DasDunkel** [comment]
After capture tasks is a step by step list of tasks that can be done as soon as you take a screenshot, you enable and disable them as you please, it is not "After save tasks"
