### ISSUE TITLE
History does not update

### ISSUE THREAD

**Issue by metalcupcake5** [ShareX/ShareX#5640]
The "Save tasks to history" setting is checked, however the app does not save non-uploaded screenshots to history
![image](https://user-images.githubusercontent.com/43897385/122360452-44281700-cf0b-11eb-93c3-ba5c20facf03.png)
![image](https://user-images.githubusercontent.com/43897385/122360938-a7b24480-cf0b-11eb-8596-e001d61815c3.png)

It seems to have started around 5/23 as that is when the history switches to file uploads only

**Comment by Jaex** [comment]
Uncheck this option:

![](https://jaex.getsharex.com/2021/06/ShareX_HfPfSqoyvH.png)
