### ISSUE TITLE
Windows multiuser installation

### ISSUE THREAD

**Issue by JustPieceOfMeat** [ShareX/ShareX#5642]
I have 2 accounts on PC: Administrator and simple user. I installed ShareX from simple user with admin rights and I got autorun and explorer integration only for administrator account:
![Administrator](https://user-images.githubusercontent.com/22642836/122640207-dea07a00-d106-11eb-8c66-9a322965e3eb.png) ![Simple user](https://user-images.githubusercontent.com/22642836/122640206-dba58980-d106-11eb-9753-b960a92bdb51.png)

**Comment by authorisation** [comment]
The registry entries are missing, reinstall.
