### ISSUE TITLE
How to delete captured cursor

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5647]
Can there be an option to delete the captured cursor in the screenshot editor? 

Asking as I know that it's not in the captured pixels, but rather a sharex object as it's not shown in sharex magnifier widget, and sharex objects were able to be sent under it as well.

**Comment by Jaex** [comment]
You can already delete it if you select "Select" or "Cursor" tool then you can hover cursor and delete it.

**Comment by yashpalgoyal1304** [comment]
Oh, i just selected the cursor tool (in editing toolbar) and the captured cursor was selectable, and draggable. I pressed delete and it was gone.

Niiiiiice. Clever implementation to have it not selectable in selection tool

**Comment by yashpalgoyal1304** [comment]
> delete it if you select "Select"

i couldnt select it using select though

**Comment by Jaex** [comment]
I tested now select tool works.

**Comment by yashpalgoyal1304** [comment]
i am on Sharex 13.4

but also, i find it kinda good that it's not selectable in select tool.

**Comment by yashpalgoyal1304** [comment]
oh, ohkayyyy. the select tool was not able to select the cursor as it was under the region object. ohkayy, got it now. when i deleted/moved the region away, it was doable. 👍
