### ISSUE TITLE
Does not seem to capture some games

### ISSUE THREAD

**Issue by ibigfire** [ShareX/ShareX#565]
When I use ShareX to capture the screen while playing many Steam games all it records is a blank white screen.

**Comment by Jaex** [comment]
ShareX needs directx or opengl capture which is very complex.

**Comment by Baegus** [comment]
Use OpenBroadcaster instead.

**Comment by ibigfire** [comment]
Well, I don't want to stream.  Just take screenshots and recordings.  There are workarounds and other programs, I have Fraps for example.  I just love ShareX more, especially with its ability to screenshot/record, upload, and copy url to clipboard all with one or two buttons.  I figured since Fraps could do it ShareX should be able to, not realizing it was a very complex issue.

**Comment by Soulflare3** [comment]
You can't screenshot in Fullscreen mode. If you would like, switch to Windowed or Borderless Windowed mode.

**Comment by Baegus** [comment]
OBS doesn't really have those features, but it can record videos to your hard drive just like FRAPS, it's not for streaming only.
