### ISSUE TITLE
Screen Recording does not respect record region

### ISSUE THREAD

**Issue by LeviSnoot** [ShareX/ShareX#5650]
As you can see from the screen recording below, I've set a screen capture region, however, ShareX records the whole screen anyway.

To reproduce:
Start a screen recording and select a region.

https://user-images.githubusercontent.com/13402525/122908360-51eafb80-d354-11eb-8c84-9da8ad95838a.mp4

Environment:

Windows 10 Pro version 21H1, build 19043.1055, Windows Feature Experience Pack 120.2212.2020.0
ShareX Microsoft Store Edition, version 13.5
Display resolution: 2560x1440
No. of monitors: 1

EDIT: Issue does _not_ reproduce on vanilla ShareX (the one downloaded from getsharex.com instead of Microsoft Store)

**Comment by Jaex** [comment]
That recorder devices you selected as video source gets region from registry and Microsoft Store not allows ShareX to edit registry therefore it can't set region. Use GDI grab video source.
