### ISSUE TITLE
Smart Eraser picking up the dimmed color

### ISSUE THREAD

**Issue by clllljjc** [ShareX/ShareX#5652]
I notice that the [Smart Eraser] picking up the dimmed color when [Dim background] is activated. As a workaround, deactivating the dimming solve the issue.

![image](https://user-images.githubusercontent.com/86313755/122960891-eaa16b80-d394-11eb-88f6-cf8420a4bdee.png)

**Comment by Jaex** [comment]
End result should not include dimmed color.
