### ISSUE TITLE
Offline OCR

### ISSUE THREAD

**Issue by mikamidd** [ShareX/ShareX#5656]
It's already been discussed [here](https://github.com/ShareX/ShareX/issues/4269), but since that issue "timed out" I'd like to make another thread in hopes of sparking more discussion on the topic.
Everything in the original issue remains valid, regarding tesseract and privacy concerns when it comes to online OCR.
The main concern with offline OCR is the application filesize, but I think not including any languages by default (tesseract) similar to how ffmpeg component works is the right approach here.
Obviously this isn't meant to replace current online OCR component, but it would be great to have an offline option available.

**Comment by Mahdi-Noor-Hasan** [comment]
There can be "Offline OCR" as an optional feature inside the installer to reduce file size for those who don't want it.

**Comment by hmnd** [comment]
Could pretty easily implement offline OCR for Windows 10+ using [Windows.Media.Ocr](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Ocr).

**Comment by Jaex** [comment]
> Could pretty easily implement offline OCR for Windows 10+ using [Windows.Media.Ocr](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Ocr). [TheJoeFin/Text-Grab](https://github.com/TheJoeFin/Text-Grab) uses that API for its OCR.

How it is pretty easy to implement?

> APIs in the Windows.Media.Ocr namespace are only supported for desktop apps with package identity. This means that the app is installed and run from an MSIX package.

Otherwise I would have used it.

**Comment by Jaex** [comment]
I found this article now: https://medium.com/dataseries/using-windows-10-built-in-ocr-with-c-b5ca8665a14e
So implementing like that right now.

But there is few disadvantages in that method:

1. Windows 10 or higher version only.
2. Language packs must be installed if you are planning to use OCR service for other languages.

**Comment by Jaex** [comment]
You can test it using dev builds: https://getsharex.com/docs/dev-builds
