### ISSUE TITLE
Imgur Upload Failed: (417) Internal Expectation Failed

### ISSUE THREAD

**Issue by omphvee** [ShareX/ShareX#5657]
Hello! I actually looked at an old error of the same kind and supposedly this happens when you attempt to upload a certain file type, gif, etc. I'm attempting a small size region image, not a gif. The issue has come very suddenly, as I was just uploading screenshots without problem 30 minutes ago. Any suggestions? I tried reinstalling (I'm terrible at troubleshooting but that seemed logical.) and to no avail. 

Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1239
X-Post-Rate-Limit-Reset: 2924
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Fri, 25 Jun 2021 22:41:33 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by HellmutLime17** [comment]
Same here with ShareX

**Comment by Jaex** [comment]
And what am I supposed to do if Imgur have internal isssue?

**Comment by SecretarySami** [comment]
Having the same issue currently

**Comment by truthsword** [comment]
This just started today for me. Another capture app I use clips to imgur without issue. Why the difference?

**Comment by westor7** [comment]
same here too

**Comment by omphvee** [comment]
> And what am I supposed to do if Imgur have internal isssue?

Your responses are always so like, passively rude and it's a little concerning. I'm not bitching and whining, I'm just sharing my logs and showing what is happening- and also sharing with the hopes that I am not the only one with this issue. It's comforting to know that all of these people are having the issue and indicates to me that it's probably a bigger issue at hand.

**Comment by omphvee** [comment]
> This just started today for me. Another capture app I use clips to imgur without issue. Why the difference?

No clue. The dev writes it off as an issue with imgur which is totally okay but I wish there were a bit more consideration from them. :')

**Comment by Jaex** [comment]
> Your responses are always so like, passively rude and it's a little concerning.

I'm just telling what's in my mind directly. Also it becomes frustrating to me that everytime Imgur API goes down people blaming me for it. And when I tell them there is issue in API, they don't even believe me. And this cycle repeats each time.

> I wish there were a bit more consideration from them. :')

I was considerate enough to reply very rapidly. What more consideration you want???

**Comment by omphvee** [comment]
> > Your responses are always so like, passively rude and it's a little concerning.
> 
> I'm just telling what's in my mind directly. Also it becomes frustrating to me that everytime Imgur API goes down people blaming me for it. And when I tell them there is issue in API, they don't even believe me. And this cycle repeats each time.
> 
> > I wish there were a bit more consideration from them. :')
> 
> I was considerate enough to reply very rapidly. What more consideration you want???

I don't know how me sharing a log and reporting a bug is considered blaming you for it? That's not at all what I'm doing. I don't know the first thing about coding, programming, etc. so I'm not by any means blaming you. I'm just sharing the experience that I'm having with the hopes of others also having the same experience and potentially a solution. There's been no blame thrown here. 

And you were considerate enough to reply rather quickly but it'd be nice to not be responded to with a rude attitude when I'm just trying to report a bug. <3

**Comment by Patchy319** [comment]
Same here, when trying to capture and upload to imgur

**Comment by solidsneak** [comment]
Nobody really blamed you for this error.. I don't think the guy who posted this or many other people realize it's not your fault because they failed to do basic research to determine this is not your fault (or the fault of the software). I was able to find a post from 2014 quite easily as well as looking up the information in my debug log to determine that this issue is not something that can be faulted towards ShareX.. the problem is the condescension and attitude.... 

yes he could have done some basic research and found out the answer, but the attitude is never going to be accepted by most users when they're simply reporting an issue..

**Comment by Duckrinium** [comment]
> I don't know how me sharing a log and reporting a bug is considered blaming you for it?

You opened the issue for ShareX because you thought ShareX is in question. When it's not. You didn't check if it was actually Imgur failing. Developer is frustrated because of it ShareX is not guilty, Imgur is to blame.
> I'm just sharing the experience that I'm having with the hopes of others also having the same experience and potentially a solution.

And since it's not ShareX's issue, there is no solution on ShareX's side.

You're not making his life harder, you just created issue for unrelated to ShareX issue, @omphvee. I hope you understand that I'm not trying to make you look bad, just telling why @Jaex might look rude to you, cause he's experiencing same question about third-party failures over and over. It's not restaurant's fault that there is no fish to serve.

**Comment by omphvee** [comment]
> Nobody really blamed you for this error.. I don't think the guy who posted this or many other people realize it's not your fault because they failed to do basic research to determine this is not your fault (or the fault of the software). I was able to find a post from 2014 quite easily as well as looking up the information in my debug log to determine that this issue is not something that can be faulted towards ShareX.. the problem is the condescension and attitude....
> 
> I'm no pro either but I know enough to know this isn't the fault of ShareX. Different people are in different stages in their knowledge of these things.
> 
> yes he could have done some basic research and found out the answer, but the attitude is never going to be accepted by most users when they're simply reporting an issue..

This. I don't really know a whole lot about this stuff, I just saw the option to report it and so I did it. :')

**Comment by omphvee** [comment]
> > I don't know how me sharing a log and reporting a bug is considered blaming you for it?
> 
> You opened the issue for ShareX because you thought ShareX is in question. When it's not. You didn't check if it was actually Imgur failing. Developer is frustrated because of it ShareX is not guilty, Imgur is to blame.
> 
> > I'm just sharing the experience that I'm having with the hopes of others also having the same experience and potentially a solution.
> 
> And since it's not ShareX's issue, there is no solution on ShareX's side.
> 
> You're not making his life harder, you just created issue for unrelated to ShareX issue, @omphvee. I hope you understand that I'm not trying to make you look bad, just telling why @Jaex might look rude to you, cause he's experiencing same question about third-party failures over and over. It's not restaurant's fault that there is no fish to serve.

I actually did do some looking and digging, and only found threads that reported this issue when uploading gifs or files with large sizes. I understand where you're coming from but this isn't my field of expertise and I every single thread I came across, the dev was pretty rude. I understand that there is some frustration to be had but it's just uncalled for in my opinion.

**Comment by omphvee** [comment]
I'll close the issue since it's not Sharex's end. :-) I was by no means trying to blame the developer or anything of that sort, just was given the option to report a bug and so I did! Best wishes.

**Comment by solidsneak** [comment]
> It's not restaurant's fault that there is no fish to serve.

Yet, it's the restaurant's responsibility to inform the user that their supplier didn't have fish available. The supplier doesn't interact with the user. Should the waitress walk up to you and be rude because you asked for the fish but they don't have it?

**Comment by Jaex** [comment]
> Nobody really blamed you for this error.. I don't think the guy who posted this

I did not tell that guy blaming me. I told "people" blaming me. From a lot of side people coming at me like Discord, email etc. So I told "people", I did not tell poster of this issue is blaming me.

**Comment by Duckrinium** [comment]
> 
> 
> I'll close the issue since it's not Sharex's end. :-) I was by no means trying to blame the developer or anything of that sort, just was given the option to report a bug and so I did! Best wishes.

no hard feelings please, we don't like Imgur being down as well, and it was unexpected, so it really stressing both dev and user sides. lot of love ❤️

**Comment by truthsword** [comment]
You can close the issue certainly, but my other screen grab uploader works fine with Imgur on an anonymous account. While this may be an imgur issue, it is not a universal imgur issue. It could be related to uploader robustness when imgur throws a curve. I'm no coder, so I speak at a macro level, if that. Peace, out.

**Comment by westor7** [comment]
What about having a FAQ about it? like when an API is broken or down, just write a good wiki and send that link when this happens again, so you won't have to explain each time the same things.. (just an idea)

**Comment by omphvee** [comment]
> > I'll close the issue since it's not Sharex's end. :-) I was by no means trying to blame the developer or anything of that sort, just was given the option to report a bug and so I did! Best wishes.
> 
> no hard feelings please, we don't like Imgur being down as well, and it was unexpected, so it really stressing both dev and user sides. lot of love ❤️

Nothing _but_ love! Hugely believe in just talking stuff like this out so there are no hard feelings at all! <3

**Comment by omphvee** [comment]
> You can close the issue certainly, but my other screen grab uploader works fine with Imgur on an anonymous account. While this may be an imgur issue, it is not a universal imgur issue. It could be related to uploader robustness when imgur throws a curve. I'm no coder, so I speak at a macro level, if that. Peace, out.

I was actually going to bring this up that it doesn't seem to be universally imgur's problem, but I also don't know much about coding/programming/etc. so I didn't want to fully overstep.

**Comment by omphvee** [comment]
> What about having a FAQ about it? like when an API is broken or down, just write a good wiki and send that link when this happens again, so you won't have to explain each time the same things.. (just an idea)

I think this is a really great idea! Since it appears to be a really common issue and obviously pretty frustrating for everyone involved, maybe write something out for this! <3 Good shout!

**Comment by Jaex** [comment]
> I don't know how to multiquote. :(

You can copy text manually then add "> " behind it which is quote syntax.

> like this

**Comment by omphvee** [comment]
> > I don't know how to multiquote. :(
> 
> You can copy text manually then add `>` behind it which is quote syntax.
> 
> > like this

Thank you so much! ♥

**Comment by Jaex** [comment]
By the way I sent support ticket using this link: https://help.imgur.com/hc/en-us/requests/new

So I'm waiting for their response.

**Comment by Jaex** [comment]
> This just started today for me. Another capture app I use clips to imgur without issue. Why the difference?

Now do you believe me? https://status.imgur.com/

![](https://jaex.getsharex.com/2021/06/chrome_g0IELArHQm.png)

**Comment by Jaex** [comment]
Got response to the ticket:

> At this time we are unfortunately experiencing a partial outage affecting upload across all mobile platforms (desktop is not affected), our team is working hard to resolve this issue and I will be happy to alert you once we have a fix pushed to resolve this.
>
> In the meantime, any updates we have will be shared on our status page first: https://status.imgur.com/

**Comment by Jaex** [comment]
Looks like they fixed the issue.

**Comment by Unknow0059** [comment]
I tried uploading a 187 kb jpg and got the error.
Uploading directing to imgur was no problem.
This is exceedingly annoying.

**Comment by ZnelArts** [comment]
Is there an update on this? I am still experiencing this issue.
Sharex 15.0
