### ISSUE TITLE
Can't select folder in OneDrive

### ISSUE THREAD

**Issue by szymski** [ShareX/ShareX#566]
I can't select folder in OneDrive settings. It's disabled (http://i.imgur.com/NDkHpbq.png).
I'd also like to have Upload path like in Dropbox setting, e.g. "Public/ShareX/%y/%mo".

**Comment by Jaex** [comment]
If not logged in to OneDrive then it will be disabled. Try re authenticating.
You can't use such folder path otherwise I would have used it because OneDrive works with folder IDs.
