### ISSUE TITLE
Question: When will be available on macOS?

### ISSUE THREAD

**Issue by wtrungvu** [ShareX/ShareX#5661]
I liked this.
I wonder when it will be available on macOS?

**Comment by Whanos** [comment]
Unlikely, as ShareX was programmed in C#, which does not run natively on MacOS. It might be possible if it was made with Xamarin or similar - It would be a herculean problem to fix though, as you'd need to re-write most of the code.

**Comment by ziaulrehman40** [comment]
so its a no :/
