### ISSUE TITLE
Hotkeys don't work when game window has focus

### ISSUE THREAD

**Issue by Bilge** [ShareX/ShareX#5662]
It seems some full 3D game windows capture key inputs before ShareX can process them. ShareX hotkeys should be registered globally so games or other applications cannot intercept or otherwise block the key inputs configured for capture.

**Comment by soupbowl** [comment]
Do you have an example of which games this happens on? I mostly game using steam and ShareX print screen always works for me.

**Comment by Bilge** [comment]
Black Desert

**Comment by Jaex** [comment]
Did you tried opening ShareX as admin?

**Comment by horusra** [comment]
I have the same issue when running some games (for example Doki Doki Literature Club Plus)
Tried running share-x as admin, but prntscrn still doesn't get to sharex.
Could there be a workaround using AHK maybe?

**Comment by horusra** [comment]
I have the same issue when running some games.
Tried running share-x as admin, but prntscrn still doesn't get to sharex.
Could there be a workaround using AHK maybe?
