### ISSUE TITLE
Thumbnails not showing for video recordings using ShareX

### ISSUE THREAD

**Issue by Adam-Kay** [ShareX/ShareX#5665]
For some reason, whenever I record video with ShareX, it does not display any thumbnail for the video, which can make them difficult to differentiate between if I don't go into File Explorer and find the file myself.
Is this an issue on my side or a problem with the program?

![ShareX_e5LPPpdD93](https://user-images.githubusercontent.com/10010491/123665454-35593280-d830-11eb-8365-ed959289eb3b.png)

**Comment by Jaex** [comment]
I couldn't figure out how to get video thumbnail as image to show inside ShareX.

**Comment by Adam-Kay** [comment]
Good to know, thank you for replying :)
