### ISSUE TITLE
Taking Window Screenshots on Windows 11 does not cut off rounded corners

### ISSUE THREAD

**Issue by ThomasAunvik** [ShareX/ShareX#5667]
Example Screenshot:
![image1](https://img.thaun.dev/jvkbg.png)
![image2](https://img.thaun.dev/plrc4.png)

Windows 11 Dev Build: 22000.51

Possible to make it transparent?

**Comment by Jaex** [comment]
Yes:

![](https://jaex.getsharex.com/2021/06/ShareX_sWgSdw4xlg.png)

**Comment by ThomasAunvik** [comment]
Does not seem to work for me.
![image](https://img.thaun.dev/vfi04.png)

Am i doing something wrong?

**Comment by ThomasAunvik** [comment]
Ah nvm, this seems to only work when using "Capture active window" and not "Capture Region" and selecting the window.

**Comment by Bluscream** [comment]
> Ah nvm, this seems to only work when using "Capture active window" and not "Capture Region" and selecting the window.

Is there a way to make it work with region?

**Comment by Void48** [comment]
> "Capture window with transparency" doesn't really produce transparent pixels, "Capture window with shadow" is required to create the illusion of transparency. ~I don't know if it's even possible to get a screenshot from Windows with an alpha channel.~
> 
> **EDIT**: Tried with a random Windows Graphic Capture API [demo](https://github.com/robmikh/Win32CaptureSample), it's possible to get a perfect semi-transparent rounded-cornered window snapshot from Windows
> 
> ![snapshot3](https://user-images.githubusercontent.com/1330321/138845889-a7ce6106-ce3c-4c7d-bd0b-42922311b9e4.png)
> 
> 300% zoom with colored background:
> 
> ![image](https://user-images.githubusercontent.com/1330321/138846180-4e55964b-6b72-49cd-874b-343acce11a19.png)
> 
> If I'm correct, WGC also automatically disables Acrylic/Mica effect on that window to protect privacy.

is there any way to capture a screenshot with transparency too?

**Comment by yume-chan** [comment]
> is there any way to capture a screenshot with transparency too?

What do you mean?

**Comment by arwebSE** [comment]
> 

I think they meant to ask if it's possible to capture a window with the acrylic effect on?
Also, I'm wondering the same thing =)

**Comment by Void48** [comment]
> > > is there any way to capture a screenshot with transparency too?
> > 
> > 
> > What do you mean?
> 
> I think they meant to ask if it's possible to capture a window with the acrylic effect on? Also, I'm wondering the same thing =)

let me know if you find some way to do it
