### ISSUE TITLE
can't resize emoji

### ISSUE THREAD

**Issue by bluelovers** [ShareX/ShareX#5670]
![image](https://user-images.githubusercontent.com/167966/123710761-de8c4100-d8a1-11eb-983c-ae91cda5401c.png)

**Comment by Jaex** [comment]
You can only change its size from sticker picker. Reason for this was performance concerns. Because drawing +100 dynamically resized sticker was slow.

**Comment by bluelovers** [comment]
ok..........

now ......... how change arrow line size ( not mean length )

![image](https://user-images.githubusercontent.com/167966/123722849-bb6e8b00-d8bb-11eb-88b2-cda1c48aa35e.png)
