### ISSUE TITLE
ShareX ffmpeg error, unable to record audio, console output appears

### ISSUE THREAD

**Issue by p2635** [ShareX/ShareX#5673]
I'm getting the same problem as the person who posted #2761, 

**Steps to reproduce**
I'm not sure what my specific configuration is that is leading to this issue, there are too many to report. Let me know if I need to provide any specifics more than this.

Windows 10 64 bit laptop
ShareX 13.5
Realtek Audio Driver 6.0.1.6122 (15/06/2017), I am advised not to update later than this because it says this is the latest my machine supports
ffmpeg v4.3.1 

Steps: 
1. For the setup, see the language learning video here https://www.youtube.com/watch?v=IS7WzYICAsk. To sum up step 1, set up a hotkey with a task to capture active window region for screen recording. Override the capture settings so it only captures audio coming from the computer.

Here is how mine looks:
![image](https://user-images.githubusercontent.com/4522927/123853653-9c9ce280-d915-11eb-9418-11ccc8c6ac99.png)

2. Press the hotkey to activate the task (F3 for me).

**Expected Results**
The usual ShareX timer appears to show that it is recording, I can press the hotkey to stop recording the computer audio. I know it works because I've tried this on a different machine.

**Actual Results**
I see the timer in the bottom left of the window but it stays stuck at 0, then this appears and nothing else happens. 
![image](https://user-images.githubusercontent.com/4522927/123853539-79723300-d915-11eb-8f80-8498e5c1431b.png)

If I try pressing Test with CMD in screen recording options, I get the same result except with `IAudioCaptureClient::setup failed` at the end.

**What I've tried**
1. Reinstalling ShareX
2. Repeating the 'Refresh' and 'Install recorder devices' buttons
3. Using a later version of ffmpeg

**Comment by femtoubik** [comment]
I have literally the same, issue

**Comment by DuaneMcD** [comment]
same issue here. first time using / fresh install.

**Comment by srgrneos** [comment]
Hi, Same issue here, do we have any update?

**Comment by eshopez** [comment]
it's the anti-virus that is blocking the voice recording. i quit my Kaspersky then no problem recording the screed with sound.
Need to add exclusions/exception to your anti-virus then you are done.

https://www.youtube.com/watch?v=yYtlRtz5AME

**Comment by p2635** [comment]
Thanks for going through the trouble of creating a video, that solution worked for me! @eshopez
