### ISSUE TITLE
Insufficient padding for screenshots with transparency on Windows 11

### ISSUE THREAD

**Issue by Sominemo** [ShareX/ShareX#5674]
ShareX has a capture with transparency option, which works for grabbing window screenshots on Windows 10 with shadow.

## Problem:
Windows 11 shadow is bigger, so it gets cut off halfway when capturing with transparency on Windows 11

## Steps:
1. Make sure window shadows are enabled
2. Enable capturing with transparency
3. Try capturing a window which is not full screen

## Expected result
ShareX captures the window and the whole its shadow

## Actual result
The shadow is being cut off cause of insufficient padding

## Screenshots
Actual shadow:
![image](https://user-images.githubusercontent.com/19842935/123891876-3db18a80-d962-11eb-8852-4516cfc834f5.png)

Captured shadow:
![image](https://user-images.githubusercontent.com/19842935/123891958-6043a380-d962-11eb-9e03-ccfcc5afd0cb.png)
As we see, the shadow is cut off at every side

It's hard for me to tell the precise size of the new shadow, so I made some approximations with a color picker, but I guess there should be a better way to know the actual size:
- Bottom: ~80px
- Left/Right: ~50px
- Top: ~35px

**Comment by Jaex** [comment]
I don't have Windows 11 so I can't test these stuffs, but as solution I will add configurable shadow margin size option I guess.

**Comment by Jaex** [comment]
Oh my god, now I check and I already added shadow margin setting long time ago:

![](https://jaex.getsharex.com/2021/06/ShareX_3ukc7jzcBR.png)

But because I did not use that option for long years, I forget the existence of that setting.
