### ISSUE TITLE
Freehand tool in image editor has some "border" around it

### ISSUE THREAD

**Issue by derekantrican** [ShareX/ShareX#5677]
"Painting" with the freehand tool is very obvious and leaves some weird outline. Maybe there is some weird border or misalignment thing going on?

See screenshot below where I used the freehand tool (with the color picked with the colorpicker/dropper) on a solid-color background and it came out quite ugly (using MS Paint, this would have been much less noticeable):

![image](https://user-images.githubusercontent.com/1558019/123995817-8ded1480-d983-11eb-8beb-82f56d53ad3a.png)

**Comment by derekantrican** [comment]
Here is the result when doing the exact same process (same image & same area) with the paintbrush in MS Paint:

![image](https://user-images.githubusercontent.com/1558019/123996417-2a171b80-d984-11eb-8f2f-57621ca506c3.png)

**Comment by Jaex** [comment]
I think you mean 1px drop shadow. You can disable it from shape options sub menu.

**Comment by derekantrican** [comment]
Ah, that's probably what's happening. Thanks
