### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 0x069** [ShareX/ShareX#5680]
L'analyse de la réponse a échoué.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   à Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   à ShareX.UploadersLib.CustomUploaderParser.ParseSyntaxJson(String syntaxJsonPath)
   à ShareX.UploadersLib.CustomUploaderParser.ParseSyntax(String syntax, Boolean isOutput)
   à ShareX.UploadersLib.CustomUploaderParser.Parse(String text, Boolean isOutput)
   à ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, ResponseInfo responseInfo, CustomUploaderInput input, Boolean isShortenedURL)
   à ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)

**Comment by Jaex** [comment]
Problem is to do with your host, not ShareX.
