### ISSUE TITLE
ShareX - Error

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5681]
### Steps:

1. ShareX > Image history
2. Open any deleted image - it has ![ShareX_1VsxlxlgLF] as thumbnail

[ShareX_1VsxlxlgLF]: https://user-images.githubusercontent.com/19423063/124358140-8dcb6e00-dc3c-11eb-8039-1b8d362727b7.png
[ShareX_nIcCmKKhiW]: https://user-images.githubusercontent.com/19423063/124358059-26152300-dc3c-11eb-9e75-e31f33f79fee.png

### Version:
- ShareX : 13.4
- Windows : 10 20H2

### Logs:

Image: [ShareX_nIcCmKKhiW]

```
extension cannot be null
Parameter name: extension
```
```
System.ArgumentException: extension cannot be null
Parameter name: extension
   at Manina.Windows.Forms.ImageListViewCacheShellInfo.GetCacheState(String extension)
   at Manina.Windows.Forms.ImageListViewItem.get_FileType()
   at Manina.Windows.Forms.ImageListViewItem.GetSubItemText(ColumnType type)
   at Manina.Windows.Forms.ImageListView.ImageListViewRenderer.DrawPane(Graphics g, ImageListViewItem item, Image image, Rectangle bounds)
   at Manina.Windows.Forms.ImageListView.ImageListViewRenderer.RenderPane(Graphics g)
   at Manina.Windows.Forms.ImageListView.ImageListViewRenderer.Render(Graphics graphics)
   at Manina.Windows.Forms.ImageListView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.4 (Release)
```

**Comment by lider33** [comment]
Ошибки при загрузке фото на сервера хранилищ:
Request URL:
https://api.flickr.com/services/rest?format=json&method=flickr.photos.getSizes&nojsoncallback=1&oauth_consumer_key=fbe042faa01e6af0371b6d87be75436a&oauth_nonce=2vtVLVwyYZea&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1625355054&oauth_token=72157719511839235-0604be80dddd1288&oauth_version=1.0&photo_id=51288025633&oauth_signature=eexEptBerES7dbbBVEomCy%2FEQtM%3D

Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
2021-07-04 07:31:05.078 - Exception:
System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: value
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.PhotosGetSizes(String photoid)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.Upload(Stream stream, String fileName)
   в ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   в ShareX.WorkerTask.DoUpload(Int32 retry)
2021-07-04 07:31:05.078 - Upload failed. Retrying upload.
2021-07-04 07:31:15.437 - ApplicationConfig save started: C:\Users\hohlo\Documents\ShareX\ApplicationConfig.json
2021-07-04 07:31:15.437 - UploadersConfig save started: C:\Users\hohlo\Documents\ShareX\UploadersConfig.json
2021-07-04 07:31:15.437 - HotkeysConfig save started: C:\Users\hohlo\Documents\ShareX\HotkeysConfig.json
2021-07-04 07:31:15.617 - UploadersConfig save successful: C:\Users\hohlo\Documents\ShareX\UploadersConfig.json
2021-07-04 07:31:15.647 - HotkeysConfig save successful: C:\Users\hohlo\Documents\ShareX\HotkeysConfig.json
2021-07-04 07:31:15.679 - ApplicationConfig save successful: C:\Users\hohlo\Documents\ShareX\ApplicationConfig.json
2021-07-04 07:31:18.152 - Error:
Error message:
Невозможно разрешить удаленное имя: 'api.flickr.com'

Request URL:
https://api.flickr.com/services/rest?format=json&method=flickr.photos.getSizes&nojsoncallback=1&oauth_consumer_key=fbe042faa01e6af0371b6d87be75436a&oauth_nonce=tC4DC8kOaovK&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1625355067&oauth_token=72157719511839235-0604be80dddd1288&oauth_version=1.0&photo_id=51288869030&oauth_signature=6%2Bn2JUYTYpjKcDgH2rAbG%2BvcWbw%3D

Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
2021-07-04 07:31:18.153 - Exception:
System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: value
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.PhotosGetSizes(String photoid)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.Upload(Stream stream, String fileName)
   в ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   в ShareX.WorkerTask.DoUpload(Int32 retry)
2021-07-04 07:31:18.153 - Task failed. Filename: t7omAcYCnP.jpg, Errors:
System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: value
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.PhotosGetSizes(String photoid)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.Upload(Stream stream, String fileName)
   в ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   в ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
Невозможно разрешить удаленное имя: 'api.flickr.com'

Request URL:
https://api.flickr.com/services/rest?format=json&method=flickr.photos.getSizes&nojsoncallback=1&oauth_consumer_key=fbe042faa01e6af0371b6d87be75436a&oauth_nonce=2vtVLVwyYZea&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1625355054&oauth_token=72157719511839235-0604be80dddd1288&oauth_version=1.0&photo_id=51288025633&oauth_signature=eexEptBerES7dbbBVEomCy%2FEQtM%3D

Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: value
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.PhotosGetSizes(String photoid)
   в ShareX.UploadersLib.ImageUploaders.FlickrUploader.Upload(Stream stream, String fileName)
   в ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   в ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
Невозможно разрешить удаленное имя: 'api.flickr.com'

Request URL:
https://api.flickr.com/services/rest?format=json&method=flickr.photos.getSizes&nojsoncallback=1&oauth_consumer_key=fbe042faa01e6af0371b6d87be75436a&oauth_nonce=tC4DC8kOaovK&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1625355067&oauth_token=72157719511839235-0604be80dddd1288&oauth_version=1.0&photo_id=51288869030&oauth_signature=6%2Bn2JUYTYpjKcDgH2rAbG%2BvcWbw%3D

Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
2021-07-04 07:31:52.344 - File opened: C:\Users\hohlo\Documents\ShareX\Logs\ShareX-Log-2021-06.txt

**Comment by Jaex** [comment]
I deleted file and opened image history, can't reproduce the issue.

**Comment by yashpalgoyal1304** [comment]
jaex - sharex version/build number? and what were u shown instead?

**Comment by Jaex** [comment]
It did not let me double click because it already know that file not exists.

**Comment by yashpalgoyal1304** [comment]
ohh, ohkay. wait, lemme check

yeah, so, that's strange. I am able to (single) click it :confused :  and also, via arrow navigation to a deleted file from non-deleted one.
