### ISSUE TITLE
ShareX history filters

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5682]
It would be nice to have video as a filter in the ShareX > History > Filters > Type

![ShareX_cLCKQpdlup](https://user-images.githubusercontent.com/19423063/124358435-e5b6a480-dc3d-11eb-9a04-95a519130012.png)

**Comment by Jaex** [comment]
Currently for example you can use `*.mp4` as filename filter.

**Comment by yashpalgoyal1304** [comment]
ohww i see. thanks :)

**Comment by yashpalgoyal1304** [comment]
this issue can be closed from my side
