### ISSUE TITLE
Possible to select OCR Engine 2?

### ISSUE THREAD

**Issue by willt** [ShareX/ShareX#5684]
I've just started using this tool and noticed it has a real hard time on numbers (depending on text) that and certain symbols like %. 

Would be nice to have this as an option to select if possible.
From ocr.space website:

Features of OCR Engine 2:
- Western Latin Character languages only (English, German, French,...)
- Language auto-detect. It does not matter what OCR language you select, as long as it uses Latin characters
- Usually better at single number OCR, single character OCR and alphanumeric OCR in general (e. g. SUDOKO, Dot Matrix OCR, MRZ OCR, Single digit OCR, Missing 1st letter after OCR, ... )
- Usually better at special characters OCR like @+-...
- Usually better with rotated text (Forum: Detect image spam)
- Image size limit 5000px width and 5000px height
- Parameter: OCREngine=2

**Comment by megamorphg** [comment]
This would be great because the current online OCR being used with ShareX is extremely inaccurate.
I'm not sure why but I don't see any settings to improve it but I always get the wrong results, missing lines and characters.
I use the same image (screenshotted) and then it works perfectly fine in another online OCR.

**Comment by Jaex** [comment]
Main reason why I did not add this before is because it would require two language lists per engine. But without adding two language list, quick solution could be automatically using Engine 2 for supported languages and Engine 1 for rest. That way no need any changes in UI side.

**Comment by Jaex** [comment]
I'm not happy with what I suggested too because I don't know which languages in our list should use engine 2.

**Comment by Jaex** [comment]
Currently it using OCR Engine 2 if language is selected as english. So english option gonna act like "auto detection for latin languages".
