### ISSUE TITLE
Does not record video at 60 FPS

### ISSUE THREAD

**Issue by suprunchuk** [ShareX/ShareX#5688]
I set the recording settings to 60 fps. but the program does not record at 60, it records at 30.

For comparison, I opened the OBS program and it records at 60 FPS
![image](https://user-images.githubusercontent.com/57152612/124616290-a1661700-de7e-11eb-8110-dc0854779551.png)

**Comment by Jaex** [comment]
Real time encoding is very costly, are you sure that your pc is able to encode 60 frames per seconds using cpu?

**Comment by suprunchuk** [comment]
> Real time encoding is very costly, are you sure that your pc is able to encode 60 frames per seconds using cpu?
why not?
I'm telling you, I used the program a few days ago https://obsproject.com/ and my PC supports 60 FPS via OBS, but your program does not..

**Comment by suprunchuk** [comment]
why not?
I'm telling you, I used the program a few days ago https://obsproject.com/ and my PC supports 60 FPS via OBS, but your program does not..

**Comment by suprunchuk** [comment]
what could have gone wrong?

**Comment by suprunchuk** [comment]
ok, if you don't believe me, I'll give you an example


https://user-images.githubusercontent.com/57152612/124621201-c066a800-de82-11eb-86ff-5706a0def08c.mp4



https://user-images.githubusercontent.com/57152612/124621197-bfce1180-de82-11eb-9d46-e6ecf7608fc0.mp4

**Comment by fastasfrick** [comment]
i have same problem too

**Comment by suprunchuk** [comment]
ok. delete ShareX

**Comment by Lustris** [comment]
ShareX uses FFmpeg to encode real-time.
OBS doesn't.
There's your answer.
If you want your 60fps then you're on your own to find the best FFmpeg arguments for your system.
