### ISSUE TITLE
Sharex Startup Auto Capture

### ISSUE THREAD

**Issue by rafomac** [ShareX/ShareX#569]
Hi Friends,

I really loved your application sharex, its really useful application for me.

can you please instruct me how to add Start Auto Capture to System startup ?

Now i assigned some hotkey, added sharex to startup but i can't add Start Auto Capturing to startup.

or i want to resume Auto capturing even if pc restarts too.

i'm eagerly waiting for your reply.

Thank you so much.
ABDUL RAFEEQUE
rafomac@rafomac.com

**Comment by Jaex** [comment]
You need to add -StartAutoCapture cli command to startup shortcut of ShareX. Which will start auto capture using last region.

**Comment by rafomac** [comment]
How to set auto capture Full Screen on Startup ?

**Comment by Jaex** [comment]
Do one time auto capture with full screen region. It will save that region. So -StartAutoCapture will do full screen region on startup when you add that command to startup shortcut.

**Comment by rafomac** [comment]
but it cannot capturing after reboot, how can we fix that ?

**Comment by rafomac** [comment]
reply me........?

**Comment by Jaex** [comment]
I don't know why it not capturing, it is supposed to capture.
