### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by orphicx** [ShareX/ShareX#5692]
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://confighub.host/upload?secret=ACzJ1l2VuGM0OkYLuIyH

Status code:
(403) Forbidden

Headers:
Transfer-Encoding: chunked
Connection: close
CF-Chl-Bypass: 1
Permissions-Policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
X-Frame-Options: SAMEORIGIN
cf-request-id: 0b275b42fc00004dc4fb92b000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=u1ZyTqcbJw0UgjuqjJFHxR7EkOA4yXTyN3hCrI%2BSd79H6bEMtkR6ecgJfqYLwLp8ZqB6lcran3e0fTf9651gq%2B7PQMpxSu8PIW8BkPV1IfXu9CIAfxsMjNF8FQ%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
CF-RAY: 66b8c7e4ccc74dc4-FRA
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html; charset=UTF-8
Date: Thu, 08 Jul 2021 10:55:32 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Server: cloudflare

Response text:
<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>

<title>Attention Required! | Cloudflare</title>

<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>

<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>

  
    <script type="text/javascript">
    //<![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "interactive",
        cNounce: "85011",
        cRay: "66b8c7e4ccc74dc4",
        cHash: "27f0b23c5d0cbd9",
        cFPWv: "b",
        cTTimeMs: "4000",
        cLt: "n",
        cRq: {
          ru: "aHR0cHM6Ly9jb25maWdodWIuaG9zdC91cGxvYWQ/c2VjcmV0PUFDekoxbDJWdUdNME9rWUx1SXlI",
          ra: "U2hhcmVYLzEzLjUuMA==",
          rm: "UE9TVA==",
          d: "BM8zL2pGu2fPqu0WXokCTcFs6GgvjANGxbYckhfV83hqgMWadY9u+jfLndXcQ/MOvWE4zkoFmDHybhnYLqjTHliWKYsiwOKUsmy/urRLB/Xa1VyexlO3//n+W/GaM3sPN6cRm7LJkrmgujeYyH/ZUcTW5iFqIXcrFGcVI7Mkpw/YvJoF1Y0UCLUWuASA/+tyR2yoRYe8JeXOsRauomzZNba/j2aD7oatKylaLuqGyo1jTqmsJ4ecoQUeUCgkLtPFnPIlJEDjXnR3QT8s24QHgPuAz8RqaR85hlOVK+WNyhswm7Q4YMplPZqqOiQV9D7pq+HfvjZaUZBKSnlEEkqe76how2HyU4rS3rAXfg3D9k+aaSCrhoYfaC0AdLKIa3EgrUPQRAWGTBKvqif6fgZtllisUkfSzs03M7KURTgmbI3FJSzQ4d/ha+t96c0gd+1sWXDSwfaVlGzKaTqxwPwZesK+RV8A/ifALJVn5SmvLfVAWwc145QROCoXZjdwAGsyiQi9dn92U6NbYf8nfxmzmaKvZokm0hD3d8AHx6IgPeZ1sJded/sktjh8z67gVuy81HVKyvkrCD4pSzbbRy1+CnaefbictzsQpFjBtk80cZWJ7kaJ+BHcPsiuLOGoVL+XevGGAe1Pt0h4nuuPf+kRh76vqc6OWfvcszcLuHwlod3QdKryDwpaFDBGKSa1BpA4LBUiIEZn5KJXJ6eS7dqBgFzKi+I2YHce+oDRyeCBosnVT56HMIC5N9pbpyMnimvr5lZ4l2Q6+zykAnsubZh3R4s6fMfat4ZPGUZdpCHrCWgz6xxDVCL0Spik7fTMu/ZSeau2dX8jPSNhNv1OkCOiNNPoKTSRP7Mc9C4O/JHGgBTV1gnDZewuyye4KpSNphAOBO53L973pTH4ClSbvUZY/Q==",
          t: "MTYyNTc0MTczMi42MTYwMDA=",
          m: "cWXVO44tb9VB7f4hm0dIZahUKclb4NimQu10B1NWv+o=",
          i1: "V3xtulGV//RsxmkKfEFVyA==",
          i2: "dJ2tQAHVmqCRFS/NKviiXg==",
          zh: "pYAauMUl5zAa0XlH7pjw2u0f3qHCxVXQ+E+8ifyASAM=",
          uh: "dPgyNDH0PSGb2hRCZjYfzPdpitmvzDS6Sc83c0yubGo=",
          hh: "Wx5nyy1TkuGWZnKBAlGUwfG/KJuiVeOu0rpWe/4RV9w=",
        }
      };
    }());
    //]]>
    </script>
  

<style type="text/css">
  #cf-wrapper #spinner {width:69px; margin:  auto;}
  #cf-wrapper #cf-please-wait{text-align:center}
  .attribution {margin-top: 32px;}
  .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
  #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
  #cf-hcaptcha-container { text-align:center;}
  #cf-hcaptcha-container iframe { display: inline-block;}
  @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-wrapper #cf-bubbles { width:69px; }
  @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
  #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
  #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
</style>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
      
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> confighub.host</h2>
      
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form interactive-form" id="challenge-form" action="/upload?secret=ACzJ1l2VuGM0OkYLuIyH&amp;__cf_chl_captcha_tk__=3bd134a403c88919a7be83015bc9c39d74ac3a12-1625741732-0-AajJrpKCHTGA0GAdrqsGGFy0JczEroXammuFlwp2cl9D7obUmRSmYTDGimtsc0Z5Qvnqevch7b78RQUv4htzukrIcb4aKeT79_76FRc5H_q-lM6jRT85_UFz7Qd0P5aGy0iGjkRwzphzU33eLtf4gmSn1IQfH9anGcC5JLVlVR2SjrAguCSCnZRKAq2DS0buHhDS5E4qsSv6L6MA9nVvxTUYNL5aKkV1uuLQqWkbNmi3ayM_YyRJ1SCkh_VtG1qB0h9sKai0hVa0o10NGf9Zy2LxKW0vDNYwwKnlMVeo3_UXFuYETSI3hgpyzdJP-4kHnDeQCGwPV5wyYY_z0oEE5MpJK_47eePBx0o0PvVXkzsQfZ_Dk9VPJnweh1jXCNV8ImVY7AkHRsXTDCZIRVXhUSYz5ls5c3Z1tQJ95xb1un74wT3Al508nqxUr_kaO27JMPuKuN1SG8nfIMOhqssgwGeAcRuWYMgwU6y2i4t5pmsqWFxyhyeZQuB1O5ydhNzmgZkrjBZSvu_zoQHEzflTns03d3OnMd8Jsg-sOlPCvx4Lsr-yTPYgBDGjeob3QUcd3N93222mnTDsvOLn8foURttRPUi0r9e2mdnSVC9YOR_-mKHNz3Y8rQMEJNON29Xtz9YT8CqjjJSZtyEGhx7z_L7JXHhvrek-9N8UpBIZptXah4NoG5wZDt-aK8wzlSXZUS5A9ypgICY4508FwfdA0Tg" method="POST" enctype="application/x-www-form-urlencoded">
  
    <div id='cf-please-wait'>
      <div id='spinner'>
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
      </div>
      <p data-translate="please_wait" id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p>
      <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
      </div>
  
  
  <input type="hidden" name="r" value="84980dff1b8bfea7138f40c0b7b39e1869d2e139-1625741732-0-AautmK0q5t/+EZFS0o66IIkrvZMvFhpYZ962lxR5Daj5XcD24jjBc93/X9GjPz286OjFenvXlT87QAOuZnmAhcW+IHL/RgYOQVzgit2yQNfuAlONj9BunV1b/J/PaEof0f9zX0R0WYELinETq1KN51GEx66Or+V9Fgg3p5J1dFHMOVovdWU4bo9Q+av0L6CUwCG8d3k5cVU4L3JaBB4WbFS+EOxPRvtplZ6T7BoA801W7xqctZthGG7DUY10Yb4VGyDG9akawzeROQDR3uzwwNfZqHDJqfcCPCt2thp8ifFCRNXPxRZoqBPzw7O/6tyOqiPrb9CQbTcJWqbgqKON4r9jz6Pv4FbJ+H9xGwAlNrbx+5bPq+uN2SdpUkkvSxYITn92BPNaygMRiml5aZ8lTfA/pRi8OtsczDqad64my8iNtVrmyNn+/zvPslDIcBUCLj70D2pUzhA9CsVjoOvSYSMH9cjXSo8fUVAVQcpUlMoKw06BU7jkzJt6zPZwXnwiBZnVa7lWZFEbFYAE2F+iSC8IvUwmDZZXNkm0QSIWGqoYSokT+pwUMMlw8RiSPqXbGIo3M+naWaX2aEtzpr2doPJzV+pEkM3H7fU/+JsDjp2rGtB/78HL5uwRIzkC7bNQasYsY8IEiplWG/oNljdrxW0YUSgDxwCOyc8gk7bKFz/dFsMBH80vtifn5PO+Z7F8tCYoahDhKAapXfqmlf08v8RuR/WJVKpeeY0+FFAcgu5jbqFolExKn79zgMW1RU02KGbk+NFsh6xVL04FWSO/RvAO/427gvjgPnqRC7RdpMX9i9jr7COWgwA4WSGJLUC4b8crdJ6oIWjltkcy/GWsfTtEHcNPpQ9BT8/eK/QYYIEoiHd1qm+Awkit1T17+F2GsTV8HM8LQsysATuy1BOZZNn8VeVnGe2R/91EBkVfsXGT9GOmWmftM7FC6O4fvJYUaBgz+7maPCBOJ1Oq/eywvk5Y7XfACyEubl+Uik+RPhlbOvQErlQFyvMRFa0DU5sBhUln7JIy0dR3dRHz/TvzAomugg/KJTBaG8mFjAeJJL9Z0Bs+YqSfpaE0WEUFQ2wcG6PNETv91cbHDjkB1YZHuoPlPYVgTUVJqITAjOnTKROmiX5lA2V0TSaRDavgnf6WmVkQp4AEVEc/x/lmmFqD9ME8VLpmnYK0YKKDma++6ZhsS6VRbcbSxtYLHlPsibCsSqhYnLDswhwzeagDjqhDaFE+VC5NHlYx+Z3DWTjGbf2DIsVN3IXoN0o5nM8qwLBTEl5mtPgCkrsAsGPsvXtnAVhOAxsOTjenPlX39j8iwemFcttpkjD2UM1SfpOfmuZQz3ygkI9+7SMlXlLUs+IMao+3Au0A6Wb4HlPtD/LoV6Sij363bxUHo8NYvs6K8G4WKU995yyf8olWv/Z1lpiXNx1dpgcMiMcuPfo1wKnYEZ4sfHDA0EYKzCR92O73bWPOLKyIVVD1+K8mpBv+Uonzo4XgNoQZVtH+kLMW5et/mEZk7r2gZ/76/8AUJp7QYBbGwKdBsEiaClPvZoRF7gFmtyclgqipaGDs+F49sNFoc4kVNmLHzrnDKDZIkDDCzhQC9XboMzwKJSI+iM7EuIrT5nn/x7Q+AdGcccd5KYiHZ52AYWYwWRDSNpI4FlCJpDq/Gm4NVPfqKE0z1pRq20nq9qZddyTQ9VfomlV1Phcp3K5rUjYVecVXzxAvbgpAw4rveoT2YX09kxt1/USdouYD9WW6Rttt/Z/u2L2HiLfDpOqRL0mYxL0W+DQoAtX0cfeKscfzPhzYli0PPF9z9MpXcVFzuArwKP78xy9pB8S4SBm7YXIrjLZyPVlMeOhAXvJvO3LKyqmxlaBwsE/tYo8WhbWxfNYeLQhOmxMTr4sqL2w6loXitZlcjkE4pv4hqk7X6xrLjfp52RIFtRYlnblB9bOO1CfZSEymKVpYByZmOk+zPkGY6E4O6iq6AzzhiHPTn2WycBLG+CLLu3qt1C22jRuQndXbQNpf2/czTFiCzIQDs2IMJdhD/qeypUbBe1bWFYyDECRgM2KQKfZiZgCbx+K6wNfWiWaBymhcKaGlEg2W1+Uda0VFWHoY3ikDUFC8ZLuqYZZYNgQRAlO+874dAmtBy0uOw3KWloXC+YQ6p0jfOvJ7bPrgQXAW7q1nbd3lRPOvaaam0xEiszg7BKmi+lxOXCo/AWSH6CZjYWUR3R74WNnj1A9s469v6hsjBeMRmwHzO5RFUFbA+tvotAEs3qAUMtD4v/Vv+KBuSOL7RItAjNP4dqu7ae1l3dJw4bCnZKFQrmDbm87hX6pgz3A1LYJ68yun/c/RY5tI11FxbYSpZrdRWSOVmO3HIEkag0SZtmmiFC4KOBbfxh1+zRhMh2Os0Wgd8jlDMvhqxsYl1gpU9zU8ardKiqXpkY2xG5I/YtzRtczzpPOjvpMHWsbdBu4vWWpy7s9p82diLVxEImCZ7+kFvdM6MC03CyHbwdmGQ7jlFp/qifWikGV3U0/fZPthSPtt7+jXCycAWTvQ0Ygl1zPIl62la+w90HIOUMNdvBctkzt6yqXaQnMW48qJJM++O5X79fN2BCL4LHuIdoupPeqg6AhQxE1DjwVQTZ3HA3tj4MwRaID4emYHvSlrBattxiIeotm0B6+BHouZryB2Ugpi+4/RObpeFZY53XcvDpo7DuTsxqhqZIZdZZxmxrvia8WIwjJ1qS4r98uGSghsRj49ujDiMZqDj50I+WTo0VrKSjtYz/SbmMt7wf6ObrFnG8DNAfkSUZ3ARga7d5IjjE5PtmRPhkGCNjt+9xqdXEX5ce74ZPUVN0DRjkNmr87KiroR76JXqmeXZomGVboIsTSKXktK5DBu4D7MAlbLXQ==">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <input type="hidden" name="vc" value="2eca62ba2994feb4082ee38f881482ba">
  
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
  <script type="text/javascript">
  //<![CDATA[
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
      b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
      b(function(){
        var cookiesEnabled=(navigator.cookieEnabled)? true : false;
        if(!cookiesEnabled){
          var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
        }
      });
  //]]>
  </script>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=66b8c7e4ccc74dc4')"></div>
</form>
  
  <script type="text/javascript">
    //<![CDATA[
    (function(){
        var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
        var trkjs = isIE ? new Image() : document.createElement('img');
        trkjs.setAttribute("src", "/cdn-cgi/images/trace/captcha/js/transparent.gif?ray=66b8c7e4ccc74dc4");
        trkjs.id = "trk_captcha_js";
        trkjs.setAttribute("alt", "");
        document.body.appendChild(trkjs);
        var cpo=document.createElement('script');
        cpo.type='text/javascript';
        cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/captcha/v1?ray=66b8c7e4ccc74dc4";
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
    //]]>
    </script>
  

              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
              
            
          </div>
        </div>
      </div>
      

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">66b8c7e4ccc74dc4</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 82.210.186.152</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>

    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

**Comment by Jaex** [comment]
It is not to do with ShareX.
