### ISSUE TITLE
Nextcloud Upload Broken

### ISSUE THREAD

**Issue by TimyStream** [ShareX/ShareX#5695]
Hey,

Nextcloud seems to changed the Webdav URL in the newest update and ShareX on version 13.5 is still trying to upload to the Old URL.

The old URL had "webdav" in it and the new one only "dav" and not "webdav".

I hope i could help with this issue.

**Comment by TimyStream** [comment]
I closed this because it was my own fault. Me did something in the Configuration of ShareX and Nextcloud wrong :) Sry Guys

**Comment by jeifour** [comment]
> I closed this because it was my own fault. Me did something in the Configuration of ShareX and Nextcloud wrong :) Sry Guys

Could you share how you fixed it?
