### ISSUE TITLE
Won't capture new screen with unfinished edits.

### ISSUE THREAD

**Issue by snakyjake1** [ShareX/ShareX#5699]
When I take a screenshot, ShareX won't capture the screen nor show the Image Editor

Debug Log:
2021-07-12 10:25:01.501 - Executing: Capture region
2021-07-12 10:25:05.875 - Task in queue. Job: Job, Type: Image, Host: 

While trying to troubleshoot, it is my guess this might happen when I have another Image Editor open, and doing an unfinished "task" (I can see the editing "dots" in the editor).  Therefore the new screenshot/capture is queued.

For the user, it is not obvious there's an unfinished task that's blocked a new screen capture.

Expectations:

A new screenshot/capture "task" should still take a screenshot independently of other Image Editing tasks.

**Comment by Jaex** [comment]
Set this to 0 to have unlimited tasks:

![](https://jaex.getsharex.com/2021/07/ShareX_s9D603YMxP.png)
