### ISSUE TITLE
Screen Recorder has a 1-2 second delay after hitting Start

### ISSUE THREAD

**Issue by FrankJunk** [ShareX/ShareX#5713]
I changed the options so I would have the ability to start a GIF recording when I wanted, instead of it starting the second the region is selected. I unchecked the "Start Recording After", however once I press start there is a startup time of 1-2 seconds, causing me to mistime whatever i'm recording. Here are my options for reference:

![image](https://user-images.githubusercontent.com/55088742/126827341-6a67c0ae-cae7-41fd-ba52-0373e8eec2c5.png)

![image](https://user-images.githubusercontent.com/55088742/126827392-54aec401-ae5f-4d46-b3c6-b73b0cbb226c.png)

The command line text is:

-rtbufsize 150M -f dshow -framerate $fps$ -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:v h264_nvenc -r $fps$ -preset slow -b:v 3500k -vf "scale='iw*min(1,sqrt(1024*576/iw/ih))':'ih*min(1,sqrt(1024*576/iw/ih))':in_range=full:out_range=full:in_color_matrix=bt709:out_color_matrix=bt709" -sws_flags lanczos -profile:v high444p -pix_fmt yuvj444p -color_range 2 -c:a aac -ac 2 -b:a 128k -y "$output$"

Any idea? Possibly messed something in the command line but it runs with no errors. The issue occurs running with my custom command line and the default one

Thanks in advance

**Comment by DAOWAce** [comment]
Has been happening to me for years, on and off, even with a countdown.   One record it starts instantly, another record it just sits there after hitting 0 for a couple seconds.

No idea what causes it, just been a quirk of the program.

**Comment by eabase** [comment]
Windows like to suck up all the processing power for it's own purposes. I suggest to try to find a way to temporarily increase the process priority when starting recording.
