### ISSUE TITLE
webp picture or file?

### ISSUE THREAD

**Issue by g0blin-NN** [ShareX/ShareX#5719]
[imageban.ru ](https://imageban.ru/) supports webp. but ShareX stubbornly treats webp files as files. not like a picture.
there is a file [imageban.ru.sxcu](https://github.com/ShareX/CustomUploaders/pull/361/commits/e970b8e073a03531e9b1adc6c38d9893da4c39a3)
Or am I doing something wrong?

**Comment by Jaex** [comment]
You can add webp to list here:

![](https://jaex.getsharex.com/2021/07/ShareX_PxeuBfmHcx.png)

**Comment by g0blin-NN** [comment]
thanks. how else to make the program make references previews with clique magnification. 
`[URL=https://imageban.ru/show/2021/07/27/55f4085edf0886eac09e93fb9c72219d/webp][IMG]https://i6.imageban.ru/thumbs/2021.07.27/55f4085edf0886eac09e93fb9c72219d.webp[/IMG][/URL]`
