### ISSUE TITLE
JPEG Quality overwrite

### ISSUE THREAD

**Issue by djprmf** [ShareX/ShareX#572]
Hello,

First of all, congrats for the fantastic Sharex. I use it since the "old" Zscreen :)

Now, about the issue, i think i have found a little problem with the JPEG quality setting, when using in combination with the clipboard upload (and i think that also in any other way when using ShareX).
This setting overwrite the quality of the main image, but happends at any time, even if the main image have a lower quality number that the used in the Settings of ShareX.

For instance, let say that i have the "JPEG quality" in the 90%, and i have a clipboard image with 60% of quality. 
Becouse of the ShareX setting, the image will be processed with 90%, creating a bigger file and with no improve of the original image quality. If the original image is already in 60%, the increase to 90% will not create more quality on the image, but will increase the file zise (sometimes for many KB or even MB)...

This could lead to the creation of files with a big final size without the need of that.

I think that should be implemented a setting to allow the user to:
- Chose to disable the overwrite in the JPEG Quality by ShareX, maintaining the original image quality
OR
- Allow the user to select a option in what ShareX will bypass the change on the JPEG quality if that setting number is higger that the original image quality (a little more complicated to implement from your end, i think, as involve more checks from ShareX)

I think one of the above solutions could fix this problems and avoid the creation of files with big sizes (important even more for webmasters, as will have impact on the website load time/size).

Hope to see this implemented in the future. :+1: 
Thanks

**Comment by Jaex** [comment]
While uploading image, processing is already optional it will just upload your jpeg file not re encode it. And mainly clipboard won't contain jpeg data. So I don't understand your problem.

**Comment by djprmf** [comment]
Hello,

I think you didn't understand. Lets assume that i have the ShareX setting in the 100% of JPEG quality.
And let say that i have this original image: http://i.imgur.com/v2mhfXK.jpg
That file is encoded with a original quality of 80% and have 646KB.

Now, if i use the clipboard upload to host that image, i get this:
http://files.tugatech.com.pt/imagens/topicos/tugatech-2015-03-27_12.37.48.jpg

The same image, but encoded by the ShareX with the 100% of quality. And now he takes 718KB of space.
A increase in the file size without any improve in the quality of the image, as he is already in 80% originally.

A little more clear now? :)
Thanks

**Comment by Jaex** [comment]
I understood you but you didn't understood me. Clipboard upload can upload file directly without re encoding. And if you doing bitmap clipboard upload then it don't contains any jpeg info anyway and it will do what it is necessary.

**Comment by djprmf** [comment]
But why then the image is bigger that the original when i config a higher JPEG quality on ShareX?
If ShareX doesn't change that parameter, the size should be the same, and, as stated before, that is not the case...

**Comment by Jaex** [comment]
I don't know your settings or what workflow you doing.

**Comment by djprmf** [comment]
What do you need to know then?

**Comment by Jaex** [comment]
Step by step what workflow you following. Because normally it is not supposed to happen.

**Comment by djprmf** [comment]
I use ShareX mostly the upload from clipboard, where i copy to the clipboard a image, for instance, from a website (from the google images,etc) and use the shortcut keys to proceed with the upload task. But i notice that this also happend, for instance, if i copy a image in my desktop and proceed with the upload.

I also have tried put the workflow to directly upload to the host (FTP) and to save the image localy first and then upload, always with the same result.

In the settings, i don't have any "Clipboard Upload" option checked.
Also, i have attached the settings of the quality

![tugatech-2015-03-30_10 11 48 1](https://cloud.githubusercontent.com/assets/6960243/6893487/459e1e1c-d6c5-11e4-92aa-0207812e8444.jpg)

Hope that helps but let me know if is needed anything else.
Thanks

**Comment by Jaex** [comment]
If you copy jpeg image from web site then it copies bitmap to clipboard. So bitmap need to be encoded to jpeg or png and there is no technology in world which can do jpeg it again with same quality and same size. There is also clipboard upload setting which can download from image url and re upload it without re encoding.
And about file image uploading with clipboard upload. ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/03/ShareX_PeJsULL0uT.png) if this setting is false then it will directly upload image file without doing re encoding.

**Comment by djprmf** [comment]
But the original images are in JPG, not bitmap...

**Comment by Jaex** [comment]
You copying bitmap NOT JPG.

**Comment by HomelessAvatar** [comment]
When you copy an image to clipboard, it copies it as a bitmap, there's no way for Windows to store an image in clipboard other than in bitmap (so Windows can't store images as jpeg, png, gif etc. in clipboard, it automatically stores it as bitmap). When you then want to upload the image in clipboard, ShareX has to convert the bitmap to jpeg using its own encoder.

**Comment by djprmf** [comment]
Thanks for the info @HomelessAvatar :)
