### ISSUE TITLE
Custom hotkey ignores override and auto-uploads if image is edited before capture

### ISSUE THREAD

**Issue by Spirit532** [ShareX/ShareX#5721]
I have ShareX set up as follows:
![image](https://user-images.githubusercontent.com/13601407/127178526-275bc88d-630f-4693-b9c9-6d707c8b8f53.png)

If I hit Ctrl+End, then immediately select a region, it works fine and opens up the editor before uploading.
If I hit Ctrl+End, draw something, and then select the region, it completely ignores the custom task and automatically uploads the image without executing anything.

**Comment by Jaex** [comment]
ShareX is acting smart there, it sees you already annotated screenshot inside region capture therefore not opens image editor again to save your time.

**Comment by Spirit532** [comment]
Except it completely ignores "before upload" too.
I don't want to upload. I want to copy it into clipboard or CHOOSE to upload.

**Comment by Jaex** [comment]
I tested two times, it still showing "before upload" even it skip image editor.

**Comment by Spirit532** [comment]
Try it in this config:
![image](https://user-images.githubusercontent.com/13601407/127268421-6f317528-9ce5-4e49-8d0a-1a2d853f46ec.png)

**Comment by Jaex** [comment]
You did not even enable upload there, how it can show before upload.

**Comment by Spirit532** [comment]
Well, that wasn't exactly in the manual. Enabled upload, it shows that now. Still, it would be nice if the image editor feature had an option to override, even if edits were made. The scaling in the editor works differently, and sometimes I prefer to censor things on the capture stage, but add arrows/text in the editor.
