### ISSUE TITLE
Sharex is creating a imgur link when a screen shot is taken 

### ISSUE THREAD

**Issue by cyborgboy** [ShareX/ShareX#5726]
How do I delete a photo that is accidently uploaded by sharex to imgur 
Thanks

**Comment by cyborgboy** [comment]
Please ignore it problem solved - deleted the image Right click in ShareX > open > deletion URL

**Comment by cyborgboy** [comment]
Solved : 
We can Delete the image by going to 
Right click in ShareX > open > deletion URL
other way :
1. Go to C:\Users\username\Documents\ShareX
2. Open History.json and find deletion URL 
3. visit the "DeletionURL": to delete the particular image 

Thanks to sharex support

**Comment by Jaex** [comment]
Why you open History.json, there is History window in ShareX.

**Comment by cyborgboy** [comment]
Yeah jaex i was not aware of that feature at first and I uninstalled Sharex and the only way I had that time  is to get an image deleted via history.json and I thought to write it down here as issue for reference if any one had the same problem with deleting images if they accidently uninstalled Sharex
