### ISSUE TITLE
Unable to connect to remote server.

### ISSUE THREAD

**Issue by OnlineDenied** [ShareX/ShareX#573]
Frequently each time I go to upload a screenshot I get this

Message:
Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)

It use to never do it but now its really common is there any solution?

**Comment by Jaex** [comment]
Are you using BitDefender?

**Comment by OnlineDenied** [comment]
I'm currently using malwarebytes?

**Comment by Jaex** [comment]
That error happens mainly when firewall block ShareX.

**Comment by aniljadhavmca** [comment]
I was also getting the same error. And also found the solution for this issue!

Please refer following steps:
- Right click on sharX icon
- Click on Application settings menu - http://goo.gl/6ZOiE1
- Now click on proxy settings - http://goo.gl/ISmie7
- And select automatic proxy configuration

**Comment by aniljadhavmca** [comment]
I was also getting the same error. And also found the solution for this issue!

Please refer following steps:
- Right click on sharX icon
- Click on Application settings menu - http://goo.gl/6ZOiE1
- Now click on proxy settings - http://goo.gl/ISmie7
- And select automatic proxy configuration
