### ISSUE TITLE
shareX doesn' find Google Drive (Backup & Sync) Path (%UserProfile%\Google Drive\ShareX)

### ISSUE THREAD

**Issue by Helios61** [ShareX/ShareX#5732]
ShareX doesn't find Google Drive (Backup & Sync) Path (%UserProfile%\Google Drive\ShareX) ->  

`System.IO.DirectoryNotFoundException: Ein Teil des Pfades "G:\ShareX\PersonalPath.cfg" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bei System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   bei ShareX.Program.WritePersonalPathConfig(String path)
   bei ShareX.ApplicationSettingsForm.btnPersonalFolderPathApply_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.5 (Release)`

**Comment by vertigo220** [comment]
From that error, it looks like it's PersonalPath.cfg it's not finding, but as for the %userprofile\Google Drive\ShareX path, make sure it's in quotes. Could be the space throwing it off.
