### ISSUE TITLE
[feature request] Task that Opens the image in image viewer

### ISSUE THREAD

**Issue by fourteen-1** [ShareX/ShareX#5734]
of course, the image needs to be saved first. currently im working around this by having 'save' and 'open in image editor' as a task, basically using the editor as a viewer

it would be a lot better to have sharex save the image and open the image in the system's default image viewer.

**Comment by Jaex** [comment]
You can use "Perform actions" to open image in any image viewer or editor app.

**Comment by fourteen-1** [comment]
> You can use "Perform actions" to open image in any image viewer or editor app.

I've experimented with all the tasks and combinations. Activating the perform actions task did nothing. I thought it didn't work because it was relying on some other task being performed so I didn't report it here as a bug.

It perform actions task supposed to bring up the list of apps to open the image file? If so, it doesn't do anything on my copy of shareX.

**Comment by Jaex** [comment]
You need to add your image viewer to actions list and check it first.

![](https://jaex.getsharex.com/2021/08/ShareX_UxoXwdgUpv.png)

**Comment by fourteen-1** [comment]
thank you. now its working
