### ISSUE TITLE
Why can I only open 5 instances of "Actions"?

### ISSUE THREAD

**Issue by fourteen-1** [ShareX/ShareX#5735]
I have the task "save img and open in paint via actions".
After saving and opening 5 images, the 6th one doesnt open in paint.
the 6th one will only open in paint after i've closed one of the 5 opened images in paint. 

This happens not only just paint. its happening on my default image viewer as well.

Why is this happening and how do change this?

**Comment by Jaex** [comment]
Change this to 0:

![](https://jaex.getsharex.com/2021/08/ShareX_HnPVsjrcvL.png)
