### ISSUE TITLE
Screen recorder: Hotkey to record application window

### ISSUE THREAD

**Issue by wynntee** [ShareX/ShareX#5737]
There is an option to Capture an application window (for screenshots), but I can't find one for Screen Recording.

For Screen Recording, the region selector tool highlights the components of an application window (titlebar, statusbar, menu, etc)... but to select the entire application window, I have to hover over the window's border, which is literally one pixel wide.

I have to try a few times before I land on that one pixel. Is there an easier way to do this? Like a hotkey? If not, may I suggest a feature enhancement?

**Comment by Jaex** [comment]
You can create new hotkey for it:

![](https://jaex.getsharex.com/2021/08/ShareX_KGdlUGSTGg.png)
