### ISSUE TITLE
Hotkey runs multiple times when pressed once

### ISSUE THREAD

**Issue by TotieTo** [ShareX/ShareX#5742]
Hello
Ever since the 13.5 Update, the Capture region hotkey intermittently runs 3-7 times when it's pressed once, forcing me to abort the capture and try again, where it might happen again
I've reinstalled the program, cleaned my keyboard ;) and rebound the keys and the issue persists

It looks like this in the log file

> 2021-08-07 17:36:56.413 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:36:56.413 - Executing: Capture region (Light)
> 2021-08-07 17:36:57.413 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:36:57.413 - Executing: Capture region (Light)
> 2021-08-07 17:36:58.438 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:36:58.438 - Executing: Capture region (Light)
> 2021-08-07 17:36:59.453 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:36:59.453 - Executing: Capture region (Light)
> 2021-08-07 17:37:00.455 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:37:00.455 - Executing: Capture region (Light)
> 2021-08-07 17:37:01.468 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:37:01.468 - Executing: Capture region (Light)
> 2021-08-07 17:37:02.489 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:37:02.489 - Executing: Capture region (Light)
> 2021-08-07 17:37:03.490 - Hotkey triggered. Hotkey: Alt + S, Description: Capture region (Light), Job: RectangleLight
> 2021-08-07 17:37:03.490 - Executing: Capture region (Light)
> 2021-08-07 17:37:06.291 - Task in queue. Job: Job, Type: Image, Host: 
> 2021-08-07 17:37:06.305 - Task status: Preparing
> 2021-08-07 17:37:06.339 - Image copied to clipboard.
> 2021-08-07 17:37:06.825 - Image saved to file: D:\ShareX Screenshots\2021-08\2021-08-07_17-37-06.png
> 2021-08-07 17:37:06.842 - Task completed. Filename: 2021-08-07_17-37-06.png, Duration: 537 ms
> 2021-08-07 17:37:06.843 - ApplicationConfig save started: C:\Users\Totie\Documents\ShareX\ApplicationConfig.json
> 2021-08-07 17:37:06.843 - UploadersConfig save started: C:\Users\Totie\Documents\ShareX\UploadersConfig.json
> 2021-08-07 17:37:06.843 - HotkeysConfig save started: C:\Users\Totie\Documents\ShareX\HotkeysConfig.json
> 2021-08-07 17:37:06.939 - UploadersConfig save successful: C:\Users\Totie\Documents\ShareX\UploadersConfig.json
> 2021-08-07 17:37:06.966 - HotkeysConfig save successful: C:\Users\Totie\Documents\ShareX\HotkeysConfig.json
> 2021-08-07 17:37:06.995 - ApplicationConfig save successful: C:\Users\Totie\Documents\ShareX\ApplicationConfig.json

**Comment by Jaex** [comment]
Did you change this option?

![](https://jaex.getsharex.com/2021/08/ShareX_4LbezvvtQ6.png)

**Comment by TotieTo** [comment]
I have not touched it and it's set to 1000 for me

**Comment by Jaex** [comment]
Your debug log shows it triggers every 1 second which means your key is staying down somehow. Because nobody reported such issue before I highly doubt it is problem in ShareX.

**Comment by TotieTo** [comment]
I've switched USB ports and even keyboards and the problem persists, I assume it's some rare bug with something on my OS, then :/

**Comment by vertigo220** [comment]
Next step would be to close all other programs and see if it still happens. After that, try safe mode. Also, try closing ShareX and setting that as a shortcut in another app, then trigger it and see if it triggers multiple times. Probably a good test would be AutoHotkey with a script that writes to a file or something, though possibly just setting it as play/pause in a player might work.
