### ISSUE TITLE
Image Editor causing scratchy noise in PC

### ISSUE THREAD

**Issue by fliespl** [ShareX/ShareX#5744]
I have noticed really strange thing. I have setup sharex to open image editor after image capture.

The moment it opens I get "noise"/"scratchy" sound from speakers. 

The moment I click "exit" icon it goes away,

Any idea what could it be? Am I able to provide you with some debug stuff to diagnose this issue?

Version: 13.5

**Comment by Duckrinium** [comment]
Can you provide some video or audio reference. It's very weird otherwise.

**Comment by fliespl** [comment]
Probably would be better with more sensitive microphone but it's still hearable on those two.

https://ss.codeone.pl/ss-2021-08-08-14-51-46-1628427106-h9vLQxKk.mp4
https://ss.codeone.pl/ss-2021-08-08-14-51-46-1628427106-V8j9e6Sd.mp4


More info:
- noise goes away if image editor loses focus (i.e. clicking start bar), goes back on clicking back inside window.
- not having issues with other tools...
- noise changes depending if window is maximized or not (but still focused)
- downloaded version 13.1 and it's doing it on this version as well.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2021/08/nervous-sign-of-the-cross.gif)

Need to call exorcist!

**Comment by fliespl** [comment]
> ![](https://camo.githubusercontent.com/31e7383a566ff952029df232ff36608dcc1ef294a32e7cd18c995951c33648cf/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f30382f6e6572766f75732d7369676e2d6f662d7468652d63726f73732e676966)
> 
> Need to call exorcist!

@Jaex It was first association indeed!

Are there any instructions how to build locally? I might give it a go once I return from holiday by simply commenting out stuff that's inside image editor. Unless you have some debug logs I might collect and provide to you?
