### ISSUE TITLE
How to temporarily save the image with copying it given that only "Open in image editor" and "Copy image to clipboard" are checked?

### ISSUE THREAD

**Issue by YandLiu** [ShareX/ShareX#5757]
Background: I only checked `Open in image editor` and `Copy image to clipboard` in `After capture tasks`.
If I temporarily want to save the image after editing it, I have to press Ctrl+S, but even if "Copy image to clipboard" is checked, the image will still not be copied to the clipboard.

**Comment by yashpalgoyal1304** [comment]
which sharex version - i faced this few versions ago, but in 13.4 and 13.5 this works fine

**Comment by YandLiu** [comment]
That's weird... I'm using exactly 13.5.

**Comment by YandLiu** [comment]
Any solution now?
