### ISSUE TITLE
Add compatibility with Display fusion

### ISSUE THREAD

**Issue by connected201** [ShareX/ShareX#5762]
Hi, i have 2 monitors, and sharex not working properly with display fusion, when i want to make screenshot i get this:
![image](https://user-images.githubusercontent.com/20506433/129439214-a2db269f-4ce0-44be-ba4d-fc5346a2effe.png)
this image i see on second screen, so apps going left, and primary display moving to second display to. if i close display fusion, all working well.

**Comment by Jaex** [comment]
duplicate of #5408
