### ISSUE TITLE
Screen color picker stuck when using hotkey

### ISSUE THREAD

**Issue by hokutonanto** [ShareX/ShareX#5764]
Hi there,

I noticed that if I use the screen color picker via hotkey, the magnified area is stuck on the screen.
When I right-click on the ShareX icon in the tray bar, and I choose the screen color picker tool, I can then move the magnifier around.

I'm using ShareX 13.5, but I noticed the same issue happens with 13.4

**Comment by Jaex** [comment]
I can't reproduce it with this hotkey:

![](https://jaex.getsharex.com/2021/08/ShareX_JN49pF6w9K.png)

**Comment by hokutonanto** [comment]
Thanks @Jaex 
I tried with F9 with no luck.

By the way, I'm using the portable version.

https://user-images.githubusercontent.com/23059969/129494778-7a8176bd-829f-454e-8ec3-7949d10eaca7.mp4

**Comment by Jay-Tarzan** [comment]
Goodie
