### ISSUE TITLE
Running via commandline to edit or upload doesn't bring the dialog to the front.

### ISSUE THREAD

**Issue by stephen147** [ShareX/ShareX#5774]
If this is used for editing:
`ShareX.exe -ImageEditor "filepath"`

Or, this is used for uploading:
`ShareX.exe "filepath"`

The editor window or upload window doesn't appear at the front.

Is there an additional switch to ensure ShareX gets brought to the front?

**Comment by stephen147** [comment]
Bumping issue.

**Comment by stephen147** [comment]
Bump.

**Comment by Jaex** [comment]
Both methods actually using:

![](https://jaex.getsharex.com/2022/08/devenv_fOfmTooLLO.png)

Yet somehow it not works when executed from Windows context menu, I have no idea why.

**Comment by stephen147** [comment]
```
form.Activate();
form.Focus();
```

?

**Comment by stephen147** [comment]
I may have found another way to do this. I was writing a powerShell script and came across this issue but resolved it with this. The code below just needs to be translated to C#.

You can call an external script so it's not in the same thread.

```
cmd /c start /min powershell.exe ((Split-Path -LiteralPath (Get-PSScriptPath)) + '\dependencies\winfront.ps1')
```

The `.ps1` file.

```
[void] [System.Reflection.Assembly]::LoadWithPartialName("'Microsoft.VisualBasic")
[Microsoft.VisualBasic.Interaction]::AppActivate((Get-Process -Name "ShareX - Before Upload").MainWindowTitle)
```
