### ISSUE TITLE
Any way to save to various folder paths in Quick Task Menu?

### ISSUE THREAD

**Issue by theoryshaw** [ShareX/ShareX#5775]
I was looking for this too and found the following that perfectly explains the feature request. 

https://www.reddit.com/r/sharex/comments/nlkm47/any_way_to_save_to_various_folder_paths_in_quick/

> I just use Print Screen to start a manual capture and I prefer the menu after I make the screenshot as sometimes I just want it saved to the Screenshots folder, sometimes I want to Add Annotations first, sometimes I just want to copy to clipboard.
> But, I'd like to setup that menu with Save to: "Work", "Personal", Financial", etc. and have screenshots saved to different paths with a click.
> I know I can set up different hotkeys, but that adds a level of complexity as I want to setup at least 5 different paths.
> TIA

**Comment by Rediwed** [comment]
Bumping this request.
