### ISSUE TITLE
Make Gfycat uploads unlisted by default

### ISSUE THREAD

**Issue by gakiloroth** [ShareX/ShareX#5777]
I dug around looking to see if this is an option, apologies if I missed something obvious, but I can't find a way to make my ShareX recordings that are uploaded to Gfycat "Unlisted" by default when using an account, instead of public. Is there a way to do this?

**Comment by Jaex** [comment]
I check now it is already private by default?

**Comment by gakiloroth** [comment]
Huh. For me these are the settings, and if I uncheck "Public upload" it uploads without using my Gfycat account and just becomes a  public upload with no account. Perhaps this is just a setting I need to figure out, thanks

![image](https://user-images.githubusercontent.com/9069768/130335704-a4396f58-f29e-41ed-a549-f8f13dac18a3.png)

**Comment by Jaex** [comment]
I tested now, videos appeared in my Gfycat account very late. Also when you do private upload it not shows your account in video page, it is same when you do web upload too. So there is no problem.

**Comment by gakiloroth** [comment]
yea, i tested again and it appeared on my acc page very late and was unlisted when i went to manage view. thank you!
