### ISSUE TITLE
Haven't been able to upload to imgur for months

### ISSUE THREAD

**Issue by MaceBTW** [ShareX/ShareX#5780]
When I take a screenshot, it just plays a low pitched "ding" and gives me this error

  
![ShareX_jILgjyqTBX](https://user-images.githubusercontent.com/89434434/130546425-cca2d530-61b6-4ba0-b184-bf16ed4166ff.png)

**Comment by falcon4fun** [comment]
**Update:**
Fixed by uploading to website and solving recaptcha. Now it's working. Wrote feedback to Imgur because it look like a bug..

**Comment by ninox14** [comment]
after upload through site it sends me to https://imgur.com/a/undefined XDDDDDDDDDDDDDDDD
no captcha prompt 
![](https://i.vgy.me/ao1dUx.png)
for some reasone i have 0 request remaining for like a pretty long time
