### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iRedddy** [ShareX/ShareX#5782]
Error message:
The remote server returned an error: (422) Unprocessable Entity.

Request URL:
https://vgy.me/upload

Status code:
(422) Unprocessable Entity

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, private
Content-Type: application/json
Date: Tue, 24 Aug 2021 20:11:33 GMT
Set-Cookie: XSRF-TOKEN=eyJpdiI6IjY3YUROcC9sTlFjZFZnc1Vhbmx4VUE9PSIsInZhbHVlIjoicytTdUlkMSt0dWtkOThpeTZNdGhPODR6KzhONHdkQzB0QjlNMS96M0EwcWNGMTVHS1JtbEdHNFljSVI1WUJFeGZSR1lUTmRhTkJoR2R4ejYvblNtSzI1bUl1cFRLcnlQQU1WWW5kOFZWeVdHUWdKUjVHT0ZQeG1aeFl5dmdPREIiLCJtYWMiOiIyM2Q1NjBlNmZiNTQ3NjU2ZGRhZGFmNDc4ZGJiZjVhMDFjMmEwNjAxNDUyMWJjMGEyOGM3NTVkYzMwYmM1ODczIiwidGFnIjoiIn0%3D; expires=Tue, 24-Aug-2021 22:11:33 GMT; Max-Age=7200; path=/,vgyme_session=Dt69aGHiseiVTXPWl6z9yYQemDiNmbjEbPt3aQHR; expires=Tue, 24-Aug-2021 22:11:33 GMT; Max-Age=7200; path=/; httponly
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'self'; img-src https: data:; media-src https: data:; script-src 'unsafe-inline' 'unsafe-eval' https:; style-src 'unsafe-inline' https:; font-src https: data:; frame-src https:
strict-transport-security: max-age=2592000; includeSubDomains; preload
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=9fd9UbF9d1%2FCBwzOZFGVajD4lhX5YHM92Cv058GUD7aU2JH9ybpeKAQbW233ubOs80OwVNGEF9q9iUriG8mBIxGDIrdULLjXeyWhFrOSwZgDKANh1p7BXvY%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 683f38bed86229fa-ORD
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400

Response text:
{"error":true,"messages":{"Unauthorized":"You are not logged in, or your account has been banned. You cannot upload anonymously."}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

dunnno

**Comment by Jaex** [comment]
It says:

> "You are not logged in, or your account has been banned. You cannot upload anonymously."

**Comment by Jay-Tarzan** [comment]
Failed
