### ISSUE TITLE
teknik.io - login failed

### ISSUE THREAD

**Issue by janafrank** [ShareX/ShareX#5786]
I've had teknik destination configured. Recently the destination failed to upload files. I've tried to refresh the authorization, but when I post the verification code, it says "Login failed".

**Comment by ennsbq** [comment]
I'm facing the same issue. Any way to fix it?

**Comment by hdpcshow** [comment]
Having the same issue to.

**Comment by ninox14** [comment]
same

**Comment by Raridaze** [comment]
Can confirm, shareX gives the verification code but it doesn't work.

**Comment by Jaex** [comment]
It is fixed in pre-release build.
