### ISSUE TITLE
ShareX won't run when Windows start if ShareX.exe is set to run with administrative privileges

### ISSUE THREAD

**Issue by rogeriodec** [ShareX/ShareX#5790]
To solve this issue https://github.com/ShareX/ShareX/issues/5785, I had to set ShareX.exe to run as admin.
But now ShareX won't run when Windows start.
If I uncheck the run as admin, it works.
How to fix this?

**Comment by Jaex** [comment]
https://superuser.com/a/929227/223867

**Comment by Jaex** [comment]
I'm writing detailed step by step instructions here in case someone may need in the future.

### How to run ShareX at startup as administrator?

1. Run **Task Scheduler**.
2. At the right side click **Create Task**.
3. For **Name** you can enter `Start ShareX at log on`.
4. Check **Run with highest privileges** option.
5. For **Configure for** option select your operating system, for example **Windows 10**.
6. Switch to **Triggers** tab and press **New** button.
7. For **Begin the task** option select **At log on** and press **OK**.
8. Switch to **Actions** tab and press **New** button.
9. Press **Browse** button and choose `ShareX.exe` which is by default stored at `C:\Program Files\ShareX`.
10. For **Add arguments** option enter `-silent` and press **OK**.
11. Close **Create task** dialog by pressing **OK**.
12. Now next time Windows starts ShareX will be started as administrator.

**Comment by KarioTommy** [comment]
Thanks for sharing the solution Jaex <3
