### ISSUE TITLE
Image effects feature saves two lists of presets instead of one

### ISSUE THREAD

**Issue by tumerokslayer** [ShareX/ShareX#5795]
Image effects has a different list of presets depending on how you access it. If you access it either: 1) within the main ShareX window through the right-click menu on a previously uploaded image OR 2) through the sidebar in the main window via Tools > Image Effects... and then select an image in the prompt, you get one list (list #1). However, if you access image effects via a keybind, you receive a different preset list (list #2). In order to easily observe that they are in fact unique lists, you might want to add/delete presets on each one.

**Comment by ariefcfa** [comment]
Yes, yesterday i found this is still happening in ShareX 15.0. Please reopen this issue.

**same image effects presets** are showed when accessed from:
- ShareX tray icon `Tools > image effects...` (or from CLI `ShareX.exe -ImageEffects`)
- main program window `Task settings... > (Image) Effects > Image effects configuration...`

![ImageEffects_from_CLI](https://github.com/ShareX/ShareX/assets/34770799/32b46982-f500-4aa7-a476-f7da384542cc)
![ImageEffects-from_settings](https://github.com/ShareX/ShareX/assets/34770799/8f81cc7a-0ac8-4774-a855-b8fa68cc7acc)


but **different image effects presets** are showed when accessed from ShareX Image editor window > `add image effects...`
 
![ImageEffects-diff_from_Image_editor_add_image_effects](https://github.com/ShareX/ShareX/assets/34770799/32fded91-ec23-4406-a5f5-a13fc6eb1d1c)

cheers :)
