### ISSUE TITLE
Add an optional popup to specify a file name (after taking a screenshot)

### ISSUE THREAD

**Issue by AngryCarrot789** [ShareX/ShareX#5798]
Basically, if you take a screenshot, it opens a window that has a textbox, and you can type in a file name into that text box, and it will name the image with that name, instead of the default file name/pattern in the settings

And if you don't want to name the file and just want it to use the default, you can just press escape and it will close the window and give it the default name

I feel like this would be useful if you're screenshotting lots of things and want to instantly name the image right there and then, instead of having to goto the destination folder and rename it yourself

**Comment by martinbra** [comment]
I'd lke to add to this, in the captured file list, it would be nice to have a right click option to rename the selected file:
![image](https://user-images.githubusercontent.com/29928669/134234392-e1d6cdac-0b8e-4574-a834-f0f55e1d33df.png)

if I rename directly on the destination folder, the link to open the file is lost.

**Comment by kadamiec** [comment]
Hello @AngryCarrot789 @martinbra @displayerror 
I needed also such functionality, so I have made Pull Request (https://github.com/ShareX/ShareX/pull/6035) with implementation of the mentioned feature :)

**Comment by martinbra** [comment]
@kadamiec , nice! thanks.
