### ISSUE TITLE
ShareX does not upload the whole screen recording

### ISSUE THREAD

**Issue by kekkles** [ShareX/ShareX#580]
If I capture a video with ShareX, and select the entire screen region, ShareX will not upload the entire video. It will only upload about 2/3 of it for some reason.

This doesn't seem to happen when selecting a smaller screen region.

I'm also using webm instead of mp4, if it matters. The settings I used for ffmpeg are attached in the image.
![b19b520386](https://cloud.githubusercontent.com/assets/11714098/6890612/ad757e34-d67c-11e4-8131-51afc92c3528.png)

**Comment by Jaex** [comment]
Are you using different DPI?
Trying using "screen-capture-recorder" for video source which works fine with different DPI.

**Comment by kekkles** [comment]
I am using the standard Windows DPI. Also, I already tried "screen-capture-recorder", and it has the same issue.

**Comment by Jaex** [comment]
Oh you talking about video length, i thought you talking about video resolution size.
When you start it, it opens CLI window in background mainly it starts so quick but maybe in your computer something slowing down its open so long that you think it not uploaded full of it?

**Comment by kekkles** [comment]
I am not quite sure what you mean with that post, but the uploaded video is always a few seconds shorter than the time I spent recording.

**Comment by Jaex** [comment]
Is beginning of video missing or end of video is missing? Or is video running faster?

**Comment by kekkles** [comment]
The end of the video is missing. The video appears to run at normal speed.

**Comment by Jaex** [comment]
I'm not sure how it is possible but ShareX using FFmpeg CLI for recording and if problem happens then it happens in FFmpeg side and I can't fix it.

**Comment by kekkles** [comment]
I think it may be because of ShareX's ffmpeg configuration. This issue doesn't seem to be present in other screen recording software that uses ffmpeg.

**Comment by Jaex** [comment]
Other softwares use ffmpeg library not CLI. And that softwares doing recording theirself too. But in ShareX even recording happens in ffmpeg. You can see what commands ShareX supply and you can customize them too.

**Comment by Jaex** [comment]
Is your problem happens with x264 too?

**Comment by kekkles** [comment]
I have just test it, it only happens with webm.

**Comment by Jaex** [comment]
With webm too much frame drops happens anyway, it is not very suitable for real time recording. So I suggest you to use x264.
