### ISSUE TITLE
13.6 - Main windows keeps popping up

### ISSUE THREAD

**Issue by stephen147** [ShareX/ShareX#5802]
This window keeps appearing after the update every 30 seconds or so.

I'm currently using the portable build on the latest version of windows.

![image](https://user-images.githubusercontent.com/14054664/132105963-2b10512e-48a6-45dd-9b32-55c05734fafb.png)

**Comment by Jaex** [comment]
I'm unable to reproduce it in normal build nor portable build.

**Comment by stephen147** [comment]
> I'm unable to reproduce it in normal build nor portable build.

I will see tomorrow when I have done a restart of the PC.

Is there any steps I can do to get a log file or something?

**Comment by stephen147** [comment]
It doesn't do it now. Closed.
