### ISSUE TITLE
NVENC doesnt pass faststart movflag to FFMPEG by default

### ISSUE THREAD

**Issue by aizuon** [ShareX/ShareX#5806]
CPU encoded H264 preset passes -movflags +faststart argument to FFMPEG by default for fast web playback but NVENC encoding doesnt replicate this behavior, which makes web browsers wait for the entire download of the video to start playing. NVENC should pass this flag to FFMPEG by default as well. 

https://github.com/ShareX/ShareX/blob/c8ed5bd793273a671c2124967e07aa701f2086e1/ShareX.ScreenCaptureLib/Screencast/ScreencastOptions.cs#L190

**Comment by Jaex** [comment]
I couldn't test it, because need very long recording to test it.

**Comment by aizuon** [comment]
> I couldn't test it, because need very long recording to test it.

I've tested the latest build and it seems to be fine. Thank you for this commit!
