### ISSUE TITLE
Transparency lost when copying to clipboard (again)

### ISSUE THREAD

**Issue by namazso** [ShareX/ShareX#5809]
this was supposedly once fixed before: https://github.com/ShareX/ShareX/issues/1393 but i never saw it working ever since i use ShareX

i have automatic copy to clipboard enabled, and this is what i get on my clipboard:

![image](https://user-images.githubusercontent.com/8676443/132585227-2e3c532a-b70c-4389-a0b9-e4bb9b49919d.png)

as opposed to the file it saves:

![ShareX_Xa7WmXwG0w](https://user-images.githubusercontent.com/8676443/132585258-b53afa26-c6db-4a6f-acf8-e076ae40089a.png)

OS: Windows 10 21H1 (19043.1165)

**Comment by Jaex** [comment]
Set this option to `True`:

![](https://jaex.getsharex.com/2021/09/ShareX_06I75Jl83p.png)
