### ISSUE TITLE
How to make ShareX the default image editor for Windows?

### ISSUE THREAD

**Issue by rolltidehero** [ShareX/ShareX#5811]
I love the ShareX image editor and I would like to make it the default image editor for Windows. 

However, when I select the ShareX.exe process, it just processes the image like it would a capture instead of opening the image editor. 

Is there any way around this? Could you possibly release the image editor as it's own app?

**Comment by Jaex** [comment]
https://getsharex.com/docs/command-line-arguments

There is `-imageeditor` command.

**Comment by rolltidehero** [comment]
> https://getsharex.com/docs/command-line-arguments
> 
> There is `-imageeditor "file path"` command.

Thanks. So how would I use this to make it my default image editor?

**Comment by rolltidehero** [comment]
Thanks. But I cannot figure out how to set it as the Default Program for image files. 
I'm trying to edit the registry now for PNG files to see if I can add the -imageeditor parameter. 
Do you have any ideas?

**Comment by rolltidehero** [comment]
I was able use a tool like Default Programs Editor to do the job: https://defaultprogramseditor.com/

1. First, Select "File Type Settings".
2. Then select "Context Menu".
3. Now in the search box type the file extension of the image file, e.g. ".png" and click Next
4. Click on "Edit" in the list and click Edit Selected Command at the bottom.
5. Now, in the "Program Path" box type in the following: "C:\Program Files\ShareX\ShareX.exe" -imageeditor "%1"
6. Click Next and then click Save Context Menu

Then whenever you open a PNG file, it opens with ShareX image Editor where you and can quickly edit and upload from.

**Comment by hyatt-e** [comment]
Is there a way to open image files in the editor by default? Like when I double click on an image?
