### ISSUE TITLE
[Feature Request] Key to slow down the mouse for more accurate selections

### ISSUE THREAD

**Issue by rogeriodec** [ShareX/ShareX#5815]
Often when I try to precisely select a few pixels, for example, a corner of a square, the mouse movement is very fast, making it almost impossible to select these pixels precisely.
I suggest creating some support keys while selecting, for example, pressing Ctrl will slow down the mouse, thus enabling greater precision when selecting pixels.

**Comment by crzytrane** [comment]
@rogeriodec the arrow keys work quite nicely for pixel perfect movements like this. If you need to move the box you've selected you can hold Ctrl + mouse drag to move the region you've selected too.

**Comment by trevorjobling** [comment]
I like this suggestion. ShareX makes the capture as soon as I release the mouse button after dragging a region (which I like) but it means I don't get to use the arrow keys, or CTRL+drag. So that would be a handy feature.

**Comment by Jaex** [comment]
Sometimes I need this feature too but I don't like the idea of changing Windows mouse sensitivity settings to slow it down. For example if pc crash while doing that then sensitivity will be stuck slowed down. Also all modifier keys already taken in region capture.
