### ISSUE TITLE
Image Editor - Option to fit the image to the window size when it is resized (scaled down)

### ISSUE THREAD

**Issue by aferrazlr** [ShareX/ShareX#5818]
It'd be really useful when capturing the entire monitor screen and then editing the image with annotations using a window a bit smaller than the monitor size but still being able to see the entire screenshot.

This issue is to request that ShareX Image Editor has an option to fit the image to the window size even when it is resized (scaled down).

Thanks,

**Comment by L1Q** [comment]
looks like a duplicate of #2325
