### ISSUE TITLE
Customizable detail bar

### ISSUE THREAD

**Issue by csengh** [ShareX/ShareX#582]
Is any chance to change detail bar columns e.g. after I upload an image to Imgur, "detail bar" has filename, status, progress, URL columns. I don't want to see status and progress columns, but I want to see deletion link for uploaded file. I find this link in "response" task but I want to see directly.

thank's.

**Comment by Jaex** [comment]
What is point of be able to see deletion URL? It is not like you are gonna write it manually. You will instead press open deletion url button.
