### ISSUE TITLE
ShareX not start

### ISSUE THREAD

**Issue by ferino75** [ShareX/ShareX#5821]
I use ShareX portable version.
But from v 13.6.0 cannot start, when I doubleclick to sharex.exe - nothing happens.
Windows Defender probably blocking this file.

Windows 10 Pro 21H1  19043.1202

**Comment by postb99** [comment]
Same issue, version 13.5 launches but version 13.6.1 (didn't try version 13.6.0) is blocked by Windows Defender because of "unknown editor".
Company computer running Win Enterprise 10.0.18363.
What did you change under the hooks between version 13.5 and 13.6 ? Certificate issue ?
