### ISSUE TITLE
Sync dark/light theme with Windows dark/light theme settings

### ISSUE THREAD

**Issue by VapidLinus** [ShareX/ShareX#5823]
I toggle between Windows dark mode and light mode very often.

I wish for a setting in ShareX where it switches to a light mode if Windows switches to light mode, and where ShareX switches to dark mode when Windows switches to dark mode.

Preferably you should be able to choose which _custom theme_ when light or mode is active respectively, but I don't need that specifically.

Thanks :)

**Comment by VapidLinus** [comment]
I'd be interested to get a comment on if this is a reasonable feature or not before it's closed and discarded forever. Other applications have this feature and I'd love for ShareX to support it too.

**Comment by KvanTTT** [comment]
I'm interested in the feature as well.
