### ISSUE TITLE
Copy to clipboard filesize inconsistency

### ISSUE THREAD

**Issue by Accelyte** [ShareX/ShareX#5828]
I currently have the `Copy image to clipboard` option selected in the `After capture tasks` menu, and I have VALORANT open in borderless. After pressing `PrtScr` to screenshot, I tried to paste the screenshot into Discord, but Discord tells me the filesize has exceeded 8MB. I then tried pasting the screenshot into Telegram without compression, and Telegram indicates that the screenshot is 4.7MB. For comparison, I tried the same with Chrome, which gave a reasonable ~300KB file.

On the other hand, the actual filesizes themselves are 706KB and 326KB respectively. Is there a reason why the VALORANT screenshot is that much bigger, or is it a bug?

![image](https://user-images.githubusercontent.com/21363469/133842162-4abdf9ee-6691-4204-86a5-0984866fa89a.png)

**Comment by Jaex** [comment]
If you don't want clients to re encode image with their own encoding options then you can copy the image file, instead of image. That way it will be same file size as what ShareX captured. There is no bug.
