### ISSUE TITLE
Thumbnails in ShareX are mostly blank 

### ISSUE THREAD

**Issue by ckxion** [ShareX/ShareX#5829]
For at least 6 months each time I open shareX all or most of my previous thumbnails are missing. The links to the saved image still work.

When I upload an image the thumbnail is visible until I close ShareX

Windows 10 64bit
[https://i.imgur.com/XHvyOE3.png](https://i.imgur.com/XHvyOE3.png)

**Comment by Jaex** [comment]
You must save image as file if you want thumbnails to show up.
