### ISSUE TITLE
Portable distro

### ISSUE THREAD

**Issue by mbnoimi** [ShareX/ShareX#583]
Hi,

After releasing 9.8.0 I unable to find portable distro on your website!

**Comment by Jaex** [comment]
It is in here https://github.com/ShareX/ShareX/releases/tag/v9.8.0

**Comment by mbnoimi** [comment]
Thanks @Jaex May you please add a link on the website?

**Comment by Jaex** [comment]
Auto updater not works with portable so I don't want everybody to use it.

**Comment by mbnoimi** [comment]
Hmmm, try to add portable distro on http://portableapps.com they've magnificent updater for portable distros.

**Comment by Jaex** [comment]
They don't add .NET apps.

**Comment by mbnoimi** [comment]
Oops I didn't take a look to your code. I though it's MFC based. Any way, I'm glad to use your project.

**Comment by mbnoimi** [comment]
You can take a consider Qt instead of .NET. Qt is much flexible and stable.

**Comment by RoyiAvital** [comment]
This is great that you offer Portable Version.

Does it means this version keeps all the settings in the local folder, doesn't write to anything else on the HD and makes no registry changes?

Thank You.
