### ISSUE TITLE
ShareX + PowerToys FancyZones bug

### ISSUE THREAD

**Issue by mangkoran** [ShareX/ShareX#5832]
![image](https://user-images.githubusercontent.com/57625126/133926800-9c348e5b-e9c5-4fb3-be07-2c1217d1b8f4.png)

OS:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎7/‎30/‎2021
OS build	22000.194
Experience	Windows Feature Experience Pack 1000.22000.194.0

This bug appear randomly. Sometimes it appears, sometimes it doesn't. The image above is what I saw when the bug occurred. Captured with Windows Snip Tool. Should be somewhat related to https://github.com/ShareX/ShareX/issues/5701 https://github.com/ShareX/ShareX/issues/5712, but it seems the potential fix doesn't work.

Monitor layout:
```
                 ---------
                |         |
                |         |
                |         |
 ---------------|    2    |
|               |         | 
|       3       |         |
|               |         |
 --------------- --------- 
|               |         
|    main (1)   |       
|               |         
 --------------- 
```
All have the same resolution (1920 x 1080)

Edit: I forgot to mention that I also use [PowerToys FancyZones](https://github.com/microsoft/PowerToys). Updated the title as well.

**Comment by EdoaLive** [comment]
I think I have the same problem with Windows 10 and [Powertoys' FancyZones](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones).
I said "I think" because the problem appears at random (not always) and just this time I tried to close PowerToys and it stopped doing it.
Probably it has something to do with automatic window positioning (?) Just leaving here the hint for the developers.

**Comment by mangkoran** [comment]
Oh yes, I forgot to mention that I use PowerToys FancyZones too!

I just found out your edited comment and haven't tried the solution yet. However, I somehow managed to found another workaround fix. By default, if you have PowerToys FancyZones (I will refer this to "FZ" for the rest of the discussion) active, any apps you just started is "unsnapped" or "untiled" by FZ. If we launch ShareX, it will not be tiled by FZ. Then if we try to screenshot, specifically "Capture Region" task, the bug will appear. However, if we open the ShareX apps AND THEN snap or tile it with FZ then try to "Capture Region" again, the bug will not appear.

With this information, could we determine whether it is ShareX issue or PowerToys'?

Sorry I cannot provide video evidence because it's so hard to capture the ShareX overlay.

**Comment by 3xploiton3** [comment]
i have this problem too

**Comment by mangkoran** [comment]
Any updates?

**Comment by lohrm-stabl** [comment]
This issue still exists

**Comment by mangkoran** [comment]
Based on what I've searched, this is PowerToys issue https://github.com/microsoft/PowerToys/issues/29193
