### ISSUE TITLE
unable to set middle click to last region

### ISSUE THREAD

**Issue by hungrysnake** [ShareX/ShareX#5833]
the middle click is defautl to last region accoring to the doc but it is swap tool in the actual default setting.
there is no option in the setting to set it back to last region. am i looking at the wrong place in the setting?

![image](https://user-images.githubusercontent.com/42885440/133955527-bd109635-637b-45be-a3cb-b47be26c8777.png)

**Comment by Jaex** [comment]
It selects last region type in region capture. Not the last region capture you thinking of.

**Comment by hungrysnake** [comment]
thanks. is there a way to set the key/click to set the capture region to last region instead of doing it in the menu bar
it would be very helpful when capturing a series of image for tutorial/howto like mobile app tutorial which i always need to capture the same area over and over during the demo

![image](https://user-images.githubusercontent.com/42885440/133956132-6ee7d445-909c-4bc7-b0ef-ac0f5b8a41eb.png)
