### ISSUE TITLE
update to 13.6.1 broke the standard ctrl + prtscr option

### ISSUE THREAD

**Issue by DBVE** [ShareX/ShareX#5837]
Updating on 13-09 from 13.5 to 13.6.1 broke the standard ctrl + prtscr option.
Restarted the computer several times in between.
Not yet made a remove/install move. If this is the first way to go let me know.
If you need logging also let me know. 
I don't get any errors or events related to this.

**Comment by Nivyan** [comment]
I have the same issue, here's a log:

Trtied reinstalling the ffmpeg codec, no difference

```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[dshow @ 000001330c5ff200] Could not find video device with name [screen-capture-recorder] among source devices of type video.
video=screen-capture-recorder:audio=virtual-audio-capturer: I/O error

```

**Comment by DBVE** [comment]
@Jaex i have reinstalled the software.
Are the some locations in the registry that i must remove to get a clean install?

**Comment by Jaex** [comment]
`Documents\ShareX` folder contains settings and screenshots.

**Comment by DBVE** [comment]
@Jaex 
Uninstalled software.
Renamed folder to sharex_old
Installed software.
Same issue.
Reversed above steps and also same issue.

**Comment by Jaex** [comment]
If it not gives any error then 99.99% of times it is not to do with ShareX, so I can't know what is wrong in your computer causing ShareX to not run without give any errors.

**Comment by DBVE** [comment]
Reinstalled 13.5 same issue.
@Jaex you send me a direct mail from github that it is my computer and I agree with that. As it is a corporate computer i am not investigate further on what it is.

Thanks for your support!
