### ISSUE TITLE
Option to change sounds

### ISSUE THREAD

**Issue by brimstone-** [ShareX/ShareX#584]
Could it be added to let the user choose their own audio files to play when taking screenshots/sucesful upload? Thank you.

**Comment by Jaex** [comment]
Main reason was why I didn't added before because I couldn't find good sounds so I thought people would suggest good sounds for them. Because was using Windows sounds before. Still not sure is it good idea even I found slightly better upload and error sound than default Windows sounds.

**Comment by brimstone-** [comment]
Oh I'm not asking to change the default sound, I'm just asking for the option to use my own personal one, since every person probably has different choices.

**Comment by davidi17** [comment]
How do you turn off the sound?

**Comment by Jaex** [comment]
From Task Settings.

**Comment by davidi17** [comment]
Duh! Many thanks for replying. Your ShareX software is brilliant. Well done.

**Comment by chrisjj** [comment]
I too would like an option to change the sound source. Or at least exit the existing WAV - currently not easy AFAICS since it is embedded in the EXE.

I think the ideal would be to use a custom system sound like this: http://i.imgur.com/pYLnqj6.png

**Comment by Jaex** [comment]
You can already change or disable sounds.

**Comment by chrisjj** [comment]
Great! How do I change sounds?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/11/ShareX_goSeD82IOO.png)

**Comment by chrisjj** [comment]
Great! Done http://i.imgur.com/Ueov5cD.png

Thanks and thanks again for a great program.

**Comment by drk-mtr** [comment]
Great software, thanks!! 

The sound being on by default is highly irritating and the fact it's in Task Settings not Application Settings is unintuitive.
