### ISSUE TITLE
file extension: jpeg / jpg

### ISSUE THREAD

**Issue by KamiyaMinoru** [ShareX/ShareX#5840]
If it is possible to decide/switch file extension from jpeg to jpg?
When uploading to i.e. imgur and post the link to some forum or read by some app
jpeg is not recognize (this, not load it) while many authors do not notice this tiny matter.

**Comment by yesBad** [comment]
You can change the extension in ShareX like this:
![Picture "wow"](http://my-favourite-loli.is-having.fun/pmte86xkv64q.png)

**Comment by KamiyaMinoru** [comment]
yes...  I found this problem when
I was using jp(e)g, or checking
"use jpg whwn size larger than..."

currently I gave jpeg for png is okay

Bad ***@***.***> 於 2021年9月24日 週五 00:38 寫道：

**Comment by Jay-Tarzan** [comment]
thanks very good

**Comment by KamiyaMinoru** [comment]
Anyay if it can use jpg as extension it will be accpted by more viewer (browser).
