### ISSUE TITLE
suggestion: add QR-Option to "after upload" Window

### ISSUE THREAD

**Issue by yasuoiwakura** [ShareX/ShareX#5841]
I may nede the QR code in 1 of 20 cases so i won't open if every time.
Opening it from the "after upload" menu would make it available in case you need it

**Comment by Jaex** [comment]
> Opening it from the "after upload" menu

"after upload" menu already have it:

![](https://jaex.getsharex.com/2021/09/ShareX_vXAb5zzzD8.png)

**Comment by yasuoiwakura** [comment]
> 
> 
> > Opening it from the "after upload" menu
> 
> "after upload" menu already have it:
> 
Yes, but you'd have to enable it BEFORE doing a screenshot if you want it.
And if you enable it always then you ALWAYS have another window wich needs to be closed.

So it's possible but not as handy/ergonomic as the rest of the tool :-)
