### ISSUE TITLE
Error in history

### ISSUE THREAD

**Issue by BodyDub** [ShareX/ShareX#5842]
Got this error (can't copy/paste).

https://i.imgur.com/GUahzDS.png

**Comment by L1Q** [comment]
Perhaps the file it can't read is on a could storage or a shared folder?

**Comment by L1Q** [comment]
Error message in English is "The Cloud File provider is not running".
It is thrown [here](https://github.com/ShareX/ShareX/blob/837ef0a7fcc3cd729b03e0c7aa17873e57292b86/ShareX.HistoryLib/HistoryManager.cs#L58)
