### ISSUE TITLE
Auto selection doesnt work

### ISSUE THREAD

**Issue by heartydegree** [ShareX/ShareX#5843]
on my last pc it worked flawlessly however on this ASUS ROG Zephyrus G14 GA401QM-HZ087T it simply screenshots whole screen without dashed guides magnetting to selected window

**Comment by L1Q** [comment]
Check your Task settings -> Region Capture -> Detect window regions and allow cursor hover capture.

**Comment by EinsKatze** [comment]
> Check your Task settings -> Region Capture -> Detect window regions and allow cursor hover capture. Even better if you can transfer setting from your previous computer.

I have the same issue as @heartydegree even tho i have this option enabled.

**Comment by joshualyon** [comment]
Check if you have any apps that have an invisible overlay -- for example, it sounds like recent Nvidia Driver updates include an always-on transparent window that sites on top of everything else as [noted in this issue](https://github.com/ShareX/ShareX/issues/6147).
