### ISSUE TITLE
suggestion: Decoding QR code from the webcam

### ISSUE THREAD

**Issue by brain8891** [ShareX/ShareX#5844]
As the title says, decoding QR code from webcam as well.

Thank you for ShareX <3

**Comment by yesBad** [comment]
Use your built in camera app and then use ShareX?

**Comment by brain8891** [comment]
> 
> 
> Use your built in camera app and then use ShareX to read it?

Yes that is a good workaround, I actually do that, but it is several extra steps, hence the suggestion.  I hope it is possible 🤞 and @jaex agree
