### ISSUE TITLE
Windows 11 Could not find file

### ISSUE THREAD

**Issue by brianmingus2** [ShareX/ShareX#5846]
![image](https://user-images.githubusercontent.com/76971633/134786002-548ae2bd-f504-4c15-b267-8b1be43c45b9.png)

**Comment by Jaex** [comment]
Most likely something in your computer is blocking ShareX, such as anti-virus software. Therefore ShareX is unable to create directory. Nothing we can do about it if your computer not allows ShareX to create directory.

**Comment by brianmingus2** [comment]
Closing this ticket is premature. You should look into it. The behavior is due to Windows Defender on Windows 11. You will lose all of your Windows customers if it doesn't get fixed.

**Comment by brianmingus2** [comment]
Ask for a whitelist!

**Comment by McPringle** [comment]
I have exactly the same problem. I have a Windows 11 standard installation, no additional firewall or anti-virus. Result: ShareX is not compatible with Windows 11. Sad... :-(

**Comment by McPringle** [comment]
I found ShareX in the Microsoft Store. That version works on Windows 11. The download version does not. My problem is solved, but ShareX on Microsoft Store was a chance find. I have been looking for an alternative program. Many will give up on ShareX if it doesn't work after downloading and will use another software (e.g. Greenshot). That would be a pity.
