### ISSUE TITLE
Write "date taken" information

### ISSUE THREAD

**Issue by zhang-rite** [ShareX/ShareX#5852]
Hi ShareX developer

Thank you for your nice contribution. 
Is there an option for writing `"date taken"` information with a screenshot, like in camera-taken photos?
I want to save screenshots in Amazon photos and let them be in order as aligned in default by "date taken" information.

Thank you!

**Comment by zhang-rite** [comment]
@L1Q, thanks. What I needed is not file naming, but a meta property of pictures--"date taken" indicating when the photo was taken (not created or modified time too). The captured pictures saved by Windows's Snipping tool have this property.

![image](https://user-images.githubusercontent.com/68037967/135550367-6f317b59-7a4c-4e28-b8e1-0df2f1a2b17c.png)

**Comment by Jaex** [comment]
> The captured pictures saved by Windows's Snipping tool have this property.

I tried both Snip & Sketch and Snipping Tool but saved file had date taken field empty.

**Comment by geofiber** [comment]
I have tried add `date taken` for jpg using `exiftool` as follows. 
 ```shell
exiftool -overwrite_original  '-DateTimeOriginal<FileCreateDate' DIR
```
However, I hope ShareX can do this in default.
