### ISSUE TITLE
The screen recording ffmpeg custom settings bug!

### ISSUE THREAD

**Issue by c3m0** [ShareX/ShareX#5853]
Well, this has been addressed for years but no one has taken it serious, but I think it is, 'cuz it's really confusing to start a video screen recording with custom FFmpeg settings as it is right now. See these two old topics on this (not resolved) issue.

https://github.com/ShareX/ShareX/issues/4614
https://github.com/ShareX/ShareX/issues/4350

Please, look into it! 🙏

Steps to reproduce:
1. Have "Record using lossless encoding and then apply user encoding options" ticked!
2. Have "Use custom commands" ticked, with just any command (you can even keep it untouched)

That's it, now try the e.g. SHIFT+PrtScr hotkey, pick a window/whole screen, press "Start" (or SHIFT+PrtScr again) and then stop, and you'll notice that the "Encoding" status in the system tray will stay lit and never(!) go away, but when you click it again it vanishes quickly. What happens under the bonnet is that it _starts_ recording when you stop, and then finalizes when you simply press the "Encoding..." in the system tray.

I'm running latest ShareX (v13.6.1) and have tried different ffmpeg.exe binaries as well, to no avail.

This _can't_ be "technical design", can it?
It must be consider a bug!? 🤔

**Comment by 57382** [comment]
+1
I have the same problem.

**Comment by Aholicknight** [comment]
having the same problem
