### ISSUE TITLE
Converting to SDK-style projects

### ISSUE THREAD

**Issue by Droppers** [ShareX/ShareX#5858]
A first step (if ever feasible) of supporting .NET core would be to convert the current csproj files to the newer SDK-style project format.

**Benefits**
 - Better readability
 - All files are included by default
 - No more packages.config

https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview

A tool that can assist with converting to the newer SDK-style project has been released by Microsoft. The description is confusing, other than porting to .NET 5 it can also convert csproj files without upgrading to .NET 5.
https://dotnet.microsoft.com/platform/upgrade-assistant

I might make an attempt at this if I have some spare time in the future unless there are good reasons why not to do this, let me know!

**Comment by Jaex** [comment]
We are planning to move to .NET 6 in 2022. We are waiting for Visual Studio 2022 and .NET 6 stable release.

**Comment by Droppers** [comment]
I understand, but a first step of that journey could be converting to SDK-style projects to not have to do it all at once, since I am sure porting to .NET 6 will be quite the work itself already.

The SDK-style project format is not related to .NET core.

**Comment by yfdyh000** [comment]
> We are planning to move to .NET 6 in 2022. We are waiting for Visual Studio 2022 and .NET 6 stable release.

Any news?

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/blob/develop/ShareX/ShareX.csproj
