### ISSUE TITLE
ShareX and IPFS  Support

### ISSUE THREAD

**Issue by yeehi** [ShareX/ShareX#5860]
It would be wonderful to be able to use ShareX to publish to IPFS (Inter Planetary File System):
https://ipfs.io

Supporting IPFS on ShareX would help develop a culture where images were hosted redundantly hosted and served in a distributed fashion, instead of at centralized sites.

There is already some Free Software code for this sort of publishing, for example, Brave Browser now has integrated ipfs support. There are some other ipfs projects which might be helpful:

# ipfs-screencap
https://github.com/jbenet/ipfs-screencap

# ipfs-companion
This has some lovely functionality
https://docs.ipfs.io/install/ipfs-companion/

# ipfspics-server
The site is still available so you can see the interface
http://ipfs.pics/
https://github.com/ipfspics/ipfspics-server

**Comment by Jaex** [comment]
I opened http://ipfs.pics/trending but images not even loading there:

![](https://jaex.getsharex.com/2021/10/chrome_xWPlEv0wnM.png)

**Comment by yeehi** [comment]
@Jaex - Thanks for looking at this. The ipfs.pics project was deprecated in favour of functionality now integrated into ipfs-companion, a browser extension. That is why people aren't using it to pin pictures these days.  
  
ipfs-companion is here:
https://github.com/ipfs/ipfs-companion#access-frequently-used-ipfs-actions-from-your-browser-bar
