### ISSUE TITLE
"Upload with ShareX" compresses jpeg quality very badly

### ISSUE THREAD

**Issue by asherbasher** [ShareX/ShareX#5862]
Image uploaded directly to imgur: https://i.imgur.com/uG0BNp7.jpg
Image uploaded through ShareX: https://i.imgur.com/t3rJoOt.jpeg

Is there a way to make ShareX just upload the image directly instead of compressing it so much?

**Comment by Jaex** [comment]
If this option is false then it should upload image as it is without re encoding:

![](https://jaex.getsharex.com/2021/10/ShareX_CAQsEAcdwa.png)

**Comment by asherbasher** [comment]
It's already set to false:

![image](https://user-images.githubusercontent.com/10160470/135902760-905028b8-0595-44df-8aff-9d07f7fceb52.png)

**Comment by Jaex** [comment]
You told ShareX is compressing the image so much but I tested it now and Imgur compressing it not ShareX.

**Comment by asherbasher** [comment]
But you can see the comparison I posted between uploading it myself to imgur and uploading it through ShareX... How does that make sense?

**Comment by Jaex** [comment]
You are not using Imgur API.

**Comment by asherbasher** [comment]
Oh ok, so it can only be fixed from their side?

**Comment by Jaex** [comment]
Yes.
