### ISSUE TITLE
13.1 Update bug

### ISSUE THREAD

**Issue by Gijs-schouten** [ShareX/ShareX#5866]
Hi everyone, I dont know if this is the right place for this issue but ever since update 13.1 I've been getting a launch notification to update to the latest version. Im fully up to date but the update pop up seems to think im not.

![](https://i.imgur.com/kHSBrqn.png)

**Comment by Gijs-schouten** [comment]
I'll reinstall the program to fix this issue but I still tought it is something noteworthy.

**Comment by Jay-Tarzan** [comment]
BUK
