### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by pixeldesu** [ShareX/ShareX#5868]
After updating to Windows 11 tonight, following issue has been coming up when trying to upload an image to a custom file uploader.

Error log:
```
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://desu.pictures/upload?username=[redacted]&password=[redacted]

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

I checked with the other issues reporting for the same kind of error message, but those weren't really helpful.

Just a day before, on Windows 10, everything worked just fine. So, there haven't been any server-side/certificate updates since that could have prompted connection failures like that.

----

To be sure it's not host related, I used a REST/API client (https://insomnia.rest) against the upload endpoint, successfully returning a file URL.

----

Windows/Build Info:
* OS: Windows 11 Pro
* Version: 21H2
* Build: 22000.194
* Experience: Windows Feature Experience Pack 1000.22000.194.0

**Comment by Jaedotmoe** [comment]
Same when uploading pics to my S3 server.

Same version of Windows 11 Pro (21H2).
