### ISSUE TITLE
Update Capture Support Windows 11 ?

### ISSUE THREAD

**Issue by chuongmep** [ShareX/ShareX#5869]
Hi Team, whether we have any update for support Windows 11 with some window radius border ?
![image](https://user-images.githubusercontent.com/31106432/136136342-a2ee7aef-25f7-4d46-9025-d6c4f13c574d.png)

**Comment by Void48** [comment]
Please, we really need this 🤲

**Comment by worldsdream** [comment]
Really need this!

**Comment by Tragen** [comment]
This is only stale because it's not fixed

**Comment by chuongmep** [comment]
Hmm, I don't know they don't fix it and close this isssue :(
