### ISSUE TITLE
Right-click edit with shareX does NOT open the image in front

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#5870]
Everything was working as expected in Windows 10, but in Windows 11 it's not.

When you have a picture and you right-click it and select "Edit with ShareX". It does open the image, but not in the front. It's in the background, behind other windows.

Can this please be fixed?

**Comment by Jaex** [comment]
This issue also happens in Windows 10 but it is failing randomly to bring window to front.
Normally when window is opened, it should show at front but still in shown event of the form I force it here:

https://github.com/ShareX/ShareX/blob/master/ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs#L493

Which calling this extension method:

https://github.com/ShareX/ShareX/blob/master/ShareX.HelpersLib/Extensions/Extensions.cs#L346

Yet even with these efforts still for some reason randomly it not moving window to front and I'm unable to figure out why. And this happening randomly also makes it difficult to debug.
