### ISSUE TITLE
ffmpeg required in tools folder -> allow setting path

### ISSUE THREAD

**Issue by vertigo220** [ShareX/ShareX#5878]
Instead of requiring ffmpeg.exe in the tools folder, it would be better to add a setting in the paths part of options to set the path to it elsewhere. This way, it wouldn't require having multiple copies of it, which would take less space and be easier to update.

**Comment by Jaex** [comment]
You can already change path from here:

![](https://jaex.getsharex.com/2021/10/ShareX_YWVoKokWMI.png)

**Comment by vertigo220** [comment]
Ah, thanks, and sorry about that. I dug through the settings multiple times and still missed that.
