### ISSUE TITLE
Rotating capture box in region capture 

### ISSUE THREAD

**Issue by MW-J97** [ShareX/ShareX#5880]
Hi,  
Is there a way to add this rotating sign in the capturing box to rotate before capturing??
Thanks in advance. ❤
![12_10_2021 18_11_58_491](https://user-images.githubusercontent.com/73688266/136992662-d4d687ae-0868-41d4-9834-61053e766b1d.png)

**Comment by yashpalgoyal1304** [comment]
i have thought about suggesting that several times, but i guess it is kinda complicated task....

**Comment by MateusAuri** [comment]
+1 this.
Like yashpalgoyal1304 said, I'm afraid it might be hard to implement, but having the ability to freely rotate objects (not only the capture box, and not only in 90° intervals) in the region capture mode would be really useful.
