### ISSUE TITLE
Resizing of watermark image not correctly working

### ISSUE THREAD

**Issue by UltraHQ** [ShareX/ShareX#5882]
When choosing SizeMode: Percentage of image, to auto resize watermark image based on screenshot resolution, it starts to fail on smaller screenshots.

**Example of it working fine:**
![chrome_11wkZnwqF6](https://user-images.githubusercontent.com/35925402/137009156-82b7f692-dead-4500-83f6-284605ecee28.png)

**Example of it failing:**
![image](https://user-images.githubusercontent.com/35925402/137009253-0f4d1062-266b-47ca-8828-6007d7e06bd9.png)

**Comment by Jaex** [comment]
"Percentage of **image**" means the image that you added, not the source image which is called canvas there. So you must use "Percentage of canvas" to accomplish what you want.
