### ISSUE TITLE
Can not upload to youtube sometimes

### ISSUE THREAD

**Issue by dimmduh** [ShareX/ShareX#5888]
![image](https://user-images.githubusercontent.com/446814/137432123-937cd268-5baf-43d9-bcae-c0c45c242d7c.png)

auth was resynced
check auth button says - fine
13.6.1

**Comment by PhilippVujic** [comment]
I'm not able to upload videos today too. So they might have changed something in their API

**Comment by dimmduh** [comment]
How about register multiple accounts and select random on upload?

**Comment by andrewkm** [comment]
> Our YouTube API quota is reach to limit and I can't request increase to it without pay money looks like:
> 
> ![](https://camo.githubusercontent.com/a971f6b0669e9ff230522ad4be5105d2532eb09c4b81d6fdeda60d2f36673c32/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f31302f6368726f6d655f4e55574459725248494c2e706e67)

So link it to a billing account, and let us donate to you. :)

**Comment by dimmduh** [comment]
I can not able upload to youtube for 2 weeks already.
Please do something, or let us put own api key in settings (but it's not good solution)

**Comment by Jaex** [comment]
I'm waiting response from Google.

**Comment by FerLuisxd** [comment]
Is there a way for us to link our own google developer accounts?

**Comment by Jaex** [comment]
Google replied now and denied our quota extension request with a lot of reasons listed:

![](https://jaex.getsharex.com/2021/11/FK6ZU0Bq2s.png)

and I have no clue how to solve most of these...

**Comment by dimmduh** [comment]
I ask again. Why not just register multiple accounts and select random on upload?
Custom api key options - it's not solution for everyone.

**Comment by andrewkm** [comment]
What dimmduh said above ^
Please find a work around, or work through Google's requirements.
Reading over their email, they do not seem difficult at all, a good days work of implementing random terms of service and minor changes.

**Comment by Jaex** [comment]
> Reading over their email, they do not seem difficult at all, a good days work of implementing random terms of service stuff and other changes.

I already did that after post here. So we are waiting their reply.

**Comment by Jaex** [comment]
YouTube replied now, they again sent same violations...

**Comment by andrewkm** [comment]
Please link the commits where you actually implemented these requirements, we'd love to look over them.

**Comment by Jaex** [comment]
What you mean implemented? ShareX client already allows writing actions (uploading) to YouTube with more than 10 different methods which we listed them in email reply. ShareX also have perfect implementation of OAuth so there is no problem with authorization too. So we don't know what we must implement. We don't even know what is "Authorized data is shown to non authorized users" even means...

**Comment by andrewkm** [comment]
Have you sent them an updated video as they requested?

**Comment by Jaex** [comment]
> Have you sent them an updated video as they requested?

They requested it new, so I did not reply their email and record new video yet. It takes long time for me to write reply email because my english is not very good. Getting help to write that privacy policy page took 5 days too.

**Comment by andrewkm** [comment]
If you need help with editing any sort of formal email feel free to reach out to me via Discord, I will edit/proof read anything you need.

**Comment by Jaex** [comment]
Finally YouTube replied now and they confirmed that quota is increased to 3m. It was 1m before.

**Comment by andrewkm** [comment]
Great work!

**Comment by dimmduh** [comment]
Great! thx, see you in 2022 )

**Comment by adi-rebellion** [comment]
> Finally YouTube replied now and they confirmed that quota is increased to 3m. It was 1m before.

Its still not uploading any videos for me.  Is there a way that I can get my own key / account and use it with my own instance of sharex. Seems like there are too many users of sharex so we are exhausting the quota almost immediately. 

Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://www.googleapis.com/upload/youtube/v3/videos?part=id,snippet,status

Status code:
(403) Forbidden

Headers:
X-GUploader-UploadID: ADPycdshZSUWraSnSH5u0q5_rhtngiasmRV41kGiP6i4DGb38-oSlqZHkE3MegfDzC0RqZWdQL36EQ78rzoQ2_S1ekY
Vary: Origin,X-Origin,Referer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 306
Content-Type: application/json; charset=UTF-8
Date: Thu, 02 Dec 2021 16:52:57 GMT
Server: UploadServer

Response text:
{
  "error": {
    "code": 403,
    "message": "Access forbidden. The request may not be properly authorized.",
    "errors": [
      {
        "message": "Access forbidden. The request may not be properly authorized.",
        "domain": "youtube.common",
        "reason": "forbidden"
      }
    ]
  }
}

**Comment by andrewkm** [comment]
I am uploading just fine.

**Comment by dimmduh** [comment]
Limits exceeded again

`Error message:

Request URL:
https://www.googleapis.com/upload/youtube/v3/videos?part=id,snippet,status

Status code:
(403) Forbidden

Headers:
X-GUploader-UploadID: EBy
Vary: Origin,X-Origin,Referer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 465
Content-Type: application/json; charset=UTF-8
Date: Fri, 29 Apr 2022 06:12:31 GMT
Server: UploadServer

Response text:
{
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}


Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)`

**Comment by Jaex** [comment]
Not again! It takes month of efforts to make them increase the quota.

**Comment by Jaex** [comment]
I did few changes in quota settings, lets see is it gonna happen again tomorrow.

**Comment by crannofonix** [comment]
I've also tried uploading some videos yesterday. Some of them uploaded, some of them failed
<img width="555" alt="5uUfmK2JP" src="https://user-images.githubusercontent.com/92416370/166096047-5e82bd95-16e3-4e7f-a7cd-19a608b3fdaf.png">
.

**Comment by crannofonix** [comment]
Update: it's still uploading SOME of the videos

**Comment by Jaex** [comment]
I set limit to upload amount to not exceed quota. So if it is failing for you, that means you uploading videos so rapidly. If I remove the limit then one person single handedly filling the whole quota.

**Comment by andrewkm** [comment]
People shouldn't be uploading so fast to YouTube, please hard limit people in shareX so this nonsense stops. I don't understand how someone can make so many videos unless they are spamming.
