### ISSUE TITLE
Capture region issue with Minecraft

### ISSUE THREAD

**Issue by xiUnknown1** [ShareX/ShareX#5892]
As seen here, the first capture is wrong / delayed

https://user-images.githubusercontent.com/84973878/137633594-4fc5cc19-e809-425b-aec2-8ad13f91669f.mp4

**Comment by SkrillzPlayz** [comment]
Same issue / delayed capture when in borderless windowed fullscreen via [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming) and [Borderless Minecraft](https://github.com/Mr-Technician/BorderlessMinecraft) while both applications sets Minecraft to borderless fullscreen and allow other windows over Minecraft with no issue, have not had this issue with other games. The closest/best alternative I could find is to have it in borderless windowed with visible taskbar and I can take screenshots with no issues. (Tested in both 13.6.2 stable and dev)

**Comment by Morabert** [comment]
I play in Borderless & it doesn't work _at all_
In general I have trouble with the printscreen hotkey, it doesn't work reliably ever. I've gone & looked for replacements for ShareX as a result.
