### ISSUE TITLE
[Feature Request] ability to reset the step counter in the same screenshot

### ISSUE THREAD

**Issue by dant171** [ShareX/ShareX#5894]
Hi,
I can't find requests for this function. 
But I think being able to reset the numbering when using the step counter would be good.

my workaround is to do a nested screenshot (screenshot inside a screenshot) or edit the image and add new counters.

thanks

**Comment by Taroslord** [comment]
Same here. For me this would be also a nice feature.

**Comment by Taroslord** [comment]
I don't understand why this feature request was closed.
We still miss the feature to create multiple counter lists, please.

My proposal:
1. Every new counter list can be added by pressing CTRL-key. The counter starts again at "1" then or/and use the current step value and settings.
2. To change the recent created step lists you just cklick on the a number in a row to activate the step list to be edited and can change the settings then as always.

What do you think?

Regards
Chris
