### ISSUE TITLE
Image Editor Alignment

### ISSUE THREAD

**Issue by JonathonAnderson** [ShareX/ShareX#5897]
I started having an issue with ShareX where the cursor in the image editor is not appropriate for the region it's in. 

When trying to draw, for example, a box, I instead see the corner resize cursor, and click and dragging resizes the window. 
![image](https://user-images.githubusercontent.com/49241459/138018783-618bf1e2-09eb-4c7a-b6cc-7d3033c5e94d.png)

If I position my cursor in the wrong area of the editor, where the screenshot is not, I can draw arrows.
![image](https://user-images.githubusercontent.com/49241459/138018796-67349a60-c91d-4b90-8ba5-78c65e5c2eb1.png)

I have uninstalled and reinstalled ShareX, and I deleted the backup and configuration files between installs of ShareX.

Any help is appreciated!

**Comment by JohnicBoom** [comment]
I see this was marked as completed, but I experience this exact behavior on ShareX 17.1. I'm on Windows 11 24H2, using 2 external monitors (next to each other above my laptop) and my laptop monitor. If I edit an image using the left external monitor, editing tools will instead resize the window in certain regions of the image. If I move the same editing window to the right external monitor, I get the normal editing tool behavior with no window resizing. 

You can see the video @JonathonAnderson posted in October 2021 to see what I'm talking about. When the icon changes to the double-ended arrow, clicking and dragging will resize the window. When the icon changes to the crosshair, clicking and dragging will draw the selected editing tool shape.
