### ISSUE TITLE
Add possibility to rearrange main window columns by drag'n'drop 

### ISSUE THREAD

**Issue by Anlini** [ShareX/ShareX#590]
![image](https://cloud.githubusercontent.com/assets/4973581/6940264/c002d602-d87d-11e4-99be-4c13de04a0c4.png)
And disable some of them like at the windows explorer and almost every PC app with columns. 
![image](https://cloud.githubusercontent.com/assets/4973581/6940272/db6939d6-d87d-11e4-854d-2391dba8bef0.png)

**Comment by Jaex** [comment]
.NET listview control not supports drag and drop of columns therefore can't make it.

**Comment by Jaex** [comment]
I noticed .NET allows re ordering columns but still be able to hide them etc. will require alot of efforts and not worth the effort.

**Comment by Anlini** [comment]
Maybe can you add possibility to show image preview at the bottom?
![2015-04-01_15-00-58](https://cloud.githubusercontent.com/assets/4973581/6940652/97513b5a-d881-11e4-815c-384832f0663d.png)
