### ISSUE TITLE
Error uploading to YouTube (Quota exceeded)

### ISSUE THREAD

**Issue by onionlogger** [ShareX/ShareX#5907]
Hi it seems this has been an issue in the past and you increased your quota limit as a fix. But the issue seems to be back since last Friday:

Error message:
Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig.

Request URL:
https://www.googleapis.com/upload/youtube/v3/videos?part=id,snippet,status

Status code:
(403) Forbidden

Headers:
X-GUploader-UploadID: ADPycdtuKZH_xiWXTuAxVcSD5YsQQlXEGtwDj9dBH6bLs_R6GDbcnKtlJ7Vvikpkd-EdRfupK_g3Jkgyp4o18GQHILgI9BcDoA
Vary: Origin,X-Origin,Referer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
Content-Length: 465
Content-Type: application/json; charset=UTF-8
Date: Mon, 25 Oct 2021 14:02:45 GMT
Server: UploadServer

Response text:
{
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}

Stack trace:
   bei System.Net.HttpWebRequest.GetResponse()
   bei ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by andrewkm** [comment]
Same thing here:

`Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://www.googleapis.com/upload/youtube/v3/videos?part=id,snippet,status

Status code:
(403) Forbidden

Headers:
X-GUploader-UploadID: ADPycdu5sgDadigzCJxF41em9nwRwkKk70chSZ6usyNaj588d7T8O3X2IWQRAbAOk9AcfTcBNYInbJQeQ5j-FoVHYUaUJY9u2g
Vary: Origin,X-Origin,Referer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 465
Content-Type: application/json; charset=UTF-8
Date: Mon, 01 Nov 2021 02:56:53 GMT
Server: UploadServer

Response text:
{
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)`
