### ISSUE TITLE
After capture tasks not working properly

### ISSUE THREAD

**Issue by SuperCC25** [ShareX/ShareX#5908]
Hey there,

I have the copy to clipboard and open editor options checked, but in this specific scenario, the image recently captured does not get copied to my clipboard. It otherwise works very well, it seems like a race event conflict for this specific scenario or something.

![lP4IZQHgCO](https://user-images.githubusercontent.com/62890467/138717133-d437ffa7-41c6-4ddc-9fce-b485931b29a6.png)

Using latest version on Windows 10.

Thanks in advance!

**Comment by DeveloperBlue** [comment]
Happened again trying to capture a Chrome window. Seems to be that the capture is too large, and if I keep making smaller snippets, eventually it decides the size is okay and saves it to the clipboard.

**Comment by SuperCC25** [comment]
Thanks for your input. On my end, it NEVER copies it to clipboard, no matter how small the capture region is.
