### ISSUE TITLE
Image editor arrow bug

### ISSUE THREAD

**Issue by Anlini** [ShareX/ShareX#591]
It doesn't show selected option of the "draw arrow" tool
![2015-04-01_14-49-53](https://cloud.githubusercontent.com/assets/4973581/6940338/8498a47e-d87e-11e4-8684-b4db320828d7.png)

**Comment by Jaex** [comment]
Is it same in Greenshot software too? Because we are using their image editor.

**Comment by Anlini** [comment]
Yes

**Comment by Jaex** [comment]
If Greenshot software has this problem too then you should report to their issue tracker.
