### ISSUE TITLE
Please add Linux Support!!!

### ISSUE THREAD

**Issue by zontreck** [ShareX/ShareX#5912]
After its becoming impossible for me to upgrade my 2 year old computer to Windows 11, i am dropping windows and switching to Linux, and i am asking, please, please add Linux support.

**Comment by demirdegerli** [comment]
> As I'm sure has been said many times in this issues section, ShareX makes heavy use of many Windows-only APIs (.net and otherwise). You could try wine or something but there is no way (without a major rewrite and loss of functionality) that ShareX can just up and support Linux.
> 
> EDIT: for more info see #498

There is not a major loss of functionality nowadays in Linux, here's an easy guide: #6531
