### ISSUE TITLE
ShareX might have got me suspended in Eve Online for macro use

### ISSUE THREAD

**Issue by enkeyz** [ShareX/ShareX#5913]
If I know correctly, game developers can detect if the mouse input is physical or artificial. Does this application use some kind of mouse hook?

I just got suspended for 3 days, after using this screenshot app, and it was the only program running besides the game.

**Comment by ryantaylorr** [comment]
That's strange. As a fellow EVE player, I've used ShareX on my machine for years while also playing EVE and have never had an issue to this date.

**Comment by enkeyz** [comment]
You know I don't really know what exactly got me banned, because you know how CCP is: "We don't share any evidence".

But ShareX was the only app I didn't use before.

**Comment by 10by10pixel** [comment]
I wouldn't call myself an EVE online player but I was unable to recreate this issue as a long time ShareX user
