### ISSUE TITLE
Rfc2898DeriveBytes does not contain a constructor that takes 4 arguements.

### ISSUE THREAD

**Issue by vraddev** [ShareX/ShareX#5914]
Hello, I've been trying to compile Share X's src and I've had one problem in Vault_ooo.cs which is the following code having an error:
`Rfc2898DeriveBytes rfcDeriver = new Rfc2898DeriveBytes(key, salt, PBKDF2_ITERATIONS, HashAlgorithmName.SHA256);`

**Comment by poszer** [comment]
Reopen please. 
 
![Reopen](https://user-images.githubusercontent.com/41213210/142035629-d85f9fa6-2207-460d-bd12-26a7519b7955.png)
