### ISSUE TITLE
No option to install .sxie from portable version of ShareX

### ISSUE THREAD

**Issue by WirlyWirly** [ShareX/ShareX#5922]
Hello,

This problem is pretty self-explanatory, I've been unable to install .sxie using the portable version of ShareX. The Image Effect webpage just says to double click on the .sxie file, but this implies ShareX is installed and will open .sxie files by default. For portable usage, this is not the case.

I've tried opening the file with ShareX, but it just shows the upload file screen. I've tried moving the .sxie file to the "ImageEffects" folder but it's not detected.

Am I missing something or is there no "Import .sxie" from within ShareX?

Also, is there a normal shadow border .sxie? No fancy colors or anything, just a black glow to imply it's floating. I'm surprised one hasn't been created yet and I haven't been able to make one.

**Comment by Jaex** [comment]
You can drag n drop .sxie file to image effects window to import it.

**Comment by acc8226** [comment]
> You can drag n drop .sxie file to image effects window to import it.

Hidden enough, I think it is necessary to add an import button.
