### ISSUE TITLE
Feature Request: Support custom command line tools to upload image 

### ISSUE THREAD

**Issue by Shazoo** [ShareX/ShareX#5933]
Hi ,  developer :

Thanks for the wonderful tool at first . 

I noticed the shareX's "custom uploader setting" is very powerful , but my personal image storage uploader api is based on the oauth method and the current "custom uploader setting" can not support this kind of method . 

I think if ShareX will support custom command line to help user to use more image/file storage service? there are a lot of powerful command line tools , such as picgo-core ..etc ,  and ,  some tools support these command line tools now , such as Typora .. etc . 

A simple uploader parameter-pass-rule reference document : https://support.typora.io/Upload-Image/#custom , it's useful enough for uploader . 

Thanks again .

**Comment by LeonT-A** [comment]
+1, I'd love to see some command line options to pass image files to edit/upload as well as capture.
