### ISSUE TITLE
Instantly opening Image Editor with empty image

### ISSUE THREAD

**Issue by rfgph** [ShareX/ShareX#5934]
Hi is there a way to bypass these 3 steps and open an empty image with predefined size directly in image editor? 
For example something like this `ShareX.exe -ImageEditor --size 600 600`

![ShareX_dO1mcFfnMK](https://user-images.githubusercontent.com/93509358/141098066-aabc951d-1e92-453e-a25a-aed01f281f20.png)

**Comment by guido-visser** [comment]
Could this be expanded to add `ShareX.exe -ImageEditor --fromClipboard` as well, so that I can trigger this from my Stream Deck? Much appreciated!
