### ISSUE TITLE
The default log and configuration files location is not ideal, especially when the user Documents directory is synched between multiple computers running ShareX

### ISSUE THREAD

**Issue by vnicolici** [ShareX/ShareX#5936]
The "Documents" user directory on all my 3 computers is synched via OneDrive, which also keeps a copy in the cloud. Many people have a similar setup, since this is a Windows 10 feature, and you have the choice to enable it when you install Windows 10.

Besides the obvious advantage of having your files accessible on every computer, you also have a backup copy in the cloud, and you can even revert unwanted changes if needed, since the change history is kept in the cloud. There is also protection against accidentally deleting a large number of files, and it also helps with restoring the damage done by ransomware malware.

The only downside is that applications that keep configuration files, logs, scratch files and other temporary files in the Documents directory, which is not designed for this purpose, can become extremely annoying. ShareX is one of them.

First of all, by writing temporary files to a directory that should only store user files, it causes unneeded internet traffic to synch those files to the cloud. Then those files are also replicated on my other computers for no reason. And, in the case of ShareX, that replication also causes conflicts, because the daily log files from each computer have the same name. Which causes OneDrive to give me warning such as this one a couple of times a day:

![image](https://user-images.githubusercontent.com/2158971/141293956-6c66c719-1039-432b-bed3-3397d6f05fcf.png)

Needless to say, that is quite annoying. And similar conflicts can and do happen when I change the ShareX configuration.

There is a dedicated directory on Windows computers for local application files: %LOCALAPPDATA% which points to AppData\Local under the user directory. Alternatively, there is a %TEMP% variable pointing to a subdirectory of it, AppData\Local\Temp. These are the locations where local application data files, configuration files, log files and application temporary files should be stored, in my opinion. The actual screenshots can remain in the Documents directory, but all the other stuff, configuration files, log files, shouldn't be there.

Alternatively, there is a %APPDATA% directory that points to AppData\Roaming under the user directory, which can be used if the files needs to be synched between computers by the roaming user profiles feature in combination with Windows Servers / Domain Controllers. I don't think that's necessary for the ShareX configuration files, but it's debatable. Some people might want that. In any case, I see even less reason to use this location for logs, the %TEMP% location or at most the %LOCALAPPDATA% location is probably ideal for them.

This is the mess storing them in the Documents directory creates, in combination with OneDrive:

![image](https://user-images.githubusercontent.com/2158971/141293908-dc53336b-ebea-4dbb-9230-7537617574d1.png)

![image](https://user-images.githubusercontent.com/2158971/141294221-8b37090a-67f1-4a9b-8b46-1f7705c90b0f.png)

Each of the files having a computer name attached is the result of a conflict. And it doesn't happen just for log files, but also for the configuration files, as you can see. That's because OneDrive resolves the conflict by creating a copy of the conflicting file with the computer name that changed it remotely attached. If conflicts keep happening, it also appends a counter to the file name. So I end up with a lot of useless files synched between my computers. Which, as I mentioned before, is not ideal.

**Comment by allan2** [comment]
I am running into a similar thing.

My goal is to sync my ShareX settings between computers using OneDrive.

Some of the JSON config files are constantly deleted and recreated.

It would be nice to have a base set of configs that live in *Documents/ShareX* with machine-specific configs put somewhere else.

Something like this:
1. Documents/ShareX/config.json  <-- base config for global settings
2. Documents/ShareX/config-machine1.json  <-- loaded for machine 1 only
3. Documents/ShareX/config-machine2.json  <-- loaded for machine 2 only

**Comment by adam-wood** [comment]
One workaround would be to put the computerName into the log filename. This would remove the OneDrive conflict issue. I would be happy to have the option to disable logging

There would still be the issue of the settings file. My preference would be to have settings in sync across multiple machines. 

Maybe ShareX doesn't need to lock the settings file(s) while open? That way changes made to settings on machines sharing the same synced folder would just overwrite? If that is undesirable, then maybe ShareX could detect if the settings file is in use from an instance on a separate machine and treat settings as 'read only'. I appreciate there are implications to all these approaches.

**Comment by allan2** [comment]
I'd like to see both all-hosts settings and host-specific settings supported.

For example, my Screenshots folder might be on D:\Screenshots on one machine but C:\Screenshots on another, so I would like the screenshots folder to be an overridable setting.

**Comment by nibblerrick** [comment]
I really would like to see this supported, too.
I am running into the same issue.

**Comment by Keith94** [comment]
See #6130

**Comment by verbal007** [comment]
Agreed, running into this problem as well. Wish there was another way.

**Comment by verbal007** [comment]
> See #6130

Thx!  This will work for my purposes.

**Comment by danangua** [comment]
I have same issue, disable logging is a feature I would like to see.
