### ISSUE TITLE
copy url to clipboard not working after annotate

### ISSUE THREAD

**Issue by karb10** [ShareX/ShareX#5938]
after annotate,i click upload image.its not copy url automatically to clipboard after upload
used imgur and uploadgram bot
after capture task : show quick task menu
after upload task: copy url to clipboard

![изображение](https://user-images.githubusercontent.com/31970765/141647442-5a4c0282-1a12-44eb-924f-a13a6a33da34.png)

**Comment by Jaex** [comment]
Is "copy url to clipboard" selected in your quick task menu task?

**Comment by karb10** [comment]
> 
> 
> Is "copy url to clipboard" selected in your quick task menu task?

thanks
