### ISSUE TITLE
Task for capturing specifing monitor

### ISSUE THREAD

**Issue by Gol-D-Ace** [ShareX/ShareX#594]
Currently you only have tasks for capturing all monitors / screens or the active one.
But you can't say hey please capture Monitor / Screen X.

**Comment by Jaex** [comment]
It is good idea but not sure how I should make it because I can't add multiple monitors to hotkey task list because it is from enum list. Maybe I should have specific monitor capture hotkey task and having hotkey number section somewhere in task settings.

**Comment by danielbrezoi** [comment]
I want to help out with this project and if it is OK with you, I'll make a version of this enhancement by adding an option in "Task settings/Capture" where the monitor can be selected and a new task option in task list named "Capture Specified/Selected Monitor".
Thanks.

**Comment by Jaex** [comment]
I was thinking it could be like this:

Drop down menu:
Monitor 1 (X: 0: Y: 0 Width: 1920 Height: 1080)
Monitor 2 (....)

Text boxes:
X: Y: Width: Height:

So when you select monitor text boxes gonna be set to that rectangle info and those will be saved to setting. That way it will also allow custom regions to be used other than monitor regions. So monitor order should not be saved to setting but region of them.

If you think you can do it properly then sure will be nice.

**Comment by danielbrezoi** [comment]
Now I'm studying the project so I can understand it.

Just to confirm that I understand correctly: 
1. In the Task settings/Capture I should add:
    1.1. A drop down menu to select the monitor;
    1.2. Two text boxes to select the region.
2. Add a new task in task list called: "Capture Custom Region".

I'll create a version trying to respect the style and the current architecture. 

Thanks

**Comment by danielbrezoi** [comment]
Can you pleas review what I have done until now and tell me what should be different.
Further, If the naming is correct, I want to implement the localization for my changes. 

Thanks.

**Comment by DARKFiB3R** [comment]
Did anything come of this?

Thanks
