### ISSUE TITLE
Cannot upload image to imgurl

### ISSUE THREAD

**Issue by omrumcetin** [ShareX/ShareX#5945]
We cannot upload image to imgurl. Here is stack trace : 

> Imgur upload failed: (417) Internal expectation failed
> 
> Error message:
> The remote server returned an error: (417) Expectation Failed.
> 
> Request URL:
> https://api.imgur.com/3/upload
> 
> Status code:
> (417) Expectation Failed
> 
> Headers:
> Connection: close
> X-Post-Rate-Limit-Limit: 1250
> X-Post-Rate-Limit-Remaining: 1247
> X-Post-Rate-Limit-Reset: 3278
> X-Ratelimit-Clientlimit: 12500
> X-Ratelimit-Clientremaining: 12500
> X-Ratelimit-Clientreset: 86400
> X-Ratelimit-Userlimit: 500
> X-Ratelimit-Userremaining: 500
> X-Ratelimit-Userreset: 3600
> Content-Length: 116
> Content-Type: application/json; charset=utf-8
> Date: Tue, 16 Nov 2021 12:11:33 GMT
> 
> Response text:
> {"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}
> 
> 
> Stack trace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by jjamesmartiin** [comment]
I'm looking into this issue; I will reply back with any additional info I find.

**Comment by jjamesmartiin** [comment]
I have not been able to replicate your issue, are you able to confirm it's still occurring @omrumcetin?

**Comment by omrumcetin** [comment]
Yes its still occuring, I can give you use case, extend your gif size more than 30 MB.

**Comment by Jaex** [comment]
GIF upload limit is 10mb.

**Comment by omrumcetin** [comment]
Imgurl says its 200 mb, go to help page.

**Comment by Jaex** [comment]
You go to api page.

**Comment by omrumcetin** [comment]
Okay then maybe you fix your error log with throwing “exceeding upload limit size”, if possible?

**Comment by Jaex** [comment]
Or maybe Imgur should fix their error message? Instead of returning `Internal expectation failed`, they should return `exceeding upload limit size`.

**Comment by omrumcetin** [comment]
Its your product, its your decision. Bye mate

**Comment by Jaex** [comment]
It is not my decision. They return same error message for countless other things and we can't know what is it for this time.
