### ISSUE TITLE
Toolbar gets in the way.

### ISSUE THREAD

**Issue by Ryonez** [ShareX/ShareX#5947]
The toolbar for editing images
![image](https://user-images.githubusercontent.com/16157130/142069710-c1d555ba-84dd-4ea9-b511-98b62032dfbf.png)
gets in the way a bit.

This was referenced in issue #4028. While a workaround was given, the issue was closed without addressing the problem of a non movable toolbar. Unfortunately, this toolbar is also used in region and actively gets in the way, casing the user to have to do a lot of extra steps to capture a region should their mouse need to interact in the space the toolbar is.

I propose that when the user interacts with the image, the toolbar becomes transparent and non interactive should the mouse go over it. For example, both region capture and cropping the image have you hold down the mouse button as you use the tool.

**Comment by Jaex** [comment]
> the issue was closed without addressing the problem of a non movable toolbar

What you mean non movable? Why you can't drag it?

**Comment by Ryonez** [comment]
I was un-aware that was possible, I hadn't seen mention that was a thing anywhere. Also just learned right clicking the drag spots causes it to roll up.

I still believe that it'd be of benefit to be able to do the work without needed to move the bar at all, and that it'd be more intuitive for the toolbar to become transparent and non interactable while the user is preforming an action at the time, such as selecting a region of the screen.

**Comment by tiagopalhota** [comment]
What version are you using? I don't seem to have the same options as you.
<img src="https://i.imgur.com/akibgAv.png">
