### ISSUE TITLE
I can't shorten my url using my own url shortener and redirector

### ISSUE THREAD

**Issue by dumb-stuff** [ShareX/ShareX#5949]
Here's configuration
![](https://content-azure.biomooping.tk/contentazurebiomoopingtk/KYbmBl0aYd.txt.png)<br>
And here's me testing my redirector<br>
![](https://content-azure.biomooping.tk/contentazurebiomoopingtk/jyBypN58vK.txt.png)<br>
![](https://content-azure.biomooping.tk/contentazurebiomoopingtk/ogoUro3OOH.txt.png)<br>
So I don't know why when I use share x it won't work.<br>
You can test by do HTTP GET request to this url
https://redirect.biomooping.tk/add?url=your url want to shorten here

**Comment by Jaex** [comment]
url parameter value should be `$input$`

**Comment by dumb-stuff** [comment]
nice thanks
