### ISSUE TITLE
Color Picker copy hex code

### ISSUE THREAD

**Issue by Long-Horse** [ShareX/ShareX#595]
Can there be an option to copy the hex code instead of the RGB? Makes it a lot easier to paste into Photoshop.

**Comment by Jaex** [comment]
You can do it from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/04/ShareX_cSAgkJai0D.png)

**Comment by Long-Horse** [comment]
Thanks. There's so many settings to go through :/

**Comment by mnpenner** [comment]
This appears to have moved here:

![image](https://cloud.githubusercontent.com/assets/1112998/19017222/0a61cbbc-87e7-11e6-8303-e5b8e53e4dc7.png)

**Comment by Karlstens** [comment]
Is it possible to use any of these hex or RGB values within the automatic file naming?
