### ISSUE TITLE
Sharex downloading straight into OneDrive

### ISSUE THREAD

**Issue by officialsvre** [ShareX/ShareX#5950]
Before today, Sharex would upload to google chrome and then I could save image as and put it into any folder I wanted. Now it immediately saves it into OneDrive. How could I revert it back?

**Comment by spacecheeserocks** [comment]
If you are using the PrintScreen key, this is (probably) an issue with OneDrive, not ShareX.

There's an option in OneDrive to auto save screenshots to a OneDrive folder. **When this option is enabled, OneDrive stops other programs from responding to the Print Screen key**. 

Try disabling the option in OneDrive, or choosing another hotkey in ShareX.

You can disable this option in OneDrive Settings > Back Up > Automatically save screenshots
![image](https://user-images.githubusercontent.com/40496019/146843100-1bc79ce2-f36d-4f01-a359-a4154c8375d8.png)

**Comment by fernando-sc** [comment]
commenting to say to those who having problems with onedrive always overriding de option to use sharex (maybe win11, when you install onedrive BEFORE sharex).

I solved this issue including a entry for sharex in registry, not in startup folder as the installer does.
