### ISSUE TITLE
Rounded corners alpha problem on Windows 11

### ISSUE THREAD

**Issue by rjappleton** [ShareX/ShareX#5951]
I've just started using version 13.6.1 on Windows 11. Was pleased to read that ShareX could handle the rounded corners with the correct alpha. However it seems to work erratically - sometimes OK for all 4 corners, sometimes OK for 2 or 3 corners only, and sometimes it does not work at all (all 4 corners square opaque with the background color showing).

I am using "Capture Window with transparency" ticked, and using a shadow filter. Using Alt-PrtSc to capture window.

Here is an example corner from a screenshot file that is loaded into an image editor to more easily view the transparent area

![bad-corner](https://user-images.githubusercontent.com/37584605/142616823-4e24af17-2fe2-4aca-aa73-4ad9fea23548.jpg)

**Comment by cooperbang** [comment]
This problem still persists in ShareX 3.17.
