### ISSUE TITLE
Regarding Auto Upload feature

### ISSUE THREAD

**Issue by anique9999** [ShareX/ShareX#5960]
Hi,
Is there a way to disable the auto upload feature in application?

**Comment by Jaex** [comment]
Uncheck this:

![](https://jaex.getsharex.com/2021/11/MFeULt0Jyi.png)

There is also this option:

![](https://jaex.getsharex.com/2021/11/ShareX_82IHvHrPI4.png)

**Comment by anique9999** [comment]
Is there any argument to disable this feature during installation?

**Comment by Jaex** [comment]
Next version gonna have support to disable upload by using registry.

**Comment by anique9999** [comment]
Hi, as per [https://getsharex.com/changelog/](url) I can see that we can disable the upload features via registry. 
But after installation I don't see any ShareX settings in Registry [HKEY_LOCAL_MACHINE\SOFTWARE\ShareX key or HKEY_CURRENT_USER\SOFTWARE\ShareX key] .
