### ISSUE TITLE
-rtbufsize parameter hard coded to 150M causes errors and dropped frames

### ISSUE THREAD

**Issue by ByteJuggler** [ShareX/ShareX#5973]
FFMPEG -rtbufsize parameter is hard coded to 150M.  It turns out this is not enough in some circumstances, for example:
![image](https://user-images.githubusercontent.com/1882820/144918860-5e44e03a-fdcb-42bd-b8a7-62a8f4956883.png)

It wants to be user configurable.

**Comment by Jaex** [comment]
Reason why I did not made it configurable because normally you are not supposed to fill that buffer, if it is filling that means you are unable to real time encode screen recording in time, so in that case whatever you increase your buffer to, still it will be filled with longer recordings. So solution should be making sure it manage to real time encode in time instead of queueing all frames non stop and increase ram usage. Which eventually gonna give error and corrupt your whole screen recording.

By the way I also noticed you have `thread_queue_size` error:

![](https://jaex.getsharex.com/2021/12/chrome_py76fg75Wg.png)

I wonder is increasing it to something like `-thread_queue_size 1024` would help? Then I can add it as default argument.

**Comment by ByteJuggler** [comment]
Hi, :)

Please see comments below:


On Tue, 7 Dec 2021 at 01:13, Jaex ***@***.***> wrote:

> Reason why I did not made it configurable because normally you are not
> supposed to fill that buffer, if it is filling that means you are unable to
> real time encode screen recording in time,
>
I don't contest that if you can't encode in realtime then increasing the
buffer is moot, but there's seemingly a bit more to it than that, at least
in my case.  Generally, the buffer size is, I think, somewhat variable and
dependent on eg other factors, e.g. framebuffer size, framerate, audio
streams being mixed and so on. Why otherwise would FFMPEG itself make it
variable..?  (Then again I could be smoking crack.)

In any case, I've tried with 300, 400, 500 which causes the problem to
become increasingly intermittent, until finally with 600MB it does not
happen, at all. This implies it is encoding in realtime and the buffer use
is only temporary and needs to be large enough for whatever needs to happen
to happen (ignoring the thread_queue_size issue at least.)

*If I couldn't encode in realtime at all then I should start seeing these
errors again eventually also, no matter how large the buffer is set to,
however this does not happen in my case, which seems to imply the buffer is
just not large enough to handle the working set, for whatever reason.*

Please note also this is not exactly a slow machine, encoding at 14fps
ought not be a problem in realtime.  Further note my encoding is a bit odd
in that I mix in 2 audio streams (e.g. I get FFMPEG to mix in my headset
alongside the virtual audio capture), which might be adding some latency or
overhead [possibly I'm speculating, temporarily increasing buffer
needs/use].  Finally the framebuffer resolution is obviously fairly large
3840x1440x32bit so having to hold say 1-2sec of raw data temporarily
implies like 300-600MBish worth.

> so in that case whatever you increase your buffer to, still it will be
> filled with longer recordings. So solution should be making sure it manage
> to real time encode in time instead of queueing all frames non stop and
> increase ram usage. Which eventually gonna give error and corrupt your
> whole screen recording.
>

Sure, *but again, as I say it works well in my case with the buffer at
700MB.  No drops at all, ever.*

I don't think though, that value should be a default for everybody, which
is why I thought the best course of action is to just allow users to
override the default buffer of FFMPEG via the switch FFMPEG provides for
just this purpose, if they need to, IMHO.

Just to hammer this point home, if I may, I've been recording my desktop
while I've been writing this email and other things and* in 15 minutes it's
not dropped a single frame:*
[image: image.png]

Please just make it possible to configure this?  It's a configurable option
on FFMPEG after all..  There is no one-size-fits-all here, I think. It will
be useful to some (possibly small) group of users like me, others won't
know or or don't care can just ignore it and use the default value?  :-)

By the way I also noticed you have thread_queue_size error:
>
>
> <https://camo.githubusercontent.com/57463e3ebc4cab5c4e0afbdaac5108463ffc4b7812958d35f327fc507097be7f/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f31322f6368726f6d655f707937366667373557672e706e67>
>
> I wonder is increasing it to something like -thread_queue_size 1024 would
> help? Then I can add it as default argument.
>
Yes, I also noticed that. I've not looked into that yet too much, but
increasing it would be helpful, analogously to the above.  Though again,
I'm not sure about just hard-coding a default of 1024 for everyone [I'd
prefer it also configurable via pass through] but nonetheless, increasting
it would help.  -- To note, this is interesting because actually you may
need more than one such value, e.g. potentially additional inputs each
could need a switch and possibly not with the same value for each.
Moreover for additional inputs one can currently just add the switch in the
"Additional command line arguments" by hand.. It's just for the "default"
video input, that one must rely on the (hard coded or default) buffer
values from ShareX (if you implement the above increase as you said) or
otherwise the default from FFMPEG..

Anyway thanks, best regards and Merry Christmas. :)
