### ISSUE TITLE
Allow user to skip dependency install

### ISSUE THREAD

**Issue by JixunMoe** [ShareX/ShareX#598]
I have already installed the VC++ 2010 runtime, and the installer wouldn't let me continue :<

![image](https://cloud.githubusercontent.com/assets/5713045/6984136/95e0aa60-da1d-11e4-992e-6a733eab84d5.png)

**Comment by JixunMoe** [comment]
I thought I have (I have vs installed), not no.. Sorry :<

**Comment by Jaex** [comment]
I couldn't find how to make them skip able.

**Comment by JixunMoe** [comment]
The vc++ runtime installer have some problem with my computer, I have to manually install it. After that I restart the installer and everything went fine. 

Thanks for your quick response, and sorry for wasting your time :<
