### ISSUE TITLE
Capture region no longer captures a rectangular region

### ISSUE THREAD

**Issue by vnicolici** [ShareX/ShareX#5980]
Instead of allowing me to capture a rectangular area, it caputures some free form shape that is very difficult to control, and mostly useless for my purposes. Is there any way to capture rectangular regions again in the latest ShareX version?

Attached an ugly capture result of the new capture region:
![4BZjKrS 1](https://user-images.githubusercontent.com/2158971/146048053-9c6c977a-ae1c-4068-9646-1386fa3857b1.png)

Of course, I intended to capture all the text in that area, and I wasn't able to do that with the modified capture region tool.

**Comment by Jaex** [comment]
Click this:

![](https://jaex.getsharex.com/2021/12/ShareX_bk4D50P9DK.png)

**Comment by vnicolici** [comment]
Thanks, I probably clicked that by accident recently and it changed the default. I never messed with that before.
