### ISSUE TITLE
An error appears when saving a screenshot of a web page

### ISSUE THREAD

**Issue by ArchDem0n** [ShareX/ShareX#5985]
Windows 10. ShareX 13.6.1 (last version). In other versions of ShareX this error also appears. Please help me

![ShareX_O67OcwzgBo](https://user-images.githubusercontent.com/96194106/146609210-8ed696c5-ce46-4833-98c5-55b16466718b.png)

**Comment by Jaex** [comment]
How can I reproduce this error?

**Comment by ArchDem0n** [comment]
> How can I reproduce this error?

In my case, the program took 70 screenshots out of 72 (there are a lot of photos on the web page). I clicked Load / Save according to post-capture task settings and this error appears.

**Comment by ArchDem0n** [comment]
> How can I reproduce this error?

Try to take a screenshot (scrolling) on a web page that is more than 70 images in size

**Comment by ArchDem0n** [comment]
> How can I reproduce this error?

Try to take a screenshot (with scrolling) on a web page that is more than 70 images in size

**Comment by ArchDem0n** [comment]
Please help me
