### ISSUE TITLE
Feature Request: natively allow multiple audio sources

### ISSUE THREAD

**Issue by sahilsignup** [ShareX/ShareX#5988]
Currently, this can only be done by adding the following command to the "Additional Arguments" section of the "Screen recording options" panel, while having the virtual audio driver selected as the audio source:
```
-f dshow -i audio="**Microphone Name**" -filter_complex amix=inputs=2:duration=longest
```
The problem with this, however, is that GIFs can no longer be recorded.

Would be great to have the ability to simply choose more than one audio device from the "audio source" dropdown.

Thank you for reading, hope you have an amazing day!

**Comment by senk0n** [comment]
Just use this "Additional Arguments" in custom recording settings for other one hotkey. This may fix GIF recording.
