### ISSUE TITLE
Add edge affects to the Image Editor

### ISSUE THREAD

**Issue by paulofthe612** [ShareX/ShareX#5989]
Hi, was wondering if an 'edging' section could be added to the Image Editor?  Ala SnagIt that has a few different jagged/random/rough/blurry edge option types. 
 
<img width="572" alt="ZJ8wgFT1lg" src="https://user-images.githubusercontent.com/96267862/146458133-b9eca6a1-6c65-4040-ae61-a52d719a38a6.png">

That would be a great enhancement, imho.  Just putting it out there...goooo team!

**Comment by Jaex** [comment]
It is already exists.

![](https://jaex.getsharex.com/2021/12/ShareX_9nsNJeDzQi.png)

**Comment by paulofthe612** [comment]
Where exactly is that? The 'Image' top menu button has a 'Add image affects...' selection, but not sure if that's where you mean.  I have no items showing in that popup, and I don't see any _edging_ ones from the website* after clicking the 'Image affects...'  button.  Thx for your assistance... P

![edge_2](https://user-images.githubusercontent.com/96267862/146571366-dcf757e9-4216-45e0-8016-3f1c1144f1b9.png)

* https://getsharex.com/image-effects/

**Comment by Jaex** [comment]
Configure like this:

![](https://jaex.getsharex.com/2021/12/ShareX_3QM7iGucD2.png)
