### ISSUE TITLE
Feature request: Use shortcuts to upload the image to different image uploader

### ISSUE THREAD

**Issue by lyscop** [ShareX/ShareX#5990]
There is an option in ShareX that chooses the default image uploader after screen capture to upload it, but I want to upload the image to the different image uploader in particular situation by shortcuts, like imgur, smms, etc.

Please take it into consideration, thank you.

**Comment by Jaex** [comment]
You can already customize each hotkeys to have different settings, that way each hotkey can upload to different destination.

**Comment by lyscop** [comment]
Yeap, I find 'Override default custom uploader', that's great.
