### ISSUE TITLE
Feature Request: Add tagging / tags to taken screenshot to better organize them

### ISSUE THREAD

**Issue by Scrat94** [ShareX/ShareX#5992]
Dear ShareX Team,
I really appreciate the tool and I am using it quite heavily in my day-to-day work. 
However when taking a lot of screenshots like me, the organization of them is quite hard, especially if you want to find a specific screenshot in the past not knowing the exact date.

What do you think of a new feature like: **Tags or Tagging**

Description: After taking a screenshot, you could add "Tags" to the screenshots and by doing so you can create your own categories to easily filter and find historical screenshots. I would really appreciate a way to organize my thousands of screenshots with another metadata layer. 
You could also reuse the existing file tag column, which is already available for windows in the file explorer (you can just add the column "Tags". 
![image](https://user-images.githubusercontent.com/31823370/146944045-af630ce5-f85d-42b0-a7fd-034b581e9ac5.png)

Let me know if you think this would be a good and valid feature request! Or if I should raise it somewhere else

Thanks & enjoy your Christmas!

**Comment by Jaex** [comment]
ShareX already have auto tagging system which saves window title and process name of the app you taken screenshot from. So you can just search app name or window title part in history window of ShareX to find old screenshots.

**Comment by Scrat94** [comment]
Hi @Jaex, I am aware of the autotagging. But this is not what I meant. 
As describe in my post I would like to add my own tags like „Business“ oder „Private“ to structure my screenshot. This is completely different than the auto tagging. 

Please keep the ticket open as I can imagine many others would also be interested in this kind of feature. Thanks

**Comment by Scrat94** [comment]
Hi @Jaex, can you please reopen this ticket? Or should I create a new one? Thanks in advance

**Comment by iitjee** [comment]
+1

**Comment by vredko** [comment]
+1

**Comment by Jaex** [comment]
Added tagging to history:

![](https://jaex.getsharex.com/2025/07/Gm7iX2uyWQlh.png)
