### ISSUE TITLE
Share x keeps giving me this error, won't upload anything

### ISSUE THREAD

**Issue by Ben23452345** [ShareX/ShareX#5995]
![Untitled](https://user-images.githubusercontent.com/96529824/147092756-7dadaccc-9888-4981-bff4-d74cb8865b58.png)

**Comment by Jaex** [comment]
It is issue in Imgur side.

**Comment by sterrie** [comment]
I have this error, too. How can I fix it?

**Comment by kasu713** [comment]
I solved the problem by just unchecking in tasks after capturing the "item send to hosting"

**Comment by webstradev** [comment]
Same issue here

**Comment by DanielVALAT** [comment]
Imgur APIs is currently broken, just wait a moment ;)
Check here : https://status.imgur.com/

**Comment by DanielVALAT** [comment]
https://downdetector.com/status/imgur/

**Comment by maxpetrgit** [comment]
I had the same error, then I changed imgur to Chevereto and got this error:
![2021-12-22_15-34-17](https://user-images.githubusercontent.com/47632696/147109264-7ecdf488-5eda-4d23-8a0c-02290ec91f3e.png)

**Comment by DanielVALAT** [comment]
Work for me now
