### ISSUE TITLE
Why isn't it possible to define a hotkey for full screen recording? This way it just pulls me out of full screen and ruins everything.

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#5997]
Hi!

I can't imagine why isn't this possible. It's pretty common thing trying to record whatever is running in fullscreen mode. But since Sharex brings up that selector thing it borks everything.

**Comment by Jaex** [comment]
It is possible. Just create new hotkey with that task.

**Comment by mzso** [comment]
@Jaex
Thanks. Somehow I couldn't work it out, though I was looking in this area.
Is there some way to indicate start/fail and stop of recording? I see no option for this. And in fullscreen it would come really handy.

Although there's an option to play sound after a task. it only seems to apply to screen capture for some reason and not recording, so I don't even have that.
But more useful would be a start of recording sound and a fail sound if it fails.

(I suspect providing an OSD overlay on recorded video is out of scope of this program.)

**Comment by Jaex** [comment]
There is tray icon for it when recording happening.

**Comment by mzso** [comment]
@Jaex 
I'm aware. But I can't rely on that in fullscreen mode.
