### ISSUE TITLE
Can I get how to make custom upload for blogspot (blogger.com)

### ISSUE THREAD

**Issue by onanana** [ShareX/ShareX#5999]
https://developers.google.com/blogger/docs/3.0/reference/blogs

`{
  "kind": "blogger#blog",
  "id": value,
  "name": value,
  "description": value,
  "published": value,
  "updated": value,
  "url": value,
  "selfLink": value,
  "posts": {
    "totalItems": value,
    "selfLink": value
  },
  "pages": {
    "totalItems": value,
    "selfLink": value
  },
  "locale": {
    "language": value,
    "country": value,
    "variant": value
  }
}`

im trying make sxcu about blogspot.

but idk programming. even blogid.

what is the blogid? where is it?

plz somebody make it.

if we can use blogspot's image uploader by shareX, will be really convenient.

it is unlimited storage. and can access easily, fast. private. public.

**Comment by crewockeez** [comment]
you can make ? blogspot .sxcu ?
