### ISSUE TITLE
"ScreenRecorder.avi"

### ISSUE THREAD

**Issue by 7s3** [ShareX/ShareX#600]
I have a very large file created by ShareX named "ScreenRecorder.avi". Is this something necessary for the program or did I just accidentally record something?

Thanks!

**Comment by Jaex** [comment]
It is for GIF recording caching. It is converting to GIF when you stop recording. But normally it should be deleted after GIF created. So there must be bug which not deleted.

**Comment by 7s3** [comment]
Thanks for the quick reply! The file has been on my PC for quite some time so I'm sure the bug has either been fixed already or ShareX (then ZScreen) could have been killed in Task Manager by me causing the bug. :)
