### ISSUE TITLE
plz contain webp to image

### ISSUE THREAD

**Issue by onanana** [ShareX/ShareX#6000]
sharex recongize webp is a kind of file.
so im using upload filter for now.
but this is a image file.
plz contain webp to image.
thx a lot develpoer. thx.

**Comment by Jaex** [comment]
You can add webp from here:

![](https://jaex.getsharex.com/2021/12/ShareX_HPYiAoilVw.png)

**Comment by onanana** [comment]
> You can add webp from here:
> 
> ![](https://camo.githubusercontent.com/2fca8dd0b9eea0d28f5b662459c89f8ecb384a68ca1bb62cabdce1daf1b49fb0/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f31322f5368617265585f48505969416f696c56772e706e67)

thank you very much. thank you.
