### ISSUE TITLE
Twitter post tool

### ISSUE THREAD

**Issue by sflorg** [ShareX/ShareX#6007]
The tool has one minor flaw. # Tags are not counted as characters by Twitter. So the Character count listed is incorrect when using # Tags. Just thought I would mention it. 
Heidi-Ann

**Comment by Jaex** [comment]
I added # characters in web twitter and still remaining character count was decreasing.

**Comment by sflorg** [comment]
Hmm after checking they say they do. . . but not what screenshot is showing. . .  
Thanks for the quick response though.
https://photos.app.goo.gl/sKkVhyqLQDvzArEf7

**Comment by sflorg** [comment]
Well not so fast. . . Confirmed with twitter, and had three others take a look. ShareX is counting "spaces" as characters, Twitter doesn't That is why I keep getting a difference in counts and ability to Tweet from ShareX.

**Comment by Jaex** [comment]
I check now, space also counted in Twitter web site.
