### ISSUE TITLE
Feature Request: Screenshots with same process name put into same folder

### ISSUE THREAD

**Issue by cckinfo** [ShareX/ShareX#6010]
The process name of a given screenshot can be detected as the %pn file naming pattern shows.
Option for the following: Upon taking a screenshot, a folder should be created with its process name and the screenshot is placed inside. Then, future screenshots of that same process are also saved into that folder.

Things to account for / behavior: If the sub folder pattern is something like %y-%mo, then a folder with the same process name is created upon the first screenshot of each month within that date folder. If sub folder pattern is left blank, the process folder is only created once and includes all future screenshots of that process.

**Comment by Jaex** [comment]
It is already added two days ago: https://getsharex.com/changelog/

**Comment by cckinfo** [comment]
Wow what a timing! My version wasn't updated yet. Thank you.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2022/01/ShareX_Wqw7bxnb7k.png)
