### ISSUE TITLE
How to get the return upload link after using the command line 'path\x.png -task name' in the cmd?

### ISSUE THREAD

**Issue by lyscop** [ShareX/ShareX#6012]
I use the command line `path\ShareX.exe path\x.png -task "Upload to Imgur"` in the cmd, and the return link auto copy to the clipboard.

But there is no result shown in the cmd.

I want to get the return link directly from the cmd, also auto copy to the clipboard, and the reason is that I may think that getting the result from cmd is faster than from the clipboard.

How to get the return upload link from the cmd?

**Comment by BobbyWibowo** [comment]
Is this not a supported use case?

**Comment by lyscop** [comment]
> Is this not a supported use case?

It is easy to get the return link from the clipboard. I want to get it from the return result instead of the clipboard.

I don't know if it is easy to achieve, for there are some seconds for wait the return link to show in the result just like the clipboard.

**Comment by BobbyWibowo** [comment]
Yeah, I was asking the devs if it wasn't, since the issue got auto-closed for inactivity
I also needed something similar

Either way, I eventually settled to writing my own simple powershell script, since I only needed it for some personal requirements anyways

**Comment by lyscop** [comment]
Hmmm, it doesn't achieve, the question just auto closed.
