### ISSUE TITLE
“删除本地文件”错误

### ISSUE THREAD

**Issue by Kumiri** [ShareX/ShareX#6014]
![图片](https://user-images.githubusercontent.com/32268477/148147199-ce3a3852-6155-4d25-bb00-5d253fd3a237.png)

2022-01-05 09:24:33.069 - ShareX starting.
2022-01-05 09:24:33.073 - Version: 13.7 Portable
.
.
.
2022-01-05 09:36:41.801 - Exception:
System.ArgumentException: 传递给 Icon 的 Win32 句柄无效或者类型错误。
   在 System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   在 System.Drawing.Icon.FromHandle(IntPtr handle)
   在 ShareX.HelpersLib.NativeMethods.GetFileIcon(String filePath, Boolean isSmallIcon)
   在 ShareX.HelpersLib.ImageFilesCache.GetFileIconAsImage(String filePath, Boolean isSmallIcon)
   在 ShareX.MainForm.UpdateActionsMenu(String filePath)
2022-01-05 09:36:43.201 - Exception:
System.ArgumentException: 传递给 Icon 的 Win32 句柄无效或者类型错误。
   在 System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   在 System.Drawing.Icon.FromHandle(IntPtr handle)
   在 ShareX.HelpersLib.NativeMethods.GetFileIcon(String filePath, Boolean isSmallIcon)
   在 ShareX.HelpersLib.ImageFilesCache.GetFileIconAsImage(String filePath, Boolean isSmallIcon)
   在 ShareX.MainForm.UpdateActionsMenu(String filePath)
2022-01-05 09:36:47.580 - Unhandled exception:
System.IO.FileNotFoundException: 未能加载文件或程序集“Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
文件名:“Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
   在 ShareX.UploadInfoManager.DeleteFiles()
   在 ShareX.MainForm.tsmiDeleteSelectedFile_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jaex** [comment]
> System.IO.FileNotFoundException: 未能加载文件或程序集“Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
文件名:“Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”

Looks like Microsoft.VisualBasic dll is missing. Try re installing .NET Framework 4.8.

**Comment by Kumiri** [comment]
> > System.IO.FileNotFoundException: 未能加载文件或程序集“Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
> > 文件名:“Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
> 
> Looks like Microsoft.VisualBasic dll is missing. Try re installing .NET Framework 4.8.

Thank you, I understand, the problem has been resolved.
