### ISSUE TITLE
Set Disable Upload options to default

### ISSUE THREAD

**Issue by baramofme** [ShareX/ShareX#6016]
Hi, It's good to use ShareX!

And I just notice that my capture things have been uploaded to imgur for a year... :(

It's so ... I can't imagine how I feel right now, and find my private work in a bunch of anonymous streams of photos on Imgur.

I thought there were a lot of people like me. 

So, give a little chance, not to embarrass.

Disable auto-upload options to true when ShareX is installed. please.

Thanks for your best regards.

**Comment by CubityFirst** [comment]
This is not a planned addition / change, the first time that you take any screenshot with ShareX you are warned, and asked if you are sure that you want to upload things, if you say no, it's disabled, if yes, then it goes ahead.

This is what that prompt looks like > 
![image](https://user-images.githubusercontent.com/14070268/148376122-b79574c7-3957-4946-9912-071169f7e770.png)

If you want to disable all future uploads, either disable the After Capture Task "Upload to Host" and that will stop screenshots from uploading, or if you want to go for the nuclear option, go to Application Settings, Advanced, Upload, and turn "DisableUpload" to True.

If you want to delete the imgur files, right click the images that you want to delete in ShareX, click "Open" and then click "Open Deletion URL".

**Comment by Zorklis** [comment]
I don't think this appeared for me
