### ISSUE TITLE
Settings not saved on restart

### ISSUE THREAD

**Issue by mattacrazy** [ShareX/ShareX#602]
Windows 10 Technical Preview Build 9926. ShareX 9.8.

After a restart Destination preferences reset to default - switches from Picasa to Imgur, googl to bitly etc.. Switching to these options enables them again and they work - goes to correct folder previously specified on Picasa for example, but the menu options are empty 
![image](https://cloud.githubusercontent.com/assets/9108621/7005134/9836dc24-dcb8-11e4-8684-78da139ad527.png)

**Comment by Jaex** [comment]
Destinations settings saving when you close Destination settings window. Application settings saving when you close ShareX main window. So if it not saving then something wrong in your pc? You can check console for see when it saving.
