### ISSUE TITLE
Issue with updating.

### ISSUE THREAD

**Issue by Skaithakk** [ShareX/ShareX#6020]
I have an issue with updating ShareX, I have it on a different drive than C: and when i go to update it always installs another copy of ShareX to the C: drive instead of just updating in the already existing path.

**Comment by Jaex** [comment]
When you install ShareX first time, InnoSetup creates registry entry with path to install location. When this registry entry is missing or pointing to different location (if you moved the folder manually yourself), then setup unable to find ShareX and installs it to default location. You can uninstall/delete both ShareX and reinstall setup manually to make sure that InnoSetup creates new registry entry which pointing to ShareX in other drive.
