### ISSUE TITLE
Suddenly capture stopped working "[dshow @ 000001ff0b23d440] Could not find output pin from video capture device. "

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#6021]
Hi!

It was working a few days ago, but now I get:
```
[dshow @ 000001ff0b23d440] Could not find output pin from video capture device.
video=screen-capture-recorder:audio=virtual-audio-capturer: I/O error
```
I tried uninstalling SCR then reinstalling withing ShareX, but I get the same error.

**Comment by nupam228** [comment]
Have you used the 'dshow' option to select the video source in ShareX?
I suggest you designate the input stream as 'gdigrab' for video capturing using a prefix like here:
-f gdigrab -i video
and a separate parameter for capturing audio:
-f dshow -i audio="specific_name_dshow_audio_device"

**Comment by mzso** [comment]
@nupam228 
I used video capture recorder. I actually used the same command as before, but it started failing.

**Comment by navidmafi** [comment]
For anyone still having this issue: I realized I have disabled all audio outputs. Issue resolved upon enabling my speaker again.
