### ISSUE TITLE
QR decode doesn't work if user choose not to save file after capture

### ISSUE THREAD

**Issue by Fire1nRain** [ShareX/ShareX#6025]
If a user choose not to enable "Save image to file" or "Save image to file as..." option, neither "Scan QR code" task in the "After capture tasks" nor the option added in the quick task menu will work properly.

After checking the code, it seems that for both situations, the code rans to `DoFileJobs(),` where `AfterCaptureTasks.ScanQRCode` is only checked if `File.Exists(Info.FilePath)`. This means that any attemps to try only scan the QR code without saving it will not function noramlly(Why would you want to save a random QR code anyway?).

Since what `QRCodeForm.OpenFormDecodeFromFile` does is basically reads the Bitmap from the image file and `DecodeImage` it. It's quite easy to add a `QRCodeForm.OpenFormDecodeFromBitmap` and a `DecodeFromBitmap` function:
![image](https://user-images.githubusercontent.com/10319645/148903694-dcff46bb-546d-4a1e-9da4-20ed1838dbef.png)
![image](https://user-images.githubusercontent.com/10319645/148903654-43276815-b837-4f27-8a67-d62b86c1da9e.png)
All that left is to add an `else` in `DoFileJobs` to check `AfterCaptureTasks.ScanQRCode` again, or moving this check outside the main `if` statement and check individually:
![image](https://user-images.githubusercontent.com/10319645/148903887-e0e352e3-c42a-459d-87e6-70aa28eafbe7.png)
Or, if Info.Metadata.Image is always assigned, we can simply move the `AfterCaptureTasks.ScanQRCode` check outside the main `if` and changed it to use `OpenFormDecodeFromBitmap` entirely to eliminate file reading completely:
![image](https://user-images.githubusercontent.com/10319645/148908596-aaecb009-0aa4-4ecf-85da-2e5b58a9a27b.png)

**Comment by Jaex** [comment]
You can create hotkey for "QR code (Decode from screen)" which not depends on file.

**Comment by Fire1nRain** [comment]
Agreed, but that's whole screen QR scan.
I know ShareX shows all result on the screen, but it doesn't tell which one comes from which.
Also, the experience of selecting an area just like rect capture and scan it is much intuitive and nice.

**Comment by Jaex** [comment]
It is region capture.

**Comment by Destroy666x** [comment]
Fully agreed it's weird it doesn't work.

I could turn the above into PR if you don't mind and don't have time yourself @Fire1nRain

**Comment by mrmashal** [comment]
Yes please implement it. It doesn't work when we add it to the quick task menu like this:

<img width="357" height="330" alt="Image" src="https://github.com/user-attachments/assets/ee9b83e5-5660-41bc-ac4d-d4ee7852c633" />
