### ISSUE TITLE
Ability to ignore specific window(s) from window capturing

### ISSUE THREAD

**Issue by yuis-ice** [ShareX/ShareX#6028]
When I do "capture region" on ShareX, a feature to ignore a or some windows would be nice I believe. 

For example some software have full screen window (electron, c# software etc.); I use Dimmer, a blue light reducing software, is one of them. 

So ignoring window(s) by its window title or exe name for instance, sounds nice.

**Comment by yuis-ice** [comment]
please respond to this issue.

**Comment by livejamie** [comment]
This would be helpful for people that run remote access programs or accessibility programs like you mention.

I run WindowTop, which ruins the screen capturing targeting tool, which is very helpful.
