### ISSUE TITLE
Error/Bug at opening

### ISSUE THREAD

**Issue by mikhoul** [ShareX/ShareX#603]
System.InvalidOperationException: Le SplitterDistance doit se situer entre Panel1MinSize et Width - Panel2MinSize.
   à System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   à ShareX.MainForm.LoadSettings()
   à ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   à System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   à System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   à System.Windows.Forms.Control.WmCreate(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.Form.WmCreate(Message& m)
   à ShareX.HotkeyForm.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Windows 7 64  Version 8.8  (Will update Right now ;-)

**Comment by Jaex** [comment]
What is point of reporting bug from 1 year old version? What if it is already fixed in latest version?

**Comment by mikhoul** [comment]
Cause it's not a common bug it's the first time it happen and I have a log file.

Installed the new version and seem to be fine. ;-)

One quick question can you tell me if I can start the "greenshot image editor" as a stand alone program (I like it) ????

Maybe with a script and rundll ???  Thanks !

**Comment by Jaex** [comment]
So your problem not exist in latest version?

You can open Greenshot image editor from Tools menu and be able to assign hotkey for it but if you want standalone exe then you should contact developer of Greenshot because we using their image editor.

**Comment by mikhoul** [comment]
From now (with the new vesion) the bug did not happen but it was the first time I've seen this bug on my system.

Will try to make a shortcut for the image editor. Thx !
