### ISSUE TITLE
FFMPEG - Capture area extends outside window area

### ISSUE THREAD

**Issue by lmlikota** [ShareX/ShareX#6031]
Thank you @Jaex @dannoe @aaronrobertson 

I have downloaded latest `ffmpeg.exe` using ShareX `download` option but it didn't fix the issue. I've also tried to dowload latest  `ffmpeg.exe` from official site and still no luck. 

Any other ideas? I have Dell U2722DE 4K monitor with resolution 2560x1440 and scaling 125% on Windows 10.

![image](https://user-images.githubusercontent.com/10289319/149318281-435688c2-4063-447d-9cc1-13294e51716f.png)

**Comment by lmlikota** [comment]
Looks like it has something with scaling, after setting default scaling to 100% I've got different issue this time

![image](https://user-images.githubusercontent.com/10289319/149318569-f472ca06-efcd-4f9c-b2fe-887c7f02f96e.png)

**Comment by josdemmers** [comment]
I can confirm the scaling issue. Both my monitors are set to 125% scaling. When I start recording on both screens the following error is thrown:
[gdigrab @ 000001715719ecc0] Capture area (-2560,0),(2560,1440) extends outside window area (-2048,0),(2560,1440)desktop: I/O error

However I don't have your second issue, as soon as I set the scaling for both monitors to 100% everything works fine for me.
But would be great if the program could handle 125% scaling as well. At 100% everything is just too small for me.

**Comment by lmlikota** [comment]
@josdemmers You are right. Thank you for your time.

I forgot to change scaling on my laptop screen which was also set to `125%` because I was expecting that reversing scaling to `100%` on my big screen will resolve issue.

I can confirm that setting both screens from `125%` to `100%` fixed the issue but as you said everything is too small at `100%`.

![image](https://user-images.githubusercontent.com/10289319/150766683-5b108c4a-1c64-457d-99e1-96d68d906af8.png)

**Comment by josdemmers** [comment]
Here an example that shows ShareX does not use the scaled coordinates:
![scaled_coords](https://user-images.githubusercontent.com/8627157/150770908-e74016e5-ccb8-4974-8071-499775d33a80.jpg)

**Comment by lmlikota** [comment]
Solution is in #1433 in comment https://github.com/ShareX/ShareX/issues/1433#issuecomment-1079569785 with fix confirmation in https://github.com/ShareX/ShareX/issues/1433#issuecomment-1081693164
