### ISSUE TITLE
Right click > Upload with ShareX on image open in Firefox not working

### ISSUE THREAD

**Issue by undercovernormie** [ShareX/ShareX#6032]
I have done a clean install of Windows after hardware upgrades and have since reinstalled ShareX 13.7. If I have an image open in Firefox (95.0.2) and right click the image and click "Upload with ShareX" it no longer seems to do anything. I have default settings pointed to imgur.com. My attempts do not show up in History. It worked flawlessly for years before this. Anybody know how I would be able to fix this? It's more than likely a "me" problem than a ShareX problem, I assume.

Thank you.

**Comment by Jaex** [comment]
Did you enable this:

![](https://jaex.getsharex.com/2022/01/ShareX_IxsTORNLv9.png)

**Comment by undercovernormie** [comment]
I didn't know I had that installed on my old Windows install but I must have. Yes, I have installed the Firefox addon now. Thank you.

**Comment by wapenshaw** [comment]
Hmm weird, I am having the same issue and I don't see the Firefox Integration option at all! 
![Integration Settings](https://user-images.githubusercontent.com/739546/194914152-11a121cf-853f-48fa-864a-a86876fdcfcd.png)
@undercovernormie  can you please help?
