### ISSUE TITLE
Can't install on standard user

### ISSUE THREAD

**Issue by xmha97** [ShareX/ShareX#6036]
Hi, I can't install ShareX on the standard user.
Please make an installation for the current user/all users.
![image](https://user-images.githubusercontent.com/23485114/149637898-eb52337d-afc2-41f5-951d-4ffd8514e329.png)
![image](https://user-images.githubusercontent.com/23485114/149637918-a791a190-0516-4a8e-8ccf-ccb6742d96b4.png)
Thanks.

**Comment by Jaex** [comment]
Those options you show in screenshots just changes install location. And ShareX allows installation to any folder you want. When setup try to install to folder where it not requires admin permissions then it not asks for it. That way you can install to your user folder without require any additional permissions, same as those installers.

**Comment by xmha97** [comment]
If you add this feature to the installer, users can install the app more easily.
Also if I change the installation path to %LocalAppData%, the shortcut will be created for all users.
![image](https://user-images.githubusercontent.com/23485114/149640737-2425b97c-66ea-463d-a2f5-1dbad33c502b.png)

**Comment by xmha97** [comment]
If you add this feature to the installer, users can install the app more easily.

**Comment by xmha97** [comment]
@Jaex Do you have plans to add this feature yet?
