### ISSUE TITLE
History does not show captures since it was opened

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#6040]
1 Open History
2 Make a capture
3 Inspect History

Expected: Capture shown in History
Observed: Capture not shown in History

Workaround: press F5 (not available on mouse click, apparently)

(Repost of https://github.com/ShareX/ShareX/issues/4292 closed by a clumsy bot.)

**Comment by chrisjj** [comment]
"bot closed this as [completed]"

It is not completed. The issue persists.

**Comment by Carm01** [comment]
https://github.com/ShareX/ShareX/issues/7367
