### ISSUE TITLE
Re. Registry to Disable Uploads

### ISSUE THREAD

**Issue by anique9999** [ShareX/ShareX#6041]
Hello everyone,
After installing ShareX, I'm not able to find any Registry settings for ShareX as mentioned in [documetation](https://getsharex.com/docs/command-line-arguments) `"HKEY_LOCAL_MACHINE\SOFTWARE\ShareX"` and` HKEY_CURRENT_USER\SOFTWARE\ShareX` to disable the upload option.
![image](https://user-images.githubusercontent.com/90675448/150321495-89d93aba-a620-40d3-a43a-039a5bbdd834.png)

Can you please tell how can I disable upload?

**Comment by Jaex** [comment]
You must create them yourself.

**Comment by anique9999** [comment]
Thank you.

Just wanted to confirm the "Data" field should be set as (value not set) or do I have set some value like ("00000") etc.?
Thank you in advance

**Comment by anique9999** [comment]
Hi, I made a registry (above pic) in "HKEY_LOCAL_MACHINE\SOFTWARE\ShareX" but the upload feature is not getting disabled 
![image](https://user-images.githubusercontent.com/90675448/151749904-16dc2bcd-4dc9-4411-aee2-be9da99d1c52.png)

**Comment by L1Q** [comment]
The way you test if the registry setting worked is by trying to upload something. The setting you see in the app is the one stored in the ShareX config file. Registry entry should override it.
When trying to upload, ShareX should display a specific error message stating "Your system admin disabled the upload feature."
