### ISSUE TITLE
[Feature Request] Region selection should not stop editing (or Readjustable region)

### ISSUE THREAD

**Issue by Gdocal** [ShareX/ShareX#6042]
I use ShareX for many years but from the beginning, it was a real pain for me that I cannot select the region before adding some marks on that region. 
Users should be able to select region, add some paints, and even readjust the selected region after if they changed their minds. When you select a region, not selected space should be greyed out and the selected region should have borders that can be used for adjustments. It is so intuitive, I waited for a long time for someone to implement it but seems not one cares.
simple example  how it can work:
![source](https://user-images.githubusercontent.com/11136265/150363341-bd75d966-e38d-4fda-ab61-53abb5ef2801.gif)

**Comment by L1Q** [comment]
Have you tried the "Multi region mode"?
![image](https://user-images.githubusercontent.com/6942070/150366029-eb4cb540-ddb8-4d22-a742-df6d78675ffe.png)

**Comment by Gdocal** [comment]
can't belive it already implemented probably already for a long time, thanks for pointing me @Jaex
