### ISSUE TITLE
Screen recorder with system audio and microphone on separate channels?

### ISSUE THREAD

**Issue by Savasdotexe** [ShareX/ShareX#6046]
Is a way as an additional command line (or any other way) to separate the microphone from the system audio channel?

I would like to eliminate any background noises from the microphone via editing later on or sometimes do not need the microphone audio so I delete the channel, but when it's mixed I can't.

Also it would be nice to be able to add a custom captures that can be named so I can create a secondary screen recorder named to say for example mic+systemaudio, so when I want to record with the microphone included, I would choose that.

**Comment by megamorphg** [comment]
Surprisingly, this is already possible! Someone explains how to do it via command line here:
https://superuser.com/a/1629771/245425
