### ISSUE TITLE
Scrolling capture does not work in Firefox

### ISSUE THREAD

**Issue by pauby** [ShareX/ShareX#6047]
Firefox: 96.0.2
ShareX: 13.4

This seems to be a long running issue that isn't getting any love to fix. Following on from [this issue](https://github.com/ShareX/ShareX/issues/4224), scrolling capture does not work in Firefox 96.0.2.

**Comment by Jaex** [comment]
You should use Firefox built in scrolling capture:

![](https://jaex.getsharex.com/2022/01/MJXi0o4pG8.png)

**Comment by aranapatona** [comment]
This is not working for me still, it works only if I select to simulate mouse scrolling but it stops after only a fraction of the page is scrolled.
