### ISSUE TITLE
Option to both Muted and Unmuted Screen Recording

### ISSUE THREAD

**Issue by GitClickOk** [ShareX/ShareX#6053]
In Sharex Task Settings, in Screen Recorder, clicking on Screen Recording Options, If I select "Audio Source" to "None", my screen recordings will be without sound, and that is amazing.

But I want to an option to record with sound too.

For example, in my hotkey settings I have: 
_Shift+Print Screen = Start/Stop screen recording_
I want another hotkey like:
_Ctrl+Alt+Print Screen = Start/Stop Muted Screen Recording_

But in this case, in Screen Recorder, the button "Screen Recording Options" is disabled.
![disable button](https://user-images.githubusercontent.com/19438005/151026767-81e37578-76d9-49da-bcd3-05b19036f307.png)

Is there some alternative to do this?

**Comment by Jaex** [comment]
Click on Capture tab, there you will find option to override capture options.

**Comment by GitClickOk** [comment]
@Jaex Thank you and congratulations for this awesome project.
