### ISSUE TITLE
Text Color settings...

### ISSUE THREAD

**Issue by rbh00723** [ShareX/ShareX#6058]
Hi so I was recently trying to make some changes to Hotkey Settings  and when I was in there I found it quite difficult to read some of the text in the settings. The text I am referring  to is shown in the image below. For some reason it does not seem to correspond to any color settings in the theme settings scheme. I tried changing almost every color and couldn't seem to make that text color change. 

![ShareX_tuz3n8wenV](https://user-images.githubusercontent.com/40576026/151668308-bbd5525b-1a4c-4848-8dcc-c41de483bace.png)

**Comment by Jaex** [comment]
WinForms not allows changing text color of disabled controls.
