### ISSUE TITLE
QR Code Window doesn't properly support dark theme

### ISSUE THREAD

**Issue by jonaskohl** [ShareX/ShareX#6061]
I think the title says enough

Here are screenshots of what I'm talking about:
![ShareX_5VFQOy4Wci](https://user-images.githubusercontent.com/23175424/151699972-dd93e3e7-a6ae-472b-b0db-8ee7e8353131.png)
![ShareX_XAGjVyFxuQ](https://user-images.githubusercontent.com/23175424/151699974-d47ae4d2-144d-4d4b-8ee1-ab86ce5f9f6a.png)

ShareX Version: 13.7
Windows Version: Windows 11 Home x64 21H2 (Build 22000.434)
Selected theme: Dark

**Comment by Jaex** [comment]
I on purpose kept white QR code because it could be easier to scan.

**Comment by jonaskohl** [comment]
I actually meant the tab control rather than the QR code

**Comment by Jaex** [comment]
I can't change color of them.

**Comment by jonaskohl** [comment]
You can actually ownerdraw it if you tell it to do all of the painting in WM_PAINT. That's what I did for one of my applications
