### ISSUE TITLE
.GIF and videos fail to upload

### ISSUE THREAD

**Issue by wonshikvevo** [ShareX/ShareX#6062]
Since a few days ago, any .gif or video files I take fail to upload. They do still remain in my local screenshot files but they don't auto-upload to imgur or dropbox as my settings would indicate. Any troubleshooting on this? I keep getting an error "Imgur upload failed: (417) Internal expectation failed" for the .gifs, and then the software is trying to upload the video files to imgur even though I have my dropbox info logged in and set.

**Comment by subnwa** [comment]
I know it is being changed from the "Destinations" section.
