### ISSUE TITLE
FFmpeg error: frame dropped!

### ISSUE THREAD

**Issue by koznichki** [ShareX/ShareX#6066]
Hi,
I'm having some trouble recording long clips through screen recording. For some reason sometimes there is no error and sometimes there is. It would really make me happy if someone could tell me how to avoid this situation, please.

![ShareX error](https://user-images.githubusercontent.com/89933502/151905196-fea4737b-040c-453a-a1d8-bf4fc3cd76fc.png)

**Comment by Hunterofemotion** [comment]
Is there any way to recover a video damaged by this bug?
