### ISSUE TITLE
Custom preset for tools in image edit toolbar

### ISSUE THREAD

**Issue by d-Rickyy-b** [ShareX/ShareX#6068]
Hi there and thanks for creating ShareX. I love this tool.

Currently I find myself using the rectangle tool for two things mainly:
1. Highlight certain elements with a red frame (transparent fill color)
2. Censor critical data with a full black rectangle

Yes, I know about the Smart Eraser tool and I like it for many things. The only issue this brings up when censoring certain data: People get confused with "missing" data. Let me give you an example:

I often create and share screenshots of phishing mails. For privacy and security reasons I don't want others to know who the actual sender or the receiver of the phishing mail was. They should only get to know the domains of the sender/receiver. It's quite similar for the actual phishing URL. I don't want to have the actual URL in the screenshot, it's enough to have the domain and the URL & get parameters will be censored.
When using the Smart Eraser, people might think that the URL consists only of the domain itself (and no additional path). A black rectangle or a pixelated area on the other hand contain vital information: "This part of the screenshot has been censored (on purpose)".

Of course there's already the ability to change colors for the rectangle border and fill manually. But sometimes I switch between different settings multiple times a day. So now my question: Could you think about adding a feature to have quick selections for border/fill color combinations for shapes? Or a way for users to add shortcut buttons to tools with specific presets. That way users could add multiple presets for the same tool (e.g. buttons for different pixel sizes for the pixel tool, or buttons for different rectangle color combinations).

Maybe I am also just very blind and you already implemented a (similar) feature and I just didn't notice.

Let me know what you think.

Cheers,
Rico

**Comment by Jaex** [comment]
Currently as workaround you can use pixelate tool with 1000 pixel size, that way rectangle will have slightly different color than background but still censor whole thing.

**Comment by d-Rickyy-b** [comment]
Thanks for your reply, that is a workaround. Still it would be great to have some quick selects for certain tool settings.

I imagine something like the current "Tool options" setting (or maybe even located there as a sub menu) but with a list of your created presets (e.g. quick select for different pixel sizes or different color combinations for the shapes tool).

You marked this as a duplicate. Mind linking the other issue this one duplicates? Thanks in advance.

Cheers,
Rico

**Comment by d-Rickyy-b** [comment]
Hi, still not sure if this issue is actually a duplicate and also not sure if you plan to implement such a feature. As of now you only offered a workaround. As long as you don't state you won't implement this, I'll keep this issue from getting stale, if that's okay with you.
