### ISSUE TITLE
Circle appearing in my copied region

### ISSUE THREAD

**Issue by RK204800** [ShareX/ShareX#6070]
I have seen this issue posted previously, however their was no resolution.  When creating an image an ellipse now appears cropping the image, as indicated in the attached.  Any assistance appreciated.
<img width="487" alt="NinjaTrader_BaydlRQ2PG" src="https://user-images.githubusercontent.com/98921786/152247683-d3b0903c-4ef0-48aa-8000-c015a0d43d47.png">

**Comment by RK204800** [comment]
Resolved it for anyone with this issue:
Go to Task Settings;
Advanced;
Capture:
Set RegionCaptureDisableAnnotation to Tru
<img width="443" alt="NinjaTrader_gTwhYBFlfu" src="https://user-images.githubusercontent.com/98921786/152249444-82081d32-0bce-4c20-98ef-756ca718fc60.png">
e

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2022/02/ShareX_mP07Eh0eIu.png)

**Comment by UpworksTeam** [comment]
@Jaex I don't have that option
