### ISSUE TITLE
Sharex won't snap to any window on my main monitor.

### ISSUE THREAD

**Issue by IkkixD** [ShareX/ShareX#6071]
I'm not sure which version started this, but as of recently it won't snap to windows/inner windows on my main monitor (3440x1440) but it will to both of my other monitors (1920x1080 and 2560x1440)

**Comment by Jaex** [comment]
That means there is invisible fullscreen overlay in your screen created by one app in your pc. But even it is invisible still not marked as invisible so ShareX can't ignore it automatically as usual. So close that fullscreen overlay/app.

**Comment by IkkixD** [comment]
> 

It's nvidia share, which is unfortunate as it wasn't happening before :/ Did nvidia screw something up?

**Comment by Grimnir09** [comment]
@IkkixD sorry for the necro bump, you can keep desktop recording in Nvidia share as long as you don't have any overlay effects t. (FPS counter, Live status)
