### ISSUE TITLE
Uguu file uploader 400 error

### ISSUE THREAD

**Issue by juicetoon** [ShareX/ShareX#6077]
```
Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://uguu.se/api.php?d=upload-tool

Status code:
(400) Bad Request

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Date: Sat, 05 Feb 2022 10:41:23 GMT
Server: nginx

Response text:
{
    "success": false,
    "errorcode": 400,
    "description": "No input file(s)"
}
```

Seems to be because the upload tool API URL has changed. Looks like it's now https://uguu.se/upload.php

It's also strange that I cannot find Uguu in the "Destinations settings" menu list but Uguu is in my "Destinations > File uploadders" list.

**Comment by Jaex** [comment]
#6059

**Comment by mreduar** [comment]
@Jaex This error still persists. Was it generated after this issue or has it not been fixed?

```
Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://uguu.se/api.php?d=upload-tool

Status code:
(400) Bad Request

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'self';
Permissions-Policy: interest-cohort=()
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Type: application/json; charset=UTF-8
Date: Sun, 01 May 2022 07:22:33 GMT
Server: nginx

Response text:
{
    "success": false,
    "errorcode": 400,
    "description": "No input file(s)"
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by Jaex** [comment]
You can use dev build: https://getsharex.com/docs/dev-builds

**Comment by mreduar** [comment]
![image](https://user-images.githubusercontent.com/22550119/166136728-31ab48e8-72a6-45e3-86fd-6368e481df65.png)
I get this error after pressing the button
ShareX 13.7.0

**Comment by Jaex** [comment]
I tested now, it downloads fine for me.

**Comment by mreduar** [comment]
Well, I don't know what to say
https://a.uguu.se/HkFRRcZ.mp4

**Comment by Jaex** [comment]
Ah now I figured why, AppVeyor must have removed old builds and you can't get new dev builds without actually be in dev build (because we changed branch name to "develop").

You can manually download it from here: https://ci.appveyor.com/project/ShareX/sharex/build/job/qxy3117q3oet9yt9/artifacts

**Comment by mreduar** [comment]
Beautiful, now it works. Thank you very much
