### ISSUE TITLE
Is there a way to open an image from file manager straight into the ShareX Image Editor?

### ISSUE THREAD

**Issue by sahil48** [ShareX/ShareX#6082]
Is there a way to open an image from file manager straight into the ShareX Image Editor? I Could not figure out how to do this in Windows.

Got this Error when trying to use Open With - ShareX

![image](https://user-images.githubusercontent.com/6100774/153033086-42660d9a-b337-44b2-88ad-d41f650980e2.png)

**Comment by Jaex** [comment]
Enable this:

![](https://jaex.getsharex.com/2022/02/ShareX_URVdxJW2IF.png)

**Comment by sahil48** [comment]
Thanks!
