### ISSUE TITLE
Orange tint on screenshots

### ISSUE THREAD

**Issue by lucabrazza1** [ShareX/ShareX#6085]
When using latest version of f.lux and ShareX - there is a really bad orange tint.

https://cdn.discordapp.com/attachments/636979141421301760/940776519335284757/chrome_O1MU71ZmYF.png -- screenshot of a white background image

Using Windows 11 Insider Preview (Home). Build 22543.rs_prerelease.220122-2315

**Comment by kacperleague9** [comment]
can confirm on windows 10 home (13.7.2 sharex)

**Comment by Romybron** [comment]
I have the same thing when upgrading from Windows 10 LTSC 1809 to Windows 10 LTSC 21H2
Please fix ...

**Comment by KaspianDev** [comment]
> I have the same thing when upgrading from Windows 10 LTSC 1809 to Windows 10 LTSC 21H2 Please fix ...

Dev was mean to me when I asked for that on discord, don't expect him to fix it.

**Comment by Jaex** [comment]
> > I have the same thing when upgrading from Windows 10 LTSC 1809 to Windows 10 LTSC 21H2 Please fix ...
> 
> Dev was mean to me when I asked for that on discord, don't expect him to fix it.

Not knowing how to fix it is not being mean. And I don't think it is fixable by our side. Windows supplying the screenshot, which we don't have any control.

This is the screenshot that I was being "mean" I think:

![](https://jaex.getsharex.com/2022/05/DiscordCanary_x7nwQ0qI2j.png)

How dare I don't know how to fix something. It is always same, as soon as I reply and tell I don't know how to fix something, people being angry and calling me rude etc. Like I am supposed to know solution of every problem.

> unsurprising

If you know how to fix it, please feel free to pull request.

**Comment by KaspianDev** [comment]
> 

there is a difference in saying (i don't know how to fix it) and saying (how to fix it) to person not experienced in C# at all

**Comment by Jaex** [comment]
> there is a difference in saying (i don't know how to fix it) and saying (how to fix it) to person not experienced in C# at all

I don't know what is the difference, I wrote short form of it. Because in chat we mainly try to write stuffs short as possible.
