### ISSUE TITLE
Rename "Abort" button

### ISSUE THREAD

**Issue by Mygod** [ShareX/ShareX#6086]
Out of all the English words, why in the world would you call the two buttons "Stop" and "Abort" for screen recordings? Can you please rename "Abort" to "Cancel" (or "Stop" to "Finish"), and preferably have a confirmation for cancelling/undo cancelling? Thank you!

**Comment by navidmafi** [comment]
Hi, long time ShareX user here
I think Stop and Abort both make sense but anyway:
There *is* an option for confirmation dialog on Aborting the screen record

![image](https://user-images.githubusercontent.com/46371349/153419260-408ecb3f-3065-4d6c-9090-052dcf2d22bc.png)
