### ISSUE TITLE
When capturing very small snapshots, the dynamic size information overlaps with the image

### ISSUE THREAD

**Issue by eddeyang** [ShareX/ShareX#609]
When capturing very small snapshots, the dynamic size information overlaps with the image that being captured. Sometimes this is annoying since you can clearly see what is being captured. Is it possible to dynamically place this the size info?

**Comment by Jaex** [comment]
Where I place it?

**Comment by Jaex** [comment]
Okey I removed that outside rectangle info so I can put normal rectangle info top of them:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/05/V6RCgf6NQK.png)

**Comment by eddeyang** [comment]
Cool. Thanks Jaex! Where can I get the compiled version that include this enhancement? The getsharex website still list 9.9 version.

**Comment by Jaex** [comment]
In next release.
