### ISSUE TITLE
Sharex Personal Folder Doesn't Belong Under Documents

### ISSUE THREAD

**Issue by ourichermath** [ShareX/ShareX#6095]
I'm using the version from the Microsoft Store, so I don't know how this applies to other versions.  By default, ShareX puts its Personal Folder under the Documents folder (%userprofile%\documents).  Besides the Screenshots folder (which is odd that it's there since there's a correctly set Custom Screenshot Folder setting right beneath where the Personal Folder is set), nothing in there belongs in a user's Documents folder.  At a guess, I'd say the best place for those items should be somewhere in %APPDATA%.  Another possibility might be %LOCALAPPDATA%.

**Comment by houseofbugs** [comment]
+1 I agree. I am tired of dealing with issues on multiple PCs because I sync my docs folder between all of them...

**Comment by Keith94** [comment]
Solutions posted here: #6130
