### ISSUE TITLE
ShareX don’t work 

### ISSUE THREAD

**Issue by IlyaSafronov** [ShareX/ShareX#6096]
Hello! Yesterday I downloaded ShareX, but this program didn’t work. I have message: 
![64965099-4FB7-4C1F-8028-92E9C5199C91](https://user-images.githubusercontent.com/99478245/153720263-5894f90d-be22-4be6-bd3c-e5588444e58b.jpeg)
Windows 8.1.
I downloaded Framework, but ShareX don’t work…I would like to know the Reason this problem…

**Comment by Jaex** [comment]
ShareX not giving that error, your operating system gives. If your operating system thinks that .NET Framework 4.8 is not installed somehow, we can't know the reason.

.NET Framework installed automatically by Windows Update anyway, so I'm not even sure how you don't have it installed. Perhaps it is corrupted?
