### ISSUE TITLE
Add ability to delete screenshots through toast notification

### ISSUE THREAD

**Issue by vertigo220** [ShareX/ShareX#6098]
This was suggested a few years back in issue #3252 but was closed automatically by the stale bot. I'm hoping it can be given another look.

Reasoning: fairly often, I press the PrtSc key accidentally, due to its location and minimal resistance (scissor key on a laptop, located at the bottom of the keyboard between the right Alt and Ctrl keys).

Suggested ways of implementing:

1. Add a trash icon as suggested in the other issue
2. Add an option under Task Settings > General > Notifications > Toast notification > Left/Middle/Right click action to delete the image
3. In addition to, or instead of, option 2, add an option there to open a customizable context menu, where delete could be one of the items
4. Click and drag/swipe the notification to the side to delete the image (less ideal as harder to do on laptops, where this is more needed)

I realize this can be accomplished by clicking the notification to open the folder to the image, deleting it, then closing the folder, but this is more steps and obstructs the screen more, which is an issue when a screenshot is accidentally captured while watching a video or gaming.

**Comment by datorr2** [comment]
This would actually be a fantastic idea.  It has happened on numerous occasions, and being able to set up an action to immediately delete the erroneously captured image would be convenient!
