### ISSUE TITLE
Is it possible to add a "profile" feature?

### ISSUE THREAD

**Issue by eddeyang** [ShareX/ShareX#610]
I often change my sharex setting between two set of options. 
![Image](http://i.imgur.com/M31Y6mC.png)
and
![Image](http://i.imgur.com/wHVLFcM.png)

I have to manually choose them for now. If we have a "profile" feature, then I can create two profiles for my two set of settings and using a global shortcuts to switch between them. It should be useful. Please consider this. Thanks.

**Comment by Jaex** [comment]
It is already exists called workflows in ShareX...
