### ISSUE TITLE
Image Editor - Option to Disable the "There are unsaved changes..." popup in the Image Editor

### ISSUE THREAD

**Issue by notNSANE** [ShareX/ShareX#6100]
Hi Jaex! So, this is a request from some friends that need this feature for professional work (we're talking about taking 100+ screenshots a day so every click matters).

Basically, this is the flow:

1. Start region capture (screenshot, not video)
2. Highlight some part of the scene
3. Right click the image to confirm the changes, and immediately the image is copied to clipboard AND the image editor closes

Right now, that right click opens that annoying "there are unsaved changes..." popup which is very annoying for them.

Thanks!

**Comment by benSakac** [comment]
Adding a comment to say I would also like to use this workflow without the unsaved changes popup
