### ISSUE TITLE
Do not delete `mp4` if conversion to `gif` fails after capturing video from the screen

### ISSUE THREAD

**Issue by MrChebur** [ShareX/ShareX#6101]
Currently, if you are capturing a very long video and converting it to `gif` format, the process may fail due to lack of memory.

In this case, the original `mp4` file will automatically be deleted, which will make it necessary to re-capture video.

I suggest that you change the program's logic so that the `mp4` file is not deleted if the conversion to `gif` format fails.

**Comment by jfaquinojr** [comment]
For me it wasn't even a long video but it still crashed taking away both mp4 and the gif attempt. I had to be quick and copy the mp4 before it was deleted, then convert mp4 to gif somewhere else for now
