### ISSUE TITLE
Pasting image from clipboard results in poor quality upload

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#611]
I upload to Imgur and from recent days I am noticing that clipboard image content pasted in the app gets uploaded in very poor quality. I have the default settings which means PNG format is used for uploading. I hate saving the image and uploading the file so this has become quite painful. Please suggest if there is any setting that I can change to fix this. I tried switching to JPG/TIFF... Did not improve the quality much.

**Comment by Jaex** [comment]
What you mean poor quality PNG is loseless. Are you mean is it saving jpeg or what?

**Comment by Sushubh** [comment]
Ok. Me bad. Just realized that this problem only started recently. And I just recently installed the Chrome Data Saver app(http://ibf.rocks/1aR5HKD). Please mark this issue as not a bug.
