### ISSUE TITLE
Screen-wide crosshair clipped at zoom-out

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [ShareX/ShareX#6111]
# Steps to reproduce

1) Open image editor with screen-wide crosshair enabled
2) Zoom out a little bit -> see that crosshair does not fill whole editor window anymore:   

https://user-images.githubusercontent.com/46539653/154633835-d9365bc1-8046-4e09-83e7-6c19b9161ac6.mp4

ping @EricTetz, and thank you very much for this must-have feature implementation!

# Version
```13.7.2 dev```

**Comment by Jaex** [comment]
fixed by #6117
