### ISSUE TITLE
Option to run actions without saving the file

### ISSUE THREAD

**Issue by venturozzaccio** [ShareX/ShareX#6112]
Hi,

my need is to resize dynamically a screenshot so I wrote a Python script that reads from the clipboard, resize keeping the aspect ratio and then copy the new image to the clipboard. Putting the script into an action let me perform the trick in a  in a seamless way
The problem I am facing is that it is not possible to perform actions if the file is not saved, in my case saving the file is just taking more time leading to a 1.3 seconds for the whole task.
It could be possible to let the actions run without the need of writing the file?

**Comment by Jaex** [comment]
Why you don't use ShareX image effects to resize image?

**Comment by venturozzaccio** [comment]
Oh, I didn't though I could use 2 effects at the same time. 1 for width bigger than X and 1 for height bigger than Y. Cause using double threshold in the same effect doesn't keep the aspect ratio. 

@Jaex Thank you for the answer, I only wish I found this app years ago :)
