### ISSUE TITLE
my window is stuck in borderless!

### ISSUE THREAD

**Issue by FlashlightET** [ShareX/ShareX#6115]
i set obs to be borderless to see what the option did and now its stuck in borderless mode, ive restarted OBS and its still borderless
![image](https://user-images.githubusercontent.com/29938499/154823992-fa10b24e-52dc-4988-bd62-4f76f7b2ac38.png)

**Comment by Jaex** [comment]
You can press F11 to revert OBS to windowed mode.

**Comment by FlashlightET** [comment]
> You can press F11 to revert OBS to windowed mode.

lol how was i this dense that i forgot the most common fullscreen hotkey thank yoiu

**Comment by eqoffical** [comment]
> You can press F11 to revert OBS to windowed mode.

oh wow, that could work with other programs, but I accidentally "borderlessed" Prism Launcher and I have no idea how to revert it back

**Comment by Jaex** [comment]
Duplicate of #6015
