### ISSUE TITLE
Please bring back the upload option from context menu in the drag and drop window.

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#612]
The reason I ask is that now I have to keep the left sidebar open at all times even though the only use I have for it is to click on the upload button. I know that the upload option was removed from the context menu to remove clutter. It would be great if you can make it an opt-in option from settings. Thanks!

**Comment by Jaex** [comment]
Drag and drop window never had context menu.

**Comment by Sushubh** [comment]
There was an option to upload from this menu. Thanks. 

![mmm](https://cloud.githubusercontent.com/assets/310098/7090740/caa58a86-dfc2-11e4-9e66-dc32988e8bbd.png)

**Comment by Jaex** [comment]
I removed it because it is already exist in Upload menu in left which takes exact click amount to do it.
From right click menu it will be: right click, left click.
From left menu it is: left click, left click.
So same amount of time.
And If you want it to be more faster than you need to use hotkeys anyway.

**Comment by Sushubh** [comment]
Thanks for the hotkey idea. Got it working. Never thought of it! I can now keep the left sidebar closed like before. Thanks again!

**Comment by McoreD** [comment]
This is like Deja Vu. I remember saying this exact thing a few months ago?
From right click menu it will be: right click, left click.
From left menu it is: left click, left click.
So same amount of time.

**Comment by Sushubh** [comment]
I have zero use for the sidebar. I had to keep it open since the option was removed just to access the upload button. Now I can use a keyboard shortcut to get what I want. Though it appears to be a global shortcut so have to make it slightly complicated to avoid hitting it from other apps. My problem is basically resolved. Thanks all.
