### ISSUE TITLE
[Feature request] add right-click "open file location" to captures

### ISSUE THREAD

**Issue by rcoenen** [ShareX/ShareX#6123]
Hi, please add right-click "open file location" to captures so you can quickly access captured content on the local file system.

**Comment by Jaex** [comment]
It is already exists.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2022/02/ShareX_bOa46TuG1D.png)

**Comment by rcoenen** [comment]
That is not what I am referring to: This is immediately after the capture. Typically, I am capturing multiple images and it's then when I like from the gallery view (or Image history) to immediately fine that capture on disk. So just right-click and "open folder" is what I am referring to.  Tools like ie SnagIt etc all use that workflow.

**Comment by rcoenen** [comment]
HI! I really appreciate your actives rapid feedback!

OK so what I meant is probably this:

It should work on any image I have capture - not just the one I immediately capture last


![ShareX_Ez4k5Qf0zr](https://user-images.githubusercontent.com/753704/155246812-b21f6fa6-0145-434c-a24d-7bf2872856c1.png)

**Comment by Jaex** [comment]
You may prefer this option:

![](https://jaex.getsharex.com/2022/02/ShareX_0R8WXWBG2Y.png)

**Comment by Jaex** [comment]
There is also this:

![](https://jaex.getsharex.com/2022/02/ShareX_2uUwDQEOBo.png)

**Comment by rcoenen** [comment]
Thank you! I will try that
