### ISSUE TITLE
[Feature] re edit saved files

### ISSUE THREAD

**Issue by Sicoval31** [ShareX/ShareX#6124]
After saving files (png, jpeg), all things add with sharex are saved in the files, so can't re edit them ; i must re capture my screen and re add my text, circle, line, etc ...
Perhaps a new file format (sharex one) to save the picture and a layer for all shapes made with sharex.

--
 Sorry for my english

**Comment by troegel01** [comment]
Save the project to continue editing --> This feature would make editing much more better.
