### ISSUE TITLE
Cannot get upload using link to work

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#613]
I have never gotten this feature to work. For example... I copied a link to an image: 
http://d3kw6wfam8lfab.cloudfront.net/media/catalog/product/cache/1/small_image/200x100/9df78eab33525d08d6e5fb8d27136e95/j/_/j_5845_1.jpg

I paste it in the window... I get this error: 
![jbsgiuu](https://cloud.githubusercontent.com/assets/310098/7091070/e24f7942-dfc4-11e4-9ba0-9a2be9a7cd7d.png)

Here is the setting option for uploading from clipboard: 
![wfzmf5q](https://cloud.githubusercontent.com/assets/310098/7091091/fd1e8ad8-dfc4-11e4-9d3f-34f8252a67ec.png)

Thanks (and apologies in case I am missing something very simple again!).

**Comment by Jaex** [comment]
I copied your link and pressed clipboard upload hotkey and it was worked for me. Not sure how it won't work for you.

**Comment by Sushubh** [comment]
Thanks! It managed to fix the issue by going through the complete uninstall, fresh install and reconfiguration steps. Not sure how I broke it on my previous install. Should have tried this before posting this bug. Sorry.

**Comment by Jaex** [comment]
Uninstalling won't solve this problem. Capture folder was missing which require you to do single screen capture save so folder would be created.
