### ISSUE TITLE
ShareX personal folder creates itself after changing path

### ISSUE THREAD

**Issue by Keith94** [ShareX/ShareX#6130]
Wanted to move the ShareX personal folder to %appdata%, but there is a strange bug which causes it to re-create

1. Open ShareX application settings
2. Change personal folder to %appdata%\shareX\
3. Exit ShareX
4. Delete %userprofile%\documents\sharex\
5. Start ShareX

Results: ShareX creates a new copy of %userprofile%\documents\sharex\ even though it should stay changed to %appdata%\shareX\

**Comment by Keith94** [comment]
Cool thanks. For anyone wondering, here's how I fixed it:

1. Uninstall ShareX and delete %userprofile%\Documents\Sharex\
2. Reinstall ShareX to %appdata%\ShareX\
3. Create empty `Portable` file in installdir
4. Done

**Comment by Jaex** [comment]
You could make `PersonalPath.cfg` file near where ShareX.exe is and put custom folder path to it. You didn't have to move ShareX.

**Comment by Keith94** [comment]
Good to know. I will try that. Thanks !!

**Comment by pacoochikuputie** [comment]
> Cool thanks. For anyone wondering, here's how I fixed it:
> 
> 1. Uninstall ShareX and delete %userprofile%\Documents\Sharex\
> 2. Reinstall ShareX to %appdata%\ShareX\
> 3. Create empty `Portable` file in installdir
> 4. Done

This I can confirm works.
