### ISSUE TITLE
[Feature Request]Pause button during screen recording

### ISSUE THREAD

**Issue by onlytanmoy** [ShareX/ShareX#6131]
Hiya, please include a pause/resume button during screen recording
![image](https://user-images.githubusercontent.com/48493659/156046449-89059014-e566-4595-8273-3ad9062c17d6.png)
At the moment we just have Stop & Abort, will be nice to have a pause button so that I can pause and resume the screen recording as desired. Thanks.

**Comment by Jaex** [comment]
Duplicate of #205
