### ISSUE TITLE
HDR Screenshots are broken on Windows 10 / Windows 11

### ISSUE THREAD

**Issue by SalmonSays** [ShareX/ShareX#6135]
There are no open issues relating to HDR support, which is a problem. Images of running games for example will appear wrong, generally in a way that is overly washed-out and desaturated.

![20220301142502_1](https://user-images.githubusercontent.com/11697389/156266979-1ea284d2-e42c-41a2-b1b9-55b07603cdc7.jpg)

![unknown](https://user-images.githubusercontent.com/11697389/156266982-5b21441e-8003-4718-9899-267844bbaf25.png)

It's far less important that the final result be in proper HDR, instead it would be preferred for the pre-capture image be tone-mapped properly so that all devices (HDR or not) can view a normal looking screenshot.

It's unclear why *this particular* branch/merge addressing the problem has timed out and been marked as stale without getting any attention: https://github.com/ShareX/ShareX/pull/5565

This is a longstanding issue that only gets worse as more displays ship as HDR certified, please look into merging?

**Comment by Jaex** [comment]
> @Jaex is pure guy, he even don't know what is it HDR....

I know what is HDR and prefer to not enable it in my monitor.

**Comment by werkstrom** [comment]
As I have been struggling with this myself and while fully respecting everyone not activating HDR ;) I absolutely love it on my monitor (it's built for it and basically blinds me if it's off ;) )

However I just learned about a workaround that works just fine for me. 
a) Press Win+Alt+B = switch out of HDR-mode
b) Grab your screenshot
c) Press Win+Alt+B = switch back over in HDR-mode

Since I only occasionally take screenshots and mostly use for illustrative cases, this works fine for me.
Running Win 11 on a GTX1070, if that affects if this works or not.

Not sure if there could be an option to trigger this from ShareX, but it's no longer a big issue for me. Hope it could help someone else. Cheers.

**Comment by urosino** [comment]
chrome://flags/#force-color-profile

![SillyGoaSaturday](https://user-images.githubusercontent.com/25570106/184498707-e46dbd08-ff00-43d5-81a6-e585ce3923b9.png)

**Comment by SkySpnc** [comment]
bumping this. images are over-exposed for me on win11. REALLY annoying when trying to share images of work related things

**Comment by DesolatePsyche** [comment]
windows print screen somehow seems to know how to deal with HDR . Should be doable in sharex as well. So if you ever manage to make screenshots deal with HDR would be perfect app.

Got my self first monitor with fairly good HDR so started using it. I do make a lot of screenshots in-game and on desktop for various reasons,

**Comment by Destreyf** [comment]
I ran into a similar thing, I found that there's a Windows HDR Calibration tool in the store, I just left a comnent on a separate issue, can you guys see if this helps with your setups?

I originally tested with AutoHDR disabled, but even after toggling it on it seems to be correct but maybe I need to restart apps for it to be negatively affected.

[https://github.com/ShareX/ShareX/issues/3751#issuecomment-1364412828](https://github.com/ShareX/ShareX/issues/3751#issuecomment-1364412828)

**Comment by greggman** [comment]
It would be nice if ShareX supported HDR as in saving a 16bit per channel PNG rather than the current lossy version of saving to an 8bit png.

**Comment by Destreyf** [comment]
@greggman I think you can already change this in the options based on this comment: https://github.com/ShareX/ShareX/issues/3521#issuecomment-1368854766

**Comment by greggman** [comment]
@Destreyf AFAICT the only options there are 24bit and 32bit. You'd need 48bit and 64bit to cover HDR

**Comment by vaisest** [comment]
> > @Jaex is pure guy, he even don't know what is it HDR....
> 
> I know what is HDR and prefer to not enable it in my monitor.

Does this mean the official stance is there will be no support at all or what does this mean?

**Comment by SkySpnc** [comment]
> > > @Jaex is pure guy, he even don't know what is it HDR....
> > 
> > I know what is HDR and prefer to not enable it in my monitor.
> 
> Does this mean the official stance is there will be no support at all or what does this mean?

Knowing open source devs, it means the issue is not present as it is not an issue for them tbh

**Comment by ledlamp** [comment]
someone buy jaex a new oled monitor. I got G50SF I can't use it without HDR enabled or everything is too dim.

**Comment by aresstokrat** [comment]
it is still a big issue use ShareX on HDR displays. It is over exposed to light.
