### ISSUE TITLE
You may lose access to some of your third-party apps

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#6141]
Does this affect ShareX?

Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password. Instead, you’ll need to sign in using [Sign in with Google](https://accounts.google.com/AccountChooser?Email=jshollis@gmail.com&continue=https://support.google.com/accounts/answer/112802?rfn%3D1646361360139%26anexp%3Dnret-fa) or other more secure technologies, like OAuth 2.0.

**Comment by Jaex** [comment]
ShareX already using OAuth, so there won't be any problem.
