### ISSUE TITLE
Mouse Cursor Not Visible While Selecting Region/Editing

### ISSUE THREAD

**Issue by TrevorBrown-dev** [ShareX/ShareX#6142]
To clarify, when starting a capture, my mouse cursor disappears. It makes it very difficult to do anything because I cant see where I am selecting. The mouse does reappear if I move it over the ShareX toolbar however, anywhere else it is not visible.
![20220306_093330](https://user-images.githubusercontent.com/69442580/156927748-7932c1dc-660d-4384-9c4c-843450b53fb0.jpg)

**Comment by Jaex** [comment]
It is most likely Windows 11 insider update bug.

**Comment by wasi-master** [comment]
I'm also using Windows 11 insider and facing the same issue. Hope it gets fixed soon :)

**Comment by TacticalTechJay** [comment]
Happens to me too.
Is this version stuff important? I'll drop them below anyways

ShareX Version 13.7.0
Windows Version 22H2 Build 22572.1

**Comment by Jaex** [comment]
It is Windows insider build bug, not ShareX.

**Comment by nnaem** [comment]
@Jaex so it only can get fixed if microsoft pushes an update, what if they doesnt?

**Comment by Jaex** [comment]
Why asking me... I'm not working in Microsoft. If they broken something, I can't fix it for them.

**Comment by TrevorBrown-dev** [comment]
I mean this app is beyond my understanding as is Windows but there isn't
any chance that there's a different way to handle capturing or a workaround
you may know of based on how the method of capturing you implemented works?
I mean it is a new operating system, it may not be as compatible as it used
to be.

**Comment by Jaex** [comment]
How can I find workaround for issue which I can't reproduce. I'm not planning to use dev build of operating system which can have bugs like this. But I'm pretty sure Microsoft gonna fix it, because a lot of apps having this issue right now, not just ShareX.

**Comment by relative** [comment]
> **workaround**

clone sharex repository, `git checkout develop`, save the following patch to a file, `git apply` and build

```diff
diff --git a/ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs b/ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
index ad966fa29..0da49f019 100644
--- a/ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
+++ b/ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
@@ -200,7 +200,7 @@ private void InitializeComponent()
             SuspendLayout();
 
             AutoScaleMode = AutoScaleMode.None;
-            defaultCursor = Helpers.CreateCursor(Resources.Crosshair);
+            defaultCursor = Cursors.Cross;
             openHandCursor = Helpers.CreateCursor(Resources.openhand);
             closedHandCursor = Helpers.CreateCursor(Resources.closedhand);
             SetDefaultCursor();
diff --git a/ShareX.ScreenCaptureLib/Forms/RegionCaptureLightForm.cs b/ShareX.ScreenCaptureLib/Forms/RegionCaptureLightForm.cs
index f663bdb64..9718fe23e 100644
--- a/ShareX.ScreenCaptureLib/Forms/RegionCaptureLightForm.cs
+++ b/ShareX.ScreenCaptureLib/Forms/RegionCaptureLightForm.cs
@@ -75,7 +75,7 @@ public RegionCaptureLightForm(Bitmap canvas, bool activeMonitorMode = false)
 
             InitializeComponent();
             Icon = ShareXResources.Icon;
-            Cursor = Helpers.CreateCursor(Resources.Crosshair);
+            Cursor = Cursors.Cross;
 
             timer = new Timer { Interval = 10 };
             timer.Tick += timer_Tick;
diff --git a/ShareX.ScreenCaptureLib/Forms/RegionCaptureTransparentForm.cs b/ShareX.ScreenCaptureLib/Forms/RegionCaptureTransparentForm.cs
index 504501604..047f035f5 100644
--- a/ShareX.ScreenCaptureLib/Forms/RegionCaptureTransparentForm.cs
+++ b/ShareX.ScreenCaptureLib/Forms/RegionCaptureTransparentForm.cs
@@ -86,7 +86,7 @@ public RegionCaptureTransparentForm(bool activeMonitorMode = false)
             StartPosition = FormStartPosition.Manual;
             Bounds = ScreenRectangle;
             Text = "ShareX - " + Resources.RectangleTransparent_RectangleTransparent_Rectangle_capture_transparent;
-            Cursor = Helpers.CreateCursor(Resources.Crosshair);
+            Cursor = Cursors.Cross;
             TopMost = true;
 
             Shown += RectangleTransparent_Shown;

```

**Comment by wasi-master** [comment]
@relative Thanks

**Comment by sando** [comment]
> clone sharex repository, `git checkout develop`, save the following patch to a file, `git apply` and build

This worked for me, thanks!

**Comment by kodewdle** [comment]
This issue was fixed in **[Windows 11 Insider Preview Build 22567](https://blogs.windows.com/windows-insider/2022/03/18/announcing-windows-11-insider-preview-build-22579)**.
> Fixed an issue which was causing the mouse to be invisible in fields of certain apps, as well as some unexpected cursor related app crashes in recent flights.
