### ISSUE TITLE
Cursor/Zoom is missing after Updating Windows

### ISSUE THREAD

**Issue by 5trubel** [ShareX/ShareX#6143]
After Updating to the latest Windows 11 Insider Build the Cursor and the Zoom went missing.
ShareX Version 13.7.0
Windows Version 10.0.22567 Build 22567

**Comment by Aokromes** [comment]
confirmed, bug also present on 22572

**Comment by Daltz333** [comment]
@Jaex which one is this a duplicate of, they are both closed?

**Comment by sludgepudge** [comment]
Is this being looked at? Or do we know at the very least what change in Windows 11 has caused this?

**Comment by Aokromes** [comment]
> Is this being looked at? Or do we know at the very least what change in Windows 11 has caused this?

the 2 latest insider builds looks they broke something.

**Comment by Cral-Cactus** [comment]
the issue is fixed at least for me works fine rn

**Comment by Aokromes** [comment]
> the issue is fixed at least for me works fine rn

it's fixed on 22579 build.

**Comment by 5trubel** [comment]
Can confirm aswell. 
Working on Windows 11 22579 again
