### ISSUE TITLE
Uploading to imgur

### ISSUE THREAD

**Issue by SandDune800** [ShareX/ShareX#615]
I've been waiting for an update for months but it hasn't happened yet. Auto-upload works but if you don't automatically upload your image, it won't upload at all. 
When you copy the image and select upload to imgur from the menu, all it does is creates a copy of the image in the same folder. Never uploads.

**Comment by Jaex** [comment]
I can't reproduce your problem, it is uploading fine in my tests.

**Comment by Jaex** [comment]
If you are doing clipboard upload and it still not uploads then check this setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/04/ShareX_LYz2VxuaOF.png)

That setting was applying after capture tasks to clipboard upload for give possibility. So you could need to disable it.

**Comment by JoeTheHuman** [comment]
I'm having a similar issue where it gets a URL (somehow), but it's a broken link until I restart the application and attempt to reupload. After I get the broken link issue, anything that I screenshot goes to a broken link until I restart it. I'm not using imgur, just a service named [pxl.lt](http://plx.lt)

I'm running Windows 10, try testing it on there.

**Comment by Jaex** [comment]
Your service link not even opens, how am I supposed to test it?

**Comment by JoeTheHuman** [comment]
I either get a 404 or the page is blank, which probably means the upload failed. It does this after a few hours of not being used, and I find myself restarting the application every time.

**Comment by JoeTheHuman** [comment]
Here's a link: http://img.devjoe.me/WdmmYR.png

**Comment by Jaex** [comment]
You gave wrong url to me.

**Comment by JoeTheHuman** [comment]
That was to the blank photo.

**Comment by Jaex** [comment]
plx.lt is wrong, it is pxl.lt... I give up.

**Comment by JoeTheHuman** [comment]
I run a custom domain through it. Got it now?
