### ISSUE TITLE
ShareX screenshot send to program

### ISSUE THREAD

**Issue by spoonerarthur** [ShareX/ShareX#6155]
Hello together,
i am looking for a solution to send screenshots directly to word, outlook or onenote.

Can you help me?

Thanks, bye spooner

**Comment by subnwa** [comment]
I know there is no option to do this, but you can copy and export your screenshots to these programs. However, if you want to upload to DropBox or OneDrive, you can do so in the destination settings.

**Comment by spoonerarthur** [comment]
I think it works with actions, but I don't understand how it works.
There is an example with paint.exe, but also this doesn't work.
