### ISSUE TITLE
Mouse hidden on screenshots (Windows 11 Dev build)

### ISSUE THREAD

**Issue by Cral-Cactus** [ShareX/ShareX#6156]
So I am on Windows Version 22H2 (OS Build 22572.100) which is Windows 11 dev version and when I try make screenshot I just don't see the mouse to select how big to be screenshot, it works fine on normal windows 11 but on this idk why

**Comment by nnaem** [comment]
same, any way to fix?

**Comment by Aokromes** [comment]
in case you want to upvote the original one https://github.com/ShareX/ShareX/issues/6143
