### ISSUE TITLE
NEW: Amazon Photos | Unlimited full-resolution storage for Prime members

### ISSUE THREAD

**Issue by rolltidehero** [ShareX/ShareX#6160]
Amazon Photos has unlimited full-resolution storage for all of your images and photos.
It's only for Prime members, but it's definitely the best image host I've used.
Can you please add this or help me figure out how to set it up under the custom uploader settings?
It's not the same as Cloud Drive. It's totally separate.

https://www.amazon.com/photos

![image](https://user-images.githubusercontent.com/11590510/158493485-de8d1f52-232e-4c9b-aaba-0de5a176aad8.png)

**Comment by JeromeCos** [comment]
Amazon Drive API has been depreciated, therefore it can't be uploaded through API nor using ShareX
