### ISSUE TITLE
Feature Request: Add the ability to name EFFECTS

### ISSUE THREAD

**Issue by ShowGoShane** [ShareX/ShareX#6167]
![IMG_SHAREX_(Feature_REQ_(EFFECTS-NAMING_001))_SAV_2022-03-21](https://user-images.githubusercontent.com/39810670/159380739-6a9f484f-bfe7-4d1e-ba90-7cfeb7b47613.png)

(please see attached image)

As the image effects in my ShareX grow, get more complex with several more layers of effects - it gets difficult to recall every image attached, what color every line or border is, and especially each snippet of text added (the Title, Header, date, or just some random callout.

So, in the Image Effects screen you have to click on the list of growing Effects on the left-hand side to see what attributes it has and see what is selected in the image to know this information.

It would be great to be able to name the list of effects added to the Presets.
I have effects like an 'image' as my Logo as a watermark, 
I have 'text' that holds the date as a timestamp,
I have 'text' as Headers, Titles, etc.
and, other 'image' effects, which add up to a lot of generically-named items on the left side that could be changed.

Rather than:
image
image
image
text
text

It would read:
Icon-phone
Icon-send button
Logo-Company Logo
Header
Date 

Or, if you have to keep the original names:
image - Icon-phone
image - Icon-send button
image - Logo-Company Logo
text - Header
text - Date 

Thanks for your consideration!
-Shane

**Comment by Jaex** [comment]
Added effect name field:

![](https://jaex.getsharex.com/2022/03/ShareX_fppyfIwmoX.png)
