### ISSUE TITLE
Capture function not working.

### ISSUE THREAD

**Issue by SupraOptimo** [ShareX/ShareX#617]
Since updating to ShareX 9.9 earlier today, my capture function has stopped working. Any time I attempt to use any capture tool, the entire screen goes black. All that is visible is my mouse cursor.
Attached is the result of using the "Window" Capture tool on my current browser screen.

![1](https://cloud.githubusercontent.com/assets/11568462/7104395/55e7a4f4-e08a-11e4-88b6-07a1e1e28ec8.png)

**Comment by Jaex** [comment]
Can you try installing 9.8 back and see is problem continue?

**Comment by SupraOptimo** [comment]
Yes, rolling back to 9.8 solved the problem. I looked at the debug logs between the two versions and there appeared to be no difference.

**Comment by Jaex** [comment]
I heard some anti virus softwares have anti screen capture feature maybe that was white listed previous ShareX version?

**Comment by SupraOptimo** [comment]
Aha, that's it. Webroot's antivirus was blocking screen captures.

**Comment by Jaex** [comment]
So there is nothing I can do about it.

**Comment by mikegoatly** [comment]
If anyone else encounters this with webroot, the steps you need to take to resolve it are:
1) Open the main webroot SecureAnywhere panel by double-clicking on the webroot icon
2) Click the settings ("cog") icon next to Identity Protection
3) On the Application Protection tab, find the sharex.exe entry/entries and change the option from Deny to Protect.

Screen capture should start working again.
