### ISSUE TITLE
[BUG] Install recorder devices button not showing

### ISSUE THREAD

**Issue by kaiserdj** [ShareX/ShareX#6170]
I have version 13.7 (Microsoft Store build) installed and I can't record the audio when I record the screen.
![image](https://user-images.githubusercontent.com/5487950/159481982-77153d0c-0a31-4525-9464-1b834a57bb91.png)
![image](https://user-images.githubusercontent.com/5487950/159481876-7feda83d-ccf3-47ce-8e8f-ed848c4d9651.png)

Thank you very much and greetings

**Comment by Jaex** [comment]
Microsoft Store app can't run installer as admin, which is required to install those devices. Therefore we couldn't add install button in Microsoft Store build.

**Comment by k9gardner** [comment]
So do we need to uninstall/reinstall different version in order to enable the audio recording devices? If so, which one? Will we lose the settings in the process (the key shortcut settings and destinations I've already defined)?

**Comment by ktb-dev** [comment]
a year and a half has already passed, but the problem has not been solved

**Comment by grand-lotus-iroh** [comment]
Had same issue with M$ Build, uninstalled that junked and downloaded official from - https://github.com/ShareX/ShareX/releases/download/v18.0.1/ShareX-18.0.1-setup.exe

* Don't forget to export your settings before uninstall.
* Sharex missing download install recorder devices audio source

BEFORE
<img width="709" height="516" alt="Image" src="https://github.com/user-attachments/assets/01e29b2d-74c2-4903-8f03-acac12fe2622" />

AFTER
<img width="714" height="525" alt="Image" src="https://github.com/user-attachments/assets/d5c2ac76-8094-4c3e-a3a6-d4162bb025fe" />
