### ISSUE TITLE
Burned windows when trying to screenshot

### ISSUE THREAD

**Issue by albiback** [ShareX/ShareX#6171]
Hello,

I don't know if anyone already had this issue but when I try to do a screen capture, the windows ( it appears it only do that with google chrome and brave web browsers) is completly burned. 
I've attached a screenshot of a "burned screenshot" hope is relevant 
![image](https://user-images.githubusercontent.com/34341923/159506151-3b241e05-8187-46f3-ab63-59bb44dd7190.png)

**Comment by botatooo** [comment]
Possible duplicate of #3751. Try disabling HDR.
