### ISSUE TITLE
Tray icon darkens over time  - Windows 11

### ISSUE THREAD

**Issue by truthsword** [ShareX/ShareX#6172]
On Win11 Pro, I noticed that the tray icon (ShareX starts with Windows) is noticeably darker with time.

So I switched to the white icon, hoping that would standout, but it too darkens after a day or so.

![](https://i.imgur.com/LlQZPUO.png)

versus this (freshly launched)

![](https://i.imgur.com/QWAbrhb.png)

**Comment by anonymo0se** [comment]
I think this happens when you use fullscreen programs on non-native resolutions (Example: playing a game on 1920x1080 in fullscreen mode on a 4k monitor). Only affects some tray icons (for some reason) and makes them go fuzzy. I'm not sure whether this is an application issue or a windows issue.

![Q2fQeB9SVR](https://user-images.githubusercontent.com/53087065/164187313-4a129dd0-3d98-4d1d-8abf-d4ea6d790a58.png)

In this image, the leftmost icon is unaffected but the next two are fuzzy.

**Comment by truthsword** [comment]
So no one?

![](https://i.imgur.com/oAq7mWX.png)

Guess which is the ShareX tray icon

**Comment by Jaex** [comment]
Unfortunately I don't know how to fix this, but most likely it is bug in .NET Framework (WinForms) side or operating system side. A lot of apps also have similar issue, so not only ShareX icon is darkening/blurring.

**Comment by vertigo220** [comment]
I've noticed this too with a few apps, on Win 10, so not just a Win 11 issue. Was just wondering about it the other day, so interesting running across this.

**Comment by truthsword** [comment]
FWIW, I've come across postings elsewhere that attribute the problem to how the tray icons are refreshed (repainted?). There are several 3rd party apps involved, and the issue (dating back to W10) seems to have no traction with Microsoft. Apart from rebooting (or restarting explorer.exe), there is no fix (coming).

**Comment by vertigo220** [comment]
That's not surprising. MS is and always has been more interested in chasing the next thing, often changing themes and layout, vs actually fixing problems. There are several problems that I can think of off the top of my head, and I'm sure many, many more, with Windows and various MS programs that have existed for *years* and are just completely ignored. I even messaged them telling them I found an issue where I can 100% of the time cause every Explorer window to crash, and they didn't care enough to follow up and contact me to find out how. I've become convinced they don't even know *how* to fix half the stuff, that it's all grown beyond their capabilities and competence, and they're just winging it at this point, making graphical tweaks to justify their existence.

I'll also add that, for me, this is a relatively new issue, as I never noticed it until recently and I'm noticing it with apps that never had the problem before, so I don't know if they changed their icons and that caused them to be affected by a Windows bug or if something changed with Windows.
