### ISSUE TITLE
Great tool, but...

### ISSUE THREAD

**Issue by kubiqsk** [ShareX/ShareX#6182]
Hello,

I just found out your app and it's pretty cool, but I'm long-years user of PicPick and I really miss some features.
I'm not sure if this is right place where to write it, I just wanted to share few ideas with you, because right now I decided to stay with my old app, because of:

1. I don't want to remember X shortcuts and hotkeys for screenshots - I want to press PrintScreen and then decide if I want to capture scrolling window, fullscreen, region or some window - I was not able to figure out this in ShareX - did I overlooked some settings somewhere?

2. There is no protractor - how to measure angles? I see in ruler tool there is some info about angles, but how to measure angle between 2 objects that are not horizontal or vertical but somehow rotated in space?

3. Is there a way to decide after screenshot is taken whether to upload it or not? I don't want to upload every single screenshot, but it's cool to have 1 click action to do that instantly - some alert/messageBox?

I would really like to migrate from PicPick to ShareX as it has tons of cool features, but these are my issues now - did I overlooked something? Can this be somehow configured already?

Thank you

**Comment by trex005** [comment]
> Is there a way to decide after screenshot is taken whether to upload it or not? I don't want to upload every single screenshot, but it's cool to have 1 click action to do that instantly - some alert/messageBox?

I don't know if this is the only way to do it, but remove the upload step from your capture, then go into the interface and right-click on the capture, and choose upload. I should really change mine to this for videos as I have probably uploaded dozens if not hundreds of gigs, don't want to go through and delete some because I don't know what I have shared or might need in the future, and I have to pay AWS for them monthly. 😂

**Comment by kubiqsk** [comment]
@trex005 eg. when i create screenshot with PP now, this window will appear and that's perfect because on single click or Esc/Enter I can decide if I want upload or not
If I submit upload then it is instantly uploaded and URL is copied to my clipboard
![image](https://user-images.githubusercontent.com/20414087/160477843-c203b5fb-1605-4e0d-9b83-3f0af52296f4.png)

**Comment by trex005** [comment]
In the interface, click ```After Capture Tasks``` and click ```Show "Before Upload" Window```

**Comment by vertigo220** [comment]
I liked the idea of # 1, and maybe in the future Jaex can add a more streamlined, cleaner UI for this, but for now, using hotkeys seems to work pretty well. Just add a hotkey, select task > Other > Toggle tray menu, assign whatever key combo you want, and when you press it, the tray menu will show at your cursor location with the Capture submenu already opened, so you can just pick what you want.

For the protractor, just use the ruler tool and click and drag from the first point to the second. It shows the angle between them as well as a lot of other info.

**Comment by kubiqsk** [comment]
@vertigo220 hm, that's very interesting idea, thanks.
There is also Capture dropdown (second last button) in the topbar that appears when you're doing screenshot, it just doesn't contain all possible captures, so it will be great to add them here too

About protractor - I have no idea how to do that - what should I use as first point and what as second point?
This is how I did this with PicPick: https://share.kubiq.sk/2022-05-18_09-46-08.mp4
This is the image: https://www.mathsisfun.com/geometry/images/acute-angles.svg
But I'm not able to get correct angle values with ShareX
