### ISSUE TITLE
[feature request] screenshot display to the screen

### ISSUE THREAD

**Issue by qstdnx** [ShareX/ShareX#6183]
Can sharex achieve a similar "screenshot display to the screen" function? many screenshot software have this function, such as Snipaste,mouseInc.
![5d21d19039fa355606](https://user-images.githubusercontent.com/20844622/160642948-d63e6b47-20cf-4ef8-b03d-8bebf09d5456.gif)
![5d21d1297c16912524](https://user-images.githubusercontent.com/20844622/160642960-2392a74f-e408-44c0-aea6-3f8e7117dbdd.gif)

**Comment by Jaex** [comment]
Duplicate of #2363
