### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by pedrokleiz** [ShareX/ShareX#619]
It seems that I can't upload the screenshots. The error:
![untitled](https://cloud.githubusercontent.com/assets/6828704/7108476/06a983ec-e15e-11e4-98d9-6f76923b1741.jpg)

**Comment by Jaex** [comment]
Did you tried re opening ShareX?

**Comment by pedrokleiz** [comment]
Did now and it was fixed.
Thank you, Jaex. :)

**Comment by Jaex** [comment]
Your firewall could be causing it (I know because Bitdefender was doing same thing and even for Steam etc.). So problem not to do with ShareX.

**Comment by pedrokleiz** [comment]
I use BitDefender, it could be it.

**Comment by Jaex** [comment]
Yes it doing it.

**Comment by pedrokleiz** [comment]
If it happens again I'll contact BitDefender.

**Comment by Jaex** [comment]
It also happens for other softwares too like Steam etc. and my friends having same problem too. It is unbelievable how Bitdefender still not fixed this.
