### ISSUE TITLE
Video Screen Recording is delayed by 1-2s

### ISSUE THREAD

**Issue by JMargevics** [ShareX/ShareX#6191]
Version used: 13.6.1

Steps to reproduce: 
1) Select Screen Recording, select some region and start recording
2) Click stop and open recorded mp4

Actual result: Video starts 1-2s later than when you started recording
Expected result: Video starts right after you selected the region

A bit annoying, now every time I record anything I have to remember to wait 1-2s in order not to miss anything important in the video :)

**Comment by Jaex** [comment]
ShareX runs ffmpeg.exe to record. That process opens 1-2s delayed in your pc. So nothing we can do about it.

**Comment by JMargevics** [comment]
Makes sense then, thanks for the info!

**Comment by samusxx** [comment]
> ShareX runs ffmpeg.exe to record. That process opens 1-2s delayed in your pc. So nothing we can do about it.

You can OPTICALLY DELAY RECORDING WHILE IT WAITS FOR FFMPEG CUNT
