### ISSUE TITLE
Suggestion: Specific instructions regarding OneDrive and hotkey conflict.

### ISSUE THREAD

**Issue by martinsstuff** [ShareX/ShareX#6193]
I think it could be useful if the message warning about being unable to register hotkeys would instruct the user to press "Print Screen" in order to open the OneDrive dialog. On a fresh OneDrive install it will show "Automatically save screenshots I capture to OneDrive" as disabled, even though it claims the hotkey. In order to fix this the user first needs to press the hotkey and decline in the dialog.

**Comment by Jaex** [comment]
ShareX can't know which application claim the hotkey.

**Comment by martinsstuff** [comment]
It actually does, I forgot to take a screenshot but you can see the identical message here: https://github.com/ShareX/ShareX/issues/6051#issuecomment-1022344543

**Comment by Jaex** [comment]
It guessing by scanning active apps. There is big difference.
