### ISSUE TITLE
Yttr support

### ISSUE THREAD

**Issue by vegbrasil** [ShareX/ShareX#620]
Hi, ShareX is amazing and I would love a Yttr support.

Yttr is a no bullshit website, with a very nice API. No ads, no captchas and the only limit is the file size, 300 MB. They seem to be getting very popular in Asia, so that would be a nice addition.

[Yttr](http://yttr.co)
[Yttr API](https://yttr.co/api)

**Comment by Jaex** [comment]
You telling only limit is file size but they remove files after 12 days which is big deal.

**Comment by hmksq** [comment]
Yttr seems dead now.
