### ISSUE TITLE
Record screen area

### ISSUE THREAD

**Issue by chrispaivacwb** [ShareX/ShareX#6204]
If i try to record a selected area from capture screen option on my second monitor, one big black screen with the message I/O Errors appears and it doesn´t get back to work anymore in that monitor. It does run properly on the main monitor without issues.
![ShareX](https://user-images.githubusercontent.com/52515054/162946430-d0584cfc-47b3-4027-8726-69fb8b6632af.png)

**Comment by subnwa** [comment]
Is FFmpeg installed on your computer? If not, install FFmpeg and try later.

**Comment by chrispaivacwb** [comment]
> Is FFmpeg installed on your computer? If not, install FFmpeg and try later.

As I said it works properly on the main screen. This error only occurs on the second monitor.

**Comment by EzeKees** [comment]
Please try again but first move the monitor to the other side i.e. to the right.
