### ISSUE TITLE
Make automatically uploads opt-in

### ISSUE THREAD

**Issue by pluto-dev** [ShareX/ShareX#6206]
I don't know why this issue #6016 is closed. 
Uploading pictures should always be an opt-in option and not the other way around. It doesn't matter if there is a prompt, the user still can accidently click on yes and maybe upload sensitive information like credit card information.
Educate the user, and tell them that they have the option to upload pictures instead doing it without their consent.

**Comment by Jaex** [comment]
> instead doing it without their consent.

We are not doing it without their consent, we are taking their consent in this dialog:

![](https://jaex.getsharex.com/2022/04/ShareX_ad8aB9Ybw6.png)

> the user still can accidently click on yes

We also thought about that and added 5 seconds countdown to "Yes" button, that way users won't be able to press it for 5 seconds.

![](https://jaex.getsharex.com/2022/04/GUxbcogtnn.png)

As you can see from this screenshot "No" button is immediately clickable but "Yes" button is disabled. So we extra made sure that users won't be able to press "Yes" button accidentally. We even made sure that countdown only counts when that dialog is active. So we are going out of our way to make sure accidentally clicking "Yes" button is not possible.
