### ISSUE TITLE
[Feature request] Specific sharex vector file format

### ISSUE THREAD

**Issue by laulo13** [ShareX/ShareX#6208]
Hi,

Following [my question on discord](https://discord.com/channels/194170124859736065/194170124859736065/964543592326660269) and the No answer from Jaex
I think it would be great to have a special sharex vector file format to allow editing again a edited snapshot already closed. 
I'd love to have this feature.

**Comment by laulo13** [comment]
if I find some time, i will give a try to work on it on my side

**Comment by DanielLaberge** [comment]
What is this a duplicate of? I'd like to track this issue.

It's the only feature I'm missing from Greenshot.

**Comment by Mellumen** [comment]
> What is this a duplicate of? I'd like to track this issue.
> 
> It's the only feature I'm missing from Greenshot.

It's a duplicate of this one I think: #6124  
I think this feature is a must for a complete and feature-rich software like ShareX, compared to other more lightweight alternatives...

**Comment by dlwillequer** [comment]
Agreed - this feature is absolutely essential. Greenshot natively supports the .greenshot extension to support this and SnagIt natively supports .snagx to accomplish this. This is the only feature preventing me from not only using this as my daily driver.
