### ISSUE TITLE
Switch Between Screen and Webcam During Capture

### ISSUE THREAD

**Issue by prahladyeri** [ShareX/ShareX#6209]
This relates to another ticket raised earlier (#3613) which is basically a feature request.

Sharex is a great screen-recording tool which also supports webcam as source apart from desktop, kudos for that. However, the ability to switch between the two sources (desktop and webcam) dynamically is not only a nice-to-have but a useful and wanting feature in tools like these. Especially for those who create presentation videos on Youtube, this is almost an essential these days.

It'd be really great if this can be achieved. Just next to the "Stop" and "Abort" buttons, we can have a "Switch" button to switch the source.

Again, ShareX is a superb and highly useful open source tool, I thank you from the bottom of my heart for it.

**Comment by mpgioia** [comment]
Dynamically switching .. one thing.. what about just more than one video source.. like OBS.. so you can do the ole' small screen being webcam/yourself, and the main ratio of screen being the desktop share.. I don't think you can do dual feeds .. like OBS.. right ? noob asking here ~~

**Comment by berkdemir** [comment]
I would love the OBS like circular video of yourself at a position in the screen. Of course you can use third parties to put your video on the screen as 'always on top', but Sharex has this completeness that also needs this.

**Comment by mbtools** [comment]
Yup... just like Loom
