### ISSUE TITLE
Obfuscate inverted

### ISSUE THREAD

**Issue by MilanRS** [ShareX/ShareX#621]
Can you add option in Greenshot image editor to obfuscate everything but selected area?

http://i.imgur.com/OY46dK5.jpg

I would like to obfuscate everything but url to part of image that is important. Now on image I have opposite situation, url is obfuscated.

**Comment by Jaex** [comment]
It is already exists?

![https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/04/fpbu2wPRTz.png]()

**Comment by MilanRS** [comment]
I don't know when is added that whole set of options, I didn't see this before.
Thank you, I am very glad to see this.
