### ISSUE TITLE
"Copy image to clipboard" isn't copying correct files to clipboard

### ISSUE THREAD

**Issue by Reinbowsaur** [ShareX/ShareX#6212]
When saving an image as a JPEG for example, and having the after capture setting "Copy image to clipboard", it will copy the incorrect file to the clipboard.

I have provided an example of resulting images I get using the following after capture settings 
![image](https://user-images.githubusercontent.com/51115162/163791092-74485b1f-bf32-48b0-923b-36ed70e3ff54.png)

_**What is saved to disk**_
![mc 202204180705PM](https://user-images.githubusercontent.com/51115162/163790079-1d9fdf6e-93bb-43d4-980c-f8b47e1865ec.jpg)
_**What is saved to clipboard**_
![image](https://user-images.githubusercontent.com/51115162/163790063-8d1e5476-4a81-464c-99cc-67fa74ee64d0.png)

**_Expected behaviour_**
I'm expecting the low quality pjeg to be the one copied to clipboard, not a high detailed png.

**Comment by Jaex** [comment]
Images are stored as bitmap in clipboard, not png or jpg.
