### ISSUE TITLE
sharex crashes on startup (error log)

### ISSUE THREAD

**Issue by vibemeister** [ShareX/ShareX#6215]
System.BadImageFormatException: Could not load file or assembly 'ShareX.UploadersLib, Version=13.7.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.UploadersLib, Version=13.7.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

ShareX 13.7

**Comment by Jaex** [comment]
It looks like your ShareX installation got corrupted, try reinstalling it.

**Comment by vibemeister** [comment]
that worked, thanks
