### ISSUE TITLE
When connecting to a second monitor screen captures only allow portions of the screen

### ISSUE THREAD

**Issue by tolgabalci** [ShareX/ShareX#6225]
I undock my Dell XPS 17 and dock it back often and when I need to do a screen capture it is most of the in a confused state.

For example when I press the hotkey for the screen capture on the screen I am on, part of my monitor's screen suddenly appears to the right of the current monitor I am on (kind of like an instant screen split), but only showing a small section and I am only allowed to select inside of that area, which often does not contain the content I need.

There is no fix, nothing you can do that will fix this, even if I undock my laptop it is still in this odd ball state.  Only thing left to do is Quit the app and restart it.  Which fixes it 100% of the time.  But highly annoying.  I only need to do screenshots a few times a day, and almost every single time it's in this screwed up state, which then I need to restart ShareX for.

I'm running the latest version of ShareX on the latest version of Windows 10.
I use two monitors:
DELL XPS 17: 1920 x 1200
SAMSUNG Curved 55": 3840 x 2160
I am using the latest version of PowerToys Fancy Zones to split the screens and I do use multiple desktops (built in Win10 tech).

**Comment by Jaex** [comment]
FancyZones causing this, so it is nothing to do with ShareX.
