### ISSUE TITLE
Sharex Delay when capturing rectangle

### ISSUE THREAD

**Issue by szumlanski** [ShareX/ShareX#623]
When I attempt to capture a rectangle on my multi-monitor setup, Sharex freezes my computer for 10-15 seconds. Then the crosshairs appear and I can capture. Also, I have four monitors, 2 each on two graphics cards. The two monitors on the secondary card go black when capturing. That is not so much of a problem, but the delay is agonizing. Windows 7 x64. Same version 9.9 works fine at home on Windows 8.1 with dual monitors.

**Comment by szumlanski** [comment]
Corrections and Clarifications:

9.0, not 9.9.

Active Window and Active Monitor captures work instantly and perfectly, showing the Toast window with no delay.

Fullscreen, Rectangle, and Window & Rectangle captures all have 20 second delay before crosshairs appear, then once rectangle is selected the Toast window appears instantly.

**Comment by Jaex** [comment]
So is it faster in 9.9 or not?
Did you checked is screen capture delay feature is disable in that hotkey settings?

**Comment by hclewk** [comment]
I'm getting a 2 to 3 second delay when capturing rectangle. I have 3 monitors. I did verify that screenshot delay was disabled.

http://coppy.me/Ejyy.png

Using ShareX 9.9

**Comment by Jaex** [comment]
Try disabling this ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/04/ShareX_5oyuW0P1RH.png)
