### ISSUE TITLE
No longer able to create forks

### ISSUE THREAD

**Issue by Aholicknight** [ShareX/ShareX#6230]
![image](https://user-images.githubusercontent.com/7843719/165151938-8996593e-f539-4652-9bbd-8ab7e93eac24.png)

I would like to contribute to this github repo but for some reason it not allowing me to fork this repo. Is there some sort of fork limit? I never had this problem before on Github with other repos and other people are having the same problem as shown [here](https://github.com/netlify/netlify-cms/issues/6445#issue-1212340448) and [here](https://github.com/fluxcd/website/issues/890)

**Comment by Jaex** [comment]
We did not touch any settings. So you should contact GitHub support.
