### ISSUE TITLE
Can I move the folder in Documents?

### ISSUE THREAD

**Issue by LAPIII** [ShareX/ShareX#6232]
I thought I could using the Registry Editor because it says [here](https://getsharex.com/docs/command-line-arguments#personal-path) under Registry. I don't have `HKEY_LOCAL_MACHINE\SOFTWARE\ShareX` nor `HKEY_CURRENT_USER\SOFTWARE\ShareX`.

**Comment by LAPIII** [comment]
OK I created the subkey `ShareX`. Am I supposed to create a String Value called PersonalPath?

**Comment by LAPIII** [comment]
> OK I created the subkey `ShareX`. Am I supposed to create a String Value called PersonalPath?  I so, then what? Do I just drag the folder where I want?

**Comment by vertigo220** [comment]
Only thing I can think is maybe your path is formatted incorrectly. If you could post a screenshot of the entry in regedit, or export the key and post that, it might help. Otherwise, I just use the PersonalPath.cfg file in C:\Program Files\ShareX, so you could try that.

**Comment by LAPIII** [comment]
I don't think I have PersonalPath.cfg in C:\Program Files\ShareX. I do have `HKEY_LOCAL_MACHINE\SOFTWARE\ShareX` and will attach a screenshot of the key and subkey

![Program Manager_17-5-22 10⦂37⦂17 PM](https://user-images.githubusercontent.com/7947363/168945758-d328ec7c-4aa5-4152-9062-b559ffddd436.png)
