### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by gaitat** [ShareX/ShareX#624]
I would like to add both a text watermark and a video watermark when I do screen recording with ffmpeg but it seems that I can only do either of the two but not both. When I specify both commands under "Additional command line arguments" the later one is always executed.

**Comment by Jaex** [comment]
http://stackoverflow.com/questions/6195872/applying-multiple-filters-at-once-with-ffmpeg

In here solution tells you need to use comma to separate two different filters.
