### ISSUE TITLE
All sounds stop after taking a screenshot

### ISSUE THREAD

**Issue by tumuidle** [ShareX/ShareX#6240]
After the screenshots, the sound output of all the software was gone, including the video that had been paused  
Platfrom: Windows 11
Steam version

**Comment by vertigo220** [comment]
I assume you have it set to play a sound when taking a screenshot? Did you try disabling that to see if it still happens? Did you check to see if the volume somehow was turned down or muted or the audio device was changed? What do you have to do to get sound back? Is it enough to just close and reopen the paused video, or do you need to restart the computer, or somewhere in between. The more info you provide, the better others can help.

**Comment by A2577467404** [comment]
After taking a screenshot and playing the sound again, there is still no sound for a while
Sometimes it takes a while to automatically recover, sometimes you need to switch Audio devices multiple times, and in rare cases I need to restart Window Audio
I didn't change the volume before and after the screenshots

**Comment by A2577467404** [comment]
Error popup in foobar2000 after screenshot: Unrecoverable playback error: Unknown error (80040154)

**Comment by A2577467404** [comment]
Error no longer occurs after "Play sound after task is completed" and "Play sound after capture is made" disabled

**Comment by vertigo220** [comment]
A few thoughts:

- Does it occur with just one or the other of those options enabled?
- Have you tried with a different sound file?
- Have you restarted the computer and tried again?
- Try reinstalling your audio drivers

**Comment by A2577467404** [comment]
Error no longer appears after using custom audio

**Comment by vertigo220** [comment]
So it's the default audio file that does it? Can you upload the audio file so I can compare against mine and test it?

**Comment by vertigo220** [comment]
Also, did you try switching back to the one that caused the problem and see if it messes up again, or if simply the act of changing it fixed it?

**Comment by QuackCocaine** [comment]
I'm encountering the same issue but for me, occasionally instead of just silence I get a rather loud and annoying buzzing sound until I restart my computer

**Comment by diamondo25** [comment]
For what its worth, I have this issue too on Windows 10. I don't recall this issue prior to installing Razer software for my headset.
