### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by aagha** [ShareX/ShareX#6244]
I'm running into an issue that it seems many others have run into, but I'm not finding a solution that works for me.

I've downloaded ffmpeg from within ShareX:

![image](https://user-images.githubusercontent.com/5522103/166851497-423c6db0-d55b-4bbb-aa2c-12e958c00455.png)

Here's the version it's pulling down:

![image](https://user-images.githubusercontent.com/5522103/166851533-450ade4f-f1ab-467d-8d52-2ca574e90100.png)

When running the CMD as Admin from the bottom of the Screen Recording Options window, I get:

![image](https://user-images.githubusercontent.com/5522103/166851584-515e1a90-db82-4188-8b85-f9718ca3399d.png)

I've installed the recorder devices and played around with different video sources, but get similar errors:

![image](https://user-images.githubusercontent.com/5522103/166851664-8b0c06a3-e137-4b3b-9215-462ed5f1f877.png)

**Comment by Jaex** [comment]
Most likely your anti virus software blocking ffmpeg.exe access to Documents folder.

**Comment by aagha** [comment]
Excellent! Thanks.

Gave ffmpeg permissions here and it worked:

![image](https://user-images.githubusercontent.com/5522103/167033917-f2a035dc-8e13-4483-9e5c-147d286b2582.png)
