### ISSUE TITLE
ShareX Update issue

### ISSUE THREAD

**Issue by ZenoxVIP** [ShareX/ShareX#6246]
Everytime i start my PC i get a popup to tell me theres a new version.
When i click yes, then it gets installed and when i open the app it tells me its the new version, but everytime i restart my pc or just boot it up the update seems to have reset and its back to the old version.

Current Version: 13.4

Thankx for help

**Comment by Jaex** [comment]
You have two different ShareX is installed in different locations. So old one running at startup. Uninstall both and reinstall ShareX again.
