### ISSUE TITLE
suggestion: add more increase font options

### ISSUE THREAD

**Issue by playmobilmeister** [ShareX/ShareX#6249]
Hi,

thanks for this amazing project. I am trying to enlarge the appearance of the text, but some elements are not affected. see example in the screenshots. I increased the font size from 9 to 14 and then to 20 and some elements (including some aspects of the settings windows stay unchanged. This is a bit too small for me to read without effort. If there's something that I've missed. let me know pls.
![g3umu7PRVE](https://user-images.githubusercontent.com/33288162/167295975-bea17a30-6e5b-4ef4-8a02-432528d15207.png)
![oYm7Mkdudb](https://user-images.githubusercontent.com/33288162/167295979-8a294702-7615-4346-bf9f-e718d310784b.png)
 

using version 13.7 for windows

**Comment by gitgrub** [comment]
Same here, increasing menu font size works good, but settings fonts are too small for me, hard to read.

**Comment by hotellinawebmaster** [comment]
same issue here, I would love to see settings to increase font size.

**Comment by carlcrafteycom** [comment]
+1 on higher resolution displays these buttons are far too small...
![image](https://user-images.githubusercontent.com/99428314/225386885-111ce3cc-d086-4b68-96ba-6661621ef834.png)

**Comment by StraggleCraft** [comment]
+1 on higher resolution displays these buttons are far too small
![buttongs](https://user-images.githubusercontent.com/10663364/225387721-28448963-8e1f-4532-9551-6fc35cac0fe9.png)

**Comment by leeuniverse** [comment]
Ya, this is a SERIOUS problem for me....  I don't know how many years it's been, more than 15.... but I just can't get myself to use ShareX because everything is so SMALL.

It's "unusable"....  I wish they would create a proper modern UI, good sized, easy to read.
