### ISSUE TITLE
"Open in image editor" creates useless .bmp object

### ISSUE THREAD

**Issue by bbseal** [ShareX/ShareX#6250]
Editing this to rephrase.

**Observed behavior:**  When "open in image editor" is selected as an after-capture task, a .bmp object is created in the main window and the history window.  This .bmp object is not saved on the filesystem, has no meaningful options available on right-click, and has no apparent relationship to the object that is opened in the image editor.  If "save image to file" is also selected as an after-capture task, no image is saved.  If the object that is in the image editor is manually saved, a new file name is chosen that does not match the .bmp object.  The .bmp object remains unchanged and the saved. png does not appear in the main window or the history window.

**Expected behavior:**  (With save) The object appearing in the image editor would be immediately saved as a .png.  The objects in the main window and the history window would match the .png, and would have all standard options available on the right-click menu, such as editing and adding effects.

Edit 2:  I see now that I have to "Continue" the task in some manner in order to prevent this dangling .bmp object.  I think it would make sense to at least remove the .bmp object in the main window and history if the task is not continued, or if the item is Saved from the image editor, consider the workflow continued.  If Save image to file is also selected as an after capture task, again consider the workflow continued.

**Comment by bbseal** [comment]
I've found older issues related to this behavior, and the whole editor workflow doesn't make any sense.  If I have "Save image to file" as an after-capture task, my intention is obviously to save the file, not _maybe_ save the file.  The primary reason I also "open in image editor" is to look at what I've just captured, and possibly edit it.  But now I have to "continue" the task just so I can ensure the file is saved, but since this closes the editor, I have to go back and open the editor again!

**Comment by strigona** [comment]
I'm experiencing the same issue. If I have "Open in image editor" other tasks do not work correctly. Ex:

* copy image to clipboard does not work
* save image to file does not work
* history is wonky, shows a placeholder that points to nothing

**Comment by notrapha** [comment]
Same issue, if I use "Open in image editor" it creates the empty bmp, and some options like "show in file explorer" are not working. 
Deactivating it solves the issue, but after a snapshot I would like to open directly in the editor...
