### ISSUE TITLE
Misaligned Cursor when Windows Display Settings is beyond 100%

### ISSUE THREAD

**Issue by GreenDude120** [ShareX/ShareX#6256]
I am aware that switching windows display scaling back to 100% will allow my cursor in the video or gif to be exactly where im clicking and that using 150% (as i do) causes the mismatch. but is there any plans for sharex to detect the % and fix the alignment in a future version? it looks bad when clicking a button and changing my display settings everytime is inconvenient which is the opposite of sharex's goal of being a super convenient share tool.

example: https://greendu.de/i/BUa.gif

**Comment by GreenDude120** [comment]
@Jaex yes ive seen a github issue about this way back in 2016 but now its 2022 and this still happens. maybe we can stop tagging it as a duplicate issue and let this ticket be bumped up in priority so it finally is addressed?

**Comment by Jaex** [comment]
I already addressed it countless times in those issues. If you read them you would know that it is not ShareX fault.

**Comment by GreenDude120** [comment]
this doesnt happen in other tools. there are ways around it that sharex could still handle. are you suggesting we wait until Microsoft fixes it? that's ridiculous.
