### ISSUE TITLE
Screenshot in screenshot

### ISSUE THREAD

**Issue by t0ry003** [ShareX/ShareX#6259]
Hello! I have randomly found something frustrating if u ask me.

### Issue reproduction:
- `press the screenshot key` - starts one screenshot
- `press the screenshot key again` - starts the screenshot while another screenshot is in process
- This can run as many times u want but after the third repetition you cant press ESC to cancel

### Photo reproduction (pressed twice):
![image](https://user-images.githubusercontent.com/80108119/168644539-4c384c3c-121e-475e-85bd-638899031cc9.png)
I moved the toolbar for showing the issue.

**Comment by Jaex** [comment]
It is intentional, so you could screenshot region capture.

I could press ESC to cancel even after 10 repetition.
