### ISSUE TITLE
ShareX 9.8 constantly reminding about 9.9 update

### ISSUE THREAD

**Issue by akamud** [ShareX/ShareX#626]
ShareX is reminding me about the new update about every hour (I don't have the exact amount of time it asks for update, but is constant enough to make me close the app).  
From what I remember it usually checks for update when I start my computer, but now it is asking too frequently, even when I click the button to ask me later.

Is this expected?

**Comment by Jaex** [comment]
Yes expected because sometimes people not close computer for weeks.
