### ISSUE TITLE
After uploading to youtube video is blocked

### ISSUE THREAD

**Issue by dimmduh** [ShareX/ShareX#6262]
Youtube blocks video after uploading by reason "Spam"
Tested by 2 persons from different ip.

**Comment by dimmduh** [comment]
![image](https://user-images.githubusercontent.com/446814/169490005-8e4c6144-91c0-47b5-9c4f-900b31eeabe1.png)

**Comment by Jaex** [comment]
If YouTube blocking the videos, what can we do about it?

**Comment by dimmduh** [comment]
When upload same video manually - Youtube does not ban video.
When via shareX - Youtube bans immediately.

**Comment by swk23C8** [comment]
Seems like a problem where ShareX's YouTube API is not verified.
source:
https://stackoverflow.com/questions/64079139/using-youtube-data-api-makes-my-videos-private-on-upload/64080239#64080239
https://stackoverflow.com/questions/70422258/youtube-api-with-internal-app-is-forcing-videos-to-go-private-locked

**Comment by Jaex** [comment]
It is verified.

**Comment by dimmduh** [comment]
It seems now the problem gone.

**Comment by swk23C8** [comment]
it's working on my end as well
