### ISSUE TITLE
Feature request: add "pause" button to screen recording

### ISSUE THREAD

**Issue by rcoenen** [ShareX/ShareX#6264]
In addition to the "Stop" and "Abort" buttons while recording, add a "Pause"/"Resume" button.

**Comment by spunkerman** [comment]
Duplicate of #205

**Comment by iahmedsheraz** [comment]
Really need this button, all other works are just awesome. 
Thanks developers

**Comment by chenyjay** [comment]
Yes, We really need this function.

**Comment by MRefaie83** [comment]
really need it.
