### ISSUE TITLE
Animated webp in ShareX

### ISSUE THREAD

**Issue by huangwb8** [ShareX/ShareX#6271]
I use ShareX and its action to convert PNG to WebP.

Here is the action settings:

![chrome_mQqg6SXIf6](https://user-images.githubusercontent.com/35643122/169782525-e6d0a943-ba62-4781-88bd-9d8adb9684c4.png)

However, if I use the multiple region mode of ShareX, the webp would be animated, which could not be uploaded to Chevereto.

![chrome_0zBlAM4PGt](https://user-images.githubusercontent.com/35643122/169783114-907b244e-2cb6-4b5c-bf07-e2f6995cf4b6.png)

But actually it's just a photo, not something like gif.

How could this happen?

**Comment by Jaex** [comment]
I have no clue, this not makes sense. But in any case it looks like something cwebp doing and not ShareX. Are you sure that it is animated?

**Comment by huangwb8** [comment]
@Jaex 

Thx!

It's exactly the problem of cwebp software. I had converted to use `imagemagick`. It works perfect!

Here is the setting I use:

![zEnwG87Hsv](https://user-images.githubusercontent.com/35643122/169855888-1e2c75cf-35c5-4307-bc3a-5abd32891638.png)

![image](https://user-images.githubusercontent.com/35643122/169856013-ea6357bf-6105-46d9-9f63-74cfcb13c04d.png)

Here is another detailed tutorial For Chinese: [Use ShareX as a WebP creator](https://blognas.hwb0307.com/skill/993)

国内的老铁可以看我的博客教程：[终极截图王ShareX支持webp](https://blognas.hwb0307.com/skill/993)
