### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Hunter23071985** [ShareX/ShareX#628]
Boomer version here:
http://rsload.net/soft/manager/11759-sharex.html

**Comment by Jaex** [comment]
What can I do if they made Russian patch instead adding it to ShareX as translation which is really hilarious.

**Comment by Hunter23071985** [comment]
How to add a ShareX russian translation officially?

**Comment by Jaex** [comment]
What is Boomer?

**Comment by Hunter23071985** [comment]
He does repackaging programs. How to contact them I do not know...
