### ISSUE TITLE
CTRL+Copy for coping image file does not work from chronic 

### ISSUE THREAD

**Issue by janrrrr** [ShareX/ShareX#6289]
Hi there,

its my first issue report so please let me know if I miss something.

Issue is, that if I want to copy the imagefile with CTRL+C while I have marked the file in my chronic (using share x in German, so it might be history, see the screenshot), it does not store the file in my clipboard. ALT+C for copying the image itself does work.

![grafik](https://user-images.githubusercontent.com/19164759/173083305-ff3d5c13-85b5-4324-acfc-bf8cf80a6fb7.png)

Running on W10 with no other software for screenshots or clipboard impact (besides keepass).

Best regards!

**Comment by Jaex** [comment]
ctrl+c copies URL, shift+c copies file.

**Comment by janrrrr** [comment]
Well, you´re absolut right - probably a miss of coffee. Sorry!
