### ISSUE TITLE
Sound recording

### ISSUE THREAD

**Issue by Hunter23071985** [ShareX/ShareX#629]
The video quality is excellent, but no sound...

**Comment by Jaex** [comment]
Already exist.

**Comment by Hunter23071985** [comment]
Where? I can not find a copy?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/04/A9Pi5TaAS9.png)

**Comment by Hunter23071985** [comment]
Thank you so much!
