### ISSUE TITLE
dropobx service is not authorized broken

### ISSUE THREAD

**Issue by f1h0** [ShareX/ShareX#6290]
yesterday I tried to upload a photo via dropobx there was an error, I thought something happened and decided to remove the authorization
and pass it again here is the error

![image](https://user-images.githubusercontent.com/1436880/173280423-f61c5847-fb6b-4e53-899f-ba536c97f1b6.png)

**problem logging in with mega drive**

![image](https://user-images.githubusercontent.com/1436880/173280474-9df571f0-a2ca-48dd-9446-17a3570e32c9.png)

**Google drive error autorization** 

![image](https://user-images.githubusercontent.com/1436880/173281683-97d01552-82d5-44b9-95d7-5deab71f4060.png)
![image](https://user-images.githubusercontent.com/1436880/173281689-ab606d47-edb8-41bf-9a0a-c19707adb21f.png)

OS: win 7 64
ver: 13.7

logifle
[ShareX-Log-2022-06.txt](https://github.com/ShareX/ShareX/files/8887926/ShareX-Log-2022-06.txt)

**Comment by Jaex** [comment]
ShareX library files become corrupted, try reinstalling ShareX.
