### ISSUE TITLE
OCR not picking up Slurs

### ISSUE THREAD

**Issue by Skizzles** [ShareX/ShareX#6292]
Hello,

I use ShareX for my work in trust and safety moderation and it seems that the OCR will often not pick up the N word and other terms of Hate Speech.

Is there a setting blocking this? or is it designed this way?

**Comment by Jaex** [comment]
We are using offline OCR now in dev build. Can you try that?

**Comment by Skizzles** [comment]
> We are using offline OCR now in dev build. Can you try that?

The OCR gets stuck on processing in the latest dev build

**Comment by Jaex** [comment]
I'm unable to reproduce it.

**Comment by Skizzles** [comment]
> What is your Windows version?

Using Windows 11, Version 10.0.22000 Build 22000

**Comment by Jaex** [comment]
Is debug log shows any error related to ocr?

**Comment by Skizzles** [comment]
> Is debug log shows any error related to ocr?

It freezes the entire program to where I have to force kill it. Logs only show:
2022-06-15 18:59:20.634 - Executing: OCR

It keeps "OCR is processing." on the screen but has not processed after 30 minutes.

**Comment by Jaex** [comment]
That is very concerning but because I or any other people I asked couldn't reproduce it, I can't figure out what causing it :(

**Comment by Skizzles** [comment]
> That is very concerning but because I or any other people I asked couldn't reproduce it, I can't figure out what causing it :(

I wish I had more details to give. It does not happen on the stable build though. So definitely something with the OCR changes.

**Comment by Jaex** [comment]
Check #6317

I wish you told that you were using OCR hotkey with silent OCR option, that way I didn't had to release another version now :(
