### ISSUE TITLE
Screenshot and video capture don't respect windows mouse cursor size settings

### ISSUE THREAD

**Issue by hybridherbst** [ShareX/ShareX#6294]
When adjusting the cursor size in windows, this is unfortunately not respected in either screenshots or mp4 captures.
I found
- #2291 

and tested some of the workarounds mentioned there, but I think this relates only to windows DPI scaling, not mouse cursor size, so I think it's a different issue.

Here's the dialogue where cursor size can be set:

![image](https://user-images.githubusercontent.com/2693840/173618415-5e5160e0-5854-4639-8bbc-eda3cfe63e59.png)

**Comment by hybridherbst** [comment]
What's this a duplicate of @Jaex?

**Comment by Jaex** [comment]
#5055

**Comment by hybridherbst** [comment]
Why are you closing both of these if it's not actually fixed? I understand the discussion about this being hard(er) than it looks, but I'd at least keep one of the issues open – that way people like me actually have a chance of finding them and not opening duplicates. Thanks!

**Comment by hybridherbst** [comment]
Thanks for the explanation. Bad stale bot :) 

Out of curiosity and to understand the issue better:
- ShareX (or ffmpeg?) composes the cursor on top of the captured image (which is captured without cursor in any way)
- Windows does not provide enough information to compose the cursor correctly (correct size)

Is that correct?

**Comment by Jaex** [comment]
Thanks I will check it.
