### ISSUE TITLE
Can't record audio with screen recorder

### ISSUE THREAD

**Issue by Elmuti** [ShareX/ShareX#6298]
I noticed screen recorder wasn't recording audio and went to options, [turns out there's no audio source available to use?](https://i.imgur.com/4VoY6p8.png) I tried "install recorder devices" and while it ran through some installation dialogs it didn't actually seem to install anything. 
Using version 13.7 that I downloaded a week ago on a fresh windows installation.
ffmpeg should be latest version as well from their own site, properly linked to sharex

**Comment by Jaex** [comment]
You must update ShareX to dev build for latest FFmpeg support.
