### ISSUE TITLE
Irritating bright white UI flashes

### ISSUE THREAD

**Issue by Dark-Magician** [ShareX/ShareX#6299]
![ShareX - Bright white flash](https://user-images.githubusercontent.com/19816749/174508201-ba341559-c999-479d-8bda-b75492f7410e.gif)

These flashes, which manifest in other programs, are a significant problem that causes eye strain and other associated negative health issues. Please, fix it. If it helps, this [commit](https://github.com/mltframework/shotcut/commit/a72b757c72ef085bfecebb7e379d1dd05a0667f9) fixed it in Shotcut, and I think these commits in Sandboxie Plus:

https://github.com/sandboxie-plus/Sandboxie/commit/667535cdbe11115c44f7110ab3f800ba4844b409
https://github.com/sandboxie-plus/Sandboxie/commit/401e3d33570d02923bd51cef9aa8435800b90785
https://github.com/sandboxie-plus/Sandboxie/commit/0b1b4af79a366896ae3089214391880cb8c98b70

The developer of Sandboxie Plus referenced the Shotcut commit, extrapolating the fix to all dialog windows of all sizes in Sandboxie Plus.

ShareX version: 13.7
OS: Windows 10 Pro 21H2 64-bit

**Comment by sguergachi** [comment]
Agreed these are pretty irritating. Would be great if it was fixed
