### ISSUE TITLE
ShareX breaks `winver` search in windows 11

### ISSUE THREAD

**Issue by DoctorKrolic** [ShareX/ShareX#6305]
Before installing ShareX, I could search in windows search for `winver` and the search result just opened the `winver` app with windows information. However, after I installed ShareX when doing the same thins it doesn't open `winver.exe`, but tries to upload this file to the dropbox, which is very annoying. Please fix

**Comment by L1Q** [comment]
As a workaround, use Run (Win+R) instead of searching.
