### ISSUE TITLE
In-App (steam) after waking pc from sleep

### ISSUE THREAD

**Issue by Furrypaw** [ShareX/ShareX#6307]
ShareX seems to show up as In-App even when the setting is set to disabled after waking up pc from sleep.
Restarting sharex seems to fix the issue until next time.

**Comment by eminyilmazz** [comment]
This issue persists, I need to restart ShareX to not appear In-App on steam after waking up windows from sleep/hibernate.

**Comment by Jaex** [comment]
Unfortunately Steam update improved in-app detection and we can't figure out a way to bypass Steam detecting our app and showing in-app anymore.
