### ISSUE TITLE
Sharex not pasting images on word or teams but it does on paint - Windows 11

### ISSUE THREAD

**Issue by Txank** [ShareX/ShareX#6309]
Greetings,
This is my first message and I hope this issue has not been addressed before, please feel free to close/delete the post if it has already been solved.
After installing Sharex on windows 11 it doesn't paste the image on teams or word. In fact in word it creates a blank image.
It is weird because I can paste on Microsoft paint and if I check the Sharex image folder, screenshots are being created ok.

**Comment by Tragen** [comment]
I have the same problem since one of the last releases but with xwiki or GitHub.
I cannot paste images there.

**Comment by Txank** [comment]
So maybe a previous release as a workaround might work, have you tried that?

**Comment by Tragen** [comment]
My workaround is to click on "Annotate" and click the "Copy to clipboard" button there, then it works also.
I don't know what's the difference in the code but this way it works. So there is a bug in the other code path.

**Comment by Jaex** [comment]
Did you enable alternative clipboard methods from advanced tab?

**Comment by Tragen** [comment]
Seems I did. It was enabled. Disabling the option makes pasting working again in xwiki for me.

**Comment by Jaex** [comment]
There is a reason that options are not enabled by default, because not all apps supports every kind of clipboard format.

**Comment by glca18** [comment]
Thank you @Jaex - solved my headache too! 😊
