### ISSUE TITLE
Getting text from screen

### ISSUE THREAD

**Issue by Hunter23071985** [ShareX/ShareX#631]
Preferably with font recognition.

**Comment by Baegus** [comment]
Why? You can just copy it.

**Comment by Jaex** [comment]
This is beyond ShareX.

**Comment by Hunter23071985** [comment]
I mean capture text from folder trees, file lists, database reports, messages and dialog boxes.
There are implementation in C ++ and programs such as Kleptomania (paid) or GetWindowText (free).
This function periodically very necessary.
