### ISSUE TITLE
OCR is freezing

### ISSUE THREAD

**Issue by Eikosa** [ShareX/ShareX#6317]
when i use ocr the whole app freezes and i can't use it, if i close and open the program it gets resolved

**Comment by Eikosa** [comment]
It was working fine in the previous version.

**Comment by Eikosa** [comment]
shortcut not working but working normally
![image](https://user-images.githubusercontent.com/20538090/176956101-3d7e6fb4-e4ee-42e5-957d-2a1e6ffbf962.png)

**Comment by Jaex** [comment]
Previous version was using online OCR, now we are using offline OCR from: https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr which is only available to Windows 10 or newer versions.

We are unable to reproduce the issue unfortunately. We also asked multiple people to test it using different Windows versions yet OCR was working fine in everyone.

**Comment by Eikosa** [comment]
![image](https://user-images.githubusercontent.com/20538090/176956378-33328279-8f4d-4688-bc56-6f43741a652e.png)
Have you tried with these shortcut settings?

**Comment by Eikosa** [comment]
![image](https://user-images.githubusercontent.com/20538090/176956627-bf7cc1f0-dad0-47c8-ab7b-1c8f8d9e2b9f.png)
It works when the settings are as follows, but it is annoying that it saves the picture every time

**Comment by Jaex** [comment]
> Have you tried with these shortcut settings?

![](https://jaex.getsharex.com/2022/07/ShareX_3OOVAKyxnL.png)

Tried this, didn't had any problem.

**Comment by Jaex** [comment]
Finally managed to reproduce it by enabling this option:

![](https://jaex.getsharex.com/2022/07/ShareX_n8ekzLSGrB.png)

I tested this option countless times before but without hotkey.

**Comment by Eikosa** [comment]
I'm really glad!

**Comment by Jaex** [comment]
@Eikosa @Skizzles I fixed the issue now, can you test it by using dev build?

**Comment by Eikosa** [comment]
works flawlessly, thanks a lot!

**Comment by Skizzles** [comment]
> @Eikosa @Skizzles I fixed the issue now, can you test it by using dev build?

Works good, thank you! and sorry about not showing the options previously. I will show them all in the future :)

**Comment by mreduar** [comment]
I came to report this same error when "Process silently" is enabled. Also with the update it stopped working for me and I had to select the new microsoft function.

**Comment by Jaex** [comment]
> I was coming to report this same error when "Process silently" is enabled. Also with the update it stopped working for me and I had to select the new microsoft function.

Is it not fixed in dev build?
