### ISSUE TITLE
Corner Radius setting for Speech ballon in image editor

### ISSUE THREAD

**Issue by Leroy-X** [ShareX/ShareX#6323]
Text(Background) tools have corner radius option. but not in speech balloon.
corner radius looks more nice, so please add for speech balloon.

**Comment by Jaex** [comment]
I wanted to add it and tried a lot but couldn't make it work perfectly, because rounded corner requires anti aliasing which makes masking not work properly when drawing speech balloon tail. So I couldn't add it.

**Comment by Leroy-X** [comment]
Thank you very much for your reply, may I ask if it is possible to add the function of pinning in the future.
Float the screenshot to the top for easy switching of windows for reference.
Many screenshot software have this function, like [Snipaste](https://www.snipaste.com/), Thanks.
