### ISSUE TITLE
OCR issue has not fixed yet (Version 14.0.1)

### ISSUE THREAD

**Issue by erbanku** [ShareX/ShareX#6332]
**When I trying to OCR function:**

![image](https://user-images.githubusercontent.com/79493862/177912590-37528f60-c06f-4c82-b8d1-04ae2f9a33ec.png)

**Comment by Jaex** [comment]
Microsoft OCR only supports languages which is installed in your system, please check here:

![](https://jaex.getsharex.com/2022/07/ApplicationFrameHost_UyaVaHVNUE.png)

In my case only these two languages supported for OCR.

**Comment by erbanku** [comment]
OK, I found that.

But the OCR result has some issues. It shouldn't have a `blank` between Chinese characters, but the result has.

Before the ShereX 14 everything works correctly with OCR, did yours start to use other OCR engines?

![image](https://user-images.githubusercontent.com/79493862/177918969-8a2b7da9-a6c4-4268-8a5a-5ed45139b346.png)

**Comment by Jaex** [comment]
> It shouldn't have a blank between Chinese characters, but the result has.

I did not wrote the OCR engine myself.

> Before the ShereX 14 everything works correctly with OCR, did yours start to use other OCR engines?

Before we were uploading images to online OCR service to get results. Now we are using Microsoft's OCR engine locally.

**Comment by erbanku** [comment]
> > It shouldn't have a blank between Chinese characters, but the result has.
> 
> I did not wrote the OCR engine myself.
> 
> > Before the ShereX 14 everything works correctly with OCR, did yours start to use other OCR engines?
> 
> Before we were uploading images to online OCR service to get results. Now we are using Microsoft's OCR engine locally.

OK, but maybe you need to do it a little fix to it. Anyway, thanks!

**Comment by Jaex** [comment]
I can't know rules of every languages. Just removing spaces from OCR results won't work. It must be OCR engines job to handle these. So I'm not sure why it results like this.

**Comment by Jaex** [comment]
Duplicate of
