### ISSUE TITLE
Updated to ShareX 14.0.1 and got Out of memory.

### ISSUE THREAD

**Issue by F0xtastic** [ShareX/ShareX#6339]
That I can remember it was the first screenshot I took after the update, but I could be misremembering. 

Here's what it said in the crash window: https://paste.ee/p/uroZx

Here's the log, trimmed to shortly before the update: https://paste.ee/p/naFQ7

If you need the complete log please let me know and I'll see if I can find it again. I've used ShareX for a while now with no issues so I wouldn't be surprised if this was a one-off issue, but I figured it was worth reporting considering it happened so shortly after updating. Thanks for the support!

**Comment by Jaex** [comment]
Without exact reproduce steps I won't be able to find the cause of it.

**Comment by F0xtastic** [comment]
It happened when I took my first screenshot after the update and used blur on some sections, and then after a few screenshots without using blur, it happened again when I used blur. 

I just tried it a few more times, no issues. After something between 5-10 more screenshots, got an out of memory crash again.

It only seems to happen when I use blur several times on an image, but it doesn't happen EVERY time I use blur several times on an image. 

I can't find an exact pattern, but if I take enough screenshots using blur then it will happen often enough to say it's definitely an ongoing issue. 

Now when it happens the error window is frozen and I have to use task manager to close it.

**Comment by Jaex** [comment]
I'm still unable to reproduce it, can you try to record it?

**Comment by tmprnc** [comment]
I can report experiencing the same issue. Trying to take a screenshot (region), opening it in the image editor and applying either blur or pixellation crashes ShareX entirely, with an "out of memory" crash log. It happened three times in a row.
Restarting ShareX a fourth time, the error seemed to not happen again. I cannot say whether I reproduced the same exact steps with the same parameters.

Crashlog is as is:

2022-07-12 16:31:32.642 - Unhandled exception:
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(RectangleF rect, PixelFormat format)
   at ShareX.HelpersLib.ImageHelpers.CropBitmap(Bitmap bmp, RectangleF rect)
   at ShareX.ScreenCaptureLib.BaseEffectShape.OnDrawFinal(Graphics g, Bitmap bmp)
   at ShareX.ScreenCaptureLib.PixelateEffectShape.OnDrawFinal(Graphics g, Bitmap bmp)
   at ShareX.ScreenCaptureLib.ShapeManager.RenderOutputImage(Bitmap bmp, PointF offset)
   at ShareX.ScreenCaptureLib.RegionCaptureForm.GetResultImage()
   at ShareX.TaskHelpers.AnnotateImage(Bitmap bmp, String filePath, TaskSettings taskSettings, Boolean taskMode)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Jaex** [comment]
I took 10x region capture and spammed blur/pixelate on them:

![](https://jaex.getsharex.com/2022/07/ShareX_BzGix66MrY.png)

Still unable to reproduce the issue. You guys must be doing something different than I and I don't know what.

**Comment by botatooo** [comment]
> It happened when I took my first screenshot after the update and used blur on some sections, and then after a few screenshots without using blur, it happened again when I used blur.
> 
> I just tried it a few more times, no issues. After something between 5-10 more screenshots, got an out of memory crash again.
> 
> It only seems to happen when I use blur several times on an image, but it doesn't happen EVERY time I use blur several times on an image.
> 
> I can't find an exact pattern, but if I take enough screenshots using blur then it will happen often enough to say it's definitely an ongoing issue.
> 
> Now when it happens the error window is frozen and I have to use task manager to close it.

Do you have a specific configuration where you're always able to reproduce the issue?

**Comment by DonFano** [comment]
I'm glad I could finally find this post because I was about to report the same issue. The issue can be reproduced when the selection with any of the annotation tools (e.g. blur, rectangle, etc.) goes beyond the actual image area.

**Comment by Jaex** [comment]
Can you test the fix using [dev build](https://getsharex.com/docs/dev-builds) please.

**Comment by DonFano** [comment]
> Can you test the fix using [dev build](https://getsharex.com/docs/dev-builds) please.

The fix works. Can no longer reproduce

**Comment by F0xtastic** [comment]
Apologies for dropping out of this thread (missed my email notifs) and thanks to those who took over and got it resolved. Mine is now working as well!
