### ISSUE TITLE
Missing language options in OCR (ver.14.0.1)

### ISSUE THREAD

**Issue by rockmor** [ShareX/ShareX#6340]
As on the screenshots.
First is from 13,7.0, where I've been using Japanese and Chinese OCR. After updating to the latest 14.0.1 only two options has left (American English and Russian).

![sharex1](https://user-images.githubusercontent.com/108937449/177995451-7c589ccf-34e2-407a-b002-2061bbfe4b1b.png)
![sharex2](https://user-images.githubusercontent.com/108937449/177995457-8a47d9ea-7736-4641-a0da-4f5f32063fa5.png)

**Comment by krausekai** [comment]
The latest version relies on Windows' language support and OCR recognition now. It seems that the language needs to be installed in Windows' language list for it to be an option in ShareX now.

**Comment by rockmor** [comment]
@krausekai 
Thank you, installing new languages has solved the problem for me.

**Comment by Jaex** [comment]
I'm adding step by step instructions to add new language in here, in case people find this issue later:

1.

![](https://jaex.getsharex.com/2022/07/ApplicationFrameHost_mHSSnfNVgH.png)

2.

![](https://jaex.getsharex.com/2022/07/ApplicationFrameHost_MHJbVjMDHz.png)

3.

![](https://jaex.getsharex.com/2022/07/ApplicationFrameHost_PqCvFaApZE.png)

Uncheck all options in last dialog, none of them needed for OCR support.

**Comment by Jaex** [comment]
Made this web page now: https://getsharex.com/docs/ocr

**Comment by Jaex** [comment]
Added help button here:

![](https://jaex.getsharex.com/2022/07/ShareX_TrX2m5rDVx.png)

Which gonna open this page: https://getsharex.com/docs/ocr

**Comment by Iris-Heart** [comment]
If you don't mind me asking, why was this changed from the previous version?

**Comment by KevinFC** [comment]
> If you don't mind me asking, why was this changed from the previous version?

For offline support, since the original OCR is an online service.

Also, thank you @Jaex, very fast fix!

**Comment by Jaex** [comment]
> If you don't mind me asking, why was this changed from the previous version?

Because offline OCR is faster and more secure because you don't have to upload images to remote servers.

**Comment by Iris-Heart** [comment]
> 

Ahh I didn't realize this was for offline OCR! I appreciate the change in that case.
