### ISSUE TITLE
Arabic reversed in OCR

### ISSUE THREAD

**Issue by Selmez** [ShareX/ShareX#6342]
after OCR scanning, _Arabic_ shows in _reverse_ order

the correct one, that shows in top of this image..

![Arabic OCR](https://user-images.githubusercontent.com/3610064/178059855-4b666936-f2af-43c3-abca-9aeb9297ad14.png)

**Comment by Jaex** [comment]
Can you give some more example arabic, like web site etc. So I can test my fix with more examples.

**Comment by Selmez** [comment]
[Wikipedia Arabic](https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9)

**Comment by Jaex** [comment]
Can you test it using [dev build](https://getsharex.com/docs/dev-builds)?

**Comment by Selmez** [comment]
Thank you, it's working fine now 👍
