### ISSUE TITLE
Japanese OCR adding Spaces between every character

### ISSUE THREAD

**Issue by dkaknbk** [ShareX/ShareX#6343]
Hello, I noticed an issue with the new iteration of the OCR function in relation to Japanese ever since I updated to  14.0.1

Example output before the update:
ああ、望むとも。 そして、この願いが再び歴史に曲げられぬよう、 すべての証人の心と石に刻んで、和平の誓いと成さん

Example output after the update:
あ あ 、 望 む と も 。そ し て 、 こ の 願 い が 再 び 歴 史 に 曲 げ ら れ ぬ よ う 、す べ て の 証 人 の 心 と 石 に 刻 ん で 、 和 平 の 誓 い と 成 さ ん

Unfortunately, this makes the text very unnatural and harder to read as it makes it more difficult to judge where new words begin and it also breaks compatibility with popup dictionary tools such as Yomichan as the spaces make it impossible to parse the words because the tools opts to search for the individual characters instead of the compound words instead.

**Comment by Jaex** [comment]
Duplicate of #6322
