### ISSUE TITLE
Update to 14.0.1 portable.OCR cannot select which language donot install packs on windows 11

### ISSUE THREAD

**Issue by jrm200306** [ShareX/ShareX#6346]
It works at 13.7.0,at 14.0.1 only support language packs installed

**Comment by Jaex** [comment]
ShareX 13.7.0 was using "online" OCR, which means OCR was happening at remote servers.
With ShareX 14.0.1 OCR happens in your own computer, so languages must be installed in your system for Microsoft OCR to work.
