### ISSUE TITLE
[BUG] 14.0.1 fails to save images to the directory with an UnauthorizedAccessException

### ISSUE THREAD

**Issue by sommmen** [ShareX/ShareX#6348]
Hiya,

I recently updated from 13.7.0 to 14.0.1 and it seems that it broke something:

![afbeelding](https://user-images.githubusercontent.com/8641495/178109741-2255107d-38bf-4492-bcc8-690435d35539.png)

```
2022-07-09 16:11:13.587 - Image copied to clipboard.
2022-07-09 16:11:13.592 - Exception:
System.UnauthorizedAccessException: Toegang tot het pad C:\Users\[REDACTED]\Documents\ShareX\Screenshots\2022-07\explorer_2022-07-09_16-11-13.png is geweigerd.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bij ShareX.HelpersLib.StreamExtensions.WriteToFile(Stream stream, String filePath)
   bij ShareX.ImageData.Write(String filePath)
```

I've assigned 'everyone' full access:

![afbeelding](https://user-images.githubusercontent.com/8641495/178109727-3a324e14-4e50-415c-a216-19ba28f01ce4.png)

My virus scanner is Avast and i tried to disable that but that did not work.

Something that does strike me as odd is that the readonly flag gets applied (seemingly every time i take a screenshot):
![afbeelding](https://user-images.githubusercontent.com/8641495/178109849-af6ec147-d31f-4b6c-99d1-9afec59aef78.png)

**Comment by sommmen** [comment]
Okay odd - but i tested creating a recording (FFMPEG). 

Taking a recording works and the file appears in the right folder - no errors.

The first time i take a recording nothing changes.

The second time and now i no longer get the error anymore when taking a screenshot.

Then if i _delete_ the screenshot folder (Screenshots/2022-07) the error reoccurs!
If i then take 2 more recordings the error goes away again so this seems reproducible.

**Comment by axelitus** [comment]
I am having the same issue. When taking a screenshot it does not get saved properly stating that the folder does not have permissions.

**Comment by kolinekp** [comment]
I am also having this problem. Recording the screen is working fine, but screenshots end with the same error as @sommmen reported.

I tried to go back to 13.7.0 without uninstalling the newest version first, which did not resolve the issue.
After uninstalling first and installing 13.7.0 again, the problem is solved, but the issue occurs again when updating to the newest release. This time, I was able to install 13.7.0 without the need of uninstalling the newer version first.

**Comment by kolinekp** [comment]
I suggest renaming the issue to "fails to save images" since it is not really being downloaded.

**Comment by axelitus** [comment]
I agree and I can confirm this issue was introduced with the update to version 14.0.1

**Comment by axelitus** [comment]
This is odd... I went on a changelog hunt: [https://getsharex.com/changelog/](https://getsharex.com/changelog/) and noticed this entry: "Improved save image error message to suggest user to check anti virus [controlled folder access](https://support.microsoft.com/en-us/windows/allow-an-app-to-access-controlled-folders-b5b6627a-b008-2ca2-7931-7e51e912b034) feature". I navigated to the Windows 11 Virus & Threat protection page and as I am using avast as a third-party antivirus, everything was disabled.

I went to look into Avast's history to check if something was being blocked for SahreX and I didn't find anything. I then took a test screenshot again and.... it is working now! 😐 so odd! But I am guessing it is indeed something introduced in newer versions of ShareX that relies on setting at the OS level to protect special folders. It wouldn't hurt to look into them and see if you can manage to get rid of the issue.

Test screenshot:
![2022-07-11_09h19m21s_msedge_bEsGBAhUZz](https://user-images.githubusercontent.com/732441/178285991-bb0c628a-d0b8-42f6-bb2b-3f2f077fb491.png)

**Comment by kolinekp** [comment]
Unfortunately, the issue persists with the update to 14.1.0

**Comment by sommmen** [comment]
@Jaex Hello mate, could you take a look at this bug report?

**Comment by kolinekp** [comment]
The issue is still present in version 15.0

**Comment by sommmen** [comment]
Has anyone seen this issue in the new version?

**Comment by kolinekp** [comment]
I have changed my computer and the issue is not present here. Still on the same version.
