### ISSUE TITLE
OCR use in v.14 for Win7

### ISSUE THREAD

**Issue by harryray33** [ShareX/ShareX#6349]
I'm using Win7...Is it possible to still use OCR in v.14.0.1 or will I have to use v.13.7?

Thanks.

**Comment by Jaex** [comment]
We are using Microsoft's OCR engine now which is only available in Windows 10 or newer versions.

**Comment by CatPlanet** [comment]
Oh, I hate this. I thought only "online OCR" will be Windows 10 feature, not everything. Time to permanent downgrade, it seems.

**Comment by harryray33** [comment]
Same here. Ideally, as I can't have offline OCR for Win7, it would have been nice to be able to have the online OCR option with the new version.

**Comment by harryray33** [comment]
Is this still an issue with the latest version, is Sharex still using the MS OCR?
Thanks
