### ISSUE TITLE
Snip without a tray icon

### ISSUE THREAD

**Issue by Er1cMa** [ShareX/ShareX#6354]
Hi, developer! I suggest you try to create a new feature which enables me to snip using Func key, but without having an icon in the tray.

![image](https://user-images.githubusercontent.com/102273670/178173141-1e9840bb-cfa5-4e65-82da-87f80341f7ae.png)

just like IDM which can hide its icon

tks

**Comment by Jaex** [comment]
What is point of hiding tray icon?

**Comment by Er1cMa** [comment]
> What is point of hiding tray icon?

Just make the tray cleaner... 
actually, when i see there are more than 4 icons in the tray, i feel a sense of pressure 
so maybe it's me that ought to change
