### ISSUE TITLE
[Feature Request] OCR store the text into single .txt file per folder and ability to bulk OCR image folder

### ISSUE THREAD

**Issue by astandarduser** [ShareX/ShareX#6360]
Would be much less clutter if the OCR function stored the text into single .txt (or similar) file per folder rather than a .txt per image. The ability to bulk OCR a folder of images. Particularly the screenshots folder would be super useful as well

**Comment by gitgrub** [comment]
The one file per image approach sounds more clear to me, to be honest.
But you could unite the text files like that: `copy /b *.txt all.txt`
