### ISSUE TITLE
Update domain oauth

### ISSUE THREAD

**Issue by lollita** [ShareX/ShareX#6365]
https://api.imgur.com
instead of
https://web.imgur.com

https://twitter.com/oauth
instead of
https://web.twitter.com/oauth

**Comment by Jaex** [comment]
What?

**Comment by lollita** [comment]
https://web.imgur.com/oauth2/authorize?client_id=XXXXXXXXXXXXXXX&response_type=pin
https://web.twitter.com/oauth/authorize?oauth_token=XXXXXXXXXXXXXXXXXXXX
return error

**Comment by lollita** [comment]
When I use "Connect..." from "Destination settings..." for imgur and twitter I get a error page and I have to fix the url domain.

**Comment by lollita** [comment]
Again PhotoBucket no open authorize page.
