### ISSUE TITLE
Mouse Problem when screen recording

### ISSUE THREAD

**Issue by jtjackgal220** [ShareX/ShareX#637]
When I screen record, the mouse is slightly out of position in the video with where it is actually supposed to be on the screen.  For example if I hover over something while screen recording, When playing back the video, the mouse is about one inch left of  where it actually was when the recording was done.  Does anyone know how to correct this issue?

Thank you!
Jeff

**Comment by Jaex** [comment]
Which video source you using in FFmpeg? Did you tried other one?

**Comment by jtjackgal220** [comment]
FFmpeg is what is selected.  The other one does not work

**Comment by Jaex** [comment]
I meant video source in ffmpeg settings.

**Comment by jtjackgal220** [comment]
It is set to screen-capture-recorder

**Comment by jtjackgal220** [comment]
I tried GDI grab but always get a an error.  There is not other video source other than that to choose from.

**Comment by Jaex** [comment]
I guess your monitor dpi is different therefore your cursor position is wrong because it is bigger.

**Comment by jtjackgal220** [comment]
Ok.  That makes sense.  I will see if I can modify the settings.  Thanks.

**Comment by jtjackgal220** [comment]
Thank you for the prompt help!

**Comment by jtjackgal220** [comment]
By the way, if you are the developer of ShareX, I thank you for the great tool.

**Comment by jtjackgal220** [comment]
Just changed the screen resolution.  This fixed the problem.  Thanks very much!

**Comment by Jaex** [comment]
By the way ShareX using open source https://github.com/rdp/screen-capture-recorder-to-video-windows-free for screen recording in FFmpeg so you can report your high DPI cursor problem there if you want.

**Comment by Jaex** [comment]
https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/56

**Comment by Jaex** [comment]
#1329 In latest ffmpeg release gdigrab video source cursor position fixed, can you test it?

**Comment by mekwall** [comment]
@Jaex I just tried with latest ffmpeg. Still doesn't work :(

**Comment by HamRusTal** [comment]
I experimented with `gdigrab` in recent versions of FFmpeg and found that mouse pointer is offset when capturing a window (e.g. “`ffmpeg -f gdigrab -i title=Calculator …`”) and is OK when capturing the desktop (e.g. “`ffmpeg -f gdigrab -offset_x 10 -offset_y 20 -video_size vga -i desktop …`”).

**Comment by yashpalgoyal1304** [comment]
i am facing the similar problem while using screen-capture-recorder and it got fixed when i switched to GDI-grab. i didnt touch anything else. only switching to GDI grab fixed it.

**Comment by yashpalgoyal1304** [comment]
using GDI-grab: 
![drEclT98tw](https://user-images.githubusercontent.com/19423063/95910571-e82a5300-0dbd-11eb-8113-3593a1fbfd40.gif)

using screen-capture-recorder:
![4rWeevNnWn](https://user-images.githubusercontent.com/19423063/95913264-971c5e00-0dc1-11eb-962a-e2fb62b1e604.gif)

**Comment by locvnhub** [comment]
> using GDI-grab: ![drEclT98tw](https://user-images.githubusercontent.com/19423063/95910571-e82a5300-0dbd-11eb-8113-3593a1fbfd40.gif)
> 
> using screen-capture-recorder: ![4rWeevNnWn](https://user-images.githubusercontent.com/19423063/95913264-971c5e00-0dc1-11eb-962a-e2fb62b1e604.gif)

using GDI-grab:
=> but mouse size point not change
