### ISSUE TITLE
Regression: Image Editor should not prompt on close if image has been copied to the clipboard

### ISSUE THREAD

**Issue by deadlydog** [ShareX/ShareX#6377]
Something changed in ShareX recently (around v14) with the Image Editor. If an image is edited in the Image Editor and you have not saved the image, when you close the Image Editor you will be prompted, asking if you're sure you want to close the editor since there are unsaved changes. In previous versions, this prompt would not come up if you had copied the image to your clipboard. Now in v14.0.1, you will be prompted every time unless you've saved the image as a file to disk.

More often than not, I simply copy the image to my clipboard so I can paste it somewhere else; I don't actually save the file to disk. 

Having to always click `Yes` to the prompt is very annoying, and I cannot find any setting relating to disabling the prompt.

In the screenshot below, you can see that I've copied the image (with changes) to the clipboard, as the `Image copied` text is displayed. When closing the editor though, I still get prompted asking if I'm sure I want to close it.

![image](https://user-images.githubusercontent.com/1187140/179158995-c2628cc3-f668-4ecb-93b2-7fda3b468b6d.png)

Please either suppress the prompt if the image has been copied to the clipboard (restoring the previous functionality), or add a setting to the application that allows users to configure it to whichever they prefer.

Thanks for this wonderful application!

**Comment by Jaex** [comment]
Fixed already in https://github.com/ShareX/ShareX/commit/6cc4f116d6b207ed25496c63693e768e08345608
