### ISSUE TITLE
Ruler 5px limit

### ISSUE THREAD

**Issue by kubiqsk** [ShareX/ShareX#6379]
Hello,
thank you for a great software!

I'm wondering if it's somehow possible to measure really small distances with ruler.

Right now I can not measure anything below 5px, but I would need to see also 4, 3, 2 or 1px

I can not find anything in settings :/

**Comment by Jaex** [comment]
Reason for 5px minimum size limit is related to screen capture and hover click support, which also applies to ruler. Because people move cursor slightly while clicking, I needed to add minimum limit so people could hover click instead of creating 3px size region.
