### ISSUE TITLE
Editing the image from the URL

### ISSUE THREAD

**Issue by ymkocv** [ShareX/ShareX#638]
The error message appears while we try to save changes in the file from the Internet. May it is better to write something like: It is not possible to save changes in the file from Internet? The perfect way is to make possibility to save file on the local PC with the changes. Here is the description:

Steps:
1. Open the editor in ShareX:

![image](https://cloud.githubusercontent.com/assets/12046086/7247454/5cfcaa48-e812-11e4-9cd5-e21a5837c64d.png)

2. Open the file using it's URL:

![image](https://cloud.githubusercontent.com/assets/12046086/7247460/6f088d88-e812-11e4-8fe6-ce7a5f719c6a.png)

3. Edit the file and try to save it. There will the error appear:

![image](https://cloud.githubusercontent.com/assets/12046086/7247588/c93aff60-e813-11e4-8bac-757445c1ed1b.png)

P.S. Sorry if I am reporting something wrong, I'm the first time here.

**Comment by Jaex** [comment]
Even Paint.NET can't manage to save it. You are not supposed to use url in file dialog. Because where it saves not allows saves to there.

**Comment by ymkocv** [comment]
Jarex, I agree, but error messages can be more clear for the user. And it will be so nice to have possibility to save the edited pi on the PC.

**Comment by ymkocv** [comment]
By the way, Paint proposes to save the edited pic from the internet on the PC:
![image](https://cloud.githubusercontent.com/assets/12046086/7268823/fcec0d28-e8d5-11e4-9eb6-e5227962389e.png)

**Comment by McoreD** [comment]
Sorry - at most cases, we rely on the exception Microsoft identifies.
Otherwise, we would end up handling thousands of different exceptions to
make better sense.

**Comment by ymkocv** [comment]
Np, it's up to you ) but this is really not comfortable
