### ISSUE TITLE
ShareX always create folder in Documents

### ISSUE THREAD

**Issue by steam3d** [ShareX/ShareX#6383]
I specified custom settings folder in ShareX settings then i deleted the ShareX folder in Documents. After restart ShareX, it reset the settings and create folder in Documents. 

It is extremely annoying when you use the OneDrive.  ShareX generate lot of trash and OneDrive infinity syncs files. 

Is there way to specify the default app folder without using Documents?

**Comment by Jaex** [comment]
Yes: https://getsharex.com/docs/command-line-arguments#personal-path
