### ISSUE TITLE
Language for the OCR hotkey

### ISSUE THREAD

**Issue by l-Nuril-l** [ShareX/ShareX#6384]
![image](https://user-images.githubusercontent.com/49325887/179375696-aada6c4c-6ca9-4d50-a649-fb80350b4530.png)
When I create a hotkey for OCR, it takes the current ORC settings, which then shows up as uneditable.
T - ![image](https://user-images.githubusercontent.com/49325887/179375686-2b5a90b1-b7e2-4d75-ba06-89125a26e3f2.png)
Y - ![image](https://user-images.githubusercontent.com/49325887/179375690-e5d79d14-6456-43f8-b817-d0503d4a43fb.png)

I created 2 hotkeys with different languages, but when I use them, the default language from the general OCR settings is used.
![image](https://user-images.githubusercontent.com/49325887/179375684-c61c03bd-d9b4-4ff3-8b15-e18949799109.png)
Make it possible to select a default language for each hotkey or let it use the language that was used when the hotkey was created.

**Comment by Jaex** [comment]
Check this:

![](https://jaex.getsharex.com/2022/07/ShareX_rDx4NyoFf5.png)
