### ISSUE TITLE
Cannot get jpeg in "capture region" anymore - defaults to png

### ISSUE THREAD

**Issue by roughnecks** [ShareX/ShareX#6386]
These are my settings:
https://i.imgur.com/l8R7RDZ.jpeg

![image](https://user-images.githubusercontent.com/1666536/179405552-70d86735-e383-483c-a1fd-d58820ba164b.png)

The first image I used upload to host, the second I just hit "continue" with "copy image to clipboard" from region capture and it's always png, no matter what settings I choose.

What am I doing wrong?

**Comment by Jaex** [comment]
Use "Copy file to clipboard".
Also "Copy image to clipboard" copies bitmap, not PNG.

**Comment by roughnecks** [comment]
https://i.imgur.com/NYGmaCf.jpeg

With these settings nothing gets copied to clipboard, either if I "continue" or "copy"

**Comment by Jaex** [comment]
You can't copy file to clipboard without image saved to file first.

**Comment by roughnecks** [comment]
> You can't copy file to clipboard without image saved to file first.

Alright I give up, will keep the bitmap (which gets pasted as png).
Thanks

**Comment by Jaex** [comment]
> which gets pasted as png

Application you are using automatically creating png. So it is not copied or pasted as png.

**Comment by roughnecks** [comment]
which application?

I'm using CLCL as a clipboard tool, which says they're bitmaps: https://i.imgur.com/s5GzWiR.jpeg
Then I CTRL-V into any applications where I want to share that and it's pasted as png.

**Comment by Jaex** [comment]
> which application?

Which ever application you are pasting to. If you paste to chat app then that app automatically creates png because bitmap is huge.

**Comment by roughnecks** [comment]
> > which application?
> 
> Which ever application you are pasting to. If you paste to chat app then that app automatically creates png because bitmap is huge.

Alright then, as I said before, I will keep it like this, because it's the most convenient way for me to share images.
