### ISSUE TITLE
Select Image in Task List

### ISSUE THREAD

**Issue by sparevermicelli** [ShareX/ShareX#6392]
Hello,

I usually use Task List in Thumbnail View to annotate screenshots.
Currently when one clicks on the image, it opens in fullscreen preview (which is useless as there are no actions possible), then ESC (to close the preview). Only then is the image "selected" and one can use shortcuts to further process the image (CRTL+E for instance to annotate). 

Would it be able to have mouse click only to select image? Possibly for it to be configurable what happens on click (open in Editor for instance).

Sample:
https://i.imgur.com/W7YEPjv.gif

**Comment by Jaex** [comment]
You can select with ctrl + click or you can configure it like this:

![](https://jaex.getsharex.com/2022/07/ShareX_v62vj6DE8V.png)
