### ISSUE TITLE
[Feature Request] Changing order/sequence of after capture tasks

### ISSUE THREAD

**Issue by magetower-rgb** [ShareX/ShareX#6394]
I normally want to use the quick task menu to decide if i want to save/upload or edit a picture.

Since the quick task menu is the first task in the list of "After capture tasks", stuff like image effects after it gets ignored, when i decide to save the image or upload it and not press on continue.

Since i have a display with a high resolution, i want to scale every image down to 50% (What can be done with image effects), but in this case the image effect task have to run before the quick task menu.

So i think it would be nice if we could change the order of the tasks or at least of the quick task menu, because in my case i would have to go in the editor each time what is time consuming.

**Comment by magetower-rgb** [comment]
Hmm couldnt find another request?
Can you link me the request please?

**Comment by ZeroK59** [comment]
Couldn't find the same request as well...
Should be a usefull functionnality.

**Comment by Ejsstiil** [comment]
Can we please reopen this idea? Would super helpful to have for example: Copy to the clipboard before Editor. To get clean copy to Clipboard and then eventually ESC the editor, when no edits needed. Currently when you ESC the editor, you end up with nothing in the Clipboard.

![image](https://github.com/ShareX/ShareX/assets/36369441/26da70a4-d679-416a-944e-ab41502fb5a8)

**Comment by Ejsstiil** [comment]
For anyone needed this I found this:
![image](https://github.com/ShareX/ShareX/assets/36369441/a3acee53-b3ad-4a3e-986d-50a69f87b039)
This is even cooler as it not only autocopy on take, but after any addition you do.
