### ISSUE TITLE
Could not create SSL/TLS Channel

### ISSUE THREAD

**Issue by sudaox2001** [ShareX/ShareX#6400]
Hello, I am trying to upload screenshots to my ShareX and I am getting this error. It is not an issue with hosting as I can access it just fine in my browser.
![image](https://user-images.githubusercontent.com/107582771/180591151-31df41da-31cf-4c70-8162-8833039fe62d.png)
OS: Windows 7 SP1
ShareX Version: 14.0.1

**Comment by Lightningblade** [comment]
#5635
