### ISSUE TITLE
Magnifier does not show pixel grids properly

### ISSUE THREAD

**Issue by lakospeter** [ShareX/ShareX#6405]
Bug: Horizontal pixel grids goes through the pixels in the magnifier.
Please, see the attachments where I show you the Chrome logo in ShareX's magnifier compare to Figma zoom.

| ShareX's magnifier with wrong grids   | Figma zoom with correct grids |
|----------|:-------------:|
| ![Wrong grids in ShareX's magnifier](https://user-images.githubusercontent.com/6765819/180662406-5ec4d053-366d-49ec-b04c-3ef4caa0efba.png) |  ![Correct grid from Figma](https://user-images.githubusercontent.com/6765819/180662405-a7d4973a-d4ad-46da-aef2-58f5af3a7917.png) |

**Share X version information**
14.1 Portable

**OS version information:**
Edition	Windows 10 Pro
Version	21H2
Installed on	‎2022. ‎07. ‎15.
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by Jaex** [comment]
I'm unable to reproduce it:

![](https://jaex.getsharex.com/2022/07/ShareX_LVVNc7biY6.png)

**Comment by lakospeter** [comment]
> I'm unable to reproduce it:
> 
> ![](https://camo.githubusercontent.com/13b0b570d9ced806db4c09ce5b25037211cead592dcf003af9eb9b2ff7e0b57c/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032322f30372f5368617265585f4c56564e6337626959362e706e67)

**Comment by lakospeter** [comment]
Hi Jaex,

Interesting, because Chrome icon on my taskbar is good too but please give it a another shot among Chrome's tabs:
![20220725_082402](https://user-images.githubusercontent.com/6765819/180711707-afdfedce-32e4-44c0-8495-033267c3a458.png)
![20220725_082427](https://user-images.githubusercontent.com/6765819/180711711-4c396f65-14e6-45e8-a607-4b7f10b0744e.png)

**Comment by L1Q** [comment]
Can reproduce when why system-wide scaling is set to 125%
![image](https://user-images.githubusercontent.com/6942070/180782939-266cdc22-fb04-4367-bbd3-f643acb294ee.png)

**Comment by lakospeter** [comment]
**L1Q**: Yes, it happens in the **Image editor**, and not before taking the screenshots. Thanks for this additional information! I use my screens without scaling, so I use **100% (Recommended)** option at my Windows' scale settings.

**Comment by Jaex** [comment]
Looks like this problem is related to zoom support in image editor. It happens when I zoom.
