### ISSUE TITLE
ShareX dont work with McAfee DLP enabled

### ISSUE THREAD

**Issue by snok87** [ShareX/ShareX#641]
I think the issue is caused by the method of screen capturing, maybe other applications use other methods to capture the screen.

The first symptom is, it can't register hotkeys.
 
![sharex dlp](https://cloud.githubusercontent.com/assets/12066360/7272970/739d6ade-e8ef-11e4-9366-ae77efcaaecf.png)
![sharex dlp2](https://cloud.githubusercontent.com/assets/12066360/7272969/739ca9f0-e8ef-11e4-8bc2-3b679b733c26.png)

DLP seems tu support SnagiIt, Corel PaintSho Pro, OneNote.

**Comment by Jaex** [comment]
I don't know what is DLP but if some software blocking ShareX then there is nothing we can do about it obviously.

**Comment by snok87** [comment]
DLP = Data Loss Prevention, it prevents that you can send confidential info about your business.
It have a policy to block screenshots if you have a confidential document opened, but not works well with ShareX. Maybe ShareX use non standard methods to capute the screen. 
I just want to know the method that ShareX use to capture the screen and then open an issue with McAfee to solve the problem.

**Comment by Jaex** [comment]
You showed hotkeys not working what is it to do with screen capture?

**Comment by snok87** [comment]
Maybe DLP is blocking changing hotkeys that contains "PrntScreen key". 
The problem is that DLP detects when you try to capture the screen and shows you the next:
![image](https://cloud.githubusercontent.com/assets/12066360/7277000/b1af89ce-e90d-11e4-8049-0143ea0f57e7.png)

But with ShareX you can do ScreenShots with the manual option:

![image](https://cloud.githubusercontent.com/assets/12066360/7277025/cb5d26a6-e90d-11e4-873f-8a7c72f02297.png)

And DLP dont detect the SystemEvent/SoftwareKeystroke/others that use ShareX, how it captures the screen?

**Comment by Jaex** [comment]
If some software in your PC already registered that hotkey you can't register it again.

**Comment by snok87** [comment]
When you clic on Capture -> Screen, what action run ShareX? What do exactly?

![image](https://cloud.githubusercontent.com/assets/12066360/7277224/1a4ac3ee-e90f-11e4-911a-dcbd6367dfa9.png)

**Comment by Jaex** [comment]
What is it to do with hotkeys...

**Comment by snok87** [comment]
I just want to know what happens when you click (with the mouse) on Capture -> Screen
What generates ShareX on the system? Whats the dialogue between ShareX and System?

**Comment by Jaex** [comment]
All screen capture softwares (nearly) using same method to capture.

**Comment by snok87** [comment]
This "nearly" is the matter I have with ShareX, and i need to know which is the method to open a case with McAfee.

**Comment by snok87** [comment]
Its maybe using the class bitmap from System.Drawing.Imaging?
https://msdn.microsoft.com/en-us/library/system.drawing.bitmap(v=vs.110).aspx

**Comment by Jaex** [comment]
Your hotkey problem nothing to do with capture.

**Comment by snok87** [comment]
Can you forget completely the hotkeys and answer my questions? As I said in the first post, "The first symptom is, it can't register hotkeys."

Its maybe using the class bitmap from System.Drawing.Imaging?
https://msdn.microsoft.com/en-us/library/system.drawing.bitmap(v=vs.110).aspx

**Comment by McoreD** [comment]
Hotkey -> Capture method
Menu item -> Capture method

As @Jaex said the same Capture method is accessed eithe via Hotkey or Menu
Item. Not registering hotkeys has got nothing to do with Bitmap class.

**Comment by snok87** [comment]
And the capture method is?

**Comment by McoreD** [comment]
https://github.com/ShareX/ShareX/blob/master/ShareX.ScreenCaptureLib/Screenshot.cs
or
https://github.com/ShareX/ShareX/blob/master/ShareX.ScreenCaptureLib/Screenshot_Transparent.cs
