### ISSUE TITLE
Task Settings => Capture => capture window with transparency not save

### ISSUE THREAD

**Issue by HalidCisse** [ShareX/ShareX#642]
After restart the setting come back to default

**Comment by Jaex** [comment]
When you close task settings window it saving settings so I'm not sure why it not saving for you.

**Comment by HalidCisse** [comment]
Other settings are saved but "capture window with transparency" is not !

**Comment by Jaex** [comment]
It saves for me.

**Comment by HalidCisse** [comment]
ill app from taks manager and try

**Comment by Jaex** [comment]
Even if i kill still it will save because it saves when task settings window close not when ShareX close.
