### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by maximcepraga39** [ShareX/ShareX#6422]
Every time I take a screenshot, the CPU usage goes up to ~30%. I'm using version 14.1

I love ShareX, but every time I take a screenshot, the CPU is loaded at 30%, and it also heats up, it's kind of inconvenient. It's better to take screenshots via Win + Shift + S, in this case the processor is not loaded at all.

![image](https://user-images.githubusercontent.com/43599018/182382271-cedb0429-a5ee-4c48-ad6e-15686015ba39.png)

**Comment by L1Q** [comment]
Make sure to limit fps in your region capture, this should help a lot with the heating up problem.

![image](https://user-images.githubusercontent.com/6942070/182383525-51aa2f16-6211-46fb-b866-bca9580d7b4b.png)

**Comment by maximcepraga39** [comment]
thank you. It helped, I set FPS limit to 30 and now it is using about 10% of the CPU.

![image](https://user-images.githubusercontent.com/43599018/182384763-e7c5e14b-165d-458d-9d0d-2f8c3b93f8b0.png)
