### ISSUE TITLE
[Feature Request] Allow "save raw screenshot" before opening in image editor

### ISSUE THREAD

**Issue by clarede** [ShareX/ShareX#6424]
When taking a screenshot (or region capture) and selecting both "open in image editor" and "save to file" as the after capture tasks - the screenshot will always _open in the editor first_ and not save the screenshot

can a way to make the screen capture save to file before (or at the same time) as it is opened in editor?  
maybe something called "Save raw capture" that appears higher in the drop down list
OR at least give an option make these 2 tasks happen in parallel

Obviously I see why it works this way (an editor implies that drawing will be done on the image) 
however in my case, I probably have a split percentage of edit/upload/copy to clipboard which I prefer to do via the editor  

most of the time I then press the [Close] button on the editor, and the screenshot is never saved.

![image](https://user-images.githubusercontent.com/110512721/182526339-311e068d-30c4-48b2-9546-e96653d48939.png)

Im guessing because "save image to file" is lower on the list, it gets processed last   
it would be nice to be able to give "save image" a higher priority
The image editor already has built in functions to handle saving an image

**Comment by L1Q** [comment]
I can suggest a workaround.
Configure your After capture tasks like this:
- do not "Open in image editor"
- "Save image to file"
- "Perform actions"

![image](https://user-images.githubusercontent.com/6942070/182527408-87c6fd4b-0946-471d-8c81-b6a0d9bdbb22.png)

Go to Task settings - Actions and add an action like this:
- Name: anything you like, I typed ``ShareX Image editor``
- File path: this has to be full path to ShareX.exe, in my case ``C:\Program Files\ShareX\ShareX.exe``
- Arguments: for the desired effect you want to [run the Image editor](https://getsharex.com/docs/command-line-arguments#-imageeditor-image-file-path) using ``-imageeditor %input``

![image](https://user-images.githubusercontent.com/6942070/182527663-751fae24-f57d-44d1-b928-f7e385bc3aec.png)

You will have your image saved first, and then ShareX will start the Image editor with that screenshot opened.

Note that by default ShareX comes with an example Action that starts Microsoft Paint, you can even use that if you want.

**Comment by clarede** [comment]
Thank you - this workaround is adequate for what I wanted to do

The images were helpful aswell!

**Comment by abdumka** [comment]
> I can suggest a workaround. Configure your After capture tasks like this:
> 
> * do not "Open in image editor"
> * "Save image to file"
> * "Perform actions"
> 
> ![image](https://user-images.githubusercontent.com/6942070/182527408-87c6fd4b-0946-471d-8c81-b6a0d9bdbb22.png)
> 
> Go to Task settings - Actions and add an action like this:
> 
> * Name: anything you like, I typed `ShareX Image editor`
> * File path: this has to be full path to ShareX.exe, in my case `C:\Program Files\ShareX\ShareX.exe`
> * Arguments: for the desired effect you want to [run the Image editor](https://getsharex.com/docs/command-line-arguments#-imageeditor-image-file-path) using `-imageeditor %input`
> 
> ![image](https://user-images.githubusercontent.com/6942070/182527663-751fae24-f57d-44d1-b928-f7e385bc3aec.png)
> 
> You will have your image saved first, and then ShareX will start the Image editor with that screenshot opened.
> 
> Note that by default ShareX comes with an example Action that starts Microsoft Paint, you can even use that if you want.

Thank you!
