### ISSUE TITLE
Application path issue

### ISSUE THREAD

**Issue by gh-SAngeli** [ShareX/ShareX#6425]
Hi,
I don’t want to see in %userprofile%\documents the ShareX folder at all. As I know, through ShareX Application\Path settings I changed it to point elsewhere. The problem is that the program still wants to create its folder under %userprofile%\documents. So, now I see ShareX folder on both paths. If I try to delete it from %userprofile%\documents at next ShareX load the folder gets created again and all settings are lost. This is not how I wish to see this software behave.

Can anyone please tell me how to make so that ShareX will only appear to a specific path and totally disappear from %userprofile%\documents? 

Thank you

**Comment by gh-SAngeli** [comment]
Hi,
I see it is a duplicate issue BUT anyone can tell how to fix this?
I see many people complaining about the same issue. **How to solve it**???
Thank you

**Comment by sqal** [comment]
Yeah I have similar issue. I can change the path to whatever I want, but after a system reboot the path is restored to the default value, which is `C:\Users\<name>\OneDrive\Documents\ShareX`. 

ShareX version 14.1
