### ISSUE TITLE
ShareX upload

### ISSUE THREAD

**Issue by GoodNames18** [ShareX/ShareX#6426]
How to fix upload error? I tried different uploader it always say error

**Comment by L1Q** [comment]
Provide more information. What does the error look like? Does it say anything? What different uploaders did you try?

**Comment by GoodNames18** [comment]
Here the imgur ![04-22-32 PM](https://user-images.githubusercontent.com/41176431/182800236-53ad8633-32de-4430-969d-954a88427904.jpg)
Try on google photos but can't connect always failed.
![04-23-47 PM](https://user-images.githubusercontent.com/41176431/182800739-36525857-95cd-4ba3-9266-51da2d18d9a3.jpg)

**Comment by GoodNames18** [comment]
@L1Q
