### ISSUE TITLE
Improper scaling of fonts on save in 14.1.0

### ISSUE THREAD

**Issue by przemhb** [ShareX/ShareX#6427]
When saving an image edited with ShareX, first resized down and annotated fonts on saved fine are much bigger, than displayed in the editor.

Steps to reproduce:

1. Open hi resolution image. I used 4000x3000 px.
2. Resize it down to 960x720 px.
3. Annotate with Arial, 24.
4. Save the image file.
5. Compared what you edited and what has been stored.
6. Saved image should match the one displayed before saving, but it doesn't. Fonts are much bigger and don't fit into their boxes.

**Comment by L1Q** [comment]
Can confirm some misalignment, although I only resized 1080p to 800p.
Could not reproduce the font scaling issue both with zooming and with canvas scaling.
![image](https://user-images.githubusercontent.com/6942070/182874701-690c22e2-1dec-4d0e-ab25-5027743893a3.png)


### Following the reproduce steps

#### 1. Here is my 4000x3000 px image:
![wXaFH7lodT](https://user-images.githubusercontent.com/6942070/182876681-882ec120-8f41-4cdb-bf2d-9bf1605329aa.png)

When I annotate using Arial, 24, it looks like this:
![image](https://user-images.githubusercontent.com/6942070/182877295-0a09d6b3-ad2e-48bb-be9c-47924a50d995.png)
The text does not take a lot of space in the rectangle
When saved in this state, I get the following image:
![wXaFH7lodT_a](https://user-images.githubusercontent.com/6942070/182878164-875bab49-c073-4fea-bbdd-cc229eddbf84.png)
The size of everything is identical to the editor
![image](https://user-images.githubusercontent.com/6942070/182878365-b210ee81-7a74-4389-8ceb-02f18f7b8ba3.png)

#### 2. Resizing to 960x720 px
![image](https://user-images.githubusercontent.com/6942070/182878972-48bb2f23-af7e-4c10-8ecc-7fb4695ae14a.png)
![image](https://user-images.githubusercontent.com/6942070/182879200-3ea1df69-9f82-41e6-bb6c-7c3d41cad3b8.png)

❗Where is my text? ❗
🐛 Seems to be an issue with alignment, can confirm as a bug!
![image](https://user-images.githubusercontent.com/6942070/182879762-ccc8d40e-570a-490e-b2f5-72ff00ba95ec.png)

#### 3. Anyway, the above was not in reproduce steps, annotating a new text after resize

![image](https://user-images.githubusercontent.com/6942070/182880284-fde1a54c-b6d6-4923-9561-933de8255555.png)
Fits about right for the rectangle now!

#### 4. Saving this to a new file
The resulting file:
![wXaFH7lodT_ra](https://user-images.githubusercontent.com/6942070/182880991-ef046f54-1e75-4d4a-8eca-1fd6f4073b40.png)

#### 5. Comparing...
Very similar again
![image](https://user-images.githubusercontent.com/6942070/182881080-ed2f3f20-6cf4-46ab-9b39-29aeea598ae6.png)

#### 6. I observe matching fonts :shrug: 

There has to be something more to the reproduce steps.

**Comment by przemhb** [comment]
I do agree that must be something more. I generated jpeg file with just a gradient black-white, 4000x3000 px and repeated the steps. The issue didn't appear. On two computers. So I once again used file from Olympus TG-6 camera as a source. Just blurred the photo. The issue manifested this time.
Please find the source file attached to check what's causing the issue. Below also images showing how to reproduce it.

![00 sharex-bug-input](https://user-images.githubusercontent.com/9753991/183254477-47226224-d68d-4ee0-b510-17dd4123d61f.jpg)
^ source file

![01 sharex-bug-4000x3000-prior-resize](https://user-images.githubusercontent.com/9753991/183254497-43264d46-0c77-4743-b650-31e647382225.png)
^ Source file opened with ShareX, 4000x3000 px, prior to a resize.

![02 sharex-bug-resize-to-960x720](https://user-images.githubusercontent.com/9753991/183254527-ca851fc5-ce62-4a8b-b669-f8f295a2e9ca.png)
^ Resize settings. 960x720px.

![03 sharex-bug-resized-add text](https://user-images.githubusercontent.com/9753991/183254547-025d20de-5a72-4469-9528-e78720df372c.png)
^ Resized to 960x720, text on a background entered.

![04 sharex-bug-edition-complete-prior-save](https://user-images.githubusercontent.com/9753991/183254577-5fd817e9-ef51-4f0d-b99a-48bd15c3f22b.png)
^ Edition completed. Prior to save.

![05 sharex-bug-output-saved file](https://user-images.githubusercontent.com/9753991/183254599-1e369940-7667-4622-8910-9608ec2e3383.jpg)
^ Result. Saved file.

**Comment by L1Q** [comment]
I think I found a cause. Although from what I see, the image resizing step might be completely irrelevant.
Can you try just opening a 960x720 image and drawing the text there?
Also, do you have any DPI scaling enabled?

**Comment by L1Q** [comment]
Finally found the root cause of your struggles!

Loading an image into the ShareX Image editor preserves the DPI settings of the image. This setting is preserved after Image resize (hence the resize is not the critical part for reproduction). The DPI setting is also used for final image rendering with all the annotation shapes and Text boxes.

Now guess what DPI setting is used for the editor itself? Your monitor DPI!
So for cases where your camera is producing images with 144+ DPI and the editor is showing the text boxes with 96 DPI, the resulting text will be bigger.

I could reproduce a similar issue by setting my Windows DPI scaling to anything above 100%.
My text in the saved image will consistently be **_smaller_** than it was in the editor.

This is because my editor would show the text boxes at 120 DPI, and then save the text at 96 DPI.

**Comment by L1Q** [comment]
Current workaround: use any method to match the image DPI to your screen DPI.
You are lucky if the DPI of your screen is 96 (no scaling), as of ShareX 14.1, applying any Image effects, [sets the DPI of the image to 96](https://github.com/ShareX/ShareX/blob/develop/ShareX.ImageEffectsLib/ImageEffectPreset.cs#L44).
Some useless image effect will do:
![image](https://user-images.githubusercontent.com/6942070/183303987-0e81e20c-0ed7-48c0-992a-3ea9a08e31bc.png)

**Comment by L1Q** [comment]
Now to the real solution:
I think it's appropriate that ShareX is preserving the DPI of an image througout the editing process. I also think It's okay that Image Effects override it for whatever reason.
The issue only seems to appear for text.
I see two courses of action here:
- draw text-based drawings to their own rectangle using fixed dpi, then apply it to image, this way text will always match the size no matter what dpi the entire canvas is using.
- use screen dpi when saving the image to file, this ensures consistent scaling, perhaps with better text quality compared to the other option.

For testing purposes, uploading an altered DPI version of the ShareX logo.
High DPI:
![ShareX_Logo_256_highdpi](https://user-images.githubusercontent.com/6942070/183304753-15647604-c538-483d-ae67-d749cf7a72d8.png)
Low DPI:
![ShareX_Logo_256_lowdpi](https://user-images.githubusercontent.com/6942070/183304764-fa6f93f2-d9df-4524-94f6-7e12c03e3b37.png)

To reproduce:
1. Open any of the above image in ShareX Image editor
2. Annotate any text
3. Save As..
4. compare

Test with high DPI:
![image](https://user-images.githubusercontent.com/6942070/183304936-44246a5f-d34a-4b27-a18c-0205db298e06.png)
![image](https://user-images.githubusercontent.com/6942070/183304970-320760f1-1ba0-4257-b1cc-843a01cb672d.png)

Test with low DPI:
![image](https://user-images.githubusercontent.com/6942070/183305010-bddc0592-0908-42f7-9da2-ff670fa7fad7.png)
![image](https://user-images.githubusercontent.com/6942070/183305044-fb63ba2e-9660-49b8-8965-79aae868c9d2.png)

**Comment by L1Q** [comment]
@przemhb the issue should be completely fixed now. You can test it in [dev builds](https://getsharex.com/docs/dev-builds).
