### ISSUE TITLE
Not uploading screenshot to custom image uploader, instead copying to clipboard

### ISSUE THREAD

**Issue by notuvb** [ShareX/ShareX#6428]
So I recently configured ShareX to upload to a custom image uploader, but instead it still copies to clipboard.

My settings:
![image](https://user-images.githubusercontent.com/17932849/182951256-44bdec41-e615-4cf3-91b6-7401efc164f4.png)
![image](https://user-images.githubusercontent.com/17932849/182951281-24c5112d-a285-4b06-8dd0-11916fa66a65.png)
![image](https://user-images.githubusercontent.com/17932849/182951405-f4153734-8081-4111-940c-543a0d4696c3.png)
Some parts of this one ^ was blurred out so I don't show the image uploader to a bunch of people :L
Running the test shows that the uploader is working as intended, but when I go to actually make a screenshot, it still copies to my clipboard, and doesn't upload. I've tried restarting sharex several times

EDIT: Logs show this
2022-08-04 21:57:22.800 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2022-08-04 21:57:22.800 - Executing: Capture region
2022-08-04 21:57:25.636 - Task in queue. Job: Job, Type: Image, Host: 
2022-08-04 21:57:25.660 - Task status: Preparing
2022-08-04 21:57:25.669 - Image copied to clipboard.
2022-08-04 21:57:25.674 - Task completed. File name: ShareX_y1dBbOZ5qh.bmp, Duration: 14 ms
Showing that it is not even attempting to upload and is still just copying to clipboard

EDIT2: 
![image](https://user-images.githubusercontent.com/17932849/182953765-84e27225-ad6c-4b6b-82c1-2f1d56398f6e.png)
^ My config files, to prove that it has written to config

**Comment by L1Q** [comment]
Every hotkey can override global "After capture tasks" and "After upload tasks". Got to hotkey settings, click the cog icon next to your "Capture region" hotkey and make sure no checkmarks are checked in the "Task" tab like this:
![image](https://user-images.githubusercontent.com/6942070/182970885-1cb4a499-b420-4ca5-8a41-201807dead4e.png)
