### ISSUE TITLE
Up1 Support

### ISSUE THREAD

**Issue by Nucito** [ShareX/ShareX#6429]
It's possible to add support to Up1? if you accept i can make a pull request😁

**Comment by L1Q** [comment]
Looks like it was supported, but got removed in 2016 
 https://github.com/ShareX/ShareX/commit/c7b38b59f6ce5b59ffcfb50ac842c2d40a5fcc0e

**Comment by Nucito** [comment]
> Looks like it was supported, but got removed in 2016 [c7b38b5](https://github.com/ShareX/ShareX/commit/c7b38b59f6ce5b59ffcfb50ac842c2d40a5fcc0e)

Thx for the reply, and sorry for not searching the history 😅 was there any specific reason to remove it?

**Comment by L1Q** [comment]
As the commit message says, the service was down for a long time.
Even [the README](https://github.com/Upload/Up1#public-server) on the Up1 repository states it's "no longer available or being maintained".
![image](https://user-images.githubusercontent.com/6942070/183236223-b7ee05cb-b70c-4ca5-a6fa-e75ceb34504f.png)
