### ISSUE TITLE
 Why shadow glows?

### ISSUE THREAD

**Issue by mike2003** [ShareX/ShareX#643]
http://i.imgur.com/nIOMYLL.jpg
Why shadow does not work as it should?
Shadow should do background lot darker, not lighter! How to fix it?

**Comment by Jaex** [comment]
I didn't made Greenshot image editor.

**Comment by mike2003** [comment]
nice support

**Comment by Jaex** [comment]
You should have contacted Greenshot support for this.

**Comment by mike2003** [comment]
I can not understand.
I'm here from link from SHAREX (about-issues).
why we're talking about other app?

**Comment by Jaex** [comment]
Because you were using Greenshot image editor in your screenshot which have shadow behind arrow drawing. ShareX using Greenshot software image editor.

**Comment by jbouwens** [comment]
@mike2003 https://greenshot.atlassian.net/issues/?jql=project%3DBUG

**Comment by mike2003** [comment]
ok. thanks
