### ISSUE TITLE
Cannot select window

### ISSUE THREAD

**Issue by Mikestriken** [ShareX/ShareX#6431]
When I try to select a specific window to apply scrolling capture it highlights the entire screen and not just the window I want to capture.
![image_2022-08-05_115910436](https://user-images.githubusercontent.com/45702615/183115652-5548205a-e731-4520-8926-84aa237d7e43.png)
To the left of the image is my 2nd monitor, which when I hover my cursor in that monitor it also selects the entire screen instead of just the application I want selected.

**Comment by daviddutch** [comment]
This seems to be the same issue found here: https://github.com/ShareX/ShareX/issues/6147
