### ISSUE TITLE
ShareX error

### ISSUE THREAD

**Issue by DarkHunter7756** [ShareX/ShareX#6433]
System.Reflection.ReflectionTypeLoadException: Cannot load one or more requested types. See the LoaderExceptions property for more information.
    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
    in System.Reflection.Assembly.GetTypes()
    in ShareX.HelpersLib.Helpers.GetInstances[T]()
    in ShareX.UploadersLib.UploaderFactory.CacheServices[T,T2]()
    in ShareX.UploadersLib.UploaderFactory..cctor()

ShareX 14.1

What can i do?

**Comment by Jaex** [comment]
I think ShareX files become corrupt, try reinstalling it.

**Comment by libid0nes** [comment]
Reinstalling to any version does not help, the error occurs after the last windows 11 update.
