### ISSUE TITLE
Hash check file drag and drop not working for two files

### ISSUE THREAD

**Issue by SkryptX** [ShareX/ShareX#6434]
If I am using the hash check feature and I drag and drop a file into the window it fills the path to the file in the first text field. If I now activate "Compare two files" and drag a different file into the window (doesn't matter where) it replaces the path of the first text field with the second file instead of the second text field. Changing this behavior would make the dialog a lot more useful.

**Comment by Jaex** [comment]
I can add support to auto fill second text field when first text field already have file path. But this workaround only gonna work for first drag n drop. Because in second try, won't be possible to drag n drop to first text field in this way.

**Comment by SkryptX** [comment]
Yeah, I thought about it as well how to handle the whole-window-drag-n-drop feature and I think the correct solution would be:

1. Have the text fields work correctly. That's like 80% of the solution already.
2. The whole-window-drag-n-drop only fill the first field, since automatic text field swapping is confusing and more annoying than helpful.
3. OPTIONAL: The nicest solution would be a half-transparent-overlay that shows two zones with "First file" and "Second file" and depending on where you drop it, it would fill the first or second file path respectively. But that's just a lot of work (except you tell me otherwise :D) for a quite niche feature.

There are a lot of ideas for additional hash check features that could/should be implemented before spending time on perfecting this one feature.
