### ISSUE TITLE
post error

### ISSUE THREAD

**Issue by ZJ595** [ShareX/ShareX#6435]
Hello author. In the latest version of 14.1, I configured Lsky pro image bed upload, but the authentication failed every time. I grabbed the packet and looked at it, and found that all the characters after Bearer 5| in the request header disappeared. After tossing for a night last night, I once suspected that my configuration was not written properly. Finally, I tried the 13.7 version and found that the post was normal.
![](http://pic.rmb.bdstatic.com/bjh/6b9458791a269d229c41d8ffe3273de6.png)
![](http://pic.rmb.bdstatic.com/bjh/386980c603d4daf0b974385299c81591.png)

**Comment by Jaex** [comment]
Please escape `|` character like this: `\|`.
It is related to new syntax: https://getsharex.com/docs/custom-uploader#custom-uploader-syntax
