### ISSUE TITLE
Enhance the Pin

### ISSUE THREAD

**Issue by cei8** [ShareX/ShareX#6439]
"Pin to screen from clipboard"
"Pin to screen from screen..."
"Pin to screen from file..."

Could you make them a submenu of “Pin to screen"?

I just need "Pin to screen from screen..." that support hotkey.

**Comment by Jaex** [comment]
I also need hotkey for it but was not happy with "Pin to screen from screen" name. And because hotkey also gonna be named like this, I must make sure to name it properly.

**Comment by cei8** [comment]
Maybe "Pin to screen after capture" is better.
