### ISSUE TITLE
6GB to encode a 20sec gif??

### ISSUE THREAD

**Issue by Shybella** [ShareX/ShareX#6443]
https://prnt.sc/-_SMKt1hJVjW

This shouldn't be a thing, this is absolutely nuts.

**Comment by L1Q** [comment]
Totally agree, 20sec GIFs shouldn't be a thing, please use an actual video format

**Comment by Shybella** [comment]
20 seconds for a gif isn't that long. It even occurs with half the time. It's bad, end of story. 

I will try updating FFmpeg and give that a try. Thanks
