### ISSUE TITLE
Auto-update or option to skip until next update

### ISSUE THREAD

**Issue by drizztdourden08** [ShareX/ShareX#6452]
Hi,

I love ShareX but the only thing that annoys me is the prompt for update that's there all the times every time I start the app. There doesn't seeems to be a way to disable update prompt at all right now.

I would love for ShareX to be able to update itself without me going through a manual setup every single time. This is the main reason I am not updating it when it ask cause it's time I have to take just to do that. It might sounds petty but most of the times, I am on my work computer and it means allowing the setup to proceed with admins credential and then letting it download and install with the manual GUI setup.

ShareX is the kind of software you love but want to forget on your machine as it's there and does its job perfectly. This isn't the case right now and I don't feel it needs to update every single minor update.

My suggestion would be to add a checkbox allowing to disable update prompt entirely AND add one on the prompt that won't pompt until the next major update. (right now, the checkbox is only until next time you start the app. I don't how that's useful to be honest)

The other suggestion would be to change the way ShareX update itself and not requires admin and manual intervention to do so.

Regards,

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2022/08/ShareX_4swzsFkjjB.png)

**Comment by rivatove** [comment]
> ![](https://camo.githubusercontent.com/05ab0ae27791e4e82a8ba948ffbc279c388cbc653c87c380d94cfb439845292f/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032322f30382f5368617265585f3473777a73466b6a6a422e706e67)

@Jaex There's no such option on Windows. Where can I find this option now?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2025/01/ShareX_4aeweXqn75.png)
