### ISSUE TITLE
when capturing a screenshot, the windows 10 start bar is added

### ISSUE THREAD

**Issue by f1h0** [ShareX/ShareX#6455]
I found the error recently after installing Windows 10.
I used to have Windows 7.

The weird behavior is when I make any area selectable a 5x5 pixel square the windows 10 start bar is added.

I expect that it will not be on the screenshots of the start panel
unless the screenshot is full screen

![InkedIUClEnomDt_LI](https://user-images.githubusercontent.com/1436880/185099722-6e4799ca-33c1-46e4-ad2b-b7fa1087df40.jpg)

1. and here is an example where I made the selected area small
![image](https://user-images.githubusercontent.com/1436880/185100329-c258ff4c-67c1-4f7d-bca2-5d1d2834607f.png)

2. and here I tried to show how sharex itself makes the selection
![YandexDiskScreenshotEditor_zIsDihNeAg](https://user-images.githubusercontent.com/1436880/185100375-e37a1ab1-7185-43c4-be0f-01e716018b86.png)

did not change any settings, they are standard 100%
screen size 1366x768

**Comment by Jaex** [comment]
> did not change any settings, they are standard 100%

You literally added image effect and enabled it, how it is 100% standard.

**Comment by f1h0** [comment]
@Jaex  great thanks u
