### ISSUE TITLE
Quick copy different paths from main window with selected file

### ISSUE THREAD

**Issue by sected** [ShareX/ShareX#646]
My suggestion is to add ability to quick copy file path, file url into clipboard or doing any other actions with hotkeys.

**First case:**
I am uploading image and from main window i click on the result of uploading, pressing win+c (any others are configurable) and image url has been copied to clipboard.

**Another case:**
I would like to quick share file path with work team. So i am taking screenshot, pressing ctrl+alt+L and local file path has been copied to clipboard.

Please review this workflow for main window. Thank you!

**Comment by Jaex** [comment]
When there is no URL it should be copying local file path with ctrl + c but it not currently. Would it solve your problem?

**Comment by sected** [comment]
@Jaex yeah, thank you!
