### ISSUE TITLE
ShareX Screenshots Folder Variable?

### ISSUE THREAD

**Issue by megamorphg** [ShareX/ShareX#6462]
I like to distribute my ShareX configuration on two computers which have their own different ShareX screenshots folders (not on the C drive).
This causes an issue with ffmpeg specifications on over-ridden tasks.
Is there a way to reference the ShareX screenshots folder? (like the following)
![image](https://user-images.githubusercontent.com/1782353/186249093-35128902-f7da-4a71-a1ce-bbe85f8d3da5.png)

Otherwise I have to change all the tasks (which is a lot).

**Comment by botatooo** [comment]
What you try to do is add the folder that has ffmpeg inside it to your computer's PATH environment variable and then simply use `ffmpeg.exe` as FFmpeg path. I'm not sure if this works though.

**Comment by Jaex** [comment]
In next ShareX release FFmpeg gonna be included by default with installer and portable builds. So your issue gonna be resolved automatically too. Because ShareX gonna use that built-in FFmpeg instead of from external path.
