### ISSUE TITLE
sharex on linux & mac?

### ISSUE THREAD

**Issue by DeveloperKev** [ShareX/ShareX#6466]
Hi,
sharex is definitely the leading screenshot app so far. so, i don't think, it has to be limited to windows only. why not crossplatform?
thanks to the dev!

**Comment by botatooo** [comment]
sorry but there's currently no plan of going cross-platform

**Comment by demirdegerli** [comment]
Not officially supported but it's now possible to run ShareX through Wine and it's functional: #6531
