### ISSUE TITLE
Feature Request: Audio capture toggle

### ISSUE THREAD

**Issue by Artemis-chan** [ShareX/ShareX#6468]
I think it would be nice to have a toggle for audio capture when doing video capture, and then back when needed. Right now I can only do it by setting the audio capture device to none or using GIF capture(which is not ideal when you want to be able to scrub) It's pretty cumbersome. 

I am thinking about something like either a toggle next to the show cursor box. Also showing the toggle at top when selecting area(like still capture). Or a alternate button. Though with alternate button there would be multiple needed for screen/window/area capture, so probably just the toggle.

**Comment by robmonte** [comment]
Absolutely yes, many times you don't want audio but having to dig through settings to toggle it is way too tedious.
