### ISSUE TITLE
"Pin to screen" option seems missing for portable version

### ISSUE THREAD

**Issue by ameaninglessname** [ShareX/ShareX#6470]
![image](https://user-images.githubusercontent.com/20263103/187179345-95314522-14c4-42a2-af76-5d3f80e9908f.png)

I can't find the ["Pin to screen"](https://github.com/ShareX/ShareX/issues/2363#issuecomment-1192249442) anywhere in ShareX 14.1.0 portable version

**Comment by Jaex** [comment]
It is not released yet.
