### ISSUE TITLE
If clipboard contains a URL then use URL shortener not working

### ISSUE THREAD

**Issue by cx622** [ShareX/ShareX#6479]
![image](https://user-images.githubusercontent.com/81762466/187823852-10712079-a761-407f-81bd-d7df25eb6ecf.png)
I cant figure out how to use this. 
My shortener is working.

**Comment by Jaex** [comment]
It is not automatic. You must use the "Clipboard upload" function. For example with hotkey:

![](https://jaex.getsharex.com/2022/09/ShareX_9ijcpIpYtT.png)
