### ISSUE TITLE
Screen Frozen when taking screenshot

### ISSUE THREAD

**Issue by 2yangk23** [ShareX/ShareX#648]
When using the hotkey to take a screenshot, the screen will not update, so you are forced to capture a screenshot exactly during the time when the selection is initiated.  It would be better if the screen would continue to update so you can take a screenshot real-time.  Maybe add an option so people can choose.

**Comment by Jaex** [comment]
Set this capture method for your hotkey:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/04/aypZRrWghV.png)
