### ISSUE TITLE
Feature Request: drag and drop screenshot preview (toast notification)

### ISSUE THREAD

**Issue by paymanz** [ShareX/ShareX#6480]
Hi dear developer , 

i have a suggestion to have option to drag the preview of screenshot  (toast notification) in to other folders , move or copy.

Thanks in advance

**Comment by Jaex** [comment]
Hi,

It is actually exists but you must have "Save image to file" option is not enabled. So only when that option is enabled, then drag n drop from notification can work.

**Comment by paymanz** [comment]
> Hi,
> 
> It is actually exists but you must have "Save image to file" option not enabled. So only when that option is enabled, then drag n drop from notification works.

I see , but cant you please add a copy/move function so it would also work when save to file option is active?
