### ISSUE TITLE
Image dimensions are too large error message when using OCR

### ISSUE THREAD

**Issue by abdo2048** [ShareX/ShareX#6482]
I took a long screenshot and right click it from main windows, then "OCR image...".
but this message showed up!
```
The parameter is incorrect.
Image dimensions are too large! Check MaxImageDimension for maximum allowed image dimensions.
```
![image](https://user-images.githubusercontent.com/26915383/188288465-4ecfc65a-252d-41d8-bf1c-a53e99fa6088.png)

**Comment by reconrad48** [comment]
So this doesn't have a work around or tweak or config change? Why have a scrolling capture if it's going to max out? By default, the feature/function suggest that the height is going to be unusually large no?
