### ISSUE TITLE
Image Editor Feedback

### ISSUE THREAD

**Issue by sammikinsrox** [ShareX/ShareX#6487]
I posted this on the /r/ShareX subreddit but was advised that the developers may not read that sub. So I will post my suggestions here instead. I am using the bundled Image Editor. There is some unexpected behavior and some desired behavior while using the image editor.

- When right clicking an annotation object, it deletes the object instead of bringing up some sort of menu. I didn't expect this behavior when I first encountered it. And I still sometimes right click for some contextual menu and accidentally delete my annotation item. (You can't undo this action either)
- When UNDO-ing actions with CTRL+Z it often doesn't undo the last action, and instead jumps back several steps to remove the last annotation object added.
- When modifying text on the screen: when you double click to open the edit window, the software hiccups for a moment. When this happens, if you move your mouse during this hiccup period, the text will move to the new mouse location.
- Editing an image and adding annotations outside of the image canvas: add a feature to automatically expand the canvas to include added portions or provide a prompt when saving the image to do this.
- If expanding the canvas manually, show a selection window of the new canvas size as you enter new values. (My workaround for my canvas sizing woes has been to over-expand the canvas, then crop the image)
- Remove "Enter" as a hotkey to close editor and instead add a button for "Save and Close Editor". I've had a few instances where I closed the editor prematurely due to this hotkey. I don't believe this hotkey can be customized, though I could be wrong.
- This may be beyond the scope of this image editor, but, a basic layers system and layer rearrangement could be invaluable.

I'll probably add more to this as I use it more. I love your software and everything that it can do and I've been using for a couple years now; I've only just gotten into the image editor itself.

I recommend ShareX to everyone who needs image capture software.

**Comment by AngryCarrot61** [comment]
<img width="739" height="538" alt="Image" src="https://github.com/user-attachments/assets/512d895d-1261-402f-8e8f-193dc37879bd" />

<img width="786" height="702" alt="Image" src="https://github.com/user-attachments/assets/ba1e9fbe-f866-4975-a772-e403aaa2d5ac" />

I think somethinghs  is wrong with scaling.
