### ISSUE TITLE
Windows 11 and ShareX

### ISSUE THREAD

**Issue by TobyAdd** [ShareX/ShareX#6489]
When Microsoft made in Windows 11 rounded corners of window, the screenshot remains behind the back screen, can I do something so that the background is cut out?
![image](https://user-images.githubusercontent.com/66429886/188727287-c397b07b-3c61-47fb-90b6-2dd13b439fb6.png)

**Comment by TobyAdd** [comment]
sorry for grammatical mistakes, can you*

**Comment by rubenalamina** [comment]
Any information or progress on this? I'm also interested it having the screenshots cover the rounded corners in Windows 11.

**Comment by Araxeus** [comment]
There is also a corner radius option you can use, but what you want them to do? all images are rectangular.
the background is actually transparent and depends on the program/page that you display it in.

The following is the same screenshot, copied using different programs:
![image](https://user-images.githubusercontent.com/78568641/214675587-2e7450a9-c244-4085-b5ce-4e01e6ff2c64.png)
![image](https://user-images.githubusercontent.com/78568641/214674576-4f745016-78f4-4347-9efe-75694068a447.png)

**Comment by Void48** [comment]
> There is also a corner radius option you can use, but what you want them to do? all images are rectangular. the background is actually transparent and depends on the program/page that you display it in.
> 
> The following is the same screenshot: Screenshot from preview: ![image](https://user-images.githubusercontent.com/78568641/214677736-8c5697d0-f37c-4c5f-af79-282febcdf7bb.png) Copied from ShareX: ![image](https://user-images.githubusercontent.com/78568641/214674576-4f745016-78f4-4347-9efe-75694068a447.png) Copied from ImageGlass: ![image](https://user-images.githubusercontent.com/78568641/214675587-2e7450a9-c244-4085-b5ce-4e01e6ff2c64.png)

CornerRadius image effect seems to be the best option you can use right now but it's not perfect. It would be great if we could get true rounded corners screenshots without having to use the shadow effect/image effects like (CornerRadius)      

![](https://jaex.getsharex.com/2021/06/ShareX_sWgSdw4xlg.png)

_Originally posted by @Jaex in https://github.com/ShareX/ShareX/issues/5667#issuecomment-870135387_

**Comment by TobyAdd** [comment]
@Void48 @Araxeus thanks! I can close issue now
