### ISSUE TITLE
When copying image to clipboard with effects, there is a white background.

### ISSUE THREAD

**Issue by Xyphyn** [ShareX/ShareX#6490]
When you copy an image, and have it apply an effect that has transparency, the background is white.

![image](https://user-images.githubusercontent.com/80978739/188740301-c38e607f-96bb-4517-a420-cb9176d9943e.png)

What is odd is that the image it *saves* works with transparency. Here is the same image, but uploaded from my file explorer.

![explorer_V7ZucOcUey](https://user-images.githubusercontent.com/80978739/188740792-b73dd6f7-5f3d-4f31-a538-e30fa4374f55.png)

This is very strange. Any ideas?

**Comment by botatooo** [comment]
![image](https://user-images.githubusercontent.com/63275405/188742250-cf39eaa8-f234-4281-bc37-e9e1dad325c2.png)
By the way, this is a duplicate issue (#5339, among others).
