### ISSUE TITLE
How Does One Remove Dead Links in History

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#6495]
If possible please post how to remove dead links in ShareX history?

**Comment by jdcollier1968** [comment]
anyone?

**Comment by jdcollier1968** [comment]
anyone at all? seems like a basic question.

**Comment by Jaex** [comment]
> anyone at all? seems like a basic question.

There is no built-in way but you can write your own script for it.

@botatooo already wrote one yesterday to share with you.

**Comment by botatooo** [comment]
As @Jaex said, there's no plans to implement one built-in, but I made a quick python script to do it:
https://gist.github.com/botatooo/47de9f200111d5ed8377ef26bdebfa82
