### ISSUE TITLE
sharex making random folders

### ISSUE THREAD

**Issue by flounzy** [ShareX/ShareX#6499]
when i take a snip with sharex it makes and some application.json files and it also makes a folder for the month the snip was taken in for example 2022-09 why cant i just make it go directly to a file.

**Comment by demirdegerli** [comment]
Application settings --> Paths --> Delete the text in "Sub folder pattern" section

**Comment by flounzy** [comment]
theres nothing written already

**Comment by flounzy** [comment]
it still dosent work

**Comment by demirdegerli** [comment]
Where ShareX saving the screenshots now?
