### ISSUE TITLE
Saving settings fails with error

### ISSUE THREAD

**Issue by barbushin** [ShareX/ShareX#65]
Windows 7 x64, ShareX 8.5.0

ShareX was executed from installation Wizard. I opened Aplication settings, changed something, and when click on Close icon see error:

System.UnauthorizedAccessException: Отказано в доступе по пути "C:\Program Files\ShareX\PersonalPath.cfg".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   в System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   в System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   в System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   в ShareX.Program.WritePersonalPathConfig(String path)
   в System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

After I restart ShareX and the same problem reproduced. But, if I run ShareX as Administrator, so no error, everything works fine.

**Comment by AnsarAmantur303** [comment]
I found solution for this. In your antivirus there is a paragpraph called "Protected folders", where you should add to "Application Acess" ShareX, or to turn that off. For me that helped.
P.S. (Windows 10, my antivirus id Bitdefender)
