### ISSUE TITLE
[Feature request] Key binding for region capture

### ISSUE THREAD

**Issue by NTR0314** [ShareX/ShareX#6509]
When taking a screenshot I find it quite useful to use 'F'/'R' to use Free hand drawing / drawing a box. It would be nice if one could use a (default?) keybind to then select the region to capture.

![image](https://user-images.githubusercontent.com/25031668/190140420-25c39695-4305-4c7c-8ff2-44c204e0329b.png)
![image](https://user-images.githubusercontent.com/25031668/190140459-2c65bb4f-a8e7-4f56-a885-1fb6449b3078.png)

**Comment by Jaex** [comment]
You can press <kbd>Tab</kbd> to switch back to previously selected region tool.
