### ISSUE TITLE
Add upload file after drag and drop on tray icon

### ISSUE THREAD

**Issue by szegi** [ShareX/ShareX#651]
I used to Box Simple Share function
to upload files just by moving them on icon in tray

it would be great if you could add this option to ShareX :)

Sorry for my English

**Comment by Jaex** [comment]
It is not possible without doing ugly tricks like having transparent window top of tray icon etc.
http://stackoverflow.com/questions/2742954/drag-and-drop-on-notifyicon-in-tray-in-c-sharp

**Comment by szegi** [comment]
thanks for quick response:)
