### ISSUE TITLE
"Disable upload" prompts

### ISSUE THREAD

**Issue by anique9999** [ShareX/ShareX#6510]
Hi Team,

As soon as I take a "normal" (i.e. non-video/GIF) screen capture, it immediately says "Your system admin disabled the upload feature.". I know that it is referring to the fact that upload option is disabled via registry, but I'm not sure why it's trying to do that by default and failing. I'd assume that by default, it should just put it on the clipboard and wait for the user to paste it somewhere. 

Every time I take a screen capture, I receive this prompt "Your system admin disabled the upload feature." every single time. The point is that this leads to a very jarring UX for the common-case.

![image](https://user-images.githubusercontent.com/90675448/190583564-0f245321-5c45-4c72-84aa-d7c8f81f2ece.png)

**Comment by anique9999** [comment]
Any updates on this?

**Comment by StelioKontosXBL** [comment]
Can you provide a screenshot of your after capture and after upload tasks? Just open the submenus for them from the main screen and screenshot them.

**Comment by anique9999** [comment]
Hi @StelioKontosXBL ,
![image](https://user-images.githubusercontent.com/90675448/209287616-590f3118-9f8e-424a-ac93-f1ddc5f513b5.png)


![image](https://user-images.githubusercontent.com/90675448/209287559-4a99eda8-06d7-47e0-9a90-3557d2e7995d.png)


Note:- We have disabled upload option via registry.

**Comment by StelioKontosXBL** [comment]
Disable the **"Upload image to host"** task (in bold, from your image above).
