### ISSUE TITLE
[Feature request] Disable selecting graphical objects in image editor unless you're using Move tool

### ISSUE THREAD

**Issue by nikitsi-a** [ShareX/ShareX#6512]
Hi, the image editor in Sharex is very powerful but there's one issue.
Drawing lines or other objects is really tedious if they overlap even slightly. 
The editor prefers selecting and moving the existing graphics rather than drawing new ones on top.
Here's an example video where I try to draw a triangle with lines. 
https://user-images.githubusercontent.com/77513695/190629744-d0b68ffd-8b0b-41d6-900c-6aecc46b28de.mp4
This could be solved, if the user could choose to **disable selecting graphical objects** in image editor unless using Move tool.
Then you could draw pretty graphics that overlap or the endpoints meet, without the editor switching to Move mode sneakily.

I'd much prefer always using the Sharex image editor for everything but it's impossible to use it with overlapping lines.
Otherwise it's perfect!

**Comment by Jaex** [comment]
You can hold <kbd>Ctrl</kbd> key to disable object selection, but I must also disable selection of resize nodes.

**Comment by Jaex** [comment]
https://user-images.githubusercontent.com/822090/190845963-3e0ee71b-9c0a-40b1-bd74-732189206c5a.mp4

**Comment by nikitsi-a** [comment]
Wow, that's simply amazing, thank you so much! I hope you have a great weekend.

**Comment by gitgrub** [comment]
Cool :-)
