### ISSUE TITLE
[Feature Request] Toggle to show pointer/cursor in toolbar

### ISSUE THREAD

**Issue by PencilVoid** [ShareX/ShareX#6515]
Suggesting this because I've noticed that whether or not I want the cursor to show in a screenshot really depends on the screenshot itself, and I believe this is the same for many users. I know I could simply change the setting in the menu before taking the screenshot, but this is rather cumbersome and usage would be improved by giving users the ability to change this setting more quickly.

I imagine that this toggle would default to whatever is defined in the task settings menu, without remembering what state it was put in from the toolbar (remembering its state would make its existence in the task settings menu pointless).

I am aware of the existence of the cursor stamp, but it does not copy the current state of the cursor and defaults to the arrow, and users may not be able to accurately place it to illustrate where the cursor actually was.

**Comment by AbraxasDMG** [comment]
Hi. I tried to draw someone's attention in relation to toolbar enhancement too but no one responded.
Pointer toggle was one of the items I though would be useful addition to the toolbar: https://github.com/ShareX/ShareX/issues/6081

I ended up hard-coding those additional items by myself.
![image](https://user-images.githubusercontent.com/8733868/192513150-f2f8b2fa-9282-4848-8fca-f815e9b5a5f9.png)
I'm no programmer. It's a poorly done job but I had no other options and I didn't want to move to an alternative tool. Now I'm locked out of any updates, unless I want to repeat everything again and again. :(
