### ISSUE TITLE
What prevents "Capture active window"-hotkey-action?

### ISSUE THREAD

**Issue by PaveMentman** [ShareX/ShareX#6519]
---
Over the years this very same question has been asked numerous times without the exact definitive answer ranging from
"[Microsoft preventing the keypress reaching the hotkey-system of ShareX](https://github.com/ShareX/ShareX/issues/925#issuecomment-132495601)"
to
"[ShareX is not game capture software](https://steamcommunity.com/app/400040/discussions/1/1471969431591972306/#c1471969431592747959)"

One of the more definitive answer which also happened to be probably the earliest around was similar to former asnwer-variant:
"[window not allow hotkey to be triggered and there is nothing ShareX can do about it](https://github.com/ShareX/ShareX/issues/845#issuecomment-127008912)"
 

But the question left unanswered is "why"?
Why completely disabling "User Account Control" (on Windows 10 Pro via "Registry Editor" and "Local Security Policy") suddenly / finally allowed me to hotkey-capture
"(Microsoft) Resource Monitor"
and
"Libre Hardware Monitor"-window?

Why does "Euro Truck Simulator 2" still persists to "devour" my ShareX-hotkey-inputs
( outside the "Contracts / Jobs" and other menus that have a "write-some-text-here"-input-box ) 
while Steam-(Overlay-)Screenshot-button works like "always has been"
( alongside of course the horrid "freeze" that can last several seconds regardless of the running-software the screenshot is taken from )?
(( Infact, a key-relation "clue"-question probably is:
Why are all the "Fluent Design System"-GUI gone / turned into "bland-icons" on the "Task Switcher" (ALT+TAB-menu-screen) when I try to switch away from software(s) like "eurotrucks2.exe"? ))

What did "Fraps", "Xfire", "Raptr" and various other screenshot-tools (Greenshot?) do so much differently as opposed to ShareX?
 
 
These are only some of the questions I've "brain-hurting" myself over past "way too long".
 

I would like to emphasize that question of mine from genuine curiosity which might lead to eventually to solve this "puzzle" that been the bane of ShareX till until the unforeseeable future.

It is worth noting that, yes, all windows ( I for one am aware of ) can be captured via the "Task-bar-menu"
( Right-Click / Context-menu ShareX-icon -> Capture -> Window ->*running-window*.

And as the hotkey for "Capture active window" I use the numpad-asterisk/multiply/*-button;
I've tried numerous more "global"-buttons such as "Scroll Lock" on my Nordic-keyboard-layout without success with the aforementioned "ETS2"-game.
(Naturally) I also run everything in (bordered-)windowed-mode either forced with "wrapper"-tools or switched on with the built/cooked-in-code. 
 

(( Also worth noting that my primary inspiration for this question-post of mine is to have a bit more investigatory-up-to-date-conclusion Q&A in case there is nowadays more details unravelled since the previous answers in regards to this question.  ))

---

**Comment by Nammehub** [comment]
`What did "Fraps", "Xfire", "Raptr" and various other screenshot-tools (Greenshot?) do so much differently as opposed to ShareX?`
also OBS can do
