### ISSUE TITLE
Issue with mouse double-click in Automate Tool

### ISSUE THREAD

**Issue by szegi** [ShareX/ShareX#653]
I have mouse with double click
and when i use Add Cursor Position Button
it adds 2 positions in one line
screen-record
https://app.box.com/s/qxx0b7t5qxsrg6rcwhv40w9vmysogsgs

**Comment by Jaex** [comment]
When you click button two times of course it will add two positions, what were you expecting?
About error in video you not wrote what button to click left or right etc.

**Comment by szegi** [comment]
I know it should add two positions
but it adds them without spaces so you have to remember to add them to run script

**Comment by Jaex** [comment]
Oh you mean I needed to add new line automatically.
