### ISSUE TITLE
Authentication failure.

### ISSUE THREAD

**Issue by andy1k** [ShareX/ShareX#6537]
Authentication failure. when uploading, from nowhere. Why?

**Comment by BeAuMaN** [comment]
I'm getting the same issue right now.

**Comment by Erudite-Prime** [comment]
Just started getting this issue out of nowhere too... No clue where to begin fixing it.

**Comment by BeAuMaN** [comment]
I emailed Peppy at contact@ppy.sh but I'm not sure how often they check that email.
