### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by Erudite-Prime** [ShareX/ShareX#6538]
Only making this new thread because the other one was closed. I'm getting an "authentication failed" error and I don't even know where to begin to fix it.

**Comment by BeAuMaN** [comment]
Referenced closed thread: https://github.com/ShareX/ShareX/issues/6537

I think it's fine that it remains an open issue (because this may affect a lot of grandfathered puu.sh users) but also I don't think this is a ShareX issue. You're using ShareX in combination with Puu.sh/puush.me, right? That's what I'm using it with.

I tried using the original puush app and it had issues too. I also can't login or recover my account on the puush.me website.

**Comment by peppy** [comment]
We have been doing clean-up of unused accounts in preparation to potentially shut down the service. This was triggered by someone attempting to sell user data obtained in 2015 a few days ago.

If you have an issue you can contact dean@puush.me. We can reinstate accounts on a per user basis as required.

**Comment by botatooo** [comment]
If it's okay with you, can we redirect users to your comment if they ask for support on this issue?

**Comment by peppy** [comment]
> If it's okay with you, can we redirect users to your comment if they ask for support on this issue?

Yes that's fine. We'll probably put something up on the puush site if it gets too noisy. So far there's only been a handful of people reach out.

**Comment by BeAuMaN** [comment]
> We have been doing clean-up of unused accounts in preparation to potentially shut down the service. This was triggered by someone attempting to sell user data obtained in a 2015 data leak a few days ago.
> 
> If you have an issue you can contact [dean@puush.me](mailto:dean@puush.me). We can reinstate accounts on a per user basis as required.

Thanks Peppy! Sorry to hear this has happened. I probably use the service almost daily, so I'll reach out, though I understand if it ends up shutting down. Thanks again for the great free (and hassle-free) uploader service over the years!

**Comment by peppy** [comment]
I'll post the email we have sent out to active users so there's no missing context:

> Thanks for your continued usage of puush.
> 
> We have identified you as an active puush user, so we’re reaching out for two reasons:
> 
> Firstly, it has come to our attention that somebody is trying to sell data obtained from the breach back in 2015 (https://puushstatus.tumblr.com/post/115160990852/detailed-analysis-of-events).
> 
> Whilst from 2015, the information contained in the leak still consists of potentially sensitive data, such as: usernames, email addresses, hashed passwords (bcrypt) and API keys.
> 
> What does this mean for me?
> 
> Usernames & emails: Someone obtaining the leak would be able to determine if a given domain or email address had an associated puush account. They could also make connections between emails and usernames (if set). Depending on your expectation of privacy, this may or may not be a concern for you.
> 
> Hashed passwords: Passwords were hashed with the industry-standard bcrypt before storage. This means your passwords should be safe – bcrypt is a one-way algorithm and you cannot feasibly retrieve the password from a bcrypt hash. However, if you used the same password for other services, we recommend you exercise caution and consider changing your passwords regardless.
> 
> API keys: These are of particular note – while they were primarily used for the client to interact with the web service, they could also be used to log in to the website and subsequently access an account, including any uploaded (public and private) puushes. 
> 
> We could not confirm that all API keys were correctly reset after the initial breach, so we have reset all API keys again as a precautionary measure. We have also disabled the ability to login via API key. These two actions together should mitigate how much damage the API keys contained within the leak can cause at this point in time.
> 
> Whilst we cannot confirm that any accounts had unauthorized accesses, it may be best to assume that puushes of credentials/sensitive data or other private content in your account may have been compromised and act accordingly.
> 
> 
> What do I have to do?
> 
> - If you wish to continue using puush, you will need to either re-login to the puush client or, in the case of ShareX, update your API key manually. You can login to the site and retrieve your new key from https://puush.me/account/settings
> - If you no longer wish to use puush, feel free to reply to this email with the word "delete" somewhere in the reply and we can delete your account on your behalf.
> 
> Secondly, we want to take this opportunity to inform you that we are considering finally shutting down puush. The service has been in maintenance mode for years now and the team has long since moved on to other projects. There is no timeline for this yet, but if you rely on puush, now would be a good time to start looking for alternatives. If we do decide to shut the service down, we will likely provide a way for you to retrieve all your puushes.
> 
> We sincerely hope that the time, effort and money we have poured into keeping puush alive for the last decade has been beneficial to you.
> 
> The reply address of this email is monitored, so feel free to reach out if you need any assistance.
> 
> Regards,
> Dean & Jamie (the puush team)

I'd ask that you direct any further enquiries via email as to not unnecessarily spam this repository.
