### ISSUE TITLE
[Enhancement Request] or how do I do this.

### ISSUE THREAD

**Issue by pmisner** [ShareX/ShareX#6541]
I use ShareX portable at my job (rogue). It is especially helpful for the documentation we view. I'd like to get the software approved for use by the entire organization, but there is absolutely no way they would allowing the upload to different sites option. 
Is there a way to turn this off in a config file and/or lock down this functionality?
Thanks in advance and thank you for a consistently great product.

**Comment by Jaex** [comment]
Yes, check registry section here please: https://getsharex.com/docs/command-line-arguments#registry
