### ISSUE TITLE
How to Change/Update active API token

### ISSUE THREAD

**Issue by Varatnar** [ShareX/ShareX#6542]
I have been looking on how to change the api token for the puush api without success.

Following the recent "purge" that has happened on the puush side of things, I have reset my API token on their end.

It is unclear to me how I can now modify the used token in the ShareX application.

**Where are such information stored and how can I modify them ?**

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2022/10/explorer_gx3F1nMQJn.png)

**Comment by Varatnar** [comment]
I feel much more stupid now, but a big thanks for the reply !
