### ISSUE TITLE
[Feature Request] Ability to combine images into a grid

### ISSUE THREAD

**Issue by Sharps** [ShareX/ShareX#6543]
Hi,

I've been using the "Image combiner" feature a lot recently to show off my AI image generations.

My suggestion/request is to enable a way to tile/combine these images into a customizable grid by allowing people limit the the number of rows/columns forcing the overflowing images onto a new "line".

This would make it easy to say, share 20 images. Instead of a ridiculously long horizontal or vertical line of images they could just be in a nice 5x5 grid. My solution might not be the best but I'm sure many people would appreciate the ability to create image grids.

Here's an example image of what I have in mind, more or less:
https://i.imgur.com/Rxy6j1V.png

_P.S. Some small text with the number count of all links added to the combiner list would be useful too if this feature were to be added._

Much love for Sharex and the team, thank you!

**Comment by Jaex** [comment]
I thought about implementing this feature before, but I was unsure about plenty of things about it.

Such as name of the feature (both in UI and code).

Or which methods to implement:

* Wrap after specified max image size
* Wrap after specified max image count

**Comment by Jaex** [comment]
I think I will name it "Wrap after".

WrapAfter = `3`

Result:

![](https://jaex.getsharex.com/2022/10/HwN4JcHzrZ.png)

**Comment by Sharps** [comment]
Thanks for the lightning fast respoinse. Yes, "Wrap after" makes sense. Space between could maybe be called "Gap" instead of "Space". That's how the css property for adding space in between grid items is called in CSS grid. 

As for when to wrap, at least for my use case, I generate images in various sizes, one day it might be 512x512 the other 604x512. If the wrapping wass based on image count then the tool would work the same regardless and you wouldn't have to touch the settings at all. If it was based on image size then I'd have to keep fiddling with the "max width/height" settings to get the same result. I believe wrapping based on count is the way to go.

Also as I mentioned before it would be really nice to have a list item number count somewhere, just so if you want to make a nice 4x4 grid you could at a glance see when you've added 16 images to the list and know that your grid will be "complete" without counting the images yourself.
