### ISSUE TITLE
Screenshot is tinted orange.

### ISSUE THREAD

**Issue by ziziz** [ShareX/ShareX#6547]
All my screenshots are tinted orange. I have tried different capture methods, same result. ShareX have been working fine for me until 2022-06-14 when I got the first tinted screenshot, the screenshot before that was 2022-06-05 and that was fine.

I keep up with updates but can not see anything happening to the versions in that timeframe.
I have not modified any hardware in the last year.
I use Windows 10 (64), version: 21H2, build: 19044.2075
I currently use the latest stable release  of ShareX; 14.1.0

**Comment by L1Q** [comment]
Check if you have Night light enabled.
F.lux and Night light are known to change entire desktop colors.
![image](https://user-images.githubusercontent.com/6942070/195087326-8c138a41-47c5-469c-a2ab-98e8363f7db1.png)

**Comment by ziziz** [comment]
> Check if you have Night light enabled. F.lux and Night light are known to change entire desktop colors. 
Night light is not enabled and I do not have F.lux installed.
