### ISSUE TITLE
Some code doesn't pass `ShareX - ` to translations

### ISSUE THREAD

**Issue by PerchunPak** [ShareX/ShareX#6549]
https://github.com/ShareX/ShareX/blob/3491133dac0f2ebaac06fa70f7e9460775e9146f/ShareX/UploadManager.cs#L308
https://github.com/ShareX/ShareX/blob/3491133dac0f2ebaac06fa70f7e9460775e9146f/ShareX/HotkeyManager.cs#L201
https://github.com/ShareX/ShareX/blob/3491133dac0f2ebaac06fa70f7e9460775e9146f/ShareX/ImageData.cs#L59
(and many other places)

So languages that use `ShareX — ` instead of `ShareX - ` will show `-` (look at Ukrainian).

Fix could be to remove `ShareX - ` from all translations, or add `ShareX - ` part in those strings.

**Comment by L1Q** [comment]
Removing ``ShareX - `` from those lines would be better IMO

**Comment by L1Q** [comment]
Just checked, and Ukrainian is the only language using long dashes.
As you are in the process of updating it, it would also make sense to change back to normal dashes there as well.

**Comment by PerchunPak** [comment]
There are also some in russian.
![image](https://user-images.githubusercontent.com/68118654/195114422-eac540e7-d9f5-4a06-b4c1-69b70d9fc608.png)

**Comment by L1Q** [comment]
Yes, those lines are outdated as well now that I look, they don't even match English anymore.

**Comment by PerchunPak** [comment]
again, closed without notification
