### ISSUE TITLE
Point to "Edit with ShareX" from another app

### ISSUE THREAD

**Issue by Enissay** [ShareX/ShareX#6551]
I have a photo management tool ([faststone image viewer](https://www.faststone.org/FSViewerDetail.htm)) in which I can specify which tool to edit with. 

Sadly, in win10, ShareX exe does nothing when calling it from that tool and passing the filepath as argument.

Any suggestion how to do this ?

![image](https://user-images.githubusercontent.com/794673/195333750-46ecbeb7-250c-42a3-adb5-7a03388b481a.png)

**Comment by vassilyzaitsev** [comment]
You need to add a command line argument.

https://getsharex.com/docs/command-line-arguments#-imageeditor-image-file-path

![image](https://user-images.githubusercontent.com/35409978/195920636-4b763513-5a53-4729-8cda-52cbb29bc672.png)
