### ISSUE TITLE
ShareX not retaining white spaces when uploading to Pastebin, Gist etc.

### ISSUE THREAD

**Issue by GioFar81** [ShareX/ShareX#6555]
Hi, I'm a new user and tried to search for the same issue here and in other places but couldn't find anything.

When I select the text, right-click, and choose Upload with ShareX, the text gets uploaded but it will not retain white spaces, making the text a single long line, with codes, it's just too hard to go back and fix, and more convenient just to copy and paste straight on the actual website.

With ShareX being so good and having plenty of settings, I'm wondering if it's me missing some settings.

Kind Regards.

**Comment by ostrich** [comment]
Same issue. Newlines are dropped when using the "Text uploader" feature. Issue occurs with all text uploader destinations.

Here's what @GioFar81's comment looks like when uploaded to Pastebin:

![chrome_VqM4n9ZGUY](https://user-images.githubusercontent.com/570911/218475824-8e84e975-e6a6-4bf8-8c4c-ebd8e6180d87.png)
