### ISSUE TITLE
Can no longer connect to google drive

### ISSUE THREAD

**Issue by PoiDoex8** [ShareX/ShareX#6557]
![firefox_s7m3KQYq13](https://user-images.githubusercontent.com/20039012/196340456-a73bef6d-2f69-4fc7-b6df-44d7448b3aa4.png)
![firefox_eNfeISCspm](https://user-images.githubusercontent.com/20039012/196340465-c6902833-6315-432c-85d5-62938f82d520.png)

**Comment by Johnnycyan** [comment]
Bumping this.
