### ISSUE TITLE
SFTP uploading impossible

### ISSUE THREAD

**Issue by xNuance** [ShareX/ShareX#656]
Hello,
When trying to upload via sftp, and I have selected SFTP protocol, why does it still try to upload my screen with ftp:// or ftps://, that's not sftp.
![image](https://cloud.githubusercontent.com/assets/2312014/7431107/a20f6a10-f01b-11e4-9bd1-5275f3c60a8d.png) 
-------
![image](https://cloud.githubusercontent.com/assets/2312014/7431147/e5fbe7ee-f01b-11e4-8e87-c6475d3ca524.png)

**Comment by Jaex** [comment]
SFTP not using that server protocol at all.
