### ISSUE TITLE
Windows 11 border not in window capture

### ISSUE THREAD

**Issue by Christilut** [ShareX/ShareX#6565]
Windows 11 now has borders around all windows and it looks like ShareX thinks that is transparent and takes a 1 pixel border of whatever is behind the window.

I'm pressing ALT+PRINTSCREEN to make these screenshots.

This is what Windows CMD+SHIFT+S captures:
![image](https://user-images.githubusercontent.com/3471363/197338264-f309b183-4d9c-4be3-9c98-9db2ca85dc0e.png)

And this is what ShareX captured:
![image](https://user-images.githubusercontent.com/3471363/197338300-5bc7c136-dc9c-4508-b2b4-0af809689fd0.png)

The left border has artifacts, which is the 1 px of what was showing in the background when the capture was taken.

As an extra request, it would be nice if there was an option (or even default) to ignore the pixel border and take the capture without the border. That's personal since I don't like that border in my screenshots.

**Comment by Nagidrop** [comment]
I personally hate the 1px border too. Have you found a fix or workaround for this?

**Comment by Void48** [comment]
Same issue
