### ISSUE TITLE
Auto HDR in Windows 11 Bright Screenshots

### ISSUE THREAD

**Issue by ColliderGX** [ShareX/ShareX#6566]
I found that toggling off auto HDR in windows 11 immediatley stops screenshots from looking like a nuclear missile struck nearby.

**Comment by aeclasik** [comment]
OMG okay so thats what it was...just switched to SDR and screenshots look fine. Hope this gets addressed soon.

**Comment by Destreyf** [comment]
I ran into a similar thing, I found that there's a Windows HDR Calibration tool in the store, I just left a comnent on a separate issue, can you guys see if this helps with your setups?

I originally tested with AutoHDR disabled, but even after toggling it on it seems to be correct but maybe I need to restart apps for it to be negatively affected.

[https://github.com/ShareX/ShareX/issues/3751#issuecomment-1364412828](https://github.com/ShareX/ShareX/issues/3751#issuecomment-1364412828)

**Comment by ColliderGX** [comment]
> I ran into a similar thing, I found that there's a Windows HDR Calibration tool in the store, I just left a comnent on a separate issue, can you guys see if this helps with your setups?
> 
> I originally tested with AutoHDR disabled, but even after toggling it on it seems to be correct but maybe I need to restart apps for it to be negatively affected.
> 
> [#3751 (comment)](https://github.com/ShareX/ShareX/issues/3751#issuecomment-1364412828)

I figured out what fixes this, you have to set Chrome in Chrome flags to use SRGB color profile and this problem goes away.

**Comment by Destreyf** [comment]
Did you only have this issue when screenshotting chrome or did it affect other apps?  I was seeing issues in several apps besides chrome.

**Comment by ColliderGX** [comment]
> Did you only have this issue when screenshotting chrome or did it affect other apps? I was seeing issues in several apps besides chrome.

Being honest I think this only happened in Chrome, I have to test this more to see if the auto HDR function affected everything else because it did not affect Chrome at all.

**Comment by Destreyf** [comment]
Got it, thanks for the feedback, good to know about the SRGB color profile for chrome too!

**Comment by menix1337** [comment]
Have it as well here, also notice it affecting Discord Screensharing

**Comment by Sadin** [comment]
Anything with AutoHDR on looks washed out here when taking a screenshot. Only really happens to me on fullscreen/borderless apps.
