### ISSUE TITLE
`%ib` doesn't work in file naming patterns

### ISSUE THREAD

**Issue by PerchunPak** [ShareX/ShareX#6583]
![image](https://user-images.githubusercontent.com/68118654/200396830-45a6f124-31c3-4e6f-9f70-a6e93ea03c37.png)

**Comment by L1Q** [comment]
Similar to how ``%ra`` can take an argument for the length of the string, ``%ib`` takes an argument for the numeric base.
Try ``%ib{2}`` for base2 (binary) counter.
Unlike other patterns, the argument is mandatory for ``%ib``.

**Comment by L1Q** [comment]
Here is an enhancement suggestion:
- when ``%ib`` is selected using dropdown menus, add an argument by default
- also do it for any other patterns with non-optional arguments (if any).

**Comment by PerchunPak** [comment]
Would be nice to mention that `{}` is mandatory.

**Comment by PerchunPak** [comment]
> also do it for any other patterns with non-optional arguments (if any).

I found only `%rf`.
