### ISSUE TITLE
[Feature Request] Hold a button while cropping a screenshot to slow down the mouse

### ISSUE THREAD

**Issue by jordan-zilch** [ShareX/ShareX#6584]
If I want to select an area and fine-tune the start and end of the capture, it's quite annoying because any mouse movement shifts the cursor several pixels at a time. Hard to be precise.

**Comment by ahorn42** [comment]
I had the exact same issue and idea! Maybe something like holding Ctrl, Shift or Alt would be convenient.

**Comment by VianLaas** [comment]
Looks like what you're looking for can already be achieved by holding down CTRL+ArrowKey when cropping.

**Comment by ahorn42** [comment]
Hm - that works for the start point of the selection, but I can not figure out how to do it for the end point. Can you describe how to do this?

Anyways that's nice news already! :) 

I also did a short research on altering mouse speed, but this looks like a Win32-only solution, so I am not sure if this would be a good way to go.
https://stackoverflow.com/questions/2931122/dynamically-changing-mouse-speed

**Comment by VianLaas** [comment]
After playing around with the cropping tool a little, I noticed that the bottom and right borders move when using CTRL+ArrowKey, while the left and top borders move when using ALT+ArrowKey. Furthermore, the entire cropping area can be moved around with SHIFT+ArrowKey

**Comment by ahorn42** [comment]
@VianLaas thanks for you reply

But how do you start drawing the capturing area? 

I tried the following:

1. pressing PRINT to start capturing
2. now I can move the cursor via mouse or CTRL+Arrows to select the first corner
3. as soon as I let the mouse button up shareX saves a screenshot of the whole screen as I could not select anything

I can't set the second corner of the rectangle - unfortunately I am not able to do a screen recording of this (kind of a meta-problem :D)

Or is there a (keyboard) shortcut to start selecting an area?

**Comment by VianLaas** [comment]
Ah, it looks like I misinterpreted the original issue description. I was under the impression that captures need to be fine-tuned _after_ they were made, i.e., by using the cropping tool in the Image Editor.

To fine tune them _before_ they're made, you can go to Capture > Region (or select the topmost 'Rectangular Region' icon from the toolbar). Now, the entire screen should be bordered. Start drawing the region you want to capture, but _do not release the left mouse button_. While holding down the left mouse button, you can fine tune the end-point borders by using ALT+ArrowKey (effectively moving the cursor around). The starting point can be moved by moving the entire region using CTRL+ArrowKey.

Apologies for the confusion.

**Comment by ahorn42** [comment]
ouch - that was to simple 😄

But thanks a lot! - might be more intuitive with a slowed down mouse, but using the arrow keys while holing the left mouse button is definitively better then trying to match the pixels by mouse alone!

I discovered you also could just use the arrow keys without any modifier key to just move the last point (with out effecting the first point).

**Comment by StelioKontosXBL** [comment]
@Jaex or @waynebirdd this issue can probably be closed as completed.
