### ISSUE TITLE
Custom Sound doesn't work.

### ISSUE THREAD

**Issue by sekkure** [ShareX/ShareX#6586]
Added custom sound in settings, needed checkboxes checked but sound doesn't playing after taking screenshot.
This happens for both events, after successful task completion and when screenshot is taken.

Maybe I using wrong format for custom sound... Right now is mp3.

![ShareX_wT43NskfyG](https://user-images.githubusercontent.com/47090424/200862277-61870cef-2d47-4b04-b693-4b296ee32eec.png)

**Comment by Jaex** [comment]
Unfortunately only `wav` audio files supported.
