### ISSUE TITLE
Open tray menu on a left click

### ISSUE THREAD

**Issue by xPaw** [ShareX/ShareX#659]
Clicking on ShareX icon in tray once does nothing at the moment, perhaps make one left click act as a right click and open the tray menu?

**Comment by Jaex** [comment]
Then how double click supposed to work? When you can open it with right click why also left click?

**Comment by xPaw** [comment]
What's preventing it from doing both? One click shows the menu, double click opens the program.

**Comment by Jaex** [comment]
Because double click require two clicks and in first click it will open menu.

**Comment by xPaw** [comment]
Programs like Steam, and even Windows Defender implement it just fine. Although they seem to have a delay before the menu shows up on a left click.

**Comment by Jaex** [comment]
Steam have one second delay which lose all point, when you can open instantly with right click why wait one more second?
