### ISSUE TITLE
Can ShareX call a python script that would operate on the data (image or text) that ShareX captured?

### ISSUE THREAD

**Issue by marceepoonu** [ShareX/ShareX#6593]
Is it possible to create a workflow (i.e., sort of a macro) that would call an exe file, e.g., a python script that would operate on the data (image or text) that ShareX captured?

**Comment by L1Q** [comment]
Check out the Actions tab in the Task settings for your hotkey. [Literally what you are asking for.](https://getsharex.com/actions)
![image](https://user-images.githubusercontent.com/6942070/202360125-d5dc7760-52aa-4a80-96f1-7c72079b93da.png)

**Comment by marceepoonu** [comment]
Thank you so much.  Very much appreciated.
                 Marc
