### ISSUE TITLE
Bug - "Screen color picker info text" setting doesn't apply to screen color picker from color picker tool

### ISSUE THREAD

**Issue by Destroy666x** [ShareX/ShareX#6595]
Task Settings -> Tools -> Screen color picker info text
Let's assume you set that to `#$HEX$nR: $r255 G: $g255 B: $b255$nC: $c100 M: $m100 Y: $y100 K: $k100$n$name$nX: $x Y: $y`

It works fine if you use Tools -> Screen color picker as expected.

It doesn't work if you try to use Tools -> Color picker -> Screen color picker. There's some constant format used.

**Comment by StelioKontosXBL** [comment]
I noticed myself when making some usability fixes to the Color Picker for #6602, and was wondering about it but hadn't looked into it further. I'll take another look and include it in the PR.
