### ISSUE TITLE
[Feature request] Record audio exclusively

### ISSUE THREAD

**Issue by ItsCubeTime** [ShareX/ShareX#6596]
Hi 👋 Would be nice if we could record & upload audio files like MP3, WAV & FLAC.

**Comment by techanon** [comment]
You can just specify to have the Video Source in the screen recording options set to None and it will only capture as an audio file.
![image](https://user-images.githubusercontent.com/1837484/210127107-1a534112-a937-4988-9476-5849f1f555a3.png)

Wanting WAV and FLAC audio support is a separate issue.
