### ISSUE TITLE
Support for Tumblr and / or upload via eMail

### ISSUE THREAD

**Issue by shakeyourbunny** [ShareX/ShareX#66]
It would be really cool to have tumblr upload support (see www.tumblr.com/docs/en/api/v2) or uploading to a custom email adress.

**Comment by alexlehm** [comment]
Tumblr apparently discontinued the post by email feature. There are a few possibilities as work-around, there is a ruby script that can post to tumblr via command line or any oauth lib should be usable to create a post util
