### ISSUE TITLE
sxie effects file not being detected

### ISSUE THREAD

**Issue by fbauer-kunbus** [ShareX/ShareX#6601]
I installed ShareX with the current ShareX-14.1.0-setup.exe installer on my Windows 10 machine, and downloaded some sxie effects files.
Since 'sxie' is not associated with any ShareX component, double clicking the file does nothing but bringing up the app chooser dialog.
I then manually placed the xsie file into the Documents\ShareX\ImageEffects folder - but even after restarting ShareX, the effects are not being detected. I then also tried to manually associate the .sxie suffix with the ShareX .exe - but double clicking the file then tries to UPLOAD it to my Dropbox ...

How are the sxie files supposed to be installed? It is NOT working for me the way it is explained HERE:
https://getsharex.com/image-effects

**Comment by StelioKontosXBL** [comment]
Right-click one of the `.sxie` files, go to "Properties", then click "Change" to change the app it opens with. In the popup that Windows shows, click the link at the bottom to "show more apps", scroll all the way down, and click the "Look for another app on my PC" link. Then navigate to your ShareX installation folder and select the ShareX executable (it should be located at `C:\Program Files\ShareX\ShareX.exe`).

All that really shouldn't be necessary, but do it anyways to ensure the file association is set correctly. In my case, the extension was already associated with ShareX when I just tested it (as it should be for you also), and the image extension installed without an issue.

You may also want to check your Windows settings (search for "Choose default apps by file type" in the start menu).

![ApplicationFrameHost_GVYgTW5udc](https://user-images.githubusercontent.com/37424493/204189103-44eba394-9c16-43ca-85bd-79e92f6e8973.png)

**Comment by fbauer-kunbus** [comment]
Thank you - I already had the .sxie suffix associated with the ShareX.exe - but only after I did it AGAIN, now it works as expected Possibly the reboot of my PC finally did it ...
