### ISSUE TITLE
Clear all history

### ISSUE THREAD

**Issue by mrg9999** [ShareX/ShareX#6605]
Is there a simple one click way to clear all sharex histories? A button labelled clear history would be nice.

**Comment by StelioKontosXBL** [comment]
Keep in mind a history is more than just a preview of your previous screengrabs. It also stores deletion links for uploaded images, which you probably don't want to mass-delete unless you're ok with your history of uploads having a permanent home on the web, if not on your local machine.

My suggestions is to use the options under `Application Settings -> Settings` to export then clear your history, that way you at least have a backup file in case you need it. If you do an export while in a "fresh" state (no history), you could probably just import that file whenever you want to reset your history.

**Comment by jasonkcarter** [comment]
You can rename/delete the `Documents\ShareX\History.json` file.
