### ISSUE TITLE
Transparent background instead of white.

### ISSUE THREAD

**Issue by KoleckOLP** [ShareX/ShareX#6607]
Example pircture:
![image](https://user-images.githubusercontent.com/22729896/203627328-1bd99663-0fa9-4771-96f5-0c0086f7c648.png)

could the white be just transparent intead?
Is that a setting or not an option?

**Comment by StelioKontosXBL** [comment]
Like this?

![QNgB0GT](https://user-images.githubusercontent.com/37424493/204123035-24405833-ac8c-404b-9318-bb08f73e0ceb.png)

**Comment by KoleckOLP** [comment]
Yeah exactly like that!

**Comment by StelioKontosXBL** [comment]
That should be default behavior...check `Task Settings -> Image` and make sure it's not set to PNG 24-bit.

![ShareX_abHkew5nso](https://user-images.githubusercontent.com/37424493/204154473-12d1d96d-bf80-4aa9-9841-fd16aaa15b91.png)

**Comment by KoleckOLP** [comment]
It is set to default, and the background is still white on my system.
![image](https://user-images.githubusercontent.com/22729896/204206140-1687c54b-5ecd-4918-96d5-c3106dd4a221.png)
![image](https://user-images.githubusercontent.com/22729896/204206148-cdeeef78-1396-4ce9-8f70-cd434a3ac5dd.png)

**Comment by KoleckOLP** [comment]
I've found the issue, the picture that gets save to the screenshot folder is correct the one that goes into the Windows Clipboard is not.

Clipboard:
![image](https://user-images.githubusercontent.com/22729896/204206333-8266cdc1-1b5d-4e66-9014-2d5a8543879a.png)

Screenshot folder:
![chrome_hclnxROJhD](https://user-images.githubusercontent.com/22729896/204206357-45ad9de6-516f-4410-9850-fb16be4b14ac.png)

**Comment by StelioKontosXBL** [comment]
Makes sense. Glad you got it sorted. If possible, could you close this issue as resolved? Cheers

**Comment by KoleckOLP** [comment]
it's not sorted why does it not store transparent one in the clipboard?

**Comment by StelioKontosXBL** [comment]
Most likely due to the default .NET method used for clipboard storage of images, which drops the alpha channel (transparency). If you check your settings, it includes a couple other options that correctly save the alpha channel, along with a brief explanation of why that one is default.

**Comment by KoleckOLP** [comment]
What setting and where?

**Comment by StelioKontosXBL** [comment]
![ShareX_crDLqQ3jNT](https://user-images.githubusercontent.com/37424493/204506513-1afb90cd-66a7-4f40-99d2-47c661b9f18f.png)

**Comment by KoleckOLP** [comment]
Okay with the last two settings on stuff now works in the way would expect it to.
Only shame is that the settings are not on by default.

**Comment by StelioKontosXBL** [comment]
Right...you're welcome.

**Comment by daniiii5** [comment]
the alternative clipboard setting has been removed in newer versions, is there any fix?

**Comment by keso2user** [comment]
still does not work for me

**Comment by xLum1nous** [comment]
> still does not work for me
First, right click sharex tray icon and select hotkey settings. Click at ur preferred hotkey settings icon ( eg. Capture region ). Tick override after capture tasks. Deselect copy image to clipboard and select copy file to clipboard. Hope this can fix your issue ^^.
