### ISSUE TITLE
Why is ShareX converting my .png files to .jpg when uploaded?

### ISSUE THREAD

**Issue by Dx251** [ShareX/ShareX#661]
Hi all, I have an issue regarding file conversion when uploading .png images. I have a friend who is able to flawlessly do it (we both have our destinations linked to our imgur accounts) 100% of the time with his images, meanwhile mine just get converted. It has to be ShareX's doing, because I can upload directly to imgur and the file will still stay as .png, with no compression whatsoever. Can I get some possible suggestions on this?

**Comment by Jaex** [comment]
You mean this setting?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/05/ShareX_y08gVyhcbF.png)

Which can convert big images to jpg depending on your setting.

**Comment by Dx251** [comment]
Ahh, yeah. That's what my friend showed me. These were the settings he had on.

![lalvpta](https://cloud.githubusercontent.com/assets/12225756/7448919/cf47d7ac-f1f5-11e4-8f96-6b45f7813f09.png)

I tried the same thing but didn't get any different results.

**Comment by Jaex** [comment]
Also Imgur can compress bigger images.

"Currently we compress images over 5MB for anon uploads. We might lift this restriction down the road, but for now we don't have any parameters to disable this."

**Comment by Dx251** [comment]
Its weird though, I've uploaded the images I want directly to imgur through the website and they came out fine, but the second I upload through ShareX, it turns it into a .jpg

I've tested it with some images, I uploaded one through ShareX that was a mere 990kb, no problems. I uploaded a different image that was 1.2mb and then it converted it to jpg. Both were 1920x1080 images. I don't know, I thought it would be imgur but my friend is getting absolutely no problems on his end when he uploads though ShareX

**Comment by Kesmy** [comment]
@Dx251 Verify that you're using "User" and not Anon in the imgur destination settings

**Comment by Dx251** [comment]
@Kesmy Oh wow, that did the trick! Thank you so much! My images are large and crisp again.

**Comment by D-MAS** [comment]
now the setting is "Use JPG if file is above x kb"
