### ISSUE TITLE
Qr Code Reader not working on a specific QrCode

### ISSUE THREAD

**Issue by sivelswhy** [ShareX/ShareX#6610]
Hello, I have a qr code where it simply doesn't recognize it. If I try scanning with my iPhone it works, but not with shareX.
I'm giving the qr code below if it can help improve shareX. Thank you
* Software Version : 14.1
* OS Version : Windows 22H2 (build 22621.819)
![image](https://user-images.githubusercontent.com/82051273/203862636-c17c1ee6-a843-4c20-8270-6631efb4cca0.png)

**Comment by HOSEK1** [comment]
I got it to work by simply cropping and zooming in (nearest neighbor scaling)
