### ISSUE TITLE
Have to repeatedly click tool bar item

### ISSUE THREAD

**Issue by INEEDBOB** [ShareX/ShareX#6611]
When in capture mode, if i use lets say the Highlight tool, i click it, use it, then have to repeat each time. Is there a setting somewhere that allows me to choose it once on the tool bar then just use it over and over until i finish the capture?
Looked but cant find any such settings, its a big time waster.
Thanks!

**Comment by StelioKontosXBL** [comment]
@INEEDBOB try unchecking these two options. Also, see the second screenshot for my mouse button bind settings; makes it easy to switch between the selection tool (to take the screenshot) and the drawing tool.

![ShareX_R2EtiXnaL4](https://user-images.githubusercontent.com/37424493/204190144-f159bd5e-a56f-47a6-8f1d-4e26c50b1eb9.png)

![ShareX_OUHwUcIaNF](https://user-images.githubusercontent.com/37424493/204190328-79cc3d48-a343-48ab-a4a6-aee5d9c0cab1.png)

**Comment by INEEDBOB** [comment]
It actually was the first one of those two item. :) Was checked and unchecking that did it. I probably looked over that dropdown 10x but didn't try that. Thanks!

**Comment by StelioKontosXBL** [comment]
No problem, glad to help. If you're all set, please close issue as resolved when able.

**Comment by INEEDBOB** [comment]
Solved.
