### ISSUE TITLE
Stick to top after screenshot

### ISSUE THREAD

**Issue by hcllmsx** [ShareX/ShareX#6613]
How can I put the picture on top after taking a screenshot. Can this feature be added?

**Comment by StelioKontosXBL** [comment]
What do you mean by putting a picture "on top"? On top of what? Are you referring to above others in a list view? Order of appearance in a history view? Layer position in edit mode? Screen position of an image editor used to display the image in your task? Position in an upload queue?....

**Comment by hcllmsx** [comment]
Hahaha, sorry, I can't speak English. I use Google Translator. I mean, after the picture is cut, put the picture on the computer screen, and then keep the picture at the top. Just like the function of the software [snapest](https://www.snipaste.com/).
![image](https://user-images.githubusercontent.com/63240764/204121366-b54cf308-b257-40d5-a91c-7cc3bdf26cff.png)

**Comment by StelioKontosXBL** [comment]
It's ok, thanks for the clarification. 

I have not used that other app before, but it sounds like you want the screenshot to open in an image viewer (like Microsoft's Photos app) automatically, as soon as you take the screenshot?

**Comment by hcllmsx** [comment]
no!  Let me show you.

https://user-images.githubusercontent.com/63240764/204121982-2029fb00-d74a-4ff4-a80e-2a1124ada937.mp4

Can you understand now?

**Comment by StelioKontosXBL** [comment]
I can see that would be very helpful; being able to use your screen as a "paste board" for screenshots with the ability to annotate or move/resize them like a collage.

Personally, I like the idea. Implementing the basic functionality for that would be relatively simple. The primary issues in my mind would be:

- Integration: how it should be implemented with the ShareX workflow as a whole.
- Functionality: initial features, bindings, and integration of a menu bar (like image editing has) for the initial iteration.

@Jaex would be the one to decide if this feature should be considered.

I'd be willing to help spearhead this feature, if it gets added to the roadmap.

**Comment by StelioKontosXBL** [comment]
By the way, ShareX does already have something similar to what you are talking about, but as far as I can tell it's restricted to a single capture window...meaning your main screen is not usable while the clipped images are visible.

Extending this functionality so it's available outside of the single-frame screengrab context so it overlays your other applications (instead of only being available over a static snapshot of your screen when you started the screenshot) might be the way to go. See gif below for the current implementation

![HSkYee45n4](https://user-images.githubusercontent.com/37424493/204123546-87b29463-d720-446a-97b6-72196234ad67.gif)

https://i.imgur.com/X5UZte8.gif

**Comment by hcllmsx** [comment]
I really want this feature. It's very convenient. I believe many people will like this feature. I can paste the screenshot on the top of the screen as a reference, and then use Adobe PS to draw, or Adobe AE, or something else. Anyway, you can experience the software Snipate（[https://www.snipaste.com/](https://www.snipaste.com/)）. I now have to install ShareX and Snippate at the same time. ShareX can make GIFs, but Snipaste cannot. If ShareX also has the function of top mapping, then I can uninstall Snippate.

https://user-images.githubusercontent.com/63240764/204127687-d1d450b1-90b6-405f-aeae-4667c0484696.mp4
[https://streamja.com/0OJWG](https://streamja.com/0OJWG)

**Comment by ZacZhangzhuo** [comment]
Agree, we need that function in many cases. 

Imagine that we got a formula.jpg in the browser and tried to type this into a notebook. it would be painful to switch into the browser, memorise some alphabets, switch back to the notebook, type and then repeat. The 'paste on screen' function would allow us to keep the formula.jpg (input) and the notebook (output) on one screen without switching. It would be super handy. 

You can refer to the 'paste images as topmost floating windows' function in Snippate as an example (https://www.snipaste.com/) as @hcllmsx mentioned. 

We really look forward to having this function. Thanks a lot.

Cheers! :)

**Comment by ZacZhangzhuo** [comment]
look forward. let us know if we can contribute the developing to make it happen :) @Ste1io @Jaex

**Comment by hcllmsx** [comment]
When will this feature be implemented and have you adopted the suggestions?

**Comment by Ste1io** [comment]
@ZacZhangzhuo @hcllmsx Unfortunately, I doubt it will happen under the current leadership. I've contributed a couple pull requests closing outstanding issues (see #6623 and #6603) that were completely ignored, and eventually slipped into stale status, so there's little motivation to waste time for nothing, unfortunately.

@Jaex

**Comment by Jaex** [comment]
> @ZacZhangzhuo @hcllmsx Unfortunately, I doubt it will happen under the current leadership. I've contributed a couple pull requests closing outstanding issues (see #6623 and #6603) that were completely ignored, and eventually slipped into stale status, so there's little motivation to waste time for nothing, unfortunately.

I implemented "Pin to screen" feature 4 months before this issue is created:

![](https://jaex.getsharex.com/2023/10/GitHubDesktop_XF3TCepZxI.png)

And released it 10 months ago:

![](https://jaex.getsharex.com/2023/10/chrome_1Y1DlFGS7F.png)

**Comment by Ste1io** [comment]
@Jaex and the two PRs I mentioned?
