### ISSUE TITLE
Screen recording/ffmpeg settings: In the x264/x265 tab, tooltip string for default CRF value inconsistent.

### ISSUE THREAD

**Issue by WinkelCode** [ShareX/ShareX#6616]
![Screenshot 2022-11-30 021651](https://user-images.githubusercontent.com/29005772/204683924-b9cfaea9-e294-494b-b4f2-7a36adde2385.png)

Seems all over the place in translations as well, some say 30, some 23, correct seems to be 28: https://github.com/search?q=repo%3AShareX%2FShareX+nudx264CRF.ToolTip&type=code&p=1

**Comment by StelioKontosXBL** [comment]
> some say 30, some 23, correct seems to be 28

The correct default CRF value is 28, [according to the docs](https://trac.ffmpeg.org/wiki/Encode/H.265#Ratecontrolmodes).

On the same note, the default x264_Present should be `medium` (not `ultrafast`, as it is currently):

https://github.com/ShareX/ShareX/blob/2de97eea497ab9c1796b889c3079b0223e0e3649/ShareX.ScreenCaptureLib/ScreenRecording/FFmpegOptions.cs#L46-L47
