### ISSUE TITLE
Отказано в доступе по пути "D:\YandexDisk\Скриншоты\2022-12-01".

### ISSUE THREAD

**Issue by svbel85** [ShareX/ShareX#6618]
При создании новой подпапки всегда эта ошибка - программа вылетает. Если открыть заново то ошибка уходит

System.UnauthorizedAccessException: Отказано в доступе по пути "D:\YandexDisk\Скриншоты\2022-12-01".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   в ShareX.HelpersLib.FileHelpers.IsFileLocked(String filePath)
   в ShareX.WatchFolder.<>c__DisplayClass17_0.<fileWatcher_Created>b__0()
   в ShareX.HelpersLib.Helpers.WaitWhile(Func`1 check, Int32 interval, Int32 timeout)
   в ShareX.HelpersLib.Helpers.<>c__DisplayClass54_0.<WaitWhileAsync>b__0()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ShareX.HelpersLib.Helpers.<WaitWhileAsync>d__54.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ShareX.WatchFolder.<fileWatcher_Created>d__17.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()

ShareX 14.1

**Comment by StelioKontosXBL** [comment]
Please explain the steps needed to reproduce this. Error appears to be an issue with trying to access a file that's already open by another process.

**Comment by svbel85** [comment]
Good afternoon. I realized that if I place a directory of screenshots on a cloud drive (yandex drive), then this error occurs when creating a subfolder. Every day I have a new subfolder for screenshots. I transferred to a regular disk and the problem went away.

**Comment by dmxt** [comment]
Try renaming the folder Скриншоты to English directory like "Screenshots"

# Here's a translation:

When creating a new subfolder, there is always this error - the program crashes. If you open it again, the error goes away.

```
System.UnauthorizedAccessException: Отказано в доступе по пути "D:\YandexDisk\Скриншоты\2022-12-01".
в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
в ShareX.HelpersLib.FileHelpers.IsFileLocked(String filePath)
в ShareX.WatchFolder.<>c__DisplayClass17_0.<fileWatcher_Created>b__0()
в ShareX.HelpersLib.Helpers.WaitWhile(Func`1 check, Int32 interval, Int32 timeout)
at ShareX.HelpersLib.Helpers.<>c__DisplayClass54_0.b__0()
at System.Threading.Tasks.Task.Execute()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo .Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ShareX.HelpersLib.Helpers.d__54.MoveNext()
--- End stack trace from previous location where exception occurred ---
at System.Runtime .ExceptionServices.ExceptionDispatchInfo.Throw()
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
in ShareX.WatchFolder.<fileWatcher_Created>d__17.MoveNext()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
to System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
to System.Threading.ThreadPoolWorkQueue.Dispatch()

ShareX 14.1
```

**Comment by TheRealBix** [comment]
Hi, I think I have the exact same problem.
Everytime a new sub-folder is created in a watched folder, ShareX craches.
Tested with and without Windows Defender.

Steps to reproduce : Set a folder to watch, create a new subfolder inside, crash.
