### ISSUE TITLE
Pleeease : How can unhide Sharex side menu

### ISSUE THREAD

**Issue by Rrrrf** [ShareX/ShareX#6619]
Hi - While scrolling through the Application settings, I accidentally hid the side menu. How can I restore it? I am not able to do anything without the side menu.. any ideas please?

**Comment by StelioKontosXBL** [comment]
Which menu are you referring to? Is it one of the ones in shown [in these screenshots](https://getsharex.com/screenshots)?

**Comment by StelioKontosXBL** [comment]
Post a screenshot of how it looks for you now, please. Still unclear what is missing, and from which form window.

**Comment by Rrrrf** [comment]
@StelioKontosXBL **Here is what I see now** 

![ShareX_beaRBs4s62](https://user-images.githubusercontent.com/11408745/205330134-50b308f5-eeac-4db6-90ff-a03de9d9e461.png)


I cannot see the regular menu as shown in this screenshot below (that I got from the webpage you sent):


![image-89](https://user-images.githubusercontent.com/11408745/205330302-8f792d84-0d49-42df-abf1-8155f29af53d.png)

**Comment by StelioKontosXBL** [comment]
1. Right-click the ShareX tray icon
2. Select "Application Settings"
3. Click on "Main Window"
4. Check the "Show menu" option
5. Close the settings window

![N7muXl4WX2](https://user-images.githubusercontent.com/37424493/205341749-f9546c30-d3ac-41db-bdef-54d5e67ca079.gif)

**Comment by Rrrrf** [comment]
@StelioKontosXBL Thank you! Thank you! Thank you so much!!!!

**Comment by lukehimself** [comment]
And if you've hidden the taskbar icon...?

**Comment by Ste1io** [comment]
> And if you've hidden the taskbar icon...?

...unhide it? 🤔

**Comment by lukehimself** [comment]
> > And if you've hidden the taskbar icon...?
> 
> ...unhide it? 🤔

You can't unhide it when the menu is hidden too...

**Comment by Ste1io** [comment]
> You can't unhide it when the menu is hidden too...

https://github.com/ShareX/ShareX/issues/6652

**Comment by lukehimself** [comment]
I had done that, which fixed it. More concerned about users who aren't as comfortable with that. Even a warning beforehand could resolve it.

**Comment by Ste1io** [comment]
Unfortunately, this project is a graveyard of  PRs which are blithely ignored by the maintainer, so I wouldn't hold my breath.
