### ISSUE TITLE
This appears every time I take a screenshot:

### ISSUE THREAD

**Issue by k1r8yy** [ShareX/ShareX#6621]
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   em ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   em ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   em ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
O servidor remoto retornou um erro: (429) Too Many Requests.

Request URL:
https://api.imgur.com/3/upload

Status code:
(429) Too Many Requests

Headers:
Connection: keep-alive
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1120
X-Post-Rate-Limit-Reset: 2898
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
X-Served-By: cache-mia11389-MIA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1669927717.912014,VS0,VE172
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 139
Content-Type: application/vnd.imgur.v1+json
Date: Thu, 01 Dec 2022 20:48:37 GMT
Server: cat factory 1.0

Response text:
{"errors":[{"id":"legacy-api-789b64f687-qrdbj/KLLGgUdSJ6-131462","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}

Stack trace:
   em System.Net.HttpWebRequest.GetResponse()
   em ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   em ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   em ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   em ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
O servidor remoto retornou um erro: (429) Too Many Requests.

Request URL:
https://api.imgur.com/3/upload

Status code:
(429) Too Many Requests

Headers:
Connection: keep-alive
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1119
X-Post-Rate-Limit-Reset: 2896
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
X-Served-By: cache-mia11389-MIA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1669927718.215778,VS0,VE176
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 139
Content-Type: application/vnd.imgur.v1+json
Date: Thu, 01 Dec 2022 20:48:38 GMT
Server: cat factory 1.0

Response text:
{"errors":[{"id":"legacy-api-789b64f687-jgmpf/HxStjg7iU2-131671","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}

Stack trace:
   em System.Net.HttpWebRequest.GetResponse()
   em ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by StelioKontosXBL** [comment]
> Request URL: https://api.imgur.com/3/upload
> 
> Status code: (429) Too Many Requests

The error message says the reason ^

There's a cooldown period...wait awhile, or just upload manually on the site. Original cause of failing to upload could've been improper file size (a long gif). 

Also make sure ShareX is updated...this is from the legacy API. Updating ShareX may fix it actually.
