### ISSUE TITLE
ShareX OCR no longer working properly

### ISSUE THREAD

**Issue by rvtis** [ShareX/ShareX#6626]
Please undo whatever you did to make ShareX OCR rely on installed Windows Languages. As a multilingual person, I do NOT want to have 30 languages on my PC (that I have to scroll through whenever I use another language) just because I need to copy something in Chinese once in a while, nor does installing a language pack and uninstalling afterwards sound appealing. It used to be that you'd just get a language selector and you can scan all you want! Why did you remove this? Please bring it back!

**Comment by jkune5** [comment]
Me too. Im having the same problem especially since Im using a custom OS. I dont know what could be the problem. I have 3 languages installed and my interface language is english. But somehow OCR doesnt show english in the dropdown
