### ISSUE TITLE
ShareX doesn't starting.

### ISSUE THREAD

**Issue by mrksbgg** [ShareX/ShareX#6629]
**I've tried stable release (from sharex website), and dev release (i uninstalled stable and installed dev). When i opening ShareX its closing. Video: https://youtu.be/cRGd6m4cjUU**

**Comment by StelioKontosXBL** [comment]
Looks like Windows AV being overly zealous and silently removing it (a known issue if the app is packed, or if Windows doesn't recognize it as being the authentic ShareX - which is a possibility, given it's the dev version). I've had this happen to some of my own apps as well. You can try whitelisting it in the Windows Security settings.

tbf, though, you're probably just best off running the current distribution release. The dev version is primarily there for...devs.

**Comment by mrksbgg** [comment]
> Looks like Windows AV being overly zealous and silently removing it (a known issue if the app is packed, or if Windows doesn't recognize it as being the authentic ShareX - which is a possibility, given it's the dev version). I've had this happen to some of my own apps as well. You can try whitelisting it in the Windows Security settings.
> 
> tbf, though, you're probably just best off running the current distribution release. The dev version is primarily there for...devs.

I added an exception for ShareX, restarted PC and its not working.
