### ISSUE TITLE
Request - Direct Access to Greenshot Image Editor (from Context Menu)

### ISSUE THREAD

**Issue by Fuzzoom** [ShareX/ShareX#663]
Can you add a Context Menu option to "Edit Image with ShareX", or allow us to access "Greenshot Image Editor" separately from the main ShareX program?

Currently, every time I go to edit an image with ShareX from my Win 7 documents, it automatically uploads the image to the internet, before I can choose to Edit the image. I'd prefer to be able to just edit the image in ShareX without having it automatically upload the original from my documents folder.

Here is a video preview of my issue:
http://bit.ly/1IH4LFK

**Comment by Fuzzoom** [comment]
Here is a video preview of my problem:
http://bit.ly/1IH4LFK

I'd also like to be able to easily choose Gfycat as a video upload option, if possible.

**Comment by Jaex** [comment]
What is difficult in Gfycat choose?

**Comment by Fuzzoom** [comment]
Is that supposed to be on the list already? 
Cause all I see are these options: http://imgur.com/Ai4juJ6

**Comment by Jaex** [comment]
Not every destination have options.

**Comment by Fuzzoom** [comment]
Eh, I guess I can just drag and drop into Gfycat. So if thats a nuisance, nevermind it.

But it would be nice to be able to directly access the image editor, cause most of the default ones suck now.

**Comment by Jaex** [comment]
ShareX already can upload to Gfycat.

**Comment by Fuzzoom** [comment]
Oh... sorry about that... I see it now. >.<

**Comment by Jaex** [comment]
I'm not planning to add Greenshot to Windows shell context menu because then I need to add countless other things to there too. Maybe you should ask this to Greenshot developers and install their software to use as standalone image editor?
