### ISSUE TITLE
Recorded audio is way too quiet

### ISSUE THREAD

**Issue by cademcniven** [ShareX/ShareX#6630]
When capturing audio, the resulting mp3 file is so quiet it's barely audible. I've scoured the internet and this seems to be a very common issue without anyone actually ever having resolved it.

I've tried a few things:

In my screen recording options I am using the following command

```
-y -rtbufsize 100M -f dshow -i audio="virtual-audio-capturer" -c:a libmp3lame -filter:a "volume=80" -af silenceremove=1:0:-50dB -qscale:a 4 "$output$"
```

For volume=80 I've tried many numbers here, even up to 8000 and there has been no noticeable difference.

I've tried turning up the volume of my computer, as well as the application I'm trying to capture audio for, without any super noticeable differences (it *might* be slightly louder in the recorder, but the difference is small enough that I can't actually tell).

I've tried plugging in headphones to the computer (several people reported this fixed the issue somehow) -- the volume seemed slightly better in this case, but still far too quiet.

My full screen recording settings are here: 

![image](https://user-images.githubusercontent.com/17060136/205994935-5523c47e-3981-42d0-b41e-a90b1fe727cf.png)

I have tried reinstalling ffmpeg and the recorder devices, to no avail.

**Comment by StelioKontosXBL** [comment]
Try changing this portion...
`-af silenceremove=1:0:-50dB"`
to this...
`-af silenceremove=start_periods=1:start_threshold=0.001:detection=peak`
And see if it changes anything.

**Comment by Amichh** [comment]
1. Click Start, click Control Panel, click Hardware and Sound, and then click Manage Audio Devices.
2. Click the Recording tab, click the audio device you use to record sound, and then click Properties.
3. Click the Levels tab, drag the volume slider to the right to increase the volume, and then click OK.
4. Start The Sound Recorder, and record the sound again.

**Comment by Carm01** [comment]
nothing here really works. Seeing other people elsewhere having these issues and trying their suggestions does nothing either.  maxed out input gain in control panel for mic, tried the whole vol 10000 thing, tried Ste1io argument and that does not work. You do not have the whole issue with volume of PC and speaker volume issue with a laptop so that is not the problem as the OP had.

**Comment by Carm01** [comment]
So, I opened up sound recorder, and i had the same issue. IF you have a dell, just update the audio drivers from their site from your machine. Apparently Microbrain takes it upon themselves to update realteck drivers via windows updates and some manufacturers tweak them , this resolved the issue for me.
