### ISSUE TITLE
Virtual Audio Capturer won't record Zoom speaker audio

### ISSUE THREAD

**Issue by heavydoc** [ShareX/ShareX#6631]
Hello all,

I'd like to preface, that this issue is likely not a ShareX bug, but I need assistance and I don't know where else to turn.

So in order to record audio from attendees speaking in Zoom meetings (on PC desktop), I installed Virtual Audio Capturer (and to record my own voice, I added a command line). It worked fine.
Then, I installed something called Voicemeeter. It mixes audio channels so that I could transcribe video meetings (my voice and other speakers). I didn't like it, so I uninstalled it.
But now, when I use ShareX to record a Zoom call, it doesn't record the other speakers in the meeting (It just records my own voice). 

Notes:
- If I remove the command line to record my own voice, then silence is recorded.
- ShareX Virtual Audio Capturer DOES record system audio; I played an MP3 and it recorded and played back fine. Just not people speaking in a Zoom meeting
- I tried reinstalling the Recorder Devices
- I checked the default audio devices in Control Panel. It looks fine; default speaker looks fine, and default communication device is my headset
- For video meetings, I use a headset with microphone.

**How do I fix it so I can record people speaking in Zoom meetings again?**

Any assistance would be appreciated! Thanks in advance!

**Comment by StelioKontosXBL** [comment]
Go to Task Settings -> Screen Recorder -> Screen Recording Options, and send a screenshot of the settings screen, **with the "Audio source" dropdown expanded** (exactly like the screenshot below):

![vvXjO1hhnP](https://user-images.githubusercontent.com/37424493/206354274-2e09e2ed-4534-4009-95e2-902209288955.png)

**Comment by heavydoc** [comment]
Hi! OK, so I think I have mostly solved my issue. In Audio Devices, I need to set my headset to "Default Device" (it can't just be "Default Communication Device"), and then I can record both sides of a Zoom conversation. I thought that I could just have my headset as "Default Communication Device", and my speakers be Default Device, but it won't record the other Zoom attendees if configured like that.

Is there a way so that my headset be the Default Communication Device, and my speakers be the Default Device, and still be able to record the other size of a Zoom conversation?
![ShareX_-_Screen_recording_options_15-02-16](https://user-images.githubusercontent.com/42782982/206788169-f3a7f308-c268-4ea8-b75f-dba2dff06a42.png)
(the bottom (hidden) line in the Command Line Preview is "output.mp4")

**Comment by pythonuser2020** [comment]
Hi,

I have the same issue. Can't record the screen with audio. I have added a screenshot with the settings.
Please help.

I have noticed the following in my settings;
1. Don't have the `ffmpeg.exe` file mentioned in the previous post
2. Don't have a `Install recorder devices` button
3. don't have `virtual source capture` in the drop down

![image](https://user-images.githubusercontent.com/66160270/221813542-ef68dc2a-f7a3-4874-ab14-155ffeaf9443.png)

**Comment by miladashrafi** [comment]
> Hi,
> 
> I have the same issue. Can't record the screen with audio. I have added a screenshot with the settings. Please help.
> 
> I have noticed the following in my settings;
> 
> 1. Don't have the `ffmpeg.exe` file mentioned in the previous post
> 2. Don't have a `Install recorder devices` button
> 3. don't have `virtual source capture` in the drop down
> 
> ![image](https://user-images.githubusercontent.com/66160270/221813542-ef68dc2a-f7a3-4874-ab14-155ffeaf9443.png)

I have the same issue
