### ISSUE TITLE
Option to disable magnifier in annotation screen BY DEFAULT

### ISSUE THREAD

**Issue by WiliTest** [ShareX/ShareX#6632]
Each time we edit a picture we have to disable the magnifier. Is there a way to disabling it permanently on the editor? (If not, please make one. It could "simply" remember the previous state of the last editing session).

**Comment by StelioKontosXBL** [comment]
What version of ShareX are you on? I'm unable to repro this issue; the magnifier and position/size info settings default to their last state:

![ShareX_xkkD7Eak2c](https://user-images.githubusercontent.com/37424493/206353675-0e6627df-d0e7-4901-8bde-7bb8102a088e.gif)

**Comment by WiliTest** [comment]
Thanks for your help! I'm using the 14.1 version ( Windows 10) 
Actually, I also can't reproduce it during a session (doing the same test as you do). But the magnifier was back when I tried, I'm pretty sure I disabled the magnifier the last time. I tried to reboot the PC to see if it comes back but this time it didn't.

So, I don't know. I close this and will reopen it if it happens again.

**Comment by WiliTest** [comment]
It happens again (the magnifier does not default to its last state: I keep disabling it but it comes back).

**Comment by averagecanadian** [comment]
Is there any way to set the magnifier to turned off by default? Like other users, I can disable the magnifier, but it won't' stay disabled. After a period of time, the magnifier comes back. I get that many people find this feature helpful and that's great for them, but personally, it just gets in the way for me.
