### ISSUE TITLE
14.1 Portable - Successfully stored images where upload failed are missing from History

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#6634]
1 Capture an image that successfully goes to disc but fails to upload
2 Seek it in History

Expected: present
Observed: missing e.g. the five highlighted on right, missing between the two highlighted on left:

![image](https://user-images.githubusercontent.com/6157073/206295348-0f23db6a-da18-40f9-93af-1c7c706d047c.png)

**Comment by StelioKontosXBL** [comment]
If you right-click one of the missing images in the ShareX history window, and attempt to open it from there, what happens? Also, what does it show for the filepath if you toggle the "More info" icon?

![ShareX_9oqz0vQCaK](https://user-images.githubusercontent.com/37424493/206351610-7a53e208-fb03-43a8-958d-affce479a938.png)

**Comment by chrisjj** [comment]
> If you right-click one of the missing images in the ShareX history window

I can't. Because they are missing from the ShareX History window.

**Comment by StelioKontosXBL** [comment]
My bad, I misread it initially. Are the images missing in the "Image History" screen also, or just the "History" screen?

From the main ShareX window, go to **Debug -> Debug log**, and scroll up to the the time period those missing images are from; there should be a log entry. It's possible they failed to upload to the image sharing service.

**Comment by chrisjj** [comment]
> Are the images missing in the "Image History" screen also

Yes.

> It's possible they failed to upload to the image sharing service.

It is certain - as per the report.

**Comment by StelioKontosXBL** [comment]
Failed uploads will appear in the main window's task list with an error label, but not in the history and image history screens by default, from what I've experienced. If they're not visible in the main window's task list either, most likely it's due to your application settings -> history:

![ShareX_bOWyjt63jy](https://user-images.githubusercontent.com/37424493/206594421-39bc8314-3654-431e-8a7c-d0272ed6bfc0.png)

**Comment by chrisjj** [comment]
> Failed uploads will appear in the main window's task list with an error label, but not in the history and image history screens by default, from what I've experienced.

Thanks for the confirmation of this bug.

Each capture to file needs to go in the History regardless of the upload outcome, so that the file can be copied.

**Comment by chrisjj** [comment]
Please reopen.
