### ISSUE TITLE
Show cursor in screenshots option

### ISSUE THREAD

**Issue by 358927** [ShareX/ShareX#6635]
Cursor is showing in screenshot captures despite having the option disabled

![image](https://user-images.githubusercontent.com/85761432/206306424-4ac1b9a5-5b6e-478b-b60f-fcdd29bbd4ea.png)

**Comment by StelioKontosXBL** [comment]
I'm unable to repro that behavior...see gif below. What version are you on?

![4zW6YHZhcH](https://user-images.githubusercontent.com/37424493/206350598-2c3c277b-f8e2-45c3-89b4-362859250a71.gif)

**Comment by 358927** [comment]
I am using 14.1
