### ISSUE TITLE
[Feature Request] Need MacOS and Linux Vesion

### ISSUE THREAD

**Issue by jackdeng500** [ShareX/ShareX#6639]
Could we have ShareX on MacOS and Linux?

Please paste some url if it's possible to do it myself.

Thanks.

**Comment by lawrence-laz** [comment]
Others seem to be having good results running ShareX through Wine, see [this](https://github.com/ShareX/ShareX/issues/6531).

If you don't want to use Wine (like I don't), I guess you will have to wait for a native build.

**Comment by Infinixius** [comment]
As per [https://web.archive.org/web/20201116211818/https://getsharex.com/docs/faq](https://web.archive.org/web/20201116211818/https://getsharex.com/docs/faq);

> **Will ShareX be released on [Linux](https://en.wikipedia.org/wiki/Linux) or [Mac](https://en.wikipedia.org/wiki/MacOS) operating systems?**
>
> ShareX is written using [C# programming language](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)) and [.NET Framework](https://en.wikipedia.org/wiki/.NET_Framework). At present, the .NET technologies we utilise are only supported in Windows, and it is not possible for us to make it multi platform. There is a way to make software written using [.NET Framework](https://en.wikipedia.org/wiki/.NET_Framework) to work in Linux and Mac using [Mono](https://en.wikipedia.org/wiki/Mono_(software)) but it is not possible for ShareX to run using [Mono](https://en.wikipedia.org/wiki/Mono_(software)) because of hundreds of native calls, UI, external libraries and countless unsupported methods.
> 
> Recently Microsoft released [.NET Core](https://en.wikipedia.org/wiki/.NET_Framework#.NET_Core) which supports writing multi platform software but it is currently extremely limited and doesn’t have UI or graphic related libraries. So .NET Core is currently only viable to make console only applications.

I would love a Linux version too but it unfortunately isn't worth the time or effort. Thankfully there are many community attempts to get it working:
- https://github.com/ShareX/ShareX/issues/6531
- https://github.com/ShareX/ShareX/issues/498
- https://github.com/ShareXin/ShareXin

**Comment by jackdeng500** [comment]
Thanks

**Comment by Th3-A6add0n** [comment]
https://github.com/ShareX/ShareX/issues/6110#issuecomment-1556170041
