### ISSUE TITLE
SetUp Fail

### ISSUE THREAD

**Issue by creeperparty568** [ShareX/ShareX#664]
Hello, When i attempt to install ShareX i get the following error
![image](https://cloud.githubusercontent.com/assets/12233611/7484414/44b2c07c-f356-11e4-9b5c-47c81ae34400.png)
Also, if this helps you, my computer has 763 GB of space free.

**Comment by Kesmy** [comment]
@creeperparty568 If you install to %ProgramFiles%, the installer must either ask for elevation or you have to Run as Administrator. Make sure one of those is happening.

**Comment by creeperparty568** [comment]
Okay, I will let you know if it works  when I do it




On Tue, May 5, 2015 at 5:26 PM -0700, "Kesmy" <notifications@github.com> wrote:












@creeperparty568 If you install to %ProgramFiles%, the installer must either ask for elevation or you have to Run as Administrator. Make sure one of those is happening.

**Comment by Jaex** [comment]
If your Windows not allows for setup to create directory there then can't do anything about it. But setup should be run as admin normally, did you checked is it run as admin?

**Comment by creeperparty568** [comment]
I ran it as admin and it worked. Thanks :+1:
