### ISSUE TITLE
ShareX doesn't work properly on 4K monitor

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#6642]
Hello everyone, and especially Jaex!

Now that I'm using a 4K monitor, ShareX isn't working correctly anymore. I didn't have this issue with the 1080p monitor.

### To reproduce:
* 4k monitor is required to try

### Expected result:
* Fullscreen screenshot

### Produced result:
Cropped and zoomed in screenshot
![chrome_xwrjHUi82q](https://user-images.githubusercontent.com/3248782/206953874-79496cfa-62f9-40c4-b241-a99dd1fbf855.png)

Example of a screenshot that got zoomed in (compare the screenshot and the chrome top bar) 
![chrome_u2YumlGfyC](https://user-images.githubusercontent.com/3248782/206954262-5a0094d0-cf6f-4c3b-8dc5-9e857a27082e.png)

**Comment by dmxt** [comment]
If a fellow friend has a 4K monitor, please reply if you have this issue or not. Thank you!

**Comment by dmxt** [comment]
Here's a full-screen screenshot of the desktop to prove this is not Chrome exclusive.
![eKTqZZfIhR](https://user-images.githubusercontent.com/3248782/206956973-380d4aee-47b4-423a-befe-b8add4a81260.png)

**Comment by dmxt** [comment]
I tried the dev build (v14.1.4 Dev), and it still does the same thing. It rendered the program impossible to use, and I have to find another screenshot application that works with 4K.

Jaex or the developer team, please take this issue seriously. More and more people are using 4K or even 5K monitors.

**Comment by TheRealBix** [comment]
Hi, I've had 4k monitors for a while, didn't have any issues yet... 
What are the steps to reproduce yours ?

**Comment by JHBP2** [comment]
Try capturing a small region on a 4K monitor, then try to edit that capture afterwards e.g. add a sticker.

It seems that the mouse cursor location is not detected correctly. When I should be able to edit the capture the mouse cursor appears as the window resize cursor even in the middle of the image. When trying to place a sticker or do any image editing, it does not work as ShareX thinks the mouse cursor is not in the image, but on the window border.

My work-around is to do all my captures on a smaller side monitor until a fix is released.

**Comment by dmxt** [comment]
@JHBP2 
> My work-around is to do all my captures on a smaller side monitor until a fix is released.
Are you using a dual-monitor with a smaller resolution on the side?

**Comment by dmxt** [comment]
ShareX works well with Windows' 100% scaling. Here are comparisons screenshots:

100%
![explorer_Kh148F3hxg](https://user-images.githubusercontent.com/3248782/208276328-c08d8252-5e93-404f-a332-f6474494d56a.jpg)

125%
![explorer_NPtLnRICqL](https://user-images.githubusercontent.com/3248782/208276331-596cfc6d-b3b2-47ca-9110-da5ad423e63d.jpg)

150%
![explorer_MLglJjLXg2](https://user-images.githubusercontent.com/3248782/208276332-24d6756f-69ff-4760-8177-f5b986a9dce0.png)

175%
![explorer_GAILruT8TW](https://user-images.githubusercontent.com/3248782/208276333-1d0bda5c-4e71-4553-aa02-915a64e5c3a3.png)

**Comment by dmxt** [comment]
I also noticed that ShareX only supports the maximum resolution 2194x1234px. Per Google Search, I found out that is a common problem with other programs like recording software or anything that capture the monitor.

![photo_2022-12-17_20-17-53](https://user-images.githubusercontent.com/3248782/208278229-f8c20960-a8e7-4a45-b856-82a77f6e4f13.jpg)

**Comment by dmxt** [comment]
@TheRealBix
> Hi, I've had 4k monitors for a while, didn't have any issues yet... What are the steps to reproduce yours ?
> 
> Below a default "Fullscreen" screenshot (from right-click/capture/fullscreen) ![2022-12-15_17-13-05](https://user-images.githubusercontent.com/4289656/207911271-ddcfdb46-607d-4693-9549-865a813718cc.jpg)

Thanks for bringing this up! 

* What are your Windows scaling settings? I found out that the 100% scale doesn't have this problem.
* How big is your monitor? I have 27," and everything is too tiny on 100%. When you start to scale up, the problem becomes more serious. 

![image](https://user-images.githubusercontent.com/3248782/208278414-4294e03c-5fca-4655-8a29-e4279aa6fadd.png)

**Comment by TheRealBix** [comment]
No problem.
I only use 100% scaling, on a 42".

I don't have your issues, here at 200% :
![ShareX_2022-12-18_13-54-10](https://user-images.githubusercontent.com/4289656/208299553-4adf8631-c5d5-4f93-b8c8-8125d7b8231d.jpg)

**Comment by dmxt** [comment]
> No problem. I only use 100% scaling, on a 42".
> 
> I don't have your issues, here at 200% : ![ShareX_2022-12-18_13-54-10](https://user-images.githubusercontent.com/4289656/208299553-4adf8631-c5d5-4f93-b8c8-8125d7b8231d.jpg)

Now I'm so confused... this is freshly installed ShareX what possibly have I done to recreate this problem? 
I'm really, really, really confused now.

**Comment by JHBP2** [comment]
Yes. I have two 1080p monitors either side of my 4k monitor.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dmxt** [comment]
> Yes. I have two 1080p monitors on either side of my 4k monitor. 

What happens if you disconnect another 1080p and try to make a screenshot with a singular 4k above 100% display zoom?

**Comment by vinodj** [comment]
I am getting the same issue - I will try uninstalling and reinstalling the software.
Could it be my monitor layout in Windows as shown in the attached.

Thanks,
![LmVgH7MMbQ](https://user-images.github
![59dUBVB4LX](https://user-images.githubusercontent.com/1154447/221634807-2b324ff8-028d-4471-aa8b-e86200ee7513.png)
usercontent.com/1154447/221634720-57bb3df3-481b-43cc-9788-b6b10828f9b1.png)
