### ISSUE TITLE
How to set DPI of bitmap when taking a screenshot?

### ISSUE THREAD

**Issue by Z-E-D** [ShareX/ShareX#6644]
I see a lot of reports about improper look of the program on high DPI screens. I don't have such kind of problem, or I haven't noticed it yet. However, I have an issue with the screenshots.

I have a small display with high resolution and 175% scaling in Windows 11. When I take a screenshot, the bitmap has 168 dpi and it looks big in many programs including Firefox, Edge, Opera and even the native Windows Photo Viewer. Something like this:
![2022-12-13_08-05-04](https://user-images.githubusercontent.com/97363660/207296396-c661d826-281e-4869-9bcf-d910aa779125.gif)

However, if I choose 100% scaling in Windows,  the bitmaps of screenshots will have 96 dpi and they look fine in every program, like this:
![Screenshot_20221213_114506](https://user-images.githubusercontent.com/97363660/207297691-b0051149-3391-4b07-ac13-a40763a11327.png)

So, I would like to know if there is any option in the program to set the default DPI of screenshots to 96 DPI, including animated GIFs. I tried to find it in Settings without success. Of course, I could do that after effect in any good bitmap editor, but that would be a hassle. And I am not sure if there is any bitmap editor that allows such thing with animated GIFs.

**Comment by ronvdlg** [comment]
Anyone?

**Comment by NitroFrench** [comment]
I would like to add my vote here, when working on documents, for example training guides, it is important that all screens are scaled equally, and defining DPI allows for a defautl size when pasted that does not require resizing.

This is a feature I miss a lot from previous software....
