### ISSUE TITLE
Disabling space character replacement in file names (re-submission of #4159)

### ISSUE THREAD

**Issue by traycerb** [ShareX/ShareX#6647]
This is just a re-submission (I'm not the OP) of a prior issue #4159, where the problem is illustrated nicely. Replacing spaces in filenames is very opinionated, and I'm not sure I understand the rationale either.  Can't all modern OSes handle spaces?

It looks like the fix is easy, but incorporating the option requires more thought.

**Comment by id82** [comment]
Please revisit this issue. Thank you.
