### ISSUE TITLE
Option to automatically adjust the canvas size to include newly painted stuff

### ISSUE THREAD

**Issue by kuxv** [ShareX/ShareX#6648]
Hi,

would it be possible to add an option to automatically include the painted stuff which is out of the original canvas size? It is very useful for annotations. Here is an example where I capture a small screen area and add red arrows to it:
![image](https://user-images.githubusercontent.com/3008023/208084567-10405dba-eae4-4934-8a39-d4fb8cc3b49c.png)

Currently when I copy the image I would only get:
![image](https://user-images.githubusercontent.com/3008023/208085045-b297dfb9-aa72-4660-82f2-f489be78afc0.png)

**Comment by GodSaveEarth** [comment]
I double this request. Either automatically or with a hotkey .
