### ISSUE TITLE
Unable to connect to the remote server.

### ISSUE THREAD

**Issue by Renjh5218** [ShareX/ShareX#6650]
Hi dear,I need your help,I can't download the ffmpeg.zip/exe
your friend from china.https://pbs.twimg.com/media/FkU7OJmVEAApADw?format=jpg&name=medium

**Comment by Infinixius** [comment]
Assuming it's a firewall, use a VPN if possible.

If you just need `ffmpeg.exe`, you can download it manually (from [https://ffmpeg.org/](https://ffmpeg.org/) for example), and then attach it here:
![image](https://user-images.githubusercontent.com/68125679/209836026-62a832e7-b3c0-427b-9359-5acf503821da.png)
