### ISSUE TITLE
ShareX: Unable to restore System Tray Icon after hiding Application Settings Menu

### ISSUE THREAD

**Issue by SopieMunky** [ShareX/ShareX#6652]
Hello! I use Windows 10 and normally hide System Tray icons for programs like ShareX, but one day I was messing with settings and accidentally hid the entire menu for the application settings on the left-hand side of the program.

Since I can't see the System Tray icon in Windows, and am unable to manually turn it back on in the Windows 10 Settings, I'm unable to restore the applications menu for this program. Anyone know of a way to get this back? Even if it's just restoring the System Tray Icon. Again, I've already checked the setting built into Windows 10, and have it turned on, but it doesn't change anything. 

Thanks!

**Comment by StelioKontosXBL** [comment]
Open Windows' taskbar settings, click on the innocuous little "Select which icons appear on the taskbar" link, and toggle ShareX back on again. Then enable the menu from ShareX Application settings as shown here: https://github.com/ShareX/ShareX/issues/6619#issuecomment-1335519286

![](https://i.imgur.com/4TovQ7c.png)

**Comment by SopieMunky** [comment]
Thank you for replying. 

I actually looked at this area as one of the steps. Unfortunately, the icon isn't in this list because it's disabled in ShareX. So this solution isn't working for me. Any other suggestions?

**Comment by StelioKontosXBL** [comment]
I’m not at PC at the moment, so unable to say for sure, but I would expect the settings are stored in the registry. If so, you might be able to override them by launching a new sharex instance (portable version probably best to use for his), enabling the taskbar icon , then completely exiting that sharex process. Relaunch your normal sharex install again, and see if the settings carried over. Even if they didn’t, the taskbar option in windows setting should now be there; if so, try toggling it a couple times and see if it appears in taskbar.

If you’re comfortable with regedit, you could search for sharex, and look for a key value pair storing the taskbar and/or show menu panel settings. Changing the value from 0 to 1 (or vice versa, 0 being false and 1 being true, assuming value type is DWORD) and restarting sharex would reset those settings according.

**Comment by SopieMunky** [comment]
I am comfortable with regedits when I can find what I'm looking for in exactly the path it was advertised to be in. In this [link](https://getsharex.com/docs/command-line-arguments) the ShareX program isn't in either of the suggested Parent folders mentioned. I even went through some other sub folders to see if it was possibly nested down pretty far but had no luck.

I did find some config files in the folder that houses the actual program. Lots of options to edit true/false values as you suggested show up in there, but I'm going to have to find the exact wording they use for the option in here so it will probably take me longer to locate. I'm going to try and find it in there when I get home and post my solution if it actually worked.

**Comment by StelioKontosXBL** [comment]
I stand corrected; settings are stored in a json file. Still limited to mobile until tomorrow, but the two settings you are looking for are named [“ShowMenu”](https://github.com/ShareX/ShareX/blob/26929ab31e50b3f1355df961a449172d4270132f/ShareX/ApplicationConfig.cs#L102) and [“ShowTray”](https://github.com/ShareX/ShareX/blob/26929ab31e50b3f1355df961a449172d4270132f/ShareX/ApplicationConfig.cs#L61).

Filename for config is [`ApplicationConfig-*.json`](https://github.com/ShareX/ShareX/blob/26929ab31e50b3f1355df961a449172d4270132f/ShareX/CleanupManager.cs#L49) (suffix is wildcard pattern). Containing directory is named “ShareX”, with weekly backups saved to a “Backup” directory.

https://github.com/ShareX/ShareX/blob/26929ab31e50b3f1355df961a449172d4270132f/ShareX/SettingManager.cs#L43

Both are saved at the location returned through the Win32 property `Program.PersonalFolder`, which should be the “Documents” under the user ShareX is running under. So `C:\Users\USER\Documents\ShareX\ ApplicationConfig-*.json`.

https://github.com/ShareX/ShareX/blob/26929ab31e50b3f1355df961a449172d4270132f/ShareX/SettingManager.cs#L45-L53

If no luck there, checking the “AppData\Roaming\” directory under your user is usually a safe bet.

Hope this helps…

**Comment by StelioKontosXBL** [comment]
@SopieMunky got back to PC after holidays, and double checked on config file location per my last message. Just change the values from `false` to `true`, save, and relaunch ShareX and you'll be good to go.

![Code_z1nwq8luJn](https://user-images.githubusercontent.com/37424493/210462508-f6219f31-b4ec-49c7-81ad-761083b6c849.png)

![Code_SMlWGFWCxs](https://user-images.githubusercontent.com/37424493/210462449-19ac3dcd-aa92-4942-88c0-5c67c9162477.png)

**Comment by Ste1io** [comment]
Was ShareX closed (aka, not showing in your Task Manager) when you edited/saved `ApplicationConfig.json`? I would force-close it from the Task Manager if it shows up there, edit the files once more, then relaunch ShareX. If ShareX is open when you edit the config, manually-modified settings will be overwritten by ShareX when it restarts.

After closing ShareX, editing config, and launching ShareX again, re-check the settings for Windows tray icons again (mentioned in my earlier comment) and see if ShareX appears in the list now (and that it's set to enabled).

As a last-ditch effort, you could also try setting `"FirstTimeMinimizeToTray": true,` in order to force a program interaction with the tray icon. Windows is really screwy with how tray icons are handled to begin with; it may be necessary to click the up-arrow by your icons and mouse-over all of them to prompt a redraw by Windows.

If all else fails, made a backup of your ShareX directory containing the config files, uninstall ShareX, install it again, then swap out the contents of that directory with your backup (after manually updating those two options obv).

**Comment by SopieMunky** [comment]
I ended up just deleting the program. Thanks for your help.

**Comment by lukehimself** [comment]
This is a huge failure of the product and needs to be fixed.
