### ISSUE TITLE
Have an option to turn off customized screenshots while taking a screenshot.

### ISSUE THREAD

**Issue by Sapphire-code** [ShareX/ShareX#6657]
Hi, I recently noticed that when we take a screenshot there is no button in the toolbar which turns off the custom screenshot feature. This button will be really helpful in my opinion since not all screenshots need to be custom.

if you don't have an idea of what I am talking about, then look at the image below
![image](https://user-images.githubusercontent.com/85494077/209601928-e63afe05-fcb0-4661-81ab-7f50e4a0f4f1.png)

I think turning this off manually is kind of time-wasting manually by going into the app and turning it off manually. It would really be helpful if this feature could be turned off or on again in the top menubar of the application when taking screenshots.

have a good day!

**Comment by TinyWilll** [comment]
1. Go to Hotkey Settings when you right click on the ShareX icon in the taskbar.
2. Create a new hotkey
3. Set Task to Capture Region
4. Choose a hotkey of your preference
5. Tick the Override After Capture Task
6. You can choose whatever you want, I prefer having it copy to my clipboard right after I take a screenshot. I have two hotkeys for taking screenshots, one brings me to the edit screen, one directly copies to my clipboard so I can choose which one I want.
<img width="589" alt="VBJnJhAqWM" src="https://user-images.githubusercontent.com/75234411/209773117-e80e5932-cf03-4878-b50e-ea29d7c487b8.png">

**Comment by Sapphire-code** [comment]
Ah, got it thanks!
