### ISSUE TITLE
ShareX can not auto start after win10 boot done

### ISSUE THREAD

**Issue by geekyouth** [ShareX/ShareX#6659]
![image](https://user-images.githubusercontent.com/12899262/209760265-61602f55-ba53-4e88-9d30-98fd1b61522b.png)

I have enable "windows 启动时运行 ShareX", but it does not work.

**Comment by Infinixius** [comment]
Can you screenshot the Startup section of Task manager and check if ShareX is there and enabled?
![image](https://user-images.githubusercontent.com/68125679/209835716-20944f09-0a3e-434c-8ac4-b2c1a3133474.png)

**Comment by geekyouth** [comment]
ShareX is always enabled but never auto start after win10 boot done.

![image](https://user-images.githubusercontent.com/12899262/211535541-0a1d1dcb-77c2-4aff-8658-cac09df6faed.png)
