### ISSUE TITLE
[bug report] text copied directly from discord gets shown incorrectly

### ISSUE THREAD

**Issue by cibere** [ShareX/ShareX#6670]
Hey! Sorry if this is the wrong place, I asked multiple times on the discord server to no response.

### Current Solution
pasting text in something like notepad, copy from there, then upload

### Ideal solution
being able to directly upload

# TL;DR
We found the issue was the fact that if you directly copy text from discord and use a hotkey to upload the text, the preview is all on one line but the text uploads just fine.

I tested this by editing one of my messages, and using ctrl a and ctrl c to copy it all

**Comment by PerchunPak** [comment]
Isn't it the third or the fourth step?
![image](https://user-images.githubusercontent.com/68118654/211163593-645db201-8df3-4fd0-bbf1-59cdfa8cfbd1.png)

**Comment by cibere** [comment]
sorta. without adding the copy into notepad step, it uploads all of it on 1 line and doesnt respect multiple lines

**Comment by PerchunPak** [comment]
Are you sure that this is not your destination (like pastebin) problem? For me it works with multiple lines.

**Comment by cibere** [comment]
> Are you sure that this is not your destination (like pastebin) problem? For me it works with multiple lines.

Its not the destination. When i click my hotkey, it shows me the text thats copied to my clipboard. When i directly copy from discord everything it shows is on one line. but when i paste it into notepad and copy it from there first, it shows it on multiple lines. Can you test it yourself with like 20+ lines? I remember it working with like 5> lines in the past.

**Comment by cibere** [comment]
Update: when I actually press upload it does it just fine. (I guess I've just seen the preview and just said thats not going to upload correctly)
So this is more of a bug report since the ui shows it not being uploaded correctly.

Seems like when you straight copy text manually, it works just fine. But when you go into editing the message, and `ctrl + a`, `ctrl + c` thats when it fails to render correctly.

I made a video to showcase this: https://i.cibere.dev/p2SDwh.mp4

**Comment by PerchunPak** [comment]
If we found the reason, could you please change the title and add some kind of TL;DR into the description?

**Comment by cibere** [comment]
Updated
