### ISSUE TITLE
[bug] disable historie not working

### ISSUE THREAD

**Issue by lublak** [ShareX/ShareX#6671]
Currently i use the shortcutmenu aufter capture. It creates a historie. But i disable it in the settings:

![image](https://user-images.githubusercontent.com/44057030/210750712-d300fc83-caa3-4ce7-a695-e58ee4e31c1d.png)

**Comment by ItachGal** [comment]
Hi @lublak, it doesn't reproduce in the latest version, please share more details.

**Comment by lublak** [comment]
@ItachGal I tried some more. Copying to the clipboard creates a bmp which is displayed. And there is another difference here. Actually no chronicle is displayed but only in the main window (as long as ShareX is not restarted).
