### ISSUE TITLE
Crashed after creating a gif file

### ISSUE THREAD

**Issue by EngDavidMead** [ShareX/ShareX#6673]
Hello amazing team !
I just tried to record a gif file, and It got me to stop working. Maybe the file was too long for a gif? I don't know...
Thank you for creating this amazing tool!
[crash.txt](https://github.com/ShareX/ShareX/files/10360493/crash.txt)

**Comment by ItachGal** [comment]
Hi @EngDavidMead, your assumption makes sense as the attached file shows the following error while calling imgur's api:

`{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}`

Can you retry with a smaller gif and update?

Possible duplicate:
https://github.com/ShareX/ShareX/issues/4941

**Comment by EngDavidMead** [comment]
Thank you so much for making this amazing tool, and free on top of that!
Will do! Have a great day!
