### ISSUE TITLE
[Feature Request] Fixed path images as backgrounds

### ISSUE THREAD

**Issue by AvMavs** [ShareX/ShareX#6677]
I'd like if we could have images (whose path we can specify) as backgrounds for screenshots. (Apps like Shottr do that on macOS with the wallpaper). Currently, we can not add an image layer behind the image, only overlay it.

Here's a concept I made:

![concept](https://user-images.githubusercontent.com/82929505/211531745-070e1bae-c7dc-4969-b966-0966161e52cb.png)

**Comment by yurashik1** [comment]
That's a brilliant idea. It's a function that is very much needed.

**Comment by Jaex** [comment]
It is already available in dev build:

![](https://jaex.getsharex.com/2023/08/ShareX_AI944Xj1rX.png)

**Comment by AvMavs** [comment]
You can't add it as an After Capture task, though.

**Comment by Jaex** [comment]
You can but it shows the window always.

**Comment by AvMavs** [comment]
I'm not able to figure out how I can do it? Don't see it in the After Capture menu.
