### ISSUE TITLE
Use secondary host on upload failure

### ISSUE THREAD

**Issue by EhsanKia** [ShareX/ShareX#668]
It would be great to have some sort of mechanism which automatically or semi-automatically switches to another host when the current one is giving an error.

For automatic, I'm thinking of maybe choosing a secondary host for each type (or order) to which it resorts to upon failure. For semi-automatic, maybe a popup comes asking you if you want to use another host for this time with a list of other hosts you can use.

Currently, you have to manually go and change the host, and then remember to go and change back (since these errors are usually very temporary). I don't want this feature to actually change your default host, or if it does, it should be for a short period of time.

**Comment by Jaex** [comment]
It is already exist

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/05/ShareX_bSMnyyN2K4.png)
