### ISSUE TITLE
Emoji in text box show up as boxes 

### ISSUE THREAD

**Issue by ssmethurst** [ShareX/ShareX#6686]
When entering an emoji into the "text with outline" box, the Emoji show up as boxes instead of the expected emoji images 

Video of issue 
![ShareX_cw9mtAWHT9](https://user-images.githubusercontent.com/49768603/212986065-4cf50688-1d2b-480b-a76c-ea7515643db7.gif)

Output 
![image](https://user-images.githubusercontent.com/49768603/212985113-1ef064fd-53c2-4b44-aa4f-aa0b50ed3054.png)

Version: 14.1

**Comment by funvill** [comment]
Version 15.0

The checkmark came through but the other emojis didn't for some reason 

![msedge_DiFfsa92Ko](https://user-images.githubusercontent.com/314120/214442238-3a18a06a-0683-4a18-b23c-0fbdb3e16f90.gif)

**Comment by justsomebodyhere** [comment]
Same here.
