### ISSUE TITLE
Minus Uploading only allowed for public folders

### ISSUE THREAD

**Issue by CheesecakeRecipe** [ShareX/ShareX#669]
A few days ago, I'd gotten my first upload error for Minus. I had to re-authenticate, but when I did, I was only given a list of public folders to upload to. I tried re-authenticating a few more times, refreshing the folder list, and so on. Since I use private folders, this has caused me to need to work around by opening the screenshot folder, opening the gallery in Minus, and then dragging and dropping. Thanks for taking a look into this!

**Comment by Jaex** [comment]
https://code.google.com/p/sharex/issues/detail?id=258

**Comment by CheesecakeRecipe** [comment]
That response is from 2013, I've been able to use Private folders for the entire period I've used ShareX until the other day. Surely it didn't take them almost two years to depreciate the API?

**Comment by Jaex** [comment]
If you were using private folders for entire time and if it suddenly not showing up then it is obviously to do with them.

**Comment by CheesecakeRecipe** [comment]
Indeed, their Git for the API hasn't been touched since 2011 it looks like. I'll toss their support line an  email, but they've become quite legendary for never responding.
