### ISSUE TITLE
Screen recorder: "Test with CMD" does not work

### ISSUE THREAD

**Issue by dartraiden** [ShareX/ShareX#6690]
Default settings are

`-blablabla -y "$output$"`

Starting from ShareX 15.0 ffmpeg is located in the application directory (%ProgramFiles%\ShareX). ffmpeg cannot create output file anymore due to a lack of privileges.

`output.mp4: Permission denied`

I suggest changing the default path to `"%TEMP%\$output$"`

<img width="748" alt="mstsc_tIFtvu1jYD" src="https://user-images.githubusercontent.com/5046855/213483122-9244e2aa-3f82-4445-a73c-19bb1034042a.png">

**Comment by ABCDEV666** [comment]
A
