### ISSUE TITLE
Recorder-devices-setup.exe being detected as malicious

### ISSUE THREAD

**Issue by beanp02** [ShareX/ShareX#6694]
Appears Recorder-devices-setup.exe being detected as malicious, again?

Previous issues- https://github.com/ShareX/ShareX/issues/921 & https://github.com/ShareX/ShareX/issues/4778

Being picked up by virustotal- https://www.virustotal.com/gui/file/e0292f97c764a170c41e3ac58d0df0801c59b2646dabc6304ea8353dc2c8b526/detection

**Comment by daskydasky** [comment]
CrowdStrike blocks it as well, even so, it does not appear on VirusTotal

**Comment by fjdemos** [comment]
ShareX_NativeMessagingHost is also flagged by VirusTotal

https://www.virustotal.com/gui/file/4313c3e16843fc2953d1908da2da786dea9ee965e0c0b7483060c805177117ae
