### ISSUE TITLE
Crowdstrike blocks v15 update

### ISSUE THREAD

**Issue by rbutterworth** [ShareX/ShareX#6697]
During the update to v15 there is a tmp file created which triggers a 'high' detection on the Crowdstrike plarform.

is-9OQ39.tmp (hash e0292f97c764a170c41e3ac58d0df0801c59b2646dabc6304ea8353dc2c8b526)

**Comment by rbutterworth** [comment]
Not entirely, no. I posted on Reddit and got this analysis from another helpful user

Rob Butterworth
Head of IT

Amadeus Capital Partners
Suite 1, 2nd Floor, 2 Quayside, Cambridge,  CB5 8AB

 
T: +44 1223 707035
L: https://www.linkedin.com/in/robbutterworth/  
W: https://www.amadeuscapital.com/ 


Altana secure $100M Series B investment to fund expansion of their shared source of truth on the global supply chain
(https://www.amadeuscapital.com/altana-technologies-lands-100m-series-b-to-fund-expansion/)

Amadeus Capital Partners Ltd is authorised and regulated by the Financial Conduct Authority. Registered office: Suite 1, 2nd Floor, 2 Quayside, Cambridge, CB5 8AB, UK. 
Registered in England no: 3392685. This message, together with any associated files, is confidential and only for the use of the intended addressee(s). If you are not the intended recipient, 
you must not disseminate, copy, distribute or use the information contained in this message, or any files associated with this message, as this is strictly prohibited and may be illegal. 
If you have received this message in error, please notify us at once by email to: ***@***.*** and delete it from your system. Any views or opinions expressed by an individual 
within this email are the views and opinions of that individual and do not necessarily reflect the views or opinions of the company.

 https://www.reddit.com/r/sharex/comments/10k1dz3/newest_update_1500_is_marked_as_suspicous_and/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
________________________________
From: WizardCody ***@***.***>
Sent: Tuesday, January 24, 2023 6:48:17 PM
To: ShareX/ShareX ***@***.***>
Cc: Rob Butterworth ***@***.***>; Author ***@***.***>
Subject: [External] Re: [ShareX/ShareX] Crowdstrike blocks v15 update (Issue #6697)


I'm having the same issue, any idea why it is happening?

**Comment by aliriaz-ops** [comment]
I am having the same issue; any update from the developers?
