### ISSUE TITLE
Screen Recorder only does .mp4 but no .gif

### ISSUE THREAD

**Issue by anders1122** [ShareX/ShareX#671]
I'm not sure if it should be something I have to do on my own, but I can't find any options to convert it to .gif before uploading. 
I also tried to mess with the FFmpeg settings by changing the extension with "gif" instead of "mp4" but it gave me an error window, and I wasn't too sure what to get from it. 
![](https://feen.us/6azn.png)
![](https://feen.us/2w07.png)

**Comment by Jaex** [comment]
GIF recording nothing to do with FFmpeg. You need to configure separate hotkey for GIF screen recording.

**Comment by anders1122** [comment]
Sorry but how would I do that?

**Comment by Jaex** [comment]
Add new hotkey, edit it, select Task: Screen recording (GIF).

**Comment by anders1122** [comment]
Thank you.
