### ISSUE TITLE
Request to be able to change Image Editor key binds - Especially copying image

### ISSUE THREAD

**Issue by ekhcentrics** [ShareX/ShareX#6710]
This was mentioned multiple times in https://github.com/ShareX/ShareX/issues/2984

Can we get the ability to CHANGE the keybindings for the image editor? ( https://getsharex.com/docs/keybinds)
ESPECIALLY for copying the image.

I truly don't understand why Ctrl+C copies the position and size info instead of the image itself - the position and size info seems immensly non-helpful

**Comment by tehmichael** [comment]
I second this.  I'd rather copy and paste functions work similarly to other applications (or at least have the option to change key bindings).

**Comment by znre** [comment]
Agree with this.

**Comment by warchiefmarkus** [comment]
Up, I want ability to set my own hotkey for "End capturing" or while capturing from "Enter" to other (ctrl + c)

**Comment by selaromdotnet** [comment]
adding my vote as well, would love to use ctrl c to copy the image, it gets me every time that I just end up with coordinates that I don't think would ever be of any use to me whatsoever.

thanks!

**Comment by Export33** [comment]
yes, please change copy to ctrl+c or make some of the basic keybindings configurable.

**Comment by phantasm** [comment]
seriously? it hasn't been done from the start, or yet implemented, or at least added to settings? o_O wow

**Comment by Jaex** [comment]
Duplicate of #3495
