### ISSUE TITLE
Ability to resize pin to screen

### ISSUE THREAD

**Issue by killereks** [ShareX/ShareX#6711]
Would love the ability to have the pin on stuck on the screen be resizeable, so that I can take a screenshot of the whole monitor and resize it to fit my other one.

**Comment by leumasme** [comment]
Resizing is already possible by hovering over a pinned element and scrolling up/down, but the resize step speed is rather big and not finely controllable so it might still not be possible to fit your full-screen pin exactly to a different screen.

**Comment by killereks** [comment]
Ah i see, i was thinking like u can click and drag a corner but that works, thank you!
