### ISSUE TITLE
Region Light vs Region Transparent

### ISSUE THREAD

**Issue by WeberAlex** [ShareX/ShareX#6716]
Windows 11 Pro
ShareX 15.0.0

I couldn't figure what does Region Light and Region Transparent do vs Region. Care to detail?

When I select Region Light, I lose the window elements selection, and the ability to edit a screenshot before taking it. But what purpose does it serve?

How about Region Transparent? I took the same screenshot using Region Light & Region Transparent, and I don't see any difference.

**Comment by L1Q** [comment]
Light as in light on resources for low end computers that can't even handle annotation tools very well.
Transparent is for capturing animated content, the screen is not frozen at hotkey press.

**Comment by WeberAlex** [comment]
> the screen is not frozen at hotkey press

Thank you!
