### ISSUE TITLE
Editor: Icon for "Save as..." misleading

### ISSUE THREAD

**Issue by dartrax** [ShareX/ShareX#6719]
Hi,
I think the Icon for the toolbar command "save as" is misleading. I'm used to this convention:

![image](https://user-images.githubusercontent.com/15105943/214942800-e69f7213-38f9-43e9-acbe-32184dac3a8d.png)

Unfortunately, the ShareX Editor uses the "Save All" Icon for the "Save As..." command. I noticed that every time I want to save an image I'm so confused that I need to hover the icon and wait for the tooltip in order to convince myself that this is what I want...

Please change the Icon from "Save As" button to something with just one disk and a pen.

**Comment by dartrax** [comment]
I'd like to keep this open as this is an easy fix and no one said something against it ;-)

**Comment by Jaex** [comment]
How it is easy fix? I didn't had black disk icon with pencil on it. So I used what's exists.

**Comment by dartrax** [comment]
Like this maybe?

![disk-black-pencil](https://github.com/ShareX/ShareX/assets/15105943/d6904505-0f39-4e9d-b713-2af21e668353)

**Comment by dartrax** [comment]
Would like to get some feedback about my Icon proposal ;-)
