### ISSUE TITLE
A better database management (delete or purge)

### ISSUE THREAD

**Issue by WeberAlex** [ShareX/ShareX#6724]
Windows 11 Pro
ShareX 15.0.0

In order to manager the History (& Image history) database efficiently, I would like the have possibility to select and delete the entries of screenshots in the same way that I can do it in the Task view, using the shortcut <kbd>Ctrl</kbd> + <kbd>Del</kbd>.

By example, I want to keep a record of the all uploads, and of the current screenshots, but I don't need the database to be littered with the file names of the screenshots I have long deleted. If it's not possible, maybe a purge function to remove all the empty file names.

**Comment by 0x00100100** [comment]
I agree with OP and older closed feature requests >  the app needs a way to more easily clear history and delete files while browsing the history. Use case: sometimes we take screenshots of private info such as router settings, personal info,  etc. that should not be retained for security, such as in the event of a breach, either locally or remotely.  I can limit the history size in WIndows and Linux shell but not this GUI app? Dev's could enable an app-wide password option for extra confirmation for delete history or files. Enable a feature similar to DITTO clipboard for reviewing and deleting history entries and local files. I can not fathom why these features would NOT be available in a SCREENSHOT program?!
