### ISSUE TITLE
An empty thumbnail remains in the task list when an image is captured and cancelled in Image Editor

### ISSUE THREAD

**Issue by zhuhaixiuxin** [ShareX/ShareX#6726]
An empty thumbnail named _xxx.bmp_ remains in the task list of the main windows when "**Cancel Task**" is clicked in "**Image Editor**". The empty thumbnails are totally useless and bothersome. 

This problem only happens when an image is cancelled with the option "**Open in an image editor**" ticked in "**After Capture tasks**". 

No empty thumbnail shows when a video capture is aborted.

![ShareX_jIxi0IeJbZ](https://user-images.githubusercontent.com/26450337/215261663-3176a0c3-6b84-41d9-a489-7fb8b2c397ab.png)

**Comment by geekercz** [comment]
Did you manage to solve this somehow? I can clear the task list, but I would prefer if this file would not be created in the first place, or just after open taken screenshot in an image editor, it would be deleted automatically...
