### ISSUE TITLE
File does not have the full duration of the recording, the video is cut off

### ISSUE THREAD

**Issue by pavelforever** [ShareX/ShareX#6727]
Hello, encountered a problem that the software does not record to the end. That is, I record 15 minutes, but the output in the file is say 12. On small records it is also noticeable, for example, I count 1,2,3,4,5 1,2,3,4,5 1,2,3,4,5,6 In the output the last 6 number is cut off. The longer the length of the recording, the more is cut off. Started noticing this a couple of months ago. Then updated ffmpeg codec, but didn't help. Now I was recording and it's the same again, updated the program - didn't help. Attached are the settings I'm using. Ready to provide any information on the issue
![ShareX_apBDrhM0ft](https://user-images.githubusercontent.com/9401132/215277292-c8a8b50d-7438-42cf-b067-3ca116945450.png)

**Comment by KoBeWi** [comment]
I have the same problem. I record short videos of screen region and the last few secs are cut. It seems to happen randomly (under high CPU load?). I also noticed that when this happens, starting recording with the last region will not use the correct region, making me think that the recording just doesn't finish properly and the last moments are not encoded. The program does not indicate that any error has happened though.

Using version 15.0.

**Comment by FeralFlora** [comment]
I had the same issue with WebM encoding.
