### ISSUE TITLE
[dshow @ 00000293cbc42dc0] 

### ISSUE THREAD

**Issue by y0himba** [ShareX/ShareX#6730]
Getting this error on a fresh install of Windows 10:

```
[dshow @ 00000293cbc42dc0] Could not find video device with name [screen-capture-recorder] among source devices of type video.
video=screen-capture-recorder: I/O error
```

Any help troubleshooting it would be appreciated.

**Comment by tygerxqt** [comment]
I'm also having the exact same issue, however my ID after "@" is `000001afe2963380` instead.

**Comment by tygerxqt** [comment]
I found a workaround, if you completely delete ShareX and all it’s files either manually or with Revo Uninstaller (this will delete your configuration, screenshots, and videos), you shouldn’t see the error when you try to screen record. I’m not exactly sure why it does this, maybe a failed update?
