### ISSUE TITLE
label:bug label:enhancement delayed recording start since the last new update in regional screen recorder

### ISSUE THREAD

**Issue by jpfl** [ShareX/ShareX#6738]
there is a about a 1s delayed recording start in the screen recording before the frame turns from yellow to green. Tried on two different beasts of PCs with windows 10. before it was an instant start without delayed. this is now tricky to time to not miss the beginning of short clips recorded.
Suggestion make recording start by default instantly when one clicks start or presses the hotkey combo for the 2nd time as it was before and implement a parameter to define a delay of recording in XXXXms

**Comment by eabase** [comment]
This is really a non-issue. ! second is nothing, the **ffmepg** and libraries need to have time to open, and if you have a machine with low memory and a lot of windows apps running, you need at least a few seconds.
