### ISSUE TITLE
label:Enhancement  option to define a fixed aspect ratio for regional screen recording

### ISSUE THREAD

**Issue by jpfl** [ShareX/ShareX#6739]
it would be great to have an option to define a fixed aspect ratio for regional screen recording. when defining either a height or width of a recording with the mouse there should be a check box to use e.g. 16:9 format so that the other non defined by mouse area gets adjusted for the aspect ratio to be as defined 16:9 or 4:3 etc.

**Comment by aaron-613** [comment]
Agreed!  This would be super useful.  And related to https://github.com/ShareX/ShareX/issues/4381  (static image region capture)
