### ISSUE TITLE
Upload limit prevents new windows

### ISSUE THREAD

**Issue by CWempe** [ShareX/ShareX#6741]
I noticed a strange behavior when taking multiple screenshots in a row.

There seems to be a limit to how many Task/windows ShareX can open simultaniously.
I wanted to take ~7 screenshots in a row, but the last few taken screenshots did not open.

I looked for a configurable limit in the settings and increased "Limit of simultanous uploads".
After taking the next screenshot the previous windows appeared, too.

![20230206-1710_106](https://user-images.githubusercontent.com/1270359/217024733-559d68db-e765-4917-b707-bc802f96b49c.gif)

* ShareX 15.0
* I am new to ShareX (~2 month).
  * I do not know if this as a new or old issue
* I am not uploading any images automatically.

**Comment by ashleygagregory** [comment]
I find that if you continue to take screenshots beyond the configured upload limit (default 5), closing the existing windows allows the new screenshot windows to open.
Example:

1. Take 5 screenshots, 5 ShareX windows will open
2. Continue to take screenshots, let's say 3 more screenshots (6 7 and 8) for a total of 8, no more ShareX windows will open
3. Close the ShareX windows for any 3 of the original 5 screenshots, screenshots 6 7 and 8 that didn't appear initially will now open in ShareX windows

**Comment by Andr3asB** [comment]
Finally I found this issue, as I was searching for a "flag" to create 5 screenshots in a row with 5 windows to open. -> Now I found out, I changed the max upload to "1" and this prevents multiple screenshots to open at the same time.
This functionality should 
a, be in a better place in the options menu, when it also affects the # of parallel screenshots. "Upload" seems to be kind of wrong.
b, have a better caption, so one understands what it "really" does.

**Comment by RSchwoerer** [comment]
I believe this may be a new issue as I was certain there was no image editor window limit previously.
I am not using uploading, feels like a side-effect to have the editor count linked to 'simultaneous upload limit'.

**Comment by mbalc** [comment]
yeah, the correlation is pretty unintuitive there, it should probably be separated out - or at least stated explicitly in the settings

**Comment by dylanh724** [comment]
Yep these settings should be completely separate - this had some serious hindering on my workflow and had to deep Google to find this. Even when I found it, I highly doubted it was related to "upload".

Why was this closed?

**Comment by dylanh724** [comment]
CC @Jaex
