### ISSUE TITLE
Scrolling Captures are Cut Off

### ISSUE THREAD

**Issue by TS-02** [ShareX/ShareX#6758]
Hi,

I wonder if you could help.

I've recently noticed that when I choose the **Scrolling Capture** tool and leave the 'Guess offsets and combine images' enabled, some of my screenshots are cut off completely.

![image](https://user-images.githubusercontent.com/52854743/218799845-39e43f76-43c2-4c95-9cce-8726330237b2.png)

Are there any upcoming plans to resolve this issue?

Thanks.

**Comment by Spok1** [comment]
<img src="https://i.imgur.com/0uw8hFr.jpeg">
