### ISSUE TITLE
Allow keyboard shortcuts for Greenshot-based image editor to save/close/cancel

### ISSUE THREAD

**Issue by jakebathman** [ShareX/ShareX#676]
After taking a screenshot and having it open in the Greenshot image editor, it'd be great to have some kind of keyboard shortcut(s), such as:

- ![](http://i.imgur.com/xf7jhMP.png) Save and close (`Alt + S`)
- ![](http://i.imgur.com/oFcNxJr.png) Close (`Ctrl + W`)
- ![](http://i.imgur.com/iyST784.png) Close and cancel tasks (`Ctrl + C`)

Just suggested shortcuts based on the actions that other programs use those for. I've got another suggestion about these buttons in general, but I'll file a new issue for that.

**Comment by larrye11ison** [comment]
+1
And please Please PLEASE!! Include "copy to clipboard." I use that 100% of the time when taking screenshots and editing with the GreenShot editor (I constantly have to take caps and paste into emails).

**Comment by Jaex** [comment]
It already have copy to clipboard option.

**Comment by TheCloudlessSky** [comment]
:+1:

**Comment by pawelkuras** [comment]
+1

**Comment by ArmorDarks** [comment]
What about <kbd>Enter</kbd> for 'Save and close`?

It's simple, and some similar apps using just <kbd>Enter</kbd> for applying Editor's changes and it works quite nice.

**Comment by campbeb** [comment]
@Jaex This can be closed.
