### ISSUE TITLE
How to set default settings for all users?

### ISSUE THREAD

**Issue by AlektroNik** [ShareX/ShareX#6762]
Hi. Help please.😢

Json files are created in the user folder C:\Users\<USER>\Documents\ShareX\:
ApplicationConfig.json
HotkeysConfig.json
They are created the first time the application is launched.

**How to set default settings for all computer users?**

**Comment by JoshuaMaitland** [comment]
If you set the PersonalPath string on the registry, it should set the default settings to all of the users on the computer.

**Comment by AlektroNik** [comment]
> If you set the PersonalPath string on the registry, it should set the default settings to all of the users on the computer.
> 
> This should help (https://getsharex.com/docs/command-line-arguments#personalpath-reg_sz)


I have seen this option. I'll try, but I don't think it solves my problem.
I like the default path.
If I change it, the path to all other files in this folder will change, not just the *.json settings.

I need to replace only *.json files. It does not matter in which user folder they will lie.
If you select **%HOMEDRIVE%\ShareX-all**, users will not be able to change settings.

If you select **%UserProfile%\Documents\ShareX-all** - you will have to run the **GPO policy on behalf of the user** to replace *.json files (**I want to avoid this**). And if the application is already running, then the settings will not be applied without restarting the application.
This is the same as default personal path: **%UserProfile%\Documents\ShareX**

Or does PersonalPath work differently than I described?

Maybe there is some other option?

**Comment by JoshuaMaitland** [comment]
Unless you set the full control to all of the users on the %HOMEDRIVE%, they can end up possibly delete all of the files and I don't think that's what you're after. Try placing it on the another drive letter with the ShareX folder on it.

**Comment by AlektroNik** [comment]
> Try placing it on the another drive letter with the ShareX folder on it.

Changing the personal path will not solve my problem.
The ideal option for me is during the silent installation command, with some key or command to set the default settings.
**ApplicationConfig.json
HotkeysConfig.json**
But I still can't figure out how.

Example:
ShareX-setup.exe /sp /verysilent /defaultsettings="C:\*.json"
or import backup:
ShareX-setup.exe /sp /verysilent /importbackupsettings="C:\ShareX-backup.**sxb**"

**Comment by JoshuaMaitland** [comment]
I ran out of ideas of what I can help you. Try asking on their Discord server.

**Comment by AlektroNik** [comment]
> I ran out of ideas of what I can help you. Try asking on their Discord server.

Many thanks for the help. 🤗🍻
Maybe someone else will take a look 😁

**Comment by NicoBoege** [comment]
Hi, 
I have the same issue, how was this solved?

**Comment by shodanx2** [comment]
Usually the solution to this is to have a system wide default config file in the sharex installation folder

And then each user can override the system settings with their own config file in their user folder

**Comment by TreeBranches** [comment]
This is silly. I was in the process of configuring ShareX for our org and was ready to slim down some options/make a default config, and during testing found that ShareX writes some user-based configs in the same directory - and if it's not writable it has a tantrum.

There should be a heirachy to this similar to how https://getsharex.com/docs/command-line-arguments#personal-path is configured in the first place. Or heck for simplicity instead of putting configs in a JSON lump, just make each setting a registry key so that admins can decide which settings in particular should be locked to specific configs.
