### ISSUE TITLE
Add ability to rename screenshots

### ISSUE THREAD

**Issue by Mingun** [ShareX/ShareX#6765]
When I making screenshot to attach it to Jira, I want to name it appropriately, because this name is listed in the "Attached files" in the ticket. ShareX, however, doesn't have an action to rename already taken screenshot from the main window. You should:
- or open it in the editor and save under different name
- or save screenshot under meanful name during editing screenshot just after taking

In any case the screenshot with my name is not shown in the ShareX main area with list of all screenshots. I alsogot the two identical screenshots, which is not what I want.

Please consider to change the behavior to the one that used by the excellent [Shutter](https://github.com/shutter-project/shutter) project (Linux-only, unfortunately): save with generated name, then rename.

**Comment by neiljthomson** [comment]
+1 for better renaming within the image task list window

This would include the ability to tag multiple images in the list and allow a prefix (e.g. project name) + time-sequential numbering (ideally configurable: e.g.,  (date+sequential number)

**Comment by oscaretu** [comment]
+1 for supporting renaming captured images. Another useful option would be refreshing the contents of the Image Folder. That way, the images could be renamed externally, and, at the same time, be managed from ShareX.

**Comment by BlueShanks** [comment]
Came here for these suggestions. Now considering donating
