### ISSUE TITLE
Greenshot-based image editor action buttons are duplicative

### ISSUE THREAD

**Issue by jakebathman** [ShareX/ShareX#677]
When the image editor opens after taking a screenshot, but before uploading, the three action buttons don't seem to do different enough functions to warrant their existence.

#### Issue
The `Save and close` button (![](http://i.imgur.com/xf7jhMP.png)) does what it should, saving any edits to the image and closing the image editor, proceeding with the workflow (such as uploading the image).

The `Close` button (![](http://i.imgur.com/oFcNxJr.png)) seems to do the exact same thing as the `Save and close` button, except that if annotations are made to the image, clicking the `Close` button will close the image with no prompt to save edits, and the workflow proceeds without any edits made. 

The `Close and cancel tasks` button ([](http://i.imgur.com/iyST784.png)) works exactly as expected, and I appreciate its addition to the program.

#### Recommendation
To clear up the confusion, it might just be best to have the `Close` button prompt to save changes/annotations. The user could then decide to keep changes and proceed with the workflow, or discard changes and proceed with the workflow.

**Comment by Jaex** [comment]
I won't like seeing confirmation for save each time. If I open image editor then it is obviously because I want to do changes, so it will be very annoying to see that save prompt every single time.
