### ISSUE TITLE
The ShareX mouse icon only has the option to change size in the image editor, on one of several display monitors.

### ISSUE THREAD

**Issue by ruifisilva** [ShareX/ShareX#6772]
I have pc + 3 monitors for daily use. I use Windows 10. On the monitor nº 2 of windows display, and only on this display, sharex does not work correctly. In the image editor, the mouse only has the option to adjust the window size. All the displays have the same configuration.

Monitors in windows:
![image](https://user-images.githubusercontent.com/120924221/220985944-6de61830-5439-48f4-820e-9e15a96ed39d.png)

Gif with mouse jumping from one monitor to another. On the left monitor 2, on the right monitor 4:
![ShareX_ULQZa1MVKI](https://user-images.githubusercontent.com/120924221/220985988-8ba9346f-bde6-4e36-96b0-6b007f11ef24.gif)

**Comment by mirrorcoloured** [comment]
I have been encountering this issue for years across a few machines, and finally found the right search terms to realize I'm not alone.

OS: Windows 11 Enterprise
Software: ShareX 17.0

My monitor setup is like this:

![Image](https://github.com/user-attachments/assets/fcada179-a240-4e57-9968-90a8450f02ae)

I only get this resize error on screen 3 when my cursor is aligned with the left edge of screen 1 (anywhere to the left of halfway). If I move my display layout to this:

![Image](https://github.com/user-attachments/assets/6ef0bb5d-22cc-4e2d-808e-91f16f4e68ba)

The resize error still happens starting at the left edge of display 1 (3/4 of the way across display 3).

Could this have something to do with relative coordinates being negative on displays to the left of the primary display?
