### ISSUE TITLE
Screen Recording Support for Hi-Res Screens

### ISSUE THREAD

**Issue by retohugi** [ShareX/ShareX#678]
when I try to select a browser window on Win8.1 on MacBook Pro (Bootcamp) I get the following error:

    ffmpeg version N-72058-g3ecc063 Copyright (c) 2000-2015 the FFmpeg developers
      built with gcc 4.9.2 (GCC)
      configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
      libavutil      54. 23.101 / 54. 23.101
      libavcodec     56. 38.100 / 56. 38.100
      libavformat    56. 33.100 / 56. 33.100
      libavdevice    56.  4.100 / 56.  4.100
      libavfilter     5. 16.101 /  5. 16.101
      libswscale      3.  1.101 /  3.  1.101
      libswresample   1.  1.100 /  1.  1.100
      libpostproc    53.  3.100 / 53.  3.100
    [gdigrab @ 00000000047c84a0] Capture area (699,11),(2833,1577) extends outside window area (0,0),(4560,1200)desktop: Input/output error

Any way to work around this issue?

Thanks in advance,
- reto

**Comment by Jaex** [comment]
Select other video source in FFmpeg settings instead GDI grab.

**Comment by Jaex** [comment]
#923
