### ISSUE TITLE
Uploading Animated GIF

### ISSUE THREAD

**Issue by jdcollier1968** [ShareX/ShareX#6797]
When uploading an animated animated GIF to IMGUR it loses it's animation qualities and becomes a still image. Anyone know why?

**Comment by ryehamstrawberry** [comment]
Does ShareX upload work for you even for still images?

I've been receiving an error that seems to indicate their API has changed and is not currently working with the latest version of ShareX.
https://github.com/ShareX/ShareX/issues/6794

I'm curious if your issue is related.

**Comment by jdcollier1968** [comment]
Uploading still images to IMGUR works fine just doesn't seem to handle animated GIFs.

**Comment by ryehamstrawberry** [comment]
I should have specified, have you configured personal Imgur account credentials within ShareX or are you using the "anonymous" user upload account?

As I mentioned in my previous reply, I'm trying to confirm whether the issue is with ShareX not since image upload seems to no longer with with the anonymous Imgur upload option:
```
Error message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

Request URL:
https://api.imgur.com/3/upload
...
```

**Comment by jdcollier1968** [comment]
User.

![image](https://user-images.githubusercontent.com/42359733/223913735-ebc4b7e8-798e-4e54-8636-d45384c998ae.png)

**Comment by ryehamstrawberry** [comment]
Would you mind confirm/denying that anonymous account type fails to upload for you too, just so I can reference your experience in the other bug report?

**Comment by jdcollier1968** [comment]
It seems to upload fine as anon as well. What version are you running?

**Comment by ryehamstrawberry** [comment]
> It seems to upload fine anon as well. What version are you running?

Latest portable release v15.0, you?

**Comment by jdcollier1968** [comment]
Yes 15.0 as well. So you can't upload anything to IMGUR as a user or anon?

**Comment by ryehamstrawberry** [comment]
> Yes 15.0 as well. So you can't upload anything to IMGUR as a user or anon?

After reading your confirmation that upload works for you I determined the issue must be local.
For whatever reason uploads are no longer behaving nicely with my VPN but when disabled uploads are successful.
I've never had an issue with ShareX uploads not working behind VPN but apparently that's no longer the case.
I need to continue troubleshooting this if anyone has any suggestions.

Thank you for your replies, you've been helpful.

**Comment by jdcollier1968** [comment]
you bet

**Comment by jdcollier1968** [comment]
You may already know this but were you aware GIFS will stop working if you resize outside of their native rez?

**Comment by jdcollier1968** [comment]
Actually what I just learned (and maybe it's a setting and I don't know where it is) when I upload an animated GIF upon upload it is converted to a still PNG. How about them apples?

**Comment by ryehamstrawberry** [comment]
Does enabling .gifv extension produce the same still image result?

What about uploading to another file host?

**Comment by jdcollier1968** [comment]
Did not seem to make a difference either way.
