### ISSUE TITLE
Cannot Upload to S3

### ISSUE THREAD

**Issue by xnaas** [ShareX/ShareX#680]
Ever since Amazon switched how their authentication worked a couple of days ago, I am no longer able to upload to my S3 bucket. Every time it's a 403 forbidden error. All keys are 100% correct. No other hosting sites have this issue, only AWS S3.

**Comment by Jaex** [comment]
@alanedwardes was updated S3 to new authentication, would you like to try new version?

**Comment by xnaas** [comment]
Me? I'll try anything to get my S3 uploads working again.

**Comment by Jaex** [comment]
Try this then: https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/05/ShareX-9.10.0-setup.exe

**Comment by xnaas** [comment]
This is the error I get now when trying to upload to my S3; http://i.imgur.com/njY2E2X.png

Updated the settings too to make sure nothing was inaccurate or wrong.

**Comment by Jaex** [comment]
Because I don't have S3 account I can't test it :(

**Comment by xnaas** [comment]
I can set you up with an access code for one of my buckets if you need. My email should be on my github account. If not, just contact me in any way you'd like: http://xnaas.us/

I'd like to note this happens on both my home desktop and my work laptop on various networks. No one else I talk to has run into this issue yet.

**Comment by alanedwardes** [comment]
Hi - I am unable to recreate this issue. Could you take a screenshot of your Amazon S3 settings page for us? Feel free to blank out your access key. Thanks!

**Comment by xnaas** [comment]
This is a screenshot using the new 9.10.0 file that @Jaex sent to me: http://i.imgur.com/hfLU82M.png

This is the same exact settings I have always used. The keys are not the issue as old and new ones were working until...Monday? The only thing that has changed are the authentication policies on Amazon's side. As said above, no one else has experienced this issue, so I'm unsure what the problem could be.

**Comment by Jaex** [comment]
Can you try this: https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/05/ShareX-9.10.0-setup.exe

It is supposed to give better error report.

**Comment by xnaas** [comment]
That's what I'm already using. Unless the file has been updated in dropbox.

**Comment by alanedwardes** [comment]
It has, I added more verbose errors for the S3 uploader: https://github.com/ShareX/ShareX/pull/682

**Comment by alanedwardes** [comment]
Please post a screenshot of the error when uploading to S3 from the new build, it should provide an HTTP status code which will be useful with debugging this.

**Comment by xnaas** [comment]
Trying the latest ShareX you've shared with me, it's back to giving me 403 forbidden errors, even when creating a new access key and making sure it's 100% accurate. http://i.imgur.com/4bmNl9c.png I know that's not incredibly helpful, sorry.

**Comment by alanedwardes** [comment]
This means there is problem with your access key or secret key. Please ensure that you are able to upload objects to S3 using these keys and another program, such as S3 Browser: http://s3browser.com/

Please also ensure you are not accidentally adding whitespace around your credentials.

**Comment by xnaas** [comment]
I finally got it figured out. For some reason a policy had detached itself in the IAM management for AWS and completely fucked up everything. S3 Browser tipped me off. Thank you. Feel free to close issue.
