### ISSUE TITLE
[Feature Request] Add keyboard shortcut for OCR

### ISSUE THREAD

**Issue by ertankucukoglu** [ShareX/ShareX#6801]
Hello,

For people addicted to shortcuts, please.

Thanks & Regards,
Ertan

**Comment by artjomsR** [comment]
@ertankucukoglu I agree it would be nice specific shortcuts which would make the option more customisable. This is the workaround I've found for now (use capture as an action and OCR afterwards) + some useful settings I've found as well
![image](https://user-images.githubusercontent.com/6875790/226756504-5af1ec00-f8eb-4708-bb38-9c5c4b23ba98.png)

![image](https://user-images.githubusercontent.com/6875790/226756835-67ea3714-48bd-468d-9680-4180c4dc86f9.png)
![image](https://user-images.githubusercontent.com/6875790/226756944-bcd5eade-77ab-4c3b-a28a-f81c52ed488c.png)
