### ISSUE TITLE
ShareX keeps crashing on Windows 11

### ISSUE THREAD

**Issue by mccnash** [ShareX/ShareX#6802]
ShareX keeps crashing without warning or notification. When I try to use it again, i cant because the app crashed at some point. there is no notification about it or anything. The icon is still visible when I click on show hidden icons, but as soon as I hover the icon it disappears and i have to start the app again.
This has happened numerous times now. Its super annoying and frustrating. I loved the app until it started to behave like this. It seems to still run fine on my Windows 10 pc.

I also hate that I need a GitHub account to report issues. I am not a developer and what should I do with a GitHub account? How about email? I probably wont even realize any responses here. 
Leave GitHub to developers and people active in the community or make it so i dont have yet another account i will never use in my life again. Sorry, but that's just my 2 cents.

**Comment by MJHeijster** [comment]
As a user of ShareX stumbling upon this issue and as a developer.. I have 0 crashes on Windows 11. I understand the frustration, on the other hand this is a free program. I don't think it's an OS issue, I think it's something on the system itself.

In regards to creating a Github account, as a developer you want to have a single point of registration for issues. It has nothing to do with the end-user being a developer, it's just to keep everything in one ecosystem. Having email as a reporting system is really inefficient. Github has a search function for issues, so if there are 10 issues stating the same, the user can find it and say "hey, me too!" or issues can be closed as duplicates, where email has to be manually parse by the receiver.

While I cannot help you with this issue, that is my 2 cents.

**Comment by mccnash** [comment]
Hi,

what could it be? It was running for a long time on windows 11. It must have been one of the updates. I use the program almost daily but i can't make the connection when it happened. Any way to troubleshoot this, because it's super annoying that it crashes all the time.

**Comment by MJHeijster** [comment]
I hope they will notice this issue, else, if you have Discord, you can join that platform to see if the people there know what's going on. ShareX has logging, so maybe that sheds some light on it.

**Comment by mccnash** [comment]
Oh i dont have discord. I have huge issues with discord and their support...i uninstalled and i am done with it. thats exactly what i mean, why cant we stay on a neutral platform.. sing up here and there and there as well. 
There is way to manage email bug reporting...
I know how many accounts I had to create over the year, I used once and never again. which is just such a waste of global resources. 

anyway, lets see what can be done to fix the crashing issue...

**Comment by FLAIR7** [comment]
What are your System specs?

**Comment by mccnash** [comment]
Way above whats required.
32GB Ram
2TB Storage
WIndows 11
Dedicated Graphics
11th Gen Intel

ShareX works fine on my 6 year old Win10 Laptop with no issues. ONly on
this new one it runs and I dont know when, it just disappears out of the
task bar. I dont know if Windows is closing it or if it just silently
crashes. Is there a way to stop windows from closing it?

**Comment by mccnash** [comment]
Too bad that there is no support here. It's sad once again, that people have to sign up for accounts and dont get anything out of it. 
Either way, I know that the problem now is how you install sharex. If you install it from the microsoft store, you are screwed, install it as a regular piece of software and you are good to go if it comes to shutting the app down. Now, I have a whole ohter problem. When I try to take a screenshot, sharex enlarges the whole screen and I never can take a screenshot of the full screen, as it is enlarged now and only the visible part I can see of the elnarged screen get screenshoted. It didnt used to do that before. Lets see if I can get help on that...

**Comment by Aokromes** [comment]
works for me with windows 11 insider build 25xxx, the only problem is that now snipping tool takes print screen key so different shortcut or edit registry is needed.

**Comment by mccnash** [comment]
anyone still working on this issue? i guess not!
