### ISSUE TITLE
Question: Edit image before capture

### ISSUE THREAD

**Issue by Hutch79** [ShareX/ShareX#6804]
Heya

I'm currently trying to move from alternatives like Lightshot or Flameshot to ShareX and stumbled over a slight problem with my workflow.

The old tools I was using were working as following:
1. Mark the area you want to capture
2. Make edits to your image like adding arrows and boxes
3. resize your selection and redo No. 2 if you like

Unfortunately, I have found no option to enable this workflow in ShareX.
Here it works by editing the Image and then select the area and instantly create a screenshot without the possibility to precisely crop the image to the area needed.

Now my question is:
Is there a way to change this behaviour?

**Comment by qlaall** [comment]
I hava the same question

**Comment by prashanth1k** [comment]
I do something similar, but yes, the images are already created/saved in the background.

Right-click on the ShareX icon to view options and ensure "After Capture Tasks > Open in Image Editor" is selected - 
![image](https://github.com/ShareX/ShareX/assets/6079634/19289276-753e-4448-b870-828bd5d230bc)

1. Hit PrintScr or Ctrl + PrintScr to capture the screenshot 
1. Make changes on the editor
2. Save

[Temporarily available at https://ibb.co/26mC12X](https://ibb.co/26mC12X)

**Comment by crash5** [comment]
I'm using the same worklfow, enable the multiple region selection under the application options/reginal capture (checkbox at the top). Then you have to hint enter when you finished and want to continue with the capture/save/etc. steps.
