### ISSUE TITLE
Sign ShareX Installer

### ISSUE THREAD

**Issue by destiny14** [ShareX/ShareX#6807]
Hello!

For use in some more locked-down environments (and for good practice) the installer should be digitally signed. This is especially important for the auto-updater.

Thanks for your great work!

**Comment by SephirothWS** [comment]
@destiny14 Code signing is expensive. Do you plan on contributing the funding necessary for such a task?

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage

They average ~$250 to $500 USD per year.

**Comment by destiny14** [comment]
There is one more affordable offering from [certum.com](https://shop.certum.eu/open-source-code-signing.html), but yeah I hoped there would be some more discounted offers for open source projects, sorry.

**Comment by DRSchlaubi** [comment]
cerium does in fact provide discounts, so open source projects only need to pay 50$, However, integrating certum into a CI/CD is pretty much impossible afaik.

However, e.g. Notepad++ got a certificate sponsored from Digicert, considering the popularity of ShareX some CA might be willing to do so as well for ShareX

**Comment by DRSchlaubi** [comment]
After I looked through past issues I saw that apparently some digicert rep commented and @Jaex contacted them and never heard back.

If you are still interested in this I would suggest applying at https://signpath.org/, which sponsors a lot of open source projects, like the windows version of vim, but even for my very small one, which is way smaller than sharex, so it's very likely for sharex to be accepted.

You also don't have to worry about the certificate name, as it will read "Sign path foundation" so no need to worry about your real name
It also easily integrates with GitHub actions , which sharex uses already, the only caveat is that you need to manually confirm every release
