### ISSUE TITLE
Could you please update Readme and website documentation mentioning it is for Windows OS only

### ISSUE THREAD

**Issue by tsundara** [ShareX/ShareX#6813]
Mac user here. I assumed this might be a multi-platform tool and downloaded the portable zip. On unzipping i saw exe/dll files and figured it is only for Windows. 

Could you please explicitly mention this is only for Windows in the readme & website so that Mac/Linux users can skip the download.

**Comment by teauxfu** [comment]
This is a WinForms app, so xplat seem unlikely for the foreseeable future. Maybe when MAUI is more fleshed out this could be ported to that, or perhaps even Avalonia. Either way it would be a major refactoring effort that I'm not sure anyone wants to take on. As far as WinForms apps goes, this is hands down one of the most beautiful ones I've used. 

At any rate, I'd agree some more specific mention of Windows on the docs/website would be helpful.

**Comment by intel352** [comment]
Agreed, please update website to indicate this is Windows-only. Lack of clarity is a time waste.
