### ISSUE TITLE
Security concerns : acropcalypse and sharex

### ISSUE THREAD

**Issue by MikeZeDev** [ShareX/ShareX#6816]
Regarding the recent security issues with pixel phones and windows [snipping ](https://twitter.com/David3141593/status/1638222624084951040?s=20 )tool letting data in pictures after cropping that can be recovered, i am wondering if my favorite snapshot tool is affected.

Thanks for ShareX <3

**Comment by ElijahPepe** [comment]
I'll have to do a more thorough review later, but there appears to be a substantial difference in size between full monitor screenshots and region screenshots, suggesting that ShareX isn't susceptible to aCropalypse.

**Comment by yllekz** [comment]
Does cropping it after capture (aka via the image editor) have any cause for concern?

**Comment by ElijahPepe** [comment]
The file size also changes when cropping an image using the image editor. Again, unlikely ShareX is susceptible to aCropalypse.

**Comment by d-Rickyy-b** [comment]
As @ElijahPepe has already pointed out, the file size changes.
Additionally to that, I was not able to find data after the IEND chunk.
And most importantly, ShareX uses `FileMode.Create` ([Docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.filemode?view=net-7.0)) to write to files. Microsoft says:

> FileMode.Create is equivalent to requesting that if the file does not exist, use [CreateNew](https://learn.microsoft.com/en-us/dotnet/api/system.io.filemode?view=net-7.0#system-io-filemode-createnew); otherwise, use [Truncate](https://learn.microsoft.com/en-us/dotnet/api/system.io.filemode?view=net-7.0#system-io-filemode-truncate).

The only place where Append is being used is to write history data. I couldn't find any clues that ShareX is susceptible to the acropalypse weakness.
