### ISSUE TITLE
in ChatGPT

### ISSUE THREAD

**Issue by KamiyaMinoru** [ShareX/ShareX#6824]
![image](https://user-images.githubusercontent.com/78710607/228495472-f1997062-a77b-4b19-8475-d1a92bf2599e.png)

Hi,

I am problem in taking screenshot on chatgpt, as you can see the picture; 
Could you give me some advice, or I can expect next version of ShareX?

Thanks.

**Comment by WavingCatDevs** [comment]
![z2NUvJi6](https://user-images.githubusercontent.com/69034430/228902624-4319240e-6343-4476-a6ff-6198c3dee8d2.png)

I cannot reproduce this issue.

**Comment by KamiyaMinoru** [comment]
> ![z2NUvJi6](https://user-images.githubusercontent.com/69034430/228902624-4319240e-6343-4476-a6ff-6198c3dee8d2.png)
> 
> I cannot reproduce this issue.

Seems your diaogue is not long enough. Run more pages and see._

**Comment by BromTeque** [comment]
I'm on 15.0.1.121 Dev and can confirm scrolling capture on https://chat.openai.com/chat/ in Firefox does not work.

It scrolls, but only the first image is presented when you get the option to save. Tried both regional and whole screen.

**Comment by BromTeque** [comment]
@Jaex Thanks! Made it work. I accidentally kept including the "Regenerate response" sticky.

Is the "Don't include sticky elements" limitation communicated well to the end user at some point, or am I just that dumb?

**Comment by KamiyaMinoru** [comment]
![image](https://user-images.githubusercontent.com/78710607/231787326-e4abb0ee-d95c-4840-b3be-685d928dcdca.png)


Unable to install; error msg when clicking install Dev

**Comment by randomguyingithub** [comment]
> ![image](https://user-images.githubusercontent.com/78710607/231787326-e4abb0ee-d95c-4840-b3be-685d928dcdca.png)
> 
> Unable to install; error msg when clicking install Dev

Try updating your main shareX before attempting to install dev version
