### ISSUE TITLE
Image History - Pin to screen does not work when Image History windows is not on the main display

### ISSUE THREAD

**Issue by tolgabalci** [ShareX/ShareX#6831]
I have a hotkey assigned to the image history window.  If the mouse is on a secondary screen when the hotkey is invoked the image history window is smart enough to open on that secondary screen, however, when Pin to screen (Ctrl+P) is chosen when the image history window is not on the primary display nothing happens (image is not pinned).

It would be nice if the image is Pinned to the secondary screen in this case, but at the very least it should pin to the primary/main display.

**Comment by Jaex** [comment]
Did you test [dev build](https://getsharex.com/docs/dev-builds)?

**Comment by tolgabalci** [comment]
dev build fixes it by having the pinned image appear on the same screen as the Image History window!  awesome. thanks!
