### ISSUE TITLE
Can we change the number of a Step?

### ISSUE THREAD

**Issue by m33ts4k0z** [ShareX/ShareX#6835]
Hello.

I started using ShareX a couple of weeks ago and I absolutely love it. I wonder about one thing. When using the built in editor we can have bubbles with numbers. It's called steps in the editor. I need to create multiple screenshots and continue the numbering on every screenshot instead of start over from 1-2-3 etc. Can I change the number mnaually? I couldn't find that anywhere. Thanks for this great tool.

**Comment by merubin42** [comment]
Tool Options > Value of first step:
![image](https://user-images.githubusercontent.com/131308473/233202805-082bc9b6-3a19-4cae-9c55-c3aa4808305a.png)
