### ISSUE TITLE
[Feature Request] Add in Editor Image Rounding Rectangle

### ISSUE THREAD

**Issue by maisondasilva** [ShareX/ShareX#6837]
It would be great to see the option in addition to rectangle the option of rounding rectangle

Thanks

**Comment by merubin42** [comment]
Tool Options > Corner radius: adjusts the rounding
![image](https://user-images.githubusercontent.com/131308473/233202573-899d5f08-dcc5-460c-9dde-813fe0f613cd.png)

**Comment by maisondasilva** [comment]
Thanks for the tip @merubin42
