### ISSUE TITLE
Could not create directory error

### ISSUE THREAD

**Issue by pratyakshm** [ShareX/ShareX#6844]
The exception is related to access denied issues. But I am not sure why those are happening, Ideally, they shouldn't happen since this is a release from Microsoft Store.

<details><summary>Tap for screenshots</summary>

![image](https://user-images.githubusercontent.com/54220235/232100833-5a7c7048-462f-4847-9ccb-245c9b42adce.png)

![image](https://user-images.githubusercontent.com/54220235/232100847-4c971fac-6d8e-498b-afb3-5d3d0c3c3922.png)

![image](https://user-images.githubusercontent.com/54220235/232100861-6591150a-d88a-4f29-a1ec-e2fdb5654318.png)

![image](https://user-images.githubusercontent.com/54220235/232100869-07d11b81-46d3-496b-baae-36cd283dbdb3.png)
</details>

**Comment by Bie-NHD** [comment]
Hi i'm having the same issue. Wondering have you been able to solve it? What is your OS?

**Comment by Bie-NHD** [comment]
Oh hey, i just tried to uninstall ShareX and running the installer (downloaded from the official website) as admin and it works
