### ISSUE TITLE
UX on dark theme

### ISSUE THREAD

**Issue by SullyPanda76cl** [ShareX/ShareX#6850]
Hello, on dark theme, some controls' colour, may be improved to give better UX.

Example 1: disabled buttons text colour is black, over dark background
Example 2: Section names, are blue, which renders it difficult to read over dark background.

![ufknXK27QB](https://user-images.githubusercontent.com/44233071/232617937-5fc53829-f9c5-4ba7-bc81-49a7a70ea07f.png)

Tried to find the theme definition, but didn't succeed at it

**Comment by SullyPanda76cl** [comment]
Ok, my mistake.
They are black because [enabled]=false

Anyway, perhaps the themes color could be improved.

**Comment by mbloflin** [comment]
I have similar issues.. I have in places black text on black background like this Task Settings screen:
![ShareX_3CzBWQnvRl](https://github.com/ShareX/ShareX/assets/69241662/fdd16179-ab22-465a-92b9-303641ce6cad)
