### ISSUE TITLE
Paste Base64 image into Image Editor

### ISSUE THREAD

**Issue by gnijs** [ShareX/ShareX#6852]
Since these days we work a lot with Teams and Teams only allows to copy images in base64 format, it would be nice if the ShareX Image Editor "Load image from clipboard" function would allow us to load the Base64 encoded image into the editor.

**Comment by micahmo** [comment]
In case anyone stumbles upon this in the future, it seems like Teams is actually putting the image in the clipboard these days, so this issue isn't nearly as important!
