### ISSUE TITLE
Arrow keys cannot be used for control

### ISSUE THREAD

**Issue by shuojie819** [ShareX/ShareX#6854]
When drawing, First draw, a single node can be controlled using arrow keys.When you're done, you can only control the entire rectangle.

![ShareX-1](https://user-images.githubusercontent.com/72399630/232968702-fa4e4c82-3ba2-4ebe-b011-515cacb7708d.gif)

😊Excuse me for my poor English.

**Comment by Jaex** [comment]
Check: https://getsharex.com/docs/keybinds

**Comment by shuojie819** [comment]
> Check: https://getsharex.com/docs/keybinds

`Arrow keys`："Move cursor / Move current shape"

The shortcut keys are fine, Only when drawing a graph for the first time, you can use the arrow keys move the cursor.    and then you want to adjust it, Hold left click + arrow keys,Unable to adjust the cursor.
