### ISSUE TITLE
A question about OCR language

### ISSUE THREAD

**Issue by ANGENANA** [ShareX/ShareX#6855]
I don’t have the choice “Chinese (Simplified）”below the setting of “OCR language “.But the choices of Russia,Japanese,Chinese “traditional “are there.
Please help me!🥺

**Comment by ANGENANA** [comment]
The problem is solved. I left a message in the Microsoft community and found a way to uninstall and reinstall Chinese Simplified comes with OCR, which is done using Powershell. Screenshots and text descriptions of the solutions given by Microsoft community moderators I post below. Hope to help people who have the same problem as me. That is, after installing the 'optical character recognition' that comes with a Windows language, but does not appear in the list of OCR functions in ShareX.
If you encounter this issue, you can try using this link to uninstall and reinstall the 'Optical Character Recognition' add-on that comes with the language.
link：https://learn.microsoft.com/zh-cn/windows/powertoys/text-extractor
This is the link address where I asked the question in the Microsoft Community：https://answers.microsoft.com/zh-hans/windows/forum/all/win10%E7%B3%BB%E7%BB%9F%E7%AE%80%E4%BD%93%E4%B8%AD/a9a4f5fb-c1c0-47ac-8b9b-5fced89fb2b1?tm=1682081897265

**Comment by hhhggr** [comment]
Thank you! it dose work!!!

**Comment by springdev25** [comment]
Thank you, I faced the same problem and now it’s solved.
