### ISSUE TITLE
[Bug] URL with certain characters being detected as a text job instead of a URL shorten job

### ISSUE THREAD

**Issue by Drakonas** [ShareX/ShareX#686]
Attempting to shorten [this link](https://r6---sn-5uaeznzk.googlevideo.com/videoplayback?requiressl=yes&ip=you.no.can.haz&ms=au&nh=IgpwcjAxLmF0bDIyKgkxMjcuMC4wLjE&mv=m&source=youtube&pl=17&mime=video%2Fmp4&id=o-ANb6c7tjPZxdE49ArdSWgQBaf7bXAVMSmWgps63lWu_b&mm=31&ipbits=0&mt=1431742844&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=22&sver=3&expire=1431764506&key=yt5&fexp=9406813%2C9407664%2C9408078%2C9408142%2C9408385%2C9408705%2C9408710%2C9410706%2C9413132%2C9413525%2C945137%2C948124%2C952612%2C952637%2C952642&ratebypass=yes&dur=307.432&upn=nWt_-D8It6w&signature=C8F911F90C5E7A1732427D3E0A8FB0454C2AE704.2EAEA79A320A28E7B29252E87FEE7D70868B7AF2&initcwndbps=1663750&signature=) results in ShareX detecting it as a text job and not a URL.

I'm sure ShareX filters out non-URLs with certain characters that it believes not to be valid for URLs, however it must be filtering out something incorrectly.

Other URLs I try are detected as URL shortening jobs correctly, but this one does not. Btw, don't ask what kind of link this is... lol. It does work on my end when the correct IP address is provided. You shouldn't have to have a legit working URL to verify this bug though.

**Comment by Jaex** [comment]
ShareX using complicated regex to check is it URL therefore I don't think I can fix it:
https://github.com/ShareX/ShareX/blob/master/ShareX.HelpersLib/Helpers/URLHelpers.cs#L173

I mean I know regex but while fixing it don't wanna break something unintentionally.

**Comment by Kesmy** [comment]
@Jaex The original regex changed after it was pulled into ShareX.  The new regex just needs to be pulled in from https://gist.github.com/dperini/729294

BUT, the licence also changed, so I don't want to make that commit as it will pull in a new licence.
