### ISSUE TITLE
Cannot find any way to auto-save my screenshot

### ISSUE THREAD

**Issue by rsidon** [ShareX/ShareX#6861]
My ShareX has 2 "After capture tasks" specified:
- Open in image editor
- Save image to file

Consider the following super simple scenario:
1) I take a screenshot
2) Image editor is auto-opened.
I draw a lot of things around my new screenshot
3) Suddenly I forget to Save and hit Alt+F4
4) My window is closed, w/o any warning, I lost all my changes.
5) I open shareX and search my screenshot, it is nowhere to be found.
If I go through the same flow, and remember to use Ctrl+S, the file is saved and its name appearts in the window title.

So my question is:
- What is the benefit that I can get from the "Save image to file" configuration? Am I missing something? Does it work as expected ?
- Is there any other way to configure autosave?

Just to update, in my workplace I use A licensed copy of Techsmith SnagIt.
- In their application everthing is saved 
- They have an editor in a single app window, you don't have to search and open separately your past screen captuers. And you can continue with your changes and resave  any of your screenshot at once.
Since I am new to ShareX, Maybe I am not familiar enough with all its features. Is there any similar editor for ShareX? If not, is any such "multi-editor" planned? it can be very convinient for the users community.

Thanks,

**Comment by DasDunkel** [comment]
After capture tasks are ran in the order they are listed, if the edits made to the image aren't "confirmed", such as <kbd>Ctrl</kbd>+<kbd>S</kbd> or <kbd>Enter</kbd>, then the workflow is cancelled stopping any further tasks, like uploading and saving. There is currently no way to change this behavior.

I'd recommend making a feature request to add a confirmation box to exit without saving changes.

**Comment by rsidon** [comment]
You are correct.
I'll add it as a feature request.

However, even more basically, if NO edits were done to the image, I.E it is currently as it is when it was captured, it is not saved anywhere. I'd expect them to allow a configured behavior for saving every image upon captured to a folder.

**Comment by tigrom** [comment]
this feature is missing so badly. Any news?
It's like better safe, than sorry, I personally like to have the screenshots saved automatically. So I know for sure something is not missed.

**Comment by btTeddy** [comment]
Any update on this a year later?

Auto Save screenshot is the most basic functionality that's still missing.

It's very strange being able to upload ss but not save it localy
