### ISSUE TITLE
Win+G as ShareX hotkey

### ISSUE THREAD

**Issue by xmha97** [ShareX/ShareX#6862]
Hi,
I disabled all system Winkey hotkey using the registry:
```ini
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"NoWinKeys"=dword:00000001
```
Now I can't use Win+G !!!
![image](https://user-images.githubusercontent.com/23485114/233871329-f721cf18-7df1-4826-ba8d-10765facf7ae.png)
Please help me to bypass this limitation from Windows.

**Comment by xmha97** [comment]
> disable game bar, it is not a system application
> https://superuser.com/a/987218

I uninstalled the gamebar but still can't use its hotkey.

**Comment by Exilon24** [comment]
@Scrxtchy How exactly did you get that error to pop up? I can't seem to find it.

This is the only thing that happens when I set `Win + G` as the hotkey:
![image](https://user-images.githubusercontent.com/80382462/235256671-f8b24e66-963f-4aaf-b2b5-da3cef24ac86.png)

**Comment by DasDunkel** [comment]
Are you using Windows 10 Home? [According to the docs](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-windowsexplorer#nowindowshotkeys) NoWinKeys isn't available on Windows 10 Home.

**Comment by xmha97** [comment]
> Are you using Windows 10 Home? [According to the docs](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-windowsexplorer#nowindowshotkeys) NoWinKeys isn't available on Windows 10 Home.

I'm using Windows 11.

**Comment by xmha97** [comment]
It's Enterprise.
