### ISSUE TITLE
Problem with uploading images to FileZilla Server

### ISSUE THREAD

**Issue by Sickness-chan** [ShareX/ShareX#687]
I think it broke with the latest version, no changes were made in FileZilla or ShareX.
ShareX Version: **9.9**
FileZilla Server Version: **0.9.51 beta** & **0.9.49 beta**

ShareX error:
> System.IO.IOException: The connection was terminated before a greeting could be read.
  > at System.Net.FtpClient.FtpClient.Connect()
  > at ShareX.UploadersLib.FileUploaders.FTP.Connect()
  > at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
  > at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
  > at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
  > at ShareX.UploadTask.DoUpload(Int32 retry)

FileZilla error:
> (000000)16.05.2015 18:48:09 - (not logged in) ()> Failed to attach socket.
> Protocol error: Invalid data

**Comment by Jaex** [comment]
FTP codes not changed for long time and these kind of errors mainly to do with FTP library so I'm not sure how I can help about it.
