### ISSUE TITLE
Can't update ShareX from 14.1 to 15.0

### ISSUE THREAD

**Issue by BrainRTP** [ShareX/ShareX#6870]
Hello! For the past few months I have been getting an update notification when I start up the system. Each time I click on the update, but after restarting the system the version drops. 
What happened? How can I update to the latest version normally? 
I use Windows 10

<details>
<summary>Screenshot "About" </summary>

![image](https://user-images.githubusercontent.com/22731705/235470567-2d010fef-7ca9-49c3-a9e1-ad731c9b954a.png)
</details>

<details>
<summary>Screenshot "Update notification" </summary>

![image](https://user-images.githubusercontent.com/22731705/235471032-acf4c319-2d99-4295-a807-45f8e7942b70.png)
</details>

**Comment by vassilyzaitsev** [comment]
Make a backup of your configuration files, uninstall, then install the newest version from the website.

![image](https://user-images.githubusercontent.com/35409978/235503746-11613bcd-b8de-4f77-a15c-8987ca64aa29.png)
