### ISSUE TITLE
[Randomly BUG] Mouse Moves the bottom right with shareX Active 

### ISSUE THREAD

**Issue by chowder908** [ShareX/ShareX#6873]
I wasn't able to recreate this bug after I fixed it by rebooting my PC.

Only when ShareX was my active screen my mouse would force itself to the bottom right. If I change applications my mouse would work fine, but the moment I clicked on shareX my mouse would slide to the bottom right.

**Comment by FriskTheFallenHuman** [comment]
i have this bug too but the mouse moves to the top of the screen
