### ISSUE TITLE
Language issues with OCR

### ISSUE THREAD

**Issue by jkune5** [ShareX/ShareX#6877]
OCR is not recognizing English language

Windows has issues with languages on my PC. I tried DISM restore health and sfc scannow but it said that some things cant be fixed. This may be due because Im using a custom OS, but I just cant install the official OS from microsoft on my old PC because it would be very slow

Could there be a way around this?

![image](https://user-images.githubusercontent.com/55378442/236361709-1c319ee4-04ea-4d49-ad3e-1ab488473c7a.png)

**Comment by asheroto** [comment]
possibly related to #6855
