### ISSUE TITLE
"Object reference not set to an instance of an object." When trying to view history.

### ISSUE THREAD

**Issue by TheUtilityMan** [ShareX/ShareX#6883]
If I try to view or search my history I get this popup error and it won't display the images or let me do anything.
![Error](https://github.com/ShareX/ShareX/assets/133285339/dde7d5d0-86b2-42ab-ac91-c45dc543a14c)

**Comment by m4tic** [comment]
I am experiencing the same with ShareX history. Just one day started doing this. 
I will try downgrading.
![image](https://github.com/ShareX/ShareX/assets/20503684/4097c2df-7921-467a-854d-b6fdd1452a70)

**Comment by TheUtilityMan** [comment]
Thank you, that fixed the problem! =)
