### ISSUE TITLE
Feature Request: Scroll Wheel Changes Text and Shape Size in image editor

### ISSUE THREAD

**Issue by LoganTraceur** [ShareX/ShareX#6890]
I recently switched from Lightshot to ShareX and I am loving ShareX.

However, as someone who annotates dozens of images a week, I loved how in Lightshot that the mouse wheel changed the size of text, arrows, box boarders and objects when editing an image after a screenshot.

In ShareX, the mouse wheel just changes the magnifier size which is not as frequent a use case.

I would be thrilled with a faster way to change the size of text, arrows and objects in ShareX's image editor. I suggest using the scroll wheel like Lightshot as the user experience is already very intuitive and super useful.

**Comment by abegertler** [comment]
Couldn't agree more!! This is the one and only feature missing for me in ShareX!

**Comment by LoganTraceur** [comment]
Thanks abegertler, I still use shareX and still desperately want this feature.

Is there anything we can do to get it more attention?

**Comment by abegertler** [comment]
Ah, well i just reposted this (quoting this post) to try to re-open the topic..
https://github.com/ShareX/ShareX/issues/7657
Hopefully it might get some likes this time and gain some traction?
I don't know what else we can do! (I'm not much of a developer myself!)

**Comment by LoganTraceur** [comment]
Awesome! Fingers crossed it gets traction
