### ISSUE TITLE
Twitter Verification Stopped Working

### ISSUE THREAD

**Issue by AtomskOuO** [ShareX/ShareX#6893]
It seems like Twitter's authentication stopped working. When I press connect (to get the verification code), it usually opens a web page to get the verification code. Now it just says I'm logged in, pressing the Connect... button does nothing and I can't tweet out anything from the program. When I try to send an image, it says "Could not authenticate you." Not sure if this has to do with Twitter's recent API monetization, but that would be my guess? I tried it on two separate computers and it had the same issue.

I can provide the whole error log if that would help, hopefully this gets sorted out soon!

![Capture](https://github.com/ShareX/ShareX/assets/44685055/b59788bb-9a81-4347-b0f0-70be7e3042ac)

**Comment by mangomhf** [comment]
I have the same problem. Please advice.

**Comment by Jaex** [comment]
We had this issue: https://twittercommunity.com/t/this-app-has-violated-twitter-rules-and-policies/191204

People suggested "downgrade to free" and it seems that the API is now working again.

**Comment by AtomskOuO** [comment]
As of 5/24, the issue seems to have been resolved. Not sure if it was a Twitter issue or the application having a hiccup, but I can connect my account like normal again.

**Comment by mangomhf** [comment]
It is working fine now.
