### ISSUE TITLE
Rectangle capture sometimes cancels itself instantly since the 9.10 update

### ISSUE THREAD

**Issue by Razerock** [ShareX/ShareX#690]
I dont really know how to really how to reproduce it, it just happens.
http://i.imgur.com/iObZ2Nt.gif (A gif how it looks like incase its not clear, also the small capture is intentional I meant before the actual capture happens it shows the capturing cross for a really short time and it disappears instantly)
Using the hotkey combination ctrl + shift + 4
If it finally works, it sometimes cancels itself 3 times, it has no other problems just the start is a bit wonky.

**Comment by Razerock** [comment]
http://i.imgur.com/iObZ2Nt.gif I copypasted the wrong link... this is the gif.

**Comment by Jaex** [comment]
Are you sure is your left click not releasing itself? Example my previous logitech mouse have same issue left click was releasing itself when dragging things.

**Comment by Razerock** [comment]
Im sorry I saw it wasnt clear, I edited it.
I didnt mean the capture itself I just wanted to keep the .gif as short as possible thats why its just a small area.

**Comment by riesza** [comment]
I have the same problem

http://puu.sh/hQ1NH/dfaefffe17.webm

**Comment by Jaex** [comment]
riesza your problem look same problem as #691

**Comment by riesza** [comment]
@Jaex Ah, yes, that might be it. I also have my captures on ctrl+1-6 and if I put them anywhere but the number row I don't get that problem.

**Comment by Jaex** [comment]
@Razerock Razerock you were pressing number key too how your issue not same as theirs?

**Comment by Razerock** [comment]
Its the same issue, it works fine if I use something else than the number in my hotkeycombination it works perfectly fine

**Comment by Jaex** [comment]
Why you closing this issue, I will fix it and release new version asap :P

**Comment by Razerock** [comment]
Oh im new to Github, im sorry :c

**Comment by Jaex** [comment]
I will make sure to check modifier keys so monitor capture won't trigger if holding ctrl etc. also will add 1 second delay for key commands to work in rectangle capture so even if you set only 1 as hotkey still it won't trigger monitor capture in rectangle capture as long as you release it under one second.

**Comment by Nathan-Lane** [comment]
Thank you Jaex :)

**Comment by Jaex** [comment]
Check new version please.

**Comment by Nathan-Lane** [comment]
Perfect! Thanks

**Comment by riesza** [comment]
Thanks Jaex, that fixed it. However, as a result of the 1 second delay it seems that it now takes uncomfortably long until you can [ESC] out of the capture prompt. Is there something that can be done about that?

**Comment by Jaex** [comment]
I can handle keys when it is down instead of up. But in this case when you press ESC it will close rectangle capture and when you release ESC some application which have focus can receive that ESC key so what am I supposed to do?

**Comment by riesza** [comment]
Good point and I guess that right click to close it trick is good enough.
