### ISSUE TITLE
can't undo cut-out or crop actions in image editor

### ISSUE THREAD

**Issue by andaluspc** [ShareX/ShareX#6902]
I think the title is self explanatory.
If I do cut-out or crop of an image, I can't reverse that with ctrl+z.
This also applies to some other actions like flipping the image. I can't undo that with ctrl+z.

I would also comment on having no ctrl+y action available (a re-do action) but that has its own issue (# 6792) as I see.

**Comment by Jaex** [comment]
Duplicate of #4079
