### ISSUE TITLE
Hotkey settings (Ctrl + 1) not working in 9.10

### ISSUE THREAD

**Issue by Nathan-Lane** [ShareX/ShareX#691]
Hi,

So I've just updated to ShareX 9.10 and I've always had my hotkeys customised so Ctrl + 1 = Rectangle Region, but it keeps uploading my entire first monitor which is so infuriating.

Can I fix this or will I have to downgrade ShareX?

Thanks.

**Comment by Jaex** [comment]
I was made 1 key to capture first monitor but because it happens when key is up in rectangle capture and you releasing that key when rectangle capture is open, this problem happens. I need to make rectangle capture hotkeys either work 1 second later or make them work in key down instead up.

**Comment by Nathan-Lane** [comment]
Ah okay, I had Ctrl + 1 selected as it was easy to get to quickly, as I use ShareX for the response too, if there's a delay then for me personally it would be better for me to just simply swap the keys as I like to capture action moments in-game. xD

Before seeing your post I tried holding Ctrl + 1 down, that was a mistake xD It rapidly layered my montiro with multiple capture regions making my monitor black, all to try and read that info box that appears at the top right.

**Comment by Jaex** [comment]
Will update issue #690 when I fix it in 15 minutes.
