### ISSUE TITLE
gifycat access denied

### ISSUE THREAD

**Issue by AKBAAR911** [ShareX/ShareX#6911]
Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://filedrop.gfycat.com

Status code:
(400) Bad Request

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
X-Cache: Error from cloudfront
X-Amz-Cf-Pop: MRS52-P3
X-Amz-Cf-Id: 4FLk5tfBYm2WAg3FiXRu79sp5gYGUEYcgySeT6OfeKTcD8pmB5ieFg==
Content-Type: application/xml
Date: Wed, 31 May 2023 17:44:00 GMT
Server: AmazonS3
Via: 1.1 d2e1cc2538095700454cd55cac87c3bc.cloudfront.net (CloudFront)

Response text:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>BSKW0E5XZMJVP1F8</RequestId><HostId>0cGAx0jSVqwPd1gYnlhfNbWODl5UaHVhreRSU6OLDU3LARSsZyoOGSfBBKenpIIEihqjc9ZIUkuFxkqa7MfygQ==</HostId></Error>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

Gfy not found

**Comment by Joehuu** [comment]
Can be closed as Gfycat is discontinued.
