### ISSUE TITLE
Add an option to install without creating a desktop icon.

### ISSUE THREAD

**Issue by Noctran** [ShareX/ShareX#6915]
I would like to propose the creation of an installer switch that prevents the creation of a desktop icon.

**Comment by Jaex** [comment]
Try this [CLI](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline&anchor=MERGETASKS):

```
setup.exe /VERYSILENT /MERGETASKS="!CreateDesktopIcon"
```

**Comment by Noctran** [comment]
Thank you very much:)

May I suggest adding that to the [Documentation](https://getsharex.com/docs/command-line-arguments#sharex-setup-cli)
