### ISSUE TITLE
Can I take a screenshot by identifying web page elements?

### ISSUE THREAD

**Issue by JamYiz** [ShareX/ShareX#6917]
It seems that only rectangular area screenshots can be realized?Can you consider adding a quick frame selection for web page element identification?

**Comment by the-Arioch** [comment]
1. For any external program the browser window is just one big bitmap. Install Spy++ or Windows Detective and see. Only the browser program itself knows the bitmapo it shows has any correspondence with some web-page structure. 

2. Actually that is exactly why tools like LightShot have accompanying plugins(extensions for the browsers. And, ShareX has such a plugin too.

3. Now, bad news. I am not sure that plugin works. At least for me - it neither told any error, nor gave me (in a window otr copied to clipboard) any hyperlink. Maybe it did something, but for the outside obsewrver it was like a black hole. Maybe you would have better luck than me :-)

![firefox_XjAwRRMkri](https://github.com/ShareX/ShareX/assets/937774/c063228e-2e3a-4483-81ff-d39443038519)
![firefox_5jdBKPWv9W](https://github.com/ShareX/ShareX/assets/937774/9d54d2bd-c12c-4e0c-8b54-84e46b1db7d0)

**Comment by JamYiz** [comment]
Thanks for your reply. I open this issue because I found [snipaste](https://www.snipaste.com/) can achieve this function.

![Snipaste_2023-06-19_10-36-19](https://github.com/ShareX/ShareX/assets/44351690/c1ab1aba-5f0e-4f30-9c1b-ce28bf1fbdff)

When you take a screenshot,it can realize the website's element and screenshot of a rectangular area.
It's useful and very convenient. But I don't know how they implement this function.

**Comment by ls148478** [comment]
> Thanks for your reply. I open this issue because I found [snipaste](https://www.snipaste.com/) can achieve this function.
> 
> ![Snipaste_2023-06-19_10-36-19](https://user-images.githubusercontent.com/44351690/246713174-c1ab1aba-5f0e-4f30-9c1b-ce28bf1fbdff.png)
> 
> When you take a screenshot,it can realize the website's element and screenshot of a rectangular area. It's useful and very convenient. But I don't know how they implement this function.

He can indeed achieve it, you can refer to Microsoft's documentation

**Comment by ls148478** [comment]
> Thanks for your reply. I open this issue because I found [snipaste](https://www.snipaste.com/) can achieve this function.
> 
> ![Snipaste_2023-06-19_10-36-19](https://user-images.githubusercontent.com/44351690/246713174-c1ab1aba-5f0e-4f30-9c1b-ce28bf1fbdff.png)
> 
> When you take a screenshot,it can realize the website's element and screenshot of a rectangular area. It's useful and very convenient. But I don't know how they implement this function.

He can indeed achieve it, you can refer to Microsoft's documentation
[https://learn.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-overview](url)
![image](https://github.com/ShareX/ShareX/assets/38435967/e9b6925c-95fe-40aa-9687-8dd4316fb5d3)
