### ISSUE TITLE
How to execute user action with captured image?

### ISSUE THREAD

**Issue by tormozit** [ShareX/ShareX#6927]
I added action in action list. But how to execute it NOT all the time?
I tried to find it in mouse actions list but it is not there.
Best solution for me will be to see this action as command in submenu in internal image editor.

![изображение](https://github.com/ShareX/ShareX/assets/11896251/82909d64-b92d-4c8e-99be-a52707c563a3)

![изображение](https://github.com/ShareX/ShareX/assets/11896251/77edae76-62e9-44af-a7f5-04258009e022)

**Comment by the-Arioch** [comment]
Kinda-sorta

It would still be all-or-nothign though, without selecting specific actions.

1. Set "quick actions menu" to be displayed after the capture - https://github.com/ShareX/ShareX/issues/6044#issuecomment-1265039837
2. Do any capture just to bring the menu on
3. Click the "edit/customize this menu" command
4. CLick the "Add" button
5. Type in any label(caption, tag) you would like
6. Select "Do action" or whatever it was called in English as the command
7. Press OK, then OK

Next time you do a capture the menu would have this option for you, to run ALL the checkboxes external tools.

...vut still no individual selection of tools per-capture

**Comment by tormozit** [comment]
Thanks. I tried your recommendation. It is not good solution for me. I will continue using Clipboard and manual launch of image editor.
