### ISSUE TITLE
Dropbox direct links not working

### ISSUE THREAD

**Issue by Johnnycyan** [ShareX/ShareX#6928]
For some reason recently Dropbox direct links stopped working. They just return 404 pages so ShareX says the link is empty. Did Dropbox kill direct links?

**Comment by Johnnycyan** [comment]
Found this dropbox forum about it which describes my issue but does not have a solution to the problem. https://www.dropboxforum.com/t5/Create-upload-and-share/Shared-Link-quot-scl-quot-to-quot-s-quot/m-p/690677

**Comment by Johnnycyan** [comment]
#6956 provides more information about this

**Comment by reflex24** [comment]
I'm experiencing the same issue, just like several others: https://github.com/ShareX/ShareX/issues/6956

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/commit/5852944ee7faec7ed93f95b83ccc90e50ccc4377
