### ISSUE TITLE
save file locally on failed upload

### ISSUE THREAD

**Issue by Amrinder-S** [ShareX/ShareX#6929]
So i have recently seen many failed uploads to a few image hosts.
I totally understand that ShareX does not control any of those hosts, and just provides an option to upload to them. Therefore can't assist much with that.

However It would have been a nice feature to have "host priority" feature.
such as: If one host fails, it tries another, based on priority. And it should stop if one of those hosts yields successful upload.

Additionally it would be nice to have an option to save the file locally in case of failed upload. (As in I normally do not want my images/gifs etc to be saved, however if the upload fails it should save it locally)

This would be really helpful. Thanks for the read.

**Comment by the-Arioch** [comment]
Maybe the solution would be to delegate uploadaing to an external tool, a specialized program like Zenden2k Image Uploader ? before that tool would get executed the ShareX would just HAVE to save the file :-)

**Comment by Amrinder-S** [comment]
> Maybe the solution would be to delegate uploadaing to an external tool, a specialized program like Zenden2k Image Uploader ? before that tool would get executed the ShareX would just HAVE to save the file :-)

that totally beats the purpose of shareX. If i were to use another tool, i wouldn't use shareX in the first place.
And no, it doesn't fix anything either. ShareX can already save the file and upload. However i want this:
```cpp
if(uploadFailed())
	saveScreenshot();
else
	copyLinkToClipboard();
```
