### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by myagizmaktav** [ShareX/ShareX#6931]
In ShareX, there are numerous tools available, but it is important to know where to find the shortcuts or locate the tools. Having a search bar at the top of all the tools would make it easier to find specific tools.

**Comment by myagizmaktav** [comment]
@Jaex

**Comment by Korb** [comment]
@myagizmaktav, isn't this a duplicate of issue "Suggested feature: Add a quick search field to locate the command" (#2850)?
