### ISSUE TITLE
$prompt$ {prompt} body json

### ISSUE THREAD

**Issue by flinthamm** [ShareX/ShareX#6935]
I've just started using this amazing project again but something seems to have changed in the custom upload handling of prompts? We wish to be prompted for information and input the value given in to the json body that is sent to our custom url shortener.

Previously I'm sure this was working and inside the json body and in addition to {input} we had $prompt:Enter abbreviation$ but this is now being ignored or rather, taken as literal. Having read the [Custom Uploader Guide](https://getsharex.com/docs/custom-uploader) docs, there doesn't seem to be any mention of $prompt$ so I assume this has changed to {prompt:optional title|default value} macro. 

We've used the new macro both with and without the optional data but no prompt ever comes up and the text instead seems to be taken as literal? It's like we are escaping them `\{prompt\}`  but we are not ?

What are we doing wrong and how can we get around this?

**Comment by BluDood** [comment]
I noticed this as well, while `{input}` gets replaced by the Text Uploader input, `{prompt}` does not show a dialog nor get replaced with anything.
