### ISSUE TITLE
Can we add "pin to screen" to the top toolbar?

### ISSUE THREAD

**Issue by ghost** [ShareX/ShareX#6939]
![image](https://github.com/ShareX/ShareX/assets/112467275/4d16d9bd-e924-4a12-b881-709a52014283)
I think it would be more convenient.

**Comment by leumasme** [comment]
Currently, all of these tools (not including the the 3 rightmost non-tool icons) just edit the screenshot (&preview).  
How exactly would pin to screen work when used from there?  
Is it a button to pin the currently selected regions to screen? That wouldn't work without multi-region capture turned on.  
Is it a different type of region selector like the 3 on the right? If yes, will that cause you to just have the pinned part floating around after selecting a region with it, or will the pins only be created when the screenshot preview is exited?  
What will happen if multiple regions were selected with pin to screen - will they become multiple pins or one that stretches over all of them? The pin to screen windows dont play too well with transparency afaik.  
Nontheless, a Pin to Screen tool in the screenshot toolbar would have to work very differently from the already present tools - I suggest just configuring your ShareX to pin an item to the screen if you click the screenshot result that appears in the bottom right after you take a screenshot.
