### ISSUE TITLE
Battery power drain - high requested update frequence

### ISSUE THREAD

**Issue by someaddons** [ShareX/ShareX#6941]
![image](https://github.com/ShareX/ShareX/assets/38401808/f9311eb0-cb9c-4a4c-8cc6-1d9fbb922b45)
Share X is requesting a high platform update frequency, while just idling in the background. Should be only necessary during recording videos

**Comment by LEveLiQ** [comment]
can confirm, my usual idle power draw is 10W and when I start ShareX it increases to 22W
Definitely needs some optimization, I'm bumping to gather some eyes on this.
