### ISSUE TITLE
hide cursor doesn't apply to gifs

### ISSUE THREAD

**Issue by Hifilo** [ShareX/ShareX#6946]
Hi I noticed the show/hide cursor button in the tray > capture menu does not seem to apply when I record a gif. 

I have to go into settings and turn it off. I assumed the button would cover both video & gif. Not a serious issue, but since I noticed it I thought I'd post it here.

Thanks

**Comment by marvellz** [comment]
Yes, same problem. Noticed only on the second monitor. Try recording this on the main monitor.

**Comment by inson1** [comment]
I thing there should be 2 otptions - from screenshots, from gifs, videos
