### ISSUE TITLE
Screen recording flickers a lot when recording glowing hover elements.

### ISSUE THREAD

**Issue by jizzyjdog** [ShareX/ShareX#6947]
https://github.com/ShareX/ShareX/assets/109762133/91d078c6-bf4b-4e10-a46e-af5857f5a344

I don't know why it is doing this, but it only happens with shareX and not with something like OBS. It flickers with both gif recordings and video recordings. I am using H.264/NVENC, bitrate 13500, preset slow (high quality 2 passes). this is the site im trying to record: https://kbin.social/m/longnosebork

**Comment by charithharshana** [comment]
https://github.com/user-attachments/assets/89c3b958-4b63-4932-9076-ac9076128499
I see still has this issue!!
