### ISSUE TITLE
Hide taskbar does not hide the secondary taskbar (when you have multiple monitors)

### ISSUE THREAD

**Issue by NaitorStudios** [ShareX/ShareX#6948]
The issue bothers me quite a lot because if the window is anywhere near the screen edge with capture window with transparency enabled, it will get the taskbar and look bad.
It would be very appreciated if you guys could fix this, I'm using Dev build.

**Comment by NaitorStudios** [comment]
Guess I'll have to implement it and compile myself then...

**Comment by Jaex** [comment]
> It's like one line of code...

I don't have multi monitors...

**Comment by NaitorStudios** [comment]
I see, well, there are many mobile apps that turns the device into a wireless monitor, most of which are free, you could try that...
