### ISSUE TITLE
How to edit image,automatically copy it to the clipboard and close it without prompt

### ISSUE THREAD

**Issue by Export33** [ShareX/ShareX#6954]
Hi,

i need some assistance in using shareX.

UseCase:
I wan´t to 
-  take a screenshot
- edit it in the editor (mostly draw a rectangle)
- copy the edited image to the clipboard and close it without a prompt

I´ve set share x to open it in the editor where i can do my editing.
Clicking the checkmark (apply changes & continue) does what i want to do, but i don´t like to find this little checkmark. Pressing Enter would mean that my hand has leave the mouse (as a right-handed person) so it´s not feasible for me.

Is there an option to change the right click action or action on exit to do  what i want (close without prompt and save changes to the clipboard)? 
Switching the space key to apply changes & continue would also help.

**Comment by Neclony** [comment]
In the editor you can click on "auto copy image to clipboard" with space it closes without a prompt.
