### ISSUE TITLE
HotkeySettingsForm causes clipboard contents to be reset

### ISSUE THREAD

**Issue by HitomiTenshi** [ShareX/ShareX#696]
Issue:
When opening up the `HotkeySettingsForm` and double clicking on a `HotkeySelectionControl` in the `FlowLayoutPanel (flpHotkeys)`, the clipboard content gets set to the `lblHotkeyDescription.Text` of the `HotkeySelectionControl`.

The issue only happens on the double click event. Clicking the Edit-Button does __not__ cause the clipboard contents to be reset.

I tried to fix this issue myself but I couldn't find where the clipboard change was happening. Setting breakpoints on every function in the `ClipboardHelpers` class didn't work (breakpoints weren't triggered).

A little video showing my struggle:
http://a.pomf.se/oiyxae.webm

**Comment by Jaex** [comment]
I can't figure out what kind of wizardry is this too. There is no where clipboard method used in this hotkey window and controls. Also only ClipboardHelpers doing all clipboard writing and when I add breakpoints to those functions, breakpoints never triggers too. So I'm currently shocked how such thing possible.

**Comment by Jaex** [comment]
It is bug in .NET side: http://stackoverflow.com/a/17048661/264877

And tried many workarounds none of them was good enough to fix this issue.

Example tried this:

```csharp
    public class LabelNoCopy : Label
    {
        private bool doubleClick;

        protected override void WndProc(ref Message m)
        {
            if (m.Msg == (int)WindowsMessages.LBUTTONDBLCLK)
            {
                doubleClick = true;
            }
            else if (m.Msg == (int)WindowsMessages.GETTEXT && doubleClick)
            {
                doubleClick = false;
                return;
            }

            base.WndProc(ref m);
        }
    }
```

and it was just making clipboard empty instead not setting label text.

So I can't fix it.
