### ISSUE TITLE
incremental filenaming selected, but filenaming is still random

### ISSUE THREAD

**Issue by GooberPyle** [ShareX/ShareX#6960]
Hello there. I'm not a forum kind of guy, but i'm desperate because i use ShareX day in and day out for my job. I have scoured the internet for a solution to this problem but to no avail.

As indicated in the title, inputting some sort of incremental filenaming structure in the Task Settings -> Uploads section does nothing to change the names of the file names. Whether or not i change the setting, i'm consistently getting stupid filenames like "explorerCs4W23Fcc" and such.  

This has not been a problem in the past, but, ever since i recently wiped out my PC and freshly installed Win10, ShareX has been consistenly exhibiting this problem. Today, I spent about an hour trying to figure out what was going on. The standard method doesn't solve the problem. 

Is this a bug? Is there a checkbox somewhere that should be checked?

Many thanks in advance for any assistance.

**Comment by Korb** [comment]
@GooberPyle, have you found out where in the application settings the mask for the saved name is set?
