### ISSUE TITLE
Chrome Extension does not work

### ISSUE THREAD

**Issue by dimmduh** [ShareX/ShareX#6962]
Context menu button "Upload with ShareX" does nothing
https://chrome.google.com/webstore/detail/sharex/nlkoigbdolhchiicbonbihbphgamnaoc/related

**Comment by Manchewable** [comment]
You have to enable it in your ShareX. 

Go to Application Settings -> Integration -> Enable Chrome extension support
![ShareX_0e3bcfyDzF](https://github.com/ShareX/ShareX/assets/35658388/daeebbf5-9a4b-44fb-ad8e-ad7aa8cab82d)

**Comment by Doldak** [comment]
nope, it dont work
