### ISSUE TITLE
OCR result hard to read, we should separated with spaces as a normal sentence 

### ISSUE THREAD

**Issue by o0oke** [ShareX/ShareX#6971]
The capture OCR sentence do not separated by spaces:

![Dingtalk_20230703090454](https://github.com/ShareX/ShareX/assets/8325934/ed6f9e78-d915-422c-b3b4-996d40b9b223)

**Comment by MostafaAkrsh** [comment]
Can you provide an image example?

**Comment by o0oke** [comment]
![Type-C](https://github.com/ShareX/ShareX/assets/8325934/2ed787ca-3e96-4adc-9f10-ff9bfc1f4cfe)
Thanks, please refer to the  attached image.
