### ISSUE TITLE
Disabling file name warning.

### ISSUE THREAD

**Issue by daddyDOT** [ShareX/ShareX#6976]
Hello,

I wonder if it's possible to disable this warning on auto capture and to automatically overwrite the file instead.
The possibility was previously mentioned in #4413 but I couldn't find the option for disabling.

Thanks!

![image](https://github.com/ShareX/ShareX/assets/65982671/bc4896d1-94d5-4b76-b2da-752ba40e20e6)

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2023/07/ShareX_uRgbO5cAVR.png)
