### ISSUE TITLE
V15.0 ffmpeg download issue

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#6980]
Where's the option for ffmpeg download and install?

I get this

![image](https://github.com/ShareX/ShareX/assets/6157073/2adb935e-e380-435d-b1dd-91944911e966)

but the ffmpeg download option that web advice says should be on this dialog is missing. Likewise missing is the option Task settings >> Screen recorder >> Screen recorder options >> FFmpeg path >> Download.

**Comment by luanrnunes** [comment]
Hello chrisjj,
You can get ffmpeg through here: https://github.com/ShareX/FFmpeg/releases/tag/v6.0

**Comment by chrisjj** [comment]
Thanks for the workaround. If anyone knows the answer, I'd still like to see it.
