### ISSUE TITLE
Support rsa-sha2-256/512 for SFTP uploader

### ISSUE THREAD

**Issue by iTob191** [ShareX/ShareX#6981]
Authentication using RSA keys with SHA-1 is disabled by default since [OpenSSH 8.8](https://www.openssh.com/txt/release-8.8). Trying to connect to such a server using ShareX currently results in the error message "Permission denied (publickey)".

~~Blocked by https://github.com/sshnet/SSH.NET/issues/825, workaround in https://github.com/sshnet/SSH.NET/issues/825#issuecomment-1139440419~~

**Comment by MLWALK3R** [comment]
+1

**Comment by lilggamegenius** [comment]
Seems like SSH.NET has a release to fix this now
https://github.com/sshnet/SSH.NET/issues/825#issuecomment-1756313950
Should be as easy as updating the lib in nuget.

**Comment by Jaex** [comment]
Lib is updated now.

**Comment by iTob191** [comment]
I guess we just have to wait for the next update then

**Comment by lilggamegenius** [comment]
I haven't tested it yet, but I believe the change is in the latest dev build https://getsharex.com/docs/dev-builds
