### ISSUE TITLE
Imgur upload failed: (417) Internal expectation failed

### ISSUE THREAD

**Issue by alundil** [ShareX/ShareX#6989]
Attempted to upload a gif. 2 attempts with the same .gif failed with the same error. I was able to upload the file directly from the imgur.com website. Was also able to right-click and upload to imgur from sharex on other image files.

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: keep-alive
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1249
X-Post-Rate-Limit-Reset: 3595
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 2000
X-Ratelimit-Userremaining: 2000
X-Ratelimit-Userreset: 3600
X-Served-By: cache-iah17224-IAH
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1689420421.055318,VS0,VE4705
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Sat, 15 Jul 2023 11:27:05 GMT
Server: cat factory 1.0

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by KingJoey21** [comment]
I'm also having this exact issue.

**Comment by BeyondSteaLikez** [comment]
any news on this?

**Comment by Mwr247** [comment]
Check if your Imgur upload target album was deleted. I've been getting this the past few days, so I decided to reauthenticate in ShareX, then when that didn't change anything I tried to refresh my album list on the right side, and my selected album was missing. Checking Imgur itself, my album I used for sharing (and the album tab for that matter) are both gone.

**Comment by BeyondSteaLikez** [comment]
> Check if your Imgur upload target album was deleted. I've been getting this the past few days, so I decided to reauthenticate in ShareX, then when that didn't change anything I tried to refresh my album list on the right side, and my selected album was missing. Checking Imgur itself, my album I used for sharing (and the album tab for that matter) are both gone.

this could be the issue ty
