### ISSUE TITLE
CloudUp Support

### ISSUE THREAD

**Issue by craigjsmith** [ShareX/ShareX#70]
Would be awesome if it supported CloudUp https://cloudup.com/

**Comment by jbrooksuk** [comment]
There is no public API yet either.

**Comment by jbrooksuk** [comment]
You may be able to reverse engineer https://github.com/Automattic/cloudup-client

**Comment by Jaex** [comment]
If they don't have public API that means they don't want us to use their service.

**Comment by vatterspun** [comment]
This issue is almost 5 years old, maybe close?

**Comment by McoreD** [comment]
Smart Eraser color behavior is working now.

There are still several other minor issues in the editor/region-capture workflow (tool settings sync, annotation state edge cases, and related UX inconsistencies) that will need to be fixed over time. We will continue addressing these incrementally in follow-up fixes.
