### ISSUE TITLE
Chevereto Custom API support..

### ISSUE THREAD

**Issue by ne0ark** [ShareX/ShareX#701]
Allow to specify custom API URL instead of fixed api/1/upload. See bottom of page https://chevereto.com/docs/api-v1 for "API user upload workaround".

Thanks

**Comment by Jaex** [comment]
I was planning to add it this release but then noticed many people must be using url with fixed "api/1/upload" and their upload will get broken if i make url don't use fixed url now. So I don't want to break other people config for this. As a workaround you can config custom uploader like in here: https://chevereto.com/docs/sharex

**Comment by ne0ark** [comment]
@Jaex you can set api/1/upload as default value but make it editable. That way for people who don't specify it won't break.

**Comment by Jaex** [comment]
I made it editable now.
