### ISSUE TITLE
I can't copy GIF to clipboard automatically after recording.

### ISSUE THREAD

**Issue by ErkundenSie** [ShareX/ShareX#7011]
I can't copy GIF to clipboard automatically after recording.

**Comment by Neclony** [comment]
In my testing it follows the after capture task(not all tested) but the "show quick task menu" does not work. If you add "copy image to clipboard" you do not have to open it up manually.

**Comment by ErkundenSie** [comment]
I have selected the option to copy the image to the clipboard, but the GIF as a picture format is not pasted to the clipboard, it can only be achieved by turning on the function to copy the file to the clipboard, but I can't view my history pictures on the clipboard in this case, so I suggest to modify it.

**Comment by inson1** [comment]
Same here
