### ISSUE TITLE
Edit with shareX in context menu is not working in windows 11

### ISSUE THREAD

**Issue by anitro5** [ShareX/ShareX#7022]
Please tell me how can I fix it? I'm noob.

https://github.com/ShareX/ShareX/assets/111676882/fc1cf087-1883-42f8-8469-ef68c4b779d8

**Comment by victorgarciadeveloper** [comment]
Hi! I have a few questions: 
* What version of ShareX are you running?
* Are you able to open ShareX from the task bar and start menu without issue?
* What version of Windows are you using?
