### ISSUE TITLE
Custom Uploader POST file

### ISSUE THREAD

**Issue by hugomd** [ShareX/ShareX#703]
Hi ShareX team,

ShareX is awesome, thanks for your dedicated work.

I'm trying to use the custom uploader with the CloudApp API and it should be working but I can't work out how I can create a 'file' argument that POSTs the file.

Basically, one of my I have a bunch of misc arguments to include on each upload but one of them HAS to be the file. I was wondering if this is currently possible with ShareX? 

I'm happy to elaborate if I explained poorly.

Thanks!

**Comment by dualmoon** [comment]
I'd love to see this as well. Unfortunately it seems the dev is pretty keen on refusing this. Unfortunate. I just learned about this piece of software today but if it doesn't support the cloud storage I'm currently paying for then there's zero use for it.
