### ISSUE TITLE
Detected in VT

### ISSUE THREAD

**Issue by Unkn0wnHunt** [ShareX/ShareX#7033]
Here is the detection link: https://www.virustotal.com/gui/file/b95166183ae61504728c5667c71743a978829b98ed11bea6c17d2c338d2e86e7

The file is ShareX-15.0.0-setup.exe downloaded from the website.

**Comment by D4rkov** [comment]
Can confirm, my Windows Security also flagged the setup.exe

**Comment by ohhq** [comment]
Its not a virus, its only get flagged because it not a signed app 
![image](https://github.com/ShareX/ShareX/assets/77167979/1a7bb337-c769-4d1d-a513-feb4c5d49915)

**Comment by D4rkov** [comment]
> Its not a virus, its only get flagged because it not a signed app ![image](https://user-images.githubusercontent.com/77167979/260170171-1a7bb337-c769-4d1d-a513-feb4c5d49915.png)

Since when does Windows Security flag programs based on whether they're signed or not?

**Comment by ohhq** [comment]
> > Its not a virus, its only get flagged because it not a signed app ![image](https://user-images.githubusercontent.com/77167979/260170171-1a7bb337-c769-4d1d-a513-feb4c5d49915.png)
> 
> Since when does Windows Security flag programs based on whether they're signed or not? Anyways, I downloaded the latest Dev Build and Windows Security didn't flag it this time, weird.

idk i thought. because windows defender only popup when the app is not signed so i thought it was that 🤷‍♂️
