### ISSUE TITLE
Enhance behavior for screen recording for multiple displays/monitors

### ISSUE THREAD

**Issue by helperman** [ShareX/ShareX#7042]
"Start/Stop screen recording using active window region" now treats two displays as one region and records both two displays in one output video file.
How can I manually choose only one of them (without selecting left upper point and right bottom point which is a little bit tedious)?
I suggest a feature/enhancement: by default treat active region for screen recording as a display the mouse is hovered upon.
If user wants to record all displays then he holds Ctrl button on keyboard and active region extends to all displays.

Or another behavior: press (without holding) Ctrl button to extend region (press once = active region for recordion extends for two displays, press again - active region for recordion extends for three displays, etc).

**Comment by helperman** [comment]
Another way: show small window with options for a region to capture before starting screen capturing.
Here is how it's done in FastStone Capture (you can grab an idea):
![изображение](https://github.com/ShareX/ShareX/assets/8351863/838277bd-5279-4e06-8547-974d09e41095)

**Comment by Robubble** [comment]
I hoped the multi region would also work for video but I guess it's not the case as I only get one region despite having a workflow that has multi region enabled.
