### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kittenvr** [ShareX/ShareX#7047]
is there a way to copy to clipboard after add image effect?

**Comment by victorgarciadeveloper** [comment]
Hi! 

So I was able to add image effects to the image. Then I right clicked on the edited image preview on the right-hand side. This shows a "Copy Image" button that allows you to copy the edited image to the clipboard. 

Try that and let me know if that works. Thanks!

**Comment by kittenvr** [comment]
> Hi! 
> 
> So I was able to add image effects to the image. Then I right clicked on the edited image preview on the right-hand side. This shows a "Copy Image" button that allows you to copy the edited image to the clipboard. 
> 
> Try that and let me know if that works. Thanks!

I don't want to do that for every image I make

**Comment by victorgarciadeveloper** [comment]
What is the desired functionality? Can you explain it a little more clearly? That would really help 👍
