### ISSUE TITLE
Window screenshot captures 1-2 pixels out of border

### ISSUE THREAD

**Issue by Triramama** [ShareX/ShareX#7048]
So when I use the function "capture active window" to capture a window that's not in full screen, for some reason the program captures extra 1 pixel around the window border so you can see a little bit of what's behind it, especially so if the colors contrast with each other, this is ruins my screencaps for me, can i somehow remedy it and make it capture strictly the tab that's I'm focused on? 
![Acrobat_lgefaO3OLO](https://github.com/ShareX/ShareX/assets/97356540/333f8868-555f-422d-ba98-4c9a9195bb93)

**Comment by Jaex** [comment]
It captures correctly. Just unfocused windows have transparent borders:

![](https://jaex.getsharex.com/2023/08/paintdotnet_zcmzPsYncw.png)

**Comment by Triramama** [comment]
Thanks, but I'm pretty sure I'm focused on the window I'm capturing
