### ISSUE TITLE
QR code resolution

### ISSUE THREAD

**Issue by mwpowellhtx** [ShareX/ShareX#7049]
I gather resolution is managed by shrinking or growing the host window? Is there any way for codes to shrink less than 150x? That's pretty small, I can work with it, but I might like to tuck the code away on a parent visual in a less conspicuous margin of the image, for instance. Available, yes, prominant, yes, but not so overwhelming that it draws focus away from the impact of the visual itself. Does that make sense? I have in mind 100x or even less, if that were possible. Thanks...

**Comment by Jaex** [comment]
It is already available in [dev build](https://getsharex.com/docs/dev-builds).

![](https://jaex.getsharex.com/2023/08/ShareX_GGoYZB1FeP.png)

**Comment by mwpowellhtx** [comment]
Ah! Awesome fantastic!
