### ISSUE TITLE
Deactivated settings - now when starting, then only screenshots are displayed, but no settings anymore

### ISSUE THREAD

**Issue by VERAUTWIEN** [ShareX/ShareX#7054]
Hello,

I have installed ShareX. I tried something in the settings, now when I start ShareX I can only see the screenshots and not menu or settings tab, etc :-(
What can I do to see the settings again?

Regards,
Patrick

**Comment by VERAUTWIEN** [comment]
![image](https://github.com/ShareX/ShareX/assets/143081208/d8df05e2-86aa-4d6b-b67a-b6947849b48f)

**Comment by L1Q** [comment]
You can get to the Application settings from the system tray icon. You are looking for "Main window" - "Show menu" checkbox.

**Comment by VERAUTWIEN** [comment]
but if there is no system tray icon anymore ?

**Comment by VERAUTWIEN** [comment]
the only thing i can get "by starting the shareX application" the image above ..in system tray I cannot see any ShareX ;-(

**Comment by VERAUTWIEN** [comment]
thanks a lot, that worked fine, thanks a lot ;-)

additional question:
but having the program started in background (no program on fron screen, when starting) and also not visible in system tray is not possible ?

**Comment by L1Q** [comment]
> thanks a lot, that worked fine, thanks a lot ;-)
> 
> additional question: but having the program started in background (no program on fron screen, when starting) and also not visible in system tray is not possible ?

Not to my knowledge.
