### ISSUE TITLE
I have my internet traffic routed through tor, i cannot upload.

### ISSUE THREAD

**Issue by Motzumoto** [ShareX/ShareX#7057]
As the title says, heres my entire log

[ShareX-Log-2023-08.txt](https://github.com/ShareX/ShareX/files/12446560/ShareX-Log-2023-08.txt)
```
Error message:
The underlying connection was closed: Unable to connect to the remote server.

Request URL:
https://hep.gg/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by helperman** [comment]
Explain how to reproduce it.

**Comment by Motzumoto** [comment]
> Explain how to reproduce it.

download and run this. Like i said i have my internet traffic routed through tor. https://sourceforge.net/projects/advtor/

**Comment by Motzumoto** [comment]
> @helperman @Motzumoto I have shared my working configuration with Privoxy as a HTTP forwarding proxy to TOR running on same machine that I use with ShareX The configuration can also be ran in docker-compose with Privoxy and TOR as service stack and expose both the HTTP port and TOR's SOCKS5 port.
> 
> Heres the configration [#1113 (comment)](https://github.com/ShareX/ShareX/issues/1113#issuecomment-2015826527)

Awesome thank you!
