### ISSUE TITLE
"Pin to screen" doesn't obey Hotkey settings

### ISSUE THREAD

**Issue by helperman** [ShareX/ShareX#7059]
"Pin to screen" doesn't obey Hotkey settings

Steps:
- Add hotkey for "Pin to screen"
- set overrride capture settings
- set "Show magnifier near cursor" = false 
- click hotkey for "Pin to screen"

Expected: magnifier is not appeared
Actual: magnifier is appeared

**Comment by victorgarciadeveloper** [comment]
I have committed changes in my fork that fixes this issue. I will clean up the code and submit for PR later today.
