### ISSUE TITLE
Scrolling window capture doesn't get stitched together nicely

### ISSUE THREAD

**Issue by jddcef** [ShareX/ShareX#7063]
Great software! but the scrolling stitching doesn't work that well... I get results like this when scroll shotting an old windows app

![image](https://github.com/ShareX/ShareX/assets/608676/7e898b3f-431e-4dd3-ad91-7c2cf73ef245)

See also #4162 - it went stale, but is still relevant.

tangentially related #4722

**Comment by Jaex** [comment]
Scrolling capture rewritten in [dev build](https://getsharex.com/docs/dev-builds), if you wanna test it.

**Comment by jddcef** [comment]
> Scrolling capture rewritten in [dev build](https://getsharex.com/docs/dev-builds), if you wanna test it.

Thank you. You seem like a really organised person.
Anyway, the new scrolling seems better if I create the block area with the mouse to capture, rather than just clicking on the automatically detected scrollable area.

- If i just click on an area to capture, it scrolls a lot, until i move the mouse then it stops, that's ok, but the captured image is just only the first screenshot or so, and doesn't have the whole scrolled area that up the screen, the stitching isn't done. I notice the scroll bar is included in the capture area.

- If I select an area to capture (which by the way is not clear that it is possible, perhaps add some explanation text when choosing the area to capture, saying that one can drag to select an area. This goes a bit longer, but stops by itself, and then the final image is a lot shorter than the area that was scrolled.

I'm testing it on Libronix, an old windows application.

- The old issue of the scrolling capture being interrupted is still there, what stops the scrolling capture?  Shouldn't it wait for an ESC key to be pressed? At the moment it just seems to stop randomly. Then the capture is very short compared to the scrolled distance.

**Comment by jddcef** [comment]
@Jaex is there any capture mode that I can do something like: 

- Scroll with key (PG DOWN) and capture with that key as the scroll action rather than the mouse method used currently?
- 
- Save to Disk/ create separate files every X-MB or X-Pixels - to flush out the memory/size of the image to keep it more stable and manageable.
-

**Comment by jddcef** [comment]
The old version did capture things that actually scrolled by, but it didn't get stitched together nicely on the overlaps.

**Comment by stevekenney318** [comment]
> * If i just click on an area to capture, it scrolls a lot, until i move the mouse then it stops, that's ok, but the captured image is just only the first screenshot or so, and doesn't have the whole scrolled area that up the screen, the stitching isn't done. I notice the scroll bar is included in the capture area.
> * If I select an area to capture (which by the way is not clear that it is possible, perhaps add some explanation text when choosing the area to capture, saying that one can drag to select an area. This goes a bit longer, but stops by itself, and then the final image is a lot shorter than the area that was scrolled.

I just installed the dev version and am having similar results ... it scrolls, but only saves the original screenshot.

**Comment by vivadavid** [comment]
Hi,

I'm obtaining similar results as @jddcef trying to capture webpages. I'm on Sharex 15.0. This the webpage I was trying to capture on the reading mode in Microsoft Edge:

https://www.vozpopuli.com/opinion/terror-amor.html

And this is the area where it fails:

![scrolling capture](https://github.com/ShareX/ShareX/assets/9334287/4060e013-7a0a-4bdd-baff-5283d3a1aaa8)

Also, I set the tool to automatically start the scrolling capture and now I don't know where to find the settings for this feature and how to make the settings appear before starting the capture.

**Comment by vivadavid** [comment]
On version 16.1, scrolling captures seem to work nicely!
