### ISSUE TITLE
Is there a way to record only one window **without** other windows overlapping?

### ISSUE THREAD

**Issue by defaultuserQ** [ShareX/ShareX#7065]

**Comment by L1Q** [comment]
This could be a feature request.

FFmpeg seems to have a special option for this when using ``GDI grab`` for video source.

From [FFmpeg wiki on Desktop Capture](https://trac.ffmpeg.org/wiki/Capture/Desktop#Usebuilt-inGDIscreengrabber):

> To grab the contents of the window named "Calculator":
> 
> ```sh
> ffmpeg -f gdigrab -framerate 30 -i title=Calculator output.mkv
> ```

**Comment by Nammehub** [comment]
ShareX can focus on a window (game window, for example) and take a screenshot. How to make focus on arbitrary window for recording video/gif?
