### ISSUE TITLE
Dropbox upload stopped working

### ISSUE THREAD

**Issue by kkthebeast** [ShareX/ShareX#7067]
I haven't changed any settings: started getting errors after taking screenshots a few weeks ago, tried resigning into Dropbox and updating the verification code..

The first Error just says, Error, the URL is Empty.

Trying to right click and Upload afterward:

Error message:
The remote server returned an error: (409) Conflict.

Request URL:
https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings

Status code:
(409) Conflict

Headers:
Content-Security-Policy: sandbox allow-forms allow-scripts
X-Content-Type-Options: nosniff
Accept-Encoding: identity,gzip
X-Dropbox-Response-Origin: far_remote
X-Dropbox-Request-Id: de3bcaa880b04974b64593dd72b99d7d
Content-Length: 97
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 01 Sep 2023 10:04:29 GMT
Server: envoy

Response text:
{"error_summary": "shared_link_already_exists/", "error": {".tag": "shared_link_already_exists"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

**Comment by BartyMae** [comment]
What's odd is that it's not as if direct links have suddenly stopped working - one can check their browser history for old dl.dropboxusercontent.com links, and they still work (if the file still exists on your dropbox, that is). ShareX just doesn't seem to be generating them correctly anymore.

**Comment by baulaergrungim** [comment]
I just randomly checked some stuff... if you replace "dl=0" with "dl=1", in places like discord, image will embed the old way, but if you click the link, it'll be downloaded automatically instead just display in browser. If you replace the whole "dl" with "raw=1", it will embed in discord AND will open as a file in browser (at lest as far as images go). Didn't check with other types of files, and the link with "raw=1" in browser is pretty funky, as well. I believe that's an acceptable workaround, though.
