### ISSUE TITLE
Support for Google Cloud Storage

### ISSUE THREAD

**Issue by Glitchvid** [ShareX/ShareX#707]
There's support for S3 and even Google Drive, I'm surprised there isn't any Google cloud storage support, it would be great to have, thanks.

It appears to work similar to S3 and Google Drive.
API Stuff: https://cloud.google.com/storage/docs/overview
A custom URL option akin to the current S3 implementation should also be included.

**Comment by Jaex** [comment]
How you can surprise about this, Google Drive is free so I could try and add it but Google Cloud is not free therefore I'm not planning to buy it just for be able to add it. Also mainly it not worth adding paid only services because very few people be able to use them.

**Comment by mhils** [comment]
I'd be more than happy to start putting a $25 bounty on this issue - I know that is not much and rather symbolic, but I'm unfortunately just a poor student and maybe others want to hop in as well. :relaxed: 
Google Cloud Storage usually offers a free demo, but I'd be happy to share bucket access to anyone who's interested.

**Comment by spotlightishere** [comment]
Is there anything more on this? It looks like Azure Storage was added at some point, which I've heard is used about the same amount as Cloud Storage. It does have a similar API to Drive as mentioned originally.

**Comment by spotlightishere** [comment]
Almost a year after someone brought it up again I found more on this.
Google Cloud Storage has S3 "interoperability". To quote [their page](https://cloud.google.com/storage/docs/interoperability#using_the_xml_api),

> change the request endpoint (URI) that the tool or library uses so it points to the Cloud Storage URI (https://storage.googleapis.com), and configure the tool or library to use your Cloud Storage [developer keys](https://cloud.google.com/storage/docs/reference/v1/getting-startedv1.html#keys).

Because of this you can change the endpoint as given and set up the developer keys in Cloud Storage Settings.
![sharex_2018-03-07_23-27-33](https://user-images.githubusercontent.com/10055256/37124311-62a73208-222d-11e8-9367-e56783ea9d47.png)

**Comment by matthewburnett** [comment]
I've begun work on this and it will be it's own uploader. You can check my progress on my fork. So far I have the main program, OAuth support (no need for access keys), and custom domain support.
