### ISSUE TITLE
Remove OCR notification

### ISSUE THREAD

**Issue by MakerManu** [ShareX/ShareX#7073]
Hi all, how can I remove the successful confirmation notification in the bottom right corner of the Desktop when I manually do an OCR? I know there are options to remove notifications but they work for, indeed, all capture options except for the OCR tool.
I have tried them all but it keeps appearing.
https://imgur.com/Ukkz90L

**Comment by stevekenney318** [comment]
Interesting ... I've never seen that when I capture OCR ...

**Comment by MakerManu** [comment]
Yes because usually Optical Character Recognition (that window with the OCR result) comes up, only I put "Process OCR silently" in the options.

**Comment by MakerManu** [comment]
So can it be solved?

**Comment by Eitt1** [comment]
https://www.reddit.com/r/sharex/comments/7dy7cr/how_to_remove_preview_in_bottom_right_of_screen/

It may be useful
