### ISSUE TITLE
Avast Antivirus reports Botnet:Blacklist on 140.82.121.5:443

### ISSUE THREAD

**Issue by unknown4user** [ShareX/ShareX#7075]
ShareX is running in the background in the icon tray, and Avast antivirus shows the following block message without interacting with the ShareX application. 

![Schnappschuss_090823_103647_PM](https://github.com/ShareX/ShareX/assets/29423583/9ba78512-36d9-4a9a-a18d-058235b90b73)

**Comment by SvenAtGit** [comment]
I had the same issue this morning!
