### ISSUE TITLE
Onedrive (auto) backup 

### ISSUE THREAD

**Issue by nikagersonlohman** [ShareX/ShareX#7078]
Hi,

ShareX saves its log files and json config files by default in de Documents folder. Onedrive creates a backup of this folder, causing a very frequent upload of changed log and json files.

On a Windows system, it's better to use the AppData folder for log/config files:
%appdata%\ShareX
or (in ShareX)
%ApplicationData%\ShareX

And the Documents folder for Screenshots.:
%MyDocuments%\ShareX\Screenshots

Can these defaults be set instead of default everything into the Documents folder?

Regards,

Nika.

**Comment by Jellie06** [comment]
Searching for this myself
