### ISSUE TITLE
Keyboard shortcut to slow mouse movement for pixel-perfect captures

### ISSUE THREAD

**Issue by dtrichter** [ShareX/ShareX#7081]
I love ShareX!  It is very feature-rich and after months and months of heavy use I have had no software issues to speak of.  Great job to the ShareX team!

I have a feature request that would make a marked improvement for my use cases.  When capturing regions, the zoomed in reticle is an excellent way to help capture pixel-perfect screenshots the first time.  I use it constantly.  However, I often find it difficult to move my mouse one pixel at a time to get perfect alignment.  My suggestion would be to allow a keyboard shortcut that when held down during region captures would increase the mouse sensitivity by perhaps 4x - or possibly a configurable amount.

Thank you again!

**Comment by Predict5** [comment]
Use the Arrow Keys.

**Comment by dtrichter** [comment]
Well that worked nicely!  Thank you!
