### ISSUE TITLE
Poor OCR accuracy - consider using PowerOCR or Text Grab

### ISSUE THREAD

**Issue by ImportTaste** [ShareX/ShareX#7087]
ShareX's OCR is extremely inaccurate. Additionally, trying to do a selection of something like size 11 Arial font requires a lot of extra padding around the selection for it to even register, which can prevent a user from making a more precise selection when it's surrounded by text the user doesn't want.

PowerToys (MIT licensed) recently implemented PowerOCR, which is extremely accurate: https://github.com/microsoft/PowerToys/blob/main/src/modules/PowerOCR/PowerOCR/Helpers/ImageMethods.cs

EDIT: Apparently PowerOCR is based on "Text Grab", which is also MIT licensed: https://github.com/TheJoeFin/Text-Grab

**Comment by Jaex** [comment]
Both using [same OCR engine](https://learn.microsoft.com/en-us/uwp/api/windows.media.ocr) as us.

**Comment by karpalig** [comment]
> PowerToys (MIT licensed) recently implemented PowerOCR, which is extremely accurate: https://github.com/microsoft/PowerToys/blob/main/src/modules/PowerOCR/PowerOCR/Helpers/ImageMethods.cs

I am was in same situation as you. For now I find that use build-in solution is fine. works for all languages. Currently I have been tested for English, Chinese and Russian. 

Quick install power tools for windows is cmd command:
`winget install --id Microsoft.PowerToys`

**Comment by pota2dev** [comment]
I've also noticed PowerToys OCR is much more accurate for whatever reason. I've switched to it long ago.
