### ISSUE TITLE
Allow upload from history

### ISSUE THREAD

**Issue by CBenni** [ShareX/ShareX#709]
The current history does not allow the user to upload an image he created, but did not upload back then - you need to open the folder, drag+drop the image into the main window and then upload from there, which is slightly annoying (?)

I thought ShareX saved the main window task list back in the day? Currently it clears the list of recent tasks on startup, it would be awesome if that list could be saved for easy future access? I mean this list: 
![image](https://cloud.githubusercontent.com/assets/3787686/7797640/5463658c-02ef-11e5-9908-e0e09025d5a4.png)

**Comment by Jaex** [comment]
From history you can copy file and then press clipboard upload hotkey. I'm not planning to duplicate every single right click menu option of main window to history too.

What is point of saving two different history. If I save that then why bother also saving to history. If you want recent list then history is made for that purpose.
