### ISSUE TITLE
Any solution for HDR screenshots on chrome? I use HDR10 color profile and screenshots are taken too white saturated 

### ISSUE THREAD

**Issue by wallyhenderson** [ShareX/ShareX#7090]
Any solution for HDR screenshots on chrome? I use HDR10 color profile and screenshots are taken too white saturated 

Thanks in advance

**Comment by 1serjr1** [comment]
same for me, HDR is becoming widely in demand and it will be nice to have compatibility with it

**Comment by JFPCreations** [comment]
HDR is not supported for now.
Have a look at: https://github.com/ShareX/ShareX/issues/6688
