### ISSUE TITLE
The "Show cursor" toggle in the system tray menu should also toggle it for screen recordings and GIFs

### ISSUE THREAD

**Issue by robmonte** [ShareX/ShareX#7092]
Right-clicking the system tray icon and turning on "Show cursor" only turns it on for screenshots. Recording the screen into a GIF or a video still does not show the cursor with this enabled.

For reference, the toggle at the bottom here:
![image](https://github.com/ShareX/ShareX/assets/17119716/ae3a42b7-f8b8-4e0f-aae4-697f4e23067a)

**Comment by inson1** [comment]
I would add second option for that imho
