### ISSUE TITLE
Add a "Capture audio" and toggle to the system tray menu

### ISSUE THREAD

**Issue by robmonte** [ShareX/ShareX#7093]
In the system tray menu there is a toggle to turn on and off the cursor from showing in captures. Next to this should also be a toggle for capturing audio in screen recordings. Currently you have to dig you many layers of settings windows to toggle audio recording, and if you want to flip back and forth between that setting it is extremely tedious.

For reference, adding this option to the bottom here:
![image](https://github.com/ShareX/ShareX/assets/17119716/90e610a2-04ce-4f34-80ad-84ead314af04)

**Comment by robmonte** [comment]
Any way this can be reopened and considered? Swapping between capturing audio and not capturing audio during screen recordings is _excessively_ bad UX currently. It requires deep menu digging and I'd argue that wanting to switch between these two modes often is borderline unreasonable.

**Comment by trashkev** [comment]
this is very old but I think this is still very much needed!
I'm often wanting to record with or without audio, and needing to create a custom task for this is pretty obtuse UX.
A simple toggle or even a new default task would be amazing :)

**Comment by robmonte** [comment]
@Jaex Any chance this can be reopened?
