### ISSUE TITLE
How to record sound ?

### ISSUE THREAD

**Issue by toonetcreation** [ShareX/ShareX#7097]
Hi,

When I try to record my screen works fine, but sound is not captured.
how to do that?

Thanks
L.

**Comment by inson1** [comment]
Your sound or sound of the screen?

**Comment by toonetcreation** [comment]
My sound only, from my microphone.

**Comment by inson1** [comment]
If you want only one source that is easy.
![Untitled](https://github.com/ShareX/ShareX/assets/75314629/fae04d65-1957-46c6-8ea0-c046fcd48d7d)

**Comment by toonetcreation** [comment]
Ok thanks for the feedback, I check this out and I Come black to you.

**Comment by toonetcreation** [comment]
Ok works fine thanks.
