### ISSUE TITLE
Akari Link Shortener support

### ISSUE THREAD

**Issue by CodyMKW** [ShareX/ShareX#710]
I just found ShareX and love it I would love if it had support for Akari Link Shortener the API is at https://api.waa.ai/ if that helps

**Comment by Scrxtchy** [comment]
Regex Is a pain
```
{
  "Name": "Akari",
  "RequestType": "POST",
  "RequestURL": "https://api.waa.ai/shorten",
  "FileFormName": "",
  "Arguments": {
    "url": "$input$"
  },
  "ResponseType": "Text",
  "RegexList": [
    "short_code\\\":\"(?<code>.+)\","
  ],
  "URL": "https://waa.ai/$1,code$",
  "ThumbnailURL": "",
  "DeletionURL": ""
}
```

It's a custom destination script of course
You can add more arguments based on the API you linked, like your account api key
Using private urls returns a more diverse response, so I'll attempt to create an expression in case you prefer private urls (Which are also deletable within sharex)

![DesinationSettings](http://7proxies.pw/i/2015/06/15-06-06_18-12-53.png)

**Comment by Scrxtchy** [comment]
And here's the uploader for private urls,
I noted that if you do use an API key, you can choose to use a private, so this is what you would want for people using that
I have set private to default below though, which can easily be removed, it's only there because it is the private version

```
{
  "Name": "Akari Private",
  "RequestType": "POST",
  "RequestURL": "https://api.waa.ai/shorten",
  "FileFormName": "",
  "Arguments": {
    "url": "$input$",
    "private": "1"
  },
  "ResponseType": "Text",
  "RegexList": [
    "short_code\\\":\"(?<short>\\w+)\\\\\\/(?<priv>\\w+)\"",
    "delete_hash\\\":\"(?<delhash>\\w+)\","
  ],
  "URL": "https://waa.ai/$1,short$/$1,priv$",
  "ThumbnailURL": "",
  "DeletionURL": "https://waa.ai/delete/$1,short$/$2,delhash$"
}
```
ShareX isn't storing the deletion urls into history mind that.
Can't find any already made scripts to test off though

**Comment by Jaex** [comment]
ShareX storing deletion urls into history.

**Comment by Jaex** [comment]
Added it to here: https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#waaai
