### ISSUE TITLE
have bug

### ISSUE THREAD

**Issue by sekretneyslysby** [ShareX/ShareX#7103]
![image](https://github.com/ShareX/ShareX/assets/88547179/cd65faa0-cda5-450d-a81e-8d964f35b493)
I have three monitors. where I have three workspaces. On my 2 workspace I always get this error after a while. When I delete workspace 2, the error goes away, but not for long. always shows up after a while. The point is that the capture area (as I understand it) moves off somewhere.

Please sort it out.
 
win 10 ame
Windows 10 Pro
Build 19041 .vb release,191206-1406
[ShareXPortable_15.0.paf.exe](https://portableapps.com/downloading/?a=ShareXPortable&s=s&p=&d=pa&n=ShareX%20Portable&f=ShareXPortable_15.0.paf.exe)

**Comment by TZilba** [comment]
Exclude sharex.exe from Fancyzones in Powertoys:
![image](https://github.com/ShareX/ShareX/assets/112347659/2b350c11-0e9e-4e88-a05b-091fb2a5c799)

**Comment by sekretneyslysby** [comment]
Wow! It is realy healpfull. Great Thanks!
