### ISSUE TITLE
Capture region starts in the wrong position

### ISSUE THREAD

**Issue by julianoventola** [ShareX/ShareX#7106]
Capture region starts in the wrong position, not only capture region, but record screen also start in the wrong position. I took this screen shot to show how it shows the pre selected region to capture. I'm using win 10, i did not install anything new, but thinking about any updates that may have caused it, i could be nvidia or powertoys. Could you help me please?

It was full screen*
![image](https://github.com/ShareX/ShareX/assets/28475558/cead834a-6bd0-4565-87a8-f6cfbdaf3351)

**Comment by ashaikh** [comment]
@julianoventola I found the root cause for the developers since this is a very hard one to track down. If you are using the latest powertoys go to Mouse Utilities and turn off Enable Mouse Highlighter, this will fix the issue immediately.

**Comment by julianoventola** [comment]
@ashaikh 
Yes i am using PT! I turned off mouse highlighter just to make sure it would work properly, thank you very much!
