### ISSUE TITLE
Screen recording applies `-deadline realtime` to VP9 even when "record using lossless" is enabled.

### ISSUE THREAD

**Issue by sisby-folk** [ShareX/ShareX#7107]
[Documented here](https://trac.ffmpeg.org/wiki/Encode/VP9#DeadlineQuality).

Solution is probably to just add a dropdown like there is for x264 preset between good/best/realtime.

This is more of a problem than it needs to be because the `additional command line arguments` field is added to the parameters before the built in default deadline, so I couldn't override it (assuming ffmpeg supports declaring a param twice)

![image](https://github.com/ShareX/ShareX/assets/55819817/77331e87-68a4-405d-ae7c-d9a96c32ecdb)

**Comment by Jaex** [comment]
I check now, `-deadline realtime` is not included when "Record using lossless" is enabled.
