### ISSUE TITLE
Question: record gif as mp4 without audio

### ISSUE THREAD

**Issue by lynrayy** [ShareX/ShareX#7124]
How can i record GIFs as video without audio track? Telegram uses mp4 without audio as "gif" and this is most usable app for me. Is there custom tasks or something for do that?

**Comment by Mace68** [comment]
This is how I set it up for that:
https://i.imgur.com/CMSuSWn.png

**Comment by lynrayy** [comment]
[Mace68](https://github.com/Mace68) I want to save both of functions and have gif recorder and video recorder at the same time

**Comment by Mace68** [comment]
I'm not sure of any other ways, I just downloaded it a couple of days ago.
