### ISSUE TITLE
[Feature Request]: Remove / add autostart?

### ISSUE THREAD

**Issue by pierrelasse** [ShareX/ShareX#7126]
I might be blind but if not, it would be cool to be able to add or remove the autostart.

What i tried is to put the app in autostart but then i have it always in my face on startup.
Reinstall also did the same thing as above.

**Comment by clownmoney** [comment]
If I understand you correctly; you need to just go to **Application Settings** -> **Integration** and uncheck **Run ShareX when Windows starts**.
Personally mine doesn't open the main window, which is what I assume you mean, so you may need to check **Minimize to tray on start**. That option is under the **General** tab.

**Comment by pierrelasse** [comment]
Thanks.
