### ISSUE TITLE
Am I missing "annotate video"?

### ISSUE THREAD

**Issue by rebop** [ShareX/ShareX#7134]
Cannot seem to find a way to add arrows, text, boxes etc either during or after a video capture. Does this exist?Been searching for a screen recorder that provides this.

Thanks.

~Bob

**Comment by rebop** [comment]
Thanks for the reply....

**Comment by Xenthys** [comment]
You're welcome, please let us know if you have any further question!

**Comment by rebop** [comment]
Hah!

 

How about the one not answered? Is there no way to annotate a video either while recording or after?

 

Thanks.

**Comment by DasDunkel** [comment]
Videos cannot be annotated by/within ShareX, you'll either need to use a different tool, like KdenLive, or find an alternative recording tool

**Comment by rebop** [comment]
Thanks. I shall keep the search to see what I can find.
