### ISSUE TITLE
ShareX 15 Is Reported As Infected With A Trojan And Ransom Code

### ISSUE THREAD

**Issue by tomaszs** [ShareX/ShareX#7135]
https://www.virustotal.com/gui/file/b95166183ae61504728c5667c71743a978829b98ed11bea6c17d2c338d2e86e7

![image](https://github.com/ShareX/ShareX/assets/834977/3e28b461-31b0-48b8-bb0c-c97bddfc0ad5)

https://www.virustotal.com/gui/file/c3bc97e9fb8d107e92cb494b50f842fccafbc9fd810588a1b635aee4dbe90bc1

![image](https://github.com/ShareX/ShareX/assets/834977/8779eea4-b5b3-49aa-ab1f-dbd8664688d3)

Reported issues by Virus Total are:

Trojan.Malware.300983.susgen
Ransom.Win32.Sabsik.sa

respectively for the setup and standalone version by Gridinsoft and MaxSecure

Version 14 at the time I've downloaded it yesterday was clear, but is unable to download ffmpeg for video and GIF features.

Great work developing the application. Hopefully these security issue reports can be resolved

**Comment by jkrejcha** [comment]
Perhaps related to #6700 and #5080?

**Comment by stevenffrench** [comment]
I have the same issue with the latest DEV build and Windows Defender.  It's being flagged as Trojan:Win32/Wacatac.B!ml
<img width="556" alt="image" src="https://github.com/ShareX/ShareX/assets/65608383/400e98a2-76f3-4424-9756-4700436ddd16">

**Comment by YorkieFl** [comment]
Just want to tag onto this. Once installed certain exe files within the ShareX install folder are also picked up by VirusTotal as having issues.

Such as NativeMessaging Host 
https://www.virustotal.com/gui/file/9740b5b454f211768e15ac4a56106579e64c494e23467981a3abbb77f78ee7e3/detection
![image](https://github.com/ShareX/ShareX/assets/44997756/0b9b1da3-421b-4029-b32f-497e0e8de8f5)

and Recorder-Devices-setup.exe 
https://www.virustotal.com/gui/file/9c6639b091af643196361c14295640a347be1882e2dcc5d8959f43d93cbe821f
![image](https://github.com/ShareX/ShareX/assets/44997756/07490725-ed9a-4e1a-b649-0a5d698e84a0)


wouldn't mind but the internal IT at my place of work won't let me use it until its "clean"

**Comment by Jaex** [comment]
> I have the same issue with the latest DEV build and Windows Defender. It's being flagged as Trojan:Win32/Wacatac.B!ml <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/65608383/290193081-638b2f5b-b5e5-4aad-9200-e31aef562fe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzQ5OTQsIm5iZiI6MTcwNTg3NDY5NCwicGF0aCI6Ii82NTYwODM4My8yOTAxOTMwODEtNjM4YjJmNWItYjVlNS00YWFkLTkyMDAtZTMxYWVmNTYyZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDIyMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzViZmJmZTljNDE5NGMwZTg3MWFhZTMwNWJkNzAzY2I2Mzc0YTY4ZmYwNjYyMjU4NzMzOTBkNjM0MTE0ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TzpRdYWJCiqh1YT2PBcnNQq2z6VXquwBbKo-ONnOUd8">

Windows Defender team response:

![](https://jaex.getsharex.com/2024/01/chrome_g2qgSmfDrY.png)

**Comment by piovis2023** [comment]
So - is this malware?

**Comment by jack-hermanson-canvas** [comment]
No it is not malware. This was a false positive.
