### ISSUE TITLE
Better onedrive url link

### ISSUE THREAD

**Issue by welpdx** [ShareX/ShareX#7139]
As mentioned in #5386 and #5005

When uploading an image or file, it gives an url that is in this format
https://domain-my.sharepoint.com/:i:/g/personal/name/randomstringslikeEbzkAGAAp5xKmKkYv2LBV0YBdGmVDw5lC2fa-hEMOp9zCw
And if you click on it, it brings you to:
![image](https://github.com/ShareX/ShareX/assets/30542416/578205b4-b569-48a3-aab9-2df57e9f0a56)

If you click on, view original, you are brought to a direct link to the png, with a format like so:
https://domain-my.sharepoint.com/personal/name/Documents/Documents/ShareX/Screenshots/231108_2164_chrome.png

We like the latter. Please consider this tyty.

**Comment by campbell-reid-displayr** [comment]
I got tired of messy SharePoint URLs, so I built a clipboard tool that automatically cleans them up when you copy them. It runs silently in the background and replaces long redirect links with the cleaner direct versions.

https://github.com/campbell-reid-displayr/ClipboardCleaner
