### ISSUE TITLE
A suggestion for a new feature, Url custom proxy

### ISSUE THREAD

**Issue by OuOumm** [ShareX/ShareX#7140]
I hope that after uploading the image, the obtained address can be modified to my own custom proxy address.

For example, after uploading, the copied URL is a custom proxy address

Before Customization:

> https://example.com/img.png

After customization:
> https://proxyaddress.com/img.png

or

> https://proxyaddress.com/?https://example.com/img.png

**Comment by Jaex** [comment]
Like this?

![](https://jaex.getsharex.com/2023/11/ShareX_suXQNoTQVU.png)

**Comment by OuOumm** [comment]
> Like this?
> 
> ![](https://camo.githubusercontent.com/9a306f22c970ec57d1904929e6882d223672ad117906dcfb3e4c696284a7982f/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032332f31312f5368617265585f737558514e6f545156552e706e67)

ohhh,yes！！！
