### ISSUE TITLE
PersonalPath.cfg Error

### ISSUE THREAD

**Issue by hellosputnik** [ShareX/ShareX#715]
I am trying to change the ShareX personal folder, but upon exiting, I get an error that says "Can't access to "C:\Program Files\ShareX\PersonalPath.cfg" file. Please run ShareX as administrator to change personal folder path.

I run as the program as admin and the same error message appears. I am running 64-bit Windows 8.1 and using the latest version of ShareX. I cannot find the file "PersonalPath.cfg" in the directory listed above (C:\...\ShareX). However, I do see a PersonalPath.cfg when I list the files in terminal. When I open the file in Vim, the contents are empty.

Here is the screenshot: http://i.imgur.com/KfQEhMZ.png

**Comment by Jaex** [comment]
If your operating system not allows ShareX to create that file in that location then there is nothing ShareX can do about it.

**Comment by hellosputnik** [comment]
For anyone who runs into this problem, be sure to actually close ShareX. By default, ShareX minimizes to system tray when you click on the close button. 

I unwittingly reopened the same instance instead of creating a new one with administrative privileges.
