### ISSUE TITLE
Enhancement Request: <Enter> to start/stop region capture

### ISSUE THREAD

**Issue by Datachange** [ShareX/ShareX#7159]
I just installed ShareX after the Greenshot security vulnerability.
It looks like I get all the feature parity I was looking for, except for one detail.

When manually selecting a region with my mouse, I find that my hand may slip when being super precise.
So, once I have started the manual capture process, I position the cursor to where I want to "start" the manual selection. Then I use the `<Enter>` key to start the "click-drag" process, and then `<Enter>` to end it.

I am requesting a setting (can be off by default) to enable `<Enter>` in this way.

For now, I can continue to use the keyboard to micro-position, (which I love!) but sometimes the mouse keeps acting up as I make those adjustments.

Thank you very much for all your hard work!

**Comment by Korb** [comment]
I'm getting used to ShareX after (proprietary) **Picpick**, and I also miss the ability to specify opposite corners of a rectangular region to take a screenshot using only the keyboard. This is the only way to make a screenshot pixel-perfect, not "rough". This is important in interface design, the ability to create a ready-made template for the layout of a black layout, which you don't have to crop later in a graphics editor.

By the way, it was the inability to quickly move a selected area by one or two pixels that once prevented me from switching from **Adobe Photoshop** to **GIMP**, which also did not provide this ability.
