### ISSUE TITLE
[Request] Use https for links by default (optional)

### ISSUE THREAD

**Issue by Slind14** [ShareX/ShareX#716]
Hey,

I was wondering if there is a way to change the url given from uploads to https by default. So when you make a screenshot which gets instant uploaded to imgur I would like to get the ssl url.

**Comment by Jaex** [comment]
I was wrote reasons here: https://github.com/ShareX/ShareX/pull/689

**Comment by Slind14** [comment]
hmm, you explain that you don't want it due to possible broken images. Does this also mean that there is no and will never be a configurable option, be it a simple tick or regex? I really enjoy using ShareX, this is really the only thing that hinders me, as I always need to add the little "s". (I know it's just a second of work, but when you do hundreds of screenshots a day it get's annoying.)

Anyways thanks for the quick respond.

**Comment by Jaex** [comment]
What is point of using https in Imgur anyway. You entire private images already public because of short predictable urls. Also https won't encrypt url itself.

**Comment by Slind14** [comment]
It's about browsers not loading content from non ssl sites on sites that use ssl.

**Comment by Jaex** [comment]
I can make that After upload -> Copy URL to check if URL starts with "http://" then replace it with "https://" as optional setting. But can't bother adding this same code to each right click copy url buttons.

**Comment by Slind14** [comment]
That would be awesome :+1:

**Comment by Jaex** [comment]
![](https://i.imgur.com/IK7WwwK.png)

It replacing it inside task therefore all URLs including history and copy menu etc. gonna be using https too.

**Comment by Slind14** [comment]
wow, that was faster than I expected, thank you very much. Will it be within the next release? Or are there beta version.. ?

**Comment by Jaex** [comment]
There is no beta version but I compile beta versions when people request.

**Comment by Slind14** [comment]
If a new version containing this will be out soon, I don't wanna trouble you with this. :)
