### ISSUE TITLE
Is it possible to remove the screenshot file restrictions or force ShareX to output the uncompressed original image?

### ISSUE THREAD

**Issue by HS7097** [ShareX/ShareX#7169]
This is my current configuration. If this feature is not currently available, I kindly request the author to consider incorporating it as a new feature in future updates. Thank you very much.
![image](https://github.com/ShareX/ShareX/assets/103177863/f3c880f7-43a6-4f7f-a021-61ac0948b6c0)

**Comment by L1Q** [comment]
In your screenshot, the first checkbox from the top is what you want to uncheck.
I believe this will do exactly what what you are asking for.
Make sure to also check your hotkey configurations for any overrides on top of global task settings.
