### ISSUE TITLE
Unable to store all screenshots and screen captures in a single folder. (Forces all content to go to "screenshots" subfolder)

### ISSUE THREAD

**Issue by raindropsfromsky** [ShareX/ShareX#7181]
I have set the path to D:\Downloads, and left the **Custom screenshots** folder checkbox unselected.

![image](https://github.com/ShareX/ShareX/assets/9047168/a9c491c7-8c7a-42ad-af1c-67273ba58be0)

Even then, Sharex always stores all screenshots and screen capture gifs in **D:\Downloads\Screenshots** subfolder.

Expected behavior: Sharex should not store the content in the **Screenshots** subfolder. It should store the new files directly in the **D:\Downloads** path.

**Comment by DMCS20** [comment]
If you want to store the screenshots in D:\Downloads directly, then you need to check the "Use custom screenshots folder:" box and put in there your desired custom path (D:\Downloads)
