### ISSUE TITLE
ShareX 15.0 - Always uploads to imgur no matter what

### ISSUE THREAD

**Issue by Miraihi** [ShareX/ShareX#7184]
The title. I try to move away from imgur, and chosen another destination for images and videos. Despite that it keeps uploading to imgur and ti drives me crazy. I even wiped ShareX clean and reinstalled and it keeps doing that.

**Comment by Miraihi** [comment]
Update: Fixed it myself by adding upload extension filters at `Task setting -> Upload -> Upload filters`. Like that
![ShareX_G2TLPCnAt3](https://github.com/ShareX/ShareX/assets/63249823/b59ff327-f7f5-4eca-97a8-88b57c536ec6)

**Comment by CubityFirst** [comment]
Just to check, have you accidently changed a hotkey to have "Override destinations" go to imgur instead?

**Comment by Miraihi** [comment]
@CubityFirst I didn't. As I've mentioned, I had completely wiped my data folder to reset everything to default and it still didn't help.
