### ISSUE TITLE
Suggestion: sharex Linux 

### ISSUE THREAD

**Issue by ukcai696969** [ShareX/ShareX#7186]
add sharex linux like .deb files and stuff for chromebooks and linux users.

**Comment by NecRaul** [comment]
ShareX uses Windows Forms as its GUI, you can _technically_ build it in Linux using Mono, but for a project of this scale it doesn't seem plausible. There are decent alternatives to ShareX in Linux.

**Comment by nhoefer2** [comment]
> @ukcai696969 Not as complete as ShareX, but it works. https://github.com/flameshot-org/flameshot

That looks like an application, not a library
