### ISSUE TITLE
[Question] Open dialog after taking screenshot

### ISSUE THREAD

**Issue by Slind14** [ShareX/ShareX#720]
Hey,

in greenshot there was this neat option to open up a dialog (http://i.imgur.com/StTXIFA.png) after a picture was taken before any further option like uploading, saving or opening in editor was performed. Does there anything similar exist with shareX? I assumed it would be at the "after capture tasks" settings but there is nothing:

http://i.imgur.com/Rzvqo9q.png

This is very helpful in terms of:
1. It is a false safe mechanism, so accidental screenshots are not being uploaded. Be it by human error, an animal walking above the keyboard or a bar falling from the roof :D (It happened to me twice already. In this case the buggy mouse jumped across the screen and I captured more than I wanted containing serious data, which I don't want public.)
2. It allows to quickly open the image in the editor in case further information needs to be added, areas be highlighted.., or directly put into the mail, opened with photoshop...

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/06/s13esmGBlu.png)

**Comment by Slind14** [comment]
wow, how did I miss that. Thanks :)
