### ISSUE TITLE
Rectangle capture text alignment bug

### ISSUE THREAD

**Issue by robotboy655** [ShareX/ShareX#721]
When capturing a rectangle and trying to measure the width or height of something on the very right side of the screen, you cannot see the X, Y, Width and Height of the current selection.

Example:
![image](https://cloud.githubusercontent.com/assets/3299036/7959292/8df00fd6-0a00-11e5-80a3-9b54c2d8ebc8.png)

**Comment by Jaex** [comment]
I was aware of that and I was make sure it auto re position itself when it is in top of screen but for right side of screen I couldn't find suitable solution because when I move it to left side of crosshair it would look bad.

**Comment by Jaex** [comment]
Actually it not looked that bad:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/06/b659ZKquPk.png)

**Comment by Jaex** [comment]
Not need to move text to left side of crosshair instead making it align with right side of screen was better solution: https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/06/3GvMHWlAxt.mp4

**Comment by robotboy655** [comment]
Looks good! :+1:
