### ISSUE TITLE
Can not operate the pinned snapshot after opening the setting window.

### ISSUE THREAD

**Issue by sylph520** [ShareX/ShareX#7210]
I made a snapshot and pinned to screen, then I want to change some settings, so I right clicked the taskbar icon and opened the task setting window. Since the pinned snapshot and the setting windows overlapped, I tried to move the pinned snapshot but failed. It seems that, at this moment, I can not operate on this pinned snapshot. After I closed the setting windows, I can move and close the pinned snapshot without issues. Seems a small bug.

**Comment by Jaex** [comment]
Duplicate of #6731
