### ISSUE TITLE
Two feature requests regarding scrolling capture

### ISSUE THREAD

**Issue by vivadavid** [ShareX/ShareX#7240]
Hi,

I'd like to make two suggestions about scrolling capture:

1. Saving scrolling captions as PNG images. I know they can take a lot of space, but it'd be extremely useful if the image format could be specificied somewhere in the settings.

2. Setting a key to stop the scrolling capture (ideally, I'd choose ENTER). Currently, the only way I can think of is press ALT+TAB to switch to a different window.

Thanks in advance!

P.S. The new scrolling capture seems to work much better than the old one: thanks!

**Comment by Jaex** [comment]
1.

![](https://jaex.getsharex.com/2024/01/ShareX_iZGzwOeSFU.png)

2.

![](https://jaex.getsharex.com/2024/01/ShareX_pWgejFy2d2.png)

**Comment by vivadavid** [comment]
Hi, @Jaex ,

Thanks for your quick reply. I tried to find the answer in the settings, but it's obvious that I didn't pay enough attention: there are certainly a lot of items to look at. Sorry for bothering you with things I should have found myself.
