### ISSUE TITLE
Support Multiple Instances of Sharex

### ISSUE THREAD

**Issue by OrcVole** [ShareX/ShareX#7242]
If you work on several desktops, you have to keep closing sharex on one and then re-opening it on another, as sharex currently only permits one instance to run at a time.

Other software, e.g. VLC, permits you to have several VLC windows open simultaneously, on the same or different desktops. 

Sharex should support multiple instances, too.

**Comment by Jaex** [comment]
https://getsharex.com/docs/command-line-arguments#-multi-or--m

**Comment by OrcVole** [comment]
Can this be toggled using the GUI? If not, could a setting be added in the GUI to enable this?
