### ISSUE TITLE
ShareX Dev build problem

### ISSUE THREAD

**Issue by kyleskimo** [ShareX/ShareX#7269]
Downloaded ShareX-15.0.2.317-setup.exe, file size 40,488,472 bytes.
During the installation process, Windows displayed a virus warning and interrupted the installation.
Not sure if it's a false alarm from Windows Defender.

Windows 11 64bit with Microsoft Defender Antivirus - KB2267602 (1.405.418.0)
Detected: Trojan:Script/Wacatac.B!ml
Affected items:
file: C:\Program Files\ShareX\ShareX.exe
file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\ShareX\ShareX.lnk
....

**Comment by Jaex** [comment]
Why your Microsoft Defender is outdated? I can install latest dev build fine without any detection.

![](https://jaex.getsharex.com/2024/02/ApplicationFrameHost_hJVIxPvT7X.png)
