### ISSUE TITLE
Custom Uploader Not Storing Deletion Urls

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#727]
Upon working on the Akari Uploader,
No matter what hack I threw, deletion URLs would not be stored or displayed in the test results
![Bug](http://7proxies.pw/i/2015/06/15-06-06_18-51-04.png)
Furthermore, when testing with the main interface, URLs were not stored into history.xml

I believe this to be a bug in the program, as I have exhausted my testing ability

**Comment by Jaex** [comment]
I tried custom image uploader with Imgur and tested deletion URL. It was showing up in main window and history fine. Probably your deletion URL have something wrong therefore it was not showing up.

**Comment by Scrxtchy** [comment]
You're reproducing on a image uploader, not a URL shortener
I did manage to get deletion urls returning for the file/image

But doing the same on a Custom URL Shortening entry, with even dummy text is not stored
![](http://7proxies.pw/i/2015/06/15-06-06_20-13-44.png)

**Comment by Jaex** [comment]
You were told Akari Uploader not URL shortener therefore I was tested it on image uploader.
Problem is custom uploader actually returns thumbnail and deletion URL but because actual task like image uploader can have its own thumbnail or deletion url therefore shortened url task never copies them to result. So it was intended because deletion url supposed to direct to image, text, file host links.

**Comment by Scrxtchy** [comment]
>Akari Uploader not URL shortener

(/ _ < )
Now that we both understand each other, can deletion please urls be added to the program's functionality? These can be considered useful for some services

Also thanks for adding 53719e8, it will definitely help somewhere down the line

**Comment by Jaex** [comment]
You definitely didn't understood what I said.

**Comment by Scrxtchy** [comment]
I understood that what you're saying is that text and files get deletion links and some get thumbnail links, but deletion was not considered for short URL entries
