### ISSUE TITLE
Request for ShareX Compatibility with Ubuntu Linux

### ISSUE THREAD

**Issue by AxelAlinsky** [ShareX/ShareX#7292]
I am a long-time user of ShareX for its comprehensive screenshot and screen recording capabilities. I normally use ShareX on my office laptop but on my personal I mostly use Linux as my primary operating system and was disappointed to find that ShareX is not currently supported on Linux environments.

I would like to formally request the development of a version of ShareX that is compatible with Ubuntu Linux. This would greatly benefit users like myself who rely on Linux for their daily computing needs but still wish to use ShareX for its superior functionality.

Thank you for considering this request. I, along with many other Linux users, eagerly await the possibility of using ShareX on our preferred platform. Your effort to expand ShareX's availability would be greatly appreciated by the community.

**Comment by Xiarno** [comment]
I 100% agree with that. I use ShareX on the daily. Extremely disappointed that it isn't available nor planned for Linux.
