### ISSUE TITLE
Syntax highling problem with text uploader

### ISSUE THREAD

**Issue by monirulalom** [ShareX/ShareX#730]
I tried uploading PHP files , but it shows as text . Syntax highlighting should be automatic according to file type.

**Comment by Jaex** [comment]
How am i supposed to set that for so many text uploaders and file types. It is too much manual work.

**Comment by monirulalom** [comment]
I see  ShareX 11.1.0  has Option to use file extension for Hastebin syntax highlighting. Syntax highlighting can be set using file extension.

**Comment by Jaex** [comment]
It is actually not ShareX feature bot Hastebin feature. When you give file extension to Hastebin it selects proper syntax highlighting.
