### ISSUE TITLE
Scrolling capture produces regular captions on some somepages

### ISSUE THREAD

**Issue by vivadavid** [ShareX/ShareX#7304]
Hi,

I've been testing the new scrolling capture for a while, and now that ShareX 16.0.0 has been released, I wanted to inform that, though I've obtained better results on some websites, there are others where the scrolling capture doesn't work and the programme just provides a regular caption.

These are two webpages where I found this problem:

https://blogs.elconfidencial.com/cultura/el-erizo-y-el-zorro/2024-01-30/que-dice-exito-global-taylor-swift-sociedad-actual_3819919/

https://elpais.com/tecnologia/2024-03-10/las-ciberestafas-ya-son-el-segundo-delito-mas-denunciado-nadie-esta-a-salvo-de-caer-en-la-trampa.html

Thanks in advance!

**Comment by Jaex** [comment]
https://blogs.elconfidencial.com/cultura/el-erizo-y-el-zorro/2024-01-30/que-dice-exito-global-taylor-swift-sociedad-actual_3819919/
capture: https://jaex.getsharex.com/2024/03/tv12ygeTaL.png

https://elpais.com/tecnologia/2024-03-10/las-ciberestafas-ya-son-el-segundo-delito-mas-denunciado-nadie-esta-a-salvo-de-caer-en-la-trampa.html
capture: https://jaex.getsharex.com/2024/03/KytFbrYpS2.png

Both captured fine for me.

**Comment by vivadavid** [comment]
Thank you for your tests, @Jaex.

I've just done some more testing, and my conclusion is that, at least on certain websites, you need to use the scrolling capture on a big portion of the page.

As shown on the attached clip, the scrolling capture only worked for me in the third attempt. In the first two attempts, the portion of the web apparently wasn't big enough for the programme to realize there were fragments to put together.

https://github.com/ShareX/ShareX/assets/9334287/a549ec4a-4afc-4609-9638-592a05a9ee01

**Comment by Jaex** [comment]
You had animated ads there, it cannot combine images when stuffs changing between shots. Use [uBlock Origin](https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm).

**Comment by vivadavid** [comment]
Thank you for the suggestion, @Jaex .

I've installed the extension, and yet, it seems that there must be a mininum length for the scrolling capture to work.

In the future, if I'm interested in just a portion of the webpage and the scrolling capture doesn't work, I'll just do a bigger portion and then crop as needed.
