### ISSUE TITLE
Why not using same icons in all Menus

### ISSUE THREAD

**Issue by feelnrg** [ShareX/ShareX#7305]
Hello ShareX Team,

Here you can see the correct icons. They are visible in After capture Settings:
![grafik](https://github.com/ShareX/ShareX/assets/45741845/5d7aeb98-74bf-476a-b55c-74157742b7c9)

But unfortunately they are wrong in the Quick Tasks Menu:
![grafik](https://github.com/ShareX/ShareX/assets/45741845/ee88d285-9410-49c5-9d7d-86f7aaea94a7)
The selection would be much easier and quicker for a user to recognize if the correct icon were there too.

Why we cant using the same icons here?

Thank you for your hard work and support. 

Best regards

**Comment by thereddestdog** [comment]
Hah, I was just about to post this issue as well!

![image](https://github.com/ShareX/ShareX/assets/24947579/ae204df8-c6fb-4f8b-8c33-008e57c097bf)

**Comment by ooohaaa** [comment]
@Jaex I have harmonized the icons. May I have write access so i can publish my branch?

**Comment by thereddestdog** [comment]
Thank you! Looks great

![image](https://github.com/ShareX/ShareX/assets/24947579/dd5b6193-3036-4c2a-b2cf-2cbb7e59cc2c)

**Comment by feelnrg** [comment]
Guys thank you so much. in new update it looks very nice now
![grafik](https://github.com/ShareX/ShareX/assets/45741845/89677968-3eb7-4b23-8cbe-2ca29e7738af)
