### ISSUE TITLE
Make a capture video with audio option

### ISSUE THREAD

**Issue by madprops** [ShareX/ShareX#731]
Hi, I'm really impressed with Sharex and I will be donating soon. I was thinking about this feature that might be nice. Usually I capture video (with ffmpeg) without sound, but there are rare occasions where the sound is needed, and to do this I need to go to task settings and enable the sound. It would be nice if there was a capture option that was "Screen recording (with audio)" and "Screen recording (without audio)" Thought that could be useful i don't know. Keep up the good work.

**Comment by Jaex** [comment]
You can customize each hotkeys settings like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/06/8P3lSIUqEQ.png)

So one hotkey can have sound and other not.

**Comment by madprops** [comment]
Wow, thanks for the super quick reply! I didn't know about this, it definitely works, im happy.
