### ISSUE TITLE
Feature request : In main window, when right click screenshot, Copy filepath to clipboard

### ISSUE THREAD

**Issue by shodanx2** [ShareX/ShareX#7316]
I mean in this menu

![image](https://github.com/ShareX/ShareX/assets/10621885/e0834054-d20e-4018-bfa9-69582c692b61)

Please add this option

![image](https://github.com/ShareX/ShareX/assets/10621885/56b13294-9a68-4965-9925-f92fd6a38081)

**Comment by DasDunkel** [comment]
![image](https://github.com/ShareX/ShareX/assets/47669082/333e6f04-eb99-43ee-9974-b9c8cb953347)

**Comment by shodanx2** [comment]
Thank you, 
I had not seen that !
There's even a keyboard shortcut !
Great !
