### ISSUE TITLE
ShareX 16.0.1 detected Trojan HanaLoader in Recorder-devices-setup.exe

### ISSUE THREAD

**Issue by Paradonas** [ShareX/ShareX#7323]
During the 16.0.1 update or following it (not really sure) the software was reported as trojan. It's most likely the same issue or similar as #6700, #5080, ##6694, #4778 and probably a few more meaning this is most likely a false positive. After all, this is open source.

**Comment by DasDunkel** [comment]
New software builds often get flagged as malicious because they're not well known by anti-virus software yet, this should stop after X amount of users have it downloaded/installed, recorder devices specifically will trigger as it includes code used to capture your screen (it's whole purpose)

**Comment by Luttudo** [comment]
happened again

**Comment by DasDunkel** [comment]
> happened again

It's going to happen for every new update if you get in early enough, it's a new file so they're not sure if it's safe, once it's been reviewed by \<insert your favourite antivirus here> the pop-ups will stop, feel free to wait until then
