### ISSUE TITLE
Added "Disable Print Screen key for Snipping Tool" option to setup

### ISSUE THREAD

**Issue by worldsdream** [ShareX/ShareX#7325]
Hi,

I saw that a new feature was added in ShareX 16.0:

Added "Disable Print Screen key for Snipping Tool" option to setup

But I can't seem to find it anywhere in the application. Can you point me where to find it? This will block the default snipping tool when we click the print screen button on our keyboard and open ShareX, right?

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2024/03/SBiz0a9xkF.png)

**Comment by worldsdream** [comment]
Ah like that! Thanks. I had to update and that’s why I didn’t see it.

**Comment by Karbust** [comment]
After installed, where can I find that setting?

Thank you

**Comment by ChirilRussu** [comment]
> After installed, where can I find that setting?
> 
> Thank you

I couldn't find it in settings. So just run the installer again without deleting the app.
