### ISSUE TITLE
Pomf.se has shut down

### ISSUE THREAD

**Issue by kyodjinn** [ShareX/ShareX#733]
Can it be replaced with https://maxfile.ro/

**Comment by nzcv** [comment]
Here's JSON for a custom uploader for another alternative - http://img.loveisover.me
```JSON
{
      "Name": "loveisover.me",
      "RequestType": "POST",
      "RequestURL": "http://img.loveisover.me/upload.php",
      "FileFormName": "files[]",
      "Arguments": {},
      "ResponseType": "Text",
      "RegexList": [
        "\"url\":\"(.+?)\""
      ],
      "URL": "http://a.loveisover.me/$1,1$",
      "ThumbnailURL": "",
      "DeletionURL": ""
}

**Comment by kyodjinn** [comment]
@nzcv Thanks, it worked!

**Comment by 1112e** [comment]
Where exactly do I put that code?

**Comment by nokonoko** [comment]
@kyodjinn to use maxfile replace pomf.se/upload.php with maxfile.ro/static/upload.php

**Comment by Jaex** [comment]
Added them to custom uploader examples page:
[maxfile.ro](https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#maxfilero)
[loveisover.me](https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#loveisoverme)
