### ISSUE TITLE
[Bug] Unexpected closing dialog after screenshot for IME users

### ISSUE THREAD

**Issue by yfdyh000** [ShareX/ShareX#7347]
This issue since https://getsharex.com/changelog#v16.0.0, `Support for closing the window with the Escape key has been added to most of the windows`.

1. Set the "After capture tasks" to show window, and then take capture.
2. Try typing something with [IME](https://learn.microsoft.com/zh-cn/windows/apps/design/input/input-method-editors), such as Chinese, during this period, try pressing ESC to cancel the pending input in IME.
3. The window is closed, the capture and input are completely lost.

In addition, https://github.com/ShareX/ShareX/issues/7346.

**Comment by Jaex** [comment]
#7346 also fixed #7347 I think, but I can't test it.
