### ISSUE TITLE
How can I change the file location of the "ShareX" folder in my Documents folder?

### ISSUE THREAD

**Issue by CH0NZA** [ShareX/ShareX#7361]
In the settings menu of the app, ShareX has a section called, "paths", In "paths" there is a setting available to change the location of the "ShareX personal folder".

I have tried using the setting to move the "ShareX" folder out of my Documents folder. Once I delete or move the original folder, the app recreates a file called "ShareX" in the Documents folder. Is there a fix for this? If, yes, can you please share the steps with screenshots to avoid any mistake? 

Thanks in advance!

**Comment by L1Q** [comment]
The ``%UserProfile%\Documents\ShareX`` folder is known as [Personal path](https://getsharex.com/docs/command-line-arguments#personal-path).

As per the documentation, you have two options realistically:
- use ShareX as a portable app via ``-portable``/``-p`` command line option or by creating an empty file called "Portable" next to ``ShareX.exe``
- have a setting for personal path defined [in registry](https://getsharex.com/docs/command-line-arguments#personalpath-reg_sz)

Both options will most certainly prevent ShareX from creating ``ShareX`` folder in your ``Documents``.

> The "ShareX personal folder" setting is there to tell normal ShareX installation where to store most user data like screenshots and recordings as those might take significant space on the drive. The setting itself still needs to be saved somewhere, hece the need to create ShareX folder with those settings ``.json`` files in it.

System administrators at job sites need control over some ShareX features like ``DisableUpload`` for security. Windows Registry allows them to configure ``PersonalPath`` even before ShareX is ever installed. Most users should not need to use this radical measure just to avoid a small folder in their Documents.

## Portable
If ShareX Portable suits your needs, you can download the portable version already and keep using it.

## Registry
Here are the instructions for setting ``PersonalPath`` in registry:

1. open the registry editor (press Win+R, type ``regedit``, press Enter)
2. navigate to ``HKEY_CURRENT_USER\SOFTWARE\ShareX`` (create ``ShareX`` *key* under ``SOFTWARE`` as needed)
3. under ``HKEY_CURRENT_USER\SOFTWARE\ShareX``, create new "String value" called ``PersonalPath``
4. modify it and set "Value data" to your preferred path

Should look about like this:
![image](https://github.com/ShareX/ShareX/assets/6942070/fd869a3a-d46f-429d-a95b-1cb66092d3ac)

**Comment by CH0NZA** [comment]
I tried this method and will tell you what I did and update later if it worked. 
- [ x ] Step 1
- [ x ] Step 2, but I had to create the ShareX key
- [ x ] Step 3
- [ x ] Step 4, I chose to make the value data as "C:\Users\antho\OneDrive\Apps\ShareX
