### ISSUE TITLE
Anoxy.se how to inplement ShareX

### ISSUE THREAD

**Issue by zilveer** [ShareX/ShareX#737]
Hello, how Can I implement www.anoxy.se to sharex? 

Please let me know how to proceed. Does anoxy.se need an API for this?

Regards

**Comment by Jaex** [comment]
I added it to here: https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#anoxyse

**Comment by zilveer** [comment]
Oh great,
Thanks for that :)
Is it possible to add it to the file uploaded list as well?

**Comment by Jaex** [comment]
I don't liked it not gives direct link to images.
