### ISSUE TITLE
Doesn't capture transparent window, instead gets underlying screen

### ISSUE THREAD

**Issue by tabletguy** [ShareX/ShareX#7377]
Using cFossSpeed (version 13 - latest paid) set in transparent mode, trying to capture the window of the running program, it, instead, captures the background screen

![image](https://github.com/ShareX/ShareX/assets/2747867/908b4778-2a70-454a-a8f6-e43bfaf16689)

What it actually captured:
![CFosSpeedWindow Capture](https://github.com/ShareX/ShareX/assets/2747867/8c6079b9-292e-4d85-b950-838394938ade)

What I was trying to capture (I added the arrow afterwards by capturing with a different screen capture program)
![2024-04-01 09 54 20](https://github.com/ShareX/ShareX/assets/2747867/06ba2bc4-e725-414d-b31b-047fa1958086)

Using current ShareX 16.01 on Windows 11 Pro 22H2, 32GB memory

**Comment by Jaex** [comment]
It is possible to hide their own window from screenshots:
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity

So they must be doing it on purpose to not cover screenshots.

**Comment by tabletguy** [comment]
I was easily able to do a screenshot with another program -- no changes to
the settings. It's only ShareX that couldn't do the screenshot.

To be clear, I wasn't complaining about not getting the Windows background.
I was pointing out that ShareX did not get the CFos window even though I
selected it directly from the menu.
