### ISSUE TITLE
Showing this Error

### ISSUE THREAD

**Issue by Morphark** [ShareX/ShareX#7385]
System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ShareX.Program.ReadPersonalPathConfig()
   at ShareX.Program.UpdatePersonalPath()
   at ShareX.Program.Main(String[] args)

ShareX 16.0.1

**Comment by MurkyBanana** [comment]
Also getting the same error after trying to install the latest version of ShareX on my new laptop with Windows 11 (23H2) I tried uninstalling and reinstalling multiple older versions, but I get the same error when trying to open ShareX. 

Tried the latest version on a clean install of Windows 10 (22H2) and also on a clean install of Windows 11 (23H2) and didn't get the error popup at all.

Deleted my config files on the Win 11 laptop that originally had the issue and I no longer get the error message, so it's gotta be something in the config causing it.

**Comment by Combinacijus** [comment]
Same issue ShareX 15.0 possible fix: https://github.com/ShareX/ShareX/issues/6919#issuecomment-1593367811
Same issue ShareX 15.0 https://github.com/ShareX/ShareX/issues/7258

**Comment by Morphark** [comment]
> Also getting the same error after trying to install the latest version of ShareX on my new laptop with Windows 11 (23H2) I tried uninstalling and reinstalling multiple older versions, but I get the same error when trying to open ShareX.
> 
> Tried the latest version on a clean install of Windows 10 (22H2) and also on a clean install of Windows 11 (23H2) and didn't get the error popup at all.
> 
> Deleted my config files on the Win 11 laptop that originally had the issue and I no longer get the error message, so it's gotta be something in the config causing it.


I installed the earlier version of the software, and got the update, I no longer encounter this issue.
