### ISSUE TITLE
Two applications are displayed in Windows application startup

### ISSUE THREAD

**Issue by suprunchuk** [ShareX/ShareX#7389]
I installed the build from Microsoft Store version **16.0.1**.
I added this application to Windows startup. After restarting Windows, 2 applications are displayed in my startup in the task manager.

![2024-04-10_15-06-07](https://github.com/ShareX/ShareX/assets/57152612/984f4a8d-7aab-4fa8-974e-ece6111e4b66)

![2024-04-10_15-13-07](https://github.com/ShareX/ShareX/assets/57152612/b02c7cd5-a60a-411f-835f-1422b9c05c64)

**Comment by Combinacijus** [comment]
If in Task Manager you right click and press `Open file location` for both ShareX what are the paths?
Maybe it accidentally got installed in two locations

**Comment by dylanh724** [comment]
I have this issue, too, @Combinacijus + @suprunchuk. One is `ShareX` by `ShareX Team`. The other is `ShareX.exe` with no publisher description.  They also have different startup impacts:

![image](https://github.com/ShareX/ShareX/assets/8840024/08dba9af-796a-46af-be3d-88be13b6bfe0)
