### ISSUE TITLE
Invariant translations

### ISSUE THREAD

**Issue by Shadorc** [ShareX/ShareX#740]
Hi !

In this commit (https://github.com/ShareX/ShareX/commit/1ed4f7e586f52607baf90774eede9806104ead41) you removed all the "Invariant" comments.
Is that deliberate ? For I do not think translate site names can be usefull but I prefer ask.
And others String like "...", "http://", "/api/1/upload", ect... They can also be invariant, no ?

It's a matter of no great importance but I preferred to be sure before I change or translate anything.
(I can take care of redefining these String to invariant if it wasn't wanted)

Thanks !

**Comment by Jaex** [comment]
Everytime I change something in Designer these invariant fields keep removing, so I'm tired re adding them each commit.

**Comment by Shadorc** [comment]
Oh okay I understand ...
Thank you for the quick response.
