### ISSUE TITLE
Unhandled Exception on Colorpicker tool with multiple monitors

### ISSUE THREAD

**Issue by jnko** [ShareX/ShareX#741]
When I choose the colorpicker tool and move the mouse to another monitor, left of the the main monitor I get an unhandled exception:

2015-06-16 12:07:10.302 - Unhandled exception:
System.ArgumentOutOfRangeException: Der Parameter muss positiv und kleiner als die Breite sein.
Parametername: x
   bei System.Drawing.Bitmap.GetPixel(Int32 x, Int32 y)
   bei ShareX.ScreenCaptureLib.RectangleRegion.get_CurrentColor()
   bei ShareX.ScreenCaptureLib.RectangleRegion.DrawMagnifier(Graphics g)
   bei ShareX.ScreenCaptureLib.RectangleRegion.Draw(Graphics g)
   bei ShareX.ScreenCaptureLib.Surface.OnPaint(PaintEventArgs e)
   bei System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   bei System.Windows.Forms.Control.WmPaint(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2015-06-16 12:07:16.301 - ShareX continue.

My system has three monitors:

Mon3    Mon2    Mon1(default)

I assume this would also happen if another monitor is above the main one.

**Comment by Jaex** [comment]
#700
