### ISSUE TITLE
Microsoft Store version attempts to update itself

### ISSUE THREAD

**Issue by MattJeanes** [ShareX/ShareX#7446]
The Microsoft Store version of ShareX at the moment is trying to prompt me to upgrade to 16.1.0 which as far as I can tell it shouldn't be doing because its updates are managed by the store.

Pressing Yes and accepting the upgrade installs another version of ShareX alongside the store version.

I can workaround the issue of course by just pressing no and/or waiting for the store version to be up to date but figured it shouldn't be doing that.

![image](https://github.com/ShareX/ShareX/assets/2363642/b985b80d-b855-47ba-8165-13c9a69c4698)

![image](https://github.com/ShareX/ShareX/assets/2363642/9301d345-3920-4e18-9474-5a0eeb7488cd)

Edit: I can now see that the update has been pushed so should prevent it happening until the next patch now 😄 

Cheers

**Comment by Jaex** [comment]
It is already fixed in version 16.1.0.

**Comment by MattJeanes** [comment]
Ah okay great, I did check the release notes but doesn't say about this. Great to hear 🙂
