### ISSUE TITLE
Sharex Startup Auto Capture after Restart PC

### ISSUE THREAD

**Issue by rafomac** [ShareX/ShareX#746]
Hi Friends,

I really loved your application sharex, its really useful application for me.

can you please instruct me how to add Start Auto Capture to System startup ?

i  tried -startautocapture key for startup file, but its works fine Till we restart.

but once we restart its shows Like attached Images,

Actually i want : 

"it should Automatically Capture fullscreen every Hour even if it restart or not "

So in  Auto Capture parameter i Set as 1st and 2nd
![1](https://cloud.githubusercontent.com/assets/11643373/8348922/8b939480-1b29-11e5-8d39-09b8deca1234.png)
![2](https://cloud.githubusercontent.com/assets/11643373/8348921/8b92ff8e-1b29-11e5-98b2-70f22b72ee55.png)
![3](https://cloud.githubusercontent.com/assets/11643373/8348920/8b90c494-1b29-11e5-8e33-1ca8404d5d93.png)

 Image but after Restart it became like 3rd Image. and it not capturing screenshot.

i'm eagerly waiting for your reply.

Thank you so much.
ABDUL RAFEEQUE
rafomac@rafomac.com

**Comment by Jaex** [comment]
I added -silent -startautocapture to desktop shortcut and opened it from shortcut and it was taking captures fine. Not sure what gonna be different when using from startup.

**Comment by rafomac** [comment]
That is the problem if we restart.

Can you restart pc and try ?

then you can see its empty

**Comment by Jaex** [comment]
I don't need to restart pc it won't change anything. Did you closed ShareX normally for settings to save?

**Comment by rafomac** [comment]
yes, its works fine till i restart.

and please fix this for me.

If this Fix 100% then i will donate for your Project.

Thanks a lot

**Comment by Jaex** [comment]
I can't fix non existent problem.

**Comment by rafomac** [comment]
No... If its showing Empty after restarting means there is a Problem in this application.

Kindly resolve this

**Comment by Jaex** [comment]
How am I supposed to fix something which I works for you??

**Comment by rafomac** [comment]
waaoo... Thats great Thanks... I am waiting for that....

**Comment by Jaex** [comment]
You waiting for what?!?!

**Comment by rafomac** [comment]
Please don't Close.... Still Its not fixed ? i was waiting for your reply... Sorry if you feel bad.
