### ISSUE TITLE
Sharex crashes everytime i stop a video capture being uploaded through ftp.

### ISSUE THREAD

**Issue by madprops** [ShareX/ShareX#747]
This happens with videos, but maybe it happens with any file. 

If a video is uploading and i stop it, after a while it will show an error message and quit.

Here's the output:

![2015-06-25_19-00-08](https://cloud.githubusercontent.com/assets/206498/8368808/98e0ff90-1b6c-11e5-8013-1cdcdfe7cbef.jpg)

**Comment by Jaex** [comment]
Because I don't have SFTP account I can't test am I fixed it. Would you like to try it?
