### ISSUE TITLE
Vid.me Support

### ISSUE THREAD

**Issue by tjkhaled** [ShareX/ShareX#750]
https://docs.vid.me/

**Comment by Scrxtchy** [comment]
I used the Video - Upload API for this
https://docs.vid.me/#api-Video-Upload, so extra parameters are listed there.
However, all content with this is anonymous, and lacks filenames

Remove 'private' argument if wanted, it will hide uploaded videos/gifs from lists/search engines
```
{
  "Name": "vid.me",
  "RequestType": "POST",
  "RequestURL": "https://api.vid.me/video/upload",
  "FileFormName": "filedata",
  "Arguments": {
    "private": "true"
  },
  "ResponseType": "Text",
  "RegexList": [
    "\"url\":\"(?<code>\\w+)\""
  ],
  "URL": "https://vid.me/$1,code$",
  "ThumbnailURL": "",
  "DeletionURL": ""
}
```

If implementation of users is to be considered, it will require full implementation with auth similar to Imgur_v3, 
https://docs.vid.me/#api-Auth

**Comment by Jaex** [comment]
Added Scrxtchy's codes to here: https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#vidme
