### ISSUE TITLE
[Feature Request] - Clear all pinned screenshots option

### ISSUE THREAD

**Issue by nickvgh** [ShareX/ShareX#7518]
Hello, I would like to request a menu option to clear all pinned screenshots.

I am a user who utilizes the sharex app to pin multiple screenshots for specific tasks that last up to 60 seconds per each individual task. And as each task is completed, I right click each pinned screenshot to clear them off the desktop and start over when I initiate a new task.

So for a user like myself who has a similar task makeup, having an option to clear all pinned screenshots at once (for me, via hotkey) would provide an immense boost to quality of life and production for my day-to-day - rather than having to spam click and clear through multiple screenshots per each task.

Thank you!

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/commit/0cd5d1a2b02f64cd30fc6bf76a68857609335a76
