### ISSUE TITLE
Scrolling Capture not working properly with Arc Browser

### ISSUE THREAD

**Issue by joetomasone** [ShareX/ShareX#7526]
Scrolling capture in Arc Browser scrolls the window only once, and therefore does not complete the capture on longer web pages. 

The same instance of ShareX captures the same web page properly under Chrome. 

Arc Browser 1.10.0.

**Comment by Jaex** [comment]
Try dev build.

**Comment by joetomasone** [comment]
Works properly in the Dev build.   Thanks for the suggestion!
