### ISSUE TITLE
Need adjustable menu bar

### ISSUE THREAD

**Issue by delacroix01** [ShareX/ShareX#753]
Hi, I've recently started using ShareX and I'm liking it so far. The only one thing that seems inconvenient for me is that the menu bar isn't adjustable. Because I set font size larger than Windows' default, some button labels are not fully displayed as shown in the picture below, and so I'm opening this thread as a suggestion for improvement. It'll be perfect if I can adjust the size of this bar in future builds. Thanks.

![sharex_9 10 1_2015-06-29_06-44-20](https://cloud.githubusercontent.com/assets/13091547/8398872/5c471892-1e2a-11e5-8fbd-21785daa1697.png)

**Comment by Jaex** [comment]
I was considered it before but couldn't add it because every language have different menu size for their texts to fit and if I make menu size automatically fill empty space then I can't make languages to have different size automatically because that auto sizing will change menu size automatically.

**Comment by davidruhmann** [comment]
Rather than specifying an absolute menu size for each language in the resource files that cannot adjust to user preferences, why not automatically adjust to the size of the menu contents?

Just use the PreferredSize property of the tsMain control like so.  Also added a minimum height adjustment to prevent menu items from being hidden.

```
private void LoadSettings()
{
    ...

	// Adjust the menu width to the items
	tsMain.Width = tsMain.PreferredSize.Width;

	// Calculate the required height to view the whole menu
	int height = Size.Height + tsMain.PreferredSize.Height - tsMain.Height;

	// Set the minimum size of the form to prevent menu items from hidding
	MinimumSize = new Size(MinimumSize.Width, height);

	if (Program.Settings.RememberMainFormSize && !Program.Settings.MainFormSize.IsEmpty)
	{
		Size = Program.Settings.MainFormSize;

		if (!isPositionChanged)
		{
			StartPosition = FormStartPosition.Manual;
			Rectangle activeScreen = CaptureHelpers.GetActiveScreenBounds();
			Location = new Point(activeScreen.Width / 2 - Size.Width / 2, activeScreen.Height / 2 - Size.Height / 2);
		}
	}
	else
	{
		// Adjust the size to the minimum if not loaded
		Size = new Size(Size.Width, height);
	}

    ...
}
```

**Comment by Jaex** [comment]
Because I was tried many things for automatically resize menu and all of these tries was giving not perfect sizes. Are you sure that your codes also works when in different language not set to proper size in codes and left it in default english size?

**Comment by davidruhmann** [comment]
So I changed the language in ShareX to German and also changed the Menu text size in Windows to 12 from 9 and here are the results with my code:

__Settings__
![display_2015-08-13_22-15-22](https://cloud.githubusercontent.com/assets/2963122/9266643/93d2c9d4-4209-11e5-9c80-afec7e12bd42.png)


__12__
![sharex_10 2_beta_2015-08-13_22-14-34](https://cloud.githubusercontent.com/assets/2963122/9266612/1e0f382c-4209-11e5-998f-db3879c40f4a.png)

__9__
![sharex_10 2_beta_2015-08-13_22-19-36](https://cloud.githubusercontent.com/assets/2963122/9266637/739eb614-4209-11e5-90ae-44a5917aa9be.png)


Note that there are some additional changes like the menu separators that are visible in the screenshot, but not included in my pull request.

Let me know if there are any other specific scenarios to run through.

**Comment by davidruhmann** [comment]
The only issue encountered (existing issue before my changes as well) so far is when changing the Menu size in Windows while the application is open, the menu size does not adapt.  Would need to handle this event, but that would be a separate pr I think.

__12 to 9__
![sharex_10 2_beta_2015-08-13_22-19-24](https://cloud.githubusercontent.com/assets/2963122/9266675/13da09a8-420a-11e5-8e47-c875a6a315e9.png)

__9 to 12__
![sharex_10 2_beta_2015-08-13_22-24-58](https://cloud.githubusercontent.com/assets/2963122/9266694/51142ee8-420a-11e5-8c49-59dc572461bb.png)

**Comment by Jaex** [comment]
I removed all languages custom menu sizes and tried your code and all languages was working good.
Testing with different DPI will be better than just changing menu sizes I think.

**Comment by davidruhmann** [comment]
__150% and 12__
![sharex_10 2_beta_2015-08-14_08-23-08](https://cloud.githubusercontent.com/assets/2963122/9274844/a73193f2-425e-11e5-8dbc-8d47d1595b36.png)

__150% and 9__
![sharex_10 2_beta_2015-08-14_08-22-14](https://cloud.githubusercontent.com/assets/2963122/9274855/bc888486-425e-11e5-92e4-30122e33a6d4.png)
