### ISSUE TITLE
Anoxy custom uploader won't work

### ISSUE THREAD

**Issue by kyodjinn** [ShareX/ShareX#755]
Here are my settings:
![2015-06-30_09-48-10](https://cloud.githubusercontent.com/assets/12821446/8432287/2bba5f02-1f0d-11e5-8862-42864421c525.png)

As you can see, the test result did not work either. Am I doing something wrong?

Also a side note: http://img.loveisover.me/ has shut down, so you can remove that from the custom uploaders.

**Comment by Jaex** [comment]
I tried Anoxy from examples section and it worked.

**Comment by kyodjinn** [comment]
@Jaex Which file uploader do you think is the best?

**Comment by Jaex** [comment]
I'm using Dropbox with public folder.
