### ISSUE TITLE
[Feature] Antialiasing option for Freehand tool

### ISSUE THREAD

**Issue by Krezzin** [ShareX/ShareX#7584]
As of version 16.1, ShareX still doesnt support edge smoothing for the Freehand tool. Would like to know if AA will ever be implemented?

**Comment by Jaex** [comment]
Result is using AA.

![](https://jaex.getsharex.com/2024/08/chrome_UJA1wxSPES.png)

**Comment by Krezzin** [comment]
@Jaex Maybe I phrased it wrong or dunno, still edges don't smoothen for me like you showed, as you can see:

ShareX
![image](https://github.com/user-attachments/assets/f2aae652-0bb9-4ad3-8aad-4d065d145052)

This is how Greenshare does it, auto-smoothens corners so they dont look jagged as f.

![image](https://github.com/user-attachments/assets/ffe08c3c-b478-4e53-b0ee-4f50cb91fe53)

The way it should be.
