### ISSUE TITLE
Scrolling capture support

### ISSUE THREAD

**Issue by erdihu** [ShareX/ShareX#76]
This enhancement would be great

**Comment by jsmith000** [comment]
That would be awesome! Thanks!

PS: Another software having this feature is DuckCapture (maybe you can get an idea).

**Comment by iluvredwall** [comment]
[Greenshot](http://getgreenshot.org/) is [open source](https://bitbucket.org/greenshot/greenshot/src/3b1c30a78a3f8b1d329912976ec292521f1a395f/Greenshot/?at=master) and has scrolling capture support. Also, it's written in C#.

**Comment by Aokromes** [comment]
Plz, reopen this ticket!

**Comment by Jaex** [comment]
Why? Nobody can make it anyway.

**Comment by Aokromes** [comment]
Well, acording iluvredwall http://getgreenshot.org/ does scrolling capture :) also maybe someone else can do the work.

**Comment by Jaex** [comment]
Read his edit.

**Comment by Aokromes** [comment]
Yeah, but better ie than nothing :P

**Comment by Jaex** [comment]
This issue about scrolling capture not web page capture.

**Comment by Jaex** [comment]
And you can check #748 for ie web page capture.

**Comment by Jaex** [comment]
I added scrolling capture support now.

**Comment by erdihu** [comment]
Awesome, thanks!
