### ISSUE TITLE
Upgrade experience for portable versions is bad

### ISSUE THREAD

**Issue by Atario** [ShareX/ShareX#760]
I've seen several issues entered for this, each time dismissed and closed.

**The problem:  portable versions offer to upgrade, but end up downloading and installing installed version instead.**

**Objection to fixing, number one:  I can't tell if I'm installed or portable.**

Yes you can.  You can use the existing Windows APIs provided for information about installed applications to find out if your product ID is there and has the same path.  Or, since the portable package is a separate one from the install package, you could do something as simple as including a file or setting alongside the .exe that's not there in the install version, and detecting that way.

**Objection to fixing, number two:  I can't copy over myself.**

Effectively, you can.  Renaming a running executable is not an issue in Windows; just rename yourself, download the update, and have the updated .exe check for and delete that renamed old version.  Makes it even more seamless if you set a one-time self-deleting scheduled task to run the new version before quitting the old version; then people won't even have to quit and relaunch manually.

Thanks in advance…

**Comment by Jaex** [comment]
I don't have host etc. to write proper upgrade system for portable version. I'm relying on setup to do its job for normal version and it won't work for portable version therefore portable version don't have auto update system.

**Comment by Atario** [comment]
This makes no sense.  One of the whole points of a portable version is that upgrading is a simple copy operation, not requiring the complexity of a real installer.  So why let that ability go to waste?

Especially considering the *only* reason for this application to exist at all is to simplify the user experience.

**Comment by Jaex** [comment]
You can use normal version if you want auto update support. Portable mainly for use it inside usb drive etc. which won't be auto updated inside usb drive anyway.

**Comment by Atario** [comment]
Why won't it be updated in a flash drive?  Why would someone using it from a flash drive want to be stuck on an outdated version?

**Comment by Jaex** [comment]
I'm not going to waste my whole week to write new installer system for portable.
