### ISSUE TITLE
ShareX 10.0 Screen Recording Gif not work.

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#764]
ShareX 10.0 Screen Recording Gif not work.
Firefox 39
Windows Vista
Not work and then get Error that automatically pops up.
Do I need to make some setting changes. I did no setting changes just got updated to ShareX 10.0
Please fix thankyou.

------------------------------------------------------------------------------------------

ffmpeg version N-66438-g4f4f08e Copyright (c) 2000-2014 the FFmpeg developers
  built on Sep 24 2014 22:26:49 with gcc 4.9.1 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      54.  7.101 / 54.  7.101
  libavcodec     56.  1.101 / 56.  1.101
  libavformat    56.  5.100 / 56.  5.100
  libavdevice    56.  1.100 / 56.  1.100
  libavfilter     5.  1.102 /  5.  1.102
  libswscale      3.  1.100 /  3.  1.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  1.100 / 53.  1.100
[gdigrab @ 03ec8400] Capturing whole desktop as 310x154x32 at (139,256)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1436042702.733892, bitrate: 7640 kb/s
    Stream #0:0: Video: bmp, bgra, 310x154, 7640 kb/s, 5 tbr, 1000k tbn, 5 tbc
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 03ec07e0] using cpu capabilities: MMX2 SSE2Fast SSSE3 Cache64 SlowShuffle
[libx264 @ 03ec07e0] profile High 4:4:4 Predictive, level 1.1, 4:4:4 8-bit
[libx264 @ 03ec07e0] 264 - core 142 r2479 dd79a61 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=2 lookahead_threads=2 sliced_threads=1 slices=2 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=5 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'C:\Users\myusername\Documents\ShareX\Screenshots\2015-07\2015-07-04_13-44-57.mp4':
  Metadata:
    encoder         : Lavf56.5.100
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 310x154, q=-1--1, 5 fps, 10240 tbn, 5 tbc
    Metadata:
      encoder         : Lavc56.1.101 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame=    3 fps=0.0 q=0.0 size=      39kB time=00:00:00.60 bitrate= 537.7kbits/s    
frame=    6 fps=6.0 q=0.0 size=      40kB time=00:00:01.20 bitrate= 270.6kbits/s    
frame=    8 fps=5.3 q=0.0 size=      40kB time=00:00:01.60 bitrate= 203.8kbits/s    
frame=   11 fps=5.5 q=0.0 size=      41kB time=00:00:02.20 bitrate= 151.5kbits/s    
frame=   13 fps=5.2 q=0.0 size=      42kB time=00:00:02.60 bitrate= 131.1kbits/s    
frame=   16 fps=5.3 q=0.0 size=      43kB time=00:00:03.20 bitrate= 109.7kbits/s    
frame=   18 fps=5.1 q=0.0 size=      43kB time=00:00:03.60 bitrate=  97.9kbits/s    
frame=   21 fps=5.2 q=0.0 size=      43kB time=00:00:04.20 bitrate=  84.4kbits/s    
frame=   24 fps=5.3 q=0.0 size=      44kB time=00:00:04.80 bitrate=  74.3kbits/s    
frame=   26 fps=5.2 q=0.0 size=      44kB time=00:00:05.20 bitrate=  68.9kbits/s    
frame=   29 fps=5.2 q=0.0 size=      44kB time=00:00:05.80 bitrate=  62.1kbits/s    
frame=   31 fps=5.1 q=0.0 size=      44kB time=00:00:06.20 bitrate=  58.3kbits/s    
frame=   32 fps=5.2 q=0.0 Lsize=      45kB time=00:00:06.40 bitrate=  57.7kbits/s    
video:44kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.163669%
[libx264 @ 03ec07e0] frame I:1     Avg QP: 0.00  size: 39576
[libx264 @ 03ec07e0] frame P:31    Avg QP: 0.00  size:   164
[libx264 @ 03ec07e0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 03ec07e0] mb P  I16..4: 24.7%  0.0%  0.0%  P16..4:  0.3%  0.0%  0.0%  0.0%  0.0%    skip:75.0%
[libx264 @ 03ec07e0] coded y,u,v intra: 6.0% 5.6% 5.6% inter: 0.2% 0.1% 0.1%
[libx264 @ 03ec07e0] i16 v,h,dc,p: 95%  4%  1%  0%
[libx264 @ 03ec07e0] kb/s:55.84
ffmpeg version N-66438-g4f4f08e Copyright (c) 2000-2014 the FFmpeg developers
  built on Sep 24 2014 22:26:49 with gcc 4.9.1 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      54.  7.101 / 54.  7.101
  libavcodec     56.  1.101 / 56.  1.101
  libavformat    56.  5.100 / 56.  5.100
  libavdevice    56.  1.100 / 56.  1.100
  libavfilter     5.  1.102 /  5.  1.102
  libswscale      3.  1.100 /  3.  1.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  1.100 / 53.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\myusername\Documents\ShareX\Screenshots\2015-07\2015-07-04_13-44-57.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.5.100
  Duration: 00:00:06.40, start: 0.000000, bitrate: 57 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 310x154, 56 kb/s, 5 fps, 5 tbr, 10240 tbn, 10 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[AVFilterGraph @ 003affa0] No such filter: 'palettegen'
Error opening filters!

**Comment by Jaex** [comment]
In "task settings -> screen recorder -> screen recording options" press Download button for get latest FFmpeg version I think you have old version.

**Comment by gotquestions** [comment]
Thankyou but where is download button?

![sharex task settings](https://cloud.githubusercontent.com/assets/8550969/8509743/0da92690-226b-11e5-8c2c-f1cb391e45d7.PNG)

**Comment by Jaex** [comment]
In "task settings -> screen recorder -> screen recording options"

**Comment by gotquestions** [comment]
Okay downloaded succeessfully and it seems to work now thankyou.
But new issues:

For creating a Gif:
1. The start button has no effect. It just automatically starts and I need time to sort myself and think out exactly what procedure I am going to make for the gif so that I can be sure to include every step in order, and be sure that I keep the file size down low by not wasting any time with wasted steps.
What is the point of having the start button if it does nothing and instantly switches to Stop?
Can there be an option to have the gif not start until clicking the Start button?
Can there be a pause button so that I can pause after a step to think out my next step and not record wasted time?

2. After using shareX once, the second time I click on icon in notification bar it does not work. Nothing happens and no menu opens.
I have to click the icon in the taskbar to open the main window, close window, then I can click on the icon  in the notification bar to get menu and function. I must ALWAY EVERYTIME click the icon in the taskbar first, open ShareX window,close window, then click on ShareX icon in notification bar to get function. EVERY TIME.

**Comment by Jaex** [comment]
Uncheck this if you don't want it to auto start:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/KuF0UVvPyi.png)

Even when it auto starting still Start button have reason, it ignores auto start timer and starts, so if you have 5 seconds timer then before this time reach 0 you can force it to start.

I can't add pause because FFmpeg which doing recording not supports it.

Nothing changed in tray menu behavior and it is .NET framework codes which making this tray menu anyway so it can't be to do with ShareX. Still not sure why you have this weird problem.

**Comment by gotquestions** [comment]
1) Uncheck to stop autostart fixed the problem thankyou Jaex !

2)  Thankyou for answer and explanation "FFmpeg does not support Pause".

3) Tray menu problem fixed with computer restart!

**Comment by grofit** [comment]
I get this issue at the moment, but have downloaded the latest version:

```
ffmpeg version N-73633-gdfc5858 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 28.100 / 54. 28.100
  libavcodec     56. 47.100 / 56. 47.100
  libavformat    56. 40.100 / 56. 40.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 21.100 /  5. 21.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[gdigrab @ 0000000004797c20] Capture area (1895,740),(2845,1280) extends outside window area (-1680,-53),(2560,1440)desktop: Input/output error

```
I am using a 3k resolution screen but only wanting to capture a portion of it.

**Comment by Jaex** [comment]
People opened your issue countless times i'm tired repeating same answer people not tired asking same question.

**Comment by grofit** [comment]
I am not sure what answer you are mentioning other than download the latest version, which I did as instructed.

**Comment by Jaex** [comment]
This issue have nothing to do with your issue, as you can see error message completely different. If you searched that exact error message in issues probably you would find many issues. That way I didn't have to repeat same answer every day.

**Comment by grofit** [comment]
that's fine then, close this one and I will see if I can find an answer elsewhere.

**Comment by Jaex** [comment]
This one already closed, I can't re close it :P

**Comment by Jaex** [comment]
This explains your issue better which was opened 3 days ago: #789
