### ISSUE TITLE
Can't record FFmpeg

### ISSUE THREAD

**Issue by rhigosrebel** [ShareX/ShareX#767]
I get this error

ffmpeg version N-64695-gfaafd1e Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul 15 2014 22:09:53 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      52. 92.100 / 52. 92.100
  libavcodec     55. 69.100 / 55. 69.100
  libavformat    55. 48.100 / 55. 48.100
  libavdevice    55. 13.102 / 55. 13.102
  libavfilter     4. 11.100 /  4. 11.100
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
[gdigrab @ 0000000002b3f780] Capturing whole desktop as 1756x988x32 at (81,61)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1436215858.088233, bitrate: 555181 kb/s
    Stream #0:0: Video: bmp, bgra, 1756x988, 555181 kb/s, 10 tbr, 1000k tbn, 10 tbc
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0000000002cbbbe0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 0000000002cbbbe0] profile High 4:4:4 Predictive, level 4.0, 4:4:4 8-bit
[libx264 @ 0000000002cbbbe0] 264 - core 142 r2431 ac76440 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=10 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'E:\Library\Documents\ShareX\Screenshots\2015-07\2015-07-06_21-50-57.mp4':
  Metadata:
    encoder         : Lavf55.48.100
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 1756x988, q=-1--1, 10 fps, 10240 tbn, 10 tbc
    Metadata:
      encoder         : Lavc55.69.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame=    7 fps=0.0 q=0.0 size=    5867kB time=00:00:00.70 bitrate=68660.7kbits/s    
frame=   12 fps= 11 q=0.0 size=   10346kB time=00:00:01.20 bitrate=70626.3kbits/s    
frame=   17 fps= 11 q=0.0 size=   14574kB time=00:00:01.70 bitrate=70227.9kbits/s    
frame=   22 fps= 11 q=0.0 size=   19648kB time=00:00:02.20 bitrate=73161.8kbits/s    
frame=   27 fps= 10 q=0.0 size=   25550kB time=00:00:02.70 bitrate=77519.2kbits/s    
frame=   32 fps= 10 q=0.0 size=   31395kB time=00:00:03.20 bitrate=80370.0kbits/s    
frame=   37 fps= 10 q=0.0 size=   37417kB time=00:00:03.70 bitrate=82844.0kbits/s    
frame=   42 fps= 10 q=0.0 size=   42956kB time=00:00:04.20 bitrate=83785.0kbits/s    
frame=   48 fps= 10 q=0.0 size=   49933kB time=00:00:04.80 bitrate=85218.3kbits/s    
frame=   53 fps= 10 q=0.0 size=   55951kB time=00:00:05.30 bitrate=86481.5kbits/s    
frame=   58 fps= 10 q=0.0 size=   61964kB time=00:00:05.80 bitrate=87518.8kbits/s    
frame=   60 fps= 10 q=0.0 Lsize=   64400kB time=00:00:06.00 bitrate=87927.4kbits/s    
video:64398kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.002602%
[libx264 @ 0000000002cbbbe0] frame I:1     Avg QP: 0.00  size:779182
[libx264 @ 0000000002cbbbe0] frame P:59    Avg QP: 0.00  size:1104477
[libx264 @ 0000000002cbbbe0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0000000002cbbbe0] mb P  I16..4: 77.1%  0.0%  0.0%  P16..4: 21.6%  0.0%  0.0%  0.0%  0.0%    skip: 1.3%
[libx264 @ 0000000002cbbbe0] coded y,u,v intra: 96.6% 96.7% 96.9% inter: 89.9% 90.1% 89.9%
[libx264 @ 0000000002cbbbe0] i16 v,h,dc,p: 47% 52%  0%  0%
[libx264 @ 0000000002cbbbe0] kb/s:87924.44
ffmpeg version N-64695-gfaafd1e Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul 15 2014 22:09:53 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      52. 92.100 / 52. 92.100
  libavcodec     55. 69.100 / 55. 69.100
  libavformat    55. 48.100 / 55. 48.100
  libavdevice    55. 13.102 / 55. 13.102
  libavfilter     4. 11.100 /  4. 11.100
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\Library\Documents\ShareX\Screenshots\2015-07\2015-07-06_21-50-57.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf55.48.100
  Duration: 00:00:06.00, start: 0.000000, bitrate: 87927 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1756x988, 87925 kb/s, 10 fps, 10 tbr, 10240 tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[AVFilterGraph @ 00000000054e0ea0] No such filter: 'palettegen'
Error opening filters!

Can someone help please?

**Comment by Jaex** [comment]
palettegen feature was added new (probably you downloaded it like 2 years ago?) and therefore you need to open FFmpeg options window in Task settings and press Download button there to download new version automatically.

**Comment by rhigosrebel** [comment]
Im in task settings, where is there a download button to get the new version?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/9QYndVOAk3.png)

**Comment by rhigosrebel** [comment]
oh awesome, thanks Jaex. I'll let you know if it works.

**Comment by JustOneMoreBlock** [comment]
Fixed. Yeah I was looking at FFMpeg earlier in the tools directory it did say a year old. Maybe want to add a dependency version checker or something. (Only check if you update the config to force an update so it doesn't have to check/update every time.
