### ISSUE TITLE
Mega folder list error "Attribute deserialization failed: Unexpected character.."

### ISSUE THREAD

**Issue by vavavr00m** [ShareX/ShareX#769]
![mega](https://dl.dropboxusercontent.com/s/53i1euzgtl66025/2015-07-07_10-57-51.png?dl=0)

**Comment by Jaex** [comment]
One of your folder must have non english character, need to know what is it to be able to test.

**Comment by vavavr00m** [comment]
![Mega](https://dl.dropboxusercontent.com/s/0dj6ds4yun6tp7i/2015-07-07_10-54-01.png)

**Comment by Jaex** [comment]
Is there any sub folders?

**Comment by vavavr00m** [comment]
The screenshot is from the list of folders of Mega destination setting. There are many sub folders and too many files in there. These are the suspicious characters I found: ／ 【 】é è ï ü

**Comment by gpailler** [comment]
Node deserialization issue should be fixed with MegaApiClient 1.1.1 (https://github.com/gpailler/MegaApiClient/releases/tag/v1.1.1)
