### ISSUE TITLE
Where is the doc for the cmd `ShareX.exe -ActiveWindow`?

### ISSUE THREAD

**Issue by Norlandz** [ShareX/ShareX#7691]
I remember the cmd `ShareX.exe -ActiveWindow` is for capturing the active window. 
It still works. But where is this basic command in the docs https://getsharex.com/docs/command-line-arguments ? Is this deprecated? 

---
Nvm its in the https://github.com/ShareX/ShareX/blob/master/ShareX/Enums.cs

**Comment by BrycensRanch** [comment]
The source code is not documentation imho

**Comment by Norlandz** [comment]
@BrycensRanch 
its in the doc which has a link ref
I didnt look carefully enough
I edited above comment
