### ISSUE TITLE
Illegal characters in path on launch

### ISSUE THREAD

**Issue by Ckykyro** [ShareX/ShareX#7704]
Hello,

Recently without any change on my end I tried to launch shared and got the following error:

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at ShareX.HelpersLib.FileHelpers.GetAbsolutePath(String path)
   at ShareX.Program.UpdatePersonalPath()
   at ShareX.Program.Main(String[] args)

ShareX 16.1
```

Pressing "continue" does not open the application, and "quit" closes the window.
I have tried reinstalling, changing version, and clearing cache/local files, and reinstalling. I have also tried reinstalling onto different drives and moving/renaming previous screenshot locations. Regardless of version, I get the error upon launch.
I cannot use the program at the time; any help would be appreciated.

**Comment by BrycensRanch** [comment]
Not a contributor but I’d imagine ShareX’s logs would be helpful. They’re usually found in Documents/ShareX/Logs

**Comment by Ckykyro** [comment]
personalpath.cfg somehow got overwritten. clearing the documents folder fixed the issue.
