### ISSUE TITLE
Dropbox File Requests

### ISSUE THREAD

**Issue by vavavr00m** [ShareX/ShareX#771]
More info: https://blogs.dropbox.com/dropbox/2015/06/introducing-file-requests/

Will this be supported if there's an available API?

**Comment by Jaex** [comment]
What you mean supported? What this feature can be to do with ShareX?

**Comment by vavavr00m** [comment]
Upload to someone else's dropbox account without knowing their login credentials.

Try uploading to mine: https://www.dropbox.com/request/Of0wbU7DAoPIzUUpBF0K

**Comment by Jaex** [comment]
I don't see point of implementing this. I'm using Dropbox too for all my uploads and still don't think this will fit ShareX.

**Comment by vavavr00m** [comment]
The only use case I can think of right now is:
I have a 2 GB video and a terrible connection. Now my relatives have to download the video without the complication of joining .rar files and extracting them. The file was split into smaller parts but my internet connection kept on crapping out. So I split the files again into even smaller files to easily upload them to dropbox, for my friend, who lives far away from me and has a better connection, to download, join, extract and upload to my account without me giving my login credentials to friend, so my folks, who are aged 40s-60s, can just hit the download button and play the video. Pardon my English.
