### ISSUE TITLE
Uploads randomly fail with "Could not create SSL/TLS secure channe" when uploading to puush/custom uploader

### ISSUE THREAD

**Issue by petterroea** [ShareX/ShareX#772]
Version: 10.0

Uploads fail randomly on startup, with re-uploading normally working. This happens when uploading screenshots to a custom uploader pointing to puush.me

Full stack trace:
```
Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

Destination export:
```
{
  "Name": "puush.me",
  "RequestType": "POST",
  "RequestURL": "https://puush.me/api/up",
  "FileFormName": "f",
  "Arguments": {
    "k": "---redacted---",
    "z": "poop"
  },
  "ResponseType": "Text",
  "RegexList": [
    "(?<=,)(.+?)(?=,)"
  ],
  "URL": "$1$",
  "ThumbnailURL": "",
  "DeletionURL": ""
}
```

**Comment by ultramancool** [comment]
Hi @petterroea , I work on Up1 and we're experiencing similar issues with our recently merged ShareX support. Our current theory is that this may be related to TLS session resumption on CloudFlare. Puush and Up1 both use CloudFlare. It seems to occur when you perform an upload, wait over 1 hour then attempt another upload. I'll let you know if we discover any further details or a way to fix this.

**Comment by petterroea** [comment]
Yes, that sounds like what i am experiencing as well.

I'l check the times between failed uploads when i am on my Windows box at work again tomorrow and see if i can confirm it as plausible for me too.

Please let me know if you have any updates.

**Comment by petterroea** [comment]
In the meanwhile, is there a possibility to select a number of retries before it gives up?

**Comment by k3d3** [comment]
I don't think that functionality exists right now, but it would certainly be the easiest way to fix this issue. Even if it were just 1 or 2 retries, that would be more than enough.

**Comment by ultramancool** [comment]
Really though, this doesn't occur with hosts not behind CloudFlare, there ought to be a better way to resolve it than retries. Perhaps just dumping the TLS session cache or something.

**Comment by Jaex** [comment]
https://getsharex.com using CloudFlare too and this morning it was not opening for few minutes. They definitely have issues. There is nothing I can do about SSL issues.

**Comment by petterroea** [comment]
The puush uploader(which uses the same upload site i assume) does not fail though, so i don't think it is on CloudFlares side. Either that, or peppy has written some workaround for it. I haven't reversed puush, so i don't know.
