### ISSUE TITLE
Generate Markdown image links.

### ISSUE THREAD

**Issue by bradphelan** [ShareX/ShareX#775]
It would be nice if I could configure ShareX to generate github markdown image URL's

for example. Like

    ![image](https://dl.dropboxusercontent.com/s/yf7my65m3tfkx6c/2015-07-08_16-31-55.gif?dl=0)

![image](https://dl.dropboxusercontent.com/s/yf7my65m3tfkx6c/2015-07-08_16-31-55.gif?dl=0)

Perhapps you could add a custom markup link configuration to be able to generate the markup link as above.

**Comment by Jaex** [comment]
Are you know this?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX_kDOVumUjKm.png)

**Comment by bradphelan** [comment]
Hey super cool :) Thanks
