### ISSUE TITLE
Could not load file or assembly 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=048d311efbeb4e2' or one of its dependencies

### ISSUE THREAD

**Issue by Chocolic** [ShareX/ShareX#777]
System.BadImageFormatException: Impossibile caricare il file o l'assembly 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2' o una delle relative dipendenze. Il modulo doveva contenere un manifesto di assembly.
Nome file: 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2'
   in ShareX.UploadersLib.UploadersConfig.IsValid(FileDestination destination)
   in ShareX.MainForm.EnableDisableToolStripMenuItems[T](ToolStripDropDownItem[] parents)
   in ShareX.MainForm.UpdateDestinationStates()
   in System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   in System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   in System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Chocolic** [comment]
Solved this problem, thanks for ktdd's issue: https://github.com/ShareX/ShareX/issues/776

**Comment by Jaex** [comment]
How that dll not installs correctly I don't understand.
