### ISSUE TITLE
Add teknik support

### ISSUE THREAD

**Issue by arctic5** [ShareX/ShareX#778]
https://api.teknik.io/

**Comment by Scrxtchy** [comment]
I asked a few users in #rice if they would want Ricehalla, it's not hard to do but it is a gallery, and testing may be a bit, out-of-place.
And it is very much a niche

Other than that, here's custom uploaders for everything else,
Arguments can be changed by referring to the api docs
##### Paste
```
{
  "Name": "teknik/paste",
  "RequestType": "POST",
  "RequestURL": "https://api.teknik.io/paste",
  "FileFormName": "",
  "Arguments": {
    "code": "$input$",
    "password": "",
    "title": "%unix"
  },
  "ResponseType": "Text",
  "RegexList": [
    "\"id\":(?<id>\\d+)"
  ],
  "URL": "https://p.teknik.io/$1,id$",
  "ThumbnailURL": "",
  "DeletionURL": ""
}
```

##### File upload
```
{
  "Name": "teknik/upload",
  "RequestType": "POST",
  "RequestURL": "https://api.teknik.io/upload/post",
  "FileFormName": "file",
  "Arguments": {
    "get_delete_key": "yes"
  },
  "ResponseType": "Text",
  "RegexList": [
    "\"delete_key\":\"(?<delKey>\\w+)\"",
    "\"name\":\"(?<name>\\w+\\.\\w+)\""
  ],
  "URL": "https://u.teknik.io/$2,name$",
  "ThumbnailURL": "",
  "DeletionURL": "https://u.teknik.io/$2,name$/$1,delKey$"
}
```

**Comment by Jaex** [comment]
Added them here: https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#teknikio-file-upload

**Comment by dragons4life** [comment]
Don't know why but they don't work, is it just me?

**Comment by Jaex** [comment]
They changed API URL. Updating it now.

**Comment by dragons4life** [comment]
Thanks a lot, quick as hell response too.

**Comment by Jaex** [comment]
Updated them:

https://github.com/ShareX/CustomUploaders/blob/master/teknik.io%20(File%20uploader).json
https://github.com/ShareX/CustomUploaders/blob/master/teknik.io%20(Text%20uploader).json

**Comment by dragons4life** [comment]
Thanks a lot, they work now.

**Comment by Jaex** [comment]
https://help.teknik.io/API
https://github.com/ShareX/ShareX/wiki/Custom%20Uploader

**Comment by dragons4life** [comment]
thanks

**Comment by Jaex** [comment]
Added by #3917
