### ISSUE TITLE
Upload image from URL

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#779]
Often times I have to download/save an image and then re-upload it through Share-X.  It would be very useful for me if there was a button to click which would either copy my URL from clipboard and upload the remote image otherwise show a dialog to input the URL and then have it upload an image from a remote URL.

Many website/apps have this feature now including all the Stack Exchange (StackOverflow) sites and Gmail.

What are your thoughts on such a feature?

Would be really cool if I could have an image file from a remote server, have it;s URL in my clipboard and then simply hit a keyboard combination which would download and upload all in 1 step as if I had uploaded from my PC or from a screenshot!

**Comment by Jaex** [comment]
Both URL upload and clipboard URL upload exists in ShareX. Which downloads first and reuploads it.

**Comment by jasondavis** [comment]
Thats great, I use the software daily for years now and love it, thank you!

Could you kindly explain how to do the upload from URL feature please?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/iX0EvHeKb5.png)

or

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX_gGSMZxaAQd.png)

**Comment by jasondavis** [comment]
oh wow....perfect thank you so much!
