### ISSUE TITLE
Shorten URLs straight from clipboard

### ISSUE THREAD

**Issue by aerouk** [ShareX/ShareX#780]
Since the ability to make short URLs for uploaded files is already in the program, can you make it so you can copy a link, press a combination of keys and it will shorten the link for you?

E.g.
at the moment, doing this will upload the URL in a text document:
![](https://iaero.me/i/vMBZW)

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX_SJYlu6lhXB.png)

**Comment by MaciejLisCK** [comment]
Hi!
What type of Task should I use here?

**Comment by Jaex** [comment]
Clipboard upload

**Comment by MaciejLisCK** [comment]
Whow, that was fast response. Works perfect.

This is how it should looks like:
![image](https://cloud.githubusercontent.com/assets/1531086/23506774/3e1b039e-ff4a-11e6-9c48-a32c0857d365.png)

![image](https://cloud.githubusercontent.com/assets/1531086/23506793/501530a6-ff4a-11e6-9133-7bce68a33fd8.png)
