### ISSUE TITLE
FTP issue: PreviewHttpPath gives an FTP link and FTP client doesn't list files

### ISSUE THREAD

**Issue by vavavr00m** [ShareX/ShareX#781]
PreviewHttpPath gives an FTP link:
I was expecting http://. Is this normal? Is it also possible to add PreviewHttpsPath?
![ftp](https://dl.dropboxusercontent.com/s/he1d7mvkenirmzp/2015-07-09_08-53-07.png)

 FTP client doesn't list files:
![ftp](https://dl.dropboxusercontent.com/s/b6j6g9fjcb5i2qh/2015-07-09_09-12-32.png)

Console log:
9:17:42 AM - 220-FileZilla Server version 0.9.48 beta
9:17:42 AM - 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
9:17:42 AM - 220 Please visit https://filezilla-project.org/
9:17:42 AM - USER ***
9:17:43 AM - 331 Password required for ***
9:17:43 AM - PASS <omitted>
9:17:44 AM - 230 Logged on
9:17:44 AM - FEAT
9:17:44 AM - 211-Features:
9:17:44 AM -  MDTM
9:17:44 AM -  REST STREAM
9:17:44 AM -  SIZE
9:17:44 AM -  MLST type*;size*;modify*;
9:17:44 AM -  MLSD
9:17:44 AM -  UTF8
9:17:44 AM -  CLNT
9:17:44 AM -  MFMT
9:17:44 AM -  EPSV
9:17:44 AM -  EPRT
9:17:44 AM - 211 End
9:17:44 AM - Text encoding: System.Text.UTF8Encoding
9:17:44 AM - OPTS UTF8 ON
9:17:45 AM - 202 UTF8 mode is always enabled. No need to send this command.
9:17:45 AM - PWD
9:17:45 AM - 257 "/" is current directory.
9:17:45 AM - TYPE I
9:17:46 AM - 200 Type set to I
9:17:46 AM - EPRT |1|192.168.254.105|61264|
9:17:46 AM - 200 Port command successful
9:17:46 AM - MLSD /
9:17:47 AM - 150 Opening data channel for directory listing of "/"
9:18:02 AM - Testing connectivity using Socket.Poll()...
9:18:02 AM - Disposing FtpClient object...
9:18:02 AM - Disposing FtpSocketStream...

**Comment by Jaex** [comment]
Change BrowserProtocol to https.

**Comment by Jaex** [comment]
When you do upload with that FTP settings and open FTP client is it still shows empty? I have no idea why it is empty.

**Comment by vavavr00m** [comment]
Is this reproducible? Re-setting FTP connection to Passive (IsActive=False) solved this.

However, when I used drag and drop to FTP, it still uploads to the default uploader destination - Dropbox.

Hotkey settings:
![dropbox](https://dl.dropboxusercontent.com/s/3kzxt2dooemxfa3/2015-07-15_18-14-53.png)

Main task window settings::
![dropbox](https://dl.dropboxusercontent.com/s/t6w36ol5czj0j1b/2015-07-15_18-20-51.png)

Task upload settings:
![dropbox](https://dl.dropboxusercontent.com/s/6h80d8xpcsb5qt6/2015-07-15_18-26-08.png)

Did I configure something wrong? How should I do it? 

One more thing, can you please include a way to add port number to PreviewHttpPath?

**Comment by Jaex** [comment]
Drag and drop window didn't have your hotkey task settings because it is singleton form not possible to open it more than one time. So I didn't thought task settings should be passed to it. But did it now.

Why URL should have port?!

**Comment by vavavr00m** [comment]
I need to define the port because two different web servers are running at the same time, port 80 is locked, and that's how I was given access.

If it can be done, would be nice if I can set the following format:
PreviewFtpPath //username:password@domain.tld:port/filename.ext
PreviewHttpPath //domain.tld:port/filename.ext
