### ISSUE TITLE
SFTP not defaulting to port 22

### ISSUE THREAD

**Issue by VegetableJuice** [ShareX/ShareX#783]
Seeing as the default port for FTP is automatically set to match the norm for that protocol (21), should the same not be true for SFTP? That is to say, shouldn't SFTP default to 22 when selected, rather than 21?

Why would you do this for one, but not the other?

Just comes across as a tad inconsistent, and potentially confusing to the end user.

Alternatively, don't have an initial port number at all. Just leave it blank.

**Comment by Jaex** [comment]
Because one variable can't have more than one default value. And about automatically changing it, it will overwrite users port choose. So I can't touch it and break people port setting. Also I can't make it blank because integer variable can't be empty.
