### ISSUE TITLE
owncloud 8.1 upload target

### ISSUE THREAD

**Issue by seb-sch** [ShareX/ShareX#784]
The "direct link" option changed on owncloud 8.1 from "&download" to "/download".
Generated links using &download result in 404 errors.

**Comment by Scrxtchy** [comment]
Is it worth forcing this option, or are owncloud users not so much pressed to update their systems, meaning that both options would need to be supported?

**Comment by Jaex** [comment]
It is good question Scrxtchy asked. If people not willing to update to latest version then when I make this change it will break majority of people links.
