### ISSUE TITLE
Add right click handling in NotificationForm

### ISSUE THREAD

**Issue by chairborne** [ShareX/ShareX#785]
Sometimes I need to copy the URL of screenshot to clipboard, sometimes not. Sometimes I also can't or don't want to open my browser. I need an option to copy URL with right click. Please, add it.

**Comment by Jaex** [comment]
Can't change right click it is for close popup. And for left click there is this setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX.vshost_bTijTUk4XD.png)

But it was missing Copy URL so I'm adding it now.
