### ISSUE TITLE
Add Gyazo Image Uploader Support

### ISSUE THREAD

**Issue by Justin991q** [ShareX/ShareX#787]
API Documentation: https://gyazo.com/api/docs

<pre>
<code>
{
  "Name": "Gyazo",
  "RequestType": "POST",
  "RequestURL": "https://upload.gyazo.com/api/upload",
  "FileFormName": "imagedata",
  "Arguments": {
    "access_token": "74e83db91130748109328b9aa47c99e1d7c8dcaadc42317dae9e33378f62020a"
  },
  "ResponseType": "Text",
  "RegexList": [
    "\"permalink_url\":\"(.+?)\"",
    "\"thumb_url\":\"(.+?)\""
  ],
  "URL": "$1,1$",
  "ThumbnailURL": "$2,1$",
  "DeletionURL": ""
}
</code>
</pre>

**Comment by Jaex** [comment]
Why would anyone want to upload there. They add advertisements all over the image page.

**Comment by Justin991q** [comment]
I just got this one which gives you a straight link to the image without their page around it. Just a straight raw link.
<pre>
{
  "Name": "Gyazo",
  "RequestType": "POST",
  "RequestURL": "https://upload.gyazo.com/api/upload",
  "FileFormName": "imagedata",
  "Arguments": {
    "access_token": "74e83db91130748109328b9aa47c99e1d7c8dcaadc42317dae9e33378f62020a"
  },
  "ResponseType": "Text",
  "RegexList": [
    "\"url\":\"(.+?)\"",
    "\"thumb_url\":\"(.+?)\""
  ],
  "URL": "$1,1$",
  "ThumbnailURL": "$2,1$",
  "DeletionURL": ""
}
</pre>

This one will output:
URL: https://i.gyazo.com/b0f3e73d28a6b5737550cfba3efb4174.png
Thumbnail URL: https://i.gyazo.com/thumb/200/_1cd147ae647b322cec2486059ecae734.png

**Comment by CanadianJeff** [comment]
whats the status of this? can we add this ourself?

**Comment by Committing** [comment]
> Why would anyone want to upload there. They add advertisements all over the image page.

Useless reply and totally unhelpful not less untrue.

Thanks @Justin991q - worked a dream
