### ISSUE TITLE
Screen recording doesn't work with display scaling

### ISSUE THREAD

**Issue by vemacs** [ShareX/ShareX#789]
Here's the error I get:

![](https://i.imgur.com/rzKtnXT.png)

The area picker needs to have some calculations that compensate for display scaling. If I select a small area in the top left of my screen, this works fine, so it's not an ffmpeg issue.

ShareX should be dividing the width and height by (system dpi/96).

**Comment by Jaex** [comment]
If ShareX do that then other video source won't work. So it must be ffmpeg issue because other video source handles this fine.

**Comment by vemacs** [comment]
If I select a region in the upper left corner, the video records fine, and if I do the math and select 1280x720 exactly, the full screen is recorded. This is obviously a sharex issue, not ffmpeg. I don't see why you're marking this invalid.

**Comment by vemacs** [comment]
FFmpeg bug report: https://trac.ffmpeg.org/ticket/4232

**Comment by vemacs** [comment]
@Jaex Setting Video source to screen-capture-recorder (after clicking "install-recorder-devices") works.

**Comment by Jaex** [comment]
I was installing it automatically in previous versions but in latest version made it optional because of few problems caused by it.

**Comment by vemacs** [comment]
Can you install it automatically only for hidpi devices?

**Comment by grofit** [comment]
This fixed my issue too, good thing I found it :wink:

**Comment by Jaex** [comment]
#923
