### ISSUE TITLE
Return HTTPS for Imgur links

### ISSUE THREAD

**Issue by Murilirum** [ShareX/ShareX#793]
Imgur.com supports SSL for links directly to images (https://i.imgur.com/Z7A8TcU.png) but the image link returned by default is HTTP (https://i.imgur.com/6GU7Rl0.png). It's not a bad thing by any means but if there's support for it, it may as well be used.

It's more a quality-of-life enhancement because on some of the HTTPS sites that I use, it needs to be adjusted anyways and I'd like to encourage users to use ShareX for screenshots on my social communities since I'll be using SSL and requiring that any links or shares come from services that support it (YouTube, Facebook, Twitter and Imgur are the largest respectively).

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX_eog4Jsrajk.png)

#716

**Comment by Murilirum** [comment]
Are there any considerations for cleaning up the navigation organization in the application?

**Comment by Jaex** [comment]
This is cleaned up version.
