### ISSUE TITLE
Install for offline use

### ISSUE THREAD

**Issue by bernardcornet** [ShareX/ShareX#795]
What can be done to install ShareX on a computer without internet access and still get the dependencies?
For instance, "ffmpeg" is causing me issues.
I tried downloading it from https://www.ffmpeg.org/download.html#build-windows
and then making a copy in C:\ShareX\Tools\ffmpeg.exe (or in C:\ShareX\ffmpeg.exe).
but it does not seem to work.

It seems that others had the same problem previously:
http://superuser.com/questions/900933/install-sharex-offline

By the way thank you for this fantastic app!

**Comment by Jaex** [comment]
Did you tried portable in here https://github.com/ShareX/ShareX/releases/tag/v10.0.0 and then it will download FFmpeg to proper folder so you can later use it offline.

**Comment by bernardcornet** [comment]
Thanks! I previously didn't see that it was possible to select the path fo FFmpeg, in the "task application" menu. Now it works perfectly. Thank you!
