### ISSUE TITLE
Exception: System.Net.Sockets.SocketException (0x80004005)

### ISSUE THREAD

**Issue by blooperboy** [ShareX/ShareX#800]
I am getting this error message after trying to upload a screenshot to my FTP server.
http://pastebin.com/4Sq3Mn1v
It doesn't seem to be working from this computer specifically, it works fine on another computer with the same settings.

I can provide any additional info that might be needed. Thank you

**Comment by Jaex** [comment]
It is DNS related error and can't be to do with ShareX. Not sure what is wrong in your computer or config too.

**Comment by blooperboy** [comment]
Thank you
