### ISSUE TITLE
FTP file upload uses url-encode on file name instead of URL only

### ISSUE THREAD

**Issue by ElectronicWar** [ShareX/ShareX#802]
When you upload a file with the custom FTP uploader that contains e.g. a Space or UTF-8 characters, ShareX will mangle the file to be url-encoded, uploads it and then generates a link with a lot of url encoded characters.

Example: `my file.txt` will be uploaded as `my%20file.txt` and the resulting link will be `http://myserver.tld/my%2520file.txt`.

It is especially frustating with UTF8 files, e.g. Japanese file names. It will make the filename completely unreadable.

**Comment by maurits150** [comment]
This issue seems to have returned.

When I upload to SFTP using the following SubFolderPath: /...../data/img/%mon %y/, it actually creates a folder named July%202016 instead of using a normal space.

**Comment by ElectronicWar** [comment]
This looks like it is "deeper" in the code, my fix was only for the final file path. If I find some time I will look at it, but this might take a few days.
