### ISSUE TITLE
(S)FTP can't enter /

### ISSUE THREAD

**Issue by Alagaros** [ShareX/ShareX#804]
Whenever I am trying to upload an image to '/var/www/screenshots' it just creates a folder named var in the users folder.

I do have the required rights on my server.

**Comment by Jaex** [comment]
Your ftp path starts from that users folder then what ShareX supposed to do?

**Comment by WebFreak001** [comment]
Did you try creating a user for the screenshots where the user folder is in /var/www?
```
useradd sharex
passwd sharex
usermod --home /var/www sharex
```

**Comment by Alagaros** [comment]
@WebFreak001 putting ../../ before it helped. I assumed '/' would take it to the home directory. But that would probably work too.
