### ISSUE TITLE
Open an image file in ShareX editor instead of immediately uploading it?

### ISSUE THREAD

**Issue by ThankYou2** [ShareX/ShareX#809]
If I use the "open with" explorer context menu command to open an image file in ShareX, it automatically uploads the file via ShareX.

But I would like it to open the file in the editor first so I can edit it before uploading instead of just immediately uploading it.  Is there a way to do this?

Thank you.

**Comment by Jaex** [comment]
Try this: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX.vshost_E5D92ZtBIG.png)

**Comment by ThankYou2** [comment]
Am I allowed to say OMG here?!  Spectacular response time, and spectacular result!  Works like a charm!  Thank you for ShareX.  It's a brilliant piece of work!

**Comment by Jaex** [comment]
Actually I was 3 minute responded late because was doing testings :(

**Comment by sparcut** [comment]
@Jaex @ThankYou2 Image link broken, how did you get image in editor before upload?

**Comment by ruTrucker** [comment]
Version 11.6.0 - is ok
Version 11.7.0 - not opening editor :(

**Comment by iamcmnut** [comment]
> Version 11.7.0 - not opening editor :(

Me too. ;(

**Comment by mhjgithub** [comment]
did you remove the image editor from application????? :O that was a very strong and great tool. that was all in one window with powerful abilities.
:(
:(
:((

**Comment by tssge** [comment]
You probably should've notified that the new version will break things, particularly the great image editor ShareX offers. ShareX is part of my workflow and both are now broken for me.

I am hesitant to update ShareX ever again in the future.

**Comment by oshihirii** [comment]
If you still have the captured image filename in the 'main panel' of ShareX, you can select > right click and 'edit image'.  I'm sure there was another way to do this, but can't remember how to do it at the moment.

**Comment by mturilin** [comment]
I think the solution with opening file from the explorer context menu would be the best. This is the most logical and easiest to find. I would use it the same way I user Sublime Text with text files.

**Comment by Jaex** [comment]
There is this option:

![](https://jaex.getsharex.com/2021/09/ShareX_CGTjMaXu0e.png)

**Comment by mturilin** [comment]
This is great!

**Comment by madrum** [comment]
I recommend NOT installing ShareX through the windows app store.
The Integration > Windows section only has 1 checkbox (run when Windows starts), so those context menus can't be setup.

**Comment by yahooshua** [comment]
> There is this option:
> 
> ![](https://camo.githubusercontent.com/b93d7bff8468e20637b270a0f224fb19dba355766994898f71e8bb2787823952/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f30392f5368617265585f4347546a4d61587530652e706e67)

This is the answer I was looking for. The only issue is Windows 11's right-click windows you need to 'Show more options' to see it. :/

**Comment by yahooshua** [comment]
It would be nice if there was an option to make the Editor a default file handler.
