### ISSUE TITLE
Open image in editor when launched from Firefox add-on

### ISSUE THREAD

**Issue by ThankYou2** [ShareX/ShareX#810]
Okay... this one may be a little tougher...

I have a Firefox add-on called "Open with Photoshop":
https://addons.mozilla.org/en-us/firefox/addon/open-with-photoshop/
It adds a right click context command to Firefox that when invoked, opens a selected image on a web page in Photoshop.  Pretty simple, but also very cool.

But who needs Photoshop when you have ShareX?!

So fortunately, you can change the path parameter in Open with Photoshop to point to another program.  And obviously pointing it to ShareX is the most intelligent thing to do!

But, when you do so, it suffers from the same problem as I had with the explorer context menu command and it uploads the image immediately instead of opening it in the editor (a problem which you solved for me!).

I don't know what method Open with Photoshop uses to send the image to ShareX, but is there any way of having it also open the image in the editor instead of immediately uploading it?  This would be heaven!

Can I have a twofer?  If it's not appropriate to post this under this topic please just ignore.  Is there any way to delete items from the "History" list?

**Comment by Jaex** [comment]
I dunno what is twofer. On purpose I didn't added deletion to history for make history never lose any entry while re writing. Like if electric lose while you removing something. Because removing involve re adding each xml element from start.

I don't know anything about Firefox addon writing so how am I supposed to help about it. But it would be nice having ShareX addon :P

**Comment by ThankYou2** [comment]
A ShareX addon would be spectacular!

Twofer is a humorous slang expression meaning "two for the price of one." :)

If an image is deleted from all hosts and also from the local location, it seems logical that you might want to delete that entry from the history.  I can't see any reason to keep that record other than having an "audit trail"... but I'm not sure that is very useful.

I think what you are saying is that being able to delete entries could cause a technical problem with the data.  If so, thank you. I understand. :)

Did I mention that a ShareX Firefox addon sounds great (which has an option to open in browser of course)! :dancers:

**Comment by Jaex** [comment]
I can't write Firefox addon because I'm not good with javascript or whatever language required to write it. So someone else should write it.

**Comment by ThankYou2** [comment]
Okay... thank you for the suggestion.  Maybe I can find someone who can do it.  In the meantime, I will play with some of the advanced settings in ShareX to see if I can get it to open images in the editor from the Photoshop addon.  It is frustratingly close to working perfectly, but that last inch is killing me!

Thank you for the great help... and the spectacular ShareX!

**Comment by ThankYou2** [comment]
Wait!  I may have discovered the problem here... please keep topic open

**Comment by Jaex** [comment]
You should have posted it instead of editing because I didn't know you edited this.
