### ISSUE TITLE
Launch editor from tray icon/open local file from editor

### ISSUE THREAD

**Issue by ThankYou2** [ShareX/ShareX#814]
I often need to edit image files that are already on a local disk and then upload them.  There are two things that would make this easier.

1. Be able to launch the editor directly from the ShareX tray icon.

2. Have a file open button on the editor.

(Also-- I have extensions on my file open dialog that allow me to instantly navigate to favorite folders as long as it is the standard Windows file open dialog.  This is extremely useful.)

Thanks again!

**Comment by Jaex** [comment]
ShareX tray menu already have it in tools menu.
