### ISSUE TITLE
SomeImage.com support

### ISSUE THREAD

**Issue by caocaoxanh** [ShareX/ShareX#816]
Introduction: https://someimage.com/api

Thanks..

**Comment by Jaex** [comment]
Because their API not returns direct image URL I don't see reason to implement it.

**Comment by caocaoxanh** [comment]
^ Thank your feedback :) How about imgbox.com and imagebam.com?

**Comment by Jaex** [comment]
Added someimage to here: https://github.com/ShareX/ShareX/wiki/Custom-Uploader-examples#someimagecom

**Comment by Jaex** [comment]
I was added imagebam long time ago but then they were closed.

**Comment by caocaoxanh** [comment]
:+1: Thank you (again).

**Comment by DanielMcAssey** [comment]
@Jaex this can be closed now. :+1:

**Comment by sergeevabc** [comment]
someimage.com returns 127.0.0.1 for quite some time, i.e. is not available.
