### ISSUE TITLE
Cross-platform Support

### ISSUE THREAD

**Issue by JustOneMoreBlock** [ShareX/ShareX#818]
Hello,

I know this has been stated numerous times and you’re a very busy person. I personally don’t use MacOS or Linux for my normal PC, however I do have friends who do and I recommend ShareX to all my friends who run on Windows.

Unfortunately there isn’t any good equivalent for ShareX on MacOS X or Linux and if this was a way for you or even someone else to port it over to make run that would be awesome if it was cross platform.

I understand if you cannot do it yourself which is fine. I was doing some reading how Microsoft Visual Studio is cross platform now and NuGet also has compatibility with Mono Support. Something you possible could look into.

A friend of mine is building an application with cross-platform in mind and he decided to use wxWidgets which has many libraries available and maybe even possible to easily port over. (Don’t quote me on that.)

https://www.wxwidgets.org/

If I’m not mistaken the most popular application that was made using wxWidgets is FileZilla.

Not trying to pressure you or anything, just giving you some information maybe you could certainly look into or if someone is reading this would mind doing a port.

Kind Regards,
Cory

**Comment by DanielMcAssey** [comment]
Outside of using something like Mono, this is not really feasible in my opinion, the technical debt of the project would be too great if they were to attempt porting this project
