### ISSUE TITLE
"All-in-one" screen capture

### ISSUE THREAD

**Issue by hmemcpy** [ShareX/ShareX#823]
Hi!

Just found ShareX, and I love it already!

I've been using Snagit for the past several years, and wrote a plugin that [uploads the captured images to imgur](https://github.com/hmemcpy/SnagitImgur/). If there is one thing Snagit does really well, is offer an ["all-in-one" capture mode](https://www.techsmith.com/tutorial-snagit-using-all-in-one-capture.html), where it would highlight active areas of a screen/window, allowing you select what to capture.

Is there something similar in ShareX?

**Comment by Jaex** [comment]
Yes it is called Rectangle (Objects).
