### ISSUE TITLE
VP9 Support

### ISSUE THREAD

**Issue by MLWALK3R** [ShareX/ShareX#824]
https://en.wikipedia.org/wiki/VP9

https://trac.ffmpeg.org/wiki/Encode/VP9

**Comment by Jaex** [comment]
I already tried it before and in real time encoding it was causing issues. You can try it yourself editing commands.

**Comment by guiweber** [comment]
@Jaex This might be worth testing again since VP9 has been improved a lot since then. The libvpx releases that have been made since 2015 all say the following:

> This release improves upon the VP9 encoder and speeds up the encoding and
>   decoding processes.
