### ISSUE TITLE
Image history

### ISSUE THREAD

**Issue by NotThisMind** [ShareX/ShareX#827]
Can we get image history to enumerate all images within the \Capture\ folder and subfolders? Because the current way i believe it's enumerating all from History.xml on the Sharex personal folder, and either it's not enumerating that properly (it's not ordered, i can't really find all images, idk if this is intended)
And i made a mistake in deleting the History.xml file, which means i have no history or image history... i know it's my fault, but is there a option to enumerate in Image history all the images that are in the Custom Image folder i use? Or just the latest month? I separate them by year-month in subfolders as Sharex provides the option to.

Thanks and sorry if i used too much words explaining, english is not my first language.

**Comment by Jaex** [comment]
What is point of using it without history file. You can't have URL etc. And if you want to see latest month then why you don't use Windows explorer?

**Comment by NotThisMind** [comment]
Sorry, i wasn't thinking clearly, yes you're right, i forgot url and other info was saved in the history... i deleted it by mistake when i was testing because the issue for me was that it wasn't ordered by date, and i couldn't order it within Image History as it appeared not showing my custom Image Folder, only showing the original folder which i used when i was new to Sharex, but now as i test again after deleting that folder and History.xml (maybe this wouldn't affect but now i can't now) it shows my custom folder correctly and the image history correctly too.

Sorry for making this post, the real problem was i had the original folder of images un-deleted, and that somehow showed only it disregarding my custom folder entirely, if there's a way to delete this please feel free, otherwise i'll just close.
