### ISSUE TITLE
Ask what to do after capture

### ISSUE THREAD

**Issue by montoner0** [ShareX/ShareX#830]
It would be nice to have an option 'Ask what to do' after capture. Showing menu 'After capture' will be enough I think.
I thought ShareX will ask me if I'll uncheck all actions in 'After capture' menu but it didn't.
I'm not sure if it's by design but anyway 'doing nothing' is somewhat strange.

Upd. 'Post capture tasks' window is an overkill IMO

**Comment by Jaex** [comment]
Post capture tasks window doing exactly what you want.

**Comment by montoner0** [comment]
Anyway allowing to doing nothing after capture is a strange behavior.
