### ISSUE TITLE
Redused/user-configurable menu for notification icon

### ISSUE THREAD

**Issue by montoner0** [ShareX/ShareX#831]
It would be nice to have a reduced or even better user-configurable menu for notification tray button, with most frequent/needed actions.

**Comment by Jaex** [comment]
I'm not planning to reduce anything in that menu. It shows fundamental things. And something not frequent to you can be used by other frequently. So I can't make that menu to fit your needs.

**Comment by montoner0** [comment]
I'm not taling about reducing main menu but about creating an additional menu.
