### ISSUE TITLE
Screen recording upload to Gfycat invariably fails

### ISSUE THREAD

**Issue by MegaPixelPerfect** [ShareX/ShareX#839]
Every time I try to do a screen recording and upload to Gfycat the mp4 fails on upload due to a time-out. I'm not sure why this is happening. The upload status smoothly and quickly rides up to 100%, but then stalls there until it fails a few minutes later. Some additional information: this is on Windows 10, with ShareX 10.0 (apologies if I've missed some important information).

Here's the code:
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Message:
The operation has timed out

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, Stream dataStream)

**Comment by Jaex** [comment]
I tried to reproduce it but it uploaded successfully: https://gfycat.com/EagerGlitteringBlackfly

**Comment by MegaPixelPerfect** [comment]
I see you're on 10.1. perhaps I'm missing an update that solves this?

**Comment by Jaex** [comment]
Nothing changed in Gfycat in new version.

**Comment by MegaPixelPerfect** [comment]
What are your settings for screen recording? These are mine: http://i.imgur.com/DBCpT7N.png

**Comment by Jaex** [comment]
Did you tried reopening ShareX?

**Comment by MegaPixelPerfect** [comment]
Exiting ShareX and reopening it did not solve the issue. Is there a required driver needed for ShareX to Gfycat or something similar to that. I know one is required/downloaded when attempting to screen record a GIF to imgur.

**Comment by Jaex** [comment]
Is your recording lower than 15 seconds?

**Comment by MegaPixelPerfect** [comment]
Yes it is.

**Comment by MegaPixelPerfect** [comment]
Here is the [entire log](http://hastebin.com/yuwomujiro.tex) just in case that is helpful.

**Comment by Jaex** [comment]
I don't think I can figure out what is wrong without be able to reproduce it.

**Comment by MegaPixelPerfect** [comment]
Are your settings exactly as the ones I linked above? Are there any settings that could be limiting this such as an upload cap or something?

**Comment by Jaex** [comment]
It can't be to do with screen capture and there is not setting for Gfycat. Maybe your firewall doing something?

**Comment by MegaPixelPerfect** [comment]
I've added ShareX to the firewall permissions but that did not solve the issue, besides this, taking screenshots works fine so I don't think that's the issue? I'll keep looking around for potential things that could be blocking this because I would really like to use this feature.

**Comment by DanielMcAssey** [comment]
Can you actually access gfycat? Just want to make sure its not an ISP issue.

**Comment by Long-Horse** [comment]
I also have this issue sometimes. It's been a while since the last time it's happened. What I do is I go to gfycat.com and manually upload (I save all captures locally as well) and it always tells me it has already been uploaded. So it appears that the ShareX upload is giving some sort of false-positive because the upload does actually work. You just need to manually upload it to find the link or gfycat has to make an API so we can upload to our account from ShareX.

**Comment by Scrxtchy** [comment]
@Long-Horse Can you post the 'Show Error' log from a failed upload?
You can find this from the context menu on the main window
![](http://link-removed.xyz/i/2015/08/15-08-02_20-34-56.png)

**Comment by MegaPixelPerfect** [comment]
Now I'm getting an entirely new error in ShareX 10.1: "Oops! This looks like a video format, but it can't be read."

**Comment by DanielMcAssey** [comment]
Could you do what @Scrxtchy asks and also could you post your screen recording settings, found in "Task Settings -> Screen Recorder -> Screen recording options..."

**Comment by MegaPixelPerfect** [comment]
So, the error is literally that: 
![yjjnwcd](https://cloud.githubusercontent.com/assets/6833403/9026587/a7f3725c-3902-11e5-936a-776f06653215.png)

As for screen recording, these are my options:
![hq6wcq7](https://cloud.githubusercontent.com/assets/6833403/9026591/c8034ab8-3902-11e5-9c09-4acab533667d.png)

**Comment by DanielMcAssey** [comment]
Works perfectly fine for me with the exact settings: https://gfycat.com/MessyConcernedJerboa

It's possible that the upload times out which doesn't complete the file, do you have fast enough internet to upload? How long does it typically take to complete an upload to gfycat?

**Comment by MegaPixelPerfect** [comment]
A 5 second clip took roughly a minute and a half.. gfycat.com/TautBrightKillerwhale

**Comment by DanielMcAssey** [comment]
I really have no idea, I cant reproduce, hopefully someone may be able to help.

**Comment by MegaPixelPerfect** [comment]
Honestly not sure why I'm having all these gfycat errors.. :disappointed:

**Comment by Long-Horse** [comment]
@Scrxtchy I don't have anything in that list since updating to 10.1. I also can't force the timeout thing to happen, it just does randomly but like I said, I haven't gotten it in a while.
