### ISSUE TITLE
Add seafile support

### ISSUE THREAD

**Issue by aaomidi** [ShareX/ShareX#842]
Seafile is a software like dropbox, adding support for it would be appreciated!

**Comment by aaomidi** [comment]
Also I cant use a custom uploader for this because it is a multi step upload process.

**Comment by unixfox** [comment]
:+1:

**Comment by cdlan** [comment]
:+1:

**Comment by ndgo** [comment]
:+1:

**Comment by LeDistordu** [comment]
:+1:

**Comment by Ipquarx** [comment]
SeaFile API reference in case someone's actually going to add it: http://manual.seafile.com/develop/web_api.html

**Comment by Centzilius** [comment]
:+1:

**Comment by zikeji** [comment]
I will start work on this later today. If anyone else started work on this let me know as I don't want work on it if someone else is already.

__Planned support:__
* Custom API URL if you are hosting your own private server
* Destinations menu shows usage on account, account email being used.
* Will default to your default library (duh), but will also let you choose which library you want to use.

Although it does appear in order to obtain an API token you have to sign in through the API, which means you will have to provide credentials for Seafile through ShareX which might make some of you uncomfortable. Needless to say, the source will be available if you're paranoid. Although there will be an option to enter your auth key if you already have it, just next to it will be an option to "obtain auth key".

**Comment by unixfox** [comment]
@zikeji You are right, there is no way to generate an API token unfortunately.
Thank you for integrate Seafile in ShareX.

**Comment by zikeji** [comment]
@unixfox You can generate a token but you have to do it via POST in the API which doesn't make much sense considering normally you should be able to do it in the web panel as to not give third party software your credentials.

**Comment by zikeji** [comment]
__Update:__

Things are going strong! Ran into a hitch though, I wanted to list directories recursively but it looks like that API ability was recently added 18 days ago (according to their changelog) and doesn't seem to be supported by their seadcloud.cc API yet, as such you'll have the option to choose a repo and then provide a path in the repo you want to use (default being base, or /).

**Comment by unixfox** [comment]
@zikeji seacloud.cc is using 4.4.0 but according to the changelog, the latest stable version is 4.4.2. I think they will update soon to this release.
I can make an account for you on my seafile cloud in 4.4.2 if you need. But I'll do it tomorrow (CEST).

**Comment by zikeji** [comment]
@unixfox No need, I'll keep it as it is. I'd rather not add recursive functionality when we're this close to the release. The people without the feature may have issues, and if I keep the "path" textbox it'd look redundant to the updated people. For now I'll just keep path separate.

**Comment by zikeji** [comment]
@Jaex I looked around in the helpers some but couldn't find any. Do you have a helper for converting bytes to kb, mb, gb, etc.? Don't want to make a private function in my class if you have a helper.

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/blob/master/ShareX.HelpersLib/Extensions/NumberExtensions.cs#L101

**Comment by zikeji** [comment]
I'm having an issue right now with PUT requests.

http://manual.seafile.com/develop/web_api.html#create-file-share-link

To create the share link I have to use PUT, but your SendRequest method doesn't allow me to set the content length (which is a requirement for PUT requests, apparently). I tried replicating it but then I get a 500 server internal error. I think I may have to do post data with the PUT, as the CURL uses -d. I don't know, I'll pound at it later.

Right now my repo has it working for encrypted folders and normal folders, as long as you uncheck "Share files automatically".

**Comment by Jaex** [comment]
You didn't set "Accept: application/json" is it can be reason why it fails?

**Comment by zikeji** [comment]
Well, the API didn't call for it. I gave it a try anyway and it made no difference.

**Comment by Jaex** [comment]
API calls it like this: ``` -H 'Accept: application/json; indent=4'```

**Comment by zikeji** [comment]
Totally missed that. Anyway, I got it working. Still ugly, you may want to edit your Uploader class to allow PUT POST support and Content-Length support.

__Anyone who wants to test the new build, see here:__
https://seacloud.cc/f/71f961cd4c/ (uploaded with ShareX! Aha!)

@Jaex I've submitted a pull request for your review.

**Comment by Fedack** [comment]
It seems that this does not work with the newer implementations of Seafile. Would it be possible to update?
