### ISSUE TITLE
Suggestion - Differentiate videos and files when uploading

### ISSUE THREAD

**Issue by Fergo** [ShareX/ShareX#844]
I think it would be useful if ShareX treated video files and "other" files differently in terms of upload options. Since it differentiates text and images (you can chose different destination for each of those file types), it could also do the same for videos. I think this is useful because movie clips usually have different destination targets than other files such as exe, zip, rar, doc, etc. 

Eg.: I use Dropbox as a target for file uploads, but the short movie clips I capture would suit much better in a video sharing service such as Gfycat. Both are already supported, but at the moment, I have to keep switching between Gfycat and Dropbox destinations depending on the file type I'm uploading.

Thanks in advance!

**Comment by Jaex** [comment]
Best way to solve your problem is choosing Gfycat as destination for your screen record hotkey. When we started to make this software there was no video support and it is too much work for us to add it now.
