### ISSUE TITLE
Using "Disable/Enable hotkey" to disable hotkeys disables some keys.

### ISSUE THREAD

**Issue by vavavr00m** [ShareX/ShareX#846]
I set CTRL + ALT + H as my "disable/enable hotkeys" hotkey and SHIFT + F and SHIFT + D for other tasks. After disabling ShareX hotkeys with CTRL + ALT + H, I cannot use SHIFT + F and SHIFT + D to quickly capitalize the two letters. Just tried to set CTRL + A to do a certain task and after disabling ShareX with the Disable/Enable hotkey, I cannot use CTRL + A (highlight all) anymore.

**Comment by Jaex** [comment]
Where you can't use ctrl + a to highlight all?

**Comment by vavavr00m** [comment]
Chrome (while typing here) & Notepad so far.

**Comment by Jaex** [comment]
Reason is actually I don't unregister hotkey but make them not trigger their tasks. Main reason for this is if i disable whole hotkey system then "disable hotkey" hotkey won't work too. So yes I did workaround  like this. And I'm lazy to make proper unregistering system :P

**Comment by vavavr00m** [comment]
I understand :-D Please consider this issue a request ("Enhancement") then ^_^
