### ISSUE TITLE
Error when copying and trying to upload text.

### ISSUE THREAD

**Issue by pbparachute** [ShareX/ShareX#847]
System.IO.DirectoryNotFoundException: Kan een gedeelte van het pad C:\Users\Jellepc\Documents\ShareX\Screenshots\2015-08\6o466G5q5g.txt niet vinden.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bij System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bij System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   bij ShareX.UploadTask.DoTextJobs()

**Comment by M1kep** [comment]
Same, I recieved the error multiple times when trying to upload my clipboard to pastebin

**Comment by Jaex** [comment]
Reason for this is directory not exist. Mainly this directory create automatically in your first screen capture saving therefore I missed it. So I need to automatically create this directory in text upload too. For now you can do one screen capture to force creating directory.

**Comment by pbparachute** [comment]
Jaex, a screen capture doesn't fix it. Can there be a new update please;..

**Comment by M1kep** [comment]
You can either manually create the directory, or I'm pretty sure you have
to do a full screen shot, not selective size /shape, and make sure that or
saves itself

**Comment by pbparachute** [comment]
I just found out I have to create a .gif or .mp4 to create the directory. But do I really have to do it every day before I can upload from my paperclip?

**Comment by M1kep** [comment]
Every month.

**Comment by Jaex** [comment]
pbparachute I already fixed it 5 days ago. You can download beta version from IRC title.
