### ISSUE TITLE
Shadow problem

### ISSUE THREAD

**Issue by Suspect** [ShareX/ShareX#849]
I'm trying to use the 'Image effects configuration' and when I apply a shadow it appears to cut off on the top and bottom of the image. I just installed Windows 10 and updated ShareX recently, so I'm not sure what has caused it.

**Comment by DanielMcAssey** [comment]
Do you have an example image and did it work before you updated?

**Comment by Suspect** [comment]
Example of Shadow working - http://i.imgur.com/5vHNn2b.png
Example of current problem - http://i.imgur.com/QS4245J.png

**Comment by Jaex** [comment]
Why you don't use normal capture with shadow like this?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/08/ShareX_eaqkWKTFAz.png)

**Comment by Jaex** [comment]
But I'm still unable to reproduce your problem:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/08/ShareX_5oYg67k07H.png)

**Comment by Suspect** [comment]
Interesting, the shadow only starts working once I set the size to 20 and over. I will take a look at the normal capture method now.
