### ISSUE TITLE
Idea: Add uploaded files to Windows 10 Action Center

### ISSUE THREAD

**Issue by Scarwolf** [ShareX/ShareX#850]
So yeah, I would like to see a feature where uploaded files will be shown in the Windows 10 Action Center, clicking on it would copy the link to that image again, and remove that image from the Action Center.

**Comment by resir014** [comment]
:+1: Definitely looking forward to this.

**Comment by Jaex** [comment]
When you select balloon tip notification then those will show up there already?

**Comment by Scarwolf** [comment]
Oh, yeah, you're right. Is there any possibility to copy the link from there again and maybe preview the image?

**Comment by Jaex** [comment]
I don't know is there such api? I personally hate that action center because it wrongly adds balloon tips to there when it is only need to be added when we are away from computer or in fullscreen application and can't see it etc. Like when torrent download something randomly it shows their notification tip or adds action center.

**Comment by Scarwolf** [comment]
Theres A nice Tutorial on this from the Microsoft Virtual Academy, maybe that could help: http://microsoft-news.com/developers-heres-a-developers-guide-to-the-action-center-on-windows-10/

Yeah, I personally like the Action Center. Some Balloon Tips being added to it are annoying but it could be perfectly used with ShareX to copy the link of a previous image fast.

**Comment by Jaex** [comment]
I bet Microsoft added that functionality inside .NET Framework 4.6 and ShareX currently using 4.0 because of Windows XP support.

**Comment by Scarwolf** [comment]
To be honest you shouldn't support Windows XP anymore. It simply way to old and has thousands of security flaws. Or maybe create two branches for ShareX? One at always the latest .NET, and one at 4.0?

**Comment by Jaex** [comment]
We planning to use .NET 4.6 in future. But waiting for more people to install Windows 10.
