### ISSUE TITLE
Twitter option suddenly greyed out.

### ISSUE THREAD

**Issue by resir014** [ShareX/ShareX#851]
I usually use ShareX to instantly share my screenshots to Twitter, but just earlier my Twitter option is suddenly greyed out and I can't upload to Twitter anymore:

![2015-08-02_23-24-15](https://cloud.githubusercontent.com/assets/5663877/9027005/1ab04408-396e-11e5-9e99-eb717af10573.png)

I checked my auth tokens and all that, and they seem to be still present.

Usually (from what I found on the Internet) I would have to open `ApplocationConfig.json` and switch the `UseSecondaryUploaders` option to `true` but this time it doesn't work.

**Comment by DanielMcAssey** [comment]
Have you tried reauthorizing with twitter?

**Comment by Jaex** [comment]
Twitter list is unselectable are you sure you selected your account there and not deselected it?

**Comment by resir014** [comment]
@Jaex It wasn't deselected at all, and then suddenly ShareX was giving a `NullReferenceException`, and when I checked my uploaders settings I found out it's been greyed out.

**Comment by resir014** [comment]
@DanielMcAssey I tried this, and it works again. Thanks!

@Jaex Feel free to close this issue for now.
