### ISSUE TITLE
New update disables drag and drop

### ISSUE THREAD

**Issue by LukidayNL** [ShareX/ShareX#853]
as title says, trying to drag a file to the window results in an error
![image](https://cloud.githubusercontent.com/assets/11295568/9028071/e1576b4c-396c-11e5-8152-5bac2bd1c388.png)

**Comment by Jaex** [comment]
It can be issue with that you running ShareX with admin access maybe? Can you try reopening it.

**Comment by LukidayNL** [comment]
I have tried it on multiple computers with and without running it as administrator but it doesn't seem to work anymore since I updated it.

**Comment by Jaex** [comment]
I don't think anything changed in latest version about this. And I can't reproduce it.

**Comment by Jaex** [comment]
I also asked few people and they telling it works fine so it must be something wrong in your computer about permissions. Like if Windows explorer not ran as Admin but ShareX is ran as admin then you can't drag and drop file from your Windows to ShareX etc.

**Comment by LukidayNL** [comment]
It works for me now, the problem one the first pc was that I didn't restart it and the second pc was running an old version of win 10 insider. I have tested it again on the first pc (win 8.1) and on the other OS on the second pc (win 7) and It is working now.

Sorry to bother you with this and have a nice day!
