### ISSUE TITLE
Region capture is circular instead of rectangle

### ISSUE THREAD

**Issue by ClearLunatic** [ShareX/ShareX#859]
For some reason the task 'Capture rectangle region' doesn't make a rectangle anymore, but instead a circle. Both via hotkey and in the program itself. ''Region light'' is still a rectangle.

**Comment by DanielMcAssey** [comment]
Is it possible the circle you are referring to is the magnifier, its a little circle that pops up next to your mouse to show you Position and Pixel colour, with a grid overlay.

**Comment by Scrxtchy** [comment]
Press Numpad 1?
![](http://link-removed.link/i/2015/08/15-08-04_02-28-19.png)

Although if the issue is about the magnifier, this was an intentional change a long long time ago :v

**Comment by ClearLunatic** [comment]
Why was this closed? This wasn't about the magnifier.. 
http://i.imgur.com/jujbQC2.png

**Comment by Scrxtchy** [comment]
Learn to read, lol

![](http://link-removed.link/i/2015/08/15-08-05_00-33-41.png)

**Comment by ClearLunatic** [comment]
I should.. thanks.. I thought that was hotkeys because my hotkey for screenshots is numpad 3.. apologies.
