### ISSUE TITLE
Separate Cursor Option for Screen Recording

### ISSUE THREAD

**Issue by davidruhmann** [ShareX/ShareX#864]
The option [__Show cursor in screeshots__](https://cloud.githubusercontent.com/assets/2963122/9068624/ef4e7fb8-3aa9-11e5-820e-0217c8021f4b.png) also controls whether the cursor is shown in recordings.
Request for an additional option __Show cursor in recordings__ so that I can hide the cursor in screenshots while showing it in recordings without having to toggle the option each time.

__Related Code Locations:__
~~~ 
DrawCursor = TaskSettings.CaptureSettings.ShowCursor
~~~
[TaskSettingsForm.cs#L837](https://github.com/ShareX/ShareX/blob/afac3286c9ae2acce0785a8b0df70a951c961cb7/ShareX/Forms/TaskSettingsForm.cs#L837)

~~~
Screenshot.CaptureCursor = taskSettings.CaptureSettings.ShowCursor;
~~~
[ScreenRecordForm.cs#L195](https://github.com/ShareX/ShareX/blob/25477aa00915976a9935dd74f25a79be98be4da3/ShareX/Forms/ScreenRecordForm.cs#L195)

~~~
DrawCursor = taskSettings.CaptureSettings.ShowCursor
~~~
[ScreenRecordForm.cs#L230](https://github.com/ShareX/ShareX/blob/25477aa00915976a9935dd74f25a79be98be4da3/ShareX/Forms/ScreenRecordForm.cs#L230)

~~~
Image img = Screenshot.CaptureRectangle(CaptureRectangle);
~~~
[ScreenRecorder.cs#L165](https://github.com/ShareX/ShareX/blob/53719e8c768838b28edac08fc1ea7ca5fae27324/ShareX.ScreenCaptureLib/Screencast/ScreenRecorder.cs#L165)

**Comment by DanielMcAssey** [comment]
I would like this as well, hopefully @Jaex  thinks it's a good idea.

**Comment by Jaex** [comment]
You can already do this. In your screen recording hotkey disable cursor setting so it will only disable for screen recording this way.

**Comment by davidruhmann** [comment]
@Jaex Interesting...  Did not realize you could customize the settings for the individual tasks.  Though, I still do not like tying the recording cursor to the "Show cursor in screenshots" option.
[Hotkey Settings](https://cloud.githubusercontent.com/assets/2963122/9088159/4e619a1c-3b54-11e5-8f47-3d544823e865.png) > [Task Capture Settings](https://cloud.githubusercontent.com/assets/2963122/9088172/58c2247c-3b54-11e5-91f1-0f21d8789eb2.png)

Think I will just keep a custom build for myself to have a dedicated setting at the main level for ease of use.

**Comment by Jaex** [comment]
I already added what you want, can't you see?

**Comment by davidruhmann** [comment]
When looking at the responses, I missed your commit https://github.com/ShareX/ShareX/commit/d85db32347dab364db8dbac94e8546af84caf673 of the change to master.  Not accustomed to seeing direct master commits since that is not allowed where I work.
