### ISSUE TITLE
[request] please, add Bitcoin donations

### ISSUE THREAD

**Issue by Nogreedy** [ShareX/ShareX#869]
I'd like to make a bitcoin donation to ShareX
Please, accept Bitcoin donations.

**Comment by Jaex** [comment]
I was added this link to website before https://www.coinbase.com/Jaex but nobody was donated so I was removed it from website.

**Comment by Nogreedy** [comment]
Then I'm the first one ...
https://blockchain.info/tx/504aa8609e2cfb5c55cd0dad965dbcaf5c2b690a8f1a9ae26136478c533e854a
https://bitinfocharts.com/bitcoin/address/18tRZL1G1MJRV2SwfEaJqaKUP16fy952nH
There are dozens ways to convert instantly bitcoin to dollar... (Coinbase, Bitpay...)
https://en.bitcoin.it/wiki/How_to_accept_Bitcoin,_for_small_businesses#Merchant_Services

**Comment by Jaex** [comment]
No Coinbase not allows convert bitcoin to dollar in majority of countries.

**Comment by Krognus** [comment]
There are more markets than just Coinbase. Research what's the best BTC exchange in your country.

**Comment by theivien** [comment]
@Krognus and there are more ways to donate than just BTC @Nogreedy

**Comment by RockyTV** [comment]
Try using [Bitpay](https://bitpay.com). I think they can convert to real money.

**Comment by oldmud0** [comment]
Oh hey @RockyTV. What a small world..

**Comment by Jaex** [comment]
Added coinbase link to here: https://getsharex.com/donate/

**Comment by apometron** [comment]
What is your bitcoin wallet?

**Comment by Jaex** [comment]
@apometron please check this page for bitcoin address and QR code of it: https://getsharex.com/donate/

![](https://jaex.getsharex.com/2019/02/chrome_GBaLv52Jsm.png)

**Comment by apometron** [comment]
Thanks, when I do have something, I will donate 50 dollars!!!! =DDD Hopefully it will be soon!!!!
