### ISSUE TITLE
Crash : Upload text from paperclip

### ISSUE THREAD

**Issue by BleuDiamant** [ShareX/ShareX#870]
System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'F:\Documents\ShareX\Screenshots\2015-08\2015-08-05_17-38-34.txt'.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   à System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   à ShareX.UploadTask.DoTextJobs()
   à ShareX.UploadTask.DoThreadJob()
   à ShareX.UploadTask.ThreadDoWork()
   à ShareX.HelpersLib.ThreadWorker.WorkThread()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by Jaex** [comment]
#847

**Comment by BleuDiamant** [comment]
Oh sorry 
Thank for the solution
