### ISSUE TITLE
Update prompt window not navigatable without a mouse

### ISSUE THREAD

**Issue by rctgamer3** [ShareX/ShareX#871]
Pressing TAB while the "ShareX update is available. Do you want to update?"-like pop-up is shown doesn't cycle through the buttons/checkboxes. Clicking Yes or No is impossible without clicking either button with a mouse.

**Comment by DanielMcAssey** [comment]
Its possible the form isn't in the foreground, could you check if you ALT+TAB to the Update window, does it allow you to navigate the "Yes" or "No" options?

**Comment by rctgamer3** [comment]
As I said, window focus doesn't make a difference.

**Comment by DanielMcAssey** [comment]
Have you actually tried it?

**Comment by Jaex** [comment]
This is the reason why my custom controls in that window can't get focus:
http://stackoverflow.com/a/2362975/264877

So it is very difficult to implement.

**Comment by rctgamer3** [comment]
Maybe you could bind keyboard keys Y to Yes and N to no instead?

**Comment by Jaex** [comment]
That won't work with translation :D

**Comment by rctgamer3** [comment]
SPACE for the Yes button and Esc for No/Close perhaps?
