### ISSUE TITLE
Windows 10 - Bug Report

### ISSUE THREAD

**Issue by Fuzzoom** [ShareX/ShareX#873]
When I start ShareX on windows 10, I get this:
http://i.imgur.com/FXCCPFc.jpg

The program seems to work fine.

The only thing unusual beforehand was it asked me for permission for the app twice, so I only gave it to it once... After restarting the computer, I had to reinstall it, for it to work properly... But it still always gives this error message.

**Comment by Jaex** [comment]
Did you used portable mode?

**Comment by Fuzzoom** [comment]
Oh, yes, the first time I did... Maybe I should try uninstalling it (fully hopefully), and then installing it again without portable mode...

**Comment by Jaex** [comment]
How Portable supposed to work inside program files ShareX don't have permission to create folder and files there.

Just remove PersonalPath.cfg file from your ShareX folder to not make it portable.
