### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by hunti88** [ShareX/ShareX#878]
I'm using the auto screen capture with auto FTP upload function, and after every picture upload the software memory usage grow with the uploaded image size. The program starts with ~30mb memory usage, after a few days it can reach 1gb.
There is no memory leak if I disable the Image upload to host, so the I think the memory leak is in the FTP upload process.

**Comment by Jaex** [comment]
I'm trying my best to don't have any memory leaks but if memory leak caused by FTP library then I can't solve it because we using https://netftp.codeplex.com/

**Comment by hunti88** [comment]
You don't have to run it for days, if you set the timer to 3 sec, you will see in the task manager that the memory usage will rise every 3 second with the size of the uploaded image.

**Comment by Jaex** [comment]
But If you don't use FTP then memory usage not rise?

**Comment by hunti88** [comment]
I just tested it with imgur too, the memory still leaking. If i switch off the image upload after screenshot, the memory usage not changing, if i enable it with ftp or imgur the memory usage starts growing.

**Comment by Jaex** [comment]
I'm testing now it increasing but then decreasing back later so 5 minutes later memory was actually lower than before.

**Comment by DanielMcAssey** [comment]
@hunti88 It's possible this is meant to happen as the .NET Garbage Collector doesn't run very often (To stop constant stuttering when clearing unused memory), but if it persists after several hours of usage then its a problem.

**Comment by corruptnova** [comment]
@hunti88 Has the in use memory lead to noticeable performance issues? Generally, Windows will free RAM from the application as needed for the system. There are ways of forcing it to drop the in use memory, but it might not be a useful tool in the long run.

**Comment by hunti88** [comment]
Yes, there is a performance issue, after the sharex eats up all available memory, the system lose responsiveness, mouse lagging. Sometimes lagging so hard, i need ~5 minutes to open task manager, and another ~5 minutes to select the program and force close it.

**Comment by Soulflare3** [comment]
I can't get my ShareX to misbehave in the ways described in this thread, even on a Windows XP machine with 1.5GB RAM. ShareX appears to try and keep the usage under 60MB (GC doing a great job). Tested both Imgur and FTP uploaders. (I only let the auto-capture spam my own server, I wasn't going to do that to Imgur) ![screenshot](http://i.imgur.com/Oms65hN.png)

**Comment by hunti88** [comment]
![sharex](https://cloud.githubusercontent.com/assets/9551037/9440767/e95bad56-4a71-11e5-9f45-befbc3dbfa10.png)

**Comment by hunti88** [comment]
Today I got this:
System.OutOfMemoryException: A program „System.OutOfMemoryException” típusú kivételt váltott ki.
   a következõ helyen: System.Collections.ArrayList.GetEnumerator()
   a következõ helyen: System.Windows.Forms.ListViewItem.UpdateStateFromListView(Int32 displayIndex, Boolean checkSelection)
   a következõ helyen: System.Windows.Forms.ListView.OnHandleDestroyed(EventArgs e)
   a következõ helyen: System.Windows.Forms.Control.WmDestroy(Message& m)
   a következõ helyen: System.Windows.Forms.Control.WndProc(Message& m)
   a következõ helyen: System.Windows.Forms.ListView.WndProc(Message& m)
   a következõ helyen: ShareX.HelpersLib.MyListView.WndProc(Message& m)
   a következõ helyen: System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   a következõ helyen: System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   a következõ helyen: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by davidruhmann** [comment]
@hunti88 Are you familiar with debugging windows applications?  If so, since you can reliably repeat this issue, could you run a debugger on ShareX?  Or even build a Debug version and use the Visual Studio memory profiler?
* [Visual Studio 2015 Community Edition](https://www.visualstudio.com/downloads/download-visual-studio-vs) with [Memory Profiler](http://blogs.msdn.com/b/visualstudioalm/archive/2014/11/13/memory-usage-tool-while-debugging-in-visual-studio-2015.aspx)
* [WinDbg](http://windbg.org/)

**Comment by hunti88** [comment]
Long time ago I used GDB (GNU debugger) on linux, but I'm not familiar with compiling or debuging on windows (I'm not a programmer). But I can give you a test VPS, so one of you could prepare the debugging, and I repeat the issue. Can we do this somehow?

**Comment by davidruhmann** [comment]
Sounds like a worthwhile idea.  Compiling a debug version of ShareX does not take long.  Just have to make sure we can reproduce the issue on the virtual machine.

**Comment by Jaex** [comment]
In your out of memory exception it happen in listview. Every time it uploads it adds new entry to listview. So it is not actually leaking memory but because it keep adding to listview memory usage increases but even then that listview entries not supposed to use that much memory I think, so I'm not sure.

**Comment by hunti88** [comment]
I tried to delete the listview, but but the program got unresponsive, one cpu core went to 100%. The memory usage dropped from 288mb to 257mb, but after a half hour i killed the program from task manager, becouse it was still unresponsive.

Can I somehow contact one of you about debuging on the test vps? Today I had time to install it.

**Comment by davidruhmann** [comment]
@hunti88 Sorry I missed your message.  Were you able to recreate the issue on the virtual machine?

**Comment by hunti88** [comment]
Yes, i was able.
