### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by OHQSaucey** [ShareX/ShareX#882]
I just upgraded to windows 10 and since the upgrade I cannot take screen caps anymore. It just goes to a completely black screen no matter what way I try to take a screen cap.

**Comment by Jaex** [comment]
You must have one security software which blocks softwares taking screen capture.

**Comment by OHQSaucey** [comment]
I do not have any anti virus program installed.

**Comment by Jaex** [comment]
Something must be wrong in your computer then.

**Comment by OHQSaucey** [comment]
Worked before the switch to win10, not sure why it wouldn't now.

**Comment by Jaex** [comment]
Majority of people switched to Windows 10 and nobody reported this that means it can't be to do with ShareX.
