### ISSUE TITLE
Add abort option to the stop record icon in the task bar

### ISSUE THREAD

**Issue by M4GNV5** [ShareX/ShareX#883]
When recording full screen the stop/abort buttons get invisible (or out of the screen dunno)
you can stop & uplaod the recording by pressing the hotkey again or by pressign the icon in the task bar, but you cannot abort it

**Comment by Jaex** [comment]
I will add abort option as right click menu in tray icon.

**Comment by M4GNV5** [comment]
nice thanks :+1:
