### ISSUE TITLE
System Unauthorized Access (Windows 10)

### ISSUE THREAD

**Issue by RDF2050** [ShareX/ShareX#884]
System.UnauthorizedAccessException: Access to the path 'C:\Users\RDF\Documents\ShareX\Backup\ApplicationConfig-2015-08-W32.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.BackupFileWeekly(String filepath, String destinationFolder)
   at ShareX.Program.BackupSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

**Comment by Jaex** [comment]
When you upgrade your Windows to Windows 10 some folders getting permissions changed I think and therefore not allows ShareX to read any file inside that ShareX folder. You must check that ShareX folder permission and fix it. It is not to do with ShareX.

**Comment by Jaex** [comment]
I did some search now and Windows 10 must be did ShareX folder read only. Try to uncheck it from folder options.

**Comment by RDF2050** [comment]
Yeah. That was the problem. 

Thank you.

**Comment by TheDeviantCrafter** [comment]
This message also appears if the documents folder is inaccessible by Windows. In my case I had moved my documents folder to my D drive and then removed that drive. Just posting this in case someone else runs into the same issue.

**Comment by S474N** [comment]
Same problem, but create ShareX personal folder, but after reset is this settings empty and again Error message :(
