### ISSUE TITLE
Warn before uploading to image host site like imgur

### ISSUE THREAD

**Issue by jongampark** [ShareX/ShareX#887]
I hit a menu item wrongly. So, ShareX uploaded a screenshot anonymously.
Deleting itself in time is impossible. Why does it upload anonymously at first without warning?
It should warn : which site it uploads to, whether it's to be done anonymously or not

Also, especially it should provide "delete" linke on imgur when uploading anonymously. If it's not anonymous, users can login to their account and delete whatever images they uploaded. But anonymous upload is not possible to delete and it takes time if you file to remove the image to imgur.

**Comment by Jaex** [comment]
ShareX in first screen capture will show warning are you want to upload. And when you press No in this warning it will just disable uploading.

Also deleting it is not impossible because from main window or history you can open deletion URL of uploaded imgur image.

So everything you write is wrong.

**Comment by 10se1ucgo** [comment]
I've had this happen to me when I did a fresh install and forgot to authenticate. You can request imgur take it down at their [removal request forum](http://imgur.com/removalrequest)

**Comment by jongampark** [comment]
I requested removal last week but it's not deleted yet.

Whether the warning is there or not, also it will be good to let users know to which service it's going to upload especially if it's anonymous..

**Comment by Jaex** [comment]
You can't do user upload without actually fill your account info, so obviously it was anonymous and it have "Deletion URL" in right click menu and in history. So you could instantly remove it.

**Comment by jongampark** [comment]
@Jaex Great! I found such functionality in 'history' view. Actually I looked up people comment on this functionality and sounded like that there was no way to delete with ShareX.
Anyway, right after capturing an image. it shows a view on which it displays the image file name. On its contextual menu, there is no such menu item like "Deletion URL", although there is one like "Delete file locally" and others. (shown below)

![2015-08-10_18-04-31](https://cloud.githubusercontent.com/assets/138396/9187877/67556d98-3f8a-11e5-9d7a-0f04a222ace5.png)

So, it's kind of hard or un-intuitive to guess that there will be deletion functionality in 'history' view.

**Comment by Jaex** [comment]
It is in Open sub menu. There is nothing hard to know this.

**Comment by jongampark** [comment]
@Jaex Probably your intuition is different from mine. "Open" sounds like opening a file for viewing, editing, and so on. Well.. for "Deletion URL", it kind makes sense once you see it and think about it, but please think about it freshly. Open an image to delete it? It sounds weird. 

Well, it's about opening a URL, which is for deleting the image on imgur. So, in that,  it makes sense, but isn't "deleting a image with address, URL" more intuitive?

**Comment by 10se1ucgo** [comment]
Sounds more like opening the deletion URL.

**Comment by chebz** [comment]
First time user here... Obvioulsy don't know all tricks so I had to google to this page to resolve accidently "uploading" my bank statement... UX for this is terrible. Why is anonymous public upload button even there? What made you come to this strange decision? And I had to dig through a bunch of convoluted menu options to figure out how to delete it. This software is not good for anything sensitive.

**Comment by Soldiershak** [comment]
The author doesn't seem like they'll budge, but this is not a smart decision luckily i made this mistake with a silly snapshot

**Comment by antingxchia** [comment]
I believe this can solve the issue a bit for accidentally uploading, you could select in "After capture tasks" > "Show "after capture" Window" and in there you can select options you it to do either upload or just save or copy. This way you get a "warning" before all captured image.

With that said the Open>"Deletion URL" open is greyed out for me with my trial image...

**Comment by JNavas2** [comment]
Please **reopen** this issue.
I want to be able to use ShareX as an **image editor** _without uploading_.
Currently, there doesn't seem to be a way to do that.

**Comment by ks202005** [comment]
> I want to be able to use ShareX as an **image editor** _without uploading_. Currently, there doesn't seem to be a way to do that.

In the main ShareX window, on the sidebar, click "After capture tasks" and uncheck "Upload image to host". Here's a [video to explain more](https://www.youtube.com/watch?v=urhTU9yMxr4).
