### ISSUE TITLE
No portable version for release 10.1.0

### ISSUE THREAD

**Issue by notnsane** [ShareX/ShareX#888]
For now I'll keep using 10.0.0 but I try as much as I can to avoid installers.
Please keep creating these for the following releases.

**Comment by Jaex** [comment]
I removed portable mode from installer for next release and will release zip again.

**Comment by notnsane** [comment]
Awesome Jaex! As a small suggestion, if you can put a small link for portable version in the getsharex.org website, that would be great too. If not, I'll live =P

**Comment by Jaex** [comment]
That website not mine so I can't put...
