### ISSUE TITLE
Run as a service

### ISSUE THREAD

**Issue by Two-Tone** [ShareX/ShareX#889]
It would be nice if I could run ShareX as a service in the background when windows starts. That way I could run it without the need to have it cluttering up my task bar. If I need to open it up I'd just open it via my start menu.

**Comment by Jaex** [comment]
I'm not planning to run it as a service.

**Comment by Two-Tone** [comment]
What about other users who'd want to run it as a service?

**Comment by Jaex** [comment]
I mean I'm not planning to make service only ShareX version.

**Comment by Two-Tone** [comment]
I'm not saying a service only version, just have the program have the ability to run as a service so it can truly run in the background.
