### ISSUE TITLE
Imgur upload fail

### ISSUE THREAD

**Issue by SamEvansTurner** [ShareX/ShareX#891]
I'm getting the following error whenever I try and upload to imgur

Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
\<html>
\<head>\<title>405 Not Allowed\</title>\</head>
\<body bgcolor="white">
\<center>\<h1>405 Not Allowed\</h1>\</center>
\<hr>\<center>nginx\</center>
\</body>
\</html>

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by ATrigger** [comment]
Got the same error, so it's true.
StackTrace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2015-08-10 12:51:23.451 - Task failed. Filename: 2015-08-10_12-48-04.png, Errors:
Message:
Удаленный сервер возвратил ошибку: (405) Недопустимый метод.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


StackTrace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2015-08-10 12:51:31.024 - ApplicationConfig save started: C:\Users\Lenovo\Documents\ShareX\ApplicationConfig.json
2015-08-10 12:51:31.543 - ApplicationConfig save successful: C:\Users\Lenovo\Documents\ShareX\ApplicationConfig.json

**Comment by HitomiTenshi** [comment]
Same here.

**Comment by ATrigger** [comment]
It works now for me.

**Comment by HitomiTenshi** [comment]
Must've been some temporary api breakdown? Works here too again.

**Comment by SamEvansTurner** [comment]
Yep, working for me now too. Must have been a temporary API thing.

**Comment by Jaex** [comment]
Imgur was down.

**Comment by HitomiTenshi** [comment]
actually imgur wasn't down, I checked the site when I wasn't able to upload and it was still up and running normally.

**Comment by Jaex** [comment]
We don't use their website. We using their API. So I meant their API was down.

**Comment by preddyweddydaddy** [comment]
im getting this issue right now. Just me or is something down?
