### ISSUE TITLE
imgur Upload fails on images over 10K in size

### ISSUE THREAD

**Issue by adamnoffie** [ShareX/ShareX#893]
I'm getting this error message when ShareX attempts to upload an image over a certain size (seems to be about 10KB) to imgur.  This just suddenly started happening today.  I checked imgur API status and they do not seem to be aware of any issue yet, but I suppose it is still possible it is on their end. 

Notice that many work, but many don't, and it seems to be a size cut-off (in terms of file size, not image - a huge image of blank white space still uploads fine, but a small image of a complicated photo or text won't upload):
![2015-08-10_15-30-57](https://cloud.githubusercontent.com/assets/98626/9183469/d28fc588-3f74-11e5-9008-1f543ab726c9.png)

````
Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
````

**Comment by Jaex** [comment]
Problem in their end.

**Comment by 10se1ucgo** [comment]
Having this issue as well, didn't use to happen before. Not sure why it's happening now.

**Comment by Jaex** [comment]
#892, #891, #890, #749, #657, #533, #522, #426

**Comment by adamnoffie** [comment]
Ah, sorry I didn't see the other issues before.  Will try again tomorrow.
