### ISSUE TITLE
Question about [~] key to capture active monitor

### ISSUE THREAD

**Issue by Shadorc** [ShareX/ShareX#897]
Hi !

In tips, you say "[~] Active monitor capture" but how to use [~] key ?
I see where it's on the keyboard but it's on the same key that [2] also used by "[1, 2, 3 ... 0] Monitor capture". 
I tried by pressing [Alt Gr]+[~] but it did nothing...
So, I don't see how to use this key...

Or "~" doesn't indicate the key on the keyboard but means something else then in that case I don't understand...

Thanks for your help !

**Comment by Jaex** [comment]
That key also not in that place it is supposed to be in my keyboard. But I gave it according to standard key layout. So I'm pressing " key in my keyboard which is left side of 1 key. So it must be left key of 1 key in all keyboards I think.

**Comment by Shadorc** [comment]
Oh, okay, my AZERTY keyboard is similar to this one and it's not uncommon.
![azerty](https://cloud.githubusercontent.com/assets/6506416/9214881/99a4e99e-40a3-11e5-837d-54bcfdc009d3.jpg)
So, it's impossible to use this shortcut with this kind of keyboard, that's what I thought. 

Thank you for the quick response!

**Comment by Jaex** [comment]
I told you my ~ key in right side of keyboard but still I press left top button and it works. Are you sure that not works for you?

**Comment by Shadorc** [comment]
No, it doesn't work, I tried.
I can try with another computer.

**Comment by Shadorc** [comment]
I tried with a laptop and it doesn't work either.

**Comment by Jaex** [comment]
How you open console in games then all using ~ key for it.

**Comment by Shadorc** [comment]
In France, all games use ² key who is at the same place

**Comment by Jaex** [comment]
And which key it corresponds in here if it is not tilde: https://msdn.microsoft.com/en-us/library/system.windows.forms.keys(v=vs.110).aspx

**Comment by Shadorc** [comment]
I have not found the key in the list.
I have searched on the internet and it seems to be a recurring problem, it seems that this is the key Oem7

**Comment by Jaex** [comment]
Oemtilde must be corresponding to single button in your keyboard too did you found it? Because it can't be same button as number keys.

**Comment by Shadorc** [comment]
I tried all the keys that aren't used in the tips.
Oemtilde seems to correspond to that one
![99a4e99e-40a3-11e5-837d-54bcfdc009d3](https://cloud.githubusercontent.com/assets/6506416/9240884/2eecd5c0-416c-11e5-8055-7eeefab79870.jpg)

**Comment by Jaex** [comment]
Then I don't need to fix it if there is key for it in your keyboard. I mean there is keyboard layout for each country it is impossible for me to find equivalent of these for each layout anyway. Not to mention translation can be problematic for it too because tilde key in translation text.

**Comment by Shadorc** [comment]
I didn't think to try all the keys...
Do you prefer that I change French translation to replace [~] by [ù] or no ?

**Comment by Shadorc** [comment]
Or perhaps replace [~] by [0] and "[1, 2, 3 ... 0] Monitor capture" by "[1, 2, 3 ... 9] Monitor capture".
It will reduce the number of screens from 10 to 9 but isn't it enough ?

**Comment by Jaex** [comment]
0 key require you release your hand from mouse and press it with right hand. Because it is far from your left hand. Writing [ù] [~] both of it in French translation can be better solution?

**Comment by Shadorc** [comment]
Ok, I change it.
Anyway, [ù] and [0] are quite close on a French keyboard so it doesn't change much.
