### ISSUE TITLE
"[Hold Shift] Proportional resizing" doesn't work in 10.1

### ISSUE THREAD

**Issue by Shadorc** [ShareX/ShareX#898]
Hi ! 
It's me again... (sorry)

I'm currently testing all the tips shortcuts to translate in French and I discovered another bug.

"[Hold Shift] Proportional resizing" works perfectly in ShareX 10.0 but doesn't work anymore in version 10.1.

**Comment by Jaex** [comment]
It is already fixed and you can find beta version from IRC title.

**Comment by Shadorc** [comment]
Ok, sorry for the duplicate issue !

**Comment by Jaex** [comment]
It is not your fault this was not reported in GitHub :P
