### ISSUE TITLE
Different Destinations based on Keyboard shortcut used?

### ISSUE THREAD

**Issue by jasondavis** [ShareX/ShareX#901]
Is it currently possible to upload to a different Destination based on a keyboard shortcut?

For example my default location might be `imgur` and then I want to upload to `FTP` when I use the keys `ctrl+f` just for an example?

**Comment by Jaex** [comment]
Yes it is possible.
Edit your hotkey and it will open this window:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/08/pyeKrIxPWI.png)
