### ISSUE TITLE
Snap to common resolutions

### ISSUE THREAD

**Issue by Timmmm** [ShareX/ShareX#903]
At the moment when selecting a region to screen-record you can hold shift to make the region square.

Can I suggest making control snap to common resolutions, e.g.:

800x600  (SVGA)
1280x720   (720p)
1024x768   (XGA)
1920x1080   (1080p)

**Comment by Jaex** [comment]
Problem is everybody can have their own resolution preference so I needed to add resolution list support so people can add their preferred resolutions but I'm lazy to do that :/
But it is good idea.

**Comment by Timmmm** [comment]
I think the preset list I gave is better than nothing. I had a look at the code and it doesnt look too hard to add so I might have a go.

**Comment by Jaex** [comment]
I'm pretty sure someone will open issue and ask for custom resolution support. So list is required.

**Comment by Jaex** [comment]
Actually I don't need to make UI for it because I was using property grid for region capture settings which automatically fills from settings. So I can just have list there and it can make List editor itself. If you are not working on it I can give it a try.

**Comment by Timmmm** [comment]
I'm on holiday for two weeks now so at I won't attempt it for at least that
long...

**Comment by Jaex** [comment]
What you think default pixel distance should be for snap to happen?

**Comment by Timmmm** [comment]
I would choose the closest snap point (exhaustive search) then reject it if
it is more than.... say 200 pixels away? I think the snap distance can be
large because the user is actively pressing a modifier.

**Comment by Jaex** [comment]
I was going to use same modifier as proportional resizing but you suggest to use different modifier then.

**Comment by Timmmm** [comment]
Yeah I'd say use control as it isn't used for anything else at the moment.
Though I supppose reusing shift makes writing the code easier! I don't mind
either way.

**Comment by Jaex** [comment]
I added it now but it not easy to differentiate 1280x720 vs 1024x768 because of how i check width and height instead of using trigonometry to check distance of two points I think :/

**Comment by Timmmm** [comment]
Thank you so much! I think your logic may be not quite optimal though; e.g. it finds the first size within range rather than the closest one. And I think you meant && rather than || in the comparison.

How about this instead? Sorry if this doesn't compile; it's actually the first C# I've ever written! I also haven't tested it...

		private Point SnapPosition(Point posOnClick, Point posCurrent)
		{
			Rectangle currentRect = CaptureHelpers.CreateRectangle(posOnClick, posCurrent);
			Point newPosition = posCurrent;
			
			Size closestSize = null;
			double closestDistance = Double.PositiveInfinity;
			
			foreach (Size size in surface.Config.SnapSizes)
			{
				double thisDistance = Math.Sqrt((currentRect.Width  - size.Width)  * (currentRect.Width  - size.Width) +
			                                    (currentRect.Height - size.Height) * (currentRect.Height - size.Height));
												
				if (thisDistance < closestDistance && thisDistance < surface.Config.SnapDistance)
				{
					closestDistance = thisDistance;
					closestSize = size;
				}
			}
			if (closestSize == null)
				return posCurrent;		
		
			if (posCurrent.X > posOnClick.X)
			{
				if (posCurrent.Y > posOnClick.Y)
				{
					newPosition = new Point(posOnClick.X + closestSize.Width - 1, posOnClick.Y + closestSize.Height - 1);
				}
				else
				{
					newPosition = new Point(posOnClick.X + closestSize.Width - 1, posOnClick.Y - closestSize.Height + 1);
				}
			}
			else
			{
				if (posCurrent.Y > posOnClick.Y)
				{
					newPosition = new Point(posOnClick.X - closestSize.Width + 1, posOnClick.Y + closestSize.Height - 1);
				}
				else
				{
					newPosition = new Point(posOnClick.X - closestSize.Width + 1, posOnClick.Y - closestSize.Height + 1);
				}
			}

			Rectangle newRect = CaptureHelpers.CreateRectangle(posOnClick, newPosition);

			if (surface.ScreenRectangle0Based.Contains(newRect))
			{
				return newPosition;
			}

			return posCurrent;
		}

**Comment by Timmmm** [comment]
PS: I'd probably change "How much region size must be close to snap size for it to snap." to "How close to a snap size you must be for it to snap."

**Comment by Jaex** [comment]
I started to regret adding this because property grid control caused me problem which I can't find solution: http://stackoverflow.com/questions/31998479/how-to-edit-listsize-in-propertygrid

**Comment by Jaex** [comment]
Later when I think my width or height checking will be more easier for people than using trigonometry distance code because this is more flexible, like you can drag vertical line and when you are close to 800 height it will snap, instead of trying to find width position too.

**Comment by Jaex** [comment]
I noticed now using ctrl key was bad idea because while trying #929 and trying to move cursor fast holding ctrl it was snapping. So I must find new key for this now :(

**Comment by Jaex** [comment]
I will add these as default snap sizes:

                new SnapSize(426, 240), // 240p
                new SnapSize(640, 360), // 360p
                new SnapSize(854, 480), // 480p
                new SnapSize(1280, 720), // 720p
                new SnapSize(1920, 1080), // 1080p
                new SnapSize(2560, 1440), // 1440p
                new SnapSize(3840, 2160), // 2160p
                new SnapSize(800, 600), // SVGA
                new SnapSize(1024, 768), // XGA
                new SnapSize(4096, 2160) // 4K

**Comment by Timmmm** [comment]
Awesome! What about using a toggle key instead of a modifier if there
aren't any spare modifiers? Similar to how the crosshairs are
enabled/disabled.
