### ISSUE TITLE
Force imgur https

### ISSUE THREAD

**Issue by Phoenix616** [ShareX/ShareX#904]
This is a suggestion to build in a way to force imgur uploads to display https links instead of just http. Besides the obvious benefits of ssl this would be useful for embedding images directly in secure site without browser complaining about mixed contents.

The thumbnail and deletion url wouldn't be a problem in the current [code](https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/ImageUploaders/Imgur.cs#L258), but the image url is get [directly](https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/ImageUploaders/Imgur.cs#L219) from the response imgur sends, which contains only http although them fully supporting https.

The question here is: would it make sense to force https via replacing the http in the response url?

**Comment by Jaex** [comment]
You can use this setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/08/ShareX_OPQV5KBiSb.png)

**Comment by Phoenix616** [comment]
This option breaks sites that don't support https 'though.

**Comment by Jaex** [comment]
How you know that it not gonna break imgur in future? They are not officially support https, none of the links they give have https. Just because it works doesn't mean it will work in future too.
