### ISSUE TITLE
Add a magic-wand tool to capture selection.

### ISSUE THREAD

**Issue by o7c** [ShareX/ShareX#906]
Would make it extremely easy for captures of perfect captures of images (eg if they had a border, or were surrounded by unsimiliar content)

See:
https://github.com/wangdeshui/paint.net/search?utf8=%E2%9C%93&q=FloodToolBase

for a previous C# implementation

**Comment by Jaex** [comment]
I never saw in my life one screen capture software have magic wand capture. You are supposed to use image editor for such things.

**Comment by o7c** [comment]
Don't be so naive, its a feature that minimizes time, just as the capture selection tool does, (removes the need to import and crop the image straight away)

**Comment by Jaex** [comment]
It never gonna work unless you only want to capture single color thing. So it is very bad idea.
