### ISSUE TITLE
Can't take a screenshot while Google Chrome is active window

### ISSUE THREAD

**Issue by xREITYD** [ShareX/ShareX#914]
Hey, so I updated to Win10 and since then I'm having a problem taking screenshots while Google Chrome is the active window. It just doesn't do anything. However if I click out of the Google Chrome tab it the keybinds work normally. Any ideas what could be the problem and how to fix it?

**Comment by Kesmy** [comment]
Chrome > Settings >  Extensions > Keyboard Shortcuts, at the bottom of the page... it is likely an extension has control of one of the shortcuts.

**Comment by Jaex** [comment]
Mainly when in specific window is hotkey system of ShareX not works then it is not to do with ShareX. You can blame Windows hotkey system for this or window/software for not letting hotkey input to let through window.
But problem is majority of people using Chrome and nobody reported this issue so I'm not really sure how Chrome not let hotkey reach to ShareX :(

**Comment by xREITYD** [comment]
It's probably something with Windows 10, I also have a problem that I've to delete Chrome registers through regedit for it to be launchable from the taskbar and after the first launch it bugs out again. I hate Windows 10. I also can't use AHK script in Google Chrome, no idea what is going on, sadly on their forums and on W10 reddit I've got no responses.

**Comment by nacisimsek** [comment]
I was also having this issue when I try to take screenshot via control button on the logitech mouse. The logi options+ app I use was having customizations for browser apps, then found that the control button shortcut was set differently for chrome. I updated the control button shortcut to have the same value for all apps defined on logi options app and problem solved.
