### ISSUE TITLE
Webm issue

### ISSUE THREAD

**Issue by Lulwat** [ShareX/ShareX#915]
Jaex

You close post so i cant respond XD

I did all of the settings but when i choose screen recording (gif), the file size is still incredibly big.

**Comment by Jaex** [comment]
You can post closed issues?

**Comment by Lulwat** [comment]
huh? as i said, i have it set to Webm but the file size is still really big. Not sure it has worked.

**Comment by Jaex** [comment]
You telling you using gif recording not normal recording. Also you aware that you can't upload webm to imgur right?

**Comment by Lulwat** [comment]
All i want to do is upload a gif to imgur but a 5 second gif is like 50MB.

**Comment by Jaex** [comment]
This is how gif is.

**Comment by Lulwat** [comment]
Then how can i send smooth gifs to friends.

**Comment by Jaex** [comment]
Record mp4 and upload it to something like Up1 file host. It will be more smooth and very small size.

**Comment by Lulwat** [comment]
Up1 only shows the last second of the webm...
