### ISSUE TITLE
Low priority: Settings issue

### ISSUE THREAD

**Issue by vatterspun** [ShareX/ShareX#918]
Setup: Win7x64

Steps:

1. Open ShareX
2. Click Hotkey settings
3. Click on a hotkey (e.g. Capture Rectangle, set on my system to CTRL+SHIFT+R)
4. Press ESC (cancel)

Defect: Hotkey switches to "None"

Expected result: Reverts to previous setting (in my case CTRL+SHIFT+R)

**Comment by Jaex** [comment]
If I make it revert to previous setting then you can't disable hotkey. And If you are wondering why have hotkey if you not gonna set hotkey for it? Because you can use these tasks from Workflow menu so it don't need to have hotkey to work. So it works as intended.

**Comment by vatterspun** [comment]
Dude.  You might want to give folks a chance to reply before you close+invalid an issue.  Just future reference.

**Comment by Jaex** [comment]
People can reply after it is closed too.

**Comment by vatterspun** [comment]
That's not my point.  If you want input/feedback, this is not a good way to inspire that.

**Comment by Jaex** [comment]
People can give input/feedback when it is closed too. If I let every issue stay open how am I supposed to find more high priority active issues?

**Comment by vatterspun** [comment]
Wow.  Again, not my point.  Certainly you've got to close issues.  Certainly some issues are invalid.  However, some folks will take an immediate closed+invalid as a pretty strong dismissal of something they put time and effort into.  I'm well aware you're going to have to decline most suggestions, maybe even 95%.  But you might want to find a way that encourages users to come back if you want to inspire input/feedback.  Otherwise, you're just going to get bug reports and that's got to be boring.

**Comment by Jaex** [comment]
I don't know what you mean inspiring etc. I don't plan to do what you suggested therefore I closed it. I'm not robot, can't delay issue closing by time. And I can forget to close them in future then. Why would I risk forgetting closing when it is supposed to be closed. I really don't understand what you trying to tell.
