### ISSUE TITLE
Feature Request: Standard after capture tasks interfering with Auto Capture

### ISSUE THREAD

**Issue by vatterspun** [ShareX/ShareX#919]
Use Case: Since I use Auto-Capture to quickly track weird behavior in other programs, remembering each time to turn off my "After Capture" tasks is sometimes problematic.  So for example, right now I have my screen capture action followed by opening the image with Paint.NET [setup described here: http://www.portablefreeware.com/forums/viewtopic.php?p=75688]

Steps:

1. Setup some After Capture tasks
2. Select Capture - Auto Capture

Defect: the auto-capture process is interrupted by each image being opened by Paint.NET, essentially disabling this feature

Possible resolutions:

1. Nothing.  User remembers to turn off after capture tasks each time or runs a separate instance of ShareX (this is the current setting and might make the most sense)
2. Add a checkbox to the auto-capture window to enable/disable actions that may interfere with the auto-capture process.
3. Add another type of auto-capture called "stealth" auto-capture that captures everything happening on the screen with some default settings and no user prompts.  This would probably not be present by default but enabled in settings.

**Comment by Jaex** [comment]
As a workaround you can create auto capture hotkey and disable after capture tasks in this hotkey. Then run this from Workflows menu instead of Capture menu. This workaround good enough I think?

**Comment by vatterspun** [comment]
Yeah, I didn't think about that.  I just ran through the Hot Key Settings - Add sequence and the "default after capture" checkbox is RIGHT THERE.  So yeah, that's more than adequate.

Also, it makes sense that intelligent automation features should really have their own camp where you add and remove items to improve functioning rather than letting the "smart" stuff affect the development of the rest of the program.

Anyway, this feature request can be cancelled/closed.  Thanks.
