### ISSUE TITLE
False positive with MBAM?

### ISSUE THREAD

**Issue by flatlinee** [ShareX/ShareX#920]
After DLing newest update, 10.1, MBAM marks three files as containing Trojan.Downloaders:

/Program Files/ShareX/recorder-devices-setup.exe;
/Appdata/Temp/ShareX-10.0.0-setup.exe;
/Appdata/Temp/ShareX-10.1.0-setup.exe.

Doing a virustotal scan reveals these to be most likely false positives. (I already quarantined the files so these are scans from a friend)
https://www.virustotal.com/en/file/70887b7616b4524ee5d79e06ca0e5865f4a8915d8c04e921c0ed8b32e350d7e2/analysis/

Just thought I would let you know in case you want to resolve the issue with MBAM.  I already have someone telling them as well.

**Comment by Jaex** [comment]
I already reported it as false positive to their support and waiting response from them.
In VirusTotal you can see: ```Detection ratio:	1 / 56```

**Comment by flatlinee** [comment]
Yeah, I saw that, I just wanted to get some official response on it cause it freaked me the hell out.  I'm naturally a bit paranoid about this stuff but thanks for being so quick about it!

**Comment by Jaex** [comment]
Malwarebytes response:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/08/Vvp3WOeq2e.png)

**Comment by Jaex** [comment]
Second response:

![](http://i.imgur.com/u5HOogY.png)

They telling it is fixed.

**Comment by Brycey92** [comment]
/Program Files/ShareX/recorder-devices-setup.exe is now being reported as a trojan downloader again.

**Comment by Jaex** [comment]
@Brycey92 I scanned ShareX folder now with MBAM and it not found anything:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/10/mbam_1vj9RgzMn4.png)
