### ISSUE TITLE
malwarebytes detected a sharex installer as a trojan downloader

### ISSUE THREAD

**Issue by lafingman0** [ShareX/ShareX#921]
came home from work to find a popup from malwarebytes that it found this as malware. false positive?
http://i.imgur.com/MNGy38k.png

**Comment by Decicus** [comment]
Issue #920 already reports this. It's a false positive, as the [VirusTotal](https://www.virustotal.com/en/file/70887b7616b4524ee5d79e06ca0e5865f4a8915d8c04e921c0ed8b32e350d7e2/analysis/) from that report also shows it's only Malwarebytes detecting it.

**Comment by lafingman0** [comment]
alright, thanks!
________________________________

**Comment by Jaex** [comment]
I reported false positive to Malwarebytes support and this was their response:

![](http://i.imgur.com/u5HOogY.png)

So they confirmed it was false positive too.

**Comment by Jaex** [comment]
#920
