### ISSUE TITLE
Screen recording does not work on Hidpi screens

### ISSUE THREAD

**Issue by sibbl** [ShareX/ShareX#923]
When recording a screen capture which is quite big, the app crashes when stopping/aborting the record.

When I start the record with a big rectangle, I get this output window:
![output window](https://cloud.githubusercontent.com/assets/866535/9306665/01208aa6-44fa-11e5-935a-edee83504089.png)

It's indeed strange that it says "1600,900" whereas my resolution is 3200x1800 with a scaling of 200%. I guess some parameters are passed to ffmpeg, which don't include the scaling factor of the current resolution? It works for small resolutions (I guess because they're smaller than 1600x900), but everything above let's the app crash.

**Comment by davidruhmann** [comment]
If you manually attempt the same recording with numbers adjusted for DPI scaling does the recording come out correctly?

```
ffmpeg -y -rtbufsize 100M -f gdigrab -framerate 20 -offset_x 80 -offset_y 70 -video_size 832x604 -draw_mouse 0 -i desktop -c:v libx264 -r 20 -preset veryfast -tune zerolatency -crf 30 -pix_fmt yuv420p "output.mp4"
```

Press <kbd>Ctrl</kbd> + <kbd>C</kbd> to stop the recording.

Possibly related FFmpeg issues:
* http://trac.ffmpeg.org/ticket/4232
* http://trac.ffmpeg.org/ticket/4505

**Comment by Jaex** [comment]
FFmpeg gdigrab device have problem.
Try using these devices:

![](http://i.imgur.com/7NuKPWL.png)

**Comment by Jaex** [comment]
@davidruhmann I didn't know existence of keyboard syntax and was using inline code syntax in changelog to highlight keys :D

**Comment by davidruhmann** [comment]
The kbd tag has been around since [HTML 2 it seems](http://reference.sitepoint.com/html/kbd), can't remember when I first learned it, but it was years ago.  Here is the [GitHub markdown HTML whitelist](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L44) for a full list of supported HTML tags:
```
WHITELIST = {
        :elements => %w(
          h1 h2 h3 h4 h5 h6 h7 h8 br b i strong em a pre code img tt
          div ins del sup sub p ol ul table thead tbody tfoot blockquote
          dl dt dd kbd q samp var hr ruby rt rp li tr td th s strike summary details
        ),
```

**Comment by sibbl** [comment]
Thanks for the help! Installing the recorder devices helped. Is this documented somewhere? I did some research before posting the issue and didn't find this anywhere...?

However, recording works now, but the cursor is misaligned and the X and Y coordinates are half the size they should be. I guess the scaling factor is not multiplied there as well. See http://i.imgur.com/K29Q3jB.gifv - I moved the cursor around the inner circle and in the final video it's misaligned.

**Comment by Jaex** [comment]
Cursor issue here: https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/56

**Comment by sibbl** [comment]
Thanks. Could not find it searching for "cursor" -.-

**Comment by Jaex** [comment]
Look like it is finally fixed in FFmpeg: https://trac.ffmpeg.org/ticket/4232
Can someone who had issue before, download latest FFmpeg from ShareX screen recording options window and test it?

**Comment by Jaex** [comment]
#1329 In latest ffmpeg release gdigrab video source cursor position fixed, can you test it?
