### ISSUE TITLE
[Request] Please add menu button to "Open clipboard image into Greenshot Editor"

### ISSUE THREAD

**Issue by snyfear** [ShareX/ShareX#924]
Hi,

Congratulation for your soft which replaced my old Greenshot. The only functionality I miss is the greenshot menu button which permit to open a image from the clipboard into Greenshot editor in order add some annotation.

Sorry if this function is already available but I could not find how to perform this action in ShareX 10.0.

**Comment by Scrxtchy** [comment]
ok
![](http://sharex.moe/i/2015/08/15-08-21_09-56-29.png)

**Comment by Jaex** [comment]
While opening image editor it will check is clipboard contains image and show this message box accordingly:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/08/ShareX.vshost_Tq8VGXnJdZ.png)

**Comment by snyfear** [comment]
Cool, I didn't expect a so quick implementation.
 I can not wait to test this in the portable version ;)

Thank you and congratulation for your application.
