### ISSUE TITLE
Cannot use ShareX with numerous Active Windows

### ISSUE THREAD

**Issue by OhBizzle** [ShareX/ShareX#925]
This is an odd issue, because prior today this was not an issue at all. I have not updated ShareX nor any other application. I'm using Win10 x64.

If WoW, or Mumble is my active window I cannot use the ShareX hotkeys. If chrome, photoviewer, or file explorer are the active window I can use the hotkeys.

**Comment by OhBizzle** [comment]
Disabling UAC + Reboot fixed it, maybe just a Reboot would've worked.

Just odd because there was a similar report with this issue but Chrome casuing it a couple posts back.

**Comment by davidruhmann** [comment]
I have experienced this issue as well, though it is intermittent.  Sometimes the screenshot will work, later on it won't with the same program.  Only occurs on my Windows 10 desktop computer when using the <kbd>Alt</kbd> + <kbd>Print Screen</kbd> hotkey.  Once I get a chance, I will try some more testing.

Related #914

**Comment by ngzero** [comment]
Same issue here, Hotkeys are not working if Hyper-V Windows is active/has focus.

**Comment by Jaex** [comment]
This is not issue, if window not let key press reach to this hotkey system which made by Microsoft then there is nothing I can do about it. Other than using global keyboard hook as hotkey system which I prefer to not.

**Comment by ShadowMax** [comment]
> Reboot fixed it.
I use this option too, It's worked for me, but...maybe another way? or when this problem exacly happened\appears?

**Comment by ShadowMax** [comment]
Instal ShareX exsistention, maybe this will help.

**Comment by ledlamp** [comment]
> Other than using global keyboard hook as hotkey system which I prefer not to.

I would prefer this!! I can't use sharex hotkeys on administrative windows and it gets really annoying >:(
