### ISSUE TITLE
Windows 10 Capture Region (Objects) = Region

### ISSUE THREAD

**Issue by ngzero** [ShareX/ShareX#928]
If Region (Objects) is set then no Objects and even no windows are selected.
I can only draw a custom region frame.

**Comment by Jaex** [comment]
I remember one case this was happening to one user. It was his anti virus having invisible window in front of everything and therefore object was highlighting whole area. So it was not to do with ShareX.

**Comment by ngzero** [comment]
I have no antivirus installed. just a blank windows 10.... Very strange after a reboot it works again.
