### ISSUE TITLE
ShareX settings don't save

### ISSUE THREAD

**Issue by Quanteum** [ShareX/ShareX#934]
really really loves this app but settings don't save! i have to redownload FFmpeg.exe and i have to edit the dropdown region capture settings every time i restart the application. it's very infuriating. do you know what may be causing my problem? Windows 8.

**Comment by Jaex** [comment]
Are you not even minimize your ShareX to tray? Because when minimizing to tray it save all settings. So even if your Windows forcing ShareX to be closed before it save settings still because of minimizing it should be saving them?

**Comment by Quanteum** [comment]
i am minimizing ShareX to tray. everything works until when i physically restart the app, from either a computer shutdown or clicking the 'Exit' button on the ShareX tray menu, or killing it in task manager.

**Comment by Jaex** [comment]
Can you check debug log is it says anything about save fail.

**Comment by Quanteum** [comment]
http://i.imgur.com/RH8sLjq.png

it's saying permission denied--let me see if i can take ownership of those files.

**Comment by Jaex** [comment]
Try to get ownership of Documents/ShareX folder.

**Comment by Quanteum** [comment]
i can't seem to get ownership. i've tried multiple times but it still resets. any other ideas?

**Comment by Jaex** [comment]
Try to make that folder not read only.

**Comment by Quanteum** [comment]
hooray! i managed to solve it by a combination of using the take ownership registry hack and changing the owner of the folder to Administrators (which i am). thanks so much jaex!

**Comment by Jaex** [comment]
How that folder got ownership broken like that?

**Comment by Quanteum** [comment]
i have no idea, to be honest. i changed the "owner: " from users to administrators and now it saves! i might have tampered with it a long time ago (im pretty sure i didnt, but i dont remember if i did) because ive used ShareX for a while but only recently started to care about customizing its more in depth options.
