### ISSUE TITLE
How can I get ShareX to start automatically with admin privileges

### ISSUE THREAD

**Issue by quvide** [ShareX/ShareX#94]
The problem is that for some reason certain hotkeys don't work when used when certain windows are active. An example of this is having a hotkey in PRTSCR and having Mumble as the active window. In that situation ShareX will not notice the keypress and windows normally takes a screenshot. This problem is solved by running ShareX as administrator, but I am annoyed to close it and start it again on every starup. Is there a way to do that?

**Comment by Venryx** [comment]
I finally figured out why some hotkeys get blocked on certain windows. See here for details: https://github.com/ShareX/ShareX/issues/334#issuecomment-610259444

Short version: Windows blocks hotkeys when an elevated/admin window is focused, **and** the hotkey in question does not include any modifier keys.

I've long known the first part of that condition, but the second part I just found out a few minutes ago.

It's a bit annoying, but I understand it for security reasons, and it means there is now a workaround: just make sure to include a modifier key in all of your hotkeys. (admittedly, this isn't quite as nice as being able to just hit the one-key "print screen" button, but it's better than the annoyance of the hotkey sometimes not-working/requiring-focusing-a-different-window)

**Comment by vassilyzaitsev** [comment]
The problem for me is that if I open ShareX with admin rights I can't drag and drop files from explorer.
Current solution for me is this AutoHotkey script that activates the taskbar before starting a capture:

> PrintScreen::
> 
> WinGet ProcessID, PID, A
> 
> if IsProcessElevated(ProcessID)
> 	WinActivate, ahk_class Shell_TrayWnd
> 
> Send {PrintScreen}
> return
> 
> IsProcessElevated(ProcessID)
> {
> 	if !(hProcess := DllCall("OpenProcess", "uint", 0x1000, "int", 0, "uint", ProcessID, "ptr"))
> 		throw Exception("OpenProcess failed", -1)
> 	if !(DllCall("advapi32\OpenProcessToken", "ptr", hProcess, "uint", 0x0008, "ptr*", hToken))
> 		throw Exception("OpenProcessToken failed", -1), DllCall("CloseHandle", "ptr", hProcess)
> 	if !(DllCall("advapi32\GetTokenInformation", "ptr", hToken, "int", 20, "uint*", IsElevated, "uint", 4, "uint*", size))
> 		throw Exception("GetTokenInformation failed", -1), DllCall("CloseHandle", "ptr", hToken) && DllCall("CloseHandle", "ptr", hProcess)
> 	return IsElevated, DllCall("CloseHandle", "ptr", hToken) && DllCall("CloseHandle", "ptr", hProcess)
> }
>

**Comment by tooruu** [comment]
put `CreateObject("WScript.Shell" ).Run """C:\path to\ShareX.exe""", 0` in `shell:startup`

**Comment by Mishatopkek** [comment]
If someone use steam and steam placed in a program files (x86), you can type this command `schtasks /create /sc onlogon /tn ShareX /rl highest /tr ""${env:CommonProgramFiles(x86)}\Steam\steamapps\common\ShareX\ShareX_Launcher.exe" -silent"`

**Comment by Cardinal67** [comment]
> Just if someones wondering how to add -silent argument use following command.
> 
> schtasks /create /sc onlogon /tn ShareX /rl highest /tr ""C:\Program Files\ShareX\ShareX.exe" -silent"
> 
> (Credits to zingmars for the original command.)

If this didn't work for anyone, try this instead: (powershell friendly)
schtasks /create /sc onlogon /tn ShareX /rl highest /tr '"C:\Program Files\ShareX\ShareX.exe" -silent'

**Comment by Venipa** [comment]
powershell
```pwsh
schtasks /create /sc onlogon /tn ShareX /rl highest /tr "'C:\Program Files\ShareX\ShareX.exe' -silent"
```
