### ISSUE TITLE
upload speed goes to 0B/s

### ISSUE THREAD

**Issue by Lulwat** [ShareX/ShareX#944]
So when uploading to the destination, the speed starts at around 1B/s and decreases rapidly to 0B/s.

My internet is fine so that is not the issue.

**Comment by Lulwat** [comment]
btw, fixed the problem where it only recorded the last second. Set it to record downwards from a certain time.

**Comment by Lulwat** [comment]
will it do it

https://gyazo.com/a9f3bcfeff99ca47560f093e85eb7c23

**Comment by Lulwat** [comment]
can confirm, it didnt.

**Comment by trdwll** [comment]
Either it's your connection or it's the server that you're uploading to connection.
