### ISSUE TITLE
i did it

### ISSUE THREAD

**Issue by Lulwat** [ShareX/ShareX#945]
fixed the upload speed by going application settings, upload and turning up buffer size from 32KB to 1MB.

fix for future issues

**Comment by Jaex** [comment]
Why you keep non stop opening new issues instead of writing to previous one?

**Comment by Jaex** [comment]
#944

**Comment by Lulwat** [comment]
why u keep close my stuff before issues are solved.

**Comment by Jaex** [comment]
I didn't closed your issue it was open.

**Comment by Lulwat** [comment]
and software broke again ggwp

**Comment by Jaex** [comment]
Your computer is broke. Upload system same for like last 4-5 years and only you reported this. Guess why...

**Comment by Lulwat** [comment]
I have no issues with anything else.
