### ISSUE TITLE
Cannot drag'n'drop files to ShareX window 

### ISSUE THREAD

**Issue by alvinek** [ShareX/ShareX#951]
Until version 10.0 cannot drag'n'drop files to ShareX window. When i got file and i try to move it to ShareX window, it shows mnie forbidden cursor and i cannot do that. 
https://gfycat.com/CourteousMediumEasternglasslizard

**Comment by davidruhmann** [comment]
Is ShareX or explorer running as administrator.  I have seen this occur when explorer and ShareX are running at different permission levels.  One is elevated, the other is not.  If so, this is a limitation of the Windows OS.

**Comment by alvinek** [comment]
After killing explorer.exe and restarting ShareX multiple times it works. Now explorer and ShareX didn't have admin privileges. It's strange because on version 9.9 everything works.

**Comment by Jaex** [comment]
It is not to do with ShareX. Windows decides such stuffs.

**Comment by alvinek** [comment]
So why everything is working fine with version 9.9? Another privileges or something?

**Comment by Jaex** [comment]
How may I know? Drag and drop codes not changed for like last 8 years.

**Comment by alvinek** [comment]
Lol :-) Maybe its magic. Have a good day :)

**Comment by Jaex** [comment]
I wonder is it because right after update setup runs ShareX as admin maybe?

**Comment by alvinek** [comment]
Oh, maybe this is the problem. If setup is runned as administrator, then i wonder it runs applications as administrator too.
