### ISSUE TITLE
image uploading not working for imgur

### ISSUE THREAD

**Issue by Quanteum** [ShareX/ShareX#953]
hi,

im getting this error: http://oi62.tinypic.com/124a1hd.jpg
whenever i try to upload any image to imgur, no matter the size. this error doesnt happen with any other upload destinations.

**Comment by Jaex** [comment]
You need to right click that entries and check error + response.

**Comment by Quanteum** [comment]
woops, sorry. http://oi57.tinypic.com/2a9dwt1.jpg

**Comment by Quanteum** [comment]
i thought it was a server side issue of imgur but it's been this way for a like 4 days now.

**Comment by Quanteum** [comment]
update: got it fixed. just had to reupdate permission settings.

**Comment by TacticalTechJay** [comment]
How did you reupdate permission settings? 🤔
