### ISSUE TITLE
Avira AntiVirus detection ShareX.ImageEffectsLib.dll TR/Dropper.Gen

### ISSUE THREAD

**Issue by codeeditor** [ShareX/ShareX#954]
Probably false positive report but sending details anyway:
ShareX 10.1
Avira AntiVirus Engine version 7.11.30.172
Detection: TR/Dropper.Gen
File name:
ShareX.ImageEffectsLib.dll
MD5:
731241092749a013481aaa14c165f230
SHA-1:
406a36004988e3fef27104cc0bd940dfc515a594
SHA-256:
4ca487bc719e0504f389fbdc0823bf5b65a48c26bd4527249405b8a7943d4455

Best regards!

**Comment by Jaex** [comment]
It not finds anything here:
https://www.virustotal.com/en/file/70887b7616b4524ee5d79e06ca0e5865f4a8915d8c04e921c0ed8b32e350d7e2/analysis/1440786762/
