### ISSUE TITLE
Private picture on imgur

### ISSUE THREAD

**Issue by lol1572** [ShareX/ShareX#956]
Hey, all my screenshots from ShareX get uploaded to imgur and I noticed that all of them go public (view count increasing). Is there any option to make the pictures private, so nobody can see them unless they get direct link? I also have another concern about this, I accidentally pressed printscreen button and some of my personal information were visible in the screenshot, all of that makes me want to stop using ShareX, unless there is a possibility (maybe other uploading website?) that would make my pictures private after upload,
thanks for help, sorry if my english is unclear

**Comment by Shadorc** [comment]
You can create an Imgur account, set your images as private and associate your account with ShareX

**Comment by Jaex** [comment]
Also you can check History window and from there you can open deletion URL of image you uploaded accidentally.
