### ISSUE TITLE
Bring uploaded image directly to built-in editor

### ISSUE THREAD

**Issue by oldmud0** [ShareX/ShareX#957]
Sometimes I want to put uploaded images through the built-in image editor (forked from Greenshot, our competitor :trollface:), and then upload that edited image back to Imgur.

However, I don't want to have to set the action to "edit image" before taking the picture, as that is tedious and sometimes I take the picture and *then* decide to obfuscate something.

My workaround at the moment is to copy the image's link and then paste it in the Windows open dialog (this downloads the image to the Content.IE5 folder automagically) and then use the "Upload image" button in the Greenshot editor.

However, can there be a button added to the preview dialog (shown after each image is uploaded) or the context menu for each picture to send it to the Greenshot editor?

**Comment by vavavr00m** [comment]
Check the necessary "After capture task(s)"

![ShareX](https://dl.dropboxusercontent.com/s/tve44uq6f4g1kz2/2015-08-30_02-42-14.png)

**Comment by oldmud0** [comment]
That's exactly what I *don't* want to do every time because most of my capture do *not* need editing.

**Comment by Jaex** [comment]
You can do what I do, have different hotkey for editing:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/08/ShareX_HTc5WViIWP.png)

**Comment by oldmud0** [comment]
What if I'm playing a game and want to edit the picture later? Is my workaround the fastest solution to this?

**Comment by Jaex** [comment]
You can right click uploaded item in list and press "Edit image".

**Comment by oldmud0** [comment]
Thanks. So I need to have the image stored locally to have this option? That's okay since I can just use my RAM disk.

**Comment by oldmud0** [comment]
Okay, thanks.
