### ISSUE TITLE
ShareX icon missing from Alt+Tab menu

### ISSUE THREAD

**Issue by davidruhmann** [ShareX/ShareX#958]
Many of the forms (monitor test, drag and drop, region...) in ShareX do not have an icon specified and thus do not display an icon in the <kbd>Alt</kbd> + <kbd>Tab</kbd> menu.

![2015-08-31_13-13-27](https://cloud.githubusercontent.com/assets/2963122/9587339/b36953b2-4fe7-11e5-8b60-fea58e8701a0.png)

Side Node: What do you think about closing the surface selection forms when focus is lost?
* <kbd>Alt</kbd> + <kbd>Tab</kbd>
* <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Escape</kbd>
* <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Delete</kbd>
* etc...

**Comment by Jaex** [comment]
Sometimes I'm starting region capture while region capture already open for be able to take ss from region capture therefore even when focus is lost still I would like it to stay open. Also unintended focus losts can cause issues and people won't know what happened to region capture window. Even if it have advantage it can have unintended disadvantages therefore I won't risk it.
