### ISSUE TITLE
FTP: Uploading to "var/www/html/" issue or feature request?

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ShareX/ShareX#968]
I am unsure what to make of this.

Dreamweaver works correctly uploading to my /var/www/html/ folder and I can access my files from my server's public root directory. (Html aka zizzydizzymc.info/ ).

However while trying to upload with ShareX, it throws my uploads in /user/myusername/var/www/html/ss/ instead of into my public, out-going html folder.

![](http://i.imgur.com/zurShte.png)

Couple things here. 
Is SubFolderPath meaning from the user's directory? If yes then that explains why it's uploading there.

Secondly, if SubFolderPath can't upload to my public html is there a setting I can change to do so?

If the answer is No, Will there be a setting for that in the near future? I kinda need to upload to root and I really don't want to bother with symbolic links because I have my server's folder structure really well organized.

Note: It seemed odd such a well written program like ShareX to not have a root folder option? ( ._.)
I didn't know what to make of it really.  Couldn't understand if I was missing something obvious or if the program really didn't offer this at this time. (And maybe it could sometime?)

**Comment by Jaex** [comment]
ShareX using what is default folder when connected. Did you tried going back with ```../..var/www/html/ss/```?

**Comment by ZizzyDizzyMC** [comment]
Oh I'll give that a try.

**Comment by ZizzyDizzyMC** [comment]
Your suggestion worked great.  Maybe sometime that could be added to the help menu in the program.  (Like when you click somewhere it appears what you can do beside it.)  Otherwise issue closed as the suggestion works as intended.
