### ISSUE TITLE
White bars on the side when capturing active window in multi-monitor setup

### ISSUE THREAD

**Issue by DuckOfDuckness** [ShareX/ShareX#971]
I'm using Windows 10 with 2 monitors that aren't same resolution. If a window is full-screen or maximized, using "Capture active window" will leave white bar(s).
The two monitors are aligned at the top like this: 
![fjylqhv](https://cloud.githubusercontent.com/assets/1951003/9679338/1e2ba782-52ee-11e5-871a-554e4776e957.png)

Screenshots of issue below (open images to see the white bars):

Window is on the big monitor (1):
![qg04kf0](https://cloud.githubusercontent.com/assets/1951003/9679226/0b47a202-52ed-11e5-88e4-4eed17fd76d6.jpg)
Window is on the small monitor (2):
![0ciyab9](https://cloud.githubusercontent.com/assets/1951003/9679291/a78ce17c-52ed-11e5-8d8b-d70f0d946656.jpg)

**Comment by trdwll** [comment]
I'd say the reason is due to different resolutions, I doubt there is anyway to fix this unless you get 2 monitors of the same resolution. However, I may be wrong.

**Comment by davidruhmann** [comment]
This may be fixable with more advanced screenshot sizing logic bases on a quick glance of the code.  Though it will be several days before I can try anything due to holiday weekend.

**Comment by Jaex** [comment]
Are you have transparent capture option enabled?

**Comment by DuckOfDuckness** [comment]
Yup, "Capture window with transparency" is enabled.
![fvih5xs](https://cloud.githubusercontent.com/assets/1951003/9705869/7f829716-54d3-11e5-9a4e-12206010012e.png)

**Comment by Jaex** [comment]
So If you disable it problem solves?

**Comment by DuckOfDuckness** [comment]
If I disable that the problem goes away, yes, but then I'm left without transparency/shadows. I guess I can use this as a workaround until it's fixed. I really like the transparency and shadows though.

**Comment by Jaex** [comment]
Transparency algorithm only works if what you capturing not changing on screen. If it changes then it just returns first taken image and because shadow part is not transparent in that image it can't crop that area when there is no shadow. So I can't fix it. I suggest you to use "Region (Objects)" capture that way you can hover on window and capture it.

**Comment by DuckOfDuckness** [comment]
Okay, I tried using "Capture region (Objects)" and it works for the most part. It doesn't really like full-screen apps though. As you can see in the below screenshot, the bottom is cut off (compare the snowflake in the bottom-left to the other screenshots):
![wht7xdk](https://cloud.githubusercontent.com/assets/1951003/9720966/24823616-5594-11e5-8491-7664706214d5.jpg)
