### ISSUE TITLE
Chrome extension DirectoryNotFoundException

### ISSUE THREAD

**Issue by Jaex** [ShareX/ShareX#973]
I forget to automatically create ```Documents/ShareX/Tools``` folder when enabling Chrome extension support. Normally this folder created automatically when doing screen recording therefore many people won't notice this problem.

If you have this problem you can either start screen recording or create folder manually yourself.

**Comment by MrCD1968** [comment]
This doesn't work for me.

screenshot http://i.imgur.com/RFEBBYD.png

**Comment by Jaex** [comment]
Why your path have lines in it?

**Comment by MrCD1968** [comment]
lines were to block out my name (a user)

**Comment by Jaex** [comment]
So did you created Tools folder there manually?

**Comment by MrCD1968** [comment]
I just create a tools folder but it did not seem to change anything. I closed the program thinking it might "sync" but that was not the case.

**Comment by Jaex** [comment]
How that even possible if you created folder why ShareX gives directory not found error. Are you sure you created folder in correct path?

**Comment by MrCD1968** [comment]
Is this the correct path? http://i.imgur.com/3ZNaQJU.png

**Comment by Jaex** [comment]
If you try to start recording it will ask to download FFmpeg and it will create Tools folder automatically that way you will be sure it is created.
