### ISSUE TITLE
blank space

### ISSUE THREAD

**Issue by blanzh** [ShareX/ShareX#977]
After click to tray icon. Two displays Win10 64x
![](http://n9922.ru/s/u3j47.png)

**Comment by Jaex** [comment]
In your right monitor have taskbar with same height as blank space. Is that taskbar can be causing it?

**Comment by blanzh** [comment]
Yep. Right side is a part of second monitor

понедельник, 7 сентября 2015 г. пользователь Jaex написал:

**Comment by Jaex** [comment]
Because I don't have multi monitor I'm not sure how that taskbar works and is it can be causing that blank space.

**Comment by Scrxtchy** [comment]
I have this issue too.
What I found strage is that it's the same size as the "Windows Pro Build XXXX" watermarks.
Like, the capture form even though it's cropped out for me, so it's a strange issue.

I don't have a taskbar on the bottom of any of my displays

**Comment by ttroutindy** [comment]
I have Windows 10 x64 with two monitors and am not able to reproduce the problem.

**Comment by Jaex** [comment]
If your taskbar stays top on region capture?

**Comment by Jaex** [comment]
Look like pull request #959 caused this issue.

```public class Surface : BaseForm```

When I replace ```BaseForm``` with ```Form``` it fixed.
