### ISSUE TITLE
[Request] Add option to Greenshot to "never save"

### ISSUE THREAD

**Issue by ben-summers** [ShareX/ShareX#980]
I take a lot of one-off screenshots that I either paste into some other program or upload to a hosting service, after which time I no longer care about the image in the editor. Frequently what happens is I find that I have a lot of Greenshot windows open that I'd like to close all at once, but if I've done any edit actions on the image then I have to go through and pick "No" in each of the file save dialogs. In Windows 7 at least, this seems particularly painful because I have to select each one of the windows before I can dismiss the dialog. 

It would be really nice to have a setting that would have the effect of "I never care about the contents of any editor, and if a command is issued to close the window then I'll just close it immediately no matter what."

**Comment by ben-summers** [comment]
I see that this feature is already built in to the code. Maybe it's just not exposed in the menus? I can't find it anywhere. 

Greenshot.ImageEditor\Forms\ImageEditorForm.cs
````cs
if (!editorConfiguration.SuppressSaveDialogAtClose)
                {
                    // Make sure the editor is visible
                    WindowDetails.ToForeground(Handle);

                    MessageBoxButtons buttons = MessageBoxButtons.YesNoCancel;
                    // Dissallow "CANCEL" if the application needs to shutdown
                    if (e.CloseReason == CloseReason.ApplicationExitCall || e.CloseReason == CloseReason.WindowsShutDown || e.CloseReason == CloseReason.TaskManagerClosing)
                    {
                        buttons = MessageBoxButtons.YesNo;
                    }

                    DialogResult result = MessageBox.Show("Do you want to save the screenshot?", "Save confirmation", buttons, MessageBoxIcon.Question);

                    if (result == DialogResult.Cancel)
                    {
                        e.Cancel = true;
                        return;
                    }

                    if (result == DialogResult.Yes)
                    {
                        DialogResult = DialogResult.OK;
                        OnImageSaveRequested();
                    }
                }
                else
                {
                    DialogResult = DialogResult.OK;
                }
````

I see that I can fix it on my own machine by editing the ini file for the program: https://code.google.com/p/sharexmod/issues/detail?id=104#c2

**Comment by Jaex** [comment]
Why you don't use this button? It does exactly what you want. Closing without show anything:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/Xvqhp0ybuZ.png)

**Comment by davidruhmann** [comment]
Expanding upon what ben-summers said about editing the INI

__GreenshotImageEditor.ini__ `%UserProfile%\Documents\ShareX`
> ; Suppressed the 'do you want to save' dialog when closing the editor.
SuppressSaveDialogAtClose=__True__

**Comment by ben-summers** [comment]
Maybe I’m just being hyper-lazy, but I don’t want to click any buttons in the interface. I am talking about using the native “Close all windows” function built in to Windows. This way if I’ve collected a bunch of image editor instances in my task bar then I can just right click the Greenshot taskbar item and kill them all at once without having to visit each one individually and pick “No”.

**Comment by Jaex** [comment]
Well I'm not planning to write ini parser and show settings etc. which is a lot of efforts and i'm very lazy too.

**Comment by trdwll** [comment]
@Jaex, you wouldn't have to write one. There's already a class written. 
See it here http://www.codeproject.com/Articles/1966/An-INI-file-handling-class-using-C

**Comment by Jaex** [comment]
If I used other written classes for everything ShareX would have like 50 different library per uploader and 20 different other thing.

**Comment by trdwll** [comment]
It's like 30 lines of code, not a library.

**Comment by Jaex** [comment]
Oh I didn't know kernel32.dll have function for this.

**Comment by trdwll** [comment]
See http://pastebin.com/wU9ZsgxD

**Comment by Jaex** [comment]
I already saw it.

**Comment by aait** [comment]
I just want to second @trdwll feature request. Have the exact same modus operandi, would be a welcome feature.

**Comment by randygrolemund** [comment]
Whatever happened to this?
