### ISSUE TITLE
Allow chaining of workflows

### ISSUE THREAD

**Issue by Scrxtchy** [ShareX/ShareX#983]
Have a setting in a workflow that would allow a user to start another workflow when the task is completed.
This can allow workflows to execute multiple tasks via one hotkey sequentially, or have workflows repeating themselves if the user really cares ( or doesn't care)

**Comment by davidruhmann** [comment]
Do this already (excluding repeating else endless loop) with custom actions for the hotkey workflow
![2015-09-10_11-58-46](https://cloud.githubusercontent.com/assets/2963122/9794946/9b919046-57b3-11e5-947f-440e35996ba2.png)


Available HotKey types
```
// Upload
FileUpload,
FolderUpload,
ClipboardUpload,
ClipboardUploadWithContentViewer,
UploadURL,
DragDropUpload,
StopUploads,
// Screen capture
PrintScreen,
ActiveWindow,
ActiveMonitor,
RectangleRegion,
WindowRectangle,
RectangleAnnotate,
RectangleLight,
RectangleTransparent,
PolygonRegion,
FreeHandRegion,
CustomRegion,
LastRegion,
CaptureWebpage,
AutoCapture,
StartAutoCapture,
// Screen record
ScreenRecorder,
ScreenRecorderActiveWindow,
StartScreenRecorder,
ScreenRecorderGIF,
ScreenRecorderGIFActiveWindow,
StartScreenRecorderGIF,
// Tools
ColorPicker,
ScreenColorPicker,
ImageEditor,
ImageEffects,
HashCheck,
DNSChanger,
QRCode,
Ruler,
Automate,
IndexFolder,
FTPClient,
TweetMessage,
MonitorTest,
// Other
DisableHotkeys,
OpenScreenshotsFolder
```

**Comment by Scrxtchy** [comment]
Actions are performed before uploading, not on completion/finish upload
Also if you wanted to bring up a multiple amount of tools at once through a chain, for example colour picker, ftp, irc (etc), actions will be bypassed

**Comment by Jaex** [comment]
Workflow system already very complex for people therefore I don't want to make it even more complex. 
In IRC who requested this feature can use actions with explorer /select parameter:
https://support.microsoft.com/en-us/kb/130510
Which will open screenshot folder and select that file automatically. Better than what he wants.
