### ISSUE TITLE
Alphanumeric auto-increment names.

### ISSUE THREAD

**Issue by widget-** [ShareX/ShareX#984]
I'm using ShareX w/ SFTP to upload pictures to my server in short-URL format. However, current auto-increment only supports numbers e.g. {1, 2, ..., 10, ...} .

Would it be possible to add support for alphanumeric autoincrement, e.g. {0, 1, ... , 8, 9, a, ... , z, A, ... , Z, 10, 11, ... } ?

**Comment by davidruhmann** [comment]
`0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`

That sure is an odd way to increment and it would probably have to be case-insensitive (like hexadecimal) since Windows file names are case-insensitive else you would have increment collisions.

Alphanumeric: `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ`
Hexadecimal: `0123456789ABCDEF`

**Comment by widget-** [comment]
You're right on the Windows case-sensitivity. Personally I'd be using it to put things onto a Linux server but I doubt that would be the main use-case for most people. I'm mostly going for bit.ly-style short URLs though.

**Comment by davidruhmann** [comment]
I have implemented this functionality in my branch and wanted some opinions before submitting a pull request.

Digit Scale: `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`
Inverse Digit Scale: `0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`

```
ia  = Auto increment alphanumeric case-sensitive. Pad zeros using {n}
iAa = Auto increment alphanumeric case-insensitive. Pad zeros using {n}
```

Additional entries I developed for myself
```
ib   = Auto increment by base {n} using alphanumeric digits. 1 < n < 63
ix   = Auto increment hexadecimal. Pad zeros using {n}
rx   = Random hexadecimal. Repeat using {n}
guid = Random GUID
```

Entries are case sensitive for additional options.
```
ia  = characters are lower case
iA  = characters are upper case
iAa = uses regular digit scale
iaA = uses inverse case digit scale
ib  = uses inverse case digit scale
iB  = uses regular digit scale
ix  = characters are lower case
iX  = characters are upper case
rx  = characters are lower case
rX  = characters are upper case
guid = characters are lower case
GUID = characters are upper case
```

Example (85743)
```
%i{6}__%ia{6}__%iA{6}__%iAa{6}__%ix{6}__%iX{6}__%ib{58,6}__%rx{3}
085743__001u5r__001U5R__000Mlx__014eef__014EEF__000PSJ__547
```

**Comment by widget-** [comment]
Sorry, wrote a post but then never submitted it...

It looks good to me, but I might worry that there's too many permutations for that little tooltip box. Arbitrary base notation might be overkill.

**Comment by Jaex** [comment]
Also I'm sorry I forget to reply @davidruhmann
In my opinion it is gonna be very overkill filling that commands tooltip with so many combinations :(
Also using {n} padding zeroes would be weird in alpha numeric because it is not just only digits.
And in file namings i don't see point of using hexadecimal when there is alphanumeric.
Also using case sensitive option in { } parameter can save space in this commands tooltip I think?

**Comment by davidruhmann** [comment]
Indeed the additional options seem like a lot.  Just a habit from my day job to cover all scenarios.  Currently, the tooltip itself only shows the base options ia, iAa, ib, ix, rx, guid.  The case options are (implied) behind the scene features that are common with other string formatters in programming languages which have case-sensitive formatting.

The base notation is definitely overkill, but it sure was a nice fun exercise.  Usually just work on ShareX as a stress reliever for my daily programming job.

![menu](https://cloud.githubusercontent.com/assets/2963122/10028960/0bd51032-6135-11e5-8bce-43fe888c33ec.png)

@Jaex So which are the desired options to keep:?

**Comment by Jaex** [comment]
Now when I thinked about how to make these tooltips not complex, using categories could be good way I think. Like how I did in hotkeys:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/27QxBTjpli.png)

Example it could be Time & date, Random, Other categories.
When initiating ReplCodeMenuEntry can have 3. parameter for category. But this can be boring to program. But if you want all of these to be exist then this looks best way to do it :P

**Comment by davidruhmann** [comment]
Categories preview
![categories](https://cloud.githubusercontent.com/assets/2963122/10031012/514cbb46-6140-11e5-90c0-3b711dddadaa.png)

**Comment by Jaex** [comment]
:+1:

**Comment by davidruhmann** [comment]
What category should New Line be under or no category?
![newline](https://cloud.githubusercontent.com/assets/2963122/10031302/146ef020-6142-11e5-9a05-638e9d865b03.png)

**Comment by Jaex** [comment]
No category I think. Because it special thing like \n

**Comment by davidruhmann** [comment]
Sounds good to me :+1:
