### ISSUE TITLE
Ability to application export preferences and settings

### ISSUE THREAD

**Issue by ZanMarolt** [ShareX/ShareX#986]
Title says it all, I could use the feature since I have quite some computers and connecting to all the accounts and fine tune the preferences is pretty time consuming.

Thanks :)

**Comment by Jaex** [comment]
When you can copy files with single click what is point of having export button for it? People can think only way to backup them using export button if I add that. But copying folder which contains settings far more easier.

**Comment by ZanMarolt** [comment]
Where is the folder again? :)

**Comment by Jaex** [comment]
Documents\ShareX
