### ISSUE TITLE
Uploading file to specific MEGA folder "doesn't really work"

### ISSUE THREAD

**Issue by Farfie** [ShareX/ShareX#988]
I put that section in quotes, because it does work, but not fully. This is because when you then use the "get link" feature on the folder, and give it to someone to view the contents, things that ShareX uploaded do not show up. To get them to show up, I have to move them out of that folder, and back inside again. Then they will show up with the -same- generated link.

At first I thought this was a MEGA bug, since fixing it only involved moving files around with nothing to do with ShareX. Plus, most APIs are pretty simple, how could you mess it up (not that I'm very experienced or anything, but in the bit that I've dabbled, it was easy)?

Well, I sent an email to MEGA with my problem, and to keep this short, they basically said it was that "ShareX is buggy."
![p3ph2x](https://cloud.githubusercontent.com/assets/2372953/9836411/b3e7fc0e-59e6-11e5-84de-e136c25caab9.png)

**Comment by Jaex** [comment]
"Plus, most APIs are pretty simple, how could you mess it up (not that I'm very experienced or anything, but in the bit that I've dabbled, it was easy)?"

You must be joking? Most of the things was not even documented in their API doc page. It is probably most difficult API compared to 50+ uploaders implemented in ShareX.

**Comment by gpailler** [comment]
Hello @Farfie. The bug you reported is not related to ShareX but the MegaApiClient library. Can you create a bug on https://github.com/gpailler/MegaApiClient please?

There is probably something missing in the library to have the file accessible through shared link (after the shared link is created) but as @Jaex said, Mega API is not documented so it's lot of work to handle all cases.

**Comment by Farfie** [comment]
@Jaex Well, I said most API's are pretty simple, or at least they seem simple. I'm not an expert, but I don't think what I said was wrong, especially since MEGA seems to be an exception... It would explain why we're having problems. Sorry I didn't dig into it deeper before posting, but I don't really have time to do too much other than everything I'm already doing.

@gpailler Will do that, thanks.

**Comment by gpailler** [comment]
This issue should be fixed with MegaApiClient v1.1.2
