### ISSUE TITLE
Full Page Screenshot

### ISSUE THREAD

**Issue by Maggew** [ShareX/ShareX#992]
Nimbus (a popular browser addon) offers this functionality along with a few websites.

http://ctrlq.org/screenshots/
https://addons.mozilla.org/en-US/firefox/addon/nimbus-Screenshot/

Will ShareX offer this functionality? I believe this feature is a wicked idea.

**Comment by Jaex** [comment]
Isn't what you want exist already in Capture menu? If you want it in Chrome extension then I can't make it because I'm not web dev.

**Comment by Maggew** [comment]
Roger roger...

Capture > Webpage Capture
