### ISSUE TITLE
Change Capture > Webpage capture Default Browser

### ISSUE THREAD

**Issue by Maggew** [ShareX/ShareX#993]
I've double-checked that Firefox (but also tried with Chrome) has all it's defaults. 
When I use the Capture > Webpage Capture Feature the default browser being used is IE. 
```
Control Panel\Programs\Default Programs\Set Default Programs
```
*I believe this is an operating system bug.* After testing this url "https://github.com/ShareX/ShareX/issues/new" with ShareX Webpage Capture I received an image like this:

![sdsrh5q](https://cloud.githubusercontent.com/assets/1291364/9908188/7d8083f8-5c60-11e5-968a-77f53f45a4d3.png)

Do you think the default Windows 7 Internet Explore 7 or 8 version is being used?
I have IE 11 installed too.

**Comment by McoreD** [comment]
Hi @Maggew thank you for your issue submission. We use https://msdn.microsoft.com/en-us/library/system.windows.forms.webbrowser(v=vs.110).aspx to implement built-in webpage capture support in ShareX. Unfortunately WebBrowser class only supports Internet Explorer. You are encouraged to use other methods to capture webpages with other browsers. We have a wiki page for this purpose: https://github.com/ShareX/ShareX/wiki/Capture%20webpages%20using%20browser
