### ISSUE TITLE
Chrome App upload images to Amazon S3 randomly even though Imgur is configured properly

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#998]
If I use the Chrome app to upload an image through ShareX, the app randomly switches between Imgur and Amazon S3. I had to disconnect my S3 account to push it to stick with Imgur! Not sure how this behavior can be replicated but was happening a lot when I had both accounts configured.

**Comment by Jaex** [comment]
Only reason it can be you enabled this?:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/ShareX_bFfdVURsmp.png)

**Comment by Sushubh** [comment]
I do not seem to have this setting enabled. I would turn on S3 again and see if I can make it happen again. 
![sharex_-_application_settings_2015-09-18_16-49-34](https://cloud.githubusercontent.com/assets/310098/9958219/5cecf790-5e25-11e5-94ff-2a1d79251e28.png)
